### ISSUE TITLE
Upload New LIVD Table

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#10010]
## Problem statement

New LIVD Table out

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] ...

## To do

to be uploaded[https://app.zenhub.com/files/304423150/853c73e3-bf4a-4a1e-87ff-a9322fcfde4d/download](https://app.zenhub.com/files/304423150/853c73e3-bf4a-4a1e-87ff-a9322fcfde4d/download)

**Comment by LaFreda1** [comment]
@Jcavallo7 will you clarify what's needed for this ticket? Thanks

**Comment by Jcavallo7** [comment]
to be uploaded to staging and prod

**Comment by jalbinson** [comment]
Is the attached file the same as the latest (2023-06-14) on the CDC website? The file name is changed to something internal to Zenhub.

**Comment by jalbinson** [comment]
I loaded this table to my local environment with the master branch but it caused smoke tests to fail with the following error:
```
Invalid column name TestType specified for lookup table LIVD-SARS-CoV-2.
```

I am currently investigating with @oslynn on seeing what our current version of the LIVD table is and if the right one is currently active on prod.
