### ISSUE TITLE
Content update(s): Homepage

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10021]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. The existing homepage content does not align with message we are currently communicating out and should be updated.

## Background & context

- As we prepare to make more comprehensive changes to the website, we want to update the homepage in a low-lift way so that it reflects ReportStream more accurately for the next two months. We will be directing people to our website for more information in that time, so the homepage would be a good place to have some accurate content for the next 2 months as we await larger updates.
- [Existing 1-pager](https://docs.google.com/document/d/1YT20rO5gAyJUqph9RdLz4heceJ72MNFi0ySSwRCPPmA/edit)

## Scope
- Content-focussed changes, no new images
- No large formatting/component changes
- Stay within the existing format/content blocks
- Adding a button or two (call to action) is okay, but no new components beyond that

## Open questions
-   Does Engagement want us to direct potential senders (in this weird flux time) to the onboarding form?
-   ...

## Working links
-   ...

## Acceptance criteria
- [ ] Provide a content update that stays within the scope (above) and encompasses the following:
  - [ ] Content that more accurately aligns with our existing 1-pager and core model outline for a new homepage
  - [ ] Surfaces a more direct way for a potential sender to fill out the existing onboarding form
  - [ ] Instructs potential users above the fold with a call to action if they are interested in joining ReportStream
- [ ] Review with PO for efficient handoff to engineering 
-   [ ] Update service blueprint with relevant learnings
-   [ ] Update the [questions pool](https://docs.google.com/spreadsheets/d/1THH9Ekj5renvIwSpl-6SzzyUJ5tuNcH76l4GTiboQXE/edit#gid=0) with any questions that came up
-   [ ] ...

**Comment by chris-kuryak** [comment]
@audreykwr @jillian-hammer I added some scope and specific ACs to guide this quick content update. Let me know if this aligns with what you were thinking or not.

**Comment by audreykwr** [comment]
@chris-kuryak thanks! looks good to me

**Comment by Andrey-Glazkv** [comment]
@audreykwr if you could please update the number of points

**Comment by audreykwr** [comment]
@chris-kuryak new content approved [here](https://docs.google.com/document/d/1pE3WUcrH0cyv6vcfM5UL-n1Xfqt75ao9mx80c73G3fQ/edit?usp=sharing) Let me know how you want to review for handoff
