### ISSUE TITLE
Content update draft: Getting started - Sending data

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10024]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

- After completing basic outlines for key pages and IDing the new site structure, we need to create the actual content that will go in the wireframes.

## Working links
-   [draft outline](https://docs.google.com/document/d/1NYs6i5C6IYTlsrdcsOS_2E2yUGLczXaZF7sVZdfziMI/edit#heading=h.nw4v6eftyjbz)

## Acceptance criteria
-   [ ] Update service blueprint with relevant learnings
-   [ ] Update the [questions pool](https://docs.google.com/spreadsheets/d/1THH9Ekj5renvIwSpl-6SzzyUJ5tuNcH76l4GTiboQXE/edit#gid=0) with any questions that came up
-   [ ] Content plans discussed with content owner
-   [ ] Drafted started and reviewed with content owner and/or SME

**Comment by audreykwr** [comment]
@jillian-hammer updated with detail and to reflect scope

**Comment by jillian-hammer** [comment]
@audreykwr seen, thank you!

**Comment by audreykwr** [comment]
[Draft in review ](https://docs.google.com/document/d/1cjj9zI_EeYZuvvL2nTY_SKiwLcxZmEnD35I9P-_z1oU/edit#heading=h.nw4v6eftyjbz)so closing
