### ISSUE TITLE
Assess existing Detail page(s) to see if we can define a template

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10026]
## User story

As a WebX team member, I want to see the ReportStream website designed iteratively, starting from blockframes, so that the team can continuously align on the scope and anticipate design/content/engineering needs early in the website redesign process. 

## Background & context

The WebX design team creating blockframes for the new ReportStream website redesign. We will work in a templated approach in an effort to streamline designing pages that have a similar format. The **detail page** page template will use the [TBD page] as a basis for blockframing. These explorations in a lo-fi blockframe format allow us to explore different solutions and align on an approach across disciplines prior to moving farther into the design process.

## Open questions

-  At what touchpoint(s) should content review? 

## Working links

-   Figma: [Blockframe working space](https://www.figma.com/file/86JATe4hOwPfihwwloM5b8/Blockframes?type=design&node-id=0%3A1&mode=design&t=DbHTHvihgkt9JfRE-1)
-   [Site update plan ](https://docs.google.com/spreadsheets/d/1xhnqSoRBfkVFrLR6sgM6QgW1kav7g_FyUkPykPIjOMk/edit#gid=0)

## Acceptance criteria
- [x] Compile a list of all pages we refer to as "detail" pages (existing and new)
- [x] Blockframes capture general layout of content on existing detail pages
- [x] Review with design and/or design lead

**Comment by jillian-hammer** [comment]
Labeling as `needs-info` will connect with @audreykwr on what detail page(s) might be good candidates for this

**Comment by jillian-hammer** [comment]
Update per 1:1 with Tshering today: 

- @yudonoodles will be owning this piece of work, unassigned myself
-  @yudonoodles will assess which detail page(s) may be good representative candidates to blockframe

**Comment by yudonoodles** [comment]
Based on the site update plan, examples of what Detail pages look like are the following pages that already exist:

- [Where we're live](https://reportstream.cdc.gov/product/where-were-live)
- [Security](https://reportstream.cdc.gov/resources/security-practices)
- [Release notes](https://reportstream.cdc.gov/product/release-notes)
- Date requirements and preferences
- [Refer labs and reporting organizations ](https://reportstream.cdc.gov/resources/referral-guide)
- [Frequently Asked Questions](https://reportstream.cdc.gov/support/faq)

An outline for the following is not available, but is considered as a Detail page: 
- Case studies
- News

**Comment by jillian-hammer** [comment]
thanks for compiling @yudonoodles – do you have a recommendation on which page(s) to blockframe based on your assessment?

**Comment by yudonoodles** [comment]
Just compiled the list, will review the pages tomorrow. Speaking of which, can you share the link for "Data requirements and preferences"? I can't find anything with that title. Site update plan states that it exists.

**Comment by audreykwr** [comment]
Ah yes, I think that's referencing this existing page: https://reportstream.cdc.gov/resources/elr-checklist

**Comment by audreykwr** [comment]
I would also add that there are probably pages in the API guide that qualify and may be good candidates for this as they are newer, but I did not list them individually in the site plan sheet

**Comment by jillian-hammer** [comment]
yes, that's a subsection in the ELR onboarding checklist: https://reportstream.cdc.gov/resources/elr-checklist#data-requirements-and-preferences

**Comment by yudonoodles** [comment]
Created a new ticket for tracking the two new detail pages. See here [10266](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/10266)

**Comment by yudonoodles** [comment]
Made updates based on design feedback. Reviewed by Jillian and Audrey. Ready to close.
