### ISSUE TITLE
Meet with CSTE ELR Group 

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#10033]
Muktha Natrajan suggested we reach out to Nicole.Kikuchi@flhealth.gov who is part of CSTE's ELR team to see about getting on the agenda at the next CSTE meeting.

**Comment by LaFreda1** [comment]
@GilmoreA6 Have you been meeting with the CSTE group? What exactly do we need from them? Do it need to be ticketed?

**Comment by GilmoreA6** [comment]
@LaFreda We did meet with them early on in the process. This ticket can be closed.
