### ISSUE TITLE
Authentication Enhancements and Discovery

### ISSUE THREAD

**Issue by dylansmith-Nava** [CDCgov/prime-reportstream#10035]
## Background and Context 
From Mo: Our current authentication provider is Okta, which has served us well, but as we move into other functionality and workstreams we will need to be able to add additional third-party authentication providers. This is going to be necessary as we think about supporting ETOR and other potential CDC projects in the future. 

Furthermore, there could be concern among some security officers in the CDC in the future about the use of Okta. It may not be necessary for us to migrate off of the service entirely, especially not in the short-term, it would be good future-proofing if we abstracted out our security model. 

**Objective** 
Determine what it would take to abstract our authentication layer out so we can integrate with both SAMS, AMS, and Microsoft authentication.

See more [here](https://docs.google.com/document/d/1mHy9D9WH-pe1xf4mw6u6FKsojiK9vDdIdgTGnmdchDk/edit#heading=h.fuuv4bjliube)

## Value Proposition 
- Understanding what each current authentication platform capability(s) are in order to outline gaps we may need to fill in the future
- Supports scaling by taking an abstraction approach our authentication model so we accommodate new types of data in the future
- Potentially allowing new users to register, identity proof, and authenticate themselves as part of a self-service model
- Limiting RS risk of sending incorrect or harmful data to our end users (receivers)

## Impacted Objectives and Key Metrics (OKRs) 
TBD - suggestions:
- Define "user self-service registration", how it's measured, establish baseline
- Define “new user security protocols and identity management strategy”
- Sender can onboard through registration/sign-up process without an engineer
- Reduce average support tickets by [x]% / reduce the need for Sharon’s team’s involvement

## In Scope 
Answering the above open questions by:
- Defining authentication and identity verification and validate with the team
- Researching our current use of Okta as well as what additional options Okta offers for authentication and identity verification
- Researching SAMS, AMS, and CDC AD to understand what they offer 
- Listing open questions 
- Listing advantages and disadvantages of each authentication platform
Considering process flows from other PRIME projects such as:
- New Sender sign-up and validation for Simple Report (SimpleReport does identity proofing for facilities who report data via their site)
- New Sender sign-up and validation for NBS
In addition:
- Outlining questions for Mo
- Outlining questions for CDC experts
- Listing ETOR requirements/needs, if any
- What level of ID proofing is needed for RS in the near term, and long term?
- What solutions to ID proofing meeting those needs/requirements?
- What is needed to prove ID for RS?

## Out of Scope 
- Comprehensive ReportStream authentication and identity verification strategy
- Wireframing and prototyping of what RS self-service registration could look like 

## Users
- STLTs
- Senders
- ReportStream Admins
 
## Outcome-oriented deliverable
- Aligned definition of Identity Verification as it relates to the ReportStream product and why it is necessary
- What our users and partners believe is needed from an Identity Verification perspective
- Potential solutions for Identity Verification (including potential 3rd party services) based on what our users and partners believe is needed

**Comment by dylansmith-Nava** [comment]
@lizzieamanning new authentication epic! Hopefully I did this correctly & let me know if you have any questions / comments!

**Comment by lizzieamanning** [comment]
This looks right to me! I added the link to the design brief. We can now add your related tickets to this epic @dylansmith-Nava

**Comment by dylansmith-Nava** [comment]
This discovery epic has reached its conclusion as the strategy for at least Q3 - Q4 2023 has been set. As such, finalizing this epic and moving it to done. @chinelo-ikejimba
