### ISSUE TITLE
CA requesting removal of filter

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#10042]
## Problem statement

CA wants to receive all Covid antigen tests

## What you need to know

CDPH is requesting a full rollback of a previous change. We would no longer like any non-positive covid antigen results blocked from reaching us.

## To do

- Remove filter of non- positive antigen test

**Comment by LaFreda1** [comment]
This ticket is referring to ticket 9380. I will ask Don to look into it

**Comment by LaFreda1** [comment]
Hey @cloudmagic80 When we met with CA, they asked us to reverse what you did for ticket 9380. Will you complete this? Thanks!

**Comment by cloudmagic80** [comment]
https://github.com/CDCgov/prime-reportstream/pull/10291/files

@adegolier  @victor-chaparro  I made the pull request. Once I get a positive review, I will merge into master.
