### ISSUE TITLE
Add the PII information into our markdown files

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1004]
Currently we have a boolean pii field in our per-element descriptions in our schema and in Element.kt, but it is missing from our .md files.  This task is to make the pii value show up in the markdown.

Def of Done:
[ ] In the markdown files, all element fields in all schema .md files show pii value.  Use 'Yes', 'No' instead of true/false, for readability. . (Current default is false)
[ ] re-run ./prime generate-docs and include those updates in the PR.
[ ] check with Carlos, he's working on html generation.  If he gets his PR in first, then add PII to the html as well.

This is meant to be a starter task.

**Comment by pathikkothari** [comment]
pathikkothari: I am working on this one

**Comment by jimduff-usds** [comment]
@pathikkothari - this is done, true?

**Comment by jimduff-usds** [comment]
@pathikkothari - any status update on this?

**Comment by pathikkothari** [comment]
@jimduff-usds Yeah, PII was added to Markdown files and merged in last week.
