### ISSUE TITLE
RCA for outage June 21

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#10056]
Please add an RCA doc to discuss at Monday's eng. sync

[Add doc here](https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FOperations%2FOutage%20RCAs&viewid=17db3ff6%2D95c5%2D4562%2Da1f3%2D12b5097b5947)

**Comment by lucasdze** [comment]
Document uploaded https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B7E3F7E20-2E1D-49ED-BD50-D1AC1983489F%7D&file=Production_short_down_time_06-21-2023.docx&action=default&mobileredirect=true
