### ISSUE TITLE
SPIKE: Investigate Okta Multiple Brands

### ISSUE THREAD

**Issue by jpandersen87** [CDCgov/prime-reportstream#10064]
## Problem Statement
After our last investigation into what is needed for migrating Okta instances #9441 revealed more questions that need to get answered.

## What you need to know
- [Okta Research Notes](https://docs.google.com/document/d/1lPCVpzU9tqdESWxOyU9KqxOr-Tlax0SVe7u79bTYz2g/edit#heading=h.5d3xmmoa5n8j)
- [Okta Process Mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1681921545021/4b0bdcdfb84b03a3a7b0a90741c9dab5c1e3abd6?sender=u788ba8e0ebf56a2ad7d18905)
- ...
## Acceptance Criteria
Answers to the following question in the Okta Research notes:
- [x] How does self-service work under multiple brands?
- [x] How are applications associated with these brands?
- [x] Are there any special requirements (ex: custom domain) to use?
And review results with:
- [x] Chris and Keith

**Comment by jpandersen87** [comment]
A custom domain must be associated with brands beyond the default (the default associates the xxx.okta.com domain). This is how the branding is properly determined. Custom domain association requires making changes at the DNS/Domain level to facilitate this.

**Comment by chris-kuryak** [comment]
Meeting scheduled for Wednesday. Closing ticket.
