### ISSUE TITLE
Fix storage of incoming ingested files

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1010]
When we ingest a file in the ReportFunction, we store a copy of it, in our blobstore.    The problem is that we store it in the wrong version.  The writing to the blob store of the internal version is done to write an action history.  The recommendation is to change the writing of the action history, so we write the raw data received from a sender and use that blob to write the action history.

We need to store the file exactly as it is sent to us, and instead we store it in our "INTERNAL" format.

This task is done when:
Instead of storing the INTERNAL format of the file, we store the file exactly as it is sent to us, byte for byte.  No reason to also store the INTERNAL formatted file.
Other features continue to work as before:  eg, the report is associated with the lineage, it shows up properly as a 'parent' in the report_lineage table, the 'blob_digest' is correct.

Acceptance criteria:
1. The raw received data is written to the blobstore with a proper file extension (e.g. CSV or HL7).
2. The internal version of the received data is no longer saved to the blob store.

**Comment by jimduff-usds** [comment]
Hi Pathik, any progress on this?

**Comment by pathikkothari** [comment]
I generally work on these tasks from Tues-Thurs unless it's urgent or have nothing else going on.  Not that far yet but should be able to complete it in a day or two.

**Comment by pathikkothari** [comment]
Just an update......after making the changes...I was still seeing internal format being sent to the Azure Blob Storage (Azure Storage Explorer locally) and report file table in Postgres last week.  I believe I have made all the Internal format related changes so not sure where exactly it was coming from.  I will have to debug more.

**Comment by jimduff-usds** [comment]
Pathik,

There are lots of steps that should and do create the .internal format.   _Only the very first creation of the received file needs to be modified_.    All others should remain as .internal.

Jim

**Comment by jimduff-usds** [comment]
For example, if you submit a file with 10 rows and 5 go to NJ and 5 go to MD, then the receive step will create 3 files.

The 5 to NJ, and 5 to MD should both be .internal.    But we also want to store the 10-record original data, exactly byte for byte as it appeared in the payload.   That's the bug, right now we are storing an 'internal' representation of that data, instead of storing it exactly as it was sent to us.

**Comment by jimduff-usds** [comment]
@tlosbo please check with Pathik, and take this issue over.  Thanks!

**Comment by tlosbo** [comment]
@pathikkothari do you have a branch that I can view to see how far you got with this? I can take over from there.

**Comment by pathikkothari** [comment]
@tlosbo I do have a branch that I haven't checked in.  It might be better to start on a clean branch since I might have changed things that might need to there.  It seems like we need both internal and original formats.  Testing was tedious.....let's sync up and see if it would make sense for you to work on top of it or work on your own branch.

**Comment by tlosbo** [comment]
> @tlosbo I do have a branch that I haven't checked in. It might be better to start on a clean branch since I might have changed things that might need to there. It seems like we need both internal and original formats. Testing was tedious.....let's sync up and see if it would make sense for you to work on top of it or work on your own branch.

I find some time on the calendar to meet on it.

**Comment by carlosfelix2** [comment]
This was implemented as part of #1416
