### ISSUE TITLE
bug: Triage end2end tests failing consistently

### ISSUE THREAD

**Issue by JFU-NAVA-PBC** [CDCgov/prime-reportstream#10100]
## Describe the bug
During my recent work on local dev setup, the end2end tests consistently failing on several tests (see below trace):

========== ./gradlew testEnd2End trace excerpt ================
Polling for ReportStream results.  (Max poll time 480 seconds)
Test end2end finished in 510 seconds
Test passed: for ignore.CSV action receive:  Expecting 5 item lineage records and got 5
Test passed: for ignore.CSV action batch:  Expecting 5 item lineage records and got 5
*** TEST FAILED*** for ignore.CSV action send:  Expecting 5 item lineage records but got 0
Test passed: for ignore.HL7 action receive:  Expecting 5 item lineage records and got 5
Test passed: for ignore.HL7 action batch:  Expecting 5 item lineage records and got 5
*** TEST FAILED*** for ignore.HL7 action send:  Expecting 5 item lineage records but got 0
Test passed: for ignore.HL7_BATCH action receive:  Expecting 5 item lineage records and got 5
Test passed: for ignore.HL7_BATCH action batch:  Expecting 5 item lineage records and got 5
*** TEST FAILED*** for ignore.HL7_BATCH action send:  Expecting 5 item lineage records but got 0
Test passed: for ignore.HL7_NULL action receive:  Expecting 5 item lineage records and got 5
Test passed: for ignore.HL7_NULL action batch:  Expecting 5 item lineage records and got 5
*** Tests FAILED:  end2end ***

> Task :primeCLI FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':primeCLI'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9m 4s
6 actionable tasks: 2 executed, 4 up-to-date
=================== end trace excerpt ===============

## Impact on ReportStream
Need to find out the root cause of the 3 tests, fix if they are cause by any recent changes

## Steps to reproduce
1. Go to report stream local repo
2. Setup a local dev report stream instance by following : https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting-started/getting-started.md
3. After ./cleanslate.sh successfully finished, check report stream and supporting services are up and running
4. Might need to run ./gradlew reloadTables and ./gradlew reloadSetting to avoid tests termination due to schema loading error
5. run ./gradlew testEnd2End
6. 

then should be able to see the test failures.

## Expected behavior
A clean run of end2end tests with all tests passing

## Resources
None

## Logs
See stdout in first section

#### Desktop (please complete the following information)
 - OS: Mac, WSL2, Linux
 - Browser NA
 - Version NA

## Additional context
Add any other historical context about the problem here.

**Comment by bishoyayoub** [comment]
@JFU-NAVA-PBC Please confirm that this is ready for grooming.

**Comment by JFU-NAVA-PBC** [comment]
@bishoyayoub yes

**Comment by bishoyayoub** [comment]
@JFU-NAVA-PBC Please use #4932 to use the terminology "As a [User Persona - who are we building this for?]
I want to [Intent - what is this user trying to achieve?],
so that [Outcome - what is the value add to the user]."

**Comment by JFU-NAVA-PBC** [comment]
@bishoyayoub I used the bug template since the test failure could be due to my local setup, or it could be a real problem.

**Comment by JFU-NAVA-PBC** [comment]
@bishoyayoub @arnejduranovic After going through the "Dev get started" docs, I noticed that this is false alarm.

Fixed the SFTP permission stuff, and all smoke tests passed.

I'll close the ticket
