### ISSUE TITLE
Support Team Training Resources: Receiver Settings

### ISSUE THREAD

**Issue by jakefishbein-navapbc** [CDCgov/prime-reportstream#10108]
## User story

As a member of the support team, I need to be able to adjust receiver settings, so that issues do not need to be escalated to tier 2. 

## Background & context

Research into our support process revealed an opportunity to reduce the number of support tickets that need to be escalated from Tier 1 to Tier 2. This involves training support staff to resolve receiver requests to change their settings (filters and translations). This ticket aims to provide support staff with training resources that will help them address these types of tickets.

## Open questions

-   What information do support staff need to know in order to change receiver settings?
-   What format(s) will be most effective at teaching support staff this information?
-   How can we determine the effectiveness of these training materials?

## Working links

-   [Onboarding to RS: Technical Settings Questions](https://docs.google.com/spreadsheets/d/1xAfkzPqs4yA3tAdXW4JShtENTZW_kSW6rlH_Hjx-glI/edit#gid=206627954)
-   [Receiver Filters](https://docs.google.com/document/d/1WOExzF-52FYOd6Q09DWdC3Dt6C4WvdKNJnRIAFKiWs4/edit)
-   [Discovery Notes](https://docs.google.com/document/d/15XxIBG8v1RAa9nuTJtxLpvvtSn6zm6LOhoSDN9Sxx_I/edit#heading=h.hhevn0icya3z)

## Acceptance criteria

-   [ ] Update service blueprint with relevant learnings
-   [ ] Update the [questions pool](https://docs.google.com/spreadsheets/d/1THH9Ekj5renvIwSpl-6SzzyUJ5tuNcH76l4GTiboQXE/edit#gid=0) with any questions that came up
-   [ ] Training Resources TDB

**Comment by jakefishbein-navapbc** [comment]
Discussed the proposed solution with Ott. Determined with was not feasible due to the complexity of testing configurations and the high level of risk associated with any mistake. See [notes](https://docs.google.com/document/d/15XxIBG8v1RAa9nuTJtxLpvvtSn6zm6LOhoSDN9Sxx_I/edit) for additional information.

**Comment by jakefishbein-navapbc** [comment]
First session is being pushed a week to the 28th so Ott has more time to prepare.

[This is a revised outline of the the entire sequence of trainings.](https://docs.google.com/document/d/11C8v1qg6bSUc7133xu-Y1fXzxF2Nu-4nbr3E0VikmUo/edit?usp=sharing)

**Comment by oslynn** [comment]
Resources: 
HL7 message Validation Sample file. 
1.) junk/base10genetics/SampleFromBase10/ReportStream-Report-11932-20230326-testing.hl7   - Failed validation
2.) junk/base10genetics/SampleFromBase10/ReportStream-Report-11932-20230326-with-correction.hl7

**Comment by sliu1000** [comment]
[https://app.zenhub.com/files/304423150/4e506c08-602c-424b-a93a-5578a2676af0/download](https://app.zenhub.com/files/304423150/4e506c08-602c-424b-a93a-5578a2676af0/download)

**Comment by oslynn** [comment]
Completed modules 1, 2.  I will start module 3 tomorrow
