### ISSUE TITLE
Refactor and Remove hardcode URL dependency from the RESTTransport

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#10119]
The RESTTransport sets the message body for POST command using hardcode URL ending (i.e /HL7, /demographics, /elr, else).  This will lead us to keep changing the code when STLT's URL changes.  We want to move the dependency out to the setting to prevent changing the code when  STLT's URL changes. 

Refactor out to individual Receiver as a plugin.

**Comment by chris-kuryak** [comment]
Depends on #12802

**Comment by oslynn** [comment]
This ticket includes the design of the new RESTTransport as well.

**Comment by oslynn** [comment]
@victor-chaparro.  I think this ticket is done since all URLs have moved out from the transport code and replaced with standard REST header Content-Type info such as text/plain, text/application, application/json, and multipart/form-data.  Therefore, we can close this ticket.
