### ISSUE TITLE
UP Core Functionality: Condition Mapping

### ISSUE THREAD

**Issue by brandonnava** [CDCgov/prime-reportstream#10149]
Definition of work: building condition code mapping logic to properly identify and route the appropriate condition
User value: code mapping is crucial to ensuring the receiver understands what condition has been sent to them
Linked dependencies and appropriate labels: Engagement driving, platform label applied for visibility
Outcome-oriented deliverable: mapping solution implemented

**Comment by GilmoreA6** [comment]
duplicate with #10149 or #9177

**Comment by MikaelahD13** [comment]
Closing, work completed.
