### ISSUE TITLE
UP Core Functionality: Translation Settings

### ISSUE THREAD

**Issue by brandonnava** [CDCgov/prime-reportstream#10144]
Definition of work: Creating translation settings (filters) to help route the data
User value: There are a few key filters the data must run through to ensure the message is formatted correctly and goes where it needs to. Translation settings are a part of that set of filters. 
Linked dependencies and appropriate labels: Engagement driving this but platform label also applied for visibility
Outcome-oriented deliverable: functioning settings akin to those we built for the covid pipeline

**Comment by brandonnava** [comment]
Problem definition can be seen in the 'Summary' section of our user requirements plan here: https://docs.google.com/document/d/1Lgkp1oHvr_KhuiXDy0gepAU0U9DKlAOmaTzVaybFZ2M/edit?usp=sharing
Brief version mentioned as 'user value' in the write up at the top of this epic

**Comment by MikaelahD13** [comment]
Closing, work completed.
