### ISSUE TITLE
Document Sender & Receiver Requirements for Onboarding to the UP

### ISSUE THREAD

**Issue by brandonnava** [CDCgov/prime-reportstream#10154]

**Comment by jakefishbein-navapbc** [comment]
[Mural](https://app.mural.co/t/nava4113/m/nava4113/1689691668005/977bc208d332372cb6123a98c8054e5de89cd202?sender=u1cb5f3c6aed590b290728229)
[STLT Transform Analysis](https://docs.google.com/spreadsheets/d/1cdCVZfQrF7rs6Kjs4ihcbpaBW2bZpQ4aw3-jwiZKMt0/edit?usp=sharing)

**Comment by jakefishbein-navapbc** [comment]
Final Report[https://docs.google.com/document/d/1jprkuy6FfDY0Z2CsnKQNim6Brs5gh3_IIOUb0uDdR8g/edit?usp=sharing](url)

**Comment by brandonnava** [comment]
Mural linked above updated with lightweight wireframe of what to put in a self service UI for user requirements. Ready to be picked up at a future date when ready for build out

**Comment by brandonnava** [comment]
Slide deck version walking through the UI with more details for implementation here: https://docs.google.com/presentation/d/1hqlz7F4LwBu9A0LSX4LmJakSctndOxmLrapaGlkwoUI/edit?usp=sharing
