### ISSUE TITLE
Full home page content: draft 1

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#10168]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

- We completed low-lift content updates to the home page and now we need to continue to develop the content for the more holistic changes needed. 

## Working links
-   [Low-lift updates](https://docs.google.com/document/d/1pE3WUcrH0cyv6vcfM5UL-n1Xfqt75ao9mx80c73G3fQ/edit)
-   [draft outline](https://docs.google.com/document/d/1L6vIwjZxOJ-w8Uc142Xop4pS0pZbVW0RIVf-BOwTDro/edit#)

## Acceptance criteria
-   [ ] Update service blueprint with relevant learnings
-   [ ] Update the [questions pool](https://docs.google.com/spreadsheets/d/1THH9Ekj5renvIwSpl-6SzzyUJ5tuNcH76l4GTiboQXE/edit#gid=0) with any questions that came up
-   [x] Content plans discussed with content owner
-   [x] Drafted started

**Comment by audreykwr** [comment]
@jillian-hammer @chris-kuryak follow on to continue work on the home page past the quick updates

**Comment by jillian-hammer** [comment]
love it thanks for clarifying @audreykwr

**Comment by audreykwr** [comment]
[Drafting here](https://docs.google.com/document/d/1MWrWzRKvsTVqGXbn8PcdQSV2BAxDDsSyq7KQJ-yWnb4/edit)
