### ISSUE TITLE
[BUG] Public Key Tool produces error when it should not

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#10178]
## Describe the bug
User received an error when uploading an Public Key File (.pem) to the Public Key File Tool.
The file was successfully received through the addKey API endpoint, so it appears this is a front-end issue.

## Impact on ReportStream
All onboarding senders can use the Public Key Tool.

## Steps to reproduce
1. Log in to ReportStream as a sender
2. Go to https://reportstream.cdc.gov/resources/manage-public-key
3. Add the key file (get file from Chris Kuryak)
4. Error appears
5. However, when using the addKey endpoint directly, the file is accepted

## Expected behavior
The error should not appear. The file should be accepted by the tool without error.

## Resources
- Here is the error screen:
![image (1).png](https://images.zenhubusercontent.com/637d310dba428f3e3d55c9db/51708f8a-dbf8-4111-a46f-4bc161a56ad7)#### Desktop (please complete the following information)

## Additional context
- This bug was found by Ott, so contact him for details if needed

**Comment by penny-lischer** [comment]
Not able to reproduce locally. Ott will try as well and get back to me.

**Comment by chris-kuryak** [comment]
Thanks @penny-lischer !
Per our discussion, it appears there IS a method for removing the PK via command line interface. And since this issue cannot be reproduced and it is working for other folks, we will wait until it happens again to try and troubleshoot it.
