### ISSUE TITLE
[Research] Optimize build-frontend workflow

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#10177]
This point of this ticket is to find ways to get the build / deployment time down for the frontend application. The goal is to either recommend or introduce an updated workflow based on our experiments and findings. 

Engineering work does not "Build" in this case
Build - What you do locally. Packaging the code so it can be deployed.
Deployment - Getting the code onto server for public access.

Deployment currently takes ~10 minutes

Benefit:
- Shortens the feedback cycle (waiting by engineers)
- Shortens the actually deployment cycle: Going from ~10min to ~4min
- 

Notes:
- Currently always running tests on every build. Add some flexibility as to when to the run tests
- Caching Dependencies
- Workflow is one big action, better to break up things to run in parallel

**Comment by chris-kuryak** [comment]
@KeithNava to come back to this and flesh it out for more information and how we want to track this work moving forward.

**Comment by jpandersen87** [comment]
See: #14324
