### ISSUE TITLE
Content update draft: Getting started

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#10170]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

- After completing basic outlines for key pages and IDing the new site structure, we need to create the actual content that will go in the wireframes.

## Working links
-   [draft outline](https://docs.google.com/document/d/1pa57Hh3LsKZCuJ2XCgCW8i7C7BWq8tEscpYSbJFtx4k/edit#heading=h.4tnbzlz6x88o)

## Acceptance criteria
-   [ ] Update service blueprint with relevant learnings
-   [ ] Update the [questions pool](https://docs.google.com/spreadsheets/d/1THH9Ekj5renvIwSpl-6SzzyUJ5tuNcH76l4GTiboQXE/edit#gid=0) with any questions that came up
-   [x] Content plans discussed with content owner
-   [x] Drafted started and reviewed with content owner and/or SME

**Comment by audreykwr** [comment]
@jillian-hammer fyi

**Comment by jillian-hammer** [comment]
@audreykwr seen, thank you!

**Comment by audreykwr** [comment]
[Draft](https://docs.google.com/document/d/1cjj9zI_EeYZuvvL2nTY_SKiwLcxZmEnD35I9P-_z1oU/edit#heading=h.nw4v6eftyjbz) in review so closing
