### ISSUE TITLE
NH - 1 (one) Production Failure

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#10172]
## **Problem Statement**
We received a notification on Slack at 11:54 PM regarding a "Fatal-Alert in Production FunctionApp Logs" relating to NH.  Also, received an email in ReportStream.gov stating that the account has been suspended.

## **What you need to know**

Result:
FAILED Sftp upload of inputReportId c25abba1-6ff8-4f91-bdd8-f0db128402b6 to SFTPTransportType(host=nhftp.nh.gov, port=22, filePath=/Home/dhhs.elr.cdc_prime.prd, credentialName=null) (orgService = nh-dphs.elr), Exception: Permission denied, All retries failed. Manual Intervention Required. Send Error report for: c25abba1-6ff8-4f91-bdd8-f0db128402b6 to nh-dphs.elr

## **Acceptance Criteria**
What action needs to take place to close this ticket:
1. Assign to Engineer to investigate

## **Additional Comments**
If applicable, add screenshots, links, etc. to further explain the ticket

**Comment by sliu1000** [comment]
Update:
Received an email from NH helpdesk.  They have created a ticket and working on our issue/request to reactivate the account.

**Comment by oslynn** [comment]
Tried manaully and RS upload file.  All got write permission denied.  Emailed Corinne Davis to report the error.

**Comment by oslynn** [comment]
Closing this ticket.  I will handle it in ticket 10080
