### ISSUE TITLE
Blockframes: Landing page template

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10184]
## User story

As a WebX team member, I want to see the ReportStream website designed iteratively, starting from blockframes, so that the team can continuously align on the scope and anticipate design/content/engineering needs early in the website redesign process. 

## Background & context

The WebX design team is creating blockframes for the new ReportStream website redesign. The **Landing page** page template will use the **[About core model outline](https://docs.google.com/document/d/1L6vIwjZxOJ-w8Uc142Xop4pS0pZbVW0RIVf-BOwTDro/edit#heading=h.u53a5rrtt5tb)** as a basis for blockframing, while still considering existing outlines for the other Landing pages (`Getting started`, `Developer resources`, `Managing your connection`, `Support`). These explorations in a lo-fi blockframe format allow us to explore different solutions and align on an approach across disciplines prior to moving farther into the design process.

## Open questions

- How can the blockframe be designed in a modular way to be flexible to the needs of different Landing Pages? Ex. The `About` page is the most robust, but what might the page template look like for lighter landing pages like `Support`?

## Pages considered as Landing pages:
- [Getting started](https://docs.google.com/document/d/1EOEnUoHJgrUWkIChTo0GkVnbbLkzkN65CHC5L3tTo34/edit)
- [About](https://docs.google.com/document/d/1TYkZJDFhPq53JofDNPMpGb8laVajIisQPZShtc87DqI/edit)
- [Managing your connection](https://docs.google.com/document/d/1U0pQDg5_pYEdoA3AXsx2k5jx82LVW-1KwfnX52Qyy6k/edit#heading=h.8i8iao4a4p7q)
- [Support](https://docs.google.com/document/d/1QWz3LlI_MbDw4S0v-jBFxh63ZyT7jB0ogyMyNwHP6GI/edit)

## Working links

-   Core model outline: [About](https://docs.google.com/document/d/1L6vIwjZxOJ-w8Uc142Xop4pS0pZbVW0RIVf-BOwTDro/edit#heading=h.u53a5rrtt5tb)
-   Sheet: [Site update plan](https://docs.google.com/spreadsheets/d/1xhnqSoRBfkVFrLR6sgM6QgW1kav7g_FyUkPykPIjOMk/edit#gid=0)
-   Figma: [Blockframe working space](https://www.figma.com/file/86JATe4hOwPfihwwloM5b8/Blockframes?type=design&node-id=0%3A1&mode=design&t=DbHTHvihgkt9JfRE-1)
## Acceptance criteria

**Blockframe design**
- [x] Blockframes capture general layout of content & components
- [x] Blockframes build upon content sequence and structure identified in the `About` core model synthesis 
- [x] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Review**
- [x] Review with design and/or design lead
- [x] Review with eng & product

**Comment by yudonoodles** [comment]
07/12 Jillian and I had a meeting to talk about potential ways to showcase specific types of content and did a sketching exercise on figma together.

**Comment by yudonoodles** [comment]
Shared and reviewed design with Jillian and pinged Lizzie as well to take a look.

**Comment by yudonoodles** [comment]
Requested for review from Audrey.

**Comment by yudonoodles** [comment]
Shared and reviewed with eng+product during eng sync.
