### ISSUE TITLE
Blockframes: Tool page(s)

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10185]
## User story

As a WebX team member, I want to see the ReportStream website designed iteratively, starting from blockframes, so that the team can continuously align on the scope and anticipate design/content/engineering needs early in the website redesign process. 

## Background & context

The WebX design team creating blockframes for the new ReportStream website redesign. The **Tool page** page template will use what we already know about the Validator Tool and Public Key Tool and help us understand how those are folded into our new website structure.

## Open questions

- What is the technical lift to slot these existing features into a new IA structure and new page structure? 

## Working links

-   Sheet: [Site update plan](https://docs.google.com/spreadsheets/d/1xhnqSoRBfkVFrLR6sgM6QgW1kav7g_FyUkPykPIjOMk/edit#gid=0)
-   Figma: [Blockframe working space](https://www.figma.com/file/86JATe4hOwPfihwwloM5b8/Blockframes?type=design&node-id=0%3A1&mode=design&t=DbHTHvihgkt9JfRE-1)

## Acceptance criteria

**Blockframe design**
- [x] Blockframes capture general layout of content & components
- [x] Blockframes reference the existing Public key tool and Validation tool and suggest a design solution that feels appropriate for those use cases
- [x] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Review**
- [x] Review with design and/or design lead
- [x] Review with eng & product

## To do
- [ ] After reviewing the navigation blockframes with engineering, brainstorm technical needs re: migrating tools to inform the design scope

**Comment by jillian-hammer** [comment]
Adjusted to one point as this was pretty quick to double check if the current UI could be adapted to the side-nav format.

Ready for review @yudonoodles and @audreykwr at the [prototype link](https://www.figma.com/proto/86JATe4hOwPfihwwloM5b8/Blockframes?type=design&node-id=890-3473&t=bn2nfTEMSI5hF7ZP-9&scaling=min-zoom&page-id=858%3A3166&starting-point-node-id=890%3A3473&show-proto-sidebar=1).

**Comment by yudonoodles** [comment]
Tshering reviewed the tool page blockframe with eng+prod during eng sync on 07/18. Summary of the discussion is as follows: 
- On adding side nav to existing tool pages: There will be some eng work required to implement the side nav, it's doable, but requires extra eng effort as the current implementation need to be generalized for the rest of the site. 
- On adding a generalized search: Need an entire spike on how search would work, what pages need to be indexed. Adding search on the header would mean the entire site can be searched and is more effort than doing page-level search. 
See rest of the notes from the meeting [here](https://docs.google.com/document/d/1VMKSRp9oaBGqNCMwBca5aCzIgnRlM9xR3V50uCOW_ns/edit).
