### ISSUE TITLE
Final content draft: Homepage

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10187]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

After completing basic outlines for key pages and IDing the new site structure, we need to create the actual content that will go in the wireframes. 

## Open questions
N/A

## Working links
-   [Homepage draft outline](https://docs.google.com/document/d/1L6vIwjZxOJ-w8Uc142Xop4pS0pZbVW0RIVf-BOwTDro/edit#heading=h.u53a5rrtt5tb)

## Acceptance criteria
-   [ ] Drafted finalized and reviewed with content owner and/or SME
-   [ ] Final draft presented to designer for next steps
-   [ ] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Comment by audreykwr** [comment]
Approved. Will continue to confirm quote approval & Rhapsody highlight approval as we work on the wireframes

[final draft](https://docs.google.com/document/d/1MWrWzRKvsTVqGXbn8PcdQSV2BAxDDsSyq7KQJ-yWnb4/edit)
