### ISSUE TITLE
Blockframes: Homepage

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10183]
## User story

As a WebX team member, I want to see the ReportStream website designed iteratively, starting from blockframes, so that the team can continuously align on the scope and anticipate design/content/engineering needs early in the website redesign process. 

## Background & context

The WebX design team creating blockframes for the new ReportStream website redesign. The **homepage** page template will use the Homepage/About RS core model outline as a basis for blockframing. These explorations in a lo-fi blockframe format allow us to explore different solutions and align on an approach across disciplines prior to moving farther into the design process.

## Open questions

N/A

## Working links

-   Core model outline: [Homepage](https://docs.google.com/document/d/1L6vIwjZxOJ-w8Uc142Xop4pS0pZbVW0RIVf-BOwTDro/edit#heading=h.u53a5rrtt5tb)
-   Sheet: [Site update plan](https://docs.google.com/spreadsheets/d/1xhnqSoRBfkVFrLR6sgM6QgW1kav7g_FyUkPykPIjOMk/edit#gid=0)
-   Figma: [Blockframe working space](https://www.figma.com/file/86JATe4hOwPfihwwloM5b8/Blockframes?type=design&node-id=0%3A1&mode=design&t=DbHTHvihgkt9JfRE-1)
## Acceptance criteria

**Design process**
- [x] Blockframes capture general layout of content & components 
- [x] Blockframes build upon content sequence and structure identified in the core model synthesis 
- [x] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Review process**
- [x] Review with design and/or design lead
- [x] Review with eng & product

**Comment by yudonoodles** [comment]
On 07/06 Webex designers: Jillian, Audrey and I had a working session where we sketched out the homepage ideas using the [updated homepage outline](url) as the reference. 

- Jillian's [blockframe on Figma](https://www.figma.com/proto/86JATe4hOwPfihwwloM5b8/Blockframes?type=design&node-id=512-1769&t=MBI8YIFEL55WPK69-1&scaling=min-zoom&page-id=512%3A1767&mode=design)
- Audrey's [blockframe on Mural](https://app.mural.co/t/nava4113/m/nava4113/1688665487941/7bb2be2cfe604ad77ef52d33f23f4309a50b7276?sender=uc55a7af3b66977fba12f5528)
- Tshering's [pen and paper blockframe on Figma](https://www.figma.com/file/86JATe4hOwPfihwwloM5b8/Blockframes?type=design&node-id=512%3A1767&mode=design&t=bL4vwhFms6kYySXD-1)

**Comment by yudonoodles** [comment]
Completed the block frame and shared it with design team for review (Jillian and Lizzie). Pinged them via slack.

**Comment by yudonoodles** [comment]
Sharing design with the larger design team during crit.

**Comment by yudonoodles** [comment]
Shared and reviewed with Audrey as well.

**Comment by yudonoodles** [comment]
Shared and reviewed with eng+product during eng sync.
