### ISSUE TITLE
Replace <Dropdown /> component with <Select /> component

### ISSUE THREAD

**Issue by etanb** [CDCgov/prime-reportstream#10186]
Across the RS app, we use the `<Dropdown />` component for menus etc, but it's deprecated: https://trussworks.github.io/react-uswds/?path=/docs/components-dropdown--default-dropdown

Shouldn't be too difficult of a swap to use the supported `<Select />` component. Will have to ensure styling looks the same.

**Comment by jpandersen87** [comment]
We do not seem to be using the deprecated component anymore.
