### ISSUE TITLE
Final content draft: Getting started - Landing page

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10188]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

After completing basic outlines for key pages and IDing the new site structure, we need to create the actual content that will go in the wireframes. 

## Open questions
N/A

## Working links
-   [Getting started - landing page draft](https://docs.google.com/document/d/1EOEnUoHJgrUWkIChTo0GkVnbbLkzkN65CHC5L3tTo34/edit)

## Acceptance criteria
-   [x] Drafted finalized and reviewed with content owner and/or SME
-   [ ] Final draft presented to designer for next steps
-   [ ] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Comment by audreykwr** [comment]
[Content approved](https://docs.google.com/document/d/1EOEnUoHJgrUWkIChTo0GkVnbbLkzkN65CHC5L3tTo34/edit). Closing
