### ISSUE TITLE
Content update: Managing your connection

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10195]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

After completing basic outlines for key pages and IDing the new site structure, we need to create the actual content that will go in the wireframes. 

## Open questions
N/A

## Working links
-   TK: Draft [link](https://docs.google.com/document/d/1U0pQDg5_pYEdoA3AXsx2k5jx82LVW-1KwfnX52Qyy6k/edit#heading=h.8i8iao4a4p7q)

## Acceptance criteria
-   [ ] Drafted and reviewed with content owner and/or SME
-   [ ] Final draft presented to designer for next steps
-   [ ] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Comment by audreykwr** [comment]
[Content approved ](https://docs.google.com/document/d/1U0pQDg5_pYEdoA3AXsx2k5jx82LVW-1KwfnX52Qyy6k/edit)- closing
