### ISSUE TITLE
Review completed blockframes: Navigation, Sub-landing and Detail pages

### ISSUE THREAD

**Issue by yudonoodles** [CDCgov/prime-reportstream#10197]
## User story
As a webex designer, we want to review early iterations of new page designs with Prod and Eng so that 1) we can align on the new pages 2) get feedback before adding fidelity and work hand-in-hand in an iterative manner. 

## Working links
Combined [Figma prototype](https://www.figma.com/proto/86JATe4hOwPfihwwloM5b8/Blockframes?type=design&node-id=83-661&t=4Sg9zXYpgvbFh0eg-1&scaling=min-zoom&page-id=1%3A9&starting-point-node-id=83%3A661&mode=design)

Page-specific: 
1. [Navigation](https://www.figma.com/proto/86JATe4hOwPfihwwloM5b8/Blockframes?type=design&node-id=83-661&t=CVBXcZ15wRCZgHL6-0&scaling=min-zoom&page-id=1%3A9&starting-point-node-id=83%3A661)
2. [Sub-landing page
](https://www.figma.com/file/86JATe4hOwPfihwwloM5b8/Blockframes?type=design&node-id=420%3A6457&mode=design&t=H3OkQ7AT3maF6hen-1)
3. [Detail Page](https://www.figma.com/file/86JATe4hOwPfihwwloM5b8/Blockframes?type=design&node-id=420%3A5534&mode=design&t=H3OkQ7AT3maF6hen-1)

## Acceptance criteria
-   [x] Review design with prod and eng

**Comment by yudonoodles** [comment]
Prepped Figma file for review with prod and eng:
- Created some page demarcations on Figma: "Ready for review" and "WIP"
- Prepped sub-landing and detail pages for review. Added some context information on the left to go with the "Current Iteration" screens. 
- Added review links that jumps you to the specific screen on figma to the ticket under **"Working links"**

**Comment by yudonoodles** [comment]
Prepped Figma file for review with prod and eng:
- Created some page demarcations on Figma: "Ready for review" and "WIP"
- Prepped sub-landing and detail pages for review. Added some context information on the left to go with the "Current Iteration" screens. 
- Added review links that jumps you to the specific screen on figma to the ticket under **"Working links"**

**Comment by jillian-hammer** [comment]
Shared async via [Slack](https://nava.slack.com/archives/C02HJ43AE8Z/p1688589635374009)

**Comment by yudonoodles** [comment]
07/06 Presented the blockframes (nav, detail, sublanding page) to the entire team during 16th min after standup. Requested for feedback on figma as comments.

**Comment by yudonoodles** [comment]
Next steps: Need to review comments and feedback from Etan and Chris. No blockers.

**Comment by yudonoodles** [comment]
Reviewed the feedback from Etan and Chris:

- Responded to Etan [on figma] (https://www.figma.com/file/86JATe4hOwPfihwwloM5b8?node-id=83:719&mode=design#491338059) and as far as an action item from [Chris' feedback](https://docs.google.com/document/d/1o80xRQLfdT3Fu7tSEBMlpiODM74KDCBTyJw0swUHYvw/edit#bookmark=id.9c0buboab2m9), tagged Audrey to take a look at the **Getting started** page title versus **Get started** btn observation. Re: dynamic content piece, Chris is going to follow up on it.

cc: @jillian-hammer

**Comment by yudonoodles** [comment]
Noting here that no changes had to be made for the completed blockframes based on the feedback provided.
