### ISSUE TITLE
Content update: Support landing page

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10194]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

After completing basic outlines for key pages and IDing the new site structure, we need to create the actual content that will go in the wireframes. 

## Open questions
N/A

## Working links
- [  Draft](https://docs.google.com/document/d/1QWz3LlI_MbDw4S0v-jBFxh63ZyT7jB0ogyMyNwHP6GI/edit#heading=h.qdf75hhh527j)

## Acceptance criteria
-   [x] Drafted finalized and reviewed with content owner and/or SME
-   [ ] Final draft presented to designer for next steps
-   [ ] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Comment by audreykwr** [comment]
[Content approved](https://docs.google.com/document/d/1QWz3LlI_MbDw4S0v-jBFxh63ZyT7jB0ogyMyNwHP6GI/edit#heading=h.qdf75hhh527j). Closing

Note: new service request and interest form are in progress but will be done before site is live
