### ISSUE TITLE
Prime CLI can convert FHIR to FHIR using sender transforms

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#10191]
### User Story:
As a developer, I want to be able to convert FHIR to FHIR using sender transform schemas by using the Prime CLI, so I can perform tests on data.

### Description/Use Case
The Prime CLI current has the ability to convert FHIR to HL7 and HL7 to FHIR.  This is useful for all kinds of testing.  We need the same capability to convert FHIR to FHIR to test sender transforms.

### Dev Notes:

* Here is an example conversion from FHIR to HL7
`./prime fhirdata -i src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0001.fhir -o src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0001-expected-base.hl7 -s metadata/hl7_mapping/ORU_R01/ORU_R01-base.yml --output-format HL7`

### Acceptance Criteria
* Prime CLI can convert FHIR to FHIR using sender transforms.
* Prime CLI can output the converted report to a file.
* Prime CLI can use an input FHIR bundle file as input for the conversion.
* Prime CLI can use an input sender transforms schema file as input for the conversion.

**Comment by kant777** [comment]
@victor-chaparro Does this mean we need to create a wrapper function FhirToFhir which internally would call FhirToHl7 and then Hl7toFhir? because I am thinking if its already in Fhir then why convert again to Fhir? Sorry I am missing some context I think
