### ISSUE TITLE
Create sender for CDC-ELIMS-HL7 org in STAGING environment

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#10199]
### User Story

As the CDC-ELIMS-HL7 organization, I need the ability to send HL7v2 ELR (ORU-R01) messages through RS to STLTs on ReportStream's staging environment universal pipeline.

### Description/Use Case

We need to configure RS:
1. Create a sender under the CDC-ELIMS-HL7 org in staging that can send HL7v2 ELR messages
2. This sender should be configured to use the `CDC-ELIMS-ELR` topic. Create topic if it does not exist.

Then:

1. Contact Arnej to get the CDC ELIMS' public key and add it to RS to enable server-server auth

### Acceptance Criteria

- [x] Sender created and configured and public key added

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10199?planning-poker) with Zenhub @arnejduranovic @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @thetaurean
