### ISSUE TITLE
Content update: About

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10193]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

After completing basic outlines for key pages and IDing the new site structure, we need to create the actual content that will go in the wireframes. 

## Open questions
N/A

## Working links
-   About: [Page outline](https://docs.google.com/document/d/1L6vIwjZxOJ-w8Uc142Xop4pS0pZbVW0RIVf-BOwTDro/edit#heading=h.u53a5rrtt5tb)

## Acceptance criteria
-   [x] Drafted finalized and reviewed with content owner and/or SME
-   [ ] Final draft presented to designer for next steps
-   [ ] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Comment by audreykwr** [comment]
Splitting this into two follow ons based on on-going review. [10708](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/10708) and [10707](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/10707)

[Drafting here](https://docs.google.com/document/d/1TYkZJDFhPq53JofDNPMpGb8laVajIisQPZShtc87DqI/edit)
