### ISSUE TITLE
Create STAGING Metabase collection for CDC ELIMS HL7 team

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#10207]
### User Story

As a member of the CDC ELIMS HL7 team that is sending CDC ELR reports to STLTs via RS, I want to be able to monitor the submissions as they go through ReportStream.

### Description/Use Case

We should update this [Metabase collection](https://staging.prime.cdc.gov/metabase/collection/49-cdc-elims-collection) with easy-to-use queries that answer the following questions requested by the HL7 team:
1. For a particular STLT (RS receiver), is there a connection set up for that STLT to receive both test messages and production messages from CDC?
2. For a particular report submitted to RS, what receivers received the report? 
3. For a particular report submitted to RS, what is the status (delivered, not delivered, delivering) and time the status was achieved for each receiver?

Also, there should be queries that show when:

1. RS routing logic determined a report should not go anywhere 
2. RS transport logic failed to deliver a report to a RS receiver’s destination. RS has a retry mechanism (over the course of 24 hours), so there should be a query that shows which ones are retrying and which ones failed permanently.
3. RS had a pipeline step fail for any reason and the report did not end up getting delivered 

BUT WAIT! We need to evaluate if the RS website already answers these questions, and if it does, evaluate the usefulness of it for the CDC ELIMS use case. If it does, update ticket with a mini "design note" detailing the situation. 

If we need to create a query for some piece of information but it requires code changes, create a new ticket and link it to this one.

### Acceptance Criteria

1. Aforementioned Queries created
2. When queries were not able to be created, a ticket was created and linked here OR, if more appropriate, this ticket was updated with information regarding the situation
3. Queries delivered to CDC ELIMS team

**Comment by arnejduranovic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10207?planning-poker) with Zenhub @jimmyfagan @JFU-NAVA-PBC @thetaurean @JessicaWNava @luis-pabon-tf

**Comment by mkalish** [comment]
No code was required for this so documenting the work here:

New dashboard for elims work is available here: https://prime.cdc.gov/metabase/dashboard/33-cdc-elims-hl7-dashboard
- It is currently configured to look at the covid-19 topic and will be updated when the new topic is added
- One widget has the list of receivers with transports configured
- The other widget shows the list of reports that had a send_warning, send_error or were not routed anywhere

To test:
- Load the dashboard to make sure that the widgets load
- Open and review the individual queries for correctness


For
>For a particular report submitted to RS, what receivers received the report?
For a particular report submitted to RS, what is the status (delivered, not delivered, delivering) and time the status was achieved for each receiver?

Both of these questions can be answered via the submissions UI available on the report stream website.


cc/ @arnejduranovic @avnieldravid

**Comment by mkalish** [comment]
@arnejduranovic I added four new queries, I'll wait for your feedback and then move them into src.

- query to find the submitted report from a delivered report id or delivered file name
- query to find all delivered reports from a submitted report id or submitted file name
- query to find the row in the submitted report for a row in the delivered report
- query to find all the delivered reports and row where a submitted row ended up
