### ISSUE TITLE
Set up Documentation Structure

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#10208]
### User Story
As a technical user of ReportStream I want organized documentation to help me to easily find the documentation that I need.

### Description/Use Case
Take the existing documentation and move it into the structure defined in the UP Technical Documentation Skeleton. 

### Risks/Impacts/Considerations
Possible that after it is laid out people will want to change it and the back and forth will significantly add to the time it takes to complete this ticket. 

### Dev Notes
There is a location note before each section as to where that documentation will go. Create folders to match this structure so that it is there for others to use and we can get a formal review on the structure. 

### Acceptance Criteria
- [x] The documentation folder structure is in place
- [x] Stubbed documents are created along with their sections. 
- [x] Existing documentation moved to the stubbed documents/sections where appropriate.
- [x] Any changes to structure are reflected in the document skelly so that others writing documentation know where to put theirs.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10208?planning-poker) with Zenhub @arnejduranovic @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @thetaurean

**Comment by JessicaWNava** [comment]
https://docs.google.com/document/d/1Xr2defgjUjarZgyROqOqM1Cezx_hp6S_Gd3Ue8bik64/edit?usp=sharing I shared it with you as well @mkalish
