### ISSUE TITLE
Write documentation on the Send step of the UP

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#10212]
### User Story
As senders, receivers, and Reportstream employees I want to understand the send step of the UP.

### Description/Use Case
Create a document that describes the send step of the UP. See the doc skelly for some idea on content: https://docs.google.com/document/d/1Xr2defgjUjarZgyROqOqM1Cezx_hp6S_Gd3Ue8bik64/edit?usp=sharing

### Risks/Impacts/Considerations
This is already included within the Getting Started > Common Failures & Fixes > Message Fails to Send section. Make sure to link to that content to prevent writing it twice.

### Dev Notes
update prime-router/docs/universal-pipeline/send.md

### Acceptance Criteria
- [x] Define content that should be in documentation and review with team before writing documentation
- [x] There is a document that describes the Send step of the UP

**Comment by mkalish** [comment]
Grabbing this as I had to figure out how the step works as part of understanding retries
