### ISSUE TITLE
Write documentation on deployments

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#10218]
### User Story
As a Reportstream engineer I want documentation on deployments

### Description/Use Case
Write a document on the deployment process, keeping in mind to leave out any security information. Could perhaps just reference the document currently used for deployments.

### Dev Notes
If https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/10208 is completed, use the existing structure, otherwise put the doc in docs/features.

Existing deployment doc [here](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B30FBCC7D-02B3-4FDE-BBF2-3EEE980B11E1%7D&file=ReportStream%20Deployment%20Process.docx&action=default&mobileredirect=true).

### Acceptance Criteria 
- [ ] Define content that should be in documentation and review with team before writing documentation
- [ ] A document exists on deployments

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10218?planning-poker) with Zenhub @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @luis-pabon-tf @mkalish @thetaurean

**Comment by MauriceReeves-usds** [comment]
@mxk0 @pstonebu this doesn't feel like it should live with Platform in particular. All engineers are on the hook for deployments, and engineering writ large should be managing this doc. In fact it feels like this should just be a continuous effort, and done each time a deployment is done. "Are the docs up to date? If not, update them." This of course assumes that the current docs are up to date, and if they're not, why not?

cc: @bishoyayoub @avnieldravid

**Comment by arnejduranovic** [comment]
I agree with Mo above and also we currently have a deployment doc that is linked in the deployment channel is slack. Closing.
