### ISSUE TITLE
Write documentation on the receive step of the UP

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#10216]
### User Story
As senders, receivers, and Reportstream employees I want to understand the receive step of the UP. See the doc skelly for some idea on content: https://docs.google.com/document/d/1Xr2defgjUjarZgyROqOqM1Cezx_hp6S_Gd3Ue8bik64/edit?usp=sharing

### Description/Use Case
Create a document that describes the receive step of the UP.

### Risks/Impacts/Considerations
See the documentation skelly for some help on where to start

### Dev Notes
If https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/10208 is completed, use the existing structure, otherwise put the doc in docs/features.

### Acceptance Criteria
- [ ] Define content that should be in documentation and review with team before writing documentation
- [ ] There is a document that describes the receive step of the UP
- [ ] The document includes a section on validation - This could potentially be a link to another document/location but should describe how validation applies to this step

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10216?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @mkalish @thetaurean
