### ISSUE TITLE
Write documentation on the route step of the UP

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#10214]
### User Story
As senders, receivers, and Reportstream employees I want to understand the route step of the UP.

### Description/Use Case
Create a document that describes the route step of the UP. See the doc skelly for some idea on content: https://docs.google.com/document/d/1Xr2defgjUjarZgyROqOqM1Cezx_hp6S_Gd3Ue8bik64/edit?usp=sharing

### Risks/Impacts/Considerations
See the documentation skelly for some help on where to start

### Dev Notes
update prime-router/docs/universal-pipeline/route.md

### Acceptance Criteria
- [ ] Define content that should be in documentation and review with team before writing documentation
- [x] There is a document that describes the route step of the UP
- [x] The default filters are described in the document

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10214?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean
