### ISSUE TITLE
Write documentation for a UP overview 

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#10217]
### User Story
As a sender, receiver, or Reportstream employee I want documentation on the overview of the universal pipeline

### Risks/Impacts/Considerations
See the documentation skelly for an idea of what to write. 

### Dev Notes
If the folder structure isn't done, put it in the docs/features folder.

### Acceptance Criteria 
- [ ] Define content that should be in documentation and review with team before writing documentation
- [ ] A document exists that gives an overview of the universal pipeline
- [ ] The document includes our data retention policy
- [ ] The document includes the a graphic of the phases

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10217?planning-poker) with Zenhub @arnejduranovic @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @thetaurean
