### ISSUE TITLE
Write documentation on how to run the backend.

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#10222]
### User Story
As a Reportstream engineer, I want documentation on how to run the backend

### Description/Use Case
Write a document on how to run the backend. This should be a step by step document on how to run the back end. The existing getting started doc may have some content that would be a good place to start. 

### Dev Notes
If https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/10208 is completed, use the existing structure, otherwise put the doc in docs/features.

Make sure to grab the old content in the deprecated file for how to run on an Apple Silicon Mac since this will be the steps we want people to use in order to spin this up.

### Acceptance Criteria 
- [ ] Define content that should be in documentation and review with team before writing documentation
- [ ] A document exists on how to run the backend

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10222?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean
