### ISSUE TITLE
Write documentation on FHIR functions

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#10223]
### User Story
As a Reportstream engineer, I want documentation on FHIR functions

### Description/Use Case
Write a document on FHIR path functions. See the doc skelly for some idea on content: https://docs.google.com/document/d/1Xr2defgjUjarZgyROqOqM1Cezx_hp6S_Gd3Ue8bik64/edit?usp=sharing

### Dev Notes
If https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/10208 is completed, use the existing structure, otherwise put the doc in docs/features.

### Acceptance Criteria 
- [ ] Define content that should be in documentation and review with team before writing documentation
- [ ] A document exists on FHIR functions
- [ ] The document details custom FHIR Functions
- [ ] The document details internal vs external FHIR path functions

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10223?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @luis-pabon-tf @mkalish @thetaurean
