### ISSUE TITLE
Blockframe: New Detail pages

### ISSUE THREAD

**Issue by yudonoodles** [CDCgov/prime-reportstream#10266]
## User story
As a WebX team member, I want to design News and Case Studies pages in a templated manner so that we can align on the scope and anticipate design/content/engineering needs early in the website redesign process.

## Background & context

New detail pages include News and Case studies pages. 

## Working links

-   [Blockframe working space ](https://www.figma.com/file/86JATe4hOwPfihwwloM5b8/Blockframes?type=design&node-id=290%3A1073&mode=design&t=W3czPZbx7b25GSSk-1)

## Acceptance criteria

-   [x] Blockframe new detail pages 
-   [x] Review with design and or/design lead

**Comment by yudonoodles** [comment]
Requested design to review via slack: Jillian and Audrey

**Comment by jillian-hammer** [comment]
@yudonoodles thanks looks great! left a few clarifying comments
