### ISSUE TITLE
Update the Postgres documentation

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#10270]
### User Story
As a reportstream engineer I want documentation on Postgres that is up to date.

### Description/Use Case
Read through the Postgres docs and make any changes necessary to the document to get it up to date with the latest information. 

Docs:
-  Data restore - already exists
- DB Failover restore - already exists 
- DB Flyaway repair - already exists
- How to debug database queries (already exists)
- SimpleReport data dictionary (already exists)
- Include content for the environment RS is running i.e local, staging, and prod

### Acceptance Criteria
- [ ] Postgres doc has been read through and updated
- [ ] Look for additional documentation on this topic and consolidate if it exists.
- [ ] Put this document in the file structure, if already updated. Otherwise put it in docs/features

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10270?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @luis-pabon-tf @mkalish @thetaurean
