### ISSUE TITLE
NJ - Downsizing 45,000 files to 500 within HL7 file

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#10302]
## Problem statement
*user is Mike Firsker njelr.admin@doh.nj.gov*

*user states*

Please note there were a number of issues with this file:  covid-19-1b7faa0e-d32f-4a9a-883c-0e3914b4d58c-20230704143930.hl7

This file has over 45,000 messages in it, and many dating back to 2022.  This is too large for our system to process.  This needs to be broken down in files of no more than 500 messages.

## What you need to know

 file name is: covid-19-1b7faa0e-d32f-4a9a-883c-0e3914b4d58c-20230704143930.hl7

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by LaFreda1** [comment]
@Jcavallo7 Do you know who the sender of these files is?

**Comment by Jcavallo7** [comment]
It was Rhapsody

**Comment by cloudmagic80** [comment]
@LaFreda1  Are we going to ask the labs to decrease the size of the file by not report older cases?

**Comment by LaFreda1** [comment]
@cloudmagic80 we will need to figure out if this is a one off situation, first; like the MA ticket (#10198). @Jcavallo7 Is there a way to determine who sent the data through rhapsody? Ideally, we need to get with the state and determine how they would like for us to handle these files going forward.

**Comment by Jcavallo7** [comment]
Followed up with user for further information

**Comment by Jcavallo7** [comment]
*update from user*
I believe there were many records from MEDRITE, but I can’t be sure because I have a lot of difficulty opening the file.

**Comment by LaFreda1** [comment]
@Jcavallo7 thank you. I think the next step should be for us to contact MEDRITE to confirm if they sent the data,. If they did, figure out why.....also, ask them to decrease the size of their files for NJ to be less than 500. @cloudmagic80 you may not be needed for this ticket after all. I will remove you for now and will assign Juan.

**Comment by Jcavallo7** [comment]
Did some looking and found it was PRL InnoLabs on 7/4/23 with 39k+ messages that submitted.

Updated the user as well and asked what is the earliest date for test submission he would like, as it is looking comparable to the MA sender ticket situation, upon confirmation of NJ's request I will email Innolabs and see to it for it be less than 500

**Comment by LaFreda1** [comment]
@Jcavallo7 closing this ticket for now. Will reopen if the issue comes back up.
