### ISSUE TITLE
Create Mappings for ETOR TI OML Sample

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#10310]
### User Story

Example Message:
Example OML: https://github.com/CDCgov/trusted-intermediary/blob/main/examples/hl7/MN/MN%20NBS%20OML_O21%20Lab%20Order%20Message.txt
Example FHIR Order: https://github.com/CDCgov/trusted-intermediary/blob/main/examples/fhir/MN%20NBS%20FHIR%20Order%20Message.json

### Description/Use Case

Flexion has updated their [sample OML message](https://github.com/CDCgov/trusted-intermediary/blob/d473ac9ea63ed6ccbd6cb68cc4695588870a7fdc/examples/fhir/MN%20NBS%20FHIR%20Order%20Message.json) based on a real message from Minnesota. We need to run this through RS and update our mappings so that the output HL7v2 does not have any missing information.

The mapping guide for OML -> FHIR can be found here: https://docs.google.com/spreadsheets/d/1cSYLIXVfIjl7ib2DEGxD96LD9-YVJNQtKul5IwzJtts/edit#gid=0

### Risks/Impacts/Considerations

- Minnesota is not set in stone as a partner yet, so we may not work with them. However, this exercise still seems valuable.
- We do not know what validation profile the lab will want us to adhere to, so for now we will have to just use standard HL7v2

Additional context from John:

- we’ve seen lab order IGs from Texas, Minnesota, & California that all use OML.
- In terms of validation profile — thus far they all seem to be derived from the HL7 LOI Guide (OML/ORU 2.5.1). However, we have seen deviations that bring in newer HL7v2 fields. (e.g. OBX-29 & OBX-30)

### Dev Notes

We currently support basic demographics when converting to OML. We would like to enhance this to include the following demographics:

1. Specimen ID
2. Collection Date & Time
3. Newborn weight
4. Food source
5. Gestational age
6. Risk factors (e.g. NICU, TPN, transfusion, antibiotics)
7. PCP / Pediatrician Info
8. Submitter info
9. Insurance info

### Acceptance Criteria

- [ ] Sample FHIR message can be sent through RS and converted to HL7v2 OML losslessly

**Comment by avnieldravid** [comment]
Updated with the latest OML and FHIR files

**Comment by bishoyayoub** [comment]
Need to break this story out into a second ticket to send the message to a trusted intermediary service(Flexion).

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10310?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by avnieldravid** [comment]
@JohnNKing can you verify that we have to most up to date OML and FHIR message links?

**Comment by arnejduranovic** [comment]
This ticket is no longer applicable with ETOR moving forward with other partners and use cases.
