### ISSUE TITLE
Create SFTP monitor for the SFTP containers in Stag/Prod so we know if the are unresponsive

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#10368]
Issue says it all - we want to know if the SFTP server is not working. Ideally we'd just SSH into it every 10 minutes or so

**Comment by dkrylovsb** [comment]
Resuming work on this one, since a FWCR has been implemented in Stage.

**Comment by dkrylovsb** [comment]
Worked fine in Stage, but currently blocked from propagating to Prod due to ticket CHG0032583. Need a FWCR in Prod...
