### ISSUE TITLE
Content update: Data requirements and preferences

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10379]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

After completing basic outlines for key pages and IDing the new site structure, we need to create the actual content that will go in the wireframes. 

## Open questions
N/A

## Working links
-   TK: Draft link

## Acceptance criteria
-   [ ] Drafted and reviewed with content owner and/or SME
-   [ ] Final draft presented to designer for next steps
-   [ ] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Comment by audreykwr** [comment]
Closing because this actually ended up being combined with the main receiving data page, so it is included in [this ticket](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/10375)

@chris-kuryak @Andrey-Glazkv @jillian-hammer
