### ISSUE TITLE
Content update: Developer resources

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10378]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

After completing basic outlines for key pages and IDing the new site structure, we need to create the actual content that will go in the wireframes. 

## Open questions
N/A

## Working links
-   Draft link: [Developer resources](https://docs.google.com/document/d/1e-1EIq0Ubk6BgLWlgAkgKcovPvPo8Jm1GLJAqkVc-e0/edit#heading=h.6lykt5pnz3wz)

## Acceptance criteria
-   [ ] Drafted and reviewed with content owner and/or SME
-   [ ] Final draft presented to designer for next steps
-   [ ] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Comment by audreykwr** [comment]
Forgot to close before I left for PTO!
