### ISSUE TITLE
Convert ORM to FHIR for TI Service

### ISSUE THREAD

**Issue by avnieldravid** [CDCgov/prime-reportstream#10370]
### User Story
As a Hospital, I want ReportStream to be able to convert incoming ORM messages to FHIR format, so that I'm able to submit electronic orders the form that my EHR supports.

### Description/Use Case
We would like to support the following FHIR resources:

1. MessageHeader
2. Patient
3. Observations 
4. Specimen
5. ServiceRequest
6. Organization
7. Practitioner
8. PractitionerRole (otherwise, I can't find a way to associate both the ordering physician and hospital to the ServiceRequest)

### Dev Notes

Example ORM: https://github.com/CDCgov/trusted-intermediary/blob/main/examples/hl7/MN/MN%20NBS%20ORM_O01%20Lab%20Order%20Message.txt
Example FHIR Order: https://github.com/CDCgov/trusted-intermediary/blob/main/examples/fhir/MN%20NBS%20FHIR%20Order%20Message.json

### Acceptance Criteria

- [ ] Sample FHIR messages are flowing to the TI Service
- [ ] Confirm receipt of the FHIR messages by ETOR team

**Comment by JohnNKing** [comment]
Regarding the list of FHIR resources, I think we'll also need:

- MessageHeader
- Specimen
- PractitionerRole (otherwise, I can't find a way to associate both the ordering physician and hospital to the ServiceRequest)

Dev note: Proposed FHIR sample message https://github.com/CDCgov/trusted-intermediary/blob/fhir-sample-data/examples/fhir/MN%20NBS%20FHIR%20Order%20Message.json -- but we can certainly make adjustments to that as needed

**Comment by jimmyfagan** [comment]
This is a bit blocked on #9675 at the moment.

**Comment by avnieldravid** [comment]
Fair point @MauriceReeves-usds -- let me discuss with the team to make sure everybody agrees with the split.

**Comment by MauriceReeves-usds** [comment]
@JohnNKing @avnieldravid I made a ticket to track publishing and presenting the draft order IG you're creating to the HL7 WG. It is here: https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/10382

**Comment by JohnNKing** [comment]
Thanks @MauriceReeves-usds

@avnieldravid Now that I've merged my PR, the sample links referenced above have changed to:

- Example ORM: https://github.com/CDCgov/trusted-intermediary/blob/main/examples/hl7/MN/MN%20NBS%20ORM_O01%20Lab%20Order%20Message.txt
- Example FHIR Order: https://github.com/CDCgov/trusted-intermediary/blob/main/examples/fhir/MN%20NBS%20FHIR%20Order%20Message.json

**Comment by avnieldravid** [comment]
I believe we are no longer blocked on authenticating against TI.  So this ticket's acceptance criteria will involve that step as well.  Does that align with your thinking @JessicaWNava ?

**Comment by avnieldravid** [comment]
also @JessicaWNava please note the new links that JOhn provided.  I'm also updating the main ticket.
