### ISSUE TITLE
Content update: Receiving data

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10375]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

After completing basic outlines for key pages and IDing the new site structure, we need to create the actual content that will go in the wireframes. 

## Open questions
N/A

## Working links
-   [Draft doc](https://docs.google.com/document/d/1cewTIEbvIuUc00Qc-G8vzULZ8ZIbedQDCkrNYSN-vyQ/edit)

## Acceptance criteria
-   [x] Drafted and reviewed with content owner and/or SME
-   [ ] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Comment by audreykwr** [comment]
This is technically duplicate with [the previous one about this content](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/10025). Which one do you want to keep?

**Comment by jillian-hammer** [comment]
oh good catch @audreykwr let's keep this one and close the old one if that's okay?

**Comment by audreykwr** [comment]
That works. @chris-kuryak FYI - can you close [10025](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/10025) since this will replace it?
