### ISSUE TITLE
Handle deprecation changes on KTlint dependency

### ISSUE THREAD

**Issue by luis-pabon-tf** [CDCgov/prime-reportstream#10385]
### User Story
As a ReportStream developer, I want to keep our codebase consistent via automation to save time and keep accuracy.

### Description/Use Case
Our dependency of `org.jlleitschuh.gradle.ktlint` includes some changes that will throw deprecation notices when updated to the latest version. These notices should be handled to ensure all automated processes behave normally.

### Dev Notes
Dependabot PR that is handling the update. You may use its branch as a starting point since we can always just close this PR. https://github.com/CDCgov/prime-reportstream/pull/10300

### Acceptance Criteria
- All references to code throwing deprecation notices has been updated

**Comment by bishoyayoub** [comment]
@arnejduranovic do you know which epic this belongs to?

**Comment by arnejduranovic** [comment]
Tech Debt is best match imo

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10385?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @thetaurean
