### ISSUE TITLE
Content update: Case studies plans

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10380]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

After completing basic outlines for key pages and IDing the new site structure, we need to create the actual content that will go in the wireframes. 

## Open questions
N/A

## Working links
-   TK: Draft link

## Acceptance criteria
-   [ ] Plans started for developing case studies
-   [ ] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Comment by audreykwr** [comment]
@jillian-hammer updated the title and AC to be more representative of what's actually happening this sprint, which is making plans for creating these

**Comment by audreykwr** [comment]
[Plans drafted](https://docs.google.com/spreadsheets/d/1kFlZpMc3jYUOQ50ZhFB9vCe2WpdBfmNOFRRC79Cl0ag/edit#gid=0) and reviewed with Drew. Will add details to the follow on tickets.
