### ISSUE TITLE
[Bug] Fix the Referral page on ReportStream website

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#10392]
## Problem statement
The Referral Guide page on the ReportStream website is currently not working (showing a blank page).

## What you need to know

- On the Resources page, here is the [Referral Guide Page](https://reportstream.cdc.gov/resources/referral-guide)
- ...

## Acceptance criteria

- [ ] Referral Guide page shows the correct content (before it was blank)
- [ ] Add space b/w "nameand" in the "insert your name and/or public health department name" sentence.

## To do

- [ ] ...

**Comment by KeithNava** [comment]
According to the logs, the last time it worked was on 6/27. Next time the page was accessed was on 7/5, and it was not working then.

I'm currently rolling back the commits to see if I can isolate the exact time we introduced the issue.

**Comment by KeithNava** [comment]
Looks like it's also happening on the https://reportstream.cdc.gov/resources/getting-started-submitting-data page. These two pages are both using the legacy way of rendering Markdown - https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/pages/resources/markdown-adapters.tsx

**Comment by chris-kuryak** [comment]
@KeithNava since this is in review/QA, do we have an updated Point Estimate?

**Comment by KeithNava** [comment]
> @KeithNava since this is in review/QA, do we have an updated Point Estimate?

Ah yes, it's a 3 pointer! I'll pop it on the ticket. Thanks @chris-kuryak cc @Andrey-Glazkv
