### ISSUE TITLE
[SPIKE] SEO Audit

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#10419]
## Problem statement

As we look more into incorporating SEO in the website, we would like to first run a audit to understand how the site is currently performing in terms of SEO. There's a few tools to help with this analysis:
- [Google Page Insights](https://pagespeed.web.dev/)
- [Sem Rush SEO Checker](https://www.semrush.com/on-page-seo-checker/)
- Site-checker?

## What you need to know

- [SEO Fundamentals](https://developers.google.com/search/docs/fundamentals/get-started-developers#find-out-how-google-sees-your-site)

## Acceptance criteria

- [ ] Determine a good plan of action for measuring/finding our SEO gaps (diagnosis)
- [ ] List some options/ideas to improve rankings in Google Search

**Comment by chris-kuryak** [comment]
Review in Engr sync.

**Comment by chris-kuryak** [comment]
@penny-lischer Can you add the output/link to the docs you created/found.

**Comment by penny-lischer** [comment]
Linking to #10420 for findings

**Comment by chris-kuryak** [comment]
Penny had done some of this in Site Checker
