### ISSUE TITLE
Performance Audit

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#10420]
## Problem statement

As we go into a redesign and potential scaling of the website, we want to take this opportunity to establish some performance improvements that can be made to improve the end user's experience - This will also have a natural, positive impact on SEO.  

The initial goal of this ticket is to establish a baseline for our current performance metrics. Depending on the results, there might be a follow-up ticket to focus on improving the site's performance. 

After completion, we'll be on the path to creating a performance budget and quality gates to ensure we're not degrading the site as we add new features. 

## What you need to know

- [Performance Budgets 101](https://web.dev/performance-budgets-101/)
- [Performance on MDN](https://developer.mozilla.org/en-US/docs/Web/Performance/Performance_budgets)
- [Web Vitals](https://web.dev/vitals/)

## Acceptance criteria

- [x] Report on the current performance of the site
- [x] Recommendations to improve performance, if needed.

## To do

- [ ] Add performance as an acceptance bullet point to every ticket

**Comment by penny-lischer** [comment]
Captured metrics for desktop only. We can include mobile when needed.
Also, included API load times for our reference. *Note that the load times will vary, this was merely to get a sense of latency.
[https://app.zenhub.com/files/304423150/709de9de-c30e-4d42-b0ad-52332af1db40/download](https://app.zenhub.com/files/304423150/709de9de-c30e-4d42-b0ad-52332af1db40/download)

**Comment by penny-lischer** [comment]
@KeithNava @chris-kuryak  We may want to create a performance budget in the future to flag pages that don't meet our expectations.

**Comment by chris-kuryak** [comment]
Keith is on it, but can review when we feel like we are at a good place.
