### ISSUE TITLE
VT - Received Intrivo results that should have been filtered 7/13/23

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#10432]
## **Problem Statement**

We received an email from Andrew Gross in the ReportStream Support inbox this morning at 8:06 AM EST regarding results that should have been filtered out - see ZH tickets #9506 and #9695 for additional details.

## **What you need to know**

Email received from Andrew:

> I am following up on the below request from VDH to no longer receive self-reported covid results. VDH recently received notifications for 2 failed self-report messages to our test environment (see details below)
> 
> Filename: covid-19-ecd65040-c348-4336-bca8-9939346440ab-20230615171538.hl7
> Received: Wed Jul 12 2023 11:23:31 GMT-0400 (EDT)
> Message Control ID: `1b119334-945f-42de-b114-b00c1e1da8f6`
> Lab Accession #: 123456
> 
> Filename: covid-19-5bcb3d21-06bd-47af-a139-590b4875db2b-20230623171510.hl7
> Received: Wed Jul 12 2023 11:23:31 GMT-0400 (EDT)
> Message Control ID: `7d9c9754-c2f9-49db-b850-ecb59aa78221`
> Lab Accession #: 123456
> 
> I am just looking for some clarification on why these messages were attempted to be submitted to our test environment. We won’t require any re-submission or anything given our desire to not receive self-report data, but any input would be appreciated!

I checked in the RS Metabase and confirmed that these results contain values that should have been filtered out.

## **Acceptance Criteria**

- [ ] Determine why these results were not filtered appropriately 
- [ ] Resolve any potential holes in the filter logic for VT

## **To Do**

The attached screenshot shows the relevant values on the two message IDs listed in the user's request that should have flagged the message to filter out. The user would like to know how this occurred and whether it can be prevented in the future.

## **Additional Comments**

![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/63c6d8da609e3157761267ef/82ad8c00-6021-489b-90e4-93dd1898c8ad)

**Comment by oslynn** [comment]
@wcollin89 I am sorry for not telling you since last week since the ticket was fixed since then.  The reason VT was still getting the OTC test results was that VT-OTC-TEST channel was still open.  Now,  I closed or filtered to not let any OTC test result pass-through to the channel anymore.  Therefore, they will not get any message in that channel, again.
