### ISSUE TITLE
Wireframe: Homepage

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10436]
## User story

XXX

## Background & context

This ticket captures the work of creating a high-fidelity wireframe of the homepage to review with design, engineering, and product before moving to implementation. 

## Working links

-   Figma: [Working file](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Wireframes?type=design&node-id=12%3A2192&mode=design&t=F8l2IdfbmBIl0YfI-1)
-  Content doc: [Homepage](https://docs.google.com/document/d/1MWrWzRKvsTVqGXbn8PcdQSV2BAxDDsSyq7KQJ-yWnb4/edit#heading=h.fsis3binw4u7)

## Acceptance criteria
**Design**
-   [x] Homepage reflects the latest content finalized in Sprint 72
-   [x] Homepage captures the range of USWDS and custom components (if needed)
-   [x] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Review**
-   [x] Page template reviewed with design and/or design lead
-   [x] Make updates to the design based on feedback
-   [x] Page template reviewed with product and engineering

**Comment by jillian-hammer** [comment]
Ticket stub here for you @yudonoodles – feel free to add extra information. 

cc @lizzieamanning

**Comment by yudonoodles** [comment]
- On 07/21 completed a draft version of the homepage and shared it with Audrey+Lizzie. 
- On 07/24 shared the draft version with Jillian and received feedback. 
- Received 18 comments on the figma file, responding to them and updating the design.

**Comment by yudonoodles** [comment]
- Had the chance to review design with Etan & Joseph, and received feedback from Penny async on figma file. 
- Received add'l feedback from design sync and async: Lizzie, Audrey and Jillian
- Made updates to the design this morning [See v3.2 of homepage](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Wireframes?type=design&node-id=187%3A2171&mode=design&t=s3k8GKlSKhN9LKkE-1)

**Comment by yudonoodles** [comment]
- On 07/27 Since I was out sick in the afternoon, Jillian reviewed the wireframe with prod+eng during standup (16th min)
- On 07/28 Updated homepage with add'l feedback [See v3.2 of homepage ](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Wireframes?type=design&node-id=187%3A2171&mode=design&t=s3k8GKlSKhN9LKkE-1)
