### ISSUE TITLE
Enable replaceUnicodeWithAscii in the UP

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#10475]
### User Story
As ReportStream, I want the ability replace unicode with ASCII for messages flowing through the UP, so that I can support the translation setting in the Covid pipeline.

### Description/Use Case
The Covid pipeline has the ability to replace unicode with ASCII for messages being sent out. We need to enable this in the UP. This is currently only used for HL7 messages we need to find out if we need this for all formats.

### Dev Notes
- We need to find a way to enable replaceUnicodeWithAscii in the UP
- The covid pipeline calls the `unicodeToAscii` function in `Hl7Serializer.kt` if the flag is set to true
- We can probably re-use this function in the UP

### Acceptance Criteria
- The UP can replace unicode with ASCII for messages.

**Comment by LaFreda1** [comment]
Will reopen if needed, not used by any receivers.
