### ISSUE TITLE
Create new azure storage containers for the schemas

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#10485]
### User Story
As a report stream admin, I would like dedicated azure blob containers in staging and production to store translation schemas

### Description/Use Case
Two new containers should exist, one in staging and one in production, both called  TranslationSchemas

### Risks/Impacts/Considerations
- This might need to be handled by the devops team
- Should these get added via Terraform or manually? - ask Jeremy.

### Dev Notes
I believe we'll need two new [azure storage containers](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#blob_properties) with [versioning enabled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#versioning_enabled)

### Acceptance Criteria
- [ ] A container exists in staging for storing translation schemas
- [ ] A container exists in production for storing translation schemas

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10485?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @mkalish

**Comment by MauriceReeves-usds** [comment]
@mkalish what is the benefit to the users here?

**Comment by arnejduranovic** [comment]
@MauriceReeves-usds The benefit to users for the epic in general is faster turn around time when updating transforms. When we did the Flu pilot, we would have to do off-cycle deploys to get our California transforms updated so California could verify, or we would wait until the next scheduled deployment, losing time. Once this epic is implemented, we can update transforms in real-time without having to redeploy the app, speeding up onboarding and verification time.

**Comment by arnejduranovic** [comment]
@mkalish thinks this can be closed because container should be created automatically. Michael to confirm.

**Comment by mkalish** [comment]
I believe these will be get created automatically when schemas are first pushed and versioning is enabled.
