### ISSUE TITLE
Add a function to download a blob as BinaryData with retries

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#10487]
### User Story
As a report stream developer, I would like a function that downloads a blob as an `BinaryData` retrying if I/O errors are encountered

### Description/Use Case
Currently, the only download function generates a bytearray, but this can be simplified for downstream uses by returning `BinaryData`.  Additionally, since it's possible to encounter an I/O error we'll want to add some retry functionality

### Dev Notes
- [downloadContent](https://learn.microsoft.com/en-us/java/api/com.azure.storage.blob.specialized.blobclientbase?view=azure-java-stable#com-azure-storage-blob-specialized-blobclientbase-downloadcontent()) can be used
- The number of retries should be configurable 
- Check to see if there is a library that can implement the retry for us

### Acceptance Criteria
- [ ] A download method that returns `BinaryData`
- [ ] The method retries a configurable number of times when I/O errors are encountered

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10487?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @mkalish
