### ISSUE TITLE
Create Way to Generate Release Notes from Git Commits

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1048]
There should be a way to generate release notes from our Git Commit messages similar to what's demonstrated here: https://blogs.sap.com/2018/06/22/generating-release-notes-from-git-commit-messages-using-basic-shell-commands-gitgrep/

**Comment by JosiahSiegel** [comment]
A side-effect of building the GitHub release process is that release notes will be generated from commits.
