### ISSUE TITLE
Implement a function to list files in an azure blob container

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#10488]
### User Story
As a report stream developer, I would to be able to list blobs hierarchically

### Description/Use Case
Downstream tickets will require inspecting what is currently in the blob store and making decisions about what action to take

### Dev Notes
This function can likely use [listByHierarchy](https://learn.microsoft.com/en-us/java/api/com.azure.storage.blob.blobcontainerclient?view=azure-java-stable#com-azure-storage-blob-blobcontainerclient-listblobsbyhierarchy(java-lang-string-com-azure-storage-blob-models-listblobsoptions-java-time-duration)) and then the [versions options](https://learn.microsoft.com/en-us/java/api/com.azure.storage.blob.models.bloblistdetails?view=azure-java-stable#com-azure-storage-blob-models-bloblistdetails-setretrieveversions(boolean))

### Acceptance Criteria
- [ ] A method exists that returns the hierarchical list of blobs in a container
- [ ] The method optionally will return the version ids for each blob

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10488?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @mkalish

**Comment by JFU-NAVA-PBC** [comment]
@arnejduranovic @mkalish @jack-h-wang 

mocking the returns from azure SDK blobContainerClient.listBlobsByHierarchy(...) seems pretty involved, here is the test I created but it throw mock exception when run, post here for reference:

`@Test
    fun `list blobs`() {
        // test blobs hierarchy:
        // start directory
        // testblobbase/
        //      |
        //      +--> foo/
        //      |      |
        //      |      +---> foo_file1.txt
        //      |      |
        //      |      +---> foo_file2.txt
        //      |
        //      +--> bar/
        //             |
        //             +---> bar_file1.txt
        //             |
        //             +---> bar_file2.txt
        //      top_file1.txt
        val testEnv = "testenvvar"
        val testContainer = "testcontainer"
        val testBlobBase = "testblobbase"
        val expectedResult: List<BlobAccess.BlobEntry> = listOf(
            BlobAccess.BlobEntry(
                "$testBlobBase/foo/",
                isPrefix = true,
                versionId = "v1",
                listOf<BlobAccess.BlobEntry>(
                    BlobAccess.BlobEntry(
                        "$testBlobBase/foo/foo_file1.txt",
                        isPrefix = false,
                        versionId = "v1",
                        listOf()
                    ),
                    BlobAccess.BlobEntry(
                        "$testBlobBase/foo/foo_file2.txt",
                        isPrefix = false,
                        versionId = "v1",
                        listOf()
                    )
                )
            ),
            BlobAccess.BlobEntry(
                "$testBlobBase/bar",
                isPrefix = true,
                versionId = "v1",
                listOf<BlobAccess.BlobEntry>(
                    BlobAccess.BlobEntry(
                        "$testBlobBase/bar/bar_file1.txt",
                        isPrefix = false,
                        versionId = "v1",
                        listOf()
                    ),
                    BlobAccess.BlobEntry(
                        "$testBlobBase/bar/bar_file2.txt",
                        isPrefix = false,
                        versionId = "v1",
                        listOf()
                    )
                )
            ),
            BlobAccess.BlobEntry(
                "$testBlobBase/top_file.txt",
                isPrefix = false,
                versionId = "v1",
                listOf()
            )
        )

       val pathToListItems: Map<String, Array<BlobItem>> = mapOf(
           Pair(testBlobBase, arrayOf<BlobItem>(
               BlobItem().setName("$testBlobBase/foo").setIsPrefix(true).setVersionId("v1"),
               BlobItem().setName("$testBlobBase/bar").setIsPrefix(true).setVersionId("v1"),
               BlobItem().setName("$testBlobBase/top_file.txt").setIsPrefix(false).setVersionId("v1")
           )),
           Pair("$testBlobBase/foo", arrayOf<BlobItem>(
               BlobItem().setName("$testBlobBase/foo/foo_file1.txt").setIsPrefix(false).setVersionId("v1"),
               BlobItem().setName("$testBlobBase/foo/foo_file2.txt").setIsPrefix(false).setVersionId("v1")
           )),
           Pair("$testBlobBase/bar", arrayOf<BlobItem>(
               BlobItem().setName("$testBlobBase/bar/bar_file1.txt").setIsPrefix(false).setVersionId("v1"),
               BlobItem().setName("$testBlobBase/bar/bar_file2.txt").setIsPrefix(false).setVersionId("v1")
           )),
       )

        mockkClass(BlobAccess::class)
        mockkObject(BlobAccess.Companion)

        every { BlobAccess.Companion.getBlobConnection(testEnv) } returns "testconnection"

        val testBlobMetadata = BlobAccess.BlobContainerMetadata.build(testContainer, testEnv)
        val mockedContainerClient = mockkClass(BlobContainerClient::class)
        every { BlobAccess.Companion.getBlobContainer(testBlobMetadata) } returns mockedContainerClient

        every { mockedContainerClient.listBlobsByHierarchy(
            any(), any<ListBlobsOptions>(), any<Duration>()
        ).spliterator() } answers {
            Arrays.spliterator(pathToListItems[testBlobBase])
        }

        val result = BlobAccess.listBlobs(
            testBlobBase,
            testBlobMetadata
        )
        // assert the expected here
    }
`

**Comment by JFU-NAVA-PBC** [comment]
the test ran into mock exception:

`gov.cdc.prime.router.azure.BlobAccessTests list blobs() FAILED (2.2s)

  io.mockk.MockKException: no answer found for PagedIterable(child of #13#15).iterator() among the configured answers: (PagedIterable(child of #13#15).spliterator()))
      at app//gov.cdc.prime.router.azure.BlobAccessTests.list blobs(BlobAccessTests.kt:335)`

**Comment by JFU-NAVA-PBC** [comment]
Note:

putting spliterator in the mocked call and answer simply to make the code compile.

without the .spliterator there, I am facing the task of mocking the SDK's PagedIterable<BlobItem> which is pretty involved if not impossible (it must be possible but you just need to write a lot mocking code...)

**Comment by JFU-NAVA-PBC** [comment]
though no new tests added, existing smoke tests passed:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE1HQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7dfe637ca4c240f33768be64c7921697e5b77903/image.png)

**Comment by JFU-NAVA-PBC** [comment]
For testing and verifying, need to take manual approach:

steps:

1. checkout PR to local
2. start a local RS server and run smoke tests - this will create blobs under RS container
3. now instrument HistoryFunctions.kt with calls to BlobAccess.listBlobs() and BlobAccess.listBlobsReactive()
4. see attached HistoryFunctions.kt (already instrumented), replace your HistoryFunctiuons.kt 
5. re-compile and restart RS server with the instrumented HistoryFunctions.kt
6. Check the DB report_file table and pick a report ID
7. Call history end point with the report ID, this will return the report in response body and ALSO
8. It will call the 2 listBlobs which will print out /reports/batch/
9. See attached file for the expected stdout from RS server
10.

**Comment by JFU-NAVA-PBC** [comment]
[HistoryFunctions.kt.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGdIQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3de417036897fde12273a07df318f3b443a3c755/HistoryFunctions.kt.txt)

**Comment by JFU-NAVA-PBC** [comment]
Result from server output: attached

[listBlobs_output.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUVIQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aed9855049f74be9365d1c07b76b1c7f4d6e50d3/listBlobs_output.txt)

**Comment by JFU-NAVA-PBC** [comment]
Blob versioning:

blob versioning not supported with azurite v3 yet, so versioning has to be tested on staging e.g:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3NOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--253975e5044a80b0e009e2fd8067662b4f73b0fd/image.png)
