### ISSUE TITLE
Implement a function to recursively upload all the files in a directory

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#10489]
### User Story
As a report stream developer, I would like a function that accepts a directory (either from disk or a storage container) and uploads all the files.

### Description/Use Case
The schema syncing process will need to be able to add whole directories of files between disk and storage containers

### Dev Notes
If a file with the same name already exists in the target location, we should overwrite by default.

### Acceptance Criteria
- [ ] A new function exists for uploading all the files recursively in a directory to an storage container

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10489?planning-poker) with Zenhub @arnejduranovic @mkalish @brick-green @jack-h-wang @jimmyfagan @jalbinson @thetaurean

**Comment by Andrey-Glazkv** [comment]
Wait till 10/20 then take action (Andrey to email)
