### ISSUE TITLE
Identify all schemas that are used by a sender/receiver and create/verify input and output files

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#10483]
### User Story
As a report stream admin, I would like all currently used sender/receiver translation schemas to have sample input and output files to validate the schema

### Description/Use Case
As part of migrating the translation schemas to azure, every schema will need an input/output file for validation of changes.  The likely additions would be for introducing ones where there is only an end-2-end input/output. i.e. if there exists a sample input.hl7 and output.hl7, the work would be to to add an output.fhir and input.fhir.

### Dev Notes
Most of these likely already exist, but this is catch all ticket to verify that and add any missing ones.

### Acceptance Criteria
- [ ] Every sender or receiver translation schema has a dedicated input/output file and is added to the integration test

**Comment by jack-h-wang** [comment]
Per @victor-chaparro the NY receiver transforms are a work in progress and will be added to `translation-test-config.csv` once they are stable.

**Comment by jimmyfagan** [comment]
Sender transforms
- [x] `TILabOrder.yml`
  - Not currently tested, but is only a placeholder, not currently used.
- [x] `simple-report-sender-transform.yml`
  - `FHIR_to_HL7/sample_AOE_2_20230220-0001.fhir,,FHIR_to_HL7/sample_AOE_2_20230220-0001.hl7,metadata/hl7_mapping/receivers/STLTs/CA/CA-receiver-transform,HL7,PASS,"","","metadata/fhir_transforms/senders/SimpleReport/simple-report-sender-transform","",""`
  - 1 other
- [x] `elims-sender-transform.yml`
  - `HL7_to_FHIR_to_HL7/elims_40_4988249_33033.hl7,,HL7_to_FHIR_to_HL7/elims_40_4988249_33033-expected.hl7,metadata/hl7_mapping/ORU_R01/ORU_R01-base,HL7,PASS,"","","metadata/fhir_transforms/senders/CDC-ELIMS/elims-sender-transform","",""`
  - 10 others
- [x] `default-sender-transform.yml`
  - `FHIR_to_HL7/sample_AOE_1_20230220-0001.fhir,,FHIR_to_HL7/sample_AOE_1_20230220-0001-custom-datetime.hl7,metadata/hl7_mapping/receivers/STLTs/CA/CA-receiver-transform,HL7,PASS,"","","metadata/fhir_transforms/senders/default-sender-transform","development.DEV_FULL_ELR",""`
  - 4 others

Receiver transforms
- [x] `TILabOrder.yml`
  - `FHIR_to_HL7/sample_OML_20230831-0001.fhir,,FHIR_to_HL7/sample_OML_20230831-0001.hl7,metadata/hl7_mapping/receivers/Flexion/TILabOrder,HL7,PASS,"","","","",""`
- [x] `CA.yml`
  - Not currently in use, believe it is intended to be removed (https://nava.slack.com/archives/C025F5W5Q7L/p1698190515607079)
- [x] `CA-receiver-transform.yml`
  - `FHIR_to_HL7/sample_AOE_1_20230220-0001.fhir,,FHIR_to_HL7/sample_AOE_1_20230220-0001-custom-datetime.hl7,metadata/hl7_mapping/receivers/STLTs/CA/CA-receiver-transform,HL7,PASS,"","","metadata/fhir_transforms/senders/default-sender-transform","development.DEV_FULL_ELR",""`
  - 6 others
- [x] `CO.yml`
  - Not currently used, can likely be removed
- [ ] `NY-receiver-transform.yml`
  - Tests to be added as part of [this PR](https://github.com/CDCgov/prime-reportstream/pull/11946)
