### ISSUE TITLE
Implement a function that accepts source and destination directories and recursively copies all the files

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#10490]
### User Story
As a report stream developer, I would like a function that recursively downloads all the files in directory 

### Description/Use Case
There will be downstream work that needs to download a whole set of files in a directory when syncing schemas

### Dev Notes
Signature will be similar to `BlobAccess.copyBlob` but should operate on a whole directory rather than single blob

### Acceptance Criteria
- [ ] A new function exists that can download the files recursively between azure containers

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10490?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @jalbinson @jimmyfagan @mkalish @thetaurean

**Comment by JessicaWNava** [comment]
After writing a bunch of code, discovered there is already code that moves blobs form one blob dir to another, so just need to implement the download to the local dir.
