### ISSUE TITLE
Create a service method that accepts a schema type and recursively validates all the schemas using input/output files

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#10492]
### User Story
As a report steam developer, I would like a service method that accepts a directory and validates all the translation schemas

### Description/Use Case
This will be used by a few use cases downstream, but under the hood same validation should occur. For each schema, that includes an input.* and output.* file as a sibling, load that schema and the translation against the input and check that it exactly matches the output

### Acceptance Criteria
- [ ] A function exists that accepts a schema type and validates all the schemas in it

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10492?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @jalbinson @jimmyfagan @mkalish @thetaurean
