### ISSUE TITLE
Create the validate schemas command

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#10493]
### User Story
As a report stream admin, I would like a CLI command that can be used to validate all the schemas

### Description/Use Case
Details on how this command should work can be found [here](https://github.com/CDCgov/prime-reportstream/blob/8c1926d3969e8c466fd507d76034519efd5a3cf6/prime-router/docs/features/0005-managing-translation-schemas.md#L195), but at a high level this will be a tool used locally to validate changes and then consumed by a new CI step

### Dev Notes
This will build on top of the new service method to validate schemas

### Acceptance Criteria
- [ ] A CLI command `validateSchemas` exists that can be run against local, staging or production

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10493?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @jalbinson @jimmyfagan @mkalish @thetaurean
