### ISSUE TITLE
Create the sync schemas CLI command

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#10491]
### User Story
As a report stream admin, I would like a CLI command to sync schemas between the various environments

### Description/Use Case
This command is doing the heavy lifting for moving schemas between the environments.  The details of how it should work are [here](https://github.com/CDCgov/prime-reportstream/blob/8c1926d3969e8c466fd507d76034519efd5a3cf6/prime-router/docs/features/0005-managing-translation-schemas.md#L172)

### Dev Notes
The design doc has a verbose description of an example flow

### Acceptance Criteria
- [ ] A new `syncSchemas` command exists that can be used to move schemas between local, staging and production
- [ ] New validate schemas functions exist that will validate that
  - [ ] Updates the validation state if the new schemas are valid
  - [ ] Rolls back the schemas and resets the validation if the schemas are not valid
- [ ] End 2 end that executes all the steps

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10491?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @jalbinson @jimmyfagan @mkalish @thetaurean
