### ISSUE TITLE
Update all schemas to be valid file URIs

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#10508]
### User Story
As a report stream developer, I would no longer like to use relative paths while resolving schemas

### Description/Use Case
This captures the work of updating all the schema files in source code and replacing relative paths with file URIs

### Dev Notes
#11879 previously did this work but is out of date and needs to be redone

### Acceptance Criteria
- [ ] None of the schemas reference relative paths

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10508?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @thetaurean

**Comment by bishoyayoub** [comment]
@mkalish Please check with Jimmy/Arnej on follow up questions.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10508?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JFU-NAVA-PBC @luis-pabon-tf @mkalish @thetaurean
