### ISSUE TITLE
Add a translation schema validate to CI builds

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#10501]
### User Story
As a report stream developer, I would like translation schema validation to happen for a PR that changes a schema in the source code

### Description/Use Case
This will be a new step uses the schemas in the PR along with the schemas in the staging container and run the validateSchemas command.  This will be required to pass in order to merge

### Dev Notes
This could be added to an existing required action or introduced as a new one

### Acceptance Criteria
- [ ] Changes to schemas residing in source are validated against staging before a PR can be merged

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10501?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @mkalish @thetaurean
