### ISSUE TITLE
Remove sender upload page & from menu

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#10505]
## Problem statement

When a sender logs in they still see Upload in the menu and the page with this on it:
![image.png](https://images.zenhubusercontent.com/63b5ccd4948bff890cb806e2/bded13d7-5bdf-42ef-8a9c-56f7163e18e3)

This is no longer needed as this moved to SimpleReport a while ago.

## What you need to know

[This is the page you see when logged in](https://staging.reportstream.cdc.gov/upload)

## Acceptance criteria

- [ ] Page is removed and no longer in the menu when a sender is logged in

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
This has been removed.
