### ISSUE TITLE
MD - Revised request to ticket #9985. Exclude "no names"

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#10514]
## **Problem Statement**
We received a follow-up email in the ReportStream inbox stating they are still receiving unwanted messages from "careevolution" with "no names".  We probably need to update the filter to also exclude name values that are "blank, and/or empty".

## **What you need to know**
Please refer to ticket # 9985 which has been closed.  I believe this data may be going into the MD Secondary feed.

Email from Kristy (MD State):

Hello,

I am still seeing results from CAREEVOLUTION with no name. ex. dd6c49384e7c4b78b7f1f6d75ee6517a, 961accd67e4e4da68034390842c852ff
The collection date is 7/17/23.

Thanks,
Kristy

## **Acceptance Criteria**
Please make sure that MD is not receiving any data from Careevolution with no names or names with unknown (taken care of previously ticket # 9985).
Alert helpdesk so we can advice the user it's been updated.

## **To Do**
Assign to Engineer

## **Additional Comments**
If applicable, add screenshots, links, etc. to further explain the ticket

**Comment by kant777** [comment]
I will need to pair this up with someone since I am not seeing following message ids in the database for some reason.

dd6c4938-4e7c-4b78-b7f1-f6d75ee6517a

**Comment by kant777** [comment]
As @GilmoreA6 suggested we should have a meeting with MD

**Comment by sliu1000** [comment]
We (James) met with Kristy from MD today.  She will look to send us the message ID for the messages she's inquiring about.  As of now, we have not been able to locate the messages from "Careevolution" with the blanks. It's possible that the data is not coming from Reportstream.  However, Kristy will check.

**Comment by sliu1000** [comment]
Good morning,

 

I am sorry about any confusion. The CAREEVOLUTION ELRs are coming from a COVID Centralized ELR Reporter via AIMS. This does not seem to be related to Report Stream.

 

Thanks,

Kristy
