### ISSUE TITLE
Publish Release Notes - July 2023 - Content refinement

### ISSUE THREAD

**Issue by Andrey-Glazkv** [CDCgov/prime-reportstream#10521]
### Problem statement
As a user, I would like to know what features, bugs, other user facing updates have been made to ReportStream product.

### Procedure
https://docs.google.com/document/d/1vAiOJlfRMvJPRER3cr9Kr4lQ2-_ybNucJt28kI3fl1I/edit 

### Acceptance criteria
- [ ] Delivery Manager: Final Release Notes text (in ticket description) updated with all release notes and formatted with markdown
- [ ] Content Specialist: Approve release notes content and formatting

## Release Notes Text
**Improvements**

- Usability: The [API Programmer's Guide](https://reportstream.cdc.gov/resources/api), previously only available as a PDF download, is now part of the ReportStream website. The web pages provide a user-friendly format that ensures users always have the most updated information.

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
Items to mention:
- We have launched a pilot program receiving and sending Flu data through ReportStream! This is part of our continued efforts to expand our capabilities beyond COVID. If you're interested in receiving Flu data from ReportStream for your health department, contact us at ReportStream@cdc.gov.
- Bug Fix - The navigation on the mobile layout of the [API Guide](https://reportstream.cdc.gov/resources/api) has been fixed to no longer overlap with the content of the page.
- Enhanced documentation and guidance regarding [errors received when generating a signed JWT](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/examples/generate-jwt-python/jwt-errors.md) when onboarding to the ReportStream API have been added to Github and linked in the API Guide on the ReportStream website.
- The ReportStream [homepage](https://reportstream.cdc.gov/) has been updated to more accurately reflect the work we are doing and facilitate a more direct path to joining as a Sender or Receiver of data. And there are more improvements to come site-wide over the next couple months!

**Comment by Andrey-Glazkv** [comment]
@audreykwr - please review July's version of release notes below
cc @chris-kuryak 

New Features:

- We have launched a pilot program receiving and sending Flu data through ReportStream! This is part of our continued efforts to expand our capabilities beyond COVID. If you're interested in receiving Flu data from ReportStream for your health department, contact us at ReportStream@cdc.gov.
- Enhanced documentation and guidance regarding errors received when generating a signed JWT when onboarding to the ReportStream API have been added to Github and linked in the API Guide on the ReportStream website.
- The ReportStream homepage has been updated to more accurately reflect the work we are doing and facilitate a more direct path to joining as a Sender or Receiver of data. And there are more improvements coming to the website soon!

Bug Fix:

The navigation on the mobile layout of the API Guide has been fixed to no longer overlap with the content of the page.

**Comment by chris-kuryak** [comment]
Reviewed by Audrey
