### ISSUE TITLE
Revise design (if needed) of login page to have better instructions for users

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#10539]
## Problem statement

[Write a short description of what you want to achieve with this task]

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] Meet with Joseph to see what design changes are possible
- [ ] Revise design of login page if necessary to enable a better migration for users and document appropriately
- [ ] Facilitate handoff to Joseph for engineering

## To do

- [ ] ...

**Comment by jillian-hammer** [comment]
Shared for review via Slack on 9/11
@jpandersen87 @audreykwr @chris-kuryak 

- [User flow](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=3191%3A695&mode=design&t=qkDTGOuOcCy422W2-1) with design and content updates
- [Cheat sheet](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=3191%3A1280&mode=design&t=qkDTGOuOcCy422W2-1) with global design styles

**Comment by jillian-hammer** [comment]
Reviewed with the team and made revisions on 9/12
