### ISSUE TITLE
Create dashboard showing cost per message in production

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#10546]
This will probably be in metabase - basically we need to create a dashboard that shows the number of messages from the last 30 days/the total cost of prod in the last 30 days.

SQL for # of messages:
```
SELECT SUM("public"."report_file"."item_count") AS "sum"
FROM "public"."report_file"
WHERE ("public"."report_file"."sending_org" IS NOT NULL)
   AND (("public"."report_file"."sending_org" <> '')
    OR ("public"."report_file"."sending_org" IS NULL)) AND ("public"."report_file"."created_at" >= CAST((NOW() + INTERVAL '-30 day') AS date)) AND ("public"."report_file"."created_at" < CAST(NOW() AS date))
```

**Comment by dkrylovsb** [comment]
The dashboard is now in place and refreshes daily: https://prime.cdc.gov/metabase/dashboard/39-reportstream-costs
![image](https://github.com/CDCgov/prime-reportstream/assets/11096575/a1f8d1dc-c18f-4c8e-af49-54be2f45c7a8)
