### ISSUE TITLE
Add DAP script to all remaining public pages

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#10543]
## Problem statement

The Digital Analytics Program, or DAP, offers a tool to centralize all Analytics and Metrics tracking of government websites.  Currently we already have the script installed but it's limited to only the home page. This ticket's goal is to expand the scope of the tracking to all public pages.

DAP script: https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/components/header/DAPHeader.tsx#L17

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [More info about DAP](https://digital.gov/guides/dap/add-your-site-dap/)
- [Getting Started with Google Analytics](https://support.google.com/analytics/answer/9304153?hl=en)

## Acceptance criteria

NOTE: Acceptance can only be done with assistance by someone with DAP access (Chris Kuryak for now).

- [ ] Check which public pages are missing the DAP Google Analytics code snippet
- [ ] All public pages are sending data to DAP's Google Analytics instance
- [ ] Pages only available after login are NOT sending data to the DAP's Google Analytics instance

## To do

- [ ]

**Comment by chris-kuryak** [comment]
2 days left

**Comment by etanb** [comment]
https://github.com/CDCgov/prime-reportstream/pull/12146

**Comment by chris-kuryak** [comment]
@etanb I think we started on this yesterday, but the second acceptance criteria "All public pages are sending data to DAP's Google Analytics instance" may need you to have DAP access and we can double confirm everything is working.
