### ISSUE TITLE
Make content/design changes as needed to facilitate a better Okta migration for users

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#10540]
## Problem statement

Design and Content have created changes that need to be made to the website and Okta flows to facilitate a positive transition for users to the new Okta instance.

## What you need to know

This will be based on the change requests coming from Design and Content in these tickets:
- (#10537) Revise content of initial email to users
- (#10538) Revise content of login page to have better instructions for users
- (#10539) Revise design (if needed) of login page to have better instructions for users
- (#10541) Identify any changes/needs to the design/branding on rest of Okta instance needed for initial migration

Summary from Jillian:

- [User flow](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=3191%3A695&mode=design&t=qkDTGOuOcCy422W2-1) with design and content updates
- [Cheat sheet](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=3191%3A1280&mode=design&t=qkDTGOuOcCy422W2-1) with global design styles

## Acceptance criteria

- [ ] Content and components implemented and published
- [x] Update the asset logo in the Okta theme (get from Jillian)
- [x] Update the theme panel with new colors
- [ ] Move legal notice from the alert to the body of the page Login Page
- [ ] Repurpose the alert at the top of the page with the new content on the Login Page (DO NOT DEPLOY UNTIL 9/28 Deploy - captured in ticket #11340)
- [x] Update the content on the password reset alternate flow email
- [x] Update the content on the password reset normal flow email
- [x] Update the content of the automated activation email
- [x] Update content in the "Unable to Sign in" alert in the widget
- [x] Update remaining content per Figma file
- [ ] Update the ReportStream support page per Content update (#11069)

## To do

- [ ] ...

**Comment by jpandersen87** [comment]
@audreykwr @jillian-hammer I do not see in the given materials anything showing the desired look of the legal notice when moved out of the alert.

**Comment by jpandersen87** [comment]
engineer reference of highlights of improvements while preparing frontend for migration: https://docs.google.com/document/d/1FXj4QDLXD4Ym0xYo7OoFxsarec3_g3URGkiURt_jYhc
