### ISSUE TITLE
Transition existing partners to updated reportstream.cdc.gov

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#1054]
Now that we've got the newest version of ReportStream deployed, start scheduling partners to move over to the new site.

- List current `prime.cdc.gov` users
- Inform partners of new site and URLs via email
- ~~Do we need to host a training session? Do a walkthrough meeting?~~
- Monitor download site for stability/etc as users transition
- After 30 (?) days of all users successfully being transitioned, shut down`prime.cdc.gov`

**Comment by jlusds** [comment]
@ronaldheft-usds could you set up a redirect from https://prime.cdc.gov/download to reportstream.cdc.gov?

**Comment by ronaldheft-usds** [comment]
@jlusds Yes, I can have a PR set for that today.

**Comment by jlusds** [comment]
Thanks Ron!
________________________________
