### ISSUE TITLE
Review the unused Settings API Methods

### ISSUE THREAD

**Issue by luis-pabon-tf** [CDCgov/prime-reportstream#10599]
### User Story
As a ReportStream developer, I want to remove unused code to improve our codebase. If I see unused code that needs to remain, I want it to have a clear description.

### Description/Use Case
The Settings API are full of methods with no clearly-labeled uses anywhere in the codebase. If they are needed, they should have documentation explaining it.

### Dev Notes
The main file with unused code is `SettingsFunctions.kt`

### Acceptance Criteria
- All fully-unused methods related to the Settings API is gone
- Remaining methods have documentation

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10599?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @thetaurean
