### ISSUE TITLE
add Warnings on cases where the incoming value is not a valueset values, or otherwise fails validation (eg, testResult)

### ISSUE THREAD

**Issue by SpiderSense** [CDCgov/prime-reportstream#1061]
**Describe the bug**
Some keys, as part of waters-covid-19.schema, do not provide a WARNING on API POST to /api/reports.
The response comes back with empty strings for those keys.

**Impact**
Users submitting invalid data may not know the data is invalid. A warning should be displayed (as with the other keys). These keys produce an empty response, but are NOT included in the WARNINGS on the API POST response:

testResult
testOrderedDate
testResultDate
specimenSource
specimenCollectedDate
firstTest
previousTestDate
healthcareEmployee
hospitalized
symptomatic
congregateResident
congregateResidentType
pregnant
orderingProviderZip
performingFacilityZip
TXNTIMESTAMP

**To Reproduce**
Submit a POST with CSV file with invalid values, such as these randomized strings:

`Original request with _pii fields stripped out (used as expected values)
CSV Expected: {'SubmitterUID': 'SubmitterUIDuI9YyiWH_0', 'testId': 'testId6ZsmWZpu_0', 'testOrdered': 'testOrderedK7n706o3_0', 'testName': 'testNameQ4R780Rj_0', 'ordering_facility_state': 'ordering_facility_stateDXbBmW8G_0', 'ordering_facility_county': 'ordering_facility_countyGkGIDgKA_0', 'testResult': 'testResultla0AR4O5_0', 'testOrderedDate': 'testOrderedDateNTfIRsZO_0', 'testResultDate': 'testResultDateWx7fQP90_0', 'testReportDate': 'testReportDateQfp7Rp5S_0', 'deviceIdentifier': 'deviceIdentifierLBKZDeDa_0', 'deviceName': 'deviceNamez7ZoU0l0_0', 'patientUniqueId': 'patientUniqueIdqZfKaLVa_0', 'patientAge': 'patientAgeqSaEWkqR_0', 'patientRace': 'patientRaceR76KtQac_0', 'patientEthnicity': 'patientEthnicitynQs4ub46_0', 'patientSex': 'patientSexpT5d1OrH_0', 'PatZip': 'PatZipieMtp27e_0', 'PatStID': 'PatStIDQwEF1slN_0', 'patientCounty': 'patientCounty6QatBh7s_0', 'patientState': 'patientStateK3Swx33y_0', 'patientCity_pii': '', 'patientDob_pii': '', 'patientEmail_pii': '', 'patientHomeAddress_pii': '', 'patientHomeAddress2_pii': '', 'patientNameLast_pii': '', 'patientNameFirst_pii': '', 'patientNameMiddle_pii': '', 'patientPhone_pii': '', 'patientUniqueId_pii': '', 'specimenSource': 'specimenSourcedvh8zEaR_0', 'specimenId': 'specimenIddRFLE4Hq_0', 'serialNumber': 'serialNumberDcuQ4mU2_0', 'specimenCollectedDate': 'specimenCollectedDateCBXhmI7m_0', 'firstTest': 'firstTestT7FyVFTs_0', 'previousTestDate': 'previousTestDate1XbRXEyq_0', 'previousTestResult': 'previousTestResultNu1TGDZC_0', 'previousTestType': 'previousTestType1Fsnh5FB_0', 'healthcareEmployee': 'healthcareEmployee4LzKEMWE_0', 'healthcareEmployeeType': 'healthcareEmployeeType207LnrcH_0', 'hospitalized': 'hospitalizedVaDzaU1H_0', 'symptomatic': 'symptomaticQDsF5Lua_0', 'symptomsList': 'symptomsList410jx0Tn_0', 'symptomsIcu': 'symptomsIcuTCJEdSSQ_0', 'congregateResident': 'congregateResidentLAv410wM_0', 'congregateResidentType': 'congregateResidentTypeumgJ27vD_0', 'pregnant': 'pregnantzFYAlu1H_0', 'orderingProviderNpi': 'orderingProviderNpi3tt2tfl4_0', 'orderingProviderLname': 'orderingProviderLnamewmPuYt0H_0', 'orderingProviderFname': 'orderingProviderFnameVZFdoYs3_0', 'orderingProviderZip': 'orderingProviderZipXBHpzf7t_0', 'orderingProviderAddress': '', 'orderingProviderAddress2': '', 'orderingProviderCity': '', 'orderingProviderState': 'orderingProviderStatewkB0TiPO_0', 'orderingProviderPhone': '', 'performingFacility': 'performingFacilityzt3mbANz_0', 'reportingFacility': 'reportingFacilityDrz0FTWN_0', 'performingFacilityZip': 'performingFacilityZipcf8q8x7M_0', 'TXNTIMESTAMP': 'TXNTIMESTAMP00mxODJ0_0'}
`
Notice the WARNINGs in the response:

`POST response warnings: 
[['Invalid Code', "'patientRaceR76KtQac_0' does not match any codes for 'patient_race'"], ['Invalid Code', "'patientEthnicitynQs4ub46_0' does not match any codes for 'patient_ethnicity'"], ['Invalid Code', "'patientSexpT5d1OrH_0' does not match any codes for 'patient_gender'"], ["Invalid postal code 'PatZipieMtp27e_0'"], ['Invalid date', "'patientDob_piigvJxfFzI_0' for element 'patient_dob'"], ["Invalid phone number 'patientPhone_piiRsQNd1lc_0' for 'patient_phone_number'"]]
`
Diff the reequest data against the response (found in SFTP)

`CSV Results:  {'SubmitterUID': 'SubmitterUIDuI9YyiWH_0', 'testId': 'testId6ZsmWZpu_0', 'testOrdered': 'testOrderedK7n706o3_0', 'testName': 'testNameQ4R780Rj_0', 'ordering_facility_state': 'ordering_facility_stateDXbBmW8G_0', 'ordering_facility_county': 'ordering_facility_countyGkGIDgKA_0', 'testResult': '', 'testOrderedDate': '', 'testResultDate': '', 'testReportDate': '', 'deviceIdentifier': 'deviceIdentifierLBKZDeDa_0', 'deviceName': 'deviceNamez7ZoU0l0_0', 'patientUniqueId': 'patientUniqueIdqZfKaLVa_0', 'patientAge': 'patientAgeqSaEWkqR_0', 'patientRace': '', 'patientEthnicity': '', 'patientSex': '', 'PatZip': '', 'PatStID': 'PatStIDQwEF1slN_0', 'patientCounty': 'patientCounty6QatBh7s_0', 'patientState': 'patientStateK3Swx33y_0', 'patientCity_pii': '', 'patientDob_pii': '', 'patientEmail_pii': '', 'patientHomeAddress_pii': '', 'patientHomeAddress2_pii': '', 'patientNameLast_pii': '', 'patientNameFirst_pii': '', 'patientNameMiddle_pii': '', 'patientPhone_pii': '', 'patientUniqueId_pii': 'patientUniqueId_piiOZSdh2ZA_0', 'specimenSource': '', 'specimenId': 'specimenIddRFLE4Hq_0', 'serialNumber': 'serialNumberDcuQ4mU2_0', 'specimenCollectedDate': '', 'firstTest': '', 'previousTestDate': '', 'previousTestResult': 'previousTestResultNu1TGDZC_0', 'previousTestType': 'previousTestType1Fsnh5FB_0', 'healthcareEmployee': '', 'healthcareEmployeeType': 'healthcareEmployeeType207LnrcH_0', 'hospitalized': '', 'symptomatic': '', 'symptomsList': 'symptomsList410jx0Tn_0', 'symptomsIcu': '', 'congregateResident': '', 'congregateResidentType': '', 'pregnant': '', 'orderingProviderNpi': 'orderingProviderNpi3tt2tfl4_0', 'orderingProviderLname': 'orderingProviderLnamewmPuYt0H_0', 'orderingProviderFname': 'orderingProviderFnameVZFdoYs3_0', 'orderingProviderZip': '', 'orderingProviderAddress': '', 'orderingProviderAddress2': '', 'orderingProviderCity': '', 'orderingProviderState': 'orderingProviderStatewkB0TiPO_0', 'orderingProviderPhone': '', 'performingFacility': 'performingFacilityzt3mbANz_0', 'reportingFacility': 'reportingFacilityDrz0FTWN_0', 'performingFacilityZip': '', 'TXNTIMESTAMP': ''}`

DIFF Summary (change: key, (request string, response string)):
`[[('change', 'testResult', ('testResultla0AR4O5_0', '')), ('change', 'testOrderedDate', ('testOrderedDateNTfIRsZO_0', '')), ('change', 'testResultDate', ('testResultDateWx7fQP90_0', '')), ('change', 'testReportDate', ('testReportDateQfp7Rp5S_0', '')), ('change', 'patientRace', ('patientRaceR76KtQac_0', '')), ('change', 'patientEthnicity', ('patientEthnicitynQs4ub46_0', '')), ('change', 'patientSex', ('patientSexpT5d1OrH_0', '')), ('change', 'PatZip', ('PatZipieMtp27e_0', '')), ('change', 'patientUniqueId_pii', ('', 'patientUniqueId_piiOZSdh2ZA_0')), ('change', 'specimenSource', ('specimenSourcedvh8zEaR_0', '')), ('change', 'specimenCollectedDate', ('specimenCollectedDateCBXhmI7m_0', '')), ('change', 'firstTest', ('firstTestT7FyVFTs_0', '')), ('change', 'previousTestDate', ('previousTestDate1XbRXEyq_0', '')), ('change', 'healthcareEmployee', ('healthcareEmployee4LzKEMWE_0', '')), ('change', 'hospitalized', ('hospitalizedVaDzaU1H_0', '')), ('change', 'symptomatic', ('symptomaticQDsF5Lua_0', '')), ('change', 'symptomsIcu', ('symptomsIcuTCJEdSSQ_0', '')), ('change', 'congregateResident', ('congregateResidentLAv410wM_0', '')), ('change', 'congregateResidentType', ('congregateResidentTypeumgJ27vD_0', '')), ('change', 'pregnant', ('pregnantzFYAlu1H_0', '')), ('change', 'orderingProviderZip', ('orderingProviderZipXBHpzf7t_0', '')), ('change', 'performingFacilityZip', ('performingFacilityZipcf8q8x7M_0', '')), ('change', 'TXNTIMESTAMP', ('TXNTIMESTAMP00mxODJ0_0', ''))]]`

in the above example, testResult had a request value of 'testResultla0AR4O5_0' and an empty string as the response value.

**Expected behavior**
Values with invalid data, should produce a warning or an error in the API response.

**Additional context**
Comes back empty, but with warning on request:
patientRace
patientEthnicity
patientSex
PatZip

Comes back with value, even though _pii
patientUniqueId_pii

**Comment by jimduff-usds** [comment]
@tlosbo could you take a look at this one as well?  Thanks!

**Comment by jimduff-usds** [comment]
If a field is NOT required, then blank is "valid" and should not result in a warning.

However, @SpiderSense is right, if the data is there, but fails validation, that should be a friendly warning.

**Comment by MauriceReeves-usds** [comment]
@jimduff-usds - this was merged two weeks ago by @tlosbo Should we consider this issue closed?
