### ISSUE TITLE
Document Universal Pipeline Data Model

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#10629]
### User Story
As a stakeholder of ReportStream, I need to understand what metadata ReportStream captures and how it is stored.

### Description/Use Case
This story is different from #10270. Where as 10270 wants to document how to use and manage our database, this story not only wants to document how our database is architected but how it is used by the Universal Pipeline. 

### Dev Notes
If https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/10208 is completed, use the existing structure, otherwise put the doc in docs/features.

### Acceptance Criteria 
- [ ] Define content that should be in documentation and review with team before writing documentation
- [ ] A document exists on Metadata in regards to Universal Pipeline

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10629?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @mkalish @thetaurean @luis-pabon-tf
