### ISSUE TITLE
SFTP Check function fails for ALL

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1062]
When I execute the call to check all sftp connections, I sometimes get a failure back after 90 seconds. It appears to be an error with the front door timing out, so we don't get the results back that we want. This is, however, intermittent. Unfortunately, as we add more sftp sites, this will get worse, not better. I think it would be good to verify the cause of the failure is indeed the timeout, and if it is, look at potentially running these checks in parallel in order to collect them all before 90 seconds is over.

In order to run a check for all the sftp sites use the following command:

`curl -H "x-functions-key:<SECRET FUNCTION KEY>" "https://prime.cdc.gov/api/check?sftpcheck=all"`

You will need to get the function key in order to test this out.

**Comment by MauriceReeves-usds** [comment]
Acceptance criteria:

- Each check of a state is executed in parallel
- The results of each check is aggregated
- The call returns a JSON blob that contains the results for all the receiver checks

**Comment by jlusds** [comment]
What's the status of this?

**Comment by ronaldheft-usds** [comment]
@jimduff-usds @cwinters-usds This appears to be the issue we ran into during Thursday's deploy.
