### ISSUE TITLE
Refactor UP FHIRFunctions and Downstream Code

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#10638]
### User Story

As the Universal Pipeline, my pipeline steps should be architected so that there is no redundancy between the various step functions and each step should fully complete before kicking off the next step.

### Description/Use Case

This ticket is a result of https://github.com/CDCgov/prime-reportstream/issues/9778. While investigating this defect, it was determined that the issue is more pervasive than just the defect and the solution will require a larger refactor of FHIRFunctions and downstream code, hence this ticket. 

The cause of the defect is that one pipeline step starts running before the prior step has had a chance to commit to the database. See below for details on the specific exception referenced by the defect:

1. Convert Function, the step that runs before route, looks like this (FHIRFunctions.kt):
```kotlin
internal fun doConvert(  
    message: String,  
    dequeueCount: Int,  
    fhirEngine: FHIREngine,  
    actionHistory: ActionHistory = ActionHistory(TaskAction.convert)  
) {  
    val messageContent = readMessage("Convert", message, dequeueCount)  
    try {  
        fhirEngine.doWork(messageContent, actionLogger, actionHistory)  
    } catch (e: Exception) {  
        logger.error("Unknown error.", e)  
    }  
    recordResults(message, actionHistory)  
}
```
**In general, all UP steps defined in FHIRFunctions.kt follow this pattern.** The problem here is the DB write happens in `recordResults` but the next task gets scheduled in `fhirEngine.doWork`, hence the next step running before the prior step can wrap up its work. This is an issue for ALL steps, but is coming up in convert/route recently.

`insertReportFile` is the function that updates the `report_file` table, and that gets called eventually from doConvert's `recordResults`, but doConvert's fhirEngine.doWork schedules the route step before recordResults gets called:
```kotlin
messagesToSend.forEach { this.queue.sendMessage(elrRoutingQueueName, it.serialize()) }
```

### Dev Notes

**Potential Solution:**
We need to redesign the pattern of FHIRFunctions.kt in such a way that pipeline steps make sure to complete all DB writes prior to scheduling the next step via AQS.

The doWork for each FHIRFunction has redundant code, we should look to reduce the redundancy by factoring out and reusing the common code. It would be great if the code to update the DB could happen in one place, instead of being split between the doWork functions of each step and the doStep function in FHIRFunction.kt via recordResults.

Perhaps consider the template pattern as part of a potential solution? Have a base converter class that implements the common functionality between the converters but has a method called "doWork" that needs to be implemented by each child.

A solution should also examine
- making sure all inserts happen with the same transaction for a function invocation
- exceptions cause a transaction to be rolled back
- messages and blob store items are only added after a transaction has committed

### Acceptance Criteria

- [x] Refactored UP FHIRFunctions and downstream code to eliminate redundancy between functions and fix race condition
- [x] Removed Visibility timeout that was implemented in https://github.com/CDCgov/prime-reportstream/pull/10656 as a work around

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10638?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by bishoyayoub** [comment]
We will revisit this ticket and use as a case study to see if it expands across multiple sprints.
