### ISSUE TITLE
Content update: Release notes draft 1

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10644]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

After completing basic outlines for key pages and IDing the new site structure, we need to create the actual content that will go in the wireframes. This ticket captures the work of updating the content for the **Release notes**.

## Open questions
N/A

## Working links
-   [draft](https://docs.google.com/document/d/1YO_5GfX45dWkSE1OYcZSzA4nASgRtT-n9l4LgatPJJQ/edit)

## Acceptance criteria
-   [ ] Drafted finalized and reviewed with content owner and/or SME
-   [ ] Final draft presented to designer for next steps
-   [ ] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Comment by audreykwr** [comment]
updated to reflect final approval next sprint so closing this
