### ISSUE TITLE
Visual brand identity: Finalize palette

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10646]
## User story

As a ReportStream team member/user, I want to experience the ReportStream brand identity in a consistent and recognizable way.

## Background & context

**Goal:** Establish an identity that clarifies ReportStream's brand & offerings through a modern visual system built to scale.

This ticket captures the work of finalizing **brand identity palette** (i.e. color and typographic) for review.

## Working links

-   Mural: [Visual branding workspace](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1681847288631/0e18f2c3ba740da2a8d4bc02bdd9f55a28dfadc3?sender=u0c3cdba5126734aceb613229)
-   Deck: [Visual brand identity exploration](https://docs.google.com/presentation/d/1k5t6X2w4oICy_OVZafXxJ17-YXCneIitQ7mMNmzORlg/edit?usp=sharing)

## Acceptance criteria

-   [x] Color palette finalized
-   [x] Typography palette finalized
-   [x] Review with design and/or design lead
-   [x] Review with stakeholders

**Comment by chris-kuryak** [comment]
@jillian-hammer Is this still 8-points of work? Should we consider splitting up or just moving to next sprint? Seems like a lot of work to finish in this sprint if it hasn't gotten started.

**Comment by jillian-hammer** [comment]
Color palette captured in [[Sandbox] Visual identity design exploration deck](https://docs.google.com/presentation/d/1k5t6X2w4oICy_OVZafXxJ17-YXCneIitQ7mMNmzORlg/edit?usp=sharing) for final review in design crit.
