### ISSUE TITLE
Create Azure charts and logging around the download process in the batch function

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#10693]
### User Story
As a RS developer I want to have a way to quantify the differences in timing before and after changes to the batch function make in https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/10692

### Description/Use Case
Create some better logging around the download process and create some azure charts to show the before and after.

### Risks/Impacts/Considerations

Investigate and look to reuse existing Azure features for this instead of creating custom features.

### Dev Notes

An idea: Record the batch function start and end times, log them, and then track in azure dashboard based on log? Investigate if there is a better way to achieve this.

### Acceptance Criteria
- [ ] We can see the timing difference from before and after the changes made in https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/10692

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10693?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @luis-pabon-tf @mkalish @thetaurean

**Comment by JessicaWNava** [comment]
We decided we are going to use the charts that already exist for the overall batch function time. Also, there will be some logging added once we do the refactor since the refactor would change the logging anyways.
