### ISSUE TITLE
Download the messages during the batch step in parallel

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#10692]
### User Story
As a receiver and a RS developer I want the batch step to run quickly enough that it does not time out. One step in making this happen is downloading the message in parallel rather than one at a time. 

### Description/Use Case
https://github.com/CDCgov/prime-reportstream/issues/10305 has the full story, but essentially when a large number of messages are sent through RS the batch function starts timing out. After some digging into why, downloading came up as one of the areas taking the longest. To try to prevent the timeouts we want to download the messages in parallel. 

### Dev Notes
There are two places downloading happens during the batch step. Two places in in BatchFunction.batchUniversalData() then also in WorkflowEngine.createHeader() which is called from WorklowEngine.handleBatchEvent() which is called from BatchFunction.doBatch()

### Acceptance Criteria
- [ ] The messages are downloaded in parallel 
- [ ] ~~The code has been refactored to eliminate double-download, if possible.~~ moved to #11370
- [ ] Ultimately, we will use the overall timing of the batch function to determine the difference, but please also add logging on timing.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10692?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @luis-pabon-tf @mkalish @thetaurean
