### ISSUE TITLE
Navigation for the website redesign

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#10709]
## Problem statement

Create new top navigation bar. 

## What you need to know

**Content Updates**

- [See Figma for links and titles](https://www.figma.com/proto/Du7feM8huRDAAZCQcUIj93/Wireframes?node-id=225-822&scaling=min-zoom&page-id=221%3A453&starting-point-node-id=225%3A822&t=EGtNYSTKXF0pmcNS-1)

**Analytics**

- Use existing App Insights method to capture all link clicks 

**Storybook updates**

- Possibly make it into a Storybook component?

**Verification Steps**

- Global change should appear on all pages

**Acceptance Criteria:**

- [ ] Top Navigation dropdown links will anchor link to the appropriate section on the page if the page as a side nav
- [ ] Analytics / Metrics Required 
- [ ] Storybook update required
- [ ] Unit Tests
- [ ] Manual Testing Steps

**Dependencies**

 - [Figma for navigation blockframes](https://www.figma.com/file/86JATe4hOwPfihwwloM5b8/Blockframes?type=design&node-id=1006%3A4921&mode=dev)
- [Figma for top navigation bar](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Wireframes?type=design&node-id=12%3A2193&mode=dev)

**Additional Details**

The deployment strategy will follow the general deployment strategy for the Website Redesign EPIC. We will deliver the top navigation in isolation from the other pages.

**Comment by penny-lischer** [comment]
Per jillian - https://www.figma.com/proto/Du7feM8huRDAAZCQcUIj93/Wireframes?node-id=225-822&scaling=min-zoom&page-id=221%3A453&starting-point-node-id=225%3A822&t=EGtNYSTKXF0pmcNS-1

**Comment by chris-kuryak** [comment]
Updated to 8 points per Etan
