### ISSUE TITLE
HomePage Redesign

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#10711]
As a User,
I want to visit the ReportStream Homepage,
So that I can become informed about ReportStream and find more information.

**Content Updates**
- See [Figma](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?node-id=886%3A5587&mode=dev)

**Page Title**
- **CDC ReportStream - Homepage**

**Analytics**

- Page Load
- "Connect Now" Button Click
- "Get Started" Button Click
- "Connect with us" Button Click
- "Subscribe" Submission

**Storybook updates**

- TBD

**Verification Steps**

- Code Review
- Trail / Dev environment signoff by Product / Design
- Staging environment signoff by Product / Design
- Production environment signoff by Engineering, Product and Design

**Acceptance Criteria**

- [ ] Analytics / Metrics Required 
- [x] Storybook update required
- [x] Unit Tests
- [x] Manual Testing Steps
- [x] Convert to MDX
- [ ] Final Client Approval (See PM)

**Manual Testing Steps**
1. Log into RS
2. Homepage will appear
3. Clicking on a button will trigger the correct action
4. Clicking on a link will trigger the correct action

**Dependencies**

- Designs - https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Wireframes?type=design&node-id=1%3A17&mode=dev
- Platform API Endpoints - N/A

**Additional Details**
- The deployment strategy will follow the general deployment strategy for the Website Redesign EPIC. We will deliver the homepage in isolation from the other pages. 
- The Top Navigation is it's own separate ticket! https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/10709

**Comment by KeithNava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Web-Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/10711?planning-poker) with Zenhub @penny-lischer @etanb @jpandersen87

**Comment by etanb** [comment]
I've ranked this as a `5` with a big caveat: we remove the "subscribe" section. We don't have any functionality in place to capture email addresses and I don't believe we've approach who'd manage a newsletter etc yet. cc @chris-kuryak @KeithNava @jillian-hammer

**Comment by chris-kuryak** [comment]
@jillian-hammer Was there a plan in place as to how the "subscribe" functionality would work with the engagement team? Did y'all already have a plan/idea in place?

In @audreykwr draft I see it just commented as a "future capability". Shall we leave it out of this round of updates?

**Comment by jillian-hammer** [comment]
hi! we removed it from the latest wireframe since it was flagged as a bigger lift during a previous review. i updated the link in the main issue so hopefully it redirects y'all to the [current iteration](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Wireframes?type=design&node-id=310%3A2916&mode=design&t=598TYXdXVcw2gXcF-1). 🤞 

@etanb @chris-kuryak

**Comment by chris-kuryak** [comment]
Thank you @jillian-hammer!

**Comment by penny-lischer** [comment]
End to End Tests will be done in another ticket.

**Comment by penny-lischer** [comment]
@chris-kuryak which Analytics / Metrics did you want to be captured?

**Comment by chris-kuryak** [comment]
I think we discussed this a little bit, but tracking button clicks would be the only thing on top of our regular analytics.
@KeithNava we have the SPIKE coming up to determine how to do that for all pages moving forward. So as long as that does not get lost and we can start tracking button clicks within a sprint or two, up to y'all on how you want to deploy this page.

**Comment by chris-kuryak** [comment]
Client/PO feedback from 8/17:

Improvements for future releases:
1. Hero Image: "Connect Now" button contrast is bad. And hovering actually makes it worse. It may fail a contrast check. Need to increase contrast on the blue button with blue background.
2. Ideally, we don't want our users to be linking out of our website after their first interaction. Considering embedding forms into our website in the future.
3. The new Smartsheet Onboarding Form first page says "submit" as the button at the bottom, but it takes you to a new page for more information. Consider changing to "Next".
4. The new Smartsheet Onboarding Form does not indicate how many pages are part of the form. Consider adding page numbers or some indication of a user's progress through the form.
5. The new Smartsheet Onboarding Form has a standard success message upon finishing. It does not indicate anything specific to ReportStream or what the user should expect to happen next. More informative (RS specific) text would be better.
6. The new Smartsheet Onboarding Form keeps you in the form upon finishing successfully. Instead, the user should be redirected to the ReportStream website.
7. The button clicks are not currently being tracked. Consider tracking them in the near future to help track how users are interacting with our website.
8. Does SmartSheet indicate/track progress of how far someone gets through a form if they don't complete it successfully? Would be useful for tracking user interaction and engagement.
9. Why do the calls to action have different text when they both lead to the same place? One says "Connect Now" and the other says "Get Started".
10. The text "Public Health Entities" is "hanging" on the page, seems disjointed from rest of page.
11. The quote at the bottom of the page appears to be hanging as well and somewhat disjointed from the rest of the page.
