### ISSUE TITLE
Plan and execute update to Java 17

### ISSUE THREAD

**Issue by jack-h-wang** [CDCgov/prime-reportstream#10719]
### User Story
As ReportStream, I want to be on the latest supported Java release so that we can make use of the latest language features and security updates.

### Description/Use Case
RS is currently targetting Java 11. The latest release of Java supported by Azure is Java 17 (see [compatibility chart](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-java?tabs=bash%2Cconsumption#supported-versions)). With active support for Java 11 ending in September, we should plan to migrate to Java 17.

### Risks/Impacts/Considerations
It may be necessary to update other dependencies in the codebase if there are any that do not have Java 17 support.

### Dev Notes
The work can be built from #7539. This will additionally require updates to the GitHub actions to set up a Java 17 environment in CI.

### Acceptance Criteria
- [ ] A test plan has been created for updating and deploying to Java 17 and has been reviewed by DevOps.
- [ ] A Java 17 deployment to a demo environment has been completed and tested.

**Comment by snesm** [comment]
Active support for Java 11 ends 30 Sep 2023.  Security support will continue for three years.

Some tools (SonarCloud) appear to be ending support for Java 11 "_soon_".

**Comment by jack-h-wang** [comment]
On 8/21 I merged #10992 to `master` to apply the changes. While monitoring Jeremy and I discovered the build was failing, and traced the issue to the build image, which has not been updated since 7/13/2021. I reverted the merged changes pending completion of a new build image.

**Comment by jack-h-wang** [comment]
#11141 is merged, which should complete the update to Java 17.
