### ISSUE TITLE
Website redesign: Plan usability testing

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10722]
## User story

As a ReportStream designer/researcher, I want to conduct usability testing of the ReportStream website's redesign so that we can incorporate user feedback into the ongoing content/design development of the website.

## Background & context

The ticket captures the work of putting together a research plan for the RS website redesign. 

## Open questions

-   What is the timeline?
-   How many participants? 
-   What impact does the PRA process have?

## Working links

-   Document: [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit?usp=drive_link)

## Acceptance criteria

-   [x] Plan draft completed in accessible document
-   [x] Plan draft reviewed by design and/or design lead

**Comment by audreykwr** [comment]
[Draft](https://docs.google.com/document/d/1d34d1qZqF5MdOx6l32venfMB8-PwI2yqwkWYqg72irk/edit) done.
[Follow on ticket created](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/10914)
