### ISSUE TITLE
Write documentation for Onboarding a receiver to the Universal Pipeline

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#10743]
### User Story
As  a ReportStream employee, I want to understand how to onboard a receiver to the UP. 

### Description/Use Case
Create a document that describes how to onboard a receiver to the  UP. This should be similar to the current process we have for the Covid pipeline and should be able to re-use existing documentation we have.

### Risks/Impacts/Considerations
See the documentation skeleton for some help on where to start. https://docs.google.com/document/d/1Xr2defgjUjarZgyROqOqM1Cezx_hp6S_Gd3Ue8bik64/edit#heading=h.5vwvb1bhxtdl

### Dev Notes
There is a placeholder in the repo to store this info under docs/onboarding-users/receivers.md 

### Acceptance Criteria
- [ ] Define content that should be in documentation and review with team before writing documentation
- [ ] There is a document that describes how receivers should be onboarded to the UP

**Comment by brandonnava** [comment]
@victor-chaparro @GilmoreA6 @oslynn How is the documentation effort going? Can someone point me to updates I can see? cc: @LaFreda1

**Comment by GilmoreA6** [comment]
@brandonnava PR#11230 is open for okta account creation and sender pieces. https://github.com/CDCgov/prime-reportstream/pull/11230

**Comment by cloudmagic80** [comment]
@brandonnava  I'll start working again. . I've created a subticket for my subportion
https://app.zenhub.com/workspaces/engagement-6166edbd409257001e09f1b2/issues/gh/cdcgov/prime-reportstream/11179

**Comment by brandonnava** [comment]
Sweet thanks @GilmoreA6 @cloudmagic80 If others have sub tickets they want to share hear that would also be great!

**Comment by cloudmagic80** [comment]
The Receiver configuration documentation is up for review in github. The google UP technical docs has also been updated.
