### ISSUE TITLE
Only set sending-application-namespace-id if MessageHeader.source.name is populated

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#10770]
### User Story
As a sender, I don't want the MSH source overwritten

### Description/Use Case
Currently, the default transform will always set the sending application to report stream and we had to specifically override that behavior for ELIMS.  Realistically, we should only populate that field with report stream when the sender does not include it.

### Dev Notes
See [this](https://github.com/CDCgov/prime-reportstream/pull/10655/files#r1280711293) comment

### Acceptance Criteria
- [ ] The default sender transform only populates the sending application with reportstream if the sender does not include it

**Comment by bishoyayoub** [comment]
Need to set up meeting with Arnej/Kalish/Avniel.

**Comment by mkalish** [comment]
This is no longer relevant as the new mappings are handling this correctly.
