### ISSUE TITLE
Update CI\CD Pipeline to use Java 17

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#10815]
Find all the places we're using Java and update the JDK to use v17

**Comment by jeremy-page** [comment]
We do not want to merge this change until after discussing at EngSync

**Comment by lucasdze** [comment]
As per the latest comment on the PR, Jack is requesting to Please update [the action hash for sonarcloud-github-action](https://github.com/CDCgov/prime-reportstream/blob/master/.github/workflows/sonarcloud_master.yml#L58).
