### ISSUE TITLE
MN - Phone Number and Accession Number concerns

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#10823]
## **Problem Statement**
We received an inquiry from Minnesota regarding issues with their file. Described below:

MSH 4.0 - has a phone number instead of sender name in the HL7 file. I confirmed in the SimpleReport file that the data was entered with the phone number. So it's a user entry error. ![image.png]
(https://images.zenhubusercontent.com/6282728600f2331155d73bf3/f8c5d153-872a-4627-84f8-2be8e6959bbb)

Also, user stated that the accession and control id's have +'s in them. Please see below:
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/33fec9b8-f0df-450e-98ee-952d3795a85a)

## **What you need to know**

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/6ba3d280-3034-44fa-82d0-746352df2080)

I checked the MN HL7 file dated 8/1/2023 and confirm that the + are present in the file. Not sure if this is abnormal or not.

We have reached out to the Lab which was sent via SimpleReport for resubmission but have not heard back from them yet.

## **Acceptance Criteria**

1. Confirm whether the Accession ID/Control ID formatting is abnormal.
2. Make sure that the phone numbers find in the HL7 file to MN is not due to Reportstream.
3. Helpdesk has asked Lab "Child and Teen" to resubmit their incorrect data and waiting for confirmation.

## **To Do**
Please assign Engineer to 1 and 2

**Comment by oslynn** [comment]
@sliu1000 would you please ask MN to give us the MSH-10 list in text instead of image.  Therefore, I can copy any paste 
![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/9c55e241-e7d0-43ac-a28a-bff904569441)

**Comment by sliu1000** [comment]
<html>
<body>


MSH.10 | ORC.3.1
-- | --
206173+1+20230509 | 206173
209237+2+20230509 | 209237
204946+3+20230509 | 204946
84644+4+20230509 | 84644
204560+5+20230509 | 204560
204665+6+20230509 | 204665
208579+7+20230509 | 208579
208578+8+20230509 | 208578
210990+9+20230509 | 210990
211027+10+20230509 | 211027
209437+11+20230509 | 209437
199048+12+20230509 | 199048
188887+1+20230525 | 188887
77397+1+20230605 | 77397
78815+1+20230614 | 78815
77397+1+20230713 | 77397
211799+1+20230731 | 211799
54414+2+20230731 | 54414


</body>
</html>

**Comment by oslynn** [comment]
Done. I am closing the ticket
