### ISSUE TITLE
 Add Puerto Rico to "where we're live"

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#10845]
## Problem statement
Puerto Rico is now live and needs to be updated on the SVG map and text list on ReportStream's public facing web page "Where We're Live."

## What you need to know
**Important notes**
Documented processes with instructions on creating a PR can be found in [this Sharepoint doc](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Onboarding%20%26%20Ops/Scrum/Processes%20Documented/Update%20SVG%20Map%20and%20List%20Process.docx?d=w9640218c586e42b09fcc0324d8c7b4f5&csf=1&web=1&e=VEp7lB)

## Acceptance criteria

- [ ] SVG map and text list show Puerto Rico as "live" on these pages:
- [ ] https://reportstream.cdc.gov/
- [ ] https://reportstream.cdc.gov/how-it-works/where-were-live

## To do
- [ ] Engr to create PR ([see instructions](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Onboarding%20%26%20Ops/Scrum/Processes%20Documented/Update%20SVG%20Map%20and%20List%20Process.docx?d=w9640218c586e42b09fcc0324d8c7b4f5&csf=1&web=1&e=VEp7lB))
- [ ] Exp. engr to Review/QA the PR

**Comment by cloudmagic80** [comment]
Waiting on getting access to the map
https://cdc.sharepoint.com/teams/USDSatCDC/_layouts/15/AccessDenied.aspx?Source=https%3a%2f%2fcdc.sharepoint.com%2f%3aw%3a%2fr%2fteams%2fUSDSatCDC%2fShared+Documents%2fPRIME+ReportStream%2fOnboarding+%26+Ops%2fScrum%2fProcesses+Documented%2fUpdate+SVG+Map+and+List+Process.docx%3fd%3dw9640218c586e42b09fcc0324d8c7b4f5%26csf%3d1%26web%3d1%26e%3dVEp7lB&correlation=ae2ecfa0-506e-4000-17ab-e443569ad036&Type=item&name=603e4f84-8849-480d-80a9-5bfb0272fb18&listItemId=324195&listItemUniqueId=9640218c-586e-42b0-9fcc-0324d8c7b4f5
