### ISSUE TITLE
PA - MUSER PW Expiring

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#10841]
## Problem statement

Muser's pw expiring

## What you need to know

users whos pw are expiring are RptStreamSewsprod, pareportstream.

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] ...

## To do

assign to engineer and reset pw's

**Comment by adegolier** [comment]
@Jcavallo7 Can I please get some more info on this? Both the links go nowhere and I'm not sure what MUSER is.

**Comment by Jcavallo7** [comment]
@adegolier Its about users passwords expiring on https://edcpwdmgr.pa.gov/, and needing to be updated there and in the azure vault.

**Comment by adegolier** [comment]
That's not the same portal I was given for updating PA's passwords, but did this yesterday. Moved to awaiting confirmation because I want to give it a day or so to make sure it's working as expected since I can't run the check on a SOAP based transport.
