### ISSUE TITLE
Make the code "enhancing" the bundle more maintainable and extensible

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#10849]
### User Story
As a RS developer, I want a maintainable and extensible way of handling things like enhancing the bundle metadata and handling the birthtime. 

### Description/Use Case
There may be other cases where post translation to FHIR we need to parse the HL7 message, do some work on it to get a value, and then update the output FHIR message before completing the conversion. We want to figure out a more maintainable and extensible way to handle this.

### Dev Notes
Arnej's idea: Instead of updating translate every time we need to do something similar, I'm imagining a separate class that handles this. The class could be called something like `BundleEnhancer` and usage could be `BundleEnhancer.run()` and the run method would run all the methods like `handleBirthTime`. This way at least we don't have to update translate every time and then we can expand on this mechanism and make it even better, maybe. Also this way we are acknowledging that our business case requires us to do some sort of post conversion cleanup (I don't like cleanup hopefully we can think of a better word) and we can split this functionality out to be its own thing so everything is more cohesive.

Another note here is we may have a fork of the LinuxForHealth HL7 -> FHIR converter soon, and a lot of these solutions, like `handleBirthTime`, should be addressed there whenever possible and `BundleEnhancer` or its equivalent solution should be used as a last resort.

### Acceptance Criteria
- [ ] The code that "enhances" the bundle in moved out of the translate function
- [ ] The code is now extensible

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10849?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by bishoyayoub** [comment]
@arnejduranovic @avnieldravid Please revisit priority.
