### ISSUE TITLE
Investigate GHA to Check Key Vault Certificates Expiration failure

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#10857]
Getting the following error when trying to add the IP of the Github runner to the Key Vault firewall:
`Message: The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.`

**Comment by lucasdze** [comment]
I am not seeing any failure. We are not getting notifications just because there no cert expiring in the next 30 days
[the "add runner ip to firewall" step also runs successfully](https://github.com/CDCgov/prime-reportstream/actions/runs/6419724542/job/17430176381)
