### ISSUE TITLE
Wireframe: Support/FAQ

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10882]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

This ticket captures the work of creating a high-fidelity wireframe of the **Support landing page** to review with design, engineering, and product before moving to implementation. Previously, the landing page was completed with a simple barebones card design (see [Figma](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=1267%3A3396&mode=design&t=oaE1uhsUhwsV6zy0-1)). However, after further UX/UI consideration and timeline changes, we have the capacity to combine the **FAQ and Support page** into one consolidated landing page.

## Open questions

-   What kind of in-page navigation is needed / necessary? In-page side navigation? Jump links? Simple Back-to-top link? 

## Working links

-   Inspiration reference: [SimpleReport's Support section](https://www.simplereport.gov/support/)
- Figma: [Working file](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=0%3A1&mode=design&t=oaE1uhsUhwsV6zy0-1)
-  Content doc: [FAQ/Support](https://docs.google.com/document/d/1_G_A8GdZGnNoS5LIqPcM_xNVqqKOuFS_7qayRD0nQr0/edit#heading=h.iplmcabwi3j4)

## Acceptance criteria
**Design**
-   [x] Support page represents the range of USWDS and custom components (if needed)
-   [x] Support page is dev ready before handoff (i.e., items for future iterations identified for backlog and removed from handoff document)
-   [x] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Review**
-   [x] Reviewed with design and/or design lead
-   [x] Reviewed with content strategist for final approval
-   [x] Reviewed with product and engineering

**Comment by yudonoodles** [comment]
On 08/23 reviewed the design with Jillian.

This morning 08/24 shared a preview of the prototype (async to cdc-reportstream-website-redesign-q3-23 channel). 

[Figma prototype link](https://www.figma.com/proto/Du7feM8huRDAAZCQcUIj93/Website-Redesign?page-id=1621%3A8112&type=design&node-id=1767-17676&viewport=1439%2C848%2C0.31&t=mN3pnW10jhCuq5Sc-8&scaling=min-zoom&starting-point-node-id=1767%3A2454&hide-ui=1)

Cards on top with links can be used to navigate throughout the page. Clicking link opens up the accordion to reveal content within it.

**Comment by yudonoodles** [comment]
08/25 During today's webex eng sync spoke to eng about feasibility of jumping from a link in a card to either an accordion open state or jump to a section (an h2 element). Takeaway is that it is doable to add that functionality. 

Status: Waiting for content approval. Audrey will follow up with Sharon and/stakeholders to confirm content.

**Comment by yudonoodles** [comment]
Updated design + content based on feedback from Audrey. Shared update via slack on. Final content updates are on [this document](https://docs.google.com/document/d/1_G_A8GdZGnNoS5LIqPcM_xNVqqKOuFS_7qayRD0nQr0/edit#heading=h.iplmcabwi3j4)

**Status**: Need confirmation on links and any remaining links that need to be added from Audrey. Waiting to close.
