### ISSUE TITLE
Wireframe update: About

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10883]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

This ticket captures the work of updating the existing [About landing page](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=225%3A822&mode=design&t=oaE1uhsUhwsV6zy0-1)'s content per stakeholder feedback and preparing the Figma for dev ready handoff. 

## Working links

- Figma: [Working file](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=225%3A822&mode=design&t=oaE1uhsUhwsV6zy0-1)
-  Content doc: [About](https://docs.google.com/document/d/1TYkZJDFhPq53JofDNPMpGb8laVajIisQPZShtc87DqI/edit#heading=h.deiq74qdqmqn)

## Acceptance criteria
**Design**
-   [x] Design is ready for handoff (i.e. dev ready)
-   [x] Design includes latest content updates
-   [x] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Review**
-   [x] Reviewed with design and/or design lead
-   [x] Reviewed with content strategist for final approval
-   [x] Reviewed with product and engineering

**Comment by jillian-hammer** [comment]
labeling as blocked, awaiting stakeholder approval

**Comment by yudonoodles** [comment]
Besides content approval, also needing to figure out either an image/illustration to go with the section "How ReportStream started." @audreykwr will be following up with stakeholder if we can use an image e.g. stacks of paper.

**Comment by yudonoodles** [comment]
08/29 During webx design sync, learned that the image we were planning on using is not clear/high res enough for site. In the interim, no image will be used for the section: "How ReportStream started."

- Received [updated content](https://docs.google.com/document/d/1jDgqAcy-01sI9uS2k8zo5byuNrTSe4wIqazHNYPiwqg/edit#heading=h.deiq74qdqmqn), a new file stripped of all the back and forth comments, to be used
- Status: updated content! Need to resolve one question regarding a link on the page from Audrey.
