### ISSUE TITLE
Wireframe: Footer

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10906]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

This ticket captures the work of revisiting the footer design and adding a persistent callout to the contact us.

## Open questions

-   What is the historical background on the other footer links? 

## Working links

-   [Figma working space](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=0-1&mode=design)
-   Content TBD

## Acceptance criteria
**Design**
-   [x] Footer design includes contact us CTA
-   [x] Footer design includes legally required links
-   [x] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Review**
-   [x] Reviewed with design and/or design lead
-   [x] Reviewed with content strategist for final approval
-   [x] Reviewed with product and engineering

**Comment by yudonoodles** [comment]
On 08/23 reviewed the design with Jillian. 
This morning 08/24 shared a preview of the prototype I created to show the expandable cards and how they can be used to navigate to particular sections of the page. Clicking link opens up the accordion to reveal content.

[Figma prototype link](https://www.figma.com/proto/Du7feM8huRDAAZCQcUIj93/Website-Redesign?page-id=1621%3A8112&type=design&node-id=1767-17676&viewport=1439%2C848%2C0.31&t=mN3pnW10jhCuq5Sc-8&scaling=min-zoom&starting-point-node-id=1767%3A2454&hide-ui=1)

**Comment by yudonoodles** [comment]
@audreykwr Can you provide the copy for contact us? I am considering what we want to show (link versus button components) and how long the text is before deciding on a layout.

**Comment by chinelo-ikejimba** [comment]
Footer A works great, let's go with that one for the footer. Nice work @yudonoodles.

**Comment by yudonoodles** [comment]
- Copy is updated!
- Moved the final design to Ready for dev space and marked it appropriately on [Figma ](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=2236%3A13651&mode=design&t=O7SntAHwjDWdP44u-1)
