### ISSUE TITLE
Clarify/refactor handling of duplicate elements in ConfigSchemas

### ISSUE THREAD

**Issue by jimmyfagan** [CDCgov/prime-reportstream#10918]
### User Story
As a RS developer, I want clarity on what the expected behavior should be when multiple elements (either nested or not) exist with the same name in a config schema.

### Description/Use Case
`ConfigSchema` has a property called `duplicateElements` which is used to enforce a requirement that multiple elements don't exist with the same name. This ticket aims to investigate the need for this restriction, and ensure that errors are thrown consistently between tests (like `test transform` with nested schemas in `FhirTransformerTests` and `test convert` in `FhirToHl7ConverterTests`) and the running application using real schemas.

### Risks/Impacts/Considerations
We should be careful to consider reasons to keep some kind of restriction here, we don't want to open the possibility of something that causes unwanted behavior.

### Dev Notes
We should also consider refactoring the duplicate element checking in `FhirTransformer.transform` and `FhirToHl7Converter.convert` to reduce duplicate code and make it easier to debug.

### Acceptance Criteria
- [x] The need for duplicate element restrictions has been assessed
- [x] Any tests that trigger error conditions for duplicate elements can also be replicated by a running server
- [x] Behavior has been documented (either in the docs, or by comments on tickets related to documenting these schemas #10215)

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10918?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @mkalish @thetaurean

**Comment by luis-pabon-tf** [comment]
These tickets are thematically related and may be worth looking at for reasoning of duplicate handling in some places: 
#7245 and #6139

**Comment by jimmyfagan** [comment]
Good finds @luis-pabon-tf ! In the PR comments [here](https://github.com/CDCgov/prime-reportstream/pull/10840/files#r1290073560), Michael pointed out that overriding multiple elements with a single override was useful for the purposes of that ticket. These schemas and nested schemas and overrides and extensions are all confusing, so it might be that these are considered to be separate concepts or something, but anyway, hopefully this and other related tickets can get into all of that and also document more about how this actually works.
