### ISSUE TITLE
Website Redesign - Managing your connection

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#10911]
As a User,
I want to visit the ReportStream **Managing your connection** Page,
So that I can become informed about the tools available to me to manage my account

Designs
- Figma Link: https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=1267-6590&mode=design

Content Updates
- [See Figma Link](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=1267-6590&mode=design)

Page Title
- "CDC ReportStream - Managing your connection" 

Analytics
- TBD 

Storybook updates
- TBD

Verification Steps
- Signed off in Staging by Product / Design
- Signed off in Production by Product / Design / Engineering

Acceptance Criteria:
- [ ] Analytics / Metrics Required - TBD
- [ ] Storybook update required - n/a
- [ ] Unit Tests - n/a
- [ ] End to End Tests - TBD
- [x] Manual Testing Steps

Dependencies:
- Designs - https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=1267-6590&mode=design
- Platform API Endpoints - N/A
- Links - TBD

Additional Details:
- The deployment strategy will follow the general deployment strategy for the Website Redesign EPIC. We will deliver this page in isolation from the other pages. 
- Conversion to MDX will be determined by the Engineer owning this ticket

**Comment by KeithNava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Web-Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/10911?planning-poker) with Zenhub @etanb @jpandersen87 @penny-lischer

**Comment by jillian-hammer** [comment]
**Image assets**

Submission History:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmdoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--10e3c4ba23eac270867e7bc492ede2f4f6d1fd78/SubmissionHistory_20230821.png)

Daily Data:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblloIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8d85dfa1e0de571408681d30ebf5543eeb13f216/DailyData_20230821.png)

**Comment by penny-lischer** [comment]
Test Steps:

1. Log into RS
2. navigate to /manage-connection
3. Click links within page and validate that they open the correct page

**Comment by KeithNava** [comment]
Re-opening to address these outstanding comments: https://github.com/CDCgov/prime-reportstream/pull/11022#issuecomment-1693431697
