### ISSUE TITLE
Write Up Data Dashboard Release Email

### ISSUE THREAD

**Issue by brandonnava** [CDCgov/prime-reportstream#10937]
The ReportStream website is about to get an upgrade to the Daily Data feature, upgrading to become the Data Dashboard. Our current Okta users will need to be notified of the upgrade and given a quick reference to where this feature can be found. Support will write up the comms to be reviewed and supported by Experience, then once the the dashboard goes live at the end of this sprint we will send out the email.

**Comment by sliu1000** [comment]
@brandonnava Received.  Will work on. Do you have an approximate date you'd like us to send this out? Like a day before or day of, when we go live?

**Comment by brandonnava** [comment]
Ty! Some users will probably want to act on it right away so we'll wait to send it out until after the page is officially live

**Comment by sliu1000** [comment]
@brandonnava when's the live date?
