### ISSUE TITLE
Verify accuracy of new RS instance

### ISSUE THREAD

**Issue by Andrey-Glazkv** [CDCgov/prime-reportstream#10938]
## Problem statement

[Write a short description of what you want to achieve with this task]

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
This ticket no longer needed.
