### ISSUE TITLE
Clean up translation integration tests for UP

### ISSUE THREAD

**Issue by jimmyfagan** [CDCgov/prime-reportstream#10943]
### User Story
As a ReportStream developer, I want integration tests to clearly verify necessary behavior, and I don't want to maintain integration tests for abandoned pilots.

### Description/Use Case
Many integration tests in the UP have historically been sample data from Colorado. These tests are based on a pilot that never happened, so now that we have some other sample data and integration tests for the UP (from ELIMS and CA), the old Colorado cases don't serve much purpose, and have become difficult to maintain as we work through tech debt and improve the losslessness of the UP for new pilots. Additionally, while it may be useful to have tests that verify that things work as expected for a given use-case of the UP, it may also be useful to have integration tests that are more based on some feature of the data, rather than just a particular sender/receiver combination.

### Risks/Impacts/Considerations
We shouldn't remove so many integration tests as to lose a "safety net" of making sure we're handling a variety of cases appropriately. We couldn't possibly cover all the possibilities of segments and fields present/missing from a message, so some variety in tests helps our confidence that things are working.

### Dev Notes
Some CA tests (particularly FHIR->HL7) utilized the Colorado data. We should be sure to work with Victor or others in the loop with CA/Simple Report before removing any of those.

### Acceptance Criteria
- [ ] Translation tests for the UP in the integration tests each serve a clear purpose (either related to an in-progress or fully active sender/receiver use-case, or related to a particular feature of the data)
- [ ] We have coverage for a reasonable variety of messages.
- [ ] Non-standard mappings that only served to support outdated tests have been removed or adjusted (see [this comment](https://github.com/CDCgov/prime-reportstream/pull/11093#discussion_r1307582794) based on OBX.2)

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10943?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @thetaurean

**Comment by bishoyayoub** [comment]
@arnejduranovic Can you help refine this ticket for grooming?

**Comment by arnejduranovic** [comment]
Looking at this again, I think the AC is fine. It's also important to note that each sender/receiver translation schema will have tests run automatically once the following epic is implemented: https://github.com/CDCgov/prime-reportstream/issues/10481

**Comment by bishoyayoub** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10943?planning-poker) with Zenhub @mkalish

**Comment by jimmyfagan** [comment]
Hey Gabriel, where do things stand on this ticket? We're at the point on the [HCI changeset](https://github.com/CDCgov/prime-reportstream/pull/11174) that we'll need to make adjustments to translation tests to pass CI failing, and it's probably going to overlap with this a fair bit.
