### ISSUE TITLE
Test HCI HL7 messages through the UP

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#10963]
### User Story
As HCI, I would like the incoming HL7 message match the outgoing HL7 message.

### Description/Use Case
We want to run sample messages sent by the HCI team through RS and validate that no data is lost once the message undergoes the translation to internal FHIR and back to HL7v2. If data is lost, we want to update the HL7->FHIR or FHIR->HL7 mappings to fix the issue.

### Risks/Impacts/Considerations
- Some differences between the input HL7v2 and output HL7v2 messages may be okay.

### Dev Notes
- Sample message [HCI-sample-message.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcllUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9f6cdf254ae8b99444f0ce6557e9a1e6cb59d383/HCI-sample-message.txt)
- Each HL7v2 message that is being tested should have its own notes document. See the following document for example on how it should be formatted and where it should live: 
[40_Message_RS_processing_notes.xlsx](https://cdc.sharepoint.com/:x:/t/ReportStream/ETd2aQ7qh_9Gpxh87pQXtB0B_mVF04L_20ma3-p8f_gLHQ?e=aONvUa)

### Acceptance Criteria
- [ ] Document any differences found in the message after testing the message through the UP (document [here](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/Shared%20Documents/HCI-ELR/sample-messages/hci-8-18-23_notes.xlsx.xlsx?d=webc645bf4b244f9785f5b1f307d05bfa&csf=1&web=1&e=26Xb7W))
- [ ] Create strategy for addressing differences and write stories and assign to epic

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10963?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @thetaurean
