### ISSUE TITLE
Light Content update: Guide to receiving ReportStream data

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10960]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

This ticket captures light content updates to the existing **Guide to receiving ReportStream data** page. A more robust content draft and review process will occur later in Q3.

## Working links
-   Guide to receiving ReportStreeam data: [Live page](https://reportstream.cdc.gov/resources/getting-started-public-health-departments)
-   Draft link TBD

## Acceptance criteria
-   [ ] Light style edits made to content
-   [ ] Handoff ready for eng to update
-   [ ] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Comment by audreykwr** [comment]
@chris-kuryak @Andrey-Glazkv closing this because it is now redundant with this [10375](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/10375)
