### ISSUE TITLE
Update build image (created by /prime-router/build.sh) to Java 17 and other good things

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#11011]
The base image we use to build our application needs upgrades to:
Gradle - 
Azure Functions - looks like we are on the latest https://github.com/Azure/azure-functions-core-tools/releases
Java - 17

**Comment by jack-h-wang** [comment]
Note there are a few dependencies that require Gradle 7.0+, such as Jooq 8.0+ (see #9819). Might be a good time to migrate to Gradle 7.0+
