### ISSUE TITLE
STLT Dashboard Improvements before rollout

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#11013]
## Problem statement

With the STLT Dashboard rollout coming soon, we found a few issues that need to be fixed up to optimize the user experience before rollout begins.

## What you need to know

- STLT Dashboard is live on the site and can be accessed by:
  - Go to staging.reportstream.cdc.gov
  - Sign in as a Prime admin
  - Change your organization to a receiver
  - View the new dashboard pages by visiting:
    - Data Dashboard - staging.reportstream.cdc.gov/data-dashboard
    - All Facilities page - Click on All Facilities in the menu on Data Dashboard
    - Report Details page - Click on a report from the Data Dashboard
 
- Note from Michael Kalish on how to fix the sorting issues:
>  It looks like all three just need to have the column named adjusted in the request to the API to get this to work. orderingProvider -> ordering_provider (same for the rest).

- Here are images of the sorting issues:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdm9tIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--425a3882772186d03a6596377205d1e2fed7da7e/Screenshot%202023-08-21%20at%2011.13.26%20AM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdndtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4fefcc3883595b833a04c944140e3bf5a3f67f70/Screenshot%202023-08-21%20at%2011.13.41%20AM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjBtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0ec2b859c78642b804ec70d5816677b47d60b858/Screenshot%202023-08-21%20at%2011.17.07%20AM.png)

## Acceptance criteria

- [x] Data Dashboard sorts in descending order of report date (newest first) upon initial load
- [x] On Data Dashboard, Ordering Provider and Performing Facility sort properly (alphabetically) when toggled
- [x] On All Facilities Page, Report Count sorts properly (numerically) when toggled
- [x] "Receiver Service" list should be sorted alphabetically on both Data Dashboard and All Facilities pages
- [x] Remove info icon tooltip next to "Report ID" on the Report Details page
- [x] Blue header should span entire width of page on Data Dashboard page 
- [x] Blue header should span entire width of page on All Facilities page

**Comment by penny-lischer** [comment]
@chris-kuryak The AC refers to `report date`, did you mean `Date sent to you` date?
