### ISSUE TITLE
Okta: taking over from SimpleReport

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#1103]
- SimpleReport has started to transition to their own forms, email templates, etc for inviting users/resetting passwords/so on.
- We'll be able to take over the default email templates, login pages, and that sort of thing from them.
- Currently those communications are branded with SimpleReport imgs/language
- Transition that content to ReportStream

**Comment by loripusey** [comment]
@drew-usds is it ok if I close this epic and move it's 1 ticket to this Epic?
https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/2809

**Comment by loripusey** [comment]
Am closing this epic and moving it's 1 [ticket ](https://app.zenhub.com/workspace/o/cdcgov/prime-reportstream/issues/566 )to this [Epic ](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/2905)to consolidate?
