### ISSUE TITLE
Update Navbar Links Pt. 2

### ISSUE THREAD

**Issue by etanb** [CDCgov/prime-reportstream#11057]
## Problem statement

As we create and add more RS pages, we need to update our Navbar to reflect those changes.

## What you need to know

UPDATE NAV TO: About, Getting started, Developer Resources, Managing your connection, Support

"About" will link to the new About page (previously the "[Overview](https://reportstream.cdc.gov/product/overview)" page).

**Comment by chris-kuryak** [comment]
Completed as part of different work. Closing.
