### ISSUE TITLE
Update Navbar Links Pt. 1

### ISSUE THREAD

**Issue by etanb** [CDCgov/prime-reportstream#11056]
## Problem statement

As we create and add more RS pages, we need to update our Navbar to reflect those changes.

## What you need to know

UPDATE NAV TO: About, Getting started, Developer Resources, Managing your connection, Support

"About" will link to existing [Overview](https://reportstream.cdc.gov/product/overview) page.
"Getting started" will link to the new Getting started page.
"Developer resources" will link to the new Developer resources page.
"Managing your connection" will link to the new Managing your connection page.
"Support" will link to the existing [Support](https://reportstream.cdc.gov/support) page.

**Comment by jillian-hammer** [comment]
@etanb clarified with audrey: 

UPDATE NAV TO: **About**, Getting started, Developer Resources, Managing your connection, Support
About should link to the existing [Overview page](https://reportstream.cdc.gov/product/overview).

**Comment by etanb** [comment]
Closed in favor of: https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/11257
