### ISSUE TITLE
Update How Route Function Queues Translate Function

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#11051]
### User Story

As a pipeline step (route), I should follow the same pattern as other Universal Pipeline steps when calling the next step in the pipeline (translate) so that the pipeline can remain maintainable and reduce the probability of defects.

### Description/Use Case

Presently, there is an interesting unexpected behavior in the translate function, made apparent by #10928.

The route step will generate ONE report and add Endpoint Resources to the Provenance Resource, that the translate function will then iterate over to generate a new report for each receiver:

```kotlin
return receiverAndEndpoints
    .map {
        actionHistory.trackActionReceiverInfo(it.second.organizationName, it.second.name)
        it
    }
    .filter {
        it.second.topic.isUniversalPipeline
    }
    .map { (receiverEndpoint, receiver) ->
        val updatedBundle = pruneBundleForReceiver(bundle, receiverEndpoint)

        val bodyBytes = getByteArrayFromBundle(receiver, updatedBundle)
```

The interesting behavior that we want to solve for is when/if `val bodyBytes = getByteArrayFromBundle(receiver, updatedBundle)` throws an exception during translation (this can happen if the schema is "invalid" for the message that it is trying to process) everything the step did gets rolled back (see #10928), thus one "bad receiver" can prevent other receivers from receiving their data. Henceforth referred to as the "Rotten Apple Spoils the Bunch" problem.

If the Route step generated a separate report (and thus a separate call to the translation step) for each receiver it found for the report, this would not be an issue since the translate function would only ever run for one receiver. 

### Risks/Impacts/Considerations

As part of this update, we should update how we communicate where a report should be routed to. Destinations for a message should no longer be stamped to provenance resource in the route step, they should be communicated to the translate step via SQS queue params. This will work now because the translate step will receive a unique report for each destination.

### Dev Notes

One proposed solution is to update the Route step to generate a report and queue a Translate function for each receiver it identifies, INSTEAD OF using provenance and endpoint to indicate where a report should be routed to. This is how the other UP steps work, so implementing it this way would bring them in alignment and increase maintainability of the pipeline.

### Acceptance Criteria

- [ ] Rotten Apple problem remediated
- [ ] UP does not depend on provenance resource for routing/processing
- [ ] Route step documentation (and other documentation) updated to reflect new functionality

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11051?planning-poker) with Zenhub @arnejduranovic @jalbinson @JessicaWNava @jimmyfagan @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11051?planning-poker) with Zenhub @JFU-NAVA-PBC
