### ISSUE TITLE
Send Okta email to activate user account

### ISSUE THREAD

**Issue by Andrey-Glazkv** [CDCgov/prime-reportstream#11064]
## Problem statement

Send Okta email to activate user account to RS users. This is the Go-Live automated email.

## What you need to know

Has to happen on the Go live day

- [Comm plan draft](https://docs.google.com/document/d/18qw6o07oT1npmL_37opzm4s2e9a48-XO/edit#heading=h.gjdgxs)
- [Okta flow mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1681921545021/4b0bdcdfb84b03a3a7b0a90741c9dab5c1e3abd6?sender=uc68de765cde7b324bc271858)
- ...

## Acceptance criteria
- [ ] Okta email to activate user account sent to RS users

## To do
- [ ] Send emails to users

**Comment by chris-kuryak** [comment]
Sent today
