### ISSUE TITLE
Help page content (Okta)

### ISSUE THREAD

**Issue by Andrey-Glazkv** [CDCgov/prime-reportstream#11069]
## Problem statement

We want to create, review, and update the content on the help page related to account management, including resetting passwords, retrieving forgotten usernames, and handling expired tokens, so that users can find accurate and clear guidance that reflects the new processes and user flows in the new Okta instance.

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Comm plan draft](https://app.box.com/s/snmcejhh9do6yvs39rjac62n1drv691l)
- [Okta flow mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1681921545021/4b0bdcdfb84b03a3a7b0a90741c9dab5c1e3abd6?sender=uc68de765cde7b324bc271858)
- ...

## Acceptance criteria

- [ ] Help page content is is ready for publishing

## To do

- [ ] Content creation, review and update
- [ ] User understanding validation
- [ ] Notify engineers - content is ready for publishing

**Comment by jillian-hammer** [comment]
more about figuring out if we need it and strategizing how we use the page, if at all

**Comment by audreykwr** [comment]
[content](https://docs.google.com/document/d/1vDmWYI81cOJ8GFqhxLzscBM5KMUEC5GUhFs_1QCqtbY/edit)
