### ISSUE TITLE
Account creation: Review content style across user flow (Okta)

### ISSUE THREAD

**Issue by Andrey-Glazkv** [CDCgov/prime-reportstream#11066]
## Problem statement

We want to review and standardize the content style across the entire user flow for account creation, so that users experience a seamless transition when creating accounts in the new Okta instance, aligning with the RS branding and comms guidelines.

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Comm plan draft](https://app.box.com/s/snmcejhh9do6yvs39rjac62n1drv691l)
- [Okta flow mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1681921545021/4b0bdcdfb84b03a3a7b0a90741c9dab5c1e3abd6?sender=uc68de765cde7b324bc271858)
- ...

## Acceptance criteria

- [ ] Content meets RS branding and comms guidelines

## To do

- [x] Analyze existing content
- [x] Identify inconsistencies
- [x] Modify content to adhere to RS branding and comms guidelines
- [x] Validate changes

**Comment by audreykwr** [comment]
Main findings/edits needed: 

- Global change of Sign In to Sign in to align with style
- Possible button change to sentence case on password/question set up page
- Edits to verification code email
- Possible edits to MFA page depending on ability


All noted or changed in Figma

**Comment by Andrey-Glazkv** [comment]
@Andrey-Glazkv - ticket on implementing changes based on this one
