### ISSUE TITLE
Okta comms plan: Website update/notification

### ISSUE THREAD

**Issue by Andrey-Glazkv** [CDCgov/prime-reportstream#11065]
## Problem statement

Publish website update/notification regarding new Okta instance.

## What you need to know

A week before Go live day we add a notification to RS website

- [Comm plan draft](https://app.box.com/s/snmcejhh9do6yvs39rjac62n1drv691l)
- [Okta flow mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1681921545021/4b0bdcdfb84b03a3a7b0a90741c9dab5c1e3abd6?sender=uc68de765cde7b324bc271858)
- ...

## Acceptance criteria

- [ ] Website update/notification created and posted

## To do

- [ ] Publish a website update/notification from #11071 it on RS website

**Comment by chris-kuryak** [comment]
This will be handled by #11340
