### ISSUE TITLE
Transition plan leadership sign-off (Okta)

### ISSUE THREAD

**Issue by Andrey-Glazkv** [CDCgov/prime-reportstream#11075]
## Problem statement

We want to obtain a leadership sing-off for our Okta transition plan

## What you need to know

 Links to documents, workflows, or list of key people and contact info:

- [Comm plan draft](https://app.box.com/s/snmcejhh9do6yvs39rjac62n1drv691l)
- [Okta Migration Timeline](https://docs.google.com/spreadsheets/d/11YZ7-h3nJSQ8tqOOArZ_CyPjWuqeRB-KemBM8UmjdjM/edit#gid=1115838130)
- [Okta flow mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1681921545021/4b0bdcdfb84b03a3a7b0a90741c9dab5c1e3abd6?sender=uc68de765cde7b324bc271858)

## Acceptance criteria

- [ ] Okta transition plan signed off by leadership 

## To do

- [ ] Schedule a sign-off meeting

**Comment by chris-kuryak** [comment]
Was approved last sprint.
