### ISSUE TITLE
Plan and execute update to Gradle 8.3+

### ISSUE THREAD

**Issue by jack-h-wang** [CDCgov/prime-reportstream#11088]
### User Story
As ReportStream, I want to be on the latest supported release so that we can make use of the latest features and security updates.

### Description/Use Case
We are currently running Gradle 7.6 and should plan to migrate to 8.3+. At the same time, we should evaluate use of any deprecated features and make updates prior to them being removed in Gradle 9.0+.

### Risks/Impacts/Considerations
This will require coordination with DevOps to make sure CI and the build image are updated with the version of Gradle we target.

### Dev Notes
[This build scan](https://gradle.com/s/r4g7wjq5gjxy2) was generated using `gradle help --scan`. See the Console log as well as the Deprecations report.
Running `gradle wrapper --gradle-version 8.3` things seem to work but warnings on deprecated features are thrown in the process and on every run.

See comment in https://github.com/CDCgov/prime-reportstream/pull/11119#issuecomment-1706891479 for list of warnings 

### Acceptance Criteria
- `prime-router` is updated to run on Gradle 8.3+.
- All deprecation warnings are addressed.

**Comment by jack-h-wang** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11088?planning-poker) with Zenhub @jack-h-wang @arnejduranovic @brick-green @jimmyfagan @mkalish @luis-pabon-tf @JFU-NAVA-PBC @JessicaWNava

**Comment by luis-pabon-tf** [comment]
Sprint backlog is empty so I will do initial work on this
