### ISSUE TITLE
Backup user data in appropriate location (Okta)

### ISSUE THREAD

**Issue by Andrey-Glazkv** [CDCgov/prime-reportstream#11086]
## Problem statement

We want to create a secure and comprehensive backup of all user data in an appropriate location, so that we have a reliable rollback option in case any data is lost or corrupted during the migration to the new Okta instance.

## What you need to know

- [Comm plan draft](https://app.box.com/s/snmcejhh9do6yvs39rjac62n1drv691l)
- [Okta Timeline](https://docs.google.com/spreadsheets/d/11YZ7-h3nJSQ8tqOOArZ_CyPjWuqeRB-KemBM8UmjdjM/edit#gid=1115838130)
- [Okta flow mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1681921545021/4b0bdcdfb84b03a3a7b0a90741c9dab5c1e3abd6?sender=uc68de765cde7b324bc271858)
- ...

## Acceptance criteria

- [ ] Backup executed and verified

## To do

- [x] 	Identify data to backup.
- [x] 	Select backup location: according to CDC/USDS recommendations . 
- [x] 	Execute backup
- [x] 	Verify backup

**Comment by chris-kuryak** [comment]
Waiting on CDC Response.

**Comment by jpandersen87** [comment]
Migration data is backed up in CDC locker named "OPHDST_RS_OKTA_Migration" with access given to @chris-kuryak and @pstonebu
