### ISSUE TITLE
Wireframe: Security

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#11097]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

This ticket captures the work of creating the Figma design for the **Security page** using the existing detail page template and ensuring it is dev ready for handoff.

## Working links

- Figma: [Working file](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=225%3A822&mode=design&t=oaE1uhsUhwsV6zy0-1)
-  Content doc: [Security](https://docs.google.com/document/d/16FV9j46vx5sQ-0lpEPvcLegs_lVuEqN7IwqrfPYWfZI/edit#heading=h.io94nl3lblvl)

## Acceptance criteria
**Design**
-   [x] Design is ready for handoff (i.e. dev ready)
-   [x] Design includes latest content updates
-   [x] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Review**
-   [x] Reviewed with design and/or design lead
-   [x] Reviewed with content strategist for final approval
-   [x] Reviewed with product and engineering

**Comment by yudonoodles** [comment]
Reviews are all complete, showcased it to engineers on 09/07 and reviewed with Audrey for one last time today. Ready for Sprint 77 and moved it to the ready for dev space on Figma.
