### ISSUE TITLE
Wireframe: Release notes

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#11096]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

This ticket captures the work of exploring design solutions to the new **Release Notes** structure, collecting feedback, and finalizing the design by creating dev ready handoff materials.

## Working links

- Figma: [Working file](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=2454%3A8386&mode=design&t=dEv20yhvadoHVP4z-1)
-  Content doc: [Release notes](https://docs.google.com/document/d/1YO_5GfX45dWkSE1OYcZSzA4nASgRtT-n9l4LgatPJJQ/edit#heading=h.v4cm8fxh7i7)
-  Current release notes: [Website](https://reportstream.cdc.gov/product/release-notes)

## Acceptance criteria
**Design**
-   [x] Design is ready for handoff (i.e., dev ready and items for future iterations identified for backlog and removed from handoff document)
-   [x] Design includes latest content updates
-   [x] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Review**
-   [x] Reviewed with design and/or design lead
-   [x] Reviewed with content strategist for final approval
-   [x] Reviewed with product and engineering

**Comment by yudonoodles** [comment]
**Status:** 

- Design and content is ready! 
- Waiting to finalize color for tags using new USWDS' color palette. Already updated the colors with the new palette and shared with design. Received feedback and responded to it.

**Comment by yudonoodles** [comment]
Finalized color for tags with JH. Using what I had originally designed.
