### ISSUE TITLE
Complete MSH Mapping Inventory

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#11113]
### User Story
As ReportStream, I must implement the [HL7v2 -> FHIR Mapping inventory](https://docs.google.com/spreadsheets/d/1PaFYPSSq4oplTvw_4OgOn6h2Bs_CMvCAU9CqC4tPBgk/edit#gid=0) for the MSH segment in order to support onboarding future Senders to the Universal Pipeline.

**Note:** If a mapping does not exist in the inventory, only fields specified by NIST 2.5.1 should be considered to help limit the scope to a manageable level

### Description/Use Case
ORU-R01 calls for the following mappings:

- [ ] MSH[MessageHeader]
- [ ] MSH[Bundle]

#### Test Plan
Test Plan: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/design/proposals/mapping-inventory-test-plan.md
PR That implements test plan, use as example: https://github.com/CDCgov/prime-reportstream/pull/11147

### Acceptance Criteria
- [ ] Segment mappings updated to match [HL7v2 -> FHIR Mapping inventory ORU_R01](https://docs.google.com/spreadsheets/d/1gHK6_PFyr7PXns7wLDs0LSLsbjm0x-4bWUu3crXMKMI/edit#gid=0)
- [ ] Tests created and passing, per the linked test plan

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11113?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @thetaurean @mkalish

**Comment by Andrey-Glazkv** [comment]
Might be more than 5 points - needs to be refined

**Comment by Andrey-Glazkv** [comment]
Move to Backlog for refinement and planning

**Comment by arnejduranovic** [comment]
We are moving this from in progress to backlog because as we were working on this ticket we found that it is not worth completing this ticket before we complete epic #11655
