### ISSUE TITLE
Authentication barrier on pages 

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#11115]
As an WebX Engineer,
I want be able to add new authenticated pages without too much overhead,
So that I would not have repeat code or boilerplate logic.

Designs
- N/A
Content Updates
- N/A
Page Title
- N/A
Analytics
- N/A
Storybook updates
- N/A
Verification Steps
- Create new page with authenitication

Acceptance Criteria:
- [ ] Documentation on how to create new authenticated pages
- [ ] Unit Tests
- [ ] End to End Tests

Dependencies:
- Designs - N/A
- Platform API Endpoints - N/A

Additional Details:
- Outlet from React Router https://github.com/remix-run/react-router/blob/c13b66939ef48eacf7067f7aec4752777be8b17c/docs/api-reference.md#outlet

**Comment by jpandersen87** [comment]
the RequireGate component/pattern for routes accomplishes this now
