### ISSUE TITLE
API Mocking 

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#11117]
As a WebX Engineer,
I want to be able to Mock any API dependencies,
So that I can test and develop in isolation without worrying about the impact from external API development.

Designs
- N/A
Content Updates
- N/A
Page Title
- N/A
Analytics
- N/A
Storybook updates
- ??
Verification Steps
- API Mocking contracts signed off by API owners (Platform team)

Acceptance Criteria:
- [ ] Storybook update required?
- [ ] Unit Tests
- [ ] End to End Tests
- [ ] Manual Testing Steps

Dependencies:
- Designs - N/A
- Platform API Endpoints - **TBD**

Additional Details:
- Playwright API mocking https://playwright.dev/docs/mock
- Mock Service worker https://mswjs.io/

**Comment by jpandersen87** [comment]
With the BasePage POM pattern, we have the infrastructure that accomplishes this for E2E.
