### ISSUE TITLE
Linting Rules Audit

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#11116]
As a WebX Engineer,
I want to be able to utilize modern tooling and linting rules,
So that our application is kept up to date with modern practices.

Designs
- N/A
Content Updates
- N/A
Page Title
- N/A
Analytics
- N/A
Storybook updates
- N/A
Verification Steps
- Code Review
- Config review with Engineers

Acceptance Criteria:
- [ ] Git Hooks
- [ ] Unit Tests
- [ ] End to End Tests

Dependencies:
- Designs - N/A
- Platform API Endpoints - N/A

Additional Details:
- Prettier vs Linting https://prettier.io/docs/en/comparison.html

**Comment by jpandersen87** [comment]
eslint config was restarted to be more readable, which accomplishes this goal
