### ISSUE TITLE
Create Test Plan for Translation Template Updates

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#11125]
### User Story

As ReportStream,
I want to have a test plan I can refer to that specifies what/how/where to test transform template changes
so that I can ensure transform template changes:
1. do not break existing senders/receivers
2. behave as expected, especially around edge cases

### Description/Use Case

Presently, RS engineers maintain sample input/output files for each onboarding initiative on the UP that we work on. This may be fine as part of a test plan, but it is not a great way to test individual mappings as specified in the mapping inventory. The present tests could be thought of as "functional" tests (I'd call them sender verification tests and receiver verification tests), where as we probably ALSO need unit tests for each mapping that we create. If we say that we do, then we need to define how they are structured and organized.

There is a design note for managing translation templates that indicates how sender and receiver validation tests can be run and managed, we should look to adopt that as part of this work.

### Acceptance Criteria

- [ ] Document titled "Translation Template Test Plan" created and completed
- [ ] Example created for Michael's PR: Link here

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11125?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @mkalish @thetaurean
