### ISSUE TITLE
Onboard NY to the Universal Pipeline

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#11129]
### User Story:
As NY, I want to be onboarded to the UP, so that I can start receiving conditions other than flu.

### Description/Use Case
We will be onboarding NY to the UP as part of Full ELR pilot. They are interested in receiving flu results from Simple Report and potentially HIV results coming from HCI.

### Risks/Impacts/Considerations

- Covid results still need to be routed through the Covid pipeline. 
- NY is only interested in receiving positive flu results. We can reuse the filter we had originally set up for CA to only send positive FLU results
- Covid needs to filtered out from SR messages

### Dev Notes:
- A new receiver needs to be set-up for NY that is configured for the UP in both staging and production

### Acceptance Criteria
- [ ] NY starts receiving messages through the UP with no errors
- [ ] Integration tests are added with test messages coming from SR

**Comment by chris-kuryak** [comment]
Waiting on meeting on Wednesday to move forward (get answers from NY).

**Comment by LaFreda1** [comment]
NY is set up to our staging environment.

**Comment by LaFreda1** [comment]
Met with NY today, they are ready to move to production.
