### ISSUE TITLE
Fix-up HL7->FHIR->HL7 differences for HCI

### ISSUE THREAD

**Issue by jimmyfagan** [CDCgov/prime-reportstream#11124]
### User Story
As HCI, I want good confidence that the messages I send to ReportStream will be losslessly sent to receivers.

### Description/Use Case
As a follow-up to the work done in #10963, we have some segments and fields in the HCI test message that still need to be addressed in the spreadsheet [here](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/Shared%20Documents/HCI-ELR/sample-messages/hci-8-18-23_notes.xlsx.xlsx?d=webc645bf4b244f9785f5b1f307d05bfa&csf=1&web=1&e=26Xb7W). All entries in the spreadsheet that are yellow, red, or purple should be addressed as part of this ticket.

### Risks/Impacts/Considerations
The yellow and red entries in the spreadsheet rely on feedback from the HCI team, so there is a slight external dependency for successful completion of this story.

Additionally, some of the discrepancies noted in the sheet are related to behavior that is expected for certain STLTs, and that is based on behavior in the COVID pipeline (see comment thread [here](https://github.com/CDCgov/prime-reportstream/commit/03455e43b67762ad6bd72c42e6c32565ac1d5466#r125553401)). We should work with Victor and the Engagement team to ensure that we have properly accounted for impacts to production data and STLTs.

### Dev Notes
There is a WIP branch [here](https://github.com/CDCgov/prime-reportstream/pull/new/jimmy/10963-gap-analysis-hci) which serves as a starting point for the necessary changes. This story will continue working in the same branch.

To handle consistency for existing STLTs, we can consider adding a new receiver transform schema that aims for parity with the COVID pipeline, which can then be extended by receiver specific transforms for particular STLTs (like California).

### Acceptance Criteria
- [ ] [This spreadsheet](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/Shared%20Documents/HCI-ELR/sample-messages/hci-8-18-23_notes.xlsx.xlsx?d=webc645bf4b244f9785f5b1f307d05bfa&csf=1&web=1&e=26Xb7W) has no more yellow, red, or purple entries, or any remaining entries have follow-up stories created
- [ ] CA integration tests have consistent output from before and after these changes

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11124?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @mkalish @thetaurean

**Comment by jimmyfagan** [comment]
Closed with approval from Avniel
