### ISSUE TITLE
Website Redesign - Our Network

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#11134]
As a User,
I want to visit the Our Network Page,
So that I can become informed about ReportStream's network of organizations

### Designs
- Figma Link https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=925%3A4974&mode=design&t=JFcMNWQHEGLr4HrU-1

### Content Updates
-  Content Links TBD
  
### Analytics
- Page Load
- Button / Link clicks

### Verification Steps
- Code Review
- Trail / Dev environment signoff by Product / Design
- Staging environment signoff by Product / Design / Stakeholders 
- Production environment signoff by Engineering, Product and Design

### Acceptance Criteria:
- [ ] Analytics / Metrics Required 
- [ ] Storybook update required
- [ ] Unit Tests
- [ ] End to End Tests
- [ ] Manual Testing Steps
- [ ] Add to Navigation

### Dependencies:
- Designs - https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=925%3A4974&mode=design&t=JFcMNWQHEGLr4HrU-1

### Additional Details
- The deployment strategy will follow the general deployment strategy for the Website Redesign EPIC. We will deliver this page in isolation from the other pages.

**Comment by KeithNava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Web-Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/11134?planning-poker) with Zenhub @etanb @jpandersen87 @penny-lischer

**Comment by jillian-hammer** [comment]
update from CDC call: OK to include list of names of senders. @audreykwr will sync up with you to decide if we want to gather names and continue to slate dev for this sprint, or bump to next sprint.

**Comment by jpandersen87** [comment]
Since the page appears to be only waiting on content in the one section, I have created a draft that can be iterated on once the content is complete.

**Comment by KeithNava** [comment]
@jpandersen87 can we unblock this?
