### ISSUE TITLE
Enable phone number formatting in the UP

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#11130]
### User Story:
As ReportStream, I want to enable phone number formatting in the UP, so that I can have support Covid translation settings.

### Description/Use Case
We need to find out if we can support phone number formatting using receiver transforms, or we if we need extract the covid pipeline's logic to support this in the UP. It's preferable to use receiver transforms and avoid having to hardcode this logic. 

### Dev Notes:

- The Covid pipeline allows three different options for this setting: `STANDARD`, `ONLY_DIGITS_IN_COMPONENT_ONE` and `AREA_LOCAL_IN_COMPONENT_ONE`
- We need to understand how each of these functions format the phone number
- We could send a message to the covid pipeline with a receiver configure for each of these settings and see what it outputs
-  Investigate if those different formats can be supported in the UP using receiver transforms

### Acceptance Criteria
- [ ] The UP can format phone numbers according to the receiver needs

**Comment by LaFreda1** [comment]
Not necessary for UP
