### ISSUE TITLE
Enable convertTimestampToDateTime setting in the UP

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#11131]
### User Story:
As ReportStream, I want to enable the convertTimestampToDateTime setting in the UP, so that I can have support Covid translation settings.

### Description/Use Case
We need to extract the covid pipeline logic to support this setting in the UP. This should be very similar to the work we did on this PR: https://github.com/CDCgov/prime-reportstream/pull/10777 

### Acceptance Criteria
- [ ] The UP can convert timestamps to datetime for fields specified in the convertTimestampToDateTime receiver setting.

**Comment by GilmoreA6** [comment]
https://build.fhir.org/fhirpath.html - resource for fhirpath

**Comment by kant777** [comment]
@victor-chaparro this task of convertingtimestamp to datetime is only for hl7? because the FHIR spec doesn't have datetime

**Comment by victor-chaparro** [comment]
Yes this is only needed for HL7

**Comment by kant777** [comment]
Hi Folks, Friday was my last day however I just realized that I had some tests in my located and I committed those as well. I will be around slack in case you need me

**Comment by chris-kuryak** [comment]
Per Victor, finished and can be closed
