### ISSUE TITLE
Website Redesign - About

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#11135]
As a User,
I want to visit the About Page,
So that I can become informed about ReportStream

### Designs
- Figma: https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=2333%3A18432&mode=design&t=VTyaThKMitoM2uRm-1

### Content Updates
-  TBD Content Links

### Analytics
- Page Load
- Button / Link clicks

### Verification Steps
- Code Review
- Trial / Dev environment signoff by Product / Design
- Staging environment signoff by Product / Design / Stakeholders (Need to be explicit)
- Production environment signoff by Engineering, Product and Design

### Acceptance Criteria
- [ ] Storybook update required
- [ ] Manual Testing Steps
- [ ] Add Link to Navigation

### Dependencies
- Designs - https://www.figma.com/proto/Du7feM8huRDAAZCQcUIj93/Website-Redesign?page-id=2026%3A2&type=design&node-id=2026-73&viewport=554%2C195%2C0.17&t=0LVQdVbXub958ODz-8&scaling=min-zoom&hide-ui=1

### Additional Details
- The deployment strategy will follow the general deployment strategy for the Website Redesign EPIC. We will deliver this page in isolation from the other pages.

**Comment by KeithNava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Web-Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/11135?planning-poker) with Zenhub @etanb @jpandersen87 @penny-lischer

**Comment by penny-lischer** [comment]
@jillian-hammer or @yudonoodles the Values section order of topics is not the same b/w the two templates (collapsed/expanded views). Please advise.

**Comment by yudonoodles** [comment]
Sorry, not sure how one of them got moved, but the order is updated and the same now! Thanks for noting @penny-lischer.
