### ISSUE TITLE
Update End to End tests for Redesign

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#11132]
As an WebX engineer,
I want to be able to run automated end to end tests,
So that I don't have to do manual testing for the common flows in the application.

Designs
- N/A
Content Updates
- N/A
Page Title
- N/A
Analytics
- N/A
Storybook updates
- N/A
Verification Steps
- Run E2E tests against the latest redesigned pages

Acceptance Criteria:
- [ ] Analytics / Metrics Required 
- [ ] Storybook update required
- [ ] Unit Tests
- [ ] End to End Tests
- [ ] Manual Testing Steps

Dependencies:
- Designs -  N/A
- Platform API Endpoints - N/A

Additional Details:
- <Any additional information, context, or specifications>

**Comment by jpandersen87** [comment]
E2E tests are currently being made post-redesign.
