### ISSUE TITLE
SSH key and directory provisioning for ELIMS in staging

### ISSUE THREAD

**Issue by JosiahSiegel** [CDCgov/prime-reportstream#11146]
## Context
ELIMS needs to connect via SFTP to the SFTP container in the reportstream staging environment. They will need to pull data out at an interval of their choosing. ELIMS will not need to upload any data.

## Acceptance Criteria

- [x] volume created for ELIMS on **staging** SFTP container
- [x] Public key retrieved from ELIMS
- [x] Public key uploaded to ssh key azure resource connected to ELIMS staging volume
~- [ ] SSH key resource created for RS to connect to ELIMS staging volume~
~- [ ] private key saved to keybase : team/prime_dev_ops/receiver_info/ELIMS~
~- [X] Data factory migrate SFTP files to storage account for application access~
- [x] ELIMS can read files in SFTP folder
- [x] ELIMS can list files in SFTP folder
- [x] ELIMS can delete files from SFTP folder

**Comment by brick-green** [comment]
requesting pub key from elims. Will provide when they send it.

Also idk if we need to whitelist but here's the info provided by elims:

"DFS name is elims.development.cdc.gov"
```
nslookup elims.development.cdc.gov

Server:		192.168.50.1
Address:	192.168.50.1#53

** server can't find elims.development.cdc.gov: NXDOMAIN
```

**Comment by brick-green** [comment]
Here's the public key from elims

[elims_public.txt](https://github.com/CDCgov/prime-reportstream/files/12542429/elims_public.txt)
