### ISSUE TITLE
Website Onboarding Documentation Update

### ISSUE THREAD

**Issue by brandonnava** [CDCgov/prime-reportstream#11172]
Experience team would like us to look over 3 web pages to make updates regarding onboarding to the UP. Two of them are existing web pages, one is a new web page. 

Existing pages needing a fresh look from our team to ensure accuracy in a UP world:
1) Guide to receiving ReportStream data: https://reportstream.cdc.gov/resources/getting-started-public-health-departments
2) ELR onboarding checklist: https://docs.google.com/document/d/1PQ7mbYKJNMfolBvIjp2B4PVIv925zy6kmfmcOTyDkro/edit?usp=sharing
To be replaced with this one doc we need to look over/revise: https://docs.google.com/document/d/1WZEYlfGzRPxshshiXeSnhUlvCSuowGcN8P80w4YOTTo/edit?usp=sharing

New page we need to ensure the outline covers all the main info that needs to be mentioned:
Onboarding receiver: Core model outline - https://docs.google.com/document/d/1mIdupE1-JEt3ghaYOydu3gr_GMVWBe7XNip2BH4SVDw/edit?usp=sharing

**Comment by audreykwr** [comment]
Yeah Brandon must have made this in response to that previous work but didn't use it to follow that. This all was completed awhile ago. I can link the actual tickets where the work happened if you'd like.
