### ISSUE TITLE
Receivers who download data (instead of connect through API) are shown the Daily Data page instead of the new Data Dashboard page

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#11181]
## Problem statement
Some STLTs use the Daily Data to download reports. But those reports don't show up in the new Data Dashboard. As a receivers on the COVID pipeline, I want to continue to be able to download my data if I am not connected to the API.

## What you need to know

- Daily Data queries the BATCH step.
- Data Dashboard queries the SEND step.
- Some of our receivers are not connected to the API to receive reports through the SEND step, so instead they log in to the site and download the reports from the Daily Data page. Since the reports are not "sent" to these receivers through the SEND step, they do not show up on the Data Dashboard. Therefore, these receivers cannot download their data (and they are not receiving it through the API).
- Ticket to identify which users this effects ("download users") - #11182
  - Those users that should be shown the old Daily Data page instead of the new Data Dashboard page are any users from the following organizations:
    - ca-sbc-phd                 	        
    - ca-scc-phd	                        
    - co-routt-county-phd	       
    - co-san-juan-basin-phd	        
    - fl-hillsborough-phd	      
    - oh-ccchd-doh	                
    - pa-chester-phd	               
    - pa-montgomery-phd	     
    - pa-philadelphia-phd	       
    - pima-az-phd

## Acceptance criteria

- [x] When users that are from the receivers identified in ticket #11182 log in to (or click on) the Data Dashboard they instead see Daily Data, instead of the Data Dashboard.
- [x] All other users from all other receivers see the Data Dashboard page
- [x] Update the Nav Bar with "Dashboard"
- [x] Update link of Nav Bar to new Data Dashboard page
- [ ] Alert Sharon Liu as to the day of deployment so that she can send the comms email that accompanies this release.

## To do

- [ ] ...

**Comment by penny-lischer** [comment]
@chris-kuryak we would like to make this a temp solution and would rather a flag in the setting table to maintain this in the future. Can we discuss with platform and create story for this?
