### ISSUE TITLE
Website Redesign Review - Release Notes

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#11251]
Review designs for [Release Notes Page](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=2791%3A3377&mode=design&t=xaJlVaBtbUe5Gxr3-1)

- [x] @jpandersen87 Reviewed and Signed off
- [x] @penny-lischer Reviewed and Signed Off
- [x] @etanb Reviewed and Signed Off

**Comment by etanb** [comment]
@KeithNava made one comment in the Figma!

**Comment by KeithNava** [comment]
@yudonoodles @jillian-hammer - Engineering has completed our review of the Release Notes Page!

**Comment by yudonoodles** [comment]
@etanb I responded to your comment. Let me know if there's any issues/concerns regarding how we are planning on using tag component. Thank you!
