### ISSUE TITLE
[bug] Nav Bar logo link fix 

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#11255]
## Problem statement
The recently launched Nav Bar no longer links back to the homepage. It should.

## What you need to know
- [https://reportstream.cdc.gov/](https://reportstream.cdc.gov/)

## Acceptance criteria

- [ ] ReportStream logo in top left of Nav Bar links back to the homepage (in existing tab/window)

## To do

- [ ] ...

**Comment by etanb** [comment]
Closed in favor of: https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/11257

**Comment by KeithNava** [comment]
@etanb I'd rather us track this separately as it's the most urgent end-user impacting request. I don't want it to be held up by any other unrelated issues.

**Comment by chris-kuryak** [comment]
Closing, rolled into other PR
