### ISSUE TITLE
Website Redesign - Archive Legacy Pages

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#11267]
This ticket is a catch all for all the work needed to deprecate and archive the legacy pages/links as we move the site to the new redesign. Expect individual tickets to come from the various issues.

### Remove the following Pages
Contact
Service Request
FAQ
Resources
Account Registration Guide

### Create Redirects
- redirect links from old pages (ex: /resources/security → /about/security)

### Misc Issues

* The API guide still has the url from the resources page rather than from the new section of developer resources.

**Comment by penny-lischer** [comment]
@KeithNava re Misc Issues... is this a comment or do we want to update the link for the API guide???
