### ISSUE TITLE
Design ops: Update design system with new brand colors

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#11263]
## User story

As a designer, I want to update the color styles on Figma with the newly defined colors so that I can easily apply them to our designs moving forward. 

## Background & context

We are aiming to align with OPHDST's color palette. All colors will still live within USWDS system color token list. We have an initial list of colors mapped out. 

Approach is to keep a finite list of colors for use on our site and keep some variance in spectrum that USWDS provides. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakNmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--005f18a240ba1fc88a1ac5a1af6d48855ab595a9/image%20%289%29.png)

Note:
- [**State color tokens**](https://designsystem.digital.gov/design-tokens/color/state-tokens/) as it stands. 
- Besides the colors above, we are keeping our grayscales, black, white, as well as semantic colors such as red for error or yellow for caution. 

## Open questions

-   Is the list provided (see image) finalized?

## Acceptance criteria

-   [x] Add the new palette to Figma
-   [x] Color chart for theme tokens

**Comment by yudonoodles** [comment]
**Update:** 
- Currently text and color styles are associated with the Figma file ["ReportStream Workspace | 2023" ](https://www.figma.com/file/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?type=design&node-id=73%3A1735&mode=design&t=g4lfyExKzz7gCJeR-1). Added the gold spectrum which we didn't have in the library. 
- I also created a [new color chart](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=4031%3A10081&mode=design&t=nl92DWdQFLRFHd7Q-1) with their associated token name (what's currently used) to guide the color definition work for the site and future applications. This color chart can be adjusted to reflect new theme color tokens besides primary and base colors which we used for the new website.
