### ISSUE TITLE
Remove NJ from states that require additional validation

### ISSUE THREAD

**Issue by adegolier** [CDCgov/prime-reportstream#11284]
_[Governance document](https://docs.google.com/document/d/1__FE0OGlVAby0m7QyKfo_Qr0Gh_PvALaA1_DeCJSjzQ/edit#heading=h.qyvn837dl01t) for content process reference_

**Is this new content or an edit to current content?**

- [X] **Edit**: It is not a change that affects the design or functionality of the page/feature.
- [ ] **New**: It is something new that is mostly content (not a tool).

**Questions for edit requests:**

1. Current page link: https://reportstream.cdc.gov/resources/api/getting-started

2. Change requested: Remove New Jersey from this portion: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2FIIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1e52941d291b0c82537e3921bbeb33feff3bbc4b/image.png)

3. Why is this change needed? Reached out to New Jersey for additional validation steps in onboarding a new sender and received the following reply:

> Good morning, Angela:
>
> 
>
>There are no additional steps from NJDOH needed for a new facility to send data through ReportStream.
>
> 
>
>Respectfully,
>
>Joyce
>
>Joyce Boyd-Lee, MPH
>
>CDRSS Health Data Specialist | Epidemiology, Environmental & Occupational Health
>

4. How urgent is this change and why? Not especially urgent, because it's much easier to say "We don't actually have to do that" than "There's this additional step that wasn't mentioned"

**Complete your request by:**

- [X] Making sure you’ve answered all questions for the appropriate request type (edit or new)
- [X] Labeling this ticket as `content request`, `design` and `experience`
- [X] Assigning this ticket to @audreykwr

_Thank you for contributing to content excellence for ReportStream!_

**Comment by GilmoreA6** [comment]
Change approved for documentation. NJ email is sufficient to confirm the need for this change.

**Comment by audreykwr** [comment]
@chris-kuryak closing this because the follow up for eng has been made

@adegolier @GilmoreA6 that ticket is [here](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/11347) if you want to follow along!
