### ISSUE TITLE
[BUG] Admin dropdown visible in nav bar when logged out

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#11285]
### Current Behaviour
The Admin dropdown is visible to a non-logged in user 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0NJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--53ad2fdee8604e905bd19555c93f2c93be2ef5fa/image.png)

### Expected Behaviour
Only logged-in users should see the Admin dropdown

**Comment by jpandersen87** [comment]
@KeithNava @chris-kuryak I cannot reproduce this (via manual logout, nor timeout). Will need reproducible steps to. move forward.

**Comment by chris-kuryak** [comment]
This bug has been seen in Staging, not production

**Comment by chris-kuryak** [comment]
When I checked this in staging,

- I did not experience this bug upon manually logging out
- My staging login never auto-logged out, so I was unable to test if that was a problem

**Comment by penny-lischer** [comment]
I am not able to reproduce on staging.

**Comment by chris-kuryak** [comment]
Closing. No longer a bug that we can reproduce.
