### ISSUE TITLE
[BUG] Remove Breadcrumbs from Pages 

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#11298]
## Current Behavior 
The pages for [Manual data download guide
](https://reportstream.cdc.gov/resources/data-download-guide) and [Guide to receiving data](https://reportstream.cdc.gov/resources/getting-started-public-health-departments) both contain Breadcrumb Navigation at the top

[Manual data download guide Breadcrumb](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3lJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--174c48fd5cee57fa4fae748e412bc1218d75fed8/image.png)

[Guide to receiving data Breadcrumb](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFNJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e37a08f4665b626c0699cefa1aebdeb675b2127f/image.png)

## Expected Behavior
These pages should **not** contain the Breadcrumb navigation since it links to the archived Resources page.

## Steps to reproduce:
1. Log into RS
2. Click on "Your Connection" in the nav bar
3. Click on "How to download your data"

**Comment by penny-lischer** [comment]
@audreykwr @jillian-hammer @yudonoodles 
 should the ReportStream referral guide page also have the breadcrumb removed?
