### ISSUE TITLE
Plan next steps for legacy pages & tools

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#11290]
## User story

As a user, I need pages and tools that help me accomplish my goals.

## Background & context

The pages that we did not prioritize in the redesign need to be revisited for any potential iteration in Q4. This ticket is to evaluate their current reality to inform any possible improvements.

## Open questions

- If UP will affect how much we can plan for some of these tool improvements

## Acceptance criteria

-   [x] Initial suggestions gathered 
-   [x] Plan next steps for share out
- [ ] Update service blueprint with relevant learnings
-   [ ] Update the [questions pool](https://docs.google.com/spreadsheets/d/1THH9Ekj5renvIwSpl-6SzzyUJ5tuNcH76l4GTiboQXE/edit#gid=0) with any questions that came up
-   [ ] ...

**Comment by audreykwr** [comment]
Work gathered in this [mural](https://app.mural.co/t/nava4113/m/nava4113/1673278109303/c503de31acc97baa86ed289bbb56cbd48739e6f4?sender=uc55a7af3b66977fba12f5528)
