### ISSUE TITLE
Prime CLI can send data through the UP

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#11294]
### User Story:
As a developer, I want to be able to use the Prime CLI to send data through the UP, so that I can easily test sending messages.

### Description/Use Case
The Prime CLI currently has the ability to send messages through the Covid Pipeline using the Prime CLI. We need to make sure it can support the UP.

### Dev Notes:
- The Prime CLI can send messages using this command: 
`./prime data --input /path/to/file.hl7 --output-dir /path/to/output/dir --input-client medarbor.default --route`
- Test this command with a UP sender and check if it's able to process both HL7 and FHIR messages

### Acceptance Criteria
- [ ] Prime CLI data command can process UP messages

**Comment by adegolier** [comment]
Because the UP uses a separate pathway for translations and transforms, that command won't work for UP. There is an existing `./prime fhirdata` that appears to be meant to be the UP version but its functionality is inconsistent.

**Comment by LaFreda1** [comment]
Will pull if needed

**Comment by LaFreda1** [comment]
Not needed.
