### ISSUE TITLE
Remove "inactive" services from the "Receiver Service" List 

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#11299]
## Problem statement
The receiver service list on both the Data Dashboard and All Facilities page shows services that are currently marked as "inactive" in our database. These should not be shown (selectable) from this list on either page.

## What you need to know

- On the Data Dashboard and All Facilities pages, there is a dropdown box that allows you to select the "Receiver Service"
- Receivers can have many services connected to them
- RS has a field that indicates whether a receiver service is "inactive"

- STLT Dashboard is live on the site and can be accessed by:
  - Go to staging.reportstream.cdc.gov
  - Sign in as a Prime admin
  - Change your organization to a receiver
  - Navigate to Data Dashboard - staging.reportstream.cdc.gov/data-dashboard
  - view receivers
  - Navigate to All Facilities page (Click on All Facilities in the menu on Data Dashboard)
  - view receivers

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFdZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e420dd53c4e196d4eb6fe740e90ee5ec853db301/Screenshot%202023-09-13%20at%2012.20.43%20PM.png)

Status listing inactive/active:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGVZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--008271b1d529668f3dbaf4c1de60ace0cafce021/Screenshot%202023-09-13%20at%2012.21.48%20PM.png)

## Acceptance criteria
- [ ] "Receiver Service" list should not show "inactive" services on both Data Dashboard and All Facilities pages. All other receiver services should be shown in the list.

**Comment by penny-lischer** [comment]
@jillian-hammer @audreykwr If all receivers are inactive should we display a message?

**Comment by jillian-hammer** [comment]
Decision from sync | @jillian-hammer  @penny-lischer 

For this use case:
- Remove dropdown and date UI
- Remove table
- Show header "No available data" - Public Sans Bold, 22px
- Show body "If you need more help finding what you're looking for, contact us."
- Contact us link should go to the [Smartsheet service request](https://app.smartsheetgov.com/b/form/da894779659b45768079200609b3a599) form and be treated as an external link.
