### ISSUE TITLE
[SPIKE] Determine which pages have sufficient E2E testing and which ones do not

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#11307]
## Problem Statement
Need to determine which ReportStream website pages already have E2E testing and which ones do not.

## Acceptance Criteria
- [x] List of all ReportStream website pages showing those with sufficient E2E testing and those without
- [x] Work with Product Manager and Tech Lead to determine a prioritized list of remaining pages
- [x] Develop issue template for creating E2E tests on pages (that can be used in future tickets)
- [x] Work with Chris to create follow-on engineering tickets for remaining pages that need E2E testing

**Comment by chris-kuryak** [comment]
May need to look at Keith's PR and see what needs to be done to finish this out.
- Keith has a general E2E testing PR

**Comment by chris-kuryak** [comment]
@chris-kuryak Spike to determine which pages still need E2E testing. 
Then create prioritized list of E2E testing by page.

**Comment by chris-kuryak** [comment]
Repurposing this ticket as a spike to investigate which pages still need E2E testing.

**Comment by penny-lischer** [comment]
[e2e_Tests_audit.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXpvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c03fb9873a44dddb123ed3acdc6c8eaef0cd9a2d/e2e_Tests_audit.xlsx)

**Comment by chris-kuryak** [comment]
We have accomplished what we set out to do in this ticket.

**Comment by chris-kuryak** [comment]
Reopening since the attached PR was not closed
