### ISSUE TITLE
[SPIKE] Experiment with Release Branch for Sprint Work

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#11337]
Create a way to test all the related sprint work - ex: Website Redesign in one environment for final coordination and sign-off before launch.

**Comment by KeithNava** [comment]
Created branch `webx-sprint-77-feature-branch` as the base branch for the redesign work this sprint.

**Comment by chris-kuryak** [comment]
Though we were late, this strategy did work.
