### ISSUE TITLE
bug: Fix timezone setting in the UP

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#11330]
## Describe the bug
The incorrect timezone is being used when converting date times in the UP. The `convertDateTimeToHL7` function in `CustomTranslationFunctions.kt` needs to use the timezone from the receiver's timezone setting instead of getting the timezone from the date.

## Impact on ReportStream
Receivers will not get dates in the format they're expecting.

## Steps to reproduce
1. Update the DEV_FULL_ELR receiver by adding `timeZone: PACIFIC` and `convertDateTimesToReceiverLocalTime: true`
1. Send a report to RS using this postman collection:[Simple Report.notes test.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkdRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f6661c578799f4b816f676e04985f30b65195451/Simple%20Report.notes%20test.txt)
2. Inspect the generated HL7 file and notice that dates didn't get converted to the receiver's local timezone.

**Comment by kant777** [comment]
https://github.com/CDCgov/prime-reportstream/pull/11445

**Comment by victor-chaparro** [comment]
We should follow this logic:
