### ISSUE TITLE
Review and finalize all remaining content in the Comms Plan 

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#11339]
## Problem statement
There are still some portions of the Comms Plan that need to be reviewed and finalized before executing. 
We need to review and finalize the content of all remaining emails and messages in the Okta Comms plan in order to be in alignment with the support team.

## What you need to know

- [Comms Plan](https://docs.google.com/document/d/18qw6o07oT1npmL_37opzm4s2e9a48-XO/edit)
- ...

## Acceptance criteria
Review and Align on the following with the support team:
- [x] Pre-launch Initial Notification email
- [x] Pre-launch Internal Reminder (slack message)
- [x] Pre-launch Final Reminder email
- [x] After GoLive internal reminder (slack message)
- [x] After GoLive reminder #1 email
- [x] After GoLive reminder #2 email
- [ ] Email After 30-day Expiration email

## To do

- [ ] ...

**Comment by Andrey-Glazkv** [comment]
@audreykwr I will create a ticket for "Email After 30-day Expiration email" and close this one, if you dont mind
