### ISSUE TITLE
Handle breaking changes on HAPI FHIR version bump

### ISSUE THREAD

**Issue by luis-pabon-tf** [CDCgov/prime-reportstream#11345]
### User Story
As a ReportStream developer, FHIRPath is a vital part of my application and needs to be maintained up to date.

### Description/Use Case
Our dependency of `ca.uhn.hapi.fhir:hapi-fhir-structures-r4` includes breaking changes on its currently pending version bump.

### Dev Notes
Dependabot PR handling the update. You may use its branch as a starting point since we can always just close this PR: https://github.com/CDCgov/prime-reportstream/pull/11277

While on the dependabot branch, you can trigger the errors just by running unit tests.

### Acceptance Criteria
- With HAPI FHIR structures updated to `6.8.2`, all tests pass

**Comment by bishoyayoub** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11345?planning-poker) with Zenhub @jack-h-wang
