### ISSUE TITLE
Remove NJ from API Information

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#11347]
## Problem statement
NJ no longer requires additional steps to send data through ReportStream. They need to be removed from the Getting Started page.

## What you need to know
- Content request ticket located here: #11284

1. Current page link: https://reportstream.cdc.gov/resources/api/getting-started

2. Change requested: Remove New Jersey from this portion on both PDF and website: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2FIIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1e52941d291b0c82537e3921bbeb33feff3bbc4b/image.png)

3. Updated PDF with New Jersey removed located here: [pdf file here](https://docs.google.com/document/d/1lu7GTmOTAwLuZxcT8cYW0O7T6elI7QPY/edit?usp=drive_link&ouid=105539281535064771922&rtpof=true&sd=true)

## Acceptance criteria

- [x] New Jersey removed from Getting Started Page per above
- [x] "Downloadable PDF" link on https://reportstream.cdc.gov/resources/api will download (NOT OPEN/LINK) the new updated PDF
- [x] Edit "last updated" date on the Getting Started page to be the date that this change deploys

**Comment by KeithNava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Web-Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/11347?planning-poker) with Zenhub @etanb @jpandersen87 @penny-lischer

**Comment by penny-lischer** [comment]
@audreykwr  I need permission for the pdf
