### ISSUE TITLE
Deployment dependency: Security page URL updates

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#11355]
## Problem statement

The Homepage v2, About, and Support pages all link to the Security page. Prior to deploying these pages, the Security page needs to be updated. 

## What you need to know

- Blocked by #11333
- Current Security page URL: https://reportstream.cdc.gov/resources/security-practices
- New Security page URL: TBD

## Acceptance criteria

- [x] The Security page URL is updated to reflect the new site structure (i.e, /about/security)
- [x] Homepage V2 links to the new URL ("Our open-source platform aggregates and securely delivers...")
- [x] About links to the new URL ("In this section" links at the top)
- [x] Support links to the new URL (Related pages links) 

## To do

- [ ] ...

**Comment by KeithNava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Web-Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/11355?planning-poker) with Zenhub @etanb @jpandersen87 @penny-lischer

**Comment by penny-lischer** [comment]
@KeithNava is this ticket blocked by #11333. Does the new Security page need to happen before this?

**Comment by penny-lischer** [comment]
Completed as part of #11333
