### ISSUE TITLE
Create program to remove all unactivated (staged) migrated accounts and info from new Okta instance

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#11352]
## Problem statement
For migration, we will need a way to update the new Okta instance to have the latest set of user accounts/emails/info just before we decide to migrate. We need a way to remove all of the existing non-activated user accounts (staged) in order to upload the latest list.

## What you need to know
- Implemented in local project

## Acceptance criteria
- [ ] Program that removes all staged user accounts from the new Production/Preview ReportStream Okta instances

## To do
- [ ] Create command in local project

**Comment by jpandersen87** [comment]
The command to facilitate this is done.
