### ISSUE TITLE
Align with Backend on Okta

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#11350]
## Problem statement
The migration of Okta instances will be a joint effort between front-end and back-end. We need to align across teams to ensure what is needed (or any dependencies) for this migration to be successful.

## What you need to know
- [Transition Plan](https://docs.google.com/document/d/1nSwUA_qUuF9e6qWEBciyuhOff0ZSh7ijYaocornAtgw/edit#heading=h.atxy1smv1e88)
- [Okta Timeline](https://docs.google.com/spreadsheets/d/11YZ7-h3nJSQ8tqOOArZ_CyPjWuqeRB-KemBM8UmjdjM/edit#gid=1115838130)
- ...

## Acceptance criteria

- [ ] Determine what is needed for front-end and back-end to have a successful switch to the new Okta instance
- [ ] Document what is needed, make tickets for any technical items that need to happen, and communicate to Andrey

## To do

- [ ] ...

**Comment by KeithNava** [comment]
Platform Ticket for Okta Work: https://github.com/CDCgov/prime-reportstream/issues/11401

**Comment by KeithNava** [comment]
DevOps Ticket for Okta Work: https://github.com/CDCgov/prime-reportstream/issues/11434 cc @jpandersen87 @Andrey-Glazkv

**Comment by Andrey-Glazkv** [comment]
@Andrey-Glazkv to add tickets above to the timeline
