### ISSUE TITLE
Link fix on get started sending data

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#11371]
## Describe the bug
On in [Get started sending data](https://reportstream.cdc.gov/getting-started/sending-data) the "tools and features" link that's meant to go to the your connection page is not linked correctly.

## Impact on ReportStream
Users cannot get to the correct page. Broken link looks bad for us.

## Steps to reproduce
1. Go to get started sending data
2. Open Optional:create user account accordion 
3. Click on tools and features hyperlink

## Expected behavior
It should take you here: https://reportstream.cdc.gov/manage-connection

## Additional context
Add any other historical context about the problem here.

**Comment by KeithNava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Web-Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/11371?planning-poker) with Zenhub @etanb @jpandersen87 @penny-lischer

**Comment by chris-kuryak** [comment]
Fixed in Penny's last deployment.
