### ISSUE TITLE
HL7 ingest test cardinality of fields in input schema

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#1139]
The specified input schema for HL7 ingest contains cardinality configuration that specifies fields that are required or not, as well as minimum number of values.  Need to have the HL7 ingest reject data that does not satisfy the cardinality specified.

Acceptance criteria:
1. HL7 ingest process checks the cardinality in the input schema and rejects messages that do not satisfy the schema.
2. Error message(s) are reported for any field that does not meet the cardinality.

**Comment by tlosbo** [comment]
Was thinking of having pablocaviglia-baires work on this one. Can we assign to him?
