### ISSUE TITLE
Update and Test Okta Migration: Backend Validation

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#11401]
### User Story

As a ReportStream admin,
I must ensure the backend functionality works as expected when pointing to the new ReportStream-owned Okta instance,
so that ReportStream users do not experience any interruptions when the switch occurs in production

### Description/Use Case

Given a new Okta URL and CLIENT ID, we need to update the backend code/configs to ensure all functionality works as expected with the new instance. AT LEAST the following two config changes should occur (do a search in the repo to find all instances, should at least be a docker file and gradle file). All documentation should be updated as well: 
      - `OKTA_baseUrl`
      - `OKTA_clientId`
> Note: Contact Arnej for new Okta Instance URL and CLIENT ID.

### Test Plan
1. Create a new branch for this ticket
2. Make appropriate changes locally and ensure ALL tests pass (**point to NEW STAGING OKTA INSTANCE**)
3. Pay special attention to server-server AND Okta auth tests, perform additional manual testing as necessary
4. Notify experience team backend is passing checks and have them merge their front end changes to our branch
5. Deploy the now shared branch to a demo test environment
6. Notify experience team so they can run manual functional verification and validation tests. **Experience team will merge branch when ready for release.**
7. Close this ticket and create new migration support tickets as necessary

### Risks/Impacts/Considerations

The Okta migration was a straight 1-1 copy, and the front end tests pass with only config changes, so risk for this new instance breaking RS backend functionality seems low, but could happen. If that's the case, issues are identified and new tickets are created to address them.

### Acceptance Criteria

- [ ] Branch created that points backend to new RS Okta STAGING (preview) instance
- [ ] All backend tests passing. Broken tests fixed if the issue is with the test and not the code
- [ ] [DEPENDENCY on @Andrey-Glazkv - IF TESTS PASS] Experience team merged front end changes to our branch 
- [ ] [IF TESTS PASS] Demo test environment created for experience team and experience team notified
- [ ] [IF BREAKING ISSUES WERE FOUND] new tickets created and this ticket closed.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11401?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish

**Comment by bishoyayoub** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11401?planning-poker) with Zenhub @luis-pabon-tf

**Comment by JFU-NAVA-PBC** [comment]
@arnejduranovic, @bishoyayoub  

PR approved by 2 approvals, and per experience team, merged into feature branch :
experience/new-okta

Tested authorizations off the feature branch, work as expected

**Comment by JFU-NAVA-PBC** [comment]
here are the captured test output:

`./gradlew primeCLI --args="test --run oktaauth" 
Starting a Gradle Daemon, 2 busy Daemons could not be reused, use --status for details

> Task :primeCLI
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/Users/jimfuqian-mac-pro/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-slf4j-impl/3.0.0-alpha1/e487d0eeb91c64515db130475110376c65ab0634/log4j-slf4j-impl-3.0.0-alpha1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
oktaauth : not found
No tests to run.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 5s
6 actionable tasks: 2 executed, 4 up-to-date
~/RS-New-Okta-OCT05/prime-router$ git branch
* experience/new-okta
~/RS-New-Okta-OCT05/prime-router$`

**Comment by JFU-NAVA-PBC** [comment]
prime CLI login --env staging, generate jwt:

`~/RS-New-Okta-OCT05/prime-router$ ./prime login --env staging
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/Users/jimfuqian-mac-pro/RS-New-Okta-OCT05/prime-router/build/libs/prime-router-0.2-SNAPSHOT-all.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
About to launch a browser to log in to Okta...
Login valid until 2023-10-05T22:39:41.886930
~/RS-New-Okta-OCT05/prime-router$ cat ~/.prime/accessToken.json
{
  "token" : "eyJraWQiOiIyMUF5*****************ekxpQzVDajBSaVZMSGFvX0N5d0JzIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULlZ1QUhWNXBhWDZBW******************************tOXIyRkUiLCJpc3MiOiJodHRwczovL3JlcG9ydHN0cmVhbS5va3RhcHJldmlldy5jb20vb2F1dGgyL2RlZmF1bHQiLCJhdWQiOiJhcGk6Ly9kZWZhdWx0IiwiaWF0IjoxNjk2NTY3MTgxLCJleHAiOjE2OTY1NzA3ODEsImNpZCI6IjBvYTh1dmFuMmkwN1lYSkxrMWQ3IiwidWlkIjoiMDB1YT*************************************ltZSI6MTY5NjU2NzE3OCwic3ViIjoiamltZnVxaWFuQG5hdmFwYmMuY29tIiwib3JnYW5pemF0aW9uIjpbIkRIUHJpbWVBZG1pbnMiXX0.u7Iageb03KVWZwkyzXPgirSS9GIPhTy0n8qVbRsUYKp8APMyLjLGqRPWBuy4pXEH4HKn0dVru6hrbGd2fHF-6up99i6yiEHN7P6E32DDwvwDMjTSyMjefXYZldhyz660QIgGvlsVIljvHGqK__XcHQNf-pr1F2yErqSRo34tcm5hSSh0dncOUHmYxY57bdDIlp2qDrYVd50ynWhukzjbORjv93YS5x-F9DZM99yD5jGdesJwWbpfFT41n4D9omunfFtKJTU7Vp0kyL7e6uwyWy3kOqtQVrNUBKt78WLDUTx0b8dbCNZZGVdfqSk9aBhPP7BsoIcQwycutbT8WyUo6A",
  "clientId" : "0oa8uvan2i07YXJLk1d7",
  "expiresAt" : "2023-10-05T22:39:41.88693"
}%                                                                                                                                         ~/RS-New-Okta-OCT05/prime-router$`

**Comment by JFU-NAVA-PBC** [comment]
point browser to local swagger ui:

put in the Swagger app creds (provisioned by FE team), complete the login flow:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEFPQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--065733450660969c2376d12c83ecbb9aaa454d4e/image.png)
