### ISSUE TITLE
Gather all website links

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#11414]
## Problem statement
We need a way to get the current state of all the existing linked pages on our site. So we can identity the "dead" links and old pages we need to archive.

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Python Script for crawling site for link](https://gist.github.com/NoWorries/3e4764d72e7ea7e2b27e92c73b5fdb0a) Thanks @audreykwr !

## Acceptance criteria

- [x] CSV of all the current links on the website (every hyperlink/button, where it is and where it goes)
- [x] List all places where the links are interlinked on the site and anywhere external we link.

## To do

- [ ] ...

**Comment by KeithNava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Web-Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/11414?planning-poker) with Zenhub @etanb @jpandersen87 @penny-lischer

**Comment by chris-kuryak** [comment]
@audreykwr Is this ticket finished per Penny's work with you?

Here is the link to the doc:
https://docs.google.com/spreadsheets/d/1YiLtOr0NIIeuRYvxvox2r0L19U3bLagl9IFfHPH8yb8/edit#gid=730127812

**Comment by audreykwr** [comment]
No. That gathered current page urls but this will a) make sure we didn't miss any and b) show everywhere they are interlinked on the site or anywhere external we link.

**Comment by chris-kuryak** [comment]
Ah, so it appears there are some ACs missing in this ticket.
Irrespective of the tool used (python script or not), can you update the ACs to reflect what you and Keith wanted to accomplish with this ticket @audreykwr ? Sorry I was out when I believe y'all discussed this.

**Comment by audreykwr** [comment]
Tried to add a clarification of what links we meant. Let me know if that helps.

**Comment by chris-kuryak** [comment]
From Penny: Python script requires a sitemap, which we don't have

**Comment by penny-lischer** [comment]
[ReportStream URLs.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjliQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--008f75d00980e9516bb7151493960c3cadc5e66a/ReportStream%20URLs.xlsx)

**Comment by penny-lischer** [comment]
Working doc - https://cdc.sharepoint.com/:x:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BC83087E9-F8A2-4A47-BEC9-D9A1B20D9538%7D&file=ReportStream_URLs_10_25_23.xlsx&action=default&mobileredirect=true
