### ISSUE TITLE
VA Providers List

### ISSUE THREAD

**Issue by GlennRGrieves** [CDCgov/prime-reportstream#11412]
Virginia Department of Health is looking to onboard to RS. One question they asked was what providers they would be receiving data from. Can we pull this list and share it with Glenn so he can provide?

**Comment by GlennRGrieves** [comment]
VA is looking to onboard to RS. One question they asked was what providers they would be receiving data from. Can we pull this list and share it with Glenn so he can provide?

**Comment by oslynn** [comment]
@GlennRGrieves here is VA Providers List, in Excell format.[VA-Providers-list.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdC9GIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a6abb8e78b9ea662231a15bbec0ca0dd38b4a08e/VA-Providers-list.xlsx)

**Comment by oslynn** [comment]
Done
