### ISSUE TITLE
Okta Account Unlock Instruction Email

### ISSUE THREAD

**Issue by Andrey-Glazkv** [CDCgov/prime-reportstream#11417]
As a user I want to receive an email with instructions on how to unlock my account when it gets locked, so that I can quickly resolve account lock issues and unlock it.

## What you need to know
- [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTY3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--26fb7a4652894a102b0cb7f088272b59883f4992/Screenshot%202023-09-19%20at%201.41.00%20PM.png)

- [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcSs3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--52837ea4070f9cb8401c591fd721c71eaca94b31/Screenshot%202023-09-19%20at%201.41.52%20PM.png)

## Acceptance criteria

- [ ] Email Receipt:
Given that a user's account is locked, when user gets a message that "Email sent!" from Okta, then the user should automatically receive an email with unlock instructions.

## To do

- [ ] Find a reason why unblocking email is not being generated/sent to a user
- [ ] Fix that

**Comment by jpandersen87** [comment]
Currently cannot determine why unlock emails are failing (outside of possibly being missed in their spam folders). Our instance is currently set to auto-unlock after 15 minutes in addition to the unlock workflow. Okta support may have to be contacted regarding this.

**Comment by Andrey-Glazkv** [comment]
@jpandersen87 thank you! How to contact them? What is the best way? Do you want me to do it or do you have capacity to reach out to them yourself?
cc: @KeithNava

**Comment by Andrey-Glazkv** [comment]
@jpandersen87 As you suggested - I started a ticket with Okta support on this - attached the email/request. They say it might take up to a day to get back to me on it.
@KeithNava 
[Okta has received your support request  Case Number 01869600 ref00DA0KWYD5004z1t82w4ref.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTNEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b581862a52eb3c8af84e8608d359fe5d345ad264/Okta%20has%20received%20your%20support%20request%20%20Case%20Number%2001869600%20ref00DA0KWYD5004z1t82w4ref.pdf)

**Comment by Andrey-Glazkv** [comment]
@jpandersen87 @KeithNava 
Response from Okta saying that the issue might be on our side[No unblocking email from the system     ref00DA0KWYD5004z1t82w4ref .pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2ZFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e980909b53a5cbb6aadaa83ba6b31f3a3c2396a0/No%20unblocking%20email%20from%20the%20system%20%20%20%20%20ref00DA0KWYD5004z1t82w4ref%20.pdf)
