### ISSUE TITLE
Refer to test organizations file during translation tests.

### ISSUE THREAD

**Issue by jimmyfagan** [CDCgov/prime-reportstream#11416]
### User Story
As a ReportStream developer, I want my integration tests to be independent of the contents of my primary `organizations.yml` file.

### Description/Use Case
The TranslationTests that run as part of the integration tests include options for referencing senders and receivers. The default location to read these settings from is the same as the `organizations.yml` file that is used to update settings for local runs of the server. Since that file can often be used as a scratch pad to experiment with different settings, or as a place to store settings that will eventually be applied to staging and/or production, it would be better for these tests to use test-only settings in some other location.

### Risks/Impacts/Considerations
Make sure the existing tests still work by copying any currently referenced organizations in the new file.

Since CI enforces integration tests passing, this is fairly low-risk and low-priority, however it can prevent confusion and help with repo cleanliness.

### Dev Notes
This should be fairly straightforward by just finding where the integration tests determine the path to the organizations file and editing that.

### Acceptance Criteria
- [ ] integration tests no longer depend on the contents of `prime-router/settings/organizations.yml`
- [ ] translation tests can still reference senders/receivers from a test-specific organizations file somewhere in the integration tests folder
- [ ] review with engagement team
- [ ] add developer documentation as needed

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11416?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @thetaurean
