### ISSUE TITLE
Provide Ott Read Only DB access to prod replica

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#11435]
He needs to pull some data using Azure studio. This should be documented so other folks can use it.

**Comment by jeremy-page** [comment]
Pending document

**Comment by lucasdze** [comment]
Find The steps on how to access Prod db and run queries from local env [here](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B4367C2CB-51BC-443E-93E1-954B2536B75B%7D&file=Access-Prod-DB-From_local_RunQueries.docx&action=default&mobileredirect=true)
