### ISSUE TITLE
Write documentation on how to configure a receiver's REST transport

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#11431]
### User Story
As  a ReportStream employee, I want to understand how to onboard a receiver using REST. 

### Description/Use Case
Create a document that describes how to onboard a receiver to the  UP using REST transport.  

### Dev Notes
There is a placeholder in the repo to store this info under docs/onboarding-users/transport/rest.md

### Acceptance Criteria
- [ ] There is a document that describes how to configure a receiver's REST transport

**Comment by oslynn** [comment]
PR: https://github.com/CDCgov/prime-reportstream/pull/11876

**Comment by oslynn** [comment]
Done.
