### ISSUE TITLE
Split the batch function such that the UP and legacy pipeline no longer share the same Azure function

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#11443]
### User Story
As a report stream developer, I would like a dedicated function for handling batching

### Description/Use Case
The batch function is "shared" between the legacy and UP pipeline, but this is mostly superficial as the code quickly bifurcates based on which pipeline the topic is configured with.  Splitting up these functions would further clarify the use of topic and allow the team to make changes to the UP without considering impacts to the legacy.

### Risks/Impacts/Considerations
Existing batching is impacted while doing the split

### Dev Notes
- Most of the logic for the UP is already isolated in it's own [function](https://github.com/CDCgov/prime-reportstream/blob/463b9f0dc13139919fdfac2f52a058d2f00045c2/prime-router/src/main/kotlin/azure/BatchFunction.kt#L185)
- A new queue should get added to support the batch step, current understanding is that this will not require infra support but that should be confirmed

### Acceptance Criteria
- [ ] A new azure function and queue exist that is dedicated to batching data from the UP

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11443?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @thetaurean
