### ISSUE TITLE
Remove the use of topic in FhirTranslator

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#11442]
### User Story
As a report stream, I would like to keep the use of Topic narrow and specific

### Description/Use Case
The translate step currently checks that the topic for the receiver of the message is from the Universal pipeline which is not necessary as this already has been done in the routing step.

### Risks/Impacts/Considerations
The only extreme edge case is if a receiver has there topic edited in between the route step and the translate step; however, this would almost certainly just be a configuration error and should not bleed into the code.

### Dev Notes
[Line](https://github.com/CDCgov/prime-reportstream/blob/463b9f0dc13139919fdfac2f52a058d2f00045c2/prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt#L88) in question.

### Acceptance Criteria
- [x] Topic is not used in FhirTranslator

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11442?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @thetaurean
