### ISSUE TITLE
Covid <-> UP Migration (Q4-2023)

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#11457]
## Problem statement
The COVID pipeline was not built to accept conditions beyond COVID-19 for the long term. As such, we need to migrate all of our senders and receivers over to the Universal Pipeline at some point in the future. The goal is to migrate all of our data and users from the COVID pipeline to the Universal Pipeline with minimal negative impact to the user (ensuring senders can continue to operate normally).

Based on the documentation created in Q3 (#10158), the goal for Q4 is to develop a plan for how RS will migrate all senders and receivers from COVID pipeline to UP.

## What you need to know
This will likely happen in 4 stages:

- Developing an overall migration strategy
- Developing a receiver migration strategy
- Developing an HL7 sender migration strategy
- Developing a CSV sender migration strategy

**Comment by MikaelahD13** [comment]
Closing, work completed.
