### ISSUE TITLE
Exclude backend tests of report stream during FE build 

### ISSUE THREAD

**Issue by kant777** [CDCgov/prime-reportstream#11458]
Currently FE build fails whenever BE tests fail. For example, the FE [build](https://github.com/CDCgov/prime-reportstream/actions/runs/6265249720/job/17013708731) fails with the error below. So we should exclude BE tests in FE build github actions.

```
  Test test now timestamp logic to local time zone() FAILED

  org.opentest4j.AssertionFailedError: expected to be between:<3L> and <4L> but was:<2L>
      at app//gov.cdc.prime.router.common.DateUtilitiesTests.test now timestamp logic to local time zone(DateUtilitiesTests.kt:315)

```

**Comment by kant777** [comment]
https://github.com/CDCgov/prime-reportstream/pull/11459/files

**Comment by kant777** [comment]
The worked here is potentially integrated into this [PR](https://github.com/CDCgov/prime-reportstream/pull/11701)

**Comment by snesm** [comment]
@kant777 backed build for SonarCloud has been move to a [separate workflow](https://github.com/CDCgov/prime-reportstream/pull/11587) which should make this issue obsolete.

**Comment by LaFreda1** [comment]
Devops fixed this issue
