### ISSUE TITLE
Test test order data in the UP

### ISSUE THREAD

**Issue by brandonnava** [CDCgov/prime-reportstream#11467]

**Comment by oslynn** [comment]
These are test ORDER messages for Flexion testing:
[OML-test-FHIR-message-from-flexion-etor-service-sender-to-laphl-(etor-nbs-orders)-json.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzEwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84be701beffed6de6be4259249c01691b351819d/OML-test-FHIR-message-from-flexion-etor-service-sender-to-laphl-%28etor-nbs-orders%29-json.txt)

Screenshot of Postman send message from etor-service-sender to la-phl:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE4wQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d7c74d4d521b68afd515af13462981a30737de9/image.png)

Docker log:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFIwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6d1540053a3a448b04e5f2dd4e66ac1bd1f8737/image.png)

**Comment by oslynn** [comment]
Sending ORDER message from LA-PHL to Flexion.etor-service-receiver:[ORM-order-test-message-send-from-la-phl-(etor-nbs-results)-to-etor-service-receiver-hl7.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFYwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4cdd35a0f9d6931903d79e4b2721d43d242948a7/ORM-order-test-message-send-from-la-phl-%28etor-nbs-results%29-to-etor-service-receiver-hl7.txt)

Postman screenshot:
[Private Zenhub Image]
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHAwQVE9PSIsImV4cCI6bnVsbCwi
cHVyIjoiYmxvYl9pZCJ9fQ==--05f97c662f15abb0504030b812fa2bd921933ba3/image.png)

Docker log:

**Comment by oslynn** [comment]
Completed.
