### ISSUE TITLE
Restructure translation files for HL7v2->FHIR and FHIR->HL7v2

### ISSUE THREAD

**Issue by jimmyfagan** [CDCgov/prime-reportstream#11472]
### User Story
As a ReportStream developer, I want to have the files used to translate between HL7 segments/datatypes and FHIR resources/values arranged in an organized way that makes the intentions of each file clear.

### Description/Use Case
Historically, `prime-router/metadata/hl7_mapping/common/datatype` has been filled with schemas that are specific to each HL7 datatype, and each of those schemas might handle conversion from several different FHIR resources into that HL7 datatype. In [this PR](https://github.com/CDCgov/prime-reportstream/pull/11174), we introduced a slightly new idea; instead of having only one schema for all `HD` datatype conversions, we added a new file `hd-location.yml` which specifically only handles conversion from FHIR `Location` to HL7 `HD`. Schemas are a lot more readable and manageable when they have one specific purpose, and that is probably how we should approach these moving forward. However, there are also schemas `pl-location.yml`, which handles other conversions from FHIR `Location`s, and `hd-hierarchic-designator`, which handles other conversions to HL7 `HD`s. 

We need to establish a folder structure and naming format which allows for one-to-one FHIR-to-HL7 schemas like `hd-location.yml`, while also maintaining existing datatype schemas that are more general. Many of the existing general schemas can likely be replaced with one-to-one schemas over time, but some may stay as they are. Sometimes instead of mapping from a specific FHIR resource, we are mapping from a custom extension, so those kinds of cases should be considered as well.

On the HL7->FHIR side, we have a similar task in `prime-router/metadata/fhir_mapping/hl7/datatype`, where we recently introduced `Identifier_XON.yml` which specifically deals with populating an `Identifier` based on an `XON`. There is a greater variety of existing file names and intents on this side, so the existing format may suffice, but should also be revisited as part of this.

### Risks/Impacts/Considerations
IDE tools may not simplify the refactor of moving/renaming referenced schemas. So any moving or renaming of files should be done carefully (though automated tests should highlight any issues).

### Acceptance Criteria
- [x] `prime-router/metadata/hl7_mapping/common/datatype`'s contents are organized such that the intent of each sub-schema file is clear - team has decided to do this as a part of data type mappings (epic #11655)
- [ ] The organization plan for `prime-router/metadata/hl7_mapping/common/datatype` has been documented, perhaps in a README.md file in the folder
- [x] `prime-router/metadata/fhir_mapping/hl7/datatype`'s contents are organized such that the intent of each template file is clear (epic #11655)
- [ ] The organization plan for `prime-router/metadata/fhir_mapping/hl7/datatype` has been documented, perhaps in a README.md file in the folder

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11472?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @thetaurean

**Comment by Andrey-Glazkv** [comment]
Might not get finished 
Check acceptance criteria later on

**Comment by Andrey-Glazkv** [comment]
Need to define the scope here
