### ISSUE TITLE
Add tests for common components affected by HCI changes

### ISSUE THREAD

**Issue by jimmyfagan** [CDCgov/prime-reportstream#11471]
### User Story
As a ReportStream developer, I want to have tests that confirm expected behavior for translation of common HL7v2/FHIR elements.

### Description/Use Case
In [this PR](https://github.com/CDCgov/prime-reportstream/pull/11174), many mappings were updated for common components not specific to HCI, but to limit scope, we didn't build out tests for those. This story involves adding tests for some of these changes, following the rough format introduced in [this PR](https://github.com/CDCgov/prime-reportstream/pull/11147).

### Risks/Impacts/Considerations
None

### Dev Notes
Since there will be further mapping updates in upcoming epics/stories, the test coverage is not expected to be 100% complete, but should cover the major pieces of the mapping updates in [this PR](https://github.com/CDCgov/prime-reportstream/pull/11174) to ensure that those segment translations are stable moving forward.

### Acceptance Criteria
- [ ] Automated tests for specific segments/datatypes/resources have been added for the mapping updates covered in [this PR](https://github.com/CDCgov/prime-reportstream/pull/11174)
- [ ] The segment-specific automated tests are organized in the file structure in a sustainable format, consistent with the test plan introduced in [this PR](https://github.com/CDCgov/prime-reportstream/pull/11149)

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11471?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @thetaurean

**Comment by Andrey-Glazkv** [comment]
Might not get finished this sprint

**Comment by Andrey-Glazkv** [comment]
Closing since tests will be written as a part of mapping and some tests are completed
