### ISSUE TITLE
Wireframe: Receiving data 

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#11493]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

This ticket captures the work of putting together the **Get started receiving data** sublanding page. 

## Working links

- Figma: [Working file](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=3985%3A4176&mode=design&t=BSyZxvIVAsGU1Cbk-1)
-  Content doc: [Receiving data](https://docs.google.com/document/d/1cewTIEbvIuUc00Qc-G8vzULZ8ZIbedQDCkrNYSN-vyQ/edit)

## Acceptance criteria
**Design**
-   [x] Design is ready for handoff (i.e. dev ready)
-   [x] Design includes latest content updates
-   [x] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Review**
-   [x] Reviewed with design and/or design lead
-   [x] Reviewed with content strategist for final approval
-   [x] Reviewed with product and engineering

**Comment by yudonoodles** [comment]
10/02 Reviewed with design and engineering + product.

**Comment by yudonoodles** [comment]
10/06 Moved design to Ready for dev space on figma. Closing ticket.
