### ISSUE TITLE
Research plan: Compile user test notes

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#11490]
## User story

As a ReportStream designer/researcher, I want to conduct usability testing of the ReportStream website's redesign so that we can incorporate user feedback into the ongoing content/design development of the website.

## Background & context
This ticket captures the work of cleaning up and formatting the verbatim notes / recordings in preparation for deeper synthesis. 

## Open questions
N/A

## Working links

-   Document: [Website redesign research plan working space](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit?usp=drive_link)
- [Draft plan](https://docs.google.com/document/d/1d34d1qZqF5MdOx6l32venfMB8-PwI2yqwkWYqg72irk/edit?usp=sharing)
- [Moderator guide](https://docs.google.com/document/d/1PS3ToJtuhCQidXidTTIWNzq1SZe_-E4NTJsM5AkZiUA/edit)
- [Research participant tracker](https://docs.google.com/spreadsheets/d/1oZ3jMVo0n-IUDWPlwLqNzllcf9egpu9MUF4jU1rJxfI/edit#gid=0)
- Add link to raw notes

## Acceptance criteria
-   [ ] CT DPH notes cleaned and ready for deeper synthesis
-   [ ] Informatics Innovation notes cleaned and ready for deeper synthesis
-   [ ] HLN notes cleaned and ready for deeper synthesis
-   [ ] WI DPH notes cleaned and ready for deeper synthesis
-   [ ] NETPHD notes cleaned and ready for deeper synthesis

**Comment by audreykwr** [comment]
[Notes inputted in this mural] for synthesis (https://app.mural.co/t/nava4113/m/nava4113/1673278109303/c503de31acc97baa86ed289bbb56cbd48739e6f4?sender=uc55a7af3b66977fba12f5528)
