### ISSUE TITLE
Content update: Getting started - accepted conditions

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#11491]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

The accepted data types and conditions section of the Getting started page should be updated to include additional conditions. See feedback from Mo sent via Slack 9/20/23: 

> Questions about the future for this part of the getting-started page. Now that flu is live in CA, and going to other states soon™, can we change “More coming soon” to Influenza, and update the text underneath to say “We are currently adding support for RSV and HIV, and building support for all reportable conditions soon.”
> I also am thinking about what this needs to look like to reflect the fact that we’re building support for ETOR. Is there a defined content plan for reflecting ETOR on our site that I can review?

This ticket captures the work of making the content update.

## Open questions
- Should this be updated in the Figma, word doc, or both?

## Working links
-  [Figma](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=3707%3A5929&mode=design&t=fk1aRUxyUet1Ob5W-1)
-  [Word doc](https://docs.google.com/document/d/1EOEnUoHJgrUWkIChTo0GkVnbbLkzkN65CHC5L3tTo34/edit#heading=h.4tnbzlz6x88o)

## Acceptance criteria
-   [ ] Final draft created and reviewed/approved by content owner
-   [ ] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Comment by audreykwr** [comment]
[Follow on ticket created for eng](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/11592)
