### ISSUE TITLE
Update Buttons on site to links

### ISSUE THREAD

**Issue by KeithNava** [CDCgov/prime-reportstream#11505]
## Problem statement

The initial ask for this feature came from this [slack thread](https://nava.slack.com/archives/C02HJ43AE8Z/p1695307971065539) where we discussed the idea of changing the [PDF download link](https://reportstream.cdc.gov/resources/api) from a button (that looks like a link) to an actual native link. The reason this particular link is a button is because there's some custom analytics tracking that happens on the link click. 

Since we have a ticket to look into automating the tracking of link clicks and buttons (https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/9980) we should use this ticket as a follow up to ensure that the link tracking works and then **replace the button with a proper link**

## What you need to know

- [Spike on Link tracking](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/9980)

## Acceptance criteria

- [ ] PDF download link is an actual native link and **not** a button
- [ ] Link click is tracking in Azure App Insights (Or whatever tracking service we decide to use)

## To do

- [ ] Turn button into link

**Comment by chris-kuryak** [comment]
closing as this issue was resolved
