### ISSUE TITLE
Navigation: Add dropdown for "About" section

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#11504]
## Describe the bug
The nav bar's "About" section is missing a dropdown to the subpages.

## Impact on ReportStream
The dropdown will make it easier for users to quickly find what they're looking for in the the About (currently, the site's largest section).

## Steps to reproduce
1. Go to 'reportstream.cdc.gov'
2. Click on 'About'
3. See that no dropdown appears.

## Expected behavior
Upon click, the dropdown menu should appear listing the following links:
- Our network
- News
- Case studies
- Security
- Release notes

## Resources
N/A

## Logs
N/A

## Device info 
N/A 

## Additional context
The dropdown functionality is already built, it just needs to be toggled on for the About section. Depending on when this ticket is picked up, the pages that are still being engineered (Case Study, News, Security) will have to be added later.

**Comment by penny-lischer** [comment]
Per Jillian

> I confirmed with Audrey - we can add a link that says "About ReportStream" (instead of "Overview") that redirects to the About landing page
