### ISSUE TITLE
Establish formatting settings for different file types

### ISSUE THREAD

**Issue by jimmyfagan** [CDCgov/prime-reportstream#11503]
### User Story
As a ReportStream developer, I want to have defined formatter settings for the various different file types used in our repos, so that all contributors will have their files formatted the same way, and whitespace changes will be less common in PRs.

### Description/Use Case
While we have a linter in the pre-commit for `.kt` files, there are whitespace changes not enforced by `ktlint`, and there are non-`.kt` files that have no established formatting rules. This leads to large whitespace changes in files when one developer applies their formatting to a file that was previously not formatted, or was formatted with different rules.

We need to document our formatting settings, and include importable formatter settings somewhere in the repo. Our contributing instructions should include reference to those settings. This ticket doesn't necessarily need to include updating every file to conform to the new formatter, but should at least solidify what the format of those files _should_ be.

### Risks/Impacts/Considerations
Depending on how we roll out updates to files that are currently not following the new rules, there could be many merge conflicts to resolve. We'll need to be strategic about rolling this out to avoid that as much as we can.

### Dev Notes
The main file types that have these kinds of issues are `.kt`, `.fhir`, and `.yml` files. There may be others for the frontend as well, but the Experience team should probably be left to make those kinds of decisions on their own.

### Acceptance Criteria

- [ ] We have formatter settings saved somewhere in the repo for the following file types:

  - [ ] `.fhir`
  - [ ] `.kt`
  - [ ] `.yml`

- [ ] Instructions for setting up formatters are included in the "contributing" or "getting started" documentation
- [ ] Existing files have been updated to adhere to new rules - RISK: A lot of changes to be applied for FHIR files

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11503?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @thetaurean
