### ISSUE TITLE
Check ability to map SNOMED codes to positive and negative values in the UP

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#11501]

**Comment by LaFreda1** [comment]
@victor-chaparro TO ADD DETAILS

**Comment by adegolier** [comment]
We have a lookup table for this, but it seems to be set up more to map a result to a snomed code than the other way around as there are multiple results listed for a snomed (e.g. "Neg", "Negative", "Not Detected" all map to the same snomed "260385009")

**Comment by victor-chaparro** [comment]
I believe those lookup tables are not in the database and only stored in the repo. The UP doesn't have a way to read those value sets, but it looks like this might actually work with the code to condition table. So all we would need to is to add the values in the lookup table there. This would only be needed once we add CSV support if we decide to do, because it looks like this was only used for CSV senders?

**Comment by adegolier** [comment]
They're in the database, that's where I looked for them....

**Comment by victor-chaparro** [comment]
When I was looking at this I was specifically looking at the `Obx8Mapper` used in the covid pipeline. 
```
- name: abnormal_flag
    type: CODE
    valueSet: hl70078
    natFlatFileField: Abnormal_flag
    hhsGuidanceField:
    hl7Field: OBX-8
    mapper: obx8(test_result)
```

```
 when (values[0].value) {
                    "260373001" -> "A" // Detected
                    "260415000" -> "N" // Not Detected
                    "720735008" -> "A" // Presumptive positive
                    "42425007" -> "N" // Equivocal
                    "260385009" -> "N" // Negative
                    "10828004" -> "A" // Positive
                    "895231008" -> "N" // Not detected in pooled specimen
                    "462371000124108" -> "A" // Detected in pooled specimen
                    "419984006" -> "N" // Inconclusive
                    "125154007" -> "N" // Specimen unsatisfactory for evaluation
                    "455371000124106" -> "N" // Invalid result
                    "840539006" -> "A" // Disease caused by sever acute respiratory syndrome coronavirus 2 (disorder)
                    "840544004" -> "A" // Disease caused by severe acute respiratory coronavirus 2 (situation)
                    "840546002" -> "A" // Exposure to severe acute respiratory syndrome coronavirus 2 (event)
                    "840533007" -> "A" // Severe acute respiratory syndrome coronavirus 2 (organism)
                    "840536004" -> "A" // Antigen of severe acute respiratory syndrome coronavirus 2 (substance)
                    "840535000" -> "A" // Antibody to severe acute respiratory syndrome coronavirus 2 (substance)
                    "840534001" -> "A" // Severe acute respiratory syndrome coronavirus 2 vaccination (procedure)
                    "373121007" -> "N" // Test not done
                    "82334004" -> "N" // Indeterminate
                    else -> null
                }
```

The SNOMED codes are hardcode there, but it looks like we can actually use a lookup table instead, not sure why the covid pipeline is not doing that.

**Comment by adegolier** [comment]
Probably because, like I said, the lookup table is set up to map one SNOMED code to multiple "display" values, not the other way around.... Although it seems like it shouldn't be hard to add the normal/abnormal flag to the test result lookup. Not sure if there's something I'm missing there.

**Comment by victor-chaparro** [comment]
I'm also not sure if we're missing anything. That's the purpose of the ticket, but we can revisit this when we have time.

**Comment by adegolier** [comment]
I'm like 99% sure that if we added a "flag" value for A/N to the test_result lookup table this would work fine in UP. I'm just not sure if adding that would break the lookups that use that table in the Covid pipeline.
