### ISSUE TITLE
[BUG] Manage Public key does not handle when org has no senders

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-reportstream#11514]
## Describe the bug
If an org (ar-phd) does not have any senders the UI is not applicable.

## Impact on ReportStream
Bad user experience

## Steps to reproduce
1. Go to RS
2. Select an org without senders, i.e. ar-phd
2. Click on 'Your connection -> Manage Public Key'
3. See screen

## Expected behavior
There should be a message informing the user as to why they cannot upload a key.

## Resources
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbW5OIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a45922d2cc5ab6e7bdd9b6218a9769b353ba6be8/Screenshot%202023-09-22%20at%203.39.09%20PM.png)

**Comment by chris-kuryak** [comment]
Thanks for filing the bug @penny-lischer !

Quick question: AR-PHD is a receiver, not a sender, right? So is this a bug that is basically stating that this feature does not work for any receivers? Just checking, as I think that is how it was originally designed, and I agree that we may need a better user experience here for receivers so they don't try to use it.

**Comment by penny-lischer** [comment]
@chris-kuryak correct, for all receivers. 
Looks like this issue is not happening anymore so we can close this.

**Comment by chris-kuryak** [comment]
Thanks @penny-lischer !
Closing
