### ISSUE TITLE
Document managing Code to Condition Table

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#11511]

**Comment by GilmoreA6** [comment]
PR#11906 is up for review.

**Comment by GilmoreA6** [comment]
Related to #9248. New document should include managing and updating table, creating and working metabase queries and managing unmapped queue.

**Comment by GilmoreA6** [comment]
Working with Arnej on potential change in strategy. Arnej to modify tickets and bring recommendations back for discussion

**Comment by GilmoreA6** [comment]
PR#11906 merged
