### ISSUE TITLE
Link fix: About landing page - Our network

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#11513]
## Describe the bug
The link to the "Our network" page on the About landing page is broken.

## Impact on ReportStream
Users are unable to access the newly updated and designed Our network page.

## Steps to reproduce
1. Go to 'reportstream.cdc.gov/about'
2. Click on 'Our network' under the 'In this section' section.
3. See that it goes to the old page.

## Expected behavior
The link should go to the new URL: https://reportstream.cdc.gov/about/our-network

## Resources
N/A

## Logs
N/A

## Additional context
Add any other historical context about the problem here.

**Comment by penny-lischer** [comment]
This is fixed as part of PR - webx-sprint-77-feature-branch
