### ISSUE TITLE
Okta: Email After 30-day Expiration email

### ISSUE THREAD

**Issue by Andrey-Glazkv** [CDCgov/prime-reportstream#11534]
## Problem statement
We need to send a reminder email to users 30-day after expiration.

## What you need to know

- [Comms Plan](https://docs.google.com/document/d/18qw6o07oT1npmL_37opzm4s2e9a48-XO/edit)
- ...

## Acceptance criteria

- [ ] Send an email to users after 30-day expiration

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@chris-kuryak this is probably work for next sprint?

**Comment by audreykwr** [comment]
@chris-kuryak @TaneaY I'm good with what we have now in the communications plan doc! This ticket was written with the AC to send it, but obviously that's not a me task. So maybe we close this and make a new one for that for next sprint?

**Comment by TaneaY** [comment]
@chris-kuryak @audreykwr sounds good when will support receive the list of user not yet migrated for send out. I would like to schedule on 12/21 by 5pm for 12/22 8am EST send out just need the recipients. Thank you!

**Comment by chris-kuryak** [comment]
@TaneaY here is the list: [link](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7Bc476fe16-79f8-4cdb-afd7-c9441c57c35d%7D&action=editnew)

Sorry I missed the cutoff on this! I forgot about EST.

It is totally okay if this doesn't go out tomorrow morning or even tomorrow at all. It can wait until Tues Dec 26 if necessary.

**Comment by chris-kuryak** [comment]
Email sent, closing.
