### ISSUE TITLE
Link fix: Support landing page - "Managing your connection" link

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#11554]
## Describe the bug
The link to the "Managing your connection" page on the Support landing page is broken.

## Impact on ReportStream
Users encounter a broken link when looking for more information.

## Steps to reproduce
1. Go to 'https://reportstream.cdc.gov/support'
2. Navigate to the 'Using ReportStream' section and see the Related page card callout.
3. Click on 'Managing your connection'.
4. See the 404 message.

## Expected behavior
The link should go to the new URL: https://reportstream.cdc.gov/managing-your-connection

## Resources
N/A

## Logs
N/A

## Additional context
Add any other historical context about the problem here.

**Comment by penny-lischer** [comment]
Fixed as part of #11267 - https://github.com/CDCgov/prime-reportstream/pull/11736#event-10622141362
