### ISSUE TITLE
VT - LIVD Testkit Name ID Issue 

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#11552]
## **Problem Statement**

On 9/7/2023 we received an email from VT stating that there's an error with the Testkit Name ID - where its a text instead of a numerical value.  After digging into this we found the results came from SimpleReport so we escalated to SR engineering.  However, they said that the Testkit Name ID is managed by reportstream.  

## **What you need to know**
Spreadsheet originally provided to SimpleReport Engineering.[RSandSRDatasenttoVT.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGpiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2bdf774d114e608c9f330997a5f7b06c3c79894f/RSandSRDatasenttoVT.xlsx)

Screenshot sent by SR Engineering:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaERiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1d4d848be5ec861b01b3a9e4f07615693e609380/9-26-23.png)

## **Acceptance Criteria**
Please check/confirm that the Device/LVID Testkit Name ID is incorrect.  If yes please fix and let helpdesk know so we can inform the customer.

## **To Do**
Assign to engineer

## **Additional Comments**
If you need more clarification please reach out to me at roy2@cdc.gov (Sharon)

**Comment by oslynn** [comment]
Those three messages are missing OBX-17.1, -17.3, -17.9

**Comment by oslynn** [comment]
VT is fixed and resubmitted to their prod folder ./Prod/ToVDH the following files:
covid-19-fcdc674d-324a-4228-a222-c453478360e2-20231002134828.hl7
covid-19-55070ba9-e2d0-43bb-afc9-6cfc8f50a29b-20231002131253.hl7
I will close the ticket, now.
