### ISSUE TITLE
Brainstorm sample support issues to map to service map

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-reportstream#1156]
Goal: Brainstorm issues to use for service mapping exercise (https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-data-hub/1155)

Acceptance criteria: Complete spreadsheet https://cdc-my.sharepoint.com/:x:/r/personal/qpu0_cdc_gov/_layouts/15/Doc.aspx?sourcedoc=%7BFD31D5D1-F80F-42E2-A5E9-AFEB3E26B94B%7D&file=ReportStream%20Support%20Operations%20-%20Question%20Tagging.xlsx&wdOrigin=OFFICECOM-WEB.MAIN.MRU&ct=1621876424988&action=default&mobileredirect=true

**Comment by drew-usds** [comment]
From meeting on 6/23

https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1623079956784/93ae9029b92ee894b20c5a24bc6a7f61f17fd72d?sender=ud6a3555dd1821b626a2b3726

**Comment by jlusds** [comment]
Initial set of issues done
