### ISSUE TITLE
LinuxForHealth Library: Add Extension support for primitive elements

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#11579]
### User Story

As a ReportStream developer,
I need to be able to create mappings for extensions on primitive elements in a maintainable way
so that I can complete the Mappings in the HL7 mapping inventory

### Description/Use Case

This ticket aims to open a PR that fixes [HAPI library issue 2801
](https://github.com/hapifhir/hapi-fhir/issues/2801) so that we can create needed mappings specified by the mapping inventory.

UPDATE: After some investigation, it looks like this ticket may be a red herring and the actual issue is in the linux for health library.

### Dev Notes

The fix should be tested via tests in the library itself. While we wait for it to be merged and released, we can continue to pursue the alternate strategy of implementing the functionality specified by these mappings via bundle extension functions in kotlin.

### Acceptance Criteria

- [ ] PR opened in library repo that allows extending primitives

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11579?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @luis-pabon-tf @thetaurean @mkalish

**Comment by Andrey-Glazkv** [comment]
@arnejduranovic to update the ticket

**Comment by Andrey-Glazkv** [comment]
Check on 10/19, then Michael will email them and cc Andrey
