### ISSUE TITLE
CA - Full ELR Staging Error 9/29/23

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#11583]
## **Problem Statement**

A "pdhstaging-alertrule-functionapp-fatal" alert was posted to Slack at 12:20 AM.

## **What you need to know**

Error details:

> [1;31m04:12:33.343 [pool-2-thread-79][692] FATAL-ALERT gov.cdc.prime.router.azure.SendFunction - FAILED Sftp upload of inputReportId `4c710f67-508c-41dd-8186-ec786df8d2dc` to SFTPTransportType(host=saphiresftpstage.cdph.ca.gov, port=22, filePath=./, credentialName=null) (orgService = ca-dph.full-elr-saphire-stage), Exception: Status code 404, '{'error':{'code':'SecretNotFound','message':'A secret with (name/id) CA-DPH--FULL-ELR-SAPHIRE-STAGE was not found in this key vault. If you recently deleted this secret you may be able to recover it using the correct recovery command. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125182'}}', All retries failed. Manual Intervention Required. Send Error report for: `4c710f67-508c-41dd-8186-ec786df8d2dc` to ca-dph.full-elr-saphire-stage

## **Acceptance Criteria**

Investigate and resolve error.

## **To Do**

Investigate and resolve error.

## **Additional Comments**

N/A

**Comment by oslynn** [comment]
Fixed.
