### ISSUE TITLE
CA - ELR Staging Error 9/29/23

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#11584]
## **Problem Statement**

A "pdhstaging-alertrule-functionapp-fatal" error was posted to the O&O Slack channel.

## **What you need to know**

Error details:

> [1;31m07:35:30.034 [pool-2-thread-117][889] FATAL-ALERT gov.cdc.prime.router.azure.SendFunction - FAILED Sftp upload of inputReportId `a68ab499-3547-442d-abb9-5dacedd0d1b7` to SFTPTransportType(host=saphiresftpstage.cdph.ca.gov, port=22, filePath=./, credentialName=null) (orgService = ca-dph.elr-saphirestage), Exception: Status code 404, '{'error':{'code':'SecretNotFound','message':'A secret with (name/id) CA-DPH--ELR-SAPHIRESTAGE was not found in this key vault. If you recently deleted this secret you may be able to recover it using the correct recovery command. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125182'}}', All retries failed. Manual Intervention Required. Send Error report for: a`68ab499-3547-442d-abb9-5dacedd0d1b7` to ca-dph.elr-saphirestage[m

## **Acceptance Criteria**

Investigate and resolve error.

## **To Do**

Investigate and resolve error.

## **Additional Comments**

N/A

**Comment by oslynn** [comment]
Fixed.  It has been inactive for a while.
