### ISSUE TITLE
Update mapping for XTN data types

### ISSUE THREAD

**Issue by jimmyfagan** [CDCgov/prime-reportstream#11591]
### User Story
As ReportStream, I must implement the [HL7v2 -> FHIR Mapping inventory](https://docs.google.com/spreadsheets/d/1PaFYPSSq4oplTvw_4OgOn6h2Bs_CMvCAU9CqC4tPBgk/edit#gid=0) for the XTN data type in order to support onboarding future Senders to the Universal Pipeline.

**Note:** If a mapping does not exist in the inventory, only fields specified by NIST 2.5.1 should be considered to help limit the scope to a manageable level

### Description/Use Case
Presently, RS implements mappings for the XTN datatype, but some of these should be updated based on design findings in [story #11470](https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/11470). The mapping-relevant requirements are listed here:

- When an email address is in XTN.4 AND `x.400` is in XTN.3, output `x.400` in XTN.3
- When an email address is in XTN.4 AND `Internet` is in XTN.3, output `Internet` in XTN.3
- When an email address is in XTN.4 AND XTN.2 is blank or contains anything other than `x.400` or `Internet`, output `Internet` in XTN.3
- When an email address is in XTN.4 AND XTN.3 is blank or contains anything other than `NET`, output `NET` in XTN.4

Some of these requirements are already met by the current behavior. This story should also include any other gaps in the current implementation of the mapping that differ from the spreadsheet [here](https://docs.google.com/spreadsheets/d/1g4TA7CC4zHkWmGvGQdskKJ3DrOdVQVS3MooE_iU9CuU/edit#gid=0), as well as updates/additions to tests.

### Risks/Impacts/Considerations
Some integration tests will need updates here, but overall, those updates should be minor and should not affect any currently onboarded STLTs.

### Dev Notes
None

#### Test Plan
Test Plan: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/design/proposals/mapping-inventory-test-plan.md
PR That implements test plan, use as example: https://github.com/CDCgov/prime-reportstream/pull/11147

### Acceptance Criteria
- [ ] XTN segment mappings updated to match [HL7v2 -> FHIR Mapping inventory ORU_R01](https://docs.google.com/spreadsheets/d/1gHK6_PFyr7PXns7wLDs0LSLsbjm0x-4bWUu3crXMKMI/edit#gid=0)
- [ ] XTN mappings cover the behavior outlined in [#11470](https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/11470)
- [ ] Tests created and passing, per the linked test plan

**Comment by arnejduranovic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11591?planning-poker) with Zenhub @jalbinson @mkalish @JFU-NAVA-PBC @thetaurean @jack-h-wang @brick-green
