### ISSUE TITLE
Onboarding LIMS vender (Natus) sender (Louisiana)

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#11601]
, TI is going to have a virtual kick-off with the CDC, us contractors, LA public health lab, and their LIMS vendor (Natus).  On October 12th between 10:30 AM - 12:00 PM EDT there is technical integration session (basically a hackathon) to integrate Natus with ReportStream or whatever else needs to be done at that point to make Natus work with the system.  Some of that work could easily involve onboarding tasks where 
@OTT SATHNGAM
's help will be invaluable!  
@OTT SATHNGAM
 can you please attend that session?  I will get you an invite.

**Comment by oslynn** [comment]
Onboarding la-phl.etor-nbs-results as sender and la-phl.etor-nbs-orders as receiver.

**Comment by oslynn** [comment]
Staging environment for la-phl.etor-nbs-results (sender) and la-phl.etor-nbs-orders (receiver) are done.  We only wait for CDC to whitelist Natus's SFTP hostname.

**Comment by chris-kuryak** [comment]
Still awaiting white-listing by CDC @LaFreda1

**Comment by oslynn** [comment]
Setting: for staging environment is done and awaiting for CDC to whitelist LA-PHL server.  After that, I will send test message to their server from RS staging to see if it is ok.

**Comment by LaFreda1** [comment]
ETOR will now begin a connection with Alabama

**Comment by chris-kuryak** [comment]
LA-PHL has been whitelisted!

**Comment by LaFreda1** [comment]
@oslynn Is onboarding completed for LA? Can we close this ticket?

**Comment by chris-kuryak** [comment]
I believe they are still working on finishing up some onboarding and testing.

**Comment by LaFreda1** [comment]
Validation is now on LA side.

**Comment by LaFreda1** [comment]
Work has been completed so I am closing this ticket for now. Will create a new ticket for upcoming work and reference this one.
