### ISSUE TITLE
VT - Received additional errors from SR submissions on multiple dates

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#11612]
## **Problem Statement**

Andrew Gross sent an email to the ReportStream inbox notifying us of additional messages that are throwing validation errors.

## **What you need to know**

Email received:

> VDH can confirm that a few of the files were indeed received successfully. There are still some that are outstanding (a few new ones since we generated our request, plus one original that does not appear to have processed). I’ve included the details below:
> 
> - Message Control ID
> - Accession Number
> - Date Received
> - Reason for Failure
> 
> A. `569b28c9-f4d9-447b-b3c1-457a36877807`
> B. `569b28c9-f4d9-447b-b3c1-457a36877807`
> C. 8/31/2023
> D. Description="Field did not match regular expression for advanced validation rule 1"/>PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[0].OBX.ObservationMethod[0].OriginalText" Description="Situational rule violated"/>
> 
> 1. `626d64f9-02de-4f4d-b435-c25b965be196`
> 2. `626d64f9-02de-4f4d-b435-c25b965be196`
> 3. 9/6/2023
> 4. Description="Field did not match regular expression for advanced validation rule 1"/>PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[0].OBX.ObservationMethod[0].OriginalText" Description="Situational rule violated"/>
> 
> A. `0492ed9a-1d97-4b51-acde-aede950c66bc`
> B. `0492ed9a-1d97-4b51-acde-aede950c66bc`
> C. 9/20/2023
> D. Description="Field did not match regular expression for advanced validation rule 1"/>PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[0].OBX.ObservationMethod[0].OriginalText" Description="Situational rule violated"/>
> 
> 1. `99f567a7-3f4e-4cd6-af47-3d4b00311a99`
> 2. `99f567a7-3f4e-4cd6-af47-3d4b00311a99`
> 3. 9/27/2023
> 4. Description="Field did not match regular expression for advanced validation rule 1"/>PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[0].OBX.ObservationMethod[0].OriginalText" Description="Situational rule violated"/>
> 
> Thanks!

## **Acceptance Criteria**

Determine cause of errors on messages received from SimpleReport by the ReportStream application and resolve it.

## **To Do**

- Determine why these errors are occuring
- Correct issue and test

## **Additional Comments**

N/A

**Comment by oslynn** [comment]
Input files:

MSH-10: 569b28c9-f4d9-447b-b3c1-457a36877807
pdi-covid-19-f77dbbba-91e7-42c6-a73c-5f477e17c9c4-20230831151200.csv

MSH-10: 626d64f9-02de-4f4d-b435-c25b965be196
pdi-covid-19-a412f96a-fe3e-4d54-85ef-9d08d3cbfd4f-20230906152800.csv

MSH-10: 0492ed9a-1d97-4b51-acde-aede950c66bc
pdi-covid-19-43525277-5509-48d5-bbbc-b5367e4b0039-20230920132000.csv

MSH-10: 99f567a7-3f4e-4cd6-af47-3d4b00311a99
pdi-covid-19-17f74061-9a73-4546-adbf-fea2f62b2876-20230927154002.csv

**Comment by oslynn** [comment]
Done.
