### ISSUE TITLE
WA Electronic Laboratory Reporting: Discontinue reporting negative COVID-19 results

### ISSUE THREAD

**Issue by OHoward2023** [CDCgov/prime-reportstream#11637]
## Problem statement

Please filter out any non-positive COVID-19 results including negative and inconclusive results from WA COVID-19 ELR feeds. [Provisional Reporting COVID-19.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem9GQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4b73eddcf10d25ad051f722eec46e21f638b2e4/Provisional%20Reporting%20COVID-19.pdf)

## What you need to know

Hello,

Effective June 1, 2023, COVID-19 tests with results of negative or inconclusive are no longer reportable per the COVID-19 Provisional Letter (attached and published to the WA DOH website at Provisional Reporting COVID-19 (wa.gov)). Per WAC 246-101-201 positive test results for any COVID-19 test performed by a laboratory remain reportable.

Please begin excluding negative and inconclusive COVID-19 test results from your ELR feed as soon as possible to align with current reporting requirements.

Please contact [ELRProductionTeam@doh.wa.gov%20]ELRProductionTeam@doh.wa.gov with any questions or concerns about making this adjustment to your ELR feed.

Thank you,

Amanda Higgins, MSHI, MLS(ASCP)

## To do

Please begin excluding negative and inconclusive COVID-19 test results from the ELR feed as soon as possible to align with current WA DOH reporting requirements.

**Comment by GilmoreA6** [comment]
completed. Added matches(abnormal_flag, A) to WA REST receiver)
