### ISSUE TITLE
Update HL7v2 to FHIR to HL7v2 DataType Mappings: HD (NON PRIMITIVES)

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#11656]
### User Story

As a ReportStream engineer,
I want to update the ReportStream HL7v2 -> FHIR and FHIR -> HL7v2 mappings for the `HD` HL7v2 data type per the mapping inventory
so that I can ensure data does not get dropped during translation and enable the creation of mappings of ORU-R01 segments that reference this HL7v2 DataType.

### Description/Use Case

Given the ORU-R01 context, this HL7v2 DataType can map to the following resources (the sub list shows where exactly in what mapping file the DataType mapping appears in):

  - [ ] Identifier
      - [ ] HL7 Data Type - FHIR R4_ PL[Location] - Sheet1-PL.1
      - [ ] HL7 Data Type - FHIR R4_ PL[Location] - Sheet1-PL.2
      - [ ] HL7 Data Type - FHIR R4_ PL[Location] - Sheet1-PL.3
      - [ ] HL7 Data Type - FHIR R4_ PL[Location] - Sheet1-PL.4
      - [ ] HL7 Data Type - FHIR R4_ PL[Location] - Sheet1-PL.7
      - [ ] HL7 Data Type - FHIR R4_ PL[Location] - Sheet1-PL.8
      - [ ] HL7 Data Type - FHIR R4_ NDL[PractitionerRole] - Sheet1-NDL.7
  - [x] Reference(Organization)
      - [ ] PID[Patient]-PID-34
      - [ ] MSH[MessageHeader]-MSH-4
      - [ ] MSH[MessageHeader]-MSH-6
      - [ ] PID[Provenance-Patient]-PID-34
      - [ ] MSH[Provenance-Source]-MSH-4
      - [ ] HL7 Data Type - FHIR R4_ XCN[Practitioner] - Sheet1-XCN.9
      - [ ] HL7 Data Type - FHIR R4_ CX[Identifier] - Sheet1-CX.4
      - [ ] HL7 Data Type - FHIR R4_ XCN[PractitionerRole] - Sheet1-XCN.9
      - [ ] HL7 Data Type - FHIR R4_ XCN[Patient] - Sheet1-XCN.9
  - [x] Reference(Location)
      - [ ] HL7 Data Type - FHIR R4_ XCN[Practitioner] - Sheet1-XCN.14
      - [ ] HL7 Data Type - FHIR R4_ CX[Identifier] - Sheet1-CX.6
      - [ ] HL7 Data Type - FHIR R4_ XCN[RelatedPerson] - Sheet1-XCN.14
      - [ ] HL7 Data Type - FHIR R4_ XCN[PractitionerRole] - Sheet1-XCN.14
      - [ ] HL7 Data Type - FHIR R4_ XON[Location] - Sheet1-XON.8
      - [ ] HL7 Data Type - FHIR R4_ XON[Organization] - Sheet1-XON.8
      - [ ] HL7 Data Type - FHIR R4_ XCN[Patient] - Sheet1-XCN.14
  - [ ] Reference(Device)
      - [ ] MSH[MessageHeader]-MSH-5
      - [ ] MSH[Provenance-Source]-MSH-3

### Testing
The unit tests for the mappings of this DataType DO NOT have to cover every since segment a particular HL7v2->FHIR / FHIR->HL7v2 mapping appears in. It is sufficient to pick a representative segment and base the DataType mapping tests off of it. The unit tests should verify a segment containing a particular mapping maps correctly to HL7v2->FHIR and FHIR->HL7v2, having a test case for each condition or logic outlined in the mapping inventory for a particular mapping.

### Acceptance Criteria

- [ ] Mappings outlined in the Description of ticket have been created/updated per the mapping inventory
- [ ] Unit Tests created per testing strategy
- [ ] Any new RS extensions have FHIR examples documented

**Comment by mkalish** [comment]
Moving this to QA review as 
- the work is completed for Location and Organization 
- the spots for NDL and PL will get inlined
- there is no actual mapping for HD[Device] looks to be an error in the inventory; the HD fields in MSH will get captured when that segment is worked on
