### ISSUE TITLE
Add user roles to web receiver

### ISSUE THREAD

**Issue by mry-usds** [CDCgov/prime-reportstream#1165]
At a minimum provide users with an admin role, org admin role and a general user role
- Admins can switch orgs
- org admin can CUD organization users
- general user can R organization

For now, these will be manifested as a claim within OKTA

**Comment by MauriceReeves-usds** [comment]
@mry-usds @Bisonburger @drew-usds @Adrian-Brewster 

Thinking short term about this, we don't have a good sense of what the permissions model should look like on the web receiver side. My short-term vision is that there's basically four broad types of users, and they largely have similar permissions:
- STLTs are read/write in their jurisdiction. I haven't heard anyone say that they would ever need to grant a read-only user access to their data, though it's certainly possible.
- Senders are read/write for their data.
- ReportStream Support and Engineers have read/write across all jurisdictions. Again, I don't know that we'd necessarily need to grant read-only for any reason in this group
- CDC users would generally have read access to aggregated information across many jurisdictions and likely some ability to drill down into individual for non-PII/non-PHI information

I think it would be really good for us to set up a meeting soon to discuss internally, but also with a few states to get a sense of how they view permissions working, and how they would want to grant access. @Adrian-Brewster I need to rely on you and your experience as well. What did user permissions look like in APHL?

Is there a case where we'd need to draw a line for permissions and user roles between those able to view PII and those not able to view PII at the sender/STLT level or at the support level?

**Comment by jlusds** [comment]
yeah, i think we can start with admin + general user to start. 

i also like what adrian said in chat, which is we should always have minimum 2 users

**Comment by Adrian-Brewster** [comment]
Copying my comments over here. Sorry y'all, im still getting used to ZenHub...

In the past, I would typically identify two people at each DOH and give them access to smartsheets, the dashboard, ect. That way there was some level of accountability but jurisdictions were not in a bad situation if someone was out for a week on vacation.  Im not sure if taking a similar approach with this would make sense.

If we got with Admin + General User, then the admin can control who they give user rights to within the DOH.  That way if someone leaves the DOH, they can reassign the credentials to another team member. This seems like a safe approach for the Senders, too. 

Mo, I agree with the 4 categories you mentioned above.

**Comment by MauriceReeves-usds** [comment]
@kevinhaube @ahay-agile6 can you take a look and see if we still need this case please?

**Comment by kevinhaube** [comment]
@ahay-agile6 @MauriceReeves-usds I've added "DHPrimeAdmins" enumerator in the PR above. Once that's in, we should be good to start evaluating it as a claim throughout the React front-end. 

I'm going to go ahead and breakout the "Admins can switch organizations" into its own ticket for tracking purposes; did we want to do the same for "Org admin CUD org users", and does that feature have any mocks yet?
