### ISSUE TITLE
Update HL7v2 to FHIR to HL7v2 DataType Mappings: CWE (NON PRIMITIVES)

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#11658]
### User Story

As a ReportStream engineer,
I want to update the ReportStream HL7v2 -> FHIR and FHIR -> HL7v2 mappings for the `CWE` HL7v2 data type per the mapping inventory
so that I can ensure data does not get dropped during translation and enable the creation of mappings of ORU-R01 segments that reference this HL7v2 DataType.

### Description/Use Case

Given the ORU-R01 context, this HL7v2 DataType can map to the following resources (the sub list shows where exactly in what mapping file the DataType mapping appears in):

  - [x] CodeableConcept
      - [x] OBR[ServiceRequest]-OBR-4
      - [x] OBR[ServiceRequest]-OBR-13
      - [x] OBR[ServiceRequest]-OBR-31
      - [x] OBR[ServiceRequest]-OBR-46
      - [x] OBR[ServiceRequest]-OBR-47
      - [x] SPM[Specimen]-SPM-4
      - [x] SPM[Specimen]-SPM-6
      - [ ] SPM[Specimen]-SPM-7
      - [x] SPM[Specimen]-SPM-8
      - [x] SPM[Specimen]-SPM-9
      - [x] SPM[Specimen]-SPM-21
      - [x] SPM[Specimen]-SPM-24
      - [x] SPM[Specimen]-SPM-27
      - [x] NTE[ServiceRequest]-NTE-4
      - [x] OBX[Observation-Component]-OBX-3
      - [ ] OBX[Observation-Component]-OBX-8
      - [X] OBX[Observation-Component]-OBX-10
      - [x] OBX[Observation-Component]-OBX-17
      - [x] OBX[Observation-Component]-OBX-20
      - [ ] NK1[Patient]-NK1-3
      - [x] NK1[Patient]-NK1-7
      - [x] OBR[DiagnosticReport]-OBR-4
      - [x] PD1[Patient]-PD1-5
      - [x] PD1[Patient]-PD1-6
      - [x] PD1[Patient]-PD1-7
      - [x] ORC[ServiceRequest]-ORC-16
      - [x] ORC[ServiceRequest]-ORC-25
      - [ ] ORC[ServiceRequest]-ORC-29
      - [x] ORC[ServiceRequest]-ORC-31
      - [x] PV1[Patient]-PV1-16
      - [x] PID[Patient]-PID-15
      - [ ] PID[Patient]-PID-16
      - [ ] PID[Patient]-PID-17
      - [x] PID[Patient]-PID-26
      - [x] PID[Patient]-PID-27
      - [x] PID[Patient]-PID-28
      - [x] PID[Patient]-PID-35
      - [x] PID[Patient]-PID-36
      - [x] PID[Patient]-PID-39
      - [x] PV2[Encounter]-PV2-3
      - [x] PV2[Encounter]-PV2-7
      - [x] PV2[Encounter]-PV2-21
      - [ ] PV2[Encounter]-PV2-25
      - [x] PV2[Encounter]-PV2-40
      - [x] ORC[DiagnosticReport]-ORC-16
      - [ ] PRT[PractitionerRole]-PRT-4
      - [x] PRT[PractitionerRole]-PRT-6
      - [ ] PRT[PractitionerRole]-PRT-7
      - [x] PRT[PractitionerRole]-PRT-23
      - [ ] PRT[RelatedPerson]-PRT-4
      - [x] PRT[RelatedPerson]-PRT-6
      - [ ] PRT[RelatedPerson]-PRT-7
      - [x] PRT[RelatedPerson]-PRT-13
      - [ ] PRT[RelatedPerson]-PRT-23
      - [x] OBX[Observation]-OBX-3
      - [ ] OBX[Observation]-OBX-8
      - [x] OBX[Observation]-OBX-17
      - [x] OBX[Observation]-OBX-20
      - [x] PV1[Encounter]-PV1-4
      - [ ] PV1[Encounter]-PV1-10
      - [x] PV1[Encounter]-PV1-13
      - [x] PV1[Encounter]-PV1-14
      - [ ] PV1[Encounter]-PV1-16
      - [x] PV1[Encounter]-PV1-36
      - [x] PV1[Encounter]-PV1-38
      - [ ] NK1[RelatedPerson]-NK1-3
      - [ ] NK1[RelatedPerson]-NK1-7
      - [ ] NK1[RelatedPerson]-NK1-20
      - [x] HL7 Data Type - FHIR R4_ PLN[Identifier] - Sheet1-PLN.2
      - [ ] HL7 Data Type - FHIR R4_ RPT[Timing] - Sheet1-RPT.1
  - [ ] Quantity
      - [ ] OBX[Observation-Component]-OBX-6
      - [ ] OBX[Observation]-OBX-6
  - [ ] SimpleQuantity
      - [ ] OBX[Observation-Component]-OBX-6
      - [ ] OBX[Observation]-OBX-6
  - [ ] Coding
      - [ ] PV2[Encounter]-PV2-38
      - [ ] PV1[Encounter]-PV1-2
      - [ ] HL7 Data Type - FHIR R4_ XON[Location] - Sheet1-XON.2
      - [ ] HL7 Data Type - FHIR R4_ XON[Organization] - Sheet1-XON.2 
  - [x] Annotation
      - [ ] OBR[Specimen]-OBR-39
  - [x] Reference(Location)
      - [x] HL7 Data Type - FHIR R4_ DLD[Location] - Sheet1-DLD.1
  

### Testing
The unit tests for the mappings of this DataType DO NOT have to cover every since segment a particular HL7v2->FHIR / FHIR->HL7v2 mapping appears in. It is sufficient to pick a representative segment and base the DataType mapping tests off of it. The unit tests should verify a segment containing a particular mapping maps correctly to HL7v2->FHIR and FHIR->HL7v2, having a test case for each condition or logic outlined in the mapping inventory for a particular mapping.

### Acceptance Criteria

- [ ] Mappings outlined in the Description of ticket have been created/updated per the mapping inventory
- [ ] Unit Tests created per testing strategy
- [ ] Any new RS extensions have FHIR examples documented

**Comment by brick-green** [comment]
@JessicaWNava CWE[Annotation] and CWE[Quantity] seem to be relative low complexity if you want to take one of those on?
