### ISSUE TITLE
Create RS FHIR Extension Glossary

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#11657]
### User Story

As a FHIR sender to ReportStream,
I want to understand ReportStream's custom FHIR extension and their purpose,
so that I can ensure data is not lost when my FHIR message is transferred to HL7v2 for a particular receiver

### Description/Use Case

As we go through the mapping inventory, we sometimes have to create custom RS extensions to save data that appears in HL7v2 to FHIR because the mappings do not specify how to move that data over to FHIR. We need to have a document that explains all our extensions with examples on how to use them in a FHIR bundle.

### Dev Notes

- Could be documented in the ExtensionURLMapping

### Acceptance Criteria

- [ ] Documentation, with examples, exists for all RS FHIR extensions

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11657?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11657?planning-poker) with Zenhub @brick-green
