### ISSUE TITLE
Update HL7v2 to FHIR to HL7v2 DataType Mappings: XTN

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#11666]
### User Story

As a ReportStream engineer,
I want to update the ReportStream HL7v2 -> FHIR and FHIR -> HL7v2 mappings for the `XTN` HL7v2 data type per the mapping inventory
so that I can ensure data does not get dropped during translation and enable the creation of mappings of ORU-R01 segments that reference this HL7v2 DataType.

### Description/Use Case

Given the ORU-R01 context, this HL7v2 DataType can map to the following resources (the sub list shows where exactly in what mapping file the DataType mapping appears in):

  - [x] ContactPoint
      - [x] OBR[ServiceRequest]-OBR-17
      - [x] NK1[Patient]-NK1-5
      - [x] NK1[Patient]-NK1-6 (this use case wants to hardcode a value in ContactPoint, so the mapping should allow for this)
      - [x] NK1[Patient]-NK1-31
      - [x] NK1[Patient]-NK1-40
      - [x] NK1[Patient]-NK1-41
      - [x] ORC[ServiceRequest]-ORC-23
      - [x] PID[Patient]-PID-13 (pay special attention to fhir->hl7 mapping here since "use" is part of the hl7->fhir mapping)
      - [x] PID[Patient]-PID-14 (pay special attention to fhir->hl7 mapping here since "use" is part of the hl7->fhir mapping)
      - [x] PID[Patient]-PID-40
      - [x] PRT[PractitionerRole]-PRT-15
      - [x] PRT[RelatedPerson]-PRT-15
      - [x] NK1[RelatedPerson]-NK1-5
      - [x] NK1[RelatedPerson]-NK1-6
      - [x] NK1[RelatedPerson]-NK1-31
      - [x] NK1[RelatedPerson]-NK1-40
      - [x] NK1[RelatedPerson]-NK1-41
  - [x] code
      - [x] NK1[Patient]-NK1-6

### Testing
The unit tests for the mappings of this DataType DO NOT have to cover every since segment a particular HL7v2->FHIR / FHIR->HL7v2 mapping appears in. It is sufficient to pick a representative segment and base the DataType mapping tests off of it. The unit tests should verify a segment containing a particular mapping maps correctly to HL7v2->FHIR and FHIR->HL7v2, having a test case for each condition or logic outlined in the mapping inventory for a particular mapping.

### Acceptance Criteria

- [ ] Mappings outlined in the Description of ticket have been created/updated per the mapping inventory
    - [ ] Double checked inventory with NIST spec and created custom extensions to support NIST spec when needed
    - [ ] Extra logic not specifically outlined by inventory is NOT implemented (this includes validating that the given fields make sense in a given context)
- [ ] Unit Tests created per testing strategy
- [ ] Any new RS extensions have FHIR examples documented

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11666?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @jalbinson @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
@arnejduranovic to update the ticket based on team's discussion during the planning call
