### ISSUE TITLE
Create a playbook for updating the LIVD table

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#1166]
**Is your feature request related to a problem? Please describe.**
Create a playbook markdown file that outlines how to update the LIVD table

**Background**
LVID table tracks new devices as well as changes in the status of a device as it goes from EUA to regular authorization. While new devices are easy to handle, changes in the status of a device can lead to change in the information in the M or O column of a device. Since senders could be using an old device-id value, the change of this table could lead to a broken feed. 

**Describe the solution you'd like**
- Where to get the LIVD table
- Conversion process
- Checks that are needed
- Testing of the popular (in use) devices

**Comment by Adrian-Brewster** [comment]
Waiting for review. Change request to PR submitted.

**Comment by Adrian-Brewster** [comment]
@RickHawesUSDS to review.

**Comment by anshulkumar-usds** [comment]
@jorg3lopez please update based on current progress

**Comment by Adrian-Brewster** [comment]
@jorg3lopez to work on today.
