### ISSUE TITLE
Update HL7v2 to FHIR to HL7v2 DataType Mappings: DTM / DT / TS

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#11664]
### User Story

As a ReportStream engineer,
I want to update the ReportStream HL7v2 -> FHIR and FHIR -> HL7v2 mappings for the `DTM` and `DT` HL7v2 data types per the mapping inventory
so that I can ensure data does not get dropped during translation and enable the creation of mappings of ORU-R01 segments that reference these HL7v2 DataTypes.

### Description/Use Case

Given the ORU-R01 context, this HL7v2 DataType can map to the following resources (the sub list shows where exactly in what mapping file the DataType mapping appears in):

- [ ] DTM
    - [ ] dateTime
        - [ ] SPM[Specimen]-SPM-18
        - [ ] NTE[ServiceRequest]-NTE-6
        - [ ] OBX[Observation-Component]-OBX-14
        - [ ] OBX[Observation-Component]-OBX-19
        - [ ] OBR[DiagnosticReport]-OBR-7
        - [ ] OBR[DiagnosticReport]-OBR-8
        - [ ] PRT[Device]-PRT-17
        - [ ] PRT[Device]-PRT-18
        - [ ] ORC[ServiceRequest]-ORC-9
        - [ ] ORC[ServiceRequest]-ORC-15
        - [ ] PID[Patient]-PID-7
        - [ ] PID[Patient]-PID-29
        - [ ] PID[Provenance-Patient]-PID-33
        - [ ] PV2[Encounter]-PV2-8
        - [ ] PV2[Encounter]-PV2-9
        - [ ] OBR[Specimen]-OBR-7
        - [ ] OBR[Specimen]-OBR-8
        - [ ] PRT[PractitionerRole]-PRT-11
        - [ ] PRT[PractitionerRole]-PRT-12
        - [ ] PRT[RelatedPerson]-PRT-11
        - [ ] PRT[RelatedPerson]-PRT-12
        - [ ] OBX[Observation]-OBX-14
        - [ ] OBX[Observation]-OBX-19
        - [ ] PV1[Encounter]-PV1-44
        - [ ] PV1[Encounter]-PV1-45
        - [ ] SFT[MessageHeader]-SFT-6
        - [ ] HL7 Data Type - FHIR R4_ DR[DateTime] - Sheet1-DR.1
        - [ ] HL7 Data Type - FHIR R4_ DR[Period] - Sheet1-DR.1
        - [ ] HL7 Data Type - FHIR R4_ DR[Period] - Sheet1-DR.2
        - [ ] HL7 Data Type - FHIR R4_ XCN[Practitioner] - Sheet1-XCN.19
        - [ ] HL7 Data Type - FHIR R4_ XCN[Practitioner] - Sheet1-XCN.20
        - [ ] HL7 Data Type - FHIR R4_ XTN[ContactPoint] - Sheet1-XTN.13
        - [ ] HL7 Data Type - FHIR R4_ XTN[ContactPoint] - Sheet1-XTN.14
        - [ ] HL7 Data Type - FHIR R4_ NDL[PractitionerRole] - Sheet1-NDL.2
        - [ ] HL7 Data Type - FHIR R4_ NDL[PractitionerRole] - Sheet1-NDL.3
        - [ ] HL7 Data Type - FHIR R4_ XCN[RelatedPerson] - Sheet1-XCN.19
        - [ ] HL7 Data Type - FHIR R4_ XCN[RelatedPerson] - Sheet1-XCN.20
        - [ ] HL7 Data Type - FHIR R4_ XAD[Address] - Sheet1-XAD.13
        - [ ] HL7 Data Type - FHIR R4_ XAD[Address] - Sheet1-XAD.14
        - [ ] HL7 Data Type - FHIR R4_ TS[DateTime] - Sheet1-TS.1
        - [ ] HL7 Data Type - FHIR R4_ XPN[HumanName] - Sheet1-XPN.12
        - [ ] HL7 Data Type - FHIR R4_ XPN[HumanName] - Sheet1-XPN.13
        - [ ] HL7 Data Type - FHIR R4_ XCN[PractitionerRole] - Sheet1-XCN.19
        - [ ] HL7 Data Type - FHIR R4_ XCN[PractitionerRole] - Sheet1-XCN.20
        - [ ] HL7 Data Type - FHIR R4_ XCN[Patient] - Sheet1-XCN.19
        - [ ] HL7 Data Type - FHIR R4_ XCN[Patient] - Sheet1-XCN.20
    - [ ] instant
        - [x] OBR[DiagnosticReport]-OBR-22
        - [ ] PID[Patient]-PID-33
        - [ ] MSH[Bundle]-MSH-7
    - [ ] date
        - [x] PID[Patient]-PID-7
        - [ ] NK1[RelatedPerson]-NK1-16
    - [ ] uri
        - [x] PID[Patient]-PID-7
    - [ ] code
        - [x] PV1[Encounter]-PV1-45

- [ ] DT
    - [ ] dateTime
        - [ ] NK1[Patient]-NK1-8
        - [ ] NK1[Patient]-NK1-9
        - [ ] NK1[RelatedPerson]-NK1-8
        - [ ] NK1[RelatedPerson]-NK1-9
        - [ ] HL7 Data Type - FHIR R4_ PLN[Identifier] - Sheet1-PLN.4
        - [ ] HL7 Data Type - FHIR R4_ CX[Identifier] - Sheet1-CX.7
        - [ ] HL7 Data Type - FHIR R4_ CX[Identifier] - Sheet1-CX.8
        - [ ] HL7 Data Type - FHIR R4_ DLN[Identifier] - Sheet1-DLN.3

- [ ] TS
    - [ ] dateTime
        - [ ] OBR[ServiceRequest]-OBR-6
        - [ ] OBR[Specimen]-OBR-14
        - [ ] HL7 Data Type - FHRI R4_ TQ[MedicationRequest] - Sheet1-TQ.4
        - [ ] HL7 Data Type - FHRI R4_ TQ[MedicationRequest] - Sheet1-TQ.5
        - [ ] HL7 Data Type - FHIR R4_ TQ[ServiceRequest] - Sheet1-TQ.4
        - [ ] HL7 Data Type - FHIR R4_ TQ[ServiceRequest] - Sheet1-TQ.5
        - [ ] HL7 Data Type - FHIR R4_ TQ[Task-ExecutionPeriod] - Sheet1-TQ.4
        - [ ] HL7 Data Type - FHIR R4_ TQ[Task-ExecutionPeriod] - Sheet1-TQ.5
    - [ ] instant
        - [ ] HL7 Data Type - FHIR R4_ TQ[Appointment] - Sheet1-TQ.4
        - [ ] HL7 Data Type - FHIR R4_ TQ[Appointment] - Sheet1-TQ.5

### Testing
The unit tests for the mappings of this DataType DO NOT have to cover every since segment a particular HL7v2->FHIR / FHIR->HL7v2 mapping appears in. It is sufficient to pick a representative segment and base the DataType mapping tests off of it. The unit tests should verify a segment containing a particular mapping maps correctly to HL7v2->FHIR and FHIR->HL7v2, having a test case for each condition or logic outlined in the mapping inventory for a particular mapping.

### Acceptance Criteria

- [ ] Mappings outlined in the Description of ticket have been created/updated per the mapping inventory
- [ ] Unit Tests created per testing strategy
- [ ] Any new RS extensions have FHIR examples documented

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11664?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @jalbinson @jimmyfagan @mkalish @thetaurean
