### ISSUE TITLE
Update HL7v2 to FHIR to HL7v2 DataType Mappings: CX / PLN

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#11669]
### User Story

As a ReportStream engineer,
I want to update the ReportStream HL7v2 -> FHIR and FHIR -> HL7v2 mappings for the `CX` and `PLN` HL7v2 data types per the mapping inventory
so that I can ensure data does not get dropped during translation and enable the creation of mappings of ORU-R01 segments that reference these HL7v2 DataTypes.

### Description/Use Case

Given the ORU-R01 context, this HL7v2 DataType can map to the following resources (the sub list shows where exactly in what mapping file the DataType mapping appears in):

- [x] CX
    - [x] Identifier
        - [x] OBR[ServiceRequest]-OBR-53
        - [x] SPM[Specimen]-SPM-30
        - [x] SPM[Specimen]-SPM-31
        - [x] ORC[ServiceRequest]-ORC-33
        - [x] PID[Patient]-PID-2
        - [x] PID[Patient]-PID-3
        - [x] PID[Patient]-PID-4
        - [x] PV1[Encounter]-PV1-5
        - [x] PV1[Encounter]-PV1-19
        - [x] PV1[Encounter]-PV1-50
        - [x] PV1[Encounter]-PV1-54
        - [x] NK1[RelatedPerson]-NK1-12
        - [x] NK1[RelatedPerson]-NK1-33
    - [x] code
        - [x] OBR[ServiceRequest]-OBR-53
        - [x] ORC[ServiceRequest]-ORC-33
        - [x] PV1[Encounter]-PV1-19
    - [x] uri
        - [x] OBR[ServiceRequest]-OBR-53
        - [ ] ORC[ServiceRequest]-ORC-33
        - [x] PV1[Encounter]-PV1-19
    - [x] string
        - [x] PV1[Encounter]-PV1-19

- [ ] PLN
    - [ ] Identifier
        - [x] PRT[PractitionerRole]-PRT-24
        - [x] PRT[RelatedPerson]-PRT-24

### Testing
The unit tests for the mappings of this DataType DO NOT have to cover every since segment a particular HL7v2->FHIR / FHIR->HL7v2 mapping appears in. It is sufficient to pick a representative segment and base the DataType mapping tests off of it. The unit tests should verify a segment containing a particular mapping maps correctly to HL7v2->FHIR and FHIR->HL7v2, having a test case for each condition or logic outlined in the mapping inventory for a particular mapping.

### Acceptance Criteria

- [ ] Mappings outlined in the Description of ticket have been created/updated per the mapping inventory
- [ ] Unit Tests created per testing strategy
- [ ] Any new RS extensions have FHIR examples documented

**Comment by JessicaWNava** [comment]
PRT[PractitionerRole]-PRT-24 Does not exist in Caristix or in NIST or inside of PRT inside of the library, so we will be skipping this one for now.

**Comment by JessicaWNava** [comment]
We are not mapping CTD, there are no mappings to FHIR, so we are also going to be skipping this.
