### ISSUE TITLE
Improve documentation around installation 

### ISSUE THREAD

**Issue by cbroome** [CDCgov/prime-reportstream#1169]
Running through the current steps weren't enough to get my instance of the prime-router working properly. There are a few simple steps that should be included in the existing README that would help new users stand up the project.

**Comment by MauriceReeves-usds** [comment]
Since you both went through the installation process most recently, it would be good to update the documentation based on any issues you encountered.

**Comment by jlusds** [comment]
What's the status of this?

**Comment by cbroome** [comment]
Ah merged, I'll close it out.

**Comment by jorg3lopez** [comment]
> What's the status of this?

This one is done, it got merged already.
