### ISSUE TITLE
Website Redesign - Receiving Data

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#11724]
As a User,
I want to visit the ReportStream Receiving Data Page,

### Designs
- [Link to Figma](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=3985-4176&mode=design&t=XD7BpVzoWon43Mss-0)

### Analytics
- Page Load
- Button / Link clicks

### Verification Steps
- Code Review
- Trial / Dev environment signoff by Product / Design
- Staging environment signoff by Product / Design / Stakeholders 
- Production environment signoff by Engineering, Product and Design

### Acceptance Criteria
- [ ] Analytics / Metrics Required 
- [ ] Storybook update required
- [ ] Unit Tests
- [ ] Manual Testing Steps
- [x] Change to the Getting Started page (see additional details section) 
- [x] How to Download Your Data (/resources/data-download-guide) is archived
- [x] Remove the link to "Download your Data" from the Managing Your Connection page (at top)
- [x] Archive [Guide to receiving ReportStream data](https://reportstream.cdc.gov/resources/getting-started-public-health-departments)

Dependencies:
- None

Additional Details:
- The deployment strategy will follow the general deployment strategy for the Website Redesign EPIC. We will deliver this page in isolation from the other pages.
- 

On [Getting started](https://reportstream.cdc.gov/getting-started):

- [x] "Get started as a public health agency" now links to new receiving data page
- [x] Under Get started as a public health agency, the entire card body text will now be: 

> You need accurate, timely public health data. Learn how ReportStream works with you throughout onboarding and beyond to ensure you’re getting the data you need in the format you need. All through a single connection.

- [x] Under Get started as a healthcare organization, the entire card body text will now be:

> We know it can be difficult to balance compliance, your capacity, and the frequently changing requirements and regulations. Learn more about how our team sets up your simple, effective data transfer.

**Comment by chris-kuryak** [comment]
@audreykwr Please double check the ACs and fill in anything missing

**Comment by penny-lischer** [comment]
@audreykwr @jillian-hammer did we want the Getting started nav to have a dropdown to the child pages?

**Comment by penny-lischer** [comment]
@audreykwr should the "Download your Data" from the side nav be removed as well?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODlGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7251c7c0d64bb7657c2c9c6ca6f8ff570571c555/Screenshot%202023-10-17%20at%2010.41.45%20AM.png)

**Comment by audreykwr** [comment]
- No drop down for getting started. About is the only nav drop down.
- Yes remove how to download your data from everywhere. the page should be archived
- Chris referenced vaguely (my fault for not clarifying yet!!) in the AC a change to Getting started. I just added the details of that in the ticket description
- I also added another archive that this will need to trigger
