### ISSUE TITLE
Dependabot Onslaught

### ISSUE THREAD

**Issue by etanb** [CDCgov/prime-reportstream#11725]
We have fallen behind on updating our dependabot. I'll get us up to date (which is why i'm making a ticket, it's going to take a while), but we need to be on top of it! Whoever is on-call should be handling the latest.

**Comment by chris-kuryak** [comment]
Changed to 3 points per Etan's review.

**Comment by etanb** [comment]
We're going to have to fix all of our Jest tests that we've been avoiding.
