### ISSUE TITLE
Test Sully HL7 sample data with HL7 ingest

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#1173]
We have received a new sample data from Sully and we need to run it through the HL7 ingest process to see if we find any issues with the ingester. 

[Sully HL7 file](https://app.zenhub.com/files/304423150/b2d0db81-58e1-4760-a101-54023b98d6fb/download)

Acceptance criteria:
1. Add the HL7 data to the Observation Message Tests and verify the expected values for the data.

**Comment by MauriceReeves-usds** [comment]
@jorg3lopez this was on Cameron to complete but he has rolled off. I'm giving to you to complete. There's already a PR for it, so you just need to checkout the branch and verify that this works. The PR is here: https://github.com/CDCgov/prime-reportstream/pull/1920
