### ISSUE TITLE
Route test HIV message to California through UP

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#11748]
## Problem statement

CDPH is ready to receive an HIV test message from ReportStream.

## What you need to know

- CDPH asked for it to be sent to the staging/testing stream that is connected to the UP
- The test file has already been created and routed successfully through RS but was never sent to California
- The test file was created by SimpleReport and has already been sent to us in the past, so we may already have it

## Acceptance criteria

- [x] Confirm which staging/testing endpoint CDPH would like to receive the test file. Contact Ellaison Carroll and Theodore Fries (CDPH) for confirmation if needed.
- [x] Route SR HIV Test file to the Staging/Test California endpoint
- [x] Alert Ellaison Carroll and Theodore Fries (CDPH) when the test file gets sent through successfully

## To do

- [ ] Obtain SR HIV Test file

**Comment by chris-kuryak** [comment]
Troubleshooting issues with CDPH

**Comment by LaFreda1** [comment]
Have we heard from CDPH? @victor-chaparro Do we have any next steps?

**Comment by victor-chaparro** [comment]
Maybe @chris-kuryak can give more info, but for now we've been sending manual messages generated by SimpleReport and they usually always contain some minor issues. So, we're going to wait until SR is fully ready to start sending us data from their system. Chris mentioned they will have this working in the next two sprints, so we can put this on ice until then.

**Comment by chris-kuryak** [comment]
Complete for now. Will create a follow-on ticket in the future
