### ISSUE TITLE
California (CDPH) and LA County HIV Pilot

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#11749]
## Problem statement

California Dept of Public Health (CDPH) is working with LA County to do HIV testing and route the results via ELR.
The plan is to route the results through SimpleReport and to CDPH (via ReportStream), which will then route only those that are intended for LA County to them.
ReportStream's goal is to help facilitate this process and route the HIV data from SimpleReport, through the UP, and to California successfully.

## What you need to know
- There are weekly syncs with SR, LA County, and CDPH
- ...

## To do

- [ ] ...

**Comment by MikaelahD13** [comment]
Closing, work completed.
