### ISSUE TITLE
Updates to dashboard description on managing your connection

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#11751]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

With the new dashboard live, we need to edit content on [Managing your connection](https://reportstream.cdc.gov/managing-your-connection) to reflect that instead of Daily Data.

- New content under "For public health agencies"
 The data dashboard shows what you’ve received and allows you to dive into detail for each facility or report.
 [View your dashboard] (and update that link to be the dashboard instead of daily data)

- New content on the card at the top, instead of "View Daily Data" make "View data dashboard" (and update that link to be the dashboard instead of daily data)

## Open questions

- When we might need a different solution due to it being a COVID-only dashboard and a few users still accessing Daily Data.

## Working links
-   

## Acceptance criteria
-   [x] Content updated on card at the top and in the monitoring tools section as described above
-   [x] Change the image that says "Daily Data" to the new image provided by design

**Comment by audreykwr** [comment]
@chris-kuryak FYI, a small site fix Penny helped flag

**Comment by chris-kuryak** [comment]
@jillian-hammer Is there a new card image for replacing the one that says "Daily Data"?

**Comment by jillian-hammer** [comment]
new image asset below: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDVoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7972dd7a67d028b5ad99340d78d155228d89098/20231023_DataDashboard.png)
