### ISSUE TITLE
DE - Filter out sample data from Prod feed

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#11759]
## **Problem Statement**

We received a follow-up email in the ReportStream inbox, from Christopher Decker at the DE Division of Public Health, requesting that we filter out any sample data from their PROD feed or provide them with advance notice that sample data will be sent.

## **What you need to know**

The email received:

> I just want to confirm. Moving forward- any test messages or samples that are being tested and sent to the state of Delaware, can you either route it to our test environment, or let us know that your going to be sending a test/sample message 24 hours prior to sending, as we do not want test data entering our production environments.
> 
> Please let us know as soon as possible to fix this.

## **Acceptance Criteria**

- Apply data filters to DE feed to redirect sample data to their Test environment, or set up notifications that will send them a message when sample data is being sent.

## **To Do**

- Apply data filter to DE feed
- (Alternative) Set up notification messages for sample data that is being sent to DE

## **Additional Comments**

This is a follow-up to #11653.

**Comment by sliu1000** [comment]
Per Ott this has been resolved.
