### ISSUE TITLE
Alaska UP Onboarding - Go Live Coordination

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#11763]
### Acceptance Criteria 
- [x] Confirmed with STLT when they want to start receiving (date) 
- [x] Removed quality filter in prod settings = allowNone() 
- [x] Removed quality filter in staging settings = allowNone() 
- [x] Set Customer status = active 

### To Do 
- [x] RS engineer: update this ticket with comments with every interaction with receiver 
- [x] RS team member who originates this ticket: add any dependencies, as needed 
- [x] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [x] Pipelines: Onboarding & Operations (New) 
     - [x] Labels: "Onboarding-ops" and "Receiver" and state label 
     - [x] Epics: [select the epic for this API onboarding sender]

**Comment by GilmoreA6** [comment]
AK went live on the UP 3/11/24 @ 11AM PDT (2PM EDT)
