### ISSUE TITLE
Define MVP Product Requirements for CSV Support in the UP

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#11769]
## Problem statement
Since we will be adding CSV support (via API) to the Universal Pipeline, we need to define product requirements for the MVP functionality.

## What you need to know

- This [Product Brief](https://docs.google.com/document/d/1Ai7KGuAJrk23jUeW5wKoefF5BpZecepJOrz6bbEljKE/edit) can be used as a template/reference
- Chris has started a [Product Brief for CSV Support in UP MVP](https://docs.google.com/document/d/1dfvSWQjPhAKHW2shQ2jn4VxAPrLpvNJ4duK27NY0gnU/edit)
- This [Product Requirements Spreadsheet](https://docs.google.com/spreadsheets/d/1UXicOKc9Mn639v6TluTFE-CyErydUz08PkVcXrvK2Tk/edit#gid=149930974) can be used as a template, if needed
- ...

## Acceptance criteria
- [ ] How CSV support currently works/exists in the COVID pipeline is documented in the Product Brief
- [ ] Existing User research, if any, regarding CSV support is documented is referenced/linked in the Product Brief
- [ ] [Product Brief](https://docs.google.com/document/d/1dfvSWQjPhAKHW2shQ2jn4VxAPrLpvNJ4duK27NY0gnU/edit) created and ready for review with Engineering/Design/Product teams
- [ ] Product Requirements Spreadsheet created (if necessary) and ready for review with Engineering/Design/Product teams
- [ ] Schedule meeting with tech leads, product leads, project leads, and the design lead from Engagement and Platform for review

## To do

- [ ] ...

**Comment by jakefishbein-navapbc** [comment]
Complete research, draft product brief, and brief analysis of sender conditions
