### ISSUE TITLE
Content for WA Case Study

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#11777]
## Problem statement

Washington State gave a presentation at the CDC Innovation Summit about WA Notify, the GAEN implementation they ran that SimpleReport and ReportStream submitted data to. At the presentation they said that our work prevented 50,000 new cases of COVID and likely saved ~ 200 - 900 lives.

We want to leverage this use case into effective marketing material for Reportstream.

## What you need to know

- [Slack Conversation](https://nava.slack.com/archives/C025JHV38BY/p1696257878898409)
- ...

## Acceptance criteria

- [x] Meet/interview Washington State representative
- [x] Determine how this can be leveraged into marketing material(s)

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
This may need to be updated/split depending on meeting with Mo tomorrow

**Comment by audreykwr** [comment]
Removed AC of creating the content. We are going to wait until WA gets us some more info being finalizing a timeline for creating something.
