### ISSUE TITLE
Update HL7v2 to FHIR to HL7v2 DataType Mappings: NM (PRIMITIVES)

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#11778]
### User Story

As a ReportStream engineer,
I want to update the ReportStream HL7v2 -> FHIR and FHIR -> HL7v2 mappings for the `NM` HL7v2 data types per the mapping inventory
so that I can ensure data does not get dropped during translation and enable the creation of mappings of ORU-R01 segments that reference this HL7v2 DataType.

### Description/Use Case

Given the ORU-R01 context, this HL7v2 DataType can map to the following resources (the sub list shows where exactly in what mapping file the DataType mapping appears in):

- [ ] NM
    - [ ] integer
        - [ ] PID[Patient]-PID-25
    - [ ] decimal
        - [ ] HL7 Data Type - FHIR R4_ CQ[Quantity] - Sheet1-CQ.1
        - [ ] HL7 Data Type - FHIR R4_ CQ[Decimal] - Sheet1-CQ.1
    - [ ] positiveInt
        - [ ] HL7 Data Type - FHIR R4_ XTN[ContactPoint] - Sheet1-XTN.18
    - [ ] unsignedInt
        - [ ] HL7 Data Type - FHIR R4_ CQ[UnsignedInt] - Sheet1-CQ.1
    - [ ] code
        - [ ] HL7 Data Type - FHIR R4_ XON[Location] - Sheet1-XON.5
        - [ ] HL7 Data Type - FHIR R4_ XON[Organization] - Sheet1-XON.5
    - [ ] string
        - [ ] HL7 Data Type - FHIR R4_ XON[Location] - Sheet1-XON.3
        - [ ] HL7 Data Type - FHIR R4_ XON[Location] - Sheet1-XON.4
        - [ ] HL7 Data Type - FHIR R4_ XON[Organization] - Sheet1-XON.4
    - [ ] identifier
        - [ ] HL7 Data Type - FHIR R4_ XON[Organization] - Sheet1-XON.3

### Testing
The unit tests for the mappings of this DataType DO NOT have to cover every since segment a particular HL7v2->FHIR / FHIR->HL7v2 mapping appears in. It is sufficient to pick a representative segment and base the DataType mapping tests off of it. The unit tests should verify a segment containing a particular mapping maps correctly to HL7v2->FHIR and FHIR->HL7v2, having a test case for each condition or logic outlined in the mapping inventory for a particular mapping.

### Acceptance Criteria

- [ ] Mappings outlined in the Description of ticket have been created/updated per the mapping inventory
- [ ] Unit Tests created per testing strategy
- [ ] Any new RS extensions have FHIR examples documented

**Comment by mkalish** [comment]
These primitives will need to be handled inline in the consuming schema.  Moving to QA review
