### ISSUE TITLE
DE - Receiving consistent Sample Data uploads in Prod environment

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#11779]
## **Problem Statement**

Christopher Decker reached out to the ReportStream inbox to inform us that they have been receiving consistent uploads of sample data messages in their Prod environment, despite previous requests to filter out that data.

## **What you need to know**

Email text follows:

> We keep receiving these:
> 
> Any lab USA^07D9497600^CLIA-CDC PRIME - Atlanta,^2.16.840.1.114222.4.1.237821^ISO
> 
> With a slightly different MSH each time, pretty regularly. A previous email from report stream identified these as sample messages- however these are coming through to production.
> 
> We received the one above this morning.

Follow-up message:

> Thank you, just wanted to confirm that the ones that came through this morning are test/samples?
> 
> Any lab USA^07D9497600^CLIA-CDC PRIME - Atlanta,^2.16.840.1.114222.4.1.237821^ISO

Ott responded to request the full MSH or a copy of the message:

> Would you please give the MSH-10 (Message ID) of the message?  Or, attach the message to email to me.  I am going to trace the message of find where is the message originated.
> Therefore, I can stop the test/sample message.  Sometime this type of message came from sender which configured their system to auto-send test/message and forget to turn it off.
> In that case, we can notify them to turn off their auto-feed.

Christopher provided this information:

> Here is the full MSH-
> 
> MSH|^~\&|CDC PRIME - Atlanta,^2.16.840.1.114222.4.1.237821^ISO|Any lab USA^07D9497600^CLIA|||20231012113000+0000||ORU^R01^ORU_R01|411900|P|2.5.1|||NE|NE|USA|UNICODE UTF-8|ENG^English^ISO||PHLabReport-NoAck^ELR_Receiver^2.16.840.1.113883.9.11^ISO
> 
> We keep getting these messages from ANY LAB USA, with a slightly different MSH each time. Based off a previous email about one of the messages being a sample message, I am wondering if these that keep coming through are also tests? We just need to ensure that fake data is not coming into our production environments.

## **Acceptance Criteria**

- Find and resolve the source of the sample data messages that DE is continuing to receive.

## **To Do**

- Determine the source of the sample data messages
- Shut off any automated sending of sample data, or contact the sender to notify them of these messages.

## **Additional Comments**

This is a follow-up to #11759.

**Comment by oslynn** [comment]
Christopher,

I am looking for this message in our log database and I can't find it.  Would you please let me me what is the date the message was sent?
If you can, would you also give me the whole message as well?  I will try to locate it and fix the feed to not allow such message go through.

Very respectfully
-Ott Sathngam
CDC ReportStream Engineer

**Comment by oslynn** [comment]
I requested the very message from DE and never got a response back.   Therefore, I am closing the ticket for now.
