### ISSUE TITLE
Develop Research Plan for new Receiver Dashboard

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#11776]
## User story

As a ReportStream designer/researcher after the launch of the new Receiver Dashboard, I want to develop a plan for gathering feedback from users.

## Open questions
- Does the new feature launch meet the need of our receivers to "see who is sending me data and how often?"
- What do users like and dislike about the new feature?
- (Internally) Is it important that we add this feature to the Universal Pipeline?

## Acceptance criteria
- [x] Research plan created and reviewed with design lead

**Comment by audreykwr** [comment]
[Plan](https://docs.google.com/document/d/1k49FFmlUCRWW2wlQdICrlRPRzdci5DUoVPGk7W64RaI/edit#heading=h.8avktwn4ql31) reviewed and a meeting is scheduled for handoff
