### ISSUE TITLE
[SPIKE] Okta Users that are in both a Sender and Receiver group cannot access the Submissions Page

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#11772]
## Describe the bug
User is added to both a Sender and Receiver group in Okta and cannot access the submissions page. This appears to be a front end issue.
When the user is added to DHPrimeAdmins, the Submissions page works.

## Impact on ReportStream
This issue is forcing Platform Team to make people Admins in RS that shouldn't be so we can continue our pilot work.

## Steps to reproduce
1. See reproduction/discussion here: https://nava.slack.com/archives/C025F5W5Q7L/p1697049827376859
2. Contact Arnej Duranovic with questions

## Expected behavior
When a user is added to both a Sender and Receiver group in Okta, they should be able to access both the Submissions and Daily Data (or Data Dashboard) pages.

## Resources
https://nava.slack.com/archives/C025F5W5Q7L/p1697049827376859

#### Desktop (please complete the following information)
 - OS: 
 - Browser 
 - Version 

#### Smartphone (please complete the following information)
 - Device:
 - OS: 
 - Browser 
 - Version 

## Acceptance Criteria
- [x] Plan developed for how to solve this issue: Requirement is that a user can be a sender and receiver (not a Prime Admin) and have access to authenticated pages for both groups (Submissions, Data Dashboard, File Validator, Public Key tool, etc)
- [x] Sync'd with Platform and Engagement PM and Tech Leads on solution
- [ ] Write ticket(s) for solution

**Comment by etanb** [comment]
@chris-kuryak I mentioned this in the [associated PR](https://github.com/CDCgov/prime-reportstream/pull/11975), but I talked extensively with @arnejduranovic about the concepts of our Senders and Receivers as well as what this ticket is about. The "power" we're looking for here is a very simple combination of the Sender and Receiver on the front end, just access to those pages. Therefore, adding a 3rd user type on the backend / Okta side is NOT worth it. 

Therefore, the solution is already implemented in this [associated PR](https://github.com/CDCgov/prime-reportstream/pull/11975), is to add a new key/value in the UserState called `isUserTransceiver` that's simply a `boolean` if both `isUserReceiver` and `isUserSender` are `true`.
