### ISSUE TITLE
Update HL7v2 to FHIR to HL7v2 DataType Mappings: CWE (PRIMITIVES)

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#11788]
### User Story

As a ReportStream engineer,
I want to update the ReportStream HL7v2 -> FHIR and FHIR -> HL7v2 mappings for the `CWE` HL7v2 data type per the mapping inventory
so that I can ensure data does not get dropped during translation and enable the creation of mappings of ORU-R01 segments that reference this HL7v2 DataType.

### Description/Use Case

Given the ORU-R01 context, this HL7v2 DataType can map to the following resources (the sub list shows where exactly in what mapping file the DataType mapping appears in):

  - [ ] identifier
      - [ ] OBX[Observation-Component]-OBX-15
      - [ ] OBX[Observation]-OBX-15
  - [ ] code
      - [ ] NK1[Patient]-NK1-15
      - [ ] PID[Patient]-PID-8
      - [ ] MSH[MessageHeader]-MSH-19
      - [ ] PV1[Encounter]-PV1-2
      - [ ] NK1[RelatedPerson]-NK1-15
      - [ ] HL7 Data Type - FHIR R4_ RPT[Timing] - Sheet1-RPT.6
       - [ ] HL7 Data Type - FHIR R4_ CQ[Code] - Sheet1-CQ.2
  - [ ] uri
      - [ ] PD1[Patient]-PD1-6
      - [ ] ORC[ServiceRequest]-ORC-16
      - [ ] PV1[Patient]-PV1-16
      - [ ] PID[Patient]-PID-17
      - [ ] PID[Patient]-PID-26
      - [ ] PID[Patient]-PID-28
      - [ ] PID[Patient]-PID-35
      - [ ] PID[Patient]-PID-36
      - [ ] PID[Patient]-PID-39
      - [ ] ORC[DiagnosticReport]-ORC-16
      - [ ] HL7 Data Type - FHIR R4_ DLN[Identifier] - Sheet1-DLN.2
      - [ ] HL7 Data Type - FHIR R4_ XAD[Address] - Sheet1-XAD.10
  - [ ] string
      - [ ] HL7 Data Type - FHIR R4_ CQ[Quantity] - Sheet1-CQ.2
      - [ ] HL7 Data Type - FHIR R4_ XAD[Address] - Sheet1-XAD.9
      - [ ] HL7 Data Type - FHIR R4_ XAD[Address] - Sheet1-XAD.10
  

### Testing
The unit tests for the mappings of this DataType DO NOT have to cover every since segment a particular HL7v2->FHIR / FHIR->HL7v2 mapping appears in. It is sufficient to pick a representative segment and base the DataType mapping tests off of it. The unit tests should verify a segment containing a particular mapping maps correctly to HL7v2->FHIR and FHIR->HL7v2, having a test case for each condition or logic outlined in the mapping inventory for a particular mapping.

### Acceptance Criteria

- [ ] Mappings outlined in the Description of ticket have been created/updated per the mapping inventory
- [ ] Unit Tests created per testing strategy
- [ ] Any new RS extensions have FHIR examples documented

**Comment by mkalish** [comment]
Based on our slack huddle yesterday, there won't be a specific work for mappings that go to a FHIR primitive and each one will be handled by the consuming mapping.

cc/ @arnejduranovic
