### ISSUE TITLE
MN - 2 Files to be resent

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#11786]
## **Problem Statement**
We received an email in the ReportStream inbox where the State Minnesota says they have not received the test results submitted via SimpleReport. The Facility Name is The Glenn Hopkins - Terraces.

## **What you need to know**
I was able to locate two records:
The SimpleReport record submitted on 9/10/2023 messageid is `800bca95-b4f5-401e-8c50-93100799c573` sent to MN-DOH on 9/11/2023 at 1:40 PM.
File Name: `covid-19-2dae3553-5cac-41a1-b498-33427a2e47e1-20230911134029.hl7`

The SimpleReport record submitted on 9/18/2023 messageid is `1a38b375-6698-4bc4-b68f-112f85052f35 `sent to MN on 9/20/2023 at 1:40 PM
File Name: `covid-19-88ea9f17-d939-4a77-b06b-cecda0a901ad-20230920134105.hl7`
Please let us know if you need any further assistance.

I'll post the email chain in the comments.

## **Acceptance Criteria**
Engineer Assigned
Engineer confirms that file was resent.
Let the customer know when sent.
Confirm receipt by customer/MN.

## **To Do**
A quick note to the assignee of the ticket.

## **Additional Comments**
We don't require the entire batch from 9/11 and 9/20 to be re-sent. Please only send message IDs `800bca95-b4f5-401e-8c50-93100799c573 `and `1a38b375-6698-4bc4-b68f-112f85052f35`, which constitute 2 records, to MDH.

**Comment by sliu1000** [comment]
Japa, Srujana (MDH) <Srujana.Japa@state.mn.us>
Report Stream (CDC);Julie Nichols <jnichols@greatlakesmc.com>
Blair, Benjamin (He/Him/His) (MDH) <Benjamin.Blair@state.mn.us>
Thank you, Sharon, for sharing this information. Upon our review, we couldn't find these messages in the batch files received on 9/11 and 9/20. Could you please re-trigger these messages to MDH and notify us once they are sent?

Srujana

Srujana Japa
ELR Onboarding Coordinator | MEDSS Operations Unit
Minnesota Department of Health


From: Report Stream (CDC) <reportstream@cdc.gov>
Sent: Friday, October 13, 2023 1:48 PM
To: Japa, Srujana (MDH) <Srujana.Japa@state.mn.us>; Julie Nichols <jnichols@greatlakesmc.com>
Cc: Blair, Benjamin (He/Him/His) (MDH) <Benjamin.Blair@state.mn.us>
Subject: Re: MDH : Missing COVID Labs Great Lakes MC

Hello,

 I was able to locate two records:

The SimpleReport record submitted on 9/10/2023 messageid is 800bca95-b4f5-401e-8c50-93100799c573 sent to MN-DOH on 9/11/2023 at 1:40 PM.
The SimpleReport record submitted on 9/18/2023 messageid is 1a38b375-6698-4bc4-b68f-112f85052f35 sent to MN on 9/20/2023 at 1:40 PM
Please let us know if you need any further assistance.

 Best regards,

From: Japa, Srujana (MDH) <Srujana.Japa@state.mn.us>
Sent: Friday, October 13, 2023 2:13 PM
To: Report Stream (CDC) <reportstream@cdc.gov>; Julie Nichols <jnichols@greatlakesmc.com>
Cc: Blair, Benjamin (He/Him/His) (MDH) <Benjamin.Blair@state.mn.us>
Subject: RE: MDH : Missing COVID Labs Great Lakes MC

 Adding @Julie Nichols <jnichols@greatlakesmc.com> from Great Lakes on this email thread.

Julie,

I am Srujana Japa from MDH, I'm connecting you with the Simple Reports staff to address the issue of missing COVID labs that should have been reported to MDH. To assist in the investigation, could you please provide the dates of submission, the CLIA number, or any facility details related to these labs on this thread?

Thank you,

Srujana Japa
ELR Onboarding Coordinator | MEDSS Operations Unit
Minnesota Department of Health

From: Report Stream (CDC) <reportstream@cdc.gov>
Sent: Friday, October 13, 2023 11:43 AM
To: Japa, Srujana (MDH) <Srujana.Japa@state.mn.us>
Cc: Blair, Benjamin (He/Him/His) (MDH) <Benjamin.Blair@state.mn.us>
Subject: Re: MDH : Missing COVID Labs Great Lakes MC

Hi Srujana,

Thank you for contacting ReportStream Support.

We are unable to find any facility information on Great Lakes MC. Please reach out to the contact for dates of submission, CLIA number, or facility details so that we can research further. Please also have them reach out to SimpleReport to confirm success result upload or manual entry.

If you have any further question or concerns please don't hesitate to reach out.

Thank you,

From: Japa, Srujana (MDH) <Srujana.Japa@state.mn.us>
Sent: Friday, October 13, 2023 10:07 AM
To: Report Stream (CDC) <reportstream@cdc.gov>
Cc: Blair, Benjamin (He/Him/His) (MDH) <Benjamin.Blair@state.mn.us>
Subject: MDH : Missing COVID Labs Great Lakes MC

 Good Morning Report Stream Team,

Could you please check your logs for COVID submissions from Great Lakes Management (Great Lakes MC), a senior living facility based in Minnesota, and verify if they have indeed submitted any data? As of now, we haven't received any data from them. Great Lakes MC claims that they have submitted data using simple reports.

Thank you,

Srujana Japa

ELR Onboarding Coordinator | MEDSS Operations Unit
Minnesota Department of Health
Office: 651-201-5967

Report Stream (CDC)
Japa, Srujana (MDH) <Srujana.Japa@state.mn.us>;Julie Nichols <jnichols@greatlakesmc.com>
Blair, Benjamin (He/Him/His) (MDH) <Benjamin.Blair@state.mn.us>
Hello,

Some content in this message has been blocked because the sender isn't in your Safe senders list. General
Japa, Srujana (MDH) <Srujana.Japa@state.mn.us>
Report Stream (CDC);Julie Nichols <jnichols@greatlakesmc.com>
Blair, Benjamin (He/Him/His) (MDH) <Benjamin.Blair@state.mn.us>
Adding @Julie Nichols <jnichols@greatlakesmc.com> from Great Lakes on this email thread.

Julie,

I am Srujana Japa from MDH, I'm connecting you with the Simple Reports staff to address the issue of missing COVID labs that should have been reported to MDH. To assist in the investigation, could you please provide the dates of submission, the CLIA number, or any facility details related to these labs on this thread?

Thank you,

Srujana Japa


From: Report Stream (CDC) <reportstream@cdc.gov>
Sent: Friday, October 13, 2023 11:43 AM
To: Japa, Srujana (MDH) <Srujana.Japa@state.mn.us>
Cc: Blair, Benjamin (He/Him/His) (MDH) <Benjamin.Blair@state.mn.us>
Subject: Re: MDH : Missing COVID Labs Great Lakes MC

Report Stream (CDC)
Fri 10/13/2023 12:42 PM
Hi Srujana, Thank you for contacting ReportStream Support. We are unable to find any facility information on Great Lakes MC. Please reach out to the contact for dates of submission, CLIA number, or facility details so that we can research further. Please also

Report Stream (CDC)
Japa, Srujana (MDH) <Srujana.Japa@state.mn.us>
Blair, Benjamin (He/Him/His) (MDH) <Benjamin.Blair@state.mn.us>
Hi Srujana, 

Thank you for your email.  We are looking into this and will get back to you as soon as we have an update. 

For your reference, please visit the online Support FAQ. 

Best regards, 

Japa, Srujana (MDH) <Srujana.Japa@state.mn.us>
Report Stream (CDC)
Blair, Benjamin (He/Him/His) (MDH) <Benjamin.Blair@state.mn.us>
Good Morning Report Stream Team,

Could you please check your logs for COVID submissions from Great Lakes Management (Great Lakes MC), a senior living facility based in Minnesota, and verify if they have indeed submitted any data? As of now, we haven't received any data from them. Great Lakes MC claims that they have submitted data using simple reports.

**Comment by oslynn** [comment]
Done.
