### ISSUE TITLE
LA - Azure Alert - Production - Fatal Alert

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#11780]
## **Problem Statement**
On the Slack ReportStream onboarding-operations Channel received a "Found Fatal Alert" in Production FunctionApp.

## **What you need to know**
TenantId:	059ec6c1-498f-48d1-a59a-8df9bfdca183
TimeGenerated:	2023-10-13T14:52:20
Category:	Host.Function.Console
Location:	eastus
Message:	[1;31m14:52:20.432 [pool-2-thread-305][1810] FATAL-ALERT gov.cdc.prime.router.azure.SendFunction - Success: sftp upload of cdcprime_cdcprime_laoph_production_production_20231011213558.hl7 to SFTPTransportType(host=204.58.124.41, port=22, filePath=./, credentialName=null), FAILED Sftp upload of inputReportId f37664a4-fa8b-46e3-9fd0-f099a4ea61d3 to SFTPTransportType(host=204.58.124.41, port=22, filePath=./, credentialName=null) (orgService = la-doh.elr), Exception: Status code 409, '?<?xml version='1.0' encoding='utf-8'?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
HostVersion:	4.25.2.2
HostInstanceId:	d8b720dc-1518-4dbe-bc9c-488588e1e3ae
Level:	Information
AppName:	pdhprod-functionapp
RoleInstance	0d1d95cb5bca24eae97e7d7a3b08580f2c1be3b13b58a879b77193a70e7cfdf4
LevelId	2
ProcessId	25
SourceSystem	Azure
Type:	FunctionAppLogs
_ResourceId:	/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourcegroups/prime-data-hub-prod/providers/microsoft.web/sites/pdhprod-functionapp

## **Acceptance Criteria**
Assign to Engineer
Investigate the cause/reason for the error message.
Determine if an action/resolution is needed.
Close ticket when resolved.

## **To Do**
Please reach out the Helpdesk if you need assistance in reaching out the State/STLT.

## **Additional Comments**
If applicable, add screenshots, links, etc. to further explain the ticket

**Comment by adegolier** [comment]
These files are getting sent to LA, it's mad about another upload to our own blob. The blob upload happens in this step.
![image](https://github.com/CDCgov/prime-reportstream/assets/39102333/2836bff7-b258-4a69-a780-d3eaa2517a99)
