### ISSUE TITLE
End to end tests for HL7 generation from CSV ingestion

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1178]
Need to generate new end to end tests to test the generation of HL7 messages from CSV data. Tests should run as part of the CLI's end to end tests.

Acceptance criteria:
1. The tests sends a CSV payload with a single row to the ReportStream API
2. The test compares the HL7 output of ReportStream sent via SFTP to a receiver and verifies the HL7 data is as expected.
3. The tests also sends a CSV payload with more than one row to the ReportStream API and verifies all the records are converted to HL7 as expected

**Comment by carlosfelix2** [comment]
OBE by #1345
