### ISSUE TITLE
Add FileNameElement to get number of files sent to a receiver for the current day

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1180]
Both CA and Santa Clara County want to have a file name that includes the number of files that have been sent to them successfully, so the first file sent needs to be numbered 0001, and then 0002, and so on. 

In order to accomplish this, there's a ReportFile table in the database that tracks what organization it was sent to, and when. The query would look something like:

```sql
SELECT
    count(*) as count_files_for_date
FROM
    report_file rf
WHERE
    rf.receiving_org = @receivingOrg
    and rf.created_at between @startDate and @endDate 
    and rf.transport_params like 'SFTPTransportType%'
    and rf.transport_result like 'Success%'
;
```
In the above query, you would want to pass in the receiving organization (`ca-dph`) and the start and end date as variables, and then you could increment the count of the file by one.

The call to access the database should go into `DatabaseAccess.kt`. The query above can be a function in postgres that gets invoked.

**Acceptance criteria**:
- A new element is created to get the count of files sent for the current date and receiving organization
- The element is added to the collection of file name elements in Metadata
- The file name element returns the count of files incremented by one
- The file number should be left-padded to four digits with 0's because we could theoretically send one message a minute, and there are 1440 minutes in a day
- The file name element does not fail if connection to the database fails, or if no data is found, but instead sets the file number to `0001`

_This is blocked by #776 which must be merged in before this work can be done._

**Comment by jlusds** [comment]
What's the status of this?

**Comment by brandonnava** [comment]
@brick-green @MauriceReeves-usds Is this still something we care about and would ever actually implement?

**Comment by brick-green** [comment]
let's close. It hasn't come up recently. Plenty of other work to do
