### ISSUE TITLE
Add whitelist request with CDC for sftp1.neometrics.com

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#11807]
Please fill out the change request form to allow outbound SSH to sftp1.neometrics.com in both staging and production. You can test with your -SU account that it's working by opening an SSH session to the Function App containers and then connecting (if you get the login prompt it's working at the firewall level).

Notes on how to perform the firewall request [steps are here,](https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FOperations%2FHow%20To%2FCSPO%20Firewall%20Rule%20Change%20Request%20Process&viewid=17db3ff6%2D95c5%2D4562%2Da1f3%2D12b5097b5947) they are a bit cumbersome so check your work!

**Comment by jeremy-page** [comment]
Blocked by access on the CDC side. Lucas and Supriya are working on it.

**Comment by jcrichlake** [comment]
@supriyaaddagada any update on this item from the CDC side?

**Comment by jeremy-page** [comment]
Submitted to the CDC a second time, CHG0032022  is the ticket #
