### ISSUE TITLE
Update HL7v2 to FHIR to HL7v2 DataType Mappings: SAD

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#11816]
### User Story

As a ReportStream engineer,
I want to update the ReportStream HL7v2 -> FHIR and FHIR -> HL7v2 mappings for the `SAD` HL7v2 data type per the mapping inventory
so that I can ensure data does not get dropped during translation and enable the creation of mappings of ORU-R01 segments that reference this HL7v2 DataType.

### Description/Use Case

Given the ORU-R01 context, this HL7v2 DataType can map to the following resources (the sub list shows where exactly in what mapping file the DataType mapping appears in):

- [ ] SAD
    - [ ] string
        - [ ] HL7 Data Type - FHIR R4_ XAD[Address] - Sheet1-XAD.1

### Testing
The unit tests for the mappings of this DataType DO NOT have to cover every since segment a particular HL7v2->FHIR / FHIR->HL7v2 mapping appears in. It is sufficient to pick a representative segment and base the DataType mapping tests off of it. The unit tests should verify a segment containing a particular mapping maps correctly to HL7v2->FHIR and FHIR->HL7v2, having a test case for each condition or logic outlined in the mapping inventory for a particular mapping.

### Acceptance Criteria

- [ ] Mappings outlined in the Description of ticket have been created/updated per the mapping inventory
- [ ] Unit Tests created per testing strategy
- [ ] Any new RS extensions have FHIR examples documented

**Comment by mkalish** [comment]
Taking a closer look at this one, it looks like there will be no work here as the mapping inventory actually becomes inconsistent naming wise.  The spreadsheet is named SAD[Address], but actually should not result in an address datatype getting created.  Rather it just spells out how SAD.1-3 should get handled in XAD[Address].

**Comment by arnejduranovic** [comment]
To help speed up approval:

![Screenshot 2023-10-23 at 9 09 06 AM](https://github.com/CDCgov/prime-reportstream/assets/118766341/25bf474e-7298-4667-a859-d8d7bab9de65)

![Screenshot 2023-10-23 at 9 10 33 AM](https://github.com/CDCgov/prime-reportstream/assets/118766341/f562ea1f-6ec6-4deb-ba1f-656874201d74)

![Screenshot 2023-10-23 at 9 13 34 AM](https://github.com/CDCgov/prime-reportstream/assets/118766341/570fe7ab-9e70-4550-ae36-6409f23b2a2a)
