### ISSUE TITLE
New York UP Onboarding - Validate Test Data

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#11826]
### Acceptance Criteria 
- [ ] Created and sent data using fake data generator 
- [ ] Created and sent data using synthesized data generator 
- [ ] Confirmed with STLT that data passes validation 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with receiver 
- [ ] RS team member who originates this ticket: add any dependencies, as needed 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Receiver" and state label 
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by LaFreda1** [comment]
NY confirmed on today's call that they are ok with the test messages that Victor sent over. Now, we are waiting on SR. Glenn to follow up with them tomorrow (11/15/23).

**Comment by chris-kuryak** [comment]
Closing this ticket. Will need to do again when HCI is onboarded.
