### ISSUE TITLE
[SPIKE] Determine how to solve the Date/time/timezone issue

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#11835]
[Purpose:] We don't want to send incorrect time/date data to receivers.

Need to determine:

1. Is timezone required on test results to be sent to receivers?
2. Is timezone required for a message to move through the UP?

If the answer to either of those questions is yes, then we need to add timezone as a required field during validation. And make it a new ticket(s) in this epic.

- Currently we default to UTC when senders do not send us a time zone.
- Proposed solution was to add a timezone to initially ask Senders to provide it, if they cannot, then we ask them which timezone they would like added to the data as a transform, and if they do not know/confirm, then we can add it, but additionally add a note/comment to the message indicating that we changed the timezone (for traceability). The addition should likely ALSO be added to our logging in Azure
- We also need to get alignment from leadership
 
See [#7527](https://app.zenhub.com/workspaces/engagement-6166edbd409257001e09f1b2/issues/gh/cdcgov/prime-reportstream/7527) for reference.

## Acceptance Criteria
- [x] Leadship's guidance on how to handle this issue is documented
- [x] Engineering determines what date/time/timezone data is required of a message to move through the UP successfully
- [x] Document how to handle this issue and guidance for other team members

**Comment by LaFreda1** [comment]
Idea: Grandfather existing senders, but have all new senders standardized

**Comment by chris-kuryak** [comment]
Chris meeting with Product this week to get alignment

**Comment by chris-kuryak** [comment]
Chris met with Product and PO, no issue with the plan as stated.
There are no requirements on this topic from a regulation standpoint that we know of.

**Comment by chris-kuryak** [comment]
@victor-chaparro I updated the ticket and separated out a new one for aligning with Platform. You should be able to close this at the end of this current sprint

**Comment by chris-kuryak** [comment]
Per victor, closing
