### ISSUE TITLE
Unlabled container images still stored in ACR

### ISSUE THREAD

**Issue by snesm** [CDCgov/prime-reportstream#11869]
## Problem statement

Azure security center is reporting 403 vulnerable container images which are not labeled, but still stored in the ACR.
Security center reports: `This image has no tags. It still exists in the registry. If it's pulled by its digest, it'll expose security vulnerabilities.`

## What you need to know
[soft-delete 
](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-soft-delete-policy) is not enabled (see below).

ACR [retention policy](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-retention-policy) is set to 365 days (see below).

```
% az acr config soft-delete show -r XXXXXXX --subscription XXXXXXX
Command group 'acr config soft-delete' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
{
  "lastUpdatedTime": null,
  "retentionDays": 7,
  "status": "disabled"
}

% az acr config retention show --registry XXXXXXX --subscription XXXXXXX
Command group 'acr config retention' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
{
  "days": 365,
  "lastUpdatedTime": "2022-12-08T17:34:55.685413+00:00",
  "status": "enabled"
}

```
 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by lucasdze** [comment]
![image](https://github.com/CDCgov/prime-reportstream/assets/50645318/0e9dec36-6c2d-4628-9e73-9e833de2efa1)

**Comment by snesm** [comment]
Staging [cleanup](https://github.com/CDCgov/prime-reportstream/pull/11930)
