### ISSUE TITLE
Generate a quality score for each row in a report

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1187]
We encountered a bug last week where SimpleReport changed how they were reporting data and stopped sending patient phone numbers to us, but neither of us noticed until a state followed up.

We should generate logic that calculates a quality score for each row in a report. This is tangentially related to the quality filters we have, but allows us to quickly make a determination if a row is low-quality or not. 

The score should be out of 10 with 0 being the lowest possible score. Each row starts with 10 points, and then loses points as it is checked.

There should be several parts to the calculation:

- Failing the default quality filter immediately sets the score to 0
- Each of the following being null or empty deducts a single point:
  - `patient_email`
  - `patient_phone`
  - `patient_zip_code`
  - `testing_lab_clia`
  - `specimen_collection_date`
  - `test_result`
- If the following are badly formatted, it deducts 0.5 points:
  - `patient_email`
  - `patient_phone`
  - `testing_lab_clia`
 
This should be able to be run from the command line, and it should run on ingestion, especially as we get data from SimpleReport, and it should be reported in the JSON response body so we can can track data quality. For the JSON response body, the score reported should be an aggregation of all the rows sent, ad then an aggregation of the rows that WILL be sent to a state, which will let us see if data quality is staying high, or is declining.

cc: @RickHawesUSDS @jimduff-usds @carlosfelix2

**Comment by MauriceReeves-usds** [comment]
As an example of the output with quality scores, it should look like this:

```json
{
  "id" : "45fbb1ba-5ed0-41b8-9b30-75b8e03615c5",
  "timestamp" : "2021-05-30T23:00:00.755236Z",
  "topic" : "covid-19",
  "reportItemCount" : 14,
  "averageQualityScore" : 7.75 ,
  "destinations" : [ {
    "organization" : "Louisiana Department of Health",
    "organization_id" : "la-doh",
    "service" : "elr",
    "sending_at" : "2021-05-30T19:15-04:00",
    "itemCount" : 13,
    "averageQualityScore" : 8.0 
  }, {
    "organization" : "North Dakota Department of Health",
    "organization_id" : "nd-doh",
    "service" : "elr",
    "sending_at" : "2021-05-30T19:15-04:00",
    "itemCount" : 1,
    "averageQualityScore" : 6.0
  }, {
    "organization" : "South Dakota Public Health Department",
    "organization_id" : "sd-phd",
    "service" : "elr",
    "sending_at" : "2021-05-30T19:15-04:00",
    "itemCount" : 1,
    "averageQualityScore" : 6.0
  }, {
    "organization" : "Mississippi Department of Health",
    "organization_id" : "ms-doh",
    "service" : "elr",
    "sending_at" : "2021-05-31T09:15-04:00",
    "itemCount" : 1,
    "averageQualityScore" : 8.0
  } ],
  "destinationCount" : 4,
  "warningCount" : 0,
  "errorCount" : 0,
  "errors" : [ ],
  "warnings" : [ ]
} 
```

**Comment by jimduff-usds** [comment]
Hmm - I'd be concerned that customers will be confused by the scoring, which will result in a lot of questions.   It might be good to do some user research first, on what they will find most beneficial.

But in the meantime, there is something we can do that builds on mechanisms we already have:  warn on validation errors.   In the course of my recent work, I was surprised to discover that, for non-required fields, we mostly do **not** provide any kind of warning back to the sender on bad data.    In particular, @SpiderSense has highlighted that this results in unexpected behaviors, when mixed with the effect of mappers and defaults.

@tlosbo has fixed this problem for `CODE` Valueset fields.   We should do the same for other types, for which warnings are currently missing.
