### ISSUE TITLE
Create Sender Compendium Comparison Utility

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#11935]
As a ReportStream engineer, I want to have a CLI command that can compare an input csv with a table stored in our DB and return which values from the input CSV are contained in the stored table.

**background** 

In order to greatly reduce the number of unmapped errors that we will have to deal with. It is recommended that we build a utility where senders can submit their test compendiums during the onboarding process to allow engagement to pre-emptively map. This will be a utility that takes in a csv file prepared by the sender and compares the codes against the observation mapping table. The utility should then return which codes are not found in the table so that the engagment team can map them prior to the sender moving to production.

Example parameters: </br>
env - environment to run command against </br>
tablename - name of table to compare input to </br>
input -file location of input CSV </br>
output -location to output post comparison csv

Example CLI command:

./prime mapping-table-comparison -tablename observation-mapping -input <input-file-location> output <output-file-location> -env staging

Example input compendium CSV:
```csv
test code,test description,coding system
97099-6,Influenza virus A and B and SARS-CoV-2 (COVID-19) Ag panel - Upper respiratory specimen by Rapid immunoassay, LOINC
47457-7,Influenza virus A H8 Ab [Titer] in Serum, LOINC
123456, LDT Flu Test, LOCAL
```
Example output CSV:

```csv
test code,test description,coding system, mapped?
97099-6,Influenza virus A and B and SARS-CoV-2 (COVID-19) Ag panel - Upper respiratory specimen by Rapid immunoassay, LOINC., Y
47457-7,Influenza virus A H8 Ab [Titer] in Serum, LOINC, Y
123456, LDT Flu Test, LOCAL, N
```

| Member OID                     | Name                                                 | Code    | Descriptor                                                                          | Code System | Version | Status | Condition Name                                                 | Condition Code  |
|--------------------------------|------------------------------------------------------|---------|-------------------------------------------------------------------------------------|-------------|---------|--------|----------------------------------------------------------------|-----------------|
| 2.16.840.1.113762.1.4.1146.798 | Influenza (Tests for influenza A virus Nucleic Acid) | 80382-5 | Influenza virus A Ag [Presence] in Upper respiratory specimen by Rapid immunoassay  | LOINC       | 2.74    | Active | Infection caused by novel Influenza A virus variant (disorder) | 541000000000000 | 
| 2.16.840.1.113762.1.4.1146.799 | Influenza (Tests for influenza A virus Antigen)      | 80382-5 | Influenza virus A Ag [Presence] in Upper respiratory specimen by Rapid immunoassay  | LOINC       | 2.74    | Active | Influenza (disorder)                                           | 6142004         |
|                                | Influenza - (ABC TESTING LABS)                       | 123456  | Influenza virus A                                                                   | LOCAL       |         | Active | Infection caused by novel Influenza A virus variant (disorder) | 541000000000000 | 

**resources**
[example observation mapping table.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUJrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2356a6cd1f6568bee00cd3fee152235042729f06/example%20observation%20mapping%20table.xlsx)

**additional info**
The following CLI command can be used to load the example table into your local database. Be sure to save the example table as a .CSV file before running the command.

./prime lookuptables create -i "input-file-location" -n "input-table-name" -a

**Acceptance Criteria**
-[ ] given an input CSV and the name of a lookuptable table stored in the db, a comparison can be output to the console that shows which values in the input CSV are mapped and which are not.
-[ ] the output can be exported as a .csv file

**Comment by arnejduranovic** [comment]
@GilmoreA6 When checking if a code exists, what happens if code system and code match but description is different? What should the output of the command look like in that case?

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11935?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @jalbinson @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11935?planning-poker) with Zenhub @JessicaWNava

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11935?planning-poker) with Zenhub @JFU-NAVA-PBC

**Comment by GilmoreA6** [comment]
@arnejduranovic we should go with the description that is in the table in our database as that will be the official loinc terminology whereas the sender may have a local description
