### ISSUE TITLE
Create initial observation-mapping-table for code-to-condition work

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#11948]
As a ReportStream engineer I want to upload the initial observation-mapping-table to the development, staging, and production environments.

**Background Info**
The observation mapping table will be used to map LOINC/SNOMED codes to their relevant reportable conditions in the UP. The initial table is made up of values that are contained in valuesets maintained by the Council of State and Territorial Epidemiologists (CSTE) on the National Library of Medicines Value Set Authority Center (VSAC) https://vsac.nlm.nih.gov/ . The valuesets are compiled and mapped to conditions by CSTE and published in the Reportable Conditions Trigger Codes (RCTC) documents used by the CSTE/AIMS product Reportable Condition Knowledge Management System (RCKMS) project.

The RCTC is available to be downloaded from AIMS at https://ersd.aimsplatform.org/#/home. A login is required (registration is free).

**Resources**
The RCTC is not provided in a convenient format for direct uploading. A copy of the RCTC valuesets that has been modified to the correct format is included here for convenience. Be sure to save as a .csv file before attempting to upload. In addition this file contains mapping for AOE questions from LOINC.org. There are two sources of AOE question codes. One for COVID (https://loinc.org/sars-cov-2-and-covid-19/ - LOINC terms for SARS-CoV-2 AOE questions) and one for general public health (https://loinc.org/81959-9)
[observation-mapping-table.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMit4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f5e63fb9dfd42a7ac2c10f701ea60b0ed608547/observation-mapping-table.xlsx)

**Additional Info**
- Uploading the table  to remote environments can utilize the ./prime lookuptables create command

```
options:
 -e, --env <name>       Connect to <name> environment. Choose between
                         [local|test|staging|prod]
  -i, --input-file PATH  Input CSV file with the table data
  -s, --silent           Do not generate diff or ask for confirmation
  -a, --activate         Activate the table upon creation
  -n, --name TEXT        The name of the table to perform the operation on
  --show-table           Always show the table to be created
  -f, --force            Force the creation of new table(s) even if it is
                         already exist
  -h, --help             Show this message and exit
```

Example
`./prime lookuptables create -i 'file-path-location' -s -a -n observation-mapping -e staging`

- Uploading the table to local environment can utilize prime-router/metadata/tables so the dataset will get created locally automatically. The file can be updated when new versions are released

**Acceptance Criteria**
- [ ] latest version of dataset uploaded to staging and production environment
- [ ] latest version of dataset automatically added to local env on startup

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11948?planning-poker) with Zenhub @mkalish @jimmyfagan @JessicaWNava @arnejduranovic @thetaurean @brick-green @jalbinson @jack-h-wang

**Comment by thetaurean** [comment]
Table has been added to prod & staging using the October dataset. November was not available at the time of upload.
