### ISSUE TITLE
Upload NEW LIVD SARS-CoV-2 Table

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#11949]
## **Problem Statement**
We received an updated LIVD to the Reportstream inbox. The LIVD table needs to be uploaded into ReportStream.

## **What you need to know**
[LIVD-SARS-CoV-2-2023-10-04 PRIME.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3hxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3198f0abb673c6609f14307eac3f831eab3bacf/LIVD-SARS-CoV-2-2023-10-04%20PRIME.xlsx)

## **Acceptance Criteria**
Complete update.  Close ticket when complete.

## **To Do**
Assign to an Engineer

## **Additional Comments**
If applicable, add screenshots, links, etc. to further explain the ticket

**Comment by oslynn** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXB1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--471a9bffe3e1c771b5a4e012a44f770a4d920936/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTF1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75d6edb76fe79fb173067e2cd51db5abe1d26cae/image.png)

**Comment by oslynn** [comment]
Staging and Prod are updated.
