### ISSUE TITLE
Investigate SFTP container failure in prod

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#11970]
[This container is failing in production.](https://portal.azure.com/#@cdc.onmicrosoft.com/resource/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourceGroups/prime-data-hub-prod/providers/Microsoft.ContainerInstance/containerGroups/pdhprod-sftp01-continst/overview) Please determine why and remediate.

**Comment by dkrylovsb** [comment]
The container went down because two of the file shares it needs had been deleted by someone for unknown reason. Ran `terraform apply -target="module.sftp"` to recreate the missing shares and the container.
