### ISSUE TITLE
Content Updates to the Onboarding Form

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12007]
## Problem statement

After reviewing the current onboarding process with the Engagement team, changes need to be made to the Onboarding form to make it more accurate and helpful for our users.

## What you need to know

- [Onboarding Form](https://app.smartsheetgov.com/b/form/b0935d5d1e924c57b2d293b4ed0f2cd5)
- [Form Changes](https://docs.google.com/document/d/1PmLhy20EkqIs3c06N3emaT9PjGU4-n_81XjjvoVOMSc/edit)
- Contact Audrey Ross for questions
- This DOES NOT require USDS approval to merge. Good to merge after Engineering and Design review.

## Acceptance criteria

- [ ] Content changes/updates per the document above

**Comment by sliu1000** [comment]
@chris-kuryak updated
@audreykwr please review and let me know if you have any feedback or need changes

https://app.smartsheetgov.com/b/form/b0935d5d1e924c57b2d293b4ed0f2cd5

**Comment by chris-kuryak** [comment]
Completed
