### ISSUE TITLE
Update RADx MARS ReportStream reference

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#12011]
## Problem Statement
Information about Reportstream is not accurate on external websites?

## Background & context

Mo flagged that [NIH and RADx MARS](https://www.nibib.nih.gov/covid-19/radx-tech-program/mars/data-hubs) featured content about us that needs to be updated.

[Draft doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BBC59EB28-55AF-4D1E-88D5-649FD12644F1%7D&file=20231115_RADxMARS_site_content_WIP.docx&nav=eyJjIjo3Mjc3ODg0MDZ9&action=default&mobileredirect=true)

## Acceptance criteria

-   [x] Create Content
-   [x] Review internally
-   [ ] Review externally
-   [ ] Hand-off to Mo

**Comment by audreykwr** [comment]
@chris-kuryak for your awareness for sprint planning next week

cc @jillian-hammer

**Comment by chris-kuryak** [comment]
Needs to be approved by external team partner before going to the RadX Mars folks

**Comment by chris-kuryak** [comment]
Closing per Audrey completed
