### ISSUE TITLE
Connect HCI to the UP as a Sender on Staging

### ISSUE THREAD

**Issue by brandonnava** [CDCgov/prime-reportstream#12034]
### User Story

As the HCI organization, I need the ability to send HL7v2.5.1 NIST ELR (ORU-R01) messages through RS to STLTs on ReportStream's staging environment universal pipeline. For the pilot effort, this will be NY.

### Description/Use Case

We need to configure RS:
1. Create a sender under the `hcintegrations` org in staging that can send HL7v2.5.1 NIST ELR messages
2. This sender should be configured to use the `full-elr` topic.
3. HCI will use RS's oauth, so contact Arnej for their public key and associate it with their org

### Acceptance Criteria

- [x] Added sample sender to org file. See https://github.com/CDCgov/prime-reportstream/pull/10426/files#diff-a3595b762b115fdaacb32ec9e8930def1a645002ecc8cc1ba9102d2ec5512fd8 to see how this was done for CDC ELIMS.
- [x] Updated existing receivers on UP to ignore messages coming from HCI
- [x] HCI Public key added to org 
- [x] Verify submissions page works for all HCI senders

**Comment by arnejduranovic** [comment]
Before we can do this story, we need HCI to create a public/private key pair and send us the public key.

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12034?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @jalbinson @JessicaWNava @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12034?planning-poker) with Zenhub @JFU-NAVA-PBC

**Comment by jimmyfagan** [comment]
I misspoke in Standup today, the hci sender transform wasn't merged on Wednesday, so it wasn't in Thursday's deployment. It was merged today, but progress here will be slow until the next deployment which is next Tuesday.
