### ISSUE TITLE
Unusual Non - USA access to ReportStream

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#12031]
## **Problem Statement**
A Design/Research was working on Azure analytics and noticed a ReportStream user from Germany.  We would like to investigate to make sure this is not a security breach.

## **What you need to know**
We have tracking on individual pages, both public-facing and authenticated. This user showed as "visiting" the Data Dashboard page from Germany. Our Okta geo-fencing should limit access to only the USA.
Want to determine if this person could have logged in from outside the USA and seen the Data Dashboard page, or if they instead just attempted to visit the Data Dashboard and then were asked to log in instead.

Please see below image for more context.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmlSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e942f293acd4d3801b21a2add92cf48912977b22/user_foreign.png)

## **Acceptance Criteria**
Assign to Security Engineer
Confirm this is not a security breach

## **To Do**
A quick note to the assignee of the ticket.

## **Additional Comments**
If applicable, add screenshots, links, etc. to further explain the ticket

**Comment by chris-kuryak** [comment]
I believe this was just a visitor who may have clicked on Data Dashboard even though they were not logged in.

How can we confirm this? @snesm @penny-lischer 
Does the Azure event fire before the page loads successfully?

**Comment by chris-kuryak** [comment]
@jpandersen87 See my question above. Do you know if the Azure even fires before the page loads successfully?

**Comment by jpandersen87** [comment]
> @jpandersen87 See my question above. Do you know if the Azure even fires before the page loads successfully?

Azure wouldn't emit telemetry on the first visit (defined as going to the reportstream website in a browser tab that was not already on it) to the site on any of the public pages until the user clicked on a link to navigate to another page. Then (as long as that navigation was correctly intercepted by our web app and handled internally) some telemetry would likely immediately be emitted (PageViewData information, a MetricData with the name PageVisitTime, and PageviewPerformanceData). If a user were to do a first-visit to one our pages that requests data from our backend, however, that would at least emit RemoteDependencyData. We _should_ be under simplereport's geofencing rules, which means okta would have prevented a login from outside the US. That doesn't prevent anonymous access to the site in general from outside the US.

**Comment by chris-kuryak** [comment]
@jpandersen87 So if I am interpreting this correctly, you DO think that the following is possibly the explanation here?

User from Germany visits public ReportStream page. 
User clicks on Data Dashboard link on public page. 
Data Dashboard page attempts to load page. 
**Pageview data for Data Dashboard visit is triggered/captured by App Insights.**
Since they are not logged in, page does not load and user is redirected to log in.

**Comment by jpandersen87** [comment]
> @jpandersen87 So if I am interpreting this correctly, you DO think that the following is possibly the explanation here?
> 
> User from Germany visits public ReportStream page. User clicks on Data Dashboard link on public page. Data Dashboard page attempts to load page. **Pageview data for Data Dashboard visit is triggered/captured by App Insights.** Since they are not logged in, page does not load and user is redirected to log in.

If there was no extra data attached to indicate it was an authenticated session, then yes this is likely the scenario that occurred.

**Comment by snesm** [comment]
For this specific case we believe:

Audrey Ross (she/her) wrote:
> ha! That was probably @Penny Lischer using Sitechecker (edit - if I'm understanding that the "sitcheckerbotcrawler" was the thing that created this. Penny had used this to crawl our site links) 

The Sitechecker activity was recorded/available via Azure Application Insights.

**Comment by LaFreda1** [comment]
This access was from a bot that was triggered internally.

**Comment by chris-kuryak** [comment]
Etan and Chris checked this today and confirmed that Azure App Insights will trigger a pageview of Data Dashboard even when it redirects you to the login page. 

Therefore, I think this is sufficient evidence of how this non-USA pageview was likely triggered and how it likely does not trigger a security concern.
