### ISSUE TITLE
Document outage in postmortem

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#12046]
Please [use this template.](https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FOperations%2FOutage%20RCAs) Add the information from slack, Azure logs and your own knowledge of the outage.

This will be presented in a meeting with the USDS and CDC

**Comment by lucasdze** [comment]
Here is the first [document](https://icfonline-my.sharepoint.com/:w:/g/personal/58917_icf_com/Efo_G7DZ7FdKvVgYP2MG3MUBuoctRczMiHBlLTY10451xA?e=2k5dt7) I am working on. Will be edited accordingly until the issue is fully resolved
