### ISSUE TITLE
CSV->FHIR Formatting & Gap Analysis

### ISSUE THREAD

**Issue by brandonnava** [CDCgov/prime-reportstream#12043]
### User Story
I as a developer on RS want to be able to migrate a CSV sender in our covid pipeline to the UP

### Description/Use Case
The goal of this ticket is to understand what a properly formatted CSV message looks like for the following conditions: COVID, Flu A, Flu B, RSV, Respiratory Panel (multiplex) in service of being able to move all covid CSV senders from the covid pipeline to the UP

**Open Questions**
What fields/datatypes are currently being reported through the COVID pipeline by **RS CSV senders**?
What fields/datatypes are currently being reported by **SimpleReport bulk uploader users**?
Are there other ELR CSV templates out there (e.g., direct submission to STLTs)?
How do the CSV requirements differ between RS and SR users? With other CSV templates?
What fields/ datatypes are required for CSV users in the UP (basically, what are the column headers)?
Are we able to leverage SimpleReport's CSV > FHIR mappings within RS? What are the pros and cons/ changes that need to be made?
Are there other pre-existing tools for mapping CSV to FHIR?

**Links**
- [Product Brief](https://docs.google.com/document/d/1dfvSWQjPhAKHW2shQ2jn4VxAPrLpvNJ4duK27NY0gnU/edit)
- [CSV > FHIR Notes](https://docs.google.com/document/d/1mk06z-gZa9YAJqYtuZ6aQ3hW3iWFFzsVKNfgYboH7wQ/edit?usp=sharing)
- [API Guide](https://reportstream.cdc.gov/developer-resources/api)
- [CSV Data Model Requirements](https://reportstream.cdc.gov/developer-resources/api/documentation/data-model)
- [SimpleReport Bulk Upload Results](https://www.simplereport.gov/using-simplereport/report-test-results/bulk-upload-results/)

### Acceptance Criteria
As part of the analysis please do the following:
- [x]  Get familiar with and log our CSV format standards as outlined in the API programmers guide
- [x]  Get familiar with and log SimpleReport's CSV format
- [x]  Compare the two for diffs
- [ ] Log and analyze what SR's CSV conditions look like after SR converts them to FHIR with their CSV->FHIR library
- [ ]  Run our covid CSV format through SR's CSV->FHIR converter and analyze the result for gaps
- [ ]  Convert the FHIR result to HL7 and compare back to the baseline CSV format to see if any data is lost or misconstrued, take note of those differences
- [ ]  Ultimately, find out where SR's CSV->FHIR library mappings come up short and be ready to share of list of what transforms/translations will need to be built to so we can migrate all our CSV senders to the UP and deprecate the UP!

**Comment by dylansmith-Nava** [comment]
Owing to the conversation with [various SimpleReport stakeholders](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B585C06D0-9475-42A9-BBF5-1A59BB0B8177%7D&file=CSV%20submissions%20in%20SimpleReport.docx&action=default&mobileredirect=true), we discovered that SimpleReport's CSV format is not a viable format to use for a few important reasons, including that their validation will only accept messages with specific LOINC codes, and that SimpleReport does not have a viable strategy for handling multiplex data. As such, ReportStream will not be pursuing any further work with SR's CSV schema, including looking at their CSV>FHIR library. Instead, I will be pursuing strategies for developing a ReportStream CSV schema that can handle multiple conditions. FHIR mapping will come with later tickets. As such, I will be closing this ticket. CC @jillian-hammer @brandonnava @Andrey-Glazkv
