### ISSUE TITLE
Test CDC-ELIMS messages: Part 7 - DateTimes

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#12044]
### User Story
As ELIMS, I would like HL7v2 DateTime fields to get translated correctly when going from HL7v2 -> FHIR -> HL7v2

### Description/Use Case
Presently, there are two scenarios identified in this [spreadsheet](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/Shared%20Documents/ELIMS-ELR/Gap%20Analysis/HL7%20IN%20vs%20HL7%20OUT%20_%20Gap_Analysis.xlsx?d=wfaed6c19ba414f03a1486c8490228a1c&csf=1&web=1&e=YXLfAV) that relate to DateTime differences:

1. Rows 6 - 14: RS is converting the timezone to +0000. The resulting time is correct, but we should preserve the original timezone.
2. Rows 15 - 21: When given a DateTime containing ONLY YY/MM/DD, we are adding time which is incorrect. The FHIR spec supports DateTime values that only contain YY/MM/DD.

**IMPORTANT NOTE:** The above two issues DO NOT appear when running the translation via prime CLI, like so: 

```
primeCLI --args='fhirdata --output-format HL7 -i /Users/arnej/Downloads/julie-date-issue/29_05059412_35054.HL7 -o /Users/arnej/Downloads/julie-date-issue/cmd-line-convert-out.hl7 -s /Users/arnej/Projects/prime-reportstream/prime-router/metadata/hl7_mapping/ORU_R01/ORU_R01-base.yml'
```

But they DO APPEAR when running the message through the pipeline via submission API. When I debugged, it seems like the issue is happening inside `FhirToHl7Converter.convert`, meaning the HL7v2->FHIR translation is NOT the problem, but rather something happens during the FHIR -> HL7v2 translation. At the start of this method, the bundle submitted via the cmd line and the bundle submitted via the API are identical but the value of `return message` is different.

### Acceptance Criteria
- [ ] [Sample test message](https://cdc.sharepoint.com/:f:/r/teams/ReportStream/Shared%20Documents/ELIMS-ELR/Gap%20Analysis/12044?csf=1&web=1&e=rOR9Y6) run through pipeline and output message confirmed to equal input message.
- [ ] Understand why CLI produces different output than running through pipeline. Issue fixed or new ticket created.

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12044?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @jalbinson @JessicaWNava @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12044?planning-poker) with Zenhub @jimmyfagan

**Comment by jimmyfagan** [comment]
The reason the datetime translation is different in the CLI than in the application is around the context.config. There is a line in `CustomTranslationFuncitons.convertDateTimeToHL7` that says `if (appContext?.config is HL7TranslationConfig) {`, but the `appContext?.config` is null in the cases of the CLI and in TranslationTests where the receiver is not specified. I think as a 17th, we can try to gameplan what to do with those cases, maybe we can get a config in those cases to have the behavior in those cases more closely match what we have elsewhere. We also may want to cut down on the custom `convertDateTimeToHL7` function overall to no longer support timezone conversion based on receiver settings.
