### ISSUE TITLE
New terraform checkov detection

### ISSUE THREAD

**Issue by lucasdze** [CDCgov/prime-reportstream#12059]
Investigate these new checkov detections
Check: CKV2_AZURE_40: "Ensure storage account is not configured with Shared Key authorization"
Check: CKV2_AZURE_41: "Ensure storage account is configured with SAS expiration policy"

https://github.com/CDCgov/prime-reportstream/actions/runs/6734694971/job/18306277369?pr=12057

**Comment by snesm** [comment]
CKV2_AZURE_40 and CKV2_AZURE_41 are obsolete.
