### ISSUE TITLE
ID - Prod Error 11/2/23

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#12068]
## **Problem Statement**

An automated alert was received in Slack regarding a connection/upload error with Idaho DOH.

## **What you need to know**

Error details:
> [1;31m22:29:10.947 [pool-2-thread-191][819] FATAL-ALERT gov.cdc.prime.router.azure.SendFunction - FAILED Sftp upload of inputReportId `aa3023d7-56ce-47bb-a37f-d56d17a67cae` to SFTPTransportType(host=sftp.dhw.idaho.gov, port=22, filePath=./ELR/SimpleReport/Prod, credentialName=null) (orgService = id-phd.elr), Exception: Connection reset, All retries failed. Manual Intervention Required. Send Error report for: `aa3023d7-56ce-47bb-a37f-d56d17a67cae `to id-phd.elr[m

## **Acceptance Criteria**

Confirm successful submission of the file and receipt by ID.

## **To Do**

Investigate and resolve the error, resend report file.

## **Additional Comments**

Report was found in Metabase, and will need to be resubmitted.

**Comment by oslynn** [comment]
@wcollin89 it is fixed and resubmitted.  Done.
