### ISSUE TITLE
Develop Strategy for adding all remaining Covid Pipeline (CP) receivers to the Universal Pipeline (UP)

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12067]
## Problem statement
The overall migration strategy is going to be to add all receivers that are on the COVID Pipeline (CP) to the Universal Pipeline (UP) so they are simultaneously connected to both pipelines.

We need to develop a strategy that efficiently adds CP receivers to the UP.

## What you need to know

Goal: Developing a strategy and timeline that can be achieved over the next two quarters for adding CP receivers to the UP.

## Scope
- Existing CP receivers, not any new receivers
- Using existing Engagement resources/capacity

## Acceptance criteria
- [x] Determine a prioritization strategy for CP receivers (if applicable)
- [x] Timeline for migrating all existing CP receivers to the UP while considering capacity constraints (may require input from Product/Engineering/Design leads)
- [x] Identify what work (assets, content, etc) may need to be taken on by the Design team to achieve success
- [x] Reviewed with Product and Engineering for alignment

## To do

- [ ] ...

**Comment by jakefishbein-navapbc** [comment]
[Draft of strategy](https://docs.google.com/document/d/1V1pE1tl51Ed2ZBsqdbUVqCTLkXAe5qV77VykUvpRK1k/edit)
