### ISSUE TITLE
Research: Document how to add an existing COVID pipeline receiver to the UP

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12066]
## Problem statement
The overall migration strategy is going to be to add all receivers that are on the COVID Pipeline (CP) to the Universal Pipeline (UP) so they are simultaneously connected to both pipelines.

In order to determine a reliable strategy for migrating COVID receivers to the UP, we need to know the process and requirements for successfully adding an existing COVID receiver to the UP.

## What you need to know

- We are in the process of adding some existing CP receivers to the UP so they are simultaneously receiving data from both pipelines, but the process is not currently documented.
- Goal:  

## Scope
- Existing and previous UP onboarding initiatives (CA, NY)

## Acceptance criteria

- [x] Determine what is required from the RS team for adding a CP receiver to the UP
- [x] Determine what is required from the CP receiver perspective for being added to the UP
- [ ] Determine potential timeline and constraints for adding an existing CP receiver to the UP
- [ ] Determine areas that may need further investigation
- [ ] Findings documented
- [ ] Reviewed with Product and Engineering for alignment

## To do

- [ ] ...

**Comment by jakefishbein-navapbc** [comment]
[Running notes](https://docs.google.com/document/d/1NblX5jLQd7Q_4cYtaY7r8IFjiYXg_I2zwKTJrNjweWo/edit)
