### ISSUE TITLE
delete obsolete image and repository pdhstagingdtc:v1.0.0

### ISSUE THREAD

**Issue by snesm** [CDCgov/prime-reportstream#12061]
## Problem statement
Container registry `pdhstagingconerregistry`, repository `pdhstagingdtc` contains obsolete (and presumably unused) image `pdhstagingdtc` tagged `v1.0.0`, created 12/7/2021, 4:01 PM EST

Please verify that image and repository are unused and:

- [ ] Delete image `pdhstagingdtc` (sha256:52286bc946fe4a4a98bc49cbd9db9e817280d4769501ed9d1c81a7b6120cc3e5}
- [ ] Delete tag `v1.0.0`
- [ ] Delete repository `pdhstagingdtc`

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by snesm** [comment]
This image still needs to go:

![image](https://github.com/CDCgov/prime-reportstream/assets/94193373/e1d015ed-8b21-45de-8e51-2504601a6b6e)

**Comment by supriyaaddagada** [comment]
@snesm Image has been removed.
