### ISSUE TITLE
ETOR-Alabama onboarding

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#12074]
## Problem statement

Ott is helping the ETOR project with onboarding Alabama. He previously assisted with onboarding LA to their system and is currently waiting LA to be whitelisted. In the meantime, the team decided to proceed with onboarding Alabama. 

## What you need to know

- This in ongoing work; message from Max: 
A new part of the ETOR work stream ramped up during October, which is onboarding pilot partners to the UP to start testing the test order data flow. The partner onboarding requires more oversight from us since we're the experts in onboarding to ReportStream and hold the keys to things like e.g. creating a new receiver entity. This onboarding is what led Mo and me to commit to having one Engagement engineer available and prioritizing ETOR work for all of Q4.

## Acceptance criteria

- [ ] fully onboard Alabama to prod for ETOR

## To do

- [ ]

**Comment by oslynn** [comment]
We are going to onboard AL sender and receiver to RS.

**Comment by oslynn** [comment]
There are going to two senders and two receivers to setup.
Sender = al-phl.etor-nbs-orders Receiver = al-phl.etor-service-results
Sender = baptist.etor-nbs-orders Receiver = baptist.etor-service-results

**Comment by oslynn** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMC9RQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f19e9bae995ab004597753bbad2f5b53e1df6458/image.png)

**Comment by oslynn** [comment]
@victor-chaparro , would you approve the PR?  So, I can merge it.  PR: https://github.com/CDCgov/prime-reportstream/pull/12217

**Comment by LaFreda1** [comment]
All settings are done on staging; added another requirement to send messages one at a time. Modify messages to remove headers or footers. Ott will research if this possible.

**Comment by LaFreda1** [comment]
Ott completed research and work needed for Alabama. Closing this ticket for now, will create a new ticket and reference this one for any future work.
