### ISSUE TITLE
Rhode Island - Onboard to UP

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12107]
## Problem statement
Rhode Island has expressed interest in receiving more conditions than just COVID. As such, we want to learn what they want to receive and get them successfully added to the Universal Pipeline.

## What you need to know

- Rhode Island is already connected to ReportStream through the COVID pipeline
- TBD

**Comment by MikaelahD13** [comment]
Closing, work completed.
