### ISSUE TITLE
Metadata/linking improvements (link fixes, page titles, descriptions, etc)

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#12110]
## User story

As a ReportStream user, I want to have a useable useful site so that I can do my job.

## Background & context
We've IDed all links and surfaced some issues to solve like page titles and descriptions. This work will create solutions or a plan for that.

## Acceptance criteria
- [x] Problems to solve IDed alongside eng
- [x] Solutions created
- [x] Next steps planned as needed

**Comment by chris-kuryak** [comment]
@audreykwr please add the link to the content here in this ticket

**Comment by audreykwr** [comment]
Page titles and descriptions found on the meta data tab of [this sheet](https://docs.google.com/spreadsheets/d/1YiLtOr0NIIeuRYvxvox2r0L19U3bLagl9IFfHPH8yb8/edit#gid=529723033)

**Comment by audreykwr** [comment]
Closing. Content linked in the comment above.
