### ISSUE TITLE
Terminology audit for UP 

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#12113]
## User story

As a user, I want to know how ReportStream can help me so I can send or receive the data I need.

## Background & context

We need a more specific direction and framework for moving forward with communicating about the UP through piloting and slow onboarding this quarter and moving into full release in 2024.

While also looking at what content the user needs or is referencing, this highlights specific terms that could use more clarity and consistency across touchpoints.

## Open questions
- How many terms are important to clarify in this scope

## Working links

-[Strategy deck](https://docs.google.com/presentation/d/1GD8xfwZ7o_Vf1tFcTZaSCHenXmKOaIjHcmMrvI1J3AI/edit#slide=id.p)
- [Mural space](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1692893740765/fd049479f3c57af816d831eb7c132b4ad219b4c7?sender=uc55a7af3b66977fba12f5528)

## Acceptance criteria

-   [x] Key terms IDed along with any that need clarity
- [x] Change communication canvas updated as needed
- [ ] Update service blueprint with relevant learnings
-   [ ] Update the [questions pool](https://docs.google.com/spreadsheets/d/1THH9Ekj5renvIwSpl-6SzzyUJ5tuNcH76l4GTiboQXE/edit#gid=0) with any questions that came up
-   [ ] ...

**Comment by chris-kuryak** [comment]
@audreykwr please link to the document created

**Comment by audreykwr** [comment]
[Audit sheet](https://docs.google.com/spreadsheets/d/1Xch1N0iFw-i1FJFn1muY4OsqhpAa68kI-5UzQHrFL_Y/edit#gid=0) - not yet synthesized
