### ISSUE TITLE
Migrate the quick tests to be in Kotlin as part of a unit test integration suite

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#1214]
Currently the quick tests run as a separate shell script that is called manually by the developer.  We want to migrate these tests to run as unit tests, but as part of an integration suit and not with the current unit tests.  This integration test suite needs to be run from Gradle and as a separate step in the Github Actions build.

Acceptance criteria:
1. The quick tests run as unit tests in an integration test suite
2. The integration test suite is run from Gradle
3. The integration test suite is run as a separate step in the Github Actions build.

**Comment by MauriceReeves-usds** [comment]
@carlosfelix2 does this still need done?

@td-usds does this impact your building in the Docker container PR at all?

**Comment by td-usds** [comment]
> @td-usds does this impact your building in the Docker container PR at all?

Unlikely, any impact would be pretty minimal.
