### ISSUE TITLE
Audit exceptions to see what issues are currently triggering exceptions and pager duty alerts

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12147]
## Problem statement
We don't know all of the issues that are currently triggering exceptions and pager duty alerts

## What you need to know

Audit timeline: Last 30 days

## Acceptance criteria

- [x] Compile list of exceptions over the past 30 days
- [x] Capture list in a spreadsheet and link to the spreadsheet in this ticket

**Comment by penny-lischer** [comment]
Query to group exceptions in last 30 days

exceptions
    // additional filters can be applied here
    | where client_Type == "Browser"
    | where timestamp > ago(30d)
    | summarize Count=count() by type, tostring(customDimensions), client_Browser
    | order by Count
    | project Count, type, client_Browser, customDimensions

**Comment by penny-lischer** [comment]
[https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B282E6448-4489-4E72-8892-87D0FDE4E6BE%7D&file=Top_Exceptions_Last_30_Days.csv&action=default&mobileredirect=true](Top_Exceptions_Last_30_Days.csv)
