### ISSUE TITLE
Content Request: Remove Shared Secret Authentication Method from API guide

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12168]
_[Governance document](https://docs.google.com/document/d/1__FE0OGlVAby0m7QyKfo_Qr0Gh_PvALaA1_DeCJSjzQ/edit#heading=h.qyvn837dl01t) for content process reference_

**Is this new content or an edit to current content?**

- [x] **Edit**: It is not a change that affects the design or functionality of the page/feature.
- [ ] **New**: It is something new that is mostly content (not a tool).

**Questions for edit requests:**

1. Current page link:
- https://reportstream.cdc.gov/developer-resources/api/getting-started

2. Change requested:
- remove description and references to "Method 2: Shared Secret API Key" from the API Guide

3. Why is this change needed?
- RS engineering has expressed concern with using the Shared Secret Method for authentication for our users. As such, we want to remove it from the API guide and public facing materials so we are not advertising that we support it.

4. How urgent is this change and why?
- Not urgent

**Complete your request by:**

- [x] Making sure you’ve answered all questions for the appropriate request type (edit or new)
- [x] Labeling this ticket as `content request`, `design` and `experience`
- [x] Assigning this ticket to @audreykwr

_Thank you for contributing to content excellence for ReportStream!_

**Comment by audreykwr** [comment]
Content done [here](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/20231108_API_guide_content_updates.docx?d=wd696ca923bda402eb79f9202a0b409ea&csf=1&web=1&e=OX1g4C).

@GilmoreA6 can you give it a once over just to check I didn't misrepresent anything in the changes?

**Comment by chris-kuryak** [comment]
also tagging @arnejduranovic for awareness. Proposed content changes [here](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/20231108_API_guide_content_updates.docx?d=wd696ca923bda402eb79f9202a0b409ea&csf=1&web=1&e=OX1g4C)

**Comment by GilmoreA6** [comment]
I agree with removing it from the getting started pages and programmer's guide. We should however add a ticket to add the examples from this section to internal documentation (prime-reportstream/prime-router/docs/onboarding-users/senders.md)

**Comment by chris-kuryak** [comment]
Added #12254 to copy over those examples before they are removed.
