### ISSUE TITLE
Ensure that browser version compatibility does not trigger pager duty, but does still get logged as a warning

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12164]
## Problem statement
Browser version compatibility exceptions have been triggering on pager duty over the past month causing unnecessary time spent determining the issue. We no longer want those to trigger pager duty alerts.

## Acceptance criteria

- [x] Determine what to filter out (string-based match) for browser version compatibility issues
- [x] Send to Jeremy in DevOps with instructions on what we want to happen
- [x] Test that this no longer triggers Pager Duty

**Comment by penny-lischer** [comment]
@chris-kuryak 
1. Joseph added code that checks for minimum browser versions which will catch some of these issues. 

2. After looking at the Azure logs it may not be ideal to write a query to filter out browser version compatibility issues.
It seems better to only trigger pagerduty alerts for frontend if the same error has occurred for 3+ users within a certain time period. I am seeing if this is possible.

**Comment by penny-lischer** [comment]
@chris-kuryak here is the associated ticket from devops https://github.com/CDCgov/prime-reportstream/issues/12700

**Comment by penny-lischer** [comment]
Devops has a ticket for this [12700](https://github.com/CDCgov/prime-reportstream/issues/12700)

**Comment by chris-kuryak** [comment]
We have sent DevOps a list of acceptable browsers in Slack. They will be taking on the work from there.

**Comment by chris-kuryak** [comment]
Guidance sent to DevOps:

chrome >= 87
chrome mobile >= 87
firefox >= 78
firefox mobile >= 78
safari >= 14
ios (safari mobile) >= 14
edge >= 88

**Comment by chris-kuryak** [comment]
Still awaiting DevOps

**Comment by chris-kuryak** [comment]
According to Penny, no FE issues in weeks!
