### ISSUE TITLE
Investigate GHA for build hub

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#12185]
This is to see if we can determine what caused the PR to merge w/ a failing required test and how best to prevent it from happening again. It may be best to figure out how to remove the dummy workflow.

* Is it related to the dummy action
* Is it because an admin (Jeremy) approved the PR? `NO`
* Is it because the code was edited with the the in browser editor? `NO`
* Is it something else we're missing

[Some background](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks)

The specific workflow we are looking at is build_hub.yml/build_hub_dummy.yml

**Comment by snesm** [comment]
attempt to [reproduce](https://github.com/CDCgov/prime-reportstream/pull/12179)

**Comment by snesm** [comment]
bad [merge](https://github.com/CDCgov/prime-reportstream/pull/12075)

**Comment by snesm** [comment]
[reasoning](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks) behind the dummy workflows and workaround

**Comment by dkrylovsb** [comment]
We have two GHA files -- `build_hub.yml` and `build_hub_dummy.yml` -- both of which define workflows with the same name: `Build Hub`. These workflows trigger upon commits to mutually exclusive set of paths; however, if a PR includes changes to both sets of path (as [was](https://github.com/CDCgov/prime-reportstream/pull/12075) the case), both workflows will trigger.

In most cases this is not an issue. However, there is an apparent bug in GitHub that triggers when:
- auto merge is enabled for a PR
- Build Hub Dummy runs quickly and produces a `Success` while the "real" Build Hub is still building.

PR gets merged automatically in this case. We have reproduced this behavior [here](https://github.com/CDCgov/prime-reportstream/pull/12179). 

The best way to address is probably to remove the dummy workflow and use conditionals within the real workflow, but this would warrant a separate ticket.
