### ISSUE TITLE
Design "original message Passthrough" Universal Pipeline Feature

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#12224]
### User Story

As a Sender of HL7v2 to ReportStream who has my own data integrity requirements, I want ReportStream to not modify the message I send in any way so that the receiver can receive my message byte-for-byte the same way I sent it.

### Description/Use Case

In order to accommodate the use case above while retaining flexibility and the advantages of the Universal Pipeline, ReportStream should implement an "original message Passthrough" feature that is to be enabled via Sender settings. This setting can be called something like "send_original". If this setting is enabled, ReportStream will embed the original HL7v2 into the internal FHIR object during the translation in the `convert` step of the pipeline. Then, at the `translate` step, instead of translating the FHIR to HL7v2, the translate step will simply pull out the embedded HL7v2 from the FHIR object and send that along. Note, if this feature is enabled for a particular sender, then the message should:

- Not be batched with any other message.
- Have the same file name as the message that was received.

This ticket is to think through this use case and to elaborate on the design above and think through any edge cases or gaps. The design should be either documented in the repo or, if short, can be documented in the implementation ticket.

#### File name preservation request

ELIMS has also asked that the report we send to a receiver should have the same file name as the report we received from ELIMS. 

### Acceptance Criteria

- [ ] Design created for original message passthrough (if necessary)
- [ ] Implementation ticket created for original message passthrough which includes the design or a link to the design if a separate document

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12224?planning-poker) with Zenhub @arnejduranovic @jalbinson @JessicaWNava @jimmyfagan @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12224?planning-poker) with Zenhub @JFU-NAVA-PBC

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12224?planning-poker) with Zenhub @jsutantio @dylansmith-Nava
