### ISSUE TITLE
Improve the logging so when a sender/receiver transform fails the specific element is logged

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#12238]
### User Story
As a report stream developer, I would like to be able to diagnose what schema element prevent a receiver or sender transform from being successful.

### Description/Use Case
This is something that occasionally happen in PROD and it is extremely time consuming to track down what element is the issue as the log message contains on info.

We want to log at least the element and schema

### Acceptance Criteria
- [ ] Any exception generated when processing a schema element is caught and logged with details on the schema element that failed and then re-thrown

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12238?planning-poker) with Zenhub @arnejduranovic @jalbinson @JessicaWNava @jimmyfagan @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12238?planning-poker) with Zenhub @JFU-NAVA-PBC
