### ISSUE TITLE
NBS Server Resetting.

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#12230]
Hello Ott,

 We have prepared the latest test environment for data ingestion. You can access it at https://dataingestion.test.nbspreview.com. 
 Please integrate this environment with your staging environment. If you need to set up a quick call to discuss this further, let me know.
 Currently, we are still using basic authentication with a username and password, which I will provide below.
 Ingestion endpoint is still the same endpoint: https://dataingestion.test.nbspreview.com/api/reports

 Require Header info:
Content-Type: text/plain
msgType: HL7
validationActive: true

 Basic Auth info:
 Please see KeyBase's NBS credential

Thank you

Duc Nguyen
Backend Engineer

Enquizit, a CDW Company 

Public Health Investigation Tools Branch (proposed) 

Investigate and Respond Division (proposed)  

Office of Public Health Data, Surveillance, and Technology

**Comment by LaFreda1** [comment]
We met with NBS today 11/16/23. Ott will send them the collection by EOD tomorrow and if we need to revisit, LaFreda will reopen.
