### ISSUE TITLE
The ability to filter tests results based on the whether the test was an OTC or at home test

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#1225]
**Is your feature request related to a problem? Please describe.**
As part of the onboarding of OTC and at home tests from the new Waters sender, state may or may not want to receive these types of tests in their primary feed. And they may change their mind. 

**Describe the solution you'd like**
- The ability for each state to specify the types of test results they want
- The ability for each state to setup a secondary feed 
- Must be a setting
- Must be consistent with FDA test authorization guidelines

**Describe alternatives you've considered**

**Additional context**
This is part of wider discussion how to handle the new Waters test data

**Comment by jimduff-usds** [comment]
I'd like to be able to add `isNotOTC()` as part of our default qualityFilter (the default quality filter is currently hardcoded near the bottom of `JurisdictionalFilters.kt`).     Then, if a state wishes to receive a second "feed" with everything else, we can set up a second receiver that has the `reverseTheQualityFilter` flag set to true.   So, for that use case, the `isNotOTC() `juris filter is the most useful function.

For the use case where a state wants three feeds (case quality, otc, everything else), the `isOTC()` juris filter is needed.  In combination with some other cleverness with qualityFilters and juris Filters, three feeds can be created.

Lastly, I think there will definitely be states who want an isOTC column in their data - this would allow us to send a single file, and states can filter.   This would require an` isOTC` mapper that can create a YES/NO column, or something like that.

Note:   The validation checking on the LIVD values is mediocre right now, and needs to be improved (see Giang's test results here:  https://usds.slack.com/archives/C01SK0KGVGW/p1621977249051400) which means, at least for now, we need to deal with the case where the data is erroneous, and we can't use the LIVD table to determine OTCness.    Will need to decide if we default to OTC or not OTC.   I suggest not OTC, and lean on the other checks in the qualityFilter to throw out data that is missing key info.

Note 2:  There are remaining issues with the default quality filter as well:  1) its hardcoded, and 2) There needs to be a way to set it at the organizational level, so it can be re-used and extended (or reversed!) by individual receivers.    Neither of those features is done.
