### ISSUE TITLE
Examine HCI Test Messages Part 2

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#12257]
### User Story

As a sender to ReportStream, I want to ensure all my messages are transmitted to the appropriate sender losslessly. 

### Description/Use Case

We have received a set of [sample messages](https://cdc.sharepoint.com/:f:/r/teams/ReportStream/Shared%20Documents/HCI-ELR/sample-messages/[batch-11-15-23](https://cdc.sharepoint.com/:f:/r/teams/ReportStream/Shared%20Documents/HCI-ELR/sample-messages/batch-11-15-23?csf=1&web=1&e=nfyOvx)?csf=1&web=1&e=nfyOvx) from the sender. This folder includes:

- `moreSampleResults_20231115.txt` - the original file sent from the sender. This contains multiple HL7v2 messages pasted in a single file. The messages come in pairs, labelled "Original" and "Transformed". Original means the messages was sent by ProPhase to HCI, and Transformed means the message HCI received was updated to follow the HL7v2 NIST ELR spec and is what ReportStream will receive. The HL7v2 messages have been broken out of this file into their own separate files, labeled "prophase" and "hci" respectively. 
- `msg_<n>_<hci/prophase>.hl7` - a standalone HL7 message. RS should only have to process the messages from hci, the prophase ones are there for reference only.

We should run all the HCI messages through the pipeline and compare that the output message from RS is not missing any important data that exists in the input message. We should also document **any** differences between the input and output and fix them if it makes sense. All differences should be documented in a spreadsheet or file in the folder containing the sample messages

### Acceptance Criteria

- [ ] Messages processed. Differences documented and/or fixed.

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12257?planning-poker) with Zenhub @arnejduranovic @jalbinson @JessicaWNava @jimmyfagan @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12257?planning-poker) with Zenhub @JFU-NAVA-PBC

**Comment by JessicaWNava** [comment]
The msg_1_hci.hl7 message gets the following error when I submit it as is: Required field missing: A datatype for OBX-5 must be specified in OBX-2.

**Comment by JessicaWNava** [comment]
Differences documented here: https://docs.google.com/document/d/1i4dMY3NCZ5FSR9M4XUVjYOk5_OdqT1LhnnX6TP4VvC0/edit?usp=sharing
