### ISSUE TITLE
Oklahoma - Missing LOINC

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#12255]
## **Problem Statement**

We received an email in the RS Support inbox from the OK DOH, regarding a submission from ImageMover that is missing a LOINC code. This appears to be the same issue as #12212 for Kansas.

## **What you need to know**

Email received from OK:

> This is notification from the OSDH Acute Disease Service regarding a SpringML file submission. The file, CDC_PRIME_REPORTSTREAM_2023-11-14_15:54:35.094176-06:00.hl7, contains record(s) with no test performed code. Due to the missing data, these records have not been reported to the Oklahoma State Department of Health. The missing data for these records needs to be corrected and resubmitted as soon as possible. Your facility only needs to resubmit the records for the specimen IDs listed below; you do not need to resubmit all the records in the file. 
> 
> Specimen IDs missing OBX-3: ['`715bdb4c-416f-43d5-a812-d30347141ed2`'] 

## **Acceptance Criteria**

- [x] Determine the root cause of the data transmission issue and resolve accordingly.
- [x] Confirm resubmission of corrected file to OK

## **To Do**

- Investigate why this LOINC code does not appear to be transmitting appropriately
- Resubmit file from ImageMover

## **Additional Comments**

I was trying to obtain a copy of the original submission from ImageMover, but encountered some issues while accessing Azure. I'll attempt it again, but I have a few screenshots from Metabase and the RS Validation tool.

[Metabase LOINC](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2ZiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95764b392ffd89209060125aabdd83597936cd56/image.png)
[RS Data Validation response](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd25iQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cce81906809358466986a99d2c0f48c3514a0d7d/image.png)
[OK Routing Filters](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3ZiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a988d1670347325b2b90eb7220adb68717f495e7/image.png)

Could the routing filters have affected this?

**Comment by GilmoreA6** [comment]
email to tyler@imagemovermd.com:


Hi Tyler,

Hopefully you can help us or point me to the correct resource. We have received a number of recent files from ImageMover with an incorrect value in the deviceIdentifier and deviceName columns. Please see below for the incorrect values we have received and the correct values from the SARS CoV2 LIVD table https://www.cdc.gov/csels/dls/livd-codes.html


Received Values	Correct Values
deviceIdentifier	deviceName	deviceIdentifier
deviceName
Sofia Flu SARS Antigen FIA_Quidel Corporation
Sofia2 Flu + SARS Antigen FIA*	Sofia 2 Flu + SARS Antigen FIA_Quidel Corporation
Sofia 2 Flu + SARS Antigen FIA*


Could you help me get this information to the correct people on your end to fix the values we are receiving?

Thanks, Please let me know if I can provide any more information.

-James

James Gilmore
Senior HL7 Data Analyst
AgileSix
Public Health Data Transmission Branch ​
Detect and Monitor Division​
Office of Public Health Data, Surveillance, and Technology​
Centers for Disease Control and Prevention

**Comment by LaFreda1** [comment]
@GilmoreA6 Will you add the email response from image mover to this ticket? Thanks!

**Comment by GilmoreA6** [comment]
From Imagemover response 11/21/23:

"Hi James,

These changes have been made and we should be all set. Let me know if there are any issues!

Best,
Tyler"

**Comment by GilmoreA6** [comment]
Message resent to OK
