### ISSUE TITLE
Implement code to condition mapping

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#12275]
### User Story

As a sender of test results containing various conditions,
I want ReportStream to be able to route test results based on condition to receivers,
so I can meet by reporting requirements

### Description/Use Case

In order to be able to route messages based on condition, we first need to be able to stamp various observations in a message with the condition(s) they represent. The code to condition mapping [design](https://github.com/CDCgov/prime-reportstream/blob/5097e07acd10747c8cd2104c45bb986c29d623db/prime-router/docs/design/proposals/0023-condition-to-code-mapping/0023-condition-to-code-mapping.md#mapping-loincsnomed-codes-in-received-messagebundle-to-condition-code) discusses how to map test codes to condition codes in the internal FHIR resource. In short, this ticket should implement the code to condition stamping that is outlined in the design section titled `Mapping LOINC/SNOMED codes in received message/bundle to condition code`:
1. Update internal FHIR bundle observation resources with the appropriate condition code using a custom RS FHIR extension. If an observation is not a condition code, stamp it as "unknown" or "aoe"
    - Update action log when there is a failure to map an observation

This ticket shall implement the following sections of the design:
    - `Mapping LOINC/SNOMED codes in received message/bundle to condition code`
    - `Action Log Event`

All sections not in the list above are out of scope, including but not limited to:
    - `Filtering for condition`

Note, the design suggests where and how to implement code to condition mapping. This should be used as a guide and NOT as a hard requirement. We should implement code to condition mapping in a way that is most maintainable. This may mean refactoring current functionality.

### Acceptance Criteria

- [ ] ReportStream has the ability to stamp observations in the internal FHIR bundle with the condition it maps to
- [ ] ReportStream logs mapping failures
- [ ] Design documentation updated (if needed)

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12275?planning-poker) with Zenhub @arnejduranovic @jalbinson @JessicaWNava @jimmyfagan @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12275?planning-poker) with Zenhub @JFU-NAVA-PBC
