### ISSUE TITLE
Handle HL7v2.5.1 messages without logging any errors

### ISSUE THREAD

**Issue by jimmyfagan** [CDCgov/prime-reportstream#12287]
### User Story
As a ReportStream maintainer, I want error messages in the application output to be reflective of real errors, and not produce error output for valid and expected inputs.

### Description/Use Case
When we read incoming HL7v2 messages, we first try to read them as v2.7. If that fails, we will then fall back to read them as v2.5.1. This works fine functionally, however currently, the failure to read messages as v2.7 results in error messages in the application output. For example, OBX.2 is allowed to be `CE` in v2.5.1 but not in v2.7, so a message with OBX.2 of `CE` results in:
```
11:15:26.681 [pool-2-thread-87][263] ERROR gov.cdc.prime.router.fhirengine.utils.HL7Reader - Failed to parse message
.............
Caused by: ca.uhn.hl7v2.HL7Exception: 'CE' in record 1 is invalid for version 2.7 at OBX-2(0)
```
We should only log message parsing errors in cases where the message can be read as neither v2.7 nor v2.5.1.

### Risks/Impacts/Considerations
No known risks, though the risk of not fixing this is that the error messages will cause false alarms among developers.

### Acceptance Criteria
- [ ] HL7v2.5.1 messages which are not valid HL7v2.7 (because of OBX.2 of `CE` for example) can be sent through the Universal Pipeline without any error messages appearing

**Comment by arnejduranovic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12287?planning-poker) with Zenhub @brick-green @jack-h-wang @jalbinson @JFU-NAVA-PBC @mkalish @thetaurean @jimmyfagan @JessicaWNava
