### ISSUE TITLE
Integrate E2E tests to automatically trigger during Deployments

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12309]
## Problem statement
As we are creating these new E2E tests, we need to have them automatically triggered with deployment to serve their ultimate purpose.

## What you need to know

- #11307 has the list of pages we are targeting for E2E tests

## Acceptance criteria

- [x] All E2E tests (even those that have not been created) will be triggered for staging and production to run and provide success/failure output during a deployment.
- [ ] Work with devops to add a Github event to trigger the e2e to run on each build.
- [ ] Confirm that all expected E2E tests run during next deployment

*Note
We may want to run a group/suite of defined "smoke tests" at some point since this will slow down out builds.
We can then trigger a nightly run of all the e2e

**Comment by penny-lischer** [comment]
Blocked by #12307

**Comment by penny-lischer** [comment]
Working with Jeremy to have Devops get this triggered.

**Comment by penny-lischer** [comment]
Devops ticket - https://github.com/CDCgov/prime-reportstream/issues/12701

**Comment by penny-lischer** [comment]
Supriya is working on this.
