### ISSUE TITLE
Get access to Google Search Console for the ReportStream website

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12308]
## Problem statement
To help identify ways to improve the SEO of the ReportStream website, we should use Google Search Console. In order to user Google Search Console, we need to get access to the tool.

## What you need to know

- [Google Search Console](https://search.google.com/search-console/welcome?action=inspect&sjid=13732092635868753708-NC)
- From Etan: https://developers.google.com/search/docs/crawling-indexing/ask-google-to-recrawl?visit_id=638357794171378071-1975095206&rd=1#url_inspection

## Acceptance criteria
- [ ] Gain access to Google Search Console for ReportStream.CDC.Gov

**Comment by etanb** [comment]
Update: Supremely blocked by CDC Service Desk since this is entirely in their hands now. The only way to verify our site ownership is on a DNS level, since we're a subdomain. CDC Service Desk Ticket Number: INC0324967

**Comment by chris-kuryak** [comment]
Instruction/Answer has been given to CDC by Etan 4/2/2024
