### ISSUE TITLE
Modify REST Transport for NBS new REST Server.

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#12310]
## Problem statement

Make modifications to REST Transport and staging to allow RS to communicate to NBS Data Ingestion server.

**Ott,

 I did a bit of research on the content-length issue. It appears that you can omit the content-length and replace it with 'Transfer-Encoding: chunked.' I tested this with our DI environment, and it seems to resolve the issue with content-length. Please let me know whether this works or not from your end.

Thank you

Duc Nguyen
Backend Engineer

Enquizit, a CDW Company 

Public Health Investigation Tools Branch (proposed) 

Investigate and Respond Division (proposed)  

Office of Public Health Data, Surveillance, and Technology** 

## What you need to know

Ott will send Postman collection

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] Send postman collection

## To do

- [ ] ...

**Comment by oslynn** [comment]
Done
