### ISSUE TITLE
Idaho - Notice of Password Expiration 

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#12318]
## Problem statement

Automated email notifying of password expiration in 13 days. Need to change password before deadline.

## What you need to know

Tier 1 no longer has access to update password

## Acceptance criteria

Maurice Reeves,
The password for account: SimpleReport will expire in 13 days. Please change your password at your earliest convenience. Instructions for changing your password via FTP, SFTP, and HTTP/S are provided below for your convenience:
1. Please enter the following URL into your browser: https://sftp.dhw.idaho.gov/manageaccount
2. Supply your current password when prompted
3. Enter your new password and confirm
4. If approved, exit the browser and login as normal

## To do

Change password

**Comment by adegolier** [comment]
Finished this one just now, confirmed on RS side with the "check" function
