### ISSUE TITLE
build_hub workflow runs on updates to actions

### ISSUE THREAD

**Issue by snesm** [CDCgov/prime-reportstream#12322]
## Problem statement

.github/workflows/build_hub.yml runs the kotlin compile/test on PR's that update only actions (but not workflows).

## What you need to know

- [Example PR](https://github.com/CDCgov/prime-reportstream/pull/12319)
- [build_hub log](https://github.com/CDCgov/prime-reportstream/actions/runs/6932046670/job/18855122447?pr=12319)

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by dkrylovsb** [comment]
@snesm That is correct; the behavior is unique to `.github/actions/build-vars/action.yml`, since that particular action is a part of the overall Build Hub workflow. Here is the corresponding `filter`:
```        filters: |
          router:
            - 'prime-router/**'
            - 'operations/**'
            - '.github/actions/build-backend/action.yml'
            - '.github/actions/deploy-backend/action.yml'
            - '.github/actions/build-vars/action.yml'
            - '.github/workflows/build_hub.yml'```
