### ISSUE TITLE
Investigate clikt version upgrade issue

### ISSUE THREAD

**Issue by thetaurean** [CDCgov/prime-reportstream#12337]
### Description/Use Case
Dependabot #11603 is causing a myriad of compilation failures due to deprecated methods and updated message signatures. Investigate and resolve.

### Risks/Impacts/Considerations
This only impacts the CLI

### Dev Notes
- Adjust `throw printMessage()` usages to use named parameter `printError` instead of `error` or positional
- Replace usages of deprecated `confirm()` with `yesnoprompt`

### Acceptance Criteria
- Upgraded to latest version of `clikt` with no issues

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12337?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean
