### ISSUE TITLE
Get all Onboarding Engineers access to send test messages through the UP from SimpleReport

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12333]
## Problem statement
When migrating/onboarding receivers to the UP, engineers need to send test messages through the pipeline to the receiver to ensure connection and accuracy of data. Currently, only Victor has access to send test messages from SimpleReport through the UP. To augment our onboarding capability and remove Victor as a single point of failure, we need to get all onboarding engineers permissions to do this.

## Acceptance criteria

- [x] James has ability to send test messages from SR through the UP
- [x] Angela has ability to send test messages from SR through the UP
- [x] Ott has ability to send test messages from SR through the UP
- [ ] Process for how to send messages through the UP is documented in Github and linked in this ticket

**Comment by LaFreda1** [comment]
@GilmoreA6 Please confirm that you have access to send test messages through UP from SR. Thanks!

**Comment by GilmoreA6** [comment]
@LaFreda1 yes

**Comment by LaFreda1** [comment]
@victor-chaparro can we plan to get this documented soon and close this ticket?

**Comment by LaFreda1** [comment]
@victor-chaparro any updates on this?

**Comment by victor-chaparro** [comment]
Link to doc: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/onboarding-users/migrating-receivers.md#3-send-test-message-from-simplereport-to-stlt
