### ISSUE TITLE
[BUG] All Facilities and Providers page not loading for receivers

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12360]
## Problem statement
Similar to #12352, the All Facilities and Providers page is not loading for receivers, though it does load for Prime Admins.

## What you need to know
- See Penny's fix to #12352
- Tested with DHfl-phd and it did not work

## Acceptance criteria

- [ ] All Facilities and Providers page loads the table for an authenticated receiver

**Comment by penny-lischer** [comment]
@chris-kuryak this should be resolved from #12361

**Comment by chris-kuryak** [comment]
@penny-lischer Yep, I was just checking on that to ensure it was working.

All good!

Closing and removing the time estimate so we are not counting it towards this sprint.
