### ISSUE TITLE
Investigate and fix which endpoints may need to remove the activeMembership.service check

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12361]
## Problem statement
Similar to #12352, we saw that the logic used on the Data Dashboard was used on other endpoints as well. We need to check those endpoints to see if they are working properly on the pages that they appear.

## What you need to know
- See Penny's fix to #12352
- Endpoints to investigate:
  - useOrganizationSenders
  - useOrganizationPublicKeys
  - useSenderResource
  - useReceiverSubmitters (All Facilities and Providers Page)

## Acceptance criteria

- [x] Document where all of these endpoints are used
- [x] Confirm if those pages/features are working properly (logging in as a receiver or sender, not admin)
- [x] Communicate back to Product Manager (Chris) and Tech Lead (Victor) the findings
- [x] Remove the activeMembership.service check where applicable.

**Comment by penny-lischer** [comment]
useOrganizationSenders (Manage public key) -  activeMembership.service check can be removed
useOrganizationPublicKeys (Manage public key) -  activeMembership.service check can be removed
useSenderResource (Banner, Submission History) - Need to keep the activeMembership.service check when calling the endpoint.
useReceiverSubmitters (All Facilities and Providers Page) -  activeMembership.service check can be removed
