### ISSUE TITLE
Add Simple Report Sender transform for missing data

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#12402]
### User Story

As ReportStream, I want to add simple report sender transforms for missing fields, so that receivers can get data in the same format they've have been receiving it in the covid pipeline.

### Description/Use Case

We have compared a message generated from both the Covid and Universal pipelines and identified all the differences in this spreadsheet: https://docs.google.com/spreadsheets/d/197AeFMvozqUGRE1BuvOSMiUL_r2EEkyQv4l8D_OhhZk/edit#gid=492389121
All the fields that need action have been identified under the Remediation column. Most of this will be fixed by adding a sender transform or by contacting SR to include missing data.

### Acceptance Criteria

- [x] All fields that need remediation have been addressed
- [x] The fields listed in the spreadsheet are not different between the two pipelines
- [x] Integration tests pass

**Comment by chris-kuryak** [comment]
Reference #12768

**Comment by chris-kuryak** [comment]
Blocked by Platform work on Sender Transforms

**Comment by chris-kuryak** [comment]
Remaining fields need to be addressed by SR. They have been notified
