### ISSUE TITLE
Examine HCI Test Messages Part 3

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#12417]
### User Story
As a sender to ReportStream, I want to ensure all my messages are transmitted to the appropriate sender losslessly. 

### Description/Use Case
We should run all the HCI messages through the pipeline and compare that the output message from RS is not missing any important data that exists in the input message. We should also document **any** differences between the input and output and fix them if it makes sense. All differences should be documented in a spreadsheet or file in the folder containing the sample messages

### Acceptance Criteria
- [ ] Messages processed. Differences documented and/or fixed.

**Comment by arnejduranovic** [comment]
Waiting on HCI to update messages to pass NIST

**Comment by MichaelEsuruoso** [comment]
Do we need to keep this item open ?
