### ISSUE TITLE
Add additional attributes to receiver - external name

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-reportstream#1241]

**Comment by MauriceReeves-usds** [comment]
@jlusds - What is the intent here?

**Comment by jlusds** [comment]
I thought we wanted to add an external name so it could be referenced in the download site, e.g. "Primary", "Secondary"

@drew-usds for his thoughts

**Comment by Bisonburger** [comment]
Since the name is only used internally - can we not use the name field to be the external name?  Why use both?

**Comment by jlusds** [comment]
I think there our internal name may not be externally understandable. I dont think we need this unless/until we expose a name in the design.

**Comment by jimduff-usds** [comment]
I think an external name would be helpful.
