### ISSUE TITLE
PA MUSER accounts password update

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#12419]
## Problem statement
Muser password update for 2 accounts, Tier 1 access still pending... similar to #12318 

## What you need to know

Dear RptStreamSewsprod,

Your Password for MUSER will expire in 5 days.
Access Change Password ( edcpwdmgr.pa.gov ) to change your MUSER password.

Dear pareportstream,
Your Password for MUSER will expire in 5 days.
Access Change Password ( edcpwdmgr.pa.gov ) to change your MUSER password.

- [Document 1](https://...)
- [Document 2](https://...)
- ...
## Acceptance criteria

- [ ] ...

## To do

- Update password for both RptStreamSewsprod and pareportstream before Friday Dec. 1 2023

**Comment by adegolier** [comment]
Just got done with this one with Tanea
