### ISSUE TITLE
Investigate why Bundle.deleteResource uses so much memory and update the implementation

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#12427]
### User Story
As a report stream developer, I would like to avoid memory intensive bundle operations. 

### Description/Use Case
As part of updating the routing step, it was discovered that Bundle.deleteResources uses and holds onto a lot of memory such that it was causing OOM errors in the CI runner.  This was mitigated by upping the the heap size, but the method is self should be refactored.

### Dev Notes
There are likely a few low hanging changing items to look at:

- The recursive function [allocates memory](https://github.com/CDCgov/prime-reportstream/blob/3c5e4a3b224707549100a3c2a9f736b69fca5efa/prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt#L104) for the same data at each recursive step
- Reduce the amount of recursive calls
- This was only produced during the CI build

### Acceptance Criteria
- [ ] The settings to increase the heap size for the tests is removed

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12427?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean
