### ISSUE TITLE
Document the advantages and process for migrating to the new version of Okta

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12436]
## Problem statement

Okta is moving from a "Classic version" to their new "Identity version". We are currently on the Classic version. We assume that they will eventually stop supporting the Classic version. Additionally, we think that the Identity version will have some added benefits/features that we can take advantage of. Therefore, we need to do some research to determine the benefits and timeline of moving from the Classic version to the new Identity version.

## What you need to know
- ...

## Acceptance criteria

- [ ] Document the potential benefits/features we could take advantage of in the new version of Okta
- [ ] Determine if/when they will stop supporting the old version of Okta and add to the document
- [ ] Document the process and timeline for migrating to the new version of Okta
- [ ] Document any contingencies/issues that could arise when migrating to the new version of Okta
- [ ] Link documentation in this ticket

**Comment by jpandersen87** [comment]
https://docs.google.com/document/d/1f-WW5GegB_QCRrBYrgg82_ZByFmP3AephyKWKoazxfY/edit?usp=sharing

**Comment by chris-kuryak** [comment]
Currently, no timeline for deprecation of Okta Classic
