### ISSUE TITLE
Update message serialization to use JSON rather than custom format

### ISSUE THREAD

**Issue by jalbinson** [CDCgov/prime-reportstream#12461]
### User Story
As a developer, I should easily be able to add new messages and fields to messages in Azure queue. We should be serializing messages to JSON using libraries rather than our custom format which could potentially be prone to errors.

Going between Kotlin data classes and JSON Strings is a solved problem with libraries we already use (Jaskson) in other areas of code. We should be using best practices around that.

### Description/Use Case
Messages pushed to the Azure queue are just required to be a string. We should outsource serialization/deserialization to libraries.

For the current implementation see all implementations of the abstract function `toQueueMessage` here: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/azure/Event.kt#L19

### Risks/Impacts/Considerations
We could disrupt the existing queue during deploy. We need to have code that handles it the existing way but pushes all new messages in the new format.

### Dev Notes
You can inherit from the abstract [Message](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/fhirengine/engine/Message.kt) to create your new message types. If that is not possible please follow the pattern being used by the `Message` type.

### Acceptance Criteria
- Messages pushed to Azure queue are serialized to json (and base64 encoded but I believe that happens outside the context of this ticket)
- Deploy should not break existing messages already present in the Azure queue
- Unit tests

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12461?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by JFU-NAVA-PBC** [comment]
some out of AC notes:

the messages jsonized currently does not contain the report id associated, so, to correlate the messages to a report, it counts on the action log record (a DB table), down the road the json events ingested to analytical tool might need further enrichment at ingesting time....
