### ISSUE TITLE
Enable Distributed Logging

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#12466]
**Description**
It appears that log4j messages are not appearing in Azure App Insights (just exceptions and then azure function/trace things like request events), I think we may need to enable "Distributed tracing for Java applications" as documented here: https://learn.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions#distributed-tracing-for-java-applications but I do not see this option in azure? In the screenshot it looks like a "Preview" feature? Do we need to contact Microsoft for help here?

**Specific Requested resources**
https://learn.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions#distributed-tracing-for-java-applications

**Additional Context**
The Platform team is looking into expanding ReportStream's logging capabilities. Ultimately, we would like to be able to send custom events and customDimmensions to azure, I think the issue outlined here is the first step towards that goal.

**Comment by supriyaaddagada** [comment]
https://logging.apache.org/log4j/2.x/manual/configuration.html#Additivity
Arnej had confirmed that warnings, errors from log4j are already getting logged in the application insights, logging level needs to be adjusted in the code to get the trace and debug levels logged

https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/resources/log4j2.xml

Arnej mentioned that they are good for now and this ticket can be closed. Arnej's team will reopen or create a new one once they start looking into this on their side
