### ISSUE TITLE
Web receiver needs to intake Display Flag and External name

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-reportstream#1246]
Goal
Web receiver need to know whether to show a file or not, and if its shown, what to show

Gated on https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-data-hub/1242 and https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-data-hub/1241

**Comment by mry-usds** [comment]
Initial demo created using tabs and filtering with the REPORT_FILE table's receivingOrgSvc 
[demo found here](https://bisonworks.awsapps.com/workdocs/index.html#/share/document/c9bc558e54265d1ec444b35ed7fe20838b2385273ec43d59dca641191b71b0a9)

**Comment by jlusds** [comment]
Can't access
________________________________

**Comment by mry-usds** [comment]
Seems to be having a problem with AWS console - try here

https://drive.google.com/file/d/1Tray3LLd1xw4efosfteKufvieB9yvKcj/view?usp=sharing

**Comment by jlusds** [comment]
@mry-usds to check blocking ticket (should be done)
