### ISSUE TITLE
Update design of web receiver to support secondary feed

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-reportstream#1247]
@drew-usds to design, then @mry-usds to build

**Comment by jlusds** [comment]
Per discussion, I think there was interest in a tabbed format.

I personally think this is a lot like Gmail. There is primary inbox that the user will use 95% of the time, and secondary inbox that users will use 5% of time.

**Comment by mry-usds** [comment]
But - flip side, there may be some cause to have a single table that's filterable (checkboxes, etc.)

**Comment by jlusds** [comment]
Also would work. I think the default view should not​ show data outside the primary feed, though that should be filterable and perhaps down the line, on by default through some type of settings
________________________________

**Comment by jlusds** [comment]
Duplicate of OTC front end. Re-look at designs when we launch data volume.
