### ISSUE TITLE
Develop 1 pager for OTC/quality filter product

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-reportstream#1249]
Figure out 1 pager that can be attached to an email to describe the primary and secondary feeds and the quality options

**Comment by BerniXiongA6** [comment]
@jlusds  Here's my feedback/suggested edits for the Data Configuration One-pager (attached):

[https://app.zenhub.com/files/304423150/9ab32105-b533-40f4-a422-e29fd47ba34b/download](https://app.zenhub.com/files/304423150/9ab32105-b533-40f4-a422-e29fd47ba34b/download)

Any questions, let me know!

**Comment by jlusds** [comment]
Thanks!

Updated the Patient section to : "Patient Information: Name, DOB, Administrative Sex, Address, Contact Information "


What did you have in mind for  screenshots? Right now it is more of a backend data filter

**Comment by BerniXiongA6** [comment]
@jlusds I guess if there's no front-end view of this data filtering, then you don't need any screenshots.

**Comment by jlusds** [comment]
Sprint summary: complete
