### ISSUE TITLE
Connect local dev environment Log4j logs to Demo Environment's App Insights

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#12495]
### User Story

As a ReportStream engineer implementing Application Insights improvements, I want to test configuration changes on my local dev environment so that I do not have to merge changes to master to see if my changes worked on staging.

### Description/Use Case

DevOps is working on enabling [distributed tracing](https://learn.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions#distributed-tracing-for-java-applications ) for the apps running in azure. At the same time, platform team should look into how to set up distributed tracing locally (this ticket) so we can test subsequent tickets belonging to #12458 without having to merge to master.

### Dev Notes

> Note: These dev notes include the understandings coming out of the initial investigation required to create this ticket. All claims should be investigated and independently verified. An alternate route should be proposed if the acceptance criteria cannot be met by following the dev notes.

This ticket will have the two main parts:
1. Connect local dev environment to one of the demo application App Insights. 
2. Enable distributed tracing. 

Both of these seem to be accomplished by [running Microsoft's OpenTelemetry .jar as an agent](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-enable?tabs=aspnetcore). This will probably require changes to the docker scripts, which run the application locally. See the documentation for [configuring a Java application for application insights](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config).

This [overview document](https://learn.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions) is a good start for getting up to speed on azure functions integration with application insights and verifying these dev notes (which you should do). ReportStream already has a basic integration with Application Insights and, as discussed in the aforementioned document, the java agent is needed to get the full benefits of the integration. Integrating the [OpenTelemetry](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-overview?tabs=aspnetcore) jar will allow ReportStream to send custom metrics, events, and structured logs to Application Insights, greatly increasing the usability and helpfulness of it.

For testing or troubleshooting, contact Arnej for CURL command to send app insights data to staging env from command line.

### Acceptance Criteria

- [x] When running the application locally, all traces, exceptions, and logs (including log4j logs) go to a demo environment's Application Insights
- [x] Documentation created on how to configure local app to connect to demo environment app insights

**Comment by jalbinson** [comment]
https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Platform/Observability/local%20dev%20observability%20setup.docx?d=w741e7f376c30475281d04496ee8db7a2&csf=1&web=1&e=wbxrIG
