### ISSUE TITLE
Engagement Sprint 83 retro action items

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#12518]
## Problem statement

This epic details the action items that the engagement team will complete for Sprint 83.

## What you need to know
Tickets of this epic are the items to be completed for Sprint 83. 

## Acceptance criteria

- [ ] Engagement team members to complete their to-do items within this epic during sprint 83.

## To do

- [ ] ...

**Comment by MikaelahD13** [comment]
Closing, work completed.
