### ISSUE TITLE
Chris and Victor retro action items

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#12519]
## Problem statement

This ticket details the retro action items for Chris and Victor to complete during Sprint 83.

## Acceptance criteria

- [ ] Complete all to-do items in the ticket and fill the checkbox on easyretro. 

## To do

- [x] Victor and Chris to sync on Patrick on who is responsible for dependabots, deployments, etc
- [x] Chris and Victor setting more clear roadmap for FE work this quarter.
- [ ] Chris and Victor to lead up the discussions with DevOps on the issues that crop up and developing an SOP on how to review/solve them.
- [ ] Victor and Chris need to sync with Platform and DevOps on the queues that are not being monitored, and should they be monitored and by whom (James to lend insight if needed)

**Comment by chris-kuryak** [comment]
We have filled out the roadmap for FE for the rest of this quarter, but want to get their feedback on if it meets their needs.

**Comment by chris-kuryak** [comment]
Would like to check with team on 

> Chris and Victor to lead up the discussions with DevOps on the issues that crop up and developing an SOP on how to review/solve them.

to see if we still need to address this issue

**Comment by chris-kuryak** [comment]
> Victor and Chris need to sync with Platform and DevOps on the queues that are not being monitored, and should they be monitored and by whom (James to lend insight if needed)

Chris to confirm in the engineering Slack channel. But we think this is currently being monitored:
- All steps of the CP and UP are being monitored
- If a message fails a step, it goes into a queue to get automatically retried
- If a message fails multiple times, it goes into a poison queue
- If a message goes into the poison queue, it automatically triggers a PagerDuty alert to whomever is on call

**Comment by MikaelahD13** [comment]
Closing due to updated ticket #15006
