### ISSUE TITLE
IL UP Onboarding Validate Test Data

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#12524]
## Problem statement

As a developer, I want to compare the messages generated from the Covid and Universal pipelines, so that I can successfully onboard Illinois to the UP

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
Duplicate. Closing
