### ISSUE TITLE
Virgin Islands Onboarding - Build Receiver Settings

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#12536]
### Acceptance Criteria 
- [x] Added to organization.yml and created yamlitos  
    - [x] Customer status = testing  
- [x] Added to prod settings table  
    - [x] Added quality filter = allowNone() 
- [x] Added to staging settings table  
    - [x] Added quality filter = allowNone() 

### To Do 
- [x] RS engineer: update this ticket with comments with every interaction with receiver 
- [x] RS team member who originates this ticket: add any dependencies, as needed 
- [x] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [x] Pipelines: Onboarding & Operations (New) 
     - [x] Labels: "Onboarding-ops" and "Receiver" and state label 
     - [x] Epics: [select the epic for this API onboarding sender]

**Comment by chris-kuryak** [comment]
Blocked by mapping (Sender Transforms) work from Platform.
