### ISSUE TITLE
Covid Pipeline Sender Audit

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12533]
## Problem statement
The overall migration strategy involves migrating all senders from the CP to the UP.

To help determine a strategy and timeline for sender migration, we need to know how many senders we have and some of their defining characteristics.

## What you need to know
- A lot of this information may already exist in Smartsheet, but unsure where

## Scope
- All senders currently connected to the COVID pipeline

## Acceptance criteria

- [x] List of all existing CP senders (and total number documented)
- [x] Existing sender format (as specific as possible)
- [x] Non-standard HL7 (per engineering definition) senders marked as such
- [x] Number of results sent in the past 3 months by each sender
- [x] Which STLTs they have sent data to ever (if possible to know)
- [x] Other conditions that the sender is capable of sending (not including)

## To do

- [x] Check with Victor to see if any other information would be useful to know for each sender

**Comment by jakefishbein-navapbc** [comment]
[WIP List](https://docs.google.com/spreadsheets/d/1GerMI0hKSRK5svbcNzScUBHb5zJImLOixTpBOZXOdvU/edit#gid=1816532064)

**Comment by jakefishbein-navapbc** [comment]
Met with Victor and identified additional complexities in migrating senders. Will need to validate each senders message via NIST to determine HL7 variations.

**Comment by jakefishbein-navapbc** [comment]
Additional conditions is not a realistic additions as many senders are not directly conducting the testing.

**Comment by jakefishbein-navapbc** [comment]
[Audit sheet](https://docs.google.com/spreadsheets/d/1GerMI0hKSRK5svbcNzScUBHb5zJImLOixTpBOZXOdvU/edit#gid=443493841)

**Comment by jakefishbein-navapbc** [comment]
The audit sheet has been updated with results from passing sample messages from each relevant sender through the NIST ELR validation tool. None of these senders' messages passed validation.
