### ISSUE TITLE
Research: Document how to add an existing COVID pipeline HL7 Sender to the UP

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12532]
## Problem statement
The overall migration strategy involves migrating all senders from the CP to the UP.

In order to determine a reliable strategy for migrating COVID senders to the UP, we need to know the process and requirements for successfully adding an existing HL7 Sender to the UP.

## What you need to know
- Jessica and Dylan(?) should have some documentation on what has happened with HCI/Prophase

## Scope
- Existing and previous UP HL7 sender onboarding initiatives (for example, HCI/Prophase)

## Acceptance criteria

- [x] Determine what is required from the RS team for adding a CP HL7 sender to the UP
- [ ] Determine what is required from the CP HL7 sender perspective for being added to the UP
- [ ] Determine potential timeline and constraints for adding an existing CP HL7 sender to the UP
- [x] Determine areas that may need further investigation
- [x] Findings documented
- [ ] Reviewed with Product and Engineering for alignment

## To do

- [ ] ...

**Comment by jakefishbein-navapbc** [comment]
[In process research doc](https://docs.google.com/document/d/1gyFszhQ7aV9i7-z3nBmy8sLYLXr_uU9Y-HfJSDFEDQQ/edit)
