### ISSUE TITLE
Initial ETOR documentation research

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12543]
## Problem statement
The ETOR initiative can benefit from having some documentation created that would help onboard ETOR users. The existing onboarding documentation has caused some issues for ETOR users (according to the Flexion team).

## What you need to know

- Dylan S. is already working on researching the ETOR landscape and personas
- Adrian Brewster is a former RS teammate and needs to be consulted on his knowledge regarding ETOR onboarding documentation
- The Flexion team (which is leading the ETOR pilot project) needs to be consulted to determine the user needs

## Acceptance criteria

- [x] Meet with Dylan S.
- [x] Meet with Adrian Brewster
- [x] Schedule time with the Flexion team (likely after the holiday) to learn more about the user needs
- [x] Document findings

**Comment by audreykwr** [comment]
Findings captured alongside API guide audit work [here](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/20231219_API_guide_audit.docx?d=w83adabaa40354233a8fd79bab6c8d075&csf=1&web=1&e=hV6d9p)

Specific notes related to ETOR:
- Seemed unclear on best location for documentation and brand relationship status. Are they “ReportStream” users?
- ETOR requires significantly more validation
- Intake form also has some things that don’t make sense in the ETOR context
- While focused on NBS, ETOR team concerned with creating something that scales beyond that specific use case. 
- Received their edited copy of the guide they are using right now
- Will created ticket to track needed updates that their team notices
