### ISSUE TITLE
Collect STLT reportable conditions and reportable test results/LOINC codes

### ISSUE THREAD

**Issue by dylansmith-Nava** [CDCgov/prime-reportstream#12542]
### User Story
As a developer on RS, I want to know find out reportable conditions per STLT (and any further details about test results/LOINC codes), so I can better prepare to route messages based on condition.

### Description/Use Case
The pipeline team is already implementing a solution to route messages to STLTs based on condition. Once the UP can read a message and know what condition(s) it contains, the message will be sent to STLTs that accept that condition. We will need to know, as a next step, which STLT(s) accept which condition(s).

As an example, do we know all of the STLTs that accept flu results? And for further specificity, which STLTs accept positive and/or negative flu results? What are those specific LOINC codes that are accepted?

### Open Questions
- Which database(s) might this information live in?
- Which condition(s) are accepted by all STLTs?
- Which condition test result(s) are accepted by all STLTs?
- Which STLTs accept OTC data? What specific OTC LOINC codes will they accept?

### Risks/Impacts/Considerations
- ReportStream will not need to comprehensively know STLT condition reporting until we onboard that specific STLT
- STLT reportable conditions (and more specifically, reportable LOINC codes) will change too rapidly to capture these datapoints in the short term

**Links**
- [12275](https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/12275): Implement code-to-condition mapping

### Acceptance Criteria
- [ ] Log 15 STLT condition reporting requirements
- [ ] Log 30 STLT condition reporting requirements
- [ ] Log 45 STLT condition reporting requirements
- [ ] Log all STLT condition reporting requirements
- [ ] Add test result / LOINC code details for 15 STLTs

**Comment by dylansmith-Nava** [comment]
**Ticket housekeeping!**

@arnejduranovic have other people already made progress on the ACs in this ticket, or are they stale? I can update them or move this ticket to 'Done' as needed. cc @Andrey-Glazkv

**Comment by arnejduranovic** [comment]
> **Ticket housekeeping!**
> 
> @arnejduranovic have other people already made progress on the ACs in this ticket, or are they stale? I can update them or move this ticket to 'Done' as needed. cc @Andrey-Glazkv

@dylansmith-Nava I'm not sure we have answers to any of the open questions documented anywhere? Also, I think this would require working with engagement team, so maybe check with their researchers?

**Comment by dylansmith-Nava** [comment]
@arnejduranovic sounds good. I'll also see if it would make more sense then to pair with / or ask an Engagement designer to take on this work.

**Comment by dylansmith-Nava** [comment]
Based on the conversation with @chris-kuryak and @arnejduranovic in Slack, if an engineer wants to know which STLTs currently accept which condition(s), they can either look at the routing rules, or get access to SmartSheet via the Engagement team. As such, the ACs are not relevant -- a list like that is "impossible to maintain" and not necessary to find "reportable conditions per STLT". As such, I will close this ticket. Thank you! cc @Andrey-Glazkv
