### ISSUE TITLE
Move creation of ObjectMapper to JacksonMapperUtilities or companion objects

### ISSUE THREAD

**Issue by jalbinson** [CDCgov/prime-reportstream#12554]
### User Story
Instantiating an `ObjectMapper` is a pretty heavy operation that should only occur once per configuration. We should hold onto the few ObjectMappers we need rather than creating new ones on the fly all over the codebase.

ObjectMappers are completely thread-safe and do not need to instantiated per read/write.

### Risks/Impacts/Considerations
Using the wrong mapper in the initial spot which could cause problems serializing/deserializing.

### Dev Notes
Look for the following calls:
```kotlin
ObjectMapper()
jacksonObjectMapper()
jacksonMapperBuilder()
```

If you are using a plain json mapper use the existing  one in `JacksonMapperUtilities`.

We should add a default configuration for a YAML `ObjectMapper` in `JacksonMapperUtilities` and use it wherever default YAML parsing is needed.

Mappers created in companion objects are generally the best option if the code you are working with needs a custom configuration. 

### Acceptance Criteria
- New default YAML `ObjectMapper`
- Fewer instantiations of `ObjectMapper` and depending on the existing ones in `JacksonMapperUtilities`.
- Custom `ObjectMapper` in companion object or investigate if the custom one is really necessary

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12554?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by arnejduranovic** [comment]
Does this include updating tests to follow these new guidelines?
