### ISSUE TITLE
Build the app in a Docker container

### ISSUE THREAD

**Issue by ronaldheft-usds** [CDCgov/prime-reportstream#1256]
- Current builds are done directly on a dev machine (or CI) and requires a specific development environment configuration: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting_started.md#developer-workstation-setup
- For consistency between builds, we should be able to build the `prime` CLI jar and the Docker container created from the Gradle build through a Docker container
- Before going down this path too far, a proposal should be written and discussed at our weekly engineer sync

**Comment by td-usds** [comment]
The purpose of this is to provide a standardized, reproducible environment in which we build. This is not about producing containers as output of the build and instead is about _using_ containers during the build. This will ensure consistency in the produced artifacts (and make it easier to have an environment in which you can perform a build).

Secondly, as per #1012, it'd be great if all of this is neatly integrated with our current build system (Gradle) in such a way that any of the dependant (as opposed to dependent) container is spun up automatically when you initiate a build.

**Comment by ronaldheft-usds** [comment]
> The purpose of this is to provide a standardized, reproducible environment in which we build. This is not about producing containers as output of the build and instead is about _using_ containers during the build. This will ensure consistency in the produced artifacts (and make it easier to have an environment in which you can perform a build).
> 
> Secondly, as per #1012, it'd be great if all of this is neatly integrated with our current build system (Gradle) in such a way that any of the dependant (as opposed to dependent) container is spun up automatically when you initiate a build.

Yes, exactly!

**Comment by carlosfelix2** [comment]
@ronaldheft-usds Can you please clarify the use cases for this issue?  What would this container be used for?
1. Do you want to run the DEV build in a container when running in Github Actions?  
2. Do you want to run the RELEASE build in a container when running in Github Actions?
3. For developers, what is the use case for building within the container?
4. Any other use cases?

**Comment by ronaldheft-usds** [comment]
> @ronaldheft-usds Can you please clarify the use cases for this issue? What would this container be used for?
> 
> 1. Do you want to run the DEV build in a container when running in Github Actions?

Yes, the goal is to have the local dev builds and CI builds run on 100% the same configuration.

> 2. Do you want to run the RELEASE build in a container when running in Github Actions?

Yes, the same as above.

> 3. For developers, what is the use case for building within the container?

The use case is to ease onboarding to the project and ensure consistency between platforms. By building through a container, it doesn't matter the underlying OS configuration or dependencies installed. We can ensure all builds run the same way and automate away potential issues during the build, like settings secrets, etc.

> 4. Any other use cases?

The goal is to have a build process that is drop-dead simple for any engineer to run on any platform.
