### ISSUE TITLE
Implement Receiver FHIR Enrichment

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#12570]
### User Story

As an onboarding engineer,
I need the ability to alter data in a message according to a specific receiver's requirements,
so that I can ensure ReportStream is sending data to STLTs that are accepted by their system(s).

### Description/Use Case

The UP FHIR Pipeline has been updated to reflect the updated architecture of the translate function, as seen below. This design aims to decouple "enrichments" from "translations", recognizing they are different and adhering to the single responsibility principle. Furthermore, this design pushes all, or most, data-related enrichments to be done via FHIR transforms.

![Screenshot 2023-12-08 at 10 30 30 AM](https://github.com/CDCgov/prime-reportstream/assets/118766341/41ed8eab-7ad1-426f-a6fd-e1cabe688518)

This ticket aims to implement the paths shown in the diagram above. Furthermore, FHIR Enrichment (FHIR transforms) are already implemented in the translate step (as part of the `receive -> FHIR Enrichment -> dispatch` path, so the feature is already done, it just needs to be plugged in to the translate function as shown in the diagram.

Another way to summarize this ticket is: Enable the execution of a receiver-specified FHIR transform before running the receiver-specified format translation (like FHIR -> HL7v2)

### Dev Notes

A note on setting implications:

Presently, the convert step and translation step both share the same translation parameter, named "schemaName". Since we are now distinguishing between "enrichments" and "translations", we need a new setting. So, the current proposal is:
1. We are going to leave `schemaName` and use this setting in the convert step as well as in the translate step when enriching the FHIR
2. Create a new setting named `enrichmentSchemaName` and use this setting to enrich the FHIR before converting it to its final format and running the schema on it. 
3. Investigate the UI on website for setting schemas and see how this impacts the front end. Will need to contact engagement team with suggestions on improvements on that end.

`NOTE: `We may not want to change the schemaName param due to deployment complications. The pros and cons should be weighed and discussed. - Decision after grooming conversation was to leave the schemaName param as it. 

### Acceptance Criteria
- [ ] Design review with team as a huddle or 17th prior to implementation
- [ ] Receiver FHIR transforms implemented as depicted by the diagram
- [ ] Convert step updated to use new FHIR enrichment setting
- [ ] Rollout plan for staging and production

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12570?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by victor-chaparro** [comment]
Should we store the FHIR bundle after we do enrichments in the Blob store. In case we need to debug these transforms?

**Comment by arnejduranovic** [comment]
> Should we store the FHIR bundle after we do enrichments in the Blob store. In case we need to debug these transforms?

I think this is a good idea but I think it should be a separate ticket. Presently, in the convert step, we don't do this (we translate from HL7v2 to FHIR and then enrich with FHIR transform). This ticket is to basically do the same in the translate step, just the order is reversed (FHIR transform first then conversion). Whatever solution we come up for helping with traceability and debug-ability for the different conversions/translations should be applied evenly where it applies. Thoughts?

**Comment by victor-chaparro** [comment]
That sounds good to me and  yes we should also do this when applying sender transforms.

**Comment by arnejduranovic** [comment]
Created story for Victor's suggestion here: #12668
