### ISSUE TITLE
Further remove mock-fuel package

### ISSUE THREAD

**Issue by JFU-NAVA-PBC** [CDCgov/prime-reportstream#12597]
## Describe the bug
It is noticed that "mock-fuel" package is still included in testImplementation of build.gradle.kts
it needs to be removed

## Impact on ReportStream
No

## Steps to reproduce
1. Check report stream repo to local
2. check build.gradle.kts
3. Search "mock-fuel"

under ./prime-router, ran:
grep -r "fuel" .

you will see:

`./build.gradle.kts:            includeModule("com.github.KennethWussmann", "mock-fuel")
./build.gradle.kts:    implementation("com.github.kittinunf.fuel:fuel:2.3.1") {
./build.gradle.kts:    implementation("com.github.kittinunf.fuel:fuel-json:2.3.1")
./build.gradle.kts:    runtimeOnly("com.github.kittinunf.fuel:fuel-jackson:2.3.1")
./build.gradle.kts:    testImplementation("com.github.KennethWussmann:mock-fuel:1.3.0") {
./build.gradle.kts:        exclude(group = "com.github.kittinunf.fuel", module = "fuel")
./build.gradle.kts:    // kotlinx-coroutines-core is needed by mock-fuel
./build.gradle.kts:    testImplementation("com.github.KennethWussmann:mock-fuel:1.3.0")`

## Resources
If applicable, add screenshots, links, etc to help explain your problem.

## Logs
If applicable, please attach logs to help describe your problem.

## Additional context
Add any other historical context about the problem here.

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12597?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by arnejduranovic** [comment]
I could not find any references to fuel, this must've been resolved at some point.
