### ISSUE TITLE
Clean up legacy code using the old message type. (Not QueueMessage)

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#12614]
### User Story
As a report stream developer, I would like to remove deprecated legacy code

### Description/Use Case
As a part of putting a message on the queue in the JSON format, we had to leave in the old code so that anything still in the queue upon deployment could still be sent. 

### Dev Notes
The spots that need to be clean are marked with the ticket

### Acceptance Criteria
- [ ] Old code paths and related tests are removed

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12614?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by JessicaWNava** [comment]
JSON serialization didn't make the build today and we won't be releasing next week, so this will need to wait until after the 1/2/24 build to be merged.
