### ISSUE TITLE
Create fake Sender and Receiver orgs for E2E testing on Authenticated pages in Staging

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12636]
## Acceptance criteria

- [ ] "Dummy" Sender org with fake data created for E2E in Staging
- [ ] "Dummy" Receiver org with fake data created for E2E in Staging
- [ ] Document accordingly

**Comment by penny-lischer** [comment]
We may be able to use the Ignore organization in staging which is used for testing. We would just need to create a user and assign them that org.

**Comment by chris-kuryak** [comment]
@penny-lischer, I would confirm with @arnejduranovic or @victor-chaparro if that previous comment is a question.

**Comment by penny-lischer** [comment]
@victor-chaparro would one org used by both a sender and receiver be ok?

**Comment by chris-kuryak** [comment]
Looks like we are only going to use the Ignore org. No need to create new orgs.
