### ISSUE TITLE
Create Sender, Receiver, and Prime Admin accounts for E2E testing on Authenticated pages

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12635]
## Problem statement
In order to test authenticated pages, we need test accounts for Sender, Receiver, and Prime Admin

## Acceptance criteria

- [x] "Dummy" Sender Okta account created for E2E in Staging
- [x] "Dummy" Receiver Okta account created for E2E in Staging
- [x] "Dummy" Prime Admin Okta account created for E2E in Staging
- [x] Connect Dummy accounts to E2E test(s)
- [x] Store login credentials for these accounts in designated (safe, secure) location

**Comment by chris-kuryak** [comment]
Created a spike #12990 to develop a solution to this problem before moving forward

**Comment by penny-lischer** [comment]
Created the following Google Group:
reportstreamtesting@googlegroups.com

Created the following users in OKTA: 
reportstreamtesting+admin@googlegroups.com
reportstreamtesting+sender@googlegroups.com
reportstreamtesting+receiver@googlegroups.com
