### ISSUE TITLE
add 373121007,  'Test not done' to the covid-19/test_result valueset.

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1264]
This task is to add 373121007,  'Test not done' to the covid-19/test_result valueset.    It was used by one of our senders, but doesn't appear in that valueset.   

For you, or Pablo or even @joemeree if he wants to do the change, test, and submit a PR.

**Comment by tlosbo** [comment]
Pablo will be handling this one
