### ISSUE TITLE
Document FHIR->FHIR transform capabilities via tests

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#12640]
### User Story

As a developer on ReportStream writing FHIR->FHIR transforms,
I want to refer to automated tests that document the different features of FHIR->FHIR transforms,
so that I can understand the full extent of the FHIR-FHIR transforms.

### Description/Use Case

We should document the different features and capabilities of the FHIR->FHIR transforms for other developers to reference. A good way to do this is to write tests that test specific features or capabilities of the transforms. As we add new features to the transforms, we should write new tests. 

### Acceptance Criteria

- [ ] Features of FHIR->FHIR transforms understood and documented via test

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12640?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by arnejduranovic** [comment]
This was handled as part of #15169
