### ISSUE TITLE
Nevada - UP Migration-Receiver Translation Settings

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#12693]
### User Story:
As a developer, I want to set up Nevada receiver setting settings in the UP, so that they can receive data in the format they expect.

### Description/Use Case
Nevada is already receiving data from the covid pipeline they will be onboarded to the UP where they will be receiving data from SimpleReport including Covid, Flu and RSV. We need to make sure the message we generate from the UP matches the Covid pipeline message.

### Dev Notes:

- To migrate the Covid translation settings start by looking at their current translation settings. If the receiver uses  any of the following settings you will need to create a receiver schema:
	- receivingApplicationName
	- receivingApplicationOID
	- receivingFacilityName
	- receivingFacilityOID
	- messageProfileId
	- replaceValue
	- replaceValueAwithB
	- reportingFacilityName
	- reportingFacilityId
    - reportingFacilityIdType
    - suppressQstForAoe: true
    - suppressHl7Fields
    - suppressAoe: true
    - defaultAoeToUnknown
    - replaceUnicodeWithAscii
    - useBlankInsteadOfUnknown
    - usePid14ForPatientEmail: true
    - suppressNonNPI
    - replaceDiiWithOid
    - useOrderingFacilityName not STANDARD
    - nameFormat not STANDARD
    - receivingOrganization
    - stripInvalidCharsRegex
    
   - More documentation on how to set-up these transforms in the UP will be provided, but for now you can look for examples on how to set this up in either the NY-receiver-transforms or CA-receiver-transforms

- If the receiver uses any of those transforms you will need to create a receiver transform under `metadata/hl7_mapping/receivers/STLTs/` and update the receiver settings to point to this schema.

- After migrating the receiver setting to the UP. Send another test message using the postman collection or feel free to use the PrimeCLI to test the sender and receiver transforms using this command:
`./prime fhirdata --input-file {PATH TO INPUT FILE} -s metadata/fhir_transforms/senders/SimpleReport/simple-report-sender-transform.yml --output-format HL7 -r metadata/hl7_mapping/receivers/STLTs/{RECEIVER SCHEMA} --output-file {PATH TO OUTPUT FILE}`

- Compare the two messages again and document if there are any differences between the two messages. If there are review them with the team. We will probably need to ask the sender to add missing data or add a sender transform.

- If there are no major differences we can move on to sending test messages to the STLTs staging environment.

### Acceptance Criteria 
- [ ] Migrated  Covid receiver translation settings to the UP receiver settings
- [ ] Successfully generated a message with migrated UP receiver settings
- [ ] Compared messages from the covid and universal pipelines and documented differences

**Comment by GilmoreA6** [comment]
Initial test data found no errors.. Next step to send entire test plan through staging

**Comment by GilmoreA6** [comment]
Good morning,

James - I've run the test message through our Test environment and all is good. Awaiting next steps or the upcoming meeting today @ 1PM/PT, 4PM/ET.

Kevin - In case you want to review in EMSA Test, see Original Message ID#5485.

Thank you, 

Karen

**Comment by GilmoreA6** [comment]
-From NV-DOH

Hi James,

Confirming receipt and all tests were successful, see details below.

Please proceed with next steps to send 3-5 Production data to the Production SFTP folder. Once that's done, please let me know those Accession#s and I will review and provide feedback.
