### ISSUE TITLE
Nevada - UP Migration - Validate Test Data

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#12694]
### User Story:
As a developer, I want the Nevada to validate test messages in staging, so that they can receive data in the format they expect.

### Description/Use Case
Nevada is already receiving data from the covid pipeline they will be onboarded to the UP where they will be receiving data from SimpleReport including Covid, Flu and RSV. We need to make sure the message we generate from the UP passes the STLTs validation. We can use SimpleReport to submit test messages to the STLT.

### Dev Notes:

- [ ] Upload the newly created receiver settings to Staging
- [ ] Copy the receiver's secret key with the new receiver name in Azure's staging environment
- [ ] Verify we can connect to the newly created receiver
- [ ] Send a test message through Simple Report and make sure it gets routed to the STLT
- [ ] Send test messages according to the STLT needs

### Acceptance Criteria 
- [ ] Created and sent data using Simple Report
- [ ] Confirmed with STLT that data passes validation

**Comment by chris-kuryak** [comment]
NV is onboarded.
