### ISSUE TITLE
BUG: Fix the FhirTransformer conversion error. 

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#12702]
### User Story
As a ReportStream engineer I want the code to not consistently throw errors.

### Description/Use Case
When running a message through the pipeline, we are now consistently seeing errors like 
15:23:27.591 [pool-2-thread-17][40] ERROR gov.cdc.prime.router.fhirengine.translation.hl7.FhirTransformer - Conversion between boolean and boolean|dateTime not yet implemented.

This was introduced in this pr https://github.com/CDCgov/prime-reportstream/pull/12560 for context. 

### Dev Notes
It is believed that this is coming from using [x] on the bundleProperty and the conversion library doesn't know what type it is, but if we don't set the [x] the library can't find the property

ex. - name: sr-patient-deceased-indicator-default
  condition: '%resource.deceased.exists().not()'
  resource: 'Bundle.entry.resource.ofType(Patient)'
  bundleProperty: '%resource.deceased[x]'
  value: [ 'false' ]

### Acceptance Criteria
- [ ] These piped | cases are handled without an exception being thrown.

**Comment by arnejduranovic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12702?planning-poker) with Zenhub @brick-green @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean
