### ISSUE TITLE
Enrich log messages with searchable context

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#12722]
### User Story

As an engineer debugging the universal pipeline,
I want to be able to filter events (like trace or custom events) based on the report_id and message_id they are associated with,
so that I can quickly identify the problem.

### Description/Use Case

When a report is received by RS, RS assigns it a unique report_id. The next pipeline step that runs, convert, will generate one or more reports with new report_ids and the other steps will do the same until ultimately a report gets sent to a receiver. When debugging issues, it would be really helpful to filter log messages and events in azure logs by the report_id they are associated with. Special consideration should be paid to parent or child ids. To store all the info, we could decorate log messages with the following two searchable fields:
- `report_id` - the current reports id
- `submitted_report_id `- single value that has the id of the report that was originally submitted
- `parent_report_ids` - list of all reports this is a child of (report lineage in other words). Should be ordered.

Each report RS receives either contains a piece of data inside each item that is known as a "message_id", which is supposed to be a unique ID (like UUID) that identifies a message as unique. This will be unknown at the receive step, but will be known from the convert step on, and should decorate log messages and events where possible.

### Dev Notes

A popular way to enrich log messages with context is the [MDC pattern](https://www.baeldung.com/mdc-in-log4j-2-logback). Kotlin specific info can be found [here](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-slf4j/kotlinx.coroutines.slf4j/-m-d-c-context/). If we go this route, we need to make sure that these values will be searchable in Azure logs. If not, we may need to investigate how we can enrich trace messages with queryable key:value pairs using azure libraries.

### Acceptance Criteria

- [ ] Pattern for enriching log messages is designed and documented
- [ ] All log messages contain the report_id they are associated with, if applicable
- [ ] All log messages contain the message_id they are associated with, if applicable

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12722?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12722?planning-poker) with Zenhub @brick-green
