### ISSUE TITLE
Add a step in Receivers.md to ping the server before whitelisting

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12720]
Addition brought up in 16th min

**Comment by chris-kuryak** [comment]
Part of documentation PR
@victor-chaparro add link to PR

**Comment by victor-chaparro** [comment]
Link to doc: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/onboarding-users/migrating-receivers.md#how-to-check-if-stlt-needs-to-be-whitelisted
