### ISSUE TITLE
Design and clean up how to handle different specs

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#12752]
### User Story
As a report stream user, I would like to be able to specify different specs (HL7 2.5.1 vs 2.7 and FHIR R4) for how to translate my results.

### Description/Use Case
Currently, the mappings handles 100% HAPI HL7 2.7 -> FHIR R4 -> HAPI HL7 2.7 and other specs are all handled to some degree of fidelity (i.e. HAPI FHIR 2.7 almost entirely lines up with NIST ELR 2.5.1).  ReportStream needs a comprehensive plan on how to support using different specs.

### Dev Notes
- There is an ignored test case that highlights the difficulty in handling this. 
- `test converts with CE for obx2`

### Acceptance Criteria
- [ ] The HAPI HL7 2.7 is compared and differences noted with the NIST ELR 2.5.1
- [ ] A design is created for how the hl7v2 converter could handle going from multiple HL7 specs to different FHIR specs
  - [ ] Concrete use could be going from the Caristix 2.5.1 HL7 to FHIR R4
- [ ] The FHIR -> HL7 library has a design of how to go from different FHIR specs to different HL7 specs
  - [ ]  Concrete use would be going to HL7 2.5.1
- [ ]  A design exists for how to create new HAPI HL7 structures to handle different sender/receiver requirements

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12752?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean
