### ISSUE TITLE
Create Q&A doc that teams can reference during calls/emails with STLTs

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12779]
## Problem statement

Many internal team members have direct contact (email or phonecall) with our receivers (STLTs). A useful asset for to ensure our comms are accurate would be to create a Q&A doc that teams can reference during their outreach to users.

## What you need to know

- ...

## Acceptance criteria

- [ ] Create a Q&A doc that teams can reference during calls/emails with STLTs
- [ ] Review and share document with Support and Onboarding team members

## To do

- [ ] ...

**Comment by audreykwr** [comment]
Complete and approved [here](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/20240104_UP_internal_question_reference.docx?d=w665e1dc026054446884ffcffc5ff2f7c&csf=1&web=1&e=4kjJHw)
