### ISSUE TITLE
Remove more mentions of "Shared Secret" Auth Method from ReportStream website and PDF API Guide

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12777]
## Problem statement
There were a few other mentions of the Shared Secret Auth Method that were not removed in our last cleanup. We no longer want to publicly advertise the Shared Secret auth method for onboarding our users.

## What you need to know

- TBD

## Acceptance criteria

- [x] Update content on website API Guide 
- [x] Update content on PDF API Guide
- [x] Work with Product Mgr to create follow-on engineering ticket

**Comment by audreykwr** [comment]
@chris-kuryak - ready for follow on eng. Doc outlining updates [here](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/20240104_API_guide_content_updates.docx?d=w04b5779f7bbc4c2a8a5c8735a267f88c&csf=1&web=1&e=ILOZ5x).

**Comment by chris-kuryak** [comment]
Follow on ticket created #12875
