### ISSUE TITLE
Develop Comms to CSV Receivers to determine their capability/need

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12780]
## Problem statement

There are several receivers currently on the CP that use the CSV download feature.
The UP does not have CSV download capability.
Therefore, we need to reach out to them to determine their capability and needs so we can develop a plan for how to accommodate them in the future.

## What you need to know

- Current CSV Download receivers are cities/counties:
  - ca-sbc-phd
  - ca-scc-phd
  - co-routt-county-phd
  - co-san-juan-basin-phd
  - fl-hillsborough-phd
  - oh-ccchd-doh
  - pa-chester-phd
  - pa-montgomery-phd
  - pa-philadelphia-phd
  - pima-az-phd

- We likely need to determine:
  - if they still desire CSV download or if they are already getting their data elsewhere
  - if they can accept an ELR connection
  - do they want to remain connected to RS and why
  - 

[Link to plan document](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/2024103_CSV_STLT_outreach.docx?d=w06b13d2d0ce045b3b1f44d3bbde75f93&csf=1&web=1&e=GnsXgK)

## Acceptance criteria

- [ ] Create comms to CSV receivers to identify their capability and needs for receiving data in the future

## To do

- [ ] ...

**Comment by audreykwr** [comment]
Doc complete and approved [here](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/2024103_CSV_STLT_outreach.docx?d=w06b13d2d0ce045b3b1f44d3bbde75f93&csf=1&web=1&e=CGCHfa)
