### ISSUE TITLE
Audit existing Sender and Receiver Transforms in CP

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12803]
## Problem statement
The end goal is to have a standard operating procedure for creating transforms on the UP, which ones should be Sender vs Receiver, and how to make that determination.

First, we need to start with creating a list of existing Sender and Receiver Transforms in the CP.

## What you need to know
- 

## Acceptance criteria

- [ ] List of all Sender and Receiver transforms in the CP

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
@victor-chaparro Link to your audit

**Comment by victor-chaparro** [comment]
https://cdc.sharepoint.com/:x:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BD2E90368-621D-40A0-B4F3-F7B73170F4A4%7D&file=Transform%20Audit.xlsx&action=default&mobileredirect=true
