### ISSUE TITLE
[SPIKE] Research and define solution for refactor and remove hard code from REST transport

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#12802]
## Problem statement

[Write a short description of what you want to achieve with this task]

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] Proposal for design/solution
- [ ] Review with Victor

## To do

- [ ] ...

**Comment by oslynn** [comment]
All of URL hard codes are moved out to the RESTTransport setting.  Next, I am working on architecting code to be a single responsibility such as separating a single class into two classes.  1.) Sending Class.  2.) Authentication class.

**Comment by chris-kuryak** [comment]
After discussion with Victor, seems like we can make improvements to REST transport on an as-needed basis as new Senders/Receivers join ReportStream.

So we will close this issue for now.
