### ISSUE TITLE
Research user needs from a permissions perspective

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12812]
## Problem statement
The needs of users on ReportStream have changed since our first implementation of the CP. In particular, the way that we handle permissions on our application no longer meets the needs of our users. As we move our users over to the UP, we need to evaluate the needs of our users from a permissions perspective so that we can develop a better solution.

## Goal
Develop research to help answer the question:
"What is a permissions structure/architecture that will better meet the needs of our users."

## What you need to know
- Currently, we divide users into 3 categories: Senders, Receivers, and Prime Admins, with one flat level of access for each user type
- As we move into the UP, we have already identified that some of our users (ETOR folks) are both senders and receivers, which is a construct that is not currently supported in our application
- If helpful, here is the existing [Okta permission research](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/doc.aspx?sourcedoc=%7Bdc6c7f93-ba7c-4a43-9b5b-c91135016b1f%7D&action=edit) that has already been completed
- For Backend architecture of how we handle permissions, go to Arnej and ask who is the best
- For Okta related stuff, go to Joseph (or Chris if Joseph is not available)
- For FE website related permissions, go to Joseph or Penny
- For ELIMs info, start with Arnej
- For ETOR info, start with Dylan, and then go to Ott

## Scope
- Existing external senders and receivers (external users)
- Internal users (including support team, onboarding folks, front end, back end)
- (stretch goal) consider prospective future users

## Out of Scope
- Permission access pathways (passwords, 2FA, biometrics)
- Not how they access it, as much as what they need to access

## Acceptance criteria
- [ ] Document (or link to) our existing technical architecture for how we handle application permissions
- [x] Document existing user types and permission levels
- [x] Document how RS manages access to those permission levels
- [x] Identify all the user types (internal and external) using the UP (thinking a little into the future of potential user types as well)
- [x] Identify the permission needs of each user type
- [ ] (time permitting) Develop proposal for how to improve our permissions

**Comment by jakefishbein-navapbc** [comment]
Research completed and shared with team. Waiting for feedback to set as complete.

**Comment by jakefishbein-navapbc** [comment]
Making revisions based on initial feedback and questions.
