### ISSUE TITLE
Allow senders to specify original filename via API header

### ISSUE THREAD

**Issue by jack-h-wang** [CDCgov/prime-reportstream#12813]
### User Story
As a sender, I want to specify the original filename for a submission, so that this information can be sent to receiving organizations.

### Description/Use Case
When receiving reports, there is currently no field to receive a filename for the submission. Add an API header through which this information can be conveyed, and store the information in the database.

### Risks/Impacts/Considerations
Ensure that there is no change in function for senders who do not provide an original filename.

### Dev Notes
- Make certain stakeholders have agreed on a header to use to provide the filename under. A possible suggestion is to use `Content-Disposition` with value `filename=<filename>`
- The `report_file` database table has an existing `external_name` column. Consider adding a similar database column to store the original filename.

### Acceptance Criteria
- [ ] A new header is added to the API to allow senders to specify an original filename.
- [ ] If an original filename is provided, it must be stored.

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12813?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by jack-h-wang** [comment]
In working on this I discovered the reports API already accepts a filename via the `payloadname` header or query parameter. Testing this shows the existing functionality already meets the acceptance criteria for this issue; if a sender provides `payloadname` it is stored in the database in both the `action` and `report_file` tables in the `external_name` column. I will push a PR to update the design for the original passthrough feature accordingly.
