### ISSUE TITLE
UP updates to Developer Resources page

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#12842]
## Problem statement

The UP change communication strategy IDed ways we can updated and leverage the Developer Resources page more to help our users as the product transitions.

## What you need to know

- ...

## Acceptance criteria

- [x] Page updates drafted, reviewed, and approved by content owner
- [ ] Next step planned (Content handed off to eng or design as necessary)

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@chris-kuryak @jillian-hammer FYI

**Comment by audreykwr** [comment]
[Doc approved](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/20240104_developer_resource_content_updates.docx?d=w116dde0b4b274996ad15113fca58a552&csf=1&web=1&e=CpslFk) and ready for eng ticket @chris-kuryak

**Comment by chris-kuryak** [comment]
#12970 is follow-on ticket
