### ISSUE TITLE
UP updates to referral guide page

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#12843]
## Problem statement

The UP change communication strategy IDed changes needed to the referral guide page. Specifically, how we encourage STLTs to refer senders is affected by an adjustment in our pace of onboarding senders compared to pre-UP migration.

## What you need to know

- ...

## Acceptance criteria

- [x] Page updates drafted, reviewed, and approved by content owner
- [ ] Next step planned (Content handed off to eng or design as necessary)

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@chris-kuryak @jillian-hammer FYI

**Comment by audreykwr** [comment]
[Doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/20240104_referral_guide_content_updates.docx?d=w341eafa22ab0465aa7e9db8598d7fda0&csf=1&web=1&e=WlPM7K) complete and approved. Ready for eng ticket @chris-kuryak

**Comment by chris-kuryak** [comment]
#12970 is follow-on ticket
