### ISSUE TITLE
UP updates to Managing your connection page

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#12845]
## Problem statement

The UP change communication strategy IDed changes needed to the Managing your connection page, particularly around dashboard references.

## What you need to know

- This may be bumped based on dashboard decision dependencies. It depends on the scope of updates possible that would make a difference with what we know now.

## Acceptance criteria

- [ ] Page updates drafted, reviewed, and approved by content owner
- [ ] Next step planned (Content handed off to eng or design as necessary)

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@chris-kuryak @jillian-hammer FYI

**Comment by chris-kuryak** [comment]
Looks good

**Comment by chris-kuryak** [comment]
Make a followup ticket for later this quarter
