### ISSUE TITLE
UP updates to Our Network page

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#12844]
## Problem statement

The UP change communication strategy IDed changes needed to the Our Network page. We have an additional complication of not all senders sending all conditions.

## What you need to know

- This may be bumped after initial exploration of need and possibilities. 
- One hypothesis is that we will just feature SimpleReport more prominently and clearly.

## Acceptance criteria

- [ ] Page updates drafted, reviewed, and approved by content owner
- [ ] Next step planned (Content handed off to eng or design as necessary)

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@chris-kuryak @jillian-hammer FYI

**Comment by audreykwr** [comment]
@chris-kuryak 
[Doc approved here](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/20240104_our_network_content_updates.docx?d=w1571bd58ae274ad28453c915d10644e2&csf=1&web=1&e=LmYcKI)

So we just need a follow ticket for eng

**Comment by chris-kuryak** [comment]
#12970 is follow-on ticket
