### ISSUE TITLE
Research STLTS that are not connected, develop plan

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12852]
## Problem statement
There are still some of the 64 ELC-funded STLTs that are not connected to ReportStream.

## Goals
- The OKR for the year is connect all 64 ELC-funded by the end of the FY (Oct 2024)
- The goal for this quarter (FY24Q2) is to create a plan that we can execute in the next 2 quarters.

**Comment by MikaelahD13** [comment]
Closing, work completed.
