### ISSUE TITLE
Add SOAP Transport functionality to the "Check" feature in organization receiver settings on admin panel

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12872]
## Problem statement
The "Check" feature does not work with receivers that use SOAP as a transport mechanism.

## What you need to know
- ...

## Acceptance criteria

- [ ] "Check" feature successfully tests connection for receivers that use SOAP transport in staging
- [ ] "Check" feature successfully tests connection for receivers that use SOAP transport in production
- [ ] Test the feature with a SOAP transport receiver in staging and production

**Comment by oslynn** [comment]
There are only two SLTLs that use SOAP Transport.  They don't want us to keep checking their server alive since it will degrade their server performance.  Therefore, we will not include the checking feature for SOAP STLTs.  I am closing the ticket.
