### ISSUE TITLE
Investigate the deleteResource function not deleting orphaned resources

### ISSUE THREAD

**Issue by thetaurean** [CDCgov/prime-reportstream#12888]
### User Story
As ReportStream I want to ensure orphaned resources are removed from a bundle so that irrelevant data is not sent to receivers.

### Description/Use Case
While implementing tests for #12279, potential gaps were discovered in the `deleteResource` bundle helper; some types of orphaned resources are not removed from the bundle and instead just get nulled out. This was observed with  a `MedicationRequest` referencing an observation and at least one other type.

See dev notes for test code which demonstrates the issue.

### Dev Notes
Here's a test you can add to `FHIRBundleHelpersTests.kt` to trigger an example
```kotlin
    @Test
    fun `test filterMappedObservations`() {
        val fhirRecord = File(VALID_ROUTING_DATA_URL).readText()
        val bundle = FhirContext.forR4().newJsonParser().parseResource(Bundle::class.java, fhirRecord)
        bundle.getObservations()[0].code.coding[0].addExtension(
            conditionCodeExtensionURL, Coding("SOMESYSTEM", "840539006", "SOMECONDITION")
        )

        val refResource = MedicationRequest()
        val entryComponent = Bundle.BundleEntryComponent()
        refResource.id = "MedicationRequest/123"
        refResource.addBasedOn(Reference(bundle.getObservations()[1].idBase))
        entryComponent.resource = refResource
        bundle.addEntry(entryComponent)

        val filteredBundle = bundle.filterMappedObservations(
            listOf(CodeStringConditionFilter("840539006"))
        )

        val filteredObservations = filteredBundle.getObservations()

        println(filteredBundle.entry.map { it.resource }.filterIsInstance<MedicationRequest>())

        assertThat(filteredObservations.size).isEqualTo(1)
        assertThat(filteredObservations[0].id).isEqualTo("Observation/1667861767955966000.f3f94c27-e225-4aac-b6f5-2750f45dac4f")
        assertThat(filteredBundle.entry.map { it.resource }.filterIsInstance<MedicationRequest>().none {
            it.id == "MedicationRequest/123"
        }).isTrue()
    }
```

### Acceptance Criteria
- Orphaned resources are removed from a bundle or we understand & document  which/why aren't

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12888?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12888?planning-poker) with Zenhub @brick-green

**Comment by JessicaWNava** [comment]
This seems like a bug, so do we not point it?

**Comment by Andrey-Glazkv** [comment]
@thetaurean to work on this from design/research perspective

**Comment by Andrey-Glazkv** [comment]
@arnejduranovic to get together with @jsutantio and @dylansmith-Nava to talk about design part of this one

**Comment by arnejduranovic** [comment]
Will be resolved by https://github.com/CDCgov/prime-reportstream/issues/14568
