### ISSUE TITLE
Assign preview images to ReportStream website pages

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#12889]
## Problem statement

When the link to the ReportStream website is shared, we do not specify what the image preview should be. This ticket captures the work of assessing our available image assets and assigning image assets to pages/URLs.

## What you need to know

- Sharepoint folder: [Image assets](https://cdc.sharepoint.com/:f:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/01_WebDesign/Assets?csf=1&web=1&e=efc4mG)

## Acceptance criteria

- [x] ReportStream webpages and their image preview are clearly documented for engineering implementation

**Comment by audreykwr** [comment]
I just used [the sheet we used for the metadata](https://docs.google.com/spreadsheets/d/1YiLtOr0NIIeuRYvxvox2r0L19U3bLagl9IFfHPH8yb8/edit#gid=529723033) and added a link to asset from the linked folder in this ticket. I can move it if necessary though! Should be good to close I think. @chris-kuryak
