### ISSUE TITLE
Use service design pattern for code-to-condition lookups

### ISSUE THREAD

**Issue by thetaurean** [CDCgov/prime-reportstream#12906]
### User Story
As a dev I want blocking data retrieval to be wrapped in a service design pattern
so that data retrieval is reusable, failure methods are well defined, and business logic stays decoupled and isolated.

### Description/Use Case
The lookup of condition codes from the `observation-mapping` table is currently a rudimentary function call and lookup in a data structure. This should be wrapped into a service and use the appropriate design pattern.

### Acceptance Criteria
- `observation-mapping` table data is accessed using a service design pattern

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12906?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12906?planning-poker) with Zenhub @brick-green
