### ISSUE TITLE
Verify that the HL7->FHIR->HL7 mappings correctly handle all repeatable HL7 fields

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#12901]
### User Story
As a HL7 sender, I would like all repeatable HL7 fields to be correctly translated.

### Description/Use Case
Some fields in the HL7 spec are repeatable and require special handling when getting translated.

### Dev Notes
- Many of these fields are already covered so a lot of the work is just double checking
- There are cases where a repeatable field in HL7 is mapped to a FHIR property with a cardinality of 1.  `obx-observation-method` is an example of how to solve for this

### Acceptance Criteria
- [ ] All implemented mappings are checked for handling repeats correctly and anywhere they aren't the mapping is fixed
  - [ ] This should also include checking that empty values are handled correctly, i.e. `~1^Value` where the first value is empty

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12901?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12901?planning-poker) with Zenhub @brick-green
