### ISSUE TITLE
Lower urgency of auto-scaling events

### ISSUE THREAD

**Issue by ronaldheft-usds** [CDCgov/prime-reportstream#1290]
These should not trigger a page on PagerDuty.

**Comment by ronaldheft-usds** [comment]
Added an Event Rule to lower the severity of auto-scaling events:

<img width="1473" alt="Screen Shot 2021-06-11 at 4 16 57 PM" src="https://user-images.githubusercontent.com/52176593/121744196-8e0a9a80-cad0-11eb-9ee3-4b7a04d376d2.png">

**Comment by ronaldheft-usds** [comment]
@jimduff-usds @RickHawesUSDS Would one of you second this configuration and approach?

**Comment by jimduff-usds** [comment]
I second this!

**Comment by RickHawesUSDS** [comment]
Agreed.
