### ISSUE TITLE
Clean up the extensions that were created as part of the HL7 -> FHIR mappings inventory

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#12905]
### User Story
As a FHIR sender, I would like to be able to understand how I can add extensions to my FHIR bundle to have it deterministically converted to HL7

### Description/Use Case
This ticket should involve cleaning up the extensions (i.e. removing ones that serve the same purpose) so that we would be in a position to write up documentation that could be shared with a sender.

### Acceptance Criteria
- [ ] Extensions that serve the same purpose are de-duplicated
- [ ] Extensions follow a consistent naming pattern
- [ ] The extensions exist in manner that could be easily conveyed to a sender in terms of how they would add extensions to deterministically create HL7

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12905?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12905?planning-poker) with Zenhub @brick-green
