### ISSUE TITLE
Virgin Islands Onboarding - Validate Prod Data

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#12915]
### Acceptance Criteria 
- [x] Sent production data 
- [ ] Confirmed with STLT that data passes validation 

### To Do 
- [x] RS engineer: update this ticket with comments with every interaction with receiver 
- [x] RS team member who originates this ticket: add any dependencies, as needed 
- [x] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [x] Pipelines: Onboarding & Operations (New) 
     - [x] Labels: "Onboarding-ops" and "Receiver" and state label 
     - [x] Epics: [select the epic for this API onboarding sender]

**Comment by GilmoreA6** [comment]
Waiting for Inductive Health to introduce splitter logic for multiplex tests on their end:  "Good afternoon all,

 

I did review the last batch of labs we received and structurally everything looks good on my end.  For the panel results that include the Flu, Covid, and RSV results we are working on adding these to a splitter.

 

 

Regards,


Zachary"

**Comment by GilmoreA6** [comment]
Hi All,

I was hoping to get some recent prod data to test by our meeting tomorrow, but doesn't look like that is the case. I would suggest that we cancel our check in for tomorrow and I will let everyone know when we have some prod data to test unless there are any objections?

Thanks,

James

**Comment by GilmoreA6** [comment]
communication from Zach Donathan at Inductive Health

"Good afternoon James,

 

I was planning to touch base with you shortly regarding this topic.  Let’s plan for the cutover to production for tomorrow,  I need to take care of a few backend items for this and will reach out once this is completed with action items for your side of things. 

Would this work for you?"

**Comment by GilmoreA6** [comment]
response to Zach 

"Hi Zach,

No problem, 

The cutover will only take me a few minutes once we are notified. Also, just want to verify that the filepath will be ."/production"?

Thanks,

James"

**Comment by GilmoreA6** [comment]
Response from Zach 

"
Good afternoon James,

 

The filepath will be /incoming/prod/ in the SFTP account.  When I make the cutover and send out our standard email, it will be listed in that notification as well for your reference. 

 

Regards,

Zachary"

**Comment by chris-kuryak** [comment]
Will likely close today.

**Comment by GilmoreA6** [comment]
VI went live 3/11/24 at 11AM PDT (2PM EDT)
