### ISSUE TITLE
Design Deployment Verification Process (Backend)

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#12928]
### User Story

As a deployment engineer on RS,
I need a way to check the version of deployed code,
So I can ensure the correct code was deployed.

### Description/Use Case

Presently, RS is split up into various azure functions that we deploy at the same time. Once we have deployed them to production, we need a SOP for verifying that they are the version we think they are. This should be documented and pinned in the deployment channel and deployment instructions.

### Dev Notes

- One possible solution is to have a gradle task that updates a version file that the azure functions read from.
- Another solution is to see if Azure has mechanisms to help support this

### Acceptance Criteria

- [ ] SOP created for verifying deployed application and implementation tickets created (if any).

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12928?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12928?planning-poker) with Zenhub @brick-green

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12928?planning-poker) with Zenhub @jack-h-wang

**Comment by adegolier** [comment]
Seems to be working in Staging now. Added instructions on page 6 of the deployment doc.
