### ISSUE TITLE
Add filtering so we only get exceptions on the FE where the browser is a supported version.

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#12920]
Need to talk to Chris since we can't do > or < evals on the version numbers. 
```
chrome >= 87
chrome mobile >= 87
firefox >= 78
firefox mobile >= 78
safari >= 14
ios (safari mobile) >= 14
edge >= 88
```

**Comment by jpandersen87** [comment]
Did some research into how Azure Monitor comes up with the `ClientBrowser` field, and I think it's based off of the `parse_user_agent` function (see [here](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/parse-user-agent-function)). I ran supported useragent strings through it to determine the names for desktop/iOS/android variants. Here is a modified regex string from the one frontend generates for JS code with fixed names that works in Azure Monitor using the `matches regex` expression: `"Edge (Mobile )?(8[89]|9\\d|\\d{3,})\\.\\d+(\\.\\d+|)|Firefox (iOS|Mobile )?(7[89]|[89]\\d|\\d{3,})\\.\\d+(\\.\\d+|)|Chrome (Mobile (iOS )?)?(8[7-9]|9\\d|\\d{3,})\\.\\d+(\\.\\d+|)|(Mobile )?Safari (14[._]\\d+|(1[5-9]|[2-9]\\d|\\d{3,})[._]\\d+)([._]\\d+|)"`. 

An example Azure Monitor query:

```
AppExceptions
| where TimeGenerated >= ago(7d)
    and ClientType == "Browser"
    and ClientBrowser matches regex "Edge (Mobile )?(8[89]|9\\d|\\d{3,})\\.\\d+(\\.\\d+|)|Firefox (iOS|Mobile )?(7[89]|[89]\\d|\\d{3,})\\.\\d+(\\.\\d+|)|Chrome (Mobile (iOS )?)?(8[7-9]|9\\d|\\d{3,})\\.\\d+(\\.\\d+|)|(Mobile )?Safari (14[._]\\d+|(1[5-9]|[2-9]\\d|\\d{3,})[._]\\d+)([._]\\d+|)"
```

**Comment by chris-kuryak** [comment]
I don't fully understand Joseph's answer above as I am not technically saavy enough, but if it makes sense to you all and answers your question around browser version, then go for it.

However, if it doesn't, then we can just start with Browser names regardless of version.

**Comment by chris-kuryak** [comment]
@jeremy-page Can you update with a comment here on what is blocking so I can review with my team? Thanks

**Comment by supriyaaddagada** [comment]
@chris-kuryak  As mentioned in the chat, below are the two front end alerts we have
![image (1)](https://github.com/CDCgov/prime-reportstream/assets/19617625/c5a2c099-1504-4736-a43c-af18b98aa790)

we've tried with updating filters to the above alerts in staging and it gave not expected results, please provide a sample pager duty alert you have received for frontend, so we can update the correct alert

**Comment by chris-kuryak** [comment]
@supriyaaddagada -- See Joseph's comment above. Looks like we are getting exceptions that trigger PagerDuty from App Insights, unsure where "Alerts" that you posted falls into this picture.

**Comment by supriyaaddagada** [comment]
@chris-kuryak @jpandersen87 Based on our last weeks discussion, i added below two new alerts in staging but no alerts are getting reported

![image](https://github.com/CDCgov/prime-reportstream/assets/19617625/8372ea3b-fe9c-43a0-91ae-bf24c8ce52e2)

when i tried to run the query from app insights logs also, it is not returning any alerts, could you please check and let me know the query

exceptions
| where client_Browser == 'Browser'
    and client_Browser matches regex "Edge (Mobile )?(8[89]|9\\d|\\d{3,})\\.\\d+(\\.\\d+|)|Firefox (iOS|Mobile )?(7[89]|[89]\\d|\\d{3,})\\.\\d+(\\.\\d+|)|Chrome (Mobile (iOS )?)?(8[7-9]|9\\d|\\d{3,})\\.\\d+(\\.\\d+|)|(Mobile )?Safari (14[._]\\d+|(1[5-9]|[2-9]\\d|\\d{3,})[._]\\d+)([._]\\d+|)"

**Comment by chris-kuryak** [comment]
Also, the following query works for me in AppInsights -> Logs, if this is helpful

> exceptions
> | where client_Type == "Browser"
> | where client_Browser matches regex "Edge (Mobile )?(8[89]|9\\d|\\d{3,})\\.\\d+(\\.\\d+|)|Firefox (iOS|Mobile )?(7[89]|[89]\\d|\\d{3,})\\.\\d+(\\.\\d+|)|Chrome (Mobile (iOS )?)?(8[7-9]|9\\d|\\d{3,})\\.\\d+(\\.\\d+|)|(Mobile )?Safari (14[._]\\d+|(1[5-9]|[2-9]\\d|\\d{3,})[._]\\d+)([._]\\d+|)"

**Comment by supriyaaddagada** [comment]
@chris-kuryak @jpandersen87 Added the query to the new rules, i will monitor and provide an update about the query

![image](https://github.com/CDCgov/prime-reportstream/assets/19617625/68773183-9380-4978-a3b3-69ec9280a4cd)
