### ISSUE TITLE
Add Encryption for files sent to NATUS/LA

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#12925]
## Problem statement

The files we are currently sending NATUS are encrypted on submission, but the files that NATUS place are not encrypted. NATUS wants extra encryptions on the message before sending on on the wire so they can manually decrypt it with the same key they provide us.

## What you need to know

NATUS/LA proposes to give us the key to use for encryption. They want to rotate the key periodically and they will unencrypt in. Files should be 
Sha 512 AES. This would sit in the REST transport. To make it configurable, we need to add extra settings on the receiver transport settings.

## Acceptance criteria

- [x] Uploaded files will be fully encrypted
- [ ] Testing complete

## To do

- [ ] ...

**Comment by LaFreda1** [comment]
Ott received postman collection. Will prioritize after CA PHL

**Comment by LaFreda1** [comment]
Spoke with Flexion group yesterday, will likely prioritize this work above CA PHL. @ sprints away

**Comment by oslynn** [comment]
ETOR told me to hold off on development for now until they tell to me continue.

**Comment by chris-kuryak** [comment]
Waiting on Flexion for response/action.
Ott asked for help from Flexion to overcome an issue.

**Comment by oslynn** [comment]
Slack:  @John King
 
@Jorge Lopez
 
@pkendall
 
@victorchaparro
 
@Chris Kuryak (he/him) [ULE6]
 FYI: CDC resolved the issue regarding the LA-PHL domain name can't be found by ResportStream when RS tries to send an encrypted message.  I checked the connection and sent the encrypted test message to LA-PHL.ETOR-NBS-ORDERS successfully.

<img width="1080" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMncxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c367f8974314a502c8d153b65fe0ed909739ac55/image.png" alt="image.png" />

<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmcxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37b9b8b6405347cd6b819f3326b3df67f5b6b588/image.png" alt="image.png" />
