### ISSUE TITLE
Check if Send poison queue message was successful

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12968]
## Problem statement
After the recent maintenance downtime, there was one message left in the Send Poison queue. Arnej resent that message. Engagement team needs to check that message was sent correctly and alert to any issues (if found).

## What you need to know
- https://nava.slack.com/archives/C025F5W5Q7L/p1705423234691389

## Acceptance criteria
- [ ] Confirm that the message was resent correctly and received. If not, resend correctly.
- [ ] Remove message from Send poison queue
- [ ] Reply to thread in Slack (above) that it has been checked and no more action is needed.

**Comment by GilmoreA6** [comment]
report-id: bf8dfe2a-48f7-4c42-a794-3ac2975c95a2 was listed in send-poison-queue due to issues with changing the queue formats from custom to JSON. Arnej submitted new message to the send queue with the new format.

**Comment by GilmoreA6** [comment]
Checked azure
