### ISSUE TITLE
UP updates to Getting Started page

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#12979]
## Problem statement

The UP change communication strategy IDed the Getting Started page as content affected by the changes. 

## What you need to know

- ...

## Acceptance criteria

- [ ] Page updates drafted, reviewed, and approved by content owner
- [ ] Next step planned (Content handed off to eng or design as necessary)

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@chris-kuryak @jillian-hammer moved back to next items and out of this sprint because after further investigation revealed this makes more sense to do in conjunction with upcoming bi-directional user edits

**Comment by chris-kuryak** [comment]
Moved out one sprint

**Comment by chris-kuryak** [comment]
No longer needed as content was revised in #14629
