### ISSUE TITLE
Test SR HIV results locally

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12976]
## Problem Statement
Before sending test messages to CA in staging and making any transforms, we want to test messages locally to ensure they are getting through the UP as we'd expect.

## What you need to know
- 1/17, Victor to communicate back to SR on how to accept gender of sexual partner in the test result
- Then SR will need to make the necessary changes on their end (still waiting on SR as of 2/9, check with LaFreda for update)
- SR has confirmed that they will populate the fields, but need to send a test message

## Acceptance Criteria
- [x] HIV test message is submitted from SR and is processed through the UP "losslessly"

**Comment by LaFreda1** [comment]
Victor will send me the questions we have for LA county and I will email them.

**Comment by LaFreda1** [comment]
Email sent on 1/26/24: 

Good morning Mike and Rebecca,

Happy Friday! I am a project manager on CDC's Reportstream project. I have a couple of questions for you as we work on sending you HIV results with our sister product, SimpleReport. Please provide answers to the questions below:

SimpleReport is going to start sending patient's gender identity for HIV results. Is there a specific field in HL7 where LAC expects this field to be mapped under? By looking at the HL7 v2 for PID, there doesn't seem to be a field to map this to.

SR is also planning to start sending the sexual partner's gender identity. We are planning to send this data as an NTE segment. Does that work for LAC?

If we need to hop on a call to discuss this, please let me know; I am happy to schedule a meeting.

**Comment by LaFreda1** [comment]
Message to Merethe: 
Hi @Merethe Hansen! As we plan for our upcoming Sprint, I want to make sure we include any HIV work if needed. Do you have a general timeline of when we can expect the new test message with all of the populated fields? Thanks!!

**Comment by LaFreda1** [comment]
Response from Merethe: 
We’re planning on pulling the tickets to update the HIV fhir message into the coming sprint (starting Wednesday). I would anticipate we can send test messages by the end of that sprint

**Comment by chris-kuryak** [comment]
Per Slack, HIV message from SR may not be ready until the end of next week

**Comment by LaFreda1** [comment]
Update from Jayna:

**Comment by chris-kuryak** [comment]
Finished per Victor
