### ISSUE TITLE
Add filter status visual to Daily Data page

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12978]
## Problem statement
The Daily Data page currently uses the old table component. The new custom table component needs to be implemented and a new column for Receiver needs to be added.

## What you need to know
- [Default view](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=4520-10619&mode=design&t=R6HqNv5rD7LSEHu0-4)
- [Different state views (default, search, filter, error, etc.)](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=4474-14564&mode=design&t=R6HqNv5rD7LSEHu0-4)
- [Product-approved Feature List](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/01_WebDesign/Features/Daily%20Data/Daily%20Data%202024%20Q1%20UI%20Feature%20List.xlsx?d=w31f0338ba527439d98ea104f49f99598&csf=1&web=1&e=gPY3tA)

## Acceptance criteria
- [x] If there is an active search or filter, there will be a description in plain text of that search or filter displayed above the table
- [x] If there is an active search or filter, there will be a quantity of results returned displayed in plain text above the table
- [x] If a default filter value is used in conjunction with other filters, those default values are also displayed in plain text above. thetable
- [x] (Stretch goal) If active search or filter criteria is displayed as plain text above the table, the text describing  whether it is a search or filter is conditional based on the designs included above

**Comment by chris-kuryak** [comment]
@etanb link to PR that closed this

**Comment by etanb** [comment]
https://github.com/CDCgov/prime-reportstream/pull/13581
