### ISSUE TITLE
Identify Technical Options to improve RS permissions

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12975]
## Problem statement
Based on the research performed in the previous sprint, we want to identify what technical options/solutions exist for improving the RS permissions structure to better meet the needs of our users.

## What you need to know

- Previous research in #12812 
- ...

## Acceptance criteria

- [x] Gather feedback and ideas from engineering
- [ ] Document possible options with pros/cons
- [ ] Review concepts with support team

**Comment by jakefishbein-navapbc** [comment]
Scheduled time on Thursday, Feb 22 to white board some options.

**Comment by jakefishbein-navapbc** [comment]
[Mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1707502140746/6af0ac6188bf57666b601c7563abee95385f5a4f?sender=u1cb5f3c6aed590b290728229)

**Comment by jakefishbein-navapbc** [comment]
Spoke with Victor today. His suggestion for next steps was to develop specific use cases to work through.

I think these can be written up along with the permissions "menu" we discussed last week in to a more clear product brief. I believe it should then be handed off to engineers to develop the plan for implementation.

**Comment by jakefishbein-navapbc** [comment]
Chris and I will be developing a menu of permissions at they relate to data access: element, metadata, read, write, download. This will be passed off to engineers to determine an approach. Closing this ticket.
