### ISSUE TITLE
Add Filename and ReportID search to Daily Data

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12971]
## Problem statement
The Daily Data page currently does not have the Filename and ReportID search component. The component needs to be added to the page per the Design and Requirements doc.

## What you need to know
- [Default view](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=4520-10619&mode=design&t=R6HqNv5rD7LSEHu0-4)
- [Different state views (default, search, filter, error, etc.)](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=4474-14564&mode=design&t=R6HqNv5rD7LSEHu0-4)
- [Product-approved Feature List](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/01_WebDesign/Features/Daily%20Data/Daily%20Data%202024%20Q1%20UI%20Feature%20List.xlsx?d=w31f0338ba527439d98ea104f49f99598&csf=1&web=1&e=gPY3tA)

## Acceptance criteria
- [ ] Search bar with "search" and "reset" buttons
- [ ] Search bar label and helper text present
- [ ] Searching returns all exact matches for ReportID or Filename across all receiver services within an organization for all data of all time in the table
- [ ] X button in search bar appears when text is present, and clicking it clears the text input
- [ ] Search criteria remains persistent in the search bar after searching and the result is loaded on the table
- [ ] If filter is present and search button is pressed, all previous filter criteria is cleared and search is performed on only the new search term (no filters)
- [ ] When user clicks reset button, all search and filter criteria is removed and table refreshes based on default inputs
- [ ] Unit tests for this feature(s)
- [ ] Review with Product (Chris) and Design (Jess)
- [ ] Check that E2E tests are still functioning

**Comment by penny-lischer** [comment]
Examples of API request
/api/waters/org/ca-dph.elr/deliveries?fileName=covid-19-a76cdb1b-f0ef-4d7d-b050-e5b171690ee9-20231201171501.hl7

/api/waters/org/ca-dph.elr/deliveries?reportId=eef98896-9519-4bfd-9763-681648a18924
