### ISSUE TITLE
UP updates to STLT intake form

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#12982]
## Problem statement

The UP change communication strategy IDed the STLT intake form as content affected by the changes. 

## What you need to know

- ...

## Acceptance criteria

- [ ] Form updates drafted, reviewed, and approved by content owner
- [ ] Next step planned (Content handed off to eng or design as necessary)

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@jillian-hammer FYI

**Comment by chris-kuryak** [comment]
Moved out 2 sprints to discuss in the future

**Comment by chris-kuryak** [comment]
No longer needed as content was revised in #14629
