### ISSUE TITLE
Improve the OpenAPI.yml document

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#1298]
**Is your feature request related to a problem? Please describe.**
The OpenAPI.yml file is now approaching 1000 lines long. It covers a lot of areas but it doesn't cover the FrontEnd APIs. 

**Describe the solution you'd like**
- OpenAPI.yml remains the main file, but the content into smaller sub-files
- FrontEnd APIs are documented
- Upgrade OpenAPI 3.1 so we can take advantage of the grand convergence with JSON Schema
- More descriptions and examples

**Comment by snesm** [comment]
superseded by https://github.com/CDCgov/prime-reportstream/issues/6243
