### ISSUE TITLE
UP updates to Receiving data page

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#12981]
## Problem statement

The UP change communication strategy IDed the Receiving Data page as content affected by the changes. 

## What you need to know

- ...

## Acceptance criteria

- [ ] Page updates drafted, reviewed, and approved by content owner
- [ ] Next step planned (Content handed off to eng or design as necessary)

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@chris-kuryak @jillian-hammer after starting work to ID specific updates, it became clear that there are no updates necessary at this time, and we will ID any improvements as we onboard more users. So moving out of sprint.

**Comment by audreykwr** [comment]
@chris-kuryak @jillian-hammer after starting work to ID specific updates, it became clear that there are no updates necessary at this time, and we will ID any improvements as we onboard more users. So moving out of sprint.

**Comment by chris-kuryak** [comment]
Moved out 2 sprints and to discuss again if necessary.

**Comment by chris-kuryak** [comment]
No longer needed as content was revised in #14629
