### ISSUE TITLE
[SPIKE] How to Create Sender, Receiver, and Prime Admin accounts for E2E testing on Authenticated pages

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12990]
## Problem statement
In order to test Authenticated pages, we need to create Okta accounts for a those fake "test" users. However, those Okta accounts need to have an email address. So we need to determine a way to create those test accounts that can be used by multiple people and managed after Nava's tenure on the project.

## What you need to know
- Some existing ideas:
   - Create a shared free google email
   - Create a Google group
   - Use a fake (non-existing) email
   - Link from Victor: [https://www.mailslurp.com/examples/playwright-fake-email-test/](https://www.mailslurp.com/examples/playwright-fake-email-test/)
- Requirements:
   - Multiple users have access
   - Works with authenticated testing automated solution
   - Ownership can be transferred to a new team
   - Is as secure as possible

## Acceptance criteria

- [x] Document options for creating test accounts
- [x] Identify the advantages and disadvantages of each
- [x] Review with team to align on solution forward

**Comment by penny-lischer** [comment]
**Single email account**
**Pros**:
* Easy to implement.
* Allows RS to send and receive emails using a single address.
*  login and password can be given to anyone who needs access to the account
**Cons**:
* Huge security risk.
* No collaboration tools.
* Shared credentials

**Google group** (https://support.google.com/groups/answer/2464926?hl=en)
**Pros**:
* Group members can send and receive messages using a single email address.
* Includes basic collaboration features (email assignments, email statuses).
* Group members can label (tag) emails for organizational purposes. 
*  It’s free, allows secure, shared email access, and has some collaboration features
**Cons**
* Requires the Owner or Manager role to change settings and email options within the group.


**CDC Shared Mailbox** (https://servicedesk.cdc.gov/sp?id=sc_cat_item&sys_id=958bd4f41bd97c102954873fe54bcb6e)
**Pros**: 
* Group members can send and receive messages using a single email address.
* Can be transferred to a new owner easily
* Can add/remove members easily

**Cons**:
* May take some time to set up

**Comment by penny-lischer** [comment]
I've submitted an IT service desk ticket to create an email with the plus sign feature. If they cannot do that we can use  a google group (tested by Etan, Penny, Joseph)

**Comment by penny-lischer** [comment]
The reportstreamtesting@cdc.gov email account was created but it doesn't look like the plus addressing is working. Reached out to the help desk and waiting for a response.

**Comment by penny-lischer** [comment]
@chris-kuryak @jpandersen87 @etanb Help desk never got back to me so I think we should move forward with the Google group. Any objections?

**Comment by chris-kuryak** [comment]
Just to double-confirm - Our security exposure here is still just in staging, correct? These won't be used in production.
If so, no objections from me. Proceed with Google group.
@victor-chaparro any concerns?
