### ISSUE TITLE
ORACLE Onboarding – 2. Testing in Staging and Prod [ETOR]

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#13005]
### Acceptance Criteria 
- [ ] Sender has tested in staging and production 
- [ ] RS engineer has determined the data is good enough and graduates Sender to send Prod data to receiver  

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with sender 
- [ ] RS team member who originates this ticket: add dependencies:  
     - [ ] [name of company] Onboarding – Create Org and Sender Settings
     - [ ] [name of company] Onboarding - Validate Test Files 
- [ ] RS team member who originates this ticket: make sure the following are included when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops," "Sender"
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by chris-kuryak** [comment]
@oslynn to confirm status with Flexion and determine if ticket should be closed

**Comment by chris-kuryak** [comment]
Flexion moving this work out to early 2025

**Comment by oslynn** [comment]
Not going to use ETOR any longer.

**Comment by oslynn** [comment]
Not going to use ETOR any longer.
