### ISSUE TITLE
Gap analysis on HL7 CP senders

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13011]
## Problem Statement
In order to prioritize and estimate the work of migrating our HL7 senders from the CP to the UP, we need to perform a gap analysis on the HL7 Senders.

## What you need to know
- Connect with onboarding engineers to perform a gap analysis on all HL7 CP senders
- Connect with Jimmy Fagan (Platform) to get his template on performing a gap analysis
- Proposed gap analysis process:
  - Collect a CP message for the sender in production
  - De-identify message
  - Save file in sharepoint folder https://cdc.sharepoint.com/:f:/r/teams/ReportStream/Shared%20Documents/Engagement/Gap%20Analysis?csf=1&web=1&e=DKrFrk
  - Send HL7 message through UP and outputting as HL7
  - Save output file in sharepoint folder https://cdc.sharepoint.com/:f:/r/teams/ReportStream/Shared%20Documents/Engagement/Gap%20Analysis?csf=1&web=1&e=DKrFrk
  - Sender/Receiver combo should have base transforms, nothing custom, no receiver settings
  - Use a dif-tool to compare input to output of the HL7 message
  - If using an online tool make sure message is de-identified
  - Develop list of differences (for example, excel), consider using [Jimmy's template ](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BFAED6C19-BA41-4F03-A148-6C8490228A1C%7D&file=HL7%20IN%20vs%20HL7%20OUT%20_%20Gap_Analysis.xlsx&action=default&mobileredirect=true)
  - Save file and link in new [Sender Audit column](https://docs.google.com/spreadsheets/d/1GerMI0hKSRK5svbcNzScUBHb5zJImLOixTpBOZXOdvU/edit#gid=443493841)

## Acceptance Criteria
- [x] Perform gap analysis on all HL7 CP senders below
  - [x] intrivo
  - [x] sonic
  - [x] base10genetics
 - [x] Record results (or link to them) in the [Sender Audit document](https://docs.google.com/spreadsheets/d/1GerMI0hKSRK5svbcNzScUBHb5zJImLOixTpBOZXOdvU/edit#gid=443493841)
- [x] Review with Product Mgr (Chris) and Tech Lead (Victor) to develop a high/med/low lift
- [x] Work with Chris to update prioritization and timeline in [migration plan document](https://cdc.sharepoint.com/:p:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B580c2466-f03c-4c0c-b8a2-82a604e88928%7D&action=edit&wdPreviousSession=eb95b9c8-48f2-858e-3fb8-efb7062f16de)

**Comment by jakefishbein-navapbc** [comment]
Awaiting the completion of the gap analysis by engineers. Will then add details to sender migration spreadsheet.

**Comment by chris-kuryak** [comment]
This will be split among all onboarding engineers

**Comment by victor-chaparro** [comment]
HL7 inspector can be used for diff https://www.hl7inspector.com/

**Comment by oslynn** [comment]
I will start to work on base10generics.

**Comment by chris-kuryak** [comment]
Removing the following senders from the ticket since we do not have any data for them to test against (last messages are more than 60 days old).
- lifepoint
- prescryptive
- signetic

**Comment by oslynn** [comment]
I am working on sonic.

**Comment by GilmoreA6** [comment]
Intrivo is done

**Comment by chris-kuryak** [comment]
Glenn is going to reach out to the senders that we did not have data for.
