### ISSUE TITLE
The existing datatypes are specific to an HL7 version and analyzed to make sure they match the standard definition of that type

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#13025]
### User Story
As a report stream developer, I would like a standard set of HL7->FHIR->HL7 data type mappings that can be used across any conformance profile.

### Description/Use Case
The conformance profiles can provide custom datatypes but also will use standard ones from the HL7 spec that will be identical from profile to profile if that profile is using the same underlying version of HL7 2.5.1.  i.e. if a 2.5.1 profile says that a component is a `CWE` that will be the same for any other profile.  The profiles can then define custom version of these datatypes, i.e. `CWE_ELR`

### Acceptance Criteria
- [ ] A set of standard 2.5.1 datatype mappings exist

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13025?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13025?planning-poker) with Zenhub @brick-green
