### ISSUE TITLE
Create mappings and tests for the NIST ELR 2.5.1 message

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#13022]
### User Story
As a report stream sender, I would like to have mappings  HL7->FHIR->HL7 that losslessly and deterministically work the NIST ELR 2.5.1 conformance profile.

### Description/Use Case
There will need to be dedicated mappings that can be loaded into the HL7 translator and the FHIR translator that can reliably map the the NIST ELR 2.5.1 and not contain mappings that are not relevant to the profile

### Dev Notes
- For the HL7 mappings, the easiest approach is likely to just copy the existing `fallback` directory and then make the edits as necessary.
- For the FHIR mappings, it can likely be accomplished by extending the fallback the `ORU_R01` amending existing elements and creating datatypes specific to the profile

### Acceptance Criteria
- [ ] A set of HL7->FHIR mappings exist for the NIST ELR 2.5.1 conformance profile to the R4 FHIR inventory
- [ ] A set of FHIR->HL7 mappings exist for the R4 FHIR inventory to the NIST ELR 2.5.1 profile

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13022?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
