### ISSUE TITLE
Update the HL7Converter to support loading different schema mappings

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#13020]
### User Story
As a sender, I would like to ReportStream to have the flexibility to support converting multiple HL7 conformance profiles

### Description/Use Case
Currently, when an HL7 message is translated, the translator object is just a [singleton](https://github.com/CDCgov/prime-reportstream/blob/b2aaee0cff36f6e7bb1a448fa67cbee122c5ad8c/prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt#L203) with it's configuration hardcoded.  In order to support multiple HL7 specs, the codebase will need to create instances of the translator with different properties, specifically where the mapping schemas for that profile are loaded.

Each new instance should load the default datatypes in addition into a profile specific ones as this will substantially reduce the amount of duplicated files.

### Dev Notes
- [This](https://github.com/CDCgov/prime-reportstream/blob/b2aaee0cff36f6e7bb1a448fa67cbee122c5ad8c/prime-router/src/main/kotlin/fhirengine/translation/HL7toFhirTranslator.kt#L26) is the init logic.  As part of this work it would be great to also switch to loading them out of the classpath
- The HL7toFhirTranslator constructor should also load the "default" set of datatypes, the `additional.resources.location` property can likely be used

### Acceptance Criteria
- [ ] The schemas are loaded out of the classpath (or if not feasible a follow up ticket created to handle that)
- [ ] A `HL7toFhirTranslator` object can be created with a specified location for it's schema files as well as the default datatypes
- [ ] The current HL7 mapping schemas are moved into a new directory `catchall`
- [ ] The the `FhirConverter` code creates a `HL7toFhirTranslator` with the `catchall` schemas loaded

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13020?planning-poker) with Zenhub @brick-green
