### ISSUE TITLE
Document the SOP for adding a new HL7 spec

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#13024]
### User Story
As a report stream engineer, I would like a standard operating procedure for onboarding a new conformance profile into the system.

### Description/Use Case
Adding a new conformance profile should be relatively rote and follow the same set of steps.

### Acceptance Criteria
- [ ] A new document exists that spells out the steps with examples for adding a new HL7 conformance profile to the system

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13024?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
