### ISSUE TITLE
Deprecate (delete) MH-PHD organization and KS-PHD from Reportstream database

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13038]
## Problem statement
We have two orgs for Marshall Islands and Kansas. We need to deprecate the inaccurate one from each (mh-phd, ks-phd).

## What you need to know

- From James via Slack: "`mh-phd` was a placeholder that was set up early in the project. `rmi-doh` is the active connection"
- LaFreda via Slack:  "yes, we can deprecate ks-phd"

## Acceptance criteria

- [x] `mh-phd` organization no longer shows as an organization in our system
- [x] `ks-phd` organization no longer shows as an organization in our system

**Comment by oslynn** [comment]
Both ks-phd and mh-phd are no longer exist in Organization setting.
