### ISSUE TITLE
[BUG] Website auto-logout happening during non-idle sessions

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13040]
## Problem statement
There have been reports of being logged out of the ReportStream website when the user is not idle.

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- The website (both production and staging) is supposed to auto-logout a user if idle for 15 min
- Chris checked the production instance and had the following experience:
   - Logged into reportstream.cdc.gov as a prime-admin
   - Accessed the Org Settings page
   - Was active (reloading the page, navigating to other pages) for more than 15 min and DID NOT get logged out
   - Then, I was idle (navigated away from tab and window) for over 15 min (closer to 20) and still DID NOT get logged out
   - Then, I was active on the Admin Settings pages (while logged in) for about 5 min longer and all of a sudden it logged me out while I was actively navigating between pages.

## Acceptance criteria

- [ ] Website (production and staging) does not log out users that are active (not idle) unless they have been active for 12 hours
- [ ] Website (production and staging) does log out users that are idle for 15 min

**Comment by jpandersen87** [comment]
@chris-kuryak I had made some small settings changes awhile back when I added some tests for this. Can we get a check to see if this problem is still happening since those settings changes?

**Comment by chris-kuryak** [comment]
Chris and Victor have not had the issue recently.
Joseph to message in Onboarding-Ops channel to see if anyone else has had the issue recently. If not, close ticket.

**Comment by chris-kuryak** [comment]
No recent issues had been reported from Joseph's Slack post. Therefore closing this issue.

@jpandersen87 Do you know which PR had the changes on it that you think may have fixed this? If so, can you link it here in a comment for traceability?

**Comment by jpandersen87** [comment]
> No recent issues had been reported from Joseph's Slack post. Therefore closing this issue.
> 
> @jpandersen87 Do you know which PR had the changes on it that you think may have fixed this? If so, can you link it here in a comment for traceability?

#13194
