### ISSUE TITLE
Ensure all UP receiver settings for OTC data match survey results from RADx MARS

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13065]
## Problem statement
RADx MARS sent us survey data regarding how each STLT would like to receive OTC data. To meet our requirements, we need to ensure our Receiver settings in the UP match the preferences of the survey.

## What you need to know

- [Survey Results](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/Shared%20Documents/Engagement/ELCHealthInformation-SpecialTopicOTCRepor_DATA_LABELS_2023-09-05.csv?d=wde0a40577f6c4f3d80cc3f20d89fab18&csf=1&web=1&e=8oDVmm)
- 
- ...

## Acceptance criteria
- [x] Review survey with Chris, Victor, and LaFreda to determine what preferences we need to accommodate

**Comment by LaFreda1** [comment]
[ELC survey results-cleaned_LH.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVh0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73f98d6022fab403d67a05362bd029b84d1b1427/ELC%20survey%20results-cleaned_LH.xlsx)

**Comment by chris-kuryak** [comment]
Updated/Cleaned up spreadsheet:
https://cdc.sharepoint.com/:x:/r/teams/ReportStream/Shared%20Documents/Engagement/ELCHealthInformation-SpecialTopicOTCRepor_DATA_LABELS_2023-09-051.xlsx?d=wdf48ae4d74614637ab73e3a38a4c8b18&csf=1&web=1&e=j23ftI

**Comment by chris-kuryak** [comment]
Victor confirmed all settings could be controlled with quality filters.

Per discussion with Max and Brandon, this is no longer required to update their settings yet, just to ensure that we can filter if necessary.
