### ISSUE TITLE
SR Resend Failed CSV Uploads through the UP 

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#13062]
There was an issue with the UP CA quality filters and caused some errors to not be routed accordingly. SR was able to re-resend most of the failed reports, but they're unable to resend CSV Upload submissions.

The below report ID's need to be resent to CA:
 Report ID
0f6b3aaf-7aaa-429c-9076-5b9b30cdbe3a
11b267a5-245e-4e2e-8d5c-75f47fe3eb71
1cfac269-bc33-4ec2-9083-5f4a3bf1d33b
20a39440-5e68-41a6-8c4b-8f2257bf808e
2e068576-2885-4d9e-a80a-edba49019260
4161f249-4250-4dbb-8f4f-06c32584d22d
8d85f60d-2887-49ba-bc95-d1f22abe2a96
9d4cca5c-8c13-4044-8dc5-8f64071cfd1a
9ef6f53e-3909-4c05-87c3-9d00e3b06913
cb063fbe-064d-4f29-885e-1f214c2065cd

**Comment by GilmoreA6** [comment]
All reports resent 2/5/24
