### ISSUE TITLE
Small content edits - Sprint 87

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#13077]
## Problem statement

We occasionally find small typos or edits on the website that don't need their own ticket. They will be logged here for eng to implement together.

## What you need to know

Edits needed:

Home page

- Remove period after "Talk with our team to create your plan." so it just reads "Talk with our team to create your plan" to match the other headers

Getting started

- Make health care two words in the card title "Get started as a healthcare organization"
- 

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@chris-kuryak as discussed with @etanb - we'll have a running ticket of little edits I find that we can add into the sprint backlog each sprint when there's stuff. I'll be adding to this.

**Comment by chris-kuryak** [comment]
Perfect, I have referenced it in our FE on call ticket template as a recurring duty: See the next one here #12963 

I will add this to next sprint

**Comment by chris-kuryak** [comment]
Complete
