### ISSUE TITLE
What are your topics for today's (Mon June 14) Dev-sync?

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1309]
Add your discussion items as a comment here. Meeting is at 1pm ET.

@mauricereeves - you and @carlosfelix2  have some new testing infrastructure, I think?  Can you cover this?
@Mr0grog
@mry-usds
@RickHawesUSDS -- would you be willing to cover your AS2 prototype?
@ronaldheft-usds
@joemeree
@tlosbo
@pathikkothari
@td-usds
@pablocaviglia

**Comment by td-usds** [comment]
- #1278 : Should we start signing our commits?

**Comment by carlosfelix2** [comment]
1. Unit test coverage report example and do we want to turn it on
2. Unit test more verbose run status for Github builds
3. ordering_facility_state is required, but we have real data that does not provide it.  Do we make it optional?
3. _BLANK types and cardinality.

**Comment by jimduff-usds** [comment]
A question came up about sending data to ReportStream _directly_ from a mobile device.

**Comment by tlosbo** [comment]
Thoughts on warning/error messages in the reports response payload and condensing/aggregating with a verbose mode.

**Comment by jimduff-usds** [comment]
Action items:
- @carlosfelix2  will "turn on" basic/simple unit test coverage reporting.
- Thanks @carlosfelix2  for the improvements to providing detailed unit test results when run inside GitHub actions.   Note:  can also get this from gradle command line via the -Pshowtests option.
- We are going to keep ordering_facility_state as _required_.  @MauriceReeves-usds suggested defaulting for cases where the sender is inside a single state (eg, FL)
- @carlosfelix2 highlighted the fact that there's a bottleneck in getting PRs approved.
- @tlosbo to set up a meeting with Jim and Mo around condensing warning messages.
- Thanks, @td-usds - Action Item for everyone:   We will start signing our commits.  See https://github.com/CDCgov/prime-reportstream/discussions/1278

Ran out of time to discuss:
- _BLANK types and cardinality.
- sending data to ReportStream directly from a mobile device.
