### ISSUE TITLE
Investigate and document how MSH.21 is used

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#13104]
### User Story
As a ReportStream HL7 sender, I would like to use MSH.21 to indicate which conformance profile I used when generating the message.

### Description/Use Case
MSH.21 is the "Message Profile Identifier" and is suppose to be used to indicate which conformance profile was used for the message in addition to MSH.12 which indicates the version of HL7.  ReportStream would like to use MSH.21 to detect the conformance profile and then use dedicated mappings and HL7 structures that reflect that profile to that we can losslessly translate it.

One example of what needs to be dug into is what `PHLabReport-NoAck^PHIN^2.16.840.1.113883.9.11^ISO` (from the ELIMS messages) represents and what portion should be used when detecting the conformance profile.  Using https://www.hl7.org/oid/, the id here maps to a the NIST ELR profile (I think).

We want to understand more broadly how MSH.21 is constructed and how it can be used to decide which conformance profile ReportStream should use.

### Digsites
- What are senders sending in this field?
- How is RS going to use it/ interpret it? (How can it be used to associate to a specific profile on the backend?
- How do STLTs use it?
- What is an HL7 conformance profile? Can start [here](https://caristix.com/blog/2010/09/what-is-an-hl7-conformance-profile/): 
- How are HL7 conformance profiles related to "specs"? Such as the RADxMARS HL7 spec?

### Acceptance Criteria
- [x] Deadline end of Feb 2024
- [x] Usage of MSH.21 across HL7 senders (ETOR, ELIMS, OTC) is documented

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13104?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13104?planning-poker) with Zenhub @brick-green

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13104?planning-poker) with Zenhub @jsutantio

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13104?planning-poker) with Zenhub @dylansmith-Nava

**Comment by dylansmith-Nava** [comment]
Synced with @arnejduranovic and @jsutantio on the scope of this ticket today and how + where research can play a role and solve unknowns. Generated next steps, some helpful background research, and an SME call to be set up (likely with James). CC @jillian-hammer

**Comment by dylansmith-Nava** [comment]
Delivered [research report](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B62ee4c35-2b5f-4dc9-ab3a-1178aa80d4a6%7D&action=edit&wdPid=2c078e63) with recommendations to stand-up on 2/20 as a 16th to share out to the team and Product. Research report was reviewed by @GilmoreA6 and @arnejduranovic. @brandonnava gave an update on product direction after relaying the insights to the Product sync. As such, research has concluded for now. CC @Andrey-Glazkv @jillian-hammer

**Comment by brandonnava** [comment]
Product direction for record: the research shows inconsistent use of MSH 21 and a wide array of possible profiles that could be input, thus it is not a reliable enough source to based a strategy on parsing the field for their profile and either supporting or denying the message based on the profile provided. We suggest continuing to slowing onboard senders and support our users where they are taking a 'wait and see' approach to the growth of our sender base onto the UP to see if any senders are filling in MSH 21 and if there are any conclusive patterns of profiles submitted worth supporting. This approach does acknowledge that we can't guarantee perfect translations with the sender cleaning following a profile and we're ok with that.
