### ISSUE TITLE
Develop External Comms plan for moving receivers back to the Daily Data page (instead of Data Dashboard)

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13100]
## Problem statement
As we are launching a new search feature on the Daily Data page. We may need comms to adequately inform our external users of the feature and how to use it.

## Requirements of the comms

- Received by all receivers who did not see Daily Data already (see Chris for list)
- Informs users on the new feature(s) and how to use them
- Includes a timeline for when to send to users

## Acceptance criteria

- [x] Comms plan created (with as much content as possible with the available knowledge)
- [x] Aligned with Support team
- [ ] Link Comms plan in [Product Brief](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B651291fb-afb0-4c4f-97f8-1770cbc4d910%7D&action=edit&wdPreviousSession=da0a781d-a657-40e9-8059-674689ff2e5a) (or just inform Chris and he'll add it)

**Comment by chris-kuryak** [comment]
https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B3423A8B7-A32E-4DA9-A9CE-9B6A2230C56B%7D&file=Daily_Data_Change_Comm_Planning.docx&action=default&mobileredirect=true

**Comment by audreykwr** [comment]
@chris-kuryak where did you want this linked in the product brief for that AC? Or will you take care of that and close this out when done?

**Comment by chris-kuryak** [comment]
There is a section in the Product Brief called Communications Plan. I linked it there.
Closing ticket.
