### ISSUE TITLE
FHIR Extension Documentation added to Website

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13112]
## Problem Statement
It is required (spec) that we provide linked information about our FHIR extensions on our website. This documentation currently does not exist on our website.

## What you need to know
- Platform team (check with Arnej towards end of quarter) will develop the requirements for this documentation and how it must look/function on the RS website
- And example that was shared to us from platform: https://build.fhir.org/ig/HL7/US-Core/StructureDefinition-us-core-tribal-affiliation.html

## Acceptance criteria
- [ ] TBD based on platform requirements

**Comment by chris-kuryak** [comment]
@arnejduranovic Is this still a requirement for this quarter? And if so, have y'all produced any documentation?

cc: @brandonnava, @Andrey-Glazkv  for awareness

**Comment by arnejduranovic** [comment]
I don't think we are anywhere close to having something to put up on the website, and we are currently not working towards this as it would be a lot of work. What we did (@brick-green) was create this which is a good first step: https://github.com/CDCgov/prime-reportstream/pull/13625

**Comment by chris-kuryak** [comment]
Per product sync, this is no longer a requirement for this quarter
