### ISSUE TITLE
CA PHL Onboarding – 2. Testing in Staging and Prod [ETOR]

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#13125]
### Acceptance Criteria 
- [ ] Sender has tested in staging and production 
- [ ] RS engineer has determined the data is good enough and graduates Sender to send Prod data to receiver  

### To Do 
- [x] RS engineer: update this ticket with comments with every interaction with sender 
- [x] RS team member who originates this ticket: add dependencies:  
     - [x] [name of company] Onboarding – Create Org and Sender Settings
     - [x] [name of company] Onboarding - Validate Test Files 
- [x] RS team member who originates this ticket: make sure the following are included when creating this Issue. 
     - [x] Pipelines: Onboarding & Operations (New) 
     - [x] Labels: "Onboarding-ops," "Sender"
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by oslynn** [comment]
Testing in production for the moment.

**Comment by chris-kuryak** [comment]
Need to check with ETOR on if this is changing

**Comment by oslynn** [comment]
Flexion stopped working with CA-PHL.  I am not sure why.

**Comment by chris-kuryak** [comment]
Flexion is still working with CA-PHL as a sender. The pilot is just delayed until Jan 2025

**Comment by oslynn** [comment]
Done
