### ISSUE TITLE
Authenticated Nav Bar Design

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13120]
## Problem statement
The Nav bar on the public facing side of the site was redesigned for the website remodel in summer 2023. However, the Authenticated side of the site has more implications regarding size, color, etc for how it looks and feels with a nav bar.

Therefore, we want to redesign the authenticated nav bar to ensure a positive user experience with a more responsive design.

## What you need to know

- [Word doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engagement/Website/20240409_RS-Website_Auth-Nav-Bar.docx?d=wf606eb32e3b6451eb029f54859582171&csf=1&web=1&e=jFcn7Z)
- [Figma eng ready design](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=5597%3A21792&mode=design&t=Kw0vSzPLXR7OdC06-1)

## Acceptance criteria
- [x] Design is optimized and responsive to desktop, tablet ~and mobile~ (EDIT: Mobile design and eng implementation to be addressed in future ticket)
- [x] Design created and aligned with engineering
- [x] Handoff document created for engineering
- [x] Engineering approves and is aligned
- [x] Facilitate creation of engineering ticket with Product (Chris)

**Comment by jillian-hammer** [comment]
Reviewed [initial thoughts & sketches](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engagement/Website/20240409_RS-Website_Auth-Nav-Bar.docx?d=wf606eb32e3b6451eb029f54859582171&csf=1&web=1&e=jFcn7Z) with Audrey today. Settled on an approach to mockup. Figma mockup [here](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=5428%3A1832&mode=design&t=75mrX2TM625AojWg-1) for @audreykwr's review! cc @chris-kuryak

**Comment by jillian-hammer** [comment]
- Eng ready Figma design [here](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=5597%3A21792&mode=design&t=Kw0vSzPLXR7OdC06-1).
- Next ticket: Authenticated Nav Bar Desktop MVP - Engineering work #13121
