### ISSUE TITLE
Metrics Dashboard MvP Backend: Part 2

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#13136]
### User Story

As ReportStream,
I need to provide various product-level and application performance metrics,
so that stakeholders can better understand the system and its operation.

### Description/Use Case

This design should identify how the backend should handle collecting, storing, and surfacing the data required to answer the following questions outlined in the FY24 OKR Metrics Dashboard Requirements:

- Message volume over time (filter by condition/sender/STLT)
- Message volume over time for ELIMS ELR (filter by condition/STLT)
- Message volume over time for newborn screening ETOR (filter by message type/HCO/PHL)

Also keep in mind the Observability requirements as a whole and make sure our MvP approach does not lock us out of supporting the additional questions outline therein:  [observability requirements document](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B50A50DD5-3353-43D3-89E6-9E3D6E7DD0D8%7D&file=Observability%20Product%20Requirements.xlsx&nav=MTVfezYzNTdENzdBLTQ0RjMtMTE0Mi05RjlCLTFEMTFEQ0JDMEQwN30&action=default&mobileredirect=true).

- These metrics should be able to be retrieved from somewhere in Azure App Insights
- We should leverage Azure logs/metrics to power these queries.

### Acceptance Criteria

- [ ] Azure App Insights Graph updated to answer the questions outlined above

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13136?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13136?planning-poker) with Zenhub @brick-green

**Comment by jalbinson** [comment]
@arnejduranovic 

Questions on this one
1. Is message volume messages in or messages out? Or both?
2. Where can the STLT for a report be found?
3. ELIMS ELR and newborn screening will be separated by their `Topic` correct?
4. What does HCO and PHL stand for? Where can they be found?

**Comment by arnejduranovic** [comment]
> @arnejduranovic
> 
> Questions on this one
> 
> 1. Is message volume messages in or messages out? Or both?
> 2. Where can the STLT for a report be found?
> 3. ELIMS ELR and newborn screening will be separated by their `Topic` correct?
> 4. What does HCO and PHL stand for? Where can they be found?

1. Likely both (given the filters)
2. This information is determined during the route function, and I believe is then saved in the report_file table
3. Correct.
4. These terms are for the ETOR context: HCO is the Health Care Organization that sends test orders to the PHL (Public Health Lab) and receives test results from the PHL. So, in other words: HCO is a sender of orders and receiver of results and PHL is sender of results and receiver of orders

**Comment by jalbinson** [comment]
Follow up
How is the STLT different from the receiver?
Are HCO and PHL going to be available to us as something to extract from the FHIR bundle?

**Comment by arnejduranovic** [comment]
> Follow up How is the STLT different from the receiver? Are HCO and PHL going to be available to us as something to extract from the FHIR bundle?

A STLT is a receiver of ELR data. A STLT, HCO, and PHL can all be receivers depending on what the use case is. All the queries above are essentially filter by sender and receiver -- I don't think we need to specify whether a sender/receiver is a STLT or PHL (that should be implied given the topic (use case) that is selected)
