### ISSUE TITLE
Convert Function: Handle Large Files

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#13131]
### User Story

As a sender of report to ReportStream,
I want to receive an error if the report size (either file size or message number) is too great for ReportStream to handle,
so that I can resubmit a smaller report that ReportStream can successfully process.

### Description/Use Case

On Jan 25 SimpleReport sent two reports that both contained around 1500 messages and the convert step timed out several times trying to process them until they ended up in the poison queue. The two submitted reports were:

- f4ea453d-e5c9-4493-944a-808560a2338f
- de07b4d5-691d-475c-b4a9-b2a0397e7a1c

The receive (process) function should be updated to reject reports that are too large and/or  the Convert functions should be updated to be able to handle large reports.

### Acceptance Criteria

- [ ] Receive function throws an error when a report is too large
OR
- [x] Convert function updated to better handle large reports

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13131?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13131?planning-poker) with Zenhub @brick-green

**Comment by jalbinson** [comment]
We should decide which path to take before bidding since the work varies a lot. Maybe we need a spike ticket to decide?

**Comment by arnejduranovic** [comment]
@chris-kuryak to discuss potential solutions with SR. Potential solutions have message monitoring and message processing implications.

**Comment by arnejduranovic** [comment]
Marking this as complete since we have had several PRs merged to speed up the convert step and have not seem a timeout failure in a while. Will re-open if issue comes back. @brandonnava @chris-kuryak @Andrey-Glazkv
