### ISSUE TITLE
CA PHL Onboarding - Go Live Coordination [ETOR]

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#13155]
### Acceptance Criteria 
- [ ] Confirmed with STLT when they want to start receiving (date) 
- [ ] Removed quality filter in prod settings = allowNone() 
- [ ] Removed quality filter in staging settings = allowNone() 
- [ ] Set Customer status = active 

### To Do 
- [x] RS engineer: update this ticket with comments with every interaction with receiver 
- [x] RS team member who originates this ticket: add any dependencies, as needed 
- [x] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [x] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Receiver" and state label 
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by oslynn** [comment]
Testing in production.

**Comment by oslynn** [comment]
Done
