### ISSUE TITLE
Metrics Dashboard MvP Backend: Part 1

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#13160]
### User Story

As ReportStream,
I need to provide various product-level and application performance metrics,
so that stakeholders can better understand the system and its operation.

### Description/Use Case

This design should identify how the backend should handle collecting, storing, and surfacing the data required to answer the following questions outlined in the FY24 OKR Metrics Dashboard Requirements:

- Number of STLTs receiving two or more conditions from ReportStream

Also keep in mind the Observability requirements as a whole and make sure our MvP approach does not lock us out of supporting the additional questions outline therein:  [observability requirements document](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B50A50DD5-3353-43D3-89E6-9E3D6E7DD0D8%7D&file=Observability%20Product%20Requirements.xlsx&nav=MTVfezYzNTdENzdBLTQ0RjMtMTE0Mi05RjlCLTFEMTFEQ0JDMEQwN30&action=default&mobileredirect=true).

- These metrics should be able to be retrieved from somewhere in RS Azure App Insights
- We should leverage Azure logs/metrics to power these queries.

### Acceptance Criteria

- [ ] Azure App Insights Graph updated to answer the questions outlined above

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13160?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13160?planning-poker) with Zenhub @brick-green

**Comment by Andrey-Glazkv** [comment]
@jalbinson to add to Dev notes once his doc is through the PR
