### ISSUE TITLE
Upload new LIVD Table

### ISSUE THREAD

**Issue by OHoward2023** [CDCgov/prime-reportstream#13167]
## Problem statement

We received an updated LIVD to the ReportStream inbox. The LIVD table needs to be uploaded into ReportStream.

## What you need to know

[LIVD-SARS-CoV-2-2024-01-25 PRIME.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2NLQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce47db9dc447e48b44f5748ccf81ac7536f4fc3b/LIVD-SARS-CoV-2-2024-01-25%20PRIME.xlsx)

## Acceptance criteria

- upload the updated LIVD table

## To do

- Assign to an engineer and upload the new table.

**Comment by adegolier** [comment]
@GilmoreA6 This isn't the one you just put in last week is it?

**Comment by GilmoreA6** [comment]
@adegolier sorry I didn't see this. No the last one I updated was 12/1/23

**Comment by OHoward2023** [comment]
@adegolier Hi Angela, may I have an update on this ticket please?
