### ISSUE TITLE
Update ReportFunction ReportReceivedEvent

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#13161]
### User Story

As an Engineer on ReportStream,
I would all ReportReceivedEvent Azure Events to have the same info,
so that debugging can be consistent across all submission endpoints.

### Description/Use Case

With the creation of a new microservice in  the`submissions` spring app, there exist two implementations of ReportReceivedEvent that we should consolidate. 

```
NEW PROPOSED EVENT OBJECT

data class ReportReceivedEvent(
    val timeStamp: Instant,
    val reportId: UUID,
    val parentReportId: UUID,
    val rootReportId: UUID,
    val headers: Map<String, String>,
    val queryParameters: Map<String, String>,
    val method: HttpMethod,
    val url: String,
    val sender: String,
    val senderIP: String,
    val fileSize: String,
    val blobUrl: String,
)
```

```
prime-router/src/main/kotlin/azure/observability/event/ReportReceivedEvent.kt

data class ReportReceivedEvent(
    val reportId: ReportId,
    val sender: Sender,
    val submissionDetails: ActionHistory.ReceivedReportSenderParameters,
    val senderIP: String,
    val fileSize: String,
) : AzureCustomEvent
```

```
submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/ReportReceivedEvent.kt

data class ReportReceivedEvent(
    val timeStamp: Instant,
    val reportId: UUID,
    val parentReportId: UUID,
    val rootReportId: UUID,
    val headers: Map<String, String>,
    val sender: String,
    val senderIP: String,
    val fileSize: String,
    val blobUrl: String,
)
```

### Dev Notes

The microservice does not make use of the `AzureCustomEvent`, and it does not necessarily need to be updated to do so, as there is no immediate need for this since we expect ReportFunction to be deprecated relatively soon.
### Acceptance Criteria

- [ ] `prime-router/src/main/kotlin/azure/observability/event/ReportReceivedEvent.kt` contains the same info as the `submissions/ReportReceivedEvent`

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13161?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13161?planning-poker) with Zenhub @brick-green

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13161?planning-poker) with Zenhub @adegolier

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13161?planning-poker) with Zenhub @david-navapbc
