### ISSUE TITLE
Align with CDC stakeholders

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13180]
## Problem statement
Before making too much progress on a plan, we want to align with CDC stakeholders. 

Timing of this ticket will depend on progress with them in other conversations. This doesn't have to be a blocker to any of our individual outreach plans.

## Definition of alignment
- The stakeholder is aware of the work/plan, and their feedback has been captured and discussed for alignment.

## Acceptance criteria
- [x] Align with Teresa
- [ ] Align with Megan

**Comment by chris-kuryak** [comment]
@audreykwr Any update here? Still planning on having these conversations this sprint?

**Comment by chris-kuryak** [comment]
tagging @GlennRGrieves since he said he can assist with this

**Comment by chris-kuryak** [comment]
Audrey to follow up with Glenn before the end of the sprint

**Comment by audreykwr** [comment]
Confirmed with Glenn that Megan and Teresa are aware of the plan and are involved in ongoing conversations about what we are doing and their involvement.
