### ISSUE TITLE
Development of recruitment and research materials for FQHC initiative

### ISSUE THREAD

**Issue by dylansmith-Nava** [CDCgov/prime-reportstream#13198]
### User Story
As a researcher on ReportStream, I want to establish research and recruitment materials for the FQHC initiative, so we can proceed in conducting this research effectively. 

### Background
Through this initiative, we are trying to uncover FQHC (federally qualified health center) reporting requirements for ELR data, so ReportStream can gain a better understanding of how we could integrate similar publicly-funded Senders. Bonus points to also understand FQHC's user ecosystem, including personnel and their critical jobs. See ticket #[12960](https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/12960).

### Risks/Impacts/Considerations
- Recruitment strategies may change based on initiative needs, approvals, or other factors. These changes may required updates to the materials, which could cause some delays.
- Approval delays also may push on the sprints planned for synthesis at the end of the sprint.

### Open Questions
- Are there any program or strategic restriction(s) when it comes to things like: a) referencing Nava or ReportStream by name, any limitations on the expected length of interview, and/or how much we can share about the project?
- Are there any program limitations on the questions we can ask participants, based on sensitivity levels?

### Links
- [FQHC Reporting](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1705940727150/d100619ea4f5bdc0a6d8a9c7e7ea0ec162a7557d?sender=ufb3824a0e63fafb0304f5774)
- [FQHC Direct Research Proposal](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B3a1a7085-87f2-48c5-b1c3-f2d354dd5baa%7D&action=edit&wdPid=496e8a91)
- [FQHC recruitment materials](https://cdc.sharepoint.com/teams/ReportStream/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FReportStream%2FShared%20Documents%2FDesign%20and%20Research%2F02%5FResearch%2FFQHC%20Reporting%20Requirements%2FResearch%20and%20Recruitment&viewid=6255f791%2D133e%2D4cae%2D9185%2Db78c974e99f2)

### Acceptance Criteria
- [x] Create FQHC discussion guide / CAH discussion guide
- [x] Create HRSA technical staff discussion guide
- [x] Create eCR team discussion guide
- [x] Create FQHC / CAH recruitment materials
- [ ] Create HRSA recruitment materials
- [ ] Create eCR recruitment materials

### Out of Scope
- This ticket is not for conducting research. It is about setting up the materials for the next phase of research.
- Onboarding any FQHC to ReportStream

**Comment by dylansmith-Nava** [comment]
New research and recruitment materials ticket! CC @Andrey-Glazkv @jillian-hammer

**Comment by jillian-hammer** [comment]
Made some minor comments, otherwise approved! thank you @dylansmith-Nava

**Comment by dylansmith-Nava** [comment]
Recruitment is experiencing some difficulty. Working with the design team to discuss alternatives and path(s) forward. CC @jillian-hammer

**Comment by dylansmith-Nava** [comment]
Conducted alternate outreach to an ONC point-of-contact via a PRIME-design member connection, and reached out to the PRIME design lead, Suzi, to see if she has any recommendations for divison lead(s) to chat with on outreach.

Additionally, @jillian-hammer reached out to the eCR team, as well as JT, the other PRIME lead, about recruitment being a blocker for us. CC @Andrey-Glazkv

**Comment by dylansmith-Nava** [comment]
First FHQC call went well! Rapid synthesis is at the bottom of the page [here](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B246EF822-E7A8-49DD-A091-BE9F2AD91F84%7D&file=FQHC_Research%20Discussion%20Guide_template.docx&action=default&mobileredirect=true). As such, I am considering closing out of this ticket to create a new ticket for "research and synthesis" (and can add language about ongoing recruitment as well. Thoughts @Andrey-Glazkv @jsutantio?

**Comment by Andrey-Glazkv** [comment]
Well done @dylansmith-Nava 
Lets close this one. Tag me in your new ticket.

**Comment by dylansmith-Nava** [comment]
@Andrey-Glazkv you got it!
