### ISSUE TITLE
Review requests from NBS and respond with timeline

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13203]
## Problem Statement
NBS has two active requests:

1. Adding their development environment as a receiver
2. Moving their existing connection(s) from CP to UP so they can support more conditions

We need to review, scope, prioritize, and respond to Duc at NBS.

## Acceptance Criteria
- [x] Meet, Align, and Respond to Duc at NBS

**Comment by LaFreda1** [comment]
Dustin confirmed that NBS would like to send Covid, Flu, and Mpox.
