### ISSUE TITLE
Clean up isSendOriginal Implementation

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#13232]
### User Story

As a new feature of the pipeline,
isOriginalMessage should be implemented in the cleanest way possible,
to ensure it is defect free and maintainable

### Description/Use Case

When working on PR  #13230 to implement isSendOriginal, there were a few shortcomings identified per the comments on that PR. This ticket aims to clean up the original implementation and increase test coverage.

Some things we would like to do:
- Clean up file name generation of the delivered report.
    - Presently, HL7 messages will have the schema (that was not applied) in the filename and FHIR messages will have a `-` in the beginning of the file name.
    - If `isSendOriginal` is true and the message is HL7 but it gets routed to a FHIR receiver, then the delivered filename will have .FHIR at the end but contents will be HL7.
- Update smokeTests to verify the expected contents of files, not just the routing, and then add coverage for isOriginalMessage.
    - Can we also update the logging of the smokeTests so they do not appear to be stuck?
- Refactor translation step implementation to more clearly illustrate the intent of using topics to modify pipeline behavior
- Add unit tests for the new helper functions like `getOriginalReport` and move to a more appropriate location. Also consider refactoring to use JOOQ.
- Look into splitting the Send step into one for COVID pipeline and one for UP.

### Acceptance Criteria

- [ ] Implementation cleaned up per the comments on original PR
- [ ] Smoke tests improved/added
- [ ] Resolved TODO comments tagged with original PR (13232)

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13232?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13232?planning-poker) with Zenhub @brick-green
