### ISSUE TITLE
Update prod/staging settings to eliminate dependencies on the fhirpath filter shorthand table.

### ISSUE THREAD

**Issue by jimmyfagan** [CDCgov/prime-reportstream#13251]
### User Story
As a settings maintainer, I'd like to simplify filter maintenance and deployment by deprecating the fhirpath filter shorthand table.

### Description/Use Case
When updates are made to `fhirpath_filter_shorthand.csv` those changes need to be manually rolled out to staging and prod databases, and especially if code changes need to be synchronized with those updates, the deployment of the changes is complicated to get right.

### Risks/Impacts/Considerations
Completing this change reduces the overall risk.

### Dev Notes
CLI commands should be used to determine what dependencies on the shorthand variables currently exist.

### Acceptance Criteria

- [x] No organization filters in staging or production utilize variables from `fhirpath_filter_shorthand.csv`
- [ ] The shorthand tables for those variables in staging and production have been cleared out

**Comment by JessicaWNava** [comment]
PR up https://github.com/CDCgov/prime-reportstream/actions/runs/9601081137?pr=14840 to remove the references in the project. Going to wait until this is deployed then remove the references from the settings as well.

**Comment by JessicaWNava** [comment]
Removed the references from the settings for both staging and prod
