### ISSUE TITLE
[NBS]  Add development environment as a receiver of RS

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#13267]
## Problem statement

NBS has requested that we onboard their development environment as a receiver. 

## What you need to know

Email from Duc Nguyen: 
Hello @Chaparro Flores, Victor (CDC/IOD/OPHDST) (CTR) and @Howard, LaFreda Janae (CDC/IOD/OPHDST) (CTR),
 
 I have officially completed the demo with CDC; could you please migrate our integration to the universal pipeline. We are expecting to test with any type data other than covid.
 Also, I requested another integration with our development environment in a separate email, but it would be great if you could proceed with this request too. Once you get to this point, I will provide the Postman collection.

Thank you

## Acceptance criteria

- [ ] NBS development environment successfully receives data from RS

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
We have not heard back from NBS on this request since February. So we are closing until we hear a need for this again.
