### ISSUE TITLE
[NBS] Migrate NBS connections from CP to UP

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#13270]
## Problem statement

NBS would like to migrate their connections from the CP to the UP.

## What you need to know

Email from Duc Nguyen: 
Hello @Chaparro Flores, Victor (CDC/IOD/OPHDST) (CTR) and @Howard, LaFreda Janae (CDC/IOD/OPHDST) (CTR),
 
 I have officially completed the demo with CDC; could you please migrate our integration to the universal pipeline. We are expecting to test with any type data other than covid.
 Also, I requested another integration with our development environment in a separate email, but it would be great if you could proceed with this request too. Once you get to this point, I will provide the Postman collection.

Thank you

## Acceptance criteria

- [ ] NBS successfully send data via UP

## To do (questions that need answers)

- [ ] Are we going to do anything with those messages in the future?
- [ ] Are we routing those messages anywhere or just back to them?
- [ ] If we're just routing the messages back to them we can use the same solution we did for ELIMS where we skip all the transforms and send the original message back.

**Comment by chris-kuryak** [comment]
We have heard no response/need for this since opening the ticket. Closing for now based until we hear back.
