### ISSUE TITLE
Re-mine Product Requirements and Research Reports

### ISSUE THREAD

**Issue by jsutantio** [CDCgov/prime-reportstream#13294]
### **User Story**
As a researcher, I need to gather the high-level user needs and pain points.

### **Context**
This ticket is a portion of the research gathering tickets that act as the foundation for the larger "opportunity" framework.

The focus of this ticket is to compile high-level opportunities, recommendations, and implications that will inform the [Opportunity Map](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1708038000818/bd603af718f9ebd39ac756329585c80aa92ee43d?wid=0-1709161643586). Additional datatypes, such as needs, behaviors, feature requests, etc. will be recorded, but not the primary search focus for this ticket.

### **Documents to Re-mine:** (most require CDC credentials to access)
**Internal Development**
- [x] Routing Discovery Sprint (Aug '23 [Discovery Sprint Report](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Discovery%20Sprints/Routing%20in%20the%20UP/UP%20Routing%20Disco%20Sprint.docx?d=w249361b3cfbd482db713df4c2cc63918&csf=1&web=1&e=T9qldd), Mar '24 [Software Req Doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engineering/Design/SRD-Routing.docx?d=w3a2fa783e8dc4e9b8397da9f5d968dfa&csf=1&web=1&e=hDYJoY), Sep '23 [Deprecated Prod Req](https://docs.google.com/spreadsheets/d/1SyoVSZ2JikYOcYuebk3Gd48sfqcunE-ikcc901RTB9o/edit#gid=149930974))
- [ ] Validation Discovery Sprint
- [x] [RS Program Backlog](https://app.zenhub.com/workspaces/prime-reportstream-program-backlog-64af115169b0b900350b2b01/board)
- [ ] [Product Briefs](https://drive.google.com/drive/folders/1FT1G2x0ZrDre4KRasIDTbAEncrEN3srI) (to be broken down in more detail later)
- [x] [Design team backlog](https://docs.google.com/spreadsheets/d/1IbCGx6e8v0tnEc5KDqasHAL3UburF650Z7wOhOPym7o/edit#gid=0)
- [x] [UP_Marketing and comms strategy](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1692893740765/fd049479f3c57af816d831eb7c132b4ad219b4c7?sender=ufb3824a0e63fafb0304f5774)
- [x] [Research Opportunities Mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1685565557390/994467b18abee96e18bd31cdb00e3300baf57b45?sender=ufb3824a0e63fafb0304f5774)

**Onboarding/ External User Experience**
- [x] [Onboarding Journey Opps](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Onboarding%20journey%20improvement%20synthesis.docx?d=w3adddfe6961d49ceb237813024723bf6&csf=1&web=1&e=SC67Wv)
- [x] [Sender Audit](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/02_Research/CSV%20in%20UP/Sender%20Audit,%20Dec.%202023.xlsx?d=wd5c9935be59d45b9a1b031954f665d6b&csf=1&web=1&e=dqBQl2)
- [x] [Sender Receiver Requirements](https://app.mural.co/t/primedatainput6410/m/nava4113/1689691668005/977bc208d332372cb6123a98c8054e5de89cd202?sender=u1cb5f3c6aed590b290728229)
- [x] Receiver Settings ([2023 version](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1686686644825/a02d83d2bb0f1f9038625e7280d0bea15a97f1ed?sender=u1cb5f3c6aed590b290728229) + [UI Enhancement 2024](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1707143235464/93e77ab0af79ae95da8906218c8b5ae7b1067e47?sender=u1cb5f3c6aed590b290728229))
- [x] Health Equity Research
- [x] FQHC research
- [x] [Service Blueprint](https://app.mural.co/t/primedatainput6410/m/nava4113/1672148125717/f376adefc22f136c60e40cb9f60b1b74ef4ee43d?sender=ufb3824a0e63fafb0304f5774)
- [x] Validation Tool usability tests takeaways: [Providence](https://docs.google.com/document/d/1gAw5Uk3csf0JoByxHfQ9spsq1_eooV8ANsWWLKpV6Xw/edit#heading=h.hpsr3t2hf4k4) and [Dendi](https://docs.google.com/document/d/1523BiQ6zcxNEzDGS0MEJyzO6lyxWhXrBSQNiupbzxrA/edit?usp=sharing)
- [x] [Empathy map and user stories](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1675735666098/2dad17ee2fdba31ee5b5e375d28f2756e832f739?invited=true&sender=uc55a7af3b66977fba12f5528)
- [x] [Site user test synthesis](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1698714496089/5f99e6f6568817e28fc2b45985f543e8ffa2a554?sender=uc55a7af3b66977fba12f5528)
- [x] [IA Research Synthesis](https://docs.google.com/presentation/d/1d8GA7puc3IGCuHOiFgBUSCgGsCNYAhS3cVSr1OdNUkI/edit#slide=id.g21240411e1c_0_50)
- [x] [Arkansas](https://docs.google.com/document/d/1VRMdTwUZRKYt1waaeSaV4NuiJWB8FXSbWUSH4wE3JhQ/edit#heading=h.ght1j66yl23v) and [MedArbor](https://docs.google.com/document/d/1uZAvTmeMSRv0VydA7B5fHYbXaVoKoz5AgYjMEQjfqek/edit#heading=h.deuwfyiblnq5) Engagement Debrief

**Observability**
- [x] [Errors, warnings, quality filters mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1642006406114/075edd3011a24c1b5fbac8b75a2ec3280e4d923f?sender=u8e85df6f9eec764c4bfd6788)
- [x] [CP settings frequency tables](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BEEAF7CB4-C249-4908-AE9F-AB979FB79CEA%7D&file=CP%20STLT%20Setting%20Frequency.xlsx&action=default&mobileredirect=true)
- [ ] [Observability Requirements](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/Shared%20Documents/Platform/Epics/Observability/Observability%20Product%20Requirements.xlsx?d=w50a50dd5335343d389e69e3d6e7dd0d8&csf=1&web=1&e=Q5yVgy)
- [x] 2023 Daily Data: Colorado and Washington, and group synthesis on [Mural](https://app.mural.co/invitation/mural/primedatainput6410/1676646127606?sender=u0c3cdba5126734aceb613229&key=9a719b5c-faf5-4a28-9a36-012a139337bd)
- [x] [Data (STLT) Dashboard Usability Study](https://cdc.sharepoint.com/:f:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/02_Research/COVID%20Dashboard%20Usability%20Study?csf=1&web=1&e=81CTw8)

**Bonus**
- [ ] [user permissions study](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BD51D8B88-E290-4C8D-A2C1-72DCBB213DAF%7D&file=User%20Permissions%20Research%20Summary.docx&action=default&mobileredirect=true)
- [x] [Reportable conditions by STLT](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B57355D59-70F8-4090-9508-44912B51B7CF%7D&file=Copy%20of%20Reportable_conditions_STLTs_2023.xlsx&action=default&mobileredirect=true)
- [ ] [Content strategy update and priorities](https://docs.google.com/presentation/d/1Qa0Ek93niJZQWdHgQCl3LITHTh6_1wEXXAekNGHkh8U/edit#slide=id.g1f9b1d1a6a4_0_104) (many of the opps have already been implemented)
- [ ] [Site audit analysis deck
](https://docs.google.com/presentation/d/1H5uon85WeTZgvRQH-7DlpwmrDXQUO6tA6xIHh7KZX_M/edit#slide=id.g1f9b1d1a6a4_0_104)(many of the opps have already been implemented)

### **Acceptance Criteria**
- [x] Create master repository in [mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1708038000818/bd603af718f9ebd39ac756329585c80aa92ee43d?sender=u8e85df6f9eec764c4bfd6788) (later to be exported to excel after synthesis)
- [x] Link all documents/ sources in the mural
- [x] [Bonus] Extrapolate needs, pain points, opps, recommendations/ features and add to the master repository

**Comment by brandonnava** [comment]
Got you: https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/13784
