### ISSUE TITLE
Filter Request To Stop Sending OTC Data to Texas

### ISSUE THREAD

**Issue by OHoward2023** [CDCgov/prime-reportstream#13307]
## Problem statement

The organization, Intrivo, is sending several over the counter COVID self-reported tests coming through report stream over the last month. These have missing first and last names, incomplete address, and missing gender along with other incomplete demographic and lab info. This causes data quality issues in NEDSS and are useless tests since there is no way for follow up. The facility does not want this OTC tests coming through. Can you please remove these from their feed?

## Acceptance criteria

- [ ] ...

## To do

- Add a filter to stop sending OTC data to Texas. Please notify Support when this is complete so we can reach out to the user.

**Comment by OHoward2023** [comment]
@GilmoreA6 Hi James, may I have an update on this ticket please?

**Comment by GilmoreA6** [comment]
Added routing filter "DoesNotMatch(testing_lab_clia, 00Z0000042)" to filter out Intrivo OTC tests

**Comment by GilmoreA6** [comment]
Added routing filter "DoesNotMatch(testing_lab_clia, 00Z0000042)" to filter out Intrivo OTC tests

**Comment by LaFreda1** [comment]
@OHoward2023 Please let the client know that we have fulfilled the request. Will re-open if needed.

**Comment by OHoward2023** [comment]
@LaFreda1 I have informed the user this request has been resolved. Thank you.
