### ISSUE TITLE
Frontend e2e tests need a place to store un/pw credentials

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-reportstream#13300]
For the frontend e2e tests that require authentication they need the username and password credentials to be stored and then they will retrieve them programatically.

We have 3 new users(admin, sender, receiver) that have been added to OKTA.

Please contact Penny Lischer for un/pw for the users.

**Comment by dkrylovsb** [comment]
@penny-lischer @snesm @jeremy-page @JosiahSiegel @supriyaaddagada For your awareness, the credentials needed by the FE E2E tests have been entered in *two* places: GitHub Action Secrets _and_ Dependabot Secrets, under the Security tab.
