### ISSUE TITLE
[Bug] Preserve Original filename for ELIMS receivers

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#13344]
### User Story

As ELIMS, I want to preserve the original file name as it is routed and sent to ReportStream receivers.

### Description/Use Case

Receivers using REST transport are not getting the original filename sent by ELIMS. This would only apply for NY since they have a requirement for us to send the file name via HTTP headers. 

### Dev Notes

- [ ] NY expects to receive the filename inside a request header. See line 540 inside `RestTransport.kt`

### Acceptance Criteria
- [ ] NY receives ELIMS original filename

**Comment by Andrey-Glazkv** [comment]
@chris-kuryak @LaFreda1 for your awareness - this one is in progress and on track to be closed this sprint
