### ISSUE TITLE
Refine areas of opportunity for onboarding/user journey

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#13358]
## Problem statement
As a user, I want to onboard efficiently, so I can get connected to ReportStream.

## What you need to know
We evaluated the current journey reality and now we need to look at the ideas and opportunities that have been previously brainstormed, look for gaps in those ideas, and prepare potential priorities. 

## Acceptance criteria

- [x] Previous ideas/opportunities collected and mapped to current journey
- [ ] Findings on what to prioritize planning or learning more about shared with design lead and PM 

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
I believe we reviewed these, right @audreykwr . Or at least enough to close this ticket?

**Comment by audreykwr** [comment]
@chris-kuryak yes I'm fine closing this
