### ISSUE TITLE
Bug: Weird error message:  `Error in item **%%placeholder**`

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1335]
I think if the tracking_id field is missing, we get weird error messages.   I see stuff like:

```
Error in item **%%placeholder**: Empty value for 'deviceName' ('equipment_model_name')
Error in item **%%placeholder**: Empty value for 'performingFacility' ('testing_lab_clia')
Error in item **%%placeholder**: Empty value for 'patientState' ('patient_state')
```

if I submit data that has normal column headers plus a row of just commas, eg ,,,,,,,,,,,,,,,,,,,,,, etc

Per our other discussions, I think we should be giving the row number ("index" I'm calling it, to also account for HL7 ingests), so that can be used to identify the row, in addition to the trackingId.

### Acceptance Criteria

- The word 'placeholder' does not seem to be in our code any more, but its still worth checking to see if an error occurs, perhaps using the above ,,,,,,,, idea)
- if you can recreate the bug, fix the bug.

**Comment by jimduff-usds** [comment]
Same as #1688 ???

**Comment by oslynn** [comment]
In latest code the CsvSerializer.kt: mapRow doesn't use %%**placeholder** anymore.  It uses "" instead.  Therefore, I am closing this ticket.
