### ISSUE TITLE
Refine Receiver Settings Improvement Ideas

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13364]
## Problem statement
There is still some info needed on receiver settings to be able to chart a clear path forward.

## What you need to know
- Follow on to ticket #13185 
- [Mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1707143235464/93e77ab0af79ae95da8906218c8b5ae7b1067e47?sender=u1cb5f3c6aed590b290728229) showing research, lift, and "happy path"

## Acceptance criteria

- [x] Meet with engineers to gather feedback on how to accomplish the "happy path". Identify hidden complexity and dependencies.
- [ ] Clarify the deployment infrastructure and align with settings functions.
- [x] Get a review from Victor on overall technical approach.
- [ ] Sync with Chris and Jillian

**Comment by jakefishbein-navapbc** [comment]
https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1707143235464/93e77ab0af79ae95da8906218c8b5ae7b1067e47?sender=u1cb5f3c6aed590b290728229

**Comment by jakefishbein-navapbc** [comment]
Meet with Victor to review the current concept and got a thumbs up to move forward. This will likely need a good deal of technical design prior to moving into ux/ui iterations.

**Comment by jakefishbein-navapbc** [comment]
Met with Chris and Jillian. Determined that the next step was to have an engineering review of the existing plan to formal note feasibility and approach.
