### ISSUE TITLE
Explore updates to News UI for better link sharing

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#13369]
## User story

As a user, I want to see a clear preview of what link someone is sharing with me, so I can know if I want to open it.

## Background & context

Our current News page design only allows for sharing the entire page, not individual articles. As news articles are great to share and best shared individually, our current design limits that functionality. In coordination with engineering feedback, this explores possibilities to add more individual news article pages to evaluate lift and priority.

## Acceptance criteria

-   [x] Possible ideas discussed with design lead
-   [x] Next steps for further definition or eng sync planned

**Comment by chris-kuryak** [comment]
Considering using "collection" component from USWDS.

This now needs to be reviewed through engineering for scoping.

**Comment by audreykwr** [comment]
[Figma link.](https://www.figma.com/file/86JATe4hOwPfihwwloM5b8/Blockframes?type=design&node-id=952%3A3934&mode=design&t=uESD35FMm1IELUDu-1)
