### ISSUE TITLE
[BUG] Logic to default to Daily Data instead of Data Dashboard not working for all receivers

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13385]
## Problem statement
Some of our receivers are CSV Download receivers. The Data Dashboard will not work for them. Therefore, when logging in or clicking on Dashboard in the Nav Bar, they should be taken to the Daily Data page, not the Data Dashboard page.

## What you need to know
- I have checked the following orgs that are not being redirected:
  - Pima County receiver org = `pima-az-phd`
  - Chester County receiver org = `pa-chester-phd`
- Original ticket that introduced this logic and the list of receivers is here: #11181

## Acceptance criteria

- [ ] Pima County and Chester County should be defaulted to Daily Data instead of Data Dashboard when
  - [ ] Logging in
  - [ ] Clicking on Dashboard in the Nav Bar
- [ ] All other CSV Downloaders checked as well to ensure they are working properly
  - [ ] ca-sbc-phd
  - [ ] ca-scc-phd
  - [ ] co-routt-county-phd
  - [ ] co-san-juan-basin-phd
  - [ ] fl-hillsborough-phd
  - [ ] oh-ccchd-doh
  - [ ] pa-montgomery-phd
  - [ ] pa-philadelphia-phd

**Comment by penny-lischer** [comment]
@chris-kuryak  None of the orgs are working in prod due to a refactor that was made in Nov
