### ISSUE TITLE
Discuss transition with DevOps to identify any changes needed to CI/CD and/or Docker container

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1338]
### Acceptance criteria
- Answer the following questions:
  - How do we build the React site
  - How do we serve the React site in Docker?
  - How do we run the React testing suite on the local dev environment?
  - How do we run integration testing locally?
  - How do we run dynamic testing and code coverage for React
  - How do we run the testing tools in GitHub actions on PR creation?
  - Can we build a set of testing scripts for automated testing with Node, Puppeteer, etc?

**Comment by td-usds** [comment]
#1628 is a start at containerizing the React Front-End.

**Comment by Bisonburger** [comment]
Need to run react-snap or similar to create a static site

**Comment by jlusds** [comment]
What's the status of this?

**Comment by ronaldheft-usds** [comment]
My understanding is we decided we are still running a static site vs. a Docker container, so only support DevOps needs to provide is ensuring the build process remains working with react.

**Comment by cwinters-usds** [comment]
React site is deployed and functioning. We'll work separately on automated integration testing.
