### ISSUE TITLE
App and related component/service simplification and mock cleanup

### ISSUE THREAD

**Issue by jpandersen87** [CDCgov/prime-reportstream#13388]
Parent #12426

## Description
Some of our components and services can be simplified to require less custom code and scaffolding, as well as cleaning up mocking in these areas.

## Impact
- Time savings for FE engineers (auto-mocking rather than wrapping things, with custom function, with the necessary library code). This eliminates from having to run the custom function in a bunch of different areas/tests.

## Acceptance Criteria
- [ ] App is in control of rendering at root, not react-router
- [ ] AppInsights customization is based off officially provided classes and patterns so as not to stray if/when we can drop customizations
- [ ] Objects used for creating mock objects moved to fixture-named files/folders
- [ ] Start usage of global automocks for common libraries/local modules

**Comment by chris-kuryak** [comment]
Pausing to await conversation around moving away from our traditional SPA framework

**Comment by chris-kuryak** [comment]
From Joseph: Moving forward without SPA conversation because it will have benefits regardless.

**Comment by chris-kuryak** [comment]
@jpandersen87 Can you give an update on this in the comments when you are back?
