### ISSUE TITLE
UT - SFTP Info Request & Platform Update

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#13395]
## **Problem Statement**

We received an email in the ReportStream inbox from Utah DCP Informatics regarding their plans to upgrade their SFTP environment soon, and they have requested certain information.

## **What you need to know**

Email received on 2/15/24:

> Hello,
> 
> I wanted to reach out because we’re updating our SFTP accounts at the Utah Dept. of Health & Human services for Reporting. We need your help to ensure a smooth transition to our new secure file transfer environment. Could you reach out with a response with the following information?
> 
> 1. **Type of Reporting:** Please tell us which applies to you:
> - Reporting ELR only
> - Reporting Syndromic Surveillance only
> - Reporting both ELR and Syndromic Surveillance
> 2.  **Account Usage:** Confirm if your SFTP account is active. If you’re not using it anymore, let us know.
> 3.  **Contact Info:** Ensure we have your latest contact details. Reply with your current email and phone number. If there is someone else we need to reach out to, please provide their information.
> 4. **Migration Heads-up:** We’re moving active SFTP accounts to a new platform soon, requiring your input for setup and testing. Details to follow.
>
> Your quick response is crucial.
> 
> If you have any questions, please reach out at edx@utah.gov.
> 
> Thanks very much!
> 
> Brock McKeown

## **Acceptance Criteria**

- [ ] Provide requested SFTP information to UT DCP

## **To Do**

- [ ] Collect requested SFTP details and provide them to UT DCP Informatics

## **Additional Comments**

No specific dates have been provided for this process yet.

**Comment by LaFreda1** [comment]
@wcollin89 Here's the info requested: 

Type of Reporting: Please tell us which applies to you:
Reporting ELR only

Account Usage: Confirm if your SFTP account is active. Yes

Contact Info: reportstream@cdc.gov; Glenn Grieves, Account Manager (uum5@cdc.gov)

**Comment by TaneaY** [comment]
Closing and updating to seperate work needed- This is ticket will serve as collection of information. Correspondonce states Utah will reach out with further details on the testing phase. Support will open a new ticket at that time.
