### ISSUE TITLE
Identify the first round of React components we will build

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1342]
We should create a running list of React components we will build for the transition. We can do this as a meeting like a bug bash, or we can just create an issue in ZenHub and start listing out what we think, and do that discussion asynchronously to start. @drew-usds this is your area of expertise, so you should definitely guide this.

**Comment by Bisonburger** [comment]
This is OBE
We will create the same components as in the older eleventy site
