### ISSUE TITLE
Double-check that mapping is working properly for CA

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13435]
If we receive a multiplex result from CA, that COVID is being removed and not being sent to CA.

**Comment by LaFreda1** [comment]
To complete after we finish code to condition mappings

**Comment by GilmoreA6** [comment]
937 items for the condition-test receiver vs. 966 items for the full-elr-saphire receiver. Cause of discrepancy currently unknown.

**Comment by GilmoreA6** [comment]
Investigated discrepancy and found that it is due to 2 covid devices that are not on the LIVD table being sent to the full-elr-saphire receiver:

CDC 2019-nCoV Real-Time RT-PCR Diagnostic Panel (CDC)
TaqPath COVID-19 RNase P Combo Kit 2.0

These will need to be added to the COVID supplemental table
