### ISSUE TITLE
Create documentation on how to run FE E2E tests on RS

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13436]
## Problem statement
There is no standard procedure outlined for how to run E2E tests for a RS page.

## What you need to know

- E2E tests have been finished for the Homepage (public) and Daily Data page (authenticated)

## Acceptance criteria
Captured in Github documentation is:
- [x] Guidance on how to run an E2E test on a public page and authenticated page
- [x] Guidance on what to do if a test fails and how to check what has failed
- [x] Guidance that when you create a PR you should be running the E2E tests
- [ ] Review with rest of team at engineering sync

**Comment by penny-lischer** [comment]
[e2e Guidance](https://github.com/CDCgov/prime-reportstream/blob/87bee811663e15d3a13bc2a4f362fde4540d0c0d/frontend-react/docs/standard-operating-procedures/e2e-frontend-guidance.md)
