### ISSUE TITLE
Add updating E2E tests to our standard process on changing/fixing webpages

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13444]
## Problem statement
To ensure we don't forget to update our E2E tests, we need to add this as standard process.

## What you need to know
- https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B18EED449-24D1-49D4-8EC3-8A9D8233C11E%7D&file=ReportStream%20Development%20Process.docx&action=default&mobileredirect=true

## Acceptance criteria
- [x] Review document, make note of anything that may be missing
- [x] Add updating our E2E tests to the document about PR processes

**Comment by chris-kuryak** [comment]
There is a guide for things to look out when reviewing PRs

**Comment by penny-lischer** [comment]
@victor-chaparro please verify
