### ISSUE TITLE
MDPH Missing Files 2/11, 2/17, 2/18

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#13466]
## Problem statement

We received an email from Massachusetts stating that they were recently unable to make an ELR connection with us.  They have asked us to confirm if we sent any data on 2/11, 2/17 or 2/18. 

## What you need to know
Email: 

Good afternoon,

 

We failed to make an ELR connection with you on 2/11, 2/17, 2/18. Please resend any files from this date otherwise confirm there were no submissions.

 

Thanks,

Deni Hamiti

Research Analyst

Division of Surveillance, Analytics and Informatics 

Bureau of Infectious Disease and Laboratory Sciences

Massachusetts Department of Public Health

305 South Street, Jamaica Plain, MA 02130

Email: deni.hamiti@mass.gov

Phone: (617) 952-3514

## Acceptance criteria

- [x] Confirm if we sent them data on the dates listed above. 
- [x] Respond to the email with an update
- [ ] (if needed) Investigate what caused this

**Comment by LaFreda1** [comment]
We need to resend data from 2/18. I am assigning to an engineer now

**Comment by oslynn** [comment]
We don't any message to ma-phd.elr on 2/11 and 2/17.
We have one message (file: prime-20240219005039.hl7) sent on 2/18.  Therefore, I will resend this file to them.

**Comment by oslynn** [comment]
Done.
