### ISSUE TITLE
Missing Data from MT ELR feed and Daily Data

### ISSUE THREAD

**Issue by OHoward2023** [CDCgov/prime-reportstream#13475]
## Problem statement

Montana emailed into the SimpleReport inbox to inquire about an organization that successfully submitted data through SimpleReport on 02/19/2024 but the data did not make it to daily data or MT ELR feed in ReportStream.

## What you need to know

The Report ID in SimpleReport matches the Report ID in Metabase, however when checking both Daily Data and Data Dashboard, I was unable to find the Report ID. The picture attached is from Metabase.

## Acceptance criteria

- [ ] ...

## To do

Please confirm the results and resubmit the data. Please let support know when this is complete so we can reach out to MT.

**Comment by OHoward2023** [comment]
![MT](https://github.com/CDCgov/prime-reportstream/assets/126623267/eb1808e1-d473-45d8-9207-f12657e0fddb)

**Comment by OHoward2023** [comment]
@adegolier Hi Angela, may I have an update on this ticket please?

**Comment by LaFreda1** [comment]
@OHoward2023 reassigning this ticket. Thanks

**Comment by wcollin89** [comment]
Hello, @adegolier @LaFreda1 the user has reached out for an update on this resubmission. Please let us know once this has been completed.

Thank you!

**Comment by oslynn** [comment]
@wcollin89 the reason why their message didn't go through is the message contains an invalid Specimen_type_code (i.e. 1293160008) and Equipment_Model_ID is empty.

Please ask them to resubmit with a valid **Specimen_Type_code** and Equipment_Model_ID = "Xpert Xpress SARS-CoV-2" as given above.  After they resubmitted, please let me know.  I will check to mak  sure it goes through.

**Comment by wcollin89** [comment]
Hi @oslynn I appreciate you providing that info to Support.

I reviewed the org's submissions in SimpleReport and this result was entered manually rather than by CSV. It has also been corrected - the message ID for the correction is `c6ddede9-ed9f-49a4-906f-816f3a6e4860`, and it shows a Previous Message ID of `43694f3d-786a-47a0-9e02-641aa9d9788a`.

**Comment by oslynn** [comment]
@wcollin89 thank you for letting me know.  I checked the message ID: c6ddede9-ed9f-49a4-906f-816f3a6e4860.  And, it went to MT-ELR successfully.  Therefore, I will close the ticket.
