### ISSUE TITLE
Create documentation around how to maintain the Code to Condition table

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13495]
## Problem statement
There is currently not enough documentation around how engineers should handle updating the code to condition table in the UP.

## What you need to know

- Example: If we receive notification of a new code, or if the logs determine we have unmapped code/condition values, how do we (Engagement engineering team) go in to update the table to include those new values?
- What should we be looking at in the logs to determine we are missing a mapping? Do messages need to be resent after adding new mapping?
-  How do we determine what condition a LOINC code maps to?
- When a new sender is onboarded what's the process for getting their supported LOINC codes, checking if their LOINC codes are already mapped, mapping them to conditions and updating the table.

## Acceptance criteria

- [ ] Process for updating missing code-to-condition mappings is documented
- [ ] Documentation for onboarding senders is updated with process on how to maintain their supported conditions
- [ ] Present new processes to the team

**Comment by LaFreda1** [comment]
To place in getting started-> SOP in github repo
