### ISSUE TITLE
Ensure all "inactive" receivers on the COVID pipeline have allowNone() jurisdictional filter

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13494]
## Problem statement
On the COVID pipeline, if a receiver is marked as "inactive" it (1) still appears on the organization's Daily Data page and (2) may still be sending the report to that receiver. Neither of these two actions should be happening on receivers marked as inactive.

## What you need to know
- Chris and Victor investigated to figure this out, so consult with them if you see something different.
- In order for messages to not get routed to "inactive" receivers, the jurisdictional filter needs to be marked as "allowNone()"
- For COVID pipeline receivers, the jurisdictional filter needs to show: 
`[
  "allowNone()"
]`

## Acceptance criteria

- [ ] In Staging, all receivers that are marked as "inactive" in the COVID pipeline have a jurisdictional filter that says "allowNone()"
- [ ] In Production, all receivers that are marked as "inactive" in the COVID pipeline have a jurisdictional filter that says "allowNone()"

**Comment by oslynn** [comment]
2024-03-11 at 3:50pm done.
