### ISSUE TITLE
Create Integration Tests for FHIRConverter

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#13507]
### User Story

As a developer of the Universal Pipeline,
I want to have integration tests that ensure `FHIRConverter` updates the system state correctly and produces correct outputs,
so that I can confirm the pipeline step is working properly.

### Description/Use Case

The integration tests should use both the database and azure blob test containers and verify both are updated correctly given certain inputs to the function.

### Acceptance Criteria

- [ ] Created one or more integration tests for the pipeline step that gives confidence the step is working as expected

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13507?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
