### ISSUE TITLE
What are your topics for today's (Mon June 21) Dev-sync?

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#1350]
Add your discussion items as a comment here. Meeting is at 1pm ET.

**Comment by carlosfelix2** [comment]
1. Duplicate field in Covid schema: 
- name: result_format
    type: TEXT
    default: CWE
    natFlatFileField: Result_format
    hhsGuidanceField:
    hl7Field: OBX-2

- name: value_type
    type: CODE
    natFlatFileField:
    hhsGuidanceField:
    hl7Field: OBX-2
    valueSet: hl70125

**Comment by jimduff-usds** [comment]
Add your discussion items as a comment here. Meeting is at 1pm ET.

@mauricereeves 
@Mr0grog
@mry-usds
@RickHawesUSDS
@ronaldheft-usds
@joemeree
@tlosbo
@pathikkothari
@td-usds
@pablocaviglia

**Comment by jimduff-usds** [comment]
These two topics were left over from last week:

1. (Jim) A question came up about sending data to ReportStream directly from a mobile device.
2. (@carlosfelix2 ) _BLANK types and cardinality.

**Comment by joemeree** [comment]
*	Dashboard for new senders progress
*	HL7 promoted to production 
*	Daily sender volume email report (with errors, warnings, and
successes) 
*	Daily receiver volume email report (reconciled with sender volume?) 

 

Joe Meree  AI Architect  DataRobot  cell:703-967-4730
***@***.***> ***@***.***

**Comment by jimduff-usds** [comment]
All - I'm going to CANCEL for today, June 21.   Grab your hour back; there are a lot of meetings today anyway.
- @joemeree :     @anshulkumar-usds  and I can catch up with you on the items you mentioned
- @carlosfelix2  - @MauriceReeves-usds and I can deal with the duplicate field.
- And the two topics I mentioned are not pressing.

(And based on the new team meeting schedule, we might move to another day next time...)

**Comment by ronaldheft-usds** [comment]
IP address CIDR proposal: https://github.com/CDCgov/prime-reportstream/pull/1407

**Comment by td-usds** [comment]
- [TEUs](https://en.wikipedia.org/wiki/Twenty-foot_equivalent_unit) for everything: running the development dependencies in docker: [2021-07-19 - Dev Sync - TEUs.pdf](https://github.com/CDCgov/prime-reportstream/files/6841801/2021-07-19.-.Dev.Sync.-.TEUs.pdf)
- Status check on Enforcing [Signed Commits](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/signing-commits.md)
