### ISSUE TITLE
Create Performant End-to-End UP Tests

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#13505]
### User Story

As a developer of the Universal Pipeline,
I want to have tests that ensure reports are being delivered successfully and have the expected contents,
so that I can confirm the system is working properly.

### Description/Use Case

Presently, `testEnd2EndUP` takes a lot of time to execute due to inefficient polling and is only testing lineage, something that can be more efficiently tested on a lower level, like UP step-specific integration tests. This ticket aims to create a new end2end test that executes faster and tests that a report was correctly received instead of querying to check lineage is correct. 

This new set of end2end tests should:
- Verify Report is correctly sent to expected receiver for full-elr topic
- Verify Report is correctly sent to expected receiver for elr-elims topic
- Verify contents of received report are as expected
- have a low execution time

This new set of end2end should NOT:
- Thoroughly test various parts of the pipeline, like routing and translation. That can be left up to the integration tests of each of the various pipeline steps

### Acceptance Criteria

- [ ] New set of performant end2end tests created for UP that verifies the basic functionality of the system

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13505?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13505?planning-poker) with Zenhub @brick-green

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13505?planning-poker) with Zenhub @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @adegolier

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13505?planning-poker) with Zenhub @adegolier
