### ISSUE TITLE
Create Integration Tests for FHIRRouter

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#13506]
### User Story

As a developer of the Universal Pipeline,
I want to have integration tests that ensure `FHIRRouter` updates the system state correctly and produces correct outputs,
so that I can confirm the pipeline step is working properly.

### Description/Use Case

The integration tests should use both the database and azure blob test containers and verify both are updated correctly given certain inputs to the function.

### Acceptance Criteria

- [ ] Created one or more integration tests for the pipeline step that gives confidence the step is working as expected

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13506?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @mkalish @thetaurean @JFisk42

**Comment by Andrey-Glazkv** [comment]
@adegolier please have a look if you could take this one

**Comment by david-navapbc** [comment]
I have gotten to the point where I understand the basic idea of what's going on in here. In particular I've been sussing out what the `ReportStreamFilter` is doing and how it works. I see now there's a query mechanism for FHIR documents and Strings in `FhirRouterTests.kt` (like `OBSERVATION_COUNT_GREATER_THAN_ZERO`). 

Next steps are to use [this PR](https://github.com/CDCgov/prime-reportstream/pull/14183) as a basis to come up with a test plan.

**Comment by david-navapbc** [comment]
making a note here in case anyone who is also new to kotlin runs into this and searches the issue list for guidance. 

https://github.com/CDCgov/prime-reportstream/blob/4d5561993c63192be41154bc2ea62c4e2652500f/prime-router/src/test/kotlin/fhirengine/engine/FhirRouterTests.kt#L420

what's going on with that function definition enclused in backtics "`" is kotlin allows you to put spaces in test function signatures so long as they are enclused in "`" 

https://kotlinlang.org/docs/coding-conventions.html#names-for-test-methods
