### ISSUE TITLE
Draft of ReportStream content for SimpleReport website

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13517]
## Problem statement
The SimpleReport website needs updated content regarding ReportStream.

## What you need to know
Found some [out of date content](https://www.simplereport.gov/getting-started/public-health-departments/about-prime-reportstream/) about ReportStream on SimpleReport's site. We will confirm if there is anything else need to be updated and get at least a draft to SimpleReport for review and plan the updates.

## Acceptance criteria

- [x] Content drafted and sent to SR for review
- [x] Follow up finalizing/publishing plans created

**Comment by audreykwr** [comment]
[Content](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BE5D4DB7C-CEE5-4DB3-8E75-40F3D32F0852%7D&file=20240307_SR_Site_Update%20.docx&action=default&mobileredirect=true) approved by Mo, in SR's hand for implementation. In contact with Jayna for track progress.
