### ISSUE TITLE
Texas HIV Pilot: Develop a list of data producers that address the need

### ISSUE THREAD

**Issue by jakefishbein-navapbc** [CDCgov/prime-reportstream#13524]
## Problem Statement
In an effort to be prepared for a meeting with Texas around closing any potential gaps in reporting for HIV in Texas.

## What you need to know
- Aligned internally on [pilot planning document](https://teams.microsoft.com/l/message/19:meeting_MmQyNjk3MTYtNGZkMC00ZjIxLWFjMDUtNmQ5ZDA2NDE1ZjIx@thread.v2/1713813239343?context=%7B%22contextType%22%3A%22chat%22%7D)
- Getting buy in with SimpleReport happened April 25.
- Meeting with Texas scheduled for May 15.

## Acceptance criteria
- [x] Identify first 10 counties to prioritize in the Pilot Document that has already started (including how you arrived at that priority)
- [x] Identify 1 HIV sender per county (if possible) in the Pilot Document
  - [x] Identify which of those senders already are in the SimpleReport database (if any)

**Comment by MikaelahD13** [comment]
Update:  currently Building out the list and rationales

**Comment by jakefishbein-navapbc** [comment]
List of counties with rationale can be found [here](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/02_Research/Health%20Equity/ReportStream%20Health%20Equity%20Initiative.docx?d=we17f23c483484fbdb4d8dc099df609bd&csf=1&web=1&e=yfcba7&nav=eyJoIjoiMTA5Njk4MTg5In0).

**Comment by jakefishbein-navapbc** [comment]
Will be drilling down list to a more focused set of counties based on MUA.
