### ISSUE TITLE
Have a basic Sender CRM setup working

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1352]
- parallels existing Receiver CRM system
- follows our 5 or so basic steps (with better names):   Pre-Kickoff, Kickoff held, Customer has Staging Key, Customer in Training in Prod, Customer fully in Prod.
- has some kind of quick summary view or thermometer chart.
- is readily accessible

**Comment by anshulkumar-usds** [comment]
Currently being tracked in Sharepoint: https://cdc-my.sharepoint.com/:x:/g/personal/rdz8_cdc_gov/EZQLc0BV5q9GrAt40HAEIfEB715kbdY2DdSlLBlQ0PY1BA?email=qop5%40cdc.gov&e=bL0zaJ
