### ISSUE TITLE
Daily Data Search/Filter cleanup

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13540]
## Problem statement
Some items/functionality was missed during initial creation.

## What you need to know
- The updated API to request `active` and `testing` is coming from Penny's ticket #13480 (https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/13480)
- Recreating Bug # 1 
  - If I have a sorted table (2/6/2024 - 2/7/2024)
  - and then I manually delete the dates in both date fields (using the delete key on my keyboard)
  - I click apply
  - Nothing happens

## Acceptance criteria

- [x] Update default state of the filters such that no receiver service is selected upon page load, and all active and testing receivers are shown in the table upon page load (no inactive receivers)
- [x] In response to Bug # 1 (above), if the user manually deletes the date fields, the "Apply" button should be disabled
- [x] (regression): if a user searches for something, it should SUPERSEDE any applied filters and clear filters upon submittal.
- [ ] Add/update unit tests
- [x] Fix bug where the count that is shown is not getting cleared out when switching from an org with data to an org without data.

**Comment by etanb** [comment]
After discussing with @chris-kuryak @jsutantio @audreykwr we're going to punt on any additional explainer text (for now) but have settled on these two options if we want them for the future:

**Option 1:**

<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2xuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9daba4456815d63850d5b76b8ac0a1048f7bc6bd/image%20%286%29.png" alt="image (6).png" />


**Option 2:**

<img width="1275" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3BuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cfb97f144891ca4e5730635bfedf88049e915eee/image%20%287%29.png" alt="image (7).png" />
