### ISSUE TITLE
Write a proposal for a History API

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1356]
This story is DONE when a proposal is done (in prime-router/docs/proposals) and a correspodning openAPI spec for a history/audittrail API is documented as well.

Tasks:
- consult with JIm
- consult with Jim and @MauriceReeves-usds 
- consult with @Bisonburger  about what history info his tool needs
- ok if you come up with a small number of initial use cases.  Document these in the proposal.
- use the same security, architecture, style and code structure as existing Settings API.

**Comment by tlosbo** [comment]
Summary of steps taken for this task:

- Initial proposal created in the the docs folder (https://github.com/CDCgov/prime-reportstream/pull/1481)
- Met with Jim to discuss and collaborate on 2 different sessions
- Consulted with Mo on best practices for query string params, pagination, response body etc.
- Presented to the team at Engineering Sync and got some feedback and consideration to use a search engine (ElasticSearch, SOLR)
- Followup meeting to discuss how a search engine / tool could help us. Decided against for now
- Next steps are to build the following queries as test cases to see if we have the data we need:
-- Sender Focused: What happened to my data?
-- Receiver Focused: What kind of volume changes/anomalies do I see from my Senders 
-- Receiver Focused: My report is in error - did ReportStream mess up or did the Sending lab mess up
