### ISSUE TITLE
[BUG] Temporary fix to Daily Data API to include ELIMS files

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13578]
## Problem Statement
The Daily Data page does not show ELIMS data.

## What you need to know
- ELIMS data passthrough does not go through the batch step, which is the step that Daily Data API queries.
- The temporary fix involves changing the call to something like this:
`OR ("public"."action"."action_name" = cast('send' as "public"."task_action")
and "public"."report_file"."schema_topic" = 'elr-elims'))`
- For questions, go to Victor

## Acceptance criteria
- [x] All ELIMS sent items appear in the Daily Data table alongside other data in accordance with existing logic
  - [x] ELIMS Daily Data Page in Staging
  - [x] NY-PHD Daily Data Page in Staging
  - [x] CA-PHD Daily Data Page in Staging
- [ ] Spotcheck 4-5 receivers Daily Data pages that are NOT receiving ELIMs data to ensure they are not affected by this change

**Comment by penny-lischer** [comment]
@chris-kuryak the UI does not support ACTIVE and TESTING currently and will need to be played in order to meet the first criteria.

**Comment by chris-kuryak** [comment]
Waiting on Index to be created
