### ISSUE TITLE
Investigate Terraform sync mismatch

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#13585]
Please investigate why we are seeing the following and what it will take to get to 0 change-count
```
Alert Terraform Changes
Current Terraform Plan Changes in prod env
change-count: 5

Current Terraform Plan Changes in staging env
change-count: 4
```

**Comment by supriyaaddagada** [comment]
Synced staging and prod terraform code, now the issues are down to 2 in staging and 2 in prod, last 2 issues are generated from null_resource admin function app from GitHub action
