### ISSUE TITLE
Texas - File Exchange Folder Update

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#13583]
## Problem statement

Texas needs to update the folder

## What you need to know

Currently, Texas DSHS receives your COVID ELR submission via Globalscape (sftp-labs.dshs.texas.gov) with ID idielr007.

We have done some file exchange folder updates on our end and need you to begin sending your production files to the /prod folder.

Currently, you are dropping these files in the home/root folder.  

Files dropped in the /prod folder are forwarded to our NEDSS surveillance system. Since your files are being dropped in the home/root folder, it requires scripts in the backend to moves these files to the /prod folder.

Please let us know when this update is made and we will monitor the incoming files.

## To do

Send production files to /prod folder

**Comment by GilmoreA6** [comment]
@rnz6 @TaneaY I can update this for Texas, can we confirm with whomever sent the email that the full filepath that want us to send to is just "./prod"?

**Comment by rnz6** [comment]
Followed up with Texas, awaiting response

**Comment by rnz6** [comment]
@GilmoreA6 

Good morning,

Drop your production files in /prod folder.

You are currently dropping fles in home or “/” folder. We have made some changes to routing/monitoring at our end which require your production feed to got to /prod folder and not “/” folder.
 
Thanks,

Shamim

**Comment by GilmoreA6** [comment]
@rnz6 @TaneaY 

This has been completed
