### ISSUE TITLE
Create SWE Requirements Doc for RS Routing

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#13604]
### User Story
As a ReportStream developer,
I must understand the software requirements for routing,
so that I can implement routing properly

### Description/Use Case
We should evaluate the [outputs of the routing discovery sprint](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Discovery%20Sprints/UP%20Routing%20Disco%20Sprint.docx?d=w249361b3cfbd482db713df4c2cc63918&csf=1&web=1&e=9Wxg7v) and any other lessons learned to compile all the routing requirements of ReportStream and translate them to actionable software requirements that a software design document or implementation could reference.

### Acceptance Criteria
- [x] Software requirements doc created: https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engineering/Design/SRD-Routing.docx?d=w3a2fa783e8dc4e9b8397da9f5d968dfa&csf=1&web=1&e=Di1Hzi
- [x] Software requirements doc approved by product - @brandonnava 
- [ ] Software requirements doc approved by engineering
    - [x] Platform - @mkalish, @thetaurean 
    - [ ] Engagement
- [x] Software requirements doc approved by design - @jsutantio 
- [ ] Follow-up tickets created

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13604?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @JFisk42 @mkalish
