### ISSUE TITLE
Disable SafeHealth reporting to HHS Protect when it comes through the Oracle interface

### ISSUE THREAD

**Issue by joemeree** [CDCgov/prime-reportstream#1361]
SAFE submissions can get to HHS Protect (Protect) 3 ways.  
1. SAFE -> WATERS -> Protect, 
2. SAFE -> ReportStream production
3. SAFE -> WATERS -> Oracle -> RS interface -> HHS Protect  (can we disable this one?)
We intended for 1 and 2 but not 3. 

Not a big deal with low volumes and actually gives us a 3rd source for Kevin to reconcile in Protect.
We should be able to reconcile 1 and 2 and then turn off Oracle WATERS.

**Comment by jimduff-usds** [comment]
Done.
