### ISSUE TITLE
Add filename to the Submission Table API call and return in the File Column of the submissions table

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13620]
## Problem statement
The "File" column of the submissions table is currently showing as empty.

## What you need to know
- The submissions page: https://reportstream.cdc.gov/submissions
- The column already exists in the table, but it is showing up empty
- According to Victor, the API is not returning the filename
- So we need to fix the API to return filename, and then add it into the table

## Acceptance criteria

- [x] Submissions page API call also returns 'filename' of the submission
- [x] Submissions page table populates the File column with the 'filename'
- [x] Update Swagger 
- [x] Update E2E

**Comment by jpandersen87** [comment]
@GilmoreA6 Do you have some insight to this? Should we be using the `external_name` column or another?
