### ISSUE TITLE
FQHC in-depth synthesis and research report

### ISSUE THREAD

**Issue by dylansmith-Nava** [CDCgov/prime-reportstream#13627]
### User Story
As a researcher on ReportStream, I want to conduct in-depth synthesis of all FQHC/HCCN interviews as well as the ECR interview, so that I can form the research report with proper recommendations for scrum teams, Design teams, and Product team, to make advancement on the FY24 OKR for publicly-funded senders.

### Background
Through this initiative, we are trying to uncover FQHC (federally qualified health center) reporting requirements for ELR data, so ReportStream can gain a better understanding of how we could integrate similar publicly-funded Senders. Bonus points to also understand FQHC's user ecosystem, including personnel and their critical jobs. See tickets #[12960](https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/12960), #[13198](https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/13198), and #[13527](https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/13527).

### Risks/Impacts/Considerations
- Remaining open questions from the research may introduce more dependencies and avenues for research that delay us from receiving a satisfying answer to the relevant FY24 OKR
- The appropriate recommendations are not within ReportStream's technical and/or business capabilities, which would mean a more significant shift to the OKRs than expected
- Smaller sample size of organizations interviewed may mean that results aren't as statistically significant as the team would have liked

### Open Questions
- How should ReportStream best connect to FQHCs? Should it be 1-1, through HCCNs, via EHR vendors, or through a different channel?
- Should FQHCs care or need to know about the differences between ECR and ELR?
- What recommendations are feasible? Which ones would be too far in the future?

### Links
- [FQHC Reporting](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1705940727150/d100619ea4f5bdc0a6d8a9c7e7ea0ec162a7557d?sender=ufb3824a0e63fafb0304f5774)
- [FQHC Direct Research Proposal](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B3a1a7085-87f2-48c5-b1c3-f2d354dd5baa%7D&action=edit&wdPid=496e8a91)
- [FQHC recruitment materials](https://cdc.sharepoint.com/teams/ReportStream/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FReportStream%2FShared%20Documents%2FDesign%20and%20Research%2F02%5FResearch%2FFQHC%20Reporting%20Requirements%2FResearch%20and%20Recruitment&viewid=6255f791%2D133e%2D4cae%2D9185%2Db78c974e99f2)

### Acceptance Criteria
- [x] Conduct in-depth synthesis of each interview conducted
- [x] Create first draft of Research Report
- [x] Share-out of WIP Research Report to Platform team and design team as needed
- [x] Work on recommendation list with Product mgr to have them form recommendations
- [ ] Create final draft of Research Report

### Out of Scope
- Onboarding any FQHC to ReportStream or offering such during an interview
- Outlining any new technical strategies coming out of the recommendations
- Updating any OKRs

**Comment by dylansmith-Nava** [comment]
[Research report](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B993c0414-bd0a-4835-acce-889b04a1562d%7D&action=edit&wdPid=56821896) was reviewed by the Design team and is being prepared for a final review and shareout with Product. As such, I feel comfortable moving this ticket to Product Review. cc @Andrey-Glazkv

**Comment by Andrey-Glazkv** [comment]
@brandonnava do you think this one is good to be closed?

**Comment by brandonnava** [comment]
Looks good! Closing out
