### ISSUE TITLE
Create HL7 Schema for Oregon ELR

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1364]
Oregon wants to onboard with us!

We will need to create a HL7 file schema in the application for Oregon. Here is the link to the spec: [OPHD ELR HL7 Implementation Guide](https://www.oregon.gov/oha/PH/DISEASESCONDITIONS/COMMUNICABLEDISEASE/REPORTINGCOMMUNICABLEDISEASE/ELECTRONICLABREPORTING/Documents/OR%20ELR%20HL7%20251%20Implementation%20Guide%20v.4.12.pdf)

Acceptance criteria:
- There is a directory created for the OR schema in [the schema folder](https://github.com/CDCgov/prime-reportstream/tree/master/prime-router/metadata/schemas).
- The schema file is created. Typical naming convention is `state abbreviation-topic.schema` so `or-covid-19.schema`
- Fill in the schema file so the records OR wants are output in the order they've requested. To see an existing HL7 schema, look at the AZ HL7 files: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/metadata/schemas/AZ/
- Update `quick-test.sh` to generate a fake OR HL7 file via the CLI

Notes:
- `quick-test.sh` is a bash shell script that generates fake data and then outputs it into different schemas. You should take a look at the file itself to see how to run prime on the command line. The typical way to invoke `quick-test.sh` is to pass it the two-letter abbreviation for the state, or `ALL` to run all the tests. There are examples in quick test of us doing a complete roundtrip, meaning generating a file, outputting it to the AZ and Pima formats, then ingesting it back, and then outputting the files again and comparing to make sure there are no gaps. I recommend you do the same for the OR file
- at the top of each schema file is some header information, including the topic (right now just "covid-19" though that can change, and the `trackingElement`, which specifies which field is the unique key for this schema. The most important thing to note is that schemas can inherit from each other via two mechanisms: `basedOn` and `extends`. `basedOn` works like a Ruby mix-in in that you are pulling that base schema, but you have to manually specify which fields you want to include in the final output. `extends` on the other hand, means that ALL the fields of the base schema are automatically included. The difference is subtle, yet important
- we have mappers, which are functions that get invoked during a two-pass generation of the data on the second pass. They are pure functions which take a series of arguments and return a `String?` value. An example would be `concat(organization_name, testing_lab_name)` which tells the serializer to take the values in organization_name and testing_lab_name and concatenate them into a single value. To refer back to the point about basedOn/extends, if you used `basedOn` and you have a mapper that refers back to a field you didn't explicitly include, the mapper will fail and so will your serialization to CSV or Hl7.
- by default we have and use standard LOINC codes for certain values like race, ethnicity, gender, etc but if you look at the Pima and AZ schemas, you'll see `altValues`. That's a way of specifying that a code has a different display value. You normally only see these in CSV, and the OR spec is full of them.
- Schema elements can have a default value that you can hardcode into the schema.

If you have any questions, reach out and let me know.

Thanks

 [https://app.zenhub.com/files/304423150/c3bf3f96-d6a3-4952-abb7-dbeb391d13f5/download](https://app.zenhub.com/files/304423150/c3bf3f96-d6a3-4952-abb7-dbeb391d13f5/download)

**Comment by jlusds** [comment]
What's the status of this?

**Comment by brick-green-agile6** [comment]
This has been done. Since I didn't open this I didn't know if I should close it.

**Comment by jlusds** [comment]
I'll close it!
