### ISSUE TITLE
Conduct Content Test

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13658]
## Problem statement
We want to further understand the clarity and comprehension of key ReportStream terms and concepts. Once the PRA gets approved, we should conduct the test and note the results.

## What you need to know
- Ticket for approval #13511 
- [PRA docs](https://cdc.sharepoint.com/:f:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/PRA?csf=1&web=1&e=9EUAa3)
- [Overall planning doc ](https://docs.google.com/document/d/13v5lFuwFohYJg_GqHCx5cnSeIk61us4Vwlr0wVS5wfU/edit#heading=h.f95nzfkcj0n)

## Acceptance criteria
- [x] Send survey via Qualtrics
- [x] Create follow on ticket to synthesize results

**Comment by chris-kuryak** [comment]
Waiting on PRA approval

**Comment by chris-kuryak** [comment]
Waiting for information necessary to submit for approval again.

**Comment by chris-kuryak** [comment]
Design is owning getting this information.

**Comment by chris-kuryak** [comment]
Information gathered, and JT has submitted to necessary CDC personnel.

**Comment by chris-kuryak** [comment]
More paperwork being submitted by JT. This is a learning process for all of us.

**Comment by audreykwr** [comment]
Got PRA approval! Planning on sending today or tomorrow. @MikaelahD13

**Comment by audreykwr** [comment]
Just need to create the follow on ticket but will close soon @MikaelahD13
