### ISSUE TITLE
Sender pipeline user manual

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#1366]
## Problem statement

[Write a short description of what you want to achieve with this task]

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by celestemespinoza** [comment]
duplicate
