### ISSUE TITLE
Implement Destination Filter Function

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#13691]
### User Story

As ReportStream,
low-risk routing operations shall occur in the DestinationFilterFunction,
so that as many messages can make it through the routing logic as possible.

### Description/Use Case

See (Section I in [Routing SRD](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engineering/Design/SRD-Routing.docx?d=w3a2fa783e8dc4e9b8397da9f5d968dfa&csf=1&web=1&e=QtXM41)) for requirements/details.

### Acceptance Criteria

- [ ] Implemented DestinationFilterFunction

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13691?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
