### ISSUE TITLE
Implement Setting Validation

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#13690]
### User Story

As a RS developer updating organization, sender, and receiver settings,
I want validation of the YML,
so that I can avoid mistakes and prevent config issues

### Description/Use Case

Idea: Look into using https://pkl-lang.org/index.html (Section III.I in [Routing SRD](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engineering/Design/SRD-Routing.docx?d=w3a2fa783e8dc4e9b8397da9f5d968dfa&csf=1&web=1&e=QtXM41))

See [PKL use cases](https://pkl-lang.org/main/current/introduction/use-cases.html) to get a sense of what the library can do. ReportStream should make use of:
- **Generating Static Configuration** - helps validate the settings as they are being written in the YML file by a ReportStream engineer
- **Application Runtime Configuration** - validates the settings during runtime. This can be triggered when setting the settings via CLI or ReportStream website UI.

### Acceptance Criteria

- [ ] Validation of YML configuration happens in real-time during configuration

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13690?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean

**Comment by arnejduranovic** [comment]
@jalbinson to break up/groom ticket further. The ticket right now may be more work than can be done in a single sprint

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13690?planning-poker) with Zenhub @adegolier @jack-h-wang @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13690?planning-poker) with Zenhub @david-navapbc
