### ISSUE TITLE
Test new OTC / Proctored fields

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1370]
Most of our data models (aka schemas) now have these new very useful fields:

- test_authorized_for_otc.
- test_authorized_for_home
- test_authorized_for_unproctored

The values for each can be 'Y' or 'N'. 

- OTC means its an "over the counter" covid test.
- home means its a covid test that can be done at home.
- unproctored means its a covid test that can be run without a health professional present.
Obviously these booleans have a lot of overlap.

The data for these comes via a lookup of the Testkit Name ID or Equipment UID in the LIVD-Supplemental-2021-06-07.csv table.

Start by reviewing/studying these links:
1.  The PR for this:   https://github.com/CDCgov/prime-reportstream/pull/1238
2.  The new lookup table for OTC, Home, Unproctored:   https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/metadata/tables/LIVD-Supplemental-2021-06-07.csv
In that table, the values is_otc, is_home, and is_unproctored correspond to the schema variables listed above.

Note that there are many many devices in the main LIVD table (LIVD-SARS-CoV-2-2021-04-28.csv) - the Supplemental table only has the devices that are actively being used in our system.  (what if we missed one?  what if a new one appears?)

These new fields need testing.  Here's my initial thoughts on what needs to be tested:

1.  Happy path:   If I generate data the has any of the Testkit Name ID in the Supplemental table, do I get correct values for test_authorized_for_otc, test_authorized_for_home, and test_authorized_for_unproctored?
2.  Missing data / error paths:  What if I use a Testkit Name ID that is valid, but isn't in that Supplemental table?  What if I use an invalid or empty Testkit Name ID.  Etc.
3.  Validation: Does the list of Testkit Name IDs represented in the Supplemental table actually correspond to the actual Testkit Name IDs we see in our Production data?  That is, does our Supplemental table have the right rows?  Is it missing any test kit Name IDs?
4.  Can I add qualityFilters that filter on those fields (qualityFilters are added per receiver.   Search for qualityFilter in organizations-local.yml for examples)

**Comment by jimduff-usds** [comment]
This ticket is for @SpiderSense

**Comment by san-nat** [comment]
[https://app.zenhub.com/files/304423150/215d9af5-9144-4da0-8289-bfb69db4a8e6/download](https://app.zenhub.com/files/304423150/215d9af5-9144-4da0-8289-bfb69db4a8e6/download)[https://app.zenhub.com/files/304423150/b26895e3-bd1a-4530-9251-0bfc578dca2f/download](https://app.zenhub.com/files/304423150/b26895e3-bd1a-4530-9251-0bfc578dca2f/download)

**Comment by san-nat** [comment]
Testing complete. Please see the attached spreadsheet for functional test cases. 
[Otc_Proctored Test cases.xlsx](https://github.com/CDCgov/prime-reportstream/files/6772236/Otc_Proctored.Test.cases.xlsx)


1 bug reported https://github.com/CDCgov/prime-reportstream/issues/1493
1 automation ticket spawned https://github.com/CDCgov/prime-reportstream/issues/1488
