### ISSUE TITLE
ResearchOps initial draft of new sections

### ISSUE THREAD

**Issue by dylansmith-Nava** [CDCgov/prime-reportstream#13710]
### User Story
As a researcher on ReportStream, I want to re-structure the ResearchOps document, create at least (1) new ResearchOps section (identified as "Research tools"), and estimate tickets for other sections, so I can help centralize and formalize new ResearchOps materials, and prepare to bring other designers in so they can work on different ResearchOps sections jointly.

### Background
Prior ResearchOps documents are disjointed and spread among different teams and projects. Likewise, there is not one source of truth for ResearchOps strategies, and as such, any previous strategies are not widely practiced within the design team. Revisiting the ResearchOps documents will be helpful to understand which guidelines are still relevant for our team, what gap(s) in knowledge and/or strategy are occurring, and what new material(s) may need to be made.

### Risks/Impacts/Considerations
- Too general/not specialized enough or too much bureaucracy created for widespread adoption purposes
- Tools will change over time, requiring updates to the ResearchOps doc

### Open Questions
- What is the right material to create or include?
- What documents deserve to be turned into templates?
- How can I ensure that the research team will use the templates and standardized documents?

### Links
- [USDS Research Ops: WIP PRIME ReportStream Design Research Operations Guide ](https://docs.google.com/document/d/1DPAtvGTMc0HWNYhto3P3SDV9qZmoTRVI/edit#heading=h.gjdgxs)
- [“Early” ReportStream Research Ops doc: ReportStream Research Norms](https://docs.google.com/document/d/1dYrGtevixSEcbhFd4hQ7yBQNIfc3M7OHB7CBSCdQL6E/edit#heading=h.ywptbibq7pqj) 
- [ResearchOps template [1] from the Nava Research Library](https://docs.google.com/document/d/19nss7fuPcEaEFw1dBKLJJQx0_j4E-TtVMQXztkzuUb8/edit#heading=h.niqb23uzef2y) 
- [ResearchOps template [2] from the Nava Research Library](https://docs.google.com/document/d/1bS9yGz23k7FReFXrM8j2SRQxJLtONxrM9OIIbXIgoDg/edit#heading=h.bq8dugi5oz9q) 

### Acceptance Criteria
- [x] Restructure the ResearchOps document based on prior materials
- [x] Create first draft of Research Tools section
- [x] Create ticket estimations of work-to-be-done so Jillian and other designers have an idea of how they can share ResearchOps work
- [x] Share-out of ResearchOps synthesis to Design team and Platform scrum team, as appropriate

### Out of Scope
- Adding any other sections (yet) -- the initial work is to estimate what it would take to complete other sections, so that other designers can work on those sections

**Comment by dylansmith-Nava** [comment]
New [ResearchOps document](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B38251E1C-E969-4238-9959-EA182B99F3E2%7D&file=ResearchOps%20recommendations1.docx&action=default&mobileredirect=true) surfaced in the [ResearchOps folder](https://cdc.sharepoint.com/teams/ReportStream/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FReportStream%2FShared%20Documents%2FDesign%20and%20Research%2F00%5FDesignOperations%2FResearchOps&viewid=6255f791%2D133e%2D4cae%2D9185%2Db78c974e99f2). Very WIP, still setting up the structure and will start filling out the required fields for this ticket soon! CC @Andrey-Glazkv @jsutantio @jillian-hammer

**Comment by dylansmith-Nava** [comment]
[ResearchOps document](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B38251E1C-E969-4238-9959-EA182B99F3E2%7D&file=ResearchOps%20recommendations1.docx&action=default&mobileredirect=true) updates:
- Added material from prior ResearchOps documents and adjusted to fit the current structure
- Completed draft of the "Research tools" section
- Drafted tickets, estimations, and tasks for the other sections for other researchers to take on

As such, I am moving into Product Review pending Design Lead approval. cc @Andrey-Glazkv @jsutantio @jillian-hammer

**Comment by brandonnava** [comment]
Sections look good from my end

**Comment by dylansmith-Nava** [comment]
The [sections](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B38251E1C-E969-4238-9959-EA182B99F3E2%7D&file=ResearchOps%20recommendations1.docx&action=default&mobileredirect=true) are complete per Product's review and new sections have been commented with estimations of ticket size for other RS designers to take on. The Design team also is planning to discuss ResearchOps at Design Crit this week! (4/11). Owing to these updates, I can move this ticket to Closed. cc @Andrey-Glazkv @jillian-hammer @jsutantio
