### ISSUE TITLE
create CSV schema for Experity

### ISSUE THREAD

**Issue by kjt9cc** [CDCgov/prime-reportstream#1371]
Experity has a canned report feature that will produce a standard ELR dump for all customers of that EMR. Create a new schema in ReportStream for the experity export. Map the experity columns to the standard fields in the ReportStream platform. Requires development, checkin, code review, prod deploy

**Comment by kjt9cc** [comment]
this might be a sender automation task?

**Comment by HeatherRienks** [comment]
The Sender Automation team is currently working on this. Will update issue accordingly.

**Comment by loripusey** [comment]
@HeatherRienks if the Sender Automation team is tracking this work in a different way, can I close this ticket then?

**Comment by HeatherRienks** [comment]
@loripusey - yes, we are tracking this via a GitHub board, so I don't think that we need this ticket.

@rhood23699 - please confirm.
