### ISSUE TITLE
add Greenlight Urgent Care to the list of senders in RS

### ISSUE THREAD

**Issue by kjt9cc** [CDCgov/prime-reportstream#1372]
what is required to add a new sender and allow them to start submitting data?

**Comment by HeatherRienks** [comment]
Sender Automation team working with Pipeline team (Anshul/Jim) on next steps.

**Comment by loripusey** [comment]
@HeatherRienks if the Sender Automation team is tracking this work in a different way, can I close this ticket then?

**Comment by rhood23699** [comment]
We are tracking in the Sender-Automation Board.
