### ISSUE TITLE
Create SWE Requirements Doc for RadxMars Support

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#13733]
### User Story
As a ReportStream developer,
I must understand the software requirements for radxmars support,
so that I can implement the support properly

### Description/Use Case
Review [product requirements](https://github.com/CDCgov/prime-reportstream/issues/13072) and come up with software requirements document detailing high-level design

### Acceptance Criteria
- [ ] Software requirements doc created: https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engineering/Design/SRD-RadxMars-OTC.docx?d=wfb06850638704ddb896ef6f02a1428ef&csf=1&web=1&e=5s1gvp
- [ ] Software requirements doc approved by product - @brandonnava 
- [ ] Software requirements doc approved by engineering
    - [ ] Platform - @mkalish, @thetaurean 
    - [ ] Engagement
- [ ] Software requirements doc approved by design - @dylansmith-Nava 
- [ ] Follow-up tickets created

**Comment by Andrey-Glazkv** [comment]
@dylansmith-Nava FYI

**Comment by brandonnava** [comment]
Other than the MSH 21 requirement this looks good to go from my end
