### ISSUE TITLE
Create process, timeline, and contingency list for migrating to new Okta Identity engine

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13769]
## Problem statement
The new Okta Identity engine has improvements that could be useful to ReportStream over the Okta Classic engine. Before we upgrade, we need to develop a plan that ensures full continuity of business services without any downtime.

## Acceptance criteria
- [x] Check through the admin panel of our existing instance if we are eligible and document any warnings or issues
- [x] Review the [Upgrade Process](https://help.okta.com/oie/en-us/content/topics/identity-engine/oie-upgrade-eligibility.htm) steps from Okta and ensure all findings are documented
- [x] Document the process and timeline for migrating to the new version of Okta broken into 3 phases:
  - [x] Before migration tasks
  - [x] Day of migration tasks
  - [x] After migration tasks

- [x] Identify if we should migrate OktaPreview (staging) and Okta (production) at the same time or separate times. Identify any steps that would be different in those two processes.
- [x] Identify ownership of all tasks (can review with Chris and Victor for guidance)
- [x] Document any contingencies/issues that could arise when migrating to the new version of Okta
- [x] Determine if there is a way to roll back to Okta Classic engine if something bad happens, and if so, how
- [x] Document how we plan to overcome those issues (if possible)

**Comment by chris-kuryak** [comment]
Joseph suggests migrating over in preview first (Staging), and then taking time to use that and prove it out before migrating over the production instance.

**Comment by chris-kuryak** [comment]
@jpandersen87 After reading the document, just want to confirm:
- So there will be no action needed by end users (senders, receivers, prime-admins) in this migration?

**Comment by jpandersen87** [comment]
> @jpandersen87 After reading the document, just want to confirm:
> 
> * So there will be no action needed by end users (senders, receivers, prime-admins) in this migration?

Correct

**Comment by chris-kuryak** [comment]
Reviewed, LGTM
