### ISSUE TITLE
Implement RadxMars 2.5.1 Mappings HL7v2.5.1 -> FHIR -> HL7v2.5.1

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#13798]
### User Story
As a report stream sender,
I would like my RadxMars OTC compliant message to be processed through the pipeline losslessly
so that receivers receive all the data I submitted

### Description/Use Case
Implement mappings for RadxMars OTC:
- HL7v2 RadxMars OTC -> FHIR
- FHIR -> HL7v2 RadxMars OTC

See RadxMars [software requirements document](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engineering/Design/SRD-RadxMars-OTC.docx?d=wfb06850638704ddb896ef6f02a1428ef&csf=1&web=1&e=qzVVGh)  section:
II. Translation support

Note: This ticket should NOT do anything related to de-identification

### Dev Notes
- Step one is to create a test that verifies the UP can process a maximally configured RadxMars message, meaning it can translate `RadxMars 2.5.1 -> FHIR -> RadxMars 2.5.1` without losing any data.
- IF NEEDED: Step two is to update the catchall mappings so that the above test passes

### Acceptance Criteria
- [ ] RADxMARS OTC 2.5.1 message can be translated to and from FHIR without losing data
- [ ] Test created to confirm this functionality

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13798?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
