### ISSUE TITLE
Create the RadxMars 2.5.1 ORU-R01 message and data types

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#13794]
### User Story
As a report stream sender,
I would like to be able to have an exact mapping for a HL7 message that matches the RadxMars OTC 2.5.1 conformance profile
so that ReportStream does not drop any data when serializing my messages

### Description/Use Case
This is covered more in depth in the design spec, but in order to guarantee being able to losslessly and deterministically map from HL7->FHIR->HL7 for a give conformance profile, there needs to exist java classes that match that profile.  The work here is to create all the java code needed for RadxMars OTC 2.5.1

### Dev Notes
- See how the PR for #13021 accomplished this for NIST 2.5.1
- See output of #13024 for details on how to do this work

### Acceptance Criteria
- [ ] All the custom datatypes used in the the RadxMars OTC 2.5.1 are created
- [ ] A class that extends `AbstractMessage` exactly matches the RadxMars 2.5.1 conformance profile
- [ ] The class can be used to parse a valid RadxMars OTC 2.5.1 message

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13794?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
