### ISSUE TITLE
Develop OKR Metrics Dashboard in PowerBI

### ISSUE THREAD

**Issue by jsutantio** [CDCgov/prime-reportstream#13790]
### User Story

As a stakeholder at the CDC, I want to view ReportStream OKR product metrics on a user-friendly dashboard (without requiring special permissions to access) that allows intuitive filtering and data analysis.

### Description/Use Case

Now that we are able to obtain and log events within the UP and have proven the possibility to import that stored data into PowerBI, this ticket aims to create the user-facing OKR Metrics Dashboard based on the [design brief](https://cdc.sharepoint.com/:p:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B3BB9CF2F-B839-4DD5-BFB5-9132C6F8E707%7D&file=OKRMetricsDashboard_DesignBrief.pptx&action=edit&mobileredirect=true), which was defined in #12450.

### Risks/Impacts/Considerations

The dashboard is limited to the data that is provided; therefore, there is no existing data at this time (until it is backfilled) that precedes the logging work that was recently completed. The output visualizations within the dashboard may have insufficient historical data to produce long-term graphs, but will improve over time as more data is logged and synced.

Once we move the instance outside the staging storage environment. We must consider which sensitivity label to assign the dashboard and reports - whether it's the following and how the more restricted label may prevent access:
- General (default): data not meant for the public
- Restricted Use: sensitive data not meant for the public

**Some unknown barriers can be:**
- frequency of data refresh to PowerBI and thus the connected online dashboard
- load time/ performance of the interactive elements (e.g., filtering by condition) within the online dashboard
- support for different internet browsers (optimizing design on Chrome at this time)

### Dev Notes

[Starting point for data refresh](https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-data)
### Acceptance Criteria

- [x] Format the imported dataset from Blobstore
- [x] Format the imported dataset from Postgres
- [x] Create dashboard visualizations/ modules via DAX or SQL
- [x] Layout the visualizations according to the [design brief] (https://cdc.sharepoint.com/:p:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B3BB9CF2F-B839-4DD5-BFB5-9132C6F8E707%7D&file=OKRMetricsDashboard_DesignBrief.pptx&action=edit&mobileredirect=true) and verify functionality
- [x] NEW TICKET: Figure out how to refresh the data automatically. DevOps working on it
- [x] Create shareable online dashboard

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13790?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Jess - one last formula to create
Jamie - ticket for DevOps was created
