### ISSUE TITLE
Implement RadxMars OTC De-Identification Support

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#13799]
### User Story
As the CDC receiving RadxMars OTC data,
I want the message to be de-identified per the RadxMars rules,
so I can adhere to regulations

### Description/Use Case
All messages going to the CDC receiver of RadxMars OTC data must be de-identified, per the RadxMars de-identification rules.

See the [software requirements document](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engineering/Design/SRD-RadxMars-OTC.docx?d=wfb06850638704ddb896ef6f02a1428ef&csf=1&web=1&e=qzVVGh) section for more details:
II. Translation support

### Acceptance Criteria
- [ ] RADxMARS OTC 2.5.1 messages can be de-identified on a per-receiver basis

**Comment by Andrey-Glazkv** [comment]
blocked by prod requirements @brandonnava - FYI

**Comment by Andrey-Glazkv** [comment]
@dylansmith-Nava
