### ISSUE TITLE
Research into which condition(s) CDC will accept for OTC data

### ISSUE THREAD

**Issue by dylansmith-Nava** [CDCgov/prime-reportstream#13836]
### User Story
As a researcher on ReportStream, I want to figure out which condition(s) the CDC will accept regarding OTC data, so that I can inform the RADxMARS software requirements regarding the removal of unwanted conditions during translation.

### Background
The RADxMARS SRD is currently being created to understand how ReportStream should receive OTC data from Senders in a RADxMARS profile, and appropriately send that data to Receivers in that same profile. For our pilot program, we are working solely with makemytestcount.org (MMTC) as a Sender of OTC data. There are a few hard requirements from our MMTC & NIH stakeholder:
- ReportStream shall convert any unwanted conditions from OBX to NTE segments
- ReportStream will remove all NTE segments to support the RADxMARS de-identification rules, _except_ for converted OBX segments

For this ticket's purpose, we want to know, in this order:
- If the CDC, as a receiver, wants _all_ conditions sent
- If the CDC wants only _some_ conditions sent
- If the CDC only wants, _some_ conditions sent, do they care about receiving "unwanted conditions" as NTE

Ultimately, removing all NTE is easier and simpler for engineering. So it'll be good to know if we need to keep some NTE (the converted OBX segments) for CDC, or if we can just remove them all.

### Risks/Impacts/Considerations
- Delays or dependencies are possible if it turns out that CDC does want to see unwanted OBX segments as NTE (and therefore it's not an easy of a job as hoped for)
- It remains to be seen which organization(s) and stakeholders are affected or should be included in this ticket between DEX, HHSProtect and DCIPHER

### Open Questions
- See above in Background

### Links
- [#13799](https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/13799): Implement RADxMARS OTC De-Identification Support
- [SRD-RadxMars-OTC](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/doc2.aspx?sourcedoc=%7BFB068506-3870-4DDB-896E-F6F02A1428EF%7D&file=SRD-RadxMars-OTC.docx&action=default&mobileredirect=true)
- [RADxMARS Product Requirements](https://github.com/CDCgov/prime-reportstream/issues/13072)

### Acceptance Criteria
- [ ] Find out which condition(s) CDC wants to accept for OTC data
- [ ] Find out what the CDC would like to see with regards to unwanted conditions as NTE

### Out of Scope
- STLTs don't get a choice if they do or do not want to receive unwanted OBX as NTE (they will just receive them anyway), so this ticket is not for STLTs

**Comment by dylansmith-Nava** [comment]
Noting for future purposes; this ticket was created in a response to a discussion in Platform Stand-Up, but as Arnej noted, it will be de-prioritized for now because Product wants to approach this type work in a longer-term, more strategic manner. As such, this ticket will not be relevant until later in the quarter. Date: 3/26/24. cc @Andrey-Glazkv @jsutantio @jillian-hammer @arnejduranovic

**Comment by dylansmith-Nava** [comment]
##**Ticket Housekeeping!**

@arnejduranovic I think the main part of this potential ticket is solved...to my knowledge the logic is that c) CDC/STLTs may want only _some_ conditions sent so they will receive "unwanted conditions" as NTE. If that's correct, then I will close out of this ticket. cc @Andrey-Glazkv.

**Comment by arnejduranovic** [comment]
@dylansmith-Nava Yes we have the ability to do this (via FHIR->HL7v2 transforms). I would talk to SME @GilmoreA6 to see if the condition actually matters in the context of removing unwanted conditions. I think the answer is "no" but we should verify with James before closing.

**Comment by dylansmith-Nava** [comment]
@arnejduranovic what do you mean exactly by the condition "mattering"?

**Comment by arnejduranovic** [comment]
> @arnejduranovic what do you mean exactly by the condition "mattering"?

I am under the assumption that the logic for removing unwanted conditions is the same regardless of what the actual condition is. We should confirm this assumption with a SME.

**Comment by dylansmith-Nava** [comment]
As part of the eventual onboarding process with CDC DCIPHER, RS Product will figure out the answers to the primary questions and assumptions in this ticket, being that via the RadxMars topic:
- What condition(s) does DCIPHER want?
- Does DCIPHER want unwanted conditions dropped or as NTE? (Assumption is NTE as per the RadxMars spec)

As such, this ticket is not relevant and will eventually be solved by Product, not by Platform D/R. I will go ahead and close the ticket after chatting with @arnejduranovic. cc @Andrey-Glazkv
