### ISSUE TITLE
Re-Evaluate Submission Function Implementation

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#13831]
### User Story

As a stakeholder of ReportStream,
I want to ensure the Submission function is designed for maximum uptime and reliability,
so that there are minimal interruptions to reporting

### Description/Use Case

The design, implementation, and deployment of the submission function, as it applies to the UP, should be re-evaluated to ensure the following criteria are met:
- The availability of the submission functionality of RS is independent of other RS features (like routing) when deployed
- The submission function is as reliable as possible and unlikely to have runtime issues. This means the function should be as simple as possible and ideally not do anything else except storing the received files (will need to verify this is best approach)

### Risks/Impacts/Considerations

- Certain changes to submissions may require a new endpoint be created, which would interrupt current senders. We need to evaluate if this is worth it.

### Acceptance Criteria

- [ ] Submission function evaluated and SRD created, if needed

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13831?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
