### ISSUE TITLE
Write testing plan documentation including how to ensure filters are working as intended

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#13845]
Context: 
Engagement engineers should have comprehensive documentation of required testing plans to validate when onboarding a sender or receivers. These testing plans should include what test cases to include as well as the steps needed to fully test with a sender/receiver.

**Comment by GilmoreA6** [comment]
This is now an acceptance criteria for #13992

**Comment by chris-kuryak** [comment]
Per James, waiting on review still
