### ISSUE TITLE
Whitelist all remaining CP Receivers in Staging

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13853]
## Problem statement
In order to "test in staging" with a STLT, their staging environment needs to be whitelisted. Due to recent slowdowns in the onboarding process due to whitelisting issues, it may remove potential blockers if we can get all existing receivers Staging environments re-whitelisted before we start onboarding them.

## What you need to know
- [Previous audit](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B28EDE785-0FC9-4921-BCD0-B423F3C5E92A%7D&file=Receiver%20Staging%20Connection%20Test%20-%20Jan%202024.xlsx&action=default&mobileredirect=true) of existing staging connection tests
- Only receivers using SFTP need to be whitelisted
- First test is to check you can reach the server locally to find out if the STLT needs to whitelist us.
- Run `sftp <hostname>` on your terminal to make sure STLT doesn't have a firewall. If unable to reach they need to whitelist us.
- Check connection by going into Receiver settings in ReportStream Admin UI.
- If it works locally, find out if we need to whitelist the SFTP server in staging. Login as SU to azure, start an SSH session on the pdhstaging-function app, and run this command `sftp <hostname>`.
-  If unable to reach the server the server needs to be whitelisted

## Acceptance criteria
- [x] Document which SFTP servers need to whitelist RS
- [x] Document which SFTP servers CDC needs to whitelist
- [x] Submit ticket to DevOps with servers CDC needs to whitelist
- [x] Confirm whitelisting complete

**Comment by chris-kuryak** [comment]
@victor-chaparro Can you reference DevOps ticket here

**Comment by victor-chaparro** [comment]
DevOps ticket: https://app.zenhub.com/workspaces/prime-devops-606cb208a8c112000fd48349/issues/gh/cdcgov/prime-devops/123
