### ISSUE TITLE
Differentiate test orders from results in logged events

### ISSUE THREAD

**Issue by jsutantio** [CDCgov/prime-reportstream#13861]
### User Story

As a stakeholder at the CDC, I want to be able to filter out test orders from test results.
### Description/Use Case

For the ETOR use case where both a test result and test order may appear in the logged observation, we must be able to distinguish one from the other - so that we can obtain accurate tallies of the quantity of results coming in (potentially filtered by condition, sender, receiver, time).

### Risks/Impacts/Considerations

Currently, there is no production test order data. But if there were, those test orders would cause inaccuracies in the test result counts. Therefore, we must support this prior to an ETOR sender going live.

Confirm SR populates `MessageHeader.Event.EventCoding` correctly 

Risk: If senders populate  `MessageHeader.Event.EventCoding` with various spellings/alternatives we will have to monitor and update our queries that use these values

### Dev Notes

Consider adding the bundle's `MessageHeader.Event.EventCoding` to the Azure Events
Do note that this will not record the version

### Acceptance Criteria

- [ ] Events data is recorded in a manner that enables queryable differentiation between test orders and test results per distinct test within an observation

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13861?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean

**Comment by arnejduranovic** [comment]
This information is now in the BundleDigest `prime-router/src/main/kotlin/azure/observability/bundleDigest/BundleDigestExtractor.kt`. An engineer should pair with Jessica to walk through how this can be queried.

**Comment by arnejduranovic** [comment]
![Screenshot 2024-08-12 at 10 58 59 AM](https://github.com/user-attachments/assets/9fc8b123-0c02-4f78-9663-da528df324cd)

Already done? @jsutantio

**Comment by arnejduranovic** [comment]
Jessica confirmed this meets AC. Closing.
