### ISSUE TITLE
Add Fake Data Generation Option to Create Low-Quality OTC Data

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1388]
The Prime CLI has the ability to output fake data via this command:

`./prime data --input-fake --input-schema primedatainput/pdi-covid-19 --output-format CSV --output <PATH TO SAVE FILE>`

The `FakeReport` and `FakeDataService` classes then endeavor to crate the most complete fake data possible. We should add a new option: `input-fake-otc` that creates less complete data that doesn't pass the default quality filter, and looks similar to actual COVID OTC test results.

Acceptance criteria:
- The fake OTC data generator should use the same libraries as the regular fake data generation
- The fake OTC data generator should respect and use the `--target-states` and `--target-counties` options that get passed in
- The fake OTC data should look like actual OTC data.

**Comment by MauriceReeves-usds** [comment]
FYSA: @jimduff-usds @jlusds @RickHawesUSDS

**Comment by jimduff-usds** [comment]
- the fake OTC data should use equipment in the LIVD-Supplemental table that has is_otc and is_proctored set to True.

**Comment by JGreenFearless** [comment]
@MauriceReeves-usds Is this still something we need to address?

**Comment by brandonnava** [comment]
@brick-green @MauriceReeves-usds Still useful? And if so is this O&O work or pipeline? Else I'm fine with closing.

**Comment by brick-green** [comment]
@brandonnava I like this one a lot. Feels like we're only going to get more and more OTC. I think it can be work for us.

**Comment by LaFreda1** [comment]
Closing due to it being COVID specific
