### ISSUE TITLE
Lucero Velasco- Engagement Engineer access ticket

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#13882]
Access Needed for New Engineer

- [x] CDC email
- [x] CDC SU account access
- [x] Okta Account Staging
- [x] Okta Account Production
- [x] Open VPN credentials for Staging and Prod dbs
- [x] Metabase Staging Access
- [x] Metabase Production Access
- [x] Easyretro access
- [x] Mural access
- Slack Channels
   - [x] prime-reportstream
   - [x] prime-reportstream-engagement
   - [x] prime-reportstream-engineering
  
- [x] Lucero confirmed/checked has access to all of these tools

**Comment by chris-kuryak** [comment]
Waiting on CDC credentials

**Comment by chris-kuryak** [comment]
Per Victor: Response from DevOps is that Lucero has access to everything.

Next steps: Lucero to check she has access

**Comment by chris-kuryak** [comment]
@lucero-v Can you check if you have access to the tools that are NOT checked above?

**Comment by chris-kuryak** [comment]
Patrick has been informed to give Lucero access
