### ISSUE TITLE
Assist dev team to get BI hooked to Postgres (ideally replica)

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#13897]
This may not even be possible with our current setup but the dev team would like to hook up their BI tool to the replica instance in staging/production. This probably means to the 172.x.x.x address and will likely require assistance from the CDC firewall team

**Comment by Andrey-Glazkv** [comment]
@jsutantio @adegolier from Jeremy: "sent the request, part of the issue is we do not have a CDC security engineer officially assigned to PRIME - the person we go through is on loan from another group inside the CDC. He was supposed to leave at the end of April but I think will be able to help. Their organization is a real mess."

**Comment by supriyaaddagada** [comment]
@jsutantio @adegolier create a Ticket CHG0035387 for CDC to open the firewall from Power BI to Postgres, will provide an update based on the tickets progress

**Comment by supriyaaddagada** [comment]
@jsutantio @adegolier As mentioned in chat CDC team has cancelled the Ticket CHG0035387 since they requested to provide non-NAT internal IP address instead of 158.111.236.37

created a new ticket CHG0035441 with the IP of  FQDN from CDC VM where Power BI is installed

**Comment by Andrey-Glazkv** [comment]
@arnejduranovic FYI

**Comment by supriyaaddagada** [comment]
@jsutantio @adegolier @arnejduranovic change request CHG0035441  has been updated to closed, could you please check to see if you are able to connect to Postgres from PowerBI

**Comment by supriyaaddagada** [comment]
CDC has created a VM with PowerBI installed on the machine, created a new request CHG0036556 to CDC to create connectivity from PowerBI to staging environment.
