### ISSUE TITLE
Compare mapping inventory datatypes to v251 datatypes

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#13904]
### User Story
As an engineer I want to know that all datatypes used by v251 and v251-elr mappings align with the specification so that we do not mis-map or leave out data.

### Description/Use Case
The mapping inventory mixed datatypes from multiple versions of HL7 (v.2.5.1, v2.7, v2.9). The mappings for v251 should not use elements from v2.7 or v2.9. This is especailly important as the NIST mappings use the base v251 mapping which currently also include mapping for v2.7 or v2.9. Further, the mapping for RADx MARS will also rely on the base v251 mappings.

### Dev Notes
Compare the data types from the NIST site (https://hl7v2-elr-testing.nist.gov/mu-elr/) to the mapped datatypes in `metadata/HL7/datatypes/v251/hl7/datatypes`. Only the regular datatypes need to be compared(i.e. the datatypes that do not end with `_ELR`).

### Acceptance Criteria

- [ ] datatypes in metadata/HL7/datatypes/v251/hl7/datatypes mirror the specification at https://hl7v2-elr-testing.nist.gov/mu-elr/

**Comment by Andrey-Glazkv** [comment]
#13798
