### ISSUE TITLE
Sender Change Comms: Synthesis and plans

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#13907]
## Problem Statement
As we move into the next phase of migration and onboarding (senders), we want to improve our communication and messaging with senders to enhance improve their experience and provide them the information they want to know in an efficient way.

## Scope
- Existing senders
- Potential new senders (that align with the demographic of existing senders)

## Out of scope
- Pilot program senders (ETOR, ELIMS, NBS) as we will approach the needs of those senders in their respective workstreams

## What you need to know
- [Mural workspace](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1701295941842/fe6b8d75d6d13b217c9d4406610301e5b597cd6d?sender=uc55a7af3b66977fba12f5528)

## Acceptance Criteria
- [x]  Clarify questions/gaps from last working session 
- [x]  Finalize proposed messages and tactics

**Comment by chris-kuryak** [comment]
Looks good

**Comment by audreykwr** [comment]
Mural updated with synthesis
