### ISSUE TITLE
Create email/content for HL7 senders that are no longer sending us data

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13912]
## Problem statement
Some HL7 senders on the COVID pipeline have stopped sending us production data. Before we finalize our sender migration plan, we want to confirm whether or not we should plan on migrating these senders.

## What you need to know

- [Sender Audit](https://docs.google.com/spreadsheets/d/1GerMI0hKSRK5svbcNzScUBHb5zJImLOixTpBOZXOdvU/edit#gid=443493841) for more information about these senders
- List of CP HL7 senders to contact:
  - Lifepoint​
  - Prescryptive​
  - Medical Network Solutions​
  - Color-labs​
  - Primary​
  - Limsabc-nova​
  - Signetic​
  - Mayo-clinic​
  - Aegis​
  - Nerolab

- MedArbor is an HL7 Sender that has NOT finished onboarding to the CP, but they are very close (only need approval through WA remaining, I believe). Angela has been the team member in charge of onboarding them last year, and our sync calls have moved to an "as-needed" basis. Since we are still 4+ months away from onboarding a sender to the UP, I don't think we should stop the train from moving since the work they are doing would be necessary for the UP as well, BUT I think we should try to find out:
  - Are they capable of (or interested in) sending any other conditions beyond COVID through ReportStream?

## Answers we'd like to know
- Why have they stopped sending RS data?
- Do they plan on sending COVID data in the future?
- Do they have any other conditions (beyond COVID) that they'd be interested in sending through RS?

## Acceptance criteria
- [x] Develop email content for CP HL7 senders that have stopped sending us production data
- [x] Develop content/wording for communicating with MedArbor and how we want to communicate that
- [x] Identify high-level plan on how/when to send those emails

**Comment by audreykwr** [comment]
[Content doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B41C66A63-65B2-48D6-8956-9359B3D814FB%7D&file=20240403_HL7_sender_email.docx&nav=eyJjIjo3OTYxNDI3NDl9&action=default&mobileredirect=true)
