### ISSUE TITLE
Connect PowerBI webapp to Azure blob store

### ISSUE THREAD

**Issue by jalbinson** [CDCgov/prime-reportstream#13924]
**Description**
PowerBI is able to connect to the Azure BlobStore when setting up visualizations on the PowerBI desktop app. Once it is published to the webapp version you are unable to use the same credentials that just worked on the desktop version in order to set up a scheduled data refresh.

![Screenshot 2024-04-04 at 11 49 13 AM](https://github.com/CDCgov/prime-reportstream/assets/1209453/f4955a7c-c122-4494-b584-a5b2660bd25f)
(deleted key prior to screenshot)

**Comment by jalbinson** [comment]
@Andrey-Glazkv @jsutantio

**Comment by Andrey-Glazkv** [comment]
@jalbinson from Jeremy: "We were full this sprint but we can add 13924 next sprint (tomorrow). There is a good chance we can't do this though - you need IP access to do this and it will likely trigger a security review if we hook up blob storage to PowerBI. Our PII is stored in blob storage so this is going to be looked at very closely by our CDC Security engineer".

**Comment by Andrey-Glazkv** [comment]
@arnejduranovic FYI

**Comment by jeremy-page** [comment]
@jsutantio can you tell me which blob store you are trying to access?

**Comment by dkrylovsb** [comment]
PowerBI (https://app.powerbigov.us) is now able to access to `pdhstagingstorageaccount` and `pdhprodstorageaccount` as requested. Please let me know in case you run into further issues.
