### ISSUE TITLE
Admin Views Quality Filter Failure Messages

### ISSUE THREAD

**Issue by kjt9cc** [CDCgov/prime-reportstream#1393]
## Problem Statement
As an RS Admin, I would like to know for a specific Sender if any of my submitted data could not be delivered to a PHD because the data does not meet the PHD's quality standards so that I can make submission suggestions to the Sender.

## Assumptions
- Server work has already been done

## Design
@drew-usds to work towards a wireframe

## Acceptance Criteria
- Given I
    - Am logged into ReportStream **with RSAdmin permissions**
- When I
    - Log into ReportStream   
    - Choose to view the Submission History for a specified Sender
    - Select a submission to view the confirmation & warnings
- Then I
   - See a list of the quality filter failure messages and the rows that are affected by the failures
   - See that the messages are displayed in order by the rows affected (if this makes sense)

## TO DO
- Dev:

**Comment by loripusey** [comment]
@inkandsound @drew-usds FYI, I don't think this story is yet captured in the wireframes
