### ISSUE TITLE
Upload new LIVD Table

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#13937]
## **Problem Statement**

We received an updated LIVD table in the ReportStream inbox. Please upload to ReportStream.

## **What you need to know**

[LIVD-SARS-CoV-2-2024-04-04 PRIME.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU00QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1acaf7ea7ee77a13cdecc43af9a1998764ff884f/LIVD-SARS-CoV-2-2024-04-04%20PRIME.xlsx)

## **Acceptance Criteria**

- Upload new LIVD table where needed.

## **To Do**
N/A

## **Additional Comments**
N/A

**Comment by oslynn** [comment]
Done.
