### ISSUE TITLE
Identify Details of An Errored Message To Report Back To The Sender

### ISSUE THREAD

**Issue by brandonnava** [CDCgov/prime-reportstream#13935]
User story: I want information on "dropped" messages to help me identify the issue and if action should be taken

Source: Message Monitoring Product Requirement #3 (Row 5): https://docs.google.com/spreadsheets/d/121HEX98WGqP2_FDRkl5zC8pO_cqUo4u3t3QTS3vDdxc/edit?usp=sharing

Possible factors to consider logging to meet the requirement (From MM Product Sheet): 
- MessageID (per MessageID search tool)
- Condition being reported (for all that RS currently supports, if not supported by RS then needs to be recorded as ""not supported"")
- Errors that were triggered (and if none were, it is noted)
- Time/Date of the logging"
- Original Sender
- Filter category that triggered to remove it (Jurisdictional, Routing, Condition, Processing Mode, Quality)
- Specific filter triggered to remove it
- Time/Date successfully received to RS
- What is the last step the message successfully passed in the UP (Receive, Convert, Route, Translate, Send)
- Did it not get routed because it did not reach ANY of the receiver filters
- Filename of the file that RS received the message in

Acceptance Criteria: 
- [ ] We can identify the specific message in a batch that errors out
- [ ] We can hone in what in the message caused the error
- [ ] We can explain the cause of the error with enough detail that the sender knows how to make the fix when we message back to them

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13935?planning-poker) with Zenhub @adegolier @brick-green @david-navapbc @arnejduranovic @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
