### ISSUE TITLE
Automatically scan our code base for security vulnerabilities

### ISSUE THREAD

**Issue by ronaldheft-usds** [CDCgov/prime-reportstream#1396]
Currently, ReportStream has two static code analyzers setup on PRs: SonarCloud and LGTM. Neither of these analyzers is focused on security, and we can do better as a project.

The officially authorized CDC static code analyzer is Fortify, but the CDC lacks the licenses to use Fortify via GitHub at this time.

There are free alternatives we can explore as project. Two known options are:
* [GitHub Security Scanner](https://docs.github.com/en/code-security/code-scanning)
* [Synk](https://github.com/snyk/actions)

Our primary code base is kotlin (`/prime-router`) and JavaScript (`/frontend*`). The chosen solution(s) should support these two languages.

The implementer of this ticket will propose a scanner to implement and configure it in GitHub for this repo.

**Comment by ronaldheft-usds** [comment]
Look at GitHub security scanner that was recently released.

**Comment by td-usds** [comment]
This is completed through the merged #1674 but there is also #1753 which would make this even more robust

**Comment by td-usds** [comment]
It ink this can be closed
