### ISSUE TITLE
Build hub intermittent failure

### ISSUE THREAD

**Issue by JosiahSiegel** [CDCgov/prime-reportstream#13961]
## Problem statement

Rarely (1 out of 15 runs), [Build backend](https://github.com/CDCgov/prime-reportstream/blob/master/.github/workflows/build_hub.yml#L57) fails after [`./gradlew testSmoke`](https://github.com/CDCgov/prime-reportstream/blob/master/.github/actions/build-backend/action.yml#L185) attempts to run test `end2end_up` (runs twice since action is set to retry on failure).

Once thing I noticed is that with failed runs, error `Unable to load lookup table 'observation-mapping'` occurs 30+ times, whereas it only occurs once in a *successful* run since it's part of test [`test does not update the DB or send messages on an error`](https://github.com/CDCgov/prime-reportstream/blob/3a0ca47ec9e5af82d66cf045e8871ea72dbf6a96/prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionIntegrationTests.kt#L314)

### Example failures
- https://github.com/CDCgov/prime-reportstream/actions/runs/8647906279/job/23769387080?pr=13963#step:4:18023
- https://github.com/CDCgov/prime-reportstream/actions/runs/8544253175
- https://github.com/CDCgov/prime-reportstream/actions/runs/8474094071
- https://github.com/CDCgov/prime-reportstream/actions/runs/8439476454

**Comment by dkrylovsb** [comment]
It appears the 30 seconds delay between containers startup and subsequent `reloadTables` is too small to prevent a race condition. In rare circumstances, `./gradlew reloadTables` is refreshing the `observation-mapping` table at the same instant  the API container is loading the metadata. This is evident from these two log entries that have nearly the same timestamp:

`reloadTables` is creating the table at or around `14:24:00`
```14:24:00.4214392Z         24278 rows created for lookup table observation-mapping version 1.```

Java container is "activating" the table at `14:24:00`:
```[2024-04-07T14:24:00.348Z] ***"message":"Granted test auth request for PUT:/api/lookuptables/observation-mapping/1/activate","thread":"pool-2-thread-15","timestamp":"2024-04-07T14:24:00.348Z","level":"INFO","logger":"gov.cdc.prime.router.tokens.AuthenticatedClaims"***```

A quick short-term fix would be to just bump up that delay to, say, 90 seconds. 

A much better fix would be to delay executing `./gradlew reloadTables` until the Java container is _fully_ up and running.
