### ISSUE TITLE
Conduct desk research on ADT feeds & BioSense

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#13971]
### User story
As a ReportStream stakeholder, I want to understand the basics of ADT (admission, discharge, & transfer) data and how it currently flows from Senders to PHDs & the CDC, so that I can generate a shared understanding via documentation and visuals about how ReportStream could possible expand its role as an Intermediary in this context.

### Background
ReportStream stakeholders are strategically discussing the opportunity for ReportStream to accept ADT feeds from senders and route them to PHDs and CDC BioSense on behalf of these senders. This research is to understand this current system in greater detail, and to characterize ADT data by the needs and goals that ReportStream generally has when it comes to dissecting and analyzing a new data type. Ultimately, we want to see if ReportStream could deliver value to the greater ADT landscape by reducing sender reporting burden. 

### Risks/Impacts/Considerations
- ADT data is unique enough that it would cause greater delays and dependencies than expected on completing various ReportStream-centric functions, like Route and Validate, thus jettisoning the development of the capabilities to, for instance, ingest and send ADT data, farther out on the timeline than expected
- ADT Senders incur significantly higher difficulties to connect to ReportStream than other Senders
- ADT Senders significantly lack data standardization (related to first risk)
- Significant difficulty over other Senders of being able to correct errors and mistakes

### Open questions
ADT Data
- How can we characterize ADT data?
- What format is it in? HL7, FHIR, paper, or something else? How is this data being sent?
- What kind of condition(s) are included in ADT data? What exactly is being sent?
- What kind of **Translation** (if any) occurs with ADT data today?
- How does **Validation** (if any) occur with regards to ADT data today?
- How do Senders **Route** data to their Receivers today?
- How are **Errors** communicated back to Senders (if at all)?

Senders
- How can we characterize Senders? 
- What are their needs and common issues? 
- How do they send ADT data today? 
- How would they prefer to send ADT data?
- Which personnel is in charge of sending this data?

Receivers
- Who are the Receivers? 
- What are their needs and common issues? 
- How do they receive ADT data today? 
- How would they prefer to receive ADT data?
- Do PHDs eventually send data to CDC BioSense? If so, why should RS send to PHDs _and_ BioSense?

### Links
-   [20240408_ReportStream_ADT-Research_Notes](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/02_Research/20240408_ReportStream_ADT-Research_Notes.docx?d=w98c32c8d6ca5492eb4546e2faa2e330e&csf=1&web=1&e=GQPTNf) includes background notes from JH/MR

### Acceptance criteria
ADT Data
-   [x] Understand what condition(s)/data is sent in ADT
-   [x] Understand how/format ADT data is usually sent
-   [x] Bonus: any extra info, like validation and error communication
Senders
-   [x] High-level summary of Sender needs
-   [x] Current process of sending ADT data
Receivers
-   [x] High-level summary of Receiver needs
-   [x] Current process of receiving ADT data
-   [x] Background info about CDC BioSense
Synthesis
-   [x] Documentation and visualization
-   [x] Unsolved work / questions we have for CDC leadership (Tim, Adi, Mo) are documented and ready to share for their consideration
-   [ ] Materials reviewed by Design Lead and Product Lead

### Out of Scope
- Any work on implementation or documentation on 'how we should do things' - an SRD, for instance. This work is just exploratory in nature.

**Comment by dylansmith-Nava** [comment]
New ticket moved to In Progress! Started working [in this Mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1712766404856/3a591ef9d68c3d805b29ceb5450195fb22a847c2?sender=ufb3824a0e63fafb0304f5774). & I updated the ticket with my new understanding of jobs-to-be-done. cc @Andrey-Glazkv @jillian-hammer @jsutantio

**Comment by dylansmith-Nava** [comment]
As and FYI, I work on this ticket, I am also putting other documentation [in this doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/doc.aspx?sourcedoc=%7Bf9fd9ed0-ffdc-4b6a-b0f6-4b5b8b75099e%7D&action=edit).

**Comment by dylansmith-Nava** [comment]
Moving this ticket to Product Review for @brandonnava to review when he gets back. Please look at the [Syndromic Surveillance Data Desk Research Mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1712766404856/3a591ef9d68c3d805b29ceb5450195fb22a847c2?sender=ufb3824a0e63fafb0304f5774) and the [ADT Data Notes](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/doc.aspx?sourcedoc=%7Bf9fd9ed0-ffdc-4b6a-b0f6-4b5b8b75099e%7D&action=edit) for reference. 

The ACs in this ticket are complete, but there are some more lingering ADT questions. As such, I will create a new ADT-related ticket in drafts. Near-future ADT work is on a hold a little bit per @jillian-hammer's direction, so I won't be moving the new ADT ticket into In Progress for next sprint. cc @Andrey-Glazkv @jsutantio

**Comment by brandonnava** [comment]
Looks good. Ready to close
