### ISSUE TITLE
Update ecosystem map to include eCR

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#13973]
### User story
As a ReportStream team member, I want to understand, and visually map how ELR and eCR data flows overlap and/or diverge on the [ReportStream Ecosystem Map](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1683323417262/846f5431018e48aac7ba2fb6c3f886f9ec5fe9e9?sender=ufb3824a0e63fafb0304f5774), so that I can build upon our teams' systems-level knowledge base and potentially chart areas for opportunity or exploration.

### Background & context
Since conducting FQHC research, we've learned a little more about how senders conduct case reporting (and in some case, electronic case reporting). We'd like to continue to deepen our understanding of eCR as a data type and separate process from ReportStream through a systems-level lens. This ticket captures the work of conducting desk research and updating our existing artifact (RS Ecosystem Map) to reflect our learnings. 

### Risks/Impacts/Considerations
- Unbalancing or disrupting the original intended flow of the ecosystem map
- Creating a map that is too large or unwieldy to help make sense of different systems

### Open questions
-   What are the critical difference(s) between ELR and eCR?
-   How is eCR collected? How is it sent?
-   Who are eCR Senders? Who are eCR Receivers?
-   How can we make space for different data systems/flows and pipelines?
-   How can we scale the Ecosystem Map to seamlessly and clearly add space for different data types?

### Links
- [Create relationship map for the ecosystem ReportStream lives in #9191](https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/9191)
- [[WIP] ReportStream Ecosystem Map](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1687410340700/60ad44b0554a52fb33e7ae0d430ec79470b62e84?sender=ufb3824a0e63fafb0304f5774)
- [ReportStream Ecosystem Map (Clean version)
](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1683323417262/846f5431018e48aac7ba2fb6c3f886f9ec5fe9e9?sender=ufb3824a0e63fafb0304f5774)

### Acceptance criteria
-   [x] Ecosystem map is updated to include eCR data flows from Senders to Receivers

### Out of scope
- Formally establishing any other data types (i.e. vaccinations, ADT, etc.)

**Comment by dylansmith-Nava** [comment]
Began working on an updated ecosystem map version in the [WIP space](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1687410340700/60ad44b0554a52fb33e7ae0d430ec79470b62e84?sender=ufb3824a0e63fafb0304f5774). cc @Andrey-Glazkv @jillian-hammer @jsutantio

**Comment by dylansmith-Nava** [comment]
Finished a draft of the updated ecosystem map within the [WIP space](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1687410340700/60ad44b0554a52fb33e7ae0d430ec79470b62e84?sender=ufb3824a0e63fafb0304f5774) after feedback from @jsutantio. For final review (and if needed, a successive "iteration" ticket), @jsutantio should probably again be approver. I can set a second meeting if that makes sense with her. cc @Andrey-Glazkv @jillian-hammer

**Comment by dylansmith-Nava** [comment]
I'll be discussing this work with @jsutantio on Thursday and bringing to Design Crit also on Thursday. So I am hoping to finalize and close this ticket by EoW.

**Comment by dylansmith-Nava** [comment]
cc @Andrey-Glazkv this ticket isn't finished quite yet - I'll put it back into "In Progress". Hoping to close out by EoW.

**Comment by dylansmith-Nava** [comment]
Review of eCR materials is complete! Thank you to @jsutantio for the final review. The eCR data flow artifact can be found in the [ReportStream Ecosystem Map](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1683323417262/846f5431018e48aac7ba2fb6c3f886f9ec5fe9e9?sender=ufb3824a0e63fafb0304f5774) Mural, floating the right of the map. As such, this ticket can now be closed. cc @Andrey-Glazkv @jillian-hammer
