### ISSUE TITLE
ReportStream Configuration Validation Design Note

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#13985]
### User Story

As a RS developer updating organization, sender, and receiver settings, as well as translation mappings,
I want validation of the YML,
so that I can avoid mistakes and prevent config issues

### Description/Use Case

When updating settings or configurations in ReportStream, there is a need for engineers to be confident that their settings are **valid** prior to "publishing" them.

When loading settings or configurations during runtime, ReportStream should first validate the settings/configs and return an error of they are incorrect.

We should create a design note that addresses the above two issues and defines how ReportStream will support config-time and runtime validation of `settings` and `mappings`.

### Dev Notes

Idea: Look into using https://pkl-lang.org/index.html (Section III.I in [Routing SRD](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engineering/Design/SRD-Routing.docx?d=w3a2fa783e8dc4e9b8397da9f5d968dfa&csf=1&web=1&e=QtXM41))

See [PKL use cases](https://pkl-lang.org/main/current/introduction/use-cases.html) to get a sense of what the library can do. ReportStream should make use of:
- **Generating Static Configuration** - helps validate the settings as they are being written in the YML file by a ReportStream engineer
- **Application Runtime Configuration** - validates the settings during runtime. This can be triggered when setting the settings via CLI or ReportStream website UI.

### Acceptance Criteria

- [ ] Design note created and reviewed

**Comment by Andrey-Glazkv** [comment]
@arnejduranovic
