### ISSUE TITLE
Clarify user need re: senders checking code-to-condition table

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#13987]
## Problem statement
From conversations with engineers, we can leverage recent code-to-condition mapping to reduce back and forth communication for comparing the codes. 

## What you need to know
This originated from an idea around adding UI to update the table, but the larger time-save right now is reducing the time communicating with senders around the codes. 

- [Onboarding Journey Improvement Synthesis](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B3ADDDFE6-961D-49CE-B237-813024723BF6%7D&file=Document1.docx&action=default&mobileredirect=true)

## Acceptance criteria

- [x] ID what measureable positive impacts it can have to onboarding engineers and senders
- [x] Clarify next steps

**Comment by audreykwr** [comment]
@MikaelahD13 started initial info gathering

**Comment by chris-kuryak** [comment]
Next steps identified in #13988
