### ISSUE TITLE
Creating a DACI or RACI for onboarding processes

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#13986]
## Problem statement
In order to see improvements to our onboarding process, we need to know what roles team members are playing in consistently implementing processes and guidelines. 

## What you need to know
- [Onboarding Journey Improvement Synthesis](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B3ADDDFE6-961D-49CE-B237-813024723BF6%7D&file=Document1.docx&action=default&mobileredirect=true)

## Acceptance criteria

- [x] Relevant stakeholders gathered and aligned on roles for maintaining and implementing onboarding processes

**Comment by audreykwr** [comment]
Blocked for this sprint based on some contract lead level DACI things to sort out first

**Comment by audreykwr** [comment]
@MikaelahD13 Contract leads need to finalize some things we thought were ready, and so we won't have the full meeting until next sprint. So I had moved it to blocked, but moved it briefly out because Chris pointed out that we can still have a brief prep discussion with our team async or in a 16th minute. But it will probably go back to blocked until the contract leads can decide what they need to.

**Comment by chris-kuryak** [comment]
We have added our ideas of potential responsibilities.

Blocked until base-level DACI for RS is finalized

**Comment by audreykwr** [comment]
Meeting scheduled for tomorrow

**Comment by audreykwr** [comment]
@MikaelahD13 @chris-kuryak I realized this AC was actually met last sprint. I think we weren't sure if it needed a follow up meeting at the time, but LaFreda is handling next steps mostly async
