### ISSUE TITLE
Support Product in defining Proposal with SR

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#13983]
## Problem statement
This is related to two of the onboarding improvement items: internal visibility of STLT status and process documentation needs. 

## What you need to know

- [Onboarding Journey Improvement Synthesis](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B3ADDDFE6-961D-49CE-B237-813024723BF6%7D&file=Document1.docx&action=default&mobileredirect=true)

## Acceptance criteria

- [x] ID What gaps are on our knowledge with SR
- [x] ID what we need to create/do to implement this proposal for success

**Comment by chris-kuryak** [comment]
Gap in knowledge = SR onboarding process

Success = Aligning with SR, providing clear guidance to Support team, and developing a simplified level of visibility to STLTs that encompasses both SR and RS onboarding.
