### ISSUE TITLE
Engagement On Call Duty -  Sprint 93

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#13993]
## Responsibilities and Acceptance Criteria for this sprint
One engineer per sprint is assigned on-call duty. It is that engineer's responsibility to know the "pulse" of BE issues/health during the sprint. This includes the following responsibilities:

- [ ] Monitor poison queue messages and re-process if needed. Information on how to reprocess messages can be found here: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/standard-operating-procedures/Poison-queue/poison-queue-management.md
- [ ] Primary point-of-contact for any Engagement Support problems that occur during the sprint (including status of those issues)
- [ ] Resolve pager-duty engagement alerts
- [ ] Resolve all security (high-priority) Transport related Dependabots
- [ ] Monitor missing mappings code-to-condition table. Information on how to check missing mappings can be found here: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/standard-operating-procedures/update-observation-mapping-table.md
- [ ] Monitor if recently onboarded STLTs to the UP received any messages for new conditions.
- [ ] LIVD table updates

**Comment by MikaelahD13** [comment]
Update: Ott is currently monitoring the Pager notification and if there any issue he will fix it or notify other engineer to assist. As of 04.30.24 @ 9:48m EST two notifications has be reported and resolved.

**Comment by oslynn** [comment]
Done.
