### ISSUE TITLE
Kansas - UP Migration - Move to Production

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#14002]
### User Story:
As a developer, I want to move the Kansas settings to production after getting approval from the STLT, so that they can start receiving live data.

### Description/Use Case
Kansas is already receiving data from the covid pipeline they will be onboarded to the UP where they will be receiving data from SimpleReport including Covid, Flu and RSV. We need to make sure the message we generate from the UP passes the STLTs validation. We can use SimpleReport to submit test messages to the STLT.

### Dev Notes:

- [ ] Upload the staging receiver settings to Production
- [ ] Copy the receiver's secret key with the new receiver name in Azure's production environment
- [ ] Verify we can connect to the newly created receiver
- [ ] Monitor the UP data for the conditions the receiver is interested in and notify them when reports are routed to them
- [ ] Send a test message through Simple Report and make sure it gets routed to the STLT
- [ ] Send test messages according to the STLT needs

### Acceptance Criteria 
- [ ] Receiver UP settings are pushed to production
- [ ] ReportStream can connect to STLT in production
- [ ] Notify Kansas when reports are routed to them for each condition they are receiving

**Comment by oslynn** [comment]
Done
