### ISSUE TITLE
Add Static Map Image to Web Receiver Site of All States We're Currently Live In

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1401]
Per a request from Sparkle, we'd like to get a static image of a map on the download site in a public area that shows all of the states that we are currently live in. Since the tempo of going live is slow, it shouldn't be problematic to have it as a static image for now that we update as we go into production with more states.

**Comment by MauriceReeves-usds** [comment]
FYSA: @jlusds @sparkle-usds

**Comment by jlusds** [comment]
Linked to launching v3 content
