### ISSUE TITLE
CO File received with future date

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#14027]
## Problem statement
CO received a file with a future date of 4/12 with 4/11 in MSH field

covid-19-e992a294-1191-43eb-9635-8c4c8369a5c9-20240412013026.hl7

## What you need to know
This is the same issue seen in ticket #8881 last year. Timezone defaults to UTC and they need to be converted to Mountain time for correct processing.

## To do
Update CO timezone to Mountain Time

**Comment by GilmoreA6** [comment]
@TaneaY For the indicated file I am seeing an MSH-7 value of 20240411193026 which is the correct time in MDT when the file was sent. Is there potentially another file that was causing the issue?

**Comment by TaneaY** [comment]
@GilmoreA6 correct the MSH-7 value is 20240411193026 but the filename appears as covid-19-e992a294-1191-43eb-9635-8c4c8369a5c9-**20240412013026**.hl7. 

<img width="1017" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWR5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27b6f7e98270cca9e716555798d3739a8512c456/image.png" alt="image.png" />

**Comment by wcollin89** [comment]
Nancy responded to the request for additional details with the following:

> FileName	TransferDate	FileDate
> co-receiver-transform.yml-93bcf9cc-b458-4e6a-ba4c-205d0c7cd386-20240418193027.hl7	04/18/24 13:34:37	04/18/24 16:54:00
> co-receiver-transform.yml-f07ddbb5-3187-4557-a0db-b5499eb47547-20240418163050.hl7	04/18/24 10:38:22	04/18/24 14:09:00
> co-receiver-transform.yml-f76b9747-2ed8-4552-8e37-4bb569d54f9c-20240418103000.hl7	04/18/24 04:46:27	04/18/24 08:37:00
> co-receiver-transform.yml-f071f7b0-b579-4ee7-b958-0d9f6c7c144b-20240418043000.hl7	04/17/24 22:48:32	04/18/24 03:47:00
> co-receiver-transform.yml-cbbcefd0-7ddc-4d1f-8151-c494321b344f-20240418013003.hl7	04/17/24 19:31:57	04/17/24 23:00:00
> co-receiver-transform.yml-882eab5e-c7b1-4650-ad0d-a0226b095471-20240417223020.hl7	04/17/24 16:36:17	04/17/24 19:49:00
> co-receiver-transform.yml-9a4a1b9d-cf23-426d-9aaf-427cc4e74e61-20240417193045.hl7	04/17/24 13:34:12	04/17/24 16:29:00
> co-receiver-transform.yml-b8a72abf-9ac3-4e11-abc7-6e085b3c974d-20240417163007.hl7	04/17/24 10:36:25	04/17/24 14:04:00
> co-receiver-transform.yml-5550011c-9245-4ddb-9c82-6e8ff2d2f6f5-20240417133005.hl7	04/17/24 08:50:20	04/17/24 12:43:00
> co-receiver-transform.yml-43aaae34-7651-41df-b807-4cfc942172ac-20240417073000.hl7	04/17/24 01:34:53	04/17/24 06:49:00
> co-receiver-transform.yml-a9cd9630-48b2-4582-b80e-ea9305b2c328-20240417013004.hl7	04/16/24 19:36:30	04/16/24 22:33:00
> co-receiver-transform.yml-8ae76315-1d0b-495c-b0b4-524ce7e6c4f2-20240416223023.hl7	04/16/24 16:47:54	04/16/24 19:33:00
> co-receiver-transform.yml-2fead96c-60b7-45a8-ad74-6a753b0c942f-20240416193040.hl7	04/16/24 13:37:54	04/16/24 17:17:00
> co-receiver-transform.yml-0373e419-9a1b-43b5-886a-fe507d1030bf-20240416163048.hl7	04/16/24 10:34:29	04/16/24 13:36:00
> co-receiver-transform.yml-506758cc-8774-43b0-87f8-ac9af2cfd45d-20240416103001.hl7	04/16/24 04:42:52	04/16/24 07:52:00
> co-receiver-transform.yml-d8808753-e7f2-471b-9280-998a39f0f29b-20240416013019.hl7	04/15/24 19:35:06	04/15/24 23:01:00
> co-receiver-transform.yml-039aada0-e6e5-4279-abd1-75668d0bdb94-20240415223008.hl7	04/15/24 16:32:12	04/15/24 19:53:00
> co-receiver-transform.yml-6316da10-dc2e-45ca-9241-8a623d35b962-20240415193006.hl7	04/15/24 13:36:10	04/15/24 16:45:00
> co-receiver-transform.yml-43dce667-2133-4233-b79b-f5d046e090b8-20240415163000.hl7	04/15/24 10:33:06	04/15/24 14:22:00
> co-receiver-transform.yml-827d68a2-c6d5-4652-a046-28dcb0bb2a51-20240415133001.hl7	04/15/24 07:44:30	04/15/24 13:16:00

I have included a screenshot for better visibility. Thank you!
<img width="1017" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXQxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09a18382a0e311d237ecd5eca289d85f7d173519/image.png" alt="image.png" />

**Comment by GilmoreA6** [comment]
@TaneaY This fix has been completed. Since the cutover on 4/16 the new pipeline was not appropriately converting the timestamps from UTC to MST/MDT due to a misconfiguration of the settings and was instead leaving all timestamps as UTC which caused the future date/times. This has been corrected and all future reports should have the correct timezone conversion applied.

**Comment by GilmoreA6** [comment]
Corrected receiver settings for:

full-elr-hl7:
changed receiver config:  timeZone from "null" to "MOUNTAIN"
changed receiver config: dateTimeFormat from "OFFSETT" to "LOCAL"

 full-elr-hl7-secondary

**Comment by TaneaY** [comment]
Sent resolution confirmation to user
