### ISSUE TITLE
ResearchOps section: Preparing for research

### ISSUE THREAD

**Issue by dylansmith-Nava** [CDCgov/prime-reportstream#14050]
### User story
As a ReportStream researcher, I want to complete this new ResearchOps section, so that I can help centralize and formalize new ResearchOps materials so current and new Designer/Researchers know a)what to do b)when to do it, and c)why (purpose) when undertaking new research initiatives.

**Summary**: Establishing how a researcher may propose or receive instruction on starting a new research initiative. Requires Design Lead guidance and may need Product input. This process may also differ between scrum teams.

**Sub-sections**:
- Process Overview
- Roles and responsibilities during research
- Proposal writing
- Writing a research plan
- Adding your research plan to the ReportStream and OPHDST trackers

### Background
Prior ResearchOps documents were disjointed and spread among different teams and projects. Likewise, there is not yet one source of truth for ResearchOps strategies, and as such, any previous strategies are not widely practiced within the design team. Revisiting the ResearchOps documents will be helpful to understand which guidelines are still relevant for our team, what gap(s) in knowledge and/or strategy are occurring, and what new material(s) may need to be made.

### Risks/Impacts/Considerations
- Beginning work on some sections may be dependent on the completion of others (see [ReportStream Design and Research: Quarterly Roadmap](https://app.mural.co/t/primedatainput6410/m/nava4113/1672323752891/18dba3187f29b396293271285034f988f4189801?wid=0-1704390582198&outline=open&sender=ufb3824a0e63fafb0304f5774))
- Tools and methods will change over time, requiring periodic updates to the ResearchOps doc
- TBD

### Open questions
- What is the right material to create or include?
- How can I ensure that the research team will have buy-in to the section I am creating?
- TBD

### Links
- [[WIP] CDC ReportStream ResearchOps](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B38251E1C-E969-4238-9959-EA182B99F3E2%7D&file=ResearchOps%20recommendations1.docx&action=default&mobileredirect=true)
- [ReportStream Design and Research: Quarterly Roadmap](https://app.mural.co/t/primedatainput6410/m/nava4113/1672323752891/18dba3187f29b396293271285034f988f4189801?wid=0-1704390582198&outline=open&sender=ufb3824a0e63fafb0304f5774)

### Acceptance criteria
- [x] Shaping Research: Roadmap -> proposal -> proposal meeting agenda
- [x] Preparing for research -> Research plan -> Epic/Tickets -> OPHDST Tracker -> PRA -> etc.

### Out of Scope
- Working outside of this identified section - if your work seems to be spilling into other sections, please bring this up at any Design/Research meeting!
- TBD

**Comment by jakefishbein-navapbc** [comment]
@dylansmith-Nava I'm not sure Folder structure and naming conventions fits in this section. It seems more highlevel than just the proposal. Also Writing a research plan and Adding your research plan to the ReportStream and OPHDST trackers seem to be more aligned with Writing a Research Plan and Conducting Research respectively.

**Comment by dylansmith-Nava** [comment]
@jakefishbein-navapbc makes sense to me. I'll move 'em around. Also for these types of comments I can probably answer these faster if you'd like to comment in the doc itself!

**Comment by jakefishbein-navapbc** [comment]
Add roles and responsibilities

**Comment by jakefishbein-navapbc** [comment]
Each subsection has either been completed or outlined. Revisions and expanding on outlines will be completed after receiving feedback during design crit on 5/16.
