### ISSUE TITLE
ResearchOps: Proofreading

### ISSUE THREAD

**Issue by dylansmith-Nava** [CDCgov/prime-reportstream#14057]
### User story
As a ReportStream researcher, I want to complete this new ResearchOps section, so that I can help centralize and formalize new ResearchOps materials so current and new Designer/Researchers know a)what to do b)when to do it, and c)why (purpose) when undertaking new research initiatives.

Proofread the entire [ResearchOps document](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B38251E1C-E969-4238-9959-EA182B99F3E2%7D&file=%5BWIP%5D%20CDC%20ReportStream%20ResearchOps.docx&action=default&mobileredirect=true)

**Comment by jillian-hammer** [comment]
[ResearchOps Guide](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/00_DesignOperations/ResearchOps/CDC-ReportStream_ResearchOps-Guide.docx?d=w38251e1ce96942389959ea182b99f3e2&csf=1&web=1&e=8jfUSe) finalized!
