### ISSUE TITLE
E2E - Create script to populate Daily Data for Alaska in staging

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-reportstream#14070]
## Problem statement

We do not have reliable data for Alaska in staging and therefore cannot use live data when running our e2e tests as a receiver for Daily Data.
 
## What you need to know
- Blocked by #14210 

## Acceptance criteria

- [ ] Create a script to populate daily data for Alaska in staging each deployment as we do for the ignore organization currently.
- [ ] Update the e2e tests for the daily data receiver from using mock data to live data.

**Comment by chris-kuryak** [comment]
We pivoted away from this idea. Closing.
