### ISSUE TITLE
Add missing values to specimen type value set

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#14074]
### User Story:
As ReportStream, I need to update the specimen type value set to include missing values.

### Description/Use Case
There are a couple of missing values in the value set that Simple Report is going to be sending.

Missing values:

- 433871000124101
- 258610001
- 119335007
- 445447003
- 441620008
- 441903006
- 119336008
- 1293160008

List of SR values/descriptions can be found in [their metabase query](https://www.simplereport.gov/metabase/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjIzLCJvcmRlci1ieSI6W1siYXNjIixbImZpZWxkIiwyMzMsbnVsbF1dXX19LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=)

### Dev Notes:
- The `covid-19/specimen_type` value set under the `covid-19.valuesets` needs to be updated to include missing values.
- Do we also need to update `metadata/tables/local/specimen_type.csv` , and `metadata/tables/local/sender_automation_value_set_row.csv`

### Acceptance Criteria
- [ ] The values are added to the covid-19/specimen_type value set
- [ ] A report with the newly added values gets mapped correctly

**Comment by GilmoreA6** [comment]
Compared list again Covid-19/specimen-type valueset and sender-automation/specimen-type valueset.

Need to add:
Covid-19/specimen-type: 1293160008
sender-automation/specimen-type: 1293160008, 119342007
