### ISSUE TITLE
Resend Montana dropped messages due to specimen type missing

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#14086]
After missing specimen types are added to reportstream reprocess the following messages:

| Report ID                            | Message ID                           | SR Report Id                         | Filename                                                                                                       |   |
|--------------------------------------|--------------------------------------|--------------------------------------|----------------------------------------------------------------------------------------------------------------|---|
| '682fe85c-1da6-4874-8ac6-86826bc21667' | 'c6ddede9-ed9f-49a4-906f-816f3a6e4860' | '87934006-f0d6-4aea-9163-0f7ea306b433' | reports/receive%2Fsimple_report.default%2Fpdi-covid-19-87934006-f0d6-4aea-9163-0f7ea306b433-20240226172600.csv |   |
| '682fe85c-1da6-4874-8ac6-86826bc21667' | 'e44373ff-d768-491f-8512-c91fb05d53f'f | '87934006-f0d6-4aea-9163-0f7ea306b433' | reports/receive%2Fsimple_report.default%2Fpdi-covid-19-87934006-f0d6-4aea-9163-0f7ea306b433-20240226172600.csv |   |
| '4ab65d40-5cbf-4bd6-ad21-fd99fc26d460' | 'b0d2fc34-0350-4b9a-a178-cd6d13257ca3' | '4ab65d40-5cbf-4bd6-ad21-fd99fc26d460' | reports/receive%2Fsimple_report.default%2Fpdi-covid-19-610c96d4-ddce-4d4e-8679-c2f493b42e1c-20240328214400.csv |   |

Check with SimpleReport to see if they can resend the failed message otherwise the failed message would have to be reprocess manually.

If manually we need to download the SR report files and extract the rows for the message ids and resend those.

**Acceptance Criteria**
[ ] Montana receives failed messages

**Comment by oslynn** [comment]
@victor-chaparro @chris-kuryak MT resent messages are completed.
Sent from my localhost:
4/17/2024 at 1:59 PM CST sent two files
 covid-19-762450cd-c616-4324-bbe9-08194326b04f-20240417183300.hl7
covid-19-10552efe-25ca-47d0-973f-0178eb108a3a-20240417182700.hl7

<img width="1873" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd051QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--afe7dfb05552eaf0c2333409a08e74417cbf22ab/image.png" alt="image.png" />
