### ISSUE TITLE
Track interactions with the new Search and Filter features on the Daily Data page

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14084]
## Problem statement
We have no way of measuring how often users interact with the new Search or Filter features on Daily Data.

## What you need to know
- ...

## Acceptance criteria

- [x] Azure App Insights is tracking when the "Search" button on the Daily Data page is clicked
- [x] Azure App Insights is tracking when the "Apply" button on the Daily Data page is clicked
- [x] Azure App Insights is tracking when any "Reset" button on the Daily Data page is clicked
- [x] Test to ensure it is working properly
- [ ] Showcase to Product manager (Chris)

**Comment by penny-lischer** [comment]
@chris-kuryak for `Search` and `Apply`, do you want to track any other information i.e. what was being searched or filtered on?

**Comment by chris-kuryak** [comment]
No, for now we are only interested in if the tool is being used. We can start tracking those other details in the future if necessary.

**Comment by penny-lischer** [comment]
let usg_events = dynamic(["Daily Data | Apply", "Daily Data | Reset", "Daily Data | Search"]);
let grain = iff(true, 3m, 1h);
let mainTable = union pageViews, customEvents, requests
    | where timestamp > ago(30m)
    | where isempty(operation_SyntheticSource)
    | extend name =replace("\n", "", name)
    | extend name =replace("\r", "", name)
    | where '*' in (usg_events) or name in (usg_events);
let resultTable = mainTable;
resultTable
| summarize Events = count() by name
