### ISSUE TITLE
remove org.apache.log4j:1.2.17.2 from build chain 

### ISSUE THREAD

**Issue by david-navapbc** [CDCgov/prime-reportstream#14092]
[dependency-check-report.html.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzV1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c9d9cd3f758db7e7bd761ec34720d6a9a87c389/dependency-check-report.html.zip)

**synopsis**

Attached is the report generated by [OWASP Dependency Check](https://owasp.org/www-project-dependency-check/), invoked as a gradle plugin, for the project. The benefit of invocation by way of the build system is the tool is able to detect more than through build file or artifact analysis alone. 

In this case, it detected plugin `org.jetbrains.dokka:1.9.20` is bringing in `org.apache.log4j:1.2.17.2` which has a ton of nasty security defects associated with it [including malicious code execution and network shenanigans](https://www.cvedetails.com/vulnerability-list/vendor_id-45/product_id-37215/Apache-Log4j.html). [Here](https://github.com/CDCgov/prime-reportstream/blob/32a13ff6888992d6471cdf4f67e997f5cd518113/prime-router/build.gradle.kts#L42) is where the plugin is referenced in the build file. 

**To be clear - the vulnerable dependency is brought in ONLY during the build process by a gradle plugin. It is NOT present in the deliverable.** 

My view is that this is not of immediate concern, but, we should get this out of our build chain. It's end-of-life known vulnerable code that serves no purpose other than to grow risk. 

**ACs**

your mission, should you choose to accept it, is to remove the reference to `org.apache.log4j:1.2.17.2` from the project. This can be accomplished by removing the `dokka` plugin alltogether. This can also be accomplished by forcing the build chain to use a different logger. [The current version of that plugin in maven central is 1.9.20](https://mvnrepository.com/artifact/org.jetbrains.dokka/dokka-gradle-plugin) - so bumping the version is not an option.

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14092?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14092?planning-poker) with Zenhub @david-navapbc

**Comment by david-navapbc** [comment]
https://github.com/CDCgov/prime-reportstream/pull/14123
