### ISSUE TITLE
Investigate OK REST Transport

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#14107]
OK, REST failure in last mile failure on 401 UNAUTHORIZED Invalid User.  When trigger resend, it report successfully sent.
However, it looks like that didn't receiver any resend neither.

Investigation:  in Localhost tries to send the resent file to them and monitor the response to see a file in response.  It would be along the lines of CDC_PRIME_REPORTSTREAM_2024-04-04_17:09:36.006264-05:00.hl7

**Comment by oslynn** [comment]
Resubmit all rejected reports in last-mile-failure to OK.

<img width="790" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3gvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52e078f1f61d688eacc8a86207b223690d2cca87/image.png" alt="image.png" />

**Comment by chris-kuryak** [comment]
@oslynn to get with Gabriel on Platform team for incorporating changes into his PR to fix this issue.

**Comment by oslynn** [comment]
done
