### ISSUE TITLE
Create Schema to de-identify data per RADx MARS requirements

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#14104]
### User Story

As ReportStream, I need the ability to de-identify HL7 v2 messages, so that I can remove sensitive data from messages.

### Description/Use Case

We need to add the ability to de-identify messages that flow through the Universal Pipeline. One way to accomplish this is to create a schema that we can use to de-identify messages if needed.

The RADx MARS HL7 v2 format provides a guide on how to de-identify messages here: https://www.nibib.nih.gov/covid-19/radx-tech-program/mars/hl7-message-de-identification-for-sending-to-hhs-protect

### Dev Notes

Try to use existing Github SOP documentation and identify gaps. https://github.com/CDCgov/prime-reportstream/tree/master/prime-router/docs

### Acceptance Criteria

- [x] HL7 v2 messages can be de-identified through the Universal Pipeline

**Comment by MikaelahD13** [comment]
Currently running tests with sample data, will be correcting issues is any comes up.
