### ISSUE TITLE
Fix the transport type: NULL mystery

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1410]
If you look at master from June 24, you'll see organizations-local.yml had this for the HL7_NULL and AS2 receivers:

```
transport
  type: NULL

```
or

```
transport
  type: "NULL"

```
I'm not sure how this got there, but it dfoes not load into the settings, and this is why the HL7_NULL tests were failing.

Step 1 is to figure out why/how this got into the .yml file
Step 2 is to figure out if its correct.  If it is, then fix <something> so that it loads properly.  If its not correct, then fix <something else> so that its not generated any more in the future.

**Comment by jlusds** [comment]
What's the status of this?
