### ISSUE TITLE
Update CA to use REST instead of SFTP

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#14108]
### User Story

As ca-dph, I want to receive messages via REST transport.

### Description/Use Case

CA is moving away from using SFTP and wants to start using REST APIs to send them reports. Attached is their rest API guide. [SaPHIRE Rest API Guide-rev 032624.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUZ6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd1ab63742d969b7d59e96d1a50ffd28204535f3/SaPHIRE%20Rest%20API%20Guide-rev%20032624.pdf)

### Dev Notes

- Upload Client certificate provided by CA into azure

### Acceptance Criteria

- [ ] Onboard ca-dph as REST receiver in staging
- [ ] Validate ca-dph can receive messages through REST in staging
- [ ] Move settings to production
- [ ] Validate ca-dph can receive messages through REST in prod

**Comment by chris-kuryak** [comment]
Waiting on DevOps to finish work on #14722

**Comment by chris-kuryak** [comment]
Currently testing

**Comment by chris-kuryak** [comment]
Waiting for CA to review test messages

**Comment by chris-kuryak** [comment]
CA responded. Messages look good.

Next Steps (see email from Ellaison):
1. Update the cert
2. Send 5-10 more messages using new cert

**Comment by chris-kuryak** [comment]
Waiting on CA now again

**Comment by chris-kuryak** [comment]
Per Victor, this is now complete.
