### ISSUE TITLE
Create JSON schema for organizations.yml

### ISSUE THREAD

**Issue by jalbinson** [CDCgov/prime-reportstream#14109]
### User Story
Create JSON Schema for organizations

### Description/Use Case
We want updates to organizations.yml to be validated through JSON Schema.

### Dev Notes
- Add the schema to the top of the organizations.yml file to see if they are working (add invalid data to see red lines)
- These could be helpful (don't just copy/paste though!)
  - https://codebeautify.org/yaml-to-json-schema-generator
  - https://github.com/FasterXML/jackson-module-jsonSchema
- Add basic value validations where it seems appropriate

### Acceptance Criteria
- A new JSON schema for organizations.yml
- JSON Schema referenced at top of organizations.yml
- Create a service to use the json-schema library in code
  - Does not need to be called at this point
  - Unit tested
- Intellij automatically recognizes errors and reports them
- Add documentation on how to use the json schema reference
- Add reference to json schema on top of other files that use organizations structure

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14109?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14109?planning-poker) with Zenhub @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14109?planning-poker) with Zenhub @david-navapbc
