### ISSUE TITLE
Update the condition mapping code to indicate the correct index in the original report for an item with an unmappable code

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#14114]
### User Story
As a report stream sender, I would like to know which item in my report contained an unmappable condition

### Description/Use Case
Currently, the index set in the action log detail is the index out of the produced FHIR bundles which does not map to the actual index in the report.  The mapping logic needs to be shifted so that a sender can correctly identify the item in the report they sent that had an unmappable condition.

### Dev Notes
- This will likely require adjusting where this code runs in the conversion step

### Acceptance Criteria
- [ ] The index reported in the action log detail for an unmappable condition always reflects the index in the original report

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14114?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14114?planning-poker) with Zenhub @david-navapbc
