### ISSUE TITLE
Clean up the second part of the fhir convert function

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#14115]
### User Story
As a RS developer, I would like the FHIR convert step to have adequate logging and to create the correct lineage structures

### Description/Use Case
The newly refactoring parsing/validating of items are well logged, but the untouched code is not.  Additionally, on first glance the report/item lineage creation might be incorrect or least can be simplified and cleaned up.

### Risks/Impacts/Considerations
Should be done after additional tests are added for the FhirConvert step.

### Acceptance Criteria
- [x] Logging similar to what is done for `FhirTranslator` is added to `FhirConverter`
- [ ] Errors that occur in the convert step show up in the history endpoint result under the "errors" attribute
- [ ] Warnings that occur in the convert step show up in the history endpoint result under the "warnings" attribute
- [x] Code for generating report/item lineage is evaluated for accuracy and then fixed and/or cleaned up

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14115?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14115?planning-poker) with Zenhub @david-navapbc
