### ISSUE TITLE
Create Validation Service to validate organizations

### ISSUE THREAD

**Issue by jalbinson** [CDCgov/prime-reportstream#14110]
### User Story
We want to use Konform to validate organizations, senders, and receivers after they are parsed into objects.

### Description/Use Case
We want configuration after they are parsed into objects to be validated beyond just their structure. Find some values within an organization that could use additional validation (non-negative numbers, string formatting, etc). A big portion of this ticket is to set up the scaffolding for validation for the future objects.

### Dev Notes
- Keep validation objects together in a module
- Make a validation service
- https://github.com/konform-kt/konform

### Acceptance Criteria
- validation service created
- pattern set up for future validations
- unit tests

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14110?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14110?planning-poker) with Zenhub @david-navapbc
