### ISSUE TITLE
Google Search Console Exploration

### ISSUE THREAD

**Issue by etanb** [CDCgov/prime-reportstream#14125]
We just got access to our Google Search Console (https://search.google.com/) and we should deep-dive into it's capabilities.

Acceptance Criteria:

- [x] Identify which features of Google Search console may be the most useful to ReportStream 
- [x] Review with product

**Comment by etanb** [comment]
@chris-kuryak here's my report:

**Some Insights:**

- The Performance page should be our bread and butter. Specifically the Queries section will show us HOW users are finding Reportstream via Google Search with what they're inputting into Goole Search. For example, the large majority of users are finding us by searching "reportstream" or "report stream". However, a non-zero number of people are using the word "prime". That might be interesting to delve into.

- Another issue that I was immediately able to solve was that Google did _not_ have our sitemap. I submitted our sitemap for indexing so that'll hopefully provide a lot more insight -- we currently only have **4** pages indexed! That means **66** pages are not being indexed.

- If you look at our Performance over time, using the Compare function, you can see that there's some seasonality OR some other time-based correlation with searches for Reportstream. Perhaps when there's pandemic news? Or some other announcement? 

- We already know this, but our site is not optimized for mobile. The low score might penalize our search however, so might be worth at least thinking about optimizing the public pages.

- Within the pages section, it seems like our staging and demo environments are being indexed. We should have google remove them. There's also the meta question here of: is it ok that staging and demo environments are publically accessible?

**Comment by etanb** [comment]
Moving this to blocked until @chris-kuryak and I can sync, and check off that last Acceptance Criteria!

**Comment by chris-kuryak** [comment]
Looks good to me.

I will make a follow up ticket to make sure our Staging and Demo environments do not get indexed and show up in search results.
