### ISSUE TITLE
Add manual opt-out text to email template

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#1413]
### Problem statement

Re: standup on 6/25, the automated opt-out process won't be set until we move to React. Set up a manual, email-us-to-opt-out process and update the template footer content to reflect.

### To do

- [x] Re-build Foundation for Emails template
- [ ] Add new html to SendGrid

**Comment by Rebecca-LM** [comment]
Just a plug before I go to make sure it follows the [RS style guide](https://docs.google.com/document/d/1re6dTgrY2kjY-E1rZHENh-1x0fs5voyyG9AWbEXWsbY/edit) guidelines!

**Comment by drew-usds** [comment]
Template screengrab for reference:
<img src="https://user-images.githubusercontent.com/57154955/123744357-a6263c00-d87c-11eb-9077-cfb2f8de7d44.png" width="50%" />

**Comment by drew-usds** [comment]
## Updated copy

>ReportStream
>
>PHD Name, State
>COVID-19 test data is ready for download
>
>View and download daily test results for Tuesday June 29, 2021 [link]
>
>Data are available to download for 30 days after receipt of this email. Failure to download reports within 30 days may result in the loss of data.
>
>Data aggregated with ReportStream may be subject to the Privacy Act of 1974, the Health Insurance Portability and Accountability Act of 1996 (HIPAA), and other laws, and requires special safeguarding.
>
>Contact
reportstream@cdc.gov
Centers for Disease Control and Prevention
1600 Clifton Road
Atlanta, GA 30329
>
>Unsubscribe
To unsubscribe from this list, email reportstream@cdc.gov with the subject line "Unsubscribe from daily email."

## Template screengrab for reference

<img src="https://images.zenhubusercontent.com/5ff50e49f74e134e95117280/595947ea-03f4-488c-89a1-7b1ce1278eb5" width="50%" />
