### ISSUE TITLE
Create Structure and Next Steps for Improving Internal Documentation

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14148]
## Problem statement
Easy to reference and usable internal documentation can assist in consistent application of processes and guidelines and result in an excellent user experience.

## What you need to know
Moving this opportunity forward is critical to the success of any other onboarding/process improvements. More details on work surrounding this here:

- [Onboarding Journey Improvement Synthesis](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B3ADDDFE6-961D-49CE-B237-813024723BF6%7D&file=Document1.docx&action=default&mobileredirect=true)

## Acceptance criteria

- [x] New Sharepoint Structure/Organization implemented
- [x] ID needs and current reality of templates
- [ ] Help create followon ticket to migrate infor into new structure with Chris and LaFreda
- [ ] Help create process for sharing new structure and needs with RS team

## To do

- [ ] ...

**Comment by audreykwr** [comment]
This is going to carry over a few points because of an opportunity to collaborate with OPHDST comms on some of this

**Comment by audreykwr** [comment]
Got initial set up, reviewed with design team and LaFreda. Working on cleaning it up and implementation plans for DMs with LaFreda @MikaelahD13

**Comment by audreykwr** [comment]
Just need to finalize the follow on work, should be closed by sprint end
