### ISSUE TITLE
Finalize plans for UP Comms Content Changes and Align with stakeholders

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14147]
## Problem Statement
We want to develop a plan to update our comms based on the new information we learned and to assist with Phase 2's focus on migrating senders. 

## What you need to know
- [Current drafting space](https://cdc-my.sharepoint.com/:p:/r/personal/uou6_cdc_gov/_layouts/15/Doc.aspx?sourcedoc=%7BD2E7D963-C302-4806-9A9E-78D58DE161C1%7D&file=UP%20change%20communication%20messaging%20%2B%20plans%20-%20Copy.pptx&action=edit&mobileredirect=true)

## Acceptance criteria

- [x] Remove support for CSV from website and UP comms
- [ ] Connect with Glenn and Chris to review existing HL7 Sender responses (that haven't sent us data in the past 60 days)
- [x] Finalize plans/roadmap for implementing changes
- [x] Review with stakeholders (Max, Chris, Glenn)

**Comment by audreykwr** [comment]
Reviewing and getting feedback today/tomorrow
