### ISSUE TITLE
Whitelist the DAP tag for ReportStream website analytics

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14140]
## Problem statement
The DAP code (used to track our public website analytics through Google Analytics) is being blocked by our agency Content Security Policy. We need to whitelist the DAP code so the tag is allowed to send data.

## What you need to know

- <img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzEvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01b23f668bf4a95c36add2d3d0392cb7a628a725/image.png" alt="image.png" />

## Acceptance criteria

- [ ] DAP code is no longer being blocked by our Content Security Policy
- [ ] Check (with Chris) that GA4 is working properly (collecting data from ReportStream website)

**Comment by etanb** [comment]
The PR itself is officially merged BUT we need the changes within Azure to take effect as well. Devops has been made away of this issue and can be tracked here: https://github.com/CDCgov/prime-reportstream/issues/14202

cc @chris-kuryak

**Comment by chris-kuryak** [comment]
GA4 still not working properly, still waiting on DevOps to finish their ticket #14202

**Comment by chris-kuryak** [comment]
Just checked, appears to be working now. Closing ticket.

**Comment by etanb** [comment]
<img width="1728" alt="Screenshot 2024-05-16 at 9 48 40 AM" src="https://github.com/CDCgov/prime-reportstream/assets/516877/0495a0d9-3c49-4c68-b7bb-77902cd9a083">

double confirming that we're all good!
