### ISSUE TITLE
Configure receivers throwing exceptions in Staging

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#14144]
## Problem statement
There are couple of receivers throwing exceptions  in staging due to missing secrets.

## What you need to know
BAPTIST-ALABAMA--ETOR-NBS-RESULTS and EPIC--ETOR-NBS-RESULTS are the receivers throwing exceptions in staging. We need to create secrets for them in azure.

## Acceptance criteria
- [ ] Receivers in staging don't throw unnecessary exceptions in staging

**Comment by oslynn** [comment]
Deleted the transport and set routingFilter to "allowNone()" for both receivers above.
