### ISSUE TITLE
Texas HIV Pilot: Align with internal stakeholders on how/when to approach Texas

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14151]
## Acceptance criteria
- [x] Identify strategy for approaching Texas (work with Glenn, Audrey, Jillian, Chris)
  - [x] What will we tell them
  - [x] In what order will we tell them
  - [x] What are the questions/feedback we want to get from Texas
  - [x] How to handle any questions we may get from them
- [x] Identify and create materials needed (if any) for the conversation with Texas
- [x] Determine/schedule (with Glenn) time to meet with Texas
- [x] Share with Max for awareness and any feedback

**Comment by jakefishbein-navapbc** [comment]
Meeting schedule with Jillian and Audrey for May 8th to develop initial strategy ideas as Chris and Glenn are OOO. A meeting has been schedule with all of us on May 13th to finalize plan before meeting with Texas on the 15th.

**Comment by chris-kuryak** [comment]
Will span to following sprint

**Comment by jakefishbein-navapbc** [comment]
[Link to meeting plan](https://docs.google.com/document/d/1KJmsY6l9Wd7h8p1S7FQ7_vBqZyP0djxY2wTqGX4ftZA/edit?usp=sharing)
