### ISSUE TITLE
Create YAML Validation CLI task

### ISSUE THREAD

**Issue by jalbinson** [CDCgov/prime-reportstream#14158]
### User Story
We want to validate our YAML files from the command line

### Dev Notes
- To start, this will only support organization.yml
- Include a flag to determine if we are checking all fhir mappings and fhir transforms in the repo or an external file
  - If an external file, include the path and the type (organization, fhir mapping, or fhir transform)
- Run the json schema code against the files
- Run Konform validation code against the files
- Accumulate all errors if any
  - Do not fail fast to obtain a complete report of problems
- Print out report and return an error so the CI task fails (if running on github)

### Acceptance Criteria
- CLI task created
- It works for existing organizations.yml or passed in yml files
- pattern set up for future types (fhir mapping and fhir transforms)
- unit tests

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14158?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14158?planning-poker) with Zenhub @JFisk42
