### ISSUE TITLE
Hook up Validation CLI task to build CI pipeline

### ISSUE THREAD

**Issue by jalbinson** [CDCgov/prime-reportstream#14159]
### User Story
We want failures to validate our YAML files to cause errors in our CI pipeline

### Dev Notes
- To start, we are only validating organizations.yml
- Include a step to run created CLI task as a part of the CI pipeline on github

### Acceptance Criteria
- if there are errors in organizations.yml, the CI should not pass on github
- pattern set up for other types of YAML to be included in the future (probably as a part of the CLI code)

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14159?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14159?planning-poker) with Zenhub @JFisk42
