### ISSUE TITLE
Create Validation pipeline for FHIR->HL7 mappings

### ISSUE THREAD

**Issue by jalbinson** [CDCgov/prime-reportstream#14169]
### User Story
We want to check FHIR mappings for potential errors during development

Only handle FHIR->HL7 mappings.

### Dev Notes
- Follow pattern set up for organizations
- Add json schema for FHIR mappings
  - Include references to schema at the top of all fhir mapping files
- Add Konform validations for FHIR mapping

### Acceptance Criteria
- FHIR mappings now have Intellij autocomplete
- FHIR mappings will now be checked to have valid structure and values

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14169?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14169?planning-poker) with Zenhub @JFisk42
