### ISSUE TITLE
Create Validation pipeline for FHIR->FHIR transforms

### ISSUE THREAD

**Issue by jalbinson** [CDCgov/prime-reportstream#14168]
### User Story
We want to check FHIR transforms for potential errors during development

Only handle FHIR->FHIR transforms

### Dev Notes
- Follow pattern set up for organizations
- Add json schema for FHIR transforms
  - Include references to schema at the top of all fhir transform files
- Add Konform validations for FHIR transforms

### Acceptance Criteria
- FHIR transforms now have Intellij autocomplete
- FHIR transforms will now be checked to have valid structure and values

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14168?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14168?planning-poker) with Zenhub @adegolier

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14168?planning-poker) with Zenhub @jalbinson
