### ISSUE TITLE
Updating Content Ecosystem

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14172]
## Problem statement
Our content ecosystem map needs to be updated to provide valuable reference to who and what is involved in content for our project.

## What you need to know

We created an initial content ecosystem map and have revisited it once or twice, but it has not been updated to reflect the most recent realities, especially regarding CDC and OPHDST.

- [Old content ecosystem](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1675805766402/22ae41765b193e5b9d0ecb273170763edca9dbbe)

## Acceptance criteria

- [x] Map updated with relevant changes or new info about RS team or CDC departments

**Comment by audreykwr** [comment]
@MikaelahD13 I've begun drafting and am working on tweaking it

**Comment by audreykwr** [comment]
Wrapping up over Monday and Tuesday to finish before sprint end
