### ISSUE TITLE
Newsletter Exploration

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14171]
## Problem statement

ReportStream needs to learn the best way to maintain contact with users to continue providing them value. A newsletter is one idea to explore to meet that need.

## What you need to know
This does not assume that a newsletter is a solution we will pursue, but one that we will explore within the scope of business goals, user needs, and capacity.

## Acceptance criteria

- [x] User needs, business goals, and capacity clarified
- [x] Proposal for next steps created and reviewed with relevant stakeholders

## To do

- [ ] ...

**Comment by audreykwr** [comment]
Synced with Chris last Friday on findings and next steps. Going to share with design before sprint end to close.
