### ISSUE TITLE
PA-ELR System Maintenance Scheduled - 4/29 5-7PM

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#14193]
## **Problem Statement**

We received an email in the ReportStream inbox from PA-ELR regarding scheduled system maintenance that will affect connectivity.

## **What you need to know**

Email received:

> This email is to notify PA-ELR users about the upcoming Production environment for PA-ELR services and PA-NEDSS unavailability.
> 
> PRODUCTION environment services – PA-ELR services and PA-NEDSS - will be unavailable for system maintenance on **Monday, April 29, 2024, 5 PM EST until approximately 7 PM EST.**  
> 
> This will affect PA-ELR manual file uploads and automated file uploads, including ELR web service, PAWS, HIE/PHG and PHINMS.
> 
> During this time span if you attempt to submit files to Production PA-ELR, you will receive a message stating that it is currently unavailable for maintenance. 
> 
> If you receive the error message, please only resubmit files during this time span after being notified services are available.
> 
> Please share this information provided with other members of your organization that may not have received this email.

## **Acceptance Criteria**

- [x] Check on 4/30 or later that no messages have failed to be delivered to PA
- [x] If messages have failed to be delivered, resubmit successfully

**Comment by victor-chaparro** [comment]
No messages failed to be delivered to PA during this time
