### ISSUE TITLE
Modify Azure CSP

### ISSUE THREAD

**Issue by snesm** [CDCgov/prime-reportstream#14202]
## Problem statement

Add the following to Azure CSP:

https://www.google-analytics.com
https://www.googletagmanager.com

## What you need to know

Needed to complete https://github.com/CDCgov/prime-reportstream/pull/14166 / https://github.com/CDCgov/prime-reportstream/issues/14140

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by dkrylovsb** [comment]
This is done in Staging and Prod: 
![image](https://github.com/CDCgov/prime-reportstream/assets/11096575/a3a4fc49-53f6-4917-9f03-42cdc0c08836)
