### ISSUE TITLE
[BUG] [SPIKE] ELIMS messages not returning in Daily Data search

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14206]
## What you need to know

As an example,

1. Log in to staging as a Prime Admin
2. Set as CDC-ELIMS organization
3. Go to Daily Data
4. The following file appears in the table: InterPartner~ELIMS_ELR~CDC~KY~Test~Test~20240315150045113~STOP~13_72321_05227632_40060.hl7-None-0444ca52-e09c-4401-bf20-fec13d16ffef-20240318150040.hl7
5. But when you use the Search feature to find that file, it does not appear in the results

Expected Result: The file should be shown in the search results

## Acceptance criteria
- [x] All ELIMS files can be returned with a valid search
- [ ] Test the solution on the following orgs:
  - [ ] CDC-ELIMS
  - [ ] NY-PHD
  - [ ] CA-DPH

**Comment by penny-lischer** [comment]
The filename has special characters that need to be encoded for the API to match on the string.
