### ISSUE TITLE
[BUG] Visual Bug on Daily Data filters

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14209]
## Problem statement
There is a visual bug that rarely appears on the the Daily Data filter section.

## What you need to know

<img width="1297" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0dhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b40555a63f3af4e8e152783185d56e9b80c97bf8/Screenshot%202024-04-24%20at%202.50.17%E2%80%AFPM.png" alt="Screenshot 2024-04-24 at 2.50.17 PM.png" />

## Acceptance criteria

- [ ] Shortened box for receiver does not appear
- [ ] Misalignment of Apply/Reset buttons does not appear

**Comment by chris-kuryak** [comment]
Penny: Perhaps we need a minimum width?
Etan: There may be a deeper core issue here around loading

**Comment by penny-lischer** [comment]
Not able to reproduce. Possibly happened when we had first receiver as default.
