### ISSUE TITLE
[SPIKE] Identify how to add support within the E2E testing architecture to allow choosing what data to run E2E tests against

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14210]
## Problem statement
E2E tests always querying against Staging data is causing a large number of exceptions and PagerDuty alerts. To prevent this from happening, we want to allow E2E tests to run against different types of data including Local, Mock, Staging, and Live.

## What you need to know
- ...

## Acceptance criteria

- [x] Document Strategies for a user to specify which data to use for E2E tests:
  - [x] Local
  - [x] Mock
  - [x] Staging
  - [x] Live
- [x] Review with team for alignment at Engr Sync
  - [x] Create prototype that can be demonstrated
- [x] Create follow-on engineering ticket for implementation

**Comment by penny-lischer** [comment]
We now have a flag called isMockDisabled that when set to true, will run the tests against non mock data.

To run the smoke tests we would need to add a github action that runs the following command 
`yarn run test:e2e-smoke`

To have a test as part of the smoke test, you need to add a tag to the test or group of tests. i,e.
```
test.describe(
            "When there is no error",
            {
                tag: "@smoke",
            },
            () => {
                test("nav contains the 'Admin tools' dropdown with 'Organization Settings' option", async ({
                    organizationPage,
                }) => {
                 ... testing something
               });
   });
```

**Comment by penny-lischer** [comment]
Follow on tickets:
[15057](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/15057)
