### ISSUE TITLE
HCI - ProPhase User Requesting Login Access to RS

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#14234]
## **Problem Statement**

We received a request in the RS inbox from Matthew Chriscoe, asking for a login for the HCINTEGRATIONS sender account.

## **What you need to know**

Currently, the HCINTEGRATIONS Sender group does not exist in Okta and will need to be created.

## **Acceptance Criteria**

- [ ] User is able to log into the RS dashboard and access their Submission History

## **To Do**

- [x] Create Okta group for HCINTEGRATIONS Sender
- [x] Add user mchriscoe@prophasedx.com

## **Additional Comments**

Should Sender groups be created in Okta as part of the onboarding process?

**Comment by chris-kuryak** [comment]
Group created.
User created and activation email sent.
