### ISSUE TITLE
Update Pagination and Table Component for Daily Data table

### ISSUE THREAD

**Issue by etanb** [CDCgov/prime-reportstream#14238]
## Problem statement
We currently utilize a fairly complicated [custom version of Pagination](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/components/Table/Pagination.tsx) in our code. Since we're trying to be lock-step with USWDS React component library, we should be utilizing their [Pagination](https://designsystem.digital.gov/components/pagination/) and not rolling our own.

In addition, our `UsePagination` [hook](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/hooks/UsePagination.ts) could use a re-think and potential re-work. It's fairly complicated but we rely on it for ALL of our tables' data. The main code was created 2 years ago, and there are some race conditions and other code complexities we should work through.

## Acceptance criteria
- [ ] Table on Daily Data page use the new custom table component (USWDS)
- [ ] Pagination on Daily Data page uses the updated BE API pagination functionality with USWDS component
- [ ] Pagination works as expected: Users can access all of their data through pagination
- [ ] Filter status bar works as expected: Total results number is accurate
- [ ] Include existing AppInsights tracking code within new pagination
- [ ] Determine the goal/acceptance criteria for improving the UsePagination hook

**Comment by penny-lischer** [comment]
We may want to separate the last AC into another ticket. It may inflate this ticket since we should convert the e2e file to the POM and we will also need to get the tests working.

**Comment by chris-kuryak** [comment]
Per Etan, need a couple more days to complete
