### ISSUE TITLE
Create a common HL7 message class for RS and update catchall mappings

### ISSUE THREAD

**Issue by jack-h-wang** [CDCgov/prime-reportstream#14249]
### User Story
As a RS engineer, I want to consolidate our HL7 message classes and mappings, so that we can more easily support new formats.

### Description/Use Case
With very little exception we have found that the existing HL7 v2.7 message class supports the majority of our use scenarios. The RADx MARS class expands on the existing HL7 v2.7 class to support an extended definition of the OBX segment. We theorize the class developed for RADx MARS can be used to cover all other formats supported by RS, including NIST ELR. We need to check the class against the specifications for NIST ELR to confirm this, and make any changes necessary to our catchall mappings.

Optimally, this should reduce the number of classes and mapping sets in use to a single common set, and remove the need to change conformance profiles to support different formats.

### Dev Notes
- We mainly need to confirm that we can create a single class that is the most common denominator of the NIST ELR and RADx MARS use cases - ensure that segments and datatypes are set to a commonly functional usage constraint (optional vs required fields, data length, repeatability, etc).
- The NIST ELR profile can be viewed here: https://hl7v2-elr-testing.nist.gov/mu-elr/
- The RADx MARS profile can be viewed here (select RADx MARS from the dropdown on the top right): https://hl7v2-gvt.nist.gov/gvt/#/cf

### Acceptance Criteria
- A common HL7 message class is created for use throughout RS.
- Catchall mappings are updated to use the common HL7 message class.

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14249?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14249?planning-poker) with Zenhub @david-navapbc
