### ISSUE TITLE
Consolidate the Report Enum on Sender and Report

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#14256]
### User Story
As a developer on RS, I would like a consistent way to reference the format for a report.
### Description/Use Case
Currently,  there is both `Report.Format` and `Sender.Report` enums that reference the same values but can be used interchangeably in the code.

### Acceptance Criteria
- [ ] A single `Format` enum exists

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14256?planning-poker) with Zenhub @adegolier @jalbinson

**Comment by Andrey-Glazkv** [comment]
duplicate of #7656
