### ISSUE TITLE
Fix/Uncomment Skipped  Daily Data e2e tests

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-reportstream#14280]
## Problem statement

Some of the daily data e2e tests were skipped b/c the current pagination control was interfering when updating the table and filter status control when 'Apply' or 'Search' buttons were triggered.

## Acceptance criteria

- [ ] Uncomment skipped tests.

## To do

- [ ] ...

**Comment by penny-lischer** [comment]
Blocked by #14238

**Comment by etanb** [comment]
Tests in `daily-data.spec` still need addressing.
