### ISSUE TITLE
Checkin on ETOR News Item conversation

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14298]
## Problem statement
We had delayed on conversations around the ETOR news item until later this quarter to align the content with an event LDX will be presenting at. Now we want to check in on that conversation.

## What you need to know

- The follow-on ticket to this work will be finalizing the ETOR new item content: #13510 
- Previous ticket: #13368

## Acceptance criteria

- [x] Determine timeline for ETOR news item based on roundtable event focus 

## To do

- [x] Connect with Rebecca

**Comment by audreykwr** [comment]
Email sent to Rebecca on Friday. Got an OOO response that she's back in today (5/14)

**Comment by audreykwr** [comment]
Meeting with Rebecca scheduled for Tuesday
