### ISSUE TITLE
Accept Messages from SimpleReport in Real Time

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1431]
## Overview
Adam at SimpleReport reached out to me last week to discuss their intended conversion of sending messages in two-hour intervals pre-batched to sending us messages in (near) real-time via Azure Storage Queue. The net effect for us would be that we would receive many single-row files that will then need to be batched at the schedule defined for each receiver.

There are a few things to consider here, in no particular order:

1. We will suddenly increase the volume of the files that we're receiving and storing
2. We need to do some more testing on batching a large number of very small files as they're coming in
3. We could potentially lose the functionality of the `prime-data-upload` channel in Slack which is our quickest way to see what's getting sent
4. We lose a lot of the meaning of a `report_file` when everything comes in one at a time, at least in terms of the `report_lineage`. We should evaluate any changes we may want to make there.

### Short-term Thoughts:
- We should connect our staging system at ReportStream to the SimpleReport test system. Both contain fake data so there shouldn't be any issue with having those two system communicate
- We should allow SimpleReport to start hammering on the staging system doing this, and we should evaluate what the impact is on performance, etc
  - We will need to update staging so the batching times more closely match what we have in production, or the value of the test is lost

### Medium-term Thinking:
- As we move into this, it occurs to me that if we take down our system for a period of time to do a deployment, etc, sending systems like SimpleReport would report errors unless we can signal that we're down for maintenance. I don't like this idea or way of doing things. If we're going to need to be available to hundreds or thousands of senders, we should have near 100% up time. To that end, I think we should do the inverse of what SimpleReport is doing, and create an endpoint that will then push incoming messages to an Azure Storage Queue, and then when ReportStream comes back online, those messages could be consumed. This is something I think we should dedicate some time to in the next sprint or too.

**Comment by MauriceReeves-usds** [comment]
fysa: @nullflux

**Comment by nullflux** [comment]
**Re: your medium-term thinking:**

I think this is a good plan! Rest assured that in the short term, our approach includes a redrive policy and dead-letter queue so that in the event of a ReportStream outage, no reports would be lost as a result of failed transmission

**Comment by td-usds** [comment]
> To that end, I think we should do the inverse of what SimpleReport is doing, and create an endpoint that will then push incoming messages to an Azure Storage Queue, and then when ReportStream comes back online, those messages could be consumed. This is something I think we should dedicate some time to in the next sprint or too.

This makes a lot of sense to me. I think this is a must!

**Comment by jimduff-usds** [comment]
I'm closing this, as we now can handle this type of load if SimpleReport wishes to swich to sending one record at a time in realtime.  So this would require a small bit of operational support to make sure its working, but no coding.
