### ISSUE TITLE
Diagnose FHIR Transform Library Poor Performance

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#14335]
### User Story

As a engineer on ReportStream,
I want to ensure the FHIR Transform Library is fast,
so that it does not prevent steps in the pipeline from completing

### Description/Use Case

FHIR Transforms have been identified as the potential cause of the Convert function timing out. The functionality (especially in the convert function) should be evaluated and performance improvements should be suggested.

This issue has occurred with the SimpleReport sender, so the sender transform they use should be closely scrutinized.

### Acceptance Criteria

- [ ] Tickets created to speed up the FHIR Transform Library

**Comment by Andrey-Glazkv** [comment]
The performance was found acceptable and new tickets will be created to further monitor performance - ticket closed
