### ISSUE TITLE
Illinois receiver settings/ filter update

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#14337]
## Problem statement
We would like to change what test results that Illinois is receiving from Simple Report/Report Stream, what is the best way to do that? What are the current options available?

## What you need to know

Contact from IL Charlotte Picard, charlotte.picard@illinois.gov

## To do

- Provide current settings
- Provide available options

**Comment by LaFreda1** [comment]
@TaneaY I'm no longer on the engagement team. I tried to assign this to Mikaelah, the new delivery manager but I can't find her in the system. If you want to connect with her on this, I will follow up on how to assign her tickets. Thanks!

**Comment by TaneaY** [comment]
@LaFreda1 I could not find her either and Chris is OOO. I have reached out via slack

**Comment by chris-kuryak** [comment]
@TaneaY Just discussed this with the team this morning, we think that the best course of action/response is the following:

1) Provide list of existing settings ( @GilmoreA6  to provide in separate comment)
2) Ask what they would like to change/update?
3) Let them know that there is no restrictions (or list) of options available, we should be able to handle most (if not all) requests.
4) Ask if they are interested in receiving conditions beyond COVID-19, such as Flu, RSV, and HIV? If so, we'd like to set up a meeting with them to upgrade their connection to receive more conditions.

What do you think?

cc: @MikaelahD13 for awareness

**Comment by GilmoreA6** [comment]
current IL settings:

Messages are sent to IL if the following conditions are met :

Ordering facility OR Patient State = "IL"
Test Result Status = "F,C or P" (test results are final, corrected or preliminary)
Test performed is for SARS-CoV-2 (exists on CDC LIVD table)
Test type is "Antigen" (as defined by CDC enhanced LIVD table - see ticket#13937 for example) and Abnormal Flag = "A" (test result is detected or positive)

OR


Ordering facility OR Patient State = "IL"
Test Result Status = "F,C or P" (test results are final, corrected or preliminary)
Test performed is for SARS-CoV-2 (exists on CDC LIVD table)
Test type is "Molecular or Breath" (as defined by CDC enhanced LIVD table - see ticket#13937 for example) 

In addition the following quality filters are enforced:

At least one of the following fields must have data: test order date ( ORC-15-1), specimen collection date (SPM-17-1), test result date (OBX-14-1)
AND
At least one of the following fields must contain data: patient street (PID-11-1), patient zip(PID-11-5), patient phone (PID-13-7), patient email (PID-13-4)
AND
The following fields must contain valid data: message id (MSH-10), equipment model name (OBX-17-1), specimen type (SPM-4), test result (OBX-5), patient last name (PID-5-1), patient first name (PID-5-2), patient DOB (PID-7-1), ordering provider id (OBR-16-1)
AND
Must have a valid CLIA number for reporting facility (must be 10 characters)

**Comment by TaneaY** [comment]
Followed up with user they also so had additional questions so I offered a meeting and cc'd @GlennRGrieves @GilmoreA6 @chris-kuryak 

Thank you! I had some additional questions I was hoping you might be able to assist with:

 

Is it possible to have different filters for submissions entered into Simple Report vs. direct connections to Report Stream?
Are options for filtering still limited to test type and result? i.e. positives, negatives, or both from molecular COVID-19 tests, COVID-19 antigen tests or both are options but further refinement like we want positives from this specific test type/LOINC but not from another are not possible?
If/when additional conditions become available in Simple Report or Report Stream, how will we be informed? Will we start getting other conditions automatically? Will we be asked what kinds of filters we want or are we expected to reach out? I was not aware other conditions like mPox were available now.
Are there any limitations to what type of facilities can use either tool? i.e. a long term care facility doing point of care testing for COVID-19 vs. a lab doing more complex testing?
Are there any limitations to the types of tests that can be reported using either tool? i.e. rapid tests that can be performed by facilities operating under a CLIA waiver vs. higher complexity tests?

Hi Charlotte,

Thank you for you patience.

Engineering has confirmed the following as current settings:

current IL settings:

Messages are sent to IL if the following conditions are met :

Ordering Facility State OR Patient State = "IL"
Test Result Status = "F,C or P" (test results are final, corrected or preliminary)
Test Performed is for SARS-CoV-2 (exists on CDC LIVD table)
Test Type is "Antigen" (as defined by CDC enhanced LIVD table - see ticket#13937 for example) and Abnormal Flag = "A" (test result is detected or positive)

OR

Ordering Facility State OR Patient State = "IL"
Test Result Status = "F,C or P" (test results are final, corrected or preliminary)
Test Performed is for SARS-CoV-2 (exists on CDC LIVD table)
Test Type is "Molecular or Breath" (as defined by CDC enhanced LIVD table - see ticket#13937 for example)

In addition the following quality filters are enforced:

At least one of the following fields must have data: test order date ( ORC-15-1), specimen collection date (SPM-17-1), test result date (OBX-14-1)
AND
At least one of the following fields must contain data: patient street (PID-11-1), patient zip(PID-11-5), patient phone (PID-13-7), patient email (PID-13-4)
AND
The following fields must contain valid data: message id (MSH-10), equipment model name (OBX-17-1), specimen type (SPM-4), test result (OBX-5), patient last name (PID-5-1), patient first name (PID-5-2), patient DOB (PID-7-1), ordering provider id (OBR-16-1)
AND
Must have a valid CLIA number for reporting facility (must be 10 characters)



We would also like to set up a meeting to discuss further needs or reportable conditions with your ReportStream connection.



I have included the account manager and engineer assigned to your ticket for assistance.

**Comment by TaneaY** [comment]
@MikaelahD13 requested update- Awaiting user response- follow-up sent for meeting times 5/20 and 5/15. @GlennRGrieves @chris-kuryak @GilmoreA6 are cc'd on email thread.

**Comment by rnz6** [comment]
User responded: 

Hi,
This week I think the only time that the IDPH team might be available is 5/23 11 am-12 pm CST. Otherwise, we could consider the following (all Central time):
5/28 2-4 pm
5/29 9-11 am, 2-4 pm,
5/30 10:30 am – 12 pm, 1-2 pm
 
Would any of these work?

**Comment by chris-kuryak** [comment]
Since this meeting occurred last week, can we close this ticket @TaneaY ? Or were there any outstanding items?

**Comment by TaneaY** [comment]
@chris-kuryak I believe the settings changes have not been made or discussed from what Glenn posted on slack on May 30 "glenngrieves 9:58 AM
Good Morning. Please find the agenda and nots doc for our call with Illinois here. Please note, they asked some questions that we'll want to answer at the top of the call (these are included in the agenda). They did not answer the settings questions - so we'll need to confirm."

Please advise.

**Comment by chris-kuryak** [comment]
@TaneaY I just checked the meeting notes from the IL call last week:
https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/doc.aspx?sourcedoc=%7B2444ec8a-9350-4abb-901f-630f8c2a35a1%7D&action=edit

I believe we got to answer all of their questions in that meeting as I see them on the agenda with notes taken underneath.

Additionally, we are now actively engaged in weekly technical syncs with Illinois as we migrate them to the Universal Pipeline and will be confirming/changing any settings they want. Therefore, any changes they want beyond their questions should be answered in those meetings.

So you can just follow-up via email confirming that they received answers to their questions in the meeting last week, and that any followup questions/concerns should be brought up directly to their ReportStream onboarding engineer (Ott Sathngam) and account manager (Glenn Grieves) either via email or in the technical syncs. This can help ensure we are consolidating all requests/questions into their existing onboarding forum (weekly technical syncs).

What do you think? Perhaps I am missing something or there is a better tactic to take here?

**Comment by TaneaY** [comment]
Will close with above message sent to user. @chris-kuryak we can reopen if requested by user but meeting follow up should be sufficient Thank you.
