### ISSUE TITLE
Validate Route Steps Properly Update DB When Report Should Not Get Routed

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#14349]
### User Story
As an RS developer,
I want to ensure the route steps produce the correct output when deciding that the report should not make it to the next step,
so that the "lineage tracking model" works as expected

### Description/Use Case
When a Universal Pipeline step completes, it should always generate a new `report_file`, `report_lineage`, and `item_lineage` to indicate the report and its items were fully processed and no next action is set to take place.

This ticket is to ensure the two FHIR Routing functions are asserting that this is the case when a report should not make it to the next step.

### Dev Notes
Looking at FHIRDestinationFilterIntegrationTests specifically, it seems we have a test that validates what should happen when a report should not go to any receiver, but we do not appear to be doing any validation on report_file, report_lineage, or item_lineage here. The helper function, [fetchChildReports](https://github.com/CDCgov/prime-reportstream/blob/23f76e277d581db0dbe2cbbbad5b80e511db5c66/prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt#L247) seems to do this work but is not invoked in  the test `should respect jurisdictional filter and not send message`

### Acceptance Criteria
- [ ] verify the FHIR destinationFilter step generates a report with report and item lineage with next action set to none and that the integration tests test this
- [ ] verify the FHIR receiverFilter step generates a report with report and item lineage with next action set to none and that the integration tests test this

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14349?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14349?planning-poker) with Zenhub @JFisk42

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14349?planning-poker) with Zenhub @david-navapbc

**Comment by david-navapbc** [comment]
> This way we always ensure the lineage graph is complete. We also think this is already done for these two steps, this ticket just needs to verify before closing.

I have investigated and I believe this is already done for these two steps. See below the steps I used to verify: 

1. <img width="1530" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUF0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4482d55d862172b985ed6714f0e8aab2b2019377/Screenshot%202024-08-03%20at%206.52.43%E2%80%AFPM.png" alt="Screenshot 2024-08-03 at 6.52.43 PM.png" />

I sent a blank HL7 message into the app and received the reply shown including the `reportId`  

2. <img width="1374" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUV0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--313a2a40c27250b4fe4aa38d02390a1705bdf21e/Screenshot%202024-08-03%20at%206.53.35%E2%80%AFPM.png" alt="Screenshot 2024-08-03 at 6.53.35 PM.png" />

This is what the action table looked like after the http call. Actions are recorded through the destination filter as per the chart. 

3. <img width="1370" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUl0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe9ae6b26ef0019d6e4571a4ba840bd8d48c2d2d/Screenshot%202024-08-03%20at%206.54.00%E2%80%AFPM.png" alt="Screenshot 2024-08-03 at 6.54.00 PM.png" />
 
This is the item_lineage table post http call. You can see that the report has been transformed and on the far right you can see the item_hash information. 

4. <img width="1389" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU10Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c69d424f6af6bdb256515829836483469e245e5f/Screenshot%202024-08-03%20at%206.57.00%E2%80%AFPM.png" alt="Screenshot 2024-08-03 at 6.57.00 PM.png" />

report_file table 

5. <img width="1371" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVF0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f12fa4e420947a8a98b5df5413af87eb1baaa3ad/Screenshot%202024-08-03%20at%206.57.51%E2%80%AFPM.png" alt="Screenshot 2024-08-03 at 6.57.51 PM.png" />

**Comment by david-navapbc** [comment]
> This way we always ensure the lineage graph is complete. We also think this is already done for these two steps, this ticket just needs to verify before closing.

I have investigated and I believe this is already done for these two steps. See below the steps I used to verify: 

1. <img width="1530" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUF0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4482d55d862172b985ed6714f0e8aab2b2019377/Screenshot%202024-08-03%20at%206.52.43%E2%80%AFPM.png" alt="Screenshot 2024-08-03 at 6.52.43 PM.png" />

I sent a blank HL7 message into the app and received the reply shown including the `reportId`  

2. <img width="1374" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUV0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--313a2a40c27250b4fe4aa38d02390a1705bdf21e/Screenshot%202024-08-03%20at%206.53.35%E2%80%AFPM.png" alt="Screenshot 2024-08-03 at 6.53.35 PM.png" />

This is what the action table looked like after the http call. Actions are recorded through the destination filter as per the chart. 

3. <img width="1370" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUl0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe9ae6b26ef0019d6e4571a4ba840bd8d48c2d2d/Screenshot%202024-08-03%20at%206.54.00%E2%80%AFPM.png" alt="Screenshot 2024-08-03 at 6.54.00 PM.png" />
 
This is the item_lineage table post http call. You can see that the report has been transformed and on the far right you can see the item_hash information. 

4. <img width="1389" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU10Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c69d424f6af6bdb256515829836483469e245e5f/Screenshot%202024-08-03%20at%206.57.00%E2%80%AFPM.png" alt="Screenshot 2024-08-03 at 6.57.00 PM.png" />

report_file table 

5. <img width="1371" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVF0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f12fa4e420947a8a98b5df5413af87eb1baaa3ad/Screenshot%202024-08-03%20at%206.57.51%E2%80%AFPM.png" alt="Screenshot 2024-08-03 at 6.57.51 PM.png" />

**Comment by david-navapbc** [comment]
https://nava.slack.com/archives/C026DV8R21W/p1722876672335539

slack thread re: this ticket and ACs

**Comment by david-navapbc** [comment]
re: the slack convo above

1. I do not see the item lineage being tested in either the destination-filter tests or the receiver-filter tests. 
2. I noodled with some different ways of testing this and I landed on using the UniversalPipelineTestUtils method for verifying lineage. I successfully refactored one of the tests along these lines. I'll do the same for FHirReceiverFilterIntegrationTests tomorrow

**Comment by david-navapbc** [comment]
put up a draft PR for @arnejduranovic  et al to take a look at. There's an existing test utility method to check lineage so I've refactored some of the IT tests to additionally call that method. Assuming the team is good with this approach I'll implement the changes in all the places and remove the draft label.
