### ISSUE TITLE
Covid Result Metadata Table Improvements

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1436]
Now that the `covid_result_metadata` table is live in production, there are a few improvements we can make:

- Change patient age to be a numeric type
- Add field for `resident_congregate_care`
- Add field for upcoming `site_of_care` field. h/t @nickscialli-usds 
- Saving all of the report information exceeds our timeout. It would be better to return an Action ID, and then kick off a process that does not hold up the web response, but expose an API end point that lets us get information about an action: `api/action/{action id}`with the results. The workflow would then look like asking ReportStream to refresh the `covid_result_metadata` table with all information. The workflow creates an Action of a new type called `metadata`. The background process would then run through the reports, refresh them, and update the record in the DB table `action` with the results. The original invoker could periodically poll the new endpoint which would eventually show that the action is completed and the data is refreshed.
- Create a simple API endpoint that pulls the COVID Result Metadata for a report ID and returns it as a JSON object. This doesn't need to be anything special or fancy. Invoke GET on `api/report/{report id}/results` which would return all the rows for that report ID 
- Build some tests:
  - A test should run that submits a file to Docker and then invokes the above API for the report ID and verifies the data matches
  - A test should be run that reprocesses the same file again, and verifies that the old data was deleted and then successfully reinserted. There's two parts to this test: save the data from the original insert so you have the `created_dt` and the primary key. Then reprocess the same file, and pulls the data for the file. The data should exist, the row count should be the same, but the primary keys and the created dates should be updated. This should also use the above API endpoint
  - Once the above issue with submitting a "refresh ALL" request is done, a test should be created to get the Action ID and poll the action API until it lists as completed, and then verify that the results have been written by invoking the API for each report ID and checking the results.

fysa: @jlusds

**Comment by jlusds** [comment]
Will we work on this in sprint 22?

**Comment by anshulkumar-usds** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/1436?planning-poker) with ZenHub @MauriceReeves-usds @Adrian-Brewster

**Comment by Adrian-Brewster** [comment]
Research required to see if this is still valid or if we want to address other necessary improvements.

**Comment by Adrian-Brewster** [comment]
@MauriceReeves-usds is this still needed?

**Comment by Adrian-Brewster** [comment]
Closing. Mo will recreate with different requirements.
