### ISSUE TITLE
History/Lineage: Add JSONB to the Action Table

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1437]
Currently we're writing both regular string messages and JSON to the `action_result` column in `action`. Unfortunately that field is capped at 2048, and because it's varchar, we lose all the ability to query and index the JSON that is generated by our application.

To that end, I would like us to add a JSONB field to `action` called `action_result_json` which will contain any JSON results from actions that are taken. We don't need to backfill this with older data, and the field will accept NULL for any action.

The biggest benefit here would be longer validation messages, like the ones @tlosbo is creating can be preserved in whole without being truncated.

Leave the old action_result column there, but the code should stop using it.   I don't think there's any code that currently uses action_result (its meant for human debugging), so no further work is needed.

**Comment by jimduff-usds** [comment]
Propose calling this new column `action_response`
Leave the old `action_result` but stop using it.  Remove it on some blissful future day.
