### ISSUE TITLE
Create E2E tests for the Receiver Status Dashboard page

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14394]
## Problem statement
The MessageID Search page on the RS website needs End-to-end (E2E) tests created to ensure that it works properly before merging into master. Without E2E tests, some features/links may not function/load properly and we wouldn't know until a user tried to use them.

## What you need to know
- This is based off the investigation from #11307
- [e2e_Tests_audit.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXpvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c03fb9873a44dddb123ed3acdc6c8eaef0cd9a2d/e2e_Tests_audit.xlsx) has notes pointing out specific concerns/targets on some pages
- Strategy discussed for checking content load: check to see if every DIV on this page loaded
- The page is located at: https://reportstream.cdc.gov/admin/send-dash
- Will need to create and test against mock data

## Acceptance Criteria
As a user logged in as a Prime-Admin, check that:
- [ ] The page loads
- [ ] If there is an error, the error is shown on the page
- [ ] Page content loads without errors (including if the footer is showing, but not its functionality) (also, not checking the content itself, but just if it loads)
- [ ] Components work as expected (eg, accordion expands/collapses, side nav, etc)
- [ ] All filters work appropriately
- [ ] % success number is accurate

As any user, not logged in, check that:
- [ ] The page does not load
- [ ] The user is asked to log in

As any user **other than Prime-Admin**, logged in, check that:
- [ ] The page does not load or indicates that they do not have access to that page

**Comment by jpandersen87** [comment]
There seems to be a major bug with the old data-fetching library being used, that is corrupting data. Until we finish the hook transition (See #8370) , proper testing of this page is blocked.

**Comment by chris-kuryak** [comment]
Should be up for review soon after Base POM blocker is closed.
