### ISSUE TITLE
BUG: Change source for counting results

### ISSUE THREAD

**Issue by jsutantio** [CDCgov/prime-reportstream#14398]
**User Story**
As a product manager and ReportStream team member, I would like my dashboard's data source to be the most accurate and reliable so that the resultant calculations and dashboards are less prone to error.

**Description**
Due to results quantity being based on the mapped condition codes, the tally for results are not representative of the data the product team would like to portray. 
[Options for remediation](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1698943074617/6127d0c639d7365236c1ef3ff06cb2dc4a4ab467?wid=0-1715024737263)
The direction for moving forward is to base counts on the quantity of tests that were performed rather than the mapped condition codes. In addition, to increase automated maintainability of the dashboard, the support of manual mapping of the condition shorthands (for both test performed and condition codes) will be discontinued).

**Acceptance Criteria**
- [x] Tally result counts based on observation instances that point to a single test performed LOINC (more than one observation may be contained within an observation field)
- [ ] Remove ability to filter by condition on the

**Comment by Andrey-Glazkv** [comment]
@adegolier FYI2
