### ISSUE TITLE
Delivered filename for a FHIR receiver is wrong

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#14455]
### User Story
As a FHIR receiver, I would like the filename to look like `{reportId}-{datetime}.fhir`.  

### Description/Use Case
Currently, the format is `-{reportId}-{datetime}.fhir`

### Dev Notes

To recreate:
1. Send a report that will go to a FHIR SFTP receiver
2. Look at file in build/sftp

Expect the filename to be: `{reportId}-{datetime}.fhir`
In reality: `-{reportId}-{datetime}.fhir`

### Acceptance Criteria
- [ ] Filename for a delivered FHIR report is updated

**Comment by Andrey-Glazkv** [comment]
@JFisk42 whenever you are ready
