### ISSUE TITLE
Integrate New Route Azure Functions

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#14450]
### User Story

As ReportStream,
the route step shall be split up into two separate steps per the [SRD](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engineering/Design/SRD/SRD-Routing.docx?d=w3a2fa783e8dc4e9b8397da9f5d968dfa&csf=1&web=1&e=9wJcJi)

### Description/Use Case

- The Route function shall be replaced by the [Destination Filter Function](https://github.com/CDCgov/prime-reportstream/issues/13691) and [Implement Receiver Filter Function](https://github.com/CDCgov/prime-reportstream/issues/13692) to achieve the benefits outlined in the [SRD](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engineering/Design/SRD/SRD-Routing.docx?d=w3a2fa783e8dc4e9b8397da9f5d968dfa&csf=1&web=1&e=9wJcJi)
- By the time this ticket is picked up, both new functions shall be implemented but not integrated into the application (the convert step shall still call the old Route function. To complete this ticket, we must perform the following operations in order:

  1. update the convert step to route to the destination filter function instead of route function
  2. deploy to staging and master
  3. verify there are no queue messages for the route step in staging and master
  4. update the pipeline to delete the Route step code
  5. deploy to staging and master

### Risks/Impacts/Considerations

We will need to verify there are no tools, queries, etc. depending on the current Route step existing. Lineage tracking should just work, but there may be other things that may depend on this step, like any queries the engagement team is using that directly query the Route step.
- Look through Metabase queries in both staging and prod 
- Review findings with Engagement team 
- look through queries in repo

If there are existing functionalities depending on the Route step, they should be updated as part of this ticket.

### Acceptance Criteria

- [ ] Route function replaced with the new functions and marked for removal
- [ ] Staging and Prod environments working with new functions
- [ ] Any queries or dependencies on the Route step have been updated
- [ ] Route Step documentation updated or follow-up ticket created
- [ ] ReportRouteEvent.originalObservations is covered in unit and/or integration tests
- [ ] ReportRouteEvent.receiver is no longer nullable (moved to cleanup ticket)

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14450?planning-poker) with Zenhub @jalbinson

**Comment by Andrey-Glazkv** [comment]
@thetaurean :-)
