### ISSUE TITLE
Create Plan for ReportStream Load Testing

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#14451]
### User Story

As a ReportStream Engineer (and stakeholder),
I want to have proof that the Universal Pipeline, and ReportStream in general, can perform under pandemic loads,
so that ReportStream meets its requirements of being pandemic ready and can pass potential future audits.

### Description/Use Case

Microsoft has extensive [documentation on Load testing in Azure](https://learn.microsoft.com/en-us/azure/load-testing/). First step should be to go through these docs to get an idea of how we can leverage **automated Azure load testing tools**  to achieve our goal of proving RS can handle pandemic loads. Our tests should:
-  be automatically triggered with no user intervention
-  be easily run on a schedule (like every release or sprint)
-  generate a report that includes data we have deemed important to capture to conclude whether RS in pandemic ready

This design should also include:
- the data and metrics the load tests will capture. Some Ideas:
    - latency
    - response time per function over time under load
    - messages in poison queue
    - number of exceptions
    - time-to-deliver
- Any additional logging or Azure Events that will be needed
- Success metrics. How do we determine pass/fail?

> NOTE: Using Azure load testing tools is not a requirement, but since we already have many Azure integrations the assumption is integration should be faster than other alternatives and would be less to manage. Feel free to investigate other alternatives if Azure load testing tools do not seem appropriate for our use case.

### Acceptance Criteria

- [ ] Automated Load Testing Design Created and Reviewed by:
    - [ ] Platform Engineers
    - [ ] Engagement Engineers
    - [ ] Product Team
- [ ] tickets and epic (if needed) created and groomed to implement the design

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14451?planning-poker) with Zenhub @adegolier

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14451?planning-poker) with Zenhub @jalbinson
