### ISSUE TITLE
Setting Up Montana for Onboarding

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1447]
As part of our work to onboard states, we are ready to onboard Montana. In order to start this process, we will need to send them our public IP for the ReportStream application, and we will need to generate a public/private key pair that we will use to log in to their SFTP server.

There are steps in the documentation folder about how to generate and handle the public/private key pair here: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/how-to-create-and-manage-receiver-ppks.md

These steps do require someone to have access to Azure, which also means they have been granted an account with the CDC.

Acceptance criteria:
- A public/private key pair has been created for MT
- The public key is sent to MT
- The credentials are stored in Azure for MT
- The connection info for the MT server is updated in the organization file for prod
- The connection info for the MT server is persisted to the Setting table in production
- A successful connection test was completed

fysa: @sparkle-usds @jlusds

**Comment by jlusds** [comment]
Sent a final file as of 7/19
