### ISSUE TITLE
Adding reportstream-sftp-ingestion to sonar cloud

### ISSUE THREAD

**Issue by rajeev-flexion** [CDCgov/prime-reportstream#14496]
A new project needs to be created in sonarCloud, the associated github directory is reportstream-sftp-ingestion

**Comment by snesm** [comment]
Project [overview](https://sonarcloud.io/project/overview?id=CDCgov_reportstream-sftp-ingestion) and [summary](https://sonarcloud.io/summary/overall?id=CDCgov_reportstream-sftp-ingestion) pages.
