### ISSUE TITLE
[SPIKE] How to handle programmatic link checking

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14499]
## Problem statement
We have created a programmatic way to check all links on the ReportStream website #14004, but we have not determined how to monitor, resolve, and trigger blockers when it finds broken links.

## What you need to know

- #14004

## Proposed solution aligned by FE Engr
Experience discussed this async via Slack and conclude that this is how we should handle console.warn within this programmatic link checking end-to-end test (and maybe other warn-based tests as well):

1. go through the e2e test
2. when there's a non 200 response from a link, console.warn within the e2e test
3. within the playwright test, create a file called test-warnings.log and output all the warnings there
4. alternative implementation: write the warnings to an envar, and then read it later ie: process.env.PLAYWRIGHT_WARNINGS = warnings.join("\n");
5. once the e2e test is complete, we have a github action that reads the .log file (or envar), and creates a PR comment with the broken link clearly visible

## Acceptance criteria

- [x] Meet with rest of FE team and Tech Lead to determine:
  - [x] What should trigger an error vs a warning
  - [x] How the errors and warnings will be monitored (and who is responsible)
  - [x] What needs to be fixed, by whom, on what timeline
- [x] Document the resolution in this ticket
- [x] Create follow-on ticket (if necessary) to implement solution

**Comment by chris-kuryak** [comment]
Victor: Internal Links throw an error, external links throw a warning

Penny and Joseph agree.

**Comment by chris-kuryak** [comment]
This program is run with every pull request.

Victor: Is there any existing documentation?
Joseph: Teams other than FE likely will not trigger an error on internal links.

**If error occurs:**
- Person merging is responsible for fixing. If cannot fix, pair with FE on-call person to fix.

**If warning occurs:**
- Person merging is responsible for notifying the FE team that a warning exists. FE team will take ownership to fix. Proceed as usual.

**Comment by chris-kuryak** [comment]
Chris to align with Etan when he is back

**Comment by chris-kuryak** [comment]
Meeting Wed 6/5 to finish the discussion

**Comment by etanb** [comment]
Ok @chris-kuryak @pstonebu @victor-chaparro 

Experience discussed this async via Slack and conclude that this is how we should handle `console.warn` within this programmatic link checking end-to-end test (and maybe other warn-based tests as well):

1. go through the e2e test
2. when there's a non 200 response from a link, console.warn within the e2e test
3. within the playwright test, create a file called `test-warnings.log` and output all the warnings there
4. alternative implementation: write the warnings to an envar, and then read it later ie: `process.env.PLAYWRIGHT_WARNINGS = warnings.join("\n");`
5. once the e2e test is complete, we have a github action that reads the .log file (or envar), and creates a PR comment with the broken link clearly visible

**Comment by etanb** [comment]
This solution both makes the link-checking non-blocking but also VERY obvious when something is broken. I don't think we should differentiate between internal vs. external links, as our e2e tests will catch anything truly broken with our actual pages, and shipping any piece of website with broken links, regardless of internal or external, it needs to be fixed.

**Comment by pstonebu** [comment]
I like this approach, prevents broken links from holding up a release, but still makes them actionable
