### ISSUE TITLE
Figure out 2nd wave of OTC outreach to states

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-reportstream#1450]
To date, we've reached out to the 3 states, we want to reach out to the rest

-Figure out outreach plan
- [ ] Which states
- [ ] Email content
- [ ] 1 pager (https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/1249)
-Figure out eng to make updates

For email content, we want to write an announcement email to let them know they can now further personalize their feed, per the settings in this doc (https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/1249). Success for the email is that 1) The PHD understand the feature, 2) they respond with a simple selection/phrase that makes it easy for to document their needs (while avoiding another meeting)

**Comment by BerniXiongA6** [comment]
@jlusds I'm starting to work on this outreach email template now. Do you have any previous emails you've sent out that I could extract content from to repurpose and adapt as a starting point for this new outreach email?

**Comment by jlusds** [comment]
Sent 2 via email, 1 via slack!

**Comment by BerniXiongA6** [comment]
@jlusds Here's an email template I created for "OTC Test Results" using the email to CO you forwarded me. I followed the RS content style guide as I edited this. Let me know what other assistance you need with email comms.

[https://app.zenhub.com/files/304423150/4c3696fe-1678-474f-83cb-d4662a93446d/download](https://app.zenhub.com/files/304423150/4c3696fe-1678-474f-83cb-d4662a93446d/download)

**Comment by BerniXiongA6** [comment]
@jlusds Here's a revision of the email template for "ReportStream Daily Email" indicating COVID-19 test data is ready for download. A few minor revisions only, please see comments inserted in the document attached. Any questions, lmk, thanks!

[https://app.zenhub.com/files/304423150/bb083dd8-cf19-448f-9bb5-d71af5064c08/download](https://app.zenhub.com/files/304423150/bb083dd8-cf19-448f-9bb5-d71af5064c08/download)

**Comment by jlusds** [comment]
Hi @BerniXiongA6 i think there was a bit of mixup

1) Updating content for the automated daily email, that is actually [this task ](https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/948). The content you developed is still relevant, so I responded on that thread

2) I'll clarify the email ask for this topic

**Comment by jlusds** [comment]
Pivoted to a combined outreach for combining the announcement of the new file naming convention + launching OTC

**Comment by jlusds** [comment]
Updated project spec: https://cdc-my.sharepoint.com/:w:/g/personal/qpu0_cdc_gov/EYhZMJZb6TROnyvgMKNY1tIB2B6SYvHkUok2lyHoa_6CTQ?e=fdq9Hh

**Comment by Adrian-Brewster** [comment]
We can close this ticket
