### ISSUE TITLE
Identify Texas HIV Pilot next steps and complete prep tasks

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14503]
## Problem statement
After meeting with Texas and not being able to discuss our offer of helping with HIV health equity, we need to identify next steps. Additionally, we have been asked to follow up with Kristie Clark and CSL Plasma, which are low lifts that should happen soon.

## What you need to know

- CSL Plasma is a sender that was identified by Texas asa priority sender as part of their HIV onboarding, and Mo has asked that we reach out to CSL to start a conversation about onboarding potentially all of their locations. This will likely start as being added to an upcoming CSL call let by RS/SR.
- Kristie Clark as asked for some followup work per the well-accepted presentation. See Jillian for details.
- Since we have not talked to Texas about our proposal to help with HIV health equity, we need to determine next steps
- ...

## Acceptance criteria

Texas HIV Pilot
- [x] Next steps for the Texas HIV pilot are defined and aligned with Account Manager (Glenn)
- [x] Followup call with Texas is scheduled or email sent, depending on the strategy aligned through Glenn

Kristie Clark followup work completed:
- [ ] Prepare for (& conduct, if applicable) meeting with domestic HIV (background research on their work + existing surveillance system(s))
- [ ] Prepare for (& conduct, if applicable) meeting with Thane + Kevin (coordinate prep with Chris, Glenn + schedule meeting)

CSL Plasma:
- [x] Research regarding CSL Plasma, their locations, the tests they perform, and if they would be a good fit for SR or RS is documented
- [x] Questions/ideas for what to include in the next conversation with CSL Plasma are defined and aligned with Account Manager
- [x] Plan for asking questions in CSL Plasma meeting is aligned with Simple Report and included on agenda (if time allows)

**Comment by jakefishbein-navapbc** [comment]
Glenn and I met on 5/22/2024 to discuss Texas follow-up. Based on that conversation, I have added next steps to the [health equity initiative document](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BE17F23C4-8348-4FBD-B4D8-DC099DF609BD%7D&file=ReportStream%20Health%20Equity%20Initiative.docx&action=default&mobileredirect=true).

**Comment by jakefishbein-navapbc** [comment]
[Here is the initial background research on CSL Plasma.](https://docs.google.com/document/d/1TUSNChLANORKUScFso301Vad8ImngIz6VCDKbpSV9C0/edit?usp=sharing)

**Comment by jakefishbein-navapbc** [comment]
I reached out to Kevin and Thane regarding the territories on 5/24. I have not heard back. 

Regarding domestic HIV, Kristie provided this information: Excellent- Best page for more on the domestic HIV group here: [Homepage | Division of HIV Prevention (DHP) (cdc.gov)](https://intranet.cdc.gov/nchhstp/dhp/). Specifically, my friend who works there put me in touch with the branch chief for HIV surveillance, Angela Hernandez, who is out of office.  It is a massive group with a lot of functions that span from data to research to prevention programs. Org chart here: [PowerPoint Presentation (cdc.gov)](https://www.cdc.gov/hiv/pdf/division-of-hiv-prevention/cdc-hiv-dhp-org-chart.pdf)

**Comment by jakefishbein-navapbc** [comment]
I received a response from Kevin and Thane. Will sync with @GlennRGrieves @chris-kuryak @jillian-hammer today to see about next steps.

**Comment by jakefishbein-navapbc** [comment]
Follow-up ticket created for territories connection
