### ISSUE TITLE
Update NY Certification

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14517]
## What you need to know
- NY (Entrust) contacted us telling us that our certification will expire May 31
- This needs to be fixed in order to continue sending production data to NY
- Guide created by Brick: https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BEF1E6955-D548-423C-857A-EF2F3C793FCD%7D&file=New%20York%20Certificate%20Update%20(1).docx&action=default&mobileredirect=true
- 

## Acceptance criteria
- [x] Certificate updated
- [x] NY connection able to receive results past May 31
- [x] Documentation updated, if necessary
- [x] Any other issues documented and reported to @victor-chaparro

**Comment by chris-kuryak** [comment]
Waiting on confirmation from Tim Best and CDC that they have received the notification from NY and that they take action on it.

**Comment by chris-kuryak** [comment]
Waiting on Tim to take action on setting up the account for RS to take ownership and action.

**Comment by GilmoreA6** [comment]
Account created in NYS HCS. ServerCertificate.crt sent to certman@health.ny.gov

**Comment by GilmoreA6** [comment]
Certificate uploaded to NY. Settings updated 7/15/24 10:00 AM PST. All reports sent to NY between 6/1/24 and 7/15/24 10:00 AM PST need to be resent.
