### ISSUE TITLE
CSP Header Issues

### ISSUE THREAD

**Issue by etanb** [CDCgov/prime-reportstream#14518]
## Describe the bug
We're still having CSP header problems. This could be both on an app level (within our FE codebase) or an Azure level. Or both.

## Impact on ReportStream
Errors thrown in production, scripts not loading properly.
Not properly tracking our website analytics.

## Steps to reproduce
1. Go to https://reportstream.cdc.gov/
2. Open dev console
3. Scream

<img width="1270" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3NKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22a162951e664f79d64600450d03e8fafeeb8faa/Screenshot%202024-05-23%20at%2010.26.35%20AM.png" alt="Screenshot 2024-05-23 at 10.26.35 AM.png" />

Suggestions from Joseph:
- Update the CSP headers to allow Azure App Insights weird URL js.monitor.azure. . . . (make a ticket for devops)
- Seems like Google Analytics is misconfigured in its settings on which domains are allowed, or we need to look into GA4 documentation to make the scripts work

**Comment by penny-lischer** [comment]
Dev ops ticket [here](https://app.zenhub.com/workspaces/prime-devops-606cb208a8c112000fd48349/issues/gh/cdcgov/prime-devops/131)
