### ISSUE TITLE
Illinois Onboarding - Validate Test Data

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#14537]
### Acceptance Criteria 
- [x] Created and sent data using fake data generator 
- [x] Created and sent data using synthesized data generator 
- [ ] Confirmed with STLT that data passes validation 

### To Do 
- [x] RS engineer: update this ticket with comments with every interaction with receiver 
- [x] RS team member who originates this ticket: add any dependencies, as needed 
- [x] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Receiver" and state label 
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by chris-kuryak** [comment]
Waiting on response from IL

**Comment by chris-kuryak** [comment]
@GlennRGrieves Can we check in with IL on status of onboarding

**Comment by oslynn** [comment]
This is old COVID Validate Test Data.

**Comment by oslynn** [comment]
Sent message for IL to validate:
<img width="1603" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWNtQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e6782243d229309db57a719b0070be47f1fcfe6/image.png" alt="image.png" />

**Comment by oslynn** [comment]
Need to add integration test.

**Comment by oslynn** [comment]
Completed: 
<img width="1819" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkJNQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--172a3145a0b75b09ef5713129ba9be68be5c6f67/image.png" alt="image.png" />
