### ISSUE TITLE
FHIR Transform: Implement Resource "Prune" Feature

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#14548]
### User Story

As a writer of receiver-based FHIR enrichments,
I want the ability to REMOVE resources from a bundle that match a particular FHIR expression,
so that I can create a bundle that meets a receiver's Observation filtering requirements.

### Description/Use Case

Presently ReportStream's FHIR expressions allow for SELECTING resources and their properties in a FHIR bundle and setting their value. This ticket aims to now implement the ability to remove resources as well that match a particular "resource" expression. 

This ticket does not define the syntax that shall be used in the .yml file, but the following is an example of something that could work:

```
  - name: sr-specimen-collection-bodysite-display
    resource: 'Bundle.entry.resource.ofType(Specimen)'
    condition: '%resource.collection.bodySite.coding.display.exists().not()'
    value: [ '%remove' ]
```

The above config would remove all Specimen resources that did not have a `display` value for `collection.bodySite.coding`

### Dev Notes

- This solution should have a way to handle references that get broken when a resource is deleted. For example, in the picture below, if the highlighted Observation is removed from the bundle, the reference to it in the DiagnosticReport object should be as well.

![Screenshot 2024-07-16 at 10 19 37 AM](https://github.com/user-attachments/assets/84ca3b2b-8fb5-4f56-80f0-9d53300dca54)

### Acceptance Criteria

- [ ] Ability to prune resources added to ReportStream FHIR transforms

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14548?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
