### ISSUE TITLE
fhirpath utils incorrect catching and throwing errors

### ISSUE THREAD

**Issue by JFisk42** [CDCgov/prime-reportstream#14540]
## Describe the bug
While poking around with the fhirpath prime util I noticed that we weren't catching the specific error for invalid fhirpath syntax. This method is used in more broad use cases as well and so can cause misleading/too generic logs when ReportStream hit invalid fhirpath syntax. (Method: `FhirPathUtils.kt#parsePath()`)

Also discovered was a similar fhirpath evaluation method which was being used and in one instance could have caused an uncaught exception. (Method: `FhirPathUtils.kt#evaluateCondition()` )

## Impact on ReportStream
- We don't usefully log invalid syntax when parsing fhirpath ([see here](https://github.com/CDCgov/prime-reportstream/blob/ded69d1808d92b60246d9d90275e6bbea5a27a6d/prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt#L82)). 
- Also discovered was a similar [fhirpath method](https://github.com/CDCgov/prime-reportstream/blob/ded69d1808d92b60246d9d90275e6bbea5a27a6d/prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt#L104) which throws an exception which isn't caught in [one of its uses](https://github.com/CDCgov/prime-reportstream/blob/ded69d1808d92b60246d9d90275e6bbea5a27a6d/prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt#L409).
- Neither of these seem to be common occurrences because of the process of setting up new RS consumers.

## Steps to reproduce
1. Run the prime fhirpath util `./prime fhirpath --input-file="src/test/resources/fhirengine/engine/bundle_multiple_observations.fhir"`
2. Run an invalid fhirpath, ex: `Bundle.entry.resource.ofType(Observation).where(component.where(code.coding.code = '94558-5').exists()`
3. Notice uncaught exception on command line. 

## Expected behavior
- Exceptions for invalid fhirpath syntax should be caught with useful logging before re-throwing the error.
- When these methods with re-thrown errors are invoked, the exceptions should be properly handled.

**Comment by JFisk42** [comment]
FhirPathUtils.evaluateString() does not have any exception handling for syntax errors coming from the fhirpath library. This method is only used in one spot during hl7 to fhir conversion and this handles some exceptions we raise, but invalid syntax would cause an unhandled exception. 

Also digging into this a little today and found that FhirPathUtils.evaluate() is only used in a few spots. FhirPathUtils.evaluateCondition() is used a bit more frequently and is what is used for our UP filtering. I haven't evaluated this method for any issues.

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14540?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
