### ISSUE TITLE
Resend dropped messages in the Covid Pipeline

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#14567]
## Problem statement

Some messages did not get routed to STLTs in the CP due to a missing mapping for specimen type. The specimen type has been added since April 17th. SimpleReport might keep messages for longer then 60 days so they may be able to resend all the messages that were dropped.

## What you need to know

This query return all dropped messages in the last 60 days that need to be resent:

```
select 
detail->>'filteredTrackingElement' as messageId, 
detail->>'receiverName' as receiverName,
al.created_at,
detail->>'message' as message,
m.sender_id
from action_log al 
join covid_result_metadata m on detail->>'filteredTrackingElement' = m.message_id
where type = 'filter' 
and detail->>'filterType' = 'QUALITY_FILTER'
and detail->>'filterName' <> 'allowNone'
and detail->>'receiverName' <> 'ca-dph.full-elr-saphirestage'
and detail->>'filterName' not like '%reversed%'
and detail->>'message' not like '%simple_report%'
and detail->>'receiverName' not like '%secondary%'
and detail->>'receiverName' not like '%test%'
and detail->>'receiverName' not like '%stage%'
and detail->>'receiverName' not like '%elr-neg%'
and detail->>'message'  like '%specimen_type%'
and al.created_at > now() - interval '60 day'
order by detail->>'receiverName' desc
```

## Acceptance criteria

- [ ] Check that all dropped messages are resent from SR

**Comment by chris-kuryak** [comment]
SR is going to be resending these messages

**Comment by chris-kuryak** [comment]
Look at messages that failed the quality filter the first time.
Can check those messages have all been successfully sent.

**Comment by GilmoreA6** [comment]
SR resent 428 messages (listed in): https://www.simplereport.gov/metabase/question/872-test-events-filtered-by-specimen-type.

These were resent on 06/24/24 in 20 batches between 10:50 ET and 10:55 ET

**Comment by chris-kuryak** [comment]
Thank you @GilmoreA6 !

**Comment by JessicaWNava** [comment]
Query for determining which message_ids were needing to be resent:
select 
distinct message_id
from action_log al 
join covid_result_metadata m on detail->>'filteredTrackingElement' = m.message_id
where type = 'filter' 
and detail->>'filterType' = 'QUALITY_FILTER'
and detail->>'filterName' <> 'allowNone'
and detail->>'receiverName' <> 'ca-dph.full-elr-saphirestage'
and detail->>'filterName' not like '%reversed%'
and detail->>'message' not like '%simple_report%'
and detail->>'receiverName' not like '%secondary%'
and detail->>'receiverName' not like '%test%'
and detail->>'receiverName' not like '%stage%'
and detail->>'receiverName' not like '%elr-neg%'
and detail->>'message'  like '%specimen_type%'
and al.created_at > '2023-12-24'
and al.created_at < '2024-04-17'
and sender_id = 'simple_report.default'

**Comment by JessicaWNava** [comment]
Query for messages that appear to be resent:
select * from report_file inner join item_lineage on item_lineage.child_report_id = report_file.report_id
where report_file.created_at > '2024-06-12 10:50'
and report_file.created_at < '2024-06-14'
and report_file.transport_result like 'Success%'
and tracking_id in (
select 
distinct message_id
from action_log al 
join covid_result_metadata m on detail->>'filteredTrackingElement' = m.message_id
where type = 'filter' 
and detail->>'filterType' = 'QUALITY_FILTER'
and detail->>'filterName' <> 'allowNone'
and detail->>'receiverName' <> 'ca-dph.full-elr-saphirestage'
and detail->>'filterName' not like '%reversed%'
and detail->>'message' not like '%simple_report%'
and detail->>'receiverName' not like '%secondary%'
and detail->>'receiverName' not like '%test%'
and detail->>'receiverName' not like '%stage%'
and detail->>'receiverName' not like '%elr-neg%'
and detail->>'message'  like '%specimen_type%'
and al.created_at > '2023-12-24'
and al.created_at < '2024-04-17'
and sender_id = 'simple_report.default'
)

**Comment by JessicaWNava** [comment]
Also going to add a note per Chris' request that says the query returns three messages and I am going to create a follow up ticket to track down what happened to those.

**Comment by chris-kuryak** [comment]
So it appears all but 3 messages were sent successfully. Since follow on ticket is created, we are good to close this one.

**Comment by GilmoreA6** [comment]
399 messages were resent and received in 3 reports from SR on 06/12/24 between 10:50 AM and 10:55AM:

Report ID: b3882e30-92fc-4014-a220-7a3f01c48f7b, Action ID: 25880516 contained 73 results with specimen source code 1293160008

Report ID: 4d242090-e1d2-4b3d-8f85-8dbeb0c65994, Action ID: 25880519 contained 167 reports with specimen source code 1293160008

Report ID: 73c16984-2b2e-4666-87be-c19cf0dcf86c, Action ID: 25880523 contained 159 reports with specimen source code 1293160008

All reports were received only in the COVID-19 pipeline and the discrepancy between the number of reports re-sent by SR and number of reports sent to STLTs is due to receivers that have been ported over to the UP since the issue occurred. These receivers will not receive the resent reports because they were sent only through the UP.
