### ISSUE TITLE
Update Integration Tests for FHIRTranslator

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#14574]
### User Story

As a developer of the Universal Pipeline,
I want to have integration tests that ensure `FHIRTranslator` updates the system state correctly and produces correct outputs,
so that I can confirm the pipeline step is working properly.

### Description/Use Case

There are some FHIRTranslator integration tests located in `FhirFunctionIntegrationTests.kt`. These should be split out into its own class, following the pattern established by `FHIRRouterIntegrationTests` and `FHIRConverterIntegrationTests`. There may be a lot of test harnessing that can be reused between the three, and this should be broken out into a shared location instead of being duplicated. 

The integration tests should use both the database and azure blob test containers and verify both are updated correctly given certain inputs to the function. The following should be verified:
- report lineage is correctly updated
- item lineage is correctly updated
- task table is correctly updated
- action and action_log table is correctly updated
- report_file table is correctly updated
- Azure Queue Message is correctly generated
- Azure Events are properly generated
- Passthrough functionality works correctly
- Translation functionality works correctly

### Acceptance Criteria

- [ ] Created one or more integration tests for the pipeline step that gives confidence the step is working as expected

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14574?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
