### ISSUE TITLE
Send messages from MMTC to USVI in Staging

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14575]
## Problem statement
To finish the pilot with RadX MARS and MMTC, we need to successfully send test messages to a receiver in staging.

## What you need to know
- Makemytestcount.org (MMTC) is connected to RS in staging

## Expected process
- ReportStream will route some test messages for this OTC data to receiver testing environment.
- ReportStream will contact receiver via email indicating when those messages have been sent and their Message IDs
- Receiver will check those messages and respond to ReportStream via email indicating if they have been successfully received and are capable of being processed.
  - If they are not, receiver will indicate what changes need to be made in order to successfully receive and process them
- Repeat above process until success 

## Acceptance criteria
- [x] Convert filtered multiplex results in RadX MARS results to notes per requirement (separate into separate ticket if necessary)
- [x] Receiver has indicated that they have successfully received and can process test results from MMTC
  - [x] Influenza positive result
  - [x] COVID positive result

**Comment by victor-chaparro** [comment]
Can we get access to MMTC test environment?

**Comment by chris-kuryak** [comment]
RSV removed
