### ISSUE TITLE
Update ConditionFilter Action Logging

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#14594]
### User Story

As a reader of ReportStream ConditionFilter Action Logs,
I want the logs to be accurate,
so that I can understand what happened

### Description/Use Case

Presently, if a condition Filter evaluates to true, it will log the following in the Action Log:

```
{
 "class": "gov.cdc.prime.router.PrunedObservationsLogMessage",
 "scope": "report",
 "message": "Observations were pruned from receivers for reportID 71873ccc-c65b-4c46-b496-44848f320bc8\n",
 "errorCode": "UNKNOWN"
}
```

This message indicates that observations were pruned when they were not necessarily. For example, if you set this filter to "True" it will pass, nothing will get pruned, but this message will still appear.

Proposed Solution: 

- Only show the above message when observations were actually pruned. Enhance the message to show how many observation were pruned and what those LOINC and/or condition codes were. Also, ensure the other columns of the Action Log are properly populated:
  - report_id
  - index
  - tracking_id

- When a conditionFilter passes but nothing is pruned, update the message to reflect that.
- When a conditionFilter Fails, ensure message indicates that is what happened and what conditions it failed to find.

### Acceptance Criteria

- [ ] Functionality updated per proposal in ticket (or alternative solution that was discussed)
- [ ] All relevant tests updated. New tests created if new test coverage is needed.

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14594?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Closed since its no longer applicable
