### ISSUE TITLE
Additional priviledge in sonar cloud project

### ISSUE THREAD

**Issue by rajeev-flexion** [CDCgov/prime-reportstream#14597]
Need to make few changes to sonar project of reportstream-sftp-ingestion. For the same we will need administrative privileges for this specific project.
Please add these 3 users. @halprin, @rajeev-flexion, and @somesylvie.

**Comment by snesm** [comment]
Both @halprin and @rajeev-flexion have SonarCloud accounts.

I do not have access to grant administrative privileges to any user, nor to change Administration settings on any project other than `prime-router`.

**Comment by rajeev-flexion** [comment]
Whom should i reach out to ?

**Comment by halprin** [comment]
@jeremy-page, I believe you are an admin of the CDC SonarCloud organization, correct?  Can you fulfill this ticket?  I just updated the ticket to include three users: @halprin, @rajeev-flexion, and @somesylvie.

**Comment by halprin** [comment]
This has been resolved.
