### ISSUE TITLE
Members of the DHPrimeAdmin group in Okta should have ALL organizations in the organization drop down available

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1459]
Currently the drop down on the static site for members of the DHPrimeAdmin group only shows the organizations the user is a member of. For those of us who are in the DHPrimeAdmin group, it should include *all* active organizations so we are able to see the web for every org without having to assign ourselves to many groups.

fysa: @jlusds @drew-usds @ahay-agile6 @Bisonburger @mry-usds

**Comment by jlusds** [comment]
To make this work, do we need to automatically add DHPrimeAdmin members to all active groups?
