### ISSUE TITLE
Allow Sender to Auto-Generate a De-Identified Data File

### ISSUE THREAD

**Issue by kjt9cc** [CDCgov/prime-reportstream#1460]
## Problem Statement

As the ReportStream support team, we would like to have a Sender easily auto-generate a de-identified data file based on the columns in their data file that need to be de-identified so that we don't have to take possession of a data file that contains PHI/PII.

## Things you need to know

- The CDC will not allow the ReportStream team to test files that contain PHI; files must be de-identified
- Proposed workflow 
    - MANUAL PROCESS
        - RS team gets a data file from a Sender that contains only column names (no data)
        - RS team generates a basic schema for the Sender with data type info & indication of PII columns (including designation of "isPII" for fields that are PII)
    - AUTOMATED PROCESS FOR WHICH WE NEED DEVELOPMENT 
       - Sender logs in to RS 
       - Sender uploads a data file that contains PHI/PII
       - System uses the Sender's schema to generate a de-identified data file 
           - **NOTE: there is a mechanism in the schema to denote fields that contain PHI/PII**
       - System sends the de-identified data file to a secure CDC server location
       - System does not retain the uploaded data file that contains PHI

## Acceptance Criteria

- Given I
    - Am logged into ReportStream as a user with Sender permissions
- When I
    - Navigate to the new Sender submission page
- Then I
   - Can generate a de-identified CSV file from a CSV data file that I upload that contains PHI/PII
   - Can download the de-identified CSV file
   - Can send the de-identified CSV file to the ReportStream team
   - **NOTE: the data file is NOT retrained**

**Comment by MauriceReeves-usds** [comment]
Hey @kjt9cc, help me understand the intent here. Who is the user of this? What's the use case?  Thanks

**Comment by kjt9cc** [comment]
@MauriceReeves-usds, this one is half-baked. From a conversation with Jim in ATL about what tools are needed to make the our lives easier.  "as a sender, i would like to log into a website to see an example of what a csv might look like with realistic data under the actual schema so that I can identify any problems quickly."
