### ISSUE TITLE
Update UP Convert Step to support new Secure Upload API 

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#14603]
### User Story

As a stakeholder of ReportStream,
I want the Convert service to handle the new Upload API alongside the "reports" and "waters" apis,
so that the new upload API can be used by new clients and the other clients are supported until they are migrated.

### Description/Use Case

Presently, ReportStream has two upload APIs that the Convert step is currently supporting:
- "reports API" - uses Azure Functions Key Auth
- "Waters API" - uses OAuth2.0 with homemade custom Authorization server embedded in the application

The convert step should be updated to support the new UP Upload API alongside the two above.

### Dev Notes

The implementation details of the Convert step changes have (mostly) been thought through. Please see the Convert Step Software Requirements section in the [UP Software Requirements Document](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engineering/Design/SRD/Universal%20Pipeline%20SRD.docx?d=w5eff6d937ce34bfa8651e588bdd4ea44&csf=1&web=1&e=IYm2Ol).

### Acceptance Criteria

- [ ] Convert Function updated per the SRD. Any changes to SRD reviewed and Approved by @arnejduranovic 
- [ ] SRD updated (if needed) and Approved by @arnejduranovic

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14603?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
