### ISSUE TITLE
When trying to view delivery details for reports that are not batched but sent as single messages#

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#14609]
### User Story
As a receiver who has useBatchHeaders set to false. I want to be able to see my reports in Daily Data without errors. 

### Description/Use Case
When there are multiple reports sent to a receiver at the exact same time (which occurs when there is a receiver not using batch headers, but is instead receiving each message as it's own report). The delivery details link returns a 500 error with the exception:

`"org.jooq.exception.TooManyRowsException Message: Cursor returned more than one result"`

This can by observed logging in as ar-phd in prod, going to [Daily Data](https://reportstream.cdc.gov/daily-data), and then selecting the "reportID" link to see more details for report_ID "18955639-1c6d-4182-a078-f91f6ecbdc25"

### Dev Notes
This occurs because the query in the fetchAction method in the DatabaseDeliveryAccess class throws an exception because there is more than one report with the same action id.

It also looks like this bug is manifesting in other ways, see: https://nava.slack.com/archives/C048S3GPSQG/p1725376883033999. The TLDR of this one is that may be the root cause of these issues: 

> I think this is a bug when the receiver has batching disabled and has multiple reports that need to be sent out at the same time. They are sent individually, but still get the same action id for the batch step

### Acceptance Criteria
- [ ] The delivery details page loads for reports that originated from a report with multiple messages to a receiver who has useBatchheaders set to false.
- [ ] The fetchAction method can handle the situation where there are multiple reports returned OR multiple reports being returned are eliminated as a possibility. 
- [ ] Investigated to see if it makes sense to make the action ID in the batch step unique so these errors do not occur

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14609?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
