### ISSUE TITLE
Finalize artifacts and test for improving response time

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#14611]
## Problem statement
We identified potential priorities and exploring areas we need to learn more about. Speeding up the responses we get from users was one of those priorities. We have drafted the content and need to finalize the templates to prepare for a test phase when we are next in touch with an unconnected STLT.

## What you need to know

- [Onboarding Journey Improvement Synthesis](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B3ADDDFE6-961D-49CE-B237-813024723BF6%7D&file=Document1.docx&action=default&mobileredirect=true)
- [Improving response time proposal](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Improving%20response%20time%20proposal.docx?d=w1d6d842228ae4bef987e444f3b99e659&csf=1&web=1&e=VLggHQ)
- [Template content drafts](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7Bacc3b356-ef64-4491-8e1c-1507351df64c%7D&action=edit&wdPreviousSession=f4f63718-3e6c-40a6-bda0-6150278c309d)

## Acceptance criteria

- [x] Finish SendGrid templates
- [x] Prepare any other materials necessary for launching test phase when ready
- [x] Create backlog ticket for test launch

**Comment by jillian-hammer** [comment]
what are the ACs here? @audreykwr
