### ISSUE TITLE
Create Proposal for Data Quality Scoring

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1461]
We need to start thinking about what data quality looks like. We have quality filters that prevent some test results from making it to the STLTs, but we don't have a lot of visibility into that, or how data quality is trending by clinic or overall. 

We should be able to see why a record might have failed data quality, and then calculate a score for a test result, AND then be able to query that from a table so we can view those results in Metabase and eventually show them to our STLTs on the web front-end.

There is an added complication that some places will have different ideas about what institutes data quality, and therefore we need to be able to modify data quality rules for different organizations and even different receivers for an organization.

Therefore, I'm asking you to write a proposal for our team about what data quality looks like, how do we calculate it for an organization and a receiver, and how will we store that information and make it queryable? 

There is a proposal process that is outlined in https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/proposals/0000-proposal-process-readme.md

The goal of a proposal is not to layout the actual tasks or start writing code, but to put forward an idea of how things should work/can work, and to prompt discussion.

The outcome of the proposal once it is accepted will then be a set of tasks or an Epic with the technical details laid out.

I'd like to have the proposal ready for discussion at the 12 June Engineering meeting. Feel free to reach out to Drew, Celeste, and James about this and have discussions with them about this. Our product and design people are top-notch and can help you come up with a great proposal.

fysa: @jlusds @drew-usds

**Comment by jlusds** [comment]
Questions that come to mind
-Why is X field now missing/different from how it was reported before? (is it a bug in how RS is reporting, or is it because a facility stopped reporting it)
-For specific fields, be able to track its % completion over time (empty, or unknown)

**Comment by jlusds** [comment]
Going to move this to product backlog
