### ISSUE TITLE
Plan meeting with CDC RE: Territories

### ISSUE THREAD

**Issue by jakefishbein-navapbc** [CDCgov/prime-reportstream#14620]
ACs

- [x] Jake to connect Kevin and Thane with Glenn
- [x] Jake to write a background brief for Glenn to use for a meeting
- [x] Glenn to coordinate a meeting time with them to discuss opportunities for RS to engage with territories
- [x] Glenn to determine next steps from a STLT engagement perspective.

**Comment by jakefishbein-navapbc** [comment]
Link to background [brief](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/02_Research/Health%20Equity/Document.docx?d=wa7b5b9ce69b94803a8eb8e4b5f7bd118&csf=1&web=1&e=8xlF7G)

**Comment by chris-kuryak** [comment]
Contact is  traveling. Waiting on return to schedule meeting

**Comment by chris-kuryak** [comment]
Glenn has emailed Thane, received response. And now Glenn to reach out to new contact in Palau.

**Comment by chris-kuryak** [comment]
Thane conversations have been via email. And there does not appear to be a need for an in-person meeting at this time.
