### ISSUE TITLE
Dynamically Split STLT Data Feed on Download Site by Receiver

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1462]
As part of the work to add an external name and description to receivers, and as part of our work on offering OTC and lower-quality data feeds to STLT's, we need to find a quick and easy way to split the downloadable reports on the web receiver. I think if just group the results by the receiver, into two sections, that would probably be sufficient for now.

@jlusds @drew-usds, what are your thoughts on this?

**Comment by jlusds** [comment]
That works for me. E.g. primary feed on top, secondary feed below
________________________________
From: Maurice Reeves ***@***.***>
Sent: Friday, July 2, 2021 10:59 AM
To: CDCgov/prime-reportstream ***@***.***>
Cc: Liu, James (CDC/OCOO/OD) ***@***.***>; Mention ***@***.***>
Subject: [CDCgov/prime-reportstream] Dynamically Split STLT Data Feed on Download Site by Receiver (#1462)


As part of the work to add an external name and description to receivers, and as part of our work on offering OTC and lower-quality data feeds to STLT's, we need to find a quick and easy way to split the downloadable reports on the web receiver. I think if just group the results by the receiver, into two sections, that would probably be sufficient for now.

@jlusds<https://github.com/jlusds> @drew-usds<https://github.com/drew-usds>, what are your thoughts on this?
