### ISSUE TITLE
Website edits per Phase 2 Comms Plan

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#14629]
## Problem statement

We need to update resources on the site based on the updates to the change comms plan.

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Comms Doc](https://cdc.sharepoint.com/:p:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Phase%202%20UP%20change%20communication%20messaging%20+%20plans.pptx?d=w1d38ec13266d4b0c855c4804c3f24aa6&csf=1&web=1&e=hybw6o)
- [Page list working space](https://docs.google.com/spreadsheets/d/1Zecg0XjMHOoYwk5-pq8fgRp7NY5jR-OjzCa_CspCe_M/edit?usp=sharing)
- [Content tracker](https://cdc.sharepoint.com/teams/ReportStream/Lists/ReportStream%20content%20tracker/AllItems.aspx)

## Acceptance criteria

- [x] Necessary pages identified for updates
- [x] Updates drafted and approved

Eng implementation ticket created for the following pages:

- [ ] Refer labs and reporting organizations
- [ ] Receiving data
- [ ] Getting started
- [ ] Managing your connection
- [ ] API guide [all pages in section]
- [ ] Security 
- [ ] Support
- [ ] About
- [ ] Home page
- [ ] Our network

## To do

- [ ] ...

**Comment by jillian-hammer** [comment]
@audreykwr Here is the updated homepage asset without CSV. Also saved in this [Sharepoint folder](https://cdc.sharepoint.com/:i:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/04_Branding/Assets/20240612_Homepage-Assets/how-we-help-1.png?csf=1&web=1&e=d25eGE).

<img width="1078" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXhaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--171e8cb511d5e438e5522eb967e63bfa0edc79f0/how-we-help-1.png" alt="how-we-help-1.png" />

**Comment by audreykwr** [comment]
This ticket actually replaces the following backlog items:

- https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/12981
- https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/12979
- https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/12982
- https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/12969

**Comment by chris-kuryak** [comment]
@audreykwr Thank you. I have closed those tickets with a comment linking them back to this one.
