### ISSUE TITLE
Create Proposal for Migration from Metabase to Superset

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1463]
We are considering migrating away from Metabase for our internal analytics tools to using Superset, which is from AirBnB and Apache: https://superset.apache.org/docs/intro

Two of the reasons we are looking at Superset is because it is fully open-source, and it offers many more options, chart types, etc

I would like you to draft a proposal that outlines the benefits Superset offers us, what limitations it has, and what the migration path would look like. If you are feeling ambitious, you can even set up a demo for us to look at. You could create a set of data in your `covid_result_metadata` table then point Superset at that to show us some of its capabilities.  

There is a proposal process that is outlined in https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/proposals/0000-proposal-process-readme.md

The goal of a proposal is not to layout the actual tasks or start writing code, but to put forward an idea of how things should work/can work, and to prompt discussion.

The outcome of the proposal once it is accepted will then be a set of tasks or an Epic with the technical details laid out.

I'd like to have the proposal ready for discussion at the 12 June Engineering meeting. Feel free to reach out to Drew, Celeste, and James about this and have discussions with them about this. Our product and design people are top-notch and can help you come up with a great proposal.

fysa: @jlusds @drew-usds @RickHawesUSDS

**Comment by jlusds** [comment]
Great! Let me know if you'd want to see a few example dashboards that we build currently

Things that work well about Metabase
-Has permissions for different user groups
-Offers both SQL and GUI options to develop charts
-Has lots of self serve visualization https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html
-Has ability to create filters to easily update charts https://www.metabase.com/docs/latest/users-guide/08-dashboard-filters.html

**Comment by jimduff-usds** [comment]
FYI, @tlosbo has been thinking about very similar stuff.
Key question:  Is our intention that SuperSet be available to customers?

**Comment by jorg3lopez** [comment]
Working on demo.

**Comment by jlusds** [comment]
What's the latest status on this? I think aim to pause on this for Sprint 22

**Comment by jorg3lopez** [comment]
> What's the latest status on this? I think aim to pause on this for Sprint 22

I have the proposal already. I'm working on doing a demo. Unfortunately, setting up my environment delayed the demo. I will continue working on this once I'm done formatting the file for NH.

**Comment by jlusds** [comment]
Thanks for the update

**Comment by sarahnw** [comment]
Closing, this is not a priority for the program.
