### ISSUE TITLE
Re-enable daily-data.spec e2e

### ISSUE THREAD

**Issue by etanb** [CDCgov/prime-reportstream#14655]
Due to a slew of errors in Pagination, we had to disable a handful of tests within `daily-data.spec`. This ticket is, after we make `UsePagination` updates and fix the table using that pagination, to re-enable and fix these tests.

Blocked by: https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/14238

## Acceptance Criteria
- [ ] Re-enable all daily-data.spec e2e tests and make them work properly
- [ ] Convert tests to POM

**Comment by chris-kuryak** [comment]
Per Penny in Slack, Redundant for #15211.
Closing.
