### ISSUE TITLE
Release Notes - June 2024 - Content refinement

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14664]
### Problem statement
As a user, I would like to know what features, bugs, other user facing updates have been made to ReportStream product.

### Procedure
https://docs.google.com/document/d/1vAiOJlfRMvJPRER3cr9Kr4lQ2-_ybNucJt28kI3fl1I/edit 

### Acceptance criteria
- [ ] Product Manager: Final Release Notes text (in ticket description) updated with all release notes and formatted with markdown
- [ ] Content Specialist: Approve release notes content and formatting

#### Updated navigation bar for users logged in to ReportStream's website
Improvement - When a user is logged in to the ReportStream website, they have a new navigation bar to access tools available for their account. Before the update, authenticated features were crowded and difficult to use, especially on smaller screens. The updated navigation makes it easier to access tools without losing any of the existing functionality.

#### ReportStream login upgraded to Okta Identity Engine
Improvement - This upgrade will allow ReportStream to provide more helpful login and account features. The new [Okta Identity Engine](https://help.okta.com/oie/en-us/content/topics/identity-engine/oie-index.htm) is a feature-rich update to the classic Okta Engine. You may notice some small visual and experience changes in the existing login process.

#### Daily Data now showing all results again
Bug Fix - Users were unable to see results on Daily Data past page seven. We fixed issue, and organizations who receive data can now access all pages of Daily Data.

#### South Carolina is now connected to ReportStream
Announcement - We’re excited to announce that ReportStream can now send public health data to South Carolina.

**Comment by chris-kuryak** [comment]
@audreykwr See release notes above. Ready for your review.

**Comment by audreykwr** [comment]
My edits added

**Comment by chris-kuryak** [comment]
Thank you!
