### ISSUE TITLE
Develop plans for a repo for settings and schemas

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1467]
Develop a plan for a repo for confidential schemas and settings.   

To do this, we need a way to pull those schemas into staging and prod - work with devops team on this.

1.  Go ahead and remove all such info from anything that is only used locally, eg organizations.yml
2. With devops, work to create a new repo
3.  Move all files from settings/prod and settings/staging to the new repo
5. Move private schemas and all staging and prod settings to the new repo
4. We won't remove historical info; just no new info going forward
6. Many schemas can stay in the public sphere, eg, direct-covid-19, pdi-covid-19, strac-covid-19.

**Comment by carlosfelix2** [comment]
OBE.  Settings, schemas and tables are to be stored in the DB.
