### ISSUE TITLE
Florida - UP Migration - Validate Test Data

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#14694]
### User Story:
As a developer, I want the [STLT] to validate test messages in staging, so that they can receive data in the format they expect.

### Description/Use Case
[STLT] is already receiving data from the covid pipeline they will be onboarded to the UP where they will be receiving data from SimpleReport including Covid, Flu and RSV. We need to make sure the message we generate from the UP passes the STLTs validation. We can use SimpleReport to submit test messages to the STLT.

### Dev Notes:

- [x] Upload the newly created receiver settings to Staging
- [x] Copy the receiver's secret key with the new receiver name in Azure's staging environment
- [x] Verify we can connect to the newly created receiver
- [x] Send a test message through Simple Report and make sure it gets routed to the STLT
- [x] Send test messages according to the STLT needs

### Acceptance Criteria 
- [ ] Created and sent data using Simple Report
- [ ] Confirmed with STLT that data passes validation

**Comment by oslynn** [comment]
Sent message to FL via staging and it got there correctly:
<img width="1523" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejdUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cdfb39c13a89d9ac0419e1c63062d28a666b6655/image.png" alt="image.png" />

Check their SFTP"
<img width="1220" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBei9UQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e8ba36ba2448cdddd5097ff5425028850085f8b/image.png" alt="image.png" />

**Comment by oslynn** [comment]
Sent message to FL via staging and it got there correctly:
<img width="1523" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejdUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cdfb39c13a89d9ac0419e1c63062d28a666b6655/image.png" alt="image.png" />

Check their SFTP"
<img width="1220" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBei9UQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e8ba36ba2448cdddd5097ff5425028850085f8b/image.png" alt="image.png" />

**Comment by oslynn** [comment]
Done for staging validation.
