### ISSUE TITLE
CA UP data discrepancy 

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#14707]
## Problem statement

Submitted file from Cedars- Sinai on 5/29 Report ID from Metabase of 3ffae5ce-1773-40ed-b4c8-b06298dca142                                                                                         
622990254
623040566
OBX|1|CE|85477-8^FLUAV RNA NAA+probe Ql (Upper resp)^LN||260385009^Negative^SCT^^Invalid result|
OBX|1|CE|85479-4^RSV RNA NAA+probe Ql (Upper resp)^LN||10828004^Positive^SCT^^Invalid result||
image.png

## What you need to know

Research shows SNOMED codes in OBX-3.1 are correct, the description of Invalid is wrong 
- UP file ca-receiver-transform.yml-7c102f4d-b050-4c3a-8ef2-e947091f2158-20240529162238.hl7
- CP file covid-19-fb46d9ae-a2ed-41a1-b349-3d68855a34a8-20240529162035.hl7

## Acceptance criteria

- [ ] Messages that were not delivered are identified and resent
- [ ] Resent messages are checked to ensure they "c" value is present and they are successfully sent to CA

## To do

- Track down original file from SR
- Check UP conversion for result code disconnect
- Advise if user resubmission of new code are needed or if this is a system issue

**Comment by GilmoreA6** [comment]
original report received from SR for Report ID: 7a3234d6-1226-43c4-8333-f6df648f4d60 received from SR with mismatched SNOMED codes and descriptions in the ValueCodeableConcept Element of the observation. (e.g. "valueCodeableConcept": {
                    "coding": [
                        {
                            "system": "http://snomed.info/sct",
                            "code": "10828004",
                            "display": "Invalid result"
                        }
                    ]
                }

**Comment by GilmoreA6** [comment]
The issue appears to be with however SR is/was populating the "display" field as the original uploaded CSV does not contain the description but only the code.

**Comment by TaneaY** [comment]
Escalated to SR engineering to update will leave open until fix is confirmed

**Comment by TaneaY** [comment]
<img width="949" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWRoQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c44e0efc6332fb688c37ed7e26afe7fc688278ac/image.png" alt="image.png" />

**Comment by GilmoreA6** [comment]
SR has now input a fix for the bug and CA has confirmed they would like the results resent with a status of "C" for corrected.

**Comment by chris-kuryak** [comment]
Still need to identify and resend the data

**Comment by chris-kuryak** [comment]
This will require SR, RS, and comms with Sender to complete.

**Comment by chris-kuryak** [comment]
SR going to send out message to sender tomorrow

**Comment by chris-kuryak** [comment]
James finished an update which will get merged on next deploy. Unblocking SR from having the sender resend messages.

**Comment by chris-kuryak** [comment]
Waiting on SR

**Comment by GilmoreA6** [comment]
All report re-sent from cedars-sinai
