### ISSUE TITLE
BUG: Authenticated navbar unavailable if not associated with any admin/receiver/sender groups

### ISSUE THREAD

**Issue by jpandersen87** [CDCgov/prime-reportstream#14701]
The auth navbar isn't rendered unless a user is part of the three current group types (admin, receiver, sender). This prevents the logout button from being available. The base bar should always be available after login (with logout button), with aspects of it hidden depending on permissions (aka group).

# How to recreate
1. Log in as a user that is not part of any group in Okta
2. The Auth nav bar does not appear

# Acceptance Criteria
- [ ] Auth navbar with user display and logout button available to all logged in users
- [ ] group-based navigation links/sections available to the user if they are associated
  - [ ] If user is not part of any group, they should only see email and logout in the Auth Nav Bar
- [ ] Create user that is not part of any Okta group for E2E tests 
- [ ] Update E2E

**Comment by penny-lischer** [comment]
@chris-kuryak do we need design for this?

**Comment by chris-kuryak** [comment]
Joseph has identified that the fix is a one-line code change.
Bulk of work will be getting with DevOps to check on the change.
