### ISSUE TITLE
Changes to Illinois Communicable Disease Reporting Rules

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#14713]
## Problem statement

We received an automated email from Illinois, and it included the following guidance. The guidance needs to be reviewed and determined if we need to take any action.

## What you need to know

- [20240513_Provider_Memo_on_Rule_Chang.pdf]
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEZhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f1cd71908944aab063241d88a6522926eec911b/20240513_Provider_Memo_on_Rule_Chang.pdf)

- [IDPH_Rules_Changes_Summary_ELR_2024.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzVhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a44e821077fde657305f09bd972dc9336cf72af7/IDPH_Rules_Changes_Summary_ELR_2024.pdf)

## Acceptance criteria

- [ ] Documentation reviewed
- [ ] Actions that need to be taken (or were taken) are noted in the ticket
- [ ] Follow-on tickets created (if necessary)

**Comment by MikaelahD13** [comment]
@victor-chaparro May you please take a look at these documents we received from Illinois? This is the message that was sent in the email, 

"We are reaching out to provide additional guidance around the recent rules changes (previously communicated via the attached SIREN memo on 5/13/24). We have attached a summary document to help clarify the new reporting rules.

 

If you have questions, please email: dph.elrresp@illinois.gov.  

 

 

Thank you

IDPH ELR team"

**Comment by victor-chaparro** [comment]
Have questions about what Point of Care testing means

**Comment by chris-kuryak** [comment]
@victor-chaparro Are we still blocked here?
