### ISSUE TITLE
Ensure JOOQ is serializing fields `sender_ip` and `external_name` in a safe manner and that said values are valid. 

### ISSUE THREAD

**Issue by jack-h-wang** [CDCgov/prime-reportstream#14721]
### User Story
As ReportStream, I want inputs from external sources sanitized so that I can be certain data is valid and does not pose a security concern.

### Description/Use Case
As a best practice, we should ensure that all database access is sanitized so that unintended consequences cannot occur. We should look at both incoming data when performing writes as well as the methods by which the database is accessed when processing API calls.

### Dev Notes
Some examples that may need to be addressed:
- `action`.`sender_ip` is in some cases taken from HttpRequestMessage headers. We could attempt to validate the headers contain valid IP addresses.
- `report_file`.`external_name` is in some cases taken in by the submission endpoint as `payloadName`. We could attempt to ensure this name does not contain invalid characters.
- Ensure database access is strictly via jOOQ using methods that do not introduce SQL injection vulnerabilities. See [jOOQ documentation](https://www.jooq.org/doc/latest/manual/reference/security/security-sql-injection/)

### Acceptance Criteria
- [ ] The serialization of `sender_ip` to the database from submissions is being serialized by JOOQ safely. If this is not the case refactor so we're using JOOQ safely. 
- [ ] prior to serialization ensure `sender_ip` is a valid ip address ([commons](https://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/InetAddressValidator.html) has a ready bake way to do this). If validation fails ~reject operation on error~ don't set the ip. 
- [ ] The serialization of `external_name` to the database from submissions is being serialized by JOOQ safely. If this is not the case refactor so we're using JOOQ safely. 
- ~prior to serializtion of `external_name` to the database ensure the value is a valid unix/windows filename. You should be able to use one of the implementations of Path to check for valid filename w/o touching the actual file system. If validation fails reject operation on error~
- [ ] Unit test ensuring malicious input to those fields is sanitized before it lands in the db

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14721?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean

**Comment by david-navapbc** [comment]
This ticket has been updated since it was groomed. The volume of work is greater than was originally pointed.

**Comment by mkalish** [comment]
I've dropped the 4th ac and the payloadname currently has no expectations for it to be valid filename (in fact it typically would not have an extension)

I've also adjust the sender ip ac since it does not make sense to reject a report if there is an IP issue as the sender wont' have a remediation

**Comment by mkalish** [comment]
Taking a look at the SQL injection angle:

- I found no [usages](https://www.jooq.org/doc/latest/manual/sql-building/bind-values/sql-injection/#sql-injection-in-jooq) `org.jooq.PlainSQL`
- We use the codegen capabilities which the [documentation](https://www.jooq.org/doc/latest/manual/getting-started/use-cases/jooq-as-a-sql-builder-with-code-generation/) states that jooq will use prepared statements with bound params
