### ISSUE TITLE
[BUG] - Daily Data table does not show all results

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14742]
## Problem statement
As found by the support team, the Daily Data table is not showing all results. This impacts all of our receivers by making it significantly more difficult to find the data they are looking for.

Known issues:
1. The maximum number of "results" shown in the search status bar is 61, even when there are more results available.
2. The user cannot navigate past page 7 of the table on Daily Data, even if more results are available

## What you need to know
- Per Penny and Etan, this is apparently an issue with the front end and is around the new table component.
- Penny is reverting to an old version of the table component to restore functionality.
- We will work to fix the bug on the new table/pagination

## How to recreate
- I log in as Prime Admin on production
- I set myself as CA-DPH
- Go to Daily Data
- Filter from June 2023 - June 2024
- Click apply
- Says only 61 total results in the Search Status bar
- When I try to navigate past page 7, it does not allow me to AND does not produce anymore results

## Acceptance criteria

- [ ] An accurate number of results appears on the Daily Data search status bar upon first load and when using the filters
- [ ] The user is able to navigate via pagination to all available results

**Comment by penny-lischer** [comment]
@chris-kuryak we will create a temp solution to unblock the issue but will need a follow on ticket OR reopen the #14240 ticket which caused the issue.

**Comment by chris-kuryak** [comment]
Thanks @penny-lischer I have created a follow on ticket to address the pagination and table component update: #14762

cc: @etanb
