### ISSUE TITLE
Auth Microservice SRD Review

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#14765]
### User Story

As a stakeholder of ReportStream,
I want a SECURE, RELIABLE, and SCALABLE way to handle incoming authentication and authorization requests,
so that we can minimize potential of ReportStream AUTH bringing the system down or introducing security defects.

### Description/Use Case

Presently, ReportStream has what is essentially a custom authorization server coupled with the backend application. The program should move to a more streamlined and microservice-appropriate auth solution. The new AUTH service design is detailed in [UP Software Requirements Document](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engineering/Design/SRD/Universal%20Pipeline%20SRD.docx?d=w5eff6d937ce34bfa8651e588bdd4ea44&csf=1&web=1&e=IYm2Ol) but needs to be evaluated if it is the best approach. We need to weigh this design as is against other possible solutions and determine a path forward.

A common pattern in microservices is to have a proxy server that does AUTH and ROUTING to microservices. This pattern should be evaluated as well as potential usage of CDC's Application Gateway project.

Some additional things that should be evaluated:
- [Azure Application Gateway](https://learn.microsoft.com/en-us/azure/application-gateway/overview)
- [Azure Front Door](https://learn.microsoft.com/en-us/azure/frontdoor/front-door-overview)
- [Azure Identity Management](https://learn.microsoft.com/en-us/azure/security/fundamentals/identity-management-best-practices)

One idea to investigate could be evaluating using Azure Application Gateway with Azure Identity Management for machine-machine auth and we wouldn't use Okta at all. Or maybe Okta can integrate with Azure Identity management? Big question: Is there a way we can implement auth without writing our own auth service?

### Acceptance Criteria

- [ ] Auth Service SRD reviewed and alternate approaches investigated/considered and long-term solution agreed upon
- [ ] Auth section of [SRD](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engineering/Design/SRD/Universal%20Pipeline%20SRD.docx?d=w5eff6d937ce34bfa8651e588bdd4ea44&csf=1&web=1&e=WSTAyt) updated

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14765?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
