### ISSUE TITLE
Add validation during organization creation CLI tool

### ISSUE THREAD

**Issue by jalbinson** [CDCgov/prime-reportstream#14764]
### User Story
We want organizations attempting to be created to be validated.

### Description/Use Case
During a CLI call to created any organization/sender/receiver, call our validation code on the file passed in. Add in a new flag to skip this process if necessary.

### Risks/Impacts/Considerations
- We need a flag to bypass the validation step just in case there is a situation where an update is needed NOW (like during a meeting with a STILT) and we don't have time to update the json schem or konform validation.

### Dev Notes
- Call our validation code in `PutSettingCommand`
- Skip validation if our new flag is present (something like --no-validation)
- print out errors if there are any so the user can fix them

### Acceptance Criteria
- validation code called on all creation and updates to organizations
- new flag for skipping validation works
- errors are printed
- unit tests

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14764?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
