### ISSUE TITLE
Implement REST Transport setting for UCSD's Epic 

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#14771]
Implement REST Transport setting for UCSD's Epic instance (Making the feature reusable for any other receiver that needs it).
Epic needs the HL7 package to be cleaned without '/r' character.

1.) Implementation
2.) Test sending the message to Epic

**Comment by oslynn** [comment]
Work on getting Two-legged OAuth to authenticate with EPIC.
Got Postman collection from @jorg3lopez.  It saved in junk/flexion/LA/Epic/KeyPair/UCSD-EPIC.postman_collection.json

**Comment by chris-kuryak** [comment]
Waiting on Flexion to overcome issue with UCSD/EPIC

**Comment by oslynn** [comment]
Done with ticket. 12996.
