### ISSUE TITLE
Add sender_id to covid_result_metadata table, to help track data custody

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1478]
sender_id is the best way to identify who the data is coming from.   For example, when we are pulling from an aggregator like Waters, we can have it populate that column, and use that to know who is sending to Waters.

**Comment by MauriceReeves-usds** [comment]
Added ticket #2145 as part of this work

**Comment by jimduff-usds** [comment]
Done.
