### ISSUE TITLE
Update Clickable Prototype for CSV uploader tool

### ISSUE THREAD

**Issue by kjt9cc** [CDCgov/prime-reportstream#1479]

**Comment by celestemespinoza** [comment]
07.07.21 @hie1 is updating the [current prototype](https://www.figma.com/file/ctpYEoOBWGkUnk9cmXzVp2/ReportStream-Submitter-Front-End?node-id=943%3A4273); a [research guide](https://docs.google.com/document/d/1wd05A8cTRGNSuQR6sReTTE5AYAMzSPd3FUD80d93cLo/edit) is in review; outreach to Iowa facilities for initial validation

**Comment by hie1** [comment]
Prototype has been updated with new endpoint messaging for examples. 
Prototype has been updated with a "Recipients" message for accepted files.

Updated prototype here:
https://www.figma.com/file/ctpYEoOBWGkUnk9cmXzVp2/ReportStream-Submitter-Front-End?node-id=966%3A3566

**Comment by hie1** [comment]
Determined a clickable prototype will not be useful for demos with states. This is likely better as static screens.

The prototype has been updated with new error messaging language.
