### ISSUE TITLE
Design Comprehensive Layout for TOS Consent and Mini Intake Form

### ISSUE THREAD

**Issue by kjt9cc** [CDCgov/prime-reportstream#1480]
we need a "quick and dirty" way to capture the senders consent to the terms of service. design a simple form that can serve this need. The form collects first name, last name, email, phone, organization name, state, clia #?, org type?

the form has a button to submit (i agree?). we'll capture the submitted data in an audit log. we'll need a simple confirmation screen that the data has been received. Next step? we'll contact you with instructions on creating account credentials?

- don't need to create a record in the CRM, 
- don't need to create a user account yet.

need the **form** and **confirmation screen**

**Comment by celestemespinoza** [comment]
Initial Workflow
https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1624913471929/b42a509d8935f349ce94d6d0e47594fd841e2d9c?sender=uca3809945b9eca14d25d6461

**Comment by celestemespinoza** [comment]
@loripusey @kjt9cc is there some reason we are not performing at least one step of verification here? through email?

**Comment by celestemespinoza** [comment]
@drew-usds please review to close 
`https://www.figma.com/file/UEA8ymWclNHeb90FcTsWk5/CSV-Uploader-Miniform?node-id=0%3A1`

**Comment by kjt9cc** [comment]
for now, we are trying to just capture data. the verifcation would require ability to send out emails, not have them land in the junk folder, and the ability to process the link contained in the email. I think we need all this for the next iteration. some of this probably already exists in okta?

**Comment by BerniXiongA6** [comment]
7.13.2021 From a content standpoint, here are my suggested revisions using the ReportStream content style guide:

On page 1:
"By submitting your information, you're agreeing to the ReportSteam terms of service."

On page 2:
"If you don't receive confirmation, check your SPAM folder for an email from reportstream@prime.gov.

**Comment by drew-usds** [comment]
Added @celestemespinoza 's work to our main Figma prototype and made some updates:

- [Initial form](https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=1150%3A470)
- [Confirmation](https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=1150%3A462) (still a little rough)
- [Placeholder template for SendGrid email confirmation](https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=1156%3A4373)

**Comment by BerniXiongA6** [comment]
@drew-usds Rebecca advised that we can remove "PRIME" from the ReportStream labels. Is that your understanding as well? Also, the RS content style guide instructs to avoid "sender" and "receiver" on client-facing messaging. The guide proposes the use of "testing facility" instead of "sender." Those are the only bits of feedback I have; otherwise, looks great!
