### ISSUE TITLE
Finalize designs re: senders checking code-to-condition table

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#14808]
## Problem statement
We have created a prototype for senders checking code to condition mapping and need to refine the designs before engineering implementation.

## What you need to know

- [Onboarding Journey Improvement Synthesis](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B3ADDDFE6-961D-49CE-B237-813024723BF6%7D&file=Document1.docx&action=default&mobileredirect=true)
- [User flow draft](https://docs.google.com/document/d/1mMmVvPEkOfiQ6nW6q7teUSHbiamKPNxwKnKOexiHf34/edit)
- [Figma working space](https://www.figma.com/design/Du7feM8huRDAAZCQcUIj93/Website-Redesign?node-id=5907-7010)

**Design review**:

- [x] Review remaining notes in Figma
- [x] Fix any spacing issues
- [x] Check visual style
- [x] Check/correct links
- [x] Add any necessary navigation/breadcrumbs
- [x] Review with engineering to double check functionality (already reviewed previously, but good to check in again! Especially because it mostly A6 involved in that review)

## Acceptance criteria

- [x] Designs finished and approved
- [ ] Eng ticket created

**Comment by jillian-hammer** [comment]
Duplicative ticket. Completed with Finalize design of the code-to-condition mapping tool for eng hand-off #16297. Closing!
