### ISSUE TITLE
Discovery: Meet with engineers to determine needs around FHIR Path UI tool

### ISSUE THREAD

**Issue by jakefishbein-navapbc** [CDCgov/prime-reportstream#14802]
## Problem Statement
Existing CLI tool for onboarding engineers to test messages with specific transforms. We want to make that process easier for onboarding engineers by creating a UI. THIS IS DISCOVERY WORK.

## Acceptance Criteria

- [x] Engineering purpose of testing FHIR Paths documented (reason why they do it)
- [x] Documented existing flow of what they do
- [x] Identify how often this is being done
- [x] Identify what parts of the process can be improved and what the quantifiable impact of those improvements could be
- [x] Determine how/if this can be included in the UI/functionality for the existing Message Testing Improvement work or if it should be a separate tool/interface

**Comment by jakefishbein-navapbc** [comment]
[Notes](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B8A810A7E-ECE2-4C87-BC1E-AD34B0ED3621%7D&file=FHIR%20Path%20Testing.docx&action=default&mobileredirect=true&wdsle=0) from conversation with Ott.

**Comment by chris-kuryak** [comment]
From Jake: Likely doesn't need to be solved in our message testing UI

**Comment by chris-kuryak** [comment]
We have a meeting/sync with Josh (currently working on FHIR path error messaging) today.

**Comment by jillian-hammer** [comment]
is this considered done? @jakefishbein-navapbc
