### ISSUE TITLE
Migration versions of milestone email templates

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#14804]
## Problem statement
We have finalized the templates for onboarding milestones and can adapt them to use tested for migration communication as well, especially as we have so many coming up this next quarter.

## What you need to know

- [Onboarding Journey Improvement Synthesis](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B3ADDDFE6-961D-49CE-B237-813024723BF6%7D&file=Document1.docx&action=default&mobileredirect=true)
- [Improving response time proposal](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Improving%20response%20time%20proposal.docx?d=w1d6d842228ae4bef987e444f3b99e659&csf=1&web=1&e=VLggHQ)
- [Template content drafts](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7Bacc3b356-ef64-4491-8e1c-1507351df64c%7D&action=edit&wdPreviousSession=f4f63718-3e6c-40a6-bda0-6150278c309d)

## Acceptance criteria
- [x] Templates drafted and approved

**Comment by audreykwr** [comment]
Glenn was not able to get to this before his OOO so we will collect his feedback at a later time.

**Comment by chris-kuryak** [comment]
Templates:
https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BB77C044E-641E-4CD8-916C-31D78F58084B%7D&file=Migration%20milestone%20templates.docx&action=default&mobileredirect=true
