### ISSUE TITLE
Finalize instructions/resources re: senders checking code-to-condition table

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#14807]
## Problem statement
We have created a prototype for senders checking code to condition mapping and identified the materials needed to help users use that tool effectively. 

## What you need to know

- [Onboarding Journey Improvement Synthesis](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B3ADDDFE6-961D-49CE-B237-813024723BF6%7D&file=Document1.docx&action=default&mobileredirect=true)
- [User flow draft](https://docs.google.com/document/d/1mMmVvPEkOfiQ6nW6q7teUSHbiamKPNxwKnKOexiHf34/edit)
- [Figma working space](https://www.figma.com/design/Du7feM8huRDAAZCQcUIj93/Website-Redesign?node-id=5907-7010)
- [James documentation ticket](https://app.zenhub.com/workspaces/engagement-6166edbd409257001e09f1b2/issues/gh/cdcgov/prime-reportstream/14989)
- [Folder in Sharepoint with docs, template, and other notes](https://cdc.sharepoint.com/:f:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Code%20to%20condition%20tool?csf=1&web=1&e=6fk5tg)

### Notes on where to add the final documentation/instructions:
This step comes at the beginning of testing messaging phase of onboarding. I believe before they set up their data file and test,

**For the API guide:** 
Need to know if it should be considered a step BEFORE our current step 1 (format and validate) or if it is considered part of that step. That will determine if it is placed within that step in the guide or if it before then, and needs to be added here as well.
<img width="1880" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG4vQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4532b46339bdd1420dcc1b7b41d7c18462eb902/Screenshot%202024-09-25%20at%2010.10.10%E2%80%AFAM.png" alt="Screenshot 2024-09-25 at 10.10.10 AM.png" />

## Acceptance criteria

- [x] Review James's instructions and template and edit as needed for clarity. (Consider visual style on Excel sheet)
- [x] Get feedback and input from Victor on the clarity of instructions and template
- [x] Instructions/templates incorporated into API guide and approved by tech lead
- [x] Follow on eng ticket for updating site content and PDF when design goes to implementation

**Comment by audreykwr** [comment]
@chris-kuryak as we talked about, this may be bumped to next sprint. Should we move back into next items instead now?

**Comment by audreykwr** [comment]
James created a first version of these, and we just need to clean up for implementation with the code to condition tool. So the ACs may just change to finalizing/editing. Or you can create a new ticket for this.

@jillian-hammer @chris-kuryak

**Comment by jillian-hammer** [comment]
Duplicative ticket. Completed with Finalize design of the code-to-condition mapping tool for eng hand-off #16297. Closing!
