### ISSUE TITLE
Set up roadmap narrative log with PO

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#14825]
## Problem statement
PO wants to better equip the team to communicate about the users and their needs that we serve with the tasks and goals we are working toward. We want to create a way to start to track what we know, resources, and needs.

## Acceptance criteria

- [ ] Initial doc created and reviewed by PO

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
Removing due to PO changes
