### ISSUE TITLE
Validator tool deprecation plans per Phase 2 Comms Plan

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#14822]
## Problem statement

We need to make plans for removing the validator tool from the site as it no longer works for the UP.

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Comms Doc](https://cdc.sharepoint.com/:p:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Phase%202%20UP%20change%20communication%20messaging%20+%20plans.pptx?d=w1d38ec13266d4b0c855c4804c3f24aa6&csf=1&web=1&e=hybw6o)

## Acceptance criteria

- [x] Plan drafted and approved
- [x] Eng tickets created

**Comment by chris-kuryak** [comment]
Draft: https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B382C2073-522C-44E2-9B77-A48D9819496E%7D&file=Validator_Change_Comm_Planning.docx&action=default&mobileredirect=true&wdsle=0

**Comment by audreykwr** [comment]
Eng ticket: https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/14929
