### ISSUE TITLE
Create Interactive End-User Demo of RS (Universal Pipeline ONLY)

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#14842]
### User Story

As a non-technical stakeholder of RS,
I would like to be able to interact with the system as a sender and receiver,
so that I can better understand the user experience and common RS features.

### Description/Use Case

Create documentation in RS Sharepoint that explains how a non-technical user can best:
1.A As a sender, Send a report to ReportStream
1.B As a sender, Query the history endpoint to see where their report went
2. As a receiver, view what reports they have potentially received (SFTP)

The STAGING environment should be used for this exercise so it must be set up with at least one sender and one receiver a stakeholder can pretend to be. The receiver(s) should have an SFTP bucket a stakeholder can access to download the files. 

The point of this exercise is so that a stakeholder can understand how user interact with the system. To that end, the demo should:

- touch on both HL7v2 and FHIR formats
- touch on both custom machine-machine and x-functions-key auth

### Risks/Impacts/Considerations

If the SFTP bucket is created in Azure, folks may need Azure Super User access to access it. We need to think through how prohibitive this is and come up with alternate solution if needed.

I created a DevOps ticket for an SFTP server here: https://github.com/CDCgov/prime-reportstream/issues/14882

### Dev Notes

- Contact Arnej for SFTP bucket connection information. I was able to connect using this tool that seems friendly for non-technical users: https://cyberduck.io/
- SFTP docs here: https://github.com/CDCgov/prime-reportstream/blob/f68b1caca2fe65304950156f239866dda120edba/prime-router/docs/docs-deprecated/SFTP-SETUP.md#client-accessible-sftp

### Acceptance Criteria

- [ ] Demo steps documented in ReportStream Sharepoint
- [ ] Staging env set up and steps in document confirmed to work
- [ ] Platform designer ran through the steps and reviewed document

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14842?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
