### ISSUE TITLE
LIVD SARS-CoV-2 Catalog with FDA Attributes to be uploaded to ReportStream

### ISSUE THREAD

**Issue by OHoward2023** [CDCgov/prime-reportstream#14841]
## Problem statement

We received an updated LIVD to the Reportstream inbox. The LIVD table needs to be uploaded into ReportStream.

## What you need to know

[LIVD-SARS-CoV-2-2024-06-13 PRIME.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjErQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8efa0a0eb10ebb32b5bd1b3765fa247e4740d154/LIVD-SARS-CoV-2-2024-06-13%20PRIME.xlsx)

## Acceptance criteria

none

## To do

Please upload the new LIVD table to ReportStream.

**Comment by oslynn** [comment]
Done.
