### ISSUE TITLE
Load Test: Update demo1 environment to match production

### ISSUE THREAD

**Issue by JosiahSiegel** [CDCgov/prime-reportstream#14864]
- [x] Update SQL server to match specs of production
- [x] Enable full debugging on the SQL DB
- [x] Set up the backend SFTP server to match what's in prod/staging
  - Note: This SFTP does NOT exist in prod. 

- [x] Ensure max containers matches the current prod (I think it's 6 total, see the ASG config *but look at max - this is limited by IPs, not the ASG*)
   - Autoscaling matches across all environments (6-20 instances). If we want to change for all environments we can, but they are currently identical.

Please confirm with Michael Kalish when this is done

**Comment by mkalish** [comment]
@JosiahSiegel What was the logging settings you enabled?
