### ISSUE TITLE
Update lookupTable function to allow to lookup more than one column of a Table

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#14901]
## Problem statement

lookTable only allows to lookup one column. If we try to lookup another column, it throws "Value column not found in specified lookup table" at LookupTableValueSet.kt: 38.  During the first lookup, it filters the table to specified key:valueColumn at line 43.  

## Impact
- Example: Data from SimpleReport has the LOINC code but does not include OBR-4.7 Coding System Version ID. This value is found in the LIVD table. When we go to look up the OBR-4.7, we cannot because we are only limited to looking up one column of the LIVD table at a time.

## How to reproduce
To duplicate the problem at the sr-service-request-code-extension-version element to simple-report-sender-transform.yml after element: sr-service-request-code-extension-display as below:

  - name: sr-service-request-code-extension-display
    condition: '%serviceRequest.code.coding[0].display.empty()'
    bundleProperty: '%serviceRequest.code.coding[0].display'
    value: [ '%serviceRequest.code.coding.code' ]
    valueSet:
      lookupTable:
        tableName: LOINC
        keyColumn: LOINC_NUM
        valueColumn: LONG_COMMON_NAME

  - name: sr-service-request-code-extension-version
    condition: '%serviceRequest.code.coding[0].version.empty()'
    bundleProperty: '%serviceRequest.code.coding[0].version'
    value: [ '%serviceRequest.code.coding.code' ]
    valueSet:
      lookupTable:
        tableName: LOINC
        keyColumn: LOINC_NUM
        valueColumn: VersionLastChanged

./gradlew package

Use Postman to send
File: [SR-TEST.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG1RQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7e85a4117a1b9f2235a513e7e8289c646855357/SR-TEST.txt)

You should see the exception below:
<img width="1346" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGFRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f84064c51e945282c72a0b62792c3108e577711/image.png" alt="image.png" />

## Needed behavior
- [ ] Ability to look up more than one column in the LIVD table at a time per transform in the UP

**Comment by chris-kuryak** [comment]
Waiting on response from Platform to determine who should handle this change.

**Comment by oslynn** [comment]
The bug is in line 43 uses .retainColumns().  It makes another table that contain only the two columns.
Here is solution:
<img width="1044" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3lhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c04f003438c057fb8e504d8cc6303c37cb087c38/image.png" alt="image.png" />

**Comment by oslynn** [comment]
Done

**Comment by oslynn** [comment]
Done

**Comment by oslynn** [comment]
Done
