### ISSUE TITLE
Add short doc to the project that serves as a memorium for Dr Waters

### ISSUE THREAD

**Issue by david-navapbc** [CDCgov/prime-reportstream#14905]
### User Story

As a Report Stream developer 
I want to ensure the intent of prior RS developers to honor Dr Waters' memory is realized
So that a man worth remembering is remembered. 

### Description/Use Case
While working a ticket that dealt with some of our REST endpoints I came across [a code comment](https://github.com/CDCgov/prime-reportstream/blob/9ff7d9005572720e47b4b7b0aa60d44b7f96f0fe/prime-router/src/main/kotlin/azure/ReportFunction.kt#L80) indicating the "waters" in some of our api paths was so named for Dr Waters. There are similar comments in our API docs. As far as I can tell there's nothing in our docs that speaks to who Dr Waters was or why the RS team chose to honor him in this way. 

From a [Vanity Fair article](https://12ft.io/proxy?q=https%3A%2F%2Fwww.vanityfair.com%2Fnews%2F2021%2F01%2Fhow-trumps-covid-chaos-drowned-the-fda-in-junk-science) that references Dr Waters:

>Morale plunged inside the agency as political appointees filtered in and bullied career staff. On a conference call one of those new arrivals threatened colleagues, “Either you get on Trump time or you get out.” Meanwhile, lower-level reviewers were crushed by work. Two staffers have committed suicide in recent months. Dr. Michael Waters, a lead reviewer of COVID-19 diagnostic tests in the FDA’s Office of In Vitro Diagnostics and Radiological Health, took his own life in September. His widow, Hang Waters, told Vanity Fair that he was working around the clock and had gone five nights without sleep. She said he told his children that “he had to work harder to save a lot of people, and if you don’t work hard, then many people will die.”

### Risks/Impacts/Considerations

None

### Dev Notes

The text of [his obituary](https://www.tributearchive.com/obituaries/18488618/michael-stephan-waters) can be used for the memorial doc. 

### Acceptance Criteria

* create new markdown doc that contains the image, obituary text, and a short paragraph describing why Dr Waters is being honored by the RS team.

**Comment by MauriceReeves-usds** [comment]
I love this! Thank you for doing this! @audreykwr

**Comment by dylansmith-Nava** [comment]
@david-navapbc a brief blurb describing Dr. Waters' life is available at the bottom of the [ReportStream API webpage](https://reportstream.cdc.gov/developer-resources/api). I have also committed a pull request addition to the [Thanks and Acknowledgements](https://github.com/CDCgov/prime-reportstream/blob/master/thanks.md) page. As such, I will close out of this ticket. cc @Andrey-Glazkv
