### ISSUE TITLE
Missouri Onboarding - Validate Test Data

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#14956]
### Notes doc and requirements
https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engagement/Onboarding/Missouri%20Onboarding%20Running%20Notes.docx?d=w08365c76002c4104be0bf6e7d8e5ce2a&csf=1&web=1&e=BbcVBs

### Acceptance Criteria 
- [ ] Created and sent data using fake data generator 
- [ ] Created and sent data using synthesized data generator 
- [x] Confirmed with STLT that data passes validation 

### Dev Notes
- [x] Upload the newly created receiver settings to Staging
- [x] Copy the receiver's secret key with the new receiver name in Azure's staging environment
- [x] Verify we can connect to the newly created receiver
- [x] Send a test message through Simple Report and make sure it gets routed to the STLT
- [x] Send test messages according to the STLT needs

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with receiver 
- [ ] RS team member who originates this ticket: add any dependencies, as needed 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Receiver" and state label 
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by JessicaWNava** [comment]
I set up the user in staging as well as their credentials in Azure, but it appears that the transport information we have is incorrect and the folder does not exist. Will need to wait until this information is provided.

**Comment by JessicaWNava** [comment]
Tried creating needed folder, but permission was denied

**Comment by chris-kuryak** [comment]
@JessicaWNava Are you still blocked on this? I show @lucero-v as owning Missouri onboarding?

**Comment by lucero-v** [comment]
STLT confirmed that test messages pass their validation. Moved to Prod as of today, Oct 1st.

Connection Type: SFTP
Conditions tested: COVID-19 (including antibody)
Positives set up to receive: COVID-19 (including antibody), MPOX
Negatives set up to receive: none
Format receiving: HL7
