### ISSUE TITLE
Create Playbook for Developer GitHub Workflow

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1495]
In our playbooks folder, write up a quick document about how we work with GitHub: PR's, checking in, checking out, reviews, etc. Feel free to both write to it, and then I can take a pass through it too.

fysa: @jlusds

**Comment by jlusds** [comment]
Was any progress made on this?

**Comment by jorg3lopez** [comment]
> Was any progress made on this?

No. Not yet, but I think I can start on it this week.

**Comment by jlusds** [comment]
Thanks for the update

**Comment by jorg3lopez** [comment]
We never got to this. It's all you now, @Brick.

**Comment by brandonnava** [comment]
@brick-green I'm guessing you're using a different doc for onboarding engineers that you're keeping updated so this playbook might not be needed. Close the ticket?

**Comment by brick-green** [comment]
@brandonnava We haven't had many new engineers recently so this dropped in priority. Let's just close.
