### ISSUE TITLE
Ignore linting/testing steps in build-frontend when in trialfrontend env

### ISSUE THREAD

**Issue by jpandersen87** [CDCgov/prime-reportstream#14975]
As it is expected that our PR workflow will handle ensuring branches pass linting/testing before allowing a merge, these steps are unnecessary when deploying to the trialfrontend and their times greatly shrunk if conditionally disabled. This will also allow deployments even if there are problems with staging (causing e2e to fail).

# Acceptance Criteria
- [ ] linting and testing steps in build-frontend action updated with `if` condition checking if env-name does not start with `trialfrontend`

**Comment by chris-kuryak** [comment]
Waiting on DevOps approval
