### ISSUE TITLE
Guam Onboarding - Validate Test Data

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#14979]
Link to Notes and Requirements Doc: https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engagement/Onboarding/Guam%20Onboarding%20Running%20Notes.docx?d=wa153b215436a4f2090d7e05d6ec29bcd&csf=1&web=1&e=H38a5p

### Acceptance Criteria 
- [x] Created and sent data using fake data generator 
- [x] Created and sent data using synthesized data generator 
- [x] Confirmed with STLT that data passes validation 

### To Do 
- [x] RS engineer: update this ticket with comments with every interaction with receiver 
- [x] RS team member who originates this ticket: add any dependencies, as needed 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Receiver" and state label 
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by oslynn** [comment]
GU doesn't have staging environment setup, yet.

**Comment by oslynn** [comment]
Sent sample messages FLUE (+), RSV (+), COVID (+) to GU for validation.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk1vQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f39d0900453b24db15e960866b443518c68afb67/image.png" alt="image.png" />

**Comment by oslynn** [comment]
Sent messages for validation:
<img width="745" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjRvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0d288e64596a49d2d81fae18fcde357555ad7bd/image.png" alt="image.png" />

**Comment by oslynn** [comment]
Got email back from Christine Baza
[Uploading... ._Screenshot 2024-08-05 at 8.56.59 AM.png]
