### ISSUE TITLE
Ohio - UP Migration - Move to Production

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#14981]
### User Story:
As a developer, I want to move the Ohio settings to production after getting approval from the STLT, so that they can start receiving live data.

### Description/Use Case
[STLT] is already receiving data from the covid pipeline they will be onboarded to the UP where they will be receiving data from SimpleReport including Covid, Flu and RSV. We need to make sure the message we generate from the UP passes the STLTs validation. We can use SimpleReport to submit test messages to the STLT.

### Dev Notes:

- [x] Upload the staging receiver settings to Production
- [x] Copy the receiver's secret key with the new receiver name in Azure's production environment
- [x] Verify we can connect to the newly created receiver
- [ ] Monitor the UP data for the conditions the receiver is interesed in and notify them when reports are routed to them

### Acceptance Criteria 
- [x] Receiver UP settings are pushed to production
- [x] ReportStream can connect to STLT in production
- [ ] Notify STLT when reports are routed to them for each condition they are receiving

**Comment by lucero-v** [comment]
**Moved to Production**
Conditions tested: COVID
Positives receiving: COVID
Negatives receiving: none
Connection Type: SFTP

**Comment by chris-kuryak** [comment]
Still in the 2 weeks of monitoring
