### ISSUE TITLE
Create draft of Code-to-Conditions instructions and template for Content Review

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14989]
## Problem statement
We have created a prototype for senders checking code to condition mapping and identified the materials needed to help users use that tool effectively.  So now we need to create the instructions and CSV template used by Senders.

## What you need to know

- [Onboarding Journey Improvement Synthesis](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B3ADDDFE6-961D-49CE-B237-813024723BF6%7D&file=Document1.docx&action=default&mobileredirect=true)
- [User flow draft](https://docs.google.com/document/d/1mMmVvPEkOfiQ6nW6q7teUSHbiamKPNxwKnKOexiHf34/edit)
- [Figma working space](https://www.figma.com/design/Du7feM8huRDAAZCQcUIj93/Website-Redesign?node-id=5907-7010)

## Acceptance criteria

- [x] Draft of instructions for Senders documented in sharepoint (add link in ticket/comment)
- [x] Draft of CSV template for Sender to fill in (linked in ticket)
- [x] Inform Audrey when complete

**Comment by chris-kuryak** [comment]
On track to finish by end of sprint

**Comment by GilmoreA6** [comment]
Zenhub doesn't support a xlsm file so I can't upload to here, but the draft is completed

**Comment by GilmoreA6** [comment]
[Completing Mapping File.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0xsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ac34a608455dbbfaccbc1e181f10074b7baf19d/Completing%20Mapping%20File.docx)

**Comment by chris-kuryak** [comment]
@chris-kuryak Make new ticket for finalizing
