### ISSUE TITLE
Update OML FHIR -> HL7v2 Mappings

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#14992]
### User Story

As a maintainer of the OML FHIR -> HL7v2 mappings,
I want to make sure these mappings are using the newer long-term mappings instead of the old mappings,
so that I can work to remove the old mappings from the repo and ensure data will not get dropped during translation.

### Description/Use Case

Before Flexion ETOR goes to production with routing test orders, we need to ensure OML is properly mapped. Presently, HL7v2->FHIR appears to be using the correct mappings, but OML FHIR -> HL7v2 is using some old ones. We should update OML FHIR ->HL7v2 to use the new mappings because the old ones are not "complete".

### Acceptance Criteria

- update current OML mappings to use the new/long-term mappings. OML mappings (`prime-router/src/main/resources/metadata/hl7_mapping/OML_O21/OML_O21-base.yml`) no longer dependent on:
  - [ ] prime-router/src/main/resources/metadata/hl7_mapping/OML_O21/base (or updated)
  - [ ] prime-router/src/main/resources/metadata/hl7_mapping/common
  - [ ] prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes
  - [ ] prime-router/src/main/resources/metadata/hl7_mapping/v251-elr
- Create end-to-end tests for OML HL7v2->FHIR->HL7v2 following pattern in `/prime-reportstream/prime-router/src/testIntegration/kotlin/datatests/mappinginventory/catchall/orur01`. For the input use a maximally configured OML message ONLY FOR THE PARTS THE ARE CURRENTLY MAPPED. see:
  - FHIR -> HL7 mapping: `prime-router/src/main/resources/metadata/hl7_mapping/OML_O21/OML_O21-base.yml`
  - HL7 -> FHIR mapping: `prime-reportstream/prime-router/metadata/HL7/catchall/hl7/message/OML_O21.yml`
- [ ] Integration Tests .CSV reviewed to ensure mappings do not break current ETOR senders/receivers in staging
- [ ] Delete old mappings or create ticket to do so if there are significant issues
- [ ] Review new tickets for completeness

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14992?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean

**Comment by arnejduranovic** [comment]
Reminder: After this ticket, we need to ask ourselves "what is left for ensuring the ORM -> FHIR -> OML flow works and is adequately tested"

**Comment by MichaelEsuruoso** [comment]
closing ticket
