### ISSUE TITLE
Create Message Test Bank 

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#14993]
## Problem statement

Developers on ReportStream need test messages for various reasons including system testing, FHIR/HL7 mapping updates etc.

## What you need to know

Upload messages to staging `test-bank` container

## Acceptance criteria

- [ ] Create folders of HL7 and fhir test messages that can be used to 
- [ ] Messages should exists for each common situation and reportable condition that RS supports ( Covid, Flu A/B, RSV) positives and negatives
       - Multiplex combinations for (Covid, Flu) , (Covid, Flu, RSV)
       - Single condition without AOE
       - Single condition with AOE
       - Multiplex without AOE
       - Multiplex with AOE

**Comment by chris-kuryak** [comment]
@victor-chaparro Is this ticket still needed?

**Comment by victor-chaparro** [comment]
Yes, we need to populated the test message bank container in staging with test messages. With all the conditions above.

**Comment by oslynn** [comment]
Done
https://portal.azure.com/#@cdc.onmicrosoft.com/resource/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourceGroups/prime-data-hub-staging/providers/Microsoft.Storage/storageAccounts/pdhstagingstorageaccount/storagebrowser

**Comment by oslynn** [comment]
Personal Note.  If needed again, The created messages is in junk/Testing/TestMessages directory.
