### ISSUE TITLE
South Dakota - UP Migration - Validate Test Data

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#15022]
[STLT] = South Dakota

Notes and Requirements doc: https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engagement/STLT%20and%20Sender%20Onboarding/South%20Dakota%20Onboarding%20Running%20Notes.docx?d=w8fee313580e54ba89fc51245d730b319&csf=1&web=1&e=ueeo9g

### User Story:
As a developer, I want theSouth Dakota to validate test messages in staging, so that they can receive data in the format they expect.

### Description/Use Case
[STLT] is already receiving data from the covid pipeline they will be onboarded to the UP where they will be receiving data from SimpleReport including Covid, Flu and RSV. We need to make sure the message we generate from the UP passes the STLTs validation. We can use SimpleReport to submit test messages to the STLT.

### Dev Notes:

- [x] Upload the newly created receiver settings to Staging
- [x] Copy the receiver's secret key with the new receiver name in Azure's staging environment
- [x] Verify we can connect to the newly created receiver
- [x] Send a test message through Simple Report and make sure it gets routed to the STLT
- [ ] Send test messages according to the STLT needs

### Acceptance Criteria 
- [ ] Created and sent data using Simple Report
- [ ] Confirmed with STLT that data passes validation

**Comment by oslynn** [comment]
<img width="876" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnRkQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a06c78bd2f7923ceb13302fd95335915dcb532e5/image.png" alt="image.png" />

**Comment by oslynn** [comment]
Per my finding SimpleReport only has LOINC codes that support the following, for now:

Influenza PCR
Influenza virus A by RNA PCR: 34487-9
Influenza virus B by RNA PCR: 40982-1

I will reach out to SR to see if we can add support for the rest of LOINC codes requested by SD.

**Comment by oslynn** [comment]
Sent sample messages for validation via email.  According to James Nguyen, their SFTP for test environment is not setup, yet.

<img width="1058" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTJ5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--17bc16d270a2172bfd15c93b24edf7a49ab0ebd8/image.png" alt="image.png" />

**Comment by oslynn** [comment]
<img width="880" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3plQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccfbc8dad15b78a1d4853b093455280ebcfec7f6/image.png" alt="image.png" />

**Comment by oslynn** [comment]
<img width="1172" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW9FQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--205630aa564a84c6ae9e7883c1e1d65db86ff7f1/image.png" alt="image.png" />

**Comment by oslynn** [comment]
<img width="1180" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkllQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56ad10331043ce575cebe07d9ce816ed8a57e98c/image.png" alt="image.png" />

**Comment by oslynn** [comment]
<img width="1176" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk1lQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e65a42aecc4817301782e1350479235934266e04/image.png" alt="image.png" />

**Comment by oslynn** [comment]
<img width="1182" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFFnQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08be78f7b9b8404ea77d4cf5aaf95f35c41f7f29/image.png" alt="image.png" />

**Comment by oslynn** [comment]
South Dakota is ready for production

<img width="1166" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1FqQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84d7c9ea5204aa0a42ce680f18925f18da4f25b5/image.png" alt="image.png" />

**Comment by oslynn** [comment]
Done with validation.
