### ISSUE TITLE
Pennsylvania - UP Migration - Validate Test Data

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#15025]
### User Story:
As a developer, I want thePennsylvania to validate test messages in staging, so that they can receive data in the format they expect.

### Description/Use Case
[STLT] is already receiving data from the covid pipeline they will be onboarded to the UP where they will be receiving data from SimpleReport including Covid, Flu and RSV. We need to make sure the message we generate from the UP passes the STLTs validation. We can use SimpleReport to submit test messages to the STLT.

### Dev Notes:

- [x] Upload the newly created receiver settings to Staging
- [x] Copy the receiver's secret key with the new receiver name in Azure's staging environment
- [x] Verify we can connect to the newly created receiver
- [x] Send a test message through Simple Report and make sure it gets routed to the STLT
- [x] Send test messages according to the STLT needs

### Acceptance Criteria 
- [x] Created and sent data using Simple Report
- [ ] Confirmed with STLT that data passes validation

**Comment by oslynn** [comment]
Requirement:
https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BA78F3B32-D78E-437B-A2EB-977C89B13713%7D&file=Pennsylvania%20-%20Onboarding%20Running%20Notes.docx&action=default&mobileredirect=true

**Comment by oslynn** [comment]
Email from Glenn.
https://outlook.office365.com/mail/id/AAQkADY2ODFiNTg0LWYyZTItNDc0Ny1hNTg4LTdhYzAzOWVmYTczMgAQAMcBujbb6KhEgBM%2Bqaq91Do%3D

**Comment by oslynn** [comment]
There are two documents to fill out and submit to PA for validation.
Test list.xlsx - fill out the Performance LOINC codes that we will send to them. Note, column C is Test Performance LOINC codes 
MU_Message_Validation_Tracking.xlsx - this file is for test messages tracking.  Note,  column 'B' is Message ID (MSH-10) of every sample messages that we are going to submit to them.

**Comment by oslynn** [comment]
Here TestList.xlsx fillled and MU_message_Validataion_Tracking.xlsx
[MU_Message_Validation_Tracking.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFFFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b05fe3938aa861f5584203e27fe9e2890052ba90/MU_Message_Validation_Tracking.xlsx)

**Comment by oslynn** [comment]
Victor sent all the messages for validation to them 10/1/2024
<img width="756" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1lWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83770ac6815a159be87074ab8f9ae0fa6f2a0b7d/image.png" alt="image.png" />

**Comment by victor-chaparro** [comment]
Pennsylvania we need to suppress AOEs from being sent to them

**Comment by MikaelahD13** [comment]
Spillover Reason: PA is requesting more messages and changes.​
