### ISSUE TITLE
Clean up the route step

### ISSUE THREAD

**Issue by thetaurean** [CDCgov/prime-reportstream#15039]
### User Story
As a developer I want to prune unused/old code and related documentation so the codebase stays clean.

### Description/Use Case
We recently split the route step into two new steps. We need to remove traces of the old route step from the code.

### Risks/Impacts/Considerations
Make sure not to remove anything that might still be used such as datatypes/objects/etc.

### Dev Notes
Search for `/// TODO: remove after route queue empty` and this ticket number

### Acceptance Criteria
- [ ] `FHIRRouter.kt` and related tests/docs deleted from the repo
- [ ] All TODOs addressed
- [ ] #14904 merged and in production at least one deployment prior to the PR for this ticket getting merged

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/15039?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
