### ISSUE TITLE
Oregon - UP Migration - Move to Production

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#15031]
### User Story:
As a developer, I want to move the Oregon settings to production after getting approval from the STLT, so that they can start receiving live data.

### Description/Use Case
[STLT] is already receiving data from the covid pipeline they will be onboarded to the UP where they will be receiving data from SimpleReport including Covid, Flu and RSV. We need to make sure the message we generate from the UP passes the STLTs validation. We can use SimpleReport to submit test messages to the STLT.

### Dev Notes:

- [x] Upload the staging receiver settings to Production
- [x] Copy the receiver's secret key with the new receiver name in Azure's production environment
- [x] Verify we can connect to the newly created receiver
- [ ] Monitor the UP data for the conditions the receiver is interesed in and notify them when reports are routed to them
- [ ] Send a test message through Simple Report and make sure it gets routed to the STLT
- [ ] Send test messages according to the STLT needs

### Acceptance Criteria 
- [ ] Receiver UP settings are pushed to production
- [ ] ReportStream can connect to STLT in production
- [ ] Notify STLT when reports are routed to them for each condition they are receiving

**Comment by oslynn** [comment]
Need to contact OR for credential.  Point of contact is in the note.

**Comment by victor-chaparro** [comment]
https://app.zenhub.com/workspaces/prime-devops-606cb208a8c112000fd48349/issues/gh/cdcgov/prime-devops/140

**Comment by oslynn** [comment]
They just want us to put them in Prod and deactivate it.  Whenever we have Hep C RNA support, we can activate the feed, then.  It is in prod, now.

**Comment by oslynn** [comment]
Whenever we have Hep C support.  OR would like the sample file to drop into the 'in' SFTP and notify them.
<img width="1174" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVBhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--76f9d787844a4dc2e6ce48f99a43f822766d20e3/image.png" alt="image.png" />
