### ISSUE TITLE
Create Initial Wireframes of Message Testing Automation Improvements

### ISSUE THREAD

**Issue by jakefishbein-navapbc** [CDCgov/prime-reportstream#15050]
## User story

As a ReportStream Onboarding Engineer, I need to test receiver settings, so that I am sure they are correct before pushing them into production.

## Background & context

Onboarding engineers do not currently use the receiver settings UI as it has limited functionality. Our goal is to create a more simple and efficient experience by adding a message testing concept to the receivers setting UI to improve its functionality. 

Our prior work on this issue is to gather information from our onboarding engineers on improved functionality needs, process steps, and required elements. These can be found in this [mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1707143235464/93e77ab0af79ae95da8906218c8b5ae7b1067e47?sender=u1cb5f3c6aed590b290728229). This background work will inform the development of a UI design that will support these needs within a limited scope.

## Open questions
-   ...
-   ...

## Working links
-   [Design Brief](https://cdc.sharepoint.com/teams/ReportStream/_layouts/15/doc.aspx?sourcedoc={fd2b189e-ed8e-4c8c-a946-1a1b73afda54}&action=edit)
-   [Mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1707143235464/93e77ab0af79ae95da8906218c8b5ae7b1067e47?sender=u1cb5f3c6aed590b290728229)
-   [Figma](https://www.figma.com/design/iIGPoS3V2MCVsOOUZKlgiV/Receiver-Message-Testing?node-id=1-4&t=1wVngZWaNmISLUbH-0)

## To do
- [ ] Compile the following into a single source/document for Message Testing 
  - [ ] User tasks to accomplish
  - [ ] What the user needs to accomplish those tasks
  - [ ] FE Requirement
  - [ ] BE Requirement
  - [ ] Current Design
- [ ] Sync with Jillian and Audrey to define the following wire-framing process

## Acceptance criteria
- [x] Sync with Jillian and Audrey (above)
- [x] Create design brief
- [x] Draft initial wire-flow to determine the optimal interactions

**Comment by jakefishbein-navapbc** [comment]
[Message Testing User Tasks](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/01_WebDesign/Features/Message%20Selection%20and%20Testing/Message%20Testing%20Task%20Breakdown.xlsx?d=w16a1c1dc174444c3bdda4cd349ecb778&csf=1&web=1&e=E9pmgG)

**Comment by jakefishbein-navapbc** [comment]
[Design Brief](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/01_WebDesign/Features/Message%20Selection%20and%20Testing/2024_07_Design_Brief_Message_Selection_and_Testingg%20UI.docx?d=wfd2b189eed8e4c8ca9461a1b73afda54&csf=1&web=1&e=FfDY0T)

**Comment by audreykwr** [comment]
@jakefishbein-navapbc I don't recall this conversation. Do you have notes from where we discussed that? 

> Sync with Jillian and Audrey to define the following wire-framing process


 CC @jillian-hammer @chris-kuryak
