### ISSUE TITLE
Implement smoke test pattern from spike and tag tests to be smoked

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-reportstream#15057]
## Problem statement

E2E tests always querying against Staging data is causing a large number of exceptions and PagerDuty alerts. To prevent this from happening, we want to allow E2E tests to run against different types of data including Local, Mock, Staging, and Live.

## What you need to know

Spike to determine pattern of implementation is [here](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/14210)

## Acceptance criteria

- [x] Merge code from [spike](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/14210) and make additional changes for specs that don't require a user flow (i.e. pages with reportId) to be able to run as smoke
- [x] Add smoke tags to tests or groups that are within the Admin -> happy path.
- [x] Smoke tests should only run agains Chrome.

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
On track
