### ISSUE TITLE
Iowa - UP Migration - Validate Test Data

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#15062]
### User Story:
As a developer, I want the [STLT] to validate test messages in staging, so that they can receive data in the format they expect.

### Description/Use Case
[STLT] is already receiving data from the covid pipeline they will be onboarded to the UP where they will be receiving data from SimpleReport including Covid, Flu and RSV. We need to make sure the message we generate from the UP passes the STLTs validation. We can use SimpleReport to submit test messages to the STLT.

### Notes Document and Requirements
https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engagement/Onboarding/Iowa%20Onboarding%20Running%20Notes.docx?d=w5fa1e107e3dc4ef0bed414a3d011db7f&csf=1&web=1&e=rzwNvD

### Dev Notes:

- [x] Upload the newly created receiver settings to Staging
- [x] Copy the receiver's secret key with the new receiver name in Azure's staging environment
- [x] Verify we can connect to the newly created receiver
- [x] Send a test message through Simple Report and make sure it gets routed to the STLT
- [x] Send test messages according to the STLT needs

### Acceptance Criteria 
- [x] Created and sent data using Simple Report
- [x] Confirmed with STLT that data passes validation

**Comment by lucero-v** [comment]
Unblocked from sending messages, now need to send more test messages and email to confirm that they received them

**Comment by lucero-v** [comment]
Swathi Ramasahayam validated test messages on Aug 21st
