### ISSUE TITLE
Minnesota - UP Migration - Move to Production

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#15065]
### User Story:
As a developer, I want to move the Minnesota settings to production after getting approval from the STLT, so that they can start receiving live data.

### Description/Use Case
[STLT] is already receiving data from the covid pipeline they will be onboarded to the UP where they will be receiving data from SimpleReport including Covid, Flu and RSV. We need to make sure the message we generate from the UP passes the STLTs validation. We can use SimpleReport to submit test messages to the STLT.

### Dev Notes:

- [x] Upload the staging receiver settings to Production
- [x] Copy the receiver's secret key with the new receiver name in Azure's production environment
- [x] Verify we can connect to the newly created receiver
- [ ] Monitor the UP data for the conditions the receiver is interesed in and notify them when reports are routed to them
- [ ] Send a test message through Simple Report and make sure it gets routed to the STLT
- [ ] Send test messages according to the STLT needs

### Acceptance Criteria 
- [ ] Receiver UP settings are pushed to production
- [ ] ReportStream can connect to STLT in production
- [ ] Notify STLT when reports are routed to them for each condition they are receiving

**Comment by oslynn** [comment]
Tested the setting and uploaded to Prod.
Created secrete key for prod.
Deactivate it for now.  Will turn on tomorrow.

**Comment by oslynn** [comment]
Moved to prod 9/13/2024

**Comment by oslynn** [comment]
Good Morning All, 

We have been reviewing both feeds and things are lookin pretty good. I will do some final cross referencing today and if all checks out, I will send an email out first thing tomorrow letting you know it's ok to turn off your sFTP feed. 

Also, we should be good to cancel todays meeting as I have nothing to report. 

Thank you kindly, 
Beatrice
