### ISSUE TITLE
Minnesota - UP Migration - Validate Test Data

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#15066]
### User Story:
As a developer, I want the Minnesota to validate test messages in staging, so that they can receive data in the format they expect.

### Description/Use Case
[STLT] is already receiving data from the covid pipeline they will be onboarded to the UP where they will be receiving data from SimpleReport including Covid, Flu and RSV. We need to make sure the message we generate from the UP passes the STLTs validation. We can use SimpleReport to submit test messages to the STLT.

### Notes doc and requirements
https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engagement/Onboarding/Minnesota%20Onboarding%20Running%20Notes.docx?d=we9a6f9098aa245b8a6cac96c9df86fa5&csf=1&web=1&e=od5zlI

### Dev Notes:

- [x] Upload the newly created receiver settings to Staging
- [x] Copy the receiver's secret key with the new receiver name in Azure's staging environment
- [x] Verify we can connect to the newly created receiver
- [x] Send a test message through Simple Report and make sure it gets routed to the STLT
- [x] Send test messages according to the STLT needs

### Acceptance Criteria 
- [ ] Created and sent data using Simple Report
- [ ] Confirmed with STLT that data passes validation

**Comment by JessicaWNava** [comment]
PR for the transform is still in review and we don't have where to send the data to yet, so this ticket is not actually ready to be worked on.

**Comment by oslynn** [comment]
<img width="777" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUZ2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ce2a39c10d2122b5869a67fec30dada3ae705b0/image.png" alt="image.png" />

**Comment by oslynn** [comment]
Got email from MN.  I wonder,, should I response to them or SR should?
<img width="1174" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXE5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--641b2b215c9dece1789fa66a390e8395237d9bee/image.png" alt="image.png" />

**Comment by oslynn** [comment]
Will filter FLU out according to Glenn.
<img width="1186" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFcrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d904876afa8ad9e20584d1f8cdd41b4d5dcae821/image.png" alt="image.png" />

**Comment by oslynn** [comment]
Done
