### ISSUE TITLE
Louisiana - UP Migration - Validate Test Data

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#15073]
### User Story:
As a developer, I want the Louisiana to validate test messages in staging, so that they can receive data in the format they expect.

### Description/Use Case
[STLT] is already receiving data from the covid pipeline they will be onboarded to the UP where they will be receiving data from SimpleReport including Covid, Flu and RSV. We need to make sure the message we generate from the UP passes the STLTs validation. We can use SimpleReport to submit test messages to the STLT.

### Notes document and requirements
https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engagement/Onboarding/Louisiana/Louisiana%20Onboarding%20Running%20Notes.docx?d=w0bc3b9294d5c45df97eddc8fde6375c6&csf=1&web=1&e=mUpcYp

### Dev Notes:

- [x] Upload the newly created receiver settings to Staging
- [x] Copy the receiver's secret key with the new receiver name in Azure's staging environment
- [x] Verify we can connect to the newly created receiver
- [x] Send a test message through Simple Report and make sure it gets routed to the STLT
- [x] Send test messages according to the STLT needs

### Acceptance Criteria 
- [x] Created and sent data using Simple Report
- [ ] Confirmed with STLT that data passes validation

**Comment by JessicaWNava** [comment]
Was able to successfully send the message, waiting to hear back from the STLT

**Comment by JessicaWNava** [comment]
I have wrapped up the requested changes and am waiting for a PR review to send the message.

**Comment by JessicaWNava** [comment]
Moved their settings from staging to production and added "doesNotMatch(sender_id, simple_report.*)" as a routing filter to the CP settings for them in prod
