### ISSUE TITLE
Massachusetts - UP Migration - Validate Test Data

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#15077]
### User Story:
As a developer, I want the [STLT] to validate test messages in staging, so that they can receive data in the format they expect.

### Description/Use Case
[STLT] is already receiving data from the covid pipeline they will be onboarded to the UP where they will be receiving data from SimpleReport including Covid, Flu and RSV. We need to make sure the message we generate from the UP passes the STLTs validation. We can use SimpleReport to submit test messages to the STLT.

### Notes doc and requirements
https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engagement/Onboarding/Massachussetts%20Onboarding%20Running%20Notes.docx?d=wea4dac3fe3dc46c7bd4e06980d138089&csf=1&web=1&e=KzcUAW

### Dev Notes:

- [ ] Upload the newly created receiver settings to Staging
- [ ] Copy the receiver's secret key with the new receiver name in Azure's staging environment
- [ ] Verify we can connect to the newly created receiver
- [ ] Send a test message through Simple Report and make sure it gets routed to the STLT
- [ ] Send test messages according to the STLT needs

### Acceptance Criteria 
- [ ] Created and sent data using Simple Report
- [ ] Confirmed with STLT that data passes validation

**Comment by GilmoreA6** [comment]
Massachusettes requested change to test messages as described below:

"
Hi James,

 

MDPH would like to receive the identified AOE questions via ReportStream’s ELR feed.

 

Currently, our ELR Portal/Surveillance System (MAVEN) cannot consume the following AOE questions:

 

76691-5 - Gender identity

SR0001-What is the gender of their sexual partners

 

A MAVEN software release is required for their integration into a question package.

 

We are in the requirements gathering phase for an upcoming release, but there is no projected go live date as yet.

 

Thus, we are requesting that 76691-5 and SR0001 be temporarily filtered out from our ELR feed, until we can successfully accept these AOE questions.

 

Do send me any questions or concerns.

 

 

Best regards,

Samorga"

**Comment by GilmoreA6** [comment]
initial feedback received. Mass asked to move forward with testing plan

**Comment by GilmoreA6** [comment]
Mass approved us to move forward with testing production data
