### ISSUE TITLE
Montana - UP Migration - Validate Test Data

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15087]
### User Story:
As a developer, I want the [STLT] to validate test messages in staging, so that they can receive data in the format they expect.

### Description/Use Case
[STLT] is already receiving data from the covid pipeline they will be onboarded to the UP where they will be receiving data from SimpleReport including Covid, Flu and RSV. We need to make sure the message we generate from the UP passes the STLTs validation. We can use SimpleReport to submit test messages to the STLT.

### Notes doc and requirements
https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engagement/Onboarding/Montana%20Onboarding%20Running%20Notes.docx?d=we6f35d8c066d44ba875c8f21f9b05167&csf=1&web=1&e=wwSB7z

### Dev Notes:

- [x] Upload the newly created receiver settings to Staging
- [x] Copy the receiver's secret key with the new receiver name in Azure's staging environment
- [x] Verify we can connect to the newly created receiver
- [x] Send a test message through Simple Report and make sure it gets routed to the STLT
- [x] Send test messages according to the STLT needs

### Acceptance Criteria 
- [x] Created and sent data using Simple Report
- [ ] Confirmed with STLT that data passes validation

**Comment by chris-kuryak** [comment]
There is not anything to do on this until our initial meeting on 7/11.

**Comment by GilmoreA6** [comment]
Whitelisting for MT test environment needed, ticket started with DevOps https://app.zenhub.com/workspaces/prime-devops-606cb208a8c112000fd48349/issues/gh/cdcgov/prime-devops/139

**Comment by GilmoreA6** [comment]
CR was closed but we still cannot reach the hostname:

Jeremy Page (DevOps) email to cdc support - response from support:

Hello,

 

What is the source IP of the server you are using?
Also can you please submit a Support request linked below for tracking?

 

Thanks

Jon"

"CHG0038085

General

Page, Jeremy (CDC/IOD/OPHDST)
​
Gillen, Jonathon (CDC/OCOO/OCIO/CSPO) (CTR)
​
​
Gilmore, James (CDC/IOD/OPHDST) (CTR)
​
172.17.6.0/24 and 172.16.7.0/24 to xfer.hhs.mt.gov on port 22. I submitted a support request.

Jeremy Page, Principal Devops Engineer 
 +1.336.601.7274 icf.com | LinkedIn
Gillen, Jonathon (CDC/OCOO/OCIO/CSPO) (CTR)
​
Page, Jeremy (CDC/IOD/OPHDST)
​
​
Gilmore, James (CDC/IOD/OPHDST) (CTR)
​
Hello,

 

What is the source IP of the server you are using?
Also can you please submit a Support request linked below for tracking?

 

Thanks

Jon

 

Office of the Chief Information Officer (OCIO) | Office of the Chief Operating Officer (OCOO)

Jon Gillen

Enterprise Firewall Team

Cybersecurity Program Office (CSPO)

Office of the Chief Information Officer (OCIO)

Office of the Chief Operating Officer (OCOO)

xpe3@cdc.gov | Mobile# (765) 532-6030

 

Open a Firewall Support Request

 

Open a Firewall Change Request


Page, Jeremy (CDC/IOD/OPHDST)
​
Gillen, Jonathon (CDC/OCOO/OCIO/CSPO) (CTR)
​
​
Gilmore, James (CDC/IOD/OPHDST) (CTR)
​
Hello, this CR was closed about 2 weeks ago but we are unable to reach the the Montana DoH from our application.
