### ISSUE TITLE
Maine Onboarding - Build Receiver Settings

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#15092]
### Acceptance Criteria 
- [x] Added to organization.yml and created yamlitos  
    - [x] Customer status = testing  
- [x] Added to prod settings table  
    - [ ] Added quality filter = allowNone() 
- [x] Added to staging settings table  
    - [ ] Added quality filter = allowNone() 

### To Do 
- [x] RS engineer: update this ticket with comments with every interaction with receiver 
- [x] RS team member who originates this ticket: add any dependencies, as needed 
- [x] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [x] Pipelines: Onboarding & Operations (New) 
     - [x] Labels: "Onboarding-ops" and "Receiver" and state label 
     - [x] Epics: [select the epic for this API onboarding sender]

**Comment by GilmoreA6** [comment]
Maine receiver settings created
