### ISSUE TITLE
Maine Onboarding - Validate Test Data

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#15093]
### Acceptance Criteria 
- [x] Created and sent data using fake data generator 
- [x] Created and sent data using synthesized data generator 
- [ ] Confirmed with STLT that data passes validation 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with receiver 
- [ ] RS team member who originates this ticket: add any dependencies, as needed 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Receiver" and state label 
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by GilmoreA6** [comment]
Test messages sent to Maine, waiting on review

"Hi All,

Just wanted to let everyone know that I am able to connect via SFTP to the Maine host. I am still waiting on whitelisting to complete on my side so I can't yet send from our staging environment, but I do have attached to this three test messages for your review.

covid-single.hl7
Single positive covid result with AOEs as order level NTEs
multiple-messages.hl7
    -Two positive covid messages in a single batch file w/no NTEs
multiplex-covid.hl7
    -Single multiplex result w/ positive covid result and all other results stripped.

I included the NTE's on the first result just to give you an idea of what they would look like if you decide you would like us to send them. We could also send them as NTEs under the OBX segment(s).

Let me know what changes you would like to see/issues you encounter.

Thanks,

James
"

**Comment by GilmoreA6** [comment]
Hi All,

As per our discussion today I have sent some more test messages, this time sending them directly through our staging environment to the "TEST" folder. I've attached the test cases to this email. There are four additional messages. Currently I am doing the following transformations/configs to the messages. Please let me know if anything needs to change:

MSH-3 DEFAULTING - "CDC PRIME - Atlanta, Georgia (Dekalb)^2.16.840.1.114222.4.1.237821^ISO"
MSH-5 DEFAULTING -"ME-DOH"
MSH-6 DEFAULTING -"ME-DOH"
Removing all AOE OBXs
Removing any OBXs from panel tests that are not positive covid results

Thanks,

James
[ME test cases.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnhOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccf9227959d47cc73b17522a0daf8b29f45818c8/ME%20test%20cases.xlsx)

**Comment by GilmoreA6** [comment]
Maine validated test data and approved us to test production data
