### ISSUE TITLE
Get truncateHl7Fields to work for integration tests

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#15109]
### User Story
As a developer I want to be able to write integration tests that take the receiver's truncation fields into consideration.

### Description/Use Case
Currently, if you write a test using a receiver that has truncateHl7Fields set, it will not actually truncate those fields. 

### Acceptance Criteria
- [ ] When truncateHl7Fields is set on a receiver used in the integration tests, those fields actually get truncated.

**Comment by chris-kuryak** [comment]
Will carry over to next sprint

**Comment by JessicaWNava** [comment]
I think this was fixed by Lucero's change because it is working now, so I updated MO's testing to better reflect their settings and show that it is working.

**Comment by chris-kuryak** [comment]
Deployment complete today, marking this as done per Jessica mentioning that it was just waiting on deployment
