### ISSUE TITLE
Add additional logging to the Send step

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#15122]
### User Story
As a developer, I would like to analyze the poor performance of the send step to come up with some mitigation strategies

### Description/Use Case
The Send step is currently very slow (on average each invocation takes 60-120 seconds) and is by far the slowest part of the system.  We would like to add better logging/metrics to begin to diagnose it

### Dev Notes
- [This](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#autocollected-micrometer-metrics-including-spring-boot-actuator-metrics) might be something that can get plugged in; either the Jar or itself or micrometer on its own

### Acceptance Criteria
- [ ] Queries against events/metrics/logs can be written in azure to show a breakdown of duration by receiver, transport type, number of items and type of report (HL7 or FHIR)
- [ ] A follow up ticket is written to analyze the queries after they have run in production

**Comment by Andrey-Glazkv** [comment]
@brandonnava to discuss it at prod sync
