### ISSUE TITLE
Develop new guidance for using Sharepoint instead of Keybase

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15128]
## Problem statement
We received guidance from DevOps that we can no longer use Keybase for storing credentials. #8877
The guidance is to now use Sharepoint.
As such, we want to provide guidance to our Engagement team members as to how to store and retrieve credentials moving forward.

## What you need to know

- #8877 is the previous ticket showing this discovery
- ...

## Acceptance criteria

- [x] Confirm with Jeremy/DevOps on any existing guidance beyond "Use Sharepoint"
- [ ] Write up guidance for Engagement Team in the Team Charter (Working Agreement) document
- [ ] Present/Align with Engagement team on this new guidance (17th min?)

**Comment by snesm** [comment]
Sharing a secret with an individual (via CDC Teams) is probably different than [storing secrets](https://github.com/CDCgov/prime-reportstream/issues/8877).

Further investigation into our usage is warranted and may lead to additional discussion with the CDC.

**Comment by chris-kuryak** [comment]
@MikaelahD13 I think we can mark this as blocked pending more guidance from DevOps on STORING secrets (not SHARING secrets).

**Comment by chris-kuryak** [comment]
@snesm Thank you for the follow-up on this ticket. Please let us know of any guidance regarding STORING SECRETS since we can no longer use Keybase for that purpose.

**Comment by chris-kuryak** [comment]
Thanks @JosiahSiegel --

I just learned that Teams and Sharepoint share a document structure. I didn't know that, so thanks for the info!

Is there any specific guidance on HOW those secrets should be stored in the document structure? I mean any specific guidance on security on a file? 

When creating a document, it asks for a sensitivity label, and there are several sub-categories. Any guidance on which we need to use?
![Screenshot 2024-07-22 at 10 57 35 AM](https://github.com/user-attachments/assets/1a7f187c-498e-4cb2-bab3-dc68d31501cc)

**Comment by chris-kuryak** [comment]
Thanks @JosiahSiegel !

For awareness to all team members, we also received this guidance from CDC via email:

> No, Keybase isn’t authorized for use on CDC networks. As a matter of fact, I know it used to show up as malicious software and there are several incidents in Archer where findings were created when Keybase was found on CDC laptops. I don’t think that happens anymore.

 

Teams is a perfectly viable solution for sharing through private channels. Training on Teams may be a beyond my expertise, but the M365 team has made an entire website with some very good guides/training on sharing files through private Teams channels:

 

Teams FAQs | M365 | OCIO (cdc.gov)

How to use Private Channels in Teams.docx (sharepoint.com)

Create and use private channels - Microsoft Support

**Comment by snesm** [comment]
@MikaelahD13 please use label "**Highly Sensitive**" and "**Recipients Only**"

**Comment by chris-kuryak** [comment]
Per @snesm amending the proposed guidance:
1. Create a document/file with the secret in [Sharepoint Engagement > Private folder](https://cdc.sharepoint.com/:f:/r/teams/ReportStream/Shared%20Documents/Engagement/Private?csf=1&web=1&e=Ftdsdf)
2. Label file with "Highly Sensitive" and "Recipients Only"
3. Share only with the people who need access to that document

**Comment by chris-kuryak** [comment]
Engagement team has concerns. Sent to Patrick to approach in Mon engr sync.

**Comment by chris-kuryak** [comment]
Patrick has asked Stephen on the DevOps to confirm the following guidance:
1. For sharing/storing within the CDC environment, use Teams/Sharepoint
2. For sharing outside the CDC environment, use an encrypted Outlook message

**Comment by snesm** [comment]
Here's the [Information Protection Label Usage Guidelines](https://intranet.cdc.gov/ocio/o365/informationprotection/label-use-guidelines/index.html) (CDC network access only).
 
To send an encrypted email to a STLT: when composing email from your CDC Office365 account (webmail) use the shield dropdown on the upper right and select **Highly Sensitive\Recipients Only**. Add the recipient, and the body of the message which is to be encrypted.

The recipient will receive email with a link to the message stored on outlook.office365.com.  When the recipient wishes to read the message they will need to either authenticate with SSO for their email service or choose to receive a one time passcode.  Once authenticated, the message will be displayed.

Receiving an encrypted message from a STLT that uses O365 will be similar.  Other email platforms, such as Gmail, have a similar procedure.

**Comment by snesm** [comment]
@chris-kuryak I question whether we need to reproduce the storage functionality of Keybase at all.  There is no documented direct link between Keybase and our implementation, which leaves only a question about DR.

There are several documents that need to be updated to remove references to Keybase.

**Comment by chris-kuryak** [comment]
Sounds like we have confirmed that official guidance is to use encrypted emails when sharing secrets outside of the CDC environment.

Need to identify next steps for:
1. Removing references to Keybase
2. Confirming whether we need to reproduce the storage functionality of Keybase at all

Engagement needs to confirm we need to reproduce the storage functionality of Keybase moving forward?

**Comment by chris-kuryak** [comment]
@snesm We do not have the capability to manage access on documents in our Sharepoint site. Any guidance?

cc: @MikaelahD13 @MikaelahD13 @pstonebu
