### ISSUE TITLE
BUG: frontend-ci workflow's build-vars action requires pull request read permissions 

### ISSUE THREAD

**Issue by jpandersen87** [CDCgov/prime-reportstream#15124]
According to `dorny/paths-filter`'s documentation, it requires pull request read permissions to properly read changed files from the base branch within a pull request context. This may be the cause of erroneous skips that have occurred.

# Acceptance Criteria
- [ ] pull request read granted to `build-vars` step action for `frontend-ci` workflow

**Comment by chris-kuryak** [comment]
@jpandersen87 What is a good estimate for this ticket? Can you fill it in?

**Comment by jpandersen87** [comment]
According to devops, this permission is given by default and does not need to be explicitly defined. The cause of the bug causing frontend_ci to skip is still unknown.
