### ISSUE TITLE
NM - Result File Name Changes

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#15157]
## Problem statement

" It looks like we have started to receive files that do not adhere to the conventional file naming. Here are some examples…

covid-19-7fb3d14a-bfc6-485a-b245-e22af307d336-20240630232501.hl7

covid-19-e27662b4-92e9-4280-832c-ae9d110f478f-20240628152506.hl7

covid-19-0c974780-3383-4337-be7a-29571a027549-20240627212515.hl7

It appears that some came in on 6/28, 6/30, 7/1-7/8."

## What you need to know

Communication found in ReportStream Inbox:

" Please also confirm the following settings: 
Quality Filters Default quality filters 
Secondary receiver: gets all reports in CSV format available to download through ReportStream 
MSH-3: CDC PRIME - Atlanta, Georgia (Dekalb)^2.16.840.1.114222.4.1.237821^ISO 
MSH-5: NMDOH^2.16.840.1.113883.3.5364^ISO 
MSH-6: NMDOH^2.16.840.1.113883.3.5364^ISO 
PID-10: If Unknown set to blank 
Suppress HL7 fields: OBX-17-1 
Truncate HD Namespace Ids: True 
**File name format: cdcprime_elr_p_{created date}.hl7** 
Format: HL7 
Transport: SFTP 
SFTP Server: sftp.syncronys.org 
Path: ./incoming/ELR/ 
Batch messages – 12 times per day "

## Acceptance criteria

Verify file name format for NM/Syncronys

## To do

Correct and resend any errors.

**Comment by chris-kuryak** [comment]
@victor-chaparro is looking into it with the Platform team

**Comment by chris-kuryak** [comment]
Platform has a ticket to fix this #15164

**Comment by chris-kuryak** [comment]
@victor-chaparro to check if this is working now

**Comment by chris-kuryak** [comment]
@TaneaY @Jcavallo7 
The issue has been corrected since July 16.

Questions:
1. Are they receiving the correct filenames now?
2. If so, would they like us to resend the messages that had filenames that did not match their settings, or is there no more action needed here?

**Comment by Jcavallo7** [comment]
Follow up email sent to the user.

**Comment by TaneaY** [comment]
Follow up was received ticket resolved.

Hello Juan,

I triple checked and have not seen anymore come in in the last week. I think we a re good now. If any do come in I will let you know.

Thank you for working on this!
