### ISSUE TITLE
Document Queries From Product Requirements Document

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#15154]
### User Story
As a ReportStream support engineer,
I want to understand how to query Azure Events,
so that I can create my own queries to help troubleshoot future issues

### Description/Use Case
The [Internal Message Monitoring PRD](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engineering/Design/SRD/Internal%20Message%20Monitoring%20(PRD-SRD).docx?d=wa8c48baa234448a194bb993f8becd90f&csf=1&web=1&e=XOl6mv) details TWO use cases that should be addressed by querying Azure Events (**1.2.1** and **1.2.2**. 1.2.3 is out of scope). We should implement sample queries that address these use cases. For example, create the following queries:
- Give me a list of all messages that did not get sent anywhere that had a patient living in `X` state
- Give me a list of all messages that got filtered out by `X` state. I want to see which filters failed.
- Give me the original submitted report and the index of the item in that report for all items that got filtered out by receiver filters for `X` state so that I can easily identify which messages need to be resent through the pipeline after I fix an error with the receiver filters

### Acceptance Criteria
- [ ] Queries related to 1.2.1 and 1.2.2 tested and documented in the Azure Events document in the repo

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/15154?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
