### ISSUE TITLE
NY Resends due to Certificate issue

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#15186]
## Problem statement

NY Certificate expired on 6/1/24 at 00:00:00 EST. New Certificate updated on 7/15/24 1:00 PM EST. All reports sent to NY between that timeframe will need to be resent.

## What you need to know
All reports are in the "send" azure folder for receivers NY-PHD.elr and NY-PHD-full-elr. The requeue cli command can be used to retrigger these to go to NY.

curl -X POST -H "content-length:0" -H "x-functions-key:<SECRET>" "https://prime.cdc.gov/api/requeue/send?reportId=<reportId>&receiver=<receiver-fullname>"

the secret you have to get from azure it in the function-app->functions-requeue. The reportId is the reportid of the report that needs to be sent and the receiver-fullname will be the org+receivername of the receiver that the reportid is associated with (ex ny-phd.fullelr or ny-phd.elr)
11:05
so first thing would be to find all report ids for that timeframe that got sent to ny-phd.fullelr and ny-phd-elr, then use the command to resend those report ids

**Comment by JessicaWNava** [comment]
Verified in Metabase that all 65 resent.

**Comment by JessicaWNava** [comment]
Confirmed by @victor-chaparro via screenshots I sent him on Slack
