### ISSUE TITLE
Wire-framing and mockups for Message Testing Automation MVP

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15184]
## Acceptance criteria

-   [x] Draft initial mock-ups of the UI.
-   [x] Gather feedback from product and engineering on the UI mock-ups
-   [x] Sync with BE engineering on wireframes and develop list of dependencies/potential issues

**Comment by jillian-hammer** [comment]
where can I find the `list of dependencies/potential issues` documented? @jakefishbein-navapbc
