### ISSUE TITLE
Begin updating documentation of Design/Content processes 

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15193]
## Problem statement
We have not revisited clear design processes, particularly for feature/product development, since the team restructure last year. We need to norm and document processes to deliver consistently and effectively.

## What you need to know

-[Workshop mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1720644369460/022c7309f8431b1e46874d3603ea39064823e5fa?sender=uc55a7af3b66977fba12f5528)

## Acceptance criteria

- [x] Updated process drafted and initial artifacts created as possible
- [x] Follow-on ticket and ACs created as needed, linked as blocked by this ticket

**Comment by audreykwr** [comment]
- Cleaning up mural of refined/more detailed process by end of sprint
- Will align with Chris on product related follow on work and Jillian on broader design team follow on work
- Change comms template and content handoff docs refined and will be attached to mural process along with previously created resources like governance and style
- Two new potential resources to support the process and refining any existing resources will be incorporated into governance evaluation also scoped for next sprint
-

**Comment by chris-kuryak** [comment]
@audreykwr Can you create the expected follow-on tickets for this work based on your existing knowledge and we can review and refine later today?

**Comment by audreykwr** [comment]
Will do
