### ISSUE TITLE
Refine Interest and Intake process for new Senders

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15192]
## Problem statement
From #14997, it was determined that the next subject to work on would be refining the interest and intake process for new senders.

## What you need to know

- [Mural process draft space](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1707937586104/f6b20f0e363788e686ff1077f045fb14b06579c7?sender=uc55a7af3b66977fba12f5528)

## Acceptance criteria

- [x] Gather feedback from engineering on existing process
- [x] Align with Glenn on feedback from engineering and determine next actions
- [x] Align with product
- [x] Develop list of improvements/actions that we should take later in the quarter

## Actions to take
- [ ]

**Comment by audreykwr** [comment]
Input from eng gathered. Reviewing outstanding questions with Glenn today. Will pull together summary by end of sprint.
