### ISSUE TITLE
Document all contact and comms with TX HIV organizations

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15196]
## Problem statement
The Texas HIV Health Equity pilot involves attempting to contact many organizations. We need to keep track of those contacts and organizations. We need visibility into all of the existing conversations and next steps in one place for ease of tracking.

## What you need to know
- Existing HIV Sender contact document: 

## Acceptance criteria
- [x] All potential Texas HIV Health Equity pilot orgs that have been contacted (by RS or SR) are documented
- [x] The latest interaction with those orgs is documented
- [x] The next steps with those interactions is documented
- [x] Document (or link to existing document) the latest information/notes from SR on the two blood banks they have reached out to
- [x] Document (or link to existing document) of contact attempts and next steps with CSL plasma

**Comment by jakefishbein-navapbc** [comment]
Document has been updated with all contact STLTs. Next step is to link notes from calls and next steps for each.

**Comment by jakefishbein-navapbc** [comment]
[Link to document](https://cdc.sharepoint.com/teams/ReportStream/_layouts/15/doc.aspx?sourcedoc={a6a8bd94-e235-4d6c-a3f6-92378fcf76de}&action=edit)
