### ISSUE TITLE
Execute recurring user comms and measure

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15190]
## Problem statement
TBD

## What you need to know

- Initial Receiver List:
  - 
- Send date to initial list: TBD next sprint
- Send date to remaining list: TBD next sprint

## Acceptance criteria
- [x] Perform internal test with internal stakeholders and integrate feedback

**Comment by audreykwr** [comment]
Internal test sent. Will need to discuss if we want to split the external user send into another ticket, since this will not happen until I am back from PTO
