### ISSUE TITLE
Resent NY and RI failed messages

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15204]
## Problem statement
James indicated that the NY and RI issue on the UP was not fixed until July 15th at 11:15PST.

## What you need to know

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] Resend all necessary messages through SimpleReport to NY and RI
- [ ] Confirm all messages send correctly from RS to NY and RI

**Comment by GilmoreA6** [comment]
Simple Report has resent these up until  7/7/24. We will need to ask them to resend from 7/7 to 7/15 10:00 AM PST for NY as we discovered the setting was still broken
