### ISSUE TITLE
WY - Last Mile Failures 7/17/24

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#15219]
## Problem statement

ReportStream shows Wyoming has a downed connection since 7/15/24, and last mile failures from 7/17/24 from times: 4:25am, 6:26am, and 8:36am.

## What you need to know

State of Wyoming has multiple failed submissions.

## Acceptance criteria

- [ ] Reconnect successfully to WY
- [ ] Resend necessary messages

## To do

Establish reconnection and resubmit failures.

**Comment by Jcavallo7** [comment]
*update*

Another last mile failure at 7/17/24 for 10:18am

**Comment by Jcavallo7** [comment]
*update*

Another Last Mile Failure at 7/18/24 4:23am

**Comment by MikaelahD13** [comment]
@victor-chaparro may you please take a look at this and provide some guidance on what steps need to happen next?

**Comment by Jcavallo7** [comment]
*update*

Another failure on 7/19/24 6:21am

**Comment by oslynn** [comment]
Notified Cori Herzberger<cori.herzberger@wyo.gov> and Cody.

Dear: Cody Loveland,
My name is OTT SATHNGAM. I am a ReportStream integration engineer. ReportStream has been trying to send report of COVID-19 to WY (host: sftp-west.inductivehealth.com) and keep failing since 7/17/2024.
Is the key pair changed or expired? Would you please let me know and notify INDUCTIVEHEALTH to correct the issue?
Very respectfully
-Ott Sathngam
CDC ReportStream Engineer
Attendee panel closed

**Comment by Jcavallo7** [comment]
*update*
One more last mile failure at 7/22/24 at 4:36am

**Comment by Jcavallo7** [comment]
*update*

Another 2 more on 7/24/24, 8:34am, 10:38am.

**Comment by TaneaY** [comment]
Engagement working with WY to resolve no failures reported today. Will reopen support ticket if needed. 
<img width="1246" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEFPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0b09031f7ee81ad4c98a42f51949d4da7130a9b/image.png" alt="image.png" />

**Comment by oslynn** [comment]
Got new SFTP information from WY.
<img width="1048" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdSQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c614bb159e21144608af378b371ddb7851adf1bf/image.png" alt="image.png" />

**Comment by oslynn** [comment]
Requested to whitelist the new SFTP host with this ticket: https://app.zenhub.com/workspaces/prime-devops-606cb208a8c112000fd48349/issues/gh/cdcgov/prime-devops/135

**Comment by oslynn** [comment]
Resent all messages via localhost for now.  Therefore, they would still get messages while we are waiting for whitelisting.

**Comment by chris-kuryak** [comment]
Waiting on CDC whitelist

**Comment by oslynn** [comment]
It is CDC whitelisted.
[Uploading... image.png]

**Comment by oslynn** [comment]
<img width="1180" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNElyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3bef277e891fd790670a185eebc3b4321e1475e/image.png" alt="image.png" />
