### ISSUE TITLE
Implement smoke test user flow for Daily Data

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-reportstream#15211]
## Problem statement

Since Daily Data Detail page relies on a reportId we need to create an e2e test that mimics a user flow when running our smoke test.

## What you need to know

 We need to select a Covid pipeline receiver in order to ensure that the Report details lists facility data.
 As an admin, select the ignore org and navigate to the Daily Data page.

- UP receiver: ignore.FULL_ELR
- CP receiver: ignore.CSV
- ELIMS receiver: ignore.ELR_ELIMS
 
## Acceptance criteria

For a COVID pipeline receiver:
- [x] Test the details page contains the Facilities table headers
- [x] Clicking on the ReportId will open the Daily Data Details page
- [x] Test the details page contains the reportId that was clicked on

For a Universal pipeline receiver:
- [x] Clicking on the ReportId will open the Daily Data Details page 
- [x] Test the details page contains the reportId that was clicked on
- [ ] First record downloads when filename clicked
- [ ] Downloaded filename matches filename shown in Filename column

For ELIMS receiver:
- [x] Clicking on the ReportId will open the Daily Data Details page 
- [x] Test the details page contains the reportId that was clicked on

For any receiver:
- [x] The receiver filters return the specified data in the table
- [x] The date filters return the specified data in the table
- [x]  Retrieve first record in the table and search by ReportID and is the only result displayed in the table after search
- [x]  Retrieve first record in the table and search by Filename and is the only result displayed in the table after search
- [x]  Test the search "Reset" button to ensure it clears all filters and refreshes the table
- [x]  Test the filter "Reset" button to ensure it clears all filters and refreshes the table

- [x] Add to readme - we would test all happy path scenarios in public facing pages and all happy path scenarios for admins in auth pages

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
Will carry over to next sprint
