### ISSUE TITLE
Get baseline measurement of message testing process

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15225]
## Problem statement
To quantifiably measure future improvements, we need to get a baseline measurement for how long it takes engineers to accomplish this task now.

## What you need to know
- START: Begin creating/identifying test message to use
- FINISH: Identified any issues with Receiver/Sender settings or that no issues exist

## Acceptance criteria
- [ ] Record one time (in minutes) in a comment of this ticket of testing a message START to FINISH:
  - [ ] Victor
  - [x] Lucero
  - [x] Ott

**Comment by oslynn** [comment]
I worked on IL sample test messages and it took me about 12 hrs from start-to-finish (sent to IL for validation)

**Comment by chris-kuryak** [comment]
Ott update: 4 hours

**Comment by lucero-v** [comment]
- Idaho: took me ~3hrs, most of the time was spent identifying the issues.
- Iowa: took me 45 minutes - no issues

**Comment by oslynn** [comment]
I measured with IL - it took me about 1 hr - not man issue.
