### ISSUE TITLE
Whitelist UCSD and CA Lab for production pilot

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15227]
## Problem statement
The production pilot for ETOR newborn screening will route production data. As such, we need to ensure all parties involved are whitelisted in staging and production before we migrate any connections to production.

## What you need to know

Flow of data:
- Flexion SFTP; data from CA PHL (SENDER) ->  
- Flexion TI (INTERMEDIARY) ->  
- UCSD; EPIC (RECEIVER) 

## Acceptance criteria
- [ ] Sender - Flexion SFTP (data from CA PHL) whitelisted in staging and production
- [ ] Sender and Receiver - Flexion TI whitelisted in staging and production
- [ ] Receiver - UCSD; EPIC whitelisted in staging and production

**Comment by oslynn** [comment]
We may not need this ticket.  I connection in staging.  It looks like it is good.
<img width="979" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNndCQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d709264b068b6f86fe24f6de38675707df2dd4c0/image.png" alt="image.png" />

**Comment by oslynn** [comment]
We don't need to whitelisted the https://
