### ISSUE TITLE
Support Generating an Empty Report in Convert Step

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#15223]
# User Story
As an RS developer, I would like to be able to generate an empty report so that lineages work correctly.

# Description/Use Case
Currently, the code only support generating an empty report as part of sending something to receiver (i.e. they're on batch schedule and always want a report even if there are no items). However, the convert step also needs to be able to generate an empty report in the following situations:
- the submitted report was completely empty
- the hl7 message was unparseable

The empty report must be generated because otherwise the report lineage doesn't work and the action logs from the convert step are not visible.

# Dev Notes
ActionHistory.trackGeneratedEmptyReport already exists and overload likely can get created to support this. Another option is to remove exceptions that are based on assumptions that a report cannot have empty item lineages.

Search for ticket number in code, there is a comment.

# Acceptance Criteria
- [ ] Convert step updated to generate an empty report and report lineage (no item lineage) when certain conditions are met

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/15223?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
