### ISSUE TITLE
Create Message Monitoring research plan

### ISSUE THREAD

**Issue by jsutantio** [CDCgov/prime-reportstream#15302]
**Context**
ReportStream is investigating what information is desired and necessary, from and external usage perspective. Research must be done in order to identify the use cases, data types, methods, and frequency of which our external users would like to gain and use information. This research plan aims to document the specifics of how we're going to conduct research (primary and secondary) and be the repository for notes and findings from individual sources.

**Links**
- [Research plan document](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/02_Research/External%20Message%20Monitoring/External%20Message%20Monitoring%20-%20Research%20plan%20and%20notes.docx?d=wecf39d0b8f1d42c2aa7c79914aff2c36&csf=1&web=1&e=zq5T7r)

**Acceptance Criteria**
- [x] Outline questions specific to each audience and method of asking
- [x] Outline structure for note-taking/ capturing re-mined content
- [x] Gain approval from design lead

**Comment by jillian-hammer** [comment]
reviewed, looks good to me! approved @jsutantio
