### ISSUE TITLE
BUG - Fix Submissions Details Page and Title

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15310]
## Problem statement
The Submissions Details Page is not loading

## How to reproduce
1. Log in as Prime Admin to ReportStream.CDC.gov
2. Set yourself as a sending organization
3. Go to Submissions History Page
4. Click on a Submission to open Submission Details Page
5. Blue spinning wheel never stops loading
6. Eventually, an error message is shown:

<img width="1163" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEVBQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b9785a83e0d7d0e7d20b17816cce496a1f1f744/Screenshot%202024-07-23%20at%2010.40.41%E2%80%AFAM.png" alt="Screenshot 2024-07-23 at 10.40.41 AM.png" />

- Example Page = https://reportstream.cdc.gov/submissions/4f6257b3-b6ac-4bb9-aa20-b01422b2a6c0

## Acceptance criteria

- [x] Submissions Details Page loads properly
- [x] Ensure Submissions Details Page title in the browser is "Submission History" not "Last Mile Failures"

**Comment by penny-lischer** [comment]
I noticed that an org was not selected. Is this expected behavior? Meaning, we usually have an org selected before navigating to Daily Data or Submissions pages.

**Comment by chris-kuryak** [comment]
@penny-lischer I don't think I know what you mean here? I did set myself as a sending org before going to the submissions page.

**Comment by chris-kuryak** [comment]
Seems to be a backend issue. 
Will wait until deployment finishes, then we will check to see if it is still broken.

**Comment by chris-kuryak** [comment]
Victor taking to the Engineering channel to see if there is any consensus on the issue

**Comment by chris-kuryak** [comment]
We think it's an index issue

**Comment by chris-kuryak** [comment]
Per victor, working!
