### ISSUE TITLE
AK - File Resubmission

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#15336]
## Problem statement

" AK received 2 recent messages through their feed that caused a failure in the system. We have the message ID’s as well as the accession and the issue that was encountered with the message. We are wondering if you can review, correct and resubmit the message perhaps when you have a chance.

Message ID: 7423198

Accession#: 7423198

OBX-5 had the following information populated which is incorrect values for a snomed code and appeared to have Linefeeds in it as well as indicated with the <LF>

SARS-CoV-2: Negative<LF>
COVID 2 (0), Centennial<LF>
Lot: M807532<LF>
Operator: admin<LF>

<LF>

SARS-CoV-2 RdRp gene NAA+probe Ql (Resp): Negative^Invalid result^SCT

Thank you,

Jason Suchon" 

## What you need to know

error occured on 7/12/2024

Message ID: 7423198

Accession#: 7423198

OBX-5 had the following information populated which is incorrect values for a snomed code and appeared to have Linefeeds in it as well as indicated with the <LF>

SARS-CoV-2: Negative<LF>
COVID 2 (0), Centennial<LF>
Lot: M807532<LF>
Operator: admin<LF>

<LF>

SARS-CoV-2 RdRp gene NAA+probe Ql (Resp): Negative^Invalid result^SCT

## Acceptance criteria

- [ ] ...

## To do

- Resubmit files to Alaska

**Comment by Jcavallo7** [comment]
@GilmoreA6 yes unfortunately, and added a screenshot of the email as well <img width="1111" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm9XQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1eebb50cc2de98d0d9537febbd7bf752832d0edc/image.png" alt="image.png" />

**Comment by Jcavallo7** [comment]
@GilmoreA6 user came back with update
<img width="1157" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHdkQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--736eab47930483a8f8563f1c8ce041969c4616f3/image.png" alt="image.png" />

**Comment by GilmoreA6** [comment]
I tracked down the report. It appears the issue is that we received a CSV file from the sender where the value in the test_result column contained special characters which resulted in a gabled OBX-5 field when ultimately converted into HL7. It also appears that it was a single message sent twice. Given the unclear nature of what OBX-5 was supposed to contain we will reach out to the sender to resend the message if possible.

**Comment by GilmoreA6** [comment]
Waiting for sender to re-submit. Asked SR in slack to reach out to sender for re-submission

**Comment by Jcavallo7** [comment]
update requested, re-forwarded previous thread, 

*from user* "Good Morning James,

Haven’t seen an update in regards to this lately. Can you please let us know when that is successfully resubmitted so we can review and verify on our end.

Thank you,

Jason Suchon"

<img width="1183" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDFaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95926c87fb8b0a2f5eed8fa0761b8c47567b3c58/image.png" alt="image.png" />

**Comment by rnz6** [comment]
<img width="1076" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmVLQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b69b5e0f8aede491d54eb2ab6b1853aefd5a7445/image.png" alt="image.png" />

**Comment by chris-kuryak** [comment]
@GilmoreA6 See above, is there any info you have to answer the latest comment above from Jason Suchon?

**Comment by GilmoreA6** [comment]
@chris-kuryak We discussed this with SR at the sync on Thursday. Jayna is going to reach out again to the sender

**Comment by Jcavallo7** [comment]
hello all, Jason came back asking for a follow up, attaching screenshot for visibility, triaging and forwarding to Jayna so she is able to reach out to sender.<img width="1165" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUd1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b092671c1c4e9586c561dcebe7a0467c52c09bb1/image.png" alt="image.png" />

**Comment by GilmoreA6** [comment]
SimpleReport has seent a second email sent to sender asking to resend the affected report

**Comment by TaneaY** [comment]
Confirmation of resolution recieved...see below
<img width="840" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlhVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b15106ce119ab46ff75ff32157b68bff69ebc80c/image.png" alt="image.png" />
