### ISSUE TITLE
Implement smoke test user flow for Org Admin page

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-reportstream#15331]
## Problem statement

We need to create an e2e test that mimics a user flow when running our Organization Admin smoke test.

## What you need to know

 As an admin, navigate to the Organization Settings page. https://reportstream.cdc.gov/admin/settings
Currently we are depending on mock data and refer to mock data variables .

## Acceptance criteria

- [x]  API does not return an error
- [x]  Data is displayed in the table
- [x]  "Set" button updates the navigation as a user of that organization (Ignore organization can be used)

**Comment by chris-kuryak** [comment]
The filter and "set" button is already being tested through the other E2E tests that set the Ignore org
