### ISSUE TITLE
Remove unused catchall mappings

### ISSUE THREAD

**Issue by JFisk42** [CDCgov/prime-reportstream#15342]
### User Story
As a ReportStream Developer
I want to remove unused mappings
so that there aren't a bunch of files hanging around being all confusing and such.

### Description/Use Case
During the catchall migration ([PR](https://github.com/CDCgov/prime-reportstream/pull/13762)) mappings were moved over without having time to investigate which mappings are not being used currently. There are a number of mappings which were ported over and can safely be deleted. Part of this task will be the investigation to verify which mappings can be deleted without impacting users.

### Risks/Impacts/Considerations
If any mappings are deleted which are in use, this would cause errors for any users posting reports that utilize those mappings.

### Dev Notes
There are three main folders which are suspected to mostly/entirely contain unused mappings in the catchall/hl7/ path. [Datatype](https://github.com/CDCgov/prime-reportstream/tree/master/prime-router/metadata/HL7/catchall/hl7/datatype), [Resources](https://github.com/CDCgov/prime-reportstream/tree/master/prime-router/metadata/HL7/catchall/hl7/resource), and [Secondary](https://github.com/CDCgov/prime-reportstream/tree/master/prime-router/metadata/HL7/catchall/hl7/secondary). 

Consideration: 
Many of these mappings files reference other mappings. These will have to be traversed to ensure that all removed mappings are only being referenced by other removed mappings.

### Acceptance Criteria
Unused mappings in the `prime-reportstream/prime-router/metadata/HL7/catchall/hl7/` directory are deleted.

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/15342?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
