### ISSUE TITLE
Add a required Vulnerability Disclosure Policy link to the footer of the reportstream.cdc.gov site

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#1535]
**Is your feature request related to a problem? Please describe.**
The HHS is mandating a new link in all HHS sites including reportstream.cdc.gov. The link is to the HHS Vulnerability Disclosure Policy. https://www.hhs.gov/vulnerability-disclosure-policy/index.html. 

**Describe the solution you'd like**
The link is added to the footer of ReportStream's content page. 

**Additional context**
Go to hhs.gov to see an example of the link.

**Comment by RickHawesUSDS** [comment]
@drew-usds

**Comment by RickHawesUSDS** [comment]
Also, once this is fixed, we need to communicate back to the CDC security team.

**Comment by drew-usds** [comment]
Fixed in PR #1660

**Comment by RickHawesUSDS** [comment]
Confirmed deployed.
