### ISSUE TITLE
Review NIH Wrapper for ReportStream integration from Sender perspective

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15366]
## Problem statement
NIH has created a wrapper that will be used to integrate OTC MARS senders into ReportStream easier.

As a OTC sender reporting through the NIH wrapper, I want to know what tasks I will need to do in order to successfully send data through RS to a public health entity so that I can meet my reporting requirements.

## What you need to know

- NIH Wrapper: https://github.com/NIBIB
- Connect with Victor or Arnej for more information
- From NIH / MARS initiative:
  - radx-mars-lib - the base library with domain models, interfaces, etc. Common code shared by all hubs.
  - reportstream-mars-lib - the library to be used when communicating with ReportStream
  - aims-mars-lib - the library to be used when communicating with APHL AIMS
  - radx-mars-demo - the library that shows you how to use all of the above. Also includes a debug "hub" and all of the important documentation.

## Acceptance criteria

- [x] Document the steps, documentation, or actions required by a sender of OTC data to successfully connect and send data through the NIH wrapper to ReportStream

**Comment by chris-kuryak** [comment]
Victor to follow-up with Andy Meadows

**Comment by chris-kuryak** [comment]
Andy Meadows responded 11/4 that the wrapper is now in production.
@victor-chaparro Does this now unblock this ticket?

**Comment by victor-chaparro** [comment]
NIH needed to fix some bugs on the wrapper. They have finished making those changes and will be able to start documentation next sprint.

**Comment by chris-kuryak** [comment]
Spillover: Engr Tech Lead capacity

**Comment by victor-chaparro** [comment]
Documentation can be found here: https://docs.google.com/document/d/1BMPsSJOffuNhCaxDP5dBbUFFZAG1He1-El-4I8F6cc8/edit?tab=t.0
