### ISSUE TITLE
Create tickets for HL7v2->FHIR->HL7v2 ADT mappings

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#15388]
### User Story

As a sender and receiver of HL7v2 ADT messages,
I want ReportStream to process these messages losslessly,
So I can send/receive this data.

### Description/Use Case

The following message types have been identified as being required to support the syndromic surveillance use case:

- *HL7 EDI v2.5.1 ADT_A04 (emergency department admissions and Inpatient admissions)
- *HL7 EDI v2.5.1 ADT_A08 (emergency department patient updates and inpatient updates)
- HL7 EDI v2.5.1 ADT_A01 (emergency department patient transfers to inpatient beds)
- *HL7 EDI v2.5.1 ADT_A03 (emergency department discharges and inpatient discharges)
- *HL7 EDI v2.5.1 ADT_R01 (laboratory test results associated with emergency department patients and inpatients)

> WARNING: The messages marked with `*` do NOT have mappings defined in the mapping inventory, but if their segments mostly align with ADT_A01 we should be able to figure out how to map them. 

This ticket shall investigate these message types and come up with an implementation order and strategy, ultimately creating tickets for them that the team can follow. **When the tickets are all completed, ReportStream should be able to receiver and deliver any of the above HL7v2 message types and translate them from HL7v2 to FHIR and back to HL7v2 without dropping data.**

### Dev Notes

Research that may prove helpful can be found here: https://cdc.sharepoint.com/:f:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/02_Research/Syndromic%20Surveillance?csf=1&web=1&e=7ejbVU

### Acceptance Criteria

- [ ] Implementation tickets created

**Comment by dylansmith-Nava** [comment]
I'll add the [Syndromic Surveillance Mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1712766404856/3a591ef9d68c3d805b29ceb5450195fb22a847c2?sender=ufb3824a0e63fafb0304f5774) as well.

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/15388?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
