### ISSUE TITLE
Capture Sender Intake Data & TOS Agreement

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#1539]
## Problem statement

As a Sender, I would like to gain access to the CSV upload feature so that I can begin using it.

As the CDC, we require Senders to agree to our Terms of Service before they are allowed to use the features in ReportStream so that we can have a record of their agreement for legal purposes.

## What you need to know

- https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=1150%3A470

## Acceptance criteria

- When I
    - Navigate to ReportStream (either logged in or not)
    - **Question: will the page be accessible to the general public or ONLY to senders who have a URL provided to them by the Sender Automation team???????**
- Then I
    - Can view the Sender intake form and any of its supporting information
    - Can enter my information 
        - Title (optional)
        - First Name (required)
        - Last Name (required)
        - Email (required)
        - State or Territory (required)
        - Organization Name (required)
        - CLIA (required)
    - Can agree to the Terms of Service 
    - Can submit my information and agreement
        - Constraint: I cannot submit my information until all required fields have a value and I have agreed to the TOS

   
## To do

- [ ] Dev: Add form 
- [ ] Dev: Save data to DB on submit

**Comment by loripusey** [comment]
@BerniXiongA6 Hi Berni, this story is to cover any sender upload instructions that we may want to add to ReportStream; would you be the one that would create the content and its layout?  Would we want to also allow them to download the guide (receivers can do this with their guide)?

**Comment by BerniXiongA6** [comment]
@loripusey Hi Lori, yes I help out with the content that's client-facing (messaging that goes on the ReportStream website, in user or learner guides, sender/receiver email templates, etc.). The UX design and UI person on my team who is building out the ReportStream website pages and prototypes is @drew-usds . Drew and I currently work together on this for the receivers, and are aware we'll be expanding to senders as well. I'd be happy to sync up and discuss.
