### ISSUE TITLE
Message Testing Automation MVP - final design tasks

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15408]
## Acceptance criteria
-   [ ] Update service blueprint with relevant learnings
-   [ ] Update the [questions pool](https://docs.google.com/spreadsheets/d/1THH9Ekj5renvIwSpl-6SzzyUJ5tuNcH76l4GTiboQXE/edit#gid=0) with any questions that came up

**Comment by jakefishbein-navapbc** [comment]
Blueprint to update after development complete and feature is implemented.

**Comment by jillian-hammer** [comment]
we can wait until the feature is live and being used to update the service blueprint. so we can close this issue @chris-kuryak
