### ISSUE TITLE
Consent to be Listed on the Website as a Sender

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#1541]
## Problem statement

As the CDC, we would like to publicly list the names of our Senders & Receivers in presentations and on our web site so that we can encourage more organizations to do so.  We would like to get the organization's consent prior to listing their name so that we don't have any legal repercussions.

## What you need to know

- Need content wording and placement
- Question: do we also need this consent on the Receiver intake form?

## Acceptance criteria

- When I
    - Navigate to ReportStream (no need to log in)
    - Navigate to Sender intake form
- Then I
    - Can consent to allow the CDC to list the name of my organization in their presentations and on their web site as a user of ReportStream features 
        - Consent is not required to submit the form (we should verify this statement)
    - Can submit the intake form and the system saves my consent response
    
## To do

- [ ] Content: need wording
- [ ] Design: need placement
- [ ] Dev: need to add agreement to intake form and save response on submission

**Comment by loripusey** [comment]
@RickHawesUSDS Hi Richard, I heard you mention this the other day, can you provide some additional context for this? Is this something that needs to be done as part of the Sender intake form with their TOS agreement? Or is this just an idea at this point and not fully fleshed out?

**Comment by RickHawesUSDS** [comment]
We would like to publically state in our presentations and on our web site who are using our service, both senders and receivers. In general, it is a good practice to get some form agreement with these organizations. 

Ideally, this consent would be part of the TOS. So we didn't have to track two bits of information.

**Comment by loripusey** [comment]
@RickHawesUSDS I'm assuming that this consent (unlike the TOS) is not required in order to submit the intake form and use the ReportStream features, is that a correct assumption?

**Comment by loripusey** [comment]
@anshulkumar-usds @jlusds James & Anshul, is this functionality that needs to also be added to the Receiver intake form?

**Comment by jlusds** [comment]
I agree this would be nice to add to the intake form
