### ISSUE TITLE
North Dakota - UP Migration - Validate Test Data

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#15448]
### User Story:
As a developer, I want the [STLT] to validate test messages in staging, so that they can receive data in the format they expect.

### Link to Notes Document and Requirements: 

https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engagement/STLT%20and%20Sender%20Onboarding/North%20Dakota%20Onboarding%20Running%20Notes.docx?d=wee0d9a2a22de4cd5899425f1b146c767&csf=1&web=1&e=mdfTW4

### Description/Use Case
[STLT] is already receiving data from the covid pipeline they will be onboarded to the UP where they will be receiving data from SimpleReport including Covid, Flu and RSV. We need to make sure the message we generate from the UP passes the STLTs validation. We can use SimpleReport to submit test messages to the STLT.

### Dev Notes:

- [x] Upload the newly created receiver settings to Staging
- [x] Copy the receiver's secret key with the new receiver name in Azure's staging environment
- [x] Verify we can connect to the newly created receiver
- [x] Send a test message through Simple Report and make sure it gets routed to the STLT
- [ ] Send test messages according to the STLT needs

### Acceptance Criteria 
- [ ] Created and sent data using Simple Report
- [ ] Confirmed with STLT that data passes validation

**Comment by oslynn** [comment]
- Integration test: Past
 - Tested locally with following conditions and got 6 messages result
    ConditionFilter:  
          RSV: 55735004 (+), COVID: 840539006 (+), FLU (A or B by Antigen): 6142004 (+), FLU (A or B by Culture and Identification Method),: 541131000124102
    Flu A +  (LOINC = 85477-8, condition_code = 541131000124102)
    Flu A -  (LOINC = 85477-8, condition_code = 541131000124102)
    COVID-19 - (LOINC = 94558-4, condition_code = 840539006)
    COVID-19 + (LOINC = 94558-4, condition_code = 840539006)
    Flu B + (LOINC = 85478-6, condition_code = 541131000124102)
    Flu B - (LOINC = 85478-6, condition_code = 541131000124102)
    RSV + (LOINC = 85479-4, condition_code = 55735004)
    Multiplex messages: COVID-19 +, FLU A -, FLU B +, RSV +
    Multiplex messages: COVID-19 +, FLU A +, FLU B +

- Test in staging:

**Comment by oslynn** [comment]
<img width="1622" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnAvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ac769ca447e963cee310665eea6d2d19942c6ac/image.png" alt="image.png" />

**Comment by oslynn** [comment]
Done
