### ISSUE TITLE
Create mapping for HL7 CP -> FHIR extension -> HL7 CP

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#15490]
### User Story
As a user, I would like to have ADT data correctly mapped to FHIR and then back to HL7

### Description/Use Case
ADT contains the CP datatype but it does not having an entry in the mapping inventory so an extension will need to be created for it 

### Risks/Impacts/Considerations
- IN1.40 is a ST in 2.7.1

### Dev Notes
- See how [MOC](https://github.com/CDCgov/prime-reportstream/blob/93e350a7c23ec0e0263722eae7c2d90f13bf4f19/prime-router/metadata/HL7/catchall/hl7/datatypes/MOC/Extension.yml) was handled as an example
- IN1.40 is an CP

### Acceptance Criteria
- [ ] CP datatypes in an ADT_* message are mapped to an extension and then map into HL7 without any data loss

**Comment by MichaelEsuruoso** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/15490?planning-poker) with Zenhub @adegolier @arnejduranovic @david-navapbc @jack-h-wang @JFisk42 @kant777 @mkalish @thetaurean
