### ISSUE TITLE
Data not flowing to NM?

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1551]
I see two NM-DOH CSV reports that may not have gone to NM.  (I'm assuming we attempt to send csvs to NM)

I'm also seeing send_error actions related to NM.

81ff1dd1-29fd-470a-b66f-225bf0747e35
91 records
nm-doh.elr-csv
Thu, Jul 8, 2021, 13:15
CSV

76e1d315-4a45-4427-9a2b-fab365b67adb
109 records
nm-doh.elr-csv
Wed, Jul 7, 2021, 13:15
CSV

I haven't looked in detail.

**Comment by MauriceReeves-usds** [comment]
This was set up so they could download CSV from the download site. They're not using it. We can turn it off.

**Comment by jimduff-usds** [comment]
ok, there were also send_errors to NM and to a bunch of other states (FL, ND, OH), over the last few days.  The other states seemed like the retry mechanism was solving things; NM was the only case where I saw files still in the "needs investigation" query.  But I only looked very quickly.

**Comment by jlusds** [comment]
Was this resolved?
