### ISSUE TITLE
[BUG]: History endpoint intermediate overallStatus can be "Not Delivering" and then change later

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#15524]
## Describe the bug
`end2end_up` tests were failing during deployment when run against the staging environment because the history endpoint that the tests rely on were not showing that the tests were delivered where we expected them to be. In fact, in one case, the history endpoint showed an overall status of "Not Delivering" when a query of the customEvents showed the reports was correctly delivered. Manually hitting the history endpoint later showed expected results: overallStatus was "delivered" and the receivers were correct. 

TLDR; It seems like "not delivering" can sometimes be an "intermediary" result whereas it should be a final result. Meaning if a report is marked as "not delivering", then its status should not change at some later point in time.

## Impact on ReportStream
Senders, if using the history endpoint, may not get accurate information as to the real status of their submitted report and may lead to confusion.

## Steps to reproduce
Hard to reproduce since it relies on the processing speed of the report. It may be easier to comb through overallStatus calculation logic and identify the defect that way.

## Expected behavior
- "Not Delivering" should not be an intermediary status, only a final one.
- Create test that reproduces this issue

**Comment by adegolier** [comment]
I've run into this and it's easier to reproduce running against Staging.... Made a ticket (#15654), but closed as duplicate
