### ISSUE TITLE
[BUG] Fix slow load times for some receivers in Daily Data API call load time on Staging and Production

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15523]
## Problem statement
The daily data page is loading slowly on staging.

## What you need to know
- FE has identified that the query is returning quickly, so the slow page load is likely a FE or BE implementation issue.
- Steps to reproduce:
  - Login to staging
  - Dupe as 'Ignore' org
  - Navigate to Daily Data
  - Takes 30+ seconds to load page
- Similar response has been seen in CA on Production:
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelZVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2fa0be0f688b80028ea060149f69bad43333f79e/image.png" alt="image.png" />

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek5VQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02830ff51f15c06b7da371625c281c2105f0f246/image.png" alt="image.png" />

## Acceptance criteria
- [ ] Daily Data page loads within 5 seconds for an average API call on staging and production

**Comment by etanb** [comment]
@penny-lischer @chris-kuryak I've tested both locally and in production, and I'm not seeing load times over 3 seconds. Can y'all reproduce?

**Comment by chris-kuryak** [comment]
Yes, this is still happening for larger receivers like CA and FL

**Comment by chris-kuryak** [comment]
We have identified that we think this is a backend issue, not a front-end issue.

**Comment by chris-kuryak** [comment]
Since FE team owns the API, they are going to look into it first
