### ISSUE TITLE
Health Equity Quarterly Report

### ISSUE THREAD

**Issue by jakefishbein-navapbc** [CDCgov/prime-reportstream#15570]
## Problem statement
Approaching the endd of the quarter of work for the Health Equity Pilot with Texas, we wanted to measure and consolidate learnings.

## What you need to know
- Initiative Goals and Metrics: https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BE17F23C4-8348-4FBD-B4D8-DC099DF609BD%7D&file=ReportStream%20Health%20Equity%20Initiative.docx&action=default&mobileredirect=true

## Acceptance criteria
- [ ] Below answers/content included in the existing [Initiative Document ](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BE17F23C4-8348-4FBD-B4D8-DC099DF609BD%7D&file=ReportStream%20Health%20Equity%20Initiative.docx&action=default&mobileredirect=true)
- [ ] All **Goals** reviewed and documented with the findings/outcomes
- [ ] Calculate and document **metrics** found in the Initiative Document
- [ ] Ensured all Pilot questions have been answered and link to the answers in the Initiative Document
- [ ] Recommendations for follow-on work based on findings
- [ ] Notify stakeholders (Jillian, Audrey, Chris, Glenn) async for review

**Comment by jakefishbein-navapbc** [comment]
Working [draft of report](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B25DB7228-C21A-40AA-80A3-35A001D43CDA%7D&file=Health%20Equity%20Pilot%20Initiative.docx&action=default&mobileredirect=true) ready for review. @jillian-hammer @chris-kuryak @GlennRGrieves

**Comment by jillian-hammer** [comment]
just completed my first review of the draft - thanks @jakefishbein-navapbc!

**Comment by jakefishbein-navapbc** [comment]
Final draft added to the [Health Equity Initiative document](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BE17F23C4-8348-4FBD-B4D8-DC099DF609BD%7D&file=ReportStream%20Health%20Equity%20Initiative.docx&action=default&mobileredirect=true) and submitted for review.
