### ISSUE TITLE
Execute recurring user comms and measure

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15585]
## Problem statement
Now that we have tested internally, we want to send this communication out to our first round of users.

## What you need to know

Initial Receiver List:

- Send date to initial list: Tues, Sept 3
- Send date to remaining list: Fri, Sept 6

## Acceptance criteria
- [x] Create separate unsubscribe list
- [x] Send email to initial list from #15189
- [x] Send email to remaining users
- [x] Monitor shared inbox in case of responses
- [x] Measure statistics/impact
- [x] Review with Product to determine next steps
- [x] Define a short term process of how to manage and add users to SendGrid email list
- [x] Create documentation on how to manage the SendGrid and users

**Comment by audreykwr** [comment]
Made a [video ](https://cdc.sharepoint.com/:v:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/How%20to%20Create%20a%20Single%20Send%20for%20Monthly%20Updates.mp4?csf=1&web=1&e=s9fFIY)on creating the single send for monthly updates

**Comment by audreykwr** [comment]
[Video](https://cdc.sharepoint.com/:v:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Managing%20Users%20and%20Contact%20Lists%20in%20SendGrid%20%F0%9F%93%A7.mp4?csf=1&web=1&e=BM3SlB) for instructions on managing contacts
