### ISSUE TITLE
Enhance lineage assertions in integration tests

### ISSUE THREAD

**Issue by thetaurean** [CDCgov/prime-reportstream#15582]
### User Story
As a developer I want comprehensive tests so that I can catch any issues before they go to production.

### Description/Use Case
Many of the integration tests for `FHIRConverter`, `FHIRDestinationFilter`, `FHIRReceiverFilter`, and `FHIRTranslator` aren't checking the preceding lineage and/or the metadata on output `Report` objects. We should add these checks where it makes sense.

### Risks/Impacts/Considerations
This ticket originally only covered destination and receiver filters but has been expanded to cover all FHIR function integration tests.

### Dev Notes
These live in `FHIRConverterIntegrationTests.kt`, `FHIRDestinationFilterIntegrationTests.kt`, `FHIRReceiverFilterIntegrationTests.kt`, and `FHIRTranslatorIntegrationTests.kt`

This ticket got closed as a duplicate but contains helpful context for this ticket and all the AC there should be met here as well: https://github.com/CDCgov/prime-reportstream/issues/14349

### Acceptance Criteria
- `FhirDestinationFilterIntegrationTests`
  - [x] `Report` objects retrieved; relevant properties checked when report does not get routed anywhere
  - [x] `Report` object retrieved; contents and properties checked when report is routed
- `FhirReceiverFilterIntegrationTests`
  - [x] `Report` object retrieved; contents and properties checked when report does not get routed anywhere
- Verify lineages are adequately checked in `fetchChildReports`
  - [x] Double-check the lineage assertions for ItemLineage and ReportLineage
  - [x] Revisit usage (or lack of) in other integration tests (Convert and Translate) and ~~create tickets as needed~~ resolve

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/15582?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean

**Comment by thetaurean** [comment]
I have expanded the scope of this ticket and bumped the points from 2 to 3.
