### ISSUE TITLE
Update website News Page to include Landing Page with Individual story pages

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15592]
## Problem statement
Our news items were initially designed to be all on one page, but that does not create an ideal sharing experience. More people than we expected wanted to share our first news item, and we want to create a better experience for future articles.

This ticket is to implement the new News page design.

## What you need to know
- Design and content: [Figma working space](https://www.figma.com/design/86JATe4hOwPfihwwloM5b8/Blockframes?node-id=2117-1486&t=V1Q51uA7eEVX3s2L-1)

## Acceptance criteria
- [ ] News Landing page exists per design
- [ ] Individual News page(s) exists per design
- [ ] Review/Approval from Design and Content team

## To do
- [ ] Audrey and Jillian review this ticket

**Comment by jillian-hammer** [comment]
Audrey and I met and discussed proceed with implementing the News section as planned. that way, once the ETOR news item is approved (#14925) we still have somewhere to publish it. afterwards, we can talk more about a long-term strategy for the News section, including reusability of the Landing page UI for case studies. @chris-kuryak

**Comment by chris-kuryak** [comment]
After discussion with Jillian, News page will remain as is providing a space for the ETOR article when it gets published. But we will not continue with creating a new landing page. So closing this ticket.
