### ISSUE TITLE
Verify and Create API Key for Sender ca-phl.etor-nbs-results (CA DPH for ETOR NBS Results)

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#15595]
## Problem statement

We need to verify whether a sender has been created for the California Department of Public Health (CA DPH) for ETOR NBS results, specifically under the name ca-phl.etor-nbs-results. If the sender exists but no API key has been created, we need to create the API key and securely share it via Keybase.

## Acceptance criteria

- [x] Confirmation that the sender ca-phl.etor-nbs-results has been created and is configured correctly in staging.
- [x] Verification that the sender is in the correct environment (staging) with appropriate settings.
- [x] Creation of an API key if one does not already exist for the sender.
- [x] The API key, if created, must be securely shared via Keybase to the relevant stakeholders.
- [x] Documentation of the sender creation, API key creation, and sharing process, updated in relevant records.

 ## Information Needed

- [x] Access to the API management system to verify the existence of the sender ca-phl.etor-nbs-results.
- [x] Confirmation of the sender’s settings and environment (staging).
- [x] Credentials or permissions required to create a new API key if it doesn’t exist.
- [x] Keybase account details of the recipient(s) who need to receive the API key.

## To do

- [x] Verify Sender Creation
- [x] Create API Key (if not existing)
- [x] Share API Key
- [ ] Update Documentation:

**Comment by oslynn** [comment]
Done
