### ISSUE TITLE
Remove non-catchall mappings from HL7 -> FHIR mappings

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#15607]
### User Story

As a developer of HL7->FHIR Mappings,
I want to remove old mappings,
so that there is no confusion about what mappings are deprecated

### Description/Use Case

All mappings inside `prime-router/metadata/HL7` that are not in `prime-router/metadata/HL7/catchall` should be removed from the repository and failing tests should be investigated.

### Acceptance Criteria

- [ ] Old HL7->FHIR mappings deleted
    - [ ] `prime-router/metadata/HL7/datatypes` removed
    - [ ] `prime-router/metadata/HL7/v251-elr` removed

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/15607?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean
