### ISSUE TITLE
Add File Download testing to Daily Data smoke test user flow

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15612]
## Problem statement
Checking for File Download capability was removed from the previous ticket #15211. So we need to add that capability back in.

## What you need to know

 We need to select a Covid pipeline receiver in order to ensure that the Report details lists facility data.
 As an admin, select the ignore org and navigate to the Daily Data page.

- UP receiver: ignore.FULL_ELR
- CP receiver: ignore.CSV
- ELIMS receiver: ignore.ELR_ELIMS
 
## Acceptance criteria

For a Universal pipeline receiver:
- [ ] First record downloads when filename clicked
- [ ] Downloaded filename matches filename shown in Filename column

**Comment by penny-lischer** [comment]
Still not working. Reopening.

**Comment by chris-kuryak** [comment]
@etanb for awareness

**Comment by chris-kuryak** [comment]
@etanb Can you double check the acceptance criteria and check off the completed ones?
