### ISSUE TITLE
CA - LA County received messages with OBX Issues 8/14/24

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#15620]
## **Problem Statement**

The RS Support team received an email in the Support inbox from Los Angeles County Department of Public Health regarding OBX values that did not transmit correctly, mainly in CLIA-related fields.

## **What you need to know**

Email text follows:

> Hi Report Stream Partners,
> 
> LA County has identified two OBX segment issues related to adding CLIAs as suffixes to this segment. Below is a summary of the information:
> 
> 
> IRIS Lab Name
> 
> CMS Lab Name
> 
> CLIA
> 
> Issue
> 
> Report Count
> 
> Received Date
> 
> Prime Report Stream 0085 (ELR)    
> 
> Premiere Medical Center of Burbank, Inc.
> 
> 05D2002489
> 
> CLIA is missing the last digit in the OBX segment of the HL7 message
> 
> 18
> 
> 08/07/2024-08/12/2024
> 
> Prime Report Stream 0085 (ELR)    
> 
> First Care Medical Centers, LLC
> 
> 02D2091211
> 
> OBX segment not formatted correctly to include CLIA after facility name
> 
> 1
> 
> 08/12/2024
> 
> 
> Please let me know if you need any additional information to resolve this moving forward.

## **Acceptance Criteria**

- [ ] Resolve issue causing OBX segment changes.

## **To Do**

- Review files that were sent to LA County
- Determine cause of changes to OBX fields

## **Additional Comments**

When researching this issue, I found several Report IDs related to Premier Medical Center of Burbank that were transmitted during the specified timeframe. The total number of results included in those files exceeds the number of messages they stated had errors. When reviewing the result data in Metabase, all CLIA values appear to be intact. I can provide those Report IDs if needed.

**Comment by MikaelahD13** [comment]
@victor-chaparro, may you please provide guidance on this issue?

**Comment by victor-chaparro** [comment]
@wcollin89 @TaneaY @MikaelahD13 I've reviewed a couple of files that were sent during that timeframe with that CLIA and the CLIA appears complete. It will be useful if we could get some accession numbers back from them or filenames that had this issue.

**Comment by wcollin89** [comment]
@victor-chaparro @TaneaY @MikaelahD13 The user replied back with the attached spreadsheet containing the accession numbers for the related messages.
[Accession Numbers List_OBX Segment Issues.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0ZnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--002948afe62b393fd0c0af1deb34bd1fcd6e259e/Accession%20Numbers%20List_OBX%20Segment%20Issues.xlsx)

**Comment by victor-chaparro** [comment]
Ok, I downloaded those specific files and all the reports have the CLIA complete.

**Comment by wcollin89** [comment]
@victor-chaparro Thank you for looking into it! I am reaching out to the user to request specifics on the OBX segments they received so we can see if it differs from what was sent.

**Comment by wcollin89** [comment]
@victor-chaparro the user replied back this morning with the following:

> In the example from Premiere Medical Center of Burbank, you’ll notice that the CLIA is missing the last digit in OBX 23.1. The example from First Care has the CLIA completely missing from OBX 23.1. OBX 23.9 shows the CLIA correctly in both cases. I apologize, this is likely where the confusion came from- I didn’t specify which exact OBX segment we were discussing.
> 
>  
> 
> Premiere Medical Center of Burbank, Inc:
> 
> OBX|1|CE|94500-6^SARS-CoV-2 (COVID-19) RNA NAA+probe Ql (Respiratory system specimen)^LN||260373001^Detected^SCT^^Detected|||A^Abnormal (applies to non-numeric results)^HL70078^^^^2.5.1|||F|||20240806120000-0700|05D2002489^Premiere medical center of Burbank, inc.^CLIA||^BD Respiratory Viral Panel for BD MAX System^^^^^^^BD Respiratory Viral Panel for BD MAX System|00382904419165^^DII|20240806120000-0700||||`Premiere medical center of Burbank, inc.-05D200248`^^^^^CLIA&2.16.840.1.113883.4.7&ISO^XX^^^05D2002489|4418 VINELAND AVE SUITE 110^^Toluca Lake^CA^91602^USA||||||
> 
>  
> 
> First Care Medical Centers, LLC:
> 
> OBX|1|CE|94534-5^SARS-CoV-2 (COVID-19) RdRp gene NAA+probe Ql (Respiratory system specimen)^LN||260373001^Detected^SCT^^Detected|||A^Abnormal (applies to non-numeric results)^HL70078^^^^2.5.1|||F|||20240811235106-0700|02D2091211^First Care Medical Centers, LLC - Katherine Sterner, ANP^CLIA||^ID NOW^^^^^^^ID NOW|00811877010616^^DII|20240812000606-0700||||`First Care Medical Centers, LLC - Katherine Sterne`^L^^^^CLIA&2.16.840.1.113883.4.7&ISO^XX^^^02D2091211|1301 Huffman Rd Ste 100^^Anchorage^AK^99515-3568^USA^^^Anchorage||||||

Thank you!

**Comment by victor-chaparro** [comment]
@wcollin89 I finally found what the issue is.  OBX.23.1 max length is 50 characters, we are truncating that field per California's request. We can stop truncating it if that's what they need, but OBX.23.1 should only have the organization and the CLIA can be found in OBX.23.9.

**Comment by wcollin89** [comment]
@victor-chaparro thank you for your help! I have advised the user of this information and will let you know if they have any further requests.

**Comment by wcollin89** [comment]
@victor-chaparro the user responded this morning with the following request:

> If it works for all parties, could the team truncate the reporting facility to 40 characters and append CLIA? That way it should not exceed 50 characters but will still contain a complete CLIA #. We use the CLIA from OBX 23.1 to identify the laboratory due to what’s available in our data system at this time. (We are not able to use OBX 23.9.)

They included Ellaison Carroll from CDPH on their response to confirm that CA will accept this change.

**Comment by wcollin89** [comment]
@victor-chaparro we received the following confirmation from Ellaison:

> I’m good with truncating OBX-23.1 to 40 characters for the name of the reporting facility so the full CLIA is included.  I actually thought something like this was already in place, but for 35 characters instead of 40.  Is it possible to check the configuration history and see if it was and when it changed? 

Thank you!

**Comment by wcollin89** [comment]
@victor-chaparro thank you for the update! I've provided this information to the user and will let you know of any resend requests.

**Comment by wcollin89** [comment]
@victor-chaparro I have sent a final follow-up message to the user, asking for confirmation that there have been no further issues or messages to resend, and advising that this issue is being marked as Resolved.

Thank you!

**Comment by wcollin89** [comment]
@victor-chaparro we received confirmation from the user today that there are no further OBX issues:

> We were able to confirm that we’re receiving reports with these changes. We’ll connect with you again if we have any other issues.

Thank you for all your assistance!
