### ISSUE TITLE
Prioritize what content/artifacts need to be created for existing sender outreach

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15632]
## Problem statement

As we get ready to start migrating Senders over in the next quarter, we need to identify the content/artifacts that need to be created or updated for sender outreach.

## Acceptance criteria

- [ ] Identify what artifacts currently exist
- [ ] Work with Product to prioritize what needs to be created or updated
- [ ] Create follow-on ticket for any content related items

## To do
- [x] Flag any existing "sender onboarding" website content that may need to be updated
- [ ] Connect with Glenn and Onboarding team (even async) to determine if we have any other email templates or artifacts that currently exist
- [ ] Schedule meeting with Product (Chris) to review

**Comment by audreykwr** [comment]
Initial list from [change comms deck](https://cdc.sharepoint.com/:p:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B1D38EC13-266D-4B0C-855C-4804C3F24AA6%7D&file=Phase%202%20UP%20change%20communication%20messaging%20%2B%20plans.pptx&action=edit&mobileredirect=true): 

- [ ] Individual outreach emails to priority organizations​
- [ ] Updated decks or resources for STLTs, highlighting data sources like SimpleReport and HIV​
- [ ] Update internal documentation (like Q&A doc)​
- [ ] Email templates for migration process and/or specific to adding new conditions (Building into other evergreen content on adding conditions, such as site updates)​
- [ ] FAQ page updates​
- [ ] API guide updates (with special note of any major changes)​
- [ ] Plan for sunsetting validation tool and/or intermediate updates to clarify its limited application​
- [ ] New sender onboarding materials​
- [ ] Site and messaging updates for HIV and CSV​
- [ ] Updated one pager (and updated link on website)

**Comment by audreykwr** [comment]
**Items to update**:
- [ ] Sender intake form (on [this page](https://reportstream.cdc.gov/getting-started/sending-data#1)) - notes already gathered on initial updates needed from onboarding engineers. This might only be needed for new senders and not migrations though.
- [ ] Support team SOP/templates related to senders.

**Items to create**:
- [ ] Outreach emails 
- [ ] Meeting deck (previous discussion did not surface any recent enough materials, so considering this new while we will utilize STLT decks as a starting point)

**Comment by chris-kuryak** [comment]
For next sprint in order:
- "Requirements" Meeting deck for senders
- Migration email outreach
- Sender Intake form
- Updated SOP for support team
