### ISSUE TITLE
[BUG] Submission History API doesn't show Filtered reports

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#15645]
## Describe the bug
When filters are triggered for receivers they do not show up when calling Submission History API `{{url}}/waters/report/{reportId}/history`. The submission status says `Waiting to Deliver` and should say `Failed to Deliver` and under destinations filteredReports should be populated.

## Impact on ReportStream

Senders, if using the history endpoint, may not get accurate information as to the real status of their submitted report and may lead to confusion.

Engagement team uses API to troubleshoot submission and ensure filters are working as expected.

## Steps to reproduce
Send a report locally and make sure the submission triggers a qualityFilter. You can do this by updating a receiver's quality filter to false:`qualityFilter: ["false"]`
Call the Submission History API  `{{url}}/waters/report/2558/history`

It seems like the new steps added to the Universal Pipeline are breaking this API. The API was probably looking at the Action Log Route step records to return this information.

## Expected behavior
- "Failed to deliver" should be the status that is displayed when a report fails quality filters.
- Destinations object should return filters triggered.

**Comment by arnejduranovic** [comment]
@victor-chaparro when a report fails quality filters (or any routing filter) should we use status "not delivering / partially delivered" instead of "failed to deliver". I don't think failed to deliver is a status?
