### ISSUE TITLE
Testimonial from CDC Staff

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#1567]
6.28.2021 Notes from Rebecca/Skylight regarding V4 of RS website:

Testimonial from CDC staff: 
- ON HOLD PENDING MIKE JUDD RESPONSE (Rebecca/Berni) 
- CDC comms person as alt contact?

**Comment by loripusey** [comment]
@BerniXiongA6 is this ticket still relevant? If it is on hold can we close it?

**Comment by BerniXiongA6** [comment]
@loripusey Let's keep it open in the Icebox for now. I'll follow up with the design team in our next sync to determine whether this is still a feature we want on the website.

**Comment by loripusey** [comment]
@BerniXiongA6 were you able to follow up on this this past week?

**Comment by BerniXiongA6** [comment]
@loripusey the design team says let's keep it in the "icebox" still. It's still a possible idea, just not a priority at the moment. Thanks!
