### ISSUE TITLE
Can we track App Insights/Azure monitoring costs per enviornment

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#15699]
We are starting to take advantage of Azure Events, as part of we want to make sure we're not increasing our costs more than expected.

Done Criteria:
Dashboard in Metabase tracking Azure Events cost (or, if that's not possible Application Insights, or if that's not possible Azure Monitoring) per environment.

**Comment by dkrylovsb** [comment]
Hi @arnejduranovic could you give me some background here, specifically what "Azure Events" is? Thanks.

**Comment by arnejduranovic** [comment]
Our application is creating `custom` Azure Events that you can see in the screenshot below: 

![Screenshot 2024-08-26 at 12 54 41 PM](https://github.com/user-attachments/assets/299f0354-f795-47ac-996c-6bc1ffc8e046)

**Comment by dkrylovsb** [comment]
"App Insights Costs by Day" added to the "ReportStream - Costs" dashboard in Staging and Prod:
![image](https://github.com/user-attachments/assets/6341c602-575c-4c70-8151-1f7d8bc46bf9)
