### ISSUE TITLE
Research Marketing Data Points for Landing Page

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#1569]
### Problem statement
Currently, there's not a lot of marketing copy on the home page of the ReportStream web site that compels prospective users to sign up (i.e. how RS can address their pain points). 

### What you need to know
_Per 6.28.2021 Notes from Rebecca/Skylight regarding V4 of RS website: Research marketing Data Points that we may want to add to the Landing Page. Examples include number of files sent daily, number or percentage of public health departments onboarded, etc._

Initially, users were from PHDs that received data through RS. The first few iterations of RS home page catered mostly to one type of user (receivers). 

Now, users also include testing facilities that are sending data to PHDs through RS. The goal is to also have web copy on the RS homepage that caters to these types of users (senders). 
### Acceptance criteria

- Input from RS team members on what data points already exist (have already been collected) to improve marketing copy for senders
- Input from users (data points we haven't yet collected) that would be nice to have as marketing copy on RS home page for prospective users

### To do

- [x] Victoria and Berni discuss research ideas

- [ ] Victoria and Berni meet with RS team members, as needed

- [ ] Victoria and Berni extract info from user interviews, as needed

**Comment by BerniXiongA6** [comment]
11.9.2021 @victorialb-usds  and Berni to start discussing this as we collab on content and research efforts for future state RS website iterations.

**Comment by BerniXiongA6** [comment]
11.19.2021 @victorialb-usds and I discussed some of the questions we'd like to know to better help users (prospective users vs. first time/new users vs. returning users) get what they need from the RS home page:
- What are users trying to accomplish/what do they need help with once they've landed on the RS home page (prospective users and registered users may not need to same things)?
- How can we help users distinguish what to do/where to go/how to get help based on their status?
- Specifically for prospective users, what kind of info would they need to feel compelled to register/become a user (we know that some users say if they can save time and effort, they're more likely to sign up)?
- What cases studies/success stories can we share about RS experience (making sure we address time saved, effort reduced, ease of use, etc.)?
- How can we reduce the time it takes to learn to use RS (for people who are concerned about the hours spent being trained/figuring out how to do things)?
- Testimonials (addressing average hours saved, volume of [insert term here e.g. files] sent, time to task, # of STLTs/cities endorsed by county health officers)

**Comment by chris-kuryak** [comment]
Closing due to being old/stale. Will reference in new epic for research purposes.
Closing by committee @drew-usds @jillian-hammer @lizzieamanning @audreykwr
