### ISSUE TITLE
Remove link to archived "Data models" page on ReportStream website

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#15728]
## Describe the bug
The ReportStream website archived the Data Models page in Dec 2023 (see #12347). However, we forgot to remove the link to that page on the [Security page](https://reportstream.cdc.gov/about/security#11).

## Impact on ReportStream
An external user flagged the broken link when browsing the site looking for data transmission options for Minnesota.

## Steps to reproduce
**Broken links on the `/security` page**
1. Go to 'about/security'
2. Scroll down to the last accordion 'What data does ReportStream send?'
3. Click 'standard data schema' hyperlink.
4. See 'Page not found' 404 message.

**Broken links on the `/support` page**
1. Go to '/support'
2. Scroll to the Getting started section
3. Open the '[How do I map to the LIVD table](https://reportstream.cdc.gov/support#how-do-i-map-to-the-livd-table)' accordion
4. See two broken links.

## Acceptance criteria
**Security page**
- [ ] On the `Security` page: Adjust content: Remove "in our standard data schema" from sentence so it just reads "ReportStream always sends synthetic, non-PII data in our standard data schema during testing."

**Support page**
- [ ] Remove entire accordion/section titled [How do I map to the LIVD table](https://reportstream.cdc.gov/support#how-do-i-map-to-the-livd-table)

**Comment by audreykwr** [comment]
Remove "in our standard data schema" from sentence so it just reads "ReportStream always sends synthetic, non-PII data in our standard data schema during testing."
