### ISSUE TITLE
Remove "Okta account" requirement from API website content

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15734]
## Problem statement
There is inaccurate information on our website. An Okta account is not required to query the History Details API.

## What you need to know

On this page: https://reportstream.cdc.gov/developer-resources/api/documentation/responses-from-reportstream

Existing content:
> ReportStream features a History Details API that can be later queried to obtain the actual destinations and relevant detail. If you’d like to use this API, let the ReportStream team know, and we’ll provide you with additional information about requirements for Okta authentication.

Proposed change:
> ReportStream features a History Details API that can be later queried to obtain the actual destinations and relevant detail using your existing private/public key pair.

## Acceptance criteria

- [ ] Content on page matches above proposal
- [ ] PDF guide updated on site. [File for updated PDF](https://cdc.sharepoint.com/:b:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Programmer%27s%20Guide%20updates/ReportStream%20Programmer%27s%20Guide%20v4.6.pdf?csf=1&web=1&e=JWkmCD)
- [ ] Date updated on all API guide pages

## To do

- [x] Reviewed by Content Specialist (Audrey)

**Comment by audreykwr** [comment]
Pages with dates: 

- [ ] https://reportstream.cdc.gov/developer-resources/api/getting-started
- [ ] https://reportstream.cdc.gov/developer-resources/api/documentation/responses-from-reportstream
- [ ] https://reportstream.cdc.gov/developer-resources/api/documentation/sample-payloads-and-output
