### ISSUE TITLE
Receiver Status Filters are not working as expected

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-reportstream#15737]
## Problem statement

When switching between the Success Type, the data is inconsistent.

## What you need to know

Switch b/w two Success Type a couple of times and view the inconsistent data 

<img width="1839" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXVoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d2c0682aa617dfd5ee39204fccfab492c121fc8/Screenshot%202024-08-30%20at%203.02.50%E2%80%AFPM.png" alt="Screenshot 2024-08-30 at 3.02.50 PM.png" />

## Acceptance criteria

- [ ] Fix data inconsistencies when switching b/w the Success type filter.
- [ ] Receiver Name filter does not seem to work in most cases (i.e. uppercase search, special chars, et al)

## To do

- [ ] Fix data inconsistencies when switching b/w the Success type filter.
- [ ] Fix Receiver name filter so that it works.
- [ ] Update/uncomment e2e related tests once done.

**Comment by chris-kuryak** [comment]
Initial load works, but the filters and search are "flaky" and don't seem to work well. Need investigation before fixing. Also, need to check if these filters are still needed by onboarding engineers
