### ISSUE TITLE
[BUG] Check function not working for REST Transport

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#15794]
## Describe the bug
The REST transport authentication logic has been updated and did not get updated for the Check Function. The Check function runs every two hours and is throwing exceptions when checking the REST transport for CADPH

## Dev Notes

We need to update the logic for `testRest` under `CheckFuntion.kt`.
We should leverage the logic the is inside REST Transport to avoid duplicating logic in two places and preventing issues like this from happening.

## Steps to reproduce

Navigate to the Receiver Status Dashboard and notice how the check is failing for CADPH every time.

## Expected behavior
- CA-DPH transport check passes in the Receiver Status Dashboard
- ELIMS transport check passes  in the Receiver Status Dashboard

**Comment by oslynn** [comment]
In RESTTransport.kt: getOAuthToken(), it doesn't have UserJksCredential support.

**Comment by oslynn** [comment]
For REST endpoint doesn't have to authenticate (e.g. endpoint that use CERT or JKS install in client's engine), we will need way to check the endpoint.  I am researching for what is the best way.

**Comment by oslynn** [comment]
Done.
