### ISSUE TITLE
Authorization strategy and implementation for submissions endpoint

### ISSUE THREAD

**Issue by jalbinson** [CDCgov/prime-reportstream#15801]
### User Story
As a sender onboarded to ReportStream, I want to be authorized to hit the submissions endpoint

### Description/Use Case
We want to only allow authorized senders to hit the submissions endpoint.

### Risks/Impacts/Considerations
A nefarious user could submit false reports which could skew public health data.

### Dev Notes
- Look into custom claims block in Okta to see if its easily possible to inject the org name for easy comparison during authorization check
- Reports in send step may contain thousands of items so a single event wont be able to hold all the condition data. One option is to create a "ItemSentEvent" for each ITEM in the report.

### Acceptance Criteria
- Decide under which Okta authorization server clients orgs should live
- Scopes and extra claims clearly defined for organizational users
- ~Authz strategy implemented for submission endpoint (probably `@PreAuthorize` annotation)~
  - #16183 handles this now
- Come up with approach for authorization in Azure Functions app that does not depend on Spring
- unit tests

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/15801?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean

**Comment by dylansmith-Nava** [comment]
Linking some of the prior research here:
- [Identity proofing new senders](https://cdc.sharepoint.com/:p:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BA3E01EAA-EB8E-4C6D-80B7-40C7870317A8%7D&file=Identity%20proofing%20new%20senders.pptx&action=edit&mobileredirect=true) slide deck (a bit prescriptive, but helpful for context)
- General [authentication and verification](https://cdc.sharepoint.com/teams/ReportStream/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FReportStream%2FShared%20Documents%2FDesign%20and%20Research%2F02%5FResearch%2FAuthentication%20and%20Verification&viewid=6255f791%2D133e%2D4cae%2D9185%2Db78c974e99f2) research folder
- [Authentication and verification](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1685656723223/62d953ac53acd55780b2c58ed2b3b82385f3ba21?sender=ufb3824a0e63fafb0304f5774) Mural

**Comment by jalbinson** [comment]
Decisions made in this ticket are documented in the UP SRD under "Authorization Service Software Requirements"

**Comment by arnejduranovic** [comment]
The SRD this ticket updated will be implemented here: https://github.com/CDCgov/prime-reportstream/issues/14601
