### ISSUE TITLE
WA reports a problem with OBX-23.10

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#1580]
**Describe the bug**
WA DOH reports a general problem with how ReportStream sends an HL7 message. The OBX-23 Ordering facility fields is not correct. It has an extra CLIA component. 

**Impact**
We are passing WA QA. We may not pass other qualifications in the future. 

**To Reproduce**
1. Look at HL7 message generated by ReportStream

**Expected behavior**
OBX-23.10 doesn't have the extra field.

**Screenshots**

**Logs**

**Additional context**
Message from WA
```
Extra component
 
What we received:
CLIA&2.16.840.1.113883.19.4.6&ISO^XX^^^38D0805506^CLIA
 
Example: CLIA&2.16.840.1.113883.19.4.6&ISO^XX^^^38D0805506
```

**Comment by RickHawesUSDS** [comment]
This bug is actually reaching further than just the OBX-23. It affects the specimen-id, filler-id, placer-id and patient-id.

**Comment by jlusds** [comment]
What's the status fo this?

**Comment by RickHawesUSDS** [comment]
In production.
