### ISSUE TITLE
Submission History reads azure storage table when report not found in postgresql database

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#15822]
### User Story

As a sender to the new submissions api
I want to use the submissions history api, 
so that I can view the history for all successful and failed submissions.

### Description/Use Case
The submissions api does not connect to the postgresql database. Instead, it inserts to a table in the azure storage account. That table has information includes submission status and details which could include error information. The information in that table should be used in the submission history response.

### Dev Notes
The submissions api currently inserts to the submission table in the azure storage account(_not in postgresql_) and uploads a file to the blob storage. Then a queue message is added to the FHIRReceive queue. The current submission history expects records to exist for action and report_file. Since the submission micro service does not connect to postgresql it cannot verify the client_id supplied in the submission. The FHIRReceive step does the verification. If a sender is not found, then no record is made of the submission in postgresql. The only records are in the storage account table.

With that in mind, the submission history needs to be updated to review that table when no report exists in the postgresql database.

### Acceptance Criteria
- [ ] When a report is not in postgresql the submission history responds appropriately with detail from submission table

**Comment by JFisk42** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/15822?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @mkalish @thetaurean
