### ISSUE TITLE
javascript Syntax Exception - in production web receiver

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1582]
This Exception has occurred 3 times in Prod in the last 7 days, most recently 7/12/2021, 12:06:55 PM ET.

https://reportstream.cdc.gov/js/prime-web-receiver-post.js

url:	https://reportstream.cdc.gov/js/prime-web-receiver-post.js	
message:	Syntax error	
typeName:	Object	
columnNumber:	13	
lineNumber:	4	
errorSrc	window.onerror@https://reportstream.cdc.gov/js/prime-web-receiver-post.js:4:13

Syntax error
 from window.onerror@https://reportstream.cdc.gov/js/prime-web-receiver-post.js:4:13

**Comment by jlusds** [comment]
@mry-usds was this resolved?
