### ISSUE TITLE
LIVD SARS-CoV-2 Catalog with FDA Attributes to be uploaded to ReportStream

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#15826]
**Problem statement**
We received an updated LIVD to the Reportstream inbox. The LIVD table needs to be uploaded into ReportStream.

**What you need to know**
[LIVD-SARS-CoV-2-2024-08-29 PRIME.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTYvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8b08fbb4385f9912acd8df69016b9ba5e747e56/LIVD-SARS-CoV-2-2024-08-29%20PRIME.xlsx)

**To do**
Please upload the new LIVD table to ReportStream.

**Comment by MikaelahD13** [comment]
Good afternoon, @victor-chaparro, when you get a chance, may you please provide guidance on this ticket? Thanks!

**Comment by victor-chaparro** [comment]
Updated LIVD table in both staging and production
