### ISSUE TITLE
Monthly update content management plan

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#15851]
## Problem statement
Now that the first edition of the monthly update is complete, we can create longer term plans for managing the content.

## Acceptance criteria
- [x] Plan drafted and reviewed with product manager and design lead

**Comment by jillian-hammer** [comment]
Audrey's [draft link](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Monthly%20update/Monthly%20update%20content%20mangement%20plan.docx?d=w899c9f3e849343c7a7752cb4e124e665&csf=1&web=1&e=6WPbh2)
