### ISSUE TITLE
Receiving payload from clients in the incorrect format results in no errors

### ISSUE THREAD

**Issue by joemeree** [CDCgov/prime-reportstream#1585]
Running an HL7 file into a CSV schema gets no errors, no warnings, 0 items.  If we run an HL7 file into a CSV schema I get the following output.  There are several reasons here to throw an error:
1. A different type of data was sent than the one specified for the sender.
2. The number of reports is zero.  Is there a reason this is not an error already?  Note that the content type cannot be relied on as a user may send an HL7 file with the CSV content type.

`{
  "id" : "440582a2-ec7d-44da-a69b-fe01e3d1ffce",
  "timestamp" : "2021-07-13T16:11:24.229800Z",
  "topic" : "covid-19",
  "reportItemCount" : 0,
  "destinations" : [ ],
  "destinationCount" : 0,
  "warningCount" : 0,
  "errorCount" : 0,
  "errors" : [ ],
  "warnings" : [ ]
}`

Acceptance criteria:
1. ReportStream generates an error when a client submits data with a different data type (e.g. HL7, CSV) specified in the content-type header than what is specified for the client configuration.
2. ReportStream generates an warning if no reports where received in the payload.

**Comment by joemeree** [comment]
Here's the data I submitted to the CSV schema.
[primary health fake_data_oracle.txt](https://github.com/CDCgov/prime-reportstream/files/6811138/primary.health.fake_data_oracle.txt)

**Comment by joemeree** [comment]
Seems to me if we expect CSV or HL7 and we can't parse it, that should be an error.

**Comment by carlosfelix2** [comment]
@joemeree I ran this data through the latest master and I got failures as follows.  Is there more data we need, like the client used to submit the data?
1. Pasted the data as is from the TXT file provided resulting in errors due to missing data for PID, OBX, etc. since the TXT file has all the data as one line that looks like it is all in the MSH segment.
2. Manually added newlines to each segment and got the errors below.
`
{
    "id": null,
    "warningCount": 0,
    "errorCount": 6,
    "errors": [
        {
            "scope": "ITEM",
            "id": "",
            "details": "ca.uhn.hl7v2.validation.ValidationException: Validation failed: Primitive value 'D' requires to be empty or a number with optional decimal digits at ORC-21(0) ca.uhn.hl7v2.model.DataTypeException: ca.uhn.hl7v2.validation.ValidationException: Validation failed: Primitive value 'D' requires to be empty or a number with optional decimal digits at ORC-21(0)\n\tat ca.uhn.hl7v2.model.AbstractPrimitive.setValue(AbstractPrimitive.java:97)\n\tat ca.uhn.hl7v2.parser.PipeParser.parse(PipeParser.java:446)\n\tat ca.uhn.hl7v2.parser.PipeParser.parse(PipeParser.java:385)\n\tat ca.uhn.hl7v2.parser.PipeParser.parse(PipeParser.java:1169)\n\tat ca.uhn.hl7v2.parser.PipeParser.doParse(PipeParser.java:226)\n\tat ca.uhn.hl7v2.parser.Parser.parse(Parser.java:212)\n\tat ca.uhn.hl7v2.parser.PipeParser.parse(PipeParser.java:1028)\n\tat gov.cdc.prime.router.serializers.Hl7Serializer.convertMessageToMap(Hl7Serializer.kt:233)\n\tat gov.cdc.prime.router.serializers.Hl7Serializer.convertBatchMessagesToMap$deconstructStringMessage(Hl7Serializer.kt:114)\n\tat gov.cdc.prime.router.serializers.Hl7Serializer.convertBatchMessagesToMap(Hl7Serializer.kt:149)\n\tat gov.cdc.prime.router.serializers.Hl7Serializer.readExternal(Hl7Serializer.kt:350)\n\tat gov.cdc.prime.router.azure.ReportFunction.createReport(ReportFunction.kt:298)\n\tat gov.cdc.prime.router.azure.ReportFunction.validateRequest(ReportFunction.kt:261)\n\tat gov.cdc.prime.router.azure.ReportFunction.run(ReportFunction.kt:79)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)\n\tat com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)\n\tat com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:57)\n\tat com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)\n\tat com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)\n\tat com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)\n\tat com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\nCaused by: ca.uhn.hl7v2.validation.ValidationException: Validation failed: Primitive value 'D' requires to be empty or a number with optional decimal digits\n\tat ca.uhn.hl7v2.validation.impl.RuleSupport.failed(RuleSupport.java:67)\n\tat ca.uhn.hl7v2.validation.impl.RuleSupport.failedWithValue(RuleSupport.java:58)\n\tat ca.uhn.hl7v2.validation.impl.RuleSupport.result(RuleSupport.java:48)\n\tat ca.uhn.hl7v2.validation.impl.RuleSupport.result(RuleSupport.java:44)\n\tat ca.uhn.hl7v2.validation.builder.PredicatePrimitiveTypeRule.apply(PredicatePrimitiveTypeRule.java:115)\n\tat ca.uhn.hl7v2.validation.builder.PredicatePrimitiveTypeRule.apply(PredicatePrimitiveTypeRule.java:38)\n\tat ca.uhn.hl7v2.model.AbstractPrimitive.setValue(AbstractPrimitive.java:95)\n\t... 29 more\n"
        },
        {
            "scope": "ITEM",
            "id": "",
            "details": "The Value for ordering_facility_state for field ORC-22-4 is required"
        },
        {
            "scope": "ITEM",
            "id": "",
            "details": "The Value for patient_last_name for field PID-5-1 is required"
        },
        {
            "scope": "ITEM",
            "id": "",
            "details": "The Value for patient_state for field PID-11-4 is required"
        },
        {
            "scope": "ITEM",
            "id": "",
            "details": "The Value for message_id for field MSH-10 is required"
        },
        {
            "scope": "ITEM",
            "id": "",
            "details": "The Value for testing_lab_clia for field OBX-23-10 is required"
        }
    ],
    "warnings": []
}
`

**Comment by joemeree** [comment]
I use this one:
curl -X POST -H "client:imagemover" \
-H "Content-Type: text/csv" \
--data-binary ***@***.***/$1" \
-H "x-functions-key:THE_KEY" \
https://staging.prime.cdc.gov/api/reports

Joe Meree  703-967-4730  ***@***.******@***.***>

**Comment by carlosfelix2** [comment]
@joemeree I understand the issue now.  You are sending HL7 data with the incorrect content type and client and we should be sending errors back.  A few notes on the submission detailed above and why it fails:
1. You are submitting an HL7 message with the wrong content type.  You passed text/csv and it needs to be application/hl7-v2.  See https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/Report.kt#L53. This needs to return some error back since there are not reports taken in.  Will need to add some extra checks.
2. You are using the client imagemover, which is a sender that is supposed to be sending CSV.  We should reject HL7 if received.  Will see what extra checks we can make.  We do have to reject as the schema may not support a different type.

**Comment by joemeree** [comment]
I told you I'm good at breaking stuff 😊


Joe Meree  703-967-4730  ***@***.******@***.***>

**Comment by jimduff-usds** [comment]
These seem like low priority issues?
