### ISSUE TITLE
Finalize system and priority new content 

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#15854]
## Problem statement
We need updated messaging resources and a more usable system for different stakeholders and teammates to stay aligned and leverage these resources. 

## What you need to know
- [planning doc from sprint 100](https://docs.google.com/document/d/1lB_a-ZkxsbbHFtmXMT057P46wt4lRJVbjLjZ8nVTBBs/edit)

## Acceptance criteria
- [x] Structure finalized that contains priority content 
- [x] Feedback and input from stakeholders collected and applied as necessary

**Comment by chris-kuryak** [comment]
Chris has reviewed and is ready for publish.

**Comment by audreykwr** [comment]
https://cdc.sharepoint.com/teams/ReportStream/SitePages/Brand,-content,-and-communications.aspx
