### ISSUE TITLE
MN - Last Mile Failures 

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#15911]
## Problem statement

Hi all, please see below attachment, It is showing that Minnesota is currently having some failures.

## What you need to know

<img width="938" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVRrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed037e945e88096e6b1f930ecd2fede0800891c0/image.png" alt="image.png" />

## Acceptance criteria

- [ ] ...

## To do

Resend files if neccessary.

**Comment by MikaelahD13** [comment]
Hey @victor-chaparro, may you please provide guidance on this ticket?

**Comment by oslynn** [comment]
Results:
FAILED POST of inputReportId b240cca7-f0c6-48d5-9912-17921cc99137 to apiUrl=https://dex.web.health.state.mn.us/api/resources/proxy/idepc/elr/hl7/lab (orgService = mn-doh.full-elr), Exception: Client request(PUT https://dex.web.health.state.mn.us/api/resources/proxy/idepc/elr/hl7/lab) invalid: 422 Unprocessable Entity. Text: "MSH|^~\&|MEDSS-ELR^2.16.840.1.114222.4.3.3.6.2.1^ISO|MN DOH^2.16.840.1.114222.4.1.3661^ISO|CDC PRIME - Atlanta, Georgia (Dekalb)^2.16.840.1.114222.4.1.237821^ISO|Legacy of St. Michael^24D2003360^CLIA|20240919134048.865+0000||ACK^RO1|e5fe0c64-b5a3-40cf-829b-057ee16cb77d|P|2.5.1 MSA|AR|c163c00d-1cef-4f9e-8fe4-5b8a6cbffbfe ERR||PID^1^10^1^3|102^Data type error^HL70357|E||||Coding system not found 'PID.RACE.NULLFL' "
 ----------
Their system can process PID-10-3 with NULLFL.  This needs to replace it with blank ""

**Comment by oslynn** [comment]
Updated receiver transform.  It still has last mile failure.  Need more testing.

**Comment by oslynn** [comment]
Receiving Org:
mn-doh.full-elr
Failed at:
Fri, 9/20/2024, 8:41 AM
Action ID:
26355131
Report ID:
73f8fab3-e161-47d0-b2c1-58d888977436
Report File Receiver:
mn-doh.full-elr
File URI:
https://pdhprodstorageaccount.blob.core.windows.net/reports/ready%2Fmn-doh.full-elr%2F73f8fab3-e161-47d0-b2c1-58d888977436.hl7
mn-doh.full-elr
Results:
FAILED POST of inputReportId 73f8fab3-e161-47d0-b2c1-58d888977436 to apiUrl=https://dex.web.health.state.mn.us/api/resources/proxy/idepc/elr/hl7/lab (orgService = mn-doh.full-elr), Exception: Client request(PUT https://dex.web.health.state.mn.us/api/resources/proxy/idepc/elr/hl7/lab) invalid: 422 Unprocessable Entity. Text: "MSH|^~\&|MEDSS-ELR^2.16.840.1.114222.4.3.3.6.2.1^ISO|MN DOH^2.16.840.1.114222.4.1.3661^ISO|CDC PRIME - Atlanta, Georgia (Dekalb)^2.16.840.1.114222.4.1.237821^ISO|Partners in Pediatrics Rogers^24D1015199^CLIA|20240920134055.987+0000||ACK^RO1|79a6b288-b7ae-448a-99c9-d2465418a781|P|2.5.1 MSA|AR|1580559 ERR||PID^1^10^1^1|103^Table value not found^HL70357|E||||'ASKU' not found in 'PID.RACE.HL70005' "

**Comment by oslynn** [comment]
It it fixed.  The last mile failure stop getting mn-doh.full-elr resend notice since 9/20/2024
<img width="931" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTM2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f7563dbe74fc1c67d523fa91ea2d31fe9c1f9d6/image.png" alt="image.png" />

**Comment by oslynn** [comment]
However, I will still monitor the feed for next couple days.

**Comment by oslynn** [comment]
Need to fix hl7 messages and manually resend to mn-doh.full-elr.

**Comment by oslynn** [comment]
Done. I also received request to deactivate the ELR feed as well.

**Comment by oslynn** [comment]
9/30/2024 - Fixed and Resent all the following messages:
  18aaef96-3a16-4f22-939b-9932eccd3160.hl7  339b3561-bfe8-44f8-8bad-dc94a5bce14b.hl7  69b4cac9-d393-41f5-977c-5a6343c6d801.hl7  8b156ada-5a39-45c3-bd4a-cfe8e5862b35.hl7  b240cca7-f0c6-48d5-9912-17921cc99137.hl7  fc409dfb-4746-4e1f-b40f-9b2b182d2ba2.hl7
  18c7f0fc-a6b6-444c-9d42-03b738ed3c6b.hl7  59d86ed1-cf2f-4713-9c31-ba7f4c4df6e0.hl7  73f8fab3-e161-47d0-b2c1-58d888977436.hl7  97ea90fd-d4d7-46d6-a9e9-c20e6d46e01a.hl7  d5b25a15-8b06-415a-aa68-6485561619f8.hl7
  22757c66-1e56-40aa-b2e8-6b5c942146eb.hl7  5aa10e73-4791-4605-85c8-cd465a3dbc3d.hl7  766ae511-5a37-4269-9e52-45f9c48c2b25.hl7  aae5a453-3181-47fa-91f1-4647cbbe7829.hl7  fae9e2bc-11ca-485e-9b29-cc3ffd29333f.hl7

  18aaef96-3a16-4f22-939b-9932eccd3160.hl7  339b3561-bfe8-44f8-8bad-dc94a5bce14b.hl7  69b4cac9-d393-41f5-977c-5a6343c6d801.hl7  8b156ada-5a39-45c3-bd4a-cfe8e5862b35.hl7  b240cca7-f0c6-48d5-9912-17921cc99137.hl7  fc409dfb-4746-4e1f-b40f-9b2b182d2ba2.hl7
  18c7f0fc-a6b6-444c-9d42-03b738ed3c6b.hl7  59d86ed1-cf2f-4713-9c31-ba7f4c4df6e0.hl7  73f8fab3-e161-47d0-b2c1-58d888977436.hl7  97ea90fd-d4d7-46d6-a9e9-c20e6d46e01a.hl7  d5b25a15-8b06-415a-aa68-6485561619f8.hl7
  22757c66-1e56-40aa-b2e8-6b5c942146eb.hl7  5aa10e73-4791-4605-85c8-cd465a3dbc3d.hl7  766ae511-5a37-4269-9e52-45f9c48c2b25.hl7  aae5a453-3181-47fa-91f1-4647cbbe7829.hl7  fae9e2bc-11ca-485e-9b29-cc3ffd29333f.hl7
