### ISSUE TITLE
Front end report details download should not include blob folder structure

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#1593]
With the changes in #1416, the blobs are not stored with a folder hierarchy that is reflected in the blob name.  Blobs used to be stored in the root all together, but now they have two levels of folders like `ready/Faz-phd.elr-prod/Faz-covid-19-7edf57cf-a6d4-4a3f-98bb-300a2f9a0018-20210714141108`.  The problem is that when a user downloads one of the newer blobs uploaded then they will get a filename of `ready%2Faz-phd.elr-prod%2Faz-covid-19-7edf57cf-a6d4-4a3f-98bb-300a2f9a0018-20210714141108` instead of just the true filename.  Note that, for a few weeks, older files in the blob store will still be in the root, so you must support both with and without the folder structure.

Acceptance criteria:
1. The filename of a downloaded report from the front end only reflects the filename in the blob store without the folder names.
2. For blobs stored before #1416, the filename of a downloaded report from the front end reflects the filename in the blob store.

**Comment by jimduff-usds** [comment]
Current body_url looks like this:   http://blah-blah-blah/reports/hhsprotect-covid-19-dd8d3e53-cba0-4493-915b-77add89b5c29-20210712135017.csv

Seems like this is just a case of grabbing everything after the last / in all cases, both old and new folder structures?

**Comment by carlosfelix2** [comment]
OBE.  Added the changes to #1416

**Comment by jimduff-usds** [comment]
@carlosfelix2 , I think there's still an issue:   the name as it appears on the download website is correct, however if you actually download the file, the downloaded file's name is (for example) ready%2Fpima-az-phd.elr%2Fpima-az-covid-19-9a89c2cb-d1d3-46df-ac90-bcb7f0a4918f-20210719113546.csv

It should be pima-az-covid-19-9a89c2cb-d1d3-46df-ac90-bcb7f0a4918f-20210719113546.csv
