### ISSUE TITLE
Monthly Comms for Oct 2024 - Content creation

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15976]
## Problem statement
Sept 2024 monthly update content creation

## What you need to know

- Guidance for content/timeline provided in #15851
- Working space: [Document link](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Monthly%20update/20241001_ReportStream_Monthly-update-drafting_Oct2024.docx?d=w96c105a8181144f58ac4665e9bd52002&csf=1&web=1&e=NkRVgcs)

## Acceptance criteria

- [x] Content created in accordance with guidance found in #15851
- [x] Content reviewed by Product Manager and Account Manager

**Comment by jillian-hammer** [comment]
Putting together the draft in this [working doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Monthly%20update/20241001_ReportStream_Monthly-update-drafting_Oct2024.docx?d=w96c105a8181144f58ac4665e9bd52002&csf=1&web=1&e=NkRVgc).

**Comment by jillian-hammer** [comment]
completed the content for this month's monthly update! @chris-kuryak, I sent test emails to your CDC and Nava inboxes. lmk if you have a chance to review and if all looks good, I'll schedule the send.

**Comment by chris-kuryak** [comment]
Looks good.

For next month, you can remove the section that says:

> Public health agencies: If you are receiving data and have not updated your connection, please contact...

Glenn has contacted all but 2 STLTs left to migrate, so we should have contacted everyone by the end of the month.

**Comment by jillian-hammer** [comment]
sounds good, thanks for reviewing @chris-kuryak!
