### ISSUE TITLE
Documentation for ETOR Newborn Screening Project

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#15988]
## Problem statement

Create comprehensive and consolidated documentation 

## Acceptance criteria

- [x] Sender/Receiver contacts (with descriptions)
- [x] Short summary of current status of each connection
- [x] Data types used (ORU, OML, etc) for each connection
- [x] Data flow charts
- [x] Accounts/Credentials saved and shared with Victor in Keybase
- [x] Consolidate existing documentation

## To do

- [ ] ...

**Comment by oslynn** [comment]
done and gave to Victor
