### ISSUE TITLE
Develop talk track and agenda for Brand and Messaging Center All Teams Sync update

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15981]
## Problem statement
A new Sharepoint page has been created that provides messaging resources for ReportStream team members. This content needs to be shared with team members for awareness.

## What you need to know
- Messaging resource created in ticket #15854
- Brand and Messaging Center: [Sharepoint link](https://cdc.sharepoint.com/:u:/r/teams/ReportStream/SitePages/Brand,-content,-and-communications.aspx?csf=1&web=1&e=6aKVaZ)
- Talk track working space: [Doc link](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/00_DesignOperations/Presentations/20241030_ReportStream_Brand-Messaging-Center_Talk-Track.docx?d=w6b31e0a1d01e4410bf57c31155273fcb&csf=1&web=1&e=7xfG4f)

## Acceptance criteria

- [x] Rough agenda/talk track created and aligned by Chris and Jillian
- [x] Added to upcoming All Teams Sync agenda

**Comment by jillian-hammer** [comment]
Moving back to Next Items to pick up in Sprint 106 due to scheduling conflicts with the upcoming All Teams cc @chris-kuryak @MikaelahD13

**Comment by jillian-hammer** [comment]
presentation delivered on 10/30! copy of Slack recap below.

> **:otter: ReportStream Brand and Messaging Center is live!**
> today in All Teams Sync, @Chris Kuryak (he/him) [ULE6] and I reviewed the ReportStream Brand and Messaging Center, our source of truth for ReportStream’s brand identity and messaging guidelines. as ReportStream grows, it’s important for the team to be aligned in our language to make sure our audiences have a clear, consistent understanding of what ReportStream is. please use it as a reference and resource to grab and go for any of your external calls / emails, or if you just need a personal refresher on where our product is.
> please feel free to let us know if you have any questions or feedback as you use it. thanks all!
> 
> Here is the live [**Sharepoint link**](https://cdc.sharepoint.com/:u:/r/teams/ReportStream/SitePages/Brand,-content,-and-communications.aspx?csf=1&web=1&e=nDJcQI)
> For non-credentialed folks: we have a static **[Google Drive copy](**url**)** for you to reference in the interim.
