### ISSUE TITLE
NIST File Validation Process Updates

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#15997]
## **Problem Statement**

The ReportStream Support inbox received an email from Atilla Acar with Carbon Health. They are going through the Sender Onboarding process and receiving errors when validating a sample file using NIST Validation Tool link provided in our API Guide.

## **What you need to know**

Initial email received:

> Hi, I am following this page (https://reportstream.cdc.gov/developer-resources/api/getting-started) for onboarding. In the first step, "Format and validate a fake data file," I need to validate a sample file using the NIST General Validation Tool. However, when I open this link, the default tool scope is set to "NIST Home," and there is no available test profile for this scope. I tried changing the tool scope to "RADx MARS HL7v2" and tested the sample file from ReportStream, but I encountered many errors and warnings. I'm unsure which tool scope I should select or if I’m missing something. Thanks, Atilla

Upon further investigation, it was determined that Carbon Health will not be sending any OTC data. The specific NIST Validation Tool that is linked in our guide is only used when validating files containing OTC data. The correct link was provided, but the sample file the user downloaded from our site is still giving her numerous errors.

As mentioned in the email received 9/24/2024 at 5:08PM EST:

> Thank you for the clarification. I retrieved the sample HL7v2 message from this link: https://reportstream.cdc.gov/developer-resources/api/documentation/sample-payloads-and-output#sample-hl7-251-payload-and-output and tried to validate it using the link you provided: https://hl7v2-elr-testing.nist.gov/mu-elr/, but I'm still receiving numerous errors. It seems the sample message was recently updated on 9/9/2024, but it may be invalid, or perhaps the test suite isn't up to date.
> 
> Could you please provide me with a valid payload (HL7v2 message) for ReportStream ELR reporting, or could you double-check if this is the correct link for validating the message?

## **Acceptance Criteria**

- [ ] API Guide updated to reflect recent process updates and correct URLs for validation.
- [ ] Sample file verified to validate successfully.

## **To Do**

- [ ] Update ReportStream Onboarding Guide and Developer Resources to reflect current processes and tools.
- [ ] Update sample file as needed to validate successfully against necessary NIST validation tools.

## **Additional Comments**

More information can be found in the relevant Slack thread, but can be transposed as needed.

**Comment by MikaelahD13** [comment]
Hey @victor-chaparro, may you please provide guidance on this ticket?

**Comment by chris-kuryak** [comment]
@jillian-hammer This is in relation to the ticket that is on your plate for this sprint. This provides more context to you, and I think your ticket #16106 on the Experience board would meet these Acceptance criteria, so we could close both.

@MikaelahD13 I think this could be combined with #16106, check and see.

**Comment by jillian-hammer** [comment]
The link issue will be fixed with #16289. However, the sample file issue is still an unaddressed issue, so let's leave this ticket open for now.
