### ISSUE TITLE
Audit E2E tests for all previously skipped tests that need to be re-enabled

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#16006]
## Problem statement
During our process of creating E2E tests for the ReportStream website, we had to skip a lot of E2E tests.
We need to audit the website for all E2E tests that we may have skipped, and then develop a set of tickets to re-enable them.

## Acceptance criteria

- [x] Audit ReportStream site for all skipped E2E tests create a list of all tests that need to be re-enabled
- [x] Work with Product (Chris) to group and create ticket(s) to re-enable the skipped tests

**Comment by penny-lischer** [comment]
- last-mile-failures-page-user-flow.spec.ts (3 tests)
- idletimeout.spec.ts (1 test)
- daily-data-page-user-flow.spec.ts (3 tests)
- receiver-status-page-user-flow.spec.ts (7 tests. 2 are on hold due to filter issues)
- submission-history-page-user-flow.spec.ts (1 test. Due to filter issue)

**Comment by etanb** [comment]
@chris-kuryak @penny-lischer is the list above that Penny created the completion of this ticket? Or do we need to make another one with all the test pages, with all the SPECIFIC tests that we skipped? We should also give the reviewer the power to remove the test if need be!

**Comment by chris-kuryak** [comment]
New tickets created.
