### ISSUE TITLE
DR readiness discovery

### ISSUE THREAD

**Issue by devopsmatt** [CDCgov/prime-reportstream#16016]
The task is to understand the current state of data stores (single AZ, multi-AZ) and create a list of TF resources associated with their deployment.  Document and analyze the gap between current state and desired state of readiness for DR.

**Comment by devopsmatt** [comment]
Related to [1181](https://github.com/CDCgov/prime-reportstream/issues/1181)

**Comment by scott-aquia** [comment]
There is a skeleton entry in https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/docs-deprecated/playbooks/platform_restore.md 
It refers to moving from Azure's useast to uswest by changing _location = "eastus"_ to _location = "westus"_

**Comment by scott-aquia** [comment]
Draft document (under development) is here: https://docs.google.com/document/d/18z1HLzTPkVQ7G0CiOVJDRH00ididrzhywVE8LacgatE/edit

**Comment by scott-aquia** [comment]
The BC DR doc is in the External shared Gdrive. I sent Patrick Stoneburner a note to let him know that this is part of the current sprint and he has Commenter access. I also mentioned that it is a work in progress and I expect to build it out more when we have access to Sharepoint and Azure.
