### ISSUE TITLE
Enable FHIR functions to change bundles via transforms

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#16052]
### User Story
As a user of the FHIR->FHIR transform library, I would like to be able to use custom FHIR functions to update parts of a bundle

### Description/Use Case
Due to the underlying HAPI FHIR library, there are limitations on how a FHIR bundle can be modified generically.  Custom FHIR functions enable us to cast down to resources (i.e. Base -> HumanName) so more specific actions can be taken.

### Acceptance Criteria
- [ ] The FHIR->FHIR transform library supports using a custom FHIR function to modify a part of the bundle

**Comment by arnejduranovic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16052?planning-poker) with Zenhub @adegolier @JFisk42 @david-navapbc @jack-h-wang @jalbinson @mkalish

**Comment by MichaelEsuruoso** [comment]
item completed and review
