### ISSUE TITLE
Continue FHIR Authentication wrap-up

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1605]
Continuation of #659

@pablocaviglia  - what's left to do in the next sprint?? -- put it here:

**Comment by pablocaviglia** [comment]
- add test to TestReportStream: generating a sender token and test getting a valid token from the token endpoint.
- end to end test of Auth in TestReportStream: test of pre-auth: generate a pub/private key, submit to settings, create a signed - - JWK, submit to token endpoint, use that to submit a report.
 add unit test for Sender.addJwkSet.
- Finish writing sender docs
