### ISSUE TITLE
Un-skip E2E test: receiver-status-page-user-flow.spec.ts

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#16061]
## Problem statement
During our process of creating E2E tests for the ReportStream website, we had to skip a lot of E2E tests.
After finishing the audit, we may need to re-enable some of them.

## What you need to know
- The audit of skipped tests was done in #16006
- receiver-status-page-user-flow.spec.ts (7 tests. 2 are on hold due to filter issues)

## Acceptance criteria
- [ ] Engineer confirms test is still needed. If not, consult with Product and Tech Lead for confirmation.
- [ ] If needed, test is un-skipped and working properly

**Comment by chris-kuryak** [comment]
Updated estimate to reflect recent issues with these tickets

**Comment by chris-kuryak** [comment]
May lose Joseph for the rest of the sprint and most of next sprint.

**Comment by MikaelahD13** [comment]
Spillover Reason: Final E2E tests are taking considerably longer than anticipated. Therefore, we are deprioritizing the last two in order to focus on Message Testing Automation FE work (which is a quarterly deliverable)​
