### ISSUE TITLE
MN - Failed Messages

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#16069]
## Problem statement

Minnesota has some messages that failed to be submitted.

## What you need to know

*User states*
"A few messages failed on our end due to the incorrect use of the end-of-line character, according to our IT team. Please correct the issue and re-send the following specimen IDs."

<img width="395" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1laQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e67ea1d8114c5f18e526e1b405f9f346d5beb22/image.png" alt="image.png" />

## To do

- Resubmit files

**Comment by oslynn** [comment]
SpecimenID

d1d8382c-2325-4991-9640-dff15eb7e00d

9d2015f5-2831-4488-a4b9-47bea4df1cfc

90901b81-56ff-4851-bcef-1294f2c85a01

870d92ce-9703-49f1-a1f6-2b2a93a91bc1

3f60659f-7ce5-4646-88ec-fcefdb578294

f11e0b06-5eff-40a4-9870-b333ea7a5c60

4935df5a-5ff2-47fd-a2e9-22cdf5251cbd

2406be29-413b-4ecd-8a46-6ed73637c741

1580559

4d587390-78bc-4201-9336-9226fdde28a3

1a6dff48-30db-4b65-ab25-832263876950

d0b73491-be12-4deb-a3df-c6c5b1e854ae

a98371d8-b48a-457d-900e-8b9c223d9ee0

c163c00d-1cef-4f9e-8fe4-5b8a6cbffbfe

1ce31174-07a0-470f-9906-f052445daa66

a8c544ef-a8a4-49a2-bf75-901f60ce575d

**Comment by oslynn** [comment]
<img width="1167" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzRhQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c259099b008518c5119f43872890808a48694d39/image.png" alt="image.png" />

**Comment by oslynn** [comment]
Deleted 'LF' from all files below and resubmitted to MN 2024-10-2 @ 1:43PM CST.  The ticket is closed.

18aaef96-3a16-4f22-939b-9932eccd3160.hl7
18c7f0fc-a6b6-444c-9d42-03b738ed3c6b.hl7
22757c66-1e56-40aa-b2e8-6b5c942146eb.hl7
339b3561-bfe8-44f8-8bad-dc94a5bce14b.hl7
59d86ed1-cf2f-4713-9c31-ba7f4c4df6e0.hl7
5aa10e73-4791-4605-85c8-cd465a3dbc3d.hl7
69b4cac9-d393-41f5-977c-5a6343c6d801.hl7
73f8fab3-e161-47d0-b2c1-58d888977436.hl7
766ae511-5a37-4269-9e52-45f9c48c2b25.hl7
8b156ada-5a39-45c3-bd4a-cfe8e5862b35.hl7
97ea90fd-d4d7-46d6-a9e9-c20e6d46e01a.hl7
aae5a453-3181-47fa-91f1-4647cbbe7829.hl7
b240cca7-f0c6-48d5-9912-17921cc99137.hl7
d5b25a15-8b06-415a-aa68-6485561619f8.hl7
fae9e2bc-11ca-485e-9b29-cc3ffd29333f.hl7
fc409dfb-4746-4e1f-b40f-9b2b182d2ba2.hl7
