### ISSUE TITLE
Finalize OML Mappings

### ISSUE THREAD

**Issue by JFisk42** [CDCgov/prime-reportstream#16065]
### User Story
As a Report Stream developer
I want to fully test all mapped fields for an OML message type, 
so that our integration tests will alert for fields which have been modified.

### Description/Use Case
**OML FHIR -> HL7 Mappings to complete**

- [Observation Request Note](https://github.com/CDCgov/prime-reportstream/pull/15910#discussion_r1777868507)
- [Observation Device Participants](https://github.com/CDCgov/prime-reportstream/pull/15910#discussion_r1785412974)
- [Investigate: OBR.15 Datatype issues](https://github.com/CDCgov/prime-reportstream/pull/15910#discussion_r1785499706)

**Update OML integration test**
- All currently mapped OML segments/fields should be present in the integration test hl7 data. 
- Different possible segment combinations should be added. Ex: NTE and PRT are mapped different depending on which segment group they are in. NOTE: This does not include OBX permutations.

**Update catchall integration tests**
Some of our current mapping inventory "all possible field" integration tests are missing supported fields: NK1-13, OBR-9, OBR-14, OBR-15

### Risks/Impacts/Considerations
The vast majority of test values can be taken from existing integration tests. 

### Acceptance Criteria
- FHIR->HL7 mappings for OML are finished
- All mapped fields/permutations are present in the OML integration test.
- Any missing segment-specific fields are added to their respective integration tests.

**Comment by JFisk42** [comment]
After stuffing as many notes and todos into this task as cropped up, another pass will need to be made to see if any of the low priority items here can be broken into other tickets.

**Comment by MichaelEsuruoso** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16065?planning-poker) with Zenhub @adegolier @arnejduranovic @david-navapbc @jack-h-wang @JFisk42 @kant777 @mkalish @thetaurean

**Comment by arnejduranovic** [comment]
`All possible OML fields should be mapped` -> `All possible OML fields in supported segments should be mapped`? @JFisk42

**Comment by JFisk42** [comment]
This ticket is now ready to be refined. 
Most of the originally proposed fields to add in this ticket were incorrectly identified. As part of the ORM mappings work I've created a list of mappings to update/add. I'll log a ticket for this on Monday.

**Comment by MichaelEsuruoso** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16065?planning-poker) with Zenhub @adegolier @jack-h-wang @jalbinson @thetaurean

**Comment by JFisk42** [comment]
Spillover reason: Main tipping factor this sprint was in some last minute technical changes. (These were related to OBR -> Specimen/ServiceRequest.extension mappings, [see PR Comment](https://github.com/CDCgov/prime-reportstream/pull/16539#discussion_r1844653830)). These changes had a cascade effect on test data and pushed the PR being opened.
