### ISSUE TITLE
Create Test Message Bank Page

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#16070]
## Problem statement
The backend work is complete. Now we need to create the front-end pages.

## What you need to know
- [Design in Figma](https://www.figma.com/design/iIGPoS3V2MCVsOOUZKlgiV/Receiver-Message-Testing?node-id=538-29418&node-type=canvas&t=pIFOXdcguJDjtl6W-0)
- Go to with Jessica Willis or Victor Chaparro if you need help interfacing with the APIs that Jessica Willis created
- @victor-chaparro to add API details to the ticket here

## Acceptance criteria
- [x] Message test bank screen is created per design
- [x] When a user clicks "View Message" they see the full content of an individual message in a new tab
- [x] Design, Content, and Functionality reviewed by Design lead (Jillian)
- [x] Reviewed with Tech Lead (Victor) and Product Lead (Chris) before merging

**Comment by MikaelahD13** [comment]
Spillover Reason: E2E tests took longer than expected, no engineer available to do the work.

**Comment by chris-kuryak** [comment]
Spillover Reason: Engineers were OOO last week, and still awaiting Deployment fix from DevOps to finish other tickets

**Comment by etanb** [comment]
@chris-kuryak @jillian-hammer before i begin building these pages, where will this page live within our sitemap? ie, reportstream.cdc.gov/message-testing or something equivalent.

**Comment by chris-kuryak** [comment]
Yes, but it will be on the authenticated side of the site. It is within the Receiver Settings area/interface.
Let me know if that is not already documented somewhere and I can make sure we add it accordingly.

**Comment by jillian-hammer** [comment]
hi @etanb, +1 to Chris. 

to add an extra level of detail, this is the current URL structure for editing the org settings.
`https://reportstream.cdc.gov/admin/orgreceiversettings/org/ORG-NAME/receiver/elr/action/edit`

with the addition of this feature, it could be something like:
`https://reportstream.cdc.gov/admin/orgreceiversettings/org/ORG-NAME/receiver/elr/action/edit/message-testing`
