### ISSUE TITLE
Review SonarCloud for opportunities to improve security posture

### ISSUE THREAD

**Issue by devopsmatt** [CDCgov/prime-reportstream#16076]
We want to ensure all workloads are scanned for security issues before reaching the Azure infrastructure.

DoD: 
- [ ] Documentation of gaps in security scanning
- [ ] Documentation of proposed resolution/tooling
- [ ] Look into getting access to Fortify and other existing security tooling

**Comment by scott-aquia** [comment]
There is a document here describing the coverage of Sonarcloud and making some recommendations:

https://docs.google.com/document/d/1yQTE80wLMu7-TcG32oRGwNBvEDRKTxs5RqDsOytbSPI/edit
