### ISSUE TITLE
Update Arkansas Certification

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#16071]
## Problem statement
We received an email from Arkansas that their cert needs to be updated.

## What you need to know
- Request came via email. Connect with Victor or Glenn or Chris for details/info

## Acceptance criteria

- [ ] Arkansas certification updated to avoid any gap in service

**Comment by chris-kuryak** [comment]
Does @lucero-v ? Perhaps she can screenshare and handle any access issues you have until they are overcome?

**Comment by abiphilipnava** [comment]
Reviewed the attachment that was sent to @victor-chaparro from Arkansas . It already contains a cer file. All to do is apply it to keyvault; which I do not have access to.
[rhapstage_adh_arkansas_gov24.zip](https://github.com/user-attachments/files/17925434/rhapstage_adh_arkansas_gov24.zip)

**Comment by chris-kuryak** [comment]
Per Abi: Meeting today to discuss if key file is needed. If it is not, then will close. If it is, then likely will not close by end of sprint.

**Comment by abiphilipnava** [comment]
After discussion with @GilmoreA6  and @victor-chaparro  on 12/2/2024 , there should be nothing to do.  However , as a safety caution. I created a self signed server certificate (and pem, key, csr,crt) and delivered it to Victor to put in keybase.  This is IF Needed.

**Comment by abiphilipnava** [comment]
Closing

**Comment by abiphilipnava** [comment]
We found out today  that Arkansas is using or only accepting RSA encrypted keys.  I have sent the  newly created keys to @victor-chaparro and @lucero-v  FYI To: @chris-kuryak @MikaelahD13.  Cant attach those to the ticket b/c there security

  Arkansas will need  the .cert/.crt file forark_staging.public.key
  We just need to register the forark_staging.private.key
  The Cheat Sheet Instructions is for us because there is a password in there.
  Also if you read my cheatsheet, I still recommend running them on staging and production separately.

**Comment by abiphilipnava** [comment]
CheatSheet without  passwords or private information
CheatSheet - Create Self-Signed Cert using RSA Public and Private keys with OpenSSL
====================================================================================
NOTE: This Cheatsheet is using a client/STLT for Arkansas as an example.


Enter:
1. openssl genrsa -out forark_staging.private.key 3072
	Note: This stays on ReportStream Server- aka Staging/Production. 
	Note: Recommended to run this on each Reportstream Server 
	Note: This creates a private key.

2. openssl rsa -in forark_staging.private.key -pubout -out forark_staging.public.key
	Note: This is sent to the partner/client/STLT that needs to send data into one of the  ReportStream Server(s) - aka Staging/Production. 
	Note: Recommended to run this on each Reportstream Server 
	Note: This creates the public key.
	
3. openssl req -new -x509 -key forark_staging.private.key -out arkansas_staging.cert -days 720
	Note: This create a cert that needs to be sent to the partner/client/STLT that needs to send data into one of the  ReportStream Server(s) - aka Staging/Production.
	Note: Recommended to run this on each Reportstream Server 
	Note: This creates the Self-Signed Certificate 
	Note: Enter the following when prompted, this is for Arkansas specifically. Will need to get info for respective partners/STLT/clients
			Enter: these Values when prompted

							Country Name (2 letter code) [AU]:US
							State or Province Name (full name) [Some-State]:{get from client}
							Locality Name (eg, city) []: {get from client}
							Organization Name (eg, company) [Internet Widgits Pty Ltd]: {get from client}
							Organizational Unit Name (eg, section) []: {get from client}
							Common Name (e.g. server FQDN or YOUR name) []:**************
							Email Address []:
	

4. openssl pkcs12 -export -inkey forark_staging.private.key -in arkansas_staging.cert -out arkansas_staging.cert.cert.pfx
	NOTE/OPTIONAL: Recommended to run this on each Reportstream Server 
	NOTE/OPTIONAL: Creates a pfx file for debugging purposes. It contains both public and private keys but also needs a password/passpharse to read it.
	password: ************
	Note: This is useful. It is recommended.

**Comment by abiphilipnava** [comment]
@chris-kuryak @MikaelahD13  : @victor-chaparro or Lucero will send the files to Arkansas and wait then wait to see the status.

**Comment by chris-kuryak** [comment]
Spillover: Underestimated effort -- Arkansas has seen unforeseen issues. We are continuing to work with them to overcome.

**Comment by oslynn** [comment]
After we have the Certificate from the above procedure, we need to generate the UserJks for Azure Vault as following:

1. ./openssl pkcs12 -export -in arkansas_prod.cert -inkey forark_prod.private.key -out forark_prod.p12 <Enter>
	NOTE: use password for the vault in PROD
	NOTE: export the private RSA Key into a jks file
			Enter Export Password: ****
			Verifying - Enter Export Password: ****

2 ./keytool -importkeystore -srckeystore forark_prod.p12 -srcstoretype PKCS12 -destkeystore forark_prod.jks -deststoretype JKS <Enter>
	NOTE: import the jks file from Step 1, and import into the jks keystore ; this is needed on ReportStream side to talk to the Receiver STLTS

Create Credential type UserJks for the Vault

3. ./prime create-credential --type UserJks --jks-user <from vault> --jks-file ./junk/AR/UP/CertFiles/arkansas_prod/forark_prod.jks --jks-file-pass <from vault> --jks-private-alias <from vault> --jks-trust-alias <from vault> <Enter>
       NOTE: This creates a JSON file base64 encoded file that will need to be added to the AZURE keystores through the WebUI

**Comment by oslynn** [comment]
Done
