### ISSUE TITLE
Design and implement submissions via SFTP

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#16084]
### User Story
As a sender of NSSP reports with only SFTP capabilities,
I want to submit my reports via SFTP,
so that I can submit NSSP reports according to my technical capabilities.

### Description/Use Case
Prior to our next conversation with NSSP, it has been deemed a high priority to have an SFTP bucket(s) created and the ability to automatically submit ADT files put into that bucket(s) into ReportStream's Universal Pipeline. At this time, no functionality past ingesting into ReportStream successfully is needed.

- [Pilot brief](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/doc.aspx?sourcedoc=%7B8ef1dc5c-c966-4883-8355-15ed7b009c69%7D&action=edit&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1727451132392&web=1) with known information
- Product Requirements for this ticket as of 10/7/2024:
  - SFTP locations for "test" files (non-PII) and "production" files (with PII) as part of this initial effort
  - SFTP locations are accessible by the Oklahoma hospital system (user outside of the CDC network)
  - A mechanism to automatically pull new HL7 v2.5.1 files from the SFTP into ReportStream
  - Files from the SFTP locations are received into ReportStream Staging ("test" files) and Production ("production" files) on a new topic specific to ADT data

### Dev Notes

Michael and Victor were able to set up one of the Storage Accounts to act as SFTP.

For automated connection, look into using Azure File Store trigger

### Acceptance Criteria
- [x] SFTP location(s) are set up and meet the above requirements
- [x] ReportStream can automatically ingest the files in the SFTP locations after they are uploaded
- [x] SFTP location addresses and how to access them are documented for a external users
- [x] How the automated submission engine works and where it is located is documented for a internal users

**Comment by arnejduranovic** [comment]
@brandonnava passthrough is only tested on reports containing a single message, so we need more clarification on what/how NSSP intends to send (see product brief ticket).

**Comment by MichaelEsuruoso** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16084?planning-poker) with Zenhub @adegolier @arnejduranovic @david-navapbc @jack-h-wang @JFisk42 @kant777 @mkalish @thetaurean

**Comment by MichaelEsuruoso** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16084?planning-poker) with Zenhub @jalbinson
