### ISSUE TITLE
Okta exceptions in Production

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1609]
## Acceptance Criteria
verify if this bug still exists and is a problem

## Background on the bug
Lots of exceptions yesterday, July 14, in Prod, that looked like this:

Uncaught ReferenceError: OktaSignIn is not defined
Problem Id: Uncaught ReferenceError: OktaSignIn is not defined at login
7/14/2021, 10:41:45 AM

EXCEPTION
Uncaught TypeError: n.verify is not a function
Problem Id: Uncaught TypeError: n.verify is not a function at L.r.<anonymous>

**Comment by jlusds** [comment]
Were these resolved?

**Comment by bgantick** [comment]
Closing this for now, since this was back in July. Feel free to re-open if this emerges again.
