### ISSUE TITLE
Carbon Health Onboarding – 4. Monitor in Production with Colorado

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#16095]
### Acceptance Criteria 
- [x] Contacted sender to confirm when they want to start sending  
- [x] Introduced sender to the Customer Support form and CC: the Ops team (at least Sharon Liu and Berni Xiong)  
- [x] Adjusted final settings:  
     - [x] Modified organization.yml and created yamlitos  
          - [x] Customer status = active  
          - [x] For HL7 senders, schemaName: hl7/hl7-ingest-covid-19-prod 
     - [x] Modified prod settings table  
     - [x] Modified staging settings table 

### To Do 
- [x] RS engineer: update this ticket with comments with every interaction with sender and ops team 
- [x] RS team member who originates this ticket: add dependencies:  
     - [ ] [name of company] Onboarding – Create Org and Sender Settings 
     - [ ] [name of company] Onboarding - Validate Test Files 
     - [ ] name of company] Onboarding – Testing in Staging and Prod 
     - [ ] [name of company] Onboarding – Validate Receiver 
- [x] RS team member who originates this ticket: make sure the following are included when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Sender" 
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by MikaelahD13** [comment]
CO had some issues with prod data from Carbon Health, they are fixing and we will continue to monitor​

**Comment by chris-kuryak** [comment]
Per Victor: Issue has been fixed and can be closed.
