### ISSUE TITLE
Content Changes for Sender API Guide Formatting and Validation

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#16106]
## Problem statement
It has been identified that Step 1 of the Sender API Guide has inaccurate information, leading to confusion by the end user when trying to format and validate a fake data file. The formatting requirements are different for RADxMARS senders vs other ELR senders. This needs to be represented in the API Documentation correction

## What you need to know

- [Step 1 on this page](https://reportstream.cdc.gov/developer-resources/api/getting-started)
- Content doc [link](https://app.mural.co/t/nava4113/m/nava4113/1693235939456/bfb3ad5f9bc686236af99cd4ff3dc856e1187346?sender=u0c3cdba5126734aceb613229)

## Acceptance criteria

- [x] Tech Lead (Victor) has identified what information needs to be changed so that both types of senders can use Step 1 of the Getting Started Guide
- [x] Content and/or Design changes documented for handoff to engineering
- [x] Engr ticket created (with Product)

## To do
Jillian and Chris to discuss:
- [ ] Does the PDF version have any information that the web version does not?
- [ ] Shall we retire the PDF version for now since we have reduced capacity to keep them in sync?
- [x] (I know this was discussed before) Is there a low lift to just have a "print guide" button that dynamically generates a printout of the entire guide so that we don't have to manually sync both of them each time

**Comment by jillian-hammer** [comment]
Putting together draft in the content doc [here](https://app.mural.co/t/nava4113/m/nava4113/1693235939456/bfb3ad5f9bc686236af99cd4ff3dc856e1187346?sender=u0c3cdba5126734aceb613229).

**Comment by jillian-hammer** [comment]
content reviewed by @victor-chaparro - thank you! 

it was a low lift to update the PDF from a content perspective, so i included the PDF updates for this iteration. we can open the conversation back up if we need a larger programmer's guide update in the future @chris-kuryak. 

closing this ticket and creating eng implementation ticket #16289.
