### ISSUE TITLE
Have the Programmer's Guide good enough to send out

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1612]
Work with Berni to wrap up a first pass on this.

The guide is done when its good enough to send out to new Senders.

Note:  Our plan for the moment is to keep it as a shared .docx in CDC Sharepoint, but we also considered putting it in a .md file in GitHub.

**Comment by joemeree** [comment]
Finished my first pass with track changes on.  Send Berni the source file.  (Also getting feedback from Bill Marquardt today).   Once we agree that the CSV sample file is good, I'll convert that to HL7.

**Comment by BerniXiongA6** [comment]
7.19.2021 Guys, I realized there are two issues associated with this guide so I'm pasting below what I submitted on Friday afternoon on Issue [#1404](https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/1404). @joemeree @jimduff-usds 

7.16.2021 Here's the RS programmers user guide with both Joe's and my revisions. I've accepted most marked changes since they were design/formatting revisions. I've left the comments open in the right pane since they'll need input from the team. I used the RS content style guide when editing (so that's why you'll see a slightly different layout). If I missed anything, we can do a final clean up before sending it off. I'm happy to help with that. @jimduff-usds can you review the comments and take another peek at the guide? cc: @joemeree @hie1

https://app.zenhub.com/files/304423150/e74d61f9-f7c8-4154-bcaa-47678c60cd34/download

**Comment by joemeree** [comment]
I've sent this to two senders and didn't get any feedback so I guess it's "good enough".

**Comment by BerniXiongA6** [comment]
@joemeree here's the most current version where I've now accepted most the marked changes BUT I kept the pending comments open. Can you review and reply to the comments? I'll then remove them, make any other necessary edits, and wrap this up in a bow. Thanks! cc: @anshulkumar-usds @jimduff-usds 

[https://app.zenhub.com/files/304423150/46a434db-e296-43cd-833f-78051ffcc7f6/download](https://app.zenhub.com/files/304423150/46a434db-e296-43cd-833f-78051ffcc7f6/download)

**Comment by BerniXiongA6** [comment]
7.23.2021 @joemeree and I agree to connect on Monday to discuss suggested edits / pending questions that need clarification before edits can be made (comment also left in Issue # 1404).

**Comment by joemeree** [comment]
Joe's changes with track changes on.  Add Appendix A Field Definitions table.  Tweaked some language around test submissions.  [https://app.zenhub.com/files/304423150/261b3a46-74ab-4db6-a281-035d7233b509/download](https://app.zenhub.com/files/304423150/261b3a46-74ab-4db6-a281-035d7233b509/download)

**Comment by BerniXiongA6** [comment]
7.28.2021 Met with @joemeree to review pending comments and revise any edits in question. All marked changes have been accepted. All resolved comments have been deleted. There are a couple pending comments for @jimduff-usds to review/reply to. Happy to put my eyes on it again after you review/edit. 

Here's the current version of the draft: 
[https://app.zenhub.com/files/304423150/7c0178c1-bcb4-4e3f-8a31-b684fb73d336/download](https://app.zenhub.com/files/304423150/7c0178c1-bcb4-4e3f-8a31-b684fb73d336/download)

cc: @anshulkumar-usds

**Comment by jimduff-usds** [comment]
@joemeree , @BerniXiongA6 , thanks for your great work on this!

I made a few last updates, including changing to an HL7 example that includes the AOE questions, and changed it to version 1. 
[https://app.zenhub.com/files/304423150/9c46af1f-da40-4337-b1e6-1a0d30a86e90/download](https://app.zenhub.com/files/304423150/9c46af1f-da40-4337-b1e6-1a0d30a86e90/download)

And here's a pdf version I plan to send out today:
[https://app.zenhub.com/files/304423150/5ec10aa1-f20c-4fc8-9035-83f4654f3b84/download](https://app.zenhub.com/files/304423150/5ec10aa1-f20c-4fc8-9035-83f4654f3b84/download)

Still to be done:
- character encoding section
- tips and tricks section
- etc

**Comment by BerniXiongA6** [comment]
8.5.2021 Final RS Programmer's Guide in Clickable PDF:

[https://app.zenhub.com/files/304423150/e03c03fc-46c4-4f45-904e-ece15143fe8c/download](https://app.zenhub.com/files/304423150/e03c03fc-46c4-4f45-904e-ece15143fe8c/download)

**Comment by BerniXiongA6** [comment]
8.6.2021 Final RS Programmer's Guide in Clickable DOC:

[https://app.zenhub.com/files/304423150/571d95ce-bb3f-48ef-b977-a41d779c3ab3/download](https://app.zenhub.com/files/304423150/571d95ce-bb3f-48ef-b977-a41d779c3ab3/download)
