### ISSUE TITLE
Update Lineage Tracking in FHIRReceiver Function

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#16148]
### User Story

As the owner of the ReportStream Architecture,
I want the FHIRReceiver pipeline step to implement lineage tracking correctly,
so that FHIRReceiver behaves the same as other UP steps in this regard.

### Description/Use Case
> **CONTEXT:** Ticket #16011 was created following the [initial FHIRReceiver implementation](https://github.com/CDCgov/prime-reportstream/pull/15621) and the [QueueMessage followup](https://github.com/CDCgov/prime-reportstream/pull/15928) to rethink how the "submission specific" events should be designed. Upon further investigation, it has been decided Ticket #16011 should be closed and instead the FHIRReceiver should be updated so that a new event is not required. The initial implementation deviated from the normal report and lineage creation/handling and should be brought back in line. Once this is done, the submission specific events can go away and reuse the currently existing Report events.

### Acceptance Criteria
  - [x] FHIRReceiver does not duplicate logic in the FHIR Converter
  - [x] A missing sender is a handled error that results in the message being put on the poison queue

**Comment by MichaelEsuruoso** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16148?planning-poker) with Zenhub @adegolier @arnejduranovic @david-navapbc @jack-h-wang @jalbinson @JFisk42 @kant777 @mkalish @thetaurean
