### ISSUE TITLE
Update UP Exception Handling Strategy

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#16140]
### User Story

As the owner of the Universal Pipeline,
I want exceptions to be caught by default and handled gracefully,
so that I do not have to rely on the built-in azure retry logic which comes with its own downsides.

### Description/Use Case

See [Receiver Enrichment SRD](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/doc2.aspx?sourcedoc=%7BCD15C571-D563-4135-B293-6FFAA77826AE%7D&file=SRD-ReceiverEnrichment.docx&action=default&mobileredirect=true) for the requirements of this feature. Each step's requirements in this document outlines the strategy like so:

1. Not modify the database at all for any item (i.e. not process any items) 
2. Generate a `PIPELINE_EXCEPTION` Azure Event 
3. Manually populate `<specific-step>-poison` Azure Queue with the passed in `QueueMessage`  
4. Exit the pipeline step gracefully 

See the "Handling Failures" section of the document for more details.

### Acceptance Criteria

- [ ] Updated UP exception handling per [Receiver Enrichment SRD](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/doc2.aspx?sourcedoc=%7BCD15C571-D563-4135-B293-6FFAA77826AE%7D&file=SRD-ReceiverEnrichment.docx&action=default&mobileredirect=true) for all UP steps.
- [ ] Update the blob trigger handling for the SFTP ingestion

**Comment by MichaelEsuruoso** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16140?planning-poker) with Zenhub @adegolier @arnejduranovic @david-navapbc @jack-h-wang @JFisk42 @kant777 @mkalish @thetaurean @jalbinson

**Comment by MichaelEsuruoso** [comment]
@mkalish closing out ticket. Does not require a demo
