### ISSUE TITLE
Implement Translate Step Updates

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#16144]
### User Story

As the owner of the RS Architecture,
I want the Translate step to implement the latest SRD,
so that it can function as intended.

### Description/Use Case

The  [ReceiverEnrichment SRD](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/doc2.aspx?sourcedoc=%7BCD15C571-D563-4135-B293-6FFAA77826AE%7D&file=SRD-ReceiverEnrichment.docx&action=default&mobileredirect=true) outlines new requirements for the Translate step in the section titled "Translate Step Software Requirements". These new requirements should be implemented and the existing ones should be verified.

### Acceptance Criteria

- [ ] Implemented Translate Step requirements outlined in [ReceiverEnrichment SRD](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/doc2.aspx?sourcedoc=%7BCD15C571-D563-4135-B293-6FFAA77826AE%7D&file=SRD-ReceiverEnrichment.docx&action=default&mobileredirect=true)
- [ ] Existing Requirement should be verified and make sure there are unit tests

**Comment by MichaelEsuruoso** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16144?planning-poker) with Zenhub @adegolier @arnejduranovic @david-navapbc @jack-h-wang @JFisk42 @kant777 @mkalish @thetaurean @jalbinson

**Comment by MichaelEsuruoso** [comment]
@arnejduranovic  we need some clarifications on the document and AC.
