### ISSUE TITLE
Implement Convert Step Updates

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#16143]
### User Story

As the owner of the RS Architecture,
I want the Convert step to implement the latest SRD,
so that it can function as intended.

### Description/Use Case

The  [ReceiverEnrichment SRD](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/doc2.aspx?sourcedoc=%7BCD15C571-D563-4135-B293-6FFAA77826AE%7D&file=SRD-ReceiverEnrichment.docx&action=default&mobileredirect=true) outlines new requirements for the convert step in the section titled "Convert Step Software Requirements". These new requirements should be implemented and the existing ones should be verified.

### Acceptance Criteria

- [ ] Implemented Convert Step requirements outlined in [ReceiverEnrichment SRD](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/doc2.aspx?sourcedoc=%7BCD15C571-D563-4135-B293-6FFAA77826AE%7D&file=SRD-ReceiverEnrichment.docx&action=default&mobileredirect=true)
- [ ] Update convert step to only stamp extensions for the appropriate message type (ex: condition codes only should be stamped on ELR messages, not test orders)

**Comment by MichaelEsuruoso** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16143?planning-poker) with Zenhub @adegolier @arnejduranovic @david-navapbc @jack-h-wang @jalbinson @JFisk42 @kant777 @mkalish @thetaurean

**Comment by MichaelEsuruoso** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16143?planning-poker) with Zenhub @wcutshall

**Comment by MichaelEsuruoso** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16143?planning-poker) with Zenhub @adegolier

**Comment by MichaelEsuruoso** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16143?planning-poker) with Zenhub @JFisk42
