### ISSUE TITLE
Update ORM HL7v2 -> FHIR Mappings

### ISSUE THREAD

**Issue by JFisk42** [CDCgov/prime-reportstream#16146]
### User Story
As a sender of ORM reports,
I want the ORM mappings to properly handle CE fields,
so that I can send ORM reports with no data loss.

### Description/Use Case
We currently have ORM HL7 -> FHIR mappings that are using the catchall mappings. A number of fields throughout those mappings use CE, and these are getting lost during hapi conversion due to our system using HL7v2 for all Hapi conversions. These fields should be faithfully retaining the data during conversion to FHIR.
**Additionally**, we need to put mapping integration tests in place to ensure similar data loss does not occur again.

### Dev Notes
[Related fix for ORU/OBX fields](https://github.com/CDCgov/prime-reportstream/pull/14724), [Related fix for all OML CE fields](https://github.com/CDCgov/prime-reportstream/pull/15910/commits/258e3b66c3393e67dc529f4d72aca1461bab7578).

### Acceptance Criteria
- All mapped fields for ORM are present after conversion to FHIR
- Integration test for a fully mapped ORM HL7 -> FHIR message is in place. A second integration test which utilizes OML mappings for FHIR->HL7 would also allow a faithful HL7->FHIR->HL7 scenario.

**Comment by MichaelEsuruoso** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16146?planning-poker) with Zenhub @adegolier @arnejduranovic @david-navapbc @jack-h-wang @JFisk42 @kant777 @mkalish @thetaurean

**Comment by MichaelEsuruoso** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16146?planning-poker) with Zenhub @jalbinson

**Comment by MichaelEsuruoso** [comment]
No demo needed.
