### ISSUE TITLE
RS Installation for Windows Environment Documentation updates

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#16167]
## Problem statement
The Installation instructions for setting up the ReportStream environment on Windows OS and Linux OS regardless of distribution were not accurate and could not be completed successfully. Therefore, the documentation needs to be updated to allow future engineers to set up an environment in these operating systems successfully.

## What you need to know
- [Existing Documentation](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting-started/README.md)

## Acceptance criteria

- [ ] Documentation is updated and a new engineer can use it to successfully set up the RS environment on Windows OS and Linux OS

**Comment by chris-kuryak** [comment]
Abi is currently working to finish up this documentation. Should be finished next week

**Comment by abiphilipnava** [comment]
Uploaded Document notes for Windows installation. Needs Review from Victor .Attached is the document
[RS Installation for Windows Environment Documentation updates.docx](https://github.com/user-attachments/files/17636166/RS.Installation.for.Windows.Environment.Documentation.updates.docx)
