### ISSUE TITLE
Importing JosiahSiegel GHA: git-secrets@latest

### ISSUE THREAD

**Issue by emvaldes** [CDCgov/prime-reportstream#16186]
**Profile**: **[JosiahSiegel](https://github.com/JosiahSiegel)**
**Status**: Importing (In-Progress)

**Objective**: Prevent committing AWS , AZURE and GCP sensitive credentials to a git repository.

**Target**: [git-secrets@v1.3.0 : ad82d68](https://github.com/JosiahSiegel/git-secrets/tree/ad82d68ee924906a0401dfd48de5057731a9bc84)
**Latest**: [git-secrets](https://github.com/JosiahSiegel/git-secrets/tree/bff90684a2289cd3b0536a2cbeb37728e30680fd) ->  (`bff90684a2289cd3b0536a2cbeb37728e30680fd`)

**Warning**: This is a fork to another repository [msalemcode/git-secrets](https://github.com/msalemcode/git-secrets)

The `git-secrets` repository by Josiah Siegel is a fork of the original `git-secrets` tool developed by AWS Labs. This tool is designed to prevent the accidental inclusion of sensitive information, such as passwords, API keys, and other secrets, into Git repositories.

**Repository Overview:**

- **Purpose:** The primary function of `git-secrets` is to scan commits, commit messages, and --no-ff merges to prevent adding secrets into your Git repositories. If a commit, commit message, or any commit in a --no-ff merge history matches one of your configured prohibited regular expression patterns, then the commit is rejected. 

- **Key Features:**
  - **Pattern Matching:** Allows users to define custom patterns to detect sensitive information.
  - **AWS Integration:** Provides built-in patterns to detect AWS credentials and can be extended to other services.
  - **Pre-Commit Hooks:** Integrates with Git's commit hooks to enforce secret scanning before commits are finalized.
  - **History Scanning:** Offers the ability to scan the entire repository history for secrets.

**Technical Evaluation:**

- **Pattern Configuration:** Users can add prohibited patterns using the `--add` option and allowed patterns using the `--add --allowed` option. 

- **AWS Patterns:** The `--register-aws` option adds common AWS patterns to the git config and ensures that keys present in `~/.aws/credentials` are not found in any commit. 

- **Pre-Commit Hook Installation:** The `--install` option installs Git hooks for a repository. Once the hooks are installed, commits and non-fast-forward merges for that repository will be prevented from committing secrets. 

- **History Scanning:** The `--scan-history` option scans the repository, including all revisions, to detect any committed secrets. 

**Relevance to Your Pipeline:**

Integrating `git-secrets` into your GitHub workflows can significantly enhance security by preventing the inclusion of sensitive information in your codebase. By setting up pre-commit hooks, you can enforce secret scanning at the commit level, ensuring that secrets are not inadvertently committed. Additionally, the ability to scan the entire repository history allows for the detection and remediation of previously committed secrets.

**Conclusion:**

The `git-secrets` tool is a valuable addition to any development pipeline, providing an extra layer of security by preventing the inclusion of sensitive information in Git repositories. Its integration into GitHub workflows can help maintain the integrity and confidentiality of your codebase.

**Comment by emvaldes** [comment]
It seems this specific GitHub Action is not based on any actions or workflows but rather a collection of BATS and Git configurations.

**Comment by emvaldes** [comment]
This GitHub Action (targeted to be imported as a remote/external) is no longer in consideration until we can further evaluate if they are worth the effort to be imported at a later stage.

**Warning**: I have placed it into the "IceBox" stage as it is out of scope for now.

**Comment by emvaldes** [comment]
``` console
devops: prime-reportstream (main=) $ git checkout -b devsecops/emvaldes/git-secrets ;
Switched to a new branch 'devsecops/emvaldes/git-secrets'

devops: prime-reportstream (devsecops/emvaldes/git-secrets) $ git push --set-upstream origin devsecops/emvaldes/git-secrets ;

Total 0 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
remote: 
remote: Create a pull request for 'devsecops/emvaldes/git-secrets' on GitHub by visiting:
remote:      https://github.com/CDCgov/prime-reportstream/pull/new/devsecops/emvaldes/git-secrets
remote: 
remote: GitHub found 3 vulnerabilities on CDCgov/prime-reportstream's default branch (2 high, 1 low). To find out more, visit:
remote:      https://github.com/CDCgov/prime-reportstream/security/dependabot
remote: 
To https://github.com/CDCgov/prime-reportstream.git
 * [new branch]          devsecops/emvaldes/git-secrets -> devsecops/emvaldes/git-secrets
branch 'devsecops/emvaldes/git-secrets' set up to track 'origin/devsecops/emvaldes/git-secrets'.
```

**Comment by bethbeza** [comment]
Step 1: Checkout the MAIN branch
git checkout main

Step 2: Update the MAIN branch
git pull

Step 3: Create a new branch
git checkout -b devsecops/bethbeza/reliable-pull-request-action

Step 4: Push the new branch to the remote repository
git push --set-upstream origin devsecops/bethbeza/reliable-pull-request-action

Step 5: Create a target container (folder)
mkdir reliable-pull-request-action
cd reliable-pull-request-action

Step 6: Clone the external GitHub Action repository
git clone https://github.com/JosiahSiegel/reliable-pull-request-action.git .

Step 7: List the file structure
Get-ChildItem -Recurse -Force

Step 8: View the Git log
git log

**Comment by bethbeza** [comment]
For Step 7, I had to switch the `tree -a` command (since it’s Unix-based) to `Get-ChildItem -Recurse -Force`, which works in PowerShell.

**Comment by bethbeza** [comment]
GIT pull to finally get the dependabot.yml file. woot woot! <img width="1361" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekVZQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7489e279d12e53a1b10f524ddc5609e9197e45c4/image.png" alt="image.png" />
