### ISSUE TITLE
A report for a receiver should always go through a SEND transport

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#16191]
### User Story
As a receiver of Reports,
I would like reports destined to me to always go through a send transport and default to the NullTransport if I do not have one configured,
so that my data can show up in the Daily Data page correctly.

### Description/Use Case
The transports are responsible for handling a lot of record keeping when they process the report (such as lineage tracking uploading the contents of the sent report) that does not happen if a receiver is not configured with any transport.  This leads to downstream complications such as the daily data fetching a list of reports from the batch step rather than the send step leading to slightly inaccurate data.

### Risks/Impacts/Considerations
Does this impact the following?: https://github.com/CDCgov/prime-reportstream/issues/15644

### Dev Notes
- Which transport is used is configured [here](https://github.com/CDCgov/prime-reportstream/blob/51a8a01f93260e3dcce71ba7962a85163d35c532/prime-router/src/main/kotlin/azure/SendFunction.kt#L157)
- [NullTransport](https://github.com/CDCgov/prime-reportstream/blob/51a8a01f93260e3dcce71ba7962a85163d35c532/prime-router/src/main/kotlin/transport/NullTransport.kt#L15)

### Acceptance Criteria
- [ ] A report for a receiver uses a default Null transport when no transport is configured

**Comment by arnejduranovic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16191?planning-poker) with Zenhub @adegolier @david-navapbc @jack-h-wang @jalbinson @JFisk42 @mkalish

**Comment by arnejduranovic** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16191?planning-poker) with Zenhub @thetaurean
