### ISSUE TITLE
Missing WATERS field names in certain errors

### ISSUE THREAD

**Issue by joemeree** [CDCgov/prime-reportstream#1620]
**Describe the bug**
A clear and concise description of what feature is not working.

**Impact**
Please describe the impact this bug is causing to your program or organization.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimduff-usds** [comment]
Closing.  No waters work ongoing at this time.
