### ISSUE TITLE
update submission-to-monilith flow without pulling too many shared packages from monolith into shared library

### ISSUE THREAD

**Issue by david-navapbc** [CDCgov/prime-reportstream#16238]
### User Story
As a RS submitter
When the RS Azure Function Application has an issue with availability or performance,
I want to continue to be able to submit reports to RS

### Description/Use Case
When RS monolith goes down it takes with it the ability for senders to submit new reports. We've done some work to create micro-services for the authentication and submission features of RS so as to decouple them from the monolith. The idea is to make it so when the monolith goes down senders don't need to know or care because from their perspective they can submit reports as they always have without issue. The idea is to handle this in a way that doesn't involve co-locating dependencies from the monolith in both the monolith and the submissions service because package references in the monolith are highly coupled with other package references and things got messy when we tried that path. See Dev Notes for more detail. 

### Risks/Impacts/Considerations
If monolith is down when submissions come in it's important that the monolith is triggered to process the data that was submitted while it was offline. 

### Dev Notes
We've decided to use a queue message trigger to have submission service communicate new work to the receive function in the Azure Function App. Instead of what we tried to do previously by migrating QueueMessage classes to a shared library we're instead going back to an earlier approach of creating a submission-service-only QueueMessage that can be used for this flow only and will not require pulling out a lot of exogenous QueueMessage adjacent code from the monolith and into the shared library. The shape of the Submission QueueMessage should be the same shape as what is expected by the receive function.

for more information see 

this [ticket](https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/15761) 

this draft [pr](https://github.com/CDCgov/prime-reportstream/pull/15923)

and the attached SRDs for more information as to previous approaches to solving this problem. 

ReceiverEnrichment SRD [ReceiverEnrichmentSRD.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTlQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38fef0eb95b448c5726c847700e9ff18a6174db9/ReceiverEnrichmentSRD.pdf)

Microservice SRD [rs-as-microservices.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkJQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--078beec68fb800923caa1434b874d66001a589a9/rs-as-microservices.pdf)

### Acceptance Criteria
* submission-only queue message is put back into submission service and shared lib 
* monolith is set to respond to queue message azure function trigger tied to that submission-only queue message class 
* trigger works in a way to where if monolith is down when new reports are submitted, those reports are submitted once monolith is back online.

**Comment by arnejduranovic** [comment]
This ticket has been merged with https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/16239. Closing this one as duplicate.
