### ISSUE TITLE
Implement updates to the API Programmer's Guide online content + PDF

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#16289]
## Problem statement
To address user feedback, we updated some content on the API Programmer's Guide. See #16106 and #15997 for reference.

## What you need to know
The website needs to be updated using the content doc linked below.
- [Content doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Website%20content/Programmer%27s%20Guide%20updates/20241018_API_guide_content_updates.docx?d=w4563ca769bb840bdb617890ba194c4c0&csf=1&web=1&e=dCvttH)

## Acceptance criteria

- [x] Web content updated 
- [x] PDF download updated 
- [x] Tag @jillian-hammer in PR

**Comment by chris-kuryak** [comment]
Delaying since more content updates are needed in this section.

**Comment by jillian-hammer** [comment]
@jpandersen87 word doc and pdf version for you:

- pdf: [20241018_API_guide_content_updates.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW1VQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bceb84a76e02d423d2c3267673daa24af1fdc90b/20241018_API_guide_content_updates.pdf)
- doc: [20241018_API_guide_content_updates.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXFVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86213a64e0a0ec79e7d8cfdc03b3e8eaa6ac8326/20241018_API_guide_content_updates.docx)
