### ISSUE TITLE
Create HAPI HL7 classes for ORM and OML Messages

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#16307]
### User Story

As a Sender of ORM and OML versions 2.5.1 -> 2.7 greater,
I want the RS UP to losslessly process my message,
so that the receiver can receive all the data it contains

### Description/Use Case

Presently, for deserializing HL7v2 messages, RS uses the built-in definitions of the ORM and OML classes provided by the HAPI HL7v2 library. These classes are not fully compatible with all the different versions of ORM and OML RS may receive, and are incomplete in many cases. Thus, just like how we did for ORU_R01 in `prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory`, we want to add our own classes based on the following:
- CARISTIX ORM and OML definitions for all version 2.5.1+
- HL7v2 -> FHIR Mapping Inventory 
- LOI Nist Profile Specification

### Dev Notes

This will be very similar to what we did for ORU_R01 where the goal is to undeprecate all fields and expand the type to the largest version in the spec (i.e. some 2.5.1 fields are CE, but in 2.7 they are CWE, so the a new class should set them as CWE)

### Acceptance Criteria

- OML classes created in `prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory`
- ORM classes created in `prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory`

**Comment by JFisk42** [comment]
This work should be able to address the comment here and remove our (temporary) dependency with hapi v26: https://github.com/CDCgov/prime-reportstream/pull/16299#discussion_r1812050625

**Comment by MichaelEsuruoso** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16307?planning-poker) with Zenhub @adegolier @jack-h-wang @JFisk42 @mkalish @thetaurean

**Comment by MichaelEsuruoso** [comment]
@arnejduranovic @david-navapbc @kant777  this ticket is pointed, please review pointing  if you have questions

**Comment by MichaelEsuruoso** [comment]
item was picked up mid-sprint
