### ISSUE TITLE
[Bug]: Downloading a HL7 file from Daily Data garbles the 'µ' character in the content of the file

### ISSUE THREAD

**Issue by basiliskus** [CDCgov/prime-reportstream#16309]
### Contact Details

cdc-ti@flexion.us

### What happened?

When downloading a HL7 file that contains 'µ', the character gets garbled to �. We have confirmed that downloading the same file directly from the Azure blob storage encodes the file correctly, so it only happens when downloading from Daily Data.

We look into the issue and found the RS frontend is using the [download](https://github.com/rndme/download) library in Daily Data, which has this open issue since 2017: [1.4.6+ broke downloading files with non-ASCII charachers](https://github.com/rndme/download/issues/56). We've also confirmed the HTTP response that gets the content of the file before downloading, has the 'µ' shown correctly, so everything seems to point to this bug in the download library.

We're sending the 'µ' character in a `ORU` message as part of the `µmol/L` unit in `OBX-6`

### Version

1.0.2 (Default)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
No logs to show
```

## Acceptance Criteria
- [ ] Try testing first by calling the API directly to see if the same response/error happens. Note that response in the ticket
- [ ] Download functionality works as expected without error
- [ ] Point this ticket with proper amount of work estimate before closing

**Comment by chris-kuryak** [comment]
Per ETOR team, would like to have this solved prior to CA Go-Live which is lated for Nov 18, 2024

**Comment by MikaelahD13** [comment]
Spillover Reason: Incomplete Requirements and Resource Unavailability – This bug did not have enough information as reported by Flexion team to be able to fix appropriately. But should be fixed by the end of the week.

**Comment by chris-kuryak** [comment]
From Basilio Bogado 11/20 in Slack:

> FYI, I tried the same steps today in staging and everything is working as expected. There's no garbled characters anymore when I download the file. Thanks!

So ReportStream is closing this ticket.

**Comment by chris-kuryak** [comment]
@MikaelahD13 removing this spillover as it was closed by Etan before midnight on 11/19.
Will update our Sprint Review deck accordingly.
