### ISSUE TITLE
master -> main: update automation, setting

### ISSUE THREAD

**Issue by devopsmatt** [CDCgov/prime-reportstream#16375]
We are getting with the times and migrating from `master` to `main` as primary branch 🎉 
This work should be ideally contained in a single PR for easy switchover.

Tasks in scope:
- [x] Update all GH workflows and actions to reflect this change
- [x] Identify all matching branch occurrences and update those as well across the repo, excluding app code.
- [x] Update primary branch and branch protections in GH Settings (not part of PR but settings should be reviewed so we can execute on that at the time of PR merge.)

Not in scope:
- [x] Any application code

DoD: Single PR ready for review with all changes included.  Github settings identified, ready to edit and to save.

**Comment by emvaldes** [comment]
<img width="499" alt="Screenshot 2024-11-06 at 09 59 42" src="https://github.com/user-attachments/assets/dbf38336-a61c-4cdc-bdd6-7fc6b691e6e3">
<img width="466" alt="Screenshot 2024-11-06 at 09 59 50" src="https://github.com/user-attachments/assets/5dba0046-832c-4531-876d-4478b743fea0">
<img width="795" alt="Screenshot 2024-11-06 at 10 00 05" src="https://github.com/user-attachments/assets/ca748cb4-49fd-4703-b636-2dc22f2d20cd">

**Comment by emvaldes** [comment]
<img width="339" alt="Screenshot 2024-11-06 at 10 26 46" src="https://github.com/user-attachments/assets/dc992db2-73bb-4efb-815f-38dc305c8077">
