### ISSUE TITLE
[BUG] Daily data filter don't work after navigating to a different page

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#16385]
## Problem statement

When loading the daily data page and navigating to a different page to look at additional results filtering by dates does not work.

## What you need to know

Steps to reproduce:

- Load daily data page with ignore data.
- Select FULL_ELR receiver.
- Enter 10/19/2024 on From
- Enter 10/22/2024 on To
- Click apply and you get back some results.
- Click reset
- Select FULL_ELR receiver.
- Go to page 4.
- Enter 10/19/2024 on From
- Enter 10/22/2024 on To
- Click apply and you get no results.

## Acceptance criteria

- [x] Filtering on Daily data works
- [x] Point this ticket with time/effort it took before closing (1-2 = Low, 3-5 = medium, 8-13 = high)

**Comment by MikaelahD13** [comment]
Spillover Reason: This bug did not get started due to not having an engineer to work on it (E2E tests took too long).​
