### ISSUE TITLE
Implement Basic Synchronous Accept ACK in Submission API per LRI/LOI spec to meet immediate Flexion ETOR needs

### ISSUE THREAD

**Issue by brandonnava** [CDCgov/prime-reportstream#16394]
### User Story
As a ReportStream ETOR sender (EPIC EHR),
I want message confirmation ACKs sent to me following industry standard LOI/LRI specification,
so that the EHR integration with RS works and I can ensure the timely delivery of my data

### Description/Use Case
This ticket is to specifically implement Basic Synchronous Accept ACKs for our Submission API per [Flexion's Product Requirements](https://cdc.sharepoint.com/:w:/r/teams/OLSS_ETOR_ReportStream/Shared%20Documents/ReportStream%20ETOR%20ACK%20Requirements.docx?d=we5a9fae68cd24c99a757f027562c1737&csf=1&web=1&e=x3lgDZ) to support their first test order integration with a hospital that is using EPIC EHR.

### Dev Notes
Read Flexion's Requirements for requirements on how the HL7v2 ACK message should be structured.

**RS Additional Technical Requirements:**

Determine if a sender wants to use ReportStream's "HL7v2 ACK Support" via a new sender setting. RS submission endpoint shall return a positive ACK once the message has been received. The ACK will be in the form of a HTTP response with an HL7v2 ACK message in the body if the sender has a setting indicating they want "HL7v2 ACK support" AND MSH-15 (Accept Acknowledgment Type) field indicates they want to receive a basic ACK message, otherwise the body shall contain the standard RS JSON history object. It is not exactly clear how Batched messages can be handled, so this logic will only apply to single HL7v2 messages and batched messages will have the usual RS behavior.

The above shall be implemented specifically for the waters submission endpoint. Submission microservice implementation can be done later.

### Acceptance Criteria

- [ ] A Sender can send a test order message (HL7v2) and get back a valid HL7 ACK message
- [ ] ACK support implementation meets requirements provided by Flexion and additional tech requirements in dev notes
    - [ ] The ACK message contains the MSH and MSA fields outlined in the ETOR ACK Requirements doc
- [ ] Implementation is compatible with all specifications listed at the bottom of the aforementioned product requirements document. If not, exceptions are detailed in this ticket.

**Comment by MichaelEsuruoso** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16394?planning-poker) with Zenhub @adegolier @arnejduranovic @david-navapbc @jack-h-wang @jalbinson @JFisk42 @kant777 @mkalish @thetaurean

**Comment by MichaelEsuruoso** [comment]
Team needs access to docx

**Comment by MichaelEsuruoso** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16394?planning-poker) with Zenhub @wcutshall

**Comment by MichaelEsuruoso** [comment]
item was picked up mid sprint

**Comment by MichaelEsuruoso** [comment]
@arnejduranovic is OOO @JFisk42 will review change requested and i will close out ticket is changes checks out. (per my request)

**Comment by JohnNKing** [comment]
Feedback from one of our partners (Ochsner): ACKs in `staging` are working as expected for orders sent from Epic! 🎉
