### ISSUE TITLE
Review and comment on de-duplication

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1644]
DONE when:  comments are available here IN THIS TICKET on this posting from Krishna at NIH:
"Identifying Unique Test Results for Purposes of De-duplication"
https://www.nibib.nih.gov/identifying-unique-test-results

Its just meant to be a straightforward proposal to set a standard on how to ensure unique records in the health ecosystem.

**Comment by joemeree** [comment]
This might work.  Once we have the WATERS production data flowing to HHS Protect through ReportStream, I'll have Kevin take a look in Protect to see if he can catch the duplicates.  1. We don't always get the SPM record  2. It's not in the WATERS CSV format)

**Comment by joemeree** [comment]
7/27 asked kevin arvai to see if he has patient id assigner and specimen id assigner in any of the senders he can see in HHS Protect.

**Comment by joemeree** [comment]
Krishna called me today and we decided that in the short term we can just use patient unique id + specimen id to detect duplicates.  It's extremely unlikely that we would get that same combination randomly from two different tests.  The additional fields he has are are more rigorous solution that should be applied to future development.  I'll update kevin and see if he can use those two fields and pull a Protect report.

**Comment by joemeree** [comment]
Closing this because we don't have to do anything more.  We already have patient unique id + specimen id and it's a simple matter to run a group by SQL query in HHS Protect to detect duplicates.  I've asked Kevin Arvai to do that.
