### ISSUE TITLE
Document "Unsupported browser" 404 page across website & content artifacts

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#16448]
## User story
As a ReportStream team member, I want to know what website pages are available for external users so that I can track content / design changes.

## Background & context

The frontend team built a [404 page that the website redirects unsupported browsers to](https://reportstream.cdc.gov/unsupported-browser.html). We need to make sure that this page is documented across our website tracking systems. 

## Working links

- Mural: [Sitemap](https://app.mural.co/t/primedatainput6410/m/nava4113/1671805673271/ba355d0f84b6f3cc2c4334610ca86aee3e9d52f2?sender=u0c3cdba5126734aceb613229)
- Content tracker: [Link](https://cdc.sharepoint.com/teams/ReportStream/Lists/ReportStream%20content%20tracker/AllItems.aspx?viewid=70d3304e%2D44a7%2D459c%2Db92a%2D2953d8d259b4)

## Acceptance criteria

-   [x] Update sitemap
-   [x] Update content tracker
-   [x] Create content document

**Comment by jillian-hammer** [comment]
11/12/24: Included this page on the [sitemap](https://app.mural.co/t/primedatainput6410/m/nava4113/1671805673271/ba355d0f84b6f3cc2c4334610ca86aee3e9d52f2?sender=u0c3cdba5126734aceb613229) within the "unlisted" section.

**Comment by jillian-hammer** [comment]
All items are updated.
- [Sitemap](https://app.mural.co/t/primedatainput6410/m/nava4113/1671805673271/ba355d0f84b6f3cc2c4334610ca86aee3e9d52f2?sender=u0c3cdba5126734aceb613229)
- [Content tracker](https://cdc.sharepoint.com/teams/ReportStream/Lists/ReportStream%20content%20tracker/AllItems.aspx?viewid=70d3304e%2D44a7%2D459c%2Db92a%2D2953d8d259b4)
- 404 page: [Content doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Website%20content/20241112_404-page_content.docx?d=wc938f0a3285748adb86d495e6d762e8e&csf=1&web=1&e=QjR14b), [Backlog update ticket](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/16520)
- Unsupported browser page: [Content doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Website%20content/20241112_Unsupported-browser_content.docx?d=w7e70038bd3314fd3b099ffd82c055a11&csf=1&web=1&e=PbpShc), [Backlog update ticket](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/16521)

**Comment by chris-kuryak** [comment]
Thank you!

**Comment by jillian-hammer** [comment]
Shared with Chris today. Closing ticket.
