### ISSUE TITLE
Develop Content update for "Responses from ReportStream"

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#16476]
## Problem statement

NIH flagged that the API referenced in Responses from ReportStream to retrieve a report’s history is incorrect. We’re updating the link to point to the correct API and also an additional API that can be used to retrieve submissions for a sender in ReportStream. 

## What you need to know
- Referring to this page on ReportStream website: https://reportstream.cdc.gov/developer-resources/api/documentation/responses-from-reportstream
- [Updated Content doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Website%20content/Programmer%27s%20Guide%20updates/20241121_API_guide_content_updates.docx?d=wb70ab13426014583b80d28338404fc36&csf=1&web=1&e=yMt1tB)

From Andy Meadows via email 11/1/2024:
> we are coded to pull status from /api/waters/report/${id}/history, but the documentation at https://reportstream.cdc.gov/developer-resources/api/documentation/responses-from-reportstream states status is pulled from /api/history/simple_report/submissions/${id}.  Thought we'd point it out in case the team wanted to make a documentation correction.

## Acceptance criteria

- [x] Content changes noted in this ticket or content change doc created
- [x] Engineering content ticket created on WebX Zenhub board and flagged for refinement (labels: engineering, needs-refinement; column: Next items)

## To do
- [x] Victor to review content on "Responses from ReportStream" in the API Guide for any changes that need to be made: https://reportstream.cdc.gov/developer-resources/api/documentation/responses-from-reportstream
- [x] Victor notes those changes in this ticket either as a comment or as separate document linked in this ticket
- [x] Victor communicates those needed content changes to Jillian

**Comment by jillian-hammer** [comment]
Updated content doc [here](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Website%20content/Programmer%27s%20Guide%20updates/20241121_API_guide_content_updates.docx?d=wb70ab13426014583b80d28338404fc36&csf=1&web=1&e=yMt1tB). also created a [Figma mockup](https://www.figma.com/proto/Du7feM8huRDAAZCQcUIj93/Website-Redesign?node-id=6671-2716&node-type=frame&t=fARreyPHgeg16nYs-1&scaling=min-zoom&content-scaling=fixed&page-id=5982%3A4904) for eng reference here. thank you @victor-chaparro!!

@MikaelahD13 can you help with making the front-end engineering implementation ticket? lmk if you need additional guidance. cc @chris-kuryak

**Comment by jillian-hammer** [comment]
thanks @MikaelahD13 for creating the follow up ticket: Update and Correct API References in ReportStream Responses #16660. closing!
