### ISSUE TITLE
Enable Docker Content Trust

### ISSUE THREAD

**Issue by ronaldheft-usds** [CDCgov/prime-reportstream#1647]
We should sign our container images with the CDC's code signing certificate. This is a required of the an ATO with the CDC, so this must be implemented.

## The Certificate
We have received the CDC's certificate and it is currently stored in `pdhstaging-keyvault` under the name `pdhstaging-code-sign`.

Code signing certificates are managed by ENTRUST on behalf of the CDC. Look into the Slack history for how to request a new certificate or renew an existing certificate.

## How to Code Sign

We've done substantial research on this and the process is documented here: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/docker-content-trust.md

## The Process

1. In our GitHub Release action (`[release.yml](https://github.com/CDCgov/prime-reportstream/blob/master/.github/workflows/release.yml)`), pull down the code signing certificate from the Key Vault
2. Sign the built containers using the certificate
3. Upload the signed containers to our Azure Container Registry
   * This may require a special Azure permission
4. Enforce the function app to use only signed container images
   * This is an environment variable. It already exists in our config and is just commented out.

**Comment by JosiahSiegel** [comment]
Signature secret in staging RG confirmed. I don't have Azure access, but I will fetch via Key-Vault GitHub action.
![image](https://user-images.githubusercontent.com/5522990/144931305-989e897c-082d-43d0-b504-683f45a757b2.png)

**Comment by JosiahSiegel** [comment]
Service principal missing ACRImageSign permissions. Will request.
