### ISSUE TITLE
Move MMTC to production

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#16474]
## Problem statement
We need to move the MMTC organization to production in order to meet the requirements of our MMTC pilot initiative.

## What you need to know

- https://github.com/CDCgov/prime-reportstream/blob/main/prime-router/docs/onboarding-users/sender-onboarding/senders.md
- https://github.com/CDCgov/prime-reportstream/blob/main/prime-router/docs/docs-deprecated/playbooks/how-to-use-token-auth.md

- Set senderSchema to use MMTC-sender-transform.yml 

## Acceptance criteria

- [x] Org setup in prod with correct settings
- [x] Authorization working (MMTC public key)
- [x] RS receives a test message from MMTC in production (if possible) and zipcode routing working properly, but do not send the test messages to any receivers in production

**Comment by victor-chaparro** [comment]
Need to get MMTC's production public key
