### ISSUE TITLE
Resolve metabase configurations and certificate issues

### ISSUE THREAD

**Issue by devopsmatt** [CDCgov/prime-reportstream#16488]
We cannot follow the existing documentation [this doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B051EB54D-CA90-4941-8B22-89E4CF875178%7D&file=Document1.docx&action=default&mobileredirect=true) as the entire process is deprecated and we need to address its management and requests via a different process to generate and install certs for metabase.

**Note**: This process cannot be defined yet as it's still undefined what its workflow is and will be since it's a work in progress we need to get resolved A.S.A.P. Having a Metabase prod and staging have new TLS/SSL certs installed and validated will be address in the incoming days.

**Comment by emvaldes** [comment]
I had to reformat this original document as it was difficult to use.

#### Renewing TLS Certificates for Reportstream

1. Preset: In your local workspace perform the following steps:
$ mkdir certificates && cd $_ ;

2. Create the request file with this content

$ echo -e "
[req]
distinguished_name = req_distinguished_name
req_extensions = req_ext
prompt = no

[req_distinguished_name]
C   = US
ST  = GA
L   = Atlanta
O   = Centers for Disease Control and Prevention
OU  = PRIME
CN  = reportstream.cdc.gov

[req_ext]
subjectAltName = @alt_names

[alt_names]
DNS.1 = reportstream.cdc.gov
DNS.2 = test.reportstream.cdc.gov
DNS.3 = staging.reportstream.cdc.gov
" > vim csr.cnf ;

3. Generate a Private Key
$ openssl genrsa -out prime.cdc.gov.key 4096 ;

4. Create a CSR from the template/request file:
$ openssl req -new -key prime.cdc.gov.key -out prime.cdc.gov.csr -config csr.cnf ;

5. While logged in with your –SU account go to the cloud.entrust.net Certificate Services
(I think this is inside the CDC network – use Citgo)

6. Select the “ Multidomain OV” option
Paste the content of file in the certificate signing request box

7. Primary email is reportstream@cdc.gov -
You can add yours as a secondary to get results back from entrust in case there is a problem.
After submission, open a helpdesk ticket and email adhelpdsk@cdc.gov

8. You will receive this confirmation email
The link in the email takes you here
Chose a random server type and download the zip file at the end

9. Create the pfx file
Unzip the file under the same certificates dir in your local. This zip content 2 files, place the files in the same location with you t private key
Create another file called bundle.pem
Create the pfx file : openssl pkcs12 -export -in bundle.pem -out bundle.pfx
Along with password

10. upload the cert in azure and test
Note: Must have a second pair of eyes to watch this step
Go to staging keyvaults à certificates à click on the cert à new version -->
In the “method of certificate creation” fill, select “import”
Chose the bundle.pfx  pfx file from your local and upload and enter the password

11. Test the new certificate
$ openssl s_client --connect staging.prime.cdc.gov:443 --servername staging.prime.cdc.gov ;

**Comment by emvaldes** [comment]
![Screenshot 2024-11-07 at 19 07 47](https://github.com/user-attachments/assets/335bb019-d80a-42b5-8d2c-ddf3ccb6fe5b)

**Warning:** The site does not allow me to log-in regardless of which user I could enter. ab01@cdc.gov or ab01-SU@cdc.gov

**Comment by emvaldes** [comment]
Is this the document that we should follow in order to address/resolve this issue?
If so, should we disregard the one we have and have this one as the source of truth for this process or should we merge both as one?
https://cdcdocs-cdc.msappproxy.net/docs/devsecops/services/certificate-management/entrust

**Comment by emvaldes** [comment]
This process is not functional. I have tried and it's not only outdated but it simply does not work.
We are attempting to join a group of the CDC Cloud team and figure out the "right" procedure to follow and determine the support boundaries and what we are supposed to do, etc.

**Comment by emvaldes** [comment]
We have met today with the CDC team handling these requests and they went the extra-mile to help us understand what is happening. Based on what was identified, the process that is currently used is not in sync with the CDC supported workflow.
Apparently, we have had a self-managed resource group that follows custom configurations and this is something they are trying to figure out. Some efforts were made to correct the existing setup but other parties (CDC Active Directory team) needs to address some issues prior to get this issue resolved and functional.
We will keep you posted on what is achieved and in time we will need to re-evaluate the existing settings and procedures ownerships in this portion of the infrastructure managment.

**Comment by emvaldes** [comment]
From my perspective, this is not something we should be involved with. If you do not truly manage an infrastructure, trying to do it "your way" will always be off-sync with what everyone else is doing and sooner or later this will become a problem.
I would suggest to let the right team deal with this issue and focus on things that are within our domain. We should be requesting new certificates and let their process deal with the rest. Including the renewal of those certs in time. This will place us in a good path to ensure everything that is infrastructure critical is functional.

**Comment by emvaldes** [comment]
The CDC team is opening a Microsoft case on the key vault. It's still inaccessible after the DNS correction.  They are inquiring if we know whether the vault has anything in it?
They are presuming it does, but are unable to verify due to the connectivity issue.

**Comment by emvaldes** [comment]
They have created the Microsoft support ticket.  But, to confirm our request, to track the ticket internally they need to know if we want them to add the ticket number to our existing ticket with OMHS for the cert issue. Or if we would like for them to copy us on responses from Microsoft?
@devopsmatt has asked for a copy on the correspondence as it would be great for us to have.

**Comment by emvaldes** [comment]
**I have asked them**:
Is there a way to see/identify when was the last time any CRUD operation would have done any work in that key vault? That would tell us when it was last time functioning. It should be working as the application is extracting and probably updating data there (I will confirm that today).

**Their reply was**:

That's a great question, I suppose that's what we're chasing.  We've attempted adding our accounts to the access policy which should cover authentication/authorization and have set the storage account to private access disabled, which would allow us to access the key vault over it's private endpoint, which isn't working. I can't say for certain whether this ever worked or when it stopped working as historically we haven't managed the environment. I do supsect with the DNS issue we saw yesterday this was broken for private access from a CDC laptop.

**Comment by emvaldes** [comment]
They have confirmed access to the vault is being blocked from GFE and they are able to access it via CITGO. There's a FW rule in place that's blocking zScaler access to the vault.  They will copy us in on email to the zscaler team once CSPO forwards it to them.

**Comment by emvaldes** [comment]
The CDC team is awaiting for the zScaler teams to update us with their findings. They have explained that usually they're the group that will lock an endpoint down to an AD group.
The CDC team have cancelled the original case for the Key Vault access with Microsoft as this isn't an issue with the key vault itself.

**Comment by emvaldes** [comment]
The CDC team has opened another case to determine why authentication between the front door and the key vault isn't working. I'm investigating on my end there as well because the Engagement team performs certain CRUD operations in their own onboarding process and we need to make sure that this portion of the process is better understood and documented.

**Comment by emvaldes** [comment]
I am reaching @victor-chaparro seeking his advice on this matter following up @arnejduranovic recommendation to reach out to him.

Base on @arnejduranovic: We know so far that the application's usage of Azure Key Vault. Azure Key Vault is only written to by the primeCLI tool. The Engagement team uses this tool to store receiver transport protocol secrets (like keys for receiver rest endpoints or SFTP servers)

**Comment by emvaldes** [comment]
After a long set of support-sessions with the CDC Cloud team and some additional resources, they were able to get these issues all resolved. They are all listed in this ServiceNow ticket: REQ0390102

In summary, the metabase certificate was setup and now the following domain/sub-domains are available to address any requests for the metabase service.

https://metabase.prime.cdc.gov/metabase -> https://prime.cdc.gov/metabase
Note: We are currently experiencing some odd behavior on this application and will update this ticket once this issue is resolved.

**Comment by emvaldes** [comment]
The issue is now resolved. The following steps were performed to ensure the metabase service is working as expected. The site:
https://metabase.prime.cdc.gov/metabase -> https://metabase.prime.cdc.gov/metabase/auth/login?redirect=%2F

**Comment by emvaldes** [comment]
We are working on getting the following working/functional (without the duplicate metabase at the end of the path:
https://metabase.prime.cdc.gov -> https://prime.cdc.gov/metabase/auth/login?redirect=%2F

**Comment by emvaldes** [comment]
The following URL will take us to the Microsoft Azure prime-data-hub-prod (excluding subscription here):
https://portal.azure.com/#@cdc.onmicrosoft.com/resource/subscriptions/<subscription-id>/resourceGroups/prime-data-hub-prod/providers/Microsoft.Network/frontdoors/prime-data-hub-prod/config

**Comment by emvaldes** [comment]
The Microsoft Azure Front Door Designer (prime-data-hub-prod) has the following settings:

- Frontends/domains: metabase.prime.cdc.gov
- Backend poools: metabase
- Routing rules: metabase

**Comment by emvaldes** [comment]
#### [Backend pools](https://aka.ms/AFD-BE-Pools):
A backend pool is a set of equivalent backends to which Front Door load balances your client requests.
- metabase

##### Backend hostname:
pdhprod-metabase.azurewebsites.net

##### Health Probes:
Front Door sends periodic HTTP/HTTPS probe requests to each of your configured backends to determine the proximity and health of each backend to load balance your end user requests.

- **Status**: Enabled












#### Routing rules: metabase

**Comment by emvaldes** [comment]
#### [Routing rules](https://aka.ms/AFD-Routing-Rules):
A routing rule maps your frontend host and a matching URL path pattern to a specific backend pool.
- **Name**: metabase
- **Status**: Enabled
- **Accepted protocol**: HTTPS only
- **Frontends/domains [3]: prime-data-hub-prod.azurefd.net, prime.cdc.gov, metabase.prime.cdc.gov

##### [Patterns to match](https://go.microsoft.com/fwlink/?linkid=2084638):
Set this to all the URL path patterns that this route will accept. For example, you can set this to /users/* to accept all requests on the URL www.contoso.com/users/*.

**Comment by emvaldes** [comment]
#### Rule engine configuration:
- **HTSS**

##### THEN
- **Action**: (Response header)
- **Operator**: Append
- **Header name**: Strict-Transport-Security
- **Header value**: max-age=31536000

##### AND THEN
- **Action**: Response header
- **Operator**: Append
- **Header name**: Location
- **header value**: https://metabase.prime.cdc.gov/metabase/

**Comment by emvaldes** [comment]
Tracking changes at:
https://portal.azure.com/#view/Microsoft_Azure_ChangeAnalysis/ChangeAnalysisBaseBlade/resourceIds~/%5B%22%2Fsubscriptions%2F< subscription-id >%2FresourceGroups%2Fprime-data-hub-prod%2Fproviders%2FMicrosoft.Network%2Ffrontdoors%2Fprime-data-hub-prod%22%5D/startTime/2024-12-06T22%3A43%3A24.513Z/endTime/2024-12-09T22%3A43%3A24.513Z/deepLinkOrigin/D%26SP
