### ISSUE TITLE
FHIR Authentication wrap up, --> Part Two <--

### ISSUE THREAD

**Issue by pablocaviglia** [CDCgov/prime-reportstream#1650]
Continuation of ticket https://github.com/CDCgov/prime-reportstream/issues/659

Finish the end to end testing:

**Testing new:**

create a new sender, with the public key. Put the sender inside the 'ignore' organization and test the logic to:
-> communicate with a backend secured endpoint without a token
-> communicate with a backend secured endpoint with an invalid token
-> obtain a new token and use it to communicate with a backend secured endpoint

cleanup: delete the sender when the test is finished.

**Comment by jimduff-usds** [comment]
Done.   Merged in, and moved to cli/tests
