### ISSUE TITLE
CO - Carbon Health Future Dates 

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#16510]
## Problem statement

Colorado reports future date error for Shops at Walnut Creek and Arapahoe Crossing from Carbon Health.

## What you need to know

Received by: CDPHE ELR Prod
Received on: 2024-11-08 08:00:57
File source: CDC PRIME
File name: co-receiver-transform.yml-c94e251c-e243-4906-8c44-c4333768604f-20241108204604.hl7

Daily Data shows HL7 file sent at 3:30pm on 11/8/24. HL7 file includes data from 3:56pm.
<img width="1311" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd09xQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1fc6cedb9f7f91d08da73d5d3d6ce686b0aba3fe/image.png" alt="image.png" />

## To do

- Check if sender error or time zone issue.

**Comment by MikaelahD13** [comment]
Hey @victor-chaparro, may you please take a look at this and provide guidance?

**Comment by rnz6** [comment]
Same issue received again.

Received by: CDPHE ELR Prod
Received on: 2024-11-09 10:53:39
File source: CDC PRIME
File name: co-receiver-transform.yml-5fa8502e-4947-4db9-a310-7a1c89b1c8a5-20241109203041.hl7
Performing Org Name: Westminster, CO - Shops at Walnut Creek

Received by: CDPHE ELR Prod
Received on: 2024-11-09 13:28:03
File source: CDC PRIME
File name: co-receiver-transform.yml-ac2f51e8-ba39-407e-9f65-a259bde2300f-20241110023036.hl7
Performing Org Name: Westminster, CO - Shops at Walnut Creek

Received by: CDPHE ELR Prod
Received on: 2024-11-10 08:57:57
File source: CDC PRIME
File name: co-receiver-transform.yml-b271a1de-375f-405b-bf69-30816ba74c4d-20241110203031.hl7
Performing Org Name: Aurora, CO - Arapahoe Crossing

Received by: CDPHE ELR Prod
Received on: 2024-11-10 20:36:25
File source: CDC PRIME
File name: co-receiver-transform.yml-b74f8fbc-d130-4570-a23b-db1106dcf9ef-20241111023006.hl7
Performing Org Name: Tucson, AZ - Campbell Ave

Received by: CDPHE ELR Prod
Received on: 2024-11-10 20:36:25
File source: CDC PRIME
File name: co-receiver-transform.yml-b74f8fbc-d130-4570-a23b-db1106dcf9ef-20241111023006.hl7
Performing Org Name: Tucson, AZ - Campbell Ave

Received by: CDPHE ELR Prod
Received on: 2024-11-11 07:54:17
File source: CDC PRIME
File name: co-receiver-transform.yml-3adbbf04-d62c-410a-a9ce-f26c058b5083-20241111203022.hl7
Performing Org Name: Brighton, MA - Washington Street

Received by: CDPHE ELR Prod
Received on: 2024-11-11 18:31:49
File source: CDC PRIME
File name: co-receiver-transform.yml-0f718a43-70d0-486c-99ff-f74937f873b1-20241112083045.hl7
Performing Org Name: Westminster, CO - Shops at Walnut Creek


Received by: CDPHE ELR Prod
Received on: 2024-11-11 13:41:22
File source: CDC PRIME
File name: co-receiver-transform.yml-b20912b3-23e7-443d-aab8-65830a3a9291-20241112023036.hl7
Performing Org Name: Santa Clara, CA - Santa Clara Square

**Comment by victor-chaparro** [comment]
We found the issue with these messages and are looking into fixing it.

**Comment by Jcavallo7** [comment]
a few more are in, please see below: <img width="1177" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGkzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b1148f48cbfb62bc720c6089cd68385496690e8/image.png" alt="image.png" />

<img width="1183" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHEzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0fd0f866faccb29b0df88a47e27f3fa2a17f29a/image.png" alt="image.png" />

**Comment by Jcavallo7** [comment]
a few more are in, please see below:

<img width="1161" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHU5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ece711da5c6443f31f023a66f22c3bb2e817771/image.png" alt="image.png" />

**Comment by Jcavallo7** [comment]
New arrival: <img width="1160" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWUvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f82dd043166f45d4ac96a4d2ac58db6797c3c6ef/image.png" alt="image.png" />

**Comment by victor-chaparro** [comment]
You should stop getting these notifications. @lucero-v has pushed a fix that addresses this issue to production today

**Comment by victor-chaparro** [comment]
I'll reach out to Colorado and asked if this need to be resent.

**Comment by victor-chaparro** [comment]
Colorado has replied saying the files don't need to be resent, they have manually reprocessed them, and the issue has been resolved.

<img width="844" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0FBQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bab37cf600f94b6ec690586718fd4b3be68b2444/image.png" alt="image.png" />
