### ISSUE TITLE
View Submission History - Senders & Internal Admins

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#1652]
## Problem Statements
As a Sender, I need to be able view my submission history so that I can confirm what I submitted and see if it was successfully forwarded to my PHD(s).

## Notes from Sender Automation team 
- Problem
    - CLIA inspectors will require that a Sender provide proof that they are reporting reportable diseases and results.  
    - Multiple clinics and providers have been cited by CLIA for not reporting COVID positive AND negative results which lead to a deeper dive and found that some were not reporting all diseases.
    - CAP and Joint Commission will not only require that a Sender provide proof that they are reporting reportable diseases and results, but they will require documentation of a process to monitor and ensure all results are sent successfully.
- Possible Solution(s)
    - A Web Portal with the following reporting features.
        - Count of Reported Diseases by Result
        - List of Errors and Date Resolved
- Benefits
    - Our Tech Support will not have to be involved in the CLIA, CAP and Joint Commission processes.
    - State PHDs will not have to be involved in the CLIA, CAP and Joint Commission processes.
-  [https://docs.google.com/document/d/1G9HUQUDCKeggIXrw9PHiyqJnzNfJX0WyanzTphDotAM/edit](url)

## Notes from Jim
- Lineage is sitting in DB now; Jim suggests purchasing something (SuperSet) so that we can customize the data per Sender
- Derek is researching: https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/1927

**Comment by loripusey** [comment]
@drew-usds @inkandsound Please add stories as necessary to this Epic when the evaluation of submission history is complete enough to move forward. Notice that I de-prioritized the printing stories based on feedback notes I read.
cc: @rachelhanster

**Comment by rachelhanster** [comment]
Product backlog tickets 1657, 1871, 3906, 4438 are being transitioned to simplereport, as part of Uploader's move.

**Comment by rachelhanster** [comment]
This epic is to be closed once Cursor pagination: break down pages by # of results #4779 is done.

**Comment by HeatherRienks** [comment]
@RakshindaAslam - per the comment above, #4779 is now closed. Do we want to close this epic?

**Comment by RakshindaAslam** [comment]
closing this epic with #4779 closed.
