### ISSUE TITLE
Investigate 0.0.0.0 IP addresses in API  Azure logs

### ISSUE THREAD

**Issue by devopsmatt** [CDCgov/prime-reportstream#16544]
- [x] Figure out where IP addresses are getting filtered and provide path to resolution so IPs are logged.

**Comment by emvaldes** [comment]
To anonymize IPs in Azure logs and make it a scriptable, portable process, you can follow these steps:

1. **Identify the Log Sources**
Determine which Azure logs contain IP addresses (e.g., Azure Monitor, Application Insights, Azure Activity Logs, etc.). Use Azure Monitor or KQL (Kusto Query Language) to query the logs and identify fields that contain IP addresses.
2. **Set Up Azure CLI or Azure SDK**
Use the Azure CLI or Azure SDKs (Python, PowerShell, etc.) to interact with Azure resources programmatically.
3. **Fetch Logs Programmatically**
Query Azure logs using Azure Log Analytics.

**Comment by emvaldes** [comment]
Example in Python using the Azure SDK:
``` python
python
Copy code
from azure.identity import DefaultAzureCredential
from azure.monitor.query import LogsQueryClient

credential = DefaultAzureCredential()
client = LogsQueryClient(credential)

query = "AzureActivity | project IPAddress, OperationName"
result = client.query_workspace(
    workspace_id="<Workspace-ID>",
    query=query,
    timespan=("P1D")  # Last 1 day
)
for table in result.tables:
    for row in table.rows:
        print(row)
```

**Comment by emvaldes** [comment]
4. Anonymize IP Addresses
Replace IPs with hashed or obfuscated versions (e.g., using a script).

``` python
import hashlib

def anonymize_ip(ip_address):
    return hashlib.sha256(ip_address.encode()).hexdigest()

ip = "192.168.1.1"
print(anonymize_ip(ip))
```

**Comment by emvaldes** [comment]
5. **Store or Forward Logs**
Decide where to store the anonymized logs (e.g., Azure Blob Storage, another log system).
Use tools like az storage for scripting log uploads to Azure Storage.

6. **Automate and Schedule**
Package the script in a container or Azure Function for automated execution.
Use Azure Logic Apps or Azure DevOps pipelines to schedule and manage execution.

**Comment by emvaldes** [comment]
7. **Search for Specific IP Addresses**
For IP lookup, use KQL queries in Log Analytics, filtering by known IPs:

``` kql
AzureActivity | where IPAddress == "192.168.1.1"
```

**Comment by emvaldes** [comment]
Creating a sample end-to-end Python script or guidance on using specific Azure CLI commands.
Here’s an end-to-end Python script that anonymizes IPs from Azure logs and searches for specific IP addresses. It uses the Azure SDK for Python.

###Setup
Install the required Python packages:

``` bash
pip install azure-identity azure-monitor-query
```

Ensure you have an Azure Active Directory (AAD) application registered and assigned the necessary permissions to read Azure Monitor logs. Set up an Azure Log Analytics workspace and note the workspace ID.

**Comment by emvaldes** [comment]
**Script**

``` python
import hashlib
from azure.identity import DefaultAzureCredential
from azure.monitor.query import LogsQueryClient

# Function to anonymize IP addresses
def anonymize_ip(ip_address):
    """Hashes an IP address to anonymize it."""
    return hashlib.sha256(ip_address.encode()).hexdigest()

# Function to query logs and anonymize IPs
def fetch_and_anonymize_ips(workspace_id, query, timespan="P1D"):
    """Fetches logs from Azure and anonymizes IP addresses."""
    # Authenticate using DefaultAzureCredential
    credential = DefaultAzureCredential()
    client = LogsQueryClient(credential)

    # Run the query
    print("Querying Azure logs...")
    result = client.query_workspace(workspace_id, query, timespan=timespan)

    anonymized_results = []
    for table in result.tables:
        for row in table.rows:
            # Assuming the IP address is in the first column
            original_ip = row[0]
            anonymized_ip = anonymize_ip(original_ip)
            anonymized_results.append((anonymized_ip, *row[1:]))
    
    print("Logs fetched and IPs anonymized.")
    return anonymized_results

# Main execution
if __name__ == "__main__":
    # Replace with your Log Analytics Workspace ID
    WORKSPACE_ID = "<YOUR_WORKSPACE_ID>"
    
    # Replace with your KQL query (this one looks for IPs in AzureActivity logs)
    QUERY = "AzureActivity | project IPAddress, OperationName, TimeGenerated"

    # Fetch logs and anonymize IPs
    anonymized_logs = fetch_and_anonymize_ips(WORKSPACE_ID, QUERY)

    # Save anonymized logs to a file
    output_file = "anonymized_logs.csv"
    with open(output_file, "w") as f:
        f.write("AnonymizedIP,OperationName,TimeGenerated\n")
        for log in anonymized_logs:
            f.write(",".join(log) + "\n")
    
    print(f"Anonymized logs saved to {output_file}.")
```

**Comment by emvaldes** [comment]
**Customizing the Script**

1. Replace <YOUR_WORKSPACE_ID> with your Azure Log Analytics workspace ID.
2. Modify the QUERY to suit your specific log structure.

**Running the Script**
Run the script:

``` bash
python anonymize_azure_logs.py ;
```

**Results**
1. The anonymized logs are saved in anonymized_logs.csv.
2. You can further enhance the script to:
a.  Search for specific IPs.
b. Automate uploads to Azure Storage or another destination.

**Comment by emvaldes** [comment]
The objective for this Issue is now achieved and we can reopen it to further evaluate options to deal with the problem at hand or track the actual implementation in a separate trackable effort.
