### ISSUE TITLE
Enquizit Integration Error 

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#16553]
From: Kavitha Potluri  

Thanks so much Chris for the detailed information.

While performing regression testing, we noticed that the records make it to the RS staging environment but are in batch queue forever. We recently updated the data ingestion API URL’s. Not sure if it impacted that. Whenever you have some time, could you please investigate it

DI token API :- https://dataingestion.dts1.nbspreview.com/ingestion/api/auth/token

DI ingestion API:- https://dataingestion.dts1.nbspreview.com/ingestion/api/elrs

clientsecret: tw3lNJw1XrDvYTXB9LaprrnrkM1VkYFB

clientid: di-keycloak-client

**Comment by chris-kuryak** [comment]
@victor-chaparro Any insight on this right off the top of your head? Otherwise, we can slot this into an upcoming sprint for someone to take a look at.

**Comment by chris-kuryak** [comment]
We have not heard back from them. Can this be closed @TaneaY @rnz6 ?

**Comment by TaneaY** [comment]
Support has resolved as of Victors updates on 11/20. User has not replied to thread with confirmation of resolution nor continued error.
