### ISSUE TITLE
Spec design for logged-in website experience

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#16579]
## User story
As a ReportStream internal stakeholder, I want to understand the ideal future state of our authenticated experience so that we can make product decisions to incrementally approve our onboarding experience.

## Background & context

This ticket is to conduct speculative design exercises to explore the authenticated user flow, aimed towards improving the onboarding experience towards self-service as ReportStream's user base grows. This ticket will result in design artifacts that can serve as a "north star" for discussion and product strategy. 

## Working links

-  Figma: [Working space](https://www.figma.com/design/Du7feM8huRDAAZCQcUIj93/Website?node-id=6719-1420&t=fzbeL8BgLEFr3wMl-1)

Existing design work to be referenced
- [Service blueprint with improvement opps](https://app.mural.co/t/primedatainput6410/m/nava4113/1672148125717/44ffae1e44a9066d47678e15bdef743d7345fa15?sender=u0c3cdba5126734aceb613229)
- [Intake & interest improvements](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1684158407022/77a87b428e131bcac8a4f63240373ce25a6ba7cf?sender=u0c3cdba5126734aceb613229)
- [Okta flow Mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1681921545021/4b0bdcdfb84b03a3a7b0a90741c9dab5c1e3abd6?sender=u0c3cdba5126734aceb613229)

## Acceptance criteria

-   [x] Artifact(s) captures ideal end-to-end user journey from creating an account to monitoring in prod
-   [x] Artifact(s) captures visual ideas for the logged-in homepage, features, and user flows

**Comment by jillian-hammer** [comment]
@chris-kuryak wrote this ticket, lmk if you have any edits/feedback. ty!

**Comment by jillian-hammer** [comment]
@chris-kuryak - we didn't get to review this synchronously this sprint cause of the holiday, so I'll remove the "Artifact(s) reviewed with Product and Engineering for feedback" and "Next steps identified" ACs and move this to next steps/closed.

**Comment by chris-kuryak** [comment]
Sounds good!
