### ISSUE TITLE
Carbon Health Onboarding – Test with --

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#16587]
## Steps for testing Carbon Health with new receiver
- [ ] In staging, add Carbon Health as approved sender to Routing Filter
- [ ] Check if receiver has any specific testing requirements including:
  - [ ] Patient Name restrictions
  - [ ] Receiver Portal access requirements
- [ ] Inform Carbon Health to send test messages to receiver per receiver requirements
- [ ] Ensure messages get sent to that receiver
  - [ ] (if necessary) Update receiver quality filters
- [ ] Notify receiver to approve test message (provide MessageID, Patient Name, Filename)
- [ ] (if necessary) Make changes per receiver requirements

## Acceptance Criteria 
- [ ] Receiver can successfully receive test messages and has approved them

**Comment by chris-kuryak** [comment]
Duplicate
