### ISSUE TITLE
Carbon Health Onboarding – Test with OK

### ISSUE THREAD

**Issue by MikaelahD13** [CDCgov/prime-reportstream#16589]
## Steps for testing Carbon Health with new receiver
- [ ] In staging, add Carbon Health as approved sender to Routing Filter
- [ ] Check if receiver has any specific testing requirements including:
  - [ ] Patient Name restrictions
  - [ ] Receiver Portal access requirements
  - [ ] Check if Convert Date/Time to local receiver timezone is activated
- [ ] Inform Carbon Health to send test messages to receiver per receiver requirements
- [ ] Ensure messages get sent to that receiver
  - [ ] (if necessary) Update receiver quality filters
- [ ] Notify receiver to approve test message (provide MessageID, Patient Name, Filename)
- [ ] (if necessary) Make changes per receiver requirements

## Acceptance Criteria 
- [x] Receiver can successfully receive test messages and has approved them
- [x] Receiver is moved to receive production messages from Carbon Health

**Comment by chris-kuryak** [comment]
Ott and Victor to get together to discuss more.

**Comment by chris-kuryak** [comment]
Spillover: Confusion on engagement engr on what was required in this ticket.

**Comment by oslynn** [comment]
<img width="1717" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL05BQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d3a76e0669f8dc42d11422ce4efc3041291bfce/image.png" alt="image.png" />
