### ISSUE TITLE
Test gh access and commit signing

### ISSUE THREAD

**Issue by devopsmatt** [CDCgov/prime-reportstream#16583]
Please set up your commit signing on your machine and your GH account - [instructions here](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

Once set up and verified, please pull the `main` branch and create your "feature' branch from it. 
The DevSecOps branch naming convention is as follows: `devsecops/<username>/feature-name` 
On your newly created branch, please makea whitespace change to the README.md file, commit (verify the signing is working here), push, create a PR and send me (Matt) the link to the PR in slack.

**Comment by bethbeza** [comment]
The signed commit has been successfully verified.

**Comment by bethbeza** [comment]
Finished issue.
