### ISSUE TITLE
Push automated email to prod for pilot users

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-reportstream#1659]
Current - automated email is sent to PRIME internal at 3pm EST

Make following logic and content changes
- [ ] Make email go out at 7am EST
- [x] Change the email url to reportstream@cdc.gov (currently reportstream.cdc.gov)
- [x] Change from "seven days" to "30 days"
- [x] Change button to [Download daily test results] (edit, using alt text from Berni/Rebecca)

After these changes, push to prod
-Send email to pilot group

**Comment by drew-usds** [comment]
Sorry @jlusds just catching this issue now. The current template in SendGrid is just out of date. Your checklist should all be resolved with the new template, just need to update that in SendGrid. Doing that now!

**Comment by drew-usds** [comment]
Updated content-related items in SendGrid. Hit a few blockers and had to make some tweaks to make things work for now. 

Opened up two new issues to make things a lil' fancier later:

- #1695
- #1696
