### ISSUE TITLE
Update the API Guide with Code mapping template & instructions

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#16628]
## Problem statement

We are adding an additional step to our onboarding process (Code mapping). The content is already developed and needs to be updated on the front-end. 

## What you need to know

- [Content updates doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Website%20content/Programmer%27s%20Guide%20updates/20241122_API_guide_content_updates.docx?d=wd48455b1d5c0414b9274a4f0026c6f4a&csf=1&web=1&e=T0NZgj): Use a source of truth for content changes.
- [Figma reference](https://www.figma.com/design/Du7feM8huRDAAZCQcUIj93/Website-Redesign?node-id=6653-1089&t=yrs3IdlsjWHblHdB-1): Reference for components only (i.e. NOT content).

## Acceptance criteria

- [x] New `Map your codes` section is added
- [x] Subsequent section numbers are updated
- [x] Create hash-links for each numbered section

## To do

- [ ] When making PR, tag @jillian-hammer as a reviewer

**Comment by chris-kuryak** [comment]
Spillover: Zenhub did not sync properly and did not add this to Sprint Backlog. Noticed today, so started on today. Should be deployed by Thursday.
