### ISSUE TITLE
Shared secrets storage proposal

### ISSUE THREAD

**Issue by devopsmatt** [CDCgov/prime-reportstream#16620]
Since Keybase has been deprecated, we need a secret storage solution that will enable sharing of sensitive data among the broad RS team and other **internal and external** entities.

Requirements:

- industry standard encryption in-flight and at rest (ISO certifications a big +)
- user/group authentication and authorization on per enclosure/folder/item
- cost effective (free/OSS preferred)
- owner transfer capable
- easy to adopt and rollout
- MFA-enabled
- cross-platform or SaaS
- ability to share with third parties free of charge to the receiving party
- ability for third parties to share with us without cost burden
- no vendor lock-in

Nice to have:
- audit trail capability
- expiration with expiry warning
- 

Examples: 

- [SecretServer](https://delinea.com/products/secret-server)
- [Box](https://www.box.com/)

DoD: 
Documentation should include:
- [ ] Each solution should be evaluated to match requirements
- [ ] pricing tiers 
- [ ] side by side pros/cons of adoption comparison
- [ ] internal rollout ease t-shirt size (per person)
- [ ] third-party adoption effort t-shirt size (per person)

**Comment by bethbeza** [comment]
https://docs.google.com/document/d/e/2PACX-1vTNo30Czt9ihQxG6oEO6OQzVOINnQtqMfIYgHcITXDK2JNAbIH8pNjJsggFVnnrt0PaynQVdhnG5Dep/pub
