### ISSUE TITLE
Support for John Hopkins and IHS testing of Navajo schools

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#1663]
**Is your feature request related to a problem? Please describe.**
Johns Hopkins is conducting tests at schools in the Navajo Nation. They have reached out to the PRIME team to support them in getting COVID-19 results to the AZ DOH. 

**Describe the solution you'd like**
A temporary sender to be added for John Hopkins. 

The AZ DOH asks that these results be only sent into their download feed. Create permanent secondary feed for AZ. 

**Describe alternatives you've considered**

**Additional context**
This is a special one-time upload of test results.

**Comment by jlusds** [comment]
Was this completed? If so, I can reach out to AZ to confirm it is in their download site

**Comment by RickHawesUSDS** [comment]
Data sent
