### ISSUE TITLE
Develop strategy for updating the IA of the authenticated site

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#16667]
## Problem statement

The code mapping tool will not be public-facing and thus will require users to log in to use it. We need to revisit the IA and navigation patterns of the authenticated side of the website to ensure that onboarding tools (including the public key tool and submission history/daily data) are easily accessible for our users throughout their ReportStream journey.

## What you need to know

- [ReportStream sitemap](https://app.mural.co/t/primedatainput6410/m/nava4113/1671805673271/ba355d0f84b6f3cc2c4334610ca86aee3e9d52f2?sender=u0c3cdba5126734aceb613229)
- [Figma workspace](https://www.figma.com/design/Du7feM8huRDAAZCQcUIj93/Website?node-id=6785-1107&t=ZXK35QqbUHqpC1W1-1)

## Acceptance criteria

- [x] IA revisions proposed (using artifacts like the sitemap or through Figma mockups) 
- [x] IA revisions reviewed and approved by Product and Engineering
~- [ ] Code mapping tool designs for handoff are updated with finalized IA component~

## To do

- [x] Review spec design MVP with Product to determine first steps

**Comment by chris-kuryak** [comment]
May split into two tickets.

**Comment by jillian-hammer** [comment]
Reviewed with Eng and Product today. Notes below.

**Raw notes**
- EB: Prefer opt 2 > opt 3. Opt 2 like a toolbox vs. opt. 3 is holding your hand through something prescriptive
- VC: Is it possible to do all 3?
- + Opt 1: the links should be in the auth nav
- + Opt 2: need a landing page
- + Opt 3: having the instructions is helpful
- JA: +1 to Etan, like opt 2 + 3.
- JA: Where would the landing page live in the nav?
- CK: The three diff opts all solve 3 diff issues.
- + Opt 1: We need a place for these tools to live
- + Opt 2: Clarifies with what RS has to offer for logged in users
- + Opt 3: Clarifies what the onboarding steps are
- CK: Have heard more of a user need for Opt 3
- CK: Thinking of the MVP as a public version of Opt 3
- + Reframe as the first step being reworking our onboarding steps & content
- VC: Need to make sure that as a PRIME admin, I can dupe the org and actually use the tools
- + Action: Flag for future investigation

**Next steps**

- Jillian/Chris/Victor (early Q2): Review onboarding steps and update site-wide
- Jillian (early-mid Q2): Design auth nav bar to include more clear link to the Landing page while Chris/Etan build the code mapping tool with ACs to add to the auth nav bar
- Jillian (late Q2): Design auth landing page that incorporates all 3 options

**Comment by jillian-hammer** [comment]
Removed last AC because we are blocked by the need to update the design for the auth bar.

Updating the code mapping design with the final nav component is now an AC for this Q2 ticket: **Update auth navigation bar design #16832**. Closing!
