### ISSUE TITLE
Test remaining LOINCs with Pennsylvania

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#16709]
## Problem statement
Pennsylvania recently sent us a list of LOINCs they approved to send to them. However, that did not include ALL of the LOINCs we sent over for testing and approval. So we need to test and get approval from PA with the remaining LOINCs.

## What you need to know

- The gap list (that compares approved list vs list we sent over) has been created in Excel format here:
https://cdc.sharepoint.com/:x:/r/teams/ReportStream/Shared%20Documents/Engagement/STLTs%20and%20Senders/Pennsylvania/Test%20list-filled.xlsx?d=w250c74ffa87e45d1b8d61d8384527073&csf=1&web=1&e=hdhyNE
- The unapproved LOINC list (that need to be re-tested and approved) are here:
94762-2		Atellica IM SARS-CoV-2 Total (COV2T)
95425-5 	Advanta Dx SARS-CoV-2 RT-PCR Assay
94533-7		PacificDx Covid-
1992141-1	Bio-Rad Reliance SARS-CoV-2/FluA/FluB RT-PCR Assay Kit
94565-9		BioFire Respiratory Panel 2.1 (RP2.1)
95409-9		Labcorp Seasonal Respiratory Virus RT-PCR DTC Test
95209-3		Ellume COVID-19 Home Test
94534-5		KimForest SARS-CoV-2 Detection Kit v1 0
94558-4		BD Veritor System for Rapid Detection of SARS-CoV-2
95970-0		T-Detect COVID Test
94500-6		Boston Heart COVID-19 RT-PCR Test
95609-4		Helix COVID-19 NGS Test
98132-4		BD MAX COVID-19 ASSAY (Authorized by HHS/OASH)
95608-6		Lucira by Pfizer COVID-19 & Flu Home Test
94559-2		LumiraDx SARS-CoV-2 RNA STAR Complete
82170-2		8.15381E+11
94500-6		Boston Heart COVID-19 RT-PCR Test
99597-7		AdvanSure SARS-CoV-2 IgG(RBD) ELISA
95409-9		Labcorp Seasonal Respiratory Virus RT-PCR DTC Test
80383-3		BD Veritor System for Rapid Detection of SARS-CoV-2 & Flu A+B
72885-7		No Test Device
94534-5		KimForest SARS-CoV-2 Detection Kit v1 0
96091-4		CRL Rapid Response
80387-4		No Test Device
96448-6		SalivaDirect
82168-6		
97097-0		QIAreach SARS-CoV-2 Antigen
96119-3		VITROS Immunodiagnostic Products SARS-CoV-2 Antigen Reagent Pack
82166-0		OPTI SARS-CoV-2/ Influenza A/B RT-PCR Test (Version 1 and Version 2)
82176-9		
49580-4		No Test Device

Use Abi's script to extract data out of HL7 messages for PA and populate sheet.

Suggested next steps:
- Send a test message through Simple Report and make sure it gets routed to the STLT
- Send test messages according to the STLT needs

## Acceptance criteria
- [ ] Confirm with STLT approval of new LOINCs (above)
- [ ] Update the production PA filter of approved LOINCS to include all of the new approved LOINCs

**Comment by chris-kuryak** [comment]
Spillover: Waiting on response from PA

**Comment by oslynn** [comment]
==== List of LOINC Codes are not in RS ====
1992141-1 Bio-Rad Reliance SARS-CoV-2/FluA/FluB RT-PCR Assay Kit
94534-5 KimForest SARS-CoV-2 Detection Kit v1 0
94558-4 BD Veritor System for Rapid Detection of SARS-CoV-2
98132-4 BD MAX COVID-19 ASSAY (Authorized by HHS/OASH)
94559-2 LumiraDx SARS-CoV-2 RNA STAR Complete
82170-2 8.15381E+11
72885-7 No Test Device
94534-5 KimForest SARS-CoV-2 Detection Kit v1 0
80387-4 No Test Device
96448-6 SalivaDirect
82168-6
82176-9
49580-4 No Test Device

**Comment by oslynn** [comment]
Uploaded 2024-12-30
File: pa-receiver-transform.yml-dfb7ac85-8ce1-426b-a78c-1a027c076fae-20241230193515.hl7
94534-5 KimForest SARS-CoV-2 Detection Kit v1 0

File: pa-receiver-transform.yml-df148019-cf46-4b29-81a0-78c53ea31e8f-20241230173813.hl7
94558-4 BD Veritor System for Rapid Detection of SARS-CoV-2
98132-4 BD MAX COVID-19 ASSAY (Authorized by HHS/OASH)

file: pa-receiver-transform.yml-80936b84-922c-4da0-87d6-3bc046415e80-20241230173819.hl7
94559-2 LumiraDx SARS-CoV-2 RNA STAR Complete
96448-6 LDT: SalivaDirect

==== the Test Device below gives weird LOINC code ==== Need to talk to @victor-chaparro 
82170-2 00815381020659 - BIOFIRE SPOTFIRE system_BioFire (give LOINC 82169-4)

**Comment by oslynn** [comment]
Done.  Uploaded the last MU spreadsheet file 2024-12-31:
junk/PA/UP/MU_Message_Validation_Tracking-another-unapproved-msgs.xlsx

**Comment by oslynn** [comment]
Done for now
