### ISSUE TITLE
Onboarding North Carolina

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1671]
North Carolina attended the Intro to Prime session with Sparkle, so I've created this ticket to start tracking work for them once they complete our intake form.

fysa: @Adrian-Brewster @jlusds

**Comment by jlusds** [comment]
Duplicate task: https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/971
