### ISSUE TITLE
Document current authorization implementation

### ISSUE THREAD

**Issue by jalbinson** [CDCgov/prime-reportstream#16722]
### User Story
As a member of the ReportStream team, I would like to understand our current authorization strategy.

### Description/Use Case
We need clear documentation of our current authorization strategy so we can make informed decisions going forward. We want to make sure we can support all the same use-cases as the existing system if we were to decide changes are warranted.

### Dev notes
See all endpoints defined [here](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/Shared%20Documents/Engineering/Design/rs-endpoints.xlsx?d=wece516211a11494fb111e8376f38a45d&csf=1&web=1&e=d17kSb)

### Acceptance Criteria
- Document current authorization approach(es)
- Document all endpoints authorization requirements including:
  - required scopes
  - required groups
  - any other checks (e.g.: client_id header, checking scope and group name formatting)
 - Document pros and cons of our current system

**Comment by MichaelEsuruoso** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/16722?planning-poker) with Zenhub @jack-h-wang @jalbinson @JFisk42 @kant777 @wcutshall
