### ISSUE TITLE
Map Error/Warning Messages

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#1677]
## Problem Statement

As a Sender, when I use the CSV uploader to submit data, I would like to understand an error or warning messages that are returned so that I will know how to fix the data before I re-submit it.

## Background

When ReportStream receives data, validation of that data occurs. Should it detect any errors or warnings, it will produce error messaging. This spans the gamut of ReportStream products and users.
 
At this time, validation is somewhat basic, and there is a desire to explore new possibilities. There has been discussion of creating unique validation rules to meet the needs of each user and/or state.
 
Error messaging, which is dependent on validation, is subsequently limited. Initial error/warning messaging copy has been developed from the basic system validation available now and there is a desire to extend user-friendly messaging to a variety of users.

However, the desire to expand data validation and error messaging has been somewhat loose in terms of needs, a process, and timeline.

**Comment by hie1** [comment]
First pass at copy complete. 
Had a discussion with Lori about bubbling this up to a ReportStream wide issue to uncover needs and opportunities. She is bringing it to Kevin.
