### ISSUE TITLE
Review Fortify findings

### ISSUE THREAD

**Issue by devopsmatt** [CDCgov/prime-reportstream#16787]
Review Fortify results in both reportstream and linuxforhealth FHIR processing reports and comment.

**Comment by scott-aquia** [comment]
Creating prioritized lists of remediation categories; in some cases there are 15-20+ issues of the same type, which should allow them to be grouped for more streamlined resolution

**Comment by scott-aquia** [comment]
The remediation items have been prioritized, added to the draft POA&M, and provided to the dev team for review and verification (18 Dec).
