### ISSUE TITLE
Dependabot PRs fail due to permission restrictions on writing test results to PR

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#1686]
Re: https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/

Per https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches, Dependabot PRs will not publish test results to get around this issue.

Acceptance criteria:
1. Dependabot builds do not fail on publishing test results.

**Comment by snesm** [comment]
Resolved through several workflow optimizations and conditional testing.
