### ISSUE TITLE
Bug: The value “%%placeholder” is looked up if the test_performed_code is null/empty

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1688]
This is very old.  First step is to see if the bug can even be recreated.
---

If the test_performed_code is null/empty, the livdLookup() tries to look up the value “%%placeholder”.

Design notes:
- This code is very tricky.  You'll need to understand how the mapper code works, including the Two Passes it executes, and why, and why we use this "placeholder" value at all.
- Next step is to try to recreate the bug.   I found this bug while trying to confirm that the test_authorized_for_otc value calculation is working.  It wasn't working for cases where the testPeformed is null/empty.    The reason is that the code is putting the value %%placeholder' in testPerformed, then the livdLookup() mapper tries to filter on that value, and of course doesn't find it in the Supplemental table.

- After you have fixed the bug, please expand the tests in `./prime test --run otcproctored` to cover cases both where the test_performed_code is wrong (that is, it doesn't match the correct row in the LIVD-Supplemental table) and where it is empty.
- I suspect there are other bugs where this '%%placeholder' value is "leaking thru" into our output data.   If you see any, please create tickets for them.

Acceptance criteria:
1. Replicate and document the issue that results in the “%%placeholder” value being looked up.
2. Fix the issue if the effort is small, or propose a fix if the effort is large.
3. Update tests as necessary to make sure this change is covered.

**Comment by san-nat** [comment]
i created a sample input file using prime for strac sender and updated the equipment_model_name to "BinaxNOW COVID-19 Antigen Self Test" on LIVD-Supplemental table. I was not able to recreate the error. Just checking if i'm missing any field(s) on my file (fyi: I was using stracSender and report post call was successful)
[strac_input.csv](https://github.com/CDCgov/prime-reportstream/files/6866245/strac_input.csv)

To generate a sample file,
a) `./gradlew primeCLI --args="data --input-fake 1 --input-schema strac/strac-covid-19 --output-dir ./ --target-states CA --target-counties 'Santa Clara' --output-format CSV"`
b) modify ordering_facility_state to IG & ordering_facility_county to OTC_PROCTORED

Send a post to report endpoint
`curl -X POST -H 'client: ignore.ignore-strac'   -H 'Content-Type: text/csv'   --data-binary '@./src/test/csv_test_files/input/strac_input.csv'   'http://localhost:7071/api/reports'`

**Comment by jimduff-usds** [comment]
Same as #1335 ???

**Comment by oslynn** [comment]
There is no %%**placeholder** use with the new code anymore.  CsvSerializer.kt: mapRow use "" instead of %%**placeholder** when useCsv(element) is null/empty.  Therefore, I close the ticket.
