### ISSUE TITLE
Don't warn on missing HHMM for HHS covid dates

### ISSUE THREAD

**Issue by joemeree** [CDCgov/prime-reportstream#1693]
We warn on missing HHMM for this file and say we "need" HHMM".  HHS doesn't need these for covid tests.  Can we change this fields from datetime to date?
I got this with a good HL7 file (HHS only requires YYYYMMDD)
  "warnings" : [ {
    "scope" : "ITEM",
    "id" : "",
    "details" : "Timestamp for OBR-22 - date_result_released needs to provide more precision. Should be formatted as YYYYMMDDHHMM[SS[.S[S[S[S]+/-ZZZZ"
  }, {
    "scope" : "ITEM",
    "id" : "",
    "details" : "Timestamp for SPM-17-1 - specimen_collection_date_time needs to provide more precision. Should be formatted as YYYYMMDDHHMM[SS[.S[S[S[S]+/-ZZZZ"
  }, {
    "scope" : "ITEM",
    "id" : "",
    "details" : "Timestamp for OBX-19 - test_result_date needs to provide more precision. Should be formatted as YYYYMMDDHHMM[SS[.S[S[S[S]+/-ZZZZ"
  } ]
}

**Comment by carlosfelix2** [comment]
Looking at the HL7 fields, they are all defined as date times.  
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Name | HL7 Field | HL7 Type | HL7 Field Name | Comments
-- | -- | -- | -- | --
date_result_released | OBR-22 | DTM | Results Rpt/Status Chng - Date/Time |  
specimen_collection_date_time | SPM-17-1 | DTM | Specimen Collection Date/Time |  
test_result_date | OBX-19 | DTM | Date/Time of the Analysis (TS) 01480 |  
test_result_report_date | OBX-22 | CNE | Mood Code | OBX-22 Reserved for harmonization with V2.6
testing_lab_specimen_received_datetime | SPM-18-1 | DTM | Specimen Received Date/Time |  


</body>
</html>
We could just remove the warning sent back as the HL7 spec does not require the precision, however, we would like that precision.

**Comment by carlosfelix2** [comment]
Discussed this at the sync meeting.  We do want to push senders to provide better data and a date/time without HHMM and/or timezone lacks precision receivers may need.  For example, getting a DATE/TIME with no timezone from an EST timezone will result in a DATE/TIME set to UTC timezone that when used by a receiver it will show a different EST time.  We want to leave the warnings to push the senders to provide better data.  The warnings do not stop us from ingesting the data.
