### ISSUE TITLE
SendGrid: Add PHD name and state to daily email template

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#1695]
## Problem statement

As a mail recipient I want to be able to see some sort of personalization in the message body. 

## What you need to know

The [original mockup](https://github.com/CDCgov/prime-reportstream/pull/1434#issuecomment-870258224) included the PHD name and state above the headline in a `<p>`. Could be a start to further personalization as we expand to different message types.

- [Mockup img](https://camo.githubusercontent.com/4780e4b03f3cf14a0f6cf58ba3878632ccfea283f404032e0c06ea8341f92fe6/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566663530653439663734653133346539353131373238302f61663232316338372d663661342d346439342d616330372d373835326430303134623035)

## Acceptance criteria

- [ ] Mail recipients can see PHD name and state in sent messages

## To do

- [ ] (DEV STUFF!)
- [ ] Update Foundation template and re-export inlined template
- [ ] Update template in SendGrid

**Comment by chris-kuryak** [comment]
SendGrid allows customization of automated emails. Currently using SendGrid.

Not a bad idea, but not a priority at this time. Closing now. It will rearise naturally if necessary.
