### ISSUE TITLE
SendGrid: add today's date to subject and body of daily email template

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#1696]
## Problem statement

Need to be able to display today's date in a SendGrid template. Will help differentiate alert messages and help folks understand what day/data is being linked to.

## What you need to know

The documentation for dateFormat is only _kind of_ helpful. It shares how to format time/date but not how to actually GET that date. Want to be able to print the date for the same day the message is sent.

- [dateFormat documentation](https://docs.sendgrid.com/ui/sending-email/adding-dynamic-content-with-handlebars-in-marketing-campaigns#use-the-formatdate-helper)

## Acceptance criteria

- [ ] Date in format `MM/DD/YYYY` is part of the subject line --> "ReportStream data for 07/22/2021 is ready for download"
- [ ] Date in format 'dddd MMMM D, YYYY` is the link text to go to the download site.
>View and download daily test results for <a href="https://reportstream.cdc.gov/daily-data/" style="Margin:0;color:#2199e8;font-family:Helvetica,Arial,sans-serif;font-weight:400;line-height:1.3;margin:0;padding:0;text-align:left;text-decoration:underline">{{ however dates work 'dddd MMMM D, YYYY' }}</a>

## To do

- [ ] ...
- [ ] Update Foundation template and re-export inlined template
- [ ] Update template in SendGrid

**Comment by TomNUSDS** [comment]
This SendGrid doc seems related: https://docs.sendgrid.com/ui/managing-contacts/custom-fields

Looks like SendGrid has a preset reserved field for `created_at` and `updated_at`. These might just work by editing the template to use them, but it sounds like we don't want the send date.

_Note that it looks like the current [subject line is hard coded](https://github.com/CDCgov/prime-reportstream/blob/66db85e3f9c199f6394f20baa6a431d5738070da/prime-router/src/main/kotlin/azure/EmailEngineFunction.kt#L43)_?

Right now it looks like reports are _always_ the day before `OffsetDateTime.now().minusDays(1L)`, but there's also some fuzziness around local timezones & midnight. (e.g. will `create_at` likely seem wrong if sent around midnight UTC and/or if the receiver is PST?)

We could add a custom field for `rs_yesterday_created_at` which is always set to `OffsetDateTime.now().minusDays(1L)`, then we could use that in templates. (Also do we have any standard around adding a prefix or suffix for ReportStream specific values like `rs_...` or `..._report_stream`?)  


So, I _THINK)_ we'll need something like this defined (not really sure until I get a test account and play with things). 
```handlebars
{{#if rs_yesterday_created_at}}
{{formatDate rs_yesterday_created_at "MM/DD/YYYY"}}
{{else}}
yesterday
{{/if}}
```
Not certain where this goes in the SendGrid config (or how we're backing up / configuring such SendGrid config data).

And in our a template it might look something like this: 
```handlebars
"ReportStream data for {{rs_yesterday_created_at}} is ready for download"
```

Will generate:
`"ReportStream data for yesterday is ready for download"`
`"ReportStream data for 07/22/2021 is ready for download"`



@drew-usds / @mry-usds  To work on this bug, I'll need to get setup with a dev sendgrid account.

**Comment by chris-kuryak** [comment]
Not a bad idea, but not a priority at this time. Closing now. It will re-arise naturally if necessary in the future.
