### ISSUE TITLE
Create API Endpoint To Get A Synthetic Data CSV

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1697]
We need an endpoint that takes a function key, a list of target states, and a count of records between 1 and 50, with a default of 50 and returns a file of synthetic data that is collected from multiple files.

Acceptance criteria:

- The endpoint is accessible only by a function key
- Invoking the endpoint returns a binary CSV file of the number of rows requested
- Requesting an invalid number of rows, either less than 1 or more than 50 returns a 500 error
- If a list of target states is not provided, it will have one row for each state
- The data is synthetic and does not contain PHI or PII
- If there are less rows than states selected it will randomly select states

fysa: @jlusds @Adrian-Brewster

**Comment by jlusds** [comment]
What's the progress of this? Is this necessary for sprint 22?
