### ISSUE TITLE
Create feature to provide replacement values for any HL7 field per organization

### ISSUE THREAD

**Issue by brick-green-agile6** [CDCgov/prime-reportstream#1709]
We need to be able to set replacement values for any HL7 field. There is currently an option to suppress fields which essentially sets the field to a blank string. This feature will expand that functionality to set the replacement to any value including blank.

Strategy:

- Add property to HL7Configuration to accept array of HL7 fields with replacement values
- loop through pairs to set default values in HL7 serializer

Acceptance criteria:

- empty or filled strings can be set as default values
- only fields with a value can be replaced. Blank values will be left blank.
- does not error for non existent HL7 field (ex. MSH-99999-1) in serializer only in test
- allows any number of fields to be set
- checks that replacement values are only set once per organization (don't want later replacements to overwrite earlier replacements)

Notes:
- Are there fields where replacements should not be allowed? (Test name, test result, patient name, etc)
     - Answer: This is currently only set by developers. No restriction needed. Restriction may be needed when/if the functionality is made available to receivers. 

Solution:
Use yaml dictionary then loop through map in hl7 serializer
```
replaceValue:
- OBX-23-1: ReplacementVal
- PID-14-5: ReplacementVal
```

**Comment by brick-green-agile6** [comment]
@carlosfelix2 Can you take a look at this?

**Comment by jlusds** [comment]
What's the status of this?

**Comment by brick-green-agile6** [comment]
This is completed by PR #1740 . But it hasn't been merged in yet. Still need a review.
