### ISSUE TITLE
Move email-templates out of prime-router, add no-data email template

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#1710]
## Problem statement

Per standup discussion today, move `/prime-router/assets/email-templates` to `/email-templates`. Also update the daily email template with an alt option for when no data is available.

## What you need to know

N/A

## Acceptance criteria

N/A

## To do

- [x] Move previous foundation for emails files into `/email-templates`
- [x] Create second daily email template for when no data is available.
- [x] Update readme
- [x] Add to SendGrid

**Comment by drew-usds** [comment]
Updated no-data email copy

Subject: No COVID-19 test data was reported today

>No COVID-19 test data was reported today
>
>There are no new daily test results available in ReportStream. To view previously reported data, {{link}}log in to your account{{link}}.
>
>Data aggregated with ReportStream may be subject to the Privacy Act of 1974, the Health Insurance Portability and Accountability Act of 1996 (HIPAA), and other laws, and requires special safeguarding.

![Screen Shot 2021-07-23 at 5.22.05 PM.png](https://images.zenhubusercontent.com/5ff50e49f74e134e95117280/dadaee5c-ecbe-41dd-bc74-516f7d00ecae)

**Comment by jlusds** [comment]
LGTM
