### ISSUE TITLE
NPI Lookup Tool

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#1732]
## Problem Statement

As the ReportStream team, we should create a tool that allows us to access the NPI facility data maintained by CMS so that we can lookup facility information when senders' data is incomplete.

## Notes
- According to Mike, there is an API for this NPI data. https://npiregistry.cms.hhs.gov/api/demo?version=2.1
- Refer to the following document from Rick Hood for background info: https://docs.google.com/document/d/12t5Dsld7ecTE-MMCDeJ33af9Zcub_XL0-wmIYSD8XSM/edit

**Comment by carlosfelix2** [comment]
Placeholder.  On hold for now.
