### ISSUE TITLE
Loading spinner component

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#1743]
## Problem statement

As we start working with new test types or advanced filtering, users may experience a beat or two of load time. Create a reusable loading spinner/indicator that can work across RS.

## What you need to know

- As we're moving to React ... is there anything built in there that might be helpful with this? Theoretically things should be pretty swift with React anyway, right?
- USWDS doesn't have a default spinner. We could use some of their default icons and animate with css or js? 
- **Update: Mo added this as a stopgap solution for the time being** Font Awesome has a default spinner class, but would invovlve adding some weight to the project and may duplicate some of the icons we already have with USWDS.
- It also doesn't have to be a "spinner" either, investigate other loading indicators that may work.

## Acceptance criteria

- [ ] Users are able to see an indicator that something is loading on the page

## To do

- [ ] ...

**Comment by kevinhaube** [comment]
@TomNUSDS I would second that! My latest PR does add the `App`-level spinner back because we did have that uncaught suspense warning happening. If that doesn't fix the "loading" message displaying on page refresh in Staging then we can report that as a separate bug.
