### ISSUE TITLE
Add tribal affiliation to the simple report schema

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1746]
On July 29, SimpleReport team gave us a request to handle tribal affiliation

@nullflux is technical Point of Contact; @aliciabeckett-gov is product owner on SimpleReport.

Rick says tribal affiliation is an OMB Valueset.   SimpleReport grabbed our table, so they are already "speaking ur language."  They are using Strings at the moment; but we'd prefer they send the code.

This ticket is done when tribal affiliation is added as a column in the simple report schema, and it meets their needs.

Acceptance criteria:
1. Tribal affiliation is added to the simple report schema to take a string?????

**Comment by jimduff-usds** [comment]
@nickscialli-usds has asked for this.

**Comment by whytheplatypus** [comment]
Open questions:
- Does the [tribal citizenship](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/metadata/valuesets/tribal.valuesets) valueset represent the information that needs to be captured
- How is this being sent currently? (what is the header, what are some values?)

**Comment by whytheplatypus** [comment]
Give that the [numbers match](https://github.com/CDCgov/prime-simplereport/blob/main/frontend/src/app/constants/constants.d.ts#L16-L582) it looks like the [tribal citizenship valueset](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/metadata/valuesets/tribal.valuesets) does carry the same information. And they are sending the code, as a string.

**Comment by whytheplatypus** [comment]
[It looks like](https://github.com/CDCgov/prime-simplereport/blob/main/backend/src/main/java/gov/cdc/usds/simplereport/api/model/TestEventExport.java) this information isn't being put into the csv yet, however it is being gathered.
