### ISSUE TITLE
Add preferred language to the Simple Report schema

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1748]
On July 29, SimpleReport team gave us a request to handle preferred language.

Santa Clara requested this: patient preferred language.  Rick says there should be an HL7 standard for this.

@nullflux is technical Point of Contact; @aliciabeckett-gov is product owner on SimpleReport.

This ticket is done when patient preferred language is added as a column in the simple report schema, and it meets their needs.

See related ticket #1746

**Comment by whytheplatypus** [comment]
Possible value set to use: http://hl7.org/fhir/R4/valueset-languages.html

**Comment by aliciabeckett-gov** [comment]
This value set does not support all SimpleReport languages :*( For example, Amaric, Creole, and Farsi are all missing from the FHIR standard list. 

I ended up creating a custom list because NONE of the standards met the needs of CA's list of languages people actually speak. My recommendation is pass through the language as plain text and not a code, or ask CA how they do it in their other ELR feeds.

**Comment by whytheplatypus** [comment]
Understood, so this is aiming to meet the needs of CA first and foremost?

It sounds like starting with a plain string is a reasonable first iteration.

**Comment by whytheplatypus** [comment]
It looks like CA has a [`local_language`](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/metadata/schemas/CA/ca-scc-covid-19.schema#L70-L74) in their schema, but I'm assuming _this_ language field is something new?

For input I'm guessing it would be submitted in the CSV under something like `Preferred_language`?

**Comment by aliciabeckett-gov** [comment]
@nullflux is the person to work with on adding preferred_language to the SimpleReport schema. We should be able to add that and Tribal Affiliation quickly, and already have those tickets in our backlog.

https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/1799
