### ISSUE TITLE
OTC Front End Bug Bash

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1752]
Here is the ticket to track the OTC Front End Bug Bash issues found.

Example single feed = OH
Example double feed = NM
Example null feed = NJ

Tabs only show up if you have data

External names are not yet set up yet as of 7/29

**Comment by jlusds** [comment]
What I did:
Pima AZ PHD user

https://staging.reportstream.cdc.gov/report-details/?6d6a8dad-e777-41dc-b7e6-16c30b656189

![image.png](https://images.zenhubusercontent.com/5ff5f0b60a28f3db67e4bfed/ca779ce7-b803-4284-a35d-a63254a8a340)

Problem:
Shows "Report: This is the report ID" at the top

What I expect:
Report: [actual report id]

**Comment by brick-green-agile6** [comment]
Problem:
Dropdown not available on first login. I have to refresh the page for the feature to preset.

What I expect:
Dropdown available on every page load.

![image.png](https://images.zenhubusercontent.com/60d23d7dcaf07751be9205b6/f3f03318-921f-4f1d-ae8b-701f0be203d6)

**Comment by jlusds** [comment]
What I did:
NM user

https://staging.reportstream.cdc.gov/report-details/?3d45fca3-0fdb-4a11-bdca-0d5b9c2de43f

![image.png](https://images.zenhubusercontent.com/5ff5f0b60a28f3db67e4bfed/913d65ff-ff03-476d-aecf-0657267523b0)

Problem:
When I click HL7, nothing happens
See some javascript (see bottom of the screenshot)

What I expect:
The report to be downloaded

**Comment by Adrian-Brewster** [comment]
In Safari, no results populate for me (MPZ9). I have given it time to load and still no results populate.  

![Screen Shot 2021-07-29 at 1.28.57 PM.png](https://images.zenhubusercontent.com/60d1eba7caf0775fd79203f8/fd28abd9-0732-430a-b742-84350cc8df2a)

**Comment by brick-green-agile6** [comment]
Problem:
Dropdown list overlaps Logout link. If a user accidentally double clicks the option covering the link then they will logout of their account.

What I expect:
Logout link is not covered by dropdown list eliminating the possibility of clicking the logout

Browser:
Chrome

**Comment by Adrian-Brewster** [comment]
Problem:
SMS Authentication has option to not "challenge" me with this device for 24 hours. Every time I log out and log back in, it asks to resend. 

What I expect:
Only have to authenticate once per 24 hours. 

Browser:
Safari

![image.png](https://images.zenhubusercontent.com/60d1eba7caf0775fd79203f8/ce9da6fd-dd0d-4ae4-9bd9-d89c00a7b173)

**Comment by brick-green-agile6** [comment]
Problem:
Columns are not sortable

Expected:
columns to be sortable

Environment:
Chrome on mac

![image.png](https://images.zenhubusercontent.com/60d23d7dcaf07751be9205b6/a75c1f84-d22e-4256-b4a6-7de0ec30d179)

**Comment by Bisonburger** [comment]
Problem:  wait time for data
Expected: some indicator of "waiting for data"

especially apparent when switching organizations (old data remains)

**Comment by MauriceReeves-usds** [comment]
We need a spinner for data when load times are slow.

**Comment by MauriceReeves-usds** [comment]
When data is slow to load, it can cause a user to click on the drop down twice, which then can end up having results in the table to duplicate as they are concatenated.

**Comment by jorg3lopez** [comment]
What I did:
logged in using Chrome and selected PIMA-AZ-PHD
![image.png](https://images.zenhubusercontent.com/60d4ee31a2886cc02f9caaef/36d8e14f-8018-4b84-a67f-df186025a5e9)

then, I logged in using MS Edge and selected PIMA-AZ-PHD
![image.png](https://images.zenhubusercontent.com/60d4ee31a2886cc02f9caaef/8ee9d7e4-13bf-4005-9b3a-3d3d19d9491d)

Problem:
I couldn't see any reports in Chrome, but I was able to see the reports  using MS Edge. Also, I kept on getting 401 status codes under Chrome.

![image.png](https://images.zenhubusercontent.com/60d4ee31a2886cc02f9caaef/6bfe317a-42bb-46e5-91ba-5898429f0243)

**Comment by Bisonburger** [comment]
When clicking on the details - I always see "Report: This is the report ID"

**Comment by brick-green-agile6** [comment]
What I did:
Loaded PIMA main page. Selected first report to enter report details. Opened dropdown to change receiver. The page remained on report detail.

Problem:
New organization does not load when selected if current page is report detail. But the breadcrumb did change.

Expected:
The main page for an organization is opened when selected from the dropdown

**Prior to clicking new organization in dropdown:**
![image.png](https://images.zenhubusercontent.com/60d23d7dcaf07751be9205b6/8bf75007-f1d9-4d0a-9717-e05ff75e5af2)



**After clicking new organization in dropdown:**
![image.png](https://images.zenhubusercontent.com/60d23d7dcaf07751be9205b6/dafb542e-6164-499c-b919-68901eff1044)

**Comment by Bisonburger** [comment]
Switching organizations while in detail view changes the organization description - but still shows the old record (as if its still part of old organization)
refreshing the data - creates the display without any data in it
