### ISSUE TITLE
Creating Verbose, User-Friendly Error Messaging

### ISSUE THREAD

**Issue by hie1** [CDCgov/prime-reportstream#1756]
## Problem statement

As a Sender who uploads my CSV file, I need to understand the content of error messaging so that I can make adjustments to my file with confidence.

## What you need to know

**Design**
In the Figma File, you will see see a tab called "Error States" it shows the current and future states.
- https://www.figma.com/file/ctpYEoOBWGkUnk9cmXzVp2/ReportStream-Submitter-Front-End?node-id=943%3A4273

## Acceptance criteria

- Given I
    - Am logged into ReportStream as a user with Sender permissions
- When I
    - Navigate to the new Sender submission page
    - Choose a file to upload (i.e. browse or drag/drop) 
    - Upload the file (system submits it to ReportStream)
    - ReportStream returns one or more of the following messages
        - success message
        - error message
        - error message with additional alerts (warnings that are optional to address)
        - success message with additional alerts (warnings that are optional to address)
- Then 
   - ReportStream needs to generate verbose, error-friendly messages for the raw messages that are returned
       - **NOTE: this work involves trying to figure out how to incorporate the mapping of system messages to verbose, user-friendly messages**

## To do

- [ ] Dev: Create a full inventory of error and warning messages in current state
- [ ] Design: After full inventory created, develop copy appropriate for non-technical users
- [ ] Dev: Explore how to map the verbose copy to the current state error messages so that verbose copy will appear in CSV Uploader
- [ ] Dev: Test that mapping has occurred correctly and completely

**Comment by hie1** [comment]
adf

**Comment by hie1** [comment]
**Entered Jim Duff's feedback into spreadsheet:** https://docs.google.com/spreadsheets/d/1vrm_TudKG9SntHhm8BgrdOLs_fIIr6KeAzbqnlgNXeg/edit#gid=1323508253

Asked for Tom's clarification on several comments - responses in spreadsheet

**Comment by hie1** [comment]
Asked Tom if each error had sub-errors like he produced for lines 13 and 14. If so, we have a lot of copy to write.

**Comment by hie1** [comment]
Tom provided 'sub-errors' to address Jim Duff's feedback. It came to our attention that the other parent errors in the spreadsheet also likely have multiple sub-errors that need to be documented. We brought this to Tom's attention but then Data Robot's contract ended.

There are two pieces up in the air at this point:
1) We need to get a full inventory of all errors.
2) Once completed, these errors will need to be mapped in the backend of the system. Tom was originally going to do this and is now gone.

**Comment by hie1** [comment]
@wwilliams-Agile6 - The inventory of errors to date may be complete but I am NOT sure. In lines 13 and 14, there are 'sub-errors' that are produced. I understand that these are more specific and would be bubbled up to a more generic error. However....

1) Jim has requested that user's fix any issues with their file themselves rather than contacting the help desk. Therefore, RS would need to bubble up the specific rather than a generic error. Is this possible? Lines 9. 13, 14, 17.

2) I need you to look into the sub-errors for lines 9 and 17. These are the remaining two in which we currently direct the users to contact the help desk.

**Comment by loripusey** [comment]
@hie1 and @wwilliams-Agile6 I am confused as to what work this ticket involves; typically the "Then" portion of the AC describes the new work that needs to be done but this ticket includes work from all of the other tickets for the uploader, so what work needs to be done as part of this ticket?
