### ISSUE TITLE
Jurisdictional Newsletter

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#1757]
Jurisdictional Biweekly Newsletter Proposal  
 
Need:  
States need to stay updated on all things related to PRIME. This is particularly necessary as we onboard new senders to states that are already connected to ReportStream, but it is also a great opportunity to keep us on the radar for states that are not connected yet. As we add new capabilities and evolve the program, we should be able to celebrate these steps forward with our receiving partners. 
 
Solution: 
Future state, we may find the need to host a weekly or biweekly update call (much like the APHL Open ELR Call). For now, though, our updates can be sent via a biweekly newsletter.  This newsletter will include highlights from the sprint demos (any exciting new capabilities), go live updates for new senders, updated maps to show who is connected to RS and who is in the onboarding phase, and general updates/announcements.  Please let me know if there is anything else you think would be particularly interesting to include. 
 
Initial workflow:  
Adrian and one other person (technical) will take notes during the sprint demo.   
Adrian will also reach out to product owners for updates that were not covered in the demo. 
Those notes will be sent to Berni who will compose the newsletter.   
We will meet the following Wednesday to review the newsletter.   
The newsletter will then be dispersed to the states via email.

**Comment by BerniXiongA6** [comment]
7.28.2021 Berni mocked up an eNewsletter template in Word in case we don't quickly get access to SendGrid:

[ReportStream eNewsletter DRAFT Berni 7.28.2021.docx](https://github.com/CDCgov/prime-reportstream/files/6907931/ReportStream.eNewsletter.DRAFT.Berni.7.28.2021.docx)

7.29.2021 @drew-usds is working on getting Berni access to Sendgrid (needs to connect with @mry-usds )

**Comment by brandonnava** [comment]
@BerniXiongA6 Is this similar to the announcement page on the website Experience updated recently? If so do we want to close this out as complete? Or ask Experience if this is something they want to take on?

**Comment by BerniXiongA6** [comment]
@brandonnava feel free to bring this back up with Exp team. This was an idea to start a newsletter that users could opt-in to receive updates from us. This would supplement the What’s New page.

**Comment by brandonnava** [comment]
Experience team has their own initiative for updating users. Closing this one.
