### ISSUE TITLE
New Team Member onboarding learning path

### ISSUE THREAD

**Issue by smythe5** [CDCgov/prime-reportstream#1778]

**Comment by BerniXiongA6** [comment]
8.6.2021: Project update

- Onboarding artifacts inventory created (still updating file): https://docs.google.com/spreadsheets/d/18FqTiMCJ3gABftY06yxt3anUVdOUW44Y/edit?usp=sharing&ouid=101042533948262644907&rtpof=true&sd=true

- Preliminary findings and recommendations report created: https://docs.google.com/document/d/1JpZ72NURRlOxfO34tZtbYLsHtYbLTrtpfQsO2_OQMJM/edit?usp=sharing
