### ISSUE TITLE
Set up shared responsibilities for ktlint

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-reportstream#1781]
-[ ] Reaching out to have conversation on process (e.g. paperwork)
-[ ] Update SOPs, as needed

**Comment by jorg3lopez** [comment]
Thomas and myself will take on this task. I will write the code and Thomas will check, review it, and approve.

**Comment by ronaldheft-usds** [comment]
@td-usds

**Comment by td-usds** [comment]
@jlusds can you provide some more information about where this is coming from? I'd like to understand
