### ISSUE TITLE
Further requests from CA

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1788]
I sent the attached file to CA-DPH, per their request, as an example of what we might be able to produce.   (See #1787)

(Jim Note:  HL7s run thru two programs at CA.   1) CCRS aka Optum, then 2) CalREDIE)

They ran it thru their system manually and sent us this email response:

---------------------

So one thing I can see that we need changed is the AOE questions which are currently showing as OBX segments.  We need those as NTEs sent after the OBX and before the SPM segment.  Here is an example format:
 
```
NTE|1|L|First test for condition of interest - UNKNOWN|
NTE|2|L|Employed in a healthcare setting - NO|
NTE|3|L|Has symptoms related to condition of interest - YES|
NTE|5|L|Admitted to intensive care unit for condition of interest - NO|
NTE|6|L|Resides in a congregate care setting - UNKNOWN|
 
```
Once I changed those and sent the HL7 in, it came right through for our Santa Clara build.

-  It would be nice to see “Simple Report” or “ReportStream” referenced somewhere.  I see OBX-17 is coming through as “10811877011290_DIT^^99ELR^^^^2.68^^10811877011290_DIT” so could we change it to “10811877011290_DIT^Simple Report^99ELR^^^^2.68^^10811877011290_DIT” if that works for you.  I tested it and it comes through okay into CalREDIE in the HL7.  It could also be added in the SFT segment. And if we want it to be visible to end users, we could add it as another NTE. 
 
Anyhow, happy to see this is moving along.  Please let us know once the temp changes you made below (I guess mainly the ISO reference) have been finalized, the AOEs moved to NTEs and the reference to Simple Report or ReportStream has been added and you have sent in more results. 
 
Thanks again for everyone’s work on this!
 
PS – just to see, I did send in a modified message using CLIA instead of ISO in ORC-2.4 and OBR-2.4 and it worked.  I checked our spec and it says it should handle up to 6 characters.  The default is ISO, but it seems like you can use CLIA after all.  And this was sent through CCRS, so it didn’t error there.  Here is the message if you want to review it.  I highlighted the changes (apart from patient demographics and the accession). 
 
```
MSH|^~\&|CDC PRIME - Atlanta,^2.16.840.1.114222.4.1.237821^ISO|Winchester House^05D2222542^ISO|CDPH CA REDIE^2.16.840.1.114222.4.3.3.10.1.1^ISO|CDPH_CID^2.16.840.1.114222.4.1.214104^ISO|20210803131511.0147+0000||ORU^R01^ORU_R01|1234d1d1-95fe-462c-8ac6-46728dba581c97|T|2.5.1|||NE|NE|USA|UNICODE UTF-8|||PHLabReport-NoAck^ELR_Receiver^2.16.840.1.113883.9.11^ISO
SFT|Centers for Disease Control and Prevention|0.1-SNAPSHOT|PRIME Data Hub|0.1-SNAPSHOT||20210726
PID|1||09d12345-0987-1234-1234-111b1ee0879f^^^Winchester House&05D2222542&ISO^PI^&05D2222542&ISO||RSTest^Karl^C^^^^L||19800101|M||2106-3^White^HL70005^^^^2.5.1|120 First St^^San Jose^CA^95125^USA^^^06085||(454)456-7890^PRN^PH^^1^454^4567890|||||||||N^Non Hispanic or Latino^HL70189^^^^2.9||||||||N
ORC|RE|1234a1a2^Winchester House^05D2222542^CLIA|1234a1a2^Winchester House^05D2222542^CLIA|||||||||1679892871^Doolittle^Doctor^^^^^^CMS&2.16.840.1.113883.3.249&ISO^^^^NPI||(123)456-7890^WPN^PH^^1^123^4567890|20210802||||||Winchester House|6789 Main St^^San Jose^CA^95126^^^^06085|(123)456-7890^WPN^PH^^1^123^4567890|6789 Main St^^San Jose^CA^95126
OBR|1|1234a1a1^Winchester House^05D2222542^CLIA|1234a1a1^Winchester House^05D2222542^CLIA|94558-4^SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay^LN^^^^2.68|||202108020000-0500|202108020000-0500||||||||1679892871^Doolittle^Doctor^^^^^^CMS&2.16.840.1.113883.3.249&ISO^^^^NPI|(123)456-7890^WPN^PH^^1^123^4567890|||||202108020000-0500|||F
OBX|1|CWE|94558-4^SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay^LN^^^^2.68||260415000^Not detected^SCT|||N^Normal (applies to non-numeric results)^HL70078^^^^2.7|||F|||202108020000-0500|05D2222542^ISO||10811877011290_DIT^Simple Report^99ELR^^^^2.68^^10811877011290_DIT||202108020000-0500||||Winchester House^^^^^ISO&2.16.840.1.113883.19.4.6&ISO^XX^^^05D2222542|6789 Main St^^San Jose^CA^95126^^^^06085
NTE|1|L|This test performed using ReportStream Simple Report|
NTE|2|L|Whether patient is employed in a healthcare setting - No|
NTE|3|L|First test for condition of interest - No|
NTE|4|L|Resides in a congregate care setting - Yes|
SPM|1|1234d1d1-95fe-462c-8ac6-46728dba581c&&05D2222542&ISO^1234a1a2&&05D2222542&ISO||445297001^Swab of internal nose^SCT^^^^2.67||||53342003^Internal nose structure (body structure)^SCT^^^^2020-09-01|||||||||202108020000-0500|20210802000006.0000-0500
```
 
(Jim note:  the above is a tweak of attached file.  You can do a diff to see what she changed)

**Comment by jimduff-usds** [comment]
[reportstream-example-for-CA.hl7.txt](https://github.com/CDCgov/prime-reportstream/files/6931170/reportstream-example-for-CA.hl7.txt)

**Comment by jimduff-usds** [comment]
My understanding is that the standard is for the AOE questions to go as OBX.

eg, from https://confluence.hl7.org/display/OO/Proposed+HHS+ELR+Submission+Guidance+using+HL7+v2+Messages
 it says "AOEs are sent as OBX segments after the OBR it applies to, but before the SPM."

**Comment by Adrian-Brewster** [comment]
A new folder for the secondary feed has been created on Optum.

**Comment by Adrian-Brewster** [comment]
From California regarding AOEs:

Suppressing the OBX segments with AOEs works for us as well. 
 
Let us know where you are adding the ReportStream or Simple Report reference and when you have sent over more messages so we can confirm receipt and review. 
 
Thanks!

**Comment by brick-green-agile6** [comment]
centralized CLIA of CDPH000075 (unless they were OTC results which should have been under
CDPH000076) for testing completed outside of the jurisdiction
