### ISSUE TITLE
Generate fake full ELR HL7

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1793]
We can generate fake CSVs.   This story is to generate fake full ELR HL7

This includes the ability to generate HL7s that represent both incoming data (eg careevolution) and outgoing (most states).

Will this use a FHIR 'profile' to generate this?

This will involve understanding how our current HL7 code uses (or does not use) schemas.   On the outgoing side, much of our HL7 code uses parametric in the receiver setting yaml configuration.    I don't know how incoming hl7 gets its schema layout.   We may need to separate generating incoming HL7 into a different task?

**Comment by jimduff-usds** [comment]
This is worth doing under the context of HCA and FHIR in the hole.   Needs grooming.

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/1793?planning-poker) with ZenHub @jimduff-usds @smythe5 @whytheplatypus @oslynn @carlosfelix2 @jh765

**Comment by carlosfelix2** [comment]
Delete in favor of first creating a plan for testing then creating the issues per the AC of #4138
