### ISSUE TITLE
Update state schemas for OTC/secondary feeds

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-reportstream#1836]
**Background**
OTC volume is increasing, and states have custom requirements on how and where they want to receive data. 
To date, we’ve built a filtering system that allows RS to have more flexibility send OTC data – to keep in the existing primary feed, to move to a second ELR feed, or to move to a download site. 
States have expressed that the OTC data, as is, cannot be ingested into their surveillance systems without more default fields. 
Goal is to offer a set of default fields we fill in if there is information missing

**Proposed defaults**
MSH 4.1  

- CDC PRIME OTC

MSH 4.2  

- For Over The Counter – Fake CLIA: 0OCDCPRIME  

- For At home testing with prescription – Fake CLIA: 0PCDCPRIME 

- For At home testing with prescription and tele proctoring – Fake CLIA: 0TCDCPRIME 

- All other CLIA fields 

>- Put same as MSH 4.2 

OBX-11, OBR-25 

- Result status is currently not being sent for OTC. If it cannot be sent, the default should be "F" for Final Result.

 

APHL Recommendations for Ordering Facility, Facility Name, address 

At home testing over the counter purchase– patient buys and performs testing, result is obtained via app that then does the reporting; this may result in limited data fidelity (no verification a) that person tested = patient, b) of how the specimen was collected, c) if the test procedure was followed, d) if the interpretation of the result and subsequent reporting is accurate, unless the app preforms the interpretation, e) data about the patient is accurate) 

Ordering Provider First Name (ORC-12.3/OBR-16.3) = “SA.OverTheCounter” 

Ordering Facility Name (ORC-21.1) = “SA.OverTheCounter” 

Ordering Facility Address (ORC-22) = <Copy patient address (PID-11)>  

Ordering Facility Phone (ORC-23) = <Copy Patient Home Phone (PID-13); if not available, use default value ^^^^111^1111111> 

Performing Facility Name (OBX-23.1) = “SA.OverTheCounter” 

Performing Facility CLIA (OBX-15.1 and OBX-23.10) = 00Z0000014 

Performing Facility Address (OBX-24) = “11 Fake AtHome Test Street^^Yakutat^AK^99689^^^^02282” 

Allowed test kits with EUA for this purpose: 

Ellume’s  COVID-19 Home Test_Ellume Limited -– OBX-17.1 = Ellume COVID-19 Home Test_Ellume Limited_EUA 

Cue Health Inc’s Cue COVID-19 Test for Home and Over The Counter (OTC) Use – OBX-17.1 = Cue COVID-19 Test_Cue Health Inc._EUA 

Lucira Health, Inc.’s Lucira COVID-19 All-In-One Test Kit – OBX-17.1 =Lucira COVID-19 All-In-One Test Kit_Lucira Health, Inc._EUA (will soon be updated in LIVD to: 00810055970001_DIT) - this is what will be sent via AIMS 

ANY OTHERS??? 

Example message is for Ellume’s  COVID-19 Home Test sent by OneAbbott: InterPartner~CentralizedELR~OneAbbott~AIMSPlatform~Test~Test~2021012816241013~STOP~TestMessageSA.OTC_AL_FINAL 

  

At home testing with prescription – patient is prescribed the test, obtains the kit, sample collection and test performance is unsupervised, result is obtained via app that then does the reporting; this may result in some limited data fidelity (no verification a) that person tested = patient, b) of how the specimen was collected, c) if the test procedure was followed, d) if the interpretation of the result and subsequent reporting is accurate, however data about the patient should be accurate – since it is coming from the provider’s health record) 

Ordering Facility Name (ORC-21.1) = <Copy Ordering Provider Name (ORC-12/OBR-16), if no separate facility> 

Ordering Facility Address (ORC-22) = <Copy Ordering Provider Address (ORC-24), if no separate facility> 

Ordering Facility Phone (ORC-23) = <Copy Callback number (ORC-14/OBR17), if no separate facility number, else use default value ^^^^111^1111111> 

Performing Facility Name (OBX-23.1) = “SA.Prescription” 

Performing Facility CLIA (OBX-15.1 and OBX-23.10) = 00Z0000015 

Performing Facility Address (OBX-24) = “12 Fake AtHome Test Street^^Yakutat^AK^99689^^^^02282” 

Allowed test kits with EUA for this purpose: 

Lucira Health, Inc.’s Lucira COVID-19 All-In-One Test Kit – OBX-17.1 =Lucira COVID-19 All-In-One Test Kit_Lucira Health, Inc._EUA (will soon be updated in LIVD to: 00810055970001_DIT) – this will be discontinued – is currently being reported via providers ONLY 

Quidel Corporation’s QuickVue At-Home COVID-19 Test – OBX-17.1 = QuickVue At-Home COVID-19 Test_Quidel Corporation_EUA (will soon be updated in LIVD to: 30014613339373_DIT) 

ANY OTHERS??? 

Example message is for Quidel Corporation’s QuickVue At-Home COVID-19 Test sent by OneAbbott: InterPartner~CentralizedELR~OneAbbott~AIMSPlatform~Test~Test~2021012816241013~STOP~TestMessageSA.Prescription_AL_FINAL 

  

At home testing with prescription and tele proctoring – patient is prescribed the test, obtains the kit, sample collection and test performance is done under observation of the healthcare professional and results are reported via the app. This has verification a) that person tested = patient, b) of how the specimen was collected, c) if the test procedure was followed, d) if the interpretation of the result and subsequent reporting is accurate, e) data about the patient is accurate??? 

Ordering Facility Name (ORC-21.1) = <Copy Ordering Provider Name (ORC-12/OBR-16), if no separate facility> 

Ordering Facility Address (ORC-22) = <Copy Ordering Provider Address (ORC-24), if no separate facility> 

Ordering Facility Phone (ORC-23) = <Copy Callback number (ORC-14/OBR-17), if no separate facility number, else use default value ^^^^111^1111111> 

Performing Facility Name (OBX-23.1) = “SA.TeleProctor” 

Performing Facility CLIA (OBX-15.1 and OBX-23.10) = 00Z0000016 

Performing Facility Address (OBX-24) = “13 Fake AtHome Test Street^^Yakutat^AK^99689^^^^02282” 

Allowed test kits with EUA for this purpose:  

Abbott’s BinaxNOW COVID-19 Ag Card Home Test – OBX-17.1 = 10811877011337_DIT 

ANY OTHERS??? 

Example message is for Abbott’s BinaxNOW COVID-19 Ag Card Home Test sent by OneAbbott: InterPartner~CentralizedELR~OneAbbott~AIMSPlatform~Test~Test~2021012816241013~STOP~TestMessageSA.TeleProctor_AL_FINAL

**Comment by jlusds** [comment]
@Adrian-Brewster to work on FAQ for our different options - 1) OTC in download site, 2) OTC in primary feed. Both cases we can't reformat

**Comment by brick-green-agile6** [comment]
@mauricereeves What do you think about defaulting result status to F for final? I didn't see a result status field in the OTC files from stac so how would we even know if a record was final vs corrected?

**Comment by Adrian-Brewster** [comment]
Have we confirmed with states that once we create these filters, they will want to receive the OTC data in their primary feed?

**Comment by jlusds** [comment]
Per Slack thread, yes we have a few lined up to receive this data

@MauriceReeves-usds what do you think about Brick's comment?

@Adrian-Brewster put together some draft, external messaging for your review: https://cdc-my.sharepoint.com/:w:/g/personal/qpu0_cdc_gov/ETUI9sOjLodCj_uewXj3DpIB2yWcFR8ArzNPXV6uoN7MWA?e=Kq8FdD

**Comment by anshulkumar-usds** [comment]
We need to restart discussion on OTC data. Closing this for now.
