### ISSUE TITLE
suppressHl7Fields does not loop through all OBX iterations

### ISSUE THREAD

**Issue by brick-green-agile6** [CDCgov/prime-reportstream#1847]
## Description
The suppressHL7Fields translation property only suppress values in the fist OBX. All subsequent OBX iterations will be not be effected. This should be fixed so that all OBX iterations are suppressed.

## Acceptance criteria
- [ ] All instances of an HL7 field is suppressed upon request

## Potential Solutions
- add functionality to loop through the OBX segments to suppress each value. This code would be added to the end of the buildMessage function in a similar way to replaceValue
- remove  suppressHL7Fields as a feature and use replaceValue to set HL7 fields to a blank value

**Comment by MauriceReeves-usds** [comment]
@brick-green-agile6 is this completed?

**Comment by brick-green-agile6** [comment]
yes this is complete
