### ISSUE TITLE
NJ Needs Facility Names to Truncate Uniquely

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1866]
Per a recent email from NJ, the facility names that are put into the HD namespace fields need to truncate uniquely. The example they provided is from `Rapid Urgent Care - Slidell` from LA. When that truncates down to 20 characters, it becomes `Rapid Urgent Care - ` which then conflicts with other `Rapid Urgent Care`s that exist.

What they would like to see is the values truncate down in a unique way, though they don't have any specific way they want to see the unique truncation to happen. I have two potential solutions, and I'd like to get some feedback on them.

1. We truncate down to 10 characters from the testing facility name and then append the CLIA to the end. CLIAs are generally supposed to be unique, so this would be a simple way to create a unique namespace, though there are some issues we've encountered with CLIAs coming from SimpleReport.
2. Add a table for facility that will include the full facility name, the facility's CLIA, and some other metadata, and then append on a zero-padded four digit number that gets appended to the first 16 chars of the facility name, for example: `Rapid Urgent Car0001`

The HD namespace fields that are affected are:
```
       val HD_FIELDS_LOCAL = listOf(
            "MSH-4-1", "OBR-3-2", "OBR-2-2", "ORC-3-2", "ORC-2-2", "ORC-4-2",
            "PID-3-4-1", "PID-3-6-1", "SPM-2-1-2", "SPM-2-2-2"
        )
        val HD_FIELDS_UNIVERSAL = listOf(
            "MSH-4-2", "OBR-3-3", "OBR-2-3", "ORC-3-3", "ORC-2-3", "ORC-4-3",
            "PID-3-4-2", "PID-3-6-2", "SPM-2-1-3", "SPM-2-2-3"
        )
```

Below is a sample HL7 PID segment:

```
PID|1||987654321A^^^NapaCo_PHL_LIMS&2.16.840.1.114222.4.1.10412&ISO^PI~45AQ12345^^^Napa General Hosp&2.16.840.1.113883.19.3.2.1&ISO^MR||Everyman^Adam^A^^^^L|Mum^Martha^M^^^^M|19640619|M||^^^W^Wh ite^L^^v unknown|2222 Home Street^^Napa^CA^94558^USA^H^^06055||^PRN^PH^^1^707^2272608|^WPN^PH^^1^707^6374377||^^^M^Married^L^ ^v unknown||||||^^^N^Not Hispanic^L^^v unknown||||||||N|||201102081000- 0700|LastUpdater^2.16.840.1.113883.19.3.1^ISO
```
In the PID segment, the value for PID-3-4-1 is: `NapaCo_PHL_LIMS`

Another example:
```
PID|1|| M10984682^^^EHR&2.16.840.1.113883.99.9.9.9&ISO^MR ^A&2.16.840.1.113883.99.9.9.8&ISO||PUBLIC^JOHN^Q||19610530|M| |2106-3^WHITE^CDCREC|99&MAIN ST&APT 3A^^NORTHSIDE^NH^03999^USA^^^33011| |^^^^^603^5551213|||||||||2186-5^NOT HISPANIC OR LATINO^CDCREC
```
In the PID segment above, the PID-3-4-1 value is: `EHR`

The spec for HL7 2.5.1 says this about PID-3-4-1:

> The assigning authority is a unique name of the system (or organization or agency or department) that creates the data. . Refer to User-defined Table 0363 - Assigning authority for suggested values.

[reference](https://hl7-definition.caristix.com/v2/HL7v2.5.1/Fields/PID.3.4)

FYSA: @Adrian-Brewster @jlusds @brick-green-agile6 @jorg3lopez @jimduff-usds @carlosfelix2 @RickHawesUSDS

**Comment by RickHawesUSDS** [comment]
Interesting bug. It takes some time for me to get into the HL7 headspace. There must be a drug for it. 

If I look at your first example, I see that `PID-3-4` is a Hierarchic Designator (HD) type with a value of `NapaCo_PHL_LIMS&2.16.840.1.114222.4.1.10412&ISO`. I think this value is universally unique because the OID is unique. The same for example two, where the value is `EHR&2.16.840.1.113883.99.9.9.9&ISO`. 

The PID-3-4-1 component is a `Namespace ID` of max 20 characters, so we should truncate it, but that doesn't make the HD unique, rather it is the universal id portion that does. 

What I'm getting at is I don't think we have a problem. Here's the relevant text from the CH2-170. 

> The HD is designed to be used either as a local identifier (with only the <namespace ID> valued) or a publicly-assigned identifier, a UID (<universal ID> and <universal ID type> both valued). Syntactically, the HD is a group of two identifiers: a local identifier defined by the first component and a universal identifier defined by the second and third components. HDs that have defined third components (defined UID types) must have a second component that is unique within the series of IDs defined by that component. 

The text goes on to show valid values for HD that have the first component blank only have the second and third component valid. In other words, as long we have the universal type of HD, we should be with any local component.  

What am I missing about the problem?

**Comment by RickHawesUSDS** [comment]
After our talk, I understand that NJ has misread the HL7 specification and is requiring that component 1 of the HD to be truncated uniquely. My suggested solution is two-fold:
1. For SimpleReport results, use the correct assigning authority. In a SimpleReport result the PID patient-id and SPM specimen-id is a UUID generated by SimpleReport. So, I suggest that we use the PRIME OID `CDCPRIME&2.16.840.1.114222.4.1.237821&ISO` as the assigning authority. 
2. For other CSV senders, we can generalize this approach. This takes some thought which I'll write up in a proposal, but the basic idea that I'm thinking about is making the assigning authority a translation configuration.  

For all HL7 senders, the HL7 message should contain the assigning authority.
