### ISSUE TITLE
Print Confirmation Details for a Selected Submission

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#1871]
## Problem Statement
As a Sender, I need to be able print the confirmation for a specific submission so that I can see what data quality issues exist with my data.

## Design
[[https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=1597%3A4628](url)](url)

## Acceptance Criteria
- Given I
    - Am logged into ReportStream with **Sender permissions**
- When I
   - Log into ReportStream
   - Choose to view my Submission History
   - Select a submission to view the confirmation & warnings
- Then I
   - Can print the confirmation information for a selected submission
       - All confirmation information for the selected submission that is displayed in the UI will also be included in the printed version

## TO DO
- Dev:

**Comment by chris-kuryak** [comment]
Closing by committee. Old issue. CSV Uploader.
@drew-usds @lizzieamanning
