### ISSUE TITLE
Review Options for Tracking State Tasks

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1879]
Let's track the work for reviewing different options for state work here. Will we use SmartSheet? SharePoint? GitHub? Carrier Pigeons? Who can say?

**Comment by jlusds** [comment]
Assigning to @Adrian-Brewster as the owner

**Comment by anshulkumar-usds** [comment]
Check with Kevin and Ming in next steps

**Comment by anshulkumar-usds** [comment]
Heard from @kjt9cc that Click-up was approved for use. Need to check usage.
