### ISSUE TITLE
GitHub actions that deploy and initiate a VPN connection to our cloud environment should use a PING_URL

### ISSUE THREAD

**Issue by td-usds** [CDCgov/prime-reportstream#1886]
See #1868 and specifically this part of it: https://github.com/CDCgov/prime-reportstream/pull/1868#discussion_r690320174
However, this will require some work (and maybe depend on #778) because it needs an HTTP server to ping inside the environment

**Comment by cwinters-usds** [comment]
Recent changes to make this a local action (see https://github.com/CDCgov/prime-reportstream/blob/master/.github/actions/vpn-azure/action.yml#L57) removed the PING_URL. Closing this because the next step using the VPN will fail anyway.
