### ISSUE TITLE
Capture Submission History for Senders

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#1906]
## Problem Statement

As a Sender, when I send result data to my PHD(s), I would like to see a record of my submissions along with any confirmation, error, warning, and delivery messages that were generated as a result of each submission so that I can easily see what I have successfully submitted and understand what I need to fix before I re-submit.

## Acceptance Criteria

- Given I
   - Am a Sender who has access to send lab result data to ReportStream
- When I
   - Have submitted lab result data to ReportStream via any method
- Then 
    - ReportStream captures and stores the following data about each submission

**Comment by RickHawesUSDS** [comment]
The audit trail mechanism does this already.
