### ISSUE TITLE
patient_age appears as negative in covid_result_metadata table

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1911]
imagemover and Cue data (and perhaps others) in production shows the `patient_age` value in the `covid_result_metadata` table as negative.    The data coming from image mover is positive, if you look at its incoming CSV file.     All the other patient_age values in that table look fine; just imagemover is erroneous.

Note:  its a number in the data, but is a text column in the table.
 `patient_age                     | character varying(64)    `
We should probably change its type to number, but that may or may not be the problem here --- its not clear why other data appears to be correct (? maybe its not?) and  imagemover data always has negative patient_age.

This screenshot from Prod shows three Imagemover records:
![image.png](https://images.zenhubusercontent.com/5ff48b04da86ca0cf2bcf625/594a06ab-968c-47e6-88f0-4e739d97011b)

I spot checked 3 patient_age values in the incoming csv file, and they were all normal positive integers (eg, 34, 32, 26)

I also checked a generated .internal.csv file (for hhsprotect) and it also had the correct postitive integer age (32).

So I think this error is isolated to the database column.   FYI @MauriceReeves-usds 

### Acceptance criteria
- able to recreate the problem.     Try creating fake (`./prime data --help`) data in 'cue' or 'imagemover' schema and then replace with junk data in patient_dob field. then run that through local report stream. 
- If you get desperate, ask Jim to grab the CSV.
- fixed the bug.  Maybe line 568 of Report.kt
- As part of the fix, add a test to see if the incoming data has a patient_age value.  If it does, just use it as-is.  If not, then attempt to calculate using patient_dob.
- confirm the fix.

- use the incoming patient_age is used, if it exists and is valid. (Is a number greater than zero)
- If not, then use the patient_dob to calculate patient_age, but only if the patient_dob is valid.  otherwise, leave the patient_age field blank.
- An invalid patient_dob should include incorrectly formatted birth dates, as well as birth dates in the future.
- You can separate this code into a separate function, then be sure to write unit tests against that function.

See line 568 of ReportFile.kt - this may be we need some validation around the values prior to processing.
===================================================================================
Cause:
  ReportStream PatientAge calculation used the Period.between(dob, specimentCollectionDataTime).year.toString().  It gives a negative number if the dob is greater than specimentCollectionDateTime.

The solution to the bug:
  1.) Make sure the dob is before the specimentCollectionDateTime, if not PatientAge is null (Invalid)

Duplicate the problem:
1.) Generate the fake input using the following command line.
     ./prime data --input-fake 2 --input-schema primedatainput/pdi-covid-19 --output ./patientAge.csv
2.) Use MS Excell to modify the value under the Patient_DOB collum to 50500101 (5050-01-01 is the future date).
3.) Run the following command to persist the report to the covid_result_metadata database table.
   curl -X POST -H "client:simple_report"  -H "content-type:text/csv"  --data-binary "@./patientAge.csv"  "http://localhost:7071/api/reports"
4.) Note the report_id ("id") from the response resource. 
5.) In Postgres Data users can query the table using the following:
    SELECT patient_age from covid_result_metadata where report_id= <noted id in step 4 above>
   user will see the patient_age: Negative Number.

Varify the fixed:
1.) Shutdown docker-compose
    docker-compose down
1.) Remove the prime-router_prime_dev container from the docker
     docker container rm <CONTAINER ID>
2.) With the fix prime-router_prime_dev image built
3.)  Start the docker-compose
    docker-compose up.
4.) Go back to above duplicate the problem step 3-5
5.) User should the patient_age is null (NOT NEGATIVE ANY MORE)

**Comment by jimduff-usds** [comment]
Please check first if this PR is related to this problem, or maybe fixed this problem:
https://github.com/CDCgov/prime-reportstream/pull/1988/files

**Comment by jbiskie** [comment]
Query for instances of this issue:

select rf.*, crm.* from covid_result_metadata crm
inner join report_file rf on crm.report_id = rf.report_id
where patient_age::INTEGER < 0
order by rf.created_at
