### ISSUE TITLE
Analysis of tools to support Lineage and Covid Metadata:  PowerBI and SuperSet

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1927]
## Requirements

**Must have:**
1.  Ability to build per-ReportStream-Organization dashboards for External users (senders/receivers) that display a variety of sql queries of data found in our Postgres database.
2.   Senders and Receivers have different needs, so at a mimimum we need a Sender Dashboard and a Receiver Dashboard.
3.  It must be possible to securely stovepipe the data so that a user logged into their Organization's dashboard cannot see or find any other Organization's data or dashboard.
4.  We'll soon be expanding to other disease topics.    I don't know what that means in terms of how these dashboards work, but we don't want to have to switch tool vendors again.
5.  Be able to configure how often the tool does background database queries, or otherwise tune the tool so we can prevent it from overwhelming the database.
6.  SSO Integration with Okta.   For example, I sign into Okta in order to use the ReportStream download site.   I can then use this data dashboard, without having to re-auth.

**Very Nice to have:**

7.   Ability to do everything Metabase does for us internal users. (I'm listing this as 'Nice to have' with the thought that we could, worst case, stay on Metabase for internal stuff)
8.   Plus able to do nicer visuals, and show more than just 50 states in maps.   (These were among the original reasons Mo wanted to move off Metabase)

## Addendum

**Typical views on the Sender dashboard might include:**
- List of recently submitted reports.
- List of recently failed submissions.
- Item submission counts viewed in a few different ways:  per intended receiver, per facility, over time.
- Drilldown to one submission, to see warnings, errors, and details about where it is intended to go to.
- Drilldown to one report to see details about where it actually went.   'Process Receipts'

**Typical views on the Receiver dashboard might include:**

**Comment by ronaldheft-usds** [comment]
@derekkinsman I talked with @jimduff-usds on Friday, and from the DevOps team, @bjohnson-fearless will be available to you to assign in setting up a local version of Superset. Please let us know what you need to evaluate Superset.

@cweagans Interesting thought on Grafana. I'm not sure it's the ideal solution for the problem. While it excels at working with time-based queries, I'm not sure all our reporting requirements are time-based.

**Comment by cweagans** [comment]
@ronaldheft-usds That's the _typical_ use case, but the table plugin that's bundled with grafana itself works great for displaying arbitrary tabular data. Coupled with the postgres data source, you can dump the results of a query straight to the web UI if that's what is needed.
