### ISSUE TITLE
Add zip codes to zip-code-data.csv

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#1939]
Added the rows below to /tables/zip-code-data.csv

22,Louisiana,LA,70765,Iberville,Plaquemine
22,Louisiana,LA,70302,Lafourche,Thibodaux
22,Louisiana,LA,70835,East Baton Rouge,Baton rouge
22,Louisiana,LA,70707,Ascension,Gonzales

**Comment by rhood23699** [comment]
Added the AL & MS zip codes based on Compass Urgent Care testing.

1,Alabama,AL,35046,Chilton,Clanton
1,Alabama,AL,36568,Mobile,Saint Elmo
1,Alabama,AL,36685,Mobile,Mobile
1,Alabama,AL,36688,Mobile,Mobile
1,Alabama,AL,36691,Mobile,Mobile

28,Mississippi,MS,39555,Jackson,Hurley

**Comment by jbiskie** [comment]
## Problem statement

Some valid zip codes in AL, LA, and MS are not present in the zip-code-data table.  As a result, county lookups for those zip codes are failing.

## Acceptance criteria

- [ ] county lookups for the added zip codes are successful

## To do

- [ ] add zip codes to table

**Comment by rhood23699** [comment]
Completed and merged into Production.
