### ISSUE TITLE
Create and teardown receivers on the fly, per smoke test, so we can smoke in parallel

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1942]
Our smoke tests take forever (18 minutes, in Staging, less local but more painful as you wait and wait.

There are a number of things we can do to fix this.  This is one of them.

The big reason why you can't just launch each test in a separate thread, and run in parallel, is that the batching step in ReportStream will grab whatever reports have been created in the last minute, and batch them.  So if you are running tests in parallel, it'll grab data from all kinda different tests, and all-too-cleverly munge them together into a batch, making it look like your tests failed.

So, this story is to work around that:

- For each test that submits data to the api/reports or api/waters endpoint, create a setup and teardown step that creates a uniquely named receiver setting for just that test only, then removes that receiver when the test is completed (regardless of whether the test passed or failed)
- There is an example of how to do this in WatersAuthTests.kt -- see methods setup() and teardown() there.  However, that sets up a sender, and you are supposed to set up receivers, and a bunch of them (details depend on each test)
- Make sure the receiver names are useful and human readable, but won't clash with each other.  eg, "END2END_HL7_BATCH".
- Note the kluge that the _county_ names in the test MUST match the receiver names.
- I think its ok to assume only one suite of smoke tests is running at a time.  (That is, you don't need to attach a UUID or a timestamp to the receiver name)
- In Staging, you'll need to be authenticated to access.

**Comment by carlosfelix2** [comment]
OBE
