### ISSUE TITLE
Stop calling a missing transport an error

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1973]
In the `action` table, if we don't send data to a particular state, we call that a `send_error `right now.

Its probably not an error - we have set up receivers for all 56 states, even though only about 20 or so are actually 'live' with us.   In fact, some states are live with us, but get their data via the download website, in which case we also may not have a transport set up for them- again, not an error.

Here's what the message looks like in the action table right now:
```
action_name: send_error
action_result: Not sending f1c1de41-5873-4b50-8768-ceb5ea557a61 to ny-phd.elr: No transports defined
```

### This ticket is DONE when:

- there is a new action_name, 'send_info", available in postgres
- The `No transports defined `action uses send_info instead of send_error.
- sftp and redox Retries (which say " Will retry sending report...") use send_info instead of send_error. 
- However, its very important that the final failure (which says "All retries failed") is a send_error.
- All other send_error cases have not changed - they are still using send_error.
- (Bonus points if you think of a better name than `send_info`)

No need to change the action_result message.

Note:  this is a database sql change, which is done via Flyway.  Check out earlier .sql updates to this field - its annoying - you have to change the type of the column (its used in two tables), then change the enum type, then change the type of the column back.  Be careful.

After your change is deployed to Staging, please submit some data that causes it to occur, and doublecheck the Metabae "Last 7 days" dashboard in Staging- there may be queries that need to be modified to know about this new action name.

**Comment by anshulkumar-usds** [comment]
@jimduff-usds this is assigned to current sprint but no assignee. Is anyone working on this?
