### ISSUE TITLE
Track whether a state is "live" and activated with ReportStream, in the Settings table

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1974]
Whether a state is active/live with ReportStream is somewhat independent of whether they have a fully set up transport in the Settings table.   A state might be "live", but using the download site, so with no transport.   Or a state might not yet be live, but have working transports ready to go. 

This makes it hard to flag what's an error and what's not an error, in our metabase dashboards.   If we had solid/correct values for which states are supposed to be getting data, then we could much more easily flag errors, maybe even with PagerDuty.

Also, we could generate the map directly and automatically from database data.

So, this ticket is to
- add a new field,   `is_customer_activated`, to both `Sender.kt `and `Receiver.kt`, fed by data in the settings table.   Values are true or false.
- Note that a particular organization might have one receiver activated, and another one not.
- if you have a better name, let me know.   I added the word 'customer' to show that this is not a _technical_ status of our data feed, but more a human/legal status.
- default is false, not activated.
- you must backfill this value in organizations.yml!
- you must also backfill it for all receivers and senders in Staging and Production   The values for what's activated or not may differ between Staging and Production.   Mo has written code that does these sweeping backfills of json structured data.  See `src/main/resources/db/migration/V10__Update_settings_for_name_templates.sql`
- Be careful with flyway.  Once you deploy, unless you've written a rollback .sql, it'll be hard to go back if its messed up - you may have to remove the table in your database and start over.
- when we roll this to Prod, we should be sure to pull down the full set of settings prior to deployment, in case we mess up the data.
- note also that the act of "going live" will no longer just be an announcement in Slack - it'll have to be accompanied with a settings change.   The need for a proper settings UI increases daily.

@MauriceReeves-usds , @jlusds, @anshulkumar-usds  FYI.

**Comment by jimduff-usds** [comment]
Based on @clediggins-usds suggestion, we can make this an `activationStatus` enumeration rather than boolean.

I'm also wondering if it should be a database column rather than in the json.  That would make it much more accessible to simple queries.

Note that our design is that each Organization can have zero or more Senders and zero or more Receivers.   Currently (and somewhat confusingly, since there's also a parent-child relationship) each gets its own separate row in the Settings table.

So now the proposal here is that every Organization, Sender and Receiver gets an activationStatus, as a new column in the Settings table.

As as follow-on story/ticket, we can add features to our settings family of CLI commands (`./prime sender, ./prime receiver, ./prime organization, ./prime multiple-settings`) to do CRUD on this status.

Initial activationStatus enum values could be simply 
- 'inactive'
- `training` or maybe `testing`
- `active`

There is a significant downside to having Organizations with activationStatus:  its confusing.  What would it mean if an Receiver is 'active' but the parent Organzation is 'inactive'.  Heh?  So I'm not sure about that.

Note that we don't need to track a transport-status, because we can easily tell if they have a transport by looking at the transport portion of the Setting.

**Comment by clediggins-usds** [comment]
Chatted with @jimduff-usds. Implementation plan:
* Add customer_status to Sender and Receiver
* Valid values are [inactive, testing, active], default is 'inactive'
* Backfill existing sender and receiver records to indicate status
* There will be no changes to Organization, just Sender and Receiver

**Comment by clediggins-usds** [comment]
List of current states and statuses: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/jurisdiction-connection-status.md

Additional notes:
Senders: Currently all the senders in Production are in active mode.
Receiver States:  You saw the states list I sent.   For the 50 states, if they are listed as Live they are ‘active’, if they are listed as In Development they are ‘testing’, and if they are not listed at all, they are ‘inactive’.
the only territory that’s active is Guam.  All other territories are ‘inactive’.
Receiver Counties:  all counties in RS Production are active.
All Federal receivers are active.  (There should only be one - hhsprotect)
