### ISSUE TITLE
System Cleans Sender Data on Submission

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#1975]
## Problem Statement
As a Sender, the results I send to ReportStream may contain any or all of the following, which will result in the data being rejected by ReportStream, so I need for my data to be cleaned for me so that I don't have to acquire the knowledge/resources necessary to do it myself:
    - Blank rows
    - Invalid values and/or formats
    - Missing fields required by my PHD
    - Results for unsupported tests

## Background Notes
The onboarding team has indicated that 
- Every small sender they attempt to onboard has data that will cause the entire submission to be rejected by ReportStream because of missing data and/or incorrect formats
- Small senders lack the expertise to modify their data to be accepted by ReportStream and that, if they were to hand modify the data it would cause more serious issues

## Solution Notes
Please refer to the decisions made during this meeting on the preferred solution
https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?sortField=Modified&isAscending=true&id=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FTeam%20Documents%2FExperience%20Team%2FMeetings%2F09162021%2DDataCleansingOptionsMeeting%2Epdf&parent=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FTeam%20Documents%2FExperience%20Team%2FMeetings

**Comment by rachelhanster** [comment]
Closing initiative as this no longer applies to API senders
