### ISSUE TITLE
Clean CSV Data:  Replace Generic Test Kit Name ID with Facility-Specific Value

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#1976]
**MULTI-COLUMN LOOKUP (CARLOS)**

## Problem Statement
As an **Experity EMR platform user**, my data may not contain test order names, LOINC Code, or Specimen Type codes that are sufficiently specific to identify the exact test. LOINC code and Specimen Type code that is being performed and I need this data populated for me based on my default values so that I can report accurate data to my PHD.

## Examples
As an example, when a user orders a rapid test in Experity, they will select a test order name of "Coronavirus Antigen IA Rapid Test." It is assumed that Experity implemented generic test order names in order to allow practices to use new tests quickly as they come on to the market. With ~5,700 Experity facilities using a variety of tests coming to the market, Experity may not have had the resources to add new tests to the orderable test list at the pace required by facilities, so default test names were implemented. 

The facilities may document the specific test names in free text fields, but those aren't standardized enough to use for Electronic lab reporting. This creates a dynamic where the sender must define the specific test type that corresponds to a generic test order name such as "Coronavirus Antigen IA Rapid Test." 

In one client's case, the user selects "Coronavirus Antigen IA Rapid Test" when they want to order the “CareStart COVID-19 Antigen test”. Because the EMR data does not describe the test being performed with sufficient specificity, we must map the generic test names to the specific tests being performed. This mapping may occur at the facility (CLIA) level, where an organization has multiple facilities who use Coronavirus Antigen IA Rapid Test to order specific test types. In order to accommodate this, as a short term workaround the sender automation team has mapped the senders' generic ordered test names to specific test_kit_name_ID's in a VBScript that runs on the client side before it is sent to ReportStream. 

In another client's case, the user selects "RightSign COVID-19 IgG/IgM Rapid Test Cassette" when they want to order the "RightSign COVID-19 IgG/IgM Rapid Test Cassette_Hangzhou Biotest Biotech Co., Ltd.".  This test will produce two results.  One for IgG and another IgM.  The test ordered "RightSign COVID-19 IgG/IgM Rapid Test Cassette" and test performed "SARS-COV-2 IgG antibodies" combined provides enough information to be mapped to the appropriate ReportStream test_kit_name_id and test_performed_code.

In all the cases listed above, the user's system defaults Specimen Type to an unusable value of "Varied" and no Specimen Type Source Site is provided.  For each case, the specimen_type and specimen_type_source_site can be defaulted to values provided by the Sender that are appropriate for the test performed.

## Acceptance Criteria
- Given I
    - Am logged into ReportStream as a user with Sender permissions
    - Am a Sender who is using the Experity schema
- When I
    - Log into ReportStream
    - Upload a CSV file
- Then 
    - The System, prior to submitting the file to ReportStream for processing, checks 1 or more test kit fields and, based on the field value(s), populates 1 or more test kit field(s) with mapped value(s) specific to the Sender     
        - Using the database lookup tables feature, the sender_id and test ordered/performed description is passed into the table lookup mapper and the value identified by the tableColumn element will be returned.  tableColumn elements are:
            - Test Performed - This will be either the test_kit_name_id (column M) or equipment_model_name (column B) from LIVD spreadsheet.
            - Test Performed Code - This will be the LOINC code for the test_performed_code.
            - Specimen Type - This will be the SNOMED code for the specimen_type.
            - Specimen Type Source Site - This will be the SNOMED code for the specimen_type_source_site.
        - If no lookup value is found in the lookup data then the field is made blank.
        - If the value for ordered test name is blank then the field is left blank.

## Design Considerations 
Note that there is currently no order as to how the mappers run, so the LIVD lookup may not work correctly. However, it is possible the LIVD lookup will run on the receiver side and still work.
This will also require implementation of the database lookup tables.

**Comment by carlosfelix2** [comment]
Design consideration:  Note that there is currently no order as to how the mappers run, so the LIVD lookup may not work correctly.  However, it is possible the LIVD lookup will run on the receiver side and still work.
Suggestion for acceptance criteria:
1. ReportsStream is capable of setting the test kit name ID field using the provided ordered test name looked up from provided lookup data using the ordered test name, sender name (client name) and facility name.
2. If no lookup value is found in the lookup data then the field is made blank.
3. If the value for ordered test name is blank then the field is left blank.

**Comment by kevinhaube** [comment]
@loripusey Would you be able to point me in the direction of that VBscript? The link provided broke when we rearranged ZenHub boards I think

**Comment by loripusey** [comment]
https://cdc.sharepoint.com/:u:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Sender%20Automation%20Team/vbScript%20for%20Data%20Cleansing%20Epic/PRIME-Sender-CUC-v2%20(2).vbs?csf=1&web=1&e=zzHyNc

**Comment by kevinhaube** [comment]
Per discussion with Rick Hood, the requirements of this ticket may be changing, so I'm moving this ticket to our Product Backlog for now.

**Comment by loripusey** [comment]
@rhood23699 Can you please set a meeting to discuss the AC for this?

**Comment by rhood23699** [comment]
@kevinhaube @ahay-agile6 @sean-usds @sethdarragile6 @carlosfelix2 

In an attempt to keep us moving, I've put together my brain-dump on the Table and Mapper functionality needed for the Ticket.  The link is https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Sender%20Automation%20Team/Sender%20Tools/TestPerformedMapper.docx?d=w6612ee4dd57840b68e0cbf5613f0bebd&csf=1&web=1&e=fY1C6u

Note, this is very rough and I'll update the AC based on our meeting.  I'll send an email to everyone ask for times.

**Comment by rhood23699** [comment]
Based on our meeting yesterday with Carlos, Aurora and Kevin, I've updated the Examples and Accept Criteria.

**Comment by loripusey** [comment]
Thanks @rhood23699, we will re-refine this at our next refinement based on the new AC.
cc: @sean-usds @ahay-agile6

**Comment by rhood23699** [comment]
Note, @kevinhaube and I are moving forward based on our meeting yesterday.
cc: @sean-usds @ahay-agile6
