### ISSUE TITLE
Centralized CLIA for out of State Submitters

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1981]

**Comment by brick-green-agile6** [comment]
Coding complete in master. Need to push settings to production to change the translation property: 

Current in Production: cliaForOutOfStateTesting: null
Current in Master: cliaForOutOfStateTesting: CDPH000075

**Comment by Adrian-Brewster** [comment]
Some messages do not have any MSH-4 segment populated with CLIA at all.  Appears to be out of state. 

Will this be resolved with the push to prod?
