### ISSUE TITLE
Send an email to the states about our Palo Alto Firewall switch

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#2005]
We need to communicate to the states that we are moving to a new outbound firewall and they will need to open up a new IP range in order to continue to receive messages from us.  Our new range will be 158.111.236.0/24

We will be switching to the new IP range by 09/30/2021.

We should send the email by tomorrow.  Would that work?

**Comment by Adrian-Brewster** [comment]
Can you mark this complete? For some reason it won’t let me.

Thanks!
