### ISSUE TITLE
Refactor GitHub Actions to share code

### ISSUE THREAD

**Issue by ronaldheft-usds** [CDCgov/prime-reportstream#2011]
GitHub Actions released the ability to re-use YAML in actions with a feature called composition: https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/

Our release action could greatly benefit from this, as each environment copies and pastes the exact same code. We may be able to share GitHub Action code among other actions as well.

**Comment by TomNUSDS** [comment]
Another resource: https://docs.github.com/en/actions/learn-github-actions/reusing-workflows

**Comment by ronaldheft-usds** [comment]
@bjohnson-fearless When you have findings regarding this, please post them here so we can discuss as a group. Thanks!
