### ISSUE TITLE
LHS: Develop the 'superset' of desired fields by states for Full ELR

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#2018]
This task is DONE when we have a schema that defines the intersection of what all our known states desire for full ELR.

**Comment by jimduff-usds** [comment]
This is probably redundant with #1998

**Comment by clediggins-usds** [comment]
After conversing with HCA it seems we have the superset of data we are looking for. All of HCA's facilities send whatever data they have available.
