### ISSUE TITLE
Detect Entire submission duplicates

### ISSUE THREAD

**Issue by oifekoya** [CDCgov/prime-reportstream#2030]
If the same / repeated dataset (eg, hashes to the same digest) comes in from the same sender, reject it with a nice error message.

Documentation:
Current hash is in the REPORT_FILE table.

## Acceptance Criteria

[ ] Add an allowDuplicates=true/false sender setting parameter.   Default is to allowDuplicates=true, in which case the system works as now.
[ ] Add a allowDuplicates URL query parameter.   If used in the URL, its value always overrides the sender Setting.  
[ ] If allowDuplicates is false, then fail if this submission's digest matches one already in report_file for this sender.
[ ] That is, the submission should fail in the `receive` step **if there's already an entry in report_file associated with this sender.**
[ ] This check should occur in the ReportFunction, after auth, after basic "global" checks, but prior to parsing and validating the data.   
[ ]  Decide: blob_digest is stored as type `bytea` in postgres.   Do we need to store it as a regular hex string and change this to a text type?  (digests are currently calculated in BlobAccess.kt)
[ ] Create an index on the blob_digest column -- be sure to do this in a concurrent way that doesn't hose the system.

**Comment by cweagans** [comment]
Ref: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/azure/ActionHistory.kt#L254
