### ISSUE TITLE
Notify Sender when CSV File too Large to Process

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2040]
## Problem statement
As a Sender who uploads a CSV file, I want to know if my file size exceeds the maximum size that ReportStream allows so that I will know to break the file up into smaller files.

## What you need to know
- Here is what ReportStream limits are with a CSV file
    - 50mb is the file size limit
    - 10k is the row limit
    - 2000 is the column limit
- We should test for the 50mb limit but allow RS to check the row & column limit

## Acceptance criteria
- Given I
    - Am logged into ReportStream as a user with Sender permissions
- When I
    - Navigate to the new Sender submission page
    - Choose a file to upload (i.e. browse or drag/drop) 
    - Upload a CSV file that exceeds the 50mb limit        
- Then I
   - See a message that tells me I have exceeded the file size limit
       - NOTE **we should test if there is a lower limit than this; check for timeouts**

## To do
- [ ] Dev:

**Comment by kjt9cc** [comment]
do we know the current behavior of what happens when a user tries to upload a file larger than 10K rows?

**Comment by loripusey** [comment]
> do we know the current behavior of what happens when a user tries to upload a file larger than 10K rows?

According to @jimduff-usds , ReportStream will not process it; I'm assuming RS will return an error; I plan to test in staging once staging is fixed

**Comment by loripusey** [comment]
@BerniXiongA6 @inkandsound What should this message say for the over the file limit error message?
