### ISSUE TITLE
Polish up the spinners on the React site

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#2044]
Currently when authenticating a user on the Daily Data page, the React site flashes the login UI, covers it with a gray background and large spinner, and then presents the Daily Data page.

I propose we iron out this sequence to do the following:
- Eliminate the flash of the login screen as this may briefly concern users they've been logged out
- Work with design to create an authentication spinner UI that will be resent any time a user is navigating to an authenticated page
- Implement these designs in a way that does not make the users feel as though they're being redirected around the UI prior to page load

================================

Currently, the spinner populates the whole page while loading the Daily Data page. I propose we mimic the spinner location from the production site but use our new React-based spinner instead of the icon spinner.

**Comment by kevinhaube** [comment]
@drew-usds Is this something that already exists in design?

**Comment by drew-usds** [comment]
Hey sorry didn't see this @ sooner. The current spinner in production (that uses FontAwesome) is totally a placeholder and needs to be improved. Looking at what's on React here ... is that a default thing? Are there other existing loader/spinner components we could use or adapt?

I have a general issue open for this as well: #1743

**Comment by kevinhaube** [comment]
@drew-usds Hey! No worries. I actually started looking into how that current spinner was working, and tweaked it a bit. I haven't gotten that odd login UI flashing first again (yet, but my eyes are peeled), so once https://github.com/CDCgov/prime-reportstream/pull/2108 is merged, feel free to take a look at the React site again and see how that spinner looks. The library currently used is `spinners-react`.
