### ISSUE TITLE
Allow senders to provide fake test equipment values while testing their submissions

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#2054]
(Note:  Originally this ticket covered 2 features, but it has been split.  The other work is now in #3525)

As a test/early sender to ReportStream that doesn't have my official EUA yet, I want to be able to send data to ReportStream that has a acceptable dummy/fake value for equipment_model_name and/or device_id and/or test_kit_name_id.

The problem: Many of our senders do not yet have their EUA (Emergency Use agreement) from the FDA, and so are not listed in the LIVD table.

# Acceptance criteria

ReportStream will allow the sender to match one of a small number of "Fake" allowed values, for cases where a sender does not yet have their EUA:_

- `Test_OTC_Device`. (with the is_otc flag set to true in the LIVD-Supplemental table)
- `Test_Home_Device` (with the is_home flag set to true in the LIVD-Supplemental table)
- `Test_Unproctored_Device` (with the is_unproctored flag set to true in the LIVD-Supplemental table)
- `Test_POC_Device` (not listed in the LIVD-Supplemental table)

Add a check in the default covid-19 processingModeFilter to prevent these fake devices from feeding to states, since data with a fake device is tautologically test data.  This is exactly what that filter is for.

To keep things simple, **we'll allow any of those to be a valid value for test_kit_name_id, device_id, or equipment_model_name**.   Why not just have a single fake value?  Because we need it for #2056.

### Design Considerations
- Implement this in the mapper?

**Comment by oifekoya** [comment]
@jimduff-usds to update ticket

**Comment by Adrian-Brewster** [comment]
@MikeC-A6
