### ISSUE TITLE
Staging environment for React transition

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#2060]
**Is your feature request related to a problem? Please describe.**
As we finalize the migration to React, it would be helpful to have a staging environment that we can user test from without mucking up the regular deployment schedule.

**Describe the solution you'd like**
- Keep our current 11ty production build at `staging.reportstream.cdc.gov`
- Point the current React build to a new URL ... liiiike `staging.reportstream.cdc.gov/react` ? ... whatever that path is that makes sense to y'all (assuming I understood that from the chat earlier).

**Describe alternatives you've considered**
- Setting up entirely different environments
- Using feature flags

**Additional context**
- Met with Ron & Mo to talk through this on 9/1
- This'll probably be a temporary fix while we sort out what additional environments we'd need to set up for the whole project

**Comment by ronaldheft-usds** [comment]
@drew-usds Is this ticket as written still valid? i.e. I don't think we're going to maintain the old site once we roll out the React site. Therefore, should we close this and create a separate ticket to track having a user-experience environment.

**Comment by drew-usds** [comment]
@ronaldheft-usds Thanks for flagging, yep we can def close this one!
