### ISSUE TITLE
History API: Expose History Data to Senders/Receivers

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2072]
GOAL of this Epic: Expose Database Data:  ReportStream provides an API with all kinds of wonderful data available to our sender/receiver/admin customers:  Data Custody info, Process Receipts, Lineage History, and Metadata, and Submission error/warning history.

**Comment by jimduff-usds** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/2072?planning-poker) with ZenHub @clediggins-usds @carlosfelix2 @jh765 @JGreenFearless @whytheplatypus
