### ISSUE TITLE
Onboarding Colorado

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#2077]
This is a ticket to track the work being done to onboard Colorado. Keep any notes and info here and then close it out when they go to production.

**Comment by brick-green-agile6** [comment]
Transferred first synthetic file to the CO test server

**Comment by brick-green-agile6** [comment]
Sent new file with synthesized data.

**Comment by brick-green-agile6** [comment]
Set report stream production to send to CO staging

**Comment by brick-green-agile6** [comment]
sftp was failing in RS so CO was not receiving the files. It has been fixed. So I will manually transfer a file then the automated transfers will start in AM of 10/14

**Comment by brick-green-agile6** [comment]
Set default reporting facility name to CDC PRIME and reporting facility ID as 11D2030855 in production
