### ISSUE TITLE
Create PHINMS transport to connect to STLTs

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#2082]
Creating this epic to track all issues around standing up PHINMS in a virtual environment.

After our discussion with the PHINMS team, we can start adding tasks here.

Tasks:
1. Stand up PHINMS in a Virtual Environment

**Comment by brandonnava** [comment]
@MauriceReeves-usds @brick-green Since we're not messing with PHINMS should I close this epic? Or is MN blocked from using RS without it? On the map it looks like MN is onboarded.

**Comment by MauriceReeves-usds** [comment]
@brandonnava please leave this open for now.

**Comment by LaFreda1** [comment]
Closing due to the transport isn't needed anymore
