### ISSUE TITLE
Validate CSV File on Submission and Fail Submission if there are Quality Filter Messages

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2091]
## Problem statement
As a Sender, when I submit a CSV file, I would like for my data to be validated and, if errors exist in my data that prevent my data from being delivered to PHDs, I would like the opportunity to fix the data and then re-submit.

## Acceptance criteria
- Given I
    - Logged into ReportStream as a user with Sender permissions
- When I
    - Navigate to the new Upload page
    - Choose a file to upload (i.e. browse or drag/drop) that contains certain quality filter messages
    - Submit the file
- Then 
   - System validates the file using the ReportStream API
   - If the file has **NO** error messages and **NO** quality filter messages 
       - System **SUBMITS** the file for the Sender
   - If the file has **ANY** error messages or **ANY** quality filter messages 
       - System **DOES NOT** submit the file
NOTE: jurisdictional, routing, and process mode filters are **IGNORED**, we are only acting on the presence or absence of quality filters
NOTE: there is a separate ticket to display the quality filter messages as errors

## Questions to Answer
- Waters endpoint vs. reports endpoint?
- Validation check w/o holding the data options? Validate payload vs. Skip send - **SkipSend** is the option we want to use. It sends the data through "gaunlet". ValidatePayload only validates the request.
- Do the errors get logged on validate or not? In case we want to show them in submission history

## To do
- [ ] Dev:

**Comment by sethdarragile6** [comment]
@HeatherRienks  it was decided that this story and [#2091](https://github.com/CDCgov/prime-reportstream/issues/2091) were to be pulled out when it became apparent that there was no clean way to submit and then reject a file with quality filter messages without leaving a trace of the report within the system- which could lead to confusing artifacts in the UI, as well as the accidental transmission of said report. After discussing the situation with Jim and Brian, Jim created [a new story](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5058) on the pipeline backlog to address this lack of clean validation, with the ultimate goal to create a "validation service" that would be more useful to hand off to the SimpleReport team when CSV Upload is transitioned over to them.

**Comment by bgantick** [comment]
Closing per https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3557#issuecomment-1091729391
