### ISSUE TITLE
Bug: Staging keys deleted for registered accounts or changed values

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2101]
We are noticing that keys created in the staging function are either getting deleted, or seem to have been changed from what was previously shared with the key recipient. Here are two examples:

1. We created a staging key for sender 'Primary Health' a few weeks ago, and noticed on 9/3/21 that the key was no longer available. This caused the client a 401 error when attempting to submit data to ReportStream

2. Several keys in staging are no longer the same as when they were originally generated

Please investigate root cause and inform sender pipeline team when resolved.

cc: @anshulkumar-usds @jimduff-usds @jbiskie

**Comment by ronaldheft-usds** [comment]
This is an ongoing issue. It appears after some type of deployment, or on some interval, the function app loses all function keys.

If we plan to continue to use function keys for the long term, we should figure out what's happening here.
