### ISSUE TITLE
Change Wording for Sender Submission Alert for Warnings

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2124]
## Problem Statement
We don't want Senders to alter and re-submit CSV files that have been accepted by ReportStream because this will cause duplicate results to be forwarded to PHDs.  We need to change the wording of the alert message and the Submit button in the scenario where the file is accepted but there are warning messages.

## Acceptance Criteria
- Given I
    - Am logged into ReportStream as a user with Sender permissions
- When I
    - Navigate to the new Sender submission page
    - Choose a file to upload (i.e. browse or drag/drop) 
    - Upload the file (system submits it to ReportStream
    - System returns both a Success message and an Alert message
- Then I
   - See the alert message header says "Alert: Unusable Fields Detected"
   - See the alert message body says "Your file has been accepted with warnings. There were fields detected that are unusable for public health action. Enter valid information for future submissions."
   - See the submit button says "Upload another file"

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/801c2e87-e6ff-4983-b22d-bd936a84aeb8)

**Comment by loripusey** [comment]
@kjt9cc @ahay-agile6 I created this story in response to the meeting we had with Jim where he indicated that Senders should not be editing and re-submitting their files.  I think in light of that, we need to change the wording in this scenario.  Please take a look and let me know if you agree that this is needed.  I will reach out to Berni for better wording but wanted to make sure we need this before I do.

**Comment by loripusey** [comment]
@BerniXiongA6 Can you recommend some wording for this message given the fact that we want to discourage the Sender from fixing and re-submitting their data when the file has been accepted.

**Comment by BerniXiongA6** [comment]
@loripusey Happy to help... so is it accurate to say we want A) the sender to do nothing/leave alone this accepted file that had warnings and B) to also upload a new file (not re-submit/fix the current file) that addresses these warning issues? I want to be sure we are being explicit about what we're asking them to do/not do. We can chat if needed.

**Comment by loripusey** [comment]
@BerniXiongA6 I think definitely A; ideally B but we also acknowledge that they probably are not going to manipulate their files and according to Mike C, if they manipulate files it will lead to a lot of issues/errors; I think encouraging them to fix the data quality issues with future uploads would probably be the safest bet

**Comment by BerniXiongA6** [comment]
@loripusey I wrote 2 suggested edits for the alert message. They're both wordier than I'd like, but if we want to accomplish A) informing them the file was accepted but with warnings, and B) to address the issues in future submissions, then either of the enclosed could accomplish this. Lmk if you need a further assist!

[Suggested Edits for Issue 2124.xlsx](https://github.com/CDCgov/prime-reportstream/files/7145965/Suggested.Edits.for.Issue.2124.xlsx)

**Comment by loripusey** [comment]
Thanks @BerniXiongA6 ! I will change the wording in the user story.
