### ISSUE TITLE
[BUG] React Frontend: `.env.staging` file isn't being used by `staging.reportstream.cdc.gov`

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#2133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`frontend-react/public/index.html` contains environment variable `%REACT_APP_BACKEND_URL%` used to switch which backend api the site has permissions to reach.

These variables should be loading from `frontend-react/.env.staging` for staging and `frontend-react/.env.production` for production.

But it seems like the `%REACT_APP_BACKEND_URL%` value is being pulled from `.env.production` even for staging.

Once this is fixed the hardcoded `https://staging.reportstream.cdc.gov/api/` and `https://staging.prime.cdc.gov/api/` lines can be removed.

### Steps To Reproduce

1. Be on staging and load the default page.
2. View the `<meta http-equiv="Content-Security-Policy"...` tag in the debugger.
3. Check the value of last element `%REACT_APP_BACKEND_URL%` 
Result: It is the value from the `.env.production` NOT `.env.staging` file: `REACT_APP_BACKEND_URL=REACT_APP_BACKEND_URL=https://prime.cdc.gov/api/`

### Expected Behavior

It should be value from the `.env.staging` file: `REACT_APP_BACKEND_URL=https://staging.prime.cdc.gov/api/`

### Additional context

See: https://create-react-app.dev/docs/adding-custom-environment-variables/

html code that contains env variable and hard coded values
```html
    <meta
      http-equiv="Content-Security-Policy"
      content="default-src 'self';
        script-src 'self'
          https://hss-prime-okta.com
          https://global.oktacdn.com
          https://www.google-analytics.com
          https://*.in.applicationinsights.azure.com;
        style-src 'self' 'unsafe-inline'
          https://global.oktacdn.com
          https://cdnjs.cloudflare.com;
        frame-src 'self' https://hhs-prime.okta.com;
        img-src 'self' https://hhs-prime.okta.com https://reportstream.cdc.gov data: ;
        connect-src 'self'
          https://www.google-analytics.com
          https://*.in.applicationinsights.azure.com
          https://hhs-prime.okta.com
          https://staging.reportstream.cdc.gov/api/
          https://staging.prime.cdc.gov/api/
          %REACT_APP_BACKEND_URL%
          ;"
    />
```

### Does this issue have a priority label?

- [ ] Added a priority label

### Has issue been assigned to a team?

- [ ] Added a team label

**Comment by TomNUSDS** [comment]
This is more complicated than first expected. There is NO SERVER to host the env, so the react has to load it... but the `name=value` format of env isn't directly loadable and there's an order precedence. 

There is a `dotenv` component; however, it depends on direct file reading (which is a node thing).

Possible solutions:
 1. As part of _build_, run dotenv for the proper environment ('prod' vs 'dev' vs 'test'), then write out a single .env.json that can be loaded easily by react on startup. (Issues, could env mistakenly be leaked by future developers who don't understand how the process works.)
 2. Just stop using .env and switch to .env.json directly. It's less standard, but it's much more obvious.
 3. Write our own dotenv-like loading doesn't require direct file access (more complex, possibly buggy).
 4. Some hybrid approach of using dotenv but passing in data we've loaded? Unknown

**Comment by sean-usds** [comment]
1. sounds like the the best plan to me so long as we document in the Readme to help avoid any future issues. 

do we need all the env files we presently have? just checked at we have the following:

.env
.env.local
.env.development
.env.test
.env.staging
.env.production

**Comment by TomNUSDS** [comment]
`test` and `staging` ar the same for us. `.env.local` should never be in github and ONLY on local dev machines.

The order of operation is for us is:
 a. prod:  `.env` -> `.env.production`
 b. dev:  `.env` -> `.env.development` -> `.env.local`
 c. staging: `.env` -> `.env.development`
 
 For some setups (where there's a server) `.env.local` could be generated for prod and staging.
 
 We can/should simplify to maybe just 3x and duplicated the values out of the "root" `.env`

**Comment by TomNUSDS** [comment]
Initial approach of using json data and loading dynamically did not work. The build itself needs access to the configuration data (for things like the index.html template's `<title>%REACT_APP_TITLE%</title>`).

The best solution seems to be having separate builds for each of the targets since having any kind of variables in the package.json is tricky.

`env-cmd` seems to be the standard way to switch the env file.

So, it would be something like this:
```json
  "build:staging": "REACT_APP_ENV=staging INLINE_RUNTIME_CHUNK=false env-cmd -f .env.staging craco build",
  "build:test": "REACT_APP_ENV=test INLINE_RUNTIME_CHUNK=false env-cmd -f .env.test craco build",
  "build:release": "REACT_APP_ENV=release INLINE_RUNTIME_CHUNK=false env-cmd -f .env.release craco build",
```
Although the default is release so it could also be the `release` is simplified to this:
```json
  "build:staging": "REACT_APP_ENV=staging INLINE_RUNTIME_CHUNK=false env-cmd -f .env.staging craco build",
  "build:test": "REACT_APP_ENV=test INLINE_RUNTIME_CHUNK=false env-cmd -f .env.test craco build",
  
  "build": "INLINE_RUNTIME_CHUNK=false craco build",
```

The next challenge is getting the github action to conditionally use different builds (from `.github/workflows/build_frontend.yaml`):
```yaml
  build_frontend_react:
    name: Build Frontend React
    needs: pre_job
    if: ${{ needs.pre_job.outputs.has_react_change == 'true' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend-react

    steps:
      - name: "Check out changes"
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }} with yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn run build
```

The last run step would need to be conditional.
e.g. for staging:
```yaml
      - run: yarn run build:staging
```

@sean-usds @cwinters-usds I'm not super proficient at complex github actions (yet) and could use some help doing it the right way.

**Comment by sean-usds** [comment]
another option (if it's possible) is to store the staging build in a different directory like `.../frontend-react/build-staging/` and in the `deploy_release_staging` step in `release.yml` have it take the build from the new path

**Comment by TomNUSDS** [comment]
Points are zero for this ticket because the PR #3282 is basically a duplicate of this one.

How are we handling duplicates?

**Comment by sean-usds** [comment]
it's ok for there to be an Issue and a PR. we just point the issues

**Comment by TomNUSDS** [comment]
Done. Closing.
