### ISSUE TITLE
NC - Wants to receive aggregated OTC data 

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#2158]
Let's touch base with NC and figure out what the requirements are for this, and how they want us to aggregate the data for OTC.

**Comment by anshulkumar-usds** [comment]
Follow up with NC and Ming to understand what the specific needs from NC are.

**Comment by anshulkumar-usds** [comment]
Check with Karla to see where we are with onboarding. Will follow up with specific on OTC after hearing back.

**Comment by Adrian-Brewster** [comment]
Anshul  - we had a kick off call with NC to gather requirements several
months ago. I just took a look and can’t find my original notes, but it’s
been long enough that we may want to just set up another call with Walter
and Remmy. Let me know if you want me to set that up.

Adrian

**Comment by anshulkumar-usds** [comment]
Blocked: No response from NC
