### ISSUE TITLE
Batching Enhancement - Enable batching by sending facility

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#2164]
We have two additional capabilities we need to add to the batching in ReportStream:

1. NC wants to batch files by the sending facility, similar to how we batched WA records by negative and positive.

fysa: @jimduff-usds @RickHawesUSDS @Adrian-Brewster

**Comment by BerniXiongA6** [comment]
Let's flesh out this ticket more, some questions we can ask ourselves to add more detail:

- Who all wants this? (the more states that want it, the greater the potential priority)
- Is this feature blocking any potential states from onboarding with us?
- What do they want if we offer this feature?

cc: @sarahnw @MauriceReeves-usds @brick-green

**Comment by oslynn** [comment]
2022-09-29.  Mike Fisher (NJ) is asking me to have this feature when we send messages to NJ.

**Comment by brandonnava** [comment]
@oslynn is this feature still needed and if so is it O&O work or something to bring up with platform or pipeline?

**Comment by oslynn** [comment]
@brandonnava, no.  It looks like STLT doesn't care about this feature anymore.  I will close it.  If there is STLT that needs this feature, we can reopen it.
