### ISSUE TITLE
BUG:  Make TASK table FK to REPORT_FILE table

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#2185]
See #2180 for the initial occurrence of this bug and PR for the matching fix.

This is to do a better fix for that issue:

Note the root problem in #2180 is that the TASK table doesn't Foreign key over to the REPORT_FILE table. If it did, then no TASK could ever exist without a proper entry in the REPORT_FILE table, and this bug would never occur.
However, this is hard to fix because currently reportFunction.kt inserts into the TASK table first. And that insert is part of a nice transaction that aborts and removes the blob upon failure. The solution is probably to move that entire transaction to the end of ReportFunction (where the actionhistory inserts happen now), but that'll require a LOT of careful checking and testing.

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/2185?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @smythe5 @TurkeyFried @whytheplatypus
