### ISSUE TITLE
Create Ability to Send an Empty Batch

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#2191]
North Carolina requested the ability to receive an empty HL7 batch file with no messages in it and a count of `0` if there's been no data received for the state.

**Comment by RickHawesUSDS** [comment]
I'll take this.

**Comment by RickHawesUSDS** [comment]
After talking with Cle, it look's like the best way to tackle this just add watch dog like function to trigger the empty batch.

**Comment by Adrian-Brewster** [comment]
Cle is this completed?

**Comment by clediggins-usds** [comment]
@Adrian-Brewster nearly done, ready for review now. Assuming no blocking issues, should be merged after the review scheduled for tomorrow.

PR: https://github.com/CDCgov/prime-reportstream/pull/3951

**Comment by clediggins-usds** [comment]
Duplicate #3641
