### ISSUE TITLE
React transition: live map updates

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#2210]
**Describe the bug**
Update map on `/how-it-works/where-were-live` with the following:

- [ ] Remove in-progress/onboarding states currently represented in light blue
- [ ] Remove mouse/pointer hover states, states aren't interactive
- [ ] Only show currently live STLTs in the current dark blue

**Impact**
Please describe the impact this bug is causing to your program or organization.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kevinhaube** [comment]
@drew-usds Hey! I was digging through the Cdc-map component code and there doesn't seem to be a way to disable the hover styling; it's pretty baked in there. However, I did update the map contents and tagged you in [the PR](https://github.com/CDCgov/prime-reportstream/pull/2222)!
