### ISSUE TITLE
React transition: Okta 400 error on logout

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#2212]
**Describe the bug**
- When logging out several of us are getting a 400 error and sent to the Okta site.
- It's also got SimpleReport branding, but not much we can do about that.

**Impact**
Please describe the impact this bug is causing to your program or organization.

**To Reproduce**
1. Sign in
2. Sign out
3. Mayyyyybe get a 400 page!

**Expected behavior**
- Sign out should take you back to `/log-in`.

**Screenshots**
![Screen Shot 2021-09-15 at 3.41.23 PM.png](https://images.zenhubusercontent.com/5ff50e49f74e134e95117280/28b853a9-5429-48bd-8558-9ab8583af946)

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Bisonburger** [comment]
Change made to Okta configuration (no code change)
