### ISSUE TITLE
Add logic to invert the order of email and phone number in HL7 PID-13 field

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#2214]
Washington asked if we could reverse the order of the email and phone number in PID-13. Currently we send them as `^NET^Internet^address@gmail.com~3601111111^PRN^PH^^1^360^1111111`, which is valid HL7, but most systems cannot handle that, so we have a work around of putting the patient email into PID-14, which most states accept.

We should just bite the bullet and fix the ordering once and for all. The wrinkle here is that in our ordering fields, `patient_email` comes first, so it defaults to first, and we don't have a concept of lookahead, so we will need to do some logic to see if there is a value in the field, and if there is, we need to prepend.

This case can be closed when emails are in the second repeat in PID-13. This should not overrule the states that send the patient email to PID-14. That should take precedence.

fysa: @RickHawesUSDS @carlosfelix2 @Adrian-Brewster

**Comment by Adrian-Brewster** [comment]
Washington requested we send a sample message with the email in PID-14 so see if that will be sufficient.

**Comment by Adrian-Brewster** [comment]
I believe this deployed yesterday.  @MauriceReeves-usds Are you good with me closing this out?
