### ISSUE TITLE
React transition: common link styling

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#2230]
**Describe the bug**
Links are showing in a few different ways, would be helpful to have a common class applied to each and have some different options for external links as well.

**Impact**
Please describe the impact this bug is causing to your program or organization.

**To Reproduce**

**Expected behavior**
- [ ] all body copy links should get `className="usa-link"`
- [ ] Nav links (header, footer, sidebar) should **not** get `className="usa-link"`
- [ ] External links should also get `target="_blank" rel="noopener"`

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by drew-usds** [comment]
Tagging you on this one Tom since you flagged this in the QA meeting!

**Comment by TomNUSDS** [comment]
USWDS has `<Link>` component used in a few places. There's also an [attribute on the component](https://trussworks.github.io/react-uswds/?path=/docs/components-typography-link--external-link) `variant="external"` that appends an open-in-new-window icon. However, it does not add `target="_blank" rel="noopener"`.

There is a [Custom Link](https://trussworks.github.io/react-uswds/?path=/docs/components-typography-link--custom-component-link) USWDS component that might work. [See discussion around customizing links](https://github.com/trussworks/react-uswds/issues/145)

@drew-usds Should our custom external links have the graphics?
![image](https://user-images.githubusercontent.com/74203452/134377760-6945175d-b3ed-476c-8cd4-567a4730f981.png)

**Comment by HeatherRienks** [comment]
Closing for now. Old issue.  @chris-kuryak to link to table component tix
