### ISSUE TITLE
React transition: static pages mixing with react

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#2239]
**Describe the bug**
- `/index`,and `/about` seem to be coming from the static site build, while the sub-pages on `/how-it-works/*` are loading more like a single page app.
- When navigating to `/how-it-works/*` you'll get a quick flash of all that section's content as well.

**Impact**
This may not be in line with how we're authorized to serve the site.

**To Reproduce**
1. Click around the main nav links
2. Click on `/how-it-works/*`
3. Get a quick flash of all the content
4. Navigate with the sidebar nav to get more of a single-page app experience

**Expected behavior**
- Pages should be static. 
- HOWEVER ... if the way this is working on staging is allowed, the page loads _do_ feel super snappy
- Connect with Ron to see what might be allowed here

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kevinhaube** [comment]
@drew-usds @MauriceReeves-usds We are good to close this issue. Ron got back to me and said the following:

> Hi Kevin! The front-end is still compiled down to static JavaScript and HTML, correct? I understand the route would be handling rendering the page dynamically in browser, but CDC’s concern is dynamic pages hosted on a server like Apache or IIS. Dynamic page rendering through an SPA framework is not a concern.
