### ISSUE TITLE
Clean CSV Data:  Replace Free-Text Fields Value with their Mapped Acceptable Value (e.g. AOE) 

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2242]
## Problem Statement
As an **Experity EMR platform user**, the AOE fields are free-text and the values we enter may not match the values that the PHD(s) find acceptable, so I need my free-text values replaced with their mapped acceptable value (or UNK if no match can be found) so that I can submit acceptable data to my PHD(s).

- Given I
    - Am logged into ReportStream as a user with Sender permissions
    - Am a Sender who is using the Experity schema
- When I
    - Log into ReportStream
    - Upload a CSV file
- Then 
    - The System, prior to submitting the file to ReportStream for processing, checks the value for each field designated as a free-text field against the list of expected values for that field and replaces the value with its mapped acceptable value 
        - In the event that no match is found, System uses "UNK" to populate the field
        - Refer to the vbScript for more specific criteria: [https://cdc.sharepoint.com/:u:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Sender%20Automation%20Team/vbScript%20for%20Data%20Cleansing%20Epic/PRIME-Sender-CUC-v2%20(2).vbs?csf=1&web=1&e=kNMv7G](url)     

## Design considerations & Assumptions:
This works almost like a lookup table except that the index can match anywhere on the string.  For example, the string may be "Is pregnant: Yes" and we want to match this to a Y.  Could also be something like "This person is not pregnant" and we want to match "not pregnant" to N.  Would have to test all the possible values against the string until there is a match.
- Just a setting on the element in the schema to make the mapper run
- Write the mapper to do this
- We don't have to do anything hackish
- We may need to do work to combine mappers

Acceptance criteria:
1. ReportStream is capable of translating an AOE data value that contains a specified contains a specified value and translate it to another value.
2. if the value is not found in the provided lookup data then the field is made unknown (UNK).

**Comment by carlosfelix2** [comment]
Suggestion for acceptance criteria:
1. ReportStream is capable of translating an AOE data value that contains a specified matching value and translate it to another value.

**Comment by jimduff-usds** [comment]
I'd urge you to use @carlosfelix2's new database table feature to implement this, along with a new mapper.

For example, for hl70136 AOE questions, you can create a lookup table in the database with all the zillion possible ways to say "no" and "yes", then write a new mapper that does a "like" or "contains" match on all that data in the lookup table.   If it finds ambiguity, have it return UNK.

Using the database gives you the flexibility to add/remove matches and refine it quickly over time.

Both of the blockers listed have been completed and are available for use.
