### ISSUE TITLE
Clean CSV Data:  Overwrite Provider First & Last Names using NPI Number to Look up Provider Name

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2244]
## Assumptions
- Just a setting on the element in the schema to make the mapper run
- Write the mapper to do this
- We don't have to do anything hackish
- We may need to do work to combine mappers

## Questions
- Can Mappers run in a specified order
- If there is NPI, will they always have Last Name & First Name for provider

## Problem Statement
As an **Experity EMR platform user**, the platform does not force me to enter the Ordering Provider first and last names and I may enter incorrect values so I need the values populated for me so that I can report this required information to my PHD.

- Given I
    - Am logged into ReportStream as a user with Sender permissions
    - Am a Sender who is using the Experity schema
- When I
    - Log into ReportStream
    - Upload a CSV file
- Then 
    - The System, prior to submitting the file to ReportStream for processing, looks up the First and Last Names for the provider with the supplied NPI number and overwrites the First and Last Names with the lookup values
        - Refer to the vbScript for more specific criteria: [https://cdc.sharepoint.com/:u:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Sender%20Automation%20Team/vbScript%20for%20Data%20Cleansing%20Epic/PRIME-Sender-CUC-v2%20(2).vbs?csf=1&web=1&e=kNMv7G](url)    
   
Design consideration:
1. We would require the NPI number, which is meant to be looked up in #1742, so mapper ordering is an issue.
2. CMS has a service where an NPI number can be looked up and obtain the provider first and last name. Need to consider if this is a separate story. (12/13/2021 LP: team agreed to do the CMS service work in a separate ticket, see comment)

Acceptance criteria:
1. ReportStream is capable of using a provided NPI number to set a provider last name.
2. ReportStream is capable of using a provided NPI number to set a provider first name.
3. If the NPI number cannot be found then the last and first name are set to blank.

**Comment by carlosfelix2** [comment]
Design consideration: We would require the NPI number, which is meant to be looked up in #1742, so mapper ordering is an issue.
Suggested acceptance criteria:
1. ReportStream is capable of using a provided NPI number to set a provider last name.
2. ReportStream is capable of using a provided NPI number to set a provider first name.

**Comment by loripusey** [comment]
The team agreed to limit the scope of this ticket to lookup the provider's first and last names from a database table and split out the work to call the CMS service to retrieve the providers names and cache them into a separate ticket [3245](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3425)

**Comment by rhood23699** [comment]
de-prioritized as of 12/27; not needed for standard CSV schema
