### ISSUE TITLE
Clean CSV Data:  Populate Patient Address Fields with Ordering Facility Address when Patient Address is Blank

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2245]
## Problem Statement
As an **Experity EMR platform user**, the platform does not force me to enter the Patient's address but ReportStream needs this information to determine to which PHD the data should be routed, so we need the system to populate the Patient's address with the Ordering Facility address so that the data can be routed to the state where the test was performed.

## Acceptance Criteria
- Given I
    - Am logged into ReportStream as a user with Sender permissions
    - Am a Sender who is using the Experity schema
- When I
    - Log into ReportStream
    - Upload a CSV file
- Then 
    - The System, when the Patient's address is blank and prior to submitting the file to ReportStream for processing, populates the patient's address as follows
        - Address --> "\*\*\* No Address Given \*\*\*" 
        - City --> ordering facility city
        - State --> ordering facility state
        - Zip --> ordering facility zip (5 chars)   

## Design Considerations
This implementation may need a new mapper that looks at two fields and if both fields ARE NOT present then replace a fields data.  Current mappers like ifpresent only looks at one field. Perhaps expand the ifpresent mapper?

**Comment by carlosfelix2** [comment]
Suggested acceptance criteria:
1. ReportStream will set a blank patient state and zip code with the ordering provider's state and zip code.

**Comment by jimduff-usds** [comment]
I'd support expanding ifPresent, if we can keep it backwards compatible to minimize impact.

**Comment by loripusey** [comment]
Let's go with the original AC, it makes it more sense that if we fill in the data for the patient, having the disclaimer makes it clear that the patient doesn't necessarily live in the city, state, zip we filled in @MikeC-A6 @rhood23699 thoughts?
