### ISSUE TITLE
Clean CSV Data:  Generate Accession Number, when Blank, & Populate Accession Field(s)

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2247]
**USE EXISTING CONCAT MAPPER???**

## Problem Statement
As an **Experity EMR platform user**, the platform does not force me to generate an Accession number for my lab result so I need the system to auto-generate one for me so that I don't have to figure out how to do that.

## Acceptance Criteria 
- Given I
    - Am logged into ReportStream as a user with Sender permissions
    - Am a Sender who is using the Experity schema
- When I
    - Log into ReportStream
    - Upload a CSV file
- Then 
    - The System, when an Accession number is blank and prior to submitting the file to ReportStream for processing, generates an accession number using one or more existing fields concatenated with a dash 
        - If one of the fields used to generate is blank, then System will not generate the Accession number
        - Refer to the vbScript for more specific criteria: https://drive.google.com/drive/folders/12qqnBP1JCkLXvJBQBatNxgErn8e74FzG      

## Design Considerations
This looks like the perfect use case for the concat mapper.  What happens if we specify multiple fields to the concat mapper and one of them is blank?  I do not think we want extra dashes with blank fields.
- ReportStream is capable of generating an accession number using one or more existing fields with a dash when the accession number is blank.

**Comment by carlosfelix2** [comment]
Suggested acceptance criteria:
1. ReportStream is capable of generating an accession number using one or more existing fields with a dash when the accession number is blank.

**Comment by rhood23699** [comment]
Carlos, please correct me if I'm wrong.  The autogenerated accession number must be done before it hits RS because this number will also be used as the Message ID (MSH.10) which is what Support will use when contacting a Sender about any problems with a message.  Since this is the case, the accession number must be built with data that means something to the Sender.  At a minimum, I would use PatientID + "-" + CSV Row # + Date the CSV was sent.  I don't believe the CSV Row # can be added when the message gets to RS.

**Comment by MikeC-A6** [comment]
@loripusey "The System, when an Accession number is blank and **prior to submitting the file to the ReportStream API**, generates an accession number using one or more existing fields concatenated with a dash."   I am confused as to why it says the part in bold.  Isn't the requirement that this happens after hitting the RS API?

**Comment by loripusey** [comment]
@MikeC-A6 changed it to "submitting the file to ReportStream for processing"
