### ISSUE TITLE
Clean CSV Data: Remove Un-Processable Characters from CSV File Prior to Schema Validation/Cleansing

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2248]
Note as of 12/2/21: Reddy FMC is the only Sender with this problem

**NEW MAPPER**

## Assumptions
- Just a setting on the element in the schema to make the mapper run
- Write the mapper to do this
- We don't have to do anything hackish

## Problem Statement
As a Sender who uses the CSV Uploader, me or my EMR software may insert unusable characters into my CSV file so I need the system to remove these characters so that the data can be processed by ReportStream.

## Acceptance Criteria
- Given I
    - Am logged into ReportStream as a user with Sender permissions
    - Am a Sender who is using the Experity schema
- When I
    - Log into ReportStream
    - Upload a CSV file
- Then 
    - The System, prior to submitting the file to ReportStream for processing, removes any characters that will prevent the processing of the CSV file by ReportStream
        - Refer to the vbScript for more specific criteria: [https://cdc.sharepoint.com/:u:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Sender%20Automation%20Team/vbScript%20for%20Data%20Cleansing%20Epic/PRIME-Sender-CUC-v2%20(2).vbs?csf=1&web=1&e=kNMv7G](url)

## Example
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/6686afcb-bbca-4ace-b0cb-faf29ab2da63)
   
## To do 
- [ ] Dev:

**Comment by carlosfelix2** [comment]
Suggestion for acceptance criteria:
1. ReportStream is capable of replacing one or more specified characters with one other specified character in a field given field.  E.g. replace "*&^%" with blank or space

**Comment by sean-usds** [comment]
From @rhood23699 "I would place this one in the IceBox.  So far this was a problem with only one client who's EMR vendor was based in India which produced UCS2 charset."

**Comment by loripusey** [comment]
@rhood23699 
A few questions:
1. Do we still need this functionality, just not right now?
2. What is the status of this client?  Are they in production? Are they using the vbScript and we intend to maintain their script?
3. Do we anticipate that there will be other clients with the same EMR & problem?

I can move it to the icebox but it will most likely be a low priority moving forward. I would prefer, if we don't need it in the near term, that we close the ticket. We can always re-open it at a later time.  I don't want the Ice Box to become of a large repository of all ideas we have ever had, but rather a queue for decision making, where tickets are regularly evaluated and either moved to our backlog or closed with comments on why we are not doing the work.

**Comment by rhood23699** [comment]
1 & 2.  We will eventually need this, but so far, Reddy FMC is the only Sender with this problem.  They are currently in PROD using the VBScript.  Since this is only one Sender, they can stay there as long as needed.  I'll support them when needed.  Completing the other data cleansing tickets and the new ticket on Basic Row Filtering will have an immediate impact on our ability to onboard more Senders with less effort and long term Support needs.
3.  Reddy FMC was a unique situation with a unique EMR vendor.  I don't anticipate encountering any like them for a while.  If we do, we'll have to delay them until we complete all other cleansing tickets.

**Comment by loripusey** [comment]
Thanks @rhood23699! I'll leave it in the Icebox then.

**Comment by loripusey** [comment]
de-prioritized as of 12/27

**Comment by jimduff-usds** [comment]
@brick-green-agile6 , @rhood23699  - should we close this ticket?

**Comment by rhood23699** [comment]
I say close it.  I'll create an ticket if it comes up again.

**Comment by brick-green-agile6** [comment]
yeah I agree with Rick
