### ISSUE TITLE
Alert Sender when SSN Detected in Uploaded CSV File

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2254]
## Problem Statement
As a Sender, I may have entered an SSN into a free-text field and I need the system to let me know so that it can be scrubbed from my CSV file before sending it to my PHD.

## Acceptance Criteria
- Given I
    - Am logged into ReportStream as a user with Sender permissions
    - Am a Sender who is using the Experity schema
- When I
    - Log into ReportStream
    - Upload a CSV file
- Then 
    - The System, prior to submitting the file to ReportStream for processing, looks in all free-text fields for a potential SSN value (9 digit with or without dashes) and prompts my to confirm if the data should be removed or obscured by replacing the value(s) with "\*\*\*Possible SSN detected and obscured\*\*\*"  
  
## To do 
- [ ] Dev:

**Comment by loripusey** [comment]
@kjt9cc can you take a look and see if this meets the need that Stephanie & Ron mentioned in our security meeting?

**Comment by carlosfelix2** [comment]
Need more discussion on this one with security.

**Comment by rachelhanster** [comment]
Closing ticket due to uploader's move to simplereport
