### ISSUE TITLE
Allow a mapper mapper to  run even when field data is present

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#2270]
As a schema developer, I want to be able to specify if a mapper is to always run even when a field has data. Current mappers only run if a filed has no data. This change will allow further manipulation of a raw data value without having to create a new field to hold a converted value. A disadvantage of this method is that the original raw value will not be saved in ReportStream. Also note that by default the mappers will not run if data is present (current design).

Design considerations:
You must note that mappers are used in various places, like the serializers, deserializers and translation, so it is recommended to refactor the code with this logic to a central location (e.g. Element.kt).

Acceptance criteria:
1. ReportStream shall run a configured mapper even when data is present in a field if the always to run flag in the schema is set.
2. ReportStream shall run a configured mapper on a blank field only if the always to run flag in the schema is unset.
3. The always to run flag defaults to unset if not specified.

**Comment by carlosfelix2** [comment]
As a schema developer, I want to be able to specify if a mapper is to always run even when a field has data.  Current mappers only run if a filed has no data.  This change will allow further manipulation of a raw data value without having to create a new field to hold a converted value.  A disadvantage of this method is that the original raw value will not be saved in ReportStream.  Also note that by default the mappers will not run if data is present (current design).

Design considerations:
You must note that mappers are used in various places, like the serializers, deserializers and translation, so it is recommended to refactor the code with this logic to a central location (e.g. Element.kt).

Acceptance criteria:
1. ReportStream shall run a configured mapper even when data is present in a field if the always to run flag in the schema is set.
2. ReportStream shall run a configured mapper on a blank field only if the always to run flag in the schema is unset.
3. The always to run flag defaults to unset if not specified.

**Comment by whytheplatypus** [comment]
This makes sense and can be broken down further. The problem is that there should be things that can run to handle a `default` value, meaning the field is blank. And there are things that can run to modify an existing value. Rather than add a flag maybe making those use cases distinct will make it easy to deal with.

```yml
- default: <function names / args, or straight value>
- mappers:
    - name: mapper1
      args: 
        arg1: hello
        arg2: world
```
or go further and say the field can have either a `default` or a `default_function` or something like that.

Allowing it to be very clear that a `default` is used only if a field is blank, while a `mapper` (probably should be renamed to transform) runs only of this field is present
