### ISSUE TITLE
Details does not show organization & location

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#2282]

**Comment by kevinhaube** [comment]
This appears to be fixed! @sean-usds Can you confirm this? I'm assuming the Organization and Location columns weren't displaying in staging prior?
![Screenshot from 2021-09-30 09-39-13.png](https://images.zenhubusercontent.com/611a907ec3e013d0e33e58a7/853d0a3e-a820-4a2c-8c05-3a0936ec60f1)
