### ISSUE TITLE
Nav styling different than prod

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#2287]
ReportStream text larger
No bottom rule
How it works is bolded

![image.png](https://images.zenhubusercontent.com/61310371004bdd52b9b7d2c4/fe30e9ac-e120-4dde-aa1c-7d9fba499a57)

![image.png](https://images.zenhubusercontent.com/61310371004bdd52b9b7d2c4/95f797bf-61b8-46b9-ab8f-f1877b0bc6ec)

**Comment by sean-usds** [comment]
Possibly a dupe

**Comment by drew-usds** [comment]
This has already been resolved and merged into staging.
