### ISSUE TITLE
Simplify/improve required/optional fields, defaults, *_OR_BLANK, cardinalities

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#230]
As a sender of data, I want a simple understanding of what fields are required, and which are optional, which have defaults, etc.

This ticket is just to write a proposal, and get it reviewed and approved.

There's an ongoing discussion on this topic.   see attached file [jims-thoughts-on-required-fields.txt](https://github.com/CDCgov/prime-data-hub/files/5765907/jims-thoughts-on-required-fields.txt)

(See also related ticket #1468)

**Comment by jimduff-usds** [comment]
[jims-thoughts-on-required-fields.txt](https://github.com/CDCgov/prime-data-hub/files/5765907/jims-thoughts-on-required-fields.txt)

**Comment by RickHawesUSDS** [comment]
I believe that simplification is possible, but I think the proposal is too simplified. I suggest documententing the use-cases may be a way to reveal our needs.

**Comment by MauriceReeves-usds** [comment]
@RickHawesUSDS - I think the changes we just discussed about cardinality can just come in other this issue.

**Comment by MauriceReeves-usds** [comment]
Adding in @jimduff-usds' comments directly into the ticket as a comment.

What Rick has in CsvConverter.kt:

| Type         | Cardinality | no column on input                   | empty input value                    | Invalid input value | valid input value |
|--------------|-------------|--------------------------------------|--------------------------------------|---------------------|-------------------|
| FOO          | 0..1        | mapper -> default -> empty + warning | mapper -> default -> empty + warning | empty + warning     | value             |
| FOO          | 1..1        | mapper -> default -> error           | mapper -> default -> error           | error               | value             |
| FOO_OR_BLANK | 0..1        | mapper -> default -> empty + warning | empty                                | empty + warning     | value             |
| FOO_OR_BLANK | 1..1        | mapper -> default -> error           | empty                                | error               | value             |


Jim's translation of it, to be a bit more schema-user-friendly:

| Desired behaviour for Field | How to set, in schema           |  Column Missing | Blank Value | Invalid Value
|-----------------------------|---------------------------------|-----------------|-------------|-------------------|
| Optional, but warn me       | FOO, cardinality: 0..1          | Warn only       | Warn only   | Warn, and zero out
| Required always             | FOO, cardinality: ONE           | Error           | Error       | Error     
| Optional, but blank is OK   | FOO_OR_BLANK, cardinality: 0..1 | Warn only       | Silent/OK   | Warn, and zero out
| Required, but blank is OK   | FOO_OR_BLANK, cardinality: ONE  | Error           | Silent/OK   | Error     


And here my latest thoughts, now with the addition of default field values:

| Desired behaviour for Field | How to set, in schema     |  Column Missing | Blank Value                             | Invalid Value
|-----------------------------|---------------------------|-----------------|-----------------------------------------|-------------------|
| Required always             | option: REQUIRED (default)| Error           | Error                                   | Error
| Required, but blank is OK   | option: REQUIRED_BLANK_OK | Error           | Replace with blank or default value     | Error
| Optional                    | option: OPTIONAL          |       In all these cases, Warn, and Replace with blank or default value

Note: Warning can be silenced using `option=NoWarn` in the URL.  Errors cannot be silenced.

Also, errors cannot be masked by a `default: <val>` for the field.  In all other cases, if a default value is available, it will replace a Blank

**Comment by jimduff-usds** [comment]
Default values are all mixed up in this issue as well.

The covid field processing_mode_code is a typical example of how confusing we have made this.   You can set processing_mode_code defaults in the following places:
-- in the `translate` section of the receiver settings (at least for redox, you can do this)
-- as a parameter to the POST
-- in the `basedOn` schema (eg, as a default in the 'covid-19' kitchen sink schema)
-- in the parent schema, which is different from the `basedOn` schema
-- in your own schema (as in healthtest example in PR #1223)
-- And of course in the actual data, which might also be blank, or missing the column completely.
Yes, this is all quite confusing. I certainly couldn't tell you which gets priority.
