### ISSUE TITLE
Update mailto links

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#2300]
The Contact us button in About attempts to open an email in the default local mail app. But if one is not configured(I'm using the web based email client) then I am unable to retrieve the email address to contact RS. Need to be able to copy and paste the email address or a contact entry form. I'm using chrome on mac.

**Comment by sean-usds** [comment]
Ideally these are forms

**Comment by bgantick** [comment]
Closing: moving this into a separate feature (contact form?) cc @rachelhanster @RakshindaAslam
