### ISSUE TITLE
Logging out should clear local/session storage keys and cookies

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#2304]

**Comment by kevinhaube** [comment]
Hey @sean-usds, I took a look at the Application > Storage in the console and it appears as though cookies and session storage are both already being cleared on logout. The remaining item in local storage is an `okta-cache-storage` item. Should we be clearing this as well?![Screenshot from 2021-09-27 09-32-54.png](https://images.zenhubusercontent.com/611a907ec3e013d0e33e58a7/35da5a85-29c1-4b8e-b5f9-51612a089c24)
