### ISSUE TITLE
Add date for last reported test in each facility to weekly CLIA reports

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#2320]
North Dakota requested that we start including "date of last report" for each facility in the CLIA reports we send out weekly. @MauriceReeves-usds is this a fairly easy column to add?

**Comment by MauriceReeves-usds** [comment]
@Adrian-Brewster it shouldn't be too hard. Some fairly simple SQL could provide that.

**Comment by anshulkumar-usds** [comment]
@Adrian-Brewster, Leslie reached to me and mentioned Zedd from her team can help with this. WA expressed a need for this as well.

cc @LGFranklin

**Comment by Adrian-Brewster** [comment]
Completed and added to all state CLIA reports
