### ISSUE TITLE
Initial investigation of how to Ingest HL7 File from HCA

### ISSUE THREAD

**Issue by clediggins-usds** [CDCgov/prime-reportstream#2328]
Determine what changes need to be made to an example HL7 file from HCA and ingest one using the existing ReportStream HL7 process flow. Document what, if any, changes need to be made pre-ingestion to get it to parse properly. 

Ensure that once ingested, the in-memory representation of the files contains all of the data expected based on the file.

Objective: verify that HAPI can parse the provided files from HCA, and make notes of any transforming that needs to happen to make this succeed.

**Comment by clediggins-usds** [comment]
We can ingest the 'post' files (that have had their MSH updated to remove '#' and have superficial OBX records that are actually notes removed) and generate an output following our current process *IF* there is a device name added to OBX 17.2.  The files provided by HCA do not appear to have this field populated, so we will need to either make that field non-required or work with HCA to get the value input.

**Comment by clediggins-usds** [comment]
This task is being put on hold for the time being to focus on Ellume and Abbot ingestion.  Current status:

HCA files do not have 17.2 (equipment model name) and our process requires it. The files do have 17.1 (equipment device id) and our livd table lookups have ids and name - the code currently is just not using the lookup in the manner required to make this work. 

We could take in HCA files in the form they currently are, but there will be some code changes required on our side to look up equipment name by id.

**Comment by jimduff-usds** [comment]
[https://app.zenhub.com/files/304423150/cf9c3f21-2609-4f22-b210-4c2db2641936/download](https://app.zenhub.com/files/304423150/cf9c3f21-2609-4f22-b210-4c2db2641936/download)

(It wouldn't let me upload a plain .md file)    This attached file an an analysis Jim did on Nov 1, looking at the distance between our current HL7 parsing and what we need to support full ELR.
