### ISSUE TITLE
React: page <title>s aren't the same as production

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#2344]
Every page on staging currently has the <title> set as "ReportStream Dashboard"

Titles should match what's on prod. In 11ty they are stored in front matter and slug-ified. There's also some logic to change some styling/pipes depending on the page (ex: index = `PRIME ReportStream`, ELR onboarding page = `ELR onboarding | How it works | PRIME ReportStream`

**Comment by sean-usds** [comment]
PR https://github.com/CDCgov/prime-reportstream/pull/2369
