### ISSUE TITLE
BUG: Sending SPM segment before OBX segments returns error

### ISSUE THREAD

**Issue by jbiskie** [CDCgov/prime-reportstream#2372]
## Problem statement

When an HL7 message is submitted with the SPM segment before the OBX segments, RS returns a warning qualityFilter hasValidDataFor(equipment_model_name) reduced the Items from [n] to 0.  The same message submitted with SPM after OBX processes without issue.

The HL7 standard is SPM preceding OBX ([link](https://hl7-definition.caristix.com/v2/HL7v2.5.1/TriggerEvents/ORU_R01)).  In order to be most flexible with incoming data, we should accept these segments in either order if possible.

## Acceptance criteria

An HL7 message with an SPM segment before the OBX segments processes without error.

**Comment by anshulkumar-usds** [comment]
Bug: Quality filter, fails on universal model name.

needs more definition, backlog grooming
