### ISSUE TITLE
Walk Rick/Herman through OKTA account creation

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2380]
As part of the CSV Uploader Pilot, we need for A1H to have an OKTA account so that they can access the ReportStream CSV Uploader.

TO DO: 
- Aurora will grant OKTA admin access to Rick H. and Herman
- Rick/Herman will do the work to give A1H access to ReportStream CSV Uploader via OKTA

**Comment by loripusey** [comment]
@ahay-agile6 can you grant Rick Hood and Herman admin access to OKTA?

**Comment by rhood23699** [comment]
Done.
