### ISSUE TITLE
On the current React site, the 15 minute automatic user timeout is missing

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#2381]
**Describe the bug**
The React rewrite of the web receiver appears to be missing the user logout timer. 

**Impact**
Please describe the impact this bug is causing on your program or organization.

A user timeout of 15 minutes (not sure about this required value) is required by the ATO. 

**To Reproduce**
1. log-in to staging.reportstream.cdc.gov
=> Daily data page
2. Wait for 1 hour
3. Refresh daily data page
=> See that the daily data page is available
expected: The user is logged out.  

**Expected behavior**
A user will need to log in again after 15 minutes

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kevinhaube** [comment]
The work is ready for test in `kevinhaube/timeout-in-react` but I'm awaiting some Okta admin configuration help from Sean. After that, there will be a PR available to pull down and test.
