### ISSUE TITLE
Allow Sender to Record their TOS Agreement

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2390]
## Problem Statement
As the CDC, we need to record a Sender's acceptance of our Terms of Service prior to them being allowed to use ReportStream to submit COVID data so that we have our legal bases covered.

## Design
https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=1150%3A470

## Acceptance Criteria
- Given I
    - Am a potential Sender of COVID data
- When I
    - Receive a public link to the TOS Agreement form from the Support team
    - Open the public link
- Then 
    - I am taken to a web page where I can 
        - Link to and read the existing TOS
           - https://reportstream.cdc.gov/terms-of-service/
        - Submit my agreement to the TOS along with the following identifying information
            - Organization name
            - Title
            - First name
            - Last name
            - Email
            - State or territory
    - After I submit, I see a confirmation page with the form data I submitted along with instructions for the next steps
        - If there was an error, I see the error message on this confirmation page
        - LORI CHECKING ON IF WANT TO COMMIT TO GETTING BACK TO THEM IN 1 WEEK (LP 10/5/2021: YES)
    - System sends the data to the ReportStream@cdc.gov inbox and cc's the Sender's email 
         - To
             - ReportStream@cdc.gov 
         - CC
             - Sender's email (DAWN CHECKING ON IF THEY NEED A COPY)
         - From
             - No Reply at ReportStream@cdc.gov
         - Subject
            - "TOS Agreement for " + Organization_Name
         - Body 
            - "The following Organization has agreed to the CDC Terms of Service:"
                - Organization name
                - Title
                - First name
                - Last name
                - Email
                - State or territory

## Questions
- Which SMTP server are we using?

### Dev: 
- [ ] ...

### Design:

Take a second pass at content for:
- [x] Form (make sure headers, labels, etc make sense)
- [x] Confirmation page
- [x] Confirmation email
- [ ] Double check email subject line is good with O&O

**Comment by loripusey** [comment]
Let's confirm with Rick Hawes & a CDC legal stakeholder once we have the UI pages spun up for this

**Comment by loripusey** [comment]
@kevinhaube Can we get an update on where we are with this at the next standup?

**Comment by loripusey** [comment]
Is currently in staging (and maybe prod) behind an admin auth wall
- need rate limiter

**Comment by loripusey** [comment]
@Adrian-Brewster Here is the ticket for the TOS agreement form; can the O&O team test this form in staging?

**Comment by kevinhaube** [comment]
@loripusey @Adrian-Brewster You'll have troubles testing this until the rate limiter and IP ranges are put in place.  Sean and Chris are going to adding those, and then I have a branch ready to merge that'll open it up for testing. I went ahead and threw this into ticket #3223 

cc: @sean-usds @cwinters-usds
