### ISSUE TITLE
Sender content outline - Welcome Email template

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#2393]
## Problem statement

Outline sender focused content based on current comms from Mike C. Will be published on the website.

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

Currently have:
- Welcome email example
- One pager ([see PRIME 1-pager](https://www.cdc.gov/surveillance/pdfs/PRIME_1-sheet_single-page.pdf))

## Acceptance criteria

We have:
- [ ] An outline of index content changes
- [ ] Outline sender "how it works" section"

## To do

- [x] Draft Welcome Email for PHD

**See #2781 for Research/Investigation tasks**

**Comment by BerniXiongA6** [comment]
@drew-usds Here's a DRAFT of the "sender welcome email" copy we can review today in our Design Sync. It was adapted from the Reddy Lab sendoff email we received from the Sender Automation team.

[https://app.zenhub.com/files/304423150/f3e6d4e7-d11e-4e45-adfb-c50efb2f6671/download](https://app.zenhub.com/files/304423150/f3e6d4e7-d11e-4e45-adfb-c50efb2f6671/download)

**Comment by BerniXiongA6** [comment]
11.9.2021 Welcome email template was reviewed. Mark as Done.
