### ISSUE TITLE
California SimpleReport Centralized CLIA 

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#2447]
California is requesting that we send all SimpleReport data through a centralized CLIA. 

This would include putting the centralized CLIA in MSH 4.2 and moving the sending facility name/CLIA to OBX. 

we will do this by creating a map in the translation configuration that lets us specify: sender1 : CLIA1 , sender2 : CLIA2 etc.

**Comment by Adrian-Brewster** [comment]
Made deployment last Friday.  Need to update settings.

**Comment by brick-green-agile6** [comment]
verified that MSH-4.2 was sent with CDPH000085 in file to CA. Still need CA to verify on their end.
