### ISSUE TITLE
Fix issues related to consolidation of warning/error messages

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#2455]
NOTE:  Pointing with the assumption that we need to discuss the idea of API versioning and determining the timing if we are not versioning.

These are issues left over from the #2319 PR, which was a massive and much-needed improvement in our json responses, that were getting absurdly large in cases where there were repeated warnings.

However, the json response needs to work for both our automated and our manual submitters.  Also, it needs to work for hl7 and csv's.   So some further tweaks are needed:

Acceptance Criteria:
1. add the `scope`: field to the consolidated errors/warnings, with the same value as the current individual errors/warnings (eg, REPORT, ITEM, etc)
2. only ITEM scope will have the list of "rows" (aka Items). For others, that field can just be null or missing (not sure which is best practice). For example:

Per this criteria, the current warning:

```
{
   "message" : "Unexpected 'xxxsenderId' header is ignored",
   "rows" : ""
 } 
```

would now look like this:

```
{
   "scope" : "REPORT",
   "message" : "Unexpected 'xxxsenderId' header is ignored",
 } 
```

3. The current "rows" is nicely brief and is usable by the UI, so let's keep it, but just change the name so it makes sense for HL7.   But we still need to provide the tracking ids, especially for HL7 - let's do that only when verbose mode is turned on.  So **when in verbose mode, also add details with the tracking ids**, so it might look like this (excuse the garbled syntax):

```
"consolidatedWarnings" : [ {
   "message" : "Bad stuff happened",
   "itemNums" : "Rows: 2, 4-6",
   "itemDetails":  [ {
          "itemNum": 2, id: "trackingId17"
                    }, 
                   {
          "itemNum": 4, id: "trackingId23"
                    }, 
                 {
          "itemNum": 5, id: "trackingId45"
                    }, 
                 {
          "itemNum": 6, id: "trackingId3"
                    }]
}]
```

4.  Rename consolidated errors/warnings to just be errors and warnings, and get rid of the old errors and warnings.  
5.  Work with @anshulkumar-usds to write release notes that can be given to all our Senders
6.  @anshulkumar-usds needs to drive the timing of when this gets merged.   We can't merge in customer facing changes without letting customers know, and some may be depending on the current json syntax.

**Comment by jimduff-usds** [comment]
Here's a sampling of what the OLD warnings look like (currently still in the json):

 ```
{
    "scope" : "ITEM",
    "id" : "SomeEntityID",
    "details" : "Invalid code: 'Q' is not a display value in altValues set for 'processingModeCode' ('processing_mode_code')"
  }, {
    "scope" : "ITEM",
    "id" : "SomeEntityID",
    "details" : "Invalid date: '999999-0400' for element 'testReportDate' ('test_result_report_date')"
  }, {
    "scope" : "ITEM",
    "id" : "SomeEntityID",
    "details" : "Invalid date: '9' for element 'testOrderedDate' ('order_test_date')"
  }, {
    "scope" : "ITEM",
    "id" : "SomeEntityID",
    "details" : "Invalid date: '999' for element 'specimenCollectedDate' ('specimen_collection_date_time')"
  }, {
    "scope" : "ITEM",
    "id" : "SomeEntityID",
    "details" : "Invalid postal code '85714123123123123' for 'performingFacilityZip' ('testing_lab_zip_code')"
  }, {
    "scope" : "ITEM",
    "id" : "SomeEntityID",
    "details" : "Invalid postal code 'Not a zip code' for 'orderingFacilityZip' ('ordering_facility_zip_code')"
  } ],

```

And here's a sampling of what the new consolidated warnings/errors look like:

 ```
 "consolidatedErrors" : [ {
    "message" : "Blank value for element ",
    "rows" : "Rows: 2, 4, 6, 8, 10, 12, 14, 16, 18–19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 122–152"
  } ],
  "consolidatedWarnings" : [ {
    "message" : "Invalid code: 'Q' is not a display value in altValues set for 'processingModeCode' ('processing_mode_code')",
    "rows" : "Rows: 2, 4, 6, 8, 10, 12, 14, 16, 18–19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 122–152"
  }, {
    "message" : "Invalid date: '9' for element 'testOrderedDate' ('order_test_date')",
    "rows" : "Rows: 2, 4, 6, 8, 10, 12, 14, 16, 18–19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 122–152"
  }, {
    "message" : "Invalid postal code '85714123123123123' for 'performingFacilityZip' ('testing_lab_zip_code')",
    "rows" : "Rows: 2, 4, 6, 8, 10, 12, 14, 16, 18–19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 122–152"
  }, {
    "message" : "Invalid postal code 'Not a zip code' for 'orderingFacilityZip' ('ordering_facility_zip_code')",
    "rows" : "Rows: 2, 4, 6, 8, 10, 12, 14, 16, 18–19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 122–152"
  }, {
    "message" : "Invalid date: '999' for element 'specimenCollectedDate' ('specimen_collection_date_time')",
    "rows" : "Rows: 2, 4, 6, 8, 10, 12, 14, 16, 18–19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 122–152"
  }, {
    "message" : "Invalid date: '999999-0400' for element 'testReportDate' ('test_result_report_date')",
    "rows" : "Rows: 2, 4, 6, 8, 10, 12, 14, 16, 18–19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 122–152"
  }, {
    "message" : "Unexpected 'xxxsenderId' header is ignored",
    "rows" : ""
  } ]

```

**Comment by kevinhaube** [comment]
Hey @jimduff-usds! I took care of steps 1-4 in this ticket (all the code changes). Working with @anshulkumar-usds now on the release notes; I'm a bit confused, though. Is this affecting `/api/waters`?

**Comment by jimduff-usds** [comment]
/api/waters is identical to the current /api/reports, but with a different authentication style.   So it would affect both.
