### ISSUE TITLE
Create PRIME CLI Grep Tool

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#2460]
We need a tool that will let us parse an HL7 or CSV message via the command line and do a few things:

1. Search for a value in a specific segment or segments in an HL7 message: `./prime grep --input sample-hl7-message.hl7 --fields "MSH-4,SPM-2" --equals "12D1212123"`
2. Search for a value in a specific row in a CSV message: `./prime grep --input sample-csv-message.csv --input-schema primedatainput/pdi-covid-19 --fields "Ordering_facility_name" --eq "Roosevelt General Hospital"`

As executed above, the tool would just output the matching lines to the terminal. You could also include a switch to output the file to a new file by doing this:

**HL7**
`./prime grep --input sample-hl7-message.hl7 --fields "MSH-4,SPM-2" --equals "12D1212123" --output <PATH TO FILE>  --output-format HL7_BATCH`

Executing the above would create an HL7 batch file with the correct header and footer information at the path provided.

**CSV**
`./prime grep --input sample-csv-message.csv --input-schema primedatainput/pdi-covid-19 --fields "Ordering_facility_name" --eq "Roosevelt General Hospital" --output-schema direct/experity-covid-19 --output <PATH TO FILE> --output-format CSV`

Executing above would output a CSV file to the path provided with the output schema selected. If no output-schema is selected the input schema is used by default. The file would also output the correct header as well.

Additional search operators include:
* `like` - Does a case-insensitive search
* `contains` - Does a search inside each field
* `neq` - Matches any field that does not equal the search value
* `not-like` - Does an negative case-insensitive search
* `regex` - Executes a regex against the field to look for matching values

In addition, the grep command should allow us to pass in a wild card path to input multiple files and then merge them into a single file.

**Comment by brick-green-agile6** [comment]
Would the search result output the entire segment or csv record? If output to a file for HL7, could it include the entire message or at least an option for that?

**Comment by MauriceReeves-usds** [comment]
@brick-green-agile6 the goal would be to have it output the entire row/message by default. We could add an option to only output a selection of segments or columns.

**Comment by brick-green** [comment]
@brandonnava we did not build this. It would be nice to have when things go bad and we need to resend specific messages. But that hasn't happened recently. There's not a high value use case in normal day-to-day operations.
