### ISSUE TITLE
Pre-commit GitHook is triggered by valid 'key' property on React listed elements

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#2469]
Our pre-commit hooks are triggered by the key property used to uniquely identify list elements in the React frontend directory despite not being sensitive information populating the property:
```
{
  "line": "                    key=\"upload\"",
  "lineNumber": 2,
  "offender": "key=\"upload\"",
  "offenderEntropy": -1,
  "commit": "0000000000000000000000000000000000000000",
  "repo": "repo",
  "repoURL": "",
  "leakURL": "",
  "rule": "Generic Credential",
  "commitMessage": "",
  "author": "",
  "email": "",
  "file": "frontend-react/src/components/header/ReportStreamHeader.tsx",
  "date": "1970-01-01T00:00:00Z",
  "tags": "API, generic, key"
 }
```

The code in question:
```
<Link href="/upload"
  key="upload"
  data-attribute="hidden"
  hidden={true}
  className="usa-nav__link">
     <span>Upload</span>
</Link>
```

**Comment by sean-usds** [comment]
let's find a way to allow list react files from this check

**Comment by HeatherRienks** [comment]
@bgantick - thoughts on this ticket?

**Comment by bgantick** [comment]
Unable to trigger this running the pre-commit hook locally on changed/added `key` property in a `.tsx` file. This may have been addressed already. Closing this for now until it can be replicated.
