### ISSUE TITLE
Add Organization Name to Metadata table

### ISSUE THREAD

**Issue by brick-green-agile6** [CDCgov/prime-reportstream#2473]
Organization name is sent from Simple Report under the column Organization_name. This field is used to group multiple testing facilities together.

Example:
- Organization: Cricksaw County School District
     - Facilities:
          - Houston Lower Elementary
          - Houston Upper Elementary
          - Houston Middle School
          - Houston High School

**Comment by Adrian-Brewster** [comment]
Mo is waiting on feedback for Jim

**Comment by anshulkumar-usds** [comment]
Mo to merge in 1/21/22

**Comment by Adrian-Brewster** [comment]
@MauriceReeves-usds Any update on this?

**Comment by Adrian-Brewster** [comment]
@MauriceReeves-usds to merge.
