### ISSUE TITLE
Fix typescript files with @ts-nocheck 

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#2477]
## Files
- [x] frontend-react/src/App.tsx
~frontend-react/src/components/AuthorizedRoute.tsx~ (creating a [separate ticket #3406](https://github.com/CDCgov/prime-reportstream/issues/3406). Fixing this item is tricky)
- [x] frontend-react/src/pages/details/Details.tsx
- [x] frontend-react/src/pages/error/ErrorPage.tsx
- [x] frontend-react/src/pages/home/Home.tsx
- [x] frontend-react/src/pages/home/Sections/LiveMapSection.tsx
- [x] frontend-react/src/pages/how-it-works/WhereWereLive.tsx

## Steps
- Remove `// @ts-nocheck // TODO: fix types in this file`
- Fix build errors

Can be broken into individual bugs for each file

**Comment by TomNUSDS** [comment]
The last file (AuthorizedRoute.tsx) that needs refactoring is super tricky because it might be a bug with how React's hooks are being used.

I'd like to break it out into its own ticket with more points and mark this one as done.

**Comment by HeatherRienks** [comment]
@TomNUSDS - per Sprint Planning, we will not add to Sprint 31 - Spike ticket will be created in Icebox for review.

**Comment by TomNUSDS** [comment]
Closing this larger task. The final file to fix is big enough to be broken out into its own issue https://github.com/CDCgov/prime-reportstream/issues/3406
