### ISSUE TITLE
API endpoint to expose what organizations we are currently live in

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#2487]
## Description
We need an API endpoint that will filter organizations by the `customerStatus` enum value added in #1974, and the presence of receivers, exposing a JSON list of the matching values.

## Background
Currently, we have an API endpoint in the `settings` function that allows system admins to see a list of all organizations. We need to create a new endpoint for the front end that the web team can consume that allows a non-authenticated user to get the list of all organizations in ReportStream with at least one defined receiver that matches the `customerStatus` values we pass in.

The customer status enum has three values: "inactive", "testing", "active". 

## Acceptance criteria:
* A new API endpoint is created at `/api/frontend/active-organizations` that returns a JSON list of any organization that has its `customerStatus` value equal to the values we pass in. The values in the JSON list should include just the organization name and the state values. For example, if we invoke the endpoint like this: `/api/frontend/active-organizations?customerStatus=inactive`, it will return a list of organizations that are currently listed as inactive. If we invoke it like this `/api/frontend/active-organizations?customerStatus=testing,active` it will return organizations that are in either the testing or active status. If the endpoint is invoked with no value, therefore like this: `/api/frontend/active-organizations` it will default to matching only active organizations.
* The organizations included should have at least one receiver defined. If the organization has only senders it is not included in the list
* The API should not require authentication, so it can be invoked from the static site by anyone

**Comment by chris-kuryak** [comment]
Too vague. Already accomplished some of it. Closing by committee decision. Will be re-assessed in future website improvement efforts.
@drew-usds @fmccaf1 @HeatherRienks @lizzieamanning
