### ISSUE TITLE
LIVD Table Update Utility

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#2488]
## Background
Currently the process for updating the LIVD table is a manual one, which involves downloading the file and then doing some processing around extracting a single tab and saving it as a new CSV file. We can build a tool that will take a LIVD file downloaded off of the website, extract the data that we want, and then replace the existing file with the new data.

At some point the LIVD table will end up in the database as part of @carlosfelix2 work, but for now, this will ease our efforts around keeping up-to-date with LIVD changes.

## Acceptance Criteria
**NOTE that these acceptance criterias are a bit old.  See epic acceptance criteria for epic issues.**
* The current LIVD table to no longer have the date in the name, but instead the "current" file will have the name `LIVD-SARS-CoV-2.csv`. 
* All references to the most recent file will be updated in the project as well.
* A script (python is fine, or we can build it into the prime executable if you prefer) will be created that will migrate the existing file to an archive with the following name format: `LIVD-SARS-CoV-2-Archive-yyyymmdd-00.csv` where the date format is the date of archiving, and if the `00` is the current count of archives, the first being `00` and then incremented each time
    * The script will accept a path to a downloaded XLSX LIVD table from https://www.cdc.gov/csels/dls/sars-cov-2-livd-codes.html
    * The script will create an extract of `LOINC Mapping` tab from that spreadsheet that matches our current files and create a temporary CSV file from it
    * The script will then do a hash to compare the existing CSV file in the `tables` folder against the temp CSV file, and if the hashes match, it exits without replacing anything
    * If the hashes don't match it copies the existing file into an archive with the name formatted as above and then replaces the current file with the temporary file we created
* Archiving and replacing the existing file should be the last step of the process, so we do not inadvertently delete the existing file, and if there are any errors, the existing file should not be replaced either

## Additional Notes
There is obviously no provision above for rotation or clean up of archived files above. This is intended to be a tool that makes the process of updating the LIVD table more repeatable and safer, but it is not intended to be run without human oversight. In fact, after the file is replaced by running this utility, the application still needs to be thoroughly tested, and the update needs to be submitted as a PR for review.

Eventually we can expand on and improve this tool to automate the process of saving the new LIVD information to the DB.

**Comment by oslynn** [comment]
This is already done in the **./prime livd-table-download** command.
