### ISSUE TITLE
BUG:  Item Lineage Table Doesn't Always Have Tracking Id

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#2504]
## Background
Currently, the `ItemLineage` table doesn't always have the tracking ID filled in, even as a message goes through processing. While it is possible that a message doesn't necessarily have a tracking ID, for most senders (i.e. SimpleReport) we have a message ID, and the HL7 we're sending out to states includes a message ID, so we need to make sure that have an end-to-end tracking ID. 

## Acceptance Criteria
For a message sent by any sender who is using a tracking Id in their schema, we need to make sure that the tracking ID is carried through each step in item lineage from receiving to sending out to the jurisdiction.

**Comment by Adrian-Brewster** [comment]
@jimduff-usds @JGreenFearless Can the pipeline team pick this up?
