### ISSUE TITLE
MD - Data Issues & Questions

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#2518]
**Describe the bug**
It appears data sent by ImageMover is getting into Maryland's feed without CLIAs. Currently Friendship Charter Schools are not using SimpleReport based on my investigation and further confirmation from Emma and Adam (there are no K-12 facilities using SimpleReport in MD). I remembered getting a message from Tyler (ImageMover) inquiring if they can start the process to send Friendship Charter School data via ReportStream for DC. 

> _In addition to the questions above, can someone let me know if there is a way for us to not receive results that do not have CLIAs? We need to make sure there are no message failures. This is coming from Friendship Public Schools_

Additional Questions:

- Is there any way to know what facilities are included under Report Stream (not just ones we have signed up for SR)?

- For OTC data, is there any way to know where this data is coming from? I cannot tell what company/test kit is being used. There is really not much information besides knowing it is a PCR or antigen test.

**Impact**
Maryland is getting message failure due to missing CLIAs.

**To Reproduce**
Steps to reproduce the behavior: need to ask Maryland for additional details, if needed.

**Expected behavior**
Messages sent to Maryland should not cause message failures.

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please see email from KLunquest in the ReportStream inbox. The email came in originally on 10/1/21 and additional questions came in on 10/4/21. I responded on 10/4/21 with a clarification question. Will work with SimpleReport to respond to the rest of their questions.

**Comment by mlighdc** [comment]
Responses from the SimpleReport team for SR related questions:
1. Can only rapid antigen results be sent via SR? One of our users did not see a place for PCR tests. 

_SimpleReport will add devices for PCR tests; if it's not in the list, advise facilities to please contact support@simplereport.gov to get it added._

2. We began receiving COVID rapid antigen results from Park Pediatrics earlier this month. However, I am only seeing results from 9/3 on our end, and Cecilia has told me she also reported on 9/4 and 9/10. Were these results received and sent to MDH? 

_In app, I'm seeing 0 results for 9/3, 2 for 9/4, 3 for 9/5, 11 for 9/7, 9 for 9/8, 2 for 9/9 and 1 for 9/10._

**Comment by mlighdc** [comment]
Linking issue to resend Park Pediatrics issue #[2562](https://github.com/CDCgov/prime-reportstream/issues/2562).

**Comment by mlighdc** [comment]
@jbiskie can you let me know when the the fix for the MSH-4 is in production? I should let Maryland know or we need to figure out how to temporarily filter out the ones for Friendship Schools. I have a feeling it is causing problems for them.

**Comment by Adrian-Brewster** [comment]
Issue was addressed with MSH-4 fix.

**Comment by anshulkumar-usds** [comment]
@jorg3lopez have we resent the files to MD. We need to confirm with them on any lingering items.

**Comment by anshulkumar-usds** [comment]
Anshul checked with MD (kristy) on 11/12. Awaiting feedback from state on next steps and if any resubmissions are needed.

**Comment by anshulkumar-usds** [comment]
Per MD on 11/22: 
"I wanted the following removed due to CLIA issues, but also because there are no filler order numbers.
Family & Nursing Care Select LLC
Friendship Public Schools"

**Comment by anshulkumar-usds** [comment]
MD needs us to filter out Family & Nursing Care Select LLC and Friendship Public Schools because they have no accession numbers.

**Comment by mlighdc** [comment]
Thanks @anshulkumar-usds. As you probably know both the facilities mentioned by MD are not SR users. I double checked this evening.

**Comment by anshulkumar-usds** [comment]
Hey @MikeC-A6 requesting your help here. MD is requesting we filter out two facilities from their data feed because these facilities are missing access numbers. Here is their request:

"Is it possible to filter out Friendship Public Schools and Family & Nursing Care Select? We cannot process these as they have no accession number and continue to fail in our system."

I don't see any obvious items missing in COVID metadata table.

**Comment by anshulkumar-usds** [comment]
MD confirmed issue is resolved.
