### ISSUE TITLE
Missing CLIA values for FL-DOH (ImageMover data)

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2548]
FL reported on 10/6 at 8:14 AM EST that they are receiving messages in their ELR primary feed with missing CLIAs. They included accession numbers for the impacted messages. Running a sample set of these accession numbers in Metabase shows the data is coming from ImageMover.

Data coming to ReportStream does contain CLIAs from the sender. However, it seems outbound data to FL-DOH might be missing these values. 

1. Investigate FL outbound file pertaining to these accession numbers to confirm CLIA is missing
2. Determine root cause
3. Work on a solution and set expectations with FL

Accession #
42aeaee6-a2af-443d-b169-6f85cebef0dd
07538551-cea7-4695-bf6b-d5bd460ca180
bdde2e1d-eb30-4ccb-b377-5a822ccb6431
f9d87e43-30fd-4d0a-b152-1e0f0242cb53
3b324c79-e231-4f72-8162-e8f6110d6441
32d2ce2e-e0d1-4e43-bffe-3288ed6aeb0b
4baf0223-538c-4d7c-919b-da9f4a8b7a53
7588c28b-7724-40bc-a9c6-be76009c74eb
8513d1bc-d8b4-4a63-935f-848c79146f61
696bde56-1d20-437b-bbab-c32edbb16bf0
cd628d58-529e-4566-a450-030caea918b7

select testing_lab_clia, *
from covid_result_metadata
where message_id in ('07538551-cea7-4695-bf6b-d5bd460ca180','f9d87e43-30fd-4d0a-b152-1e0f0242cb53')

FYSA: @jorg3lopez @brick-green-agile6 @MauriceReeves-usds

**Comment by Adrian-Brewster** [comment]
Issue was addressed with MSH-4 fix.
