### ISSUE TITLE
FL -  Hillsborough County  - Access to the ReportStream Data Download Site

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#2550]
## Problem statement

Hillsborough County Public Health Department would like access to the ReportStream Data Download site so they can more easily analyze COVID cases in the county.

## What you need to know

-  Met with Hillsborough County team on 10/6/21 to better understand their current situation with one of their LTCF reporters.
- They have already submitted an initial list of users who need access to the RS site.

## Acceptance criteria

- [x] Ability to log into the site and access the files for their county
- [x] Ability to access the data they need
- [x] Ability to download the files for their county

## To do

- [x] Complete RS intake form
- [x] Names and emails of users for account access
- [x] Test and verify
- [ ] Confirm no issues with access or data file

**Comment by brick-green-agile6** [comment]
Hillsborough is available as a selection in the dropdown on reportstream.cdc.gov. But I do not see any reports for that receiver or any other receiver(I must not have permission?). @anshulkumar-usds Can you view reports for receivers on the site?

**Comment by emmastephenson** [comment]
Meeting with Veena tomorrow morning to try and figure out her access issues. I'll update this ticket once that's done.

**Comment by anshulkumar-usds** [comment]
@jorg3lopez Could you please take a look at this. I think we may need to update config settings and change the format from HL7 to CSV. Thanks.

**Comment by anshulkumar-usds** [comment]
Awaiting deployment on 11/4 for conversion to CSV. Expected availability 11/8

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 can you please share updated ETA switching from HL7 to CSV?

**Comment by Adrian-Brewster** [comment]
@anshulkumar-usds to confirm with jurisdiction they have access.
