### ISSUE TITLE
Onboarding OTT

### ISSUE THREAD

**Issue by oifekoya** [CDCgov/prime-reportstream#2555]
We need to ensure that OTT has access to all the platforms and invites, need to be a team member on the sender pipeline team

Checlist:
OTT needs to have the following

- [ ] All meeting invites - Yemi
- [x] Access to the sender pipeline slack channel
- [ ] Access to Github - Jim
- [ ] Access to zenhub - Yemi
- [ ] Assign 1st story - Yemi
- [x] Walkthrough of engineering process/practices - Jim and Carlos

Please update bullets to done, when assigned task is completed.

**Comment by JGreenFearless** [comment]
@jimduff-usds Can we close this now?

**Comment by jimduff-usds** [comment]
closing
