### ISSUE TITLE
(MD) Resend Data for Park Pediatrics up to 9/10

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#2562]
Maryland is unable to located any data from Park Pediatrics before 9/10. Please resend data prior to that data. 

SR Message Counts:
0 results for 9/3,
2 for 9/4,
3 for 9/5,
11 for 9/7,
9 for 9/8,
2 for 9/9 and
1 for 9/10

**Comment by brick-green-agile6** [comment]
@mlighdc @Adrian-Brewster The data was resend today and has been delivered to MD.
