### ISSUE TITLE
MA reporting errors in OBR.22 and MSH.4

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2575]
## Problem statement

MA has reported errors in files delivered from RS due to missing OBR.22 field and missing MSH.4 field.   MA reported data effected on following dates:

## What you need to know

MA alerted data receipt from following days:
9/29/21: 
Specimen ID: e5ff257e-56b2-4a9c-946b-a62cfd45415c
Report ID: 6e6238e0-1ee6-4253-85d7-d77634937416

9/30/21
10/7/21

## Acceptance criteria

Errors in noted fields are resolved and test results resubmitted to state
Confirm with MA on data delivery and acceptance
Notify Janice Granter and Becky Reed of the bug fix: elr.cdsupport@state.ma.us

## To do

Work with @jbiskie to determine fix deployment of direct.schema and resulting effects on MA file delivery

**Comment by Adrian-Brewster** [comment]
@jorg3lopez Has this been completed? Do we need to let the jurisdiction know the issue is resolved?

**Comment by anshulkumar-usds** [comment]
Unblocked: https://github.com/CDCgov/prime-reportstream/pull/2897

Still waiting deployment for MSH-4: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3205

**Comment by anshulkumar-usds** [comment]
Anshul following up with MA on resubmissions

**Comment by Adrian-Brewster** [comment]
Anshul will follow up today.

**Comment by anshulkumar-usds** [comment]
MA confirmed fix is in place.
