### ISSUE TITLE
OH - Clark County Download Site

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2578]
## Problem statement

Clark County Combined Health District in OH is requesting "database access" to ReportStream.

## What you need to know

Clarifying questions have been submitted to understand specific need (ELR or download site), and what rules/logic, if any, need to be applied.

## Acceptance criteria

- Connection (ELR or DS) is setup for STLT
- A first confirmation from STLT is received that all users have access and can download the data

## To do

@anshulkumar-usds to follow up with STLT to understand specific needs
- Determine next steps based on STLT feedback

**Comment by anshulkumar-usds** [comment]
Site setup, user profile in Okta setup and users have access. Need conversion to csv format before closing.
fyi - @jorg3lopez

**Comment by Adrian-Brewster** [comment]
@jorg3lopez Can this be closed out?
