### ISSUE TITLE
Create Draft Team Charter

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2594]

**Comment by HeatherRienks** [comment]
Team Charter can be found on our SharePoint/Teams site in the "Artifacts" folder here: https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FTeam%20Documents%2FExperience%20Team%2FArtifacts&viewid=17db3ff6%2D95c5%2D4562%2Da1f3%2D12b5097b5947
