### ISSUE TITLE
IL - Missing LOINC Codes from ImageMover

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#2596]
## Problem statement

Some messages going to IL do not have a LOINC code in OBX 3.1. Please make sure all tests have the proper LOINC code. See email in the shared support inbox received on **Tue 10/12/2021 2:44 PM Eastern**.

## What you need to know

No need to resend the specific messages.

## Acceptance criteria

- [ ] All messages sent to IL have the appropriate LOINC codes

## To do

- [ ] Investigate why some messages are missing LOINC codes

**Comment by mlighdc** [comment]
FYI - @anshulkumar-usds

**Comment by MauriceReeves-usds** [comment]
@anshulkumar-usds @mlighdc These are more from ImageMover that need to be fixed and resent. They are sending them with test kit name `CStartAntigenSARSCOV` but they should be `CareStart COVID-19 Antigen test*`.

**Comment by anshulkumar-usds** [comment]
Following up with ImageMover to determine root cause and prevent additional issues with test kit names with other states

**Comment by anshulkumar-usds** [comment]
Followed up with IM on 11/2 - awaiting sender's response and fix

**Comment by anshulkumar-usds** [comment]
Confirming with IM if they resubmitted effected records.

**Comment by anshulkumar-usds** [comment]
addressed with the MSH-4 deployment fix from IM
