### ISSUE TITLE
Primary Health - Review Staging Data

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2599]
## Problem statement

RS requested Primary to deliver a test message to staging (no PHI) for further data validation.

## What you need to know

Include a 10 digit string for the CLIA number (MSH-4.2, OBX-15.1, OBX-23.10) and a valid Test Kit Name ID from the LIVD table in OBX-17.1.  Ensure that it's one that reports a 94558-4 result (or whichever value you're using in OBX-3.1).

## To do

- Review staging data from Primary 
- Provide feedback to sender on next steps

**Comment by Adrian-Brewster** [comment]
Just received staging data last week. Joel is planning to look at it this week and provide feedback.
