### ISSUE TITLE
Develop Plan for Creating the ReportStream Service Map

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2600]
## Problem Statement
We need to map out what happens for senders and receivers when onboarding and interacting with RS.

## AC

Break out maps into following categories. Covers user-facing and RS team internal tools/process.

- [x] Solicitation of senders (assuming they're already on board, have been rec'd by juristdiction)
- [x] Account creation
  - [x] Sender
  - [x] Receiver
- [x] Schema approval/flat file validation
  - [x] Data quality checks
- [x] Jurisdictional approval
  - [x] Schema approval (receiver)
  - [x] Schema approval (from senders)
- [x] In production
  - [x] Receiver (state & county)
  - [x] Sender (API vs flat file upload)

How will this actually be used?

- [x] Reference artifact, living doc (mural?)

**Comment by drew-usds** [comment]
Will be working on finishing this tonight/tomorrow AM.

**Comment by drew-usds** [comment]
Created WIP murals with items sketched out in the original Mural. Will use to create more detailed maps for individual steps/features in future issues.

- [Original map](https://app.mural.co/invitation/mural/primedatainput6410/1635273936376?sender=ud6a3555dd1821b626a2b3726&key=98a169ce-ccda-4717-aae5-76fb87804aee)

- High level CSV onboard and upload diagrams: [Mural original](https://app.mural.co/invitation/mural/primedatainput6410/1638564411649?sender=ud6a3555dd1821b626a2b3726&key=a9d245f6-eadc-42df-92ba-7012c4e6ffd1), [CSV dataset presentation (slides 21, 22 screenshots from Mural)](https://app.mural.co/invitation/mural/primedatainput6410/1635273936376?sender=ud6a3555dd1821b626a2b3726&key=98a169ce-ccda-4717-aae5-76fb87804aee)
Solicitation of senders (assuming they're already on board, have been rec'd by juristdiction)
 
- Account creation: Sender, Receiver
- Schema approval/flat file validation
- Data quality checks
- Jurisdictional approval: Sender, Reciever
- Schema approval: Sender, Reciever
- In production: Sender (API vs flat file upload), Receiver (state & county)

**Comment by rachelhanster** [comment]
Hey @drew-usds. I took a look at Broken-out detailed maps (WIP). What's the next step to turn work in progress detailed maps to be referential material?
For example with Account creation: in absence of CRM, where are current bottlenecks with account creation?
