### ISSUE TITLE
CA - San Benito County - Download Site Setup

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#2620]
## Problem statement

San Benito Public Health Dept would like access to the RS Download site.

## What you need to know
Please see email in the shared inbox for additional details. 2 - 3 users may need access.

## Acceptance criteria

- [ ] San Benito Public Health Dept users are able to log in, view, and download data for their jurisdiction.

## To do

- [x] Send intake form and terms of service

- [x] Receive completed intake form

- [x] Set up users accounts

- [x] Test account access and functionality

**Comment by anshulkumar-usds** [comment]
Site setup, user profile added and activated in Okta. Awaiting conversion to csv
