### ISSUE TITLE
Content on how to successfully use daily-data or download site

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#2621]
## Problem statement

As an end user at a public health authority, I want to know how to access and use ReportStream to view and download data.

## What you need to know

Currently, there is limited info for potential and current end users to see what functionality is available via the daily-data page and how to use it.

## Acceptance criteria

- [x] prospective and current users know what is the daily-data page
- [x] Add a de-ID'd screenshot of where download links are when logged in. Add it to `https://reportstream.cdc.gov/getting-started/public-health-departments/data-download-guide #accessing-data`
- [x] If users need help with this feature, direct them to contact via email

## To do
- [x] Learning content and instructional design for how to use Daily Data page (send off to UI when done)

**Comment by HeatherRienks** [comment]
@mlighdc  - Please provide us with the 3 counties that requested this so that we can ensure we follow up with them directly once this has been completed. Thanks!

**Comment by BerniXiongA6** [comment]
Notes for design sync: 
**Current state:**
- In Daily Data view, user can see Report Id, Date sent, Expires, Total tests, and link to HL7 batch
- In Report Details view, user can see Facility, Location, CLIA#, Total tests, Total positive, and an option to download the batch in HL7 format

**Future state (based on this ticket):**
- how to download data as CSV file (BX question: is this even possible in current state?)
- public-facing how-to guide (instructing user how to use Daily Data and Report Details page features)

**Comment by BerniXiongA6** [comment]
[Here's the link in SharePoint](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Website%20Copy%20Writing/How%20to%20use%20ReportStream%20Daily%20Data%20and%20Report%20Details.docx?d=wb1aca5bdef314598895e9d715aaf958a&csf=1&web=1&e=xG19BE) to see the current work in progress. Should be ready for Review/QA by Friday AM, so it can be DONE before sprint end.

**Comment by BerniXiongA6** [comment]
All content and learning artifacts created for this ticket are [saved here in SharePoint](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Website%20Customer%20Success%20Center/How%20to%20Use%20ReportStream%20Daily%20Data%20and%20Report%20Details?csf=1&web=1&e=KyngEc). This ticket has moved to Review/QA for UI to take a peek.

**Comment by HeatherRienks** [comment]
@drew-usds and @a-chappelear - would you please take a look at this ticket today so we can close out this sprint?
Thx!
cc: @RakshindaAslam

**Comment by drew-usds** [comment]
We'll make a UI/frontend/implement-this ticket to follow on to this and then close it.

**Comment by BerniXiongA6** [comment]
Closing this ticket now that [UI ticket # 5293 ](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5293)is created. cc: @drew-usds @RakshindaAslam
