### ISSUE TITLE
WA - Result with incorrect specimen collection date 

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#2622]
## Problem statement

WA state was recently notified of an ELR from USDS that had an incorrect specimen collection date. The collection date on the record is 10/3/2021, however, the result was processed by our system on 10/2/2021. 

Please investigate this record and resend the result with a corrected specimen collection date?

The filler order number on this record is 2d148d39-4949-4f64-a214-cc0a0447cf4e.

If additional information is needed, please let me or Anshul know and we can request from WA state.

## What you need to know

Issue email received on Thursday, October 14, 2021 4:55 PM Eastern

## Acceptance criteria

- [ ] To be completed by RS team

## To do

- [ ] To be completed by RS team

**Comment by mlighdc** [comment]
@mauricereeves would it be possible to take a quick look at this issue for WA to see if it is a quick resolution? Or if you can provide a quick update on when you think can be resolved. Thanks!

**Comment by MauriceReeves-usds** [comment]
@mlighdc yes I will take a look tomorrow morning.
