### ISSUE TITLE
VT - OTC Feedback Follow-Up

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#2623]
## Problem statement

Vermont has provide feedback regard our OTC proposal. Their most recent feedback was on 9/17/21 and it appears no one from our side responded.

Currently, the OTC feed is being directed to Vermont’s secondary feed and requires manual review and hand-entry due to the issues with the HL7 message. There issue is outline in the email string sent on Monday, October 11, 2021 10:34 AM.

## What you need to know

Vermont is looking for an update on the OTC. Please see email and my reply on Friday, October 15, 2021 12:35 AM for their detailed feedback.

The desired (long term) outcome is for VT to accept the OTC results as part of their primary feed.

## Acceptance criteria

- [ ] TBD

## To do

- [ ] Provide Vermont with an update on the OTC feed.

**Comment by anshulkumar-usds** [comment]
Plan communicated to VT:

Priority
•	Test message delivery by end of next week (11/19)

After test delivery
•	Review and re-adjust to feedback as needed
•	Build automated process to deliver production OTC data (completed by 12/3)

**Comment by anshulkumar-usds** [comment]
Anshul to get back to VT, need to reset timelines - work with 12/3 for first sample file

**Comment by anshulkumar-usds** [comment]
Informed VT about our revised timeline. Moving to product backlog.

**Comment by anshulkumar-usds** [comment]
We expect to deliver first round of results by 12/3.
Ultimately, the outcome desired by VT is that we reach stable state with the OTC data, and it can be routed to their primary feed.

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 delivered first round of test files to VT on 12/2 - awaiting feedback from VT.

**Comment by Adrian-Brewster** [comment]
Feedback received last Friday.  Brick will review feedback.

**Comment by anshulkumar-usds** [comment]
Call with VT on 1/21:
1.	OTC Defaults
a.	VT’s preference is to treat all results as OTC when the associated CLIA is not legitimate. This includes “SA” for self-administered results
b.	An interim CLIA entered by facilities in SimpleReport will be treated as a valid CLIA (47ZXXXXXXX)
c.	Add a placeholder address under ordering facility address 
d.	MSH-4 sending facility should be populated with a placeholder: PRIME-OTC

**Comment by anshulkumar-usds** [comment]
1/25: For MSH-4, VT checked with RS if we can create a standard namespace that is 10 chars long. This limit should only apply to OTC results. **The existing truncation logic for SimpleReport facilities is working as expected and not causing any issues – no changes needed there.**

1/25: @brick-green-agile6  checked with VT and proposed the following value for MSH-4. Waiting for VT to confirm.
**CDC PRIME OTC^0OCDCPRIME^CLIA**

**Comment by anshulkumar-usds** [comment]
1/28: VT's preference for MSH-4 is to use "PRIME OTC" as the namespace so that it's less than 10 chars.

**Comment by anshulkumar-usds** [comment]
Notes from slack: https://usds.slack.com/archives/C01HFHPNJEL/p1643644886999509?thread_ts=1643644870.034559&cid=C01HFHPNJEL

VT has requested that all OTC results going to their jurisdiction use these values:
 
Message Header and Other
Sending Facility Name (MSH-4.1) = “PRIME OTC“
Sending Facility ID (MSH-4.2) = “0OCDCPRIME”
All other CLIA fields Put same as MSH 4.2
Message Profile Identifier (MSH 21.1) = “PHLabReport-NoAck”
Result Status (OBX-11, OBR-25) = “R”
NTE = Send organization name 
 
Ordering Facility, Facility Name, Address Defaults 
Ordering Provider First Name (ORC-12.3/OBR-16.3) = “SA” 
Ordering Facility Name (ORC-21.1) = “SA” 
Ordering Facility Address (ORC-22) = “11 Fake AtHome Test Street^^Yakutat^AK^99689^^^^02282” 
Ordering Facility Phone (ORC-23) = “^^^^111^1111111”
Performing Facility Name (OBX-23.1) = “SA” 
Performing Facility CLIA (OBX-15.1 and OBX-23.10) = ”00Z0000014”
Performing Facility Address (OBX-24) = “11 Fake AtHome Test Street^^Yakutat^AK^99689^^^^02282” 
Additional process request from VT:
1.    The default values should be applied but the results should only be sent to the test receiver for VT. VT would then work to confirm the message content prior to approving the data for production.
Process Steps
Check all OTC fields (is_otc, is_home, is_serial, is_unproctored)
Ensure receiver wants default values to be used
Apply Default values to message
Route messages to receiver

**Comment by brick-green-agile6** [comment]
Sent two more test messages to VT for review

**Comment by anshulkumar-usds** [comment]
3/17: On 3/16, VT wrote back with the following:
"now that we know the defaults are working in test messages, what are the next steps toward implementation?"
@brick-green-agile6

**Comment by brick-green-agile6** [comment]
code has been merged and will be deployed on 3/22. Asked VT what data they would like in the three feeds(primary, secondary, otc)

**Comment by brick-green-agile6** [comment]
From VT:
![image.png](https://images.zenhubusercontent.com/60d23d7dcaf07751be9205b6/2d4f8f77-858a-455c-98e1-28bfecb7d903)

This is possible. Essentially making a primary and secondary OTC feed. But we would need to explicitly allow senders for both feeds which means maintaining the lists as new senders are added that could possibly transmit OTC. 

@anshulkumar-usds, I feel like other STLTs have mentioned wanting similar capabilities(to test senders as they come on board). I understand Theresa's argument so I'm happy to take that responsibility for VT for the time being. But i think we need a stronger policy on this long term. What do you think?

**Comment by brick-green-agile6** [comment]
@anshulkumar-usds I think it's finally time to close this issue. The bulk of the work is done. So now it's on to new work. What do you think?

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 agreed; we can close this. Thank you for the awesome work and support you provided to VT!
