### ISSUE TITLE
AZ - Missing Records and Other Data Issues

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#2631]
## Problem statement

AZ contacted us (Friday, October 15, 2021 11:22 AM) with issues they are experiencing:

> In today's file we are again receiving records without a Lab_Name populated. These appear to be  a different facility from the ones listed in my last email as the CLIA is different. We also are not receiving Specimen_IDs for these records either. Both of these fields are required fields for processing. Please resolve. See screenshot below

![image.png](https://images.zenhubusercontent.com/5eaf8fc6e9ce8c652d0f1cb4/d3407d35-61e2-4a20-9a58-1723e62e04c8)

Removing the comma from the school name

> "St Ambrose Catholic School**,**". 

## What you need to know

Please see email from AZ on Friday, October 15, 2021 11:22 AM. For additional details

## Acceptance criteria

- [x] Remove comma from school name

- [ ] Lab name should populate as expected

## To do
- [x] Confirm with the SimpleReport team that comma has been removed from the school name - confirmed on 10/15/21

- [ ] Investigate while Lab name is not being populate and identify resolution

**Comment by MikeC-A6** [comment]
@MauriceReeves-usds - I verified in Metabase that all records received into RS in the last 30 days have the testing lab name populated where Ordering_Facility_Name `contains` "St Ambrose Catholic School".  This does not appear to be an issue with the inbound data.

**Comment by anshulkumar-usds** [comment]
Assigned to @jorg3lopez

**Comment by MikeC-A6** [comment]
@jorg3lopez - I did some investigation on this CLIA.  Up until 9/11/2021, the lab name was not sent for this CLIA.  On 9/13/2021, lab name is populated on the inbound reports.  This is confusing because AZ is stating that they didn't receive the lab name on 10/15.  It looks like they are referring to the 8 records with a created date of 10/14/2021.  Are we able to check the outbound file and determine why Testing Lab name didn't populate in OBX-23-1?

**Comment by Adrian-Brewster** [comment]
@jorg3lopez Can you provide an update on this?

**Comment by anshulkumar-usds** [comment]
Fix merged and deployed: https://github.com/CDCgov/prime-reportstream/pull/2956/files

Have not hear of any new issues from AZ.
