### ISSUE TITLE
MA - Missing Filler Order Number in ORC-3.1 and ORC-2.1

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#2634]
## Problem statement

In Wednesday’s file there was an error caused by a missing Filler Order Number in ORC.3. Can you please review, edit and resubmit if necessary? 

Error: Expected Required field Unique ID (ORC.3.EI.1 of type ST) is not found.
Error: Filler Order Number (ORC.3 of type ORC.3.EI) value is invalid.
Message rejected.

## What you need to know

After further conversations with state here is the proposed path:
ORC-3-1: We do need this field to be populated. It is a required data element in our system, used to represent a unique identifier (specimen/accession number).

ORC-2-1: This is not a required data element for us, but please do populate it if the information is available.   

## Acceptance criteria

The updates to ORC-3.1 and ORC-2.1 are completed

## To do

- For ORC-3.1, please use the accession ID. MA does not want this field to be blank
- For ORC-2.1, this is an optional field. Leave it blank if no data is available.

**Comment by Adrian-Brewster** [comment]
Waiting on message confirmation from state jurisdiction

**Comment by anshulkumar-usds** [comment]
@jorg3lopez will deliver updated file to MA

**Comment by Adrian-Brewster** [comment]
Jorge sent test message on 11/24.  Waiting on feedback from MA.  Jorge will send accession to Becky to follow up.

**Comment by mlighdc** [comment]
@jorg3lopez I just followed up on the email that I sent the MA team on 11/24. It probably got missed during the holiday week. Thanks.

**Comment by anshulkumar-usds** [comment]
MA confirmed test files looks good.
@jorg3lopez please send messaged to the prod directory.

**Comment by anshulkumar-usds** [comment]
12/20: Checking with MA for any next steps

**Comment by anshulkumar-usds** [comment]
@jorg3lopez MA requested following message Id to be resent after fixing ORC-3:
d48bf41a-b686-42bd-8c25-17e0f91591c1

**Comment by anshulkumar-usds** [comment]
@jorg3lopez can you please check if the message ID above was resent to MA?

**Comment by jorg3lopez** [comment]
@anshulkumar-usds the above message id was resent on 12-28-2021.
File name: 
prime-20211228213300

**Comment by jorg3lopez** [comment]
@anshulkumar-usds It seems that message id has not been sent yet. Is that a message id? I'm not finding it in our database.

**Comment by anshulkumar-usds** [comment]
'd48bf41a-b686-42bd-8c25-17e0f91591c1

@jorg3lopez zenhub has been snipping a char off the message ID. This is the right one.

**Comment by jorg3lopez** [comment]
@Adrian-Brewster @Adrian-Brewster Submitted test result to MA with specimen id of `d48bf41a-b686-42bd-8c25-17e0f91591c1` 
File name: prime-20220131215206
