### ISSUE TITLE
OH - Missing LOINC Codes from ImageMover

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#2635]
## Problem statement

More messages came through today without any LOINC codes.  **Please resend them correctly ASAP to prevent further delay.**

4a89300e-e979-4874-91d6-95d17533bd83
e892cf7e-6b16-4f07-906d-ddc901a7fc2f
48a7e06f-bbe4-4365-8e73-9c06e6b1d481
4efea813-d66f-4aae-90db-8faa6f59a006
3bd3a8f2-f90c-49d1-9032-3081fc8e9aa3
2dcdf353-e2c6-4458-96b6-89df232ba279

## What you need to know

 Please refer to email in shared inbox received Fri 10/15/2021 5:53 PM

## Acceptance criteria

- [ ] Messages are corrected and resent with LOINC

## To do

- [ ] ...

**Comment by MauriceReeves-usds** [comment]
This ticket is waiting on ImageMover to resubmit the records.

**Comment by mlighdc** [comment]
@anshulkumar-usds we received another email regarding a missing LOINC code (date of email - Mon 11/1/2021 10:44 AM)

0b796db7-c769-440a-8292-007fee90d00f

**Comment by anshulkumar-usds** [comment]
Followed up with IM on 11/2 - same issue with IL - awaiting sender's response and fix

**Comment by anshulkumar-usds** [comment]
On 11/2 OH reported another message with missing LOINC: 
0b796db7-c769-440a-8292-007fee90d00f

**Comment by anshulkumar-usds** [comment]
On 11/15 at 8:49 AM, OH reported additional messages where the LOINC code is missing.

Message IDs:
69e18868-3d96-43e0-bc99-656dd3f8a1b4
2e2fe3ef-233a-4213-a354-cfd1c1c971d2

**Comment by anshulkumar-usds** [comment]
Shared the messages IDs reported by OH on 11/15 with ImageMover.

**Comment by anshulkumar-usds** [comment]
Another one reported on 11/16:

File: CDCPRIME_20211116001547_b733591bed0747dc86d5be5c5a9f258f
Message Control ID: c138841d-66b8-49a4-919f-b5578d561660
Specimen ID: c138841d-66b8-49a4-919f-b5578d561660

**Comment by anshulkumar-usds** [comment]
Escalated to Imagemover, and checking with OH which/if they need all/some message to be resent after the fix from sender.

**Comment by anshulkumar-usds** [comment]
OH confirmed they need all effected messages to be resent. Once I hear back from IM on a fix, a consolidate list of message IDs will be shared with IM for resubmission.

**Comment by anshulkumar-usds** [comment]
Imagemover confirmed they have corrected the issue on their side. Re-shared message IDs with sender so that resubmission can happen.

**Comment by anshulkumar-usds** [comment]
Anshul checking with OH to see if they have any specific instructions for resubmission: can we use the same specimen IDs to resubmit.

**Comment by anshulkumar-usds** [comment]
OH's wants all messages delivered with a new message ID and a valid LOINC code. Imagemover has been made aware and will provide Anshul with a list of message IDs for follow up.

**Comment by anshulkumar-usds** [comment]
From Imagemover on 12/1:

Ok, we compiled a report for staging and sent it along just now.  Can you please validate that the submission in staging is valid, or at least that the following fields are correct?
•	testId is unique and is the original id appended with a datetimestamp for uniqueness
•	correctedTestid contains the original Id for the record
Below is the response I received from the send.  Perhaps the Id returned is the easiest way to view the transaction.  These samples happened to be for an organization in WI vs OH but just trying to prove out the process here.  Please let us know if this successfully corrects the previous transactions and we'll do the same for the dataset in OH for production.

{
  "id" : "deeed200-c90d-41ce-9cf4-151bdbe34ba7",
  "timestamp" : "2021-12-01T17:21:10.572587Z",
  "topic" : "covid-19",
  "reportItemCount" : 6,
  "destinations" : [ {
    "organization" : "Wisconsin Department of Public Health",
    "organization_id" : "wi-dph",
    "service" : "elr",
    "sending_at" : "2021-12-01T12:22-05:00",
    "itemCount" : 6
  }, {
    "organization" : "HHSProtect",
    "organization_id" : "hhsprotect",
    "service" : "elr",
    "sending_at" : "2021-12-01T12:30-05:00",
    "itemCount" : 6
  } ],
  "destinationCount" : 2,
  "warningCount" : 1,
  "errorCount" : 0,
  "errors" : [ ],
  "warnings" : [ {
    "scope" : "REPORT",
    "message" : "Missing 'orderingFacilityEmail' ('ordering_facility_email') header"
  } ]
}

Here are the original testIds in that dataset:
7fb4f7b2-7290-482c-a1a4-3191be5e7523
17e66651-db0d-4668-ac81-7cbf0dcb2d35
2ab54d9f-eecb-4cec-95c1-b3a8fb38d4cc
26a8274e-ee2f-487d-ab36-3914aff1db83
13ec79c5-d308-4160-a552-5ea0eef2b67e
5914020c-4fc8-4dd7-b0f1-126eaad13a34

**Comment by anshulkumar-usds** [comment]
@jbiskie can you please review sample data from ImageMover and share your findings?

**Comment by anshulkumar-usds** [comment]
@jbiskie can you please share an update on this?

**Comment by jbiskie** [comment]
Going to see if devops can help us at all...  I've worked with Jorge and Brick so far, and no one can get into the staging blobstore.

**Comment by anshulkumar-usds** [comment]
@jbiskie any luck accessing the data?

**Comment by anshulkumar-usds** [comment]
@jbiskie Jim shared the data files from Imagemover over email on Friday morning. And based on his instructions, I'm pretty sure I have access to the blob-store as well. Please take a look at the data.

**Comment by jbiskie** [comment]
Reviewing and will provide feedback to ImageMover today

**Comment by jbiskie** [comment]
@anshulkumar-usds Feedback to ImageMover will be tomorow (12/21), I'm in meetings until the end of my day today.

**Comment by anshulkumar-usds** [comment]
anshul to fu with IM

**Comment by anshulkumar-usds** [comment]
ImageMover noted on 1/7 that they will se sending additional records to staging for review. @jbiskie

**Comment by anshulkumar-usds** [comment]
ImageMover noted the issue was resolved between the client facility and OH. Closing.
