### ISSUE TITLE
Organization Requests Support Online (Github Issue Forms)

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2637]
## Problem Statement
As an Organization that uses ReportStream, when I have a problem with ReportStream, I would like to easily be able to request assistance from the support team so that I can work towards solving my problem.

## Background Info
- When a RS user has an issues with our platform, the only way currently to notify the development/product team is via email - directed personally to team members, or to the share mailbox. Managing inboxes is not fun for anyone, and leads to backlogs of email management and customer communication delays.
- Let's explore creating issue forms in Github. @kjt9cc suggested this: https://beyondco.de/blog/github-issue-forms; This may also auto-tagging of some sort, and will remove the intermediate step of someone in the O&O team or PRIME Ops team having to create tickets.
- We are exploring alternatives using CRM, but actual implementation of that is months away (potentially).
- FYSA: @mlighdc @kjt9cc

**Comment by loripusey** [comment]
This issue has been turned into an Epic: [https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/2906](url)
