### ISSUE TITLE
NJ - Errors in ELR File 20211017

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2641]
## Problem statement

NJ is reporting errors in file delivered on 10/17/21

## What you need to know

Please note the errors below in your ELR File: covid-19-ea24033a-0e0a-46df-ae87-ae2166264db5-20211017131515.hl7

File ID: 2620742
Message(s) within the file "CDC_PRIME_covid-19-ea24033a-0e0a-46df-ae87-ae2166264db5-20211017131515.hl7" were in error on route (2) ELR-Validate 2.5.1
Sender	Message Control ID	Location of Error in Message	Error Description
CDC PRIME - Atlanta,	99748142-d881-4feb-8ee1-48f6096ca368	PATIENT_RESULT[0].PATIENT.PID.PatientIdentifierList[0].IdentifierTypeCode	Required field missing
CDC PRIME - Atlanta,	99748142-d881-4feb-8ee1-48f6096ca368	PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.PlacerOrderNumber.EntityIdentifier	Required field missing
CDC PRIME - Atlanta,	99748142-d881-4feb-8ee1-48f6096ca368	PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.FillerOrderNumber.EntityIdentifier	Required field missing
CDC PRIME - Atlanta,	99748142-d881-4feb-8ee1-48f6096ca368	PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBR.PlacerOrderNumber.EntityIdentifier	Required field missing
CDC PRIME - Atlanta,	99748142-d881-4feb-8ee1-48f6096ca368	PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBR.FillerOrderNumber.EntityIdentifier	Required field missing
CDC PRIME - Atlanta,	99748142-d881-4feb-8ee1-48f6096ca368	PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBR.ResultsRptStatusChngDateTime.Time.Year	Required field missing
CDC PRIME - Atlanta,	99748142-d881-4feb-8ee1-48f6096ca368	PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBR.ResultStatus	Required field missing
CDC PRIME - Atlanta,	99748142-d881-4feb-8ee1-48f6096ca368	PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[0].OBX.ObservationResultStatus	Required field missing
CDC PRIME - Atlanta,	99748142-d881-4feb-8ee1-48f6096ca368	PATIENT_RESULT[0].ORDER_OBSERVATION[0].SPECIMEN[0].SPM.SpecimenID.FillerAssignedIdentifier.EntityIdentifier	Required field missing

**Comment by Adrian-Brewster** [comment]
@jorg3lopez have these messages been resent?

**Comment by jorg3lopez** [comment]
I will work on this tomorrow, Wednesday (11/24/2021).

**Comment by anshulkumar-usds** [comment]
NJ does not need us to resubmit files. ORC-2.1 and ORC-3.1 fix in place in prod.
