### ISSUE TITLE
[Draft] SecurityHeaders for React client server

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#2648]
Note: Content-Security-Policy can have the line feeds removed (aka combine into a single, long line). It's just more human readable in the format below:

```
"SecurityHeaders": {
 "Content-Security-Policy": "
    default-src 'self';
    script-src 'self'
      https://hss-prime.okta.com
      https://global.oktacdn.com
      https://www.google-analytics.com
      https://*.in.applicationinsights.azure.com;
    style-src 'self' 'unsafe-inline'
      https://global.oktacdn.com
      https://cdnjs.cloudflare.com;
    frame-src 'self' https://hhs-prime.okta.com;
    img-src 'self' https://hhs-prime.okta.com https://reportstream.cdc.gov data: ;
    connect-src 'self'
      https://www.google-analytics.com
      https://*.in.applicationinsights.azure.com
      https://hhs-prime.okta.com
      https://staging.reportstream.cdc.gov/api/
      https://staging.prime.cdc.gov/api/ ;
    ",

    "X-Content-Type-Options": "nosniff",
    "X-Frame-Options": "DENY",
    "X-Permitted-Cross-Domain-Policies": "master-only",
    "X-Xss-Protection": "1; mode=block;",

    "Referrer-Policy": "origin-when-cross-origin",
    "Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",

    "x-azure-ref": null,
    "x-ms-request-id": null,
    "x-ms-version": null,
  },

```
The last few _remove_ the header that Azure adds.

Other possible items for `Content-Security-Policy`? Not sure how much security they actually add based on defaults.
```
  script-src 'self'
    'nonce-{nonce}'
    https://www.google-analytics.com/analytics.js;

  font-src 'self' data: ;

  object-src 'none';

  base-uri staging.reportstream.cdc.gov 'self';

  frame-src 'self';

  frame-ancestors 'none';

  form-action 'self';

  manifest-src 'self';

  media-src 'self';

  worker-src 'none';
```

**Comment by cwinters-usds** [comment]
A few things:
1. Are we planning on using these rules as-is for all environments? Or are we going to templatize/customize per environment? For example this would impact `connect-src` which only explicitly mentions staging.
2. Are we or any of our dependent services using web workers? (see: [child-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/child-src)
3. Based on my understanding we don't need to explicitly specify rules that don't modify what's in `default-src` -- e.g., `media-src 'self'`

**Comment by cwinters-usds** [comment]
Just some implementation notes:

1. There is no way to set HTTP headers on the storage account ([Azure docs here](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website#adding-http-headers))
2. There's a way to do this via the Front Door configuration ([Azure docs here](https://docs.microsoft.com/en-us/azure/frontdoor/front-door-security-headers)) However, note that Terraform does not yet support this -- see [this issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/7455) -- so we'd have to add manually. Keep an eye on the issue comments and workarounds for ensuring tf doesn't remove manual configuration. Not sure if it's necessary, but good to know.
3. We can probably also do this in Akamai, but the fact that this might be done in the future in terraform config makes me lean toward that.

**Comment by sean-usds** [comment]
doing this manually via the Front Door config makes sense to me! maybe we should just have a Readme somewhere in our repo with the configurations so that we at least have version history of any changes? we'd have to make sure the Readme stays up to date, but I don't imagine changes to SecurityHeaders will happen too frequently

**Comment by cwinters-usds** [comment]
We may make updates to this later, but the basics are working now in the Front Door.
