### ISSUE TITLE
Onboarding PMG-AZ

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#2652]
Onboarding PMG-AZ from California for the CSV Uploader Pilot.

**Acceptance Criteria:**
1. PMG-AZ is configured as a CSV Sender in ReportStream.
2. PMG-AZ is a one-off Sender configuration.  There will be one schema under /schemas/non-standard/

**Assignees & Labels**
rhood23699 - Rick Hood   /  Onboarding & Ops

**Comment by anshulkumar-usds** [comment]
@MikeC-A6 can you please update status?

**Comment by rhood23699** [comment]
PMG is moving from CSV Pilot to RestAPI onboarding.  Anshul, we take over this project and create the necessary tickets.
