### ISSUE TITLE
SafeHealth - Staging Feedback

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2653]
## Problem statement

SafeHealth submitted dummy data for our review and validation on 10/19. Please review and provide feedback to sender. Sender also has open questions regarding data content and format.

## What you need to know

Open Queries:

1.	As discussed on the call, these Tests are performed “At Home” setting. So, sending all the “PerformingFacility” details as null. The acknowledge is showing them as warnings. Are you expecting any specific values for “At Home” testing for the PerformingFacility details?
2.	We filled the OrderingProvider details, but left the “OrderingFacility” as blank.

Other than items related to “PerformingFacility” and “OrderingFacility, rest fields are taken care of.

## Acceptance criteria

Sender's questions are resolved

## To do

- Please review sender data and open question and reply

**Comment by anshulkumar-usds** [comment]
@jbiskie submitted feedback to sender, awaiting feedback.

**Comment by anshulkumar-usds** [comment]
@jbiskie Safehealth submitted new test messages to staging on 12/7. Can you please review and offer feedback?

Today we have submitted a couple of messages to the sandbox environment and got a successful response as well. Below are the success ID's returned by the API which can be used to track the data:
885d90a8-1171-49ef-9b6a-cb33ae4e78fb
6b06ae92-9840-42ec-b098-8767754ab190

**Comment by anshulkumar-usds** [comment]
Blocked: We have requested the sender to send us sample data over email until access is provisioned to the Azure data-store.

**Comment by anshulkumar-usds** [comment]
@jbiskie Can you please let Safehealth advise on next steps. Looks like they sent over sample data and looking for feedback.

**Comment by anshulkumar-usds** [comment]
@jbiskie SafeHealth reported on 12/27 specimen source to new records for your review. Message IDs noted below:

8eec76ac-8d2c-41e2-84d9-bb5b7cdeca6c
abfef98a-3204-4bf5-8e29-fde988b4f5bf

**Comment by anshulkumar-usds** [comment]
@jbiskie SafeHealth is also concerned about lack of warnings for missing fields. Please have a look and advise them on next steps.

**Comment by anshulkumar-usds** [comment]
Last updates from sender on 1/21 indicates successful submissions to our prod env (in test mode). Please check if they can be promoted to prod.

**Comment by anshulkumar-usds** [comment]
Sender in production, test mode. 

Signed TOS already. Anshul to check with sender on state validation.

**Comment by Adrian-Brewster** [comment]
Safehealth is onboarded in health. They have a prod release on their side so we should start seeing data come in this week

**Comment by anshulkumar-usds** [comment]
SafeHealth data in prod metabase as of 2/8. Closing this. Thanks @jbiskie
