### ISSUE TITLE
LA - MSH-4 Errors

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2666]
## Problem statement

LA is reporting issues/errors with MSH-4 field in recent messages. This is possibly related to the dependency mentioned on the ticket.

## What you need to know

From LA:

Louisiana is receiving some messages where: 
•         MSH 4.1 contains an NPI number instead of the name, 
•         MSH 4.2 is blank rather than containing a CLIA number, and
•         MSH 4.3 is blank.  
 
Here are the facilities that have this issue so far:
MSH 3.1	MSH-4.1	ORC-21
CDC PRIME - Atlanta, Georgia (Dekalb)	1205894995	Bella Clinic - BRGP
CDC PRIME - Atlanta, Georgia (Dekalb)	1376520650	Primary Care - BRGP
CDC PRIME - Atlanta, Georgia (Dekalb)	1346563020	Denham Clinic - BRGP
CDC PRIME - Atlanta, Georgia (Dekalb)	1063516151	Port Allen - BRGP
CDC PRIME - Atlanta, Georgia (Dekalb)	1255545752	BRGP - Central
CDC PRIME - Atlanta, Georgia (Dekalb)	1073596094	Shenandoah - BRGP
CDC PRIME - Atlanta, Georgia (Dekalb)	1417126277	BRGP - Zachary
CDC PRIME - Atlanta, Georgia (Dekalb)	1346563020	O'Neal Clinic - BRGP
CDC PRIME - Atlanta, Georgia (Dekalb)	1972623049	East Jefferson Ear Nose and Throat
CDC PRIME - Atlanta, Georgia (Dekalb)	1437325206	Heal 360
CDC PRIME - Atlanta, Georgia (Dekalb)	1184159501	Bluebonnet Family Clinic - BRGP
CDC PRIME - Atlanta, Georgia (Dekalb)	1053459644	BRGP- Ascension

## Acceptance criteria

- LA verifies that issue is no longer present
- Message with errors are resubmitted and validated by the state

## To do

- Please investigate root cause and reply to state with next steps

**Comment by Adrian-Brewster** [comment]
@jorg3lopez Can this be closed, also?

**Comment by anshulkumar-usds** [comment]
Continues to be blocked by the fix needed for MSH-4.

**Comment by mlighdc** [comment]
LA sent a list of data where MSH-4 values are blank or contain and NPI number in MSH 4.1, ORC-21 (usually populated, but also some blank), and MSH-10 (Message Control id) for identification.  Please let them know if any additional information is needed to resend these.  It looks like there are 700+ messages that need to be resend.

Also, please let LA know when messages will be resend.

**Comment by Adrian-Brewster** [comment]
MSH-4 Issue will be addressed with Rick Hawes deployment tomorrow. Then we just need to work on resubmissions. @jorg3lopez

**Comment by jorg3lopez** [comment]
@anshulkumar-usds Do we have the specimen IDs for the failed messages?

**Comment by anshulkumar-usds** [comment]
@jorg3lopez see attached messages that need to be resent:
[https://app.zenhub.com/files/304423150/dd1bbe72-9a44-4087-bed9-9e7c1c2e2f72/download](https://app.zenhub.com/files/304423150/dd1bbe72-9a44-4087-bed9-9e7c1c2e2f72/download)

**Comment by anshulkumar-usds** [comment]
@jorg3lopez please resubmit files to LA

**Comment by Adrian-Brewster** [comment]
Ready for resubmissions @jorg3lopez

**Comment by anshulkumar-usds** [comment]
Code in prod; @jorg3lopez need to resubmit.

**Comment by jorg3lopez** [comment]
@anshulkumar-usds @Adrian-Brewster I'm working on it.

**Comment by anshulkumar-usds** [comment]
@jorg3lopez any update on this?

**Comment by anshulkumar-usds** [comment]
Anshul to check with LA if resubmissions are still needed

**Comment by anshulkumar-usds** [comment]
@jorg3lopez LA still wants the resubmissions completed. They are requesting that if the files are sent in batches, that the batch size does not exceed 1000 kb.

**Comment by jorg3lopez** [comment]
@anshulkumar-usds Understood, I'll keep the files below 1000kb.

**Comment by anshulkumar-usds** [comment]
@jorg3lopez any update?

**Comment by jorg3lopez** [comment]
Resubmission of test results is complete, 272 total test results.  (02/09/2022)
File name:
cdcprime_cdcprime_laoph_testing_testing_20220208202907
cdcprime_cdcprime_laoph_testing_testing_20220208203005

**Comment by anshulkumar-usds** [comment]
2/9: Checking with LA, awaiting response

**Comment by anshulkumar-usds** [comment]
2/15: @jorg3lopez reported that the remainder messages have missing performing facility name and/or ordering facility name from ImageMover. Please share these message IDs and I will work with sender to get these resubmitted.

Also, ticketed the larger investigation into data quality here: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4385

**Comment by jorg3lopez** [comment]
@anshulkumar-usds This file contains the message_ids that need to be resubmitted (LA).[https://app.zenhub.com/files/304423150/4f1feb4a-93ba-4395-92f3-46d1e069cdac/download](https://app.zenhub.com/files/304423150/4f1feb4a-93ba-4395-92f3-46d1e069cdac/download)

**Comment by Adrian-Brewster** [comment]
Adrian emailed list of resends to ImageMover

**Comment by Adrian-Brewster** [comment]
@anshulkumar-usds will follow up with ImageMover to make sure Resends were completed.
