### ISSUE TITLE
Add the ability to stop a retry sequence 

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#267]
**Is your feature request related to a problem? Please describe.**
Need to add a stop retry procedure for a task, for a destination, and all tasks

**Describe the solution you'd like**
A method only people with Azure account access can use. 

**Describe alternatives you've considered**

**Additional context**
This feature idea comes out of today's incident

**Comment by jimduff-usds** [comment]
Closing as we haven't seen a need for this.  Feel free to reopen if a need arises.
