### ISSUE TITLE
Store FHIR file in blob storage

### ISSUE THREAD

**Issue by clediggins-usds** [CDCgov/prime-reportstream#2684]
Store the generated FHIR file in blob storage in a FHIR folder, with sub folders per recipient within the FHIR folder. For this step, each generated FHIR file will have a direct mapping to one internal csv file.

Test: verify the file is generated and saved in blob storage.

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/2684?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @oslynn @smythe5 @whytheplatypus

**Comment by jimduff-usds** [comment]
Subsumed by more recent Gage tickets.
