### ISSUE TITLE
CA - Onboarding Operations and Data Issues

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2706]
## Problem statement

CA continues to report data quality issues and concerns which require data investigation and engineering work.

## What you need to know

We have a weekly call with CA to discuss open item hosted by @Adrian-Brewster 

## Acceptance criteria

- All major issues are resolved

## To do

- Continue to meet CA weekly and address questions and updates in the comments

- [x] Provide list of filtering criteria to determine high or low quality messages and routing to the primary and secondary feeds

**Comment by mlighdc** [comment]
@anshulkumar-usds and @Adrian-Brewster CA has requested the filtering criteria to determine high or low quality messages and routing to the primary and secondary feeds. Not sure if this request has been captured somewhere, Adrian. I have added to the to dos so it does not get missed. Thanks.
