### ISSUE TITLE
WY - Data Issue

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-reportstream#2719]
Hello,
The Wyoming Department of Health received a positive COVID-19 lab result on a patient that says they were never tested. We received no information about the ordering facility or ordering provider to try and track down what might have caused this test result. 
The accession number is BEE82A0E-66E1-44CD-B7A6-660811816C03
Can you help us figure out where this lab result came from?

**Comment by LGFranklin** [comment]
@anshulkumar-usds

**Comment by anshulkumar-usds** [comment]
Followed up with Cue on 11/2 to understand root cause.
