### ISSUE TITLE
Ensure that the smoke and simulation tests work against new processing steps

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#2723]
### Acceptance criteria:

- The db queries in TestReportStream assume exactly 3 steps:  receive, batch, send.  Change this to 4 steps, to include 'process.  Be careful:  not every CoolTest looks at every step.
- The Simulation tests need to be improved to check that data actually flows end2end.  As a first pass, you could implement a query that polls until the number of sending to WAIT_5_MINS is greater than the number submitted.  Because the number of Sent reports is small (a few dozen, even with very large number of Items), this should perform OK.   This should work well, as long as nobody else is submitting a Simulation run at the same time.

FYI @clediggins-usds , @whytheplatypus

**Comment by clediggins-usds** [comment]
@jimduff-usds Can we discuss this?  I think adding tests to ensure the simulator data is flowing end to end would invalidate the load test aspect of it if we were checking real time. 
Are you thinking for each record?  Verify there is data in the database after it all runs?
Wait the batch duration and make sure batch step is present?

**Comment by clediggins-usds** [comment]
Determine a way to check results after the run - either check off items individually or run a more simple count to verify the data got through.

**Comment by clediggins-usds** [comment]
Async Test:
![image.png](https://images.zenhubusercontent.com/6138d507d762bdc46fa56814/d7ea4789-6a09-4c19-b52d-ce4ae213c766)

Sync Test: (staging was getting another hit at the same time, so the result # is higher than expected)
![image.png](https://images.zenhubusercontent.com/6138d507d762bdc46fa56814/7b0327f5-9388-40c8-aee1-2609d70ee4cc)
