### ISSUE TITLE
Sprint 30 - Update Live States on SVG Map

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#2740]
## Problem Statement
As ReportStream Product, we need to keep our map of live states up-to-date so that we communicate the state of our application to our current and prospective users and other stakeholders.

## Acceptance Criteria
- Update the SVG map so that all states that have a status of "Live" in this spreadsheet also show as Live on the [map on this page](https://reportstream.cdc.gov/how-it-works/where-were-live) 
- Update the list of Live states to include all that have a status of "Live" in the [spreadsheet](https://cdc.sharepoint.com/:x:/t/USDSatCDC/EetP9vPm-npFpt009d1ziB8BYeQNtvq0kr786dPlrcsFAQ?e=WMOK79)
- As of 11/30/21, we need to add Tennesse & Oregon

## To Do
- [ ] Small code change to set to "true" those states that are now live

**Comment by TomNUSDS** [comment]
Let me know if you need help updating the new svg map in the React app.

**Comment by HeatherRienks** [comment]
@MauriceReeves-usds  or @Adrian-Brewster  - Do you have a list of the states that we need to update?

Thanks!

cc: @TomNUSDS, @drew-usds

**Comment by HeatherRienks** [comment]
@Adrian-Brewster - do you have a list of the states that we need to update, or is there another teammate I should reach out to?

Thanks!

**Comment by Adrian-Brewster** [comment]
Hey @HeatherRienks We haven't had any states go to production for a couple of weeks so I dont have any updates.  Thanks for checking!

**Comment by HeatherRienks** [comment]
@Adrian-Brewster -thank you!

**Comment by Adrian-Brewster** [comment]
I just tag Drew in a slack message letting him know.  We can improve on that workflow though if you have any ideas! :) @HeatherRienks

**Comment by HeatherRienks** [comment]
Yes, let's chat more! Since we already have nearly 50% of the US in production, I don't think it would be too "noisy" if we posted this in RS general? It's also a big win when we have a state go into production, so would be good for the larger team to be aware too! 

cc: @drew-usds

**Comment by drew-usds** [comment]
Moving to backlog, let's keep updated with O&O and look at this again when new states are added.

**Comment by anshulkumar-usds** [comment]
Hey @drew-usds , how would you like O&O to share updates on the onboarding work. We have a tracker on sharepoint that shows status of each STLT, and we update that on a daily basis: https://cdc.sharepoint.com/:x:/t/USDSatCDC/EetP9vPm-npFpt009d1ziB8BYeQNtvq0kr786dPlrcsFAQ?e=WMOK79

We should get OR and TN listed as LIVE on the website.

**Comment by HeatherRienks** [comment]
@drew-usds & team, let's discuss what would work best.

cc; @loripusey @rachelhanster

**Comment by loripusey** [comment]
@drew-usds @sean-usds I pulled this in to this sprint per Drew's agreement that we could pick this up; going forward we will pull 1 of these into each sprint (unless we look at the map and determine there are no changes)

**Comment by HeatherRienks** [comment]
@drew-usds, @sean-usds, @loripusey , @anshulkumar-usds 

I spoke with @anshulkumar-usds and he has agreed to update the corresponding sprint ticket with any NEW states that have gone live during the sprint. If there are no updates on the ticket, we can assume that no states have gone live. This will provide more visibility and will save time so we don't have to compare against the PHD Onboarding Excel Tracker.

**Comment by HeatherRienks** [comment]
@sean-usds - Looks like 3299 is closed -what else needs to happen in order to move this one to "done?" 

Thanks!

cc: @drew-usds
