### ISSUE TITLE
Make sure all our Metabase queries still work after splitting `receive` in two.

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#2745]
Some of our metabase queries probably depend on there being 3 steps.  These will need to be fixed so they allow for 3 or 4 steps.

### Acceptance Criteria

- All Metabase dashboard queries in Staging are accurate.
- All Metabase dashboard queries in Production are accurate. (Will have to copy queries over by hand from Staging if needed)

**Comment by clediggins-usds** [comment]
Checked all queries - two outstanding questions @jimduff-usds:

- On 'waiting to batch or send' query - do we need to include 'process' records in this?  Process is set to go immediately which will typically result in expected 'batch' records so I would say no, but want to confirm
- 'Actions taken by reportStream in last day' will currently include 'process' records. I'm guessing it should, want to confirm.

**Comment by jimduff-usds** [comment]
I added #3101 as a blocker, as this task needs to be done after #3101 is in Staging.

**Comment by clediggins-usds** [comment]
Verified all dashboards in metabase again, no issues.

**Comment by jimduff-usds** [comment]
Closing as DONE.
