### ISSUE TITLE
Experiment with large queue sizes in the Batch and/or Process steps

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#2746]
If our input volumes increase dramatically we need to confirm that our downstream batch queue can handle it.

Experiment with large queue sizes in the Process step
Test batching with 10,000, 100,000, 1,000,000 items in the batch. 

First solution is probably to batch more often, on the assumption that STLTs will not want these massive batches either.

Note:  This test can be done by adding a, say, EVERY_60_MINS receiver to Simulator.kt

**Comment by clediggins-usds** [comment]
Tested with 20 threads, batches of 1000

![image.png](https://images.zenhubusercontent.com/6138d507d762bdc46fa56814/298f6109-2326-44a1-9787-093b272cf15b)

**Comment by clediggins-usds** [comment]
Talked to Chris / devOps.  We can set up autoscaling to trigger on queue volume as needed. We can turn on/off functions to test this as needed.

**Comment by clediggins-usds** [comment]
Test:
![image.png](https://images.zenhubusercontent.com/6138d507d762bdc46fa56814/59c7e6d3-872e-4e64-8ca4-d8ae3a1c8527)

**Comment by clediggins-usds** [comment]
Another test:
![image.png](https://images.zenhubusercontent.com/6138d507d762bdc46fa56814/9c1079fd-e53b-45de-b4dd-3c3923dd4790)

**Comment by clediggins-usds** [comment]
The steps are working as expected, but staging falls over (still works, but goes VERY slowly) when hammering it with 100,000 records as fast as we can across 20 threads.  The batchfunction is the slowdown part.   When load drops, it eventually catches up.
