### ISSUE TITLE
Submissions History API Filter: By Date

### ISSUE THREAD

**Issue by derekkinsman** [CDCgov/prime-reportstream#2754]
## Problem statement

The Submissions History API needs to be filterable by a variety of date functions.

## What you need to know

- How the UX team and users would like to interact with Date selection.
- How the Pipeline team would like to interact with Date selection.

## Acceptance criteria

A call to `/submissions` with a date filter returns data within this parameter.

Date inputs are converted to format in the database before being submitted.

Current filter parameter design include:
```
  # ?dateStart=STRING (YYYY-MM-DD) || INT (NN [days back] | default: 30)
  # ?dateEnd=STRING (YYYY-MM-DD | default: Today)
  # ?year=INT (YYYY | default: CURRENT YEAR)
  # ?month=INT (MM | default: CURRENT MONTH | requires ?year)
```
`(dateStart and dateEnd)` or `(year and month)` are required.

**Comment by bgantick** [comment]
@jimduff-usds I believe this was already implemented here: https://github.com/CDCgov/prime-reportstream/pull/4622
