### ISSUE TITLE
Rate Limit for /api/email-registered

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#2757]
## Request
- We need an rate limit per IP address for requests sent to /api/email-registered

## Problem statement
- We are building an in-take form for senders to agree to our TOS. This form will be on a public page and submissions will trigger emails from our web server. To guard against attacks/spam, we need to rate limit these requests
- PR with code changes: https://github.com/CDCgov/prime-reportstream/pull/2662

**Comment by JosiahSiegel** [comment]
API rate limits can be set per API key or address with [Azure API Management](https://azure.microsoft.com/en-us/services/api-management/)

[Example](https://docs.microsoft.com/en-us/azure/api-management/api-management-sample-flexible-throttling#ip-address-throttling)

**Comment by cwinters-usds** [comment]
We can also use the Web Application Framework in conjunction with the Front Door we're already using to limit requests to an API. It cannot limit requests per Client IP (unless you know their IP beforehand, which we won't), but instead we can match a specific path in the URL and effectively say "Ensure that /api/email-registered isn't called more than five times a minute".

I think this is ok -- setting this to something like five per minute would ensure we don't drown in spam while providing more than enough space for people to sign up.

@sean-usds @kevinhaube do you think this will meet your needs?

**Comment by sean-usds** [comment]
that sounds good to me! i

**Comment by cwinters-usds** [comment]
@sean-usds There's now a policy in staging to limit access to /api/email-registered to 5 per minute. I applied this policy to the host `staging.reportstream.cdc.gov` -- is that the one the front-end is calling into?

**Comment by loripusey** [comment]
@cwinters-usds do you expect to be finished with this work by the end of this sprint? (Sprint 31)
cc: @rachelhanster @sean-usds

**Comment by kevinhaube** [comment]
@cwinters-usds Hey! The endpoint base URL for staging is `staging.prime.cdc.gov` and the calls are coming from `staging.reportstream.cdc.gov`

**Comment by cwinters-usds** [comment]
@kevinhaube thank you! will modify

**Comment by cwinters-usds** [comment]
@kevinhaube ok updated

**Comment by cwinters-usds** [comment]
Created a WAF policy in staging and applied to the Front Door. Long-term plan is to do this in Akamai instead.
