### ISSUE TITLE
TX - EFT Administrative Password

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2760]
## Problem statement

Automated email from TX DOH's EFT Administrator bound for Mo notifying that the password will expire in 4 days from 10/25. We need to assign this responsibility to someone else in team. Currently a placeholder for further discussion.

Maurice Reeves,
User ID: idielr007
This notification is to inform you that your password will expire on EDTS in 4 days
If you strictly connect using key authentication, please disregard this email.
At your earliest convenience, please address your password:
Click to reset your password.
User-chosen password's must have a minimum of 15 characters.
User-chosen password's must not use a word from the English dictionary.
User-chosen password's must not contain 3 or more characters from the user name.
User-chosen password's must not contain 2 or more repeating character.
User-chosen password's must contain at least 4 characters from the following:
•	An uppercase letter.
•	A lowercase letter.
•	Number (0-9).
•	Non alpha-numeric symbol for example: !,@,#,$.
Note: If you need assistance resetting your password, please contact the HHSC Help Desk 855-435-7181. Request the Help Desk assign ticket to Enterprise Secure FTP Support.

**Comment by Adrian-Brewster** [comment]
Completed.
