### ISSUE TITLE
NJ - ORC-2.1 Field Update

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2761]
## Problem statement

NJ has reported failures and data issues with RS when ORC-2.1 is empty. Per NJ:
"For ORC-2.1, if you don’t have a value, leave the rest of ORC-2 empty.  **So either put the specimen in ORC-2.1, or leave all of ORC-2 empty.**"

## Acceptance criteria

- NJ specific field mappings (and schemas, if any) are updated to reflect the preference from the state
- NJ confirms this change and accepts data with new logic

## To do

- Check our current logic for ORC-2.1 for NJ
- If ORC-2.1 is empty, leave the rest of ORC-2 empty as well

**Comment by Adrian-Brewster** [comment]
@jorg3lopez Can this be closed out?

**Comment by jorg3lopez** [comment]
yes
