### ISSUE TITLE
CDC map component accessibility concerns

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#2773]
**Describe the bug**
- If navigating by tab, I have to move through every state one-by-one. 
- ANDI also throws some arial-label related errors.

**Impact**
Would be a huge pain to get to any content underneath wherever the map component shows up.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TomNUSDS** [comment]
The new svg map is in place. Can you let me know if you have any 508 concerns for it?
