### ISSUE TITLE
OR - Receiving records from PA

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2777]
## Problem statement

OR is reporting test messages for facilities in PA, and is requesting suppressing messages not intended for OR.

## What you need to know

OR was recently onboarded to RS. So it's possible they're receiving data for OR residents getting tested in PA. Need to investigate root cause and apprise OR.

## Acceptance criteria

- Explanation is provided to OR on current issue and path forward

## To do

- Investigate why OR is receiving records from PA
- Inform OR why this is the case, and what, if any, fix is needed to correct the issue

**Comment by Adrian-Brewster** [comment]
Sender likely accidentally hit the wrong state on a drop down. Do they need to be resent? @anshulkumar-usds will follow up.

**Comment by anshulkumar-usds** [comment]
Checking with OR if they need us to resubmit corrected results

**Comment by anshulkumar-usds** [comment]
OR confirmed no resubmissions are needed. Closed.

**Comment by MikeC-A6** [comment]
@anshulkumar-usds - Wouldn't PA be the one who might want the results sent?  The results shouldn't have gone to OR in the first place, but they should have gone to PA
