### ISSUE TITLE
R&D - Tools for Self Onboarding

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2779]
## Problem Statement
As the Onboarding & Operations team, we need to allow Senders and Receivers to quickly and easily onboard themselves based on our Key Results of
- Onboarding a Sender within 15 business days from kickoff
- Onboarding a Receiver within 3 business day from kickoff

**Comment by victorialb-usds** [comment]
VLB: Here is link to the current intake form: https://prime.powerappsportals.us/siw/

**Comment by victorialb-usds** [comment]
Q? VLB: is there already sense/synthesis of barriers to onboarding - perhaps this is a quick first step or SPIKE to do? based on CDC demo and conversations with onboarding team the variation in onboarding includes external factors to consider perhaps we already have a sense of these.

**Comment by loripusey** [comment]
@victorialb-usds this is a good place to start: https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FTeam%20Documents%2FSender%20Automation%20Team%2FMisc%2E%20Notes%20%26%20Artifacts%2FSender%20Automation%20Team%20program%20Review%20V1%20%2010%201%202021%2Epdf&parent=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FTeam%20Documents%2FSender%20Automation%20Team%2FMisc%2E%20Notes%20%26%20Artifacts

**Comment by loripusey** [comment]
Also, this captures some of the ideas for internal tools.
https://app.mural.co/t/primedatainput6410/m/agilesixapplications0942/1632761768968/ce4723a6dc07bc6d9d58a07e9f79d71c54d83375?sender=ud3aa760e30b39bcf436d4473

https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1634743003369/60869a741f0cc628d79dbcc167736033fa5ae9f2?sender=ud3aa760e30b39bcf436d4473

**Comment by rachelhanster** [comment]
Closing initiative as it's now duplicative with Ops' teams effort in identifying business processes improvements and Experience team's service blueprint initiative (especially pain points and opportunities)
