### ISSUE TITLE
Research and spec feature flag implementation

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#2786]
As we continue to build features on the frontend, it will become more and more important to be able to easily toggle features on and off for certain users. This makes testing, rollout, and emergencies shutoff easier. 

One place to start: https://www.flagship.io/feature-flags-react-app/

**Comment by mlighdc** [comment]
@sean-usds the VA uses feature flags. Let me know if you would like to be connected to the VA / USDS team to brainstorm with them.

**Comment by cwinters-usds** [comment]
@bgantick do you think this is still relevant/useful?

**Comment by bgantick** [comment]
Hey @cwinters-usds  - this was actually already implemented here: https://github.com/CDCgov/prime-reportstream/pull/4488
