### ISSUE TITLE
Refactor pre-commit hooks to run without Docker

### ISSUE THREAD

**Issue by ronaldheft-usds** [CDCgov/prime-reportstream#2797]
This may opt to skip Docker if the tool is installed locally.

**Comment by JosiahSiegel** [comment]
@ronaldheft-usds There's a small win at reducing dev daily builds by adding the `--quick-package` argument to cleanslate, which passes same to `gradlew`. I made this change in this commit [here](https://github.com/CDCgov/prime-reportstream/commit/80eac746c681f221eeaa78c0a610839a82e1d524), but it doesn't really go with the title of this issue, even if all towards the same effort of reducing build times. Should I create a new issue or make this one more generic to capture more of these small adjustments?
