### ISSUE TITLE
Duplicate LOINC Code on IgG & IgM Antibody Results

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#2800]
## Problem statement
On COVID Antibody tests, if blank is passed into test_performed_code for the IgG and IgM rows, both IgG and IgM results get the same LOINC Code in the HL7 message.

Further explanation:
IgG and IgM tests are a type of test that will return multiple results.  For example, a combo test.  This type of tests can return two or more results for one patient and sample.  The issue here is that:
1. The LOINC code for the results should be different since they are providing different result types.  
2. If a report is received with no LOINC codes but with a device ID/model ID then the LIVD lookup proceeds to populate the LOINC code with the first found in the table that matches.  BUT, the first one that matches may not be the correct one and we have no way to determine which one to choose.  This issue is asking for the report to be flagged as an error since it is missing required data.

Design considerations:
There is currently no mechanism in the LIVD lookup table to determine if a lookup is unique or not.  
What will happen if a lookup returns a non-unique value?  

## Acceptance criteria
- If the LIVD lookup cannot find a unique LOINC code then the LOINC code should be left blank.

**Comment by carlosfelix2** [comment]
Sample input data in CSV
[https://app.zenhub.com/files/304423150/6867cb19-1afa-4b66-9cdf-1e281c608417/download](https://app.zenhub.com/files/304423150/6867cb19-1afa-4b66-9cdf-1e281c608417/download)

**Comment by rhood23699** [comment]
Duplicates LOINCs are no longer returned.  Closing this ticket.
