### ISSUE TITLE
React 404 page not working

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#2810]
**Describe the bug**
When going to a bad url, the React app shows the 404 page message but then it quickly disappears.

**Impact**
Bug

**To Reproduce**
1. Go to a nonexistant url 'https://staging.reportstream.cdc.gov/how-it-works/systems-and-settings2'
Result:
404 page message is displayed briefly but then disappears.

**Expected behavior**
404 page should not disappear

**Screenshots**
Expected ![image.png](https://images.zenhubusercontent.com/6001ffdbfa03b2340a4ca394/721aa0b1-053b-4723-b963-617bf2d500e8)

Actual ![image.png](https://images.zenhubusercontent.com/6001ffdbfa03b2340a4ca394/d185882e-2940-49c9-96ab-c711c03f3742)

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome 94

**Comment by loripusey** [comment]
@TomNUSDS if this is fixed can you close please?
