### ISSUE TITLE
Create and Finalize Research Plan for CSV upload pilot

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#2811]
## Problem statement

O&O is planning on piloting the CSV uploader (in staging possibly?) this sprint. We need to gather feedback and input from our pilot users.

## What you need to know

Lots to look into as we have thus far not tested any of the uploader with users.

Ideas to start with: 

- What's currently going on with the pilot, where is A1H at?
- Are users able to upload a csv?
- Do error messages make sense?
- What is working well about the csv upload? 
- What could be improved about the csv upload process?
- What happens after folks are in production? What is the process for learning to use the tool? What ongoing support do they need to use it?

## Acceptance criteria

- [x] Create research plan to capture what we want to learn from CSV upload pilot

## To do

- [x] Connect with O&O on A1H meeting agenda. @drew-usds @BerniXiongA6 got email back that this will be on 11/23 11 AM or 1PM PST TBC

**Comment by loripusey** [comment]
Please refer to the Onboarding's team research that led to the CSV Uploader: https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FTeam%20Documents%2FSender%20Automation%20Team%2FMisc%2E%20Notes%20%26%20Artifacts%2FSender%20Automation%20Team%20program%20Review%20V1%20%2010%201%202021%2Epdf&parent=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FTeam%20Documents%2FSender%20Automation%20Team%2FMisc%2E%20Notes%20%26%20Artifacts

**Comment by drew-usds** [comment]
Design sync updates:

### Interview process wants:

- Keep group small
- Have first meeting intro'd by Mike or Rick, they'll join our 1st meeting (will bring on other eng or product on follow-ups)
- Victoria or I will run the meeting, run through of the app/process to be driven by the user. 
- 2nd designer and eng will take notes on shared doc

**Comment by victorialb-usds** [comment]
As of 11/17/21: 
Rick sent email to Simmi to ask for a few days that she would be able to do talk through. @drew-usds @BerniXiongA6  @inkandsound

**Comment by drew-usds** [comment]
Doc in our Drive for now (only shared docs Victoria has access to): https://docs.google.com/document/d/18KHaYwSJQeRjVc4rj9uA1i8YEph1zFtz/edit?usp=sharing&ouid=115819704652469288687&rtpof=true&sd=true

Will move to Sharepoint when Victoria has access.
