### ISSUE TITLE
SPIKE -- Research OKTA SendGrid integration for new user account creation

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#2815]
## Problem statement
New users should get a RS-branded email when an account has been created for them in Okta. Currently we're locked into using SR's branded templates that are set up in Okta.

## Research this solution
- When RS team creates an Okta account for an RS user ...
  - An email is sent to that user to let them know they can log in
    - Email template is RS branded
    - Email content lets them know ...
      - An account has been created
      - [Links them to an RS page where they can set a password?] [Gives them a temp password and links them to the login page?]
  - User can log in to RS app 

## To do
- [x] Connect with Okta rep about SendGrid (also in progress with SR team https://github.com/CDCgov/prime-simplereport/issues/2833)
- [ ] Determine how we would build SendGrid integration
- [ ] Determine what email template we want (can copy our standard template)
- [ ] Write email copy
- [ ] What page do we want to link to?

**Comment by drew-usds** [comment]
Updates from the related SR issue linked above. TL;DR = Looks like the internal OKTA workflows will meet our needs. OKTA possibly doesn't handle the static pages that show up elsewhere though.

> sean-usds commented 6 days ago
Couple of us working on ReportStream chatted with Dale and Mike from Okta yesterday and this topic came up. They gave us a brief demo of Okta Workflows and it seems like this will solve this problem. When a new user is created, we can trigger different welcome emails based on what Okta Group they are in. Since all (afaik) SimpleReport Groups begin with "SR-" and all ReportStream groups begin with "DH" we can base the email sent off that

> drew-usds commented 5 days ago
>@sean-usds mentioned this to you in today's standup but just writing it down for posterity:
>
> The sign up email flow stuff looks good! Also looks like it applies to any updates to their accounts as well.
Are there also similar options to differentiate what content shows up on any of the hhs-prime.okta.com/* pages? Ex: login help, or password reset? Currently those pages show the SimpleReport logo.

> emmastephenson commented 5 days ago • 
Thank you both! I think sorting by groups within the workflow is likely our best option. @drew-usds, I'm not sure about the options available to differentiate content on the login or password reset pages, but I'll look into it.
>
> I did just try to start creating a workflow in our Preview account, and it looks like it's not an option that's enabled for us just yet. I got in touch with Michael & Dale, but I suspect this might be something additional we have to add to the contract 😞
>
> Just heard back from Okta; they do indeed have to turn Workflows on but Dale doesn't have permission to do that in production. Sounds like they're working on their end to enable it.

**Comment by loripusey** [comment]
@sean-usds can you look into this for this sprint (sprint 32)?

**Comment by sean-usds** [comment]
Proposal: https://github.com/CDCgov/prime-reportstream/issues/3682
