### ISSUE TITLE
CLIA reporting for states

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2816]
## Problem statement

Onboarded states have a requirement whereby they must know of newly registered facilities (CLIAs) prior to receiving data from them. Presently, a member of the O&O team manually runs a query in Metabase, and sends out emails to each state with this information. Due to resource limitations, this process is only performed weekly. However, states would like to have access to newly registered facilities in real-time (ideally), or daily. Current process is time consuming with room for human error.

## What you need to know

- Registered facilities are primarily SR facilities, with an uptick in facilities from our "other" senders
- On several occasions, the states have questions about the data submitted due to incomplete information or accuracy of data itself
- We need to find a more automated, self-service-able solution to this issue

## Acceptance criteria

- TBD

## To do

- Experience team should schedule time with O&O to learn about current state of affairs
- Perform discovery / research into how an automate solution to this issue can be achieved
- More to come based on initial discussion

FYI - @Adrian-Brewster @anshulkumar-usds

**Comment by loripusey** [comment]
@anshulkumar-usds is this still something that is needed?
cc: @Adrian-Brewster

**Comment by anshulkumar-usds** [comment]
Providing a more self-serviceable (needs definition) dashboard to STLTs is still needed, although not high priority. I will let @Adrian-Brewster define the requirements here. Ideally, if the states can find some info on facilities reporting to them without our  manual metabase reports, that would be helpful.

**Comment by Adrian-Brewster** [comment]
@loripusey I think this is definitely still needed.  We have managed to set up some work arounds for specific state partners that require notice before any new sender is onboarded, but its not a permanent solution.  Having an interactive dashboard that enables users to see a list of senders (and their associated CLIAs) along with message volume would be a great start.  Do you want to have a call to brainstorm?

**Comment by rachelhanster** [comment]
Closing this ticket as list of reporting facilities and CLIA info per public health authority is part of the work in a separate initiative [3608](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3608)
