### ISSUE TITLE
Update settings table for onboarding STLTs

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2817]
## Problem statement

The settings table needs to be updated as states are onboarded (moved to prod) to RS. The process needs to be documents and formalized alongside our update process for map on the website.

## What you need to know

The attribute  customerStatus and has values of inactive, testing, and active
At this time this will only drive the metabase reporting to help us better find issues with 'active' senders/receivers and filter out those that are testing
CLI command when a receiver/sender comes online is ./prime receiver set --key customerStatus --value active --env staging --name oh-doh.elr 

## Acceptance criteria

- A process is documented with when the updates should happen
- An owner and back-up is designated

## To do

- Meet with @MauriceReeves-usds to determine process
- Document process and designate owner and backup

FYI - @Adrian-Brewster

**Comment by anshulkumar-usds** [comment]
Anshul to setup RS locally and circle back with Mo

**Comment by anshulkumar-usds** [comment]
Need to follow up with engineers on next steps

**Comment by anshulkumar-usds** [comment]
Updated the STLT onboarding template to ensure the status flag gets updated as part of our process

**Comment by brick-green-agile6** [comment]
Where is the list of all STLTs that should be active? I don't want to prematurely change a customerStatus setting.

**Comment by jimduff-usds** [comment]
Currently this flag is important because its used in metabase to distinguish between errors of critical concern because the receiver is 'active',  and those that can be ignored, because the receiver is not 'active'.

**Comment by jimduff-usds** [comment]
And looking to the future, it would be great for this flag to become the source of truth for maps/lists of active SLTLs.  Next step there would be to wire up our UIs to a pull from settings.

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 please consult our receiver onboarding tracker: https://cdc.sharepoint.com/:x:/t/USDSatCDC/EetP9vPm-npFpt009d1ziB8BYeQNtvq0kr786dPlrcsFAQ?e=WMOK79

**Comment by anshulkumar-usds** [comment]
Confirmed settings applied in settings table in metabase
