### ISSUE TITLE
Abbott - Consent to RS ToS

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2820]
## Problem statement

To onboard a sender to RS, consent to RS's ToS is required. Abbott already has a DUA in place with HHS for the current HHS Protect reporting. We need to understand whether a new DUA with CDC is required, or if their consent to RS/CDC ToS is sufficient for us to move forward with migration.

## What you need to know

- Abbott is reviewing the current DUA internally with their legal team and HHS contacts
- Anshul is partnering with Mike Judd at CDC to understand implications and timelines for having/missing consent prior to go-live date of 11/19

## To do

- [ ] Follow up with Abbot week of 11/1 for an update / impediments
- [ ]  Anshul to fu with M Judd for any internal concerns re our ToS and related dependencies

**Comment by Adrian-Brewster** [comment]
Still pending. Part of Abbott Onboarding. Still waiting to hear back
