### ISSUE TITLE
CSV Uploader - Add De-Identify Function 

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#2821]
## Problem statement
Senders typically do not have a good way to de-identify data.  They typically use EXCEL, but EXCEL can unexpectedly alternate data.  Example, date formats are changed; leading zeros are removed; and large numeric fields are changed to scientific notation.  This is a major problem during testing because the schema is developed and tested using altered data, so when we move to Production, we receive errors, warnings and data transformation failure because the unaltered CSV file is different.

## Needs
- We already have the initial schema developed, so we need a way to identify the PHI and PII fields to be de-identified.
- The CSV Uploader could then de-identify the CSV file as it uploaded using the previous De-Identify VBScript.

## Purpose
- This feature would allow Senders to easily send unaltered production files to Staging; thus allowing us to complete testing with more confidence that the move to Production will be successful.
- This will prevent Senders from accidentally Sending PHI & PII to Staging.

## Comments
This is a feature needed as soon after the CSV Uploader MVP is completed.

**Comment by loripusey** [comment]
@rhood23699 Are there OTS products out there that could do this for Senders?

**Comment by loripusey** [comment]
@rhood23699 Is this feature still needed for your onboarding purposes?
cc; @rachelhanster

**Comment by rhood23699** [comment]
This is not needed at this time.
