### ISSUE TITLE
Ongoing Bug in production:  Syntax error at from window.onerror

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#2822]
We occasionally see this Exception in Production:

Syntax error
Problem Id:Syntax error at from window.onerror

window.onerror@https://reportstream.cdc.gov/js/prime-web-receiver-post.js:4:13

Sorry - that's all that's in the message

This most recently occurred on 10/28/2021, 10:16:06.980 AM (Eastern Local time)

It has occurred 35 times in the last 30 days.

**Comment by MauriceReeves-usds** [comment]
@loripusey this just happened again. are we able to prioritize this as it's triggering Pager Duty notifications.  Thanks

FYSA: @jimduff-usds @sean-usds @rachelhanster

**Comment by loripusey** [comment]
@MauriceReeves-usds I can prioritize it in our backlog and pick it up next sprint; I'll also check with the team to see if anyone has capacity to pick it up this sprint

**Comment by loripusey** [comment]
@sean-usds can we close this bug now that React has moved to Production?
