### ISSUE TITLE
IL - ORC-12.1 & ORC-16.1 ordering facility name being placed in an ‘ID’ subfield causing messages to fail

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#2833]
ORC12.1 (OrderingProvider->ID) is for an ID and has maximum character size limit of 15, it would be best if this subfield could be left blank or the correct NPI be placed here. The same problem is happening in OBX 16.1.1 (OrderingProvider->ID), the ordering facility name is being placed here and it’s exceeding the character size limit.

Messages do not need to be resent. 
 
![image.png](https://images.zenhubusercontent.com/60d1eba7caf0775fd79203f8/84aa62c7-3979-4170-ab57-ea41ff4ebd87)

**Comment by Adrian-Brewster** [comment]
Mike working on triaging the ticket today.  Will coordinate with Herman to get eta in creating a fix

**Comment by rhood23699** [comment]
@Adrian-Brewster @anshulkumar-usds @MikeC-A6 I've reviewed the Metadata and their a 66 rows with Egyptian Health Department as the Ordering Provider ID.  All rows came from Sender ID: simple_report.default.  I can't see the actual data sent, but from reviewing the Schema Name: pdi-covid-19, I'm almost 100% sure that we are receiving Egyptian Health Department in the Ordering Provider ID field; so this appears to be a data entry problem in Simple Report.

**Comment by anshulkumar-usds** [comment]
@LGFranklin can you please take a look on your side? I'll forward you the email we received from IL.

**Comment by MikeC-A6** [comment]
@anshulkumar-usds - I'm thinking we need a fix for MA on our end as any changes on the sender side could take a bit.  Their specific request is to only populate ORC 12.1 and OBX 16.1.1 with a value if there is a properly formatted NPI.  Flagging this for a 16th minute topic for tomorrow to discuss potential solutions - not sure if we can do this in the HL7 serializer, as @mlighdc mentioned that some States use the Provider ID field in different ways- so a serializer change could have unwanted side effect for other STLTs.

**Comment by LGFranklin** [comment]
@anshulkumar-usds Egyptian Health Department has not done anything with their SR account aside from identity verification. No facility has been input and no tests have been submitted.

**Comment by mlighdc** [comment]
@rhood23699 did you say there are 66 rows with Egyptian Health Department as the Ordering Provider ID? How can that be since they have not created any facilities or submitted any tests via SimpleReport. Are they submitting their test results via Cue Health or another OTC device?

They should have an NPI number since they are a health care facility.

**Comment by LGFranklin** [comment]
Sorry Ming! My original sleuthing was incorrect. There is an Egyptian Health org with Ms. Byrd as the only user. They haven’t done any setup. This above is for a facility in a separate org that listed Ms. Byrd as the OP and Egyptian PH as the NPI. Should have written “scratch that” in my GH comment as opposed to the edit. 

I will follow up with this user here to have them update and our team at SR to make sure our validation is fixed.

**Comment by MikeC-A6** [comment]
@LGFranklin - The specific issue that is causing messages to fail in ILs integration engine is when the character length of the Provider ID field is >15..  There are 14 SimpleReport users who have sent data in the last month that have >15 characters.  Some info regarding potential validation options in SimpleReport:
- NPI is always a 10 digit numeric value
- Might be useful to have this as an optional field, but if there is data populated it must be 10 numeric characters
- this would eliminate the need for users to type in random or dummy values for NPI if they don't have one

**Comment by LGFranklin** [comment]
Great ideas; thanks, Mike! I'll log this and our team will amend shortly.

TY!

**Comment by anshulkumar-usds** [comment]
@LGFranklin @MikeC-A6 IL is looking for updates on this issue. Here's my proposed response:
1. Users in SR are entering the PHD name in the NPI field causing the issue at hand. SR will contact the user and advise they use the correct numeric value
2. SR will also work on a longer term solution to add data validation to the NPI fields, so we prevent future issue
3. At ReportStream, we can still enable logic to blank these fields ( per state?) if the 15 char limit is broken. Any thoughts on this Mike.

**Comment by LGFranklin** [comment]
@anshulkumar-usds Yes, we have contacted the user to request and update, and we created a ticket to address this: https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/3005 

Once this is complete, the validation will allow only numerical characters, and not allow input longer than 10 digits.

**Comment by anshulkumar-usds** [comment]
Thanks @LGFranklin I will close this out on RS board. 

RS will track a platform wide enhancement to blank these fields if the char limit is violated here: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3137

**Comment by anshulkumar-usds** [comment]
SimpleReport is working on the validation process here: https://github.com/CDCgov/prime-simplereport/issues/3005
