### ISSUE TITLE
MD - Prince Georges County facilities all having the same CLIA ID? 

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#2835]
Maryland reached out to see why all the Price Georges County facilities have the same CLIA ID.

**Comment by anshulkumar-usds** [comment]
Anshul will investigate and fu with MD

**Comment by anshulkumar-usds** [comment]
RS Metabase shows several SR facilities using same CLIA. Following up with @LGFranklin on next steps for resolution.

**Comment by anshulkumar-usds** [comment]
Blocked: SimpleReport team investigating. Unclear next steps for RS at this time.

**Comment by anshulkumar-usds** [comment]
Closing ticket: SimpleReport team will follow up with MD on next steps for remediation.
