### ISSUE TITLE
As a coder, I need to be able to generate fake data for `direct` schema children

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#2841]
Generating fake data for schemas that are children of `direct` causes exceptions.   

Is this a problem with the schema or with the fake data generator?  Either way, we have to be able to generate fake data without getting exceptions.

```
$ ./prime data --input-fake 1 --input-schema direct/cue-covid-19 --output ./junk/cue.csv

Exception in thread "main" java.lang.IllegalStateException: Element type is null for reportingFacility
	at gov.cdc.prime.router.FakeDataService.getFakeValueForElement(FakeReport.kt:182)
	at gov.cdc.prime.router.FakeReport.buildColumn$prime_router(FakeReport.kt:249)
	at gov.cdc.prime.router.FakeReport.buildRow(FakeReport.kt:297)
	at gov.cdc.prime.router.FakeReport.build(FakeReport.kt:318
```

Also when you run it, you get errors on duplicate `performingFacilityName` and `performingFacility` fields.

```
 "There's an issue parsing your file (Error: header 'performingFacilityName' is duplicated) For additional help, contact the ReportStream team at reportstream@cdc.gov.",
"There's an issue parsing your file (Error: header 'performingFacility' is duplicated) For additional help, contact the ReportStream team at reportstream@cdc.gov."
```

**Comment by kevinhaube** [comment]
Expanding on this regarding my experience:  It appears this is an issue with schemas with duplicated element names. A great example, currently, is the `all-in-one-health` covid-19 schema. This schema duplicates elements like Specimen ID and patient demographics a few times. This causes issues when generating fake data and attempting to use it with the CSV uploader.

**Comment by jbiskie** [comment]
Confirmed all children of the direct schema are generating fake data without issue. non-standard/all-in-one-health-ca-covid-19 is also generating without issue.
