### ISSUE TITLE
Understand ways senders report data

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2843]
## Problem Statement
As ReportStream, we need to understand all of the different ways that submitters of data need to be able to submit their data so that we can build tools that would benefit them.

## Acceptance Criteria
- Secondary/desk research on user segments
- Interview users (3-5 for smaller segments up to 10 for larger segments)
- Synthesize results
- Document research & present to team
- Create ZenHub Tickets based on findings

Link to the O&O team roadmap: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/roadmap

**Comment by victorialb-usds** [comment]
@rachelhanster @loripusey we are starting to do this with our contacts for the CSV Pilot. Can we bring this into the next sprint or create a new ticket, but then that would be redundant.

**Comment by victorialb-usds** [comment]
VLB to work on sender facilitation guide for potential call with sender on 12/30 will add link to that here 12/30.

**Comment by loripusey** [comment]
@victorialb-usds @rachelhanster I really think we need to re-consider how we are using ZenHub for research work; the amount of work in progress for each sprint is very large and I don't think it's productive to use ZenHub this way; perhaps Victoria and I can get together to figure something else out

**Comment by victorialb-usds** [comment]
@loripusey I think we can close this ticket. I put the description in the ongoing sender research epic and will create tickets for the sender research we are doing for CSV pilot and for UI of the submission history
