### ISSUE TITLE
Gather Feedback from Users for Validation & Submission History Feature's Clickable Prototype

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2859]
- Reach out to 5 Sender users (i.e. people) with at least 3 Organizations to get their feedback on the Validation & Submission History Feature's Clickable Prototype
- Doesn't have to be CSV users, can be API users

**Comment by inkandsound** [comment]
Notes from our user testing session with A1H based around clickable prototypes for sender submission history and file upload/validation: https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BB5D4CD06-7B93-4BFD-91FE-F69D84AF6D72%7D&file=A1H%20-%20Sender%20Experience%20Prototypes.docx&action=default&mobileredirect=true&cid=f6290ce4-84df-4d7c-8aae-6a9de08f916e

**Comment by victorialb-usds** [comment]
Created folder in sharepoint. https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Experience%20Research/Feedback%20from%20Users%20for%20Validation%20%26%20Submission%20History%20Feature%27s%20Clickable%20Prototype%232859%20January%202022%20ongoing?csf=1&web=1&e=7fxgt0 

Got referrals from O+O for API senders. Need to F/U and get contacts.

**Comment by inkandsound** [comment]
API ticket split out: https://app.zenhub.com/workspaces/prime-reportstream-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/3929
