### ISSUE TITLE
Make a Plan to Gather Feedback from Users for Validation Feature's Clickable Prototype

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2861]
- Develop a plan for how we will gather feedback

**Comment by drew-usds** [comment]
Will wrap this up later tonight/tomorrow. Will use in upcoming meeting with A1H on Thursday.

**Comment by HeatherRienks** [comment]
@drew-usds & @inkandsound  - reminder to pls include notes!

**Comment by inkandsound** [comment]
Working draft of usability test: https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Design%20and%20Research/User%20testing/Sender%20Experience%20Prototype%20-%20Usability%20Study%20Brief%20Notes.docx?d=w3a4ea23b3ffe47438cd9b8b294feaeac&csf=1&web=1&e=nbDnOV

@drew-usds we can also discuss during design sync - this isn't completely fleshed out.

**Comment by loripusey** [comment]
@drew-usds @inkandsound 
- can this ticket be closed?
- if there are follow-on stories that need to be created, please add them to the same Epic?
cc: @rachelhanster

**Comment by inkandsound** [comment]
@loripusey I'd say this is done. I'll close it.
