### ISSUE TITLE
Develop Plan for Measuring Organizations’ Likelihood of Referral 

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2862]
## Problem Statement
As ReportStream, we would like to measure an organizations’ likelihood of referring ReportStream to their peers so that we can gauge overall product satisfaction.

## Hypothesis
Organizations will recommend the use of ReportStream to others in their industry/state​

## Results
- We would like to be able to generate an average referral score
- Question: what is the industry standard for measuring this?

## Acceptance Criteria
- Brainstorm and decide on a method for capturing this metric 
- Generate a list of currently onboarded Organizations
- Create a plan to capture the metric
- Create a plan for documenting, storing, and visualizing the metrics over time

## TO DO
- Write up the plan, including 
    - Content for a survey
    - Ranking (what is the industry standard?)
    - Implementation recommendation for O&O team

## Plans
- [Plan for capturing metric](https://cdc.sharepoint.com/teams/USDSatCDC/_layouts/15/doc.aspx?sourcedoc={9a66d7df-4c6d-42c6-bfcb-c7b6a1a78688}&action=edit)
- Research questions

## Write Ups
- [Research Plan](https://docs.google.com/document/d/1bXJSgUBTEOzheQL0b8EyGB6jT7okiEiN/edit)

**Comment by victorialb-usds** [comment]
@drew-usds saw your question about Touchpoints - is this something we might consider here 
@victorialb-usds created a draft research plan on user satisfaction need to focus purpose of research  can share in (potential) meeting on Friday 11/19
@rachelhanster do we have clarity on if it is just receivers or also senders VLB under assumption was receivers but think it might include both

**Comment by rachelhanster** [comment]
This is for all reportstream users. Let's hold off considering touchpoints as an option for gathering this initial data.
