### ISSUE TITLE
Develop Plan for Capturing Analytics

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2863]
## Problem Statement
As ReportStream, we would like to capture analytics to measure the success and usage of the product over time so that we can know that we are heading in the right direction.  

## Notes
Refer to the analytics as outlined in the Product Brief [https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Artifacts/ReportStream%20Experience%20Team_Product%20Brief_draft%20v3%202021.10.21.pptx?d=w951bdeb553ad410b8149e95f463f3a59&csf=1&web=1&e=eaB5nI](url).

Refer to shared scratchpad "notes on tools to consider for gathering metrics" [https://cdc.sharepoint.com/teams/USDSatCDC/_layouts/15/doc.aspx?sourcedoc={da429e45-5f42-4399-a2b1-70ccc066a718}&action=edit](url)

Related to [https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/2834](url)

**Comment by TomNUSDS** [comment]
Early in the research, we should double-check the assumption we'll be using Azure's analytics product (application insights) versus the one government agencies one "DPA": https://open.gsa.gov/api/dap/

Probably using the same as SimpleReport is the best decision.
