### ISSUE TITLE
Add Attribution content to site to comply with creative commons requirements?

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#2868]
We're using a Creative Commons map svg https://commons.wikimedia.org/wiki/File:Blank_USA,_w_territories.svg and need to give attribution somewhere. 

Do we have such a page yet? Seems like we should. 

Also, there's a comment in the .svg file (which is just text) giving attribution (where the svg came from), but I'm not sure if this is enough.

use title or alt for the attribution

**Comment by loripusey** [comment]
Yes, we should comply with their requirements and give credit.

**Comment by HeatherRienks** [comment]
@kevinhaube  to reach out to @TomNUSDS  for more info

**Comment by TomNUSDS** [comment]
We should try to stay compliant with Creative Commons (licencing) requirements. We just need to figure out that that means (e.g. an attribution page?). 

I think the svg image file (`.svg` file is actually text) contains an attribution and it may be enough? We just need to verify, and if so, then we can close this ticket.

**Comment by kevinhaube** [comment]
@HeatherRienks @chris-kuryak I'll seek out those answer next Monday for this 👍🏼 
Thanks @TomNUSDS We miss you!

**Comment by TomNUSDS** [comment]
Wahoo! Thank you for the follow through!
