### ISSUE TITLE
IL - Data Issue

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-reportstream#2872]
This message came into the SimpleReport inbox. It's been forwarded to the Report Stream inbox.

"I am reporting for my department at Wabash General Hospital. I had accidentally submitted that <patient> was positive on DOS 10/18 and 10/25. I marked them as an error and input the correct information. The health department is requesting that the errors be removed so they do not show up on IMED.

**Comment by anshulkumar-usds** [comment]
@LGFranklin sorry I don't see the message in our shared mailbox. Could you please forward it to me at rdz8@cdc.gov

thanks!

**Comment by anshulkumar-usds** [comment]
@mlighdc @LGFranklin replied to IL user that we cannot remove any records. If they need to amend previously submitted results, please reach out on the SR side. No further action from RS is needed.

**Comment by mlighdc** [comment]
@anshulkumar-usds I would like to talk to IL about this because it was the public health department who asked the SR user to  remove the incorrected result. I am wondering if they would like to handle as we proposed to MT.
