### ISSUE TITLE
Design Tools the Onboarding & Operations Team Needs to do Onboarding Faster

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2874]
As the Onboarding & Operations team, we need to be able to onboard Senders and Receivers quickly and easily so that we can meet our Key Results of

Onboarding a Sender within 15 business days from kickoff
Onboarding a Receiver within 3 business day from kickoff

Refer to this mural for ideas from initial research: [https://app.mural.co/t/primedatainput6410/m/agilesixapplications0942/1632761768968/ce4723a6dc07bc6d9d58a07e9f79d71c54d83375?sender=ud3aa760e30b39bcf436d4473](url)

**Comment by chris-kuryak** [comment]
Too vague. Already accomplished a lot of this. Closing now per committee agreement.
@drew-usds @fmccaf1 @lizzieamanning @HeatherRienks
