### ISSUE TITLE
VT - Issue with OBX-18

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#2881]
For tests run on the BD Veritor, OBX-18 (Equipment Instance Identifier) is missing a required field, Universal ID Type (OBX-18.4). This field is required but may be empty, and we would expect OBX-18 to contain the serial number or UDI of the test kit or instrument. SimpleReport does not capture either the serial number or UID.

Example OBX-18 received in a recent message:
|BD Veritor Plus System_Becton Dickinson^^MNI|

Therefore, VT would like to leave OBX-18 blank for all tests, including the BD Veritor. Currently, for other test types (ex: BinaxNOW), this field is not populated.

**Comment by anshulkumar-usds** [comment]
OBX-18 can be left blank if we can't find a valid value to populate. 

![image (3).png](https://images.zenhubusercontent.com/607d9d4a591b7cc0bb55c82e/2924231e-2da6-4d82-aa84-3566576d09f3)The preferred approach might one suggested by @MikeC-A6 to use the LIVD table mappings. Attached is the mapper.

**Comment by anshulkumar-usds** [comment]
Also investigate why BinaxNOW is empty

**Comment by anshulkumar-usds** [comment]
DII: Device Instance Identifier

For the immediate term, we will make all of OBX-18 blank for VT.

**Comment by MikeC-A6** [comment]
Confirmed that BinaxNow is empty because there isn't a UID listed for BinaxNow on the LIVD spreadsheet

**Comment by anshulkumar-usds** [comment]
Issue is more widespread beyond BD Veritor. Preferred fix for VT is to leave all of OBX-18 blank. fyi - @jorg3lopez

**Comment by mlighdc** [comment]
Emailed VT to inform them OBX-18 should be blank for SimpleReport facilities.

**Comment by anshulkumar-usds** [comment]
We still need to implement that same fix for OBX-18 for all senders.

**Comment by jorg3lopez** [comment]
@mlighdc OBX-18 will be blank in all messages.

**Comment by Adrian-Brewster** [comment]
@jorg3lopez Any update on this ticket?

**Comment by mlighdc** [comment]
Sent a message to VT on 11/23 to let them know we delivered two test files for them to review. Also communicate that we are targeting all updates to be in production by 11/30. Would be this ticket and [2933](https://github.com/CDCgov/prime-reportstream/issues/2933).

**Comment by anshulkumar-usds** [comment]
Changes accepted by VT in the test file. @jorg3lopez will deliver prod file to VT.
