### ISSUE TITLE
Visual Design & Clickable Prototype for Submission History Feature

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2891]
## AC

Create a clickable prototype where:

- [ ] Sender can log into the app
- [ ] Sender can see an index/table view of everything they've submitted
  - [ ] Index view has < prev and next > pagination
  - [ ] Sender can filter results in the index view
- [ ] Sender can see show page of details about each thing they've submitted

Prototype includes:

- [ ] updated symbols
- [ ] layers/artboards organized

**Comment by inkandsound** [comment]
@loripusey @rachelhanster Added to this sprint because this is what we need for the API senders - since it's here already I don't need to make a separate story like I was going to.

Figma: https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=2233%3A11312
