### ISSUE TITLE
Organizations Can Request Support Online

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2906]
## Problem Statements
As an Organization that uses ReportStream, when I have a problem with ReportStream, I would like to easily be able to request assistance from the support team so that I can work towards solving my problem.

## Background Info
- When a RS user has an issues with our platform, the only way currently to notify the development/product team is via email - directed personally to team members, or to the share mailbox. Managing inboxes is not fun for anyone, and leads to backlogs of email management and customer communication delays.
- Let's explore creating issue forms in Github. @kjt9cc suggested this: https://beyondco.de/blog/github-issue-forms; This may also auto-tagging of some sort, and will remove the intermediate step of someone in the O&O team or PRIME Ops team having to create tickets.
- We are exploring alternatives using CRM, but actual implementation of that is months away (potentially).
- FYSA: @mlighdc @kjt9cc

**Comment by loripusey** [comment]
O&O is creating a github form to enter tickets for support

**Comment by rachelhanster** [comment]
Noting that @Adrian-Brewster investigated github issues forms. His two observations: 1) To create a ticket, an external user would need a github account. 2) Git is not user friendly.
