### ISSUE TITLE
LIVD Table Needs To Be Updated

### ISSUE THREAD

**Issue by jorg3lopez** [CDCgov/prime-reportstream#2912]
There is a new update for the LIVD table. This is an essential operation as it adds new emerging tests and takes away deprecated ones.

Steps:
* Download LIVD table from here: https://www.cdc.gov/csels/dls/sars-cov-2-livd-codes.html
* Add it to metadata/tables folder
  * follow naming convention to rename the current one
  * follow naming convention by renaming the new one LIVD-SARS-CoV-2-latest.csv
* Check the covid-19 schema and make sure the table property points to the latest table
* Check and change values in the supplemental table for the model name, if it has changed in the SARs table
* Run generatedocs
* Run integration test and end2end

**Comment by Adrian-Brewster** [comment]
Jorge experiencing sign in errors. @MauriceReeves-usds will work with @jorg3lopez to get it merged.

**Comment by Adrian-Brewster** [comment]
Currently 4 updated behind on LIVD. Jorge will work on this today.
