### ISSUE TITLE
ImageMover, Cue - Incorrect Equipment Model Names

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2914]
@MikeC-A6 pulled together a summary of all equipment names in RS for the past 7 days that show incorrect names compared to the LIVD table. Summary attached below.

Next steps:
Reach out to ImageMover and Cue to share these results and determine next steps for resolution with each sender.[https://app.zenhub.com/files/304423150/67338508-64c1-4bda-ae9b-b59b0849ca71/download]

**Comment by anshulkumar-usds** [comment]
[https://app.zenhub.com/files/304423150/2257f802-127a-4c75-a960-8763c82a4fda/download](https://app.zenhub.com/files/304423150/2257f802-127a-4c75-a960-8763c82a4fda/download)

**Comment by anshulkumar-usds** [comment]
Shared results with ImageMover, awaiting reply from sender

**Comment by anshulkumar-usds** [comment]
Shared with Cue as well, awaiting sender reply

**Comment by anshulkumar-usds** [comment]
Cue mentioned the LIVD tables recently changed and will work to fix in their next release.

No word yet from IM.

**Comment by Adrian-Brewster** [comment]
IM acknowledged the issue and is working on a remedy. Same with CUE.  Hoping to deploy corrections this week.

**Comment by Adrian-Brewster** [comment]
Potential solution on our end is building in logic to accommodate * so that we do not need to coordinate with senders going forward.  @MikeC-A6
