### ISSUE TITLE
Reporting on all users who have signed TOS

### ISSUE THREAD

**Issue by HeatherRienks** [CDCgov/prime-reportstream#2917]
Feedback from @mlighdc  on 10/27/21 via Slack and via our conversation on 11/3/21:

**How can we track users who have signed the Terms of Service?**

Currently, we are just able to search the ReportStream general inbox by the address "no-reply@cdc.gov" or subject line "`OrgName` has signed the Terms of Service" 

It is important for us to be able to pull list of users/organizations as we continue to grow our user base.

cc: @kevinhaube

**Comment by loripusey** [comment]
@mlighdc Can you provide us with information on who would need access to see the list of users who have agreed to the TOS and how frequently they would be accessing this information?

**Comment by mlighdc** [comment]
@loripusey I don't have a full list. It would be myself, members of the PRIME team, and anyone on the OGC side.

**Comment by rachelhanster** [comment]
Closing. This problem will be solved once every user has a reportstream login. For now, reportstream general email inbox is functional.
