### ISSUE TITLE
CO - Send OTC Results to TEST

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2919]
CO is interested in review what OTC data ReportStream has available for them. Please send available OTC data to CO's TEST / staging endpoint for their review.

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 will generate a sample for OTC for CO, and submit to CO by 12/3

**Comment by brick-green-agile6** [comment]
@anshulkumar-usds I am unclear about what is needed here. Should I open up all OTC to a test feed for CO?

**Comment by anshulkumar-usds** [comment]
1/23: Anshul checking with CO on what's needed for OTC results

**Comment by anshulkumar-usds** [comment]
CO does not have staffing to address this for the next two weeks. RS needs to circle back with CO in early/mid Feb

**Comment by anshulkumar-usds** [comment]
5/5: CO got back to us that they are willing to test the data. They requested we send this data to their TEST env for their evaluation.

@brick-green-agile6 perhaps something for next sprint?

**Comment by Adrian-Brewster** [comment]
Deprioritized for this sprint.
