### ISSUE TITLE
Run jest tests as Github Action on submit

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#2920]
**Is your feature request related to a problem? Please describe.**
Changed the CdcMap component but forgot to run unit tests locally. Submission didn't get blocked.

**Describe the solution you'd like**
Run all jest test on Github PR creation/updates.

**Describe alternatives you've considered**
Remembering to always do it ourselves locally... but that's a fail.

**Comment by loripusey** [comment]
@TomNUSDS I will bring this up at the Scrum of Scrums today

**Comment by loripusey** [comment]
@TomNUSDS Is this work that needs to be done or a process that needs to be put in place? Is this something that you can bring up in the engineering sync?

**Comment by loripusey** [comment]
@TomNUSDS ?

**Comment by TomNUSDS** [comment]
Done. Closing.
