### ISSUE TITLE
Run prettier to verify everything is formatted correctly on PR add/update.

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#2921]
**Is your feature request related to a problem? Please describe.**
As a developer, I forget to run prettier on my local machine before submitting a PR. I'd like the new/update PR sanity check to reject my request if the prettier needs to clean up any files.

**Describe the solution you'd like**
Github action should just do this.

**Comment by loripusey** [comment]
@TomNUSDS  I will bring this up at the Scrum of Scrums today.

**Comment by loripusey** [comment]
@TomNUSDS Is this work that needs to be done or a process that needs to be put in place? Is this something that you can bring up in the engineering sync?

**Comment by loripusey** [comment]
@TomNUSDS ?

**Comment by TomNUSDS** [comment]
@loripusey A good thing to do is put me in the assignment field. I typically check the queue of things assigned to me to decide what to work on next.

As for this ticket, I'm going to check with @sean-usds to see if this is already done.

**Comment by sean-usds** [comment]
We not run prettier in the pre-commit hook so this is all set
