### ISSUE TITLE
CA - Missing ImageMover Data

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2930]
CA continues to report that ImageMover data is not reaching them. In metabase, we see the following CLIAs assigned to ImageMover and bound for CA; none is reaching CA.

05D2189797
05D2191150
05D2204489
05D2213725
05D2230032
11D2213893
31D2214292
CDPH000077
SA

We now have access to the ACK/NACK inbox: https://ecgqc.healthtechnologygroup.com/ecgqc/home.do 
And a sample message shows a few errors why these message are not reaching CA.

MSH|^~\&|CDC PRIME - Atlanta,^2.16.840.1.114222.4.1.237821^ISO|Inovia Pharmacy^05D2191150^CLIA|CDPH CA REDIE^2.16.840.1.114222.4.3.3.10.1.1^ISO|CDPH_CID^2.16.840.1.114222.4.1.214104^ISO|20211104051500.4434+0000||ACK|d23a3974-73bb-4c44-9af3-796dba676171|P|2.5.1|||NE|NE|USA|UNICODE UTF-8|||PHLabReport-NoAck^ELR_Receiver^2.16.840.1.113883.9.11^ISO
MSA|AR|d23a3974-73bb-4c44-9af3-796dba676171|
ERR||OBR^5^2^1^1^|101^Required field missing|E|Required component missing in segment 5:OBR.  Field 2, repetition 1 is missing component 1, which is required in data structure 2.5.1CA:EI
ERR||OBR^5^3^1^1^|101^Required field missing|E|Required component missing in segment 5:OBR.  Field 3, repetition 1 is missing component 1, which is required in data structure 2.5.1CA:EI
ERR||OBR^5^22^^^|101^Required field missing|E|Required field missing in segment OBR. Missing field 22 which is required in segment structure 2.5.1CA:OBR. 
ERR||OBX^6^17^1^1^|102^Data type error|E|Component size restriction exceeded in segment 6:OBX.  Field 17, repetition 1, component 1 is larger than data structure 2.5.1CA:CWE permits it to be.
ERR||OBX^6^18^1^4^|101^Required field missing|E|Required component missing in segment 6:OBX.  Field 18, repetition 1 is missing component 4, which is required in data structure 2.5.1CA:EI
ERR||ORC^4^2^1^1^|101^Required field missing|E|Required component missing in segment 4:ORC.  Field 2, repetition 1 is missing component 1, which is required in data structure 2.5.1CA:EI
ERR||ORC^4^3^1^1^|101^Required field missing|E|Required component missing in segment 4:ORC.  Field 3, repetition 1 is missing component 1, which is required in data structure 2.5.1CA:EI
ERR||SPM^7^2^1^2^1|101^Required field missing|E|Required subcomponent missing in segment 7:SPM.  Field 2, repetition 1, component 2 is missing subcomponent 1, which is required in data structure 2.5.1CA:EI.

**Comment by anshulkumar-usds** [comment]
Also need to check with @MauriceReeves-usds if we can receive these acks and nacks to our SFTP, or can pull from CA's SFTP

**Comment by brick-green-agile6** [comment]
@anshulkumar-usds this will be fixed by [#2897](https://github.com/CDCgov/prime-reportstream/pull/2897) from @jorg3lopez . After the fix has been deployed we can look at a data resend.

**Comment by Adrian-Brewster** [comment]
Resent but CDPH replied with additional NACKS.

**Comment by brick-green-agile6** [comment]
New NACKS included OBR-2.1 and OBR-3.1 which have already been addressed by a fix from Jorge. The other errors are:

-  OBX-17.1 exceeded max length. The HL7 spec has the limit at 20 chars. I asked CA if that is the limit they are requiring.
- OBX-18.4 is a required field. I asked CA what that value should be.

**Comment by brick-green-agile6** [comment]
Feedback from Ellaison:

- OBX-71.1 – Character length exceeded
     - **From Ellaison:** We have been using “PCR”, “Antigen”, or “AB” for the type of test and then OBX-17.2 for the longer device description.  The second component has a much longer character limit (199) so the full manufacturer and device name can be populated there.  
- OBX-18.4 – Required field missing
     - **From Ellaison:** Are you sending something in OBX-18?  The entire field can be blank.  I suspect if one component is populated than others may be required.

**Comment by anshulkumar-usds** [comment]
Summary of outstanding items and next steps:

On 12/1 @brick-green-agile6 notified CA that OBR-2.1 and OBR-3.1, which were previously noted as missing fields, have been corrected.

Outstanding items:
1. OBX-17.1: Character length exceeded
Needs more discussion with CA. Per CA, for 12.1we have been using “PCR”, “Antigen”, or “AB” for the type of test and then OBX-17.2 for the longer device description.  The second component has a much longer character limit (199) so the full manufacturer and device name can be populated there.  

2. OBX-18.4: Entire OBX-18 segment should be set to blank

**Comment by brick-green-agile6** [comment]
added most recent NACK report to sharepoint. Here is the breakdown:

- 59% of them concern OBX-17 and OBX-18 which has already been fixed. 

- 40% concern missing OBR-2.1. That is a new error that I will need to investigate

- 1% are a mix of missing MSH-4.3, length exceeded OBR-16.1, length exceeded OBX-23.1 

https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Onboarding%20%26%20Operations/CA%20Onboarding%20Operations/ReportStream_CCRS%20Prod_ACKNACK_12032021.xlsx?d=wd21ce65a8b524117adb442de8819bba6&csf=1&web=1&e=BNsZ5o

**Comment by brick-green-agile6** [comment]
Most recent OBR-2.1 NACK is from 11/10. We can consider that issue to be resolved

**Comment by brick-green-agile6** [comment]
@anshulkumar-usds are there any newer NACK messages in the shared inbox?

**Comment by Adrian-Brewster** [comment]
I just checked @brick-green-agile6 and I do not see any new NACK messages in the shared inbox

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 @Adrian-Brewster The acks or nacks would come to Optum inbox, not our shared mailbox. I'll check and get back to you on this.

**Comment by Adrian-Brewster** [comment]
CDPH may request so resubmissions, but closing as this issue has been addressed.
