### ISSUE TITLE
Onboarding for Abbott and Lifepoint

### ISSUE THREAD

**Issue by jbiskie** [CDCgov/prime-reportstream#2950]
## Problem statement

Abbott and Lifepoint need to be set up as senders.  Abbott needs a pared down version of the direct schema available.

## Acceptance criteria

Abbott and Lifepoint are set up as senders in RS and Abbott has a working schema associated.

**Comment by hermanAlexCordero** [comment]
Reviewed the issue with special characters showing in the API response when the transaction errors.

Tested the sample files against my local instance.  The special characters transfer to the back end correctly even though the response file 
Source String:
54-testíd-hásh
Response:
54-testï¿½d-hï¿½sh
Back End File:
54-testíd-hásh

**Comment by hermanAlexCordero** [comment]
Reviewed the issue with special characters showing in the API response when the transaction errors.

Tested the sample files against my local instance.  The special characters transfer to the back end correctly even though the response file alters the characters.
Source String:
54-testíd-hásh
Response:
54-testï¿½d-hï¿½sh
Back End File:
54-testíd-hásh
