### ISSUE TITLE
Unknown `text/html` urls return 404 instead of being routed to react's root index.html page.

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#2952]
**Describe the bug**
Single Page Apps (SPAs) don't issue http requests to load "pages", but they do change the url path in the Address Bar to make it look like the pages are being changed. 

This path is "abstract" and doesn't lead to an actual page on the server. So, browser refreshing the page and bookmarks won't work correctly.

This is a common issue with SPA setups.

**Impact**
Deep links and browser refreshes result in 404 errors from the web server.

**To Reproduce**
1. Go to https://staging.reportstream.cdc.gov/
2. Use react to "navigate" to the About in the navbar (React's SPA means no http requests happen, but notice the address bar's url changes).
3. Once on https://staging.reportstream.cdc.gov/about (and it loads successfully), hit refresh.
**Result**: webserver returns 404.

**Expected behavior/Additional context**
The old "crawl" basically put a copy of the index.html and the javascript files into each possible url path. 
This could just be a file system alias or a http server mapping. The redirect should include all `text/html` media type requests, but NOT other types (e.g. `image/jpeg`, `text/css`, etc).

**Comment by TomNUSDS** [comment]
Suggestion from [here](https://medium.com/medialesson/best-way-to-host-a-single-page-application-spa-in-microsoft-azure-3e70cbd075c3) (in the _ Azure App Service_ section).

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <rewrite>
      <rules>
        <rule name="SPA" stopProcessing="true">
          <match url="^(?!.*(.js|.css|.png|.jpg|.ico|.svg)).*$" />
          <conditions logicalGrouping="MatchAll">
          </conditions>
          <action type="Rewrite" url="/"  appendQueryString="true" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>
```

**Comment by TomNUSDS** [comment]
There's an alternate solution. Switch the React app from using url paths to using fragment identifier.

> So we simply changed the routing in the app itself to use a fragment identifier. So instead of expecting `http://hostname.com/path/to/content`, the app now expects `http://hostname.com/#/path/to/content`. That way, index.html is always being served by default, without URL rewriting and without using the ‘Override backend path’ setting. This may negatively affect indexation by search engines ...

I'm going to do more research down this path.

**Comment by cwinters-usds** [comment]
Sounds good. I'll keep that solution in mind while researching the security headers stuff, there may be overlaps there in implementation.

**Comment by TomNUSDS** [comment]
@cwinters-usds I'd like to try an experiment. 

If there's a `404.html` will that automatically load when a page isn't found?

If so adding this to the package.json might be enough?

`"postbuild": "cp build/index.html build/404.html",`

I'm going to do a PR with just this change, if nothing else, it shouldn't break anything.
https://github.com/CDCgov/prime-reportstream/pull/2958
