### ISSUE TITLE
Conduct CSV Uploader Pilot

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2954]
## Problem Statement
As the Experience Team, we need to pilot the CSV Uploader with reporting entities and PHDs so that we can understand whether ReportStream via the CSV Uploader using a standard schema will get used.

## [Hypotheses](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1638985599379/3d76a25d28d21d28d698f30146322677e9f3ab4b?sender=ud3aa760e30b39bcf436d4473)
- Hypothesis: Senders find ease in complying with ReportStream's data schema, enough to switch from existing reporting process/tool.
- Hypothesis: Reportstream's data processors function as expected and delivers lab results to the appropriate STLT in HL7 format.

## Goals
- Get to 2 STLTs and 10 entities who use ReportStream daily for at least 5 business days

## Key Indicators
-

**Comment by rachelhanster** [comment]
Uploader experiment is done and closing this initiative. Summary doc is here in [CDC sharepoint.](https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Pilots/CSV%20Uploader/ReportStream%20CSV%20dataset%20and%20quality%20improvements.pptx?d=wde566704b7f34b2e9eaa332b8fe7cd0b&csf=1&web=1&e=LtUAUf)
