### ISSUE TITLE
Clark County Download Site - CSV Format

### ISSUE THREAD

**Issue by jorg3lopez** [CDCgov/prime-reportstream#2971]
Clark County has requested the test results to be in csv format.

 Steps to follow:
* Create csv schema for Clark County, OH
* Update org file to reflect csv format

**Comment by Adrian-Brewster** [comment]
Moving HL7 to CSV.  Jorge will work on this today. Will then resubmit files

**Comment by jorg3lopez** [comment]
@Adrian-Brewster @anshulkumar-usds Submitted settings changes to prod this morning.

**Comment by anshulkumar-usds** [comment]
Converted to csv on 12/27.
