### ISSUE TITLE
CA - NCES School ID

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2973]
CA is interested in receiving NCES school ID in their HL7 messages from ReportStream.

- RS shared the APHL guidance on how to incorporate this for receivers
- Waiting for CA to get back to us and advise on next steps
- Will need to work with Rick Hawes to update the settings internally

**Comment by RickHawesUSDS** [comment]
@anshulkumar-usds So wait until CA gets back to us.

**Comment by anshulkumar-usds** [comment]
Blocked: Need next steps from CA
