### ISSUE TITLE
CA - Setup SFTP to pull ACKS and NACKS from Optum

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2974]
To manage the ACKS and NACKS workflow for CA, we need to consider setting up a connection to Optum's SFTP folders. Need to be further groomed.

- One option is for Optum to use subfolders to differentiate between primary and secondary ACKS and NACKS
- Sample NACKs can be found in this ticket 2930
https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/2930

Current state:

- CA provides secure access to Optum hosted ECG Inbox that contains ACKS and NACKS in HL7: Access path and credentials here: https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Onboarding%20%26%20Operations/CA%20Onboarding%20Operations/CA%20ACK%20NACK%20Inbox%20Creds.docx?d=w824f2384e0b3477e81c8444234e9ee39&csf=1&web=1&e=5Mbzqv

- CA can send these HL7 messages to RS, or RS can pull them from an SFTP location at CA

- CA can also expose this data with a SOAP API - this is similar the method PA is currently using. @MauriceReeves-usds has more details on this.

Next steps
- Review available options and setup an automated process to review and flag NACKs
- Consider options to scale this effort across other states, and make it a standard across RS onboarding receivers

**Comment by anshulkumar-usds** [comment]
CA pushing to RS may not be possible - not in scope with our ATO - check with Chris Winters if this is possible for RS
RS can pull from CA/Optum - no current process
1. New type of transport, ingestion and processing in our blob store
2. Ideal - API endpoint, emulate what we get from senders,. Ingest ACKS and NACKS and save them in our DB
3. Check if there is a proposal for this in RS

**Comment by anshulkumar-usds** [comment]
How is AIMS processing ACKS and NACKS? Do we have an industry best practice? What is the standard in this space?

Possible discussion point with pipeline team.

**Comment by anshulkumar-usds** [comment]
Plan to demo CA workflow to Pipeline team to 11/29 as one use case from a state.

**Comment by anshulkumar-usds** [comment]
@rhood23699 and @hermanAlexCordero requesting your assistance on managing the ack and nack workflow for CA. I can provide more details in our standup. For now, we need to parse the messages from CA, and categorize them into themes for resolution among RS, state or sender.

**Comment by RickHawesUSDS** [comment]
@anshulkumar-usds can you provide example CA ACK and NACK messages?

**Comment by anshulkumar-usds** [comment]
@RickHawesUSDS Credentials to the Optum inbox where the ACKs and NACKs are delivered, as well as sample ACKS and NACKs can be found here:

https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Onboarding%20%26%20Operations/CA%20Onboarding%20Operations?csf=1&web=1&e=ktL56O

**Comment by RickHawesUSDS** [comment]
@anshulkumar-usds It's going to send an access code to the email address for the account, which I don't have, because I'm using a new browser. I think we need to pair to make this access work.

**Comment by anshulkumar-usds** [comment]
Need to gather additional details from Optum on 12/22

**Comment by anshulkumar-usds** [comment]
Per Brick, CA suggested the SOAP method for ACK/NACK workflow.

Determined next steps with @brick-green-agile6 and @RickHawesUSDS
