### ISSUE TITLE
Research/Negotiate OKTA Page Re-branding

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2980]
## Acceptance
- Determine if we can re-brand OKTA pages (login, help, forgot password) that currently say "Simple Report" to say something that is inclusive of ReportStream

## Background
- Help page: Content would be the same for Simple Report and ReportStream but the header says "Simple Report"
[https://hhs-prime.okta.com/help/login](url)

## TO DO
- Talk to Simple Report branding/design folks to see if this is possible (e.g. Leslie, Tim)

**Comment by drew-usds** [comment]
Updates from[ related SR issue](https://github.com/CDCgov/prime-simplereport/issues/2833). TL;DR = Okta might not let us differentiate these static content pages in the same way we can with emails.

> drew-usds commented 5 days ago
> Are there also similar options to differentiate what content shows up on any of the hhs-prime.okta.com/* pages? Ex: login help, or password reset? Currently those pages show the SimpleReport logo.

> emmastephenson commented 5 days ago • 
Thank you both! I think sorting by groups within the workflow is likely our best option. @drew-usds, I'm not sure about the options available to differentiate content on the login or password reset pages, but I'll look into it.
>
> I did just try to start creating a workflow in our Preview account, and it looks like it's not an option that's enabled for us just yet. I got in touch with Michael & Dale, but I suspect this might be something additional we have to add to the contract 😞
>
> Just heard back from Okta; they do indeed have to turn Workflows on but Dale doesn't have permission to do that in production. Sounds like they're working on their end to enable it.

**Comment by drew-usds** [comment]
Possible workarounds given the above comment:

- Use CDC branding for the Okta account
  - Swap the SR logos to a CDC one
  - Make sure we scrub any specific mentions of SR from those generic pages
- Create our own login flow with dedicated RS help pages
