### ISSUE TITLE
Give users ability to change their passwords

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#2981]
## Problem Statement
Users are unable to reset their password. Their workaround is to select "forgot my password" and go through that flow

## Acceptance Criteria
- Given I
    - Am a ReportStream user who wants to change their password
- When I
    - Log in
    - Select "change my password"
- Then 
    - I am taken to a form for changing my password

**Comment by bgantick** [comment]
Closing - this is currently achieved via the "Forgot password?" link (`/signin/forgot-password`)
