### ISSUE TITLE
Ignore the presence or absence of asterisk characters for Test Equipment name fields

### ISSUE THREAD

**Issue by MikeC-A6** [CDCgov/prime-reportstream#2985]
As a sender, I want to be able send in a test equipment name value from either column M or column B from the [LIVD table](https://www.cdc.gov/csels/dls/documents/livd_test_code_mapping/LIVD-SARS-CoV-2-2021-10-27.xlsx) with or without an asterisk so that Reportstream can look up related fields using the LIVDMapper() function.

Design considerations:
The LIVD table column in question is Model, and the value in the table may or may not have the *.  It is thought that senders are told that some model they are sending to us is incorrect and to add the *, but they may be doing a blanket add and hence some other data may or may not come with *.

Acceptance Criteria:

1. *Given* that I am a sender, and *when* I send in a value for Model ID (column B) that does not contain an asterisk when an asterisk should be present in that value, *then* the LIVDMapper() function is able to look up and populate the lookup fields

2.  *Given* that I am a sender, and *when* I send in a value for Test_Kit_Name_ID (column M) that contains an asterisk when an asterisk should not be present in that value, *then* the LIVDMapper() function is able to look up and populate the lookup fields

**Comment by carlosfelix2** [comment]
Artifact with more information and examples of Equipment model names
[https://app.zenhub.com/files/304423150/43a9e1e8-c21d-4923-ba3b-8f91ab61f22c/download](https://app.zenhub.com/files/304423150/43a9e1e8-c21d-4923-ba3b-8f91ab61f22c/download)

**Comment by HeatherRienks** [comment]
@carlosfelix2 - do you have any updates on this ticket? Thanks!

cc: @loripusey
