### ISSUE TITLE
MN Suppress SPM-2-1 And Resend Failed Messages

### ISSUE THREAD

**Issue by jorg3lopez** [CDCgov/prime-reportstream#3003]
MN has asked us to suppress SPM-2-1 which came with the fixes for OBR-22.  Once this is done we need to resend the three failed messages.

#### Specimen id
1.	61804-95209-3-R113-20210914 
2.	58088-95209-3-R2574-20210921
3.	d1f90347-832a-48b3-bd85-085cd07bacaf

**Comment by mlighdc** [comment]
Emailed MN about the fixes were deployed today and 3 files resent. Awaiting confirmation the issue has been resolved.

**Comment by anshulkumar-usds** [comment]
This issue also persists for STRAC messages. Anshul alerted MN that a fix will be rolled out on 11/16. We need to resubmit files to MN again and confirm their delivery before closing this issue. This will also include the fix to suppress SPM-2.1.

@jorg3lopez please plan to resubmit the relevant files on Tuesday. I will inform MN on the plan.

**Comment by jorg3lopez** [comment]
@anshulkumar-usds I submitted the fix into production a few minutes ago. The fix is in effect as of now, we don't have to wait until Tuesday. The org file gets updated directly through the command line and not through the deployment. I don't see any records of MN failed messages, this is something we can ask them; to send us the message ids from the failed messages so we can resend them.

**Comment by anshulkumar-usds** [comment]
Thanks @jorg3lopez . I'm following up with MN to see if/what needs to be resubmitted.

**Comment by mlighdc** [comment]
MN successfully received the 3 messages that were resent. Received confirmation on Friday, 11/12/21.
