### ISSUE TITLE
Results show page has errors with report ID

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#3011]
**Describe the bug**
If a user clicks through to a report show page, they can see the full details including the list of facilities. If you refresh the page (or go back and click through to the same report), you get an error and a few empty fields. Shows up on localhost/staging/prod.

![Screen Shot 2021-11-10 at 1.26.18 PM.png](https://images.zenhubusercontent.com/5ff50e49f74e134e95117280/5215ef0a-9b06-421a-bc96-16210ac0ed7f)

**Impact**
Please describe the impact this bug is causing to your program or organization.

**To Reproduce**
1. Log in
2. Click on report show page
3. Refresh the report show page (or click back and then click through to the same report)

**Expected behavior**
Report show pages shouldn't show errors when refreshing or navigating around.

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kevinhaube** [comment]
@drew-usds Apologies for not linking them, but PR #3025 fixed 1/2 of this bug and has been merged. I'll dig into it further and see if I can't figure out why `reportId` isn't properly being passed in on refresh.
