### ISSUE TITLE
When logged out and viewing the login page, can't go back to previous page

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#3013]
**Describe the bug**
When logged out of the application and viewing the `/login` page, you can't navigate back to the previous page you were on. Page just reloads `/login`.

**Impact**
Users could get stuck navigating the app when logged out.

**To Reproduce**
1. Go to `/login`
2. Click back in your browser
3. Page infinitely will go back to `/login`

**Expected behavior**

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chris-kuryak** [comment]
Tried to reproduce bug. Was unable to. Clicking the back button on Login page works properly (takes me to previous page).
