### ISSUE TITLE
Right clicking a CSV download link saves "download.html" and not the CSV

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#3014]
**If this is easy then we want to go ahead and fix this, if not easy then discuss with the team**

**Describe the bug**
Left clicking on the "CSV" download link for a report on the report index works. Right clicking and choosing "save link as" (Using a mac, but equivalent on Win) does not download the CSV, it downloads "download.html" instead.

**Impact**
Users might have trouble if they choose to download files with "save as"

**To Reproduce**
1. Log in
2. Download a CSV from the report index (`/daily-data`) with a left click ... works!
3. Try downloading a CSV using the right click save as menu ... downloads the html file

**Expected behavior**
A CSV should be able to be downloaded using "save link as".

**Screenshots**

![Screen Shot 2022-04-15 at 9.42.11 AM.png](https://images.zenhubusercontent.com/5a6b4b784b5806bc2bc46da6/23e9da3a-e64f-431a-84ae-0596f78edb68)

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kevinhaube** [comment]
Fixed long ago :)
