### ISSUE TITLE
IA - Onboarding

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#3021]
The following items, generally in order, must be completed to successfully onboard a receiver to ReportStream:

* [ ] Added to organization.yml
* [ ] Added to organizations-local.yml
* [ ] Added to staging settings table
* [ ] Added to prod settings table
* [ ] Added at least one receiver
* [ ] Added OKTA group to download site
* [ ] Added customers to OKTA group for download site
* [x] Is customer contact made?
* What doc format are we supporting for the receiver (HLV, CSV, other)? **(Add comment below)**
* What transport(s) are we supporting for the receiver (SFTP, other)? **(Add comment below)**
* [ ]  Got credentials?
* [ ] Tested ELR connection locally?
* [ ] Tested ELR connection from Azure?
* [ ] Has the receiver accessed the download site?
* [ ] Has the receiver been sent at least one test file?
* [ ] Has the receiver signed off on file formatting?
* [ ] Are there labs sending data?
* [ ] Has the receiver confirmed receipt of the data?
* [ ] Have the files processed successfully?
* [ ] Are we in production?

**Comment by mlighdc** [comment]
- Met with IA team on 11/10/21 to kick-off onboarding process
- Have received Implementation Guide
- Frequency - every 2 hours is fine
- Have requested SFTP credentials
- Will work with  team to onboard SimpleReport facilities

**Comment by anshulkumar-usds** [comment]
Checking with IA on their preference for secondary feed and OTC data

**Comment by anshulkumar-usds** [comment]
Shared OTC updates, primary and secondary feed, and option to receive either on the download site.

@Adrian-Brewster please get back to Ellen on the IP whitelist topics

**Comment by mlighdc** [comment]
I responded to IA regarding the IP whitelist and sent her our range.

**Comment by Adrian-Brewster** [comment]
Hi Ming and Anshul,

Sorry - after being out for bereavement leave last Friday and being sick
today I’m still playing catch up on emails. Ming, it looks like you sent IA
the IP range via secure email. Let me know if there is anything I can help
with!

Adrian

**Comment by anshulkumar-usds** [comment]
IA does not want any OTC results made available to them. Please filter out any results that do not have a valid CLIA.

**Comment by MauriceReeves-usds** [comment]
@Adrian-Brewster @Adrian-Brewster @mlighdc moved this into "In Progress"

**Comment by anshulkumar-usds** [comment]
Updated priority given our SLAs

**Comment by anshulkumar-usds** [comment]
Feedback from IA after first file submissions on 1/6/22:

MSH-3.1 -   SendingApplication/NamespaceID - We can only accept 20 characters.
MSH-4.1 -   SendingFacility/NamespaceID - We can only accept 20 characters.
PID-3.1 -   PatientIdentifierList/IDNumber - We can only accept 15 characters.
PID-3.4.1 - PatientIdentifierList/AssigningAuthority/NamespaceID - We can only accept 20 characters.
PID-3.6.1 - PatientIdentifierList/AssigningFacility/NamespaceID - We can only accept 20 characters.
ORC-2.1 -   PlacerOrderNumber/EntityIdentifier - We can only accept 20 characters.
ORC-2.2 -   PlacerOrderNumber/NamespaceID - We can only accept 20 characters.
ORC-3.1 -   FillerOrderNumber/EntityIdentifier - We can only accept 20 characters.
ORC-3.2 -   FillerOrderNumber/NamespaceID - We can only accept 20 characters.
OBR-2.1 -   PlacerOrderNumber/EntityIdentifier - We can only accept 20 characters.
OBR-2.2 -   PlacerOrderNumber/NamespaceID - We can only accept 20 characters.
OBR-3.1 -   FillerOrderNumber/EntityIdentifier - We can only accept 20 characters.
OBR-3.2 -   FillerOrderNumber/NamespaceID - We can only accept 20 characters.
SPM-2.1.1 - SpecimenID/PlacerAssignedIdentifier/EntityIdentifier - We can only accept 20 characters.
SPM-2.1.2 - SpecimenID/PlacerAssignedIdentifier/NamespaceID - We can only accept 20 characters.
SPM-2.2.1 - SpecimenID/FillerAssignedIdentifier/EntityIdentifier - We can only accept 20 characters.
SPM-2.2.2 - SpecimenID/FillerAssignedIdentifier/NamespaceID - We can only accept 20 characters.

**Comment by anshulkumar-usds** [comment]
Working on truncation for Patient ID
