### ISSUE TITLE
MA Missing OBR-22 In Messages From STRAC

### ISSUE THREAD

**Issue by jorg3lopez** [CDCgov/prime-reportstream#3022]
MA has reach to us (2021-11-11) letting us know that OBR-22 is missing in some messages. There was a fix pushed to production for this same issue (Image Mover). After further investigation, it was noticed that reports coming from STRAC had the issue. 

### Action
- Add the test result released date to OBR-22 in the STRAC schema

**Comment by Adrian-Brewster** [comment]
FIx is in. Included in test data sent on the 24th.

**Comment by anshulkumar-usds** [comment]
12/20: Checking with MA on next steps.

**Comment by anshulkumar-usds** [comment]
@jorg3lopez MA replied with the files then need to be resubmitted.

**Comment by anshulkumar-usds** [comment]
The following files need to resubmitted to MA:

767294
d48bf41a-b686-42bd-8c25-17e0f91591c1
740086
758361
778515
818558

**Comment by jorg3lopez** [comment]
@anshulkumar-usds All the files were sent on 12-28-2021 except for `d48bf41-b686-42bd-8c25-17e0f91591c1`. 
File names:
**prime-20211228213300
prime-20211228213400**
I'm further looking into `d48bf41-b686-42bd-8c25-17e0f91591c1`

**Comment by anshulkumar-usds** [comment]
@jorg3lopez you mentioned this is resolved. Can you share which files have been resubmitted to MA so I can follow up?

**Comment by anshulkumar-usds** [comment]
Shared with MA - closing this
