### ISSUE TITLE
Lighthouse issues with the CSP

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#3038]
Related to #2228 

We've implemented the CSP (Content Security Policy header) that the Lighthouse was complaining about and we're up to 93%, but it appears there is one more recommendation:

> Host allowlists can frequently be bypassed. Consider using CSP nonces or hashes instead, along with 'strict-dynamic' if necessary. (For `script-src` part of CSP)

Currently, that section is:
> `script-src 'self' https://hhs-prime.okta.com https://global.oktacdn.com https://www.google-analytics.com https://*.in.applicationinsights.azure.com`

**Comment by TomNUSDS** [comment]
It seems the risk is associated with the whole domains we're giving for the `script-src`. ANY script on `hhs-prime.okta.com`,` global.oktacdn.com`, `www.google-analytics.com` or `*.in.applicationinsights.azure.com` can run. (So for example, `global.oktacdn.com` would need to be serving up malicious code). 

The concern with nonces or hashes in the CSP might be keeping hashes synced up as scripts change since the http header is fairly tricky to change dynamically.

`strict-dynamic` is a newer header (part of CSP3) and I'm not familiar with it. So, more research is still needed.

**Comment by TomNUSDS** [comment]
Notes: 
 - We might be able to change the `script-src` to just be `'self'`. Looking at how the okta widget works, it seems like it's ONLY loading script from our react app and making ajax requests to okta.
 - This will create issues when we go to add analytics _scripts_ that load remotely from a CDN. We can add a `'sha256-###'` to the `script-src` which is a checksum for every remote script we execute, but it's fragile.
 - We _might_ be able to host the analytics script on our server, but this approach isn't common.
 - Unfortunately, the recommended `noone` approach requires the server insert a one-time code into the CSP header **AND** the same value into the page returned inside the `<script>` tag. This is fine for traditional http servers, but presents challenges when there's a CDN proxy and/or the site is all static pages.

**Comment by TomNUSDS** [comment]
@cwinters-usds I'd like to try an experiment on staging once things are stable there.

I'd like to change the CSP's `script-src` section to remove all the domains and just have `'self' 'strict-dynamic'` and see if our site works correctly. 

> ` script-src 'self' 'script-src' ; `

I think might be issues when we add analytics support (since this typically loads from a remote script).

**Comment by TomNUSDS** [comment]
Related to #2648

**Comment by cwinters-usds** [comment]
@TomNUSDS I'm totally up for trying that; let's sync up on a time where I can modify it in staging and the team can observe the results.

**Comment by TomNUSDS** [comment]
I think the fundamental problem is we're using `style-src: 'unsafe-inline'`.

@drew-usds 
Chris and I tried to remove this option but the images referenced in content.json were being blocked. (e.g. `"icon": "cdc-logo.svg",`)

I suspect the `dangerouslySetInnerHTML` is what's triggering it.

```html
                <p
                    data-testid="summary"
                    className="usa-prose"
                    dangerouslySetInnerHTML={{ __html: cleanSummaryHtml }}
                ></p>
```

But I need to get CSP somehow working on my local dev server... Maybe with a META approach? `<meta http-equiv="Content-Security-Policy" content="default-src 'self'">`

Here's the current CSP:
```
content-security-policy: 
  default-src 'self'; 
  
  script-src 'self' https://hhs-prime.okta.com https://global.oktacdn.com https://www.google-analytics.com https://*.in.applicationinsights.azure.com; 
  
  style-src 'self' 'unsafe-inline' https://global.oktacdn.com https://cdnjs.cloudflare.com; 
  
  frame-src 'self' https://hhs-prime.okta.com; img-src 'self' https://hhs-prime.okta.com https://reportstream.cdc.gov data: ; 
  
  connect-src 'self' https://www.google-analytics.com https://*.in.applicationinsights.azure.com https://hhs-prime.okta.com https://reportstream.cdc.gov/api/ https://prime.cdc.gov/api/
```

**Comment by TomNUSDS** [comment]
Seems like the `<SpinnerCircular>` component modifies style on-the-fly and fails. We'll need to find a different solution.

**Comment by drew-usds** [comment]
@TomNUSDS Sorry I hadn't seen this @mention until now!

We can delete any of the `"icon": "foo",` references in `content.json`. We were using them in a previous iteration of the homepage, but not presently.

If it's helpful to resolve problems elsewhere let's just strike them.

**Comment by bgantick** [comment]
Need to follow up to see what still needs to be done here cc @TomNUSDS

**Comment by kevinhaube** [comment]
Our CSP is passing Lighthouse without any alerts/errors. Closing this!
