### ISSUE TITLE
FL - 4 files for fl-hillsborough-phd.elr-download Batch step failed due to different schemas in same batch

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#3039]
A bug that occurred on Saturday Nov 13, 2021, as aftermath of Friday Nov 12 deployment:

It looks like fl-hillsborough used to have the wrong schema, and it was fixed during a deployment on Friday, which is all well and good.   However, this caused the Saturday 9:15am ET merge of 4 reports destined for fl-hillsborough to fail, because it happened to be a mix of the old and new/corrected schema names, and our code rightly refuses to merge different schemas together.

This is a new manifestation of a problem we have long known about - that deploying schema changes is currently fraught with possible difficult-to-fix errors as old and new formats clash.  One solution would be to give the batch queue an enema prior to doing a deployment, but it would have to be done carefully (atomically with the deploy), because new data is coming in so rapidly these days.

This query shows the 4 reports that are stuck waiting for Batch, in the task table:

`select created_at, item_count CNT, report_id, next_action, next_action_at, schema_name from task where next_action_at = '2021-11-13 14:15:00+00' and receiver_name = 'fl-hillsborough-phd.elr-download' order by created_at ;`

![image.png](https://images.zenhubusercontent.com/5ff48b04da86ca0cf2bcf625/f87dcc6b-d2b4-4de9-9f5e-0ed74feb1060)

**Comment by anshulkumar-usds** [comment]
Anshul notified receiver contacts of delayed files. Will need to provide another update when files are delivered.

**Comment by mlighdc** [comment]
@anshulkumar-usds Colorado emailed me Monday at 10:30 am Eastern about not receiving files since Friday. Will cc you on my reply but assumed that they should have gotten an email from you.

**Comment by brick-green-agile6** [comment]
Talked to @MauriceReeves-usds about this. If files are re-ran for Hillsborough they will also be sent to Florida. @anshulkumar-usds we will need to get sign off from Florida that duplicate records will not cause a problem in their system. Can you coordinate that with them?

**Comment by anshulkumar-usds** [comment]
Emailed FL and copied both FL-state and Hillsborough POCs. @brick-green-agile6 you're copied too, so please follow up in my absence this week.

**Comment by brick-green-agile6** [comment]
Kristin from FL said she would follow up on 11/29 to let us know if duplicate results are acceptable

**Comment by anshulkumar-usds** [comment]
FL-state is hesitant to ingest duplicate records. Hence, we shared accession IDs of missing records for the county. The county will reference these to work with the state. No action needed from RS at this time until we hear from county.

**Comment by anshulkumar-usds** [comment]
Veena from Hillsborough is checking with the state to get the needed results. Will follow up on 12/6 to see if issue can be closed.

**Comment by Adrian-Brewster** [comment]
FL responded that they no longer need these.
