### ISSUE TITLE
AZ - Missing Specimen ID

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3045]
On 11/12, 6:51 PM, AZ reported that in the file received on 11/11, the Specimen_ID column was left blank for many entries. This is a required field for AZ, so we need to do the following:

1. Understand what is missing 
2. Repopulate the file missing specimen IDs and submit to AZ
3. Understand root cause of why this field was left blank
4. Can we implement internal checks within RS to prevent this from happening again

Assignee needs to provide AZ with an ETA for completion.

**Comment by Adrian-Brewster** [comment]
@jorg3lopez Any update on this?

**Comment by jorg3lopez** [comment]
@Adrian-Brewster Waiting to hear back from AZ if they have had any issue with test results missing the specimen id.

**Comment by anshulkumar-usds** [comment]
@jorg3lopez to resubmit file to AZ. 
Filename reported by AZ containing original issue: az-covid-19-7709172d-b72a-49ff-bbfe-2aa7b3370d01-20211111141513

**Comment by anshulkumar-usds** [comment]
@jorg3lopez below is the list of message IDs AZ would like us to resend:

Patient_ID
f00f7b72-10a3-48d6-bdda-6e8135ab52e1
bdcb261d-a7e5-4704-93f1-47caafbb84b4
976021cd-752f-4118-8ed9-5a0e57a312a0
59d8c126-28ea-4c98-b8fe-f9cefa12f7c7
eb77a449-fd11-4afb-a2be-7622f7847316
27458e20-6b9f-44da-84cd-70d8110776ef
37cfc3c0-50a9-41ee-848a-c7da51c027af
dc917219-e04f-49ca-9a65-f9d8979cbe40
b6ce44b3-ef30-4569-a19f-4aa401a4bae0
ed3663ad-0f90-4310-9cb1-50f1e03fba2e
6ea25ad3-cadb-4a10-be2a-1469f77f342d
faeac554-bdab-4d05-88a2-4e9e38809aaf
e88e06dc-1741-45f5-997a-6805fa578ba9
42d8bcbc-4229-4257-b159-f9c9778d9982
f45b8d28-4db1-4522-b897-513271056e1e
2064d014-4c51-42ff-a50d-ec20781849c9
7bcc6db6-ccc6-4eff-82f2-7e3e55c7b48e
d36c907e-acca-4511-bd7d-3edf64670bc9
ac6a3ee8-0ffc-4b2d-a16b-5d8d4f088073
e02649c2-fb40-4560-bcbd-75c15c7023d3
2d5ca4ac-f747-48c8-8a61-78b5bcf2a344
d94618aa-dfab-4c3a-bfa1-b8845336c112
5aa215b5-fe2a-4de4-aa6f-4faf28f77c74
b970bdab-611a-4bd7-9285-82f235e7b495
61365eb8-abe8-43db-9fef-a1346e9bf4dd
176860ef-9f29-4c24-9f26-783d596ea225
cc463a83-77d6-4791-9077-e51308ddf2a3
4853c18d-d866-4fb9-835d-d4484ca45451
3ecdaa5e-fce5-41a2-89bf-86520832e0cb
0944ce24-ed88-4e3f-bd61-138219b3e7d0
a0776b7a-a9e7-4337-b064-47ebaa2aeec6
76d94d66-ad78-4bd8-8674-5afdef20e969
399077c4-a1ca-4b38-b9b7-a0e175ef0b8c
514d9238-4ed9-491f-b988-d36febcc4452
be5b936f-5b09-46c5-8b00-5c9d1386dba6
61ee0627-1076-48e5-91c3-3268c05f4c83
d7b45edb-0f12-4771-9cb4-bfb0159a36f8
2ee473e2-d0d0-40ed-a1d1-f89ecf7c34a6
078bde9b-a2b9-44f4-8ecb-4ff824e01041
27128dab-8bc7-45c5-9c6e-076379cfddc8
98b59815-8c33-41fe-a03f-225f075a6c55
ef0bdc7f-7186-448f-bcf8-f181faa83ffb
9e7a8b63-f6ce-4d86-8e09-36c27dbee327
a4400509-db38-442e-a0ff-87e0078571f0
33251053-a5f0-4e57-9a4e-9a3fd8ae57e9
5fad65a3-1506-48d1-bc82-818766de9d3d
17d2301a-3d74-4bf8-ad10-dfc1afe24e13
bb993828-5f84-4607-b7f9-c41938db9d50
e7b4ddae-3f9a-4120-aff0-322ea223c05c
44c055ac-5674-446f-82ec-1953ed313e0c
46c036ee-4844-4837-bb70-f301029306c0
562f55b2-5a25-476b-a23d-7c7e6eaa618a
3a619364-6425-478c-be03-f1e3bd1eb924
260d4488-8917-45e5-a281-5b2e593163f0
d0de3627-1481-4d7f-8eb0-34acd8dd3332
b465a00c-e6ca-4a72-9d77-e65b1d2a91aa
36bbe374-fc17-46aa-a7b2-4bb24f948bbe
24ef6621-7e67-4e23-b0be-6e74ffe04a9c
bb4743b7-9729-4e3e-a647-51bfdb77656e
37cebc40-3e32-4c93-8684-37960e9d9bb4
a7c77d36-b674-4123-bb31-9fa19b3689f2
5aca602a-a959-4220-84a9-9bf0b19f3fe5
fdad4107-4a67-46d1-bbd7-79b1e8d0efcf
658aa02f-82ee-4620-b10a-bbe06b399517
a5c7241d-4c26-416c-a2a0-cea522a38dc5
244d6111-b80b-4902-818a-735d3caf096d
b66611e4-9cbc-431a-b989-c74ef811f1e5
d7b79087-f01b-4af0-8d33-d206695330d5
169f9ca2-a8a2-43f0-adea-65f607049ef9
7a715672-4539-4e09-98d2-f932ca006b62
69574fe6-d389-4dcd-965d-67871df09b7e
01c78a0d-d781-4fcc-9d66-a6145e76ef0f
064e96c9-0165-4203-af75-470267fdebc7
21063b4f-8a45-47e9-a40b-706b30a5da04
f9e14737-06a1-4c8c-8140-368cb149e4ff
0b4ece5b-6ee4-44bb-a620-6050c0374a04
5c233ac8-5605-47d5-a267-65ab283099b3
fd96435d-1e51-4aa7-b23c-e21798cd575e
01c5c09e-4460-4cbc-81ac-70c2b83c5b74
0c99fe5f-c626-49e6-a744-7ac43fc369da
c77921a2-bfce-4d78-b364-6925476d5e45
7f9c14aa-410d-4c6b-8c01-c38ec5d0f17e
e3b1386f-6c4c-4486-abc4-2d2ed62f05d0
ada1e039-1f60-4fff-877f-acd2f518cf81
53e2b568-0601-46a9-a205-8fa302fa0c42
c909216a-b000-4cbf-ad34-dbfdf3aa4679

**Comment by anshulkumar-usds** [comment]
@jorg3lopez please deliver sample data to AZ's test directory and request validation. I cc'ed you on the last reply to AZ.

**Comment by Adrian-Brewster** [comment]
@jorg3lopez Will work on this this week.

**Comment by jorg3lopez** [comment]
@anshulkumar-usds @MauriceReeves-usds @Adrian-Brewster Below are the speciment ids, I will start working on pulling the files they came in.

**specimen ids:

b1a9b8b8-c7aa-424e-8d4f-07c61cc197b7
775ff74a-4686-44eb-bb80-2f16e54d8d85
27090eae-b870-4139-a214-f0117ad70777
3cd06ae0-4c30-4837-b6d4-e5981b951fb4
c03dcfea-83d9-4005-9793-2131f6c7fd29
93bb74d0-f360-4e04-8e46-21786adb3f37
d5b66b23-d7d1-4dc7-9bfb-39bb836658c8
859938b2-1151-433b-9d9f-4e4ef589e0bf
1005ebea-eb9e-4740-8a4d-018c5ee3cbb8
b4b0fd77-ddad-45c3-a317-2bb927b0aa76
f4f89724-42d4-4a0f-82a4-03fad343c3b5
6b0b0346-3db4-4563-9053-253eb2da499e
1c065b10-31c6-4509-bc37-dba915b3c58d
057abc03-5d2e-4ccc-af64-fa102343d64d
63adbae3-d636-4596-80a3-bed2f624c95e
36e6773c-edce-4f78-8969-8df533e74cf5
ade10e66-4b85-40d4-988f-0c1846bc55e1
7730fcee-e810-469f-928e-65e135b9fd18
bf89f825-9ee0-42ba-8c99-5b91eeb84817
fcc16324-ca01-4824-b108-84b56f023b6b
8263709b-31ff-42be-b2b1-2aee9c731101
caba9405-3e15-4a0d-8db6-478eb44318c7
6f2126a8-a43a-44d2-9be3-9fd3aef465d3
15b7c9c3-1402-45f1-8098-04891d2330c0
96e57334-8130-46ec-a002-bc419105b686
1814343a-9ba0-46cd-a5c7-63586454a11e
5ec1551e-ff15-4c1a-8eb2-79d32c131167
435ad28d-2b58-4934-98ed-50c63fba254d
1f90101d-9b25-48cc-b324-5f50c8a5371d
01a97eef-6155-49ab-84f5-8883b089acb6
c1e7185a-5e0d-4891-bafb-a874f616684c
985daf24-99c9-4d40-9402-91585d4e0468
7dba5b3d-34ed-47a9-99b1-c7c0355102cb
4e7a3bae-a05b-4a55-97eb-a8752e240900
fd58f5c-9521-4399-b26c-b34adc8db57c
e2e066fd-8d40-4074-902a-5f575b7586ed
dd9521b3-f68b-405e-8227-2076347c98d8
627fafee-89b9-4f31-890b-1aae39267b5d
e7d78e1f-6a47-474e-9fed-5ad1aef9df4c
660cd44b-fd2b-41bf-9266-ee35f334d5ed
3f7fce9b-a325-48da-921d-a62927072011
33959303-1b5a-4bce-adba-9f26dda9198e
74a87db9-b4ba-4a21-952c-159e6d4b1932
d740530c-6257-49b4-83ce-8b165d695e09
6f7d89e3-6689-4e29-93ba-fd823ee5777f
a8312745-c70b-4415-a4f8-25de28c50101
46c80f14-6dd2-43c9-b207-1c595098a44e
0394b943-da62-4a0f-86a5-0752cd679853
ff3defd1-f054-4463-af7a-57e7e9b305ed
8b9733ec-443b-445e-9fd2-3f277965da4c
17298954-36e9-43f1-b478-7d042f65f363
1ba621b2-70ce-4449-ad3c-43d2dee9c1c3
07865a85-b16d-4228-8d36-0e3d64840de7
e272d8be-fe93-4b96-ad66-4d41bed1bf87
460ac107-4983-4889-b3a6-f6502fc8ff33
3cfe681f-2cb4-4214-916b-8c94f9acc91c
eb92e5c3-ef9d-4ad1-932f-fa47163b871c
cf147283-14fc-4720-b1fb-ed0a6af196d0
8a8a793c-8db5-4f98-9757-feb41116c75b
3bd22c50-f340-49a9-951b-ace16df1457d
a4d6fcc9-6e1a-48a6-8934-00c5cc2e7eec
fd28944d-b252-406c-8b62-c703e5a6668b
b3f1ee16-37f8-4635-8a8c-c58cf803af73
a9e51968-18a7-4187-80ee-168266ce29a7
ce455f84-1f18-4159-8b94-2eb367776d44
d7111e01-7fde-4f53-9286-a04aaec2e68e
cbb70621-e470-43c4-8a8a-f3ee3be366f9
a1cefc1b-b094-4a47-afcc-061f3687b98b
0617e3f8-ae62-4f90-9d9b-3f8af8a8a89a
5b5e80c4-e042-4651-b87c-34036e0614cf
50a70f71-4acd-4189-a198-f8165020fba5
423d5c41-72f7-4f1d-b572-c7b48dc3fb86
cd2936d0-7465-4a42-a534-8f72bd8a48c8
1760b5c6-eb6f-40b5-834d-643b598dd03d
12e0aa10-ccc7-4fd3-a32b-c9735c127c75
fc7e412b-0a7a-4147-aa4a-ce3baabfc27a
2bdc2135-14c0-4fc9-8a59-af237e539ee3
9b64e328-456c-43e2-afb3-6cf9de3fbb95
86ccde0c-b977-43f7-a297-dc79824f37cb
b6403c25-6310-44d9-b1b2-6ca48ec27968
0806bd60-c966-4e19-b5bc-36ae1dee189c
35ff3fab-6cab-42ed-81e4-826ecc75e06e
a57d8296-fe02-4723-880e-4583340c8304
42df58cb-c6c3-4220-badc-caa8d570c3a8
981daaa2-2cfd-46b4-ac3c-2ba1adf15b9e
f0dd43a7-af14-4456-968e-97a069afd804**

**Comment by jorg3lopez** [comment]
@anshulkumar-usds @Adrian-Brewster I have resent all the test results to AZ that failed due to missing specimen id. (date: 01/21/2022)
File name:
**az-covid-19-93b52535-a7f3-4b94-b6c8-db8dea7c7bbb-20220121215101
az-covid-19-4a9032af-cf25-4768-9526-10b3b1b91de1-20220121215201**

There were three speciment ids that went to CA as this was the ordering facility and the patient state was AZ. Below are the specimen ids.
specemen id:
**6b26c950-9a43-4829-ab71-68bc2aceb4dd
3ea3cd64-44f9-47c0-bbfb-6db7da8d19c1
6e197891-7652-43c4-aae7-c087b840ab00**

**Comment by anshulkumar-usds** [comment]
1/23: Checking with AZ on file delivery and validation

**Comment by anshulkumar-usds** [comment]
1/31: Checked with AZ again

**Comment by anshulkumar-usds** [comment]
AZ confirmed delivery.
