### ISSUE TITLE
IL - Missing LOINC in OBX-3.1

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3052]
First reported on 10/12, IL reports that some messages were sent with missing LOINC codes in OBX-3.1

Message control IDs and HL7 snippet showing missing LOINCs are attached.

To do:
1. Repopulate LOINCs in the missing messages and resubmit to IL
2. Understand root cause as to why this is happening and what RS can do to prevent from happening again?
2.1 Is it a sender issues? If so, please share more details.

Note: before reaching out to IL, please check with @anshulkumar-usds since we have other open items for IL as well. ![IL LOINC1.png](https://images.zenhubusercontent.com/607d9d4a591b7cc0bb55c82e/b9022209-5593-4933-b6c7-9aee57966fc3)

**Comment by MikeC-A6** [comment]
@anshulkumar-usds - In the original email, IL said "We had some messages come over that did not have a LOINC code in OBX 3.1. Could you please make sure that all tests have the proper LOINC attached to them? **You do not need to worry about resending these specific messages.**   #1 in the to-do list says "Repopulate LOINCs in the missing messages and resubmit to IL"  Should we still be resubmitting?

**Comment by anshulkumar-usds** [comment]
@MikeC-A6 We should still resubmit to ensure we get confirmation from the state on our fix.

**Comment by anshulkumar-usds** [comment]
Hey @MikeC-A6 IL is looking for an update. In the short term, can we have the sender address any data on their side?

**Comment by MikeC-A6** [comment]
@anshulkumar-usds 5 out out of the 6 are "CStartAntigenSARSCOV" from ImageMover - I believe you already reached out to them right?  The 6th one is from SimpleReport - Sienna-Clarity COVID-19 Antigen Rapid Test Cassette*.  This test appears to be in the RS LIVD table  not sure why the LOINC wouldn't have populated.  Needs more investigation.

As far as an update to IL - perhaps for now:  We have contacted the sender to make a fix on their end so the LOINC code will be populated moving forward.  We have also implemented an improvement on our end where you should start to see far fewer results come in without LOINC codes.  There  is some more work to do to address all scenarios, but we are actively working on it.  Can you keep us updated with any new results with missing LOINC codes that you continue to see?

**Comment by hermanAlexCordero** [comment]
Reviewed some of the failures.  Equipment model does not exist in the latest livd table.  

3cd6961b-dda3-4b5e-a293-9c5317e4cfad - CStartAntigenSARSCOV
7f0b026d-9480-41f0-8361-edb654611bf5 - CStartAntigenSARSCOV
1f8c66e2-5f99-4ad6-8da3-f33ddf3cc0e1 - CStartAntigenSARSCOV
054a9887-8477-4731-97b6-b278a3dcac54 - CStartAntigenSARSCOV

**Comment by anshulkumar-usds** [comment]
Let IL know the issue is resolved from sender. Awaiting confirmation from IL if records need to be resent.

**Comment by anshulkumar-usds** [comment]
Issue resolved by ImageMover. IL indicated no resubmissions are needed.
