### ISSUE TITLE
NJ - OBX-23.1 Truncate Organization Name to 50 chars

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3054]
In recent days, both IL and NJ have reported that Organization Name in OBX-23.1 should be truncated to 50 characters.

This ticket is to make the change to our universal schema so that ALL receivers begin to receive less than or equal to 50 characters in OBX-23.1

For reference, tickets from NJ  and IL are below:

https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3015

https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/2702

**Comment by jorg3lopez** [comment]
PR waiting for review and approval.

**Comment by anshulkumar-usds** [comment]
Awaiting deployment for updates from Rick's PR: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3205

**Comment by Adrian-Brewster** [comment]
@jorg3lopez Will send test files and get approval

**Comment by anshulkumar-usds** [comment]
Updated ticket name to NJ since we're tracking IL specific work and statewide enhancements separately

**Comment by anshulkumar-usds** [comment]
@jorg3lopez can you please provide an update on this? Thanks.

**Comment by anshulkumar-usds** [comment]
Test file was shared with NJ on 11/24: test-covid-19-e09a2ed3-9c1e-46da-9458-891e9eae8ca5-20211124191607

NJ was notified of this on 12/22, and we are awaiting their UAT.

**Comment by anshulkumar-usds** [comment]
NJ validated the test file.

**Comment by Adrian-Brewster** [comment]
files validated and in prod. closing ticket
