### ISSUE TITLE
Update Fake Data Generator to Allow Injection of Desired Values for a Column

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#306]
For some clients of fake data, we want to be able to pass in lists of acceptable values for a field, and we need to inject them into the fake data generator.

**Comment by brandonnava** [comment]
@GilmoreA6 @lizzieamanning Is this similar to what we discovered in sender interviews where they were saying onboarding would be easier if the sample file showed examples of acceptable values in the required fields?

**Comment by LaFreda1** [comment]
Closing due to low priority and time frame.
