### ISSUE TITLE
SPIKE -- Research a better design for user permissioning

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#3078]
## Problem
Right now user permissioning is based just on Okta group. The frontend code makes assumptions on Okta group naming conventions and isn't designed for complex permissions. This has caused bugs for admins who are are a part of many groups and have sending and receiving permissions.

## Acceptance Criteria
- Recommendation for a more reliable and scalable permissions pattern that follow best practices
- Document recommendations
- Present to the team
- Tickets will be created later after team discusses

## Notes
- Might make sense to talk to Okta reps and/or read through their docs to learn best practices

**Comment by kevinhaube** [comment]
I'm going to get a head start on this, but I'd love to bring it into our next Sprint @loripusey
