### ISSUE TITLE
[Design] After failed ReactUI upload, Continue action is hard to find

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#3079]
**Describe the bug**
Design bug: errors and warnings are unbounded length (e.g. there could be thousands of them?) The retry is so far down the page as it gets lost and re-clicking the Upload tab doesn't clear the results.

**Impact**
Could be frustrating/confusing.

**To Reproduce**
1. Go to Upload page from the topnav
2. Click on Upload file
3. Select an large invalid file like `/prime-reportstream/prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-batch-pdi-20210608-0001.csv`
4. Click Upload.
**Result**: Really long results pushes the next action several scrolls down.
**Note**: Clicking the Update tab from the topnav doesn't clear the results.

**Expected behavior**
No clear "expected" behavior some ideas:
Maybe keep the try again results at the top of the page and the results under it?
Or, just keep the result toast at the top and #ref link to a longer list below?
Or, put the results in an expandable section that's initially closed?

**Screenshots**
![image](https://user-images.githubusercontent.com/74203452/142054874-6baab836-600a-41bc-be1c-1c413649e453.png)

**Comment by loripusey** [comment]
@inkandsound @drew-usds Can you take a look at this and make some recommendations? Thanks!

**Comment by bgantick** [comment]
Closing: feature moving to SimpleReport
