### ISSUE TITLE
Provider ID Data Quality Issue

### ISSUE THREAD

**Issue by MikeC-A6** [CDCgov/prime-reportstream#3093]
This ticket outlines a Reportstream and SimpleReport data quality issue related to the Provider ID field that is impacting multiple STLTs, originally surfaced by Illinois.

Illinois indicated that they are having "quite a few messages fail" due to values being sent in the (OrderingProvider->ID) that are greater than 15 characters, which is the character length limit in their integration engine for that field.  Link to the original ticket: [https://app.zenhub.com/workspaces/prime-reportstream-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/2833](url)

Multiple STLTs are affected by this in addition to IL, and the problem goes beyond the Provider ID exceeding the maximum character limit of 15.

*Analysis*
The reason for this character length limit is that the HL7 2.5.1 specification sets a maximum of 15 characters for segment ORC.12.1 (Ordering Provider ID Number), although this value is considered optional in the HL7 Specification.  Integration engines like Rhapsody enforce adherence to the HL7 specifications, and therefore if a value is sent in ORC.12.1 that exceeds a character length of 15, a HL7 message will "error out" resulting in that message dropping into an error queue for manual handling.  An ELR analyst at a PHD may just delete the erroneous Provider ID value manually so that the message can process in the system.

The constrained HL7 specification for Electronic Laboratory Reporting (HL7 Version 2.5.1 Implementation Guide: Electronic
Laboratory Reporting to Public Health, Release 2 (US Realm) ) indicates that for the provider ID field "If available, a NPI should be used as the identifier."  NPIs are solely issued by the HHS-CMS, and follow a strict format of 10 numeric digits.    Anything that does not have 10 numeric digits is not a valid NPI

Currently, Reportstream is sending whatever value the sender provides in the Provider ID field.  In the last 30 days, there were 108,819 messages from 174 unique ordering Provider IDs received into Reportstream for SimpleReport users where the Provider ID field was not a properly formatted provider NPI.  In the provider ID field, one sender input "Grama's Home".  In that particular example, because that value is only 12 characters, it may not fail in a STLTs integration engine.  A total of 1,766 messages had Provider ID fields where the character length exceeds 15, which would result in message failure at many PHDs.

Values that Reportstream is sending to STLTs in the provider ID field (from SimpleReport users) include:
- masks
- Grama's Home
- Egyptian Health Department
- Binax Now
- ???
- SCHOOLS
- unknown
- RN
- None
- Not Available
- NA
- DOH
- CDPHE
- AMHS

*Solution Recommendation*:  At a minimum, Reportstream should provide validation on the Provider_ID field to ensure that it does not exceed the 15 character length.  This will prevent messages from erroring in STLT integration engines.  Additionally, we may want to do further validation to enforce a 10 digit numeric value for the provider ID field, as that is the only valid format for a NPI.  We should not be sending values like "Grama's Home" in the provider ID field to STLTs.

**Comment by rhood23699** [comment]
Note, most states will accept the data shown below in the ORC.12.1; ORC.12.9; ORC.12.13 and the OBR.16.1; OBR.16.9; OBR.16.13, but they would prefer to have the ORC.12.9; ORC.12.13; OBR.16.9 and OBR.16.13 indicate local coding instead of NPI.

![image.png](https://images.zenhubusercontent.com/60d60ccc22b13400ec870367/d7a49c05-a1c5-43fd-a2a7-4a005d5cf8a1)
![image.png](https://images.zenhubusercontent.com/60d60ccc22b13400ec870367/f043a904-ae64-41d9-9b21-edcc672565ce)

**Comment by MikeC-A6** [comment]
@rhood23699 - I'm just making sure I'm interpreting your comment correctly.  So in ORC-12.1, you used "LocalCodeForProviderID," and Reportstream still populated ORC-12.13 (Identifier Type Code) as NPI?  Is Reportstream populating ORC-12.13 if a value is supplied in the provider ID field, whether the value is an NPI or not?  The implication of that would be that we may be often supplying STLTs with a ID type of NPI in ORC-12.13 when what the sender provided was not a NPI.  Can you confirm?  If this is true, I think it needs to be a separate bug ticket.

**Comment by rhood23699** [comment]
If you pass in an Ordering Provider ID alone, RS defaults the ORC.12.13 to NPI.  I believe this can be overridden by passing in a value to Ordering Provider ID Authority Type.

**Comment by rhood23699** [comment]
Correction.  RS put "NPI" in ORC.12.13 even if you try to override it by putting another value into Ordering Provider ID Authority Type.

**Comment by anshulkumar-usds** [comment]
SimpleReport fix for NPI: https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/3005

**Comment by MikeC-A6** [comment]
![image](https://user-images.githubusercontent.com/77452595/143029291-d34fc62c-69c5-41ee-9bd0-c9222d8f2b07.png)

Brainstorming meeting notes 11/22

**Comment by MikeC-A6** [comment]
NPI requirements: https://www.cms.gov/Regulations-and-Guidance/Administrative-Simplification/NationalProvIdentStand/Downloads/NPIcheckdigit.pdf
