### ISSUE TITLE
Compass Urgent Care (CUC) - Add New COVID Test

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#3094]
## Problem statement
Compass Urgent Care is adding a new COVID test.  It is the "BD Veritor Rapid SARS-Cov-2, Flu A & B".  The test must be added to the CUC Schema and the VBScript with the additional logic only send the COVID results (ie. exclude the Flu A & Flu B results).

## Acceptance criteria
- [x] OBX.3.1 - SARS Antigen must be LOINC Code:  97097-0
- [x] OBX.17.1 must be "BD Veritor System for Rapid Detection of SARS-CoV-2 & Flu A+B_Becton, Dickinson and Company (BD)_EUA"

## To do
- [x] Add the test to the the CUC Schema
- [x] Add the code to filter out Flu A & Flu B.

**Comment by Adrian-Brewster** [comment]
Got access to their system yesterday. Will start looking at files today.

**Comment by rhood23699** [comment]
Schema and VBScript changes are complete, but I'm having issues with the qualityFilter.  I've posted in Engineering channel of Slack for assistance in resolving the problem.

**Comment by rhood23699** [comment]
Deployed on 12/8/21.
