### ISSUE TITLE
Install Azure App Insights for the Web Application

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3095]
## Problem Statement
As the Experience Team, we would like to capture analytics to measure the success and usage of the product over time so that we can know that we are heading in the right direction.  

## Notes
Refer to the analytics as outlined in the Product Brief [https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Artifacts/ReportStream%20Experience%20Team_Product%20Brief_draft%20v3%202021.10.21.pptx?d=w951bdeb553ad410b8149e95f463f3a59&csf=1&web=1&e=eaB5nI](url).

Refer to shared scratchpad "notes on tools to consider for gathering metrics" [https://cdc.sharepoint.com/teams/USDSatCDC/_layouts/15/doc.aspx?sourcedoc={da429e45-5f42-4399-a2b1-70ccc066a718}&action=edit](url)

Related to [https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/2834](url)

Update: This appears to be the correct link for "Notes on Tools": https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BDA429E45-5F42-4399-A2B1-70CCC066A718%7D&file=Notes%20on%20tools%20for%20gathering%20product%20metrics.docx&action=default&mobileredirect=true

**Comment by kevinhaube** [comment]
#3099 May be more iterative rather than a one-time creation of all dashboard items; doing it per-insight seems to make sense from what I'm learning while implementing the prototype.
