### ISSUE TITLE
Configure Azure Application Insights

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3096]
## Problem Statement
As ReportStream, we would like to capture analytics to measure the success and usage of the product over time so that we can know that we are heading in the right direction.  

## Acceptance Criteria 
- Configure an Azure Application Insights resource in our Azure production environment​ to enable the capturing of usage analytics
- Question: how does our content security need to be configured to handle the AAI scripts

## Notes
Refer to the analytics as outlined in the Product Brief [https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Artifacts/ReportStream%20Experience%20Team_Product%20Brief_draft%20v3%202021.10.21.pptx?d=w951bdeb553ad410b8149e95f463f3a59&csf=1&web=1&e=eaB5nI](url).

Refer to shared scratchpad "notes on tools to consider for gathering metrics" [https://cdc.sharepoint.com/teams/USDSatCDC/_layouts/15/doc.aspx?sourcedoc={da429e45-5f42-4399-a2b1-70ccc066a718}&action=edit](url)

Related to https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/2834

**Comment by loripusey** [comment]
@cwinters-usds I added this ticket for DevOps to pull in for the next sprint to get our AAI resource configured, thanks!

cc: @rachelhanster @drew-usds

**Comment by JosiahSiegel** [comment]
I will prefer the Terraform refactor is completed before adding logs, analytics, and shared dashboards to production, but of course we can do that manually if Terraform is not ready in time.

Another blocker is that I do not yet have Azure access, but if necessary, I can walk someone through setting up everything.

**Comment by cwinters-usds** [comment]
@JosiahSiegel Proposal: I'm ok with unblocking the FE folks by setting the instrumentation keys as Github secrets. Then once Terraform is in a good place we can put the into KeyVault and make some (I think) minor changes to the GitHub Action to source the keys from there. And since https://github.com/CDCgov/prime-reportstream/pull/3392 is now merged in we'll only have one place to do that.

Does that sound like it'll work?

**Comment by JosiahSiegel** [comment]
@cwinters-usds I was more referring to adding the log setup and insights to terraform. IMO this ticker is not blocked at all, it just depends if you want to record changes in Terraform now or later.

**Comment by cwinters-usds** [comment]
@JosiahSiegel Gotcha. I was assuming we'd use the existing per-resource-group App Insights instances (e.g., pdhstaging-appinsights, pdhprod-appinsights) to receive the data. Is there a reason to create a separate one?

**Comment by JosiahSiegel** [comment]
logs still need to be configured to export to a log analytics workspace from each item that supports it, and the insights need to be adjusted to report from the workspace. For example, this may show up as a "diagnostic settings" change for the database in terraform

**Comment by cwinters-usds** [comment]
This is currently deployed to staging -- the environment variable `REACT_APP_APPINSIGHTS_KEY` contains the value to use with `instrumentationKey` [per these docs](https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript-react-plugin). It's also setup to provide that value in the production environment.
