### ISSUE TITLE
[Insights] Configure Azure Application Insights React Integration

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3097]
## Problem Statement

As ReportStream, we would like to capture analytics to measure the success and usage of the product over time so that we can know that we are heading in the right direction. We've chosen to use **Azure Application Insights** to capture our telemetry. There's a [convenient npm package](https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript-react-plugin) that integrates the Azure Application Insights javascript configuration into the React application build process.

## Notes

- May need a separate key for prod & staging
- Please see Chris Winters for keys; he has configured an Azure App Insights resource

## Acceptance Criteria 

- [ ] Configuration for Azure app insights transmits data to the correct Application Insights instance (i.e. the connection string is correct per-environment)
- [ ] One application insight action is transmitting from ReportStream to Azure App Insights (simple home page hit metric?)

## To Do

- [x] Get Application Insights instance made for web client in Test
- [x] Prototype the React application integration with Microsoft's provided App Insights React package
- [x] Get prototype running and smoke test in Test environment
- [x] Troubleshoot & Revise (god only knows how many times we may want to do this step)
- [ ] Replicate successful prototype for staging and production releases
- [ ] Put that PR up and stand tall with pride for a job well done

**Comment by cwinters-usds** [comment]
There's now a file in keybase under the `prime_dev_ops` at `environment_info/app-insights.txt` with the instrumentation key needed for each environment. I think the key is all that's needed to configure the front-end client to communicate with the service.

**Comment by TomNUSDS** [comment]
Chris also found this react component that might work for us (depending on which version of React Router we're using): [React plugin for Application Insights JavaScript SDK ](https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript-react-plugin)

**Comment by HeatherRienks** [comment]
Update from @doug-s-nava - He  is working with @jeremy-page on getting access for the team.

**Comment by kevinhaube** [comment]
Now that we're on Router v6 that link @TomNUSDS shared is clutch! Should make app insights integration fairly easy (_knocks on wood_)

**Comment by HeatherRienks** [comment]
@kevinhaube - great news! Let's discuss what the next steps are!

**Comment by kevinhaube** [comment]
After some investigation this morning, here's what this work might look like:

- [ ] Get Application Insights instance made for web client in Test
- [ ] Prototype the React application integration with Microsoft's provided App Insights React package
- [ ] Get prototype running and smoke test in Test environment
- [ ] Troubleshoot & Revise (god only knows how many times we may want to do this step)
- [ ] Replicate successful prototype for staging and production releases
- [ ] Put that PR up and stand tall with pride for a job well done

**Comment by kevinhaube** [comment]
Set to deploy to prod November 22!
