### ISSUE TITLE
[Insights] Create basic insights dashboard with from-the-box data

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3099]
## Problem Statement

As ReportStream, we would like to see basic metrics in a dashboard, created from the available App Insights data out of the box (no custom insights).

## Notes

Refer to the analytics as outlined in the Product Brief [https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Artifacts/ReportStream%20Experience%20Team_Product%20Brief_draft%20v3%202021.10.21.pptx?d=w951bdeb553ad410b8149e95f463f3a59&csf=1&web=1&e=eaB5nI](url).

Refer to shared scratchpad "notes on tools to consider for gathering metrics" [https://cdc.sharepoint.com/teams/USDSatCDC/_layouts/15/doc.aspx?sourcedoc={da429e45-5f42-4399-a2b1-70ccc066a718}&action=edit](url)

Related to [https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/2834](url)

## Acceptance Criteria 

- [ ] Assume we are just setting up out-of-the-box metrics
- [ ] Create an Azure Application Insights dashboard to show the following metrics

**Comment by HeatherRienks** [comment]
Per @kevinhaube - an Engineer does NOT need to pick this ticket up :)

**Comment by kevinhaube** [comment]
Determined 11/28 with Jewel and Jeremy that the "otb" data is not quite enough to form anything actionable. Site reliability is already handled by the current dashboard. Case closed!
