### ISSUE TITLE
Execute CSV Uploader Pilot Plan for Cohort 1 and Synthesize Results

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3106]
## Problem statement
As the ReportStream teams, we would like to pilot our CSV Uploader feature for our Cohort 1 group so that we can gather feedback and metrics for ReportStream. 

## What you need to know
- Lots to look into as we have thus far not tested any of the uploader with users.
- We should gather feedback and metrics from not only the Sender's interaction with the CSV Uploader but also the onboarding process and the delivery of results to PHDs 

## Ideas to start with: 
- Are users able to upload a csv?
- Do error messages make sense?
- What is working well about the csv upload? 
- What could be improved about the csv upload process?

## Acceptance criteria
- [x] Execute plan with Cohort 1 pilot participants
- [ ] Synthesize results
- [ ] Write up short message for sharing with team in Slack
- [ ] Create icebox issues for any updates

**Comment by victorialb-usds** [comment]
Here is synthesis for the A1H call: [https://app.zenhub.com/files/304423150/6cf455c4-8200-4f61-a387-22cefde99059/download](https://app.zenhub.com/files/304423150/6cf455c4-8200-4f61-a387-22cefde99059/download)

**Comment by inkandsound** [comment]
Notes from our user testing session with A1H based around clickable prototypes for sender submission history and file upload/validation: https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BB5D4CD06-7B93-4BFD-91FE-F69D84AF6D72%7D&file=A1H%20-%20Sender%20Experience%20Prototypes.docx&action=default&mobileredirect=true&cid=f6290ce4-84df-4d7c-8aae-6a9de08f916e

**Comment by victorialb-usds** [comment]
as of 1/3 Rick Hood still working with A1H and CAPHD to make sure data is being received.
