### ISSUE TITLE
Research Tools to Help Senders Self-Onboard

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3107]
## Problem Statement
As the Experience team, we need to understand what tools may be helpful to help Senders  onboard so that we can decide what we can automate.

## Acceptance Criteria
- Look at and document our current onboarding processes, including steps performed by the O&O team
  -  Look into time it takes to complete each step (may be all over the place, but if we knew generally per sender that'd be a start)
- Determine what steps could potentially be automated
- Make recommendations

## Notes
Maybe look at:
- CSV users
- API users
- Device manufacturers

**Comment by chris-kuryak** [comment]
- Brandon Canniff has already [created a user funnel](https://app.mural.co/invitation/mural/nava4113/1670871165114?sender=u788ba8e0ebf56a2ad7d18905&key=2c7759fb-a9e4-4b50-860e-8d43e0bfe685) with general onboarding steps and average time it takes to accomplish.

- O+O Team is maintaining [this mural](https://app.mural.co/invitation/mural/primedatainput6410/1660314801327?sender=u788ba8e0ebf56a2ad7d18905&key=e2e4eab1-2bf1-43be-9769-a2806a9385ad) that prioritizes items for Experience team to build to help onboard users more efficiently.

Closing.
