### ISSUE TITLE
Research Tools to Help Receivers Self-Onboard

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3108]
## Problem Statement
As the Experience team, we need to understand what tools may be helpful to help Receivers onboard so that we can decide what we can automate.

## Acceptance Criteria
- Look at and document/map our current onboarding processes, including steps performed by the O&O team
  - Look into time it takes to complete each step (may be all over the place, but if we knew generally per receiver that'd be a start)
- Determine what steps could potentially be automated
- Make recommendations

## Notes
Potentially use LA County, as they might be doing this soon

**Comment by chris-kuryak** [comment]
- Design team has research underway (tracked elsewhere) to determine the best place to start for self-onboarding.

- Brandon Canniff has already created a user funnel with general onboarding steps and average time it takes to accomplish.

- O+O Team is maintaining this mural that prioritizes items for Experience team to build to help onboard users more efficiently.
