### ISSUE TITLE
WA - Missing Specimen Collection Date

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#3112]
WA submit an issue today (11/17/21) regarding missing specimen collection dates.

Here are some message IDs to start the investigation of the issue. I have a spreadsheet of these IDs and they will need to be resend once we have resolution. When this ticket gets assigned, please let me know and I will send the spreadsheet.
![image.png](https://images.zenhubusercontent.com/5eaf8fc6e9ce8c652d0f1cb4/e894a18d-35de-4de4-9f36-f3ce44198615)

9381c282-f680-42e3-88bb-528227025192
2426fe47-11b9-406e-90c6-079f8f0715cb
1071b551-5be6-42a5-b9c5-48934ceb48a2
b14d350b-d6cf-4578-b885-a7c2c5a45cad
9c8b7b12-b4dd-4fe5-a500-d5df492d489b
3f89ebfe-040d-49ad-afe0-c9f0f1a2e17b

**Comment by mlighdc** [comment]
WA emailed today (11/18/21) with an updated file with more examples of the issue.

**Comment by anshulkumar-usds** [comment]
[https://app.zenhub.com/files/304423150/393893bc-a6bd-43f2-89fc-23d38289fee7/download](https://app.zenhub.com/files/304423150/393893bc-a6bd-43f2-89fc-23d38289fee7/download)

this file contains all the message IDs as of 11/16 where the report issue was found. We need to resubmit these once the issues is resolved, and check again with WA to see if any new submissions since 11/16 also need to be resubmitted.

**Comment by anshulkumar-usds** [comment]
Mo identified the root cause. Plan to deploy fix this week. Will need to follow up with WA on consolidate list of messages that need to be resent. WA was notified of this on 11/23.

**Comment by anshulkumar-usds** [comment]
@MauriceReeves-usds WA is reporting that SPM-17 and OBR-22 are also effected by the changes to the time-stamp format. Details are in the email from WA on 11/23 at 1:50 PM ET.

**Comment by anshulkumar-usds** [comment]
Reopening since we need to resubmit the messages effected by this bug.

**Comment by anshulkumar-usds** [comment]
Two sets of resubmission are needed:

1. Prior to 11/10 - some messages were effected. Message IDs are attached from WA
[https://app.zenhub.com/files/304423150/c20acb5d-1e0d-4973-ab42-f9a4aff39e90/download](https://app.zenhub.com/files/304423150/c20acb5d-1e0d-4973-ab42-f9a4aff39e90/download)

2. ALL results submitted to WA after 11/10 need to be resubmitted to WA

**Comment by Adrian-Brewster** [comment]
Mo will meet with Rick to see how to do resends to WA

**Comment by anshulkumar-usds** [comment]
Anshul notified WA that due to AS2 connectivity, we'll need additional time for resubmissions. New timeline is by 12/10.

**Comment by anshulkumar-usds** [comment]
@RickHawesUSDS - @MauriceReeves-usds mentioned he needs to work with you to figure out the custom AS2 setup for WA for resubmission. Just putting this on your radar for awareness.

The last ETA we shared with WA was 12/10. If we need more time please let me know.

**Comment by Adrian-Brewster** [comment]
Mo will resend affected files.

**Comment by Adrian-Brewster** [comment]
@MauriceReeves-usds WA has followed up on this.

**Comment by Adrian-Brewster** [comment]
Since we are past 30 days, WA may need to reupload the messages themselves and manually fix the errors.

**Comment by anshulkumar-usds** [comment]
Checked with WA during the weekly call on 1/3, and they do not find it feasible to correct all the records by hand. 
@MauriceReeves-usds  they are looking to us to complete the resubmissions.

**Comment by anshulkumar-usds** [comment]
Test files were submitted to UAT; awaiting WA to confirm the files.

Followed by RS to resubmit prod data to WA

**Comment by anshulkumar-usds** [comment]
Anshul to follow up on email thread

**Comment by anshulkumar-usds** [comment]
2/9: WA informed RS that their HIE informed the following:
"When we looked into this issue we could only find a couple of instances where we noticed this error message was sent. Has the USDS team looked at restricting the size of the batch files sent that contain the negative results to see if this resolves the issue? We have had other customers in the past batch more frequently to resolve this issue."

**Comment by Adrian-Brewster** [comment]
Needs to be emailed because they are over 90 days.

**Comment by Adrian-Brewster** [comment]
comprehensive list of required resends in ticket 3677

**Comment by oslynn** [comment]
pecimen_collection_date_time is not missing, according to Mo.  It just has -0000 at the end of date_time.  yyyymmddhhmmss-0000 (UTC).
