### ISSUE TITLE
Test Performed LOINC code gets overwritten if the Model ID / TestKitNameID is invalid

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#3121]
Test Performed LOINC code gets removed if the Model ID / TestKitNameID is invalid.  This has been observed in output reports (reports sent to receivers).  Some sample report IDs with this issue (note these reports may be purged at some point):
This list was made 11/17/2021
```
4a89300e-e979-4874-91d6-95d17533bd83
e892cf7e-6b16-4f07-906d-ddc901a7fc2f
48a7e06f-bbe4-4365-8e73-9c06e6b1d481
4efea813-d66f-4aae-90db-8faa6f59a006
3bd3a8f2-f90c-49d1-9032-3081fc8e9aa3
2dcdf353-e2c6-4458-96b6-89df232ba279
```

Related to issue #2635

Design considerations:
The code is supposed to not replace a provided value even when a mapper is present.  A quick test shows that the LOINC is not being removed.  Could this problem lie with a specific issue in a schema?

Acceptance criteria:
1. Reproduce the problem of the LOINC code being removed and identify the problem.
2. Fix the issue or propose a fix if the solution is complicated.
3. Inform @anshulkumar-usds and update ticket #2635 with findings/solution.

Status:
1. 12/23/21 - This has been reproduced.  See comments below.
2. 12/23/21 - Per the meeting held as noted in the comments below, the solution is to reject the report item with the bad equipment information and return a proper error message.  Issues #3579 and #3580 already cover this solution.  Will also need to add the proper mapperOverridesValue property to the LIVD fields to force this check.
3. 12/23/21 - Wait until #3579 and #3580 are completed to close this issue and inform Anshul

**Comment by anshulkumar-usds** [comment]
@MikeC-A6  you did some analysis in this space and found that based on how RS is setup, we use the sender-provided LOINC to lookup our mapper API. If the test kit name contained in our mapper is does not match EXACTLY as the sender-provided test kit name, then RS blanks out the LOINC when sending results to the states. However, Carlos claims that he ran a test and found that LOINC is not being removed. Can you please add more color based on what you found.

cc @MauriceReeves-usds

**Comment by anshulkumar-usds** [comment]
@carlosfelix2 Let's say the sender provide test-kit name does not match the LIVD table EXACTLY. (Let's put aside the issue of whether we should look for an exact match, or best match). Can we make the sender submission fail when their test kit name does not match the LIVD table? It will then be upon the sender to correct the issue and resubmit, instead of RS forwarding missing/incorrect data to states.

**Comment by carlosfelix2** [comment]
From @anshulkumar-usds: The issue is common across all states so far. In a nutshell, effected states, (OH, IL, MA) are receiving blanked LOINCs from RS, and that is causing failures on their end.
My understanding of RS internal mapping:
Inbound files from sender usually contains test-kit name and LOINC
RS disregards the sender-provided test-kit name, takes the sender-provided LOINC, and looks up the LIVD table (that we update manually)
Using this lookup, RS finds test-kit name and then compares that to the test-kit name provided by the sender.
If the two are not an EXACT match, we blank out both test-kit name and LOINC, BUT still route that message to the states.
My proposal:
Can we do a "best-match" type lookup and comparison against the sender file?
Often, the sender's test-kit name is missing only one characters, and we fail that completely
Can we consider failing the inbound message from the sender when the test-kit name or LOINC is TRULY off? If it's a data quality issue on the sender side, we should be providing errors/warnings at ingest.

**Comment by MikeC-A6** [comment]
@carlosfelix2 - I like this idea, but I think we should also fix the issue that the sender-provided LOINC gets blanked out if there isn't a proper test_kit_name_ID.  That way, if we do implement best match functionality for the test_kit_name_id, the sender provided LOINC is still populated whether there is or is not a best match found

**Comment by carlosfelix2** [comment]
I was able to replicate this issue.  The problem lies with the hl7 Serializer having a different logic to handle table lookups.  It actually always performs the lookup hence blanking out values if the lookup fails.  This needs to use the new lookup logic in the Element class, so all that logic is the same and in one place.

**Comment by carlosfelix2** [comment]
There is an issue with populating HL7 data that requires validation of the LIVD related data.  This becomes a problem when we get, for example, a bad equipment model and a good LOINC code that we cannot validate.  Furthermore, there are senders that truncate their equipment models to 20 characters, so this becomes a bigger problem.

**Comment by carlosfelix2** [comment]
Meeting held 12/23/2021 @ 11:00am EST.  It was decided that the issue is really the senders sending incorrect data and hence we should be rejecting report items that we cannot validate against the LIVD table.  This implies that we will need to change the logic in the CSV reader to use mappers before cardinality check (see and use Element.processValue), but we have the same issue of having the proper error message to the sender (see #3580).  If we change the logic to use mappers before cardinality checks, and change the schema to override existing values then we can have the system reject report items that have incorrect LIVD info, but the error will be seen as the data is missing (which is confusing as they did same data) when the error really is that they sent bad data.

**Comment by carlosfelix2** [comment]
Met with @rhood23699 and @brick-green-agile6. This ticket is OBE due to the addition of being able to error out when an invalid test device is provided by a sender.

**Comment by anshulkumar-usds** [comment]
@carlosfelix2 we may need to notify our senders if the errors for invalid device names are in place now. Any release notes or guidance on this?
