### ISSUE TITLE
WY - Failed ELRs on 11/10/21

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#3132]
WY's NBS system began receiving a large number of failed ELRs from Prime on November 10th. 

We reviewed the records and found the following issues which need correction or the records will continue to fail:
•	MSH-4: The required SendingFacility value was missing. 
o	Must be formatted as |SendingFacilityName^FacilityCLIA^CLIA|
o	We rather receive CLIAs than OIDs, etc. for MSH-4 for all NBS clients due to how this information is stored in the database

•	MSH-5: Records were missing this required value to indicate the receiving application. Please be sure to include the applicable information for this value. This value can be formatted as follows: |PHA_DOH|

•	MSH-6: Records were missing this required value to indicate the receiving facility. Please be sure to include the applicable information for this value. This value can be formatted as follows: |WY_DOH|

•	ORC-12.2 & ORC-12.3: These values are for the ordering provider’s first name and last name. These required values were missing. Please put “Unknown” if not available, i.e. |^Unknown^Unknown|

•	ORC-21: This value is for ordering facility name. Values were missing for this required section. Please put “Unknown” if the information is not available, i.e., |Unknown|

•	ORC-22: This section is for the ordering facility address. Values were missing for this required section. Please put “Unknown” in ORC-22.1 if the information is not available, i.e., |Unknown^^^|

•	OBR-16.2 & OBR-16.3: These values are for the ordering provider’s first name and last name. These required values were missing. Please put “Unknown” if the information is not available, i.e., |^Unknown^Unknown|

•	OBX-23: This value is the performing organization. This required value was missing from the 2nd OBX. 

Here are three examples ORC-3.1 (accession number) values from some of the failed files received from CDC Prime:
•	12A04AEE-01EE-4868-8311-C57C414490D0
•	7F3C9BF3-A016-4DCE-82F9-70A2E00FE964

Their ticket number is Ticket SUP-20332 is open for this incident.

**Comment by anshulkumar-usds** [comment]
These tests are all OTC, and the missing fields are expected. Informed state and offered to create a secondary feed. Awaiting feedback from state on next steps.

**Comment by anshulkumar-usds** [comment]
From STLT:

"Thank you for your email. We are working to include exceptions for these issues into Rhapsody to ensure they process successfully. We will continue to follow up with Cody from WY DOH and let her know once complete."
