### ISSUE TITLE
Allow State PHD to View a List of Test Events / Messages Marked as Error

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#3140]
As a state public health department, I would like tosee all the messages that were marked as error by a SimpleReport user so I can handle them appropriately in my surveillance system.

**Comment by HeatherRienks** [comment]
@mlighdc - thanks for submitting this! I moved this to our "Icebox" for now and unassigned myself. We will review and keep you posted.

cc: @loripusey & @rachelhanster

**Comment by mlighdc** [comment]
I was not sure who to flag in the issue. Maybe I should have mentioned you @HeatherRienks vs. assign. Just following the suggested process. :-)

**Comment by HeatherRienks** [comment]
@mlighdc - we appreciate it! Thanks!

**Comment by loripusey** [comment]
@rachelhanster Rachel is going to schedule a meeting with @mlighdc to get some additional information & use cases
