### ISSUE TITLE
Verbiage "Web Receiver" Got Injected into the Page where it did not Exist Previously

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3153]
**Describe the bug**
Terminology on the following page got changed and now says "web receiver", perhaps because of a merge conflict:
https://reportstream.cdc.gov/how-it-works/data-download-guide

https://usds.slack.com/archives/C02HJ43AE8Z/p1637286956456000

**Impact**
Verbiage is incorrect and may be confusing to users

**To Reproduce**
1. Go to https://reportstream.cdc.gov/how-it-works/data-download-guide
2. Scroll down and notice that the term "Web Receiver" is used 3 times on this website page

**Expected behavior**
@BerniXiongA6 what is the term that is supposed to be used here?

**Screenshots**

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/f3c113bf-fc7e-473a-900c-c51e95492a4b)
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/218fc955-eef8-45b2-a91c-94881e7de8c9)

**Comment by loripusey** [comment]
@drew-usds Can you add detail for this ticket? I couldn't see where the bug is happening, thanks!

**Comment by loripusey** [comment]
@BerniXiongA6 @drew-usds what is the term that is supposed to be used here?

**Comment by loripusey** [comment]
@BerniXiongA6 @drew-usds What is the term that is supposed to be used on this page?

**Comment by BerniXiongA6** [comment]
@loripusey According to the RS content style guide, a "web receiver" or "receiver" should be referred to as "public health department" on any public-facing page/documentation. As far as "Web receiver experience" being used in the web page copy, I think this decision was established before I took over the content role. @drew-usds Could you provide some insight on this?

**Comment by loripusey** [comment]
@BerniXiongA6 @drew-usds Can you two look at this page and indicate the verbiage to replace "Web Receiver" with in each case?  I don't think that replacing with "public health department" is going to work as the content is referring to the feature and not a PHD. cc: @rachelhanster

**Comment by BerniXiongA6** [comment]
@loripusey cc: @rachelhanster Will follow up with @drew-usds during Design Sync today to resolve this.

**Comment by drew-usds** [comment]
@loripusey easy fix! Just created a PR for it.
