### ISSUE TITLE
Redesign our error/warning system so we can give different messages to different users; also from every pipeline step

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#3154]
As [anyone seeing errors/warnings in ReportStream], I want to hear errors/warnings in my own language ("contextual messaging")
I also want to see errors/warnings from every pipeline step, not just the 'receive' step.

## Acceptance Criteria

* A Design is prepared, in this ticket, so we can move forward with coding.   The design should meet these requirements:
- Any step of the pipeline can generate warnings / errors.
- Warnings/errors can be displayed for these three Personas:

1. Download site user.   An occasional user, a healthcare professions, not a tech person.
2. Large sender user:  A non-technical person at a large sender - running an automated query and then viewing / sorting /searching errors.
3.  Technical users, internal or external.

## Design considerations

- Should we have a separate table for warnings/errors, or continue to use a jsonb?   Thinking ahead a bit, we are going to want to track lineage on a per-Item basis.   Senders want to know if every individual covid test submitted has delivered; this is a complicated question - some will deliver to multiple jurisdictions, others to no jurisdictions, which might be correct or might be an error.    I think we need a database table that tracks per-Item warnings and errors, mostly properly normalized in the database, to support these kinds of queries efficiently.
- Note that we need to be able to find Errors and Warnings without necessarily having a successful report and report_id.    This implies that the warning/errors details table (I'll call it ERROR) should FK to ACTION, not to REPORT_FILE.   This further implies that this requirement cannot be met by adding columns to the ITEM_LINEAGE table, since it FKs too REPORT_FILE.
- Not all warnings are per-Item.  Some are per-whole-Report or per submission.   In these cases, Warnings/errors in the ERROR also FK to Action table, but do not FK as items to the ITEM_LINEAGE table.   That seems ok?
- Should we enumerate errors and then parameterize them, and generate actual string error messages on the fly?  Or, should we simply store 3 different error/warning messages for each error.
- Think about whether we keep or change DetailScope (PARAMETER, REPORT, ITEM, TRANSLATION)
- Still need 'scope'
- Needs to work for HL7, CSV
- Still need line numbers (should ALWAYS start with the first test being line '1', for HL7 or CSV)
- Still need qualityFilter errors/warnings
- Still need consolidated errors/warnings when printing.
- Coordinate with the Experience team to ensure this design will work for them and will not break existing functionality.

```
// I'm picturing errors and warnings linked to action table.
// Also link to report table, Item_lineage when possible.
CREATE TABLE action_error (
    action_error_id BIGSERIAL PRIMARY KEY,
    action_id BIGINT NOT NULL REFERENCES action(action_id) ON DELETE CASCADE,
    report_id UUID BIGINT REFERENCES report_file(report_id),  //
    report_index INTEGER,  // can we FK this to ITEM_LINEAGE table?
    item_lineage_id BIGINT REFERENCES item_lineage(item_lineage_id),  // opt FK to ITEM_LINEAGE
    scope    // examples: PARAMETER, REPORT, ITEM, TRANSLATION }
    level,     // examples:  INFO, WARN, ERROR
    etc, etc with the details somehow.
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

```

**Comment by whytheplatypus** [comment]
Is this the time to add a traceable ID to a submission, allowing the system to easily see the submission every piece of information came from originally?

**Comment by whytheplatypus** [comment]
Created #3345 

There will be other follow on work, e.g. rendering this information in different ways.
