### ISSUE TITLE
SPIKE: Investigate LIVD Lookup data quality issues to determine a next step

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#3157]
There are a few LIVD lookup data issues that seem to be related in one way or another that can affect how those issues are tackled.  This issue is to look at the different issues to generate an attach plan for them.

The issues are:
#2056
#2054
#2800
#3121

Acceptance criteria:
1. Identify the problem and clean up the acceptance criteria of the related issues. 
2. Determine how the related issues should be tackled.

**Comment by anshulkumar-usds** [comment]
Adding myself to assignee for tracking
