### ISSUE TITLE
Register to use DAP with the GSA

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3161]
## Problem Statement
As the Experience Team, we need to be able to capture metrics for how senders and receivers are interacting with the ReportStream UI so that we can gain insights into the ReportStream user experience and make recommendations for improving it.

As the Experience Team, we need to register with the GSA to use DAP so that we can start using it to capture metrics for our public-facing pages. 

## Acceptance Criteria
- Register to use DAP with the GSA (team leads)

**Comment by drew-usds** [comment]
@loripusey I got my CDC address added to DAP this past week using this: https://github.com/usds/prime-simplereport-docs/wiki/DAP-access

The most confusing part is that you have to make a non-email Google account with your CDC email.

**Comment by loripusey** [comment]
@drew-usds I got a non-email Google account but can't access your USDS simple report link; is there another way to get my CDC email address on this list?

**Comment by sethdarragile6** [comment]
@drew-usds @HeatherRienks @BerniXiongA6  I was going to close this, but I wonder if we shouldn't put this in formal docs/wiki somewhere first. Thoughts?

**Comment by HeatherRienks** [comment]
@sethdarragile6 - Brilliant idea!  

@BerniXiongA6 - should this be something that is part of our new hire onboarding, with a note that it is not required for all? Worried if it's not in a central spot it will never be found! What do you think?

**Comment by BerniXiongA6** [comment]
@sethdarragile6 I love this idea! I'll go ahead and close this for you, and then I'm taking an action item to document this in our ReportStream Wiki page (will share with everyone when I do this). Thanks! cc: @HeatherRienks
