### ISSUE TITLE
Apply the DAP script to public-facing pages

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3163]
## Problem Statement
As the Experience Team, we need to be able to capture metrics for how senders and receivers are interacting with the ReportStream UI so that we can gain insights into the ReportStream user experience and make recommendations for improving it.

As the Experience Team, we need to add the DAP script to our public-facing pages so that we can indicate to analytics.gov that it should capture metrics for our pages. 

## Documentation

DAP docs & JS on GitHub:
- https://github.com/digital-analytics-program/gov-wide-code

Other docs on digital.gov:
- https://digital.gov/guides/dap/add-your-site-dap/

## Acceptance Criteria
- Download the common page tag code​ from the GSA website
- Add the DAP script to ReportStream's public-facing pages
- Make sure we turn it off for staging & local

**Comment by drew-usds** [comment]
DAP documentation & JS on GitHub:

- https://github.com/digital-analytics-program/gov-wide-code

Documentation on digital.gov:

- https://digital.gov/guides/dap/add-your-site-dap/

**Comment by drew-usds** [comment]
Something to note: in their docs they mention we add a little bit of content in an HTML comment above where we link to the script. Ex:

```
<!-- We participate in the US government's analytics program. See the data at analytics.usa.gov. -->
<script async type="text/javascript" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=AGENCY" id="_fed_an_ua_tag"></script>
```

**Comment by bgantick** [comment]
This should only go on pages that don't require authentication (per the docs): https://digital.gov/guides/dap/add-your-site-dap/#appropriate-placement-of-the-dap-script-tag

**Comment by kevinhaube** [comment]
Merged 05/10/2022
