### ISSUE TITLE
Truncate Provider ID Field

### ISSUE THREAD

**Issue by MikeC-A6** [CDCgov/prime-reportstream#3169]
As a receiver, I want `ordering_provider_id` values with more than 15 characters to be truncated to 15 characters so that messages do not fail in my integration engine for failing the HL7 specification.

Acceptance Criteria:
1. Given that sender sends in a COVID-19 test that has a value with > 15 characters in the ordering_provider_id field, and the data goes to an HL7 output, then `ORC-12` and  `OBR-16-1` should populate with a truncated version of that value, with 15 characters maximum
2. Given that sender sends in a COVID-19 test that has a value with > 15 characters in the ordering_provider_id field, and the data goes to an CSV output, then the `ordering_provider_id ` CSV field should populate with a truncated version of that value, with 15 characters maximum

**Comment by MikeC-A6** [comment]
@RickHawesUSDS - let me know if you are able to pull this Provider ID truncation story - it is high priority for IL to prevent messages from failing

**Comment by RickHawesUSDS** [comment]
Deployed
