### ISSUE TITLE
Provider_ID ordering_authority and ordering_authority_type bug

### ISSUE THREAD

**Issue by MikeC-A6** [CDCgov/prime-reportstream#3170]
**Background:**
Something other than a Provider [NPI](https://www.cms.gov/Regulations-and-Guidance/Administrative-Simplification/NationalProvIdentStand/Downloads/NPIcheckdigit.pdf) is sometimes sent in the `Ordering_Provider_ID` field, yet Reportstream applies a default to tag any value as an NPI.  Specifically, in the `ordering_provider_id_authority` field, the base COVID-19 schema uses the ifPresent() mapper to automatically apply CMS' OID - `mapper: ifPresent(ordering_provider_id, NPI^2.16.840.1.113883.4.6^ISO)`.  Additionally, for the `ordering_provider_id_authority_type`, Reportsream uses the ifPresent() mapper to default that field to NPI.

The NPI is a specific 10-digit numeric format issued by CMS.  If the sender sends in something other than a NPI in the `Ordering_Provider_ID` field, then associated fields should not be populated to indicate that the value is an NPI.  This validation could happen in 1 of 2 ways:

1. Validation could be done on the format of the value to test whether it matches to CMS' defined format for NPI, and if not, use another default value
2. Validation could be done using the NPPES API to test whether the incoming value is actually a valid NPI tied to a provider.  Leveraging the API may create data enrichment opportunities to populate other values like ordering_provider_name if we have a NPI, but the provider name is missing.

In either case, we need to determine what an alternate default value would be for the following fields in instances where the value is not a valid NPI:

1. `ordering_provider_id_authority_type`
2.  `ordering_provider_id_authority`

**Comment by MikeC-A6** [comment]
@brick-green-agile6 - please comment on your recommendation for an alternate default value for the 2 fields listed, in cases where the value provided is not a NPUI

**Comment by RickHawesUSDS** [comment]
Deployed
