### ISSUE TITLE
Send only properly formatted NPIs to certain STLTs

### ISSUE THREAD

**Issue by MikeC-A6** [CDCgov/prime-reportstream#3172]
**Background**
At least 1 STLT (IL) has requested to receive a value in the `ordering_provider_id` field only when the value provided is a properly formatted NPI.  

**Story**
As a STLT, I want to be able to decide whether I receive a value in the `ordering_provider_ID` field and associated fields* if the ordering_provider_ID provided is not a properly formatted NPI so that I am only receiving values that are meaningful.

- `ordering_provider_id `
- `ordering_provider_id_authority`
- `ordering_provider_id_authority_type`

1. Given that a message is received into Reportstream with something other than a properly formatted NPI in the ordering_provider_ID field, and when the receiving STLT is Illinois, then the 3 fields listed above should not be populated with any values in the outbound message

**Comment by RickHawesUSDS** [comment]
Deployed
