### ISSUE TITLE
Handle non-unique matches in LIVD lookups

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#3175]
The LIVD lookup is currently matching the first hit regardless if there are other possible hits in the table.  For example, looking up the model `1copy COVID-19 qPCR Multi Kit` really matches 5 different records, but the way the LIVD lookup is done it actually returns the last entry.  

Design notes:
Why does it return the last entry?  A map is being used and as the table is read then subsequent identical values overwrite the one set in the map, so the last entry always wins.  Will need a new algorithm for this.

But wait, there is more: See for example the first five rows of the RS LIVD table, the device with model name `1copy COVID-19 qPCR Multi Kit*`.  As you can see in the table, the only difference between those 5 rows is the equipment UID with its type.  For this example it is impossible to figure out what value to grab if you do not have the device ID.  One possible solution to alleviate empty data is to determine if the value we need is the same for all the rows then use the value since it is unique. 

Furthermore, we could try to do a better match using more data, but that is a different issue.

Acceptance criteria:
1. LIVD lookup mapper returns an empty field if a LIVD lookup is not a unique value from one or more matches.  E.g. We match 5 rows in the table, but the value we need is not the same among those 5 rows we found.
2. LIVD lookup mapper returns a value when a unique value from one or more matches can be found.  E.g. we match 5 rows in the table, but the value we need is unique in all those rows.

**Comment by jimduff-usds** [comment]
@carlosfelix2 is this ticket done?  If so, can the blocked ticked become unblocked now?
