### ISSUE TITLE
CSV pilot - Post Research - Synthesize Results from CSV Uploader Pilot

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3197]
## Problem statement
As the Experience Team, we need to synthesize the results collected from the piloting of the CSV Uploader feature for Cohort 2, so that we can guide direction of the ReportStream product. 

## What you need to know
- This is a companion to customer journey maps

## Ideas to start with: 
- metrics outlined in [csv deck ](https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BDE566704-B7F3-4B2E-9EAA-332B8FE7CD0B%7D&file=ReportStream%20CSV%20dataset%20and%20quality%20improvements.pptx&action=edit&mobileredirect=true&cid=be01cb8c-ee97-4100-839d-14d932d8f9f9)
- research plans for senders and receivers  
- Are users able to upload a csv?
- Do error messages make sense?
- What is working well about the csv upload? 
- What could be improved about the csv upload process?

## Acceptance criteria
- [ ] Update notes/call info in Excel 
- [ ] Pull data on errors from metabase and reportstream and add to cumulative errors excel [add link to share point]
- [ ] Share insights with team:
  - [ ] Slack 
- [ ] standup sync with Product
- [ ] @rachelhanster add findings to product [deck](https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BDE566704-B7F3-4B2E-9EAA-332B8FE7CD0B%7D&file=ReportStream%20CSV%20dataset%20and%20quality%20improvements.pptx&action=edit&mobileredirect=true&cid=be01cb8c-ee97-4100-839d-14d932d8f9f9)

**Comment by victorialb-usds** [comment]
@BerniXiongA6 tagging you here so you can see the original ticket on this
https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B3883912A-317A-4E99-8A2E-187C105C02BF%7D&file=A1H%20Pilot%20Synthesis_1.27.22_Internal.pptx&action=edit&mobileredirect=true
