### ISSUE TITLE
Develop Plan - Understand Ways PHDs Want to Get Data

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#3200]
## So far the research plan on CSV upload pilot has focused on senders. I would like to include/pair this with receiver research. 

Develop a research plan for receivers CSV upload pilot

## What you need to know
What is the experience of receivers for the CSV pilot? What errors or pain points are they experiencing in setting up this connection? 
What is the current process for collecting data with California on this? 
Could experience attend those meetings? 
What data on this do we already have and could this be saved in share point CSV upload pilot. 
... 

## Acceptance criteria

- Create a plan for this [small]
- Shared with Design, then experience then Core CSV upload pilot group for finalization

## To do

- Loop in the communications effort to put this on radar of O+O
- VLB meet with Rick Hood
- VLB draft plan and share with Design, then experience then Core CSV upload pilot group for finalization

**Comment by loripusey** [comment]
@victorialb-usds 
- Can we take another look at this ticket and see if what we really need is something similar to this ticket but for how Receivers want/need to receive data and their pain points with data quality (isn't necessarily tied to the CSV Uploader pilot). 
https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/2843
- Can Victoria get invited to the weekly calls with PHDs? (CA?) or are you already invited?

**Comment by rachelhanster** [comment]
@victorialb-usds I requested @rhood23699 's help to forward you the call series with California.

**Comment by loripusey** [comment]
@victorialb-usds we changed the title for this one, please update the AC if you need to
