### ISSUE TITLE
Add Leading Zero to 4 Digit Zip Codes And Two Leading Zeros to 3 Digit Zip Codes

### ISSUE THREAD

**Issue by jorg3lopez** [CDCgov/prime-reportstream#3202]
### Issue:
Some states have 4 digit zip codes, this creates an error in their system as they are expecting a 5 digit zip code; the same is true for states that have a 3 digit zip code.

### The fix:
- Add a leading zero if the zip code is only 4 digits long
- Add two leading zeros if the zip code is only 3 digits long

**Comment by jorg3lopez** [comment]
@anshulkumar-usds @mlighdc This is the ticket to address adding leading zero(s) when zip code has a length of 4 or 3 digits. PR is up, awaiting review.

**Comment by anshulkumar-usds** [comment]
This ticket also addresses specific issue for VT: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/2933

**Comment by jorg3lopez** [comment]
Submitted test file to VT test feed on 11/29/2021. This is the file name: 
test-covid-19-eb10b765-afed-4fe0-addb-c70f44b1c0f7-20211129194404

**Comment by mlighdc** [comment]
Sent email to VT to let them know that a test file is ready for their review. Hoping they can provide feedback today, if possible but know it is late in the day for them.

**Comment by anshulkumar-usds** [comment]
@jorg3lopez is this still an issue given the fix for VT?

**Comment by jorg3lopez** [comment]
Will close this. File being tested was missing the zero but it was present in the actual incoming file in Azure.

**Comment by jorg3lopez** [comment]
Closing this ticket because the zip code issue has been resolved. The problem was the file that I used to generate the hl7 file, it was missing the leading zero. After further investigation, we noticed that the original file in Azure had the leading zero.
