### ISSUE TITLE
Synthesize Front-End Analysis Results​

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3207]
## Problem Statement
As the Experience Team, we need to synthesize and understand the front-end analysis results so that we can identify strategies for evolving our product and add additional metrics, if more data points are needed.

## Acceptance Criteria
- Synthesize front-end analysis results
- Document the synthesis
- Present to the team
- Recommend additional metrics

**Comment by chris-kuryak** [comment]
Per Kevin Haube on Dec 8, 2022 comment on this epic, 
"Closing out, no details in here. Work all looks like App insights work. See #7518 "
