### ISSUE TITLE
Create Metabase Queries to Measure ReportStream Usage​

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3209]
## Problem Statement
As the Experience Team, we need to capture metrics for how senders and receivers are using ReportStream so that we can gain insights into usage and user retention and make recommendations for improving ReportStream.

## Queries we would like
- Senders & Receivers
    - List of active receivers **(done, needs QA)**
    - % receivers that are active 
    - List of active senders **(done, needs QA)**
    - % senders that are active
    - Number of active senders **(done, needs QA)**
    - Number of active receivers by jurisdiction **(done, needs QA)**
- Reports Received & Sent
    - Number of reports submitted by active senders by sender & week **(using existing query, needs QA)**
    - Number of reports sent to active PHDs by PHD & week **(using existing query, needs QA)**
- Test Results Received & Sent
    - Number test results submitted by active senders & week **(using existing query, needs QA)**
    - % active senders sending data by week 
    - Number test results received by active PHDs by PHD & week  **(using existing query, needs QA)**
    - Number test results received by active PHDs by PHD & week & feed 
    - % active receivers getting data by week 

---

- Senders & Receivers
    - List of active receivers: https://prime.cdc.gov/metabase/question/153-live-stlt-orgs
    - % receivers that are active: https://prime.cdc.gov/metabase/question/194-percentage-of-active-receivers-over-total-receivers
    - List of active senders: https://prime.cdc.gov/metabase/question/154-live-reporting-orgs
    - % senders that are active: https://prime.cdc.gov/metabase/question/195-percentage-of-active-senders-over-total-senders
    - Number of active senders: https://prime.cdc.gov/metabase/question/113-live-organizations
    - Number of active receivers by jurisdiction: https://prime.cdc.gov/metabase/question/167-live-stlts-by-jurisdiction
- Reports Received & Sent
    - Number of reports submitted by active senders by sender & week: https://prime.cdc.gov/metabase/question/201-number-of-reports-submitted-by-active-senders-by-sender-week
    - Number of reports sent to active PHDs by PHD & week: https://prime.cdc.gov/metabase/question/202-number-of-reports-sent-to-active-phds-by-phd-week
- Test Results Received & Sent
    - Number test results submitted by active senders & week: https://prime.cdc.gov/metabase/question/71-covid-test-results-sent-to-reportstream-per-submitter-per-week
    - % active senders sending data by week: https://prime.cdc.gov/metabase/question/196-active-senders-sending-data-by-week
    - Number test results received by active PHDs by PHD & week: https://prime.cdc.gov/metabase/question/200-number-test-results-received-by-active-phds-by-phd-week
    - Number test results received by active PHDs by PHD & week & feed: https://prime.cdc.gov/metabase/question/198-number-test-results-received-by-active-phds-by-phd-week-feed
    - % active receivers getting data by week: https://prime.cdc.gov/metabase/question/199-active-receivers-getting-data-by-week

**Comment by loripusey** [comment]
@hermanAlexCordero @Adrian-Brewster in what sprint were you planning to look at these and do you have a different ticket off of which you are working?

**Comment by loripusey** [comment]
@hermanAlexCordero @Adrian-Brewster Not sure if this is still on your radar, but I have updated & added some new MB queries to the [Experience Team Dashboard](https://prime.cdc.gov/metabase/dashboard/20-experience-team-dashboard) (see comments in the AC above) 
cc: @rachelhanster

**Comment by hermanAlexCordero** [comment]
@loripusey I will add the new queries to the set.  The first set of queries were being reviewed with Mike before I went on vacation.  I'll update the ticket when I'm done with the new queries

**Comment by anshulkumar-usds** [comment]
@loripusey - @hermanAlexCordero is no longer with O&O so I'm removing him from the ticket and the O&O label for now.

**Comment by loripusey** [comment]
Some of the queries have been written and now exist on the Experience Team dashboard (mostly the numbers ones) - these probably need to be reviewed for query correctness but also need to be reviewed because some of the fields where we get data are not being consistently used across senders & receivers
None of the percentage queries have been created

**Comment by ahay-agile6** [comment]
## Queries we would like
- Senders & Receivers
    - List of active receivers **(done, needs QA)** https://prime.cdc.gov/metabase/question/153-live-stlt-orgs
    - % receivers that are active https://prime.cdc.gov/metabase/question/194-percentage-of-active-receivers-over-total-receivers
    - List of active senders **(done, needs QA)** https://prime.cdc.gov/metabase/question/154-live-reporting-orgs
    - % senders that are active https://prime.cdc.gov/metabase/question/195-percentage-of-active-senders-over-total-senders
    - Number of active senders **(done, needs QA)** https://prime.cdc.gov/metabase/question/113-live-organizations
    - Number of active receivers by jurisdiction **(done, needs QA)** https://prime.cdc.gov/metabase/question/113-live-organizations
- Reports Received & Sent
    - Number of reports submitted by active senders by sender & week **(using existing query, needs QA)**
    - Number of reports sent to active PHDs by PHD & week **(using existing query, needs QA)** https://prime.cdc.gov/metabase/question/21-test-reports-sent-weekly
- Test Results Received & Sent
    - Number test results submitted by active senders & week **(using existing query, needs QA)** https://prime.cdc.gov/metabase/question/71-covid-test-results-sent-to-reportstream-per-submitter-per-week
    - % active senders sending data by week https://prime.cdc.gov/metabase/question/196-active-senders-sending-data-by-week
    - Number test results received by active PHDs by PHD & week  **(using existing query, needs QA)**
    - Number test results received by active PHDs by PHD & week & feed https://prime.cdc.gov/metabase/question/198-number-test-results-received-by-active-phds-by-phd-week-feed
    - % active receivers getting data by week https://prime.cdc.gov/metabase/question/199-active-receivers-getting-data-by-week
