### ISSUE TITLE
Remove token authentication from TOS Agreement

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#3223]
## Problem statement

Currently, the UI is using token-based authentication for the Terms of Service Agreement form, but this page needs to be an unauthenticated route.

## What you need to know

![Screenshot from 2021-11-29 12-28-08.png](https://images.zenhubusercontent.com/611a907ec3e013d0e33e58a7/a8239510-79f7-41be-a90c-1842b526cf0c)

## Acceptance criteria

- [ ] A user can only access the form without being logged in from US State + Territory IP addresses
- [ ] A user can submit the form and receive a verification email

## To do

- [ ] Remove Authorization token passing from `fetch` call
- [ ] Remove Authorization token check from method

**Comment by kevinhaube** [comment]
Blocked by #2757

**Comment by loripusey** [comment]
still need to test in staging after blocker removed

**Comment by loripusey** [comment]
2 bugs remain; @cwinters-usds working on
