### ISSUE TITLE
NM - Incorporate NCES ID

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#3233]
NM is expanding the use of SimpleReport to more schools and would like to leverage the ReportStream work done to date with the NCES ID.

NM would like test files sent prior to moving this into production for them.

For a test message, rather than “prod” in the file name, use “test” similar to during onboarding. Please let NM know when the test files / messages have been sent.

To Do:

- [x] Test files /messages sent have been approved by NM

**Comment by mlighdc** [comment]
NM would like test files sent prior to moving this into production for them. 

For a test message, rather than “prod” in the file name, use “test” similar to during onboarding. Please let NM know when the test files / messages have been sent.

**Comment by anshulkumar-usds** [comment]
@RickHawesUSDS are there any configurations updates you need to do on your side to enable this function for NM? Same learnings can be applied to CA as well when they get back to us.

**Comment by anshulkumar-usds** [comment]
@RickHawesUSDS has completed deployment to make the NCES ID available for NM. Need to send test file(s) to NM for validation before enabling fully in prod.

**Comment by RickHawesUSDS** [comment]
@anshulkumar-usds Sent you a set of test files to give NM.

**Comment by anshulkumar-usds** [comment]
Anshul to fu with NM and share files

**Comment by anshulkumar-usds** [comment]
Shared test files with NM on 12/21 - awaiting STLT feedback

**Comment by anshulkumar-usds** [comment]
@RickHawesUSDS NM approved the changes and requested we enable the same change in prod. Please let us know next steps.

fyi - @MauriceReeves-usds
