### ISSUE TITLE
STRAC - Add properties to sender schema

### ISSUE THREAD

**Issue by hermanAlexCordero** [CDCgov/prime-reportstream#3234]
## Problem statement

STRAC results are failing for MA (Issue 3134).  This is caused by missing testing_lab_ entries in the schema.  The entries need to be added to the strac-covid-19.schema.

## Acceptance criteria

- [ ] OBX-24 XAD must contain Performing Organization Address

## Testing

- [ ] Tested Locally?
- [ ] Ran deidentified file against local instance of Report Stream and verify OBX-24 XAD gets populated

## Fixes

- [3134](https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3134)

**Comment by RickHawesUSDS** [comment]
Is the proposal that STRAC add these fields (which will not happen) or RS fill them in?

**Comment by hermanAlexCordero** [comment]
RS will fill them from the testing_lab fields.  Just need to update the schema.  I already tested locally.  Getting ready to do the pull request.

**Comment by hermanAlexCordero** [comment]
Double ticket.  Ticket 3134 covers this issue.  We'll be closing this ticket.
