### ISSUE TITLE
SPIKE -- Bug: PrimeAdmins is missing from the Settings db

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#3236]
Context: https://github.com/CDCgov/prime-reportstream/issues/2989

Right now, we do not have PrimeAdmins in the Settings db. When we call workflowEngine.settings.findOrganization(orgName.replace('_', '-')) we are asking for the db to return that organization from the proper table, so when this returns null we see the error message written above. To fix this, the PrimeAdmins organization would first need to be added to the proper table.

**Comment by bgantick** [comment]
Closing: I think this issue was resolved via https://github.com/CDCgov/prime-reportstream/pull/3727
