### ISSUE TITLE
SOAP Transport Improvements

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#3238]
A collection of issues centered on making improvements to the SOAP transport.

**Comment by MauriceReeves-usds** [comment]
FYSA: @anshulkumar-usds @Adrian-Brewster I have added the following epic to include changes and improvements for the SOAP transport type based on code reviews.

**Comment by brandonnava** [comment]
@MauriceReeves-usds @brick-green Are SOAP improvements still on our radar or close as we move to a more RESTful world?

**Comment by brandonnava** [comment]
@brick-green is it safe to say we're not doing SOAP?

**Comment by brick-green** [comment]
We're using SOAP for PA. So we won't be able to avoid it completely. Hopefully we won't have to add any additional STLTs though.

**Comment by brandonnava** [comment]
Closing as the SOAP transport works well enough now for PA. Will reopen or start fresh should the need for improvements arise down the road
