### ISSUE TITLE
Add tests to IGNORE for SOAP

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#3242]

**Comment by LaFreda1** [comment]
@oslynn To update requirements for the ticket

**Comment by jalbinson** [comment]
Hi @oslynn, can you add more specific requirements for this ticket?

**Comment by oslynn** [comment]
@jalbinson I will look at them and will add more info to the ticket.

**Comment by oslynn** [comment]
This ticket is already done.  I am closing it.
