### ISSUE TITLE
Basic Row Filtering

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#3248]
## Problem Statement
As an **EMR platform user**, my data may contain Rows that represent an order not a result, and Rows for test results that are not accepted by ReportSteam.

## Examples
As an example, when a user orders a test, their system sends at least two rows of data.  One for the order and one or more rows with results. If the CSV field named "RecordType" has "O", then the Row should be excluded from processing.  We are temporarily doing this in a VBScript by removing this row from the CSV file.

Also in the same file, there could be multiple results for one ordered test.  The ordered test is "BD Veritor COVID Flu A&B Panel" which has three results and we accept only the COVID Antigen result.  The row with ordered test of "BD Veritor COVID Flu A&B Panel" and test performed of "Antigen Result" is the only result that should be accepted.  The rows for the results on "FluA" and "FluB" should be excluded from processing.  We are temporarily doing this in a VBScript by removing the FluA and FluB rows.

## Acceptance Criteria
- Given I
    - Am logged into ReportStream as a user with Sender permissions
    - Am a Sender who is using the Experity schema
- When I
    - Log into ReportStream
    - Upload a CSV file
- Then 
    - The System, prior to submitting the file to ReportStream for processing, checks 1 or more fields and, based on the field value(s), excludes rows from processing.
   
## Design Considerations
- This may require implementation of the database lookup tables, but excluding Rows may have to be done outside of ReportStream.
- Details of the AC will be determined by whether or this process is done within ReportStream or not; but the basic AC is that rows are included and excluded based on the values from 1-3 fields within the CSV file.

**Comment by loripusey** [comment]
@rhood23699 Can you elaborate on your statement above "Details of the AC will be determined by whether or this process is done within ReportStream or not"; how will the implementation change the AC?
cc: @rachelhanster

**Comment by rhood23699** [comment]
ReportSteam as-is cannot exclude rows from processing.  If the Engineers believe that RS can be modified to exclude rows, then we'll have to wait and see how they plan to accomplish it.  Basically, will we use the existing lookup table and mapper functionality or not.  If RS cannot be modified, then Engineer will have to determine how this will be accomplished in the front-end CSV Uploader.

**Comment by loripusey** [comment]
@rhood23699 
- who is the sender to which you are referring?
- what is the level of priority for onboarding this particular sender? 
- is this a blocker for onboarding this sender?

**Comment by rhood23699** [comment]
We cannot move Greenlight Urgent Care or Compass Urgent Care off of VBScript until this is done, but more importantly, we have worked with 4 Senders and all required Row Filtering.  Our ability to onboard new Senders is very limited without this.  Note, we had a meeting today with LADOH about new Senders, and this will be a roadblock to onboarding some of them.

**Comment by loripusey** [comment]
Thanks @rhood23699 ! I know you put high priority, is it safe to say that this one should come before the other data cleansing tickets?

**Comment by rhood23699** [comment]
Yes, it is a higher priority.

**Comment by HeatherRienks** [comment]
@victorialb-usds - FYI

**Comment by HeatherRienks** [comment]
@rhood23699 - @rachelhanster & @loripusey  would like more info on this before we proceed. Thx!

**Comment by rhood23699** [comment]
@HeatherRienks @rachelhanster @loripusey Let me know when y'all have time discuss the need to implement Row Filtering as soon as possible.  I consider this a critical need to move forward with as many Senders as possible.  We have worked with 5 Senders for CSV uploading (Reddy, Greenlight, Compass, TCCH, and Main Street).  They have all required Row Filtering.

If we do not have Row Filtering, the Senders will receive large numbers of error messages that are not really errors which will cause them to miss actual errors within the error report.

Example #1, for a Sender who performs COVID Flu Panels, 2 out of every 3 results will be reported as errors because we don't accept Flu A & Flu B results.  For a small Sender of 50 panels a day, they will see 100 error messages which will greatly increase the chances that they will miss an actual error within the large error report.  Also in my opinion, this just simply looks unprofessional.

Example #2, for a Sender who cannot send COVID only, all non-COVID results will be reported as errors.  Once again, there may be a large numbers of errors for a batch of results with few COVID results.

Example, #3, some Sender EMR system produce a file that includes more than one Row for a single COVID result.  This extra Row is typically an order Row.  These rows will be reported as errors.

**Comment by loripusey** [comment]
Thanks @rhood23699 that was helpful information.

**Comment by loripusey** [comment]
De-prioritized as of 12/27

**Comment by rachelhanster** [comment]
Closing. No custom schemas going forward, and uploader's moving to simplereport.
