### ISSUE TITLE
HCA - New ReportStream topic:  'full-elr'

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#3253]
This needs grooming.

- Create a new schema 'full-elr.schema', in the folder metadata/schemas/, top level.
- It'll have a new "topic" 'full-elr', NOT 'covid-19'
- create a child schema for HCA, setting the sender-id default etc.
- Run our same sample set through it.
- We'll work through the other issues here in the context of this new topic.
- At a minimum, it'll have test_performed LOINC but not the other device-related fields, to match with what we are and are not getting from HCA.
- Its possible the current way topics work will be inadequate for 'full-elr'.   its too soon to tell until we talk to the states.

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/3253?planning-poker) with ZenHub @jimduff-usds @smythe5 @whytheplatypus @oslynn @carlosfelix2 @jh765

**Comment by anshulkumar-usds** [comment]
Removing O&O and @jbiskie from the ticket. cc @jimduff-usds

**Comment by carlosfelix2** [comment]
OBE full ELR will not run through the current pipeline.
