### ISSUE TITLE
R&D - Research Organizations Requesting Support

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3279]
## Problem Statement
As the Experience team, we need to understand what we can do in the near term (before we get a new CRM) to allow organizations to easily request support.

## Acceptance Criteria
- Collect data on what types of requests we currently receive and how many of each type
- Look at and document/map our current request processes, including steps performed by the O&O team
  - Look into time it takes to request support
- Determine what steps could potentially be automated
- Make recommendations

## Notes
- Consider Senders & Receivers
- Maybe look at what Simple Report is doing (https://www.simplereport.gov/support/)
- Maybe take a look at whether we need better documentation & perhaps "mail to" links
- What are the categories for support?

**Comment by chris-kuryak** [comment]
Closing by committee. Old issue that will come up again in the future and will be re-scoped at that time.
@drew-usds @lizzieamanning
