### ISSUE TITLE
Receiver-facing: Summary stats about data from reportstream

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#3286]
As a ReportStream state public health department user, I would like to have visibility into how many test results each facility in my jurisdiction have submitted.

Suggestions for filtering options:
- by facility
- by facility/organization type
- by timeframe
- by county 
- by city

See this dashboard from Simple Report as a reference: https://training.simplereport.gov/app/dashboard?facility=3c0e79e5-1389-4313-a22d-f737f570b711

**Comment by HeatherRienks** [comment]
@mlighdc - thank you for submitting!

**Comment by victorialb-usds** [comment]
Add this to receiver research plan and facilitation guide or do short follow up calls showing this as model. We have asked about this in the CSV upload pilot to know what they want to see but having an example might help elicit more answers.

**Comment by victorialb-usds** [comment]
@drew-usds @BerniXiongA6 @inkandsound

**Comment by victorialb-usds** [comment]
We asked this in the WA discovery call (2/8/22) and it did not resonate. they just look at their surveillance to see if its been uploaded.

**Comment by victorialb-usds** [comment]
Will ask at COPHE 2.23.22

**Comment by victorialb-usds** [comment]
From COPHE and CA - they would like to see
- if the sender is in testing or production
FROM COPHE 2.23.22
-  by Facility – and by program CSV and SR and HL7
- filter by dates, weekly what comes in by facility, counts, by program (CSV, SR, HL7)
- affirmed a chart type view would be good. FYI: @drew-usds @inkandsound

**Comment by victorialb-usds** [comment]
Notes doc for Receiver Dashboard initial requests, comments, etc. This should help to put it all in one scannable place as we as ask some initial questions about what PHDs want to see during other calls - we can refer to it when writing up a design brief/AC so we know we're creating a dashboard that serves actual needs.
https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B2C375318-E722-4CAB-9E6D-984360C7D1A5%7D&file=Receiver%20Dashboard%20-%20Initial%20Research%20Notes.docx&action=default&mobileredirect=true

**Comment by victorialb-usds** [comment]
I am creating a new ticket for user story: As a ReportStream state public health department user, I would like to have visibility into what testing facilities are in testing and production. #4527

**Comment by victorialb-usds** [comment]
@BerniXiongA6 this relates to 3919

**Comment by BerniXiongA6** [comment]
@drew-usds pls pre-refine at design sync

**Comment by HeatherRienks** [comment]
@drew-usds - Per refinement mtg., pls create a new Epic (while we shift gears for Pipeline's refactoring work).

**Comment by chris-kuryak** [comment]
Closing due to being old/stale. Will reference in new epic for research purposes.
Closing by committee @drew-usds @jillian-hammer @lizzieamanning @audreykwr
