### ISSUE TITLE
MA - PID.20 of type PID.20.DLN

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3287]
MA identified an issue in the file delivered on 11/24. Below is what MA provided in secure message:

There was also an error in the file received 11/24, due to a Driver's License Number, which was also missing an OBX.24 section.  Can you please review, edit, and resubmit as necessary.

MSH|^~\&|CDC PRIME - Atlanta, Georgia (Dekalb)^2.16.840.1.114222.4.1.237821^ISO|Chester County Health Department^39D0673533^CLIA|MA-MDPH^2.16.840.1.113883.19.3.2^ISO|MA-MDPH^2.16.840.1.113883.19.3.2^ISO|20211124141501.8739+0000||ORU^R01^ORU_R01|767294|P|2.5.1|||NE|NE|USA|UNICODE UTF-8|||PHLabReport-NoAck^ELR_Receiver^2.16.840.1.113883.9.11^ISO

SPM|1|767294&Chester County Health Department&39D0673533&CLIA^binax_81dd649c5da288b32f8a2a01a5130e0e&Chester County Health Department&39D0673533&CLIA||258500001^Nasopharyngeal swab^SCT^^^^2.67|||||||||||||202111230938-0600|20211123093806.0000-0600

Error: Driver's License Number - Patient (PID.20 of type PID.20.DLN) repeats more than maximum occurence allowed.

Message rejected.

**Comment by anshulkumar-usds** [comment]
Herman - this may be related to the ticket you recently worked on for MA OBX.24 issue: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3134

**Comment by anshulkumar-usds** [comment]
@hermanAlexCordero can you please share on update on this?

**Comment by anshulkumar-usds** [comment]
@hermanAlexCordero can you please provide an update on next steps?

**Comment by hermanAlexCordero** [comment]
The error is misleading.  The issue with the failing HL7 is because the sender is sending a "0" (zero) as driver license.  We could leverage the schema to create a default value or map a zero to "blank"

Checking with @anshulkumar-usds  for suggestions.

**Comment by anshulkumar-usds** [comment]
@hermanAlexCordero please set the value to blank if the sender provided value is invalid.

**Comment by hermanAlexCordero** [comment]
Tried to map the patient_driver_license to blank when DL is 0 (zero).  We cannot map values on type ID_DLN so changing the type to CODE permits mapping the value to Blank.
Upon further reviewing the data from STRAC, the patient_driver_license column have almost any value.  
![image.png](https://images.zenhubusercontent.com/60f97bb38b9c26403cc29560/aaa74e64-1514-4058-bb1a-27a2d5027145)
request advice on next steps

**Comment by hermanAlexCordero** [comment]
Tried to map the patient_driver_license to blank when DL is 0 (zero).  We cannot map values on type ID_DLN so changing the type to CODE permits mapping the value to Blank.
Upon further reviewing the data from STRAC, the patient_driver_license column have almost any value.  
request advice on next steps
