### ISSUE TITLE
Discovery Call with Louisiana Department of Health

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3289]
## Problem Statement
As the Experience Team, we need to have a discovery call with the Louisiana DH so that we can understand how users in Louisiana are currently submitting flat files.

**Comment by victorialb-usds** [comment]
Did call 12/6 Victoria, Kevin, Drew, Ming and Rick and 2 LADOH reps
- LADOH share their redcap process for currently uploading - think-a-loud
- VLB asked open ended questions to gauge current process and paint points
- Rick demo'd CSV upload
Next steps: 
- LADOH will be updating list of CSV pilot letting us know which ones might be good pilot
- Rick and USDS team create criteria for selection of senders into pilot
- Design will do f/u to get feedback on prototypes
- VLB will be summarizing notes [need to make ticket for this]

**Comment by drew-usds** [comment]
Raw notes here on sharepoint:

https://cdc.sharepoint.com/:w:/t/USDSatCDC/EQGTWmP5w9FNjAmdWXU6YIwBtq00KW1xxrdPtN-lRi523w?e=L9dGR5
