### ISSUE TITLE
Discovery Call with Vermont Department of Health

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3290]
## Problem Statement
As the Experience Team, we need to have a discovery call with the Vermont DH so that we can understand how users in Vermont are currently submitting flat files.

- [x] call 1 [VHD]

- [x] call 2 [VHD]

- [x] call 3 [VITL] (1/6)

**Comment by HeatherRienks** [comment]
call scheduled for Monday 12/13/21.

**Comment by victorialb-usds** [comment]
Call notes: https://cdc-my.sharepoint.com/:w:/r/personal/tcq5_cdc_gov/_layouts/15/Doc.aspx?sourcedoc=%7BAF3474DF-1819-44FB-9D4F-F5B8CDF995A8%7D&file=Vermont%20PHD_discovery%20session%20guide_12.01.2021%20internal%20notes.docx&action=default&mobileredirect=true

To do call 3 with VITL.

**Comment by victorialb-usds** [comment]
call 3 scheduled for 1/6 with Regi

**Comment by victorialb-usds** [comment]
Here is a link to the notes:
https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Experience%20Research/CSV%20flat%20file%20upload%20December%202021%20ongoing/Vermont%20discovery%20research%20flat%20file%20upload%20December%202021/PHD%20STLT_CSV%20upload%20pilot%20VT%20discovery%20call%20%232%20of%201.6.21.docx?d=w87c58cac677a4e10baee9c759602e802&csf=1&web=1&e=CXyNqQ 

Rec closing it is complete. Regi said we can go back to her to talk again. Will put more on synthesis ticket. VT does not want to pilot CSV but would like to see it once its tested.
