### ISSUE TITLE
Discovery Call with Colorado Department of Health

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3291]
## Problem Statement
As the Experience Team, we need to have a discovery call with state public health department, so that we can understand how users are currently submitting covid test data, including state's flat file method.

- [x] call 1

- [x] call 2 with state's flat file contact person

**Comment by victorialb-usds** [comment]
Call with Flat file focused staff 12/23; Research can be found in this folder: https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Experience%20Research/CSV%20flat%20file%20upload%20December%202021%20ongoing/Colorado%20discovery%20research%20flat%20file%20upload%20December%202021?csf=1&web=1&e=KafYGp

**Comment by victorialb-usds** [comment]
CO is eager to work with us in whatever way possible to get folks onto SR or using a RS flat file option as per call 12/21/21

**Comment by victorialb-usds** [comment]
Completed the call - recording and notes https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStre[…]3%20Call%20Two%20_Nancy%20%26%20Alyson?csf=1&web=1&e=IfVHWI (edited)

**Comment by victorialb-usds** [comment]
@rachelhanster @loripusey @drew-usds FYI I moved this into review. If you can take a look at what I put in this ticket and if its ready for closing.

**Comment by loripusey** [comment]
Notes look good!
