### ISSUE TITLE
Content Bug - No Recipients but Says Delivered to Health Department

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3306]
**Describe the bug**
Even though the message says that there were no recipients who received my CSV File, the message header says that my file was delivered to the health department.

**Impact**
Impacts the CSV Uploader Pilot

**To Reproduce**
1. Log into ReportStream as a Sender who's STLT has **NOT** been onboarded
2. Click on Upload
3. Select a CSV file that will return NO errors and will be accepted by ReportStream

**Expected behavior**
Consistent messaging when there are no recipients

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/946693af-3a2f-4052-888c-cc32cc40c7ad)

**Comment by bgantick** [comment]
Closing: this scenario wouldn't occur in prod - STLTs should be onboarded _before_ senders would try to send data
