### ISSUE TITLE
IDLE logout generates 404 error (staging)

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#3327]
**Describe the bug**
A clear and concise description of what feature is not working.

**Impact**
Only matters for staging? Will double check prod.

**To Reproduce**
1. Go to https://staging.reportstream.cdc.gov/daily-data
2. Log in
3. Wait for auto-logout to happen.
Result: 
<img src="https://user-images.githubusercontent.com/74203452/144919148-38105d83-86c4-444d-95da-4f670aa433c1.png" width=200px>

**Comment by bgantick** [comment]
Closing: this doesn't seem to be an issue anymore
