### ISSUE TITLE
OH - Need to Confirm if Test Results Are Being Transmitted and Received

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#3331]
A SimpleReport (SR) user email to let us know that the test results being submitted by her facility may not be getting to the state PHD and therefore not getting to the county PHD.

The SR user was told by the county PHD that they have not seen any test results from this facility for probably 2+ weeks even though they tend to have positive results.

Examples of Test Event IDs that may be in question:
- 4ce06311-3942-4128-88e1-674ae1fc47c1
- 5cfcf9f8-f12c-4cbd-a05b-74dfd8197e9b
- a108cdd5-a97b-4a16-b529-5910e260fd5a

Facility uses 2 different devices (BinaxNow and Accula) so does not appear to be device specific.

Can someone check to make sure the test results have successfully been transmitted to O PHD so we can advice next step for the user?  Thanks.

cc - @emmastephenson

**Comment by MikeC-A6** [comment]
@mlighdc 
4ce06311-3942-4128-88e1-674ae1fc47c1 - one of 397 records sent December 2, 2021, 8:15 PM
5cfcf9f8-f12c-4cbd-a05b-74dfd8197e9b -  one of 319 records sent November 1, 2021, 3:15 PM
a108cdd5-a97b-4a16-b529-5910e260fd5a - one of 410 records sent November 30, 2021, 8:16 PM

**Comment by mlighdc** [comment]
Thanks @MikeC-A6. I will reach out to the state PHD to confirm and see if there are anything we need to be aware of on our side. cc- @LGFranklin @emmastephenson

**Comment by mlighdc** [comment]
Sent an email to OH PHD on 12/7/21 to verify the messages are getting to their system. Waiting for confirmation.

**Comment by anshulkumar-usds** [comment]
Anshul will follow up with OH on next steps

**Comment by anshulkumar-usds** [comment]
Confirmed with OH - this issue is not longer present.
