### ISSUE TITLE
A1H - Setup New Feed for "T" and "D"

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#3338]
## Problem statement
All messages from A1H with processing_mode "T" or "D" need to be sent to CA's test environment not the ca-elr or ca-elr-secondary feeds.

## Acceptance criteria
- [x] All messages with processing_mode "T" or "D" must go to the new CA Test Feed which sends the results to the CA test environment, and be blocked from the ca-elr and ca-elr-secondary Feeds.

## To do
- [x] Add ca-test as a new feed for CA sending to their test environment.
- [x] Modify the existing Jurisdiction or Qualify Filters to exclude processing_mode "T" and "D" from ca-elr-secondary.

**Comment by brick-green-agile6** [comment]
Setting up CLIA for the CA test receiver as CDPH000087

**Comment by brick-green-agile6** [comment]
just pushed the settings to production. The only qualityFilter in place is: "doesNotMatch(processing_mode_code,P)". This will allow all messages to be delivered for California where the processing mode code does not equal "P". Additionally, i set the MSH-4.2 to default to CDPH000087. Last I set the transport to be sent to the test folder.
