### ISSUE TITLE
VT - MSH-3.1 namespace truncation failures

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3363]
## Problem statement

On 12/8, 11:27 AM ET, VT reported that:
"All 196 COVID test result ELR messages in the 11:17 file from SimpleReport/ReportSteam failed in our production environment due to the namespace in MSH-3.1 being too long (current value: CDC PRIME - Atlanta, Georgia (Dekalb))."

## What you need to know

The failures coincide with the code deployment that was completed on 12/8 at 10:17 AM ET. Several items in this deployment were intended to address truncation issues across RS. More than likely, the deployment cause this issue for VT.

## Acceptance criteria

- Determine root cause for VT
- Fix is implemented
- Corrected files are delivered to VT; first in test, and then in prod

## To do

- Determine root cause
- Deliver test message to VT's test directory and seek validation
- Deliver corrected files to VT's prod directory and get confirmation of delivery and acceptance

**Comment by anshulkumar-usds** [comment]
this is effecting a few more states: CA, NM, NJ and IL

**Comment by mlighdc** [comment]
@anshulkumar-usds I am in the RS support inbox and it looks like the automated confirmation from IL came at 5:17 pm Eastern today (for potential resends). Not sure if any other auto-confirmations came in today from IL. I didn't see any in the folder I set up for theses auto-generated IL messages as well as the trash folder.

**Comment by Adrian-Brewster** [comment]
Resubmitted file last Friday and waiting for feedback from VT

**Comment by anshulkumar-usds** [comment]
VT validated test file.
