### ISSUE TITLE
Spike—Plan high level eng architecture for sender settings (i.e. schemas, mappers, settings)

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#3364]
## Problem
Presently we have to create unique schemas per sender. This isn't scalable since it requires a lot of manual effort per sender. This was a problem on the receivers end and it was solved by creating settings—configurations that are easy to create and change and live in the database. This pattern should be followed on the sender side.

## Acceptance criteria
- Technical specs for how we will implement sender settings modeled after receiver settings
- Definition of sender unique sender types (probably csv and API to start)
- Suggestions for initial setting options we can start with that we know will be valuable based on what we already know

**Comment by sean-usds** [comment]
@RickHawesUSDS fyi, created this ticket to track progress on sender settings

**Comment by loripusey** [comment]
@sean-usds investigating if we still need this and its background
