### ISSUE TITLE
SPIKE -- How do we want to allow RS Admins to select a Sender for which to view their History

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3368]
## Problem Statement
We need admins to be able to select any sender in the org drop down.

## Acceptance Criteria
- Figure out what this looks like and how we would configure OKTA

**Comment by sean-usds** [comment]
Pretty sure we can use the same drop down as selecting receivers. Senders are showing up too: 

Will check with O&O that sender groups always begin with "DHSender" which is a core assumption in the frontend

![image.png](https://images.zenhubusercontent.com/61310371004bdd52b9b7d2c4/01ecc967-8d18-4ada-bbb1-03b2db5b49dd)

**Comment by kevinhaube** [comment]
@sean-usds We may want to consider sorting them if possible, or maybe prefixing them with "Sender:" or "Reciever:" so they appear grouped accordingly. Not sure if this component supports categorical lists or not
