### ISSUE TITLE
All internal page links throw a 404 error.

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3372]
**Describe the bug**
All internal page links throw a 404 error. Top-level navigation is unaffected as well as links that open a PDF or mailto. After opening a PDF, using the browser navigation also throws a 404.

**Impact**
Large impact, link navigation is basically broken.

**To Reproduce**
1. Go to https://reportstream.cdc.gov/
2. Click on any link that navigates to a different "page" (excluding ones that open a mailto or PDF and ones that open the state intake form and top-level navigation)
4. See 404 error (clicking browser back after getting a 404 also causes a 404)

**Expected behavior**
Linked page opens

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/4fb4d0e7-4f67-4824-9300-ba0de4126207)

**Comment by loripusey** [comment]
cc: @mlighdc

**Comment by TomNUSDS** [comment]
Build issue.
Fixed by https://github.com/CDCgov/prime-reportstream/pull/3377

@cwinters-usds Manually made a temporary fix on production to fix.

**Comment by mlighdc** [comment]
@TomNUSDS will there a more permanent fix or do you anticipate this happening every time we have a production deploy? Just want to make sure when we do demos :-)

**Comment by TomNUSDS** [comment]
@mlighdc Sorry for the slow reply. Stuck in meetings.

Yes. We have a temporary fix in place that should seamlessly be replaced with a more permanent fix (unless something goes wrong). So you should be good for demos.
