### ISSUE TITLE
IL - Issue with Timezone configurations 

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#3379]
**Describe the bug**
Illinois is receiving some data where the specimen collection date is set to the following day.  On December 8th, for example, Illinois DOH received messages where the specimen collection date was showing December 9th. This may have affected the whole batch, not just a single message. 

**Expected behavior**
There would be some sort of logic in place so that senders can not enter dates in the future. Configurations should be set to the proper timezone.

**Sample Messages**
 0201b425-8f16-49a4-b5e4-30bf219bc30b

**Comment by MikeC-A6** [comment]
269 records in the last 30 days, all SimpleReport where the Specimen Collection Date is > the Created At date.
![image.png](https://images.zenhubusercontent.com/600074c877558bc7db71dd9a/2dd5b7d0-0629-4f6a-a13b-f74cca4959b6)

**Comment by MikeC-A6** [comment]
236 of the 269 records occur when the created_at time of the record is 6pm or later.  3 records had a created_at time between 6AM and noon, so it doesn't look like this is isolated only to records sent late in the evening.

**Comment by MikeC-A6** [comment]
In the SimpleReport Demo Site, it appears to capture test date and time, but the specimen collection date field is only a date value in Metabase.  I'd like to compare the original incoming data for a record with what is in Metabase.  @jorg3lopez or @jbiskie  are you able to pull the original data sent in for Message ID: `94b920c3-d586-40c6-bb26-3a847d030e41` ?

**Comment by anshulkumar-usds** [comment]
Per @LGFranklin, ability to enter a future date is feature in SR by design. SR team is looking into the need for this, and how/if to roll it back.

**Comment by anshulkumar-usds** [comment]
12/20: Anshul shared internal findings with IL and awaiting feedback.

**Comment by anshulkumar-usds** [comment]
IL reported back on 1/3/22 that they do not have the ability to convert UTC to CST, or work with UTC in their surveillance systems.

**Comment by anshulkumar-usds** [comment]
Blocked by https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3243
