### ISSUE TITLE
PRIME CLI extracts LIVD Lookup table data from downloaded LOINC test code mapping table

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#3380]
As an administrator, I want a tool to extract the LOINC test code data from the downloaded file, so a tool can automatically update our lookup table data.  Note the tab to be extracted is called LOINC Mapping

Acceptance criteria:
1. The PRIME CLI extracts the necessary data from the downloaded and verified LOINC test code data.
2. The PRIME CLI cleans the extracted data as follows:
    - Removed the * from the equipment model
    - Note: take a look at the data and see if any other cleanup makes sense, but be careful about changing the data

**Comment by oslynn** [comment]
PRIME cli command line shall be as:
./prime livd-table-extract --input-file ./junk/LIVD-SARS-CoV-2-yyyy-MM-dd.xlsx --output-file ./metadata/tables/LIVD-SARS-CoV-2-yyyy-MM-dd.csv (default).  User can specify any other file as he/she wanted.
