### ISSUE TITLE
PRIME CLI can store the extracted LIVD lookup data to a new version of a lookup tables

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#3381]
As an administrator, I want a tool that will store the extracted data from the LOINC test codes to a lookup table in the database, so it can be used by the system.

Design considerations:
1. Is there any use to output the table for review?  It is kind of large.  Ask the ones that do this LIVD data updating.
2. Should be allow for importing from a CSV file?  I don't think this is useful.

Acceptance criteria:
1. The PRIME CLI tool stores the extracted LIVD table data to a new version of a lookup table.
2. The PRIME CLI tool is capable of storing the newly extracted LIVD table to a lookup table in any of the current environments (local, staging, etc.)

**Comment by oslynn** [comment]
I will add more meaningful error messages to the LivdTableDownload process.
