### ISSUE TITLE
PRIME CLI updates the lookup table(s) only if changed

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#3383]
As an administrator, I want the tool to update the lookup table(s) to only do so if the data has changed, so we do not have unnecessary revisions to the table.

Design considerations:
The database lookup tables currently do not have data to determine if a table has been updated.  Consider adding something or perhaps you can just compare tables.  Thinking that if you add metadata to the tables then perhaps it can be easier to debug, but unsure how useful that can be.  This check will have to be done to the specific environment we are storing the new data into, so if I am using the CLI in my local computer, but storing to production, then you must check the production system to see if it needs an update.

Acceptance criteria:
1. The PRIME CLI detects if the lookup table(s) data to be stored in an environment are identical to the already existing one and active.
2. The PRIME CLI does not allow the storing of identical data to an environment.  Unless, the -f command line option is set.  Or, there is no data in the csv file.
3. Do we need a way to bypass this check and force and upload?  Not sure for what
    (To bypass, force, and upload, user need to add the -f, --force to the command line)

**Comment by oslynn** [comment]
I am introducing the MD5 checksum of lookup tables and will corporate it into the lookup_table_verion.  It will be used to store the MD5 checksum of all lookup tables.  Therefore, we can use the field for the integrity check and update the table if needed.  @carlosfelix2, do you have any objections?
