### ISSUE TITLE
Combine duplicated steps into a single local action file

### ISSUE THREAD

**Issue by JosiahSiegel** [CDCgov/prime-reportstream#3386]
## Problem statement

Steps duplicated across multiple GitHub workflows are not only difficult to maintain, but they also present a security risk when some steps are not implemented appropriately (e.g. Azure Key Vault)

## What you need to know

- [Local actions](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-an-action-in-the-same-repository-as-the-workflow) will allow us to combine multiple steps into a single action file and share it across multiple workflows.

## Acceptance criteria

- [ ] Duplicated workflow steps no longer exist.

## To do

- [ ] Create local actions that can be shared across all workflows.

**Comment by cwinters-usds** [comment]
I think this will also close out https://github.com/cdcgov/prime-reportstream/issues/2011
