### ISSUE TITLE
Develop ReportStream System Architecture

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#3387]
- High-level system block diagram
- Components diagram (include Docker containers)
- Sequence diagram
- UML diagram

**Comment by brandonnava** [comment]
@oslynn Still needed? Does this meet your needs? https://lucid.app/lucidchart/16f174e9-0f04-4c48-8738-23000588b98f/edit?viewport_loc=-2105%2C-2539%2C3237%2C1680%2CSV4g-lPnP.PU&invitationId=inv_2451a1af-1096-4119-a964-baad0f91a74f

**Comment by oslynn** [comment]
@brandonnava , no I don't need it anymore.
