### ISSUE TITLE
Recuro: Staging Validation

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3391]
Validate staging data from sender and offer feedback on next steps

**Comment by anshulkumar-usds** [comment]
Adding @whytheplatypus since the sender submitted a FHIR formatted file

**Comment by anshulkumar-usds** [comment]
Per @whytheplatypus, we are not yet ready to ingest FHIR data. Hence, Anshul reached out to sender to resubmit HL7 or CSV data for validation.

Removing @whytheplatypus as an assignee. - since @jbiskie will own next steps.

**Comment by anshulkumar-usds** [comment]
Anshulm to check with sender on HL7 submit

**Comment by anshulkumar-usds** [comment]
No word from sender

**Comment by Adrian-Brewster** [comment]
@Adrian-Brewster to follow up
