### ISSUE TITLE
VT - Assigning Authority Field No Longer Populating

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#3393]
**Describe the bug**
Some messages are failing in our HL7 validation due to missing assigning authority for the Ordering Provider in ORC-12.9 and OBR-16.9. Per HL7 2.5.1 ELR Implementation Guide, when an ID is provided in ORC-12.1/OBR-16.1, ORC-12.9/OBR-16.9 and ORC-12.13/OBR-16.13 are required..

**Impact**
Messages are failing to send

**Expected behavior**
Per HL7 2.5.1 ELR Implementation Guide, when an ID is provided in ORC-12.1/OBR-16.1, ORC-12.9/OBR-16.9 and ORC-12.13/OBR-16.13 are required..

**Additional context**
May be related to the recent PR for the Provider ID field.

**Comment by mlighdc** [comment]
Responded to VT on 12/9/21 with an explanation on why the change was implement, what happened in the past, and what is happening as part of the deployment that happened on 12/8/21.

**Comment by mlighdc** [comment]
@jorg3lopez - I talked to VT and this is what they preferred:

- If NPI is valid, include the following (need all 3 fields)
    1. assigning authority for the Ordering Provider 
    2. ID
    3. ID type

- If NPI is not real, do not need to send NPI entered but need Ordering Provider name 

Additionally, they have requested to see if we can divert some messages to their secondary feed for testing. They would like one than one test message.

@anshulkumar-usds @MauriceReeves-usds

**Comment by jorg3lopez** [comment]
@mlighdc @anshulkumar-usds @MauriceReeves-usds I'm testing a live data file that has an invalid NPI. So far everything looks good, ORC-12-1 is left blank and ordering provider name is populated (ORC-12-2 and ORC-12-3). I will keep on testing the settings a few more times, I will have a file that covers everything by the end of the day.

**Comment by Adrian-Brewster** [comment]
File was sent last Friday. Waiting on feedback from Vermont.

**Comment by Adrian-Brewster** [comment]
Anshul will reach out to Vermont to follow up.

**Comment by anshulkumar-usds** [comment]
VT validated test file.
