### ISSUE TITLE
Github forms

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3395]
Check if github forms will work for us as a ticketing system

fyi - @Adrian-Brewster

**Comment by anshulkumar-usds** [comment]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

**Comment by Adrian-Brewster** [comment]
Form needs refinement. Team will meet this week to discuss next steps.

**Comment by anshulkumar-usds** [comment]
@Adrian-Brewster can you please partner with @hermanAlexCordero and work on a first draft of the form. Consider which questions, and in what orders, should STLTs and Senders complete when submitting a support ticket. Is there a way to auto-populate our team's label on the submission, and apply the support queue epic?

**Comment by Adrian-Brewster** [comment]
Name
Submitting Organization
Email
Issue Description
Expected Behavior
Date Issue Started
Submitter Severity with drop downs for High/Medium/Low

**Comment by hermanAlexCordero** [comment]
completed the changes in my own repository.  Working with Adrian to start migrating to RS repository

**Comment by anshulkumar-usds** [comment]
@hermanAlexCordero please prioritize this for the current sprint. We can start piloting the form with a couple of states starting next sprint.

**Comment by anshulkumar-usds** [comment]
Let's mark this closed for now. Seems like Clickup is a better option.
