### ISSUE TITLE
New Truncation Logic Truncates Incorrect Field

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#3411]
**Describe the bug**
After applying the settings in #3405 (https://github.com/CDCgov/prime-reportstream/pull/3405) we encountered an issue were instead of `OBX-23-1` was being truncated, `OBX-1` was truncated, which then caused parsing to fail for VT and IL.

This is a high-priority bug that we need addressed quickly.

**Impact**
Until we have this fixed we are not able to use the new truncation logic for custom fields.

**To Reproduce**
1. Update your local settings to truncate OBX-23-1
2. Run ReportStream locally and post a file to it
3. Note that with OBX-23-1 set, OBX-1 changes from `CWE` to `CW` 
4. Remove the OBX-23-1 truncate flag and post a new file
5. Note that OBX-1 is now `CWE` as expected.

FYSA - @RickHawesUSDS @brick-green-agile6 @jorg3lopez @Adrian-Brewster @anshulkumar-usds

**Comment by brick-green-agile6** [comment]
Correction - OBX-2 is was being truncated to CW (not OBX-1)

**Comment by MauriceReeves-usds** [comment]
@brick-green-agile6 @RickHawesUSDS I found the issue that is causing the inadvertent truncation. In this logic here:

```kotlin
            hl7Config?.truncateHDNamespaceIds == true && hl7Field in HD_FIELDS_LOCAL -> {
                getTruncationLimitWithEncoding(value, HD_TRUNCATION_LIMIT)
            }
            // For the fields listed here use the hl7 max length
            hl7Config?.truncateHl7Fields?.contains(hl7Field) == true -> {
                getHl7MaxLength(hl7Field, terser)
            }
```

In this piece of code: `hl7Config?.truncateHl7Fields?.contains(hl7Field)` `truncateHl7Fields` is a string, not a list, so when the serializer checks to see if the field needs to be truncated, `OBX-23-1` contains `OBX-2`, so it truncates that field as well. In addition, while in HL7 2.5.1 the OBX-2 field is indeed only supposed to be 2 chars long, the HHS requirements for COVID reporting ported HL7 2.8 ID values back into HL7 2.5.1

The fix here should be as simple as turning `hl7Config?.truncateHl7Fields` into a list and then change the `contains` call to look in that list.

fysa: @Adrian-Brewster @Adrian-Brewster @jorg3lopez
