### ISSUE TITLE
WA - Migrate off AS2 to REST-API

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3416]
WA notified ES that they are reviewing a web-based API for their HEI and are awaiting security approval internally in the next two months.

Question for USDS: Can we support WA moving off AS2, and on-to a REST-API? If so, need to determine project plans, timelines, etc.

This ticket is intended to start the conversation b/w RS and WA to determine next steps.

FYI - @RickHawesUSDS @MauriceReeves-usds

**Comment by sarahnw** [comment]
closing this for a new ticket
