### ISSUE TITLE
Build Data Insights with OTC

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3424]
ReportStream is growing: we have more states and more senders onboarded, and onboarding soon. ReportStream, beyond functioning just as a conduit of data, can deliver data insights to our partners and stakeholders. Given the current surveillance ecosystem, and growth in OTC testing, we can consider embedding data insights through dashboards to inform our stakeholders.

Planned steps:
1. Obtain access to HHS Protect to survey current state of data at the Federal level
2. Enhance sender-specific data elements and metadata to capture additional data points. Need to discuss with Mo, Jim, Rick
3. Determine MVP state and start drafting visualizations, dashboards
4. Gather feedback from RS, CDC stakeholder and iterate

fyi - @RickHawesUSDS @MauriceReeves-usds

**Comment by brandonnava** [comment]
@MauriceReeves-usds Was this ever taken on? Still something we want to consider?

**Comment by brandonnava** [comment]
Closing in favor of experience's effort on a data dashboard
FYI @chris-kuryak

**Comment by chris-kuryak** [comment]
For reference, our work is currently being tracked in #7005
