### ISSUE TITLE
Use the CMS Service to Retrieve Provider First and Last Names for a Needed NPI Number

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3425]
## Problem Statement
As an **Experity EMR platform user**, the platform does not force me to enter the Ordering Provider first and last names and I may enter incorrect values so I need the values populated for me so that I can report this required information to my PHD.

## Acceptance Criteria
We want to use the CMS service to get the First and Last names for a specified NPI number and cache this information in our system so that we don't have to call the CMS service for every result

**Comment by loripusey** [comment]
@ahay-agile6 I created this story for the CMS service work and linked it to the one you are currently working

**Comment by rhood23699** [comment]
@loripusey de-prioritized as of 12/27; not needed for standard CSV schema
