### ISSUE TITLE
PMG - API Staging Validation

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3427]
Validate staging data from PMG and build schema with RS

**Comment by anshulkumar-usds** [comment]
@jbiskie PMG is attempting to send data over staging but getting errors. Can you please confirm if the service is available.

**Comment by anshulkumar-usds** [comment]
Anshul working with NM on testing feedback.

**Comment by anshulkumar-usds** [comment]
Update as of 1/6: @jbiskie provided additional feedback to sender on submission warnings.

**Comment by anshulkumar-usds** [comment]
@jbiskie both NM and WA need to validate test results for PMG before we promote the sender to prod. So please let us know when the sender is ready for prod and we should coordinate with the states.

**Comment by jbiskie** [comment]
In process of getting test files to NM and WA

**Comment by anshulkumar-usds** [comment]
Checking with WA on secure email solution to deliver the PMG data.

**Comment by anshulkumar-usds** [comment]
WA does not need to validate. They are making PMG use SR. Still waiting on NM.

**Comment by anshulkumar-usds** [comment]
PMG looking into the three additional fields requested by NM

HL7 field   CSV Field 
MSH.4.1     performingFacilityName
ORC.23      performingFacilityStreet
OBX.24      orderingFacilityPhone

**Comment by anshulkumar-usds** [comment]
@jbiskie Can you please review the additional data PMG sent and share your feedback with the sender.

**Comment by anshulkumar-usds** [comment]
3/1: Blocked by https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3943
