### ISSUE TITLE
Some ValueSets Do Not Serialize Cleanly Into a Markdown Table

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#343]
When generating Markdown for valuesets, some do not serialize cleanly and break formatting. See an example below.

![Screen Shot 2021-01-19 at 2.00.07 PM.png](https://images.zenhubusercontent.com/5ff4880376fe251547594b05/30fa22b6-d102-4375-bce3-5b8afc836d6c)

When serializing properly, it should look like this instead:

![Screen Shot 2021-01-19 at 1.56.08 PM.png](https://images.zenhubusercontent.com/5ff4880376fe251547594b05/4139087d-8bc5-4622-9d21-7a25a41961c0)

**Comment by MauriceReeves-usds** [comment]
Acceptance Criteria:
- When we generate docs, the value sets appear as expected in the markdown

Notes:
We have integrated documentation generation logic into the application that can be run via the command line: `./prime generate-docs`. This creates all the markdown files based off [the schemas in our documentation folder](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/schema_documentation/covid-19.md), and it's executed on builds and PR creation. We have this so non-technical people are able to get more information about the schemas, expected values, etc. 

The documentation is currently pretty sparse, but it's a good first resource for folks.

**Comment by oslynn** [comment]
The reason why the ValueSets Do Not Serialize Cleanly Into a Markdown Table as stated above.  It is because of the common.valuesets hl70078 code: **">"** character represent **blockquote** control character of Markdown file format.  The solution is to use code: **"&#62"** instead.
