### ISSUE TITLE
Admin UI for Mo to make org settings changes

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#3433]
## Problem statement
Right now when Mo needs to update settings for an organization, he needs to manually do it via the command line.

## Design
- We need a basic wireframe

## Solution
Allow settings to be edited in the web app by admin:
- Create a "Settings" tab
- Show fields that Mo would like ability to edit in a form
- Show an "Update" button that is clickable when fields are edited
- Must do a diff to show what has changed before committing changes
- Commit the changes (server-side code is already available & does versioning)
- Show success/error message below button after it is clicked

## Notes
- Since this is an admin tool just for Mo, the design is not important. This just needs to be functional
- Server endpoints should be ready for this
- There should be server support for diffing, which is a nice to have feature
- If we just show the entire yml and make it editable, that would be an acceptable starting postion. Could use a tool like https://www.npmjs.com/package/react-ace
- USWDS form that could be good to use https://trussworks.github.io/react-uswds/?path=/story/components-form-templates--text-input-form but it can be up to the engineer
- As of now Mo is the only customer of this tool so we just need his review on any solution

**Comment by TomNUSDS** [comment]
Thoughts: should there be an email or maybe a slack channel message documenting whenever anything is changes? (Sending slack channel messages is pretty easy.)

**Comment by TomNUSDS** [comment]
Some todo items from talking to @mauricereeves (@sethdarragile6 feel free to edit this comment).
 - [ ] Add API parameter to _optionally_ check that the `priorrevision` version number matches. This handles the race condition where two people edit the same record. If the api PUT knows the revision being updated, then it can sanity check that nobody else has edited first. The failure case should probably include the latest revision meta (mod date, user who did the action, version number). [_This probably should be its own ticket number_]
 - [ ] Verify there's an API call to LIST the per-setting revision history (e.g. list of tombstoned rows) with meta data (date, who edited it, etc).
 - [ ] Verify there's an API call to GET a tombstoned record so it can be viewed for debugging issues.
 - [ ] Verify there's an API parameter to update the `is_active` column of a settings row.

**Comment by TomNUSDS** [comment]
I can do some mock-ups for the UI and tack them onto this ticket. 
 
 First question is where should this Admin navigation should go? 
 
 The topnav is getting pretty crowded.
 
![Current top nav](https://user-images.githubusercontent.com/74203452/147283942-50d32c97-34fd-4a93-96b4-22bf4ecd5cac.png)

We could put a small icon near the "Log Out" that's a link. Or we could even make the username a link if you're an admin. Less discoverable, but cause any other layout issues. I was going to look what SimpleReport does, but I don't have a login for them anymore. 

@drew-usds  Any strong opinions?

**Comment by TomNUSDS** [comment]
UI ideas:
 - Fetch all `type='ORGANIZATION'` including "values" json. This is the "top level" of the tree and can be type-filtered in an edit box. The typical json data in the `values` column is tiny and includes `stateCode`, `description` and `jurisdiction`

**Comment by TomNUSDS** [comment]
@sethdarragile6 
[Reference to the API](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/openapi.yml)

It seems like the top level api call we want to generate the whole list of possible settings is `components/schemas/SettingMetadata` (call to [api/settings/organizations](https://github.com/CDCgov/prime-reportstream/blob/4bb019fa882cc3dcc969f07ff8f5e79fd95738ef/prime-router/docs/openapi.yml#L267)) [which references this schema as a result](https://github.com/CDCgov/prime-reportstream/blob/4bb019fa882cc3dcc969f07ff8f5e79fd95738ef/prime-router/docs/openapi.yml#L780)?

But from the schema, there doesn't seem to be any db id column returned from the rest call. This may be ok if we can identify the setting we'll finally need by "combined key" (e.g. the unique id for the organization combined with a "type")

**Comment by drew-usds** [comment]
@TomNUSDS Totally agree on the nav, we've started mocking up a secondary nav to clear up the problems/crowding we're currently seeing. I'll work on some mockups and sync with y'all/copy them here.
