### ISSUE TITLE
Create Poll for Likelihood of Referral

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3436]
## Problem Statement
As the Experience Team, we would like to poll our current users so that we can find out the likelihood that they would recommend using ReportStream to their peers.

## Acceptance Criteria
- Create poll/survey with the following questions
    - See [research plan](https://docs.google.com/document/d/1bXJSgUBTEOzheQL0b8EyGB6jT7okiEiN/edit) for questions
- Get feedback from O&O team, Kevin T., and Rick Hawes

## Notes
- Poll will be sent in a separate ticket

**Comment by loripusey** [comment]
@victorialb-usds Can you provide some AC?
cc: @rachelhanster

**Comment by victorialb-usds** [comment]
Here is where the draft is: https://cdc-my.sharepoint.com/:w:/r/personal/tcq5_cdc_gov/_layouts/15/Doc.aspx?sourcedoc=%7BE26920D8-0B8A-493C-BBEA-D9F45278EE8D%7D&file=ReportStream_Likelihood%20to%20Refer%20Survey%201.13.22_VLB.docx&action=default&mobileredirect=true&cid=f7b96117-5e73-4e32-ac82-641a06f9a26e
will share with Anshul, Mo, Kevin and Rick H Wednesday 1/26 @rachelhanster

**Comment by victorialb-usds** [comment]
Adding information on touch points:
https://touchpoints.app.cloud.gov/touchpoints/17290e43/submit
there is a 3 questions CX survey on here FYI - we can also create our own via this platform.

**Comment by victorialb-usds** [comment]
Awaiting feedback on this estimated Wednesday 2/2 to get feedback.

**Comment by victorialb-usds** [comment]
Will add a ticket about looking into survey tools. It was not in the AC above it was a note.
