### ISSUE TITLE
CA - Centralized CLIA for ImageMover

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3437]
CA would like to be kept abreast of all new facilities being reported through ReportStream. While we can manage reporting on this effort for SimpleReport, we cannot guarantee that a sender will provide adequate notice to RS, and RS will be able to provide adequate notice to CA. Hence, this ticket is intended to create a centralized CLIA for all ImageMover facilities for CA.

1. Confirm with CA if this approach work for them
2. Determine the placeholder CLIA to be used
3. Make necessary steps in settings and configuration to manage the change

**Comment by brick-green-agile6** [comment]
From Ellaison:

Please configure what is needed on the ReportStream side to send everything under CDPH000077.  We’ll have original sending CLIA in OBX-23.1, so local health staff will be able to tell where the results came from or where testing occurred.  And we’ll need a resend of all the results from ImageMover going back to say Oct 1.  I don’t think the total number is very high and this will allow the earlier NAK’s to go through now that corrections have been added to the feed.  We’ll also need the OBR-25 changed from F to C to ensure duplicates for CLIAs that we didn’t have built earlier are not filtered out by CCRS. 
 
If possible, can we get a count of the number of messages this covers?  I am guessing it’s probably 300 or less.  And prior to the resend, can we ensure all the messages have LOINCs in OBR-4 and OBX-3.  I know this was a problem for some of them that didn’t cause a NAK, but is an issue in CalREDIE. 
 
Thank you,
Ellaison

**Comment by Adrian-Brewster** [comment]
centralized CLIA set. CDPH requested resubmissions that are over 30 days old.  @brick-green-agile6 @anshulkumar-usds may need to get data from ImageMover.

**Comment by brick-green-agile6** [comment]
Here is the list of Message IDs that need to be resent. It's essential that they send the test result status as "C". To do so they will use this field "test_result_status" and simply add C to all the results. @anshulkumar-usds Can you help coordinate this with ImageMover? 

**Message ID**
64ad12c3-102e-4dab-bb25-5b89b97dbb1b
496fd66a-b497-4084-9119-f453a119e9a4
f930adfd-bbdc-4ca6-a3a3-857c96aafbaa
48e8875a-ec11-4131-b379-03c43f7f3510
b9e9dd39-f285-4ca1-bfe5-6592dd374af2
2afa8553-5f04-46e3-ab5a-1c1b7dba32f0
600264ff-13db-4c58-959d-87f40262a4cf
040a61d5-217d-48e7-8fad-1710ea157518
9ab0d620-0164-4507-b11f-839385e31187
2acb2ed2-6b16-40e9-8447-5f28a2d8d07e
f3357852-759e-4204-aa19-c57220cfece7
0c4dfb69-82f4-43cc-a6e4-35b8bb836fce
af2f1724-1c7a-47a0-a2c6-2c10bcfd2715
f998628a-c8f7-46fd-b1a7-8ddab9c9b969
71cd0db7-34ae-4359-87bd-c8ff516b4a97
8254e837-18cf-4a59-982d-b9c58bc40e94
8e48e4dc-2aae-4efd-b63f-9cb1a6c75ee8
96c8504d-d42f-4676-80ac-0369071cf8f6
ddd5f11a-5819-4a60-8ec5-4e630719ee93
2735d7ec-915e-40e5-a1b4-2835d4c0465a
abd3b090-34d8-49ed-8a7b-68419931d2ac
9159318b-3ea0-480a-8c8f-9fa7af11b2a5
006f5b6b-1367-437d-a327-4f33bfb701df
bbd009b9-64fd-4b19-828b-b9ef12e4af15
509852bd-2fb7-4038-b763-263efce7da49
3308ca0d-c338-4984-8127-c9663815fe43
c2b7dd84-3fb9-4363-979d-bbcd9c2c9784
0f38dc02-c064-48c4-827f-7f5c3e753d48
6557a989-8308-44d5-8729-43399527af61
a15e9df5-9c46-4314-8288-18e5629492a7
a5c1792c-5322-4d72-8fff-80809ba6b5b7
dc2f325f-4e79-41ab-9b34-7e2c7873952c
959caf78-43b0-4f8e-a4de-ea2de1f13c49
db26b765-3343-4079-ad75-2a03477ebf10
e4be49fe-8bd8-4b75-a416-1632f0a37287
200cf5f1-f1d7-480d-95f0-1912fc442004
b606d5b0-31f5-48fb-9583-58e4d2165a5d
8e861e3b-6291-4ab0-aafe-000584cf6b9a
98bb43d7-b550-47ca-b1f0-d127d3b32499
33b3cfda-e4f0-4d9b-a5b5-396b5b60a734
980db6fd-adce-4a27-b9bc-24c3dc4bc6cb
4f29fdad-33e3-4c91-9f95-15346cec3c0d
40e5c973-0699-48d2-adc4-d6851b26f973
31f3707a-ace5-4e7b-b6c1-66b7cd128263
3fe9f923-120f-4329-8aa7-80ceccc2e6a0
e6ec6841-6bc6-45ee-ad02-007c944faca3
562e7f79-a36b-402b-89e1-27af02ca09bf
9e6412bd-b609-4851-bfe9-af9da3d36026
e8f9dc59-c4be-43e4-b3c2-0a090cd4d0b1
e04fa613-7f10-45b0-8543-b36b95575fb7
48c5fea8-b8cc-4d57-a38e-3bfdd0b16ad8
02824d5f-3676-4db5-94c3-316cfec450c6
29a3059c-6253-4b91-b44e-c05247456ba7
68452d9f-1d04-4be2-8261-d906b4033685
6b1878b7-1eba-4520-b5e0-ca9f172a179d
7b27ce52-04ee-40bf-bab8-9240fb29a151
3961ae53-db07-4b2a-a563-b6d3120fb0eb
a3318b83-b573-413e-9467-f44e70eaa7a5
4ac52230-eeb0-4125-8cbb-38a00acbbc58
612980b3-3d35-4f6c-aa60-3ca6f0c6449e
aa9f7465-d637-421d-a1e8-5e70c3130105
22d1964f-8fc4-47f8-a150-1b333250505a
e5039142-fd24-498d-a2d0-143ace3c29fe
b582f32b-2c34-4105-ad17-87bd3b56f807
ffd753fb-3dcb-4664-8841-d0fbd8d02076
d940e590-46e7-4e9a-ae28-effd9e02eb5f
d0b2827d-a963-4f24-b2e9-e7ffa5150e46
e7d532af-c6cb-4e93-9696-924db4d20b46
29a769ae-0bb2-4019-b2df-e7b5c23fdfa2
c4593652-8777-44e9-ba65-3b292fe5e319
6616c46d-7f6b-45ae-99a8-12196711422e
3fab9c93-cdf8-441a-9fe2-26059f014f04
36d3cd1e-4176-49c8-b64b-26d664ba07a9
09457a86-9f39-4862-899d-0ac0bfbd17ee
7c05969f-f60b-4ffd-897f-eeb59e5bc59c
d92f8112-e2a3-4bdb-8d5f-10e1643e9632
a5f22510-4c13-484d-9503-6f4814a750c1
2a3eb33a-2e2c-4a28-803e-ca330bed7543
c8fefa4d-73d3-4208-98b6-9a26ed947eb2
894a609c-7c20-437b-877c-6de0ce38d6a1
88b1d186-e442-4cd1-8899-b0a892250cc2
e4290c6f-4c89-46c4-8a54-82a06a4fe309
211edd78-a866-4388-b243-c92c262e5e58
b11a5e57-7ebc-4d50-8552-8541742d680e
01a9eca9-ccf2-44a8-b937-899c800f14a1
378dccff-5855-4fa0-9150-d6e5e4cf717c
f9ce690e-1817-4ec2-9ad6-68e91c332a01
4652ab21-3541-44f3-af1f-18733b0cbe53
8b7ca7bb-1d89-46f7-a45c-a1b4be8d5c48
bb660e87-13df-4146-8d82-f427113ee015
7fd6d226-4e98-49e3-b234-786f31ee3ebf
50303976-9dd1-4d99-8b57-f31099fb2da2
f73c5926-986f-4c5b-a086-c3479857925e
295a41b4-43fc-4540-9295-35088ef5e713
b332fb90-41f8-4cb3-9a7d-5896ed63316c
f09d424d-014a-4c7e-8e28-eef39c27277d
482c8cf7-61d3-44ab-a08b-c36eb3128db8
b13545bf-27c0-43fa-8024-d98af78709b6
4a04fc2a-b51a-4851-8e92-891e544c7668
e402ee19-2303-4911-aced-cf11d1df86d9
31ee5bfa-ae79-447c-b204-26edd827d522
d8e9e38f-1a4a-4557-8b12-8da3034ceddb
2a65824d-6bfe-4062-841e-c3075aa7bab7
728b3540-df33-4b68-926f-6a5399d9bfaf
7ad95b2a-57cc-4574-b07f-cb293640c772
f1286b9f-9743-4eae-b8b3-5faab394b72a
60fd49de-628d-4862-8810-bb2413a2ebcf
87cf4fa5-687e-44f6-8167-7fa7943afd33
293862c3-eb8c-40d3-ba27-e731dac7b7f0
dc0d4cc1-893c-44f6-adc8-7b4e0f24faed
9da9265e-906b-4678-a1e4-38e9beb5019f
ac5bee81-56f0-4f4b-8b24-b0b360d8ec20
65d59905-c235-4e5e-9545-2fbef133b37c
aff89715-7cec-47f4-a326-131d9055c00f
665b3f81-a451-499b-8284-5310d874226e
59671e48-661b-442e-a65e-82f4fd7f2bd6
8b5cf110-48f9-4b5e-b05c-3168f4c9562e
5aad651e-47d2-4477-8e5d-03eee4a1fdda
983f4b61-54d0-4cbe-a44f-4c8d459b84b7
d521f28d-776e-47f9-81c2-a44f4e0d3d2f
63c44988-3392-4353-8658-48de79ef4928
efc76121-712b-444d-83fe-7f4c3e5bb933
1e489635-0f11-457c-9d09-e60ba9bc07c4
16146cbd-d296-4c7d-b782-d07745c0f672
6acdbba7-75f4-48d2-acdc-de78117fc4af
ebfe3557-8430-47f6-8977-30bc76fa0ac5
1304bc84-7f6c-4d95-8771-a7fe810bc6e8
78db0697-60c1-4a34-ae4b-3315a0faf3a3
0abddcdc-af35-4d66-becc-fe2092a9cb72
4fd895cc-e856-4990-ba8a-f7e06339866d
b5e6dc88-c7e1-4a5e-ae26-f51f4f675e71
26479988-15c4-4bb1-afa1-80864ce93a23
8bb63150-5fc9-4537-bff6-8986e35306ba
5b6ca89b-389e-407f-8841-0d09d4c9a841
66c06305-f0c6-4521-ac8d-5afd893a31c0
8a88d83b-4b49-4251-926b-9013c51636c6
a050a3e2-ee2d-4252-a3ed-0a49d8655203
91a635fd-9c06-4257-8e70-8981491da4d2
0d325044-1a64-401a-a1f8-17e266682a06
afe7675a-5239-4265-b8a8-a5910b77051e
a0478dc2-a59e-46b1-8d0e-0cc6992d2420

**Comment by anshulkumar-usds** [comment]
1/23: Shared message ids with IM again. Awaiting sender resubmissions

**Comment by anshulkumar-usds** [comment]
1/25: ImageMover completed the resubmissions.
Accession:
64ad12c3-102e-4dab-bb25-5b89b97dbb1b

Response:
cf0f6b5a-a5d8-4ae6-917e-e012e042c694

@brick-green-agile6 please review.

**Comment by brick-green-agile6** [comment]
I don't see the new result in metadata yet. The only result I see with that accession\message id is the original result from november.

**Comment by brick-green-agile6** [comment]
we have a problem - the data looks for from imageMover. But the imagemover schema needs to be updated. Currently it is defaulting the test result status to "F" and overwriting the "C" value that IM is sending.

**Comment by Adrian-Brewster** [comment]
Should deploy tomorrow if blocking ticket is resolved. Imagemover will need to resend affected files.

**Comment by brick-green-agile6** [comment]
@anshulkumar-usds The fix was deployed on friday. ImageMover does not need to send the field test_result_status in their files. They only need to fill the correctedTestID field with the testID of the previous message. Let me know if i should reach out to IM on this.

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 I contacted IM with your instructions. Thanks,

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 sender made a few submissions. Please review and confirm if the resubmissions are good.

**Comment by brick-green-agile6** [comment]
Checked these results and they look good. IM can send the reset along.

**Comment by anshulkumar-usds** [comment]
3/1: @brick-green-agile6 IM completed all remaining resubmissions.

**Comment by brick-green-agile6** [comment]
Sent some examples to Ellaison for confirmation

**Comment by anshulkumar-usds** [comment]
3/1: CA confirmed receipt and validated records. Closing.
