### ISSUE TITLE
CA - MSH-3.1 Truncation Resubmission

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3438]
Due to the recent bug with MSH-3.1 truncation logic, outbound messages from ReportStream (including the data for A1Health >> Prod) have been failing.

@brick-green-agile6 has made settings updates to address this issues CA. We need to resubmit failed messages from 12/8 until when the fix was deployed.

fyi - @MauriceReeves-usds @rhood23699

**Comment by Adrian-Brewster** [comment]
Waiting on confirmation from CA

**Comment by Adrian-Brewster** [comment]
Still waiting on feedback. Will follow up during touchpoint this Thursday.

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6  did CA provide an update yesterday? Any steps needed from RS?

**Comment by anshulkumar-usds** [comment]
Anshul to fu with CA and determine next steps.

**Comment by anshulkumar-usds** [comment]
Anshul followed up with CA on 1/21 to confirm resolution of issue. Awaiting feedback from CA.

**Comment by anshulkumar-usds** [comment]
Accessions for MSH-3.1 resends shared with CA on 1/21
•	b207a398-947b-42bd-9fe6-0be815b93a45
•	f0e7964d-9cfc-447b-9269-a0b14b4be3cb
•	e43a5189-019a-4f5e-9ac7-afa8973c6630
•	0b5273b4-84af-4470-bc0a-ce8fb73eea2f
•	89279a33-6394-450e-a070-598561860e2d
•	87caacf6-a18d-43dc-9c7e-59e6b9cafa2e

**Comment by brick-green-agile6** [comment]
Provided Ellaison with the date of transfer for the results
