### ISSUE TITLE
View STLTs that are Live on ReportStream

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3446]
## Problem Statement
As the ReportStream team, we would like to show on a map all of the STLTs that are live on ReportStream so that we can generate interest in prospective users who come to see what ReportStream is about.

## Acceptance Criteria
Similar to how we display a list and map of all of the states that are live on ReportStream on a public-facing page, we would like to also have a map that shows a list and map of all of the STLTs that are live on ReportStream.

## Pages Affected?
https://reportstream.cdc.gov/
https://reportstream.cdc.gov/how-it-works/where-were-live

**Comment by chris-kuryak** [comment]
Too vague. Already accomplished some of it. Closing by committee decision. Will be re-assessed in future website improvement efforts.
@drew-usds @fmccaf1 @HeatherRienks @lizzieamanning
