### ISSUE TITLE
DESIGN -- Design How to Display STLTS using ReportStream on Public-Facing Pages

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3448]
## Problem Statement
As ReportStream Product, we need to show which STLTs are using ReportStream so that we communicate the growth of our application to our current and prospective users and other stakeholders.

## Design
Do we need a map? What can we design that makes sense?

## Acceptance Criteria
Similar to how we communicate which states are using ReportStream on our public-facing pages, design how we would like to also have a representation of which STLTs are using ReportStream

**Comment by chris-kuryak** [comment]
Too vague. Already accomplished some of it. Closing by committee decision. Will be re-assessed in future website improvement efforts.
@drew-usds @fmccaf1 @HeatherRienks @lizzieamanning
