### ISSUE TITLE
Sprint X - Update Live STLTs on Public-Facing Pages

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3449]
## Problem Statement
As ReportStream Product, we need to keep our list of live STLTs up-to-date so that we communicate the state of our application to our current and prospective users and other stakeholders.

## Acceptance Criteria
- Update the list of live STLTs

## To Do
- [ ]

**Comment by chris-kuryak** [comment]
Too vague. Already accomplished some of it. Closing by committee decision. Will be re-assessed in future website improvement efforts.
@drew-usds @fmccaf1 @HeatherRienks @lizzieamanning
