### ISSUE TITLE
Reach out to California for Sender Referrals 

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3454]
## Problem Statement
As the Experience Team, we need to reach out to PHDs to get referrals for COVID reporting entities.

## Acceptance Criteria
- Schedule times to speak with PHDs
- Speak with PHDs
- Compile referral list and any notes

## Responsibilities & Questions
- Determine who is responsible for engaging with referrals (i.e. prospective Senders)
    - Ming will send an email saying we are preparing an email for them to send to prospects
    - TBD
- Determine who is responsible for onboarding and getting to production w/ public health department + prospective sender
    - O&O team (Rick Hood w/ a backup person)
    - SLA: respond to questions w/i 1 business day
- How much support are we willing to provide to Senders?
    - We will do NO manual cleaning work for them
    - We will do NO deployments for them (i.e. custom schema & data cleansing)
    - Answer questions about complying or the onboarding process via email or phone (exceptions on a case-by-case basis)

**Comment by victorialb-usds** [comment]
We have heard the start to some of the answers in the responsibilities and Questions in the Discovery Calls, I can add these to the future calls too not as a way of enlisting but important to know who is doing what.

**Comment by victorialb-usds** [comment]
Ming sent an email requesting referrals in advance of the CA sync on 12/23 and primed Vanessa to bring a list to call on 12/28. The two previously suggested sites include Martinez and a VA site. Ming has followed up to these.

**Comment by loripusey** [comment]
Y: 
- CSV syncs; icebox review; SOS; meet with Chris over AAI
T: 
- Data Cleansing; review research mtg notes/video; AAI tutorials
B: 
- None

**Comment by victorialb-usds** [comment]
Vanessa sent 2 potential next pilot sender referrals @rachelhanster 
(1) Naval Health Clinic Lemoore Michell Neuroth michelle.r.neuroth.mil@mail.mil

(2) Contacts for Source BioScience:
Andrew Bronkema Andrew.Bronkema@sourcebioscience.com; 
Haleh Farzanmehr Haleh.Farzanmehr@sourcebioscience.com; 
richard.chaplin@sourcebioscience.com

Source

**Comment by victorialb-usds** [comment]
@victorialb-usds will reach out to these senders to do discovery calls as AH1 wraps up pilot

**Comment by victorialb-usds** [comment]
- Lori and VLB meeting today to discuss sender f/u with Lemoore
- VLB send email to bioscience to set up discovery call.
