### ISSUE TITLE
Create a Welcome Email  

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3456]
## Problem Statement
As the Experience Team, we need a Welcome Email template that PHDs can send to COVID-19 reporting entities they're referring to ReportStream.

This will be the first email we have PHDs send to find Senders who may be interested in getting onboarded.

## Acceptance Criteria
Email copy + content that includes the following: 
   - Info on ReportStream (what it is and is not)
   - Info on the CSV Uploader (what it is, why it's used vs. another method, demo link?)
   - Link to Schema guide/documentation (on GitHub)
   - Link and invite to agree to the CDC TOS
   - What support we will provide (answer questions w/i 1 business day)
   - We will not provide any manual data cleaning for you 
   - List of what data processing ReportStream does provide
   - Caveat about PHD quality filters (data that does not pass the PHD quality standards will not be accepted by the PHD)
   - List of PHDs currently connected to ReportStream 
        - Caveat - some state PHDs will forward test results for out-of-state patients to those states, so if RS is not connected to those other, states the data **may** eventually get to those states anyway
        - ReportStream will share data for out-of-state patients with those state PHDs if they are connected

**Comment by BerniXiongA6** [comment]
12.21.2021 This story wasn't pointed yet and sprint ends today. I can start working on this issue, but we'll need to point it to determine when it can be delivered. cc: @rachelhanster @loripusey

**Comment by loripusey** [comment]
We can look at today in planning

**Comment by loripusey** [comment]
Setting up meeting for Wed after x-mas to show draft to LADOH

**Comment by BerniXiongA6** [comment]
12.28.2021 Current DRAFT of Welcome email instructions for PHD to send to prospective users of RS. Still working on other dependencies to finish hyperlinking resources within the file. Will return to complete pending items by EOD today. (Saved as PDF in order to upload here on ZH).[https://app.zenhub.com/files/304423150/b0cf7568-84f5-4aa2-9aac-00dc33fef87f/download](https://app.zenhub.com/files/304423150/b0cf7568-84f5-4aa2-9aac-00dc33fef87f/download)

**Comment by BerniXiongA6** [comment]
12.28.2021 New DRAFT (will review/QA with @drew-usds in the AM 12/29). 

"How to Refer Users to ReportStream" [https://app.zenhub.com/files/304423150/f601a542-e1cf-4fdb-9327-4e7c34355795/download](https://app.zenhub.com/files/304423150/f601a542-e1cf-4fdb-9327-4e7c34355795/download)

and

"How to Register for a Free ReportStream User Account" [https://app.zenhub.com/files/304423150/06da29a8-dc2e-461e-b1d5-f0ee6cb4cf4b/download](https://app.zenhub.com/files/304423150/06da29a8-dc2e-461e-b1d5-f0ee6cb4cf4b/download)

**Comment by loripusey** [comment]
@BerniXiongA6 welcome email has "Centers for Disease and Control", should be "Centers for Disease Control and Prevention"

**Comment by BerniXiongA6** [comment]
Thanks @loripusey it's now corrected on the DRAFT

**Comment by loripusey** [comment]
@BerniXiongA6 can you provide a link to the current version of the welcome email?

**Comment by BerniXiongA6** [comment]
[Link](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/ReportStream%20CSV%20Uploader%20Guides/DRAFT%20-%20How%20to%20Refer%20Users%20to%20ReportStream%20v20211229.docx?d=w13a16c62f120488986d6cbd5a0cb7928&csf=1&web=1&e=D9tWyd) to How to Refer Users to ReportStream on Sharepoint (source of truth)

**Comment by BerniXiongA6** [comment]
1.10.2022 Final [Doc](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/ReportStream%20CSV%20Uploader%20Guides/FOR%20PILOT%20-%20How%20to%20Refer%20Users%20to%20ReportStream%20v20220110.docx?d=w4452d9e0f8e14dfab25583d1c8706c79&csf=1&web=1&e=fFp4oe) and [PDF](https://cdc.sharepoint.com/:b:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/ReportStream%20CSV%20Uploader%20Guides/FOR%20PILOT%20-%20How%20to%20Refer%20Users%20to%20ReportStream%20v20220110.pdf?csf=1&web=1&e=J1nfxm) shared in Sharepoint and with @loripusey (who will email LADOH today)
