### ISSUE TITLE
Create Format for User-Facing Standard Schema Instructions

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3461]
## Problem Statement
As a Sender, I need to understand how to comply with the ReportStream standard schema so that I begin to use the CSV Uploader. NOTE: this info will be provided in the welcome email as a link to where it lives in GitHub.

## Acceptance Criteria
- Required: Create Github markdown for the content (markdown file preferably, but if run into any issues, can be PDF for testing purposes)
    - We will not have a file of the user guide to download, only markdown
- Required: link to example Excel file
- Optional: link to demo video of ReportStream & CSV Uploader? (STRETCH GOAL)
- @drew-usds to help find a spot for this in the repo (something like `/documentation`?)

## Considerations
- Perhaps later we will do a Website page

**Comment by BerniXiongA6** [comment]
12.23.2021 In Design Sync with @drew-usds , we decided the Guidance content can be shared alternatively as a PDF if we can't get GitHub markdown page ready in time for LA call. If so, we'll make sure to include language in the PDF that content is still being iterated / not published for all PHDs.

**Comment by BerniXiongA6** [comment]
12.28.2021 Update: Finishing up DOC versions (and PDFs) of instructional guides for Issues 3569 and 3456 by EOD today. Will work with @drew-usds on Wed AM (12/29) to determine spot for turning these into markdown files in GitHub.

**Comment by BerniXiongA6** [comment]
1.7.2022 RS website has the following updates being deployed today:

Overview has been added to "How it works":

For PHDS

For Senders

Menu item added for Getting Started

Senders and Receivers have their own pages

How to register for RS added to Sender page

CSV Uploader guide added to Sender page

Resources for senders added to Sender page as hyperlinks

[URL to be added when it's ready today for QA/Review]

**Comment by BerniXiongA6** [comment]
1.10.2022 Content is now live on RS website - here are the URLs:
Main section: https://reportstream.cdc.gov/getting-started/testing-facilities/
Account registration guide: https://reportstream.cdc.gov/getting-started/testing-facilities/account-registration-guide
CSV upload guide: https://reportstream.cdc.gov/getting-started/testing-facilities/csv-upload-guide
CSV schema documentation: https://reportstream.cdc.gov/getting-started/testing-facilities/csv-schema

**Comment by drew-usds** [comment]
Closing! Published on 1/10.
