### ISSUE TITLE
Synthesize Likelihood of Referral survey results and interviews

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3485]
## Problem Statement
As the Experience Team, we want to use data from survey and interviews to address known issues, reiterate available product features (customer success), identify users who might want to be active promoters and beta testers.

## Acceptance Criteria
- [x] Create dashboard in survey monkey on dashboard using survey results (export data so we all can see it without Survey Monkey access)
- [x] Create artifact that synthesize survey data 
- [x] Share roadmap inputs with product managers (are there things we learned from the survey that relate to items on the roadmap?)
- [x] Share known issues (customer support topics that need follow up) with Ops team
- [x] ~~From the survey results, create list of organizations that might be future active promoters and beta testers (beta tester = early adopter of a new feature. active promoter = partner with cdc/reportstream on case studies, quotes, reference to prospects)~~ Captured in other ticket, #5211

## To do

- [x] Create mural/doc/etc to synthesize results
- [x] Link to the above item in research folder w/raw notes/etc
- [x] Make related ticket for synthesis of interviews after they are completed.

**Comment by victorialb-usds** [comment]
[ ] VLB created dashboard on survey monkey for when survey closes - this will provide summaries of answers to each question

**Comment by rachelhanster** [comment]
I updated notes under acceptance criteria, which will need to be reviewed with the team.

**Comment by drew-usds** [comment]
@a-chappelear Spreadsheet of full Surveymonkey export from Victoria:

https://cdc.sharepoint.com/:x:/t/USDSatCDC/EQf3-S3AXytLt7RR1cPR79MBM_KpCZfy2hNGdpSHuiHvDQ?e=tjwAOU

**Comment by a-chappelear** [comment]
Mural synthesis link - once our interviews are done! 
https://app.mural.co/invitation/mural/primedatainput6410/1652730693329?sender=uc91f7c72c0f84196a8818813&key=e9793b26-0a99-4c34-b1af-4b47c8921663

**Comment by RakshindaAslam** [comment]
Moving to Next Items to wait for interviews on June 6th. Will be pulled in the sprint starting June 8th.

**Comment by BerniXiongA6** [comment]
6/7/2022: @a-chappelear and BX will pair on this now that all CX follow up interviews are completed. More updates to come on Friday 6.9/2022.
