### ISSUE TITLE
Internal Admin Manages Lookups (i.e. CRUD)

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3489]
## Problem Statement
Currently, values & values sets are maintained in files and must be checked in by an engineer (some work has been done to move these to the DB?). The O&O team needs a way to easily create, modify, diff, and version these values so that we can speed up the onboarding process.

## Things to consider (from the prioritization exercise)
- Diff is crucial (in case of mistake)
- Roll back/forward to a different version?
- View different versions?

**Comment by rachelhanster** [comment]
Per product sync meeting on March 24, 2022, this epic will now be owned by the Operations team with Experience team providing design expertise when needed. cc @anshulkumar-usds @sarahnw @Adrian-Brewster @drew-usds @bgantick @BerniXiongA6 @HeatherRienks

**Comment by HeatherRienks** [comment]
testing email notifications - @HeatherRienks

**Comment by HeatherRienks** [comment]
@HeatherRienks - confirming notifications work

**Comment by rachelhanster** [comment]
@HeatherRienks writing this comment as a test, per your request

**Comment by rachelhanster** [comment]
Experience team to continue with this internal tool. @bgantick @HeatherRienks

**Comment by RakshindaAslam** [comment]
@rachelhanster - This epic has moved between O&O and Experience team a few times with no tickets. Who owns it now?
