### ISSUE TITLE
Clean CSV Data: Allow Sender Automation Lookups to do "contains" matching [SPIKE]

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#3496]
## Problem statement

In [this story](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/2242), we introduced the ability to map sender automation valuesets from a database lookup table, sender_valuesets - an improvement on the old valueset lookup functionality from a maintenance perspective. However, one of the intents of the story was to allow a "contains" match on lookup values within the database. So for example we would like a value like "This person is not pregnant" to match to a lookup value column of "not pregnant", producing some standard output such as "N" (or a SNOMED code). 

At the face of it, it's not difficult to extend an existing lookup function in code to perform this match. The real work is in making this solution "false positive proof", i.e. _not_ matching to the wrong value. For example, many lookup values are single character, like 'Y' for pregnant (maps to '77386006'), 'M' for gender. For patient ethnicity, 'H' maps to 'H' (for Hispanic) and 'Non Hispanic' maps to an 'N' (for, you guessed it, Non Hispanic)- but since '**H**' _also_ would map to 'Non **H**ispanic', how do automatically decide which value it should map to?

## What you need to know

Spawning story: https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/2242

## Acceptance criteria

This story is a spike to determine either
1. To decide NOT to do this at all, or
2. Design a way to eliminate or mitigate the risk of false positives, in a way that is not overly complicated in code OR for the onboarding team to maintain

**Comment by loripusey** [comment]
de-prioritized as of 12/27; not needed for standard CSV schema
