### ISSUE TITLE
Paginate Submission History

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#3497]
## Problem Statement
As a Prime Admin, I need to be able view the submission history for each organization so that I can help them with submission issues and/or questions.

## Design
https://www.figma.com/proto/VrSkTA87t8PPeXPugQ0i8O/ReportStream?page-id=1868%3A15072&node-id=1868%3A15073&viewport=241%2C48%2C0.84&scaling=min-zoom&starting-point-node-id=1868%3A15591

## Acceptance Criteria
- Given I
    - Am logged into ReportStream as a Prime Admin
- When I
   - Log into ReportStream
   - Choose to view Submission History 
   - Choose a Sender for whose submissions to view
- Then I
   - Can view all of the Sender's submissions listed in descending order by date/time submitted
    - **Can page through the results (previous/next)**

**Comment by TomNUSDS** [comment]
See the "Paginated data" section of https://resthooks.io/docs/api/useresource

**Comment by TomNUSDS** [comment]
Also, some of the work happening right now with #3433 on [this branch](https://github.com/CDCgov/prime-reportstream/pull/3624/files) that does some advanced resthook stuff that might be useful.

**Comment by loripusey** [comment]
FYI: can't do proper pagination given the way the API was designed
