### ISSUE TITLE
Perform Likelihood of Referral Poll Follow-up Interviews

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3499]
## Problem Statement
As the Experience Team, we would like to interview current users so that we can find out the likelihood that they would recommend using ReportStream to their peers.

## What You Should Know

- [x] For more context, review acceptance criteria for [synthesizing data from survey and interviews 3485](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3485)

- [x] During interviews, some questions to consider asking:

- might you be interested in partnering with us on a case study so other public health authorities could benefit from your knowledge?

- might you be interested in working with us on some content about your experience so others can benefit from this cdc product to share data w/ public health authorities?

- might you be interested in being a beta tester for new features or new products?

## Acceptance Criteria
- [x] Look at Likelihood to Refer Survey for insights
- [x] Have we had previous contact/meetings/etc with the participant?
- [x] Look into the the population/organization/individual we're meeting with
- [x] Desk research on the participant for any relevant information. Can their website/documentation/etc inform interview questions?
- [x] Incorporate into facilitation guide and tailor for user

## To Do
- [x] Send out email to prospective participants (IN PROGRESS: [see outreach tracker ](https://cdc.sharepoint.com/:x:/t/USDSatCDC/EdQTAaw3KlNDl6qGFrWtpU0BRbCrqUaXBobIOzDqMEJeEg?e=NGA5bA)for current updates)
- [x] Schedule meetings (IN PROGRESS: [see outreach tracker](https://cdc.sharepoint.com/:x:/t/USDSatCDC/EdQTAaw3KlNDl6qGFrWtpU0BRbCrqUaXBobIOzDqMEJeEg?e=NGA5bA) for current updates)
- [x] Perform follow-up interviews with detractors (0-6 NPS rating) & promoters (9-10 NPS rating) (IN PROGRESS: [see outreach tracker ](https://cdc.sharepoint.com/:x:/t/USDSatCDC/EdQTAaw3KlNDl6qGFrWtpU0BRbCrqUaXBobIOzDqMEJeEg?e=NGA5bA)for current updates)

**Comment by RakshindaAslam** [comment]
@victorialb-usds @BerniXiongA6 @a-chappelear - Is this ticket still needed or was it covered in the post pilot interviews?
@rachelhanster

**Comment by BerniXiongA6** [comment]
@RakshindaAslam Please keep this ticket open, this is the task to actually conduct the follow-up interviews (which I'm trying to complete those next week). Thanks for checking into this! cc: @a-chappelear

**Comment by victorialb-usds** [comment]
These are different interviews @RakshindaAslam

**Comment by BerniXiongA6** [comment]
Updates 5/6/2022: I'm planning to send out the email "asks" to the promoters and detractors identified on Monday 5/9 to conduct the interviews between 5/10 through 5/12. [Refer to Issue # 5211 for those details](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5211).

**Comment by RakshindaAslam** [comment]
@BerniXiongA6  - do we know how many and which API senders on this list?

**Comment by BerniXiongA6** [comment]
HI @RakshindaAslam Of all promoters and detractors identified, only 1 is an API user: Primary Health

**Comment by BerniXiongA6** [comment]
Updates on 5/11/2022: Working on sending out recruitment emails today and tomorrow to conduct follow up interviews this and next week with promoters and detractors. [See outreach tracker](https://cdc.sharepoint.com/:x:/t/USDSatCDC/EdQTAaw3KlNDl6qGFrWtpU0BRbCrqUaXBobIOzDqMEJeEg?e=NGA5bA) for In Progress updates.

**Comment by BerniXiongA6** [comment]
Updates on 5/12/2022: For @Adrian-Brewster - [here's the letter I wrote for you](https://cdc.sharepoint.com/:w:/t/USDSatCDC/EYpumi0W_SVIltHrsY_HYnwBDAP1q-y5UnWgN8B6AqclHg?e=EcBh7a) that you can adapt and make your own when reaching out to WA DOH - Thanks!

**Comment by BerniXiongA6** [comment]
Updates on 5/16/2022: Completed interview with North Dakota this morning ([see recording and transcript here](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Design%20and%20Research/RS%20CX%20Survey_Likelihood%20to%20Refer%20Research%20January%202022/Follow%20up%20interviews%20for%20CX%20Survey/Interview%20Recordings%20and%20Transcripts/North%20Dakota%20DOH?csf=1&web=1&e=U5GaGF)). BX to follow up via email to North Dakota on Tuesday 5/17/2022 with action items promised, as mentioned in transcript and notes.

**Comment by BerniXiongA6** [comment]
Updates on 5/17/2022: Completed interview with Alaska yesterday ([see recording and transcript here](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Design%20and%20Research/RS%20CX%20Survey_Likelihood%20to%20Refer%20Research%20January%202022/Follow%20up%20interviews%20for%20CX%20Survey/Interview%20Recordings%20and%20Transcripts/Alaska%20DOH?csf=1&web=1&e=5EtATI)). BX to follow up via email to Alaska with action items promised, as mentioned in transcript and [facilitation notes](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Design%20and%20Research/RS%20CX%20Survey_Likelihood%20to%20Refer%20Research%20January%202022/Follow%20up%20interviews%20for%20CX%20Survey/Facilitation%20Guides/For%20Alaska%20-%20Facilitation%20Guide%20for%20Follow%20up%20Calls%20to%20CX%20survey%202022.docx?d=w6f7a2b7986d04c648cb43ca22c3cac5f&csf=1&web=1&e=LOEkP4).

**Comment by BerniXiongA6** [comment]
Updates on 5/19/2022: Followed up with North Dakota today ([see outreach tracker for updates](https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BAC0113D4-2A37-4353-97AA-8616B5ADA54D%7D&file=Experience%20Team%20Outreach%20Tracker%20-%20May%202022.xlsx&action=default&mobileredirect=true)). Sent last of recruit emails to PA DOH and Guam DOH/Inductive Health. BX to 1) finish prepping facilitation notes for Friday call with NH DOH, 2) follow up with Alaska DOH with thank you and completed action items.

**Comment by BerniXiongA6** [comment]
Updates on 5/23/2022: Can close this for this sprint. Can create a new ticket to capture the notes for upcoming calls with WA DOH & Guam DOH, both scheduled for 6/6/2022. cc: @a-chappelear @RakshindaAslam

**Comment by BerniXiongA6** [comment]
Updates 5/25/2022: Transcript and action items for NH DOH are [ready for viewing here](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Design%20and%20Research/RS%20CX%20Survey_Likelihood%20to%20Refer%20Research%20January%202022/Follow%20up%20interviews%20for%20CX%20Survey/Interview%20Recordings%20and%20Transcripts/New%20Hampshire%20DOH?csf=1&web=1&e=m6jELz). @RakshindaAslam and I to chat on 5/26 about MN DOH's question regarding follow-up interview before they schedule with us.

**Comment by BerniXiongA6** [comment]
Updates 6/6/2022: Completing Washington DOH and Guam DOH calls tonight. Will get transcripts, notes, and follow up emails and action items done before Friday.
