### ISSUE TITLE
Clean CSV Data: Allow double quotes in mapper parameter arguments

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#3500]
## Problem statement

Currently with mapper arguments, you can not have a single argument that contains a double quote (")- else you will get a parsing error. The use case for allowing double quotes are to be able to have arguments that contain commas in them- such as address information or other general cases.

Example:

>     - name: ordering_provider_last_name
>       csvFields: [{name: Provider Last Name}]
>       mapperOverridesValue: true
>       mapper: ifNotPresent($mode:literal, $string:"Patel, MD", some_field, some_other_field)

This mapper definition is trying to say: if some_field and some_other_field is blank, then write "**Patel, MD**" (without quotes) to the Provider Last Name field. A small code change to the parseMapperField() function will get you past the parsing error, but the code still interprets the comma in "Patel, MD" as the end of that particular argument. Specifically, the value gets mapped as **"Patel** (with the quote)

This is behavior is general to _all_ mapper functionality- not just ifNotPresent, for example.

## Acceptance criteria

- Allow double quotes to appropriately group a value containing commas, rather than as an end-of-argument delimiter, for any mapper function

**Comment by rhood23699** [comment]
@loripusey de-prioritized as of 12/27; not needed for standard CSV schema
