### ISSUE TITLE
SPIKE -- Understand Needs and Potential Solutions for Managing Values & Value Sets

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3501]
## Problem Statement
Let's get with Mo to understand where we are with moving the values to the DB and what the needs are for managing them.

**Comment by loripusey** [comment]
@sean-usds do you have enough information from our meeting with the other teams to create some tickets for this epic? Here is the [mural board](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1639501417351/8582e7c460c7bc759f7251f6c6c44ef693da7c1f?sender=ud3aa760e30b39bcf436d4473) to refresh your memory

**Comment by sean-usds** [comment]
@loripusey do you have a sense of which value sets need are edited most frequently? That'll help prioritize where we start. 

@drew-usds we can start on something fast and loose here similar to settings admin UI, but wanted to put this on your radar since we'll eventually want UI design input

**Comment by loripusey** [comment]
@sean-usds values sets edited most often would be a good question to ask @mauricereeves and @rhood23699

**Comment by sean-usds** [comment]
Notes from 1/10
- Goal it move off value sets and move to lookup tables
- Can prioritize building support for editing lookup tables
- Lookup tables already have an API
  - Supports full CRUD
  - Doesn't edit, just replaces records (can make it slow)
  - No lock version support
- Assumption is that Rick Hood will be primary (only) user
- Database has been replaced with command line tools
- Can load lookups from csv tables
- Should support field validation
- One use case is supporting uploading a csv to a table
- Use case 1: tweak
  - Pull current version, make a tweak, send it back
- Use case 2: bigger table changes
  - Table lookups are defined in a csv locally, csv need to be uploaded 
- Zip code table
  - Ideal to pull all data into the browser so missing zips can be searched for
  - If zip is missing, it can be added in the web UI 
- Right now the API doesn't support editing one row, just updating the entire table
- Web UI could start with small tables
  - Example: Dr name lookup based on facility 
- Small tables that would be good to start with: dr lookup, sender automation value set (seth), LIVD supplemental
- API should support looking up all table name options
- Large table examples:
  - HCA, need to expand to all body parts (will be thousands of records). Official version is on SNOMED
  - Specimen type, source
  - Possible tests (all reportable diseases) 
- Rick is initial customer

**Comment by sean-usds** [comment]
I broke the work into eng tasks that can be seen in the epic https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3489
