### ISSUE TITLE
Add External Patient ID to schema

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#3502]
We have a use case where systems that are submitting to us may need to track more than ID for a patient, for example a school may want to include the student ID when submitting records to SimpleReport, or a department of corrections may want to include a prisoner's ID. To facilitate communicating that to STLTs, we need to add a new field to the COVID-19 schema that will be called `external_patient_id`. If it is has a value, we will fill in a repeat on the `PID-3` value. The `external_patient_id` will *ALWAYS* go after the primary `patient_id` field.

In addition, we will add a feature flag to allow for states to receive external patient IDs. If the flag is false, we will NOT put any repeat into the `PID-3` field even if `external_patient_id` has a value. This means, for example, that if a resident of VT ends up in a prison in TX and TX sends us the prisoner's ID, we would not send that second ID to the state of VT unless they have specifically and explicitly asked us to turn this feature on.

### Acceptance Criteria
- The field is added to the schema
- If the field has a value, we add it to `PID-3` as a second repeat. 
- If the field doesn't have a value, we do not affect PID-3 in any way
- The feature flag for second additional IDs is added to the translation config and the logic for inserting the repeat will be wrapped in the check of the feature flag

**NOTE**: because of the way we process elements in reports, `external_patient_id` will come first before `patient_id`, which means you cannot simply just add the `external_patient_id` to `PID-3`. You can add it, but you will need to make sure that when you are inserting the `patient_id` that you prepend it to the existing value in `PID-3`. This is similar to the logic we use when we put the email after the phone number in `PID-13`.

**Comment by rhood23699** [comment]
This was mentioned as a possible need during the kickoff call.  BI2 Technologies is working to create their 1st test file.  We'll wait to see if they request this addition.

**Comment by brandonnava** [comment]
@brick-green Any qualms with closing this? As per Adrian's comment no one is asking for it and it looks related to SR if anything.

**Comment by brick-green** [comment]
@brandonnava I think we can close till it's asked for. I like the concept for the ticket.
