### ISSUE TITLE
Add fileName to json response for submission history

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#3506]
For end points:
- /history/{organization}/submissions
- /history/submissions

The web app needs the file name for each submission. For cases where there is no file name, the field can be left out or set to an empty string

**Comment by jimduff-usds** [comment]
The field is called external_name and is in the action table as a column.   (For some reason I forgot to put its in the action_response json; it needs to go there too; we could do that as part of this ticket, or as a follow-on)

Please call it `externalName` not `fileName`.   Its just a descriptive string, useful to the sender, that they attach to the POSTed payload.   Usually that's a filename, but doesn't have to be.

**Comment by whytheplatypus** [comment]
Hey @jh765 I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/pipeline-6182b02547c1130010f459db/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by jh765** [comment]
First Comment - this is from github.com.  I'll also try from Zenhub.  If you read this, it worked.
