### ISSUE TITLE
Build a Standard COVID Schema 

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3508]
## Problem Statement
As the Experience Team, we need a standard schema for COVID reporting in ReportStream so that we can test the hypothesis that reporting entities will be able to comply with a standard schema.

## Notes
Jim currently taking a first pass at building and will then be handing off to Joel & Rick 

## Criteria
- [x] Setup a default sender_id named "manualupload" to be used as a test Sender for our validation.
- [x] The schema must be developed based on the requirements outlined in the Standard CSV Requirements document named "CSV-StandardFileFormatAndNotes-v2.docx" in the CSV Pilot Sharepoint folder.

**Comment by loripusey** [comment]
@brick-green-agile6 @brick-green-agile6 @jbiskie Created this ticket for your work picking up the standard schema handoff from @jimduff-usds 

Can you update us on the status?
cc: @rachelhanster

**Comment by rhood23699** [comment]
12/17/21 - Rick H completed the initial draft of a document outlining required fields to be reviewed by MikeC, Brick, Joel and Rick.

**Comment by rhood23699** [comment]
12/20/21 - Feedback has been received.  We'll finalize the requirements today and begin building the schema, and providing info to the Research Team to build the initial documentation.  Also will create another Ticket because this one will be closed when JimD's merge is completed.

**Comment by rachelhanster** [comment]
FYI @BerniXiongA6 here is the latest info on standard schema for csv use case

**Comment by MikeC-A6** [comment]
@rachelhanster - The term "schema" in the context of discussing ReportStream typically refers to a YAML file that can be read during the ReportStream processing pipeline.  For the purposes of an MVP for LADOH, I think this needs to be broken down further so we can deliver on time.  Potential way to break this down:

1. Sample CSV format with an accompanying document that outlines the expected format for each field
2. Reportstream YAML file schema deployed into staging, and tested with dummy data
3. Reportstream YAML file schema fully tested and deployed into production

I think what we are looking for for LADOH MVP by Wednesday is #1.  This should be complete by COB Tuesday, 12/20.  CC @rhood23699

**Comment by rhood23699** [comment]
12/21/21 - The initial draft of the Standard CSV File Requirements is complete.  The Research Team has the document which she'll use in the User Facing documentation.  Brick and Joel may review further to insure that I got everything correct.

Also a sample Standard CSV file has been created.

**Comment by rhood23699** [comment]
12/22/23 - Completed first draft of schema and it works. Extensive testing is still needed and pending.

@loripusey Note, I closed #3583 and will made all updates to this ticket.

**Comment by loripusey** [comment]
@rhood23699 from you last comment can you clarify what ticket 3583 has to do with the standard schema?

**Comment by loripusey** [comment]
@MikeC-A6 I'll add tickets for 
> 2. Reportstream YAML file schema deployed into staging, and tested with dummy data
> 3. Reportstream YAML file schema fully tested and deployed into production
One question, is the standard schema currently tailored for Louisiana and being deployed as a Louisiana-specific schema?

**Comment by rhood23699** [comment]
@loripusey @MikeC-A6 The standard CSV schema is not being deployed as a LA specific schema.

**Comment by Adrian-Brewster** [comment]
Just merged. Will go in with tomorrow's deployment

**Comment by rhood23699** [comment]
This was deployed today.
