### ISSUE TITLE
Require at least one of: test_kit_name_id,device_id,equipment_model_name required for all senders

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#3525]
(This ticket was split apart from 2054)

We need all our Covid-19 senders to use valid device IDs at all times, because both we and the states use it for all kinds of other lookups and validations.    Currently we don't  always require a valid value.   So the value needs to be non-empty AND it needs to be match-able to a valid value in LIVD (or one of our special Fake values - see #2054 

| Our name | HL7 loc | Livd Location | Livd Name | Our Mapper|
|---|---|---|---|---|
| test_kit_name_id |  ? | column M | 'Testkit Name ID' | livdLookup() mapper |
| equipment_model_name | OBX-17-2 | column B | 'Model' | livdLookup() mapper
| device_id | OBX-17-1 | column O, | 'Equipment UID' | obx17() mapper

So, each sender must send at least one of the above values, with a match against the appropriate column in the LIVD Table as specified above.

If they don't have a valid value, they can use one of our dummy/fake values (see #2054)

### Acceptance criteria
- Review each schema, and change to enforce the `cardinality: ONE` rule for at least one of those fields.  Operations team must notify each sender of the impending change! Coordinate carefully with @anshulkumar-usds .
- having the field filled in is insufficient - you also have to enforce that the value is valid from the LIVD table.    I suggest changing the mapper so it always runs, even when the field is non-empty.   See Carlos' #2270 and use `mapperOverrideValues: true`
- Simple rule:  If you give us a value, it better be in the LIVD table, or be one of our Fake values, or we give an error.

### Design Considerations

- How do we want to "match"?   contains?   exact?  some regex? 
- What if there's no match?  Its just an error - is that OK?
- should we also attempt LIVD lookup matches on test_ordered_code and test_performed_code?  These are non-unique - what do we do with that?
- I suggest you try to combine livdLookup() and obx17() mappers into one new mapper that gracefully handles all three fields.
- Some small senders won't be able to make these changes.   Carlos' new 'lookupTable' work is meant to address those situations.
- Special Note: the PDI schema is super confusing - it has a column they call `Device ID` that maps to our internal `equipment_model_name`, not to device_id.  Confusing.
- You can do a Covid-result-metadata query and find the total list of all distinct test_kit_name_ids, and figure out which senders are sending invalid values  or no value at all.  
- When we roll this out live, we'll need to make sure there's no data queued for batch, because it may fail, due to the new validation rules.
- Note:  You'll see that there is a device_id in our schema. If empty, it is filled in using the obx17() mapper.    Currently device_id is treated as an outgoing-schema field only.   However, it now appears we have senders sending us the device_id.
- Note that currently, test_kit_name_id in our schema, if empty, is filled in using the livdLookup() mapper.    Its also a possible input to the mapper, so its playing the role of both the independent and the dependent variable, which is confusing.

**Comment by carlosfelix2** [comment]
Next action:
1. Wait for the deployment of #3580 and wait an extra few weeks to collect data as to what senders are having LIVD lookup issues or not.
2. When updating a sender we may need to notify them about the change.

**Comment by carlosfelix2** [comment]
Talking to the operations team, it is more prudent to slowly add this capability to the different senders, so there is communication with each one when this will happen.  Perhaps move this ticket to the operations team.

**Comment by Adrian-Brewster** [comment]
Anshul to schedule convo to brainstorm this issue

**Comment by anshulkumar-usds** [comment]
Working to have this implements with each sender one at a time. Starting with ImageMover: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4230
