### ISSUE TITLE
Add sender attributes to our Sender settings

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#3526]
PRs  [4401](https://github.com/CDCgov/prime-reportstream/pull/4401), [#4624](https://github.com/CDCgov/prime-reportstream/pull/4624), [#4639](https://github.com/CDCgov/prime-reportstream/pull/4639), and [#4700](https://github.com/CDCgov/prime-reportstream/pull/4700)
### Acceptance Criteria

Add these attributes to Sender object and corresponding sender settings in the database:

1.  `senderType`.   Possible enum values are: `testManufacturer, dataAggregator, facility, hospitalSystem`.   Default is null.

2. `primarySubmissionMethod`.  Possible enum values are `automated, manual`.  Default is null.

- both should be nullable and null by default.
- test the `./prime sender` methods thoroughly by hand.  You should be able to retrieve an old setting with these values missing, add them, then submit an update.  You should also be able to submit a sender setting with these values missing.
- add values to unit tests as needed
- Be sure to also fix the SenderAPI class down inside the SettingsFacade.  
- please add a separate ticket to add ability to speicfy a userAgent header value to specify primarySubmissionMethod.

### Design Considerations

@whytheplatypus suggests making primarySubmissionMethod settable by header.  However, I think we need this under our control so we can turn on/off submission easily, if we want to start to 'enforce' this field.

**Comment by anshulkumar-usds** [comment]
Hey @jimduff-usds sorry I completely missed this. This is still needed. Here is my proposal:

Sender type:
1. Test Manufacturer
2. Data Aggregator
3. Lab/Facility

Sending method:
1. API (synch or asynch endpoint)
2. Flat-file upload

**Comment by anshulkumar-usds** [comment]
Hypothetical question we'd like to answer: 

Abbott, a test manufacturer, sends us OTC BINAX-NOW results. ImageMover, a data aggregator, sends us OTC BD Veritor tests. Both sending entities are sending us OTC results; however, one (Abbott) is a test/device manufacturer, and the other (IM) is a data aggregator. By having these identifiers, we can study data quality and completeness across the sender types.

**Comment by jh765** [comment]
### putting this off
Primary-test-Method Flag:
proctor-authorized
not proctored
unknown/mixed
### Anshul can get more clarity on this one.

**Comment by whytheplatypus** [comment]
lets split ` sendingMethod` into a separate ticket, it should probably not be static in something like settings, but allowed to be set via a header (probably user agent, or similar)

**Comment by jh765** [comment]
Anshul, the `senderType` should have a default value.  If you had to pick the default,
`testManufacturer, dataAggregator, facility, hospitalSystem`
what would you recommend?
I used `SenderType.facility` (they are more-likely to need a default) but that is easily changeable.

**Comment by anshulkumar-usds** [comment]
Fine with using ```facility``` as the default

**Comment by jh765** [comment]
did someone remove the following line:
import gov.cdc.prime.router.azure.Facility
(was line 5 of sender.kt)

**Comment by TurkeyFried** [comment]
Using a default value for `senderType` is making the test data look off. Might be best to just let the field be nullable unless the data is provided by the client.
