### ISSUE TITLE
Add Schemas to the Settings Table (or its own Table)

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#3531]
## Introduction
It is time for us to add schemas to the database and stop reading them from the file system. This is a *HUGE* change, and something that will require a lot of work. But this will make it possible for us to more quickly push updates and changes for senders and receivers, or even onboard new senders/receivers.

## Acceptance Criteria
- All the existing schemas are loaded into a table in the DB
- The settings CLI allows us to upload, download, and interact with schemas just like we do with other settings
- The Metadata object loads schemas from the database first
  - But we are able to also inject schemas into the Metadata object
  - If there is a conflict between what's in the DB and what's on the file system, the DB is the winner 

## Next Steps
I will create a proposal for this to solicit comments from other engineers, and then update this ticket based on the feedback.

**Comment by MauriceReeves-usds** [comment]
I think for the purposes of this work, we should have the ability to process a schema in both JSON and YAML format.

**Comment by jimduff-usds** [comment]
Note:
#2571
#3135
#3364
#3531
are all very similar.  We probably only need one of these.

**Comment by Adrian-Brewster** [comment]
This looks like it really needs to be an epic. Does this work live with the pipeline team?

**Comment by Adrian-Brewster** [comment]
Iceboxing to see if ticket becomes redundant with FHIR work
