### ISSUE TITLE
JSON response from reports and waters API should be identical to the Submission History API response

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#3534]
As a sender, when I submit to ReportStream, I want a well-formatted clean response that is identical to what I would get from the SubmissionHistoryDetails API.

Note on tickets blocking this one:
- In ticket #4241 (DONE!), we've done the work to make the HistoryDetails API backward compatible.  So now we can safely replace the old json response with the History Details response.
- In ticket #4246 (DONE!), we've enable the HistoryDetails API to search on report "id", in addition to submissionId.   Our customers are much more used to report Ids.

Note:  this is the ticket in which we "go live" with the new Details, so let's make sure our ducks are in a row, both that its solid and we have good communications going out.

### Acceptance Criteria

- The json response is identical to that generated by the new History Details API.   Check with @whytheplatypus -- I think he has expressed some ideas on how to do this.
- This works for both `api/waters` and `api/reports` endpoints, and it works for both sync and async calls.  (Sync would contain the `destinations` and `routing`, and async these values would be empty)
- This works for both successful submissions and for failed submissions.
- Important:  Release notes must be written documenting all the changes for our customers.  Make sure @anshulkumar-usds has time to communicate them out prior to go-live.  (This is all in a different ticket, #4263)
- If we didn't forget anything with #4241, the smoke tests should work with no modifications!

## Design Considerations

Key point:  We want the API response to be identical to the submission response.  Best way to do this is to use the same code.  

An important open question is whether we'll continue to use either the action_response or action_result fields.   They make it super easy to do debugging by doing database queries, but maybe those days are gone, and all such debugging will be replaced with API queries?    Either way we decide, we need to document it, so that we know if we have to continue maintaining those fields for new features.   We CANNOT delete those columns just yet -- they are used by error cases to document the error, eg send_warning, send_error, process_error, etc.  All those use cases would have to be migrated to the action_log table before we touch the action_response and action_result columns.

#### Testing note

A valid localhost history details api GET has this form.  It requires the authorization header, but the value can be bogus.  The python prettyprints the json:

 curl -H "client:ignore"  -H "authorization:bearer 123" -H "content-type:text/csv" "http://localhost:7071/api/history/simple_report/submissions/1557" | python -mjson.tool

#### Further work

Note the history details does not have the per-Item "routing" info.

**Comment by jimduff-usds** [comment]
Example of the current json returned at the time of submission, with verbose mode on:

```
{
  "id": "690bce83-dfc7-4d3f-aa52-45e3f20ee014",
  "topic": "covid-19",
  "errors": [],
  "sender": "cue.default",
  "warnings": [
    {
      "scope": "REPORT",
      "message": "Missing 'correctedTestId' ('previous_message_id') header"
    }
 ],
  "timestamp": "2021-12-19T23:34:31.013992Z",
  "errorCount": 0,
  "destinations": [
    {
      "service": "elr",
      "itemCount": 1,
      "sending_at": "2021-12-19T18:42-05:00",
      "organization": "HHSProtect",
      "organization_id": "hhsprotect"
    },
    {
      "service": "elr-neg",
      "itemCount": 0,
      "sending_at": "never - all items filtered out",
      "organization": "Washington Department of Health",
      "organization_id": "wa-phd",
      "filteredReportRows": [
        "For wa-phd.elr-neg, filter isValidCLIA[testing_lab_clia, reporting_facility_clia] reduced the item count from 1 to 0.  Data with these IDs were filtered out: (F4677DE5-11B7-3AD7-801D-41A23D571167)"
      ]
    }
  ],
  "warningCount": 16,
  "reportItemCount": 1,
  "destinationCount": 1
}
```

Change needed:

- Change current "id" to be "submitted_report_id", and add action_id as the new "id".
- Change "timestamp" to "submitted_at"
- Add "submitter", and use the sender's full name (eg simple_report.default)
- Use universal consistent syntax (right now we have camelcase (errorCount) mixed with underscores (organization_id)
- change reportItemCount to submitted_item_count
-

**Comment by jimduff-usds** [comment]
Three approaches to getting SubmissionDetails
- #3534 : fix the fieldnames returned in the submission json; ignore the new details API for now.
- #3538 : keep the old filenames; just combine process/receive and return via new details API.
- #3539 : write the new details API, ignore the submission json for now.

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/3534?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @smythe5 @TurkeyFried @whytheplatypus
