### ISSUE TITLE
CUE - Confirm if proctored OTC results are reaching CA

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3536]
CUE is inquiring if their proctored results are being delivered to CA.

Per CUE, CA shared on a recent AIMS call that they do not want OTC results, but ok with proctored results. Hence, we need to confirm whether RS is routing CUE's Proctored OTC results to CA's primary feed.

CA has completely turned off their secondary feed citing data quality and completeness concerns with OTC data.

**Comment by Adrian-Brewster** [comment]
Was likely turned off when secondary feed was turned off.  @jbiskie @brick-green-agile6 can one of you two look into this?

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 could you please take a look at this today? Thank you.

**Comment by brick-green-agile6** [comment]
@anshulkumar-usds Just reviewed the most recent results and they are not going to CA. Still trying to lock down which specific quality filter is blocking the results from continuing.

**Comment by brick-green-agile6** [comment]
Checked the CUE files against the quality filters for CA. They are failing for two reasons:

1. Missing CLIA
2. Missing Provider ID

**Comment by anshulkumar-usds** [comment]
Shared updates with CUE - no further questions at this time.
