### ISSUE TITLE
As an Async Sender, I want a History Details API that returns a clean, well-formatted response from 'process' and 'receive'

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#3539]
As an Async Sender, I want a new History Details API endpoint that returns at least what I get when I do a synchronous submission, but with the fieldnames cleaned up.  Ignore the submission json response for now.

This is the beginning of implementing #2722.  All of #2722 is too much for one ticket, so I'm splitting it up, starting with this one.  This ticket covers creating a new SubmissionDetailedHistory object, and populating it from database data.   Initially, this approach ignores the fact that the `action_response` is old/different.

## Acceptance Criteria

- A call to to the History API /submissions/submission/{id} endpoint returns a json serialization of the SubmissionDetailedHistory object, as represented in the example below.
- Only return data combined from the 'receive' and 'process' steps.
- This works for data submitted by either sync and async method.   That is, either way, the History Details API response would contain the 'destinations' info.
- Note that the field names in the example below are different from in the current action_response.  Here, the fieldnames are camelCase throughout.  In action_response there's a mix of camelCase and under_scores.
- Release notes are written documenting all the changes.
- Update the openapi spec as needed.

- The JSON follows this example (the comments are not proper json):
```
{
  "id" : "123456",      // action.action_id.      Report_id is now relegated to second class citizen, so we can show errors better.
  "externalName":  "/foo/bar/baz/quux/mydata.csv",    // name given to us by the sender.  Could be any string.
  "submittedAt" : "2021-08-22T12:51:28.785706Z",     // action.created_at
  "submittedReportId": "abc123cd-07b1-4784-9907-e43c194abbb",  // was "id"
  "submitter" : "robust-tester-inc.default",          // was "sender"
  "topic" : "covid-19",
  "contentLength" : 44553,                        // action.content_length
  "httpStatus" : "201",                           // action.http_status
  "submittedItemCount" : 25,
  "warningCount" : 0,
  "errorCount" : 0,
  "errors" : [ ],  
  "warnings" : [ ],
  "destinations" : [{
    "destination" : "Alabama Public Health Dept",  // was organization
    "destinationId" : "al-phd.elr",  // was organizationId and service.
   "itemCount": 25,
    // (if we want, we could include processed_at and batched_at timestamps too...)
    "plannedSendAt" : "2021-10-22T10:00-04:00",   // determined during routing.
   },
    {
      "itemCount": 0,
      "plannedSendAt": "never - all items filtered out",   // bad.   Mixing date and string datatypes.
      "destination": "Washington Department of Health",
      "destinationId": "wa-phd.elr_neg",
      "filteredItems": [   // change name from filteredReportRows
        "For wa-phd.elr-neg, filter isValidCLIA[testing_lab_clia, reporting_facility_clia] reduced the item count from 1 to 0.  Data with these IDs were filtered out: (F4677DE5-11B7-3AD7-801D-41A23D571167)"
      ]
    },
   <etc>
  }
}
```

Note the change from "send/sender" nomenclature to "submit/submitter".   "Send" is confusing:  does it mean sent to reportStream, or sent to the State.

## Design Considerations

Here's what we need to build:

- We get a Sender history query: /submissions/submission/{id} 
- We authenticate sender vs the id in the action and/or report
- Do a descendant query 
- For all reports Grab the receive and process steps and get the details from REPORT_FILE and ACTION.
- Populate a tree-of-history object
- read from that object, massage, and create a SenderDetailedHistory object, and return it.

Note: While not in this ticket, its important to remember ultimate goals:
- When all is done, we want info from the entire chain of descendants, not just 'receive' and 'process'
- When all is done, we want the waters and reports submission responses to be identical to the History Details API response.

## What's not in this ticket:

- making the submission json response look like the above response.
- Some of the complicated fields are still missing from the original #2722:
 -- overallStatus
 -- plannedCompletionAt
 -- per-destination:  `actuallySentAt`
 -- per-destination consolidated errors and warnings across all subsequent steps.
- including the 'routing' info if verbose==true param is used in call.  For reference, the routing section looks like this:

```
  "routing": [
    {
      "trackingId": "ba5970a1-d047-4cfe-a385-d70163f50863",
      "reportIndex": 0,
      "destinations": [
        "al-phd.elr"
      ]
    },
  <etc>
 ]
```

**Comment by jimduff-usds** [comment]
Steps to completing #2722:
1. #3539 (this ticket): Write the new details API, ignore the old submission json for now.
2.  #3534 : Replace the old submission json so its identical to #3539.
3.  Wrap up by doing Batch and Send steps and related fields.

- #3538 : keep the old filenames; just combine process/receive and return via new details API.

**Comment by jimduff-usds** [comment]
I've done a pass at trying to write queries to support the construction of the "tree of history" as mentioned above.

I ended up dividing this into three queries:

1.  Given the action_id of a submission, get basic information on that submission
2.  See if it has an associated submitted report.  This is the mother report.
3.  Find detailed info about it and all its children.

To wit:

1.  Get basic info on the submission, that might or might not have failed. 
```
select
  A.action_id       as id,
  A.external_name   as externalName,
  A.created_at      as submittedAt,
  concat(A.sending_org, '.', A.sending_org_client) as submitter,
  A.content_length  as contentLength,
  A.http_status     as httpStatus
from action as A
where 
  A.action_id = $action_id 
  and A.sending_org is not null;
```

2.  See if there is a mother report associated with this Action.  I'm doing this as a separate query because the LEFT OUTER JOIN didn't work, due to a quirk in our data.  (The quirk is that for non-async submission, the action has mutiple reports associated with it, and the _only_ way right now to find the mother report is to search on `sending_org is not null`.  However, if we do that, then the query won't work in cases where the Action failed.   So I left out the LEFT OUTER JOIN)

```
select
  RF.report_id      as submittedReportId,
  RF.created_at
from action as A
join report_file as RF ON A.action_id = RF.action_id
where 
  A.action_id = $action_id 
  and A.sending_org is not null
  and RF.sending_org is not null;

  -- Stil missing these values:
  -- missing overall_status
  -- missing planned_completionAt
  -- missing warningCount, errorCount, errors[], warnings[]
```

3.   Find detailed info about the mother of all reports, and all its descendants. 
```
select 
  RF.report_id as reportId,
  A.action_name as actionName,  -- report was created by this action
  string_agg(RL1.child_report_id::text, ',') as childReports,
-- SKIP PARENTS FOR NOW:   string_agg(RL2.parent_report_id::text, ',') as parents,
  A.action_id as actionId,
  A.created_at as createdAt,
  RF.item_count as itemCount,
  RF.receiving_org as receivingOrg,
  RF.receiving_org_svc as receivingOrgSvc,
  RF.next_action_at as nextActionAt,
  CASE 
      WHEN A.sending_org is not null THEN substring(A.action_result,0, 8)
      ELSE A.action_result
  END as actionResult
  -- missing all error and warning details
from report_file as RF
join action as A ON A.action_id = RF.action_id
left join report_lineage as RL1 on (RF.report_id = RL1.parent_report_id)  -- used to find the children
-- SKIP PARENTS FOR NOW:  join report_lineage as RL2 on (RF.report_id = RL2.child_report_id)   -- used to find the parents
where RF.report_id in (select report_descendants('$report_id'))
group by   RF.report_id, A.action_id, item_count, A.action_name, receiving_org, receiving_org_svc
order by RF.created_at
```

**Comment by loripusey** [comment]
@jimduff-usds Is this ticket being done in the current sprint? and do you expect it to be finished in 1 sprint?
cc: @rachelhanster @ahay-agile6
