### ISSUE TITLE
WA - Do Not Need Tribal Affiliation Transmitted

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#3555]
WA have requested that tribal affiliation data for patients not to be sent to them.

**Comment by anshulkumar-usds** [comment]
@MauriceReeves-usds WA has requested that we do not send them tribal affiliations. Is there any configurations that need to be updated to handle this?

**Comment by MauriceReeves-usds** [comment]
@Adrian-Brewster @anshulkumar-usds @sarahnw moved this into the sprint backlog. this should be a very simple field to suppress or blank out, and we might as well do it so we can close out this ticket.
