### ISSUE TITLE
CSV Uploader Enhancements for Errors, Warning, & Quality Filters

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3557]
## Problem Statement
As we begin to release the CSV Uploader to pilot participants, we need to enhance the feature based on our findings.

**Comment by loripusey** [comment]
@drew-usds @inkandsound Do we have enough feedback to finalize the discussion for these stories today in refinement and point?
cc: @rachelhanster

**Comment by rachelhanster** [comment]
Closing this epic. Transfer product backlog tickets to Simplereport for product manager's future consideration. cc @timothybest-usds
