### ISSUE TITLE
Validate gitleaks config

### ISSUE THREAD

**Issue by acoushawk** [CDCgov/prime-reportstream#3559]
We found that gitleaks was not using the correct config file. Once we added this functionality we got ~50 errors which was preventing us from merging. These errors need to be reviewed/documented and discussed with the group to determine their validity.

**Comment by jeremy-page** [comment]
https://github.com/CDCgov/prime-reportstream/releases/tag/v-2022.03.03-181702 shows it applied successfully

**Comment by zricethezav** [comment]
@jeremy-page @acoushawk @cwinters-usds 👋🏻 we recently released a [new version of Gitleaks-action](https://github.com/gitleaks/gitleaks-action/releases/tag/v2.0.0). It includes lots of new features and  uses the latest version of gitleaks (v8.8.7 atm). Feel free to shoot me an email if you want a demo: `zach @ gitleaks.io`
