### ISSUE TITLE
As a database connection pool, I want to handle even larger loads by biggering

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#3566]
This ticket is to experiment with biggering our database connection pool size.

This is a DevOps / Pipeline Collab.

Pipeline can run a Simulator.kt Load against Staging, when DevOps varies the connection pool size.

The trick is to pick a load that simulates large simultaneous submissions.   Note that these may be limited by local laptop thread/process limitations.

### Acceptance Criteria

- we have determined the largest reasonable connection pool size.
- we've set the pool size in Staging, and ready to go to Prod.
- (create a ticket if needed)

### Design Considerations

- might need to run from a different server on the cloud.
- See:  https://azure.microsoft.com/en-us/blog/performance-best-practices-for-using-azure-database-for-postgresql-connection-pooling/ for possible tool to help with this work.

FYI @cwinters-usds

**Comment by cwinters-usds** [comment]
Recent (2021-12-21 @ 4:50 PM EST) percentile breakdown (in ms) of the duration of "reports" transactions over the last...

```
            50%   75%   85%     95%      99%
 4 hours:   274   816   909   1,336   92,674
12 hours:   299   838   938   2,522   92,670
24 hours:   442   855   953   2,009   89,648
48 hours    453   849   946   1,812   31,786
72 hours:   613   849   943   1,712    4,822
  7 days:   356   835   933   1,578    3,614
```

The top-end is what's hurting us during these storms, I think. In addition to considering increasing the connection pool size we might decrease the amount of time it'll wait for a connection. Or at least putting a max cutoff of 10 seconds (or something) for all incoming transactions to "reports".
