### ISSUE TITLE
CSV Serializer checks cardinality before running mappers

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#3579]
Currently the CSV serializer read checks for cardinality first before running the mappers.  An example of the limitation that brings is having the ability to use mappers to validate incoming data (e.g. the LIVD lookup mapper could check values and blank them out).

There are questions about if any of this is the proper way to do this or if changing anything breaks data, so a big portion of this issue is to identify if we even need a change here.

Acceptance criteria:
1. Identify if we really want or need to check cardinality before running the mappers.  This could have been done to keep the cardinality check to only use the provided data, so we can then run mappers and modify the data, but the mappers will not provide any errors to the sender.
2. Make any changes to this logic if needed.  Preferably, use the logic provided in the Element.processValue function, so the logic on how to run mappers, etc. is centralized.

**Comment by carlosfelix2** [comment]
Status:
1. Yes, we want the cardinality to be checked like the rest of the logic.  No one knows why it was done this way.

**Comment by RickHawesUSDS** [comment]
I agree that the current behavior is wrong. Cardinality should be checked on validated values.
