### ISSUE TITLE
Reach out to Louisiana for Sender Referrals

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3581]
## Problem Statement
As the Experience Team, we need to reach out to PHDs to get referrals for COVID reporting entities.

## Acceptance Criteria
- Schedule times to speak with PHDs
- Speak with PHDs
- Compile referral list & any notes

## Responsibilities & Questions
- Determine who is responsible for engaging with referrals (i.e. prospective Senders)
    - Kevin will send an email to LADOH saying we are preparing an email for them to send to prospects
    - TBD
- Determine who is responsible for onboarding and getting to production w/ public health department + prospective sender
    - O&O team (Rick Hood w/ a backup person)
    - SLA: respond to questions w/i 1 business day
- How much support are we willing to provide to Senders?
    - We will do NO manual cleaning work for them
    - We will do NO deployments for them (i.e. custom schema & data cleansing)
    - Answer questions about complying or the onboarding process via email or phone (exceptions on a case-by-case basis)
 
## Proposal for Louisiana Senders
- All senders in this [list ](https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BFC2449BB-4775-4869-8658-35CC4A0E97E7%7D&file=Agile6_CSV_initial_list_20211213%20(1).xlsx&action=default&mobileredirect=true)get email outreach about reportstream, csv, and schema
- Open question 1: does LADOH send this email or does reportstream/cdc send this email?
   - LADOH sends the email
   - Some senders may need an additional email
- Open question 2: how many lead generating emails?
   - Each prospect gets 1 email

**Comment by victorialb-usds** [comment]
Could we do a baseline assessment with these new senders or first do a discovery call?

**Comment by loripusey** [comment]
I didn't think that a baseline assessment was planned as part of this second round of piloting; I believe the plan was to have Louisiana & California send out the emails for us early next week
@rachelhanster ?

**Comment by loripusey** [comment]
[Uploading... Louisiana Email.pdf]
