### ISSUE TITLE
Settings Bug: new processing=async flag in Settings doesn't appear on prime CLI settings reads 

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#3587]
When reading a sender's setting from the database using the CLI, a sender set to processing type of Async returns sync instead.

**Comment by carlosfelix2** [comment]
Unable to reproduce.
Traced this issue in various places and saw no issues with the code. Tried to reproduce as follows:

1. Change a sender in the organizations.yml file to have processing type of async.
2. Load the settings to the database.
3. Verify the setting was stored. Note that there could be multiple versions of a setting, so make sure to look at the last version.
4. Run ./prime sender get -n <name> and verify the async flag is set correctly.
