### ISSUE TITLE
NJ - OBX-18 Missing Required Field

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3606]
On 12/27, NJ reported a message with missing required field in OBX-18

1105fda9-c49e-4b43-a429-49d10d591af3 PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[0].OBX.EquipmentInstanceIdentifier[0].EntityIdentifier                Required field missing

This is supposed to be an EI data type, and the field contains:  |^^MNI|

**Comment by hermanAlexCordero** [comment]
report id is wrong.  The correct report ID is:
1105fda9-c49e-4b43-a429-49d10d591af3
Investigating issue

**Comment by hermanAlexCordero** [comment]
report id is not reading correctly.  The correct report ID is:
1105fda9 - c49e-4b43-a429-49d10d591af3
Investigating issue

**Comment by hermanAlexCordero** [comment]
report id is not reading correctly.  The correct report ID  has a 9 after fda.  for some reason the 9 before the dash does not get displayed

Investigating this issue

**Comment by anshulkumar-usds** [comment]
@hermanAlexCordero  NJ reported a few more cases of missing OBX-18 on 12/30; details below:

File#1:  CDC_PRIME_covid-19-c5e34f80-0f28-4354-8eb3-164349821d0e-20211230141655.hl7
Message IDs:
a25d3f24-5073-46a2-9a6b-c21d1d0511f6
8f1cee78-adeb-4f3c-b42c-6e5271c6471a
809d3310-ea21-445c-a879-d2fd7bddc11e
8e49326b-09a3-41e5-9e7f-e2287c6634bb
80b4b902-ab0b-4a04-8055-b2d73388b65d
dff96021-a932-45b3-9bc8-6ccbc25a6205
8bd0ba78-217c-4e41-bf22-3d24d6af78f3
b64116a3-92e4-42ed-88b4-61f82bbe162d


File#2: CDC_PRIME_covid-19-f785326d-05c1-4385-a894-fe0d37be0f01-20211230141653.hl7
Message IDs:
0a3975da-b53d-4d65-9bda-1b7ef50b05e5
1927fa11-ec08-4773-a0f0-b932281dfdcb
4fb93fdb-81d1-4b17-ad14-40c7b383003e
c3cacbde-6a16-45eb-898e-3c8512e95e37
3618b780-4773-4e5b-9bf4-828b011ec667
299097a1-9b45-4e02-b6b9-48499ae9c5c0
c4bb2a47-9ad6-41f3-bfef-35b777add212
e165e17a-9b55-4c9a-9243-c68b502d760e
2876cfa0-1f43-45f6-bc6a-61cdd311a312
b70f4421-f373-47af-bf22-cd2cd6238b85
0565464d-1cc5-4922-9956-5ebcf5b13015

**Comment by hermanAlexCordero** [comment]
Some Equipment ID fields in the LIVD table are missing causing OBX-18 to be blank.  I'm investigating what should be the proper action to correct that.

**Comment by anshulkumar-usds** [comment]
Anshul to fu with NJ what to place in OBX-18 if we don't have the bar code number

**Comment by Adrian-Brewster** [comment]
Adrian responded to NJ to see what they would like in OBX-18 when we dont have a bar code number

**Comment by anshulkumar-usds** [comment]
Per NJ, if the equipment ID field on the LIVD table is not populated, leave this field blank.

**Comment by Adrian-Brewster** [comment]
NJ responded and confirmed that they would like to leave the field blank if the equipment ID field is not populated. @hermanAlexCordero @anshulkumar-usds

**Comment by hermanAlexCordero** [comment]
Working with @MauriceReeves-usds for next steps.  Contemplating defaulting the field to blank.

**Comment by MauriceReeves-usds** [comment]
@anshulkumar-usds @Adrian-Brewster I never got to get back with @hermanAlexCordero about this before he went on vacation. Let's just blank OBX-18 for NJ for now. This is a settings change and we could roll this out fairly quickly.
