### ISSUE TITLE
NJ - ORC-12.3 field length too long

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3607]
On 12/22, NJ reported errors due to ORC-12.3 where the field value was too long: 47 > 30

```ceee838a-dda1-4b40-8a3a-4c5158ae31f7 ```               PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.OrderingProvider[0].GivenName        Field too long: 47 > 30

The data is: 
|1215934393^SOMERSET VALLEY VISITING NURSE ASSOCIATION INC.^SOMERSET VALLEY VISITING NURSE ASSOCIATION INC.^^^^^^NPI&2.16.840.1.113883.4.6&ISO^^^^NPI|

**Comment by anshulkumar-usds** [comment]
@MauriceReeves-usds wanted to surface this issue as it's been open for a while.

**Comment by oslynn** [comment]
Test: curl -X POST -H 'client: simple_report' -H 'Content-Type: text/csv' --data-binary '@/home/jorg3/Desktop/CDC/sample-data/pdi-covid-19-78d580bb-f426-43f8-a8ca-d319f338ee4d-20211221172001.csv' localhost:7071/api/reports

**Comment by oslynn** [comment]
Acceptance Criteria:
- View the output HL7 file and check the  OR-12-3 field.  It should truncate to 30 characters per HL7 standard as shown below:
![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/1eea5608-bd79-4ea0-a1d4-8eedbf80edef)

**Comment by jorg3lopez** [comment]
@oslynn @Adrian-Brewster @anshulkumar-usds Test results resubmitted today (02/11/2022)
file name:
covid-19-ee5e39a0-4b0c-4f18-8896-e95606ff96ef-20220210232102

**Comment by anshulkumar-usds** [comment]
2/11: Checking with NJ to validate changes in the file.

**Comment by anshulkumar-usds** [comment]
2/15: Check with NJ again. If NJ does not reply by EOD 2/16, consider the issue closed and move the changes to PROD.
