### ISSUE TITLE
State, Tribal, Local, and Territorial (STLT): enhancement to daily-data and report-detail pages

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3608]
ON HOLD until pipeline team's refactoring of historyfunction.kt is done.

Epic used to bundle enhancements to current STLT feature on daily-data and report-details pages

## Problem Statement
As a person working at a public health authority, I need pagination/sorting/filtering on detailed-report and daily-data pages. I also need a summary list of facilities and senders in production and in test modes. Later, I’ll need summary, descriptive stats of data coming from reportstream.

**Comment by chris-kuryak** [comment]
All issues complete.
