### ISSUE TITLE
Content: Create ReportStream Template for OKTA Activation Email

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3634]
## Problem Statement
As an organization who wants to activate my OKTA account in order to gain access to ReportStream, I would like to see some ReportStream branding in the email that is sent to me for account activation.

## Possible Solutions
- Create email template for ReportStream based on the Simple Report one but with Reportstream branding

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/9539bc18-4f86-430c-a96b-042fcbcb4738)

**Comment by chris-kuryak** [comment]
Old. I will be taking lead on setting up new RS Okta instance in #4573.
