### ISSUE TITLE
ReportStream OKTA Account Activation

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3635]
## Problem Statement
As a user who wants to activate my OKTA account in order to gain access to ReportStream, I would like to see branding and content related to ReportStream and easily get an account.

## What you need to know
- Currently, the OKTA account registration process references only Simple Report and sends users who activate their account to the Simple Report website.
https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1643997933186/ca218dcd309f6d54f73e522a56c741a77f8b9366?sender=ud3aa760e30b39bcf436d4473

- Now we have just gotten new Okta domains for ReportStream. [See Set Up, Configure, and Migrate ReportStream OKTA Instance#4573](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4573)

## Long Term Goals are TBD
Option 1:
- We want to move away from OKTA
- OKTA will remain for authentication
- Authorization/permissions will need to be built and NOT in OKTA (long term goal)

Option 2:
- Stay with OKTA for authentication and permissions

## Acceptance criteria
As a user I can:

Be notified by an RS-branded email that I have a new account
Log in with credentials provided RS team
Reset my password within the app
Be notified by an RS-branded email that my password has been updated
Things users should no longer see/get:
- Default Okta pages when navigating the site
- Default Okta emails based on actions taken
- Simplereport branded content and logo

**Comment by sean-usds** [comment]
Spike detailing the solution approach for the Epic: https://github.com/CDCgov/prime-reportstream/issues/3682

**Comment by loripusey** [comment]
@loripusey @rachelhanster We need to rethink this epic in light of getting away from OKTA

**Comment by HeatherRienks** [comment]
Per Design Tix Review on 12/19/22, we will keep this epic

**Comment by chris-kuryak** [comment]
I will be taking on leading the new Okta Instance creation. May repurpose this epic in the future.

**Comment by chris-kuryak** [comment]
Will be using a different epic #4573 to track our migration to a new Okta instance. Closing all these issues/epic they will naturally arise in the future as we set up our new RS Okta instance.
