### ISSUE TITLE
Content: Create ReportStream Template for OKTA Multi-Factor Authentication Email

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3637]
## Problem Statement
As an organization who wants to activate my OKTA account in order to gain access to ReportStream, I would like to see some ReportStream branding in the email that is sent to me for multi-factor authentication activation.

## Possible Solutions
- Create email template for ReportStream

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/2f3f02d7-69a6-48ee-983e-e31ecc28bc44)

**Comment by chris-kuryak** [comment]
Old. I will be taking lead on setting up new RS Okta instance in #4573.
