### ISSUE TITLE
Link Activated Users to ReportStream instead of Simple Report

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3639]
## Problem Statement
As an organization who wants to activate my OKTA account in order to gain access to ReportStream, after I have activated my account I would like to be directed to the ReportStream website instead of the Simple Report website so that I don't have to hand-enter the URL for ReportStream.

**Comment by sean-usds** [comment]
This will be part of https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3717
