### ISSUE TITLE
send empty batch file

### ISSUE THREAD

**Issue by clediggins-usds** [CDCgov/prime-reportstream#3641]
### User Story
As a receiver, I want the option to receive a batch file at my scheduled time even if there are no records either every time I am scheduled to batch or no more than once per 24 hours.

### Description
We need to allow a setting for a receiver to get 'empty' batch files at their scheduled batch time if there are no records to send. This will require updates to the Receiver.kt file, settings in the database, and an update to BatchDeciderFunction. Each receiver also needs a second setting added to indicate if they would like an empty file every time they are scheduled to batch or no more frequently than once per 24 hours.

When the receiver gets CSV, send a file with all headers but no records.
When the receiver gets HL7, send a file with FHS, BHS, BTS, FTS records

### Acceptance Criteria
* A receiver can be set to 'receive empty batches'
* If there are no records for a receiver who is set to receive empty batches at that receiver's batch time, they still receive a file (it will be empty).
* If there are no records for a receiver who is *not* set to receive empty batches at that receiver's batch time, they receive nothing (as currently is the case).
* If a receiver is set to receive an empty batch file no more than once per 24 hours, they should not get an empty more frequently than once every 24 hours even if they are set to batch more frequently.
* If a receiver is set to get an empty on every batch run, generate one no matter how frequently the batch is set to run.
* empty test case needs to be added to the smoke tests
* if receiver is CSV, send headers with no rows
* if receiver is HL7, send FHS, BHS, BTS, FTS
* will SendFunction object to sending an empty file?
* will sftp object to sending an empty file?

### Dev Notes
- Settings table will need to be updated to allow for new setting
- 'receiveEmptyBatch'.  Receiver.kt will need to be updated as well
- BatchDecider will need to check this property alongside where it currently checks for maxBatchSize to determine if the receiver should have 'batch' run for them even if there are no records.
- BatchFunction will need to be changed to also check the 'receiveEmptyBatch' property, then write out a file when it batches for a receiver regardless of if there are records or not (due to batchDecider, it will only run for receivers that should actually get a file, empty or otherwise)

**Comment by jimduff-usds** [comment]
Let's have both BatchDecide and BatchFunction check the receiveEmtpyBatch flag, just to be doubly sure.

**Comment by clediggins-usds** [comment]
This card did not move through the pipeline on the board as it should have. It is now merged to master.
