### ISSUE TITLE
Synthesis of Receiver Research - Colorado

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3646]
## Problem statement
Synthesize findings from calls to assess the baseline and need as a receiver of data including their need and opportunity for piloting a CSV upload feature. 

## What you need to know
What are they currently doing - what is the current process (practices and actions) for receiving data, what is the time and labor involved. 

## Acceptance criteria
- Synthesis of 
    - Current process including description of what they are doing, who is involved, the time, time, labor, technology, other resources and costs involved 
    - Any current templates, list of fields, and validation rules
    - Needs and pain points 
    - Common errors 
    - List of senders that would speak with us and/or be good pilot/would they like to get a demo

## To do
- Tailor facilitation guide, notetaker, recoding (get notes clean and transcript), thematic and practice analysis, share here.

Review: 
Share synthesis with designers and product for feedback

**Comment by victorialb-usds** [comment]
- Current process including description of what they are doing, who is involved, the time, time, labor, technology, other resources and costs involved [SEE SYNTHESIS below]
- Any current templates, list of fields, and validation rules [See folder]
- Needs and pain points
- Common errors
- List of senders that would speak with us and/or be good pilot/would they like to get a demo See here: https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B5C057B81-BEDB-4FE0-941D-A519206701A2%7D&file=Data%20sharing%20pilot_csv_cohorts.xlsx&action=default&mobileredirect=true


Folder: https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Experience%20Research/CSV%20flat%20file%20upload%20December%202021%20ongoing/Colorado%20discovery%20research%20flat%20file%20upload%20December%202021?csf=1&web=1&e=gv78Tw

Call #1 Synthesis: 
https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Experience%20Research/CSV%20flat%20file%20upload%20December%202021%20ongoing/Colorado%20discovery%20research%20flat%20file%20upload%20December%202021/2021.12.23%20Call%20Two%20_Nancy%20%26%20Alyson/Colorado_discovery%20session_synthesis_call%20two_12.23.21.docx?d=w2d050dc80ef54a9398f44acebbfcca99&csf=1&web=1&e=oUydLW
Call #2 Synthesis: https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Experience%20Research/CSV%20flat%20file%20upload%20December%202021%20ongoing/Colorado%20discovery%20research%20flat%20file%20upload%20December%202021/2021.12.23%20Call%20Two%20_Nancy%20%26%20Alyson/Colorado_discovery%20session_synthesis_call%20two_12.23.21.docx?d=w2d050dc80ef54a9398f44acebbfcca99&csf=1&web=1&e=VHuEOP

Synthesis across states can be found here: https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BAD839AB7-96AE-4661-960C-8674E870C693%7D&file=CSV%20Flat%20file%20upload%20comparison.pptx&action=edit&mobileredirect=true&cid=9d1f4b66-57af-457c-838d-4b259f018a03

**Comment by victorialb-usds** [comment]
@loripusey @rachelhanster for your qa and can close.
