### ISSUE TITLE
Synthesis of Receiver Research - New Mexico

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3647]
## Problem statement
Synthesize findings from calls to assess the baseline and need as a receiver of data including their need and opportunity for piloting a CSV upload feature. 

## What you need to know
What are they currently doing - what is the current process (practices and actions) for receiving data, what is the time and labor involved. 

## Acceptance criteria
- Synthesis of 
    - Current process including description of what they are doing, who is involved, the time, time, labor, technology, other resources and costs involved 
    - Any current templates, list of fields, and validation rules
    - Needs and pain points 
    - Common errors 
    - List of senders that would speak with us and/or be good pilot/would they like to get a demo

## To do
- Tailor facilitation guide, notetaker, recoding (get notes clean and transcript), thematic and practice analysis, share here.

Review: 
Share synthesis with designers and product for feedback

**Comment by victorialb-usds** [comment]
https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Pilots/CSV%20Uploader/Experience%20Research_CSV%20flat%20file%20upload%20December%202021%20ongoing/New%20Mexico%20discovery%20research%20flat%20file%20upload%20December%202021/2022.1.4.NMDOH_discovery%20call_Carmela%20and%20Jordyn/New%20Mexico_discovery%20call%20%232_synthesis_1.4.21.docx?d=w420ca7b9a1a5441d82ca57e516ca958f&csf=1&web=1&e=l36oS8

Close this ticket. Can reopen if/when we re-engage with NM.
