### ISSUE TITLE
Synthesis of Receiver Research - California

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3648]
## Problem statement
Synthesize findings from calls to assess the baseline and need as a receiver of data including their need and opportunity for piloting a CSV upload feature. 

## What you need to know
What are they currently doing - what is the current process (practices and actions) for receiving data, what is the time and labor involved. 

## Acceptance criteria
- Synthesis of 
    - Current process including description of what they are doing, who is involved, the time, time, labor, technology, other resources and costs involved 
    - Any current templates, list of fields, and validation rules
    - Needs and pain points 
    - Common errors 
    - List of senders that would speak with us and/or be good pilot/would they like to get a demo

## To do
- Tailor facilitation guide, notetaker, recoding (get notes clean and transcript), thematic and practice analysis, share here.

Review: 
Share synthesis with designers and product for feedback

**Comment by victorialb-usds** [comment]
AC summary: 
https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BAD839AB7-96AE-4661-960C-8674E870C693%7D&file=CSV%20Flat%20file%20upload%20comparison.pptx&action=edit&mobileredirect=true&cid=9d1f4b66-57af-457c-838d-4b259f018a03

Synthesis: 
https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Experience%20Research/CSV%20flat%20file%20upload%20December%202021%20ongoing/California%20pilot%20site_discovery%20research%20flat%20file%20upload%20December%202021/CA%20PHD/Discovery%20Call%2012.28.21_Vanessa%20and%20Elliason_CADOPH/CA_DPH_PHD%20STLT_CSV%20upload%20pilot%20discovery%20research%20call_%2012.28.2021%20-%20synthesis.docx?d=wd8112ea8d33c433fa988ab0f2ef8f15d&csf=1&web=1&e=qb1ifj

Current process: https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Experience%20Research/CSV%20flat%20file%20upload%20December%202021%20ongoing/California%20pilot%20site_discovery%20research%20flat%20file%20upload%20December%202021/CA%20PHD/California%20public%20health%20dept_current%20flat%20file%20process?csf=1&web=1&e=EzTEHD
