### ISSUE TITLE
Synthesis of Receiver Research - Louisiana

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3649]
## Problem statement
Synthesize findings from calls to assess the baseline and need as a receiver of data including their need and opportunity for piloting a CSV upload feature. 

## What you need to know
What are they currently doing - what is the current process (practices and actions) for receiving data, what is the time and labor involved. 

## Acceptance criteria
- Synthesis of 
    - Current process including description of what they are doing, who is involved, the time, time, labor, technology, other resources and costs involved 
    - Any current templates, list of fields, and validation rules
    - Needs and pain points 
    - Common errors 
    - List of senders that would speak with us and/or be good pilot/would they like to get a demo

## To do
- Tailor facilitation guide, notetaker, recoding (get notes clean and transcript), thematic and practice analysis, share here.

Review: 
Share synthesis with designers and product for feedback

**Comment by victorialb-usds** [comment]
Synthesis of all states in here: https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BC4BA15FA-62A2-4847-916C-625A2C95BE20%7D&file=_TO%20USE_Receiver%20CSV%20Flat%20file%20upload%20comparison_Internal.pptx&action=edit&mobileredirect=true

**Comment by victorialb-usds** [comment]
Link to folder with Louisiana data here: (note that Louisiana did not have a discovery call like the other states that were conducted in December 2021 and January 2022; they had technical assistance calls that we integrated research into. https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Pilots/CSV%20Uploader/z_Experience%20Research_CSV%20flat%20file%20upload%20December%202021%20ongoing/Louisiana%20discovery%20research%20flat%20file%20upload%20December%202021?csf=1&web=1&e=PuuuKW
