### ISSUE TITLE
Date Validation and Parsing Fails If Date Value Contains Trailing Spaces

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#3650]
While working with A1H, it was discovered that dates that have a trailing space don't pass date validation and parsing. We need to add logic to trim leading and trailing spaces before attempting to cast to date.

FYSA: @rhood23699 @MikeC-A6 @anshulkumar-usds @loripusey

**Comment by loripusey** [comment]
@MauriceReeves-usds I noticed in the python code from Colorado validation that they automatically trim leading & trailing spaces from all values; should we do the same?

**Comment by Adrian-Brewster** [comment]
Jorge reviewing.
