### ISSUE TITLE
Create Web Page for CSV Uploader Guide

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3666]
## Problem Statement
As the Experience Team, we need to make the CSV Uploader guide publicly accessible so that prospective Senders can easily access it.

## Recommendation
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/c456de9d-b8c8-492f-80fc-4e8ef34841c9)

## To do 

- [x] Review and edit guide content
- [x] Create JSON from upload guide documentation content
- [x] Build new page structure
- [x] Edit navigation to fit in new content
- [x] Move content into markup
- [x] Review with eng
- [x] Review with product/design
- [x] Review with O&O team

**Comment by loripusey** [comment]
@sean-usds @BerniXiongA6 Rachel has recommended that we put out the CSV Uploader Guide as a web page in ReportStream this week and have it deployed to production by 1/5. This takes priority over anything else you are working on at the moment. I don't think that it needs to be navigable (yet) but we should be able to provide a link to the page in production that we can provide to our prospective senders. Please work together to get this guide out and let me know what blockers you may have. Thanks!

cc: @rachelhanster

**Comment by drew-usds** [comment]
@loripusey already have a working branch for this and will be working with @BerniXiongA6 today to flow our current content into it.

**Comment by drew-usds** [comment]
Content is up on [staging](https://staging.reportstream.cdc.gov) and have iterated through a couple PRs as of Fri 1/7.

**Comment by drew-usds** [comment]
Doing last checks today based on what's on staging. Have put up a couple PRs (#3729 and #3732) and have one last draft PR up at #3754.
