### ISSUE TITLE
PA Reports STRAC Sending Invalid Unicode Character 0x19 in Some Fields

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#3669]
Reported to STRAC before the New Year. Waiting to hear back. Created the ticket to track that we're waiting to hear back from STRAC and CHOP on this.

FYSA: @anshulkumar-usds @Adrian-Brewster

**Comment by Adrian-Brewster** [comment]
Mo to follow up with STRAC. If needed, we can strip it out.

**Comment by Adrian-Brewster** [comment]
Closed. Mo is opening new ticket for resends.
