### ISSUE TITLE
Re-configure receiver setting to conform with new filters

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#3681]
Jim made improvements to the receiver filtering settings. https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/playbooks/how-to-use-filters.md

The changes Jim made did not break the current settings. But the settings need to be adjusted to use the new toolings.

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/3681?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS

**Comment by brick-green** [comment]
@brandonnava The filters are going to be different for the universal pipeline. But the covid pipeline won't be decommissioned for a while so I think there's still value in finishing this ticket.

**Comment by brick-green** [comment]
Reached out to SR on this. They are going to discuss internally to create a work plan.

**Comment by brick-green** [comment]
Removed senders and receivers from local organizations file then refactored unit and integrations tests.
