### ISSUE TITLE
IL - Non-Covid specific LOINCS populating in Prod

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#3686]
**Describe the bug**
From IL's perspective, it appears they are receiving Flu + COVID panel test results, when they should only be receiving the COVID results from that panel test. 

**Expected behavior**
Only COVID specific LOINCS should populate

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60d1eba7caf0775fd79203f8/90ee3667-ea13-407e-8759-d2f588150406)

**Comment by anshulkumar-usds** [comment]
IL wants to use LOINC 94533-7.

Can this change be made globally across SimpleReport, or just for IL in RS? @MauriceReeves-usds

**Comment by anshulkumar-usds** [comment]
@MauriceReeves-usds was there any follow up work from RS on this? SR has made the update on their side.

**Comment by anshulkumar-usds** [comment]
Fix in SR complete. IL confirmed this is no longer an issue on their side for this specific device of LOINC
