### ISSUE TITLE
NJ - Message Failures in Secondary Feed

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#3687]
**Describe the bug**
NJ has written in and provided a list of messages that have failed to populate in their secondary feed with a list of reasons.  A snapshot has been included below. Most show missing required feed as the reason for the messages failing. 

**Impact/Expected Behavior**
The organization would like us to address these issues so the messages are more complete and can route to prod. 

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60d1eba7caf0775fd79203f8/05f43483-9f7e-4565-accf-043bb37a0ea7)

**Additional context**

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 is assume this along the OTC defaults you're working on. Can you share any update if your updates will address what NJ is looking for as well?

**Comment by anshulkumar-usds** [comment]
1/24: Checking with NJ to see their default preferences, and what would it take to consumer OTC in their primary feed.

**Comment by brick-green-agile6** [comment]
spot checked a few of those files and they were all OTC results

**Comment by anshulkumar-usds** [comment]
Anshul contacted NJ on 1/24 to understand their OTC delivery preferences. Still waiting to hear back from NJ.
