### ISSUE TITLE
Router build occasionally fails because it can't find java

### ISSUE THREAD

**Issue by cwinters-usds** [CDCgov/prime-reportstream#3693]
Here's an [example action where this happened](https://github.com/CDCgov/prime-reportstream/runs/4715485385?check_suite_focus=true).

Exit code 255 typically means the command cannot be found. Which is weird because the previous lines are output from gradle... which uses java.

**Comment by carlosfelix2** [comment]
This is an issue with the Docker container running in Github Actions being slow and taking longer than the default read timeout set for the Fuel HTTP client library.  Found one more piece of code with no updated timeout and fixed in #3580.
