### ISSUE TITLE
Review extending Okta claims/tokens with SimpleReport team for possible side effects

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#3703]
As part of the work to support a single schema for all CSV uploaders, I am going to discuss adding custom claims to Okta so we can include additional sender information that we then extract and use to drive processing on submission.

## Notes
This impacts the rate at which we can onboard senders who use the standard schema.

**Comment by loripusey** [comment]
@MauriceReeves-usds what is your timeline for this work?
FYI: @TomNUSDS @drew-usds (for other interactions w/ OKTA & Simple Report)

**Comment by loripusey** [comment]
@MauriceReeves-usds is this ticket still needed given the new solution that was put in place last week?
cc: @rachelhanster
