### ISSUE TITLE
Ambulunz - Onboarding Operations

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3710]
Placeholder for onboarding sender to RS

**Comment by anshulkumar-usds** [comment]
1/4: Met with sender and shared demo and programmers guide. Awaiting sample data from sender

**Comment by Adrian-Brewster** [comment]
@Adrian-Brewster to follow up with sender

**Comment by sarahnw** [comment]
It's been 6 months, I'm closing this out as no response from the sender.
