### ISSUE TITLE
VT - HL7 Encoding for Ampersand in MSH-4

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3712]
On 1/6/22, VT reported that several facilities with an ampersand (&) in their name are showing up with non-relevant encoded characters in test messages.

Example: Springfield Probation & Parole, Newport Probation & Parole

Please share a test message with VT on their TEST folder prior to rolling to production.

Issues is related to what IL also reported here:
https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3015

**Comment by jorg3lopez** [comment]
Update: These are the ordering facility names:

**Burlington Probation & Parole
Leland and Gray Union Middle & High School
Mt. Abraham Union Middle & High School
Newport Probation & Parole
St. Albans Probation & Parole**

**Comment by anshulkumar-usds** [comment]
Checked with VT on 1/18 for any messages that need to be resubmitted

**Comment by anshulkumar-usds** [comment]
@jorg3lopez VT confirmed they do not need any resubmissions. Please confirm once the fix is in prod, and I can notify VT.

**Comment by anshulkumar-usds** [comment]
Awaiting PR - deployment on Tuesday

**Comment by anshulkumar-usds** [comment]
@jorg3lopez can you please confirm if this is fixed

**Comment by anshulkumar-usds** [comment]
Resubmission to VT not needed per VT's preference. Fix in prod as an RS global change.
