### ISSUE TITLE
Spike -- Research how to use split off RS activation email

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#3718]
## Problem statement
When users are added to Okta, we need a way to send SR users the current activation email, and RS users the email being created by https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3634

Okta Workflows can probably handle this task. It is likely we can determine the email sent by the name of the user's Okta group (all RS user groups begin with "DH")

## Acceptance Criteria
- A detailed solution to the problem above

**Comment by loripusey** [comment]
**Notes from Tom:**

- SR (SimpleReport) uses an Okta Preview account for all non-production work to stage/test Okta changes and reduce risk for production.
- Tim can add our @cdc.gov account to the Okta Preview so we can start using it.
- We should migrate all non-production to start using this account.

**History of Okta customization in Simple Report.**
- Two dedicated full time engineers (@Emma Stephenson (SAN, she/her) and @Nick Clyde (he/him)) worked it exclusively for a couple of months.
- Custom solutions for signup flow that involved custom React and Java (server) calling a REST api to get working.
- If they had to do it over, they might do some things differently (e.g. sending email via Okta or Postman, storing more per-user settings in our own database, etc).
- Costs are getting very high as more users are being added. May become an issue in the future.

**Concerns**:
- Both SR and RS depend on Okta accounts being set up in a specific way. Any accounts created for ReportStream will not automatically be able to onboard with SimpleReport and require "hand tweaking".
- Investing too much more dev that generates more Okta lock-in.

**Notes from Tim:**
- backend code
    - https://github.com/CDCgov/prime-simplereport/blob/main/backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserAccountCreationController.java
- FE okta signup code:
   - https://github.com/CDCgov/prime-simplereport/tree/main/frontend/src/app/login
   - https://github.com/CDCgov/prime-simplereport/tree/main/frontend/src/app/accountCreation
- Related signup flow stories
   - https://www.chromatic.com/library?appId=60a556a7c807cc0039ec6786&groupPrefix=App%2FAccount%20set%20up (requires signup and permission granting)

**Action items out of this meeting:**
- We have access to it now and it makes a lot of sense to start using it reserving the Production Okta purely for the Production environment.
- The recommendation from RS experience was to NOT put more permissions into Okta but into our own database and use Okta for just login authentication.
:arrow_right: 

Need to identify who can make this an official decision (or officially reject) and who will work on them. @Rick Hawes @Maurice Reeves @Jim Duff

**Comment by rick** [comment]
![image](https://user-images.githubusercontent.com/6259/150222560-af1f655f-4b86-43c9-8227-2e4318b6d1c0.png)

cc https://github.com/rick/you-rang/issues/1

**Comment by loripusey** [comment]
@TomNUSDS I moved this to de-prioritized based on our new direction (i.e. not OKTA) for account activation
@rachelhanster
