### ISSUE TITLE
Colorado Sender Research - SDI - baseline

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#3723]
## Problem statement
We have done discovery calls with States and now need to understand the processes for submitting data to understand the other side of the user dyad. We will also always assess if senders are a good fit for ReportStream CSV upload pilot or SR. 

- [x] SDI 

## What you need to know
(1) Email template to send to sender or to PHD to send to senders: https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/doc2.aspx?sourcedoc=%7BCBA4C4BA-4191-4B90-8084-7C0590979B82%7D&file=Document.docx&action=default&mobileredirect=true&cid=d8f5cc22-1cd1-4af9-ace5-97d9fa8a1ebf

(2) Template for discovery call if doing discovery call [note that we are attaching baseline research data collection to kick off calls for the most part]
https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Experience%20Research/CSV%20flat%20file%20upload%20December%202021%20ongoing/Sender_CSV%20upload%20pilot%20discovery%20research%20template_as%20of%2012.30.%202021.docx?d=w753c4748533e4e08b3f882939c8319df&csf=1&web=1&e=aCENbt

(3) Template for Usability Research with Senders
https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Experience%20Research/CSV%20flat%20file%20upload%20December%202021%20ongoing/Sender%20Experience%20Prototype%20-%20Usability%20Study%20Brief%20Notes.docx?d=w78564931887c42db99b90912b5f8e920&csf=1&web=1&e=eeOOdr
(4) Log status in
(4a) Product Log:
https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B5C057B81-BEDB-4FE0-941D-A519206701A2%7D&file=Data%20sharing%20pilot_csv_cohorts.xlsx&action=default&mobileredirect=true&cid=06ab645b-0edd-44f2-bb0b-0ec674150f89
(4b) Research Log:
https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B6ECC6EA3-5D73-41BA-BCBA-AF01D84EA643%7D&file=CSV%20Upload%20Pilot%20Research%20Data%20Tracking%20Log%20November%202021%20ongoing_VLB.xlsx&action=default&mobileredirect=true&cid=4fb78082-d86b-4bb8-a193-947bbde5dd23

## Acceptance criteria

 locate existing notes on sender or create new set of notes in CSV upload pilot folder, experience folder, in the state of referral
 experience does kick off call with sender to get baseline information (see excel) and takes notes in ongoing notes
 enter information into excel
 share insights in slack including user stories and into microsoft lists
EXCEL:
https://cdc.sharepoint.com/❌/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B431D9FDE-C408-43E7-B643-E1D30652155C%7D&file=CSV%20pilot%20cohort%201_Pre%20Post%20Data.xlsx&action=default&mobileredirect=true

- [ ] Check log status in Product Log is updated:
https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B5C057B81-BEDB-4FE0-941D-A519206701A2%7D&file=Data%20sharing%20pilot_csv_cohorts.xlsx&action=default&mobileredirect=true&cid=06ab645b-0edd-44f2-bb0b-0ec674150f89

- [ ] Log Status in Research Log:
https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B6ECC6EA3-5D73-41BA-BCBA-AF01D84EA643%7D&file=CSV%20Upload%20Pilot%20Research%20Data%20Tracking%20Log%20November%202021%20ongoing_VLB.xlsx&action=default&mobileredirect=true&cid=4fb78082-d86b-4bb8-a193-947bbde5dd23

## To do
- [x] Get list of senders from state
- [x] Prepare and send email to sender to schedule call
- [x] Prepare (i.e. do background reaching & tailor facilitation guides) and conduct discovery session (include product on call 1 - 2 people)
- [ ] Synthesize discovery session and ID actionable insights and next steps for sender
- [ ] Create zenhub tickets based on outcomes of the Discovery Session

**Comment by loripusey** [comment]
[https://app.zenhub.com/files/304423150/0f452c1b-505f-44c3-9249-60d44c9a38da/download](https://app.zenhub.com/files/304423150/0f452c1b-505f-44c3-9249-60d44c9a38da/download)

**Comment by victorialb-usds** [comment]
We had one call with COVIDCheck CO. Waiting for more to come through via RS inbox and having the kick-off calls with them. Noting that CO is also moving people to simple report too at this time. COVIDCheck CO notes in sharepoint in pilots folder CSV Upload. RH followed up with other 2 referred senders and we have not heard back.

**Comment by victorialb-usds** [comment]
I attended a Q and A call with SDI yesterday and inserted some of the baseline questions we are looking to answer. I documented what I was able to gather in this document; https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B431D9FDE-C408-43E7-B643-E1D30652155C%7D&file=CSV%20pilot%20cohort%201_Pre%20Post%20Data.xlsx&action=default&mobileredirect=true

Notes can be found: https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B27A59B05-4CDA-452E-A4B8-9462B9210691%7D&file=SDI_CSV%20Uploader%20Pilot_Feburary%202022%20ongoing%20notes%20VLB.docx&action=default&mobileredirect=true&DefaultItemOpen=1

Can reach back out to see if they would do a 30 minute call to answer more questions and perhaps give feedback on designs @drew-usds what do you think. Process is changing and adapting.

**Comment by victorialb-usds** [comment]
@rachelhanster @loripusey as per the research integration discussion yesterday we can go back to them and ask for a 30 minute discovery call to get more detailed information and perhaps show some designs. This would change the AC on this.

**Comment by victorialb-usds** [comment]
They want to wait to do follow up call. 
Research debt is to make sure info is in the excels and microsoft lists. cc @inkandsound

**Comment by victorialb-usds** [comment]
Baseline information entered into: 
https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B431D9FDE-C408-43E7-B643-E1D30652155C%7D&file=CSV%20pilot%20cohort%201_Pre%20Post%20Data.xlsx&action=default&mobileredirect=true&cid=11ff6849-4668-4c53-9f1c-a363c809f112

@rachelhanster let me know if you have any questions or have specific questions for your deck.
