### ISSUE TITLE
SPIKE - Leverage SimpleReport knowledge surrounding user claims in Okta

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#3724]
Context: #3078

SimpleReport has a test Okta account that we should reach out and attempt to leverage. This way, we can make changes that don't risk affecting our production environment. Additionally, SimpleReport seems to have attempted setting up custom claims via custom user attribute conditions. We should learn about how they did this.

**Comment by bgantick** [comment]
I don't think this is relevant anymore, given that we have an OktaPreview instance now
