### ISSUE TITLE
NTE.1 is blank

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#3725]
## Problem statement
I added a "comment" column to the standard CSV schema.  The NTE segment is being created, but as shown below, the NTE.1 doesn't have a Set ID.

NTE||L^Ancillary (filler) department is source of comment^HL70105|Test Comment|RE^Remark^HL70364^^^^2.5.1

## What you need to know
For testing, use the branch "OO/StdCSVSchema-Modifications Based on Testing".  Attached is a test.

[StandardCSV-Test.csv](https://github.com/CDCgov/prime-reportstream/files/7839140/StandardCSV-Test.csv)

## Acceptance criteria
Each NTE.1 segment is sequentially numbered starting with 1.

**Comment by rhood23699** [comment]
Note, I marked this is a high priority.  The Experience Team is moving quickly to add new Senders to the Standard CSV Upload, so this problem may appear soon than later.

**Comment by oslynn** [comment]
Rick Hood, would you please give steps to reproduce the bug?

**Comment by rhood23699** [comment]
Sorry, Below is the CLI to run.  The HL7 output will go into the junk directory.  Attached is the test file to use.

./prime data --input result_files/StandardCSV-Test.csv --input-schema manualupload/csvuploadertest-covid-19 --output-dir junk --route

[StandardCSV-Test.csv](https://github.com/CDCgov/prime-reportstream/files/7834150/StandardCSV-Test.csv)

**Comment by oslynn** [comment]
@Rick Hood where can I find the manualupload/csvuploadertest-covid-19?

**Comment by rick** [comment]
![giphy-downsized-large (3)](https://user-images.githubusercontent.com/6259/150223185-fc6d4449-d201-429d-91e6-c49939e947a6.gif)

cc https://github.com/rick/you-rang/issues/1

**Comment by oslynn** [comment]
Need to check with @MauriceReeves-usds to see if this issue still need to be fixed.

**Comment by rick** [comment]
![hithere](https://user-images.githubusercontent.com/6259/189667902-336b65a0-bd0d-4aae-a5b1-d05286eb6a3b.gif)

**Comment by oslynn** [comment]
This ticket can be close.  We don't need to fix NET.1 any longer.  If needed, we can reopen the ticket later.  So far, there is no need and SLTLs never complain about this field.
