### ISSUE TITLE
CA - Siskiyou County School Messages Nacking

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#3731]
**Describe the bug**
CDPH reported that messages from SimpleReport for Siskiyou County Schools are nacking. This is likely due to the following truncation issue: OBX-23.1 is over the 50 character limit for performing lab and OBR-16.3 is over the 30 character limit for provider first name (and also the same for ORC-12.3 provider first name).

These messages need to be corrected and resent. 

ERR||OBX^6^23^1^1^|102^Data type error|E|Component size restriction exceeded in segment 6:OBX. Field 23, repetition 1, component 1 is larger than data structure 2.5.1CA:XON permits it to be.
ERR||OBX^6^23^1^1^|102^Data type error|E|Component size restriction exceeded in segment 6:OBX. Field 23, repetition 1, component 1 is larger than data structure 2.5.1CA:XON permits it to be.
ERR||OBR^5^16^1^3^|102^Data type error|E|Component size restriction exceeded in segment 5:OBR. Field 16, repetition 1, component 3 is larger than data structure 2.5.1CA:XCN permits it to be.
ERR||ORC^4^12^1^3^|102^Data type error|E|Component size restriction exceeded in segment 4:ORC. Field 12, repetition 1, component 3 is larger than data structure 2.5.1CA:XCN permits it to be.
ERR||OBR^5^16^1^3^|102^Data type error|E|Component size restriction exceeded in segment 5:OBR. Field 16, repetition 1, component 3 is larger than data structure 2.5.1CA:XCN permits it to be.
ERR||ORC^4^12^1^3^|102^Data type error|E|Component size restriction exceeded in segment 4:ORC. Field 12, repetition 1, component 3 is larger than data structure 2.5.1CA:XCN permits it to be.
ERR||OBR^5^16^1^3^|102^Data type error|E|Component size restriction exceeded in segment 5:OBR. Field 16, repetition 1, component 3 is larger than data structure 2.5.1CA:XCN permits it to be.
ERR||ORC^4^12^1^3^|102^Data type error|E|Component size restriction exceeded in segment 4:ORC. Field 12, repetition 1, component 3 is larger than data structure 2.5.1CA:XCN permits it to be.
ERR||OBX^6^23^1^1^|102^Data type error|E|Component size restriction exceeded in segment 6:OBX. Field 23, repetition 1, component 1 is larger than data structure 2.5.1CA:XON permits it to be.

FYSA: @mlighdc @brick-green-agile6 @anshulkumar-usds

**Comment by brick-green-agile6** [comment]
I started pulling these results then realized I don't have any boundary on how far back in time to go. I don't anyone has monitored the NACKs close enough to pull a date range. Going to ask CA.

**Comment by brick-green-agile6** [comment]
Ellaison said "It’s actually just for any of theirs that errored." I assume she means the NACKs. @Adrian-Brewster Is there anyway for me to access the NACK files?

**Comment by Adrian-Brewster** [comment]
I don’t have the log in credentials. @anshul should be able to share them
with you.

**Comment by mlighdc** [comment]
@brick-green-agile6 we can also get a sense from SimpleReport and how many messages they have sent.

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 creds to access the nack portal is here:
https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Onboarding%20%26%20Operations/CA%20Onboarding%20Operations/CA%20ACK%20NACK%20Inbox%20Creds.docx?d=w824f2384e0b3477e81c8444234e9ee39&csf=1&web=1&e=X3UamD

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 to confirm with CA on timeframe and message IDs that need to be resent.

**Comment by anshulkumar-usds** [comment]
Next steps for resolution:
1. Truncate OBX-23.1 and ORC-21.1 to 50 chars
https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4360

2. Truncate OBR-16.3 and ORC-12.3 to 30 chars
https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4361

3. Check back with CA on corrected resubmissions

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 Both dependencies have been resolved. I will follow up with CA on next steps for resubmission.

**Comment by anshulkumar-usds** [comment]
3/3: CA is checking to see which, if any, resubmissions are needed.

**Comment by anshulkumar-usds** [comment]
3/17: No response from CA after multiple attempts. Closing for now.
