### ISSUE TITLE
Sales funnel process considerations for managing touch points with prospective RS users (senders)

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#3733]
## Problem statement

A ReportStream team member who is responsible for outreach to prospective users needs to be able to manage all the touch points of the sales funnel to avoid presenting end users/customers with an inconsistent and disorganized experience / initial impression of our team and potentially cause us to miss out on acquiring more senders.
 
## What you need to know

We can populate this section with any relevant docs or info, but here's what we know so far:
- Currently, Research and PHDs work together to engage the prospective end user (sender) via email
-- Email could originate from PHD
-- Email could originate from ReportStream team
- Senders reply via email to express their interest/intent to participate
-- Reply could go directly to PHD
-- Reply could go directly to RS team
-- Reply could go to both (if both parties CC'ed)
- It's unknown whether we track (outside of the Sent email folder) a Sender once they go through our sales funnel (who has been contacted, when they were contacted, the status of the touch point, how many touch points have been made, whether they never contacted RS, etc.)
- As RS team talks to more prospective users, the lack of having a CRM tool or sales funnel process could add some risks and cause us to miss out on opportunities, lose traction, etc.

## Acceptance criteria

- [ ] tbd

## To do

- [ ] tbd

**Comment by rachelhanster** [comment]
Closing as problem no longer exists due to low volume of prospective API senders and STLTs
