### ISSUE TITLE
Log error on any send_error that gets picked up by PagerDuty

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#3736]
### AC

An log message appears in the logs for any error result in send_error, (but not necessarily for send_warning).

Implement this by having Send errors insert a unique string into the logs that will trigger PagerDuty.  Could include a class name if needed.

**Comment by whytheplatypus** [comment]
https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/azure/SendFunction.kt#L94-L99 catches all errors, a re `throw` at the end of this would expose those errors to our tooling.

Exposing this case https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/azure/SendFunction.kt#L136-L142 as a thrown error will allow the previous step to make the error visible to our tooling.

**Comment by jimduff-usds** [comment]
Our original way to do this didn't work - throwing an exception at the "top level" of an Azure function triggers the queue retry mechanism.  For SendFunction we don't want the queue retry mechanism since we wrote our own.   We could turn this off with a function.json file, but we are currently autogenerating those files during the build, so that's a larger change than anticipated.

A better solution is to see if PagerDuty can trigger off of a specific message in the logs.

**Comment by jimduff-usds** [comment]
PagerDuty can look for a unique string.   The use case in this ticket should not be at a level that triggers pagerduty to call someone, but we might want this in the future.

Use an existing Logger level?  This will require getting rid of the Azure "context" logging, and using the regular log4j logger.  TBD to use ERROR or FATAL.  Be sure there's enough context in that message - which receiver, what was the error, etc. 

Ask @cwinters-usds to trigger based both on ERROR messages and initially the classname or other unique distinguishing string as well.

Kill the old PR.

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/3736?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @smythe5 @TurkeyFried @whytheplatypus

**Comment by jimduff-usds** [comment]
Implementation is that all calls to `logger.fatal(...)` will trigger PagerDuty alerts.
The keyword is secreted away in `src/main/resource/log4j2.xml`
