### ISSUE TITLE
Many schemas appear to have missing TrackingElements

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#3737]
We use the tracking elements internally to provide traceability to the user.  If a schema does not define a tracking element, we can't do tracing.  We also print out the tracking element in logs and in error messages.   So a missing tracking element, while allowed, is a  bad thing.

./prime generate-docs flags the following as not having tracking elements:

$ ./prime generate-docs | grep Tracking
12:26:46.117 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema covid-19: TrackingElement is empty
12:26:46.207 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema co/co-covid-19-redox: TrackingElement is empty
12:26:46.224 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema hl7/hl7-ingest-covid-19: TrackingElement is empty
12:26:46.263 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema experity/experity-covid-19: TrackingElement is empty
12:26:46.266 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema experity/cuc-al-covid-19: TrackingElement is empty
12:26:46.269 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema experity/guc-la-covid-19: TrackingElement is empty
12:26:46.308 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema ipatientcare/ipatientcare-covid-19: TrackingElement is empty
12:26:46.310 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema ipatientcare/reddyfmc-la-covid-19: TrackingElement is empty
12:26:46.317 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema mt/mt-covid-19: TrackingElement is empty
12:26:46.328 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema non-standard/all-in-one-health-ca-covid-19: TrackingElement is empty
12:26:46.333 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema oh/oh-covid-19: TrackingElement is empty
12:26:46.340 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema pa/pa-covid-19-hl7: TrackingElement is empty
12:26:46.343 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema pa/pa-covid-19-redox: TrackingElement is empty
12:26:46.349 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema sample/fed1-sample: TrackingElement is empty
12:26:46.351 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema sample/phd1-sample: TrackingElement is empty
12:26:46.352 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema sample/phd2-sample: TrackingElement is empty
12:26:46.354 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema standard/standard-covid-19: TrackingElement is empty
12:26:46.364 [main][1] WARN  gov.cdc.prime.router.DocumentationFactory - Schema vt/vt-covid-19: TrackingElement is empty

### Acceptance criteria

If this is by design, then narrow the warning so that it only prints when there's a real issue.
If this is not by design, then add a tracking element to each schema above.

**Comment by rhood23699** [comment]
@jimduff-usds Some of the schemas are mine, but what does "TrackingElement is empty mean?

**Comment by rhood23699** [comment]
@jimduff-usds I added trackingElement to the schemas that I created (Experity, iPatientCare, All-In-One schema and Std CSV schema.
