### ISSUE TITLE
Change batch size to a minimum of 500 records

### ISSUE THREAD

**Issue by brick-green-agile6** [CDCgov/prime-reportstream#3774]
Some STLTs have a batch size of 100 records. With volume increasing a batch size that small is resulting in an issue where data is being received faster than the batch can be created. Example provided was MN needed to have ~8400 results batched. 84 batches were created but in the time that the batches were made new results arrived. The bathes pulled the 8400 most recent results leaving multiple older results out.

Another solution to that problem is in place to order results by oldest first. But this may still be a good idea. Opening ticket for discussion.

**Comment by MauriceReeves-usds** [comment]
Closing this because #4147 supersedes it. We have set the batch size down to 100 now.
