### ISSUE TITLE
Incorporate OTC identifiers in LIVD table creation

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#3778]
This ticket is to track conversation and work with the LIVD committee to include OTC identifiers in the LIVD table creation

**Comment by brick-green-agile6** [comment]
LIVD team is going to add two columns initially: isOTC, isHome. isProcorted will take a bit more time to be included. All three of the extra columns will only be included in the file that the LIVD team sends to ReportStream. Those fields will not be included in the file that is posted to the CDC website. That will required authorization which may take some time.

**Comment by RickHawesUSDS** [comment]
Great to read about this progress.

**Comment by anshulkumar-usds** [comment]
On 1/19/2022, ReportStream shared a proposal to add the following four identifiers to the LIVD spreadsheet:
```
isAuthorizedForOTC
isAuthorizedForProctoredUse
isAuthorizedForHome
isAuthorizedForSerialUse
```
We also suggested using the following values to mark these as true, false or unknown based on the HL7 Standard https://hl7-definition.caristix.com/v2/HL7v2.5.1/Tables/0136
```
Y
N
UNK
```
During the meeting, the LIVD group agreed to adding the identified for OTC and Home-use. Other two will take more time.

On 2/7/2022, Anshul checked with the team to see if they have further questions or need additional information from us. Awaiting response.

**Comment by anshulkumar-usds** [comment]
Received confirmation from Riki that the team is working on this and will have a PRIME-facing version of this mapper available by next week. The public facing version will not be altered as it is a standardized version used by other entities.

**Comment by anshulkumar-usds** [comment]
Checking with FDA on further guidance

**Comment by anshulkumar-usds** [comment]
3/1: Checked with FDA again. Awaiting reply.

**Comment by anshulkumar-usds** [comment]
3/31: Shared FDA's feedback with LIVD team. The LIVD team needs additional guidance from FDA. Call setup on 4/6 to discuss next steps.

**Comment by anshulkumar-usds** [comment]
5/11: @brick-green-agile6 met with the LIVD team. They have agreed to start including the granular OTC identifiers in the PRIME specific LIVD mapper.

**Comment by anshulkumar-usds** [comment]
5/19: @brick-green-agile6 Now that the LIVD mapper meets our expectations, what is the process to get that incorporated into our local mapper. Let me know if a separate ticket is needed to track this work.
