### ISSUE TITLE
California - Core Bio Labs - Baseline Research

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3784]

**Comment by loripusey** [comment]
@rhood23699 @victorialb-usds @rachelhanster @drew-usds

**Comment by victorialb-usds** [comment]
Here is where I am going to track where things are. https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B1653409F-6449-4D8C-8707-958767522CAD%7D&file=Sender%20Pipeline%20Onboarding%20Tracker.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1 once they are in production I would like to do check-in call and then at 45 days post production and at these check-ins maybe do some UI testing. CC: @drew-usds @inkandsound

**Comment by victorialb-usds** [comment]
Information is logged in here: Information entered into tracking sheet: https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B431D9FDE-C408-43E7-B643-E1D30652155C%7D&file=CSV%20pilot%20cohort%201_Pre%20Post%20Data.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1&cid=f5f8bd31-6856-436a-b8c2-e7629f60d9ca

Specific notes in here: call 1/25; email from CADOPH; https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BDC5BA733-8548-40B5-A897-DE197A425016%7D&file=CA_SenderCore_Biolabs_CSV%20upload%20pilot%20discovery%20research_1.25.22.docx&cid=579372c3-c8e9-46b6-add4-87092db311de
