### ISSUE TITLE
Transition CA to SOAP from SFTP

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#3786]
CA is able to process ACK/NACK via SOAP more easily than SFTP. The majority of large senders to CA use SOAP for precisely this reason.

* [ ] soap credentials for CA acquired
* [ ] update the organization.yml
* [ ] update staging settings table
* [ ]  Got credentials?
* [ ] Tested ELR connection locally?
* [ ] Tested ELR connection from Azure?
* [ ] Has the receiver been sent at least one test file?
* [ ] Has the receiver signed off on file formatting?
* [ ] Has the receiver confirmed receipt of the data?
* [ ] Have the files processed successfully?
* [ ] Are we in production?
* [ ] Update the production settings

**Comment by MauriceReeves-usds** [comment]
@brick-green-agile6 is the SOAP for just ACK/NACK or for sending test results as well?

**Comment by brick-green-agile6** [comment]
@MauriceReeves-usds test results as well

**Comment by brick-green-agile6** [comment]
added SOAP information that optum provided to keybase: prime_dev_ops/state_info/CA/SOAP/CCRS_Preprod_Resources

**Comment by brick-green-agile6** [comment]
CA reported that they do not want to move to SOAP until the ACK/NACK workflow is in place

**Comment by sarahnw** [comment]
CA is going to move to REST likely by the end of this year. I'm closing this.
