### ISSUE TITLE
ifNotPresent Mapper returns "null" instead of blank

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#3793]
## Problem statement
When using the schema configuration below, if the field "testing_lab_street2" is blank, then value shown in the resulting HL7 output shows the value of "null" instead of a blank value.

    - name: ordering_facility_street2
      csvFields: [{name: ordering_facility_street2}]
      mapperOverridesValue: true
      mapper: ifNotPresent($mode:lookup, **testing_lab_street2**, ordering_facility_name_temp, ordering_facility_street_temp)

## What you need to know
For testing:
   - Use the attached CSV file.
   - Make sure the code shown above is uncommented in the schema ./metadata/schemas/upload-covid-19.schema
   - Run the CLI "./prime data --input result_files/StandardCSV-Test.csv --input-schema manualupload/csvuploadertest-covid-19 --output-dir junk --route".  Note csvuploadertest-covid-19.schema extends upload-covid-19.schema.
   - Check the ORC.22.2 on all HL7 messages created in the junk folder to make sure all have blank instead of null.  Note, I believe testing_lab_street2 in the first row of the CSV has a value, so it will not be null.

[StandardCSV-Test.csv](https://github.com/CDCgov/prime-reportstream/files/7854712/StandardCSV-Test.csv)

## Acceptance criteria
 - If testing_lab_street2 is blank, then ordering_facility_street2 written to the ORC.22.2 must be blank.

**Comment by loripusey** [comment]
@jimduff-usds @JGreen-Fearless @smythe5 
Based on the decision that was made on 12/28 (see [decision log](https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B3C88D2E6-7BD6-446C-804E-812FF3297FB7%7D&file=Decision%20Log_v2.xlsx&action=default&mobileredirect=true&cid=6542787a-353c-46c4-a091-1fde879176a9)), custom mapper work should be done by the Pipeline team so I am reassigning this work to the Pipeline team; please work with @rhood23699 as this appears to be a high-priority item
cc: @rachelhanster @sean-usds
