### ISSUE TITLE
Receivers: ordering and duplication of reporting facilities on web app

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#3794]
As a public health department employee, I need better visibility into reporting facilities. Specifically, I want to more easily discover and identify a reporting facility to see its specific metadata on test reports.

Acceptance Criteria

- Sort list of reporting facilities in alphabetical order
- Each reporting facility is listed once with associated descriptive metadata

Right now the ordering of the reporting facilities on the web app is not sorting by facility name first, and the list is not aggregating properly, so it can be difficult to see which facilities are included in a file because things are out of order and facilities repeat.

Examples from IL:

![Screen Shot 2022-01-12 at 8.35.31 AM.png](https://images.zenhubusercontent.com/5ff4880376fe251547594b05/1b944767-20cc-4fdf-973a-d5ad543d489a)![Screen Shot 2022-01-12 at 8.34.58 AM.png](https://images.zenhubusercontent.com/5ff4880376fe251547594b05/39017adf-75df-40a5-8013-e9546cb29e50)

**Comment by TomNUSDS** [comment]
@drew-usds Q: should there be a date/time column in this list?

**Comment by sethdarragile6** [comment]
hey Mo! I mean @MauriceReeves-usds . Dumb question- how do I get to the page from whence the screenshots were taken? I selected il-phd in staging and in production and clicked around and could not find it for the life of me @TomNUSDS @loripusey
