### ISSUE TITLE
California - Naval Health Clinic Lemoore (NHCL)- Baseline Research

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3796]
## Problem Statement
Naval Health Clinic Lemoore (NHCL) has requested to be onboarded to ReportStream and the CSV Uploader.

## Contact Info
Name: Michelle Neuroth
Job title: Lab Manager
Organization: Naval Health Clinic Lemoore (NHCL)
Email address: michelle.r.neuroth.mil@mail.mil
Phone number: 904-509-4697

## Request Email
[https://app.zenhub.com/files/304423150/8bf12ce7-5386-4108-9788-0419e43f4b3a/download](https://app.zenhub.com/files/304423150/8bf12ce7-5386-4108-9788-0419e43f4b3a/download)

- [x] locate existing notes on sender or create new set of notes in CSV upload pilot folder, experience folder, in the state of referral (e.g. Colorado) make a new folder State_sender_name of new sender
- [x] experience does kick off call with sender to get baseline information (see excel) and takes notes in ongoing notes
- [x] enter information into excel
- [x] share insights in slack including user stories and into microsoft lists (see here https://cdc.sharepoint.com/teams/USDSatCDC/Lists/Test%20test/AllItems.aspx?env=WebViewList)
EXCEL:
https://cdc.sharepoint.com/❌/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B431D9FDE-C408-43E7-B643-E1D30652155C%7D&file=CSV%20pilot%20cohort%201_Pre%20Post%20Data.xlsx&action=default&mobileredirect=true

**Comment by loripusey** [comment]
@rhood23699 @victorialb-usds @anshulkumar-usds @Adrian-Brewster 
Naval Health Clinic Lemoore has requested a ReportStream account for the CSV Uploader Pilot. Please proceed with onboarding them.
cc: @rachelhanster @drew-usds @sean-usds

**Comment by rhood23699** [comment]
@loripusey Have they completed the TOS?

**Comment by victorialb-usds** [comment]
Here is where I am tracking where things are. https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B1653409F-6449-4D8C-8707-958767522CAD%7D&file=Sender%20Pipeline%20Onboarding%20Tracker.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1 once they are in production I would like to do check-in call and then at 45 days post production.

**Comment by victorialb-usds** [comment]
Relates to #3975
