### ISSUE TITLE
Add value set for patient country based on on ISO3166 values

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#3800]
We need to add the ISO3166 data set as a value set in the application. 

Based on our testing, PID-11-6, which is the patient country defaults to `USA`. We need to add a field to the simple report schema to get that field from them, and then pass that through.

FYSA: @Adrian-Brewster @anshulkumar-usds @mlighdc @emmastephenson @LGFranklin

**Comment by MauriceReeves-usds** [comment]
An alternate list of the countries is here: https://hl7-definition.caristix.com/v2/HL7v2.5.1/Tables/0399

PID-11-6 is a three character code, and nothing else.

**Comment by Adrian-Brewster** [comment]
@oslynn @brick-green-agile6 @jorg3lopez @jbiskie please review today so we can close this out.
