### ISSUE TITLE
Small content updates on sender/csv documentation

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#3807]
## Problem statement

Got some additional feedback on content after deploy. Need to make some small tweaks for clarity.

## Acceptance criteria

- Include some extra language to make our ID-proofing/PHD recommendation process clearer. 
- Further define "pilot program" where we have that outlined/labeled

## To do

- [x] Add ID/PHD rec lang to `/overview`
- [x] Add pilot program def to csv doc pages
- [x] ALSO! Add note about col orders not being specific. Just has to have the right values.

**Comment by BerniXiongA6** [comment]
1.14.2022: @drew-usds and @BerniXiongA6 collab'ed today to update content on local environment. Drew will submit PR. Moving to Review/QA.
