### ISSUE TITLE
OH - Missing LOINC Codes

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#3809]
**Describe the bug**
Ohio reached out to let us know they received more files with missing LOINC codes. They need to be corrected and resent. 

**Affected Files**
File: CDCPRIME_20220110161613
```
898233f4-d300-4745-8965-55e8183dc8f2
d6b95c73-ba3e-426b-924b-947853a33f57
a807e087-5b25-4684-bddc-f264054756bb
eb6f4a8a-14fc-402c-b540-9e12e60471f3
```

File: CDCPRIME_20220110181525
```
3a7ab66f-40c3-4f1f-a61d-dc62155759ba
8f58f6f8-fe71-4195-8b5d-fbbd0fbf8ef4
95148391-c374-4f67-be7b-065305da6540
```

File: CDCPRIME_20220110221603
```
a33d1a56-4e87-45ed-958f-50c5b67d3b62
69559b1b-9ea2-4d42-a816-a0e0b4781ff6
cf2f002e-375a-4c1f-97bf-055b69b63804
```

File: CDCPRIME_20220111001534
 
`8638b9ac-c274-48fc-9a0c-adbcc91d1528`

**Comment by Adrian-Brewster** [comment]
Additional Message IDs: 
e6f89214-d3f5-493b-9d43-2d5d97b63f83
40fcd127-cf5a-4053-845c-8780c25a60cb
0b84610e-423c-4374-9f83-f5d617c9d3a8
3240244c-c520-4008-88e0-3fcccac6a2f2
40fdf04c-9159-40e2-bd33-6a9196c24a31
a1640088-5c7b-48d2-a0e4-d8cdb84f90d6
ad14b0a0-7297-4390-a698-62ab94ff613d
2b17c051-903b-49dd-90c8-ed27cf2e3cc8
4600fef5-d723-4cf4-97e4-0512c2cee7a1
7c791e2e-fb6b-487d-b97d-ba80c23d0317
b1edcd6f-192e-4ec8-a165-fc38bf6109f0
d10a36af-97b5-4ef1-b7dc-51bc6b22c751
713ef93a-a275-4496-bb37-2f0156fca02c
47eab9f4-1390-455f-a533-481edcd1821e
640ab6d6-24e6-4d84-b5ba-e11df4349b38
d70974e2-54dc-4ae4-b221-10213bd12412
cc2e399b-a486-49ea-8c5c-d5743648e635

**Comment by Adrian-Brewster** [comment]
f1eaa276-ba6f-4377-b09f-7891120e3589
7ecbab92-1a7d-4b23-8786-b77dd9abaf5a
4841955d-0e6b-4585-a72c-4b7ebc4b0b01
eec0905c-5307-4b88-940c-375357fb8fb2
 
25e51bd7-2d76-44e9-a387-9678abbfe70e
c8ce2467-afda-4b95-8efe-6722d974f441
5d23c5a4-ac10-4db1-9e9f-39e1b03d8239
a807e087-5b25-4684-bddc-f264054756bb
318286a9-3908-47c1-b0bb-21819bfde8ac
688080db-69e5-4ece-9a85-0f8f72085294
99a4cdf7-bc4e-40ab-a4a4-3a9a4a83fd1f
27ec4b68-cbe1-4a48-92c0-0beb6f26ee03

**Comment by MauriceReeves-usds** [comment]
@Adrian-Brewster @anshulkumar-usds looking at the data above, there's a few different things happening. The following IDs were already resubmitted by SimpleReport, and should be okay. They were part of the BD issue we identified earlier.

```
898233f4-d300-4745-8965-55e8183dc8f2
8f58f6f8-fe71-4195-8b5d-fbbd0fbf8ef4
95148391-c374-4f67-be7b-065305da6540
a807e087-5b25-4684-bddc-f264054756bb
d6b95c73-ba3e-426b-924b-947853a33f57
```

The following IDs are for iHealth and need to be resubmitted by SR so they are correctly mapped:
```
0b84610e-423c-4374-9f83-f5d617c9d3a8
25e51bd7-2d76-44e9-a387-9678abbfe70e
2b17c051-903b-49dd-90c8-ed27cf2e3cc8
318286a9-3908-47c1-b0bb-21819bfde8ac
3240244c-c520-4008-88e0-3fcccac6a2f2
3a7ab66f-40c3-4f1f-a61d-dc62155759ba
40fcd127-cf5a-4053-845c-8780c25a60cb
40fdf04c-9159-40e2-bd33-6a9196c24a31
4600fef5-d723-4cf4-97e4-0512c2cee7a1
47eab9f4-1390-455f-a533-481edcd1821e
4841955d-0e6b-4585-a72c-4b7ebc4b0b01
640ab6d6-24e6-4d84-b5ba-e11df4349b38
688080db-69e5-4ece-9a85-0f8f72085294
69559b1b-9ea2-4d42-a816-a0e0b4781ff6
713ef93a-a275-4496-bb37-2f0156fca02c
7c791e2e-fb6b-487d-b97d-ba80c23d0317
7ecbab92-1a7d-4b23-8786-b77dd9abaf5a
99a4cdf7-bc4e-40ab-a4a4-3a9a4a83fd1f
a1640088-5c7b-48d2-a0e4-d8cdb84f90d6
a33d1a56-4e87-45ed-958f-50c5b67d3b62
ad14b0a0-7297-4390-a698-62ab94ff613d
b1edcd6f-192e-4ec8-a165-fc38bf6109f0
c8ce2467-afda-4b95-8efe-6722d974f441
cc2e399b-a486-49ea-8c5c-d5743648e635
cf2f002e-375a-4c1f-97bf-055b69b63804
d10a36af-97b5-4ef1-b7dc-51bc6b22c751
d70974e2-54dc-4ae4-b221-10213bd12412
e6f89214-d3f5-493b-9d43-2d5d97b63f83
eb6f4a8a-14fc-402c-b540-9e12e60471f3
```

This single record is for a FlowFlex test. It also needs resubmitted by SR:
`8638b9ac-c274-48fc-9a0c-adbcc91d1528`

Finally, IM needs to resend these two results:
```
27ec4b68-cbe1-4a48-92c0-0beb6f26ee03
5d23c5a4-ac10-4db1-9e9f-39e1b03d8239
```

Please let me know if you have any questions.

**Comment by anshulkumar-usds** [comment]
1/25: OH was notified of current status of resubmissions.

**Comment by anshulkumar-usds** [comment]
OH confirmed that resubmission from SR as of 1/14 have been received, and no further action is needed for the following messages:

```
898233f4-d300-4745-8965-55e8183dc8f2
8f58f6f8-fe71-4195-8b5d-fbbd0fbf8ef4
95148391-c374-4f67-be7b-065305da6540
a807e087-5b25-4684-bddc-f264054756bb
d6b95c73-ba3e-426b-924b-947853a33f57
```

**Comment by anshulkumar-usds** [comment]
The ImageMover submissions are blocked by https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4033

**Comment by anshulkumar-usds** [comment]
1/28: After updates from SR team, OH was notified that all SR resubmissions were completed on 1/25. Awaiting confirmation of delivery from OH.

ImageMover submission still blocked by issue above.

**Comment by anshulkumar-usds** [comment]
Still need ImageMover to resubmit the following:
```
27ec4b68-cbe1-4a48-92c0-0beb6f26ee03
5d23c5a4-ac10-4db1-9e9f-39e1b03d8239
```

I will follow up with sender.

**Comment by anshulkumar-usds** [comment]
Covered under the resubmits from 1/30
