### ISSUE TITLE
Look at Colorado's validation python script

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3818]
## Acceptance Criteria
- Document the validation rules that exist in the [script](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStre[…]3%20Call%20Two%20_Nancy%20%26%20Alyson?csf=1&web=1&e=IfVHWI
)
- Share findings with the team

**Comment by victorialb-usds** [comment]
Going back to the slack post after CO call, I think that Rick Hawes might have looked at it too perhaps whoever does this can circle back to the slack and synch up with whoever looked at it.

**Comment by chris-kuryak** [comment]
Closing by committee. WA is already onboarded, and this research will come up in the future.
@drew-usds @lizzieamanning
