### ISSUE TITLE
Synthesis/discussion on common errors from calls & research notes

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3819]
## Acceptance Criteria
- Compile from research notes a list of common errors observed by receivers and encountered by senders when submitted test results
- Share findings with team

**Comment by victorialb-usds** [comment]
Common errors can be found https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7Bc4ba15fa-62a2-4847-916c-625a2c95be20%7D&action=edit&uid=%7BC4BA15FA-62A2-4847-916C-625A2C95BE20%7D&ListItemId=322806&ListId=%7B603E4F84-8849-480D-80A9-5BFB0272FB18%7D&odsp=1&env=prod

**Comment by victorialb-usds** [comment]
To do: add Washington
