### ISSUE TITLE
CO - Update to ELR Requirements 

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#3820]
**Describe the bug**
Colorado emailed the ReportStream inbox to inform us of some changing requirements on their end. These changes will go into affect January 25, 2022, and any messages that are missing the following data elements will be rejected and require resubmission.
Sending Facility Name
   Last name
   First name
   Date of birth
   Gender
   AccessionId
   Test_LOINC
   Test_Name
   Result_Text
   State

**Impact**
Messages will fail.

**Comment by mlighdc** [comment]
@LGFranklin - FYI I don't think the SR team needs to do anything as Sex Assigned at Birth is already required field on the SR side.

**Comment by MauriceReeves-usds** [comment]
@anshulkumar-usds @Adrian-Brewster Reviewing this, I think we'll be okay as well. All of these fields are in the messages we provide.

**Comment by Adrian-Brewster** [comment]
Fields are already populated. Closing out
