### ISSUE TITLE
Spike -- Scope Eng work needed to build custom authorization

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#3833]
## Problem Statement
Presently ReportStream relies on Okta for authorization and authentication. We should investigate how much work it would be to build our own solution to authorization (data access permissioning) and only use Okta for authentication (logging in). Things to consider:
- What would make it easiest to move off Okta if it becomes necessary in the future?
- What happens if ReportStream and SimpleReport have different patterns for authorization?
- If we move to a custom solution for authorization, what would the migration plan look like?

**Comment by doug-s-nava** [comment]
i'm going to close this, as moving off of okta hasn't come up since I started in May. If it comes up again we can make a new ticket
