### ISSUE TITLE
Unicode to ASCII in HL7 Messages

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#3845]
## Problem statement
Our HL7 message are UTF-8 encoded.  Some STLTs (CA-PHD & IL-PHD) convert UTF-8 to ASCII which causes the extended ASCII values for diacritics (Latin letters) to be converted to "?" or whatever they coded for their state; thus results do not automatically match to existing patient results in the STLT's surveillance system.

## What you need to know
(1) CA-DPH has requested that we convert the diacritics to English letters, and we agree this is the best solution.  Below are a couple of options, but the engineers need to decide which is best.

Option 1:  Removing non-ascii is nice concise `.replace(/[ÀÁÂÃÄÅ]/g,"A") .replace(/[ÈÉÊË]/g,"E") .replace(/[Î]/g,"I") .replace(/[Ô]/g,"O") .replace(/[Ù]/g,"U") .replace(/[Ç]/g,"C")` but it's a LOT of rescanning the same string... It might be better to do a first pass/check IF there are any non-ascii characters in a string via a simple grep before running the replaces.

Option 2:  Logic for removing diacritics from letters (i.e. turning unicode into ascii): https://stackoverflow.com/questions/18123501/replacing-accented-characters-with-plain-ascii-ones

(2) There should be a setting on the Receiver, maybe replaceDiacritics, that defaults to false, but can be set to true on the Receiver who want the diacritics replaced.

## Acceptance criteria
 - [ ] Diacritics are converted to English letters if the Receiver setting, replaceDiacritics: true

**Comment by jorg3lopez** [comment]
Update: code in production already.
