### ISSUE TITLE
VT - Canadian Patient Address

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3848]
Until the enhancements for accommodating Canadian addresses can be tested, VT is requesting the following:

1. Remove the default values of "NA" and "00000" in PID-11.4 and PIC-11.5, respectively, and send blank values when they are unknown.

2. Also update the mapping such that when Canada is selected as the country in SimpleReport, PID-11.6 = "CAN", instead of "USA" - as it's currently being provided.

cc: @LGFranklin @MauriceReeves-usds

**Comment by anshulkumar-usds** [comment]
Per VT, we can leave the county blank for Canadian addresses

**Comment by anshulkumar-usds** [comment]
1/28: Shared an update with VT that initial testing of sample data yielded positive results. We should look to prioritize this for next week.

**Comment by anshulkumar-usds** [comment]
2/9: VT reported that "USA" is coming in as the country under PID-11

**Comment by emmastephenson** [comment]
This is on SimpleReport to fix - I thought we were passing the country information to our test event exports, but looks like we're only storing it internally. How quickly would VT like this resolved?

**Comment by anshulkumar-usds** [comment]
Thanks @emmastephenson. We haven't promised any timelines to VT. Soon-ish is great!

**Comment by emmastephenson** [comment]
Soon-ish we can do! :)
