### ISSUE TITLE
CA - Resend Simple Report Results Oct 1 - Nov 11

### ISSUE THREAD

**Issue by brick-green-agile6** [CDCgov/prime-reportstream#3857]
Need to pull simple report files for california that were sent between Oct 1 and Nov 11 with these CLIA numbers:

'14D2207204',
'05D2230613',
'05D2209018',
'25D2099997',
'65D2191411',
'14D2240498',
'14D2241370',
'14D2240427',
'14D1077656',
'50D2182786',
'31D2204774',
'36D0863477',
'14D2232511',
'05D0715882',
'32D0653271',
'53Z0000000',
'14D2056249',
'14D2209943',
'14D2192855',
'21D2216975',
'14D2215684',
'14D0878962',
'32D0537339',
'03D2159846',
'03D0532131',
'03D2232412',
'14D2238583'

**Comment by anshulkumar-usds** [comment]
Updated issue title to conform to our template

**Comment by anshulkumar-usds** [comment]
Accessions shared with CA on 1/21
'b207a398-947b-42bd-9fe6-0be815b93a45
'15c87acb-c267-4ff5-99e4-45e744d9b5d2.
'919daf12-e911-4b3b-9dcb-86dc3f1b366e
'be71c779-2976-4ed0-83cc-827aece2fa00
'eebcdb36-8073-4b31-985e-dc1c6ffc12e3

All of the examples posted here are from simple report so the MSH-4.2 value is CDPH0000085.

**Comment by anshulkumar-usds** [comment]
Brick followed up with CA on 1/28 - awaiting response from CA

**Comment by Adrian-Brewster** [comment]
@brick-green-agile6 if we haven't heard back from CA, lets close this out.
