### ISSUE TITLE
CSV Uploader - Accept multiple formats for type: DATETIME

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#3860]
## Problem statement
CA-DPH wants Date & Time if the Senders can provide it.  Senders using the Std CSV format, provide date & time in multiple formats.  RS doesn't accept multiple formats for type: DATETIME formats; thus we can't accept multiple Date / Time formats as we currently do with type: Date.

## What you need to know
The current type: DATE validation accepts the (DatePattern, "M/d/yyyy", "MMddyyyy", "yyyy/M/d", "M/d/yyyy HH:mm", "yyyy/M/d HH:mm") and converts them to the internal RS DATE format; thus allowing a schema to accept multiple Date formats with no customization per Sender.  **FYI.....Aurora can provide details on how the work for type: DATE**

**For Testing,**
 - Use the attached CSV test file
 - Modify the column order_test_date by replacing the date with each of the requested date formats.
 - In the schema ./metadata/schemas/upload-covid-19.schema, change the type: to DATETIME for the element: order_test_date.
 - Run the CLI "./prime data --input result_files/StandardCSV-Test.csv --input-schema manualupload/csvuploadertest-covid-19 --output-dir junk --route"

[StandardCSV-Test.csv](https://github.com/CDCgov/prime-reportstream/files/7905654/StandardCSV-Test.csv)

## Design notes:
When implementing a fix, make sure not to duplicate code.

## Acceptance criteria
- [ ] For type: DATETIME, RS accepts the following (DatePattern, "M/d/yyyy", "MMddyyyy", "yyyy/M/d", "M/d/yyyy HH:mm", "yyyy/M/d HH:mm") and converts them to the RS DATETIME format.

 - [ ] **Not required.**  If possible, it would be great if both type: DATE and type: DATETIME could also accept the DatePattern: M/d/yyyy HH:mm AM/PM".  Example, "1/20/2022 9:30 AM" and "1/20/2022 2:30 PM"

**Comment by loripusey** [comment]
@rhood23699 would this involve creating a new custom mapper for date/time similar to the one for date?

**Comment by rhood23699** [comment]
No, it is not a Mapper change.  @ahay-agile6 can explain where the change needs to be made.

**Comment by rhood23699** [comment]
@ahay-agile6 @loripusey Lori, since Aurora is going to be out, I've moved this to Carlos and the Pipeline Team.

**Comment by oslynn** [comment]
@rhood23699, may I have the command line to duplicate the issue?
