### ISSUE TITLE
VT - Missing LOINC (ImageMover) and Incorrect Unit Identifier

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#3870]
Message from an out-of-state facility for a Vermont resident failed HL7 validation due to missing LOINC codes for the test performed by this facility in either OBR-4 or OBX-3. The accession # is dd91c1df-90ae-41a8-8192-33f43529fd90

It appears the device is BD Veritor System for Rapid Detection of SARS-CoV-2 & Flu A+B_Becton, Dickinson and Company (BD)

Please ensure all tests are sent with a valid LOINC code as these are required.

Another issue is the message has “yr” as the units identifier in OBX-6.1. The correct identifier for the unit years is “a”. VT is not seeing this issue in other messages. Additionally, the Age AOE is not required and if sent, must be formatted correctly.

**Comment by mlighdc** [comment]
VT responded and indicated they do not need this message resent. Anshul replied that we are working with ImageMover to resolved the field unit format issue.

**Comment by anshulkumar-usds** [comment]
Sender addressed root cause. Issue with patient age units and AOE questions is being tracked under separate ticket.
