### ISSUE TITLE
Create SSH firewall exemption for VDH SFTP

### ISSUE THREAD

**Issue by NatHillardUSDS** [CDCgov/prime-reportstream#3899]
## Problem statement

We need to create an SSH firewall exemption for the VDH SFTP server, vdhsftp.vdh.virginia.gov, in coordination with CDC. This ticket is to track that work

## What you need to know

As part of the PHDI project, we need a way for our ingest function to reach out and grab data from the Virginia Department of Health. To enable this, we need to work with the relevant parties within CDC to create the appropriate SSH firewall exemption to enable this connectivity from our VDH VNET.

## Acceptance criteria

- [ ] We are able to run a simple ingest function from within our PHDI VNET to see and list directory contents of the VDH server

**Comment by cwinters-usds** [comment]
This was approved and implemented by the firewall team on Jan 24
