### ISSUE TITLE
Naval Clinic - Lemoore - Sender Setup - Create OKTA group & OKTA account

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#3909]
## Main Objectives & Tasks:

- [x] Define the RS sender_id
- [x] Create an OKTA group for the sender_id
- [x] Create an OKTA account using the RS Registration information.
- [x] Verify OKTA account registration by the Sender.

**Comment by anshulkumar-usds** [comment]
Anshul to check with sender on okta setup

**Comment by rhood23699** [comment]
1/22/22 - Michelle confirmed she completed the account activation.
