### ISSUE TITLE
Naval Clinic - Lemoore - Sender Setup - Create Sender Settings for Staging & PROD

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#3910]
## Main Objectives & Tasks:

- [ ] Locally, create and test Settings in organizations.yaml
- [ ] Create the Staging & Production YAML settings files

**Comment by rhood23699** [comment]
Target completion is Tuesday, 1/25/22.

**Comment by anshulkumar-usds** [comment]
Anshul to check on progress for onb
