### ISSUE TITLE
Design and implement Account Activation Flow in ReportStream Okta domains

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3916]
## Problem statement
As a user, I need to be able to get an account and start using ReportStream as easily as possible. Now that ReportStream has its own Okta and Okta Preview accounts, replicate SimpleReport's account activation flow in ReportStream okta domains.

## Acceptance Criteria
- Look at the flow that Simple Report uses in OKTA
- Re-use SimpleReport's where applicable
- Introduce ReportStream's specific flow where applicable
- End user seamlessly gets an account to start using ReportStream in as few steps as possible

**Comment by loripusey** [comment]
@TomNUSDS I moved this to de-prioritized based on our new direction (i.e. not OKTA) for account activation
@rachelhanster

**Comment by BerniXiongA6** [comment]
@drew-usds do have what we need yet to close this ticket? Can I help you with creating new issues to cover other options with the new account? Lmk, thanks!

**Comment by kevinhaube** [comment]
Tagged stale. @drew-usds Can you make sure this is refreshed as needed once we have direction on Okta changes?

**Comment by HeatherRienks** [comment]
Per Eng tix mtg on 12/16, closing

Notes from Okta discussion: https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B557AFAB4-141F-42DE-B1EB-1D32F009AA5B%7D&file=Okta%20-%20transition%20from%20SimpleReport%20to%20ReportStream%20-%20Summary.docx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=rut6%40cdc.gov&ct=1669653936892&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=bf31d169-bae2-455e-8bf7-f252775d713b
