### ISSUE TITLE
API: Add paging functionality to list of reporting facilities on daily data report details page

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3919]
Problem
As a public health department employee, I want to easily understand who sent in data and associated descriptive metadata.

Acceptance criteria
- Do API work to allow this data to be paginated for this [feature](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3795)

Additional context:
- Daily data report details page (`https://reportstream.cdc.gov/report-details?reportId=xxxxxxxxxxxx`)

**Comment by kevinhaube** [comment]
Closed by release of Delivery API
