### ISSUE TITLE
Receivers: Add sorting functionality to list of reporting facilities on daily data report details page

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3920]
## Problem Statement
As a public health department employee, I want to easily understand who sent in data and associated descriptive metadata.

## Acceptance criteria
- See that I can sort the list by the following fields
    - Organization	
    - Location
    - Total Tests
    - Total positive

**Comment by TomNUSDS** [comment]
See filters in the api: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/openapi.yml

**Comment by kevinhaube** [comment]
Closed; work done in #4861
