### ISSUE TITLE
Create Process for Release Notes

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3933]
## Problem Statement
As ReportStream, we would like a better process for creating and distributing our product release notes so that we can keep the CDC informed and excite our customers.

## Things to Consider
- Someone other than an engineer writing them 
- Writing them with a marketing tone to excite customers 
- Having a process where the release notes are auto-shared with customers 
- Sharing them with Megan Lyght both to inform her/CDC and for her to use for customer acquisition

## Acceptance Criteria
- Document the current process
- Develop a process to create release notes
- Document the process
- Share the process with all teams to get feedback
- Pick a start date for the process
- Inform those who will contribute to the release notes & be responsible for their distribution

## Proposal (Draft)
https://cdc.sharepoint.com/teams/USDSatCDC/_layouts/15/doc.aspx?sourcedoc={961c0804-374b-48f9-8df0-66d3fcd3ce2c}&action=edit

**Comment by BerniXiongA6** [comment]
1.27.2021 Update: @loripusey and I met with @JosiahSiegel and @cwinters-usds to discuss the current Release Notes process. 

What we learned:
- every deployment to production, a tag is generated
- creates release notes for PRs between that tag and previous tags
- labels / categories are pulled from the logic of how the PR is written
- categories (which are manually created to automate this process) also parses titles if there are no labels
- "Uncategorized" is where untagged and unlinked PRs show up
- current deployment schedule is 2x/week, but future state could include deploying more often (e.g. with each fix)

Next steps:
Lori and my recommendation: propose a change to how we write PRs (use better labeling/categorizing)

Josiah could look into the automation to see if there's a better way to summarize categories/labels to take the guesswork out of writing our monthly summary for customers.

Lori and Berni to present our new process proposal (Feb. 1st) to POs and lead engineers.
