### ISSUE TITLE
[Bug] Settings list incorrectly updates after cloning a settings

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#3934]
**Describe the bug**
After hitting Save on a new cloned setting, it returns to the originating settings list page- however, it sometimes incorrectly shows that the original setting has been updated with your changes instead of displaying an entirely new cloned setting. When you refresh your browser at this point, it correctly displays the new cloned issue. @TomNUSDS believes the problem is related to react caching, which probably needs to be disabled or otherwise handled differently.

**Impact**
Display issue that may "freak out" the user, but all is actually well on the data-side of things.

**To Reproduce**
1. Login as an admin
2. Click on Admin->Organization Settings from the top menu
3. Click on an Org Name link of your choice
4. Click "Clone" on a setting of your choice
5. Give the setting a new name and click Save (which navigates you back to the org's settings page)
6. If you're "lucky", the setting you clone appears to be updated with the new information instead of added (see screenshot below)
7. Refresh the page, note that the setting was indeed added, and all is right with the world (see screenshot 2 below).

**Expected behavior**
Newly cloned settings should display as added upon hitting Save, without a need to manually refresh the page

**Screenshots**
Hitting Save after cloning the CLONE-ME-5 setting to CLONE-ME-6 (uh oh)
![clone bug 1.PNG](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/cf67bbd4-752b-44e9-8604-8d16ab4701b4)

After refreshing the page (oh ok whew)
![clone bug 2.PNG](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/1441cd68-2c36-4b6b-9bcb-d3d11eda9501)

**Logs**
If applicable, please attach logs to help describe your problem.

**Additional context**
Related to #3433 
also happens now when _creating_ a new setting: #3970

**Comment by loripusey** [comment]
@sethdarragile6 can you add story points to this bug?

**Comment by sethdarragile6** [comment]
@loripusey Done, Not sure why I didn't get notified of your comment 7 days ago? 🤔

**Comment by sethdarragile6** [comment]
@loripusey now I know. gmail was shoving a lot of my github stuff in the "Updates" category, which was hiding out from me in plain sight. fire me, fire me now. 🤦‍♂️
