### ISSUE TITLE
Admin Setting features part 2

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#3935]
This is a list of all things missed from doing the initial Admin Settings feature.
**_Edit this list issue in place to add more_** possible items.

Not all of the things listed here will be done, it's just more of a brainstorming/way of tracking possible features.

## MUST HAVE:
- JSON diff on save is probably a bigger deal.
   - might be partly be addressed by [3970 ](https://github.com/CDCgov/prime-reportstream/issues/3970) as well, as we are considering making the JSON diff page the default way to update AND create new settings
   - [4264](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4264)
- Allow editing of the top-most Setting for Org. [4142](https://github.com/CDCgov/prime-reportstream/issues/4121)
- Back button missing from top-most Setting for Org [4122](https://github.com/CDCgov/prime-reportstream/issues/4122)

## NICE TO HAVE:
- Some text values that only allow a subset of valid string constants should be dropdowns.
- Error notify toast UI doesn't fit. Make dialog bigger and add close box.
- Fix <Grid> layout so it resizes on mobile correctly.
- Fix navigation so that going back and forth between pages always takes you to the top of the intended page
- Future: Show history of edits (API addition)

Related to #3433

**Comment by loripusey** [comment]
@sethdarragile6 Is the brainstorming list in priority order? If not, can we prioritize the list based on Mo's needs?
cc: @rachelhanster

**Comment by sethdarragile6** [comment]
> @sethdarragile6 Is the brainstorming list in priority order? If not, can we prioritize the list based on Mo's needs? cc: @rachelhanster

It pretty much is in priority order already (that's probably intentional, thanks @TomNUSDS ). I added a couple notes to the above regarding [3970](https://github.com/CDCgov/prime-reportstream/issues/3970). The rest of the list are mostly in priority order and just small things- so perhaps we can group some of the smaller things into one story.

**Comment by loripusey** [comment]
@sethdarragile6 can you break this story up into individual tickets for the "must haves" so that we can look at during the next refinement

**Comment by sethdarragile6** [comment]
> @sethdarragile6 can you break this story up into individual tickets for the "must haves" so that we can look at during the next refinement

@loripusey this is done now, sorry for the delay. Must-haves boil down to

- #3970 
- #4121 
- #4122

**Comment by sethdarragile6** [comment]
closing, this was just a scratchpad to gather input for stories which have already been created.
