### ISSUE TITLE
Test How Having both a Simple Report OKTA group and a Sender OKTA Group affects ReportStream Use

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3945]
## Problem Statement
Some Senders want/need both a Simple Report account and a ReportStream account. We need to test these scenarios to make sure they don't affect use of ReportStream.

## Assumptions
We are not looking at API senders, only CSV senders.

## Acceptance Criteria
- Test scenarios using a single OKTA account 
   - Currently SR user, want to be a RS sender
   - Currently RS receiver, want to be a RS sender
   - Currently SR user & RS receiver, want to be a RS sender
- Test
  - Use of SR features
      - Can upload data and it is sent using my SR sender group
  - Use of RS Sender features 
      - Can upload data using my RS sender group and data is sent as my sender group
      - Can view my submission history and I see my data for my RS sender group
  - Use of RS Receiver features
      - Can view my daily data and see data sent to me as a receiver
- Summarize results
- Present to team

## Questions to answer
- Does it work
- Are there any side effects
- Are there any sign-up issues

**Comment by chris-kuryak** [comment]
This is an old issue that was never completed. As Experience PO I will be owning this migration moving forward and will update the tickets/epic as necessary.
