### ISSUE TITLE
Need a ticket related to ingest and testing of HL7 data.

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#3963]
We need to be able confirm that we can ingest HCA-style data.

This ticket needs to be split apart.   
- Testing vs Ingest Functionality
- HL7 Full ELR (aka HCA's format) vs NIH Standard Covid format.

### Other notes
- We might be able to write tests for both the new NIH standard AND full-ELR
- NIH has a standard they are developing with APHL that is meant to be a _standard HL7 for Covid-19_.
- "Full ELR" means HL7 that meets the HL7 standard for all reportable diseases.  "ORU-?"
- We originally thought about handling HCA data.   That is, our AC was:  We can ingest at least the covid test data inside the full-ELR data.  Examples of data can be found in our sharepoint site.

- This could be done with a testIntegration test.
- Do we need a distinct fullELR schema?

**Comment by jimduff-usds** [comment]
Command to generate fake HL7:

./prime data  --output-format HL7 --input-fake 1 --input-schema hl7/hl7-ingest-covid-19 --output ./build/fakehl7.hl7

**Comment by jimduff-usds** [comment]
During grooming on 1/31/2022, we said that we'll write tests on a case-by-case basis as we work on ingesting HCA data.

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/3963?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @oslynn @smythe5 @whytheplatypus

**Comment by jimduff-usds** [comment]
Closing.  Duplicate of #4138.
