### ISSUE TITLE
CSV upload: send user a confirmation email on successful upload

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#3972]
## Problem statement

Users would like to get a confirmation email when a CSV is successfully uploaded.

## What you need to know

Our existing daily email setup could probably be repurposed to fire when a user has a successful upload.

## Acceptance criteria

- [ ] When a user successfully submits a file, they get an email telling them that it was uploaded.
- [ ] Uses our standard email template
- [ ] Email copy lets a user know the file was a success.
- [ ] Email copy tells user the filename of what they uploaded
- [ ] Email copy includes top-level RS info about upload: ID, # of results uploaded, ...
- [ ] Email copy links to log in/to the submission history

## To do

- [ ] ...

**Comment by rachelhanster** [comment]
Closing as Uploader is moving to SimpleReport
