### ISSUE TITLE
Implement HTTP Transport 

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#3977]
We have received documentation for using NY’s REST API to send ELR data that way. This epic will track all of that work.

Building out the HTTP transport to connect to NY, OK, WA
NY will be our first

Due date: ASAP

Responsible eng: Tom Greene

**Comment by MauriceReeves-usds** [comment]
FYSA: @Adrian-Brewster @anshulkumar-usds @mlighdc

**Comment by anshulkumar-usds** [comment]
[https://app.zenhub.com/files/304423150/0d415fc5-ee55-44a4-a9ad-0ec461d6d083/download](https://app.zenhub.com/files/304423150/0d415fc5-ee55-44a4-a9ad-0ec461d6d083/download)

**Comment by sarahnw** [comment]
closing this in favor of the specific state onboarding epics - NY and OK
