### ISSUE TITLE
Efficiently Route Requests from End Users

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3982]
## Problem Statement
As the ReportStream support team, we need to better understand a user's support needs so that we can properly route emails to the correct internal resource(s).  

## Background Info
Currently, the general public can use the "Get in Touch" feature on the website to trigger their default desktop email system to create an email addressed to the RS inbox.

Currently, the Account Registration Guide instructs users who want to use RS to send an email to the RS inbox with subject "Register a new account: organization or testing facility"

## Acceptance Criteria
- Given I
    - Am one of these
        - Current ReportStream user
        - Prospective ReportStream user
        - General public
- When I
    - TBD..................
- Then 
    - I am prompted for the type of support I need 
        - TBD
    - My request is routed to the right internal resource based on the type of support I need

**Comment by chris-kuryak** [comment]
Closing by committee. Old issue that will come up again in the future and will be re-scoped at that time.
@drew-usds @lizzieamanning
