### ISSUE TITLE
R&D - Efficiently Route Requests from End Users

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3984]
## Problem Statement
As the ReportStream support team, we need to better understand a user's support needs so that we can properly route emails to the correct internal resource(s).  

## Background Info
Currently, the general public can use the "Get in Touch" feature on the website to trigger their default desktop email system to create an email addressed to the RS inbox.

Currently, the Account Registration Guide instructs users who want to use RS to send an email to the RS inbox with subject "Register a new account: organization or testing facility"

## How Might We's
- Easily capture RS requests in a standardized format
- Capture the detailed nature of a request 
    - Who --> what org, contact info
    - Why --> what do they want to accomplish (onboard, support, question etc.)
    - What --> what is their issue or question
    - Criticality --> how critical is the request
- Segment end users so that we can best route their request to the right internal resources
    - Sender vs. Receiver
    - API vs. CSV
    - Prospective user vs. user being onboarded vs. existing user
- Bypass the RS inbox by creating tickets directly from a request from the website and assigning/labelling them appropriately so that they are routed to the correct team boards and they can respond to them quickly

## Acceptance Criteria
- Consult with Adrian on what might work for the O&O team
- Brainstorm and evaluate potential solutions
- Present potential solutions to the team & Adrian
- Create tickets for the selected solution

**Comment by chris-kuryak** [comment]
Closing by committee. Old issue that will come up again in the future and will be re-scoped at that time.
@drew-usds @lizzieamanning
