### ISSUE TITLE
MN - Missing LOINC Codes

### ISSUE THREAD

**Issue by brick-green-agile6** [CDCgov/prime-reportstream#3998]
Good afternoon,
 
MDH received a message missing an OBX 3 value, MSH 4 is listed as  “Chinatown Brooklyn - Doral Medical^33D2178905^CLIA”
 
Are you able to correct and resend the message?
Accession ID: ```1ab07245-500d-459a-aec5-ce223bd852fa```
MSH 10: ```1ab07245-500d-459a-aec5-ce223bd852fa```

**Comment by anshulkumar-usds** [comment]
1/25: Following up with ImageMover on resubmissions.

**Comment by anshulkumar-usds** [comment]
Blocked by https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4033

**Comment by anshulkumar-usds** [comment]
2/10: No longer blocked - checking with ImageMover on update

**Comment by Adrian-Brewster** [comment]
ImageMover doing resubmissions.

**Comment by anshulkumar-usds** [comment]
3/1: IM completed resubmissions. MN was notified.

**Comment by anshulkumar-usds** [comment]
3/2: MN confirmed and validated message.
