### ISSUE TITLE
Testing using the CLI doesn't work with the new CSV uploader schema

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#4003]
## Problem statement
You can no longer use the CLI for testing or creation of fake data when using the new CSV Uploader schema (upload-covid-19.schema) because the sender_id and processing_mode_code are now pulled from the Settings instead of from a child schema.

## Things to know
The CLI has a parameter for the input-schema whereas CURL requires the "client:' which then allows the schema to get the sender_id from the Settings.  Examples are:

./prime data --input result_files/StandardCSV-Test.csv --input-schema manualupload/csvuploadertest-covid-19 --output-dir junk --route

curl -X POST -H "client:csvuploadertest" -H "content-type:text/csv" --data-binary "@./result_files/StandardCSV-Test.csv"  "http://localhost:7071/api/reports"

./prime data --input-fake 100 --input-schema manualupload/sourcebioscience_ca-covid-19 --output junk/StdCSV-fake.csv

## Acceptance criteria
- The user can set the client name when using the `data` CLI tool. 
- When the client is passed as an argument from the CLI then the schema should be set to the one for the given client.  Only one of input-client or input-schema can be set

**Comment by oslynn** [comment]
New test CLI commands:
./prime data --input result_files/StandardCSV-Test.csv --input-client csvuploadertest --output-dir junk --route

curl -X POST -H "client:csvuploadertest" -H "content-type:text/csv" --data-binary "@./result_files/StandardCSV-Test.csv" "http://localhost:7071/api/reports"

./prime data --input-fake 100 --input-client csvuploadertest --output junk/StdCSV-fake.csv
