### ISSUE TITLE
Adjust test_result_status in direct covid schema to accept sender input

### ISSUE THREAD

**Issue by brick-green-agile6** [CDCgov/prime-reportstream#4022]
## Problem statement

Currently, a CSV sender is not able to provide a value for the test result status. All result statuses are defaulted to F. We need to continue to default to F when no value is provided by a sender. But the sender should also be able to send a value in cases where corrected results are to be sent.

## Acceptance criteria

- [ ] testResultStatus is a available field for CSV senders
- [ ] when testResult status is blank the output message will default to F
- [ ] when a value is provided it is not overwritten
- [ ] the value provided must be in table hl70123

## To do

- [ ] add csvFields: [{ name: testResultStatus}] under field test_result_status in direct-covid-19.schema

**Comment by jbiskie** [comment]
A couple findings on this...

-The field that Direct senders are asked to populate for a corrected result is "correctedTestID".  This should be a reference back to the original result.
-Given that correctedTestID is the indicator that it's a corrected result, should the direct schema do the work of mapping of the result status based on the presence of a value in correctedTestID?

**Comment by brick-green-agile6** [comment]
@jbiskie Thanks for this!!! I think you're right that the direct schema should fill in the result status based on the presence of correctedTestID
