### ISSUE TITLE
Adjust the direct covid schema to set result status based on value in test corrected id

### ISSUE THREAD

**Issue by brick-green-agile6** [CDCgov/prime-reportstream#4033]
## Problem statement

Currently, a CSV sender is not able to provide a value for the test result status. All result statuses are defaulted to F. We need to continue to default to F when no value is provided by a sender. But the sender should also be able to send a value in cases where corrected results are to be sent.

## Acceptance criteria

- [ ] when testCorrectedID is blank the output result status will default to F
- [ ] when testCorrectedID is present the output result status will default to C

**Comment by anshulkumar-usds** [comment]
OH and MN resubmissions from ImageMover are also dependent on this fix

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 can this be closed?
