### ISSUE TITLE
Prescryptive - Onboarding wht CSV instead of HL7

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4035]
Prescryptive is currently being onboarded to RS API. For far, they have been sending HL7 files for our testing and validation. The sender decided to change the format of these submissions to CSV, and has requested we update our ingestion process to accommodate this change.

1. Update internal settings/schemas to allow sender to submit CSV
2. Validate sample CSV file submitted on 1/26 over email
3. Request sender to submit additional sample/fake data over staging to ensure csv files can be ingested over the API without any errors
4. Follow up on next steps with taking sender to prod

**Comment by jbiskie** [comment]
Prescryptive is switching back to HL7, closing ticket.
