### ISSUE TITLE
Colorado - Covid Clinic - Baseline Research

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4068]

**Comment by victorialb-usds** [comment]
Logged in [tracker. ](https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B431D9FDE-C408-43E7-B643-E1D30652155C%7D&file=CSV%20pilot%20cohort%201_Pre%20Post%20Data.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1&cid=f5f8bd31-6856-436a-b8c2-e7629f60d9ca)
