### ISSUE TITLE
Colorado - SDI Labs - Baseline Research

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4069]
## Problem Statement
SDI Labs has requested to be onboarded to ReportStream and the CSV Uploader.

## Contact Info
Afreen Rahman, Product Manager
afreen@sdilabsinc.com
+1 (214) 713-1437

**Comment by victorialb-usds** [comment]
kick-off question call requested by SDI on 2/3/22 VLB added some questions in https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FPilots%2FCSV%20Uploader%2Fz%5FExperience%20Research%5FCSV%20flat%20file%20upload%20December%202021%20ongoing&viewid=17db3ff6%2D95c5%2D4562%2Da1f3%2D12b5097b5947

Logged in [tracker. ](https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B431D9FDE-C408-43E7-B643-E1D30652155C%7D&file=CSV%20pilot%20cohort%201_Pre%20Post%20Data.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1&cid=f5f8bd31-6856-436a-b8c2-e7629f60d9ca)
