### ISSUE TITLE
IL - Duplicate Submissions (Failures from 1/30)

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#4078]
IL has identify duplicate submissions in files they received on 1/28/22.

A 36 MB file that was transmitted to them contained a significant amount of duplicates. After IL ran through their deduplication process, the file went from 36 MB to roughly 7 MB.  

IL was also able to identity the first message control ID in the file was repeating in the file multiple times. More details can be  found in the email box with screen shots.

The name of the file with this issue is - ‘covid-19-4ce041f5-aa05-4be4-903f-0242c0e4ba8f-20220128183853.hl7’.

Based on the facility example that IL provided, there were only 43 test events that were submitted via SR for that facility.

Also, it looks like there was a RS deployment on 1.28.22.

**Comment by anshulkumar-usds** [comment]
Known issue with SR duplicate message submissions

**Comment by anshulkumar-usds** [comment]
2/2: @MauriceReeves-usds I am checking with IL again on how they would like to receive resubmissions. For now, please prioritize positives with corrected LOINCS.

**Comment by anshulkumar-usds** [comment]
IL asked to be sent just the positives with corrected LOINCs.

Files should be sent as a .txt so they are treated as a "test" file at IL.

**Comment by MauriceReeves-usds** [comment]
2/3 - Sent the file to their SFTP with a .txt extension.

**Comment by anshulkumar-usds** [comment]
After emailing IL got a an auto reply that IL DOH is closed today due to weather. Hence, their review and feedback might be delayed.

**Comment by anshulkumar-usds** [comment]
2/7: Checked with IL again today. Awaiting response from IL.

**Comment by anshulkumar-usds** [comment]
2/10: Checked with IL if anything is pending

**Comment by anshulkumar-usds** [comment]
2/11: No further news from state. Closing.

**Comment by anshulkumar-usds** [comment]
3/8: Reopening - IL inquired about some pending messages they need. Working on clarifying details with state.

**Comment by anshulkumar-usds** [comment]
3/9: @MauriceReeves-usds IL wrote back with the following. They basically need the full HL7 file sent to them with the corrections:
"That is a csv file that we have to manually trudge through and we were hoping that we could get an HL7 file with the correct data in the correct places and we would run that back through our system and then the cases that were positive would Merge and would then be correct instead of how they are currently.  Then we can system process the rest that are negative to make them not a case, but it all starts with having something that we can process through our normal work flow. "

**Comment by anshulkumar-usds** [comment]
@MauriceReeves-usds this is still pending. Who can take this on in our team?

**Comment by Adrian-Brewster** [comment]
Next in priority after Washington resends.

**Comment by jorg3lopez** [comment]
@anshulkumar-usds @Adrian-Brewster Please see attached file which contains all message_ids that need resend. The original HL7 message has 15,417 test results which include duplicated test results. The excel file has no duplicates, the total files that need resend are 3,942. I will start working on the resends.[https://app.zenhub.com/files/304423150/1ab36a3a-0fd8-4c32-9cd6-ab207ffa8644/download](https://app.zenhub.com/files/304423150/1ab36a3a-0fd8-4c32-9cd6-ab207ffa8644/download)

**Comment by jorg3lopez** [comment]
@Adrian-Brewster @anshulkumar-usds I think the duplicates don't need to be resent. @anshulkumar-usds please verify this. It seems that this ticket has entries going to two different events, one being the duplicates, and another dealing with LOINC codes fails.
