### ISSUE TITLE
MD - ELR failures for SR and "Unknown" sex

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4094]
On 1/28, MD reported that a list of ELR messages from SimpleReport that are failing (attached).

Additionally, they reported that large amount messages are showing patients' sex as "Unknown". Are users actually entering sex as Unknown or is there some kind of default?  @LGFranklin  can you respond to the second question on patient reported sex in SR?

**Comment by anshulkumar-usds** [comment]
[https://app.zenhub.com/files/304423150/45349b48-e0c6-4ac4-b2c6-a7a77d146969/download](https://app.zenhub.com/files/304423150/45349b48-e0c6-4ac4-b2c6-a7a77d146969/download)

**Comment by LGFranklin** [comment]
@anshulkumar-usds 
We recently updated the patient-facing options for sex assigned at birth to male, female, other, prefer not to answer. I believe the HL7 mapping for other, prefer not to answer is unknown. I'll confirm w/ the team.

**Comment by anshulkumar-usds** [comment]
@LGFranklin I copied you on my last response to MD. Please let MD know how the "Unknown" is being mapped.
