### ISSUE TITLE
Update Content for Programmer's Guide

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4101]
## Problem Statement
The content in the API Programmer's Guide is out of date. As the ReportStream team, we need to update the content so that it matches the API functionality and we can provide accurate information when we distribute it to API end users.

## Acceptance Criteria
- Update the API Programmer's Guide so that it matches the API functionality
- Include the async progress in the API Programmer's Guide (see [Jim Duff's slack](https://agilesix.slack.com/archives/C02HJ43AE8Z/p1643723202116759?thread_ts=1643722591.081889&cid=C02HJ43AE8Z))
- Review the API Programmer's Guide when changes are complete to ensure they match the API

**Comment by anshulkumar-usds** [comment]
@jbiskie is working on an updated version of the Programmer's Guide here: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3627

**Comment by jbiskie** [comment]
@BerniXiongA6 I'm planning to complete this sprint.

**Comment by BerniXiongA6** [comment]
Update 2.8.2022: Joel Biskie to complete updated version of programmer's guide by end of sprint. I'll do a full content review after that time to finalize a version 2.0 doc. (Couldn't create a dependency on O&O's # 3627 for this Issue, can you help @loripusey ?)

**Comment by BerniXiongA6** [comment]
Update 2.24.2022: Received the version 2.0 draft of the programmer's guide for senders from @jbiskie yesterday. Completed content review (containing marked changes and comments) and saved it on [shared doc in Experience teams folder](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/3.%20Instructional%20Design%20Projects/ReportStream%20Programmer%20Guide%20for%20Senders/Berni%20edits%20-%20v2.0%20ReportStream-Programmers-Guide-for-Senders%20v20220224.docx?d=w76b6be5b1d4f4f79a0e43ca7d1c67280&csf=1&web=1&e=LbSjsS) for Joel to accept/reject/modify changes and resolve comments. Joel B. to finalize 1) "Appendix A: Fields List..." and 2) routing info via separate API call.

**Comment by BerniXiongA6** [comment]
Update 2.25.2022: See new issue [# 4555](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4555) for "content review" that will need to be done once final updates on schema guidance (and other minor engineering edits) come back from engineering (Joel B.).

**Comment by BerniXiongA6** [comment]
Updated 3.10.2022: Saving final API programmer's guide version 2 [here](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/3.%20Instructional%20Design%20Projects/ReportStream%20API%20Programmer%20Guide/FINAL-ReportStream-Programmers-Guide-v2.0.docx?d=w335fe0c2408b4e38a0152ea1c0c8fc1c&csf=1&web=1&e=wSboaa).
