### ISSUE TITLE
Design the replacement to legacy history function endpoints

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#4104]
Some of the legacy history API functions can now be replaced by the new Submissions History API, but not all.

There are current these use cases for the legacy history API:
1. Get a list of reports available for download.
1. Get details about one specific report.
1. Perform a download of one report.
1.  Get the facilities associated with a Report.  (Data is in the covid_result_metadata table)

Design considerations:
1. Note the RS UI is the only one using this legacy API.
1. This will be an internal refactor as there is code that needs to be simplified like Okta.

Acceptance criteria:
1. Document the legacy history API functions, determine what can be replaced by the new submissions history API.
1. The API endpoints should follow the established naming conventions.
1. Write a proposal with the details and present to the team.
1. Generate required issues to be groomed.
1. From a user perspective, the bad thing we need to fix the most is that the "Facilities" query is extremely slow.

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/4104?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @oslynn @smythe5 @whytheplatypus
