### ISSUE TITLE
Admin Settings: add back button to org edit page

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#4122]
## Problem statement

Currently after the user chooses an organization to edit, there is no explicit way to navigate back to the main page- one has to use the browser's back button or reselect Admin-->Organization Settings from the top menu. Need to have a back button to make it simple.

## Design
May want to use the USDS Design System bread crumb component
https://designsystem.digital.gov/

Example:
![image](https://user-images.githubusercontent.com/92405130/151877738-5af39458-1b1b-4538-9dd3-e83551c80b7c.png)

## Acceptance criteria

- [ ] Back button on the Org Edit page that navigates the user back to the main Org List page

## Related stories

- [3343 (Original)](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3433)
- [3935 (Part 2 idea list)](https://github.com/CDCgov/prime-reportstream/issues/3935)

**Comment by loripusey** [comment]
This has been de-prioritized.

**Comment by kevinhaube** [comment]
The designs provided are stale after seasons of inactivity. Design needed before we move forward with adding any back nav. @drew-usds Good first item for new designers!

**Comment by brick-green** [comment]
I think it would be useful but also that it should be part of a larger design pattern rather than a one-off on that page alone. I like the idea for the breadcrumb rather that simple back since there are multiple layers to click through
