### ISSUE TITLE
Source BioScience - CSV Sender Onboarding

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#4126]
## Sender Info:
- Sender/Company Name: Source Bioscience in CA
- RS sender_id: sourcebioscience_ca

## Initial Interest & Follow Up
- [x] Document the date & time the Sender expressed interest  --  1/13/2022
- [x] Send Std Kickoff email.  This includes:

         - Links to TOS & TOS Registration
                 - https://reportstream.cdc.gov/terms-of-service
                 - https://reportstream.cdc.gov/sign-tos 
         - Links to the CSV upload guide and CSV schema documentation
                 - https://reportstream.cdc.gov/getting-started/testing-facilities/overview
         - Provide an option to have a Kickoff call to review these documents and answer any questions.
- [x] Schedule Kickoff / Q&A meetings at the Senders request.
- [x] Received TOS.

## Sender Setup - Create OKTA group & OKTA account
- [x] Define the RS sender_id  --  sourcebioscience_ca
- [x] Create an OKTA group for the sender_id
- [x] Create an OKTA account using the RS Registration information.
- [x] Verify OKTA account registration by the Sender.

## Sender Setup - Create Sender Settings for Staging & PROD
- [x] Locally, create and test Settings in organizations.yaml
- [x] Create the Staging & Production YAML settings files

## Testing - Prod/Test Internal
- [x]  Move all RS development to Staging & PROD.
- [x] Make settings change to block results to the STLT, or send all results to the STLT's Test Feed.
- [ ] Validate Production data and make all necessary RS changes.  Iterate through testing until validation is complete.

## Testing - Prod/Test External (if required by the STLT
- [ ] Contact the STLT to setup testing with Production data in their Production environment.
- [ ] Verify which Feed the STLT wants to receive the results.  Make settings changes as-needed and deploy to PROD. 
- [ ] Work directly with the STLT to complete Integrated Testing and gain approval to move into Production.
          - Prod/Test External (if required by the STLT)

## Implementation - Plan & Schedule GO LIVE
- [ ] Change setting "customerStatus:" to active from testing.
- [ ] Contact RS Pipeline Team to turn on HHSProtect reporting.
- [ ] Determine if there is a backlog of results.  If so, contact the STLT to determine what results are needed.  Example, in at one STLT, if a Sender has reported positives only to the STLT, then the STLT wants all COVID (positive & negative) since the Sender started testing.
- [ ] Coordinate and schedule a start date for daily results and backlog results between the STLT and the Sender.

## Implementation - GO LIVE and Post LIVE Review
- [ ]  Monitor daily uploads for errors and contact Sender if results need to be corrected and resent.  Monitoring will typically be 1 week in duration unless issue are found.

**Comment by rhood23699** [comment]
1/13/22 - Adrian has kickoff schedule for 1/13/22 at 4p CT.

**Comment by rhood23699** [comment]
1/13/22 Kickoff meeting completed. Source BioScience will contact their I/T in the UK to get started. They did confirm receipt of the OKTA registration email, but they have completed the registration yet.

**Comment by rhood23699** [comment]
1/19/22 Source Bio reported that their activation email says expired. I've asked them to contact me because the email shouldn't expire for 90 days.

Added two more OKTA accounts and sent the activation emails.

**Comment by rhood23699** [comment]
1/24/22 On the third activation email resend, the first account has been successfully activated. The 2 additional accounts have been resent, but are still pending activation.

**Comment by rhood23699** [comment]
1/26/22 One OKTA account has been activated which is enough for testing. The other users can contact us whenever they like.

**Comment by rhood23699** [comment]
They email'd and stated they hope to send the first test file today, 2/3/2022.

**Comment by rhood23699** [comment]
2/8/22 We didn't receive a test file on 2/3/22.  Email'd asking for a status today.

**Comment by rhood23699** [comment]
'2/14/22 Had to reset OKTA password.  They are trying to send a test file.

**Comment by rhood23699** [comment]
2/17/22 Email'd and they stated no update.

**Comment by rhood23699** [comment]
3/2/22 Victoria had a call with them.  They hope to start testing next week.

**Comment by rhood23699** [comment]
3/9/22  Email'd asking for an update.

**Comment by rhood23699** [comment]
Icebox'd until they contact us for testing.

**Comment by sarahnw** [comment]
closing. csv is handled by SR now.
