### ISSUE TITLE
GU - Duplicate Submissions (Failures from 1/30)

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4132]
GU reported duplicates and failures. Attached is the list of all messages that need to be resubmitted to GU with valid LOINCs

[https://app.zenhub.com/files/304423150/5376aced-e217-4536-9d68-eadcd3a7ddf2/download](https://app.zenhub.com/files/304423150/5376aced-e217-4536-9d68-eadcd3a7ddf2/download)

**Comment by anshulkumar-usds** [comment]
@jbiskie Similar to what Mo did with MD, we can share the GU accession IDs with Zedd in SR team for resubmissions. Not sure how far you may have gotten on this, but consider this as an option. You can share this list in slack thread with Zedd.

**Comment by jbiskie** [comment]
Thanks, that makes things a lot easier than I thought they would be. So do we only need to manually resubmit those that didn't come from SR?

**Comment by anshulkumar-usds** [comment]
AFAIK, the duplicates all came from SR, so this might be as easy as asking SR team to resubmit the messages on this list.

**Comment by anshulkumar-usds** [comment]
Updates list here; failures as of 2/2 are greater than previously reported. Refer to the sheet for GU

[https://app.zenhub.com/files/304423150/e1318207-fe16-4169-a13c-6d25c35b3b64/download](https://app.zenhub.com/files/304423150/e1318207-fe16-4169-a13c-6d25c35b3b64/download)

**Comment by jbiskie** [comment]
Thanks, I'm reviewing this against the first list

**Comment by jbiskie** [comment]
Full list has 1212 unique message id's vs 444 in first list.  Counts are approx the same between created_at > '2022-01-28T10:55:23.094780' and created_at < '2022-01-31T01:30:00.000000'.  Remainder were messages after that time span.

**Comment by jbiskie** [comment]
Sent json with all messages to Zedd.

**Comment by zdeveloper** [comment]
Done! expect to see it in RS around 10:45 CST

**Comment by jbiskie** [comment]
Thank you @zdeveloper!

**Comment by anshulkumar-usds** [comment]
Inductive is reviewing the resubmissions.

**Comment by anshulkumar-usds** [comment]
From Inductive:
"Guam received the 1212 reprocessed labs yesterday and are officially caught up! All processed into the NBS system successfully. "
