### ISSUE TITLE
TN - Duplicate Submissions (Failures from 1/30)

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4133]
TN reported failures due to duplicates received on 1/30. Awaiting further instructions from TN on which messages to resubmit.

**Comment by Adrian-Brewster** [comment]
TN responded. They want all messages not sent to TN due to missing LOINC or invalid LOINC to be sent/resent including the two below:
137e9089-31e1-4fbb-8226-7c2923d0d5d7
2ab908ed-3133-4606-b058-a72685587312

**Comment by brick-green-agile6** [comment]
Requested resend from Zedd for these results:

**message_id**
```
137e9089-31e1-4fbb-8226-7c2923d0d5d7
2ab908ed-3133-4606-b058-a72685587312
7735253c-2785-4814-baf1-ea4e1b60dca6
d2239c58-97f1-4ebd-b393-a2b244371a8e
f1b5d170-e6ea-414a-bdd2-b3f65c5d708c
```

**Comment by brick-green-agile6** [comment]
The 5 results above only solve the LOINC code issue. Will work to find all results failed due to duplication issue.

**Comment by brick-green-agile6** [comment]
We have received the results and they are batched. TN is scheduled to receive files once per day at 09:15 ET. So the results will be sent out tomorrow morning.

**Comment by zdeveloper** [comment]
resent these yesterday [(slack convo)](https://skylight-hq.slack.com/archives/C025F5W5Q7L/p1643817407558969?thread_ts=1643812851.953239&cid=C025F5W5Q7L)
137e9089-31e1-4fbb-8226-7c2923d0d5d7
2ab908ed-3133-4606-b058-a72685587312
7735253c-2785-4814-baf1-ea4e1b60dca6
d2239c58-97f1-4ebd-b393-a2b244371a8e
f1b5d170-e6ea-414a-bdd2-b3f65c5d708c


and these [(slack convo)](https://skylight-hq.slack.com/archives/C025F5W5Q7L/p1643819288159219?thread_ts=1643812851.953239&cid=C025F5W5Q7L)
065ea852-e297-448f-b7fc-4b12040c35d1
0a950c6f-3d0b-4088-b1ef-2a5a0cdba6d6
0c829ea3-632f-424d-af9e-b8cf75027e6d
14fa0595-5d44-4ce1-9861-23e7b26ce885
1570b12d-5670-4bfc-9910-1e2a91b76fbb
28f86506-3cdf-4840-9763-736d3a9b58e5
2a5d9e11-2c34-405c-9145-1d420a474bd1
2cd37562-e6f3-4707-b5a7-3d45532dc736
2f026e4e-8a9e-45e9-8977-63da146daaaf
32e5ebd3-5653-4843-b1de-f1d300733ae0
33aa0cff-cdd0-4f38-b568-6c4e3a13168f
3485c5f7-e744-4870-8b2a-5ce55b4347b1
35895d70-064f-4cbf-9157-eefc835df487
3ad1ed26-ab07-49cc-8b05-3dc5b5d5cc17
45f38151-7862-438b-bc77-111c0ca19217
49c7fc33-2eaf-40b0-beef-bbe0e4145783
4a1f048c-31ba-4a60-90ae-17dd50a229a9
4bf856c2-ddb4-45bd-9c31-179f5c43c438
4c9fa780-bbc9-429e-b8a6-55868f96ddcf
4dfbe261-5a0a-4503-9b3d-5382ebe004f3
5b927f5f-6db8-4b9f-b6fb-6a1c947bb891
5c07d618-5b38-4485-9dde-e4f384fef04f
60c82990-a3b0-4116-b300-fec61bc98a23
632561fe-7690-489f-8f3a-7405fd80179a
6a150b14-3d5d-424d-be51-1379f34f5096
73aad662-01f0-4b7b-9f5a-45ce0c0c2087
75c18f0f-5862-4a56-8e20-e735a647a15b
78b36d72-3337-4be9-8942-5a8d36aa9e9b
7a8cf73e-f781-490c-9f62-2d44ad4979d0
7e72175f-9164-47ee-8c29-3ec2558addae
7fba9896-0911-46e4-a2f7-df110084c512
921d19da-f2e6-4626-8a94-94f724a820e9
95a844ed-5c0c-45dc-9941-1b0676704104
a1ad3a87-b3b2-4921-8824-6268fbdbe7c0
a2ae7649-92f4-4373-ac2c-f5871820e343
a9048d6b-b8db-40c8-b27d-7650a70ca9e9
ab1a3a90-8075-4f99-bd2e-c419560d8473
b22a0da1-7dcb-4e79-acea-bf6d3824697d
bb37f50b-0aa1-49e3-8148-451393a5597b
bd99d113-1e7e-403d-908c-1b527e9f6686
c2470265-549e-455c-9754-5cc86c0b7e21
c5e0e0fb-1e91-46f2-8b4d-173d99c8bbfc
ccd3a847-c66e-4b4b-b774-3c8d5571af40
ce00537c-56d4-41ee-8bc5-4fb539917a63
ce9b95c3-8581-4076-9b4b-3fc4d15dddbf
d2239c58-97f1-4ebd-b393-a2b244371a8e
da51d528-d571-4b64-9a55-04b617da6659
da783eb8-acbf-4b4f-b5a2-59c533552365
e0e74a90-e8ff-4e49-85a9-28ff6cdd88df
ea9639db-47da-483b-b5db-67ffe5edc3b1
ed0d999e-c8a6-4aac-beeb-0d391b69e4cc
f71a3412-e5f5-4e15-b754-ead6cbbd6de0
fcd226a1-2674-437b-8169-4c626966fa3e
fce202c7-281d-42cd-8681-1e6c4eb4893b

**Comment by zdeveloper** [comment]
was there anything else for TN?

**Comment by anshulkumar-usds** [comment]
Checking with state on file delivery

**Comment by brick-green-agile6** [comment]
filename delivered to TN: 

covid-19-c0dc322c-ba67-41f1-8fe0-b7fbf428d541-20220203141604.hl7

**Comment by anshulkumar-usds** [comment]
2/11: No further request from state. Closing.
