### ISSUE TITLE
MS - Duplicate Submissions (Failures from 1/30)

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4134]
MS reported failures due to duplicate submissions on 1/30.

MS has requested we resubmit ALL results with valid LOINCs to correct this.

Please share file names for resubmissions so they can be tracked by the STLT.

**Comment by brick-green-agile6** [comment]
Going to ask Zedd to resend these results from SR. After they run I can gather the file names. [Uploading... MS - Message ID Resend.csv]

**Comment by brick-green-agile6** [comment]
Zedd is still working on the resend:

"btw the list you shared yesterday is still in flight, will have to make a minor code change, will let you know when that is done"

**Comment by anshulkumar-usds** [comment]
Inductive provided a list of effected messages in the attached sheet. Refer to MS sheet:

[https://app.zenhub.com/files/304423150/443cef4a-2f70-49d1-8bfc-8506d712fb09/download](https://app.zenhub.com/files/304423150/443cef4a-2f70-49d1-8bfc-8506d712fb09/download)

**Comment by brick-green-agile6** [comment]
@anshulkumar-usds The list I provided to Zedd included all these results Inductive asked for. My request actually included more results...should I go back to Zedd with the list from Inductive?

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 No, that's fine. Let's work with your original list of IDs.

**Comment by zdeveloper** [comment]
Resend 1347 events supplied by Brick

**Comment by anshulkumar-usds** [comment]
Checking with state

**Comment by anshulkumar-usds** [comment]
2/7: Inductive still reviewing, no update yet.

**Comment by anshulkumar-usds** [comment]
2/10: Checking with Inductive if anything is pending
