### ISSUE TITLE
WA - Duplicate Submissions (Failures from 1/30)

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4135]
WA reported failed messages due to duplicate submissions on 1/30.

WA wants us to inform them of the count and message ids for positive and negative results before any resubmissions are attempted.

**Comment by anshulkumar-usds** [comment]
Prior to any resubmissions are done, WA would like us to send them a spreadsheet with accessions IDs for positive and negative results along with respective LOINCs so they can assess the extent of the issue. Please organize this spreadsheet by positive and negative results separately as WA treats this as distinct workstreams in their systems.

After WA reviews this, their preliminary preference is to prioritize sending positive results.

**Comment by MauriceReeves-usds** [comment]
@Adrian-Brewster @anshulkumar-usds Attached are the two spreadsheets to return to WA for the separate events (duplicated records and missing LOINCs). Please forward both to WA and ask them what steps they'd like us to take next.

**Comment by MauriceReeves-usds** [comment]
[https://app.zenhub.com/files/304423150/158979c9-84d0-4c5a-809e-963657130f70/download](https://app.zenhub.com/files/304423150/158979c9-84d0-4c5a-809e-963657130f70/download)
[https://app.zenhub.com/files/304423150/f229b8d5-5444-4999-a97f-c9aef7e8d5dc/download](https://app.zenhub.com/files/304423150/f229b8d5-5444-4999-a97f-c9aef7e8d5dc/download)

**Comment by anshulkumar-usds** [comment]
Spreadsheet shared with WA on 2/6 - awaiting response

**Comment by anshulkumar-usds** [comment]
@zdeveloper completed the resubmissions for 169 messages. @MauriceReeves-usds when possible, please share filenames under which these got batched. WA requested these for tracking.

**Comment by anshulkumar-usds** [comment]
@jbiskie @jorg3lopez @oslynn can any one of you please help me locate the filenames where the 169 message got batched for WA?

**Comment by anshulkumar-usds** [comment]
Filename for 169 messages with missing LOINCs: missing-loincs-2/cdcprime_testing_20220210161515_879684.hl7

**Comment by anshulkumar-usds** [comment]
2/14: WA does not need the failures due to SR duplicates resubmitted. They are reviewing the 169 submissions and will inform RS of next steps as needed. Follow up with WA by 2/18, otherwise close ticket.

**Comment by anshulkumar-usds** [comment]
2/15: @MauriceReeves-usds WA reports the following need to resent, and were not included in the 169 messages earlier:
```
300cb78a-6c08-4b38-b9eb-68cb50630dc2
7a4d66b1-ad52-4bba-b51e-30ec064bf693
a9861753-e954-447a-aec3-78db42ec4ecf
b2f33a22-e358-4c4c-b475-b76f43a51acf
f807f58c-e5cf-4d0c-8e72-b5c855ee5a15
a5ac70fb-47c8-42c8-8b62-04da08cb8974
```

**Comment by Adrian-Brewster** [comment]
@MauriceReeves-usds will resend the 6 required messages today.

**Comment by anshulkumar-usds** [comment]
3/23: @MauriceReeves-usds WA wrote to us on 3/22 that they have identified additional records that are missing LOINCs from the 1/30 failures. There were part of the negatives so these results just processed now. The attached list of message is missing LOINCs in the OBX segments. WA needs us to resubmit these as well:

[https://app.zenhub.com/files/304423150/6c10d5af-e5c4-423c-99fd-9bb95de08927/download](https://app.zenhub.com/files/304423150/6c10d5af-e5c4-423c-99fd-9bb95de08927/download)

**Comment by anshulkumar-usds** [comment]
3/28: @MauriceReeves-usds WA mentioned they identified even more, but will send a list on a weekly basis with messages related to missing LOINCs. So we should expect to receive a new list by 4/1

**Comment by anshulkumar-usds** [comment]
4/8: @MauriceReeves-usds Attached is the latest file as of 4/8

[https://app.zenhub.com/files/304423150/7e3a2d0f-4a3c-4ed3-8ec2-23379e779ddd/download](https://app.zenhub.com/files/304423150/7e3a2d0f-4a3c-4ed3-8ec2-23379e779ddd/download)

**Comment by Adrian-Brewster** [comment]
WA has a 90 day window for resubmissions.  We need to make sure we send these before the end of the month. @MauriceReeves-usds

**Comment by Adrian-Brewster** [comment]
These messages need to be sent via email at this point.

**Comment by oslynn** [comment]
When I am done with my tickets, I will come to @brick-green-agile6 and help if he still needs my help.

**Comment by anshulkumar-usds** [comment]
@oslynn and @brick-green-agile6 please see my comment above from 4/8 - that contains the latest list of messages.

**Comment by brick-green-agile6** [comment]
finally retrieved all the filenames. Now I need to go download the files and extract the correct results.

**Comment by brick-green-agile6** [comment]
should be ready to send these this morning

**Comment by brick-green-agile6** [comment]
[https://app.zenhub.com/files/304423150/85e07f48-6a19-4603-a3f7-b93e391556b9/download](https://app.zenhub.com/files/304423150/85e07f48-6a19-4603-a3f7-b93e391556b9/download) Here's the file that needs to be sent to WA

**Comment by anshulkumar-usds** [comment]
6/22: WA reported on 6/21 that "Correction needed in formatting of the times, requested 6/17". 

Moving to internal review.

**Comment by sarahnw** [comment]
@Adrian-Brewster followed up with Caroline that this isn't something we can go back and correct now as too much time has passed.
