### ISSUE TITLE
IL - BHS Precision Enhancement Request 

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#4136]
**Describe the bug**
Illinois is having an issue because they use the time stamp in the BHS as a unique key and some of our files have the same time stamp so they are getting kicked out.  They initially thought they were more duplicates, but it looks to be a time stamp issue. They are requesting that we create a BHS down to seconds.  Apparently this is a common practice for them with other senders.

**Impact**
Unable to identify duplicates

![Screen Shot 2022-02-01 at 11.37.41 AM.png](https://images.zenhubusercontent.com/60d1eba7caf0775fd79203f8/e7e242a4-b465-47e6-9f35-20fab19aed91)![Screen Shot 2022-02-01 at 11.37.22 AM.png](https://images.zenhubusercontent.com/60d1eba7caf0775fd79203f8/5cbb2cb0-03a4-49de-a8a9-7fdeb58103ee)![Screen Shot 2022-02-01 at 11.36.59 AM.png](https://images.zenhubusercontent.com/60d1eba7caf0775fd79203f8/b2fa5c3c-bcdb-4bd4-acae-b48fbe6927f0)

**Comment by MauriceReeves-usds** [comment]
Assigning to myself. Moving to sprint backlog. This can get done very quickly.
