### ISSUE TITLE
Develop a test plan for testing "Full ELR" data conversion  

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#4138]
As a developer, I need a way to test the conversion of full-ELR data (FHIR->HL7 and HL7->FHIR), so tests can be run for development and I know the conversions still work as expected.  This issue is to come up with a plan for such tests.

### AC

This is just a thinking ticket.  So the AC is that we have a set of stories/tickets written to do basic testing on the FHIR engine and Full ELR.

### Other notes

NIH has a standard they are developing with APHL that is meant to be a standard HL7 for Covid-19.  We might be able to write tests for both the new NIH standard AND full-ELR

"Full ELR" means HL7 that meets the HL7 standard for all reportable diseases. "ORU-?"

We originally thought about handling HCA data. That is, our AC was: We can ingest at least the covid test data inside the full-ELR data. Examples of data can be found in our sharepoint site.

This could be done with a testIntegration test, a smoke test, or other.

There's already a ticket to generate fake Full ELR HL7:  #1793.   Amend as needed, for this ticket.

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/4138?planning-poker) with ZenHub @carlosfelix2 @jimduff-usds @oslynn @smythe5 @whytheplatypus @jh765

**Comment by jimduff-usds** [comment]
This ticket was redundant with #3963, so I removed that one and kept this one.
