### ISSUE TITLE
Washington

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-reportstream#414]
- [X] Direct vs Redox = Direct
- [x] Security review
- [x] SFTP credentials
- [ ] First sender
- [ ] New Site Registration
- [x] Data use agreements
- [ ] Confirmation on testing process
- [x] Synthetic Data
- [ ] Patient data
- [ ] Go live

**Comment by jlusds** [comment]
Blocked by security review

**Comment by jlusds** [comment]
Submitted HIE form yesterday

**Comment by jlusds** [comment]
Still blocked on HIE conversation.

**Comment by jlusds** [comment]
**AS2 connection details**
[https://app.zenhub.com/files/304423150/66c46877-7e7a-478a-bbb5-88b44b269c9c/download](https://app.zenhub.com/files/304423150/66c46877-7e7a-478a-bbb5-88b44b269c9c/download)

**Data Schema details**

https://www.doh.wa.gov/ForPublicHealthandHealthcareProviders/HealthcareProfessionsandFacilities/PublicHealthMeaningfulUse/LaboratoryReportingELR

Guidance on AOEs here - https://www.doh.wa.gov/Emergencies/COVID19/HealthcareProviders/ReportingTestResults


Link is under How do I meet the new HHS lab requirements.

https://www.doh.wa.gov/Portals/1/Documents/1600/coronavirus/421-005-LabsReportingTestResultsAOEQuestions.pdf

**Comment by RickHawesUSDS** [comment]
@jlusds We need a connection meeting where we get a certificate, url, port, ip to make progress on this.

**Comment by RickHawesUSDS** [comment]
Technical questions worked out.

**Comment by RickHawesUSDS** [comment]
Security review done.

**Comment by RickHawesUSDS** [comment]
Still have data use agreements issues.

**Comment by jlusds** [comment]
Working on a bug fix

**Comment by RickHawesUSDS** [comment]
WA is live
