### ISSUE TITLE
Fully onboard `DHPrimeAdmins` organization in staging and production

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#4140]
We need an fully onboarded organization that is used as Prime Admins' default when they log into the server.

- [x] `DHPrimeAdmins` needs to exist in Okta and Okta Preview
- [ ] `PrimeAdmins` is the human readable Organization name.
- [ ] Add existing admins to this organization
- [ ] When there is an admin login default to this organization. (And fail in a reasonable way if the user is an admin but NOT in this organization)
- [ ] Make sure this organization is in the database and fully onboarded.
- [ ] Add to `organizations.yml` for local testing.

**Comment by kevinhaube** [comment]
This has gone stale, but the idea is good. Actively considered in discussions around new Admin UXs
