### ISSUE TITLE
Improve Admin's Organization dropdown for large amounts of data

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#4142]
Since this is an admin-only UI, we don't need formal design. Maybe something similar to what github does with selecting Estimate or a Project in a ticket?

<img src="https://user-images.githubusercontent.com/74203452/152037927-e47e38d8-ab47-48aa-993a-09de33d3d137.png" width="200em">

Since this is an internal-only UI, strict USWDS isn't required initially.

Part of this is probably to make the call to get all Organization async versus using a hook. Admin Settings edits does this with something like `const { fetch: fetchController } = useController();`

Also, switching Organizations probably should cause the whole page to reload.

**Comment by loripusey** [comment]
Can you show this to us after stand up today?

**Comment by sethdarragile6** [comment]
hey @TomNUSDS , should this story just go away in favor of the story I just create yesterday (with your help): #4352

**Comment by sethdarragile6** [comment]
never mind, you just killed it! https://github.com/CDCgov/prime-reportstream/pull/4388
closing this
