### ISSUE TITLE
Distribution Lists for Receivers and Senders

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4145]
Let's work on creating shareable distribution lists for all of our receivers and senders. This will come handy for release notes, bug fixes, and disruption in service announcement.

fyi @MauriceReeves-usds @sarahnw

**Comment by Adrian-Brewster** [comment]
Sorry @anshulkumar-usds  I didn't see that you assigned this to me. @sarahnw we can put this together pretty quickly using the shared inbox folders.

**Comment by Adrian-Brewster** [comment]
Currently compiling contacts per jurisdiction here: https://cdc-my.sharepoint.com/:x:/r/personal/mpz9_cdc_gov/_layouts/15/Doc.aspx?sourcedoc=%7Ba435b5bd-e042-4c58-a8c4-162b7b09a849%7D&action=editnew&wdPreviousSession=ced5336b-46b0-43a1-ab06-ccdea1ab7edb&wdNewAndOpenCt=1644964712441&wdo=4&wdOrigin=wacFileNew&wdTpl=blank&wdLcid=1033&wdPreviousCorrelation=bff75d55-bcda-445d-896c-b36f74f4c276
