### ISSUE TITLE
Globally Reduce Batch Size Limits for STLTs

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4147]
On 2/2, NJ requested that we limit the file size to under 5000 messages.

NJ pointed to one example file that contained 20,000 messages and caused memory issues in their system:

covid-19-3ba2e765-b06b-4eb0-a36c-f35aba199eb7-20220130143723.hl7 

**Ticket title, description and scope updated on 2/15**

We should consider reducing batch sizes for all states, and make this a global change across ReportStream. Consider a batch of 100 messages as the standard.

cc @MauriceReeves-usds @brick-green-agile6

**Comment by anshulkumar-usds** [comment]
2/15: Based on the 1/30 failures, and ongoing requests from WA-HIE to reduce batch sizes, we should consider making this a global change across all STLTS.

**Comment by MauriceReeves-usds** [comment]
Moved to sprint backlog.

**Comment by MauriceReeves-usds** [comment]
@anshulkumar-usds I've completed this. The PR is out.
