### ISSUE TITLE
NH - Duplicate Submissions (Failures from 1/30)

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4151]
Checking with NH to see if they have a need for resubmissions and which options suites them best.

**Comment by anshulkumar-usds** [comment]
NH wants to know how many messages were effected due to this and their message IDs. Please share the message IDs before any resubmissions are attempted

**Comment by MauriceReeves-usds** [comment]
Looking at the results, I only see one record sent multiple times to NH: `48de367d-c704-43ff-8b70-25adf16122b7`. @Adrian-Brewster will follow up with them and ask them how they'd like us to proceed.

**Comment by Adrian-Brewster** [comment]
Reached out to Zedd for resend

**Comment by Adrian-Brewster** [comment]
Message resent.
