### ISSUE TITLE
Update homepage layout with new sender content

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#4156]
## Problem statement

This is spun out of #3348.

RS is currently not communicating what we offer for senders on our homepage.

## What you need to know

[Content document](https://cdc.sharepoint.com/:w:/t/USDSatCDC/Ee6kAtuIKlxEsNQwaeiUcpIBMt29ktZNxmdSW_qRmyW8Fw?e=W0dTCU)
- Incorporate feedback/notes from Product at top of doc

## Acceptance criteria

- [ ] Homepage Layout is updated to capture high-level overview about what we do for Senders
- [ ] Content links (can direct senders to other pages within RS website)
- [ ] Incorporate Sender proposed content into existing content
- [ ] Remove images

## To do

- [ ] Update [mockup in Figma](https://www.figma.com/proto/VrSkTA87t8PPeXPugQ0i8O/ReportStream?page-id=754%3A0&node-id=754%3A315&viewport=298%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=1150%3A470)
- [ ] Re-work previous content.json file to accommodate sender content
- [ ] Re-work homepage template to fit in new content (for senders)
- [ ] ...

**Comment by rachelhanster** [comment]
Closing this and renewing focus on API senders. cc @drew-usds
