### ISSUE TITLE
Core Bio Labs - CSV Sender Onboarding

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#4158]
## Sender Info:
- Sender/Company Name: Core Bio Labs 
- Type of Sender: Commercial Laboratory
- Location: OH
- RS sender_id: corebiolabs-oh

## Initial Interest & Follow Up
- [x] Document the date & time the Sender expressed interest -- 2/2/2022
- [x] Send Std Kickoff email.  This includes:

         - Links to TOS & TOS Registration
                 - https://reportstream.cdc.gov/terms-of-service
                 - https://reportstream.cdc.gov/sign-tos 
         - Links to the CSV upload guide and CSV schema documentation
                 - https://reportstream.cdc.gov/getting-started/testing-facilities/overview
         - Provide an option to have a Kickoff call to review these documents and answer any questions.
- [x] Schedule Kickoff / Q&A meetings at the Senders request.
- [x] Received TOS.

## Sender Setup - Create OKTA group & OKTA account
- [x] Define the RS sender_id  --  corebiolabs-oh
- [x] Create an OKTA group for the sender_id
- [x] Create an OKTA account using the RS Registration information.
- [x] Verify OKTA account registration by the Sender.

## Sender Setup - Create Sender Settings for Staging & PROD
- [x] Locally, create and test Settings in organizations.yaml
- [x] Create the Staging & Production YAML settings files

## Testing - Prod/Test Internal
- [x]  Move all RS development to Staging & PROD.
- [x] Make settings change to block results to the STLT, or send all results to the STLT's Test Feed.
- [x] Validate Production data and make all necessary RS changes.  Iterate through testing until validation is complete.

## Testing - Prod/Test External (if required by the STLT
- [x] Contact the STLT to setup testing with Production data in their Production environment.
- [x] Verify which Feed the STLT wants to receive the results.  Make settings changes as-needed and deploy to PROD. 
- [x] Work directly with the STLT to complete Integrated Testing and gain approval to move into Production.
          - Prod/Test External (if required by the STLT)

## Implementation - Plan & Schedule GO LIVE
- [x] Change setting "customerStatus:" to active from testing.
- [x] Contact RS Pipeline Team to turn on HHSProtect reporting.
- [x] Determine if there is a backlog of results.  If so, contact the STLT to determine what results are needed.  Example, in at one STLT, if a Sender has reported positives only to the STLT, then the STLT wants all COVID (positive & negative) since the Sender started testing.
- [x] Coordinate and schedule a start date for daily results and backlog results between the STLT and the Sender.

## Implementation - GO LIVE and Post LIVE Review
- [x]  Monitor daily uploads for errors and contact Sender if results need to be corrected and resent.  Monitoring will typically be 1 week in duration unless issue are found.

**Comment by rhood23699** [comment]
Email'd CoreBio to give them a heads on about receiving an activation email.  Turns out they have an OKTA account, so I created an OKTA group and added their account.  I also created and deployed their YML Staging & PROD settings today, tomorrow at the latest.

**Comment by rhood23699** [comment]
Updated Staging & PROD and created PR #: 4168.  Email'd Core Bio Labs that they are ready to test.

**Comment by rhood23699** [comment]
They are configured on our side.  We have a kickoff call on 2/4/22 at 9:30a CT

**Comment by rhood23699** [comment]
Adrian is contacting Core Bio because they didn't join today's call.

**Comment by rhood23699** [comment]
2/7/22 Below are notes from Victoria.  Summary, kickoff completed, CSV development will be started by Core Bio.  No estimate on starting testing.

Some insights from follow up kick-off call with CoreBioLabs for CSV upload pilot. cc: @Rick Hood @Adrian Brewster @sarah add anything I missed.
@Rick Hood went over the unique schema requests for our standard schema (LOINC and equipment model name)(Berni and Drew maybe we call this out in the schema documentation); With them they will likely have different facility names since they work with a lot of schools.  
Value added for them is that data they send to CA PHD will be sent to Los Angeles County.  
They would like to discuss long-term moving to an HL7 option (@Adrian Brewster) 
They asked in CSV was case sensitive (@Rick Hood has a ticket out there for this) 
They asked about estimated time to be up and running noting this is a common question potential sites are asking.
Research will f/u with them once in production to debrief and run query on Metabase and get post - to evaluate the pilot.
@Dawn L. Low (IL, she/her) @drew.gardner they are open to do a call to on submission history or other designs or feedback on error messaging. They are open to it and I affirmed this was part of pilot.

**Comment by rick** [comment]
![giphy (16)](https://user-images.githubusercontent.com/6259/153062556-e36853b9-a1f8-482e-9069-f88a5489d568.gif)

cc https://github.com/rick/you-rang/issues/1

**Comment by rhood23699** [comment]
Moved Core Bio Labs to Production.  We'll watch for results.

**Comment by rhood23699** [comment]
2/11/22 Three results sent.  Waiting on CA-DPH validation.

2/12/22 Seven results sent.  Waiting on CA-DPH validation.

**Comment by rhood23699** [comment]
'2/12/22 thru 2/14/22 Only 10 results.  CA-DPH has accepted all, but with a request to receive RACE codes.  Currently receiving OTHER.

**Comment by rhood23699** [comment]
'2/16/22 Create an addition OKTA account

2/16/22 CA-DPH is asking Core to collect the Race & Ethnicity consistently.

2/18/22  Moving Core Bio to Done/Completed.
