### ISSUE TITLE
WY - Duplicate Submissions (Failures from 1/30)

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4162]
Inductive sent a list of messages that need to be resubmitted. See attachment and refer to sheet for WY.

[https://app.zenhub.com/files/304423150/452538ad-f1aa-4635-b2fb-fe6d2153166d/download](https://app.zenhub.com/files/304423150/452538ad-f1aa-4635-b2fb-fe6d2153166d/download)

**Comment by brick-green-agile6** [comment]
Results needing to be resent. Pulled from spreadsheet.
```
30637f45-0f98-4e09-b693-d6489de3764f
bd42c1e4-e6f5-44a7-89d7-c57e71d1f92d
12e87fd4-9938-44ee-bc88-3e1abb4a41cf
48266e6d-7eb1-407d-b5ec-d8928404af7a
e15ba9f1-5b4e-4670-8883-4f34a1e64127
```

**Comment by anshulkumar-usds** [comment]
The messages Brick listed above are from the excel sheet. So just need to resubmit these 5 for WY

**Comment by zdeveloper** [comment]
Done, resubmitted 
30637f45-0f98-4e09-b693-d6489de3764f
bd42c1e4-e6f5-44a7-89d7-c57e71d1f92d
12e87fd4-9938-44ee-bc88-3e1abb4a41cf
48266e6d-7eb1-407d-b5ec-d8928404af7a
e15ba9f1-5b4e-4670-8883-4f34a1e64127

**Comment by anshulkumar-usds** [comment]
Inductive is reviewing the resubmissions.

**Comment by brick-green-agile6** [comment]
filename:

covid-19-fdf3598f-12c2-46c5-932d-241c8f6bef22-20220203181544.hl7

**Comment by anshulkumar-usds** [comment]
2/10: Checking with Inductive if anything is pending
