### ISSUE TITLE
AK - Duplicate Submissions (Failures from 1/30)

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4167]
Inductive provided list of messages that need to resubmitted. See attachment

[https://app.zenhub.com/files/304423150/e2065708-b7cd-4ce0-9626-22991c552b3c/download](https://app.zenhub.com/files/304423150/e2065708-b7cd-4ce0-9626-22991c552b3c/download)

**Comment by brick-green-agile6** [comment]
Inductive health requested one result for resend: eb77b5e6-a90e-481d-8b21-9c2446674ee0

**Comment by zdeveloper** [comment]
OK resent "eb77b5e6-a90e-481d-8b21-9c2446674ee0"

**Comment by anshulkumar-usds** [comment]
Inductive is reviewing the resubmissions.

**Comment by brick-green-agile6** [comment]
filename: covid-19-a1301cce-c402-44be-a166-b5fd70d46149-20220203181545.hl7

**Comment by anshulkumar-usds** [comment]
2/10: Checking with Inductive if anything is pending
