### ISSUE TITLE
Send ReportStream-branded Multi-Factor Authentication Email when MFA Activated for ReportStream Users

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4179]
## Problem Statement
As an organization who wants to activate my OKTA account in order to gain access to ReportStream, I would like to see some branding for ReportStream when I activate my OKTA account.

## Acceptance Criteria
- Given I
    - Am a user who received an activation email for ReportStream
- When I
    - Set up my password, security questions & answers, and MFA method
    - Submit my information
- Then 
    - OKTA sends the ReportStream-branded MFA email to the users if they are ReportStream users

**Comment by chris-kuryak** [comment]
Old. I will be taking lead on setting up new RS Okta instance in #4573.
