### ISSUE TITLE
Change the Main OKTA Account Image to a Different Logo

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4185]
## Problem Statement
As an organization who wants to activate my OKTA account in order to gain access to ReportStream, I would like to see some branding for ReportStream when I activate my OKTA account.

## Acceptance Criteria
- Change the Main OKTA Account Image to a new logo

**Comment by chris-kuryak** [comment]
Old. I will be taking lead on setting up new RS Okta instance in #4573.
