### ISSUE TITLE
Settings API: update org validation treats empty string as potential value for stateCode and countyName

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#4193]
**Describe the bug**
When submitting a PUT call to the /api/settings/organizations/{org} endpoint with FEDERAL as the jurisdiction and empty string ("") as the stateCode and countyName, the API sends a 400 Bad Request and sends the message "stateCode or countyName not allowed for FEDERAL organizations".

![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/c45b8d67-ecfb-47a4-86e0-eb2e483a86b4)

If stateCode and countyName is _null_, then it passes validation

![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/da6bb9d9-bac1-490a-ad8c-284a19826a40)

**Impact**
This was discovered during the course of development on the Organization Settings webpage, and a simple workaround was to convert these values to null before passing them on to the API call. So the overall impact is minimal, however a consumer would expect that an empty string and a null would be treated the same and no workaround should be needed.

Also, there might be other PUT calls in the settings endpoint group where similar treatment of null vs empty string values might lead to similar situations- i.e. in the receiver and sender updates. It would be nice to quickly hunt down and correct those while we're in there, so that this behavior is consistent throughout (and therefore lead to cleaner code by the consumer).

**To Reproduce**
1. Execute a curl/Postman/etc call as described/screenshotted  above
2. Observe the validation message

**Expected behavior**
Submitting either a null or an empty string for these values should yield the same result

**Screenshots**
See above

tagging @TomNUSDS

**Comment by sethdarragile6** [comment]
hey @MauriceReeves-usds, we noticed this while working with the API. Not sure if it's an issue but it was confusing. If you agree, who would be a good person to assign to it for investigation?

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/4193?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @oslynn @smythe5 @whytheplatypus

**Comment by MauriceReeves-usds** [comment]
@oslynn I am assigning this to you.

In `src/main/kotlin/azure/SettingsFacade.kt` there is an `OrganizationAPI` class that is responsible for saving an organization. The business rules for an organization state that if an organization has a jurisdiction type of `FEDERAL` then it cannot have a value in either `stateCode` or `countyName`. It should default to NULL. When someone submits an empty string, it should accept that as functionally equivalent to null.

If you look at the `consistencyErrorMessage` function in Organization.kt, that is where the error message "stateCode or countyName not allowed for FEDERAL organizations" comes from, but I don't think you should fix it there. I would instead emulate the `trimToNull` function we have other places. The functionality is pretty straightforward. We already have this method in Report.kt. I would move it out to a common class instead:

```
       private fun String?.trimToNull(): String? {
            if (this?.isEmpty() == true) return null
            return this
        }
```

For testing, coordinate with @sethdarragile6 to check it out locally. You can also curl to your local API to test.

**Comment by MauriceReeves-usds** [comment]
FYSA: @Adrian-Brewster @anshulkumar-usds @sarahnw I'm going to put this into sprint backlog for @oslynn to work on.

**Comment by oslynn** [comment]
The input payload for testing:
{
    "name": "ignore",
    "description": "FOR TESTING ONLY sdsd",
    "jurisdiction": "FEDERAL",
    "stateCode": "",
    "countyName": "",
    "filters": [
        {
            "topic": "covid-19",
            "jurisdictionalFilter": [
                "matches(ordering_facility_state, IG)"
            ],
            "qualityFilter": null,
            "routingFilter": null,
            "processingModeFilter": null
        }
    ]
}
