### ISSUE TITLE
CO - Routt County Public Health Download Site

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4194]
Please setup access to the download site for Routt County Public Health in Colorado

**Comment by Adrian-Brewster** [comment]
Needs contact information

**Comment by anshulkumar-usds** [comment]
Provision access to: 
Nicole Harty 
nharty@co.routt.co.us

**Comment by Adrian-Brewster** [comment]
Waiting for PR to be approved.
