### ISSUE TITLE
NJ - Truncate Performing Org Name to 50 chars for OBX-23.1 and AOE

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4197]
NJ needs the performing organization name to be truncated to 50 chars in OBX-23.1 and across all AOE questions.

Sample messages with this issue can be found in file "CDC_PRIME_covid-19-53f131f0-9f03-42a0-9b7f-0ca016b71b5f-20220203141620.hl7" 

![asdadadadadada.PNG](https://images.zenhubusercontent.com/607d9d4a591b7cc0bb55c82e/821f5489-6752-46c3-89da-b0e21b4d6e39)

**Comment by Adrian-Brewster** [comment]
Lets make this a global change.

**Comment by jorg3lopez** [comment]
Fix is in master and the test result has been resubmitted to their prod feed.
file name:
`covid-19-cdd3cc12-6903-4122-9463-d7ee3afbe278-20220223231406`

**Comment by jorg3lopez** [comment]
[https://app.zenhub.com/files/304423150/81f3472c-15d2-4cef-83ca-b2105759ad65/download](https://app.zenhub.com/files/304423150/81f3472c-15d2-4cef-83ca-b2105759ad65/download)

**Comment by Adrian-Brewster** [comment]
"It looks like the OBX-23.1 was the one worked on last year.  For the OBX segment with the Lab Test, that gets truncated, but not for the OBX segments with the AOE’s."

From Nicholas

**Comment by jorg3lopez** [comment]
@Adrian-Brewster Correct. The truncation logic for the OBX iterations was not working properly. The fix is in production already and I have resent 96 additional test results.
file name:
`covid-19-d884d2b4-8693-4af7-9dcf-e25e4074b994-20220225225904`

**Comment by anshulkumar-usds** [comment]
On 2/25, @jorg3lopez noted that 96 additional test messages were sent to NJ related to OBX-23.1 truncation in the following file:

covid-19-d884d2b4-8693-4af7-9dcf-e25e4074b994-20220225225904

**Comment by anshulkumar-usds** [comment]
3/1: Checking with NJ if this is good on their side.

**Comment by anshulkumar-usds** [comment]
3/3: NJ validated the data. Closing.
