### ISSUE TITLE
MN - Missing Specimen Collection Date

### ISSUE THREAD

**Issue by brick-green-agile6** [CDCgov/prime-reportstream#4198]
From: Cassman, Jacqueline (MDH) 
Sent: Wednesday, February 2, 2022 3:42 PM
To: Judd, Michael (CDC/DDPHSS/OD <vuj4@cdc.gov>; Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR <rut5@cdc.gov>; Reeves, Maurice (CDC/OCOO/OD <qva8@cdc.gov>; Brewster, Adrian (CDC/DDPHSS/OD) (CTR <mpz9@cdc.gov>; Liu, James (CDC/OCOO/OD) <qpu0@cdc.gov>
Subject: MDH: CDC Prime ELR Error 1/27/22
 
Good afternoon,
 
MDH received an ELR message that was missing OBR 7, Observation Date/time. Are you able to correct and resend the message please?
 
```
Accession ID:
00356bbf-0e49-4741-b66a-34364703dbcf
```
 
Thank you,
Jacqueline
Jacqueline Cassman, MPH
Electronic Case Reporting (eCR) Onboarding Coordinator | MEDSS Operations 
Pronouns: she/her/hers
Minnesota Department of Health
Office: 651-201-4269

**Comment by brick-green-agile6** [comment]
@Adrian-Brewster @anshulkumar-usds I checked into this. ImageMover did not send the specimen collection date. Should we request they resend?

```
Message ID:
00356bbf-0e49-4741-b66a-34364703dbcf
```

**Comment by MauriceReeves-usds** [comment]
@brick-green-agile6 yes. And they should always be sending that to us. @Adrian-Brewster @anshulkumar-usds please ask them to resubmit this record, and to make sure they're always sending us this. In fact, we should maybe update their schema to force that value to have a cardinality of one if it doesn't already. I can't really think of a single location that would accept a message without the specimen collection date.

**Comment by anshulkumar-usds** [comment]
2/14: Checked with IM and requested to make this a priority

**Comment by Adrian-Brewster** [comment]
Anshul following up with IM.

**Comment by anshulkumar-usds** [comment]
IM confirmed resubmitting. MN notified.
