### ISSUE TITLE
MS - Northwest Health and Wellness OBX-3 Confusion

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#4202]
**Describe the bug**
ELR messages from Northwest Health and Wellness Clinic where the Resulted Test LOINC (OBX-3) of "95423-0" appears to be resulted out incorrectly. 

From PHA "We see that a Detected result was provided in OBX-5, and we are not entirely sure which virus is detected from this field. Can we get clarification of how this LOINC is being resulted out and if this can be addressed for all CDCPRIME messages going forward? Would it be possible for the facility to provide a result specific SNOMED (such as|840533007^SARS-CoV-2^SCT| if SARS-CoV-2 was detected) in OBX-5 instead?"

**Examples**
OBX|1|CWE|95423-0^Influenza virus A and B and SARS-CoV-2 (COVID-19) identified in Respiratory specimen by NAA with probe detection^LN^^^^2.69||260373001^Detected^SCT|...

**Affected Files**
```5ce85a0c-87f8-4df2-82f7-50bb22936fc6```
```e9283a3c-bbb6-408a-a0f7-b97126e89683```
```9e9c2108-ecaa-420c-8b7f-6aed27b898eb```
```4f12a031-7f8e-4bf0-b414-7f794733563e```
```0034efe6-65a5-4a9b-992c-6a30cdee7a0a```
```33b57da9-ea18-4090-a163-75e6822ec18c```
```8e047232-0692-487f-a834-910ada049865```
```3e77e6fc-0707-45eb-a69e-bf44401577cd```

**Comment by anshulkumar-usds** [comment]
Zedd - these messages point to a multiplex assay with a non-specific LOINC. I think you may need to update the LOINC to point to the COVID specific test and resubmit these to MS.
cc @LGFranklin

**Comment by anshulkumar-usds** [comment]
MS/Inductive's concern isn't the LOINC code itself. Sample accession:
```5ce85a0c-87f8-4df2-82f7-50bb22936fc6```

We see that a Detected result was provided in OBX-5, and we are not entirely sure which virus of the three is detected from this field. We’re looking at the values from cell E218 in the “LOINC Mapping” sheet of the LIVD mapper and we do not see the “Detected” result as mentioned above for this LOINC. Our concern is that just using “Detected” as the Test Result does not provide much information for 95423-0, would it be possible for the facility to provide a result-specific SNOMED (such as |840533007^SARS-CoV-2^SCT| if SARS-CoV-2 was detected) in OBX-5 instead? If all three viruses were detected for the LOINC 95423-0, shouldn’t the results be formatted like the example below instead? 
```
OBR|1|2005700000392-41^PHLIP-Test-EHR^2.16.840.1.113883.3.72.5.24^ISO|1905700000256-176^STARLIMS.AR.STAG^2.16.840.1.114222.4.3.3.2.5.2^ISO|95422-2^FluAB + SARS-CoV-2 Pnl Resp NAA+prb^LN||...
OBX|1|CWE|95423-0^FluAB + SARS-CoV-2 Resp NAA+probe^LN|1|840533007^SARS-CoV-2^SCT|||...
OBX|2|CWE|95423-0^FluAB + SARS-CoV-2 Resp NAA+probe^LN|2|407479009^Influenza A virus^SCT||||...
OBX|3|CWE|95423-0^FluAB + SARS-CoV-2 Resp NAA+probe^LN|3|407480007^Influenza B virus^SCT|||||...
```

**Comment by MauriceReeves-usds** [comment]
@anshulkumar-usds I think this is related to the the issue we had back from the bug Carlos introduced. Let's have Zedd resubmit these. Our system should handle them fine now.

**Comment by anshulkumar-usds** [comment]
3/1: Checking with Inductive on resubmissions

**Comment by anshulkumar-usds** [comment]
3/4: MS confirmed they do not need resubmissions, and are ok with the fix in place for future submissions.
