### ISSUE TITLE
Warrior Diagnostics - CSV Sender Onboarding

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#4204]
## Sender Info:
- Sender/Company Name: Warrior Diagnostics in CO
- Type of Sender: Commercial Laboratory
- Location: CO
- RS sender_id: warrior-dx-oh

## Initial Interest & Follow Up
- [x] Document the date & time the Sender expressed interest -- 2/3/2022
- [x] Send Std Kickoff email.  This includes:

         - Links to TOS & TOS Registration
                 - https://reportstream.cdc.gov/terms-of-service
                 - https://reportstream.cdc.gov/sign-tos 
         - Links to the CSV upload guide and CSV schema documentation
                 - https://reportstream.cdc.gov/getting-started/testing-facilities/overview
         - Provide an option to have a Kickoff call to review these documents and answer any questions.
- [x] Schedule Kickoff / Q&A meetings at the Senders request.
- [x] Received TOS.

## Sender Setup - Create OKTA group & OKTA account
- [x] Define the RS sender_id  --  warrior-dx-oh
- [x] Create an OKTA group for the sender_id
- [x] Create an OKTA account using the RS Registration information.
- [x] Verify OKTA account registration by the Sender.

## Sender Setup - Create Sender Settings for Staging & PROD
- [x] Locally, create and test Settings in organizations.yaml
- [x] Create the Staging & Production YAML settings files

## Testing - Prod/Test Internal
- [x]  Move all RS development to Staging & PROD.
- [x] Make settings change to block results to the STLT, or send all results to the STLT's Test Feed.
- [x] Validate Production data and make all necessary RS changes.  Iterate through testing until validation is complete.

## Testing - Prod/Test External (if required by the STLT
- [x] Contact the STLT to setup testing with Production data in their Production environment.
- [x] Verify which Feed the STLT wants to receive the results.  Make settings changes as-needed and deploy to PROD. 
- [x] Work directly with the STLT to complete Integrated Testing and gain approval to move into Production.
          - Prod/Test External (if required by the STLT)

## Implementation - Plan & Schedule GO LIVE
- [x] Change setting "customerStatus:" to active from testing.
- [x] Contact RS Pipeline Team to turn on HHSProtect reporting.
- [x] Determine if there is a backlog of results.  If so, contact the STLT to determine what results are needed.  Example, in at one STLT, if a Sender has reported positives only to the STLT, then the STLT wants all COVID (positive & negative) since the Sender started testing.
- [x] Coordinate and schedule a start date for daily results and backlog results between the STLT and the Sender.

## Implementation - GO LIVE and Post LIVE Review
- [x]  Monitor daily uploads for errors and contact Sender if results need to be corrected and resent.  Monitoring will typically be 1 week in duration unless issue are found.

**Comment by rhood23699** [comment]
2/3/22 - Adrian send kickoff request.

**Comment by rhood23699** [comment]
2/4/22 Completed all Sender Setup.  (OKTA, YML and move to PROD & Testing).

**Comment by rhood23699** [comment]
Will help with account activation problem today.  They are setup and we are ready to receive test files.

**Comment by rhood23699** [comment]
2/9/22  Receive a test file through secure email because uploading failed.  The file was not in our CSV format.  It was in CO's CSV format.  Email'd back and let them know we needed it in our format.

**Comment by rhood23699** [comment]
2/11/22 Had a Zoom with Megan.  She finally got the LIVD fields correct, but she did find a problem with us not accepting Saliva as a specimen type.  I'm fixing it now for Tuesday release.

She was frustrated.  Said our format is far harder to meet than Colorado's which is true.
CC:  @loripusey @rachelhanster @victorialb-usds

**Comment by rachelhanster** [comment]
Zoom call: Sounds good.
Data schema: Why? What exactly is leading Megan to say that reportstream's data schema is "harder to meet than Colorado's"?

**Comment by rhood23699** [comment]
'2/15/22 First test file looks good.  Submitted it to CDPHE.

2/16/22 CDPHE doesn't see the file.  I resubmitted it.

2/17/22 First test file looks good.  I've sent to CDPHE for validation.  Received OK to move to PROD.  Waiting on first PROD file.

**Comment by rhood23699** [comment]
Closed out this Sender, but did email them to capture Race & Ethnicity because most are UNK.
