### ISSUE TITLE
Update ImageMover Schema to make Specimen Collection Date to have a Cardinality of One

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#4206]
Based on the ticket @brick-green-agile6 created for a message MN received without a specimen collection date (#4198) we need to update the schema for Image Move to make sure they're always sending us that value. Let's add the value to their schema and update the cardinality and then test it out.

FYSA: @Adrian-Brewster @anshulkumar-usds

**Comment by oslynn** [comment]
How to test: curl -X POST -H 'client: imagemover' -H 'Content-Type: text/csv' --data-binary '@/home/jorg3/Desktop/CDC/sample-data/ma-imagemover-to-resend-20220131.csv' localhost:7071/api/reports

**Comment by oslynn** [comment]
Acceptance: 
1.) check ./build/sftp/<file output>.hl7
2.) check segment SPM-17 to see the same date as the test_result_date.

**Comment by Adrian-Brewster** [comment]
Already merged. No feedback from ImageMover.
