### ISSUE TITLE
route messages about HL7s to a new fhirengine queue

### ISSUE THREAD

**Issue by JGreenFearless** [CDCgov/prime-reportstream#4210]
Acceptance Criteria:

- if ReportFunction.kt detects an HL7 file, put a message on a new fhirengine queue with a reference to the report_id of the submitted raw HL7.
- a new FHIREngine function grabs the message from the queue.

_(the above could be its own ticket)_

- The FHIR engine takes the message off of the queue, reads the file from the blob,  and compares it to itself.
- This is not running in Prod
- Successful smoke test of FHIR Engine
- Results of the test are printed to STDOUT/logs

## Design Thoughts

- The FHIR Engine will be written as a separate Azure Function, and will include both the (future) Engine and the Test/Comparison tool combined, for now.

**Comment by whytheplatypus** [comment]
![FHIR Engine Progression - Page 1.png](https://images.zenhubusercontent.com/611d33d5e624dd44c803bcf4/c1e84c90-d0fd-478b-a2f1-b73d279ca31e)
