### ISSUE TITLE
HL7 to FHIR translation

### ISSUE THREAD

**Issue by JGreenFearless** [CDCgov/prime-reportstream#4211]
Acceptance Criteria:
- HL7 Message is converted to FHIR Bundle
- Unit tests

**Comment by whytheplatypus** [comment]
![FHIR Engine Progression - Page 1(1).png](https://images.zenhubusercontent.com/611d33d5e624dd44c803bcf4/60ed790b-8ba0-43b3-9993-3d9926ae1850)
