### ISSUE TITLE
Write a first draft of a FHIR profile for our systems for full ELR

### ISSUE THREAD

**Issue by JGreenFearless** [CDCgov/prime-reportstream#4212]
As a ReportStream user / dev I want to know what data we're storing in the FHIR bundle and how it's represented in FHIR.

AC:
- The profile is based on https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-observation-lab.html
- All fields which have an hl7Field  from the base covid-19.schema have a representation in FHIR.
- Document those fields in covid-19.schema that are not covered.
- Record the relationship between the covid-19.schema columns and FHIR resources
- The result is represented as JSON-Schema
- Generate one or more examples of the corresponding FHIR JSON

**Comment by jimduff-usds** [comment]
@whytheplatypus says this needs to be re-groomed.

**Comment by whytheplatypus** [comment]
relates to #4469

**Comment by JGreenFearless** [comment]
@clediggins-usds @carlosfelix2 Do we still need this ticket, or have you two covered this in the tickets you wrote?

**Comment by carlosfelix2** [comment]
Closed while we figure out what we really want to do with profiles if anything.
