### ISSUE TITLE
Begin using the action history processes for the FHIR Engine

### ISSUE THREAD

**Issue by JGreenFearless** [CDCgov/prime-reportstream#4214]
Acceptance Criteria:
- When an HL7 file is sent to the $convert-data endpoint an action history is created
- Details and Errors are entered as ActionLogs

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/4214?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @oslynn @smythe5 @whytheplatypus

**Comment by TurkeyFried** [comment]
Action History uses an enum called `task_action` for the action name. `translate` is already a valid value, so these entries should use it.

**Comment by TurkeyFried** [comment]
As per discussion, the History API call part will be split into a new ticket.

**Comment by TurkeyFried** [comment]
#4824
