### ISSUE TITLE
FL - Invalid CLIA number 

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#4227]
FL received 50 results from ReportStream containing an invalid CLIA number. The following CLIA number was provided : ```10D2251395```
 
Please provide the correct CLIA number for the patient with the accession numbers below:
 
specimen ids
```0cb30225-903a-4299-91c8-b85355b97f58```
```3aed2bd2-5b79-49f3-b4c6-661fc700adb3```
```a631f5aa-9ceb-4c2f-b969-70b6fd5f060c```
```f0abdefa-ebc1-4ead-b5ea-8a83d3cd4c04```
```81b15dc7-f82d-4fa6-b2ad-f8432d7e822a```
```99cd9ed0-c226-4ad6-a8b0-ef82516b4b65```
```78d00418-aa62-41d1-b897-ae4f0813b2ac```
```f8911362-a322-452d-82ed-4df748ad2183```
```a02dfb74-481b-413c-905b-b651331a9f93```
```cbbce1c2-ce13-4e3d-9179-995a2414f5f6```
```88e30c8a-816d-4f86-add5-3a06fc10c3bb```
```431466e5-13f7-47c1-a087-99029a3433e6```
```fdc01aae-8c92-45f9-b450-8e4d85a7795c```
```94746056-a91f-4d54-a169-fbc2518ef0cf```
```ad349fc3-4a73-4fad-9190-45d84d60c887```
```8967ef3f-794a-4605-9c3a-1e74f9806211```
```25840c56-1f09-4d55-b980-c8b4c77f8654```
```9480ea28-d052-4f22-afa3-75f0bb55559b```
```761d8363-dd29-4246-ac82-91f04d03add4```
```c9cb5721-9ffe-4c13-b2c3-e7efa1650d4f```
```7e8465b7-ebd2-49bf-ab8b-8dcebc76b6e2```
```744ea4f7-4a10-40f2-9030-043918c587ee```
```0b3156ee-d472-4ff4-8a59-c4b874f62cb9```
```b39239a4-3c35-453c-b03d-e1b497e956db```
```974d2063-573f-4439-ad66-a96053249a69```
```80798986-a66d-4822-bf2e-779b003f3c3a```
```dc9c4c8f-47d0-4d45-9dc0-eaa8a96d1f00```
```01a1ba03-230d-4a4b-81b4-6859de031f83```
```69b6c624-dd08-4a6b-8895-2dffb63442b9```
```0885e9a5-00db-4498-84ef-c15d21c0e361```
```5694a16b-a0ed-4b13-b735-0fbe7b5ac915```
```35435402-1177-4bfc-bcf2-4b0a8a27212b```
```7acffd84-4a92-42f9-b202-1c9f3386c16e```
```9d2670c7-8e1b-4dac-874c-d105747227a1```
```96b29b28-8ee1-4152-90cf-cb9d6ef58518```
```498cc776-2013-48d5-b13b-1bbcb07f5b6d```
```0f52240b-89c6-4fbd-899a-e2a712b52059```
```4eb3aa4a-9ae0-4076-886d-5e3096a512b0```
```8622e2a3-a0e7-4bc7-9913-107a04adc92d```
```7dd1ba60-1107-465b-ac74-26b270e6b2f2```
```899218e6-3c1c-4078-ad82-253e68322d68```
```9be5dcb8-4838-4f54-87e7-358667edf5ec```
```634b0943-29b6-4071-b306-1f5b8aafff5b```
```e79337a3-7a1b-452d-9ccf-0d5ebd0aa194```
```e0732d8b-e307-4b29-a64c-a4b23dd9f8c7```
```726abb86-086d-4cd4-bda6-edf2937df637```
```9b9bb31d-203c-453d-aa59-700f60181a61```
```bb817210-abf0-43d8-8dcd-2de251b53f4b```
```344c763f-9844-49c4-b5f0-5dd553e27987```
```3159130f-c7b6-46f6-8b0e-b81cdc0efa85```
```6814f74f-d403-418c-91d9-80214df774c8```
```d9f7b62b-e269-4be4-867f-ceae572821e4```
```14aa4d0e-d5fd-489e-8775-3696052cfcff```
```9b52a90c-3efb-4175-9ad1-fd3727af6219```
```891b91e4-b2b4-41f1-a28a-86ba7c1c7c3f```
```dcc251ae-5f6b-4c0a-8f15-57214286d89c```
```e35056ab-c8a6-4cb2-8555-74231d5cbd2c```
```cfb37f21-c66c-4c61-a5d9-63f0b78a34a7```
```c55eb03b-449d-4e50-858a-8a89c8d2b271```
```e534942c-3f7c-439f-8265-e474afa37130```
```c9b3ec1b-3293-46e2-ae58-d4badd737f74```
```1bca2ac3-de95-4b83-a4f5-5badd7031868```
```d78c39b8-5ddf-4cc5-add6-34f81818712e```
```a81929ff-2b30-4afa-a895-0b881a7db5dd```
```85f9ac63-142f-46d1-b504-d5614ce98831```
```b981edb7-487f-49f0-822a-92b27d93a958```
```bccef97c-4798-45a1-b6de-9bf1760be7bc```
```520587a9-fb71-48dc-ac11-8a40e54d3a4c```
```74a98fec-5664-4d43-af61-7065e2d0b5db```
```dc9ef14a-f6e3-40e4-97e6-aaeafe6d09c0```
```2ca9fad2-e2b3-4020-a227-cfde5f2e5ad7```
```7d18f5ef-068d-4ab7-8980-64d3d5597cf3```
```8e390c35-93e7-4870-8b49-157594606bae```
```e9ef4b2b-efa7-4354-a318-fd69c729123b```
```b6f8fa5b-1862-4a7a-9db9-ec93455e8f15```
```3939ddcf-d967-4ec5-8f5e-47188168865c```
```32392c45-7b88-4f47-940c-bca0fa3b7367```
```27e3abf8-3c5c-41a9-b1bd-9b03a04de4fb```
```4159be9d-e3fc-48eb-a7d0-2f22712ae75a```
```c671b538-b951-458d-a73f-f2614a815757```
```eaa0c409-646a-4b3e-9715-18eed74a0afd```
```455c0da5-1ce0-4d98-87e4-36d3097d0d2b```
```a928deb5-e921-4eef-b692-39f004f15d03```
```0af8e813-e6a5-4f4b-808e-830659ea36a7```
```bc1810c8-1378-49d5-a44c-ccadf5f6d7c7```
```03005fe2-847e-4bc4-a02b-3fa8f7d416af```
```dce176c1-5ce7-4982-b46c-480872852737```
```3e6b0ba1-7675-4988-afe6-48498f0a8586```
```9d3da517-e9a2-487d-b8f2-93d9c3aab180```
```682e9906-0bc3-4953-b982-2a5c9ad0848c```
```a2f6ae1b-a071-46e5-a49d-25238d476fd6```
```c9316558-5e7e-4c0f-8b9a-4882642da100```
```b83e3a84-544c-4588-8eb9-7068196aef0c```
```5fbd0b51-385d-4b74-821f-cdfc67d326c1```
```38cfc3e3-4d68-4750-ba0d-a4652da0d048```
```2871cf36-e38b-4603-ae7c-9cd2448e2257```
```2e57e5c6-118e-41f7-aa2f-f4bc258fb2d6```
```324e78b1-1009-4e36-b89e-fe9b88eea211```
```7338706a-1527-4321-84c3-6d7945f77e0b```
```bda70d5f-32b7-4989-a9a9-9addc6b4019e```
```07ca82ae-01c3-4286-b995-85b3a2f7c12c```
```9af20413-81d5-4064-bcb6-34283aac4895```
```60b2a745-2b1b-4a22-b60d-45f02f0c0682```
```81aa1570-804e-4fc9-a4a1-2f705f97ba22```
```505b15f4-6a20-4cce-83c6-800e3d37ccd3```
```81d61137-9b05-457c-b2b3-7273210beb50```
```4aeeab2a-afdc-400e-b802-8f870b7013ce```
```c7631534-1b28-440c-9250-1a57c1e29353```
```e37093ed-170d-482d-b2a0-97eba95bdd4d```
```0412822b-063b-4cdb-8bc0-772a0dd9f50d```
```840f9d6b-696d-4742-86dd-1a74b869de49```
```748a4ddd-5194-4576-93e4-ba8cca07fd64```
```086c9f38-de9d-4634-92c2-78c6664c102f```

**Comment by Adrian-Brewster** [comment]
This is going to be addressed by the SimpleReport team. Leaving open until I hear from Leslie that the issue is resolved.

**Comment by anshulkumar-usds** [comment]
@LGFranklin assigning this you. Please let us know if anything is needed from ReportStream.

**Comment by LGFranklin** [comment]
I emailed the admin of this facility to request that they update the CLIA #.

**Comment by LGFranklin** [comment]
@anshulkumar-usds The CLIA is valid per the below. I am not sure how FL DOH wants to handle situations where it is valid but not yet in the "directory" 
![image](https://user-images.githubusercontent.com/81384847/153266325-76416079-6f44-411b-8eb6-4e8102fadf04.png)

**Comment by anshulkumar-usds** [comment]
@Adrian-Brewster  can you please share this with FL

**Comment by Adrian-Brewster** [comment]
Sent over to FL.  Waiting on a response. Moving to external review.

**Comment by LGFranklin** [comment]
Closing the issue --- Sent CLIA receipt and hone number to Kristin
