### ISSUE TITLE
AZ - ELR feed not transported on 2/6

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4231]
Our ops dashboard (https://prime.cdc.gov/metabase/question/23-needs-investigation-reports-not-transported-last-5-days)

shows that AZ's primary data feed on 2/6 failed to transport to the STLT. 

Report ID ``` a36593ac-d238-4bc0-ba7f-4a90e2094126 ```
Action ID ```6919991```

**Comment by anshulkumar-usds** [comment]
Outcomes: Make sure AZ gets the file, and root cause analysis why the report failed

**Comment by oslynn** [comment]
@jorg3lopez is looking into this.

**Comment by jorg3lopez** [comment]
Findings:
It appears that the transport params were missing at the time of sending the file during the batch process. Below is how it should look with the params:
![image.png](https://images.zenhubusercontent.com/60d4ee31a2886cc02f9caaef/fdfdaca7-b20c-4915-ad36-45c7e935094b)
Below it show this step is missing:
![image.png](https://images.zenhubusercontent.com/60d4ee31a2886cc02f9caaef/67b8e5af-ef76-445c-99d6-7731434a8479)

This needs further investigation. (03/02/2022)

**Comment by oslynn** [comment]
I am blocked.  I still can't access the Azure storage using my CDC credential.

**Comment by jorg3lopez** [comment]
@anshulkumar-usds Test results have been resent to AZ. (03/17/2022)
File name:
`az-covid-19-42ee57bb-6a6c-46fa-87f6-25c022125f02-20220317204900`

**Comment by anshulkumar-usds** [comment]
3/18: AZ notified.
