### ISSUE TITLE
API Sender Onboarding Content on RS Public Website

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4233]
After the review and updates to our API Programmer's Guide is completed by @jbiskie  in ticket https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3627, we need to start the work of getting this content up on our website to the senders are aware that two options exist for onboarding.

To do:
1. Work with Experience team to get this prioritized in their queue 
2. Engage with content designers (Bernie?) to get updates to the current language and structure

A/C:
1. Prospective senders to RS can understand that two equivalent options exist for transporting data to states
2. The onboarding process for API senders is clear and repeatable for senders of varying technical expertise
3. Reduce as many manual inputs as possible to make the process automated

FYSA @loripusey @rachelhanster

**Comment by rachelhanster** [comment]
@anshulkumar-usds Experience team is working on API documentation on public website right now. See https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4101 and https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4100

**Comment by anshulkumar-usds** [comment]
Closing this. Experience already working on this initiative.
