### ISSUE TITLE
Setup an Outbound version of Covid Results Metadata table

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4238]
Our current view into Covid Results Metadata table shows us what ReportStream received from senders. Several support tickets mention the STLTs receiving an altered form of data from our senders - expectedly so after applying our transformations and other customizations that the STLTs have requested,

The proposal is to create an outbound version of the Covid Results Metadata table so we can see what data was sent from RS to STLTS.

Details to be added after more discussion and definition.

cc @MauriceReeves-usds @jimduff-usds @cwinters-usds @Adrian-Brewster @sarahnw

**Comment by BerniXiongA6** [comment]
@MauriceReeves-usds is this the same as the work you're currently in the process of doing? Let @brandonnava or me know if we can assign this to you or close it or something else if it's not the same.

**Comment by brandonnava** [comment]
@brick-green Still useful? Can't we see results sent to STLTs in Metabase currently?

**Comment by brick-green** [comment]
The values in the covid_results_metadata table represent the data as we received it. It does not represent the data as we sent it to the STLT. I think we can close this though as we will be moving to the UP eventually which will have a different solution.
