### ISSUE TITLE
Make the new HistoryDetails API backward compatible with the current json response

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#4241]
Rather than do API versioning for now, we're just going to make the field names in the new history details API backward compatible with the current api/waters and api/reports json response.

This is pretty easy to do, as follows:

## Acceptance Criteria

Change the new HistoryDetails fields as follows:

- Change "submittedAt" to "timestamp"
- Change "submitter" to "sender"
- Add  "reportItemCount" with integer value of the item_count for the submitted report.
- Add "destinationCount"  (be careful!  This is NOT just the number of items in the destinations array.  This is the number of destinations receiving one or more items.  Don't include destinations receiving zero items)
- Add externalName field.   (Often null, but very valuable to CSV Uploader UI users.  Currently found in the action.external_name column.   Note: Its currently set to only display when non-null.  See #4309 for a fix for this)

See example in comment below.  If we've made the new HistoryDetails response into a perfect superset of the current json response, then we've succeeded.

### Testing note

A valid localhost history details api GET has this form.  It requires the authorization header, but the value can be bogus.  It takes the actionId as an argument, so you may need to get that using a database query.  The python prettyprints the json:

 curl -H "client:ignore"  -H "authorization:bearer 123" -H "content-type:text/csv" "http://localhost:7071/api/history/simple_report/submissions/1557" | python -mjson.tool

**Comment by jimduff-usds** [comment]
Here's an example of what the history details returns right now:

```
{
    "submissionId": 1556,
    "submittedAt": "2022-02-08T12:47:50.945531Z",
    "submitter": "simple_report",
    "httpStatus": 201,
    "id": "abf8338c-8c00-435e-88da-982712a02b93",
    "destinations": [
        {
            "organization_id": "de-dph",
            "service": "elr",
            "filteredReportRows": [
                "For de-dph.elr, filter isValidCLIA[testing_lab_clia] filtered out item 850928 at index 0"
            ],
            "sending_at": "",
            "itemCount": 0,
            "sentReports": [],
            "organization": "Delaware Division of Public Health"
        }
    ],
    "errors": [],
    "warnings": [
        {
            "scope": "report",
            "index": null,
            "trackingId": null,
            "type": "warning",
            "message": "Missing 'Corrected_result_ID' ('previous_message_id') header"
        }
    ],
    "topic": "covid-19",
    "warningCount": 1,
    "errorCount": 0
}
```

And here's what it will look like when you are done (ignoring the order of the fields):

```
{
    "submissionId": 1556,
    "timestamp": "2022-02-08T12:47:50.945531Z",
    "sender": "simple_report",
    "httpStatus": 201,
    "id": "abf8338c-8c00-435e-88da-982712a02b93",
    "destinationCount": 0,
    "reportItemCount": 1,
    "destinations": [
        {
            "organization_id": "de-dph",
            "service": "elr",
            "filteredReportRows": [
                "For de-dph.elr, filter isValidCLIA[testing_lab_clia] filtered out item 850928 at index 0"
            ],
            "sending_at": "",
            "itemCount": 0,
            "sentReports": [],
            "organization": "Delaware Division of Public Health"
        }
    ],
    "errors": [],
    "warnings": [
        {
            "scope": "report",
            "index": null,
            "trackingId": null,
            "type": "warning",
            "message": "Missing 'Corrected_result_ID' ('previous_message_id') header"
        }
    ],
    "topic": "covid-19",
    "warningCount": 1,
    "errorCount": 0
}
```

**Comment by kevinhaube** [comment]
This will make some breaking changes to the `/submissions` and `/submissions/:taskId` pages on the front-end. Please reach out/pair with the Experience team to ensure nothing is left broken! 
>Note: Front-end unit tests use a mocked form of this response that isn't retrieved from the API currently, so changes won't immediately break any component unit tests. Network unit tests are limited by our current networking library and are an active area of work for us.
