### ISSUE TITLE
API - Return Filter Type and Row(s) Affected with Filter Messages Returned upon CSV File Validation

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4244]
## Problem Statement
As the Experience Team, we need to be able to fail a file and display messages when we detect the presence of quality filter messages in the json that is returned by the API when we validate a file.

## Assumptions
We assume that there is currently a way to validate a file against quality filters.

## Acceptance Criteria
- When
    - A CSV file is validated/submitted using the API
- Then
    - The API returns the following information for Filter messages 
       - Message
            - The message string (i.e. what it is currently returning) with the field(s) affected      
        - Row(s) affected
            - The row(s) that has the message (if applicable)
       - Type of filter message; one of these values
           - Jurisdictional
           - Routing
           - Processing 
           - Quality

## To Do
-

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/4244?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @oslynn @smythe5 @whytheplatypus
