### ISSUE TITLE
Add function app for infrastructure checking

### ISSUE THREAD

**Issue by cwinters-usds** [CDCgov/prime-reportstream#4245]
This should be a separate application not tied to the server. Some basic functionality:

* Validate our outbound IP address
* Validate we can reach a third party on the internet
* Validate we can read from/write to storage accounts
* Validate we can read from key vault

We may want to run this on a recurring basis and log results to the log analytics workspace so we can alert on errors. Make that logging configurable as we may want to run this if the LAW or other underlying infrastructure is down.

Also:

* Create an HTTP endpoint to respond in a configurable amount of time (e.g., `/api/infra/ping?respond_time=62`) to see if 504s are triggered
    * This will also require a separate invocation script which should sit alongside the function app code
    * We should also make this callable via the `prime` CLI tool
    * The endpoint must only be callable with a shared key (function API key, whatever)

A template for some of this is in the [PHDI repo](https://github.com/CDCgov/prime-public-health-data-infrastructure/tree/main/operations/app/sample)

**Comment by JosiahSiegel** [comment]
In my attempt to standardize the admin/DevOps function app requested [here](https://github.com/cdcgov/prime-reportstream/issues/4245), I created a function app Terraform file that I can share across projects and just primarily change the path to the admin python functions:
PRs:
 * [PHDI](https://github.com/CDCgov/prime-public-health-data-infrastructure/pull/119)
 * [reportstream](https://github.com/CDCgov/prime-reportstream/pull/5536)
