### ISSUE TITLE
HHSProtect - Settings Changes needed for adding new Senders

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#4255]
Currently, every new Sender added to ReportStream must send its production data to the "hhsprotect" sender.  A bit more explanation:
1. ReportStream is to send all production data to HHS protect EXCEPT for those senders that reject this.
2. Simple Report is one of the senders that CANNOT send its data to HHS protect.
3. We will handle any rejections by adding the specific sender to the jurisdiction filter for filtering.
4. Currently, the setup was to add each sender to the jurisdiction filter, which will result in a big long list and extra effort as we onboard more senders.  THe need here is to simplify this setup, so we do not have to update this filter over and over.
5. IMPORTANT: We must exclude any senders not currently sending data to HHS protect, so it cannot be a blanket everyone sends their data there.

## Things know
Example from hhsprotect settings:
    jurisdictionalFilter:
    **- "matches(sender_id, SafeHealth,ImageMover,Cue,InBios,Strac,.*CueHlth.*,reddyfmc,primary,cuc-al,guc-la,abbott,lifepoint,hca,pmg,ihealthlabs,mns)"**
    qualityFilter:
    - "allowAll()"
    - "doesNotMatch(processing_mode_code,T,D)"
    routingFilter: []
    processingModeFilter: []

## Acceptance criteria
1. All results with processing_mode_code P (production) are sent to HHS protect.
2. Results from senders CURRENTLY not sending data to HHS protect are NOT sent to HHS protect.  This means we must reverse the current list of senders from a match to does not match.

**Comment by rhood23699** [comment]
sender_id: "all-in-one-health-ca" - They are in production and should be included.  I'll do that today.

Below are Senders that I'm working on that will soon need to be included.  Note, some of the Senders in your list are not mine, so I can't really answer for them.
"hollywoodsmiles-ca"
"kern-county-phsd-ca"
"cdphe-csvuploader"
"cadph-csvuploadertest"
"sourcebioscience_ca"
"warrior-dx-co"
"covidclinic-org"
"naval-health-clinic-lemoore"
"vivature-tx"
"sdilabs-ca"
"ocrapidtest-ca"
"stemexpress-ca"
"corebiolabs-oh"

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/4255?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @oslynn @smythe5 @whytheplatypus

**Comment by JGreenFearless** [comment]
@rhood23699 Is this something that still needs to be addressed?
