### ISSUE TITLE
Sender production status: visual indicator and copy to help user identify status

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4265]
### Background

Senders would like to know whether they are in production and sending data to their PHD. We need a status indicator 

### Acceptance Criteria
- [x] What does it look like?
- [x] Indicator/alert for "Test" status for CSV/API sender (ex: you have not yet been approved by your PHD)
- [x] Indicator/alert for "Error" status for CSV/API sender (ex: your account has been disabled in some way)
- [x] If a user is in production, the nav displays without the alert/indicator.
- [x] Write status content to link to in documentation. Help a user understand -- what is this status? What does it mean? What step in the process am I? Who should I contact if I have a question/problem?

**Comment by drew-usds** [comment]
A couple examples to try out, saw these while clicking around this week:

 **In between gov banner and nav**

<img src="https://images.zenhubusercontent.com/5ff50e49f74e134e95117280/50436e6a-467e-4c29-b5bb-712508cb0a50" width="800px" />

**Under nav**

<img src="https://images.zenhubusercontent.com/5ff50e49f74e134e95117280/df7a6cf8-32bb-4046-b878-d0f4821ba535" width="600px" />
