### ISSUE TITLE
GU - Failures due to incorrect observation status

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#4266]
**Describe the bug**
GU DOH received 17 files yesterday that failed due to an observation status being “X” in OBR-25 and OBX-11.
 
The NBS only accepts the observation status codes of “F” for final, “P” for preliminary,” or “C” for corrected.
 
Need to fix and resubmit. 
 
Message ID                                                                  Reporting Facility
'''b96900e5-1d13-4302-84df-581deb04a158'''          Guam Radiology Consultants
'''20ce6311-c739-4b2b-816a-2c332a7db33f'''            Guam Radiology Consultants
'''4ef5c33f-e6ef-4a82-a824-2040be8ab330'''             Guam Radiology Consultants
'''cede4400-eb7a-4d17-99c6-895cb1340107'''          Southern Regional Community Health Center
'''d615f82e-5780-4e67-b693-b62627502ab7'''          Saint Anthony Catholic School
'''ecab4ced-51e8-4915-835f-cb6f13b343c5'''             Outreach Testing Facility
'''328579b6-0791-4ec3-a7da-1090eeb419f4'''           Southern Regional Community Health Center
'''ff33a8d8-b576-403b-9920-dafb0ffbe33e'''             Guam Radiology Consultants
'''a56ad2ed-097f-4dac-8caf-28d702532598'''            Guam Radiology Consultants
'''efd2a6a7-066e-4f63-96aa-2ec82de92db2'''            Guam Radiology Consultants
'''f4bff738-41e8-4b31-a0bf-e4f11eeb9e3e'''              Guam Radiology Consultants
'''288df73f-e10e-46bc-ae1c-5f70d8a132d7'''             Outreach Testing Facility
'''61e588f9-42b7-47d9-9409-159c26f27a10'''            Outreach Testing Facility
'''8557abdb-c51f-4964-a9d0-4bf27fe1e7d9'''            Outreach Testing Facility
'''e104082b-6c67-4584-9fbd-1dbd85c6b8f5'''           Outreach Testing Facility
'''8a97859e-732a-436b-b3eb-c77997a4dc35'''       Outreach Testing Facility
'''d35ba41d-9e9c-4aa1-8cf1-8c176755fb2e '''           Guam Radiology Consultants

**Comment by anshulkumar-usds** [comment]
2/11: Inductive reported that the following two facilities also came up with the same error:
Father Duenas Memorial School 
messageID: ```96eddc2c-58c0-4e15-bccf-2e92ec58e9fa```
OKKODO HIGH SCHOOL
messageID: ```22237388-cfbe-4c99-8a53-fd53192fc1a7```

**Comment by brick-green-agile6** [comment]
SimpleReport transmitted the results with "X" in the test_result_status field. These all seem to be corrections to previous results. @zdeveloper Can you check these results and let us know why "X" was used rather than "C" in test_result_status?

**Comment by anshulkumar-usds** [comment]
@zdeveloper VT reported the same issue today: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4381

**Comment by brick-green-agile6** [comment]
Just talked to Zedd. These results do not need to be resent. On 2/7 SR implemented a change with this work flow:

1. First message is sent as final
2. User recognizes that a data entry problem occurred then marks the result as an error and enters a reason for the error
     - examples of possible errors include: incorrect DOB, duplicate result, incorrect patient last name
3. A second message is sent with the reason for the error and "X" as the result status but nothing in the message is chagned
4. The user enters a new test event with the corrections

So in this workflow, the jurisdiction is receiving 3 distinct messages. The first is an error. The second is a notification of the error. Then third contains the correct information. The second message is the only one producing an error and the correct information was transmitted to the jurisdiction. So I don't think anything needs to be resubmitted.

In my conversation with Zedd, we found a use case for sending results with statuses other than F, C, or P. When a duplicate message or a test message is entered sending a correction isn't really correct. The correct option is actually "W" which means "Post original as wrong".

In the short term, I think those messages should be filtered from going out to receivers. I don't think any of the surveillance systems have the ability to delete results based on a second message. In the long term, Zedd is going to approach the SR team and adding a workflow for true corrected results. Then also, could we approach the NBS team about adding functionality for additional results statuses?

cc @MauriceReeves-usds

**Comment by zdeveloper** [comment]
@brick-green-agile6  +1

**Comment by MauriceReeves-usds** [comment]
@brick-green-agile6 @zdeveloper @anshulkumar-usds while it appears the ideal case is that downstream systems would recognize and update their systems for an `X` status, that doesn't seem to be how they work. given the number of errors we receive, I think it's good for us to just filter these out for now for all jurisdictions. We can offer to send them if there is a state/system that is able to handle them, so I want to keep receiving them, but we don't need to pass them along.

**Comment by anshulkumar-usds** [comment]
2/16: Checking with GU/Inductive if they wish to receive a "W" status

**Comment by anshulkumar-usds** [comment]
2/16: GU also confirmed they do NOT want "W" or "X"

**Comment by brick-green-agile6** [comment]
GU sent some new examples
```
52703f7c-800a-4fcb-86d6-f0735dac0135

12524e75-c92c-4e72-8400-f5151f9fa180

dcfe0aae-001c-4209-aa42-fdffa0f5c695

73e1421e-aaab-4aa4-85d4-27b5fcfd580e

05a3d4a7-3502-457e-990c-3c520ed41145
```

**Comment by Adrian-Brewster** [comment]
Of course. Thanks @brick-green-agile6
