### ISSUE TITLE
Add the filter type (eg 'qualityFilter') to the  ReportStreamFilterResult

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#4283]
When this ticket is done, a new field filterType should be added to ReportStreamFilterResult, and should appear in serialized versions of that object in the `action_log` table.

The possible values are as found in ReportStreamFilter.kt, that is:

```
enum class ReportStreamFilterType(val field: String) {
    JURISDICTIONAL_FILTER("jurisdictionalFilter"),
    QUALITY_FILTER("qualityFilter"),
    ROUTING_FILTER("routingFilter"),
    PROCESSING_MODE_FILTER("processingModeFilter");
```
(in practice jurisdictionalFilter will never appear, because we are not logging those right now)

So here's what the new serialized version of ReportStreamFilterResult might look like, as found in the action_log table, with the new `filterType`:

```
{
  "type": "TRANSLATION",
  "class": "gov.cdc.prime.router.ReportStreamFilterResult",
  "filterType": "qualityFilter"
  "filterArgs": [
    "testing_lab_clia",
    "reporting_facility_clia"
  ],
  "filterName": "isValidCLIA",
  "receiverName": "co-phd.elr-test",
  "filteredIndex": 0,
  "originalCount": 1,
  "filteredTrackingElement": "01F84F64-8BF8-49AB-B58E-579C90F644EA"
}
```

###  Implementation Notes

- It might require a bit of thought to figure out how best to "pass down" the filterType value to the place where those ReportStreamFilterResult objects are getting instantiated.
- I suppose you could call the field reportStreamFilterType if you prefer a more accurate but verbose name.
- test that we do not have backward compatibility issues if we deserialize old action_log data (sans filterType) into the newer obj.  Might need to make the field nullable, as I don't think there's a reasonable default to apply

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/4283?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @oslynn @smythe5 @whytheplatypus
