### ISSUE TITLE
SPIKE -- Can we use SendGrid to Trigger emails for OKTA Users

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4286]
## Questions to answer:
- Can we use SendGrid to trigger activation emails for OKTA users

## Acceptance Criteria
- Create solution proposal and place it [here](https://github.com/CDCgov/prime-reportstream/tree/35de1f5379a453d582cb8b96de8cca09b1c77a27/prime-router/docs/proposals)

**Comment by rachelhanster** [comment]
@bgantick Can this be closed? Under option 3, open question 3 is captured **[here](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3945).** Feel free to start new tickets for open questions 1 and 2 as needed.
cc @BerniXiongA6
