### ISSUE TITLE
Add tests of the AS2 transport to existing Smoke tests

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#4298]
The smoke tests are designed to send to multiple transports.

We do not currently test the AS2 transport.  (Nor the SOAP transport, but I'm ticketing that separately)
(We were testing the Redox transport, but that just got removed.)

### Acceptance Criteria

-- The 'end2end' and 'merge' tests send data to AS2 transport.   Add others as you see fit.
- Needs to at least work locally
- Better if it also works in staging.

### How to do this

- Check with @RickHawesUSDS how to do a reasonably rigorous test of the AS2 transport in Staging.   This may involve a significant amount of work to stand up a fake AS2 receiver in our environment (?).  If that's horrible, then at least get a localhost AS2 test working.
- That's the hard part.
- The rest is:  Add receiver setting for an AS2 transport to the 'ignore' organization, list them in TestReportStream.kt, and add them to, say, the 'end2end' and 'merge' tests, and get them working.
- If it only works locally, make sure you TURN OFF that portion of the test when it runs in the Staging environment.

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/4298?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @oslynn @smythe5 @whytheplatypus
