### ISSUE TITLE
Add SOAP transport to Smoke Tests

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#4299]
The smoke tests are designed to send to multiple transports.

We do not currently test the SOAP transport.  (Nor the AS2 transport, but that's ticket #4298)
(We were testing the Redox transport, but that just got removed.)

### Acceptance Criteria

-- The 'end2end' and 'merge' tests send data to SOAP transport.   Add others as you see fit.
- Needs to at least work locally
- Better if it also works in staging.
- If it only works locally, make sure you TURN OFF that portion of the test when it runs in the Staging environment.

### How to do this

- Check with @MauriceReeves-usds  how to do a reasonably rigorous test of the SOAP transport in Staging.   This may involve a significant amount of work to stand up a fake SOAP receiver in our environment (?).  If that's horrible, then at least get a localhost SOAP test working.
- That's the hard part.
- The rest is:  Add receiver setting for a SOAP transport to the 'ignore' organization, list them in TestReportStream.kt, and add them to, say, the 'end2end' and 'merge' tests, and get them working.

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/4299?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @oslynn @smythe5 @whytheplatypus

**Comment by MauriceReeves-usds** [comment]
Setting up a SOAP receiver isn't too bad. CastleMock makes it fairly simple to add an endpoint you can submit to, and give a response, so for simple cases we're probably fine. If you want to do something more advanced, you need to use XSL to parse and process the message. @clediggins-usds when you're ready to work on this, let me know and we'll set aside some time to chat about it.
