### ISSUE TITLE
Publish Emergency Phone Number and Email for STLTs and Senders

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4303]
Pursuant to the incident from 1/30, we need to create a share a phone number and email address that can be used by our STLT and Sender partners in case of urgent support from the ReportStream team.

https://cdc.sharepoint.com/:w:/t/USDSatCDC/EeFS0Pw7PiRCvYUncjLAL7oB7CnPlJjGdouk_0uDRB7nQw?e=t08mkb&CID=B2403B80-0A1A-482E-B945-A2223BCD075B&wdLOR=cFB8C96FD-0258-479D-B78C-F60EC92893E6

Todo:
1. Work with dev-ops to create phone and email associated with PagerDuty
2. Share this contact information with STLT and Sender partners

fyi @MauriceReeves-usds @cwinters-usds @RickHawesUSDS

**Comment by cwinters-usds** [comment]
Hey @anshulkumar-usds -- AFAICT PagerDuty doesn't support exposing phone numbers to trigger alerts. It should be possible to wire up an integration with something like Twilio to do this, but it would be some work.

However we can setup email addresses directly in PagerDuty -- if a user emails the address it can trigger an alert to a specified group, and we can set separate emails up for senders and receivers.

**Comment by anshulkumar-usds** [comment]
@cwinters-usds email should be sufficient for now. As long as the STLTs have a way to trigger an urgent alert.
cc @mauricereeves

**Comment by cwinters-usds** [comment]
Super, will get these setup ASAP. Initially they'll just go to the existing ReportStream oncall team but we can redirect to different teams later.

**Comment by anshulkumar-usds** [comment]
The following emails have been setup for Receivers and Senders:
emergency-reportstream-receiver@prime-cdc.pagerduty.com
emergency-reportstream-sender@prime-cdc.pagerduty.com

**Comment by anshulkumar-usds** [comment]
3/21: Sent remainder notifications to AK, AL, AZ, CA, CO, DE, FL, GU, IA, ID, LA, MD, MN, MS, MT, ND, NH, NJ, NM, OR, PA, TN, TX, WA, WY

Following states are in development, and need to be notified post onboarding: IN, NY, NV
