### ISSUE TITLE
CA - Truncate OBX-23.1 and ORC-21.1 to 50 chars

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4307]
CA has requested we truncate OBX-23.1 and ORC-21.1 to 50 chars.

**Comment by anshulkumar-usds** [comment]
3/1: Checking with CA and moving to External Review.

**Comment by oslynn** [comment]
Need to update the staging settings.

**Comment by jorg3lopez** [comment]
@anshulkumar-usds You can close if you want. I don't we have sent the failed messages yet; at least I'm not aware of. I will back track from Feb 11th until March 3rd, and gather the messages that failed during that time.
