### ISSUE TITLE
Force externalName to always appear in the submissions function summary/list response

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#4309]
### AC

Return"externalName" in the submissions summary/list response even when its null.

###Notes

Right now the code is set to not include this value when its empty.

The fix is on Submission.kt line 210.

### Example from when its filled in:

This call

curl -H "client:ignore"  -H "authorization:bearer 123" -H "content-type:text/csv" "http://localhost:7071/api/history/ignore/submissions" | python -mjson.tool

Returns this response, that includes the externalName:
```
     {
        "taskId": 1671,
        "createdAt": "2022-02-11T15:20:22.70434Z",
        "sendingOrg": "ignore",
        "httpStatus": 201,
        "externalName": "hl7null Smoke Test",
        "id": "75856884-6fce-463d-8a9d-b8a7a887a74b",
        "topic": "covid-19",
        "reportItemCount": 100,
        "warningCount": 0,
        "errorCount": 0
    }

```

This ticket is to always include, even when its null, eg
"externalName": null,

**Comment by jimduff-usds** [comment]
### AC

Return"externalName" in the submissions summary/list response even when its null.

###Notes

Right now the code is set to not include this value when its empty.

The fix is on Submission.kt line 210.

### Example from when its filled in:

This call

curl -H "client:ignore"  -H "authorization:bearer 123" -H "content-type:text/csv" "http://localhost:7071/api/history/ignore/submissions" | python -mjson.tool

Returns this response, that includes the externalName:
```
     {
        "taskId": 1671,
        "createdAt": "2022-02-11T15:20:22.70434Z",
        "sendingOrg": "ignore",
        "httpStatus": 201,
        "externalName": "hl7null Smoke Test",
        "id": "75856884-6fce-463d-8a9d-b8a7a887a74b",
        "topic": "covid-19",
        "reportItemCount": 100,
        "warningCount": 0,
        "errorCount": 0
    }

```

This ticket is to always include, even when its null, eg
"externalName": null,

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/4309?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @oslynn @smythe5 @whytheplatypus
