### ISSUE TITLE
Add a few summary fields to the History Details

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#4310]
### AC

Add the following fields to the submission History Details Response:  `overallStatus`, `plannedCompletionAt`, `actualCompletionAt`.

#### overallStatus

`overallStatus `is meant to be a simple status value that tells a user if all the data in that submission has made its way to all the intended recipients.    Values are

- `error `- error on initial submission
- `received `- has passed the receive step in the pipeline, and is waiting to be processed/routed.   This state should be extremely brief, except when the system is backed up.

Then once something has been processed/routed it can enter one of these states:

- `notDelivering `-- has been processed, but has zero intended receivers, or has receivers but was submitted with 'SkipSend' or similar flag, so its done.  Sadly, nobody wants this data.
- `waitingToDeliver `- has been processed, has real intended receivers, but has not gone to any of them.
- `partiallyDelivered `-- has been processed, has real intended receivers, and has been successfully sent to at least one of them.
- `delivered `-- has been processed, has intended receivers, and has been successfully sent to all of them.

This is simple for the customer, not so simple for us to figure out.

For now, no "send error" type of state.  If a send error occurs for example, it'll just sit in the waitingToDeliver or partiallyDelivered state until someone fixes it.  (Doing a sendError state is quite tricky - we probably don't have the right data in the right place database to do it easily.  We could do this as a follow-on ticket)

####  plannedCompletionAt

Example 

"plannedCompletionAt":  "2021-10-22T10:00-04:00".  

This is max of all the planned sending_at values for all destinations.  If the current overallStatus is `error`, `received` or `notDelivering`, then this is null

 #### actualCompletionAt

This is null unless the overallStatus is `delivered`.   If the data has been delivered to all receviers, then this is the timestamp of the last actual delivery time.   That is, all receivers have at least one sentReports, this is the max(createdAt) timestamp for all of them.  See #4623 for examples.

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/4310?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @oslynn @smythe5 @whytheplatypus

**Comment by JGreenFearless** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/4310?planning-poker) with ZenHub @TurkeyFried
