### ISSUE TITLE
Abbott Onboarding - Direct to ReportStream for STLT Reporting

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4311]
Abbott wishes to start a pilot with ReportStream to begin reporting data to states. This is a placeholder to document the work and next steps for onboarding operations.

**Comment by anshulkumar-usds** [comment]
2/11: Staging key and updated instructions shared with user navicanonprod in keybase

Next steps are to review Abbott's current data schema, and update or create a new child schema from Direct.schema. Abbott still needs to confirm if they're sending CSV or HL7 files

**Comment by anshulkumar-usds** [comment]
3/28: Moving to product backlog. Meeting scheduled with Abbott this week.

**Comment by anshulkumar-usds** [comment]
3/31: Met with Abbott team on 3/30 to discuss next steps with onboarding. Awaiting sender's confirmation on outstanding questions and next steps.

**Comment by anshulkumar-usds** [comment]
Meeting scheduled with Abbott on 4/12 to provide demo of submission history API. Jim and Carlos from Pipeline also invited to provide the demo.

**Comment by anshulkumar-usds** [comment]
@jbiskie Do you recall any takeaways from the last meeting with Abbott on state reporting? I believe the last meeting Pipeline was going to demo the submission history API.

**Comment by anshulkumar-usds** [comment]
5/19: Higher level discussion between CDC and Abbott are pending. Iceboxing until we have more clarity on a roadmap.

**Comment by LaFreda1** [comment]
Closing due to time line
