### ISSUE TITLE
Pagination behavior not accounting for failed Submissions being filtered out

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#4315]
**Describe the bug**
It looks like we receive the full API response, including failed submissions (id: null), and when filtering out, are not displaying the first 10 successful items on page 1, but rather the successful items from that original network call; in this case, only 2 items were successful. **This is likely due to the API only returning 10 items from the cursor and using an array filter to remove invalid submissions.**

**Impact**
Minimally frustrating; could confuse a Sender when looking for Submissions

**To Reproduce**
1. Go to staging and log in
2. Switch to `all-in-one-health-ca`
3. Navigate to `/submissions`
4. Observe displayed list
5. Click next, observe another displayed list of under 10 items
Bonus: F12 to open dev tools and navigate to Network to view the response from the call with 10 items.

**Expected behavior**
The list should display 10 successful submissions per page

**Screenshots**
![Screen Shot 2022-02-11 at 2.02.25 PM.png](https://images.zenhubusercontent.com/611a907ec3e013d0e33e58a7/f502c90e-5999-4b0c-8863-51329fb29cf6)
![Screen Shot 2022-02-11 at 2.02.43 PM.png](https://images.zenhubusercontent.com/611a907ec3e013d0e33e58a7/353fcb22-a85b-4c5b-8477-79af356a9d40)

**Comment by loripusey** [comment]
@kevinhaube Can you point this bug? I'd like to get this into the next sprint
cc: @rachelhanster

**Comment by kevinhaube** [comment]
@loripusey Will do! This also looks like something we can tackle alongside the API work that goes with #4270

**Comment by kevinhaube** [comment]
Keeping the API sorting and filtering tickets independent of this, so that if any rollback is needed, those features won't be caught in the cross-fire.

**Comment by TomNUSDS** [comment]
Bonus points: have just the CONTENTS of the table flash as it reloads the next/prev page instead of the whole table.

**Comment by kevinhaube** [comment]
@TomNUSDS Challenge accepted 😈

**Comment by TomNUSDS** [comment]
@kevinhaube wait... it's closed... did you fix it?
