### ISSUE TITLE
[Bug]: Site Wide: Navigating through the application buttons does not scroll you to the top of destination page

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#4327]
## Describe the bug
Generally within the app if you navigate to any other page it will try to keep you at whatever vertical position you had scrolled to before clicking the button- often forcing the user to constantly keep scrolling up as they use the application.

## Need to Know
This may be "us" using the React Router incorrectly.
React Router version is now v6.

## Acceptance Criteria
- [ ] When clicking one of the page interaction buttons (eg, Edit, Clone, Cancel, etc) you are navigated to the top of the subsequent page
- [ ] Verify problem is solved site-wide

## Impact
Harmless but very annoying. Could eventually lead to carpal tunnel syndrome.

## To Reproduce
Login as admin, go to Admin->Organization Settings
Choose the "waters" org from the list
Scroll down to a Receiver setting and click Edit or Clone
Observe that you are halfway down the page

## Screenshots
1. scrolled down to giang2-clone receiver setting
![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/865a5641-10d2-445e-aca8-7bdbbeaa3065)

2. Navigated to edit page after clicking Edit on giang2-clone
![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/90271e17-50bb-40bf-8dc4-07a9257110fe)

**Comment by kevinhaube** [comment]
Stale description, should be verified, but likely a good bug ticket to work on!

**Comment by HeatherRienks** [comment]
@brandonnava & @brick-green - are you aware if there is still a need for this ticket?

cc: @BerniXiongA6

**Comment by brick-green** [comment]
Just tested and it appears this is still an issue. I agree with the Impact section - it's harmless but annoying

**Comment by HeatherRienks** [comment]
FYI- @chris-kuryak

**Comment by chris-kuryak** [comment]
Got it.
Adding to product backlog. Removing the time estimate since it was estimated by someone no longer on the team. Adding low-priority and needs-refinement so it gets brought up in the refinement meeting.

**Comment by chris-kuryak** [comment]
@brick-green Thanks for the clarification!

**Comment by stephenkao** [comment]
Just for context on the implementation side of things, this should be a really simple change since the website is an SPA/we're using react-router.  [Here](https://stackoverflow.com/a/54343182)'s an example of how it can be done, and I've personally implemented something similar in the past with little issue so that could be a good starting point!

**Comment by kevinhaube** [comment]
@stephenkao Nice! I was just about to ask if Router had some kinda built in scroll fix but I guess not. Pretty useful custom effect hook if you ask me! Maybe a useScrollPosition so we could use it as a general UX tool
