### ISSUE TITLE
Convert senders to prefer datetime offset or UTC

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4333]
Several states has expressed concerns about default assumptions ReportStream makes for time-zones and date-time offsets that are communicated with our test results.

Upstream: We need to work with all our senders to have them send a date-time offset or default to UTC for all messages communicated to ReportStream. 

Downstream: ReportStream needs to communicate with each STLT on how the time-zones and date-time formats are communicated to STLTs. Customizations requested per STLT need to be addressed on a case-by-case basis.

The following senders are currently connected to ReportStream. We need to work with each one get the these updates working:
1. SimpleReport
2. CUE
3. ImageMover
4. Abbott
5. Ellume (via Lifepoint)
6. iHealth (via Lifepoint)
7. Primary Health
8. PMG
9. CSV Senders

Next steps (as of 2/14)
1. @jbiskie is working to update the API Programmer's Guide to update our spec from yyyyMMdd to yyyyMMddhhmmsszz (https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3627)
2. Start with ImageMover as the first sender to update these requirements, their schema, and test submissions to ensure updates are per RS requirements. 
3. Ticket per sender will be added to this Epic.

fysa @RickHawesUSDS @jimduff-usds @MauriceReeves-usds @jbiskie @brick-green-agile6 @rhood23699

**Comment by brandonnava** [comment]
@MauriceReeves-usds @GilmoreA6 Still an issue? Close?

**Comment by MauriceReeves-usds** [comment]
@brandonnava still an issue. We need to communicate this to senders.

**Comment by brandonnava** [comment]
@brandonnava To bring up at next sprint planning. Will pick highest priority sender to start getting the ball rolling

**Comment by LaFreda1** [comment]
@sliu1000 Let's set some time to discuss this

**Comment by LaFreda1** [comment]
zz format: 

This format is defined by the sensible practical standard, ISO 8601. The T separates the date portion from the time-of-day portion. The Z on the end means UTC (that is, an offset-from-UTC of zero hours-minutes-seconds).

**Comment by sliu1000** [comment]
I think the last time we talked about this we decided to put this on hold due to us needing to test this prior to putting into production. @LaFreda1

**Comment by LaFreda1** [comment]
That's right. @sliu1000 Moving to O&O backlog

**Comment by chris-kuryak** [comment]
Purpose: We don't want to send incorrect time/date data to receivers.

Need to determine:
1. Is timezone required on test results to be sent to receivers?
2. Is timezone required for a message to move through the UP?

If the answer to either of those questions is yes, then we need to add timezone as a required field during validation.

**Comment by MikaelahD13** [comment]
Closing, work completed.
