### ISSUE TITLE
ImageMover - Convert sender to prefer datetime offset or UTC

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4334]
Per details contained in this epic: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4333

we need to work with ImageMover, update their schema, and default to a timezone to ensure we are capturing any datetime uniqueness and offsets the senders wishes to supply.

Per Jim, one way to do this would be to setup a "defaultTimeZone" field in the sender settings.

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/4334?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS
