### ISSUE TITLE
Endpoint for HL7 -> FHIR translation

### ISSUE THREAD

**Issue by whytheplatypus** [CDCgov/prime-reportstream#4339]

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/4339?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @oslynn @smythe5 @whytheplatypus
