### ISSUE TITLE
OO/Change Std CSV Schema to use the sender_valuesets DB table

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#4346]
## Problem statement
Before I can move the Std CSV schema to the sender_valuesets lookup table, it needs to be sync'd with the existing sender-automation.valuesets file.

## Acceptance criteria
- [ ] Each field listed below translates from the csv data received to the appropriate RS value.
         Fields are: race, ethnicity, test performed code, test result, specimen type, specimen source site, etc.

## To do
- [ ] In the Std CSV Schema, change all the existing fields that currently use the sender-automation.valuesets to use the use the sender_valuesets table.

**Comment by brandonnava** [comment]
CSV moved to SimpleReport
