### ISSUE TITLE
Admin Settings: On landing page, sort organization list alphabetically

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#4349]
## Problem statement

When at the landing page of Organization Settings, the list of organizations are not in any particular order. 

![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/a5ff4e79-b5dc-40df-a0cc-dd60d1c49362)

Although there is a mechanism to search for the org that you want, it would provide a smoother experience if the organizations were already sorted alphabetically by default.

## Acceptance criteria

- [ ] Organizations sorted alphabetically by default

**Comment by TomNUSDS** [comment]
@meckila @sethdarragile6 is reworking this page as part of https://github.com/CDCgov/prime-reportstream/issues/4352
So it probably makes sense for him to fix this bug OR for you to wait when other changes are done (to avoid merge conflicts).

**Comment by sethdarragile6** [comment]
@TomNUSDS I'm not actively working on #4352 yet, it wasn't pulled into the sprint. Regardless of whatever we do in Admin Settings we'll have to keep in close communication to avoid conflicts. Long story short- I'm giving back to @meckila , I don't want it! 😂
