### ISSUE TITLE
[Bug] Admin Settings: Padding issue on Edit Sender

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#4350]
**Describe the bug**

![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/4ff76a26-9c6a-4f7c-a51a-18383ba036bc)

**Impact**
Ugly display, but functional

**To Reproduce**
1. Login as admin, go to Admin->Organization Settings
2. Choose an organization from the list
3. Click on Edit for a Sender setting
4. If on a large display, resize window until screen matches above screenshot

**Expected behavior**
Padding should be relative even throughout.

**Comment by mreifman** [comment]
@sethdarragile6, is the issue that "Customer Status" wraps, causing there to be extra vertical space between the text inputs? What is the desired behavior?

**Comment by bgantick** [comment]
@mreifman Space should be equal between inputs and there should be space between the inputs and the buttons.

**Comment by mreifman** [comment]
For the spacing between inputs, I think the right way to fix this is to adjust to a vertical layout on narrow screens, where the each label sits above its associated input. With the labels we have now, the longest one (Customer Status) breaks to two lines when the screen is 545px wide. 

We discussed another narrow screen issue in backlog grooming and I think decided to punt for now given the fact that we don't really have mobile users. Should this fall into the same bucket?

**Comment by mreifman** [comment]
This issue also happens on the Edit Receiver page, where the longest label breaks at around 828px wide. The change to the vertical spacing is less obvious there since it doesn't cause a problem with the taller textareas.

**Comment by bgantick** [comment]
@mreifman Adding margin to the buttons is probably sufficient for now. I think admin settings will need a design pass as a whole at some point, but there are other priorities at the moment and this is only internal for now cc @drew-usds
