### ISSUE TITLE
Remove Ron Heft specific branch code in GHA

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#4357]
The following GHA yaml files have stuff explicitly looking for Ron's work. These should be removed and either updated to use new branches or removed entirely.

* workflow "release.yml"
* actions "deploy-backend, deploy-frontend,vpn-azure"

**Comment by cwinters-usds** [comment]
@jeremy-page I think you did this in the updated terraform branch, correct?
