### ISSUE TITLE
Globally Update Sender Schemas to make Specimen Collection Date to have a Cardinality of One

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4359]
We recently made it a requirement for ImageMover to send specimen collection date by changing this sender's schema cardinailty. https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4206

We need to make this a global change for all of our senders in production, and those in queue for onboarding. Please make the necessary changes to cardinality for the Direct schema, or other parent schema for senders so that specimen collection date is a required field.

List of senders schemas to update:
* [x] ImageMover
* [x] CUE
* [ ] Abbott (direct-lite)
* [ ] Lifepoint (Ellume and iHealth) (HL7)
* [ ] Primary (HL7)
* [x] SafeHealth

cc @oslynn @jbiskie @rhood23699

**Comment by anshulkumar-usds** [comment]
Anshul will partner with all senders to let them know of upcoming changes. Follow up with individual tickets for each sender.

**Comment by anshulkumar-usds** [comment]
Anshul will turn this into an epic and create tickets for each sender.

**Comment by anshulkumar-usds** [comment]
3/7: ImageMover schema was updated on 3/10 to make specimen collection datetime a required field by updating the cardinality of the field:
https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4206
https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/schema_documentation/direct-imagemover-covid-19.md
![IM_SCD.PNG](https://images.zenhubusercontent.com/607d9d4a591b7cc0bb55c82e/3020a8bd-10bb-4b1f-8886-b04e3d44cce5)

**Comment by anshulkumar-usds** [comment]
3/7: Checking with remaining API senders

@rhood23699 Can you please advise if any CSV sender schemas need updating too?

**Comment by anshulkumar-usds** [comment]
Direct Schema: If specimen collection date is not present, the schema will look for test ordered date

**Comment by rhood23699** [comment]
The Std CSV Schema and All-In-One-Health schemas have the cardinality set to ONE.

iPatientCare and Experity do not.  I'll work these two, but note they are not a problem.  The VBScript checks for this before it hits the schema.
