### ISSUE TITLE
Global Truncation to 50 chars: OBX-23.1 and ORC-21.1

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4360]
Make a global change to ReportStream to truncate OBX-23.1 and ORC-21.1 to 50 chars.

State waiting for this change are noted below.

**Comment by Adrian-Brewster** [comment]
Addressed for IL already. Needs to be applied globally.

**Comment by oslynn** [comment]
Need to clarify with @anshulkumar-usds and @Adrian-Brewster above CA, IL, NJ ok to have OBX-23-1 and ORC-21-1 to truncated.

**Comment by oslynn** [comment]
NJ - Truncate Performing Org Name to 50 char for OBX-23-1 is done.  The AOE is taken care of by @jorg3lopez ticket 4197.

**Comment by Adrian-Brewster** [comment]
@oslynn  will upload to prod today.

**Comment by oslynn** [comment]
CA-DPH truncation of OBX-23-1 and ORC-21-1 is done.  Prod-settings.yml has them.

**Comment by oslynn** [comment]
THIS NEEDS TO BE CLOSED.
