### ISSUE TITLE
Global truncation to 30 chars: OBR-16.3 and ORC-12.3

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4361]
Some of this work is already done for the specific issue raised by NJ in 
https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3607

**Comment by anshulkumar-usds** [comment]
Communicate with all Receivers that this change is being applied

**Comment by oslynn** [comment]
Need to clarify with @anshulkumar-usds and @Adrian-Brewster above CA, IL, NJ ok to have OBX-23-1 and ORC-21-1 to truncated.

**Comment by Adrian-Brewster** [comment]
Will push to prod today.
