### ISSUE TITLE
Build API support for Filtering Submission History

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4362]
## Problem Statement
As a user, I need to be able to filter submission history by a "Date/Time" range. This is the first step in that process, allowing the front end to query the back end to return values from a date range.

## Acceptance Criteria
- Can filter the submissions by the Date/time submitted based on a date range (i.e. start date and end date)

## To Do
-

### Relevant backend files:
- Submission functions (where the endpoint lives): https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/azure/SubmissionFunction.kt
- API yaml: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/openapi.yml
### Relevant frontend files:
- Table (where we display returned submissions): https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/pages/submissions/SubmissionsTable.tsx
- Submissions resource (where we make queries with search params): https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/resources/SubmissionsResource.ts

## Related tickets/bugs:
Pagination bug: https://github.com/CDCgov/prime-reportstream/issues/4315
Design work: https://github.com/CDCgov/prime-reportstream/issues/4271
Frontend work: https://github.com/CDCgov/prime-reportstream/issues/1922
Sorting API work: https://github.com/CDCgov/prime-reportstream/issues/4270

**Comment by bgantick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/4362?planning-poker) with ZenHub @ahay-agile6 @kevinhaube @meckila @sethdarragile6 @TomNUSDS
