### ISSUE TITLE
Create Likelihood to Refer Follow up interview protocol

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#4366]
## Overview
We are doing these follow up interviews with those with high and low scores on the CX survey - promoters and detractors - those that are happy with the product and those that are not. There are two key reasons for doing this 
(1) Research - provide insights on what is working and what is not working to guide recommendations for changes and growth plan (as per OKR Q2). 
(2) Marketing - #1569 e.g. have quotes to share

## Participants

**Interview subject(s)**: [name/organization/etc]
**Contact info**: [ ... ]

## Background
These interviews are discrete/separate from the survey. Survey was anonymous and we aim to get the org name from the survey but honor the fact that survey responses were anonymous so in the interviews not say things like "in your survey you said X" if that makes sense. We choose them based on scores but need to be a bit agnostic in the interviews especially if the person doing interview did not respond to the survey or if we meet with multiple people from the org we do not want to "out" people for their responses. If they bring it up that is fine to roll with it.  

## To do
- [x] Finalize draft began in here: [Facilitation Guide for Follow up Calls to CX survey 2022](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B981f88a3-773b-45e4-aabe-4b9751a0a5ce%7D&action=edit&wdPreviousSession=e7e20b8c-5d5a-4c6d-8cfb-83f9373346a5)

**Comment by victorialb-usds** [comment]
Week of 5/3 VLB is finalizing this.

**Comment by BerniXiongA6** [comment]
Hey @RakshindaAslam @rachelhanster - I spoke with @victorialb-usds and while she's finalizing the questions for the facilitation guide, she said you can go ahead and add any questions under the title "Suggested Questions from Others" on the 3rd page. The link to the guide is in the AC above and also here: [Facilitation Guide for Follow up Calls to CX survey 2022](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B981f88a3-773b-45e4-aabe-4b9751a0a5ce%7D&action=edit&wdPreviousSession=e7e20b8c-5d5a-4c6d-8cfb-83f9373346a5)

**Comment by victorialb-usds** [comment]
@BerniXiongA6 ready for you. Noting this is just a template that requires time to tailor :)

**Comment by victorialb-usds** [comment]
I did not have time to cross check and align with federal CX work. I would do a quick and dirty look at this not spend too much time.

**Comment by BerniXiongA6** [comment]
Thanks @victorialb-usds - will do!
