### ISSUE TITLE
VT - Incorrect observation status of "X" in SimpleReport

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4381]
On 2/15, VT reported:

"We are seeing an increasing number of results from SimpleReport come to Vermont with an Observation Status = X. Reviewing the messages, it appears from the notes that the test was cancelled. These messages are failing to process successfully into our surveillance system (we use NBS). This was not previously an issue, and we first began seeing this about a week ago and the rate appears to be increasing. Can you help me understand the workflow in SimpleReport that creates these messages, and would it be possible to work together to identify 1. Whether this data should be reported to public health and 2. If it should be reported, a way to format the message that ensures it processes successfully?"

**Comment by anshulkumar-usds** [comment]
Appears to be related to the issue reported by GU: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4266

**Comment by anshulkumar-usds** [comment]
2/16: Checking with VT on their preference for "W"

**Comment by anshulkumar-usds** [comment]
2/16: @LGFranklin will setup a call with VT to discuss SR workflow. RS can support "W", or filtering these out entirely for VT.

**Comment by Adrian-Brewster** [comment]
@LGFranklin and @zdeveloper met with VT. Vermont would prefer to not receive the cancellation notifications. For tests that the SimpleReport user cancels/deletes, VT would also like the original message generated for that result to not be sent as the user has indicated this is not a valid result. If that’s not possible, VT would like the result for that test to be updated to “Test Not Performed” when the user cancels/deletes the test in SimpleReport.

**Comment by Adrian-Brewster** [comment]
@brick-green-agile6 @jorg3lopez @oslynn @MauriceReeves-usds Can someone pick this up now that we have clear requirements from VT?

**Comment by brick-green-agile6** [comment]
@Adrian-Brewster Sending the result with a status of W means that the original message was sent incorrectly. Are they unable to support W? If not now, do they have plans to adopt it in the future along with the other result status options? What field should "Test Not Performed" be placed in? Should that value overwrite whatever is currently in that field?

**Comment by LGFranklin** [comment]
See above from 10 days ago. They prefer not to receive cancellation notifications.

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 VT also needs "X" and "W" filtered out entirely. I will assign this to you as well.

**Comment by brick-green-agile6** [comment]
I can filter out the W messages. But we cannot update the result to "Test Not Performed" for the first result. The result is sent out of simple report pretty quickly after it's entered. So it would most likely have already been sent by the time the user marks it as an error.

**Comment by brick-green-agile6** [comment]
Made the setting change to filter all messages except those with F, C, or P.

**Comment by anshulkumar-usds** [comment]
3/15: VT confirmed issue is settled on their side. Closing.
