### ISSUE TITLE
CO Sender - SDI - Interim Research

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#4384]

**Comment by loripusey** [comment]
What does interim research consist of?

**Comment by victorialb-usds** [comment]
**Assess how the intervention is going so we can provide support and collect data about pain points.  

## To do
- [ ] Assign RS team member as note taker (if possible) 
- [ ] Conduct meeting and take notes in ongoing notes doc
https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BC6413B25-BFC2-47D7-AEEE-126F37BE87CD%7D&file=Interim%20Check-in%20calls%20raw%20notes_CSV%20Uploader.docx&action=default&mobileredirect=true
