### ISSUE TITLE
Verify Identities of STLT contacts requesting access to Download Site

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4386]
As a data platform, we avail test results to STLTs through ELR and a Download Site. To promote better security practices, we need to confirm the identity of STLT contacts that are requesting access to the Download Site. 

1. Work with the SimpleReport (Leslie Franklin) team to understand how this is done today for SR users and facilities. 

2. Document the process and create SOP for applying the same set of principles and practices for ReportStream Download Site

**Comment by anshulkumar-usds** [comment]
@sarahnw can you please share an update on this?

**Comment by sarahnw** [comment]
Ready for input here: https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/doc2.aspx?sourcedoc=%7Bbdf0ba0c-08d3-4057-9533-fe33764d5622%7D&action=editnew

**Comment by anshulkumar-usds** [comment]
@sarahnw can you please share an update on this?

**Comment by Adrian-Brewster** [comment]
Sarah planning to review with team on Thursday
