### ISSUE TITLE
GlobalContext isn't really used correctly

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#4390]
When changing orgs, the code current does this:
```javascript
 updateOrganization(orgName);
 window.location.reload();
```
to reload everything. `updateOrganization()` should really set state on the global context (aka `createContext`)

**Comment by loripusey** [comment]
What is the impact to the end user and/or functionality?
Can you use the bug template in ZenHub for reporting bugs in the future?

**Comment by TomNUSDS** [comment]
User impact: More full page reloading than should be required. Right now it only impact Admins.

**Comment by kevinhaube** [comment]
The context itself wasn't doing much but packaging up the sessionStorage. This will be refactored out due to changes made in #4630

**Comment by kevinhaube** [comment]
GlobalContext no longer exists in our project
