### ISSUE TITLE
MD - Incorrect observation status of "X" in SimpleReport

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4392]
MD is also reporting receiving "X" in OBR-25 under observation status instead of P, F or C

Sample messages
Complete Care Severna Park	2/9/22 5:36 AM	```3a12a0df-d1ab-4556-a477-54ce808c188f```
sanchez pediatrics	2/10/22 11:26 AM	```ae25a69f-5726-48f3-b48d-1192d743e022```
ResultsLab,LLC	2/14/22 5:30 AM	```7a9e18e3-63c0-435a-9da5-a44d3fa90833```
Brightview White Marsh	2/8/22 2:16 PM	```ae25a69f-5726-48f3-b48d-1192d743e022```

**Comment by anshulkumar-usds** [comment]
2/16: MD confirmed they do not want "W" or "X" results
cc: @MauriceReeves-usds @brick-green-agile6

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 MD wants "W" and "X" messages excluded from their feed.

**Comment by anshulkumar-usds** [comment]
3/1: MD reported they are continuing to see failures due to this issue with invalid values in OBR-25. Sample messages:
```
15e808a5-8a43-432f-a4c6-0afc52624ffa
515a8fe7-0bc5-4d24-99eb-5984fd342de8
```

**Comment by brick-green-agile6** [comment]
Just pushed the settings change in production

**Comment by anshulkumar-usds** [comment]
3/14: Checking with MD to validate results.

**Comment by anshulkumar-usds** [comment]
MD confirmed data is good. Closing.
