### ISSUE TITLE
OO/Bug: NTE Fix

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#4402]
## Problem statement
In a Schema, if comment_source is set to "L", the NTE.2 is created as if the DataType is CE instead of ID which is wrong.  CA-DPH rejects our message as-is.

Example, below is the NTE currently created.
NTE|1|L^Ancillary (filler) department is source of comment^HL70105|Test Comment|RE^Remark^HL70364^^^^2.5.1

It should be:
NTE|1|L|Test Comment|RE^Remark^HL70364^^^^2.5.1

## Acceptance criteria
- [ ] If comment_source is set to "L", then the NTE.2 should be "|L|"

## To do
- [ ] ?????

**Comment by MauriceReeves-usds** [comment]
There are three ways this should be tested:
1. We should create a unit test that submits a message to the HL7 serializer and looks at the NTE segment directly
2. We should create an integration test that includes two types of comments, one with comment_source = ‘L’ and and one where it is not set to ‘L’. The integration test should then verify that the created HL7 matches what is expected. This is an extension on the existing integration tests we have now.
3. Create a test file that includes both L and non-L comments and submit it to the local Docker container. Verify that the comments are encoded correctly.
