### ISSUE TITLE
Provide Consolidated identical log messages in the Submission History API response

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#4417]
The current (soon to be old) json response combines identical error messages.  The new History Details API does not have that feature.  This ticket is to add that feature to the new History Details API response.

### Current Submissions History API response:

```
    "errors": [
        {
            "scope": "item",
            "index": 1,
            "trackingId": "a",
            "type": "error",
            "message": "Blank value for element 'Patient_last_name' ('patient_last_name')"
        },
        {
            "scope": "item",
            "index": 2,
            "trackingId": "b",
            "type": "error",
            "message": "Blank value for element 'Patient_last_name' ('patient_last_name')"
        },
        {
            "scope": "item",
            "index": 3,
            "trackingId": "c",
            "type": "error",
            "message": "Blank value for element 'Patient_last_name' ('patient_last_name')"
        },
        {
            "scope": "item",
            "index": 5,
            "trackingId": "e",
            "type": "error",
            "message": "Blank value for element 'Patient_last_name' ('patient_last_name')"
        }
    ],
```

Note the current REPORTS API has the following format:
```
{
            "scope": "item",
            "message": "Invalid code: 'WRONG_specimen_type' is not a display value in altValues set for 'Specimen_type_code' ('specimen_type').",
            "itemNums": "Rows: 7 to 8, 10"
        },
```

###  AC:  Desired New History API Response, replacing the above, once this ticket is done:
Would consolidate to:

```
  "errors" : [ {
    "scope" : "item",
    "message" : "Blank value for element 'Patient_last_name' ('patient_last_name')",
    "indexListString" : "1-3,5",
    "indexList": [1,2,3,5],
    "type": "error",
    "trackingIdList":  [ "a","b","c","e"]
  } ],
```

Per @rachelhanster : "Yesss ---  we want users to see the same error messaqes toqether. UI would return somethinq like:   Blank value for element 'Patient_last_name in Rows 1, 3, 6-10"

### Design considerations

- The rule is that any action_log entries with the same 'scope', 'type', and 'message' strings, can be consolidated.
- The number of entries in the indexList and trackingIdList should always be Identical, with identical ordering and correspondence between the two arrays.
- Its possible the user will not supply tracking Ids, so they'll be empty.   So in cases where there is no tracking id, what do we do?  An empty string?  (eg, `"trackingIdList":  ["a","","c","e"]`)  Most often if one tracking id is missing, they are all missing.  This will look ugly, like `["","","",""]`
- potentially we could do the indexList and trackingIdList arrays in the back end, and let the front end create the more readable "1-3,5" string.  Note that this code is already written to do this, in kotlin.  Should be able to grab and re-use.
- This should apply to both errors and warnings.    It should probably apply to filters as well.  Needs brief discussion.

**Comment by jimduff-usds** [comment]
The current (soon to be old) json response combines identical error messages.  The new History Details API does not have that feature.  This ticket is to add that feature to the new History Details API response.

### Current History API response:

'''
    "errors": [
        {
            "scope": "item",
            "index": 1,
            "trackingId": "a",
            "type": "error",
            "message": "Blank value for element 'Patient_last_name' ('patient_last_name')"
        },
        {
            "scope": "item",
            "index": 2,
            "trackingId": "b",
            "type": "error",
            "message": "Blank value for element 'Patient_last_name' ('patient_last_name')"
        },
        {
            "scope": "item",
            "index": 3,
            "trackingId": "c",
            "type": "error",
            "message": "Blank value for element 'Patient_last_name' ('patient_last_name')"
        },
        {
            "scope": "item",
            "index": 5,
            "trackingId": "e",
            "type": "error",
            "message": "Blank value for element 'Patient_last_name' ('patient_last_name')"
        }
    ],
```

###  AC:  Desired New History API Response, replacing the above, once this ticket is done:
Would consolidate to:

  "errors" : [ {
    "scope" : "item",
    "message" : "Blank value for element 'Patient_last_name' ('patient_last_name')",
    "indexListString" : "1-3,5",
    "indexList": [1,2,3,5],
    "trackingIdList":  [ "a","b","c","e"]
  } ],


Per @rachelhanster : "Yesss ---  we want users to see the same error messaqes toqether. UI would return somethinq like:   Blank value for element 'Patient_last_name in Rows 1, 3, 6-10"

### Design considerations

- The rule is that any action_log entries with the same 'scope', 'type', and 'message' strings, can be consolidated.
- The number of entries in the indexList and trackingIdList should always be Identical, with identical ordering and correspondence between the two arrays.
- Tracking Ids are not required.   So in cases where there is no tracking id, what do we do?  An empty string?  (eg, `"trackingIdList":  ["a","","c","e"]`)  Most often if one tracking id is missing, they are all missing.  This will look ugly, like `["","","",""]`
- potentially we could do the indexList and trackingIdList arrays in the back end, and let the front end create the more readable "1-3,5" string.  Note that this code is already written to do this, in kotlin.  Should be able to grab and re-use.

**Comment by jimduff-usds** [comment]
Arrg.  I think we're going to need to treat fixing the filtering messages as a separate 

```
"destinations": [
        {
            "organization_id": "de-dph",
            "service": "elr",
            "filteredReportRows": [
                "For de-dph.elr, filter isValidCLIA[testing_lab_clia] filtered out item 808969 at index 1",
                "For de-dph.elr, filter isValidCLIA[testing_lab_clia] filtered out item 253262 at index 2",
                "For de-dph.elr, filter isValidCLIA[testing_lab_clia] filtered out item 508806 at index 4"
            ],
            "sending_at": "2022-03-01T15:59Z",
            "itemCount": 1,
            "sentReports": [
                {
                    "reportId": "bd512b74-9f5c-4c06-b5ba-095f7d6bea66",
                    "externalName": "covid-19-b9015ff1-2274-4cfb-8bb6-8421ede79472-20220301155902.hl7",
                    "createdAt": "2022-03-01T15:59:05.352756Z",
                    "itemCount": 1
                }
            ],
            "organization": "Delaware Division of Public Health"
        }
    ],

```

**Comment by JGreenFearless** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/4417?planning-poker) with ZenHub @smythe5

**Comment by TomNUSDS** [comment]
I could see breaking out the column name into its easily parsable field.
The goal is to allow a client to show a spreadsheet and show the cells that have issues (this requires row AND column).

e.g. 
```json
"errors" : [ {
    "scope" : "item",
    "message" : "Blank value for element 'Patient_last_name' ('patient_last_name')",
    "indexListString" : "1-3,5",
    "indexList": [1,2,3,5],
    "type": "error",
    "trackingIdList":  [ "a","b","c","e"]
  } ],
```
Would required string parsing the human readable text field to extract the column name.

```
"errors" : [ {
    "scope" : "item",
    "message" : "Blank value for element 'Patient_last_name'",
    "column":  "patient_last_name",
    "indexListString" : "1-3,5",
    "indexList": [1,2,3,5],
    "type": "error",
    "trackingIdList":  [ "a","b","c","e"]
  } ],
```

**Comment by carlosfelix2** [comment]
Held a meeting 3/7/2022 to talk about the contents of the errors/warnings.  A few changes came up with the aim to remove the antipattern of providing formatted errors to users:
1. Provide the fieldName (name of the field in the schema) and field??? (CSV column name or HL7 spec).  When null or blank it will indicate the issue is not in a field.
2. indices and trackingIds. No need to say List
3. No formatted string that shows the indices.  Will be generated in the UI if needed.
4. While type is redundant, it could be in use by someone, so leave it.
5. Would like to see some type of error code in the future, to completely create custom messages in the UI.

```
"errors" : [ {
    "scope" : "item",
	"type": "error",
CSV-    "message" : "Blank value for element 'Patient_last_name' ('patient_last_name')",
HL7-	"message" : "Blank value for element OBX-17-1 ('patient_last_name')",
    "indices": [1,2,3,5],
    "trackingIds":  ["a","b","c","e"]
	"field": "Patient_last_name"  OR "OBX-17-1"
	"fieldName": "patient_last_name"  = SCHEMA
  } ],
```

Some possible error types:
1. Missing field from schema (e.g. for a csv, the required column is missing)
2. Empty data for field (e.g. column is there but the cell is empty)
3. Truncated value (Maybe this is a type of malformed data?)
4. Malformed data: (date format wrong, number is a string, zip code format, expected enum value)
For #4, this could also be a set of enumerated error strings?
