### ISSUE TITLE
NJ - ORC 12.3 and OBR 16.3 Issues

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#4428]
**Describe the bug**
Please note the errors below in ELR File: covid-19-e46bb24d-351f-4a28-8f40-23c04e823898-20220217141615.hl7
 
Orders:
`2f03bb44-0e87-4198-9e42-364126b138fc`
`95b29bd0-82e6-4c21-a9a2-24ff421ba1fe`
 
Issues in ORC-12.3 and OBR-16.3  The provider’s  “given name” is “SOMERSET VALLEY VISITING NURSE ASSOCIATION INC.”. 

NJ has corrected these, but this has recurred a number of times.  Please correct this so it does not occur in the future.

**Comment by Adrian-Brewster** [comment]
If fields are truncated, resend affected files.

**Comment by oslynn** [comment]
They are corrected in ticket 4163.  The PR is: https://github.com/CDCgov/prime-reportstream/pull/4529
![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/f3089c9e-7e8f-48cc-8489-0ebcf5d5b924)
