### ISSUE TITLE
NJ - OBR-25 and OBX-11

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#4429]
**Describe the bug**
Please note the errors below in ELR File: covid-19-ca446a5b-acdf-49b0-8361-044448cec94b-20220217141559.hl7
 
Order: `985cc42e-6e33-4b91-8153-71c3f8fd9fdc`
 
OBR-25 and OBX-11 are missing.  Please correct and resubmit.

**Comment by Adrian-Brewster** [comment]
Order: `26709bb3-667e-4d86-84ba-4c358ac9a675`
OBR-25 / OBX-11 are missing – Please correct and resubmit.
 
Order: `c8e8cc70-f272-46a2-886e-547451dc4b85`

**Comment by Adrian-Brewster** [comment]
File: covid-19-3e1266d4-f379-4c07-aaba-f57e764b3735-20220218141618.hl7
 
Orders:
`2ad95397-b643-421e-aab0-1478e335554a`
`3546774e-0877-4fa5-be87-ef09f69fe278`
`91048247-7438-403b-acc2-01e5f26b34b6`
`c33f5615-6237-4246-8ed6-6a340ab6ba71`

**Comment by Adrian-Brewster** [comment]
Order: `26709bb3-667e-4d86-84ba-4c358ac9a675`
OBR-25 / OBX-11 are missing – Please correct and resubmit.
 
Order: c8e8cc70-f272-46a2-886e-547451dc4b85

**Comment by Adrian-Brewster** [comment]
Assigning to Jorge. May need SimpleReport to resubmit with different final result status.

**Comment by Adrian-Brewster** [comment]
Please note the errors below in your ELR File: covid-19-ed564ebc-f535-4438-a401-42083884d6a9-20220220141535.hl7
 
Order: `59fe81a3-49b6-4a7a-b467-3c4ee441fc94`
 
OBR-25 / OBX-11 are missing.  Please correct and resubmit

**Comment by Adrian-Brewster** [comment]
Please note the error below in your ELR File: covid-19-17cea486-46f7-45aa-bfc7-ffa496d33c6b-20220221141553.hl7
 
Order: `8248cc8a-6913-49dc-b81f-a783d09dcda2`
 
OBR-25 / OBX-11 are missing.  Please correct and resubmit.

**Comment by Adrian-Brewster** [comment]
Please note the errors below in your ELR File: covid-19-deee5a15-5c95-4e13-b4f3-9878ced77594-20220221141554.hl7
 
Orders:
`7095df8a-94a3-41fa-a68f-3e19f3ec28b7`
`072f2890-f9f9-44b0-90c7-a0249b30589f`
 
OBR-25 / OBX-11 are missing.  Please correct and resubmit.

**Comment by Adrian-Brewster** [comment]
Please note the errors below in your ELR File: covid-19-dda4fb02-be38-4529-bf93-0d75e76f9aea-20220219141620.hl7
 
Orders:
`118ba642-028d-4b25-928d-4c9244c6cc9d`
`9e1e61f2-8bb0-45d9-9721-49df919f3b46`
`620a80f8-45fd-4fca-9f6d-a223069d6f35`
`2765586b-2f25-4ec6-8f8c-8a62edd51b26`
 
OBR-25 / OBX-11 are missing.  Please correct and resubmit.

**Comment by Adrian-Brewster** [comment]
Please note the errors below in your ELR File: covid-19-107bcf28-27f5-49fe-a328-a92aae952d82-20220219141609.hl7
 
Orders:
`eeb3edc4-9304-4ab7-b478-7766ef17c955`
`7cba8be6-9e82-49e3-92fc-f548b8d0fd0b`
`a45b5a6b-3f96-4fd5-b38d-f72ceef0f374`
 
OBR-25 / OBX-11 are missing.  Please correct and resubmit.

**Comment by Adrian-Brewster** [comment]
Please note the errors below in you ELR File: covid-19-ba4618ac-8313-45b2-b400-ae3e312eb07d-20220220141535.hl7
 
Order:`81d1c74d-8316-433a-a008-cb17d8309272`
 
OBR-25 / OBX-11 are missing.  Please correct and resubmit.

**Comment by Adrian-Brewster** [comment]
Please note the errors below in your ELR File: covid-19-8c961d82-f23f-40fd-9754-4443064b7fe6-20220222141613.hl7
 
Order: `d997e29c-d727-48e5-ab24-7e4d5c3cd85c`
 
OBR-25 / OBX-11 are missing.  Please correct and resubmit.

**Comment by Adrian-Brewster** [comment]
File: covid-19-d311193b-f82e-414e-9384-c9b857d9520b-20220224141557.hl7

OBR-25 / OBX-11 missing.  Please correct and resubmit.

**Comment by Adrian-Brewster** [comment]
File: covid-19-13823a98-ce46-4dc8-b7b6-1e9074862205-20220224141555.hl7
 
OBR-25 / OBX-11 missing.  Please correct and resubmit.

**Comment by Adrian-Brewster** [comment]
Please note the errors below for file covid-19-927db0cd-a852-48da-ac82-5be564c6f6a7-20220224141549.hl7
 
OBR-25 / OBX-11 are missing.  Please correct and resubmit

**Comment by Adrian-Brewster** [comment]
Please see errors below.
 
File: covid-19-24b7eac8-b926-47c0-a897-c61a29759b8b-20220223141628.hl7
 
Missing OBR-25 / OBX-11.  Please correct and resubmit.

**Comment by Adrian-Brewster** [comment]
Please see errors below.
 
File: covid-19-7c92beed-a93b-4777-860e-21955124df6d-20220223141617.hl7
 
Missing OBR-25 / OBX-11.  Please correct and resubmit.

**Comment by Adrian-Brewster** [comment]
Please see errors below.
 
File: covid-19-24e3054d-7688-41a3-8534-70f60a9e2c34-20220223141610.hl7
 
Missing OBR-25 / OBX-11.  Please correct and resubmit.

**Comment by Adrian-Brewster** [comment]
Please see errors below.
 
File: covid-19-bcfb4316-ed5b-46f5-bc9b-0b2e52f0a7bb-20220223141614.hl7
 
Missing OBR-25 / OBX-11.  Please correct and resubmit.

**Comment by Adrian-Brewster** [comment]
Please note the errors below in your ELR File: covid-19-b0e0bf97-9703-4fd1-bff1-f0b2b0ed4a92-20220222141616.hl7
 
Orders:
`96636308-27d0-4d8e-8bc9-2d097632e733`
`8c760ec1-3d7f-4ee9-aeda-26717702ec5c`
`a4c88786-8ace-4f7a-8fd9-c3164756f269`
 
OBR-25 / OBX-11 are missing.  Please correct and resubmit.

**Comment by Adrian-Brewster** [comment]
Please note the ELR errors below from file: covid-19-86ac7f22-f9fd-4b52-b2c2-71cd9cb35535-20220225141616.hl7
 
OBR-25 / OBX-11 are missing.  Please correct and resubmit.

**Comment by jorg3lopez** [comment]
@Adrian-Brewster @anshulkumar-usds Do we know if NJ is ok with receiving OBX - 11 with code of 'W'?

**Comment by anshulkumar-usds** [comment]
Notes in a duplicate ticket: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4427

**Comment by anshulkumar-usds** [comment]
3/1: @jorg3lopez I am checking with NJ if they can accept "W". Will report back once I hear back.

**Comment by anshulkumar-usds** [comment]
3/2: @jorg3lopez NJ noted the following in their response:

- For OBR-25, they can accept values from table HL70123: https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.815
- For OBX-8 and OBX-11, they can accept values from table HL70085: https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.811

Hence, NJ can accept "W" for OBX-11, bot not for OBR-25

**Comment by anshulkumar-usds** [comment]
3/3: Notified NJ of this updates. Thanks @jorg3lopez

**Comment by anshulkumar-usds** [comment]
NJ needs us to resubmit. I am checking with NJ on the date range for resubmissions.

**Comment by Adrian-Brewster** [comment]
CDC Prime: Error in Rhapsody Route in PRODUCTION



General
General
RS
Report Stream (CDC)
Fri 3/4/2022 4:11 PM










To: Kumar, Anshul (CDC/OD/OCS)



Reply

Forward

You forwarded this message on Fri 3/4/2022 4:11 PM
You forwarded this message on Fri 3/4/2022 4:11 PM
DN
DOH-ADMIN NJELR [DOH] <NJELR.ADMIN@doh.nj.gov>
Mon 2/28/2022 1:37 PM










To: Kumar, Anshul (CDC/OD/OCS); Report Stream (CDC); Liu, James (CDC/OD/OCS); Reeves, Maurice (CDC/OD/OCS)
Cc: Boyd-Lee, Joyce [DOH] <Joyce.Boyd-Lee@doh.nj.gov>; Melendez, Jenizah A [DOH] <Jenizah.Melendez@doh.nj.gov>+4 others
Please note the errors below in your ELR File: covid-19-cf54151a-1632-4759-b2af-3a9fd2466884-20220226141613.hl7
 
OBR-25 has an illegal value.  Please correct and resubmit.

**Comment by anshulkumar-usds** [comment]
@jorg3lopez please use the files and messages Adrian posted above in the comments for resubmissions. NJ did not provided a consolidated list of messages.

**Comment by jorg3lopez** [comment]
@anshulkumar-usds this file contains the test results that were only provided the report id. [https://app.zenhub.com/files/304423150/2582e6b7-0940-46bf-a137-7d8bb9d49d4e/download](https://app.zenhub.com/files/304423150/2582e6b7-0940-46bf-a137-7d8bb9d49d4e/download)

**Comment by jorg3lopez** [comment]
@anshulkumar-usds All about message ids, including the ones in the excel file, have been resubmitted to NJ.
File name:
`covid-19-4b9c7749-0ffa-4ce6-9b53-955d4859fc7a-20220311194303`

**Comment by Adrian-Brewster** [comment]
@anshulkumar-usds to follow up with NJ

**Comment by anshulkumar-usds** [comment]
3/14: Informed NJ of these two files. Waiting for NJ to validate and confirm.

**Comment by anshulkumar-usds** [comment]
3/18: After multiple follow ups with states, no response received. Closing for now.

**Comment by jorg3lopez** [comment]
@anshulkumar-usds So far, we have blocked OBX-11 from getting code of 'W'. We are still waiting for Simple Report to have a designated filed for OBR-25-1. Without this, OBR-25-1 will end up with a "W" and produce failures in their system.
