### ISSUE TITLE
Submission history: allow sender to refresh list if new submissions have been made during their session

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#4438]
## Problem statement

If a user is clicking around their submission history (next/prev, filtering, etc) and new results are submitted, they won't necessarily see those new results in the list.

## What you need to know

This is due to cursor pagination. Tom flagged this while working on submission history.

Possible ideas to test: 

- Automatically refresh the history
- Have a persistent manual refresh button somewhere
- Show a manual refresh button only when we know there are new results to display. Have seen the below pattern on a site and it works pretty nicely.
<img src="https://images.zenhubusercontent.com/5ff50e49f74e134e95117280/aae98732-cef1-469e-8545-789be4e87013" width="800px" />

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by rachelhanster** [comment]
Ticket moving to simplereport for its product backlog consideration

**Comment by chris-kuryak** [comment]
Closing by committee. Old Issue. CSV Uploader.
@drew-usds @lizzieamanning
