### ISSUE TITLE
Guam - Missing OBR-25/OBX-11 Values

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#4458]
Per an email sent 18-Feb-2022, Guam had some additional messages come in missing OBR-25 and OBX-11. They provided the following message IDs:

```
52703f7c-800a-4fcb-86d6-f0735dac0135

12524e75-c92c-4e72-8400-f5151f9fa180

dcfe0aae-001c-4209-aa42-fdffa0f5c695

73e1421e-aaab-4aa4-85d4-27b5fcfd580e

05a3d4a7-3502-457e-990c-3c520ed41145
```

Here is the content of the email from Lindsey:

> Adding the Simple Report team to this ticket; We had some failures on 2/17 due to missing OBR-25/OBX-11 values. Below are some accessions. Could these be related to code being implemented to only send results with “F,” “P,” or “C” status codes?

FYSA: @Adrian-Brewster @sarahnw @anshulkumar-usds

**Comment by brick-green-agile6** [comment]
added message IDs to other ticket. Closing duplicate
