### ISSUE TITLE
IL - Not Receiving Observation Status

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#4465]
**Describe the bug**
IL is not receiving the observation result status in the OBX which is a required field.
 
![image.png](https://images.zenhubusercontent.com/60d1eba7caf0775fd79203f8/3f05c3da-67b9-4b3c-80d4-260612dc4425)

![image.png](https://images.zenhubusercontent.com/60d1eba7caf0775fd79203f8/c71de5ff-5aa1-430b-9ea3-72ab51212b3a)
 
![image.png](https://images.zenhubusercontent.com/60d1eba7caf0775fd79203f8/e4985c73-3e87-4a10-83ff-3be01b045fe1)

**Impact**
 
This is causing a good number of records to have to manually be touched and it is unclear whether these should be Finalized result statuses or not.

![image.png](https://images.zenhubusercontent.com/60d1eba7caf0775fd79203f8/3a167974-6c6c-459a-a137-526b9aedf5e1)

**Comment by oslynn** [comment]
I checked this ticket as follows and our software produced Observer Result Status.
1.) ./prime data --input-fake 100 --input-schema PrimeDataInput/pdi-covid-19 --output ./junk/pdi-nj-testing.csv --target-states NJ 
2.) ./prime data --input junk/pdi-nj-testing.csv --input-schema PrimeDataInput/pdi-covid-19 --output-dir junk --route
3.) Verify the OBX-11:
![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/8f55f4a4-e85b-4995-b9d0-3a5ab764c3f1)

**Comment by anshulkumar-usds** [comment]
@Adrian-Brewster I think this ticket is for IL, not for NJ right? I think that'll inform @oslynn investigation. I saw this was reported by Nicholas at IL.

**Comment by anshulkumar-usds** [comment]
@oslynn could you please take a look at this again. Please note this is for IL, not NJ

**Comment by oslynn** [comment]
Per @jorg3lopez, @Adrian-Brewster or @anshulkumar-usds need to verify with IL that they want to accept OBX-11 with 'W' or not.  If they do, we need to resubmit.

**Comment by anshulkumar-usds** [comment]
@oslynn @jorg3lopez IL does NOT want "W" in OBX-11 or OBR-25. Please exclude from their feed.

**Comment by anshulkumar-usds** [comment]
3/3: Correction to my comment earlier. IL provided a full list of values that they accept in their OBR and OBX fields"

OBR list:
![IL OBR.png](https://images.zenhubusercontent.com/607d9d4a591b7cc0bb55c82e/727fbb0d-d263-4931-a9d5-584172d89c7e)

OBX list:
![IL OBX.png](https://images.zenhubusercontent.com/607d9d4a591b7cc0bb55c82e/bb4771f2-0065-4c0a-aadb-9c6353c4fa51)

**Comment by oslynn** [comment]
I am creating PR for review, now.
