### ISSUE TITLE
Design for validating a FHIR Bundle against a Profile

### ISSUE THREAD

**Issue by whytheplatypus** [CDCgov/prime-reportstream#4469]
## ReportStream should be able to ensure a FHIR Resource conforms to an expected Profile.

A given FHIR resource should be validated against a provided profile and/or the information listed in the Resource.meta.profile attribute. This should use existing validation libraries.

## What you need to know

- [FHIR Validation](https://www.hl7.org/fhir/validation.html)
- [Similar example in the wild](https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir/validation-against-profiles)

## Acceptance criteria (questions to be answered)

- [ ] Document the validation design
- [ ] A list of libraries that can accomplish this (may only be one)
- [ ] An example of use of each library - internally demo-able
- [ ] A decision record for the recommended library

- [ ] How will profiles be provided?
- [ ] How will profiles be stored?
- [ ] How will custom profiles be handled?

### Optional:
- [ ] A comparison between those libraries

## To do

- [ ] ...

**Comment by JGreenFearless** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/4469?planning-poker) with ZenHub @TurkeyFried

**Comment by JGreenFearless** [comment]
@carlosfelix2 @clediggins-usds I believe you guys have covered this in other tickets.  Can we close this?

**Comment by carlosfelix2** [comment]
Closed while we figure out what we really want to do with profiles if anything.
