### ISSUE TITLE
Design how to validate incoming HL7 v2 messages

### ISSUE THREAD

**Issue by whytheplatypus** [CDCgov/prime-reportstream#4470]
### User Story:
As ReportStream, I want HL7 message submissions to be validated beyond being a valid HL7 message, so we accept only submissions that meet the minimum set of data.

### Description/Use Case
We currently verify the the HL7 message being received is a valid message (e.g. structure), but we do not check anything else like a minimum set of data.  We need a way to specify what minimum requirements we need of HL7 data as well as the ability to verify data values we need.  E.g., we reject data that has no patient last name, or message ID, or for a specific sender it needs to be a set of LOINC codes.  This issue is to design how we are going to implement this validation step as well as how will we configure it for different senders.

### Risks/Impacts/Considerations
* Different STLTs may require different minimum data, but this ticket is solely to validate sender data for a shared minimum data set and can happen before routing.

### Dev Notes:
* Need to determine what data qualifies as 'minimum data'
* The COVID pipeline does something similar using cardinality and mappers to validate data.
* Are HL7 message profiles viable for this?
* We should be able to have a default configuration for the system, so the configuration needs to be reusable.

### Acceptance Criteria
* Design the HL7 validation component and document the design.
* Present the design to the Pipeline team to get buy-in.

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/4470?planning-poker) with ZenHub @jimduff-usds @carlosfelix2 @smythe5 @jh765 @TurkeyFried @whytheplatypus

**Comment by JGreenFearless** [comment]
@carlosfelix2 @clediggins-usds You've covered this work in other tickets, correct? Can we close this?

**Comment by avnieldravid** [comment]
Check in with @carlosfelix2
