### ISSUE TITLE
Submission API timestamps are different from reports API

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#4471]
Timestamps must be formatted the same to make the submission API response to be identical to the reports API.

E.g., current timestamp for the submissions API:
 "timestamp": "2022-02-16T14:12:54.942551-05:00"

E.g., current timestamp of reports API:
"timestamp": "2022-02-22T15:31:57.085816600Z"

Furthermore, the reports API is using two different timestamp formats within the same response.  See timestamp and sending_at below.
```
"timestamp": "2022-02-24T13:52:09.702263Z",
    "topic": "covid-19",
    "reportItemCount": 1,
    "sender": "lifepoint.default",
    "destinations": [
        {
            "organization": "HHSProtect",
            "organization_id": "hhsprotect",
            "service": "elr",
            "sending_at": "2022-02-24T09:00-05:00",
            "itemCount": 1
        },
```

Acceptance criteria:
1. The timestamps returned by the submissions API must match the format used in the reports API.
2. The timestamps returned within a reports API response should use the same format.

**Comment by MauriceReeves-usds** [comment]
My own $0.02 I would prefer we standardize on UTC and explicitly include the `Z` marker per the reports API.

**Comment by jimduff-usds** [comment]
OK, we will change the Submissions API to use Z style.

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/4471?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @smythe5 @TurkeyFried @whytheplatypus
