### ISSUE TITLE
PHDI FHIR Server

### ISSUE THREAD

**Issue by JSkeets** [CDCgov/prime-reportstream#4474]
**Description**
The PHDI team has a FHIR server which was spun up via the console. We need to create an Azure API for FHIR which is managed in terraform and has the appropriate security restrictions as this will be used to handle PII.

The current server (spun up via console, seeded with fake data) https://portal.azure.com/#@cdc.onmicrosoft.com/resource/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourceGroups/prime-ingestion-test/providers/Microsoft.HealthcareApis/services/phdi-cdm-fhir-server/overview

The current server should not be used as an import into a terraform state as it has fake data, and the server with seeded data should be kept separate from the one containing PII (which this one will) 

cc: @NatHillardUSDS @jeremyzitomer-usds 

**Specific Requested resources**
- Azure API for FHIR (phdi-fhir-api-prod)

**Existing Resources?**
Are there any existing resources that we will need to delete or modify for this?

**Additional Context**
Any additional necessary context?

**Comment by NatHillardUSDS** [comment]
(Note from Devops sync just now: we can equivalently secure our resources by means of a separate VNET; this has the added benefit of not consuming precious IP addresses)
