### ISSUE TITLE
Settings API: Validation fixes/enhancements

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#4476]
## Problem statement

During the course of developing (and bug bashing) the Admin Settings UI, some inconsistencies and shortcomings around the settings API updates were discovered that had to be worked around (where possible).

1. On Receiver updates, the filter fields ("jurisdictionalFilter","qualityFilter","routingFilter","processingModeFilter")
- "[]" must be sent to indicate a blank value, whereas other fields require a empty string or null
- invalid JSON can be send to the API, but it is simply ignored instead of failing the API call and/or reporting back the error. see #4322 for example
2. On Receiver updates, the fields "Timing" and "Transport" _can_ be sent to indicate a blank value. However...
- invalid JSON can be send to the API, but it is simply ignored instead of failing the API call and/or reporting back the error. ex. you can send "{ sdfsdf }"
3. Generally when validation _does_ fail when updating these types of fields, only one blanket message is reported back from the API: "Could not parse JSON payload" - leaving the consumer to sometimes guess which field triggered the response

## What you need to know

- #4293
- #4322
- possibly #4323

## Acceptance criteria

- [ ] When any JSON-type field contains invalid JSON, it should consistently fail the call and return a more detailed "error:" response to the client about what went wrong
- [ ] Wherever possible, sending empty string or null for any particular field should be allowed and interpreted as a blank value. If the field in question is absolutely required (as Translation seems to be), it should provide a more detailed message to that effect.

## To do

- [ ] ...

**Comment by JGreenFearless** [comment]
@sethdarragile6 Validating that this falls under the History API epic?

**Comment by sethdarragile6** [comment]
@JGreenFearless Not sure what epic this would fall under, but it's related to the Settings API (which I understand to be unrelated to the History API)
