### ISSUE TITLE
Send government approval to conduct likelihood of referral, customer satisfaction survey

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#4482]
## Problem Statement
As a government product, ReportStream falls under Public Records Act rule to reduce paperwork for the public and must apply for approval to send a customer satisfaction survey. 

## Acceptance criteria:

- [x] Fill out form, "Request for Approval under the “Generic Clearance for the Collection of Routine Customer Feedback” (OMB Control Number: 0920-1050)"

- [x] Submit form

## Note
[Draft form](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B7050465F-82E0-4E58-9A9D-EBD3EE2A335D%7D&file=0920-1050_Customer_Service_GenIC_Clearance_Template%20(002).docx&action=default&mobileredirect=true&cid=44076be2-4f48-48c7-bf3b-a9aa897e9fbf)

**Comment by victorialb-usds** [comment]
Here is where I am drafting it. https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B7050465F-82E0-4E58-9A9D-EBD3EE2A335D%7D&file=0920-1050_Customer_Service_GenIC_Clearance_Template%20(002).docx&action=default&mobileredirect=true

**Comment by rachelhanster** [comment]
@victorialb-usds and I discussed this work, and I've updated the ticket. cc @BerniXiongA6

**Comment by victorialb-usds** [comment]
emailed CDC contact to ask how to submit it was not clear on the form.

**Comment by victorialb-usds** [comment]
sent for approval 3/7/22
