### ISSUE TITLE
[SPIKE] React Networking: Add cache using the browser Cache Api

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#4486]
**Is your feature request related to a problem? Please describe.**
Before we can implement our new network layer, we should implement a _client-side_ cache to prevent excess API calls. All browsers are equipped with a Cache API that lets you easily read from and write to the cache. Need to document a path forward here.

**Describe the solution you'd like (AC)**
- `useNetwork` should check for cached responses before calling the API, and return a cached response with no API call if found.
  - auto-cache things that aren't cached
  - pull things that are cached from the cache

**Additional context**
https://hazelcast.com/blog/a-hitchhikers-guide-to-caching-patterns/
Here are some caching patterns that might help with how you think about the cache implementation. Both cache-aside and write-through are great implementations! Either will serve our needs.

TO-DOs:
- decide on caching pattern/strategy to use (it doesn't look like axios has a caching mechanism)
- get a list of all the calls we're making on the FE
- see what testing exists
- coordinate w/ pipeline on effort to document APIs

**Comment by doug-s-nava** [comment]
closing this, as any caching we do now will likely be through react-query
