### ISSUE TITLE
California - Newport Children’s Medical Group - Post Research

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4503]
## Overview
Assess impact of the intervention by asking similar questions to baseline.  

## To do
- [ ] Conduct meeting and take notes in ongoing notes doc

**Comment by RakshindaAslam** [comment]
Closing per https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3557#issuecomment-1091729391
