### ISSUE TITLE
Colorado- Warrior Diagnostics - Post Research

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4511]
## Overview
Assess impact of the intervention by asking similar questions to baseline.  

## To do
- [x] Conduct meeting and take notes in ongoing notes doc

**Comment by victorialb-usds** [comment]
@RakshindaAslam @rachelhanster for sprint starting 4/27 - scheduled for 4/28

**Comment by victorialb-usds** [comment]
Notes here: https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B08F9856D-E8AE-4A0B-A2FF-E64137F7CE5C%7D&file=Warrior%20DX_Final%20Check%20in%20Facilitation%20Guide%20for%20CSV%20Pilot%20Cohort%20April%2028%2C%202022.docx&action=default&mobileredirect=true
