### ISSUE TITLE
California - Naval Health Clinic Lemoore (NHCL)- Post Research

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4518]
## Overview
Assess impact of the intervention by asking similar questions to baseline.  

## To do
- [x] Conduct meeting and take notes in ongoing notes doc

**Comment by victorialb-usds** [comment]
## Overview
Assess impact of the intervention by asking similar questions to baseline.  

## To do
- [ ] Conduct meeting and take notes in ongoing notes doc

**Comment by victorialb-usds** [comment]
@rachelhanster @RakshindaAslam pulling in for end of sprint doing it today

**Comment by victorialb-usds** [comment]
scheduled for 4/26

**Comment by victorialb-usds** [comment]
Link to notes: https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7Bfe3e1aae-6a30-4aa4-a74f-4a50bcf9969b%7D&action=edit&wdPreviousSession=4f077c9e-61cd-4b21-bc0e-3f6ac76aef26
