### ISSUE TITLE
Receiver wants to monitor and know when senders are not submitting.

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#4520]
## Problem statement

As a STLT I want to monitor and know when senders are not submitting
So that we can follow up and ensure that data is submitted as per state law. 

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by loripusey** [comment]
@victorialb-usds Closing this as [this ](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4312)ticket covers this idea
