### ISSUE TITLE
Per Receiver Integration Tests 

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#4525]
**Is your feature request related to a problem? Please describe.**
The HL7 messages that ReportStream sends to a state go through an acceptance process by the state before the feed is turned on. Every change to the system has the potential to make ReportStream's HL7 messages fall out of acceptance for a state. While it is impractical to have the state PHD go through an acceptance process on every check-in, we can run per-state integration tests on every check-in. 

**Describe the solution you'd like**
I envision a series of tools to create and update the tests

- Sender-Files: to fetch source files for a particular file sent to a state
- Preview: to run the RS pipeline with source files
- HL7-Compare: To compare two hl7 files with a set of acceptable variations
- Generate-Test: Using the previous tools, generate a per receiver integration test

**Describe alternatives you've considered**

**Additional context**
The attached presentation further explains the concept. 
[State Regression Testings.pdf](https://github.com/CDCgov/prime-reportstream/files/8133409/State.Regression.Testings.pdf)

#3394 Describes a problem that will be fixed by this epic.

**Comment by carlosfelix2** [comment]
Please note that there is an integration test that does all these functions (I think), so check that first.

**Comment by brandonnava** [comment]
@oslynn Per Carlos' comment has this already been done? Close?
