### ISSUE TITLE
Receiver facing: facility status visibility

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#4527]
## Problem statement

As a ReportStream state public health department user, I would like to have visibility into what testing facilities are in testing and production. 
## What you need to know

In interviews and meetings with receivers who are using CSV upload pilot feature both requested wanting to know 
- the status of facilities that are being onboarded to CSV upload pilot
- they are trying to track onboarding of new facilities from their side
- CA PHD said, "If we could go into report stream and get a tabled list... that would be great" 

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by victorialb-usds** [comment]
CA PHD 2/24/21 said they want to track: Start and Completion dates per Sender

**Comment by loripusey** [comment]
@victorialb-usds What do start and completion dates mean?

**Comment by victorialb-usds** [comment]
Start - when they started being onboarded to RS
Completion - when they are in production
