### ISSUE TITLE
CSV Pilot Onboarding: Receiver Facing: providing information needed for receivers to review and validate data (e.g. ascension number)

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#4540]
## Problem statement

As a public health department that is working with RS to validate results and onboard CSV upload pilot senders
I want to look up tests that have issues. 

So that (why they want to accomplish that thing)

An example:
if there is an issue with CSV test data - sometimes it hard to locate so rick will send the ascension number and then I (VB/CA PHD) can find it -- Question is this scalable if we go to more senders and more states and they have to validate. Is there are way to default/show ascension number in daily download. So that there is not manual work to enable PHDs to find and review the data. 

Call with CA PHD 2.24.22 - If there is an issue with CSV test data - sometimes it hard to locate so rick will send the ascension number and then I (VB/CA PHD) can find it -- 

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by loripusey** [comment]
Turned this into an [Epic](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4583)
