### ISSUE TITLE
Sender facing: showing proof of submission by date of submission

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#4541]
## Problem statement

As a facility using CSV upload pilot 
I want to know if I submitted results yesterday
So that I am in compliance. 

## What you need to know

From communication with user: "Also I really can’t remember if I submitted results for yesterday the 23rd, can you let me know, I have the file prepared but I can’t prove to myself if I uploaded it or not……(distractions)."
- A1H also wanted to see this

## Acceptance criteria

- [ ] 

## To do

- [ ] ...

**Comment by loripusey** [comment]
@victorialb-usds Doesn't the submission history MVP solve this problem now?
