### ISSUE TITLE
CSV Sender: Onboarding and operations - adding individuals to upload data

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#4542]
## Problem statement

As a CSV upload pilot sender
I want to add other individual to submit reports for the facility
So that [we can report daily - individuals can be sick and go on vacation]

## What you need to know

- 2.24.22 communication: "Once we are really going, can I have another person added to be able to submit the reports for us? That report would be very helpful in that situation too." 
- a big part of the invisible work of onboarding senders is the learning that takes place and the very micro practices each user created to understand the task and complete the task. 

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by rachelhanster** [comment]
Closing this ticket with uploader's move to simplereport
