### ISSUE TITLE
Duplicate detection on a per-item level

### ISSUE THREAD

**Issue by clediggins-usds** [CDCgov/prime-reportstream#4548]
Follows #2024

Using the hash on item_lineage verify that we are not getting exact duplicates, and provide feedback to user if it is.

### Acceptance Criteria
* When 'allow duplicates' is set to false on a sender, verify each individual item
* If an item is a duplicate, return friendly messages indicating this
* Add tests to verify the use cases.
* Remove SkipInvalidItems as it is no longer used

**Comment by JGreenFearless** [comment]
@clediggins-usds Which epic does this belong to?

**Comment by clediggins-usds** [comment]
@JGreenFearless 3997, updated.
