### ISSUE TITLE
MT - Missing OBX-11 Field

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#4551]
**Describe the bug**
Montana got the first correction message today, but unfortunately it failed to migrate into their instance of NBS.
 
File Name: ELR_sr_802564_covid-19-56ec2de3-c434-4aa2-bfe0-d2fe71326f0c-20220224141517.hl7
Message ID: `e986c1b3-d71b-4e62-a707-870eb545818a` , generated 2/24/2022 at 7:17 MST
 
The issue with the message was that it was blank in OBX-11, which is a required field:

![image.png](https://images.zenhubusercontent.com/60d1eba7caf0775fd79203f8/beb98a80-9e0b-4bed-a211-b320f4186d4e) 

Is there any way to remedy this? I know this field usually reads F, for Final and that could be fine for our purposes but I believe there are codes out there for “edited” but I would need to check the codebook.
 
In any case, it worked and generated the message which was really cool to see! Now just some fine tuning.

**Comment by anshulkumar-usds** [comment]
3/3: Checking with MT if they can accept values from table HL7008 for OBX-11 and OBR-25: https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.811

**Comment by anshulkumar-usds** [comment]
3/4: MT confirmed they can accept values from HL70085

**Comment by jorg3lopez** [comment]
@anshulkumar-usds @Adrian-Brewster The above test result has been resent to MT. ( 30/07/2022 )
file name:
covid-19-7fa98ee3-078e-4f1c-884f-7202145d20df-20220307220119

**Comment by anshulkumar-usds** [comment]
3/10: Checking with MT to get confirmation

**Comment by anshulkumar-usds** [comment]
3/14: @jorg3lopez MT wrote back with the following. They need some help interpreting the sample data that was sent in the test file. 

The message successfully made it into our NBS now, but I have a follow up question, is this trying to report a positive or negative result? The comment “yes, negative result - marked positive.” Is somewhat ambiguous as to which way they are trying to correct the test. Negative-> Positive or Positive  -> Negative

I have a negative result from that same collection date, so I’m thinking that it is trying to change Negative -> Positive. 

The other thing is that it did not overwrite that previous lab result, but just created a new lab report, is that what is expected? It would be nice if we could have them overwrite, but I also know that it is difficult to match accession numbers within the Simple Report platform as we’ve discussed in meetings with your team before.

**Comment by anshulkumar-usds** [comment]
3/18: @jorg3lopez please take a look at this too. Issue is mostly resolved. MT needs some explanation and clarity on how to interpret results based on the last comment above.

**Comment by anshulkumar-usds** [comment]
Shared guidance with MT based on convos with SR team.
