### ISSUE TITLE
Update Content for Programmers Guide - Appendix A

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4555]
This issue came out of [# 4101](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4101).

***

## Problem Statement
The content in Appendix A (Fields List for a Typical COVID-19 Submission aka schema documentation and guidance) of the API Programmer's Guide is out of date. As the ReportStream team, we need to update the content so that it matches the API functionality and we can provide accurate information when we distribute it to API end users.

## Acceptance Criteria
- Complete a "content" review of the final "schema doc and guidance" that will come from O&O engineering to replace Appendix A in the API Programmer's Guide so that it matches the API functionality.

**Comment by BerniXiongA6** [comment]
Updated 2.28.2022: @jbiskie and I are currently working on the pending edits and comments for v2.0 of the programmer's guide. Joel is expected to have the new "Fields list" by today for me to review and add to Appendix A of the guide. [See working doc on SharePoint](https://cdc.sharepoint.com/:w:/t/USDSatCDC/EVu-tnZPHXlPoOQ8p9HGcoABgppsEX5gA9o3rzV5PFutaQ?e=E0M0Gg).

**Comment by BerniXiongA6** [comment]
Updated 3.7.2022: Joel B. has updated the Fields List in Appendix A and responded to my pending comments/suggested revisions (as of 3/4/2022). I'll finalize content review today and will tag @drew-usds in shared doc to prepare content for staging.

**Comment by BerniXiongA6** [comment]
Updated 3.8.2022: The programmer's guide is in Review/QA pending comment responses from @jbiskie in the Appendix A: Field's List. Once these comments are resolved, I'll download the shared doc and clean up formatting and styling (should take about an hour). That final version can then be linked to RS website by UI team ( @drew-usds ).

**Comment by BerniXiongA6** [comment]
Updated 3.10.2022: [Final Appendix A: Field List](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Sender%20Pipeline/Programmer%27s%20Guide/FINAL-Programmers-Guide-Version2.0-Field%20List.docx?d=w69a4be36fdeb4cde9460f930d530541b&csf=1&web=1&e=ME0bcG) is done being edited and reviewed! Will copy/paste Appendix A content over to Programmer's Guide Version 2 by COB 3.11.2022.
