### ISSUE TITLE
Set Up ReportStream Production and Preview OKTA Instances

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4574]
## Problem Statement
ReportStream is getting its own instance of OKTA for authentication and authorization. We need to set up and configure the production and preview instances and migrate our ReportStream groups and users from the HHS instance to our new instance.

## Acceptance Critieria
- [ ] All required email templates exist in new Okta/Okta Preview instances

**Comment by bgantick** [comment]
FYI - this is on hold for now, pending further discussion.

**Comment by HeatherRienks** [comment]
Per Eng tix mtg on 12/16, closing

Notes from Okta discussion: https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B557AFAB4-141F-42DE-B1EB-1D32F009AA5B%7D&file=Okta%20-%20transition%20from%20SimpleReport%20to%20ReportStream%20-%20Summary.docx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=rut6%40cdc.gov&ct=1669653936892&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=bf31d169-bae2-455e-8bf7-f252775d713b
