### ISSUE TITLE
Configure ReportStream Production and  Staging to work with new OKTA Instances

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4575]
## Problem Statement
ReportStream is getting its own instance of OKTA for authentication and authorization. We need to set up and configure the production and preview instances and migrate our ReportStream groups and users from the HHS instance to our new instance.

## Acceptance Critieria
- [ ] Login/authentication/password reset workflows route through new Okta/Okta Preview instances

## Other considerations
- [ ] #3891 (Previous Issue for Okta Preview set up) - permissions cleanup

**Comment by kevinhaube** [comment]
Tagged stale. @drew-usds Can you make sure this is refreshed as needed once we have direction on Okta changes?

**Comment by HeatherRienks** [comment]
Closing for now. Old issue. Not sure if it is scope anymore. New issue will arise naturally if it is still needed.
