### ISSUE TITLE
Migrate ReportStream Groups & Users from HHS Production and Preview OKTA Instances to ReportStream Intsances

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4576]
## Problem Statement
ReportStream is getting its own instance of OKTA for authentication and authorization. We need to set up and configure the production and preview instances and migrate our ReportStream groups and users from the HHS instance to our new instance.

## Acceptance Critieria
- All ReportStream users from `hhs-prime.okta.com` now appear in `reportstream.okta.com`
- All ReportStream users from `hhs-prime.oktapreview.com` now appear in `reportstream.oktapreview.com`

**Comment by kevinhaube** [comment]
Tagged stale. @drew-usds Can you make sure this is refreshed as needed once we have direction on Okta changes?

**Comment by HeatherRienks** [comment]
Closing for now. Old issue. Not sure if it is scope anymore. New issue will arise naturally if it is still needed.
