### ISSUE TITLE
SFTP Send to Texas Failed Successfully!

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#4578]
## Background
In the last mile problems query in Metabase, I noted the following "failed successfully" message sending to Texas:

> Success: sftp upload of CDCPRIME_11D2030855_20220227201543.hl7 to SFTPTransportType(host=sftp-edts.hhs.texas.gov, port=22, filePath=./, credentialName=null), Send function unrecoverable exception for event: report&SEND&24981b1f-3a6c-43eb-ae10-8bb10f0aea56&false

We need to diagnose what happened here. 

## Acceptance Criteria

- Verify Texas got this file? If the did not, please resend
- Why does it say it succeeded but there was an exception? Update our logic on sending to capture this type of exception and properly mark it as a failure not a success
- What was the cause of the exception? Is it on our end or on their's? Write up the cause if it's on our end and what steps need to be addressed to make sure this doesn't happen again. Or fix it if the work required is small

**Comment by oslynn** [comment]
@MauriceReeves-usds @jimduff-usds @clediggins-usds.  After investigating, I found the issue was the RS report sending retry exception occurred during the sender is trying to handle retry.  To fix this, it will take a little time.  For the retry assault the limit, we need to handle it via manual upload as stated in the "How Retry works in ReportStream" documentation.

**Comment by Adrian-Brewster** [comment]
@MauriceReeves-usds to set up meeting with Cle and Jim to discuss

**Comment by Adrian-Brewster** [comment]
@clediggins-usds  and @jimduff-usds Please see the notes above.  @JGreenFearless Adding you to the ticket for visibility.

**Comment by brick-green-agile6** [comment]
> [1;31m19:51:11.635 [pool-2-thread-10888][188597] FATAL-ALERT gov.cdc.prime.router.azure.SendFunction - Success: sftp upload of CDCPRIME_11D2030855_20220516193504.hl7 to SFTPTransportType(host=sftp-edts.hhs.texas.gov, port=22, filePath=./, credentialName=null), Send function unrecoverable exception for event. Mo intervention required: report&SEND&c1d8c781-e8d0-4261-b408-25e53b2ed4dd&false

**Comment by sarahnw** [comment]
haven't seen this issue recur in a while. closing for now.
