### ISSUE TITLE
All in one health: Collect and communicate final data collection and point on error messages

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#4585]
## Problem Statement
As an organization, ReportStream wants to capture information on csv users' error messages before submitting files to ReportStream, ~45 to 60 days after an org is in production.

## Acceptance Criteria

- [x] Review metabase query on error messages

- [x] Summarize number and type of error messages

- [ ] Share as part of a slide in [CSV deck](https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Pilots/CSV%20Uploader/ReportStream%20CSV%20dataset%20and%20quality%20improvements.pptx?d=wde566704b7f34b2e9eaa332b8fe7cd0b&csf=1&web=1&e=cO7bDj)

- [x] Share as part of [research synthesis deck](https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B3883912A-317A-4E99-8A2E-187C105C02BF%7D&file=A1H%20Pilot%20Synthesis_1.27.22_Internal.pptx&action=edit&mobileredirect=true&cid=4ab41cf6-aeb5-40da-a752-0320ce73a8af) on all in one health

**Comment by rachelhanster** [comment]
@victorialb-usds: What is the final data point that needs to be gathered/synthesized for All in one health?

**Comment by victorialb-usds** [comment]
We wanted to look at the errors at 60 days once it is part of their routine. With A1H seems like there were some bumps when omicron happened. How could we get a metabase run of errors for them now Lori is gone?

**Comment by rachelhanster** [comment]
@victorialb-usds Got it. I can show you how to find this data in metabase. Let's figure out a time to screenshare.

**Comment by victorialb-usds** [comment]
Here is where I have done analysis of errors in excel. 
https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B4D355B15-2CA4-49C9-938A-DFDA7C813A00%7D&file=A1H_query_result_2022-02-07T15_14_32.751885Z%20-%20Copy.xlsx&action=default&mobileredirect=true&cid=408f26d1-d55d-492e-9419-770b500419dc

**Comment by victorialb-usds** [comment]
See slides 9 - 10.

**Comment by victorialb-usds** [comment]
Same as cohort 1 -[ the research deck](https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B3883912A-317A-4E99-8A2E-187C105C02BF%7D&file=A1H%20Pilot%20Synthesis_1.27.22_Internal.pptx&action=edit&mobileredirect=true&cid=4ab41cf6-aeb5-40da-a752-0320ce73a8af) is for you to use. I added what I thought would work in your deck @rachelhanster
