### ISSUE TITLE
Gather list of ReportStream users' contact info

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#4586]
## Problem Statement
ReportStream wants to gather user feedback via a survey. We need a comprehensive list of all current ReportStream users/POCs and their email addresses from the Onboarding and Operations team.

## Acceptance Criteria
- [x] required: A list of first name, last name, organization name, work email address
- [x] optional: role at org (if possible), any relevant notes/history (optional)
- [x] @Adrian-Brewster add local/county/territory/tribal to [directory](https://cdc-my.sharepoint.com/:x:/r/personal/mpz9_cdc_gov/_layouts/15/Doc.aspx?sourcedoc=%7Ba435b5bd-e042-4c58-a8c4-162b7b09a849%7D&action=editnew&wdPreviousSession=ced5336b-46b0-43a1-ab06-ccdea1ab7edb&wdNewAndOpenCt=1644964712441&wdo=4&wdOrigin=wacFileNew&wdTpl=blank&wdLcid=1033&wdPreviousCorrelation=bff75d55-bcda-445d-896c-b36f74f4c276&cid=fe5b7997-cc01-4463-9872-9961023a302a)

**Comment by rachelhanster** [comment]
@victorialb-usds Please review and revise acceptance criteria if needed

**Comment by victorialb-usds** [comment]
blocked by O+O -- https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4600

**Comment by victorialb-usds** [comment]
https://cdc-my.sharepoint.com/:x:/g/personal/mpz9_cdc_gov/Eb21NaRC4FhMqMQWK3sJqEkB_5NfSzhlNl6BaR6rOOjy6Q?e=4%3A4o2gq3&CID=B20D136D-A730-42E3-A45D-9A6D8A7CC4F5&wdLOR=cE38BA707-0565-436E-8FB8-D09BBE396E8A sent from Adrian 3/2/22 CC: @rachelhanster @BerniXiongA6

**Comment by victorialb-usds** [comment]
@Adrian-Brewster what do you think the ETA is for the local/county and territory and tribal contacts? Thanks! I am working on figuring out mailmerge for this effort - have you every done that before -- emailing all our contacts?

**Comment by BerniXiongA6** [comment]
hey @Adrian-Brewster just a heads up that I've put this ticket in your "Needs Analysis" pipeline. Today @victorialb-usds has updated us that she is in the middle of getting the surveymonkey tool approval and she's anticipating being able to send out the survey next week. Does O&O think the pending contacts will be added to the directory/spreadsheet? Thanks in advance!

**Comment by victorialb-usds** [comment]
Adrian updated the directory. we tabled but talked at a high level about where it would live/who would edit it. when we want to send out survey I will have him do a once over to make sure there is not anyone missing (e.g. an org that goes live between yesterday and when we send). he said that he has emailed from reportstream inbox and have not heard of it going to spam - so think we should send from there.
