### ISSUE TITLE
Display Information for each PHD/STLT Feed Displayed in the Submission History Details - expose aggregate numbers

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4590]
## Problem Statement
As a Sender, when I view submission history detailed page, I would like to see total number of records sent to a specific public health authority.

## Background

[Original Slack thread that flagged this](https://slack.com/archives/C02HJ43AE8Z/p1646071615220209?thread_ts=1645730346.019779&cid=C02HJ43AE8Z).

Currently, we are displaying the number of records that were sent to each feed for each PHD/STLT. However, there is no content that indicates total number of records to a PHD, and what this means in terms of complying with required reporting policy.
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/dcc207de-8c5e-4a32-b3a5-621ac7ae0e1c)

## Note
- Working design [in Figma](https://www.figma.com/proto/VrSkTA87t8PPeXPugQ0i8O/ReportStream?page-id=754%3A0&node-id=1142%3A829&viewport=298%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=1150%3A470)
- Focus on 2 columns in figma file: "organization" and "records"
- [slack thread on submissions endpoint ](https://slack.com/archives/C02HJ43AE8Z/p1646860737402509)

## Acceptance Criteria
- [ ] Design how the information will be presented in the UI (i.e. wireframes). See Note section above
- [ ] Implement the design
- [ ] date, time, and number of records per receiver (aggregate) are displayed

**Comment by drew-usds** [comment]
Started to mock this up -- [incomplete in Figma but we can work on it further](https://www.figma.com/proto/VrSkTA87t8PPeXPugQ0i8O/ReportStream?page-id=754%3A0&node-id=1142%3A829&viewport=298%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=1150%3A470).

**Comment by rachelhanster** [comment]
@drew-usds @inkandsound Closing this ticket for Experience team. I would recommend this be part of the design knowledge transfer with Simplereport regarding Uploader.
