### ISSUE TITLE
Add option for value sets to output null if the value set cardinality allows it

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#4591]
## Overview
In `FakeReport.kt` we have a method (`createFakeCodeValue`) that outputs value set choices based on the value set, but not every element that comes from a value set *requires* a value. Many of our coded elements actually have a cardinality of `ZERO OR ONE`, which means we should be okay to output a blank value. 

## Detail
For this ticket, update the `createFakeCodeValue` function to allow for blank values to be output for any coded element that has a cardinality of `ZERO OR ONE`, or allows for null.

## Acceptance Criteria
- Fields like `patient_tribal_citizenship` (for example) have blank values mixed in with coded values

**Comment by oslynn** [comment]
patient_tribal_citizenship has csvFields = patient_tribal_affiliation.  Therefore, patient_tribal_affiliation is csv column header.
