### ISSUE TITLE
Bump SSHJ to latest version - v0.32.0

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#4596]
## Introduction
SSHJ has incremented past a version that we currently use. Unfortunately, upgrading SSHJ has caused issues in the past, and rather than just trust the dependabot PR, we're going to make this a manual ticket and verify that all of the functionality we anticipate works after we upgrade.

**NOTE - This is very sensitive and therefore you need to be very deliberate about how we go about completing this work.**

## Details and Acceptance Criteria
- Upgrade `implementation("com.hierynomus:sshj:0.31.0")` to version `0.32.0`
- Add two receivers to IGNORE, for a PEM key and one for a Putty key
- Add the two receivers to the `end2end` test, verify that the new version of SSHJ does not affect their ability to receive files
- Add a specific public key auth test type to the `./prime test` suite that checks both the receivers created above
- Add the public key auth test to the top-level `./prime test` run so it is executed every time `./prime test` is run

**Comment by Adrian-Brewster** [comment]
Being put on hold.  Deprioritized for this sprint.
