### ISSUE TITLE
User Agent override for Sender PrimarySubmissionMethod

### ISSUE THREAD

**Issue by luis-pabon-tf** [CDCgov/prime-reportstream#4605]
**Is your feature request related to a problem? Please describe.**
PrimarySubmissionMethod is initially handled as part of the request body, even thought it may make more sense to be part of the header.

**Describe the solution you'd like**
Add header support for the field without breaking existing integrations.

**Comment by JGreenFearless** [comment]
@TurkeyFried Is this still something we need to address?
