### ISSUE TITLE
Washington File Delivery Failures

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#4611]
Both the positive and negative feed failed to deliver to Washington on Monday one time.

Positive: `15fa8db9-dc48-48d4-8be6-480555e212fc`
Negative: `4ecee671-0301-4a1a-94c2-def52254d6fe`

Both happened around 17.00 UTC, and the failure for both was a read timeout.

We need to ask Washington if they received those files and if they did not, send them to them. We can email them via encrypted email if they do need resent.

**Comment by anshulkumar-usds** [comment]
@MauriceReeves-usds WA did not receive the files and are requesting resubmissions via the usual PROD route of through secure email.

**Comment by MauriceReeves-usds** [comment]
I have the files pulled. I am ready to send it to them. @anshulkumar-usds who should I forward them to?

**Comment by MauriceReeves-usds** [comment]
Files were sent to Kim and Caroline. Moving to external review.

**Comment by anshulkumar-usds** [comment]
3/2: Clarified for WA that data Mo delivered was to address missing files, not accession numbers. Still waiting for WA to confirm acceptance.

**Comment by anshulkumar-usds** [comment]
3/3: From WA:
"I have checked the accessions from the files provided and we did receive those results successfully on 2/28/22 so I do not think we are missing any data."

Closing.
