### ISSUE TITLE
Illinois Window Size Timeout Delivery Failure

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#4612]
We had another window size timeout for Illinois on Monday at 13.09 UTC. We need to verify they received report `94cd10c0-bff7-48eb-b34a-899c8781d2d7`, and if they did not, we need to copy it over for them manually.

I don't see any other exceptions of this type, so this might be the last resend we need to do from this exception.

**Comment by anshulkumar-usds** [comment]
@MauriceReeves-usds `94cd10c0-bff7-48eb-b34a-899c8781d2d7` isn't showing up in COVID Metadata table as a report or a message. Is there somewhere else I should be looking at ?

**Comment by anshulkumar-usds** [comment]
3/1: Checking with IL.

**Comment by MauriceReeves-usds** [comment]
File has been sent. Moving to external review.

**Comment by Adrian-Brewster** [comment]
Closing ticket and will open a new one with any new occurrences.
