### ISSUE TITLE
Survey STLTs to understand their systems and capabilities

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4637]
ReportStream is connected to several STLTs, and we do not have a consolidated knowledge bank of how these entities behave on their side with respect to their back-end systems, capabilities, limitations, etc.

Therefore, we need to conduct a survey of our STLTs and ask them questions about their systems and capabilities. A recent example was RS learning that CA-DPH cannot handle UTF-8.

Some elements to consider starting with:
- Receiving interface engine
- surveillance system used
- additional non-standard quality filters like Patient ID required
- Result Status accepted
- UTF-8 or Std ASCII only, if ASCII only how do they want to receive extended ASCII, etc.

Next steps:
- Partner with @rhood23699, @brick-green-agile6, @MauriceReeves-usds to compile a list of questions
- Work with @victorialb-usds to design a survey
- Send out surveys and compile data in a shared format for program-wide reference

**Comment by anshulkumar-usds** [comment]
@MauriceReeves-usds @Adrian-Brewster @sarahnw Moving this up to Product Backlog. 
As a first step, O&O should meet internally to draft a list of survey questions. 
Next, work with Experience/Design to create a survey/email template to gather these responses.

cc: @brick-green-agile6 @rhood23699

**Comment by sarahnw** [comment]
Gathering input here https://nava.slack.com/archives/C025F5W5Q7L/p1649351405861059

**Comment by anshulkumar-usds** [comment]
@sarahnw I don't have access to the slack link you shared above. Could you please grant me access or share notes in our team folder?

**Comment by jakefishbein-navapbc** [comment]
@brandonnava I think this is something that would happen in the Qualtrics survey. I think @drew-usds or @victorialb-usds might be able to give context on this. adding @lizzieamanning in case she knows anything about existing efforts. I'm happy to work on this but want to make sure I'm not duplicating efforts that are in the works.
