### ISSUE TITLE
Create new gen2 storage account, copy pitestdatastorage files there

### ISSUE THREAD

**Issue by NatHillardUSDS** [CDCgov/prime-reportstream#4641]
**Description**
Due to various Microsoft bugs, we are unable to continue using the current `pitestdatastorage`. In devops sync yesterday we talked about the following as next steps:
* Create a new storage account identical to `pitestdatastorage` but with gen2 storage enabled, in both `-dev` and `-test`, managed by terraform
* Copy files over from `pitestdatastorage` storage account to the new storage account in `-test`. 

**Specific Requested resources**
* [new storage accounts in `dev` and `test` with latest appropriate naming conventions for each environment

**Existing Resources?**
`pitestdatastorage`

**Additional Context**
Notes from sync [here](https://docs.google.com/document/d/1E8-ZEIfSa0dg_xrKQ_5JQm7RuPO2vt8fBIzUcsZa4fU/edit#heading=h.sxrtxooyo3v4)

**Comment by JosiahSiegel** [comment]
Data lake storage account with hierarchical namespace created.
