### ISSUE TITLE
Indiana (IN) - Onboarding Operations

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4654]
The following items, generally in order, must be completed to successfully onboard a receiver to ReportStream:

* [ ] Added to organization.yml
* [ ] Added to organizations-local.yml
* [ ] Added to staging settings table
* [ ] Added to prod settings table
* [ ] Added at least one receiver
* [ ] Added OKTA group to download site
* [ ] Added customers to OKTA group for download site
* [ ] Is customer contact made?
* What doc format are we supporting for the receiver (HLV, CSV, other)? **(Add comment below)**
* What transport(s) are we supporting for the receiver (SFTP, other)? **(Add comment below)**
* [ ]  Got credentials?
* [ ] Tested ELR connection locally?
* [ ] Tested ELR connection from Azure?
* [ ] Has the receiver accessed the download site?
* [ ] Has the receiver been sent at least one test file?
* [ ] Has the receiver signed off on file formatting?
* [ ] Are there labs sending data?
* [ ] Has the receiver confirmed receipt of the data?
* [ ] Have the files processed successfully?
* [ ] Are we in production?
* [ ] Update customerStatus flag in production settings to active

**Comment by anshulkumar-usds** [comment]
Submitted in the intake form on 2/25:
The following information has been submitted:
State/Territory: Indiana
2 Letter Territory Code: IN 
Public Health Department Name: Indiana Department of Health
Primary Contact
   First Name: Irene
   Last Name: Jameson
   Phone: 317-233-7684
   Email: ijameson@isdh.in.gov
   Title: IT Project Manager (Office of Technology and Compliance)
Secondary Contact
   First Name: Kelly
   Last Name: White
   Phone: 317-233-7548
   Email: kewhite@isdh.in.gov
   Title: Epidemiologist Director (Epidemiology Resource Center)
Preferred Transport Protocol: SFTP
Preferred File Format:  HL7
How often should data be sent? Realtime 
Ask on Entry question data?  Yes
Additional Data Fields:
New Site Registration: I need new sites to be registered and can accept the standard process
What data do you require to be sent?
   Synthetic?  True
   Obfuscated Patient data?  True
   Real Patient Data?  False
   Other Custom Needs?  False
Local Jurisdiction Reporting:
Interest in other PRIME projects?
   Data Automation: True
   Simple Report: False

**Comment by anshulkumar-usds** [comment]
3/4: Kickoff scheduled for 3/10 at 10 AM EST

**Comment by anshulkumar-usds** [comment]
3/17: Checked with IN if they had any questions post kickoff

**Comment by anshulkumar-usds** [comment]
3/31: IN replied with the following to our onboarding questionnaire and additional attachment:

Section 1: Engineering   
•	PHA implementation guide -  we follow HL7 ELR  2.5.1 Implementation guide
•	Do you require a specific file name format – Yes, please, naming convention should be IDOH_CDCSR_MMDDYYYYHHMMSS.hl7 (files should have hl7 extension)
•	Do you accept HL7 2.5.1 – Yes
•	Sending protocol – SFTP
•	Accept batch messages -  do you mean to say, multiple ELRs in one HL7 file, if so, Yes, we can take batch messages, (of course, we need to test it out)
•	Is there a limit on the number of messages in batch – strictly, there is no number, but couple of hundred messages in one HL7 file is fine
•	Frequency – every two hours works fine

Section 2: HL7
•	Value for MSH-5 (MSH-5.1) is  IN-ELR
•	Value for MSH-6 (MSH-6.1) is IDOH
•	Value for MSH-4 (MSH-4.1 Please put own identifier name), MSH-4.2 -  XXXXXXXXXX (own CLIA), MSH-4.3 specific value - CLIA
•	Receive AOE questions – Yes
•	Suppress the QST flag in OBX-29 – Yes
•	Any other fields that are required – Please see the attached spreadsheet (IDOH_ELR_template_20220330.csv) for the required fields, so they won’t fail during processing in our system (of course, testing is to be done to ascertain this)
•	Specific values for MSH 21 -  PHLabReport-NoAck (MSH 21.1),  ELR_Receiver (MSH 21.2) , 2.16.840.1.113883.9.11 (MSH 21.3), ISO (MSH 21.4)

Section 3: SFTP
•	How to get SFTP credentials ? – I will work with our systems admin and approvals to setup the account and get the details once I have it
•	Do the credentials need to be rotated/do they expire  - No
•	Do you need to whitelist our IP addresses before we connect  - I do not know at this point, once we get to the testing phase and you drop in test messages, then we can confirm if any whitelisting is to be done if they don’t come through in SFTP
•	What file path do we need to write files on SFTP server ? -  Once SFTP account is created, then I will share the SFTP file path for the messages to be dropped off

Section 4: Data Quality Filters
•	(How) Do you want to receive OTC results ? – No

**Comment by anshulkumar-usds** [comment]
[https://app.zenhub.com/files/304423150/ded6d16c-624b-4602-a984-2bca9faa45f5/download](https://app.zenhub.com/files/304423150/ded6d16c-624b-4602-a984-2bca9faa45f5/download)

**Comment by Adrian-Brewster** [comment]
@greene858 Prioritizing this over Oklahoma since Oklahoma is dependent on REST API and Indiana is fine with sFTP

**Comment by anshulkumar-usds** [comment]
5/17: IN has not yet provided credentials to SFTP. Requesting and waiting.

**Comment by brick-green** [comment]
@oslynn We're in production with IN, right? Can this be closed?
