### ISSUE TITLE
Customer journey maps for proto-persona at lab facility and health clinic

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#4662]
## Problem statement
As an organization, ReportStream wants to meet and exceed users' expectation at all touchpoints of their data sharing experience. 

As a sender of data to ReportStream, I want to be aware, consider, decide, onboard, use, and advocate product(s). 

ReportStream needs customer journey maps to help us gain an understanding of how the customer experience develops over time. Journey maps provide a common reference that allows team members to center on the experience of the user.

## What you need to know

- [Existing maps in mural](https://app.mural.co/t/primedatainput6410/r/1634134576762?folderUuid=9e552663-1ea2-4e60-9af8-1b13b30672aa)
- [Customer journey map example from Rachel](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1646247730614/554e1ef2f179ad7322c1994222b98c28627dbdff?sender=u8081ec802748acf27d0d6445)

## Later
**Team alignment and issue creation**

- [ ] ~~Develop actionable recommendations (product & design)~~
- [ ] ~~Create tickets (All team)~~

## Acceptance criteria
- Limit scope to CSV senders in csv experiment
**Create two customer journey maps**
- [x] Lab facility
- [x] Health clinic
- [ ] ~~Discuss opportunities (product & design)~~
- [x] Share maps with the team

**Comment by drew-usds** [comment]
Meeting with @victorialb-usds 3/21 to incorporate current research findings.

**Comment by victorialb-usds** [comment]
Meeting with designers 3/24 to flesh out user groups: labs v point of care clinic @drew-usds

**Comment by drew-usds** [comment]
In-progress map his here: https://app.mural.co/invitation/mural/primedatainput6410/1647893436382?sender=ud6a3555dd1821b626a2b3726&key=e6406195-2b0d-43dd-bffb-23101f53b325

**Comment by rachelhanster** [comment]
Timeboxing this to sprint that ends on 2022.04.12. cc @HeatherRienks

**Comment by HeatherRienks** [comment]
@drew-usds  & @victorialb-usds - any updates on this? Thanks!

**Comment by HeatherRienks** [comment]
Keeping this ticket in Sprint 40 for 1 day, then will pass along to SR team.
cc: @drew-usds & @rachelhanster @RakshindaAslam

**Comment by HeatherRienks** [comment]
Team - are we ready to pass along to SimpleReport team? @rachelhanster @drew-usds & @victorialb-usds 

cc: @RakshindaAslam

**Comment by victorialb-usds** [comment]
@drew-usds if you want to do final time on this to wrap and perhaps have meeting with Rick hood where I can ask questions about their process there is likely information that he holds that would be good to document before he goes. I believe O and O also have a flow chart that Sarah made that would be good to have. 

@rachelhanster do you have access to the process chart sarah made and could you add the link here?

**Comment by rachelhanster** [comment]
@sarahnw can you please share the Ops team's process chart, specifically focused on Uploader users? 
cc @victorialb-usds @RakshindaAslam

**Comment by drew-usds** [comment]
Will update links here later today!

**Comment by rachelhanster** [comment]
Hey @drew-usds Where can I find the final artifact to review?

**Comment by drew-usds** [comment]
@rachelhanster Did a last look at these with Rick Hood before his departure and made some small edits based on his feedback.

[Final map ready for handoff.](https://app.mural.co/invitation/mural/primedatainput6410/1647893436382?sender=ud6a3555dd1821b626a2b3726&key=e6406195-2b0d-43dd-bffb-23101f53b325)
