### ISSUE TITLE
TX - Incorrect datatype in OBX-2 and OBX-5, and missing SNOMED codes

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4667]
On 3/1/22, TX reported the following:

1.	Some files are still failing due to incorrect datatype for 65222-2^Date and time of symptom onset^LN. If the date and time of symptom onset is unknown, the expected datatype in OBX-2 is CWE/CE and OBX 5 | UNK^Unknown^NULLFL| 
2.	Some messages are missing SNOMED codes for the pregnancy status. OBX|7|CE|82810-3^Pregnancy status^LN||^^SNM^UNK^UNK^L
Please populate the field
Some example accession  nos. for files that have failed for your review.
```
•	11441219-a505-42d3-9395-17569bea4753
•	7c3defeb-efd9-41ab-84ea-4fd0b7cda73c
•	32ed7987-e75e-45d4-8046-fb7c11f6467c
•	a5ca2f1d-d8f6-4dab-9f16-f89afb63a448
•	14b17dfd-2a2e-404a-a189-1097c7d91cbb
•	f57ffc82-d2c4-4567-a55d-415f3c5b76d9
•	ca8b0ca5-284e-471b-bd63-a419ebb505d1
•	9af81264-a36e-44b4-91de-259b68ece6ee
•	87051e53-bec9-4fb6-a53e-a30ecc57aa53
•	7c81ae5e-1e95-4972-9fa4-24bbfe1f4b84
```

**Comment by anshulkumar-usds** [comment]
@MauriceReeves-usds I noticed TX raised this issue and you replied to them. Wasn't sure if this was addressed already. Ticketing for now.

**Comment by MauriceReeves-usds** [comment]
@oslynn in the `setAOE` method in the HL7Serializer, check the date value and see if it's empty string. if it is, change the valueType variable to CWE and set the value you output to UNKNOWN as Texas notes above. Let me know if that makes sense.

**Comment by oslynn** [comment]
Per Mo's comment, If the illness onset date is blank, then it should be set to UNK:  OBX-5 would look like:
UNK^Unknown^NULLFL
and OBX-2's data type field would be CWE instead of DT.

**Comment by Adrian-Brewster** [comment]
@MauriceReeves-usds will take a look at PR today

**Comment by oslynn** [comment]
It is done and merged by Mo.  Therefore, I closed it.
