### ISSUE TITLE
Click-Up Internal Pilot

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4668]

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/4668?planning-poker) with ZenHub @brick-green-agile6 @sarahnw

**Comment by anshulkumar-usds** [comment]
Looks like we might get access to smartsheets after all.

**Comment by Adrian-Brewster** [comment]
Dreams DO come true! @anshulkumar-usds

**Comment by sarahnw** [comment]
we're using smartsheets, so closing this.
