### ISSUE TITLE
CSV sender: submission detail page edits

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#4672]
## Problem statement

Edits to the details/show page for a given CSV file uploaded.

## What you need to know

See last comment in #4271

>### Report detail
>[Report detail page](https://www.figma.com/proto/VrSkTA87t8PPeXPugQ0i8O/ReportStream?page-id=754%3A0&node-id=1142%3A829&viewport=298%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=1150%3A470)
>_Notes_
>- Add [USWDS breadcrumb](https://designsystem.digital.gov/components/breadcrumb/) to take you back to `submission index`
>- Turn jurisdiction sent-to details into table

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by rachelhanster** [comment]
@drew-usds
What design changes are needed to csv' submission history?
This ticket's content is the same as API sender. Is the intention for csv/API senders to have the same submission history designs?

**Comment by drew-usds** [comment]
> @drew-usds What design changes are needed to csv' submission history? This ticket's content is the same as API sender. Is the intention for csv/API senders to have the same submission history designs?

@rachelhanster Since API results come in line-by-line, we'll have to aggregate things differently. In our submission history sessions with these users, they still wanted to be able to see each thing submitted since that is how they're seeing it on their end. However they're potentially sending thousands of results per day, so their index would end up thousands of pages long in a matter of days. Based on that, things may look similar to a CSV user, but drilled down an extra level. Maybe something like this for an API user:

**API submission index**
- Aggregate all submissions per day under a single table row that shows top level info like date, number of results etc
- Each day is a new row
- User clicks through to see details about everything submitted on a given day

**API submission detail**
- Aggregated by day
- Shows each submission for that day in a table with relevant info (ID, pos/neg, etc). Will probably need to be grouped in some way (testing location? where they were sent to?). Will also need to keep the top-level detail available like we outlined for CSV users -- total results, where they went (and what feed).

**Comment by rachelhanster** [comment]
@drew-usds Is this ticket still applicable given 1) Uploader's move to SimpleReport; and 2) our team's working on submission history enhancements, only if these enhancements are applicable to API senders?

**Comment by rachelhanster** [comment]
Closing ticket due to uploader's move
