### ISSUE TITLE
Prospective user's identity verification

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#4675]
## Problem Statement 
As a prospective user, I'm unable to complete onboarding to use ReportStream in production unless my identification has been verified.

## Describe the solution you'd like
When necessary, a prospective user is able to easily provide the necessary document(s) to verify their identity.

## Describe alternatives you've considered
Prospective users who find out about ReportStream independently:
Solution 1: Video session with a ReportStream admin
Solution 2: Outsource verification work to a third-party organization

Prospective users who discover ReportStream via a referral from a public health authority
Solution 1: Channel referral tool for public health authorities to easily make a referral and for ReportStream to automate the referral process

**Comment by victorialb-usds** [comment]
UX research on this topic 3.2.22 COVID Clinic check in, 
"Trying to get into simple report was a bit of a nightmare. The one girl was help me. They had to call us to verify our ID they asked me 3 questions about me, I guess I don’t know me very well. I had to show them my ID, I am putting up to screen. The one girl was asked for birth certificate. That was really difficult. Felt like I was giving too much information. This was for my company .. was not sure if was supposed to give all personal information."
