### ISSUE TITLE
API sender: submission detail page edits

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#4678]
## Problem statement

Edits to the details/show page based on feedback from API senders

## What you need to know

See last comment in #4271

>### Report detail
>[Report detail page](https://www.figma.com/proto/VrSkTA87t8PPeXPugQ0i8O/ReportStream?page-id=754%3A0&node-id=1142%3A829&viewport=298%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=1150%3A470)
>_Notes_
>- Add [USWDS breadcrumb](https://designsystem.digital.gov/components/breadcrumb/) to take you back to `submission index`
>- Turn jurisdiction sent-to details into table

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by kevinhaube** [comment]
@drew-usds Let us know if/when you have designs and @CnoteNava can handle prioritization of the edits!

**Comment by chris-kuryak** [comment]
Closing due to being old/stale. Will reference in new epic for research purposes.
Closing by committee @drew-usds @jillian-hammer @lizzieamanning @audreykwr
