### ISSUE TITLE
API sender: Submission history page edits

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#4679]
## Problem statement

Based on the needs of API senders, may need to edit how we display their submission history.

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
Closing due to being old/stale. Will reference in new epic for research purposes.
Closing by committee @drew-usds @jillian-hammer @lizzieamanning @audreykwr
