### ISSUE TITLE
Bug:   We do not accept  MSH-2 value of ^~\&#

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#4694]
Bug:   We do not accept 
`MSH|^~\&#|`
but it is in fact valid MSH-2
(Right now we accept `MSH|^~\&|`)

That is, the hash is legal but we're still saying its illegal.

### Acceptance Crit

- An HL7 message with a hash in the MSH-2 is successful by ingestion into ReportStream
- Unit tested

 Needed for HCA.

**Comment by jimduff-usds** [comment]
@MauriceReeves-usds proposes a "preprocessor":

I think the ideal way to handle this is to add the ability to do pre-processing on sender submissions.  There are other use cases where you'd want to scrub data coming from a sender, for example, the unicode character from STRAC that was difficult for PA to handle.

There are more instances of just "remove the hash" that we will experience into the future, and just patching the serializer is not always going to sustain us. Having a preprocessor that can handle those kinds of cases gives us additional flexibility, especially if we create them as a series of mappers that can run on the entire message body we can control them from settings.

TBD whether this should be done as a feature in the new FHIR pipeline, the old pipeline, or both.  FYI @whytheplatypus

**Comment by jbiskie** [comment]
Latest sender using this is Nova Labnetics (LIMS ABC).

**Comment by carlosfelix2** [comment]
OBE
