### ISSUE TITLE
Set up mailmerge for CX survey

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#4703]
## Problem statement
As an organization, ReportStream needs a way to send referral/customer survey to people at ~50 organizations. 

## What you need to know
- Option 1: use outlook email, bcc recipient
- Option 2: use outlook email + spreadsheet, send individual message to a single recipient

Have access to O and O [directory ](https://cdc-my.sharepoint.com/:x:/g/personal/mpz9_cdc_gov/Eb21NaRC4FhMqMQWK3sJqEkB2qEOo_rg0On6FsA2QVhEwQ?email=tcq5%40cdc.gov&e=4%3AFLVIaU&CID=860b427e-68da-7f11-4368-304422bef3f8)of contact that is almost up to date. 

## Acceptance criteria

- [x] research how to do mail merge
- [x] Excel template to copy of emails to be sent to and format excel (so this process is easy to repeat)
- [x] Paste draft email so it is ready to go once we get the greenlight

## To do

- [x] research how to do mail merge
- [x] update acceptance criteria depending on option

**Comment by rachelhanster** [comment]
@victorialb-usds Is this still applicable? If no longer needed, please close.

**Comment by victorialb-usds** [comment]
We decided to send from rs inbox because the 
- time to mail merge did not seem worth it for this round - went with generic "valued report stream user"
- did not send directly from survey monkey b/c concern would land in the spam folders
- only sending to 60 orgs at this point
