### ISSUE TITLE
CSV upload pilot participant not able to view submission history

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#4707]
**Describe the bug**
CSV Upload Pilot sender EliteMed Labs is not able to view their submission history. ReportStream team members are able to view submission history in production. 

While Victoria was doing a check in call with user they tried to show me but when they clicked on submission it was not loading. Later they followed up with @rhood23699 via email to ask about this. 

**Impact**
User needs this to meet requirements - needed before their next CLIA, CPA or Joint Commission inspection. 

It is not only frustrating for the user, but they must have evidence of data reporting before their next CLIA, CAP or Joint Commission inspection.

Attn: @rachelhanster @BerniXiongA6 
@drew-usds @bgantick

**Comment by rhood23699** [comment]
@victorialb-usds @BerniXiongA6 @drew-usds @bgantick It is not only frustrating for them, but they must have this before their next CLIA, CAP or Joint Commission inspection.

**Comment by rachelhanster** [comment]
@rhood23699 @victorialb-usds I am able to view this org's submission history. When is the last date that the org successfully uploaded a file?

**Comment by victorialb-usds** [comment]
I checked it too and could see it as well. @rachelhanster I can see on the website it looks like 3/9.

**Comment by rachelhanster** [comment]
Latest[ slack thread](https://slack.com/archives/C02HJ43AE8Z/p1647280163357259) on this topic

**Comment by kevinhaube** [comment]
![Screen Shot 2022-03-16 at 10.13.14 AM.png](https://images.zenhubusercontent.com/611a907ec3e013d0e33e58a7/a9b0538b-fd31-4ed6-8769-bd1fc718dfc9)
This looks to be the main issue: the organization does not exist in the settings database for production.
