### ISSUE TITLE
NV - Data Quality Issues

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4710]
NV/Inductive wrote to RS on 3/9 with the following data quality issues that need addressing before moving NV to prod:

1. **PID-5 (patient name)** - PID-5.7 is currently populated. Please do NOT populate the PID-5.7 (Patient Name indicator), as the NBS only accepts certain codes, and the messages will fail if the Indicator is incorrect.

2. **PID-22 (patient ethnicity)** - PID-22.3 is currently using the HL70189 table. Instead please use the CDCREC table. Accepted codes are in the CDCREC table: https://phinvads.cdc.gov/vads/ViewValueSet.action?id=35D34BBC-617F-DD11-B38D-00188B398520. Use the NULLFLAVOR table if “Unknown,” i.e., `|UNK^Unknown^NULLFL|`   https://phinvads.cdc.gov/vads/ViewValueSet.action?id=A0D34BBC-617F-DD11-B38D-00188B398520. Can send local codes if cannot send CDCREC codes. Can send both coded and local codes, but please send coded first

3. **ORC-22 (ordering provider)** - Invalid value format received in the file. Currently, ORC-12.1 is populated while ORC-12.2-.3 is blank. 

4. **ORC-12.1 (Ordering Provider ID)** is NOT required, please DO NOT send if possible. The database stores ORC-12.1 which can cause issues with matching provider IDs.
Please include values for ORC-12.2 and ORC-12.3: 
`ORC-12.2 (Ordering Provider Last Name)`
`ORC-12.3 (Ordering Provider First Name)`
Please put “Unknown” if not available, i.e. |^Unknown^Unknown|

5. **OBR-16 (ordering provider)** Currently, OBR-16.1 is populated while OBR-16.2-.3 is blank. 
ORC-16.1 (Ordering Provider ID) is NOT required, please DO NOT send if possible.
Please include values for OBR-16.2 and OBR-16.3: 
`OBR-16.2 (Ordering Provider Last Name)`
`OBR-16.3 (Ordering Provider First Name)`
Please put “Unknown” if not available, i.e. |^Unknown^Unknown|

**Comment by oslynn** [comment]
After the master is deployed next week.  I will update the setting in prod and staging.

**Comment by oslynn** [comment]
Merged to master, updated database settings for prod and staging.

**Comment by oslynn** [comment]
@Adrian-Brewster and @MauriceReeves-usds OBR-16-1 is still there.  It is NOT dropped.  I will suppress it from PROD and STAGING now.
