### ISSUE TITLE
CSV pilot - post research participant recruitment

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#4713]
## Overview

**Post-intervention:** Send out communication to CSV pilot partners to schedule calls to assess impact of the intervention by asking similar questions to baseline.  

## To do

- [x] Write and send out outreach email to all CSV pilot partners
- [x] Create ScheduleOnce calendar

**Comment by victorialb-usds** [comment]
wonder if we might do these sessions with SR folks as optional attendees

**Comment by HeatherRienks** [comment]
@victorialb-usds - I will add this work to the sprint KO slide for our next sprint (40, which starts on 4/13/22).

cc: @rachelhanster

**Comment by victorialb-usds** [comment]
I created my schedule once calendar so will be able to send this out late next week/early the week following.

**Comment by victorialb-usds** [comment]
See the Pre-Post Excel [here](https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B431D9FDE-C408-43E7-B643-E1D30652155C%7D&file=CSV%20pilot%20cohort%201_Pre%20Post%20Data.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1). 
**List of places to reach out to to do close out calls with.**
Youth Clinic
Core Bio Labs
COVID CLINIC
EliteMed
Lemoore Naval Health Clinic
SDI
SourceBioscience
StemExpress
Warrior DX

**Comment by victorialb-usds** [comment]
[Link to fac guide]([url](url))

**Comment by HeatherRienks** [comment]
@victorialb-usds - the link to Fac Guide is not working for me. Not sure if anyone else has the same issue. 
Do you mind reposting/ Thx!

**Comment by victorialb-usds** [comment]
@HeatherRienks I re linked and also the [email](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B6B2D0CD8-9AF2-42C8-A187-23A274151C2A%7D&file=Scheduling%20Final%20Call%20email.docx&action=default&mobileredirect=true)

**Comment by HeatherRienks** [comment]
@victorialb-usds -thanks - it works!
