### ISSUE TITLE
Update content on API Programmer's Guide (version 2.2) to include NIH at-home testing standards

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#4723]
## Problem statement
- As a ReportStream API user, I want to have instructions on how to submit data reporting for at-home test results.

## What you need to know
This ticket came out of [Rick Hawes' Epic # 4598](https://app.zenhub.com/workspaces/prime-reportstream-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/4598).

**SUMMARY OF TICKET # 4598 as it pertains to Experience Team:**
- Per Rick Hawes: The NIH has developed an HL7 profile of self-administered tests. This profile is being balloted by HL7 now and is likely to be accepted as a standard HL7 profile soon. NIH is meeting with ReportStream senders as well to advocate their standards. ReportStream should have comprehensive support for the NIH standard.
- O&O team and Experience team will cross-collab on updating the Onboarding changes to support the NIH standard: 1) Documenting ReportStream's support for at-home testing on the top-level of the public website, 2) Referencing the NIH website in our programmer's guide documentation
- [Original Slack thread](https://agilesix.slack.com/archives/C02HJ43AE8Z/p1646334329680559?thread_ts=1646333830.737329&cid=C02HJ43AE8Z)
- [Slack thread with proposed Ask from Rick Hawes](https://agilesix.slack.com/archives/C02HJ43AE8Z/p1646938806445769)

**BLOCKER:**
- O&O team updates the sender onboarding documentation and programmer's guide to include NIH at-home test standards and sends updated documentation and guide to Exp. Team to revise content for public-facing audience.

## Acceptance criteria
- [x] Update [current API programmer's guide](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/3.%20Instructional%20Design%20Projects/ReportStream%20API%20Programmer%20Guide/FINAL-ReportStream-Programmers-Guide-v2.0.docx?d=w335fe0c2408b4e38a0152ea1c0c8fc1c&csf=1&web=1&e=M3ddt9) to version 2.1 (with NIH standards guidance)
- [x] Guidance speaks to the ReportStream API user
- [x] Saved as a styled and formatted user-facing Word document
- [x] Adherent to [ReportStream content style guide](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Content%20Style%20Guide/ReportStream%20content%20style%20guide.docx?d=webd8f377528c4175b0acb0fbfd6c5866&csf=1&web=1&e=ObGSuA)

## To do
- [ ] Content review of O&O team's revisions to API programmer's guide (typically 2-3 passes between Joel/O&O and Berni/Exp.)
- [ ] Formatting and styling of version 2.2 after all revisions approved by O&O (Joel Biskie)
- [ ] Share API programmer's guide v2.2 with UI to stage for deployment (keep this bullet point - [see # 4874](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4874) for UI staging task)

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 Note for BX: create new ticket for UI (see AC above for info)

**Comment by BerniXiongA6** [comment]
@rachelhanster @HeatherRienks The [O&O team said](https://slack.com/archives/C024MGSJZ38/p1648656142593549) they won't prioritize the schema updates to include NIH standards for another 2-3 sprints from now. I'm going to place this ticket back into Product Backlog.

**Comment by HeatherRienks** [comment]
@jbiskie - is this something that you will be able to help us with during this sprint? 

cc: @BerniXiongA6

**Comment by HeatherRienks** [comment]
Spoke w/ @jbiskie and this ticket is being worked on. O&O work will be in this ticket: #5377.

**Comment by BerniXiongA6** [comment]
Updated 5/12/2022: Per @jbiskie the O&O (engineering) content will be done and ready for me to review by mid- next week (5/18/2022). This ticket should then be able to pull into the sprint after that time. I'll keep an eye on [O&O's # 5377](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5377) in the meantime. cc: @RakshindaAslam @HeatherRienks

**Comment by BerniXiongA6** [comment]
Updated 5/19/2022: Updated programmer's guide is ready per @jbiskie ! I'll be revising content for v2.2 this coming sprint. cc: @RakshindaAslam @HeatherRienks

**Comment by BerniXiongA6** [comment]
Updates 6/6/2022: [Final Version 2.2](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/3.%20Instructional%20Design%20Projects/ReportStream%20API%20Programmer%20Guide/Version%202.2/FINAL%20-%20ReportStream%20API%20Programmer%20Guide%20v2.2.docx?d=w45034ec803a8466ba5f5e78066e323e6&csf=1&web=1&e=Yeg393) is ready for staging!
