### ISSUE TITLE
Add Link for API Programmer's Guide v2.0 onto ReportStream website

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#4724]
## Problem statement

Sender: As an API user, I want to have the most current copy of the API Programmer's Guide so I can correctly submit data through ReportStream.

ReportStream: We want to make the API Programmer's Guide available on the website so that email exchange is not necessary and so that end users always have access to the most up-to-date guidance.

## What you need to know

- [Final copy of ReportStream API Programmer's Guide Version 2.0](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/3.%20Instructional%20Design%20Projects/ReportStream%20API%20Programmer%20Guide/FINAL-ReportStream-Programmers-Guide-v2.0.docx?d=w335fe0c2408b4e38a0152ea1c0c8fc1c&csf=1&web=1&e=AaUxC1)

## Acceptance criteria

- [x] Add a link to the API Programmer's Guide version 2.0 on ReportStream website's Sender Overview page (to replace v1.0 link)

## To do

- [x] Remove v1 docx from `/prime-router/docs`
- [x] Add v2 docx at `/prime-router/docs`
- [x] Create public pdf version to link to
- [x] Add link to `/getting-started/testing-facilities/overview`

**Comment by BerniXiongA6** [comment]
cc: @drew-usds @kevinhaube now that Programmer's Guide version 2.0 is finalized, this ticket is for linking up the new version on RS website.

**Comment by drew-usds** [comment]
@bgantick this is ready for review in PR [#4817](https://github.com/CDCgov/prime-reportstream/pull/4817)

**Comment by BerniXiongA6** [comment]
Per @bgantick v2.0 should go live with Tuesday's (3/29/2022) deployment.

**Comment by drew-usds** [comment]
Merged in #4817, should be out with tomorrow's deploy.
