### ISSUE TITLE
Quantgene - CSV Sender Onboarding

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#4732]
## Sender Info:
- Sender/Company Name: Quantgene in CA
- Type of Sender: Commercial Laboratory
- RS sender_id: quantgene-ca

## Initial Interest & Follow Up
- [x] Document the date & time the Sender expressed interest. - 3/9/2022
- [x] Send Std Kickoff email.  This includes:

         - Links to TOS & TOS Registration
                 - https://reportstream.cdc.gov/terms-of-service
                 - https://reportstream.cdc.gov/sign-tos 
         - Links to the CSV upload guide and CSV schema documentation
                 - https://reportstream.cdc.gov/getting-started/testing-facilities/overview
         - Provide an option to have a Kickoff call to review these documents and answer any questions.
- [ ] Schedule Kickoff / Q&A meetings at the Senders request.
- [ ] Received TOS.

## Sender Setup - Create OKTA group & OKTA account
- [x] Define the RS sender_id  --  quantgene-ca
- [x] Create an OKTA group for the sender_id
- [x] Create an OKTA account using the RS Registration information.
- [x] Verify OKTA account registration by the Sender.

## Sender Setup - Create Sender Settings for Staging & PROD
- [x] Locally, create and test Settings in organizations.yaml
- [x] Create the Staging & Production YAML settings files

## Testing - Prod/Test Internal
- [x]  Move all RS development to Staging & PROD.
- [x] Make settings change to block results to the STLT, or send all results to the STLT's Test Feed.
- [ ] Validate Production data and make all necessary RS changes.  Iterate through testing until validation is complete.

## Testing - Prod/Test External (if required by the STLT)
- [ ] Contact the STLT to setup testing with Production data in their Production environment.
- [ ] Verify which Feed the STLT wants to receive the results.  Make settings changes as-needed and deploy to PROD. 
- [ ] Work directly with the STLT to complete Integrated Testing and gain approval to move into Production.

## Implementation - Plan & Schedule GO LIVE
- [ ] Change setting "customerStatus:" to active from testing.
- [ ] Contact RS Pipeline Team to turn on HHSProtect reporting.
- [ ] Determine if there is a backlog of results.  If so, contact the STLT to determine what results are needed.  Example, in at one STLT, if a Sender has reported positives only to the STLT, then the STLT wants all COVID (positive & negative) since the Sender started testing.
- [ ] Coordinate and schedule a start date for daily results and backlog results between the STLT and the Sender.

## Implementation - GO LIVE and Post LIVE Review
- [ ]  Monitor daily uploads for errors and contact Sender if results need to be corrected and resent.  Monitoring will typically be 1 week in duration unless issue are found.

**Comment by rhood23699** [comment]
3/11/2022 Completed Sender Setup.  Need TOS.

**Comment by rhood23699** [comment]
3/15/22 Adrian asked for an update.  They responded that it would take their I/T about a month to create the CSV file.  They stated that they will contact us when they are ready to test.

**Comment by rhood23699** [comment]
Moved to the Icebox pending notification that they are ready to start.

**Comment by sarahnw** [comment]
@Adrian-Brewster can we close this?

**Comment by sarahnw** [comment]
closing. csv is handled by SR now.
