### ISSUE TITLE
CA - OBX-23.1 and PID-5 need to be truncated to HL7 specification

### ISSUE THREAD

**Issue by brick-green-agile6** [CDCgov/prime-reportstream#4733]
## Problem statement

PID-5.3 and OBX-23.1 need to be truncated

3/08/22
Component size restriction exceeded in segment 6:OBX.  Field 23, repetition 1, component 1 is larger than data structure 2.5.1CA:XON permits it to be.
Jerold Phelps Commun^CDPH000085^CLIA
College of the Canyo^CDPH000085^CLIA
Konocti DO Baseball^CDPH000077^CLIA
 
`92d0064d-66f1-4237-9fbe-d4708e877378`
`e3cd65bb-9881-4487-b5f4-2a05f67329fd`
`6beed36b-e35b-417e-a1fb-1d74ba93f1b9`
 
3/07/22
Component size restriction exceeded in segment 6:OBX.  Field 23, repetition 1, component 1 is larger than data structure 2.5.1CA:XON permits it to be.
Component size restriction exceeded in segment 3:PID.  Field 5, repetition 1, component 3 is larger than data structure 2.5.1CA:XPN permits it to be.
College of the Canyo^CDPH000085^CLIA
Jerold Phelps Commun^CDPH000085^CLIA
CCC College of the C^CDPH000085^CLIA
ERUSD by Pico Care^CDPH000085^CLIA
and more

`32cc1ee5-5c27-4bff-a549-2ec66977856e`
`496c7c11-cd03-4e17-af61-89facce6c8a1`
`2387b5af-f60c-4881-a39c-dcf1359623f5`
`c2d05360-d5b9-47ae-8a98-532a4a1df1d6`

**Comment by brick-green-agile6** [comment]
Need to request additional examples of PID-5.3 exceeding the length limit. The examples provided only showed the OBX-23.1 length.

CA originally requested that OBX-23.10 be appended to OBX-23.1. We are currently truncating OBX-23.1 but then we are appending 23.10 so the field expands to exceed the threshold. Since that was a customization for CA I don't want to truncate out important data. So I am going to ask CA what they want to do.

**Comment by brick-green-agile6** [comment]
going to update CA settings to to truncate PID-5.3

**Comment by Adrian-Brewster** [comment]
Moving back to in progress for resends.

**Comment by brick-green-agile6** [comment]
made a request to Tim for SR to resend 5 results:

```
b600b9a0-164d-46c8-96bf-27b18bc5e30b
043ec95e-88ed-4ada-a467-32d0f8ec1afc
1db13264-e57b-4be2-9585-1b661ba8353c
fcb9492c-78a3-4426-8195-4dc6a77ee64e
c5e3cc4f-5fdc-4ecf-a34d-4c0ac7791508
```

**Comment by brick-green-agile6** [comment]
CA said this was fine
