### ISSUE TITLE
[SPIKE] Investigate why when Okta login expires, it still appears you're logged in (in some cases)

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#4738]
Steps:
1. Continue using site for longer than the Okta login expiration timer (feels like 60 minute?)
Result: site breaks as API requests just start failing so app breaks. Link to log out doesn't work, clicking on any nav doesn't work.
Work-around: user has to go to root site again and/or reload? They then KNOW to click log out, otherwise it remains broken!

Theory: The server-side isn't telling use the tokens are expired, it's just giving API errors. The client can't tell the difference between server generic errors (e.g. something is failing) and errors when the bearer has expired.

We haven't noticed, because _idle_ timeouts will redirect to logout page. But okta times out even while using the site. (I think there's a setting to auto-refresh token, but I'm not sure if it's set. Maybe it's only on OktaPreview?

The API response is 503 with a body
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>CDC Test Page</title>
  <link rel="stylesheet" href="/apology_files/style.css">
</head>
<body>
<h1>Centers for Disease Control and Prevention</h1>
<h2>Test Page</h2>
<p>This is a test page for prime.cdc.gov.</p>
<p>This page will appear if an error or timeout occurs at origin.</p>
<p><span>Reference ID: </span></p>
</body></html>
```

**Comment by bgantick** [comment]
Potential fixes: 
- adjust the timeout threshold
- handle the error (503) better on the RS end (route to logout, and/or throw a better error code)

**Comment by kevinhaube** [comment]
Possibly of interest: Okta's React library has a `useOktaAuth()` hook that I believe is their source of truth for your auth. We, however, are accessing this as a stored session variable which wouldn't be updated when a refresh is necessary.

**Comment by HeatherRienks** [comment]
Closing for now. Old issue. Not sure if it is scope anymore. New issue will arise naturally if it is still needed.
