### ISSUE TITLE
PA - Send failures from 3/11 - 3/12

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4754]
The following failures were observed for PA on 3/14. Preliminary reasons indicate issue is related to password change from 3/11. Something about the way it got saved in the vault didn't parse correctly causing it to fail when it tried to pull the credentials. 

**Resubmissions are needed.**

![PA Send Failures.PNG](https://images.zenhubusercontent.com/607d9d4a591b7cc0bb55c82e/9536bf7b-4f14-40af-b7c5-7b8d5733795a)

**Comment by Adrian-Brewster** [comment]
@MauriceReeves-usds has this been completed?

**Comment by anshulkumar-usds** [comment]
@MauriceReeves-usds is this still open?

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/4754?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS
