### ISSUE TITLE
Create USWDS sortable table component

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#4773]
## Problem statement

As a user, I'd like to be able to sort tables of data by date/etc. 

This came up specifically with users when talking about submission history, but would apply to any table in the app.

~~Will this be fixed by #2787?~~

## What you need to know

While working on submission history, Kevin H noted that there wasn't a current Truss/USWDS component for sortable tables.

[USWDS sortable table rows documentation.](https://designsystem.digital.gov/components/table/#sortable-table-rows)

## Acceptance criteria

- [ ] Component is on our own library, not Truss
- [ ] Has tests
- [ ] ...

## To do

- [ ] ...

**Comment by BerniXiongA6** [comment]
Update from @drew-usds : We should hold on refining this, the upgrade to 2.3.0 might very well fix the problem statement.




Drew Gardner  7 minutes ago
If we can prioritize that upgrade, in general it'll help things along as well

Berni Xiong  < 1 minute ago
Thanks @drew.gardner! I'll update the ticket with these comments.

**Comment by drew-usds** [comment]
@kevinhaube USWDS recs for accessibility here are better than I remember (https://designsystem.digital.gov/components/table/#accessibility-table). The big thing to include here is the `aria-live` region -- this might actually be a different ticket as we tackle some overall accessibility debt
