### ISSUE TITLE
Explore tooling for publishing a FHIR Profile

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#4774]
AC:
- a tool for authoring and publishing a FHIR Profile is identified.
- documentation on how to run / use it is written or found and added to the `docs/playbooks` directory
- a quick demo of at the end of sprint (or earlier)

See also #4212

Potentially useful links:
https://build.fhir.org/profiling.html
https://build.fhir.org/downloads.html (IG Publisher in particular)
https://confluence.hl7.org/display/FHIR/IG+Publisher+Documentation
https://fire.ly/products/forge/
https://simplifier.net/forge

**Comment by JGreenFearless** [comment]
@carlosfelix2 @clediggins-usds Do we still need this ticket?

**Comment by carlosfelix2** [comment]
Closed while we figure out what we really want to do with profiles if anything.
