### ISSUE TITLE
CSV Pilot _A1H_post research

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#4776]
## Overview
Assess impact of the intervention by asking similar questions to baseline. This is separate from error messages. See research plan. 

## To do

- [x] Locate existing sender notes. If notes do not exist, create new folder and notes in `CSV upload pilot folder / experience folder / name of state (e.g. Colorado)` 
- [x] email partner to schedule meeting
- [x] Schedule meeting with partner
- [x] Assign RS team member as note taker (if possible) 
- [x] Conduct meeting and take notes in ongoing notes doc @victorialb-usds  and @inkandsound 
- [x] Share insights with team:
  - [x] Slack @a-chappelear 
   - [x] Add to [PPT](https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B3883912A-317A-4E99-8A2E-187C105C02BF%7D&file=A1H%20Pilot%20Synthesis_1.27.22_Internal.pptx&action=edit&mobileredirect=true&cid=4ab41cf6-aeb5-40da-a752-0320ce73a8af) @victorialb-usds or @a-chappelear Monday 4/18

**Comment by victorialb-usds** [comment]
meeting scheduled for Thursday 3/31 1 pm PST/4 pm ET. @drew-usds @rachelhanster do you want to join for this call - I would like one notetaker/back up facilitator; also any follow up on designs too

**Comment by victorialb-usds** [comment]
rescheduled call with A1H to Thursday 4/14

**Comment by victorialb-usds** [comment]
@a-chappelear would like to discuss what and if you might feel ok taking a stab at entering info into excel

**Comment by HeatherRienks** [comment]
@victorialb-usds & @a-chappelear - any updates on this one? Not sure if it still needs review, or if it can be closed out this sprint. Thx!

cc: @RakshindaAslam

**Comment by victorialb-usds** [comment]
I believe @rachelhanster was going to review this and then it can be closed. @RakshindaAslam if you and @rachelhanster have review the content feel free to close. The work is done.
