### ISSUE TITLE
Good KDoc Documentation Examples

### ISSUE THREAD

**Issue by jh765** [CDCgov/prime-reportstream#4780]
There are good kdoc and kotlin comments for source code.  It would be convenient to have a getting-started document that provides brief good examples with bad counter-examples.  To convey clearly and quickly what to do.

I'd like to create and help maintain a kdoc-and-comments.md file in the docs/getting-started folder to illustrate good practices.

Please add any alternative solutions, here.

**Comment by jh765** [comment]
placeholder...

**Comment by JGreenFearless** [comment]
@jh765 Can you re-write this using our template?  After which, it can be groomed.
