### ISSUE TITLE
Report and Submission History API JSON response should not show sending at time if data will not be sent

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#4784]
### User Story:
As a sender, I do not want to see a sending at time if the data is not to be sent to a destination, so I can clearly see where my data is sent to.

### Description/Use Case
API JSON response should not show sending at time when data will not be sent to a destination.  While you can have an itemCount of 0 when all items are filtered for a destination, you can still get an itemCount > 0 for destinations that are not configured correctly and hence will never receive any data.  For example, as of 3/16/2022, md-doh for our local is setup with NO transport and hence nothing will truly be sent.  To duplicate this issue you can use the `prime-router\examples\submission\simple_report_example.csv` file and sent it as simple_report.  The result will be like

```
"organization_id": "md-doh",
            "service": "elr",
            "filteredReportRows": [],
            "sending_at": "2022-03-15T18:05:00.000Z",
            "itemCount": 2,
            "sentReports": [],
            "downloadedReports": [],
            "organization": "Maryland"
```

However, nothing is sent because the receiver does not have a transport.  Note this could be an issue in some other part of the code besides the JSON response, so make sure that the logic is correct in the proper place in code.

### Risks/Impacts/Considerations
* The FHIR to HL7 library is unable to convert some data for some unforeseen reason.
* The HL7 to FHIR conversion was not lossless and we are missing data.
* If we make changes to not report destinations we are not sending to, will this affect any of the metabase reports or metadata?

### Dev Notes:
The fix could be something on the JSON response, or somewhere else. Where is this data generated?  Is it stored in the database and also needs to be fixed there?

### Acceptance Criteria
1. The submissions and reports API shows the correct status of no items to be sent for a destination that is not configured to receive any data.
2. Update the OpenAPI spec as necessary to show this change.
3. ReportStream still process reports as expected (no loss of data, metadata stored in DB, etc.)

**Comment by JGreenFearless** [comment]
@carlosfelix2 Is this still something we need to address?

**Comment by jimduff-usds** [comment]
I think this condition should be rare in Production, just because we rarely have Receivers with 'timing' but no 'transport'.    The one "normal" situation when this will happen is for a receiver that is only using manual download via the web UI - they will having a 'timing' but no 'transport'.

I'm guessing there aren't many such cases in Production.
