### ISSUE TITLE
Interface to change sorting order on Submissions list

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#4787]
Previously scoped: #1922

This ticket is a breakout from the Sort & Filter ticket above. This breakout ticket is a result of the USWDS sorted table header not displaying as intended. Drew agreed to take that portion back to design and come up with a new solution.

Acceptance Criteria
- Given I
Am logged into ReportStream with Sender permissions
- When I
Log into ReportStream
Choose to view my Submission History 
See the list of my successfully submitted files
- Then I
Can sort the submissions that are displayed by the Date/time submitted (ascending or descending)
Can change sort order and the list re-populates based on the selected filters

**Comment by bgantick** [comment]
@drew-usds Closing this out. @kevinhaube can demo the new table component.
