### ISSUE TITLE
Loading (Suspense) and ErrorBoundary need standardization

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#4790]
# Overview

The front-end directory began using `rest-hooks`, a library from Coinbase that handles RESTful API calls in a Reactive way. Their documentation led us to using `<Suspense>` to handle our loading spinner needs and `NetworkErrorBoundary` to handle errors thrown in components. Unfortunately, at the time, we were still in startup mode, so we didn't fully grasp the Suspense/ErrorBoundary pattern.

At its creation, this ticket proposed the following solution to normalization:

```typescript
const [loading, setLoading] = useState<boolean>(true)

useEffect(() => {
     if (apiContent) { setLoading(false) }
}, [apiContent]);

if (loading) return (
    <Spinner />
)
```

Our new API tooling supports this, however, that would require a heavy refactor of multiple API calls in components to utilize. Beyond that, it's also easily solved for by consolidating the logic in a higher-order component (HOC) and conditionally showing an alternative. After thinking myself to this conclusion, I realized... that's `Suspense`.

Long story, short, the pattern `rest-hooks` originally suggested is actually preferred for its agnosticism to what API tooling we're using, but in removing their library, we will be left without `NetworkErrorBoundary`, meaning we need to create our own. Luckily, `Suspense` is part of React.

# Tips for `Suspense` and `ErrorBoundary`

## ErrorBoundary
Info on creating ErrorBoundaries can be found [here in the React docs](https://reactjs.org/docs/error-boundaries.html)

An ErrorBoundary is basically a `catch` block for rendering components that `throw` and `Error` -- something our new API tooling and utility functions are beginning to do in an effort to expand our in-app error messaging. With that in mind, you simply nest any components with a chance of throwing in this boundary, and you can use the boundary to handle it however you please. For example, displaying the stack trace if it's a JS error, or relaying the API message if it's a network error. 

To achieve this without disruption to much of our code, and having to manually figure out where to put each tag, we can make a HOF that nests it for us, and export like:

```typescript
// Now includes <ErrorBoundary> wrapper when used without adding it to the JSX!
export default withErrorBoundary(FuncComponent)
```

## Suspense
[Info about Suspense](https://reactjs.org/docs/react-api.html#reactsuspense), but bare in mind that there is outdated info about Suspense not being used for data fetching. It _is_ now used for data fetching.

Suspense follows the same declaration: nest inside of it any component with network calls or lazy loads, and you'll get an automagic spinner! Baring that in mind, the same logic applies: simply use a `withSuspense()` on export. 

## Methodolgy

So far as I can tell, Suspense should always be _inside_ of an ErrorBoundary, but nothing states logically nor syntactically that Suspense must be a direct child of ErrorBoundary. This gives us design flexibility!

It makes the most sense to work bottom-up when working with design. We are able to better control what components do and don't show at lower levels of the tree; higher levels are page-sized components and currently that is why most of our pages are consumed by a spinner when loading! 

Both Suspense and ErrorBoundary will be needed for API calls, but it's a good thought exercise to stop and consider where we need them. Network errors like `401` can cause most of a page to be unusable if accessed, but are _some_ parts still logical to render? Because some component loading UI needs may differ from the location of the `ErrorBoundary`, it makes sense to keep them separate and compose them together if you need to use both in one spot. 

# Acceptance Criteria

- [ ] HOF/HOC for wrapping with Suspense and ErrorBoundaries separately and together
- [ ] Refactor out `NetworkErrorBoundary` with our own solution that serves our unique needs as we uncover them in design co-work.

**Comment by bgantick** [comment]
cc @drew-usds for style/design considerations

**Comment by kevinhaube** [comment]
Setting this to be blocked by #5557 on Zenhub. The consumer hook for API endpoints will spit out a `loading` state that's managed in the hook and can be used in components. This'll drastically cut down the time needed to normalize spinners across the app.

**Comment by bgantick** [comment]
This should be brought to design sync once it is in a place to be reviewed (to get consensus on styles and where loaders should show up). cc @drew-usds

**Comment by kevinhaube** [comment]
I have _technical_ thoughts on this work to share in our sync on Thursday, and as a general thought, let's work on the design side first. @drew-usds @a-chappelear We can collab to figure out where spinners occur, when and why, and same for errors, no content loaded, etc.

**Comment by HeatherRienks** [comment]
Per backlog refinement mtg on 6/29/22, we will have a coworking session (Design & Eng) to tackle this!

**Comment by RakshindaAslam** [comment]
@drew-usds - add design ticket for this that needs to be done first.

**Comment by kevinhaube** [comment]
From PR #6416 
> Two main issues I found:
>1. Our endpoint doesn't throw, so, it's not much help.
>2. Because we aren't using rest-hooks, that NetworkErrorBoundary doesn't do what we need. We don't have a custom ErrorBoundary of our own yet, so we can't implement ErrorBoundaries for non-rest-hooks errors. 😢

We will need a custom error boundary to handle things.

**Comment by doug-s-nava** [comment]
closing this, as it this work was covered in https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6522 https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6662 https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6785
