### ISSUE TITLE
[Bug] CSV uploader: drag a file to upload function not working

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#4792]
**Describe the bug**
As a csv sender, I sometimes want to drag a file to upload it vs clicking "“Choose from folder” button. 

A csv sender reports:
"I have attached a screenshot of the error that I receive when trying to drag files from my desktop to the upload portal.  
I have been using Microsoft Edge on Windows operating system.  
When I click the “Choose from folder” button, I am able to select the file and it works every time." 

 
**Impact**
To be discovered: 1 user or all csv uploader users

**To Reproduce**
1. Go to "Upload"
2. Try to drag a file to upload
3. See error

**Expected behavior**
A user can either drag a file or "choose from folder"

**Screenshots**
![Invalid File Type v2.png](https://images.zenhubusercontent.com/61434e26d4a139174e54bf81/7db292ce-177c-4aaf-86c8-cb0c01afc9e0)

**Comment by rachelhanster** [comment]
@bgantick @drew-usds  I would prefer we disable drag and drop, by changing text instruction from "Drag file here or choose from folder" to "Choose from folder." If we were to add additional text to explain how to use the drag/drop function, it might quick up more confusion and/or introduce an additional touchpoint with customer success/support. Thoughts?

**Comment by drew-usds** [comment]
@rachelhanster @bgantick  yes totally agree on just disabling the drag and drop. 

If we're choosing between the two -- it's more confusing, and could possibly introduce other problems, if we ask folks to rename files. The extension is getting applied by whatever their system outputs and asking them to rename (or maybe they'd even end up make duplicates of files with different extensions), might be more of a pain than just picking the file.
