### ISSUE TITLE
[design] Receiver facing: show which senders are in test mode with reportstream

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#4799]
## Problem statement

As a public health department, I want to know which facilities' data are included in the state's single data connection so I can track which facilities and organizations are able to submit data to us.

## Acceptance Criteria

- Given I am logged into reportstream and receivers' download site, I am able to see a list of facilities in test mode with reportstream. Test mode is defined as in the process of onboarding with reportstream.

## Note
- Only sender organizations can be shown in test mode

**Comment by BerniXiongA6** [comment]
@drew-usds pls pre-refine at design sync

**Comment by chris-kuryak** [comment]
Closing by committee decision. Will be re-assessed in future receiver research, and will be recreated naturally if needed.
@drew-usds @fmccaf1 @HeatherRienks @lizzieamanning
