### ISSUE TITLE
BUG:  Non-null blobs with real data, but associated with 400 errors are leaking into the system.

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#4815]
Reports with 400 errors should never have item_count > 0.  And they should never have non-null blob_url.
This ticket is to find out what's happening, and fix it.
This is a problem because the duplicate detection is looking at digests for other reports.

Acceptance criteria:
1. Replicate and investigate why this issue is occurring.
2. Fix as part of this issue or create new issues as needed.

**Comment by JGreenFearless** [comment]
@clediggins-usds believes this has been resolved; needs to be checked.

**Comment by clediggins-usds** [comment]
This is resolved alongside the fix for #6114
