### ISSUE TITLE
MN - Received message with W in OBR-25

### ISSUE THREAD

**Issue by brick-green-agile6** [CDCgov/prime-reportstream#4830]
`MDH has received invalid result status ‘W’ in OBR.25 for Accession number e0f38f21-cbbe-409a-a76c-3c1f5a2de883^Hospice of the Red River Valley^35D0721452^CLIA (ORC.3).
Can you please correct and resend it?`

Need to investigate and resend data.

cc @Adrian-Brewster @anshulkumar-usds

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 We closed a related issues for MD on this topic:
https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4392

Just sharing for your awareness in case the filtering logic needs to be re-examined. MD confirmed they do not want "W" or "X" in either OBR-25 or OBX-11.

**Comment by brick-green-agile6** [comment]
asked MN if they'd like us to filter

**Comment by brick-green-agile6** [comment]
MN would like to have the W messages filtered
