### ISSUE TITLE
Verify prospective user's identification

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#4831]
## Problem Statement 
As a prospective user, I'm unable to complete onboarding to use ReportStream in production unless my identification has been verified by ReportStream or a public health authority.

For prospective users who are not referred by a public health authority to Reportstream, as an organization, ReportStream is responsible for identity verfication.

Prospective user can be someone who works at a reporting facility (sender) or public health authority (receiver).

## Describe the solution you'd like
When necessary, a prospective user is able to easily provide the necessary document(s) to verify their identity.

## Describe alternatives you've considered
Prospective users who find out about ReportStream independently:
Solution 1: Video session with a ReportStream admin
Solution 2: Outsource verification work to a third-party organization

Prospective users who discover ReportStream via a referral from a public health authority
Solution 1: Channel referral tool for public health authorities to easily make a referral and for ReportStream to automate the referral process

**Comment by chris-kuryak** [comment]
@drew-usds Can you provide any guidance on this regarding:
- Who does the user ID/verification process?
- Did this problem get solved?
- Is it still a problem for our users/RS-admins?

**Comment by chris-kuryak** [comment]
This is being encompassed by Dylan's current work on engagement. Ref: #10035
Closing.
