### ISSUE TITLE
Add Next of Kin Capability for ELR Message

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#4833]
As part of work to allow ReportStream to send additional ELR information, and a more complete data record, we need to add the information that can be used to fill in [the NK1 segment](https://hl7-definition.caristix.com/v2/HL7v2.5.1/Segments/NK1).

These include:

- Adding the Contact Role value set - https://hl7-definition.caristix.com/v2/HL7v2.5.1/Tables/0131
- Adding the Relationship value set - https://hl7-definition.caristix.com/v2/HL7v2.5.1/Tables/0063
- Adding the following fields:
    - next_of_kin_first_name
    - next_of_kin_last_name
    - next_of_kin_middle_name
    - next_of_kin_relationship
    - next_of_kin_address (street, city, state, postal)
    - next_of_kin_phone
    - next_of_kin_email

FYSA: @Adrian-Brewster @anshulkumar-usds @sarahnw

**Comment by avnieldravid** [comment]
Tagging @arnejduranovic not sure about these specific fields.  Can you point us in the right direction?

**Comment by bishoyayoub** [comment]
UP supports this effort.
