### ISSUE TITLE
Add Base ELR Schema

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#4840]
Looking ahead to the future where we are able to send not just COVID messages, but other types of reporting, we should create a base ELR schema that includes the core field definition (for example the name, a base type, and documentation) but not much else. This schema should not have any composite fields (for example `message_profile_id` which fills in four fields with a single string value, or `sending_application_id`) and is intentionally very generic. 

The `covid-19.schema` would then inherit from that schema and fill in defaults and HL7 outputs, override fields to inherit from value sets, etc. 

An example would be the `specimen_source_site_code`. We currently fill that in with a COVID-specific value set, but these values will change for different diseases. In the base ELR schema we will treat this code as a TEXT value, but the COVID-19 schema converts it to `CODE` and the right value set.

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/4840?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS

**Comment by brandonnava** [comment]
@brick-green @avnieldravid @arnejduranovic Same here is this taken care of by the UP work?

**Comment by brick-green** [comment]
Definitely don't need this one anymore
