### ISSUE TITLE
Add HIV LIVD Table to Application

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#4842]
The CDC currently publishes a LIVD table for HIV tests. We should incorporate this data into the application. 

The Excel spreadsheet is [here](https://www.cdc.gov/hiv/xls/guidelines/cdc-hiv-diagnostic-tests-loinc-map.xlsx).

The outcome from this ticket is an epic for the work required to get the data into the application.

Acceptance criteria:
- Create the epic

**Comment by brick-green** [comment]
The LIVD table (or any test reference table) is not being used in the UP currently. IMO, some kind of test reference table is and tool is needed in the UP that would accept the COVID and HIV LIVD tables. I think this epic should be changed to a ticket and included as part of a new epic for platform to build out the test reference.

**Comment by bishoyayoub** [comment]
Will create a story for LIVD HIV if needed.
