### ISSUE TITLE
Discussion About Integration with eHARS API

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#4844]
As part of the thinking around incorporating STI and HIV test results into ReportStream, we should have some discussion and planning around meeting with the eHARS team to see what it would take to stand up an API that our system could communicate with and deliver test results to.

**Comment by avnieldravid** [comment]
I think we can close this for now.  We will be working with SimpleReport on the STI pilot, so it might come up again, but we can re-write in our User Story template.
