### ISSUE TITLE
FHIR -> HL7 PATIENT_RESULT/PATIENT/PID mapping

### ISSUE THREAD

**Issue by whytheplatypus** [CDCgov/prime-reportstream#4852]
Map this required field of the ORU_R01 hl7 message from our FHIR resource.

Acceptance criteria:
- Our FHIR model has been updated to include any necissary information _from_ a given ORU_R01 message
- The FHIR -> HL7 translation builds a ORU_R01 message with a complete PID segment

**Comment by JGreenFearless** [comment]
@carlosfelix2 I believe you and Cle have developed tickets related to mapping or converting the various segments - can we close this?
