### ISSUE TITLE
Content changes for CSV Schema documentation: Patient ID and Requested guidance

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#4854]
## Problem statement

As a CSV Upload user, I want to have the most updated schema guidance for submitting my CSV file to ReportStream.

## What you need to know

- [Original Slack Thread from Rick Hood](https://agilesix.slack.com/archives/C02HJ43AE8Z/p1648039370006869)
- [Shared Working Doc](https://cdc.sharepoint.com/:w:/t/USDSatCDC/ETthm9WygedBnEbPPArjjEYBlpbGDpCxJdfAP1d157ZvKw?e=uoe6Q4)
- [Location on ReportStream website where changes are needed](https://reportstream.cdc.gov/getting-started/testing-facilities/csv-schema)

## Acceptance criteria

- [ ] Change Patient ID to Requested from Optional.  
- [ ] Change the guidance of "Requested" to read: "Fields are not required by HHS, but the data is incredibly helpful to and, in some cases, required by jurisdictions."

## To do

- [x] Content to update Shared Doc with items above in acceptance criteria
- [x] UI to stage changes for deployment

**Comment by BerniXiongA6** [comment]
Updated 3/23/2022: Content revisions have been made on the shared doc (it only took me 5 minutes). Ready for UI work @drew-usds (feel free to wait for refinement before pulling in this work).

**Comment by rachelhanster** [comment]
@rhood23699 Follow up questions:
1. Why is "patient ID", if available, is helpful to public health authorities?
2. For requested fields, if they were blank, will the file submission go through or file?

**Comment by rhood23699** [comment]
@rachelhanster 
1. Patient ID along with other patient information is used by the PHD's Surveillance System to attempt to automatically link results from multiple Senders to the same patient.
2. HHS currently lists Patient ID as requested, but some States required it.  In our CSV Schema, we will accept blank, but behind the scenes, we create a dummy patient ID, so that it will not fail for the States that require it.

**Comment by bgantick** [comment]
Should be done at the same time as #5292

**Comment by mreifman** [comment]
@BerniXiongA6, for non-required fields, we currently sometimes show both "Requested" and "Optional". Since the definition of "Requested" indicates it's not required, could we change the documentation rules to reflect that this property has only one of the three values? 

Doing so would simplify how we model the data (using one field instead of three) and render it (`required: true` takes precedence over the rendered value, which isn't clear just by looking at the data).

**Comment by BerniXiongA6** [comment]
Hi @mreifman , when we originally published this guidance on the CSV schema documentation static page, we added the "Optional" label to any fields that were "not-required" or requested" to indicate to the user that their file would not fail if the fields were left blank. 

We had originally thought that [having the guidance at the top of the page](https://reportstream.cdc.gov/getting-started/testing-facilities/csv-schema) would help the user distinguish between 1) Required 2) Requested 3) Optional. But as you can see when you scroll through the static page, the rules get buried and a user won't necessarily remember the difference between Requested and Optional. 

Though it might seem redundant, at the time Design decided to give "Requested" fields BOTH labels to prevent confusion for the user. I'm open to discussing your idea and revisiting this decision - could we bring it to the larger group on our Experience team to see what they think?

**Comment by BerniXiongA6** [comment]
Sounds good to me @mreifman and I do appreciate the consideration for web accessibility!

**Comment by mreifman** [comment]
Recapping our discussion at standup: "Requested" isn't really its own level but rather a modifier to "Optional." It might be helpful to indicate the requested nature of fields in a different way to avoid confusion, but that may be out of scope here.

That last point did make me wonder about whether and how the change in the guidance language at the top should also impact the field descriptions. 

Right now the "Requested" guidance says: 
> Fields are not required. If available, including this data is incredibly helpful to public health.

and then requested fields have something like this:
> Enter patient's pregnancy status. Field is not required, but requested for thorough reporting. Enter one of the acceptable values exactly as displayed.

@drew-usds, @BerniXiongA6: should that per-field language also change? Should we take this as an opportunity to change the presentation of the "Requested" indicator?

**Comment by BerniXiongA6** [comment]
Hi @mreifman these are good callouts. My recommendation would be to 1) have Content decide on a consistent guidance per-field, and then 2) have UI or Front End make edits on all impacted fields all at once as opposed to editing per-field guidance one at a time. When we first drafted the guidance, the language used per field seemed more consistent then. As we've been updating the schema, we've noticed the guidance changing a bit too. That might be why the guidance seems less consistent. If you and @drew-usds agree with this recommendation, I'll write up a ticket for this Content work for a future sprint.

**Comment by mreifman** [comment]
That works for me -- I'll keep things as-is for now and just make the changes originally described in this ticket.

**Comment by mreifman** [comment]
Ugh, sorry for the churn here, but I looked back at the description and remembered why I started down this path:

> Change Patient ID to Requested from Optional.

Given the clarification that "requested" modifies "optional" what I would do here is _add_ the Requested label to the Patient ID field. Is that right, @drew-usds?

**Comment by HeatherRienks** [comment]
@drew-usds - please see note from @mreifman. Thanks~

**Comment by BerniXiongA6** [comment]
HI @mreifman - I just checked the [standard schema documentation authored by Rick Hood ](https://cdc.sharepoint.com/:w:/t/USDSatCDC/EUYE7gtPjjZHvWBIMfsddewBErRq0UycLrYxd9lEsu7piA?e=bICWkq), which informs the content I create for our public-facing static pages, and I can confirm that "Patient ID" should get the "Requested" label. So yes to your question. Go ahead and add "Requested" label to Patient ID. Thanks for following up! cc: @drew-usds
