### ISSUE TITLE
Receivers: Add paging functionality to list of reports on daily data page

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#4859]
## Problem statement

On the daily data page (https://reportstream.cdc.gov/daily-data), results can get quite long. We'd like to add pagination to this table to make it easier to consume and save on load time.

## What you need to know

 Similar to https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3795

## Acceptance criteria

1. On daily data page, I see table of test results reports
2. Table of reports is paginated

## To do
- [x] On daily data page, I see table of test results reports
- [x] Table of reports is paginated
- [ ] Unit Tests
- [ ] Team review

## Assumptions

- API work is already done

## Design

- Page design is similar to [senders' submission history](https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=2513%3A22007), with "number of records per page 25 50 100" on the lower left hand side and "previous" "next" on the right hand side.

**Comment by BerniXiongA6** [comment]
@bgantick please pre-refine at eng sync

**Comment by bgantick** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/4859?planning-poker) with ZenHub @TomNUSDS

**Comment by bgantick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/4859?planning-poker) with ZenHub @kevinhaube @sethdarragile6

**Comment by kevinhaube** [comment]
Changed to an 8 to account for unexpected refactor from history -> deliveries

**Comment by kevinhaube** [comment]
Tying in 6126 since it involves conversion to new API tools

**Comment by kevinhaube** [comment]
Can continue work on this with Luis's most recent PR fixing Delivery bugs. Auth bug still a blocker for merging to Staging/Prod

**Comment by kevinhaube** [comment]
Swapping to a 3-pointer and putting into Next Items pre our discussion in sprint planning related to React Query implementation being a blocker

**Comment by kevinhaube** [comment]
Incremental work to untangle network calls in Daily Data led to 6524 (tech-debt for Sprint 54 anyway) being included in necessary changes for this work to be completed! Two birds, meet my one stone.
