### ISSUE TITLE
Receivers: Add date filtering functionality to list of reports on daily data page

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#4861]
## Problem statement

As a public health department employee, I want to easily navigate and understand reports that were uploaded

## Acceptance criteria

- On the /daily-data page, I can filter the table by date range

## Design

- Page design is similar to [senders' submission history](https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=2513%3A22007)

**Comment by BerniXiongA6** [comment]
@bgantick please pre-refine at engineering sync

**Comment by bgantick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/4861?planning-poker) with ZenHub @TomNUSDS @kevinhaube @sethdarragile6

**Comment by kevinhaube** [comment]
Set to deploy 10/20
