### ISSUE TITLE
CSV Uploader - Not all but some warning messages need to be displayed for the Sender

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#4863]
## Problem statement
When using the CSV Uploader, not all warning messages, but some warning messages need to be displayed for the Sender.  Below is an example of the patient_phone_number warning message.  The Sender needs to know if they are making data entry errors, so they can address them.  Another example is for patient_preferred_language.

**Current patient_phone_number warning message**.
          "itemNum": "167",
          "groupingId": "Invalid phone number 'UNKNOWN' for patient_phone_number (patient_phone_number). Reformat to a 10-digit phone number (e.g. (555) - 555-5555)."

## Things know
When grooming this Ticket, you may want to reach out to Mo because he had some ideas on how to do this from an Engineering perspective.

[See Slack Thread with some initial guidance from Rick Hood](https://agilesix.slack.com/archives/C02HJ43AE8Z/p1648039370006869)
## Acceptance criteria
- [ ] ??

## To do
- [ ] ???

**Comment by BerniXiongA6** [comment]
@rachelhanster and I can review this soon and will update the ticket details or comments to keep everyone informed on next steps. Thanks @rhood23699

**Comment by rhood23699** [comment]
@rachelhanster Additional fields are:
patient_state
ordering_facility_state
ordering_provider_state
testing_lab_state

**Comment by rachelhanster** [comment]
Closing this ticket for ReportStream. Will share this as a roadmap input idea w/ SimpleReport.
