### ISSUE TITLE
Add Link to API Programmers Guide v2.2 on public-facing pages

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#4874]
## Problem statement

Sender: As an API user, I want to have the most current copy of the API Programmer's Guide so I can correctly submit data through ReportStream.

ReportStream: We want to make the API Programmer's Guide available on the website so that email exchange is not necessary and so that end users always have access to the most up-to-date guidance.

## Acceptance criteria

- [ ] Add a link to the API Programmer's Guide version 2.1 on ReportStream website's Sender Overview page (to replace v2.1 link)
- [ ] When the [v2.2 file is completed by Content](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/3.%20Instructional%20Design%20Projects/ReportStream%20API%20Programmer%20Guide/Version%202.2/FINAL%20-%20ReportStream%20API%20Programmer%20Guide%20v2.2.docx?d=w45034ec803a8466ba5f5e78066e323e6&csf=1&web=1&e=Yeg393), create a PR to add the [Doc version to Github](https://github.com/CDCgov/prime-reportstream/tree/master/prime-router/docs)

## To do

- [ ] Remove v2.1 docx from `/prime-router/docs`
- [ ] Add v2.2 docx at `/prime-router/docs`
- [ ] Create public pdf version (make sure the PDF is clickable for users) to link to
- [ ] Add link to `/getting-started/testing-facilities/overview`

**Comment by BerniXiongA6** [comment]
@drew-usds please feel free to flesh out the AC further as needed, thanks!

**Comment by drew-usds** [comment]
@BerniXiongA6 looks like eng already did this? PR #4908 got merged this morning.

**Comment by BerniXiongA6** [comment]
@drew-usds I think you may be confusing this ticket with Programmer's Guide version 2.0 (see my content ticket #[4101](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4101) and [#4555](https://github.com/CDCgov/prime-reportstream/issues/4555)). This is not the same as version 2.1 (NIH standards, which haven't been updated in the schema yet).

**Comment by drew-usds** [comment]
Just updated our version number to 2.2 based on _different_ updates made in PR #4908

**Comment by HeatherRienks** [comment]
Should be done at the same time as #5292 and #4854.

**Comment by BerniXiongA6** [comment]
Hey @bgantick next week I'll be prioritizing revising the API programmer's guide v2.2 (since Joel is done updating the contents for me which now include NIH standards). In addition to linking up the PDF to the public-facing website (this ticket), Joel says that we also should include the [Doc version of the guide in GitHub](https://github.com/CDCgov/prime-reportstream/tree/master/prime-router/docs). @jbiskie wants to know if he should do a PR for that, or do we? I couldn't remember if Experience engineers did that last time?

**Comment by bgantick** [comment]
@BerniXiongA6 Looking at the last two edits in GH.. it looks like 2.1 was added Stephen N. and 2.0 was added by Drew. If you have the file, I can add it if you want.

**Comment by BerniXiongA6** [comment]
Updates 6/6/2022: [Final Version 2.2](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/3.%20Instructional%20Design%20Projects/ReportStream%20API%20Programmer%20Guide/Version%202.2/FINAL%20-%20ReportStream%20API%20Programmer%20Guide%20v2.2.docx?d=w45034ec803a8466ba5f5e78066e323e6&csf=1&web=1&e=Yeg393) is ready for staging!

**Comment by BerniXiongA6** [comment]
Updates: Here's the PDF that I gave @doug-s-nava - [keeping a copy here for our reference](https://cdc.sharepoint.com/:b:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/3.%20Instructional%20Design%20Projects/ReportStream%20API%20Programmer%20Guide/Version%202.2/FINAL%20-%20ReportStream%20API%20Programmer%20Guide%20v2.2.pdf?csf=1&web=1&e=qTKNLO).
