### ISSUE TITLE
undesired expansion of HL7 fields with type ID

### ISSUE THREAD

**Issue by jbiskie** [CDCgov/prime-reportstream#4878]
This is a follow-on to the latter half of #4793, which has been resolved for the state of WA in PR #4807. When we receive HL7 results from senders, ID fields such as OBR-25, OBX-2, and OBX-11 are expanded from standard ID values (e.g. "F", "CWE") to fully expanded values such as

```
F^Final results^HL70123
CWE^Coded With Exceptions^HL70125
F^Final results; Can only be changed with a corrected result^HL70085
```

**Impact**
Receivers are expecting value type ID in these fields and messages will error.

**To Reproduce**
Run sample message in #4793 through RS for a state **other** than WA and note the output will match the "current" messages documented in that issue, rather than the "desired"

**Expected behavior**
HL7 ID fields will retain their values as received, instead of expanding them.

**Additional context**
Believe these values are getting set by the code in setCodeComponent. Excluding fields of type ID within this function (or possibly the calling function, if appropriate) should resolve the issue.

**Comment by oslynn** [comment]
Try to fix Smoke Test by reversing the value_type.type: CODE and pushed the commit.  However, it auto-merged to master bank.  I will have to create another branch to fix the OBX-2 value_type.type: ID.

**Comment by oslynn** [comment]
The OBX-2 is fixed in ticket 4990 by changing value_type from type: CODE to ID.  Ticket 4990: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4996
