### ISSUE TITLE
Need ability to override HL7 field with a hardcoded value

### ISSUE THREAD

**Issue by jbiskie** [CDCgov/prime-reportstream#4879]
**Is your feature request related to a problem? Please describe.**
For HL7 senders, we cannot currently default a value in a field and have it **always** replace the value received. This is described in the first half of #4793, which was resolved for WA only by the use of 2 sender-specific replacement values. 

**Describe the solution you'd like**
We need to be able to set a default, hardcoded value for a field and have it populate that way for all receivers.

Another example where this is needed is for testing in production. When we onboard an HL7 sender to testing in production, we rely on them to set MSH-11 to "T" or "D" so their messages aren't routed downstream. If they forget to do this and send "P" instead (which happened this week with WA), their messages will route to HHS+STLTs before they've been approved for full production. 

**Describe alternatives you've considered**
Have tried changing field definitions in child schemas to not reference their corresponding inbound HL7 fields, but that did not affect the functional behavior.

**Comment by oslynn** [comment]
The ticket allows users to wild card (*) replace as organizations.yml setting below:
replaceValueAwithB:
          MSH-3: ["*": "CDC PRIME - Atlanta, Georgia (Dekalb)^2.16.840.1.114222.4.1.237821^ISO"]
          MSH-11-1: ["*": "D"]
It will replace whatever in MSH-3 with "CDC PRIME - Atlanta, Georgia (Dekalb)^2.16.840.1.114222.4.1.237821^ISO" and 
MSH-11-1 with 'D'
