### ISSUE TITLE
Discovery Research Planning: Decide on Discovery Calls with States that are new or returning to engage with ReportStream

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#4881]
## Overview
As states return to ReportStream after not wanting to participate, we need to understand why they are coming back. What needs and conditions are facilitating their interest in joining ReportStream. This will provide insights into developing and marketing the product and also track with these users the anticipated versus the actual impacts (the intended and unintended consequences).

## Potential Participants
- PHD contacts at: 
- Indiana
- Nevada
- Idaho
- North Carolina

## Background
- [ ] Check the [State Tracker](https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BF3F64FEB-FAE6-457A-A6DD-34F5DD73881F%7D&file=PHD%20Onboarding%20Tracker%20-%20v2.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1)
- [ ] Have we had previous contact/meetings/etc with the participant?
- [ ] Desk research on the participant for any relevant information: website/documentation/etc

## To do
- [ ] Identify states to reach out to currently Indiana, Nevada, Idaho, and North Carolina that will not confuse their onboarding
- [ ] create tickets based on tasks below: 

Ticket 1: 
- [ ] Warm hand off (email) from person with existing relationship 
Ticket 2: 
- [ ] Email/schedule session with STLT/partner
- [ ] Confirm schedule and set up team for notetaking and recording  

Ticket 3
- [ ] Tailor the facilitation guide 
- [ ] Read background materials and previous emails 

Ticket 4
- [ ] Conduct call (facilitation, notes, recording) 
- [ ] Upload any documentation notes and recording  
- [ ] Identify high-level findings, put in shared document 
Ticket 5
- [ ] Share in Slack

**Comment by drew-usds** [comment]
@victorialb-usds  Edits to this issue: Can we edit this so it's more about deputizing O&O to carry this out? Can we create a plan for them to execute on and report back to us?
