### ISSUE TITLE
Send survey with internal team members to test

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#4882]
## Problem Statement
As the Experience Team, we would like to TEST our customer survey, so we can troubleshoot before survey is sent out to current users. 

## Acceptance Criteria
- Recruit 5 team members from Operations team + Experience team's designers
- Send survey to 5 team members via email

**Comment by victorialb-usds** [comment]
try to do before 4/1 or while away.

**Comment by victorialb-usds** [comment]
By COB Thursday 3/31

**Comment by victorialb-usds** [comment]
Here is what I plan to send after the meeting today in RS channel. Hi everyone, as demo'd today for CDC, RS is planning on sending out the ReportStream customer experience soon. But we need at least 5 people to test it. I would like to request that you pretend that you are (1) working at a STLT (2) working at an org that is an API sender (3) working at an org that is a CSV uploader sender as you complete it. If you are game, respond in the thread. I will post a link to the test survey in thread too. Please complete the survey with your user hat on and and enter feedback in comment function (it is the little word bubble). You can also add feedback and questions, and indicate you are DONE using the thread.  What I am I looking for ..... are you getting stuck any where --- if so document in comment function questions you have.  We can add little instructions as needed.  THANK YOU SO MUCH! This should not take you more that 10 - 15 minutes. (the survey should only take a few minutes itself). I would like to have feedback by COB tomorrow so we can cue everything up to be sent first thing Monday morning or early in the week (no good to send emails end of the week/especially Friday afternoon!).  [link: https://www.surveymonkey.com/r/Preview/?sm=hrtWt_2FdfnmfvsofrYMaSMYKApdQsc_2BCkIz0qX2_2B1l4fNKy5cqB9FgTZTXhXFiG0a]
