### ISSUE TITLE
Research Debt: entering, maintaining and sharing info from research repo

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#4890]
## Problem Statement
As a design team on ReportStream, we need an easily searchable tool to summarize data points gathered from various data sources, e.g. ReportStream team members, product end users, CDC stakeholders, desk research, etc., to inform product and design decisions.

A research repository would be the tool that serves this purpose, in addition to slide presentations in PowerPoint and synthesis reports in Word.

## Overview
We have created a research repository in Microsoft lists that we need to be entering our previous and ongoing research into. 

*this might be an epic?

## Participants
Designers and those that we need to collect data from. 

## To do

- [ ] Enter into [Research Log](https://cdc.sharepoint.com/teams/USDSatCDC/Lists/ReportStream%20research%20log/AllItems.aspx?env=WebViewList)
- [ ] Enter into [Research Insights](https://cdc.sharepoint.com/teams/USDSatCDC/Lists/ReportStream%20research%20tracker/AllItems.aspx?env=WebViewList)
- [ ] If applicable, Identify high-level findings, put in shared document 
- [ ] Share in Slack on a regular cadence?

**Comment by rachelhanster** [comment]
@victorialb-usds Can I get help to understand what is the purpose of the research repository in Microsoft lists, specifically research log and research insights?

**Comment by rachelhanster** [comment]
@victorialb-usds @drew-usds Nudge to provide more info on developing a research database: what is the purpose of research repository in Microsoft lists as it relates to other research artifacts, e.g. slide presentations and research notes?

**Comment by drew-usds** [comment]
@rachelhanster This is about developing a more refined practice and bringing insights from our users to the fore. Slide presentations/docs/etc are great for sharing overall results, but they aren't a great long-term place for keeping track of findings. 

Ex: If you were looking to see what users have said about problem X, would you rather sort/filter/search a central list of coded findings or open 20 separate notes docs or powerpoints and read 200 pages of raw notes and slideware?

**Comment by victorialb-usds** [comment]
to add a resource/more information about research repos/repositories from the field:
- https://www.nngroup.com/articles/research-repositories/

**Comment by rachelhanster** [comment]
@drew-usds @victorialb-usds Great -- we are on the same page. I didn't want to make assumptions. Will pull notes from this conversation in comments into the ticket's problem statement. 

How do we want to incorporate research repository data gathering into a definition of done for design -- if at all?

**Comment by HeatherRienks** [comment]
@RakshindaAslam - Is this a ticket we should be working on?

cc: @a-chappelear, @victorialb-usds

**Comment by HeatherRienks** [comment]
Per our conversation on 8/31/22, this will be a ticket that @victorialb-usds will work on outside of a defined Sprint for the purpose of helping RS/PRIME as a whole, not limited exclusively to the Experience Team.

cc: @RakshindaAslam

**Comment by chris-kuryak** [comment]
Closing due to being old/stale.
Closing by committee @drew-usds @jillian-hammer @lizzieamanning @audreykwr
