### ISSUE TITLE
Sender facing: Add new page to ReportStream website for Contact Us and FAQs

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#4913]
## Problem statement

- As an existing user, I want to have helpful tips or information that I can refer to when I need help with ReportStream.

- As a prospective user, I want to have helpful information or to be able to find the answers I need regarding how ReportStream can work for me.

## What you need to know
- See [shared working doc](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Website%20Customer%20Success%20Center/Content%20for%20-%20New%20Page%20-%20Contact%20Us.docx?d=we57b2685df974ffc9023f60ca19f87ab&csf=1&web=1&e=FobmAk) containing Contact Us page, and FAQs

- This came from issues [# 4760](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4760) and [# 1568](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/1568)

## Acceptance criteria

Content was created with this acceptance criteria:
- easy to access on RS public website
- information is organized by most common to least common tasks
- content must really matter
- questions and answers are phrased in customer voice
- search-able
- sender only (for FAQs)
- any type of user 

- [ ] **UI to make sure AC is kept intact during staging of content to RS website**

## To do

- [x] create new static page on reportstream.cdc.gov for "Contact us" and "FAQs"

**Comment by drew-usds** [comment]
Working branch: [dg/contact-faq](https://github.com/CDCgov/prime-reportstream/tree/dg/contact-faq/frontend-react)

**Comment by drew-usds** [comment]
Closing. This will get adapted into MD and rolled into #5858.
