### ISSUE TITLE
cardinality: ONE does not work if there is a mapper

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#4918]
## Problem statement
The code below is in upload-covid-19.schema.  testing_lab_phone_number and ordering_facility_phone_number are both blank, so I expected an error since the cardinality: ONE is set; but I don't receive an error on ingest, and the outbound HL7 has blank for the ORC.23.6 & ORC.23.7.

## Things know
For testing use the attached CSV file.  I've also attached the YML for the inbound sender cadph-csvuploadertest and outbound receiver al-phd.

curl -X POST -H "client:cadph-csvuploadertest" -H "content-type:text/csv" --data-binary "@./result_files/StandardCSV-Test-AL.csv"  "http://localhost:7071/api/reports"

    - name: ordering_facility_phone_number
      cardinality: ONE 
      csvFields: [{name: ordering_facility_phone_number}]
      mapperOverridesValue: true
      mapper: ifNotPresent($mode:lookup, testing_lab_phone_number, ordering_facility_name_temp, ordering_facility_street_temp)

[https://app.zenhub.com/files/304423150/771a7857-c60f-4ec1-afbc-da1e0d4c9a07/download](https://app.zenhub.com/files/304423150/771a7857-c60f-4ec1-afbc-da1e0d4c9a07/download)

[https://app.zenhub.com/files/304423150/72e3561d-b725-4b17-a231-f57824423f87/download](https://app.zenhub.com/files/304423150/72e3561d-b725-4b17-a231-f57824423f87/download)

[https://app.zenhub.com/files/304423150/3161b734-56d3-4092-9360-041175eaf7f8/download](https://app.zenhub.com/files/304423150/3161b734-56d3-4092-9360-041175eaf7f8/download)

## Acceptance criteria
- [ ] Blanks are treated as an error and the file is not accepted.

## To do
- [ ] ??

**Comment by rhood23699** [comment]
@MauriceReeves-usds Should I assign this to Carlos and the Pipeline team since Carlos seems to have made the last change to this code, or do you want to work on this?

**Comment by oslynn** [comment]
It looks like the Hl7Serializer use the ordering_facility_phone_number element from covid-19.schema instead of upload-covid-19.schema.

**Comment by oslynn** [comment]
Up on investigated, during translator.filterAndTranslateByReceiver(inputReport, getDefaultValues(), emptyList()), it always returns reports schema = covid-19 instead of the input-schema specified in command line.  This will cause the HL7 generation to use covid-19 instead of upload-covid-19.schema as input schema.  Therefore, regardless of what we change element in upload-covid-19 schema, it will not affect the HL7 generation.

**Comment by oslynn** [comment]
Waiting for ticket 4841 to merge.  PR: https://github.com/CDCgov/prime-reportstream/pull/5294

**Comment by oslynn** [comment]
Test command:
./prime data --input junk/StandardCSV-Test-AL-single.csv --input-schema upload-covid-19 --output-dir junk/output --route
