### ISSUE TITLE
Tables need to side-scroll in narrow viewports

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#4926]
## Problem statement
On narrow layouts, like mobile phones, the tables on the RS website do not side-scroll. They currently cause overflow scrolling.

## What you need to know
USWDS scrolling table: https://designsystem.digital.gov/components/table/

## Acceptance criteria
- [ ] Users can side-scroll data on a table when in narrow viewports.

## To do
- [ ] Implement USWDS scrolling on tables

**Comment by bgantick** [comment]
There's potentially a utility class for this (could be a very small fix)

**Comment by kevinhaube** [comment]
@bgantick @drew-usds also brought up the stacked table class that we could use on mobile https://designsystem.digital.gov/components/table/#responsive-stacked-table

**Comment by doug-s-nava** [comment]
@kevinhaube - can you confirm if this is still an issue? if so we should maybe prioritize this

**Comment by kevinhaube** [comment]
Looks like this has introduced a styling bug. @penny-lischer and I saw this odd behavior while on a call, and we traced it back to the addition of `display: block` in this PR overriding `display: table` in the uswds `usa-table` styles.

@stephenkao Should we re-open this ticket or open a new bug report?

cc: @etanb 

Without obstructions in the way of the view
<img width="1236" alt="Screen Shot 2023-01-10 at 6 54 57 PM" src="https://user-images.githubusercontent.com/4022304/211686741-1ee74f59-5755-4e79-8b1a-031f4d8eeb8a.png">
Showing the bounds of the table element in relation to its displayed size
<img width="792" alt="Screen Shot 2023-01-10 at 6 55 31 PM" src="https://user-images.githubusercontent.com/4022304/211686742-884b1492-a47e-40de-8e6c-299460207809.png">
Overridden style creating the bug
<img width="205" alt="Screen Shot 2023-01-10 at 6 55 52 PM" src="https://user-images.githubusercontent.com/4022304/211686744-97ce75c5-4c5e-4409-a4ac-548033762d1d.png">

**Comment by etanb** [comment]
@kevinhaube Penny showed me this -- was going to check it out. To confirm, the bug is that the tables are now not the width of the container, correct?

**Comment by kevinhaube** [comment]
Yes, the `display: block` style attribute causes the table to shrink in width. Noting that it _should_ cause it to take up 100% of the available space, I'm guessing something nested above the table, perhaps a grid column, is shrinking as the table content shrinks. Overrides to uswds styles can get tricky based on how they nest things!

**Comment by etanb** [comment]
Got it, I'll open a separate ticket as it isn't functionality breaking, just a visual regression: https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/7925

**Comment by stephenkao** [comment]
A separate ticket makes the most sense to me as well.  Thanks, Etan!
