### ISSUE TITLE
[SPIKE] Slow loading times for Submission Details API call

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#4927]
## Problem statement
Users experience long loading times when loading the details of a submission through the SubmissionDetails page

Ex:

Requests going to https://prime.cdc.gov/api/history/${ORG}/submissions?pagesize=10&cursor=&sort=DESC are taking over 30 seconds. This may be related to the recent "pagination" changes?

Investigate and make recommendations.

## Acceptance criteria
- [ ] When loading the SubmissionsDetails, the user should not have to wait longer than any other RS API call

## To do
- [ ] Investigate issue and share findings with team.

**Comment by rachelhanster** [comment]
@bgantick which tech debt epic do you think this can be associated with?

**Comment by kevinhaube** [comment]
### Notes
- Getting a user's organization takes 11+ seconds
- Loading `/daily-data`'s API response (for `ignore` in staging) took 33+ seconds
