### ISSUE TITLE
CUE - Missing patient name

### ISSUE THREAD

**Issue by brick-green-agile6** [CDCgov/prime-reportstream#4931]
## Problem statement

Some Cue messages sent without patient name.

## What you need to know

Example message IDs:

- `AD7468AC-E404-43B8-B440-719FD852C133`
- `8CA92261-2974-42B6-B9B3-AE827D82BF3`
- `212B182A-09C7-4049-A2A8-9716C545643C`
- `A679DE63-07A2-4A50-BF41-B0AC74BB87CF`
- `D220F12A-F690-4E8A-981C-A0A96B5D4D5E`

**Comment by anshulkumar-usds** [comment]
3/29: Checking with CUE to see if they can start including patient names in their feed.

**Comment by anshulkumar-usds** [comment]
4/6: Broader conversation between Cue and VT taking place on viability of including patient names (and other demographics) in their OTC results. Cue looped in their legal counsel to address VT's concerns. RS standing by.

**Comment by anshulkumar-usds** [comment]
@brick-green-agile6 Do you know if this is still an issue for VT based on recent conversations with them? Can we close this?
