### ISSUE TITLE
[Title] = State the problem.

### ISSUE THREAD

**Issue by JGreenFearless** [CDCgov/prime-reportstream#4932]
_**What is a User Story?**_
A user story is a requirement for any functionality or feature, written down in one or two lines, about one and only one functionality or feature.

_**What is Acceptance Criteria?**_
A set of conditions or business rules, as defined by the Product Owner, which the functionality or feature should satisfy, in order to be accepted by the Product Owner.

### User Story Example:
Use the following template when creating new User Stories/Tickets. Remove/replace any  _italicized_ text.

"As a _[User Persona - who are we building this for?]_
I want to _[Intent - what is this user trying to achieve?]_, 
so that _[Outcome - what is the value add to the user]_."

### Description/Use Case
_Use this section to describe the 'Why', and/or provide an example scenario in which this feature/functionality would be valueable._

### Risks/Impacts/Considerations
_Use this section to briefly list out any risks/impacts that may come about, as a result of the proposed solution._
- _System performance may be slowed_
- _Only a single search parameter can be used_

### Dev Notes:
_Use this section to describe any useful technical information to duplicate an issue or explain requirements related to this ticket without providing implementation details._
- _Provided is the data that was used to replicate the issue..._
- _To test, use SimpleReport upload CSV page to ..._

### Acceptance Criteria
"Given _[describe the precondition]_, when I _[describe the action performed]_, then I expect _[describe the expected outcome]_."

_OR... it may be written as a bulleted list._

- _Time must be displayed as HH:MM:SS_
- _Delivery rate must be shown as a percentage_

**Comment by bishoyayoub** [comment]
@JFU-NAVA-PBC Can you use this template to modify your existing stories?
