### ISSUE TITLE
Receivers: Add paging functionality to list of reporting facilities on daily data report details page

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#4950]
## Problem Statement
As a public health department employee, I want to easily understand who sent in data and associated descriptive metadata.

## Acceptance criteria
- On daily data page, I click an individual report ID, I see list of reporting facilities in a table
- Table is paginated

## Assumptions
- Back end is already done

## Design
- Page design is similar to [senders' submission history](https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=2513%3A22007), with "number of records per page 25 50 100" on the lower left hand side and "previous" "next" on the right hand side.

**Comment by kevinhaube** [comment]
@drew-usds Can we verify a need for this? If not, let me know and this can get closed out.

**Comment by HeatherRienks** [comment]
Per Eng Ticket mtg on 12/16/22 not a priority at the moment.
