### ISSUE TITLE
Codify filter/sort design standards that are flexible to fit any table

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#4970]
## Problem statement

RS has a variety of table views across user types. In general, any of our tables can be sorted, filtered, and paged through. We should have a tighter vision of these features outlined in Figma so we have consistency across or tables.

- Pagination has been covered under #4779

## User story 

As a user, I would like to be able to filter and sort data consistently across tables I encounter on the site. Additionally, if I am working with large table I want to be able to page through the data.

## What you need to know

 We have several different mocked-up versions of pagination and filtering in Figma, plus what has (and will) been deployed on submission history based on feedback from Kevin H.

[Pagination work already done.](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4779)

## Acceptance criteria

- [ ] Filtering options are consistent
- [x] Pagination options are consistent

## To do

- [ ] Survey where designs/linked files differ, and where designs differ within Figma
- [ ] Make Figma updates for consistency
- [ ] Update any relevant Eng tickets with Figma links

**Comment by inkandsound** [comment]
Ticket for receiver detail view design: https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5094

**Comment by drew-usds** [comment]
The pagination part of this [was addressed in #4779](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4779)

**Comment by kevinhaube** [comment]
@drew-usds Closing this out, as we have numbered pagination and date filters in production. Further table updates and improvements can be ticketed and packaged for a next iteration! :)
