### ISSUE TITLE
Make Fake data generator to generate valid phone numbers

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#4975]
Make the Fake data generator to generate valid phone numbers.  Therefore, they will pass the parsePhoneNumber (phone number validation).  For detail of phone validation, see Element.kt:794 - fun parsePhoneNumber(phoneNumber: String): Pair<String?, Phonenumber.PhoneNumber?> {}.

**Comment by Adrian-Brewster** [comment]
No longer needed.
