### ISSUE TITLE
Add Nevada to "where we're live"

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#4983]
## Problem Statement
Nevada is live per [conversation on slack](https://www.slack.com/archives/C01KGBU542K/p1648740599486769). We need to update the ReportStream website accordingly.

## Acceptance Criteria

- SVG map and list show Nevada as "live" on these pages:
  - https://reportstream.cdc.gov/
  - https://reportstream.cdc.gov/how-it-works/where-were-live

**Comment by BerniXiongA6** [comment]
Hi @bgantick per @anshulkumar-usds Nevada is now live with ReportStream ([see thread](https://slack.com/archives/C02HJ43AE8Z/p1649165283460529))!

**Comment by bgantick** [comment]
Already merged (#4984) per the [thread last Thur](https://www.slack.com/archives/C02HJ43AE8Z/p1648742504150269)
