### ISSUE TITLE
MA - Invalid LOINC

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#4986]
**Describe the bug**
MA received a new LOINC code that they were not expecting from Sumas Drug who was the ordering provider and also the lab facility.  They wanted to see if we could clarify with them or please send us their contact information so that we can see if they meant to send this test, which “detects but does not differentiate between SARS-CoV and SARS-CoV-2” or if they accidentally selected this option.
 
The MSH.10 IDs in question are:
`d523819b-67dd-46e0-b74e-57c4d28dcdb0`
`d23b1c7c-cfb3-49ce-bba2-40185b2657a2`
 
The test in quest was:
95209-3 - SARS-CoV+SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay

**Comment by oslynn** [comment]
@jorg3lopez got data files from Azure inbound for me.  I will start working on this in parallel with ticket 4990.

**Comment by oslynn** [comment]
@Adrian-Brewster @sarahnw , @jorg3lopez and I verified the LOINC code is in the LIVID table in the database.  Please provide the contact information to MA to get with Sumas Drug provider.  And, let MA provide the update of the outcome.  Therefore, we can take action on what they what us to do with the message.

**Comment by Adrian-Brewster** [comment]
Sender is part of Prescryptive.  CC'd John at Prescryptive to get this sorted.

**Comment by Adrian-Brewster** [comment]
Yup! We are all set here @anshulkumar-usds I just forgot to close the ticket.
