### ISSUE TITLE
Research/Design Documentation and Synthesis - CSV Upload Pilot

### ISSUE THREAD

**Issue by inkandsound** [CDCgov/prime-reportstream#4987]
## Problem statement

Since ReportStream is no longer going to be handling CSV uploaders, we need to make our research and design work easily digestible by the SimpleReport team so they can don't have to duplicate any work that's already been done and are able to easily build off of our work. 

## Acceptance criteria

- [x] Provide clean Figma files with brief explanations of design decisions
- [x] Link to closed GH issues of future product ideas
- [ ] Synthesize research and provide research repository
- [ ] List participants in CSV upload pilot and research so we can transition relationships

**Comment by drew-usds** [comment]
Epics/closed issues that might be handy to hand off:
- [2954](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/2954)

**Comment by inkandsound** [comment]
Cleaned CSV upload Figma files that can be handed to SR team: https://www.figma.com/file/7D1gikrgQiRCf24ihuuZ9I/ReportStream---CSV-Uploader?node-id=0%3A1

**Comment by victorialb-usds** [comment]
invited SR to attend final check ins to hand off relationship. Need to get some agreed upon language on transition in order to communicate with folks on this call about the transition.

**Comment by victorialb-usds** [comment]
As of now @drew-usds @a-chappelear @BerniXiongA6 time is tomorrow 1 - 130. Could not find a full hour. But perhaps we might schedule other time or use part of sync agenda going forward?

**Comment by drew-usds** [comment]
@victorialb-usds and I to get on a Zoom and close this out in an hour or less.

**Comment by victorialb-usds** [comment]
@drew-usds I created a folder where we can make copies of everything to hand off in pilot folder

**Comment by victorialb-usds** [comment]
@drew-usds I created a folder where we can make copies of everything to hand off in pilot folder

**Comment by victorialb-usds** [comment]
We can then link to it https://cdc.sharepoint.com/:w:/t/USDSatCDC/EZPs906A_VlHreQdunv0NSoBI7Kxo3_bmn8DJD2AKQ_QeQ?e=JwyL2A
