### ISSUE TITLE
Investigation Needed: April 2 PageDuty Alert

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#4993]
**Description**
Rick Hawes received a "Found FATAL-ALERT in FunctionApp logs" through the escalation path. After looking at dashboards, the system appeared to be operating nominally and the need to open an incident was determined to be not needed. 

See: [PageDuty Incident #3873](https://prime-cdc.pagerduty.com/incidents/Q2HPUNXCM5BJ9X) for the reports

**Expected Outcomes**
We should not have a system with false alerts. It hampers readiness for real alerts. The incident should be investigated during business hours. After determining the cause, either 1) the alert rule is fixed to not trigger and escalate, or 2) the code is changed to not place a false FATAL alert into the logs. 

**Additional Context**
@rhood23699 There is this clue in the logs. Apparently, co-phd.elr-test is known to produce a false "FATAL-ALERT" 

""// 2022-03-31: Exclude co-phd.elr-test -- this is a known error per Rick Hood\nFunctionAppLogs\n| where Message contains 'FATAL-ALERT' and not(Message contains 'co-phd.elr-test')"

**Comment by cwinters-usds** [comment]
A couple notes about this:

* The PagerDuty alert that prompted this resulted from an issue with the receiver `oh-doh.elr` so the item in this issue around `co-phd.elr-test` doesn't apply.
* When we originally created this alert (based on https://github.com/cdcgov/prime-reportstream/issues/4712) the idea was that the backend could issue a logging message with a particular string to trigger a PagerDuty alert.

I think the problem this investigation request points out is the need for another channel for the application to reach out to humans, one that's *not* going to wake somebody up. I'll see if we can create a separate schedule that only notifies during business hours.

**Comment by cwinters-usds** [comment]
This should be taken care of now. For production there's a new PagerDuty Service (ReportStream Production Business Hours) with the same group of people as the standard Production service but the escalation policy is limited to 7 AM - 6 PM. It should still publish to #prime-reportstream-prod-pagerduty for viewing there.
