### ISSUE TITLE
Verify all current alerts are defined in Terraform

### ISSUE THREAD

**Issue by acoushawk** [CDCgov/prime-reportstream#5006]

**Comment by lucasdze** [comment]
Here is (https://icfonline-my.sharepoint.com/:x:/r/personal/58917_icf_com/Documents/Azure-Monitor-Alerts-Rules%20(2).xlsx?d=w80c5914ba6ea473da2430a7c1c639eb8&csf=1&web=1&e=8wZl15) the list of all Alerts currently running in Azure. Now checking if they are all defined in terraform or not.

**Comment by lucasdze** [comment]
This Alert list is now updated and I created separated ticket to follow up with alerts that aren't configure via terraform 
https://icfonline-my.sharepoint.com/:x:/r/personal/58917_icf_com/_layouts/15/Doc.aspx?sourcedoc=%7B80C5914B-A6EA-473D-A243-0A7C1C639EB8%7D&file=Azure-Monitor-Alerts-Rules%20(2).xlsx&action=default&mobileredirect=true&cid=6ed14a71-f9b6-4b4c-ade5-a358cad8fbeb
