### ISSUE TITLE
Create document for creating/testing/deploying a new alert

### ISSUE THREAD

**Issue by acoushawk** [CDCgov/prime-reportstream#5007]
Create a doc in the "How To" section in sharepoint on how to create alerts in Azure that talk to Slack.

**Comment by lucasdze** [comment]
See the document [here](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B50C341F6-CCA0-44A9-B277-618FF18153AC%7D&file=Azure-Alert-Creation-Steps.docx&action=default&mobileredirect=true)
