### ISSUE TITLE
Create Content for NIH website

### ISSUE THREAD

**Issue by kjt9cc** [CDCgov/prime-reportstream#5011]
https://www.nibib.nih.gov/aphl-workflow

Our friends at NIH who are promoting the OTC HL7 spec have offered to give us a content section on their website. 

https://www.nibib.nih.gov/standardized-reporting-covid-self-test-results.

We can have our own menu item on the left navigation bar. Similar content to this: https://www.nibib.nih.gov/aphl-workflow
We want to explain what ReportStream is, who makes it, that its an option for sending OTC data, how it works, that its free, what the limitations are, and a call to action: how to get started.

**Comment by rachelhanster** [comment]
Closing ticket as it's now an epic.
