### ISSUE TITLE
Design and Content: NIH website, Reportstream page

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#5013]
## Problem Statement
As ReportStream organization, we want to increase our outreach to potential senders so that they become aware of our Products and Services when they're visiting other government agency websites.

## What you need to know
-  Our friends at NIH who are promoting the OTC HL7 spec have offered to give us a content section on their website. https://www.nibib.nih.gov/standardized-reporting-covid-self-test-results.
- We can have our own menu item on the left navigation bar. Similar content to this: https://www.nibib.nih.gov/aphl-workflow
- ([This came from Kevin Thomas ticket #5011](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5011))
- This is the original ask from Rick Hawes: https://app.zenhub.com/workspaces/prime-reportstream-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/4598

## Things to consider

1. ReportStream Overview content ideas:
- Why: Why it was created, why a user would use it, why it's an option for sending OTC data
- What: What it actually is, what it does, what it's not/limitations
- How: How it works
- Where: Where to find it
- Who: Who ReportStream is, Who makes it
- Call to action: how to get started

2. Graphics ideas:
- Diagram that shows ReportStream's architecture from a high-level

**Comment by BerniXiongA6** [comment]
Updated the details and AC. We can size if other designers think it's ready!

**Comment by HeatherRienks** [comment]
@BerniXiongA6 - I don't believe there is any existing work to be done here. If there anything you are aware of that is outstanding?

**Comment by BerniXiongA6** [comment]
Outstanding work is changing “COVID-19” references to more general “reportable diseases” verbiage instead. And if there are any updated metrics to the info we’ve last provided them!

**Comment by kevinhaube** [comment]
Old and closing! New work can be ticketed and tagged accordingly.
