### ISSUE TITLE
Okta Preview migration cleanup

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#5032]
Some steps remain as part of this effort: https://github.com/CDCgov/prime-reportstream/issues/3891

We were waiting due to the possibility of yet another migration to a separate ReportStream instance, but this is off the table for now.

- [ ] Audit/remove/lower access to Okta production to a smaller set of folks.
- [ ] Remove Okta Prime (test) app from production.
- [ ] Any approve urls that may have snuck into Okta Prime app
- [ ] Verify Trusted Origin in app
- [ ] Remove unused Okta Trusted Origins [On Okta site: admin/access/api/trusted_origins]
- [ ] Verify Security -> API list [On Okta site: admin/oauth2/as]
- [ ] Remove our own members from groups like all_in-one
- [ ] CSP header remove https://hhs-prime.okta.com

**Comment by rachelhanster** [comment]
Keep in "new items" until decision is made on whether reportstream moves to new okta domain

**Comment by doug-s-nava** [comment]
Unclear if this still needs to be done, but much of it seems to have been done. Would love to prioritize looking at this to gauge the current situation

**Comment by kevinhaube** [comment]
This was completed but not logged. Closing!
