### ISSUE TITLE
Validate java function app deployment and managed identity connectivity

### ISSUE THREAD

**Issue by JosiahSiegel** [CDCgov/prime-reportstream#5034]
**Description**
[Daniel Paseltiner](https://app.slack.com/team/U0315K0CJ2J)  [9:18 AM](https://semanticbits.slack.com/archives/C02TRFPBFJN/p1649164692494479)
Hi [@Josiah Siegel](https://semanticbits.slack.com/team/U02E1BY11RP) and [@Chris Winters](https://semanticbits.slack.com/team/U025P0DALSE), I’m having trouble still deploying our Java runtime function app to pitest-java-functionapp. After zipping /src/FunctionAppsDSTP from the repo I have run az functionapp deployment source config-zip --resource-group prime-ingestion-test  --name pitest-java-functionapp --src DSTP.zip , but get a 202 response with the following:
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...

**Comment by JosiahSiegel** [comment]
[PR](https://github.com/CDCgov/prime-public-health-data-infrastructure/pull/75) that deploys a java function app that validates managed identity connectivity.

**Comment by JosiahSiegel** [comment]
[Josiah Siegel](https://app.slack.com/team/U02E1BY11RP)  [2 hours ago](https://semanticbits.slack.com/archives/C02TRFPBFJN/p1649249798182789?thread_ts=1649164692.494479&cid=C02TRFPBFJN)
[@Dan Paseltiner (PWM he/him)](https://semanticbits.slack.com/team/U0315K0CJ2J) Working/deployed test Java function app with managed identity auth [here](https://github.com/CDCgov/prime-public-health-data-infrastructure/blob/josiahsiegel/deploy-java-app/src/FunctionApps/TestJava/src/main/java/com/function/Function.java)
This is the [PR](https://github.com/CDCgov/prime-public-health-data-infrastructure/pull/75) to merge in this test app. We don't need to always deploy it, but it's nice to have it wired up to see a working sample.

[Daniel Paseltiner](https://app.slack.com/team/U0315K0CJ2J)  [1 hour ago](https://semanticbits.slack.com/archives/C02TRFPBFJN/p1649250700776039?thread_ts=1649164692.494479&cid=C02TRFPBFJN)
[@Josiah Siegel](https://semanticbits.slack.com/team/U02E1BY11RP) thanks for this. I think the challenge we are having is that the current function we are trying to deploy is a BlobTrigger which requires the connection to a storage account to be provided as an argument of run before any other code is executed. I’ll discuss converting the current function to an HttpTrigger with the team. ([@Graham Smith (PHL, he/him)](https://semanticbits.slack.com/team/U031BSS6S7M) for visibility based on our conversation yesterday)

[Josiah Siegel](https://app.slack.com/team/U02E1BY11RP)  [1 hour ago](https://semanticbits.slack.com/archives/C02TRFPBFJN/p1649250746624289?thread_ts=1649164692.494479&cid=C02TRFPBFJN)
you should be able to do the same with BlobTrigger. I'll see about having an example put up

**Comment by JosiahSiegel** [comment]
[Josiah Siegel](https://app.slack.com/team/U02E1BY11RP)  [1 minute ago](https://semanticbits.slack.com/archives/C02TRFPBFJN/p1649269299864989?thread_ts=1649164692.494479&cid=C02TRFPBFJN)
[@Dan Paseltiner (PWM he/him)](https://semanticbits.slack.com/team/U0315K0CJ2J) [@Graham Smith (PHL, he/him)](https://semanticbits.slack.com/team/U031BSS6S7M) Added a test Java blob trigger w/managed identity function to this [PR](https://github.com/CDCgov/prime-public-health-data-infrastructure/pull/75/files#diff-13f8d90368098e676a0f45f329867684d7c9ee90d3df22e014807a5fc67761d8)[](https://files.slack.com/files-pri/T040Y0HTW-F03AB2H5LS1/untitled.png)[](https://files.slack.com/files-pri/T040Y0HTW-F03AB2H5LS1/download/untitled.png?origin_team=T040Y0HTW).
Validated it picked up the file change:
![Untitled](https://user-images.githubusercontent.com/5522990/162042708-4e647a24-19b5-4db9-8c59-568bdb2e9146.png)

**Comment by cwinters-usds** [comment]
@JosiahSiegel this looks to be done, ok to close?

**Comment by JosiahSiegel** [comment]
No. Data ingest team did not approve my PR for this for the original example function. I am now working on the in-depth function  fixes and doc to add to this same PR

**Comment by cwinters-usds** [comment]
Ah gotcha, I didn't get that from the context, my bad. Thanks.

**Comment by JosiahSiegel** [comment]
[PR](https://github.com/CDCgov/prime-public-health-data-infrastructure/pull/75) is merged and issue is complete. 🥳
