### ISSUE TITLE
NJ - OBX-11 missing from files for NJ

### ISSUE THREAD

**Issue by sarahnw** [CDCgov/prime-reportstream#5044]
OBX-11 missing from files starting 4/5/22

Example messages for reference:
File ID: 4453332
Message(s) within the file "CDC_PRIME_covid-19-6a4dc618-d345-4869-9492-dc217a2c7f13-20220406131630.hl7" were in error on route (2) ELR-Validate 2.5.1
Sender	Message Control ID	Location of Error in Message	Error Description
CDC PRIME - Atlanta,	`b71f82f6-2c8c-451c-bed0-bfdf08a7ca90`	PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[1].OBX.ObservationResultStatus	Required field missing
CDC PRIME - Atlanta,	`b71f82f6-2c8c-451c-bed0-bfdf08a7ca90`	PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[2].OBX.ObservationResultStatus	Required field missing
CDC PRIME - Atlanta,	`b71f82f6-2c8c-451c-bed0-bfdf08a7ca90`	PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[3].OBX.ObservationResultStatus	Required field missing
CDC PRIME - Atlanta,	`b71f82f6-2c8c-451c-bed0-bfdf08a7ca90`	PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[4].OBX.ObservationResultStatus	Required field missing
CDC PRIME - Atlanta,	`a99b77b8-3c47-4ce8-86a1-42259ff2f0f8`	PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[1].OBX.ObservationResultStatus	Required field missing

Let me know if you need more and I'll figure out how to attach the emails/content of.

Once corrected we'll need to resend. Please let me know if there's any other information needed. We'll also use this email to track follow up.

**Comment by oslynn** [comment]
@sarahnw is this ticket for NJ and MA?

**Comment by brick-green-agile6** [comment]
just transferred file - there were 100 records with missing OBX-11
