### ISSUE TITLE
MA - OBX-11 missing from MA files

### ISSUE THREAD

**Issue by sarahnw** [CDCgov/prime-reportstream#5045]
In today's 4/6 file there were 41 messages with errors caused by missing Observation Result Status (OBX.11) values. OBX.11 is a required field. 

Please review this issue, and resubmit if possible. Included is an example message for reference. Please let me or @Adrian-Brewster  know if you would like the full list of 41 messages.

MSH.10
```0eb7b439-1f45-4d8d-ac58-c921c13f55b9```

We'll use this ticket to track follow up comms too.

**Comment by oslynn** [comment]
This is the same as the ticket 5044 findings.

**Comment by brick-green-agile6** [comment]
Just transferred the file - 41 results included
