### ISSUE TITLE
API Onboarding Process Improvements

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#5047]
This is an epic to capture ideas and work needed to make refinements and improvements to our current API onboarding process. The O&O team has created service workflow to map the existing process as of 3/31/2022 here: https://lucid.app/lucidchart/1bb900ca-6a0e-41d1-9c86-d3529ea7e7fc/edit?invitationId=inv_e94a833a-e5a3-4784-96aa-23973f487065&page=0_0#

### Proposed Ideas based on onboarding stage:

- **Communication**
  - During kickoff, set clear expectations with sender on onboarding timelines. Some senders are very slow or ghost us after kickoff. If a sender commits to onboarding with us, the expectation should be that both parties will complete onboarding within X-number of weeks. (X could 2 or 3 weeks based on our existing capacity). The sender is expected to be responsive in the process. 
- **Process Improvements and Better Tooling**
  - Develop a self-serviceable data validation: Prior to kick-off, the sender should utilize a CDC/NIH tool to validate CSV or HL7 data to get a better understanding of their existing setup, and assess their readiness to onboard with ReportStream. The tool should provide enough guidance to a prospective sender to improve the data quality prior to onboarding. The tool does not need to get us 100% with data quality, but should be a good start.
  - Terms of Service: Make it a pre-requisite for the sender to provide their consent to our ToS prior to kickoff. This reduces a dependency once technical implementation kicks-off.

### Other considerations and Questions

- Do we need onboard a sender to staging? What value does it really provide?
  - After onboarding a sender in staging, we promote them to 'testing-in-production- stage where they send us real/PII data that does not reach states. What is we started with this step?
  - There are good reasons for onboarding senders to Staging first to understand their payload (i.e. large test manufs.); However, for the the smaller API senders we're getting now, the need is less obvious.

- What if we onboard a sender directly to 'testing-in-prod' mode?
  - This shortens the overall time needed for onboarding
  - Fewer keys and endpoints to share with senders over keybase
  - We can contact states earlier (right after kickoff) and alert them of a prospective sender so testing with states begin earlier.

### ReportStream Onboarding Sandbox
- Under active discussions with Experience Team

**Comment by anshulkumar-usds** [comment]
@jbiskie @rhood23699 @sarahnw @Adrian-Brewster Above is a placeholder for now just to capture our recent discussions. Most of this is translatable into process enhancements, not necessarily as a feature-set improvement to our software. However, making these change MAY results in a shortened onboarding timeline and a better experience for our senders. 

Please share any thoughts, suggestions you have. We can start adding tickets under the epic soon.

cc @MauriceReeves-usds @kjt9cc

**Comment by sarahnw** [comment]
can't figure out how to turn this into a ticket from an epic so closing and moving here https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/6435
