### ISSUE TITLE
Receiver wireframing and research re: facility data and summary stats

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#5049]
## Problem statement

[Write a short description of what you want to achieve with this task]

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by rachelhanster** [comment]
@drew-usds Can the team get more detailed info on this initiative?

**Comment by HeatherRienks** [comment]
@drew-usds - please provide more info on this ticket. Thanks!
cc: @RakshindaAslam

**Comment by HeatherRienks** [comment]
@drew-usds - please update per 7/11/22 meeting.

**Comment by HeatherRienks** [comment]
@RakshindaAslam - pls provide info on if we should keep this open or if this work is now encompassed in another ticket? 
cc: @drew-usds, @a-chappelear

**Comment by HeatherRienks** [comment]
@drew-usds - Do we need this ticket?

**Comment by drew-usds** [comment]
Closing. Will turn this into individual tickets.
