### ISSUE TITLE
A submission by a full ELR sender gets a return json response from the API

### ISSUE THREAD

**Issue by clediggins-usds** [CDCgov/prime-reportstream#5052]
### User Story:
As a sender, I want to receive a response from the API when I submit a report, so I can know if the submission was successful.

### Description/Use Case
A sender needs to receive a structured json response to their submission, including a report ID and other relevant data.

### Risks/Impacts/Considerations
* Following the existing json response structure may result in many empty fields
* Creating a new response structure may result in downstream effects from existing senders that want to switch to full ELR

### Dev Notes:
* The response should have all/most populated fields as compared to a COVID Async response.
* Only the async method of submission will be used for full ELR senders.
* Need to generate response using existing structure and methods use to generated the COVID response.
* If the structure of the response is not going to be matching the existing response structure, this needs to be discussed with the team

### Acceptance Criteria
* The reports/waters API returns a JSON response with a report ID if the report was accepted/validated.
* The reports/waters API returns a JSON response without a report ID if the report was not accepted.
* The reports/waters API JSON response has similar data to a COVID async response.
* The reports/waters API returns a JSON response which must contain a submission ID.

**Comment by JGreenFearless** [comment]
All AC met accordingly.
