### ISSUE TITLE
Submitted HL7 full ELR reports are validated as HL7 batch or messages

### ISSUE THREAD

**Issue by clediggins-usds** [CDCgov/prime-reportstream#5053]
### User Story:
As ReportStream, I want to validate incoming HL7 full ELR reports, so I it can be determined if they are valid HL7 reports.

### Description/Use Case
We need to validate the incoming payload submitted by a sender to ensure it is a valid HL7 batch or message.  This will also result in rejection of the report if it does not pass the validation.  Note that more detailed validation could be added in the future.

### Risks/Impacts/Considerations
* If we do not validate the incoming files, they may cause errors downstream

### Dev Notes:
* Use the HAPI HL7 library functionality to validate the structure of incoming files
* We will have to use this same initial validation in the HL7 parsing portion too.

### Acceptance Criteria
* The reports/waters API returns a successful response if the HL7 payload is validated.
* The reports/waters API returns a BAD_REQUEST response if the HL7 payload is invalid.
* The reports/waters API returns errors as part of the JSON response when an HL7 payload is invalid (similar of how it is done with COVID).

**Comment by JGreenFearless** [comment]
All AC met accordingly.
