### ISSUE TITLE
Logout timer: direct users to /login, let them know they timed out

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#5056]
## Problem statement

When a user is inactive for >15 mins, they will be logged out of the application. This is a security feature that we have to keep.

When a user is logged out, however, it directs back to the RS homepage without indication of what has happened.

## What you need to know

As a user, I'd like to understand why I have been logged out automatically.

## Acceptance criteria

- [ ] When a user has been inactive for > 15 mins, they are logged out
- [ ] The user is directed to the `/log-in` page
- [ ] The `/log-in` page has an alert that notifies them that they have been logged out due to x mins of inactivity (and to log in again).

## To do

- [ ] ...

**Comment by kevinhaube** [comment]
@drew-usds Saw a few tickets about this same UX, and different parts of it, so check out #7610
