### ISSUE TITLE
MN: Missing OBX-11 field and question about production status

### ISSUE THREAD

**Issue by sarahnw** [CDCgov/prime-reportstream#5059]
Could someone confirm that the OBX-11 issue we've seen starting 4/5 applies here and also check the question MN has below:

We received about 10 messages with a processing ID of P (for production), in an SFTP folder that indicates “ /home/usdsprime_testonly/PROD” Can you confirm if these are true production messages or if these are test messages that you are finessing a system change with? If these are to be going to PROD, we might want to look into changing the directory path so the production messages to indicate “_testonly” and so we don’t have issues in the future. We would also need the 10 messages resent as they are failing due to the OBX.11 not being filled in on the ask on order entry questions sent within the message. This field is required by HL7 to be filled in for ELR messages.
ID: 9cda867-6346-4e9b-963f-c6d1427242d9

ID: `2254957-7475-493f-8e9d-966ee5c9e32f`; `f4041099-cb2e-47a1-9f9c-c243e2a3c262`; `d03d497e-3385-483a-9fac-84a625aac09e`; `356273bc-a0f8-4037-b320-f2d010e4be7c`; `cde1f4da-fe78-4f73-9ef1-f1ebb2eab05e`; `e37d092a-3893-46d9-a6d8-c097ac5b0cba`; `93ed8e9c-8f68-4f9b-b0b9-65d86fbf9e38`; `469ab262-fd64-4b1d-afbd-71a87a90ae89`; `c9cda867-6346-4e9b-963f-c6d1427242d9`

**Comment by oslynn** [comment]
Checking 2022-04-07 @ 2:30pm CST. @sarahnw, there is no result for the message_id=9cda867-6346-4e9b-963f-c6d1427242d9 in production database.  This must be the test message.

**Comment by oslynn** [comment]
This is the same as the ticket 5044 finding.

**Comment by brick-green-agile6** [comment]
I can't find that message nor can I find any file that was transferred to /home/usdsprime_testonly/PROD. 

@sarahnw Can we request the remaining message control IDs and the filename from MN?

**Comment by brick-green-agile6** [comment]
Oh also, this ticket is marked at MD in the title but looks like it should be for MN

**Comment by sarahnw** [comment]
@brick-green-agile6 good catch - @Adrian-Brewster also confirmed it's MN. Ann Kayser reached out to him directly so we'll follow up for more info.

**Comment by sarahnw** [comment]
@brick-green-agile6 here are the other message ids (I'll also update the description)

ID: 2254957-7475-493f-8e9d-966ee5c9e32f; f4041099-cb2e-47a1-9f9c-c243e2a3c262; d03d497e-3385-483a-9fac-84a625aac09e; 356273bc-a0f8-4037-b320-f2d010e4be7c; cde1f4da-fe78-4f73-9ef1-f1ebb2eab05e; e37d092a-3893-46d9-a6d8-c097ac5b0cba; 93ed8e9c-8f68-4f9b-b0b9-65d86fbf9e38; 469ab262-fd64-4b1d-afbd-71a87a90ae89; c9cda867-6346-4e9b-963f-c6d1427242d9

**Comment by brick-green-agile6** [comment]
I found the file and all 10 of the messages are there.
Filename: covid-19-0cc99552-5b06-4834-832c-fdc9db0a0aa1-20220406131556.hl7

Our records show the file was transferred to "./PROD". I tried logging in to their SFTP server and our credentials only allow us to see and /TEST and /PROD folder. So I don't know what the parent folders are. That being said, the username that we are currently using is "usdsprime_testonly". So that seems to align with what MN is seeing. We are sending all data to the same location though so this file was no different than any other.Also, this file has 28 total message. There are the 10 with missing OBX-11 plus an additional 18 other messages that are not missing OBX-11. Did MN receive those results into their prod system?

**Comment by Adrian-Brewster** [comment]
Ann responded and said the connection piece sounds right and its likely just the way the folder was set up initially.  

We can just resend the 10 messages without OBX11 and we are good to go. @brick-green-agile6

**Comment by brick-green-agile6** [comment]
Just fixed the file and sent it over

**Comment by brick-green-agile6** [comment]
just sent the new file with /r as the line endings

**Comment by brick-green-agile6** [comment]
no word for a month, think it's safe to close
