### ISSUE TITLE
MA - Missing ORC21 message

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#5060]
**Describe the bug**
There was one message that errored out in the file received on 3/30/2022.  The error was caused by missing Ordering Facility Name in ORC.21, and Result Rpt/Staus Chng – Date/Time in OBR.22. Please review, edit, and resubmit as necessary.

 

Message ID: `dd88b7a2-bb29-4510-8654-fe518965f0b4`

Sample: 1000560627

 

Error: Expected Required field Organization Name (ORC.21.XON.1 of type ST) is not found.

Error: Ordering Facility Name (ORC.21 of type ORC.21.XON.T) value is invalid.

 

Error: Expected Required field Results Rpt/Status Chng - Date/Time + (OBR.22 of type OBR.22.TS_CMP) is not found.

**Comment by oslynn** [comment]
The file associate with the message Id is no longer in Azure Storage
Using ./prime sender-files command got error:
./prime sender-files --env prod --message-id dd88b7a2-bb29-4510-8654-fe518965f0b4 -o ./junk/ticket5060
Exception Error:         Error using the report-files API
        Status Code: 503
        Message: Service Unavailable
        Details: <!DOCTYPE html>
<html lang=“en”>
<head>
 <meta charset=“utf-8"/>
 <title>CDC Test Page</title>
 <link rel=“stylesheet” href=“/apology_files/style.css”>
</head>
<body>
<h1>Centers for Disease Control and Prevention</h1>
<h2>Test Page</h2>
<p>This is a test page for prime.cdc.gov.</p>
<p>This page will appear if an error or timeout occurs at origin.</p>
<p><span>Reference ID: </span></p>
</body></html>
-----
I also login into the Azure Storage and search for the file listing in database: https://pdhprodstorageaccount.blob.core.windows.net/reports/receive%2Fprescryptive.default%2Fprescryptive-covid-19-10a3e22a-cadc-40e6-b0f7-c4fc4932094d-20220329152224.hl7.  I can't find it either.  Therefore, I will close this ticket.
