### ISSUE TITLE
CO - No Observation Identifier

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#5062]
**Describe the bug**

Issue Report: The record submitted has no observation identifiers. 
Every record submitted must have at least one observation identifier recognized as valid by CDPHE ELR. (For HL7-formatted files, the lab result must be uniquely identified as a LOINC code in OBX 3.1 in the Order Observation group.)

Common causes for a missing or invalid observation identifier:
 - For HL7 files, the record is missing an OBX segment or is missing a value in OBX 3.1, or the OBX 3.1 value provided is not recognized by CDPHE ELR (i.e., is not a recognized LOINC).
 - For flat files, the record contains an escaped (\) character, or the fields in the message do not match Colorado's standard flat file format.

Message ID: `1dfd2f77-6a65-4911-bfac-5956d95016b2`
Received by: CDPHE ELR Onboarding
Received on: 2022-03-30 19:30:33
File source: CDC PRIME
File name: 14389031_hl7.txt

**Comment by jorg3lopez** [comment]
@anshulkumar-usds @Adrian-Brewster We need to reach out to CO and ask what the issue is because the LOINC codes that the message has are all valid. 
[Uploading... image.png]

**Comment by anshulkumar-usds** [comment]
@Adrian-Brewster I'm not able to find this email from CO in my or shared inbox. If you have it, can you please clarify what is needed from them?

**Comment by oslynn** [comment]
The file associate with the message Id is no longer in Azure Storage
Using ./prime sender-files command got error:
./prime sender-files --env prod --message-id 1dfd2f77-6a65-4911-bfac-5956d95016b2 -o ./junk/ticket5060
Exception Error: Error using the report-files API
Status Code: 503
Message: Service Unavailable

I also login into the Azure Storage and search for the file listing in database:
