### ISSUE TITLE
HL7 Compare utility compares individual HCA HL7 messages for the same patient record in an HL7 batch message

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#5068]
### User Story:
As a developer, I want to be able to compare HCA messages from what HCA is expected us to generated to what HCA generates, so I can verify that our conversion process works.

### Description/Use Case
We are going to receive both unprocessed and processed HL7 messages from HCA.  The unprocessed messages are the raw messages we will process through our new pipeline to convert to FHIR and then convert back to a STLT specific HL7.  This STLT specific HL7 needs to compared to the HCA processed message HCA will send us, so we can verify our conversion outputs the same data as HCA.  The trick here is that these HL7 batch messages may contain multiple HL7 messages in a random order and the compare utility must find the proper HL7 messages to compare and then tell us if the HL7 batch message is what HCA is expecting.

### Risks/Impacts/Considerations
* May be hard to identify HL7 messages if any of the HL7 reports HCA send us do not have enough data.  Normally they have some ID and must have at least patient name, so this may be enough, but the utility could fail if we cannot identify the data.
* The data from HCA is test data, we need to ensure that this functionality never exposes real PII in the future

### Dev Notes:
* Extend the existing HL7 compare utility.  This means do not break the existing compares, which are done in the integration test suite.
* the HL7 compare utility already has code to match messages, so perhaps there is no work to be done here.  You will need to look at the reports HCA sends to make sure they have enough information for this.

### Acceptance Criteria
* The HL7 compare utility is able to compare two sample HCA HL7 batch messages with HL7 messages in random order.

**Comment by carlosfelix2** [comment]
Test file for PR: 
[sample_hl7.txt](https://github.com/CDCgov/prime-reportstream/files/8743167/sample_hl7.txt)

**Comment by JGreenFearless** [comment]
All AC met accordingly.
