### ISSUE TITLE
Santa Clara County Public Health - Lost access to download site

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#5069]
**Describe the bug**
Elaine Li at Santa Clara County lost access to the download site. When sent a password reset link, the issue continued to occur.  

![image.png](https://images.zenhubusercontent.com/60d1eba7caf0775fd79203f8/a57dc23c-6b4a-49a2-a09e-543fbf3464c2)

**Comment by rhood23699** [comment]
@Adrian-Brewster @MauriceReeves-usds  This is not the issue with a user assigned to two groups.  The user is in the group DHca_scc_phd and the ReportStream app is assigned to the user.  I'm not sure if this should be reported to the Experience Team or SimpleReport support.
