### ISSUE TITLE
NC - Setup Download Site

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#5073]
While discussions between CDC and NC-DOH are ongoing about which connection method will be best suited to setup an ELR connection, NC has requested that we provide them with all testing data currently in ReportStream that is meant for their jurisdiction: Patient State or Ordering Facility State = NC

Hence, we need to setup a download site for NC - just one (primary) feed that shows them everything flowing through RS for NC. The following person should be granted access to this site:

patricia.rago@dhhs.nc.gov (Patricia Rago)

**Comment by sarahnw** [comment]
@sarahnw look into shared inbox and see if this is still needed

**Comment by sarahnw** [comment]
I emailed Patricia 8/19/22. Will reopen should she request this again.
