### ISSUE TITLE
[Bug] Downloading Daily Data file doesn't warn about PII

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#5075]
Steps:
1. Log in as an organization that uploads csv files.
2. Go to Daily Data
3. Click link to download to download that organization's csv file.
Result: File containing PII is downloaded.
NOTE: This is PII that that organization owns, but there still be a warning/disclaimer.

This process should include an interstitial page warning the user they are about to download a file containing PII and that it should be handled appropriately (encrypted at rest, not forwarded, deleted when done) and they should be authorized to handle such data.

The exact text displayed should be discussed and refined by subject matter experts.

![Example screenshot](https://user-images.githubusercontent.com/74203452/162489874-3d8b5c8a-d8c3-49e7-99aa-9848d77d3f18.png)

[Reference to USWDS guideline for how to use links](https://designsystem.digital.gov/components/link/#:~:text=Component%20code-,Guidance,-Overview)

**Comment by rachelhanster** [comment]
@TomNUSDS I assume you mean download page as daily-data page. Is a reporting facility/sender currently able to access the daily-data page? By design, only public health authority employees are able to access daily-data page; an uploader isn't able to access said page.

**Comment by TomNUSDS** [comment]
I updated the description to include a screenshot. It has design implications. @drew-usds

**Comment by rachelhanster** [comment]
Thanks for the screenshot @TomNUSDS. 
However, I can't replicate what you are seeing. "Log in as an organization that uploads csv files." Do you mean logged in as an organization that _gets_ data via csv files? By design, only public health authority employees are able to access daily-data page; an organization that uploads data isn't able to access said page. I want to make sure that this is definitely still the case.

Meanwhile, we'll look into public health authorities' daily-data page. Thanks for catching that!

**Comment by TomNUSDS** [comment]
Maybe I'm confused because I'm using as an Admin? Please fix my steps by editing the issue if they aren't right.

The core issue is that _any_ action that allows _any user_ (including admins) to download data that contains PII should include a warning and disclaimer in a dialog/interstitial and allow them to reconsider the action.

We should craft the text for this warning text to include guidelines for how to properly handle PII. It will probably include:
 - Only accessing from an agency or organization computer that's encrypted and fully security patched. 
 - Securely deleting files after use (don't leave around on the machine).
 - Person is authorized and takes responsibility to correctly handle PII.
 
I suspect there's probably some boilerplate messaging somewhere?

**Comment by rachelhanster** [comment]
Checking in with product/legal expertise on requirement rules vs best practice norms related to CDC-products

**Comment by rachelhanster** [comment]
I'll continue to follow up with legal expert on this topic

**Comment by drew-usds** [comment]
@rachelhanster @TomNUSDS +100 to ongoing legal advice ... but ... unless things have changed, we should be covered by what we currently have in place. For background -- legal efforts were put in to the following to make sure we were meeting requirements:

- Keeping the terms of service up to date
- Adding the below boilerplate language to both `/daily-data` as well as on individual detail views.
> Data aggregated with ReportStream may be subject to the Privacy Act of 1974, the Health Insurance Portability and Accountability Act of 1996 (HIPAA), and other laws, and requires special safeguarding.

For your other bullet points in the screengrab:

- We tested with users and they understood it was a link to download the file. Always worth continuing to check in on though.
- There are some other performance improvements in progress, right? Would any of those make the download move faster, or is that something we should write out another ticket for?

**Comment by RakshindaAslam** [comment]
Per legal advice, no additional language is required on the RS UI for the end-user(STLTs). New team members to reportstream need to be advised that some of them may get access to PII data and need to be trained on the protocol to be followed.

**Comment by TomNUSDS** [comment]
Thanks for investigating and clarifying!
