### ISSUE TITLE
API sender: homepage and deep dive content

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#5076]
## Problem statement

As an API user, when I arrive at the public-facing ReportStream website I want to see information that's relevant to my role as a person who is sending test results data reporting to my public health department.

## What you need to know
Exploratory, connected to Berni's user learning experience research ([Issue # 4982](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4982)).

**_Links to user learning experience research:_**
1. [RS User Learning Experience Research Report](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/3.%20Instructional%20Design%20Projects/ReportStream%20User%20Learning%20Experience%20Research/ReportStream%20User%20Learning%20Experience%20Research%20Report%20April%2011%202022.docx?d=we3a97427e6454fb8b0c833a12d718a95&csf=1&web=1&e=fHz7ll)
2. [User Learning Artifacts inventory](https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/3.%20Instructional%20Design%20Projects/ReportStream%20User%20Learning%20Experience%20Research/RS%20User%20Learning%20Artifacts%20Inventory.xlsx?d=w1d2eb4a5d58c4602822b4ef046bb6f3d&csf=1&web=1&e=FcdUgN)
3. [RS User Learning Flow maps](https://app.mural.co/invitation/mural/primedatainput6410/1649452765699?sender=u3e174ac555fe8a2ccb8c7497&key=476f7290-9e2d-4073-b913-d1d47b22be1f)

## Acceptance criteria

1. EXPLORATORY WORK CAN INFORM THESE PROPOSED CHANGES (can extract from User Learning Experience research above)
2. PROPOSED CONTENT REVISIONS OF RS HOMEPAGE (which could include high-level overview of):
- Benefits and outcomes of using ReportStream as an API user
- How ReportStream works for an API user
- How to sign up for ReportStream as an API user
- Determine what the primary call-to-action is
3. UPDATED INFORMATION ARCHITECTURE (IA):
- Visual of proposed content revisions on the RS homepage at a high-level for an API user
4. Create tickets for implementing the proposed changes
  
## To do
- [x] Link proposed Home page content revisions and learning artifacts for API senders from SharePoint working docs to proposed IA

**Comment by BerniXiongA6** [comment]
Updated 5/2/2022: I've updated the AC above and will be ready to size at Design Sync @drew-usds

**Comment by BerniXiongA6** [comment]
Updates 6/13/2022: [Proposed and current content for RS website](https://cdc.sharepoint.com/:w:/t/USDSatCDC/Ee6kAtuIKlxEsNQwaeiUcpIBMt29ktZNxmdSW_qRmyW8Fw?e=ifZ64U) have been linked up to the [June 2022 IA scratchpad](https://app.mural.co/invitation/mural/primedatainput6410/1638994814548?sender=u3e174ac555fe8a2ccb8c7497&key=e1caad3b-ebae-429c-80eb-e7873446668d).

**Comment by RakshindaAslam** [comment]
@BerniXiongA6 @a-chappelear - Added AC #4
