### ISSUE TITLE
API senders: customer journey map or tip of the iceberg

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#5086]
## Problem Statement
As an organization, ReportStream wants to design with not for users. We need a visual map to help us understand an API user's persona(s) and experience at various touchpoints -- what they currently do/feel/think -- when engaging with reportstream end-to-end: from initially gaining awareness about CDC and CDC tool(s) all the way to being a user who detracts/neutralizes/promotes CDC/ReportStream.

## What you should know

- Refer to "Tip of the iceberg / Customer journey/user experience" [- see mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1649439946587/2454a861c8d7bad98a8e33df8c55b094c5b6fa75?sender=u3e174ac555fe8a2ccb8c7497)

- Operations team started a process map on API sender onboarding [here in lucidchart](https://lucid.app/lucidchart/1bb900ca-6a0e-41d1-9c86-d3529ea7e7fc/edit?page=0_0&invitationId=inv_e94a833a-e5a3-4784-96aa-23973f487065#)

## Acceptance Criteria

- [ ] Map in Mural that reflects the broad user journey
- [ ] Talk through amp with Exp team
- [ ] Revise if needed

## To do

- [ ] Flesh out  broad user journey steps:
  - Awareness
  - Consideration
  - Decision
  - Onboard
  - Operations/use (customer support, product usage)
  - Advocacy
*consider in terms of what user wants to accomplish
- [ ] Apply the below to each journey step, where relevant:
  - Time
  - User action
  - Thoughts 
  - Feelings
  - Pain points
  - Dependencies

**Comment by HeatherRienks** [comment]
Per our Sprint Planning, this issue needs input from Product.

cc: @rachelhanster, @RakshindaAslam

**Comment by drew-usds** [comment]
[In-progress Mural.](https://app.mural.co/invitation/mural/primedatainput6410/1652109384482?sender=ud6a3555dd1821b626a2b3726&key=5cdd2c92-907f-44f0-a5c8-365a0d3a91e4)
