### ISSUE TITLE
PHDI Blob Trigger Help

### ISSUE THREAD

**Issue by ghost** [CDCgov/prime-reportstream#5089]
## Problem statement

We've got a blob trigger function app (https://github.com/CDCgov/prime-public-health-data-infrastructure/tree/main/src/FunctionApps/DSTP) that we haven't been able to get quite working with the various permissions in Azure. Can someone help identify exactly what's going wrong with the DSTP app?

## What you need to know

We've tried to follow @JosiahSiegel's sample app here (https://github.com/CDCgov/prime-public-health-data-infrastructure/pull/75/files#diff-13f8d90368098e676a0f45f329867684d7c9ee90d3df22e014807a5fc67761d8), but haven't been able to get the output fully working.

## Acceptance criteria

- [ ] The DSTP app outputs something to the outbound container in the `pitestdatasa` storage account based on another blob being uploaded

**Comment by JosiahSiegel** [comment]
Phdi were able to make blob triggers work
