### ISSUE TITLE
API senders: business model by customer stage

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#5091]
## Problem Statement
As an organization, ReportStream needs to identify the problem it wants to solve and the value proposition to be delivered, for API senders by customer journey stage.

Business model is an organization's plan for creating and delivering value. Value is often measured in private industry by revenue, cost, and profit. In government digital service, value is measured by building and delivering digital interactions that make it possible for people to receive a government service.

**Comment by HeatherRienks** [comment]
Per our Sprint Planning session today, this issue needs input from Product.

cc: @rachelhanster, @RakshindaAslam
