### ISSUE TITLE
WA - Issue Accessing Download Site

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#5093]
WA reported that both users that were provisioned access to the site are not able to access it. They get the following error:

![image.png](https://images.zenhubusercontent.com/607d9d4a591b7cc0bb55c82e/e4126cb2-fbf7-49e5-9a9c-0607483653bc)

**Comment by Adrian-Brewster** [comment]
Okta issue where user belongs to multiple groups. Which team should they belong to? This should likely go to experience team.
