### ISSUE TITLE
Receiver Detail View Design

### ISSUE THREAD

**Issue by inkandsound** [CDCgov/prime-reportstream#5094]
## Problem statement

Daily data > Report details

Receivers need to be able to filter and sort on the Report Details page - some of these may replicate what we show on Daily Data, but it would be good to make sure we're providing all of the options that we need and removing any that don't make sense at that view.

We should also make sure that we're displaying all the data columns on that page that would be helpful for receivers to view. Most of these items already exist in some fashion, but we will want to mock up how they look on this page specifically to make it easier for engineering to implement. 

![Screen Shot 2022-04-08 at 3.14.18 PM.png](https://images.zenhubusercontent.com/611a905f814eda0684979aed/9928816b-6021-4556-ab09-4cc331c0f006)

## Acceptance criteria

- Mockup that's been vetted by engineering lead
- Share with product and engineering leads on Experience and Pipeline teams

**Comment by inkandsound** [comment]
@drew-usds Added you to this - this is the split out from the pagination ticket. This should be fairly simple - mostly engineering wants to see all the filtering/sorting/etc. options on this page in a visual and make sure that we only display what's relevant, as well as double check that all the displayed columns/rows make sense.

**Comment by kevinhaube** [comment]
@drew-usds @fmccaf1 Marking as possibly stale and closable!

**Comment by drew-usds** [comment]
Closing! Duplicate of @fmccaf1 's current work.
