### ISSUE TITLE
SonarCloud build script need to be fixed during Code Smell of checking the name of the function.

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#5100]
Currently, the Code Smell script checks the  function's name using the regular express to  match ^[a-zA-Z][a-zA-Z0-9]*$
It gives warning if the function's name include space (i.e 'unit test case for something').  The matching string should allow the space for unit test function name (i.e  ^[a-zA-Z][a-zA-Z0-9 ]*$.  Note, there is a space after 9).

**Comment by cwinters-usds** [comment]
@oslynn just to be clear, you want to add a space to the allowed characters for test names?

Actually I think this will be unnecessary as this PR (https://github.com/CDCgov/prime-reportstream/pull/5113) skips checks on tests.

**Comment by cwinters-usds** [comment]
Completed in https://github.com/CDCgov/prime-reportstream/pull/5113

**Comment by oslynn** [comment]
Yes, it is ok to close it.  Thanks.
