### ISSUE TITLE
Convert full ELR HL7 MSH segment data to FHIR resource

### ISSUE THREAD

**Issue by clediggins-usds** [CDCgov/prime-reportstream#5111]
### User Story:
As a sender, I want my all of my submitted data to be converted to FHIR, so it can be fully and accurately reported to STLTs.

### Description/Use Case
We have an initial HL7 to FHIR conversion, but we now need to verify that all data fields are correctly converted and contained in a FHIR resource to make sure we do not lose any data in the conversion.  This work is to verify that ALL data is retained without any loss for a given HL7 portion (see acceptance criteria).

### Risks/Impacts/Considerations
* May need some research as to what resources will contain a piece of data.  
* Is there a possibility we are not able to decode some HL7 data due to the current libraries we are using?
* There seem to be duplicate resources in the generated FHIR bundle, so care must be taken to remove those duplicates as needed.
* There are duplicate segments in the HCA HL7 messages that need to be handled accordingly.  May need to communicate with HCA to ask about those segments, but it is expected those are coming from the source and we will probably have to handle them.

### Dev Notes:
* The HL7 to FHIR conversion is configuration driven.
* HCA sample data is stored in Keybase.  It has no PII.

### Acceptance Criteria
* The full ELR HL7 MSH segment data is converted to FHIR resources.
* All available data from the MSH segment fields of an HCA full ELR HL7 message are stored as part of the FHIR bundle.

**Comment by jimduff-usds** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/5111?planning-poker) with ZenHub @carlosfelix2 @clediggins-usds @JGreenFearless @jh765 @whytheplatypus

**Comment by jimduff-usds** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/5111?planning-poker) with ZenHub @TurkeyFried

**Comment by carlosfelix2** [comment]
Mapping spreadsheet for MSH segment
[HL7 to FHIR - MSH.pdf](https://github.com/CDCgov/prime-reportstream/files/8672767/HL7.to.FHIR.-.MSH.pdf)
[HL7 to FHIR - MSH.xlsx](https://github.com/CDCgov/prime-reportstream/files/8672773/HL7.to.FHIR.-.MSH.xlsx)

Sample HL7 file:
[sample_hl7.txt](https://github.com/CDCgov/prime-reportstream/files/8672777/sample_hl7.txt)

**Comment by carlosfelix2** [comment]
Sample FHIR output
[https://app.zenhub.com/files/304423150/c40de7e2-9c61-4bc1-9aa3-414a7cf9ab64/download](https://app.zenhub.com/files/304423150/c40de7e2-9c61-4bc1-9aa3-414a7cf9ab64/download)
