### ISSUE TITLE
FHIR Profile

### ISSUE THREAD

**Issue by clediggins-usds** [CDCgov/prime-reportstream#5112]
### User Story:
As ReportStream, I want to verify that FHIR bundles match a specific FHIR Profile, so that I know I am not missing any data.

### Description/Use Case
We are not yet certain we need a Profile for this, but want to do the research and determine if it is something that is 1) useful to us, and 2) potentially something we could publish as The Standard for healthcare reporting.

### Risks/Impacts/Considerations
* Is having a FHIR Profile something useful to us
* If it is determined to be useful, it may be something we only use internally instead of having broader adoption

### Dev Notes:
* A good understanding of FHIR and FHIR Profiles will be necessary to accomplish this task and answer questions

### Acceptance Criteria
* Determine if we need a FHIR Profile
* Complete issues in Epic

**Comment by carlosfelix2** [comment]
OBE not working on profiles right now
