### ISSUE TITLE
Ascending Pagination on Table Component

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#5127]
### Problem

Currently, the `Table` component does not paginate in ascending order. The table should be able to accurately update the `cursorManager` and `filterManager.range` so that:

- When the sort order is **"ASC"**, our cursor incrementally closes the gap from **endRange -> startRange**, setting endRange with the next cursor value each time the user pages next
- When the sort order is **"DESC"**, our cursor incrementally closes the gap from **startRange -> endRange**, setting startRange with the next cursor value each time the user pages next.

### Acceptance criteria

- When I navigate to a page utilizing the `Table` component with filtering, sorting, and pagination, I can click next and previous to paginate a consistent list of results.
- When I click on a date column header to flip its sorting to ASC, I am taken back to the first page of the table, and I can page next and previous to see a consistent list of results.

**Comment by kevinhaube** [comment]
TODO:
- [ ] Refactor cursor manager
- [ ] Refactor filter hooks
- [ ] Use reducers from refactor to handle cursor and filter updates based on sorting order

**Comment by rachelhanster** [comment]
@kevinhaube will this fix a[ new bug identified here ](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5180)

**Comment by kevinhaube** [comment]
@rachelhanster It will not. We originally intended to leave the ability for start and end range UI elements to be interchangeable for a user, as Brian is attempting to do here. That's fine if both dates are set every time, but the logic breaks down once you consider somebody who'll only set one date. There's no way for our software to tell what a user expects "end range" to mean if they don't provide the context of what they think start range means, as well. For this, we removed that interchangeability.

The true solution to that issue is a UI change. We should be using the [Date Range Picker](https://designsystem.digital.gov/components/date-range-picker/) from USWDS, but the React component version cannot be used to mimic the current design because it's stacked instead of horizontal like ours. However, I think we can use the USWDS classes to make one and add our own classes atop that to reorient them horizontally. I'll copy this info to the other ticket, as well.
