### ISSUE TITLE
Diagram IA: look at current pages, figure out how to fit in help center, programmer's guide, interest forms

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#5131]
## Problem statement

Our current IA is outdated and needs a refresh. We also want to add new sections, including help center, the programmer's guide, and an area for interest/registration type forms.

We should take a step back and look at our current information architecture. How will these new section s slot into the current site? How can we set it up so there is room to grow?

## What you need to know
- [Content outlined this proposal back in January 2022](https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Website%20Copy%20Writing/Proposed%20Outline%20for%20RS%20Website%20Content%20Infrastructure%20Revisions.pptx?d=wf0edd12661f244f9b80f1390bb36462e&csf=1&web=1&e=huBfhw) that we can adapt and use for this work as needed

 - [Existing IA scratchpad in Mural](https://app.mural.co/invitation/mural/primedatainput6410/1638994814548?sender=ud6a3555dd1821b626a2b3726&key=e1caad3b-ebae-429c-80eb-e7873446668d)
## Acceptance criteria

- [ ] IA diagram for RS site
- [ ] After team feedback, create relevant follow-on tickets

## To do

- [ ] Look at current IA
- [ ] Look at recommendations from #5130
- [ ] Outline general sections for help center
- [ ] Outline how programmer's guide/similar content might slot in
- [ ] Get feedback from team and refine

**Comment by BerniXiongA6** [comment]
@a-chappelear I'm sharing again the content I created back in January regarding the [initial proposal for RS website content infrastructure](https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Website%20Copy%20Writing/Proposed%20Outline%20for%20RS%20Website%20Content%20Infrastructure%20Revisions.pptx?d=wf0edd12661f244f9b80f1390bb36462e&csf=1&web=1&e=huBfhw). This can help us to avoid having to reinvent the wheel with our new IA ideas.

**Comment by a-chappelear** [comment]
Based on syncs and review - I am moving this to closed. The IA Mural will likely continue to evolve a bit as we start work on content pieces (new and/or consolidating some pages) so it should be considered as more a guide/living doc that stays updated.
