### ISSUE TITLE
In-app communication to uploader users about transition

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#5141]
## Problem Statement
As a current user, I would like multiple communication channels about the Uploader's move to SimpleReport. This is 1 of 2 communication methods, to inform current, logged in uploader users about the upcoming transition.

## Note
- [Slack thread for context](https://slack.com/archives/C03A23UMGTS/p1649786111601549)
- [Figma designs from SimpleReport](https://www.figma.com/proto/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?page-id=8979%3A27220&node-id=8987%3A27262&viewport=260%2C48%2C0.55) for ReportStream's consideration

## Acceptance criteria

- In app message: After logging into reportstream, I'm taken to Upload page, and I see an alert message at the top of the screen about uploader's upcoming transition from reportstream to simplereport
- public webpage: show same in-app alert message

## To do
- develop content for in-app alert message and public website documentation page
- Create prototype view and share with eng on #5190

**Comment by HeatherRienks** [comment]
work is pulled into #5145 - closing this ticket.
