### ISSUE TITLE
CSV upload transition: if an upload user tries to log in, provide help text to direct them to SR

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#5145]
## Problem statement

As a CSV Uploader user, I need to see the following messages pre, during and post transition of this service to SimpleReport:
1 - When the feature is not yet Live on SimpleReport
    Inform the user of the upcoming change about the upload feature and that the submission history will continue to be available until further notice.
2 -  When the feature goes Live on SimpleReport but also available on ReportStream during the transition period.
     Inform the user the feature has migrated to SimpleReport and provide them with the link to the new location. Let the users know that the service will be removed from ReportStream by x date and that the submission history will continue to be available until further notice.
3 -  After the feature has fully migrated to SimpleReport and has been removed from ReportStream
     Inform the user the feature has migrated to SimpleReport and provide them with the link to the new location. The submission history will continue to be available until further notice.

## Questions

Q: Is it possible to flag our CSV upload user's credentials so we can show specific help text if they try to log in?
A: Yes.

## Need to know
Link to the transition documentation created by the SimpleReport design team
https://skylight-hq.slack.com/files/U01PJ2ZPD2L/F03G1P1NAV8/csv_uploader_transition_-_communications_plan_shared

Planned order of events:
1 - Pre-transition banner goes up on ReportStream about upcoming transition to SimpleReport (aim to complete by next Sprint (6/8/22)
2a - CSV Uploader goes Live in SimpleReport - July 5 ETA
2b - Transition banner goes up on ReportStream informing the user that the site is now also available on SimpleReport and a link to go there. The user can continue to upload on ReportStream for now. 
3 - CSV Uploader is disabled on ReportStream, directing the user to SimpleReport. July 18 ETA

## Acceptance criteria
- [ ] Help content should inform users of the location change before, during and after the transition. 
- [ ] If a deactivated CSV upload user tries to log in, we direct them to help content that gets them started with SR.
- [ ] Help content should inform users of the deactivated feature
- [ ] Help content should inform users of how to get connected/in touch with SR

## To do

- [ ] ...

**Comment by rachelhanster** [comment]
@drew-usds Is this a must have, given there will be an alert message on pages post log in?

**Comment by rachelhanster** [comment]
@drew-usds Scratch my previous question. This ticket is for after Simplereport has Uploader up and running. I'm moving it to our backlog.

**Comment by kevinhaube** [comment]
We'll have to ensure that the user logging into ReportStream is in an Okta group that has access to ReportStream. Access to login is _not_ permission to operate anything within RS, though, so we can still protect all in-app operations from being access while allowing them in so we can pass them over to SimpleReport.

**Comment by victorialb-usds** [comment]
Design choice: Do something once a user logs in **
not when they try to log in.

**Comment by victorialb-usds** [comment]
@drew-usds I know you missed refinement and we did not get to this in our sync yesterday so wanted to tag you here and we can add to our refinement or perhaps do another sync today/friday to get to the tickets in the slack thread "Update for 4/21: we will did 3815 but did NOT get to 5109, 5208, 5145, 4338 and 4790 perhaps 4338 @Andrea Chappelear (MO, she/her) perhaps you can look at this a bit more @drew.gardner think you can look at 4790 async. perhaps we can bump to Tuesday but if we can do another meeting Friday to finish up"

**Comment by BerniXiongA6** [comment]
Per our backlog refinement today, @RakshindaAslam is taking an action item to sync with Product owners cross SR/RS to discuss plan for the transition - to help inform what content/design work is needed for this ticket so we can unblock # 5295. Try to complete sync/get info within week or so to meet July 1st CSV uploader transition deadline. cc: @a-chappelear @bgantick @HeatherRienks @drew-usds

**Comment by HeatherRienks** [comment]
Regarding comment above, a meeting is now set for 5/20/22 with RS/SR team to discuss transition.

**Comment by BerniXiongA6** [comment]
Updates 5/25: I'm starting to work on the content for the email series ([# 5140](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5140)) and will adapt some of that content for this ticket. Will provide updates this week before I leave on PTO (Friday 5/27).

**Comment by a-chappelear** [comment]
Updates!

Figma files for the banner (s) can be found here:
Pre-move, https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=3209%3A22143

....and should it be determined to not want an auto-redirect, but instead have another banner that will redirect users via the link, https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=3210%3A21918  

From a design perspective, this uses the same alert banners from USWDS and are already in place on RS. The blue is for pre-move messaging and switches to the yellow version once the event has passed and it needs to be more "alert"-ish.

Content is based on the draft work from the email(s) mentioned above, but guessing this may alter slightly (ie. we might want to link to help content that is on SR when available.) Easy to update as needed!

@RakshindaAslam @BerniXiongA6 @drew-usds
