### ISSUE TITLE
CSV upload transition: banner to notify users about the transition

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#5146]
## Problem statement

[Write a short description of what you want to achieve with this task]

## What you need to know

[Discussion in Slack with Victor](https://usds.slack.com/archives/C03A23UMGTS/p1649786111601549)

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by HeatherRienks** [comment]
@drew-usds - the Slack convo under "What You Need to Know" is not accessible. Would you mind adding some additional info in? Thanks!

**Comment by rachelhanster** [comment]
Closing as this is a duplicate
