### ISSUE TITLE
API senders user research plan and tools: using/re-purposing submission history API?

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#5150]
## Overview
[11/21 need to add more detail!!!] As ReportStream pivots to focus on STLTs and API senders, we need a research plan for our engagement with API senders. 

**Background*: 
Abbott & Healthcare Integrations(as per meeting 4/12/22)
Slack thread from Healthcare Integrations https://www.healthcareintegrations.com/
Notes from Abbott call: 
https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BC495E011-223B-4C7A-AB49-9CC709BB58D4%7D&file=2022.04.12%20Abbott_history%20API%20demo.docx&action=default&mobileredirect=true

## To do
- [ ] Create research plan (include facilitation/interview guide)
- [ ] Share in Slack

**Comment by victorialb-usds** [comment]
- May need to do internal survey first about some questions about API users that the team has or has hunches around. 
- questions relevant for how they would like to receive information about changes or updates to the software

**Comment by victorialb-usds** [comment]
@rachelhanster FYI I created this ticket as a first step of turning towards API users this quarter

**Comment by rachelhanster** [comment]
@RakshindaAslam and Rachel to finish scope out initiatives related to API senders, that we'll be tackling "now" and "near." We'll then engage with designers to discuss research needs.
cc @victorialb-usds @drew-usds

**Comment by victorialb-usds** [comment]
What about HCA seems like there has not been systematic research or UX around that - that I know of.

**Comment by HeatherRienks** [comment]
@drew-usds @victorialb-usds -do we still need this ticket?  Not sure if it's been documented elsewhere in another ticket?

cc: @fmccaf1

**Comment by chris-kuryak** [comment]
Closing by committee. Old issue relevant notes coped by Lizzie to different doc.
@drew-usds @lizzieamanning
