### ISSUE TITLE
Receiver retrieves delivered reports for a specific service (Pagination, sorting, and filtering available in daily-data API endpoint)

### ISSUE THREAD

**Issue by JGreenFearless** [CDCgov/prime-reportstream#5157]
As a ReportStream end-user, I want pagination, sorting, and date filtering on the daily-data API endpoint, so that I can get to my data easily. 

### Description/Use Case
End-users need an efficient way to be able to sort and/or filter through large amounts of data on the daily-data API endpoint.

"Daily Data" refers to the list of reports available for download by a STLT (Receiver)

### Risks/Impacts/Considerations
- We won't be able to test the front end

### Acceptance Criteria
1. Daily-data API endpoint displays "Next" and "Previous" buttons. (cursor-based pagination)
2. Daily-data API endpoint allows end-users to filter on dates, by selecting a start and end date
3. Daily-data API endpoint allows end-users to sort (ascending to descending) on the selected filtered dates

**Comment by jimduff-usds** [comment]
Screenshot of the page we need to populate:
![image.png](https://images.zenhubusercontent.com/5ff48b04da86ca0cf2bcf625/f0c7dd57-5e83-45a4-99cb-c2bff75b7604)

**Comment by jh765** [comment]
This shows a page size (report count) of 8 (per page).  Will that value be passed in?  Rachel said it would be a fixed size...

**Comment by TurkeyFried** [comment]
As per discussion this week, the ticket is being split into 3 smaller ones so we can better keep track of the progress.

**Comment by TurkeyFried** [comment]
The scope of #5234 is too large, so after a discussion today we decided to split it into a couple smaller tickets.
