### ISSUE TITLE
Error when an OKTA account is assigned to two OKTA groups

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#5168]
## Problem statement
WA reported that both users that were provisioned access to the site are not able to access it. They get the following error:

![image.png](https://images.zenhubusercontent.com/607d9d4a591b7cc0bb55c82e/e4126cb2-fbf7-49e5-9a9c-0607483653bc)

## Things to know
After troubleshooting, it was determined that this is not a WA problem.  This error occurs when a single OKTA account/user is assigned to multiple OKTA groups.  In WA's case, two OKTA users were assigned to the OKTA groups, DHwa_phd and DHSender_waphd-csvuploadertest.  When they were removed from DHSender_waphd-csvuploadertest, they could login successfully.

Note, they haven't reported it yet, but this will be a problem for CA and CO; basically, this will be a problem for any Receiver that has a download site and CSV Uploader account.

**Comment by rachelhanster** [comment]
@rhood23699 Does Washington want access to both the Upload and Daily Data pages?

Between now and end of June, do you anticipate California and Colorado wanting access to Upload page?

**Comment by HeatherRienks** [comment]
@RakshindaAslam - FYI

**Comment by rhood23699** [comment]
@rachelhanster @mauricereeves WA was the Receiver that help us find the bug.  Since they are not onboarding right now, they do not have this problem.  I mentioned CA & CO simply to provide other potential Receiver problems.  Whether a Sender or Receiver will utilize CSV Uploader now or in the future, is not really the problem.  This is a bug preventing a single OKTA user from being assigned to multiple OKTA groups.  It may not be high priority right now, but eventually it needs to be fixed because it will happen again.

**Comment by rachelhanster** [comment]
@rhood23699 
"this will be a problem for any Receiver that has a download site and CSV Uploader account": does this problem go away once uploader is no longer operated by reportstream?

"it will happen again": help me understand. under what additional scenarios would someone need an okta login and be part of two or more organizations?
