### ISSUE TITLE
[Feature] Setting Revision History

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#5187]
## Problem Statement:
As a member of the O&O team, I want to be able to view, compare and clone previous version of Sender, Receiver and full settings for an organization to troubleshoot issues.

## Acceptance Criteria:
- User is able to view any version of settings from history
- User is able to compare the current version with any previous version of settings
- User is able to clone a previous version and create a new version for any setting.

## What you need to know:
Background: All past Setting for an organization are only marked deleted (tombstoned). These older revisions contain a version number in the meta. A nice safety-net feature is to allow seeing past versions and comparing to recent to help track down issues.

API:
- [ ] Given an Org name and Setting type, return a full list of all past revisions.
`settings/revision/organizations/{organizationName}/{settingSelector}`

Frontend:
- [ ] Show History as a list.
- [ ] Use DiffEditor to show differences across two revisions AND across different named settings.
- [ ] Add mode to DiffEditor to NOT allow editing of text.

## Modifications to existing Settings page
<img width="550" src="https://user-images.githubusercontent.com/74203452/189396936-07c58acb-77e8-4abc-9962-7aad9e507ae9.png">

Add link to every settings type. This will lead to a new Settings Revision History page. 

Note: This link is ALWAYS displayed even when a list might be empty (like Sender Settings) because there might be settings that were deleted.

## New Settings Revision History page
New page will contain two copies of the same lists side-by-side. The list will be a 2-level hierarchy with the top level being the setting name and the inner level being the revision. It will use [USWDS's accordion view](https://trussworks.github.io/react-uswds/?path=/docs/components-accordion--borderless).

Clicking on any item will fill in that side of the existing Text Difference Compare component and that will highlight the differences.

<img width="550" src="https://user-images.githubusercontent.com/74203452/189397700-e19cf7e2-5856-4deb-bc5d-64fd58972263.png">

No editing will be supported. We might have a Back button somewhere at the top of the page.

The new page's url will include the org name and settings type so it can be linkable.

**Comment by RakshindaAslam** [comment]
@bgantick

**Comment by TomNUSDS** [comment]
## Modifications to existing Settings table
<img width="450" alt="image" src="https://user-images.githubusercontent.com/74203452/168325527-2366586f-8efc-4baa-b92a-dd98db190e82.png">

1. Org Name and Topic are always the same. Remove columns to make room.
2. Break out the Meta into columns (Version, LastMod, Editor)
3. Add a "Revisions" (Or "History") button to actions. 

<hr>

## New page showing revision history
<img width="450" alt="image" src="https://user-images.githubusercontent.com/74203452/168327019-55e9f32d-1bcd-4edb-bfa0-e7e5d56740bb.png">

Note: Prototype only. Feel free to tweak. The action buttons should really should only be shown on hover
<hr>

## Compare shows revision against current setting
<img width="450" alt="image" src="https://user-images.githubusercontent.com/74203452/168327035-afe005c2-1d70-483b-9dd8-525566da7fd2.png">

Clicking the Compare button shows the Diff Editor with the old version on the left and the latest on the right.

**Comment by TomNUSDS** [comment]
I added quick UI mocks for the Admin-only (no customer facing) change if that's helpful.

**Comment by TomNUSDS** [comment]
@RakshindaAslam Is this something you guys want to take on? It spans multiple teams (api and frontend).

**Comment by RakshindaAslam** [comment]
@TomNUSDS - This is something we can take on but we don't have capacity to pick it up for atleast 3-4 sprints while we build out the new Validation Service.

**Comment by TomNUSDS** [comment]
Pipeline: there is some Settings API work that could be done as part of this ticket.

**Comment by TomNUSDS** [comment]
Would have been nice to have this feature today while debugging PMG issues. @jimduff-usds

**Comment by RakshindaAslam** [comment]
@TomNUSDS -To help us understand where it should stand in our priorities, can you give us an idea on how many times this feature might have been used in the last 3 months and saved how much time in each case? cc @bgantick
