### ISSUE TITLE
Build in-app alert to uploader users about transition - Before

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#5190]
## Problem Statement
As a CSV Uploader user, I need to see the following messages pre, during and post transition of this service to SimpleReport:
1 - When the feature is not yet Live on SimpleReport
Inform the user of the upcoming change about the upload feature and that the submission history will continue to be available until further notice.
2 - When the feature goes Live on SimpleReport but also available on ReportStream during the transition period.
Inform the user the feature has migrated to SimpleReport and provide them with the link to the new location. Let the users know that the service will be removed from ReportStream by x date and that the submission history will continue to be available until further notice.
3 - After the feature has fully migrated to SimpleReport and has been removed from ReportStream
Inform the user the feature has migrated to SimpleReport and provide them with the link to the new location. The submission history will continue to be available until further notice.

## Need to know
- Refer #5145
- This ticket is for the initial banner display. There will be separate tickets for during and post transition content updates.

## Acceptance criteria
 - When a CSV Upload user logs in, they see a banner with information that CSV uploader is being moved to SimpleReport. 
 

## Context
- See design from In-app communication to uploader users about transition 5141 / 5145

**Comment by bgantick** [comment]
@RakshindaAslam @HeatherRienks When does this need to go live?
