### ISSUE TITLE
Debug and Deploy Python DSTP Function App to Azure

### ISSUE THREAD

**Issue by bamader** [CDCgov/prime-reportstream#5193]
**Description**
The PHDI engineering team has created a Python function app (located at https://github.com/CDCgov/prime-public-health-data-infrastructure/tree/convert-dstp-to-python) that uses a blob trigger to convert one type of file into another. The team has successfully gotten the function app to run locally, but we are unable to successfully deploy it in Azure or see the functions run.

**Specific Requested resources**
The Python Function app at the branch linked above should be deployed to the Azure environment in the pitest-python-functionapp resource.

**Existing Resources?**
Any code currently in `pitest-python-functionapp` can be freely modified or deleted. Getting the code in the linked branch working in Azure is our top priority.

**Additional Context**
Previously, we had been using a Java/Kotlin function app to handle bulk conversion of HL7 messages into FHIR. However, we decided to port our functionality over to Python for consistency with the rest of our codebase and functionality. We migrated the code over and attempted to replicate the work that went into a test Java app (https://github.com/CDCgov/prime-public-health-data-infrastructure/commit/6152260fe4e6f033d0e500fdcb4e587d478aa4e6) built to show how one could set a config for a function, but no combination of various `__serviceUri` settings would enable successful function invocation after deployment, consistently returning the following error instead:

```
[2022-04-18T19:20:19.813Z] Microsoft.Azure.WebJobs.Script.WebHost: Secret initialization from Blob storage failed due to missing both an Azure Storage connection string and a SAS connection uri. For Blob Storage, please provide at least one of these. If you intend to use files for secrets, add an App Setting key 'AzureWebJobsSecretStorageType' with value 'Files'.       
Value cannot be null. (Parameter 'provider')
```

**Comment by acoushawk** [comment]
We were able to add the correct permissions and verified that the function app is now able to access the storage with the managed identity. Going to update documentation before I mark the issue as complete.
