### ISSUE TITLE
Add tag to all Azure resources that are created via Terraform

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#5198]
As a devops engineer (or anyone, really) looking through resources in Azure I want to know which are manually created and which have been created from IaC. I think this means we should add a tag - something like "git-origin" that adds the URL for the repo the object was created. For instance in our case all the current IaC would be tagged as follows:

`git-origin:https://github.com/CDCgov/prime-reportstream.git`

**Comment by lucasdze** [comment]
I was able to get this list of resources that are not tagged in Azure 
![image](https://user-images.githubusercontent.com/50645318/196801234-2c7042df-8bfa-4cd2-8fd7-4420bf275738.png)

**Comment by lucasdze** [comment]
We have added tags using terraform on dns zones in test env. See PR https://github.com/CDCgov/prime-reportstream/pull/7222
Most of the resources hav been manually tag from Azure portal
Some of the tag do not need to be tagged or cannot be tagged now https://icfonline-my.sharepoint.com/:x:/r/personal/58917_icf_com/Documents/[AzureResources-Tags.xlsx](https://icfonline-my.sharepoint.com/:x:/r/personal/58917_icf_com/Documents/AzureResources-Tags.xlsx?d=w3855102de4fa4c0bb3d565573af5bb65&csf=1&web=1&e=KxtXCw)?d=w3855102de4fa4c0bb3d565573af5bb65&csf=1&web=1&e=KxtXCw
