### ISSUE TITLE
Email message: Inform Uploader users of Submission page - Email content

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#5208]
## Problem statement

As someone working at an organization reporting covid results, I need to be able view a list of csv files shared with ReportStream, so I can keep track of data submissions and so my organization has "written proof" should CLIA inspectors request proof.

As an organization, Reportstream wants to communicate to end users about new features.

## What you need to know
- Given a user is logged into reportstream as an Upload user
- User is directed by default to "Upload" page
- "Submissions" page is found next to "Upload" page

## Acceptance criteria

- Via email, all current Uploader users are informed of Submissions page availability
- Message has a mix of written and visual content

## To do
- [x] Develop standard email message (Experience to own)

**Comment by HeatherRienks** [comment]
we will break this ticket up - @victorialb-usds - thanks!

**Comment by victorialb-usds** [comment]
tagging @Adrian-Brewster and @rhood23699 for visibility even though assigned to Berni b/c content specific

**Comment by victorialb-usds** [comment]
@BerniXiongA6 tagging you here after we talked about it in stand up 4/21

**Comment by HeatherRienks** [comment]
@BerniXiongA6 - do you think this will be done by end of this current sprint, or should we plan for it to be in the next sprint?

**Comment by HeatherRienks** [comment]
Discussed in the Design sync today and we will be moving this ticket to the next Sprint. Confirmed that this is a high priority ticket.

**Comment by BerniXiongA6** [comment]
Updates on 4/27/2022: As a first step, I can start taking screenshots of the Upload and Submissions pages when logged in to RS, and can de-identify the content. 

As a second step, I can reach out to @Adrian-Brewster to discuss email copy.

**Comment by BerniXiongA6** [comment]
Updates on 5/2/2022: Content and instructional design deliverables are ready for review by @drew-usds @Adrian-Brewster ! Any questions, lmk.

[Here's the link to the Shared Folder](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/3.%20Instructional%20Design%20Projects/ReportStream%20Email%20Comms%20to%20Senders%20for%20Viewing%20Submission%20History?csf=1&web=1&e=zh0Pcx) to view: 1) Email copy template, and 2) Quick Guide to Submission History

**Comment by HeatherRienks** [comment]
@BerniXiongA6  to discuss with @Adrian-Brewster today re: send date.

**Comment by BerniXiongA6** [comment]
Updates 5/6/2022: Scheduled sync with @Adrian-Brewster to discuss outreach plan. Goal is to send outreach comms the week of May 9th.

**Comment by BerniXiongA6** [comment]
Updates 5/9/2022: I'll close this ticket when I send out the email comms on Tuesday 5/10.

**Comment by BerniXiongA6** [comment]
Sent to CSV users in Prod!
