### ISSUE TITLE
CSV upload: inform users of Submission History feature

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#5209]
## Problem statement

As someone working at an organization reporting covid results, I need to be able view a list of csv files shared with ReportStream, so I can keep track of data submissions and so my organization has "written proof" should CLIA inspectors request proof.

As an organization, Reportstream wants to communicate to end users about new features.

## What you need to know
- Given a user is logged into reportstream as an Upload user
- User is directed by default to "Upload" page
- "Submissions" page is found next to "Upload" page

## Acceptance criteria

- [ ] Users are informed of Submissions page availability as part of their upload workflow

## To do

- [ ] Find place on upload confirmation page to direct users to the submission history index (maybe a button/link)
- [ ] If needed, write content to help folks find the button
- [ ] Update prototype and share in a related eng ticket

**Comment by HeatherRienks** [comment]
@drew-usds @BerniXiongA6  - pls discuss in your design sync and let us know your feedback.

**Comment by BerniXiongA6** [comment]
@kevinhaube per our Slack convo, [please see # 5208 for this content](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5208).

**Comment by BerniXiongA6** [comment]
For consistency,[ feel free to use the quick guide ](https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=zh0Pcx&cid=3c387112%2D43f8%2D4ee0%2Db707%2D0f98c4a1c539&FolderCTID=0x0120004368ADED9C3BEA4B94E57C5781F119FF&id=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FTeam%20Documents%2FExperience%20Team%2FInstructional%20Design%2F3%2E%20Instructional%20Design%20Projects%2FReportStream%20Email%20Comms%20to%20Senders%20for%20Viewing%20Submission%20History%2FArtifacts%20Sent%2FQuick%20Guide%20%2D%20ReportStream%20Submission%20History%20View%20%2D%20PDF%2Epdf&parent=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FTeam%20Documents%2FExperience%20Team%2FInstructional%20Design%2F3%2E%20Instructional%20Design%20Projects%2FReportStream%20Email%20Comms%20to%20Senders%20for%20Viewing%20Submission%20History%2FArtifacts%20Sent)we created for Submission History to extract any content that might be needed for this ticket.

**Comment by a-chappelear** [comment]
This has been reviewed w/ @BerniXiongA6 @bgantick @RakshindaAslam 
Figma file: https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=3090%3A21665
 - Link added to submission success, links to the "Submissions" page.
-  Button added next to "upload another file", links to the "Submissions" page.
