### ISSUE TITLE
WA - Incorrect Specimen Collection Date

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#5213]
**Describe the bug**
`23d1852c-cc3f-4b78-8ac3-76ab7de9b44b`
Specimen collection date is in 2021 but we received the result on 2/10/2022.
 
`f8fcfb1c-9633-4b14-9233-ed394d095f8b`
Specimen collection date is in 2020 but we received the result on 1/15/2022.
 
Can you review these results and confirm the specimen collection dates? If the specimen collection dates on these are incorrect, please have the facilities send the corrected results.

**Comment by jayna-SkylightDigital** [comment]
It appears these dates were entered intentionally by the user. The following dates/times were provided by Metabase.

23d1852c-cc3f-4b78-8ac3-76ab7de9b44b
created at February 10, 2022, 5:37 PM
backtested to January 31, 2021, 5:37 PM
https://prime-simple-report-prod-metabase.azurewebsites.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIj[…]Zpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==

f8fcfb1c-9633-4b14-9233-ed394d095f8b
created at January 14, 2022, 7:58 PM
backtested to January 10, 2020, 7:57 PM
https://prime-simple-report-prod-metabase.azurewebsites.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdW[…]Zpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==

During the **WA/USDS Check in (ReportStream/SimpleReport) Meeting on 9 MAY 2022** Washington requested that SimpleReport follow up with the facilities in question to verify that the dates were entered intentionally.

**Comment by anshulkumar-usds** [comment]
SR team will follow up with user to confirm intent of the date updates
cc: @jayna-SkylightDigital 
Closing in RS queue

**Comment by jayna-SkylightDigital** [comment]
Test result ID: f8fcfb1c-9633-4b14-9233-ed394d095f8b 
Created at January 14, 2022, 7:58 PM 
Back-dated to January 10, 2020, 7:57 PM

**Tue, May 17, 2022 at 2:08 PM: Email sent to Larson, Charissa <charissalarson@selahschools.org>
Tue 5/17/2022 5:16 PM: Response received from Larson, Charissa <charissalarson@selahschools.org>** 

> Yes, that was a mistake. The true date should have been January 10th 2022.
> Thank you

--
Test result ID: 3ada02ce-daff-4023-a555-1fe4d94f6012
Created at February 11, 2022 
Back-dated to January 18, 2021

**Mon 5/23/2022 5:26 PM: Email sent to Ben Swartsel <benjamin.swartsel@psischiefs.org>
Tue 5/24/2022 9:55 AM: Response received from Ben Swartsel <benjamin.swartsel@psischiefs.org>**

> Thank you for your attention in this matter.  Please change the year on this entry to 2022.  Have a  great day.
> 
> Ben Swartsel, Rn
> School Nurse
> Paschal Sherman Indian School
> 509-422-7704

--
Test result ID: 23d1852c-cc3f-4b78-8ac3-76ab7de9b44b 
Created at February 10, 2022, 5:37 PM
Back-dated to January 31, 2021, 5:37 PM

**Tue 5/17/2022 5:07 PM: Email sent to Madelynn Wheeler <mwheeler@stanwood.wednet.edu>
Tue 5/17/2022 6:01 PM:  Response received from Madelynn Wheeler <mwheeler@stanwood.wednet.edu>**

> Hi, 
> That was actually a test result for myself that I was back entering, the date I tested positive was 12/31/2021. I've just gone back in and fixed it.
> 
> -Maddie Wheeler

--
**Thu 5/26/2022 3:24 PM: Request for correction was sent via email on May 26, 2022 to: Charissa Larson, Ben Swartsel, & Madelynn Wheeler.** 
Content of email is below.

> Caroline Thomas at the Washington Department of Health has requested that you resend the result for test ID: f8fcfb1c-9633-4b14-9233-ed394d095f8b with the corrected date.
> 
> You can find instructions on how to correct a previous test result here:
> https://www.simplereport.gov/using-simplereport/manage-results/correct-a-previous-test-result/
> 
> If you have additional questions, please reach out to Caroline Thomas: Caroline.Thomas@doh.wa.gov

--
A ticket has been added to the SimpleReport backlog to alert users if attempting to add a backdate more than 6 months in the past. 

**Conduct Test: Add warning when user attempts to back-date more than 6 months**
https://app.zenhub.com/workspaces/simplereport-growth--engagement-605b43a6ceb92c000f86279a/issues/cdcgov/prime-simplereport/3792
