### ISSUE TITLE
Email message: Inform Uploader users of Submission page - Generate list of contacts

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#5219]
## Problem statement

As someone working at an organization reporting covid results, I need to be able view a list of csv files shared with ReportStream, so I can keep track of data submissions and so my organization has "written proof" should CLIA inspectors request proof.

As an organization, Reportstream wants to communicate to end users about new features. And wants to communicate about submission page to end users. 

## What you need to know
- Given a user is logged into reportstream as an Upload user
- User is directed by default to "Upload" page
- "Submissions" page is found next to "Upload" page

## Acceptance criteria

- Via email, all current Uploader users are informed of Submissions page availability
- Message has a mix of written and visual content

## To do
- [ ] Develop list of most up to date contacts via Okta account utilization report

**Comment by victorialb-usds** [comment]
@rachelhanster should this be on experience board now or O and O?

**Comment by rachelhanster** [comment]
@victorialb-usds For visibility, let's keep both teams' labels on this ticket, i.e. it currently shows up on both boards.

**Comment by sarahnw** [comment]
@victorialb-usds is this something we need anymore?

**Comment by chris-kuryak** [comment]
Closing by committee. CSV Upload feature.
@drew-usds @lizzieamanning
