### ISSUE TITLE
Write an OpenAPI spec for end-user daily-data (Lists of Deliveries)

### ISSUE THREAD

**Issue by jh765** [CDCgov/prime-reportstream#5233]
As a ReportStream end-user, I want a well-defined endpoint so that I have an efficient way to handle large amounts of data on the daily-data page. (Epic #5157)

### Description/Use Case
End-users need an efficient way to be able to sort and/or filter through large amounts of data on the daily-data page.
Currently, (API) exists,
We are creating a new API based on the Waters endpoint , it will include pagination, date filtering and sorting.
Eventually, when this API is functioning, we will retire the old API
add details to AC

### Dev Notes:
- The first of three parts will be to develop the receiver-facing endpoint. /api/waters/{organization}/deliveries
- URL Parameters that the API takes in
```
        receiver.organizationName,  // Basis for the entire query
        sortOrder,                  // ASC, DESC
        sortColumn,                 // Name of the column to sort on... likeThis, not_this
        resultsAfterDate,           // see Gage's example
        resultsBeforeDate,          //  
        pageSize,                   // pagination size
```
- Returns an array of data for a receiving organization, containing at least these values:
```
        reportId
        dateSent (created_at, in the report_file table)
        itemCount (aka 'total')
        bodyFormat (aka file type) (eg, CSV, HL7)
        receivingOrg
        receivingOrgSvc
        external file name
```
- Reuse as needed existing sort and filter component
- The spec should pass validation

### Acceptance Criteria
- create a new OpenAPI yaml file

**Comment by TurkeyFried** [comment]
![image](https://user-images.githubusercontent.com/2624105/165328260-a8e1d660-de27-4fb0-8560-97caaaf19163.png)
