### ISSUE TITLE
Update application with new LIVD table fields

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#5240]
## Problem statement

The LIVD team has agreed to provide a verson of the LIVD table that has expanded fields. Those fields allow for more accurate identification of test usage authorizations. This is primarily is response the varied usage of OTC. But there may be other applications for the fields.

## What you need to know
 
- New LIVD Document: [https://app.zenhub.com/files/304423150/37f19565-9605-4d3f-9c2e-77aea94fec05/download](https://app.zenhub.com/files/304423150/37f19565-9605-4d3f-9c2e-77aea94fec05/download)

## Acceptance criteria

- [x] LIVD Table can be loaded to the database

## To do

- [ ] replace materialized view "vw_livd_table" based on new table
- [ ] update LIVD tables in /metadata/tables/
- [ ] update covid-19 schema to include new fields
- [ ] update covid-19 schema to remove deprecated fields
- [ ] update settings filters for new fields

**Comment by anshulkumar-usds** [comment]
5/4: Anshul checking with LIVD team to see if they can start including more granular details for FDA attributes.

**Comment by brick-green** [comment]
the LIVD team originally told us they were only going to send the new expanded LIVD table to ReportStream. They explicitly said they could not update the website version ([LINK](https://www.cdc.gov/csels/dls/sars-cov-2-livd-codes.html)). But they did update the website version...so now the livd-table-download tool is broken.

**Comment by anshulkumar-usds** [comment]
@brick-green I'm going to take myself off as an assignee as I believe next steps lie with engineering. Let me know if I can help.
cc @MauriceReeves-usds

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5240?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS

**Comment by BerniXiongA6** [comment]
@sarahnw this is the ticket that @brick-green recommended we increase the priority on -- let me know how you want to re-prioritize this one so we can re-label. Thanks!

**Comment by brick-green** [comment]
merged code change to allow for custom LIVD tables updates via command line
