### ISSUE TITLE
SimpleReport CSV Migration - Must accept separate ordering facility and testing lab name and address info

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#5253]
## Problem statement
There are several current CSV Uploader Senders that are laboratories not physician offices or urgent care centers.  Laboratories must have the ability to provide separate facility name and address information for the Ordering Facility and Testing Laboratory.  This is critical because most STLTs receive results based on the patient state and/or ordering facility state.

## Things know
Example, a test is ordered and collected by a provider from their office in CO.  The patient is visiting CO, but resides in CA. The testing laboratory is in TX.  In this scenario, the result is sent to CA based on the patient state of residence, and CO based on the ordering facility state. 

## Acceptance criteria
- [x] TBD

## To do
- [x] TBD

**Comment by sarahnw** [comment]
@zdeveloper is this something y'all have handled in the CSV port over? Is there anything on the RS side that we need to handle?
