### ISSUE TITLE
MD Resubmits from 4/23 and 4/24

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#5260]
We had a series of delivery failures to MD over the weekend.

The following failed to their secondary feed:
```
0c1c7213-ccf7-4a73-9854-072ba282e85f
f869d495-fb2c-47e1-88b6-d1f7fd0b82a6
a6fdafcd-e4a2-4bd5-8172-858849cb8d6f
```

The following failed to their primary feed:
```
40e1a20d-afb9-4dff-968f-bc0a551921bb 
7b91b1de-90b1-4413-acf5-28873d44dbcc
b2a7f072-0c11-4b0a-adb3-b442176fdb0b
adb5241b-8ea9-4694-9237-3cfb0e60dd20 
7cef17ce-84e0-4814-bd2f-0c9bfeeacef3
509205a4-b91c-4a8c-8da6-6c2ab142b04e
51dc782f-92cb-4a63-bb54-4441affc535d
015ac80b-48bd-4fe1-aa51-51bacb277be5
2aaebee6-5215-4da2-8806-8e81ac57af96
```

We need to reach out to MD and verify that they didn't receive the reports, and that they want them resubmitted.

**Comment by jorg3lopez** [comment]
@Adrian-Brewster @anshulkumar-usds update: All files have been resubmitted to MD. ( 05/16/2022) 
Primary feed:
`covid-19-7b91b1de-90b1-4413-acf5-28873d44dbcc-20220423211501`
`covid-19-40e1a20d-afb9-4dff-968f-bc0a551921bb-20220423191501`
`covid-19-b2a7f072-0c11-4b0a-adb3-b442176fdb0b-20220423231513`
Secondary feed:
`covid-19-20220423191502-0c1c7213-ccf7-4a73-9854-072ba282e85f-secondary`
`covid-19-20220423211502-f869d495-fb2c-47e1-88b6-d1f7fd0b82a6-secondary`
`covid-19-20220423231514-a6fdafcd-e4a2-4bd5-8172-858849cb8d6f-secondary`
`covid-19-20220424011531-adb5241b-8ea9-4694-9237-3cfb0e60dd20-secondary`
`covid-19-20220424031551-7cef17ce-84e0-4814-bd2f-0c9bfeeacef3-secondary`
`covid-19-20220424051544-509205a4-b91c-4a8c-8da6-6c2ab142b04e-secondary`
`covid-19-20220424071500-51dc782f-92cb-4a63-bb54-4441affc535d-secondary`
`covid-19-20220424091500-015ac80b-48bd-4fe1-aa51-51bacb277be5-secondary`
`covid-19-20220424111539-2aaebee6-5215-4da2-8806-8e81ac57af96-secondary`
