### ISSUE TITLE
WA Delivery Failure Resubmits from 4/25/2022

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#5261]
We had two reported AS2 delivery failures for WA on 4/25/2022 that we need to resend to Washington State. In prior cases these were false negatives, where the files were delivered but their system reported a timeout.

We need to confirm if they received the files, and if they did not, resubmit them.

Positive Feed:
`429ae247-6072-4a94-98d5-76cab42f9745`

Negative Feed:
`952d1dbf-f534-4e33-aa00-106ceceab42e `

**Comment by oslynn** [comment]
@jorg3lopez is working on this ticket.

**Comment by jorg3lopez** [comment]
Updagte: Gathered all positive feed files and parsed them. Working on the neg feed. Will send email with files once the negative feed is done.

**Comment by jorg3lopez** [comment]
Updagte: Gathered all positive feed files and parsed them. Working on the neg feed. Will send email with files once the negative feed is done.

**Comment by jorg3lopez** [comment]
@Adrian-Brewster @anshulkumar-usds both files have been resent to WA, one containing 52 test results and another containing 990 rest results.
file names:
`cdcprime_testing_20220425171556_629764`
`cdcprime_testing_20220425171626_951856___neg`

**Comment by anshulkumar-usds** [comment]
5/13: WA was notified. Awaiting confirmation from state.

**Comment by anshulkumar-usds** [comment]
5/16: WA confirmed that they received the files.
