### ISSUE TITLE
Use Topic enum in Receiver

### ISSUE THREAD

**Issue by clediggins-usds** [CDCgov/prime-reportstream#5282]
### Description/Use Case
In the work for #5050 a new enum was introduced to track Topics. It currently has two values - FULL_ELR and COVID_19. Receiver should also use this enum instead of the String topic value.

### Risks/Impacts/Considerations
* Tests may need to be updated.

### Dev Notes:
* All constructors for Receiver will need to be updated
* Tests may need to be updated
* The enum serializes/deserializes properly to the existing string "covid-19" so that should not be a properly

### Acceptance Criteria
* Receivers no longer use the string "covid-19" as a topic value.
* Full pipeline still works

**Comment by jimduff-usds** [comment]
What's the argument for making this an enum?    We have lots of config data (like 'topic') that are not enums.

In an ideal world, you'd want to be able to add a new topic without having to touch the code.   So, let's just have a strong argument as to why this is necessary.
