### ISSUE TITLE
UI: update ReportStream website on how to successfully use daily-data or download site

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#5293]
## Problem statement

As an end user at a public health authority, I want to know how to access and use ReportStream to view and download data.

## What you need to know

- Content has updated the website copy that UI can use to populate in staging ([see shared doc with those changes](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Website%20Customer%20Success%20Center/How%20to%20Use%20ReportStream%20Daily%20Data%20and%20Report%20Details?csf=1&web=1&e=KyngEc))

## Acceptance criteria

- [ ] UI: content updates to be reflected on this static page: https://reportstream.cdc.gov/getting-started/public-health-departments/data-download-guide #accessing-data

**Comment by BerniXiongA6** [comment]
@drew-usds I created this UI ticket for you and @a-chappelear so I can close out[ Content Issue #2621](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/2621). cc: @RakshindaAslam

**Comment by a-chappelear** [comment]
I think this may have been part of the our latest content updates - but want to verify because the content above looks different (but also several months old) @drew-usds @BerniXiongA6

**Comment by BerniXiongA6** [comment]
@a-chappelear this content was created back in April before the MVP website updates. There may have been some changes to RS since these April edits, I’d recommend doing an audit of these edits to make sure they are accurate/or need revisions before making content edits. Happy to consult if needed. cc: @drew-usds

**Comment by fmccaf1** [comment]
Completed in ticket[ 7462](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/7462)
