### ISSUE TITLE
Inform users CSV upload has moved to SimpleReport - After transition

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#5295]
## Problem statement

On the cut-off date, we'll need to disable the Uploader feature in ReportStream and redirect CSV upload users in ReportStream to the relevant portion of SimpleReport and inform them that this feature is no longer available on ReportStream website.

## What you need to know

Designs being worked on as part of #5145

Design: https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=3210%3A21918

## Acceptance criteria

- [ ] The CSV uploader feature is disabled on the ReportStream website
- [ ] The CSV uploader user is informed via app that this feature is no longer available in ReportStream using the content specified in #5145

**Comment by HeatherRienks** [comment]
@bgantick - to add addtl questions to this ticket.

**Comment by RakshindaAslam** [comment]
@bgantick - what information do we need to refine this ticket?

**Comment by bgantick** [comment]
This should go live on/around 7/18 per the [transition comms plan](https://docs.google.com/document/d/1MpcmWD8XrAVAjviGLQhqgXjvGzX_6riNi-24beLPk1E/edit#heading=h.2zejfxt1s30)

**Comment by RakshindaAslam** [comment]
Asking change of language on the banner for availability of Submission History to "until further notice" instead of "3 months". The purpose is to allow for detailed planning of migration of transmission history and sunset date based on audit requirements.
