### ISSUE TITLE
Onboard Neurolab sender

### ISSUE THREAD

**Issue by jbiskie** [CDCgov/prime-reportstream#5297]
## Problem statement

Neurolab needs to be onboarded as an HL7 API sender

## What you need to know

Sample messages are in keybase: prime_dev_ops/sender_info/Neurolab

**Comment by oslynn** [comment]
Emailed instructions for fixing the file and attached the fixed hl7 (neurolab-01e.hl7) back to them @ 2022-05-13.

**Comment by oslynn** [comment]
Steps to onboarding:
1.) Verify Sample.hl7 file from Neurolab.
2.) Add sender entry to organization.yml file
     - name: neurolab
  description: Neurolab
  jurisdiction: FEDERAL
  senders:
    - name: default
      organizationName: neurolab
      topic: covid-19
      customerStatus: testing
      schemaName: hl7/hl7-ingest-covid-19-training
      format: HL7
3.) Add "neurlab" to hhsprotect.jurisdictionalFilter receiver.
#      jurisdictionalFilter: [ "matches(sender_id,.*SafeHealth.*,.*CueHlth.*,.*ImageMover.*,InBios,Strac,AnavasiDx,careevolution,reddyfmc,primary,abbott,lifepoint,hca,prescryptive,pmg,ihealthlabs,mns,detect,hcintegrations,signetic,neurolab)" ]
4.) Create the PR.
5.) Update step 3 using UI in ReportStream.cdc.gov (using okta credential)
6.) Generate API key to give to Neurolab via Keybase.

**Comment by oslynn** [comment]
Updated the setting for prod and staging and organization.yml: 
      timeZone: CENTRAL
      dateTimeFormat: LOCAL

**Comment by oslynn** [comment]
Sent curl command to them in KeyBase.

**Comment by oslynn** [comment]
Review submission for staging.  Downloaded in prime-report
./junk/neurolab/2verify/org/hl7-ingest-covid-19-training-8c873121-18bc-4115-823a-428ab4ac149f-20220622191306.hl7
./junk/neurolab/2verify/org/hl7-ingest-covid-19-training-09921424-73f3-488e-8a93-8b3c7b9cdd70-20220622191757.hl7
./junk/neurolab/2verify/org/hl7-ingest-covid-19-training-b24d9c93-009e-4213-8b80-3e6bda57789f-20220622191902.hl7
./junk/neurolab/2verify/org/hl7-ingest-covid-19-training-d4dc170c-1c1f-4f40-bf58-f31cbf9f22b8-20220621214849.hl7
./junk/neurolab/2verify/org/hl7-ingest-covid-19-training-e489e776-da79-4238-b0f0-4a08960b81d2-20220621212555.hl7

**Comment by oslynn** [comment]
Verified their files:

**Comment by oslynn** [comment]
Email Nancy (CO) to verify messages from Neurolab and get feedback to correct those messages and resubmission in ticket 6180: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/6180

**Comment by oslynn** [comment]
Sent email to TX asking them to verify messages from Neurolab.  Still haven't get answer regarding of verification's result.

**Comment by oslynn** [comment]
Tx messages's validation is confirmed.  Therefore, Neuroloab is ready for production.  I am switching them the production, today.
