### ISSUE TITLE
Investigate causes of 503 responses

### ISSUE THREAD

**Issue by cwinters-usds** [CDCgov/prime-reportstream#5300]

**Comment by JosiahSiegel** [comment]
## [Issue](https://semanticbits.slack.com/archives/C01HFHPNJEL/p1650300058775859):
![Screenshot from 2022-04-18 12-36-49](https://user-images.githubusercontent.com/5522990/165959603-95a258ec-3bad-4efc-8a36-9f50ee4869ad.png)

## Log:
```
AzureDiagnostics
| where (httpStatusCode_s == '503')
    and backendHostname_s startswith 'pdhprod-functionapp'
| where TimeGenerated >= todatetime("4/16/2022") and TimeGenerated <= todatetime("4/19/2022")
| summarize count() by Category, ErrorInfo_s
```
![image](https://user-images.githubusercontent.com/5522990/165959949-4eb7dc7e-d33e-4fe4-89e8-45a2510c0ef9.png)

## [Potential cause/solution](https://docs.microsoft.com/en-us/azure/frontdoor/troubleshoot-issues#:~:text=If%20requests%20going%20through%20Azure,manager%20and%20select%20Edit%20endpoint.):

If requests going through Azure Front Door result in a 503 error response code, configure  ❗**Origin response timeout**❗ (in seconds) for the endpoint. You can extend the default timeout to up to 4 minutes, which is 240 seconds. To configure the setting, go to Endpoint manager and select Edit endpoint.

**Comment by JosiahSiegel** [comment]
# Follow the failure through the logs.

## It appears that the function app returns successfully quickly, while the front door does not pick up the successful response.

```
AzureDiagnostics
| where TimeGenerated >= todatetime('2022-04-16T18:43:35.935Z') and TimeGenerated <= todatetime('2022-04-16T18:43:41')
    and httpStatusCode_s == "503"
| project ResourceType, requestUri_s, timeTaken_s, backendHostname_s, OperationName, ErrorInfo_s
```
![image](https://user-images.githubusercontent.com/5522990/166000514-c6fdaacd-6241-4703-811f-581f64a347e1.png)
```
FunctionAppLogs 
| where TimeGenerated >= todatetime('2022-04-16T18:43:35.935Z') and TimeGenerated <= todatetime('2022-04-16T18:43:41')
 and FunctionInvocationId == "b3aad6c9-8e9d-403b-a174-ee138eec401a"
```
![image](https://user-images.githubusercontent.com/5522990/165999241-1fd6567b-3495-4469-ba42-f56b6ef5c7d0.png)

```
requests
| where timestamp >= todatetime('2022-04-16T18:43:35.935Z') and timestamp <= todatetime('2022-04-16T18:43:41')
| extend seconds=duration / 1000
| where customDimensions.InvocationId == "b3aad6c9-8e9d-403b-a174-ee138eec401a"
```
![image](https://user-images.githubusercontent.com/5522990/165999608-fb406df8-aacc-4ab0-9282-a6215038dc00.png)
![image](https://user-images.githubusercontent.com/5522990/165999646-cb788f7a-6949-4240-a087-eb94c2d1ddea.png)
