### ISSUE TITLE
Admin Settings: Refactor meta tag information

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#5304]
## Problem statement

The pipeline team would like to remove the "meta" JSON field from any Settings API, after moving it's content to the top level of the response. Currently, the response looks like this

```json
{
    "name": "abbott",
    "description": "Abbott",
    "jurisdiction": "FEDERAL",
    "stateCode": null,
    "countyName": null,
    "filters": [],
    "version": 1,
    "createdBy": "qop5@cdc.gov",
    "createdAt": "2021-12-23T15:21:36.449662Z",
    "meta": {
        "version": 1,
        "createdBy": "qop5@cdc.gov",
        "createdAt": "2021-12-23T15:21:36.449662Z"
    }
}
```

Once we refactor the front end to pull "version", "createdBy" and "createdAt" from the top level of the response, pipeline will then remove "meta" entirely.

## What you need to know

"Meta" data is primarily used in DisplayMeta.tsx, and in the version control checks within AdminOrgEdit, EditSenderSettings and EditReceiverSettings (in each page's ShowCompareConfirm and SaveXyzData methods)

## Acceptance criteria

- [ ] Site will function normally with the "meta" JSON field removed from the API response

## Relates to

#4325

**Comment by HeatherRienks** [comment]
Per our convo in Sprint Planning, @sethdarragile6 recommends to hold off on this for now.

**Comment by sethdarragile6** [comment]
Finally retested locally with a fresh environment, and was not able to reproduce the weirdness I was initially seeing (which, for the record, was that the new top-level meta information was not updating with the (soon to be legacy) meta tag info. Long story short- this ticket should not be open for business! @HeatherRienks @bgantick @mreifman
