### ISSUE TITLE
API Internal Research: Research Plan

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#5326]
## Overview
As ReportStream, orients towards STLTs and API sender, we need to understand teams members workflow and processes; what they see as issues and priorities and why in order to develop blueprints. 

## Participants
Internal reportstream team members 

**Interview subject(s)**: [name/organization/etc]
Joel Biskie
API O and O
API backend engineers - Pipeline team
Dev ops
Experience engineers

## Background
- [ ] Have we had previous contact/meetings/etc with the participant?
- [ ] Look into the the population/individual we're meeting with.
- [ ] Desk research on the participants and teams including documentation

## Acceptance Criteria
- [ ] 1 - 2 page research plan

**Comment by RakshindaAslam** [comment]
@RakshindaAslam - Do not need a ticket for research plan. Work with other RS teams on this. Can close this ticket.

**Comment by RakshindaAslam** [comment]
@victorialb-usds , @drew-usds - Is this ticket planned as a research ticket for program wide processes and tools improvement? If you have capacity, this may need to be done outside the sprint or closed. Let us know. cc @HeatherRienks

**Comment by chris-kuryak** [comment]
Closing by committee. Old issue.
@drew-usds @lizzieamanning
