### ISSUE TITLE
Rick H Offboarding

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#5328]
# Offboarding checklist

Note: please do not put sensitive information here (issues are public)

Feel free to edit list and ~strike through~ any items that do not apply.

## Engineering specific:
- [x] Change GitHub access level
- [ ] Zenhub
- [ ] Azure (CDC as a result of ActiveDirectory)
- [x] PagerDuty
- [x] Splunk
- [x] Docker Desktop license assignment

## General:
- [x] Revoke Okta accounts (Search for name, agency email, and contractor email)
  - [x] staging
  - [x] prod
- [x] Slack access to channels
- [ ] Metabase
  - [ ] staging
  - [x] prod
- [ ] Office 365 (CDC as a result of ActiveDirectory)
- [ ] Keybase
  - [ ] VPN creditials in `/prime_dev_ops/vpn` (revoke?)
  - [x] Access to keybase itself
- [ ] Mural
- [ ] Lucid Chart
- [ ] Any additional CDC-specific off-boarding (did they get a PIV?)

## Workflow:
- [ ] Reassign any github issues
- [x] Verify no open git PRs
- [ ] Delete any old, open branches (maybe work in progress)
- [ ] Set Away message in CDC Outlook saying they've left and who to contact instead. 
This is required since it takes time for CDC to deactivate their account.

**Comment by MauriceReeves-usds** [comment]
@TomNUSDS - I suspended his account in Okta Prod. If you can do Staging that would be helpful. I have removed him from KeyBase. I'll remove his access in GitHub and metabase as well.

**Comment by TomNUSDS** [comment]
Thanks for doing prod. OktaPreview done.

**Comment by TomNUSDS** [comment]
@cwinters-usds Any items you can check off as done?

**Comment by cwinters-usds** [comment]
@TomNUSDS all the ones I can do are done; I either (a) verified no account exists or (b) deactivated/removed the account for:

* Slack
* Docker
* PagerDuty

Was he offboarded at CDC? Typically they're very thorough and quick but his account is still active on Azure.

**Comment by Adrian-Brewster** [comment]
@TomNUSDS @cwinters-usds Just following up in this (we are cleaning up our ZenHub board). Can you confirm if this can be closed out?

**Comment by cwinters-usds** [comment]
@Adrian-Brewster do you know if Rick was offboarded at CDC? His Active Directory Azure accounts (normal and -su) are still showing up as assigned to all the relevant groups.

**Comment by TomNUSDS** [comment]
Right. Adrian, maybe one way you can check yourself is if you go into Outlook and create a New Email Message, his name still auto completes.
Same for MS Teams if you try to start a chat with him.

I assume when he's deactivated, these should stop working, right @cwinters-usds ?

**Comment by TomNUSDS** [comment]
Seems like there are still:
- [GH Issues](https://github.com/CDCgov/prime-reportstream/issues/assigned/rhood23699) and 
- [GH Branches](https://github.com/CDCgov/prime-reportstream/branches/all?query=rhood)
still owned by `rhood`?
