### ISSUE TITLE
Write an OpenAPI spec for end-user detailed-report (List of Facilities for a Report)

### ISSUE THREAD

**Issue by JGreenFearless** [CDCgov/prime-reportstream#5333]
As a ReportStream end-user, I want a well-defined endpoint so that I have an efficient way to handle large amounts of data on the report-details page. (Epic https://github.com/CDCgov/prime-reportstream/issues/5158)

### Description/Use Case
Provides an easy to use reference for the new endpoint. As users integrate to the new endpoint, this documentation makes the process much simpler. Additionally, the Experience team can generate visual documentation using these spec files.

### Risks/Impacts/Considerations
Will require UI changes for the frontend to use the new features.

### Dev Notes:
* Have the Experience team review the spec as part of the PR to establish what UI changes are needed
* OpenAPI docs can be verified using Linting programs and documentation generators
* Facilities and Report Details might need to be two separate queries
* Old implementation is in `HistoryFunctions.kt`, new code style is in `SubmissionFunction.kt`

### Acceptance Criteria
* All the expected endpoints and parameters are included in the API doc
* Proof that the doc is built with the valid OpenAPI format

**Comment by jh765** [comment]
Merged in PR 5384
