### ISSUE TITLE
Implement list of facilities query for detailed-report page

### ISSUE THREAD

**Issue by JGreenFearless** [CDCgov/prime-reportstream#5336]
As a ReportStream receiver, I want to see the facilities for a given delivery ID, so I can get more information as to its status.

### Description/Use Case
RS needs to allow a receiver to fetch details of a delivery that happened to their organization. An initial mock of data will ensure that the URL parameters that the API takes in can be understood, and that the data sent to the receiving organization is also properly handled.

### Acceptance Criteria
- response data structure conforms to the openAPI spec for this API
- The endpoint returns data from the database that matches the parameters passed in

**Comment by TurkeyFried** [comment]
Facilities come from the metadata, and do not have a numeric or date value to use for pagination.

We may need to make this be sorting only.
