### ISSUE TITLE
Create Flyway script for the improve Zipcode de-identification

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#5340]
A flyway script is created that will update all of the existing records in covid_result_metadata that will apply this same logic to the data there.
The zip codes that this applies to are not hardcoded into the logic, but instead come from a table loaded in the DB using our new table logic like LIVD data, etc

Please see ticket #5232 for more detail.

**Comment by Adrian-Brewster** [comment]
After meeting with USDS attorneys, we have determined that this is not a requirement.  Will align with APHL and others going forward but does not need to be applied retroactively.
