### ISSUE TITLE
Add Patient Country to the COVID Result Metadata Table

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#5347]
### Description

We added the `patient_country` field to the COVID-19 schema a while back, but it is not part of the COVID Result Metadata Table. We need to add it to the table, and we should index it as well.

### Background 

When someone sends a file into the application, ReportStream collects deidentified data and saves it to the `covid_result_metadata` table for use in reporting. Currently we are not tracking the patient_country field in that table, and we should be.

### Acceptance criteria:

- The `getDeidentifiedResultMetaData` method in Report.kt is updated to write to the `patient_country` field
- A flyway script is created that adds the `patient_country` field to the `covid_result_metadata` table. the script also includes an index on the column. The field should accept character data, be a reasonable length, and allow for null values
- The `patient_country` field is trimmed to null if it is empty
- This should include unit tests to verify that nothing breaks
- Create a fake file that includes test data, and has a few different countries in it for patient_country
- Send the data to your local Docker container
- Verify the data you send is saved into the `covid_result_metadata` table with the correct user country

**Comment by Adrian-Brewster** [comment]
@MauriceReeves-usds Are you currently working on this?

**Comment by MauriceReeves-usds** [comment]
@Adrian-Brewster I am not. Mani is. I told him he should wrap it up so he can head over to the Pipeline team and coordinate with you.
