### ISSUE TITLE
On-call PagerDuty person only gets notified for sftp failures associated with Active customers

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#5353]
As an on-call person, I want to be notified in PagerDuty for sftp failures only when they occur with an _Active_ customer so that I only get notified about Active customers.  (Right now, the triggers occur for Inactive and Testing customer statuses too)

### Risks/Impacts/Considerations
- Risk with _not_ doing this is that sftp failures are not noticed because they "cry wolf" too often.

### Dev Notes:
- How this works:  logger.fatal creates an log entry with the string "FATAL-ALERT".  Then PagerDuty should trigger when it sees FATAL-ALERT in the logs, and notify whoever is on call.
- logger config for this is in `src/main/resources/log4j2.xml` 
- Currently PagerDuty is not picking up FATAL-ALERT, because it was triggering too often, so Chris turned it off

### Acceptance Criteria
- Fatal alerts for sftp failures only occur when the associated with a receiver that has status Active, not Testing or Inactive.

**Comment by jimduff-usds** [comment]
Original work was in #3736

**Comment by clediggins-usds** [comment]
Confirmed by Jeremy, this has been re-enabled.
