### ISSUE TITLE
MD - Send Errors Investigation

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#5364]
The last mile problems showed that several files for MD failed to deliver due to a send-error issue.

Checking with MD to understand if there is a known issue on their side, and if they need us to terminate the secondary feed.

Attached list of failures:

**Comment by anshulkumar-usds** [comment]
[https://app.zenhub.com/files/304423150/7eb6f068-3cb1-4c20-abb0-86830c715cdd/download](https://app.zenhub.com/files/304423150/7eb6f068-3cb1-4c20-abb0-86830c715cdd/download)

**Comment by anshulkumar-usds** [comment]
5/5/: Checked with MD again for updates

**Comment by Adrian-Brewster** [comment]
Kristy Lunquest requested that we resend these files @anshulkumar-usds

**Comment by anshulkumar-usds** [comment]
@jorg3lopez do you have capacity to work on this? Assigning to you for now.

**Comment by Adrian-Brewster** [comment]
Jorge is going to work on this now and then move back to Washington resends. @jorg3lopez

**Comment by jorg3lopez** [comment]
@anshulkumar-usds @Adrian-Brewster All messages have been resent to MD. (05-12-2022)
file names:
`covid-19-20220430051543-4075e341-ca98-4514-bc8e-d57de2460ec0-secondary`
`covid-19-20220430111513-db3b37d9-1b04-44a6-b0bd-001fe9a254fa-secondary`
`covid-19-20220501111527-8c726598-c83b-47e7-b8d9-ed71dca51469-secondary`
`covid-19-20220501131548-d2fa10a9-1373-4c87-b88e-658ec947217c-secondary`
`covid-19-d9f94e33-b75e-4d8f-b195-0fb43cbfc00a-20220501131546`

**Comment by anshulkumar-usds** [comment]
5/13: MD notified; awaiting confirmation
