### ISSUE TITLE
Content for the NIH link on ReportStream

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#5380]
## Problem Statement
As ReportStream organization, we want to increase our outreach and the ways that potential senders are made aware of our Products and Services by sharing ReportStream information on other government agency websites that serve our customers.

## What you need to know
-  We have an opportunity to provide an overview of ReportStream on the NIH site. We can have our own menu item on the left navigation bar. Similar content to this: https://www.nibib.nih.gov/aphl-workflow
([This came from Initial ticket #5011](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5011))
-See Rick Hawes' ticket #4598

## Acceptance criteria
- [x] Styled as the rest of NIH site
- [x] Contents include: ReportStream - what it is, who makes it, that it's an option for sending OTC data, how it works, that it's free, what the limitations are, and a call to action (how to get started).

## To do
- [x] Content: Create web copy that includes AC 
- [x] Save deliverable as Shared Doc and send to NIH (NIH handles the content publishing)

**Comment by RakshindaAslam** [comment]
@BerniXiongA6 - Can we update this with A/C and description?

**Comment by RakshindaAslam** [comment]
@BerniXiongA6 for A/C and other info.

**Comment by BerniXiongA6** [comment]
Ticket details and AC updated, ready to be sized!

**Comment by BerniXiongA6** [comment]
Updates on 5/23: Content will be completed by Tuesday morning 5/24/2022.

**Comment by BerniXiongA6** [comment]
Updated on 5/23/2022: Content is completed for RS's web copy on NIH website - [see SharePoint doc](https://cdc.sharepoint.com/:w:/t/USDSatCDC/EQr1TNz7B85IlfVPgPFUr2YBqlaXty25I2XeXqiTpOdJ9A?e=mkucJL).  cc: @RakshindaAslam

**Comment by BerniXiongA6** [comment]
Hi @RakshindaAslam - I'll share this for review in design sync today. I don't have a contact yet for NIH so I won't be sending to them until we review/approve it here first. Thanks!

**Comment by BerniXiongA6** [comment]
Hi @RakshindaAslam - [here's the updated RS content for NIH page](https://cdc.sharepoint.com/:w:/t/USDSatCDC/EQr1TNz7B85IlfVPgPFUr2YBSMx1RETcqY31SaFiVL3u-g?e=gx2Zh0). I made the changes as we discussed this AM. The additional content I added in the "how RS works" section came from this PPT (slide 22 - also look at its note section). We can close this ticket and send off the content to our NIH contact when you're OK with this revision!

**Comment by RakshindaAslam** [comment]
@BerniXiongA6 - the revisions look great!
@drew-usds - do we have a contact for NIH to send this to?

**Comment by BerniXiongA6** [comment]
6/6/2022: Content work is done from Exp. team's end - All that's left is for BX to follow up with NIH to discuss their edits/feedback regarding ReportStream's feature on their site. I think the best next step is to make sure we're clear about NIH/NIBIB goals for featuring their partners when I reach back out to Andrew Weitz. That will help us determine what kind of revisions we want to make to their RS content based on what we learn. [Here's the project folder](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Web%20Copy%20on%20NIH%20Website?csf=1&web=1&e=p50zSp) I've created to document this progress (email comms, the original content we sent, etc.). cc: @RakshindaAslam @rachelhanster @kjt9cc
