### ISSUE TITLE
Email Notification SOP- "Built for you: New in Reportstream" 

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#5389]
## Problem statement

As a ReportStream organization, I want to establish a standard operation procedure on when and how these emails will be sent out. 

## What you need to know
**This will be an exploratory ticket conducted by Experience Team Content.**

PROPOSED RELEASE NOTES 2.0 PROCESS:
- Engineers make two changes to existing release notes operations: 1) link PR with original ticket that has user outcome(s) described; 2) Write PR title as [original ticket number] + [title]. Detailed proposal [here.](https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Releases/ReleaseNotesProposal.pptx?d=w961c0804374b48f98df066d3fcd3ce2c&csf=1&web=1&e=f0wVYU ) TLDR [one-pager here](https://cdc.sharepoint.com/:w:/t/USDSatCDC/ERjfi1u0TN5OubshesUvnSQBgOLOEO4Ig5XWQYfskgYh3g?e=6OqlRB).
- Product managers: create user-friendly content, day after every sprint
- Content/Experience Team: ensures content from Product is in plain language and adheres to ReportStream content style guidelines 
- Operations send out the email after every Major release / pre-determined frequency

[Example 1](https://www.intercom.com/changes/en) and [Example 2](https://mailchimp.com/whats-new/)
CONSIDERATIONS:
- [ ] Who will get these email notifications? 
- [ ] How will the contents be added to the email?
- [ ] What will be considered Major release?
- [ ] Or what will be the pre-determined frequency?
- [ ] What will be the protocol and time-frames for creating the content/reviewing the content/sharing the contents with the O&O team, sending out the email and storing them?

## Acceptance criteria
DRAFT OF CONTENT STRATEGY:
- [x] Clear and easy to follow DRAFT SOP for sending out these email notifications
- [x] Establishes roles and responsibilities for each task
- [x] Establishes timeframes for each task
- [x] Consults O&O (SME = Adrian B.) to consider current and ideal future state outreach process

**Comment by BerniXiongA6** [comment]
Content update 5/12/2022: This ticket can be worked on simultaneously with Content activities in [Issue # 5382](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5382). Pulling into Sprint Backlog for "Content" spec work that can be done this sprint.

**Comment by BerniXiongA6** [comment]
Content update 5/23/2022: Content work should be done by EOD today. Can have ready for review for Design Sync tomorrow 5/24. cc: @a-chappelear @RakshindaAslam

**Comment by BerniXiongA6** [comment]
Updated 5/23/2022: [See DRAFT on SharePoint](https://cdc.sharepoint.com/:w:/t/USDSatCDC/EaL2QHqgxYJOpbaAeJ26plIBPTvps1XQAopiDSDco8yqtw?e=qbD3wp). SharePoint saves the format it in a wonky way. For best view, go to link and download the file to your desktop. cc: @a-chappelear @RakshindaAslam
