### ISSUE TITLE
auto-populate the state based on the zip code

### ISSUE THREAD

**Issue by kjt9cc** [CDCgov/prime-reportstream#5407]
For PID-11.4,  auto-populate the state based on the zip code, if the state was blank in the original message.  In situations where a zipcode maps to more than 1 state, perform no operation / no auto completion.

Rationale: NBIB folks are trying to rally device manufacturers around streamlining the information they collect in order to improve conversion. Zip will be required but not state.

**Comment by BerniXiongA6** [comment]
duplicate of # 5700
