### ISSUE TITLE
PII Deidentification Logic - Add Translation Option to Specify Deidentification Placeholder

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#5410]
NIH has asked us to align our deidentification logic with with APHL currently produces. When they remove a value for deidentification purposes they replace with `<DEIDENTIFIED>` to distinguish it from being blank. I think this is a fine idea, but I don't want us to hard code this. Instead we should add this as a translation configuration option that receivers can set per their preferences. If one is NOT provided, we will use empty string per our current functionality.

### Acceptance Criteria
- Add a new parameter to the translation configuration class that allows us to specify placeholder text for deidentification. This *WILL NOT* go into the HL7 translation configuration, but must go into the base translation configuration because it must be present in all the different outbound formats (CSV, HL7, etc)
- The parameter must default to empty string if not specified
- The deidentify method in `Report.kt` will use this placeholder value if it exists
- Unit tests are updated to verify the base case (no placeholder text) and the new case for using a placeholder

### Other Notes
- Once we make this change, we will need to notify HHSProtect and NIH that we are able to provide the APHL style value for those who want it and coordinate a time to cut over

**Comment by TomNUSDS** [comment]
Interesting that it's `<deidentified>` vs  [deidentified]` or just `deidentified` I guess if it's in a quoted string value the the various parser _shouldn't_ care.

**Comment by RickHawesUSDS** [comment]
So, the HHS-protect's team request is for `<DEIDENTIFIED>` in their mail message. I would make the `deidentifiedValue` a string value with default "" setting along with the existing `deidentify` boolean.
