### ISSUE TITLE
PII Deidentification Logic - Deidentify Patient Age if Greater than 89

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#5412]
We need to identify the patient age deidentification logic so that if a patient's age is greater than 89 years old, we replace it with `0`. 

### Acceptance Criteria
- If a patient has an age greater than 89, the deidentify method replaces it with 0 for outbound messages
- Unit tests are updated to test this new logic

**Comment by MauriceReeves-usds** [comment]
Pulling into the sprint.

**Comment by BerniXiongA6** [comment]
@MauriceReeves-usds to fix merge conflicts cc: @sarahnw @BerniXiongA6
