### ISSUE TITLE
LIVD API no longer appears to work

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#5414]
At some point the LIVD API available at `metadata/livd` has stopped working. We need to get this stood back up.

### Background
When I attempt to invoke the LIVD API at `https://prime.cdc.gov/api/metadata/livd` I no longer get the data I expect but instead get back an error response:

```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<title>CDC Test Page</title>
	<link rel="stylesheet" href="/apology_files/style.css">
</head>

<body>
	<h1>Centers for Disease Control and Prevention</h1>
	<h2>Test Page</h2>
	<p>This is a test page for prime.cdc.gov.</p>
	<p>This page will appear if an error or timeout occurs at origin.</p>
	<p><span>Reference ID: </span></p>
</body>

</html>
```

### Acceptance Criteria
- The LIVD API is functional again, including searching, etc
- The API is updated to include the new fields being added such as isOTC, etc that are now in the LIVD table
- Searching works on the new fields as well, so `https://prime.cdc.gov/api/metadata/livd?manufacturer=Abbott` will return all records for Abbott, and `https://prime.cdc.gov/api/metadata/livd?isOtc=true` returns all the OTC tests

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5414?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS

**Comment by BerniXiongA6** [comment]
Updates from [Slack thread ](https://agilesix.slack.com/archives/C025F5W5Q7L/p1660844018723959) on 8.17.2022:

Per Emma Stephenson:

> Berni and Sarah, we’re hoping to use the LIVD API to standardize our device creation. Right now it’s a manual process that requires someone to look at the LIVD table, pull the relevant info, and create a new entry in our database. The goal is that by pulling directly from the LIVD table we can avoid that manual process, and make all devices available to users so they don’t have to request specific ones for engineers to process as is currently done.
> We’re in the initial planning phases now, so I don’t imagine we would be trying to productionize this for several weeks at the earliest. We’re hoping to get this done before we need to start working on additional diseases in earnest, which I believe will likely happen in late October/early November, but it’s not a hard deadline.
> It may help to clarify that I don’t think we need the full API functionality - we essentially need something that can give us the contents of the entire LOINC mapping sheet, not necessarily to be able to look up devices on a per-row basis. It was my understanding from  Jim Duff that that functionality still works through the following endpoint: https://prime.cdc.gov/api/lookuptables/LIVD-SARS-CoV-2/12/content. So for our purposes, the existing API might work just fine (I’m not sure what exactly about the existing API is broken)

@sarahnw @brick-green -- So we're looking at late-Sept to early mid-October to complete this work given SR's timeline, does this seem feasible?

**Comment by oslynn** [comment]
@emmastephenson @sarahnw @BerniXiongA6.  The API is fixed, now.

**Comment by BerniXiongA6** [comment]
@brick-green will review and close out when approved

**Comment by oslynn** [comment]
Done
