### ISSUE TITLE
Intrivo - Sender onboarding

### ISSUE THREAD

**Issue by jbiskie** [CDCgov/prime-reportstream#5419]

**Comment by sliu1000** [comment]
Karim Lalani (Klalani@intribo.com) has completed the TOS. @jbiskie is there anything else the Karim needs to do?

**Comment by sliu1000** [comment]
@jbiskie 
Karim Lalani from Intrivo is looking for an update on the recent sample messages sent. They would like to understand what the next steps/timeline is to start operating in full production mode.

**Comment by sarahnw** [comment]
@jorg3lopez Intrivo is basically good to go once we get 5700 released. they did send over more test messages asking us to look at them. could you help with that this sprint?

**Comment by sliu1000** [comment]
@jorg3lopez 

Hi Jorge, Intrivo identified some issues with their recent testing.  Please see below the list of errors they receive in response to their submission:

"message" : "For fl-phd.elr, filter hasValidDataFor[patient_dob] filtered out item `a419be90-b378-46c7-b734-b1c64e2e3a71`" 
      "message" : "For hhsprotect.elr, filter doesNotMatch[processing_mode_code, T, D] filtered out item `a419be90-b378-46c7-b734-b1c64e2e3a71`"
      "message" : "For hhsprotect.elr, filter doesNotMatch[processing_mode_code, T, D] filtered out item `f3950988-1ebf-44d2-8789-2a6c6d5ef234`"
      "message" : "For vt-doh.elr, filter doesNotMatch[processing_mode_code, T, D] filtered out item `f3950988-1ebf-44d2-8789-2a6c6d5ef234`"
      "message" : "For vt-doh.elr, filter hasValidDataFor[message_id, equipment_model_name, specimen_type, test_result, patient_last_name, patient_first_name, patient_dob] filtered out item `f3950988-1ebf-44d2-8789-2a6c6d5ef234`"
      "message" : "For vt-doh.elr-otc, filter atLeastOneHasValue[Y, test_authorized_for_otc, test_authorized_for_home, test_authorized_for_unproctored] filtered out item `f3950988-1ebf-44d2-8789-2a6c6d5ef234`"
      "message" : "For vt-doh.elr-otc, filter matches[sender_id, ImageMover] filtered out item `f3950988-1ebf-44d2-8789-2a6c6d5ef234`"
      "message" : "For vt-doh.elr-otc-test, filter atLeastOneHasValue[Y, test_authorized_for_otc, test_authorized_for_home, test_authorized_for_unproctored] filtered out item `f3950988-1ebf-44d2-8789-2a6c6d5ef234`"
      "message" : "For vt-doh.elr-secondary, filter doesNotMatch[processing_mode_code, T, D] filtered out item `f3950988-1ebf-44d2-8789-2a6c6d5ef234`"
"submissionId" : 17533344,
 "overallStatus" : "Not Delivering"

**Comment by shy2cdc** [comment]
We are currently blocked by these below errors.

Could you please assist us in identifying the issues with our recent test messages?

This is the list of errors we are receiving in response to our submission:

"message" : "For fl-phd.elr, filter hasValidDataFor[patient_dob] filtered out item a419be90-b378-46c7-b734-b1c64e2e3a71"

      "message" : "For hhsprotect.elr, filter doesNotMatch[processing_mode_code, T, D] filtered out item a419be90-b378-46c7-b734-b1c64e2e3a71"

      "message" : "For hhsprotect.elr, filter doesNotMatch[processing_mode_code, T, D] filtered out item f3950988-1ebf-44d2-8789-2a6c6d5ef234"

      "message" : "For vt-doh.elr, filter doesNotMatch[processing_mode_code, T, D] filtered out item f3950988-1ebf-44d2-8789-2a6c6d5ef234"

      "message" : "For vt-doh.elr, filter hasValidDataFor[message_id, equipment_model_name, specimen_type, test_result, patient_last_name, patient_first_name, patient_dob] filtered out item f3950988-1ebf-44d2-8789-2a6c6d5ef234"

      "message" : "For vt-doh.elr-otc, filter atLeastOneHasValue[Y, test_authorized_for_otc, test_authorized_for_home, test_authorized_for_unproctored] filtered out item f3950988-1ebf-44d2-8789-2a6c6d5ef234"

      "message" : "For vt-doh.elr-otc, filter matches[sender_id, ImageMover] filtered out item f3950988-1ebf-44d2-8789-2a6c6d5ef234"

      "message" : "For vt-doh.elr-otc-test, filter atLeastOneHasValue[Y, test_authorized_for_otc, test_authorized_for_home, test_authorized_for_unproctored] filtered out item f3950988-1ebf-44d2-8789-2a6c6d5ef234"

      "message" : "For vt-doh.elr-secondary, filter doesNotMatch[processing_mode_code, T, D] filtered out item f3950988-1ebf-44d2-8789-2a6c6d5ef234"

"submissionId" : 17533344,
  "overallStatus" : "Not Delivering"

**Comment by sliu1000** [comment]
**Updated Status/Communications:**

**Comment by jorg3lopez** [comment]
##### Update:

I received the test file from Karim. The next step is to replicate the error and give feedback.

**Comment by sliu1000** [comment]
@jorg3lopez Follow-up questions from Karim (Intrivo).

Is there any documentation/list of states like FL, where this would pose an issue?

**Communication/Background Info:**

**Comment by jorg3lopez** [comment]
#### Update:
Intrivo sent new test data to review. I will review and provide an update soon.

**Comment by BerniXiongA6** [comment]
@kjt9cc -- Jorge is reviewing the new test data from Intrivo... he's committed to updating us on this soon. We're getting close!

**Comment by shy2cdc** [comment]
Karim 8/17 5:23pm 

We've sent 20 messages to Vermont (submissionId 18541085) and another 20 to Hawaii (submissionId 18541134).

**Comment by BerniXiongA6** [comment]
Hey @sarahnw Per @jorg3lopez -- we should let Hawaii and Vermont know that they will be receiving data from Intrivo, and to let us know if there are any issues due to the files. Jorge will be sending this data manually once he has reviewed the files. I'm happy to reach out if we know who the contact persons are? cc: @shy2cdc

**Comment by shy2cdc** [comment]
@BerniXiongA6 I forgot to respond to you I'm sorry. I reached out to Vermont and Hawaii last week.

**Comment by jorg3lopez** [comment]
#### Update:
Still waiting for VT to get back to us. Intrivo has voiced that this delay is affecting their timelies on their projects.

**Comment by BerniXiongA6** [comment]
I sent this email to VT today with a cc: to @sarahnw and @jorg3lopez 

> Hello Vermont team!
> 
> My colleague, Sarah White, introduced me a couple of weeks ago as the new delivery manager for our Onboarding and Operations team. While Sarah is currently out on vacation, I'm following up to see if your team has any feedback regarding Intrivo's previous submission. Intrivo has expressed concern that the delay in getting their data validated is beginning to affect their timelines for other projects, so they are asking us for next steps. If you have any insights into this matter or how we can help, we're happy to assist.
> 
> Thank you!
> 
> Best,
> Berni
>

**Comment by BerniXiongA6** [comment]
While we await a response from VT DOH, I also replied to Karim to let her know current status. cc: @sarahnw @jorg3lopez 

> Hi Karim,
> 
> Thank you so much for reaching out. My colleague, Sarah White, is currently on vacation so I'll be handling this issue in her absence. The quick update is, Jorge and I are still waiting on Vermont Dept. of Health to respond with feedback after your previous submission. I put in a note to them today. I let them know of the urgency of this request, so hopefully we hear from them soon. Please feel free to reply if you have any other questions. I'm happy to help and Jorge is standing by to assist technically as well as we hear more from Vermont.
> 
> Thanks again!
> 
> Best,
> Berni
>

**Comment by sliu1000** [comment]
@BerniXiongA6 @jorg3lopez 

We received a follow-up on them not receiving any additional messages beyond 8/19.  Please resend corrected version.

Please see below the original communication:

Hi,

We haven’t received any additional messages beyond the 8/19 ones that failed. If you can resend the corrected versions of those or new ones we can validate them.

Thanks,
Jessie

**Comment by sliu1000** [comment]
Follow-up email sent from Karim at Intrivo -

Berni, and Jorge.

I hope you had a nice weekend.

I wanted to **check the status** of the **recent requests we sent for MA** and the errors that I shared in my previous email.

Also, I **wanted** to see if we might also **test a sample against Colorado.**

Please advise.

Karim

**Comment by sliu1000** [comment]
Update from Kaleigh from MA State:

Hi Berni,

We found this file in our production portal.  In the future, can you send test files to us via email attachment?  These cases did not error so they went into our reporting database as if they were actual cases.

Also, just a reminder we would only want provider administered home tests.

**Comment by shy2cdc** [comment]
Message from Karim (Intrivo) 9/8 at 7:40pm

Hello, Berni and Jorge,

Any updates on this?

I wanted to check the status of the recent requests we sent for MA and the errors that I shared in my previous email.

Also, I wanted to see if we might also test a sample against Colorado.

**Comment by sliu1000** [comment]
Update from Karim from Intrivo:

That's great news, Jorge.
We'll make the change to the processing_code to P in our production environment and wait to hear from you on Monday.

Best regards,
Karim Lalani | Engineering Lead
📧 klalani@intrivo.com | www.intrivo.com

On Fri, Sep 9, 2022 at 11:44 AM Lopez, Jorge (CDC/DDPHSS/OD/HITSSU) (CTR) <rut7@cdc.gov> wrote:
Hi Karim,

Thank for being patient, we got feedback from MA and all messages checked out without any errors. Our next step is to fully, move to production. The only change that you have to do on your end is to change the processing code from T to P. Also, it is normal to have warnings and errors show up on the receivers' end during this transition. This is because some systems might need minor adjustments when digesting the data. This is totally fine; we will keep you updated if this happens.

One last thing, we will move you to production starting Monday, next week. I will reach out and confirm when this happens. Thank you, have a wonderful weekend.

Jorge

**Comment by shy2cdc** [comment]
Email from Karim 9/30 at 8:04pm

Hello all,
I wanted to share an update regarding our integration with ReportStream.
We processed a batch today in which we processed test results for the entire month of September for all users who had provided consent.
Close to 750 test results passed our selection criteria and those reports were sent over to ReportStream.

When you get a chance, please review the submissions and let us know if you notice any errors.
