### ISSUE TITLE
CLX - Sender onboarding

### ISSUE THREAD

**Issue by jbiskie** [CDCgov/prime-reportstream#5420]

**Comment by BerniXiongA6** [comment]
Updates 8/15/2022: Last comms w/ sender from PR # 6040:

> commented on Jul 15
> @jbiskie User asking for next steps.
> 
> From: John Gassenheimer jgassenheimer@siriusiq.com
> Sent: Thursday, July 14, 2022 4:58 PM
> 
> Hi Joel,
> 
> We were able to use the keys you sent to connect and receive responses. We have the HL7 configured and ready to send. Let me know what the steps are to get the project going so we can start sending reports to report stream in addition to APHL.
> 
> Regards,
> 
> John

Next steps are to reach out to sender and finish onboarding to Prod. cc: @sarahnw @kjt9cc

**Comment by oslynn** [comment]
@BerniXiongA6 I will take over the sender from Joel.  Would you please forward me this email chain?

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 will contact the sender to re-engage for next steps. Then we can get engineering involved.

**Comment by BerniXiongA6** [comment]
Still haven't heard back from sender yet -- email was sent to John (jgassenheimer@siriusiq.com) on 8.16.2022.

**Comment by BerniXiongA6** [comment]
Updates 9/13/2022: John replied back saying they are already sending to ReportStream? @jbiskie @oslynn — let’s discuss at sprint planning?

**Comment by BerniXiongA6** [comment]
Closing this Epic, looks as though CLX was already onboarded previously.

**Comment by BerniXiongA6** [comment]
@jbiskie @BerniXiongA6 will look into these files in "Staging" tomorrow to determine whether ready to move them to Prod.

**Comment by BerniXiongA6** [comment]
Call with CLX team is being scheduled for Friday w/ @BerniXiongA6 @jbiskie -- hopefully we can clear the confusion as to why they think they're in Prod and we think we have yet to complete onboarding? cc: @sliu1000

**Comment by BerniXiongA6** [comment]
Updates 9/16/2022: @jbiskie is working with CLX to test messages in Prod. After testing is validated, we could potentially go live with CLX early next week! cc: @sliu1000 @sarahnw

**Comment by BerniXiongA6** [comment]
Updates 9/16/2022: Also @BerniXiongA6 will email an updated list of "Where We're Live" info to CLX contacts per their request.
