### ISSUE TITLE
IL, OH - Filter out negative results per 4/4 HHS Guidance

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#5435]
Illinois no longer requires reporting negative rapid test results. Since several SimpleReport senders would like to continue entering negative results so they can provide copies of the results to patients who request them, we need to filter them out much like we do for WA in our settings.  

Including Ohio here, too. They have the same request for at-home test results.

**Comment by anshulkumar-usds** [comment]
@Adrian-Brewster let's keep the tickets in "needs analysis" until there in assignee on the ticket. We can discuss this and other during sprint planning

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5435?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS

**Comment by Adrian-Brewster** [comment]
Jurisdiction quality filter change.

**Comment by sliu1000** [comment]
From: william.storm@odh.ohio.gov <william.storm@odh.ohio.gov> 
Sent: Thursday, June 23, 2022 10:02 AM
To: Report Stream (CDC) <reportstream@cdc.gov>
Cc: Reeves, Maurice (CDC/OD/OCS) <qva8@cdc.gov>; White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>; Kumar, Anshul (CDC/OD/OCS) <rdz8@cdc.gov>; ELR@odh.ohio.gov
Subject: RE: ReportStream: Filtering out negative COVID results

Hello,

If you are able to filter according to the HHS guidance, that would be great.

So, negatives should only be reported for CLIA-certified laboratories performing NAAT testing.  Negative test results can be filtered for all other testing from any lab/entity. 

Thanks,
Bill

From: Report Stream (CDC) <reportstream@cdc.gov> 
Sent: Thursday, June 9, 2022 10:20 AM
To: Storm, William <william.storm@odh.ohio.gov>
Cc: Reeves, Maurice (CDC/OD/OCS) <qva8@cdc.gov>; White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>; Kumar, Anshul (CDC/OD/OCS) <rdz8@cdc.gov>
Subject: ReportStream: Filtering out negative COVID results

Hi Bill,

We have an open ticket to filter out negative COVID results for Ohio based off of the 4/4 HHS guidance that was released.  Is this still your preference? If so, we can have the settings change made today. Please confirm your preference and we will make the change. 

Thanks!
Adrian

**Comment by MauriceReeves-usds** [comment]
I have updated the jurisdictional filters for IL and OH. They are now only receiving positive COVID results.
