### ISSUE TITLE
Valueset editor: UI for index page

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#5441]
## Problem statement

As a team member of O&O team, I want to be able to view, add and update value sets via a user interface so that the change is easy to make and these settings changes don't have to wait on deployment.

## Acceptance criteria

- [ ] User is able to view a list of existing value sets in the layout defined by the wireframe
- [ ] User is able to take action to view the list of values/aliases in one value set 

## What you need to know
- Page/components for main "Value Sets" page:
![Screen Shot 2022-05-10 at 11.04.36 AM.png](https://images.zenhubusercontent.com/5a6b4b784b5806bc2bc46da6/9b52ec4d-8114-4641-8487-9a4d29a93143)

Design file: https://www.figma.com/file/fKl2M96ylkxYezwjVVUSIX/Internal-Admin-%26-Tools?node-id=0%3A1

## To do

- [ ]

**Comment by kevinhaube** [comment]
Table changes needed are ticketed in #5460
Sort changes needed are ticketed in #5461
