### ISSUE TITLE
Need CSP entries added for dap.digitalgov.gov

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#5444]
**Description**
To allow the DAP script (google analytics) to run on production, we need the [dap.digitalgov.gov](http://dap.digitalgov.gov/) to be added to the appropriate CSP headers. Specifically, it needs to be added to the `connect-src` & `script-src` sections of the `content-security-policy` header, and needs to be added to staging and test as well (for consistency). 

Basically, where ever `applicationinsights` is listed.

- [x] Update Production
- [x] Update Staging
- [ ] Update Test
- [ ] Update index.html (client-side change)

**Specific Requested resources**
@cwinters-usds

**Comment by cwinters-usds** [comment]
Production and staging are done, test doesn't have any headers configured right now (which I'll create a ticket for).

**Comment by cwinters-usds** [comment]
Ticket created: https://github.com/CDCgov/prime-reportstream/issues/5449

**Comment by sethdarragile6** [comment]
It's fixed! Thanks heaps, @cwinters-usds !
