### ISSUE TITLE
Properly handle 404s from the history API on submission history page.

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#5445]
**Describe the bug**
If you're logged in as an admin and try to access `/submissions` while switched to an organization that has no senders, you'll get an "An error has occurred" message. This is due to the fact that the history API now returns a 404 if there are no senders. We need to handle that error better on the front end and display a more informative message.

**Impact**
Only happens for admins (other users don't have access to this part of the UI)

**To Reproduce**
1. Log in to staging as an admin
2. Switch to an org that doesn't have senders (`al-phd` for example)
3. Navigate to `https://staging.reportstream.cdc.gov/submissions`

**Expected behavior**
As a user, I'd expect to see a more informative error message (otherwise it seems like something is broken)

**Screenshots**
![Screen Shot 2022-05-10 at 2.45.58 PM.png](https://images.zenhubusercontent.com/5a6b4b784b5806bc2bc46da6/68a11fab-bbe0-464b-aa82-ff0da842bc53)

**Additional context**
Slack conversation [here](https://www.slack.com/archives/C02HJ43AE8Z/p1651683449430729?thread_ts=1651607671.440669&cid=C02HJ43AE8Z)

**Comment by kevinhaube** [comment]
The underlying issue is that Admins can access anything because we measure their role through Okta auth, so when hopping between senders and receivers, they aren't shown _just_ sender or _just_ receiver features. That said, I'd love to improve our app permissions. We could break out app user permissions into a context that's set using the Okta's auth handler. Then, for admins only, handle permissions from the selected org in app, not their okta token. This would help us fully emulate the experience of a user in that organization without having to alter your okta groups.

**Comment by mreifman** [comment]
There are also a few 404s for settings requests but they don't seem to have an impact on the UI. 

```
https://staging.reportstream.cdc.gov/admin/settings
https://staging.prime.cdc.gov/api/settings/organizations/al-phd/senders/default
```
![image.png](https://images.zenhubusercontent.com/626953d64b8b78bf600eb108/271d7bae-f4a4-4a73-ac96-305c25b1f5c0)

**Comment by kevinhaube** [comment]
@mreifman Are you able to post the payloads of those calls, as well? Curious if that'll help diagnose where it's coming from. We have `<SenderModeBanner>` that calls out for the sender (that second call labeled `default`, indicating you might be in a group labeled `DHSender_` in OktaPreview and it's not finding the org settings and sender settings.

**Comment by mreifman** [comment]
The request to `https://staging.reportstream.cdc.gov/admin/settings` doesn't have an `organization` header.

The request to `https://staging.prime.cdc.gov/api/settings/organizations/al-phd/senders/default` has request header for `organization: al-phd`, which matches the selected org.

**Comment by kevinhaube** [comment]
Doh! I guess I could've derived that from the URI. I think I found it, but I'm unable to replicate locally.

[This hook](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/hooks/UseSenderMode.ts) is what's calling it. It's used in `<SenderModeBanner>` to handle the fetch logic. It looks like [my original safety is failing here](https://github.com/CDCgov/prime-reportstream/blob/dcd98ec1f2afc8957ed9d0a71305c709fc15dc6b/frontend-react/src/App.tsx#L99-L101) so it calls regardless.

This is another byproduct of our tricky handling of permissions, as is [this (noted above)](https://github.com/CDCgov/prime-reportstream/issues/5445#issuecomment-1122766733). I think it's worth creating some form of "ProfileContext" that makes this logic cleaner and accessible by providing a user type (sender/receiver), permissions, org, etc.

**Comment by kevinhaube** [comment]
Bumping this up to a 5 due to coverage and the amount of places we're utilizing these permissions conditionals.
