### ISSUE TITLE
[SPIKE] Valueset editor: UI architecture decisions

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#5446]
## Problem statement

We're running into a lot of duplicate JSX in our React project that, with some strategic planning, can be solved by creating reusable components configurable by props. In this ticket, we will be breaking down #5441 #5442 and #5443 into chunks of work with reuse of code as a high priority.

## To-do

- [x] Assess what available components and hooks we have that suit our needs, and any changes that might need to be made
- [x] Organize these efforts into sensible chunks

## Acceptance criteria

- Present the breakdown of work to engineering team

**Comment by kevinhaube** [comment]
## Component breakdown

It helps me to go one-by-one through the pages as we've spec'd them and derive chunks of work that way, so these notes below serve as that process, visualized.

#### 5441

1. `Title` for page title
2. Optional title/header for `Table` component
3. `SortSettings` refactor to work as both a local array sort (applicable to this work) OR a db query sort like ASC/DESC
4. Action column configuration for `Table`
5. Table dataset action button configuration for `Table`

#### 5442

- Shares 1-2 and 4-5 in common with 5441
1. `Table` legend under title/header, above table; should take a component not configuration props
2. `Crumbs` to take user back to Value Sets index

#### 5443

- Trussworks component should work fine here

## Units of work

Now that I've sorted through the pages and work related to them, I see main chunks of work that should help us achieve these results efficiently by allowing synchronous work between engineers. 

### Table

Current table props
```typescript
export interface ColumnConfig {
    dataAttr: string;
    columnHeader: string;
    sortable?: boolean;
    link?: boolean;
    linkBasePath?: string;
    linkAttr?: string; // if no linkAttr is given, defaults to dataAttr
    valueMap?: Map<string | number, any>;
    transform?: Function;
}

export interface TableConfig {
    columns: Array<ColumnConfig>;
    rows: Array<TableRow>;
}

export interface TableProps {
    config: TableConfig;
    filterManager?: FilterManager;
    cursorManager?: CursorManager;
}
```

These props could be extended to include a table title, column config options
for button/button group columns (action columns), and a dataset action like
"Add Item" that displays as a button in the Table header area.

Styling should be consistent across the site, so we should use the alternating
row color and vertical row space found in the mockups. This should reflect on the
`SubissionsTable` component when on `/submissions` in the browser automatically, but
`/daily-data` needs to be fitted with the `Table` component. 

### SortSettings

Current interface
```typescript
type SortOrder = "ASC" | "DESC";
interface SortSettings {
    column: string;
    order: SortOrder;
}
```

This will need to be extended in a way that it can account for local OR server-side
sorting. This is specifically designed, now, for passing ASC or DESC as a param in
API calls for sorting on the created_at column. It will still need to be
able to do that.

This isn't explicitly "dependent" upon the `Table` work, but is a large enough task that
it should be handled separately.

### Page creation

Dependent upon `Table` and `SortSettings` work, this should be the last chunk of work done.
The page will utilize the new features from prior work to create the user interfaces and experience
outlined in the designers' mockups.
