### ISSUE TITLE
Information architecture for Programmer's Guide static page

### ISSUE THREAD

**Issue by mreifman** [CDCgov/prime-reportstream#5448]
In order to migrate the Programmer's Guide to a markdown-driven HTML page we need to know what URLs they should live at and what page structure should be around the content. Should the page be in the [testing facilities getting started section](https://reportstream.cdc.gov/getting-started/testing-facilities/overview), linked as an item in the side nav? 

Related to [5092](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5092)

AC - still needed

**Comment by HeatherRienks** [comment]
Closing this ticket - will use #5092 for all related work.
