### ISSUE TITLE
Santa Clara - Download Site Access

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#5465]
Name of public health department: Santa Clara County Public Health
Jurisdiction type: County
Name of jurisdiction: Santa Clara County, CA
Name(s) and email(s) of people who need database access: Elaine Li (Elaine.li@PHD.SCCGOV.ORG)

Elaine is no longer able to access the download site.  She had access previously.  We have already reset and that did not work.  Elaine has attempted to log in using different browsers. 

@anshulkumar-usds FYSA since you have previously worked on this.

**Comment by anshulkumar-usds** [comment]
5/12: Checking with Elaine to get more clarity on next steps

**Comment by anshulkumar-usds** [comment]
Solved by https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5509

**Comment by anshulkumar-usds** [comment]
5/20: Notified user of the fix, and awaiting confirmation.

**Comment by anshulkumar-usds** [comment]
User confirmed they have access now
