### ISSUE TITLE
Sorting submissions by date returns no results

### ISSUE THREAD

**Issue by mreifman** [CDCgov/prime-reportstream#5474]
**Describe the bug**
The Submissions page loads a list of submissions initially sorted by descending date. Clicking the arrow icon next to the "Date/time submitted" column header to change the sort order to ascending removes all results from the table. Clicking the sort arrow again to change the order back to descending does not return to the initial state -- the results table is still empty.

**Impact**
Submissions cannot be sorted by ascending date, and attempting to do so ultimately requires reloading the page to see the results sorted by descending date.

**To Reproduce**
1. Go to the submissions page for the `ignore` org: https://staging.reportstream.cdc.gov/submissions
2. Click on the down arrow next to the "Date/time submitted" column header.
3. The loading spinner appears, and when it goes away, the results table is empty.
4. Click on the up arrow next to the "Date/time submitted" column header.
5. The loading spinner appears, and when it goes away, the results table is empty.

**Expected behavior**
Submissions should be sortable by ascending date.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/626953d64b8b78bf600eb108/449fd289-37c0-49c0-a4cd-cd62823d3e68)

**Additional context**
The start and end values are getting mixed up when we try to sort. The initial fetch has these query parameters: 
```
cursor=3000-01-01T00:00:00.000Z&endcursor=2000-01-01T00:00:00.000Z&sort=DESC
```

But when we change the sort order the request has a new end value but not a new start value: 
```
cursor=3000-01-01T00:00:00.000Z&endcursor=3000-01-01T00:00:00.000Z&sort=ASC
```

Changing the sort order back to descending again has the correct end value but the incorrect start value:
```
cursor=2000-01-01T00:00:00.000Z&endcursor=2000-01-01T00:00:00.000Z&sort=DESC
```

**Comment by kevinhaube** [comment]
Ah, shoot, looks like it's something to do with the cursor dance when swapping sort order. It's tricky.![Screen Shot 2022-05-12 at 5.06.10 PM.png](https://images.zenhubusercontent.com/611a907ec3e013d0e33e58a7/bd41d52f-d2ef-4bed-ab74-eca7cec3b656)

**Comment by kevinhaube** [comment]
Ah, shoot, looks like it's something to do with the cursor dance when swapping sort order. It's tricky.![Screen Shot 2022-05-12 at 5.06.10 PM.png](https://images.zenhubusercontent.com/611a907ec3e013d0e33e58a7/bd41d52f-d2ef-4bed-ab74-eca7cec3b656)
