### ISSUE TITLE
Search feature for ReportStream website

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#5476]
## Problem statement

As a end user, I want to be able to search for a word or a phrase and easily find the content I need so that I don't spend time looking through all the menus to find what I need. (i.e. Programmer's Guide).

## What you need to know
- cdc.gov
- nih.gov

## Acceptance criteria
- Search feature allows for partial, complete, case in-sensitive search for the input entered.
- User is able to navigate back from the search results. 

## To do

- [ ] ...

**Comment by RakshindaAslam** [comment]
@bgantick @drew-usds

**Comment by HeatherRienks** [comment]
Per 5/18/22 refinement mtg, this is a complex Eng effort. Requires more discussion and a separate ticket.

Next step for Design: Investigate search.usa.gov and integration options. Where will the search box live?

**Comment by a-chappelear** [comment]
this ticket is also [https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5515](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5515)  (think this is a duplicate?)

**Comment by RakshindaAslam** [comment]
I believe this one is a duplicate but it has some comments from Brian so I did not want to close it. @bgantick - can we close this now or leave it till the eng ticket is completed? cc @a-chappelear

**Comment by kevinhaube** [comment]
Hey @RakshindaAslam this should be okay to close -- I'm picking up the eng ticket now

**Comment by RakshindaAslam** [comment]
Thanks @kevinhaube !
