### ISSUE TITLE
MD - Discontinue Secondary Feed

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#5494]
Original Request: Maryland has requested that we make the data available to them in csv instead of hl7 on the download site - for both primary and secondary feeds.

New Request: When I explained that we are unable to change the format of their secondary feed without also changing the format of their primary feed, they requested that we discontinue their secondary feed as the OTC data they are seeing lacks the necessary information they require.

**Comment by brick-green-agile6** [comment]
We cannot change the format solely for the download site. If we change the format for a feed it will reflect i the download and sftp. The best option I see if they need CSV and HL7 is to create two new feeds for CSV that mimic the data in the primary and secondary feeds. All four feeds would be available via the daily data page (download site) but only the two HL7 would go through sftp. What do we think? cc @Adrian-Brewster

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5494?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS

**Comment by Adrian-Brewster** [comment]
Adrian to look for MD response. And send follow up

**Comment by MauriceReeves-usds** [comment]
@sarahnw @Adrian-Brewster when we talk to MD, we also need to determine if we need to follow a specific schema or can provide one of our own.

**Comment by brick-green** [comment]
@Adrian-Brewster Was there any discussion with MD?
