### ISSUE TITLE
Messages with Missing LOINC Code - Resends Needed

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#5498]
WA Reporting several messages with missing LOINCs today. These need to be corrected and resent. 

```
2daa8c5a-30dd-4eb8-b12d-321f08a39c85
5ef47792-5d78-4608-945a-1609455db47a
262cc578-07ff-447e-99cc-81be03b3acab
c54ff4d4-fae1-44a2-a810-baf7f93d7c49
f74e292a-eac7-4118-92cb-15630e8c6464
53308112-eacf-4444-a4d2-310bd2812449
9ef618b0-c2b0-4a83-9c1d-6c8e4c1e3648
833caf3f-d4df-4f1d-a538-45519b84ecd5
2041b7b2-6862-498f-80ab-ba474b8b4acb
18750172-5dce-4151-950a-d05a21031775
ebfab1b1-ba5d-44b7-aef3-bfb4b6b536e6```

**Comment by anshulkumar-usds** [comment]
@oslynn WA reported three additional messages with missing LOINCs:

``
2daa8c5a-30dd-4eb8-b12d-321f08a39c85
88a1b30c-82f1-4d00-8d0b-44dd7897568
f3fe6f8b-7117-4910-a1f4-f80cd51f7179
``

**Comment by oslynn** [comment]
Emailed to Caroline.Thomas the corrected LOINC Code Zip file 2022-05-18 at 4:30pm.

**Comment by anshulkumar-usds** [comment]
@oslynn WA wrote to us today, 5/19, that they're seeing more messages with missing LOINCs:
```
edf6e4f0-3009-42c1-9140-110c34
37c7e7e5-8742-4023-b03e-792e0a
e91d2e19-5eaa-4178-8649-4c117c
5560244a-b411-4ecc-aabb-d48176
d93e5dc6-3273-4ecd-9b96-6c512d
f6d068b9-69a5-45d8-afaa-5e03d2a3cd6d
04734b26-adfc-4655-85f0-78fed83f6f04
93744359-0443-467c-8774-6878c75a6c49
9281a5b4-088a-4329-acd1-5edc517ec6ab
dba69f2b-2e55-4c28-bcf7-4b6ce019472d
7c7ea552-3875-4a0f-aaa5-1f14c4634b9f
```

**Comment by Adrian-Brewster** [comment]
```b4bf5bb4-553b-496d-b29a-e766aa66df36
6dac78da-f37e-4f4f-a1fc-52c715e5ac52

Two additional resends @oslynn

**Comment by oslynn** [comment]
Email from WA:
Thanks Anshul,

 

We found two more today.  I’ve added them to the bottom of the list I’ve compiled below:

 

Accessions requested

2daa8c5a-30dd-4eb8-b12d-321f08a39c85

5ef47792-5d78-4608-945a-1609455db47a

262cc578-07ff-447e-99cc-81be03b3acab

c54ff4d4-fae1-44a2-a810-baf7f93d7c49

f74e292a-eac7-4118-92cb-15630e8c6464

53308112-eacf-4444-a4d2-310bd2812449

9ef618b0-c2b0-4a83-9c1d-6c8e4c1e3648

833caf3f-d4df-4f1d-a538-45519b84ecd5

2041b7b2-6862-498f-80ab-ba474b8b4acb

18750172-5dce-4151-950a-d05a21031775

ebfab1b1-ba5d-44b7-aef3-bfb4b6b536e6

88a1b30c-82f1-4d00-8d0b-44dd7897568

f3fe6f8b-7117-4910-a1f4-f80cd51f7179

edf6e4f0-3009-42c1-9140-110c34

37c7e7e5-8742-4023-b03e-792e0a

e91d2e19-5eaa-4178-8649-4c117c

5560244a-b411-4ecc-aabb-d48176

d93e5dc6-3273-4ecd-9b96-6c512d

f6d068b9-69a5-45d8-afaa-5e03d2a3cd6d

04734b26-adfc-4655-85f0-78fed83f6f04

93744359-0443-467c-8774-6878c75a6c49

9281a5b4-088a-4329-acd1-5edc517ec6ab

dba69f2b-2e55-4c28-bcf7-4b6ce019472d

7c7ea552-3875-4a0f-aaa5-1f14c4634b9f

b4bf5bb4-553b-496d-b29a-e766aa66df36

6dac78da-f37e-4f4f-a1fc-52c715e5ac52

**Comment by sliu1000** [comment]
Email from WA - Caroline Thomas (Caroline.Thomas@doh.wa.gov)

In our meeting yesterday, we discussed the results with missing LOINCs. I mentioned that we had mostly been seeing this issue in old results from January that have been processing more recently, however, yesterday afternoon we found brand new results with the same issue so there is still an underlying issue that needs addressing. Below is an example of the OBX segment missing a LOINC.

OBX|1|CWE|^^LN||82334004^Indeterminate^SCT|||N^Normal (applies to non-numeric results)^HL70078^^^^2.7|||F|||20220523171200-0000|KIRK'S PHARMACY^KIRK'S PHARMACY^CLIA||BD Veritor System for Rapid Detection of SARS-CoV-2^^^^^^^^BD Veritor System for Rapid Detection of SARS-CoV-2||20220523171200-0000||||KIRK'S PHARMACY^^^^^CLIA&2.16.840.1.113883.4.7&ISO^XX^^^KIRK'S PHARMACY|104 MASHELL AVE^^EATONVILLE^WA^98328

Here is the list of accessions sent on 5/23/22 that have the issue: 

58de7ecb-bc6c-4eb8-927e-7f6d7ab879b3
2839e154-6680-420f-98a5-570d08a8204b
11e96988-f9db-4e4e-83d0-d6e2cac8e8f4
e4f70bd4-350b-4b77-a142-165119033b73
08ea3dc2-2139-4f1a-9344-ea8a872e40ad
c8fc2e19-c46f-4e67-bf4e-f0011c087514
55d84e04-f718-47bc-81c2-25036ececf6e
3c93731d-35c6-45f7-825a-d8bc5ef3eb46
c8918131-f856-464f-bd95-37892644a146
4b187910-3504-4b9a-a72d-81a7f1cee0b8
9907c59f-4938-4f76-a1c3-803890b11891
4a834bde-428f-47df-94eb-f657a17ad980
35f84656-cc3d-4536-98d4-65e9fecd8551

We can push these through our system manually for now (so no resubmissions needed), but please investigate and address the root cause of why these messages are being sent without appropriate LOINC codes.

**Comment by oslynn** [comment]
I have ask @jbiskie for help investigate the above issue and inform @sarahnw about why the issue popping backup again.

**Comment by oslynn** [comment]
Files with message ids below are no longer there!!
    b4bf5bb-553b-496d-b29a-e766aa66df36
    6dac78d-f37e-4f4f-a1fc-52c715e5ac52

**Comment by oslynn** [comment]
According to @jbiskie messages with message ids below sent wrong LOINC codes.  
"They're sending 97099-6, which is the test ordered LOINC code. They need to send the test performed LOINC code, 97097-0 in OBX-3.
"
58de7ec-bc6c-4eb8-927e-7f6d7ab879b3
2839e15-6680-420f-98a5-570d08a8204b
11e9698-f9db-4e4e-83d0-d6e2cac8e8f4
e4f70bd-350b-4b77-a142-165119033b73
08ea3dc-2139-4f1a-9344-ea8a872e40ad
c8fc2e1-c46f-4e67-bf4e-f0011c087514
55d84e0-f718-47bc-81c2-25036ececf6e
3c93731-35c6-45f7-825a-d8bc5ef3eb46
c891813-f856-464f-bd95-37892644a146
4b18791-3504-4b9a-a72d-81a7f1cee0b8
9907c59-4938-4f76-a1c3-803890b11891
4a834bd-428f-47df-94eb-f657a17ad980
35f8465-cc3d-4536-98d4-65e9fecd8551

**Comment by jbiskie** [comment]
Emailed Prescryptive regarding the batch that @sliu1000 referenced.

**Comment by oslynn** [comment]
The following message Ids don't have any file associate with them:
=================================================================================
Files for the following message ids are no longer exist.
=================================================================================

     2daa8c5a-30dd-4eb8-b12d-321f08a39c85
     edf6e4f0-3009-42c1-9140-110c34
     37c7e7e5-8742-4023-b03e-792e0a
     e91d2e19-5eaa-4178-8649-4c117c
     5560244a-b411-4ecc-aabb-d48176
     d93e5dc6-3273-4ecd-9b96-6c512d
     b4bf5bb-553b-496d-b29a-e766aa66df36
     6dac78d-f37e-4f4f-a1fc-52c715e5ac52

**Comment by oslynn** [comment]
The following message ids has (precryptive.default) HL7 files associate with them:
Create file for Message ID:
     f6d068b9-69a5-45d8-afaa-5e03d2a3cd6d
Writing: ./junk/ticket5498/20220527/csv/receive/prescryptive.default/2022052714303474_prescryptive-covid-19-0636c4fc-371a-4c54-a418-5ceb06cdadf5-20220518170242.hl7

Create file for Message ID:
     04734b26-adfc-4655-85f0-78fed83f6f04
Writing: ./junk/ticket5498/20220527/csv/receive/prescryptive.default/2022052714303823_prescryptive-covid-19-5fc5b11d-b139-4d76-a4b1-bc841048ec61-20220518170302.hl7

Create file for Message ID:
     93744359-0443-467c-8774-6878c75a6c49
Writing: ./junk/ticket5498/20220527/csv/receive/prescryptive.default/2022052714304130_prescryptive-covid-19-9ed14e07-44e0-4ab1-9b53-2f8992cd4278-20220518162413.hl7

Create file for Message ID:
     9281a5b4-088a-4329-acd1-5edc517ec6ab
Writing: ./junk/ticket5498/20220527/csv/receive/prescryptive.default/2022052714304437_prescryptive-covid-19-7e6c16b3-2f78-4d34-a0c3-331458167caf-20220518161451.hl7

Create file for Message ID:
     dba69f2b-2e55-4c28-bcf7-4b6ce019472d
Writing: ./junk/ticket5498/20220527/csv/receive/prescryptive.default/2022052714304744_prescryptive-covid-19-6f28bc03-f9ca-431d-99b6-ab0c729f7e15-20220518175249.hl7

Create file for Message ID:
     7c7ea552-3875-4a0f-aaa5-1f14c4634b9f
Writing: ./junk/ticket5498/20220527/csv/receive/prescryptive.default/2022052714305121_prescryptive-covid-19-bfdf51f0-31c4-4366-8632-74f22785664a-20220518214753.hl7

Create file for Message ID:
     b4bf5bb4-553b-496d-b29a-e766aa66df36
Writing: ./junk/ticket5498/20220527/csv/receive/prescryptive.default/2022052714305407_prescryptive-covid-19-d1547b87-e265-4640-90bf-aa06bae251de-20220519162304.hl7


Create file for Message ID:
     6dac78da-f37e-4f4f-a1fc-52c715e5ac52
Writing: ./junk/ticket5498/20220527/csv/receive/prescryptive.default/2022052714305710_prescryptive-covid-19-f4f1c793-b8cb-49dc-9d01-c7c4b2c311af-20220519165953.hl7

**Comment by oslynn** [comment]
Email Hl7WIthLOINCCodeFixed.zip that contains HL7 files with fixed LOINC Code fixed.

**Comment by jbiskie** [comment]
> According to @jbiskie messages with message ids below sent wrong LOINC codes. "They're sending 97099-6, which is the test ordered LOINC code. They need to send the test performed LOINC code, 97097-0 in OBX-3. " 58de7ec-bc6c-4eb8-927e-7f6d7ab879b3 2839e15-6680-420f-98a5-570d08a8204b 11e9698-f9db-4e4e-83d0-d6e2cac8e8f4 e4f70bd-350b-4b77-a142-165119033b73 08ea3dc-2139-4f1a-9344-ea8a872e40ad c8fc2e1-c46f-4e67-bf4e-f0011c087514 55d84e0-f718-47bc-81c2-25036ececf6e 3c93731-35c6-45f7-825a-d8bc5ef3eb46 c891813-f856-464f-bd95-37892644a146 4b18791-3504-4b9a-a72d-81a7f1cee0b8 9907c59-4938-4f76-a1c3-803890b11891 4a834bd-428f-47df-94eb-f657a17ad980 35f8465-cc3d-4536-98d4-65e9fecd8551

Prescryptive has corrected the issue for these messages.
