### ISSUE TITLE
HHS-Protect team requests a <deidentified> value for non-empty PII fields

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#5500]
**Is your feature request related to a problem? Please describe.**
The HHS Protect team (Kim Del Guercio) is trying to prepare the results sent to HHS Protect data for release as a public data set in data.cdc.gov. They would like to measure the completeness of reporting on patient information, even though this information is withdrawn from the results sent to HHS Protect. 

**Describe the solution you'd like**
> Hi Rick,

>  
> I connected with Jason and if possible, it would be great to have a completeness indicator for all of the demographic fields - first name, last name, home address 1, home address 2, email, phone number, and city. Jason mentioned that APHL did this for iHealth and inserted <DEIDENTIFIED> in the field if there is information available.
>  
> Kim 
>  
> Kim Del Guercio, MPH

So a new deidentify algorithm. Instead of always blanking out a field, write <DEIDENTIFIED> if the field is not empty, and blank if the field is empty.  

I would expect to a new set of deidentify settings that replace the existing true | false setting. 

**Describe alternatives you've considered**

**Additional context**
This is part

**Comment by MauriceReeves-usds** [comment]
We have an existing ticket for this work: #5410

**Comment by RickHawesUSDS** [comment]
Closing as duplicate of #5410
