### ISSUE TITLE
Design - Validation Service UI

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#5504]
## Problem statement

As a sender or an O&O team member, I want to be able to test my data file in CSV, HL7 or RADx-MARS format and get user friendly responses to understand, identify and fix issues with my data.

## What you need to know
- [Existing Figma mockup for CSV upload](https://www.figma.com/file/b2Zd1xzmp4cdwFO8O7edcI/CSV-Uploader?node-id=0%3A1)
-  [Mural board for Validation Service Deep Dive with Options ](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1651702156098/60d77d324b3bf252c83d30f73f2cc201a59cc1eb?sender=u3fea607b46e84058d3224917)
 - Provide user-interface that allows file drag&drop or upload feature and display of response to the file
 - There is an expectation of reusing CSV Uploader components and features and not a full new page
 - Supporting HL7, CSV, RADx MARS formats
-Example: https://validator.aimsplatform.org/

## Acceptance criteria

- [ ] IA for the Validation Service Page
- [x] Design/wireframe for the Validation Service Page
- [x] Reviewed with the Product and Experience team

## To do

- [ ] Review example HL7 and RADx MARS files, how do they differ from our existing CSV format?
- [ ] ...

**Comment by a-chappelear** [comment]
Work in progress for this is located at: https://www.figma.com/file/b2Zd1xzmp4cdwFO8O7edcI/CSV-Uploader-%26-Validation?node-id=2288%3A1127

**Comment by a-chappelear** [comment]
Updates - UI can be used as in the Figma file for MVP; but as we learn more about different “types” of messaging and errors that could get thrown from HL7, we might want to circle back around and see if adjustments need to be made to how they are displayed or communicated back.
