### ISSUE TITLE
Build - Validation Service UI Prototype

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#5506]
## Problem statement

As a sender or an O&O team member, I want to be test my data file in CSV or HL7 format and get user friendly responses to understand, identify and fix issues with my data.

## What you need to know
-  [Mural board for Validation Service Deep Dive with Options ](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1651702156098/60d77d324b3bf252c83d30f73f2cc201a59cc1eb?sender=u3fea607b46e84058d3224917)
 - Provide user-interface that allows file drag&drop or upload feature and display of response to the file
 - There is an expectation of reusing CSV Uploader components and features and not a full new page
 - Supporting HL7 and CSV formats for MVP
 - Spike: #5505
- Warning messages need to be added back in to the UI

## Acceptance criteria

- [ ] User is able to upload a file in HL7 or CSV format
- [ ] User is able to view success, warning, and/or error msgs based on the current validation methods
- [ ] Should be behind a feature toggle with safeguards to prevent accidental submissions in prod
- [ ] Update UI based on attached Figma file https://www.figma.com/file/b2Zd1xzmp4cdwFO8O7edcI/CSV-Uploader-%26-Validation?node-id=2288%3A1127

## To do

- [ ] UI tweaks
  - [ ] Buttons
  - [ ] Text, banner colors, etc
- [ ] Reformat errors
- [ ] re-expose warnings
- [ ] sender/receiver selector
- [ ] refactor (reducer usage, shared components, fetching/API interface)
- [ ] Success state/file metadata (on success - TBD)

**Comment by HeatherRienks** [comment]
Per 5/18/22 Refinement meeting, let's wait for #5504 to be finished before starting on this.

**Comment by bgantick** [comment]
Pending #5504 and #5505

**Comment by bgantick** [comment]
This should be ready for pre-refinement based on what we went over in discussion of #5505

**Comment by bgantick** [comment]
This work is a prototype, there may need to be adjustments to the designs based on engineering work needed (adding selected receiver to the UI for example)

**Comment by bgantick** [comment]
See comments/TODOs from https://github.com/CDCgov/prime-reportstream/pull/5932

**Comment by bgantick** [comment]
Bumping up to an 8 to accommodate additional refactor work.
