### ISSUE TITLE
Daily data page errors for receivers with more than one underscore in their Okta group name

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#5509]
## Description:
First reported by a user in the `DHca_scc_phd` group. The error occurs with any group that has more than one underscore in their group name. When trying to load an authenticated page, the GET call to org settings fails (404): `Request URL: https://prime.cdc.gov/api/settings/organizations/ca-scc_phd`. The URL should be `https://prime.cdc.gov/api/settings/organizations/ca-scc-phd`. The org is getting mangled when saving to `global-context-org` in session storage.

**Comment by kevinhaube** [comment]
Set to deploy May 19th 2022
