### ISSUE TITLE
Swap USWDS CDN for USWDS-Gulp

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#551]
Currently 11ty is pulling in UWDS via CDN. Swap it to build with [uswds-gulp](https://github.com/uswds/uswds-gulp).

uswds-gulp allows us to:

- Customize what parts of UWDS we want to include in the app
- Use custom variables/etc with USWDS components
- Use USWDS variables/tokens/etc with custom styles

**Comment by jlusds** [comment]
What's the status for this?
