### ISSUE TITLE
San Juan Basin unable to access Download Site

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#5516]
**Describe the bug**
San Juan Basin is unable to access the download site. 

From Sender "Hello, When I log into this link (https://reportstream.cdc.gov/ ), and click on “daily data” I keep getting this error message"

**Additional context**
![image.png](https://images.zenhubusercontent.com/60d1eba7caf0775fd79203f8/0e0d2e6a-2525-4272-805b-5dd83c3b89d9)

**Comment by anshulkumar-usds** [comment]
Solved by https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5509

**Comment by anshulkumar-usds** [comment]
5/20: Notified STLT of the fix and asked for their review.

**Comment by anshulkumar-usds** [comment]
User confirmed they have access now.
