### ISSUE TITLE
Investigate viz libraries for insights

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#552]
Look into libraries for displaying charts/graphs/etc for displaying insights data.

- D3
- Airbnb Visx

**Comment by drew-usds** [comment]
Currently using chart.js - https://www.chartjs.org/

**Comment by MauriceReeves-usds** [comment]
I think we should investigate moving to visx - airbnb.io/visx

**Comment by celestemespinoza** [comment]
Requires a formal recommendation as an output
