### ISSUE TITLE
Implement search for ReportStream static content

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#5523]
## Problem statement
As an end user, I want to be able to search for a word or a phrase and easily find the content I need so that I don't spend time looking through all the menus to find what I need. (i.e. Programmer's Guide).

## What you need to know
- SimpleReport has [search](https://search.usa.gov/search?utf8=%E2%9C%93&affiliate=simplereport&query=test&commit=) (powered by search.gov) on their [user guide](https://www.simplereport.gov/user-guide/)/[using SimpleReport](https://www.simplereport.gov/using-simplereport/) pages.
- It looks like indexing on search.gov is relatively straight-forward: https://search.gov/admin-center/dashboard/add-site.html
- search.gov provides search form snippets: https://search.gov/admin-center/activate/code.html
- we might want to improve SEO/meta info before indexing ([can preview in search.gov dashboard before activating](https://search.gov/admin-center/preview.html))

## Assumptions
- We'll use search.gov to index the site and provide search results

## To do
- [ ] Sign up and activate search.gov account (adding relevant users)

## Acceptance criteria
- [ ] Search feature allows for partial, complete, case in-sensitive search for the input entered.
- [ ] User is able to navigate back from the search results (or search results open in a new tab).

**Comment by drew-usds** [comment]
@bgantick @a-chappelear from sprint planning 8/16:

Would be helpful to know if y'all uncover any other info about how we can use search.gov as you work through this issue.

Like ... anything we can do to incrementally improve it? Are there options beyond the basic implementation that add extra utility? Are there other options for hosting, like on our own domain (though it'd maybe have to be a sub.sub.domain.gov, which might not be great)? Are there things we need to do to update it as we add pages/301 links/anything like that?

**Comment by kevinhaube** [comment]
First attempt: Ran into an issue where our site is not indexed due to our SPA architecture. Proposed ways forward:
- SSR our public pages
- Try a sitemap generator compatible with React Router Dom (may not like our generative routes, packages are currently abandoned)
- Hand-write a sitemap for basic indexing while we figure it out

**Comment by kevinhaube** [comment]
@chris-kuryak @CnoteNava @HeatherRienks The outcome of #6421 indicates **static site generation** is a well-rounded, future-proof approach to providing indexable search results for public site content and documentation. Currently we do have a static public site, and thus cannot be indexed by search engines beyond our index page.

**Comment by chris-kuryak** [comment]
A decision needs to be made around the architectural design of the site, and should be discussed at the higher level with engineering and product and site architecture.

**Comment by chris-kuryak** [comment]
A search feature and improving SEO will be addressed at a later date. Closing for now.
