### ISSUE TITLE
Improve code coverage for HL7Reader class

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#5526]
Add unit tests to increase code coverage of the HL7Reader class.  Aim for a minimum of 80%, but cover as much as the code a possible for proper testing.

### Description/Use Case
Add unit tests to increase code coverage of the class.

### Dev Notes:
* Aim for a minimum of 80%, but cover as much as the code a possible for proper testing.

### Acceptance Criteria
* Code coverage is above 80% for the class.  Deviations should be documented with a reason as to why.
* All functions and inputs are tested.  Deviations should be documented with a reason as to why.

**Comment by jh765** [comment]
Actually, the  code was covered at 100%, with a couple of lines that were not pure green.  I studied the yellow coverage and tried to break out the compound statements.  I tried to understand what part of the MSH string MSH-7 was, and by hovering over the "MSH" in the code (not the quoted version) saw a drop-down list of MSH parts.  I hovered over the MSH name at the top of that list and click to open the document MSH.java, which was a HAPI document.

MSH.java included enough commentary to understand the HL7 encoding process, minus the meaning of 'MSH', 'OBX', etc...

I talked with Carlos And he agreed that the coverage was sufficient and that I should write up what I uncovered and close the ticket, without the need for a PR.
