### ISSUE TITLE
TN - Missing OBR-4 and OBX-3.2

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#5538]
**Describe the bug**
TN has received three messages so far this week with missing OBR-4. Can these be fixed and resent? 

```12c6126e-efbe-4f12-809d-f5d7c4ce4428
40edd576-ed1e-4b5f-a61e-9abca1b218c2
1b4a584b-2a59-489a-848e-8c275a9c388b
562fab60-93d9-4b2a-aabb-66d72c356fab```

These messages are also showing up with missing OBX-3.2 i.e. we are only getting ' 94500-6^^LN' in the first observation result.

**Comment by brick-green** [comment]
Simple report currently sends two fields to identify a test type:
```
  - name: test_performed_code
    csvFields: [{name: Ordered_test_code}]

  # The type of device used for the test.  eg, BinaxNOW COVID-19 Ag Card
  - name: equipment_model_name
    csvFields: [{name: Device_ID}]
```

Until recently that combination of fields was sufficient to identify a unique row in the LIVD table. But that's not true any longer. You can see in the [LIVD](https://app.zenhub.com/files/304423150/bb34917f-1144-4216-8d30-b30068dfc377/download) table that rows 25 and 26 are identical for columns B and F which map to  equipment_model_name and test_performed_code. When the LIVD mapper finds multiple results for the lookup it will default to blank which is what's happening here. The solution is to request additional fields from simple report (and other senders) so that the test type can be uniquely identified.

**Comment by brick-green** [comment]
In the short term, I can manually add the information for these three results and resend to TN

**Comment by brick-green** [comment]
I just resent these files. I'll make a new ticket for the work with simple report. But note that this can/will happen again until we work with the senders.

**Comment by brick-green** [comment]
@Adrian-Brewster Please let TN know I resent them

**Comment by sliu1000** [comment]
@brick-green User Angie from CEDS Informatics email (ceds.informatics@tn.gov).  

Is asking if there are any updates on resending the below?  And that they received another message that would need to be resent for the same issue:

6/6/2022 (Another One)
8c673ee1-645e-4e2c-ba48-90744a23a97e

**Comment by brick-green** [comment]
@sliu1000 I resent the first three earlier today. I can work to resend the new one. Can you add the message id again in a new comment? It looks like the first character was not included. For some reason zenhub does not like the message id formats. You have to treat it like code for it to come through properly. If you highlight it then click the "Insert Code" button it should work.

**Comment by sliu1000** [comment]
`8c673ee1-645e-4e2c-ba48-90744a23a97e`
@brick-green Hopefully this looks better. Please let me know if I should contact the user and ask them to resend the message id.

**Comment by brick-green** [comment]
@sliu1000 That worked, thanks! I just transferred that message as well to TN. Can you let them know that all four of these have been fixed and resent? 
Also, we are working on a solution currently though. So this problem may reoccur a couple more times before we get the fix in place.

**Comment by sliu1000** [comment]
@brick-green 

From: CEDS Informatics <CEDS.Informatics@tn.gov>
Sent: Monday, June 13, 2022 3:18 PM
To: Report Stream (CDC) <reportstream@cdc.gov>
Subject: Re: Missing OBR-4 and OBX-3.2
 
Hello,

The all but `12c6126e-efbe-4f12-809d-f5d7c4ce4428` were resent to us. Can this be reviewed? 

Thanks,

CEDS Informatics

**Comment by brick-green** [comment]
@sliu1000 Just fixed and transferred that message too

**Comment by brick-green** [comment]
@sliu1000 Oops, my mistake. Just transferred the correct file.
