### ISSUE TITLE
RESEARCH Validation service API/Backend 

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#5548]
## Problem statement
While we're [prototyping a validation page](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5506), we should start exploring and building out a new backend workflow for handling validation outside of our normal pipeline. There are a couple of approaches here..

Option 1: Continue the path we were taking with CSV Uploader and refactor to not store data if a certain flag is passed.

Option 2: Continue the path of the preview feature/Create a new endpoint, untangle pipeline logic.

**Option 2** seems like the best fit for what we're trying to do. There are two requirements for this work:

- Don't store any data that is submitted
- Keep a record of errors for reference/troubleshooting

## What you need to know
- Previous [SPIKE](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5505)
- Previous [work on "preview" functionality](https://github.com/CDCgov/prime-reportstream/pull/4564)
- [Issue](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5058) created by Pipeline team

## Acceptance criteria
- Define a path to get the Validation Service to analyze a file, without sending data to a STLT.
- Update [Engineering](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5713) ticket and/or new tickets and create Design ticket (if necessary).

**Comment by sethdarragile6** [comment]
added some code analysis to #5713
