### ISSUE TITLE
NJ - ELR File Issues

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5560]
**Describe the bug**
We are seeing many ORC-23 missing.

We are also getting many errors for OBX-17.1 (Observation Method.Identifier) exceeding maximum length:

BD Veritor System for Rapid Detection of SARS-CoV-2 \T\ Flu A+B_Becton, Dickinson and Company (BD)_EUA

Maybe the escape characters put it over the limit, but will leaving out the (BD) do any harm?

Please correct the phone numbers and resubmit.

**Expected behavior**
No errors when submitting

**Screenshots**
See attached Emails

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Adrian-Brewster** [comment]
Need to have comprehensive list of resubmissions required by New Jersey. How many messages have failed due to ORC-23 issues? @sliu1000
