### ISSUE TITLE
NJ - Error in Rhapsody Route in PRODUCTION

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5563]
**Describe the bug**
Please note the errors below with your ELR File: covid-19-3c487e78-13d2-4f0e-bcbd-938863ac6a09-20220523134035.hl7,,,,

ORC-23 is missing.  Please correct and resubmit.

**Expected behavior**

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Adrian-Brewster** [comment]
Duplicate. Merging both tickets.
