### ISSUE TITLE
Messages From ReportStream to VT Failing

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5565]
User Theresa Dunn from Theresa.Dunn@Vermont.gov

Is there any chance a change to the SimpleReport/ReportStream code was introduced last week? I was out of the office so apologize for the delayed notification of the errors, but **hundreds** of SimpleReport messages to Vermont have failed due to the following issues:

**MSH-7** (Date/Time of Message): Field not properly formatted as date/time; we are currently receiving date only. Please ensure this field is properly formatted as date/time. This has not previously been an issue.
**MSH-19** (Principal Language of Message): This is an optional field; we have not tested values in this field so please leave blank in messages to VT.

Once these two issues are corrected, we will need all messages generated from SimpleReport from 5/19 forward to be resubmitted, including both SimpleReport and ImageMover (OTC) messages.

Some messages for testing conducted using **iHealth tests** also have the following issues:
OBR-4 (Universal Service Identifier) – LOINC code missing
OBX-3.2 (Observation Identifier) – value missing
OBX-17.1 (Observation Method) – Identifier missing
Example Accession # 4f2001c-3586-4f28-81ef-2a7237f84410
Example Accession # 2951063-27fc-432a-875d-5a55212a3b33

**Comment by sliu1000** [comment]
User is Therea Dunn can be reached at Theresa.Dunn@vermont.gov

**Comment by sliu1000** [comment]
Is there any chance a change to the SimpleReport/ReportStream code was introduced last week? I was out of the office so apologize for the delayed notification of the errors, but hundreds of SimpleReport messages to Vermont have failed due to the following issues:

MSH-7 (Date/Time of Message): Field not properly formatted as date/time; we are currently receiving date only. Please ensure this field is properly formatted as date/time. This has not previously been an issue.
MSH-19 (Principal Language of Message): This is an optional field; we have not tested values in this field so please leave blank in messages to VT.

Once these two issues are corrected, we will need all messages generated from SimpleReport from 5/19 forward to be resubmitted, including both SimpleReport and ImageMover (OTC) messages.

Some messages for testing conducted using iHealth tests also have the following issues:
OBR-4 (Universal Service Identifier) – LOINC code missing
OBX-3.2 (Observation Identifier) – value missing
OBX-17.1 (Observation Method) – Identifier missing
Example Accession # 4f2001c5-3586-4f28-81ef-2a7237f84410
Example Accession # 2951063b-27fc-432a-875d-5a55212a3b33

**Comment by sarahnw** [comment]
@Adrian-Brewster do we have a new ticket for the resubmissions? Is this something SR should handle? Or are we responsible?

**Comment by Adrian-Brewster** [comment]
@sarahnw I will defer to @MauriceReeves-usds on who should handle the resubmissions. If the change to the code that caused the resubmissions was on our end, we should probably handle the resubmissions. Thats my thought at least. 

@sliu1000 Are the resubmissions being tracked separately?

**Comment by sliu1000** [comment]
@Adrian-Brewster Yes, i created a separate ticket for the resubmission.

**Comment by MauriceReeves-usds** [comment]
These are proper resubmissions that need to be corrected and resent. I'll be doing this tomorrow. @sarahnw @Adrian-Brewster @anshulkumar-usds

**Comment by Adrian-Brewster** [comment]
@MauriceReeves-usds has this been completed?

**Comment by Adrian-Brewster** [comment]
Once iHealth change gets pushed to production, SimpleReport should be able to complete resubmissions. @MauriceReeves-usds to coordinate.

**Comment by sarahnw** [comment]
@MauriceReeves-usds is this done, can we close it?
