### ISSUE TITLE
Investigate why older blobs aren't being removed

### ISSUE THREAD

**Issue by cwinters-usds** [CDCgov/prime-reportstream#5566]
According to [this in TF](https://github.com/CDCgov/prime-reportstream/blob/master/operations/app/terraform/modules/storage/main.tf#L115-L145) we should be removing blobs whose most recent modification is 60+ days ago. But browsing around the storage account this doesn't seem to be the case (see screenshot).

![Screenshot from 2022-05-23 16-42-52](https://user-images.githubusercontent.com/86251310/169902894-45def3f2-6581-407e-a0f7-b0720a2a6000.png)

**Comment by JosiahSiegel** [comment]
Confirmed resolved:
![image](https://user-images.githubusercontent.com/5522990/170264132-f032eb5c-6184-45cc-8240-f930522fd137.png)
