### ISSUE TITLE
TLS Certification (Brick, Green)

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#5574]
Brick Green still has not submitted Cert for TLS 

Cannot move forward in the process

Brick Green was supposed to upload cert today in the morning

**Comment by brick-green** [comment]
Done - retreived the cert from Entrust and uploaded to NY

**Comment by sliu1000** [comment]
@brick-green User is asking a follow-up question on this.

From: Ummidi, Madan (HEALTH) <Madan.Ummidi@health.ny.gov> 
Sent: Thursday, June 23, 2022 2:58 PM
To: Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR) <rut5@cdc.gov>; Schabses, Karolina A (HEALTH) <karolina.schabses@health.ny.gov>; Yang, Zhaohui (HEALTH) <zhaohui.yang@health.ny.gov>
Cc: Report Stream (CDC) <reportstream@cdc.gov>; Kumar, Anshul (CDC/OD/OCS) <rdz8@cdc.gov>; Brewster, Adrian (CDC/DDPHSS/OD/HITSSU) (CTR) <mpz9@cdc.gov>; Reeves, Maurice (CDC/OD/OCS) <qva8@cdc.gov>; doh.dl.UPHN-Lite-Support <UPHN-Lite-Support@health.ny.gov>; Greene, Thomas (CDC/DDPHSS/OD/HITSSU) <trv5@cdc.gov>
Subject: RE: AFT Account - CDC Report Stream - New York State

Hi Brick, I’m following up on where are you on testing the connectivity. If you have a timeline please let us know. Thank you.
