### ISSUE TITLE
CA - Register a New Account

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5578]
1) I would like to set up a user account with ReportStream.

Name: Steve Jordan
Job Title: Project Manager
Organization: Birdrock Laboratories
Email: sjordan@labhealth.com
Phone: 201-574-5845
Referring Organization: CalREDIE
State: California

2) The expected volume would be about 100/day. I don’t think the lab is reporting to any other states.

3) My schedule is flexible, so either I or one of my colleagues can be on a call any time between 8:00 AM and 6:00 PM Eastern any day this week.

**Comment by Adrian-Brewster** [comment]
Sent back to CADOH. Sender wanted to send via SFTP to us.
