### ISSUE TITLE
PagerDuty alert: SendFunction - FAILED

### ISSUE THREAD

**Issue by JosiahSiegel** [CDCgov/prime-reportstream#5581]
## Problem statement

[PagerDuty](https://prime-cdc.pagerduty.com/incidents/Q0F09FMKNF9LVQ) alert: SendFunction - FAILED

## What you need to know

```
[1;31m21:22:51.446 [pool-2-thread-269][2706] 
FATAL-ALERT gov.cdc.prime.router.azure.SendFunction - 
FAILED Sftp upload of inputReportId 12d00f1a-74a1-4f8c-8316-fdf3f79eec22 to SFTPTransportType(host=prod.moveit.state.co.us, port=22, filePath=./, credentialName=null) (orgService = co-phd.elr-hl7), 
Exception: Exhausted available authentication methods, All retries failed.  Manual Intervention Required.  
Send Error report for: 12d00f1a-74a1-4f8c-8316-fdf3f79eec22 to co-phd.elr-hl7[m
```

**Comment by JosiahSiegel** [comment]
[Error](https://portal.azure.com/#blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/source/Alerts.EmailLinks/scope/%7B%22resources%22%3A%5B%7B%22resourceId%22%3A%22%2Fsubscriptions%2F7d1e3999-6577-4cd5-b296-f518e5c8e677%2Fresourcegroups%2Fprime-data-hub-prod%2Fproviders%2Fmicrosoft.operationalinsights%2Fworkspaces%2Fpdhprod-loganalyticsworkspace%22%7D%5D%7D/q/eJxljrEOgjAURXe%2B4m7oUEHY3DpAHHAh%2FEDTvkADea9pS3Dw49VVkzOenJyqQlM3japb1V5v6J522x3BigqLu9AWVaaUoRTy4hM%2BGKwsB4NilIhAEaO3K%2B4iruh3ttkL6xAGmVPxwrFQJDwoJTN%2Fs5yN54Sy15MelB66cSph2IEln%2F61n4%2Fy%2FAY%3D/prettify/1/timespan/2022-05-25T21%3A23%3A15.0000000Z%2F2022-05-25T21%3A28%3A15.0000000Z) occurred again at `2022-05-25T21:25:32Z`:

```
[1;31m21:25:32.845 [pool-2-thread-2162][28492] FATAL-ALERT gov.cdc.prime.router.azure.SendFunction - 
FAILED Sftp upload of inputReportId e46140f2-9381-4792-a5be-3eb5ebf13db7 to SFTPTransportType(host=prod.moveit.state.co.us, port=22, filePath=./, credentialName=null) (orgService = co-phd.elr-hl7), 
Exception: Exhausted available authentication methods, All retries failed.  Manual Intervention Required.  
Send Error report for: e46140f2-9381-4792-a5be-3eb5ebf13db7 to co-phd.elr-hl7[m
```

**Comment by JosiahSiegel** [comment]
[Error](https://portal.azure.com/#blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/source/Alerts.EmailLinks/scope/%7B%22resources%22%3A%5B%7B%22resourceId%22%3A%22%2Fsubscriptions%2F7d1e3999-6577-4cd5-b296-f518e5c8e677%2Fresourcegroups%2Fprime-data-hub-prod%2Fproviders%2Fmicrosoft.operationalinsights%2Fworkspaces%2Fpdhprod-loganalyticsworkspace%22%7D%5D%7D/q/eJxljrEOgjAURXe%2B4m7oUEHY3DpAHHAh%2FEDTvkADea9pS3Dw49VVkzOenJyqQlM3japb1V5v6J522x3BigqLu9AWVaaUoRTy4hM%2BGKwsB4NilIhAEaO3K%2B4iruh3ttkL6xAGmVPxwrFQJDwoJTN%2Fs5yN54Sy15MelB66cSph2IEln%2F61n4%2Fy%2FAY%3D/prettify/1/timespan/2022-05-26T15%3A23%3A15.0000000Z%2F2022-05-26T15%3A28%3A15.0000000Z) occurred again at `2022-05-26T15:25:50Z`

**Comment by JosiahSiegel** [comment]
Merged 3 incidents into single on [pagerduty](https://prime-cdc.pagerduty.com/incidents/Q0F09FMKNF9LVQ)

**Comment by MauriceReeves-usds** [comment]
Increment in the version of SSHJ to `0.33` caused this error. Rolled back to `0.32` addressed it.

**Comment by JosiahSiegel** [comment]
Issue also impacting staging: https://prime-cdc.pagerduty.com/incidents/Q10ZXUVNU4C2LG
