### ISSUE TITLE
Compass Urgent Care - Issue w/CSV file

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#5594]
Name: Lauren Young
Email: lyoung@compassurgentcare.com

After running our daily report and switching over to a CSV file, this is the message that pulls up

![download.png](https://images.zenhubusercontent.com/62827d1e0129e15b5c366b1a/072ee684-149f-48e7-aa71-79b5e1940281)

**Comment by shy2cdc** [comment]
6/13 9:11pm

Hi @Adrian-Brewster  - the user is asking for an update on this request.

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5594?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS

**Comment by sliu1000** [comment]
@Adrian-Brewster  Queenie Zhang from Inductivehealth sent an email on 6/22 to confirm that the date/time zone corrects were deployed.  She did mention that they have NOT seen any recent ELR failures but just wanted to confirm. And that we can close out this ticket if the correction was deployed.

queenie.zhang@inductivehealth.com
