### ISSUE TITLE
CA and IL - Nova Labnetics Diagnostics - Test Message

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5598]
User Mihail Sinitaru 
Email: mihai.sinitaru@limsabc.com 

Based on that message, can you **confirm** that it's good for you, and can you, please, provide the credentials **where** we can **drop** messages?

Here is a test message approved by the IL state:
MSH|^~\&|LIMSABC|Nova Diagnostics Labs LLC^14D2216112^CLIA|ILDOH|IL|20220526045500||ORU^R01^ORU_R01|RNLN7216|T|2.5.1
SFT|LIMSABC^L^^^^LIMSABC&05D2182047&ISO^XX^^^|2.12.465|LIMSABC|88e51d4e|LIMSABC HL7 v2.5 object|202109200000
PID|1||1852||Patient^Test^Illinois^||19930304|M||W|1122 400 North Rd^^Cissna Park^IL^60924^USA^H^^||^PRN^PH^^^815^4572097|||||||||H^Hispanic or Latino^HL70189^H^Hispanic or Latino^L^2.5.1^2.11.200
ORC|RE|RNLN7216^LIMSABC^2.16.840.1.113883.9.260^ISO|RNLN7216^Nova Diagnostics Labs LLC^2.16.840.1.113883.9.260^ISO|||||||||1234567890^Doctor^Test^^Md^^^^NPI||^WPN^PH^^^262^6536223^^|||||||TEST SITE^L^^^^NPI&2.16.840.1.113883.9.260&ISO^XX^^^|581 Temple Ave^^Starke^FL^32091^USA|^WPN^PH^^^262^6536223^^|581 Temple Ave^^Starke^FL^32091^USA
OBR|1|RNLN7216^Nova Diagnostics Labs LLC^14D2216112^CLIA|RNLN7216^Nova Diagnostics Labs LLC|94756-4^SARS-CoV-2 (COVID-19) N gene [Presence] in Respiratory specimen by Nucleic acid amplification using CDC primer-probe set N1^LN^^^^2.34|||20220327044500-0500|20220329074955-0500|||||||258603007|1234567890^Doctor^Test^^^^^^NPI&2.16.840.1.113883.9.260&ISO^L^^^NPI|^WPN^PH^^^262^6536223^^|||||20220329081717-0500|||F
OBX|1|CWE|94756-4^SARS-CoV-2 (COVID-19) N gene [Presence] in Respiratory specimen by Nucleic acid amplification using CDC primer-probe set N1^LN||82334004^Indeterminate^SCT||Not Detected||||F|||20220329081717-0500|||ABI7500_ThermoFisher^ABI7500_ThermoFisher||||||Nova Diagnostics Labs LLC^D^^^^CLIA&2.16.840.1.113883.9.260&ISO^XX^^^14D2216112|2340 Highland Ave Ste^^Lombard^IL^60148^USA
SPM|1|107141&NLN&14D2216112&CLIA^107141&LIMSABC&2.16.840.1.113883.9.260&ISO||258603007^258603007^SCT|||||||||||||20220327|20220327

**Comment by sliu1000** [comment]
@jbiskie 
Updating this ticket with a follow-up question from Adrian Balint (Adrian.balint@limsabc.com) - please let me know if a separate ticket should be created for this:

We would like to reignite the process for integration between LIMSABC and ReportStream. 

We were going back and forth over some small details that we needed to update for this client (NLN) to integrate and report to IL. In the meantime, we have directly established ELR on behalf of this client with IL as well as the following states: IA, MI, MO, TX and VA. There is still NJ pending for NLN and we would like to do this via RS. 

We also have a new client that are in the process of implementing it and that client also require several states integrations. Our system is pretty uniform across all of our clients, but the data coming in and captured by the clients is different. We can definitely provide you with a test message with all the data completed 100%, but we (LIMSABC) cannot control what data is captured by each particular client. 

We definitely want to speed up the signup process with the RS platform. Please provide us with some sort of connection details and let us know if we need to do anything to set up some sort of account for sending the data over to you for validation. We want to prioritize this integration and work with you to complete and be able to transfer the same to other clients in the future. 

I am attaching several messages for you to validate and restart this process. The bellow messages are for test patients from both IL and NJ. Please let us know what changes we need to make and we will respond ASAP.

**Comment by Adrian-Brewster** [comment]
Closing as this is a duplicate ticket. Being tracked separately.
