### ISSUE TITLE
CA - Validating a New Sender

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#5599]
Name: 
Email:

[Write a short description of what you want to achieve with this task]

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by shy2cdc** [comment]
Name: Vanessa Burkhart
Email: vanessa.burkhart@cdph.ca.gov

Received the message & reviewing the details. A couple of questions on items I noticed.

Message Control ID - 20220523172328

Ordering facility & ordering provider address are US Storage Centers?
Address for both fields - U.S.  Storage 4800 Valley Blvd^unit 3103
Need the Ordering Facility & Ordering Provider addresses to be accurate
 

Message Control ID – 20220523172755

Ordering Physician address is NY, the NPI listed in this message has a CA address NPI Number Lookup (npidb.org)

NPI Number Lookup
Find health care providers in the National Provider Identifier database (NPPES).
npidb.org
1215053962 NPI - located in CA, verified on NPI lookup, link above

**Comment by Adrian-Brewster** [comment]
Related to healthcare integration prior to go live. Completed.
