### ISSUE TITLE
pdhprod-reportstream-website: 503

### ISSUE THREAD

**Issue by JosiahSiegel** [CDCgov/prime-reportstream#5602]
## Problem statement

The following error occured for pdhprod-reportstream-website:
`'503 - Service Unavailable' does not match the expected status '200 - OK'.`

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [PagerDuty](https://prime-cdc.pagerduty.com/incidents/Q06RNPPC6JJXBP)
- [Logs](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-data-hub-prod%22%2C%22Name%22%3A%22pdhprod-appinsights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7d1e3999-6577-4cd5-b296-f518e5c8e677%252FresourceGroups%252Fprime-data-hub-prod%252Fproviders%252Fmicrosoft.insights%252Fcomponents%252Fpdhprod-appinsights%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%22857d0d4b-dd26-11ec-b478-501ac51095d4%22%2C%22timestamp%22%3A%222022-05-26T19%3A01%3A22.422Z%22%2C%22cacheId%22%3A%22480dc437-b14b-486a-8ab3-e5ee95507e5f%22%2C%22eventTable%22%3A%22availabilityResults%22%7D)

**Comment by sarahnw** [comment]
Not sure if this is actionable anymore as we're still sending to CA. Closing.
