### ISSUE TITLE
ELR File issues- NJ

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#5606]
Error in Rhapsody Route in PRODUCTION -3 attachments

DOH-ADMIN NJELR [DOH] <NJELR.ADMIN@doh.nj.gov>
Fri 5/27/2022 2:27 PM

Please note the ELR errors in the attached emails.  Please correct and resubmit.

Thank you,

Mike Firkser

Technical Lead - NJDOH ELR Team

NJELR.Admin@doh.nj.gov

**Comment by sliu1000** [comment]
Duplicate to 5537
