### ISSUE TITLE
CA - SimpleReport Errors - OBX-23.6.2 and OBX-23.6.3 are missing

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5611]
**Describe the bug**
We’re seeing errors for quite a few SimpleReport users that started yesterday.  The error is that OBX-23.6.2 and OBX-23.6.3 are missing.  I’ve copied it below and provided some example MSH-4 and MSH-10 values.

**Impact**
But what is strange is that not all results from each of these submitters are failing – the errors seem sporadic – but they are widely distributed across quite a number of SR users – we have over 50 different locations with errors.

Error Message:
Required subcomponent missing in segment 6:OBX.  Field 23, repetition 1, component 6 is missing subcomponent 2, which is required in data structure 2.5.1CA:HD. 
Required subcomponent missing in segment 6:OBX.  Field 23, repetition 1, component 6 is missing subcomponent 3, which is required in data structure 2.5.1CA:HD.

Advanced Molecular D^CDPH000085^CLIA    d690b2eb-c650-46d6-b2c9-13d9a7939ee8
Altus Lab Wellness C^CDPH000085^CLIA    f2e71744-0fbd-4867-b69b-6530f243abe7
Alvarado Hospital Me^CDPH000085^CLIA    0b488343-ad98-4e94-a254-d79d01597056
American Indian Chan^CDPH000085^CLIA    ff192148-02e4-49fd-b520-7c7f4cfed9ab
Assured Home Health^CDPH000085^CLIA    f4cddac4-4983-4ff9-b8a6-d54c53a8f3d5
Aurora San Diego, LL^CDPH000085^CLIA    19c6d795-ff2e-41cc-9bd7-bf5fb081633f
Axis Community Healt^CDPH000077^CLIA    386108e2-1a25-4677-86c8-f3210229a334
Berenda^CDPH000085^CLIA    5ac3326b-e40d-4209-b82a-3ea0f9bc05fd
BHS American Recover^CDPH000085^CLIA    229d6cdd-b8e8-47f1-aa92-e461c2fb77a2
CCC College of the C^CDPH000085^CLIA    22cbb40a-2e6f-42bc-9180-b17c5762fa11
Cedar Crest Nursing^CDPH000085^CLIA   04b0f4f9-8369-43ff-8e3d-4f6eba1eb966
Cedars Health Main L^CDPH000085^CLIA    2ab2cb9f-b284-48ce-83d8-897afe12ce76
Chavez^CDPH000085^CLIA     29947656-c1e9-4a8e-8dd0-80832aa35cba

**Comment by oslynn** [comment]
There is no CSV file associate with this message ID 'd690b2e-c650-46d6-b2c9-13d9a7939ee8'

**Comment by sliu1000** [comment]
@oslynn Hi - how can I help you? Should I contact the customer and ask for the associated CSV file?

**Comment by oslynn** [comment]
@Adrian-Brewster @anshulkumar-usds, how can resubmit these messages?  Is it via email?  If so, may I have the contact info for me to resubmit?

**Comment by sliu1000** [comment]
Hi @oslynn, my apologies in not including earlier.  The email is Ellaison.Carroll@cdph.ca.gov

**Comment by oslynn** [comment]
@sliu1000 I apologize for not seeing your message.  Yes, please as ask the customer for the associated CSV files.  Thanks.

**Comment by oslynn** [comment]
@sliu1000 , should resubmit by email to [Ellaison.Carroll@cdph.ca.gov](mailto:Ellaison.Carroll@cdph.ca.gov)?

**Comment by sliu1000** [comment]
@oslynn Yes, I just asked her to send via email. I'll add here once received.

**Comment by oslynn** [comment]
@sliu1000 , thanks.

**Comment by brick-green** [comment]
Hi @sliu1000 and @oslynn, I want to clarify here. @oslynn, you have the files ready to send to CA? If so, then we do not need any additional CSV files from CA. The next step is to send the files. In the past, I have just sent the files via their SFTP connection. @oslynn are you comfortable doing that? The other potential option is encrypted email. @sliu1000 Can you ask CA if encrypted email is an option to send a small number of HL7 results and if so, then which email address should that encrypted email be sent to?

**Comment by oslynn** [comment]
@brick-green, yes I have all the HL7 files ready to resubmit.  It is easy for me to encrypt and email files to them.  I will wait for @sliu1000 to clarify with them.  Thanks.

**Comment by sliu1000** [comment]
@oslynn @brick-green I just sent Carroll a follow-up email. I'll update you all once I receive a response.

**Comment by brick-green** [comment]
@sliu1000 Just saw the email. The contact's first name is actually Ellaison. Carroll is her last name. I called her Carroll the first time I was on a call with her and she told me she gets it all the time, haha. Next, it looks like there's still a bit of confusion. Ellaison does not need to send us any files. We are interested in sending CA an encrypted email with the HL7 results. We need to know if that is an accepted practice for CA. So we just need you to ask if CA is willing to accept HL7 results via encrypted email.

**Comment by sliu1000** [comment]
@brick-green Got it, I'll resend the email with the correction.

**Comment by oslynn** [comment]
@sliu1000 would you please let me know if I can email the resubmission back to CA.  Thanks.

**Comment by sliu1000** [comment]
@oslynn GM - CA has not emailed us back yet. I'll give them a call in a few hours since they are on west coast time.

**Comment by sliu1000** [comment]
@oslynn FYI - I spoke with Adrian and he advised me that you two spoke about sending it via SFTP.

**Comment by oslynn** [comment]
@sliu1000 I sftped all files to CA already.  Would you please notify them? Thanks.

**Comment by sliu1000** [comment]
@oslynn I just let them know.
