### ISSUE TITLE
VT - ProPhase Diagnostics

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#5614]
Name: Theresa Dunn
Email: theresa.dunn@vermont.gov

Additionally, the message we did receive failed HL7 validation. I notified ReportStream earlier today and am including the feedback below as well for your awareness.

MSH-3 (Sending Application Universal ID and Universal ID Type): Required values missing.

               Current value: |CDC PRIME - Atlanta|

               Expected value: |CDC PRIME - Atlanta^2.16.840.1.114222.4.1.237821^ISO|

MSH-5 (Receiving Application): Incorrect values for messages submitted to Vermont

               Current value: |CDC Prime|

               Expected value: |NBS^2.16.840.1.114222.4.1.185.1^ISO|

MSH-6 (Receiving Facility): Incorrect values for messages submitted to Vermont

               Current value: |CDC Prime|

               Expected value: |VDH^2.16.840.1.114222.4.1.185^ISO|

MSH-7 (DateTime of Messsage): Field formatted as date only rather than date/time. Note that this message was received prior to the date/time fix implemented at ReportStream this afternoon, so this may be resolved.

MSH- (Message Profile Identifier): Invalid value provided.

               Current value: |PHLabReport-Batch^Mirth^2.16.840.1.114222.4.1.238646^ISO

               Expected value: |PHLabReport-NoAck^ELR_Receiver^2.16.840.1.113883.9.11^ISO

OBX-17 (Observation Method): Name of coding system not provided in OBX-17.3.

               Current value: |PhoenixDx SARS-CoV-2 Multiplex_Trax Management Services Inc.^PhoenixDx SARS-CoV-2 Multiplex^^^^^2.68^^PhoenixDx SARS-CoV-2 Multiplex_Trax Management Services Inc.|

               Expected value: |PhoenixDx SARS-CoV-2 Multiplex_Trax Management Services Inc.^PhoenixDx SARS-CoV-2 Multiplex^99ELR^^^^2.68^^PhoenixDx SARS-CoV-2 Multiplex_Trax Management Services Inc.|

**Comment by shy2cdc** [comment]
We are continuing to see messages from ProPhase Diagnostics fail HL7 validation for the reasons listed below. Please provide an update.

**Comment by jbiskie** [comment]
Danielle Smalley <danielle.smalley@healthcareintegrations.com>
Fri 6/3/2022 10:45 PM

I have this corrected on my end and have reprocessed the 44 results we have for VT to ReportStream.
