### ISSUE TITLE
Top Rank Labs - Add another User to existing ReportStream Portal

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5618]
Email from Deepak Hingorani from Top Rank Diagnostic Lab

**Action:**
Please add Shanon Nakayama as the new user. 
I have copied her on this email. 
Her email address is - shanonnakayama@gmail.com
Her cell phone number is (714)342-5414.

**Comment by Adrian-Brewster** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5618?planning-poker) with ZenHub @sarahnw

**Comment by sarahnw** [comment]
I've asked Charlye to look into this as this is a CSV uploader.

**Comment by sliu1000** [comment]
I see that shanonnakayama@gmail.com has an account in simplereport. I think this can be closed out now.
