### ISSUE TITLE
NJ: CDC Prime: Error in Rhapsody Route in PRODUCTION

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#5620]
Name: Mike Firkser
Email: NJELR.Admin@doh.nj.gov

Please note the ELR Error below in your ELR File: covid-19-aae290f5-2cc7-4149-9b69-d8b9b6d241a3-20220531134120.hl7

Order: 9bd72213-8db3-45c9-895f-c3aae935ab1b

ORC-23 is missing.  Please correct and resubmit.

**Comment by sliu1000** [comment]
Duplicate to 5537
