### ISSUE TITLE
Stop mocking `rest-hooks`

### ISSUE THREAD

**Issue by mreifman** [CDCgov/prime-reportstream#5623]
There are a few instances[1] where we test components by using `jest.mock` on `rest-hooks`, which is not recommended: https://resthooks.io/docs/guides/unit-testing-components

PR #5587 adds a [test helper](https://github.com/CDCgov/prime-reportstream/pull/5587/files#diff-4235a213e08ec2237314718914d7ac34dfcf4273c14e448a28c4a65c4410ba3cR22) for setting up `rest-hooks` fixtures in component tests, but it can't go in a shared location until we stop mocking `rest-hooks`.

**Acceptance Criteria**
- The `renderWithResolver` method is available from [`CustomRenderUtils.tsx`](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/utils/CustomRenderUtils.tsx).
- All component unit tests that need canned responses to `rest-hooks` calls are refactored to use `renderWithResolver` rather than `jest.mock`ing `rest-hooks`.

---

[1] GitHub search is bad at this sort of thing, so here are the references: 
- https://github.com/CDCgov/prime-reportstream/blob/0fe7fbd220b93889a2f4473adf8db4f3f7ed1935/frontend-react/src/components/Admin/EditSenderSettings.test.tsx#L14
- https://github.com/CDCgov/prime-reportstream/blob/0fe7fbd220b93889a2f4473adf8db4f3f7ed1935/frontend-react/src/pages/admin/AdminOrgNew.test.tsx#L14 
- https://github.com/CDCgov/prime-reportstream/blob/0fe7fbd220b93889a2f4473adf8db4f3f7ed1935/frontend-react/src/pages/daily/Table/ReportsTable.test.tsx#L34
- https://github.com/CDCgov/prime-reportstream/blob/0fe7fbd220b93889a2f4473adf8db4f3f7ed1935/frontend-react/src/pages/submissions/SubmissionDetails.test.tsx#L26

**Comment by doug-s-nava** [comment]
going to close this as we are moving off of rest hooks, and this testing business will come out in the wash
