### ISSUE TITLE
Phone Number Validation Logic to Account for Extension number

### ISSUE THREAD

**Issue by jorg3lopez** [CDCgov/prime-reportstream#5628]
Currently, our phone number validation logic throws a warning message and blanks the phone number when an extension number is included as part of the phone number. This is true for Ordering Facility Phone Number but it might be the same case for any phone number field.

Warning message:
![image.png](https://images.zenhubusercontent.com/60d4ee31a2886cc02f9caaef/216d7fca-4af1-4d5c-a257-51924760a092)

### Acceptance criteria
- Modify phone validation logic to accept phone numbers with extension number: (555) 555 - 5555 ext. 5555

**Comment by jorg3lopez** [comment]
This might need further investigation as I can't find anything related to having extension number for ORC-23.

**Comment by Adrian-Brewster** [comment]
May be related to all of the NJ issues

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5628?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS
