### ISSUE TITLE
NH ELR Feedback-ProPhase Diagnostics - Reporting COVID Results to New Hampshire DHHS

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#5631]
Feedback on the eight messages that were sent over. ELR Issues 

from Corinne Davis, MPH, MS

**Comment by TaneaY** [comment]
[https://app.zenhub.com/files/304423150/c7bc3b89-5028-4a20-925d-f1be57706f4b/download](https://app.zenhub.com/files/304423150/c7bc3b89-5028-4a20-925d-f1be57706f4b/download)

**Comment by oslynn** [comment]
Couldn't find Hl7 files associated with the following message ids:
20220526225112
20220531061816

**Comment by oslynn** [comment]
@jbiskie, who is the sender for NH?  Or, what schema can I use to regenerate the new HL7 file for them?

**Comment by TaneaY** [comment]
Update sent from customer: I reviewed the messages sent on June 7th and it looks like all the issues except NH28 (below) was addressed. Please let us know if you are able to correct NH28. We will keep monitoring the feed and let you know if we notice anything else.

 ·         OBX-17 (Device Identifier) should be formatted as outlined in the LIVD file (https://www.cdc.gov/csels/dls/sars-cov-2-livd-codes.html

Sent: PhoenixDx SARS-CoV-2 Multiplex_Trax Management Services Inc.^PhoenixDx SARS-CoV-2 Multiplex^^^^^2.68^^PhoenixDx SARS-CoV-2 Multiplex_Trax Management Services Inc.

Example Correction:
|PhoenixDx SARS-CoV-2 Multiplex_Trax Management Services Inc._EUA^^99ELR~INSERT EQUIPMENT UID HERE_INSERT EQUIPMENT UID TYPE HERE^^99ELR|

**Comment by oslynn** [comment]
Email from Danielle regarding NH27 wrong city and zip, but correct state.
--------------------------------------------------------------------------------
Danielle Smalley <danielle.smalley@healthcareintegrations.com>
Fri 6/10/2022 11:30 AM
Hi Ott,

I reviewed the three accession numbers provided and these look like data entry errors. The addresses went to ReportStream exactly how they came into ProPhase, but upon further digging it looks like these should reflect NY, not NH. I am looking into adding logic on our end to filter these cases out in the future.

Thank you,

**Comment by oslynn** [comment]
Regarding the NH28, they will change on their side and send to us for verify.

**Comment by oslynn** [comment]
Status:  
1.) Update the organization.yml 
2.) ./prime multisettings get --env staging -f nh > ./workspace/nh-staging-setting.yml

**Comment by oslynn** [comment]
@TaneaY, I SFTP updated hl7 to NH SFTP server, just now.  Would you please notify them?
