### ISSUE TITLE
CDC Prime: Error in Rhapsody Route in PRODUCTION

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#5635]
Please note the ELR Errors below in your ELR File: covid-19-446c630b-ae8a-43e2-b65b-c0971bb5c22a-20220601134120.hl7

Please correct and resubmit.

Thank you,

Mike Firkser

Technical Lead - NJDOH ELR Team

NJELR.Admin@doh.nj.gov

**Comment by sliu1000** [comment]
Duplicate to 5537
