### ISSUE TITLE
CDC Prime: Error in Rhapsody Route in PRODUCTION

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#5636]
Please note the errors below in our ELR File: covid-19-f79192c6-1bbc-4ffa-86c8-c27fef2751ba-20220601134105.hl7

ORC-23 missing from 4 messages.  Please correct and resubmit.

Thank you,

Mike Firkser

Technical Lead - NJDOH ELR Team

NJELR.Admin@doh.nj.gov

**Comment by sliu1000** [comment]
Duplicate to 5537
