### ISSUE TITLE
VA - Peraton (Follow-Up Questions)

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5639]
Daniel Park - Daniel.Park@peraton.com

Follow-up Questions on signing up for Reportstream.

Hello!

Thank you for the quick response. I have some more follow up questions:

•	Is there a time line on supporting beyond COVID-19? Or is ReportStream only focusing on pandemic related reporting?
•	If there is no testing facility registered in my jurisdiction, does ReportStream/PRIME reach out to encourage them to register?
•	Is ReportStream working on getting the other 21 states and territories onboarded or do they wait for local demand to arise?
•	As a consumer of ReportStream, am I limited to my jurisdiction or can I view other jurisdiction as well to see the disease at a national level?
•	What kind of analytics and insights does ReportStream offer? Will there be an analytic platform?
•	The “built-in network” come from the ReportStream website: https://reportstream.cdc.gov/

Thank you,

-dan park

Dan Park
Lead Solutions Architect
Global Health & Finance Campaigns and Solutions
Office: (571) 481-9528

**Comment by Adrian-Brewster** [comment]
Adrian responded to email.
