### ISSUE TITLE
Prototype API Error Messages with Codes

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#5641]
## Problem statement
As a ReportStream user, when sending incorrect/invalid data to ReportStream, I want to see actionable and easy to understand error messages, clearly identifying the problem and giving some guidance on how to send data correctly.

## What you need to know
Work breakdown for error msg improvement initiative
https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1659379562245/028bbeb7dd7b819298ba1b436703882855bc767f?sender=u3fea607b46e84058d3224917

https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Onboarding%20%26%20Ops/API%20Error%20Msgs%20for%20Improvement.docx?d=w6327b3dc2ace4757aa62ab8dcfffb535&csf=1&web=1&e=Ww1wBl

## Acceptance criteria

- Error Messages are displayed as described in the tickets under this initiative

## To do

- [ ] ...

**Comment by kevinhaube** [comment]
The work for this may change based on the following topic raised tomorrow among tech leads:
> Can the Experience team, in our effort to provide better errors for the web app, update our Error reporting to use codes that are translated rather than pure english error messages from the source code?

**Comment by chris-kuryak** [comment]
Closing. All issues complete.
