### ISSUE TITLE
Update the API error msg description returned

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#5643]
## Problem statement

As a user, I want to see the error message describe clearly what is expected in the data fields identified below, so that I can correct the data error and resend data in a format that will be accepted by the ReportStream API.

Refer - https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B3fac1cd7-3045-479b-b46e-1f2550a3415e%7D&action=editnew&cid=598df61b-8bdd-4e59-ac83-2bae83b41783

Scope - where column A is Ticket#5643

## What you need to know

Initial doc from O&O: https://cdc.sharepoint.com/teams/USDSatCDC/_layouts/15/doc.aspx?sourcedoc={6327b3dc-2ace-4757-aa62-ab8dcfffb535}&action=edit

Doc of Errors & Warning Info from Seth: https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FTeam%20Documents%2FExperience%20Team%2FEngineering%2FMisc%20Experience%20Eng%20Docs%2FReportStream%20Errors%20%26%20Warnings%20Inventory%20%2D%20sample%20files&viewid=17db3ff6%2D95c5%2D4562%2Da1f3%2D12b5097b5947

Link to Error & Warnings Inventory SAMPLE FILES from Seth: https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FTeam%20Documents%2FExperience%20Team%2FEngineering%2FMisc%20Experience%20Eng%20Docs%2FReportStream%20Errors%20%26%20Warnings%20Inventory%20%2D%20sample%20files&viewid=17db3ff6%2D95c5%2D4562%2Da1f3%2D12b5097b5947

Research from #6307: https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B3fac1cd7-3045-479b-b46e-1f2550a3415e%7D&action=editnew&cid=598df61b-8bdd-4e59-ac83-2bae83b41783

## Acceptance criteria
- [ ] As recommended in Column I,  https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B3fac1cd7-3045-479b-b46e-1f2550a3415e%7D&action=editnew&cid=598df61b-8bdd-4e59-ac83-2bae83b41783
Scope - where column A is Ticket#5643

- [ ] Modify existing unit tests as needed

## Excluded
- Any new tests for uncovered conditions

**Comment by bgantick** [comment]
TODO: add example file/command

**Comment by RakshindaAslam** [comment]
@carlosfelix2 @JGreenFearless @jbiskie - Can you help us with what is considered acceptable phone number format for this field? 

Error/Warning Message for Phone Number format issues is displayed as - fieldname " field accepts numeric value only. Please format as 5555551234."
cfelix --- I think we are accepting other international formats, so make sure this message takes any other formats into consideration.

cc @bgantick

**Comment by bgantick** [comment]
Example HL7 files can be found in [this slack thread](https://www.slack.com/archives/C025F5W5Q7L/p1655228154154049?thread_ts=1655151942.284019&cid=C025F5W5Q7L) or in #5709

**Comment by RakshindaAslam** [comment]
Review the recommended error/warning msgs with O&O team. cc @brick-green @jbiskie @jh765
