### ISSUE TITLE
Improve Error Msgs for LIVD Lookups

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#5651]
## Problem statement

**** Ticket in progress ****
As a user, I want to see the error message describe clearly what is expected in the data fields identified below, so that I can correct the data error and resend data in a format that will be accepted by the ReportStream API.
- Testkit name ID
- Device id
- Equipment model name

## What you need to know

https://cdc.sharepoint.com/teams/USDSatCDC/_layouts/15/doc.aspx?sourcedoc={6327b3dc-2ace-4757-aa62-ab8dcfffb535}&action=edit

## Acceptance criteria

- [ ] Error Message for Testkit name ID - ??

## To do

- [ ] ...

**Comment by HeatherRienks** [comment]
@kevinhaube - any feedback on this ticket? It says it is "in progress"- not sure if we need to bring it out of New Items...

**Comment by kevinhaube** [comment]
@HeatherRienks I'll take a look into this. I'm working on the outline for implementing codes throughout all error messages, and LIVD errors will be part of that plan 😄

**Comment by kevinhaube** [comment]
Okay, i can confidently say this is being handled as a part of the Platform team's API Error Codes work. Closing out!
