### ISSUE TITLE
New User Okta invite template design

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#566]
Build an invite email for ReportStream download site users. Have a link to ReportStream. 

- Should point to right location
- Should _not_ include SimpleReport branding etc

- [ ] Template needs to go under different locale in Okta @mry-usds

**Comment by sean-usds** [comment]
Duplicate of https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3634
