### ISSUE TITLE
AK - H7 Failure Message

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5663]
**Describe the bug**
Several results we have received through SimpleReport have errored out our system.  There were a total of 4 errors from three testing sites. All four of the errors were the same, I believe: The code for Ordered Test name is missing. Blank identifiers in segments **HL7LabReport.HL7PATIENT_RESULT.ORDER_OBSERVATION.ObservationRequest.UniversalServiceIdentifier**

**Impact**
Reporting Facility ICY Strait Point LLC and Silver Bay Seafoods

Screenshot
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/894b16db-1e39-4ef3-8f33-16f465ac592e)

**Comment by sliu1000** [comment]
From: Weingartner, Clayton H (HSS sponsored) <clayton.weingartner@alaska.gov> 
Sent: Wednesday, June 8, 2022 3:52 PM
To: Report Stream (CDC) <reportstream@cdc.gov>; SimpleReport Support (CDC) <simplerpt_support@cdc.gov>
Cc: Tompkins, Megan (CDC alaska.gov) <MEGAN.TOMPKINS@ALASKA.GOV>
Subject: RE: SimpleReport result(s) submission with errors: State of Alaska Division of Public Health (Ticket #5663)

Hello,

I was hoping to follow up and get an update, if possible, regarding Ticket #5663? 

Please refer to emails below for background/context.

Thank you,


Clayton Weingartner, MPH | Data Scientist  
State of Alaska | Department of Health and Social Services 
Division of Public Health | Section of Epidemiology
tel: 907-782-6283 | e-mail: clayton.weingartner@alaska.gov

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5663?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS

**Comment by sliu1000** [comment]
Hello,  The user is looking for an update on this.  They continue to receive errors.

From: Tompkins, Megan L (HSS) <megan.tompkins@alaska.gov> 
Sent: Friday, June 24, 2022 4:34 PM
To: Report Stream (CDC) <reportstream@cdc.gov>; Weingartner, Clayton H (HSS sponsored) <clayton.weingartner@alaska.gov>
Subject: RE: SimpleReport result(s) submission with errors: State of Alaska Division of Public Health (Ticket #5663)

Hello Sharon and team-
I wanted to check back in in hope we can please get an update on this issue? We continue to receive errors. 

In case it’s helpful, it appears to me that both the OBR and OBX lines associated to LOINC 97097-0 have fatal format errors. 
OBR is missing an ordered test LOINC and description:
OBR|1`|9c369953-49d4-45ca-8e3c-6e20ef9b9cba`^SBS-Valdez^02D2226515^CLIA|9c369953-49d4-45ca-8e3c-6e20ef9b9cba^SBS-Valdez^02D2226515^CLIA|^^LN|||2022062217225000000|2022062217225000000||||||||^Seafoods^Silver Bay^^^^^^^^^^U|2069927573^WPN^PH^^1^206^9927573|||||2022062217375000000|||F

OBX is missing a resulted test description: 
OBX|1|CWE|97097-0^^LN||260373001^Detected^SNM|||A|||F|||2022062217225000000|02D2226515^SBS-Valdez^CLIA||||2022062217375000000||||SBS-Valdez^^^^^CLIA&2.16.840.1.113883.4.7&ISO^XX^^^02D2226515|210 S Harbor Drive^^Valdez^AK^99686

Looking forward to hearing more from your team as soon as you’re able.
Thank you,
Megan


Megan Tompkins, MPH
Public Health Informaticist II
Alaska Department of Health & Social Services | Division of Public Health
Section of Epidemiology | Infectious Disease Epi
megan.tompkins@alaska.gov 
O: (907)269-8014 | C: (907)717-0351 | Fax: (907)563-7868
Section of Epidemiology: (907) 269-8000
https://dhss.alaska.gov/dph/Epi/pages/default.aspx

**Comment by sliu1000** [comment]
June 29, 2022 at 2:51 PM. Email from Clayton H. Weingartner - looking for an update:

Received Today from SBS-Valdez yesterday:

11 Message IDs

`b2e6d9a8-4669-4ff0-b58c-e852c571027a`
`ec57771a-2de0-428e-943e-bfb79533042d`
`78dcbfe0-b9a4-4a26-8d7a-82bd12df5f77`
`cb77f97d-4836-4299-8d1a-4dcbe149e153`
`91fe1d89-6633-4582-b90a-37776c977cbe`
`f09b0100-0917-4cca-a578-b236ec392948`
`c82e61a3-30d3-46c3-83e5-90e951012cb9`
`bdd6245a-fc10-4694-83cb-bd6c47234da2`
`93170a16-44e0-459d-8815-cd6430911d65`
`2c64034c-7c15-4313-8c5c-0d23e90dd2fd`
`bc3f6b35-9df9-4027-85eb-583e549c09a4`

**Comment by sliu1000** [comment]
@MauriceReeves-usds @Adrian-Brewster @sarahnw 

User believes that the test associated with LOINC 97097-0 hasn't been fully set up by us.

From: Tompkins, Megan L (HSS) <megan.tompkins@alaska.gov> 
Sent: Wednesday, June 29, 2022 4:48 PM
To: Weingartner, Clayton H (HSS sponsored) <clayton.weingartner@alaska.gov>; Report Stream (CDC) <reportstream@cdc.gov>; White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>
Cc: Brewster, Adrian (CDC/DDPHSS/OD/HITSSU) (CTR) <mpz9@cdc.gov>; Reeves, Maurice (CDC/OD/OCS) <qva8@cdc.gov>; Wallace, Jayna (CDC/DDPHSS/OD/HITSSU) <tof4@cdc.gov>
Subject: RE: SimpleReport result(s) submission with errors: State of Alaska Division of Public Health (Ticket #5663)

Thanks much, Sharon. To reiterate text down below: it appears that the test associated with LOINC 97097-0 hasn’t been fully set up there on your side, as an ordered or reported test. I believe all the failures we have are associated with selection of this test.

We appreciate your assistance, take care!
-Megan


Megan Tompkins, MPH
Public Health Informaticist II
Alaska Department of Health & Social Services | Division of Public Health
Section of Epidemiology | Infectious Disease Epi
megan.tompkins@alaska.gov 
O: (907)269-8014 | C: (907)717-0351 | Fax: (907)563-7868
Section of Epidemiology: (907) 269-8000
https://dhss.alaska.gov/dph/Epi/pages/default.aspx

**Comment by Jcavallo7** [comment]
Update *7/6/22*

Hello,

 

I was hoping to check in regarding the status of our help ticket #5663?

 

We continue to receive test results submitted (via SimpleReport) that are erroring out of our system.

 

Any update on if/when there will be a fix to this issue would be greatly appreciated.

 

 

The most recent failure was from this testing site:

 

2021-09-30T22:37:46.93Z

URGENT CARE AT LAKE LUCILLE

Urgent Care at Lake Lucille

02D0892730

185 EAST PARKS HIGHWAY

WASILLA

Matanuska Susitna

AK

99654

(907) 373-4200

 

urgent_care

2022-07-06T00:38:23.451Z

 

Thank you,

 

Clayton Weingartner, MPH | Data Scientist  

State of Alaska | Department of Health and Social Services

Division of Public Health | Section of Epidemiology

tel: 907-782-6283 | e-mail: clayton.weingartner@alaska.gov

**Comment by sarahnw** [comment]
there's an ongoing email chain for this one. I believe SR is going to resend.

**Comment by sarahnw** [comment]
Clayton wrote back this ticket is officially closed... so I'm going to close it!
