### ISSUE TITLE
wa - duplicate results in file 

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#5665]
User is having issues with results duplicating on a file

User cannot update the feed

When user opens file it shows the duplicated results

should have no duplicates ![Screenshot 2022-06-02 181914.png](https://images.zenhubusercontent.com/62828ac9597e3bae41382df7/5113c297-fa54-4280-beaa-063a7f0fdca3)

**Comment by MauriceReeves-usds** [comment]
Here's the text from the image above:
```
MSH10 10618cab-30ec-42eb-a48c-9c2f8d40e733 repeated twice
MSH 10 76385bf0-1870-4af9-b467-f3f4f8952145 repeated twice
MSH 10 2f8406d-2f0d-433c-bc14-964ccd3863fc repeated twice
MSH 10 a655db61-57de-4f3b-a956-5e2460c873f9 repeated twice
```

**Comment by MauriceReeves-usds** [comment]
I've reached out to SimpleReport @zdeveloper for an answer on this. Waiting to hear back.

@Adrian-Brewster can you reach out to Washington to see if there's any actions they want us to take?

**Comment by sliu1000** [comment]
@Adrian-Brewster Per the user Jennifer.Risler@doh.wa.gov 

Thank you for letting us know.  We would like for duplicate results to be suppressed in the future and it sounds like you have a fix that can be applied, so this ticket may be closed.
