### ISSUE TITLE
MS - Raymond Detention Center File Location and Message Analytics

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#5666]
Email from Carrie.Cannaday@msdh.ms.gov

I need to locate files for Raymond Detention Center. If possible may we have the message count validated and the messages resubmitted. I have listed the date range below.

Raymond Detention Center
•	February 2022 – 159 tests logged in Simple Reports
•	March 2022 -  266 tests logged in Simple Reports 

Please let me know if you have any questions.

Regards,

Carrie W. Cannaday, MPH
Epidemiologist
Carrie.Cannaday@msdh.ms.gov
Mississippi State Department of Health
570 E. Woodrow Wilson| O-420| Jackson, MS| 39215

**Comment by Adrian-Brewster** [comment]
Need additional information. @Adrian-Brewster to review email thread and add context.

**Comment by sliu1000** [comment]
@Adrian-Brewster updated to include the whole email content.  Please let me know if you'd like us to reach out to the customer for more information.

**Comment by sliu1000** [comment]
@Adrian-Brewster 

Any update on this ticket? The user is asking for a status update.

**Comment by sliu1000** [comment]
@Adrian-Brewster User is requesting for an update on this ticket. I advised them that engineering is looking into this and we'll get back to them as soon as possible.

**Comment by sarahnw** [comment]
hmm I may need someone to double check me, but I only see 46 records.

**Comment by sliu1000** [comment]
@sarahnw any update on this? Please let me know if there's anything I can assist with.

**Comment by sarahnw** [comment]
MS is having them resubmit. closing this.
