### ISSUE TITLE
WA - Invalid MSH-3 "ProPhase"

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#5669]
Name: Jenni Risler
Email: jennifer.risler@doh.wa.gov

We received two files today with invalid MSH-3 values that failed to be processed by our system. 

We are not requesting resubmission of these files, however we ask that you correct MSH-3 from ProPhase to CDC PRIME - Atlanta, Georgia (Dekalb)^2.16.840.1.114222.4.1.237821^ISO for future submissions.

 

Filename:

7uycso49@cdcprime_testing_20220602191618_809000___neg

7uycso49@cdcprime_testing_20220527071602_697325___neg

 

MSH segment (actual):

MSH|^~\&|ProPhase|7uycso49^1.3.6.1.4.1.38630.2.1.1.519^ISO|WADOHPHRED^2.16.840.1.113883.3.237.4.2^ISO|dn1fro00^1.3.6.1.4.1.38630.2.1.1.19^ISO|20220602191605-0000||ORU^R01^ORU_R01|20220602134008|P|2.5.1|||NE|NE|USA|UNICODE UTF-8|ENG^English^ISO||PHLabReport-Batch^Mirth^2.16.840.1.114222.4.1.238646^ISO

MSH-10: 20220602134008

MSH|^~\&|ProPhase|7uycso49^1.3.6.1.4.1.38630.2.1.1.519^ISO|WADOHPHRED^2.16.840.1.113883.3.237.4.2^ISO|dn1fro00^1.3.6.1.4.1.38630.2.1.1.19^ISO|20220527||ORU^R01^ORU_R01|20220527023722|P|2.5.1|||NE|NE|USA|UNICODE UTF-8|ENG^English^ISO||PHLabReport-Batch^Mirth^2.16.840.1.114222.4.1.238646^ISO

MSH-10: 20220527023722

 

MSH segment (expected):

MSH|^~\&|CDC PRIME - Atlanta, Georgia (Dekalb)^2.16.840.1.114222.4.1.237821^ISO|7uycso49^1.3.6.1.4.1.38630.2.1.1.519^ISO|WADOHPHRED^2.16.840.1.113883.3.237.4.2^ISO|dn1fro00^1.3.6.1.4.1.38630.2.1.1.19^ISO|20220602191605-0000||ORU^R01^ORU_R01|20220602134008|P|2.5.1|||NE|NE|USA|UNICODE UTF-8|ENG^English^ISO||PHLabReport-Batch^Mirth^2.16.840.1.114222.4.1.238646^ISO

 

MSH|^~\&|CDC PRIME - Atlanta, Georgia (Dekalb)^2.16.840.1.114222.4.1.237821^ISO|7uycso49^1.3.6.1.4.1.38630.2.1.1.519^ISO|WADOHPHRED^2.16.840.1.113883.3.237.4.2^ISO|dn1fro00^1.3.6.1.4.1.38630.2.1.1.19^ISO|20220527||ORU^R01^ORU_R01|20220527023722|P|2.5.1|||NE|NE|USA|UNICODE UTF-8|ENG^English^ISO||PHLabReport-Batch^Mirth^2.16.840.1.114222.4.1.238646^ISO

**Comment by shy2cdc** [comment]
We received more than 100 additional files with only “ProPhase” in MSH-3.  Please pause their feed until a fix can be implemented and reviewed by our team.

**Comment by sarahnw** [comment]
@jbiskie WA does need resubmits for the ones that were errors before. do we know which ones those are? Can they resubmit prior to the fix being implemented?

**Comment by anshulkumar-usds** [comment]
@jbiskie WA wrote back inquiring on the status of 120-ish resubmissions.

**Comment by anshulkumar-usds** [comment]
@sarahnw can you please follow up with WA and find out.

**Comment by sarahnw** [comment]
emailed WA. will. update when I hear back

**Comment by sarahnw** [comment]
Forwarded list to Joel. Jenni's requested:

Please check the following items prior to sending resubmissions:
- Update MSH-7
- No UTC time
- Set MSH-11 to P for production messages
- Correct MSH-3 value as requested above

Lmk when they're resent so we can give Jenni a heads up!

**Comment by sliu1000** [comment]
@Adrian-Brewster 
6/27/2022 @ 7:51 PM
Jennifer Risler sent a request via Reportstream Smartsheet form with Additional resubmission requests:

**Problem Statement**
Require requested resubmission for Prescryptive MSH-5 and MSH-6 value of "CDC PRIME" See also email with subject line RE: Prescryptive dated 5/18, excerpted text below: We would like the files sent prior to the fix to be resubmitted. 

Please check the following items prior to sending resubmissions: • Update MSH-7 • No UTC time • Set MSH-11 to P for production messages • Correct MSH-5 and MSH-6 to the values agreed upon during onboarding.

Message Control ID:

MSH_10_MsgControlId:

``86475ebf-ae36-474b-a197-c20f34ded09c
fb2bf2a4-e5a5-4b96-9d06-edd00461d9bb 
2e3705fa-a693-4818-980a-70ed8ed2d05a
7b294caf-b278-4617-8686-58423d88d0f0
6bde976e-0e85-434f-be6e-2a49d40d74dd
93106df3-12b5-4b42-8b1f-35c8d29282a4
a9f71afc-29e9-48d0-9684-2842a24db3ce
88d07740-ffbe-4c87-a7e6-96852b1a0c4d
e86ffe37-9235-487c-a2d3-334890bc5677
e0ceae91-d668-4937-8310-815ac4c4267e
090a4c46-7ed1-4fd8-907b-45c1ad805b72
6a5e958b-2bd3-4f6e-88b1-7f353fa77b3a
cb1e404b-11f8-435a-9a17-a483855fc2f4
83f74979-ef99-4aa5-8652-7671a11c3633
3a138b05-4864-452d-8b98-806bcdfc95fc
3465b5fe-e481-40ce-95cd-48d25debcf19
96c8dc45-f403-4fa3-a3e0-80c4a22cfeb8
376d3906-7207-4ccc-837e-3825eebafbb4
b5c7f068-c617-42df-b7c5-8201ce657b46
5bb3098d-8c5c-44d8-9dae-131df1750505
d2fb9be4-524f-48b7-96df-1321f79a9a22
63445b52-5d2d-4bc0-b1a8-48a1a6215e2c
2acde598-233e-404a-b89b-aa4c198c53c0
6458b645-6029-4f92-9626-6ecb7735e214
62749ba7-03f4-455d-8b78-3f6735498178
24c5a7b1-beef-432c-b39c-35c8cffc6900
1528e6b0-1ef9-4409-9e4f-11ccbb4f9dd2
 5f853df6-1957-4023-9481-8ed102bf0eae
7368f148-98d9-4797-95a6-f00a3c5bee58
ee3ed0bd-caec-497d-992d-cc7c9b382831
61be9f73-6c9a-4a67-901f-59d726520325
7f0b7708-c705-4067-a3ed-2bdc0f7c4516
5c33efb4-ac0f-4b7e-9167-6abbef3d353d
7a7ffc05-5a5b-4df6-9d8c-ee55d850e143
3e720a05-a489-4386-bdb6-cd83e051fd4f
 9d4a3be3-03ef-40fd-8589-33dc8ba251b0
19e62a9f-704b-48ee-af4c-4ab47efef2b9
dcf6b512-5f62-48b6-90db-00e5a2ee8188
c6add39d-b1ec-49b7-8b89-9c14b2a9a3b0
132b81ef-8c37-4848-b40b-a819c7883d90
7243284e-ce77-4407-90af-188305787ce8
c63d2a57-398f-4682-b08a-cc47398674ff
2134a71a-e7f9-4cba-a638-006274eeec92
c7d90ce5-e046-4db9-af54-d08aeff0d207
0c2a51a4-4c3a-454b-8cb6-f9294d0b0cf1
86a1b701-635e-4948-8e2c-21c62aa143ea
f65c6dd3-ce6d-4263-97c4-47b46f31da9a
```

**Comment by Adrian-Brewster** [comment]
@sliu1000 Are there two separate tickets included here? One refers to ProPhase and the other perscryptive.

**Comment by sliu1000** [comment]
@Adrian-Brewster thank you for catching that. I'll create a separate ticket for perscryptive.

**Comment by Adrian-Brewster** [comment]
@oslynn have the resubmissions been completed for these?

**Comment by BerniXiongA6** [comment]
Updates 8/3/2022: After working with @oslynn to investigate this for Jenni and Julie at WA DOH, looks like ProPhase did not complete resubmissions. I've contacted WA DOH to let them know we'll be asking ProPhase to send the data since the resubmissions timeframe has expired. I'll reach out to ProPhase with this request and cc: @oslynn for visibility. (FYI: New sender contact as of 7/28/2022 is anthony.millan@healthcareintegrations.com.)

**Comment by BerniXiongA6** [comment]
Closing this ticket because WA issues were fixed -- sender (Anthony at Healthcare Integrations for ProPhase) should have been able to re-send the data back through RS and it should go through without further issues. cc: @oslynn

**Comment by oslynn** [comment]
2022-08-29: I checked the organization.yml file to make sure RS is already setup to translate messages for WA-PHD and IT IS READY.  That means it is validated.  If ProPhase resend those message, it will translate to WA-PHD according to what WA-PHD wants.

**Comment by shy2cdc** [comment]
From Jenni:

Joel,

I can confirm that we do regularly receive files from USDS at roughly two hour intervals from 4AM – 9PM PST. Our midday files tend to arrive around 12:45PM.  We regularly receive files at this time except for on 9/7/2022. 

 

Could we get these 3 transmission failures resubmitted?


`cdcprime_testing_20220907071609_520183___neg.hl7`      9/7/2022, 2:16:09 AM                   not received

`cdcprime_testing_20220907191605_561311___neg.hl7`      9/7/2022, 2:16:05 PM                       not received

`cdcprime_testing_20220907193544_283978.hl7 `           9/7/2022, 2:35:44 PM         not received


Thank you,

Jenni
