### ISSUE TITLE
MN - MDH:CDC Prime ELR Errors 06/03/2022

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#5676]
Name:  Srujana Japa
Email: srujana.japa@state.mn.us

MDH has received 41 messages on 06/03/2022 with incorrect values in MSH.5 and MSH.6, would you please be able to correct and re-send them?

Please find the accession IDs in the attachment.

**Comment by shy2cdc** [comment]
@jbiskie the user sent another email - Following-up on the below email. Are you able to fix and re-send these messages? Please let us know.

**Comment by jbiskie** [comment]
@shy2cdc Thanks for the list, will review today.

**Comment by shy2cdc** [comment]
6/13 3:27pm

Confirming receipt of all but one– the only one I didn’t see resent was the following:

 

221240005558^ProPhase Diagnostics^33D2215033^CLIA

**Comment by shy2cdc** [comment]
6/13 3:35pm

Sorry for the double email, but it looks like these are still utilizing incorrect MSH.5, but the MSH.6 was corrected. Can you fix this for all future transmissions please?

 
Error MSH.5 incorrect value

Sent MEDSS-ELR^2.16.840.1.114222.4.1.185.1^ISO

Needed MEDSS-ELR^2.16.840.1.114222.4.3.3.6.2.1^ISO
