### ISSUE TITLE
VT - Facilities List Report - Vermont Contact Changes

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#5677]
Would you be able to update the distribution list for this report?

 

If so, please add AHS.VDHIDDS@vermont.gov and please remove myself (Theresa Dunn) and Veronica Fialkowski – today is my last day with the Health Department, and Veronica moved to a new role in January.

 

Moving forward,  AHS.VDHIDDS@vermont.gov and AHS.VDHELRSupport@vermont.gov will be the best contacts for Vermont. This will ensure the full team is looped in, as they will be working together to support ELR while my position is vacant.

 

Thank you so much for your help,

Theresa

**Comment by Adrian-Brewster** [comment]
Adrian to add to directory.

**Comment by shy2cdc** [comment]
[VT - Facilities List.csv](https://github.com/CDCgov/prime-reportstream/files/8846992/VT.-.Facilities.List.csv)

**Comment by Adrian-Brewster** [comment]
@anshulkumar-usds This is the CLIA report that Ming created.  Do you know where it is saved metabase?

**Comment by anshulkumar-usds** [comment]
@Adrian-Brewster the report is in the SimpleReport instance of metabase. https://prime-simple-report-prod-metabase.azurewebsites.net/

Under reports and dashboards
