### ISSUE TITLE
MA - ELR MIssing FIles

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#5680]
From elr.cdsupport@state.ma.us

Good Afternoon,

We have not yet made a connection with you today.  Please confirm whether or not this is correct, and resend any messages which should have crossed over.

Settings implemented for connection/ resending messages from crossover

![thumbnail_image002.jpg](https://images.zenhubusercontent.com/62828b77597e3bdcbc3834fd/d605e5e6-1287-47cb-9266-313a8fe6a9b5)

Thanks,
Becky 

Becky Reed (Pronouns are  flexible)
Research Analyst 
Division of Surveillance, Analytics and Informatics (DSAI)
Bureau of Infectious Disease and Laboratory Sciences
Massachusetts Department of Public Health
305 South Street
Jamaica Plain, MA 02130
617-366-6239 (Work Cell)
617-983-6813 (Fax)

**Comment by rnz6** [comment]
@Adrian-Brewster 6/8 - Becky Reid sent a follow up email today. Please see below email. 

From: CDSupport, ELR (DPH) <elr.cdsupport@state.ma.us>
Sent: Wednesday, June 8, 2022 12:56 PM
To: Report Stream (CDC) <reportstream@cdc.gov>
Subject: RE: MDPH ELR: Missing Files - PRIME - ticket 5658
 
Good Morning,

I am following up on the below issue. We did not receive any files on 6/3, 6/4, or 6/5. Please let me know if there are any updates on this issue.

Thanks,

Becky

Becky Reed (Pronouns are  flexible)
Research Analyst
Division of Surveillance, Analytics and Informatics (DSAI)
Bureau of Infectious Disease and Laboratory Sciences
Massachusetts Department of Public Health
305 South Street
Jamaica Plain, MA 02130
617-366-6239 (Work Cell)
617-983-6813 (Fax)

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5680?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS

**Comment by Adrian-Brewster** [comment]
@rnz6 Moving forward, please forward the email chain to me at mpz9@cdc.gov.  I am just now seeing this issue. I will flag this for the team

**Comment by brick-green** [comment]
just resent the files for 6/3, 6/4, or 6/5

**Comment by sliu1000** [comment]
@brick-green @Adrian-Brewster 

The user says that they received the files but was missing some data they were expecting to get.  Specifically for positive results from 6/3 from "The Residence at Five Corners (Norton MA).

Please see the email from the user below:
From: CDSupport, ELR (DPH) <elr.cdsupport@state.ma.us> 
Sent: Friday, June 24, 2022 10:44 AM
To: Brewster, Adrian (CDC/DDPHSS/OD/HITSSU) (CTR) <mpz9@cdc.gov>; CDSupport, ELR (DPH) <elr.cdsupport@state.ma.us>; Report Stream (CDC) <reportstream@cdc.gov>
Subject: RE: MDPH ELR: Missing Files - PRIME - ticket 5658 

Hi Adrian,

We were expecting certain cases to be in these files and they did not come through.  Can you tell me the last time The Residence at Five Corners (Norton MA) reported via report stream? Supposedly they had positive results from 6/3 and in the past they reported via report stream.

Thank you,
Kaleigh
--
Kaleigh Carney, MPH
Research Analyst   
Division of Surveillance, Analytics and Informatics 
Bureau of Infectious Disease and Laboratory Sciences
Massachusetts Department of Public Health
305 South Street, Jamaica Plain, MA 02130
Tel:  781-223-7094   Confidential Fax: 617-983-6813
Email: kaleigh.carney@mass.gov
