### ISSUE TITLE
Need a configurable retry mechanism for sending data to receivers

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#5681]
As an administrator, I want to set a retry timeout for sending data, so we can control when a manual retry is needed.

Needed sometime in the 3 months or so.  Possible deadline Oct 1, 2022.

This is an issue reported by @MauriceReeves-usds .  This ticket needs more information to be complete.

**Comment by bishoyayoub** [comment]
Exponential backoff mechanism exists. This ticket is no longer needed.
