### ISSUE TITLE
NJ -Missing ORC-23

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#5686]
Name: Mark Firkser
Email: njelr.admin@doh.nj.gov

Please note the error below with your ELR File: covid-19-82ba6f13-72c9-4942-9f53-d10fbf8887e9-20220606134029.hl7

 

Order: 9d2c5990-377e-43a8-80f9-121d1cdcef77

 

ORC-23 missing

 

Please correct and resubmit.

**Comment by sliu1000** [comment]
Duplicate to 5537
