### ISSUE TITLE
ORC23 Failure Submission

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5688]
**Describe the bug**

- 5/27/2022, 13:15, accession # 8a63e2a7-1f15-4ce5-98ef-d8139b6912c1  (Per Maurice completed the deployment this morning for the fix for the MSH-7 field).

- Error Messages from 5/26/2022, 5:15 pm batch failed due to date only being included in MSH-7

- Timeline for affected messages (from approximately 5/19 -->Forward)
Error Messages from 5/17/2022 
OBR-4 (Universal Service Identifier) – LOINC code missing
OBX-3.2 (Observation Identifier) – value missing
OBX-17.1 (Observation Method) – Identifier missing
Example Accession # 4f2001c5-3586-4f28-81ef-2a7237f84410
Example Accession # 2951063b-27fc-432a-875d-5a55212a3b33

**Impact**
errors are preventing facilities utilizing SimpleReport from fulfilling their requirement to report all COVID-19 test results to public health

**Comment by sliu1000** [comment]
duplicate to 5537

**Comment by Adrian-Brewster** [comment]
@sliu1000 to confirm. Is this issue for VT or NJ? It looks like the labels were shuffled around a bit.

**Comment by Adrian-Brewster** [comment]
@sliu1000 No, 5565 is still being worked on. generally speaking, the engineer working on the ticket with close it when they are complete. No need for the help desk to close tickets currently.

**Comment by sliu1000** [comment]
@Adrian-Brewster It's for Vermont

From: Dunn, Theresa <[Theresa.Dunn@vermont.gov](mailto:Theresa.Dunn@vermont.gov)> 
Sent: Thursday, May 26, 2022 4:43 PM
To: Report Stream (CDC) <[reportstream@cdc.gov](mailto:reportstream@cdc.gov)>; Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR) <[rut5@cdc.gov](mailto:rut5@cdc.gov)>; Kumar, Anshul (CDC/OD/OCS) <[rdz8@cdc.gov](mailto:rdz8@cdc.gov)>; [adrian.brewster@agile6.com](mailto:adrian.brewster@agile6.com)
Cc: Oates, Devin <[Devin.Oates@vermont.gov](mailto:Devin.Oates@vermont.gov)>; AHS - VDH ELR Support <[AHS.VDHELRSupport@vermont.gov](mailto:AHS.VDHELRSupport@vermont.gov)>
Subject: RE: Messages From ReportStream to VT Failing
 
Thanks Maurice, I’ll keep an eye on the 5:15 batch as well and will touch base with what we’re seeing.
 
Assuming the fix is successful, what is the anticipated timeline for re-submitting the affected messages (from approximately 5/19 forward)? 
 
I’m also wondering if you and your team were able to take a look at the third issue we are seeing, where we’re seeing missing LOINC values for iHealth testing? It looks like this issue began on approximately 5/17.
OBR-4 (Universal Service Identifier) – LOINC code missing
OBX-3.2 (Observation Identifier) – value missing
OBX-17.1 (Observation Method) – Identifier missing
Example Accession # 4f2001c5-3586-4f28-81ef-2a7237f84410
Example Accession # 2951063b-27fc-432a-875d-5a55212a3b33
 
Thanks,
Theresa
 
 
 
Theresa Dunn 
Electronic Surveillance Coordinator
she/her/hers
[phone]     802-578-8390
[email]      [theresa.dunn@vermont.gov](mailto:theresa.dunn@vermont.gov)
 
Vermont Department of Health
Division of Health Surveillance
108 Cherry St
Burlington, VT  05402

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5688?planning-poker) with ZenHub @jorg3lopez @jbiskie @MauriceReeves-usds @TomNUSDS @brick-green @greene858 @oslynn

**Comment by jorg3lopez** [comment]
#### Update:
submitted message ids to SR so they can resend them. If the messages fail, then we can revisit this issue again.

**Comment by BerniXiongA6** [comment]
No failures so we can close now
