### ISSUE TITLE
Migrate away from PermissionUtils, towards SessionContext

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#5691]
## Problem statement

Now that we have a `SessionContext` to parse auth and provide permissions to the application, we need to refactor a few key areas that are still using `permissionCheck`. The goal is to migrate off of the old permission parsing utils and rely on the okta token being parsed by the SessionContext as our means of making sense of permissions.

## What you need to know

In the app are comments labeled `PERMISSIONS REFACTOR`; search that and you'll see notes left for this work. The three main notes are:

- App.tsx is handling redirects through `permissionCheck` and they should be determined by the active memberType of the user logging in. By default, the login action sets this to the first org in a user's array, so if I'm in 3 orgs, my first org in the claims list dictates that redirect. We do not currently support non-admins changing active membership/user-type.
- AuthorizedRoute is handling permission parsing with `permissionCheck` and should instead handle it using the memberships provided by SessionContext
- ReportStreamHeder is showing the admin org selector based off of `permissionsCheck`. This should NOT be coupled to our active memberType, but since permissionCheck is likely going away, a simple check to ensure someone's token has PrimeAdmins should do for "hard checking" admin access.

## Acceptance criteria

- [ ] We can refactor out the `PermissionUtils` file without sacrificing functionality.

## To do

- [ ]

**Comment by doug-s-nava** [comment]
@kevinhaube - think we can close this. Can you confirm?

**Comment by kevinhaube** [comment]
Yep! We fully rely on session membership state now 👍🏼
