### ISSUE TITLE
Zip Code Deidentification Bug - Remove +4

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#5694]
There is a bug with the zip code deidentification logic where it includes the +4 for zip codes. No deidentified zip code should include the +4. For example, 17011-1402 should become 17000 and 20589-7352 should become 00000.

**Comment by oslynn** [comment]
Since the last Improve Zip Code PR: https://github.com/CDCgov/prime-reportstream/pull/5690 wasn't merged yet.  Therefore, I will fix it in that PR and I will close this ticket.
