### ISSUE TITLE
Lookup Table API Enhancements: Easier retrieval of latest content

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#5708]
## Problem statement

Below is the summary of backend changes that need to be made, this ticket has been repurposed to handle changes to the frontend to communicate with the new endpoint created as a result of these changes.

------------
Currently in the Lookup Table API, you are required to _explicitly specify_ the version number of the lookup table you want to retrieve. For example,

`GET /api/lookuptables/sender_automation_value_set/2/content`

If all you care about is the _latest version_ of the content, you must first make a call to `GET /api/lookuptables/list`, filter those results for the table you're after (i.e. `sender_automation_value_set`), then feed that version into the above call (i.e. _2_ in the above call). Consequentially, the Valuesets Editor UI must _also_ chain these calls. It would be better if the UI only needed ONE call, i.e. 

`GET /api/lookuptables/sender_automation_value_set/latest/content` or
`GET **/api/lookuptables/sender_automation_value_set/content/latest` or even just
`GET **/api/lookuptables/sender_automation_value_set/content` 

...or whatever solution would avoid route contention issues while adhering reasonably to best practices.

## What you need to know

- [Valueset Editor Backend Architecture](https://cdc-my.sharepoint.com/:w:/r/personal/srz7_cdc_gov/_layouts/15/doc2.aspx?sourcedoc=%7B107af8c4-c9be-47ad-8d6a-acc2817ae24b%7D&action=editnew&wdPreviousSession=88175852-f506-4502-9155-747b9f56bf2e&wdNewAndOpenCt=1652735315621&wdo=4&wdOrigin=wacFileNew&wdTpl=blank&wdLcid=1033&wdPreviousCorrelation=164fe638-ea15-4dca-a1dd-819218e6beaf&cid=2d68a5ae-8cbf-40f5-844a-d11607d174c0)
- Related epic: #3489 
- Related tickets: 
-- #5534 
-- #5535  
-- #5590 

## Acceptance criteria

- [ ] Add the ability to retrieve the latest version of any lookup table by calling ONE endpoint
- [ ] Unit tests as needed

**Comment by JGreenFearless** [comment]
@sethdarragile6 Is this something that requires work from the Pipeline Team?

**Comment by sethdarragile6** [comment]
@JGreenFearless not necessarily. it's backend/API work that traditionally would be done by the pipeline team, but also doable by experience (w/pipeline's eyes/help) @bgantick

**Comment by doug-s-nava** [comment]
think we can close this, based on https://github.com/CDCgov/prime-reportstream/commit/eabd48994b82e8ecd24ceb72762d88a8d2b638d2

**Comment by doug-s-nava** [comment]
or actually let's repurpose this card for frontend work
