### ISSUE TITLE
Send HL7 file to API via Validation Service UI

### ISSUE THREAD

**Issue by HeatherRienks** [CDCgov/prime-reportstream#5710]
## Problem statement

[Write a short description of what you want to achieve with this task]

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- Review response; can we see the response in the UI? (Continuation of #5709)

## To do

- [ ] ...

**Comment by bgantick** [comment]
Closing: combining with #5709
