### ISSUE TITLE
Validation Service: Create validation endpoint

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#5713]
## Problem statement

We need a new API endpoint (called `validate`) for senders to validate a potential incoming CSV or HL7 file, without actually sending the file or storing the file in the database. It should return any and all errors and warnings that a normal submission would in its JSON response- all without logging or otherwise storing _this_ information, either.

## Recommended approach

Start by cloning the `/api/waters` endpoint, then factor out any codepaths that result in a save to the database.

## For possible future iterations:
- add quality filters to the response coming back
- return more detailed information about the file uploaded file (HL7 version, etc)
- store error metadata

## What you need to know
Research work: #5548

## Acceptance criteria

- [ ] Able to submit HL7 or CSV to new `validate` endpoint
- [ ] Endpoint returns warnings and errors (the same as the current endpoint), without saving data to the DB
- [ ] Unit and integration tests as need

**Comment by HeatherRienks** [comment]
@sethdarragile6 & @bgantick spoke with Carlos & Cle on this ticket on 6/29/22.

**Comment by bgantick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/5713?planning-poker) with ZenHub @ahay-agile6 @sethdarragile6 @kevinhaube

**Comment by sethdarragile6** [comment]
### internal fun processRequest(a love story)

this is glorified pseudocode describing (most of) the flow of the `processRequest` method, with the main purpose of identifying places along that codepath that will need to be factored out of our new `/api/validate` endpoint- for the following reasons:

```
  * READS FROM DB (something that won't exist) 
  ** WRITES TO Blob Storage
 *** WRITES TO DB
**** SENDS FILES
```
BEGIN processRequest:
```
- // gathers options + sync/async
- actionHistory.trackActionSenderInfo() // begins building ActionHistory object
- validateRequest() // begins building ActionLogger, which has errors and warnings
  - // if error thrown, calls actionHistory.trackLogs() which just adds error(s) to ActionHistory.actionLogs
- validateAndMoveToProcessing() // 2 different implementations based on if sender is CovidSender or not
  - if CovidSender:
    - workflowEngine.parseCovidReport() // calls either csvSerializer or hl7Serializer
	- workflowEngine.recordReceivedReport()
	  - ** BlobAccess.uploadBody() // uploads contents of file to Azure blob storage
	  - trackExternalInputReport() // records history info about report
	- actionHistory.trackLogs() // adds to ActionHistory
	- if async:
	  - processAsync() // not sure if this path is relevant. but if so...
	    - *** workflowEngine.insertProcessTask() // write report and its actionHistory to the database
	- else
	  - workflowEngine.routeReport()
	    - translator.filterAndTranslateByReceiver() // Translate and filter by the list of receiver in metadata
		- actionHistory.trackFilteredReport()
		- *** **** this.db.transact { txn ->
            preparedReports.forEach { (report, receiver) ->
                sendToDestination(
                    report,
                    receiver,
                    options,
                    actionHistory,
                    txn
                )
            }
        } // everything is written to the database and sent
  - else (ELRReceiver)
	- workflowEngine.recordReceivedReport()
	  - ** BlobAccess.uploadBody() // uploads contents of file to Azure blob storage
	- *** workflowEngine.insertProcessTask()
	- **** workflowEngine.queue.sendMessage()
- actionHistory.trackActionResult() // adds HTTP status and results to an actionHistory
- *** workflowEngine.recordAction() // writes the actionHistory to the database (w/ an actionId)
- * findDetailedSubmissionHistory() // pulls submission history from the database
- * request.createResponseBuilder() // builds API response based on pulled submission history
- **** actionHistory.queueMessages(workflowEngine) // send all the things!

END ProcessRequest
```

**Comment by sethdarragile6** [comment]
after a quick hotfix, this was successfully verified in Staging!
