### ISSUE TITLE
Resubmission Needed for File to LA Secondary Feed

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#5724]
A report needs resubmitted to LA's secondary feed:

```
159ed7c1-71b4-49e2-9a5a-de429a248d19	2022-05-26T21:28:11.629679-04:00
```

The report does not need any corrections. It just needs resent.

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5724?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS
