### ISSUE TITLE
Add ~, Hl7 Field repetition separator, handling to Hl7Serializer. replaceValueAwithBUsingTerser method.

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#5734]
Currently, the replaceValueAwithBUsingTerser() method can't handle the '~', Hl7 Field repetition separator.  Therefore, it needs to be able to handle the separator instead of passing it to Terser.  Terser will replace it with /R/ and it is not correct.

Currently, ticket 5631 needs the feature to be able to handle the OBX-17 issue.

**Comment by BerniXiongA6** [comment]
@brick-green to review PR for @oslynn
