### ISSUE TITLE
Create technical documentation for feature/fields for organization.yml setting.

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#5736]
Create technical documentation for feature/fields for the organization.yml setting.

**Comment by oslynn** [comment]
@jorg3lopez has started this process in docs/playbooks/how_to_use_translation_configuration_features.md.  Perhaps, I need to incorporate into the file.

**Comment by brandonnava** [comment]
@oslynn still need this or close?

**Comment by brick-green** [comment]
@brandonnava We still need this
