### ISSUE TITLE
Compare initial HL7 to generated HL7

### ISSUE THREAD

**Issue by clediggins-usds** [CDCgov/prime-reportstream#5743]
This will need to be fleshed out. Are we automatically comparing ingested HL7 to generated HL7 to verify lossless translation? Is this a manual process?

See Phase 1: https://lucid.app/lucidchart/84402da0-abb1-4a7a-99c0-0832cbad7197/edit?beaconFlowId=069E09287C5F02FB&invitationId=inv_e2d8fb92-d650-4427-85c3-06325b8845f1&page=b1h7R-jYfGAT#

**Comment by carlosfelix2** [comment]
Replaced by #5838
