### ISSUE TITLE
CA - Difficulty uploading

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#5761]
Name: Michelle Neuroth
Email: michelle.r.neuroth.mil@mail.mil

Using the same format as previously, report stream is not taking my results tonight, I've checked the requested information and it is there but report stream is saying it is not. Do I need to update my format, did something change?

LCDR Michelle Neuroth, MLS(ASCP)CM
Head, Laboratory Department
Navy Medicine Readiness and Training Command Lemoore
Lemoore, CA 93246
Office: (559) 998-4436
DSN: 998-4436
Fax: (559) 998-4972
michelle.r.neuroth.mil@mail.mil

**Comment by MauriceReeves-usds** [comment]
Notified LCDR Neuroth that we have completed a deployment and they should be able to submit again.
