### ISSUE TITLE
Remove FTPS Transport

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#5768]
A while ago, we added the FTPS transport to ReportStream in order to provide an alternate connector to New Mexico, but we're not using it, so I'm proposing we remove it.

Acceptance criteria:
- Remove the FTPS transport type
- Remove the Docker image for FTPS

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5768?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS

**Comment by MauriceReeves-usds** [comment]
Completed and moved to internal review. PR is ready for review.
