### ISSUE TITLE
Pilot using Apache MINA as a Replacement for SSHJ

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#5770]
Apache has a library for SSH that we should pilot as a replacement for SSHJ. The library is available here: https://github.com/apache/mina-sshd

**Comment by MauriceReeves-usds** [comment]
Resurfacing this now that SSHJ has released another update. I'd like to pull this into a sprint soon so we can build a test harness that lets us check out how easy it would be to use Mina instead of SSHJ and if it's reliable. 

Acceptance criteria:
* Mina is able to connect to our different SFTP clients:
    - PuTTY Key
    - SSH Key
* We are able to wrap an interface around Mina and SSHJ such that no matter which one we use for a client the switch could be made at runtime and is transparent to support staff
* Mina has a LTS version and Apache isn't planning on sunsetting it any time soon

**Comment by brandonnava** [comment]
@MauriceReeves-usds still want to do this? How does it help our workflow? Worth the effort?

**Comment by brandonnava** [comment]
@oslynn @brick-green Do we still want to do this or not needed?

**Comment by brick-green** [comment]
yes, I think so. @oslynn what do you think?

**Comment by oslynn** [comment]
@brick-green @brandonnava , I think, we can hold off for now.  Our SSHJ is still secured and good and tested with all of our STLTs. We only need to update our SSHJ to the latest version.  Adding new MINA lib will add more code to our RS and require **extensive** testing and verification to ensure all STLTs are still functioning and comparable with RS.  We can wait until we have more bandwidth to incorporate MINA into our RS.
