### ISSUE TITLE
IL - BioVision Diagnostics - CSV Uploader - Error: File Not Accepted

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5773]
**Describe the bug**
Report Stream Csv Uploader Not able to upload

**Impact**
Unable to submit data

**Expected behavior**
Should upload with no errors

**Screenshots**
Attached
**Logs**

SV**Desktop (please complete the following information):**
- OS: Windows
- Browser: Microsoft edge
- Version : 102.0.1245.33

![Report stream errors FL.jpeg](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/fff7d0cd-00b5-428f-975a-c15b4370391d)

**Comment by Adrian-Brewster** [comment]
Removed PII/PHI from ticket.  @sliu1000 Please do not include PII/PHI in these tickets and let me know asap if a sender includes any in an email or ticket.

**Comment by sliu1000** [comment]
@Adrian-Brewster Should I redact the PII prior to attaching in Zenhub?
