### ISSUE TITLE
CO - Warrior Diagnostics - CSV Uploader - BLANK Value Error

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5774]
**Describe the bug**
ReportStream CSV Uploader Error when file is submitted. 

**Impact**
Org unable to submit data

From: Katie R <katie@warrior-dx.com>
Date: Fri, Jun 10, 2022 at 9:37 AM
Subject: 6/9/22 ReportStream File Submission
To: Hood, Rickey (CDC/DDPHSS/OD/HITSSU) (CTR) <rwe6@cdc.gov>, Megan Doss <megan@warrior-dx.com>

Good morning, Rickey,

Both Megan and I have attempted numerous times to submit our report this morning but continue to get the same error message:

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/8ffd7de9-bfd4-477b-a79c-82396b9c21f0)

The errors are:   
-Blank value for element date_result_released (date_result_released) 
-Blank value for element specimen_collection_date (specimen_collection_date_time)  
-Blank value for element testing_lab_specimen_received_date (testing_lab_specimen_received_datetime)

I am unsure why this error is populating because all of these necessary columns are filled with dates. So I tried the "yyyymmdd" format and tried to resubmit and still receive the same errors. 

Could you please help us with this?

Thank you,
Katie

**Comment by MauriceReeves-usds** [comment]
Emailed Warrior DX and let them know about the deployment. Asked them to inform us if there are any other issues.
