### ISSUE TITLE
AZ - New Users

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#5776]
**Is your feature request related to a problem? Please describe.**
Name: Christina Pickering & Janet White

Job title: Health Reporting Specialist
Organization: Premier Lab Solutions
Email address: reporting@premierlabsolutions.com
Phone number: 602-455-1595

Organization that referred me to ReportStream: Websites Department of Health
Current reporting method(s): CSV generated file via state provided spreadsheet / template.

**Describe the solution you'd like**
Would like users to be added

**Comment by sliu1000** [comment]
@Adrian-Brewster Can we close this ticket. This ticket should not have been created.  The user wanted to create a reportstream account and we are waiting for them to provide more information.

**Comment by Adrian-Brewster** [comment]
No problem @sliu1000 I can close this out.  Thanks!
