### ISSUE TITLE
Deploy Terraform from GitHub Actions

### ISSUE THREAD

**Issue by ronaldheft-usds** [CDCgov/prime-reportstream#578]
Configure a a GitHub action that:

- [ ] Allows deployment of our Terraform state from GitHub
- [ ] Can deploy to any non-developer environment: `test`, `staging`, and `prod`
- [ ] Requires approval of the `terraform plan` before deployment
  - [ ] Terraform plan is stored securely, so only approved developers can view the plan
- [ ] Does not persist Terraform logs in any form that is viewable to the public, i.e. requires an approved developer to view the logs

**Comment by MauriceReeves-usds** [comment]
Removed Chris from ticket.
