### ISSUE TITLE
CA - Errors while uploading the .csv file to Reportstream

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#5780]
Name: Deepak Hingorani
Email: admin@trdl.net

Can you please look at the Error I am getting when trying to upload the .csv file to reportstream. All the values are in tact but the message I get is the values are blank and so the file does not get uploaded. Please see attached Error message.

Thank You,

 

         Deepak Hingorani

         Top Rank Diagnostic Lab

         1400 Reynolds Ave Suite 202

         Irvine CA 92614

         Phn: (949) 966-0432

         https://www.trdl.net/

**Comment by MauriceReeves-usds** [comment]
Notified Deepak of the deployment and that they should be able to start sending again.
