### ISSUE TITLE
WA - Lab reports likely not for WA

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#5784]
6/10/22 4:28pm
Name: Maggie Dorr
Email: maggie.dorr@doh.wa.gov

Good Afternoon,

 

We received two reports which I believe are not intended for WA.

 

Issue: Patient address = Singapore; Provider = CA; State = WA

Message Date/Time: 6/10/2022 7:16:12 PM

Message Control ID: bb70c1ed-1995-45a8-803c-0ef1fca8dbca

Accession Number: bb70c1ed-1995-45a8-803c-0ef1fca8dbca

MSH ID (For WA Records): 336448249

 

Issue: Patient address = Singapore; Provider = CA; State = WA

Message Date/Time: 6/10/2022 7:16:12 PM

Message Control ID: 5d6126ea-5e6a-4f0d-abdc-9982c4193de1

Accession Number: 5d6126ea-5e6a-4f0d-abdc-9982c4193de1

MSH ID (For WA Records): 336440114

 

Please let me know if you believe they are indeed meant for us.

**Comment by shy2cdc** [comment]
Name: Tesha LeSure
Email: Tesha.LeSure@doh.wa.gov

During our regular quality checks we found a file from US Digital that we believe is meant for another health jurisdiction. Unfortunately, DOH does not have an easy way to send data to these groups.

The file is as follows…

 

MSH ID – 336366772
MSG Control ID - ae564ca3-e03d-486a-84b7-a369dee93e69
Message Filler Order Number - ae564ca3-e03d-486a-84b7-a369dee93e69
Reason  - Patient Address has state listed as WA but the zip code indicates the patient address is in HI. The ordering provider is in CA.

 

MSH ID – 336379197
MSG Control ID - f2814834-77a4-42c2-8f72-518b686f5576
Message Filler Order Number - f2814834-77a4-42c2-8f72-518b686f5576
Reason  - Patient Address has state listed as WA but the zip code indicates the patient address is in HI. The ordering provider is in CA.

 

We would appreciate you double checking this file and letting us know whether this report is indeed for WA. If not, please send it to the corresponding state’s department of health or appropriate health jurisdiction at your earliest convenience. If you need additional information to help you locate this record, please let me know.

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5784?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS

**Comment by shy2cdc** [comment]
@brick-green Here is the email they sent on 6/10 4:28pm.

![image.png](https://images.zenhubusercontent.com/62827d1e0129e15b5c366b1a/15ada8cc-f6eb-4212-8d53-23f53bf682d5)

**Comment by Adrian-Brewster** [comment]
Additional training required with WADOH.  They ought to reach out directly to senders to confirm the correct address.  Will discuss on our next call with them.
