### ISSUE TITLE
CA - Result Submission API Returning Error

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#5785]
Name:  Wassauf Khalid - SDI Labs
Email: wkhalid@sdilabsinc.com
6/10/22 7:41pm

It is to notify that we are getting errors while submitting results through the API flow. The error says we are sending the fields blank but on our side everything looks fine. Please check the issue and let us know if there is any correction needed on our side or it is because of some ReportStream updates.

**Comment by MauriceReeves-usds** [comment]
Notified Wassauf that they are able to start resubmitting again.
