### ISSUE TITLE
Validate report counts for Healthcare Integrations

### ISSUE THREAD

**Issue by jbiskie** [CDCgov/prime-reportstream#5791]
## Problem statement

Healthcare Integrations asked us to validate that their counts line up with what's been sent to states so far. There have been some resends and some early on where they had MSH-11 set to "T", so we need to look at counts that were _sent_ instead of counts received.

## What you need to know

Message from Healthcare Integrations:

> Good afternoon,
> 
> Attached are counts for each ReportStream state, for 5/26 through today as of a few minutes ago.
> 
> Please let me know if these are close to matching yours. On my end, data pruning had occurred on some of the state channels (prunes after a certain amount of time where I cannot access messages, but ProPhase can still access data in Orchard). But the numbers should still be accurate.
> 
> Thank you,
> Danielle Smalley
> 
> From 5/26 PM backlog sent to 6/10 ~12pm Central:
> · Alabama - 43
> · Alaska - 14
> · Arizona - 95
> · California - 9483
> · Colorado - 137
> · Delaware - 41
> · Florida - 1248
> · Guam - 1
> · Idaho - 24
> · Illinois - 349
> · Iowa - 33
> · Louisiana - 46
> · Maryland – 119: from 5/27 forward (reporting directly to MD prior)
> · Massachusetts – reporting directly to state, switching to ReportStream soon
> · Minnesota - 62
> · Mississippi - 21
> · Montana - 23
> · Nevada - 72
> · New Hampshire - 75
> · New Jersey - reporting directly to state, switching to ReportStream soon
> · New Mexico - 57
> · North Dakota - 6
> · Ohio - 166
> · Oregon - 79
> · Pennsylvania - 1871
> · Tennessee - 143
> · Texas - 599
> · Vermont - 58
> · Washington - 254
> · Wyoming - 11

## Acceptance criteria

- [ ] Counts confirmed and feedback sent to Healthcare Integrations

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5791?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS

**Comment by brick-green** [comment]
@jbiskie Could this be a good first issue for @GilmoreA6 to take on?

**Comment by BerniXiongA6** [comment]
@sarahnw will look into before decision to close this cc: @GilmoreA6
