### ISSUE TITLE
Add TestKit Name ID and Equipment UID to simple report schema

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#5798]
## Problem statement

Some test types cannot be uniquely identified in the LIVD table by the fields simple report is currently sending(model and test performed code). To uniquely identify the test types simple report needs to send two additional fields: TestKit Name ID and Equipment UID.

## Acceptance criteria

- [ ] every test can be uniquely identified with the data provided by simple report. Check alinity m model specifically

## To do

- [ ] add field to simple report schema that maps to equipment_model_id in covid-19
- [ ] add field to simple report schema that maps to test_kit_name_id in covid-19

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5798?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS
