### ISSUE TITLE
Make edits to the API Programmer's Guide content

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#5809]
## Problem statement

As a ReportStream user (API sender), I want self-guided instructions to learn how to work with ReportStream, and to learn how reporting data via the API works.

As the ReportStream team, we need a single, easy to update location for technical documentation. Current documentation is [shared in a PDF](https://reportstream.cdc.gov/resources/programmers-guide), and has lived in various documents in Sharepoint over time. Having a single, public-facing place for this documentation will be easier to keep up-to-date and share with users. 

## What you need to know

In scope edits:
- Remove unnecessary or duplicative content 
- Redirect the reader to other content that exists on the RS website as needed
- Content is updated to reflect current project status

Etc:
- The current API Programmer's Guide contains some duplicate information (e.g. our onboarding processes) that might not need to be included in the guide and could simply link up to parts of RS website instead
- The current API Programmer's Guide still reads fairly technical even for API users and could be further revised in plain language
- The current content in the API Programmer's Guide could be organized more intuitively as a "how to" resource for users 
- The current guide is a PDF and a bit hard to keep up to date (as well as to distribute up to date versions)
- The outcome from this revamp will be published as pages on the website (#5814)

## Acceptance criteria

- [x] Findings about immediate action or questions for future action from working session and research in working doc 
- [x] Content is written/edited according to working sessions findings and federal plain language guidelines
- [x] Content adheres to [ReportStream content style guide](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Content%20Style%20Guide/ReportStream%20content%20style%20guide.docx?d=webd8f377528c4175b0acb0fbfd6c5866&csf=1&web=1&e=ObGSuA)
- [x] Doc has sections broken down to represent IA/how it will flow on the website
- [x] Bonus/Stretch goal: Flag any of the existing images/diagrams that need updating

## To do

- [x] Apply edits from research and working session

**Comment by BerniXiongA6** [comment]
Per our Design Sync today, we agreed it might be a good idea to create an epic for "Programmer's Guide" since it's ongoing and has taken a life of its own. This is the "content" ticket we can prioritize in upcoming sprint for the Programmer's Guide epic once it's created. cc: @RakshindaAslam

**Comment by HeatherRienks** [comment]
Please note #5814

**Comment by HeatherRienks** [comment]
Per Backlog refinement mtg, we will need to create a separate ticket to actually implement this.

**Comment by HeatherRienks** [comment]
Per sync on 11/30/22, we will prioritize this!
Will create new tickets as part of this epic for next steps - possibly add Error Codes as first section to update on site?

**Comment by audreykwr** [comment]
For reference:

1. [Edit copy with full suggestions/comment threads from working sessions](https://docs.google.com/document/d/1S4SlRp5nznuymnCr1nOwhQYDKYt2OqTX/edit#)
2. [Clean copy with edits applied and only design notes/misc in comments](https://docs.google.com/document/d/1S4SlRp5nznuymnCr1nOwhQYDKYt2OqTX/edit#)
3. [Mural working space](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1672412662691/888f40d9e714837654e616612dfc9761bf191576?sender=uc55a7af3b66977fba12f5528)

@chris-kuryak closing this
