### ISSUE TITLE
Revamp content and design for ReportStream About page

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#5815]
## Problem statement

User: As a prospective or existing user, when I visit the ReportStream website I want to be able to learn about ReportStream so that I can determine why it should matter to my job.

## What you need to know

We can adapt some of previously revised (but not yet published) content work for this upcoming redesign so we don't have to reinvent the wheel.

- Here's the [Content Design folder](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Website%20Copy%20Writing?csf=1&web=1&e=8d3yPq) that contains previously revised web copy prior to this current June 2022 redesign. 

- [Here's the IA mural board](https://app.mural.co/invitation/mural/primedatainput6410/1638994814548?sender=u3e174ac555fe8a2ccb8c7497&key=e1caad3b-ebae-429c-80eb-e7873446668d) for reference.

- [Here's the ReportStream Content Style Guide](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Content%20Style%20Guide?csf=1&web=1&e=GuyPFD) we adhere to for public-facing content

## Acceptance criteria

Content:
- adheres to ReportStream Content Style Guide
- follows federal plain language guidelines

Design:
- follows USWDS guidelines
- if diagrams/graphics are needed where indicated by Content, include them on the relevant page/section
- if template is not built, design needs to create it

User voices: Sender is an API user (phase out CSV uploader content), Receiver represents a public health dept (STLTs)

Review/QA:
- Content shares work with Exp. Product and Design team to review before publishing
- Design shares work with Exp. Product and Design team to review before publishing (staging for review? how does this work / let's discuss)

[Need more info - this page should be worked on last since it's dependent on the rest of the website content]

**Comment by BerniXiongA6** [comment]
Note: The "About" page might just be a section within the future "Product" page -- however, if we do decide to keep "About" as its own static page, then we can keep this ticket open. Will flesh out details once "Website Updates MVP" is done.

**Comment by drew-usds** [comment]
We are [supposed to include an about page of some sort](https://digital.gov/resources/required-web-content-and-links/#about-page), so we need to keep it around in some fashion.

Some options for easy moves we could make here:

1. Keep the existing page at `/about`. Link to it in the footer.
1. Keep the existing about page, move it into the new `/product` sidebar. Keep the path at `/about` or redirect from `/about`
2. Move the existing `/about` content to the bottom of the `/product` page content. Redirect `/about` to this new path

**Comment by BerniXiongA6** [comment]
Updates 7/29/2022: Per our convo today @a-chappelear -- the About page can probably keep the same content for now and then have it linked up in the side-nav on the Product page. Ideal future state for content and design would be to revamp the "one-pager" that's linked up on the About page since it's fairly outdated.

**Comment by a-chappelear** [comment]
This has also been added to the /product sub-nav (as it gets pretty lost in the footer.) Possible adjustments later - update or review the 1-pager that is attached to the page. Get feedback on the language used here from stakeholders during the review/research phase. Closed!
