### ISSUE TITLE
Revamp content ReportStream Product section

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#5816]
## Problem statement

User: As a prospective or existing user, when I visit the ReportStream website I want to be able to learn about how ReportStream works from a product perspective so that I can determine how it impacts my role.

## What you need to know

We can adapt some of previously revised (but not yet published) content work for this upcoming redesign so we don't have to reinvent the wheel.

- Here's the [Content Outline for Product](https://cdc.sharepoint.com/:w:/t/USDSatCDC/EbdI-wzIA6FJlSSARJ4pct8BfeNkyIsvvzWdYNmQq7q6bg?e=76uroU) that contains revised web copy prior for the July 2022 redesign. 

- [Here's the ReportStream Content Style Guide](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Content%20Style%20Guide?csf=1&web=1&e=GuyPFD) we adhere to for public-facing content

## Acceptance criteria

User voices: 
- [ ] Sender is an API user (phase out CSV uploader content)
- [ ] Receiver represents a public health dept/STLTs

Content:
- [ ] Adheres to ReportStream Content Style Guide
- [ ] Follows federal plain language guidelines
- [ ] Includes helpful product info that can be used by:​ Existing Users​, Prospective Users​, STLTs/PHDs​, Orgs and testing facilities​ 
- [ ] Focuses on primary goal of page:
- [ ] Prospective users: Some people need more data and proof about a product before deciding to sign up for it. Details about the what/why/how/who of ReportStream will reduce the fear of risk/increase confidence in signing up.​ Learn more about “sending” test results for data reporting and how to become a sender-type user​. Learn more about “receiving” test results for data reporting and how to become a receiver-type user​
- [ ] Existing users: ​Find info that they can use to communicate more effectively to peers about RS or can refresh what they know about the product and how it can serve them
​ 

Review/QA:
- [ ] Content shares work with Exp. Product, Design team, and O&O team to review before publishing

*An additional ticket will need to be created to publish/implement this (turn this content outline and design work into actual static pages).

**Comment by BerniXiongA6** [comment]
Updates 7/22/2022: Work in progress in the [Content Outline slide deck](https://cdc.sharepoint.com/:p:/t/USDSatCDC/EaOHz4eeu09AvziQLHnAP9YBCRUZavk1jKSSft0iG3EDPQ?e=RjmCYy) under July 2022 subsection.

**Comment by BerniXiongA6** [comment]
Updates 7/27: Finishing up [content updates for Product section ](https://cdc.sharepoint.com/:w:/t/USDSatCDC/EdW3YQotiptLsh7bKEAbbbQBe4i8qINW20YcHogOa3J7vA?e=Rdrj2b)hopefully today

**Comment by BerniXiongA6** [comment]
Updates 7/28: Done with [Product section content updates](https://cdc.sharepoint.com/:w:/t/USDSatCDC/EdW3YQotiptLsh7bKEAbbbQBe4i8qINW20YcHogOa3J7vA?e=Rdrj2b)!

**Comment by a-chappelear** [comment]
All content in! Assistance needed from Eng to add "about" to the subnav on the Product section.
