### ISSUE TITLE
Revamp content and design for ReportStream Resources page

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#5817]
## Problem statement

User: As a prospective or existing user, when I visit the ReportStream website I want to learn what resources and tools I have that can help me become a better user of ReportStream.

## What you need to know

We can adapt some of previously revised (but not yet published) content work for this upcoming redesign so we don't have to reinvent the wheel.

- Here's the [Content for Resources Version B - Overview page](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B7AF28529-87F8-4A1E-B088-E4339FC635FD%7D&file=Content%20Revisions%20for%20-%20Resources%20-%20Overview%20Page.docx&action=default&mobileredirect=true) that can be adapted for July 2022 redesign.

-  Here's the [ReportStream Content Style Guide](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Content%20Style%20Guide?csf=1&web=1&e=GuyPFD) we adhere to for public-facing content

- Here the [Figma with designs](https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=3486%3A24075)

## Acceptance criteria

Content:
- [ ] adheres to ReportStream Content Style Guide
- [ ] follows federal plain language guidelines
- [ ] includes helpful product info that can be used by:​ Existing Users​, Prospective Users​, STLTs/PHDs​, Orgs and testing facilities​ 
- [ ] focuses on primary goal of page:
- [ ] Prospective users: Might be a bit too much info for prospects, but those who need a lot of data to make a decision to use RS can look through this section to find answers​
- [ ] Existing users: RS guides, tools, and updates help existing users with a potential issue, answer a question they have, or help them adapt what we’ve created for them to do their job better
​ 
Design:
- [ ] follows USWDS guidelines
- [ ] if diagrams/graphics are needed where indicated by Content, include them on the relevant page/section
- [ ] if template is not built, design needs to create it

User voices: 
- [ ] Sender is an API user (phase out CSV uploader content)
- [ ] Receiver represents a public health dept/STLTs

Review/QA:
- [ ] Content shares work with Exp. Product, Design team, and O&O team to review before publishing
- [ ] Design shares work with Exp. Product and Design team to review before publishing (staging for review? how does this work / let's discuss)

*An additional ticket will need to be created to publish/implement this (turn this content outline and design work into actual static pages).

**Comment by BerniXiongA6** [comment]
Updates 7/27: Should be able to start working on these today and hope to finish content updates by Friday 7/29 (content outline to come)

**Comment by BerniXiongA6** [comment]
Updates 7/29/2022: Resources page content is revised - [see PPT slide # 6](https://cdc.sharepoint.com/:p:/t/USDSatCDC/EaOHz4eeu09AvziQLHnAP9YBCRUZavk1jKSSft0iG3EDPQ?e=KkAzCz) @a-chappelear cc: @RakshindaAslam @HeatherRienks

**Comment by a-chappelear** [comment]
Content updates are in, but assistance from eng is needed to reorder the "cards" and group them as [originally designed in the Figma file](https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=3486%3A24075)
