### ISSUE TITLE
Revamp content and design for ReportStream Home page

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#5821]
## Problem statement

As a prospective or existing user, when I land on the ReportStream home page I want to quickly understand what it is and whether it's relevant to me so that I can continue to read on and learn more about the product.

As ReportStream team, we want prospective and existing users to land on the home page and for our content to hook them into reading more information that will help them decide to sign up, contact us, or learn more about our product.

## What you need to know

We can adapt some of previously revised (but not yet published) content work for this upcoming redesign so we don't have to reinvent the wheel.

- Here's the [Content Design folder](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Website%20Copy%20Writing?csf=1&web=1&e=8d3yPq) that contains previously revised web copy prior to this current June 2022 redesign. 

- [Here's the ReportStream Content Style Guide](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Content%20Style%20Guide?csf=1&web=1&e=GuyPFD) we adhere to for public-facing content

- Here's the [Figma with designs (in progress)](https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=3332%3A22842)

## Acceptance criteria

Content: 
- adheres to ReportStream Content Style Guide
- follows federal plain language guidelines

Design: 
- follows USWDS guidelines
- if diagrams/graphics are needed where indicated by Content, include them on the relevant page/section
- if template is not built, design needs to create it

User voices: Sender is an API user (phase out CSV uploader content), Receiver represents a public health dept (STLTs)

Review/QA:
- Content shares work with Exp. Product and Design team to review before publishing
- Design shares work with Exp. Product and Design team to review before publishing (staging for review? how does this work / let's discuss)

**Comment by BerniXiongA6** [comment]
Updates 7/27: Not bringing into this sprint yet, will edit all other sections first and if time I can make content revisions for Home page after. Otherwise, design team can remix what's being used for all other sections and incorporate as needed using [previously written content from slidedeck](https://cdc.sharepoint.com/:p:/t/USDSatCDC/EaOHz4eeu09AvziQLHnAP9YBCRUZavk1jKSSft0iG3EDPQ?e=XZ2F2p).

**Comment by a-chappelear** [comment]
I am closing this and linking it to a ticket created for iterations based on feedback for the homepage from O&O](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6687).
