### ISSUE TITLE
Update Error Messages - HAPI Parser Msgs

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#5822]
## Problem statement

As a user, I want to see the error message describe clearly what is expected in the data fields identified below, so that I can correct the data error and resend data in a format that will be accepted by the ReportStream API.

This is not a message that is generated by RS code, but the HAPI parser.  To change this , it needs to be intercepted and updated for the UI display.

1. Result Status in field OBR-25 
2. Valid CLIA in CLIA fields

## What you need to know

https://cdc.sharepoint.com/teams/USDSatCDC/_layouts/15/doc.aspx?sourcedoc={6327b3dc-2ace-4757-aa62-ab8dcfffb535}&action=edit

CLIA # could be in a few different fields. It can be in MSH4, but CLIAs can be used in other places.  The data can specify any type of system for IDs, not just CLIA.  If you look at the example of Avante at Ormond Beach^10D0876999^CLIA , note the third component that says CLIA.  This indicates the ID provided in the second component is a CLIA ID.  Now look at this other example: COCAA^1.2.3.4.5^ISO .  Here the ID is an OID.  The third component tells you the ID system that is used on the second component.  So, you cannot assume you will always get a CLIA.

## Acceptance criteria

1. Error/Warning Message for Result Status format issues is displayed as - "Value" input "for field OBR-25 is invalid. Please send "F' or "C" for Final or Corrected."

2. Error/Warning Message for empty or invalid CLIA field is displayed as - "The sending facility’s CLIA is required to be populated in the following format: |[Sending facility name]^[Facility CLIA number]^CLIA|. Please ONLY send CLIAs rather than facility OIDs."
cfelix -- Needs to be defined with O&O team

## To Do

- The msg may get changed in the library and break the interception.

**Comment by HeatherRienks** [comment]
@kevinhaube - per our convo, this might be a candidate to be closed (and grouped with external VS work, along with 6667).

**Comment by kevinhaube** [comment]
Yep! We'll be handling this in our API Error Codes project :) HAPI is one of our noted libraries to begin implementing codes with first to translate the error to something more readable on the front-end.
