### ISSUE TITLE
All PMGs Submissions to us are returning 400 errors

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5830]
Jim Duff noticed on 6/15/2022 that all of the PMGs submissions to us are returning 400 errors to them.

Here's a look at all the submissions to ReportStream over the last 24 hours.  Note the 599 PMG failures.  I have not had time to see how long this has been going on:

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/2a4da534-5aa1-45ce-b733-098cec421006)

Any idea what could be causing the errors?

You can find the errors by looking in the action_log table, or by querying the submissions API.

**Comment by jbiskie** [comment]
Deployment on May 19 broke the ISO 8601 date parsing. PR #5857 will address the issue.

**Comment by sarahnw** [comment]
I believe this has been resolved now. Closing.
