### ISSUE TITLE
CA - JRS - CSV Uploader - Error: File not Accepted

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5835]
**Describe the bug**
When submitting CSV Uploader on Friday (6/10/2022), user received an error message:

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/573e741d-4173-4a9a-8b76-dbf6307384d3)

**Impact**
Unable to submit test results

User Email Below:
From: Cenllase Estrada <cenllase.estrada@pcl-inc.com> 
Sent: Wednesday, June 15, 2022 6:38 PM
To: Report Stream (CDC) <reportstream@cdc.gov>
Cc: PCL Inc. <info@pcl-inc.com>
Subject: ReportStream Submitting Issues 

Good afternoon,

I hope this email finds everyone well. I have been successfully submitting logs for both PCL and JRS Laboratory since the end of March of this year. Last Friday I found I was being given an error message for log submissions. The error messages say there are blank elements, however, they have been properly filled out in the file I am attempting to submit. I have attached the excel document I attempted to submit along with the error message, the patient data has been removed from the document. I appreciate your help with this issue. 

Thank you.

Best regards,
Cenllase Estrada
Reporting Coordinator
Precision Clinical Laboratories Inc.
e. cenllase.estrada@pcl-inc.com

**Comment by sarahnw** [comment]
This was the CSV issue. I responded to them it's been fixed and to let us know if still occurring.
