### ISSUE TITLE
Create Clonable Onboarding Issue

### ISSUE THREAD

**Issue by PatriciaPerozoUSDS** [CDCgov/prime-reportstream#5842]
As a new developer onboarding to Reportstream, there is a clear checklist of what needs to be done to set up the development environment, use our tools, and learn about the project. 

**Description/Use Case**
This issue will be cloned and assigned to all onboarding team members. It will help them get accustomed to our processes at the same time as they set up their dev environment.
**Risks/Impacts/Considerations**
None

**Dev Notes:**
None

**Acceptance Criteria**
Update #4472 with updated information that can guide a new team member to onboard to the pipeline team. It includes an estimate to help set expectations for the new developer.

**Comment by JGreenFearless** [comment]
@PatriciaPerozoUSDS There's a standing ticket (#4524) for this already with a checklist that can be cloned and assigned as needed.  Feel free to add to it.
