### ISSUE TITLE
ProPhase Diagnostics - Received file NOT for our Jurisdiction

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#5843]
6/16 3:10pm
Caroline Thomas - caroline.thomas@doh.wa.gov

Good morning,

During our regular quality checks we found a file from ProPhase Diagnostics via USDS Report Stream that we believe is meant for another health jurisdiction. Unfortunately, DOH does not have an easy way to send data to these groups.

The file is as follows:

MSH ID (for DOH use) – 339975547
Message Control ID - 20220614162157
Accession Number - 221640003989
Reason  - Patient Address has state listed as WA but the remainder of the address (including city and zip) indicate the patient address is in NY.

We would appreciate you double checking this file and letting us know whether this report is indeed for WA. If not, please send it to the corresponding state’s department of health or appropriate health jurisdiction at your earliest convenience. If you need additional information to help you locate this record, please let me know.

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5843?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS
