### ISSUE TITLE
SimpleReport - Testing New Schema - DATETIME errors

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5846]
**Describe the bug**
SimpleReport Testing New Schema and getting unexpected results.  All the values for DATETIME columns do not appear to be parsed correctly - the errors returned - saying that the fields are blank:

**Impact**
Testing Stage so not a major impact right now.

**Expected behavior**
Submission should have no errors.

**Screenshots**
![image (2).png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/b16c08c0-f2bc-4b67-867f-2f41f955f80f)

**Comment by brick-green** [comment]
SR is going to move forward using four digit year. The bug is tracked in ticket #5849. Closing this one as the SR is good to go.
