### ISSUE TITLE
Improve validation of CLIA #s

### ISSUE THREAD

**Issue by sarahnw** [CDCgov/prime-reportstream#5850]
Right now we only validate CLIA # based on character length. Unfortunately, incorrect/fictitious CLIA #s are sent downstream when incorrectly input by senders. TX has raised this issue and offered input on how they've validated this in the past. 

RS should evaluate:
1. When do we need to pass through real, but not registered CLIA #s to receivers?
2. Are there ways to improve our validation that do not block the needs in #1, but also improve the occurrence of false CLIAs being sent downstream to receivers?

Notes from TX:

> Here are the rules that we use to validate, fyi…
> The value has to be in ##D####### format and we flag any CLIAs in the file that are in consecutive order.  The latter rule was applied because the facilities would copy and drag the CLIA number causing the values to increase by one from one record to the next
> We check the CLIA number in CMS or CDC website to make sure it is a valid CLIA number and it belongs to the facility.  Perhaps you can automate that check through API’s?

From TX - The websites they use:
CDC website (https://www.cdc.gov/clia/LabSearch.html) – we use this one first and if we can’t find the CLIA number there, we will check CMS website
CMS QCOR website (https://qcor.cms.gov/index_new.jsp) – tends to have more up-to date information than CDC website

**Comment by brick-green** [comment]
I've used those CLIA tools in the past. I agree that the CMS site is better but neither are perfect. If we wanted to validate I see two approaches:

1. Similar to the LIVD table: we pull a copy of the CLIAs and also maintain supplemental file that allows us to add special CLIA
2. We treat it as a valueset: pull a copy one time then maintain the full list ourselves going forward

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5850?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS

**Comment by Adrian-Brewster** [comment]
Megan going to SimpleReport to understand what CLIA verification they are doing.
