### ISSUE TITLE
Website updates MVP

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#5858]
## Problem statement

We have a ton of content to roll out in the epic this issue is linked to, but we need to make some large, baseline changes first in order to make the rest happen.

## What you need to know

- The below AC will help us get the content/layout ready for the homepage and top three main sections in the new IA.
- Let's try to reuse/remix as much existing content as possible. We can clean up and make the bigger improvements we have planned out in coming sprints.
- Existing work has been done on `/contact` in #4913 in [this branch](https://github.com/CDCgov/prime-reportstream/tree/dg/contact-faq/frontend-react)
- [Working Figma File](https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=3332%3A21910)
- [IA Mural](https://app.mural.co/invitation/mural/primedatainput6410/1638994814548?sender=uc91f7c72c0f84196a8818813&key=e1caad3b-ebae-429c-80eb-e7873446668d)

### Homepage

>Content that covers high-level information about the product and drives folks to learn more or contact us.

- [x] Section that describes what ReportStream is (the current Hero may still work here)
- [x] Section that describes what we do for API senders + links to sender-focused overview under `/product`
- [x] Section that describes what we do for STLTs + links to receiver-focused overview under `/product`
- [x] Section for "where we're live" map, links to `/where-were-live`
- [x] Section for contacting us that links to `/contact`
- [x] Create a layout for above content sections

### Product section

>Content that helps a prospective user understand what RS does and how it can help them. The existing `/how-it-works/overivew` pages will most likely work here with minimal changes.

[What's new/release notes content June 22](https://cdc.sharepoint.com/:w:/t/USDSatCDC/EfCKDZRx94VLnNl9WQZr_0UBterUyFDFm7pCDKsVyRSelg?e=nIWtmr)

- [x] Product index page (?)
- [x] Overview page for API senders
- [x] Overview page for CSV senders
- [x] Have solid ideas for nav dropdowns/sidebars/etc we may need for this content

### Resources section

>Content that helps a user understand the more technical aspects of the project (ex the programmer's guide). We can consolidate and edit existing guides from `/how-it-works/*` for the MVP.

[Referrral guide pdf content](https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=q70yvu&cid=14bcfa86%2D21af%2D485e%2D9bd5%2D11fcfa1a0218&FolderCTID=0x0120004368ADED9C3BEA4B94E57C5781F119FF&id=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FTeam%20Documents%2FExperience%20Team%2FInstructional%20Design%2F3%2E%20Instructional%20Design%20Projects%2FReportStream%20Referral%20Email%20Instructions%20and%20Copy%20%2D%20for%20PHD%2FFor%20Public%20Health%20Dept%20%2D%20How%20to%20Refer%20Users%20to%20ReportStream%20v20220519%20%2D%20PDF%2Epdf&parent=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FTeam%20Documents%2FExperience%20Team%2FInstructional%20Design%2F3%2E%20Instructional%20Design%20Projects%2FReportStream%20Referral%20Email%20Instructions%20and%20Copy%20%2D%20for%20PHD)

- [x] Resources index
- [x] Existing guides are linked _somewhere_, *including CSV guides/documentation*
- [x] Programmer's guide PDF is linked from _somewhere_
- [x] Have solid ideas for nav dropdowns/sidebars/etc we may need for this content

### Support

> Content that helps a user understand common problems and reach out to get help.

- [x] FAQ page (can use existing content from #4913)
- [x] Support page (can use existing content from #4913)
- [x] Have solid ideas for nav dropdowns/sidebars/etc we may need for this content

### ETC

- [x] Find something to do with the existing CSV user guides. If we launch this before we fully sunset that feature, that content needs to live somewhere.
- [ ] Catalog necessary redirects from existing URLs + create follow-on engineering ticket

## To do

- [x] Put together a suuuuuper-basic wireframe (LIIIIIKE THE MOST BASIC EVER) to help visualize how this'll come together
- [x] Draft content outline in this [doc](https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Website%20Copy%20Writing/Proposed%20Outline%20for%20RS%20Website%20Content%20Infrastructure%20Revisions%20-%20June%202022.pptx?d=w87cf87a3bb9e404fbf38902c79c03fd6&csf=1&web=1&e=I1eHgw)
- [ ] ...

**Comment by BerniXiongA6** [comment]
Content outline is done and ready for review over [here](https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Website%20Copy%20Writing/Proposed%20Outline%20for%20RS%20Website%20Content%20Infrastructure%20Revisions%20-%20June%202022.pptx?d=w87cf87a3bb9e404fbf38902c79c03fd6&csf=1&web=1&e=I1eHgw) and is also housed under [Issue # 5856](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5856)

**Comment by HeatherRienks** [comment]
FYI - #5826 (Engineering ticket) should be worked at the same time!

**Comment by BerniXiongA6** [comment]
Content outline is saved in the above AC but for your convenience, I've also [included the Shared Doc again here](https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Website%20Copy%20Writing/Proposed%20Outline%20for%20RS%20Website%20Content%20Infrastructure%20Revisions%20-%20June%202022.pptx?d=w87cf87a3bb9e404fbf38902c79c03fd6&csf=1&web=1&e=I1eHgw) just in case.

**Comment by kevinhaube** [comment]
@drew-usds @BerniXiongA6 Working branch can be seen by checking out `git checkout experience/5826-IA-shuffle` or in the browser by navigating to our repository and selecting `experience/5826-IA-shuffle` from the branches dropdown. 

[Here is a link to where our working nav changes will live](https://github.com/CDCgov/prime-reportstream/blob/a37b9f1e62f5ec2bf2533c7a28fe5e112bf43869/frontend-react/src/components/header/ReportStreamHeader.tsx#L46-L49); when using `new-ia` feature flag, we will overwrite the navigation with a whole new navigation so we can really tinker with things. This will *only* overwrite public pages since below it we are still conditionally adding pages for logged in members.

**Comment by drew-usds** [comment]
Updates for sprint review 7/5

- Content is good for `/resources` and `/help center`
  - Pages are starting to be built out
- Work still in progress on home page and `/product` section
  - Andrea working on image ideas for home page
- Will need to carry this card over into the next sprint, but will be able to get this work published this coming sprint along with #5826 and #5859

**Comment by BerniXiongA6** [comment]
Hey @drew-usds I've updated the [PPT deck with links to the content outline](https://cdc.sharepoint.com/:p:/t/USDSatCDC/EaOHz4eeu09AvziQLHnAP9YBCRUZavk1jKSSft0iG3EDPQ?e=Tpf3hf) -- for "Product overview" section and "Support" overview section, see Versions B for links to both shared docs. Happy to update any other pieces of content for the MVP if needed, LMK. Thanks! cc: @a-chappelear

**Comment by kevinhaube** [comment]
Worked with @drew-usds to get the `/resources` page templated out so edits can be made in JSON rather than JSX

**Comment by drew-usds** [comment]
Am working on further cleanup on the templates for `/resources` and am duplicating some of that work over to `/product` and `/support`.

Also have moved copies of our existing content to these new directories and appended `Ia` to thier constants so we can use them/make any needed edits without altering anything currently in prod.

**Comment by drew-usds** [comment]
Todo for 7/14:

- [ ] Get Andrea's local env fully set up to be able to push/pull (was blocked by Docker setup, signed commits)
- [ ] Get Kevin's help with `/product` section with mixed tsx and md content
- [ ] Kevin's help with redirects ex `/contact` to `/support` ... how can we make this work to future proof changes to paths as `/support` grows?
- [ ] Kevin's help: page titles working across templates/tsx/md files
- [ ] Kevin: set up tests for routes to new pages (so we can eventually make this PR)
- [ ] Andrea: paste in content to `/product`, format as MD (but don't worry about template perfection yet)
- [ ] Andrea: paste in content to `/built-for you`, and format as MD (and don't worry about template perfection yet)
-  [ ] Drew: Template work on `/product`, `/support`
  - Is responsive
  - Is valid HTML (right Hx, right nesting, labels, accessible, etc)
  - Steps towards Figma mockups but doesn't have to be pixel perfect

Follow-on work

- [ ] Template work on `/product` content Andrea is working on
