### ISSUE TITLE
SCSS updates for markdown-driven static pages

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#5859]
## Problem statement

Many of our existing pages rely on USWDS classes applied directly in the markup. This worked at the time, but is hard to maintain and is generally a pain to deal with as we move forward with .md. We need to move those styles into appropriate SCSS so .md renders consistently.

## What you need to know

Having poked around with new pages while working on #4913, this may also necessitate some small changes to our templates (ex: we might have some extraneous wrapping divs and similar things)

## Acceptance criteria

- [x] Static content SCSS is moved into it's own file + linked in SCSS manifest
- [x] Updated SCSS compiles correctly
- [x] Md displays consistently across our pages

## To do

- [x] Create new scss file and add to manifest
- [x] Audit classes in current markup
- [x] Migrate to styles in scss

**Comment by TomNUSDS** [comment]
Note: USWDS (and Trussworks) have an update to a major new version that will require build changes.

**Comment by drew-usds** [comment]
Technically done with with Kevin merging #5858 yesterday.

Will be more ongoing cleanup here but this can be "closed".

**Comment by HeatherRienks** [comment]
@RakshindaAslam - closing this, per Drew's comment.
