### ISSUE TITLE
Onboard Nova Labnetics (LIMS ABC)

### ISSUE THREAD

**Issue by jbiskie** [CDCgov/prime-reportstream#5863]
## Problem statement

Onboarding for Nova Labnetics. LIMS ABC client.

**Comment by GilmoreA6** [comment]
Sender is in testing mode in ReportStream prod. Need to validate message with IL-DPH to move to active.

**Comment by sliu1000** [comment]
Please refer to 5880 - closed duplicate ticket.

**Comment by GilmoreA6** [comment]
Message sent to il-dph for validation. Informed LIMS ABC that we are awaiting validation from state

**Comment by GilmoreA6** [comment]
Il responded with a request for the following changes:
PID-8 remove additional components except PID-8-1
PID-10 race is not populated but is being sent in PID-12. Send race in PID-10
SPM-2 contains addition component separators (^^). Please send only SPM-2-1 and SPM-2-2 per HL7 standard.

**Comment by sliu1000** [comment]
Received email from user on 8/24 at 5:28 AM asking for an update.  Please see below for more information:

Do you have any updates for us? I've made the corrections that you mentioned and sent a few more messages starting from a week ago. 
Please let u s know if we can move ahead with Illinois and maybe start with some other state as well. 

Thank you,
Adrian B.

**Comment by GilmoreA6** [comment]
State of IL, validated new messages. Sender is ready to move to full production. Relayed info to sender.

**Comment by GilmoreA6** [comment]
Waiting for PR #6547 to be completed. Settings already updated in prod and staging through UI.

**Comment by sliu1000** [comment]
Updated from User:

Greetings everyone, 

Now that we are live with Illinois via Report Stream, we will send production like messages for the other states that Nova will be resulting. 
I will let you know once messages have been sent for those states so you can validate and provide feedback. 

Thank you,
Adrian B.
