### ISSUE TITLE
Design & Discovery - HL7 Validation Errors

### ISSUE THREAD

**Issue by a-chappelear** [CDCgov/prime-reportstream#5869]
As a sender or an O&O team member, I want to clearly see in the UI and different types of errors that make my HL7 invalid and how to correct.

## Need to know
Work breakdown for error msg improvement initiative
https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1659379562245/028bbeb7dd7b819298ba1b436703882855bc767f?sender=u3fea607b46e84058d3224917
Here are where the API error/warning messages are generated: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/ActionMessages.kt

## Acceptance Criteria
- [ ] Define how each message is labelled and the text that is displayed in the UI. Possible additions maybe link to HL7 specs.
- [ ] Update the wireframe, if necessary. 

## To do

- [x] Create an initial taxonomy based on Hl7 sample files that return errors and/or through discussions of possible error types with O&O. Identify the "types" - warnings, structural, lining. (Seth working on in blocked/linked ticket)
        - [Seth has done much of this already located here ](https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FTeam%20Documents%2FExperience%20Team%2FEngineering%2FMisc%20Experience%20Eng%20Docs&viewid=17db3ff6%2D95c5%2D4562%2Da1f3%2D12b5097b5947)

- [ ] [Figma file](https://www.figma.com/file/b2Zd1xzmp4cdwFO8O7edcI/CSV-Uploader-%26-Validation?node-id=2652%3A1578)

**Comment by bgantick** [comment]
TODO: add links to documentation and warning/error examples

**Comment by a-chappelear** [comment]
Per the scope of this ticket -  the below is for HL7 errors only. (however! You could extend this to CSVs or other file types as they are added.) This is also utilizing [several UI updates that were made in this completed and closed ticket](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6365).

[Figma file](https://www.figma.com/file/b2Zd1xzmp4cdwFO8O7edcI/CSV-Uploader-%26-Validation?node-id=2652%3A1578) - as annotated:

25 - The fail message should link to some form of documentation. Are there plans to create it in the same way CSV has it? It's mentioned as a possibility in the AC of the ticket, but no link to where these are.

24 - A nice to have - on any error message you should specify where a user can locate the error. For an Hl7, that is segment, for other file-types it could be "rows" or "numbers".  

23 - Confirm with O&O or others that "tracking ID" is needed. Are status codes also used?

22 - I added a "content" guideline piece to the [inventory spreadsheet](https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Engineering/Misc%20Experience%20Eng%20Docs/ReportStream%20Errors%20%26%20Warnings%20Inventory%202022-08-26.xlsx?d=w3fac1cd73045479bb46e1f2550a3415e&csf=1&web=1&e=DZ9pxv) (row H & I)and also tried to reword a few of the errors listed there. This can be used when crafting a new error as a reference. 

Generally, the goal is not just to inform a user of the error, but also to provide guidance on what to do about it. I tried to rewrite the ones listed & made some comments on a few (there's little info in these to determine what to do to fix it, so documentation would be helpful here.)

**Comment by HeatherRienks** [comment]
@bgantick - are we ok to close this ticket out? I believe there are some UI changes that "may" still need to be done. Let's discuss!

cc: @a-chappelear @RakshindaAslam

**Comment by bgantick** [comment]
Yes - okay to close this.
