### ISSUE TITLE
MO - Validation Errors - Dates

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5875]
**Describe the bug**
Dates out of sequence 

From: Muehlhausen, Jake <Jake.Muehlhausen@oa.mo.gov> 
Sent: Tuesday, June 21, 2022 10:43 AM
To: Sathngam, Ott (CDC/DDPHSS/OD/HITSSU) <sry8@cdc.gov>

Subject: RE: Get Missouri Onboarding started.
 
Good morning, Ott!
 
We received the 15 messages, thank you.  For all 15 messages we are seeing dates out of sequence, please remember these datestamps should follow in time sequence:  SPM-17 <= OBX-19 < MSH-7 The Specimen Collection Date should be the earliest, followed by Observation Date, 
followed by Message Date.  
 
Here are the validation errors we are seeing on 12 of the messages.  
 
• PATIENT_RESULT[0].PATIENT.PID.PrimaryLanguage[0].NameOfCodingSystem Description=Field value not found in validation table
•	PATIENT_RESULT[0].PATIENT.PID.TribalCitizenship[0].NameOfCodingSystem Description=Field value not found in validation table
 
Some of the 12 messages show both errors, some show one error or the other.  Please let me know if you need anything.  Thanks.
 
Jake

**Expected behavior**
Datestamps should follow in time sequence:  SPM-17 <= OBX-19 < MSH-7 The Specimen Collection Date should be the earliest, followed by Observation Date, followed by Message Date.  

**Screenshots**
None

**Logs**
None

**Comment by sliu1000** [comment]
Follow-up from user Jake on June 21, 2022 at 3:30 PM

From: Muehlhausen, Jake <Jake.Muehlhausen@oa.mo.gov> 
Sent: Tuesday, June 21, 2022 3:30 PM
To: Sathngam, Ott (CDC/DDPHSS/OD/HITSSU) <sry8@cdc.gov>
Cc: Muehlhausen; Report Stream (CDC) <reportstream@cdc.gov>; Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR) <rut5@cdc.gov>; White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>; Brewster, Adrian (CDC/DDPHSS/OD/HITSSU) (CTR) <mpz9@cdc.gov>; Thomas, Susan_DHSS <Susan.Thomas@health.mo.gov>; Dietle, Eden <Eden.Dietle@health.mo.gov>; Williams, Joel <Joel.Williams@health.mo.gov>; Mickels, Becca <Becca.Mickels@health.mo.gov>; McKee, Angela AK (CDC health.mo.gov) <angela.mckee@health.mo.gov>; jayna@skylight.digital; charlye@skylight.digital; West, Zachary <Zachary.West@oa.mo.gov>
Subject: RE: Get Missouri Onboarding started.

Good afternoon, Ott.

Please re-send the 15 messages with corrections.  

Also, regarding the 6 messages we received at 13:01, this afternoon (Filename: covid-19-ddbe82ed-7152-4c94-9d56-6159df1ac073-20220621172009), here are the validation errors.  

PATIENT_RESULT[0].PATIENT.PID.PrimaryLanguage[0].NameOfCodingSystem Description=Field value not found in validation table (each of the 6 message showed this error) PID-15 is not required, you may omit.  Or you may omit PID-15-3 ‘ISO’

(these errors below were only present on MSH-10: 01c1d220-f797-49e4-b61e-3e8caada1626)

PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[0].OBX.PerformingOrganizationName.OrganizationName Description=Field too long: 64 > 50 
PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[1].OBX.PerformingOrganizationName.OrganizationName Description=Field too long: 64 > 50
PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[2].OBX.PerformingOrganizationName.OrganizationName Description=Field too long: 64 > 50
PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[3].OBX.PerformingOrganizationName.OrganizationName Description=Field too long: 64 > 50
PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[4].OBX.PerformingOrganizationName.OrganizationName Description=Field too long: 64 > 50
PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[5].OBX.PerformingOrganizationName.OrganizationName Description=Field too long: 64 > 50

Thank you.

Jake

**Comment by oslynn** [comment]
I am closing this ticket.  We are going to fix this with ticket 5891 https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/5891.
