### ISSUE TITLE
LA County Dept. Public Health - Getting Started with ReportStream

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5876]
@Adrian-Brewster  
Do we need to do anything further for this user?

From: Emily Mabile <EMabile@ph.lacounty.gov> 
Sent: Wednesday, June 15, 2022 7:22 PM
To: Report Stream (CDC) <reportstream@cdc.gov>
Cc: Brewster, Adrian (CDC/DDPHSS/OD/HITSSU) (CTR) <mpz9@cdc.gov>
Subject: RE: Getting started with ReportStream

Hi Adrian,

After our call, I believe someone was planning to send the csv specs that you use for report stream.

Thanks,

Emily A. Mabile, MPH
Supervising Epidemiologist | Lab Data Operations
Acute Communicable Disease Control
Los Angeles County Department of Public Health
EMabile@ph.lacounty.gov | Office: (323) 215-7597 
Pronouns: she/her/hers
Why pronouns matter

Confidentiality Notice:  This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information.  Any unauthorized review, use, disclosure or distribution is prohibited.  If you are not the intended recipient (or a designated agent), please contact the sender by reply e-mail and destroy all copies of the original e-mail message.

From: Report Stream (CDC) <reportstream@cdc.gov> 
Sent: Wednesday, May 25, 2022 10:21 AM
To: Emily Mabile <EMabile@ph.lacounty.gov>
Cc: Brewster, Adrian (CDC/DDPHSS/OD/HITSSU) (CTR) <mpz9@cdc.gov>
Subject: Re: Getting started with ReportStream

CAUTION: External Email. Proceed Responsibly. 
Hi Emily,

I can hop back in here. ReportStream uses a series of mappers and filters to ensure the data coming in can pass validation with the receiving jurisdiction's surveillance system.  In the event that you received data that were missing any key elements, you would email this address (reportstream@cdc.gov) and we would get a ticket opened to have an engineer troubleshoot.  That said, our CSV format is pretty strict so in order for data to upload to ReportStream and pass our validation, it would need to be high quality.  We work with senders to make sure their data can conform to our requirements and the data is validated with several end users before we move it to production. 

If you would like to refer users to onboard to ReportStream, I would be happy to host a Q/A or information session to ensure smooth adoption of our tools. 

Let me know how I can help.

Adrian
________________________________________
From: Emily Mabile <EMabile@ph.lacounty.gov>
Sent: Tuesday, May 24, 2022 9:32 PM
To: Report Stream (CDC) <reportstream@cdc.gov>
Cc: Brewster, Adrian (CDC/DDPHSS/OD/HITSSU) (CTR) <mpz9@cdc.gov>
Subject: RE: Getting started with ReportStream 
 
Hi Sharon,
 
I am with the LA County department of Health, and I do not have any anticipated message volume.  We currently have a process to transform flat files into HL7 messages for our ELR at LA County. I am interested in transitioning a few labs from our processing stream to yours.
 
Let me know if you are able to meet to discuss.
 
Emily A. Mabile, MPH
Supervising Epidemiologist | Lab Data Operations
Acute Communicable Disease Control
Los Angeles County Department of Public Health
EMabile@ph.lacounty.gov | Office: (323) 215-7597 
Pronouns: she/her/hers
Why pronouns matter
 
Confidentiality Notice:  This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information.  Any unauthorized review, use, disclosure or distribution is prohibited.  If you are not the intended recipient (or a designated agent), please contact the sender by reply e-mail and destroy all copies of the original e-mail message.
 
From: Report Stream (CDC) <reportstream@cdc.gov> 
Sent: Tuesday, May 24, 2022 3:42 PM
To: Emily Mabile <EMabile@ph.lacounty.gov>
Cc: Brewster, Adrian (CDC/DDPHSS/OD/HITSSU) (CTR) <mpz9@cdc.gov>
Subject: RE: Getting started with ReportStream
 
CAUTION: External Email. Proceed Responsibly. 
Hi Emily,
 
What is your anticipated daily message volume?  Also, can you please provide the below information:
 
Name:
Job title:
Organization:
Email address:
Phone number:
 
Organization that referred me to ReportStream:
Public health department(s) I report to:
Current reporting method(s):
 
Best regards,
 
Sharon
 
From: Emily Mabile <EMabile@ph.lacounty.gov> 
Sent: Thursday, May 19, 2022 12:38 PM
To: Report Stream (CDC) <reportstream@cdc.gov>
Subject: RE: Getting started with ReportStream
 
Hi Adrian,
 
We are interested in onboarding a couple of labs, but before we do I was hoping I could learn more about your feedback process and how your team handles dirty data. I want to propose the transition to the labs with a more complete understanding of what the process will be like for them.
 
I am available tomorrow between 10am and 3pm pst, Monday 11am or 1pm pst, or 10am or 12:30pm pst.
 
Let me know if you’re available to meet at any of those times!
 
Emily A. Mabile, MPH
Supervising Epidemiologist | Lab Data Operations
Acute Communicable Disease Control
Los Angeles County Department of Public Health
EMabile@ph.lacounty.gov | Office: (323) 215-7597 
Pronouns: she/her/hers
Why pronouns matter
 
Confidentiality Notice:  This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information.  Any unauthorized review, use, disclosure or distribution is prohibited.  If you are not the intended recipient (or a designated agent), please contact the sender by reply e-mail and destroy all copies of the original e-mail message.
 
From: Report Stream (CDC) <reportstream@cdc.gov> 
Sent: Friday, March 25, 2022 12:22 PM
To: Emily Mabile <EMabile@ph.lacounty.gov>
Cc: Karen Swanson <kswanson@ph.lacounty.gov>; Daniel Lichtenstein-boris <DLichtenstein-Boris@ph.lacounty.gov>
Subject: Re: Getting started with ReportStream
 
CAUTION: External Email. Proceed Responsibly. 
Yes, absolutely.  Below is a brief snippet of information you can send out to potential CSV Uploader users and it includes next steps for signing up and getting started. 
 
What’s ReportStream?
ReportStream is a free tool developed by the Centers for Disease Control and Prevention (CDC) and U.S. Digital Service (USDS) that makes it easy for public health data to be transferred from testing facilities to public health departments. More about this tool can be found at reportstream.cdc.gov.
 
Why use ReportStream?
ReportStream is 100% free and offers some other great benefits:
•        Allows you to send faster, more accurate data directly from your testing facility or lab through a single connection. You no longer have to come up with a makeshift approach to report data.
•        Test results and patient data are securely stored and protected by two-factor authentication, database encryption, and HTTPS.
•        Provides access to view your file submission history.
 
How do I submit to ReportStream?
Currently, ReportStream can accept either a comma-separated values (CSV) file or Health Level 7 (HL7) input data format. All you’ll need to do is register for a free ReportStream user account to get started.
Next steps:
1. Register for a free ReportStream user account at https://reportstream.cdc.gov/getting-started/testing-facilities/account-registration-guide
2. Review the ReportStream CSV Uploader Guide at https://reportstream.cdc.gov/getting-started/testing-facilities/csv-upload-guide
 
Questions?
If you have questions about ReportStream, you can email them directly at reportstream@cdc.gov.
 
________________________________________
From: Emily Mabile <EMabile@ph.lacounty.gov>
Sent: Wednesday, March 23, 2022 8:22 PM
To: Report Stream (CDC) <reportstream@cdc.gov>
Cc: Karen Swanson <kswanson@ph.lacounty.gov>; Daniel Lichtenstein-boris <DLichtenstein-Boris@ph.lacounty.gov>
Subject: RE: Getting started with ReportStream 
 
Thanks so much for that information! Are there specific instructions that it would be helpful to include when we direct providers to you?
 
Emily A. Mabile, MPH
Supervising Epidemiologist | Lab Data Operations
Acute Communicable Disease Control
Los Angeles County Department of Public Health
EMabile@ph.lacounty.gov | Office: (323) 215-7597 
Pronouns: she/her/hers
Why pronouns matter
 
Confidentiality Notice:  This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information.  Any unauthorized review, use, disclosure or distribution is prohibited.  If you are not the intended recipient (or a designated agent), please contact the sender by reply e-mail and destroy all copies of the original e-mail message.
 
From: Report Stream (CDC) <reportstream@cdc.gov> 
Sent: Wednesday, March 23, 2022 12:21 PM
To: Emily Mabile <EMabile@ph.lacounty.gov>
Subject: Re: Getting started with ReportStream
 
CAUTION: External Email. Proceed Responsibly. 
Hi Emily,
 
Apologies for the delay.  I had an email written up and saved in my draft folder to respond to this and must have not hit the send button! 
 
California is one of the 4 states currently engaged in the CSV uploader pilot program. Onboarding is fairly quick assuming the data coming in can meet our CSV standard schema requirements. What sorts of questions can I answer for you?
 
Adrian
________________________________________
From: Emily Mabile <EMabile@ph.lacounty.gov>
Sent: Thursday, March 17, 2022 8:17 PM
To: Report Stream (CDC) <reportstream@cdc.gov>
Subject: Getting started with ReportStream 
 
Hi there,
 
I am part of the Los Angeles County Lab Data Operations unit and would like some more information on lab and provider opportunities to report through ReportStream. Specifically, is the CSV upload pilot available in California?
 
Thank you,
 
Emily A. Mabile, MPH
Supervising Epidemiologist | Lab Data Operations
Acute Communicable Disease Control
Los Angeles County Department of Public Health
EMabile@ph.lacounty.gov | Office: (323) 215-7597 
Pronouns: she/her/hers
Why pronouns matter

**Comment by Adrian-Brewster** [comment]
@MauriceReeves-usds will follow up with CSV spec

**Comment by Adrian-Brewster** [comment]
@MauriceReeves-usds have your sent the specs?

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5876?planning-poker) with ZenHub @brick-green @greene858 @jorg3lopez @oslynn @sarahnw @TomNUSDS

**Comment by shy2cdc** [comment]
Email from Emily:

Hi Sharon,

Yes, you can close it. @Quratulain Ajmal if you have any questions about Report stream- please reach out directly to open a new ticket!

Thank you!


Emily A. Mabile, MPH
