### ISSUE TITLE
Onboarding API Sender - Geneus Diagnostics Las Vegas

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5878]
## Issue
This is the ticket for onboarding API sender Geneus Diagnostics. They're using LIMSABC which we're working with already so this should be a relatively straightforward onboarding :fingers_crossed:

## STLTS they'll report to
Nevada, Arizona, Colorado and Texas

## Onboarding Status Updates
(please update here when they've moved between each onboarding phase)
STATUS: PRE-STAGING
- Sarah emailed developer guide 7/11
- Kickoff call held 7/8

## Original ticket below
New Reportstream ELR request

TOS completed
Looking to schedule a call for next steps.

From: Beatriz Pompe <bpompe@ivitalize.com> 
Sent: Tuesday, June 21, 2022 12:38 PM
To: Report Stream (CDC) <reportstream@cdc.gov>
Subject: Re: Geneus Diagnostics Las Vegas

I have some sense of urgency to get this done, maybe get the simple report started would be a good option while ELR is set up.
I just registered for the ReportStream and signed the terms and conditions.
We need to report results to: Nevada, Arizona, Colorado and Texas at this time.
I am available for a call any day this week. 10am.

Thank you for your help.

Kind Regards,

Beatriz Pompe Austin, CLS
Chief Executive Officer - Las Vegas Laboratory
bpompe@ivitalize.com
Direct: 702-960-2445
Office: 725-240-0608

**Comment by Adrian-Brewster** [comment]
Kickoff scheduled for later this week.

**Comment by sarahnw** [comment]
On 7/29/22 Beatriz let us know the lab was having financial issues and pausing connecting for now. Closing this out. Should they decide to onboard in the future we'll revisit.
