### ISSUE TITLE
NM - CLIA Report Dashboard - no longer receiving

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5890]
**Describe the bug**
New Mexico has not received a CLIA report since May 11th, 2022. 

From: Nweke, Pearl, DOH <Pearl.Nweke@state.nm.us> 
Sent: Tuesday, June 21, 2022 5:50 PM
To: metabase@simplereport.gov
Cc: Dinwiddie, Jordyn, DOH <Jordyn.Dinwiddie@state.nm.us>; Smith, Carmela, DOH <Carmela.Smith@state.nm.us>; Report Stream (CDC) <reportstream@cdc.gov>; Ligh, Ming (CDC/OD/OCS) <rtn9@cdc.gov>; Doyle, Maggie, DOH <Maggie.Doyle@state.nm.us>
Subject: New Mexico CLIA Report Dashboard

Good afternoon Simple Report,

New Mexico has not received a CLIA report since May 11th, 2022. Please, can you send us the latest report? We will like to receive the report twice a week on Mondays and Wednesdays.

Let us know if you have any questions.

Thank you
Pearl

**Expected behavior**
 Please, can you send us the latest report? We will like to receive the report twice a week on Mondays and Wednesdays.

**Additional context**
After looking in the SLLT folder for New Mexico. It appears that the CLIA reports have been sent to Pearl. Not sure why she did not receive it.

**Comment by Adrian-Brewster** [comment]
@sliu1000 I just reconfigured their report distribution. Lets check in with them and see if that takes care of their issue.

**Comment by sliu1000** [comment]
@Adrian-Brewster Hi Adrian,  I have contacted Pearl and let her know.
