### ISSUE TITLE
Fix SPM-17, OBX-19, and MSH-7 Fake data generator 

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#5891]
Currently, Fake data generator generates datetime stamp for SPM-17, OBX-19, and MSH-17 out of sequence.  It supposes to generate datestamps in time sequence: SPM-17 <= OBX-19 < MSH-7.

**Comment by oslynn** [comment]
Example of good and bad messages:
Good message
MSH-7:  Date/Time of Message:                   20220617223224	(file_created_date)
OBX-19: Date/Time of the Analysis:      		20220617000000  (test_result_date)
SPM-17: Specimen Collection Date/Time : 		20220608021708  (specimen_collection_data_time)

Bad message
MSH-7:  Date/Time of Message:                   20220617223224	(file_created_date)
OBX-19: Date/Time of the Analysis:              20220608000000  (test_result_date)
SPM-17: Specimen Collection Date/Time : 		20220615010820 < -- Date (20220615 > 20220608) is later than "Time of the Analysis"

Bad message
MSH-7:  Date/Time of Message:                   20220617223224	(file_created_date)
OBX-19: Date/Time of the Analysis:              20220610000000  (test_result_date)
SPM-17: Specimen Collection Date/Time : 		20220611215438 < -- Date (20220611 > 20220610) is later than "Time of the Analysis"

**Comment by sliu1000** [comment]
@oslynn 

Validation Issues

`covid-19-1f1c6ba2-ab00-4d57-9804-a4007a9324a5-20220624152012`

From: Muehlhausen, Jake <Jake.Muehlhausen@oa.mo.gov> 
Sent: Friday, June 24, 2022 12:27 PM
To: Sathngam, Ott (CDC/DDPHSS/OD/HITSSU) <sry8@cdc.gov>
Cc: Report Stream (CDC) <reportstream@cdc.gov>; Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR) <rut5@cdc.gov>; White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>; Brewster, Adrian (CDC/DDPHSS/OD/HITSSU) (CTR) <mpz9@cdc.gov>; Thomas, Susan_DHSS <Susan.Thomas@health.mo.gov>; Dietle, Eden <Eden.Dietle@health.mo.gov>; Williams, Joel <Joel.Williams@health.mo.gov>; Mickels, Becca <Becca.Mickels@health.mo.gov>; McKee, Angela AK (CDC health.mo.gov) <angela.mckee@health.mo.gov>; jayna@skylight.digital; charlye@skylight.digital; West, Zachary <Zachary.West@oa.mo.gov>
Subject: RE: Get Missouri Onboarding started.

Good morning, Ott!

Thank you! I did want to report a couple validation issues on a message this morning, filename covid-19-1f1c6ba2-ab00-4d57-9804-a4007a9324a5-20220624152012:

PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.OrderingFacilityName.OrganizationName Description=Field too long: 52 > 50
PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[0].OBX.PerformingOrganizationName.OrganizationName Description=Field too long: 55 > 50
PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[1].OBX.PerformingOrganizationName.OrganizationName Description=Field too long: 55 > 50
PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[2].OBX.PerformingOrganizationName.OrganizationName Description=Field too long: 55 > 50
PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[3].OBX.PerformingOrganizationName.OrganizationName Description=Field too long: 55 > 50
PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[4].OBX.PerformingOrganizationName.OrganizationName Description=Field too long: 55 > 50

Thanks for all your hard work!  

Jake

**Comment by sliu1000** [comment]
Created new ticket #5937 for the data validation error

**Comment by oslynn** [comment]
SPM-17 (csv:  specimen_collection_date_time) <= OBX-19 (csv: test_result_date) < MSH-7 (csv: file_created_date)

**Comment by oslynn** [comment]
Email from Angela: https://outlook.office365.com/mail/inbox/id/AAQkADY2ODFiNTg0LWYyZTItNDc0Ny1hNTg4LTdhYzAzOWVmYTczMgAQABZxXftT5UGdsRDhNJCWIU8%3D

Hi, Ott!

 

Your most recent messages passed structural validation, which is great, thank you!

There are still some issues with the dates being out of sequence, but I think the issue can be fixed very easily. There are some messages where the specimen collection date/time (SPM-17) and the observation date/time (OBX-19) are before the date/time reported (MSH-7). I believe this can be solved by adding the same date/time offset to SPM-17 and OBX-19 as is applied to MSH-7. The date/time offset is -5000. So you would just need to add -5000 to both SPM-17 and OBX-19 and that should solve the issue.

I will follow this email with an encrypted email including some of the affected messages so you can see what I’m referring to.

Thank you, Ott!

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5891?planning-poker) with ZenHub @brick-green @greene858 @jorg3lopez @oslynn @sarahnw @TomNUSDS

**Comment by sliu1000** [comment]
@oslynn @BerniXiongA6 Can we close this?

**Comment by oslynn** [comment]
Already deployed.  I am closing this ticket.
