### ISSUE TITLE
React API Tools: Runtime type checking API data

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#5892]
## Problem statement

Right now, we are not checking data at runtime which is a feature of `rest-hooks` we want to implement within our own API tooling. The data coming back from `useRequestConfig` should be type-checked at runtime and used to create objects from the `API.resource` so we can later embed functionality in those resources to perform actions on our data.

## Acceptance criteria

- [ ] Data returning is type-checked at runtime
- [ ] Data comes back as resource(s) that can extend future functionality

## To do

- [ ] ...

**Comment by doug-s-nava** [comment]
closing this as we discussed as part of react-query implementation and ruled that it was a nice to have that can be possibly revisited later after migration to react-query is complete
