### ISSUE TITLE
WA - Test Data Suppression Request

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5897]
## Problem statement
The user Jennifer Risler submitted a request asking for the Test Data sent to production interface to be suppressed in production feed. 

Test data sent to production interface First name: Testing; Last name: Build.  

Requesting suppression of test data in production feed.

## Acceptance criteria

Suppression of test data in production feed.

## To do
Let Jennifer Risler know when completed jennifer.risler@doh.wa.gov

**Comment by Adrian-Brewster** [comment]
Look to see why we submitted test data to production. Did a sender accidentally send during onboarding?

**Comment by sliu1000** [comment]
@Adrian-Brewster per the user Jennifer Riseler (jennifer.risler@doh.wa.gov)

I have no background regarding why a test result is submitted through the production feed versus the test feed.  That is something that happens on the sender side of the equation.  
The result below could have been created at the test site for training or other purposes or might be a new site onboarding with USDS that failed to route to the test interface. Could you please investigate?

First name = Testing
Last name = Build
Test request assigner = Specialty Diagnostics Inc
MSH-10 = GK343732+3+20220517

**Comment by Adrian-Brewster** [comment]
Sender is SDI Labs.  Single occurrence.  User error as sender transitions over to CSV Uploader in SimpleReport. I emailed WA.
