### ISSUE TITLE
Valueset Editor: Refactor lookup table backend structure

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#5909]
## Problem statement

For MVP of Valueset Editor, it was decided to store all valueset detail data in one large table called `sender_automation_value_set_row`. At the time it seemed that, in light of some of the limitations of the lookuptable api (links below) we would need to make an embarrassing number of calls to the API if we had to store each valueset in their own table. While those limitations still hold, and there are a series of stories now written to address some of that, it became apparent while doing the MVP work that storing each valueset in their own table would _not_ lead to an increased number of calls in and of itself, since each set of valueset data would only be pulled once per page load.

Fortunately, our MVP frontend code was built generically enough that moving to this model should _not_ be that difficult. All valuesets share now and will continue to share the same basic structure (same fields) and still can relate to their parent table `sender_automation_value_set` by their name fields. Moving to this model will also solve our awkward "Last Update" issue [link to story here TBD], since we'll now be able to pull that information directly from the API rather than having to store it as custom fields on the related `sender_automation_value_set` record. And besides just being better aligned with industry-standard data normalization practices, it will also lead to less redundant data being stored in the database _aggregate_. In other words, instead of having to re-insert the 1600+ row `sender_automation_value_set_row` table into the database with each little update to _any_ valueset, we can now re-insert generally much smaller tables into the database with each little update- but _only_ to the table corresponding to the valueset we're editing (the `patient_preferred_language` will still be a problem, there). 

Basic workflow:

Split the existing sender_automation_value_set_row CSV into 11 different CSVs corresponding to each valueset. We can modify the ConvertValuesetsYamlToCSV.kt CLI tool to do this easily from the source document (sender-automation.valuesets). Then, load them per usual via the lookuptable CLI. 

IF, however, Valuesets UI has already gone live and is in use, a _new_ migration tool will have to be created. Instead of the `sender_automation_value_set` file acting as the source of truth, it will instead be whatever the latest version of the `sender_automation_value_set_row` table. You can get the latest content of that table in CSV form via the Lookuptable CLI, for example:

`$ ./prime login --env prod`
`$ ./prime lookuptables list --env prod  # to determine the latest version, which plugs into the next command`
`$ ./prime lookuptables get --name sender_automation_value_set_row --env prod --output-file output.csv --version 1`

## What you need to know

- [Valueset Editor Backend Architecture spike](https://cdc-my.sharepoint.com/:w:/g/personal/srz7_cdc_gov/EcT4ehC-ya1HjWqswoF64ksBKooh0wmuth75DY-lCWKeWg?e=2VbYEF)
- Lookup Table API Enhancement stories: #5706 #5707 #5708

## Acceptance criteria

- [ ] Refactor backend data structure to one table per valueset
- [ ] Modify the LookupSenderAutomationValuesets mapper as needed (IF needed)
- [ ] Add/modify unit tests as needed

## To do

- [ ] ...

**Comment by bgantick** [comment]
TODO: split the UI portion into a separate ticket (3pts). Add details about updating the mapper to this ticket
