### ISSUE TITLE
Valueset Editor: Display Last Update Info on Details Page

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#5912]
## Problem statement

Due to some technical complexities and general shortage of time, we passed on implementing the Last Update and Updated By information for MVP (outlined below from the [design doc](https://www.figma.com/file/fKl2M96ylkxYezwjVVUSIX/Internal-Admin-%26-Tools?node-id=0%3A1)). Implement it now!

![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/00441a22-6680-47f5-839f-017edb8ac314)

If the [backend refactor](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5909) story is first implemented, then this becomes a very easy task. One would simply need to call the `/info` lookuptable api endpoint for the particular valueset, and bob's your uncle. Highly recommend doing the refactor first!

Barring the backend refactor, the task looks something like:

1. On saving or adding a value set row, update the custom `created_by` and `created_at` fields on the `sender_automation_value_set` table. Without any of the Lookup Table API Enhancement stories completed, _that_ task involves: a. pulling the entire contents of `sender_automation_value_set`, b. updating createdBy and createdAt for the particular valueset row, and c. posting the entire contents of `sender_automation_value_set` back to the API
2. On load of the Details page, display the Last Update and Updated By fields for that valueset. Without any of the Lookup Table API Enhancement stories completed, _that_ looks like: a. pulling the entire contents of `sender_automation_value_set`, b. filtering that set by just "sender_automation_value_set" and, c. displaying the createdBy and createdAt values

## What you need to know
- [Valueset Editor Backend Architecture spike](https://cdc-my.sharepoint.com/:w:/g/personal/srz7_cdc_gov/EcT4ehC-ya1HjWqswoF64ksBKooh0wmuth75DY-lCWKeWg?e=2VbYEF)
- Lookup Table API Enhancement stories: #5706 #5707 #5708
- [OG Design Doc](https://www.figma.com/file/fKl2M96ylkxYezwjVVUSIX/Internal-Admin-%26-Tools?node-id=0%3A1)

## Acceptance criteria

- [ ] Display the Last Update and Updated By fields on the Details page for the selected valueset
- [ ] Unit tests as needed

## To do

- [ ] ...

**Comment by HeatherRienks** [comment]
Work #5911 in tandem!

**Comment by doug-s-nava** [comment]
not implementing: designs do not match the reality of the data available from the API at this time. Following up with Mo to figure out next steps.

**Comment by doug-s-nava** [comment]
reopening - createdAt and createdBy params can be treated as update metadata, as the entire lookuptable is created anew whenever it is updated. The PR will include this, but not the text above the updated meta, as this text is meant to be dynamic, but not available from the API
