### ISSUE TITLE
Cleanup FHIR empty properties generated by HL7 translation

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#5920]
### User Story:
As a developer, I want empty properties in the FHIR Bundle to not be present, so the bundle is easier to read.  This can help future FHIR data users as well.

### Description/Use Case
The HL7 to FHIR conversion library is generating some empty properties in the FHIR bundle that could be suppressed to make it cleaner and easier to read.  Remove those empty properties if possible.

### Risks/Impacts/Considerations
* There could be properties that are too hard to suppress.  Consider effort vs gain.  It does not hurt to leave those in the bundle.

### Dev Notes:
* Example: See `Observation->interpretation` and `Observation->method` in a FHIR bundle.
* Go through the entire bundle to find any empty properties that could be suppressed.
* You will need to use some `condition` in the config to suppress them.

### Acceptance Criteria
* Empty properties in a FHIR bundle are not shown.

**Comment by TurkeyFried** [comment]
In most cases, adding `condition: $textValue NOT_NULL` to the field config will take care of it.

**Comment by TurkeyFried** [comment]
For reference, this is the spec to look for Observation data on: https://build.fhir.org/observation.html

**Comment by TurkeyFried** [comment]
Race and Ethnicity are giving me trouble when I attempt to filter them out. The data is very similar to the Religion data, but any `NOT_NULL` conditions I attempt to put in it are leading to valid data being filtered out!

Leaving those 2 as is for now...

**Comment by TurkeyFried** [comment]
Animal is giving the same issue. These are all in the `PID` Segment.
