### ISSUE TITLE
Activation of Valueset Lookup Tables

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#5923]
## Problem statement

Currently in the Valueset Editor UI, when someone edits or adds a row, that new version of the lookup table(s) is(are) automatically "activated" via a call to the Lookup Table API's activate endpoint:

`PUT {{baseUrl}}/lookuptables/sender_automation_value_set[_row]/{{version}}/activate`

In other words, we made the decision for MVP to _only_ display the latest active version of the lookup tables in the UI, and any edits are automatically activated. However, a better understanding of the current use cases in and around activation should be investigated and better handled in the UI, if this current default handling is insufficient. 

For example, 

- Are table versions only inactivated/re-activated in emergency rollback scenarios? 
- Are they sometimes left inactive to represent a "draft" or "in-development" version of a table, to be reviewed before being made active? 
- Are they sometimes left inactive in order to more precisely time their deployment? 
- Is this more important just for audit/archive capabilities? 
- All of the above? 
- None of the above?

This spike is to determine
1. Is the current default handling sufficient for our present needs?
2. If not, what use case(s) do we need to support, and how?

An important consideration here also relates to how we're currently representing valueset lookup tables. For MVP, we chose to represent _all_ valuesets in one "master" lookup table, `sender_automation_value_set_rows` (with their parent records in `sender_automation_value_set`). What this means in terms of activation/de-activation is that the "versions" we're talking about here equate to the latest version of _all_ valuesets at once, as a big set. There is a story in the backlog (#5909) to refactor this into a lookup table _per valueset_. If that story has been completed by now, that will greatly help guide the decisions in and around activations. In other words- is it even meaningful/useful to provide any control over version activation when the version we're talking about one version of all valuesets combined?

## What you need to know
- [Valueset Editor Backend Architecture spike](https://cdc-my.sharepoint.com/:w:/g/personal/srz7_cdc_gov/EcT4ehC-ya1HjWqswoF64ksBKooh0wmuth75DY-lCWKeWg?e=2VbYEF)
- Lookup Table API Enhancement stories: #5706 #5707 #5708
- [OG Design Doc](https://www.figma.com/file/fKl2M96ylkxYezwjVVUSIX/Internal-Admin-%26-Tools?node-id=0%3A1)

## Acceptance criteria

- [ ] Document findings on this ticket. Or, if extensive, on a new external doc
- [ ] Recommend a general course of action and write supporting stories for design and/or implementation as needed
- [ ] Unit tests as appropriate. Just kidding, there's no coding here, I just wrote that out of habit.

**Comment by bgantick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/5923?planning-poker) with ZenHub @ahay-agile6 @doug-s-nava @kevinhaube @sethdarragile6

**Comment by doug-s-nava** [comment]
this should likely be taken into account in any future Value Sets research. heads up to @fmccaf1 . If user testing doesn't bring up any of these issues, this card can be closed.

**Comment by kevinhaube** [comment]
Labeled with "needs design" so @fmccaf1 and @drew-usds have visibility. Not sure if we did ValueSets usability testing or not, but if not, this can remain open. If we did, let's assess the outcomes for relevance of this ticket together!

**Comment by fmccaf1** [comment]
Looks like usability testing was done by Andrea C. as one of her items on her last sprint. [Here's the ticket - 6786 - , which is where findings are located.](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6787)

**Comment by chris-kuryak** [comment]
Experience team has a new value sets issue/epic tracking our updates to Value Sets UI in #7904. Any other updates needed will be requested by O+O team a future date. Closing.
