### ISSUE TITLE
Retire old sender automation lookup mapper (LookupSenderValuesetsMapper)

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#5924]
## Problem statement

Many months ago, a mapper called `LookupSenderValuesetsMapper `(in Mapper.kt) was created out of the ashes of an aborted effort to write a fuzzy-match AOE mapper. For whatever reason, this mapper was never adopted, and now a _new_ mapper called `LookupSenderAutomationValuesets` is in active development which essentially does the same thing, only better. This mapper should either be completely removed or otherwise formally deprecated (if there is a way in code to designate that and support it)- along with its supporting unit tests and artifact(s), i.e. `./metadata/tables/local/sender_valuesets.csv`

## Acceptance criteria

- [ ] One last general investigation into whether or not LookupSenderValuesetsMapper is being used (it's currently not, but it's always good to check one last time)
- [ ] Remove (or deprecate) all code, tests and data related to LookupSenderValuesetsMapper 

## To do

- [ ] ...

**Comment by bgantick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/5924?planning-poker) with ZenHub @ahay-agile6 @doug-s-nava @kevinhaube @sethdarragile6
