### ISSUE TITLE
MO - Message Validation Issue

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5937]
**Describe the bug**
Receiving a data validation error message

From: Muehlhausen, Jake <Jake.Muehlhausen@oa.mo.gov> 
Sent: Monday, June 27, 2022 10:05 AM

Subject: RE: Get Missouri Onboarding started.

Good morning!
 
Here is the ID for the message in reference → MSH-10:  `a68813c0-0bf6-4b62-9e34-dcbc55a42e22`

From: Muehlhausen, Jake <Jake.Muehlhausen@oa.mo.gov> 
Sent: Friday, June 24, 2022 12:27 PM
To: Sathngam, Ott (CDC/DDPHSS/OD/HITSSU) <sry8@cdc.gov>
Cc: Report Stream (CDC) <reportstream@cdc.gov>; Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR) <rut5@cdc.gov>; White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>; Brewster, Adrian (CDC/DDPHSS/OD/HITSSU) (CTR) <mpz9@cdc.gov>; Thomas, Susan_DHSS <Susan.Thomas@health.mo.gov>; Dietle, Eden <Eden.Dietle@health.mo.gov>; Williams, Joel <Joel.Williams@health.mo.gov>; Mickels, Becca <Becca.Mickels@health.mo.gov>; McKee, Angela AK (CDC health.mo.gov) <angela.mckee@health.mo.gov>; jayna@skylight.digital; charlye@skylight.digital; West, Zachary <Zachary.West@oa.mo.gov>
Subject: RE: Get Missouri Onboarding started.
 
Good morning, Ott!
 
Thank you! I did want to report a couple validation issues on a message this morning, filename covid-19-1f1c6ba2-ab00-4d57-9804-a4007a9324a5-20220624152012:
 
PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.OrderingFacilityName.OrganizationName Description=Field too long: 52 > 50 (ORC-21.1)
PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[0].OBX.PerformingOrganizationName.OrganizationName Description=Field too long: 55 > 50 (OBX-23.1)
PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[1].OBX.PerformingOrganizationName.OrganizationName Description=Field too long: 55 > 50
PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[2].OBX.PerformingOrganizationName.OrganizationName Description=Field too long: 55 > 50
PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[3].OBX.PerformingOrganizationName.OrganizationName Description=Field too long: 55 > 50
PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[4].OBX.PerformingOrganizationName.OrganizationName Description=Field too long: 55 > 50
 
Thanks for all your hard work!  
 
Jake

**Comment by oslynn** [comment]
We are having an issue with prod VPN 2022-06-27.

**Comment by oslynn** [comment]
I downloaded the covid-19-d994b83c-dc25-48a9-8596-d710150a3df4-20220627232021.hl7 file to ~/Downloads

**Comment by Jcavallo7** [comment]
Hello,

The user followed up and needs help with additional messages.

This is what he reported.

MSH-10:  489daaaa-09fd-4848-a70b-b984f0700236

 

PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.CallBackPhoneNumber[0].PhoneNumberString_X Description=Field too long: 18 > 15

<PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBR.OrderCallbackPhoneNumber[0].PhoneNumberString_X Description=Field too long: 18 > 15

 

We continues to see this validation error, on many messages also. 

 

PATIENT_RESULT[0].PATIENT.PID.PrimaryLanguage[0].NameOfCodingSystem Description=Field value not found in validation table

 

Here is another error, I noticed from a message sent early this morning.

 

<MSH.SendingApplication.UniversalID Description=Required field missing

<MSH.SendingApplication.UniversalIDType Description=Required field missing

<MSH.ReceivingApplication.UniversalID Description=Required field missing

<MSH.ReceivingApplication.UniversalIDType Description=Required field missing

<MSH.ReceivingFacility.UniversalID Description=Required field missing

<MSH.ReceivingFacility.UniversalIDType Description=Required field missing

Thanks

**Comment by oslynn** [comment]
Hi, Ott!

Here are the MSH-10’s for some of the messages where the SPM-17 and OBX-19 values are out of sequence. Please let me know if you need any additional information. Thank you!

·         495445
·         537048
·         c005f5ab-7cba-4bb1-898b-9d7f67b60239
·         d8ed81f0-fbec-4cf1-bd14-f8f0aa24ed13

·         aa91366c-a6f6-46cb-a2f6-26ef70a74824

Please let me know if you need any additional information. Thank you!

**Comment by oslynn** [comment]
To resubmission:

Here is the ID for the message in reference → MSH-10:  `a68813c0-0bf6-4b62-9e34-dcbc55a42e22`

OTT Downloaded: 
./prime sender-files --env prod --message-id a68813c0-0bf6-4b62-9e34-dcbc55a42e22 -o junk/mo-onboarding/csv/2022-07-06
Writing: junk/mo-onboarding/csv/2022-07-06/receive/simple_report.default/2022070716263258_pdi-covid-19-d2596c44-1484-484a-9e49-e112b94470fc-20220624135200.csv

Update organization.yml: truncateHl7Fields:  ...ORC-21-1, OBX-23-1
Ran: data --input junk/mo-onboarding/csv/2022-07-06/receive/simple_report.default/2022070716263258_pdi-covid-19-d2596c44-1484-484a-9e49-e112b94470fc-20220624135200.csv --input-schema primedatainput/pdi-covid-19 --output-dir junk/mo-onboarding/hl7 --route

Output:
/home/judith/workspace/cdc/working/prime-reportstream/prime-router/junk/mo-onboarding/hl7/covid-19-124207fa-33b5-46da-bcd4-326f17bea533-20220707175522.hl7
/home/judith/workspace/cdc/working/prime-reportstream/prime-router/junk/mo-onboarding/hl7/covid-19-1d476e91-abf1-41c7-816d-50edfba1ae6e-20220707175522.hl7

**Comment by oslynn** [comment]
Email back to Jake:

Dear: Jake,

I apologize for getting back to you a little late.  I resubmitted three files associated with thee MSH-10s.

MSH-10
24d41af-9297-490a-ba20-497b4e386df0
    Fixed:              suppressHl7Field: PID-15-3
    Resubmitted file:   covid-19-49d80a3e-7f27-4a87-9acc-455040d5a889-20220708104813.hl7

MSH-10:
a68813c0-0bf6-4b62-9e34-dcbc55a42e22
    Fixed: ORC-21-1, OBX-23-1 truncated to length of 50.
    Resubmitted files:  covid-19-124207fa-33b5-46da-bcd4-326f17bea533-20220707175522.hl7,
                        covid-19-1d476e91-abf1-41c7-816d-50edfba1ae6e-20220707175522.hl7

MSH-10s below, I Can't find file associated with them.
489daaa-09fd-4848-a70b-b984f0700236
495445
537048
c005f5a-7cba-4bb1-898b-9d7f67b60239

**Comment by oslynn** [comment]
Need to work on adding the offset to the times.

**Comment by oslynn** [comment]
Updated Organization settings:
Prod:
![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/a4bf8abe-0200-4cd6-9244-3623589014c9)

Staging:
![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/d43a01bb-1df1-475e-877f-903b4502ce6f)
