### ISSUE TITLE
Update githook scripts to let user know if it can't find Terraform

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#5940]
Currently if you do not have Terraform installed you may run into a message saying it is failing the Terraform Formatting check. This is usually due to a rebase pulling merged Terraform into a feature branch & caused by the developer not having Terraform installed.

Please update the script to make it obvious it's missing the Terraform executable when failing for that reason.

**Comment by lucasdze** [comment]
I created https://github.com/CDCgov/prime-reportstream/pull/6566 to resolve this issue
