### ISSUE TITLE
Valueset Editor: Refactor UI network calls to implement newer API tooling

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#5985]
## Problem statement

While the Valuesets UI was being developed, a new refactor was made to the overall networking sitewide. Not wanting to interfere with the on-going development, that refactor was left out of the Valuesets UI. We need to now move Valuesets UI to that network refactor.

## What you need to know

- Refactor Story: #5557
- Refactor PR: #5893

## Acceptance criteria

- [ ] Migrate Valuesets UI existing network layer to new Haubean network layer

## To do

- [ ] ...

**Comment by bgantick** [comment]
Closing: being implemented in #6392
