### ISSUE TITLE
Transition fully to USWDS 3.0

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#5997]
# Problem Statement

USWDS 3.0 has been released, and to maintain best UI practices, we need to transition off of 2.0 onto 3.0. We currently do not know what that entails. 

## What to know
- Our current style architecture - will this transition require changes, and are there new features we should be taking advantage of to improve our styling architecture?
- State of the Stylesheet - we should assess what custom redundant custom styling we may have, ways we can simplify and reduce any styling in excess of uswds.
- Trussworks compatibility and ROI - how reliant are we on trsusworks, and do we want to be? Falls under the style architecture umbrella but is of extra importance since we've intertwined it with uswds sass styling in our app.

>Note from the future: Hey, Kev again. Trussworks seems to have been a limiting factor for our team in some ways, and beneficial in some small doses. Personally, I'd advocate for replacing their implementations by just spinning your own with the style sheets provided by USWDS and their [in-depth component documentation](https://designsystem.digital.gov/components/overview/). Most of the code you'd need is already there if you have the stylesheet integrated into your site.

# Acceptance Criteria
- [ ] USWDS 3.0 style sheets are implemented in ReportStream's React app

**Comment by kevinhaube** [comment]
@CnoteNava @chris-kuryak @HeatherRienks Rewrote this ticket as a unit of work to update the stylesheets for USWDS from 2 to 3. I removed tech-debt as a label because design system updates do provide a true enhancement to the site and this should be prioritized over tech-debt.

**Comment by stephenkao** [comment]
Notes from today's backlog refinement discussion:
This ticket is specifically regarding upgrading the `@trussworks/react-uswds` dependency from v2 --> v3.  If we want to move off of this dependency entirely (and roll our own visual treatment compliant with the USWS), we should spin up a technical proposal and have a separate discussion about that.

**Comment by chris-kuryak** [comment]
This will require a scoping session by engineering before breaking into multiple issues.

**Comment by jpandersen87** [comment]
an experiment branch that is migrated to react-uswds 4.0 (uses uswds 3.0) is here: https://github.com/CDCgov/prime-reportstream/tree/experience/experiment/react-uswds-4.0.0
