### ISSUE TITLE
CO - Warrior Diagnostics - Server Error When Submitting Report

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#6008]
File not uploading

User cannot submit report due to server issue

![image.png](https://images.zenhubusercontent.com/62828ac9597e3bae41382df7/fd690ed4-9695-4e48-819c-391fa6701a53)

Good morning, 

I am trying to submit a report and am getting the following error:

Error: File not accepted
There was a server error. Your file has not been accepted.

Please let me know how I need to proceed.

Thank you,
Katie
--
Katie Rhyner, General Supervisor

**Comment by Adrian-Brewster** [comment]
@sliu1000 Please follow up with the submitter for this issue and see if it still persists.  I am trying to rule out if this is related to the issue that occurred earlier last week for SimpleReport users that we fixed already.

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/6008?planning-poker) with ZenHub @oslynn @jbiskie @MauriceReeves-usds @TomNUSDS @sarahnw @brick-green

**Comment by sliu1000** [comment]
@Adrian-Brewster Kattie from Warrior is still getting the same message as before.

**Comment by shy2cdc** [comment]
Megan Doss megan@warrior-dx.com 7/7 1:27pm

We are still having issues loading our CSV.  We get an a message saying there is a server error.  Can you please assist us in getting our files uploaded?

@sarahnw @Adrian-Brewster Can you please provide a status update on this ticket. The user is still receiving an error.

**Comment by brick-green** [comment]
@sarahnw Can we close this?
