### ISSUE TITLE
CO - San Juan Basin Public Health - Add 2 new users

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6015]
Samie Stephens (sstephens@sjbpublichealth.org)

We would like to request access to Report Stream.
•	Name of public health department: San Juan Basin Public Health
•	Jurisdiction type (state, county, city, etc.): County (La Plata and Archuleta counties)
•	Name of jurisdiction (For example: “Harris County” or “Washington State”): Archuleta county and La Plata county
•	Name(s) and email(s) of people who need database access:
1.	Shandi Pritchett <SPritchett@sjbpublichealth.org>;
2.	Todd Macon <tmacon@sjbpublichealth.org>;

For the users listed above, we are requesting access to view test results (via this website: https://reportstream.cdc.gov/login). They do not need access to report test results.

**Comment by Adrian-Brewster** [comment]
@sliu1000 Can you please explain what the following statement means? "For the users listed above, we are requesting access to view test results (via this website: https://reportstream.cdc.gov/login). They do not need access to report test results."

**Comment by sliu1000** [comment]
User Samie Stephens emailed ReportStream today asking for a status update.

**Comment by brick-green** [comment]
Just added both users to the group. @sliu1000 Can you confirm with them that it's working?

**Comment by sliu1000** [comment]
@brick-green 

Hello,  I have emailed the user and will let you know if there's any further action required.

Sharon

**Comment by brick-green** [comment]
closing after 2 weeks
