### ISSUE TITLE
MA - Last time The Residence at Five Corners reported

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#6016]
MA is trying to see when the last time The Residence at Five Corners reporting via reportstream. The sender has told MADPH that they have been submitting results recently but MA is unable to find them.

**Comment by sarahnw** [comment]
@Adrian-Brewster the last I see of data we got from them is May 6th. I'll ask SR to check on their side too.

**Comment by sarahnw** [comment]
Emma confirmed that's the last time they entered a test into SR too.

**Comment by sarahnw** [comment]
@sliu1000 do you know if Adrian ever followed up with Mass on this? I can't find an email in the shared inbox with this specific ticket. I see an email thread from June, but doesn't look like he followed up there. LMK if I can/should just respond there.

**Comment by sliu1000** [comment]
@sarahnw Hi Sarah, I do not see any follow-up response from Adrian on this.

**Comment by BerniXiongA6** [comment]
@sarahnw will email them cc: @BerniXiongA6

**Comment by sarahnw** [comment]
Responded. Closing.
