### ISSUE TITLE
NV - ELR Resent (272 times) since 7/2/2022

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6017]
Karen Felicietta (kfelicetta@health.nv.gov) Sent an email to ReportStream on 7/5/2022 at 11:13 AM.

**Describe the bug**
Please stop the sending of ELR to Trilith Main Tent facility in Nevada.  

**Impact**
Since 7/2/2022 the ELR has been updated/resent 272 times.

Accession Number:  `612c7ff1-26c1-449a-ab8e-fac0066a8aaa`

Reporting Facility: Trilith Main Tent 
CLIA#11D2243389
NV-LabID: OBS46149950NV01
Collection Date: 06/08/2022

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/6017?planning-poker) with ZenHub @brick-green @jbiskie @MauriceReeves-usds @oslynn @sarahnw @TomNUSDS

**Comment by shy2cdc** [comment]
Karen Felicietta (kfelicetta@health.nv.gov) Sent an email to ReportStream on 7/6/2022 at 11:20 AM.

We are having this duplication/update issue with multiple ELRs where the same result has been sent over 400 times. We really need this to stop now. Can you please provide an ETA as to when the support team will have completed their review?

All have been from:
Reporting Facility: Trilith Main Tent
CLIA#11D2243389

Additional duplication/updates:
422 updates between 7/2 & 7/6
Accession Number: 38024d1c-6d1a-47e7-a86e-23bf726e4f0c
NV-LabID: OBS46149956NV01
Collection Date: 06/29/2022

429 updates between 7/2 & 7/6
Accession Number: cce3e1c7-8cf8-4cbf-bb18-0922fadd8188
NV-LabID: OBS46149954NV01
Collection Date: 06/22/2022

427 updates between 7/2 & 7/6
Accession Number: 205a081c-88c2-42f7-9fe5-93a92d2d3382
NV-LabID: OBS46149952NV01
Collection Date: 06/15/2022

425 updates between 7/2 & 7/6
Accession Number: a1cdab1f-2603-4fb1-b135-c453ee970b03
NV-LabID: OBS46149946NV01
Collection Date: 06/08/2022

426 updates between 7/2 & 7/6
Accession Number: 859c1b93-f5b3-4419-b3c8-3678e86a61e1
NV-LabID: OBS46149948NV01
Collection Date: 06/01/2022

**Comment by shy2cdc** [comment]
Karen Felicietta (kfelicetta@health.nv.gov) Sent an email to ReportStream on 7/6/2022 at 11:45 AM.

The sample below is of an ELR where earlier this morning there were 429 updates and now there are 462.

Accession Number: cce3e1c7-8cf8-4cbf-bb18-0922fadd8188
NV-LabID: OBS46149954NV01

![image.png](https://images.zenhubusercontent.com/62827d1e0129e15b5c366b1a/3bea0fd4-23d5-4316-84b3-8a156d98fb1f)

**Comment by Adrian-Brewster** [comment]
Sharon, are these still coming in as of today? This problem sender, PMG, was removed from our program yesterday until this issue is resolved on their end.  They should not be receiving duplicates anymore. @sliu1000 @sarahnw

**Comment by shy2cdc** [comment]
@Adrian-Brewster @sarahnw Karen says that duplicates continue to come today as well

**Comment by sarahnw** [comment]
I emailed NV last night. If they don't need anything else from us, I'll close this ticket.
