### ISSUE TITLE
WA - Duplicate Messages sent (7/2 - 7/5) ~ 39-42 copies

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6022]
Caroline Thomas from Washington State Department submitted a ticket via Smartsheet.

## Problem statement

Duplicate messages being sent 7/2-7/5. Approximately 39-42 copies of each message control ID. 

## What you need to know

 Tests were also performed in early to mid June so unsure why they have been sent in July.

`badbe1c5-9bb8-421b-b872-91877a2950ba`
`34abe157-9b9f-4881-8308-92fa0aeabaa1`
`bf7a4567-df12-4e7c-b5ea-d888948fe21a`
`badbe1c5-9bb8-421b-b872-91877a2950ba` 
`d98d80be-2c77-40b2-ac7a-7be84f787667`
`62e1a135-090d-49af-aa5c-3f9e164a1fb2`
`95b29078-84b9-4d45-b1b4-ed17d783ada5 `
`78892e3b-d3b8-4920-94d7-1adfd436f264`
`b4074df0-c987-41cb-ae92-920cd0a74e15`
`2b30b445-f5fc-4890-adfa-407a43e3f4d5`

## Acceptance criteria

Please confirm that these are true duplicates, provide guidance on how DOH should handle these (okay to disregard them?)

## To do
 Investigate why the duplicates are being sent.

**Comment by sarahnw** [comment]
@sliu1000 I'll respond to caroline from the RS email inbox with more information. thank you!
