### ISSUE TITLE
BUG - File size limit does not appear to be working correctly

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6031]
## Issue
MA wrote in that during the PMG duplicate issue RS was sending v large files to their system and requested we lower the file size limit and send multiple files a day instead. 

Upon investigation their maxReportCount is set to 100. Brick checked and there are definitely files being sent larger than that. Jim recommends testing with a receiver in staging with 100 limit, create a 1000 row fake file and send it to see if it creates 10 files to send.

## Acceptance criteria

maxReportCount successfully limits a outgoing report size (sent to receivers) to the number of rows it is set to in the configuration and creates subsequent files for any remaining results that need to be sent.

## Original email/ticket from MA
MA - Request for increase in max file size constraint for HL7 251 messaging
Janice Grantner (elr.cdsupport@state.ma.us)

Problem statement

MA State Department user Janice is asking for ReportStream to review the max file size contraint imposed for HL7 251 messaging. 

What you need to know

User would like the max file size limit to be higher than 2 MB as she doesn't want to submit two separate files.

From: CDSupport, ELR (DPH) <elr.cdsupport@state.ma.us> 
Sent: Wednesday, July 6, 2022 12:13 PM
To: Report Stream (CDC) <reportstream@cdc.gov>
Subject: MDPH ELR: Batch File Size 
Importance: High

Good Morning, 

Can you please review the size of Prime files? We have come across the last couple of days that you files are too big and will need to be split into two files. Today’s file size was 3,139KB and 3,377KB and the size is 2.0MB. I have fixed all the files that we received the last couple of days and these are all set. 

A max file size constraint of 2.0 MB is imposed for HL7 251 messaging. Batch file sizes of <=400 messages are strongly recommended. Multiple batch files can be transmitted each day based on reporting volume.

Please let me know if you have any questions or concerns. 

Thanks, 
Janice

**Comment by Jcavallo7** [comment]
*Update 7/6*

Hi Sharon,

 

It is just one facility CDC Prime-Atlanta, Georgia (Dekalb) where we are seeing the issue with the size of there files. We do not see an error for these messages they are just stalled on our end to go into our database.

 

Thanks,

Janice

**Comment by sliu1000** [comment]
From: CDSupport, ELR (DPH) <elr.cdsupport@state.ma.us> 
Sent: Thursday, July 7, 2022 10:48 AM
To: Report Stream (CDC) <reportstream@cdc.gov>; Brewster, Adrian (CDC/DDPHSS/OD/HITSSU) (CTR) <mpz9@cdc.gov>
Subject: RE: MDPH ELR: Batch File Size 

Hi Sharon and Adrian, 

I would like to clarify this issue. We are receiving these reports from Report Stream to the Massachusetts Department of Public Health. Recently the HL7 file sizes being transmitted to our health department are too big for us to consume. We are requesting that you decrease the number of messages per batch file sent to us (<=400 messages in your batch). For HL7 2.5.1 messages, Massachusetts has a file size constraint of 2.0 MB for our batches. We can set up a meeting to go over this issue if you would like. 

Here are examples of the files. 

File Name	Date	Number of Messages 	File Size
`Prime-20220706135131`	7/6/2022	1,227	3,139KB
`Prime-20220706135134`	7/6/2022	1,336	3,377KB
`prime-20220707135106`	7/7/2022	942	2,491KB

Thanks, 
Janice

**Comment by jimduff-usds** [comment]
? To be clear, MA wants a _decrease_ in file size, not an increase.

**Comment by sarahnw** [comment]
@sliu1000 could you let Janice know these files were large because of the bug we had were we received a large number of duplicates from a sender. We've corrected that issue though so the volume is under control. Please let her know that we do have a file size limit in place for MA, but it looks like that is not working correctly. We've filed a bug ticket and will investigate.

(PS - I'm going to keep this ticket open as the bug and will re-write it)

**Comment by sliu1000** [comment]
@sarahnw I confirmed with Kaleigh that they would appreciate if we could restrict files to no larger than limit 2.0mb (<=400 messages).

**Comment by sliu1000** [comment]
New ticket created 7343. Will close this one out.
