### ISSUE TITLE
Admin Settings for sender missing "allow duplicates" in UI for admin pages

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#6039]
## Problem Statement
As an admin, it is more difficult than it needs to be to change "Allow Duplicates" setting. Would be nice to have a checkbox on the Edit Settings page.

1. Go to sender.
2. Edit Settings.
Result: there is no UI to change the Allow Duplicates setting.
<img width="512" alt="image" src="https://user-images.githubusercontent.com/74203452/177644923-41c2f6de-78a3-42a5-9882-95cd45b65dc7.png">

## Background Info
-  click Preview and the json shows the `allowDuplicates` boolean.

## Acceptance Criteria

- [ ] Checkbox when toggled will set JSON of "allowDuplicates" to true when checked and not true when unchecked
- [ ] Checkbox will will be checked on render if the setting is true in the sender settings

**Comment by RakshindaAslam** [comment]
Hi @TomNUSDS - Could you add what this ticket would solve or how it would add value to ReportStream product or process to help us prioritize?

**Comment by TomNUSDS** [comment]
There is a sub-data value called "Allow Duplicates". It would be nice to surface this as a full field in the UI. Currently, to edit it the user must drill into the json and manually change it (via the Preview button).

Not a super high priority. Might be enough to rename the Preview button to "Preview/Edit Json..." or something?

**Comment by kevinhaube** [comment]
@CnoteNava For Sprint 58 consideration!
