### ISSUE TITLE
NH - Duplicate ELR & Incorrect Patient State Issue

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#6044]
Hello,

 

We are receiving duplicate ELR messages (same MSH-10) from SimpleReport (see below). In addition, this particular patient is not a NH resident. It looks like there is a typo for state. This ELR should have been sent to NM.

 

MSH-10: d52b4ee7-a53e-4f9f-b55f-a8f189fbcb60

 

Entered PID Address: San Felipe Pueblo^NH^87001

 

Thanks,

 

Corinne Davis, MPH, MS

HL7 Implementation SME

New Hampshire Department of Health and Human Services
Bureau of Public Health Statistics & Informatics

corinne.m.davis@affiliate.dhhs.nh.gov | Ph: 603-271-6970

**Comment by sarahnw** [comment]
Hmm I think I already responded to NH about this one.
