### ISSUE TITLE
DE - No Ordering Practitioner / Verify Race Issue

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#6051]
## Problem statement

Missing Ordering Practitioner Information and need to validate that the race and ethnicity is truly unknown

## What you need to know

Message Id for REVIV_Cosmopolitan:

`c7853be7-f4f2-4d02-8230-f43f02deb62d`

Message Id for Lake Clinic:

`b810e385-4bdc-439f-8cb2-f10799abead3`

## Acceptance criteria

Determine the issue of missing ordering practitioner information and correct. Determine if race and ethnicity is valid if not need to correct.

**Comment by Adrian-Brewster** [comment]
@rnz6 I would ask the ticket submitter to reach out directly the the sender and request this information

**Comment by sliu1000** [comment]
The State Department of New Hampshire is still receiving results from NJ Facilities. For more information please see below:

We continue to receive out of state ELR messages for Covid test results from SimpleReport (Same patient, different dates).

It looks like there is a typo for state. This ELR should have been sent to NJ.

 

Most recent message: 8/1/2022

 

MSH-10:

`1b18534c-2514-42d1-b3e2-bc5e7829a522`

 

Entered PID Address:  2621 Hwy 138^^Wall^NH^07719^USA

The zip code is for “Wall Township, New Jersey”.

 

Please let us know if this is something your team could help address.

Thanks,

 

Myron Miroslaw Lizak, MS, MB(ASCP)CM

ELR Coordinator

New Hampshire Department of Health and Human Services
Bureau of Public Health Statistics & Informatics

Myron.Lizak@dhhs.nh.gov | Ph: 603-271-4224
