### ISSUE TITLE
Spike: Discovery of test suite improvements

### ISSUE THREAD

**Issue by sarahnw** [CDCgov/prime-reportstream#6068]
## Problem statement(s)

We would like testing to give us greater certainty on the health of the system. There have been times when our system broke and we didn't know about it. 

## What you need to know

@sarahnw to find tickets where the system broke and our tests didn't indicate it

## Acceptance criteria

- A breakdown of themes/issues with current state of the system
- Should include a write up of ways our system allowed the identified failures to occur
- Impact statement for each problem - either quantifiable or a reason why this is/causes issues.

- Timeboxed to 1 sprint, which should be about 3 focused days of work (spread out however best fits your schedule)

## To do

- @oslynn and @greene858 decide how you want to divide the review of testing
- Write up issues
- Review with team once done.

**Comment by oslynn** [comment]
I am starting to inspect and review our current Unit, Integration, and End2End Tests.

**Comment by oslynn** [comment]
I started the process and using the replaceValueAwithB integration testing as initial test development.

**Comment by brandonnava** [comment]
@oslynn @greene858 Is this done? Did we get what we wanted out of this work?

**Comment by brandonnava** [comment]
@oslynn Bump for an update on priority or if we'd rather close

**Comment by LaFreda1** [comment]
Will reopen in the future, if needed.
