### ISSUE TITLE
Upgrade Function App 2.0 to 4.0 investigation

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#6070]
Work required to update to 4.0. This includes investigating what changes need to be made and implementing them

**Comment by JosiahSiegel** [comment]
[Function app runtime doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=azure-cli%2Cin-process%2Cv4&pivots=programming-language-java)

Also note [breaking changes](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=azure-cli%2Cin-process%2Cv4&pivots=programming-language-java#breaking-changes-between-3x-and-4x)

**Comment by snesm** [comment]
EOL timeline:
"Beginning on December 3, 2022, function apps running on versions 2.x and 3.x of the Azure Functions runtime can no longer be supported." (https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=azure-cli%2Cin-process%2Cv4&pivots=programming-language-java)

**Comment by JosiahSiegel** [comment]
Update teams on status:
https://semanticbits.slack.com/files/T040Y0HTW/F03PB8R2AT0?origin_team=T040Y0HTW
