### ISSUE TITLE
Prescryptive - MSH 5, 6, 7 failures 

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6085]
**Problem Statement**
Require requested resubmission for Prescryptive MSH-5 and MSH-6 value of "CDC PRIME" See also email with subject line RE: Prescryptive dated 5/18, excerpted text below: We would like the files sent prior to the fix to be resubmitted. 

Please check the following items prior to sending resubmissions: • Update MSH-7 • No UTC time • Set MSH-11 to P for production messages • Correct MSH-5 and MSH-6 to the values agreed upon during onboarding.

Message Control ID:

MSH_10_MsgControlId:

`86475ebf-ae36-474b-a197-c20f34ded09c`
`fb2bf2a4-e5a5-4b96-9d06-edd00461d9bb `
`2e3705fa-a693-4818-980a-70ed8ed2d05a`
`7b294caf-b278-4617-8686-58423d88d0f0`
`6bde976e-0e85-434f-be6e-2a49d40d74dd`
`93106df3-12b5-4b42-8b1f-35c8d29282a4`
`a9f71afc-29e9-48d0-9684-2842a24db3ce`
`88d07740-ffbe-4c87-a7e6-96852b1a0c4d`
`e86ffe37-9235-487c-a2d3-334890bc5677`
`e0ceae91-d668-4937-8310-815ac4c4267e`
`090a4c46-7ed1-4fd8-907b-45c1ad805b72`
`6a5e958b-2bd3-4f6e-88b1-7f353fa77b3a`
`cb1e404b-11f8-435a-9a17-a483855fc2f4`
`83f74979-ef99-4aa5-8652-7671a11c3633`
`3a138b05-4864-452d-8b98-806bcdfc95fc`
`3465b5fe-e481-40ce-95cd-48d25debcf19`
`96c8dc45-f403-4fa3-a3e0-80c4a22cfeb8`
`376d3906-7207-4ccc-837e-3825eebafbb4`
`b5c7f068-c617-42df-b7c5-8201ce657b46`
`5bb3098d-8c5c-44d8-9dae-131df1750505`
`d2fb9be4-524f-48b7-96df-1321f79a9a22`
`63445b52-5d2d-4bc0-b1a8-48a1a6215e2c`
`2acde598-233e-404a-b89b-aa4c198c53c0`
`6458b645-6029-4f92-9626-6ecb7735e214`
`62749ba7-03f4-455d-8b78-3f6735498178`
`24c5a7b1-beef-432c-b39c-35c8cffc6900`
`1528e6b0-1ef9-4409-9e4f-11ccbb4f9dd2`
 `5f853df6-1957-4023-9481-8ed102bf0eae`
`7368f148-98d9-4797-95a6-f00a3c5bee58`
`ee3ed0bd-caec-497d-992d-cc7c9b382831`
`61be9f73-6c9a-4a67-901f-59d726520325`
`7f0b7708-c705-4067-a3ed-2bdc0f7c4516`
`5c33efb4-ac0f-4b7e-9167-6abbef3d353d`
`7a7ffc05-5a5b-4df6-9d8c-ee55d850e143`
`3e720a05-a489-4386-bdb6-cd83e051fd4f`
` 9d4a3be3-03ef-40fd-8589-33dc8ba251b0`
`19e62a9f-704b-48ee-af4c-4ab47efef2b9`
`dcf6b512-5f62-48b6-90db-00e5a2ee8188`
`c6add39d-b1ec-49b7-8b89-9c14b2a9a3b0`
`132b81ef-8c37-4848-b40b-a819c7883d90`
`7243284e-ce77-4407-90af-188305787ce8`
`c63d2a57-398f-4682-b08a-cc47398674ff`
`2134a71a-e7f9-4cba-a638-006274eeec92`
`c7d90ce5-e046-4db9-af54-d08aeff0d207`
`0c2a51a4-4c3a-454b-8cb6-f9294d0b0cf1`
`86a1b701-635e-4948-8e2c-21c62aa143ea`
`f65c6dd3-ce6d-4263-97c4-47b46f31da9a`

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/6085?planning-poker) with ZenHub @brick-green @greene858 @jorg3lopez @oslynn @sarahnw @TomNUSDS

**Comment by Adrian-Brewster** [comment]
@sliu1000  who opened this ticket? What state is it for?

**Comment by oslynn** [comment]
Those messages are no longer in the Azure storage to work with.  Therefore, I will close this ticket.

**Comment by BerniXiongA6** [comment]
Updates 8/3/2022: After working with @oslynn to investigate this for Jenni and Julie at WA DOH, looks like Prescryptive did not complete resubmissions. I've contacted WA DOH to let them know we'll be asking Prescryptive to send the data since the resubmissions timeframe has expired. I'll reach out to John@prescryptive.com with this request and cc: @oslynn for visibility.

**Comment by oslynn** [comment]
@BerniXiongA6 can you find out what are MSH-5 and MSH-6 values agreed upon during onboarding?  I can't find his email.  I will make sure ReportStream is setting those values for them.

**Comment by oslynn** [comment]
The correct MSH-5 and 6 is hightlighted in green:
Prescryptive MSH-5 error:

MSH|^~\&|CDC PRIME - Atlanta, Georgia MSH|^~\&|CDC PRIME - Atlanta, Georgia (Dekalb)^2.16.840.1.114222.4.1.237821^ISO|7uycso49^1.3.6.1.4.1.38630.2.1.1.519^ISO|CDPH CA REDIE|CDPH_CID

MNS MSH-5 (no error)

MSH|^~\&|CDC PRIME - Atlanta, Georgia (Dekalb)^2.16.840.1.114222.4.1.237821^ISO|7uycso49^1.3.6.1.4.1.38630.2.1.1.519^ISO|**WADOHPHRED^2.16.840.1.113883.3.237.4.2^ISO|dn1fro00^1.3.6.1.4.1.38630.2.1.1.19^ISO**

**Comment by oslynn** [comment]
I checked prod database.  This issues had already been fixed by @greene858 (Tom Green).
![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/53c382d0-d588-4e96-8fdf-c55855fc9d79)
