### ISSUE TITLE
CA - Test Network Environment For Sending Data To Stage

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#6087]
**Describe the bug**
Configuration to send data to stage was turned off due to lack of use and needed to be activated

**Impact**
User could not send date to stage

**Expected behavior**
Configuration activated and check test environment connection

**Comment by Jcavallo7** [comment]
Ticket Number from Optum "INC27413234"

Subject from email: INC27413234 - CCRS - TACC req - CDC Reportstream unable to send data to stage

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/6087?planning-poker) with ZenHub @brick-green @greene858 @jorg3lopez @oslynn @sarahnw @TomNUSDS

**Comment by sliu1000** [comment]
Vanessa Burkhart asked a follow-up question on 7/25/2022 asking the following:

The Config was re-enabled, hope this resolves the issue and ability to sent to staging should be back. Please let us know.

**Comment by brick-green** [comment]
Just tested and was able to connect to the CA test location.

**Comment by sliu1000** [comment]
@brick-green @BerniXiongA6 

We received an email from CA State asking if their connection has been re-established.  Please confirm.

**Comment by brick-green** [comment]
The test connection is up. Can let CA know.

**Comment by sliu1000** [comment]
@brick-green I have emailed Vanessa from California that the test connection is up.
