### ISSUE TITLE
Validation Service UI - reformat errors/warnings

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#6091]
## Problem statement

As a sender or an O&O team member, I want to be test my data file in CSV or HL7 format and get user friendly responses to understand, identify and fix issues with my data.

## What you need to know
-  [Mural board for Validation Service Deep Dive with Options ](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1651702156098/60d77d324b3bf252c83d30f73f2cc201a59cc1eb?sender=u3fea607b46e84058d3224917)
 - Provide user-interface that allows file drag&drop or upload feature and display of response to the file
 - There is an expectation of reusing CSV Uploader components and features and not a full new page
 - Supporting HL7 and CSV formats for MVP
 - Spike: #5505
- Warning messages need to be added back in to the UI

## Acceptance criteria

- [ ] User is able to upload a file in HL7 or CSV format
- [ ] User is able to view success, warning, and/or error msgs based on the current validation methods
- [ ] Should be behind a feature toggle with safeguards to prevent accidental submissions in prod
- [ ] Update UI based on attached Figma file https://www.figma.com/file/b2Zd1xzmp4cdwFO8O7edcI/CSV-Uploader-%26-Validation?node-id=2288%3A1127

## To do

- [ ] Reformat errors + warnings to be easier to read upon HL7/CSV upload (maybe displaying item, segment, and the error/warning for HL7)
![Screen Shot 2022-07-13 at 7.45.22 AM.png](https://images.zenhubusercontent.com/5a6b4b784b5806bc2bc46da6/610342fb-bfe7-43be-bf0b-25a26010e913)

**Comment by sethdarragile6** [comment]
Change was merged into the [PR ](https://github.com/CDCgov/prime-reportstream/pull/6143)for #6092. Will move to Done when the PR is merged.
