### ISSUE TITLE
Research Validation Service UI - Schema Selector

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#6093]
## Problem statement

As an authenticated OR unauthenticated user, I want to be able to test my data file in CSV or HL7 format and get user friendly responses to understand, identify and fix issues with my data.

## What you need to know
This would essentially be overriding/replacing the reliance on the admin org selector for this feature.
![Screen Shot 2022-07-13 at 8.05.33 AM.png](https://images.zenhubusercontent.com/5a6b4b784b5806bc2bc46da6/0b6ec817-270d-4024-a4c5-e151300487a2)

Might make sense to break this into 2 dropdowns (and narrowing)

## Acceptance criteria

- [ ] Document requirements to make validation page (with an org/schema selector) available to users without an Okta login
- [ ] Create ticket to implement

**Comment by ahay-agile6** [comment]
# Research

## Diagram of notes:
https://lucid.app/lucidchart/183a86c3-8cfd-4eb3-adcc-ebd24ddad360/edit?view_items=_qAIOUIJDFGY&invitationId=inv_fb1f4bd8-b943-4881-9f0c-f754c818b793#

## Research notes:
https://cdc-my.sharepoint.com/:w:/g/personal/rvx0_cdc_gov/EdoL90x7cYlFk-Dm3DtXwjwBj5r49wJLPGgJIgmpteKDOg?e=yTuf8e
