### ISSUE TITLE
Use Upload/Validate UI and give feedback (by Sept. 6, 2022)

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#6112]
## Problem statement

Adjustments to the UI based on feedback from initial user(s)

## What you need to know

- Feature flags: `user-upload` for upload, `validation-service` for file validator
- Features are under a new `Validate & Upload` dropdown in the UI if you're an admin and have the feature flags enabled (Go to "Admin" > "Feature flags" to enable)

## Acceptance Criteria
- [ ] List of issues found
- [ ] List of additional features, if any
- [ ] Metrics or estimates of how long the manual validation took before this Service and with this Service

## Issues found

- [ ] ...

## To do

- [ ] Please [USE THIS MURAL BOARD ](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1662043767982/1bf0eb7e095a84da09e42b2a7d56a764d74a112d?sender=u4a60651bc33557d542d18858) to share any feedback with the Experience Team on your observations with the HL7 UI as you're using the tool to validate sender files. Thanks in advance! [Read original Slack thread](https://slack.com/archives/C025F5W5Q7L/p1660755705103759). **DEADLINE: 9/6/2022 11AM ET**

**Comment by bgantick** [comment]
Pending a sync with the team on enhancements/fixes for upload feature

**Comment by BerniXiongA6** [comment]
8/17/2022 notes: this came up in conversation during Exp. + O&O sync today. Exp. would like to have O&O engineers test -- more to come from Brian. cc: @sarahnw

**Comment by BerniXiongA6** [comment]
Per Brian's Slack ask:

> Hey O n' O team! As discussed in Exp <> O&O sync. We're soliciting feedback on our :sparkles: new :sparkles: validation/upload features (mostly validation)! We have a placeholder ticket to collect feedback. We're hoping to get a list together by our next sync on 8/24.

**Comment by oslynn** [comment]
@bgantick after playing with the validate UI, I love the feature and it surely will help us, indeed.  However, I wonder why we have to use prod for this feature.  Can this feature be in stagging, only?  Therefore, we don't have to touch the prod environment.

**Comment by bgantick** [comment]
@oslynn Validation and upload are available on both staging and prod. Settings differ slightly on prod and staging, so we'd want these features on both.

**Comment by RakshindaAslam** [comment]
O&O team - Updating a phone number in the PID section by adding some dashes still validated the file successfully. Should it have thrown an error?

**Comment by GilmoreA6** [comment]
> O&O team - Updating a phone number in the PID section by adding some dashes still validated the file successfully. Should it have thrown an error?

Looks like the regex allows for both either dashes, spaces or nothing between the numbers and still counts it as "valid". from the code

 "NOTE: (\s|-)?
         * Gives the option of using a space or a dash, but it is not mandatory.
         * This allows for many permutations of phone numbers.
         * Examples:
         * 213-353 4836
         * 213-3534836x1234
         * 213-353-4836 x 1234"

**Comment by jorg3lopez** [comment]
@GilmoreA6 All the above are valid permutations. This was done with the idea to do a fast screening of the phone number. The convention was to restrict the possibility of an invalid phone while expanding the permutations of valid ones.

**Comment by BerniXiongA6** [comment]
Hey engineers -- have you had a chance to use the validator tool to validate sender files yet? Have any feedback for Experience team? Please comment below by tomorrow. Thanks!

**Comment by RakshindaAslam** [comment]
Thanks @jorg3lopez @GilmoreA6 for response on telephone numbers format!

Also updated the A/C - please see above.
@GilmoreA6  @jbiskie @brick-green @oslynn @jorg3lopez @bgantick @BerniXiongA6

**Comment by GilmoreA6** [comment]
Not something that's really a bug per se but I did notice that when uploading CSV files if the format of the cell with a DATETIME in it is anything other than general it can give an error for incorrect format.

**Comment by a-chappelear** [comment]
Hi testers! Question for you - in this screenshot, you can see that the labels used on the header rows are a little inconsistent. (ie. one shows indices, field, tracking id - the other is showing "areas containing the requested edit") When showing these errors, what is the most useful for you to see in these columns (and what is not at all)? Is it helpful for you to know "where" the error is in the file (similar to how you give a row number in a csv) and if so, what is that ideally - a message-id or segment for example?
<img width="1186" alt="Screen Shot 2022-08-24 at 4 49 45 PM" src="https://user-images.githubusercontent.com/33157420/186530182-e0297d79-5fe5-4900-bac8-8896e4bde360.png">

Thanks!

**Comment by HeatherRienks** [comment]
Per Design Sync on 8/25, let's meet w O&O to get more feedback during next sprint (we will guide questions).

**Comment by victorialb-usds** [comment]
Here is a link to the mural to add your feedback: https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1662043767982/1bf0eb7e095a84da09e42b2a7d56a764d74a112d?sender=u4a60651bc33557d542d18858 

Please go ahead and brain dump in all or any of the sections. Including your process or examples for using the validator I can make sense of it (and check in in case I have any questions). If you can do this by 10am ET on Tuesday September 6th!

**Comment by victorialb-usds** [comment]
Presented at O and O standup for async feedback 6/1. As of 6/7 no feedback. We can keep it open for this week and sync up 1-1 with O and O folks. I am concerned this is: overlapping/confusing with shadowing, and overall asking for more (time). Suggestion  (1) who ever is shadowing shares out what they find in terms of use and pain on validation feature specifically and documents it on this ticket or in the mural, and (2) we do 15 minute syncs with any interested and able O and O folks. @HeatherRienks could we temperature check the 1-1 check-in idea in our O and O sync? CC: @RakshindaAslam

**Comment by RakshindaAslam** [comment]
@victorialb-usds - The expectation from the shadowing is to to get input for #1 above as well as ideas for what enhancements may be useful post quality filter response implementation.

**Comment by HeatherRienks** [comment]
@victorialb-usds - We did discuss the 1:1 check-in/shadowing in our Standup today. @bgantick will be working with the Experience Eng team on coordinating this. I know that @BerniXiongA6 has mentioned it to the O&O team and they are on board!
