### ISSUE TITLE
Add Indiana to onboarded map

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#6117]
Indiana is onboarded, just need to update our map.
<img width="450" alt="image" src="https://user-images.githubusercontent.com/74203452/179023508-6f66b1d1-1457-46b2-a355-91b1a5159b7a.png">

- [x] Update map svg
- [x] Update text list on page

**Comment by bgantick** [comment]
Thanks @TomNUSDS ! PR up!
