### ISSUE TITLE
DE - Wants to Receive Facilities List Reports

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6120]
## Problem statement

Would like to receive a facilities list report for those facilities that are sending to DE through ReportStream.

## What you need to know

Please send facilities report to 

- christopher.decker@delaware.gov
- Uche.Njoku@delaware.gov 

## Acceptance criteria

When Christopher and Uche start receiving Facilities list report pertaining to their state facilities.

## To do

Generate and add the above users to a DE facilities distribution list.

**Comment by sliu1000** [comment]
@jayna-SkylightDigital Was this completed?

**Comment by jayna-SkylightDigital** [comment]
@sliu1000:

@Adrian-Brewster will be passing these types of tasks off to @BerniXiongA6.

I've added @BerniXiongA6 as the assignee to this ticket, and removed @emmastephenson.

**Comment by sliu1000** [comment]
@jayna-SkylightDigital @BerniXiongA6 @Adrian-Brewster I think Berni needs to be added to the SimpleReport Metabase in order to make these changes.  Is this something your team can work on?

**Comment by Adrian-Brewster** [comment]
@BerniXiongA6 I am going to move this to the sprint backlog.  If you can try formatting the report as we discussed yesterday before EOD tomorrow, I can assist as needed :)

**Comment by sliu1000** [comment]
@BerniXiongA6 Hi Berni, I believe you should now have access to SimpleReport Metabase.  Please let me know if you'd like me to take care of this.  I was also, able to get SimpleReport Metabase access.
