### ISSUE TITLE
OH - User specific request - Needs Screenshot of their results going to the State by (EOD Monday)

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6124]
## Problem statement

Dr. Matthews (Kmatthews@centrastate.edu) is being audited by Department of Health on July 18 and needs to demonstrate full compliance.  A screenshot of her results being submitted to the state would be sufficient. 

## What you need to know

This is a test results from the State of Ohio.  She needs documentation showing that she's in full compliance with the State of OH by EOD Monday July 18.
- ...

## Acceptance criteria

- Screenshot of her test result submitted to the state of OHIO.

## To do

Someone needs to locate her test results being submitted to the State of OHIO.

- [ ] ...

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/6124?planning-poker) with ZenHub @brick-green @oslynn @jorg3lopez @greene858 @TomNUSDS @sarahnw
