### ISSUE TITLE
401 on report page for admins

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#6126]
**Describe the bug**
Getting a 401 error from the `/api/history/report/xxxxx` endpoint when trying to load a report detail page when mocking a receiver as an admin.

**Impact**
Only affecting PrimeAdmins.

**To Reproduce**
1. Log in with an admin account
2. Switch to a receiver org & select `receiver` from the mock dropdown (`al-phd` for example)
3. Click the "Daily Data" in the nav menu, click through to an individual report

**Expected behavior**

**Screenshots**
![Screen Shot 2022-07-14 at 2.12.29 PM.png](https://images.zenhubusercontent.com/5a6b4b784b5806bc2bc46da6/77fd8935-8fe9-4dc4-aa12-95c6836ad4ba)

^ Note the mismatch between organization header and what org is selected in the admin org switcher.

**Comment by kevinhaube** [comment]
Blocked by: https://www.slack.com/archives/C026DV8R21W/p1658438513173289

**Comment by kevinhaube** [comment]
Blocked by PR #6032 -- Awaiting merge so we can migrate this page over to the new deliveries API and remove this bug.
