### ISSUE TITLE
API error and warning messages include a unique message code

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#6133]
### User Story:
As a Sender, I want error and warning messages to include a unique message code per type of message, so I can programmatically identify a message.

### Description/Use Case
Users like the UI team want to have the ability to identify a message, so they can change the text provided to the users as they see fit.  E.g., the UI team wants to show a help page URL when there are LIVD lookup related errors and warnings.  They also want to be able to summarize all LIVD lookup errors into one.  This effort is to provide unique message codes to be able to programmatically identify the messages.

### Risks/Impacts/Considerations
* Some messages may be too generic and may require future work to make them more unique.

### Dev Notes:
* We have talked several times about having a dictionary of message codes to messages.  We think that may can done in the _ActionMessages_ class, so that may be a good place to add the codes.
* Need to design what the codes look like and design for expansion (e.g. are they numbers, hex, etc.)

### Acceptance Criteria
* Error and warning messages to include a unique message code in API responses.
* Document the error codes (need to determine best place for this - openAPI spec?)

**Comment by kevinhaube** [comment]
Completed by experience #7277
