### ISSUE TITLE
Detect circular schema reference in FHIR to HL7 schema

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#6138]
### User Story:
As developer, I want the FHIR to HL7 library to detect when there is a schema circular dependency, so I can fix the issue.

### Description/Use Case
The FHIR to HL7 library configuration allows for child schemas (a schema that includes another schema).  There is the possibility that someone could include a schema that was already included at a higher level which will result in an infinite loop.  We need to detect any circular dependency, so the pipeline is more robust.

### Risks/Impacts/Considerations
* Need to make sure to detect circular dependencies between child and parents and not confuse it with a reuse of a schema.

### Dev Notes:
* Child schemas could be reused withing a schema, so care must be taken to not remove this feature and only detect circular dependencies.

### Acceptance Criteria
* The FHIR to HL7 library throws a SchemaException if it detects a schema circular dependency.

**Comment by TurkeyFried** [comment]
Tested for circular references based on legit schema issues. The library handles cases such as "Encounter.partOf itself" or "Encounter.part of an Encounter that's part of the first one" fine with no looping.

Will test with badly entered configs yet, with schemas referring to themselves.
