### ISSUE TITLE
Make History API Parameters Case-Insensitive

### ISSUE THREAD

**Issue by luis-pabon-tf** [CDCgov/prime-reportstream#6149]
As an History API user, I want to receive results without needing to verify the casing of each parameter.

### Description/Use Case
RS needs to allow parameters to be accepted in both lower cases or camelCase.

### Acceptance Criteria
- The results of a search with `sortdir = asc` and with `sortDir=ASC` must be identical
- Other parameters defined in openAPI need to do the same.

**Comment by bishoyayoub** [comment]
@TurkeyFried Please check on if this is still needed. If so, please update.

**Comment by bishoyayoub** [comment]
@luis-pabon-tf Please move to ready for grooming or let me know if we should icebox this story.
