### ISSUE TITLE
Refactor `SlugParams` to be generated by directory tools

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#6151]
## Problem statement

Right now, the instantiation of `SlugParams` on pages like `/resources` and `/support` is quite lengthy. It would be awesome to simplify this and maybe bake the process into the `ContentDirectoryTools` object somehow.

## Acceptance criteria

- [ ] Slugs are able to be easily generated through the `ContentDirectoryTools` class

## To do

- [ ] ...

**Comment by doug-s-nava** [comment]
seems like maybe this was done? can you confirm @kevinhaube ?

**Comment by kevinhaube** [comment]
@doug-s-nava Yep, we can close this out!
