### ISSUE TITLE
Research & usability plan - RS public site (MVP)

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#6155]
## Problem statement

Review and collect feedback on the content and usability of the RS website (in its current MVP state). Collect insights from the feedback to help determine the next steps in future iterations. Prepare a planning doc to tackle different sections of the website and how to conduct and schedule interviews.

## What you need to know

 Existing/linked tickets:

- [Product  - content](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5816)
- [Product - design](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6159)
- [Resources - content](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5817)
- [Support - content](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5818)
- [Homepage- content](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5821)

## Acceptance criteria

- [x] [Create a research plan w/ outlined steps for planning](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/UX%20Research/3.%20UX%20Research%20Projects/RS%20Website/MVP%20Updates/Research%20Planning.docx?d=w5ee0434afd3b49df91b797568409964d&csf=1&web=1&e=0MeEyh).
- [ ] Update existing design/content tickets if applicable.

**Comment by a-chappelear** [comment]
@BerniXiongA6 I created a folder for this work under "[Research Projects > RS Website > MVP Updates](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/UX%20Research/3.%20UX%20Research%20Projects/RS%20Website?csf=1&web=1&e=yX7eRT)"  and a doc we can work with around [planning / prep](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/UX%20Research/3.%20UX%20Research%20Projects/RS%20Website/MVP%20Updates/Research%20Planning.docx?d=w5ee0434afd3b49df91b797568409964d&csf=1&web=1&e=vrjdAR)

**Comment by a-chappelear** [comment]
Note - this has recently been updated and adjusted to reflect @BerniXiongA6 moving! :) 
Tickets for updates have also been created and linked within.
