### ISSUE TITLE
Admin - IA, Discovery

### ISSUE THREAD

**Issue by a-chappelear** [CDCgov/prime-reportstream#6160]
## Problem statement
Review the current state of the admin section of the RS site and determine if any changes are needed in the navigation based on recent public site IA changes. Diagram and document the users + goals of different sections of the Admin when logged into ReportSteam.

## What you need to know

- [IA work for the public site](https://app.mural.co/invitation/mural/primedatainput6410/1638994814548?sender=uc91f7c72c0f84196a8818813&key=e1caad3b-ebae-429c-80eb-e7873446668d)
- [Helpful slack convo on user flow needs](https://a1msolutions.slack.com/archives/C02HJ43AE8Z/p1660682632014169)

## Acceptance criteria

- [ ] Determine and map out user flows (and define who the user types are)

## To do

- [ ] ...

**Comment by HeatherRienks** [comment]
@drew-usds, @a-chappelear , @victorialb-usds - pls review in Design Sync. Thanks!

**Comment by a-chappelear** [comment]
This ticket has been edited to cover 2 sprints. Initial work should be mapping out the current use and state, and the following ticket is for any redesign work/recommendations.

**Comment by a-chappelear** [comment]
@kevinhaube Tagging you on this! Whenever this ticket gets pulled in -  I noticed you have some other tickets related to the Admin nav, would love to chat with you on some of these IA-related UI pieces/thoughts.

**Comment by kevinhaube** [comment]
@a-chappelear Can you link the tickets so I have some context?

**Comment by a-chappelear** [comment]
#5961 seemed relevant to some of this (and know you also had some interest in us looking into the user flows in the Admin area, which would be part of this design discovery ticket)

**Comment by a-chappelear** [comment]
This can be closed and the design ticket can be started. The [design team should refine that ticket together](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6555), as the [service map work ](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6503)may adjust some of the mappings as we go along.

**Comment by HeatherRienks** [comment]
FYI @fmccaf1
