### ISSUE TITLE
Design Implementation for RS Home Page

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6172]
## Problem statement

As a prospective or existing user, when I land on the ReportStream home page I want to quickly understand what it is and whether it's relevant to me so that I can continue to read on and learn more about the product.

As ReportStream team, we want prospective and existing users to land on the home page and for our content to hook them into reading more information that will help them decide to sign up, contact us, or learn more about our product.

## What you need to know

We can adapt some of previously revised (but not yet published) content work for this upcoming redesign so we don't have to reinvent the wheel.

- Here's the [Content Design folder](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Website%20Copy%20Writing?csf=1&web=1&e=8d3yPq) that contains previously revised web copy prior to this current June 2022 redesign. 

- [Here's the ReportStream Content Style Guide](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Content%20Style%20Guide?csf=1&web=1&e=GuyPFD) we adhere to for public-facing content

- Here's the [Figma with designs (in progress)](https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=3332%3A22842)

## Acceptance criteria

Content: 
- adheres to ReportStream Content Style Guide
- follows federal plain language guidelines

Design: 
- follows USWDS guidelines
- if diagrams/graphics are needed where indicated by Content, include them on the relevant page/section
- if template is not built, design needs to create it

User voices: Sender is an API user (phase out CSV uploader content), Receiver represents a public health dept (STLTs)

Review/QA:
- Content shares work with Exp. Product and Design team to review before publishing
- Design shares work with Exp. Product and Design team to review before publishing (staging for review? how does this work / let's discuss)

**Comment by kevinhaube** [comment]
@fmccaf1 @drew-usds Doesn't look like a UI ticket. I'll add `design`, and let y'all decide whether this is pertinent to our current goals or not! :)

**Comment by chris-kuryak** [comment]
Closing out as it will come up again naturally in the future.
