### ISSUE TITLE
Design for Validator and Uploader (MVP)

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6173]
## Problem statement

As a user, I want to understand the use case of the Validator and the File Uploader. I want to understand the difference between a "warning" and an "error" and any action I need to take.

## Acceptance criteria

- [ ] Wireframe (if needed) and content for the page descriptions and alert messages.
- [ ] Collect feedback from O&O that helps inform adjustments needed in future iterations and also starts to identify the different groups (or taxonomy) of errors

.

**Comment by a-chappelear** [comment]
Update on this ticket - this mentions error/ warnings as well. [Based on info in 6253](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6253) - "Pipeline team (#6133) is working to create message IDs for each error/warning and a mapper for all msgs" ...this would be very helpful in determining "how"  and "with what" to design this portion. @RakshindaAslam @HeatherRienks

**Comment by a-chappelear** [comment]
It seems like there are other validator stories that go deeper into this - would suggest closing this one and moving on to others. (This seemed to cover the warning/error banners, but the other newer tickets get more specific with the error UIs) @HeatherRienks @RakshindaAslam @drew-usds
