### ISSUE TITLE
Improve loading indicators across site

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#6174]
## Problem statement

Loading spinners currently behave a bit inconsistently across the site. The loading spinner we've currently got is quite large, and is also a non-cdc/non-uswds green for no particular reason. It also has a kind of coronavirus look to it, which is a little _too_ on the nose 😂!  Let's create a plan for making this better for users, better from an engineering perspective, and overall slightly less obtrusive of a _thing_.

_As a user_ ... I'd like to see when a page/piece of a page is loading. There are occasionally long load times on the site and I want to know that something is happening when I click/search/filter/etc. I want this loading indicator to behave fairly consistently so I know where to look/what's going on whether I'm logged into the site or not.

## What you need to know

This is probably the biggest concern for folks who are logged in. The public site is pretty snappy, but we should still consider how loading indicators work whether you're authenticated or not.

- Existing ticket for engineering work #4790

## Questions

- What spinner library are we using currently? What are other options out there? Are there options other than spinners?
- If something in an existing library doesn't work, what are our options?
- USWDS doesn't specify something here ... has the Truss library implemented anything?

## Acceptance criteria/questions to be answered

- [x] Catalog where we are currently displaying spinners
- [x] Outline of how and where we want loading indicators to display across the site
  - [x] If needed, create a low-fidelity mockup of how it might work/look
- [x] Is a spinner the best option (vs other types of loading indicators)?
- [x] Look into options for spinner libraries/what we can use
- [ ] Engineering has had input on the above
- [ ] Engineering is able to move forward with #4790

## To do

- [ ] ...

**Comment by HeatherRienks** [comment]
@a-chappelear - reach out to @bgantick for more details!

**Comment by a-chappelear** [comment]
@bgantick @kevinhaube @drew-usds 
[I have created a doc with some of the questions in the above AC addressed](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/UI%20UX%20Design/3.%20UI%20UX%20Design%20Projects/Loading%20Spinners%20UX.docx?d=w3612f70a31eb4675b8c72d1716def5cd&csf=1&web=1&e=2hvBbr), but a few I can not without a quick chat with Kevin or Brian. Let me know if this can be done in one of the existing Eng syncs next week or I can send out a separate invite!

**Comment by HeatherRienks** [comment]
@kevinhaube & @a-chappelear - if you haven't connected yet, maybe we can use the 16th minute of our Standup tomorrow (or Friday, 8/12) to discuss Andrea's questions.

**Comment by a-chappelear** [comment]
Per design sync + also the doc w/ several of the AC pieces addressed above, [here is a link to a concept for the spinner](https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=3641%3A22877)

Preferences are (noted in the[ Figma file](https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=3641%3A22877) also) - 
- Anytime the spinner loads there is a page title shown (saw instances of just a spinner sitting by itself)
- Any type of circle animation can be used but should be set to the primary blue color
- Would like the ability to *say* what is happening, ie. "loading submission data"

@drew-usds @bgantick @RakshindaAslam @HeatherRienks

**Comment by bgantick** [comment]
This is the closest thing I found to the figma file in the library that we're using: https://mhnpd.github.io/react-loader-spinner/docs/components/oval (feel free to make another suggestion if there's something you like better in that library @a-chappelear )

**Comment by a-chappelear** [comment]
Thanks works @bgantick !

**Comment by drew-usds** [comment]
@bgantick @a-chappelear used the live editor to enter some USWDS colors. Could use this as a starting point.

```
<Oval
  height={60}
  width={60}
  color="#2378c3"
  wrapperStyle={{}}
  wrapperClass=""
  visible={true}
  ariaLabel='oval-loading'
  secondaryColor="#aacdec"
  strokeWidth={8}
  strokeWidthSecondary={8}

/>
```

![Screen Shot 2022-08-15 at 3.30.12 PM.png](https://images.zenhubusercontent.com/5ff50e49f74e134e95117280/ff354f00-b303-46ce-9e31-e099c46ba579)

**Comment by bgantick** [comment]
Awesome. I opened an initial PR (#6398) to update the styles. We'll do more normalizing as part of #4790.
