### ISSUE TITLE
Indiana - Ready to receive messages in PROD

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6175]
## Problem statement

Indiana is ready to receive the messages in PROD. Can Reportstream please stop the Test feed.

## What you need to know
We are still seeing messages in the test folder as of today 7/19 3:20 PM.

## Acceptance criteria

User stops receiving messages in the test folder and starts receiving in PROD. 

## To do

Let the client know when completed.

**Comment by sarahnw** [comment]
@oslynn confirmed they're in prod today. closing

**Comment by oslynn** [comment]
This ticket is closed.  All done.
