### ISSUE TITLE
Integrate feature flags with nav items and routes

### ISSUE THREAD

**Issue by doug-s-nava** [CDCgov/prime-reportstream#6177]
## Problem statement

As a report stream experience developer I would like to be able to easily control access to routes and nav items via feature flags.

Feature flags on the report stream are flexible, but largely serve to restrict/grant access to routes or add/remove items to the main nav. Since this is the main use case for feature flags it makes sense to build a system that will allow for automatically adding nav items and routes when adding a feature flag.

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] each feature flag will optionally be able to be configured to activate routes and add nav items, without any one off implementation for the particular feature flag
- [ ] refactoring existing feature flags to use this configuration, and removing redundant code

## To do

- [ ] ...

**Comment by kevinhaube** [comment]
This effort is being prioritized and executed as #7390 and #7546
