### ISSUE TITLE
Greenlight Urgent Care - Confirm "auto pull" still working

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6189]
## Problem statement

Greenlight recently closed their Baton Rouge location and wanted to confirm that their Covid information is still being automatically sent to the appropriate agency.

## What you need to know

Name of the facility- Greenlight Urgent Care
Address of the facility- 10330 Airline Hwy, Suite B8, Baton Rouge, LA 70816
State of the facility- LA
Date of facility closure- 5/30/22
Contact: Randee LeMay - randee@greenlightuc.com

## Acceptance criteria

- Confirmation that their data has been sent to appropriate agency even after their facility closed on 5/30/2022.

## To do

- Review that the above facility's log and check that no data is outstanding and/or not sent to appropriate agency upon closure of their facility.

**Comment by sliu1000** [comment]
Sent user email stating the last day reports received from Greenlight was 5/2/2022. Will wait for confirmation from user prior to closing out this ticket.

**Comment by sarahnw** [comment]
I think it's been long enough and we can close this.
