### ISSUE TITLE
DE ELR Issue- Ordering Provider missing- resend from 7/12 to date

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#6197]
We are receiving ELRs from Milwaukee Brewers (MSH3/4 listed below) through Prime. The ELRs have no ordering Provider. Please correct this and resend all messages from 7/12/2022 to date.  
 

Milwaukee Brewers LP^52D2188931^CLIA-CDC PRIME - Atlanta,^2.16.840.1.114222.4.1.237821^ISO

**Comment by jorg3lopez** [comment]
Any message_id for this one, or a report_id?

**Comment by sliu1000** [comment]
Emailed user to see if they could provide the messageids.

**Comment by Adrian-Brewster** [comment]
Thanks @sliu1000 Let us know when you receive the message ID.  I am going to move this to the icebox until we have that.

**Comment by shy2cdc** [comment]
`ef86038c-d920-4164-baa9-4c2f438b0b1b

f8626cda-0183-4dec-9ac0-cc232c7bf1c7`

**Comment by sliu1000** [comment]
Per User, please see the message ids:

`ef86038c-d920-4164-baa9-4c2f438b0b1b`
`f8626cda-0183-4dec-9ac0-cc232c7bf1c7`

The user is requesting to correct and resend all messages from 7/12/2022 to date.

**Comment by jorg3lopez** [comment]
I'm on it, I'll have an update soon.

**Comment by jorg3lopez** [comment]
#### Update:

imagemover schema blanks out ORC-12-2 and ORC-12-3. OTC data was being submitted with the patient's name under those fields so imagemover requested for those fields to be blanked out in order to prevent a PHI/PII leak.

---
The issue with this is that test results without ORC-12-2 and ORC-12-3 fail DE's system. Due to these findings, we should reachout to both parties and make them aware of the situation.

**Comment by sliu1000** [comment]
@TaneaY Can you please reach out to the the relevant parties as Jorge described above?

**Comment by sarahnw** [comment]
Update @jorg3lopez and I met and here's next steps:
- Sarah will email ImageMover to ask if they've fixed the PII concern with these two fields
- Checking with Joel about other OTC senders and RADX MARS for these fields
- Once we have those answers, we'll reach back out to DE to discuss their requirements on these fields.

**Comment by BerniXiongA6** [comment]
@BerniXiongA6  BX to help contact ImageMover and DE

**Comment by BerniXiongA6** [comment]
@sarahnw to review this before taking action, @BerniXiongA6 can backup if needed - cc: @jorg3lopez

**Comment by BerniXiongA6** [comment]
Hi @sliu1000 could you send me any emails you have regarding this ticket? I don't think I've been on the email chains and I'd like to follow up on it in Sarah's place. I'll need to reach out to ImageMover and Delaware, but in the meantime would like to see any emails you might have on this before I do so. Thanks! cc: @jorg3lopez

**Comment by sliu1000** [comment]
@BerniXiongA6 Hi Berni - no I have not received any other emails from DE. The shared inbox should have all the communications under SLTL Support/Delaware/Support Queue

**Comment by BerniXiongA6** [comment]
Thanks @sliu1000 for clarifying this. I’ll follow up and cc: RS shared email and @jorg3lopez when I do.

**Comment by BerniXiongA6** [comment]
BX sent reply to Chris on 9/2/2022, waiting to hear back from them:

> Hi Chris,
> 
> I'm the new Delivery Manager for ReportStream's Onboarding and Operations team. I'm hoping you can help me out with an open issue concerning a Delaware Dept. of Health ELR issue. 
> 
> In July, they received ELRs from Milwaukee Brewers, which have no ordering Provider. Our engineer, Jorge, investigated this to determine that the ImageMover schema blanks out ORC-12-2 and ORC-12-3 in order to prevent a PHI/PII leak since OTC data is submitted with the patient's name under those fields. The issue with this is that test results without ORC-12-2 and ORC-12-3 fail Delaware's system. We wanted to make you aware of the situation and to find out whether there has since been a fix on your end? We're happy to reach back out to Delaware with any updates or insight you're able to share with us.
>  
> These are the Message IDs:
> ef86038c-d920-4164-baa9-4c2f438b0b1b
> f8626cda-0183-4dec-9ac0-cc232c7bf1c7
> 
> Thank you so much.
> 
> Best,
> Berni

**Comment by shy2cdc** [comment]
From Chris Cash - chris@witsmd.com 9/12 at 11:30am

Hi Berni,

Sorry for the late reply (I was out last week) - we're sending these as the orderingProviderLname and orderingProviderFname fields; are these blank for these records? If they are blank, is there any data populated for the orderingProviderNpi field?

Thanks,

Chris

**Comment by shy2cdc** [comment]
@jorg3lopez Please see email from Chris Cash below. 

Hi Jorge,

Yes, those fields are good to go now (no PHI, healthcare provider/physician's information when it's available; for OTC results these fields are blank); it was addressed on our side in November last year, so anything sent from December 2021 on should have non-PHI data for those fields.

Hope that helps,

Chris

**Comment by BerniXiongA6** [comment]
@jorg3lopez @BerniXiongA6 create new ticket "allow for ORC-12-2 and ORC-12-3 to not be blank in Imagemover's schema" -- can close this ticket.
