### ISSUE TITLE
ARCpoint Labs - Client Needing Onboarded with ReportStream for COVID State Reporting

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#6205]
**Lynn DiPlacito <lynn.diplacito@healthcareintegrations.com>**

Please use my calendly link to set a meeting time/date:

https://calendly.com/lynn-diplacito

Thu 7/21/2022 4:00 PM

Jessica:

Thanks for your response.

I was able to visit with Adrian today and get some clarification regarding our initial request. We are transitioning employees and there was some confusion on what was required on our end.

We have already completed the onboarding with Report Stream - as Healthcare Integrations. According to Adrian, when we bring on new clients, we do not need to complete the onboarding process again.

For the new Clients, we need to work through Joel Biskie to make sure the messages we’re sending through include the correct mapping so that each facility’s CLIA number is included properly for each State and the results are associated with the correct facility, so that we don’t risk any of our clients facing fines from a specific State for not reporting results.

I believe the next step in the process that we need to complete is to set up a meeting with Joel or if he can email us to let us know how to set up the channels for a new Client, that would be extremely helpful.

ARCpoint's client would be focusing on Florida (FTL = Fort Lauderdale) as quickly as possible, with West Palm Beach (WPB), FL and CA (SFS = Santa Fe Springs) next.

We are wondering how quickly we would be able to get reporting to FL up and running? Their client is hoping for asap, as soon as a week or so.

Below are the answers to your questions:

- What is your expected message volume? 
              Florida:
              FTL previous 6 months – 759
              WPB previous 6 months – 14,871

- Are you currently reporting to any other states outside of Florida? 
              California:
              SFS previous 6 months – 7,740

- What is your current process for reporting COVID-19 data? 
              WPB & SFS – HL7 from previous software platform to the state
              FTL – CSV fax to the state

**Comment by sliu1000** [comment]
@jbiskie  Hi Joel, what needs to be done to get Arcpoint onboarded?

**Comment by GilmoreA6** [comment]
Research: Healthcare Integrations is a data aggregator that provides data transport for clients by creating Mirth Connect interfaces. We are already receiving data from HC Integrations for their client ProPhase Diagnostics and sending to PDHs in prod. They have a new client they would like to add - ArcPoint Labs. They will send data to FL and CA. 

Needs: 
We need a CLIA for Healthcare Integrations for CA. (currently they do not have one even though they are sending to CA?
Decide if we need to validate data for new clients of data aggregator. The source data is different and they will be sending on different Mirth Channels (interfaces) even though they will be sending to the same endpoint

**Comment by GilmoreA6** [comment]
Ellaison.Carroll@cdph.ca.gov - Will provide CLIA for HC Integrations

**Comment by GilmoreA6** [comment]
sent email to HC Integrations asking for sample messages to start process.

**Comment by oslynn** [comment]
2022-08-26.  Emaile Anthony and Lynn asking them to send me sample hl7 message for validation.

Anthony, Lynn,

I am picking up the ticket regarding your client "ARCpoint Labs - Client Needing Onboarded with ReportStream for COVID State Reporting" to report to FL and CA.  Do you have the Sample HL7 file for validation?  After that, I will validate with those STLTs.

Best regards,
-Ott S
CDC SW Eng.

**Comment by oslynn** [comment]
2022-08-26 latest email to Anthony:

Anthony,

The sample file that you sent is so simple and contains no message data.
When I ran through ReportStream for validation, it doesn't produce any output.
Do you have another sample file that have message data and without PHI/PII?

Very respectfully,
-Ott S
CDC SW ENG.

**Comment by BerniXiongA6** [comment]
Updated 9/8/2022:

> Ott,
> 
> Sorry it has been a minute we are focusing on other issues first since ARCpoint is just not quite ready for it just yet. We are still planning on working on this but they have to get other items done first.
> 
> Thank you,
> 
>
> Anthony Millan
> Integrations Specialist
>

**Comment by brandonnava** [comment]
@oslynn Have ARCpoint fully onboarded yet?

**Comment by oslynn** [comment]
2023-01-25.  Checked with HCHealthcareIntegration, Anthony, and he told me that ARCPoint Labs is not ready, yet.  As soon as, they are ready.  He will reach out to us.  Therefore, I will put this ticket in the O&O backlog for now.

**Comment by LaFreda1** [comment]
LaFreda reached out on 3/1/23:
Hi Anthony, 
I hope this email finds you well. I am writing to request an update on the status of ARCpoint Labs onboarding to Report Stream. We are excited to have ARCpoint Labs join our platform, and we want to ensure that the onboarding process is going smoothly. I look forward to hearing from you soon!



Best,
LaFreda

**Comment by LaFreda1** [comment]
Response on 3/1/23:
Good Morning LaFreda,

I will ask to see where they are. I know they are finishing up the portal and that is their main focus right now. I will reach out when I know more.

Thank you,
Anthony

**Comment by oslynn** [comment]
@LaFreda1 @brandonnava.  ARCPoint Labs has already been onboarded via Healthcare Integration.  I have already onboarded Healthcare Integration and in production for a while, now.  Therefore, this ticket is done.  It can be closed.
