### ISSUE TITLE
CO - ELR Message error to DB

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#6219]
From: cdphe_elr@state.co.us

This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the message into the database due to the following reason:
**************************************************
The conversion of a varchar data type to a datetime data type resulted in an out-of-range value.

**************************************************
Common causes for the failure to write a message to the database include the following:
 - The message contained an end-of-line character in the middle of the record.
 - The message contained a value that was incompatible with the field's datatype (e.g., an invalid date or a string where there should be a date).

Message ID: `AEC70DFB-50CE-485C-AD23-E8C4E9136742`
Received by: CDPHE ELR Onboarding
Received on: 2022-07-23 07:30:26
File source: CDC PRIME
File name: covid-19-e93414a5-4446-410e-84c8-2c6269b762ff-20220723073027.hl7

Please review, correct, and resubmit the message.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Describe the bug**
Message error not reaching data base

**Expected behavior**
Message sent without error for reporting/resubmission

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the message into the database due to the following reason:
**************************************************
The conversion of a varchar data type to a datetime data type resulted in an out-of-range value.

**************************************************
Common causes for the failure to write a message to the database include the following:
 - The message contained an end-of-line character in the middle of the record.
 - The message contained a value that was incompatible with the field's datatype (e.g., an invalid date or a string where there should be a date).

Message ID: 90829E4C-0669-4E2E-9D82-23B6CB5BC05C
Received by: CDPHE ELR Onboarding
Received on: 2022-07-29 13:30:21
File source: CDC PRIME
File name: covid-19-feb977ec-d2c6-4383-9dd9-2f1cdd2b15b0-20220729133022.hl7

Please review, correct, and resubmit the message.

**Comment by sliu1000** [comment]
@BerniXiongA6 @sarahnw 

Over the weekend we received 44 error messages from Colorado. "Error: Missing or Invalid Observation ID". I will add all the message ids in a separate comment.

**Comment by sliu1000** [comment]
-----Original Message-----
From: cdphe_elr@state.co.us <cdphe_elr@state.co.us> 
Sent: **Sunday, July 31, 2022 9:32 PM**
To: Report Stream (CDC) <reportstream@cdc.gov>
Subject: [CDPHE ELR Onboarding] Error: Missing or Invalid Observation Id

This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

**Issue Report:** The record submitted contained the following **invalid observation identifier**s: 
  - 95409-9
  - 30525-0

Every record submitted must have at least one observation identifier recognized as valid by CDPHE ELR. (For HL7-formatted files, the lab result must be uniquely identified as a LOINC code in OBX 3.1 in the Order Observation group.)

Common causes for a missing or invalid observation identifier:
 - For HL7 files, the record is missing an OBX segment or is missing a value in OBX 3.1, or the OBX 3.1 value provided is not recognized by CDPHE ELR (i.e., is not a recognized LOINC).
 - For flat files, the record contains an escaped (\) character, or the fields in the message do not match Colorado's standard flat file format.

Message ID: `D80D405B-BB71-3388-B93B-241B9FA9DAC9`
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Please review, correct, and resubmit the message.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by sliu1000** [comment]
-----Original Message-----
From: cdphe_elr@state.co.us <cdphe_elr@state.co.us> 
Sent: **Sunday, July 31, 2022 9:32 PM**
To: Report Stream (CDC) <reportstream@cdc.gov>
Subject: [CDPHE ELR Onboarding] Error: Missing or Invalid Observation Id

This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

**Issue Report:** The record submitted contained the following **invalid observation identifiers**: 
  - 95409-9
  - 30525-0

Every record submitted must have at least one observation identifier recognized as valid by CDPHE ELR. (For HL7-formatted files, the lab result must be uniquely identified as a LOINC code in OBX 3.1 in the Order Observation group.)

Common causes for a missing or invalid observation identifier:
 - For HL7 files, the record is missing an OBX segment or is missing a value in OBX 3.1, or the OBX 3.1 value provided is not recognized by CDPHE ELR (i.e., is not a recognized LOINC).
 - For flat files, the record contains an escaped (\) character, or the fields in the message do not match Colorado's standard flat file format.

Message ID: `AEA6118C-B69C-355F-906A-22D6ACB35366`
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Please review, correct, and resubmit the message.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
Message ID: A2344C86-D849-4FCD-BE32-3B8E42D038F6
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: C7FA0B07-E95C-3983-8B8B-26A5932693BE
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 4C5CF70E-04D7-3723-858B-5C6147D8FA7B
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 3B4D4B29-72FF-3177-AE69-A4F8BF620FD3
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: A11752F6-A6E2-4ACD-AA75-CA97CBF5B68A
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 7F424B21-D201-479A-AA25-D8329E7B69FB
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 7F424B21-D201-479A-AA25-D8329E7B69FB
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 5316DDCA-4F0B-3769-8432-7F37626B323E
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: EADFEC26-3D66-3700-B405-6A3747A341C6
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7


Message ID: 476E37E2-ADA3-4609-9CC2-D0921FCF52EC
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 78D0B751-6D2D-461B-8E41-9ABD719AC381
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7


Message ID: CA197D14-340E-37F6-87DE-79DC7C2CA7BD
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 360B118E-0563-3CF8-B6AB-40133B12390E
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 10299B01-2CBE-3DD3-B880-CA002BB61E3C
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 655D4BD5-1CB7-4841-AF9D-0F71E7C0646C
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 9E9EE5D3-54E2-4D29-9AD8-465BFC55E30E
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 16B57B3C-25AF-464E-A349-0236982695A2
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7


Message ID: F5DE4CE0-1443-49DB-B992-1311BCE94869
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 075D1928-CCCD-4F29-911F-2A70350B342C
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 4C10C450-EFB2-3256-8351-65C98CF41CD2
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: C2F35FEC-AF96-3047-998E-7A24E9355569
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 785976A8-8612-34F7-9F20-A6C4A8FC396F
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: C895DB26-5444-3658-934E-C6026A4620AE
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: F4C4252A-B2C2-39E5-BFCC-62746153E6D1
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: ABB299AB-176C-3349-B991-52405D00EE59
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: A7273367-D358-4B3A-92C5-A7914F465A5A
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 4A98299E-96E3-4CF5-A383-888B06143057
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: B79598A7-E6A8-36DF-8E99-31C68C2B9300
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 15182633-64C8-4BAA-99D0-9B694F86C70C
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

**Comment by shy2cdc** [comment]
Message ID: 8D595249-B88B-3E0C-95C5-4EF8D40DB2B8
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 66A66D22-6181-32A5-9874-5E388E6BF935
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: F5CF769A-EA9F-3658-A8A8-33912FB16177
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 0F1BFE68-EAB8-4F17-9105-EE93CA4C1212
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: A8459AE6-250C-3E0A-AB87-F019D4196285
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: BF3B2765-7EA6-4D99-B814-A2D468641121
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 887B6FEC-6096-4A8F-BE06-461CC1480FB2
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: A6880715-D501-4551-8FBA-7572800F4CE7
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 6AFF4343-46C6-45E7-BAB6-A518F9A4F6C2
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 07EE3143-911F-38FA-AEDD-AA38F809BC96
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 0228B370-77A8-3519-814F-CC9331AF43D1
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 9BC17E73-F829-3141-9934-26081CF273A3
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7


Message ID: C3CFB552-8537-398D-9A87-0FCEF01A567F
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 28BA8B94-7B86-341E-B555-741D3CDA6799
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7


Message ID: EE7225CF-6333-4FE9-A8D2-D48B0E0DC66A
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: 6F8EC035-E397-3036-A31F-AF775F9E3633
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

Message ID: FDAE52D0-BBAC-4D49-B661-5C066734036B
Received by: CDPHE ELR Onboarding
Received on: 2022-08-01 01:30:47
File source: CDC PRIME
File name: covid-19-fc822788-b4ff-45bd-9d49-dea87294fac9-20220801013048.hl7

**Comment by jbiskie** [comment]
Emailed follow-up to cdphe_elr@state.co.us. These are Cue messages that went to the secondary feed.

First 2 appear to be bad DOBs.

Remainder from 8/1 appear to be ok. Asked for assistance with tracking down what the issue might be.

**Comment by jbiskie** [comment]
From CO DPH:

Thank you for checking on these error messages.  The first two were generated from our Onboarding system, which is used for testing.  Given that those were test transactions, I do not think that we need to worry about them.  We could work with how these errors are sent.  We currently have the error messages sent to [Reportstream@cdc.gov](mailto:Reportstream@cdc.gov).  We can add additional email addresses or different addresses for the test environment and the production environment.  Let us know if you would like to make that change.

For the third transaction, you are correct 95409-9 is a valid reportable LOINC code that is now listed on our system.  If the file were submitted today, it should pass.  Unfortunately, our system only holds on to 21 days worth of files, so this file will need to be resubmitted.

**Comment by jbiskie** [comment]
Further conversation with Nancy Kesco:

> You can tell where the message originated from the "Received by:" line.  As I looked at it just now, all three of these errors were from the test environment.  So, you really do not need to resubmit any of them.

`Received by: CDPHE ELR Onboarding`

Followed up with Sharon so we know what to look for on these now. Per Nancy we don't need to resubmit. Closing ticket.
