### ISSUE TITLE
LA Mobile - HL7 Integration - Review

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6224]
LA Mobile has provided a HL7 file with no PHI for review.

Per User:

Apologies for the delay. I was out of town and just got back. We will be reporting in various states including: CA, TX, and FL. 

I am available any time this week. We had a call with some programmers and they told us to create some HL7 files for you and would let us know where to send them but have not gotten back to us. 

Please let me know when we can get on a call to finalize the HL7 integration.

Best wishes,

Eric K.
Mobile COVID Testing
By LA Mobile Labs, LLC
Phone:      (310) 361-5457
Direct:      (310) 361-5339 ext. 1
Cell:         (310) 871-1408
Email:       Office@lamobilelabs.net
Website:   www.LAmobileLabs.net

Attached file Sample_HL7_2_5.HL7 : [https://app.zenhub.com/files/304423150/c6213063-5198-4e47-8676-785517f5c6b0/download](https://app.zenhub.com/files/304423150/c6213063-5198-4e47-8676-785517f5c6b0/download)

**Comment by oslynn** [comment]
Email the analysis' errors result and action to Eric:
https://outlook.office365.com/mail/inbox/id/AAQkADY2ODFiNTg0LWYyZTItNDc0Ny1hNTg4LTdhYzAzOWVmYTczMgAQADBEhdYqy0NuluFw6lHDWU4%3D

**Comment by sliu1000** [comment]
@oslynn @BerniXiongA6 Eric from LA Mobile is saying that he never received a response on his files.  I don't see an email in the look provided above. Can you please forward the email to me.

**Comment by BerniXiongA6** [comment]
Updates 8/17: Eric from LA Mobile has revised the HL7 file and sent it over. @oslynn to review.

> Hi Ott,
> 
> Please see attached revised HL7 file. Let me know if you have any questions or changes.
> 
> Please confirm receipt of this email.
> 
> Best wishes,
> Eric K.
> 
> Mobile COVID Testing
> By LA Mobile Labs, LLC
> Phone:      (310) 361-5457
> Direct:      (310) 361-5339 ext. 1
> Cell:         (310) 871-1408
> Email:       Office@lamobilelabs.net
> Website:   www.LAmobileLabs.net
> 
>**

**Comment by BerniXiongA6** [comment]
@oslynn following up on this -- please check your Outlook email, thanks!

**Comment by oslynn** [comment]
2022-09-02.  Completed validation and send back result to Eric.

Eric,

I ran the Sample_HL7_2_5_08172022.hl7 through our ReportStream for validation check.  Everything is good except OBX-17 (Test_Kit_Name_ID).  Here is the result.

Invalid field Test_Kit_Name_ID (test_kit_name_id); please refer to the Department of Health and Human Services' (HHS) LOINC Mapping spreadsheet for acceptable values.


Question to you LAMobileLabs:


    Is OBX-17 "flat^q7^q7^QUANTSTUDIO7^^^2.68" Test_Kit_Name_ID that you are going to use?

Very respectfully,
-Ott Sathngam
CDC SW ENG.

**Comment by BerniXiongA6** [comment]
Update 9/8/2022: BX followed up via email with Eric and Malay / LA Mobile Labs. Awaiting reply. cc: @oslynn 

> Hi Erik and Malay,
> 
> I'm the delivery manager of the ReportStream Onboarding and Ops team, and I'm following up on the pending question we have for LA Mobile Labs:
> 
> Per our engineer, Ott:
> 
> We ran the Sample_HL7_2_5_08172022.hl7 through ReportStream for validation check. Everything is good except OBX-17 (Test_Kit_Name_ID). Here is the result:
>  
> Invalid field Test_Kit_Name_ID (test_kit_name_id); please refer to the Department of Health and Human Services' (HHS) LOINC Mapping spreadsheet for acceptable values.
>  
> Question for LA Mobile Labs:
>  
> 
>     Is OBX-17 "flat^q7^q7^QUANTSTUDIO7^^^2.68" Test_Kit_Name_ID what you are going to use?
> 
> 
> Let us know if you need further clarification on anything.
> 
> Best,
> Berni
>

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 keep an eye on this -- in contact with Eric

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 reached out to Eric and Malay again today to get a status update. Awaiting reply.

**Comment by LaFreda1** [comment]
@sliu1000 can you have someone on your team reach out to LA mobile to see if they would like to continue onboarding? Thanks!

**Comment by wcollin89** [comment]
@sliu1000 @TaneaY I have reached out to the POCs for LA Mobile Labs to follow up on their interest in onboarding.

**Comment by LaFreda1** [comment]
Closing due to no response from the sender.
