### ISSUE TITLE
Neurolab - Validation Issues - OBX 5.1 and OBX 5.2

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6226]
From Asenath.Onderi@dshs.texas.gov

During validation , the following issues were identified R537889
SEGMENT	
- For AOEs 

REMARK
- Please update OBX 5.1 and OBX 5.2 
    - Y^Yes^HL70136
    - N^No^HL70136

For pregnancy status the acceptable values are;
SNOMED-CT Pregnancy Status: 
• 77386006 - Not Pregnant 
• 261665006 - Unknown 
• 276727009 - Null 
 
The 2nd message passed validation. Please make the above correction and I will complete an end to end test and move facility into production for COVID.

**Comment by oslynn** [comment]
I sent one wrong message (covid-19-72b459d1-c9e3-49b8-876e-b914b18bb71d-20220720213102.hl7) to TX which the first message that caused error.  I emailed to let Asenath know already.
