### ISSUE TITLE
NJ - ProPhase Failed messages

### ISSUE THREAD

**Issue by jorg3lopez** [CDCgov/prime-reportstream#6231]
NJ reached out to us with a list of messages that failed. The messages are coming from ProPhase. Initially, these messages were added to ticket [#5537](https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/5537), and it was believed that they had failed due to the Ordering Facility Phone Number (ORC23) having an extension number. Unfortunately, this is not the case, it is unclear why they failed.

---
We need to reach out to NJ and get more information on the reason they failed. Below are the message_ids and file names:

#### covid-19-6d03f278-eaa4-4b44-b02f-86b82e1c823c-20220527134110.hl7
`20220526224158`

#### covid-19-448ea83a-6159-4703-bd8f-5ee1d675721b-20220528134046.hl7
`20220527134030`

#### covid-19-5a82161f-ac99-4c93-a695-b19590101dfc-20220603134128.hl7
`20220602152920`

#### covid-19-0b9e5876-2837-4f96-988f-9a955d59b948-20220603134117.hl7
`20220504123730`
`20220513090915`
`20220519130445`
`20220519211504`
`20220520145454`
`20220520172542`
`20220525125945`
`20220526095717`

**Comment by BerniXiongA6** [comment]
8/1: Let's flesh out details for this before moving forward @sarahnw @BerniXiongA6

**Comment by jorg3lopez** [comment]
@oslynn This is another ticket from ProPhase

**Comment by BerniXiongA6** [comment]
Did this slip through the cracks or is this possibly a duplicate? Any ideas @jorg3lopez @oslynn before I move this out of O&O backlog?

**Comment by oslynn** [comment]
May I investigate this issue I will let you know?  Instead of asking ProPhase to resend messages without Extention, we may be able to do something in RS to suppress phone EXT.

**Comment by oslynn** [comment]
2022-09-12.  Reached out to NJ for detail regarding error messages.

Dear: Mr. Firkser,

In regarding to issues with the following message_ids, would you please provide me detail error messages?  I would like to investigate and fix them accordingly.

20220526224158

20220527134030

20220602152920

20220504123730
20220513090915
20220519130445
20220519211504
20220520145454
20220520172542
20220525125945
20220526095717


Very respectfully,
-Ott Sathngam
CDC SWE

**Comment by jorg3lopez** [comment]
#### Update:

Prophase is still in onboarding phase. We can move this ticket to close.

**Comment by shy2cdc** [comment]
Email below is from Mark Firkser:

What files were these in?

**Comment by shy2cdc** [comment]
From Mark Firkser:

Attached are emails with the reasons why these messages failed.  These are from back in June and are from Production.

**Comment by oslynn** [comment]
2022-09-15.  Got with Emma Stephenson (SR).
"=== here message ===
Emma Stephenson (PST, she/her)
  4 minutes ago
Thanks!
I’m going to rely on 
@Zedd Shmais (DFW, he/him)
 to double-check me here, but I believe that we can ask the facility to update their ordering provider phone # and facility phone #. After that, we should be able to use these message ids to resend the affected tests. The one that’s a little more concerning is the observation method identifier truncation - I don’t know for sure, but I think that must be the device/specimen type combination. Not sure what we can do to truncate that appropriately
" ==== my response =====

Oh, yes.  
That would be very nice.  I will make sure that ReportStream will truncate those longer fields.  Thank you very much Emma.

**Comment by oslynn** [comment]
2022-09-16.  According to Messaged from Emma Stephen.  SimpleReport will get with senders to fill in those missing fields as in the attached file and will resubmit those messages accordingly.  Also, Zedd Shmais, will resubmit those messages with too long string to ReportStream (currently, RS is ready to truncate the OBX-17-1 as those messages contain).  I will move this ticket to ready to close column.

**Comment by shy2cdc** [comment]
Email from Mark:

We’ve reviewed your test files, and your updated issues spreadsheet is attached.

Please include ProPhase’s name in the file name so these are easier to identify.

**Comment by shy2cdc** [comment]
@oslynn Email from Mark

We’ve reviewed your latest file and your updated issues spreadsheet is attached.

 

 

Thank you,

Mike Firkser

Technical Lead - NJDOH ELR Team

NJELR.Admin@doh.nj.gov

**Comment by BerniXiongA6** [comment]
@oslynn will look into this and update ticket cc: @BerniXiongA6

**Comment by oslynn** [comment]
2022-10-11: message need to resend:
Following message_id from ProPhase:
20220526224158

20220527134030

20220602152920

20220504123730
20220513090915
20220519130445
20220519211504
20220520145454
20220520172542
20220525125945
20220526095717

'===============
message_id in files below are from SimpleReport:
  Error in Rhapsody Route in PRODUCTION.eml
  Error in Rhapsody Route in PRODUCTION (1).eml
  Error in Rhapsody Route in PRODUCTION (2).eml
  Error in Rhapsody Route in PRODUCTION (3).eml

**Comment by oslynn** [comment]
2022-10-11: I checked the database.  None of them has been resubmit yet.  I will following up with ProPhase and SimpleReport to see the status.

**Comment by oslynn** [comment]
2022-10-12: Reminded ProPhase (emailed Anthony) to resend the following message again:

'============== From ProPhase =========================================
I requested ProPhase (Anthony) to resend these messages + the missing fields. When I checked
the database (table: covid_result_metadata), I don't see any of them resend yet.

Message_ids:
20220526224158
20220527134030
20220602152920
20220504123730
20220513090915
20220519130445
20220519211504
20220520145454
20220520172542
20220525125945
20220526095717

**Comment by oslynn** [comment]
2022-10-12: Reminded SR (Emma) to  to resend the following message again:

Messages inside the following file:
[https://app.zenhub.com/files/304423150/20686683-2f3e-48ac-b4f8-6c34994c0eaf/download](https://app.zenhub.com/files/304423150/20686683-2f3e-48ac-b4f8-6c34994c0eaf/download)

**Comment by oslynn** [comment]
2022-11-12: Got response back from SR.

They requested senders to filled in those missing fields and resend those message to RS.  However, none of sender did the resend.  This need to discuss in 16 min standup.

**Comment by shy2cdc** [comment]
Email from Anthony:

Good Afternoon Ott,

I reached out to ProPhase and they requested Any way to identify the messages by a different value? If I'm sending from the LIS again I need PID4 or an OBR or orc 2 value.

Is there anyway to get this information from NJ to be able to reprocess the messages? Thank you for your help.

Anthony,

**Comment by shy2cdc** [comment]
Email from Anthony:

Good Morning @oslynn ,

Thank you for the information. The question I was asking about was that you requested to resend certain messages from back in May. Our company only holds data for 30 days like yours and I sent the list to ProPhase to resend from their LIS. I copied what they requested that they would need more information in order to pull from the LIS and resend the messages. I did not know if you could find the requested information out? Thank you for your help and response.

Anthony,

**Comment by oslynn** [comment]
2022-10-14: ProPhase's client can't use MSH-10 to locate message to resend.  They can only use PID4 or OBR2 or ORC2 to locate message in their system.  I emailed NJ to provide those value for each message.  Therefore, I can give to ProPhase.

'====
Good morning, Mike,

 

They are in the following files:

covid-19-6d03f278-eaa4-4b44-b02f-86b82e1c823c-20220527134110.hl7
20220526224158

covid-19-448ea83a-6159-4703-bd8f-5ee1d675721b-20220528134046.hl7
20220527134030

covid-19-5a82161f-ac99-4c93-a695-b19590101dfc-20220603134128.hl7
20220602152920

covid-19-0b9e5876-2837-4f96-988f-9a955d59b948-20220603134117.hl7
20220504123730
20220513090915
20220519130445
20220519211504
20220520145454
20220520172542
20220525125945
20220526095717

 

Thank you for your help,
-Ott Sathngam
CDC SWE

**Comment by oslynn** [comment]
2022-10-20 Mike can't find those message in their system any more to get information for ProPhase.

'=== email ===
DOH-ADMIN NJELR [DOH] <NJELR.ADMIN@doh.nj.gov>
**I cannot find those files or order numbers in our system.**

Please note, @Boyd-Lee, Joyce [DOH] is your point of contact for Phase 2 testing.
 
Thank you,
Mike Firkser
Technical Lead - NJDOH ELR Team
NJELR.Admin@doh.nj.gov

Therefore, I will close this ticket for now.

**Comment by oslynn** [comment]
Mike (NJ) can't find those message in their system any more to get information for ProPhase.
