### ISSUE TITLE
`AuthenticationStrategy.authenticate()` returns wrong Okta organization name

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#6263]
> `Experience` label is present so we can list this as a blocker for another ticket on our ZenHub board

**Describe the bug**

When authenticating with okta, the AuthenticationStrategy returns the wrong parsed Okta organization name.
Input: DHxx_yyy
Output: xx_yyy
Expected: xx-yyy

**Impact**

We cannot implement the `/waters/delivery` endpoints for STLT features.

**To Reproduce**

1. Login as a user with a STLT organization group, not as a PrimeAdmin.   Per the example below, I get the failure with a user associated with DHmd_phd.
1. Use Postman (or similar) to call `/api/waters/org/{org.service}/deliveries` (ex. org.service = md-phd.elr)
2. You should get a 401 Unauthorized. Check logs, should be something about mismatched xx-yyy != xx_yyy (for this exact call it's line 77 in `ReportFileFunction.kt`
3. Use Postman (or similar) to call `/api/waters/org/{org.service}/deliveries` again, but with an underscored org name (ex. org.service = md_phd.elr)
4. You should get a 404 Not Found. Check logs, should be something about xx_yyy not being an organization. This failure is on line 73 of the same file.

**Expected behavior**

`xx-yyy` should be returned as the `organizationNameClaim` from the `AuthenticationStrategy` when given an Okta group with the format `DHxx_yyy`

**Screenshots**

This is the code block in question -- see above for line numbers.
![Screen Shot 2022-07-25 at 10.44.02 AM.png](https://images.zenhubusercontent.com/611a907ec3e013d0e33e58a7/0ccc972d-1390-408c-8573-6daf856451bf)

**Comment by jimduff-usds** [comment]
I'll grab this and take it on.

**Comment by jimduff-usds** [comment]
After studying the code, I decided that its likely we can simply change all the _ groups in okta to match the - used in RS Settings.
Note that simple_report has a "_" in both Okta and in RS Settings, however, at the moment the front-end code does not change DHSender settings such as DHSender_simple_report.

So I tested this.   In Staging, I have tested simply changing the group name in okta, eg, from DHmd_phd to DHmd-phd.   This appears to work.

I tested three users:
1. a prime admin
2. a user only with DHmd-phd group.
3. a user only with DHSender_simple_report group

I tested them both before and after making the change from DHmd_phd to DHmd-phd.

In each case, I tested three calls:
1.   attempt to see md-phd deliveries  (after the change, this works for prime admin and md-phd user, fails for the simple_report user)
2.  attempt to see simple_report submissions (after the change, this works for prime admin and simple_report user, fails for the md-phd user)
3.  attempt to see md_phd deliveries (this always fails - no such org!)

Test passed.

Here are the details of how I did this test. 

Here are the three queries I tested:

#### md-phd
`curl -H "authentication-type: okta" -H "Authorization: Bearer $TOK" "https://staging.prime.cdc.gov/api/waters/org/md-phd.elr/deliveries"`
#### simple_report
`curl -H "authentication-type: okta" -H "Authorization: Bearer $TOK" "https://staging.prime.cdc.gov/api/waters/org/simple_report.default/submissions"`
#### md_phd THIS SHOULD ALWAYS FAIL.
`curl -H "authentication-type: okta" -H "Authorization: Bearer $TOK" "https://staging.prime.cdc.gov/api/waters/org/md_phd.elr/deliveries"
`

### How to logout.
Logging out is a pain to really truly force a new login with a different user.  Here's what I did.
a. Logout (`./prime logout`) and
b. logout of oktapreview by going to https://hhs-prime.oktapreview.com/app/UserHome and log out.
c. And  clear browser cache!
d. Log back int as a the different user, using `./prime login --env staging`
e.  grab the token and put it in $TOK
`export TOK=$(cat ~/.prime/accesstoken.json | grep token | cut -d"," -f1 | cut -d":" -f2 | tr -d \")`
f.  Now you are ready to run the three curls, above.

**Comment by jimduff-usds** [comment]
Response to @kevinhaube comment above:

The strange way the HistoryFunction.kt code handles dashes and underscores:

If the group in Okta was ‘DHmd_phd’, then OrganizationUtils.ts changes it, and sends ‘organization=md-phd’.  Then the old HistoryFunction.kt changes it back to DHmd_phd, and compares that to all the Okta groups it finds, once of which is DHmd_phd, so the match succeeds.

If the group in Okta was ‘DHmd-phd’, then OrganizationUtils.ts sends ‘organization=md-phd’.
Then the old HistoryFunction.kt changes it back to DHmd_phd, and compares that to all the Okta groups it finds, once of which is DHmd-phd, so the match FAILS.

The latter is why, when I changed DHmd_phd to DHmd-phd in Okta, it broke the HistoryFunction authentication.

The PR changes the HistoryFunctions.kt auth, so that it is happy with either DHmd_phd _or_ DHmd-phd.  This will allow us to take our time fixing the okta group names in Prod, without having to time it exactly with a PR deployment.

**Comment by kevinhaube** [comment]
@jimduff-usds I'm realizing as I put #6333 up for review (transition off of `History` to `Deliveries`) the original issue of the newer `AuthenticationStrategy` only accepting the exact string match and thus mismatching `DHmd-phd` and `DHmd_phd` would still require a coordinated change of all `DHxx_yyy` groups in Okta during a deployment.

**Comment by bgantick** [comment]
I believe this was fixed in the linked PR

**Comment by kevinhaube** [comment]
@bgantick The `HistoryFunction` PR above only fixes it for `/reports`. The `AuthenticationStrategy` method might still be a concern? Jim's conversion of okta groups to claims strings might fix this?
