### ISSUE TITLE
RS Website - Resources template modification

### ISSUE THREAD

**Issue by a-chappelear** [CDCgov/prime-reportstream#6278]
We'd like to be able to sort the "card" components on index pages that use them into "sections", if possible. 

There are different "types" of guides/documentation on this page and it would be helpful to be able to add section titles, like the below screenshots, in order to better group & sort them.

This may be something needed later on in other index pages (like Support) may want to consider this as something that could be used site-wide.

### Prior Info
- `IACard` and `IACardGroup` already exist, might be a good idea to put the template in with the rest of that code for easy changes in the future
- Our IA rendering philosophy is that templates take collections of `ContentDirectory` (such as `IACardGroup` class obejcts, and elements rendered with data from them should always accept the whole `ContentDirectory` (such as `IACard`)

### Acceptance Criteria
Only need the template/code revised (or the ability to add section titles). Design can then update the titles/content after.

- [x] Template is extracted from `Support` and `Resources`
- [x] Cards/links are able to sectioned into subsets (as seen in screenshot)
- [ ] Make PR with changes to match screenshot

![future_resources-cards.png](https://images.zenhubusercontent.com/5d08f49d32d94d3393126018/9648d031-d1a1-45cd-bc5e-8c3c2d6bccd4)

**Comment by a-chappelear** [comment]
cc @BerniXiongA6 @drew-usds

**Comment by kevinhaube** [comment]
Quick engineering notes:

This ticket is a great opportunity to refactor the template out from `SupportIndex.tsx` into an actual reusable template, like `<IACardTemplate directories={directories} />` where `directories` is _currently_ only an array of `ContentDirectory`

From there, we can make the template accept both `ContentDirectory[]` and the new `Map<string, ContentDirectory[]>`. We can conditionally implement a sectioned or unified card rendering loop with easy `instanceof Map` check.

Lastly, to make it more comprehensible for non-engineers using these tools, we can add this `Map<string, ContentDirectory[]>` as a part of `DirectoryTools` with a method like `makeDirectorySection(title: string, dir: ContentDirectory)` to make creating these very easy.

In the end, we should have two ways of producing a page like this: the current method of supplying a direct `ContentDirectory[]` as we are doing now, or by supplying the new `DirectoryTools.sectionedDirectories`, a map of `string`s and `ContentDirectory[]`s.

**Comment by bgantick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/6278?planning-poker) with ZenHub @doug-s-nava @ahay-agile6 @kevinhaube @sethdarragile6

**Comment by kevinhaube** [comment]
Due to deploy as a part of PR 6430 on Tuesday, Aug 23.

**Comment by kevinhaube** [comment]
Deploy pushed to Aug 25

**Comment by drew-usds** [comment]
@kevinhaube Moved this back to "In progress" ... we're just going to make this change using this same ticket, since the point count/effort is so low. @a-chappelear will make a PR this week.

**Comment by HeatherRienks** [comment]
FYI- the code changes to support this have been merged, however, NO CONTENT structure has been updated.
