### ISSUE TITLE
Hide logs on successful tests

### ISSUE THREAD

**Issue by doug-s-nava** [CDCgov/prime-reportstream#6289]
## Problem statement

As a report stream developer, when running a test suite, I do not want to be distracted by console errors for tests that are passing. In some cases we are running tests that expect error logs, and in these cases the logs are output by the tests, while the tests themselves pass and are running as expected.

## What you need to know

We have, as far as I can tell, three options for approaching this. In order of complexity:

- run tests with `--silent` flag. With this flag, jest will suppress all console logs during testing. see https://jestjs.io/docs/cli#--silent
- mock the console object on all tests to capture logs before they can be output to the screen. This can be done for the entire test suite by introducing a pre-test script, along the lines described here https://stackoverflow.com/a/49591765/5500298
- create our own logger for the application, wrapping `console` whose behavior we can customize. If we want to be able in the future to suppress some logs in production, or hide some logging behavior behind a feature flag / query param, this implementation, in addition to allowing us to suppress logs based on environment without touching test implementations, would be useful.

## Acceptance criteria

When running `yarn run test:ci`
- [ ] all tests pass
- [ ] no error logs are present

Possibly more, if we decide to build a custom logger.

## To do

TBA based on decision on approach

**Comment by TomNUSDS** [comment]
Thoughts:
 - When debugging failures in when a GH action fails, there's a checkbox to show details of error. I wonder if there's some way to tie into this feature?
 - There's a jest way to intercept expected console errors. 
```typescript
jest.spyOn(global.console, "warn");
jest.spyOn(global.console, "error");
```
We could use it for all tests that are expected to issue warning/errors and silence them selectively OR even verify they did generate a console error?

**Comment by kevinhaube** [comment]
@TomNUSDS We have an example of this now in our `useRequestConfig` tests for warnings, I believe. The third, most complex, option brings up something interesting for me -- are there `jest logs` of any kind? It sounds like that's kinda what we're hoping to get out _not_ mocking them...the ability to log things in jest when needed?

**Comment by doug-s-nava** [comment]
* I don't think that github actions will be able to take care of what we're talking about here, since it's internal to testing, but I do owe github actions some research time so now seems like a good time for that
* if we want to go with option two, there are definitely a few ways to accomplish it, either the spy method, or by replacing the global object methods with mocks. I personally don't think that would really matter, but with mocks we'd have a little bit more flexibility I think
* I don't think there are really jest logs exactly, though jest obviously outputs things to the stdout. However, yeah, in any of these three cases we'd probably want to think about how we could disable hiding logs, so that we could use them for debugging purposes. For option 1 it's as easy as removing the flag from the cli command, and for 3 it would be as easy as using `console` instead of the custom logger. For option 2 it'd be a little more complex but not much more, probably just altering the jest setup script to not do the mocks

**Comment by kevinhaube** [comment]
> However, yeah, in any of these three cases we'd probably want to think about how we could disable hiding logs, so that we could use them for debugging purposes

Jest is flexible enough - I think the solution here is to just `spyOn(console, "error")` in the individual tests that affirm negative cases that trigger console.error in our code

**Comment by doug-s-nava** [comment]
i ended up adding `--silent` as a simple solution here. done!
