### ISSUE TITLE
Error and Warning Msgs - Discovery

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6307]
## Problem statement

In order to improve current API error and warning messages, create/run HL7 test cases to get the full list of errors and warnings.

## What you need to know
https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1659379562245/028bbeb7dd7b819298ba1b436703882855bc767f?sender=u3fea607b46e84058d3224917

Here are where the API error/warning messages are generated: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/ActionMessages.kt

Initial list of commonly encountered errors/warnings: https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/doc.aspx?sourcedoc=%7B6327b3dc-2ace-4757-aa62-ab8dcfffb535%7D&action=edit

Presentation on HL7: https://www.slack.com/archives/C024MGSJZ38/p1659722811223229

See field list in Programmer's Guide: https://reportstream.cdc.gov/resources/programmers-guide

## Acceptance criteria

- [ ] A library of test files to trigger errors/warnings (as outlined in docs above)
- [ ] An output of error and warning msgs from the API response from above test files

**Comment by RakshindaAslam** [comment]
cc @bgantick

**Comment by bgantick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/6307?planning-poker) with ZenHub @doug-s-nava @sethdarragile6 @kevinhaube @ahay-agile6

**Comment by bgantick** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/6307?planning-poker) with ZenHub @TomNUSDS

**Comment by sethdarragile6** [comment]
https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7Bf90ae2fb-ec67-4652-8b40-652a21e90e29%7D&action=edit&wdPreviousSession=875e55e3-ee48-4463-b6c1-a3b3d4cf5b99
