### ISSUE TITLE
Investigate/resolve issues with admin org switcher

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#6317]
## Problem statement

Some bugginess has been reported around the admin org selector tool. Reports include the wrong data returning in the UI when visiting the submissions page among other selected org/data mismatches. It would be nice to persist org selection on refresh, to minimize confusion and having to re-select an org, as well as provide some sort of indicator as to what user mode an admin is in (might be good to get design to weigh in).

### Pages to check for parity between selected org and what gets sent to the API

- `/submissions` + detail page
- `/daily-data` + detail page
- `/file-handler/user-upload`
- `/file-handler/validate`

## Acceptance criteria

- [ ] Selected org persists on refresh (stored in state/session)
- [ ] API calls match selected org where appropriate
~~- [ ] It's clear what user mode I'm in when I'm navigating around (sender, receiver, or prime admin)~~ (let's wait and tackle this in a separate card after design has had a chance to go over it)

**Comment by doug-s-nava** [comment]
here's a research doc! will continue with work on harmonizing stored org values between session and state https://cdc-my.sharepoint.com/:w:/g/personal/twq5_cdc_gov/EU4JY2WGuBBKsufbk1rJc0QBepYRI2jFaRnmYZ_ec1rljg?e=OKP8jW

**Comment by doug-s-nava** [comment]
two PRs came out of this directly:
* https://github.com/CDCgov/prime-reportstream/pull/6397
* https://github.com/CDCgov/prime-reportstream/pull/6402

Some points that came up during review:
* we would like to be able to implement a pattern where user state is stored only on app shutdown and read only on app startup, after which the persistent storage is cleared. The reason for this would be security - at this point a user authorized under one organization could discover our storage mechanism and use it to spoof a different organization, gaining access to reports or permissions to upload for a different org. 
* However, this may not really be feasible, as there are valid reasons (and invalid reasons, such as the fact that our rest-hooks based requests rely on session storage atm) that the app may need access to stored values throughout the app lifetime. Ex: persistence of state between tabs
* another point is that we should have persistence of override / log in state between tabs. This would require two things:
    * using localStorage instead of session storage
    * instead of always redirecting users to the login page, drawing on existing stored okta state data to log users in programatically. I imagine the okta library will help a good deal with this.
