### ISSUE TITLE
WA - Duplicate Messages - 101 Messages from ELITEMED Labs included twice in file

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6318]
Received Ticket via Smartsheet ReportStream Service Form from Caroline Thomas at Washington State Department of Health on 8/4/2022 @ 7:43 PM.

## Problem statement 
Potential duplicate messages?

101 messages/control IDs from Elitemed Laboratories included twice in file 7uycso49@cdcprime_testing_20220804151622_339372___neg.hl7

Duplicate messages get stuck in our system and create additional work for our team members. If these are not true duplicates, they need to have unique message control IDs.

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

Message IDs Provided by Client. (I'll look to add the proper message ID code here need to research).

188574+1+20220804, 188583+2+20220804, 188532+3+20220804, 188510+4+20220804, 188517+5+20220804, 188575+6+20220804, 188552+7+20220804, 188502+8+20220804, 188569+9+20220804, 188500+10+20220804

## Acceptance criteria

- Confirm the message ids are duplicate, action correct issue
- If Message Ids are not duplicates will need unique messageid.

## To do

- Prioritize the ticket and assign to Engineer

**Comment by jorg3lopez** [comment]
#### Update:
After investigating the source of the issue, it was noticed that these test results came from simple report (csv uploader). A file containing these test results was submitted three times, this created the duplicates. The same message_id was produced as a result of the same file being submitted on the csv-uploader.

**Comment by BerniXiongA6** [comment]
Update 9/6/2022: BX sent email to Caroline Thomas at WA DOH:

> Hi Caroline,
> 
> We're responding to your service request from August 4, 2022 regarding duplicate messages from Elitemed Laboratories.
> 
> Our engineer, Jorge, investigated the source of the issue. It appeared that these test results came from SimpleReport (via the CSV uploader). A file containing these test results was submitted three times by the sender, which created the duplicates. Therefore, the same message_id was produced as a result of the same file being submitted on the csv-uploader.   
> 
> Let us know if you have any additional questions.
> 
> Thanks,
> Berni
> 

Moving ticket to Waiting for Confirmation.

**Comment by sliu1000** [comment]
Ready to close out per the user:

Hi Berni,

Thanks for the update and for confirming that there was no larger system issue causing the duplicates in this case. We are ready to close out this ticket.

Thanks,

Caroline
