### ISSUE TITLE
Innolitics API Onboarding

### ISSUE THREAD

**Issue by sarahnw** [CDCgov/prime-reportstream#6324]
This is a ticket to track the onboarding for Innolitics

They're sending csv files
They're using a different test kit in the LIVD table to test with while waiting on EUA approval for theirs
It will be an OTC test

Whoever picks this up, I'll add to the email thread with their engineer. It contains their test csv.

**Comment by shy2cdc** [comment]
Sam'an 8/18 2:54 pm 

Hey yall,
Just checking in, any word on where we're at with this?

**Comment by GilmoreA6** [comment]
Received sample file. Validating against schema.

**Comment by GilmoreA6** [comment]
Sent feedback to sender requesting minor updates to example file.
