### ISSUE TITLE
A6 aftermath:  Okta issues

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#633]

**Comment by jimduff-usds** [comment]
Okta user experience issues

- [ ] The "Do not challenge me on this device for the next 12 hours" thing does nothing.  Remove it.
- [ ] I tested this:  No matter how much you use the download site, you always get kicked off after 5 minutes.
- [ ] Access to Staging currently gives access to Prod!   Need separate groups for access to staging/prod/local systems
- [ ] change the timeout.  Yes, FHIR API access has a 5 minute timeout, but that isn't appropriate for user facing tools.

**Comment by mry-usds** [comment]
Do not challenge and timeouts are OBE as the download site is now replaced by the WebReceiver site
