### ISSUE TITLE
CA - Out of state reporting for multiple facilities 

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#6338]
User is asking if it is possible to report with facilities outside of state.

Hi SimpleReport Team,

 

I have a question about a lab from one state reporting test results performed in another state.  We have a lab from Hawaii that will be conducting testing in California on a temporary basis to assist with some events in California.  Can they use SimpleReport?  Hawaii is not one of the states that is live with SimpleReport, but since the testing will be performed in California on California patients, could they register and use SimpleReport for reporting those results to CalREDIE?   

 

I know if the lab was from another state that is live this would not be a problem, but wasn’t sure in this case. 

 

Thanks,

Ellaison

**Comment by BerniXiongA6** [comment]
8/9/2022: I'm watching this one -- I'm working with Charlye Tran (SimpleReport) to answer the question. 

Per Charlye (via email): "Is their CLIA recognized and set up with your systems? Also, would they be using the single entry test results or would they need access to the CSV results uploader as well?"

Awaiting response from Ellaison. Also, invited Charlye to join the CA sync this Wednesday (if she can't join, she'll provide me with updates to share with Ellaison).

**Comment by BerniXiongA6** [comment]
Resolved on 8/10/2022 during call with Cal DOH. Per Brick, there's a workaround for senders to be able to submit out-of-state results, but RS will not route those reports to the jurisdiction. Charlye wasn't present for the discussion, but she agreed that Brick's workaround was correct.
