### ISSUE TITLE
Investigate GHA failure

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#6339]
As a devops engineer I'd like my pipeline to run reliably, including the check for leaked information. Looks like[ this job ](https://github.com/CDCgov/prime-reportstream/runs/7737909360?check_suite_focus=true)is not working properly

**Comment by lucasdze** [comment]
This issue is now fixed by removing argument from the Gitleaks bash script and append the output into a log file

Please see PR #6370

**Comment by lucasdze** [comment]
I Created a new PR #6373 to complete this issue

**Comment by lucasdze** [comment]
Created a final PR [#](https://github.com/CDCgov/prime-reportstream/pull/6381)
