### ISSUE TITLE
ReOpen/Cerner - New Sender Onboarding

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6343]
## Problem statement

Would like to start testing sample files.

## What you need to know

-Have completed a kick-off meeting.  Also, send a "public key", but requesting a "client-id".
-Sender (New Onboarding)

## Acceptance criteria

- Able to start testing their sample file

## To do

- Determine if we need to send the client a "client-id" per their request to start testing sample file.

**Comment by BerniXiongA6** [comment]
8/9/2022: @oslynn has offered to help out with this. Berni can keep informed in case more coordination/outreach is needed. cc: @sliu1000

**Comment by oslynn** [comment]
Emailed to Cerner 2022-08-10.

Good afternoon Nathaniel,

My name is OTT SATHNGAM, I am going to help you get connect and authenticate with ReportStream.  Would you please resend your public key to me and let me know?  My KeyBase Id: oslynn1.  I will add your key to our system and let you know when I am done.



I assumed that you know how to generate a signed JWT (token-signed-secret) key and using curl or PostMan to obtain the access_token from our API endpoint.

There is an example in our ReportStream Programmer's Guide page 10.


Please let me know if you need further help,


Very respectfully,

-Ott Sathngam

CDC SW ENG.

**Comment by oslynn** [comment]
2022-08-12 Completed sender message validation and email back to Natheniel to make correction and send back to me for further validation.

**Comment by oslynn** [comment]
Nathenail decided to use shared key authentication access for now.

**Comment by oslynn** [comment]
2022-08-16.  Following up with Cerner.

Nathaniel,

Please let me know the status of correcting your sample HL7 message and get it back to me for further validation.
Also, I would like to have the list of receiver(s) that you will report to.  Therefore, I can get our system ready to validate your message with them.

Best regards,
-Ott Satghngam
CDC SW ENG.

**Comment by BerniXiongA6** [comment]
Updates 8/16/2022:

> From: Sheley, Tyler <Tyler.Sheley@Cerner.com>
> Sent: Tuesday, August 16, 2022 9:52 AM
> To: Sathngam, Ott (CDC/DDPHSS/OD/HITSSU) <sry8@cdc.gov>; Mays, Nathaniel <Nathaniel.Mays@Cerner.com>
> Subject: RE: Need help with sample files testing Fw: Cerner/ReOpen
>  
> Ott,
> 
>  
> 
> We are currently pausing on all work we are doing with ReportStream.  We have run into some difficulties and are re-grouping to develop a new gameplan.  I will follow up if/when we are ready to proceed.  Thank you!
> 

Will close ticket for now, will update the Sender onboarding tracker with this info. If sender changes mind in the future, we'll create a new ticket. cc: @oslynn @sarahnw

**Comment by rnz6** [comment]
Alex Miller - alex.sneedmiller@reopenlabs.com requested a ReportStream account and API connection. We've followed up with the TOS agreement and asked for a sample file. @BerniXiongA6 

Hello,

I am a Technical Product Manager at a diagnostics company and we are looking to modernize our test reporting. ReportStream appears to be a great solution to a lot of our problems with regards to sending test results to public health offices.

I'm getting some mixed messages from LIS vendors around the stability and usability of ReportStream and our internal software development team has started to build SFTP integration with various public health offices.

I would love to be a part of ReportStream and help contribute data and even core commits if possible to improve the service for everyone involved. 

Would it be possible to jump on a call with someone to talk about the timeline and requirements to get started with ReportStream?

Overall we are currently at ~7k/day. We are building new tests and assays so we expect that number to go up soon.

We are reporting to a handful of states - I think roughly 15 at my latest count automatically. Most of these are via fax or through Cerner's ELR system, which I believe is HL7 files via SFTP. 

We are building our own HL7 file creator program and hope to send HL7 files to states via SFTP as that seems to be the most common way. We do have the capability to send .csv, HL7, or JSON messages as files or via REST or GraphQL API calls.

**Comment by oslynn** [comment]
2022-10-06: Sent ReportStream programmer's guide to Alex Sneed and Forward the email thread to @BerniXiongA6 for setting up the formal onboard meeting with them.

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 will update this ticket with the email exchange with Alex

**Comment by BerniXiongA6** [comment]
Last email reply from BX to Alex on 10/7/2022:

> Hi Alex,
> 
> Thanks for the reply. I've got some answers for you below (highlighted in bold):
> 
> We are currently building out integrations with each state to report test results for COVID and other assays. My understanding is that a lot of states (the ones in blue here) subscribe to ReportStream so that my company only needs to send data to ReportStream, rather than have to integrate with each individual state's system. Am I understanding this correctly? <<< Correct, if your company needs to send COVID-19 test results data to a particular jurisdiction that ReportStream is connected to, then ReportStream would have the capability to route your data to that connected jurisdiction. Therefore, your company would essentially only have to get connected to ReportStream's technology. Some states might still have their own onboarding requirements, but ReportStream would work with your company and that state to ensure we're all aligned on those requirements.
> 
> In addition, I still need to reach out to each individual state to go through their onboarding process, but I wouldn't need to actually send them results directly because I would be sending them to ReportStream. Is that right? <<< Yes, some states might still have their own onboarding requirements, but ReportStream would work with your company and that state to ensure we're all aligned on those requirements since our job is to connect with companies that are sending data and public health agencies that are receiving that data. Again, we're the hub that routes the data between senders and receivers so we would work with both sides to ensure that connection is made both upstream and downstream.
> 
> Do you know if there is a timeline for other pathogens for ReportStream (e.g. Flu, RSV, Monkeypox, etc.)? <<< ReportStream is currently piloting with a large lab and the state of Colorado to allow for full ELR so that we can eventually allow for all reportable conditions to be sent and received. We're hoping to complete that this quarter, but in the event that we aren't able to, we've got MonkeyPox and Flu coming soon. We're happy to keep you informed as we make progress on this.
> 
> Please feel free to reach out if you have any other questions at all!
> 
> Thanks,
> Berni

Email reply from Alex on 10/7/2022:

> Hi Berni,
> 
> Before I involve the rest of my team, I really want to make sure I understand the purpose of ReportStream. We are currently building out integrations with each state to report test results for COVID and other assays. My understanding is that a lot of states (the ones in blue here) subscribe to ReportStream so that my company only needs to send data to ReportStream, rather than have to integrate with each individual state's system. Am I understanding this correctly?
> 
> In addition, I still need to reach out to each individual state to go through their onboarding process, but I wouldn't need to actually send them results directly because I would be sending them to ReportStream. Is that right?
> 
> Do you know if there is a timeline for other pathogens for ReportStream (e.g. Flu, RSV, Monkeypox, etc.)?
> 
> Thanks,
> Alex

BX sent next steps email to schedule Kickoff to Alex on 10/7/2022:

> Hi Alex,
> 
> My name is Berni Xiong. I'm the Delivery Manager of ReportStream's Onboarding team. I work alongside Ott, who has been assisting you. It appears we've not yet completed a ReportTeam Sender Kickoff meeting with you and your team. I'd be happy to set one up with you next week as your schedule allows.
>  
> I'm including some useful resources in the following to get you prepared for our kickoff meeting:
> If you haven't already done so, please make sure these items are completed before the kickoff call: 
> Register for a free ReportStream user account
> Review our Terms of Service 
> Sign our Terms of Service agreement
> If you have any questions about sending via API connection, we'll have engineering on the call to briefly go over the ReportStream API Programmer's Guide but feel free to preview the document ahead of time.
> We'll cover a high-level overview of all the onboarding stages and steps during the kickoff call (which are also detailed in the programmer's guide)
> We'll ask you to have several test messages prepared to help streamline this onboarding effort (instructions can be found on Page 6 of the programmer's guide), but since we have a 1-2 week backlog, you've got some time to prepare this.
> NEXT STEPS
> 
> Could you propose about 2-3 dates and times next week that could work for you and anyone from your team (we are closed on Monday 10/10)? We'd only need about 30 minutes.
> 
> Thanks so much, I look forward to hearing from you.
> 
> Best,
> Berni

**Comment by BerniXiongA6** [comment]
As of today 10/24/2022, Alex and ReOpen/Cerner team has not responded regarding scheduling an API Sender Kickoff meeting with O&O.

**Comment by sliu1000** [comment]
Update from Sender:

Can you confirm for me that these values will work with ReportStream? Also, do you know what value we should use for the AN Swab? On other lines in the [http://LIVD SARS-CoV-2 Test Codes.xlsx]LIVD sheet it looks like AN Swab and NP Swab specimen have the same SNOMED code. Are we allowed to use the same SNOMED code for both of those specimen types?

Model: CDC 2019-nCoV Real-Time RT-PCR Diagnostic Panel (CDC)
LOINC: 94309-2
Specimen Types/Snomed codes:
NP Swab / 258500001
AN Swab / [not specified on LIVD sheet]
Oral Swab / 258529004
Saliva / 258560004

Thank you,
Alex

**Comment by BerniXiongA6** [comment]
@oslynn please look into this and reply to sender as needed

**Comment by brandonnava** [comment]
@oslynn will follow up once more. If no response will close

**Comment by oslynn** [comment]
The sender decide to discontinue the onboarding process with ReportStream:

Good Morning Ott,

Thank you for following up with us concerning our ReportStream onboarding process. Unfortunately, PRL has made the difficult decision to cease clinical laboratory operations, effective 12/31/22. Our current goal is to utilize SimpleReport to send our remaining back-data to states and not to continue the onboarding process with ReportStream due to the change in our operations. We appreciate the guidance and assistance your team provided earlier as we were developing a long-term reporting method for several states. If there are any pending actions that must be taken to discontinue our onboarding process, please let me know.

Thank you again for your outreach and have a great 2023.

Best,

Andrew Kosterman

Quality Assurance Manager

Pandemic Response Lab, DC

9605 Medical Center Dr., Ste 220

Rockville, MD 20850

andrew.kosterman@reopenlabs.com

C: 716-622-0165
