### ISSUE TITLE
Validate initial file BZD labs - CSV to API

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#6345]
New sender BZD labs will be sending CSV format to API. Contacts are:

Desiree Brock - desiree@dobringroup.com
Qais Alkurdi -  qais@dobringroup.com

**Comment by GilmoreA6** [comment]
Hi Desiree,

I have taken a look at the sample data provided and looks like we are in pretty good shape. There are a few additions/ things to be aware of that would be great if we could get added/ironed out. 

If it is possible we have a few additional columns we would like to see (they are listed in the Programmer's Guide as optional and don't need to necessarily be valued but we would like to have the columns included in sent files even if they are not populated). The additional column headers are:

patient_middle_name
patient_street2
patient_preferred_language
testing_lab_specimen_received_date
ordering_provider_middle_name
ordering_provider_street2
testing_lab_street2
comment

The other thing to be aware of is the date/time fields. We prefer a format with a UTC offset (e.g. "20220825154000-0800" for 8/25/2022 3:40 PM PDT). For date/time fields without a UTC offset value, ReportStream will assume a UTC offset of +0000 (which will result in inaccurate date/times being reported if the timestamps do not correlate with that timezone)

Finally, do you have a preference for either token-based authentication or a shared secret key for connecting to the API? Both methods are described in the Programmer's Guide (https://reportstream.cdc.gov/resources/programmers-guide
CDC Prime ReportStream
ReportStream Dashboard Application
reportstream.cdc.gov
) with examples. 

Please let me know if you have any questions that I can answer. After you make the changes described above if you could send a new sample file for validation that would be appreciated. Please use fake data in the sample file that does not include any PHI/PII

Thank you,

James Gilmore

James Gilmore (Agile Six)
Senior HL7 Data Analyst
Pandemic-Ready Interoperability Modernization Effort (PRIME)

**Comment by sliu1000** [comment]
@GilmoreA6 

Please review revised CSV File from Dobringroup:

Qais Alkurdi from Dobringroup.com has sent a revised CSV with the new additions and the timezone format changes.
