### ISSUE TITLE
VT - Potential Service Interruption between June 2022 to Present

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6352]
## Problem statement

The Vermont Department of Health has been noticing that cases  identified by the Vermont Department of Corrections are not ending up in NBS.

## What you need to know
 Full Communication from User: 
I’m reaching out to ask if you would be able to indicate whether there have been any interruptions or outages in Covid case reporting via Simple Report from Vermont between June 2022 to present. We are noticing that cases identified by the Vermont Department of Corrections are not ending up in NBS and our team is working to identify the source of the error. If you need additional information from me, please let me know.
- ...

## Acceptance criteria

- Confirm/determine the source of error and communiciate back to user on next steps.

**Comment by BerniXiongA6** [comment]
@sliu1000 could you send me the email communication from them so I can try to investigate before moving this out of needs analysis?

**Comment by sliu1000** [comment]
@BerniXiongA6 I just fwd you.

**Comment by BerniXiongA6** [comment]
Thanks @sliu1000 I'll handle it for now and if it needs to be escalated to a dev, I can coordinate that. BX to investigate.

**Comment by sliu1000** [comment]
Got it. Thank you Bernie.

Sharon
________________________________

**Comment by BerniXiongA6** [comment]
Resolved 8/11/2022:

Email sent:

>Hi Lucy,
> 
> Nice to meet you, I'm the new Delivery Manager for ReportStream's Onboarding and Operations team. I investigated further on your question and here's what I was able to find out.
> 
> 
> 
> Per SimpleReport, Vermont Dept. of Corrections hasn’t submitted any test results since June 15, 2022 (that’s the last reported test date). The engineering team was wondering if they might’ve been back-dating results back in January/February (at that time, they were showing about 1-2 results per day)?
> 
> 
> 
> Also, in case there were any concerns about login issues, SimpleReport was able to confirm that the sender has active user access.
> 
> 
> Please let us know if there's anything else!
> 
> Thanks,
> Berni

**Comment by shy2cdc** [comment]
lucy.lincoln@vermont.gov 8/18 12:24pm 

Our Epidemiology team has been in communication with the Vermont Department of Corrections and they claim to have sent a “big batch” of test results through SimpleReport this week. Are you able to confirm whether these test results have been received on your end?
