### ISSUE TITLE
CA - Transition to Manifest Medex from Optum

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#6355]
## Problem statement

California is transitioning away from Optum and to a new vendor (Manifest Medex). We'll need to work with the new vendor to create and test the transport.

## What you need to know
Email CA's new vendor:
```
Good Morning Lab Submitters,

I am reaching out to you in response to the communication that was emailed to you on Tuesday July 19th from the CalREDIE Help Desk.  My name is Rich Brown and I’ll be the Implementation PM working with you throughout the process.  
The California COVID Reporting System (CCRS) will be migrating to the Surveillance and Public Health Information Reporting and Exchange (SaPHIRE) system starting August 1, 2022 
You are receiving this communication because you have been selected to migrate to SaPHIRE in August. Listed below is the limited scope of what will be needed from you as a lab submitter. 
Scope
You will receive new SFTP login credentials to send data to the new SaPHIRE System.
Provide your Public facing IP for firewall whitelisting.
The migration to SaPHIRE does not involve any changes to your current message/data structure.
Next Steps 
Please respond to this email with the following information.
Acknowledge receipt of this communication.
Confirm you will be able to execute the steps above the week of August 29 at an agreed upon date and time.
Please send a full list of CLIAs you are currently submitting to the CCRS system.
Confirm you will continue sending to the CCRS system until the agreed upon migration date and time in August at which point you will change the SFTP to point to the new SaPHIRE host.
Please send over any questions and if you'd like to meet to discuss the process, please send back a few times/dates that work for you and your team this week.
Thank you in advance for your cooperation.  We are looking forward to working with you.


Rich Brown
Training Support for SaPHIRE Project
e: rich.brown@manifestmedex.org
p: 513-668-7208


```

## Acceptance criteria

- [ ] Able to connect to the new test/staging env
- [ ] Able to connect to the new prod env

## To do

- [ ] Answer questions from Manifest Medex
- [ ] Receive sftp creds (Maybe different for prod and staging?)
- [ ] Create new transport to test/staging
- [ ] Create new transport to prod
- [ ] Verify connections with Manifest Medex

**Comment by brick-green** [comment]
Sent email to Rich:
```
Confirm you will be able to execute the steps above the week of August 29 at an agreed upon date and time.
     Yes
Please send a full list of CLIAs you are currently submitting to the CCRS system.
     CDPH000075
     CDPH000087
     CDPH000077
     CDPH000085
     *These are the values sent in MSH-4. Do you need the CLIA values sent in the other CLIA fields?
Confirm you will continue sending to the CCRS system until the agreed upon migration date and time in August at which point you will change the SFTP to point to the new SaPHIRE host.
     Yes
Please send over any questions and if you'd like to meet to discuss the process, please send back a few times/dates that work for you and your team this week.
     Will there be separate environments for test/staging/production?
```

**Comment by brick-green** [comment]
Looks like they'd like to plan the transition for the first full week of September. They are going to send the SFTP credentials directly to me.

**Comment by brick-green** [comment]
sent the IP range(158.111.236.0/24) to allow over to the vendor

**Comment by brick-green** [comment]
Pinged Amy on the IP address and credentials for the SFTP connection

**Comment by brick-green** [comment]
sent josiah the hostnames so that he can submit a request to palo alto team to allow traffic out. Next step is testing.

**Comment by brick-green** [comment]
cutover scheduled for 9/7

**Comment by brick-green** [comment]
Waiting for palo alto firewall whitelisting. This is the CDC firewall that has to whitelist the hostnames from Manifest Medex.

**Comment by brick-green** [comment]
palo alto team found that the production URL does not resolve. The staging and validation URLs do resolve though. So I sent an email to Amy at Manifest to confirm the URL for production.

**Comment by sliu1000** [comment]
Update from Amy Manjon from Manifest:

Hello,

 The Go Live for the SaPHIRE production cutover has been postponed and we will need to reschedule your migration date from 9/7 to a date in the future. We are reviewing the schedule and will provide an update on the new target Go Live date within a week and will reach out to confirm the new date and your organization’s ability to cutover on that date. 

In the meantime, you must continue to submit data to the California Department of Public Health via your existing connection to CCRS.

We apologize for any inconvenience this may have caused, and we are still striving to keep you informed and make this transition as smooth as possible. Please reach out if you have any questions about this change.

 Thanks,

Amy Manjon

**Comment by sliu1000** [comment]
Response from Amy Manjon:

Hi Brick,

To respond to your earlier question, I’ve confirmed that these will be the production endpoints once we go live:

Staging: saphiresftpstage.cdph.ca.gov
Production: saphiresftp1.cdph.ca.gov

Thanks,

Amy Manjon

**Comment by sliu1000** [comment]
Update from Amy Manjon:

Hello,

Just wanted to drop you a quick update on this. We are getting close to setting a new go-live date but do not yet have it finalized. I’ll get back to you once we have more information on timelines.

Thanks,

**Comment by shy2cdc** [comment]
Email from Amy: 

Hi @brick-green ,

 

We have a few submitters live and are continuing to onboard the rest. Prior to having you cut over, we have some additional data analysis that we need to complete on our side.  At this point we’re expecting to be able to get you live sometime in late October. Let me know if you have any outages or events we need to schedule around and we can settle on an exact date as we get closer.

 

Thanks,

 

Amy Manjon

Manifest Lab Onboarding, Outreach and Data Quality Support Workstream Analyst for SaPHIRE Project

**Comment by sliu1000** [comment]
Update from Amy:

Hi Brick,

We’d like to have you start submitting to SaPHIRE ASAP (preferably this week), but we would need to have you submit dual feeds to both CCRS and SaPHIRE for a period of time. Is that something you are able to do?

Thanks,

**Comment by shy2cdc** [comment]
Email from Amy:

Hello,

 

Were you able to confirm whether you are able to set up a dual feed this week?

 

Thanks,

 

Amy Manjon

**Comment by shy2cdc** [comment]
Email from Amy:

Hi Brick,

 

I’m checking in to see if you are able to set up the dual feed this week?

 

Thanks,

 

Amy Manjon

**Comment by brick-green** [comment]
Jeremy confirmed that the whitelist request was made for HTTPS instead of SFTP. So he put in a new expedited request for SFTP.

**Comment by brick-green** [comment]
Enabled Medex feed in production. They will review files are send back next steps.

**Comment by sliu1000** [comment]
Update from Amy Manjon (Sender):

So far, it’s looking good. I see a lot of messages have come across this morning. We’ll continue to monitor things and will be in touch.

**Comment by brick-green** [comment]
Closing as I turned off the old feeds.
