### ISSUE TITLE
NV moving to EpiTrax

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6356]
## Problem statement
The Nevada Department of Health and Human Services is working on on-boarding all of their reporters at this time.  I understand there are reporters that are being sent through both SimpleReport and Report Stream to Nevada...which is what I would like to work with you on getting set up on the new connection.

## What you need to know

Hi,

I am hoping that you are aware that the Nevada Department of Health and Human Services is moving to EpiTrax as their surveillance system and has contracted with End Point for support.  We were given your name as a contact to help with making the change.

We are working on-boarding all of their reporters at this time.  I understand there are reporters that are being sent through both SimpleReport and Report Stream to Nevada...which is what I would like to work with you on getting set up on the new connection.

I think it would be good if you had time for a short call to discuss the details and get the process started.  The implementation date to make the change is September 10th (last feed to the existing communication point is September 9th).

If you could give me a few times you are available, I would be happy to set up a meeting.

Thanks so much.
--
Linda King
linda@endpointdev.com

## Acceptance criteria

- Determine next steps for setting up a new connection by September 10th, 2022.

## To do

- Determine who should be involved to resolve this.

**Comment by sarahnw** [comment]
duplicate closing
