### ISSUE TITLE
TX - Send failure

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#6364]
## Problem statement

Last mile problem for Texas

## What you need to know

```
Info Details 18267120
Receiving Org:
sftp-edts.hhs.texas.gov
Failed at:
Wed, 8/10/2022, 6:51 PM
Action ID:
18267120
Report ID:
80d27d66-523d-4dc6-98e7-da4f5c536ce8
File URI:
https://pdhprodstorageaccount.blob.core.windows.net/reports/ready%2Ftx-doh.elr%2FCDCPRIME_11D2030855_20220810233511.hl7
tx-doh.elr
Result message:
Success: sftp upload of CDCPRIME_11D2030855_20220810233511.hl7 to SFTPTransportType(host=sftp-edts.hhs.texas.gov, port=22, filePath=./, credentialName=null), Send function unrecoverable exception for event. Mo intervention required: report&SEND&80d27d66-523d-4dc6-98e7-da4f5c536ce8&false
```

## Acceptance criteria

- [x] Successfully test TX sftp connection
- [ ] Resend report and ensure successful send

**Comment by brick-green** [comment]
triggered the resend. Moving to internal review to ensure the trasnport was successful

**Comment by brick-green** [comment]
Just realized this is a really weird one. Somehow the transport host was set as the receiving org...I just checked the TX settings and there is no record of any changes to the TX settings since 6/6/22. No clue how this happened.

**Comment by brick-green** [comment]
Gonna have to manually resend

**Comment by GilmoreA6** [comment]
Message Control ID
re-sent report containing 22 messages

"d6d03ec8-932e-45a3-874e-5351caf70d03"
"6113661e-057e-43be-bb45-fdc888be6262"
"5ce68302-6d45-41f7-8a88-c66b7e2957db"
"569f076f-24b7-48db-8051-c192b16a3db1"
"2dced0a5-a36d-43de-9d36-b116cf0c2950"
"fe3803fd-e2e7-46f7-aab7-cf974778b44b"
"bc0bd2bc-687b-4ca3-b6e3-475e3c7c14d8"
"44a251df-7ac3-4b3f-a650-3d9fc8225b5d"
"760f829f-3edc-4bd9-99df-907ee1252a00"
"f1d666c0-9e86-467e-89ed-c00bdc67c890"
"8e6b746a-42e4-4341-a2e2-352a8efd8d91"
"3c9ab21f-bd3d-4b2d-9cb9-a31200d2921c"
"72b6b73b-5826-4033-8339-aa7441c77d40"
"7d065fc0-df42-4c08-9cc3-bea5be778b22"
"5d4618de-8335-4ca4-82d3-d70080185354"
"d8dd1aec-24db-422d-afd5-51839a3f8ade"
"c152c857-4f45-4039-85fd-bb044b9f539e"
"1125cc68-4bec-4070-a089-ba909a2dc503"
"46607fee-2af4-42ed-95d8-526bffba81ba"
"ffb0dc5f-5b4f-447a-9b1a-fc063dafec9c"
"52b02497-04bf-4284-99ec-4c28a01d6fb6"
"c48f785c-fb7c-4a64-88b8-26c46f80f33f"

**Comment by GilmoreA6** [comment]
Need to have public IP whitelisted by Texas

**Comment by GilmoreA6** [comment]
file manually re-sent via web upload

**Comment by GilmoreA6** [comment]
file manually re-sent via web upload
