### ISSUE TITLE
Design - Discovery: Validation Service UI for a prospective Sender

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6365]
## Problem statement

As a prospective sender with no access to the protected ReportStream website, I want to be test my data file in CSV, HL7 or RADx-MARS format and get user friendly responses to understand, identify and fix issues with my data.

Things to consider:
- Are new senders using custom schema?
- Are non-authenticated users looking to validate without support?
- Specify the user group and segment to design for and why (API only; large senders, what would most reduce burden for state in their onboarding of senders?)

## What you need to know
-  [Mural board for Validation Service Deep Dive with Options ](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1651702156098/60d77d324b3bf252c83d30f73f2cc201a59cc1eb?sender=u3fea607b46e84058d3224917)
 - Provide user-interface that allows file drag&drop or upload feature and display of response to the file
 - There is an expectation of reusing CSV Uploader components and features and not a full new page

## Acceptance criteria
- [ ] Design/IA/Wireframes to allow a public user to do the following:
- [x] User is able to upload a file in HL7 or CSV format
- [x] User is able to view success or error msgs based on the validation of the data file
- [x] Determine where this tool fits in the IA
- [ ] Author content around explaining the tool and how to use it (support /troubleshooting?)

## To do

- [x] Verify what the intent is with files that get uploaded (are they kept?)
- [x] Review the current state of the feature-flagged validator (in order to keep any wireframes in sync)

**Comment by HeatherRienks** [comment]
FYI- @a-chappelear and @drew-usds will discuss. Not ready to refine yet.

**Comment by a-chappelear** [comment]
Per design sync, @drew-usds & @victorialb-usds are going to meet with O&O for a bit of background/discovery work on this ticket (to be revised.)

**Comment by victorialb-usds** [comment]
Added some details to problem statement: - Are non-authenticated users looking to validate without support?
- Specify the user group and segment to design for and why (API only; large senders, what would most reduce burden for state in their onboarding of senders?); 
- also take learnings from internal validator and the use case for which states would do this instead of reportstream and why? IL uses NIST. They might want to use our validator to directly connect senders. As per call with IL august 2022, it is not clear why they would directly connect rather than using RS.

**Comment by a-chappelear** [comment]
_I would suggest making an additional ticket for the for problem statement work (if not done in this sprint.)_

For the AC on this  _“Author content around explaining the tool and how to use it (support /troubleshooting?)”_ There is additional discovery work happening in other tickets on how a user could select a receiver (on the public side) and until that is determined/designed, it’s unclear how to write instructions.
—
This ticket does have a number of UI updates completed and should be done for both public and internal users. [They are annotated and numbered in the Figma file](https://www.figma.com/file/b2Zd1xzmp4cdwFO8O7edcI/CSV-Uploader-%26-Validation?node-id=2617%3A2068), listing them also here:

15 - Adding “ReportStream” to the page title
8 - Move the filename info up to the top and above the messages/alerts
9 - Replace alert banners with the “slim” comp option, updated copy on all
12 - We only need “warnings” and “errors” mentioned once, replace them as headers and remove as table labels
13 - Updated copy
14 - “Cancel” is removed (not needed for a validator)
11 - Nothing to change in row headers, but there likely will be when we get to the error content / inventories in a coming ticket.
—
Some possible stories/ideas for later:
- Consider creating a guide or documentation that a user could refer to on it’s use and for troubleshooting tips 
- Possibly add the ability to save or download results (if errors get really lengthy, it may be something someone wants to save and refer back to)

cc: @RakshindaAslam @bgantick @HeatherRienks

**Comment by HeatherRienks** [comment]
Should we add this to our O&O sync tmrw? 
@drew-usds @victorialb-usds @a-chappelear  @RakshindaAslam
