### ISSUE TITLE
receiver_connection_check_results table full of data that will never succeed

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#6367]
**Background**
The receiver_connection_check_results table is used by `CheckFunction.scheduleRun()` and checks that a receiver is working by connecting to it on a periodic schedule (every two hours currently). It then adds a row to the `receiver_connection_check_results` table.

This table is used by the PrimeAdmin Dashboard page [/adm/send-dash](https://staging.reportstream.cdc.gov/admin/send-dash).

**Issue**
There are lots of receivers that NEVER succeed (about 50%). These are never expected to succeed for various reasons. 

This results in:
 - Worse signal:noise when looking at results.
 - Taking up more significantly more storage since the failures including a long java stack trace.
 - Slows down the Dashboard page because querying for a timespan required more data and a much bigger DOM.
 - Limits max number of days displayed in the Dashboard page. The query for a span of days gets bigger than 9000 rows and gets clipped by api.
 
 **Thoughts**
 - Solution should work in staging and production.

**Comment by TomNUSDS** [comment]
@MauriceReeves-usds Is there an existing "RECEIVER" Setting value that can be used to determine if it should be tested?

**Comment by MauriceReeves-usds** [comment]
Unfortunately no. We should just add one to specify whether or not they're considered routable.

**Comment by TomNUSDS** [comment]
I'm thinking it should "default to safe" for this value. Which means the check feature should run if the value is missing. 

Do "missing values default to false" a common thing with our Settings or  is it ok to assume `routable=true` if it's missing?

**Comment by TomNUSDS** [comment]
While investigating I had a question:

@MauriceReeves-usds Would this be considered a bug to have a non-optional parameter buried in the middle like this?

```kotlin
class ReceiverAPI
@JsonCreator constructor(
    name: String,
    organizationName: String,
    topic: String,
    customerStatus: CustomerStatus = CustomerStatus.INACTIVE,
    translation: TranslatorConfiguration,
    jurisdictionalFilter: ReportStreamFilter = emptyList(),
    qualityFilter: ReportStreamFilter = emptyList(),
    routingFilter: ReportStreamFilter = emptyList(),
    processingModeFilter: ReportStreamFilter = emptyList(),
    reverseTheQualityFilter: Boolean = false,
    deidentify: Boolean = false,
    deidentifiedValue: String = "",
    timing: Timing? = null, // OPTIONAL
    
    description: String = "",  // <--- NOT OPTIONAL
    
    transport: TransportType? = null, // OPTIONAL
    override var version: Int? = null,
    override var createdBy: String? = null,
    override var createdAt: OffsetDateTime? = null,
) : Receiver(
```

**Comment by TomNUSDS** [comment]
Oh, I see. because the default is an empty string it's considered optional?
