### ISSUE TITLE
Internal testers feedback, RS public site

### ISSUE THREAD

**Issue by a-chappelear** [CDCgov/prime-reportstream#6375]
## Problem statement

The experience team would like to collect feedback from RS internal teams (O&O!) on recently updated content on the public site and also discuss any potential additions or updates that may be needed.

## What you need to know

 [A Mural doc has been created](https://app.mural.co/invitation/mural/primedatainput6410/1660180328563?sender=uc91f7c72c0f84196a8818813&key=99f2160c-37ce-481d-b13f-d7c6bd00e0c8) w/ instructions on how the public-facing site could be reviewed async (so folks are able to review as they have time) and we can then meet at the end of a sprint to review and discuss as needed.

The following detailed instructions are included inside the Mural link above:

> **ReportStream Content & Usability Review (Internal teams)**
> 
> The experience team has made signficant content updates to the public site and would love your internal feedback on what's working and what could be improved
> 
> Homepage: https://reportstream.cdc.gov/
> Goals: High level overview on ReportStream as a product and service
> 
> Product section: https://reportstream.cdc.gov/product/overview
> Goals: Detailed overview, why and how to use ReportSteam, where we are live and recent updates
> 
> Resources: https://reportstream.cdc.gov/resources
> Goals: Detailed documentation, checklists and onboarding guidance
> 
> Support: https://reportstream.cdc.gov/support
> Goals:  Contact and FAQs, future state of a more robust help center
> 

## Acceptance criteria

- [ ] Looking for feedback on the current state (and verifying that documentation, onboarding materials, dev guides are current)
- [ ] Potential ideas on future additions/features (helping onboarding, support, guides, etc)

## To do
Timeline to complete this: before or by late Sept/early Oct 2022

O&O Team Members:

1. Go to the [Mural board](https://app.mural.co/invitation/mural/primedatainput6410/1660180328563?sender=uc91f7c72c0f84196a8818813&key=99f2160c-37ce-481d-b13f-d7c6bd00e0c8) and:
- [ ] Read Mural board description
- [ ] Questions to consider

2 . After reading the description and questions, visit reportstream.cdc.gov and review content for each of the following pages (average total time to review all the following pages is between 30 minutes to 1 hour): 
- [ ] Home
- [ ] Product
- [ ] Resources
- [ ] Support

3. After reviewing each section, leave your feedback on the Mural board:
- [ ] Write your name on one of the available boxes labeled "My Name"
- [ ] Write your feedback within the appropriate box (add cards within the box as needed)

**Comment by a-chappelear** [comment]
(This ticket is a result of [RS Website Research Scheduling & Prep](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6258))

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 Tagging myself so I can watch this!

**Comment by BerniXiongA6** [comment]
@sarahnw when do we think we can prioritize this for O&O based on our current work and future sprint goals?

**Comment by sarahnw** [comment]
@BerniXiongA6 I can look at this this week, but there's probably other folks from the team that will want to talk a look. why don't we put this in the Next column for now? @a-chappelear is there a deadline y'all are looking for feedback from us by?

**Comment by a-chappelear** [comment]
@sarahnw over the next couple sprints or so - not a rush, but know several of you have input on the site and want to make sure we get that incorporated! :)

**Comment by BerniXiongA6** [comment]
Hey @sarahnw and engineers, providing our feedback to Experience team is important however please plan this work around the O&O sprint work. Sarah will do a comprehensive review, so feel free to spend no more than 1 hour total on reviewing this content and providing feedback. We're aiming to provide final feedback by late-Sept/early-Oct 2022, so we've got some time to incorporate this into our sprint work little by little. Thank you!

**Comment by sarahnw** [comment]
@BerniXiongA6 left my feedback on the mural!

**Comment by a-chappelear** [comment]
This feedback has been collected and is being turned into backlog tickets, per #6394. Closing as completed.
