### ISSUE TITLE
WA - GAEN Send failures assessment

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#6377]
## Problem statement

We currently have a receiver for Google/Apple Exposure Notification (GAEN). The transport regularly fails. We need to understand why it fails and plan for a solution.

## What you need to know

 Failures can be reviewed on last mile problems page: https://reportstream.cdc.gov/admin/lastmile

## Acceptance criteria

- [ ] Failure cause is identified and documented
- [ ] Solution plan is created

## To do

- [ ] Access failures in last mile
- [ ] Review code for GAEN retries
- [ ] Create solution plan

**Comment by GilmoreA6** [comment]
Majority of errors are of type 400: Bad Request. The GAEN documenation (https://github.com/google/exposure-notifications-verification-server/blob/main/docs/api.md#apiissue) mentions several different reasons for why a 400 status might be returned as evident in this table ![image.png](https://images.zenhubusercontent.com/62dae0f57dfc25367c3e0ca6/d53c9ae6-b1d4-4c5f-b61f-5110911c1da2)e

**Comment by GilmoreA6** [comment]
Errors do not appear to be related to message content as there are no obvious deficiencies in failed message. Need to investigate full JSON response to see if this is helpful.

**Comment by oslynn** [comment]
When I have a chance, I will take a look at this ticket with James.

**Comment by GilmoreA6** [comment]
Need to modify error logging on GAEN to extract error code sent back in from API so we can get more detailed info on why messages fail.

**Comment by GilmoreA6** [comment]
Need to add logic to GAENTransport.kt to include error returned in JSON in logs.

**Comment by oslynn** [comment]
I added a response errorCode of 400 Bad request Status code.  The errorCode will tell us a specific failure.  Therefore, we can address it.

**Comment by oslynn** [comment]
Every wa-gaen test that failed in last mile failure.  They all failed with 400 Bad request of invalid_date = 'The provided test or symptom date, was older or newer than the realm allows.   For date to be valid the illness_onset_date (or symptomDate) and date_result_release (or testDate) must be within 29 days between them.  For example, date_result_release = 2022-12-15 the illness_onset_date >= 2022-11-17 (e.g., 2022-11-18/19/20 etc).   Otherwise,  date consider to be older.

**Comment by oslynn** [comment]
Need to find out how RS generate the GAEN message for WA-GAEN.
