### ISSUE TITLE
Move Nevada to EpiTrax

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#6379]
Met with EpiTrax 8/22/22

RS will need to:

- open port in Palo Alto firewall - Mo has already asked DevOps for help with this 8/22
- send them a list of all NV senders
- send them our IP address - @brick-green did this 8/22
- they will give us username and pass for auth
- we need to give them some deidentified info
- set up a static value in MSH-4-1
- create a new feed for epitrax while testing with them but still in production with inductive health

Original ticket:
8/9 7pm

I am hoping that you are aware that the Nevada Department of Health and Human Services is moving to EpiTrax as their surveillance system and has contracted with End Point for support.  We were given your name as a contact to help with making the change.

We are working on-boarding all of their reporters at this time.  I understand there are reporters that are being sent through both SimpleReport and Report Stream to Nevada...which is what I would like to work with you on getting set up on the new connection.

I think it would be good if you had time for a short call to discuss the details and get the process started.  The implementation date to make the change is September 10th (last feed to the existing communication point is September 9th).

If you could give me a few times you are available, I would be happy to set up a meeting.

Thanks so much.
Linda

--
Linda King
Project Coordinator
End Point Corporation
linda@endpointdev.com

**Comment by sliu1000** [comment]
Update from Kevin from Endpointdev:

Confirming we can see 4 files from you on our Prod server. Looks like it's running smoothly!

Thanks!
Kevin Q

**Comment by sliu1000** [comment]
Update from Linda King:

Hi,

All of the production messages we are receiving through Report Stream are de-identified.  The patient name and addresses have been removed.

Would you please have a look?

Thank you.
Linda

--
Linda King
Project Coordinator
End Point Corporation
linda@endpointdev.com
