### ISSUE TITLE
Feature: easier way to generate keys

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#6393]
Correctly creating a private/public key pair to work with our API can be tricky. Then exchanging the keys requires some secure communication.

IDEA: create an API and web page for logged in users to generate correct key and allow the end user to download from the https page. The private key once downloaded by the user should NOT be saved on the server. (Self-service!)

The API can do as much as possible on the backend to configure the user (add settings, add keys to keystore ... or generate ticket/event with bucket reference to the key to add it).

**Comment by TomNUSDS** [comment]
@mauricereeves  @jimduff-usds Thoughts?

**Comment by brandonnava** [comment]
@TomNUSDS Did we ever end up making a feature like this? Seems useful given our renewed focus on self service

**Comment by jimduff-usds** [comment]
There are websites that generate keys, eg, https://cryptotools.net/rsagen.

Note:  One of the beauties of the way we do server2server auth is that no secret ever needs to change hands.   But that does require that the Sender be able to generate a keypair.
