### ISSUE TITLE
RS Website - Conduct feedback interviews

### ISSUE THREAD

**Issue by a-chappelear** [CDCgov/prime-reportstream#6394]
Conduct & review interviews [as scheduled in 6258](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6258)

O&O and external users

- [ ] Synth and review O&O site feedback and prep tickets for the backlog

**Comment by a-chappelear** [comment]
[We've gotten some feedback from O&O](https://app.mural.co/invitation/mural/primedatainput6410/1660180328563?sender=uc91f7c72c0f84196a8818813&key=99f2160c-37ce-481d-b13f-d7c6bd00e0c8). Would recommend bringing this ticket into the next sprint to review feedback & next steps. @RakshindaAslam @HeatherRienks

**Comment by RakshindaAslam** [comment]
Thank you @a-chappelear! The RS website initiative is put on hold after the last product checkin. So let's plan to revisit this after the next few priorities are addressed.

**Comment by a-chappelear** [comment]
Converting the feedback we got from this into tickets for the backlog!

**Comment by a-chappelear** [comment]
Tickets have been created from this feedback:

- https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6687
- https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6688
- https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6689
- https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6690
