### ISSUE TITLE
CA - Missing data for recent ELR's- Out of State

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#6400]
We are noticing some ELR’s coming to us from CDC ReportStream (out of state) These ELRs are missing a LOINC in OBX 3.1. There is nothing in the message that indicates what the disease condition is. Please resubmit these files by placing a “c” in OBR 25 and OBX11 and ensure that this is corrected for future results.

OBX|1|CWE|^^LN||260415000^Not detected^SCT^^Not detected|||N^Normal

 

Correct and resubmit

SH00116_59f5443c922944b0b587d4f789b96d40               

SH00116_65b2df678be749e5976c1463d3da705f

SH00116_cbecc6535b5441f0a72f43769067cf5d

SH00116_aabf4ae887c74aed8eda7f369076b9a1

SH00116_628bb46a8150431a819e137e4f457835

SH00116_856f46e51be445a0bd46bafaba587cef

SH00116_deb839b718054fb884c671df67cd4398

**Comment by oslynn** [comment]
@TaneaY , would you please give the receiver's (state) name?  Also, forward their email to me.

**Comment by oslynn** [comment]
Email chain from receiver.

From: San Nicolas, Jocelyn@CDPH <Jocelyn.SanNicolas@cdph.ca.gov>
Sent: Monday, August 15, 2022 4:27 PM
To: alan@safehealth.me <alan@safehealth.me>
Cc: Report Stream (CDC) <reportstream@cdc.gov>
Subject: CDC ReportStream-Out of State RE: Missing data for recent ELR's
 
Hi there,

 

We are noticing some ELR’s coming to us from CDC ReportStream (out of state) These ELRs are missing a LOINC in OBX 3.1. There is nothing in the message that indicates what the disease condition is. Please resubmit these files by placing a “c” in OBR 25 and OBX11 and ensure that this is corrected for future results.

OBX|1|CWE|^^LN||260415000^Not detected^SCT^^Not detected|||N^Normal

 

Correct and resubmit

SH00116_59f5443c922944b0b587d4f789b96d40               

SH00116_65b2df678be749e5976c1463d3da705f

SH00116_cbecc6535b5441f0a72f43769067cf5d

SH00116_aabf4ae887c74aed8eda7f369076b9a1

SH00116_628bb46a8150431a819e137e4f457835

SH00116_856f46e51be445a0bd46bafaba587cef

SH00116_deb839b718054fb884c671df67cd4398

 

Best regards,

Jocelyn San Nicolas, MS

Laboratory Reporting Analyst

Division of Communicable Disease Control

California Department of Public Health

Jocelyn.Sannicolas@cdph.ca.gov

**Comment by TaneaY** [comment]
@oslynn Email has been forwarded. Tagged receiver state- CA

**Comment by oslynn** [comment]
Looking from database table: covid-result-metadata.sender_id = SafeHealth.

**Comment by oslynn** [comment]
2022-08-16, emailed to Dave and Alan (SafeHealth).

Dear: Alan, Dave

Would you please resend the following messages with correct values as follow:

OBX-3.1 fill with correct LOINC Code
OBX-11 and OBR-25 with value 'C'

 message ids



SH00116_59f5443c922944b0b587d4f789b96d40               

SH00116_65b2df678be749e5976c1463d3da705f

SH00116_cbecc6535b5441f0a72f43769067cf5d

SH00116_aabf4ae887c74aed8eda7f369076b9a1

SH00116_628bb46a8150431a819e137e4f457835

SH00116_856f46e51be445a0bd46bafaba587cef

SH00116_deb839b718054fb884c671df67cd4398



Best regards,

-Ott Sathngam

CDC SW ENG.

**Comment by shy2cdc** [comment]
Jocelyn 8/17 at 3:25pm

Just wanted to follow up on this as I am seeing an additional 3 messages coming in from CDC Report Stream (out of state) Using CLIA CDPH000075 – performing lab, Safe Health.

@Report Stream (CDC) is there another contact for this lab?

Referencing accession #’s

`SH00116_fb97e79294374ae3912f3a2c5087c86c`

`SH00116_9c37558529ad420dbf83914debbe7d85`

`SH00116_b1634275e1b842079a8829d9b14b8559`

**Comment by brick-green** [comment]
Same issue as ticket #6334. I'm working with SafeHealth to fix the issue. When they fix it, I'm going to ask them to resend the full backlog. That will fix this ticket and 6334.
