### ISSUE TITLE
DE - Validate Primary Health

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#6412]
## Problem statement

Delaware requested that we validate Primary Health. They are concerned that the correct facilities were not being mapped to the correct locations in the HL7 messages. 

## What you need to know

Primary Health has a testing service that includes an application to assist in running testing at offsite locations. They will often be contracted by a company to run testing at a third party location. Example: a mcdonalds store wants to test all the employees. So they hire Primary to help with the testing. The testing is run at the hotel across the street. So the testing location is the hotel, the ordering facility is McDonalds and Primary is the test producer. 

Another example that is more difficult. Quidel partners with Delaware Public Schools to run a school testing program. Quidel is running the test so they are the producer, the school is the testing location, but what facility is the ordering faciltiy?

## Acceptance criteria

- [ ] Determine facility mapping

**Comment by GilmoreA6** [comment]
Met with client and provided guidance on how to modify messages to contain information as expected by de-phd

**Comment by GilmoreA6** [comment]
Met with client and provided guidance on how to modify messages to contain information as expected by de-phd

**Comment by BerniXiongA6** [comment]
Closing because we resolved on our part, we can create a new ticket if they contact us in the future.
