### ISSUE TITLE
MA - MDPH ELR4 Portal is Down 

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#6413]
MA DOH - elr.cdsupport2@state.ma.us 8/17/22 at 11:51am

We estimate that systems were down from 2:30 AM until 11:35 AM this morning.

If you had any transmissions that should have been sent during that period, could you possibly resend them?

**Comment by GilmoreA6** [comment]
Gilmore, James (CDC/DDPHSS/OD/HITSSU)
Good Afternoon,

As regards the outage on 8/17/22 noted in ticket #6413, I am not seeing any send failures within the timeframe noted (02:30 AM - 11:35 AM). I am showing a successful transmission of a batch file at ~9:50 AM EDT. Filename was ?prime-20220817135059.hl7" and it contained 159 items. Could you verify that file was received or let me know if you would like it re-sent.

Thanks,

James Gilmore

James Gilmore (Agile Six)
Senior HL7 Data Analyst
Pandemic-Ready Interoperability Modernization Effort (PRIME)

**Comment by GilmoreA6** [comment]
Received response for MA "Hi James,

 

We received this on file on 8/17/2022, we are all set.

 

Thanks,

Janice"
