### ISSUE TITLE
BZD Labs/Dobring API Sender Onboarding - CSV

### ISSUE THREAD

**Issue by sarahnw** [CDCgov/prime-reportstream#6417]
We should prioritize this sender as they've been waiting a while. 

CSV sample file is available in Sharepoint: https://cdc.sharepoint.com/:x:/t/USDSatCDC/ETPGZMcgHu9An_J_yxs2yPsBA444LhQ_sLKN4xVwzzCVpg?e=YN9mby

Message Sarah, Berni, or Sharon to get added to the email thread.

**Comment by sliu1000** [comment]
@GilmoreA6  The user Desiree Bock is looking for an update.  She can be reached at desiree@dobringroup.com.

**Comment by sliu1000** [comment]
James provided user an update on 8/25 at 6:54 PM, see response below:

Hi Desiree,

I have taken a look at the sample data provided and looks like we are in pretty good shape. There are a few additions/ things to be aware of that would be great if we could get added/ironed out. 

If it is possible we have a few additional columns we would like to see (they are listed in the Programmer's Guide as optional and don't need to necessarily be valued but we would like to have the columns included in sent files even if they are not populated). The additional column headers are:

patient_middle_name
patient_street2
patient_preferred_language
testing_lab_specimen_received_date
ordering_provider_middle_name
ordering_provider_street2
testing_lab_street2
comment

The other thing to be aware of is the date/time fields. We prefer a format with a UTC offset (e.g. "20220825154000-0800" for 8/25/2022 3:40 PM PDT). For date/time fields without a UTC offset value, ReportStream will assume a UTC offset of +0000 (which will result in inaccurate date/times being reported if the timestamps do not correlate with that timezone)

Finally, do you have a preference for either token-based authentication or a shared secret key for connecting to the API? Both methods are described in the Programmer's Guide (https://reportstream.cdc.gov/resources/programmers-guide
CDC Prime ReportStream
ReportStream Dashboard Application
reportstream.cdc.gov
) with examples. 

Please let me know if you have any questions that I can answer. After you make the changes described above if you could send a new sample file for validation that would be appreciated. Please use fake data in the sample file that does not include any PHI/PII

Thank you,
James Gilmore

**Comment by GilmoreA6** [comment]
Provided feedback to sender. Awaiting updated sample data with corrections.

**Comment by sliu1000** [comment]
Update from Sender 10/3/2022:

Hello!
I hear we are close to finalizing a connection. I am very excited. **Can you confirm if we can add other CLIA numbers in the same file, or do I need to fill anything out for the new CLIA numbers?** Also, for **data that was before the connection, do we submit this a certain way?** I just want to make sure we are covering everything once this is established. 
Kindest Regards,

Desiree Bock, B.S., C(ASCP), MBA

**Comment by sliu1000** [comment]
Update from CA State - Ellaison on 10/7 at 8:45 PM:

Hi James,

Yes, for the CSV messages, please do use CDPH00085 in place of the CLIA and send the prod messages for us to review to our test environment.  Since we are currently getting a fair amount of data in our test environment, it would be helpful to know when you send the messages and the accession numbers which will make it easy for us to locate and review them. 

I’ve added Teddy Fries on this email chain and she or one of her team members will be performing the review.  I’ve also cc’d Vanessa for awareness as she is familiar with ReportStream CSV uploads as well. 

Thanks,

Ellaison

**Comment by shy2cdc** [comment]
Hello,

All of this was sent and I received notification that it was successful. Can you please advise?


Thank you!


Qais Alkurdi
