### ISSUE TITLE
Tooling for search

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#6421]
# Strategy

## Problem statement
In order to index with search.gov, we'll need to pre-render/statically render all of our public-facing content during the build process.

### Static/pre-rendering

[https://web.dev/rendering-on-the-web/#static-rendering](https://web.dev/rendering-on-the-web/#static-rendering)

[https://create-react-app.dev/docs/pre-rendering-into-static-html-files/](https://create-react-app.dev/docs/pre-rendering-into-static-html-files/)

**Pros:**

- added benefits
  - improving load times
  - indexing on DAP

**Cons:**

- adds to the build process
- medium lift

### Libraries
- https://github.com/sPavl0v/react-spa-prenderer: Recently updated (within ~6mo), not a ton of downloads
- https://github.com/stereobooster/react-snap: Hasn't been updated since 2019, more downloads/more widely used
- https://www.gatsbyjs.com/docs: very well supported, will take more work

## Acceptance criteria
- [ ] Public facing site is statically rendered as HTML pages on production
- [ ] Azure CDN (Front Door) is configured to serve static pages for public facing content

# Other options explored

## Create sitemap as part of the build process and update CDN rewrite rules

Tentative release date for JS indexing support through search.gov is end of this calendar year / early next year. We could use Bing's index to power search initially (if they handle the JS rendering well), and then transition to search.gov indexing once the feature is ready.

**Pros:**

- low to medium lift

**Cons:**

- adds to build process
- seems somewhat fragile/hand-wavy
- less of a “complete” solution
- a few unknowns

## Server side rendering (SSR)

[https://web.dev/rendering-on-the-web/#server-rendering](https://web.dev/rendering-on-the-web/#server-rendering)
[React's SSR Tools](https://reactjs.org/docs/react-dom-server.html)

**Pros:**

- most “complete” solution
- added benefits
  - improving load times
  - indexing on DAP

**Cons:**

- medium to high lift
- adds complexity around infrastructure
- might be outside scope of ATO

## Generate an RSS feed

Another interim option would be to provide an RSS feed for each URL, with the unique body content of the page as the `description` (more information on how this works with search.gov is here: [https://search.gov/admin-center/content/domains-advanced.html](https://search.gov/admin-center/content/domains-advanced.html)).

**Pros:**

- could be low lift?

**Cons:**

- is a work-around
- little benefit outside the context of search.gov

## Roll our own search within react app

**Pros:**
- Circumvents need for all of the above for search

**Cons:**
- Could be a very big lift
- Doesn't provide any SEO benefits

---

**Testing:**

[https://search.google.com/test/mobile-friendly](https://search.google.com/test/mobile-friendly)

**Comment by kevinhaube** [comment]
@chris-kuryak @CnoteNava @HeatherRienks Closing this. Safe to say the outcome of this is that **ReportStream needs a statically-generated public site if we hope to implement `search.gov` or other indexing tools into our documentation. 

We should make the ticket for work if/when we prioritize this :)
