### ISSUE TITLE
Fix HL7 sample message on the Programmer's Guide

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6422]
## Problem statement
The HL7 sample message in the Programmer's Guide v 2.2 on ReportStream website is not correct and cannot be used as is to run test against the API. As a user testing the API with help from the Programmer's Guide, I would like the HL7 msg sample to be complete in structure and content so the API returns a successful response. 

## What you need to know

- https://reportstream.cdc.gov/assets/pdf/ReportStream-Programmers-Guide-v2.2.pdf
- Sample HL7 file to be included
https://cdc.sharepoint.com/:u:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Test%20Files/Sample%20HL7%20Valid.hl7?csf=1&web=1&e=1c9mZz

## Acceptance criteria

- A user is able to copy the HL7 sample msg from the programer's guide v2.2 and get a successful response both from the API end point and Validation Service UI. 

## To do

- [ ] Confirm with O&O team that the HL7 sample referenced here is good to be included in the Programmer's Guide.

**Comment by RakshindaAslam** [comment]
James Gilmore - Could you verify that the HL7 sample file referenced in the ticket is okay to include in the Programmer's Guide? I redacted some names, phone numbers and addresses in the PID section. Thanks! cc @HeatherRienks @bgantick @a-chappelear

**Comment by HeatherRienks** [comment]
@GilmoreA6 - see above.
