### ISSUE TITLE
Genabio - Sender Onboarding

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#6425]
## What you need to know
- Terms of Service agreement signed
- Kickoff meeting completed 8.18.2022

Per Genabio intake form:

> ReportStream API – format CSV
> 
> Q: What is your expected message volume?
> A: 100-1000/day
> Q: Are you currently reporting to any other states outside of your state?
> A: Our company is located in MA, but our product will be sold to every single state
> Q: What is your current process for reporting COVID-19 data?
> A: It will be CSV
> Q: What state do you report to?
> A: MA
 

## To do

- [ ] create individual tickets for this epic

**Comment by sliu1000** [comment]
Genabio is requesting for a update on their CSV file.

**Comment by sliu1000** [comment]
Update from Maurice to Sender:

Good afternoon Juehua,

Sorry for the delay on providing feedback. Everything looks good except we ask that you also add a column for “message_id” that allows us to distinguish an individual message. You could use the same value as specimen_id, or some other unique ID, but it gives us a way to communicate with your team in case we have questions.

 

While you prepare that, I will get things ready on our end for your team to be able to send messages to our staging system. We will set up you with two-legged auth. I have attached the Programmer’s Guide which includes information about how to generate a private key pair and communicate with our staging server. Please review the documentation and let me know if you have any questions. Once you’ve sent us your public key, we can get that set up in staging and you will be able to start sending test messages there!

 

Thank you very much for your patience,

Maurice

**Comment by sliu1000** [comment]
Update from Genabio:

They would like to start testing and need their Authorization and to be setup in the system.

To Do:  Please assign to an engineer

**Comment by sliu1000** [comment]
Update from Maurice to Genabio:

Sorry for the delay on the response. I have reviewed the file that you provided and just noticed that for both the patient_state and the ordering_facility_state fields you are providing the full state name. Are you able to change that to be the postal abbreviation instead?

Aside from that issue, I think we are good to move to connecting you to the staging environment. I will set you up with access to our CSV uploader so you can manually upload files and get back feedback from our system, as well as set you up with API access. In order to give you access to the API, I will need you to send me your public key, which will allow you to request tokens from our system and connect to send test messages.

Please refer to the programmers guide I sent previously and let me know if you have any questions.

**Comment by shy2cdc** [comment]
Email from Jeuhua at 7:30pm 9/30

Good morning @MauriceReeves-usds ,

Please find attached new csv file. I have turned the formating off in this updated version. Please let me know if there is any addtional question. 

Best wishes,
Juehua Yu PhD
Genabio

**Comment by sliu1000** [comment]
Update from Sender Jeuhua 10/12/2022 at 10:45 am:

To Whom It May Concern:

This is Juehua Yu from Genabio. We are working on report submission by CDC ReportStream system. We have generated EC384 key by following "Step 1:  Prior to submission, send your public key to ReportStream" in the doc "ReportStream-Programmers-Guide-v2.3-updated.docx". The public key has been sent to ReportStream team and had notification back. However, in the following sections at that doc and the github site(https://github.com/CDCgov/prime-reportstream/tree/master/prime-router/examples/generate-jwt-python/), only RSA256 is used. So we just wonder whether we can use our old one public key or have to regenerate a new key by RSA256.



Your kindly help will be appreciated!

Sincerely

Juehua

**Comment by sliu1000** [comment]
Update from Genabio as they are looking for an Update:

Hi Sharon, 

Thank you for your email. Hopefully the engineer will look into our case and get back to us soon. 

Best wishes,
Juehua Yu PhD
Genabio Diagnositics INC

**Comment by BerniXiongA6** [comment]
@sliu1000 we're working on getting this ticket re-assigned to an engineer who can assist with next steps. Will update the ticket when that happens. Thanks Sharon!
