### ISSUE TITLE
CA OSANG LLC API Onboarding

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#6427]
ReportStream API – format CSV

Q: What is your expected message volume?
A: 10,000 daily

Q: Are you currently reporting to any other states outside of your state?
A: Not yet

Q: What is your current process for reporting COVID-19 data?
A:  Our current system is designed to support manual self-reporting to STLT in an arbitrary manner, but we plan to change the system to enable  automatic reporting using the authorized LIVD mapping code.

Q: What state do you report to?
A: CA

## TO DO
- [ ] create individual tickets to for this epic (BX can work on doing this)

-------
Stacy 8/18 12:50pm 

We want to request adding a new device OHC COVID-19 Antigen Self Test.

Line 316 on LIVD-SARS-CoV-2-2022-04-27

![image.png](https://images.zenhubusercontent.com/62827d1e0129e15b5c366b1a/f8657779-b1ab-4dae-a0bd-9b1e5e25a847)

**Comment by BerniXiongA6** [comment]
OSANG LLC kickoff meeting scheduled for 8/24/2022 @ 1:30pm ET w/ @sarahnw @BerniXiongA6 @jbiskie

**Comment by BerniXiongA6** [comment]
@sarahnw is this on your radar?

**Comment by sarahnw** [comment]
@BerniXiongA6 no I'm not really sure what we do here? the description may be misleading. I'm going to update with the meeting info from the Help Desk.

**Comment by sliu1000** [comment]
@sarahnw @BerniXiongA6 Hello, is this Genabio? I think this may be a duplicate ticket.

**Comment by BerniXiongA6** [comment]
Hi @sliu1000 this should not be the same as Genabio -- we met with Genabio last week for kickoff. The kickoff for Osang LLC is scheduled for this Wednesday with Stacy Kim at Osang LLC. cc: @sarahnw

**Comment by sliu1000** [comment]
Osang asking for an update. I advised them that it looks like we are still waiting to recieve a test file. @BerniXiongA6

**Comment by BerniXiongA6** [comment]
Will forward previous emails to @MauriceReeves-usds as we wait for Osang to send over test files. @sarahnw told them it may take up to 2 weeks to validate due to our current backlog.

**Comment by BerniXiongA6** [comment]
Updates 9/19/2022: Stacy from Osang followed up today on status. Will let her know @MauriceReeves-usds  is working on it. cc: @sliu1000

**Comment by shy2cdc** [comment]
From StoneLabs inc in cooperation with Osang:

Dear Maurice,

This is Eric Song from StoneLab Inc. in cooperation with OSANG LLC for the development of myHomeTest mobile app using ReportStream.
I apologize for the late reply to your request. 

Below I attach the sample output data from myHomeTest in CSV format.

Consequently, we would like to request your review and the technical guideline for the next steps,
e.g. API share secret key/token, directed URL.

We will be attentive to your instructions in order to meet the FDA's requirements for successful test result reporting on the app to ReportStream.
* I would like to involve two more engineers of StoneLab Team in assisting or cooperating with you: Farid Talibli (Senior SW Engineer), Alexander Sharipov (Junior SW Engineer)

Thank you very much for your help in advance.

Best regards,
Eric

**Comment by sliu1000** [comment]
Hi Eric,

Thank you for the clarification.  We'll provide you with an update once our Engineer finishes reviewing your sample CSV Test file.

Best regards,

Sharon
The ReportStream Support Team

Contact us at reportstream@cdc.gov

Support hours:  8:00 am through 9:00 pm Eastern time

Monday-Friday, excluding US public holidays

From: StoneLab Inc. <president@stonelab.kr>
Sent: Tuesday, September 27, 2022 8:41 PM
To: Report Stream (CDC) <reportstream@cdc.gov>
 
Dear Sharon,

Thank you for your inquiry as well.

I would like to clarify that Osang and StoneLab are independent companies and StoneLab has assisted Osang for software development and technical support.
All the operation, including reporting, shall be performed by Osang as the virtual CLIA after the launch of the app.

Thank you.

Best regards,
Eric

----------------------------------------------
 
Eric (Mingoo) Song

**Comment by sliu1000** [comment]
Sender Requesting an API Key:

I wonder if we could have any updates on the API key.

Otherwise, scheduling would be greatly appreciated as the FDA has been urging us to enable self-reporting from our app, myHomeTest, via ReportStream at earliest.
In more detail, this is in accordance with our description on the app that self-reporting is expected to go through ReportStream in the software development plan.

Thank you for your cooperation!

**Comment by sliu1000** [comment]
Update from Sender:

Needs to submit their data no later than November 5, 2022.  They missed their last deadline and was given an extension.

Communication:

Thanks for your prompt response. 
And absolutely we have not enough time for our software (SaMD = mobile medical application) validation until due date given by FDA.
Our original due date was overed already. So, FDA gave one more chance about submission due date until 5th November. 
For this due date, we should perform the validation in next week using your API key and our system definitely. We have no way further more. 
So, please support us to give the API Key to StoneLab & OSANG Healthcate in this week clearly for our final software validation about system stream reporting. 
It is very urgent. 
I am sorry to push and bother you and thanks for your support in advance.
Best regards,
Philip Choi
OSANG HealthCare

**Comment by shy2cdc** [comment]
Dear Joel,

Good day. Thanks for your prompt response about API Key.

And I have question about your API Key.

Is this whether Test verion API key or real version rkey? (This is our partner question.)

Please kinldy inform me of that.

Thanks & Best reagards,

Philip Choi
