### ISSUE TITLE
O&O Tech Debt

### ISSUE THREAD

**Issue by sarahnw** [CDCgov/prime-reportstream#6436]
For all the things we know we need to do eventually

--- 
Talk with all team to prioritize the tickets in this epic.

Qs from Brandon:

- How bad is the debt?
- How many problems is it causing?
- Do we take on a certain # of issues per sprint?
- Do we take on a certain percentage (%) of issues per sprint?

**Comment by BerniXiongA6** [comment]
@brandonnava and @BerniXiongA6 discussed this epic and bring up with the rest of the team.
