### ISSUE TITLE
Support new reporting requirements for WA - by Jan. 1, 2023

### ISSUE THREAD

**Issue by sarahnw** [CDCgov/prime-reportstream#6438]
WA is requiring expanded values for Race/Ethnicity/Language of Preference for COVID-19 Case Reporting by January 1, 2023 

See this word doc in sharepoint for the complete list of updates required.
https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BB0131589-6B6D-4440-AE52-C9E55CD1933F%7D&file=Race_Ethnicity_Language%20Values_WAC%20246-101-011.docx&action=default&mobileredirect=true&cid=497c02f9-63e5-4234-b3ea-b2c39f8c2b97

This will require coordination with SR too. WA has offered to help test this functionality starting in Oct.

Acceptance Criteria
- RS has notified WA senders they will also need to conform with these new requirements
- RS can accept new values for Race
- RS can send more than one value for Race
- RS can accept new values for Ethnicity
- RS can accept new Language of Preference
- RS can send all the new information to WA

**Comment by sarahnw** [comment]
Latest from WA team:

Race changes:

- Do these have codes to go with them? And if so can you provide us with them? For example, in HL7, things like race look like "2028-9^Asian^HL70005", where the first value is the code, the second value is the display text, and the third value is the coding system.   
-- As Julie mentioned in our call today, they will have a spreadsheet soon with the corresponding HL7 and CDC national standard codes as well as a few local WA codes. 

- If we use a non-standard value, should we leave the ID value null?  
-- I believe that this will be answered in the upcoming spreadsheet. 

- For Alaska Native and American Indian in HL70005 these have the same code value. Are we ok to send the same code for both or do you have distinct codes for them you'd want us to use? 
-- They do need to be separate (and the same is true for Pacific Islander and Hawaiian Native).

- Related for these two categories, do you have definitions for these you'd recommend we use to help people select? 
-- No, we do not have any definitions to use to help people select.  The idea is to have people self-identify as whatever race/ethnicity they consider themselves – so they should pick whatever they see themselves as (which could be one or the other or both if they previously would have selected Alaska Native and American Indian).

Language of preference
- Do these have codes to go with them as well? What coding system and what codes for these values? 
-- The spreadsheet for race changes will also have any applicable codes for language of preference.

- Does WA only want a single preferred language? Can respondents specify more than one preferred language? 
-- Yes, WA wants only a single preferred language and respondents should only specify one.

- Do you want Dari and Farsi treated separately? 
-- Yes

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 bring into backlog refinement

**Comment by BerniXiongA6** [comment]
@brick-green please create ind. tickets for this epic

**Comment by GilmoreA6** [comment]
https://doh.wa.gov/public-health-healthcare-providers/notifiable-conditions/rule-making/supplemental-guidance-elr-submitters

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 reach out to SR about their work on this with WA DOH -- bring back to O&O team for next steps. cc: @brandonnava

**Comment by BerniXiongA6** [comment]
Hey @brandonnava could you connect with Laura King (via Slack) on this? I gave her a heads up that I'll be out the week she's back. I told her in advance that O&O will be reaching out as we'd like to find out what work they've done so far on this from a SR standpoint. That will help us to determine next steps on the RS end. Feel free to lean on @brick-green and Mo too if you need more background on this. Thanks!

**Comment by BerniXiongA6** [comment]
More updates to come from SimpleReport (Laura King and Mike Judd) on this topic (will be informing PRIME wide) cc: @brandonnava @BerniXiongA6

**Comment by BerniXiongA6** [comment]
@MauriceReeves-usds -- please add comments or add'l details on this epic in preparation for our sync with WA on Mon 12/19. Thanks so much ! cc: @brandonnava @brick-green

**Comment by BerniXiongA6** [comment]
@brick-green will connect with Mike Judd to create ind. tickets for this work -- new due date end of January 2023. cc: @brandonnava

**Comment by LaFreda1** [comment]
@brick-green have the tickets been made for this?

**Comment by brick-green** [comment]
@LaFreda1 No tickets yet. The plan hasn't been decided yet. There's a 30 min meeting scheduled for friday 17th with Simple REport to go over their research

**Comment by LaFreda1** [comment]
Closing this ticket. Refer to https://app.zenhub.com/workspaces/prime-reportstream-design-6400c6976f9c390010df623b/issues/gh/cdcgov/prime-reportstream/8479

**Comment by LaFreda1** [comment]
Closing this ticket. Refer to https://app.zenhub.com/workspaces/prime-reportstream-design-6400c6976f9c390010df623b/issues/gh/cdcgov/prime-reportstream/8479
