### ISSUE TITLE
Update the programmer's guide to v2.3

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#6444]
## Problem statement

Programmer's guide has been updated as part of this PR: https://github.com/CDCgov/prime-reportstream/pull/6439/files. We need to generate a PDF and update the site accordingly

## What you need to know

Previous PR: https://github.com/CDCgov/prime-reportstream/commit/8f25035f1355f875b63d18b76b4679b539e00042

## Acceptance criteria

- [ ] https://reportstream.cdc.gov/resources/programmers-guide links to new programmer's guide (v2.3)

## To do

- [ ] ...

**Comment by GilmoreA6** [comment]
@kevinhaube I've got a small update for the programmer's guide that didn't make it in with Jim's update. Can you hold off on this until PR#6433 get's completed so that those updates make it in?

**Comment by kevinhaube** [comment]
@GilmoreA6 Will do! 👍🏼

**Comment by kevinhaube** [comment]
Linking new dependency: PR #6467
