### ISSUE TITLE
Determine minimum data set for full ELR metadata

### ISSUE THREAD

**Issue by clediggins-usds** [CDCgov/prime-reportstream#6446]
### User Story:
As a reporter, I want deidentified metadata relating to full ELR files, so I can effectively generate reports.

### Description/Use Case
For covid files we have a covid_metadata table. We will need something similar for full ELR. Consider creating an Item table.

### Risks/Impacts/Considerations
* Need to 'future proof' as much as possible to have fewest changes as we move forward
* Determine if we are going to merge the existing covid metadata with the new tracking structure.

### Dev Notes:
* Consider all use cases

### Acceptance Criteria
* A plan on how to do this (table per type? Item table? hierarchy?) is agreed upon by the team
* We have buy-in from O&O and Experience on what will be stored
* Minimum metadata requirements are documented - what values, when will they be stored

**Comment by MauriceReeves-usds** [comment]
@clediggins-usds This should hopefully be handled by https://github.com/CDCgov/prime-reportstream/pull/7228

**Comment by carlosfelix2** [comment]
OBE. We are doing research on this
