### ISSUE TITLE
RI - Create organization and receiver settings

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#6456]
## Problem statement

Rhode Island will be a new jurisdiction connecting with report stream. They will need an organization and receivers added to the settings. There should be a receiver for testing and production.

## Acceptance criteria

- [ ] Organization created with jurisdictional filter for RI
- [ ] Receiver for test environment created
- [ ] Receiver for production env created

## To do

- [ ] Add organization and receivers to local org file
- [ ] create yml files in settings/prod and settings/staging
- [ ] add settings to staging
- [ ] add settings to production

**Comment by oslynn** [comment]
2022-08-29: I started to onboarding RI and sent the PRIME Onboarding Questions to RI and wait for their response.

**Comment by oslynn** [comment]
2022-08-30, get response back from Jason (RI).
Good Morning Ott,

I have answers below to your questions let me know what other information you may need in regards to this.

Engineering

A copy of the Implementation guide. We support the CDC HL7 2.5.1 Implementation Guide: Electronic Laboratory Reporting to Public Health (US Realm), Release 1 dated February 2010 as the most recent HL7 implementation guide.
Do you require a specific file name format? Currently there is no specific file name formatting implemented but if you are using a standard of some sort and can let us know it would be appreciated and would help us out.
Do you accept HL7 v2.5.1? Yes
What sending protocol do you use to accept files? We utilize SSH File Transfer Protocol(SFTP)
Do you accept HL7 batch messages? Yes
Is there a limit on the number of messages in a batch? We request that processing would be limited to a couple hundred messages within a batch message if a batch message is sent.
Frequency -we typically send files every two hours. We process messages hourly during business hours throughout the whole week.
HL7

What value do you want in MSH-5? MSH-5 can be populated as RI_DOH
What value do you want in MSH-6? MSH-6 can be populated as RI_DOH
Do you require us to put our own identifier and CLIA in MSH-4? MSH-4 should be populated as <Sending Facility Name>^<Facility CLIA Number>^CLIA
Would you like to receive the AoE questions? Yes
Do we need to suppress the QST flag in OBX-29? OBX-29 is not identified in the specifications so I would not think that OBX-29 would need to be suppressed.
Are there any other fields that are required? I have attached a FAQ that may assist in some of the required field information you may be looking for.
Do you require a specific value in MSH-21-1 (Message profile ID)? No

SFTP

How do we get credentials for an SFTP connection? We sent this information over to reportstream@cdc.gov as well as to Sarah and Brick. If we need to resend let us know.
Do the credentials need to be rotated/do they expire? Not currently.
Do you need to whitelist our IP addresses before we connect? Yes we do not have that information at this point in time.
What file path do we need to write files to on the SFTP server? For initial testing it would be the Staging folder you would utilize to start with.

Data Quality Filters

(How) Do you want to receive OTC results? Yes, as long as the demographic information is available as well for the patient information.


Thank you,
Jason Suchon

**Comment by oslynn** [comment]
2022-08-31.  Created PR and merged.

**Comment by oslynn** [comment]
Need to update -name: ir-doh to ir-phd

**Comment by oslynn** [comment]
2022-09-08.  Got the validation result from RI (Jason).

**Comment by oslynn** [comment]
2022-09-09: More setting and schema changed to produce hl7 according to RI need.
Emailed to Jason:

Good afternoon, Jason,

I uploaded the corrected sample hl7 file (covid-19-sample-20220909132810.hl7) to your SFTP Test folder.  
I updated the ReportStream setting to correct the message per your validation result.
Please validate it and let me know what else is needed.  Notice, we don't support the OBR-31.

Here is list what I corrected:

MSH-2
Encoding Characters is a required field and should be populated with ^~\& your system submitted us ^~\\&
Ott: in our message MSH-2 is ^~\&

PID-8
Patient Sex is required to be sent and was not present in 3 of the messages.
Ott: |F|

We request that ORC-12.1
Ordering Provider ID be suppressed if possible.
Ott: Suppressed

We request that OBR-16.1
Ordering Provider ID be suppressed if possible.
Ott: Suppressed

OBR-25
is appearing as F/r which it appears there may be an additional /r at the end of segments could this be looked at.
Ott: Need investigate.  Perhaps, something is adding /r

--------------------------------------------------------------------------

Optional Information that was sent incorrectly from message.

We request that PID-5.7
Patient Type be suppressed if possible.
Ott: Suppressed

PID-22.1
was specified as N which is not a valid value for the HL70189 code set please review and update correctly.
Ott: N - Non Hispanic or Latino
- name: hl70189
  system: HL7
  reference: HL7 guidance for ethnicity
  referenceUrl: https://www.hl7.org/fhir/v2/0189/index.html
  version: 2.9
  values:
    - code: H
      display: Hispanic or Latino
    - code: N
      display: Non Hispanic or Latino
    - code: U
      display: Unknown

ORC-12.4
Ordering Provider Middle Name
Ott:  Smith

ORC-22.2
Ordering Facility Street Address 2
Ott:  ^12345 Hammes Common 2^

OBR-16.4
Ordering Provider Middle Name
Ott:  Smith

SMP-18
Specimen Received Date/Time is appearing as 20220901225138\r which it appears there may be an additional /r at the end of segments could this be looked at.
Ott: something is adding /r

--------------------------------------------------------------------------

Optional Information that was not submitted but would be valuable to be sent if able.

PID-11.2
Patient Address 2
Ott:  ^27354 Dooley Overpass 2^

PID-14
Ott: blank

ORC-24.2
Ott: 12345 Rempel Plaza 2

ORC-24.6
Ott: USA

OBR-31
Ott:  Not supported

OBX-24.2
Ott: 12345 Ronny Locks 2

OBX-24.6
Ott: USA

--------------------------------------------------------------------------

Another thing to note none of the CLIA's you sent us were able to be found when looking them up is that normal?
Can you let us know what can be done in regards to these issues perhaps for correction? Were these production
messages being sent or test messages?
Ott: CLIA in this message is for testing only that is why is not valid.

May you have a wonderful weekend.​

Very respectfully,
-Ott Sathngam
CDC SW ENG

**Comment by oslynn** [comment]
2022-09-09: Created PR for suppressing ORC-12-1, OBR-16-1, PID-5-7 and update covid-19.schema to produce output HL7 fields ORC-24-6 and  OBX-24-6.

**Comment by BerniXiongA6** [comment]
@oslynn closing this ticket and continue working on[ # 6457](https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/6457)
