### ISSUE TITLE
RI - Test HL7 message structure and content

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#6457]
## Problem statement

The HL7 structure needs to be tested with RI. They will need messages sent through the test feed first as fake data. When that passes validation, then LIVE messages should be sent

## Acceptance criteria

- [ ] Fake messages sent to RI
- [ ] RI accepts HL7 structure of fake messages
- [ ] Live messages sent to RI
- [ ] RI accepts HL7 structure of live messages

## To do

- [ ] Create HL7 files from CLI with fake data
- [ ] received feedback on fake messages
- [ ] implement settings changes as needed
- [ ] Send live HL7 files from CLI
- [ ] received feedback receive feedback on fake data

**Comment by oslynn** [comment]
2022-09-06: Fake HL7 RI generated and uploaded to their SFTP test directory.

**Comment by oslynn** [comment]
2022-09-13.  Got response from Jason to correct MSH-3-2 and MSH-3-3.
I corrected and ran through RS to product output for validation.  Email back to him:

Jason,

ReportStream is adding MSH-3-2 and MSH-3-3 to RI message as following:
MSH-3:  Sending Application:                    
  MSH-3-1:                                      CDC PRIME - Atlanta, Georgia (Dekalb)
  MSH-3-2:                                      2.16.840.1.114222.4.1.237821
  MSH-3-3:                                      ISO

I uploaded the latest message (covid-19-sample-20220913160031.hl7) to your SFTP staging folder.  
Please validate and let me know.  If it is all good, I will route production message to your site.

Best regards,
-Ott Sathngam
CDC SWE.

**Comment by oslynn** [comment]
Prod and Staging database setting are updated.

**Comment by oslynn** [comment]
2022-09-15. Jason (RI) responded that both sample and production messages are good.  He then as for couple more production data to run more test.

"--- email --
Good Morning Ott,

I did see those come through and they both looked fine from my review so far. Could you send a couple more both positive and negative results through to our test region that are production specific messages so we can review those and get some state feedback specifically about those and let me know when they are submitted?

Thank you,
Jason Suchon

" =========
I got 3 messages with negative and positive result for him.

**Comment by oslynn** [comment]
2022-09-19: Got response from Jason requested for more prod messages that contain "detected" and "not detected" results.  I got 6 messages that contains detected and not-detected result back to him.
"==== email ====
Good after noon, Jason,

I just submitted to your SFTP/Stagging a production data file (covid-19-production-data-with-dectected-and-notDetected-20220919144141.hl7).  It contains 6 messages with not detected and detected results (Observation Values) per your requested.
Please let me know the result as soon as you can.

If anything else that I can do please let me know.

Grateful, indeed.
-Ott Sathngam
CDC SWE.

**Comment by oslynn** [comment]
2022-09-21: RI, Jason, requested one of the last message to fix PID-11-3.  He also requested another set of production data for further testing.
"=== Email to Jason ===

Good after noon, Jason,

I just submitted to your SFTP/Staging another production data file (covid-19-production-data-with-detected-and-notDetected-2022-09-21-175453.hl7).  
It contains 6 messages with not-detected and detected results (Observation Values) per your requested.

Please let me know the result as soon as you can.

If anything else that I can do please let me know.

Grateful, indeed.
-Ott Sathngam
CDC SWE.

**Comment by shy2cdc** [comment]
Email from Jason:

Good Afternoon Ott,

A couple of questions in regards to this.

1. Is this the schema that would be being used then from me looking at Appendix C?
https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md

prime-reportstream/primedatainput-pdi-covid-19.md at master · CDCgov/prime-reportstream
Contribute to CDCgov/prime-reportstream development by creating an account on GitHub.
github.com

2. How do we identify which ones in the schema you flag already and would already go back to the facility on if the information is not sent across?

Just trying to work on getting some documentation around this on our end for the future and how to resolve issues perhaps that may crop up.

Thank you for any additional information,

**Comment by shy2cdc** [comment]
Email from Jason:

Good Afternoon Ott,

I just wanted to get some clarification in regards to what you have stated in regards to this to start with as we are working with the state on getting some clarification on some of this prior to approving a go-live.

1. When you conduct onboarding with a sender you advise them to include all required fields as given in your schema.
2. I understand there is no flagging whatsoever to route anything back to the facility if they are not sending you a required field in your schema is that correct?
3. From step one the message would get processed through your system and filter out what we mentioned we would want filtered out as well as modifications for table differences and then it would get sent over to RI.
4. If there is an issue with the messaging in RI then you would expect to be notified to have the message corrected and go back to the initial sender to correct the initial message?

Jason Garrett and Michael Gosciminski if you have additional questions regarding this specifically please feel free to chime in as well.

Thank you,

Jason Suchon

**Comment by oslynn** [comment]
2022-09-26: RI is ready for production.  I will start working on moving them to production.

Email from Jason Suchon,

Thank you for the clarification, @Sathngam, Ott (CDC/DDPHSS/OD/HITSSU).
@Jason Suchon – RI is good to go for moving to production with this onboarding.  Please coordinate with Ott and the Report Stream team to move forward.

Best
Jay

 

Best,

Jay

**Comment by shy2cdc** [comment]
Email from Michael:

Hi All,

Jason Garrett is out of the office this week and will be returning next Tuesday.  If possible, could this wait until he is able to formally approve it sometime early next week?

Thanks for your consideration.

**Comment by oslynn** [comment]
2022-10-05.  Confirmed from RI.  They are good to go for prod.  I activated them and close this ticket.
