### ISSUE TITLE
WA - Missing LOINC - Need SafeHealth to resubmit

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6459]
## Problem statement

Received request from Jennifer Risler from WA via Smartsheet Submission Form.  Regarding a **Missing LOINC, please resubmit.**

## What you need to know

MSH|^~\&|CDC PRIME - Atlanta, Georgia (Dekalb)^2.16.840.1.114222.4.1.237821^ISO|7uycso49^1.3.6.1.4.1.38630.2.1.1.519^ISO|WADOHPHRED^2.16.840.1.113883.3.237.4.2^ISO|dn1fro00^1.3.6.1.4.1.38630.2.1.1.19^ISO|20220822191609-0000||ORU^R01^ORU_R01|SH00116_`fffb180bf847466496d1cc3baa2ae5e7`|P|2.5.1|||NE|NE|USA|UNICODE UTF-8|ENG^English^ISO||PHLabReport-NoAck^ELR_Receiver^2.16.840.1.113883.9.11^ISO

OBX|1|CWE|^^LN

## Acceptance criteria

- Resubmission of Missing LOINC

## To Do
- Research
- Assign

**Comment by sliu1000** [comment]
Second Request from Jenni Risler - jenni.risler@doh.wa.gov

Missing LOINC, please resubmit.

MSH|^~\&|CDC PRIME - Atlanta, Georgia (Dekalb)^2.16.840.1.114222.4.1.237821^ISO|7uycso49^1.3.6.1.4.1.38630.2.1.1.519^ISO|WADOHPHRED^2.16.840.1.113883.3.237.4.2^ISO|dn1fro00^1.3.6.1.4.1.38630.2.1.1.19^ISO|20220822191609-0000||ORU^R01^ORU_R01|SH00116_`fffb180bf847466496d1cc3baa2ae5e7`|P|2.5.1|||NE|NE|USA|UNICODE UTF-8|ENG^English^ISO||PHLabReport-NoAck^ELR_Receiver^2.16.840.1.113883.9.11^ISO

OBX|1|CWE|^^LN

**Comment by sliu1000** [comment]
Received another Smartsheet Service Request from WA State - Jennifer Risler (jenni.risler@doh.wa.gov):

missing LOINC, please resend

MSH|^~\&|CDC PRIME - Atlanta, Georgia (Dekalb)^2.16.840.1.114222.4.1.237821^ISO|7uycso49^1.3.6.1.4.1.38630.2.1.1.519^ISO|WADOHPHRED^2.16.840.1.113883.3.237.4.2^ISO|dn1fro00^1.3.6.1.4.1.38630.2.1.1.19^ISO|20220823171610-0000||ORU^R01^ORU_R01|SH00116_`638392009b3246adbe7e6b693af75bc3`|P|2.5.1|||NE|NE|USA|UNICODE UTF-8|ENG^English^ISO||PHLabReport-NoAck^ELR_Receiver^2.16.840.1.113883.9.11^ISO

OBX|1|CWE|^^LN

**Comment by sliu1000** [comment]
Another one received on 8/23/2022 @ 5:10 PM:

Missing LOINC, please resend

MSH|^~\&|CDC PRIME - Atlanta, Georgia (Dekalb)^2.16.840.1.114222.4.1.237821^ISO|7uycso49^1.3.6.1.4.1.38630.2.1.1.519^ISO|WADOHPHRED^2.16.840.1.113883.3.237.4.2^ISO|dn1fro00^1.3.6.1.4.1.38630.2.1.1.19^ISO|20220823191618-0000||ORU^R01^ORU_R01|SH00116_`40a23f40ed68477da624ad7d6a15ed46`|P|2.5.1|||NE|NE|USA|UNICODE UTF-8|ENG^English^ISO||PHLabReport-NoAck^ELR_Receiver^2.16.840.1.113883.9.11^ISO

OBX|1|CWE|^^LN|

**Comment by BerniXiongA6** [comment]
@sliu1000 Hi Sharon, we've flagged this as medium priority. It might make it to this sprint or the next so let's hang tight for now. We talk to WA DOH next Monday so we can update them then.

**Comment by oslynn** [comment]
2022-09-20.  Analyzed the message and verified that sender (SafeHealth) didn't fill the LOINC code (OBX-3).  I requested them to resubmit the message.
" === email ===
Dear: Dave Cassell, or Santosh Jami,

My Name is OTT SATHNGAM.  I am an Engineer who assigned to work on your message with message ID = SH00116_fffb180bf847466496d1cc3baa2ae5e7 that sent to WA.  
It was sent around 2022-08-22.  The message is missing the LOINC Code or test_performance_code (HL&: OBX-3-1, OBX-3-2, OBX-3).  Would you please fill the 
in the LOINC code and resubmit to us.

If you have any question, please feel free to contact me.

Best regards,
-Ott Sathngam
CDC SWE

**Comment by sliu1000** [comment]
TEST__RESULT	PERFORMING__ORG__NAME	WELRS__HC	WELRS__ASSIGNED__HC__MANUAL	WELRS__MSH__ID	SUBMITTER__UNIVERSAL__ID__MSH_0402
Detected	SA.OTCSelfReport	COVID-19	False	386665667	1.3.6.1.4.1.38630.2.1.1.519
Detected	SA.OTCSelfReport	COVID-19	False	386665695	1.3.6.1.4.1.38630.2.1.1.519
