### ISSUE TITLE
Store raw received content in a folder and in a format that sorts by date. 

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#646]
Change the internal filename from `<schema>-<report-id>-<date>` to `<schema>-<date>-<report-id>` to sort report filename better.

**Comment by MauriceReeves-usds** [comment]
@carlosfelix2 - this came out of a discussion we had where we recognized we could end up having name collisions for different receivers going ahead and we needed to start organizing the data we're receiving in folders by receiver name, and then also changing the file name format to put the date before the report ID so they sort correctly.

**Comment by MauriceReeves-usds** [comment]
This will require an announcement sent to the STLTs that we are going to be changing the default file name.

**Comment by MauriceReeves-usds** [comment]
@BerniXiongA6 - I'd like to get this pushed to production in the next milestone, which means we need to communicate to some of the STLTs that there will be a minor change to the file names, to prep them. Can we put some time on the calendar at the beginning of the week like Tuesday or Wednesday to discuss?

**Comment by BerniXiongA6** [comment]
Sounds like a good plan @MauriceReeves-usds 

Here's my availability:
Tues 7/6 10 AM-11 AM ET
Wed 7/7 10 AM - 12 PM ET, or anytime after 1:30 PM ET

**Comment by BerniXiongA6** [comment]
RS File Name Format Change Email templates sent to @MauriceReeves-usds : 

Version A

[https://app.zenhub.com/files/304423150/d63f15a3-e350-440d-96db-0c5c0d0e1962/download](https://app.zenhub.com/files/304423150/d63f15a3-e350-440d-96db-0c5c0d0e1962/download)

Version B

[https://app.zenhub.com/files/304423150/1c61b8d4-9072-4e8f-84e5-2b6f3926ac02/download](https://app.zenhub.com/files/304423150/1c61b8d4-9072-4e8f-84e5-2b6f3926ac02/download)

**Comment by BerniXiongA6** [comment]
Hey @MauriceReeves-usds I've made some slight edits to the email templates for "RS File Name Format Change" and have attached the revisions below. No worries if you've already sent them out, the corrections were minor. Wanted you to have updated templates just in case.

Version A
[https://app.zenhub.com/files/304423150/a798bdac-d862-48c3-b8ce-d95151832434/download](https://app.zenhub.com/files/304423150/a798bdac-d862-48c3-b8ce-d95151832434/download)

Version B
[https://app.zenhub.com/files/304423150/fdc5876e-8c77-4040-af23-1854a6770d85/download](https://app.zenhub.com/files/304423150/fdc5876e-8c77-4040-af23-1854a6770d85/download)
