### ISSUE TITLE
Send EpiTrax a list of all NV senders

### ISSUE THREAD

**Issue by sarahnw** [CDCgov/prime-reportstream#6461]
Send EpiTrax a list of all NV senders

**Comment by sliu1000** [comment]
update from user Linda King (Linda@endpointdev.com) on 8/25 @ 5:58 PM:

Hey Brick,

No, we don't have any specifics for the file name.  Thanks so much for the sample messages, I will be reviewing and getting back to you soon.

Take care.
Linda

**Comment by sarahnw** [comment]
List of what I've pulled so far here https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Onboarding%20%26%20Ops/STLTs/Nevada/NV%20Senders.xlsx?d=wae2275b32ff54e4692e563c0dfd1e7e8&csf=1&web=1&e=B1UDg9

This includes distinct CLIAs where patient state is NV, sender ids where patient state is NV, and ordering facility name where patient state is NV

**Comment by sarahnw** [comment]
Assigning this to @MauriceReeves-usds to take over for me with filling in the rest. Thanks Mo!

**Comment by brick-green** [comment]
@MauriceReeves-usds I don't know if this is really necessary anymore. We're switching NV over to EndPoint today at 1:00PT.
