### ISSUE TITLE
Create a new feed for NV while moving to EpiTrax

### ISSUE THREAD

**Issue by sarahnw** [CDCgov/prime-reportstream#6463]
@MauriceReeves-usds recommends we set up a separate feed for EpiTrax. We will want to set up 'deidentify: true' for their feed until we get the all-clear to move to production which should happen by Sept 9th at the latest.

**Comment by brick-green** [comment]
sent reportstream SFTP outbound IP range to Linda and kevin at EndPoint

**Comment by brick-green** [comment]
SFTP connection information from EndPoint saved to keybase

**Comment by brick-green** [comment]
PR out for updating local settings

**Comment by brick-green** [comment]
sftp setup in azure

**Comment by brick-green** [comment]
receivers configured in staging and production. Currently they are set to "allowNone()". So no results will flow to them.
