### ISSUE TITLE
Send EpiTrax deindentified info to test connection

### ISSUE THREAD

**Issue by sarahnw** [CDCgov/prime-reportstream#6464]
We should send some deindentified NV results to NV's new EpiTrax connection to make sure things are working and they're handling our data correctly. 

@MauriceReeves-usds or @brick-green could you add any more details here?

**Comment by brick-green** [comment]
Sent fake HL7 messages via email to start the validation process while we wait for whitelisting via CDC palo alto

**Comment by brick-green** [comment]
update from user Linda King (Linda@endpointdev.com) on 8/25 @ 5:58 PM:

Hey Brick,

No, we don't have any specifics for the file name. Thanks so much for the sample messages, I will be reviewing and getting back to you soon.

Take care.
Linda

**Comment by brick-green** [comment]
Message queued to send to NV.

**Comment by brick-green** [comment]
Test message sent to end point and they confirmed receipt!
