### ISSUE TITLE
TN - Missing required information from results from ^05D2195670^CLIA

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#6471]
Angie - ceds.informatics@tn.gov 8/23 10:32am

Starting on 8/15, TN started receiving results from CDC Prime for what looks to be a new sending facility. The following are missing from the 15 messages received so far: 

MSH-4.1: You are only sending ^05D2195670^CLIA
OBR-4.1 and OBR-4.2
OBX-3.1 and OBX-3.2

We would need all messages for this new facility resend. We would also ask that when possible to inform us when you go live with a new MSH-4 so that we can keep an eye out of issues quickly. Below are a list of messages to resend. If resending using the same MSH-10, we ask that .rerun be appended to each file or one single file if sending a batch to avoid the messages from being flagged as duplicate.

`SH00116_a8b496e2c9f5474ba65c4c8f2f20ee66`
`SH00116_cf42888c78da461c981fa335c58b838c`
`SH00116_073678df92b144799b3e26d9c8558d0b`
`SH00116_b370d077deaa4628844497edda627ab3`
`SH00116_ff2637129806485cbae4beab9a68d567`
`SH00116_b1100993e6c14f43a84f094ca3841ab2`
`SH00116_41f0c50509f54742b691c62ef323139d`
`SH00116_7aff0d00114541f4aab5a06c46969bd0`
`SH00116_b67d5c4e88944d58b9c921a0be688a01`
`SH00116_c9e723fd158d434bac08cb9c9b3416a7`
`SH00116_00ff5870c054419282d6cc82464fa5f9`
`SH00116_312ff4eb5f9749ab91f0eec34b895b10`
`SH00116_aa9e3c3e3a7a4ea082c8edfec5ec1969`
`SH00116_d9ecb6b90f624590ac03873a39b47aa2`
`SH00116_4e4a18cae0364eaab679831abaa39bbf`

**Comment by Jcavallo7** [comment]
Hello,

Any updates on fixing this issue as we are still get messages that we cannot process.

Thanks,

Angie

**Comment by GilmoreA6** [comment]
This issue is related to the SafeHealth Epic issue that they are currently correcting. SafeHealth is currently working on modifying their submission csv file to RS so that the data quality issues are resolved.

**Comment by sliu1000** [comment]
Sent Senders update, please see below the communication to TN - CEDS.Informatics@tn.gov and LA - tania.bechtel@la.gov:

Greetings,

We have been working with the original sender and they advised that they will release their updates into production today.

Thank you for your patience.

Best regards,

Sharon
The ReportStream Support Team

Contact us at reportstream@cdc.gov
Support hours:  8:00 am through 9:00 pm Eastern time
Monday-Friday, excluding US public holidays

**Comment by sliu1000** [comment]
TN asked if the they will be receiving all the messages from the original sender.

**Comment by sliu1000** [comment]
Update requested from TN - CEDS Informatics:

Hello,

We wanted to check if all these messages have been resent to TN?

Thanks,

CEDS Informatics

**Comment by brick-green** [comment]
Not yet. They sent a sample backlog on monday but there were still issues with the messages. So I sent feedback yesterday. Not sure about a timeline but I relayed the importance of reporting results in a timely manner.

**Comment by sliu1000** [comment]
@brick-green I'll let them know that we are still waiting on the Sender to update/finalize the messages prior to sending back out.

**Comment by shy2cdc** [comment]
Email from CEDS:

Hello,

We wanted to check if messages have been resent?

Thanks,

CEDS Informatics

**Comment by sliu1000** [comment]
Update from CEDs Informatics on 10/3/2022:

Hi Sharon,

**We did not get any confirmation that the messages were resent**. Please confirm this on your end and we would check if we received anything.

Thanks,

CEDS Informatics

**Comment by sliu1000** [comment]
Update from TN CEDS Informatics on 3:50 PM:

Hello,

TN can confirm we received 28 backlog of messages that has previously failed to process in our system and has no issues with them. We consider this case closed. 

Thanks,

CEDS Informatics
