### ISSUE TITLE
Design - Email notification for support tickets - MVP

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6473]
## Problem statement
As a user, I want to be notified when a support ticket for ReportStream is created, closed, or needs more information so that I do not have to spend time and effort sending and monitoring emails to check on status of my tickets.

The email notification serves an additional purpose of saving time for O&O team to manage these email requests for status on support tickets.

## What you need to know
Smartsheet with support tickets:
https://app.smartsheetgov.com/sheets/w66xJvFr578CcCCfJ6RrxPCfg2qJV9X9hhp2HvF1?view=grid
Link to create a support ticket - https://app.smartsheetgov.com/b/form/ff33efa457be461c9893301d4c0ec12d
MVP events - Create, Close, Needs more info(when the ticket is waiting for information from user)
Scope - Sending the email notification is excluded from scope of Experience team's work at this time. The email will be sent by Helpdesk via Smartsheet.

Sharon Liu is working on a workflow for support tickets - to be shared with Experience and O&O team when ready.

## Acceptance criteria

- A design/wireframe/figma artifact outlining the following:
    - Events when the email notification will be sent
    - Fields to be included in the email(subject, salutation, body, ending, ticket fields)
     - Font/formatting (as allowed by Smartsheet's email notification service)
 
## To do
- Define what fields from the support ticket on Smartsheet should be included in these notifications
- Work with Sharon to figure out Smartsheet notification system and constraints that would apply to the design

## Things to consider 
- How this fits in the overall Customer Support Center initiative

**Comment by RakshindaAslam** [comment]
@a-chappelear @sliu1000 @drew-usds

**Comment by HeatherRienks** [comment]
This might be a dupe.

**Comment by sliu1000** [comment]
@HeatherRienks This is something Rakshinda and I were working on. But I think we can close this out.

**Comment by HeatherRienks** [comment]
@sliu1000 - sounds good - closing!
