### ISSUE TITLE
CA - Problem for access data

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#6475]
Elaine Li - elaine.li@phd.sccgov.org 8/23 3:19pm

I want to report that I’m not able to access my data again. It is wired because I could download the report last Tuesday, the last time I used the system. However, When I logged in today, there were no results/files under the daily data tab. Can you please let me know if any updates or new versions were released that impacted my access?

![image.png](https://images.zenhubusercontent.com/62827d1e0129e15b5c366b1a/674a7fdb-9875-44c8-9361-0bc91755ae4e)

**Comment by sliu1000** [comment]
@BerniXiongA6 

Per user (Elaine Li, they are able to access the data now).  I think we can close this one.
