### ISSUE TITLE
Refactor App.tsx for ease of use

### ISSUE THREAD

**Issue by doug-s-nava** [CDCgov/prime-reportstream#6486]
## Problem statement

As a ReportStream developer I want to be able to easily understand the fundamental pieces of our application easily, and easily make changes to one piece of the app without affecting others.

Currently our App.tsx file contains:
* our main routing information
* the application scaffolding (global providers and wrapping components)
* routing and auth logic

It does not contain:
* the actual router component, which is in index.tsx

As the main entry point of our app, it makes sense that it contains some of this stuff, or even bits of all of it. The app would be better served, however, if:
* list of routes was moved to its own file
* all wrapping / provisioning elements were in their own file, outside of App
* other logic in this file was kept to a minimum

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] App.tsx is smaller, more focused, easier to work with
- [ ] Routes are in their own file

## To do

- [ ] ...

**Comment by kevinhaube** [comment]
Closed by PR #6597 (Adoption of Router v6)
