### ISSUE TITLE
Possible vulnerability

### ISSUE THREAD

**Issue by snesm** [CDCgov/prime-reportstream#6491]
## Problem statement

Possible vulnerability detected by Snyk code scan

## What you need to know

- [Snyk finding](https://app.snyk.io/org/prime-reportstream/project/980e6e3c-7075-4866-b014-efa3b037bfa1#issue-ad4e8af9-0283-426d-8db6-cd8ebd737c93)

- ...

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by bgantick** [comment]
@snesm The link to the screenshot seems to be invalid and I'm not sure anyone on our team has access to the Snyk UI ("You are not a member of this organization.")

**Comment by bgantick** [comment]
Update: It looks as though this might not actually be an issue, but will get factored out with some work we have coming up within the next week or two.

**Comment by snesm** [comment]
Thanks @bgantick 

Is there another Issue or PR that can be linked to this?

**Comment by bgantick** [comment]
#6526
