### ISSUE TITLE
[SPIKE] [Validation Service] Make validate endpoint open (no authorization required)

### ISSUE THREAD

**Issue by ahay-agile6** [CDCgov/prime-reportstream#6495]
## Problem statement

Unauthenticated users (i.e. users without login) need access to the validator UI and endpoint. To achieve that, we need to ensure our endpoint is opened up safely before the UI is made public.

## What you need to know

Previous research: https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6093

We have an existing endpoint. This endpoint needs to be opened up, safely, to be used on an unauthenticated front-end page. Existing security concerns:

### Security concerns

- have rate limit restrictions per source (100/ip/minute? 5-10/ip/min?)
- We could make the validator a stateless Azure function separate from the main prime_dev one, which could potentially limit some risk as well, and allow for individual tuning of each

### Open questions

- [ ] How does our rate-limiter work? (We know it's through Akamai, but need details.)
Akamai: another team needs to update the rate-limiter. Tell them which endpoint/paths, what limits we want, flex past the limit? get a zoom call to get resolved faster
- [ ] Do we need to limit this public page more than other pages? Can we even do that?
- [ ] Do we need to separate the endpoint in any way from the `prime_dev` container that other functions run in? Do we gain anything by doing this?

### Documentation
- [ ] Documented answers to `Open questions`
- [ ] Documented proposal on a path forward
### Implementation (as discussed in 8/29 session with Jim)
- [x] Factor out authentication from `ValidateFunction.kt`
- [x] Add a max items check to HL7 serializer (or somewhere more relevant)
- [x] Adjust size limits lower for authentication endpoint (file size, row/column size, etc)
- [x] Configurable  payload size for validation endpoint
- [x] Create generic senders for HL7 and CSV for the purposes of submitting data via the validation page
- [x] Work with DevOps to load test adjusted endpoint in demo environment

## To do

- [x] Talk to DevOps about implication for opening up the validate endpoint to the world vs token/auth/header usage
- [x] Create generic senders for HL7 and CSV for the purposes of submitting data via the validation page?
- [x] Allow an unauthenticated user to send data to the `/validate` endpoint by allowing the specified generic senders to send data without authentication

---
## Load Testing
Using the load testing tool k6, we were able to create a script that hits the endpoint several times concurrently as if several users are using the tool at once, or there is a (D)DOS attack going on

1. 1000 virtual users over 120s with a "relatively small" payload - no errors expected from the server
```
running (2m30.0s), 0000/1000 VUs, 2714 complete and 296 interrupted iterations
default ✓ [======================================] 1000 VUs  2m0s

     data_received..................: 30 MB  201 kB/s
     data_sent......................: 31 MB  205 kB/s
     http_req_blocked...............: avg=745.54ms min=160ns   med=390ns   max=3.82s    p(90)=2.53s    p(95)=2.63s   
     http_req_connecting............: avg=64.62ms  min=0s      med=0s      max=421.87ms p(90)=268.65ms p(95)=301.5ms 
     http_req_duration..............: avg=45.98s   min=8.38s   med=47.96s  max=1m0s     p(90)=58.58s   p(95)=1m0s    
       { expected_response:true }...: avg=43.72s   min=8.38s   med=46.09s  max=59.99s   p(90)=54.3s    p(95)=56.29s  
     http_req_failed................: 14.77% ✓ 412       ✗ 2377  
     http_req_receiving.............: avg=11.12ms  min=0s      med=2.2ms   max=385.24ms p(90)=31.66ms  p(95)=39.39ms 
     http_req_sending...............: avg=87.69µs  min=32.59µs med=78.71µs max=262.25µs p(90)=142.57µs p(95)=156.65µs
     http_req_tls_handshaking.......: avg=629.92ms min=0s      med=0s      max=3.55s    p(90)=2.16s    p(95)=2.32s   
     http_req_waiting...............: avg=45.97s   min=8.38s   med=47.95s  max=1m0s     p(90)=58.58s   p(95)=1m0s    
     http_reqs......................: 2789   18.592346/s
     iteration_duration.............: avg=47.9s    min=9.39s   med=50.06s  max=1m1s     p(90)=1m1s     p(95)=1m1s    
     iterations.....................: 2714   18.092372/s
     vus............................: 297    min=297     max=1000
     vus_max........................: 1000   min=1000    max=1000
```
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/77dde6ea-65f4-4de8-9742-a1e689a2da8e)

The server slowed down quite a bit to the point where some requests timed out and no response was given

**Comment by bgantick** [comment]
Pending security audit on strategy

**Comment by RakshindaAslam** [comment]
@ahay-agile6 @bgantick - do we have enough information to refine and include this in the upcoming sprint? cc @HeatherRienks

**Comment by kevinhaube** [comment]
Notes from Exp Eng Sync:
- Maybe this makes more sense as a SPIKE to kick off an epic
- Work looks distributed across all teams, not exclusive to us
- Work load is more than a single sprint's worth

The consensus is that this seems like a SPIKE more than a unit of work exclusively for the Experience team. The proposal is that we use this ticket as the SPIKE, re-written with the AC to determine who's needed, form a plan, and write separate tickets of work to be pointed and completed.

**Comment by kevinhaube** [comment]
Re-worded as research AC instead of engineering AC

**Comment by kevinhaube** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/6495?planning-poker) with Zenhub @ahay-agile6 @sethdarragile6 @bgantick @doug-s-nava

**Comment by HeatherRienks** [comment]
Will be an "implementation spike" ticket, rather a discovery ticket. per Standup on 8/30

**Comment by bgantick** [comment]
Added more acceptance criteria (cc @ahay-agile6)
