### ISSUE TITLE
Service map for STLT-facing features

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6503]
## Problem statement

As a STLT who uses Reportstream to ingest data into their state surveillance system I want to be able to track and monitor (i.e. see and access) information on the data that is being sent to me through Reportstream, what issues there are with the data, how frequently the data is being sent, and by whom (what facilities including stats on that facility). 

As a product, ReportStream needs to be tracking and displaying test result metrics and progression in ReportStream.

To address this problem, RS needs to first understand the scope of all services that need to be built, reused or updated given the current services available. 

## What you need to know

Mural board with feature break-down for this initiative
https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1660849046968/e257020850ab71f57b31120e27ec06203ae9c22b?sender=u3fea607b46e84058d3224917
- Design has examples of service maps from CSV upload and support

## Acceptance criteria
 
- [x] Do it in Mural! (ex: support or CSV upload blueprints)
- [x] User type(s) are indentified. Currently: [Internal/admin, STLT, sender]
- [x] Outlines what each user type wants to do/learn/etc, including ...
  - [x] How STLTS can view list of currently connected senders
  - [x] How STLTS can see daily activity per each sender
  - [x] How STLTS can get help/take action when any problems arise
- [x] Goal of this ticket is to get enough info for the MVP; doesn't need to be comprehensive service plan!

## To do

- [x] Create Mural board
- [ ] ...
- [x] Get feedback from Andrea & Victoria

**Comment by RakshindaAslam** [comment]
@a-chappelear @drew-usds @HeatherRienks - This ticket is created as a shell..will need more details in pre-refinement.

**Comment by HeatherRienks** [comment]
@drew-usds and @victorialb-usds will own this ticket, per Design Sync on 8/25.

**Comment by RakshindaAslam** [comment]
@drew-usds @victorialb-usds - we need to refine this ticket so we can have a clear understanding of the outcome of this ticket.

**Comment by HeatherRienks** [comment]
@bgantick - any specific info that is needed from an Eng perspective on this ticket?

cc @a-chappelear

**Comment by victorialb-usds** [comment]
@drew-usds @a-chappelear updated the problem statement. To-dos may need to be added.

**Comment by victorialb-usds** [comment]
Began mural here: https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1661979707820/db6b8a08700ccd21fb842da7ac3fa61a476d6d02?sender=u4a60651bc33557d542d18858

**Comment by HeatherRienks** [comment]
@victorialb-usds @drew-usds - Hoping that @fmccaf1 could help you with this ticket!

**Comment by victorialb-usds** [comment]
@drew-usds @fmccaf1 the journey maps are done (MVP) and I can work on the blueprint on Monday and perhaps we can discuss this at our sync which I think needs to move a bit b/c of meeting conflict. @fmccaf1 if you want to co-work on the blueprint Monday LMK.

**Comment by HeatherRienks** [comment]
Moving this to Product Backlog, as it is not tracking as part of current sprint work.

**Comment by victorialb-usds** [comment]
@a-chappelear @drew-usds @fmccaf1 think we can wrap this up. I am sure there are things that need to be added/moved. Your experience with blueprint and service design needed. There is a key that indicates the colors and I have made notes on the side about next steps this does not include answering all the questions in the pink post-its.

**Comment by victorialb-usds** [comment]
Noting to schedule in research to understand users internal and external is needed and then usability of features as they are developed.

**Comment by RakshindaAslam** [comment]
@HeatherRienks - can we schedule a review of this with the entire team sometime next week?

**Comment by HeatherRienks** [comment]
@RakshindaAslam - yes, I will coordinate with the Design Crew to review this with the team.

**Comment by fmccaf1** [comment]
I connected w/ Berni about getting O&O's eyes on this to fill in some gaps. We'll try to get together briefly on Friday and if we need more time (I think we will), then we'll continue the convo next week. @victorialb-usds I'm assuming you're interested in coming too so I'll make sure you're added to everything!

**Comment by victorialb-usds** [comment]
Some summary points: 
Doing this journey maps and blueprint revealed

- Too many tasks in the original ticket to put on the service blueprint was too many to answer the questions in the ticket
- Many of the pieces in the map are future state, that is OK to lay out where we are going AND we often have the information to make the future state actions, expose the information possible
- STLTs are getting things done outside of Reportstream/in different ways that we need to understand better (e.g. research roadmap)
- O and O are doing the lions share of data monitoring and resolution manually (need to understand this more see @fmccaf1 above)
- We have many questions about how things are currently done without knowing where these are documented or there is a need to document them (this can be added to a research roadmap and will be somewhat answered by what @fmccaf1 mentioned above)
- There is over lap with the story map; this visual adds.... in future discuss relationship between different steps 

To do for future: 
- Break up the blueprint more

Next:
- Start with the daily index as priority feature to discuss next steps as team/product and ID tasks to ticket
- Create a Research roadmap: doing this brought up many questions with a priority on understanding what is currently actually happening for users to accomplish the tasks outlined in the service blueprint talk about what does and does not exist; sessions w O and O and FM
- Do a cross disciplinary feature discussion of daily data to make a decision on next steps and what each discipline for this specific work will do as well as will do to move towards some of the next work laid out. (what @HeatherRienks is scheudling)

**Comment by victorialb-usds** [comment]
https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1661979707820/db6b8a08700ccd21fb842da7ac3fa61a476d6d02?sender=u4a60651bc33557d542d18858

**Comment by HeatherRienks** [comment]
Link to recording of @victorialb-usds sharing with the team on 10/5/22
https://us06web.zoom.us/rec/share/y94OLZIC6LF4Qaln2cu7wQPMH8Ppn0XZl56rWZofuV9bblWqMbDnNwgHvYKdpSnE.icknIn7sWUUEWnCw?startTime=1664989532000
