### ISSUE TITLE
CO - CDPHE ELR Onboarding automated error message [Error: Cannot Write File to DB]

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6505]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, `covid-19-dca4a58d-41ed-41c3-8eb9-6b8bc97a8a33-20220819013031.hl7`).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Onboarding
Received on: 2022-08-19 01:30:27
File source: CDC PRIME
File name: `covid-19-dca4a58d-41ed-41c3-8eb9-6b8bc97a8a33-20220819013031.hl7`
Performing Org Name: null

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by sliu1000** [comment]
Second Automated Email from CO CDPHE: Sent 8/25/2022 at 9:08 AM

This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-d7cb7f13-0eed-4ac1-920f-afd5188f4e74-20220819013025.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Onboarding
Received on: 2022-08-19 01:30:24
File source: CDC PRIME
File name: covid-19-d7cb7f13-0eed-4ac1-920f-afd5188f4e74-20220819013025.hl7
Performing Org Name: null

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by brick-green** [comment]
Looks like the same file was sent twice. I think it was resent after CO had some transport failures
