### ISSUE TITLE
Feature: need secure way to view data in blobstore

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#6506]
# Discuss options

## Basic return via API

This approach is to read the blobstore and stream it back out an API endpoint.

| Pros | Cons|
|------|-----|
| Straight forward to impl    |  Tough to get security correct |
|   | Large files increase memory pressure on server |
|   | Our API does not do gzipped content, so slow for larger files |
|   | Client needs complexity of how to display large files. |

 - Could add support for a range header to return portions of blobstore files that allows for displaying portions of files on the client.
 - Could add support for a grep string and offset that would return data around the grep string.

## Integrate with SharePoint

| Pros | Cons|
|------|-----|
| Very secure |  More complex approach |
| Client "viewer" is Sharepoint's rich UI viewer | Keys needed "drop" files as service |
|   | User would need to be logged into okta and sharepoint at same time |

- Ideally, this approach would use both Okta's auth to check the email address is `@cdc` and use sharepoints credentials from the session to drop the file (write only) into a secure location, then be able to link/redirect to it.

**Comment by sarahnw** [comment]
@TomNUSDS should this be an epic?

**Comment by TomNUSDS** [comment]
@sarahnw Yeah, you're probably right. I was thinking it was a spike to figure out the approach.
