### ISSUE TITLE
Fetch Refactor: Cypress Tests

### ISSUE THREAD

**Issue by doug-s-nava** [CDCgov/prime-reportstream#6520]
## Problem statement

As a report stream developer / maintainer I want to be ensured that the new fetch system is working properly, and I'd like to do so by having the value sets editor run through end to end tests.

Create some Cypress tests for value sets.

This may not be worth doing until existing Cypress tests are fixed and running in CI?

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] Common value sets workflows are covered by passing Cypress tests

## To do

- [ ] ...

**Comment by bgantick** [comment]
Might need a separate ticket for figuring out Auth
