### ISSUE TITLE
Fetch Refactor: Loading State on Value Sets

### ISSUE THREAD

**Issue by doug-s-nava** [CDCgov/prime-reportstream#6521]
## Problem statement

As a report stream user / admin I would like to see loading state reflected in the value sets UI. As a report stream developer I would like to make sure that the useQuery loading state management is well demonstrated in the application MVP.

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] all value sets related API calls result in a loading state reflected in the UI, via usage of useQuery loading state

## To do

- [ ] ...

**Comment by bgantick** [comment]
Closing in favor of incorporating this work in #4790
