### ISSUE TITLE
Fetch Refactor: Replace NewApi: UseSenderResource

### ISSUE THREAD

**Issue by doug-s-nava** [CDCgov/prime-reportstream#6524]
## Problem statement

As a report stream developer I want to replace all instances of usage of NewApi and useRequestConfig with react query based hooks.

This ticket accomplishes replacement for files downstream of UseSenderResource:
* SenderModeBanner
* FileHandler

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] usage of NewApi and useRequestConfig on all mentioned files is replaced with new react query based functionality

## To do

- [ ] ...

**Comment by kevinhaube** [comment]
This fetch refactor work is entangled with STLT features despite being "SenderResource" -- the idea of a "sender" before is now referred to generically for senders/receivers as a "service", so this refactor work affects the services call that's blocking changes necessary for pagination on Daily Data (#4859)
