### ISSUE TITLE
Fetch Refactor: Replace NewApi: WatersApi

### ISSUE THREAD

**Issue by doug-s-nava** [CDCgov/prime-reportstream#6526]
## Problem statement

As a report stream developer I want to replace all instances of usage of NewApi and useRequestConfig with react query based hooks.

This ticket accomplishes replacement for files downstream of WatersApi:
* FileHandler
    * Validate
    * UploadToPipeline

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] usage of NewApi and useRequestConfig on all mentioned files is replaced with new react query based functionality

## To do

- [ ] ...

**Comment by kevinhaube** [comment]
Set to deploy on Tuesday, 10/18
