### ISSUE TITLE
Fetch Refactor: Replace rest-hooks: Independent Resources

### ISSUE THREAD

**Issue by doug-s-nava** [CDCgov/prime-reportstream#6528]
## Problem statement

As a report stream developer I want to replace all instances of usage of rest-hooks with react query based hooks.

This ticket accomplishes replacement for files downstream of all Resources that do not have any dependencies on other resources:
* AdmConnStatusResource 
    * AdminReceiverDashboard 
* AdmSendFailuresResource 
    * AdminLastMileFailuresTable 
* FacilityResource 
    * FacilitiesTable 
* OrgReceiverSettingsResource 
    * EditReceiverSettings 
    * NewSetting 
    * OrgReceiverTable 
* OrgSettingsResource 
    * OrgsTable 
    * AdminOrgEdit 
* ReportResource 
    * ReportLink 
    * TableResportsData 
* SubmissionsResource 
    * SubmissionTable 

Also remove unused resources
* CardResource
* SenderOrganizationResource
* SenderAuthResource

This is a lot, and can be split into multiple PRs

## Acceptance criteria

- [ ] usage of rest-hooks on all mentioned downstream files is replaced with new react query based functionality
- [ ] all resource files mentioned are deleted

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
Note for Chris in non-technical way:
There are currently two libraries (Rest Hooks vs React Query) used to call resources (the information through the API. This ticket is to replace the old resource calls with the new ones so that we can move completely to the new library (React Query).

**Comment by jpandersen87** [comment]
Abandoning this in favor of the new tickets that were created. Will try to implement them within the bounds of the existing endpoint infrastructure.
