### ISSUE TITLE
Fetch Refactor: Replace rest-hooks: ActionResource

### ISSUE THREAD

**Issue by doug-s-nava** [CDCgov/prime-reportstream#6529]
## Problem statement

As a report stream developer I want to replace all instances of usage of rest-hooks with react query based hooks.

Dependent on https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6528

This ticket accomplishes replacement for files downstream of ActionResource:
* Reports

## What you need to know

- ActionResource shape and script types may be available by plugin TSGenerate tracked by issue #7787

## Acceptance criteria

- [ ] usage of rest-hooks on all mentioned downstream files is replaced with new react query based functionality
- [ ] all resource files mentioned are deleted
- [ ] create automating testing associated with this feature

**Comment by chris-kuryak** [comment]
Closing because we have replaced all of the remaining Fetch Refactor tickets with updated "Create/Replace Hooks" tickets divided by API area.
