### ISSUE TITLE
Fetch Refactor: Replace rest-hooks: Auth and Test Resources

### ISSUE THREAD

**Issue by doug-s-nava** [CDCgov/prime-reportstream#6530]
## Problem statement

As a report stream developer I want to replace all instances of usage of rest-hooks with react query based hooks.

Dependent on all other rest hooks resources having been already replaced

This ticket accomplishes removal of AuthResource and TestResponse

## What you need to know

- ActionResource shape and script types may be available by plugin TSGenerate tracked by issue #7787

## Acceptance criteria

- [ ] usage of rest-hooks on all mentioned downstream files is replaced with new react query based functionality
- [ ] all resource files mentioned are deleted
- [ ] create automating testing associated with this feature

**Comment by chris-kuryak** [comment]
Closing because we have replaced all of the remaining Fetch Refactor tickets with updated "Create/Replace Hooks" tickets divided by API area.
