### ISSUE TITLE
Fetch Refactor: Replace rest-hooks: Test Dependencies

### ISSUE THREAD

**Issue by doug-s-nava** [CDCgov/prime-reportstream#6531]
## Problem statement

As a report stream developer I want to replace all instances of usage of rest-hooks with react query based hooks.

Dependent on https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6528

This ticket accomplishes replacement for files with on which TestResponse is dependent:
* OrganizationResource
    * AdminOrgNew
* OrgSenderSettingsResource
    * EditSenderSettings
    * NewSetting
    * OrgSenderTable
* ActionDetailsResource
    * FileHandler (useFilehandler)
    * SubmissionDetails

## What you need to know
- ...

## Acceptance criteria

- [ ] usage of rest-hooks on all mentioned downstream files is replaced with new react query based functionality
- [ ] all resource files mentioned are deleted

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
Closing because we have replaced all of the remaining Fetch Refactor tickets with updated "Create/Replace Hooks" tickets divided by API area.
