### ISSUE TITLE
Fetch Refactor: Replace rest-hooks: OrgSettingsBaseResource

### ISSUE THREAD

**Issue by doug-s-nava** [CDCgov/prime-reportstream#6532]
## Problem statement

As a report stream developer I want to replace all instances of usage of rest-hooks with react query based hooks.

Dependent on https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6528 and https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6531

This ticket accomplishes replacement for files downsteam of OrgSettingsBaseResource:
* OrgSettingsBaseResource
    * DisplayMeta

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] usage of rest-hooks on all mentioned downstream files is replaced with new react query based functionality
- [ ] all resource files mentioned are deleted

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
@jpandersen87 @stephenkao Is this issue still valid as written? 
It seems a little old and sparse, so checking to see if it is ready for team refinement this week.

**Comment by chris-kuryak** [comment]
Closing because we have replaced all of the remaining Fetch Refactor tickets with updated "Create/Replace Hooks" tickets divided by API area.
