### ISSUE TITLE
PII Leakage to HHS Protect

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#6534]
HHS Protect has informed us to that both Abbott and BD Veritor are putting the patient's first and last name into the `sending_facility_namespace_id` field, so they are receiving PII. I don't see that field mapped for HHS Protect, so we will need to see what field they are referring to, and then mask that field. Looking at a file for HHS Protect I do see there are names that appear in the ordering provider first and last name field sometimes, so perhaps that's the field?

We need to reach out to Kim Del Guerico and get more details.

This is high priority.

**Comment by sarahnw** [comment]
This is an old issue and we no longer have access to the data. Have advised HHS protect to delete it.

**Comment by BerniXiongA6** [comment]
Sarah took care of this via email on 8/30/2022: 

> Hi Sarah,
> 
>  
> 
> Got it. Thank you for the clarification.
> 
>  
> 
> Best,
> 
> Tim
> 
>  
> 
> Timothy Tsung | Data Scientist
> 
> Laboratory Data Section | CDC
> 
> Deloitte Consulting
> 
> From: White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>
> Sent: Tuesday, August 30, 2022 2:14 PM
> To: Tsung, Timothy (CDC/DDID/NCEZID/OD) (CTR) <trx4@cdc.gov>; Reeves, Maurice (CDC/OD/OCS) <qva8@cdc.gov>; Del Guercio, Kim Lu (CDC/DDID/NCEZID/DHQP) (CTR) <uwx1@cdc.gov>
> Cc: Xiong, Bernadette (CDC/DDPHSS/OD/HITSSU) (CTR) <rwe7@cdc.gov>; Hawes, Richard (CDC/OD/OCS) <qom6@cdc.gov>; Kpamegan, Norris (CDC/DDID/NCEZID/OD) (CTR) <svi5@cdc.gov>
> Subject: Re: PII in ReportStream data
> 
>  
> 
> Hi Timothy,
> 
>  
> 
> ReportStream is just a pass through. We don't keep data beyond 60 days so we are unable to resend corrected data. You all will need to remove it on the HHS Protect side. If you have more recent examples where this is still occurring, please let us know.
> 
>  
> 
> Sarah
> 
>  
> 
> Sarah White (Nava PBC)
> 
> Senior Product Manager
> 
> Pandemic-Ready Interoperability Modernization Effort (PRIME)
> 
> Centers for Disease Control and Prevention
