### ISSUE TITLE
NY - validate HL7 over REST

### ISSUE THREAD

**Issue by greene858** [CDCgov/prime-reportstream#6545]
## Problem statement

Need to test sending HL7 messages using REST transport to NY. Confirming that the connection works reliably and HL7 messages meet NY needs. 

## What you need to know

REST code, settings, secrets: NY-PHD--ELR and NY-PHD--ELR--JSK deployed to staging 08/25. Test message successfully sent with fake data, NY confirmed

## Acceptance criteria

Multiple messages sent, NY confirm messages are valid. 

## To do

- [ ] ...

**Comment by brick-green** [comment]
Sent 5 messages over to NY via staging

**Comment by brick-green** [comment]
What value do you want in MSH-5? ECLRS
What value do you want in MSH-6? NYSDOH
Do you require us to put our own identifier and CLIA in MSH-4? The CLIA should be ‘10DRPTSTRM’ unless you have your own.
Would you like to receive the AoE questions? Not required
Do we need to suppress the QST flag in OBX-29? Not required
Are there any other fields that are required? For example, the ordering provider information is sometimes missing, and some states won’t accept messages without it. We will process records if values are not populated.
Do you require a specific value in MSH-21-1 (Message profile ID)? No

**Comment by brick-green** [comment]
NY confirmed that messages passed validation!
