### ISSUE TITLE
Admin - IA, Design

### ISSUE THREAD

**Issue by a-chappelear** [CDCgov/prime-reportstream#6555]
## Problem statement
Follow on to [Admin - IA, Discovery](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6160)

## Acceptance criteria

- [x] Based on previous discovery work, wireframe or map out recommended IA adjustments to RS Admin section.
- [ ] Define and share a teamwide recommendation on how/when to add new pages or sections (or a workflow for having them approved.)
- [ ] Review design recommendations with internal team

## To do

- [ ] ...

**Comment by HeatherRienks** [comment]
*Please note that refinement details are dependent on outcome of ticket #6160.

**Comment by HeatherRienks** [comment]
@a-chappelear - this would be great to pair with @fmccaf1 on!

**Comment by fmccaf1** [comment]
I created [this mural](https://app.mural.co/invitation/mural/primedatainput6410/1664549522278?sender=ua604735c5cf1162b042a4310&key=bb142218-add5-4db8-abd0-8102e9d03568) to add a little structure to discovery. Will start scheduling calls with team members to get their input.

**Comment by a-chappelear** [comment]
An implementation ticket can be made with the above Mural on navigation items above. @HeatherRienks @doug-s-nava

**Comment by HeatherRienks** [comment]
@kevinhaube - please create an Imp ticket for the work noted above (per our discussion, prob 1 pt of work!) :)
cc: @fmccaf1
