### ISSUE TITLE
Automatically run a SmokeTest after a deploy and alert on failure

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#656]
Automatically run a smoke test like ./prime test run after every deploy to staging and production. The implementer of this PR should with @jimduff-usds to identify the best smoke test to run.

- [ ] Smoke test triggered by GitHub action
   * This will use Docker containers and spin up an environment for the test
- [ ] Smoke test run under the GitHub security principal
   * This will run with the release GitHub Action in the environment that is being deployed. This will run against the `candidate` function app slow. If the smoke test fails, the `candidate` slot should not be swapped to `production`.

**Comment by MauriceReeves-usds** [comment]
Should this include a call to check all SFTP connections as well?

**Comment by ronaldheft-usds** [comment]
Added details.
