### ISSUE TITLE
MO - Production Error Message

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#6570]
Muehlhausen, Jake <Jake.Muehlhausen@oa.mo.gov> received at 8/29 12:58pm

We received a production message this weekend missing the following information:

Filename:  covid-19-15fc86b2-725b-45cd-8225-d1038940d14f-20220827172058

MSH-10:  '9e60a9c2-1cd1-440f-8de3-c6e22335429a'

PATIENT_RESULT[0].PATIENT.PID.PatientIdentifierList[0].IdentifierTypeCode Description=Required field missing

PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.PlacerOrderNumber.EntityIdentifier Description=Required field missing

PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBR.PlacerOrderNumber.EntityIdentifier Description=Required field missing

**Comment by oslynn** [comment]
2022-08-29.  Looking into the following message.

MSH-10: 9e60a9c-1cd1-440f-8de3-c6e22335429a

PATIENT_RESULT[0].PATIENT.PID.PatientIdentifierList[0].IdentifierTypeCode Description=Required field missing (PID-3.5)

PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.PlacerOrderNumber.EntityIdentifier Description=Required field missing (ORC-2.1)

PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBR.PlacerOrderNumber.EntityIdentifier Description=Required field missing (OBR-2.1)

**Comment by oslynn** [comment]
2022-08-29: Email Prescryptive to resend the message.

Good afternoon John,

Would you please resend the following message and fill the specified fields:

MSH-10: '9e60a9c2-1cd1-440f-8de3-c6e22335429a'

PATIENT_RESULT[0].PATIENT.PID.PatientIdentifierList[0].IdentifierTypeCode Description=Required field missing (PID-3.5)

PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.PlacerOrderNumber.EntityIdentifier Description=Required field missing (ORC-2.1)

PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBR.PlacerOrderNumber.EntityIdentifier Description=Required field missing (OBR-2.1)

If you want me to map these fields to other field (i.e. map ORC-2.1 and OBR-2.1 to MSH-10), please let me know.



Best regards,
-Ott Sathngam
CDC SW ENG.

**Comment by oslynn** [comment]
Working with John @ prescryptive.  He still can't locate the file for resend.  Ask him, if he need me to send the file to him.  And, I am waiting for his response.

**Comment by oslynn** [comment]
2022-08-31, got email back from John (Prescryptive) and he found the message to be resent.  I asked him to make correction to the message according to MO requested and resent the message.

**Comment by oslynn** [comment]
2022-09-01: I am closing this ticket.  Since, John (Prescryptive) already resubmit this message.
