### ISSUE TITLE
WA - Close the loop on MSH 5, 6, 7 failures "Prescryptive"

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#6571]
## Problem statement

WA DOH wants to know when Prescryptive has sent correct data that previously had invalid MSH-5, 6, 7 errors so they can close the loop on this issue.

## What you need to know

- See [previous ticket # 6085](https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/6085) for RS engineering work that was completed on this issue. 

- WA DOH knows we've previously asked Prescryptive to send the data since the resubmissions timeframe has expired and we've also fixed the errors.

- Submitter for Prescryptive is John@prescryptive.com who was alerted of the request to send data through now that errors have been fixed. He's not yet replied to us.

## Acceptance criteria
Ticket can be closed when:
- [ ] Sender contact has confirmed they've sent the data successfully
- [ ] WA DOH has been alerted of the successful submission

## To do

- [ ] Follow up with John and cc: @oslynn to confirm 
- [ ] Follow up with WA DOH with status

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 note to self: ask Jenni WA DOH for help

**Comment by BerniXiongA6** [comment]
@oslynn working on this since he has made contact with John from Prescryptive.

**Comment by oslynn** [comment]
2022-08-31.  John can't find any of those messages going back to June.

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 sending confirmation to WA DOH that they can close this out
