### ISSUE TITLE
CA - MSH-4 confusion

### ISSUE THREAD

**Issue by sarahnw** [CDCgov/prime-reportstream#6577]
CA expected CSV uploaders to have CDPH000085 in MSH-4, they were initially being reported with CDPH000087, then during the portover we confirmed that the MSH would change from that 87 to 85 identifier.

Quick screenshot of data not being received in production due to the lacking of CDPH000085 in MSH-4.

Past 30 days – I have a feeling this goes back further – hope CDC can help trace to when these results were being transmitted with the changed CLIA so we can untangle as you said & ideally get them resubmitted with that CDPH000085 in MSH-4 so CDPH/CalREDIE can receive & process results in production.

![image.png](https://images.zenhubusercontent.com/61f1951e82ea0e048555632f/45a1227f-855f-4685-a46c-1b594c1763bf)

**Comment by sarahnw** [comment]
DATE

SUBMITTER_CLIA

SUBMITTER_NAME

SUBMITTER_TYPE

Total

8/27/2022

05D1013559

J RANDOLPH SCHNITMAN MD INC

SFTP DIRECT CONNECT

1

8/27/2022

05D2241990

MyCare Labs

SFTP DIRECT CONNECT

29

8/26/2022

05D1013559

J RANDOLPH SCHNITMAN MD INC

SFTP DIRECT CONNECT

3

8/26/2022

05D2062640

TRISTAN BICKMAN, MD

SFTP DIRECT CONNECT

28

8/25/2022

05D2241990

MyCare Labs

SFTP DIRECT CONNECT

75

8/25/2022

05D2062640

TRISTAN BICKMAN, MD

SFTP DIRECT CONNECT

89

8/24/2022

05D2062640

TRISTAN BICKMAN, MD

SFTP DIRECT CONNECT

64

8/24/2022

05D1013559

J RANDOLPH SCHNITMAN MD INC

SFTP DIRECT CONNECT

17

8/23/2022

05D2241990

MyCare Labs

SFTP DIRECT CONNECT

68

8/22/2022

DOD9324601

0028 Lemoore Laborat

SFTP DIRECT CONNECT

60

8/20/2022

05D1013559

J RANDOLPH SCHNITMAN MD INC

SFTP DIRECT CONNECT

2

8/20/2022

05D2241990

MyCare Labs

SFTP DIRECT CONNECT

31

8/20/2022

05D2062640

TRISTAN BICKMAN, MD

SFTP DIRECT CONNECT

4

8/19/2022

05D1013559

J RANDOLPH SCHNITMAN MD INC

SFTP DIRECT CONNECT

4

8/19/2022

05D2062640

TRISTAN BICKMAN, MD

SFTP DIRECT CONNECT

94

8/18/2022

05D2241990

MyCare Labs

SFTP DIRECT CONNECT

47

8/17/2022

05D1013559

J RANDOLPH SCHNITMAN MD INC

SFTP DIRECT CONNECT

25

8/17/2022

05D2062640

TRISTAN BICKMAN, MD

SFTP DIRECT CONNECT

104

8/16/2022

05D2241990

MyCare Labs

SFTP DIRECT CONNECT

82

8/15/2022

DOD9324601

0028 Lemoore Laborat

SFTP DIRECT CONNECT

99

8/13/2022

05D2241990

MyCare Labs

SFTP DIRECT CONNECT

36

8/12/2022

05D2062640

TRISTAN BICKMAN, MD

SFTP DIRECT CONNECT

3

8/11/2022

05D2241990

MyCare Labs

SFTP DIRECT CONNECT

72

8/11/2022

05D1013559

J RANDOLPH SCHNITMAN MD INC

SFTP DIRECT CONNECT

1

8/11/2022

05D2062640

TRISTAN BICKMAN, MD

SFTP DIRECT CONNECT

10

8/10/2022

05D1013559

J RANDOLPH SCHNITMAN MD INC

SFTP DIRECT CONNECT

4

8/10/2022

05D2062640

TRISTAN BICKMAN, MD

SFTP DIRECT CONNECT

3

8/9/2022

05D2241990

MyCare Labs

SFTP DIRECT CONNECT

87

8/9/2022

05D2062640

TRISTAN BICKMAN, MD

SFTP DIRECT CONNECT

26

8/9/2022

05D1013559

J RANDOLPH SCHNITMAN MD INC

SFTP DIRECT CONNECT

18

8/6/2022

05D1013559

J RANDOLPH SCHNITMAN MD INC

SFTP DIRECT CONNECT

9

8/6/2022

05D2062640

TRISTAN BICKMAN, MD

SFTP DIRECT CONNECT

5

8/5/2022

05D2241990

MyCare Labs

SFTP DIRECT CONNECT

24

8/4/2022

05D2062640

TRISTAN BICKMAN, MD

SFTP DIRECT CONNECT

4

8/4/2022

05D1013559

J RANDOLPH SCHNITMAN MD INC

SFTP DIRECT CONNECT

2

8/3/2022

05D1013559

J RANDOLPH SCHNITMAN MD INC

SFTP DIRECT CONNECT

1

8/3/2022

05D2241990

MyCare Labs

SFTP DIRECT CONNECT

25

8/3/2022

05D2205714

KWOKMAN DIAGNOSTICS

SFTP DIRECT CONNECT

12

8/3/2022

05D2062640

TRISTAN BICKMAN, MD

SFTP DIRECT CONNECT

5

8/2/2022

05D2062640

TRISTAN BICKMAN, MD

SFTP DIRECT CONNECT

13

8/2/2022

05D2241990

MyCare Labs

SFTP DIRECT CONNECT

41

8/2/2022

05D2205714

KWOKMAN DIAGNOSTICS

SFTP DIRECT CONNECT

59

8/2/2022

05D1013559

J RANDOLPH SCHNITMAN MD INC

SFTP DIRECT CONNECT

12

8/1/2022

05D2241990

MyCare Labs

SFTP DIRECT CONNECT

25

**Comment by brick-green** [comment]
Every sender has a sender_id value set. The sender_id for Simple Report is "simple_report.default". We have a rule in the receiver settings for CA that looks for any message with sender_id = "simple_report.default" then sets the CLIA to CDPH000085. Initially I thought all CSV uploader data was going to come through the same sender for simple report. That did not happen. Instead a new sender was made specifically for CSV uploader data. That new sender has a sender_id = "simple_report". So the rule was not catching those messages. To fix, I added a new rule looking for sender_id = "simple_report" then setting CLIA to CDPH000085. This is currently in production and should be working going forward.

**Comment by sliu1000** [comment]
Vanessa Burkhart is still have the same issue.

**Comment by brick-green** [comment]
I just checked our outgoing files and this issue has been resolved. I see in the email from Vanessa the report only goes to 8/30. That's the day I fixed the problem.

**Comment by brick-green** [comment]
So I think now we need to look at resends. 

@sliu1000 Can you ask Vanessa is she sees and examples newer than 8/30. Then if not, can she provide a list of MessageIDs for the errors? Then we will get them resent.

cc @BerniXiongA6

**Comment by sliu1000** [comment]
Thank you for checking. I'll send Vanessa and email shortly.

**Comment by brick-green** [comment]
CA sent a file with message IDs for the messages they need resubmitted. It's more than 3000...the problem was our oversight so I feel bad going to simple report on this. But 3000 is a lot with our current workflow.
[Uploading... toberesent-withCDPH000085inMSH.csv]

**Comment by sliu1000** [comment]
@brick-green I can relay this to SimpleReport Team.  Do you have a document of the messageid that need to be sent? I can forward to simplereport.

**Comment by BerniXiongA6** [comment]
@brick-green to create an epic to split up the resubmissions work 9/13/2022 sprint planning update

**Comment by brick-green** [comment]
Closing as issue has been fixed. Other tickets for resubmissions
