### ISSUE TITLE
PW - Expiration in 6 days from 8/30/22

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6585]
## Problem statement

Several accounts on MUSER will have passwords to expire in 6 days.  Please change password prior to deadline for the following accounts:

achdUSDSewsprod
bchdUSDSewsprod
pphlUSDSewsprod
cchdUSDSewsprod
mcophUSDSewsprod

## What you need to know

[(https://edcpwdmgr.pa.gov/)]

## Acceptance criteria

- The pw to be updated for the five listed accounts prior to expiration deadline.

**Comment by brick-green** [comment]
@MauriceReeves-usds You completed this, right?

**Comment by brick-green** [comment]
passwords were reset by @MauriceReeves-usds
