### ISSUE TITLE
Inventory current/new endpoints that provide STLT related data

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#6587]
## Problem statement

We need to inventory current/new endpoints that service "Daily Data" and other STLT related pages for the purposes of finding out what data is available from what endpoints and what will need to be added as it relates to the service map (#6503).

## Acceptance criteria

- [x] A document outlining the availability of each required feature for STLT work
- [x] Tickets addressing gaps in available functionality, properly labeled (Experience, Needs Refinement, API)

## To do

- [x] Gather list of all requirements in STLT future work
- [x] Check OpenAPI docs for info 
- [x] PIVOT! Peruse the code for this info instead
- [x] Compile list of necessary tickets to create
- [x] Compile list of functionality already existing related to STLT work
- [x] Create tickets for refinement

**Comment by kevinhaube** [comment]
Notes from the process: https://cdc.sharepoint.com/:w:/t/USDSatCDC/EXXo_HDcvhNBre9FnV_37pkBjNFwK7ZryxjpTROmxllQrg?e=tSVh6A

**Comment by kevinhaube** [comment]
Scheduled for discussion in Eng Sync, October 6th!
