### ISSUE TITLE
Add Smartsheet service request form to /support section

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#6588]
## Problem statement

As a sender or receiver, I'd like an easy way to request support. Currently I have to send an email and wait for a response. It's hard to know if my request was received and sometimes takes a minute to get a response back.

If I could submit a form on the RS website, get confirmation of my submission, and get a faster response back or resolution, I'd spend less time managing these requests in my email.

## What you need to know

- Currently most users email reportstream@cdc.gov for help. The message goes to our general inbox and has to be triaged manually.
- We built a test form in Smartsheet to help streamline the process.
- We have piloted the form with select STLTS over the last couple months.
- We have a small amount of data, but it suggests it's going ok. The system is working well enough we'd like to move all users over to it. 

## Acceptance criteria

**Embed the form**
- [x] Create new page for service request form, `/support/service-request`
- [x] Embed form ``` <iframe>embed code here</iframe>```
  - [x] Also link to form separately in case of loading problems or accessibility issues with iframes
  - [x] Ensure all form features and validation work
  - [ ] ~~Ensure inputs and font sizes aren't super small (they currently kind of are?)~~ not able to do anything with this
- [x] Content explains what the link is and where it's directing you
- [ ] Connect with O&O and make plan to message current users about the change

~~**Failsafe if the embed doesn't work! Link to the form**~~
- Link to service request form [insert link here] on `/support/contact`
- Content explains what the link is and where it's directing you
- Message current users about the change

## To do

- [x] Connect with Sharon about options for CSS changes
- [x] Hack away at CSS to see what we can change on our end
- [x] Figure out if we can get at least 1 Smartsheet account for further exploration into our options
- [x] Get embed code for live form from Sharon

**Comment by victorialb-usds** [comment]
Notes from 9/7 O and O and experience sync. 
Content: 
- change the field names to be more inclusive and more plain language
- add N/A option for senders for resubmissions drop down as this is not relevant for them 
- looking at the email to see if it can be tailored ... 

Workflows: 
- Sharon is going to look into if can send a notification can be sent to specific people with a ticket number 

Re smartsheet admin access: 
- cant get more admin access on smart sheets until October 1
- looking into sharing passwords and sync up Drew and Sharon on this

**Comment by drew-usds** [comment]
@a-chappelear @HeatherRienks just opened a PR for this here: https://github.com/CDCgov/prime-reportstream/pull/6701

**Things for y'all to QA when it hits staging:**

`/support`
- [ ] The new "Service request form" card shows up on the index
- [ ] Subhead makes sense/has no typos

`/support/contact`
- [ ] Review the updated language and link to the form under the "Have a problem with a data you're trying to send or receive?" header
- [ ] Updated content makes sense/has no typos

`/support/service-request`
- [ ] Does the form load in the iframe?
- [ ] Can you tab navigate through the form?
- [ ] The header/subhead/info alert makes sense/has no typos
- [ ] Confirm the info alert is the best way to offer an alternate way of getting in touch. Want to not dead end anyone in case there is a problem with the form on Smartsheet's end.

`/support` & `/support/contact` & `/support/service-request`
- [ ] No errors are thrown on [ANDI](https://www.ssa.gov/accessibility/andi/help/install.html) (or other accessibility tool of choice)

**Comment by HeatherRienks** [comment]
@a-chappelear - let's plan to review on 9/15 once it hits staging (since deployment did not happen on 9/13 due to merge conflicts).
cc: @drew-usds

**Comment by a-chappelear** [comment]
This has been updated to only use a direct link vs the iframe. I also rearranged the cards slightly on the landing page (so the FAQs are the first per feedback received from O&O) I committed the changes to the same branch.


@drew-usds @RakshindaAslam @bgantick 


![Screen Shot 2022-09-16 at 12.04.45 PM.png](https://images.zenhubusercontent.com/5d08f49d32d94d3393126018/26ae1a20-06bd-418d-a6c3-d1ef135eb67e)
![Screen Shot 2022-09-16 at 12.04.37 PM.png](https://images.zenhubusercontent.com/5d08f49d32d94d3393126018/6337158e-17a1-42b8-9fdf-d28fcc137d6c)

**Comment by HeatherRienks** [comment]
Follow Up from today's earlier meeting re: sharing SmartSheet link with our customers...
**Next Steps:**
**By EOD Wednesday, 9/28** 
@BerniXiongA6 and @sliu1000 to finalize:
-Auto-reply message for RS shared inbox
-Email to all current users, explaining new process of submitting "Service Requests/Support Tickets" via SmartSheet link
-Email to MonkeyPox lab contacts (Mayo, Aegis, etc.) informing them of new and improved Support process (so they don't need to email 
Stephen Smythe with their requests)
 
@BerniXiongA6  to send out email to all users the morning of **Thursday, 9/29**
(Here is the link to the draft we created: (https://cdc.sharepoint.com/:w:/t/USDSatCDC/EdQtH9bbdohPp4xvOADZ_eAB5MGif69Wih3YLgyWqUITMg?e=up0XsN)

**Comment by HeatherRienks** [comment]
Email was sent by Berni/Sharon to all RS users today and auto-reply message was enabled.

Content here: [https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B87E306C7-C610-4EDC-9DB3-E87D17D9A99E%7D&file=Templates%20for%20Informing%20ReportStream%20Users%20about%20Smartsheet%20Form.docx&action=default&mobileredirect=true](url)
