### ISSUE TITLE
Check in with Innolitics no later than Oct. 11, 2022 - validate initial file and send feedback to sender

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#6589]

**Comment by GilmoreA6** [comment]
Sent email and requested changes to innolitics

**Comment by GilmoreA6** [comment]
Thank for the clarification John,

In that case there are only a few updates I see that are needed. I've attached a copy of the file with the changes I've listed below.

Column Name	Value Received	Correct Value	Comment
symptomatic_for_disease	U (Unknown)	U	This is confusing in the Programmer's guide, we just need the code "U","N","Y"
patient_id	N/A	null	This is an optional column for OTC data. If you do not capture data relevant for this field please send blank. We do require the column to be present even if it is not populated with data
testing_lab_specimen_received_date	N/A	null	This is an optional column for OTC data. If you do not capture data relevant for this field please send blank. We do require the column to be present even if it is not populated with data
equipment_model_name	Alinty m	BinaxNOW COVID-19 Ag Card Home Test	For LOINC code 94558-4 "Alinity m" is not a correct value in the LIVD table (https://www.cdc.gov/csels/dls/sars-cov-2-livd-codes.html). Please use a value that aligns with 94558-4 (this will be different once your product is added to the table but for now to prevent errors let's use the value I've listed under "correct value".
testing_lab_clia	15D2243459
00Z0000014	For at-home testing there are two accepted CLIA values for this field "00Z0000014" is for OTC tests and 00Z0000015 is for prescription tests. 

Also, do you have a preference for either token-based authentication or a shared secret key for connecting to the API? Both methods are described in the Programmer's Guide (https://reportstream.cdc.gov/resources/programmers-guide) with examples. Please go ahead and send a new sample file when you have made the listed changes and let me know if you have any questions.

Thanks,

James Gilmore


James Gilmore (Agile Six)
Senior HL7 Data Analyst
Pandemic-Ready Interoperability Modernization Effort (PRIME)

**Comment by GilmoreA6** [comment]
Feedback sent to sender on 8/30. Checked in on 9/12 to see if updates had been made.

**Comment by GilmoreA6** [comment]
9/16 - asked for update
"Hi Qais and Desiree,

I wanted to check in and see if you have been able to retrieve the keys and example curl command from the Keybase message I sent. Please let me know if you have any questions/

Thanks,

James"

**Comment by GilmoreA6** [comment]
9/27 - Sent additional email requesting update or if there were any questions.

**Comment by BerniXiongA6** [comment]
@sarahnw @BerniXiongA6 let's follow up with them

**Comment by GilmoreA6** [comment]
Innolitics sent new file for validation. I reviewed the file and sent feedback along with instructions for the next step to Sam'an Herman-Griffiths (shermangriffiths@innolitics.com)

"Hi Sam'an,

Not a problem. This file is almost entirely correct. The only change we would like if possible is to the responses in the columns for symptomatic_for_disease. It looks like you are sending "TRUE" or "FALSE". Could you instead use the values "Y", "N" or "UNK". Also, the next step will be sending a test file to our staging database. For this we generally share the secret key via Keybase encrypted message (https://keybase.io/). If possible, could you create a Keybase account and let me know your username so that I can send the secret keys and example curl commands for the next step?

Thanks,

James"
