### ISSUE TITLE
SafeHealth - Validate sender data

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#6590]
## Problem statement

SafeHealth is working to improve their data quality. Prior to moving the changes to production they need to be validated in staging. 

## Acceptance criteria

- [ ] Messages included required fields that were previously missing including performingFailityName, orderingFailityName, orderingFacilityStreet, and reportingFaility
- [ ] Test type fields align with LIVD table: TestOrdered, TestName, DeviceName, and DeviceIdentifier

**Comment by brick-green** [comment]
Validated some messages in staging from SafeHealth. performingFailityName, orderingFailityName, and reportingFaility are looking good. Still waiting on orderingFacilityStreet and test type fields.

**Comment by brick-green** [comment]
responded to their email. There are a few issues with the messages above. OrderingFacilityZip and PerformingFacilityZip are incorrect. TestResult is null for result 2 and correctedID is blank when it should equal the value in SpecimenID.

**Comment by shy2cdc** [comment]
Email from Santosh:

Hi Brick,

Here are the reprocessed messages with Zip fix, submitted to Staging. 
Please review.

PatientZip and OrderingProviderZip are already in there.

Thanks
Santosh

**Comment by sliu1000** [comment]
Update from Ravi from Safehealth:

Hey Brick,

A few days ago, we worked with your team to test the quality of the data sent from Safeheath's QA environment to CDC staging environment.  

I just wanted to inform you that we have deployed that fix to our production, so going forward all the data submitted will adhere to the requirements. 

We have a few questions related to resubmission of the historical data. 

Please let us know when you have some time to connect for 30 minutes or so to discuss. 

Thanks and regards

**Comment by sliu1000** [comment]
Meeting Scheduled for 9/30 at 2:30 pm:

Hi Ravi,

Per your request, this time is to answer a few questions related to resubmission of the historical data.  
Could possibly send us your questions ahead of time, this will help us to make sure the appropriate team members are on the call.

Best regards,

Sharon
-------------------------------------------------
Hi Ravi,

 

Sounds good. Here are some open slots:

9/28 10:00AM – 11:00AM ET
9/28 3:00PM – 4:00PM ET
9/30 10:00AM – 11:00AM ET

9/30 2:30PM – 3:30PM ET

What works for you?

Thanks,

Brick Green (Agile Six)
Integration Engineer
