### ISSUE TITLE
American Samoa - Create organization and receivers

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#6592]
## Problem statement

American Samoa will be a new jurisdiction connecting with report stream. They will need an organization and receivers added to the settings. There should be a receiver for testing and production.

## Acceptance criteria

- [ ] Organization created with jurisdictional filter
- [ ] Receiver for test environment created
- [ ] Receiver for production env created

## To do

- [ ] Add organization and receivers to local org file
- [ ] create yml files in settings/prod and settings/staging
- [ ] add settings to staging
- [ ] add settings to production

**Comment by BerniXiongA6** [comment]
9/8/2022: email chain with American Samoa forwarded to @GilmoreA6 !
