### ISSUE TITLE
Make ./prime test run against APIs instead of DB connections

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#660]
**Is your feature request related to a problem? Please describe.**
For security purposes, we should limit network access to the DB. 

**Describe the solution you'd like**
An API that allows the ./prime test to gather the information it needs as part of a smoke test

**Describe alternatives you've considered**

**Additional context**
Part of the monitoring epic

**Comment by MauriceReeves-usds** [comment]
Replaced Chris with Ron as DevOps assignee

**Comment by MauriceReeves-usds** [comment]
@jorg3lopez , this might be a good thing to take a look at. Currently the `TestReportStream` class has a series of tests that directly call into the DB to check the results after running tests. It would be good to abstract those out into Azure functions that can be invoked instead.

This not only helps decouple the code, but it also will help us in the future as we want to use some of those calls in our web front-end.

If you look down towards the bottom you'll see four queries that get invoked via Jooq using the DSL. 

Acceptance criteria:
- The DB logic is moved into a series of Azure functions that are callable via the API
  - The API calls should be RESTful, eg `api/report-history/<REPORT ID>/sftp-file-name/<RECEIVING ORG NAME>`
- The DB calls in `TestReportStream` get replaced by API calls

We should discuss this further once you're ready to start working on it. Ping me when you're ready and we can discuss.

FYSA: @jlusds @jimduff-usds

**Comment by jorg3lopez** [comment]
@MauriceReeves-usds, ready to start.

**Comment by ronaldheft-usds** [comment]
Where does this ticket stand?
