### ISSUE TITLE
WA -January 2023 Updates on Race/Ethnicity values to SR&RS

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6606]
## Problem statement

The Race/Ethnicity values for WA State will need to be added to SimpleReport and ReportStream by January 2023.

## What you need to know

**1.  Please see ELR supplemental guidance related to the 2023 WAC changes related to ELR including downloadable spreadsheet of values/codes.**

https://doh.wa.gov/public-health-healthcare-providers/notifiable-conditions/rule-making/supplemental-guidance-elr-submitters

Please let me know if there are questions.

Julie Vanderkolk, MSPH                            

**2.  Email Communication with Sarah and WA State**

From: White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>
Sent: Monday, August 29, 2022 4:38 PM
Subject: Re: Race/Ethnicity option in SimpleReport for WA State

External Email

Thanks, Joyous! Please send us the spreadsheet as soon as it's ready!
 
Sarah White (Nava PBC)

From: Van Meter, Joyous J (DOH) <Joyous.VanMeter@doh.wa.gov>
Sent: Monday, August 29, 2022 4:59 PM
Subject: RE: Race/Ethnicity option in SimpleReport for WA State

Hi Sarah,

Thank you for reaching out.  Please find our answers below (in red). 

**Race changes:**
Do these have codes to go with them? And if so can you provide us with them? For example, in HL7, things like race look like "2028-9^Asian^HL70005", where the first value is the code, the second value is the display text, and the third value is the coding system.   As Julie mentioned in our call today, they will have a spreadsheet soon with the corresponding HL7 and CDC national standard codes as well as a few local WA codes. 

If we use a non-standard value, should we leave the ID value null?  I believe that this will be answered in the upcoming spreadsheet. 
For Alaska Native and American Indian in HL70005 these have the same code value. Are we ok to send the same code for both or do you have distinct codes for them you'd want us to use? They do need to be separate (and the same is true for Pacific Islander and Hawaiian Native).

Related for these two categories, do you have definitions for these you'd recommend we use to help people select? No, we do not have any definitions to use to help people select.  The idea is to have people self-identify as whatever race/ethnicity they consider themselves – so they should pick whatever they see themselves as (which could be one or the other or both if they previously would have selected Alaska Native and American Indian).
Language of preference

Do these have codes to go with them as well? What coding system and what codes for these values? The spreadsheet for race changes will also have any applicable codes for language of preference.

Does WA only want a single preferred language? Can respondents specify more than one preferred language? Yes, WA wants only a single preferred language and respondents should only specify one.

Do you want Dari and Farsi treated separately? Yes
Thank you so much!  Please let me know if you have any further questions.

--Joyous

From: White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>
Sent: Thursday, August 25, 2022 2:21 PM
Subject: Re: Race/Ethnicity option in SimpleReport for WA State

External Email

Hi Joyous,

Thanks again for this information - picking this thread back up! We have some questions for y'all. I'm including them below, but if they're easier to talk through we can use our call next week if that works?

Race changes:
Do these have codes to go with them? And if so can you provide us with them? For example, in HL7, things like race look like "2028-9^Asian^HL70005", where the first value is the code, the second value is the display text, and the third value is the coding system. 
If we use a non-standard value, should we leave the ID value null?
For Alaska Native and American Indian in HL70005 these have the same code value. Are we ok to send the same code for both or do you have distinct codes for them you'd want us to use? 
Related for these two categories, do you have definitions for these you'd recommend we use to help people select?
Language of preference
Do these have codes to go with them as well? What coding system and what codes for these values? 
Does WA only want a single preferred language? Can respondents specify more than one preferred language?
Do you want Dari and Farsi treated separately?
 

Sarah White (Nava PBC)

Senior Product Manager
Pandemic-Ready Interoperability Modernization Effort (PRIME)
Centers for Disease Control and Prevention

From: Van Meter, Joyous J (DOH) <Joyous.VanMeter@doh.wa.gov>
Sent: Wednesday, August 10, 2022 10:58 AM
Subject: RE: Race/Ethnicity option in SimpleReport for WA State

Hi Sarah,

Here is the link to the Notifiable Conditions rule including the updates that go into effect January 1, 2023: Chapter 246-101 WAC:.  It gives both the current requirements (noted as “Effective until January 1, 2023”) and the new requirements (noted as “Effective January 1, 2023”).  The main change that will affect Simple Report is the expansion of the categories for reporting patient race, ethnicity, and language of preference.  I have attached a list of these new categories that are required.

I’m not aware of any email distribution lists for future changes.  Most likely this will be the only big changes we need in the foreseeable future.  And we will continue to connect via email and the SimpleReport/ReportStream Bi-Monthly Check-In call.

Please let me know if you have any questions or need anything more!

Thank you,

Joyous

From: White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>
Sent: Wednesday, August 10, 2022 6:49 AM
Subject: Re: Race/Ethnicity option in SimpleReport for WA State

External Email

Hi Joyous,

Thank you for reaching out! Can you send us the requirements for the new reporting? I'm including my colleague, Jayna Wallace, from SimpleReport here as well so we're both ready to handle these changes. Anything you can send to us about these new requirements from WA would be gladly appreciated. 

For future changes, is there an email distro we should subscribe to? My apologies for missing this before, we've had turnover on our team over the year so some things may have gotten lost in the shuffle.

Sarah

Sarah White (Nava PBC)
Senior Product Manager

From: Van Meter, Joyous J (DOH) <Joyous.VanMeter@doh.wa.gov>
Sent: Monday, August 8, 2022 5:45 PM
Subject: Race/Ethnicity option in SimpleReport for WA State

Hello Sarah,

It was great to meet you last week on the WA DOH & CDC SimpleReport/ReportStream Bi-Monthly Check-In call.  I know that you had said that you would need to check in with some colleagues before sending an email to connect on the race/ethnicity values we will need to have added to SimpleReport by January 1, 2023.  Please let me know if there is anything you need from me, and I look forward to discussing this further.

Thank you,

Joyous

Surveillance Process Team | Surveillance Section
Public Health Outbreak Coordination, Informatics, and Surveillance
Washington State Department of Health
Joyous.VanMeter@doh.wa.gov
360-236-3431 | www.doh.wa.gov

## Acceptance criteria

- Create updated spreadsheet prior to January 2023 deadline. Read email communications and WA guideline link for more information.  
- Test updated spreadsheet make sure no errors

## To do

- Who will create the updated spreadsheet?

**Comment by sarahnw** [comment]
closing this - we already have an epic to capture the work see #6438
