### ISSUE TITLE
Clean up old images out of ACR

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#6609]
We need to create a script that runs on a daily basis cleaning up old containers. 

For now we should remove the containers older than 30 days from each environment's repository.

This can run as a cron based Github Action

**Comment by snesm** [comment]
Cleanup tool based on keeping the most recent N images: https://github.com/andrew-kelleher/azurecontainerregistry-cleanup

**Comment by snesm** [comment]
Example [powershell on ubuntu action](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-powershell)
