### ISSUE TITLE
Better API error reporting for key (auth) errors.

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#6611]
API calls do not give detailed errors when there is some issue with authentication (for security reasons).

Figure out some way to safely determine if it's safe to return detailed information. 

We can't base it on if they are an Admin or based on Settings because the user isn't logged in.

@mauricereeves @jimduff-usds @brick-green @clediggins-usds 

Reply to this issue with brainstorming ideas.

**Comment by brandonnava** [comment]
Hi @TomNUSDS any new ideas on how to do this? Should we revive the discussion?

**Comment by TomNUSDS** [comment]
This came up in a discussion and I captured it to be discussed again in the future (so thanks for doing that now!)

Maybe @jimduff-usds can help jog my memory, but I think there are different authentication sub-errors that can happen (e.g. when parsing the bearer token or verifying something or another in our code)... but the response is always generic "auth failed".

While it is more secure to not give details, this approach isn't helpful when trying to debugging why an authorization is failing. 

The thought was the http response error can include debug information in the body IF the caller is a Prime Admin. But the issue with that is how do we KNOW if someone is a Prime Admin if they aren't able to log in!

**_But: I'm not sure how common an issue this is._** 

One possible solution is to create a Verify Credentials API endpoint that takes TWO credentials. The first being a valid Prime Admin `bearer`. The second is the credentials to debug. The result of the API call would include details about why the 2nd credentials is failing.

**Comment by brandonnava** [comment]
@arnejduranovic @jimduff-usds @stephenkao Is this ticket still relevant or outdated given platforms/experiences efforts to improve error codes?
