### ISSUE TITLE
Iterate/improve ValueSets table UI

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#6613]
UX feedback:

- [ ] The many-to-one relationship of data needs to be reflected in UI.
- [ ] If there is some change history that's available surface it in the UI.

[Direct edit this ticket to clarify]

**Comment by TomNUSDS** [comment]
@jimduff-usds @bgantick @sethdarragile6

**Comment by bgantick** [comment]
For reference, we already have some work planned on this feature: https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3489. The current version is very much an MVP and isn't really in use yet (we had other priorities come up). cc @RakshindaAslam

**Comment by kevinhaube** [comment]
@fmccaf1 @drew-usds @CnoteNava For consideration in upcoming sprints, and requires mockups and UX decisions :)

**Comment by chris-kuryak** [comment]
This is old ticket and needs refinement. O+O will contact us about improvements like these in the future if they are high priority.
