### ISSUE TITLE
LGTM.com will be shut down in December 2022

### ISSUE THREAD

**Issue by snesm** [CDCgov/prime-reportstream#6614]
LGTM is approaching [End of Life](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/).  New commits will no longer be analyzed by the end of Nov 2022.
Also, [LGTM](https://lgtm.com/) is a nice scanning tool. [CodeQL](https://github.com/github/codeql) is what powers [LGTM](https://lgtm.com/). However, [LGTM](https://lgtm.com/) takes too long to check for new/fixed alerts. [CodeQL](https://github.com/github/codeql) works much more https://github.com/TheAlgorithms/website/pull/24, and [LGTM](https://lgtm.com/) seems to only use [CodeQL](https://github.com/github/codeql). You can also see [CodeQL](https://github.com/github/codeql) runs on commits, and [LGTM](https://lgtm.com/) doesn't.

CodeQL should be enabled to [replace](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository) LGTM.

https://codeql.github.com/docs/codeql-cli/getting-started-with-the-codeql-cli/

**Comment by jeremy-page** [comment]
Please note this supports JS/TS but not Kotlin (but does support Java so I think it can see lib issues). We should make sure & filter out changes to the .kt code if it's not scannable.

**Comment by snesm** [comment]
There may be [Kotlin public beta scan](https://github.com/github/roadmap/issues/207) functionality available.

**Comment by lucasdze** [comment]
Created PR https://github.com/CDCgov/prime-reportstream/pull/6781 to resolve this issue
