### ISSUE TITLE
CO - Would like to start receiving Flu results

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6621]
## Problem statement
Received via Smartsheet Reportstream Service Request Form.
Nancy Kecso from The State of CO Dept. would like to start receiving flu reports.  As of July 7 from the addition of the Multiplex device (a list of 4-5 devices that allow the reporting of flu and covid) in SimpleReport.  They would like to start receiving flu and covid 19 submitted results.

## What you need to know
-SimpleReport Multiplex add [https://www.simplereport.gov/using-simplereport/whats-new](url)

## Acceptance criteria

- For CO State Depart of Public Health start receiving both flu and covid 19 lab results.

**Comment by BerniXiongA6** [comment]
@MauriceReeves-usds @brick-green forgot to mention this during Team Leads sync today. What's the typical process for a request like this since Sarah is out and would normally handle it? I want to make sure it's on our radar and also wondering if what should next steps be?

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 send email to CO to inform of UP work with Pipelilne team -- then close out cc: @brandonnava

**Comment by BerniXiongA6** [comment]
Per Sprint Planning, we'll close this ticket since CO will roll under the UP work moving forward. cc: @brandonnava @brick-green @MauriceReeves-usds
