### ISSUE TITLE
Checkov: CKV2_AZURE_21: “Ensure Storage logging is enabled for Blob service for read requests”

### ISSUE THREAD

**Issue by lucasdze** [CDCgov/prime-reportstream#6623]
The Storage Blob service provides scalable, cost-efficient objective storage in the cloud. Storage Logging happens server-side and allows details for both successful and failed requests to be recorded in the storage account. These logs allow users to see the details of read, write, and delete operations against the blobs. Storage Logging log entries contain the following information about individual requests: Timing information such as start time, end-to-end latency, and server latency, authentication details , concurrency information and the sizes of the request and response messages.
Storage Analytics logs contain detailed information about successful and failed requests to a storage service. This information can be used to monitor individual requests and to diagnose issues with a storage service. Requests are logged on a best-effort basis.
We recommend that you ensure Storage Logging is enabled for Blob Service for Read Requests

Guide: https://docs.bridgecrew.io/docs/ensure-storage-logging-is-enabled-for-blob-service-for-read-requests

**Comment by snesm** [comment]
Previously added to `.github/workflows/validate_terraform.yml` `skip_check`.
