### ISSUE TITLE
Refactor Lastmile table to use RS Table component

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#6636]
![Screenshot 2023-06-06 at 1.51.57 PM.png](https://images.zenhubusercontent.com/6376907717d32d4f8caabb68/815f1c7d-b95d-4219-9657-efb859e10e57)See PR review discussion on #6594. @kevinhaube 

Refactor `AdminLastMileFailuresTable` to use `/components/Table` instead of `@trussworks/react-uswds/Table`

Thoughts:
 - Consider renaming our Table component to avoid confusion.
 - Consider our Table leveraging the trussworks table.
 - HTML5 is starting to deprecate table features. (This is around using table for layout versus displaying information).
 - The "Mobile First" approach is to use a grid instead a table even for data. Keep in mind as consider how much investment into our own table components.

**Comment by chris-kuryak** [comment]
Will carry over to next sprint. Aiming for PR up by Fri 6/16.
