### ISSUE TITLE
COVID Check Today - API Sender Onboarding

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#6637]
### Problem Statement

COVID Check Today was previously set up as a CSV user. They now would like to be set up as an API user.

### What You Need to Know
*From User*:
Ryan Nelson
Denver Area Manager
Covid Check Today

> Hi Sarah,
> 
> My apologies for the delayed response. I am working to have backlog numbers for you by next week for CA, CO, NV and FL.
> 
> I met with our developers and shared the Programmers Guide with them. They are telling me they need additional information as far as what system/platform they will need to integrate with, and what format you will need the data transfer sent in. When I was working with Ricky, we started down this path, in particular with the excel/csv file layout that you all needed us to send backlog and ongoing records in. Is it possible to revisit this? Also, is there someone on your staff I can connect our developers with for the technical side of things?

### To Do
- [ ] Set up individual tickets for this API Sender Onboarding epic

**Comment by BerniXiongA6** [comment]
I'll share this in standup with the engineers to see who could help me get this email answered.

**Comment by BerniXiongA6** [comment]
@rnz6 @sliu1000 looks like this needs to be converted to an "API sender onboarding" ticket. I can fix the ticket details and then I'll reach out to them to request a sender KICKOFF call (cc: @jbiskie @brick-green for visibility). Thanks!

**Comment by BerniXiongA6** [comment]
Updated 9/8/2022: BX email replied to Ryan Nelson / COVID CHeck Today:

> Hi Ryan!
> 
> Thanks so much for reaching out to ReportStream. 
> 
> I apologize in advance if I'm unaware whether you've yet had this conversation with Sarah before she left on vacation: have you both discussed scheduling a ReportStream Data Sender Kickoff meeting? That would be our first step of engagement. In that Kickoff meeting, we would schedule 30 minutes to go over ReportStream in greater depth as well as detailing the technical onboarding steps for data senders (we would have an engineer join the kickoff meeting to go over the key points in programmer's guide and answering any specific questions you have for getting started with ReportStream).
> 
> Does this sound like a good next step for COVID Check Today?
> 
> 
> Thanks,
> Berni
>

**Comment by BerniXiongA6** [comment]
@sliu1000 FYI, we've converted this ticket from a support ticket to an Epic for "API Onboarding" since that's what the user was asking assistance on.

**Comment by sliu1000** [comment]
Update from Sender:

Hi Joel,

Thank you so much for reaching out. I apologize for the delayed response. I have been a bit out of the office last week, this week and next week on paternity leave. I'm working a little bit here and there, and will try and get the task work caught up on this project as soon as possible. It will most likely be mid to end of next week. Thank you for your patience in working with me on all of this.

Ryan

**Comment by jbiskie** [comment]
Email to Ryan on 9/20, regarding the sample file he sent on 9/16. His sample file is in keybase.

> Overall, the sample looks good. I found a few edits that we'll need to have you make:
> 
> The equipment_model_name and test_performed_code should match up with columns B and F of the [LIVD table](https://www.cdc.gov/csels/dls/sars-cov-2-livd-codes.html). If the Accula SARS-CoV-2 Test is correct, then use 95409-9 as the code.
> For the patient_dob, use "09/09/1970" for the format
> On the AOE questions, please leave them blank if the information is not available, do not use "N/A"
> 
> When your developers are ready, please have them provide me their keybase.io account name, and I'll send over the API keys with some sample commands so you can start testing against our endpoint.

**Comment by BerniXiongA6** [comment]
Ryan is currently out on paternity leave -- @BerniXiongA6 will follow up on this to re-engage when he's back.

**Comment by brandonnava** [comment]
@BerniXiongA6 Do we know how much longer he's out on paternity?

**Comment by LaFreda1** [comment]
@GilmoreA6 what are we waiting on from COVID check today? I see that this is the last email that was sent to them:
ames Gilmore <notifications@github.com> Unsubscribe
Wed, May 17, 4:06 PM
to CDCgov/prime-reportstream, me, Comment

Hi Ryan,

I have sent you a keybase message with the x-functions-keys that you will use to send to our staging and production systems

Please find the example curl commands below. The "x-functions-key" values should be replaced with the secrets in the keybase message. You can find information on sending to us in the ReportStream Programmer's guide (https://reportstream.cdc.gov/assets/pdf/ReportStream-Programmers-Guide-v3.0.pdf). Please ensure to never send PII/PHI to our staging environment. Only mock data should be sent to this environment.

Your organization name is "covidchecktoday"

Example curl command staging:

curl -X POST -H “client:covidchecktoday” -H “content-type:text/csv” –data-binary “@./covidchecktoday-nonPII-data.csv” -H “x-functions-key:” https://staging.prime.cdc.gov/api/waters

Example curl command production:

curl -X POST -H “client:covidchecktoday” -H “content-type:text/csv” –data-binary “@./covidchecktoday-prod-data.csv” -H “x-functions-key:” https://prime.cdc.gov/api/waters

Thanks,

James
