### ISSUE TITLE
CO - API Sender Onboarding - Vault

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#6641]
9/6 @ 12:13pm
CO Onboardee Julie Smith - juliaagness@vaulthealth.com
DE Completed Onboardee - Shari Feldman - sharif@vaulthealth.com

After reading the below please let @shy2cdc (Katie) know if another TOS needs to be sent to Vaulth Health. 

We have 2 states that we report to that are requesting that we switch over to ReportStream, Colorado and Delaware. I believe we are already set up for Delaware, or we should be. My colleague Shari Feldman has already answered the 3 questions below to register Delaware for ReportStream (I will copy the responses below), but now we are concerned with registering in Colorado. 

**COLORADO:** 

-What is your expected daily message volume? Testing volume varies, but we currently report anywhere from 10-30 results per week

-What states are you currently reporting to? We report Covid Results to all 50 states.

-What is your current process for reporting COVID-19 data (I.e., CSV, HL7)? Colorado is HL7

**Here is the previous response from Shari Feldman for DELAWARE:** 

-What is your expected message volume? - We currently report anywhere between 5-30 daily results

-What states are you currently reporting to? We report Covid Results to all 50 states.

-What is your current process for reporting COVID-19 data (I.e., CSV, HL7)? - for all but five remaining states, we report via HL7, currently reporting Delaware via daily csv file.

**Comment by BerniXiongA6** [comment]
@jbiskie do you know the answer to this, whether Vault needs to complete another ToS agreement?

**Comment by sliu1000** [comment]
@shy2cdc Katie - you can let the customer no, they do not need to complete another TOS since they are still in the process of onboarding DE and now CO.

**Comment by shy2cdc** [comment]
Just sent the customer the below:

I just heard back from the engineers and you do not need to sign the ToS. Can you please provide some dates and times (in EST) for next week that you can meet with my team for a 30 minute kick off call? The soonest we could meet is Thursday 9/15 between 2:30pm and 3pm EST.

Alternatively, if your schedule is too busy to meet and prefer, we cover our kick-off material via email, we are happy to accommodate that as well.

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 will email sender with Kickoff via email content. Stay tuned! @shy2cdc @sliu1000

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 sent kickoff email to Julie at Vault today. @shy2cdc @sliu1000

**Comment by BerniXiongA6** [comment]
Updates 9/19/2022: Vault has responded to the kickoff email along with a sample message. This ticket is now available to work on.

**Comment by shy2cdc** [comment]
Email from Tara:

Hi James,

It looks like we are missing the endpoint we need to hit that is specific for Vault.  Would you be able to help me with that?  I’m being asked for something like - https://staging.prime.cdc.gov/api/token?scope=<redoxClientIdentifierHere>

Tara

**Comment by sliu1000** [comment]
Update from Sender:

Hi James,

It looks like we may need some help.  Are you seeing any messages hit your endpoint? 

 

We are trying to query a token request, our paramaters are:

 

grant_type=client_credentials&client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&client_assertion=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjU5MTY1YTRlLTcwMDctNDY3Yy04YzgwLTk0NjJmNDI4NzFmMyJ9.eyJpYXQiOjE2NjYzNjM1MzIsImV4cCI6MTY2NjM2MzUzNywiYXVkIjoiaHR0cHM6Ly9zdGFnaW5nLnByaW1lLmNkYy5nb3YvYXBpL3Rva2VuIiwiaXNzIjoidmF1bHRoZWFsdGgiLCJzdWIiOiJ2YXVsdGhlYWx0aCIsImp0aSI6ImE3YjFjYWY5LWQwMzUtNGEwYy04MzVlLTViMDViNDFmMzI1OCJ9.Cp0ZzxpP6g1BOkmOF_QfAXOax5kQQqavKsqvbVD1Wnf132d7jI2v0Ko3aYjeadjynSoQU6NAnOqGGJSvgh44xEjV-SGhxBroLjHjrfXIw6rjGtnIjWRlu0vSooGICaSYRd1MD50nBw2EbP65A2jSsSfsFTtLSCdhges0NNRfYeyw8Mg67aAJdDbE-U1RMFxLcmj7Nd9WcXAqI0GNSO6quDFuXig640CpNC_PJxiYusShMKV4hiOA1Tr3bwK4JejjaOOaGT8OIx0mi8irLtICDZMwYTRQnVNp5_yRm_lGXdRXd5fX5U6MHOzAFy8LZPKhS6zjgU0dniCTXV0qESK2cQ&scope=vaulthealth.default.report

 content-type is application/x-www-form-urlencoded

We are receiving a 401 error response.

Tara Brocke

**Comment by brandonnava** [comment]
Blocked due to LIVD table - LDTs no longer getting added bc FDA not giving out new EUAs

**Comment by brandonnava** [comment]
@GilmoreA6 After hearing from Megan about not needing EUAs moving forward, do we want to revive the conversation with onboarding Vault?

**Comment by sliu1000** [comment]
@brandonnava If I remember correctly, I think there's a LOINC code issue for devices not approved by EUA...

**Comment by GilmoreA6** [comment]
@brandonnava In order to move this forward we would need to establish how we would go about accepting results for devices not on the LIVD table. There is both a process and technical component here that we would need to solve for.

**Comment by brandonnava** [comment]
@GilmoreA6 Do we think it's worth it to take this one? Especially with the mandate ending soon. How often are we running into device makers not on the LIVD table?

**Comment by chris-kuryak** [comment]
Close per James Gilmore
