### ISSUE TITLE
Research & Discussion around consolidating components 

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#6652]
## Problem statement

Research and discussion around consolidating and cleaning up component structure with goal of making things easier to find.

NOTE: see #2230 for more notes on this.

## Acceptance criteria

- [ ] What components can be consolidated?
- [ ] Discuss in Experience Eng sync
- [ ] Create actionable items for next steps
- [ ] Add proposal doc

**Comment by kevinhaube** [comment]
@stephenkao This was written a while back, we have a broken approach to tables and should unify that on the front-end. However, adding "stale" to this as we should absolutely refresh its contents.

**Comment by HeatherRienks** [comment]
Per Eng tix review- our next proposed steps: @stephenkao to take on this ticket- What can be consolidated? Discuss in Eng Sync.

(Low priority)

**Comment by etanb** [comment]
Would love to make this a priority @stephenkao as well as talk about our general reliance / usage of USWDS + Trussworks components.

**Comment by etanb** [comment]
Would love to make this a priority @stephenkao as well as talk about our general reliance / usage of USWDS + Trussworks components.

**Comment by stephenkao** [comment]
@etanb Let's chat about this today!  I have some thoughts about long-term maintainability and what we can do in the meantime to consolidate everything :)

**Comment by stephenkao** [comment]
@etanb and I just chatted about this, and he'll be taking over this ticket!  🙌

Overall, we synced up on
