### ISSUE TITLE
Design - Track Progression of a single test result for Internal Admin 

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6657]
## Problem statement

As an internal admin, I would like to be able to search for a message ID and get the following information about that message:
- Incoming report id
- URL to blob store
-  Incoming file name
-  Sender Org and facility name
 -  Errors and/or warnings
 - Output report ID
 - Output file name, 
The purpose of this is to help the internal admin with troubleshooting support tickets and reducing manual time taken today to research these tickets.

## What you need to know
Mural with initiative break-down https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1660849046968/e257020850ab71f57b31120e27ec06203ae9c22b?sender=u3fea607b46e84058d3224917

[Figma file](https://www.figma.com/file/fKl2M96ylkxYezwjVVUSIX/Internal-Admin-%26-Tools?node-id=411%3A1068)

## Acceptance criteria

- [ ] Wireframe for the page(s)/feature
- [ ] Navigation flow for this feature
- [ ] Review the wireframe and IA with Product and Eng

## To do

- [ ] Sync with Brick for more information
- [ ] Question: This similar action is on every page but they're all different, can we consolidate these?
- [ ] Consider the next iteration for allowing users to input multiple message IDs.

**Comment by RakshindaAslam** [comment]
cc @a-chappelear @drew-usds

**Comment by drew-usds** [comment]
From 9/8 sync: We need to ask more questions on this. @a-chappelear needs to talk more with Brick to figure out what we need to do here.

Biggest question: We're searching/filtering in very similar ways on all the other admin pages ... do we really need to make this a separate page/feature? Is this something we can roll into existing search/filter things we've built out? This is also a chance to audit our current admin features and see what we can consolidate.

**Comment by a-chappelear** [comment]
[Figma file with updated partial results & adjustments](https://www.figma.com/file/fKl2M96ylkxYezwjVVUSIX/Internal-Admin-%26-Tools?node-id=411%3A1069) to table headers/results.

**Comment by ahay-agile6** [comment]
@a-chappelear here is the lucidchart of notes with brick
https://lucid.app/lucidchart/ea5c58a0-b884-4952-a3e9-165a816dc68f/edit?view_items=lKsVGvSZdI7c&invitationId=inv_d8ce9e1c-7368-4866-8ea7-b2a04516cda0#

**Comment by a-chappelear** [comment]
Minor updates are needed to the Figma file for this ticket (based on feedback above) this should stay open in the next sprint (by about 2 points for design). @HeatherRienks @RakshindaAslam

**Comment by HeatherRienks** [comment]
@a-chappelear - thanks!

**Comment by a-chappelear** [comment]
Figma has been updated with the most recent updates from syncs. Quality filters may come into play more in later tickets. If there are additional design needs for this as more discovery work continues in other tickets - we can open a new design ticket/and or make a spike. @RakshindaAslam @ahay-agile6
