### ISSUE TITLE
Reset your password for SpringML UAT App

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#6666]
9/7 @ 7:08PM noreply@osdh-covid-case-investigation.firebaseapp.com

Hello,

Follow this link to reset your SpringML UAT App password for your reportstream@cdc.gov account.

Reset Password Here

Afterwards, you can begin uploading COVID-19 cases here: SpringML UAT App

If you didn’t ask to reset your password, you can ignore this email.

Thanks,

SpringML team

**Comment by sliu1000** [comment]
resolved.
