### ISSUE TITLE
Implementation - Improve HL7 Errors and Warnings

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6667]
As a sender or an O&O team member, I want to get easy to understand error and warning msgs on uploading an HL7 file in the Validation Service.

## Need to know
- [ ] Work breakdown for error msg improvement initiative
https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1659379562245/028bbeb7dd7b819298ba1b436703882855bc767f?sender=u3fea607b46e84058d3224917

- [ ] Here are where the API error/warning messages are generated: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/ActionMessages.kt

- [ ]  Seth's inventory of warning and error msgs
(https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FTeam%20Documents%2FExperience%20Team%2FEngineering%2FMisc%20Experience%20Eng%20Docs&viewid=17db3ff6%2D95c5%2D4562%2Da1f3%2D12b5097b5947)

- [ ] [Figma file](https://www.figma.com/file/b2Zd1xzmp4cdwFO8O7edcI/CSV-Uploader-%26-Validation?node-id=2652%3A1578)
Design Ticket #5869 - An outcome is a content template to replace current error and warning msgs.

## Acceptance Criteria
- [ ] Replace existing error and warning msgs with the ones described in the content template in #5869. 
- [ ] Update the UI if there are wireframe changes in #5869

**Comment by HeatherRienks** [comment]
@kevinhaube - per our convo, this might be a candidate to be closed (and grouped with external VS work, along with 5822).

**Comment by HeatherRienks** [comment]
Per our convo, this ticket can be closed - this was merged in PR #6889.
