### ISSUE TITLE
Adding users to receiver list- Pima county AZ

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#6678]
From amanda.sapp@pima.gov -9/9 @ 11:00AM.

I'd like to set up a new user account with ReportStream for 4 folks in my organization please

1.    Name: Amanda Sapp
Job title: Epidemiologist
Organization: Pima County Health Department

Phone number: 520-724-8145
Email address: Amanda.sapp@pima.gov
Organization that referred me to ReportStream: Pima County Health Department
Public health department(s) I report to: Pima County Health Department
Current reporting method(s): Pull down data from database compile and report to leadership

2.    Name: Matthew Christenberry
Job title: Program Manager
Organization: Pima County Health Department

Phone number: 520-724-7760
Email address: Matthew.Christenberry@pima.gov

Organization that referred me to ReportStream: Pima County Health Department
Public health department(s) I report to: Pima County Health Department
Current reporting method(s): Pull down data from database compile and report to leadership

3.    Name: Anissa Taylor
Job title: Epidemiologist
Organization: Pima County Health Department

Phone number: 520-724-7972
Email address: Anissa.Taylor@pima.gov

Organization that referred me to ReportStream: Pima County Health Department
Public health department(s) I report to: Pima County Health Department
Current reporting method(s): Pull down data from database compile and report to leadership

4.    Name: David Harris
Job title: Program specialist
Organization: Pima County Health Department

Phone number: 520-724-5900
Email address: David.Harris@pima.gov

Organization that referred me to ReportStream: Pima County Health Department
Public health department(s) I report to: Pima County Health Department
Current reporting method(s): Pull down data from database compile and report to leadership

**Comment by GilmoreA6** [comment]
Added users and sent activation emails. Matthew Christenberry already had an accounts but it was suspended for inactivity. An activation email was re-sent.

**Comment by sliu1000** [comment]
Emailed users to confirm they were able to log on.

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 work with Help desk to confirm with user so we can close out

**Comment by GilmoreA6** [comment]
closing as now engagement from users.
