### ISSUE TITLE
OTC Mapping Question

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6682]
## Problem statement

We received an email from user who is working with ReportStream Dataset in HHS Protect.
While reviewing the data they had a few questions:

1) While viewing the Abbott OTC Tests.  They want to know how the columns are mapped from the original message to the columns in the dataset?

2) There's no patient zipcodes.  Are the zip codes getting stripped from the data before being sent over?

## What you need to know

Original Communication from User:

We have been working with the ReportStream dataset in HHS Protect (reportstream_v3_cleaned) and had two questions relating to the data:

There are only ~1 million tests from **Abbott** with the expected **OtC** test type in the correct OBX 23.1 format: SA.xyz (ex. SA.OTCSelfReport) from sending_facility_namespace_id. **Could you please inform us how the columns are mapped from the original message to the columns in the dataset?**
Manufacturers like Abbott, BD Veritor, CueHlth, and Ellume require patient zip code before allowing the patient to use their OtC Covid test app. However, there is **no patient zip code data** in the dataset. **Are the zip codes getting stripped from the data before being sent over?**

## Acceptance criteria

- Provide answers to questions 1 and 2, described above.

## To do

- [ ] ...

**Comment by BerniXiongA6** [comment]
@sliu1000 could you forward the email to me so I can look into this?

**Comment by sliu1000** [comment]
@BerniXiongA6 Just forwarded it to you.

**Comment by BerniXiongA6** [comment]
Looks like these 2 questions were originally sent to Rick Hawes and Alicia Beckett via email and then likely forwarded to ReportStream to answer? Who would know the answers, @MauriceReeves-usds @brick-green ?

**Comment by sliu1000** [comment]
Duplicate to ticket # 6817
