### ISSUE TITLE
RS Website Content - Homepage

### ISSUE THREAD

**Issue by a-chappelear** [CDCgov/prime-reportstream#6687]
## Problem statement

As a viewer of the RS public website, the current homepage is geared very specifically to STLTS/receivers. It is not clear or obvious to senders where to go from here.

I would like to see clear call to actions per user type and understand the benefits of RS for both of these personas.

## What you need to know

[Collected O&O feedback on site improvements](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1660180328563/e7dc91609e755a98404473d9de14072f2d5f9b79?invited=true&sender=uc91f7c72c0f84196a8818813)
Much of current homepage content is identical to https://reportstream.cdc.gov/product/overview - consider condensing this and making the CTAs more obvious.
[Note past work/comments on this previous ticket](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5821)

## Acceptance criteria

- [ ] Updated wireframe on homepage design/layout
- [ ] Content revisions on both the homepage and product section if needed. 
- [ ] Review proposed changes with O&O
- [ ] Once approved, supply implementation details and/or prep an implentation ticket if being handled by the design team

**Comment by chris-kuryak** [comment]
Already incorporating into new homepage design. This is duplicative and old/stale.
