### ISSUE TITLE
RS Website Content - Product

### ISSUE THREAD

**Issue by a-chappelear** [CDCgov/prime-reportstream#6688]
## Problem statement

As a viewer of the RS public website's product section, much of the content for a sender and receiver are grouped together and it's unclear which benefits which - especially in the "why" sections.

It is also unclear how some of the benefits "save time" - I would like to understand this more clearly.

## What you need to know

Collected O&O feedback on site improvements
_Please refer to the collected feedback, as there are numerous questions on what we actually do provide or not (and how)_

## Acceptance criteria

- [ ] Updated wireframe on product design/layout (if needed)
- [ ] Identify who can clarify content on these pages and if it's correct (schedule time and collect that feedback.)
- [ ] Review proposed changes with O&O and internal
- [ ] Once approved, supply implementation details and/or prep an implementation ticket if being handled by the design team

**Comment by a-chappelear** [comment]
Please consider pulling this ticket [in with the homepage ](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6687)(or shortly after) so there is not a disparity in content updates.

**Comment by chris-kuryak** [comment]
This is old/stale. Already being involved in the new ReportStream website redesign happening now.
