### ISSUE TITLE
RS Website Content - Resources 

### ISSUE THREAD

**Issue by a-chappelear** [CDCgov/prime-reportstream#6689]
## Problem statement

As a viewer of the RS public website's resources section, much of the selections for a sender and receiver are grouped together and it's unclear which applies to who.

## What you need to know

[Collected O&O feedback on site improvements](primedatainput6410/1660180328563/e7dc91609e755a98404473d9de14072f2d5f9b79?invited=true&sender=uc91f7c72c0f84196a8818813)
Consider also eliminating the repetitive use of the word "guide", and group sections appropriately by user types.

[Mural with updates](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1667328248835/9317b8b37c030fe0edae0b5c42fe5df48472f404?sender=ua604735c5cf1162b042a4310)

## Acceptance criteria

- [ ] Updated wireframe on product design/layout (if needed) 
- [ ] Identify who can clarify content on these pages and if it's correct (schedule time and collect that feedback.)
- [ ] Review proposed changes with O&O and internal
- [ ] Once approved, supply implementation details and/or prep an implementation ticket if being handled by the design team

**Comment by BerniXiongA6** [comment]
Happy to pair with someone on Exp. team to revisit this work as the O&O rep. If we need to add anyone else in the convo, I can arrange that. Thanks! cc: @HeatherRienks

**Comment by HeatherRienks** [comment]
@BerniXiongA6 -thank you for your offer! The public site updates are a part of our Stretch goal for this Sprint (53), but we should def discuss this priority with the product team.
cc: @fmccaf1

**Comment by BerniXiongA6** [comment]
All old content files for this project can be found here: https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Website%20Copy%20Writing/Proposed%20Outline%20for%20RS%20Website%20Content%20Infrastructure%20Revisions%20-%20June%202022%20to%20July%202022.pptx?d=w87cf87a3bb9e404fbf38902c79c03fd6&csf=1&web=1&e=pTVcvp cc: @fmccaf1 @HeatherRienks

**Comment by fmccaf1** [comment]
### Findings from call w/ Berni - 11/4
- Programmer's guide needs update: both content and format
- Getting started: PHDs needs help, Berni happy to be SME
- ELR onboarding checklist: no longer accurate and unclear, should get rid of
- CSV download guide needs some updates, but other CSV resources can be removed
- Keep security practices and systems and settings

**Comment by fmccaf1** [comment]
Account registration guide updates documented in ticket [7307](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/7307)

**Comment by fmccaf1** [comment]
### Still to do on this ticket

- [ ]  Need Berni's okay on newly edited "Account registration guide" [which can be found with all other content updates on this mural board](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1667328248835/9317b8b37c030fe0edae0b5c42fe5df48472f404?sender=ua604735c5cf1162b042a4310)

- [ ] Need Berni's okay on removing ELR onboarding checklist but allowing the link to work to continue to access (and a sense of how long this should be accessible?)

### Info on other tickets
- Programmer's guide work has its own epic [5813](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5813)
- Need Berni's okay on "Guide to receiving RS data" and "Guide to submitting data to RS" but this work on feedback is captured already in [7098](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/7098)

**Comment by fmccaf1** [comment]
One more: 

- [ ] Need Brick's okay on removing ELR onboarding checklist but allowing the link to work for those that may still have access to it (and a sense of how long this should remain available?)
