### ISSUE TITLE
RS Website Content - Sender onboarding

### ISSUE THREAD

**Issue by a-chappelear** [CDCgov/prime-reportstream#6690]
## Problem statement

As a sender of the RS public website's resources section, I would like to see guidance on onboarding for a sender.
 
Currently, there is only one for a receiver - https://reportstream.cdc.gov/resources/elr-checklist

## What you need to know
[
Collected O&O feedback on site improvements](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1660180328563/e7dc91609e755a98404473d9de14072f2d5f9b79?invited=true&sender=uc91f7c72c0f84196a8818813)

## Acceptance criteria

- [ ] Updated wireframe on product design/layout (if needed) 
- [ ] Work with O&O to author this content
- [ ] Review proposed updates with O&O and internal
- [ ] Once approved, supply implementation details and/or prep an implementation ticket if being handled by the design team

**Comment by chris-kuryak** [comment]
No longer needed. Being encompassed by new website redesign currently in progress.
