### ISSUE TITLE
Nevada - ELR Messages Missing Patient Information

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#6691]
Linda King - linda@endpointdev.com 9/10 at 3:43pm 

All of the production messages we are receiving through Report Stream are de-identified.  The patient name and addresses have been removed.

Would you please have a look?

Thank you.
Linda

**Comment by brick-green** [comment]
I promoted the receiver from staging to production but didn't turn off the de-identify setting. So I just did that. 

@shy2cdc Can you ask them to review the next file that comes through? If it looks good, then I can go back and resubmit the other results.

**Comment by shy2cdc** [comment]
Just sent Linda the below. 

Hi Linda, 

Our engineers have requested that you review the next file that comes through to you. If you approve of it, we will go ahead and resubmit the other remaining results.
