### ISSUE TITLE
Fix the ./prime sender-files to download he message from prod.

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#6705]
The ./prime sender-files download message from prod is broken.  It needs to be fixed.

To duplicate the issue fo the fillowing:
  1.) ./prime login --env prod
  2.) ./prime sender-files --env prod --message-id $msgId -o $outputDir

You should see error code 503.

**Comment by BerniXiongA6** [comment]
Blocking the 3000 resubmissions work ( @brick-green will create those tickets )

**Comment by brick-green** [comment]
echo function was deprecated by dependabot. But the command files are not tested so it was not caught.
