### ISSUE TITLE
Innolitics onboarding to staging

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#6707]

**Comment by GilmoreA6** [comment]
10/6/22 - Sent Innolitics Keys to connect to staging and prod and waiting test file to staging.

**Comment by GilmoreA6** [comment]
"Thanks Sam'an,

I have sent the keys via keybase. The next step will be sending a sample file to staging. Please do not include any real patient data in this test file.

Thanks,

James"

**Comment by GilmoreA6** [comment]
-Innolitics getting 401 error when attempting to send to staging. Investigating.

**Comment by GilmoreA6** [comment]
Hi Sam'an,

It looks like for some reason that second test file has incorrect state abbreviations for patient_state and ordering_provider_state. The states should use the two letter postal code abbreviations found here (https://pe.usps.com/text/pub28/28apb.htm). For example in the sample file "GEORGIA" is abbreviated "GE" instead of  the correct "GA".

One other thing I've noticed is it looks like for columns ordering_provider_first and ordering_provider_last the file is populated with the patient name. For OTC data we do not want the patient name in this field as it will cause issues for our deidentification logic (if this is just an artifact of how you generated the test data that is fine but I wanted to check that we would not receive the patient name

**Comment by shy2cdc** [comment]
Email from Sam'an:

Sounds great,
I've defaulted all of the ordering provider information to blank and I'm still getting that same error message. I've attached a copy of the latest report for your reference.
Sam'an Herman-Griffiths
Junior Software Engineer
Innolitics

**Comment by GilmoreA6** [comment]
Excellent,

I received the files and they look as expected. Our next and last step will be sending some production data to our production endpoint and testing with a STLT of your choosing (usually the one that will have the most reports). Is there a particular state or healthcare jurisdiction that you would like to use? (note that not all will accept OTC data)

Also, in my notes I have that we were testing with a different test than production while we were waiting on EUA approval. Has that been completed, or are we still waiting for that to occur?

Thanks,

James

James Gilmore (Agile Six)
Senior HL7 Data Analyst
Pandemic-Ready Interoperability Modernization Effort (PRIME)
