### ISSUE TITLE
Facilities table shows un-grouped entries

### ISSUE THREAD

**Issue by hannasage** [CDCgov/prime-reportstream#6711]
## Problem statement

Facilities table shows un-grouped entries from the same CLIA. These entries should be summed on a single line.

## What you need to know

Facilities table lives in Daily Data > Details (click on report id)

https://github.com/CDCgov/prime-reportstream/issues/6252#issuecomment-1245246871

## Acceptance criteria

- [ ] Facilities table only shows one row per CLIA
- [ ] Accurately sums total test for a single CLIA

## To do

- [ ] ...

**Comment by kevinhaube** [comment]
Makes sense to do #6712 first in case that fixes this bug! This is produced only on the _old_ endpoint thus far.

**Comment by stephenkao** [comment]
@kevinhaube @HeatherRienks I think this was already taken care of in #6712 -- can you confirm?

Just tracing back from [`getDeliveryFacilities`](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/history/azure/DeliveryFunction.kt#L173-L192), it looks like the facilities are [pulled in from the `report_facilities` procedure](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/history/azure/DatabaseDeliveryAccess.kt#L107), which already groups by [a few attributes (including CLIA)](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/resources/db/migration/V19__add_report_facilities_function.sql#L53-L57).

And just checking locally, it looks like the tests are already grouped by CLIA:
![Screenshot 2022-12-13 at 2.19.08 PM.png](https://images.zenhubusercontent.com/5999b3b38f62dc7798c36942/a5a65445-1b2f-49a8-89a0-f999f04ff02b)

Let me know what y'all think!  🙏

**Comment by kevinhaube** [comment]
@stephenkao My only concern left would be to ensure production is effectively doing this. This bug, I believe hasn't ever been truly observable in staging (a gripe I often share is that there's incongruences between staging/prod).

**Comment by stephenkao** [comment]
> @stephenkao My only concern left would be to ensure production is effectively doing this. This bug, I believe hasn't ever been truly observable in staging (a gripe I often share is that there's incongruences between staging/prod).

Just checked production, and it looks to be working there!  (Not gonna screenshot anything just in case, but I'm happy to send a link :P) The `Total tests reported` is also correct re: https://github.com/CDCgov/prime-reportstream/issues/6252#issuecomment-1245250728

**Comment by kevinhaube** [comment]
Perfect! Should be good to close this then. 😄
