### ISSUE TITLE
CA - MSH-4 confusion - Resubmission

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#6724]
CA expected CSV uploaders to have CDPH000085 in MSH-4, they were initially being reported with CDPH000087, then during the portover we confirmed that the MSH would change from that 87 to 85 identifier.

The issue has been fixed. Now we need to look to resubmission. The full list is >3000. Spliting that list into multiple tickets of 500 each.

**Comment by brick-green** [comment]
There are 1198 records that have been purged from RS. Of those 113 are positive

**equipment_model	count**

BioFire COVID-19 Test | **count = 19**
BioFire Respiratory Panel 2.1 (RP2.1)*@ | **count = 2**
LDT: PacificDx Covid-19 | **count =  74**
Xpert Xpress SARS-CoV-2 | **count = 18**

**Comment by brick-green** [comment]
Email sent to CA asking if we need to resend the full remaining list (1197) or only the positives (113)

**Comment by sliu1000** [comment]
Update: Response from CA State on 9/29/2022

Thank you, Brick & team!


For CA COVID reporting, if results are negative antigens, we do not need these, if the remaining 1197 have positive & negative PCR results, CA does require these to be reported.
Confirmation on PCRs vs Antigens can help, thanks & let me know if there are any other questions?

Thanks!
Vanessa Burkhart

**Comment by brick-green** [comment]
Of the 1197, 1174 are molecular tests and need to be resubmitted according to CA rules. I asked Nathan with SR what the process is for manually pulling in the needed files.

**Comment by brick-green** [comment]
CA agreed on the sync today that we only need to send the 113 positive results. I reached out to Laura King with SR to coordinate
