### ISSUE TITLE
Handle result in any OBX Set ID

### ISSUE THREAD

**Issue by jbiskie** [CDCgov/prime-reportstream#6733]
## Problem statement

Currently ReportStream requires that the COVID-19 result appears in the first OBX instance (typically Set ID = 1). Providence results may appear in any Set ID. While atypical for our senders, this is valid and allowed by the HL7 spec. So we need to be able to accommodate this.

This is a blocker for full onboarding of Providence.

## What you need to know

Examples are in keybase under Providence.

- sender_info/Providence/2022-08-26/ELR_Raw_message.txt
- sender_info/Providence/2022-08-26/POC_Raw_message.txt

Note this samples will generate some other warning and filter issues. The related warning is "The code N for field OBX-5 is invalid."

You can also reorder the OBX segments in a working message to achieve the same outcome.

## Acceptance criteria

- [ ] Message with a result appearing in an OBX instance other than the first is successful.

**Comment by BerniXiongA6** [comment]
Providence is currently on hold, could engrs shadow Joel/Jorge on this? cc: @BerniXiongA6

**Comment by jbiskie** [comment]
Met with Brick, James, and Ott today to go over findings so far and potential solution paths. The testing and research modifications are in the `onboarding-ops/6733/results-any-obx` branch.

**Comment by brick-green** [comment]
have the coding completed - writing tests and commenting
