### ISSUE TITLE
Make Table handle suspense and error

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#6735]
## Problem statement

Right now, our custom `Table` component loads all data before any table structure is shown; the result is a spinner on a blank page. What's more preferable is the user already accessing the table UI, and the loading spinner only populating the part of the page where the data has not loaded.

In laymen's terms: **we should see the table headers even if data is still loading!**

## What you need to know

We've spun our own `Table` because the Trussworks USWDS package has been notoriously difficult to work with in testing, and our heavy use of tables led to some custom functionality needs in our Table component, such as providing a `filterManager` and `paginationProps`. **Lots of areas for improvement, always keep your eye out for a good refactor in this component system!**

Data is loaded inside parent components and passed in via the TableConfig -- this model would have to change, likely, to support this work.

We rely on `Suspense` for fetch loading state, and should be implementing both a Suspense and ErrorBoundary here. See docs here: https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/docs/rs-error-boundary-and-suspense.md

## Acceptance criteria

- [ ] The `Table` component loads data, but still shows the empty table and headers while fetching
- [ ] The `Table` component uses our desired EB/Suspense pattern for error and loading state management

## To do

- [ ] ...

**Comment by kevinhaube** [comment]
Will re-write this to better reflect the problem and AC

**Comment by kevinhaube** [comment]
@CnoteNava Great enhancement to our Table component, and my hope is this work will spawn other refactor ideas. Let me know if you wanna chat; think this could be great for next sprint!

**Comment by stephenkao** [comment]
Closing because this is something we'll naturally work on as we create a better consolidated table component.
