### ISSUE TITLE
OK - Create organization and receiver settings

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#6740]
### Problem Statement
Oklahoma will be a new jurisdiction connecting with ReportStream. They will need an organization and receivers added to the settings. There should be a receiver for testing and production.

### Acceptance Criteria
 - Organization created with jurisdictional filter for OK
 - Receiver for test environment created
 - Receiver for production env created

### To Do
- [ ]  Add organization and receivers to local org file
 - [ ] create yml files in settings/prod and settings/staging
 - [ ] add settings to staging
 - [ ] add settings to production

**Comment by BerniXiongA6** [comment]
@greene858 @brick-green I just created this ind. ticket for OK onboarding epic. If this has already been completed, go ahead and close it out. But at least we have it on record. If it still needs work, let's get this assigned asap. Thanks!

**Comment by oslynn** [comment]
@BerniXiongA6 , after looking at the setting and database.  It looks like it is done.  I am confirming with @greene858 to see if this ticket can be closed or not.  If it is, I will close it.

**Comment by oslynn** [comment]
Tom Green is working on it.
