### ISSUE TITLE
CA - Incorrect result submission during Ascensions

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#6747]
From: vanessa.burkhart@cdph.ca.gov

Thanks for this update! I was spot checking accessions from the file I sent over & found we have not received the corrected results.

Example accession: MCL74708  received 8/25, MSH-4 not containing CDPH000085 led to error in our CalREDIE system:
![ascensions.png](https://images.zenhubusercontent.com/62828b77597e3bdcbc3834fd/6584e5b2-ac10-46b7-a776-7e0c2be6cbb0)

**Comment by shy2cdc** [comment]
From Vanessa:

Hi all,

Hope the week is well.

 

Looks like there was an attempt for these to be resent, but they are still facing the same issue: MSH-4 does not have CDPH000085 as expected so these results received today are still not processing, example from Pacific Clinical Lab seen today:

 

`MSH|^~\\&|CDC PRIME - Atlanta,^2.16.840.1.114222.4.1.237821^ISO|PACIFIC CLINICAL LAB^05D2062640^CLIA|CDPH CA REDIE^2.16.840.1.114222.4.3.3.10.1.1^ISO|CDPH_CID^2.16.840.1.114222.4.1.214104^ISO|20220920165513+0000||ORU^R01^ORU_R01|082222_75+60+20220920|P|2.5.1|||NE|NE|USA|UNICODE UTF-8|ENG^English^ISO||PHLabReport-NoAck^ELR_Receiver^2.16.840.1.113883.9.11^ISO\r`

SFT|Centers for Disease Control and Prevention|0.2-SNAPSHOT|PRIME ReportStream|0.2-SNAPSHOT||

![image.png](https://images.zenhubusercontent.com/62827d1e0129e15b5c366b1a/1c5d0f0f-9116-47c3-9ab7-47fe5b7b8e39)

**Comment by brick-green** [comment]
@jorg3lopez  is resubmitting these under ticket #6726
