### ISSUE TITLE
404 pages broken with new router

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#6754]
1. Go to non-existent URL: e.g. `http://localhost:3000/admin/foobar`
Observe: blank content body is returned instead of 404 content

<img width="450" alt="image" src="https://user-images.githubusercontent.com/74203452/190685220-1bc0a1a9-4170-4460-b0f2-f3939d7469ec.png">

**Comment by kevinhaube** [comment]
Closed by: https://github.com/CDCgov/prime-reportstream/pull/6753 :) thanks Tom!
