### ISSUE TITLE
CO Sender - Validate test files from Vault

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#6762]
### What you need to know

- Vault has 2 states they report to that are requesting a switch over to ReportStream: Colorado and Delaware. Vault is already set up for Delaware, but now they need to be connected to Colorado.
-  Kickoff via email has already been completed.

### Acceptance Criteria
...

### To Do
- [x] Once engineer is assigned, have @BerniXiongA6 forward all email chain along with sample file to be validated.

**Comment by sliu1000** [comment]
Tara Brook from redoxengine provided a sample message file for review.

**Comment by GilmoreA6** [comment]
note: The organization's name in ReportStream is reopenlab.

**Comment by GilmoreA6** [comment]
9/27 - Provided feedback on initial test file. Also, tried to get clarification on sending to Delaware.

**Comment by GilmoreA6** [comment]
Vault does not appear to be set up for DE yet either. There is some confusion about the LIVD values as the test kit used does not appear on the table. Sent email to integration engineer and Vault employees asking for clarification.

**Comment by GilmoreA6** [comment]
Message sent to Tara Broke (tara@redoxengine.com)

"Hi Tara, 

Other than the LIVD table value not matching, everything else looks good. While we wait for the folks at Vault, the next thing to decide will be whether you want to use token-based authentication or a shared secret key for connecting to the API. Both methods are described in the Programmer's Guide (https://reportstream.cdc.gov/resources/programmers-guid
CDC Prime ReportStream
ReportStream Dashboard Application
reportstream.cdc.gov
e) with examples. 

We typically use Keybase encrypted messaging (Keybase.io) to share keys, so if possible if you could create a Keybase account and let me know your account name that would be great. If Keybase is not an option for your organization we can use secure email as an alternate method.

Thanks,

James"

**Comment by sliu1000** [comment]
This looks like it's on hold due to their device not being FDA approved.
