### ISSUE TITLE
IL - Missing City Data

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#6775]
From User:

Report Stream Team,

 

We had a complaint about several records coming in with no city and I am wondering if that is an issue that can be corrected.  I am not sure if this is an issue with your system or the submitting facility but all the ones in this file from different labs are all missing the city for the patient address.  This file was sent on 9/2 but the issues was just reported to us today and no one on our end caught it. 

 

These are all coming from different locations. 

![image.png](https://images.zenhubusercontent.com/62828ac9597e3bae41382df7/d96b01a3-7b46-469a-90f0-eb177ece8f82)

Can you please look into this and let us know if more information is needed. 

Thanks

Todd

**Comment by oslynn** [comment]
2022-09-27: Sent email to ask for message ids instead of screenshot.

Dear: IL

I am looking to fix the issue of your messages that missing city.  Would you please provide with list of message ids of those messages?
Therefore, I can search for them easily.

Greatly appreciated,
-Ott Sathngam
CDC SW ENG.

**Comment by Jcavallo7** [comment]
Message ID's for resubmission







`b56da2c1-8d32-4346-88cc-ad284a56fa90`
`464f4087-53a7-4dde-9650-92a245edce14`
`b0e09fb9-995b-48b4-97d7-6eca4dcebf6a`
`8dccdfae-4c32-4b18-aa10-0f4a41972050`
`56189dcc-a7a4-4a32-8eb3-82f2a14e2bdf`
`616757e3-55e5-4e93-a671-5cf1fd3ae885`
`ae05733b-911e-4afa-86cd-3538e746ea02`
`7ac95dc9-deae-4447-8360-7617ce2c3a28`
`d8112dc5-980b-4618-b290-6f1d1dd19e4f`
`39416559-cac9-4281-bd71-6b79efb0ed56`
`a6194867-292f-4cf6-b425-5ec071d7c0f2`
`68d0bb1b-45ff-4dc1-bbc0-6f0c3b0ffC7c`
`372b33f4-5975-4960-a2e0-d3bbff3733bc`
`b547d34e-47c1-4056-b8f9-adb4812ccc63`
`927276b0-5756-482b-b357-f65033dbd900`

**Comment by oslynn** [comment]
2022-09-28:   Analysed and Requested resubmission.

Email:
Emma, Jayna

The following message IDs are missing patient City Address those messages are from SimpleReport to IL:

b56da2c1-8d32-4346-88cc-ad284a56fa90
464f4087-53a7-4dde-9650-92a245edce14
b0e09fb9-995b-48b4-97d7-6eca4dcebf6a
8dccdfae-4c32-4b18-aa10-0f4a41972050
56189dcc-a7a4-4a32-8eb3-82f2a14e2bdf
616757e3-55e5-4e93-a671-5cf1fd3ae885
ae05733b-911e-4afa-86cd-3538e746ea02
7ac95dc9-deae-4447-8360-7617ce2c3a28
d8112dc5-980b-4618-b290-6f1d1dd19e4f
39416559-cac9-4281-bd71-6b79efb0ed56
a6194867-292f-4cf6-b425-5ec071d7c0f2
68d0bb1b-45ff-4dc1-bbc0-6f0c3b0ffC7c
372b33f4-5975-4960-a2e0-d3bbff3733bc
b547d34e-47c1-4056-b8f9-adb4812ccc63
927276b0-5756-482b-b357-f65033dbd900

Would you please have the sender fill in the patient city address and resubmit them to ReportStream?

Very respectfully,
-Ott Sathngam
CDC SWE

**Comment by BerniXiongA6** [comment]
@oslynn need to verify

**Comment by oslynn** [comment]
Ott,

Do you have any update on this issue?  The local health department has asked and found another case for the following message control ID.

ba1c56c2-a3a3-4e86-9a80-35036d2d09ab

Thanks

Todd

**Comment by shy2cdc** [comment]
Email from Todd:

What about just fixing the issue so we don’t have more come in? 

 

Todd

**Comment by oslynn** [comment]
2022-10-21: @sliu1000 and I have found the SR csvupload has Patient City Address as required field.  However, in manual, it is not required.  To fix this issue for all STSLs, @sliu1000 will ask SR team to make it as required field.  

After SR compete the task, this ticket can be closed.

**Comment by sliu1000** [comment]
Fwd'd to SimpleReport to update.
