### ISSUE TITLE
Intrivo post-product issue: Error : Blank value for element ORC-22-4 (ordering_facility_state)

### ISSUE THREAD

**Issue by sarahnw** [CDCgov/prime-reportstream#6780]
Intrivo is having some messages fail to send through based on what they expect is a blank state, zip code provided.
They're receiving this error "Error : Blank value for element ORC-22-4 (ordering_facility_state)"

I think this is because we handled this via patient state and not ordering facility state in ticket 5700. 

A/C
- confirm that the RADX MARS spec either requires or does not require ORC-22-4
- confirm if RS requires ORC-22-4 or if optional
- if it does not require and we should fill in based on zip code, create a new ticket to implement same logic from 5700 for ORC-22-4

**Comment by sliu1000** [comment]
Update from Karim from Intrivo:

Please note that since OnGo tests are not prescription and are considered OTC, we are using Patient (PID) address field values for Ordering Facility (ORC) based on the direction from the implementation guide.
