### ISSUE TITLE
DE - Create workaround for ORC-12-2 and ORC-12-3 fields that are blank

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#6786]
## Problem statement

Ongoing blank ORC-12-2 and ORC-12-3 fields in ImageMover's schema will continue to cause system failures for Delaware. ReportStream can create a workaround for Delaware so that we can prevent the fields from blanking.

## What you need to know

This is the email @BerniXiongA6 sent to Delaware:

> Hi Uche and Christopher,
> 
> We wanted to circle back to you regarding the DE test result data from ImageMover that were failing the system due to blank ORC-12-2 and ORC-12-3 fields. 
> 
> After working on this issue, our engineer Jorge found that the schema from ImageMover was purposely blanking these fields in order to prevent a PHI/PII leak. ImageMover has since come up with a fix to ensure that no PHI/PII will leak by disabling those fields; however, the field values are still coming in blank to ReportStream. 
> 
> To prevent future failures in your system, ReportStream can work something out on our end if Delaware would like a default value that should be printed out when the fields are blank and that can display values if the fields do contain a value.
> 
> What are your thoughts on on this? I've copied in Jorge if you have any technical questions you'd like to have answered before moving forward with a fix on our end.
> 
> Thanks,
> Berni
> 

## Acceptance criteria

- [ ] The default Ordering Practitioner is set as "Dr. Gregory Warner" for any messages that come through that do not already have an Ordering Practitioner value provided in that field.

## To do
- [ ] Contact Delaware once the workaround has been completed to confirm its completion

**Comment by shy2cdc** [comment]
Email from Christopher DE DOH:

Good Morning,

 

I am sorry, what is this regarding? Do you have the original ticket?

 

I submitted a ticket for the facility Milwaukee Brewers back in July that I still have yet to hear back from, but do not recall sending in anything for Image Mover.


Thank you for any other information.

**Comment by BerniXiongA6** [comment]
@jorg3lopez Imagemover is a data aggregator for milwaukee brewers, correct?

**Comment by BerniXiongA6** [comment]
Updates: @BerniXiongA6 has been emailing with Christopher from DE DOH:

Sent Mon 9/26/2022:

> Good morning, Christopher. 
> 
> Sorry for any confusion. To clarify, this issue is indeed in reference to your open inquiry regarding Milwaukee Brewers from July (Ticket # 6197). 
> 
> When we learned of the failures in Delaware's system, our engineer Jorge further investigated this to determine that the data aggregator's (ImageMover) schema blanks out the ORC-12-2 and ORC-12-3 values in order to prevent a PHI/PII leak since OTC data is submitted with the patient's name under those fields. As you're already aware, test results without ORC-12-2 and ORC-12-3 values fail Delaware's system. 
> 
> Since that time, we were able to reach out to ImageMover and they have implemented a fix (disabling those fields for OTC test results); however, the field values are still coming in blank to ReportStream when OTC data is being reported. Therefore, we would like to work with Delaware to recommend one of the following workarounds to prevent blank fields from failing your system.
> 
> Option 1: ReportStream could create a second feed for Delaware, designated to filter exclusively for OTC data. The benefit in doing this, you can still receive OTC data but you don't have to see it in your primary Prod feed.
> 
> Option 2: When OTC data is sent in by ImageMover (on behalf of reporting facilities and organizations) to Delaware: if there are blank values in this fields, ReportStream can fill in a default value (e.g. "Default Name") instead to prevent test results without ORC-12-2 and ORC-12-3 values from failing Delaware's system.
> 
> I hope this provides more clarity around the issue and our proposed workarounds. Please let us know if you have any more questions as well as letting us know how you'd like to proceed.
> 
> Thank you.
> Berni


cc: @jorg3lopez @sarahnw @sliu1000

**Comment by BerniXiongA6** [comment]
Updates 9/26/2022: @BerniXiongA6 has been in contact with Delaware. Christopher Decker has confirmed they would like to go with option 2 and have asked that RS set the default Ordering Practitioner as "Dr. Gregory Warner when the field values are blank. This ticket is assigned to @jorg3lopez . cc: @sliu1000

**Comment by jorg3lopez** [comment]
#### Update:
Settings have been changed for DE to display "Dr. Gregory" "Warner" when ORC-12-2 and ORC-12-3 fields are blank.
