### ISSUE TITLE
Usability testing for Validation Service

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6789]
## Problem statement
Perform usability testing for Validation Service with O&O team to understand if the MVP delivers functionality as expected to allow internal admin to validate HL7 messages easily and get error/warning/quality filter messages for faster validation. The purpose of this effort is to identify what updates/new enhancements need to be made to make the tool useful for the  O&O team for reducing the time spent in manual validation today.

## What you need to know
This testing effort covers the initiatives for building the internal validation service(#5503) and improvement of error and warning messages(#5641).

[Notes from testing and summary of findings found in this Mural.](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1666190212832/25f971cebb2d289837352dc406cb379ce362068c?sender=ua604735c5cf1162b042a4310)

## Acceptance criteria

Performed usability test for the internal Validation Service MVP built for O&O admin team to identify:
- Satisfaction level with the MVP as delivered on a scale from 1-5 with both quantitative and qualitative feedback
- Issues/challenges with the UI/functionality of the feature, if any
- Enhancement requests/if any

## To do

- [ ] ...

**Comment by RakshindaAslam** [comment]
@a-chappelear - new ticket for pre-refinement. 
cc @HeatherRienks

**Comment by a-chappelear** [comment]
Test files if needed: [https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FTeam%20Documents%2FExperience%20Team%2FEngineering%2FMisc%20Experience%20Eng%20Docs%2FReportStream%20Errors%20%26%20Warnings%20Inventory%20%2D%20sample%20files&viewid=17db3ff6%2D95c5%2D4562%2Da1f3%2D12b5097b5947](https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FTeam%20Documents%2FExperience%20Team%2FEngineering%2FMisc%20Experience%20Eng%20Docs%2FReportStream%20Errors%20%26%20Warnings%20Inventory%20%2D%20sample%20files&viewid=17db3ff6%2D95c5%2D4562%2Da1f3%2D12b5097b5947)

**Comment by a-chappelear** [comment]
To test on staging, set yourself as a sender - ex: hcintegrations (set-up to accept Hl7)
The validator sits behind a feature flag of "validation-service"

**Comment by fmccaf1** [comment]
Testing and summary of findings complete (see Mural in ticket text). Closing ticket.
