### ISSUE TITLE
Add a loooong-wait retry delay when Send fails.

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#6797]
We agreed at the Monday 9/19/2022 Dev Sync that we'd explore adding one or two more retries, with long delays, to our "exponential" backoff mechanism.  Note that the backoff mechanism is already in place.  This is just a case of adding to it.

See `SendFunction.kt`.  As of this writing, these are the retries:

```
// index is retryCount, value is in minutes
// We often send every 2 hours.   Idea here is that the 4th retry occurs *before* the next round of sends, in 111 mins.
val retryDuration = mapOf(1 to 1L, 2 to 5L, 3 to 30L, 4 to 75L, 5 to 120L)
```
(Note:  that comment looks mildly wrong: there's no real pattern to how often we send any more.   We send as often as every 10 mins, and as rare as once a day)

In addition we talked about a feature to "Hold All Sends".  However, we believe this can be done now by shutting down just the Send step.  Should experiment to prove this is true, in Staging.

See PR #7185

**Comment by oslynn** [comment]
@mauricereeves @jimduff-usds.  Perhaps, this is time for us to incorporate the Circuit Breaker pattern to our SendFunction.kt.  Here is info: https://resilience4j.readme.io/docs/circuitbreaker.  Will you let me look into incorporate the pattern into our SendFunction? Please let me know.  I have done this with my past project.  Netflix and many other cloud services use the pattern to solve the very same network issue that we have.
