### ISSUE TITLE
ReportStream to HHS Protect - COVID Data - Mapping Question

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6817]
## Problem statement

Could you confirm that the original Reportstream message relating to OBX 23.1 is mapped to the column reportingFacility_1 in the dataset Reportstream_v3_cleaned?

## What you need to know

Original Email:

Hi Sharon,

Originally, the ~1 million tests from Abbott with the expected OBX23.1 format: SA.xyz was noted in the column reportingFacility_1, however, that column was stripped, so we do not have an example to share anymore. Therefore I want to modify my original question a bit. Could you confirm that the original Reportstream message relating to OBX 23.1 is mapped to the column reportingFacility_1 in the dataset Reportstream_v3_cleaned?
We figured out the issue that was blocking the zip codes coming in from the Reportstream side, and are now seeing the data. We will no longer need help looking into this matter.

Thank you for your time!

Timothy Tsung | Data Scientist
Laboratory Data Section | CDC
Deloitte Consulting | Mobile: 332-257-6892
Trx4@cdc.gov

## Acceptance criteria

- Confirm the original ReportStream Message relating to OBX23.1 is mapped to the column reportFacility_1 ?

## To do

- [ ] ...

**Comment by jbiskie** [comment]
Reviewed and emailed Tim

> Hi Tim,
> 
> I believe the answer to your question is yes. This is a bit tricky to answer because we don't have old examples either, and was from a time when there was a bug in our code. So I've had to rewind to determine how it worked back then. reportingFacility corresponds to OBX-23.1 for entities that send us HL7. (Abbott actually sends us CSV.) There was a duplicate column back then, which had the same name in our output. The reportingFacility_1 that you saw on your side should have corresponded to one of those two columns.
> 
> Hope this helps and let me know if you have other questions,
