### ISSUE TITLE
Update Terraform Azure provider

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#6819]
Need to update to >= V3.0, this is a breaking change!

**Comment by lucasdze** [comment]
At a high level, version 3.0 includes the following changes:

[New Data Sources and Resources for App Service and Function Apps](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide#new-resources-and-data-sources-for-app-service)
[Soft Delete Recovery/Purging for Certificates, Keys, and Secrets](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide#soft-delete-for-key-vault)
[Switching to Microsoft Authentication Library (MSAL)](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide#switching-to-msal)
[Updates to existing behaviors for Application Gateway, API Management, Resource Groups, Storage, among others](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide#behavioural-updates)
[Removal of Deprecated Fields, Data Sources, and Resources](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide#removal-of-deprecated-fields-data-sources-and-resources)

**Comment by lucasdze** [comment]
Documentation
https://github.com/hashicorp/terraform-provider-azurerm/blob/main/website/docs/guides/3.0-upgrade-guide.html.markdown
