### ISSUE TITLE
TX - Convert to key based authentication

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#6833]
## Problem statement

RS currently connects to Texas via SFTP using username and password authentication. The passwords expire every three months. At that time a member of the technical staff must reset the password via the Texas website. A technical staff member in Texas told us they can also authenticate via key based auth. That method will not expire and thus require much less maintenance. 

## Acceptance criteria

- [ ] Can connect to Texas via SFTP using public key authentication

## To do

- [ ] Create public and private keys
- [ ] Create new secret for TX in staging with private key
- [ ] Send public key to TX and ask them to install in their staging/test
- [ ] Send fake message to test connection
- [ ] Create new secret for TX in production with private key

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 keep an eye on, need to reset pw in 2 months time

**Comment by brandonnava** [comment]
@oslynn waiting for them to reply when they are ready

**Comment by oslynn** [comment]
Done.
