### ISSUE TITLE
[Submission History] Enable use with Receiver `reportId`

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#6843]
## Problem statement

As a Receiver, I need to query the History API and see any error/warnings and QF responses when fetching report details.

## What you need to know

STLT Feature Ideas (Mural): https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1660849046968/e257020850ab71f57b31120e27ec06203ae9c22b?sender=u67aa35711489d1496d0a7320

Stock of API functionality (Word): https://cdc.sharepoint.com/:w:/t/USDSatCDC/EXXo_HDcvhNBre9FnV_37pkBjNFwK7ZryxjpTROmxllQrg?e=VYoo3C

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by jimduff-usds** [comment]
The deliveries API, when queried on a single delivered report, could/should give info on the Senders it came from, the Facilities it came from, the timing, and _maybe_ other locations the data was sent to.

It could also the show warnings given to Senders, for data received.

However, it can't show information on data that was never delivered, which would include data that errored out, and data that was filtered out.

**Comment by kevinhaube** [comment]
@jimduff-usds 
This is not only `stale`, but truly `moldy`. _I'll_ close this one... and feel proud for my growth in the last 1000 tickets haha
