### ISSUE TITLE
[Daily Data] Flag reports with error/warning messages & QF responses 

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#6844]
## Problem statement

As a Receiver, I need to see an indicator on the Daily Data list that a report has error/warnings and/or QF responses.

## What you need to know

STLT Feature Ideas (Mural): https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1660849046968/e257020850ab71f57b31120e27ec06203ae9c22b?sender=u67aa35711489d1496d0a7320

Stock of API functionality (Word): https://cdc.sharepoint.com/:w:/t/USDSatCDC/EXXo_HDcvhNBre9FnV_37pkBjNFwK7ZryxjpTROmxllQrg?e=VYoo3C

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by jimduff-usds** [comment]
The deliveries API, when queried on a _single_ delivered report, could/should give info on the Senders it came from, the Facilities it came from, the timing, and _maybe_ other locations the data was sent to.

It could also the show warnings given to Senders, for data received.

These are good features to add.    However, doing this in the _list_ deliveries query may or may not be performant right now, so we might want to hold on that.

Important note:   No API can show something that doesn't exist.  It can't show information on data that was never delivered, which would include data that errored out, and data that was filtered out.

**Comment by kevinhaube** [comment]
@jimduff-usds 
Understood 👍🏼 Sounds like it'd be a lot of work, little gain right now, especially as we're working on revamping things. It's one of those "if we truly need it it'll naturally come back up". Chris K on Experience is a fan of closing tix like that! We currently have no designs supporting this, either.

**Comment by chris-kuryak** [comment]
Per comments above, closing as it is not a high priority and will naturally come up in the future if needed.
