### ISSUE TITLE
SPIKE: Document all existing routing operations required by the COVID pipeline

### ISSUE THREAD

**Issue by clediggins-usds** [CDCgov/prime-reportstream#6848]
To effectively ensure the universal pipeline is able to do routing, we need to document the existing routing capability in the COVID pipeline. Look at the types of routing options (e.g. jurisFilter, qualityFilter, etc.). - we need to specifically know each of the filters used within those categories and what they do (greaterThan, isWithin, etc...)

Dev Hints:
* Look in ReportStreamFilterDefinition.kt, all of the filter types are within this file and implement a shared interface
* the code that actually does the filtering is Translator.kt
* Document each item, and then go figure out which ones are actually used in prod at this time

AC:
* A list of each routing option and a short description of what it does, along with any strangeness / oddness that could be confusing to someone making the filter work for the universal pipeline.

**Comment by carlosfelix2** [comment]
Design is attached:
[https://app.zenhub.com/files/304423150/b0f41580-4e93-4b6d-957f-f752698796dc/download](https://app.zenhub.com/files/304423150/b0f41580-4e93-4b6d-957f-f752698796dc/download)

[https://app.zenhub.com/files/304423150/1e85fda6-1c2a-4768-ae1a-1865e2bb244f/download](https://app.zenhub.com/files/304423150/1e85fda6-1c2a-4768-ae1a-1865e2bb244f/download)

**Comment by carlosfelix2** [comment]
Results of the spike:[https://app.zenhub.com/files/304423150/cd842617-64f6-48b6-a8b0-febc0b7bba85/download](https://app.zenhub.com/files/304423150/cd842617-64f6-48b6-a8b0-febc0b7bba85/download)
