### ISSUE TITLE
ME - Create organization and receiver settings

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#6851]
## Problem statement

Maine will be a new jurisdiction connecting with report stream. They will need an organization and receivers added to the settings. There should be a receiver for testing and production.

## Acceptance criteria

- [ ] Organization created with jurisdictional filter for RI
- [ ] Receiver for test environment created
- [ ] Receiver for production env created

## To do

- [ ] Add organization and receivers to local org file
- [ ] create yml files in settings/prod and settings/staging
- [ ] add settings to staging
- [ ] add settings to production

**Comment by brick-green** [comment]
@oslynn I saw the you merged the PR for this already. But it looks like the values are incorrect. This information was in a comment on the epic for this ticket. Sorry I didn't add it to this ticket specifically.
```
What value do you want in MSH-5?​ MEDOH

What value do you want in MSH-6?​ MEDOH

Do you require us to put our own identifier and CLIA in MSH-4?​ Yes, please

Do you require a specific value in MSH-21-1 (Message profile ID)?​ We have facilities use “PHLabReport-NoAck”

Do you want to receive OTC results? If so, how would you like to receive them? No, thanks
```

Can you make another PR with these values included in the settings?

**Comment by oslynn** [comment]
@brick-green , I will create another PR to correct that.

**Comment by oslynn** [comment]
From Sarah:
**Do you have an implementation guide we should follow?**​ Nothing specific to Maine; we follow the PHIN HL7 spec for ELR

Do you accept HL7 v2.5.1?​ Yes, we prefer it
What sending protocol do you use to accept files?​
SFTP (preferred)​ This is our preferred as well
REST API​
AS2​
Do you accept HL7 batch messages?​ Yes
Would you like to receive the AoE questions?​ Yes
1. Frequency - we typically send files every two hours.​ That’s fine

If SFTP

How do we get credentials for an SFTP connection?​ Scott Snow can coordinate
Do the credentials need to be rotated/do they expire?​ They don’t expire
Do you need to whitelist our IP addresses before we connect?​ No
What file path do we need to write files to on the SFTP server? We’ll provide that info
What value do you want in MSH-5?​ MEDOH

What value do you want in MSH-6?​ MEDOH

Do you require us to put our own identifier and CLIA in MSH-4?​ Yes, please

Do you require a specific value in MSH-21-1 (Message profile ID)?​ We have facilities use “PHLabReport-NoAck”

Do you want to receive OTC results? If so, how would you like to receive them? No, thanks

These are the ones I (Scott) don’t have answers for yet -

Is there a limit on the number of messages in a batch?​
Do you require a specific file name format?​
Do we need to suppress the QST flag in OBX-29?​
Are there any other fields that are required? For example, the ordering provider information is sometimes missing, and some states won’t accept messages without it.​

**Comment by oslynn** [comment]
2022-10-11: I am closing this ticket for now.  According to @brick-green, ME is pausing the onboarding for now since they don't have enough man power.
