### ISSUE TITLE
Validate file for LimsABC for Nova for NJ

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6857]
Hi All,

The sending facility is Nova Diagnostics Lab CLIA:14D2216112. They send to ReportStream through a data aggregator called LimsABC. I have sent two test files to the test folder:

covid-19-379e58e7-9698-4713-a4db-7add338bb2d8-20220927145341 (MSH-10: RNLN12345)
covid-19-d0ce882a-be99-4198-8852-b7c8efa7eaa4-20220927150445 (MSH-10 RNLN45678)

Please let me know if you have issues finding the messages or if there are any corrections the sender needs to make to the format.

Thanks,

James (AGILE 6)
----------------------------------------------------------

Adrian Balint <adrian.balint@limsabc.com> 9/26/2022, 4:18 AM

Hi Sharon, 

Appreciate your response. I've noticed 2 requisitions that were approved for NJ patients. I've released those 2 results as well via the interface to the staging endpoint. Please let someone know to follow up with New Jersey and validate if possible the 2 messages. 

Thank you,
Adrian B.
LIMSABC

**Comment by sliu1000** [comment]
@GilmoreA6 - Is there a reason why NJ thinks the Labs should be reporting to them directly?

It looks like labs have started to send through ReportStream instead of dealing directly with us here at NJ DOH. 

However, they must still go through our on-boarding process.  Two important provisions are:

 They must submit an ELR Interface Enrollment form at https://cdrs.doh.state.nj.us/cdrss/common/cdrssELREnrollment 
As they are going through an intermediary, their lab name must appear in the file name, as this makes it easier for us to find and identify their files in our system.
 
Thank you,

**Comment by shy2cdc** [comment]
Email from Mark: Nova Diagnostics - ELR Feedback

We have reviewed your latest ELR Test files, and your issues spreadsheet is attached.


Thank you,

Mike Firkser

Technical Lead - NJDOH ELR Team

NJELR.Admin@doh.nj.gov

**Comment by shy2cdc** [comment]
Email from Mike: 

Documentation can be found at https://cdrs.doh.state.nj.us/cdrss/common/cdrssELREnrollment - we have links to our Implementation  Guide and Onboarding Manual on that page.

 

 

Thank you,

Mike Firkser

Technical Lead - NJDOH ELR Team

NJELR.Admin@doh.nj.gov

**Comment by sliu1000** [comment]
Update from Sender - Nova Labnetics Diagnostics:

Hi Joel,

I hope you are doing well. Wanted to follow up and see if we can start implementing ReportStream for our new LIS.

Thank you and Regards,
Basit Hussain | Chief Operating Officer

**Comment by GilmoreA6** [comment]
10/18 email to LimsABC - Waiting for response to requested changes.

"Hi Adrian,

Thanks for that info. Yes, there is another step that NJ requires. I've attached some instructions on how to sign up and complete the training for NJ's CDRSS portal (manual reporting portal). The lab will need to complete this training as part of the onboarding. For the HL7 side of things, NJ is requesting that we value the PID-3.5 field, if it is a unique internal ID for the patient the PID-3.5 should be "PI". They are also requesting that we value ORC-4.1, placer group number or "requisition number". If you could make those adjustments I would appreciate it.

To answer a question that Basit had asked on a separate email, we are currently receiving and reporting data for Illinois and Indiana for Nova Labnetics Diagnostics and we do not need to do anything special to report to everywhere that ReportStream is connected to except for three jurisdications (New Jersey, Washington and California) which require extra onboarding steps for every new sender. Please let me know if there are additional questions."

**Comment by GilmoreA6** [comment]
Waiting for Nova Diagnostics to complete NJ onboarding training
