### ISSUE TITLE
Allow users to maintain login status between tabs

### ISSUE THREAD

**Issue by doug-s-nava** [CDCgov/prime-reportstream#6868]
## Problem statement

As a logged in report stream user I would like to be able to open a report stream page in a new tab without having to log in again.

## What you need to know

The solution to this is storing login status in localStorage rather than sessionStorage. Our current system relies on sessionStorage as the source of truth for log in status, and this information is not shared between tabs, while localStorage is.

Logging in or out on one tab should also reflect on any other open tabs.

## Acceptance criteria

- Remain logged in when opening a new tab while logged in
- All open tabs log in or out when logging in or out
  - i.e. if I login/logout on one tab, other tabs should login/logout too
- No refreshes should be performed to sync a tab
  - Ideally no navigations either (except for login/logout redirect as appropriate)

## Design

1. Introduce a `session` broadcast channel which will be used to broadcast `login` and `logout `messages when the user logs in or out.

2. Listen to the broadcast channel and react accordingly (redirect as appropriate and ensure app state reflects session state)
  1. okta's `updateAuthState` function handled this nicely

## Notes

- Currently the [code](https://github.com/CDCgov/prime-reportstream/blob/thetaurean/6868-allow-users-to-maintain-login-status-between-tabs/frontend-react/src/App.tsx#L69) handling broadcast messages does not differentiate between `login` and `logout` messages because the handling code is the same in either case.
- On logout we always trigger other tabs to logout, even if logout failed. Maybe we don't want to trigger in some cases? Relevant finally statement [here](https://github.com/CDCgov/prime-reportstream/blob/thetaurean/6868-allow-users-to-maintain-login-status-between-tabs/frontend-react/src/utils/UserUtils.ts#L6)

**Comment by thetaurean** [comment]
Implementation is complete for maintaining logged in status when opening a new tab while logged in.

Improvements/Todo:
- On logout: Redirect to home/login? page on other tabs

**Comment by thetaurean** [comment]
- Refined ticket: added acceptance criteria, design, and notes
- Redid a good bit of the implementation
  - using BroadcastChannel instead of localStorage events
  - Simplified sync handling and handler registration
  - Added handling for login sync
