### ISSUE TITLE
WA - Data Resubmission - First / last both "Unknown"

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#6907]
User: Jennifer Risler
Email address: jenni.risler@doh.wa.gov
Submitting facility: WA DOH 

"Possible test data sent to production, two events identified.  First/last both "Unknown".

Request resubmission with corrections if data is for a real patient."

Message ID:
`8f04c1dd-4552-4e73-acf4-61b702a9428e`;  `f68c5fab-8653-40c6-8b7a-785c96445cd7`

**Comment by sliu1000** [comment]
@BerniXiongA6 

What's the priority on this one. We received this 10/3 and looks like it has not been assigned as well.

**Comment by BerniXiongA6** [comment]
I'm flagging resubmissions high just because I don't want them to expire. Whichever engineer taking this on, please ping @BerniXiongA6 with questions.

**Comment by jorg3lopez** [comment]
#### Update:
I was unable to get a hold of the inbound file and the outbound file because of the age of the ticket.  But with the information gathered, it seemed that these files were ready to be sent to MO and not WA. The above IDs are report_id(s) and not message_id(s). If we can get the message_id(s), we can check with SR if they can resubmit them, in case they came from SR.

**Comment by BerniXiongA6** [comment]
Hi @jorg3lopez what's our action item so I can update WA DOH on this? Also, can I help in any other way?

**Comment by BerniXiongA6** [comment]
BX sent updates to Jenni and WA DOH team on 11/1/2022:

> Hi Jenni and Team,
> 
> I wanted to follow up on Ticket # 6907.
> 
> Possible test data sent to production, two events identified. First/last both "Unknown".
> 
> Request resubmission with corrections if data is for a real patient.
> 
> 8f04c1dd-4552-4e73-acf4-61b702a9428e; f68c5fab-8653-40c6-8b7a-785c96445cd7
> 
>  
> Here's the update after our engineer further investigated: 
> 
> We were unable to get a hold of the inbound file and the outbound file because of the age of the data. With the information gathered, it seemed that these files were ready to be sent to MO, and not WA. The above IDs are report_id(s) and not message_id(s). If we can get the message_id(s), our next step is to find out if SimpleReport can resubmit them. It appears that these files might have likely been sent from SimpleReport. We can't ascertain the ordering facility until we have the message_id(s) to provide us with more information.
> 
> Thanks,
> Berni

**Comment by BerniXiongA6** [comment]
@oslynn and @BerniXiongA6 to chat about next steps now that WA DOH has replied with more info.

**Comment by BerniXiongA6** [comment]
Emailed from Jenni at WA DOH on 11/1/2022:
> Berni,
> 
>  
> 
> Performing Org and Ordering Fac for all is: SA.OTCSelfReport
> 
>  
> 
> We have received a few more of these since our initial report. Details are below:
> 
>  
> 
> DOH CASE_ID
> 
> INVESTIGATION_CREATE_DATE
> 
> PATIENT__IDENTIFIER__VALUE
> 
> ASSIGNING__AUTHORITY
> 
> MESSAGE__CONTROL___ID__MSH10
> 
> SUBMISSION__FILENAME
> 
> SUBMISSION__FILE__ID
> 
> 105749670
> 
> 2022-09-30 12:49:00.000
> 
> 3345568
> 
> SA.OTCSelfReport
> 
> db365053-28bd-4422-a032-1c381240c104
> 
> 7uycso49@cdcprime_testing_20220930191616_657313
> 
> 25559993
> 
> 105749674
> 
> 2022-09-30 12:52:00.000
> 
> 3345568
> 
> SA.OTCSelfReport
> 
> 53bd3c23-73ce-4b71-b650-945ef335a85f
> 
> 7uycso49@cdcprime_testing_20220930191616_657313
> 
> 25560072
> 
> 105749672
> 
> 2022-09-30 12:52:00.000
> 
> 3345568
> 
> SA.OTCSelfReport
> 
> 98f7a56f-e063-4577-938c-aaf9769a7c84
> 
> 7uycso49@cdcprime_testing_20220930191616_657313
> 
> 25560077
> 
> 105749755
> 
> 2022-09-30 13:20:00.000
> 
> 3345568
> 
> SA.OTCSelfReport
> 
> f68c5fab-8653-40c6-8b7a-785c96445cd7
> 
> 7uycso49@cdcprime_testing_20220930193507_595409
> 
> 25560413
> 
> 105749680
> 
> 2022-09-30 12:55:00.000
> 
> 3345568
> 
> SA.OTCSelfReport
> 
> 7afcf41d-a5c3-4dd5-b273-79e32cdfeec7
> 
> 7uycso49@cdcprime_testing_20220930191616_657313
> 
> 25560246
> 
> 105749680
> 
> 2022-10-09 10:49:00.000
> 
> 3345568
> 
> SA.OTCSelfReport
> 
> 8a0a7ad3-f3bc-4562-9a5a-fc65534b573a
> 
> 7uycso49@cdcprime_testing_20221009171613_841262
> 
> 25660573
> 
> 105749751
> 
> 2022-09-30 13:19:00.000
> 
> 3345568
> 
> SA.OTCSelfReport
> 
> 8f04c1dd-4552-4e73-acf4-61b702a9428e
> 
> 7uycso49@cdcprime_testing_20220930193507_595409
> 
> 25560401
> 
> 105749751
> 
> 2022-10-11 18:48:00.000
> 
> 3345568
> 
> SA.OTCSelfReport
> 
> 4dc21b7e-b0d2-4eda-a7ce-dbdc1e291318
> 
> 7uycso49@cdcprime_testing_20221012011603_533895
> 
> 25688081
> 
> 105749751
> 
> 2022-10-12 12:50:00.000
> 
> 3345568
> 
> SA.OTCSelfReport
> 
> 5cb34012-fde1-4d17-95e0-0b8edc86b818
> 
> 7uycso49@cdcprime_testing_20221012191616_780315
> 
> 25697329
> 
> 105749751
> 
> 2022-10-12 14:53:00.000
> 
> 3345568
> 
> SA.OTCSelfReport
> 
> 7f694e84-a39c-4646-b29c-e0848301f3fb
> 
> 7uycso49@cdcprime_testing_20221012211611_815843
> 
> 25698873
> 
>  
> 
> Thank you,
> 
> Jenni

**Comment by oslynn** [comment]
Message Ids only:

db365053-28bd-4422-a032-1c381240c104

53bd3c23-73ce-4b71-b650-945ef335a85f

98f7a56f-e063-4577-938c-aaf9769a7c84

f68c5fab-8653-40c6-8b7a-785c96445cd7

7afcf41d-a5c3-4dd5-b273-79e32cdfeec7

8a0a7ad3-f3bc-4562-9a5a-fc65534b573a

8f04c1dd-4552-4e73-acf4-61b702a9428e

4dc21b7e-b0d2-4eda-a7ce-dbdc1e291318

5cb34012-fde1-4d17-95e0-0b8edc86b818

7f694e84-a39c-4646-b29c-e0848301f3fb

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 will email Jenni, WA DOH to inform them that Ott is working on the ticket and has so far identified the sender is Intrivo. @oslynn is investigating further to determine what's causing the error "first/last unknown" and will provide next steps if needed to contact the sender to re-send if these are for actual patients.

**Comment by oslynn** [comment]
@BerniXiongA6 , I don't these messages are valid messages.  Or, they are testing messages.  The reason are:
Missing 
Patient Name: first/last are Unknow,  
Patient's Address 1: Unknow, 
Ordering Facility Phone Number: 1-111-111-1111
Performing Organization Name, Identifier Type Code: XX

I am not sure whether we should request Intrivo to resend them or not.

**Comment by oslynn** [comment]
@BerniXiongA6 , please email the following to Intrivo:

WA would like to know if these messages with the message ids below are testing messages or real production messages.

Message IDs
'------------
db365053-28bd-4422-a032-1c381240c104
53bd3c23-73ce-4b71-b650-945ef335a85f
98f7a56f-e063-4577-938c-aaf9769a7c84
f68c5fab-8653-40c6-8b7a-785c96445cd7
7afcf41d-a5c3-4dd5-b273-79e32cdfeec7
8a0a7ad3-f3bc-4562-9a5a-fc65534b573a
8f04c1dd-4552-4e73-acf4-61b702a9428e
4dc21b7e-b0d2-4eda-a7ce-dbdc1e291318
5cb34012-fde1-4d17-95e0-0b8edc86b818
7f694e84-a39c-4646-b29c-e0848301f3fb

They cause issues due to the following:
'------------------------------------------
PID-5-1: Patient First Name: Unknown,
PID-5-2: Patient Last Name: Unknown,
PID-11-1: Patient's Address 1: Unknown,
ORC-23: Ordering Facility Phone Number: 1-111-111-1111
OBX-23-7: Performing Organization Name, Identifier Type Code: XX

**Comment by BerniXiongA6** [comment]
BX sent this email to Karim / Intrivo on 11/3/2022:

> Hi Karim,
> 
> On September 30, 2022, there were a number of messages that were sent to WA Dept. of Health that had data issues. WA would like to know if these messages with the message ids below are testing messages or real production messages.
> Message IDs
> '------------
> db36505-28bd-4422-a032-1c381240c104
> 53bd3c2-73ce-4b71-b650-945ef335a85f
> 98f7a56-e063-4577-938c-aaf9769a7c84
> f68c5fa-8653-40c6-8b7a-785c96445cd7
> 7afcf41-a5c3-4dd5-b273-79e32cdfeec7
> 8a0a7ad-f3bc-4562-9a5a-fc65534b573a
> 8f04c1d-4552-4e73-acf4-61b702a9428e
> 4dc21b7-b0d2-4eda-a7ce-dbdc1e291318
> 5cb3401-fde1-4d17-95e0-0b8edc86b818
> 7f694e8-a39c-4646-b29c-e0848301f3fb
> They cause issues due to the following:
> '------------------------------------------
> PID-5-1: Patient First Name: Unknown,
> PID-5-2: Patient Last Name: Unknown,
> PID-11-1: Patient's Address 1: Unknown,
> ORC-23: Ordering Facility Phone Number: 1-111-111-1111
> OBX-23-7: Performing Organization Name, Identifier Type Code: XX
> 
> We recommend that these messages get resubmitted with correct values if indeed these are real production data. If these were only for testing, then there's no need to resubmit; however, if you could confirm either way, we'd like to inform WA of the next steps.
> 
> Thanks,
> Berni

**Comment by BerniXiongA6** [comment]
BX sent this email to Karim on 11/23/2022:

> Hi Karim,
> 
> Thanks for your reply. I followed up with WA Dept of Health and they have indicated that anonymous reporting does not meet the requirements of public health notifiable conditions reporting for the state of WA. 
> 
> Additionally, they have since found four more MSH-10’s with first/last unknown (see below):
>  
> 40d90f47-9867-49b8-b862-be1b89933e68
> f3024231-fae6-44d5-9a45-b06eeedc8f7b
> a47b55f8-6681-44ab-86e3-ac3daa25275d
> 28758d5c-e38b-4c2e-bde5-e144f029c874
>  
> We recommend that these messages get resubmitted with correct values if indeed these are real production data. 
> 
> Please have yourselves a great Thanksgiving.
> 
> Thanks so much,
> Berni

**Comment by brandonnava** [comment]
@BerniXiongA6 Ask WA if they want us to filter out unknown name data. 
@brandonnava Make ticket about how we as RS want to filter blank name data and/or report to HHS. Also discussion to be had about OTC data.

**Comment by BerniXiongA6** [comment]
Sorry a little bit late to pasting the comment here. Last update from Andrew W./RADx Mars on 11/28/2022:

> We’ve heard that most states do not want to accept anonymous messages.  Because of this, APHL only routes messages to states if they contain at least the Last Name and DOB.  I suggest that ReportStream does the same.
> 
>  
> 
> We are working with CDC to survey the states regarding their preferences for receiving OTC data, including whether they will accept anonymous messages.  We expect to have the survey results some time in January.

**Comment by BerniXiongA6** [comment]
BX replied to Jenni and Julie on 12/29/2022:

> Hi Jenni and Julie,
> 
> Sorry for the late update on this one (ticket # 6907). Per Andrew Weitz (NIH/NBIB) from the RADx Mars team, they are working with CDC to survey states regarding their preferences for receiving OTC data. This includes whether states will accept anonymous message. The survey results should be coming some time in January 2023. 
> 
> In the meantime, Andrew suggests that ReportStream considers routing messages to states if they at least contain Last Name and DOB. I'll make sure to have our team discuss this before the next sync, as our engineers are closer to the schema requirements and quality filters than I am.
> 
> Thanks,
> Berni

**Comment by BerniXiongA6** [comment]
Update on 1/3/2023: no resolution for sender data -- but keeping this ticket open for WA sync (until we hear about survey results on STLT otc data receiving preferences/which includes anonymous reporting). @brandonnava @brick-green this can be your update for WA sync

**Comment by TaneaY** [comment]
![WA requirements.png](https://images.zenhubusercontent.com/628286bc0129e14bd536e6f9/5c21bbb6-360b-4ec6-885d-f852c66ba284)

Hi Berni-

WA ELR program requests notifiable conditions laboratory reporting submitted as ELR be sent per the implementation guide specifications of the national standard ELR HL7 2.5.1 rel 1 format.  For WA state, contents of notifiable conditions laboratory reporting are specified in Washington Administrative Code (WAC) https://app.leg.wa.gov/WAC/default.aspx?cite=246-101-225.  Submitters sending less than these WAC required data elements are out of compliance with the regulations

However, from a purely functional standpoint of our ELR and surveillance systems (i.e., no errors and no added manual work) and a practical view of data being usable for public health action, the minimum person-related data for a lab report are: **First name, Last name, DOB, City and State with all those fields not only not null, but also meaningfully completed (i.e., not filled with “Unknown”, etc.)  These 5 elements are needed in the ReportSteam routing filter for WA.**

I appreciate your ongoing work to improve the quality of ReportSteam COVID testing data to support public health.

Thanks,

Julie

**Comment by brick-green** [comment]
@TaneaY @sliu1000 @brandonnava I just updated the quality filter for WA. It will now filter out all results where First name, Last name, City, or State equals one of the following: Unknown, unknown, UNKNOWN. Can an email be sent to WA letting them know?

**Comment by brandonnava** [comment]
Email sent out so WA is informed
