### ISSUE TITLE
SonarCloud not scanning prime-router

### ISSUE THREAD

**Issue by snesm** [CDCgov/prime-reportstream#6910]
## Problem statement

SonarCloud seems to be stopped scanning /prime-router code.

## What you need to know

- [SonarCloud scan statistics](https://sonarcloud.io/code?id=CDCgov_prime-data-hub)

## Acceptance criteria

- SonarCloud statistics show results for /prime-router code
- SonarCloud shows correct statistics for /frontend-react and /prime-router

## To do

- [ ] ...

**Comment by snesm** [comment]
Also: sonarcloud checks are not part of the build-backend custom action.

**Comment by jeremy-page** [comment]
Possible dup with #57
Here is how they fixed this in TI: https://github.com/CDCgov/trusted-intermediary/pull/126/files

**Comment by snesm** [comment]
Probably deleted in https://github.com/CDCgov/prime-reportstream/pull/6372
which deleted .github/workflows/run_sonarcloud_scan.yaml.  Line 38 called out both frontend-react and prime-router.

**Comment by jeremy-page** [comment]
Dupe of 57

**Comment by snesm** [comment]
https://github.com/CDCgov/prime-reportstream/pull/9538
https://github.com/CDCgov/prime-reportstream/pull/9539
https://github.com/CDCgov/prime-reportstream/pull/9542

**Comment by snesm** [comment]
SonarCloud appears to be stable and is not overwriting any portion of the statistics.

https://github.com/CDCgov/prime-reportstream/pull/9574
https://github.com/CDCgov/prime-reportstream/pull/9672
https://github.com/CDCgov/prime-reportstream/pull/9691
https://github.com/CDCgov/prime-reportstream/pull/9714
https://github.com/CDCgov/prime-reportstream/pull/9719
https://github.com/CDCgov/prime-reportstream/pull/9724
https://github.com/CDCgov/prime-reportstream/pull/9728
https://github.com/CDCgov/prime-reportstream/pull/9798
https://github.com/CDCgov/prime-reportstream/pull/9946
https://github.com/CDCgov/prime-reportstream/pull/9972
