### ISSUE TITLE
Backward compatibility test for Daily Data - Full ELR 

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6913]
## Problem statement

With the Hospital Corporation of America getting ready to send full ELR data to Colorado via ReportStream API, the user needs to continue seeing the delivered data history (Daily Data) with no issues.
The purpose of this ticket is to test the full ELR daily data history and document any issues that need to be fixed.

## What you need to know
- Work is in progress for pipeline and is expected to be ready for testing by week of Oct 17th
 
## Acceptance criteria
The following outcome is desired:
- [x] On sending data for multiple diseases via the full ELR endpoint, and delivering that data to Colorado PHD, Daily Data UI for CO PHD shows details for all the records delivered in the dataset correctly.
- [x] There is no reference to COVID 19 on the Daily Data UI

The following is documented:
- [x] If there are COVID 19 references, they are documented as an output of this ticket
- [x] Any work required to fix issues found is captured in tickets for future work

## To do

- [x] Submit a test file for multiple reportable diseases on Staging via the new full ELR API endpoint and delivered to CO PHD
- [x] Confirm that all the test results are accounted for in the Daily Data UI

**Comment by RakshindaAslam** [comment]
@doug-s-nava @HeatherRienks - needs pre-refinement. Not ready to be pulled in before Oct 17th.

**Comment by RakshindaAslam** [comment]
cc @HeatherRienks - Need to check with @carlosfelix2 @clediggins-usds when this feature is in staging for testing.

**Comment by kevinhaube** [comment]
Set to deploy Thursday 10/27!
