### ISSUE TITLE
Publish What's New - Oct 2022 Update

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6919]
## Problem statement
As a user, I would like to know what features, bugs, other user facing updates have been made to ReportStream product.

## What you need to know
- This document will be updated by POs and DMs with new changes. This will need to be reviewed/revised by the Experience Design team and published on the reportstream.gov website at the end of each month.  
https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B46d04c32-4db8-4d1d-941a-e5fdbf76df09%7D&action=edit&wdPreviousSession=ed1dd437-d3a3-431e-84d2-8ebb8c0c67ff&cid=accaa3e4-0b9c-416b-b410-de8a175033d1

## Acceptance criteria

- [ ] The monthly updates as described in the linked document is reviewed and published  on the reportstream.gov website by end of first week of every month.

## To do

- All teams will begin using the label “release_notes” in ZH, (starting now) for any customer-facing tickets. Scrum masters and Product Owners will be responsible for working with their teams to ensure we are all using this label, as well as the “bug” and “feature” labels (helps us to easily identify work we want to share on the “Release Notes/What’s New” page.
- Scrum masters and PO’s will compile all pertinent updates in this doc in the appropriate sections (New Features, Fixed Issues, Improvements, or Additional Resources).
- Every month, the Experience Team will be responsible for publishing updated content on the “Release Notes/What’s New” RS website.

**Comment by HeatherRienks** [comment]
FYI @fmccaf1

**Comment by HeatherRienks** [comment]
@RakshindaAslam - what was the date that we would like to plan to launch the notes?

@fmccaf1 @a-chappelear

**Comment by HeatherRienks** [comment]
FYI - we will plan to launch around 11/4/22 (end of the first week of the month, as noted above).

**Comment by kevinhaube** [comment]
In staging, ready to deploy November 3
