### ISSUE TITLE
Universal pipeline sets HL7 processing mode to T for receivers masked with status testing

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#6949]
### User Story:
As a receiver, I want HL7 data to be marked with processing mode T (test) if my customer status is set to Testing, so my data is flagged correctly.

### Description/Use Case
This feature is similar to the existing COVID pipeline.  If the customer status is set to testing then the processing mode in the HL7 data must be set to T.  Also, if the processingModeCode property for the receiver is set to a valid HL7 value then it should be set to that.  By default it should be P.

### Dev Notes:
* The HAPI library should be able to verify the value I think.  Try not to hard code the values.

### Acceptance Criteria
* The Universal Pipeline sends HL7 data to a STLT with a processing mode of T if the receiver is configured with a customer status of testing.
* The Universal Pipeline sends HL7 data to a STLT with a specified processingModeCode from the receiver settings as the HL7 processing mode if the processingModeCode is a valid mode.

**Comment by clediggins-usds** [comment]
Processing Mode code 'T' in HL7 does not mean Testing. There is no 'testing' in the processing mode value set: https://hl7-definition.caristix.com/v2/HL7v2.5.1/Tables/0207

**Comment by clediggins-usds** [comment]
We are actually talking about Processing Id, not Processing Mode. MSH.11 https://hl7-definition.caristix.com/v2/HL7v2.8/Tables/0103
