### ISSUE TITLE
Retrieve reporting facilities from API

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#6950]
## Problem statement

To serve the facility-centric data display feature outlined in #7005, the API needs an extension of functionality to account for retrieving a list of Facilities who have reported tests that got routed to the STLT in various Reports

## Resources & info

Blocking React implementation: #7651 
The above ticket includes mockups showing the intended use of this endpoint.

An ideal response might look like
```
{
    orderedBy: "My Facility",
    ordererId: 123,
    mostRecentContribution: 2022-03-15 17:30.000z,
    mostRecentReportId: "abcd-1234-efgh-5678"
    performedBy: "Performer Facility",
    performerId: abc,
    submittedBy: "Submitting Facility",
    submitterId: abc123,
}
```

## Acceptance criteria

- [ ] Endpoint response of sorted A-Z on Ordering Provider **by default**
- [ ] Database query can be sorted by Ordering Provider, Performing Facility, Submitter, and Most Recent Report Date
- [ ] Database query supports numbered pagination

**Comment by jimduff-usds** [comment]
What's the difference between this ticket and #6846?

**Comment by kevinhaube** [comment]
@jimduff-usds This one is newer, and I think better-written. But yes, the other ticket was part of that batch that got made with little solid requirements. This one is rooted in designs and front-end work, so there's lot more information. Link to that ticket should be in the description.

**Comment by chris-kuryak** [comment]
Closing as we are currently redesigning the STLT dashboard MVP. This work will be re-ticketed if needed.
