### ISSUE TITLE
HHS Protect Data Issue - Blanks for MSH-3.1 and MSH-3.2

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6954]
## Problem statement

NIH user Krishna, found some data quality issues in HHS Protect from ReportStream Data.

For all test results coming from Intrivo, the MSH-3 segments are being left blank:
MSH-3.1 (Sending system namespace)
MSH-3.2 (Sending system OID)
The MARS specifications requires that these be populated.

## What you need to know

I reviewed 1 Intrivo HL7 file dated 10/6/2022 and it looks like there's data in those fields.

MSH
^~\&
Intrivo^2.16.840.1.113434.6.2.2.1.1.2^ISO
Intrivo^2.16.840.1.113434.6.2.10411^CLIA
CDC PRIME^2.16.840.1.114222.4.1.237821^ISO
CDC PRIME^2.16.840.1.114222.4.1.237821^ISO
20221006165232+0000

ORU^R01^ORU_R01
`b8c4a9ff-53fe-4746-8602-03092cc3dbbf`
P
2.5.1

NE
NE
USA
UNICODE UTF-8

PHLabReport-NoAck^ELR251R1_Rcvr_Prof^2.16.840.1.113883.9.11^ISO

## Acceptance criteria

- Confirm whether the MSH-3.1 and MSH-3.2 fields are blank on ReportStream side.
-Figure out a way to send that over to HHS Protect with no blanks

## To do

- [ ] ...

**Comment by sliu1000** [comment]
Update:

Reportstream sends csv file to HHS Protect (per their request) instead of HL7 file. Andrew from NIH thinks we should start sending our HL7 file to Palantir instead of the CSV files. TBD

**Comment by sliu1000** [comment]
Update:

Adding and removing some recipients due to staffing changes.
Andrew - we'll look at calendars and get back with you.

Thanks,

Joel Biskie (Flexion, Inc.)
Integration Engineer
Pandemic-Ready Interoperability Modernization Effort (PRIME)
From: Weitz, Andrew (NIH/NIBIB) [E] <andrew.weitz@nih.gov>
Sent: Thursday, October 13, 2022 9:07 AM
To: Report Stream (CDC) <reportstream@cdc.gov>; Beckett, Alicia (CDC/OD/OCS) <qom2@cdc.gov>; Hawes, Richard (CDC/OD/OCS) <qom6@cdc.gov>; Thomas, Kevin (CDC/OD/OCS) <qqf6@cdc.gov>; Biskie, Joel (CDC/DDPHSS/OD/HITSSU) (CTR) <rtz3@cdc.gov>; Brewster, Adrian (CDC/DDPHSS/OD/HITSSU) (CTR) <mpz9@cdc.gov>
Cc: Juluru, Krishna (NIH/NIBIB) [E] <krishna.juluru@nih.gov>
Subject: RE: [External] Intrivo Diagnostics ready to onboard fully - ReportStream - 5/9/2022
 
ReportStream team –

 
There are ongoing issues with getting MARS-compliant data from Intrivo into HHS Protect (details in the attached email).  There appear to be two causes for this:

Intrivo not fully complying with the MARS spec.  This is something we expected ReportStream to catch during the onboarding QA/QC phase, but it looks like some issues slipped through the cracks.

ReportStream sending CSV files to Protect.  MARS HL7v2 files were designed to be natively compatible with state/federal health systems.  It’s not clear why ReportStream is converting HL7v2 to CSV prior to transmission, as this is most certainly resulting in an information loss.
 
Can we set up a call to discuss these issues and a path forward?  Some options:

                Fri: 12:30-2, 3:30-5:30 ET
                Mon: 11-12, 1-2, 3-4:30 ET

Thanks,
Andrew

**Comment by sliu1000** [comment]
@jbiskie 

Hi Joel were you able to review the Intrivo file and provide feedback to Karim?

Please see below their correspondence:
ReportStream team – Can you please follow up with Karim asap, as we discussed on Monday?

 

Karim, apologies that I can’t help you directly.  ReportStream needs to verify the sample messages that you provided.

 

Thanks,

Andrew

**Comment by sliu1000** [comment]
@jbiskie 

Update from Intrivo:

Hi Joel,

Sex, Race, and Ethnicity are all optional values that the users have the ability to set on their profiles. None of our users provide that, however.

Regarding County, we don't have a UI to collect that on our app.
I wasn't aware of this issue being raised during our app walkthroughs, however, I'll discuss it with our product team.
Where available, we send all the other address fields that the user might have provided at the time of providing consent to share their data.

Best regards,
Karim Lalani | Engineering Lead

**Comment by sliu1000** [comment]
Update, question from NIH Team:

Thank you, Kevin, for the fwd. 

Joel, 

Do you know the answer to the below question from Andrew?
Question for the ReportStream team: We know you are replacing PII fields with a <deidentified> string.  Can you let us know the date that you began using the <deidentified> string, instead of blanking out the values?
Best regards,

Sharon

From: Weitz, Andrew (NIH/NIBIB) [E] <andrew.weitz@nih.gov>
Sent: Tuesday, October 25, 2022 2:00 PM
To: Thomas, Kevin (CDC/OD/OCS) <qqf6@cdc.gov>; Reeves, Maurice (CDC/OD/OCS) <qva8@cdc.gov>; Hawes, Richard (CDC/OD/OCS) <qom6@cdc.gov>; Beckett, Alicia (CDC/OD/OCS) <qom2@cdc.gov>
Cc: Juluru, Krishna (NIH/NIBIB) [E] <krishna.juluru@nih.gov>; Report Stream (CDC) <reportstream@cdc.gov>
Subject: RE: Zip code handling
 
Thanks for following up, Kevin.  I have not received an answer yet

From: Thomas, Kevin (CDC/OD/OCS) <qqf6@cdc.gov>
Sent: Tuesday, October 25, 2022 1:04 PM
To: Weitz, Andrew (NIH/NIBIB) [E] <andrew.weitz@nih.gov>; Reeves, Maurice (CDC/OD/OCS) <qva8@cdc.gov>; Hawes, Richard (CDC/OD/OCS) <qom6@cdc.gov>; Beckett, Alicia (CDC/OD/OCS) <qom2@cdc.gov>
Cc: Juluru, Krishna (NIH/NIBIB) [E] <krishna.juluru@nih.gov>; Report Stream (CDC) <reportstream@cdc.gov>
Subject: Re: Zip code handling

removing a few folks and adding support inbox. did we get this question answered?

From: Weitz, Andrew (NIH/NIBIB) [E] <andrew.weitz@nih.gov>
Sent: Thursday, October 20, 2022 11:53 AM
To: Reeves, Maurice (CDC/OD/OCS) <qva8@cdc.gov>; Thomas, Kevin (CDC/OD/OCS) <qqf6@cdc.gov>; Hawes, Richard (CDC/OD/OCS) <qom6@cdc.gov>; Beckett, Alicia (CDC/OD/OCS) <qom2@cdc.gov>; Kumar, Anshul (CDC/OD/OCS) <rdz8@cdc.gov>
Cc: Juluru, Krishna (NIH/NIBIB) [E] <krishna.juluru@nih.gov>; Brewster, Adrian (CDC/DDPHSS/OD/HITSSU) (CTR) <mpz9@cdc.gov>; White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>
Subject: RE: Zip code handling

Hi Maurice and team,

We’re working with Palantir to perform QA/QC on the OTC data being sent to HHS Protect from ReportStream and APHL.

Question for the ReportStream team: We know you are replacing PII fields with a <deidentified> string.  Can you let us know the date that you began using the <deidentified> string, instead of blanking out the values?

Thanks,

Andrew

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 will follow up with @kjt9cc on this (CSV to HL7 / HHS Protect file format)

**Comment by sliu1000** [comment]
Update:

Andrew from RADX Mars mentioned that he will reach out to Intrivo and let him know they would like to keep those fields optional.
