### ISSUE TITLE
Vault Onboarding – Validate Receiver  

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#6958]
### Acceptance Criteria 
- [ ] Contacted receiver to ask them to validate sample production data (real data) from sender  
- [ ] Contacted sender to inform which state we’ll be working with (need sample production data for that state)  
- [ ] Data received from sender for the selected state  
     - [ ] RS engineer accessed Azure “receive” folder in production to pull out reports from sender  
     - [ ] Ensured local receiver configuration for the state matches production  
          - [ ] Except the SFTP settings need to point to local  
     - [ ] RS engineer submitted reports to the local pipeline  
     - [ ] Engineer deliver processed reports to the state by whatever means they specify (email, SFTP, etc.)  
     - [ ] Contacted the state to inform them file is ready for validation  
     - [ ] Received confirmation from state that file is validated (clear to go Live after this step) 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with sender and receiver 
- [ ] RS team member who originates this ticket: add dependencies:  
     - [ ] [name of company] Onboarding – Create Org and Sender Settings 
     - [ ] [name of company] Onboarding - Validate Test Files 
     - [ ] [name of company] Onboarding – Testing in Staging and Prod 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Sender" 
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by sliu1000** [comment]
Update from Sender Tara from Vault:

Hi James,

No, the response received was:

{

  "statusCode": 200,

  "headers": {

    "server": "nginx",

    "content-type": "text/plain; charset=UTF-8",

    "transfer-encoding": "chunked",

    "connection": "close",

    "vary": "Accept-Encoding",

    "x-request-id": "da77d715-8adb-4de8-8c95-12f822eb27a4",

    "x-token-id": "c2c62d55-c7a5-44db-aa99-061cd8efbf4a",

    "cache-control": "no-cache, private",

    "date": "Wed, 09 Nov 2022 23:36:02 GMT"

  },

  "body": ""

}

 

 

-- 

Tara Brocke
