### ISSUE TITLE
SimpleReport CSV Uploader - missing Equipment UID and Equipment Type in ~367 records

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#6964]
[https://app.zenhub.com/files/304423150/83f151e7-b748-46fb-b62c-de1a8c05c1e9/download](https://app.zenhub.com/files/304423150/83f151e7-b748-46fb-b62c-de1a8c05c1e9/download[https://app.zenhub.com/files/304423150/8c3f806f-c3a6-49be-8244-44bef68e53ac/download](https://app.zenhub.com/files/304423150/8c3f806f-c3a6-49be-8244-44bef68e53ac/download))

Sharada Kawal from Optum sent a request for us to resubmit about 367 records.  However, we need to check to see why OBX 18.1 (Equipment UID) and OBX 18.4 (Equipment Type) data is missing.  As it was submitted via SimpleReport CSV uploader.

Email from Sharada Kawai - OPTUM
**Hi SimpleReport,

The issue was not corrected. Can you review the accessions and let me know what you find? There are 367 NACK (negative acknowledged records) across 330 distinct accessions from 7/18 and 9/20 for MyCareLabs, due to the error reasons below still pending correcting and resubmission.

 
 Summary of Missing Data:

18-Jul - 152 records effected with missing data from fields OBX 18.1 and OBX 1.4

1. Required component missing in segment - OBX 18.1 -  Equipment Instance Identifier.Entity Identifier
2. Required component missing in segment - OBX 18.4 - Equipment Instance Identifier.Universal Id Type

20-Sep -215 records effected with missing data from the below

1. Required component missing in segment - OBX 18.1 -  Equipment Instance Identifier.Entity Identifier
2. Required component missing in segment - OBX 18.4 - Equipment Instance Identifier.Universal Id Type

Grand Total

367

**

**Comment by brandonnava** [comment]
@sliu1000 Is this a SimpleReport issue their team needs to fix or is it the RS side that is having issues?

**Comment by sliu1000** [comment]
@brandonnava - Let me get back to you on this. I need to look into this.

**Comment by sliu1000** [comment]
@brandonnava 

After looking into this, I see why this was sent to RS Zenhub.  The below OBX 18.1 is not listed in our HL7 file format.  Is this mapped as something else in our HL7 file?

Required component missing in segment - OBX 18.1 - Equipment Instance Identifier.Entity Identifier
Required component missing in segment - OBX 18.4 - Equipment Instance Identifier.Universal Id Type

**Comment by brandonnava** [comment]
@GilmoreA6 Any ideas on this one?

**Comment by GilmoreA6** [comment]
@brandonnava We've seen this before, as an issue with the way the LIVD table gets certain values when there are duplicates. The SR schema only specifies two fields which when not unique can cause problems for our logic. Unfortunately, given the dates in the ticket we no longer have any of these messages stored so we would have to ask the submitter to re-send them.

**Comment by brandonnava** [comment]
@sliu1000 Per James' insight can you ask them to resend?

**Comment by brick-green** [comment]
@GilmoreA6 Will resending work here? Won't the same thing happen with equipment UID?

If not, I'm happy to work with SR to send the extra fields

**Comment by sliu1000** [comment]
Can I close this out or is there something that the sender needs to resend?

**Comment by LaFreda1** [comment]
Hi @jayna-SkylightDigital we are blocked on this ticket due to the SR schema. Would SR like to work with us to add the extra fields?
