### ISSUE TITLE
CO - Filter Results based on test type and result

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#6981]
## Problem statement

Memo/Notice sent from CDPHE - Colorado Department of Public Health and Environment dated 7/15/2022.

Effective Immediately:  

- CDPHE will no longer require reporting of negative rapid and antigen SARS-CoV-2 negative test results.

- However, Positive and Negative nucleic acid amplification/molecular SARS-CoV-2 tests continue to be reportable to CDPHE

## What you need to know

See attached Memo

[https://app.zenhub.com/files/304423150/857118d0-8efe-497c-819b-3cf8f8840257/download]

## Acceptance criteria

- Please review what other states requested for changes such as IL and OH after similar reporting changes were adopted recently.

## To do

-Please review other states that recently made the similar changes (IL, OH).

**Comment by brick-green** [comment]
@oslynn Can this epic be closed?

**Comment by oslynn** [comment]
It is done.
