### ISSUE TITLE
Message Tracker - Single Result - MVP

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6992]
## Problem statement

As an internal admin, I would like the ability to search for multiple msgIDs to understand what happened to it and why it did not make it to the expected state
The purpose of this is to help with addressing support tickets.

**Additional context**
The main use case for this feature is as a troubleshooting tool if a STLT reaches out about an error or problem. O&O engineers can use the message ID search to find the message in question, see the errors associated with it, and triage accordingly.

## What you need to know
- Creating this epic for organizing the tickets on the board

Mural with initiative break-down https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1660849046968/e257020850ab71f57b31120e27ec06203ae9c22b?sender=u3fea607b46e84058d3224917

Wireframe for the ongoing work on this feature
https://www.figma.com/file/fKl2M96ylkxYezwjVVUSIX/Internal-Admin-%26-Tools?node-id=411%3A1069

## Acceptance criteria

Internal admin user is able to search for multiple  test results to get information about
- success in being delivered or the reason why it was not delivered
- all associated dates, facility, organization, report ID and other related data
- confirm with O+O engineers to move forward with design (added by Chris 12/22)

## To do

- Design Wireframes, flow and IA
- Scope out requirements from O&O for display and export of data

**Comment by chris-kuryak** [comment]
The redesign of the Message Tracker feature has launched. Closing epic.
