### ISSUE TITLE
Message Tracker - External Authenticated Service

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#7001]
## Problem statement

As an external authenticated user sender or receiver, I would like the ability to search for one or multiple msgIDs to understand what happened to it and why it did not make it to the expected state
The purpose of this is to help users to self-serve with troubleshooting errors with message delivery via ReportStream.

## What you need to know

Mural with initiative break-down https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1660849046968/e257020850ab71f57b31120e27ec06203ae9c22b?sender=u3fea607b46e84058d3224917

Wireframe for the ongoing work on this feature
https://www.figma.com/file/fKl2M96ylkxYezwjVVUSIX/Internal-Admin-%26-Tools?node-id=411%3A1069

## Acceptance criteria

External authenticated user is able to search for multiple  test results to get information about
- success in being delivered or the reason why it was not delivered
- all associated dates, facility, organization, report ID and other related data

## To do

- Research if this feature should be built and with what scope.
- Design Wireframes, flow and IA
- Scope out requirements from O&O for display and export of data

**Comment by RakshindaAslam** [comment]
cc @HeatherRienks

**Comment by kevinhaube** [comment]
With ongoing STLT feature improvements, we should reassess how this functionality can fit into the wonderful features in design right now, such as the Facility features for STLTs! @chris-kuryak @CnoteNava @HeatherRienks

**Comment by chris-kuryak** [comment]
Per conversation with O+O engineers (James and Ott and Tom G), making the message tracker feature available to Senders and Receivers (not just RS admins) is not needed at this time and should be rescoped in the future if/when it is needed.
cc: @HeatherRienks @stephenkao
