### ISSUE TITLE
Upgrade NodeJs version from 12 to 16 in juliangruber/sleep-action

### ISSUE THREAD

**Issue by lucasdze** [CDCgov/prime-reportstream#7003]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: juliangruber/sleep-action

**Comment by snesm** [comment]
or maybe

```
run: |
    echo "sleeping 30"
    sleep 30
    echo "wake up"
```
