### ISSUE TITLE
Upgrade NodeJs version from 12 to 16 in jwalton/gh-docker-logs action

### ISSUE THREAD

**Issue by lucasdze** [CDCgov/prime-reportstream#7004]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16:  jwalton/gh-docker-logs

**Comment by lucasdze** [comment]
Resolved with PR https://github.com/CDCgov/prime-reportstream/pull/7006

**Comment by snesm** [comment]
https://github.com/CDCgov/prime-reportstream/pull/7006 approved/merged.
