### ISSUE TITLE
Retrieve demographic info for Facility

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7008]
## Problem statement

To display info about a reporting facility on the front-end, we need to store and supply facility data from submission rows to the STLTs who received their messages.

## Resources & info

Related React work is blocked: #7652, #7655
The above tickets include mockups that show the intended implementation

## Acceptance criteria

- [ ] Endpoint returns indication of which type of Facility this is: ordering, performing, or submitting
- [ ] Endpoint returns the name and contact info for a Facility
- [ ] Endpoint returns date of first report contribution, all-time total test count, and average test count per report

**Ordering only**
- [ ] Endpoint returns NPI

**Performing only**
- [ ] Endpoint returns the performing facility's designated Submitter(s)

**Comment by chris-kuryak** [comment]
Closing as we are currently redesigning the STLT dashboard MVP. This work will be re-ticketed if needed.
