### ISSUE TITLE
API timeout during deployment

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7032]
**Describe the bug**
When deploying our ReportStream application, after the container swap occurs, there's an indefinite period of time (10-30 mins) where the front-end site will timeout after 3 minutes waiting for an API response from **only some** endpoints.

**Impact**
Endpoints with this affect, observed 10/18 and 10/20:
- Submission History (cleared after 10ish minutes)
- Data result size directly affects whether it times out or not: Submissions call with no data returned took just over 2 minutes, Submissions call with data timed out
- Organizations endpoint seems fine
- Daily Data is slow, but did not time out
- No Admin APIs timed out

**Expected behavior**
After a slot swap, there should be no downtime on the front-end website when calling the API.

**Screenshots**
![Screen Shot 2022-10-18 at 2.40.20 PM.png](https://images.zenhubusercontent.com/611a907ec3e013d0e33e58a7/0b870403-9ae4-4da1-87b2-7da3a3a65ab1)

![Screen Shot 2022-10-18 at 2.40.39 PM.png](https://images.zenhubusercontent.com/611a907ec3e013d0e33e58a7/b30869da-bfa4-403a-8be4-acc618cd5b6a)
**Logs**
TBD

**Additional context**
- Problem seems to occur on heavier loads **BUT** all endpoints are slower after deployment
- Previously observed on `Submission History` list endpoint

**Comment by kevinhaube** [comment]
I will be on Experience deployment duty this week: I will observe what endpoints I can trigger the bug on and list them in this ticket's description.

**Comment by HeatherRienks** [comment]
FYI @GilmoreA6 :)

**Comment by kevinhaube** [comment]
@jeremy-page @jimduff-usds After observing this last week and paying extra special attention to emerging patterns, my hypothesis is that the container may be under a heavy load at start-up, and paired with the slow performance of the Submission History endpoint, it creates these timeouts. In one instance I was able to query an empty submission history array, but then it timed out on a response that would've had data.

The impact for a theoretical user (not sure how many use the Submission History page) is about 5-10 minutes of downtime every Tuesday/Thursday at 1:30-ish ET. On a rare occasion it's been up to 30 mins.

**Comment by kevinhaube** [comment]
@jimduff-usds Yes, this is the query as it goes out from our front-end call in prod:

`https://prime.cdc.gov/api/waters/org/simple_report/submissions?pagesize=61&cursor=3000-01-01T00:00:00.000Z&endcursor=2000-01-01T00:00:00.000Z&sort=DESC&showfailed=false`

**Comment by kevinhaube** [comment]
Issue removed from Experience board since discovery of impact is done. I'll remain subscribed to track progress!
