### ISSUE TITLE
CA DOH - Zuckerberg SF General SimpleReport submissions

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#7034]
Email from Bonnie: 10/6 6:38pm

Hi Zuckerberg staff

 

We have received laboratory result messages sent to SimpleReport from your facility which have encountered errors during transmission. This error has happened due to your facility name exceeding the maximum acceptable length of 35 characters.

 

To correct this you will need to:

Suspend reporting.
Shorten your facility name to 35 characters, spaces included, or less.
Resubmit all results from 9-8-21 to current
 

If you have any questions about this process, please let us know and we will do all we can to assist you.

Warmly

 
Bonnie Brandt

Email from Shannon: 10/14 7:36pm

Hi SimpleReport,

See the message below from the California Dept of Public Health.  There were errors in the transmission of our SimpleReport tests to them due to the facility name length.  I have changed our facility name in Simple Report, but do not see how to re-transmit all of our results.  Any assistance is appreciated.

Kind regards,

Email from Shannon: 10/17 10:50am

Thank you for the response.  The error is not in the resulting. All of the entered results are correct.  

The issue is with the transmission of the results to the California Department of Health.  This transmission from SimpleReport to them is mandated by the CDC and the State of California.  

The transmission of the results did not complete due to the character length of the facility name.  

Please retransmit all of our results to the California Department of Health, now that our facility name is changed. 

Thank you!

User is requesting a resubmission to the CA DPH of results back to 9/21.

**Comment by sliu1000** [comment]
Hi Ott,

Can you please check in Reportstream if the Facility Names was updated:

New Facility Name:  SF DPH ZSFG
Old Facility Name:  Zuckerberg San Francisco General

**Comment by oslynn** [comment]
@sliu1000 do you have message id for me to check?

**Comment by sliu1000** [comment]
@oslynn 

The ReportID: `Covid-19-4d92224f-5134-4a1a-b8c6-c6c73c8a9f69-20220930210926.csv`

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 and @oslynn to follow up on and make sure ticket is updated with comments/work done.

**Comment by sliu1000** [comment]
Update: Emailed SimpleReport to make sure the backlog was resubmitted.

**Comment by oslynn** [comment]
2022-10-28: Can't find the message in the Azure storage.

**Comment by sliu1000** [comment]
@oslynn 

Hi Laura and Emma,

Could you please resubmit the back log with the short name? Calredie is requesting for the names to be shorten on all their old data so that it will become available in their system.  Please let me know if you have any questions.

Best regards,

Sharon

**Comment by sliu1000** [comment]
Email Sent on Friday 11/4/2022 @ 6:56 pm

Just a heads up that this request has been completed - all the tests for Zuckerberg Hospital have been re-sent to ReportStream.

Thanks,
Emma

**Comment by sliu1000** [comment]
@oslynn 

Emma updated the Facility name from Zuckerberg Hospital to SF DPH ZSFG on Friday. Can you please confirm.

**Comment by BerniXiongA6** [comment]
@sliu1000 @oslynn -- can this be closed?
