### ISSUE TITLE
Delivery details contains information about data delivered by the Universal Pipeline

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#7055]
### User Story:
As a receiver, I want to see the list of deliveries include those made by the UP, so I can track my data.

### Description/Use Case
ReportStream as a system needs to provide receivers with a list of reports sent to them.  This list must include data from all pipelines in a consistent manner, so we need to include deliveries from the UP.

### Risks/Impacts/Considerations
* Some of the delivery data could be different since the pipeline is different.

### Dev Notes:
* Compare to the COVID responses and figure out if there are differences and tackle them as appropriate for the UP.  Engage the team for feedback

### Acceptance Criteria
* A receiver can see the deliveries made to it as part of the Deliveries API response.
* A receiver can see the specifics of a delivery made to it as part of the Detail Deliveries API response.

**Comment by carlosfelix2** [comment]
@TurkeyFried thinks we will need some extra data for the UP

**Comment by TurkeyFried** [comment]
This ticket is actually redundant of the work done by @victor-chaparro in #7576

I can confirm that as we currently are, the API call works correctly and you are able to see relevant data for UP deliveries.

Note that as of this writing there is a bug with the Deliveries API on the developer environment, most noticeable with COVID pipeline calls. Adding ticket here shortly...
