### ISSUE TITLE
ELR Failure - RI, 10/19/2022

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#7080]
Email from Jason Garrett RI DOH:

Hi @oslynn ,

 

I am emailing at this time because RI has identified an ELR that failed upon entry into the RI system.  This is with accession#` cb23c0a5-3984-4ba2-8f9c-141db7d7bca4` and failed on entry yesterday 10/19.  I had our vendor investigate the raw message and the case for failure is listed below.  Can you please review and verify if this is a good result or was it one used when testing your system with Jason Suchon yesterday?  If it is a good result, can this please be corrected and resubmitted?  If it was a test message to test the SFTP, no further actions are required.

 

![image.png](https://images.zenhubusercontent.com/62827d1e0129e15b5c366b1a/97730bb0-cd79-4538-8893-e0df6e68d845)
 

 

Thank you,

 

Jason Garrett, BSN, MPH

**Comment by shy2cdc** [comment]
Email from Jason G:

Good morning Ott,

 

This morning RI received a list of ELR failures from the ReportStream feed due to missing required data elements in the HL7 messaging.  There are 7 total failed messages from yesterday, and all with the same reason code.  Below is a screenshot of the reason for failure and list of accession numbers.  Please work to have these corrected and resubmitted as soon as possible, as implement the fix to prevent these errors going forward.  If you need additional information, please let us know and I can open a ticket with our NBS host vendor.

 

Accession #: `05204ec7-476e-4af2-a80d-8a8f88aa4651`

Accession #: `9ecadb3d-57b1-4530-a8b8-857fc9e67646`

Accession #: `9c96a25a-aabe-4322-b768-851ebe7d8c60`

Accession #: `5872ddd8-e380-4d1a-a446-42f1cf18e288`

Accession #: `ef515e92-26b7-41ad-82c8-ae14bb328f41`

Accession #: `04aa517d-f52e-4478-86bb-9f2c26e155fa`

Accession #: `19b6b8ed-b23f-4e15-815a-64e9f1a356ec`

 

 

 

Success/Failure

Description

Failure

The code for Ordered Test name is missing. Blank identifiers in segments HL7LabReport.HL7PATIENT_RESULT.ORDER_OBSERVATION.ObservationRequest.UniversalServiceIdentifier


 

 

 

Thank you,

 

Jason Garrett, BSN, MPH

**Comment by shy2cdc** [comment]
Email from Jason G:

Thank you all.  I have also looped in Jason from our ASP vendor, who conducted the onboarding, in case there are any back end questions that he may be able to assist with.  Ott, if you would like one cumulative file of all the Advanced Molecular Diagnostic accessions #’s which failed, please let me know.  I would be more than happy to get that for you.  In the meantime, is that feed able to be turned off until the fix is completed and implemented so RI does not keep getting numerous failure alerts?

 

Thank you,

Jason G

RIDOH

**Comment by shy2cdc** [comment]
Email from Jason G:

Hi @oslynn tt,

 

There were continued Advanced Molecular Diagnostics ELR failures over this weekend due to the feed continuing to stay active while you work on the fix.  I have attached a cumulative list of message ID’s and test accession #’s for your FYI of all AMD failures.  All of these results will need correct and resubmission to RI once your fix is in place.  If RI continues to received AMD failures, I will add to his aggregate file and forward to ReportStream for FYI purposes and easier identification of which messages need to be retriggered for submission to RI.

 

Thank you,

Jason Garrett

RI Dept of Health

**Comment by shy2cdc** [comment]
Email from Ott:

Good morning, Mr. Garrett,

I will deactivate the feed while I am working on the fix.  Is that ok with you?  I will reactivate it as soon as I have a fix in place.

Very best regards,
-Ott Sathngam
CDC SWE

**Comment by oslynn** [comment]
2022-10-24 - Email from RI (Jason Garrett)

Hi Ott,

There were continued Advanced Molecular Diagnostics ELR failures over this weekend due to the feed continuing to stay active while you work on the fix.  I have attached a cumulative list of message ID’s and test accession #’s for your FYI of all AMD failures.  All of these results will need correct and resubmission to RI once your fix is in place.  If RI continues to received AMD failures, I will add to his aggregate file and forward to ReportStream for FYI purposes and easier identification of which messages need to be retriggered for submission to RI.

[https://app.zenhub.com/files/304423150/ba6e7b37-c5c1-4141-8532-cb44fc8cc815/download

Thank you,
Jason Garrett
RI Dept of Health

**Comment by oslynn** [comment]
2022-10-24.  Configure prod setting database for RI-DOH to block messages that doesn't have valid OBX-3.2.
Notified RI with email below:

Good after noon, Mr. Garrett,

I configured our system to not send the message that doesn't have valid "Test Ordered LOINC Long Name" (OBX-3.2).
Therefore, you will still get other messages.  Further, I will be working with senders to resolve those invalid messages.
After we get them resolved, I will resubmit all of them.

Please let me know, if you still get those invalid missing OBX-3.2 messages.

Thank you for your patient,
-Ott Sathngam
CDC SWE

**Comment by shy2cdc** [comment]
Email from Jason G:

Hi Ott,

 

Failed message info from yesterday, 10/24, below.

 

Processed Time

Status

Message ID

Reporting Facility

Accession#

Exception Text

10/24/22 4:01 PM

Failure

`c11377a5-907d-42f8-b71b-ac1ceabcf00f-6`

Advanced Molecular Diagnostics

`c11377a5-907d-42f8-b71b-ac1ceabcf00f`

Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

10/24/22 4:01 PM

Failure

`d3b3f773-bf60-4d39-afc6-b00214861e4a-6`

Advanced Molecular Diagnostics

d3b3f773-bf60-4d39-afc6-b00214861e4a

Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

10/24/22 4:01 PM

Failure

`928d6586-7ee3-4602-b4fb-ab16802358d8-6`

Advanced Molecular Diagnostics

`928d6586-7ee3-4602-b4fb-ab16802358d8`

Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

 

Best,

Jason

**Comment by oslynn** [comment]
2022-10-24:
Hi Ott,

 

Failed message info from yesterday, 10/24, below.

 

Processed Time

Status

Message ID

Reporting Facility

Accession#

Exception Text

10/24/22 4:01 PM

Failure

c11377a5-907d-42f8-b71b-ac1ceabcf00f-6

Advanced Molecular Diagnostics

c11377a5-907d-42f8-b71b-ac1ceabcf00f

Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

10/24/22 4:01 PM

Failure

d3b3f773-bf60-4d39-afc6-b00214861e4a-6

Advanced Molecular Diagnostics

d3b3f773-bf60-4d39-afc6-b00214861e4a

Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

10/24/22 4:01 PM

Failure

928d6586-7ee3-4602-b4fb-ab16802358d8-6

Advanced Molecular Diagnostics

928d6586-7ee3-4602-b4fb-ab16802358d8

Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

 

Best,

Jason

**Comment by oslynn** [comment]
2022-10-29.  Resubmitted all the messages with corrected OBX-3.2 to Jason.

**Comment by oslynn** [comment]
2022-10-31: Feed back from RI all messages resubmitted on 2022-10-29 missing OBR-4.1, 4.2.

**Comment by oslynn** [comment]
2022-11-1: resubmitted one corrected OBR-4 message to RI to see if it is good. 
Good morning, Jason,

I corrected the OBR-4-1, 2, 3, 7 for one message and uploaded to your prod folder to see if it is good for you.
The message id: cb23c0a5-3984-4ba2-8f9c-141db7d7bca4

Please let me know if it is good for you.  I will process and resubmit the rest of the messages.

Very respectfully,
-Ott Sathngam
CDC SWE

**Comment by shy2cdc** [comment]
Thank you, Ott,

 

I will be on the lookout for this at the next ELR push time and provide some feedback.

 

In addition, I did notice during my review of the failures from 10/29 that there are duplicate accession #’s coming through with different reporting facility names, i.e. Advanced Molecular Diagnostics (AMD) and CDC PRIME.  It is my assumption that these are all AMD accessions, but my question is to why they are also coming through with CDC PRIME as the reporting facility?  Examples below:

 

Processed Time

Status

Message ID

Reporting Facility

Accession#

Exception Text

10/22/22 4:01 PM

Failure

027b9348-8718-45cd-9d3c-7f8e55c24d99-6

Advanced Molecular Diagnostics

027b9348-8718-45cd-9d3c-7f8e55c24d99

Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

10/29/22 4:01 PM

Failure

027b9348-8718-45cd-9d3c-7f8e55c24d99-6

CDC PRIME

027b9348-8718-45cd-9d3c-7f8e55c24d99

Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

10/29/22 4:01 PM

Failure

027b9348-8718-45cd-9d3c-7f8e55c24d99-6

Advanced Molecular Diagnostics

027b9348-8718-45cd-9d3c-7f8e55c24d99

Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

Processed Time

Status

Message ID

Reporting Facility

Accession#

Exception Text

10/20/22 6:01 PM

Failure

`04aa517d-f52e-4478-86bb-9f2c26e155fa-6`

Advanced Molecular Diagnostics

`04aa517d-f52e-4478-86bb-9f2c26e155fa`

Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

10/29/22 4:01 PM

Failure

`04aa517d-f52e-4478-86bb-9f2c26e155fa-6`

Advanced Molecular Diagnostics

`04aa517d-f52e-4478-86bb-9f2c26e155fa`

Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

10/29/22 4:01 PM

Failure

`04aa517d-f52e-4478-86bb-9f2c26e155fa-6`

CDC PRIME

`04aa517d-f52e-4478-86bb-9f2c26e155fa`

Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

 

 

Thank you,

Jason G
RIDOH

**Comment by shy2cdc** [comment]
Email from Jason G:

Hi Ott,

 

Thank you for this update and thank you for the time and efforts to correct the feed.   Please feel free to contact me with any questions you have as well.

 

Best,

Jason
