### ISSUE TITLE
Map the error message flow for receivers

### ISSUE THREAD

**Issue by fmccaf1** [CDCgov/prime-reportstream#7082]
## Problem statement
What happens when receivers get an error?

## Acceptance criteria
Perform interviews with receivers (PHDs) to understand:
- How do PHDs realize they're getting incomplete data?
- What is the process for PHDs in reaction to incomplete data?

## To do
- [ ] Identify and reach out to (minimum of 5, including CA) PHDs to communicate research plan and schedule interviews
- [ ] Create conversation guide 
- [ ] Perform interviews
- [ ] Synthesize interviews
- [ ] Document findings in a Mural as a flow of events including tools and screenshots

**Comment by chris-kuryak** [comment]
@fmccaf1 Is this issue to synthesize results based on the interviews you will complete as part of this epic #7341 ?
Or are you going to reach out to 5 new PHDs in addition to the ones you have already talked to?

**Comment by fmccaf1** [comment]
@chris-kuryak I ended up getting pretty stalled on this work, as well as epic 7341. I think we could close out these issues, given that I'll be leaving the team soon, and let Nava designers decide what research they want to do and what should be prioritized.
