### ISSUE TITLE
Utah Onboarding – Create Org and Sender Settings  

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#7092]
### Acceptance Criteria 
- [ ] Added to organization.yml and create yamlitos  
    - [ ] Customer status = testing  
    - [ ] For HL7 senders, schemaName: hl7/hl7-ingest-covid-19-training  

- [ ] Added to prod settings table  
- [ ] Added to staging settings table

FYI: this ticket can be completely concurrently with “Validate Test Files” ticket for this API sender 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with sender 
- [ ] RS team member who originates this ticket: add any dependencies, as needed 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [x] Pipelines: Onboarding & Operations (New) 
     - [x] Labels: "Onboarding-ops" and "Sender" 
     - [x] Epics: [select the epic for this API onboarding sender]

**Comment by oslynn** [comment]
2022-12-19:
The person who normally helps with some of these processes is off for the week. If you can answer a few questions, with any luck, we'll have some feedback for you next week. Over the holidays is tricky with our staffing.

Thanks for your patience with this. Once we get these initial pieces set up it should be a very quick process.

Teri

**Comment by brandonnava** [comment]
@oslynn Keeping an eye on this. Will follow up if don't hear from them this week.

**Comment by oslynn** [comment]
Done.
