### ISSUE TITLE
Utah Onboarding - Validate Test Files 

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#7093]
## Problem statement

The HL7 structure needs to be tested with UT. They will need messages sent through the test feed first as fake data. When that passes validation, then LIVE messages should be sent

## Acceptance criteria

- [x] Fake messages sent to UT
- [ ] UT accepts HL7 structure of fake messages
- [ ] Live messages sent to UT
- [ ] UT accepts HL7 structure of live messages

## To do

- [ ] Create HL7 files from CLI with fake data
- [ ] received feedback on fake messages
- [ ] implement settings changes as needed
- [ ] Send live HL7 files from CLI
- [ ] received feedback receive feedback on fake data

**Comment by BerniXiongA6** [comment]
@brick-green will edit AC and To Do's (currently using sender onbaording by acciddnt)

**Comment by BerniXiongA6** [comment]
I'm sizing this as a "2" since most previous tickets with this scope were sized as "2"

**Comment by oslynn** [comment]
Teri,

I sent the test file to you sFTP/in folder file: covid-19-c21b8eef-8283-4060-a480-d4b023c92e3f-20221205155713.hl7
Please validate it and let me know the quality of the messages.
If anything that I need to do, please let me know.  I will get it done for you asap.

Thank you for you response.  I am looking forward to get your onboarding done asap.

Very respectfully,
-Ott Sathngam
CDC SWE

**Comment by Jcavallo7** [comment]
User states: 

"The person who normally helps with some of these processes is off for the week. If you can answer a few questions, with any luck, we'll have some feedback for you next week. Over the holidays is tricky with our staffing.

Thanks for your patience with this. Once we get these initial pieces set up it should be a very quick process.

Teri"
