### ISSUE TITLE
Publish What's New - Nov 2022 Update

### ISSUE THREAD

**Issue by fmccaf1** [CDCgov/prime-reportstream#7095]
## Problem statement
As a user, I would like to know what features, bugs, other user facing updates have been made to ReportStream product.

## Acceptance criteria
Please check the box corresponding with your name when you have finished editing the ["Content Updates" document](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B46d04c32-4db8-4d1d-941a-e5fdbf76df09%7D&action=edit&wdPreviousSession=ed1dd437-d3a3-431e-84d2-8ebb8c0c67ff&cid=accaa3e4-0b9c-416b-b410-de8a175033d1).

- [x] Stephen's done
- [x] Berni's done
- [x] Heather's done
- [ ] Florence published to RS

**Comment by HeatherRienks** [comment]
@HeatherRienks to provide content to Florence by XX date for release in early December.

**Comment by HeatherRienks** [comment]
@CnoteNava - FYI

**Comment by BerniXiongA6** [comment]
My portion is done for O&O!

**Comment by HeatherRienks** [comment]
My portion is done too!
