### ISSUE TITLE
Clean up the livd-table-update utility command.

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#7118]
The CDC https://www.cdc.gov/csels/dls/sars-cov-2-livd-codes.html is blocking all bots.  Therefore, the download option of the livd-table-update is no long work since it is a bot.  From now on, we can only download the LIVD Table Spreadsheet manually.

This ticket is to clean up the download option from the utility.  We also need to add unit and integration tests to the utility.
Update all documentation relating to the utility.

**Comment by BerniXiongA6** [comment]
@oslynn will PR today, and then close this ticket -- then create a new ticket for O&O backlog for next steps. cc: @BerniXiongA6
