### ISSUE TITLE
New Jersey - Move It Account Questionnaire

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#7122]
Hello,

We are in the process of verifying if you still need your State of New Jersey, Department of Health MoveIt account.  We have provided a questionnaire below that we are requesting you fill out to determine if you still need access to MoveIt, along a few other questions that will help us identify how you use MoveIt, password expirations and if you are receive the emails from the MoveIt system.

Please reply to this email with the questionnaire answered below. 

1. How often you log on to your MoveIt account?

Frequently
Sometimes
Never
 
2. Do you have an automated script for sending data to MoveIt?

Yes
No
 
2A. If yes to question number 2, how often you check if data is transferred? 

3. Do you manually upload files to MoveIt?

Yes
No
 
4. Do you get the password expiry e-mail from MoveIt?

Yes  
No
 
5. If your do receive the password expiry e-mail from MoveIt, do you reset it right away?

6. Would you find it helpful to receive multiple emails reminding you about your password expiring from MoveIt?

Yes
No
                                                               
7. If yes to question number 6, how often would you like to receive an email from MoveIt before the password expiration date?

8. Are you able to use a group email when setting up a MoveIt account?

Yes
No
 
Thank you,
The Health Information Technology Team

**Comment by Jcavallo7** [comment]
User sent an update:

"Hello,

 

We are in the process of verifying if you still need your State of New Jersey, Department of Health MoveIt account.  We have provided a questionnaire below that we are requesting you fill out to determine if you still need access to MoveIt, along a few other questions that will help us identify how you use MoveIt, password expirations and if you are receive the emails from the MoveIt system.

 

Please reply to this email with the questionnaire answered below.

 

1. How often you log on to your MoveIt account?

Frequently
Sometimes
Never
 

2. Do you have an automated script for sending data to MoveIt?

Yes
No
 

2A. If yes to question number 2, how often you check if data is transferred? 

                

3. Do you manually upload files to MoveIt?

Yes
No
 

4. Do you get the password expiry e-mail from MoveIt?

Yes  
No
 

5. If your do receive the password expiry e-mail from MoveIt, do you reset it right away?

 

6. Would you find it helpful to receive multiple emails reminding you about your password expiring from MoveIt?

Yes
No
                                                               

7. If yes to question number 6, how often would you like to receive an email from MoveIt before the password expiration date?

 

8. Are you able to use a group email when setting up a MoveIt account?

Yes
No
 

Thank you,

The Health Information Technology Team"

**Comment by rnz6** [comment]
Forwarded to Ott to complete the survey
