### ISSUE TITLE
SimpleHealthKit - Onboarding - Validate Test Files 

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7133]
### Acceptance Criteria 
- [**10/25/2022**] Sample file from sender received by RS team 
- [x] Sample files saved to Keybase by assigned RS engineer 
- [x] Sample file ingested into RS using validation UI tool by assigned RS engineer 
- [x] Feedback provided to sender by assigned RS engineer (including instructions on what to modify in order to get validated)* 
- [x] Sender modifies and re-sends sample file to get file validated by RS engineer* 

*Steps can continue until RS can ingest the file from sender 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with sender 
- [ ] RS team member who originates this ticket: add any dependencies, as needed 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Sender" 
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by GilmoreA6** [comment]
Hello James,

Thank you for reviewing our initial file. We made the necessary changes based on your guidance. Please take a look at our new file attached below. 

Please let us know if there are questions and what the next steps are when this file passes your validation.

Best regards,
Ramtej Pinisetty

**Comment by Jcavallo7** [comment]
User sent an update:

"Hello James,

Happy New Year! Hope the holidays are going well. Do you have an update on the new file validation? 

Thank you,
Ramtej"

**Comment by GilmoreA6** [comment]
Hi Ramtej,

Looking at the updated file it looks like the only item to discuss would be the dates in the file are not valid and don't have offsets (example order_test_date 20200000000000). Can you make sure that what gets sent in those fields is a valid date? (don't need to send a new file, just as we move forward in testing). For the offsets we expect the UTC offset (example for pacific time zone 20230117121314-0800). If we do not receive the UTC offset in the date we will assume that the timestamp sent is UTC (+0000).

I think this is good enough to move to testing in staging. Do you know if you will be able to use token auth (preferred) or if want to use a shared secret? (both methods are described in the Programmer's guide starting on page 9 https://reportstream.cdc.gov/resources/programmers-guide).

If you do decide to use token auth, I will need you to send me two public keys (one for staging and one for production). If you decide to use shared secret I will generate a secret to send to you. We typically send via Keybase.io. If you choose this route please create a keybase account and let me know what your account name is. Once we have that set-up our next step will be sending test data to our staging system.

Please let me know if you have any other quetsions.

Thanks,

James
