### ISSUE TITLE
Genabio Onboarding – Testing in Staging and Prod

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#7134]
### Acceptance Criteria 
- [ ] Sender has tested in staging and production 
- [x] RS engineer has determined the data is good enough and graduates Sender to send Prod data to receiver  

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with sender 
- [x] RS team member who originates this ticket: add dependencies:  
     - [x] [name of company] Onboarding – Create Org and Sender Settings
     - [x] [name of company] Onboarding - Validate Test Files 
- [x] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [x] Pipelines: Onboarding & Operations (New) 
     - [x] Labels: "Onboarding-ops," "Sender"
     - [x] Epics: [select the epic for this API onboarding sender]

**Comment by GilmoreA6** [comment]
Hi Juehua,

I have included the new public key you sent in our staging environment. Could you also provide one for production and I will add it.

When you are ready could you attempt to send some test data to the staging environment? Please note that no real data should be sent to staging, only test data.

Let me know if you have any other questions.

Thanks,

James

**Comment by GilmoreA6** [comment]
Hi Juehua,

I think I've found the issue. In your payload you have: 
{'iss': 'genabiolab.default', 'sub': 'genabiolab.default', 'aud': 'staging.prime.cdc.gov', 'exp': 1667400144, 'jti': 'xxxxxxxxx'}
Whereas ReportStream is expecting 
{'iss': 'genabio.default', 'sub': 'genabio.default', 'aud': 'staging.prime.cdc.gov', 'exp': 1667400144, 'jti': 'xxxxxxxxx'}
also, make sure that your header replaces genabiolab.default with genabio.default and that you change your scope from genabiolab.*.report to genabio.*.report in the CURL request to get the token.
That should allow you to generate the token. 
Once you have the token, remember that you should put genabio as the client in when submitting data as below:
 curl -H "authorization:bearer " -H "client:genabio" -H "contenttype:text/csv" --data-binary "@./healthy-labs-nonPII-data.csv"
"https://staging.prime.cdc.gov/api/waters"
This is probably a mistake on our part where we gave you the wrong org name so I apologize.

For your other question " "I have included the new public key you sent in our staging environment. Could you also provide one for production and I will add it." We recommend different public/private keypairs for staging and prod. The .pem file you provided with your public RSA key I have associated with your account in staging and I am requesting a .pem file with the public key associated to the public/private keypair that you will use in production (this does not have to be done now and can be done once we complete testing in staging.)

Thanks,

James

**Comment by GilmoreA6** [comment]
Hi James,


Thanks a lot for your detailed information in your previous email. We fixed the problems and have sent our dummy csv file verified previously by CDC ReportStream team with bearer token, however, a failure JSON response was sent back to us, please see the attached "genabio.output.txt". We also used the sample csv file in the manual page 31, "Appendix B: Sample Payloads and Output", unfortunately, we never got the response listed in the manual instead of error JSON info, please see "sample.output.txt". We suspect the errors are due to the missing values in the csv file. Do you have any suggestion?


We truly appreciate your great help!


Juehua

**Comment by GilmoreA6** [comment]
Hi Juehua,

It looks we had created you a custom schema with different column headers. I have reverted your settings to use the default CSV upload schema. If you submit a file following the Programmer's guide now you should receive a successful response.

Thanks,

James

**Comment by GilmoreA6** [comment]
Hi All,


I forgot to mention that if you would like to keep using the existing custom schema you have if you could forward me the dummy file you attempted to send in I can troubleshoot. It looks like you are missing the field testing_lab_clia.

Thanks,

James

**Comment by GilmoreA6** [comment]
Hi James, 

Thank you so much for your email. We could not submit our dummy csv file yet by bear token, though we used the sample csv file provided by ReportStream Programmer's Guide at Appendix B, Page 31, for successful submission. After carefully checking the csv files, we noticed that testing lab information are required, however, our Covid19 antigen testing kits are OTC products and the information about testing lab is not available. So we wonder whether you can do sth in your side to ingore the testing lab information, such as name, address, phone, etc, for our submission.

In attached, please find our dummy csv file. 

Best wishes,
Juehua Yu

**Comment by GilmoreA6** [comment]
-multiple issues with latest test file that need to be corrected.

**Comment by GilmoreA6** [comment]
Hi Juehua,

Apologies for my delay in response. I've checked the most recent file and I think the only thing we have that's still an issue in the file is the timestamps. Currently the date and timestamps are being sent in format dd/mm/yy. For DOB we would like yyyyMMdd and for the other timestamps in the file (order_test_date, specimen_collection_date, test_result_date, date_result_released) we would like to use the format yyyyMMddhhmmss+/-zzzz where zzzz is the offset from UTC time (for example for PST this would be 20221117142800-0800). If the offset is not included we will assume the timezone is UTC.

As far as documents, the only thing we need is acceptance on our Terms of Service, do you know if you have completed that yet? Once we have that and the timestamps issues fixed we can move to testing in production. One other thing I will need is the public key for the public/private keypair that you want to use in production. We recommend using different keypairs in staging and production.

Thanks,

James

**Comment by GilmoreA6** [comment]
Thanks Juehua!

The file looks good. Can you submit this through the API to our staging endpoint? If we don't have any problems there we can move on to testing in Prouction. Is there a particular state or territory that you want to test with? (usually this would be the state where most of results will go or where you are located).

Thanks,

James

**Comment by GilmoreA6** [comment]
Hi Juehua,

I saw some test files come in on 12/13 to staging and I have validated they look ok. The last step will be testing in production. In this step we will need you to send a few real patient results to our production api. Is there a State you would like to test with or are you only looking to report federally?

Please make sure that any real patient data is only sent to the production api. No real data should be sent to staging.

Thanks,

James 

James Gilmore (Agile Six)
Senior HL7 Data Analyst
Pandemic-Ready Interoperability Modernization Effort (PRIME)

**Comment by GilmoreA6** [comment]
Hi James, 
I have submitted real patient data already. Could you please check whether they look good? 

Best,
Juehua

**Comment by brandonnava** [comment]
Waiting on Genabio
