### ISSUE TITLE
CA - Unable to download daily data

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#7138]
Elaine Li, elaine.li@phd.sccgov.org, Santa Clara County Public Health

User needs help downloading reports under daily data. "It always shows me a system message that there was an error loading the contents when clicking on the report name or "CSV". "

**Comment by TaneaY** [comment]
User emailed in for an update....

"I want to report that I’m not able to open and download my data. Can you please let me know if any updates or new versions were released that impacted my access? Thank you! 

I submitted a service request two days ago and haven’t received any feedback."

**Comment by rnz6** [comment]
@BerniXiongA6 

Follow up email from user 11/3:

 "I need help downloading and accessing the daily data though I can see the daily report comes up every day. Please verify my access/account setup if it caused the problem."

**Comment by sliu1000** [comment]
Sent follow up email to see if user is still having dl issues.

**Comment by sliu1000** [comment]
This ticket will be merged with ticket # 7372 @BerniXiongA6  @brandonnava should we create an epic for RS Daily Download Data issue? So far, we have three users having this issue.

**Comment by BerniXiongA6** [comment]
Closing this and keeping 7372 open
