### ISSUE TITLE
New Settings names (and Clone) should prevent any names with special characters (e.g. `.`)

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#7139]
Lots of code on the server depend on specific naming conventions. If Setting names (or Org names) include a specific set of character (or even words), then random problems will happen.

Ideally, this would be enforced at the API/pipeline layer, but a good place to start is the frontend UI.

 - [x] Exclude following characters from all names: 
  - `"."` (period) because it's often used as a delimiter for `[org].[setting]` 
  - `" "` (space)
  - `"/"` (forward slash)
  - Any non-ascii characters. (e.g. UTF8)
  - URL reserved characters: [e.g. `&`, `+`, `,`, `=`, `?`, etc]. 

The best approach might be to call a urlEncode function on the string and verify it doesn't change.

 - [x] Prohibited names:
  - `"all"` (`api/check` issue)
  - `"revs"` (`org/{organizationName}/senders/revs` issue)
  - `"organization"`, `"sender"`, `"receiver"`, `"org"`, `"list"` because they are often used as cmd actions.
  
Bonus Lookup table:
 - [ ] Exclude all URL reserved characters (see above for how).
 - [ ] Exclude Lookup table named `"list"` (`/api/lookuptables/` issues)

**Comment by TomNUSDS** [comment]
Also, the server-side Settings api should probably enforce there as well!

**Comment by kevinhaube** [comment]
@TomNUSDS saw your note in slack, will make sure we point and do in Sprint 5...7? The next one.

**Comment by kevinhaube** [comment]
As for the API side, make that unit of work a ticket and label it Platform! Jim Duff will be managing backend and experience will be React only again with the way Nava team structures are moving 🙂

**Comment by kevinhaube** [comment]
To be duplicated and a back-end version of this work will be done in addition to this front-end portion!

**Comment by penny-lischer** [comment]
API ticket #7744
