### ISSUE TITLE
FE Tech Debt: Design Enhancements

### ISSUE THREAD

**Issue by HeatherRienks** [CDCgov/prime-reportstream#7141]

**Comment by HeatherRienks** [comment]
@fmccaf1, @victorialb-usds @drew-usds 
Creating this Epic to keep track of all of our small design related "tech debt" so we can tackle as we have time and it won't be overlooked.

**Comment by etanb** [comment]
@HeatherRienks once I close the remaining tickets I'm working on currently, will this Epic close itself? Or should I assign myself?

**Comment by HeatherRienks** [comment]
@etanb - great question - Epics will NOT close themselves. In this particular case, we want to keep this Epic open, as it is where anyone on the team can add new Design related Tech Debt tickets.
