### ISSUE TITLE
Abbott- Sender failure- system outage

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#7149]
Pamela Palmer, pamela.palmer@abbott.com, We are receiving a number of failures from our function that sends COVID test results to HHS. It is indicating that the service is unavailable.

**Comment by sliu1000** [comment]
Update from Jim regarding Sender ABBOTT:

From: Palmer, Pamela A <pamela.palmer@abbott.com>
Subject: AIMs issue
 
Good afternoon,

At approximately 11:00 AM CDT, we started getting a failure with the function application that sends Abbott’s NAVICA application COVID test results into AIMs. It is indicating that service is unavailable. We have had over 750 failures. There have been some successful transfers of data, but we are still seeing failures. I submitted a ticket through the AIMs dashboard, but John Schullian recommended we send you an email as well. We would appreciate any assistance and information you can  provide.
 
Here is a sample of the error:

![thumbnail_image002.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/d4c79405-c623-4a11-9cc1-b8e5eaaf99b5)

**Comment by shy2cdc** [comment]
Email from Pam:

Hi,

 

By 4:30 PM CDT, the errors had dropped to zero.

 

 

Regards,

 

Pam

**Comment by shy2cdc** [comment]
Email from Pam:

Good morning,

 

The error count has remained low overnight and we have retries built into the function that sends the data. We are continuing to monitor, but we are anticipating that nothing will need to be resent. Can you share what the root cause of the issue was?

 

 

Regards,

 

Pam
