### ISSUE TITLE
Investigate which high volume senders not set to async

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#7151]
## Problem statement

All senders should be set to async processing type unless they have a need for the richer JSON response from the sync processing type. This action needs to be coordinated with the sender in the event they are currently using the data received in the "sync"  SON response. This will require us to reach out to the customer to ask about their current use of this data.

This will enable future work to "decouple" receiving actions from the rest of ReportStream to increase platform flexability in the event of an unexpected downtime.

## What you need to know

Here is the current list of active senders set to processing type "sync". All of them need to be contacted and a switch to "async" processing mode coordinated unless they have a need for the information generated from the "sync" processing mode for their own internal processes.

##Acceptance criteria

- [ ] All senders contacted and set to "async" or determined to need "sync" processing mode
  - [ ] corebiolabs-oh
  - [ ] warrior-dx-co
  - [ ] stemexpress-ca
  - [ ] covidclinic-org
  - [ ] hollywoodsmiles-ca
  - [ ] all-in-one-health-ca
  - [ ] newport-childrens-hospital-ca
  - [ ] youthclinic-co
  - [ ] elitemedlabs-co
  - [ ] strac
  - [ ] safehealth
  - [ ] inbios
  - [ ] imagemover
  - [ ] johns_hopkins
  - [ ] reddyfmc-la
  - [ ] cuc-al
  - [ ] guc-la
  - [ ] primary
  - [ ] jrslab-ca
  - [ ] pcl-ca
  - [ ] mycarelabs-ca
  - [ ] biovisiondx-il
  - [ ] kwokmandx-ca
  - [ ] toprankdx-ca
  - [ ] hcintegrations
  - [ ] mpbiomedicals
  - [ ] neurolab
  - [ ] limsabc-nova
  - [ ] intrivo
  - [ ] clxhealth
  - [ ] signetic
  - [ ] aegis
  - [ ] mayo-clinic
  - [ ] sonic

**Comment by brick-green** [comment]
Jim mentioned that we should not change the simple report csv uploader to async as SR may be displaying that information directly to the upload user. Going to make a spreadsheet to track comms with senders on this.

**Comment by BerniXiongA6** [comment]
@GilmoreA6 -- please add steps to the AC

**Comment by BerniXiongA6** [comment]
Brandon says it's a high priority Product goal - aligns with our OKR

**Comment by LaFreda1** [comment]
@brandonnava can I close this?

**Comment by brandonnava** [comment]
@brick-green Do you think we really need to reach out to all the senders listed or can we just go in and set everyone to async?

**Comment by LaFreda1** [comment]
See @GilmoreA6 for context

**Comment by LaFreda1** [comment]
Next step is to run query again

**Comment by LaFreda1** [comment]
@brandonnava to make more appropriate ticket for async
