### ISSUE TITLE
Add "Test Performed LOINC Long Name" column to LIVD-Suplemental table.

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#7165]
During livd lookup for "Test Performed LOINC Long Name" using "Device_ID" (in LIVD Mapping column: Model), we don't get a unit value.  The reason is that LIVD-Suplemental table doesn't have the "Test Performed LOINC Long Name" column.  It gives us blank ("").  Therefore, the lookup will return a valid value + blank and it is not unique.

**Comment by BerniXiongA6** [comment]
@oslynn Thanks for letting us know you found this issue. Please add more details: who is this affecting? how many senders are affected, if any? is this already being worked on or is it coming up as new work for Spring 54? Thanks for updating the ticket with these answers. cc: @brandonnava @BerniXiongA6
