### ISSUE TITLE
Remove the LIVD-Suplemental table

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#7166]
According to MO, he suggested that we remove the supplemental table.  This needs to be confirmed with Brick.  
1.) Remove the table 
2.) Test to make sure it doesn't break anything else.

**Comment by BerniXiongA6** [comment]
@oslynn please provide more info, also including @brick-green for visibility. What priority is this? Should it go into this or next sprint? Please advise, thanks! cc: @brandonnava @BerniXiongA6

**Comment by oslynn** [comment]
@BerniXiongA6 @brick-green this ticket is a lower priority.  @MauriceReeves-usds told me to clean up the supplemental table.  He thinks that we don't need it.  However, he wants me to confirm with @brick-green first.  Yes, it can go to the next sprint.

**Comment by brandonnava** [comment]
@oslynn in testing mode for this

**Comment by LaFreda1** [comment]
updates? @jalbinson

**Comment by jalbinson** [comment]
This ticket is still in progress and I worked with @oslynn a bit yesterday to clarify some details.

**Comment by LaFreda1** [comment]
Should have PR out by tomorrow

**Comment by jalbinson** [comment]
Decided against working on this as it would add more tech debt by only partially removing the supplemental table.
