### ISSUE TITLE
PA - Investigate are/not receiving ALL SimpleReport Data

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7169]
Question sent from Kirsten Waller (kwaller@pa.gov), state of PA on 10/28/2022 11:27 AM:

## Problem statement

Wants to make sure they are or can receive SimpleReport Data.

## What you need to know

- The PA Department of Health ELR team would like to have a conversation regarding receiving SimpleReports in our ELR system.  We do receive some SimpleReport data that comes through AIMS, and assumed that they all were going through AIMS, but we have learned that this is not the case. 

Per Michael G. Eberhart, MPH (Epidemiology Research Associate - Informatics):

> We currently receive data from CDC Prime ReportStream for school based testing results delivered to us using HL7 from USDS
> 
>  
> 
> SFT|Centers for Disease Control and Prevention|0.2-SNAPSHOT|PRIME ReportStream|0.2-SNAPSHOT|
> 
>  
> 
> This covers school testing in Montgomery, Chester, Buck, Philadelphia and Allegheny counties.

 

## Acceptance criteria

- Start to receive all SimpleReport Data

## To do

- Check to see if PA is or is not receiving ALL SimpleReport Data

**Comment by BerniXiongA6** [comment]
Hi @sliu1000 Sharon, do we know what we are asking @brandonnava to do to take action on this request? Should this be a SR and RS joint meeting with PA DOH to confirm to them whether there is SR data coming through RS as opposed to AIMS? It says that PA DOH learned not all SR data is coming through AIMS, but it didn't indicate "who" they learned that from... curious if you have more info on this ask? cc: @brick-green @MauriceReeves-usds

**Comment by sliu1000** [comment]
@BerniXiongA6

I tagged Brandon because at the last meeting you mentioned that the Product Manager will be moving the tickets from new to old.   A few things that come to mind is to check to see what data is coming in from PA. Someone from Engineering can check or do some research on that.

**Comment by BerniXiongA6** [comment]
Thanks @sliu1000 for clarifying... I also see that you emailed PA to ask additional info too. @brandonnava and I met today to go over "Needs Analysis" of New tickets that get put on the board, so we'll make sure to keep communicating thoroughly on the tickets as we have questions or comments or updates. Thanks Sharon!

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 to get back to PA DOH on Monday 10/31 to schedule a call or respond with more elaborate answers to their questions. cc: @brandonnava @sliu1000

**Comment by BerniXiongA6** [comment]
Meeting scheduled w/ PA DOH for 11/10 1:30pm-2pm ET

> Hi all, the purpose of this meeting is for PA Dept. of Health to address questions and needs they have regarding ReportStream/SimpleReport reporting data. I've included members of engineering, design, and product in the mix.
> 
> Here's the original request: 
> 
> The PA Department of Health ELR team would like to have a conversation regarding receiving SimpleReports in our ELR system.  We do receive some SimpleReport data that comes through AIMS, and assumed that they all were going through AIMS, but we have learned that this is not the case.

**Comment by brick-green** [comment]
In meeting with PA we discussed how the state is not connected with RS currently. So the solution was to onboard PA with SOAP. I think we can close this ticket out in favor of a PA onboarding epic.
