### ISSUE TITLE
Osang LLC / Stone Labs Onboarding – Testing in Staging and Prod

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#7217]
### Acceptance Criteria 
- [ ] Sender has tested in staging and production 
- [ ] RS engineer has determined the data is good enough and graduates Sender to send Prod data to receiver  

### To Do 
- [x] RS engineer: update this ticket with comments with every interaction with sender 
- [x] RS team member who originates this ticket: add dependencies:  
     - [x] [name of company] Onboarding – Create Org and Sender Settings
     - [x] [name of company] Onboarding - Validate Test Files 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops," "Sender"
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by sliu1000** [comment]
Update from Sender:

Dear Brick,

Thanks for your feedback.

Our engineer Dr Farid will follow up this issue more detail from next email.

And I am not sure whether attached file is what you or your colleague need to get from us.

Anyway he (our engineer) will back to you on Monday.

Thanks & Best regards,

Philip Choi

**Comment by oslynn** [comment]
Email to Philip: 2022-11-21,
Good after noon, Philip,

Thank you for providing me the sample file for validation.  After examine the file, I had found additional fields and values needed for RS validation.
Please make correction to the sample file as info provided below and then resubmit it back to me.

Please fill in values to following fields:
patient_street: Need value (e.g., 123 Street)
patient_phone_number: need value (e.g., 250837223)
patient_dob: need value (e.g., 20081110)
testing_lab_specimen_received_date: need value (e.g., 20221121)
test_result_date: Need date/time format of YYYYmmDD (e.g., 20221121)
date_result_released: Need date/time format of YYYYmmDD (e.g., 20221121)
ordering_provider_id: Enter National Provider Identifier (NPI)
ordering_provider_last_name: Need value (e.g., Smith)
ordering_provider_first_name: Need value (e.g., John)
ordering_provider_street: Need value (e.g., 123 Street)
ordering_provider_city: Need value
ordering_provider_state: Need value
ordering_provider_zip_code: Need value
ordering_provider_phone_number: Need value
Please add following columns and values:
testing_lab_name
testing_lab_street
testing_lab_city
testing_lab_state
testing_lab_zip_code
ordering_facility_name
ordering_facility_street
ordering_facility_city
ordering_facility_state
ordering_facility_zip_code
ordering_facility_phone_number



If you have any question please feel free to contact me, I will be happy to help out.

Very respectfully,
-Ott Sathngam
CDC SWE

**Comment by oslynn** [comment]
I just got email responded.  I will resume the ticket asap.

**Comment by oslynn** [comment]
Phillip,

I added those columns that provided to your csv test file.  And, I finished with your validation.  However, the file still need values as following:

Field needs value                                                 Example
=======================================================================
patient_street (patient_street).                                  e.g, 123 Street
patient_dob (patient_dob).                                        Format YYYYmmDD e.g.,20081112
ordering_provider_id (ordering_provider_id).                      Enter National Provider Identifier (NPI). e.g., 1341954158
ordering_provider_last_name (ordering_provider_last_name).        e.g., lastName
ordering_provider_first_name (ordering_provider_first_name).      e.g., firstName
ordering_provider_street (ordering_provider_street).              e.g., 123 Street
ordering_provider_city (ordering_provider_city).                  e.g., City
ordering_provider_zip_code (ordering_provider_zip_code).          e.g., 12345
ordering_provider_phone_number (ordering_provider_phone_number).  e.g., +1 844 909 1089
ORC-24-4 (ordering_provider_state).                               e.g., CA
processing_mode_code                                              e.g., T - Test, P - Production
I made the Sample-File-Temple.csv for you to just replace ???? with your value.  Please the attached file.
If you still need me to explain what you need to do, please feel free to you let me know.  And, we can talk 
on the phone.

Very respectfully,
-Ott Sathngam
CDC SWE

**Comment by oslynn** [comment]
Validated their latest message and it is good, now.

**Comment by oslynn** [comment]
Dear Ott,

I wish you and your collegues were having a refreshing start in the New Year and thank you very much again for all your considerate support.

Having discussed with OSANG, we can enumerate the list of four states as of today.

* California (CA)
* Washington (WA) 
* Nevada (NV)
* Ohio (OH)

For any possible changes, we will keep you apprised consistently in order to maintain the reporting system working properly. 

Thank you!​


Best regards,
Eric 
 
----------------------------------------------
 
Eric Mingoo Song
 
CEO / 대표이사
StoneLab Inc.
 
AI Research Center
306, Maeheon-ro 8-gil 47, Seocho-gu, Seoul

HQ Office
303, Daehak-ro 179, Yuseong-gu, Daejeon

**Comment by oslynn** [comment]
Added csv-otc-covid-19-training.schema for Osang to send test messages to us and we will need to process the messages.  Then, we can get them to STLTs for validation.

**Comment by brandonnava** [comment]
@oslynn To check with NV if they will accept the data

**Comment by oslynn** [comment]
They never response back to email.  I will close it for now.  We can reopen it when they are ready to continue.
