### ISSUE TITLE
Implement Phase 1 of Metadata Table Normalization

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#7232]
## User Story
As a user of ReportStream I need access to the data about the contents of the test events we deliver to be available cleanly and in a very performant way.

## Description/Use Case
The current structure of the metadata tables is not sustainable. We need to move the data to a new layout that will scale into the future. More details are available in https://github.com/CDCgov/prime-reportstream/pull/7228

## Risks/Impacts/Considerations
- Experience front-end breaks because the data structure changes
- Metabase queries break because the data structure changes
- We lose data fidelity because we are trying to normalize the data, and not all the data is high-enough quality to support doing that

## Dev Notes:
See https://github.com/CDCgov/prime-reportstream/pull/7228 for more notes

## Acceptance Criteria
- We don't lose any data
- We can accept data with differing levels of quality
- Performance for inserts remains high
- We don't break any experience functionality
- We don't break metabase

## Related Tickets
#7228
#5026
#5884
#6446

**Comment by BerniXiongA6** [comment]
Hi @MauriceReeves-usds -- please add the priority label to this ticket when you get a chacne. In the meantime, @brandonnava and I will move it into O&O backlog so we can take it out of the New column. Thank you sir!
