### ISSUE TITLE
UP Sender Transform detects schema circular dependencies in schema configuration

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#7244]
### User Story:
As developer, I want the UP sender transform to detect when there is a schema circular dependency, so I can fix the issue.

### Description/Use Case
The UP sender transform configuration allows for child schemas (a schema that includes another schema).  There is the possibility that someone could include a schema that was already included at a higher level which will result in an infinite loop.  We need to detect any circular dependency, so the pipeline is more robust.

### Risks/Impacts/Considerations
* Need to make sure to detect circular dependencies between child and parents and not confuse it with a reuse of a schema.

### Dev Notes:
* Child schemas could be reused within a schema, so care must be taken to not remove this feature and only detect circular dependencies.

### Acceptance Criteria
* The UP sender transform throws an error (e.g. SchemaException) if it detects a schema circular dependency.

**Comment by JessicaWNava** [comment]
Work is already done, moving to product review to demo it.

**Comment by JessicaWNava** [comment]
![Screenshot 2023-06-28 at 7.43.15 AM.png](https://images.zenhubusercontent.com/639363089b4547a756baf932/580afb56-0268-4816-a2ea-ccf16dd14907)
