### ISSUE TITLE
Support inline value sets in UP Sender Transform schema

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#7249]
### User Story:
As a developer, I want to be able to specify a set of key/value pairs, so data that matches the key is converted to data specified by the value of the pair.

### Description/Use Case
This feature is similar to the existing FHIR to HL7 value sets.  The idea is that we will take FHIR values and convert them to another value.  For example, we may get strings like "PROD" and "DEMO" that are not valid HL7 values and convert them to proper values using the value sets, like to "production" or "test". 

### Dev Notes:
* This feature is the same as in the FHIR to HL7 library, so reuse is possible, but maintain the library code separate from the rest of the code.

### Acceptance Criteria
* The UP Sender Transform can use a valueSet list of key/value pairs to match a FHIR value to a key and set a FHIR property to the matching value of the key/value pair.
* The UP Sender Transform can have one or more key/value pairs in its valueSet list.
* The UP Sender Transforms valueSet can have an empty string for the value in a key/value pair.
* The UP Sender Transforms valueSet does not set the value of a field if there is no matching key/value pair (no op).

**Comment by jimmyfagan** [comment]
Design doc to reference: https://app.zenhub.com/files/304423150/d666073a-0d70-42dc-9779-82f163ae5593/download
