### ISSUE TITLE
Allow the extending of a UP sender transform schema to create a new schema

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#7251]
### User Story:
As a developer, I want to be able to extend a UP sender transform schema, so I do not have to duplicate a schema configuration that already exists.

### Description/Use Case
This feature is similar to the existing FHIR to HL7 schema extension.  We want to be able to create some common sender transforms that can be reused and tweaked for other senders as well.  This is a similar use as compared to the COVID schemas.

### Dev Notes:
* This feature is probably the same extension process as in the FHIR to HL7 library, so reuse is possible, but maintain the library code separate from the rest of the RS code.
* Reference the design from #6761

### Acceptance Criteria
* An administrator can extend an existing UP sender transform schema.
* The UP Sender Transform extended schema can overwrite an element with the same element name in the parent schema.
* The UP Sender Transform extended schema can add new elements with names that are not defined in the parent schema.
* The UP Sender Transform extended schema can include repeating elements (using child schema and resourceIndex).

**Comment by jimmyfagan** [comment]
Want to note here that this functionality was likely covered in previous tickets, so this ticket may just involve verifying the AC and writing additional tests if the existing ones are insufficient to demonstrate the AC.

**Comment by JessicaWNava** [comment]
Make sure you add tests in FhirTransformerTests to verify each of the acceptance criteria.
