### ISSUE TITLE
[API] Mechanism for switching Database queries to replica (readonly) database

### ISSUE THREAD

**Issue by ahay-agile6** [CDCgov/prime-reportstream#7256]
ReportStream Production Replica - pdhprod-pgsql-replica.postgres.database.azure.com
ReportStream Staging Replica - pdhstaging-pgsql-replica.postgres.database.azure.com (guessing)

## Problem Statement:

Most of the "experience" features on the ReportStream front-end are "readonly" operations on the database.
We are currently connecting to the prodcution's "real" databse that is "read-write" and is used for _**every**_ service in ReportStream.
This causes our "readonly" database queries to be unnecessarily slow to the point where they may timeout.

Our proposal is to use the "readonly" replica version of the Database when we have these types of operations, which will hopefully improve query return times.

## Acceptance Criteria
- [ ] Mechanism in API to switch to "readonly" replica database queries in the DataAccess class (or wherever we are making queries to the database in the back-end)

## TO DO:
- [ ] simulate primary-replica database infrastructure on local environment (the database username is the same as the primary, and the database name is "-replica" at the end). Note: This is tricky because we use docker container...
- [ ] Because of the note above, do we need to add this architecture to the docker services makeup?
- [ ] create a mechanism to switch to the "readonly" database for database queries (either from the API or in the database access layer itself for most queries?)

## Progress

Examples from Aurora: https://github.com/CDCgov/prime-reportstream/pull/7584/files

**Comment by HeatherRienks** [comment]
More info needed from Platform Team before merging

**Comment by HeatherRienks** [comment]
Per 12/12/22 meeting, we will re-evaluate this effort

**Comment by arnejduranovic** [comment]
This ticket does not appear to actually be a requirement for MessageTracker? Need confirmation from the O&O team, probably?

**Comment by chris-kuryak** [comment]
@stephenkao @kevinhaube See Arnej's comment above. Do you think we can close or remove this ticket from Single Message MVP?

**Comment by arnejduranovic** [comment]
This ticket is considered "obsolete" by the Platform team and there is no plan to implement this anytime soon. More investigation is required by the Platform team to determine if this ticket will provide any real value to the application.

**Comment by stephenkao** [comment]
I agree with @arnejduranovic closing this ticket.  The read-only operations could potentially be useful in the future, but it's not a stepping stone for the Message Tracker epic, and it's not a silver bullet for any performance issues we may be currently experiencing.  In any case, it's up to Platform to prioritize/deprioritize as needed, so I'm gonna close this for Experience :)
