### ISSUE TITLE
RI - Error Messages

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7264]
## Problem statement

Errors/ Failures from 11/3:

Json Garret from RI is requesting that we point back to NBS TEST to avoid the failures in PROD when making these adjustments to avoid the overflow of failure reports in the production environment.  Once we can verify the fix is complete, we can then point back to NBS PROD and send all backlogged results.

## What you need to know

Processed Time: 11/3/22 6:01 PM
Status:  Failure
Message ID: `9064574a-cdce-4e95-9d9e-7526aff5464c-6`
Reporting Facility:  Advanced Molecular Diagnostics
Accession #:  `9064574a-cdce-4e95-9d9e-7526aff5464c`
Exception Text:  Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

Processed Time: 11/3/22 6:01 PM
Status: Failure
Message ID:  `eca11338-1388-455e-8c41-e8ca11bb88af-6`
Reporting Facility:  Advanced Molecular Diagnostics
Accession #:  `eca11338-1388-455e-8c41-e8ca11bb88af`
Exception Text:  Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

Processed Time:  11/3/22 6:01 PM
Status:  Failure
Message ID:  d`912e991-fca4-4af1-9db5-6a02c2f2d451-6`
Reporting Facility:  Advanced Molecular Diagnostics
Accession #: `d912e991-fca4-4af1-9db5-6a02c2f2d451`
Exception Text:  Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

Processed Time: 11/3/22 6:01 PM
Status: Failure
Message ID:  `09f3e969-8837-4d1b-afec-9ef468375644-6`
Reporting Facility: Advanced Molecular Diagnostics
Accession #: `09f3e969-8837-4d1b-afec-9ef468375644`
Exception Text: Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

Processed Time:  11/3/22 6:01 PM
Status: Failure
Message ID:  `d82d6513-528d-48b6-b48d-7fd15952a341-6`
Reporting Facility: Advanced Molecular Diagnostics
Accession #: `d82d6513-528d-48b6-b48d-7fd15952a341`
Exception Text:  Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

Processed Time: 11/3/22 6:01 PM
Status: Failure
Message ID: `6e242c47-4b54-4532-9b60-dc1207e71cbf-6`
Reporting Facilty:  Advanced Molecular Diagnostics
Accession #: `6e242c47-4b54-4532-9b60-dc1207e71cbf`
Exception Text: Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

Processed Time:  11/3/22 6:01 PM
Status: Failure
Message ID: `a8657d98-454c-4110-9b08-12d37133969f-6`
Reporting Facility: Advanced Molecular Diagnostics
Accession #: `a8657d98-454c-4110-9b08-12d37133969f`
Exception Text:  Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

**Comment by BerniXiongA6** [comment]
@oslynn how many points are left on this?

**Comment by oslynn** [comment]
All messages below need to be resent to RI production again.

Message_id/Accession #: 9064574a-cdce-4e95-9d9e-7526aff5464c
Message_id/Accession #: eca11338-1388-455e-8c41-e8ca11bb88af
Message_id/Accession #: d912e991-fca4-4af1-9db5-6a02c2f2d451
Message_id/Accession #: 09f3e969-8837-4d1b-afec-9ef468375644
Message_id/Accession #: d82d6513-528d-48b6-b48d-7fd15952a341
Message_id/Accession #: 6e242c47-4b54-4532-9b60-dc1207e71cbf
Message_id/Accession #: a8657d98-454c-4110-9b08-12d37133969f

**Comment by shy2cdc** [comment]
Good Afternoon Ott,

Wondering if you had any update in regards to this at all at this point in time?

Thank you,
Jason Suchon

**Comment by oslynn** [comment]
After everything is good and gets confirmed by RI.  I will resend all the failed messages back to them.

**Comment by oslynn** [comment]
Got response from RI (Jason Suchon) said all messages get to their production feed are good.  Now, it is time to gather all failed messages and resubmit to their prod.
