### ISSUE TITLE
NJ - ProPhase: Error in Rhapsody Route in PRODUCTION

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#7265]
njelr.admin@doh.nj.gov - Mike Firkser

Please note the errors below in your ELR File: covid-19-7bff3bf2-0fd2-475a-835d-7b0e96cf5422-20221104134158.hl7 

ORC-12.1 and OBR-16.1 are filled with 255 pound signs (#) and ORC-12 and OBR-16 contain “Unknown” for provider names.

In addition PROPHASE HAS NOT BEEN APPROVED TO MOVE TO OUR PRODUCTION ENVIRONMENT!!!   DO NOT SEND ANY MORE FILES TO OUR PRODUCTION ENVIRONMENT UNTIL YOUR ONBOARDING PROCESS IS COMPLETE!
 

Thank you,
Mike Firkser
Technical Lead - NJDOH ELR Team
NJELR.Admin@doh.nj.gov

**Comment by oslynn** [comment]
I notified ProPhase not to send any message to NJ until the onboarding is completed.   Sharon also responded to NJ email and notified them.
