### ISSUE TITLE
Fresno County - Duplicate Records

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7266]
## Problem statement

Issue reported by Logan Dambrino from Fresno County Department of Public Health.

There seems to be an issue with Simple Report’s data transmissions to CalREDIE over the last 2 weeks.
It appears that slightly altered duplicate labs were submitted by Simple Report to CalREDIE (2 per actual lab submitted to Simple Report), both with the same accession number and all other info, except that the collection dates are a day apart. These are showing incorrect lab submission numbers, and throwing our numbers off a bit. This appears to not only have effected Fresno County Public Health and Jail lab entries (we are using the CSV uploads), but also everyone else's in the area who are not using CSV uploads. Please see the attached spreadsheet for more info.

[https://app.zenhub.com/files/304423150/c8fca5f8-62c9-47ea-9a57-92ee186f1c80/download]

## What you need to know

Comments by SLIU: I checked the SimpleReport CSV Uploader data going to Reportstream and found no duplicates being sent to reportstream.

ReportID: `c13757a4-8efd-4fdc-95b4-0cf92c5402e4`

About the same time, the “Report Source” for us changed from CSV-Simple Report, to ELR- CDC Simple Report. I am not sure if this is connected but is something we noticed.

I am not sure what exactly we can do about this. We are hoping that perhaps we can have Simple Report submit a “Correction to Results” lab for these that may supersede these labs, or that we can have this issue correct for the future and deal with the duplicates ourselves. We are open to further guidance from Simple Report or the CDC.

We also are hoping Simple Report will contact the other providers in the community to notify them of the error and work with them to correct it, or if they will not notify us so we can (if they do not, I can/will reach out).

Dr. K, until we have this sorted out, we are probably going to go back to using CalREDIE-MLR until we can make sure there are no further errors. Based on what Maggie has found, there seem to be only about 20 or so positive labs that were affected, the rest are negative, so it should not interfear too much with investigations or positivity rates (I hope) at this time.

**Comment by BerniXiongA6** [comment]
Hey @brandonnava this one is a couple weeks old so would be good to bring this up in a backlog refinement. Thanks! cc: @sliu1000 @brick-green

**Comment by sliu1000** [comment]
SimpleReport requesting an update on the status on the below:

From: CDPH CalREDIEELR <CalREDIEELR@cdph.ca.gov>
Sent: Monday, November 28, 2022 6:22 PM
To: Light, Megan (CDC/DDID/NCEZID/DPEI) <wpa8@cdc.gov>; Garner Franklin, Leslie (CDC/DDPHSS/OD/HITSSU) (CTR) <rnx3@cdc.gov>; Wallace, Jayna (CDC/DDPHSS/OD/HITSSU) <tof4@cdc.gov>; Judd, Michael (CDC/DDPHSS/OD) <vuj4@cdc.gov>
Subject: FW: SimpleReport Reporting Error

Hi Simple Report staff,

I’m forwarding this email to you from one of our submitters. Can you please take a look at the content and let us know how next steps for correcting this?

 -Kindly,

Jocelyn

From: Andrade, Margarita <maandrade@fresnocountyca.gov>
Sent: Monday, November 28, 2022 1:34 PM
To: CalREDIEHelp (CDPH-DCDC) <CalREDIEHelp@cdph.ca.gov>
Cc: Pena, Marlene <mapena@fresnocountyca.gov>; Koch-Kumar, Stephanie <skochkumar@fresnocountyca.gov>; ldambrino <ldambrino@fresnocountyca.gov>
Subject: SimpleReport Reporting Error

Good afternoon, On November 3rd, we discovered an issue with Simple Reports data transmission that occurred between 10/31/2022-11/1/2022. It appears that slightly altered duplicate labs were submitted by Simple Report to CalREDIE (2 per actual

Good afternoon,

On November 3rd, we discovered an issue with Simple Reports data transmission that occurred between 10/31/2022-11/1/2022.

 It appears that slightly altered duplicate labs were submitted by Simple Report to CalREDIE (2 per actual lab submitted to Simple Report), both with the same accession number and all other info, except that the collection dates are a day apart. The data alteration only affected incidents submitted from our Fresno County Public Health Laboratory via CSV file. All other locations who submitted via Simple Report had 2 submissions of identical labs.

After discovering this issue we promptly reached out to the Simple Report Support Center to see if they could assist with a correction to the results however we have heard back from them.

No other data has been affected since the first issue occurred, we have submitted multiple CSV files and they all transmit properly.

How would you suggest that the data be resolved? In total there are 840 incorrect negative labs within CalREDIE.

Thank you for your time,

Margarita Andrade
Program Technician II
Division of Epidemiology, Surveillance, & Data Management
Fresno County Department of Public Health
maandrade@fresnocountyca.gov
Phone: (559) 600-6889 | Fax: (559) 600-7607

**Comment by brandonnava** [comment]
@sliu1000 to check in metabase if need to resubmit

**Comment by sliu1000** [comment]
Per Bricks direction, I confirmed each accession number only was one record.  The last step is to check if there was any manual entry from our end that may have caused the duplicates.  We asked CA State for the file names of the file.  Once we have the file names, we will be able to determine if we sent any duplicates via manual submission.

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 @brandonnava look into this via email thread cc: @brick-green

**Comment by BerniXiongA6** [comment]
@sliu1000 I tried checking the RS inbox to see if this issue was resolved, but couldn't find the email thread. Can you confirm?

**Comment by sliu1000** [comment]
@BerniXiongA6 It should be under:  STLT Support/California/Support Queue

**Comment by BerniXiongA6** [comment]
Hey @brick-green -- could you check and see if we ever got file names from CA state as our last step in resolving this ticket? I checked the RS shared inbox and couldn't find an email. I also checked my inbox and didn't see an email either. Is it possible that you or @sliu1000 got emailed without a cc: to me? What I'm looking for is whether CA state send us file names so that we can determine whether we sent any duplicates via manual submission? cc: @brandonnava

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 @sliu1000 -- make sure this is handled before closing / before BX leaves -- determine if follow up is needed cc: @brick-green

**Comment by BerniXiongA6** [comment]
Hey @brandonnava and @sliu1000 and @brick-green -- you might want to ask customer support to check the shared inbox since I was unable to locate any emails with "file names" from CA state. Please see my note from 3 weeks ago above, let's make sure to close the loop on this before closing the ticket.

**Comment by brandonnava** [comment]
@brick-green would this get solved as part of solving the new accession numbers tickets?

**Comment by brandonnava** [comment]
Closed unless resurfaced
