### ISSUE TITLE
Design UP: Managing Translation Schemas

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#7275]
### User Story:
As ReportStream, I want to provide an easy way for an end user or engineer to manage translation schemas in the universal pipeline without having to redeploy the app.

### Description/Use Case
Presently, the HL7 -> FHIR, FHIR -> HL7, and FHIR->FHIR schemas are stored as files in the repo.  Any changes to those schemas need to be made as a PR, merged then deployed to production.  We want the UP schemas to be stored in such a way that it does not require redeploying any part of the application, as that process can be lengthy. To do this, however, we need to establish not only how to implement storing and changing these schemas, but also the process on how to update them. 

**NOTE:** The COVID schemas on the legacy pipeline are also stored as resources in the repo, and should also be considered, but should NOT limit or prevent us from designing a good solution. If our best solution cannot be applied to COVID schemas, then that should be made clear and accepted.

### Risks/Impacts/Considerations
* Potential performance impacts must be considered

### Dev Notes:
Note that the settings for senders and receivers are stored in the database, so they could be used as a template on how we handle the schema updates, IF we determine storing the schemas in the database is the best solution.

* Analyze the process and tools available to manage the organization settings in the `setting` table.  Notice how it supports versioning! This can be used as a template for how we handle the schemas.
* How do we store the schemas in the database, or somewhere else, so we make it easy for the software to read/write them.
* Most likely we will need an API to manage the schemas, so you will need to design that as well
* How do we let a user (end-user or engineer) manage the schemas, so it is not burdensome to read/update them.  Note that having child schemas could be a burden to a user to read/update them. Do we need a "merge" functionality at some level, either in the UI, endpoint, or storage location itself?
* Need to consider how a particular solution will effect the translation library (FHIR -> HL7)

### Acceptance Criteria
* Document and design how we can update schemas without having to redeploy the app
* Document the process on how the schemas will be updated (api design).
* Get buy-in from the Experience team on the design. They will probably want to create a UI for what we design.
* Get buy-in from the Engagement team on the design, they will be users of our api/UI.

**Comment by PatriciaPerozoUSDS** [comment]
Needs a re-write. We aren't sure DB is the right storage choice. Cle hates jsonb. He now owns the re-write of this ticket. @clediggins-usds

**Comment by arnejduranovic** [comment]
> Needs a re-write. We aren't sure DB is the right storage choice. Cle hates jsonb. He now owns the re-write of this ticket. @clediggins-usds

Rewrote the ticket, ready for grooming.
