### ISSUE TITLE
[Prototype] Create a prototype for codified error messages

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7277]
## Problem statement

The API error messages now are string-based, and while some contain useful metadata, all contain a hard-coded string error message. We will codify these errors, so that if the given error string does not suit the need, a translation layer may be applied to convert them to UI-friendly messages, or into another language for multi-lingual support.

### From recent error updates

> It also does not fix messages and stack traces from external libraries. Notably, the following error message which was requested to change:
>
> > Error parsing HL7 message: ca.uhn.hl7v2.validation.ValidationException: Validation failed: Primitive value '08112022' requires to be empty or a HL7 datetime string at PID-29(0)
>
> This, as well as the stack trace presented by the phone number parser library, are great candidates for an MVP implementation of Codified Error Messages (aka, the Error Message Makeover!)

Based on this knowledge, let's base this prototype on these error messages we wish to translate for the UI. See Florence's mural for more info: https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1666190212832/25f971cebb2d289837352dc406cb379ce362068c?sender=ua604735c5cf1162b042a4310

### Use cases

- Unifying how we deal with errors and error messages coming from various external libraries through ReportStream (i.e. HL7 validation package, HAPI, etc.)
- Support for various spoken languages
- Contextual mapping of codes to messages

Pipeline is a heavy user of our Kotlin errors, so we should design additively rather than overhauling the current pattern.

## Acceptance criteria

- [ ] Error codifying prototype is presented at eng sync
- [x] `ValidationException` is caught and the error received by the front-end has a string message **and** error code. That code translates to a clean message in the UI.
- [x] Invalid Phone exception is caught and the error received by the front-end has a stiring message **and** error code. That code translates to a clean message in the UI.

## To be answered

- [x] Error code nomenclature, how do we pack inferable metadata into a code?? (Ex: validate-hl7-format-datetime, or ex:616-007) This doesn't have to be complicated, it just has to make sense! 😄 
- [X] ~~Where do we first implement this change?~~
- [X] ~~What's the MVP scope?~~ We will use the InvalidPhone stack trace and ValidationException seen above as MVPs for supplying error codes

**Comment by kevinhaube** [comment]
Just a note to later me: 

If you forgot, we thought to do this as a proposal because error messages AND this functionality could be usefule to the wider team. We as Experience, though, want to take ownership of this error code standard by defining what it'll look like rather than just bring the idea up for wider team discussion.

**Comment by HeatherRienks** [comment]
@kevinhaube - pls add in links to relevant info.

**Comment by penny-lischer** [comment]
1. Updated the InvalidHL7Message() method to take an optional ‘ErrorCode’ string 
2. Created an enum ‘ErrorCode’ to allow for consistent nomenclature and containment of the error codes to be passed into the InvalidHL7Message() method.
3. The front-end can then use the 'ErrorCode' to display a friendly message. In FileHandlerMessaging.tsx -> ErrorRow we call the ErrorCodeTranslation enum which maps the error codes to a friendly message.

**Comment by kevinhaube** [comment]
@HeatherRienks I will go ahead and label this ticket with `release_notes`, bet let's sync and come up with how it's worded. I want to make sure these are communicated via release notes as experimental. These `code`s are still in a prototype phase, subject to change, and we do not have versioning or feature flags in place for the API.

Once we have a system in place to roll out stable error codes in production, these codes will also be made available with details in the API Programmer's Guide; a process we're considering as we work through the prototype phase. :)
