### ISSUE TITLE
Receiver checks do not support newer transports

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#7284]
The CheckFunction and CRON job that drives the PicklesNDogs dashboard only support checking SFTP connections. 

We should add support for the newer REST Receivers.

- [ ] Figure out what it means to test a REST Receiver endpoint. For SFTP, it means connecting and doing a "cd" into the directory. (For CheckFunction it actually uploads a file, but it sounds like we should avoid generating junk files for production).
- [ ] Update `scheduled-remote-connection-check` to determine which Receivers are REST and run the new checking function.
- [ ] Add support to `checkreceiver`. API caller should not need to know/care which underlying transport is being used, the function should determine it.

**Comment by TomNUSDS** [comment]
@greene858 I'm assigning to you for now as a heads-up only, but it should go into the normal sprint cadence.

**Comment by brandonnava** [comment]
@greene858 Any update here?

**Comment by oslynn** [comment]
Approved by Jim Duff and Merged.
