### ISSUE TITLE
Research steps needed to publish FHIR to HL7 library as new repo

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#7288]
### User Story:
As a ReportStream, we want to publish the FHIR to HL7 library as a new open source library, so others can use it in their projects.

### Description/Use Case
The FHIR to HL7 library has unique functionality that can be useful for the healthcare community.  We want to move the code to its own repo and make it open source, but we need to identify all the steps needed and the process to get there.  We also need to take into account how we will deal with inquiries, bugs, suggestions, etc.

### Risks/Impacts/Considerations
* External users may generate extra work for us with inquiries, questions, tickets, etc.
* Need to be able to make changes to the library in a safe way, so we do not break other people's work.

### Dev Notes:
* 

### Acceptance Criteria
* Document the steps needed to migrate the FHIR to HL7 library to be in its own repo and automatically publishing a JAR to distribution sites like the Maven repo.
* Document how we would handle inquiries, bugs, questions coming from external users.
* Document how we would handle updates to the library (e.g. how do we increment version numbers, update release notes, etc.)
* Document what documentation is needed before this library goes live.
* Document the documentation as to what documents are needed to be created with documentation tickets, so to document all the documentation work. ;D
* Document any CDC specific requirements for maintaining this separate library as a separate repo.

**Comment by jpandersen87** [comment]
Current conversations in regards to my gradle plugin (https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/7787) seem to be leading towards treading some of this ground in regards to moving to a new repo. I will try to leave notes on it in the future with steps taken if any.

**Comment by jpandersen87** [comment]
To request creation of a new repo under CDCGov you must fill out this O365 form: https://forms.office.com/Pages/ResponsePage.aspx?id=aQjnnNtg_USr6NJ2cHf8j44WSiOI6uNOvdWse4I-C2NUNk43NzMwODJTRzA4NFpCUk1RRU83RTFNVi4u . It requires you to have a CDC O365 account. You'll be asked general information about the project as well as what users+role you want initially added to it. I followed @stephenkao 's recommendation of requesting people across the teams as admins. Turnaround time was half a day.

**Comment by PatriciaPerozoUSDS** [comment]
@jpandersen87 Thank you! This was super helpful. The form is maybe the most entertaining form I've seen so far at the CDC. A+
