### ISSUE TITLE
Possible vulnerability

### ISSUE THREAD

**Issue by snesm** [CDCgov/prime-reportstream#7297]
## Problem statement

Possible vulnerability discovered by Snyk code analysis.

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- Snyk [finding](https://app.snyk.io/org/prime-reportstream/project/980e6e3c-7075-4866-b014-efa3b037bfa1#issue-b755fec9-09b2-4baa-83fd-6c0173f70734)

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by HeatherRienks** [comment]
@kevinhaube - FYI,  @snesm has flagged this for further review. Thanks!

**Comment by kevinhaube** [comment]
Hey! #6523 removes the final use of this method, and #6527 will remove the dormant remaining code thereafter. 👍🏼

**Comment by kevinhaube** [comment]
The above PR solves this!

**Comment by snesm** [comment]
Snyk scanning agrees!  Thank you!
