### ISSUE TITLE
[FeatureFlags][API] Storing Organization-level Feature Flags

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7301]
## Problem statement

To effectively test over zoom with clients (and restrict organizations from features not ready yet) we want to allow access to a feature only to select organizations in ReportStream for a limited time. We would need to extend our current React app session capabilities, and allow the database to maintain a record of an organization's available features.

## What you need to know

Currently we use Okta to authenticate users on the front-end. We integrate through their packages for the web and React, and receive info that's interpreted into a session object and provided by the `SessionProvider` to the ReportStream web app. Scopes were considered for this work, but Okta's overhead and the benefit being front-end only for its integration led to a decision not to use the approach. Additionally, conversations and opinions have always trended towards on-prem auth rather than relying on Okta.

Currently we use a FeatureFlag context to provide feature flags to the ReportStream application.

Currently, no field exists on an Organization object to set feature flags, but in a Slack thread, Cle provides insight on two ways we can do this:

> Kevin H. : So, if we hoped to achieve the goal of piloting a new feature in production with feature flags for specific organizations, would the OrganizationSettings make sense as to where we’d integrate that array of strings? I’m seeing a need for limited releases of features to only some senders or some receivers in the near and distant futures, and would like to avoid another dependence on Okta groups or claims if we can.
>
> Cle D. : I'd say yes, the 'values' column in the settings table for the Organization seems to be a good spot for feature toggles, assuming everyone who logs in is positively identified to belong to a specific organization. That way it could also support organization-level toggles or overrides for specific senders or receives that are part of that organization.
>
> Also could make two new tables called Feature and FeatureToggle, where Feature holds the list of available features with default toggle values and FeatureToggle is a many to many between Setting and Feature. This would get us away from 'an array of strings'  and give all the flexibility but with strongly typed data, but would take more setup and maintenance up front.

Feature Flags run on strings right now that are freely available to read in our repository. We should ensure no front-end user can mock permission to a feature through browser dev tool sleuthing. This may mean a Feature Flags table and ids, maybe delivering some kind of "scope or claim" for the front-end to parse as a UI permission, and then some kind of back-end check through our `AuthElement` before the page can load.

## Questions to answer

- Can this endpoint functionality be worked into any of our current settings endpoints? 
**OrgSettings should return these values**
- Do we need global switches for features as well? 
**Yes**

## Acceptance criteria

- [x] API call to return permissions for an organization
- [x] Feature Flags have global toggles
- [ ] PRIME Admin can update feature flag state (global, org)

## To do

- [ ] ...

**Comment by kevinhaube** [comment]
Should deploy 12/13

**Comment by HeatherRienks** [comment]
Per 12/19/22 Platform/Exp meeting, we will keep this ticket on hold until new tix are created and design work is completed.

**Comment by penny-lischer** [comment]
Closing due to new direction in approach via #7734
