### ISSUE TITLE
Edits to Account Registration Guide (in Resources, RS public site)

### ISSUE THREAD

**Issue by fmccaf1** [CDCgov/prime-reportstream#7307]
# Important Info

[Mural board](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1667328248835/9317b8b37c030fe0edae0b5c42fe5df48472f404?sender=ua604735c5cf1162b042a4310) with all findings from evaluation of resources [(#6689)](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6689)

If any of the screenshots provided below are two small to read, please refer to the Mural linked above. 

### 1. Update subheading text:
![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/700d00f1-f1d3-44e3-94ff-26d68068ae9a)

### 2. Add ability for user to jump down to other sections (put this above the blue box)
![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/23d2d206-e724-40d4-a0f7-e72a885ca4cf)

### 3. Change blue info text:
![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/885c7c9b-686d-47d5-85aa-8b57a878bbb9)

### 5. Small changes to text in step 3 and step 4:
![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/2643857a-4dba-4199-bae0-4f0e9114e640)

### 6. Remove Step 5 (Close window) and move updated text from that original Step 5 to live under iv. Click "continue":
![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/cadb6e80-8f10-4b53-b4da-8d417780ba4a)![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/ad9f9a9d-1e9b-4679-ac0c-f29a65b16a3f)

### 7. Update Step 6 text and make sure the numbering is correct (I think now this would be Step 5)
![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/11bfce7a-a80b-4be6-a816-027cfa7b30c9)

### 8. Keep multi-factor auth section but edit H2 text: Set up Multi-factor authentication
![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/9c750dae-7ae5-4afe-8f1a-6afcbbbfcc4b)

### 9. Add another section, starting with H2: "Account management"
![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/a41243b7-cdec-40c9-8604-c45b31c7bc3f)

**Comment by fmccaf1** [comment]
These updates must be preceded by the availability of SmartSheets and their corresponding forms from @sliu1000

**Comment by sliu1000** [comment]
@fmccaf1 I'm working on reviewing this today and tomorrow.

**Comment by sliu1000** [comment]
Comment1: Under account registration guide. I would put a blurb stating that reportstream is for API users only. If they are looking for manual report or CSV uploads to defer to SimpleReport.

Comment 2: Steps 3,4,5 do not apply here. Users are not able to create or activate an account prior to scheduling a kickoff meeting.  I would replace step 3 with a Calendly link to schedule a kickoff meeting. And/or (the onboarding YouTube videos).
