### ISSUE TITLE
CDPH CA - Missing Specimen and Result Data

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7319]
![thumbnail_image001.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/5769ac04-63b3-43eb-bcee-5060e4878462)## Problem statement

Received an email from Jocelyn San Nicolas at CDPH CA on 11/8/2022:

Some of the CDC SimpleReport ELRs are not populating the Specimen and Result dates for labs, those are missing from the Laboratory tab for the incidence, but the lab entry is filled out correctly in the Filing Cabinet. Below are 10 that Imperial has found so far & there may be more. Do you have any insight on this? Hoping that it is not due to the submitter cutting off the GMT offset in the MSH segment.

## What you need to know

Imperial county
CDC ReportStream-SimpleReport (CDPH000085)
Incident IDs provided in the last email but also including accession #s. Hope this helps, thank you

Accession #: `8c378dd2-c7e9-4f03-9495-a19b8ae061f3`
Incident ID:  156331222

`046fc1fb-53dc-41de-a670-512443f194fc
156331088

`0f315703-ed17-4793-9e1e-b7f0cafc9596`
156331138

`6b591640-85ad-4671-9c3d-228c1063836e`
156331155

`3be736d7-543f-4b6a-84b6-b39343f4c06d`
156331147

`73f4af7f-f394-4b9a-9e94-200f150fee56`
156331107

`9a165087-e0a2-44ea-a031-118cbacd3fc9`
156331162

`e499c10f-bcfb-454c-95e7-b0e02c436c4f`
156331167

?
156331182

`5a90659c-fbe6-4b68-83bf-b5b1ad62ce6e`
156331233

## To do

Assign to an Engineer

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 let's add a Sprint 56 to this ticket.

**Comment by GilmoreA6** [comment]
This appears to be an internal issue to CA. For the messages being sent to CA we are populating the following date/time fields in the HL7 message for the listed accession numbers above. MSH-7 (date/time of message), ORC-15 (order effective date/time), OBR-7 (observation date/time), OBR-8 (observation end date/time), OBR-22 (results rpt date/time), OBX-14 (date/time of observation), OBX-19 (date/time of analysis), SPM-17 Specimen collection date/time), SPM-18 (specimen received date/time). All the above date time stamps are being sent with format yyyymmddhhmmss+/-zzzz (offset).

**Comment by sliu1000** [comment]
@GilmoreA6 

Emailed the user to let them now that we are sending all those values over to them and to please check their internal system.  Also, advised them to reach out to us if they'd like to schedule a call to discuss further.

**Comment by Jcavallo7** [comment]
User provided an update that states:

"Hello,

 

I am following up on this request and the possible mismatch with the time in MSH 7. Accession numbers were provided on 12/1 as requested. Can you please send an update to this inquiry.

 

Thank you!

Jocelyn

**Comment by sliu1000** [comment]
Hi Jocelyn,

Thank you for your email.  We are still waiting on the CalConnectintegration team to provide us with the filenames per the accession numbers.

Best regards,

Sharon
The ReportStream Support Team
Contact us at reportstream@cdc.gov
Support hours:  8:00 am through 9:00 pm Eastern time
Monday-Friday, excluding US public holidays

From: CDPH CalREDIEELR <CalREDIEELR@cdph.ca.gov>
Sent: Thursday, December 8, 2022 7:11 PM
To: Report Stream (CDC) <reportstream@cdc.gov>; SimpleReport Support (CDC) <simplerpt_support@cdc.gov>; Kerry, Laura (CDC/DDPHSS/OD/HITSSU) <tse0@cdc.gov>; King, Laura (CDC/DDPHSS/OD/HITSSU) (CTR) <rnv9@cdc.gov>; rnv2@cdc.gov <rnv2@cdc.gov>; Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR) <rut5@cdc.gov>
Cc: CalConnect Integration@CDPH <CalConnectIntegration@cdph.ca.gov>
Subject: RE: Possible mismatch with Universal Time and Local Time.
 
Hello,

I am following up on this request and the possible mismatch with the time in MSH 7. Accession numbers were provided on 12/1 as requested. Can you please send an update to this inquiry.

Thank you!

Jocelyn


From: Report Stream (CDC) <reportstream@cdc.gov>
Sent: Thursday, December 1, 2022 12:11 PM
To: CDPH CalREDIEELR <CalREDIEELR@cdph.ca.gov>; SimpleReport Support (CDC) <simplerpt_support@cdc.gov>; Kerry, Laura (CDC/DDPHSS/OD/HITSSU) <tse0@cdc.gov>; King, Laura (CDC/DDPHSS/OD/HITSSU) (CTR) <rnv9@cdc.gov>; rnv2@cdc.gov; Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR) <rut5@cdc.gov>
Subject: Re: Possible mismatch with Universal Time and Local Time.
 
Please find attached the accession numbers. The ReportStream Support Team Contact us at reportstream@ cdc. gov Support hours: 8: 00 am through 9: 00 pm Eastern time Monday-Friday, excluding US public holidays From: CDPH CalREDIEELR <CalREDIEELR@ cdph. ca. gov>

Please find attached the accession numbers.
 
The ReportStream Support Team
Contact us at reportstream@cdc.gov
Support hours:  8:00 am through 9:00 pm Eastern time
Monday-Friday, excluding US public holidays

From: CDPH CalREDIEELR <CalREDIEELR@cdph.ca.gov>
Sent: Thursday, December 1, 2022 3:03 PM
To: Report Stream (CDC) <reportstream@cdc.gov>; SimpleReport Support (CDC) <simplerpt_support@cdc.gov>; Kerry, Laura (CDC/DDPHSS/OD/HITSSU) <tse0@cdc.gov>; King, Laura (CDC/DDPHSS/OD/HITSSU) (CTR) <rnv9@cdc.gov>; rnv2@cdc.gov <rnv2@cdc.gov>; Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR) <rut5@cdc.gov>
Subject: RE: Possible mismatch with Universal Time and Local Time.

Hello,
 
Thank you for looking into this. I’m unsure of how this became an issue about duplicates? This ticket was originally opened in efforts to address the ‘future’ time in MSH 7. Looping back in the CalConnect team CalConnectIntegration@cdph.ca.gov Do you have any specific accession numbers that you can provide for investigating this issue?


-Jocelyn

From: Report Stream (CDC) <reportstream@cdc.gov>
Sent: Thursday, December 1, 2022 11:53 AM
To: SimpleReport Support (CDC) <simplerpt_support@cdc.gov>; CDPH CalREDIEELR <CalREDIEELR@cdph.ca.gov>; Kerry, Laura (CDC/DDPHSS/OD/HITSSU) <tse0@cdc.gov>; King, Laura (CDC/DDPHSS/OD/HITSSU) (CTR) <rnv9@cdc.gov>; rnv2@cdc.gov; Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR) <rut5@cdc.gov>
Cc: Meesey, Jill@CDPH <Jill.Meesey@cdph.ca.gov>
Subject: Re: Possible mismatch with Universal Time and Local Time.
 
Hello, The engineering team has reviewed this issue and found no duplicates being sent with the accession numbers provided. The second part of this review will require the filenames of those accession numbers in question. This will help us.

Hello,

The engineering team has reviewed this issue and found no duplicates being sent with the accession numbers provided.  The second part of this review will require the filenames of those accession numbers in question.  This will help us further confirm whether we did or did not send duplicates.


Best regards,

Sharon

The ReportStream Support Team
Contact us at reportstream@cdc.gov
Support hours:  8:00 am through 9:00 pm Eastern time
Monday-Friday, excluding US public holidays

**Comment by sliu1000** [comment]
Hi @GilmoreA6, please find below the updated information from CalConnection:

For the incident reported, the CR Incident ID is 158049013
accession number: cc2bd7ec-825b-4d78-8dcf-ea435734b04e

file name: CR_202211241839cc2bd7ec825b4d788dcfea435734b04e.hl72022-11-24-18-39-27-641.xml

However, we have reason to believe that this issue affects many other labs submitted through Simple Report.  Unfortunately it is a little difficult for our team to grab the files since they are not integrated with other system; we see the downstream impact of the lack of Date Specimen Collected imported into CalREDIE in our system.

Please let us know if you need any other information.

Best,

Dani

**Comment by GilmoreA6** [comment]
@sliu1000 I was under the impression that the issue was *missing* timestamps in the data and that's what we had investigated. It appears that with this most recent information the issue is that they are receiving future timestamps, which is absolutely true since we send it as UTC. We have an option where we can convert the timestamps into their local time which sounds like what they want us to do. Can you forward me the email chain so I can respond and verify that is what they want?

**Comment by GilmoreA6** [comment]
sent email to RS, CalConnect & CalRedie:

Hi all,

Apologies for the delay as two separate issues got crossed. In regards to the timezone issues. We were sending results with a UTC timezone and the proper UTC offset (+0000). Since it looks like this was causing issues when the UTC time was rolling over into the next day I have made a change on our side that will send all timestamps as PACIFIC time and appropriate offset (UTC-0800). Please let us know if this resolves the issue. If needed we can also send in PACIFIC time without the offsets.

Thank you,

James
