### ISSUE TITLE
CO - Error Message Received

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#7322]
From Nancy Kesco - nancy.kecso@state.co.us

Smartsheet Question Submitted:
When errors are detected in the files that Colorado receives, we send an error message to ReportStream@cdc.gov.  "Today we received an auto reply that asks us to find a different way to report.  What email address should we be using to notify you of errors in the files that you are sending to us?"

Message ID:
V2020-07-01_Results+3+20221108

**Comment by BerniXiongA6** [comment]
@brick-green I didn't know that error message automatically go to the RS shared inbox, what do you think? cc: @sliu1000 @brandonnava

**Comment by brick-green** [comment]
It sounds like CO wants to continue sending to an inbox. The shared inbox makes the most sense. So either we tell CO they can just ignore the auto reply emails or we turn off the auto reply?

**Comment by sliu1000** [comment]
I will turn off the auto reply.

**Comment by BerniXiongA6** [comment]
Follow @sliu1000 -- what does that mean if we turn off auto-reply for its intended purposes? Or could we modify the language in the auto-reply?

**Comment by BerniXiongA6** [comment]
Hey @sliu1000 can we close this ticket?
