### ISSUE TITLE
Add Senders hook

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7328]
## Problem statement

Organizations in ReportStream have "services", such as Sender services and Receiver services. These are what we call "Senders" or "Receivers" internally for short. Because an Organization may have one, the other, or both, and they are required parameters for many features, we should have an way to fetch and cache the Organization-specific Senders and Receivers.

## What to know

- We're going to be disabling redundant refetches as part of [this changeset](https://github.com/CDCgov/prime-reportstream/pull/7928/files#r1080627826)

- We already have a [`useOrganizationReceivers` hook](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/hooks/UseOrganizationReceivers.ts), and we have [the endpoint configuration to fetch Senders](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/config/endpoints/settings.ts#L65).

To that point, we can add a hooks:
- `useOrganizationSenders` to fetch an Organization's Senders

## Acceptance criteria
With this hook:
- [ ] Senders are fetched once for the current Organization when needed

**Comment by chris-kuryak** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/7328?planning-poker) with Zenhub @jpandersen87 @kevinhaube @penny-lischer

**Comment by kevinhaube** [comment]
Per discussions leading to creeping scope on #7923 and #8021 the approach to solving the above Problem Statement needs refinement before engineering work can continue. Adding `needs-info` label to indicate this @chris-kuryak @stephenkao

**Comment by stephenkao** [comment]
I'm going to clarify this ticket a bit.  Ultimately, I think what we need is a central hook to fetch both types of services whenever needed, and this fetch can be cached in the query cache based on the organization name.  It's unlikely for services to change throughout the lifetime of the app in the browser, and even if it does, we can just manually refetch or update the cache ourselves.

**Comment by stephenkao** [comment]
Closing for now -- we can create a new ticket when we have need of this functionality.  Will likely happen when we focus on Sender functionality in the future, but our focus is on Receivers for the next few quarters.
