### ISSUE TITLE
NJ - ORC-12.1 and OBR-16.1 consists of 255 Hashtags - Please resubmit

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7342]
**Describe the bug**

NJ - ORC-12.1 and OBR-16.1 consists of 255 Hashtags - Please resubmit

Location of Error in Message
PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.OrderingProvider[0].IDNumber

Error Description
Field too long: 255 > 15

**Impact**
Not able to submit the results with the incorrect data.

**Expected behavior**
Submission with correct data with a field length less than 15 characters

**Screenshots**
File ID: 5442224
Message(s) within the file "`CDC_PRIME_covid-19-d6e9d836-351a-4d35-968d-d7150e4b1a87-20221109144202.hl7`" were in error on route (2) ELR-Validate 2.5.1

[https://app.zenhub.com/files/304423150/c5a0a022-d45b-44f8-92fa-3b26f5b8f49d/download](https://app.zenhub.com/files/304423150/c5a0a022-d45b-44f8-92fa-3b26f5b8f49d/download)

File ID: 5446235
Message(s) within the file "CDC_PRIME_covid-19-36d0b4aa-827b-44fb-bbba-4834b72697a3-20221110144102.hl7" were in error on route (2) ELR-Validate 2.5.1

**Comment by rnz6** [comment]
Update from NJ: 

Please note the errors below in your ELR File: covid-19-4543aef5-d678-48ce-831e-1410c4f4d1b1-20221115144137.hl7

ORC-12.1 and OBR-16.1 are populated with 255 hashtags.

Please correct and resubmit.

Thank you,

Mike Firkser

Technical Lead - NJDOH ELR Team
NJELR.Admin@doh.nj.gov

**Comment by sliu1000** [comment]
Another one:

Please note the recurring errors below in your ELR File: covid-19-`6db3f44e-0440-4363-a724-8a07899abffe`-20221116144105.hl7

The issue with hashtags in ORC-12.1 and OBR-16.1 continues.  Please correct and resubmit.

**Comment by oslynn** [comment]
@sliu1000 ReportStream for NJ production feed is fixed.  It will truncate the ORC-12-1 and OBR-16-1 to the standard lengths accordingly.  Attached please find the list of patient_ids for SimpleReport to resubmit.  Please contact @emmastephenson for SimpleReport resend.

[https://app.zenhub.com/files/304423150/957f3961-b3cd-463c-9e86-86db8bdcce3e/download](https://app.zenhub.com/files/304423150/957f3961-b3cd-463c-9e86-86db8bdcce3e/download)

**Comment by emmastephenson** [comment]
@sliu1000 was this triggered by a CSV results upload or a traditional SimpleReport test? If it was a CSV upload, we'll need to contact the organization to resend it.

**Comment by sliu1000** [comment]
@emmastephenson Yes, its via CSV upload. I know that one of the organizations is Cirrusdx.  @oslynn Can you please confirm its for only one organization (Cirrusdx).
