### ISSUE TITLE
MA - ELR File Size Too Big

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#7343]
## Problem statement

ELR Batch File Size problem that involved one being cut into smaller files

## What you need to know

 User's name is Janice Grantner 
janice.Grantner@mass.gov

Email from Janice:

> Good Afternoon,
> 
> We are receiving these reports from Report Stream to the Massachusetts Department of Public Health. The facility that is sending them in CDC Prime-Atlanta, Georgia (Dekalb).
> 
> - Can you please review the size of these Prime files? We came across a file yesterday that was too big which needed to be split into multiple files. Yesterday file size was 5, 550KB (2096 messages) and we can only accept files up to 2.0MB. I have fixed and manually upload this file to our ELR Portal.
> 
> - A max file size constraint of 2.0 MB is imposed for HL7 251 messaging. We strongly recommend that you send <=400 messages in your batch. Multiple batch files can be transmitted each day based on reporting volume.
>  
> - _Additionally, this file (prime-20221109145115) was received with special characters within some of the patient names. Can you please review this issue? Also, we noticed several cases that were not Massachusetts residents. They should not be sent to us and should go the proper state."_ **(This bullet point is being handled under[ Issue # 7393](https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/7393) -- thx, BX)**

## To do
To review for file submission sizes and errors
- [ ] ...

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 @brandonnava create new ticket to break out hte data quality issues

**Comment by BerniXiongA6** [comment]
New ticket created for third bullet point -- [Issue # 7393](https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/7393)

**Comment by MauriceReeves-usds** [comment]
Updated the batch timing to be every two hours instead of once a day via the website console.

**Comment by BerniXiongA6** [comment]
Bullet points 1-2 are done per @brick-green

**Comment by rnz6** [comment]
Update from Janice: 

Hi Berni,

It is nice to meet you too. We will remove Adrian from our email list and add you Brandon, Brick and Sarah to the list. I have added my response under the questions.

 Currently, we route results to MA based on the Ordering Facility State or Patient State. If MA only wants results where Patient State = MA, we can make an edit to our filtering. Please confirm this is indeed how you'd like to proceed. (We've experienced that the majority of states want both Ordering Facility State or Patient State.)
Yes we want both of these but only if the patient state is in MA

As for the file in question, after downloading it, our engineer couldn't find any messages with special characters in the patient names. Could you provide us accession numbers with examples?
I will work on getting you the accession numbers for you and send them to you.

Thanks,

Janice Grantner 
Research Analyst
Division of Surveillance, Analytics and Informatics
Hinton State Laboratory Institute 
305 South Street, Boston, MA  02130  
Cell Phone: 781-223-6737
Confidential Fax: 617-983-6813 
Email: Janice.Grantner@mass.gov

**Comment by rnz6** [comment]
Re-opening issue: 

User response was from 12/6. Please advise.

**Comment by rnz6** [comment]
@LaFreda1 

User is asking for an update. Please see above email for reference.

**Comment by brick-green** [comment]
I still don't understand what the ask from MA is here. The file size issue was resolved by Mo on 11/23/22. 

@rnz6 What is MA asking us to do?
