### ISSUE TITLE
CO - Not Receiving Data from Secondary Feed "Co-phd.elr-secondary"

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7366]
## Problem statement

The state of Colorado is not receiving data from their secondary field.  They believe that their secondary feed is being directed to their test server.

## What you need to know

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/990011cf-ba75-47c6-b1eb-6d44121be321)

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/0c666772-f20c-4885-a744-cc4f8ee3b944)

## Acceptance criteria

- Colorado to start receiving the secondary data to their production server.

## To do

- Assign an Engineer to make this change.

**Comment by sliu1000** [comment]
@oslynn - Please resend these
ReportID
`ace09eb5-d932-48a9-b2cd-d1e300a3593e`
`4a7d5a83-fad3-44fb-b251-9fd208d7ddd3`
`42c665e2-fe7a-49f8-95e5-09e7fba299b9`

I still need to locate the other reportids but if you can find that would be awesome.

**Comment by oslynn** [comment]
@sharon, I will find it, don't worry.

**Comment by sliu1000** [comment]
@oslynn @GilmoreA6 
Background Information:
Secondary Feed was turned off on 10/24/2022. SR data was going to the Secondary Feed prior to that turn off. Ott will resend that data prior to the turn off.

**Comment by oslynn** [comment]
@sliu1000 I just resent 3 files with report_ids above to co-phd prod feed.  Files names are below:

covid-19-4a7d5a83-fad3-44fb-b251-9fd208d7ddd3-20221026193205.hl7
covid-19-42c665e2-fe7a-49f8-95e5-09e7fba299b9-20221026013037.hl7
covid-19-ace09eb5-d932-48a9-b2cd-d1e300a3593e-20221027193134.hl7

Will you please let CO know?
Thanks
