### ISSUE TITLE
San Juan Basin Public Health - Unable to download daily data

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#7372]
New request from Shandi Pritchett,  spritchett@sjbpublichealth.org at San Juan Basin Public Health:

"We are not able to download and csv data from our daily data therefore we cannot access any data. We have tried several times and multiple accounts and different computers. We use this data to manage our numbers and input our out of state patients."

**Comment by sliu1000** [comment]
Followed up with user to see if they are still having issues.

**Comment by sliu1000** [comment]
After further research this may be a bigger issue than login/reactivation.  We have two users from the same county have the same issue.   Not able to see daily data when they log into their reportstream account.

I suspect this has to do with the new CO San Juan Basin Public Health folder/feed.

User emails: tmacon@sjbpublichealth.org and sjbpublichealth.org 

@brandonnava  @BerniXiongA6  Please assign an engineer to make sure the data is flowing into the appropriate folder  for SanJuan user access on ReportStream website.

**Comment by sliu1000** [comment]
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/7a91cb05-2d93-482e-9f46-a5fd5777eb68)

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 will add back to Sprint Planning to assign engr for Sprint 56. cc: @brandonnava

**Comment by MauriceReeves-usds** [comment]
Reviewed Okta set up for Shandi and it looks correct. Settings in the app also look correct. Shandi is able to log in and sees the screenshot linked above when trying to access the Daily Data page. When I log in as an admin I am able to access the Daily Data page. We will need to tag in Experience to see why this is happening.

**Comment by MauriceReeves-usds** [comment]
Reached out to Experience 12.40 ET 23-Nov-2022

**Comment by brick-green** [comment]
@GilmoreA6 Can this be closed?

**Comment by GilmoreA6** [comment]
@sliu1000 Did San Juan report being able to access their downloads today? If so, we're good. All testing on our side didn't reveal any issues.

**Comment by sliu1000** [comment]
@GilmoreA6 I just check both users and it looks like they both signed in yesterday, everything must have worked for them as they didn't respond with any complaints.
