### ISSUE TITLE
Identify missing data in the Submission History API response for the UP data vs Covid pipeline data

### ISSUE THREAD

**Issue by PatriciaPerozoUSDS** [CDCgov/prime-reportstream#7379]
**User Story:**
As a sender, I expect to receive API responses in the same format containing the same information regardless of what pipeline I submitted messages to.

**Description/Use Case**
We need to review the API response for the submission history API to identify any missing data between the two pipelines.  We want to figure out if we are missing data or provide data in a different format that may confuse senders.

**Risks/Impacts/Considerations**
* Not all data needs to be the same between the pipelines, so need to research any differences before writing a ticket for it.

**Dev Notes:**

**Acceptance Criteria:**
* Document in this ticket the Submission History API response differences between the UP and the COVID pipeline.
* Brief the team on the differences and get buy-in on the work needed to make the responses the same.
* Generate new tickets for any work identified.

**Comment by JessicaWNava** [comment]
Universal Pipeline Response:
`{
    "id": "51c34757-7450-4f7c-9958-d3a36f9f3c8b",
    "submissionId": 1089,
    "overallStatus": "Delivered",
    "timestamp": "2023-01-11T23:16:54.598Z",
    "plannedCompletionAt": "2023-01-11T23:18:00.000Z",
    "actualCompletionAt": "2023-01-11T23:18:13.398Z",
    "sender": "ignore.ignore-full-elr",
    "reportItemCount": 1,
    "errorCount": 0,
    "warningCount": 0,
    "httpStatus": 201,
    "destinations": [
        {
            "organization": "Colorado Department of Public Health and Environment",
            "organization_id": "co-phd",
            "service": "full-elr-hl7",
            "itemCount": 1,
            "itemCountBeforeQualityFiltering": 1,
            "sending_at": "2023-01-11T23:18:00.000Z",
            "filteredReportRows": [],
            "filteredReportItems": [],
            "sentReports": [
                {
                    "externalName": "co-9f225afc-8087-4bb1-8c78-66d89dcd545f-20230111151811.hl7",
                    "createdAt": "2023-01-11T23:18:13.398Z",
                    "itemCount": 1
                }
            ],
            "downloadedReports": []
        }
    ],
    "actionName": "receive",
    "externalName": null,
    "reportId": "51c34757-7450-4f7c-9958-d3a36f9f3c8b",
    "topic": "full-elr",
    "errors": [],
    "warnings": [],
    "destinationCount": 1
}`

Covid Pipeline Response:
`{
    "id": "e65317ac-b87f-45ad-926a-4f587d1b97e1",
    "submissionId": 1029,
    "overallStatus": "Partially Delivered",
    "timestamp": "2023-01-11T20:56:47.170Z",
    "plannedCompletionAt": "2023-01-11T20:57:00.000Z",
    "actualCompletionAt": null,
    "sender": "careevolution.default",
    "reportItemCount": 25,
    "errorCount": 0,
    "warningCount": 25,
    "httpStatus": 201,
    "destinations": [
        {
            "organization": "FOR TESTING ONLY",
            "organization_id": "ignore",
            "service": "HL7_BATCH_OFFSET_TIME_UTC",
            "itemCount": 5,
            "itemCountBeforeQualityFiltering": 5,
            "sending_at": "2023-01-11T20:57:00.000Z",
            "filteredReportRows": [],
            "filteredReportItems": [],
            "sentReports": [
                {
                    "externalName": "covid-19-00e7cb7f-cfb5-4600-8931-109fe2f8f36e-20230111125702.hl7",
                    "createdAt": "2023-01-11T20:57:06.149Z",
                    "itemCount": 5
                }
            ],
            "downloadedReports": []
        },
        {
            "organization": "FOR TESTING ONLY",
            "organization_id": "ignore",
            "service": "HL7_BATCH_OFFSET_TIME_CONVERT",
            "itemCount": 5,
            "itemCountBeforeQualityFiltering": 5,
            "sending_at": "2023-01-11T20:57:00.000Z",
            "filteredReportRows": [],
            "filteredReportItems": [],
            "sentReports": [
                {
                    "externalName": "covid-19-fa15e452-9d06-4138-a5d2-76c03c0909cd-20230111125702.hl7",
                    "createdAt": "2023-01-11T20:57:06.441Z",
                    "itemCount": 5
                }
            ],
            "downloadedReports": []
        },
        {
            "organization": "FOR TESTING ONLY",
            "organization_id": "ignore",
            "service": "HL7_BATCH_LOCAL_TIME_CONVERT",
            "itemCount": 5,
            "itemCountBeforeQualityFiltering": 5,
            "sending_at": "2023-01-11T20:57:00.000Z",
            "filteredReportRows": [],
            "filteredReportItems": [],
            "sentReports": [
                {
                    "externalName": "covid-19-09469c96-d0d8-4699-b9a5-47a3fd544c24-20230111125701.hl7",
                    "createdAt": "2023-01-11T20:57:06.382Z",
                    "itemCount": 5
                }
            ],
            "downloadedReports": []
        },
        {
            "organization": "FOR TESTING ONLY",
            "organization_id": "ignore",
            "service": "HL7_NULL",
            "itemCount": 5,
            "itemCountBeforeQualityFiltering": 5,
            "filteredReportRows": [],
            "filteredReportItems": [],
            "sentReports": [],
            "downloadedReports": []
        },
        {
            "organization": "FOR TESTING ONLY",
            "organization_id": "ignore",
            "service": "HL7_BATCH_PEM",
            "itemCount": 5,
            "itemCountBeforeQualityFiltering": 5,
            "sending_at": "2023-01-11T20:57:00.000Z",
            "filteredReportRows": [],
            "filteredReportItems": [],
            "sentReports": [],
            "downloadedReports": []
        },
        {
            "organization": "FOR TESTING ONLY",
            "organization_id": "ignore",
            "service": "HL7_BATCH_PPK",
            "itemCount": 5,
            "itemCountBeforeQualityFiltering": 5,
            "sending_at": "2023-01-11T20:57:00.000Z",
            "filteredReportRows": [],
            "filteredReportItems": [],
            "sentReports": [],
            "downloadedReports": []
        },
        {
            "organization": "FOR TESTING ONLY",
            "organization_id": "ignore",
            "service": "HL7_BATCH",
            "itemCount": 5,
            "itemCountBeforeQualityFiltering": 5,
            "sending_at": "2023-01-11T20:57:00.000Z",
            "filteredReportRows": [],
            "filteredReportItems": [],
            "sentReports": [
                {
                    "externalName": "az-covid-19-hl7-5f76993e-7d54-45d8-9da4-8a2794b96bb9-20230111125701.hl7",
                    "createdAt": "2023-01-11T20:57:06.329Z",
                    "itemCount": 5
                }
            ],
            "downloadedReports": []
        },
        {
            "organization": "FOR TESTING ONLY",
            "organization_id": "ignore",
            "service": "HL7",
            "itemCount": 5,
            "itemCountBeforeQualityFiltering": 5,
            "sending_at": "2023-01-11T20:57:00.000Z",
            "filteredReportRows": [],
            "filteredReportItems": [],
            "sentReports": [
                {
                    "externalName": "fl-covid-19-d0f79c17-5fe9-4799-a93a-c1d1ff3c6414-20230111125701.hl7",
                    "createdAt": "2023-01-11T20:57:06.085Z",
                    "itemCount": 1
                },
                {
                    "externalName": "fl-covid-19-539a7ab1-c16c-4daa-a66e-0966589f00be-20230111125701.hl7",
                    "createdAt": "2023-01-11T20:57:06.108Z",
                    "itemCount": 1
                },
                {
                    "externalName": "fl-covid-19-6e53f4aa-1529-4082-bd6c-5244b38fbf52-20230111125701.hl7",
                    "createdAt": "2023-01-11T20:57:06.664Z",
                    "itemCount": 1
                },
                {
                    "externalName": "fl-covid-19-bf0c6104-678f-4379-9549-58a662528dae-20230111125701.hl7",
                    "createdAt": "2023-01-11T20:57:06.678Z",
                    "itemCount": 1
                },
                {
                    "externalName": "fl-covid-19-cd73c73e-d5fc-40c6-bd54-17034676c218-20230111125701.hl7",
                    "createdAt": "2023-01-11T20:57:06.844Z",
                    "itemCount": 1
                }
            ],
            "downloadedReports": []
        },
        {
            "organization": "FOR TESTING ONLY",
            "organization_id": "ignore",
            "service": "CSV",
            "itemCount": 5,
            "itemCountBeforeQualityFiltering": 5,
            "sending_at": "2023-01-11T20:57:00.000Z",
            "filteredReportRows": [],
            "filteredReportItems": [],
            "sentReports": [
                {
                    "externalName": "pima-az-covid-19-1f59b74e-7102-436b-b5f2-3d94f4921272-20230111125701.csv",
                    "createdAt": "2023-01-11T20:57:05.231Z",
                    "itemCount": 5
                }
            ],
            "downloadedReports": []
        },
        {
            "organization": "HHSProtect",
            "organization_id": "hhsprotect",
            "service": "elr",
            "itemCount": 25,
            "itemCountBeforeQualityFiltering": 25,
            "sending_at": "2023-01-11T20:57:00.000Z",
            "filteredReportRows": [],
            "filteredReportItems": [],
            "sentReports": [
                {
                    "externalName": "http://localhost:10000/devstoreaccount1/hhsprotect/hhsprotect-covid-19-b1d2cb53-3dbf-408a-b4b9-96c03612db3d-20230111125701.csv",
                    "createdAt": "2023-01-11T20:57:02.375Z",
                    "itemCount": 25
                }
            ],
            "downloadedReports": []
        }
    ],
    "actionName": "receive",
    "externalName": null,
    "reportId": "e65317ac-b87f-45ad-926a-4f587d1b97e1",
    "topic": "covid-19",
    "errors": [],
    "warnings": [
        {
            "scope": "item",
            "indices": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24,
                25
            ],
            "trackingIds": [
                "428303",
                "716531",
                "589434",
                "075492",
                "488076",
                "747072",
                "565763",
                "669772",
                "876959",
                "954486",
                "215062",
                "477980",
                "539003",
                "057640",
                "020353",
                "681371",
                "416834",
                "529565",
                "442176",
                "660211",
                "136962",
                "055410",
                "645338",
                "650068",
                "458713"
            ],
            "field": "ORC-15 (order_test_date)",
            "message": "Timestamp for order_test_date should be precise. Reformat to either the HL7 v2.4 TS or ISO 8601 standard format.",
            "errorCode": ""
        }
    ],
    "destinationCount": 10
}`
Differences where all explainable. Different number of destinations, warnings from data issues in the Covid pipeline. Covid stays at Partially Delivered. 

There is a question of whether or not to include destinations in the response to the /reports endpoint in UP since it will always be empty, but we can put that off for the API team in the future.
