### ISSUE TITLE
[FeatureFlags][UI] Support for toggling global FeatureFlags

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7382]
## Problem statement

To establish control over all features on the site, admins will have a toggleable flag value to turn on or off a feature of the ReportStream website. Example: I as an admin may go in and turn off global access to Daily Data, so no org may see it.

## What you need to know

Blocked by work in #7390

Awaiting designs as of December 8, 2022

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by HeatherRienks** [comment]
We need Design input on this  :)
cc: @fmccaf1, @drew-usds

**Comment by HeatherRienks** [comment]
We will need @fmccaf1 and @kevinhaube to create new Design tickets to precede this work.

**Comment by chris-kuryak** [comment]
Closing per committee. Will re-write in the future when more information is available and better scoping is necessary.
@stephenkao @kevinhaube
