### ISSUE TITLE
Update Pagerduty Slack Action 

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#7386]
From PD:
You are receiving this message because our database shows that you are currently using an outdated version of our Slack integration in your PagerDuty environment and need to migrate to Slack v2 Next Generation. PagerDuty’s Slack v1 application was discontinued late 2021 and the Slack v2 connections that use v2 webhooks are currently slated to be discontinued. Please follow our Slack migration guide by January 31, 2023 to maintain functionality.

Who needs to take action?  To ensure all channel connections are properly migrated, migration must be performed by a PagerDuty Account Admin or Account Owners with Slack Workspace Permissions.

Important Date: We will discontinue PagerDuty Slack v2 connections that use v2 webhooks on January 31, 2023. Please migrate your Slack connection to Slack v2 Next Generation, which uses PagerDuty’s v3 webhooks, to not experience service interruption.

Need help or have questions? 

Check out the Migration Guide
Preview the Slack Migration Video
For immediate help reach out to support [support@pagerduty.com]

**Comment by lucasdze** [comment]
Documentation
https://support.pagerduty.com/docs/slack-v2-integration-guide

**Comment by lucasdze** [comment]
Won't do
