### ISSUE TITLE
[FeatureFlags][React] Feature Flags available in application

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7392]
## Problem statement

ReportStream's front-end client needs access at any level to check the feature flags given to a user through their organization settings.

## What you need to know

There's currently a FeatureFlagContext that could maybe be stripped for functionality and merged in with our SessionContext? 

## Acceptance criteria

- [ ] The ReportStream React client can perform checks on feature flags from any component

**Comment by HeatherRienks** [comment]
@kevinhaube - Will integrate this into UI tickets.
