### ISSUE TITLE
MA - Data issues and wrong receiver

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#7393]
## Problem statement

The user's file (prime-20221109145115) was received with special characters within some of the patient names. Also, they noticed several cases that were not Massachusetts residents, that should go to the proper state.

## What you need to know
Email sent from user, Janice Grantner (janice.Grantner@mass.gov):

> Good Afternoon,
> 
> We are receiving these reports from Report Stream to the Massachusetts Department of Public Health. The facility that is sending them in CDC Prime-Atlanta, Georgia (Dekalb).
> 
> - Can you please review the size of these Prime files? We came across a file yesterday that was too big which needed to be split into multiple files. Yesterday file size was 5, 550KB (2096 messages) and we can only accept files up to 2.0MB. I have fixed and manually upload this file to our ELR Portal. (BX: this bullet point is being handled under [Issue # 7343](https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/7343))
> 
> - A max file size constraint of 2.0 MB is imposed for HL7 251 messaging. We strongly recommend that you send <=400 messages in your batch. Multiple batch files can be transmitted each day based on reporting volume. (BX: this bullet point is being handled under [Issue # 7343](https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/7343))
> 
> - Additionally, this file (prime-20221109145115) was received with special characters within some of the patient names. Can you please review this issue? Also, we noticed several cases that were not Massachusetts residents. They should not be sent to us and should go the proper state." 

User's name is Janice Grantner
janice.Grantner@mass.gov

## Acceptance criteria

- [ ] Root cause is identified
- [ ] Resolution has been identified
- [ ] User has been notified of root cause/resolution

## To do

- [ ] Review user's file (prime-20221109145115) to investigate the data issues
- [ ] Contact user with root cause/problem resolution

**Comment by brick-green** [comment]
Currently, we route results to MA based on the Ordering Facility State or Patient State. It sounds like MA only wants results where Patient State = MA. Since the majority of states want both Ordering Facility State or Patient State I think we should confirm that with MA before editing the filtering. @BerniXiongA6 Can you reach out to MA on this?

**Comment by brick-green** [comment]
Oh also, I downloaded the file in question. I couldn't find any messages with special characters in the patient names. Can we see if MA con provide accession numbers with examples?

**Comment by BerniXiongA6** [comment]
Yes, I can reach out to MA on this @brick-green -- I'll update the ticket with that progress. Thanks!

**Comment by BerniXiongA6** [comment]
BX emailed MA on Dec. 6, 2022:

> Hi Janice,
> 
> Nice to meet you, I'm Berni, the Delivery Manager for ReportStream's Onboarding & Operations team (previously in this role was Adrian Brewster). Our team has looked into this matter and here's the feedback I got from our engineer in response to your questions/issues raised:
> Currently, we route results to MA based on the Ordering Facility State or Patient State. If MA only wants results where Patient State = MA, we can make an edit to our filtering. Please confirm this is indeed how you'd like to proceed. (We've experienced that the majority of states want both Ordering Facility State or Patient State.)
> As for the file in question, after downloading it, our engineer couldn't find any messages with special characters in the patient names. Could you provide us accession numbers with examples?
> Please feel free to reply to all to this email.
> 
> Thanks,
> Berni
> 
> P.S. I've also copied in our Sarah White's replacement, Brandon Canniff (ReportStream Onboarding & Operations Product Manager), and Brick Green (ReportStream Onboarding & Operations Technical Lead).

**Comment by brick-green** [comment]
@BerniXiongA6 I don't understand this statement:

"Yes we want both of these but only if the patient state is in MA"

I don't think Janice understood what was being asked. I think MA only wants the routing to look at patient state but don't feel 100% clear on that. What do you think?

**Comment by brandonnava** [comment]
@brandonnava to reach out to MA

**Comment by LaFreda1** [comment]
@brandonnava do we have any updates on this?

**Comment by brandonnava** [comment]
Followed up with Janice. She says the issue hasn't reoccured so go ahead and close
