### ISSUE TITLE
Support ingesting a single FHIR Bundle through the reports endpoint using the UP

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#7402]
### User Story:
As a sender, I want to be able to submit my data as a FHIR bundle, so I can submit all reportable conditions.

### Description/Use Case
We want to be able to support the receiving of FHIR as a report from a sender. This is only for a single FHIR bundle right now.

### Risks/Impacts/Considerations
* We know that any change from the existing RS FHIR bundle format can break us, but the direction we are taking right now is that we are only taking the same FHIR Bundle we are using right now.

### Dev Notes:
* This could be implemented by simply detecting the type of data being submitted (use the content type and verify the right data was sent for that type) then bypassing the HL7 to FHIR conversion.
* Use the proper FHIR content type (research this online)

### Acceptance Criteria
* A sender can submit a RS FHIR bundle to the Universal Pipeline (UP) via the reports endpoint.
* The submitted FHIR bundle is processed (converted, routed, translated, sent) by the UP.
* The reports endpoint returns a success API response if a FHIR Bundle was accepted by the system.
* The reports endpoint returns an error API response (e.g. id=null) if a submission was not accepted by the system (e.g. sent an HL7 file using the FHIR content type).
* Receive and Convert steps are still used with the underlying logs and lineage information stored the same as the incoming HL7 to the universal pipeline.

**Comment by jimmyfagan** [comment]
@victor-chaparro and I spent some time working through this today. It feels like we're just scratching the surface, but it was a very good way to get more hands on with seeing what the process looks like in the code. I'll resume on it next week and ask for help as needed.
