### ISSUE TITLE
HHS Protect Jurisdictional Filter - Confirm which senders are and/or not sending their data to HHS Protect

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7411]
## Overview

HHS Protect Jurisdictional Filter - Confirm which senders are and/or not sending their data to HHS Protect

## Participants

**Interview subject(s)**: [name/organization/etc] 
Joel Biskie - Flexion

**Contact info**: ?

## Background

- [ ] Have we had previous contact/meetings/etc with the participant?
- [ ] Look into the the population/oranization/individual we're meeting with.
- [ ] Desk research on the participant for any relevant information. Can their website/documentation/etc inform interview questions?

Generally, if a sender is sending to STLTs, we often do not send that data to HHSProtect. 

Vice versa, some of our senders have separate non-ReportStream pipes to STLTs, and only use ReportStream to send to HHSProtect.   Abbott,lifepoint,ImageMover,CueHlth all fall in this category and should be sending to HHSProtect.   Probably others too.

But the current HHSProtect juridictional filter in Production seems to allow for a ton of labs to be sending data to HHSProtect:

[
  "matches(sender_id, SafeHealth,ImageMover,Cue,InBios,Strac,.*CueHlth.*,reddyfmc-la,primary,cuc-al,guc-la,abbott,lifepoint,hca,pmg,ihealthlabs,mns,all-in-one-health-ca,corebiolabs-oh,covidclinic-org,elitemedlabs-co,warrior-dx-co,stemexpress-ca,newport-childrens-hospital-ca,sdilabs-ca,naval-health-clinic-lemoore,prescryptive,pcl-ca,jrslab-ca,mycarelabs-ca,biovisiondx-il,youthclinic-co,kwokmandx-ca,toprankdx-ca,hollywoodsmiles-ca,hcintegrations,signetic,xtrava,intrivo,neurolab,limsabc-nova,clxhealth,providence,color-labs,genabio,osang-otc)"
]

The task with this ticket is to do a sanity check and confirm that this list of senders to HHSprotect is correct.  You might need to check in with Joel Biskie.

(As an FYI, I checked a data file from yesterday, and the following sender_id's actually sent data to HHSProtect in that file:   abbott, CueHlth, hcintegrations, ImageMover, lifepoint, prescryptive, sdilabs-ca

Thanks!
Jim
(Note:  unlike STLT data, HHSProtect files do not have PII in them)

## To do

- [ ] Warm hand off (email) from person with existing relationship 
- [ ] Email/schedule session with STLT/partner
- [ ] Tailor the facilitation guide 
- [ ] Read background materials and previous emails 
- [ ] Confirm schedule and set up team for notetaking and recording  
- [ ] Conduct call (facilitation, notes, recording) 
- [ ] Upload any documentation notes and recording  
- [ ] Identify high-level findings, put in shared document 
- [ ] Share in Slack

**Comment by BerniXiongA6** [comment]
Hey @sliu1000 Is this an Experience Research ticket? Just wanted to make sure because it was tagged as O&O too but Joel Biskie is no longer on our team. Please advise? cc: @brandonnava @HeatherRienks

**Comment by sliu1000** [comment]
@BerniXiongA6 Its related to the backend reportstream jurisdictional filters.  A request came into the Reportstream box to check which senders data is going to HHS Protect and which ones are not. So, it's more of a checklist/confirmation. I'm not sure if this is something that we can easily query/look up. Or if we should just create a checklist of all the senders and categorize them as Yes/No to data going to HHS Protect.  I think the suggestion was to contact Joel for confirmation if we need further assistance/confirmation.

**Comment by BerniXiongA6** [comment]
Thanks for the clarification @sliu1000 ! @brandonnava lets discuss so we can triage this accordingly.

**Comment by BerniXiongA6** [comment]
Hey @brandonnava could you bring this up at backlog refinement so that the engineers can determine what they want to do with this ticket? THanks! cc: @sliu1000 @brick-green

**Comment by brandonnava** [comment]
@brick-green to follow up with Jim and provide guidance on troubleshooting

**Comment by jimduff-usds** [comment]
@brick-green , senders have the ability to force routing when they POST, via a URL parameter, like this:

/api/reports?routeTo=hhsprotect.elr

**Comment by brick-green** [comment]
@jimduff-usds Okay, that makes sense. So we need to understand which senders do not want to report to STLTs via RS or are sending data that is not reportable to STLTs? For the latter I think self-reported OTC would fall in that category? I know many STLTs have expressed that they do not want that data.

cc @BerniXiongA6 @brandonnava I think this is going to require some larger discussion and outreach to senders and receivers

**Comment by BerniXiongA6** [comment]
@brick-green check in with Jim D. to see if we need to further work on this on O&O team cc: @brandonnava

**Comment by brick-green** [comment]
@sliu1000 Senders to contact:

- Strac
- Primary Health
- Prescryptive
- Medical Network Solutions (MNS)
- Nova Labnetics (limsabc-nove)
- ImageMover
- Healthcare Integrations (hcIntegrations)
- Cue Health
- Premier Medical Group (PMG)
- LifePoint
- SafeHealth

**Comment by brick-green** [comment]
@GilmoreA6 Are you working to onboard any other these senders:

- InBios
- Xtrava
- CLXHealth
- NeuroLab

**Comment by GilmoreA6** [comment]
@brick-green just InBios, which was initially started by Joel awhile back but we just re-engaged them.

**Comment by sliu1000** [comment]
Sent first batch of emails to:

1. Prescryptive - jon@prescryptive.com 
2. Medical Network Solutions (MNS) - jacob@medicalnetworksolutions.com
3. Nova Labnetics (limsabc-nove) - gabriel.balint@limsabc.com
4. Cue Health - b.bye@cue.me
5. Premier Medical Group (PMG) - dcorderman@syncronys.org

See below email communication:

Happy New Year!

In efforts to better support your needs and expectations - can you please provide some feedback on the below:

Is your organization reporting COVID test results to State Health departments via interfaces outside of ReportStream? 
Is your organization reporting non-COVID test results to State Health departments via interfaces outside of ReportStream? 
Do you expect the test results your organization is submitting to ReportStream to be reported to HHS Protect (Federal)? 
Other feedback? 
Best regards,

The ReportStream Support Team
Contact us at reportstream@cdc.gov
Support hours:  8:00 am through 9:00 pm Eastern time
Monday-Friday, excluding US public holidays

**Comment by sliu1000** [comment]
second email batch to:

1.  Imagemover - tyler@imagemovermd.com
2.  Primary Health - Andrew.Nguyen@primary.health
3.  Health Integrations - Anthony.Milan@healthintegrations.com
4.  Lifepoint - kdizon@lifepoint.com
5.  Safehealth - santosh@safehealth.me

See below email communication:

Happy New Year!

In efforts to better support your needs and expectations - can you please provide some feedback on the below:

Is your organization reporting COVID test results to State Health departments via interfaces outside of ReportStream?
Is your organization reporting non-COVID test results to State Health departments via interfaces outside of ReportStream?
Do you expect the test results your organization is submitting to ReportStream to be reported to HHS Protect (Federal)?
Other feedback?
Best regards,

The ReportStream Support Team
Contact us at reportstream@cdc.gov
Support hours: 8:00 am through 9:00 pm Eastern time
Monday-Friday, excluding US public holidays

**Comment by LaFreda1** [comment]
@sliu1000 confirming that we received responses from the senders? Thanks

**Comment by sliu1000** [comment]
@LaFreda1 I did not receive any responses. I'll need to send out personalized emails to see if that helps.

**Comment by LaFreda1** [comment]
Update from Marshall at Vikor Scientific:

**Comment by sliu1000** [comment]
@jimduff-usds Hi Jim, my apologies. I'll follow-up again today and send separate emails to illicit a better response rate.

**Comment by sliu1000** [comment]
wow, I actually got a response from Primary Health. 1 down 14 more to go.

![image](https://user-images.githubusercontent.com/102377655/221056891-bbc94de0-67cc-4aad-adc2-997b80eb40bf.png)

**Comment by sliu1000** [comment]
Response from Inbios:

![image](https://user-images.githubusercontent.com/102377655/221058660-011ff550-0d8d-43c5-ac33-fbf64704f207.png)

**Comment by sliu1000** [comment]
3 out of 15 responded - 12 more to go.

Response from Nova Labs:

![image](https://user-images.githubusercontent.com/102377655/221249718-793c1ec3-c0df-42f0-ad90-67d39777c69b.png)

**Comment by sliu1000** [comment]
Send email again to senders that did not respond. Hoping an earlier time will illicit more responses:

Sent out again to:
1. Strac
2. Neurolab
3. CLXHealth
4. ImageMover
5. Prescryptive

**Comment by sliu1000** [comment]
@oH232022 Can you please send the reset of the 2nd followup emails for the remaining senders that did not respond.

**Comment by OHoward2023** [comment]
second email batch sent 03/07/2023 at 2:54pm to:

1. Health Integrations - Anthony.Milan@healthintegrations.com
2. Lifepoint - kdizon@lifepoint.com
3. Safehealth - santosh@safehealth.me
4. Medical Network Solutions - jacob@medicalnetworksolutions.com
5. CueHealth - b.bye@cue.me
6. Premier Medical Group - dcorderman@syncronys.org

**Comment by OHoward2023** [comment]
Response from Neurolab:

![image.png](https://images.zenhubusercontent.com/6400befe5a4d6b4a14165257/ae06e697-3d8e-4000-b80c-9d3d611af205)
