### ISSUE TITLE
Tech Debt: Investigate need for "CsvFileTests-topic" Topic

### ISSUE THREAD

**Issue by jimmyfagan** [CDCgov/prime-reportstream#7415]
### User Story:
As a RS developer, I want to confirm whether or not the "CsvFileTests-topic" Topic is necessary so I can remove it from the repo if it is not necessary.

### Description/Use Case
In the process of updating objects to use the `Topic` enum instead of hardcoded strings, we added a few enum values to allow all existing tests to continue to run. One of these was for "CsvFileTests-topic", but at the time of [PR 7384](https://github.com/CDCgov/prime-reportstream/pull/7384) we weren't confident whether or not it was necessary to keep that. This issue involves investigating that need, and if it is deemed unnecessary, removing that `Topic` value and any associated tests to clean up our code base.

### Risks/Impacts/Considerations
* If cleanup of the Topic is done, we should be sure that all tests pass and that coverage isn't affected.

### Dev Notes:
* See [this comment](https://github.com/CDCgov/prime-reportstream/pull/7384#discussion_r1026491808) for context

### Acceptance Criteria
- [ ] The necessity of "CsvFileTests-topic" has been confirmed.
- [ ] If "CsvFileTests-topic" is deemed unnecessary, all references to that topic in tests, functions, and other files has been removed.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/7415?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @mkalish @thetaurean @victor-chaparro
