### ISSUE TITLE
Prototype Facility Look-Up Feature

### ISSUE THREAD

**Issue by fmccaf1** [CDCgov/prime-reportstream#7437]
### Overview
- Experience team met to discuss facility look-up feature and went through [research supportive of the concept.](https://cdc.sharepoint.com/:w:/t/USDSatCDC/EYiKKLbo-BpMpJW4d9V-B7YBdDSjTk2tQqRcBvyoEi_kkw?e=CSgQVR)
- Identified a prototype of this concept that needs update: [Prototype link 1](https://www.figma.com/proto/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=12%3A275&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=12%3A275) and [Prototype link 2](https://www.figma.com/proto/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=12%3A275&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=2%3A4&show-proto-sidebar=1)

### Next steps

- [x] Meet w/ Drew to understand what about about prototype do we already know needs to be updated

- [x] Update prototype in prep for internal user testing

**Comment by fmccaf1** [comment]
[Figma file located here](https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=4172%3A25136&t=Vbz7OmRdzv8Y7uhB-1)

Also attaching PDFs of the Figma file in case eng is lacking Figma access.[https://app.zenhub.com/files/304423150/39419bb4-f17b-4463-a4c8-dee9e462c538/download](https://app.zenhub.com/files/304423150/39419bb4-f17b-4463-a4c8-dee9e462c538/download)

**Comment by kevinhaube** [comment]
@fmccaf1 THESE ARE GREAT! Thank you so much, Flo. @stephenkao I'll work on refreshing our Epic, but this might be a great exercise for breaking out tickets together
