### ISSUE TITLE
Tell Senders we are Deprecating usage of URL parameters when sending to api/token endpoint

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#7440]
This is a follow-on to ticket #7364.

We need to ask our senders to make a small change to the way they are requesting bearer tokens from us.  

### Steps:

1.   Find all senders using the api/token endpoint.  (There are several ways to do this.  One is to look in metabase for all recent senders who create token_auth actions in the ACTION table)
2. Contact them and let them know they need to switch to sending parameters in the body of the http message, and they need to make sure they are using `Content-Type: application/x-www-form-urlencoded`
3. Give them time to make the change (See example below)
4.  Warn them
5. Warn them again
6.  Modify the code in TokenFunction.kt so that only parameters in the body work.

#### THE OLD WAY THAT IS GOING AWAY

**Instead of sending this URL:**

`http://localhost:7071/api/token?scope=<put-customer-scope-here>&grant_type=client_credentials&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&client_assertion=<very-looooooooong-jwt-string-generated-by-customer>
`

**with an EMPTY body** ....

#### THE NEW WAY THEY SHOULD BE USING

... the customers should instead send

**This URL:**

`http://localhost:7071/api/token`

**Using this payload body:**

`scope=<put-customer-scope-here>&grant_type=client_credentials&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&client_assertion=<very-looooooooong-jwt-string-generated-by-customer>`

**And they should set this header**: `Content-Type: application/x-www-form-urlencoded`

**Comment by brandonnava** [comment]
@GilmoreA6 @brick-green Do we know if anyone is still using the old URL for API calls? Is this an issue we need to follow up with senders on for the sake of data not breaking in transit or just a nice to have?

**Comment by GilmoreA6** [comment]
@brandonnava we absolutely need to address this with senders. Most of of senders are still sending the old way

**Comment by brandonnava** [comment]
1. An engineer needs to pull from settings a list of senders using token based authentication (probably less than 20)
--- Anyone with a non-null value under their keys parameter in settings
2. Pass that list to support to send out a mass email to all those senders letting them know they need to update where they are sending the parameters by Oct 1 (used to be all in URL, now supposed to send separately in the body)(can share example Jim shows above)
3. Periodically check the logs to make sure they all have made the update. If not, follow up with the sender.

**Comment by brandonnava** [comment]
Goal to close by Oct 2 with a log check two weeks before

**Comment by sliu1000** [comment]
@wcollin89 @TaneaY - Wendy could you please research in RS Metabase for a list of senders we need to reach out to as described above.

**Comment by wcollin89** [comment]
@sliu1000 @TaneaY I was able to pull the list from the RS Metabase "Setting" table and downloaded it as a CSV. Please let me know if you need anything else!

https://app.box.com/s/mzj6erhaotugpya9up6gu41honfzvm04

**Comment by sliu1000** [comment]
@brandonnava Hi Brandon, I have a draft email ready to go but I can't seem to locate an email address for MAYO and HCA? Do you happen to know if Engineering has this information somewhere?

**Comment by brandonnava** [comment]
Platform might have the HCA contact, post an ask in our slack channel and I
can @ people as needed

**Comment by sliu1000** [comment]
Sent the below email out to BDVeritor, Color Labs, Genabio, HCA, Mayo, SimpleReport and Simplehealthkit
(https://images.zenhubusercontent.com/6282728600f2331155d73bf3/68d66535-be6b-4977-acf7-944f8d904760)

**Comment by wcollin89** [comment]
SimpleHealthKit responded to our email and notified us that they are already using this URL.

**Comment by wcollin89** [comment]
Ran a weekly check for these parameters and uploaded the new CSV file here: https://app.box.com/s/r4slw8s4kie4o5pr094ppq8g2lvmdwez

Still shows 26 entries.

**Comment by LaFreda1** [comment]
@brandonnava Can we close this for now?

**Comment by brandonnava** [comment]
@LaFreda1 We'll probably forget to reopen it so we can close it but please make a 'check in two weeks before Oct 2' ticket so we still have some way to track the deadline we set for ourselves

**Comment by sliu1000** [comment]
@brandonnava After working with @oslynn it appears that no changes are required for these senders.

**Comment by brandonnava** [comment]
Thanks for checking in. In that case we can close
