### ISSUE TITLE
AZ DOH - Missing Data

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#7444]
Ticket from Ana (ana.mendoza@adhs.gov):

ELR file `az-covid-19-ea11cec7-9742-4ea4-81f2-1793270c6399-20221121145037` received 11/21/2022 has records that are missing data in column 'test name'. These records are failing and we are unable to process.

Message ID: `29ba810a-b516-4a7f-aba3-4ec0fe89d834`

**Comment by shy2cdc** [comment]
Email from Ana:

ELR file we are receiving is missing Test Name on some of the records. These records are failing

**Comment by GilmoreA6** [comment]
Sender PMG is sending incorrect value in column deviceName. Value being sent is "FlowFlex COVID-19 Antigen Test". Correct value from LIVD table is "FlowFlex COVID-19 Antigen Home Test"

**Comment by GilmoreA6** [comment]
Good Morning all,

We received a ticket from one of our State DOH receivers and after investigation found that the issue stems from incorrect values being received in column "deviceName" and "deviceIdentifier" on some reports from PMG.

 The incorrect value being received in "deviceName" is "FlowFlex Covid-19 Antigen Test". Values in column deviceName should match the appropriate values from column B of the LOINC Mapping sheet on the CDC SARS-COVID-19 LIVD table (https://www.cdc.gov/csels/dls/livd-codes.html?CDC_AA_refVal=https%3A%2F%2Fwww.cdc.gov%2Fcsels%2Fdls%2Fsars-cov-2-livd-codes.html). 

The incorrect value being received in "deviceIdentifier" is "FlowFlex Covid-19 Antigen Test_ACON Laboratories, Inc". Values in column deviceIdentifier should match the appropriate values from column M of the LOINC Mapping sheet on the CDC SARS-COVID-19 LIVD table (see link above).

I believe the correct values you are looking for should be "FlowFlex Covid-19 Antigen Home Test" for "deviceName" and "FlowFlex Covid-19 Antigen Home Test_ACON Laboratories, Inc" for "deviceIdentifier" as those appear to be the only values on the LIVD table that are close to the values you are sending and that match the other columns on the LIVD table for that row. Could you correct these values moving forward to match values on the current CDC SARS-COVID-19 LIVD table?

Please let me know if you have any questions, 

Thanks,

James

**Comment by GilmoreA6** [comment]
@sliu1000 Can you or someone from support doublecheck Ana's email address from the ticket. I tried to email her at ana.mendoza@adhs.gov and got a failed delivery message.

**Comment by sliu1000** [comment]
@GilmoreA6 The email address is ana.mendoza@azdhs.gov

**Comment by sliu1000** [comment]
Hi Ana,

Thank you for the details. It's very helpful.  I have reached out to the sender and asked them to resend. 

Best regards,

Sharon
The ReportStream Support Team
Contact us at reportstream@cdc.gov
Support hours:  8:00 am through 9:00 pm Eastern time
Monday-Friday, excluding US public holidays

From: Ana Mendoza <ana.mendoza@azdhs.gov>
Sent: Friday, December 9, 2022 2:24 PM
To: Report Stream (CDC) <reportstream@cdc.gov>
Cc: Arizona Electronic Lab Reporting - ADHS <ELR@azdhs.gov>
Subject: Re: Receiving file question re: Prophase
 
Hello
This is the file with the date and time submitted. There is one message that is missing Test code and Test code name.

image.png

Thank you,
Ana Mendoza
ELR Team Lead
Business Intelligence Office
Arizona Department of Health Services
150 North 18th Avenue, Suite 550, Phoenix, AZ 85007
Teleworking Monday-Friday (8:00am-5:00pm Arizona Time)
Mobile    +1 (602) 736-7377
Email       ana.mendoza@adhs.gov
