### ISSUE TITLE
Sender Abbott - API Upload Failure

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7449]
Sender Abbott, sent a service request via Smartsheet.

Problem:
Abbott received an error message when trying to send data to the ReportStream API.

Please see below images for more information:
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/ab49eb32-3228-4acc-a1c6-4e3bcfe03f93)Pro![Abott.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/dfed8702-2b8a-41c2-97f6-a7c0822085c3)
![abott2.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/ec254e3f-a590-46c2-ba52-f64ab7050eec)

**Comment by BerniXiongA6** [comment]
@sliu1000 can we get more info so we can determine how to take action on this?

**Comment by sliu1000** [comment]
@BerniXiongA6 

I just emailed Rajan from Abbott asking for more information and a for a screenshot (if available).  I'll update you once I receive more information.

Sharon

**Comment by sliu1000** [comment]
@BerniXiongA6 

I have attached three screenshots sent from Abbott.  They confirm that the error message is when they try to send data via ReportStream.

However, this error may be related to the data that reportstream is sending to HHS Protect.

**Comment by BerniXiongA6** [comment]
@sliu1000 Thanks for the updates to the ticket. We'll pull this into our backlog refinement next week to make sure it gets assigned and worked on by an engineer. For now, I'll assign it to @brandonnava so we can transfer ownership from support to O&O team. Thank you!

**Comment by GilmoreA6** [comment]
After meeting with Abbott we have additional details. Starting 11/21/22 ~9:45PM - 11/22/21 12:45AM UTC approx 17% of all attempts to send messages to ReportStream were met with a 503 Service Unavailable error. Abbot mentioned this was the same error they received during the 10/27 outage when RS was completely down.

**Comment by GilmoreA6** [comment]
Abbott has automated retry functions and all affected messages were able to resend.

**Comment by BerniXiongA6** [comment]
@GilmoreA6 can this be closed, or shoudl we wait to ensure all is OK before closing? Please advise. Thanks for handling this! cc: @sliu1000 @brandonnava

**Comment by GilmoreA6** [comment]
@BerniXiongA6 I'd like to leave this open for now as I don't yet have a good answer for why this happened and am still trying to track it down.

**Comment by sliu1000** [comment]
Jeremy would like us to start a process on how to hand these types of issues in the future.  I'll start a draft document and share for feedback.

**Comment by GilmoreA6** [comment]
Response from Abbott on my follow-up:

Hi James,

 

The time period is correct. We send messages 1 at a time in 15 minute batches. So every 15 minutes we will send N number of POST requests (where N = number of tests in the past 15 min). We have retries built in.

 we've been transmitting successfully before and since. We don’t have any failure requests since we have retry policy.  Seems like a transient issue from Report stream side.

 

Thanks

Krishna
