### ISSUE TITLE
Designate website location and update the transcript for 5-min intro video to data senders

### ISSUE THREAD

**Issue by fmccaf1** [CDCgov/prime-reportstream#7459]
## Problem Statement
As a sender, I receive a 5-min intro video via email. To reduce the pain of downloading and finding that video in the future (and potentially clogging my inbox), it would be nice to have a link to the video hosted elsewhere (like the RS website) to avoid these issues.

## Important info

- O&O team created a 5-minute intro video (mp4) to start off the process of onboarding senders (there is also a PDF transcript to the video)
- [Video here](https://github.com/CDCgov/prime-reportstream/wiki/files/RS%20Sender%20Onboarding%20Kick-off%20Nov.9.2022.mp4)
- [PDF transcript here](https://github.com/CDCgov/prime-reportstream/wiki/files//ReportStream%20Sender%20Onboarding%20Kick-off%20Toolkit%20PDF.pdf)

SimpleReport's solution for reference:
- SimpleReport has a set of onboarding and training videos that they have uploaded to a [Youtube account playlist](https://www.youtube.com/playlist?list=PL3U3nqqPGhab0sys3ombZmwOplRYlBOBF)
- There is no dedicated page on the website for the videos, the link in their top navigation just takes you directly to the Youtube Playlist page: 
![Screen Shot 2023-01-25 at 3 31 22 PM](https://user-images.githubusercontent.com/117934818/214696925-928b114f-7102-4a60-9150-09b4bbbe61c8.png)

## Acceptance Criteria
- [ ] Transcript updated for web accessibility purposes
- [ ] Location on the RS website for both the mp4 and the transcript
- [ ] If applicable, include any necessary page design/changes
- [ ] Once decided, ticket needs to be created for the dev work

## To Do
- [ ] If design team has a preference, indicate whether or not you would like it to be hosted on Youtube and why

**Comment by fmccaf1** [comment]
@BerniXiongA6: We'll revisit when you're back from PTO, week of Dec. 5

**Comment by fmccaf1** [comment]
cc @sliu1000 @brandonnava

**Comment by fmccaf1** [comment]
For now, USDS wants us to tackle this less directly, in a more strategic conversation about the ReportStream website as a whole. For now, I guess we want to put this off. @BerniXiongA6

**Comment by chris-kuryak** [comment]
@lizzieamanning @brandonnava @sliu1000  
Any update on whether we still want to add this video somewhere on the website?

**Comment by brandonnava** [comment]
@chris-kuryak Yes please! The current experience is that users need to download it from their email. Would be better if we could share a website link instead, even better if we could get it on Youtube like SimpleReport did

**Comment by chris-kuryak** [comment]
@brandonnava Thanks!

**Comment by chris-kuryak** [comment]
No longer need this since we do not send out this video anymore.
