### ISSUE TITLE
Public validation service: Research and design

### ISSUE THREAD

**Issue by fmccaf1** [CDCgov/prime-reportstream#7464]
### Need to know
- Internal usability testing is complete. Next stage of feedback is to learn from external users (senders themselves)
- Florence (UX) will meet with James (O&O eng) to be on hand and observe as senders (3 minimum) try out the validation service and attempt to understand and address the errors associated with their test message

**Comment by chris-kuryak** [comment]
Moved from Experience to O+O per convo with @lizzieamanning @fmccaf1
