### ISSUE TITLE
Upload new LIVD table

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#7491]
## Problem statement

The LIVD team sent over a new LIVD table that needs to be uploaded into ReportStream.

## What you need to know

[LIVD Table Excel sheet](https://app.zenhub.com/files/304423150/4f9932c4-377b-4cfd-82ec-56a1ffb5ac67/download)

## To do

- [ ] Run livd-table-update command with new table

**Comment by GilmoreA6** [comment]
LIVD table update deployed
