### ISSUE TITLE
Missouri - Last Mile Failures - Needs Investigation on why Failure occurred

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7492]
## Problem statement

Failed message received - Last Mile Failure on 11/28 at 11:36 am.

## What you need to know

Info Details: 21357737
Receiving Org: moftp.mo.gov
Failed at: Mon, 11/28/2022, 11:36 AM
Action ID: 21357737
Report ID: `0b1968ce-63b0-4fbd-a31c-6d313f8d07d0`
Report File Receiver: mo-phd.elr
File URI: https://pdhprodstorageaccount.blob.core.windows.net/reports/ready%2Fmo-phd.elr%2Fcovid-19-0b1968ce-63b0-4fbd-a31c-6d313f8d07d0-20221128162024.hl7
mo-phd.elr
Results: Success: sftp upload of covid-19-0b1968ce-63b0-4fbd-a31c-6d313f8d07d0-20221128162024.hl7 to SFTPTransportType(host=moftp.mo.gov, port=22, filePath=/Distribution/DHSS/Epitrax_ELR_hl7/, credentialName=null), Send function unrecoverable exception for event. Mo intervention required: report&SEND&0b1968ce-63b0-4fbd-a31c-6d313f8d07d0&false

## Acceptance criteria

- [ ] ...

## To do

Please investigate

**Comment by brandonnava** [comment]
@brick-green @GilmoreA6 @oslynn How serious do we think this is? Should we get on a call with them or just ask Sharon to have them resubmit?

**Comment by brick-green** [comment]
If this is the first and only failure then I think just an attempt to resend. If the problem persists then we would investigate internally first prior to escalating to a call with MO.

**Comment by brandonnava** [comment]
@sliu1000 Can you ask them to resend per Brick's advice?

**Comment by sliu1000** [comment]
Sure thing, I'll send out an email shortly.

**Comment by brick-green** [comment]
@sliu1000 @brandonnava the transportation issue was with reportstream. So all we need to do is use the last mile failures tool to try to resend. @sliu1000 Have you used that before? I can show you how if not.

**Comment by sliu1000** [comment]
@brick-green Yes, I just click on the resend button.

**Comment by sliu1000** [comment]
![image](https://user-images.githubusercontent.com/102377655/204644816-45079b6a-edde-40d0-9682-2fc831340bc8.png)

It Failed.

**Comment by brick-green** [comment]
Okay, this should go to an engineer to investigate the root cause

**Comment by brandonnava** [comment]
@oslynn Hi Ott, given you're doing MO work can you look into this?

**Comment by oslynn** [comment]
Somehow, their server lock out account.  I am working with Jake at MO to resolve it.  We can get their server to response to our curl sftptest.  However, we still can't connect to it.

**Comment by oslynn** [comment]
MO SFTP production feed, somehow, locked our account.  I was working with Jake to Unlock our account.  It is now UNLOCKED.  We should be able to send messages to their SFTP production feed, now.

**Comment by oslynn** [comment]
However, I will have to still look into why the last mile still prompts triggering resend command failed.

**Comment by oslynn** [comment]
Just activate the mo-elr.  Need to check in Receiver Status Dashboard.

**Comment by oslynn** [comment]
The production feed is fixed.
