### ISSUE TITLE
WA - Last Mile Failures - The files for WA will need to be emailed securely,

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7493]
## Problem statement

A small number of WA delivery failures found on Last Mile Failures. Please investigate.  The files will need to be emailed securely.

## What you need to know
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/d195c103-16c4-4de0-b20b-ff2927ae5f2a)

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by brandonnava** [comment]
@greene858 figured it made sense for you to take on this one. How pressing is this? You want me to throw it in this sprint or backlog?

**Comment by brick-green** [comment]
Just resent these using the last mile failures resend tool. WA only needs results emailed if they were sent in error. Since these were failures to transport, the last mile tool works.
