### ISSUE TITLE
APHL - Message criteria suggestion

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7495]
## Problem statement

Andrew Weitz from NIH emailed the ReportStream box on 11/25/2022 at 1:32 pm requesting that we include at least the Last Name and DOB in messages.  The reason being that APHL only routes messages to states if they contact at least the Last Name and DOB.  Also, most states do not want to accept anonymous messages.

## What you need to know

Hi all,

We’ve heard that most states do not want to accept anonymous messages.  Because of this, APHL only routes messages to states if they contain at least the Last Name and DOB.  I suggest that ReportStream does the same.

We are working with CDC to survey the states regarding their preferences for receiving OTC data, including whether they will accept anonymous messages.  We expect to have the survey results sometime in January.

Best,
Andrew

## Acceptance criteria

- [ ] Decide if we will or will not make messages to include the minimum (last name and dob).

## To do

- [ ] Research

**Comment by brandonnava** [comment]
Update from Andrew: 

Here is the answer I received from APHL:

This is the first I’ve heard of any jurisdiction mentioning ORC-2 and OBR-2. According to the base ELR standard, ORC-2 is conditional on OBR-2 and OBR-2 is RE (Required, but may be empty).

For OTC tests, there would not be a placer order number, so you could reply to VT that it is not available for that reason.

Regarding anonymous reporting, APHL only sends messages to states (including Vermont) if the last name and DOB are populated.  If they are missing, then the messages will only be routed to HHS Protect.

**Comment by LaFreda1** [comment]
We will handle this on a case by case situation. When STLTs reach out, we will update accordingly. We will have design add this to the interviews
