### ISSUE TITLE
[FeatureFlags][API] Checking Organization's FeatureFlags

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7502]
## Problem statement

Scopes will be delivered to the front-end to show and hide UI, but to truly validate a user's access to a page, our front-end `AuthElement` gate should implement a strict check with the API. 

## What we know

Related to the database setup #7301

`AuthElement` on the front-end can take one or many scopes (`requiredFeatureFlag` prop); does it need to? Maybe we can simplify this work if we don't know of a case for many feature flags, and whether we'd want to "and" or "or" check them.

## Acceptance criteria

- [ ] The ReportStream API can validate that a React app user's organization has the given feature flag

## Todo

- [ ] ...

**Comment by HeatherRienks** [comment]
Hold off on pointing this until @penny-lischer finishes her work on #7301

**Comment by kevinhaube** [comment]
Aurora & Penny knocked this functionality out in one fell swoop!
