### ISSUE TITLE
[FeatureFlags][React] Use strict FeatureFlag check

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7503]
## Problem statement

So no front-end user can use browser tool sleuthing to manipulate their membership and gain access into features hidden to their organization, **we need to verify with a source of truth (RS API) that the organization is allowed access to a feature**.

If a feature is part of the RS unauthenticated experience (available when not logged in), **the check should _then_ only consider global availability**.

In cases of a globally "off", nobody should be granted access.

## What we know

`AuthElement` already does our soft check for feature flags; could maybe be converted to the hard check!

This simultaneously supports A/B testing, slow rollouts of features, and added safety for unauthenticated experiences.

## Acceptance criteria

- [ ] A user cannot mock authorization to a restricted feature through editing their given feature flags or scopes
- [ ] The server authenticates and authorizes access to features at an organization level

**Comment by kevinhaube** [comment]
@CnoteNava @chris-kuryak @HeatherRienks Back-end work in #7301 and the associate epic will be blockers for this, but this is an upcoming enhancement to allow for organization-level, and global, access control to features. This opens the door to A/B testing, slow rollouts, and a level of safety for the unauthenticated features.

**Comment by chris-kuryak** [comment]
Closing per committee. Will re-write in the future when more information is available and better scoping is necessary.
@stephenkao @kevinhaube
