### ISSUE TITLE
PA Onboarding - Test HL7 with PADOH

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#7507]
## Problem statement

PA DOH will need to test the current HL7 format and content. It is very likely they will require changes to the current submissions.

## Acceptance criteria

- [ ] PA-DOH approves HL7 format

## To do

- [ ] Begin testing cycle with PADOH

**Comment by sliu1000** [comment]
@brick-green - Did you want me to create the Okta accounts?

**Comment by brick-green** [comment]
@sliu1000 no worries, I already took care of it

**Comment by sliu1000** [comment]
Updated Communication from PA:

I have to create a new test organization and need to know the following organization information. 

I also need to know who will be responsible tor updating the account password every 60 days like we talked about.

 

                Organization name

                Organization street address 1

                Organization street address 2

                Organization city

               Organization state
               Organization zip code
               Organization County
               Organization phone number
               Organization CLIA number
               Organization NPI Number
               ELR web service contact first name
                                                         last name
                                                          email address
                                                          phone number
 
If you have any concerns or questions, please contact me.

If asking about PA-ELR, please include ‘PA-ELR: ‘ in the subject line when sending emails.

Thank you for your cooperation.

**Comment by Jcavallo7** [comment]
User provided an update: 

" have created a test PA-NEDSS prime contact account for you. 

I have created a test PA-NEDSS designee for the test ELR web service connection.

 

The accounts are not ready yet as there needs to be some database scripts run by our DBA.  I will let you know when it is completed.  I will then send out the test PA-NEDSS usernames and passwords in separate emails.

 

 

 

If you have any concerns or questions, please contact me.

If asking about PA-ELR, please include ‘PA-ELR: ‘ in the subject line when sending emails.

Thank you for your cooperation."

**Comment by sliu1000** [comment]
updates from PA:

There will be a single feed to PA-DOH (including data from Philadelphia).  PDPH maintains its own surveillance system and worked something out with USDS to have their data sent to them also.  Their data is delivered to them via SFTP. 


Michael G. Eberhart, MPH
Epidemiology Research Associate - Informatics
Pennsylvania Department of Health
Bureau of Epidemiology
meberhart@pa.gov
215-828-7407 (P)
717-772-6875 (F)
http://www.health.pa.gov

**Comment by brick-green** [comment]
Gonna send some production level messages for testing purposes.

**Comment by brick-green** [comment]
Added transport for PA-PHD in production. It points to the test env in PA. This will provide PA will production level data to test. After some data is transferred over, I will check the PA test system for errors and continue from there.

**Comment by brick-green** [comment]
Notes back from PA about the test files. Here are the issues they identified:

Field feedback
---
- Required fields
    - Race missing
        - (BG) this is an issue with the test data generator. These values are present in the live data
    - Gender missing
        - (BG) this is an issue with the test data generator. These values are present in the live data
- Optional fields
    - OBR-16-16 has NPI when OBR-16-1 is blank. 
        - (BG) OBR-16-1 holds the NPI number. There are instances when we receive the provider name but no NPI. Need to ask PA what they want in this scenario
    - OBR-17-1 can be blanked
        - (BG) will add to settings for PA
    - OBX-7 would like to have the Reference Range value
        - (BG) Optional field. Will try to add.
    - OBX-23-2 value should be "L" when OBX-23-1 is present
        - (BG) Will adjust in schema

Additional Notes
---
Some negative tests may not be reportable

**Comment by brick-green** [comment]
- PR out to fix OBX-23.2 and OBR-16.10
- OBR-16.1 and OBR-17.1 have been fixed via PA receiver settings

**Comment by brick-green** [comment]
Sent second round of test messages out

**Comment by brick-green** [comment]
Sent a new round of test messages
[MU_Message_Validation_Tracking_20230309.xlsx](https://github.com/CDCgov/prime-reportstream/files/10936781/MU_Message_Validation_Tracking_20230309.xlsx)

**Comment by brick-green** [comment]
PA said the messages did not go though. I attempted to resend all 6 and got 200 http status response but only 5 messages are appearing on their side. I have a question out to PA to review the 5 that did make it though and to understand why the 6th failed but reported success.

**Comment by brick-green** [comment]
Christina reviewed the structure of the messages from 3/15 and approved all. She asked Michael to review the messages for content.

**Comment by brick-green** [comment]
Got confirmation from Michael that the messages pass validation!!!!!
