### ISSUE TITLE
PA Onboarding - Test SOAP with full feed

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#7508]
## Problem statement

PA uses a SOAP web service. We are currently using that service for the feed to PA counties. We should be able to use that same connection for PA but it will need to be tested.
## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [PA-ELR Interface Specification v1-0.pdf](https://app.zenhub.com/files/304423150/9a3e2569-7ec1-4bd4-bca5-52eb2360ca95/download)

## Acceptance criteria

- [ ] Connection success to PA Testing
- [ ] Connection success to PA Production

**Comment by brick-green** [comment]
Sent an email checking in on this. No word back yet

**Comment by brick-green** [comment]
Christina said she can create the account with a fake phone number for now.

**Comment by sliu1000** [comment]
Update from Sender:

I have created a test PA-NEDSS prime contact account for you. 
I have created a test PA-NEDSS designee for the test ELR web service connection.

The accounts are not ready yet as there needs to be some database scripts run by our DBA.  I will let you know when it is completed.  I will then send out the test PA-NEDSS usernames and passwords in separate emails. 

If you have any concerns or questions, please contact me.

If asking about PA-ELR, please include ‘PA-ELR: ‘ in the subject line when sending emails.

Thank you for your cooperation.

Christina Crawford

**Comment by sliu1000** [comment]
Update from Sender:

I have to get database scripts run yet.  That will occur this week as I have other test accounts to create also.

 

Thanks,

Christina
