### ISSUE TITLE
Universal Pipeline Postman Examples - Submission History Endpoint

### ISSUE THREAD

**Issue by PatriciaPerozoUSDS** [CDCgov/prime-reportstream#7513]
User Story:
As a developer, I want to manually test the Universal Pipeline with a number of examples that will generate error and warning messages.

Description/Use Case
When writing and testing code manually, it would be helpful to have a set of postman examples checked into the repo that can be used to test all of our apis and compare against the expected behavior.

Risks/Impacts/Considerations
Sample data cannot have PII.

Dev Notes:

Acceptance Criteria:
There is a postman example for each of the following in the repo and onboarding instructions that teach new team members how to use them.
**Submission History endpoint** submission that generates:

a response no errors or warning messages
a response no errors with warning messages
a response with errors and no warning messages
a response with both errors and warning messages (if possible)

**Comment by oslynn** [comment]
@PatriciaPerozoUSDS It would be nice that have Postman Collection as well.  Therefore, developers can just load it into their Postman and run it.

**Comment by PatriciaPerozoUSDS** [comment]
Yes @oslynn! The acceptance criteria is for it to be included in the report stream repo for all to use!

**Comment by arnejduranovic** [comment]
This has been resolved so closing.
