### ISSUE TITLE
Write up support documentation for O&O/Support

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7523]
## Problem statement

O&O and Support will need to know where to find information to help out API users with questions about error codes and what to do with them.

## What we know

**Notably absent from the AC is the list of error codes.** The error code documentation will be a part of our API Programmer's Guide, and updated each time we add a new code. O&O will have access to the programmer's guide.

## Acceptance criteria

- [x] A document outlines the intended use of the error code system
- [x] Documents are stored in a place O&O can easily retrieve them
- [x] O&O is briefed on the resources available to them

**Comment by arnejduranovic** [comment]
This story may be moot, due to the fact we now have `0017-serializer-error-codes.md` in the repo.

**Comment by arnejduranovic** [comment]
The Error Codes proposal document, located at https://github.com/CDCgov/prime-reportstream/blob/6ca83c6e4381c7a3e9772509e3d193c2bd4aee8e/prime-router/docs/proposals/0017-serializer-error-codes.md, includes a list of the error codes and their purpose, as well as any additional information the team may need. This document should be kept up to date as new errors are created.
