### ISSUE TITLE
WA - Data Entry Time zone Discrepancy

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#7527]
Hello,
user is: caroline.thomas@doh.wa.gov

User states:

"Results are coming in with UTC timezone which impacts the dates in the message.
Example: results received on 11/30/22 have 12/1/22 dates in them.
This is problematic for us because downstream data users will see the dates (importantly, specimen collection date) as being one day after the case was created in our system.

This was a problem many months ago that was fixed, however, the problem appears to have resurfaced with the transition to the OHP API connection.

We would like date/times to be converted to Pacific time zone before being transmitted."

[Write a short description of what you want to achieve with this task]

User is asking to be switched from different timezone for data entry

## To do

Switch timezone of user data entry

**Comment by brick-green** [comment]
Tried adjusting the settings to these values:

convertDateTimesToReceiverLocalTime: true
timeZone: PACIFIC 
dateTimeFormat: LOCAL

Then I tested locally and it doesn't seem to be working. The datetimes are still coming out in UTC. Gonna keep investigating

**Comment by brick-green** [comment]
Issue has been resolved. Now we need to do the resubmission.[https://app.zenhub.com/files/304423150/49aff590-c831-4ea0-817f-4a80991e2746/download](https://app.zenhub.com/files/304423150/49aff590-c831-4ea0-817f-4a80991e2746/download)

**Comment by brick-green** [comment]
@Jcavallo7 I had a sync with WA today. I confirmed the fix with them so no need to reach out.

**Comment by sliu1000** [comment]
thank you for the update.

**Comment by brick-green** [comment]
Just sent the resubmissions to Caroline Thomas. They will review and let us know if anything else is needed.

**Comment by brick-green** [comment]
Sent another file with Caroline's requested changes.

**Comment by brick-green** [comment]
Confirmation from WA that this can be closed.
