### ISSUE TITLE
Update Programmer's Guide PDF with prototype codes

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7528]
## Problem statement

To effectively communicate that error codes are an experimental feature, the Programmer's Guide needs updated information about Error Responses. Enlist the help of Berni (content, O&O) for content/editing.

## Acceptance criteria

- [ ] API Programmer's Guide PDF on the site has error code information and maps the current error codes to messages

**Comment by kevinhaube** [comment]
Removed from sprint, and sent to Next Items until an updated programmers guide is delivered out of #7619

**Comment by chris-kuryak** [comment]
@kevinhaube Is this ticket for Experience to add the latest API Prog Guide to the website (like update the link to the newest file)?

Like #4874 (old ticket)?

**Comment by chris-kuryak** [comment]
- @GilmoreA6 Is it in scope to add the API Error Codes into the next version of the API Programmers Guide 3.0?
- And if so, do you have all of the info you need from the API team?

cc: @avnieldravid for awareness

**Comment by GilmoreA6** [comment]
@chris-kuryak Chris, that is not something that we I had anticipated adding to this revision but I am not opposed to it if the information is available. I have not discussed this with platform yet.

**Comment by chris-kuryak** [comment]
@avnieldravid Can you check with the API team to see if the error codes for the API are in a format that we can share with the O+O team?

cc: @brandonnava for awareness

**Comment by avnieldravid** [comment]
@arnejduranovic can you update here, once you have agreement on the new error codes?

**Comment by arnejduranovic** [comment]
We just merged the [response code proposal PR](https://github.com/CDCgov/prime-reportstream/pull/7688). Here you will find a table detailing the proposed error codes. We are currently in the process of implementing the proposal, so this document may end up getting updated, depending on what we run into during implementation.

**Comment by chris-kuryak** [comment]
@arnejduranovic Great! And is there an issue # for "implementing" the proposal, or is it all just linked to the proposal PR?

cc: @avnieldravid

**Comment by arnejduranovic** [comment]
> @arnejduranovic Great! And is there an issue # for "implementing" the proposal, or is it all just linked to the proposal PR?
> 
> cc: @avnieldravid

The implementation work is documented/outlined here: https://github.com/cdcgov/prime-reportstream/issues/7453

**Comment by chris-kuryak** [comment]
@arnejduranovic Thanks!

@GilmoreA6 It appears that #7523 is the issue that needs to be completed that will inform your team of the new Error Codes. So I added it as a dependency to this issue. Once it gets finished, we can then circle back around on this. So no action from you at this time. But I want this to slow you down on completing the API Prog Guide update, so just to be clear, proceed without error code info. Let me know if you disagree.

**Comment by chris-kuryak** [comment]
The updated codes have been completed by API team and documented here:
https://github.com/CDCgov/prime-reportstream/blob/6ca83c6e4381c7a3e9772509e3d193c2bd4aee8e/prime-router/docs/proposals/0017-serializer-error-codes.md
Experience team will be using the codes to create more user-friendly error messages as seen by the user on the Validation tool.

O+O handles updating the API programmers guide with the latest codes, so closing this item.
