### ISSUE TITLE
CO - Submission Error

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#7534]
## Problem statement

There was an issue with a file or message submitted by the organization

## What you need to know

File source: CDC PRIME

File name: covid-19-cbeca6d5-a8fa-45e2-bdbb-41b388216f4d-20221124203055.hl7

Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-cbeca6d5-a8fa-45e2-bdbb-41b388216f4d-20221124203055.hl7).

## To do

Help with submission of file

**Comment by GilmoreA6** [comment]
It appears this file was accidently manually retriggered twice from last mile failures. In this case the rejection is CO's system acting as it should and rejecting the second duplicate file. This ticket can be closed.
