### ISSUE TITLE
UP Routing function sends message to Translate function even when data will go to no receivers

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#7545]
There is a need for some queries to see the step runs.  Will need to figure out if there is anything to do here.  Potentially, the proper thing to do here is not to put a message on the translate queue, not translate task, and make sure the generate report next action is NULL.  This is not causing any issues and it is a TINY inefficiency.

### User Story:
As a administrator, I don't want the UP to send data to the Translate function if no receivers will receive data, so it is easier to track where the data went.

### Description/Use Case
The UP sends a message to the Translate function regardless if data will go to a receiver.  The result is that the Translate function does not do anything (which is not bad), but it is an unnecessary message and unnecessary resources used.

### Dev Notes:
* Just change the data or the filters, so data goes nowhere, submit it, then see in the logs how the translate function gets a message, but nothing happens.
* Ensure that the Task, Action, and Report all reflect that there is no next step needed. 
* Ensure that nothing breaks and there is no expectation of a 'translate' step for each submission going through the UP.

### Acceptance Criteria
* The UP only sends messages to the Translate function when data is to be sent a receivers.

**Comment by clediggins-usds** [comment]
This is done so that all messages hit all 3 steps of the UP - convert, route, translate. We *could* remove the translate when not needed, but as it is a cheap no-op it doesn't really matter until we are getting overwhelmed with queue messagews
