### ISSUE TITLE
[FeatureFlags][Design] Global feature toggle UI

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7547]
### Need to know
- This toggle allows admin to turn features on and off globally, for all organizations (not to be confused with the organization settings toggle, which allows admin to turn features on and off for one organization - [ticket 7548](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/7548))
- It will live in the Feature Flag UI that already exists
- Admin must be able to see at a glance: What features are "on" globally and what features are "off"

### Acceptance Criteria
- [ ] Admin can turn feature toggles on and off 
- [ ] Includes name and description of what each feature does
- [ ] Turning on/off has clear implications (and warnings)
- [ ] Points to org settings for organization-level feature flags
- [ ] Include space for 5+ feature flags

**Comment by chris-kuryak** [comment]
Closing per committee. Will re-write in the future when more information is available and better scoping is necessary.
@stephenkao @kevinhaube
