### ISSUE TITLE
SimpleReport - Add TestKit Name ID and Equipment UID

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#7557]
## Problem statement

Some test types cannot be uniquely identified in the LIVD table by the fields simple report is currently sending(model and test performed code). To uniquely identify the test types simple report needs to send two additional fields: TestKit Name ID and Equipment UID.

## What you need to know

LIVD API is available. Example call:

http://prime.cdc.gov/api/metadata/livd?manufacturer=Abbott

## Acceptance criteria

- [ ] every test can be uniquely identified with the data provided by simple report
- [ ] "Test_Kit_Name_ID" is received from SR and corresponds to Testkit Name ID (column M) in LIVD table
- [ ] "Equipment_Model_ID" is received from SR and corresponds to Equipment UID (column O) in LIVD table

## To do

- [ ] ask SR to send "Test_Kit_Name_ID"
- [ ] ask SR to send "Equipment_Model_ID"

**Comment by brick-green** [comment]
Reached out to SR on this. They are going to discuss internally to create a work plan.

**Comment by lg-king** [comment]
@brick-green Can RS accept these fields? Is there a ticket number for this work if it's not already done so we can track it?

**Comment by brick-green** [comment]
@lg-king yes, RS can accept these fields via the SimpleReport manual entry submission. But we did not add the fields for the CSV upload submission schema. Our thought was to start with the manual entry first then move to upload if needed. Does that work?

**Comment by lg-king** [comment]
OK, sounds good. Can you keep me posted on the CSV upload submission schema? For now our plan is to update the manual entry submission schema and we'll hold off on updating the requirements for the bulk upload, but I imagine we'd probably want to update it there as well eventually.

**Comment by lg-king** [comment]
@brick-green Checking in. We are currently adding these fields to the manual entry submission and can pick up the CSV upload submission soon - are you all planning on adding these fields to the CSV upload schema as well?

**Comment by brick-green** [comment]
@lg-king Looks like adding the fields to the CSV upload schema has been merged and it set to go to production with the next deployment.

@GilmoreA6 Can you confirm?

**Comment by GilmoreA6** [comment]
@brick-green yep, They were added as optional field so it should work whether or not they are sent.

**Comment by GilmoreA6** [comment]
@brick-green yep, They were added as optional field so it should work whether or not they are sent.

**Comment by brick-green** [comment]
@lg-king James got those fields added to the schema for CSV Upload submission. So those should be available. Were the fields added to the manual entry submissions?

**Comment by lg-king** [comment]
Ok, great. Not yet - that work is currently in progress.

**Comment by lg-king** [comment]
@brick-green @GilmoreA6 On the bulk upload submissions - does it cause issues if these fields are not added (sounds like they're optional right now), or do you also need to uniquely identify devices on those submissions? We're weighing whether it makes sense to begin requiring this for the bulk uploader (which could cause some user frustration) vs. just including them in the single entry submissions.

**Comment by LaFreda1** [comment]
@brick-green @GilmoreA6 Following up on Laura's question above. Thanks!

**Comment by GilmoreA6** [comment]
@lg-king They are currently optional fields so there won't be problems that don't already exist if they aren't required right away. 

Where we saw issues and what was the genesis for adding these fields is that in some cases the existing fields weren't enough to uniquely identify a row in the LIVD table which caused problems with missing data when sending to receivers.
