### ISSUE TITLE
Errors in the evaluation of UP filter expressions should be recorded

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#7558]
### User Story:
As an administrator, I want ReportStream to log any issues evaluating receiver filter expressions, so I can trace why of data was not sent to a receiver.

### Description/Use Case
Filter expressions for receivers are automatically evaluated to being false if the result of the FHIR Path expression does not evaluate to a boolean.  If someone makes a mistake in an expression, then the filter simply return false and the data will not be sent to a receiver.  There is a warning that gets written to the logs, but those logs are pretty much hard to get to in production.  

### Dev Notes:
* The reason to auto evaluate a bad expression to False is that there is really no reason for the system to retry re-evaluating the filters again when you know 100% that they will fail again.
* But, it is not easy to see that there was a problem.
* I think if there is a syntax error in the FHIR Path then an exception is thrown, but don't remember if it goes into a retry or not.
* Need consistency in this behavior.
* We log a warning instead of an error as we can continue evaluating filters for other receivers.  Maybe this should be an error, but careful with changing the behavior for other uses (e.g. for a schema it is just a warning as we want to generate the data anyways). 
* The Submission History API response has not included this level of errors, so need to define how this will look in the response.

### Acceptance Criteria
* The UP logs an action log error for a given report if there is a syntax error in a receiver filter FHIR Path expression.
* The UP logs an action log error for a given report if there a receiver filter FHIR Path expression does not evaluate to a Boolean expression.
* The Submission History API response includes filter FHIR Expression errors.

**Comment by TurkeyFried** [comment]
From discussion: These messages are not actually useful for the average API user. Instead, these should be logged but not returned in the API response.

**Comment by TurkeyFried** [comment]
From discussion: These messages are not actually useful for the average API user. Instead, these should be logged but not returned in the API response.

**Comment by TurkeyFried** [comment]
From discussion: These messages are not actually useful for the average API user. Instead, these should be logged but not returned in the API response.
