### ISSUE TITLE
Identify missing data in the Deliveries API response for the UP data vs Covid pipeline data

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#7576]
**User Story:**
As a receiver, I expect to receive Deliveries API responses in the same format containing the same information regardless of what pipeline I submitted messages to.

**Description/Use Case**
We need to review the API response for the Deliveries API to identify any missing data between the two pipelines.  We want to figure out if we are missing data or provide data in a different format that may confuse senders.

**Risks/Impacts/Considerations**
* Not all data needs to be the same between the pipelines, so need to research any differences before writing a ticket for it.

**Dev Notes:**

**Acceptance Criteria:**
* Document in this ticket the Deliveries API response differences between the UP and the COVID pipeline.
* Brief the team on the differences and get buy-in on the work needed to make the responses the same.
* Generate new tickets for any work identified.

**Comment by PatriciaPerozoUSDS** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/7576?planning-poker) with Zenhub @jimmyfagan @avnieldravid

**Comment by victor-chaparro** [comment]
Reviewed the API response when for both Covid Pipeline and UP pipeline. The UP is returning the data in the same format the covid pipeline is returning it. No changes required.
