### ISSUE TITLE
Upload new LIVD Table

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7579]
## Problem statement

The LIVD team sent over a new LIVD table that needs to be uploaded into ReportStream.

## What you need to know

[https://app.zenhub.com/files/304423150/48ecaeba-90a0-433d-90bc-466f33688efd/download]

## To do

- [ ] Run livd-table-update command with new table

**Comment by BerniXiongA6** [comment]
hey @brick-green @sliu1000 could we add more details to this ticket? Just trying to establish urgency and priority on this... thanks so much! cc: @brandonnava
