### ISSUE TITLE
Support COVID pipeline features in the UP

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#7589]
E.g. mappers, LIVD table

This is the doc that describes the differences between the COVID and Universal Pipelines:
https://docs.google.com/spreadsheets/d/1na02y8lwK05_HdL36pKEzBuBw7kkSr-G/edit?usp=sharing&ouid=103642664053510831650&rtpof=true&sd=true

**Comment by arnejduranovic** [comment]
@JessicaWNava can you please link the spreadsheet that you worked on to the description of this epic?

**Comment by JessicaWNava** [comment]
> @JessicaWNava can you please link the spreadsheet that you worked on to the description of this epic?

Done!
