### ISSUE TITLE
Identify COVID pipeline features needed in the UP

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#7591]
### User Story:
As ReportStream, I want to be able to process COVID reports using the UP, so I can process all reports in one pipeline.

### Description/Use Case
There are features in the COVID pipeline used for data validation and enrichment that we need to support in the UP if we are to process COVID data.  For example, supporting the LIVD table lookups.  Identify all these features and filter out what is no longer used/needed.

### Risks/Impacts/Considerations
*

### Dev Notes:
* The COVID schemas is a good place to see what is done for senders and receivers.
* There are features in the settings as well.
* See covid_result_metadata as well
* check metabase, see what queries are running and what data they use

### Acceptance Criteria
* Document all the COVID features needed in the UP including features no longer needed.
* Get buy-in from the OO team that you have all the features identified.  Are there any new features they also need?
* Generate the necessary tickets to implement the needed features.

**Comment by TurkeyFried** [comment]
Some of the fields missing on UP but used on COVID schema:
	- test_kit_name_id
	- patient_tribal_citizenship
	- equipment_model_name
	- equipment_model_id
	- test_correction_reason
	- patient_preferred_language
	- employed_in_healthcare
	- resident_congregate_setting
	- first_test
	- symptomatic_for_disease
	- site_of_care

**Comment by JessicaWNava** [comment]
I don't have CDC access, so I do not have access to Metabase to do that portion of this ticket. We may need to put it into a separate one.
