### ISSUE TITLE
High Severity Synk finding: Storage Account allows any traffic by default

### ISSUE THREAD

**Issue by lucasdze** [CDCgov/prime-reportstream#7595]
Detailed paths https://app.snyk.io/org/prime-reportstream/project/bbba8804-ae71-4886-94e4-cf6793434a22
Introduced through: resource › azurerm_storage_account[storage_public] › network_rules › default_action
Show less details 
This issue is...
Azure storage account network rules allow traffic by default

The impact of this is...
Potentially anyone can access storage account over the network

You can resolve it by...
Set default_action attribute to Deny

**Comment by dkrylovsb** [comment]
![image](https://github.com/CDCgov/prime-reportstream/assets/11096575/78402fb2-7eb4-4d40-b72f-5386ccf10bf0)
