### ISSUE TITLE
Markdown for displaying documentation/yml on GitHub

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-reportstream#76]
Content = https://github.com/CDCgov/prime-data-hub/issues/61

**Visualizing data schema**
- Jim has dev-centric version
- Schema-matching tool for demonstration purposes
- How are folks comparing schemas? How do you compare schemas?
- State, county, assc users

**To do**
- [ ] Review Schema .md UX w/Pima (Kat)

**Comment by drew-usds** [comment]
Next steps from 12/16 chat with @MauriceReeves-usds 

- Look into layout edits for current markdown template. Will use md on GH for now.
- Test template with pilot partner - does this documentation help? Meet your needs? What else do you need to know?
- Look into translating to html next, could pave way for more fully-featured documentation site down the line/as we scale.

**Comment by drew-usds** [comment]
Reaching out to Kat to try to schedule time later this week.

**Comment by drew-usds** [comment]
Closing. Outdated.
