### ISSUE TITLE
Capturing exceptions from the React app in Azure (trackException)

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7607]
## Problem statement

Our React application is likely to throw critical errors when utilizing third party packages to support core functionality. We do our due diligence, but software can be unpredictable, and logs are a key site reliability tool we can use to prevent production outages of functionality. 

To capture a log of warnings and errors to aid us in site maintenance and bug troubleshooting, **we should implement Azure App Insights to capture the output of any console warning and error.**

## What you need to know

Our sister application, SimpleReport, seems to have hijacked the console methods and implemented a "track exception" function for app insights when it's a warning or error: [code snippet](https://github.com/CDCgov/prime-simplereport/blob/main/frontend/src/app/TelemetryService.ts#L64-L87)

Azure has _some_ kind of default logging of these that has been triggering PagerDuty for the smallest JavaScript errors. Through conversation, @jeremy-page informed us we can use a string to filter _some_ front end messages from PagerDuty. Work with him or the DevOps team to outline an approach that lets us utilize errors and warnings, **and prevents PagerDuty from receiving unnecessary alerts**.

## Acceptance criteria

- [ ] Azure App Insights maintains a log of exceptions thrown by the React applications (console.warn, console.error)
- [ ] PagerDuty will not be alerted for unnecessary errors in the React application
- [ ] PagerDuty **will** be notified for unexpected failures that require attention

## To do

- [ ] _Use this section to outline your approach as you work, if you'd like!_

**Comment by kevinhaube** [comment]
@CnoteNava For Sprint 58 consideration!

**Comment by stephenkao** [comment]
Reopening because we reverted the change in production: https://nava.slack.com/archives/C01HFHPNJEL/p1671565285613699
