### ISSUE TITLE
Tighten up the idle logout UX

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7610]
## Problem statement

When a user is idle for 15 minutes, they are logged out of the site and dumped back at the beginning of our user experience with no indication that they were ever logged in, where they left off, why they got logged out, etc...

To tighten this user flow, we could:
- Start a countdown after 10 idle minutes to inform the user that they will be logged out soon
- Provide a modal to explain the user was logged out and left off at a certain page

## What you need to know

We will need designs, none exist as far as I can find in Figma. Maybe a good first design item!

## Acceptance criteria

- [ ] Users are notified of an impending idle logout
- [ ] Users are aware of why they were logged out
- [ ] Users have an indication as to where they left off

## To do

- [ ] ...

**Comment by kevinhaube** [comment]
@fmccaf1 @drew-usds @CnoteNava For consideration in upcoming sprints, **and** requires mockups and UX decisions :)

**Comment by chris-kuryak** [comment]
This is low priority for now considering we have so few authenticated external users. Good to re-assess with Design/UX in the future.

**Comment by stephenkao** [comment]
Going to close this because it's not something we want to take on now.  If it becomes a burden for our users, we can create a new ticket and act accordingly.
