### ISSUE TITLE
UP needs to support resending of data per OO process

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#7616]
### User Story:
As an administrator, I want the UP to allow for retransmission of reports, so I can resend data to a STLT after some failure.

### Description/Use Case
OO has a process to resend data.  Currently that process only applies to the COVID/Monkeypox pipeline, but it needs to apply any pipeline. We need to research this process and identify what work we need to do to support that process if any.

### Risks/Impacts/Considerations
* There is a possibility the process/software is COVID pipeline specific and we may need to expand that software instead of the UP.

### Dev Notes:
* Contact OO for a demo and tour of the code.
* The current process seems inefficient, so there is a possibility of making improvements. However, care must taken to make sure we support ONE process for any pipeline.

### Acceptance Criteria
* Document the resend process or link to an existing document.
* Document the work needed to be able to include the UP in the resend process.
* Brief the team with the findings.
* Generate any tickets for work approved by the team.

**Comment by PatriciaPerozoUSDS** [comment]
Brain dump: O&O uses a combination of Pager Duty and the [Last Mile feature](https://reportstream.cdc.gov/admin/lastmile) to get notified about last mile failures and keep tabs on the status of whether a resend has been attempted. 

The query that pulls the reports that have failed and need to be resent (for UI linked above) pulls from the actions and reports table. This works the same for both the UP and the legacy covid pipelines. There are no changes required coming out of this research. The current resend process will be sufficient for the new pipeline.

Query defined here for anyone else that needs to see it: prime-router/src/main/resources/db/migration/V50__add_send_failure_function.sql
