### ISSUE TITLE
Updating Programmer's Guide to Version 3.0

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#7619]
## Problem statement

As a ReportStream user, I want to have updated instructions on how to compile and format data properly so that my company can report required disease results to public health authorities.

## What you need to know

- Current process found at [this SharePoint doc](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Onboarding%20%26%20Ops/Scrum/Processes%20Documented/Updating%20API%20Programmer%E2%80%99s%20Guide.docx?d=w0e55f55dbf5c4d91a4ba53e2bdebfa81&csf=1&web=1&e=mz6rxV)

## Acceptance criteria

- [x] Copy of the previous version of the programmer’s guide (in DOC format) is created and [saved in SharePoint Drive](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/3.%20Instructional%20Design%20Projects/ReportStream%20API%20Programmer%20Guide?csf=1&web=1&e=5NXWz4)

- [x] Technical edits completed on the doc with updates, modifications, or removal of content - by Engineer

- [x] Content edits completed on the doc with  language, punctuation and grammar adhering to content style guidelines and plain language guidelines - by Content SME

## To do

- [x] BX send content edits to originating O&O Engineer

- [x] O&O engr send reviewed edits to reviewing RS Engineer

- [x] Approved content edits send to Experience Team for publishing

**Comment by GilmoreA6** [comment]
Draft of 3.0 available for review

**Comment by BerniXiongA6** [comment]
@GilmoreA6 I can review it today and make edits accordingly -- thanks!

**Comment by GilmoreA6** [comment]
[https://app.zenhub.com/files/304423150/46da254e-5ad8-4db9-be37-58c9a738d54c/download](https://app.zenhub.com/files/304423150/46da254e-5ad8-4db9-be37-58c9a738d54c/download)

**Comment by BerniXiongA6** [comment]
@GilmoreA6 My content edits are ready for Review/QA 

Please note that I uploaded my Word Doc w/ content edits (and formatting and styling) into SharePoint so when you open it inside SharePoint, it might look strange. Best is to download a copy of the Word doc onto your computer and view it from your desktop to get the full effect. 

All links have been tested and should work.

Any broken URLs have been fixed.

Some guidance has been slightly edited for clarity or plain language.

Here's the [SharePoint link](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/3.%20Instructional%20Design%20Projects/ReportStream%20API%20Programmer%20Guide/Version%203.0/Berni%20Edits_ReportStream-Programmers-Guide-v3.0_rev20230103.docx?d=wcb5f0342dc9447db8dcb8a7a7dde81e9&csf=1&web=1&e=vjb1p4)

**Comment by GilmoreA6** [comment]
Meeting with experience set for 2/2/23 for Programmer's Guide Content sync

**Comment by LaFreda1** [comment]
@GilmoreA6 Any updates from the meeting on 2/2/23?

**Comment by GilmoreA6** [comment]
@LaFreda1 We had another meeting today 02/08/23 to complete going through the entire document with Experience (ticket #7683). The next steps are (#5809) making edits to the content based on what we've discussed.

**Comment by GilmoreA6** [comment]
Moved into prod
