### ISSUE TITLE
Add support for outbound SMTP to Metabase

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#7624]
Sharon Liu's team would like to be able to configure alerts in Metabase. To get alerts working we will need to provide outbound SMTP access for Metabase.

SR is already doing this, maybe we can copy their work.

**Comment by lucasdze** [comment]
https://docs.sendgrid.com/for-developers/partners/microsoft-azure-2021

**Comment by lucasdze** [comment]
https://adamtheautomator.com/azure-send-email/

**Comment by lucasdze** [comment]
https://stackoverflow.com/questions/39053329/sendgrid-not-working-from-azure-app-service

**Comment by lucasdze** [comment]
resolved
