### ISSUE TITLE
Total page views with membership metadata

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7625]
## Problem statment

Application insights transmits a ping every time you land on a new page of the site. To make any use of this metric beyond counting a page's hits, **we need to pass back some user metadata to give insight into who's hitting the pages**. 

>~~`needs-info`: @CnoteNava @JGreenFearless  We should meet to iron out the insight dashboard item for this metric.~~
Answered :D

## Acceptance criteria

- [x] Front-end page hits are sent out with membership metadata
- [x] Azure can query page views and use membership data to filter their query
- [x] Dashboard item shows types of users by day (sounds maybe like a stacked bar graph)

**Comment by kevinhaube** [comment]
Updated item...
>Dashboard item shows types of users per page by day (sounds maybe like a stacked bar graph)

@chris-kuryak Can you confirm this is what we hope to see from page hit and demographic data for mvp?

**Comment by chris-kuryak** [comment]
@kevinhaube Yes, total users of each type per page by day. 
As long as the total number of user type X on day Y is attainable, I don't think it matters the type of graph shown/used for this MVP.

**Comment by penny-lischer** [comment]
@chris-kuryak 'per day' is the last 24 hrs acceptable, or would you like insights for the last x number of days?

**Comment by chris-kuryak** [comment]
@penny-lischer Ideally, something like each day (midnight to midnight) as a separate column on the x-axis of a bar chart where you can choose the last Y number of days to be shown. However, if not possible now, perhaps just showing the past 7 days as standard would be a great start.

**Comment by penny-lischer** [comment]
let usg_events = dynamic(["*"]);
let mainTable = union pageViews
    | where timestamp > ago(7d)
    | where isempty(operation_SyntheticSource)
    | extend name =replace("\n", "", name)
    | extend name =replace("\r", "", name)
    | where '*' in (usg_events) or name in (usg_events);
let queryTable = mainTable;
let splitTable =  () {
    queryTable
    | extend member_type = parse_json(tostring(customDimensions["activeMembership"])).memberType
    | extend member_type = iif(isempty(member_type), "<undefined>", member_type)
};
let cohortedTable = splitTable
    | where 'user_Id' != 'user_AuthenticatedId' or ('user_Id' == 'user_AuthenticatedId' and isnotempty(user_Id))
    | where member_type != "<undefined>"
    | extend byDimension = bin(timestamp, 1d)
    | summarize metricHll = hll(user_Id) by byDimension, member_type;
let topSegments = cohortedTable
    | summarize mergedMetricHll = hll_merge(metricHll) by member_type
    | project member_type, dcount_user_Id = dcount_hll(mergedMetricHll)
    | top 5 by dcount_user_Id desc nulls last
    | summarize makelist(member_type);
cohortedTable
| extend member_type = iff(member_type in (topSegments), member_type, "Other")
| project byDimension, member_type, metricHll
| summarize page_views = hll_merge(metricHll) by member_type, byDimension
| project byDimension, member_type, page_views = dcount_hll(page_views) 
| render columnchart

**Comment by penny-lischer** [comment]
![Screenshot 2022-12-22 at 2.36.00 PM.png](https://images.zenhubusercontent.com/62697ac1be6e84867ab47e74/6ec33d45-f306-46be-9102-592eba548eb6)

**Comment by penny-lischer** [comment]
![Screenshot 2022-12-29 at 10.12.19 AM.png](https://images.zenhubusercontent.com/62697ac1be6e84867ab47e74/b6dac99e-4fab-431f-adf0-916a512fb645)![Screenshot 2022-12-29 at 10.12.51 AM.png](https://images.zenhubusercontent.com/62697ac1be6e84867ab47e74/dadc51d5-7793-4bd6-8dcc-5b996600d8c6)

**Comment by chris-kuryak** [comment]
Just so we are aligned, this looks great but appears to miss the "per page" acceptance criteria is still the sticking point on this specific issue as written. In other words, the ability to pick out a specific page and just see the total page views by user type on that page.

@stephenkao @penny-lischer I leave to y'all to decide to either (a) remove that requirement from the acceptance criteria and create a new ticket to address it in the next sprint, or (b) continue to work on that for this sprint.

**Comment by stephenkao** [comment]
Ah, great call Chris!

@penny-lischer Would it be possible to add a filter by either `name` or `url` for the "Total Page Views by Member Type" graph?  If we need something that's a little cleaner/more readable, we could also update the automatic data collection to include, say, `Support` as a page name rather than `Support | CDC Prime ReportStream`.

**Comment by chris-kuryak** [comment]
@stephenkao @penny-lischer 
I removed the "per page" acceptance criteria from this issue since it seemed to be a sticking point. I am creating a new ticket #7884

**Comment by chris-kuryak** [comment]
Reviewed and working. Closing accordingly.
