### ISSUE TITLE
Session count with membership metadata

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7626]
## Problem statment

Right now, there is no effective way for us to tell who's logging into the site when, and how often. To better understand the behavior of our organizations/users in ReportStream, **an insight dashboard item should show counts of sessions sorted by `memberType`** on the Application Insights dashboard

## Acceptance criteria

- [X] Front-end data is sent with unique session id
- [x] Azure can query the `AppEvents` table and group by unique session id
- [x] Dashboard item shows the count for each memberType's unique sessions

**Comment by penny-lischer** [comment]
Do we want to view session counts over a 24 hr period? what timeline?

**Comment by penny-lischer** [comment]
@kevinhaube I'm assuming only authenticated users since we are referring to membership metadata/member_type

**Comment by kevinhaube** [comment]
@penny-lischer Great question; in my current understanding, yes! Not sure if we have a way to get a moderately accurate count of truly unauthenticated users since everyone starts out without being logged in, thus generating both authenticated and unauthenticated membership metadata on every use.

That'd be a tricky query, but if you figured that out, that'd be cool! Something like "where a single session ID has both undefined and defined membership info" to determine an authenticated user who just hasn't logged in yet. But **not necessary** for this ticket!

**Comment by penny-lischer** [comment]
//Session Count by Member Type within 24 hrs

let usg_events = dynamic(["*"]);
let mainTable = union pageViews, customEvents, requests
    | where timestamp > ago(1d)
    | where isempty(operation_SyntheticSource)
    | extend name =replace("\n", "", name)
    | extend name =replace("\r", "", name)
    | where '*' in (usg_events) or name in (usg_events);
let queryTable = mainTable;
let splitTable = () {
    queryTable
    | extend dimension = todynamic(tostring(customDimensions["activeMembership"]))
    | evaluate bag_unpack(dimension)
    | extend memberType = iif(isempty(memberType), "<undefined>", memberType)
};
let cohortedTable = splitTable
    | where 'user_Id' != 'user_AuthenticatedId' or ('user_Id' == 'user_AuthenticatedId' and isnotempty(user_Id))
    | where memberType != "<undefined>"
    | extend byDimension = bin(timestamp, 1h)
    | summarize metricHll = hll(session_Id) by byDimension, memberType;
let topSegments = cohortedTable
    | summarize mergedMetricHll = hll_merge(metricHll) by memberType
    | project memberType, dcount_session_Id = dcount_hll(mergedMetricHll)
    | top 5 by dcount_session_Id desc nulls last
    | summarize makelist(memberType);
cohortedTable
| extend userId = iff(memberType in (topSegments), memberType, "Other")
| project byDimension, userId, metricHll
| summarize metric = hll_merge(metricHll) by userId, byDimension
| order by userId asc, byDimension desc
| project ["Date/time"]=byDimension, ["Membership Type"]=userId, ["Session Count"] = dcount_hll(metric)
| render columnchart

**Comment by penny-lischer** [comment]
![Screenshot 2022-12-27 at 10.19.57 AM.png](https://images.zenhubusercontent.com/62697ac1be6e84867ab47e74/5be69b5f-c3d1-4021-ae62-e9598aff69a6)

**Comment by penny-lischer** [comment]
![Screenshot 2022-12-29 at 10.12.24 AM.png](https://images.zenhubusercontent.com/62697ac1be6e84867ab47e74/9de80e86-1dab-4d3d-91d8-f5b77e91648c)

**Comment by chris-kuryak** [comment]
Reviewed and working. Closing issue.
