### ISSUE TITLE
Session duration with membership metadata

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7627]
## Problem statment

Usage statistics for our website are a mystery. We know that people hit the site, because we see unique session ids coming through production app insights. We **don't** know, however, how long they're using the site for, nor can we relate their session ID to a set of actions. To better understand how long different types of users are on the site, **app insights should show a breakdown of average session times per memberType**, and when observing the tracked event, I should be able to pull a session ID and query the `AppEvents` table for event logs.

## Acceptance criteria

- [X] Front-end data is sent with unique session id
- [x] Session length data is sent to App Insights with session id
- [x] Azure can query the `customEvents` table and find the actions of a single session
- [x] Dashboard item shows the average time spent on the app for each memberType

**Comment by kevinhaube** [comment]
Identified #7730 as the blocker, adding blocked label and starting on the fix.

**Comment by etanb** [comment]
@kevinhaube would love to sync up with you on this ticket!

**Comment by etanb** [comment]
Talked with Chris, and for this MVP, the concept of a session will be the following:

- begins when a user first loads up the ReportStream website
- we ignore the concept of logged in and logged out
- we will attach the member type to the response
- if possible, pause session timer when user navigates to a different tab
- ends when a user navigates away from the page which includes: closing browser, closing tab

We will also want a view in the Azure dashboard that aggregates session length counts into buckets (0-1 min, 1-5 min, 5 - 10 min, 10 - 20 min, Over 20 min) to see the distribution -- Chris.

Let me know if this sounds good to everyone! cc @stephenkao and @kevinhaube for visibility

**Comment by kevinhaube** [comment]
Nice!! Love the idea of binning the times rather than taking a general average for each member type. Gives us granularity!

**Comment by stephenkao** [comment]
@etanb Makes sense to me as well!

One thing--

> we will attach the member type to the response

We're already [adding the user's `activeMembership` to every AI event tracked](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/TelemetryService.ts#L43) (including automatic ones like PageViewData and RemoteDependencyData) -- is there anything more we need to do here?

**Comment by chris-kuryak** [comment]
@stephenkao @penny-lischer 
I am not familiar with the technical aspect of this as I'm unsure if sessions are built into AI, or if Etan is creating something new here. Any insights you can lend here would be appreciated.

I assume that if we are passing membership data with every AI event we track, then it should automatically be queryable with session data on the AI side of things?

**Comment by kevinhaube** [comment]
Yep, we are currently packing the following data shape, identified as `activeMembership` or the `MembershipSettings` interface, to every App Insights telemetry transmission:

```typescript
export interface MembershipSettings {
    // The org header value
    parsedName: string;
    // The type of membership
    memberType: MemberType;
    // Optional service name (i.e. "elr", "default")
    service?: string;
}
```
There shouldn't be any need to add this in ad-hoc as we can query by any of those values within Azure currently. See @penny-lischer's work on #7805 for an example of implementing custom metrics.

**Comment by etanb** [comment]
@chris-kuryak with the code merged, and the future Dashboard shared from Azure, can I close this?

**Comment by penny-lischer** [comment]
@etanb can you please add the query for the Azure dashboard to this ticket?

**Comment by etanb** [comment]
there's some editing we can do to the query, like the time portion, but here:

```
let usg_events = dynamic(["*"]);
let mainTable = union customEvents
    | where timestamp > ago(200h)
    | where isempty(operation_SyntheticSource) //filtering out HTTP requests made by bots
    | extend name =replace("\n", "", name)
    | extend name =replace("\r", "", name)
    | where '*' in (usg_events) or name in (usg_events);
let queryTable = mainTable;
let splitTable =  () {
    queryTable
    | extend timeInSeconds = todynamic(tostring(customDimensions["sessionLength"]))
    | evaluate bag_unpack(timeInSeconds)
    | order by timestamp desc
};
splitTable
```

**Comment by chris-kuryak** [comment]
Closing per meeting all ACs per Etan's comment above
