### ISSUE TITLE
Pagination usage by Table

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7628]
## Problem statment

Pagination is a useful tool for segmenting data in views, so users only see what they need, and we don't have to fetch a gajillion (real number, probably) results for them all at once. However, our pagination _does_ fetch quite a bit. With a page size of 10, we're fetching 6 pages worth of content on the first load. **To effectively tell whether or not we _need_ to be fetching this much data on first load, we can implement app insights to show the number of times any given page number is viewed on each table.**

## Acceptance criteria

- [x] Insights can be broken up table-by-table since not all tables serve the same purpose and each table may have different needs
- [x] Azure can query the `AppEvents` table and find insights on which pages of a table are access, and by whom (membership metadata)
- [x] Dashboard item shows the trend of page use per-table
- [x] Dashboard filterable by membership Type

## Developer notes
- We'll need to settle on a unique event name wherever the Pagination component is rendered (e.g., "Daily Data" versus "Submissions"), but the implementation should be fairly simple!  We can track `pageSize` and `pageNumber` as custom metrics of this event.

**Comment by penny-lischer** [comment]
//Pagination Usage by Table

let usg_events = dynamic(["Daily Data | Table Pagination", "Submissions | Table Pagination"]);
let mainTable = union customEvents
    | where timestamp > ago(90d)
    | where isempty(operation_SyntheticSource)
    | extend name =replace("\n", "", name)
    | extend name =replace("\r", "", name)
    | where '*' in (usg_events) or name in (usg_events)
    | where true;
let byTable = mainTable;
let queryTable = () {
    byTable
    | extend dimension = customDimensions["tablePagination"]
    | extend dimension = iif(isempty(dimension), "<undefined>", dimension)
};
let byCohortTable = queryTable
    | project name, dimension;
let topSegments = byCohortTable
    | summarize Events = count() by name, dimension
    | summarize make_list(dimension,1000);    //Returns a dynamic JSON array of all the values of Expr in the group. Needed here.
let topEventMetrics = byCohortTable
    | where dimension in (topSegments);
let otherEventUsers = byCohortTable
    | where dimension !in (topSegments)
    | extend dimension = "Other";
otherEventUsers
| union topEventMetrics
| summarize Events = count() by name, dimension
| order by dimension asc
| render columnchart
with (
    xtitle="Table",
    ytitle="Counts",
    title="Pagination Usage by Table")

**Comment by penny-lischer** [comment]
![Screenshot 2023-01-12 at 11.25.14 AM.png](https://images.zenhubusercontent.com/62697ac1be6e84867ab47e74/a65a97c6-99e1-4997-9e26-338606fede68)

**Comment by penny-lischer** [comment]
Two possible solutions for adding Member_type:
1. Make a table similar to what you did with the PageView by Page by Member type, so that you can see the total clicks/views of each pageNumber by member type (in separate columns)
2. Create a chart showing PageNumber on the x-axis, membership type by color on a stacked bar chart. Much like our existing charts, but instead of date being the x-axis, it is PageNumber.

**Comment by penny-lischer** [comment]
// Table View
let usg_events = dynamic(["Daily Data | Table Pagination", "Submissions | Table Pagination"]);
let mainTable = union customEvents
    | where timestamp > ago(30d)
    | where isempty(operation_SyntheticSource)
    | extend name =replace("\n", "", name)
    | extend name =replace("\r", "", name)
    | where '*' in (usg_events) or name in (usg_events)
    | where true;
let byTable = mainTable;
let queryTable = () {
    byTable
    | extend dimActiveMembership = todynamic(tostring(customDimensions["activeMembership"]))
    | evaluate bag_unpack(dimActiveMembership)
    | extend member_type = iif(isempty(memberType), "unauthenticated", memberType)
    | extend dimTablePagination = todynamic(tostring(customDimensions["tablePagination"]))
    | evaluate bag_unpack(dimTablePagination)
};
let byCohortTable = queryTable
    | project name, member_type, pageSize, pageNumber;
let topSegments = byCohortTable
    | summarize PageCount = count() by name, member_type, pageSize, pageNumber
    | project
    ["Event Name"] = name,
    ["Page Size"] = pageSize,
    ["Page Number"] = pageNumber,
    p = pack(strcat(member_type, " Table Page Count"), PageCount) //Creates an object that contains keys and values i.e. {"prime-admin Table Page Count", "3"}
| summarize b = make_bag(p) by ["Event Name"], ["Page Size"], ["Page Number"] //Creates a dynamic JSON property bag (dictionary) of all the values of expr in the group.
| evaluate bag_unpack(b) //transforms the bag keys in the make_bag() output into columns
| order by ["Event Name"] asc, ["Page Size"] asc, ["Page Number"] asc;
topSegments

**Comment by penny-lischer** [comment]
![Screenshot 2023-01-19 at 1.09.13 PM.png](https://images.zenhubusercontent.com/62697ac1be6e84867ab47e74/e13a2f5a-6768-422a-ae7f-e2a5b417cd2e)
