### ISSUE TITLE
Filters usage with feature info and membership data

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7629]
## Problem statment

Table filtering is useful for limiting the data you're seeing. On our site, we currently have date filtration on Daily Data and Submission History. To tell whether we're delivering value with these filters, **an insight should show us how many days the query range covered, the day it was called, which organization used this, using which table's filters**.

>~~`needs-info`: @CnoteNava @JGreenFearless  We should meet to iron out the insight dashboard item for this metric~~
Answered! :D

## Acceptance criteria

- [X] Insights data transmits with membership metadata
- [x] Insights can be broken up table-by-table since not all tables serve the same purpose and each table may have different needs
- [x] Azure can query the `AppEvents` table and find insights on what dates users query for on a given day
- [x] Dashboard item to show the range size of data queried through Daily Data and Submission History

## Developer notes
- We can use the [useTrackEvent hook](https://learn.microsoft.com/en-us/azure/azure-monitor/app/javascript-react-plugin#usetrackevent) in the filters component.  We can track the `from` and `to` timestamps as part of this custom event.

**Comment by kevinhaube** [comment]
Updated statements:
>...an insight should show us how many days the query range covered, the day it was called, which organization used this, using which table's filters.
>
> Dashboard item to show the range size of data queried through Daily Data and Submission History
@chris-kuryak Updates based on convos and outcomes from yesterday along tracking date range filter usage

**Comment by penny-lischer** [comment]
![Screenshot 2022-12-29 at 12.05.48 PM.png](https://images.zenhubusercontent.com/62697ac1be6e84867ab47e74/342c59cf-ac8f-4dad-a0d7-f77f414a6859)

**Comment by penny-lischer** [comment]
//Table Filters usage with feature info and membership data
let usg_events = dynamic(["*"]);
let mainTable = union customEvents
    | where timestamp > ago(90d)
    | where isempty(operation_SyntheticSource)
    | extend name =replace("\n", "", name)
    | extend name =replace("\r", "", name)
    | where '*' in (usg_events) or name in (usg_events)
    | where isnotempty(customDimensions["tableFilter"])
    | extend ActiveMembership = todynamic(tostring(customDimensions["activeMembership"]))
    | evaluate bag_unpack(ActiveMembership)
    | extend TableFilter = todynamic(tostring(customDimensions["tableFilter"]))
    | evaluate bag_unpack(TableFilter);
let queryTable = mainTable;
queryTable
| extend TimeDiff = datetime_diff('day', todatetime(endRange), todatetime(startRange))
| summarize hll = hll(itemId) by tostring(TimeDiff), name, tostring(todatetime(startRange)), parsedName
| summarize merged = hll_merge(hll) by tostring(TimeDiff), name, tostring(todatetime(startRange)), parsedName
| order by TimeDiff desc 
| project
    ["No. Days in Range"] = TimeDiff,
    ["Total Counts"] = dcount_hll(merged),
    ["Start Date"] = startRange,
    ["Table Filter Name"] = name,
    ["Organization Name"] = parsedName;
queryTable

**Comment by penny-lischer** [comment]
![Screenshot 2022-12-29 at 1.16.45 PM.png](https://images.zenhubusercontent.com/62697ac1be6e84867ab47e74/7fff4e81-171d-4692-a0a1-8abb9eaabc03)

**Comment by chris-kuryak** [comment]
@penny-lischer Looks great. I believe this covers the requirements of the MVP. Thanks!

**Comment by kevinhaube** [comment]
@chris-kuryak @penny-lischer This is awesome!!! This is how I'm used to handling data; pulling from tables to create a more refined tabular set of data. But from here, Chris, I see like at _least_ 4 good insights. I'm wondering if this is a better method: building out these nice tabular sets of data, then using _these_ generated sets to generate smaller queries for graphs. Penny says she's got prior experience in Azure App Insights; would love to know if that's what "Workbooks" are meant to be!

**Comment by penny-lischer** [comment]
![Screenshot 2023-01-01 at 9.25.58 PM.png](https://images.zenhubusercontent.com/62697ac1be6e84867ab47e74/695cc36f-f40a-4d95-b239-24ff8e7c8f0d)

**Comment by chris-kuryak** [comment]
Reviewed. Chart looks good.
