### ISSUE TITLE
Code interview: Genabio

### ISSUE THREAD

**Issue by fmccaf1** [CDCgov/prime-reportstream#7654]
Link coding document [here](https://docs.google.com/document/d/1F92JxCCJ0pipuemGgRyvc9vOdHdZ3uA_u43sDoPl15g/edit#).

**Comment by fmccaf1** [comment]
cc: @lizzieamanning 
Feel free to estimate a number of points on this ticket. I would probably recommend a 2, but up to you.

**Comment by lizzieamanning** [comment]
Notes [here](https://docs.google.com/document/d/1F92JxCCJ0pipuemGgRyvc9vOdHdZ3uA_u43sDoPl15g/edit#)
