### ISSUE TITLE
Clean up enumerations with duplicate mime types

### ISSUE THREAD

**Issue by jimmyfagan** [CDCgov/prime-reportstream#7656]
### User Story:
As a RS developer, I want to prevent having duplicate information about file formats (including mime types) in different enums.

### Description/Use Case
In the Pull Request for changes in #7402, [Carlos pointed out](https://github.com/CDCgov/prime-reportstream/pull/7543#discussion_r1039833168) that we have mime types in both `Sender.Format` and `Report.Format`. This ticket involves consolidating those two `Format` enums to prevent that info from being stored in two locations.

### Risks/Impacts/Considerations
* Automated tests should verify that these changes don't impact functionality
* It's possible some unit tests will become redundant, depending on how these structures are consolidated

### Dev Notes:
* See `Sender.Format` and `Report.Format`
* This looks like duplication of code, so will need to refactor in order to use a common set of mime types.

### Acceptance Criteria
* Mime types for file formats are listed in one place in the code.

**Comment by david-navapbc** [comment]
* MIME types are not in a new enum class `MimeFormat` 
* where possible, we're using MIME constants from fhir library we're already using 
* everything looking for `Sender.Format` or `Report.Format` now points to `MimeFormat`
