### ISSUE TITLE
Dendi Onboarding - Validate Test Files 

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#7660]
### Acceptance Criteria 
- [x] Sample file from sender received by RS team 
- [x] Sample files saved to Keybase by assigned RS engineer 
- [x] Sample file ingested into RS using validation UI tool by assigned RS engineer 
- [x] Feedback provided to sender by assigned RS engineer  (including instructions on what to modify in order to get validated)* 
- [ ] Sender modifies and re-sends sample file to get file validated by RS engineer* 

*Steps can continue until RS can ingest the file from sender 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with sender 
- [ ] RS team member who originates this ticket: add any dependencies, as needed 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Sender" 
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by sliu1000** [comment]
Update from Sender:

Happy New Year.

Here are the followup items:
•	Connectivity: can you share the SFTP connectivity details [URL , username etc.] ?  
o	As we will be supporting numerous clients [laboratories], can we send client-specific files to designated folders [via the same connection]?
•	Report format: can you confirm if the report sample is acceptable [the file was shared earlier] ?
Best regards,

Shatabdo Banerjee
dendisoftware.com

**Comment by sliu1000** [comment]
Update from sender:

Hope you're doing well.

Can you  share the ETA for sprint review? 
We will use the Shared Secret Key (KeyBase) connectivity option:
•	Can you confirm the timeline for creating our client-id ?
Best regards,

Shatabdo Banerjee

**Comment by Jcavallo7** [comment]
user update:

Hi Reportstream team,

Can you share the following details:
How do we get the specific client id for our client 'modMD'?
How do we get the Auth token?
How do we get access to the sandbox?
When can we get on a call with the ReportStream team to discuss high level steps?

**Comment by GilmoreA6** [comment]
Hi Shatabdo,

I've evaluated the test file and there are a couple of items that need correction:

1.) The test_result column is required. The value in this column should follow the guidance in column E of the LIVD-SARS-CoV2 table (https://www.cdc.gov/csels/dls/livd-codes.html). Either the Snomed code or the common text value is accepted (e.g "Positive" or "260373001"

2.) ordering_provider_zip_code is a required field and cannot be left blank

3.) ordering_provider_phone_number is a required field and cannot be left blank

4.)equipment_model_name is a required field and cannot be left blank. This field should match with column B of the LIVD-SARS-CoV2 table (https://www.cdc.gov/csels/dls/livd-codes.html
LOINC In Vitro Diagnostic (LIVD) Test Code Mapping
The LIVD specification outlines an industry-defined format to facilitate the publication and exchange of LOINC codes for vendor IVD test results, based on either vendor IVD test transmission codes or manual test identification, for use by laboratory personnel or laboratory applications.
www.cdc.gov
)

5.) For the datetime fields the preferred format is yyyymmddHHMMSS+zzzz where zzzz is the datetime offset from UTC. (e.g. if you were reporting values in the Pacific Timezone you would put 20230124000000-0800 for January 24th, 2023 00:00:00 PDT). If you do not include the offsets ReportStream will assume all datetimes are in UTC.

If you could make these corrections and submit a new test file that would be appreciated. The next step after this will be submitting to our staging environment. We have two options for authentication (described in the Programmer's guide starting on page 9). The first and preferred option is token authentication. For this we would need you generate a public/private keypair and to send us the public key that we store in our database. You would then send a signed JWT and receive a token that you would then send in with your submission.

For the second method (shared secret) we would generate a secret key and send it to you via encrypted message. You would then used that secret key with each submission. Let me know which direction you would like to go.

Thanks,

James

**Comment by GilmoreA6** [comment]
How do we get the specific client id for our client 'modMD'?
Will you require a unique client id for each client? In this case we will set up each client as an individual organization and can use modMD as the client id. The other option is to set Dendi up as it's own org and you can use that for every client.
How do we get the Auth token?
You will need to generate two public/private keypairs (one for staging and one for production) and send us the public keys that we will store. Then following the process on page 9 of the programmer's guide you would send a signed JWT to the token endpoint and receive the auth token. (https://reportstream.cdc.gov/assets/pdf/ReportStream-Programmers-Guide-v2.3-updated.pdf)
How do we get access to the sandbox?
I'm not sure what you are referring to here. We do not currently have a sandbox environment. After we receive a successful example file, the next step is to send to our staging environment.
When can we get on a call with the ReportStream team to discuss next steps?
What is you availability for Thurday or Friday this week? We can set up a quick call to answer questions you may have.

**Comment by GilmoreA6** [comment]
Hi Shatabdo, 

See answers below in red:

How do we get the specific client id for our client 'modMD'?
Will you require a unique client id for each client? In this case we will set up each client as an individual organization and can use modMD as the client id. The other option is to set Dendi up as it's own org and you can use that for every client.
How do we get the Auth token?
You will need to generate two public/private keypairs (one for staging and one for production) and send us the public keys that we will store. Then following the process on page 9 of the programmer's guide you would send a signed JWT to the token endpoint and receive the auth token. (https://reportstream.cdc.gov/assets/pdf/ReportStream-Programmers-Guide-v2.3-updated.pdf)
How do we get access to the sandbox?
I'm not sure what you are referring to here. We do not currently have a sandbox environment. After we receive a successful example file, the next step is to send to our staging environment.
When can we get on a call with the ReportStream team to discuss next steps?
What is you availability for Thurday or Friday this week? We can set up a quick call to answer questions you may have.

Thanks,

James

**Comment by sliu1000** [comment]
Update from Dendi:
Hi James,
1.	Please set up Dendi LIS  as it's own org and we will use that connection for every client.
2.	We will use the first and preferred option: token authentication to connect to reportstream Rest API
1.	 We can generate a public/private keypair and to share the public key with you
2.	 Is there a separate url for Staging and Prod? Can you share the details?
3.	We should have the .pem file ready to share by next Friday 2-3-23
3.	The sample file was shared on 1-27-2023
1.	Awaiting feedback from James
Best regards,

Shatabdo Banerjee
dendisoftware.com

**Comment by GilmoreA6** [comment]
waiting for public keys from Dendi
