### ISSUE TITLE
Publish What's New - Dec 2022 Update

### ISSUE THREAD

**Issue by HeatherRienks** [CDCgov/prime-reportstream#7664]
## Problem statement
As a user, I would like to know what features, bugs, other user facing updates have been made to ReportStream product.

## Acceptance criteria

Please check the box corresponding with your name when you have finished editing the "Content Updates" document.

- [ ]  Berni's done
- [ ]  Heather's done
- [ ] Florence published to RS

**Comment by HeatherRienks** [comment]
@fmccaf1 - let's show @jillian-hammer how to update RS site!

**Comment by HeatherRienks** [comment]
@chris-kuryak & @brandonnava - This is def something that you will want to note, as Berni/Flo/I were handling this.

@kevinhaube is also familiar with how this works. Link to process is in the associated Epic (#6995)

**Comment by chris-kuryak** [comment]
@HeatherRienks Set up a recurring monthly meeting for Brandon, Stephen, and I to review this.
cc: @stephenkao

**Comment by fmccaf1** [comment]
Just covered the release notes process w/ Lizzie and Jillian

**Comment by chris-kuryak** [comment]
@jillian-hammer @lizzieamanning 
Here are the release notes for Dec 2022:

- To assist in onboarding new labs and facilities that would like to send data through ReportStream, we have added a new resource: [Guide to Submitting Data to ReportStream](https://reportstream.cdc.gov/resources/getting-started-submitting-data)

- In an effort to be as useful as possible to ReportStream users and visitors, we have updated the content several items on the ReportStream website including: [Account Registration Guide](https://reportstream.cdc.gov/resources/account-registration-guide), [Guide to Receiving ReportStream Data](https://reportstream.cdc.gov/resources/getting-started-public-health-departments), [Manual Data Download Guide](https://reportstream.cdc.gov/resources/data-download-guide)


cc: @kevinhaube @brandonnava @stephenkao for awareness

**Comment by jillian-hammer** [comment]
Updated and submitted PR with @kevinhaube as reviewer!

**Comment by kevinhaube** [comment]
Approved and merged! :)

**Comment by chris-kuryak** [comment]
Merged and published in early Jan.
