### ISSUE TITLE
[SPIKE] Split out markdown content to a separate bundle

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#7675]
## Problem statement

Some of our markdown content is currently [imported into the main bundle](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/content/product/index.ts#L14-L15).  This means that the main.js file we serve for JavaScript on the site will grow linearly with the amount of markdown content we add -- which means a delay in the time to interactivity.  We should look into splitting out markdown content into its own bundle(s) so it's only requested on demand rather than on page load.

## What you need to know

There are some libraries that handle this logic already, like [react-async-component](https://github.com/ctrlplusb/react-async-component) which ties nicely into Webpack's `import`.  It's worth looking into if this still works well or if we should look for another library.

## Acceptance criteria

- [ ] A new markdown bundle is created
- [ ] The `main` bundle's size is reduced by (about) the size of the markdown bundle (minified, gzipped)

**Comment by jpandersen87** [comment]
This should be possible as a built-in feature of create-react-app (https://create-react-app.dev/docs/code-splitting/) already.

**Comment by stephenkao** [comment]
Closing -- this isn't a high-priority item, and we can create a front-end optimizations epic now that we're off CRA and we have more visibility/flexibility into our capabilities.
