### ISSUE TITLE
Intrivo- Validation Errors for messages being sent to VT

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7677]
Receiver VT contacted Intrivo to resolved certain validation errors for messages being sent to VT.  The findings are as follows:

1) PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBSERVATION[0].OBX.ObservationMethod[0].NameOfCodingSystem"
Description="Situational rule violated"/>

We are providing the value `99ELR` for that field which is not apparently considered valid by VT.

2) We also received these errors from them:
 PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.PlacerOrderNumber.EntityIdentifier"
Description="Required field missing"/>

3) PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBR.PlacerOrderNumber.EntityIdentifier"
Description="Required field missing"/>

Special Request from Andrew (NIH). Would like ReportStream to fix this issue instead of asking Intrivo to resend the messages.

Other Relevant Information from Intrivio:
I believe these were optional fields from ReportStream. In any case, what would be acceptable values for these fields?

### What You Need to Know
- Per Andrew Gross/VT Dept of Health: "The accession numbers for all of the failed messages coming from Intrivo are 123456. I’m unsure of the explanation for that, but that is what we are seeing on our end."

**Comment by BerniXiongA6** [comment]
BX replied to the email thread with both Intrivo and RADx Mars teams. Let's bring into this or the next sprint if we have bandwidth. Will need refinement first. cc: @brandonnava @brick-green 

> Hi All, 
> 
> Let me reach out to my team and do some digging for you. Will be in touch, thanks!
> 
> Best,
> Berni


> From Karim/Intrivo:
> Subject: Re: [EXTERNAL] Re: Question regarding data issues sent to WA Dept. of Health (ReportStream Ticket # 6907)
>  
> Andrew,
> 
> VT reached out to us notifying us about the errors.
> 
> Best regards,
> Karim Lalani | Engineering Lead
> 📧 klalani@intrivo.com | www.intrivo.com
> 
From Andrew W./ RADx Mars:

**Comment by MauriceReeves-usds** [comment]
@BerniXiongA6 @brick-green @GilmoreA6 - this one confuses me because the `99ELR` value comes from the LIVD table, and it's the coding system that is used for many of the tests. 

If it's not accepted, what does VT want instead?

**Comment by brick-green** [comment]
@MauriceReeves-usds I just looked at the LIVD table and 99ELR is not in there.

@BerniXiongA6 I think we're going to need to do more investigation here.

**Comment by BerniXiongA6** [comment]
OK thanks @brick-green for the heads up...I won't reach out to VT yet. We can bring this into the sprint when you guys think you have enough info to work on it. Even if it's simply to just do research/investigate. cc: @brandonnava @MauriceReeves-usds

**Comment by MauriceReeves-usds** [comment]
That's weird. It used to be. Investigation time indeed.

**Comment by MauriceReeves-usds** [comment]
99ELR comes from the confluence doc about COVID reporting. Maybe the guidance has changed. 

https://confluence.hl7.org/plugins/servlet/mobile?contentId=86967947#content/view/86967947

@BerniXiongA6 @brick-green @GilmoreA6

**Comment by MauriceReeves-usds** [comment]
Non-mobile version of the link above; https://confluence.hl7.org/display/OO/Proposed+HHS+ELR+Submission+Guidance+using+HL7+v2+Messages

**Comment by BerniXiongA6** [comment]
BX sent email to VT ELR team 12/16:
> Hi Vermont ELR Team!
> 
> We have a question from Intrivo regarding recent data submissions that are not passing validation:
> When inputting the value of "99ELR" for OBX 17.3, they're getting a "Situational rule violated" error. If this isn't a correct value per your jurisdiction, the sender is wondering what the guidance should be.
> Per the RADx Mars team over at NIH/NBIB, we're told that "99ELR" is correct for OBX 17.3, according to the MARS spec. Our engineers dug further into this and found this guidance, which also mentions this (you can do a keyword search to locate the updated guidance on that web page): https://confluence.hl7.org/display/OO/Proposed+HHS+ELR+Submission+Guidance+using+HL7+v2+Messages
> 
> We're happy to help get this resolved. How would you like for us to proceed?
> 
> Thanks,
> Berni

**Comment by BerniXiongA6** [comment]
VT email reply today 12/19/2022:

> Hi Berni,
> 
>  
> 
> I’ve reached out to our HIE team for guidance on this, and essentially what has been relayed from them is that the OBX 17.3 is errored because there is no value entered at all. The 99ELR must be being placed in a different spot than the OBX 17.3. In other words, the 17.3 is required and currently messages are being sent with 17.3 empty and the 99ELR is being entered elsewhere. Please let me know if you have further questions, and I can reach back out to our HIE team for further assistance.
> 
>  
> 
> Thanks,
> 
>  
> 
> Andrew Gross, MPH | Health Data Administrator
> 
> Division of Health Statistics & Informatics
> 
> Vermont Department of Health
> 
> 108 Cherry St, Burlington, VT 05402

**Comment by brick-green** [comment]
Can VT provide the accession numbers for these messages? We don't have a way to identify which messages were sent in error.

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 to check if we can find a message ID or accession number in order to trouble-shoot this ticket. cc: @sliu1000

**Comment by BerniXiongA6** [comment]
BX sent email to VT DOH on 12/29/2022:

> AHS - VDH ELR Support <ahs.vdhelrsupport@vermont.gov>
> Report Stream (CDC);Brandon Canniff <brandoncanniff@navapbc.com>
> Hi Andrew, thanks for looking into this. I'll check with my team to see if we can investigate this further given what you've shared. We'll be in touch soon.
> 
> 
> Thanks,
> Berni
>

**Comment by BerniXiongA6** [comment]
Email reply from Andrew / VT on 12/30:



AHS - VDH ELR Support

Fri 12/30/2022 6:36 AMView more
Hi Berni,
 
The accession numbers for all of the failed messages coming from Intrivo are 123456. I’m unsure of the explanation for that, but that is what we are seeing on our end.
 
Thanks,
 
Andrew Gross, MPH | Health Data Administrator
Division of Health Statistics & Informatics
Vermont Department of Health
108 Cherry St, Burlington, VT 05402

**Comment by BerniXiongA6** [comment]
Flagging this so we can bring it into the Sprint Backlog at planning. cc: @brick-green @brandonnava

**Comment by brick-green** [comment]
Confirmed the problem. OBX-17.3, ORC-2.1, and OBR-2.1 were sent to RS by intrivo but were not included in the file sent to VT. Will investigate and identify

**Comment by sliu1000** [comment]
Hi Karim,

Hope you had a nice weekend.  We are reaching out on behalf of the State of Vermont.  They experienced a few validation errors on their side due to the following:
Incorrect values for OBX 17.2
Should only include values from column B (model) in the LIVD Table.
Causing OBX 17.3 to be blanked
ORC-2 and OBR-2 were not provided.
Please do not use default values for patient name
PID 5.1
PID5.2
ORC-3, OBR-3 (Filler Order Numbers)
If you'd like to discuss this further, please provide availability days and times.

Best regards,

Sharon

The ReportStream Support Team
Contact us at reportstream@cdc.gov
Support hours:  8:00 am through 9:00 pm Eastern time
Monday-Friday, excluding US public holidays

**Comment by brandonnava** [comment]
@brick-green @LaFreda1 @sliu1000 Just a heads up VT just followed up with us on email looking for an update. Looks like they want confirmation that Intrivo is only sending self reported data and if so to turn off their feed.

**Comment by LaFreda1** [comment]
@brandonnava will you forward it to me? Thanks

**Comment by LaFreda1** [comment]
@sliu1000 so it seems that this issue is on VT's side. Is that correct?

**Comment by sliu1000** [comment]
Yes, we are waiting for them to let us know what they want to update their filters to:

Update from VT Receiver:

Hi
I appreciate you getting back to me! I wanted to circle back to let you know I’ve been communicating with our epi team here to discuss what sort of filters we would want in place – from what we understand, some self-report applications for covid that come through ReportStream may also send results for different tests the same way, so we want to be careful that we aren’t ‘turning off’ streams of results for tests we’d still want to receive. I’ll plan to reach out again once we’ve had a chance to discuss the filtering a bit more.

Thanks for your assistance!
Andrew Gross, MPH | Health Data Administrator
Division of Health Statistics & Informatics
Vermont Department of Health

Hi Andrew,

My apologies in the delayed response.  As the receiver for VT, you can let us know what filters you want us to put in place and we can work on updating what you receive.  If you know exactly what results from Intrivo you no longer want to receive specifically we can filter that out.  However, if you'd like to set up time to review the current filters in place and please provide availability for next week and we can coordinate with our Engineering Team to map out what you'd like to receive.

Best regards,
 
The ReportStream Support Team
Contact us at reportstream@cdc.gov
Support hours:  8:00 am through 9:00 pm Eastern time
Monday-Friday, excluding US public holidays

**Comment by sliu1000** [comment]
linked to ticket #7922

**Comment by sliu1000** [comment]
@brick-green Can I close this one as well? I see you closed the referenced ticket #7922.
