### ISSUE TITLE
Upload new LIVD Table

### ISSUE THREAD

**Issue by cmo44** [CDCgov/prime-reportstream#7695]
## Problem statement

The LIVD team sent over a new LIVD table that needs to be uploaded into ReportStream.

## What you need to know

[https://app.zenhub.com/files/304423150/13369856-4828-4aca-944e-6a13b838ec2c/download]

## To do

 Run livd-table-update command with new table

**Comment by cmo44** [comment]
[https://app.zenhub.com/files/304423150/b4929c6e-b69d-4414-9c21-a5673e677d94/download]

**Comment by brick-green** [comment]
This is for monkey pox. No work to be done.
