### ISSUE TITLE
Facility Look-up feature: Usability testing w STLTs

### ISSUE THREAD

**Issue by fmccaf1** [CDCgov/prime-reportstream#7701]
### Information
Following the design of the facility look-up feature [(7437)](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/7437) based on internal (O&O) feedback, the next step is to conduct external research with STLTs to understand whether and how this tool might meet their needs.

**Comment by chris-kuryak** [comment]
Closing per @lizzieamanning
