### ISSUE TITLE
Develop research plan to share with Megan Light/CDC

### ISSUE THREAD

**Issue by fmccaf1** [CDCgov/prime-reportstream#7702]
### Information
Using Patricia's pipeline research plan as a guide or template, generate a research plan for usability testing the facility look-up designs with STLT users.

### Acceptance criteria
- [ ] Research plan is generated and saved in shared location in Sharepoint
- [ ] Plan includes STLTs we'll reach out to and why we chose them
- [ ] Plan is shared with Megan Light/CDC for feedback and potentially help getting in touch with STLTs

**Comment by LaFreda1** [comment]
@jakefishbein-navapbc will you get with Lizzie to see where she left off with this?
