### ISSUE TITLE
Synthesize API Programmer's Guide research findings into actionable items

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#7703]
## Info
This is the last step to complete research around migrating the API Programmer's Guide from a PDF to web-based content. After this, designing and building the API guide into the website should be able to proceed.

## Acceptance criteria
- [x] List of actionable items for the design and build phase of putting the API Programmer's Guide onto the website

**Comment by audreykwr** [comment]
@jillian-hammer Relevant files:

1. [Edit copy with full suggestions/comment threads from working sessions](https://docs.google.com/document/d/1S4SlRp5nznuymnCr1nOwhQYDKYt2OqTX/edit#)
2. [Clean copy with edits applied and only design notes/misc in comments](https://docs.google.com/document/d/1S4SlRp5nznuymnCr1nOwhQYDKYt2OqTX/edit#)
3. [Mural working space](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1672412662691/888f40d9e714837654e616612dfc9761bf191576?sender=uc55a7af3b66977fba12f5528)

@chris-kuryak closing this
