### ISSUE TITLE
Request for Okta access for new developers

### ISSUE THREAD

**Issue by jimmyfagan** [CDCgov/prime-reportstream#7705]
**Description**
In preparation for getting into the on-call rotation, it seems likely that the Pipeline engineering team will all need Okta access.

**Specific Requested resources**
Access for Okta (whichever staging or production level is necessary for on-call duty) granted to Jimmy Fagan (jimmyfagan@navapbc.com), Victor Chaparro (victorchaparro@navapbc.com), and Jessica Willis (jessicawillis@navapbc.com).

**Existing Resources?**
Not aware of any existing resources that we will need to delete or modify for this

**Additional Context**
Not sure exactly which roles need Okta access or not, but it seems like most folks on other teams do have access; if Okta access is generally given to non-engineers as well, it would be nice to verify that Avniel Dravid has access too as part of this.

**Comment by jeremy-page** [comment]
This is now done by Sharons team!
