### ISSUE TITLE
[SPIKE] Experiment with using libraries to log data to AppInsights from inside our Azure function code

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#7706]
Experiment with using libraries to log data to AppInsights from inside our Azure function code.

Part of Epic [7518](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/7518)

@kevinhaube suggests looking at this:  https://search.maven.org/artifact/com.microsoft.azure/applicationinsights-core/2.6.0/jar

@JGreenFearless has use cases documented.

These data are needed per all API calls:

HTTP method used
•	Transaction size (available in action table for 'receive', but buried in action_parameters)
•	Who executed the transaction (available in action table for 'download' action.   Could be added for settings changes)
•	Success / failure of a transaction (available as a 'Request' log in AppInsights; available for 'receive' actions in action table)
•	When the transaction took place (available as a 'Request' log in AppInsights; available for 'receive' actions in action table)
•	Which API was hit during the transaction (available as a 'Request' log in AppInsights; available for 'receive' actions in action table)
•	Number of API invocations (available with a group query on the 'Request' log in AppInsights, and for 'receive' actions in the action table)
•	Transaction length of time (available as a 'Request' log in AppInsights; available for 'receive' actions in action table)

As you can see from the comments in parens, we already do a lot of logging:  directly into the AppInsights text logs, and into the ACTION table in the database, which already has a lot of the items above.

Only the first two are not easily retrievable via AppInsights right now.

### Acceptance Criteria

- Go/no-go:   We know if the azure appinsights library is going to be "good enough" to track the above parametrics.
- We have a written design proposal if needed.
- If "go", we have stories generated to followup.
- If "no go" we have alternative approach.

**Comment by jimduff-usds** [comment]
The current `requests` table has 
- http status
- timestamp
- which API was hit
- number of invocations (that is, we can sum them in KQL)

It does not appear to track
- size of the payload
- who executed the transaction
- what organization they are with.

**Comment by jimduff-usds** [comment]
Links:

https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent

https://learn.microsoft.com/en-us/troubleshoot/azure/azure-monitor/app-insights/investigate-missing-telemetry#curl-command-send-availability-test-result

**Comment by jimduff-usds** [comment]
In gradle:  

dependencies {
   implementation("com.microsoft.azure:applicationinsights-core:3.4.7")

**Comment by avnieldravid** [comment]
@stephenkao do you still need this work to be completed by the platform team?

**Comment by stephenkao** [comment]
@avnieldravid Nope, this is going to be handled by the WebX team now [in this ticket](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/8291).  Feel free to close!

**Comment by arnejduranovic** [comment]
Closing this as done. RS supports sending custom logs, events, and metrics to azure app insights now.
