### ISSUE TITLE
Breadcrumbs on Submissions Detail don't link back to previous URL

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7712]
## Describe the bug
When using the message ID search feature for Admins, the Report ID links to `/submissions/{reportId}` to display submission details. The breadcrumb to go back, however, links to `/submissions`, the list page for submissions from an organization.

## Impact
Breaks the UI if Admins navigate using the breadcrumb.
Can be bypassed using browser "Back" button.

## To Reproduce
_Requires #7711 to merge_

1. Login at staging.reportstream.cdc.gov
2. Under the Admin dropdown in navigation, click Feature Flags
3. Add `message-tracker` to your active Feature Flags
4. Under the Admin dropdown in navigation, click Message ID Tracker
5. Search `014228`
6. The message will appear in the results, click on the Report ID (this is the part dependent on #7711's fix)
7. The url change to `/submissions/{reportId}`, when results load, observe the breadcrumb `Submissions` (hard-coded)
8. Click it
9. Submissions UI will break because of a **known issue** where `PrimeAdmins` is not a valid organization, and thus have no submissions

## known workaround

10. Replicate 4-7 again
11. Click the browser "back" button.
12. UI is okay and back to the message ID search

## Expected behavior
In step 7, we should observe `Message ID Search` if coming from that page, and `Submission History` if coming from that page.
In step 8, we should be taken to the proper previous URL

## Acceptance Criteria

- [ ] When clicking on the breadcrumb, it takes you to the expected page, not back to /submissions
- [ ] Breadcrumb link name matches correct previous page

**Comment by chris-kuryak** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/7712?planning-poker) with Zenhub @kevinhaube @penny-lischer @jpandersen87

**Comment by stephenkao** [comment]
Hey, @chris-kuryak and @jillian-hammer!  Joseph, Kevin, and I have [a discussion on GitHub](https://github.com/CDCgov/prime-reportstream/pull/7827#discussion_r1061783319) that could use your wisdom!

Essentially, the flow here is:
- Use the Message Tracker to find a message
- Click on the report id (not the message id)
- Click on the 'Submissions' breadcrumb --> goes back to Submissions index rather than Message Tracker

The question is: should we just change this breadcrumb to a back button?

**Comment by chris-kuryak** [comment]
Here is my clarity copied from Slack:

> 
Accurate breadcrumb:
- adds new route to existing page
- could negatively impact SEO in future and complicate page routings
- allows user to use breadcrumb to go back to message tracker

Inaccurate breadcrumb:
- no new route added
- message tracker would not be in the breadcrumb and would require user to hit back button to return to message tracker

**Comment by chris-kuryak** [comment]
Since the only negative implication on the Inaccurate breadcrumb path is a usability impact, I want to hear from @jillian-hammer: Is it a big issue for the user to have to use the browser's back button or have a "back button" on the page instead of breadcrumbs when using the messageID tracker?

**Comment by jillian-hammer** [comment]
I vote to remove the breadcrumbs in this use case and replace with a back button.

**Comment by jillian-hammer** [comment]
[Copy of a [Slack message](https://nava.slack.com/archives/C02HJ43AE8Z/p1673044643302619?thread_ts=1673029962.531689&cid=C02HJ43AE8Z) sent in the discussion thread]

Atter a discussion, joseph and I landed on trying some solutions where we include BOTH the breadcrumbs and back button. TBH including both is not a common ux convention, but it felt important to address the feedback. 

here are two sketches i'd love y'all's thoughts on.

**- Option 1: Back button in-line with breadcrumbs.** if this is implemented, it should appear universally across the site. however this feels like a risk to universally implement just bc of this single message tracker use case.

![BackButton_Inline_Small](https://user-images.githubusercontent.com/119958649/211111755-2d03b837-b745-47ba-8353-ae5e59d60051.png)


**- Option 2: Return-to-previous-page callout:** this solution would only conditionally appear in instances where you got to the page from an alternate route. pros: allows us to tack this callout when necessary without having to touch the breadcrumbs. con: complexity? ux confusion? 

![BackButton_ConditionalOverlay](https://user-images.githubusercontent.com/119958649/211111760-43ee805c-e785-4382-bb80-42650faa0a89.png)

**Comment by chris-kuryak** [comment]
Option 2 was the decision.
Adding here for traceability.

**Comment by kevinhaube** [comment]
Re: Joseph's idea

> the program knowing you're set to prime-admin so on pages we know that's not gonna jive we show you a page immediately saying you need to set an organization rather than hitting the API and then relying on the response to say it

Created #7890 to implement this for Admins while we work with O&O to refine the Admin settings mocking experience. 
cc: @chris-kuryak
