### ISSUE TITLE
WA submission failures invalid characters in ORC and OBR

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#7721]
Messages from AFC Urgent Care are failing out due to strings of '############' in ORC and OBR segments.

Example:
```
ORC|RE|1123141^AFC Urgent Care^06D2240326^CLIA|1123141^AFC Urgent Care^06D2240326^CLIA|||||||||###############################################################################################################################################################################################################################################################^Franklin^Yosef^^^^^^^^^^U||3033436000^WPN^PH^^1^303^3436000|20221216160000||||||AFC Urgent Care Aurora Havana^L|10552 E Arizona PL^^Aurora^CO^80012^USA|3033436000^WPN^PH^^1^303^3436000|10552 E Arizona PL^^Aurora^CO^80012^USA
OBR|1|1123141^AFC Urgent Care^06D2240326^CLIA|1123141^AFC Urgent Care^06D2240326^CLIA|95942-9^Influenza virus A and B and SARS-CoV+SARS-CoV-2 (COVID-19) Ag panel - Upper respiratory specimen by Rapid immunoassay^LN^^^^2.69|||20221216160000|20221216160000||||||||###############################################################################################################################################################################################################################################################^Franklin^Yosef^^^^^^^^^^U|3033436000^WPN^PH^^1^303^3436000|||||20221216160000|||F
```

Message control IDs: 
```
1098959+83+20221217
1123141+75+20221219
1102748+74+20221219
1102672+32+20221219
1107644+310+20221219
1102747+73+20221219
```

Contact: caroline.thomas@doh.wa.gov

**Comment by TaneaY** [comment]
Caroline provided an update - it’s the ordering provider ID that is missing and being replaced with the string of #, causing the messages to fail in our system.

We also received a few more messages with the issue, message IDs listed below.

1108692+9+20221220

1111201+12+20221220

1111085+161+20221220

1108870+139+20221220

1109650+164+20221220

Helpdesk has reached out to AFC to see if they have entered a NPI or local code as the field is a requirement for the CSV uploader.

**Comment by brandonnava** [comment]
@TaneaY @sliu1000 Any update on this?

**Comment by brandonnava** [comment]
@TaneaY checking in on this ahead of today's WA meeting

**Comment by TaneaY** [comment]
AFC responded:We’ve corrected the Ordering provider NPI format & have uploaded the file already on 12/21/2022! Also, it is successfully uploaded in that website!

For your reference, it was automatically decoding through invalid format (####) when we cut & paste the NPI previously, we’ve now changed the format and uploaded again already on 12/21/2022.![AFC resubmissions.png](https://images.zenhubusercontent.com/628286bc0129e14bd536e6f9/daa8ed86-4b56-4301-8e4a-d1fd2af6ba93)

Follow-up sent to Caroline to confirm resubmissions received.

**Comment by sliu1000** [comment]
@TaneaY I'm looking at this data and seeing no patients are for WA state.

**Comment by brandonnava** [comment]
@TaneaY @sliu1000 Is resubmission confirmed? Can I close?

**Comment by TaneaY** [comment]
AFC Urgent Care confirmed the correction to the NPI and resubmitted, however when resubmitted the sender stated that there were no WA state patients in that file. Support desk reviewing initial request to try to pinpoint the specific patients to assist the sender with correct resubmission.

Thank you,


Tanea

The SimpleReport Support Team

Contact us at ***@***.***

Support hours:  8:00 am through 9:00 pm Eastern time

Monday-Friday, excluding US public holidays

________________________________

**Comment by sliu1000** [comment]
Hi Caroline,

Here are the corresponding Message ID's for AFC's resubmissions.

Report ID: c8ef549a-7087-4acb-8b1b-37460b0c3dab
Message ID: 1109650+164+20230207
Report ID: 9525276d-7cb6-4a21-87a8-9bca3a81267a
Message ID: 1108870+139+20230207
Message ID:  1108692+9+20230207
Report ID: e7ee7408-1daf-4521-ab2f-8b43c17d5146 Message ID: 1111085+161+20230207
Message ID: 1111201+12+20230207

Please let us know if you need any additional assistance.

Thank you,

Tanea

**Comment by TaneaY** [comment]
Hi Caroline,

We have received the following message ID resubmissions from AFC.

Hope this clears up all of them.

![image.png](https://images.zenhubusercontent.com/628286bc0129e14bd536e6f9/03e43786-2d18-448f-81e8-be347978e97b)

Thank you,
Tanea 

Good morning Tanea,

I can confirm that we received these resubmissions and that takes care of all the requested resubmissions on our list. We can close this ticket out!

Thank you,
Caroline
