### ISSUE TITLE
Okta access for Nava team

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#7733]
Description
In preparation for getting into the on-call rotation, it seems likely that the Pipeline engineering team will all need Okta access.

Specific Requested resources
Access for Okta (whichever staging or production level is necessary for on-call duty) granted to Jimmy Fagan (jimmyfagan@navapbc.com), Victor Chaparro (victorchaparro@navapbc.com), and Jessica Willis (jessicawillis@navapbc.com).

**Comment by sliu1000** [comment]
Accounts created and assigned to DHPrimeAdmins
