### ISSUE TITLE
Revise flu pilot research plan 

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#7739]
**User Story**
As an RS stakeholder or STLT, I want to understand the goals of the flu pilot research 

**Background & Context**
We shared a draft of the research plan with CDC stakeholders and they responded with comments.

**Acceptance Criteria**

- [x] Address CDC comments in the flu pilot research plan  

- [x] Add in more detail about our research process where possible

- [x] Align with Patricia, Victoria, Kevin 

- [x] Share back with CDC via email 

- [x] Prepare to discuss updates in meeting on 1/3/23 or in another separate, smaller meeting

**Comment by BerniXiongA6** [comment]
Hi @lizzieamanning should we bring this into backlog refinement next week (I can schedule one in place of a standup). Lmk if you have questions about pre-refining the ticket before then. cc: @brandonnava

**Comment by lizzieamanning** [comment]
This work is completed and can be reviewed in this [document](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BA6C5772B-7E9E-41D8-8B25-C1757D13C463%7D&file=%5BWIP%5D%20PRIME%20SimpleReport%20Flu%20FHIR%20ReportStream%20Universal%20Pipeline_ReportStream%20Research%20PlanV3to%20share%20as%20of%201.4.23.docx&action=default&mobileredirect=true)

In the future, flu pilot work will be tracked on the pipeline board
