### ISSUE TITLE
Research SendGrid uses and capabilities 

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#7742]
**User Story**
As a customer support team member, I want a tool to support in manually combing through and cataloging emails into our onboarding funnel categories 

**Background & Context**
Currently, customer support is manually tracking the stages of onboarding. 
We recently re-discovered access to a tool called SendGrid, that we may be able to leverage for this purpose.

**Acceptance Criteria**

- [ ] Review and outline SendGrid capabilities 

- [ ] Review and outline our current use of SendGrid 

- [ ] Share with Sharon & Brandon to discuss possible next steps

**Comment by BerniXiongA6** [comment]
Hi @lizzieamanning should we bring this into backlog refinement next week (I can schedule one in place of a standup). Lmk if you have questions about pre-refining the ticket before then. cc: @brandonnava

**Comment by lizzieamanning** [comment]
@jakefishbein-navapbc

**Comment by LaFreda1** [comment]
@lizzieamanning any updates on this ticket? Is it still a priority? Should we close it?

**Comment by lizzieamanning** [comment]
@LaFreda1 can we put this in the backlog for @jakefishbein-navapbc  (or our incoming designer) to pick up in a future sprint? Since its a tool we have access to and it could potentially reduce workload, I still think its worth prioritizing in the near future (maybe sprint 66)

**Comment by LaFreda1** [comment]
@lizzieamanning are you ok with me closing this ticket? Would you still like for Jake to take this on?

**Comment by lizzieamanning** [comment]
Apologies for the delay- this is fine to close out for now
