### ISSUE TITLE
Research viability of using new WA values w/o further enhancements

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#7743]

**Comment by BerniXiongA6** [comment]
@GilmoreA6 @brick-green please add details and AC thanks! cc; @brandonnava

**Comment by GilmoreA6** [comment]
[https://app.zenhub.com/files/304423150/ef6c13c8-aed0-46a5-b792-b83ffa4837f8/download](https://app.zenhub.com/files/304423150/ef6c13c8-aed0-46a5-b792-b83ffa4837f8/download)

**Comment by GilmoreA6** [comment]
Brick did some work to compare the race values between the WA values and the HL7 values. A few major issues were discovered in that there are several values that appear on the WA set that do not have corresponding values in the HL7 set and there are also multiple values in the WA set that map to a single value in the HL7 set.
