### ISSUE TITLE
[SPIKE] Look into CJS alternatives of rehype-raw/rehype-slug/github-slugger

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#7753]
## Problem statement

[github-slugger](https://github.com/Flet/github-slugger/blob/master/CHANGELOG.md#200-2022-10-27) moved to ESM in 2.0.0, and we have no plans on moving our project to ESM.  We use these sluggifying dependencies in our [MarkdownRenderer](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/components/Content/MarkdownRenderer.tsx) component, so we should look into CJS-compatible equivalents going forward.

See [this pull request](https://github.com/CDCgov/prime-reportstream/pull/7648) for more context.

## Acceptance criteria

- [ ] Find a dependency (or create our own) that can auto-generate anchor ids out of headers

**Comment by chris-kuryak** [comment]
We believe this is no longer needed, but will be re-opened if there is a security issue. @stephenkao
