### ISSUE TITLE
MD - Timezone Discrepancy

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#7755]
Email address: kristy.lunquest@maryland.gov

User requests:

Hello,

Our HIE and contact tracing unit identified some examples of future specimen collection dates coming from Simple Report. It appears to be a timestamp/timezone issue since the timestamps seem to be 5 hours ahead of our timezone (EST). Not all results are affected since it may have to do with when the test was run/result was entered. I've attached some examples. Can you look into this?

![image.png](https://images.zenhubusercontent.com/62828b77597e3bdcbc3834fd/7bff749a-883c-4ed0-a5c6-1651c632d629)

Thanks,

Kristy Lunquest, ScM
Epidemiologist, Division of Infectious Disease Surveillance
Maryland Department of Health 
201 W. Preston Street, 3rd Floor, Baltimore, MD 21201
Phone: 410-767-6675  Fax:  410-225-7615
Email: kristy.lunquest@maryland.gov

**Comment by brick-green** [comment]
Need to change MD reciever settings to set timezone to EASTERN and LOCAL

**Comment by rnz6** [comment]
Update 1/5: Kristy confirmed to changed to Eastern and Local

**Comment by shy2cdc** [comment]
Email from Kristy:

Hello,

Has this been changed yet?

Thank you!
Kristy

**Comment by adegolier** [comment]
@rnz6 @shy2cdc Updated today! Can we confirm that it's working the way they're expecting?

**Comment by rnz6** [comment]
@adegolier Thank you for the update! I just followed up with Kristy for confirmation.

**Comment by rnz6** [comment]
User is all set and will let us know if they find any new instances of this issue
