### ISSUE TITLE
Azure cannot parse nested JSON object `activeMembership`

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7767]
**Describe the bug**
In App Insights, we transmit our `activeMembership` object containing non-identifying user information, like their org name and role, to use as aggregation properties in our Insights queries. The way we send it now looks like:

```json
{
    ...
    "activeMembership": {
         "parsedName": "my-org",
         "memberType": "receiver"
    }
}
```

**When attempting to deconstruct the nested `activeMembership` object in Azure using KQL, it, for some reason, cannot be parsed as JSON.**

**Impact**
Medium-High: we cannot efficiently parse insights with membership metadata, and must rely on "quick and dirty" methods like extensive `where` cases that do string parsing on the object.

**To Reproduce**
1. See Screenshots below

**Expected behavior**
When parsing JSON with KQL, it should turn each key/value pair into a column/scalar. 
See [this video](https://www.youtube.com/watch?v=HeZryWcBW2k) for examples of parsing JSON.

**Screenshots**
![Screen Shot 2022-12-27 at 10.40.08 AM.png](https://images.zenhubusercontent.com/611a907ec3e013d0e33e58a7/4ec08ee8-4428-4880-aabb-d48020817788)

![Screen Shot 2022-12-27 at 10.28.31 AM.png](https://images.zenhubusercontent.com/611a907ec3e013d0e33e58a7/678e380b-dd3b-4bcc-836c-7a3d4cdff117)

**Comment by kevinhaube** [comment]
Assigning myself in anticipation! :D

**Comment by chris-kuryak** [comment]
Awaiting meeting result from Kevin, Penny, and Stephen for refinement and prioritization.

**Comment by chris-kuryak** [comment]
Moved to product backlog for refinement with rest of team per meeting outcome with Kevin, Penny, and Stephen.

> We identified there’s a decision to be made by engineers on a best path forward since it only affects how we write queries, but doesn’t block the outcome of querying.

This does not block our current MVP.

**Comment by jpandersen87** [comment]
Do we have an example of an app insights log that KQL is failing to parse on?

**Comment by chris-kuryak** [comment]
@jpandersen87  I think you may need to tag others in order for them to see your question:

> Do we have an example of an app insights log that KQL is failing to parse on?

 I am tagging them here for awareness: @kevinhaube @penny-lischer @stephenkao

**Comment by kevinhaube** [comment]
@jpandersen87 
Yes; let me get a sample query for you tomorrow! 🙂

**Comment by chris-kuryak** [comment]
This is no longer needed, and has been overcome per engineering team. (Stephen)
