### ISSUE TITLE
Public Validation Page design finalization

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#7771]
## Problem statement
Need a location, page layout, and instructions for the new public validation feature on the RS website.

## What you need to know
Much work has been done to design the validation tool, now we need to determine where it goes and what it will look like to an unauthenticated user (public).

See feedback on the validation tool [here](https://docs.google.com/document/d/1gAw5Uk3csf0JoByxHfQ9spsq1_eooV8ANsWWLKpV6Xw/edit#)

## Acceptance criteria
- [x] Determine new page location 
- [x] Content final pass with Audrey 
- [x] On page, include instructions for proper usage of the feature and next steps after success
- [x] Place relevant design details and instructions into #7772 for engineering work to be completed

## To Do
- [x] Work with O+O onboarding team to determine verbiage for on-page instructions as it should likely match what is used in their future emails to prospective senders

**Comment by jillian-hammer** [comment]
Design work is complete! Here is the [Figma Prototype](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=2183%3A21892&scaling=min-zoom&page-id=2173%3A22160&starting-point-node-id=2183%3A21892) of the final designs.

See the epic "Make Validation page available to unauthenticated users #5517" and related issues for the latest updates.

**Comment by lizzieamanning** [comment]
Great summary thank you! One note @jillian-hammer  the modal looks like it still has the primary and secondary buttons mixed up. Can you check that? Let me know if you need any support talking through that
