### ISSUE TITLE
Move validation feature page to be public facing

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#7772]
## Problem statement
The validation feature is only available to logged-in users of the RS website.  To make it public, we have to remove the authentication dependency and open up the page to the public Organization.

## What you need to know
- Design team is working on public page location and necessary page content changes.
- Pages are gated through an `AuthElement`. You'll find the one for the Validator in `Validate.tsx`. We should be okay to remove this and rely on the `Validate` component

## Acceptance criteria
- [ ] Move page to public location on website determined by design team
- [ ] Engagement reviews and approves making the Validation feature live
- [ ] Ensure page can be used by logged-out user
- [ ] Ensure page can be used by logged-in user
- [ ] Visual QA with Design and Content team before merging

**Comment by kevinhaube** [comment]
Added in two peaces of context to "What you need to know":
>- Pages are gated through an `AuthElement`. You'll find the one for the Validator in `Validate.tsx`. We should be okay to remove this and rely on the `Validate` component
>- `itemsMenu` in `ReportStreamHeader.tsx` is initialized with all public pages; this is where we'll add `<Validate />`

**Comment by chris-kuryak** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/7772?planning-poker) with Zenhub @etanb @jpandersen87 @kevinhaube @penny-lischer @stephenkao

**Comment by chris-kuryak** [comment]
@etanb  Looks like everyone else is at 2-3 points on this one. How would you feel about making it a 3-pointer? Or want to describe here why you think it should be 5-pointer?

**Comment by etanb** [comment]
3 is fine for me! Was just being overly cautious based on our conversation yesterday.

**Comment by stephenkao** [comment]
The design portion of this is being handled in [#8531](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/8531) so I'm going to update the description and pointing accordingly.

**Comment by chris-kuryak** [comment]
Awaiting feedback from Engagement team before moving to public.

**Comment by chris-kuryak** [comment]
QA Content ongoing.
Awaiting feedback from Engagement and approval to deploy.

**Comment by kevinhaube** [comment]
From afar, it's great to see this getting done! Miss you all
