### ISSUE TITLE
Update validator page to allow for selecting schema or Sender settings

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#7773]
## Problem statement
In this MVP, we have three possible master schemas to validate against with the public validation tool.  Since the users may or not be logged in, we have no way of knowing which schema they'll want to validate their uploads against.  Additionally, Organizations have their own Sender settings against which they may want to validate.  Consequently, we'll need to provide a select box to choose among all available options on the validation page while they're uploading their file.

## What you need to know
We currently have three "master schemas" that we can validate against:
- [HL7](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/metadata/schemas/HL7/hl7-ingest-covid-19-training.schema)
- [CSV](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/metadata/schemas/upload-covid-19.schema)
- [CSV OTC](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/metadata/schemas/csv-otc-covid-19.schema)

## Acceptance criteria
**For all users**
- [x] There's a [select box](https://designsystem.digital.gov/components/select) accompanying the validator tool
- [x] The schema choice can be pre-selected via unique query parameter in the URL
  - [x] If the schema choice is invalid or not applicable for the currently logged-in user, there should be no initial selection
- [x] The validation button should be disabled until the user selects an option and chooses a file for upload

**For an unauthenticated user**
- [x] The dropdown component should be rendered with the three default options

**For an authenticated user**
- [x] The dropdown component should be rendered with all available Sender settings for the user _in addition to_ the three default options
- [x] If the user has a designated schema, the dropdown should default to that

## Additional information
- We may want to hide the tooltip behind a `public-validator` feature flag if it'd be confusing to admins as we're preparing to make the validator page public.
- [FileHandler](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/components/FileHandlers/FileHandler.tsx) is also rendered in [UploadToPipeline](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/pages/UploadToPipeline.tsx), but that's locked behind the now-unused `user-upload` feature flag.  We should be okay to update that with the select dropdown for the time being, and we can revisit if we need `user-upload` to be turned on for whatever reason.

**Comment by chris-kuryak** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/7773?planning-poker) with Zenhub @etanb @jpandersen87 @kevinhaube @penny-lischer @stephenkao

**Comment by stephenkao** [comment]
Updating the pointing on this due to the work needed for rewriting/reworking a good chunk of logic and tests.
