### ISSUE TITLE
Use public organization for unauthenticated users

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#7775]
## Problem statement
In order to use the Validation tool **with the public schemas** as a user with **and** without login credentials, the ReportStream web application needs a "default" (nay, `public`) organization setting that it may retrieve. This setting will include the 3 standard schemas for ReportStream: CSV, CSV-OTC, and HL7. It should be retrieved and stored as `MembershipSettings` for any unauthenticated user. 

>To retrieve these _without_ authentication, we will need work from the `Platform` team. #7774

## What you need to know

We currently set `activeMembership` only for authenticated users. This will require us to no longer default to `undefined` as we do now. See [UseOktaMemberships](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/hooks/UseOktaMemberships.ts).

Schema designation is handled by a `Sender` setting within the `Organization`. (often seen in code as: `my-org.sender`) One sender setting maps to one schema.

We have the idea of "many memberships" already baked into our SessionContext, so we can leverage this to make the `public` settings available to authenticated users.

## Acceptance criteria

- [ ] Public settings include the 3 standard schemas
- [ ] Unauthenticated users have access to the `public` schemas from the validator
- [ ] Authenticated users have access to the `public` schemas from the validator

## To do

- [ ] _Use this section to outline your approach!_

**Comment by kevinhaube** [comment]
Instead of using a public org, we're just hard-coding schema names in #7773 and then Platform's work will allow us to pass those hard-coded public schema names instead of an `org.setting` value, and still validate properly.

**Comment by chris-kuryak** [comment]
Per engineering decision, closing as #7773 satisfies the requirement of the MVP.
