### ISSUE TITLE
Create Events and Queries to track success of Public Validation MVP

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#7776]
## Problem statement
In order to track the success of the Public Validation MVP, we want to track how the feature is used. In order to achieve this, we need to create some queries and events in the Azure dashboard that track user interactions around the Public Validation tool.

## What you need to know

We already track network calls, their `url`, and their `responseCode` with our telemetry data

We will need to manually track the `org.sender` and/or schema name header values to measure what schemas are being validated against.

**Workbooks are an unexplored part of Azure for us so point accordingly!**

## Acceptance criteria
Front-end:
- [x] On validation completion (success or failure), we track an AI custom event that includes the following properties:
  - `warningCount` (from validate response)
  - `errorCount` (from validate response)
  - fileType
  - selected schema
  - sender (if any)

Azure App Insights:
- [x] Workbook/report/table showing the responses from the validation tool during each user session, with time stamp, and Pass/Fail column (based off of errors captured)
- [x] Workbook/report/table showing what schema is validated against in each user session (likely part of the same Workbook as above)

**Comment by kevinhaube** [comment]
@chris-kuryak @stephenkao This feels like maybe a 2-3 ticket effort. If we wanted to do 2, I'd recommend:
1. Workbooks/reports AC
2. Custom metric and Stacked bar chart AC

**Comment by chris-kuryak** [comment]
@kevinhaube I am definitely okay with that.

**Comment by chris-kuryak** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/7776?planning-poker) with Zenhub @etanb @jpandersen87 @kevinhaube @penny-lischer @stephenkao

**Comment by penny-lischer** [comment]
@chris-kuryak is it beneficial to capture the filetype as well? i.e. .csv or hl7?

**Comment by penny-lischer** [comment]
@chris-kuryak minor effort

**Comment by penny-lischer** [comment]
let usg_events = dynamic(["File Validator"]);
let mainTable = union customEvents
    | where timestamp > ago(30d)
    | where isempty(operation_SyntheticSource)
    | extend name =replace("\n", "", name)
    | extend name =replace("\r", "", name)
    | where '*' in (usg_events) or name in (usg_events)
    | extend fileValidatorProps = tostring(customDimensions["fileValidator"]);
let queryTable = mainTable
    | where 'user_Id' != 'user_AuthenticatedId' or ('user_Id' == 'user_AuthenticatedId' and isnotempty(user_Id))
    | summarize ['Count'] = count() by bin(timestamp, 1d), session_Id, fileValidatorProps
    | extend dimension = todynamic(fileValidatorProps)
    | evaluate bag_unpack(dimension)
    | extend ['Pass/Fail'] = iif(errorCount==0, "Pass", "Fail")
    | project
    ["Date/Time"] = timestamp,
    ["Session Id"] = session_Id,
    ['Pass/Fail'],
    ["Warning Count"] = warningCount,
    ["Error Count"] = errorCount,
    ["Schema"] = schema,
    ["File Type"] = fileType,
    ["Sender"] = sender,
    ["Count"]; 
queryTable

**Comment by penny-lischer** [comment]
![Screenshot 2023-01-26 at 5.41.02 PM.png](https://images.zenhubusercontent.com/62697ac1be6e84867ab47e74/13570df2-0f13-4bc5-9370-fce376872cc4)

**Comment by stephenkao** [comment]
@chris-kuryak @penny-lischer The same component is being used for pure validation and for uploading to send from the website.  The functionality of the latter only seems available if the `user-upload` feature is enabled, which I don't think anyone is actually using (but I could be wrong).  So I think we can do one of three things here:
- Only track the event when validating, not sending
- Track the event when validating and sending
- Use separate events for validating versus sending

What are your thoughts?

**Comment by chris-kuryak** [comment]
@stephenkao @penny-lischer 
The Upload to Send feature I believe is defunct for RS and I think is covered by SimpleReport now. However, will have to confirm that with O+O.

For the purposes of this event tracking, let's **only track the event when validating, not sending**.

**Comment by penny-lischer** [comment]
![Screenshot 2023-01-27 at 2.51.16 PM.png](https://images.zenhubusercontent.com/62697ac1be6e84867ab47e74/80316be6-18a4-4bdc-8df1-cd6526d76733)

**Comment by chris-kuryak** [comment]
@penny-lischer Per our review, this meets the acceptance criteria. Looks great!
