### ISSUE TITLE
Epic - Updating Programmer's Guide Version

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#7783]
## Problem statement

As there are changes to the LIVD table, reporting requirements, and other API user-related guidance, ReportStream API programmer's guide will need to be updated with new content, version number and date. 

## What you need to know

- The public-facing API Programmer's Guide currently lives on the Resources page: https://reportstream.cdc.gov/resources/programmers-guide

- The archived versions of the guide currently live [in SharePoint](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/3.%20Instructional%20Design%20Projects/ReportStream%20API%20Programmer%20Guide?csf=1&web=1&e=cIr3is)

- The documented process for updating programmer's guide lives [in SharePoint](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Onboarding%20%26%20Ops/Scrum/Processes%20Documented/Updating%20API%20Programmer%E2%80%99s%20Guide.docx?d=w0e55f55dbf5c4d91a4ba53e2bdebfa81&csf=1&web=1&e=xori9r)

## To do

- [ ] O&O delivery/product/eng lead create an individual ticket when a new version needs to be created
- [ ] O&O person who originates the individual ticket must make sure to add it to this Epic.

**Comment by sliu1000** [comment]
Duplicate to the Experience ticket
