### ISSUE TITLE
 Rhode Island is still seeing UNK^Unknown Names

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#7784]
Good Afternoon Jason,

Below is a list with Dates and MSH-10 values as well as Accession #'s that had Unknown Names still being sent across recently. Let me know if you need anything else from our end and if you hear back from Ott in regards to this.

12/28
MSH-10 = 0F23C90E-312B-4F06-A153-533693BD2420
Accession# = 0F23C90E-312B-4F06-A153-533693BD2420
12/28
MSH-10 = 39DC3298-E71A-30D4-AE38-D5B8CD3B0AB8
Accession# = 39DC3298-E71A-30D4-AE38-D5B8CD3B0AB8
12/28
MSH-10 = B6E07280-A372-48BF-A46A-57C2AB257915
Accession# = B6E07280-A372-48BF-A46A-57C2AB257915
12/28
MSH-10 = 7F1E267B-DBEF-3536-AF57-7B02D532C481
Accession# = 7F1E267B-DBEF-3536-AF57-7B02D532C481
12/28
MSH-10 = E450AC57-A6BA-3343-BEDC-3AAF62E176FF
Accession# = E450AC57-A6BA-3343-BEDC-3AAF62E176FF
12/28
MSH-10 = 7E967A8E-9425-4F3C-A2B7-6241CF594A25
Accession# = 7E967A8E-9425-4F3C-A2B7-6241CF594A25
12/27
MSH-10 = 87C6E6E4-61E1-4A34-A848-FF49AE28AB88
Accession# = 87C6E6E4-61E1-4A34-A848-FF49AE28AB88
12/21
MSH-10 = 771F9FFC-846A-4EBF-A363-CA259F305730
Accession# = 771F9FFC-846A-4EBF-A363-CA259F305730
12/20
MSH-10 = D48FF270-8B3F-4399-90F5-E6B1C5856E74
Accession# = D48FF270-8B3F-4399-90F5-E6B1C5856E74
12/20
MSH-10 = 9BA3C411-3F27-3646-80AE-0B14BE67C96C
Accession# = 9BA3C411-3F27-3646-80AE-0B14BE67C96C
12/20
MSH-10 = DBB50295-EA1A-4D75-BADF-F58BCA375263
Accession# = DBB50295-EA1A-4D75-BADF-F58BCA375263
12/19
MSH-10 = 9CEE6B52-DB81-39C2-87DB-CD2ABD75BEBF
Accession# = 9CEE6B52-DB81-39C2-87DB-CD2ABD75BEBF
12/19
MSH-10 = 2C085FA1-DDB0-383E-A883-BE1E771319C2
Accession# = 2C085FA1-DDB0-383E-A883-BE1E771319C2
12/19
MSH-10 = DBA4CE84-0FB9-4329-ABB8-BB73522832BF
Accession# = DBA4CE84-0FB9-4329-ABB8-BB73522832BF
12/17
MSH-10 = 0C868A74-908A-437B-8B82-879D953B3AC3
Accession# = 0C868A74-908A-437B-8B82-879D953B3AC3
12/17
MSH-10 = 0C868A74-908A-437B-8B82-879D953B3AC3
Accession# = 0C868A74-908A-437B-8B82-879D953B3AC3
12/17
MSH-10 = 38E4114A-B246-4F46-9409-6421831A502D
Accession# = 38E4114A-B246-4F46-9409-6421831A502D
12/16
MSH-10 = 83CDFD5D-B49E-3DE2-A4A5-4C60CBB0FB6E
Accession# = 83CDFD5D-B49E-3DE2-A4A5-4C60CBB0FB6E
12/16
MSH-10 = 18F77A01-0C8D-4BD2-8420-9BE1C4B42BD7
Accession# = 18F77A01-0C8D-4BD2-8420-9BE1C4B42BD7
12/16
MSH-10 = 726BD7E8-9585-4C3C-B87D-683F5946CCFE
Accession# = 726BD7E8-9585-4C3C-B87D-683F5946CCFE
12/15
MSH-10 = 245AA44D-C7B2-38AC-BC27-5217162B89F2
Accession# = 245AA44D-C7B2-38AC-BC27-5217162B89F2
12/15
MSH-10 = 8B621348-4D89-4EA5-9BB6-9E0762E65823
Accession# = 8B621348-4D89-4EA5-9BB6-9E0762E65823
12/15
MSH-10 = D97E7901-559B-4113-A78E-64C8F10F47BF
Accession# = D97E7901-559B-4113-A78E-64C8F10F47BF
12/14
MSH-10 = 87F11178-9D96-4942-9C80-A164D0E4C46B
Accession# = 87F11178-9D96-4942-9C80-A164D0E4C46B
12/13
MSH-10 = 650E927B-288D-3F75-9025-263F3AB447DF
Accession# = 650E927B-288D-3F75-9025-263F3AB447DF
12/13
MSH-10 = 73A9698B-FB12-496C-82A6-829D6FC0F1DA
Accession# = 73A9698B-FB12-496C-82A6-829D6FC0F1DA
12/13
MSH-10 = FC69FB9C-A3B4-4ED3-987D-96052B2C9CF2
Accession# = FC69FB9C-A3B4-4ED3-987D-96052B2C9CF2
12/12
MSH-10 = 20D3E0F6-F6B7-4577-ABDA-4D4A6594C867
Accession# = 20D3E0F6-F6B7-4577-ABDA-4D4A6594C867
12/12
MSH-10 = 312D3960-9ECA-44CF-AB07-93720FADFAC6
Accession# = 312D3960-9ECA-44CF-AB07-93720FADFAC6
12/12
MSH-10 = 6CA29D0E-3A7B-3AD3-9065-C0C147A7D0C1
Accession# = 6CA29D0E-3A7B-3AD3-9065-C0C147A7D0C1
12/12
MSH-10 = 4550A9EB-1D37-38AF-8F31-5B9A07799354
Accession# = 4550A9EB-1D37-38AF-8F31-5B9A07799354
12/11
MSH-10 = 99E52AA5-A2BD-3B2D-8ECE-D57C8F884B3B
Accession# = 99E52AA5-A2BD-3B2D-8ECE-D57C8F884B3B
12/11
MSH-10 = D6DD6F59-40B0-4D1B-8EAA-26B0FC0E3BB8
Accession# = D6DD6F59-40B0-4D1B-8EAA-26B0FC0E3BB8
12/10
MSH-10 = BB1A4C2B-6C33-4CB4-83FC-F19E9C33015B
Accession# = BB1A4C2B-6C33-4CB4-83FC-F19E9C33015B
12/10
MSH-10 = 43B1916B-C9A0-4CDB-B561-3634134A14C4
Accession# = 43B1916B-C9A0-4CDB-B561-3634134A14C4
12/10
MSH-10 = 5DF85EEF-324E-3AA7-95FB-B15E07220763
Accession# = 5DF85EEF-324E-3AA7-95FB-B15E07220763
12/10
MSH-10 = A8865968-DF52-3882-ACEF-4468A8ED8B09
Accession# = A8865968-DF52-3882-ACEF-4468A8ED8B09
12/9
MSH-10 = D243E916-5506-4E93-9B4D-CA719D9F3E52
Accession# = D243E916-5506-4E93-9B4D-CA719D9F3E52
12/9
MSH-10 = B02D0069-88B9-3E08-B683-CC9639FDF238
Accession# = B02D0069-88B9-3E08-B683-CC9639FDF238
12/8
MSH-10 = 7BE81ECC-4C3D-4724-9DBF-09EA2A6CAA26
Accession# = 7BE81ECC-4C3D-4724-9DBF-09EA2A6CAA26
12/8
MSH-10 = 570212E0-F772-43FF-9BB1-431AD765EFD9
Accession# = 570212E0-F772-43FF-9BB1-431AD765EFD9
12/8
MSH-10 = 36E98251-3585-44BC-9AC5-6ABAAB082BB6
Accession# = 36E98251-3585-44BC-9AC5-6ABAAB082BB6
12/8
MSH-10 = C13393FD-D66E-45F0-B0EA-CC10F92417CE
Accession# = C13393FD-D66E-45F0-B0EA-CC10F92417CE
12/8
MSH-10 = AD5468A0-F2BA-4E55-90E4-8B099EBBABD5
Accession# = AD5468A0-F2BA-4E55-90E4-8B099EBBABD5
12/8
MSH-10 = BD908689-3ADC-49B5-8BBD-BD573A67728F
Accession# = BD908689-3ADC-49B5-8BBD-BD573A67728F
12/8
MSH-10 = 345A941F-2D83-4EAD-97D9-E2C0B6FAAF7C
Accession# = 345A941F-2D83-4EAD-97D9-E2C0B6FAAF7C
12/6
MSH-10 = 41218DFC-D166-4B55-B32A-655CFCA1B112
Accession# = 41218DFC-D166-4B55-B32A-655CFCA1B112
12/6
MSH-10 = 1907C559-97EA-472C-B365-F463522FF25A
Accession# = 1907C559-97EA-472C-B365-F463522FF25A
12/6
MSH-10 = B5CEE512-3BE4-4118-B53E-8941563FA4D1
Accession# = B5CEE512-3BE4-4118-B53E-8941563FA4D1
12/6
MSH-10 = C8AB9626-7BA6-423C-9F85-70ACB4BFCE03
Accession# = C8AB9626-7BA6-423C-9F85-70ACB4BFCE03
12/5
MSH-10 = E699D78E-05B1-4253-BD9B-24B63396322B
Accession# = E699D78E-05B1-4253-BD9B-24B63396322B
12/5
MSH-10 = C28E6C10-10AE-4ABE-AF4B-B78B9323289B
Accession# = C28E6C10-10AE-4ABE-AF4B-B78B9323289B
12/5
MSH-10 = E1069A53-7CCA-4F8B-A14B-F4338433095C
Accession# = E1069A53-7CCA-4F8B-A14B-F4338433095C
12/5
MSH-10 = 5B3FC9B6-75A2-4CF7-A626-A463A6A028BD
Accession# = 5B3FC9B6-75A2-4CF7-A626-A463A6A028BD
12/4
MSH-10 = 7ADD901C-A9B0-413E-80EA-8FE2B3F90D5F
Accession# = 7ADD901C-A9B0-413E-80EA-8FE2B3F90D5F
12/4
MSH-10 = 2E1E3B16-F4A0-4B3C-8300-AB419042B70D
Accession# = 2E1E3B16-F4A0-4B3C-8300-AB419042B70D
12/4
MSH-10 = 5B6004AF-E852-4425-A2CE-E3E610FF7CD6
Accession# = 5B6004AF-E852-4425-A2CE-E3E610FF7CD6
12/3
MSH-10 = 8FE60C80-672C-4637-A3A6-D61AA1A5A89C
Accession# = 8FE60C80-672C-4637-A3A6-D61AA1A5A89C
12/3
MSH-10 = 402B4842-E263-4AE3-A9B3-7F926034DF03
Accession# = 402B4842-E263-4AE3-A9B3-7F926034DF03
12/3
MSH-10 = C7327697-C354-4FF5-9C2B-F3157BED273C
Accession# = C7327697-C354-4FF5-9C2B-F3157BED273C
12/2
MSH-10 = 7241CD7F-7076-4BFB-A2F1-1B2F6D1DE66C
Accession# = 7241CD7F-7076-4BFB-A2F1-1B2F6D1DE66C
12/2
MSH-10 = FEE4AB60-B964-397F-BA5C-EAC670734180
Accession# = FEE4AB60-B964-397F-BA5C-EAC670734180
12/2
MSH-10 = 2AE887FC-00DA-3C8B-BD0D-B4AE9DC39AA9
Accession# = 2AE887FC-00DA-3C8B-BD0D-B4AE9DC39AA9
12/2
MSH-10 = 09B5B029-021A-3359-A8F9-AEA589DC37C7
Accession# = 09B5B029-021A-3359-A8F9-AEA589DC37C7
12/2
MSH-10 = D0F112BD-CA87-4FB4-834B-F286DF0B9986
Accession# = D0F112BD-CA87-4FB4-834B-F286DF0B9986
12/1
MSH-10 = 652838AD-7F9B-49F8-BF0C-EC9D889C29B1
Accession# = 652838AD-7F9B-49F8-BF0C-EC9D889C29B1
12/1
MSH-10 = B78FEBC4-C78D-4234-9876-5F68F6276FB4
Accession# = B78FEBC4-C78D-4234-9876-5F68F6276FB4

**Comment by oslynn** [comment]
This is done.  I updated the prod and staging setting to add gualityFilter to not allow invalid patient to go to RI.  And, I notified @BerniXiongA6 to requested for resubmission all messages with valid patient's information.
