### ISSUE TITLE
Message ID search doesn't trim leading/trailing whitespace

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7792]
## Describe the bug
When a user copies and pastes `message_id` values into the search box, sometimes the value includes leading or trailing whitespace, and the search doesn’t work.

Leading and following whitespace is not trimmed from search inputs.

## Impact on ReportStream
Message ID search requires fairly strict matching, so Ott and crew are unable to find their desired IDs without a clear indication as to why, considering whitespace is not always immediately noticeable.

## Steps to reproduce
1. Arrive at the Message ID ui with a valid ID to search
2. Ensure searching the ID without leading/trailing whitespace gives results
3. Add leading whitespace and ensure that this bug is valid
4. Add trailing whitespace and ensure that this bug is valid

## Expected behavior
Whitespace at the front and back of the value should be trimmed.

> **NOTE:** It's possible - but rarely, if ever, do we see it occurring - for a `messageId` to include middle whitespace. No current mechanisms in ReportStream prevent this. See [this Slack thread](https://www.slack.com/archives/C02HJ43AE8Z/p1672326722671439) for this conversation.

## Resources
N/A

## Logs
N/A

## Additional context
N/A

**Comment by oslynn** [comment]
The ticket looks good.

**Comment by chris-kuryak** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/7792?planning-poker) with Zenhub @kevinhaube

**Comment by chris-kuryak** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/7792?planning-poker) with Zenhub @jpandersen87 @penny-lischer

**Comment by kevinhaube** [comment]
Should deploy Thursday, Jan 12

**Comment by kevinhaube** [comment]
@chris-kuryak NOT worthy of `release_notes` as it's admin-only currently, but worth communicating in O&O sync today that this is going into prod with tomorrow's deployment :)

**Comment by chris-kuryak** [comment]
@kevinhaube Thanks!
I will include for next O+O sync. Sorry I didn't see this one in time.
