### ISSUE TITLE
Publish Release Notes - Jan 2023

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#7815]
## Problem statement
As a user, I would like to know what features, bugs, other user facing updates have been made to ReportStream product.

## Acceptance criteria

- [x] New Experience Items added as a comment
- [x] New STLT's finished onboarding this month added as a comment
- [x] New O+O Items added as a comment
- [x] New API Items added as a comment
- [x] Release Notes text (in ticket description) updated with all release notes
- [x] Experience team published to RS website on [Release Notes](https://reportstream.cdc.gov/product/release-notes) page

## Release Notes text
**Improvements**
- Accessibility: The ReportStream website now has a "skip navigation" link that takes users with screen readers to the main page content instead of tabbing through each nav item. To access it with a keyboard, for example, a user just hits TAB once, then ENTER to "click" the link.
- Usability: Now you don't need to re-login or re-logout across multiple browser tabs open on the ReportStream website. When logged in to the ReportStream website, if you open a new browser tab to the ReportStream website, you will already be logged in to the website. When you log out of the website on one browser tab, you will be logged out of all ReportStream browser tabs.
- Usability: On Daily Data table, to make it easier to find the file you are looking for, the "File" column now displays the entire filename instead of just the file type.

**New State Connections**
We’re excited to announce that ReportStream has recently established connections to send and report public health data with the following state: Utah

**Comment by chris-kuryak** [comment]
For this month's release notes, from issue #2772

Improved accessibility: The website now has a "skip navigation" link that takes users with screen readers to the main page content instead of tabbing through each nav item.
To access it with a keyboard, for example, a user just hits TAB once, then ENTER to "click" the link.

**Comment by chris-kuryak** [comment]
From #6868 :
Usability: Now you don't need to re-login or re-logout across open RS tabs:
- Remain logged in when opening a new tab while logged in
- All open tabs log in or out when logging in or out

**Comment by chris-kuryak** [comment]
From #7851:
Improved Usability: On Daily Data table, to make it easier to find the file you are looking for, the "File" column now displays the entire filename instead of just the file type.

**Comment by chris-kuryak** [comment]
From Brandon Canniff:
Utah (STLT) is now onboarded and live.

**Comment by chris-kuryak** [comment]
From Avniel Dravid:
No release notes. Universal pipeline work not ready to share with public.

**Comment by jillian-hammer** [comment]
Pull request: Update release-notes.md #8324
