### ISSUE TITLE
Publish What's New - Feb 2023

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#7816]
## Problem statement
As a user, I would like to know what features, bugs, other user facing updates have been made to ReportStream product.

## Acceptance criteria

- [x] New Web Experience Items added as a comment
- [x] New STLT's finished onboarding this month added as a comment
- [x] New Engagement Items added as a comment
- [x] New Platform Items added as a comment
- [x] Release Notes text (in ticket description) updated with all release notes
- [x] Release Notes text proofread by Content team
- [x] Experience team published to RS website on [Release Notes](https://reportstream.cdc.gov/product/release-notes) page

## Release Notes Text
**February 2023**
See Github release notes anytime at https://github.com/CDCgov/prime-reportstream/releases.

**Improvements**
- Usability: Based on user feedback, the filename is now shown on the Daily Data table for data receivers. Previously it only showed the data type without a filename. 

- Usability: On Daily Data table, if the user has multiple ELR settings, the first active one is automatically selected. This prevents an inactive setting from being selected upon table load.

- The ReportStream Terms of Service have been updated. Visit the [Terms of Service page](https://reportstream.cdc.gov/terms-of-service) to view them.

- Visual differences that appeared in the past few weeks after the ReportStream website updated to USWDS 3.0 have been fixed.

- Bug fix: When typing a non-numeric character into the Daily Data table date range, the table would show an error and disable use of the table. Now, when a non-numeric character is entered into the date range the table remains active and allows for the user to fix the entry into a numeric character. This prevents the user from needing to reload the table.

**Comment by chris-kuryak** [comment]
WebX Items:

- Replace File with Filename on Daily Data table #7851
- Daily Data loads with active receiver settings #7950
- Update the terms of service content on the RS website #8132

Check before publishing:
- Typing non-numeric characters into date range filter fields errors out #7998

**Comment by chris-kuryak** [comment]
From @brandonnava - No new STLTs or Engagement Team items.

From @avnieldravid - No new Platform Team items

**Comment by jillian-hammer** [comment]
@audreykwr can you proofread this before I submit the PR?

**Comment by audreykwr** [comment]
@jillian-hammer [updated content](https://docs.google.com/document/d/1JYngl1n8TPw_CRmyHHWFcwAS_S8pQRozVhETA4UApNI/edit)

**Comment by jillian-hammer** [comment]
PR is here: Update release-notes.md #8707

**Comment by jillian-hammer** [comment]
PR merged. Closing issue!
