### ISSUE TITLE
TX - 10 (TEN) Production Errors (Last Mile Failures)

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7818]
## Problem statement

Received Production Errors for TX for several days (1/1 and 1/2)

Example1:
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/6f3ec4e6-1e91-400d-8690-e453429a119f

## Logs
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/2ecca1e0-6735-4a4b-a0dd-328756d3ed6a)

To Do:

1) Assign to Engineer to Investigate
2) Do we need to resend? Please let helpdesk know and we can resend on The Lastmile ReportStream resend section.

**Comment by brick-green** [comment]
just resent these. Sorry, I didn't look at the to-do list. For the rest, I just test the connection then let helpdesk know.
