### ISSUE TITLE
MD - 9 (NINE) Production Errors (Last Mile Failures)

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7819]
## Problem statement

Many Production Failures occured (1/1 to 1/2) for the state of Maryland.

## What you need to know

Example 1:
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/ee18f478-01eb-4e60-9905-77d07ee5e394) 

LOG:
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/d3f59def-e518-4bfc-b874-150d537bf0c3)

## Acceptance criteria

- [ ] ...

## To do

- Assign an Engineer to investigate
- Do we need to resend? If yes, please advise helpdesk and we can resend via (Last mile failures) tool in ReportStream.

**Comment by brandonnava** [comment]
Assigning Sharon per resend request

**Comment by sliu1000** [comment]
All Resents Submitted Successfully.

(1) Report ID: d246440a-504c-45ca-b460-02252901d851
File Name: covid-19-20230102201525-d246440a-504c-45ca-b460-02252901d851-secondary.hl7
Destination:  md-phd.elr-secondary
Success. 
 Will resend all (10) items in d246440a-504c-45ca-b460-02252901d851
d246440a-504c-45ca-b460-02252901d851 has been queued to resend immediately to md-phd.elr-secondary

(2)  Report ID:  a63e5188-06c1-400b-8aad-13bf1a55f628
File Name:  covid-19-20230102141516-a63e5188-06c1-400b-8aad-13bf1a55f628-secondary.hl7
Destination: md-phd.elr-secondary
Success. 
 Will resend all (5) items in a63e5188-06c1-400b-8aad-13bf1a55f628
a63e5188-06c1-400b-8aad-13bf1a55f628 has been queued to resend immediately to md-phd.elr-secondary

(3) Report ID: f18c97e3-4b2d-4933-b8f7-c5b346b9343c
File Name: covid-19-20230102041516-f18c97e3-4b2d-4933-b8f7-c5b346b9343c-secondary.hl7
Destination: md-phd.elr-secondary

Success. 
 Will resend all (3) items in f18c97e3-4b2d-4933-b8f7-c5b346b9343c
f18c97e3-4b2d-4933-b8f7-c5b346b9343c has been queued to resend immediately to md-phd.elr-secondary

(4) Report ID: 866c7243-7e62-46a1-ac82-e41a95c71ce4
File Name: covid-19-866c7243-7e62-46a1-ac82-e41a95c71ce4-20230102021511.hl7
Destination: md-phd.elr

Success. 
 Will resend all (2) items in 866c7243-7e62-46a1-ac82-e41a95c71ce4
866c7243-7e62-46a1-ac82-e41a95c71ce4 has been queued to resend immediately to md-phd.elr

(5) Report ID: 52271f9d-9709-4946-acc0-89b705ff208d
File Name: covid-19-20230101221530-52271f9d-9709-4946-acc0-89b705ff208d-secondary.hl7
Destination: md-phd.elr-secondary

Success. 
 Will resend all (5) items in 52271f9d-9709-4946-acc0-89b705ff208d
52271f9d-9709-4946-acc0-89b705ff208d has been queued to resend immediately to md-phd.elr-secondary

(6) Report ID: 99210c38-24fc-4ce3-82ce-72a064e3547e
File Name: covid-19-20230102021512-99210c38-24fc-4ce3-82ce-72a064e3547e-secondary.hl7
Destination: md-phd.elr-secondary

Success. 
 Will resend all (5) items in 99210c38-24fc-4ce3-82ce-72a064e3547e
99210c38-24fc-4ce3-82ce-72a064e3547e has been queued to resend immediately to md-phd.elr-secondary

(7) Report ID: 8661837f-d9b3-41c6-91b1-cacae429e054
File Name: covid-19-8661837f-d9b3-41c6-91b1-cacae429e054-20230101201542.hl7
Destination: md-phd.elr

(8) Report ID: a7233bc0-4758-4cda-b55d-0c4abe59b597
File Name: covid-19-20230101181505-a7233bc0-4758-4cda-b55d-0c4abe59b597-secondary.hl7
Destination: md-phd.elr-secondary
Success. 
 Will resend all (6) items in a7233bc0-4758-4cda-b55d-0c4abe59b597
a7233bc0-4758-4cda-b55d-0c4abe59b597 has been queued to resend immediately to md-phd.elr-secondary

Success. 
 Will resend all (14) items in 8661837f-d9b3-41c6-91b1-cacae429e054
8661837f-d9b3-41c6-91b1-cacae429e054 has been queued to resend immediately to md-phd.elr

(9) Report ID: a7233bc0-4758-4cda-b55d-0c4abe59b597
File Name: covid-19-20230101181505-a7233bc0-4758-4cda-b55d-0c4abe59b597-secondary.hl7
Destination: md-phd.elr-secondary

(10) Report ID: 1287f6c7-c31e-46e0-b91b-cc0bb674fb92
File Name: covid-19-1287f6c7-c31e-46e0-b91b-cc0bb674fb92-20230101141511.hl7
Destination: md-phd.elr
Success. 
 Will resend all (6) items in 1287f6c7-c31e-46e0-b91b-cc0bb674fb92
1287f6c7-c31e-46e0-b91b-cc0bb674fb92 has been queued to resend immediately to md-phd.elr
