### ISSUE TITLE
MA - 5 (FIVE) Production Errors (Last Mile Failures)

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7820]
## Problem statement

Received Production Errors for TX for several days (1/1 and 1/2)

## What you need to know

Example 1:
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/7c73623a-0a5a-42f1-ba57-d91a1665c8e4)

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/09e7c277-9e51-4711-8501-410de780da70)

## To do

- Assign Engineer to Investigate
-Do we need to resubmit? Please advise helpdesk and we can try to resubmit via Last Mile Failure Tool.

**Comment by brick-green** [comment]
MA connections check passed. These can be resent @sliu1000

**Comment by sliu1000** [comment]
Resends Submitted Successfully:

(1) Report ID: 3e64769a-4f76-48cb-b0a7-483bf316ce28
File Name: prime-20230102165041.hl7
Destination: ma-phd.elr

Success. 
 Will resend all (16) items in 3e64769a-4f76-48cb-b0a7-483bf316ce28
3e64769a-4f76-48cb-b0a7-483bf316ce28 has been queued to resend immediately to ma-phd.elr

(2)  Report ID: a04d6565-4c1b-45ee-8bad-078f3127350e
File Name: prime-20230102145021.hl7
Destination: ma-phd.elr

Success. 
 Will resend all (14) items in a04d6565-4c1b-45ee-8bad-078f3127350e
a04d6565-4c1b-45ee-8bad-078f3127350e has been queued to resend immediately to ma-phd.elr

(3) Report ID: b74dfb5c-deaf-4100-8966-c6d8105f3f2a
File Name: prime-20230102125000.hl7
Destination: ma-phd.elr

(4) Report ID: 716acb7b-5e28-47a8-8925-e059d2913a1b
File Name: prime-20230101165004.hl7
Destination: ma-phd.elr

Success.  Will resend all (4) items in 716acb7b-5e28-47a8-8925-e059d2913a1b
716acb7b-5e28-47a8-8925-e059d2913a1b has been queued to resend immediately to ma-phd.elr

(5) Report ID: 146e6090-1854-4679-a5ee-fc02c6a17e2a
File Name: prime-20230101045046.hl7
Destination: ma-phd.elr

Success. 
 Will resend all (1) items in 146e6090-1854-4679-a5ee-fc02c6a17e2a
146e6090-1854-4679-a5ee-fc02c6a17e2a has been queued to resend immediately to ma-phd.elr
