### ISSUE TITLE
NJ - 2 (TWO) Production Errors (Last Mile Failures)

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7822]
## Problem statement

Production Errors on 1/1 for NJ.

## What you need to know

Example 1: NJ-doh-elr-secondary
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/59e2801f-b493-4702-b392-0039cad585ca)

Example 2:  NJ-doh-elr-test-secondary

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/3abf3248-9583-424b-9a44-e00c31ab0c11)

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/ac7a272b-73bf-4d70-8c53-30b03d65512a)

## To do

- Assign to Engineer to Investigate
- Resubmit?

**Comment by brick-green** [comment]
SFTP connection check passed. These can be resent via the last mile tool

**Comment by sliu1000** [comment]
Resents successfully resubmitted"

Report ID: 16d95d39-6299-4d84-90b6-d915185c9bad
File Name: covid-19-20230101144031-16d95d39-6299-4d84-90b6-d915185c9bad-secondary.hl7
Destination: nj-doh.elr-secondary

Success. 
 Will resend all (20) items in 16d95d39-6299-4d84-90b6-d915185c9bad
16d95d39-6299-4d84-90b6-d915185c9bad has been queued to resend immediately to nj-doh.elr-secondary

(2) Report ID: c6a68316-eb62-41dc-96c7-975288f1beb3
File Name: covid-19-20230101144036-c6a68316-eb62-41dc-96c7-975288f1beb3-secondary.hl7
Destination: nj-doh.elr-test-secondary

Success. 
 Will resend all (56) items in c6a68316-eb62-41dc-96c7-975288f1beb3
c6a68316-eb62-41dc-96c7-975288f1beb3 has been queued to resend immediately to nj-doh.elr-test-secondary
