### ISSUE TITLE
CA - 2 (TWO) Production Errors (Last Mile Failures)

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7823]
## Problem statement

Production Errors on 1/2/2023

## What you need to know

Example 1: ca-dph.elr-saphire
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/2353f03c-54d7-4c62-a355-d22297fe290a)

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/9bb7435c-c137-43ca-a13e-64d696e762db)

## To do

- Assign to an Engineer to Investigate
- Resubmit?

**Comment by brick-green** [comment]
sftp check passed. These can be resent @sliu1000

**Comment by Jcavallo7** [comment]
resubmission completed

**Comment by brandonnava** [comment]
@Jcavallo7 @sliu1000 To confirm, resubmission went through no problems? I can close this?
