### ISSUE TITLE
AK - 1 (ONE) Production Errors (Last Mile Failure)

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7824]
## Problem statement

Production Error on 1/2/2023

## What you need to know

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/ff9882a7-2dc6-4765-a895-35c4404581d4)

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/d870c30a-5e24-4b0b-b71b-6774d63423e8)

## To do

- Assign to Engineer
- Resubmit?

**Comment by brick-green** [comment]
sftp check passed. These can be resent @sliu1000
