### ISSUE TITLE
FL - 1 (ONE) Production Error (Last Mile Failure)

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7825]
## Problem statement

Production error on 1/1/2023

## What you need to know

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/ab1231f2-2754-4a47-9ba7-da1a4e866110)

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/4146a72c-8269-4709-9693-f4602da6d75a)

## To do

- Assign Engineer to investigate
- Resubmit?

**Comment by brick-green** [comment]
sftp check passed. Can be resent @sliu1000

**Comment by Jcavallo7** [comment]
report resent
