### ISSUE TITLE
OR - 1 (ONE) Production Error (Last Mile Failure)

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7826]
## Problem statement

Production error on 1/1/2023

## What you need to know

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/748b538e-f86e-4ee9-9192-e2c90b32be40)

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/6cf183b0-6c5a-4eac-8ece-058321b66933)

## To do

- Assign to an Engineer to Investigate
- Resubmit?

**Comment by brick-green** [comment]
sftp check passed. Can be resent @sliu1000
