### ISSUE TITLE
Lean content inventory of API programmer's guide

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#7828]
### **Background & Context**
As part of the work to transfer the API programmer's guide PDF content to the website, we want to take stock of all the components used in the current guide.

### **Working Links**
[Flo's content audit ](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1672412662691/888f40d9e714837654e616612dfc9761bf191576?sender=u791b7d4d34761ac59b672214)
[Completed Design Audit
](https://docs.google.com/document/d/1X5Lcysor_wod63OdvEzoCstl5QGBv6bl/edit?usp=sharing&ouid=108375376459243880703&rtpof=true&sd=true)

### **Acceptance Criteria**
- [x] Review of the guide to categorize all the components used today, like images, tables, lists, markup examples

**Comment by jillian-hammer** [comment]
Completed this work! See the annotated version of the Programmer's Guide [here](https://docs.google.com/document/d/1X5Lcysor_wod63OdvEzoCstl5QGBv6bl/edit?usp=sharing&ouid=108375376459243880703&rtpof=true&sd=true). I've marked up the content with the corresponding component.

Copying the list below as well:

**Existing components**

- Prose 
- - H1-H6
- - Body text
- List
- - Unordered
- - Ordered
- Link
- - Internal
- - External
- Process list
- Card
- In-page navigation
- Side navigation
- Table (reuse Message ID table; sortable + truncation -> modal)
- Download table as CSV (reuse Validation tool download button)
- Image

**New components**

- Last updated 
- Callout/tip
- Body text
- Unordered list
- Ordered list
- Code snippet (with opt. ability to apply in-line styling + copy to clipboard)
- In-line
- Multi-line (expand UI, scrollbar) 
- Label 

Now that the components are identified, I will use this list as a starting point for wireframes! (#8481)

cc: @lizzieamanning @audreykwr @chris-kuryak

**Comment by jillian-hammer** [comment]
This work is completed; upcoming work captured in the Wireframes ticket #8481. Closing!
