### ISSUE TITLE
CA - Accession Number Discrepancy

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#7835]
From Theodora.Fries@cdph.ca.gov:

Hello, happy new year!

Got the below interesting report from an LHJ- three results came in through SimpleReport, for different patient names and different providers, but the exact same accession numbers and specimen collection dates. Assuming these are truly three distinct results, from the unrelated facilities, can you think of anything that might have happened to conflate the accession IDs and other info?
![image.png](https://images.zenhubusercontent.com/62828b77597e3bdcbc3834fd/3d10720f-7bef-42c7-9f34-3aa214f144f9)
Thanks!

Teddy Fries | Pronouns: she/her
CalREDIE CSV/Alternate Lab Reporting Team Lead
Communicable Disease Emergency Response
Division of Communicable Disease Control
California Department of Public Health
Theodora.Fries@cdph.ca.gov
------------------------------------------------------------------------------------------------------------------------------------------
From: Kelly Chung <kchung@ph.lacounty.gov>
Sent: Tuesday, January 3, 2023 7:34 AM
To: Jenkins, Garrett@CDPH <Garrett.Jenkins@cdph.ca.gov>; Deshmane, Sanmati@CDPH <Sanmati.Deshmane@cdph.ca.gov>; Meesey, Jill@CDPH <Jill.Meesey@cdph.ca.gov>; Carroll, Ellaison@CDPH <Ellaison.Carroll@cdph.ca.gov>; Fries, Theodora@CDPH <Theodora.Fries@cdph.ca.gov>
Cc: hylee <hylee@ph.lacounty.gov>; Keilina Lu <KLu@ph.lacounty.gov>
Subject: Prime Report Stream CDPH000085

Hi,

We have received same Acc#s for different patients from Report Stream

Received 1/3/2022 ACC#121422_2 ( same ACC#s from three different performing facilities)

OBX|1|CE|94500-6^SARS-CoV-2 (COVID-19) RNA NAA+probe Ql (Resp)^LN||260385009^Negative^SCT^260385009^Negative^SCT|||N^Normal (applies to non-numeric results)^HL70078^^^^2.5.1|||F|||20221213160000-0800|14D2098020^IMMEDIATE CARE CENTER OF WESTMONT^CLIA||^TaqPath COVID-19 Combo Kit_Thermo Fisher Scientific, Inc._EUA^99ELR||20221213160000-0800||||IMMEDIATE CARE CENTER OF WESTMONT-14D2098020^^^^^CLIA&2.16.840.1.113883.4.7&ISO^XX^^^14D2098020|29 N CASS AVE^^WESTMONT^IL^60559^USA|

OBX|1|CE|94500-6^SARS-CoV-2 (COVID-19) RNA NAA+probe Ql (Resp)^LN||260385009^Negative^SCT^260385009^Negative^SCT|||N^Normal (applies to non-numeric results)^HL70078^^^^2.5.1|||F|||20221213160000-0800|05D2062640^PACIFIC CLINICAL LABORATORY^CLIA||^TaqPath COVID-19 Combo Kit_Thermo Fisher Scientific, Inc._EUA^99ELR||20221213160000-0800||||PACIFIC CLINICAL LABORATORY-05D2062640^^^^^CLIA&2.16.840.1.113883.4.7&ISO^XX^^^05D2062640|1304 15TH STREET^#318^SANTA MONICA^CA^90404^USA| 

OBX|1|CE|94500-6^SARS-CoV-2 (COVID-19) RNA NAA+probe Ql (Resp)^LN||260385009^Negative^SCT^260385009^Negative^SCT|||N^Normal (applies to non-numeric results)^HL70078^^^^2.5.1|||F|||20221213160000-0800|05D1013559^JRS LABORATORY^CLIA||^TaqPath COVID-19 Combo Kit_Thermo Fisher Scientific, Inc._EUA^99ELR||20221213160000-0800||||JRS LABORATORY-05D1013559^^^^^CLIA&2.16.840.1.113883.4.7&ISO^XX^^^05D1013559|1304 15TH STREET^#318^SANTA MONICA^CA^90404^USA|

As is same for CalREDIE, subsequent ELRs with same accession numbers are getting attached to the original ELR with same ACC#s

Can you see if you can find solution to differentiate ACC#s from different facilities?

Thanks,
Kelly

**Comment by rnz6** [comment]
Follow up from user: 

Hi ReportStream Team!

Just wanted to check in on the below ticket, get a feel for what a timeline on resolution might be. Thanks so much!

Teddy Fries | Pronouns: she/her

**Comment by brandonnava** [comment]
Verify and track back where the result came from. 
If they are from different places figure out why and if there's a problem. 
May or may not be an issue
Might require a resend
@sliu1000 Can you investigate? If need help let us know!

**Comment by sliu1000** [comment]
@rnz6 Jessica, can you please do the leg work in researching this a bit further.

**Comment by sliu1000** [comment]
Spoke to Teddy and was able to resolve this issue.  It was a manual entry error from the reporter/lab.
