### ISSUE TITLE
Replace native HTML button elements with Trussworks' Button component

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#7837]
## Problem statement

We have a few places where we're using native HTML `button` elements instead of Trussworks' `Button` element.  Since we're already using the latter more frequently in the codebase, we should convert the native HTML elements so they're consistent across the board.  This'll also help with any migration should we choose to migrate away from Trussworks' component system.

This is relevant to [6652](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/6652).

## What you need to know

There are two places in the code that we're using native HTML buttons:
- [Pagination.tsx](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/components/Table/Pagination.tsx#L35)
- [ColumnData.tsx](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/components/Table/ColumnData.tsx#L103)

## Acceptance criteria

- [ ] The `button`s are replaced with `Button`s with no user-facing impact

## Related links

- [GitHub discussion](https://github.com/CDCgov/prime-reportstream/pull/7796#discussion_r1060918942)

**Comment by kevinhaube** [comment]
Should deploy Thursday, Jan 12
