### ISSUE TITLE
External link URLs as constants

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7840]
## Problem statement

External links are all over the site, and route to various government and non-government resources. **We want to keep a directory of these links for easier auditing of where our site links out to.** To achieve this, we want all external URLs consolidated in a single file for use in the app.

## What you need to know

Links in markdown content cannot utilize imported javascript modules by default. Luckily a large portion of public site content is still written as `JSX`. Markdown page links could out of scope.

Origin of this ticket: https://github.com/CDCgov/prime-reportstream/pull/7796#discussion_r1060893039

## Acceptance criteria

- [ ] A consolidated and accessible source for all external link urls
- [ ] All external links converted to use this pattern

## To do

- [ ] ...

**Comment by stephenkao** [comment]
Closing because we already have [content/site.json](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/content/site.json) for the short term, and this is something we'll most likely touch on with sitemap/SEO work anyway.
