### ISSUE TITLE
USLink parses url for protocols

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7841]
## Problem statement

The `to` prop for a `USLink` can contain many unique values, from a relative route to a `mailto:` link. When using the component, we provide an override `anchor` prop that lets us dictate whether something should render as an `a` or `Link` element. **To provide a better experience using the `USLink` component, we should implement logic to parse the following, and correctly set the element to either an anchor or Link.**

## What you need to know

Origin of this work: https://github.com/CDCgov/prime-reportstream/pull/7796#discussion_r1060902074
From the above PR comments:
- `http(s)://`
- `mailto:`
- `tel:`
- `javascript:`
- `#`

## Acceptance criteria

- [ ] USLink can auto-detect which element is needed
- [ ] USLink no longer requires `anchor` prop

## To do

- [ ] ...

**Comment by kevinhaube** [comment]
@stephenkao Heads up, looks like we should move away from `javascript:` links anyway.
![Screen Shot 2023-01-06 at 10.23.24 AM.png](https://images.zenhubusercontent.com/611a907ec3e013d0e33e58a7/b3bd7e2c-0f82-4ac2-9619-8bb771cc5c54)

**Comment by jpandersen87** [comment]
Closed by #8254
