### ISSUE TITLE
Update Message structure to include additional data

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#7850]
## Problem statement

We need to add some additional fields to the messages response payload so we can display them in the redesigned Message Tracker.  Specifically, the missing fields are:

- Performing Facility

## What you need to know

- For `Performing Facility`:
  - See [processMesageDetailRequest](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/azure/MessagesFunctions.kt#L156) as a starting point
  - We should return `testing_facility_name` as part of the payload

## Acceptance criteria

- [ ] The message detail endpoint (`/api/message/<report_index>`) includes the above fields.

**Comment by arnejduranovic** [comment]
I don't have an issue with this proposal, looks good to me.

**Comment by kevinhaube** [comment]
@chris-kuryak @penny-lischer 
Hey, this seems to have competing verbage: `orderingFacility` vs `Performing Facility`. These are two different fields within the table: `ordering_facility_name` and `testing_lab_name` respectively, I believe. Which is the true addition needed?

**Comment by chris-kuryak** [comment]
@jillian-hammer See question from Kevin Haube above. Do you know if the O+O folks specifically wanted the Ordering Facility or the Testing Lab Name displayed in that area? If unsure, we can ping the O+O folks.

cc: @stephenkao for awareness

**Comment by stephenkao** [comment]
> @chris-kuryak @penny-lischer Hey, this seems to have competing verbage: `orderingFacility` vs `Performing Facility`. These are two different fields within the table: `ordering_facility_name` and `testing_lab_name` respectively, I believe. Which is the true addition needed?

Sorry, that's my bad -- it seems like this is an alias for multiple fields in the schemas, e.g.:
- https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/schema_documentation/pa-pa-covid-19.md
- https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/schema_documentation/direct-anavasidx-covid-19.md

I think `testing_lab_name` is actually correct for this use case, but I'll defer to Jillian and O&O!

**Comment by jillian-hammer** [comment]
I believe "Performing Facility" refers to `testing_lab_name` and not the ordering facility, but worth checking in with O&O to double check! @kevinhaube 

cc @chris-kuryak

**Comment by stephenkao** [comment]
Updated the ticket!  Thanks for catching this, @kevinhaube!

**Comment by kevinhaube** [comment]
Closing for now. Will re-open **IF** O&O finds this to be critical for this iteration. If not, efforts will be made by Platform to generalize this endpoint for retrieval of all messages, not strictly those within the covid metadata table. :)
