### ISSUE TITLE
Replace File with Filename on Daily Data table

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#7851]
## Problem statement

On Daily Data there's a column for File. The value in the field is almost always "HL7_BATCH". That value does not provide much value to users. Instead, that value should be the name of the file. This will give users an other option for identifying files that need further examination. For example, when a STLT sends a service request saying "The first message in file XYZ.csv has a missing field". Currently, the filename is not viewable in daily data. So it would have to be queried for. The file name can be accessed via the `report_file` table in the `external_name` column.

## What you need to know

![image.png](https://images.zenhubusercontent.com/60d23d7dcaf07751be9205b6/f926355b-6cc8-492f-babc-9ed8421d1a25) [Links to documents, workflows, or list of key people and contact info]

## Acceptance criteria

- [ ] Report file name is present in File column in Daily Data
- [ ] file name is clickable and will download the file

**Comment by kevinhaube** [comment]
Current response on `/daily-data` yields an array of this object shape:
```
{
  "deliveryId" : 12345678,
  "batchReadyAt" : "2022-12-16T20:06:00.658Z",
  "expires" : "2023-01-15T20:06:00.658Z",
  "receiver" : "org-name.receiver-setting",
  "reportId" : "b6c90d6d-6fc9-4458-9e66-ac66e5078032",
  "topic" : "covid-19", // or "full-elr" or "monkeypox"
  "reportItemCount" : 1,
  "fileName" : "covid-19-50221216200500-b6c90d7d-7fc9-4455-9e66-ac77e5078032-secondary.hl7",
  "fileType" : "HL7_BATCH"
}
```

For context, this is not the actual file name ([Jim's threaded response](https://fearless.slack.com/archives/C02HJ43AE8Z/p1672764040430279?thread_ts=1672428864.293759&cid=C02HJ43AE8Z)). @brick-green Just want to make sure that the above `fileName` _is_ the type of file name that's of use to the `receiver`.

**Comment by chris-kuryak** [comment]
@kevinhaube @stephenkao Do you think we have enough info on this one to begin refinement and slide it into the sprint backlog?

**Comment by brick-green** [comment]
Yep, fileName looks like the correct field to use. @kevinhaube also made a note that the field is quite long. That example seems longer than average but I might be wrong there. If space is an issue I think the reportID field could be truncated first. That field is not useful to STLTs, only to RS staff. Or perhaps this could be a place for the expanding field like what @jillian-hammer showed for the new message ID search results?

**Comment by chris-kuryak** [comment]
@brick-green For my own education, does the existing link (and now future link) under the FILE column download the file to your personal machine? And does that file contain PII (personally identifiable information)?

**Comment by brick-green** [comment]
@chris-kuryak yes it downloads to the folder you've set for downloads in your browser. the default is typically /downloads. Then yes that file does contain PII. It's exactly what's is sent out the the STLT

**Comment by stephenkao** [comment]
> @chris-kuryak Yep! And to Brick's point, I think in this work, we can fit in a change to the display text for the `Report ID` column. Maybe even shortening it to just an appropriate icon button with the column heading `Details` instead of it's current heading.
> 
> @jillian-hammer and @stephenkao Thoughts?

Yep, sounds good to me!  We can truncate/replace/display whatever we want, but I'd say the specifics here are Jillian's call 🙏

**Comment by chris-kuryak** [comment]
@brick-green Thanks!

**Comment by kevinhaube** [comment]
@chris-kuryak should deploy Tuesday, Jan 17! Will add "release notes" since this is a customer-facing change.

In short, where we used to show the file type, such as `HL7 (BATCH)`, we now show the file _name_.
Screenshot from staging:
<img width="790" alt="Screen Shot 2023-01-13 at 11 17 22 AM" src="https://user-images.githubusercontent.com/4022304/212367778-b8c32f6d-6f2e-4201-95de-8cb052bad602.png">
