### ISSUE TITLE
Delete ReportStream Wiki team page

### ISSUE THREAD

**Issue by snesm** [CDCgov/prime-reportstream#7860]
## Problem statement

Delete ReportStream Wiki team [page](https://github.com/CDCgov/prime-reportstream/wiki/About-ReportStream-Team)

The About ReporStream Team wiki page provides too much information to the public about staffing and is currently unmaintained.

## What you need to know

After significant recent staffing changes the ReporStream team Wiki page is significantly out of date.

**Comment by jeremy-page** [comment]
We'll need to talk about this at eng sync

**Comment by snesm** [comment]
Page saved (to my workstation) and deleted.
