### ISSUE TITLE
Add App Insights dashboard to Terraform

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#7871]
To assist with [this issue](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/7869) - They have a query etc already to go, we just need to translate it into IaC and then show the team how to add more graphs moving forward.

Penny Lischer is the primary contact for this on the dev side.

**Comment by jeremy-page** [comment]
Attached is the query definitions for the dashboard.
[queries.json.txt](https://github.com/CDCgov/prime-reportstream/files/10376516/queries.json.txt)

**Comment by penny-lischer** [comment]
Latest query definitions for the dashboard.
[queries.json.txt](https://github.com/CDCgov/prime-reportstream/files/10492201/queries.json.txt)

**Comment by lucasdze** [comment]
resolved with PR #https://github.com/CDCgov/prime-reportstream/pull/8438 & # https://github.com/CDCgov/prime-reportstream/pull/8150
