### ISSUE TITLE
TX- Account due for Recertification 

### ISSUE THREAD

**Issue by cmo44** [CDCgov/prime-reportstream#7882]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [X ] Other

**Please describe how you'd like us to help.**

If you need support for your HHS Enterprise Portal account or applications you access, please contact the HHSC Consolidated Help Desk at (512) 438-4720.

 Online HELP for using the HHS Enterprise Portal is available by clicking here.

 Questions about Recertifying a user’s access? See the Recertification Help Guide.

·         If access has been removed or terminated due to not being recertified, a request for new access must be submitted via the Portal.

·         If access requires modification, a request to modify access must be submitted via the Portal.
 
Please note:

For us to provide prompt processing of your requests, please observe the following:

·         Access inquiries may be made after 2 business days by calling the HHSC Consolidated Help Desk at (512) 438-4720. Do not contact provisioners directly.

·         Access support should be requested by calling the HHSC Consolidated Help Desk at (512) 438-4720. Do not contact provisioners directly.

·         Do not resubmit requests unless instructed to do so by provisioning staff. 

Access requests for many applications and systems are available in the HHS Enterprise Portal.  A list of applications that may be requested using the HHS Enterprise Portal can be viewed by clicking here. Access requests for those applications and systems may only be submitted using the HHS Enterprise Portal.
 
For applications that are NOT requested using the HHS Enterprise Portal, complete the appropriate access request form and submit to Enterprise_Provisioning@hhsc.state.ts.us.

A list of applications that must be requested using an access request form can be viewed by clicking here. Forms are available for download from the HHS Enterprise Portal or on The Connection. All required approvals must be obtained before form is submitted.
 
TIERS access requests must be submitted on form 4743A and submitted to TIERS_Provision@hhsc.state.tx.us. Forms are available for download from the HHS Enterprise Portal or on The Connection.  All required approvals must be obtained before form is submitted.

**Original Communication below:**

"Hi Maurice Reeves,

Your account is due for recertification.
The request to recertify has been sent to the supervisor.

Below are the details:

Application: EFTServer
Owner Name: Maurice Reeves

If the account is not certified by due date, the account will be suspended.

(During CAPPS HCM recertification month, failure to recertify elevated access will revert the CAPPS HCM account to Basic level.)

For further help, or if you believe you have received this email in error, please notify the Help Desk at 512-438-4720.
Thank you,
HHS Enterprise Identity and Access Management"

![image.png](https://images.zenhubusercontent.com/636c1583781a7784128d8e0c/f9369743-c6c1-4a05-8b8b-02eae4d66e9b)

**Comment by brandonnava** [comment]
@oslynn to role in to larger TX support

**Comment by oslynn** [comment]
@Sharon is taking over this ticket.

**Comment by sliu1000** [comment]
@MauriceReeves-usds 

I called HHS Texas and they created two separate tickets.

Ticket # 1 - Add the main Reportstream@cdc.gov email to the account. The support person mentioned that this may not be possible but will try.

Ticket # 2 - Created another ticket to find out who the HHS contact is to recertify our access. As the supervisor of the  account needs to recertify all the users.

**Comment by LaFreda1** [comment]
@sliu1000 any word on this?

**Comment by sliu1000** [comment]
@jeremy-page @Jcavallo7 @LaFreda1  Hi Jeremy, do we need to do anything with this Texas recertification? Or can we close it?

**Comment by LaFreda1** [comment]
@sliu1000  this ticket connected to #8545 (I closed this today). Also, it is best to communicate your questions/comments to Jeremy via slack to make sure he sees it.
