### ISSUE TITLE
Add Webpage filtration to the pageview and session website analytics visualizations

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#7884]
## Problem statement
Currently, the Pageview and Session charts in the website analytics dashboard show data for the entire site and cannot be broken down by specific page. It would be helpful for product owners to be able to see Pageview and Session data filterable by specific page on the RS website. This will allow product owners to determine how changes to the webpages affect the user interactions/traffic on those specific webpages.

Adding a "page" filter to the existing charts is a sufficient solution.
Chris Kuryak can further clarify requirements if needed.

## What you need to know

Existing work on Session and Pageview:
- #7625
- #7626

## Acceptance criteria

- [x] Pageview data able to filter not only by date range and user type, but also by specific web page
~~- [ ] Session data able to filter not only by date range and user type, but also by specific web page~~ Unclear on benefit of this view in the MVP. Removing from ACs per Chris Kuryak
- [x] Review/UAT goes through PO (Chris Kuryak)

**Comment by penny-lischer** [comment]
//Pageview data able to filter not only by date range and user type, but also by specific web page
let usg_events = dynamic(["*"]);
let mainTable = union pageViews
    | where timestamp > ago(90d)
    | where isempty(operation_SyntheticSource)
    | extend name =replace("\n", "", name)
    | extend name =replace("\r", "", name)
    | where '*' in (usg_events) or name in (usg_events);
let queryTable = mainTable;
queryTable
| extend dimension = todynamic(tostring(customDimensions["activeMembership"]))
| evaluate bag_unpack(dimension)
| extend member_type = iif(isempty(memberType), "unauthenticated", memberType)
| summarize PageCount = count() by member_type, operation_Name
| project
    ["Page Viewed"] = operation_Name,
    p = pack(strcat(member_type, " visit count"), PageCount)
| summarize b = make_bag(p) by ["Page Viewed"]
| order by ['Page Viewed'] asc 
| evaluate bag_unpack(b)

//dynamic(["*"]) - can specify all with * or can specify specific name in usg_events as strings i.e.dynamic(["Daily Data | Table Pagination", "Submissions | Table Pagination"])
//pack() Creates a dynamic property bag object from a list of keys and values   
//make_bag() Creates a dynamic JSON property bag (dictionary) of all the values of expr in the group.
//bag_unpack() transforms the bag keys in the make_bag() output into columns

**Comment by penny-lischer** [comment]
![Screenshot 2023-01-17 at 10.38.04 AM.png](https://images.zenhubusercontent.com/62697ac1be6e84867ab47e74/c68b10fc-f220-40ca-b0dd-f9e83a3bb63c)

**Comment by chris-kuryak** [comment]
Closing per meeting all ACs and approving the table view.
