### ISSUE TITLE
Create Authenticated User Sitemap

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#7889]
### **Background & Context**
Currently, our sitemap only includes the pages on the public website. To better understand the experience of our internal and external users and inform future feature development, our team needs a shared understanding of the sitemap from an authenticated user's POV. 

The findings & sitemap help inform:
- Short-term: Where the automated key tool (#7862) should live on the site
- Long-term: IA strategy 

### **Open Questions**
- [ ] What does an **authenticated sender** see on the RS website and how can we reproduce it from our Admin accounts?
- [ ] What does an **authenticated receiver** receiver see on the RS website and how can we reproduce it from our Admin accounts?
- [ ] What is the IA of the **Prime Admin Tools** section?

### **Working Links**
- [Sitemap Mural
](https://app.mural.co/invitation/mural/nava4113/1671805673271?sender=u0c3cdba5126734aceb613229&key=17cb76f4-ff00-4515-ac75-a6be2cf10eb9)
- Existing work: [Website content audit ](https://airtable.com/invite/l?inviteId=invDweYvWCSoSGqug&inviteToken=64fcac124a01d497334bb34632a17c628638878f594efd0369dad644ce50f4cf&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts) 

### **Acceptance Criteria**
- [ ] Discovery: Ask engineers which senders and receiver profiles we can use as representative models for building the sitemap
- [ ] Authenticated sitemap created in Mural 
- [ ] Permissions of the different user types (Prime Admin, Sender, and Receiver) included on the sitemap
- [ ] Share sitemap with the team
- [ ] Incorporate feedback as needed
- [ ] Share the link as reference in onboarding documents

### **Review Info**
- Design Lead to review

**Comment by chris-kuryak** [comment]
Close per Jillian
