### ISSUE TITLE
MessageID related: Implement API For COVID Table

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#7892]
## Problem statement

The O+O team has requested that we display covid-specific data, specifically the ordering facility, as part of the Message Tracker feature [#6992](https://github.com/cdcgov/prime-reportstream/issues/6992). There was an attempt as part of PR [#7885](https://github.com/CDCgov/prime-reportstream/pull/7885) to update the `Message` object returned by the`/api/message/{id}` and `/api/messages` endpoints but, as discussed in that PR, we reverted the change since we agreed that these endpoints should not be covid specific, and we should create separate endpoints for covid data instead. See below for the relevant comment made in the aforementioned PR that discusses the issue with the original implementation and proposed solution:

The endpoints that return the `Message` object, `/api/message/{id}` and `/api/messages`, both appear to be NOT covid specific. These endpoints, as documented here, functionally do not have to rely on the covid database table, although currently they do. Adding `testingLabName` here would now make the `messages` endpoints tightly coupled to the covid table, which I think would be a significant step backwards, seeing as we would like to move away from the covid pipeline.

Furthermore, I do not see why a seemingly generic feature such as "message tracker" needs to be coupled to covid at all. If "message tracker" needs to show covid-specific information, I would propose we add a NEW endpoint that can return a NEW covid-table-specific message object, like `CovidMessage`, for example. Then, if it determines the message in question is a covid message, the message tracker feature can call the new endpoint in addition to the current endpoint to get ALL the covid-specific data, not just `testingLabName`. If the O+O team currently wants "testingLabName" in the message tracker, it seems reasonable that they may request additional data be provided in the future. Furthermore, it goes without saying, we should update the query to use the `elr_result_metadata` table instead of covid table. This method has the following advantages over the current approach:

1.  The current messages endpoints remain decoupled from any specific "topic" and, as such, can be used for other topics/pipelines
2.  Adding a new endpoint for covid messages means we can add all the covid specific data-points you want without breaking any good practices, since it would be specific to covid

## Acceptance criteria

- [ ] Create new endpoints for COVID messages, similar to `/api/message/{id}` and `/api/messages`. These endpoints should return data from the covid table

## To do

- [ ] Notify Experience team of change when complete

**Comment by stephenkao** [comment]
@arnejduranovic We confirmed that the field is a nice-to-have, not a blocker, for the Message Tracker updates so this ticket can be deprioritized.  It's still relevant in moving off of the `covid_result_metadata` table for generalized usage in the future, but the need for COVID-specific data is no longer necessary as part of our Message Tracker work!  

Up to you if you want to close it for now, though!

**Comment by arnejduranovic** [comment]
> @arnejduranovic We confirmed that the field is a nice-to-have, not a blocker, for the Message Tracker updates so this ticket can be deprioritized. It's still relevant in moving off of the `covid_result_metadata` table for generalized usage in the future, but the need for COVID-specific data is no longer necessary as part of our Message Tracker work!
> 
> Up to you if you want to close it for now, though!

Thanks for the update! I updated this ticket to only be for creating the new COVID message endpoints. [7911](https://github.com/CDCgov/prime-reportstream/issues/7911) now covers updating the existing message API to use elr table.

**Comment by jimduff-usds** [comment]
My thinking on this has changed.   See #8031 , #8032, #8033
