### ISSUE TITLE
prime cli fake test file generation is broke.

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#7897]
Using csv-otc-covid-19.schema, The command Fake file generates wrong values for Patient_state and Patient_county.  It also adds extra columns patient_state to the file.

To duplicate the issue run the following command:
./prime data --input-fake 2 --input-schema csv-otc-covid-19 --output PATH/TO/pdi-covid-19-ri.csv --target-states RI

Generated Output file contains wrong Patient_state and Patient_county instead of RI.

![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/a3fc5ae3-516a-44ea-af20-53da13e73380)

**Comment by adegolier** [comment]
I believe I've got the extra columns and weird random text values fixed. Moving on to "Why is the target state wrong?"

**Comment by adegolier** [comment]
PR [#8263](https://github.com/CDCgov/prime-reportstream/pull/8263)
