### ISSUE TITLE
Design Comp for Automated Public Key / Token Auth Tool

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#7899]
### **Background & Context**
The sender emails us two separate public keys. Then those are stored in the database under sender settings. (Currently stored on staging and prod.) Then we send them an email that they can start testing (authentication) and includes the API endpoint to point to. And link them to API Programmer's guide.This happens on almost every new sender (majority). Server-to-server auth.

This tool requires a sender's authenticated login.

### **Open Questions**
- [x] Where does this tool live on the RS website?
- [x] In the case of an error, is any additional follow up needed beyond just an error message on the website (ie: separate email)?

### **Working Links**
- [Figma Workspace](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=1203%3A14237&scaling=min-zoom&page-id=1179%3A14239&starting-point-node-id=1203%3A14237)
- [Figma Final Design - Eng Ready](https://www.figma.com/file/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=2167%3A21663&t=WLhbJIqQnfBOulOo-1)
- [Automated Key Tool | Design Brief](https://docs.google.com/document/d/1cQGAE-tY2jP8KpVzr1KR786xQfVDKrtdOI5Td6qe00Y/edit?usp=share_link)

### **Acceptance Criteria**
- [x] Design includes `file-input` component for uploading file
- [x] Design includes submit button
- [x] Design includes error message
- [x] Sender can change their key
- [x] Provides instructions on next steps after success
- [x] Work with Exp Eng team to define ACs and tickets for followup engineering work
- [ ] Get with @chris-kuryak to share design with Jim Duff

### **Review Info**
- Experience Eng team feedback

**Comment by lizzieamanning** [comment]
@jillian-hammer does this need to live behind the login?

**Comment by jillian-hammer** [comment]
@chris-kuryak ready to close this as long as you can capture the AC to consult with Jim elsewhere!

**Comment by chris-kuryak** [comment]
Thanks @jillian-hammer
I'm setting up a time with Jim and the API team to review.
