### ISSUE TITLE
HI Onboarding - Build Receiver Settings

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#7900]
### Acceptance Criteria 
- [ ] Added to organization.yml and created yamlitos  
    - [ ] Customer status = testing  
- [ ] Added to prod settings table  
    - [ ] Added quality filter = allowNone() 
- [ ] Added to staging settings table  
    - [ ] Added quality filter = allowNone() 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with receiver 
- [ ] RS team member who originates this ticket: add any dependencies, as needed 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [X] Pipelines: Onboarding & Operations (New) 
     - [X] Labels: "Onboarding-ops" and "Receiver" and state label 
     - [X] Epics: #7804

**Comment by GilmoreA6** [comment]
Waiting result of test data to finalize settings
