### ISSUE TITLE
Determine Value Sets Warning and Confirmation dialogue content per O+O feedback

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#7903]
## Problem statement
The feedback from O+O team regarding an update to the Value Sets UI has not been implemented. First, a new design for the changes needs to be proposed before engineering can begin work.

## What you need to know

- Current location of value sets: https://reportstream.cdc.gov/admin/value-sets
- Feedback from O+O can be found in #6787

## Acceptance criteria

- [ ] TBD

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/7903?planning-poker) with Zenhub @etanb @jpandersen87 @kevinhaube @penny-lischer @stephenkao

**Comment by kevinhaube** [comment]
Sounds like a solid 3 at least! ☺️

**Comment by chris-kuryak** [comment]
Internal facing, not needed at this time. Engineers can determine what warning and confirmation dialogue boxes should say.
