### ISSUE TITLE
MessageID API minimizes use of COVID result metadata table

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#7911]
## Problem statement

Currently the message API interacts with the `covid_result_metadata` db table but it should use `elr_result_metadata` instead since this API should not be specific to any topic. 

## What you need to know

This ticket has a sister ticket [7892](https://github.com/CDCgov/prime-reportstream/issues/7892) for implementing a NEW message API specifically for COVID data. They are not dependent on one another.

TODO: We may need to use item lineage table instead of ELR. Investigate this.

## Acceptance criteria

- [ ] Refactor the current message endpoints to read from ITEM LINEAGE table instead of COVID table

**Comment by jimduff-usds** [comment]
My thinking on this has changed.  See #8031, #8032, #8033.

Basically, I think we need to go ahead and create an ITEM table.
