### ISSUE TITLE
Login persists on tab close

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7916]
## Describe the bug
When logged into RS, closing the tab does not end a user's logged in session as expected. Navigating back to the RS site will show you're still logged in.

## Impact on ReportStream
Security implications.

## Steps to reproduce
1. Go to RS website
2. Log in
3. Close any/all RS tabs
4. Open a new tab and go to RS website
5. Observe logged in state

## Expected behavior
When the last tab opened to RS is closed, a user is logged out and required to log back in.

## Acceptance Criteria
- [ ] When the last tab opened to RS is closed, a user is logged out and required to log back in.
- [ ] Add maximum time to keep in local storage (1 hour)
- [ ] When last tab is closed, make delete request to Okta to clear the session
- [ ] Write ticket to create Cypress test

## Resources
Likely related to #7727

## Logs
If applicable, please attach logs to help describe your problem.

## Additional context
Add any other historical context about the problem here.

## To Do
- [ ] What is the existing lifetime of Okta token?

**Comment by chris-kuryak** [comment]
@etanb 
Will @jpandersen87 upgrade of Okta to 7.2 fix this bug? #8012

**Comment by jpandersen87** [comment]
It will not. I have concerns on our ability to reliably do something like this with how the lifecycle of a page (or tab) works in modern browsers.

**Comment by chris-kuryak** [comment]
After investigation with the WebEx experience team and DevOps, this does not appear to be an issue with our existing setup and aligns with the guidelines provided by DevOps in SSP (Security document).

SSP AC-11: Components that reside on the internal CDC network and have joined the CDC domain, a group policy exists that will lock the session after 15 minutes.

**Comment by chris-kuryak** [comment]
Closing per above comment
