### ISSUE TITLE
Finalize designs of STLT Data Dashboard / Facility Submission Stats MVP

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#7919]
## Problem statement

STLTs have shown interest in viewing their data from the perspective of "who is reporting and how often". It is believed that this will encourage them to use the site more regularly and increase the value they see in this product. This will also be used to facilitate future research with STLTs regarding a "STLT Dashboard."

## What you need to know

- [Figma Prototype](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=2369%3A26965&scaling=min-zoom&page-id=2369%3A26962&starting-point-node-id=2369%3A26965)

Previous research issues:
- #7437
- #7438

## Acceptance criteria

- [x] Final designs
- [x] Location of the page(s)
- [x] Review briefly with O+O to get feedback on any tweaks
- [x] Update the Epic #7005 with latest designs and Acceptance Criteria, then communicate to Experience engineers

## Review Requirements
- None

**Comment by jillian-hammer** [comment]
Design finalized, see the [Figma Prototype](#8136) for the mockup. Link updated in epic #7005.

Closing this issue.
