### ISSUE TITLE
VT HL7 message failures

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#7922]
![VT failures.PNG](https://images.zenhubusercontent.com/628286bc0129e14bd536e6f9/b928f814-2dd0-488e-b52c-e8baaee66870)

Helpdesk has reviewed HL7 file from CDC Prime all patient info appears in code. However user is receiving "PATIENT_RESULT[0].PATIENT.PID.PatientAddress[0].StateOrProvince" Description="Field value not found in validation table"/>" Error on the attached messages.

Andrew Gross, ahs.vdhelrsupport@vermont.gov

**Comment by brick-green** [comment]
These were received from simple report with the patient state = "NA". They were routed to VT based on the ordering facility state which was sent as VT. 

@TaneaY @sliu1000 Can you work with SimpleReport to find out how "NA" could be sent in the patient state field?

**Comment by sliu1000** [comment]
@TaneaY , Please create a SimpleReport Escalation ticket .

**Comment by TaneaY** [comment]
Escalated to SimpleReport engineering. Awaiting response

**Comment by TaneaY** [comment]
SimpleReport engineering responded : "After further investigation the reason why patients states would be NA is when their state is not USA.

Specifically in this case, the patient's countries are TON."

**Comment by brick-green** [comment]
Next step is to convey that information from SimpleReport to VT and ask them to propose a solution for these messages and similar messages that may arrive in the future with foreign patient addresses.

**Comment by TaneaY** [comment]
Message sent to submitter for proposed solution:

Hi Andrew,

After further investigation SimpleReport team was able to provide the reason why patients states would be NA is when their state is not in the USA.

Specifically in this case, the patient's countries are TON.

How would you like these these messages and similar messages that may arrive in the future with foreign patient addresses to be processed?

Thank you,

Tanea

**Comment by sliu1000** [comment]
@TaneaY If the state is NA how is that data being routed to VT? is it based on some other state?

**Comment by TaneaY** [comment]
Hi Sharon,

When Brick investigated he discovered that they were routed to VT based on the ordering facility state which was sent as VT from SR. Then, I escalated to SR engineers to find out why and they responded that it was because they were out of the country patient addresses. So far, VT has not responded as to how they would like future results like this filtered.

Thank you,


Tanea

The SimpleReport Support Team

Contact us at ***@***.***

Support hours:  8:00 am through 9:00 pm Eastern time

Monday-Friday, excluding US public holidays

________________________________

**Comment by sliu1000** [comment]
@TaneaY I believe Vermont stated that they wanted to just leave that state field blank. But not sure if that's a required field for SimpleReport?

**Comment by sliu1000** [comment]
Hi Tanea,

ReportStream can filter out states with "NA", the question is if VT wants to receive international patient test results. We may need to find out if they do or do not.

**Comment by TaneaY** [comment]
Hi Sharon,

I see, apologies for the confusion. I have emailed VT to confirm if they would like to receive the international test results going forward.

Thank you,


Tanea

The SimpleReport Support Team

Contact us at ***@***.***

Support hours:  8:00 am through 9:00 pm Eastern time

Monday-Friday, excluding US public holidays

________________________________

**Comment by LaFreda1** [comment]
@TaneaY any update from VT?

**Comment by TaneaY** [comment]
No reply to the 1/30 follow-up to confirm if they want to filter the results from patients with addresses outside of the USA. Request for information resent 2/9.
________________________________

**Comment by sliu1000** [comment]
Update from Sender:

Thank you for your assistance with this. Below is what I believe we would like our filter criteria to be, can you let me know if that is something that could be done?

Filter out OTC antigen covid results, excluding employee testing.

Thanks,

Andrew Gross, MPH | Health Data Administrator
Division of Health Statistics & Informatics
Vermont Department of Health
108 Cherry St, Burlington, VT 05402

**Comment by Jcavallo7** [comment]
*update from user*

Hi Juan,

 

Thank you for that info! I had recently inquired with ReportStream about filtering out at-home test results, as VDH no longer requires those results – I wonder if that filter has been implemented (though that hasn’t been confirmed with me)? If so, that might be the reason for the error?

 

Thanks,

**Comment by LaFreda1** [comment]
@brick-green any updates on the filter? Has it been implemented?

**Comment by sliu1000** [comment]
linked to ticket # 7677

**Comment by brick-green** [comment]
@LaFreda1 We can filter out Antigen results. But we do not have a way to distinguish employee testing. So we can't create the filter how VT is asking. We need to ask VT if they want to filter out all antigen results if there is another approach for filtering.

**Comment by TaneaY** [comment]
Follow-up to user sent.
Hello Andrew,

We received an update on your filter request. We can filter out Antigen results, but we do not have a way to distinguish employee testing. 

Please advise if you want to filter out all antigen results or if there is another approach you would like to try.

Thank you,

Tanea
