### ISSUE TITLE
SonarCloud rules should mirror our lint/prettier rules

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#7924]
**Is your feature request related to a problem? Please describe.**

We sometimes run into code smells and quality degradation reports from SonarCloud that don't match up with our ESLint/prettier rules.

See [this discussion](https://github.com/CDCgov/prime-reportstream/pull/7883#issuecomment-1374998121) as an example.

**Describe the solution you'd like**
SonarCloud's quality checks should mirror our ESLint and Prettier rules exactly.

**Comment by stephenkao** [comment]
cc @jpandersen87!

**Comment by jpandersen87** [comment]
SonarCloud has an eslint plugin (https://github.com/SonarSource/eslint-plugin-sonarjs) but the description seems to indicate that it is not fully representative of what the service lints for. They prefer you use an IDE-specific extension (https://www.sonarsource.com/products/sonarlint/) to get a matching linting experience. Annoyingly, that would mean that it's no possible to reproduce SonarCloud linting as part of our pre-commit lifecycle to enforce linting.

**Comment by chris-kuryak** [comment]
@penny-lischer @etanb @jpandersen87 @stephenkao 
Ensure that you have installed the IDE-specific Extension:(https://www.sonarsource.com/products/sonarlint/) 

Closing based on engineering consensus.
