### ISSUE TITLE
[SPIKE] Consider ejection from CRA

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#7943]
**Is your feature request related to a problem? Please describe.**
We used [Create React App](https://create-react-app.dev/) to spin up the ReportStream website initially, but we've run into some obstacles due to the fact that it intentionally lacks build configuration options.

**Describe the solution you'd like**
We should use this ticket to keep track of a non-exhaustive list of pros/cons for sticking with CRA, and we can reassess in the future on whether or not to eject from CRA.

CRA pros:
- Opinionated configuration*
- No Webpack maintenance needed
- Externally maintained dependency updates

CRA cons:
- Opinionated configuration*
- No build configuration options for Webpack

Discussed limitations of CRA:
- No support for TypeScript path aliasing
- Can't add or extend Webpack configuration/plugins

**Describe alternatives you've considered**
- We can continue to work within the bounds of CRA configuration and punt on proposals for new features.  We can continue to raise ejection as a discussion point in the future.

**Additional context**
- In ideating on a v2 of the ReportStream website, it's also been proposed that we move to a Next.js project -- likely [Nava's template](https://github.com/navapbc/template-application-nextjs).  While this ticket isn't entirely contingent on whatever comes out of that decision (if any), it's something we should keep in mind when discussing long-term maintenance of our current configuration.

cc @jpandersen87 @kevinhaube

**Comment by jpandersen87** [comment]
CRA currently has issues with having active maintainers: https://github.com/facebook/create-react-app/discussions/11768

**Comment by jpandersen87** [comment]
Alternatives: 

- Eject from CRA (builder: Webpack)
- Vite 2.0 (builder: esbuild)
- Rollup
  - Does not support Hot Module Replacement for dev server
- Parcel
- (FUTURE OPTION) Turbopack
  - Successor to Webpack
  - If we decide to migrate to Next.js in the future, this would be our bundler

**Comment by jpandersen87** [comment]
We should figure out in a post-eject world if we even need babel transformations, or if we could rely entirely on typescript's output (instead of right now, where we transpile through babel and use typescript only for type checking).

**Comment by jpandersen87** [comment]
Have spoken to @stephenkao about this and we agree the best immediate path forward is to move away from CRA, while still using the same bundler (Webpack 5). We want a 1:1 experience on our project to using CRA, just with the freedom to update our webpack config as necessary (especially during these dev-hostile times of libraries hard-switching to ESM with no CJS support).
