### ISSUE TITLE
Create Content for the Validation Tool

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#7944]
## Problem statement

The current Validation tool needs new content and content edits for public release, as well as error messages that are not aligned with the most recent API Error codes. The purpose of error messages is to provide users of the Validation tool what went wrong and how they can fix their issues. This is important for the shift to making the Validation tool public.

## What you need to know

Error Codes = the codes returned by the API that can be used to figure out what went wrong
Error Message = the human readable message that the front-end returns 

- #7523
- [Error Code Documentation](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/proposals/0017-serializer-error-codes.md)

## Acceptance criteria

- [x] Content added/edited for each tool page and shared with Jillian for final design.
- [x] New error messages created and documented
- [x] Update issue #7945 with the new error messages for engineers to implement

## To do

- [x] Watch HL7[ intro video ](https://nava.slack.com/archives/C024MGSJZ38/p1659722811223229)

- [x] Prep for convo and share async with design/product to fill in gaps we can

- [X] Meet with an experience engineer and an O+O engineer (if possible) to craft new error messages (James)

**Comment by audreykwr** [comment]
@chris-kuryak closing!
