### ISSUE TITLE
Update the API Error Messages on the Validation Tool

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#7945]
## Problem statement

The current Validation tool has error messages that are not aligned with the most recent API Error codes. The purpose of error messages is to provide users of the Validation tool what went wrong and how they can fix their issues. This is important for the shift to making the Validation tool public.

## What you need to know

 This work is dependent on the design team creating/finalizing the error messages.

- #7523
- [Error Code Documentation](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/proposals/0017-serializer-error-codes.md)

## Acceptance criteria

- [x] API Error Messages are shown to user
- [x] API Error Messages align with design team's output from #7944 -- included in comment below
- [x] Create tests

**Comment by audreykwr** [comment]
The new messages are [here in the new message sheet under column J](https://docs.google.com/spreadsheets/d/1uY-yVnOfKLhVJYN6gf8OJpEgu3dKRKKp/edit?usp=sharing&ouid=105539281535064771922&rtpof=true&sd=true). Let me know if there are any questions!

**Comment by penny-lischer** [comment]
Updated .xls with error code mapping.
[https://app.zenhub.com/files/304423150/a0319a2a-f5c7-4e5d-8cf0-f820f8e4eb14/download](https://app.zenhub.com/files/304423150/a0319a2a-f5c7-4e5d-8cf0-f820f8e4eb14/download)
