### ISSUE TITLE
Update the validate API call from the Validation Tool

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#7948]
## Problem statement
Given that the validation tool will allow users to select between schemas and Sender settings, we need to update our front-end call to the validate function to include their choice.

## What you need to know
- The validation API endpoint [is going to be updated](https://app.zenhub.com/workspaces/platform-638a6fe2aacec620dafdac38/issues/gh/cdcgov/prime-reportstream/7927) to accept either 1) one of the three master schemas (HL7, CSV, CSV OTC) or 2) a Sender setting.  
- useWatersUploader already factors in a [client header](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/hooks/network/WatersHooks.ts#L39) for the Organization name.  This will be updated on the backend to allow for a chosen schema as well.

## Acceptance criteria
- [ ] [useWatersUploader](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/hooks/network/WatersHooks.ts#L19) for `validate` should be updated to pass the chosen schema or Sender settings as part of the header, which will be informed by [7773](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/7773)

**Comment by chris-kuryak** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/7948?planning-poker) with Zenhub @jpandersen87 @kevinhaube @penny-lischer @etanb @stephenkao

**Comment by chris-kuryak** [comment]
@etanb The overwhelming majority here was a 2-pointer, so I'm gonna choose that for now. Comment here if you have a strong disagreement/case you'd like to make otherwise.

**Comment by stephenkao** [comment]
Closing since this was handled as part of [8201](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/8201)
