### ISSUE TITLE
MO DHSS Production Validation Errors

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#7954]
Jake Muehlhausen, jake.muehlhausen@oa.mo.gov:
We received a couple messages in our production path showing validation errors. 

Filename:  covid-19-dae196d7-2f3b-4b79-9f1e-c0cec4c07c91-20230113002018

MSH-10:  D-8115369491202301130011949967, D-7613707749202301130011476727, D-7217245302202301130011013263, D-2687064168202301130011510868, D-5782820541202301130011033013, D-5632828421202301130011601564, D-3473050973202301130011098948

 

Filename:  covid-19-2a739114-199e-4334-acb6-72fbb59f5ae2-20230113142047

MSH-10:  D-4843509193202301131411999302

 

PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.PlacerGroupNumber.EntityIdentifier" Description="Required field missing

PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.OrderingProvider[0].AssigningAuthority.UniversalID" Description="Required field missing

PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.OrderingProvider[0].AssigningAuthority.UniversalIDType" Description="Required field missing

PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBR.OrderingProvider[0].AssigningAuthority.UniversalID" Description="Required field missing

PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBR.OrderingProvider[0].AssigningAuthority.UniversalIDType" Description="Required field missing

**Comment by Jcavallo7** [comment]
user update:

"Thank you, all!

 

We received 3 additional messages this afternoon, within filename covid-19-0553ae07-bb7e-4fba-8501-73b2eb0457a6-20230113222054, showing this same error.  Have a great weekend!

 

Jake"

**Comment by oslynn** [comment]
**HL7 Definition:**

PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.PlacerGroupNumber.EntityIdentifier" Description="Required field missing
Ref: https://hl7-definition.caristix.com/v2/HL7v2.5.1/Fields/ORC.4.1

PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.OrderingProvider[0].AssigningAuthority.UniversalID" Description="Required field missing
Ref: https://hl7-definition.caristix.com/v2/HL7v2.5.1/Fields/ORC.12.9.2

PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.OrderingProvider[0].AssigningAuthority.UniversalIDType" Description="Required field missing
Ref:  https://hl7-definition.caristix.com/v2/HL7v2.5.1/Fields/ORC.12.9.3

PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBR.OrderingProvider[0].AssigningAuthority.UniversalID" Description="Required field missing
Ref:  https://hl7-definition.caristix.com/v2/HL7v2.5.1/Fields/OBR.16.9.2

PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBR.OrderingProvider[0].AssigningAuthority.UniversalIDType" Description="Required field missing
Ref: https://hl7-definition.caristix.com/v2/HL7v2.5.1/Fields/OBR.16.9.3

**Comment by oslynn** [comment]
Message files:
From: 
   color lab:  junk\MO\ticket7954\color-lab\hl7-ingest-covid-19-prod-c5c970f0-d510-4960-a1d3-8f2ca49b4b1a-20230113001106.internal.csv
To:
  MO: junk\MO\ticket7954\color-lab\covid-19-dae196d7-2f3b-4b79-9f1e-c0cec4c07c91-20230113002018.hl7
