### ISSUE TITLE
Conduct secondary research to answer questions about clarity and usability

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#7982]
**Background and context**
We have various documents with feedback from senders that we can use as we update the API programmer's guide. 

**Open Questions**

- What themes do we see in our conversations with senders?

**Working Links**

1. [Mural](https://app.mural.co/t/nava4113/m/nava4113/1672245855117/9c84f3ad3a2b9d0bb28654949ce7622eede8378d?sender=u791b7d4d34761ac59b672214) that synthesizes recent sender conversations (links out to source materials 
3. Document with sender notes downloaded from Share point (see attachment)

**Acceptance Criteria**

- [x] Ask teammates if we are missing any key materials 

- [x] Review existing materials and pull out common themes: questions, assumptions, areas we can clarify further

- [x] Use this information to inform priority of content in working session with O&O engineers and customer support

**Comment by lizzieamanning** [comment]
[https://app.zenhub.com/files/304423150/38c0068a-9512-4a9b-a0f1-53840d4e6991/download](https://app.zenhub.com/files/304423150/38c0068a-9512-4a9b-a0f1-53840d4e6991/download)

**Comment by lizzieamanning** [comment]
[https://app.zenhub.com/files/304423150/94a0f8d1-5518-497d-bf4b-04cb3437d530/download](https://app.zenhub.com/files/304423150/94a0f8d1-5518-497d-bf4b-04cb3437d530/download)

**Comment by audreykwr** [comment]
[Working doc](https://docs.google.com/document/d/1S4SlRp5nznuymnCr1nOwhQYDKYt2OqTX/edit?usp=sharing&ouid=105539281535064771922&rtpof=true&sd=true) for API guide that contains edits, questions, and what to walk through during a working session.
