### ISSUE TITLE
Provide memberType boolean checks from SessionProvider

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7987]
## Problem statement

We use the check `if (activeMembership.memberType === "...") { ... }` in numerous places within the React app. **To consolidate the logic, we can provide booleans from the session level that do this check for us**, and use those in places we need to check member types, such as `AuthElement`. 

## What you need to know

Stems from this discussion: https://github.com/CDCgov/prime-reportstream/pull/7923#discussion_r1069614277

## Acceptance criteria

- [ ] SessionProvider can be utilized to retrieve boolean checks for member types
- [ ] Provided booleans are used in place of current conditionals within our React app

## To do

- [ ] ...

**Comment by jpandersen87** [comment]
Going to piggyback off the work being done in #7923 for this.
