### ISSUE TITLE
Add timeZone and dateTimeFormat fields to Receiver Settings

### ISSUE THREAD

**Issue by adegolier** [CDCgov/prime-reportstream#7994]
## Problem statement

Currently cannot update these fields (timeZone and dateTimeFormat) through the ReportStream Settings UI.

## What you need to know

- Example URL from Staging: https://staging.reportstream.cdc.gov/admin/orgreceiversettings/org/md-phd/receiver/elr-secondary/action/edit
- timeZone options: [ARIZONA, SAMOA, HAWAII, EASTERN, CENTRAL, EAST_INDIANA, PACIFIC, MICHIGAN, MOUNTAIN, CHAMORRO, UTC, INDIANA_STARKE]
- dateTimeFormat options: [HIGH_PRECISION_OFFSET, LOCAL, DATE_ONLY, OFFSET]
- See screenshot from organizations.yml with desired fields highlighted.

![image.png](https://images.zenhubusercontent.com/63bed644ef19cf422cdec9ca/dffb7cbb-8d0a-48d1-b690-3ec5d60345ed)

## Acceptance criteria

- [ ] timeZone field is editable from ReportStream Settings UI (possible dropdown?)
- [ ] dateTimeFormat field is editable from ReportStreamSettings UI (possible dropdown?)

**Comment by chris-kuryak** [comment]
@adegolier Few quick questions to confirm:

1. When you say the ReportStream Settings UI, which page are you referring to? (provide example URL)
2. What are the possible choices for timeZone that need to be provided?
3. What are the possible choices for dateTimeFormat that need to be provided?

**Comment by adegolier** [comment]
@chris-kuryak Updated the ticket!

**Comment by chris-kuryak** [comment]
@adegolier Thank you!
