### ISSUE TITLE
Add front-end support saving and reading feature flags

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8005]
## Problem statement

Feature flags v2 involves moving enabled flags to an Organization level, so we no longer need to maintain that in LocalStorage.

## What you need to know

- [Feature flag v2 pull request](https://github.com/CDCgov/prime-reportstream/commit/9ad6d6682631f619c154e500d7272ffc0c96b3d0)

## Acceptance criteria

- [ ] Add a `useIsFeatureEnabled` hook to determine if the current Organization has a feature enabled based on settings
- [ ] Feature flag v1 UI and logic is removed
- [ ] Organization settings page has a JSON textarea to specifically update `featureFlags` (optional, can get by without it)

**Comment by stephenkao** [comment]
@chris-kuryak We can have a longer discussion about this, I'm wondering if we really need to support feature flags in the future.  It doesn't make sense to me to show a specific set of UX features to certain Organizations other than the normal Sender/Receiver user journeys.  With feature flags, we'd have the capability of showing, say, the validator feature to Abbott but not SimpleReport.  This is a farfetched example, but if we're trying to make the ReportStream website universally usable to our users, feature flags feel antithetical to that.

Thoughts?

**Comment by chris-kuryak** [comment]
@stephenkao Yes, I don't have any great examples with what's on our roadmap regarding features we'd only want to show to limited users. I can only see the case where we'd want to have a "limited release" of a feature to a certain sub-group of users to test it out before a full release.
I think we should bring this up to all teams in our sync to see if we are missing any historical context/obvious. How do you feel about that?

**Comment by stephenkao** [comment]
Ah, sorry -- I forgot to follow up on this ticket @chris-kuryak!

I asked about historical context in the sync this week, and the short of it was that we didn't have a good use case for Organization-specific feature flags, so my feeling is that we can close this ticket and revisit if we ever need to handle the aforementioned "limited release" logic.  

Another topic that comes to mind is a/b testing, but I think we're a looooooong ways away from even thinking about that at this point given the fact that we won't be able to get any statistically significant values from our very limited set of real users.  If/when we do want to broach a/b testing, we should consider investing in a more fully fleshed out solution so we can automatically group users into cohorts and potentially run blind/double-blind experiments against them.

In any case, I don't think we need to take any further action with feature flags as they are now so I'm in favor of closing this ticket.  Thoughts?

**Comment by chris-kuryak** [comment]
Agreed @stephenkao
