### ISSUE TITLE
CA CDPH - Need MSH-4 CLIA number Updated from CDPH000087 to CDPH000085

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#8009]
## Problem statement
CAL State user Vanessa is requesting MSH-4 to be updated for facility Specialty Diagnostics Inc. 05D0642622

CDPH has a list of specific senders that should have an MSH-4 of CDPH000085 NOT CDPH000087.  Can we hard code this update? 

## What you need to know

Please see some example files:

ReportID:  `73295065-fd4b-4db1-b6c6-996377ee7ea7`
Date 1/12/2023 at 3:30 

## Acceptance criteria

- All data from facility listed above should have the MSH-4 showing as CDPH000085

## To do

- Assign to an Engineer

**Comment by Jcavallo7** [comment]
update from user: 

Accession            MSH-4                  Submitter                            Message TimeStamp

TFHR-NQVV       CDPH000087       Specialty Diagnostic        2023-01-18 00:30:00

SPMQ-CETH       CDPH000087       Specialty Diagnostic        2023-01-18 00:30:00

WMAN-VSHU    CDPH000087       Specialty Diagnostic        2023-01-18 00:30:00

GMCS-CKUC       CDPH000087       Specialty Diagnostic        2023-01-18 00:30:00

PESU-CUQR        CDPH000087       Specialty Diagnostic        2023-01-18 00:30:00

**Comment by adegolier** [comment]
Updated the settings in all three of their feeds. @sliu1000 can we get confirmation that it's good?

**Comment by sliu1000** [comment]
@adegolier I just got a message from Vanessa from California.  She said that they are not seeing the change:

Communication below:
I will check again tomorrow but as of 1/25 seeing some of their results reported under the CDPH000087 MSH-4, thanks.

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/f4c82a8b-fb40-4409-839f-65d7a7edb7b8)

**Comment by adegolier** [comment]
I double checked and they should be updated. Hopefully that was one last batch that slipped in under the old number.

**Comment by adegolier** [comment]
@sliu1000 Can we confirm whether the 25th was just the last one slipping in under the wire and if it's fixed now?

**Comment by sliu1000** [comment]
CA confirmed this has been resolved.
