### ISSUE TITLE
Provenance Endpoint resource is missing required properties

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#8023]
### User Story:
As receiver, I want to FHIR data that is correct and complete, so I can validate it against a profile.

### Description/Use Case
The routing step of the UP adds Endpoint resources to the Provenance resource to list the receivers the data will be sent to.  This Endpoint is missing required properties per the FHIR spec.

### Dev Notes:
* See https://hl7.org/fhir/endpoint.html#resource
* You will need to figure out what data to place on these fields. Some of it may come from the receiver settings.
* You will need to update code in the Routing step, not config

### Acceptance Criteria
* The UP routing step creates Endpoint resources that includes all required properties specified in the FHIR spec.

**Comment by avnieldravid** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8023?planning-poker) with Zenhub @carlosfelix2 @PatriciaPerozoUSDS @jack-h-wang @victor-chaparro @JessicaWNava @thetaurean

**Comment by avnieldravid** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8023?planning-poker) with Zenhub @arnejduranovic

**Comment by jack-h-wang** [comment]
This may no longer be applicable based on the outcome of #11051

**Comment by jack-h-wang** [comment]
Closed in favor of #12268.
