### ISSUE TITLE
Use widescreen grid for data-heavy pages

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8026]
## Problem statement

At the moment our maximum container width on desktop viewports is 1024px.  However, since so many of our views will contain tabular data, we'd like to introduce a wider container so we can display more data at any given time.

## Acceptance criteria
- [ ] The message tracker page uses the widescreen container
- [ ] The daily data page uses the widescreen container
- [ ] The submissions page uses the widescreen container

**Comment by stephenkao** [comment]
@jillian-hammer We also chatted about updating the grid + gutters, but I think we could break that out into a separate ticket and just keep this about widening the container overall. 
 What are your thoughts about this?

**Comment by jillian-hammer** [comment]
Confirming 1440px as the container width! 

And yes, OK with separating the grid layout as a separate issue. I'm sure playing around with the 1440px demo will help inform the ultimate grid, so that totally makes sense. Thank you!

**Comment by jillian-hammer** [comment]
@stephenkao I reviewed this on demo3 and all three pages look great! Thank you so much!

**Comment by stephenkao** [comment]
Thank you for reviewing, @jillian-hammer!!!!
