### ISSUE TITLE
Create an ITEM table, in support of the messageID API

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#8032]
### Problem

Currently we do not have any table in the system that has one row per submitted ITEM.   The closest we have is ITEM_LINEAGE.  It has these flaws:

- Data is only inserted into ITEM_LINEAGE if there is both a parent and a child report.   So ITEMS that get completely filtered out never appear in ITEM_LINEAGE and so are not well tracked in our system.  (They do appear in COVID_RESULT_METADATA, which is one reason why the messageID query is using that table)
- As we add more datatypes (eg, full_elr, covid, etc), we need a table per item that knows nothing about what datatype it is.  This is the ITEM table.
- Then all the datatype specific metadata tables can simply FK to the ITEM table.

### Acceptance Criteria

- [x]  The new ITEM table is nicely designed 
- [x] ITEM TABLE COLUMNS: item_id, report_id, created_at
- [x] ITEM_LINEAGE, COVID_RESULT_METADATA, and ELR_RESULT_METADATA all FK to ITEM. All these tables need an ITEM_ID column added to them (FK)
- [x] ITEM FKs to REPORT_FILE.
- [ ] All descendant ITEM_LINEAGE entries (not just for the initially received report, but also for the routed, batched, and sent reports) have the proper FK back to the original ITEM_ID) - This will be a part of #8147
- [x] No backfill of old items; that can be a separate ticket, or we can choose not to do it.
- [x] No changes to messageID api (yet) - separate ticket.

### Notes

See #8031 for more background on this need.
See #8147 for populating the data
See also #8033 for the follow-on work to change the messageID queries to use this.

**Comment by arnejduranovic** [comment]
The Universal Pipeline already treats the item lineage table as an "item" table and there is no immediate need for an item table in the old pipeline, since message tracker already works for covid via the covid metadata table, and that is essentially all the old pipeline is and will be used for.

Will potentially revisit/rethink this when working on universal search engine.
