### ISSUE TITLE
HI Onboarding - Set Up Connection

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#8040]
### Acceptance Criteria 

CONNECTION TYPE:
If SFTP:
- [x] 1. Submitted host name for CDC whitelisting
- [x] 2. Retrieve username and PW from STLT 
- [x] 3. Determine if they have public key authentication 
- [x] 4. Add private info to Keybase 
- [x] 5. Create Azure secret staging 
- [x] 6. Create Azure secret production 
- [x] 7. Test connection

If REST:
- [ ] 1. Submit host name for CDC whitelisting 
- [ ] 2. Retrieve username and PW from STLT 
- [ ] 3. Create private and public key 
- [ ] 4. Send public key to STLT 
- [ ] 5. Build REST transport [we can flesh out further if needed, could be another epic] 
- [ ] 6. Add private info to Keybase 
- [ ] 7. Create Azure secret staging 
- [ ] 8. Create Azure secret production 
- [ ] 9. Test connection 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with receiver

**Comment by GilmoreA6** [comment]
sftp information from hawaii: 

Ip Address:  162.221.245.152
Port Open:  22

Username/Password combo received and stored in keybase under appropriate STLT folder

**Comment by GilmoreA6** [comment]
Whitelist request to devops for IP:

**Comment by GilmoreA6** [comment]
ip has been whitelisted and test messages has been received by HAWAII DOH
