### ISSUE TITLE
HI Onboarding - Validate Test Data

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#8042]
### Acceptance Criteria 
- [x] Created and sent data using fake data generator 
- [x] Created and sent data using synthesized data generator 
- [ ] Confirmed with STLT that data passes validation 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with receiver

**Comment by GilmoreA6** [comment]
Waiting for STLT to validate test data sent to staging environment. Test Plan attatced to ticket.

**Comment by GilmoreA6** [comment]
[HI Test Cases.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1ZCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10bcda8c47022902164ca716091b0975fc827ef2/HI%20Test%20Cases.xlsx)

**Comment by GilmoreA6** [comment]
approved to move to testing prod data
