### ISSUE TITLE
VT - ELR Senders and Facilities

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#8054]
## Problem statement

Andrew Gross (andrew.gross@vermont.gov)

User ask:

"We are hoping to compile a list of facilities actively sending ELRs via ReportStream to VDH. Further, if possible, we would like to know the facilities that are utilizing SimpleReport to get their results in to Report Stream. Please let us know if such lists are something that could be provided! Thanks!"

**Comment by brandonnava** [comment]
@Jcavallo7 To clarify, is this a request from Vermont to know who their senders are?

**Comment by Jcavallo7** [comment]
Yes. @brandonnava

**Comment by Jcavallo7** [comment]
sent out list of facilities to user
