### ISSUE TITLE
SimpleHealthKit Onboarding – Testing in Staging and Prod

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#8063]
### Acceptance Criteria 
- [x] Sender has tested in staging and production 
- [x] RS engineer has determined the data is good enough and graduates Sender to send Prod data to receiver  

### To Do 
- [x] RS engineer: update this ticket with comments with every interaction with sender 
- [x] RS team member who originates this ticket: add dependencies:  
     - [x] [name of company] Onboarding – Create Org and Sender Settings
     - [x] [name of company] Onboarding - Validate Test Files 
- [x] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [x] Pipelines: Onboarding & Operations (New) 
     - [x] Labels: "Onboarding-ops," "Sender"
     - [x] Epics: [select the epic for this API onboarding sender]

**Comment by GilmoreA6** [comment]
Public Keys received. Waiting for staging environment to be available to upload.

**Comment by sliu1000** [comment]
update from sender:

Hello James,

I am in the process of sending data to staging following the Programmers guide. What is Simple HealthKit's client ID? I do not know if that was ever given to us after searching through some of our emails. That would be greatly appreciated.
If possible, could we also schedule a tentative meeting this upcoming week just to make sure that we are connected properly and securely?

Best,
Abdul Ahmed @ Simple HealthKit

**Comment by sliu1000** [comment]
Update:

Hi Abdul,

I've sent an invite, feel free to forward to whomever on your side should be included.

Thanks,

James

James Gilmore (Agile Six)

Subject: Re: ReportStream - simplehealthkit validation
 
Hello James,

Thanks so much for the client id. I will use this to get the bearer token. Can we schedule a call on Thursday 2/2 at 9am PST to 10am PST?

Best,
Abdul @ Simple HealthKit

On Mon, Jan 30, 2023 at 11:41 AM Gilmore, James (CDC/DDPHSS/OD/HITSSU) <uaf6@cdc.gov> wrote:
Hi Abdul,

Your client id is "simplehealthkit" so an example command to get a bearer token would be:

curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "scope=simplehealthkit.*.report&grant_type=client_credentials&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&client_assertion=<token-signing-secret>" "https://staging.prime.cdc.gov/api/token" 

We can schedule a meeting later this week if that works for you. I have availability on Thursday 2/2 from 8:30-10:00 AM PST and Friday anytime between 8AM-5PM PST except for between 11-11:30.

Thanks,

James


James Gilmore (Agile Six)
Senior HL7 Data Analyst
Pandemic-Ready Interoperability Modernization Effort (PRIME)

**Comment by GilmoreA6** [comment]
Hello James,

Thanks so much for the client id. I will use this to get the bearer token. Can we schedule a call on Thursday 2/2 at 9am PST to 10am PST?

Best,
Abdul @ Simple HealthKit

**Comment by GilmoreA6** [comment]
Hi Abdul,

I've sent an invite, feel free to forward to whomever on your side should be included.

Thanks,

James

**Comment by sliu1000** [comment]
Hi Abdul,

The files look good so we can move on to testing in Prod. Please send a few real patient examples to our production endpoint that we can use to validate. Please ensure that you do not send any real patient data to the staging environment. We will forward the examples on to the relevant public health jurisdictions for approval and once we receive that can move you to full production.

To get the detailed submission history send a GET request to https://staging.prime.cdc.gov/api/waters/report/{id}/history where {id} is either the submission id or UUID returned in the JSON response to your POST. For production you would send to https://prime.cdc.gov/api/waters/report/{id}/history.  in the request you client id and bearer token as you would in a POST submission.

Let me know if you have trouble getting the submission history to return.

Thanks,

James

James Gilmore (Agile Six)
Senior HL7 Data Analyst
Pandemic-Ready Interoperability Modernization Effort (PRIME)

**Comment by sliu1000** [comment]
Update from Sender:

Hello James,

I was having some trouble using my script to send data to production. I think my production URLs may be incorrect since my staging configuration is giving me a 200 response. I am using my production .pem file for this script.

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/5128c991-6702-4411-8316-daf98485f5e2)

Best,
Abdul Ahmed @ Simple HealthKit

**Comment by GilmoreA6** [comment]
Good Afternoon,

ReportStream has a new sender that would like to send to California.

SimpleHealth Kit - CLIA 5D2201580

They are sending CSV to ReportStream so I have used CLIA CDPH000085. I have sent some messages for validation to the test environment at saphiresftpstage.cdph.ca.gov

The filename is:

covid-19-4a441115-d85e-4d56-a9cb-e6d64597409a-20230208150740.hl7

The message id's are:

397403+1+20230208
397404+2+20230208
397405+3+20230208
397406+4+20230208
397407+5+20230208

Please let me know if there are any changes that need to be made and I will work with the sender.

Thanks,

James

**Comment by GilmoreA6** [comment]
CA has validated the messages andsimplehealthkit is now in full production mode.
