### ISSUE TITLE
UP Translation step generates a filtered FHIR bundle with only the resources needed by a receiver

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#8098]
### User Story:
As an receiver, I want to be able to receive only the data that I need, so I don't have to filter the data when I get it.

### Description/Use Case
Receivers are going to want to determine which reportable conditions they want to receive from ReportStream as we start ingesting all reportable conditions. We need a mechanism to filter out reportable conditions they want.

### Dev Notes:
* See design in #7588
* This is to be done in the translation step. Use the data placed in the FHIR Bundle from #8095 to know which Observation resources to keep and generate a new FHIR Bundle with the rest removed.
* Use the code generated from #8096 to remove the resources.
* This new FHIR bundle is then translated as needed and sent to the receiver.
* The original FHIR Bundle is not changed.

### Acceptance Criteria
* The UP translate step can remove unneeded Observations from a FHIR Bundle before sending to a receiver.
* Any translated report (e.g. FHIR to HL7 v2) contains only the needed Observation data.

**Comment by PatriciaPerozoUSDS** [comment]
We need to be mindful that we don't remove AOE observations accidentally. Either we have to include AOE loinc codes in all condition filters or we have to include them as a special case? Worth talking to engagement about how they want to handle this
