### ISSUE TITLE
`receivingApplicationName` and `receivingFacilityName` translation properties are not applied to HL7 senders on output

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#8099]
## Problem statement

`receivingApplicationName` and `receivingFacilityName` translation properties are receiver settings that are meant to set a default value for MSH-5 and MSH-6 respectively. This feature is working when the sender is submitting a CSV file. However, this is not working when the sender is submitting HL7. The expectation is all receiver settings will equally apply regardless of the sender input message type.

## Acceptance criteria

- [ ] The value in `receivingApplicationName` should be applied consistently to MSH-5 on output regardless of input message type
- [ ] The value in `receivingFacilityName` should be applied consistently to MSH-6 on output regardless of input message type

**Comment by LaFreda1** [comment]
@kant777 any updates?

**Comment by brandonnava** [comment]
Closing as finished
