### ISSUE TITLE
BUG: COVID Pipeline Delivery API Vague DevEnv Error

### ISSUE THREAD

**Issue by luis-pabon-tf** [CDCgov/prime-reportstream#8101]
### Background:
Currently, attempts on the developer environment to hit `/waters/report/{deliveryId}/delivery`  and `waters/report/{deliveryId}/facilities` both cause errors: `500: Cursor returned more than one result` when hit on the API via the developer environment.

### Acceptance Criteria
* API calls to the Delivery Details and Delivery Facilities endpoints need to return descriptive data on errors for both COVID and UP pipelines.

**Comment by avnieldravid** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8101?planning-poker) with Zenhub @carlosfelix2

**Comment by avnieldravid** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8101?planning-poker) with Zenhub @arnejduranovic @JessicaWNava @jack-h-wang @victor-chaparro @thetaurean

**Comment by avnieldravid** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8101?planning-poker) with Zenhub @PatriciaPerozoUSDS

**Comment by bishoyayoub** [comment]
@TurkeyFried Please see if this is still required. If so, please use latest template. Add steps to reproduce the issue.

**Comment by luis-pabon-tf** [comment]
I'm running the API calls that used to trigger the error with new submissions, and it seems we're good on this ticket.
