### ISSUE TITLE
Update FA versions in all environments

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#8120]
This can be done manually or via Terraform - but we need to make sure each FA (_and the candidate slot_) are at v4

[Docs](https://learn.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal)

**Comment by lucasdze** [comment]
[Migrate apps from Azure Functions version 3.x to version 4.x](https://learn.microsoft.com/en-us/azure/azure-functions/migrate-version-3-version-4?tabs=net6-in-proc%2Cazure-cli%2Cwindows&pivots=programming-language-csharp)

**Comment by lucasdze** [comment]
All functionApps ae now running on Version 4 already
