### ISSUE TITLE
Content for Automated Key Tool

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#8133]
## Problem statement

The sender emails us two separate public keys. Then those are stored in the database under sender settings. (Currently stored on staging and prod.) Then we send them an email that they can start testing (authentication) and includes the API endpoint to point to. And link them to API Programmer's guide.
This happens on almost every new sender (majority). Server-to-server auth.

## What you need to know

- [Figma](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=1203%3A14237&scaling=min-zoom&page-id=1179%3A14239&starting-point-node-id=1203%3A14237)
- [Working doc](https://docs.google.com/document/d/1rtAPVbDoDi_J4gbReHDZSMKdPU5IzUQ3mx1Y_xoqxJA/edit?usp=sharing)

Open Questions
[ ] In the case of an error, is any additional follow up needed beyond just an error message on the website (ie: separate email)?

## Acceptance criteria

 [ ] Any instructions/headers/sub-headers for submitting and editing their key
 [ ] Microcopy for input text field for key
 [ ] Microcopy for submission
 [ ] Error message content
 [ ] Share and review with Jillian

**Comment by audreykwr** [comment]
@chris-kuryak closing
