### ISSUE TITLE
Create Content for email to update all users on the changes to the Terms of Service

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8134]
## Problem Statement
The Terms of Service will be updated on the RS website. It is required that we communicate that those terms of service have changed to all of our users. The purpose of this issue is to define the content of that email message that will be sent to all users.

## Background Information
- The users will be defined by #8137
- Michael Burstein is currently working on some email message content

## Acceptance Criteria
- [x] Finalize email message content and formatting
- [x] Review finalized email message content with Chris Kuryak
- [x] Attach or paste finalized email message content and formatting in this ticket or send directly to Sharon Liu, copying Chris Kuryak and Brandon Canniff.

**Comment by chris-kuryak** [comment]
@lizzieamanning @audreykwr
FYI, Kimberly Labno said she would be able to help craft an email message if y'all wanted it. She has done this in the past, according to my convo with her.

**Comment by audreykwr** [comment]
Would that take the place of the Michael Burstein's content in the first AC?

**Comment by chris-kuryak** [comment]
I haven't heard back from Michael in a bit, so I am going to ping him. If he sends anything over, I'll let y'all know. But I would proceed without his content as I cannot ensure we will ever receive it.

**Comment by audreykwr** [comment]
Ah got it. Yeah I was waiting on that, thinking it was just an edit of someone else's draft. I'm fine with Kimberly making the first draft instead of Michael then if she's more available!

Also - did we clear up the question of if everyone who is getting this had indeed signed TOS already?

**Comment by lizzieamanning** [comment]
(https://app.zenhub.com/files/304423150/b0ddb3fd-221d-490a-aecd-7951e7459fab/download)

This is the redlined TOS- is this what you're looking for? @audreykwr @chris-kuryak 

@audreykwr https://github.com/CDCgov/prime-reportstream/issues/8137 might answer your question about who this is going to

**Comment by lizzieamanning** [comment]
(https://app.zenhub.com/files/304423150/b0ddb3fd-221d-490a-aecd-7951e7459fab/download)

This is the redlined TOS- is this what you're looking for? @audreykwr @chris-kuryak 

@audreykwr https://github.com/CDCgov/prime-reportstream/issues/8137 might answer your question about who this is going to

**Comment by chris-kuryak** [comment]
@audreykwr 
1) I'll connect you with Kimberly Labno on getting a rough draft/guidelines on a ToS Update email.
2) Getting senders to sign the ToS is in Sharon's onboarding process. However, I don't think receivers have signed the ToS. @sliu1000 can you clear that up for us?

**Comment by chris-kuryak** [comment]
Yep!
