### ISSUE TITLE
Email all users to indicate the updates to RS Terms of Service

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8135]
## Problem Statement
All RS users need to be updated on the changes to our Terms of Service. The O+O / Support team will be responsible for emailing those users from the findings of the WebEx team.

## Necessary Information
- The users will be defined by #8137
- The content of the email will be defined by #8134
- SendGrid may be useful for this task

## Acceptance Criteria
- [ ] All applicable users are sent the email as defined by #8134

**Comment by sliu1000** [comment]
I can send out the below communication once you give me the go ahead.  Do you know the specific updates/changes we can tell the user to review?

"Dear ReportStream User,

We want you to know that we've made updates our Terms & Conditions, including information on procedures for _________________.

We encourage you to review all the updated terms that apply to you.

Your continued use of our websites and mobile apps is your agreement to these updated term and policies.  If you have questions, please contact Customer Support at reportstream@cdc .gov.

Thank you,

**Comment by chris-kuryak** [comment]
@sliu1000 Hold off on sending out any email communication yet. Need to clear content through the design team in ticket #8134 
@lizzieamanning @audreykwr @jillian-hammer

**Comment by chris-kuryak** [comment]
Sharon has emailed all users
