### ISSUE TITLE
STLT Dashboard Testing with CO & WA

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#8136]
### **Background & Context**
Washington and Colorado have both expressed interest in learning more about the upcoming Data Dashboard. ReportStream designers will share the Figma prototype with the STLTs in a 30 minute session to learn more about the usability of the current design, identify gaps & needs. Takeaways will inform future iterations of the Data Dashboard.

### **Working Links**
- [Conversation Guide & Raw Notes](https://docs.google.com/document/d/1QSE1s0cEwIJFXrTL1KBROTP3wId1gQa-aBLCU7N10KQ/edit?usp=sharing)
- [Washington Synthesis Notes](https://docs.google.com/document/d/12vIKZB0iD3DOnjxHACBh6rRlzVfrS_Zpfk4tvQGW03s/edit?usp=sharing)
- [Colorado Synthesis Notes](https://docs.google.com/document/d/1VEZh1h_WUKcVz67EdohqepvcNDcTVeemqxqHEsAmG7U/edit?usp=sharing)
- [Research Synthesis Mural](https://app.mural.co/invitation/mural/primedatainput6410/1676646127606?sender=u0c3cdba5126734aceb613229&key=9a719b5c-faf5-4a28-9a36-012a139337bd)
- [Updated Figma designs per Research Synthesis](https://www.figma.com/file/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=2369%3A26962)

### **Acceptance Criteria**
- [x] Conversation guide completed 
- [x] Synthesized CO notes shared via Slack
- [x] Synthesized WA notes shared via Slack
- [x] Identify design changes to MVP, if any
- [x] Identify design changes to long-term version of the Dashboard, if any

**Comment by jillian-hammer** [comment]
This work is complete! Links to relevant research & synthesis materials have been updated in the issue description. 

**Research-determined design changes for MVP:**
- ADD facility location (City, State) column to the ["All facilities and providers"](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=2369%3A27610&scaling=min-zoom&page-id=2369%3A26962&starting-point-node-id=2369%3A26965) listing page, if applicable
- ADD facility location (City, State) to "[Facility Detail](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=2369%3A27947&scaling=min-zoom&page-id=2369%3A26962&starting-point-node-id=2369%3A26965)" page, if applicable
- ADD date range for each report to the "[Report Detail](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=2369%3A27816&scaling=min-zoom&page-id=2369%3A26962&starting-point-node-id=2369%3A26965)" page [NOTE: pending backend structural changes]
- ADD specimen collection date to the "[Report Detail](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=2369%3A27816&scaling=min-zoom&page-id=2369%3A26962&starting-point-node-id=2369%3A26965)" page [NOTE: pending backend structural changes]

Tagging @lizzieamanning and @chris-kuryak for awareness, and @stephenkao to ensure I captured takeaways from our Slack convo correctly.

**Comment by chris-kuryak** [comment]
Closing per updated Figma and communication out on the changes.
