### ISSUE TITLE
Prophase - California wants to receive test messages 

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#8138]
From Ellaison Carroll - ellaison.carroll@cdph.ca.gov

## Problem statement

Prophase wants to first receive test messages via the new HL7 format. Can you please send a few test messages? Do you want them to be sent to a staging environment?

## What you should know

Prophase CLIA 33D0126129 is confirmed and correct.
![image.png](https://images.zenhubusercontent.com/62828b77597e3bdcbc3834fd/c9d22377-28f7-4fc8-86c2-b2255dd1bd57)

Full communication:

Hi Ott,

Is Prophase’s CLIA 33D0126129?  If so, they last sent us CSV files in May.  Do we expect they will have a backlog of results when they start reporting using ReporStream?

We would like to see test messages first, especially since they will now come in via HL7 format.  Can you send me a txt file or some test messages from them or do you want to send them to our staging environment? 

Thanks,
Ellaison

**Comment by oslynn** [comment]
Hi Ellaison,

Yes, ProPhase's CLIA is 33D0126129.  I think, you are correct they may have a backlog of results to send to CA using ReportStream.
Attached please the test synthesized messages for you to validate.

Very respectfully,
-Ott Sathngam
CDC ISWE.

Attached file: junk/HealthcareIntegrations_ProPhase/CA/Sent/Prophase-to-CA-Test.hl7

**Comment by rnz6** [comment]
Hi Ott,

The first message looks okay, but are you able to send in maybe about 5 more results including several positives?  

That would be helpful for validation.  Emailing them is fine and please use test patient demographics.

Thanks,

Ellaison

**Comment by oslynn** [comment]
Done.
