### ISSUE TITLE
Verify if PMG Data going to HHS Protect is OTC Self-reported or Not

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#8139]
## Problem statement

We received an inquiry in the ReportStream inbox from Norris Kpamegan (Data Scientist, Analytics Team, Laboratory, CDC (Deloitte Contractor) on whether the below are OTC Data or School Based:

- PMG
- Safehealth
- Reddyfmc-la

## What you need to know

-All are reporting directly to HHS Protect
-User is requesting this to be high priority as they need to submit this information for a project they are working on.

## Acceptance criteria

- Confirm if PMG, Safehealth, Reddyfmc-la is OTC Self-Report results or something else

## To do

- Assign to Engineer to confirm

**Comment by LaFreda1** [comment]
@brick-green Will you confirm whether or not those senders are OTC or school-based? Thanks!

**Comment by sliu1000** [comment]
Del Guercio, Kim Lu (CDC/DDID/NCEZID/DHQP) (CTR)
Report Stream (CDC);Kpamegan, Norris (CDC/DDID/NCEZID/OD) (CTR);Liu, Sharon (CDC/DDPHSS/OD/HITSSU) (CTR)
Thanks, Sharon. That is our plan. 

Kim 

Kim Del Guercio, MPH
Deloitte Consulting
Mobile: 404.353.2101

Please note that the best way to get in touch with me for urgent requests and on weekends is by texting the number above. 

From: Report Stream (CDC) <reportstream@cdc.gov>
Sent: Wednesday, February 1, 2023 12:59 PM
To: Del Guercio, Kim Lu (CDC/DDID/NCEZID/DHQP) (CTR) <uwx1@cdc.gov>; Kpamegan, Norris (CDC/DDID/NCEZID/OD) (CTR) <svi5@cdc.gov>; Liu, Sharon (CDC/DDPHSS/OD/HITSSU) (CTR) <roy2@cdc.gov>
Subject: Re: A new ticket has been submitted to the ReportStream Smartsheet
 
Hi Kim,

Its separate from SimpleReport. However, it may not be exclusively OTC data. I have yet to confirm. You can omit from your data set if you need to send out.  As I am still waiting for confirmation.

Best regards,

Sharon
The ReportStream Support Team
Contact us at reportstream@cdc.gov
Support hours:  8:00 am through 9:00 pm Eastern time
Monday-Friday, excluding US public holidays

From: Del Guercio, Kim Lu (CDC/DDID/NCEZID/DHQP) (CTR) <uwx1@cdc.gov>
Sent: Tuesday, January 31, 2023 5:48 PM
To: Kpamegan, Norris (CDC/DDID/NCEZID/OD) (CTR) <svi5@cdc.gov>; Report Stream (CDC) <reportstream@cdc.gov>; Liu, Sharon (CDC/DDPHSS/OD/HITSSU) (CTR) <roy2@cdc.gov>
Subject: Re: A new ticket has been submitted to the ReportStream Smartsheet

Another alternative - do you happen to know if the data are coming through SimpleReport for them? 

Kim Del Guercio, MPH
Deloitte Consulting
Mobile: 404.353.2101

Please note that the best way to get in touch with me for urgent requests and on weekends is by texting the number above. 

From: Kpamegan, Norris (CDC/DDID/NCEZID/OD) (CTR) <svi5@cdc.gov>
Sent: Tuesday, January 31, 2023 4:53 PM
To: Report Stream (CDC) <reportstream@cdc.gov>; Liu, Sharon (CDC/DDPHSS/OD/HITSSU) (CTR) <roy2@cdc.gov>
Cc: Del Guercio, Kim Lu (CDC/DDID/NCEZID/DHQP) (CTR) <uwx1@cdc.gov>
Subject: RE: A new ticket has been submitted to the ReportStream Smartsheet
 
Hi Sharon,

Thank you for sending over this information. Would it be possible to confirm with them by tomorrow and let us know what you learn? That would be incredibly helpful for us.

Best,

Norris K.

Norris N. Kpamegan
Data Scientist, Analytics Team, Laboratory Data Section 
Centers for Disease Control and Prevention
Deloitte Consulting | Mobile: (202) 823-3555
nkpamegan@deloitte.com | svi5@cdc.gov
 
From: Report Stream (CDC) <reportstream@cdc.gov>
Sent: Tuesday, January 31, 2023 4:41 PM
To: Del Guercio, Kim Lu (CDC/DDID/NCEZID/DHQP) (CTR) <uwx1@cdc.gov>; Liu, Sharon (CDC/DDPHSS/OD/HITSSU) (CTR) <roy2@cdc.gov>; Kpamegan, Norris (CDC/DDID/NCEZID/OD) (CTR) <svi5@cdc.gov>
Subject: Re: A new ticket has been submitted to the ReportStream Smartsheet

 

Hi Kim,

It stands for Premier Medical Group. I believe they are a data aggregator and not certain if its only for self-reporting test kits. I'll need to reach out to them to confirm.

Best regards,

Sharon

The ReportStream Support Team
Contact us at reportstream@cdc.gov
Support hours:  8:00 am through 9:00 pm Eastern time
Monday-Friday, excluding US public holidays

From: Del Guercio, Kim Lu (CDC/DDID/NCEZID/DHQP) (CTR) <uwx1@cdc.gov>
Sent: Tuesday, January 31, 2023 4:21 PM
To: Liu, Sharon (CDC/DDPHSS/OD/HITSSU) (CTR) <roy2@cdc.gov>; Kpamegan, Norris (CDC/DDID/NCEZID/OD) (CTR) <svi5@cdc.gov>; Report Stream (CDC) <reportstream@cdc.gov>
Subject: Re: A new ticket has been submitted to the ReportStream Smartsheet

Thanks, Sharon. Can you provide more info on who the sender is (what pmg stands for)? 

Kim Del Guercio, MPH
Deloitte Consulting
Mobile: 404.353.2101
Please note that the best way to get in touch with me for urgent requests and on weekends is by texting the number above.
