### ISSUE TITLE
Content strategy kick-off workshops

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#8143]
## Problem statement

To set a strong foundation of where we are and what our user's needs are, we need to gather SMEs and other relevant stakeholders around some key questions for both alignment and discovery.

## What you need to know

- The current plan is for the first workshop to focus on the purpose of the site and overall direction, and the second will dive deeper into user needs. (I am considering flip-flopping that order though)
- [Mural of general work roadmap/misc notes](https://app.mural.co/invitation/mural/nava4113/1673278109303?sender=uc55a7af3b66977fba12f5528&key=27b02b81-58ce-4f9b-a734-4aab2802ad5b)

## Acceptance criteria

- [x] Attendees IDed and invited
- [x] Agendas prepared and shared with participants
- [x] Activities planned and prepared in a collaborative space

## To do

- [ ]

**Comment by audreykwr** [comment]
@lizzieamanning let me know how this looks

**Comment by lizzieamanning** [comment]
@audreykwr the only thing I'm wondering is if we should move the last AC: "Final notes and findings shared with design team and other relevant stakeholders" into a follow up ticket. Pending when the workshop is scheduled, this could hold up completion of this ticket. Another way to think about it is this as the "prep" ticket for the workshop and adding another "synthesis" ticket for the workshop as a follow up

**Comment by audreykwr** [comment]
Yeah good point that that depends on timing. If it is like, the last day of the sprint then there might not be follow up time. That said, these typically don't require that intense of summarizing, so it would very likely be in the lower point range if we did separate it. But that's just me wondering about granularity again. I'm fine separating if it's helpful!

**Comment by audreykwr** [comment]
@chris-kuryak closing this!
