### ISSUE TITLE
WA not receiving results 

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#8158]
WA DPH has not received the following test event submitted through SimpleReport on 1/25/23 c22487bf-8930-4591-aa5d-5f01bca301c0.

Support desk has confirmed in Metabase that the event Id was a backlogged test entered at 6:57pm on 1/25/23 backdated to 1/25/23 5:30pm. SimpleRepot logs the result as submitted at 12:30 pm. 

Daily data HL7's were searched for WA DPH for 1/25 and 1/26 and San Juan Island School District is not listed on any of the reports for that 24 hour period.

**Comment by brick-green** [comment]
Contacted OneHealthPort via their service form. Going to make a code change to log the status codes we're receiving

**Comment by LaFreda1** [comment]
Making this a low priority ticket due to team's bandwidth

**Comment by brick-green** [comment]
Just resent these messages. @TaneaY Can you let WA know?

**Comment by TaneaY** [comment]
Follow- up sent.
Hi Erin,

Engineering has confirmed a resubmission of these files. Please check your logs for updates.

Please let us know if you have any additional questions or concerns.

Thank you,
