### ISSUE TITLE
BD Veritor Onboarding – Testing in Staging and Prod

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#8174]
### Acceptance Criteria 
- [ ] Sender has tested in staging and production 
- [ ] RS engineer has determined the data is good enough and graduates Sender to send Prod data to receiver  

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with sender

**Comment by brick-green** [comment]
Sent an update to sender that they can start testing with staging

**Comment by sliu1000** [comment]
Update from Sender:

I hope you are doing well! 

Now that we’ve successfully reported test data to the ReportStream staging server, I wanted to check in and see what are the next steps.   Do we need to do anything else first before getting production access?

Thanks!

Rami

**Comment by GilmoreA6** [comment]
Missing required fields or other issues (notes from 2/24/13 meeting Brick/Angela/James)
-MSH-4-2 needs to contain a valid CLIA number (10 characters) for RS. Proposal to inform BD Veritor to follow process outlined in RadXMars spec to use fake CLIA number provided by APHL of 00Z0000005.
- Inform BD Veritor that fields marked optional on the RADX Mars spec may result in reports not reaching a certain jurisdiction if the filter for that jurisdiction requires that element (Ex: CA requires DOB).

**Comment by LaFreda1** [comment]
@chris-kuryak Closing (all BD tickets), we can reopen if they reach out
