### ISSUE TITLE
BD Veritor Onboarding – Go Live Coordination

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#8176]
### Acceptance Criteria 
- [ ] Contacted sender to confirm when they want to start sending  
- [ ] Introduced sender to the Customer Support form and CC: the Ops team (at least Sharon Liu and Berni Xiong)  
- [ ] Adjusted final settings:  
     - [ ] Modified organization.yml and created yamlitos  
          - [ ] Customer status = active  
     - [ ] Modified prod settings table  
     - [ ] Modified staging settings table 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with sender and ops team

**Comment by sliu1000** [comment]
Update from Sender:

Hi LaFreda and ReportStream team,

 

I wanted to check in and see if there is any update.   Also, I noticed last week that the RADx MARS team published an update to their specification (on Feb 22): https://www.nibib.nih.gov/covid-19/radx-tech-program/mars/HL7v2-implementation-guide

 

I updated our app to match that new spec.   I’ve already sent a couple of messages to the ReportStream staging server late last week, but wanted to send a sample via email as well in case that is preferable:

 

MSH|^~\\&|BDVERITOR.STAG^2.16.840.1.113883.3.8589.4.2.108.2^ISO|BDLab^2.16.840.1.113883.3.8589.4.1.32^CLIA|CDC PRIME^2.16.840.1.114222.4.1.237821^ISO|CDC PRIME^2.16.840.1.114222.4.1.237821^ISO|20230307235215+0000||ORU^R01^ORU_R01|20230307_dx_1A6CVLrCejt9DkAGLeTcgeQN|T|2.5.1|||NE|NE|||||PHLabReport-NoAck^ELR251R1_Rcvr_Prof^2.16.840.1.113883.9.11^ISO\rSFT|Becton, Dickinson and Company|v1.5.1|Scanwell App|2566c7e||20230115\rPID|1||pat_1ErbRCgR6qc5fM3UZ4GdVfnF^^^&2.16.840.1.113883.3.8589.4.2.108.2&ISO^PI||Test^Rami||19720310||||^^^^56007||^^Internet^rami@test.com\rORC|RE||dx_1A6CVLrCejt9DkAGLeTcgeQN^^2.16.840.1.113883.3.8589.4.2.108.2^ISO|||||||||^^SA.OTCSelfReport|||||||||SA.OTCSelfReport|^^^^56007\rOBR|1||dx_1A6CVLrCejt9DkAGLeTcgeQN^^2.16.840.1.113883.3.8589.4.2.108.2^ISO|97097-0^SARS-CoV-2 (COVID-19) Ag [Presence] in Upper respiratory specimen by Rapid immunoassay^LN^^^^2.71|||20230303192600+0000|||||||||^^SA.OTCSelfReport||||||20230303192600+0000|||F\rOBX|1|CWE|97097-0^SARS-CoV-2 (COVID-19) Ag [Presence] in Upper respiratory specimen by Rapid immunoassay^LN^^^^2.71||260415000^Not Detected^SCT^^^^20210301|||N^Normal^HL70078^^^^2.5.1|||F||||00Z0000042||BD Veritor At-Home COVID-19 Test_Becton, Dickinson and Company (BD)_EUA^^99ELR^^^^Vunknown||20230303192600+0000||||SA.OTCSelfReport^^^^^&2.16.840.1.113883.3.8589.4.1.152&ISO^XX^^^00Z0000042|Fake AtHome Test Street^^Fake City\rNTE|1|L|BD Veritor At-Home COVID-19 Test_Becton, Dickinson and Company (BD)_EUA\rOBX|2|NM|35659-2^Age at specimen collection^LN^^^^2.71||51|a^year^UCUM^^^^2.1|||||F||||00Z0000042||||||||SA.OTCSelfReport^^^^^&2.16.840.1.113883.3.8589.4.1.152&ISO^XX^^^00Z0000042|Fake AtHome Test Street^^Fake City|||||QST\rSPM|1|^dx_1A6CVLrCejt9DkAGLeTcgeQN&&2.16.840.1.113883.3.8589.4.2.108.2&ISO||697989009^Anterior nares swab (specimen)^SCT^^^^20210301|||||||||||||20230303192600+0000|20230303192600+0000\
 

Thanks!

Rami
BD Veritor
