### ISSUE TITLE
Synthesis of content strategy workshops

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#8178]
## Problem statement

To set a strong foundation of where we are and what our user's needs are, we need to gather SMEs and other relevant stakeholders around some key questions for both alignment and discovery.

## What you need to know

- The current plan is for the first workshop to focus on the purpose of the site and overall direction, and the second will dive deeper into user needs. (I am considering flip-flopping that order though)
- [Mural of general work roadmap/misc notes](https://app.mural.co/invitation/mural/nava4113/1673278109303?sender=uc55a7af3b66977fba12f5528&key=27b02b81-58ce-4f9b-a734-4aab2802ad5b)

- [Ticket for workshops](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/8143)

## Acceptance criteria

- [x] Notes summarized and shared with participants and design team, and other relevant stakeholders as further identified
- [x] Next steps planned and tickets created

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@chris-kuryak was this the ticket you said needed refinement? it's just kind of a simple ticket ha. We separated out a step or two from the actual workshop ticket since it likely will be in next sprint since the last workshop isn't until the last day of this sprint. But it's just not that involved. @lizzieamanning what other details do you think are helpful?

**Comment by chris-kuryak** [comment]
@audreykwr Yep, but noticed:

-  that the link to Document 2 is broken 
- when you say "notes summarized and shared out" -- to whom is the sharing (Design, engr, etc)?
- next steps planned -- are you going to document that somewhere, create new tickets, etc? (That is just more for my awareness in case I look at this ticket after it is closed)

**Comment by audreykwr** [comment]
Added some clarity on those! And the document link was just an error.. forgot to delete it from the template haha

**Comment by chris-kuryak** [comment]
Thanks!

**Comment by audreykwr** [comment]
@lizzieamanning @chris-kuryak closing this!
