### ISSUE TITLE
HL7 County Codes Don't Map in Sully File Properly

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#818]

**Comment by jimduff-usds** [comment]
Explanation needed.

**Comment by jimduff-usds** [comment]
@MauriceReeves-usds , do we think this is still an issue?   Feel free to close if it does not need fixing.

**Comment by jimduff-usds** [comment]
@MauriceReeves-usds , I'm closing this.  Feel free to reopen if needed.
