### ISSUE TITLE
Generate Simple Report specific FHIR to HL7 v2 translation config

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#8180]
### User Story:
As a receiver, I want to receive a complete message even if some data is not provided by SR, so I can process the data.

### Description/Use Case
Simple Reports provides us with the test data, but we are missing some data like headers that we will need to fill in before sending the data to a receiver.

### Risks/Impacts/Considerations
* Some missing data may have to be provided by SR, so identify what it is, discuss if this is really the case, then request it. Good source for a checkup is OO.

### Dev Notes:
* We currently do not have a sender transform feature, so all sender transforms will need to be done on the FHIR to HL7 translation config. Separate and mark those configs, so it is easier later to move them to the sender transform config.
* Reference configuration and data generated by the COVID pipeline to figure out what is needed.

### Acceptance Criteria
* The UP can translate SR data to HL7 v2.
* The HL7 v2 generated data from a SR report contains all HL7 v2 required fields.
* (Ambiguous requirement) The HL7 v2 generated data from a SR report contains expected HL7 v2 fields (check with COVID messages and OO).

**Comment by PatriciaPerozoUSDS** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8180?planning-poker) with Zenhub @arnejduranovic @jimduff-usds @jimmyfagan @PatriciaPerozoUSDS @TurkeyFried @JessicaWNava @victor-chaparro @jack-h-wang @carlosfelix2

**Comment by carlosfelix2** [comment]
Initial samples provided by SR - No PII
[https://app.zenhub.com/files/304423150/aef09750-ad71-4bd2-9609-e8beaaf793fc/download](https://app.zenhub.com/files/304423150/aef09750-ad71-4bd2-9609-e8beaaf793fc/download)[https://app.zenhub.com/files/304423150/fad7dee6-ad6d-4500-bad9-9ed2e792f8ec/download](https://app.zenhub.com/files/304423150/fad7dee6-ad6d-4500-bad9-9ed2e792f8ec/download)[https://app.zenhub.com/files/304423150/e63fc800-673c-44c8-b001-c6e9cd75c134/download](https://app.zenhub.com/files/304423150/e63fc800-673c-44c8-b001-c6e9cd75c134/download)[https://app.zenhub.com/files/304423150/a45d8c56-8c41-4002-84d3-3a1c7827615e/download](https://app.zenhub.com/files/304423150/a45d8c56-8c41-4002-84d3-3a1c7827615e/download)[https://app.zenhub.com/files/304423150/c1f7f201-d861-4e34-ba93-e0f1cee45aa5/download](https://app.zenhub.com/files/304423150/c1f7f201-d861-4e34-ba93-e0f1cee45aa5/download)[https://app.zenhub.com/files/304423150/757b4512-2d65-4c13-8698-a9947d28236b/download](https://app.zenhub.com/files/304423150/757b4512-2d65-4c13-8698-a9947d28236b/download)
