### ISSUE TITLE
CA - LA County Test Date Error

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#8193]
LA County California is reporting issues with test dates being wrong.

##Background Information

At LA county, we have received some reports with date issue. See summaries below and examples attached. Please let us know if you’re able to help resolve these issues.

 ![image.png](https://images.zenhubusercontent.com/62828ac9597e3bae41382df7/75da72a0-80eb-4c6f-9b26-049fbe9216f4)

**Comment by sliu1000** [comment]
Confirmed this was a SimpleReport user entry error.  Emailed SimpleReport to reach out to the lab to correct the data entry error and resubmit.
