### ISSUE TITLE
Prophase(HC) - Production Error - Key revoked until HC issue confirms fix

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#8196]
## **Problem Statement**
Starting Friday night 2/4/2023 we received several thousand failures with 400 message errors.  fix the situation with hcintegrations.    They were sending erroneous data through Friday evening, at which time we completely turned off their ability to send data.  

## **What you need to know**
The problem appears to have started Thursday (2/3), and was a mix of failures and successes and has gotten worse over time.  I’m not sure why we didn’t get pagerduty alerts sooner.

The payload size from hcintegrations is always either 2264 or 2292 bytes.  Both fail.
They might just be sending fake or bogus data — in the action_log table the tracking_id is always ‘message1’.

All the errors in their data look like this:
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/2d8dc0a5-f9e9-48f8-bf63-1e93663d8bb6)

Jim Duff - sent the x-functions-key to @Maurice Reeves in Keybase, so we can simply re-install it once Healthcare Integrations says they have fixed the problem.

James Gilmore - Sent an email to a contact at HC Integrations and cc'd everyone here.

## **Acceptance Criteria**
- HC Integrations needs to confirm they have fixed the problems with their data, then Engineering needs to re-install their key in Prod, so they can send again.   Then of course we need to monitor to confirm its really fixed.

## **To Do**
- Helpdesk to contact HC regarding their Key revoke and setup a meeting to discuss next steps
- Log/create incident report - determine rootcause

## **Additional Comments**
If applicable, add screenshots, links, etc. to further explain the ticket

**Comment by oslynn** [comment]
Fixed and restored their key.  Note, it is healthcareintegrations (ProPhase) instead of HCA.
