### ISSUE TITLE
Add end-to-end tests for validate page

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8200]
## Problem statement

With the validator page going public, we should add some end-to-end tests to cover the three basic flows:

- As a logged-out user, see three master schemas and run validation
- As an admin, see three master schemas and run validation
- As a Sender, see four schemas (three master schemas + Sender-designated schema) and run validation

## Acceptance criteria

- [ ] A new Cypress test is added for a logged-out user validation flow
- [ ] A new Cypress test is added for an admin validation flow
- [ ] A new Cypress test is added for a Sender validation flow

**Comment by chris-kuryak** [comment]
This is a good place to start in creating E2E tests on the rest of the site moving forward.

**Comment by KeithNava** [comment]
The scope for this original ticket has changed quite a bit but the End Goal is the same - Get an End To End testing framework pattern up and running. See: https://github.com/CDCgov/prime-reportstream/pull/10881

I'll be create new tickets and adding End to End testing to acceptance criteria after a full round of code review
