### ISSUE TITLE
Proposal for consolidated API response payload structure

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8202]
## Problem statement

We're sending back top-level arrays for collection-oriented responses (`/deliveries` and `/submissions` endpoints in particular), and we can update this to return an object so that we can include collection metadata like entity type and pagination information. 

## What you need to know

- See [this Slack conversation](https://www.slack.com/archives/C01HFHPNJEL/p1670348915918859) for more information.

## Acceptance criteria

- [ ] A proposal doc is reviewed and approved by Platform team

**Comment by chris-kuryak** [comment]
This is a more fundamental structural change that we want to have ironed out (between all teams) before we build/launch the STLT dashboard.

**Comment by chris-kuryak** [comment]
Awaiting review from Arnej
