### ISSUE TITLE
Create new repo for FHIR to HL7 v2 library following CDC guidelines

### ISSUE THREAD

**Issue by PatriciaPerozoUSDS** [CDCgov/prime-reportstream#8211]
### User Story:
As a developer, I need a repo within the CDC github organization to host the new open source conversion library.

### Description/Use Case
This repo will be dedicated to the FHIR to HL7 v2 converter and will host all of the code, configuration, and documentation needed for the library. Determine if the default license works for our use case.

### Dev Notes
* Note from @jpandersen87 :

> To request creation of a new repo under CDCGov you must fill out this [O365 form](https://forms.office.com/Pages/ResponsePage.aspx?id=aQjnnNtg_USr6NJ2cHf8j44WSiOI6uNOvdWse4I-C2NUNk43NzMwODJTRzA4NFpCUk1RRU83RTFNVi4u) . It requires you to have a CDC O365 account. You'll be asked general information about the project as well as what users+role you want initially added to it. I followed @stephenkao 's recommendation of requesting people across the teams as admins. Turnaround time was half a day.
* CDC has a starter repo template that includes a number of things out of the box such as a code of conduct, contribution guidelines, and a default license! https://github.com/CDCgov/template

### Acceptance Criteria
* There is a repo created within the CDC organization to house the FHIR to HL7 v2 converter
* All ReportStream engineers have access to it (including Mo)
* An open source license has been chosen

**Comment by avnieldravid** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8211?planning-poker) with Zenhub @arnejduranovic @carlosfelix2 @jack-h-wang @JessicaWNava @PatriciaPerozoUSDS @thetaurean @victor-chaparro
