### ISSUE TITLE
Adjust process report request to use Customer Status

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#8214]
## Problem statement

There have been multiple cases when a sender is submitting bad data continuously. In those cases it can be difficult to contact the sender is a timely basis. The only option to block data submission to to revoke the API key for the sender. A better solution is to use Customer Status. The field is currently available for use with values including: ACTIVE, INACTIVE, TESTING. 

## Need to Know

- This feature request was mentioned by @mauricereeves in Slack here for context:
https://nava.slack.com/archives/C025F5W5Q7L/p1675692640674619?thread_ts=1675688304.141689&cid=C025F5W5Q7L

## Acceptance criteria

- [ ] A sender with customer status `ACTIVE` should be able to submit data freely
- [ ] A sender with customer status `TESTING` should be able to submit data freely
- [ ] A sender with customer status `INACTIVE` should have submissions refused and the reason included in the http response
- [ ] Review with Brick Green and James Gilmore (O+O team) that all Senders 'customerStatus' is accurate BEFORE deploying

## To do

- [ ] Adjust ReportFunction to inspect customer status

**Comment by avnieldravid** [comment]
@carlosfelix2 can we prioritize this for next sprint?

**Comment by LaFreda1** [comment]
@brick-green do we need to work with the platform team on this?

**Comment by brick-green** [comment]
@LaFreda1 I think an engineer from either team can pick this up. It shouldn't be too too hard.

**Comment by brandonnava** [comment]
Blocked by #8091

**Comment by LaFreda1** [comment]
No need for this work with UP
