### ISSUE TITLE
Develop rough requirements for RS tables

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8231]
## Problem Statement
The requirements for tables on the RS project should be a design-forward discussion. This revolves mostly around what we want tables to do and how users should be able to interact with them. Therefore, this ticket is to have the Design team develop some rough requirements around tables on the RS website.

## What to Know
[Here is the document](https://docs.google.com/document/d/1HgVHQb7jGsDv_JmGa-8ewwIoFaJi0Hj5Jy7_10pcYUo/edit) Stephen has put together with notes around Table Requirements (and questions to answer).

Stephen had mentioned the following for a framework of what to answer:

- How is the data in a table expected to appear?
- What are the desired behaviors? Such as:
  - Here is what happens when you click on X
  - Here is what happens when you hover over Y
  - When a user does event Z, this is what is expected
  - If the data is too large for the cell, then Y
  - A filter should be able to do X

The document can be visual if it is easier, but needs to be behavior based. 
It does not need to be exhaustive yet, but should provide a good foundation for the follow-on discussion with engineering.

## Acceptance Criteria
- [x] A document regarding table behaviors and appearance is created and ready to share with engineering for further discussion

**Comment by jillian-hammer** [comment]
Adding the link to the [Table Discovery & Requirements Mural](https://app.mural.co/invitation/mural/primedatainput6410/1677789052306?sender=u0c3cdba5126734aceb613229&key=7c59f374-11c2-4911-8dc5-5b389e432a5e).
