### ISSUE TITLE
Add Utah to "where we're live"

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#8233]
## Problem statement

Utah has been live and needs to be updated on the SVG map and text list on ReportStream's public facing web page "Where We're Live."

Documented processes with instructions on creating a PR can be found in [this Sharepoint doc](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Onboarding%20%26%20Ops/Scrum/Processes%20Documented/Update%20SVG%20Map%20and%20List%20Process.docx?d=w9640218c586e42b09fcc0324d8c7b4f5&csf=1&web=1&e=VEp7lB)

## Acceptance criteria

- [x] SVG map and text list show Utah as "live" on these pages:
- [x] https://reportstream.cdc.gov/
- [x] https://reportstream.cdc.gov/how-it-works/where-were-live

## To do

- [x] Engr to create PR ([see instructions](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Onboarding%20%26%20Ops/Scrum/Processes%20Documented/Update%20SVG%20Map%20and%20List%20Process.docx?d=w9640218c586e42b09fcc0324d8c7b4f5&csf=1&web=1&e=VEp7lB))
- [x] Exp. engr to Review/QA the PR

**Comment by LaFreda1** [comment]
@GilmoreA6 will you complete this ticket when you get a chance? Thanks!

**Comment by GilmoreA6** [comment]
This work has already been merged to master by @penny-lischer in PR #8129. This will move to production with our next deploy on 2/14. Closing ticket as duplicate.
