### ISSUE TITLE
Update email address in Terms of Service

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8241]
## Problem statement

A mistake was made on the new terms of service on the website. The email in "Other Responsibilities" section needs to be changed from usds@cdc.gov to reportstream@cdc.gov.

## What you need to know

- There is an existing code change (#8132) that has been merged but not deployed with the updated Terms of Service
- The change of email address needs to be made to the code that is going to be deployed as part of #8132
- This is the email address that needs to be changed to reportstream@cdc.gov:
![Screenshot 2023-02-07 at 3.45.37 PM.png](https://images.zenhubusercontent.com/637d310dba428f3e3d55c9db/abb1fa5e-6f8c-4536-9719-a48d52d6f789)

## Acceptance criteria

- [x] The email in "Other Responsibilities" section of ToS needs to be reportstream@cdc.gov

## To do

- [ ] ...

**Comment by penny-lischer** [comment]
@jillian-hammer @audreykwr should this be a link? Currently it's just text in a paragraph.

**Comment by jillian-hammer** [comment]
@penny-lischer yes, for consistency, emails should be a treated as a link with an external link icon. see how it's treated on the FAQ page for reference: 

<img width="1609" alt="image" src="https://user-images.githubusercontent.com/119958649/219230864-705f6c96-2940-4cf3-8980-62001daa5f45.png">
