### ISSUE TITLE
Update FhirTranscorderTests to use .isEqualTo instead of .equals

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#8249]
## Describe the bug
Inside FhirTranscorderTests.kt, there are 5 instances of .equals being used with assertThat to test that two bundles are equal. The tests need to be updated to use .equalsTo otherwise the tests are not testing anything. 

## Impact on ReportStream
Unit test are not testing the expected behavior

## Steps to reproduce
1. Debug this unit test "test encoding and decoding combination" inside FhirTranscorderTests.kt
2. decodedBundle.equals(testBundle) returns false, but the test doesn't report that

## Expected behavior
Update unit tests inside  FhirTranscorderTests.kt to use isEqualTo instead of equals. Make sure all unit tests pass after updating them.

**Comment by avnieldravid** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8249?planning-poker) with Zenhub @carlosfelix2 @jack-h-wang @JessicaWNava @PatriciaPerozoUSDS @thetaurean @victor-chaparro @arnejduranovic
