### ISSUE TITLE
CA - Add test receiver

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#8250]
## Problem statement

CA would like the ability to send results to their staging system using the SR CSV uploader and SR direct entry. To do so RS will need to add a receiver to accept results with processing mode code T or D and an SFTP transport to the Saphire Staging env.

## What you need to know

host: saphiresftpstage.cdph.ca.gov
userName: ReportStream-sftp

password is stored in keybase: keybase://team/prime_dev_ops/state_info/CA/ca-connection-info.yml

**Comment by LaFreda1** [comment]
Teddy emailed for an update on 2/15/23. I responded to let her know that we are still working through the queue and will provide an update when I can.

**Comment by oslynn** [comment]
Done.
