### ISSUE TITLE
Remove extra wrapping <hr>s from breadcrumb component

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#8252]
## Describe the bug
The breadcrumb component has extra `<hr>`s wrapping it. Causes rules to show up around the component that jam up against the nav and `<h1>`s.

## Impact on ReportStream
Adds unneeded extra rules to header area of most pages.

## Steps to reproduce
1. Go to any page under `/resources/*` or `/support/*`
2. See extra `<hr>`s in header area

## Resources
![Screen Shot 2023-02-07 at 9.29.37 PM.png](https://images.zenhubusercontent.com/5ff50e49f74e134e95117280/ddafd5ce-65ec-4c42-a0f2-3e8d3b5bc677)

## Logs
If applicable, please attach logs to help describe your problem.

## Additional context
Add any other historical context about the problem here.

**Comment by drew-usds** [comment]
Was just deleting two lines, put a PR for this out here: https://github.com/CDCgov/prime-reportstream/pull/8253

**Comment by jillian-hammer** [comment]
I _believe_ these line rules are an artifact from @jpandersen87 and I's implemented solution for previous issue "Breadcrumbs on Submissions Detail don't link back to previous URL" #7712. 

I wanted to clarify that the line rules were intended to only live on the Submission Detail page (see below) as a way to visually separate the breadcrumbs from the "Return to Message ID" callout. My mistake for not catching that they updated globally. 

![image.png](https://images.zenhubusercontent.com/639236212968fbce989b5d65/1c9712bb-665b-492d-acf8-ad75bced3324)

cc @stephenkao
