### ISSUE TITLE
IL - Filter Update Request

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#8269]
## **Problem Statement**
We received an email from Charlotte Picard from the State of Illinois in the ReportStream inbox to update their filters. 

## **What you need to know**
Charlotte is requesting their filter to be updated so that they start receiving:
·       Antigen tests – positives only
·       Antibody tests – no results
·       Other tests such as PCRs, NAATs etc. – all results

Please let them know if theirs's any additional information and what they should expect to receive now.

Per Charlotte "We’d like to be able to do in an ideal world, we would want to be able to refine the filters so that we could request different subsets within test type, like all results for lab-based PCRs performed in labs approved to do moderate- to high-complexity testing but not rapid tests like ID Now for example. "

-Currently IL filters out negative results.

## **Acceptance Criteria**
-IL starts receiving (1) Antigen tests - positives only, (2) Antibody Tests - no results, (3) Other tests such as PCs, NAATs etc. all results.

-Please confirm with IL they are receiving (the above)
-Email necessary communication to affect users on the update.

## **To Do**
-Communicate with Charlotte that an Engineer has been assigned and will start working on this.  Advise on the expected time it will take to complete this work.

## **Additional Comments**
None

**Comment by sliu1000** [comment]
Receiver is requesting for a Status Update:

 Hi Sharon,

EliteMed has sent bulk uploads since Friday with positive results in them as well as the negatives.  We are not seeing the positives in our I-NEDSS system, however.  Is there something in our filters that are not allowing the positive results in bulk uploads reach Illinois? 

Thanks,
Jennifer

**Comment by LaFreda1** [comment]
@GilmoreA6 please see the receiver's email above. Thanks!
