### ISSUE TITLE
Investigate capabilities and work to be done on new Okta instance

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8275]
## Problem statement

Since the Experience team is not very familiar with Okta and it's capabilities, this ticket to have an Experience engineer get more familiar with Okta features and how we will interface with them on the website. And then report those learnings back to the rest of the team.

## What you need to know

- New Okta instance here: reportstream.okta.com
- You need Stephen or Chris to create an admin account for you to access it
- NOTE: We may move away from SPA, so please investigate from an technically agnostic perspective. SimpleReport app configuration is geared more towards a traditional website design, so can use that for reference.

## Acceptance criteria

- [x] How would we WANT the new Okta instance interface with our RS website?
- [x] What work needs to be done on the new Okta instance to get it ready to plumb to the RS website?
- [x] How can we migrate users from the existing HHS instance to this new ReportStream instance?
- [x] How to create multiple levels of RS Admin access to the RS website
- [x] Answers to questions (or links to answers) documented and shared with team during Eng sync (invite Chris Kuryak to that Eng sync)

## To do

- [ ] ...

**Comment by jpandersen87** [comment]
Notes on this currently are here for those with permission: https://docs.google.com/document/d/1lPCVpzU9tqdESWxOyU9KqxOr-Tlax0SVe7u79bTYz2g/edit?usp=sharing

**Comment by chris-kuryak** [comment]
Great readout and notes. Closing this for follow-on tickets.
