### ISSUE TITLE
Table Design Discovery

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8277]
## Problem statement
Tables are used extensively across the ReportStream website, but use different styles and address different use cases. Prior to consolidating the table component into "One table to rule them all" (#8280), the design team needs to conduct an audit of all of the table instances to ensure that the new component will address the needs of tables across RS. Additionally, tables that don't yet exist (e.g, Programmer's Guide and the Data Dashboard) also have to be considered. Ultimately, this deeper understanding will better inform the subsequent synthesis and functionality work (captured in Develop rough requirements for RS tables #8231).

## What you need to know
- [Table Component Design Brief](https://docs.google.com/document/d/1ZT0YtNyPZSVcDh3cbWEG2PpowXGz91aPJwI6hlWjiA8/edit?usp=sharing)
- [Sister Ticket: Table Content Discovery #8278](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/8278)
- [Table Design Discovery Mural](https://app.mural.co/invitation/mural/primedatainput6410/1677789052306?sender=u0c3cdba5126734aceb613229&key=7c59f374-11c2-4911-8dc5-5b389e432a5e)

## Acceptance criteria

- [x] Table designs are documented in an accessible format 
- [x] Any preliminary recommendations/findings from the audit are captured and ready to inform subsequent ticket (Develop rough requirements for RS tables #8231)

## To do

- [x] Audit current Admin & Admin Tool tables
- [x] Audit current Sender tables
- [x] Audit current Receiver tables
- [x] Audit public website tables
- [x] Audit future feature tables (e.g. Programmer's Guide, Data Dashboard)

**Comment by etanb** [comment]
This is excellent! Please let me know if I can join any discovery meetings / be helpful in any way @jillian-hammer @audreykwr

**Comment by jillian-hammer** [comment]
I took a pass at writing this ticket and gave it 3 points.

cc @chris-kuryak

**Comment by jillian-hammer** [comment]
the design table discovery work is complete and captured within this [Mural](https://app.mural.co/invitation/mural/primedatainput6410/1677789052306?sender=u0c3cdba5126734aceb613229&key=7c59f374-11c2-4911-8dc5-5b389e432a5e).

the next steps are for design (@jillian-hammer) + content (@audreykwr) to share their findings and workshop a starting list of requirements for webx engineers to review – which is captured in: Develop rough requirements for RS tables #8231.
