### ISSUE TITLE
Table Content Discovery

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8278]
## Problem statement

Tables are used extensively across the ReportStream website, but use different styles and address different use cases. Prior to consolidating the table component into "One table to rule them all" (#8280), the design team needs to conduct an audit of all of the table instances to ensure that the new component will address the needs of tables across RS. Additionally, tables that don't yet exist (e.g, Programmer's Guide and the Data Dashboard) also have to be considered. Ultimately, this deeper understanding will better inform the subsequent synthesis and functionality work (captured in Develop rough requirements for RS tables #8231).

## What you need to know

- [Table Component Design Brief](https://docs.google.com/document/d/1ZT0YtNyPZSVcDh3cbWEG2PpowXGz91aPJwI6hlWjiA8/edit?usp=sharing)
- [Sister Ticket: Table Design Discovery #8278](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/8277)

## Acceptance criteria

- [x] Current table content elements are documented in an accessible format 
- [x] Any preliminary recommendations/findings from the audit are captured and ready to inform subsequent ticket (Develop rough requirements for RS tables #8231)

## To do

- [ ] Audit current Admin & Admin Tool tables
- [ ] Audit current Sender tables
- [ ] Audit current Receiver tables
- [ ] Audit public website tables
- [ ] Audit future feature tables (e.g. Programmer's Guide, Data Dashboard)

**Comment by audreykwr** [comment]
@chris-kuryak mostly took this from @jillian-hammer's work on #8277 because that was solid!

**Comment by audreykwr** [comment]
closing @chris-kuryak 

[Doc of findings here](https://docs.google.com/document/d/1iIYDRVxi-KQwjpotX3SL62WJwoZBANCeXWfu1v3L47g/edit?usp=sharing)
