### ISSUE TITLE
Sender data for onboarding remaining STLTs

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#8290]
## Problem statement

As the engagement team, we need sender data from Metabase for the remaining STLTS that we will onboard. Our goal is to provide these metrics in our outreach email. (ex. there are currently #  senders that are ready to send COVID data to Georgia Health Department). 

**STLTs not currently on boarded to RS (no previous engagement):** 
Arkansas Department of Health
Georgia Department of Health 
Kansas Department of Health
Kentucky Department of Health
Nebraska Department of Health
South Carolina Department of Health
Federated States of Micronesia
Marshall Islands

## What you need to know

The leads of the engagement team discussed this during our weekly meeting on 2.10.23. Although @brick-green will be OOO next week, the goal is to have Ott use this ticket as training for Kant. 

## Acceptance criteria

- [ ] We will have sender data for the remaining STLTS to be onboarded to RS

## To do

- [x] Brick to provide pseudo logic
- [ ] Ott to train Kant on this for onboarding

**Comment by brick-green** [comment]
Query pseudo code for Georgia. These can be run in metabase:


## Count by test type for GA in last 30 days
select LOINC code, test name, count(test name)
from covid_result_metadata
where (patient state = GA OR ordering facility state = GA)
    AND created at date > 30 days ago
group by LOINC code, test name

## Count by sender_id for GA in last 30 days
select count(*), sender_id
from covid_result_metadata
where (patient state = GA OR ordering facility state = GA)
    AND created at date > 30 days ago
group by sender_id

## Count by testing lab for GA in last 30 days
select count(*), testing lab
from covid_result_metadata
where (patient state = GA OR ordering facility state = GA)
    AND created at date > 30 days ago
group by testing lab
