### ISSUE TITLE
Support ADT A01 HL7 v2 data submissions on the UP

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#8304]
### User Story:
As an ETOR data sender, I want to be able to submit ADT A01 HL7 v2 messages to ReportStream, so they are relayed to ETOR.

### Description/Use Case
The UP is currently setup to ingest only ORU R01 per the Linux4Health library. We need to enable ADT A01, so ETOR submissions do not result in errors.

### Risks/Impacts/Considerations
* 

### Dev Notes:
* We are not going to work on converting any missing segments in this issue. We only care to accept ADT A01 messages regardless of how much data we can convert.
* Will need to setup Linux4Health to accept ADT A01. Use existing segments as needed per HL7 v2 spec for ADT A01.

### Acceptance Criteria
* The UP can accept sender submissions of ADT A01 HL7 v2 messages.
* The UP stores ADT A01 message data in a FHIR Bundle.

**Comment by avnieldravid** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8304?planning-poker) with Zenhub @arnejduranovic @carlosfelix2 @jack-h-wang @JessicaWNava @PatriciaPerozoUSDS @thetaurean @victor-chaparro
