### ISSUE TITLE
Allow sending single FHIR bundle to receiver using the UP

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#8305]
### User Story:
As a receiver, I want to be able to be sent FHIR bundles from ReportStream, so I can ingest the data as I want to.

### Description/Use Case
The UP is currently setup to send data as HL7 v2 only. We need to add functionality to send as FHIR.

### Risks/Impacts/Considerations
* I do not think there are any mechanisms to stop us from sending any kind of data, but make sure the FHIR data is sent correctly (e.g. validate the FHIR data in the SFTP folder)

### Dev Notes:
* You will need to look at the Translate function and add code to not convert that data.
* You will also need to make sure the item lineage is populated correctly.
* Right now we are only sending one bundle per message, so you may need to hard code something.

### Acceptance Criteria
* The UP can send a FHIR bundle to a receiver.
* The UP populates the lineage when sending data to a receiver as a FHIR bundle.

**Comment by avnieldravid** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8305?planning-poker) with Zenhub @arnejduranovic @carlosfelix2 @jack-h-wang @JessicaWNava @PatriciaPerozoUSDS @thetaurean @victor-chaparro

**Comment by arnejduranovic** [comment]
@jimmyfagan is this a duplicate?

**Comment by jimmyfagan** [comment]
Maybe not a duplicate exactly, but yea I covered this stuff in the other ticket, I think we can close this. The other ticket didn't specifically mention lineage, but I think that all worked seamlessly.

**Comment by jimmyfagan** [comment]
Closed this since the functionality was included in [this PR](https://github.com/CDCgov/prime-reportstream/pull/9261) for [this ticket](https://github.com/CDCgov/prime-reportstream/issues/9144).
