### ISSUE TITLE
UP can send OML HL7 v2 messages to a receiver

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#8306]
### User Story:
As an ETOR data receiver, I want to be able to receive OML HL7 v2 messages from ReportStream, so I process the data.

### Description/Use Case
The UP is currently setup to deliver only ORU R01 HL7 v2 messages. We need to enable OML, so ETOR submissions do not result in errors.

### Risks/Impacts/Considerations
* Most of the initial effort was about ORU R01. Is that event hard coded in places? 

### Dev Notes:
* We are not going to work on converting any missing segments in this issue. We only care to send some ADT A01 message regardless of how much data we can convert.
* Will need to setup our library to generate OML. Use existing segments as needed per HL7 v2 spec for ADT A01.
* Will be nice to make the HL7 type generated generic. Could we take in the class name in the config?  Can it be determined from the data itself? Should we?

### Acceptance Criteria
* The UP can send OML HL7 v2 messages to a receiver from a FHIR bundle that follows the HL7 v2 to FHIR mapping IG.
* The UP generates an error if a non-OML FHIR message is being translated to ADT A01 (makes this for any type incorrectly converted).
* Create new tickets for work to fully support OML sending

**Comment by avnieldravid** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8306?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @PatriciaPerozoUSDS @thetaurean @victor-chaparro

**Comment by avnieldravid** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8306?planning-poker) with Zenhub @jimduff-usds

**Comment by carlosfelix2** [comment]
OBE
