### ISSUE TITLE
Create a template for our kick-off calls with STLTs and Senders

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#8307]
## Problem statement

As the engagement team, we need a way to standardize some of our outreach effects to onboard STLTs and Senders effectively and rapidly. I'd like to initiate some standardization by creating templates/forms that we can use for all partners. 

## What you need to know

I've attached an example of the prep document that we used for BD Veritor. I would like to design a template similar to this to use for/on the kickoff calls.
- [BD Veritor Example](https://docs.google.com/document/d/1ZrUIoOVzBKxyDk9G2l6E9ZGWV4P62EuZ/edit?usp=sharing&ouid=101766109526781967347&rtpof=true&sd=true)

## Acceptance criteria

- [x] Standardized template/form that we can use on all kick-off calls

## To do

- [x] Determine what questions our engineers might need
- [x] User research info that would be beneficial
- [x] Determine what questions are common for kick-off calls
- [x] Format the document using the Outreach Plan as a model

**Comment by jakefishbein-navapbc** [comment]
Connected tasks:

- Create outreach email
- Create intake form and email
-Create mail merge in Kickoff template to bring in information from the form
-Create notifications in smart sheets to update internal stake holders
-Create kickoff process document

**Comment by jakefishbein-navapbc** [comment]
[Link to Template](https://docs.google.com/document/d/1C9xevCAcKQYNYPo-YzNGZHwbU2F-1eL3f93xYOPrvsg/edit?usp=sharing)

**Comment by lizzieamanning** [comment]
@jakefishbein-navapbc how is this different from the SOP?
