### ISSUE TITLE
Investigate effort needed to generate RADx MARS HL7 v2 compliant messages

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#8310]
### User Story:
As a receiver, I want to receive HL7 v2 data in the RADx MARS format, so I can process the data in a format I can support.

### Description/Use Case
The RADx MARS provides an implementation guide (IG) on data requirements for HL7 v2. We want to support this IG as it is required for some reveivers.

### Risks/Impacts/Considerations
* Are there any features we currently do not have that we need to fully support the IG?

### Dev Notes:
* See RADx MARS documentation [at this link](https://www.nibib.nih.gov/covid-19/radx-tech-program/mars/hl7v2-getting-started).

### Acceptance Criteria
* Document what is needed to support the RADx MARS IG for HL7 v2.
* Get buy-in from the team and OO on the steps to support the RADx MARS IG.
* Generate any issues to implement the RADx MARS IG.

**Comment by avnieldravid** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8310?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @PatriciaPerozoUSDS @thetaurean @victor-chaparro

**Comment by avnieldravid** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8310?planning-poker) with Zenhub @jimmyfagan @jimduff-usds

**Comment by PatriciaPerozoUSDS** [comment]
https://www.nibib.nih.gov/covid-19/radx-tech-program/mars/HL7v2-implementation-guide

Jim found this and we think this is the implementation guide we should be following

**Comment by JessicaWNava** [comment]
Created https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/8655 for assigning the work generated by this ticket.

**Comment by JessicaWNava** [comment]
Also created https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/8695 for assigning the work generated by this ticket.

**Comment by JessicaWNava** [comment]
Also created https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/8696 for assigning the work generated by this ticket, so 3 tickets so far

**Comment by bishoyayoub** [comment]
@JessicaWNava are we OK to close this item?
