### ISSUE TITLE
Design UP FHIR to CSV converter

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#8312]
### User Story:
As a STLT, I want to receive data in CSV format, so I can process the data as I want to.

### Description/Use Case
The UP currently only support HL7 v2 and soon FHIR data for sending to STLTs. We need to also support CSV.

One use case that has been brought up is described here: https://www.cdc.gov/std/program/STD-NETSSIMPLN-V5_2018Jan.pdf. Attachment A describes how the STD data is formatted in a spreadsheet. This is a flat file format that the CDC uses to get data about STDs and delivers it to programs.

### Risks/Impacts/Considerations
* May need some very special transforms depending on the receiver.

### Dev Notes:
* The COVID pipeline sends CSV data to some receivers.
* Will this be part of the library?
* Try to reuse the design for the other conversion.

### Acceptance Criteria
* Document the design for the FHIR to CSV converter.
* Get buy-in from our team, then the OO team on the design.
* Generate any issues required to implement the design.

**Comment by avnieldravid** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8312?planning-poker) with Zenhub @arnejduranovic @thetaurean @victor-chaparro @PatriciaPerozoUSDS @JessicaWNava @jack-h-wang

**Comment by avnieldravid** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8312?planning-poker) with Zenhub @jimduff-usds

**Comment by MichaelEsuruoso** [comment]
item not needed atm.
