### ISSUE TITLE
UP supports translation from FHIR of AOE questions

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#8320]
### User Story:
As a receiver, I want to have ask on entry (AOE) questions in the HL7 v2 data, so the data is complete.

### Description/Use Case
AOE questions are part of COVID reports. For HL7 v2, they show up as separate observations with specific LOINC codes. We need to convert those AOE questions into the proper HL7 v2 segments.

### Risks/Impacts/Considerations
* Need to make sure the AOE questions are part of the correct segments in the HL7 v2.
* There is a possibility the location of AOE questions will change in the future, but for now we will go with what we found in #8271

### Dev Notes:
* See sample AOE in #8271
* A list of AOE LOINC Codes and samples[ can be found here](https://doh.wa.gov/sites/default/files/legacy/Documents/1600/coronavirus//421-005-LabsReportingTestResultsAOEQuestions.pdf).
* AOEs belong to a specific group of ORC/OBR observations
* You will need a way to properly add the AOE questions into the HL7 v2 at the end of all other observations

### Acceptance Criteria
* The UP can translate AOE questions from a FHIR bundle to an HL7 v2 message.

**Comment by avnieldravid** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8320?planning-poker) with Zenhub @arnejduranovic @carlosfelix2 @jack-h-wang @JessicaWNava @PatriciaPerozoUSDS @thetaurean @victor-chaparro
