### ISSUE TITLE
Design: Design API Programmer's Guide on the RS Website

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8342]
## User story
As a sender, I need an accessible, updated, online Programmer's Guide, so that I can successfully connect to the ReportStream API.

## Background & Context
This Programmer's Guide ticket captures the final design  and documentation work needed to handoff to the WebX engineering team. The design effort leverages the work already completed in Wireframe the API Programmer's Guide #8481, and will fill in the remaining gaps (namely, pixel perfect documentation of new components, and other technical specs).

## What you need to know

- [Figma: Programmer's Guide Wireframes](https://www.figma.com/file/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=2112%3A21339)
- [Programmer's Guide Design Brief](https://docs.google.com/document/d/10hJwh0xOywdL-gbuj1YvHhMIWfz6ODtV7G9k7bXcMWE/edit?usp=sharing)
- [Programmer's Guide Content](https://docs.google.com/document/d/1xsxkr7EnnpbXo8CcfdDcUnIYNKuFzY1u/edit?usp=sharing&ouid=108375376459243880703&rtpof=true&sd=true)

## Acceptance criteria

**High fidelity design of new components**
- [x] Code snippet, in-line
- [x] Code snippet, multi-line
- [x] Tip callout
- [x] Prose style: H4
- [x] Prose style: Body (small)

**Documentation for WebX handoff**
- [x] Style guide of new components for WebX eng handoff
- [x] Annotated high-fidelity page template with spacing, type styles
- [x] Annotated wireframes for WebX eng handoff, outlining existing Trussworks components, external links, etc.
- [x] Location on RS website, IA structure

**Review**
- [x] Review with content 
- [x] Design lead (via tag in ticket)
- [x] Help WebEx engineering team scope the necessary engineering work and create tickets in #5814

**Comment by jillian-hammer** [comment]
@chris-kuryak I wrote this ticket and gave it 8pts. I recommend capturing the content finalization + review work in a separate ticket (cc @audreykwr).

**Comment by lizzieamanning** [comment]
@jillian-hammer looks great & agree with the points

**Comment by jillian-hammer** [comment]
I previewed this deliverable with the eng team and it fulfills their needs for a smooth handoff!

This is ready for content and design review! @audreykwr and @lizzieamanning can you give these a once over? did I miss anything? any inaccuracies/super off? 

- [Full prototype](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=3592-36212&scaling=min-zoom&page-id=3592%3A36210&starting-point-node-id=3592%3A36212) (design + wireframes, annotated)
- [Style guide](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=3592-38284&scaling=min-zoom&page-id=3592%3A36210&starting-point-node-id=3592%3A38284&show-proto-sidebar=1) for new components & type styles

**Comment by Andrey-Glazkv** [comment]
AI: to be reviewed by Audrey and Lizzy

**Comment by lizzieamanning** [comment]
@Andrey-Glazkv thanks for the bump! @jillian-hammer left a few minor comments, otherwise looks good to me.

**Comment by audreykwr** [comment]
Putting the content docs here. 

[Copy doc table format with design components noted](https://docs.google.com/document/d/1JLIddU8elkQji24JxjEeeL04smLLWI1Q/edit?usp=sharing&ouid=105539281535064771922&rtpof=true&sd=true)

[Traditional doc format](https://docs.google.com/document/d/1xsxkr7EnnpbXo8CcfdDcUnIYNKuFzY1u/edit#heading=h.b9hyc7d95oq4) Note: H tags in this doc do not currently match Figma components

**Comment by lizzieamanning** [comment]
@audreykwr how do you intend these two different docs being used? Is the first one the new format you were trying out?

**Comment by jillian-hammer** [comment]
hey @jpandersen87, feel free to review the links above ahead of the Friday hand-off call!
