### ISSUE TITLE
Implementation: Public Key Tool

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#8344]
**Background & Context**
The sender emails us two separate public keys. Then those are stored in the database under sender settings. (Currently stored on staging and prod.) Then we send them an email that they can start testing (authentication) and includes the API endpoint to point to. And link them to API Programmer's guide.This happens on almost every new sender (majority). Server-to-server auth.

This tool requires a sender's authenticated login.

**User story**
As a sender, I want to be able to send my public key to the RS database via RS website. 

**Link to design**

**Acceptance criteria** 
1. Reflects above design
2. Design QA

**Comment by chris-kuryak** [comment]
@lizzieamanning Can you give me more context on what this epic is for? We already have an epic for the Public Key Tool, so just want to know what makes this different.

**Comment by chris-kuryak** [comment]
Made on accident. Closing per alignment with @lizzieamanning
