### ISSUE TITLE
OH - Please resend file CDCPRIME_20230215083511 

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#8345]
## **Problem Statement**
Received an email from William Storm from OHIO stating that they had a connection issue needs the following file resent.

CDCPRIME_20230215083511

## **What you need to know**
Email from OH Receiver:
Overnight, ODH experienced a disk space issue on its SFTP server. As a result, over a 6-hr period, labs who submitted files either had connection issues and couldn’t send files or were successful, but the files received were incomplete, mostly as a 0 kb file. ODH apologizes for the inconvenience; however, action is now required by the sending laboratory.

## **Acceptance Criteria**
- Locate the correct file and confirm file was not sent to OH
- Once correct file is located, please resent to OH
- Let helpdesk know once completed to send confirmation to OH Receiver (William Storm)

## **To Do**
Assign to Engineer

## **Additional Comments**
Receiver is requesting that this be resent as soon as possible.

**Comment by oslynn** [comment]
File: CDCPRIME_20230215083511.hl7 is resubmitted to OH-DOH.ELR at following path:
"filePath": "CDC-ELR/ProdFiles",

**Comment by oslynn** [comment]
Done
