### ISSUE TITLE
Get instance of Storybook running locally with RS website

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8346]
## Problem statement

In essence, [Storybook](https://storybook.js.org/) is a showcase of all the coded-version of of our design components. For Design (note the capital D) to work well with engineering, they require "building blocks" so they don't have to redesign the wheel every time they create a new feature, do a bug bash or polish something. Currently we have no established component library or styleguide from an Engineering perspective that Design can work with which means they have to shoot-in-the-dark as to what is already coded and what is not. This greatly affects how well we can estimate things going forwards.

## Context

Here is a [link to our Figma "Master Components" page](https://www.figma.com/file/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=218%3A285&t=yTpCeDZCX5FTLg9J-0) (which is incomplete) but a good reference point of what we'd want to mirror in our Storybook instance.

We'd also want to implement full page mocks of some of our main pages, like the homepage, unauthenticated and authenticated, different states of components like banners and modals.

Some excellent examples of living Storybooks for inspiration:

- [The Guardian's Storybook Instance](https://5dfcbf3012392c0020e7140b-gmgigeoguh.chromatic.com/)
- [The BBC's Storybook Instance](https://www.bbc.co.uk/iplayer/storybook/index.html?path=/story/styleguide--colours)

## Acceptance criteria

- [ ] All Styleguide items included in Storybook local instance
- [ ] All Components items included in Storybook local instance

_Caveat: all of the below very intentionally MUST include not just our customized resources, but anything we use from USWDS and beyond. Design, and anyone else looking at our Storbook, need to know EVERYTHING we're potentially working with._

**Styleguide**
This would be an overview of the fundamental building blocks of our site that would include:

- Colors
- Typography
- Spacing and Formatting
- Icons

**Components**
This would be an extensive overview of all the components in use across our site, from base USWDS modals and how we implement them, to customized table components:

- Table
- Modal
- Link
- Checkbox
- Label
- Textinput
- Dropdown
- Accordion
- Button
- DateRangePicker
- Tooltip
- Alert
- Form
- Banner
- Title

_This list is not-exhaustive_

**Add Ons**

We may want to explore a few add-ons to our Storybook that would be extremely useful including:

[Accessibility](https://storybook.js.org/addons/@storybook/addon-a11y): evaluates the ally accessibility of our Storybook components and what levels of compliance they are in.

[Figma Designs](https://storybook.js.org/addons/storybook-addon-designs): a plugin that allows us to easily embed Figma designs within Storybook.

**Comment by stephenkao** [comment]
@etanb We chatted about this before, but what do you think about making this ticket just about getting an instance of Storybook running locally with an example story or two?  I think the notes you added here are excellent, but they touch on longer-term items whereas I intended this ticket to just be the initial configuration for getting Storybook included in ReportStream.

**Comment by stephenkao** [comment]
@etanb Heads up: I moved the description you added here to the Storybook epic since it outlines more of an overarching approach rather than an individual ticket.  Also for transparency, I'm going to assign myself to this ticket since I pushed up a quick local configuration pull request last week.

**Comment by chris-kuryak** [comment]
Not deployable. Done and can be closed.
