### ISSUE TITLE
Content audit planning

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#8352]
## Problem statement

An audit helps determine how what we currently have or have planned to build is working toward our goals and our users' goals. Based on previous research work, we need to determine the most strategic focus and plan for the audit.

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]
- [Workshop synthesis ticket](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/8178)
- [Mural of general work roadmap/misc notes](https://app.mural.co/invitation/mural/nava4113/1673278109303?sender=uc55a7af3b66977fba12f5528&key=27b02b81-58ce-4f9b-a734-4aab2802ad5b)

- [Ticket for workshops](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/8143)
- ...

## Acceptance criteria

- [x] Determine scope and priorities to review
- [x] Tool for evaluation chosen and set up (google sheet, airtable, mural etc)
- [x] Next tickets created

## To do

- [ ]

**Comment by chris-kuryak** [comment]
@audreykwr Added 'Design' label. Otherwise looks good!

**Comment by audreykwr** [comment]
@chris-kuryak going to go ahead and close this
