### ISSUE TITLE
Conduct content audit

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#8355]
## Problem statement

We need to know how our current site and plans are meeting our users' needs and RS goals. An audit will examine that based on previously IDed needs and priorities.

## What you need to know

- [General planning doc](https://docs.google.com/document/d/1WjaSCEqaZkJ0Xmkll-rllc219S9nT7B1vfyRtN9R0Vc/edit?usp=sharing)
- [Workshop synthesis deck with planning notes](https://docs.google.com/presentation/d/1ljFEf3dUm3z2cOrgikiXoCemIoqDRWWRnMz4vyue--Y/edit#slide=id.g11de60fb153_0_1358)
- [Mural of general work roadmap/misc notes](https://app.mural.co/invitation/mural/nava4113/1673278109303?sender=uc55a7af3b66977fba12f5528&key=27b02b81-58ce-4f9b-a734-4aab2802ad5b)

## Acceptance criteria

- [x] Scope examined through determined heuristics
- [x] Tickets created for next steps

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@lizzieamanning @chris-kuryak Created this ticket as a follow up to planning the audit. More detail can probably be added after that planning one. My plan is to at least start this this sprint, but that depends on how the planning ticket goes and the scope that is determined

**Comment by chris-kuryak** [comment]
Sounds great @audreykwr 
So you are saying that this will be informed by the Planning ticket within this epic, right? So we'll keep this in the "new" column until the ticket fully written after the planning ticket is finished. Am I understanding you correctly here?

Adding Design label and making contingent on Planning ticket.

**Comment by audreykwr** [comment]
Yeah, after planning there will be a little more detail on scope and pointing

**Comment by audreykwr** [comment]
@chris-kuryak closing!
