### ISSUE TITLE
Software Engineer Access/Setup for Angela DeGolier

### ISSUE THREAD

**Issue by adegolier** [CDCgov/prime-reportstream#8360]
Need 
- [ ] regular Azure access
- [ ] SU
- [ ] VPN 
- [ ] Keybase (adegolier)

I think? Not sure what all you need for this, but presumably you'll need my CDC user which is UOQ2. If there's anything else, please let me know!

**Comment by LaFreda1** [comment]
@jeremy-page checking to see if we can get some traction on this ticket. Please let me know if we can provide anything to help. Thanks!

**Comment by jeremy-page** [comment]
Please make sure we know the ticket is in the queue.

**Comment by adegolier** [comment]
That was probably my fault. I know I posted the original one (that went to the black hole) to Slack, but I may not have re-posted this one. Is that the best way to let y'all know that the ticket is in the queue or is there something else we should do in the future?

**Comment by LaFreda1** [comment]
@GilmoreA6 Kant and Jamie will need this same access, correct? If so, I will start a ticket for them

**Comment by adegolier** [comment]
@LaFreda1 Do they have CDC access? Because if not, they'll need that first.
