### ISSUE TITLE
Engagement team needs data on Senders/STLTs

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#8362]
## Problem statement

As the engagement team, we need data on our STLTs like
1. How many senders are sending data for that PHD
2. What's the volume of data we are receiving for each PHD

## What you need to know
The goal is to eventually use these data to apply to our internal SLAs and apply a system that can be based on these metrics. 
 [Links to documents, workflows, or list of key people and contact info]

## Acceptance criteria

- [ ] We can interpret sender/STLT data to make informed decisions as the engagement team

## To do

- [ ] Brandon to find these data through cross-functional efforts

**Comment by brandonnava** [comment]
Data collected
