### ISSUE TITLE
Create hooks for Check Settings Commands

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8368]
## Problem statement
To fully move from rest-hooks to react query, we need to add the new hooks into every API area. This ticket is to add react-query hooks for Check Settings Commands API area.

## What you need to know
- Creating the hooks and tests is the first step, followed by adding those hooked into the pages, which will be on a following ticket
- Can refer to #6528 branch once merged for examples on hook implementation

## Acceptance criteria

- [ ] Create all necessary creation, read, update, deletion hooks in the Check Settings Commands API area
- [ ] Ensure every hook has a complimentary test to go with it

## To do
- [ ] ...

**Comment by KeithNava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Web-Experience-607d9d5e68b95200150fec37/issues/CDCgov/prime-reportstream/8368?planning-poker) with Zenhub @etanb @jpandersen87 @penny-lischer

**Comment by penny-lischer** [comment]
@KeithNava I need more context around this before estimating.

**Comment by KeithNava** [comment]
@penny-lischer not a prob, take your time.

**Comment by jpandersen87** [comment]
Superseded by #14341
