### ISSUE TITLE
Create hooks for Lookup Tables API area

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8377]
## Problem statement
To fully move from rest-hooks to react query, we need to add the new hooks into every API area. This ticket is to add react-query hooks for Lookup Tables API area.

## What you need to know
- Creating the hooks and tests is the first step, followed by adding those hooked into the pages, which will be on a following ticket
- Can refer to #6528 branch once merged for examples on hook implementation

## Acceptance criteria

- [ ] Create all necessary creation, read, update, deletion hooks in the Lookup Tables API area
- [ ] Ensure every hook has a complimentary test to go with it

## To do
- [ ] ...

**Comment by jpandersen87** [comment]
Superseded by #14341
