### ISSUE TITLE
Updated API guide PDF

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#8391]
## Problem statement

Before we can get an updated guide on the site, engagement needs a new pdf version to use for onboarding in the meantime.

## What you need to know

- [Edit copy with full suggestions/comment threads from working sessions](https://docs.google.com/document/d/1S4SlRp5nznuymnCr1nOwhQYDKYt2OqTX/edit#)
- [Clean copy with edits applied and only design notes/misc in comments](https://docs.google.com/document/d/1S4SlRp5nznuymnCr1nOwhQYDKYt2OqTX/edit#)
- [Mural working space]
- ...

## Acceptance criteria

- [x] New edits formatted for PDF readability
- [x] Reviewed by engagement 
- [x] PDF send to eng for upload -- Ticket #8641 

## For Reference

- Old: [ReportStream-Programmers-Guide-v2.3-updated.pdf](https://github.com/CDCgov/prime-reportstream/files/10913456/ReportStream-Programmers-Guide-v2.3-updated.pdf)
- New: [ReportStream-Programmers-Guide-v3.0.pdf](https://github.com/CDCgov/prime-reportstream/files/10913461/ReportStream-Programmers-Guide-v3.0.pdf)

**Comment by audreykwr** [comment]
@chris-kuryak this is ready to hand off to be uploaded. how would I go about doing that? would you create a ticket for end?

**Comment by chris-kuryak** [comment]
Created ticket for engineering #8641 . Closing this ticket.
