### ISSUE TITLE
[Manage Public Key] Error message

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8397]
## Problem statement
The sender emails us two separate public keys. These keys are stored in the database under sender settings. Then we send them an email that they can start testing (authentication) and includes the API endpoint to point to and link them to API Programmer's guide.
This happens on almost every new sender and is a manual process.

## What you need to know
https://www.figma.com/file/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=2167-21742&t=hrkPPWw0VtqV0v9V-0

## Acceptance criteria
[ ]  Display error if/when an error occurs when submitting a senders public key
[ ] Try again button returns the user back to the Manage Public Key page

## To do

- [ ] Add Try again button
- [ ] Unit tests

**Comment by penny-lischer** [comment]
Will be covered as part of #8398
