### ISSUE TITLE
Add API endpoint for Senders to submit new public keys

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8399]
## Problem statement
We need to add a new API endpoint to allow Senders to add and update their public keys for server-to-server communication with ReportStream.

## What you need to know

 - [Server2ServerAuthentication.kt](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/tokens/Server2ServerAuthentication.kt) (most notably [FindSenderKeyInSettings](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/tokens/Server2ServerAuthentication.kt#L199)) contains related logic for dealing with the public key.
- [`validateRequest` in RequestFunction.kt](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/azure/RequestFunction.kt#L68) has related logic for receiving uploaded files.

## Acceptance criteria
As a non-Sender: 
- [ ] The new API endpoint returns a 401

As a Sender (or admin impersonating a Sender):
- [ ] A .pem file can be submitted to the new API endpoint as the request body
- [ ] The Sender's key in their `setting->>'values'` is updated with the key
    - [ ] If the Sender doesn't already have a key of the same algorithm (`kty`), the new key is appended to the keys array (NOTE: will be `null` if the Sender never set up their key)
    - [ ] If the Sender already has a key of the same algorithm (`kty`), the existing key is replaced with the new one
- [ ] `setting` history should be maintained (see [`putSetting`](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/azure/SettingsFacade.kt#L184))
- [ ] On insert/update success, return a 200

**Comment by jimduff-usds** [comment]
- The system allows for multiple scopes per org.sender and multiple keys per scope - how will all that work?  The phrase "replace the existing key" doesn't make sense in that context.
- Why not just use the existing API endpoint that lets you edit anything in a setting?  Then you don't need any new API work, and you can handle the complexities of multiple keys per scope.
- If you do plan too create a new endpoint - then, are we going to have a new endpoint for CRUD on _every_ field in a setting?

**Comment by stephenkao** [comment]
Closing in favor of [#8489](https://github.com/cdcgov/prime-reportstream/issues/8489) and [#8472](https://github.com/cdcgov/prime-reportstream/issues/8472), which will be handled by the Platform team!
