### ISSUE TITLE
Research operations 

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#8416]
**Goal**
To align on approaches to various research processes

**Background**
We are a new and growing design team that spans across three different scrum teams, so it's important we align on process and structure for visibility, clarity, and consistency.

**Approach**
We have prioritized some of the activities and processes that need definition (see Mural [here](https://app.mural.co/t/nava4113/m/nava4113/1673916436749/fa6b9fa1649bfcc743f872ac3691460172a7141e?sender=u791b7d4d34761ac59b672214)), reflected by the ticket work inside this epic.

We will focus this first chunk of work on defining the norms, process, and tools for 
1. Recruiting
2. Scheduling
3. Conducting research (primarily usability tests and group feedback sessions)

**Assumptions**
This is ongoing work to be iterated on as we continue to grow and flesh out our processes.

**Out-of-scope**
Design processes. This work will be defined in epic #8335, Design Operations 

**Dependencies and risks**
This work could go on forever! We need to determine how far we want to take this chunk of work.

**Open questions**

**Links & resources**
[Mural](https://app.mural.co/t/nava4113/m/nava4113/1673916436749/fa6b9fa1649bfcc743f872ac3691460172a7141e?sender=u791b7d4d34761ac59b672214)

**We will be successful if...**

Our team agrees that the processes we've outlined help make our workflow and collaboration more effective and efficient.
All design team members understand the processes we've outlined and are able to implement the processes in their everyday work

**Comment by MichaelEsuruoso** [comment]
epic completed
