### ISSUE TITLE
IL - Please send backlog (60 days) for SimpleReport Sender - Baha Labs Data

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#8431]
## **Problem Statement**
We received a request via ReportStream inbox from the State of IL (Charlotte Picard) to send a backlog of data (60 days) for Baha Labs.  

## **What you need to know**
This data is being sent via SimpleReport. The lab is Baha Labs and the CLIA number is 14D2253890.

Previously IL was not sending this data however the filter is being updated and this data should then be going to IL.

## **Acceptance Criteria**
- Locate all the data for Baha Labs being sent from SimpleReport and resend to IL State/Receiver for the past 60 days.
-Once completed please let helpdesk know so that we can alert the Receiver.

## **To Do**
-NA

## **Additional Comments**
If applicable, add screenshots, links, etc. to further explain the ticket

**Comment by GilmoreA6** [comment]
Identified two report IDs :
52c8d88f-c6f9-4b55-a59a-1735c556465c
a6dd706b-e2cb-4405-9211-5b03dfa6b2c1

from Baha Labs. Manually resent files to IL on 02/28/13
