### ISSUE TITLE
UP's LIVD Lookup FHIR custom function must reside outside of conversion library

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#8434]
### User Story:
As a developer, I want to separate code that is RS specific from the more generic conversion library, so when the library is moved to its own repo then it will not be dependent on RS code.

### Description/Use Case
We need to make sure we separate code that is specific to RS from the conversion library.

### Dev Notes:
* Suggest to add to the custom context to pass in a class that contains the extra functions needed.
* You will need to create an interface for this class. Suggest to follow the method signature required for the FHIR Path library (see CustomFHIRFunctions.kt)
* Suggest following the same pattern of code as CustomFHIRFunctions.kt.

### Acceptance Criteria
* The UP's LIVD Lookup custom FHIR Function code resides outside the FHIR to HL7 v2 conversion library.
* The UP's FHIR to HL7 v2 conversion can use the LIVD Lookup custom FHIR Function.
* The FHIR to HL7 v2 library can be extended to use a provided set of custom FHIR functions.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8434?planning-poker) with Zenhub @arnejduranovic @carlosfelix2 @JessicaWNava @jimmyfagan @mkalish @PatriciaPerozoUSDS @thetaurean @victor-chaparro
