### ISSUE TITLE
UP's LIVD Lookup common function arguments can be implemented more cleanly

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#8436]
### User Story:
As a developer, I want all the code be be more readable and maintainable.

### Description/Use Case
This ticket was based off this comment: https://github.com/CDCgov/prime-reportstream/pull/8160/files#r1113262631 regarding the "find" function. All the parameters in the find function are optional but do not default to anything. Search for calls to this function and you will see us passing "null" for a lot of the parameters. This type of implementation is easily broken when new parameters are added and hard to maintain. 

### Dev Notes:
The builder pattern, as described here https://www.baeldung.com/kotlin/builder-pattern, makes the code referenced above much more maintainable and readable.

### Acceptance Criteria
- [x] We no longer have to pass "null" when not using parameters of LivdLookup.find 
- [x] LivdLookup.find is more maintainable and open to future modifications
- [x] The Legacy pipeline's LIVD Lookup mappers still works as expected.

**Comment by avnieldravid** [comment]
For Dev notes, it might be useful to have the specific function

**Comment by avnieldravid** [comment]
Add link to Kotlin Builder pattern

**Comment by avnieldravid** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8436?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimduff-usds @jimmyfagan @PatriciaPerozoUSDS @thetaurean @victor-chaparro

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8436?planning-poker) with Zenhub @carlosfelix2 @mkalish

**Comment by bishoyayoub** [comment]
This needs to be refined further - we are taking it back to grooming.

**Comment by jack-h-wang** [comment]
Question - instead of the builder pattern, can we provide default parameter values and adjust the calls to use named parameters?

**Comment by arnejduranovic** [comment]
> Question - instead of the builder pattern, can we provide default parameter values and adjust the calls to use named parameters?

When implementing builder pattern in Kotlin, both of these methods are used.

**Comment by arnejduranovic** [comment]
I've updated this ticket to not be coupled to builder pattern, although I still provide builder pattern tips in the dev notes.
