### ISSUE TITLE
Feedback loop for currently active senders and receivers

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#8439]
## Background and Context 
The engagement team would like to develop a feedback loop for currently active senders and receivers. We have an established meeting cadence with CA and CO and would ultimately like to establish this type of communication with all active senders and receivers.

## Value Proposition 

- Establishing a clear feedback loop with users creates efficiencies as it allows us to gather feedback regularly instead of planning large research efforts 
- It also provides value to the user and our client as it should help us ensure we aren't duplicating communications or asking the same questions, but instead, building on our knowledge of different users and building our relationships with them

## Impacted Objectives and Key Metrics (OKRs) 
Supports the 2023 Objective: Human centered design informs the product strategy

## In Scope 
TBD

## Out of Scope 
Outreach to new senders/receivers or senders/receivers who have not yet completed the onboarding process 

## Users 
Onboarded senders & receivers

[Link to Feedback Loop Document](https://docs.google.com/document/d/1HyepRJpIVIMKDESb3csXH4tXmsPr3_mxoZ6RAjUfExk/edit#)

**Comment by jakefishbein-navapbc** [comment]
@LaFreda1 In the To Do section, what does "Tier information" refer to?

**Comment by LaFreda1** [comment]
This refers to the discussion that we had during our SLA call. Brandon is currently doing the work to figure out the data volume from our current senders and receivers. We will use that info the create a "tier" system for the STLTs based on how much data we receive from them. @jakefishbein-navapbc

**Comment by LaFreda1** [comment]
This refers to the discussion that we had during our SLA call. Brandon is currently doing the work to figure out the data volume from our current senders and receivers. We will use that info the create a "tier" system for the STLTs based on how much data we receive from them. @jakefishbein-navapbc

**Comment by jakefishbein-navapbc** [comment]
@LaFreda1 @brandonnava would you please attach any files that would be helpful in defining and scoping this ticket?

**Comment by brandonnava** [comment]
Sender data per STLT in the outreach doc: https://docs.google.com/document/d/1sKVu6i8mjy3U-dQeXlNG7y5wgXR6tcoe/edit?usp=sharing&ouid=111339355923815956950&rtpof=true&sd=true

**Comment by lizzieamanning** [comment]
@LaFreda1 @brandonnava Wanted to clarify a point in this epic with you:
"We have an established meeting cadence with CA and CO and would ultimately like to establish this type of communication with all active senders and receivers."

Is this right? Does the engagement team want to be meeting regularly with each STLT and sender? If so, how regularly? It may help to flesh this scope out a bit more (together!)

**Comment by brandonnava** [comment]
@LaFreda1 do you have a cadence in mind? I was thinking @jakefishbein-navapbc would have a better idea of what would be appropriate after doing a few feedback sessions and getting a feel for the types of questions and concerns that come up. My gut check assumption is reaching out once a quarter or bi-annually

**Comment by LaFreda1** [comment]
@brandonnava @lizzieamanning Quarterly is fine.

**Comment by jakefishbein-navapbc** [comment]
@LaFreda Howard ***@***.***> @Brandon Canniff
***@***.***> @Lizzie Manning ***@***.***> I'm
wondering if the engagement panel that USDS wants to establish overlaps
with this and could be leveraged to support this work.

**Comment by brandonnava** [comment]
Possibly! Do you have more info on that panel initiative? @jakefishbein-navapbc

**Comment by brandonnava** [comment]
Adding an ask for feedback calls with STLTs from sprint planning. With NHE ending soon we want to include in the check in calls with STLTs what type of covid results they want to accept and filter out (ie positive results only, no OTC, etc)

**Comment by jakefishbein-navapbc** [comment]
@Brandon Canniff ***@***.***> Unfortunately, I don't. I am
meeting with Drew today so I should be able to get more context.
