### ISSUE TITLE
Reorganize HL7 mapping files into common areas

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#8445]
### User Story:
As a developer, I want to have the HL7 mapping files organized, so I can find what I need fast.

### Description/Use Case
With the addition of the ADT A01 schema, some schema files are now common. Need to reorganize the files to show what is common and what is not.

### Dev Notes:
* Focus on what is common now and keep segments only used in ORU R01 in that area.

### Acceptance Criteria
* The FHIR to HL7 v2 conversion schema files are organized with the common files in a common area.

**Comment by avnieldravid** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8445?planning-poker) with Zenhub @jimduff-usds @jimmyfagan @arnejduranovic @jack-h-wang @JessicaWNava @PatriciaPerozoUSDS @thetaurean @victor-chaparro
