### ISSUE TITLE
BUG: UP Submission History reports "receiving" when data goes to no receivers

### ISSUE THREAD

**Issue by jack-h-wang** [CDCgov/prime-reportstream#8451]
## User Story:

As an administrator, I want the Submission History overall status to be able to indicate that a report was not delivered to any receivers so that the correct status is reported.

## Description/Use Case

The submission history currently reports an overall status of "receiving" in the instance a report has no receivers. It does this in two distinct cases:

- Data hasn't been processed yet (common in async submissions)
- Very rare: No data matches any geographical location.

At the moment the function does not distinguish between these cases. This needs to be changed so that the overall status returned in the Submission History reflects what actually occurred.

## Risks/Impacts/Considerations

- The existing behavior for when data is not processed yet needs to be preserved.

## Dev Notes

- As of #7545 the UP routing function adds a "none" event in the case of the data having no receivers. This is also reflected in the "next action" of the "routing" event.
- As of #9224 some additional changes were made, including setting the item count to 0 in the "none" event.

## Acceptance criteria

- The Submission History reports an overall status of "not delivering" when UP routing has determined there are no receivers.
- The Submission History reports an overall status of "receiving" when data is still waiting for routing to start.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8451?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimmyfagan @thetaurean @victor-chaparro

**Comment by mkalish** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8451?planning-poker) with Zenhub @mkalish
