### ISSUE TITLE
Publish "Release Notes" - March 2023

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8464]
## Problem statement
As a user, I would like to know what features, bugs, other user facing updates have been made to ReportStream product.

## Procedure
https://docs.google.com/document/d/1vAiOJlfRMvJPRER3cr9Kr4lQ2-_ybNucJt28kI3fl1I/edit

## Acceptance criteria

- [x] New Web Experience Items added as a comment
- [x] New STLT's finished onboarding this month added as a comment
- [x] New Engagement Items added as a comment
- [x] New Platform Items added as a comment
- [x] Release Notes text (in ticket description) updated with all release notes
- [x] QA from Content before publishing
- [x] Experience team published to RS website on [Release Notes](https://reportstream.cdc.gov/product/release-notes) page

## Release Notes Text
**Improvements**

Usability: Widescreen grid containers are now shown on the [daily data](https://reportstream.cdc.gov/daily-data) and [submissions](https://reportstream.cdc.gov/daily-data) pages. Widescreen grid containers allow the user to see more data on wider screens.

You can also view release notes on [Github](https://github.com/CDCgov/prime-reportstream/releases).

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
From @avnieldravid: No March release notes from Platform team.

**Comment by chris-kuryak** [comment]
From @avnieldravid: No March release notes from Platform team.

**Comment by chris-kuryak** [comment]
From WebX:
#8026: Widescreen grid containers now shown on the [daily data](https://reportstream.cdc.gov/daily-data) and [submissions](https://reportstream.cdc.gov/daily-data) pages.

**Comment by chris-kuryak** [comment]
From Engagement:
No new STLTs. No release notes to share.

**Comment by Andrey-Glazkv** [comment]
Updated.
Sent for review.

**Comment by audreykwr** [comment]
1 question and 1 edit:
1) Why is the TOS update here two months in a row? It was completed last month right? Or is there something new that happened this month we should mention about that?
2) edit: 
Improvements
Usability: Users can now see more data on wider screens. Tables on Daily Data (for public health departments) and Submissions (for testing facilities) have been updated with widescreen grid containers.

**Comment by chris-kuryak** [comment]
@Andrey-Glazkv 
See Audrey's notes above.
In regards to the first one, the Terms of Service has not been two months in a row, so that section should be removed.

**Comment by audreykwr** [comment]
Still missing some edits per my previous comment. It should say:

Usability: Users can now see more data on wider screens. Tables on Daily Data (for public health departments) and Submissions (for testing facilities) have been updated with widescreen grid containers.

**Comment by chris-kuryak** [comment]
@Andrey-Glazkv I see Audrey's comment above. Can we get this ready for deployment by Tuesday?

**Comment by Andrey-Glazkv** [comment]
That is fixed - should be good to go.
