### ISSUE TITLE
PA - PW expiring - EXPIRES March 5

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#8467]
## **Problem Statement**
PW resets from PA that came in via ReportStream

## **What you need to know**
New issue, here are the users: 
pphlUSDSewsprod
achdUSDSewsprod
bchdUSDSewsprod
mcophUSDSewsprod
cchdUSDSewsprod

## **Acceptance Criteria**
PW's will expire in 10 days and therefore new pw must be created to close.

**Comment by brick-green** [comment]
@GilmoreA6 and I reset the passwords
