### ISSUE TITLE
[SPIKE] Investigate Chromatic for hosting Storybook

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8468]
## Problem statement

[Chromatic](https://www.chromatic.com/) is a tool for hosting and publishing different versions of a given repository's Storybook, and they offer [a sponsorship](https://www.chromatic.com/docs/open-source#:~:text=Chromatic%20sponsors%20open%20source%20component,workflow%20out%20of%20the%20box.) for open source projects.

Chromatic would give us the benefits of spinning up our own production Storybook instance without needing to maintain hosting or GitHub actions to publish changes.

## What you need to know

@stephenkao has reached out to add Chromatic to the prime-reportstream repository and to query about whether or not we quality for the open source sponsorship.

## Acceptance criteria

- [x] We determine whether or not we can use OSS Chromatic -- if so, we can initialize it as part of this ticket

**Comment by stephenkao** [comment]
FYI @etanb and @chris-kuryak.  Also, I didn't point this ticket because the outcome is largely dependent on what the two contacts say about using Chromatic.  Just wanted to track it as something that's underway!

**Comment by stephenkao** [comment]
Update: We're not eligible for the OSS sponsorship.  There aren't hard criteria for meeting the requirements, but it's based on rough numbers of contributors, downloads, and overall usage.  In lieu of that, I think we can test out the limits of the free version if/when the Chromatic app gets added to our project and see how it goes.

**Comment by chris-kuryak** [comment]
We have determined that CDC allows usage of Chromatic per @stephenkao
