### ISSUE TITLE
Implement ReportStream Key Management API MVP

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#8472]
## Problem statement

As a report stream sender, I want the ability to **upload an API key** on the ReportStream website for the `orgname.*.report` scope without having to contact anyone. 

### Design
See linked epic for design document and more information. We will need to implement the following endpoints to support the MVP (per the figma design document):
1. Endpoint to create a key and return list of scopes with their keys or error message.
  - `POST apiKey` - This endpoint should take in: `orgName`, `scope`, and `kid` as required query parameters AND a .pem file in the body
  - This endpoint should verify the .pem contains only a public key
2. Endpoint that will return a list of scopes with their keys, or an empty list. The frontend can call this to see if there are any keys for the organization or not. This endpoint should return the same thing as endpoint 1 (in the case of success)
  - `GET apiKeys` - This endpoint should take in: `orgName` as the only parameter, also required

#### Authentication/Authorization

the proposed API key endpoints should use OKTA authentication. Currently `UpdateReceiver` and `UpdateSender` in `SettingsFunctions.kt` use `OktaAuthentication.checkAccess` but this is deprecated.

Instead, we should look to use `AuthenticatedClaims.authenticate` for authentication and `checkAccessAuthorizationForOrg` for authorization. Note that `checkAccessAuthorizationForOrg` is hardcoded to run `authorizedForSendOrReceive` which checks if a user can send or receive. We may want to create a new scope for API key creation?

### use case 1: create key
A sender will generate a .pem file manually and then upload it to the site. Once the user submits it, RS will add the key to the `keys` section of the organization settings. See linked epic for more details.

### use case 2: check if key exists
A sender will go to a page in RS that will tell them if they have at least one key associated with one sender.

### Current Process

To set up a key on an environment, these are the steps. Look at the "addKey" code and see how it is done there, we basically want the same thing to happen when you hit the new API we are creating.

1. Create a Key on your machine. The system supports two types of key types, EC (Elliptic Curve) and RSA (RFC 3447).
	1. `openssl genrsa -out my-rsa-keypair.pem 2048`
	2. `openssl rsa -in my-rsa-keypair.pem -outform PEM -pubout -out my-rsa-public-key.pem`
2. `./prime sender addkey --env staging --name simple_report.csvuploader --public-key ~/.ssh/id_rsa/my-rsa-keypair.pem --scope simple_report.csvuploader.report --doit`

Now that a key is in the system, you can request a token from ReportStream:
- `./prime sender reqtoken -e staging --private-key ~/.ssh/id_rsa/my-rsa-keypair.pem --scope simple_report.csvuploader.report --name simple_report.csvuploader`

### Security Implications
**AFTER THE MVP**, we need to limit the number of keys a user can add. Someone is going to put addkey in a loop and we'll end up with thousands or even millions of keys. Maybe limit to two to allow for key rotation. When a user hits the addKey endpoint, we need to check if they are at their key limit and, if they are, return an error message that indicates they need to delete an existing key first.

**FOR THIS MVP/TICKET**, we will just override the `orgName.*.report` scope in the organization object with the key being sent, this covers the case of having thousands of keys.

## Acceptance criteria

- [ ] Created API to create a key.
- [ ] Created API to get list of keys for an organization.
- [ ] Created tests/verified code coverage.
- [ ] Notified experience team

**Comment by snesm** [comment]
I believe we need to limit the number of keys a user can add.  Someone is going to put `addkey` in a loop and we'll end up with thousands or even millions of keys.  Maybe limit to two to allow for key rotation.

This implies that there needs to be `delkey` or logic to handle overwriting keys as well.

**Comment by arnejduranovic** [comment]
> I believe we need to limit the number of keys a user can add. Someone is going to put `addkey` in a loop and we'll end up with thousands or even millions of keys. Maybe limit to two to allow for key rotation.
> 
> This implies that there needs to be `delkey` or logic to handle overwriting keys as well.

This sounds good to me. @stephenkao @chris-kuryak this may have an effect on your MVP design. Or, you could just throw an error saying "you have too many keys, sorry" and not allow an option to delete a key for the MVP, but that sounds bad to me. I propose we support del functionality for the MVP and also update the UI to include the ability to delete keys and show an error message when a user tries to create a key but they are already at their limit.

**Comment by stephenkao** [comment]
@snesm @arnejduranovic Thanks for the feedback!

I'd be in favor of overriding the existing key for the `orgname.*.report` scope each time a user successfully inserts a new key in an effort to keep things simple for now. 
 We'd talked about the possibility of a more fully featured key management system in the future, and in my mind that'd be a better time to allow for and limit multiple keys since there'd be more transparency to the user in that case.  We only have 22 Senders with keys stored in the database, and my feeling is that we can manually update if someone needs to have multiple active keys for whatever reason.

@chris-kuryak What are your thoughts about this?

**Comment by chris-kuryak** [comment]
@stephenkao @arnejduranovic 
Thanks for collaborating on this.
> I'd be in favor of overriding the existing key for the orgname.*.report scope each time a user successfully inserts a new key in an effort to keep things simple for now.
> We'd talked about the possibility of a more fully featured key management system in the future, and in my mind that'd be a better time to allow for and limit multiple keys since there'd be more transparency to the user in that case. We only have 22 Senders with keys stored in the database, and my feeling is that we can manually update if someone needs to have multiple active keys for whatever reason.

I am aligned with this. Nice work y'all!

**Comment by mkalish** [comment]
@stephenkao Arnej and I were chatting and wanted to confirm that you would be okay with an implementation with an endpoint that accepts text as content body rather than actual file.  This lines up better with existing patterns in the API and would requires less of a refactor lift.  I've included a screenshot of what the request would look like in Postman for reference.

<img width="749" alt="Screenshot 2023-03-14 at 10 14 58 PM" src="https://user-images.githubusercontent.com/1225895/225187302-8f21d41c-f7c5-4b12-958f-f9d78f9b64c1.png">


cc/ @arnejduranovic

**Comment by stephenkao** [comment]
@mkalish @arnejduranovic Sure, that shouldn't be a problem -- we were more concerned about making it look like the user's uploading a file for their convenience than actually having to upload a file.  Apologies for the miscommunication on my part!  But for my own edification, you're talking about just reading `request.body` as we're doing [during file validation](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/azure/RequestFunction.kt#L122)?

cc @penny-lischer who's working on the front-end side of this.  We can just use the [`text` function](https://developer.mozilla.org/en-US/docs/Web/API/Blob/text) (as we're doing [in FileHandler.tsx](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/components/FileHandlers/FileHandler.tsx#L153)) and pass that as the POST body.

**Comment by mkalish** [comment]
@stephenkao Yep, that looks right to me!

For reference, here is the PR that is implementing this https://github.com/CDCgov/prime-reportstream/pull/8678

**Comment by stephenkao** [comment]
@mkalish Looking great to me!  Many thanks to you (and @arnejduranovic!) for circling back on all this 🙏

**Comment by avnieldravid** [comment]
@mkalish let's check in on this ticket tomorrow at standup.  just wanted to make sure if was complete from a WebEx point of view.
