### ISSUE TITLE
Wireframe the API Programmer's Guide

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#8481]
## Problem statement

As the content has been created and the content audit is finished, the next step is to create the design of the API Programmers Guide in web form. To test ideas, share design intention, and gather feedback more quickly, the design team will take a a wireframe-first approach. The wireframes will capture general layout, IA, and the required components. These wireframes will ultimately inform the high fidelity designs for eng hand-off (upcoming ticket).

## What you need to know

- [Figma: Final Wireframes](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=3259%3A31995&scaling=min-zoom&page-id=2112%3A21339&starting-point-node-id=3259%3A31995&show-proto-sidebar=1)
- [Figma Workspace](https://www.figma.com/file/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=2112%3A21339&t=JBV2vNA6EKuXS3pM-1)
- [Design Audit](https://docs.google.com/document/d/1X5Lcysor_wod63OdvEzoCstl5QGBv6bl/edit?usp=sharing&ouid=108375376459243880703&rtpof=true&sd=true): used to identify components for wireframes (#7828)

## Acceptance criteria
**Design work**
- [x] Complete wireframes for the Landing Page
- [x] Complete wireframes for the Onboarding Guide page
- [x] Complete wireframes for select Resources/References 

**Review & feedback**
- [x] Review with design team (Design Lead, Design Crit)
- [x] Review with Experience engineers
- [x] Review with Engagement engineers
- [x] Incorporate feedback as needed

**Comment by jillian-hammer** [comment]
The wireframe designs & incorporated feedback (Content, Engagement, Experience Eng, and Design team) are completed!

Review links for @lizzieamanning 
- Figma: [Latest wireframes](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=3259%3A31995&scaling=min-zoom&page-id=2112%3A21339&starting-point-node-id=3259%3A31995&show-proto-sidebar=1)
- Mural: [Feedback stickies](https://app.mural.co/invitation/mural/primedatainput6410/1672412662691?sender=u0c3cdba5126734aceb613229&key=596c51e8-50f9-44b1-a1b9-33f42155be8c) with labels designated whether or not that feedback was incorporated 
- Next steps: Captured in the subsequent [Design: Design API Programmers Guide on the RS Website #8342](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/8342) ticket

**Comment by lizzieamanning** [comment]
@jillian-hammer @chris-kuryak looks great- lets close this

**Comment by chris-kuryak** [comment]
Closing
