### ISSUE TITLE
Don't log out validation errors to console

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8483]
## Problem statement

We currently output all validation errors to the console error stream.  We shouldn't do that because 1) these are specific to the user and their validation experience and 2) an influx of console errors will trigger PagerDuty alerts.

## What you need to know

- [This](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx#L143-L149) is the block of code that logs out the validation errors.

## Acceptance criteria
- [x] Determine why we are console logging and communicate out to engineering team
- [x] No validation errors are logged out

**Comment by stephenkao** [comment]
Will be handled in [this pull request](https://github.com/CDCgov/prime-reportstream/pull/8498/files#diff-5d2a81558a6b431619341e16c5ec886d7ba330cb7b93cb459db17980dc4b9177L143-L149).

**Comment by penny-lischer** [comment]
Was handled per #7945
