### ISSUE TITLE
Onboarding process materials creation

### ISSUE THREAD

**Issue by jakefishbein-navapbc** [CDCgov/prime-reportstream#8515]
**Goal:** 
Create a standard operating procedure and related documents for user onboarding. 

**Background and context:**
We can create efficiencies in the onboarding process by creating standard processes and documentation for our team members to use in meetings and to share with our customers 

**Impacted OKRs:**
Onboard more STLTs

**In scope**

- Formal SOP document modeled after the example provided by LaFreda. @jakefishbein-navapbc can you link this?
- Kickoff template
- Slide Deck @jakefishbein-navapbc is this a kickoff specific slide deck?
- "Handbook" of curated resources not included in the programmers guide. @jakefishbein-navapbc what are some examples of these resources?

**Out of scope**

- @jakefishbein-navapbc would you consider sender or receivers out of scope? Is this epic just for one type of customer or both?

**We will be successful if** 
Any engagement team member can run a kickoff meeting, including the pre and post kickoff activities, using the materials provided

**Comment by lizzieamanning** [comment]
@jakefishbein-navapbc when you get chance, can you fill out this ticket according to the design-issue template?

**Comment by lizzieamanning** [comment]
@jakefishbein-navapbc do you see this epic as being ready to be closed? What other onboarding work is there to be done?
