### ISSUE TITLE
Create updated slide deck for kickoff meeting

### ISSUE THREAD

**Issue by jakefishbein-navapbc** [CDCgov/prime-reportstream#8516]
**User Story**
As a member of the report stream team, I need a slide deck to display during kickoff meetings to help organize and reinforce the presentation content.

**Background & Context**
The current slide deck is not aligned with the updated kickoff agenda.

**Acceptance Criteria**

- [ ] Slide deck makes use of PRIME ReportStream formatting and branding.
- [ ] Slide deck content is aligned to current kickoff agenda.
- [ ] Slide deck contains presenter notes that support the facilitator in understanding and communicating content.
- [ ] Slide deck utilizes adult learning principles to help reinforce the onboarded users' understanding.
- [ ] Slide deck is reviewed with design team and Engagement team for alignment 

**Working Links**
[Kickoff Agenda](https://docs.google.com/document/d/1L2N02F0XVPERP1Qd0ANsnAt7AT2Ax8ChOY10JPxplNw/edit#heading=h.g5fk9amnajub)
[Existing Deck](https://docs.google.com/presentation/d/1WsbG4hgTnTT8A1kUKvpQdSoVdoKdDThu/edit#slide=id.p27)
[WIP Deck](https://docs.google.com/presentation/d/1iF2uJtT5ATCvdEj7lO7gktBGl3ISguYw/edit#slide=id.g228913439ae_0_42)

**Comment by lizzieamanning** [comment]
Added an AC for reviewing
