### ISSUE TITLE
API Key Management Security Design

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#8518]
## Problem statement

As the ReportStream API key management API, I need to follow the security best practices. 

There should exist a collection of endpoints in ReportStream that allow Okta users to upload API keys into ReportStream for a given scope. The assumption are as follows:

1. If an Okta user is assigned to a scope, that same user should be able to create an API Key with that scope for their organization to allow for server-server auth.

## Proposed Design

We propose API key management endpoints should use OKTA authentication. Currently `UpdateReceiver` and `UpdateSender` in `SettingsFunctions.kt` use `OktaAuthentication.checkAccess` but this is deprecated.

Instead, we should look to use `AuthenticatedClaims.authenticate` for authentication and `checkAccessAuthorizationForOrg` for authorization. Note that `checkAccessAuthorizationForOrg` is hardcoded to run `authorizedForSendOrReceive` which checks if a user can send or receive, so this will probably need a refactor or a new method created.

We can create a new scope for API key management.

## Acceptance criteria

- [x] security implications/architecture agreed upon
  - See discussion in https://github.com/CDCgov/prime-reportstream/issues/8472#issuecomment-1458783179
- [x] #8472 updated with security design in section "Security Implications"

**Comment by avnieldravid** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8518?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimduff-usds @jimmyfagan @PatriciaPerozoUSDS @thetaurean @victor-chaparro

**Comment by arnejduranovic** [comment]
See updated acceptance criteria
