### ISSUE TITLE
IL - ELR Issue with Duplicate Date Time Stamp

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#8521]
From Nicholas McGee <Nicholas.McGee@illinois.gov>

Report Stream folks,

It looks like as of a few days ago we have started to receive files with the same date time stamp in the FHS/BHS segments causing an issue when we try to load this data into our ELR database. We key our ELR database tables by the CLIA in FHS/BHS/MSH 4 as well as the date time stamp in the FHS/BHS/MSH segments so when the two keys are the same, it kicks out in error for duplicate key.

Here is an example. These are two different files that came in with the same date time stamp in the FHS/BHS segments. Please ignore the file name of the first snippet below as our archive process renames the files. The actual filename of the first snippet below is: covid-19-262a285c-f339-4d48-b74d-c28e52896f2d-20230227211539.hl7

![image.png](https://images.zenhubusercontent.com/62828b77597e3bdcbc3834fd/f6c87651-12c4-406c-a0c6-8c658c314e8d)
![image.png](https://images.zenhubusercontent.com/62828b77597e3bdcbc3834fd/a13fcd04-c3e8-4885-a727-a614ee0fb0c3)

When I came into the office this morning I have 15+ files that had kicked out over the weekend because of this issue. I have manually fixed them and reprocessed them so you do not have to worry about resending, but we do need this problem resolved going forward. Just to clarify, the date time stamps need to be different on every report stream file that is being sent.
 
Please let me know if you have any questions.
 
Thank you! 

Nicholas McGee

**Comment by GilmoreA6** [comment]
This occurred because IL now has two receivers and they were batching and sending on the same cadence. I have offset one of the receivers by 15 mins to alleviate this issue and let IL (nicholas.mcgee@illinois.gove) know to let us know if they see further issues.
