### ISSUE TITLE
Migrate ReportStream website to ECMAScript Module Standard

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8523]
## Problem statement

The standard for javascript modules is moving to ECMAScript. To ensure full functionality of the ReportStream website and to get in alignment with current standards, the ReportStream website needs to migrate to the ECMAScript Module Standards.

## What you need to know

- This migration may be dictated by the Jest library for automated testing.
- Jest library update is being tracked on #8460
- According to Joseph, we have about 6-12 months before this change may be absolutely necessary, so it is marked as Low-Priority for now.

## To do

- [ ] ...

**Comment by jpandersen87** [comment]
I consider this work blocked by jest's ESM support. At the moment it is being worked on and considered experimental. Jest issue for tracking: https://github.com/facebook/jest/issues/9430

**Comment by jpandersen87** [comment]
ReportStream Frontend is moved to ESM for majority of code and major dev dependencies (with remaining CJS libraries, if any, likely to naturally move to ESM when that library supports it).
