### ISSUE TITLE
NJ - ProPhase: Error in Rhapsody Route in PRODUCTION 2/28/23

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#8530]
*user is njelr.admin@doh.nj.gov - Mike Firkser and states*:

Please note the errors below in your ELR File: covid-19-8682a691-026a-4b41-939c-3526cb72bd48-20230228144110.hl7

 

Orders:

230550000473

230550000469

 

PID-11.6 should be a three character country code.  In each of these messages, it is “CN”, despite the patients having a United States address.  This has occurred previously.  Please correct and resubmit.

Thank you,

Mike Firkser

Technical Lead - NJDOH ELR Team

NJELR.Admin@doh.nj.gov

*screenshots from message*
![image.png](https://images.zenhubusercontent.com/62828ac9597e3bae41382df7/48858d63-eaef-4ee8-ab70-c5eb33a22fdb)

**Comment by GilmoreA6** [comment]
Report ID: 8682a691-026a-4b41-939c-3526cb72bd48

**Comment by Jcavallo7** [comment]
@LaFreda1 good morning! any updates?

**Comment by LaFreda1** [comment]
@Jcavallo7 Good morning! This ticket has been assigned to Kant, one of our new engineers who will need to gain appropriate access before completing the ticket. Ideally, this needs to be low priority if he remains on this ticket. Can we decrease the priority? If not, I will re-assign; let me know. Thanks!

**Comment by oslynn** [comment]
Done
