### ISSUE TITLE
File Validator Redesign

### ISSUE THREAD

**Issue by etanb** [CDCgov/prime-reportstream#8531]
## Problem statement

We are making our File Validator tool public-facing (meaning no authentication needed to use the tool) but we're also updating the overall Design and UX for better usability as well as the copy for better clarity.

## What you need to know

-  [Figma Final Design (Eng-ready)](https://www.figma.com/file/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=2183%3A21892&t=WLhbJIqQnfBOulOo-1)

## Acceptance criteria
- [x] Completely redesigned UX flow, layout and UI for File Validator
- [x] Make sure all copy is updated across File Validator pages
- [x] Update page with the new schema selector in #7773

**Comment by jillian-hammer** [comment]
just checked this out on staging and it looks great, @etanb and @stephenkao!!!

of course there a few nit-picky design notes, but i can take care of documenting them & writing tickets when i'm back.

@audreykwr wanna take a look at those new error messages? 😍

**Comment by chris-kuryak** [comment]
Content QA complete. This ticket can be closed. Follow up ticket exists.
