### ISSUE TITLE
Dendi Onboarding – 2. Testing in Staging and Prod

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#8532]
### Acceptance Criteria 
- [ ] Sender has tested in staging and production 
- [ ] RS engineer has determined the data is good enough and graduates Sender to send Prod data to receiver  

### To Do 
- [x] RS engineer: update this ticket with comments with every interaction with sender 
- [x] RS team member who originates this ticket: add dependencies:  
     - [x] Dendi Onboarding – Create Org and Sender Settings
     - [x] Dendi Onboarding - Validate Test Files 
- [x] RS team member who originates this ticket: make sure the following are included when creating this Issue. 
     - [x] Pipelines: Onboarding & Operations (New) 
     - [x] Labels: "Onboarding-ops," "Sender"
     - [x] Epics: #7582

**Comment by sliu1000** [comment]
Update from Sender:

Hi James,

Thanks for getting back to us.
Here is the .csv file we tried to send [attached]

**Comment by GilmoreA6** [comment]
Thanks Shatabdo,

Here's the corrections that should be made. Looks like a few of them are bug fixes on my side which I will address.

Column Name	Received Value	Expected Value	Comments
order_test_date	2023-01-03T11:08:44.341284-0600	2023010311084434-0600	expected format for datetime stamps is yyyymmddhhmmss +/- zzzz
specimen_collection_date	2023-01-03T11:08:44.341284-0601
2023010311084434-0600
if not present will use value from order_test_date 
ordering_provider_street
null
*
equired field
ordering_provider_city
null	*	required field
ordering_provider_state	null	*	required field
ordering_facility_city	null	*	required field, should default to testing_lab_city if not present, likely bug fix needed on my end.
ordering_facility_zip_code	null
*	required field, should default to testing_lab_zip_code if not present, likely bug fix needed on my end.
ordering_facility_phone_number	null
*	required field, should default to testing_lab_phone_number if not present, likely bug fix needed on my end.
equipment_model_id	Quantstudio 5	ex: Linea COVID-19 assay kit	 Needs to match value from column B of SARS-CoV-2 Covid-19 table https://www.cdc.gov/csels/dls/livd-codes.html
LOINC In Vitro Diagnostic (LIVD) Test Code Mapping for SARS-CoV-2 Tests | CDC
CENTER FOR SURVEILLANCE, EPIDEMIOLOGY AND LABORATORY SERVICES (CSELS)
www.cdc.gov

Thanks,

James

James Gilmore (Agile Six)
Senior HL7 Data Analyst
Pandemic-Ready Interoperability Modernization Effort (PRIME)

**Comment by GilmoreA6** [comment]
Thanks Shatabdo,

Here's the corrections that should be made. Looks like a few of them are bug fixes on my side which I will address.

Column Name	Received Value	Expected Value	Comments
order_test_date	2023-01-03T11:08:44.341284-0600	2023010311084434-0600	expected format for datetime stamps is yyyymmddhhmmss +/- zzzz
specimen_collection_date	2023-01-03T11:08:44.341284-0601
2023010311084434-0600
if not present will use value from order_test_date 
ordering_provider_street
null
*
equired field
ordering_provider_city
null	*	required field
ordering_provider_state	null	*	required field
ordering_facility_city	null	*	required field, should default to testing_lab_city if not present, likely bug fix needed on my end.
ordering_facility_zip_code	null
*	required field, should default to testing_lab_zip_code if not present, likely bug fix needed on my end.
ordering_facility_phone_number	null
*	required field, should default to testing_lab_phone_number if not present, likely bug fix needed on my end.
equipment_model_id	Quantstudio 5	ex: Linea COVID-19 assay kit	 Needs to match value from column B of SARS-CoV-2 Covid-19 table https://www.cdc.gov/csels/dls/livd-codes.html
LOINC In Vitro Diagnostic (LIVD) Test Code Mapping for SARS-CoV-2 Tests | CDC
CENTER FOR SURVEILLANCE, EPIDEMIOLOGY AND LABORATORY SERVICES (CSELS)
www.cdc.gov

Thanks,

James

**Comment by GilmoreA6** [comment]
Hi Shatabdo,

File was received and everything looks good. If you are ready, I would like to move on to the last step of onboarding which is for you to send a few real examples to our production endpoint. We will use those examples (3-5) to validate with the appropriate public health jurisdiction and once they give the green light we are good to move to full production mode.

Please ensure that any real patient data is sent to our production endpoint (prime.cdc.gov/api/waters) and that no real data is sent to the staging environment. Please let me know if you have any other questions or require further validation in the staging environment.

Thanks,

James

**Comment by GilmoreA6** [comment]
Hi Shatabdo,

CA has validated your file and you are cleared to move to full production mode. I have already made the change on our end. Let me know if you have any issues.

Thanks,

James
