### ISSUE TITLE
Virgin Islands example CSV file

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#8548]
## Problem statement

Virgin Islands is requesting for us to send them an example CSV file to gauge what type of data they will be working with in reporting to the RS platform.

## What you need to know
Our contact at Virgin Islands, Lisa is requesting an example CSV file: 

**Lisa L. Ekpo, DrPH

Deputy Territorial Epidemiologist 

U.S. Virgin Islands Department of Health

1303 Hospital Ground, Suite 10

Saint Thomas, VI 00802-8273

Mobile: (340) 514-7583

Fax:  (340) 776-1506

## Acceptance criteria

- [ ] A CSV example 

## To do

- [ ] Provide VI with an example CSV file and detailed explanation of how the fake file is similar to what they will see.

**Comment by brick-green** [comment]
[as-download-csv-06b2d852-3c9f-4f2f-90fb-e6e761cdc013-20230306193601.csv](https://github.com/CDCgov/prime-reportstream/files/10902240/as-download-csv-06b2d852-3c9f-4f2f-90fb-e6e761cdc013-20230306193601.csv)
[as-download-csv-467c2f13-2b91-409f-81f8-042b8ed738e5-20230306192400.csv](https://github.com/CDCgov/prime-reportstream/files/10902241/as-download-csv-467c2f13-2b91-409f-81f8-042b8ed738e5-20230306192400.csv)

**Comment by brick-green** [comment]
[vi-download-csv-06b2d852-3c9f-4f2f-90fb-e6e761cdc013-20230306193601.csv](https://github.com/CDCgov/prime-reportstream/files/10902248/vi-download-csv-06b2d852-3c9f-4f2f-90fb-e6e761cdc013-20230306193601.csv)
[vi-download-csv-467c2f13-2b91-409f-81f8-042b8ed738e5-20230306192400.csv](https://github.com/CDCgov/prime-reportstream/files/10902249/vi-download-csv-467c2f13-2b91-409f-81f8-042b8ed738e5-20230306192400.csv)

**Comment by LaFreda1** [comment]
Happy Monday all, 

Lisa, please find the sample CSV files attached. In these examples, our technical lead, Brick used real results from Simple Report, synthesized them to replace the PII, and added in data for Virgin Islands. Please review and let me know if you have any questions or comments. We look forward to continuing this collaboration! If you'd like to continue with this onboarding process, I am happy to schedule a kick-off call. 



Best, 
LaFreda

**Comment by LaFreda1** [comment]
Sent on 3/15/23

Good day,


Thank you for following up.  Are we able to get a better idea of the ordering providers and/or reporting facilities for the USVI data you have? We’d just like to make sure these data are unique and aren’t duplicates of what we already receive from our local providers. 

 

For the self-reported data, can I also see a sample file that show how these data will come over?  From what I understand, there may not be any PII associated with these reports, so it would be good to better understand what data elements we can expect before deciding on moving forward.

 

Thank you,
Lisa

**Comment by Jcavallo7** [comment]
*Tier 1 update*
sent over VI ordering facilities list
Also, csv file was already sent so not sure if they want hl7 file

*user update*

Good day,


Thank you for following up.  Are we able to get a better idea of the ordering providers and/or reporting facilities for the USVI data you have? We’d just like to make sure these data are unique and aren’t duplicates of what we already receive from our local providers. 

 

For the self-reported data, can I also see a sample file that show how these data will come over?  From what I understand, there may not be any PII associated with these reports, so it would be good to better understand what data elements we can expect before deciding on moving forward.

 

Thank you,
Lisa

**Comment by LaFreda1** [comment]
@Jcavallo7 please forward me the email thread of the ordering facilities. I think she is specifically asking for an example file that is tailored to OTC data. @brick-green Once the phd receives the data, is there any differentiation of the data format whether it is OTC or CLIA?

**Comment by Jcavallo7** [comment]
@LaFreda1 will do!

**Comment by sliu1000** [comment]
@LaFreda1 @brick-green Do you think we should suggest putting them through staging to start testing the OTC data?

**Comment by LaFreda1** [comment]
@brick-green Is that required to show her how how to the self reported data will look once they receive it? My understanding of her message is that she just wants to see what it will look like once they receive it. Can we just send an example of self reported data not specific to VI?

**Comment by brick-green** [comment]
I don't think it's required but I do think it's better. The data they will get would be a better representation and we wouldn't have to go through this process of making them test files anymore.

I can still make a test file though in the meantime. How many results should be in it? Which sender should we choose? Should it be more than one sender?

**Comment by LaFreda1** [comment]
@brick-green Since they have not formally committed to onboarding I think we should do whatever is easiest. One sender will work, she is just trying to get a feel for what it will look like.

**Comment by sliu1000** [comment]
Sent follow-up email:

Greetings Lisa,

I'm just following up on resources you received and wondering if you have any questions.  Another option that is available is that we can turn on the data feed for you to receive the data so you can see what the data actually looks like. Please let us know if this option interests you.

Best regards,

Sharon
The ReportStream Support Team
Contact us at reportstream@cdc.gov
Support hours:  8:00 am through 9:00 pm Eastern time
Monday-Friday, excluding US public holidays
