### ISSUE TITLE
Gracefully Handle Routing Filters when a property isn't present in the FHIR Bundle

### ISSUE THREAD

**Issue by PatriciaPerozoUSDS** [CDCgov/prime-reportstream#8552]
User Story.
As an oncall engineer I don't want to be paged unnecessarily.

Description/Use Case
We currently throw an error when we try to evaluate a filter condition and a boolean is not returned. This will cause our on call to be paged. It is expected that there will be filter conditions that evaluate to null because the data doesn't exist in the bundle we were sent and therefore cause us to not return a boolen. 

We also want to better proof the filters that are in our settings. Please update prod, staging, and organizations.yml with the check to see if the resource exists before comparing it.  For example `%performerState.exists() and %performerState = 'CA'`

Risks/Impacts/Considerations

Dev Notes:
* Error thrown here: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt#L454 

Acceptance Criteria
UP logs a warning when information isn't present in the FHIR bundle
UP still logs that a filter couldn't be evaluated because information wasn't present

**Comment by jimmyfagan** [comment]
Updated filters in staging to check for existence of fields before comparing them. In prod, no filters needed updates. We can consider that aspect of this story to be done.
