### ISSUE TITLE
Change Daily Data Date Filter Default Values

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8554]
## Problem statement
The Daily Data table date filter is used by both the support team and STLTs. The date filter starts with very low (01/01/2000) and very high (01/01/3000) values that make using the date selector tool difficult because you need to scroll for lots of years in order to get to something similar to today. Ideally, it should start at a date when RS started receiving data, and end at something less than 900 years away to make the date selection tool more usable.

## What you need to know

- [Daily Data Page](https://reportstream.cdc.gov/daily-data)
- Per discussion with Jillian and Audrey on design 3/2/2023, the default values should start at the beginning of ReportStream (6/25/2021) and end at today's date, if possible.
- Per discussion with Jessica S on 1/4/2024, the default values should be blank on first load, and then populate to today's date on first interaction
- Screenshot:
![Screenshot 2023-03-01 at 4.12.08 PM.png](https://images.zenhubusercontent.com/637d310dba428f3e3d55c9db/8d80a854-3620-4198-8435-a8b5b237366b) ...

## Acceptance criteria

- [ ] Upon first load, no date is shown in the start or end date fields (but the page still loads all results)
- [ ] Upon interaction with the date picker, the default dates will be shown as today's date in both Start and End date fields

## To do

- [ ] ...

**Comment by penny-lischer** [comment]
@chris-kuryak should this logic be applied to the Data Dashboard page and any other page where this component occurs?

**Comment by chris-kuryak** [comment]
Does it occur anywhere else other than Data Dashboard and Daily Data now? If not, then my answer is yes.

**Comment by chris-kuryak** [comment]
After discussion with Jessica S, the ACs have been changed to be:
- Upon first load, no date is shown in the start or end date fields (but the page still loads all results)
- Upon interaction with the date picker, the default dates will be shown as today's date in both Start and End date fields

**Comment by penny-lischer** [comment]
@chris-kuryak This ticket is no longer valid and is working per AC

**Comment by chris-kuryak** [comment]
Etan fixed as part of another ticket. ACs met.
