### ISSUE TITLE
Content operations discovery

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#8557]
## Problem statement

With all of the different places that content can live and be worked on and reviewed, we need to determine the best options for the different types of work we do with ReportStream. 

## Acceptance criteria

- [x] Top option(s) for platforms/tools/processes shared with design team for further planning with design ops

## To do

- [ ] ID use cases needed
- [ ] Explore options
- [ ] Share out findings and recommendations

**Comment by audreykwr** [comment]
@lizzieamanning @chris-kuryak fyi

**Comment by audreykwr** [comment]
@chris-kuryak moving to review as it is done except for sharing out with design team, which I'll do in sync tomorrow.

@jillian-hammer @lizzieamanning I can share in sync, or async if that's not the best time, but [here is my summary so far](https://docs.google.com/document/d/1tglUxI7VE3LKMbRvpb-av9gO_n5C-Puz6FDunh6g-iY/edit?usp=sharing)

**Comment by lizzieamanning** [comment]
@audreykwr since tmrw is our first "thursday crit" lets review then!
