### ISSUE TITLE
CSV/download version for API field guides

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#8558]
## Problem statement

For the first version of the programmer's guide on the web, we are not putting the field list tables online. However, that means that we need to have an accessible version ready to download. A PDF is probably not the best solution, so we need to adapt the PDF tables into CSV form. 

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [new pdf version of guide](https://docs.google.com/document/d/17M0jqjRa2DKnvr8lHWP98Et2CgrWTv3_/edit)
- [edit copy with design notes/misc in comments](https://docs.google.com/document/d/1S4SlRp5nznuymnCr1nOwhQYDKYt2OqTX/edit#)

## Acceptance criteria

- [ ] Tables formatted for download and shared with design/eng for upload

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@chris-kuryak this was actually really quick work. moved to 1 pt from 2.

**Comment by jillian-hammer** [comment]
Reviewed this quickly, and it looks great! The only thing I might add is a version/last updated label. @audreykwr

**Comment by audreykwr** [comment]
@jillian-hammer great point!

**Comment by audreykwr** [comment]
[Draft of csv download](https://docs.google.com/spreadsheets/d/1sSpDeKQdackzRS5IT58WmUWn1eq6pA1Rm57u0C5QpgM/edit#gid=0)
