### ISSUE TITLE
Content audit analysis

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#8562]
## Problem statement

We need to know how our current site and plans are meeting our users' needs and RS goals. An audit will examine that based on previously IDed needs and priorities.

## What you need to know

(May add detailed audit doc when that ticket is completed) 

- [General planning doc](https://docs.google.com/document/d/1WjaSCEqaZkJ0Xmkll-rllc219S9nT7B1vfyRtN9R0Vc/edit?usp=sharing)
- [Workshop synthesis deck with planning notes](https://docs.google.com/presentation/d/1ljFEf3dUm3z2cOrgikiXoCemIoqDRWWRnMz4vyue--Y/edit#slide=id.g11de60fb153_0_1358)
- [Mural of general work roadmap/misc notes](https://app.mural.co/invitation/mural/nava4113/1673278109303?sender=uc55a7af3b66977fba12f5528&key=27b02b81-58ce-4f9b-a734-4aab2802ad5b)

## Acceptance criteria

- [x] Scope examined through determined heuristics
- [x] Tickets created for next steps

## To do

- [ ] ...

**Comment by lizzieamanning** [comment]
@audreykwr note to adjust points here as we discussed in our 1:1 today

**Comment by audreykwr** [comment]
Closing. I[nitial deck of work here](https://docs.google.com/presentation/d/1H5uon85WeTZgvRQH-7DlpwmrDXQUO6tA6xIHh7KZX_M/edit?usp=sharing)
