### ISSUE TITLE
API guide best practices deep dive

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#8564]
## Problem statement

After our "1.5" version of migrating the guide to the web, there is deeper work to be done to really make the guide as usable and useful as possible. There are lots of best practices and examples out there that can provide inspiration, ideas, and guidelines as we plan that work. 

## Acceptance criteria

- [ ] Findings gathered and logged in a shared folder to reference for next steps plans

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@chris-kuryak This is probably something I'll do next sprint, but I wanted to log it as a chunk of work related to moving the guide forward after this launch. I think it's worth looking at ahead of actually making those next levels plans to be prepared for that. It's more of a background, low priority thing to do as there is time.

**Comment by audreykwr** [comment]
lol. just realized this was duplicate. should I close it or is there a way to delete it? @chris-kuryak

**Comment by chris-kuryak** [comment]
Deleting does not exist. I have tried, haha.
Closing now per Audrey.
