### ISSUE TITLE
Jamie Albinson - Engagement Engineer access ticket

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#8566]
Access Needed for New Engineer

- [x] CDC email - (in Progress - Frank Dilley contact)
- [ ] CDC SU account access
- [x] Okta Account Staging
- [x] Okta Account Production
- [x] Open VPN credentials for Staging and Prod dbs
- [x] Metabase Staging Access
- [x] Metabase Production Access
- [x] Zenhub Access
- [x] Easyretro Access
- [x] Mural Access
- Slack Channels
   - [x] prime-reportstream
   - [x] prime-reportstream-engagement
   - [x] prime-reportstream-engineering

**Comment by brick-green** [comment]
Can you include these slack channels on this?

prime-reportstream
prime-reportstream-engagement
prime-reportstream-engineering

**Comment by GilmoreA6** [comment]
GitHub Username: jalbinson

**Comment by LaFreda1** [comment]
@GilmoreA6 I'm going to make this an epic and include this. We need to start list of what's needed to onboard people and this is a great start!

**Comment by LaFreda1** [comment]
Access to slack channels granted by Patricia on 3/7/23

**Comment by brick-green** [comment]
Just added jalbison as a collaborator on the git repo

**Comment by chris-kuryak** [comment]
Can be closed
