### ISSUE TITLE
Document the endpoints we'd need to mock for our Cypress specs

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-reportstream#8569]
## Problem statement

We need to create a mechanism to switch to mocked API endpoints on production and create mocks for most API endpoints that would otherwise return real data.

## Acceptance criteria

- [ ] Investigate and document the endpoints we'd need to mock

*Relates to #8025

**Comment by jpandersen87** [comment]
This is being handled on a per-page basis per ticket unit-of-work.
