### ISSUE TITLE
Implement mocked API endpoints for our Cypress specs

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-reportstream#8570]
## Problem statement

We need to create a mechanism to switch to mocked API endpoints on production and create mocks for most API endpoints that would otherwise return real data.

## What you need to know

 Relates to #8025
 Depends on #8569

## Acceptance criteria

- [ ] Implement mocked API endpoints (can be split up if needed)
- [ ] Stub the data that should be returned when Cypress queries an endpoint (.JSON files)
- [ ] Mock the HTTP call that will return the data

## To do

- [ ] ...

**Comment by jpandersen87** [comment]
This is being handled on a per-page basis for a ticket-of-work.
