### ISSUE TITLE
VPN access for Victor Chaparro (staging/demo/production)

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#8579]
**What type of help do you need?**

I need staging, demo, prod VPN credentials to be able to connect to those environments

**Please describe how you'd like us to help.**

Please create vpn credentials for @victor-chaparro  for the staging and demo environments.
Keybase username is victorchaparro
Thanks so much for your help!

**Comment by jeremy-page** [comment]
Sent Victor a bundle of profiles
