### ISSUE TITLE
VT - Production Error 

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#8585]
## **Problem Statement**
Vermont's submission error

## **What you need to know**
Happened at 3/3/23 early morning

## **Acceptance Criteria**
Needs to be resubmitted, or connection error fixed to allow resubmission to go through

## **Additional Comments**
![image.png](https://images.zenhubusercontent.com/62828ac9597e3bae41382df7/b7059b60-0e3f-468e-ab78-cf19ecf59b46)

*File that error occured on*

**Comment by sliu1000** [comment]
@Jcavallo7 can we close this one?

**Comment by Jcavallo7** [comment]
yes ill close it
