### ISSUE TITLE
Design way to constrain ETOR data to ETOR receivers only.

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#8586]
### User Story:

As someone outside the ReportStream team, I need a simple, foolproof way, independent of the data itself, to configure my Senders and Receivers so my data is partitioned from everyone else's data.

Detailed descriptions of **simple**, **foolproof**, and **independent**, are below.

### Description/Use Case/Further Details

A couple analogies might be helpful
- I need something that acts a like a VPN.  My data flows in my ReportStream 'private virtual network', and your data flows in yours, and RS guarantees the wires never cross.
- Another analogy might be observer/observable or 'topics' in subscription models. My senders submit messages within a particular topic, and my receivers subscribe to those topics.   Its leak-proof - anyone not subscribed never gets my data.

Here's why it needs to be simple, foolproof, and independent:

1. **Simple**:  The Requirement is best described with an example: It is likely that  ETOR onboarding and operations will be managed by Technical Assistants ("TA") hired directly by CDC, not by people on the ReportStream team.   Those non-ReportStream teams need a very _simple foolproof_ way to stovepipe their data, to avoid confusion and errors.
2. **Foolproof**:  The implementation should default to not send -- it can't depend on a human remembering to put in an extra clause in one of the FHIR path filters.    (Although I think that solution is fine for a UP MVP).
3.  **Independent of the data itself**:  _You can easily conceive of situations where the data itself might not contain enough info to determine if it belongs within a particular topic._   Or, situations where the customers repeatedly change datatypes as they setup their system.  That is, the private network is tied to senders and receivers, and may not be in the data itself.   Topics should be an abstraction.

### Risks/Impacts/Considerations

Its possible this the current filters will become a performance issue.  ETOR may end up having thousands of receivers.   RS's powerful filter mechanism tries them all right now.   'topic', or something like it, acting basically as an "initial filter" will help you constrain the number of comparisons occurring.  Why bother trying to send full-elr data through ETOR and vice versa?

### Dev Notes:

The problem of mixing data has already happened.  The first time I submitted ETOR data, I immediately found it flowing to bizarre places, like the 'ignore' full-elr test receivers even though its not full-elr data. This is confusing, and further, it breaks easily. (See #8583 for an example - this is not a one-off problem -- filters necessarily make assumptions about the _type_ of data coming through their receivers, so this will recur)

In the old pipeline, this requirement was met with the 'topic' concept, which was simple and foolproof.   We either need topics, or something that fills the equivalent role, in the new pipeline. Whereas filters sometimes depend on the data in a message, topics work above the level of the message and are concerned with settings. This way ReportStream can publish topics it supports, for example "ETOR", and senders can identify themselves, in their settings, as sending that topic and at the same time receivers can identity themselves, in their settings, as wanting to receive that topic.

### Acceptance Criteria
- [x] A proposal for receiver settings which satisfy the requirements outlined in this description has been reviewed and checked in to the repo
- [x] Tickets for the implementation of this have been opened and are linked here: 
  - https://github.com/CDCgov/prime-reportstream/issues/8661
  - https://github.com/CDCgov/prime-reportstream/issues/8592
  - https://github.com/CDCgov/prime-reportstream/issues/9464
  - #9495

**Comment by avnieldravid** [comment]
needs acceptance criteria

**Comment by arnejduranovic** [comment]
@jimmyfagan The schema associated with a receivers has a message type in it (R01, for example) and the message type acts like a partition type. Is this sufficient enough?

**Comment by jimmyfagan** [comment]
Yea filters in the settings can include message type checks, or the receiver transforms can require a particular condition, but we probably need to make sure message type filters to go along with jurisdictional filters or something like that to kick it in sooner and not log filter results for message type mismatches (we currently log filtered results that pass the juris filter but don't pass other filters). You could theoretically tie that directly into the juris filters, but that's maybe less foolproof that Jim had in mind in his description, and an enum or something like that would be better. Anyway, I don't think any work here is strictly required or urgent, but it's probably worth keeping this ticket around.
