### ISSUE TITLE
Send generated Simple Report CA HL7 to CA STLT

### ISSUE THREAD

**Issue by PatriciaPerozoUSDS** [CDCgov/prime-reportstream#8587]
**User Story:**
As CA PHD, I want the to receive the new HL7 data generated from FHIR to my test system, so I can verify the data is good to be received.

**Description/Use Case**
We need to send the generated Simple Report data to CA once we know the specifics of what we want. 

**Risks/Impacts/Considerations**

**Dev Notes:**
- We need to add a CA SLTL specific transform (Take a look at the Simple Report yml)
- We need to add a new CA receiver. We will need to talk to Engagement about how to do the credentials for the new receiver.

**Acceptance Criteria**
* The UP sends HL7 v2 data to CA PHD's test system.

**Comment by avnieldravid** [comment]
@PatriciaPerozoUSDS to point this

**Comment by avnieldravid** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8587?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimduff-usds @PatriciaPerozoUSDS @victor-chaparro
