### ISSUE TITLE
Address Fortify Scan Results

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#8595]
### User Story:
As a ReportStream engineer, I need to address Fortify scan findings either by:
1. Ignoring them and documenting a reason
2. Updating the code to silence the finding

### Description/Use Case
If the finding is a serious issue, we should fix it.
If the finding is a non-issue, we should fix it if it is quick to do so. Otherwise, document why it is a non-issue and not fix it.

### Dev Notes:
The findings can be found in this [spreadsheet](https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Engineering/fortify_scan.xlsx?d=w71e7b441617c40a4b60ad34a661db970&csf=1&web=1&e=EMYluD)

### Acceptance Criteria
- [x] Reviewed code changes/comments with @snesm 
- [x] Clearly documented findings we did not fix and why and reviewed with Stephen Nesman
- [x] If an individual fix takes longer than a day, a separate standalone ticket is created

**Comment by PatriciaPerozoUSDS** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8595?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jimmyfagan @JessicaWNava @victor-chaparro @PatriciaPerozoUSDS

**Comment by bishoyayoub** [comment]
@JessicaWNava are we OK to close this item?
