### ISSUE TITLE
CA requesting new results filter

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#8598]
## Problem statement

CalREDIE is receiving results for people not in CA

## What you need to know

CalREDIE has been receiving results from mobile clinics out of CA where the patient is not physically tested or living in CA

- MODO Mobile doctor and Brainworks Foundry Medio Lab are examples sent from Jill Massey

## Acceptance criteria

- For California, if the patient has an out of state address (non CA) and was seen by a provider, also not in CA, please do not send the reports to CalREDIE if the test was run by a CA laboratory.

## To do

- Filter out results where the patient address and ordering provider address are not CA

**Comment by jalbinson** [comment]
May I have the message IDs for the test result that is routed to CalREDIE?

**Comment by jalbinson** [comment]
@TaneaY 

The issue is that although the `Ordering_facility_state` field is `CA`, we don't want to send reports to `CA` when the `Ordering_provider_state` is not `CA`?

To be more specific, `MODO Mobile Doctor` is based in Los Angeles but is being used outside California and California doesn't need those results.

Do I have that right?

**Comment by TaneaY** [comment]
Apologies for the delay, that is correct they do not want the results if the patient was not tested in CA even though the lab is based in CA for these mobile clinics

Thank you,

Tanea

The SimpleReport Support Team

Contact us at ***@***.***

Support hours:  8:00 am through 9:00 pm Eastern time

Monday-Friday, excluding US public holidays

________________________________

**Comment by jalbinson** [comment]
@TaneaY

@brick-green has brought up a scenario that we want California's input on. What should happen in the following:
> What does CA want to to happen when ordering facility state = CA, Patient State <> CA, and Provider State is blank? With the proposed filters those results will also be filtered

**Comment by TaneaY** [comment]
Sent a follow up to CA contacts with the above question



________________________________

**Comment by TaneaY** [comment]
@jalbinson @brick-green Follow-up reponse:

Hi Tanea, I think I am following your question.

If the patient has an address in CA and was seen/treated in CA, send to CA.

If the patient has an address not in CA but was seen/treated by a CA provider, send to CA.

If the patient has an address in CA and was seen/treated in a different state, send to CA.

 

This should capture people that are travelling essentially.

 

Our logic is, geocode on address of patient (PID 11), if missing or non-geocodeable, geocode on the address of the provider (OBX 24), if not, then geocode on the address of the performing lab.

If the primary or secondary are CA address, send to CA.

 

Let me know if you need more information.

Thanks,

Jill M. Meesey

**Comment by LaFreda1** [comment]
Last response on April 18

**Comment by jalbinson** [comment]
Is this still something CA is interested in? I have yet to hear back.

**Comment by TaneaY** [comment]
Last correspondence was not found in Reportstream inbox. Sent a follow-up from 4.3.23 thread. Engineering and product cc'd

**Comment by TaneaY** [comment]
Follow-up email sent with context from product correspondence for additional staff to assist.
