### ISSUE TITLE
CO - Production Error

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#8609]
## **Problem Statement**
submission error over the weekend

## **What you need to know**
file name was 0ff8a2e4-4cb2-4e44-b712-af687c06a7b7

## **Acceptance Criteria**
resubmission and confirmation of resubmission, will confirm submission with state

![image.png](https://images.zenhubusercontent.com/62828ac9597e3bae41382df7/5e3e62c5-d7d1-4bbe-8c2d-65e641eb9429)

**Comment by kant777** [comment]
Looks like it is resent sucessfully!
