### ISSUE TITLE
Remove reserved word, hyphen restriction for Organization/Sender/Receiver names

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8616]
## Problem statement

In [#7139](https://github.com/CDCgov/prime-reportstream/issues/7139), we added a restriction against special characters and reserved words for Organization/Sender/Receiver names just in case this were to cause issues in the back end.  However, reserved words aren't an issue at the moment so we can remove that restriction for now.

Additionally, we should allow hyphens since those are already part of many of our service names.

## What you need to know

- [isProhibitedName](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/utils/misc.ts#L53-L79) is the function that checks against special characters and reserved words.

## Acceptance criteria

- [ ] Organization/Sender/Receiver names can contain reserved words and hyphens again
- [ ] Organization/Sender/Receiver names still cannot contain disallowed characters

**Comment by arnejduranovic** [comment]
I just want to make sure we are clear here, the following character should definitely not be restricted: `*` Current deploy is basically broken because this character is very common in scopes

**Comment by arnejduranovic** [comment]
@stephenkao On staging I get this error when clicking the "edit json and save" button as shown. I did not could/not check what exact thing it was choking on, I just assumed it was the `*`?

![Screenshot 2023-03-17 at 2 12 57 PM](https://user-images.githubusercontent.com/118766341/225998551-ab99ea14-ed4d-4d15-9994-e0b1f426e549.png)

**Comment by stephenkao** [comment]
@arnejduranovic Ah, gotcha gotcha.  It's from [this regex](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/utils/misc.ts#L50), which is failing on the hyphen -- which we should absolutely allow.  I'm going to update the ticket to remove the reserved words check AND allow hyphens (which should line up with the "all lowercase + hyphenated" format that we discussed with Jim in Slack), and I'll hop on this now to unblock everyone on this point.

**Comment by arnejduranovic** [comment]
Ah okay I remember this now. Thanks for the help!!

**Comment by stephenkao** [comment]
No problem -- just put up [a pull request](https://github.com/CDCgov/prime-reportstream/pull/8760) if you'd like to take a look.  Thanks for re-raising this issue!
