### ISSUE TITLE
WA - 58 Incorrect Submissions

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#8630]
*User is Jennifer Risler - jenni.risler@doh.wa.gov*

## **Problem Statement**
Washington Department of Health received 58 incorrect messages from KC POCT LAB.

## **What you need to know**
as of 4:30PST WA DOH received 58 structurally incorrect messages that have errored in our system. Messages contain a hard carriage return after street address, ordering lab is KC POCT LAB.

*Note: Jennifer will email a spreadsheet to the ReportStream mailbox*

**Comment by rnz6** [comment]
Update 3/7:

Thank you Jessica,


I have attached a list of MSH IDs for the 37 records that errored in our system due to a structurally incorrect hard carriage return in address fields.  Please correct and resubmit these errors.
 
Filename: ELR__API_7uycso49__20230306_143530816__23b44224-2446-4603-adaa-020052bc7c31

Example of error:

OBX|1|CWE|94558-4^SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay^LN^^^^2.68||10828004^Positive^SCT|||A^Abnormal (applies to non-numeric results)^HL70078^^^^2.7|||F|||20230219160000|50D0632420^KC POCT LAB^CLIA||10811877011290_DIT^BinaxNOW COVID-19 Ag Card^99ELR^^^^2.68^^10811877011290_DIT|No Equipment|20230219160000||||KC POCT LAB^L^^^^CLIA&2.16.840.1.113883.4.7&ISO^XX^^^50D0632420|401 5TH AVE

SUITE 1000^^SEATTLE^WA^98104^USA

MSH-10 value:

484855104+1+20230306

494129351+2+20230306

484731663+1+20230306

484700606+2+20230306

484747707+3+20230306

485493013+4+20230306

486001439+5+20230306

485849379+6+20230306

484732548+7+20230306

484683124+8+20230306

484747368+9+20230306

490062309+10+20230306

484770343+11+20230306

487342665+12+20230306

493811096+13+20230306

484698868+14+20230306

489083707+15+20230306

484757745+16+20230306

484761092+17+20230306

490939543+18+20230306

487365124+19+20230306

484675737+20+20230306

485857933+21+20230306

492294540+22+20230306

484210013+23+20230306

484763031+24+20230306

484486958+25+20230306

491798552+26+20230306

484321878+27+20230306

484496957+28+20230306

484330540+29+20230306

484502080+30+20230306

484701946+31+20230306

484702438+32+20230306

491875599+33+20230306

484783342+34+20230306

490090651+35+20230306

 
Sincerely,

Jenni


[https://app.zenhub.com/files/304423150/b631c3b8-a56b-4458-9b9f-e401c2da44e0/download](https://app.zenhub.com/files/304423150/b631c3b8-a56b-4458-9b9f-e401c2da44e0/download)

**Comment by rnz6** [comment]
Update 3/7:

Thank you Jessica,


I have attached a list of MSH IDs for the 37 records that errored in our system due to a structurally incorrect hard carriage return in address fields.  Please correct and resubmit these errors.
 
Filename: ELR__API_7uycso49__20230306_143530816__23b44224-2446-4603-adaa-020052bc7c31

Example of error:

OBX|1|CWE|94558-4^SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay^LN^^^^2.68||10828004^Positive^SCT|||A^Abnormal (applies to non-numeric results)^HL70078^^^^2.7|||F|||20230219160000|50D0632420^KC POCT LAB^CLIA||10811877011290_DIT^BinaxNOW COVID-19 Ag Card^99ELR^^^^2.68^^10811877011290_DIT|No Equipment|20230219160000||||KC POCT LAB^L^^^^CLIA&2.16.840.1.113883.4.7&ISO^XX^^^50D0632420|401 5TH AVE

SUITE 1000^^SEATTLE^WA^98104^USA

MSH-10 value:

484855104+1+20230306

494129351+2+20230306

484731663+1+20230306

484700606+2+20230306

484747707+3+20230306

485493013+4+20230306

486001439+5+20230306

485849379+6+20230306

484732548+7+20230306

484683124+8+20230306

484747368+9+20230306

490062309+10+20230306

484770343+11+20230306

487342665+12+20230306

493811096+13+20230306

484698868+14+20230306

489083707+15+20230306

484757745+16+20230306

484761092+17+20230306

490939543+18+20230306

487365124+19+20230306

484675737+20+20230306

485857933+21+20230306

492294540+22+20230306

484210013+23+20230306

484763031+24+20230306

484486958+25+20230306

491798552+26+20230306

484321878+27+20230306

484496957+28+20230306

484330540+29+20230306

484502080+30+20230306

484701946+31+20230306

484702438+32+20230306

491875599+33+20230306

484783342+34+20230306

490090651+35+20230306

 
Sincerely,

Jenni


[https://app.zenhub.com/files/304423150/b631c3b8-a56b-4458-9b9f-e401c2da44e0/download](https://app.zenhub.com/files/304423150/b631c3b8-a56b-4458-9b9f-e401c2da44e0/download)

**Comment by rnz6** [comment]
Update from Jenni 3/10:

Good morning Jessica, 

We received another file with the carriage return issue.  An updated file with MSH segments is attached.  MSH-10s are listed below.  Please pause submissions from this sender until the issue is fixed, and resubmit corrections with updated MSH-7 values as soon as possible.

MSH-10

SimpleReport_2023-02-23+1+20230309

SimpleReport_2023-02-23+2+20230309

SimpleReport_2023-02-23+3+20230309

SimpleReport_2023-02-23+4+20230309

SimpleReport_2023-02-23+5+20230309

SimpleReport_2023-02-23+6+20230309

SimpleReport_2023-02-23+7+20230309

SimpleReport_2023-02-23+8+20230309

SimpleReport_2023-02-23+9+20230309

SimpleReport_2023-03-07+10+20230309

SimpleReport_2023-03-07+11+20230309

SimpleReport_2023-03-07+12+20230309

SimpleReport_2023-03-07+13+20230309

SimpleReport_2023-03-07+14+20230309

SimpleReport_2023-03-08+15+20230309

SimpleReport_2023-03-08+16+20230309

SimpleReport_2023-03-08+17+20230309

SimpleReport_2023-03-08+18+20230309

SimpleReport_2023-03-08+19+20230309

SimpleReport_2023-03-08+20+20230309

SimpleReport_2023-03-08+21+20230309

SimpleReport_2023-03-08+22+20230309

SimpleReport_2023-03-08+23+20230309

SimpleReport_2023-03-08+24+20230309

SimpleReport_2023-02-23+1+20230309

SimpleReport_2023-02-23+2+20230309

SimpleReport_2023-02-23+3+20230309

SimpleReport_2023-02-23+4+20230309

SimpleReport_2023-02-23+5+20230309

SimpleReport_2023-02-23+6+20230309

SimpleReport_2023-02-23+7+20230309

SimpleReport_2023-02-23+8+20230309

SimpleReport_2023-02-23+9+20230309

SimpleReport_2023-02-23+10+20230309

SimpleReport_2023-02-23+11+20230309

SimpleReport_2023-02-23+12+20230309

SimpleReport_2023-02-23+13+20230309

SimpleReport_2023-02-23+14+20230309

SimpleReport_2023-02-23+15+20230309

SimpleReport_2023-02-23+16+20230309

SimpleReport_2023-02-23+17+20230309

SimpleReport_2023-02-23+18+20230309

SimpleReport_2023-02-23+19+20230309

SimpleReport_2023-02-23+20+20230309

SimpleReport_2023-02-23+21+20230309

SimpleReport_2023-02-23+22+20230309

SimpleReport_2023-02-23+23+20230309

SimpleReport_2023-02-23+24+20230309

SimpleReport_2023-02-23+25+20230309

SimpleReport_2023-02-23+26+20230309

SimpleReport_2023-02-23+27+20230309

SimpleReport_2023-02-23+28+20230309

SimpleReport_2023-02-23+29+20230309

SimpleReport_2023-02-23+30+20230309

SimpleReport_2023-02-23+31+20230309

SimpleReport_2023-02-23+32+20230309

SimpleReport_2023-02-23+33+20230309

SimpleReport_2023-02-23+34+20230309

SimpleReport_2023-02-23+35+20230309

SimpleReport_2023-02-23+36+20230309

SimpleReport_2023-02-23+37+20230309

SimpleReport_2023-02-23+38+20230309

SimpleReport_2023-02-23+39+20230309

SimpleReport_2023-02-23+40+20230309

SimpleReport_2023-02-23+41+20230309

SimpleReport_2023-02-23+42+20230309

SimpleReport_2023-02-23+43+20230309

SimpleReport_2023-02-23+44+20230309

SimpleReport_2023-02-23+45+20230309

SimpleReport_2023-02-23+46+20230309

SimpleReport_2023-02-23+47+20230309

SimpleReport_2023-02-23+48+20230309

SimpleReport_2023-02-23+49+20230309

SimpleReport_2023-02-23+50+20230309

SimpleReport_2023-02-23+51+20230309

SimpleReport_2023-02-23+52+20230309

SimpleReport_2023-02-23+53+20230309

SimpleReport_2023-02-23+54+20230309

SimpleReport_2023-02-23+55+20230309

SimpleReport_2023-02-23+56+20230309

SimpleReport_2023-02-23+57+20230309

SimpleReport_2023-02-23+58+20230309

SimpleReport_2023-02-23+59+20230309

SimpleReport_2023-02-23+60+20230309

SimpleReport_2023-02-23+61+20230309

SimpleReport_2023-02-23+62+20230309

SimpleReport_2023-02-23+63+20230309

SimpleReport_2023-02-23+64+20230309

SimpleReport_2023-02-23+65+20230309

SimpleReport_2023-02-23+66+20230309

SimpleReport_2023-02-23+67+20230309

SimpleReport_2023-02-23+68+20230309

SimpleReport_2023-02-23+69+20230309

SimpleReport_2023-02-23+70+20230309

SimpleReport_2023-02-23+71+20230309

SimpleReport_2023-02-23+72+20230309

SimpleReport_2023-02-23+73+20230309

SimpleReport_2023-02-23+74+20230309

SimpleReport_2023-02-23+75+20230309

SimpleReport_2023-02-23+76+20230309

SimpleReport_2023-02-23+77+20230309

SimpleReport_2023-02-23+78+20230309

SimpleReport_2023-02-23+79+20230309

SimpleReport_2023-02-23+80+20230309

SimpleReport_2023-02-23+81+20230309

SimpleReport_2023-02-23+82+20230309

SimpleReport_2023-02-23+83+20230309

SimpleReport_2023-02-23+84+20230309

SimpleReport_2023-02-23+85+20230309

SimpleReport_2023-02-23+86+20230309

SimpleReport_2023-02-23+87+20230309

SimpleReport_2023-02-23+88+20230309

SimpleReport_2023-02-23+89+20230309

SimpleReport_2023-02-23+90+20230309

SimpleReport_2023-02-23+91+20230309

SimpleReport_2023-02-23+92+20230309

SimpleReport_2023-02-23+93+20230309

SimpleReport_2023-02-23+94+20230309

SimpleReport_2023-02-23+95+20230309

SimpleReport_2023-02-23+96+20230309

SimpleReport_2023-02-23+97+20230309

SimpleReport_2023-02-23+98+20230309

SimpleReport_2023-02-23+99+20230309

SimpleReport_2023-02-23+100+20230309

SimpleReport_2023-02-23+101+20230309

SimpleReport_2023-02-23+102+20230309

SimpleReport_2023-02-23+103+20230309

SimpleReport_2023-02-23+104+20230309

SimpleReport_2023-02-23+105+20230309

SimpleReport_2023-02-23+106+20230309

SimpleReport_2023-02-23+107+20230309

SimpleReport_2023-02-23+108+20230309

SimpleReport_2023-02-23+109+20230309

SimpleReport_2023-02-23+110+20230309

SimpleReport_2023-02-23+111+20230309

SimpleReport_2023-02-23+112+20230309

SimpleReport_2023-02-23+113+20230309

SimpleReport_2023-02-23+114+20230309

SimpleReport_2023-02-23+115+20230309

SimpleReport_2023-02-23+116+20230309

SimpleReport_2023-02-23+117+20230309

SimpleReport_2023-02-23+118+20230309

SimpleReport_2023-02-23+119+20230309

SimpleReport_2023-02-23+120+20230309

SimpleReport_2023-02-23+121+20230309

SimpleReport_2023-02-23+122+20230309

SimpleReport_2023-02-23+123+20230309

SimpleReport_2023-02-23+124+20230309

SimpleReport_2023-02-23+125+20230309

SimpleReport_2023-02-23+126+20230309

SimpleReport_2023-02-23+127+20230309

SimpleReport_2023-02-23+128+20230309

SimpleReport_2023-02-23+129+20230309

SimpleReport_2023-02-23+130+20230309

SimpleReport_2023-02-23+131+20230309

SimpleReport_2023-03-07+132+20230309

SimpleReport_2023-03-07+133+20230309

SimpleReport_2023-03-07+134+20230309

SimpleReport_2023-03-07+135+20230309

SimpleReport_2023-03-07+136+20230309

SimpleReport_2023-03-07+137+20230309

SimpleReport_2023-03-07+138+20230309

SimpleReport_2023-03-07+139+20230309

SimpleReport_2023-03-07+140+20230309

SimpleReport_2023-03-07+141+20230309

SimpleReport_2023-03-07+142+20230309

SimpleReport_2023-03-07+143+20230309

SimpleReport_2023-03-07+144+20230309

SimpleReport_2023-03-07+145+20230309

SimpleReport_2023-03-07+146+20230309

SimpleReport_2023-03-07+147+20230309

SimpleReport_2023-03-07+148+20230309

SimpleReport_2023-03-07+149+20230309

SimpleReport_2023-03-07+150+20230309

SimpleReport_2023-03-07+151+20230309

SimpleReport_2023-03-07+152+20230309

SimpleReport_2023-03-07+153+20230309

SimpleReport_2023-03-07+154+20230309

SimpleReport_2023-03-07+155+20230309

SimpleReport_2023-03-07+156+20230309

SimpleReport_2023-03-07+157+20230309

SimpleReport_2023-03-07+158+20230309

SimpleReport_2023-03-07+159+20230309

SimpleReport_2023-03-07+160+20230309

SimpleReport_2023-03-07+161+20230309

SimpleReport_2023-03-07+162+20230309

SimpleReport_2023-03-07+163+20230309

SimpleReport_2023-03-07+164+20230309

SimpleReport_2023-03-07+165+20230309

SimpleReport_2023-03-07+166+20230309

SimpleReport_2023-03-07+167+20230309

SimpleReport_2023-03-07+168+20230309

SimpleReport_2023-03-07+169+20230309

SimpleReport_2023-03-07+170+20230309

SimpleReport_2023-03-07+171+20230309

SimpleReport_2023-03-07+172+20230309

SimpleReport_2023-03-07+173+20230309

SimpleReport_2023-03-07+174+20230309

SimpleReport_2023-03-07+175+20230309

SimpleReport_2023-03-07+176+20230309

SimpleReport_2023-03-07+177+20230309

SimpleReport_2023-03-07+178+20230309

SimpleReport_2023-03-07+179+20230309

SimpleReport_2023-03-07+180+20230309

SimpleReport_2023-03-07+181+20230309

SimpleReport_2023-03-07+182+20230309

SimpleReport_2023-03-07+183+20230309

SimpleReport_2023-03-07+184+20230309

SimpleReport_2023-03-07+185+20230309

SimpleReport_2023-03-07+186+20230309

SimpleReport_2023-03-07+187+20230309

SimpleReport_2023-03-07+188+20230309

SimpleReport_2023-03-07+189+20230309

SimpleReport_2023-03-07+190+20230309

SimpleReport_2023-03-07+191+20230309

SimpleReport_2023-03-07+192+20230309

SimpleReport_2023-03-07+193+20230309

SimpleReport_2023-03-07+194+20230309

SimpleReport_2023-03-07+195+20230309

SimpleReport_2023-03-07+196+20230309

SimpleReport_2023-03-07+197+20230309

SimpleReport_2023-03-07+198+20230309

SimpleReport_2023-03-07+199+20230309

SimpleReport_2023-03-07+200+20230309

SimpleReport_2023-03-07+201+20230309

SimpleReport_2023-03-07+202+20230309

SimpleReport_2023-03-07+203+20230309

SimpleReport_2023-03-07+204+20230309

SimpleReport_2023-03-07+205+20230309

SimpleReport_2023-03-07+206+20230309

SimpleReport_2023-03-07+207+20230309

SimpleReport_2023-03-07+208+20230309

SimpleReport_2023-03-07+209+20230309

SimpleReport_2023-03-07+210+20230309

SimpleReport_2023-03-07+211+20230309

SimpleReport_2023-03-07+212+20230309

SimpleReport_2023-03-07+213+20230309

SimpleReport_2023-03-07+214+20230309

SimpleReport_2023-03-07+215+20230309

SimpleReport_2023-03-07+216+20230309

SimpleReport_2023-03-07+217+20230309

SimpleReport_2023-03-07+218+20230309

SimpleReport_2023-03-07+219+20230309

SimpleReport_2023-03-07+220+20230309

SimpleReport_2023-03-07+221+20230309

SimpleReport_2023-03-07+222+20230309

SimpleReport_2023-03-07+223+20230309

SimpleReport_2023-03-07+224+20230309

SimpleReport_2023-03-07+225+20230309

SimpleReport_2023-03-07+226+20230309

SimpleReport_2023-03-07+227+20230309

SimpleReport_2023-03-07+228+20230309

SimpleReport_2023-03-07+229+20230309

SimpleReport_2023-03-07+230+20230309

SimpleReport_2023-03-08+231+20230309

SimpleReport_2023-03-08+232+20230309

SimpleReport_2023-03-08+233+20230309

SimpleReport_2023-03-08+234+20230309

SimpleReport_2023-03-08+235+20230309

SimpleReport_2023-03-08+236+20230309

SimpleReport_2023-03-08+237+20230309

SimpleReport_2023-03-08+238+20230309

SimpleReport_2023-03-08+239+20230309

SimpleReport_2023-03-08+240+20230309

SimpleReport_2023-03-08+241+20230309

SimpleReport_2023-03-08+242+20230309

SimpleReport_2023-03-08+243+20230309

SimpleReport_2023-03-08+244+20230309

SimpleReport_2023-03-08+245+20230309

SimpleReport_2023-03-08+246+20230309

SimpleReport_2023-03-08+247+20230309

SimpleReport_2023-03-08+248+20230309

SimpleReport_2023-03-08+249+20230309

SimpleReport_2023-03-08+250+20230309

SimpleReport_2023-03-08+251+20230309

SimpleReport_2023-03-08+252+20230309

SimpleReport_2023-03-08+253+20230309

SimpleReport_2023-03-08+254+20230309

SimpleReport_2023-03-08+255+20230309

SimpleReport_2023-03-08+256+20230309

SimpleReport_2023-03-08+257+20230309

SimpleReport_2023-03-08+258+20230309

SimpleReport_2023-03-08+259+20230309

SimpleReport_2023-03-08+260+20230309

SimpleReport_2023-03-08+261+20230309

SimpleReport_2023-03-08+262+20230309

SimpleReport_2023-03-08+263+20230309

SimpleReport_2023-03-08+264+20230309

SimpleReport_2023-03-08+265+20230309

SimpleReport_2023-03-08+266+20230309

SimpleReport_2023-03-08+267+20230309

SimpleReport_2023-03-08+268+20230309

SimpleReport_2023-03-08+269+20230309

SimpleReport_2023-03-08+270+20230309

SimpleReport_2023-03-08+271+20230309

SimpleReport_2023-03-08+272+20230309

SimpleReport_2023-03-08+273+20230309

SimpleReport_2023-03-08+274+20230309

SimpleReport_2023-03-08+275+20230309

SimpleReport_2023-03-08+276+20230309

SimpleReport_2023-03-08+277+20230309

SimpleReport_2023-03-08+278+20230309

SimpleReport_2023-03-08+279+20230309

SimpleReport_2023-03-08+280+20230309

SimpleReport_2023-03-08+281+20230309

SimpleReport_2023-03-08+282+20230309

SimpleReport_2023-03-08+283+20230309

SimpleReport_2023-03-08+284+20230309

SimpleReport_2023-03-08+285+20230309

SimpleReport_2023-03-08+286+20230309

SimpleReport_2023-03-08+287+20230309

SimpleReport_2023-03-08+288+20230309

SimpleReport_2023-03-08+289+20230309

SimpleReport_2023-03-08+290+20230309

SimpleReport_2023-03-08+291+20230309

SimpleReport_2023-03-08+292+20230309

SimpleReport_2023-03-08+293+20230309

SimpleReport_2023-03-08+294+20230309

SimpleReport_2023-03-08+295+20230309

SimpleReport_2023-03-08+296+20230309

SimpleReport_2023-03-08+297+20230309

SimpleReport_2023-03-08+298+20230309

SimpleReport_2023-03-08+299+20230309

SimpleReport_2023-03-08+300+20230309

SimpleReport_2023-03-08+301+20230309

SimpleReport_2023-03-08+302+20230309

SimpleReport_2023-03-08+303+20230309

SimpleReport_2023-03-08+304+20230309

SimpleReport_2023-03-08+305+20230309

SimpleReport_2023-03-08+306+20230309

SimpleReport_2023-03-08+307+20230309

SimpleReport_2023-03-08+308+20230309

SimpleReport_2023-03-08+309+20230309

SimpleReport_2023-03-08+310+20230309

SimpleReport_2023-03-08+311+20230309

SimpleReport_2023-03-08+312+20230309

SimpleReport_2023-03-08+313+20230309

SimpleReport_2023-03-08+314+20230309

SimpleReport_2023-03-08+315+20230309

SimpleReport_2023-03-08+316+20230309

SimpleReport_2023-03-08+317+20230309

SimpleReport_2023-03-08+318+20230309

SimpleReport_2023-03-08+319+20230309

SimpleReport_2023-03-08+320+20230309

SimpleReport_2023-03-08+321+20230309

SimpleReport_2023-03-08+322+20230309

SimpleReport_2023-03-08+323+20230309

SimpleReport_2023-03-08+324+20230309

SimpleReport_2023-03-08+325+20230309

SimpleReport_2023-03-08+326+20230309

SimpleReport_2023-03-08+327+20230309

SimpleReport_2023-03-08+328+20230309

SimpleReport_2023-03-08+329+20230309

SimpleReport_2023-03-08+330+20230309

SimpleReport_2023-03-08+331+20230309

SimpleReport_2023-03-08+332+20230309

SimpleReport_2023-03-08+333+20230309

SimpleReport_2023-03-08+334+20230309

Sincerely,

Jenni
*Attached file below*

[https://app.zenhub.com/files/304423150/ed59478e-1507-47ca-9a4d-0077736e7235/download](https://app.zenhub.com/files/304423150/ed59478e-1507-47ca-9a4d-0077736e7235/download)

**Comment by rnz6** [comment]
Update from 3/14: 

Jessica,

We received another file with this issue.  An updated tracking sheet with MSH segments is attached.  MSH-10s are listed below.  Please pause submissions from this location until the issue is fixed, and resubmit corrections with updated MSH-7 values as soon as possible. 

 

497145458+1+20230314

496569785+84+20230314

496569823+15+20230314

496569931+86+20230314

496569957+76+20230314

496570224+16+20230314

496570347+87+20230314

496570379+77+20230314

496575982+17+20230314

496579073+78+20230314

496579996+79+20230314

496581345+18+20230314

496582744+1+20230314

496584388+2+20230314

496586863+19+20230314

496587884+3+20230314

496591841+20+20230314

496624407+4+20230314

496628602+21+20230314

496674743+70+20230314

496816166+22+20230314

496818213+80+20230314

496880234+23+20230314

496923234+24+20230314

496954421+2+20230314

497009499+71+20230314

497013424+5+20230314

497055738+25+20230314

497061767+6+20230314

497078173+26+20230314

497080621+7+20230314

497088548+27+20230314

497092541+28+20230314

497092713+29+20230314

497092924+30+20230314

497094153+31+20230314

497095136+32+20230314

497096138+33+20230314

497096347+8+20230314

497096390+9+20230314

497096419+34+20230314

497096647+35+20230314

497096842+10+20230314

497097872+11+20230314

497098252+12+20230314

497099166+36+20230314

497118715+37+20230314

497124279+38+20230314

497126285+39+20230314

497143943+40+20230314

497148799+41+20230314

497149275+13+20230314

497151454+14+20230314

497158836+42+20230314

497161170+43+20230314

497301341+44+20230314

497308484+72+20230314

497321937+45+20230314

497338181+81+20230314

497342256+46+20230314

497396185+73+20230314

497430434+47+20230314

497432023+48+20230314

497516725+85+20230314

497519552+82+20230314

497528833+49+20230314

497538645+50+20230314

497571641+51+20230314

497587855+52+20230314

497589430+53+20230314

497590602+54+20230314

497601029+55+20230314

497604642+56+20230314

497606808+57+20230314

497607837+74+20230314

497607854+58+20230314

497607930+75+20230314

497610113+59+20230314

497610376+83+20230314

497610434+60+20230314

497610735+61+20230314

497610773+62+20230314

497610805+63+20230314

497610830+64+20230314

497610921+65+20230314

497611020+66+20230314

497611032+67+20230314

497611035+68+20230314

497611055+69+20230314

497614180+181+20230314

497614213+191+20230314

497615864+107+20230314

497615950+203+20230314

497615978+116+20230314

497616375+91+20230314

497617009+134+20230314

497617867+147+20230314

497618929+162+20230314

497623621+97+20230314

497625130+178+20230314

497741616+98+20230314

497742270+3+20230314

497745213+100+20230314

497766671+99+20230314

497767978+179+20230314

497770184+180+20230314

497771895+182+20230314

497809941+209+20230314

497941704+5+20230314

497942887+183+20230314

497943754+6+20230314

497944544+184+20230314

497996841+186+20230314

498008551+101+20230314

498023911+187+20230314

498031319+102+20230314

498034232+188+20230314

498040812+190+20230314

498047131+192+20230314

498047482+103+20230314

498047916+193+20230314

498053639+104+20230314

498054143+217+20230314

498054414+194+20230314

498055404+105+20230314

498056734+195+20230314

498057097+218+20230314

498059625+106+20230314

498061410+196+20230314

498061996+197+20230314

498062197+198+20230314

498062372+185+20230314

498063315+199+20230314

498063478+108+20230314

498063487+200+20230314

498063638+201+20230314

498063649+202+20230314

498063731+109+20230314

498064038+110+20230314

498064114+111+20230314

498064236+204+20230314

498064290+205+20230314

498064813+112+20230314

498065704+219+20230314

498066104+88+20230314

498066640+113+20230314

498067001+114+20230314

498067090+115+20230314

498067121+89+20230314

498068315+117+20230314

498071591+90+20230314

498077310+7+20230314

498084398+210+20230314

498085155+118+20230314

498085647+206+20230314

498086650+119+20230314

498089820+211+20230314

498091319+8+20230314

498091497+9+20230314

498091711+10+20230314

498092028+11+20230314

498092124+12+20230314

498092369+13+20230314

498092588+14+20230314

498092733+15+20230314

498092899+16+20230314

498093140+17+20230314

498093361+18+20230314

498093606+19+20230314

498093906+20+20230314

498094268+21+20230314

498094520+22+20230314

498094635+23+20230314

498094787+24+20230314

498094999+25+20230314

498095149+26+20230314

498095448+27+20230314

498095686+28+20230314

498095996+29+20230314

498096246+30+20230314

498096375+31+20230314

498096649+32+20230314

498096825+212+20230314

498096883+33+20230314

498097307+34+20230314

498097792+35+20230314

498098159+36+20230314

498098233+37+20230314

498098403+38+20230314

498098546+39+20230314

498098667+4+20230314

498101876+213+20230314

498103838+120+20230314

498106770+121+20230314

498107012+122+20230314

498117574+123+20230314

498118207+124+20230314

498118609+125+20230314

498119291+126+20230314

498125237+127+20230314

498126301+128+20230314

498127351+129+20230314

498127418+207+20230314

498127578+92+20230314

498127666+130+20230314

498128036+131+20230314

498129085+132+20230314

498130051+133+20230314

498130329+135+20230314

498130750+136+20230314

498130878+137+20230314

498130986+93+20230314

498132168+138+20230314

498132281+139+20230314

498132344+140+20230314

498132358+141+20230314

498132521+142+20230314

498132584+143+20230314

498132618+94+20230314

498132648+144+20230314

498132717+145+20230314

498133129+146+20230314

498133457+95+20230314

498133804+148+20230314

498133932+149+20230314

498134139+150+20230314

498134331+151+20230314

498134980+96+20230314

498135028+152+20230314

498137207+153+20230314

498137290+154+20230314

498138553+155+20230314

498138597+214+20230314

498138879+156+20230314

498139739+157+20230314

498139966+215+20230314

498140079+189+20230314

498140283+158+20230314

498141470+159+20230314

498141496+216+20230314

498144182+160+20230314

498146032+161+20230314

498155033+163+20230314

498159000+164+20230314

498159275+165+20230314

498159366+208+20230314

498159778+166+20230314

498162039+167+20230314

498162679+168+20230314

498162755+169+20230314

498163906+170+20230314

498164821+171+20230314

498166230+172+20230314

498166340+173+20230314

498166399+174+20230314

498166420+175+20230314

498166501+176+20230314

498166665+177+20230314

Sincerely,

Jenni

**Comment by rnz6** [comment]
*File attached via user*

[https://app.zenhub.com/files/304423150/62cf7b9d-b677-455b-82d6-e82ccfe81eb8/download](https://app.zenhub.com/files/304423150/62cf7b9d-b677-455b-82d6-e82ccfe81eb8/download)

**Comment by LaFreda1** [comment]
@kant777 any updates or blockers for this ticket?

**Comment by wcollin89** [comment]
@LaFreda1 @rnz6 
Upon researching these submissions, they appear to be CSV uploads coming from "Maleng Regional Justice Center" under the "Public Health - Seattle & King County" organization. From what I can see in those messages, the carriage return may have been copied and pasted into the template for each entry that was submitted. That could explain why the issue occurs on all of those submissions.

The facility that is listed in the reports and HL7 messages, "KC POCT LAB", is **not** an existing facility within SimpleReport or ReportStream. The CLIA number listed is associated with four facilities, which actually seem to be two facilities with duplicates under another organization. One of which is the Maleng Regional Justice Center previously mentioned, the other is King County Correctional Facility.

Please let me know what, if any, specific values (e.g. report ID, organization ID, the duplicate facilities' org, etc.) you would like me to provide from my research - I want to make sure I am providing what is needed and not excessive or unnecessary data.

**Comment by sliu1000** [comment]
@LaFreda1 @kant777 

We just received a high priority for this to be resolved.

Good morning,
I am wondering if we can escalate the attention being given to ticket #8630?  
As mentioned by Jenni below, there are currently over 700 errored messages that do not process for WA public health.  We are concerned about the timeframe for receiving resubmission of corrected files for inclusion in our surveillance system for potential public health action.  Also, we have not seen a response to the request to not have any additional submissions sent to us that contain this issue.  Are there limitations on pausing the affected submitter until a fix for the problem is put into place?
Appreciate additional information around both mitigation and solutioning plans for this issue.
Thanks,
Julie

**Comment by rnz6** [comment]
Follow up has been sent.

Hi Julie,

An engineer has been assigned to your ticket and is investigating the issue. I can update the ticket to pause the submissions, however, I cannot guarantee how soon the fix will be in.

We appreciate your patience as we work through sorting out the MSH-7 values issue.

**Comment by brick-green** [comment]
@LaFreda1 @rnz6 @wcollin89 Has anyone made a request to the simple report submitter to stop submitting with the carriage return? Seems like WA is saying they are still doing this?

**Comment by rnz6** [comment]
@brick-green I will reach out to SimpleReport now

**Comment by rnz6** [comment]
Email to submitter:

Hi Karin,

We receive a complaint from Washington state that the submissions they receive recently from Maleng Regional Justice Center/KC POCT LAB has a carriage return error.

Please pause all CSV submissions with the carriage address and inspect your files for adequate formatting prior to resubmitting to SimpleReport.

The issue is an encoded line break in the address field between AVE and SUITE 1000 that creates a structurally incorrect message.  

Once the address is fixed, please resubmit your CSV uploads backdating to March 6, 2023.

Please let me know if you have any further questions or concerns. 

Thank you, 
 
Jessica

**Comment by oslynn** [comment]
@kant777 , I put these three files in your KeyBase.  I also put the instruction to fix them in your Slack channel.
cdcprime_testing_20230306223519_365607.hl7
cdcprime_testing_20230309023520_225532.hl7
cdcprime_testing_20230314013602_663876.hl7

**Comment by kant777** [comment]
Done! i fixed the errors and resubmitted all the files and i see it is successful

File sent: upload-covid-19-6d89e922-61bf-47a3-9399-9d403e2e0202-20230314000436.csv
report id: 9c73eaee-5851-4638-8a05-129a67696ae3

File sent: upload-covid-19-9b932a39-cbbb-4d40-97e0-4eead338c3d0-20230309010557.csv
report id: b8a908bc-349d-4dcb-9274-b11c30ec51da

File sent: upload-covid-19-c0c34a17-f677-4333-ba6f-e5486bc6de9b--20230306204125.csv
report id: b84b9fdf-67b6-4a40-a30d-ca6e3f1a631c

**Comment by LaFreda1** [comment]
@rnz6 Will you confirm that this was successful on WA's end? Thanks!

**Comment by brick-green** [comment]
@sliu1000 I don't think we ever actually paused the sender. So we should be good
