### ISSUE TITLE
PA - Prod Failure 3/7/23

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#8634]
## Problem statement

We received a notification in slack on a production failure for Pennsylvania.

## What you need to know

- ALERT gov.cdc.prime.router.azure.SendFunction - FAILED SOAP of inputReportId `2ad65afd-81ee-4ee7-828a-24c2ca1e9f73` to endpoint=https://www.ers.health.pa.gov/ELRWCF/ELRService.svc/ELR, soapAction=http://nedss.state.pa.us/2012/B01/elrwcf/IUploadFile/UploadFiles (orgService = pa-phd.elr-philadelphia-hl7), Exception: Server error(POST https://www.ers.health.pa.gov/ELRWCF/ELRService.svc/ELR: 503 Service Unavailable. Text: '<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01//EN''http://www.w3.org/TR/html4/strict.dtd'>",

## Acceptance criteria

Engineer reviews the error message and corrects so we do not receive any more errors for this state in Production.

## To do

- Assigned to an Engineer
- Investigate the issue
- Correct

**Comment by sliu1000** [comment]
Juan has completed the resubmission, Engineering please investigate the issue to ensure everything is in proper order.

**Comment by adegolier** [comment]
@sliu1000 @wcollin89 The resend appears to have worked as far as I can tell. Do we need to get confirmation from them?

**Comment by sliu1000** [comment]
@wcollin89 Wendy, can you please send a confirmation email to confirm the above?

**Comment by wcollin89** [comment]
@sliu1000 @adegolier The State has confirmed receipt of this file and its contents.
