### ISSUE TITLE
Break out RS auth code into separate service

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#8636]
This story is blocked by #8633 and its details will depend on the outcome of that. #8633 will likely spawn more stories (refactoring) and this story will also probably be blocked by those.

**Comment by bishoyayoub** [comment]
@arnejduranovic Please move to ready for grooming or let me know if we should icebox this story.

**Comment by arnejduranovic** [comment]
@bishoyayoub This epic should be ice boxed, it's not a project priority at this time but could be in the future
