### ISSUE TITLE
Upload latest API Programmers Guide PDF to RS Website

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8641]
## Problem statement

The API Programmers Guide PDF has been updated to better serve our users. The latest version should be uploaded in place of the old version on the RS Website.

## What you need to know

- [API Programmers Guide Page with Link](https://reportstream.cdc.gov/resources/programmers-guide)
- [New API Programmers Guide PDF](https://app.zenhub.com/files/304423150/d81e8da6-c139-4f98-b53b-6486e087a1eb/download)

## Acceptance criteria

- [ ] New API Programmers Guide PDF downloads when link clicked
- [ ] Old API Programmers Guide PDF removed

**Comment by audreykwr** [comment]
@GilmoreA6 FYI
