### ISSUE TITLE
Improve error messaging in server2server auth code

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#8642]
### User Story:
As a user of the ReportStream API, I want to have more actionable error messages when authentication fails.

### Description/Use Case

Presently, error messages returned by various portions of our server2server auth code are rather oblique.  ETOR expects many many senders - we need to make the auth code easier to use for them.

We are taking other steps to make our server2server auth easier to use. This includes a public key upload tool, and possible plans for a UI form to test the two calls manually.  Improving the error messaging is part of that.   And it'll make the UI more usable too.

### Risks/Impacts/Considerations

It is important that we NOT aid anyone trying to gain unauthorized access to the system, so all the text/examples of the error messages must be reviewed by @snesm. The error messages should also have a Content expert review them.

### Dev Notes:

Actionable and helpful error messages should be returned to the user by code under TokenFunction.kt, and under the various server2server authenticate and authorized methods.

An alternative would be to have better error messages, but be able to turn them on and off.   For example, we could provide detailed error messaging in Staging, but then the terse error messages in Prod. There are other ways you could do this as well.

All the auth code that needs to be "fixed" is in the .kt files in the `token/` dir.   Good news:   The code already does _copious_ logging of errors, so a pretty simple first pass would be to just return those error strings to the user, as well as logging them.   I think in most or all cases, the code stops on the first error, so there's no need to accumulate an array of error messages.

**IMPORTANT:** The smart on fhir or oauth specs probably have something to say about error messages, so we must ensure we are following them. A link to the relevant specs can be found in this [intro document](https://docs.smarthealthit.org/authorization/best-practices/)

### Acceptance Criteria
- [ ] Auth failures return helpful messages to client
- [ ] All new public error messages approved by @snesm

**Comment by avnieldravid** [comment]
@mkalish can you add a link to the OAuth Spec?

**Comment by arnejduranovic** [comment]
> @mkalish can you add a link to the OAuth Spec?

I added the link

**Comment by chris-kuryak** [comment]
Moved to Public Key Tool backlog improvement epic #8382 since it is not blocking feature launch (per @mkalish) and we can close out the Feature Launch epic.
