### ISSUE TITLE
Two '404' Prod Failures 3/7/23

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#8643]
## Problem statement

Two (2) failures were reported via slack that simply state a "status code 404 error."

## What you need to know

- Exception message: `not-found: Request failed with status code 404 error`
- Client IP is listed as 0.0.0.0 and with a City/State of Herndon, VA
- Operation Name: /file-handler/validate
- Under 'activeMembership,' the "parsedName" value is "vt-doh"

>     not-found: Request failed with status code 404
>     at https://reportstream.cdc.gov/static/js/main.caab66a3.js:2:2802871
>     at c (https://reportstream.cdc.gov/static/js/main.caab66a3.js:2:984768)
>     at Generator._invoke (https://reportstream.cdc.gov/static/js/main.caab66a3.js:2:984521)
>     at Generator.throw (https://reportstream.cdc.gov/static/js/main.caab66a3.js:2:985131)
>     at Cn (https://reportstream.cdc.gov/static/js/main.caab66a3.js:2:990004)
>     at s (https://reportstream.cdc.gov/static/js/main.caab66a3.js:2:990245)

## Acceptance criteria

- Resolve 404 error, ensure any missed data is resubmitted, and confirm no further issues.

## To do

- [x] Assign to engineer
- [ ] Investigate the cause of the 404 error
- [ ] Resolve the underlying issue and confirm normal function

**Comment by oslynn** [comment]
This failure has been resolved and resubmitted.
