### ISSUE TITLE
VT - Production Failure Alert

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#8646]
## **Problem Statement**
Received a Product Fatal Alert via PagerDuty App/Slack.

## **What you need to know**
Error Message:
FATAL-ALERT gov.cdc.prime.router.azure.SendFunction - FAILED Sftp upload of inputReportId 98e60811-9477-4907-9a25-8ae66f9e7829 to SFTPTransportType(host=gs-sftp.ahs.state.vt.us, port=22, filePath=./Prod/ToVDH/, credentialName=null) (orgService = vt-doh.elr), Exception: Connection refused (Connection refused), All retries failed.  Manual Intervention Required.  Send Error report for: 98e60811-9477-4907-9a25-8ae66f9e7829 to vt-doh.elr\u001b[m",
        "3.18.0.0",

## **Acceptance Criteria**
- [x] Please Assign to Engineer 
- [ ] Engineer investigates
- [ ] Provide solution/next steps

## **To Do**
- [ ] Please let Helpdesk know if we need to email the customer or ask any claryfing questions for you.

## **Additional Comments**
If applicable, add screenshots, links, etc. to further explain the ticket

**Comment by GilmoreA6** [comment]
File was resent via last mile resend no 3/8/23
