### ISSUE TITLE
Clean up after keys have been entirely migrated to organizations

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#8659]
## User Story:
As a user, I would like API keys to be handled consistently

## Description/Use Case
When senders no longer store API keys, there are several spots in the code that can now be cleaned up, including some temporary utilities to support reading the keys from the sender or organization.

## Risks/Impacts/Considerations
None

## Dev Notes:
- Originally keys were read from the sender
- The code modified to read keys from the organization, but in order to remain backwards compatible the keys continue to be read from the sender as well as the organization
- Grep the code base for the ticket number and clean up the relevant code
- Remove SettingsProvider.getKeys
- Update the handling [issuer](https://github.com/CDCgov/prime-reportstream/blob/f59c27c45b8fa801a63fcbb208f90f12296cfbcb/prime-router/src/main/kotlin/tokens/Server2ServerAuthentication.kt#L212) to treat it as organization name and then as a sender name if an organization is not found

## Acceptance Criteria
- Keys are only read from the organization
- Senders no longer have a key field 
- The utility code to migrate keys are removed
- The token endpoints supports either sender name or organization name as the issuer (Note:   We want new onboarding  organizations to just use `iss=orgName`, but for backward compatibility we'll continue to accept `iss=orgName.senderName` as an undocumented feature.
- The CLI utilities around authentication and keys operate on an organization rather than a sender

**Comment by bishoyayoub** [comment]
Update to User Story template please @mkalish

**Comment by mkalish** [comment]
@bishoyayoub Do you have a link to the template?
