### ISSUE TITLE
tech debt:  can't create a new Sender child every time we have a new datatype

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#8661]
### User Story
As ReportStream, I should not associate datatypes with specific Sender objects.

### Description/Use Case
Currently, senders in the code are represented by a few different types. The overall parent class is called `Sender`. `Sender` is an abstract class which is extended by `FullELRSender` (used for UP) and `TopicSender` (used for the legacy pipeline). `TopicSender` has subtypes `CovidSender` and `MonkeypoxSender`.

We should avoid creating a new Sender class every time we have a new type of data or new topic - that won't scale, especially with ETOR likely needing a wide variety of data types and/or topics.

### Dev Notes:
The structure of the Sender configuration data needed is dependent on the Pipeline (Old PIpeline, New Pipeline), not on the datatype, nor on the topic.

Based on the proposal in https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/proposals/0020-univeral-pipeline-topics.md, `FullELRSender` will be renamed to `UniversalPipelineSender`, and `TopicSender` will be renamed to `LegacyPipelineSender` (still with subclasses `CovidSender` and `MonkeypoxSender`). Topic will still be used to determine which subclass of `Sender` to use; `full-elr` and `etor-ti` will correspond to `UniversalPipelineSender`, while `covid-19` will correspond to `CovidSender` and `monkeypox` will correspond to `MonkeypoxSender`.

See also:
#8586 ticket design for `topic` usage in the UP.
#8592 ticket for separation of `etor` from existing `full-elr` topic.

### Acceptance Criteria
- [ ] `Sender` subtypes match the proposal documented [here](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/proposals/0020-univeral-pipeline-topics.md)

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8661?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimmyfagan @luis-pabon-tf @mkalish @victor-chaparro
