### ISSUE TITLE
HHS Protect/Palantir is requesting example HL7 messages to test and validate

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#8671]
## Problem statement

We met with the HHS Protect/Palantir team on March 2 to discuss the transition of RS sending HL7 messages instead of CSV. They followed-up on March 9 to ask for example HL7 messages. 

## What you need to know

Email:
Charlee Sherrill <csherrill@palantir.com>
2:12 PM (42 minutes ago)
to John, qva8@cdc.gov, Patricia, rut5@cdc.gov, roy2@cdc.gov, me, brandoncanniff@navapbc.com, lizziemanning@navapbc.com, avnieldravid@navapbc.com, Elizabeth, Michael, Satvik, George, Stephen, Andrew, Mohd, John

Hi all,

 

Thanks again for meeting with us last week. As we begin to configure the pipeline to ingest and parse HL7 messages in HHS Protect, we were wondering if the ReportStream team had any example HL7 messages they could send us so we can test and validate this workflow. Look forward to meeting again next week to discuss next steps. Thank you for your help!

 

Charlee Sherrill

Palantir | Forward Deployed Software Engineer

csherrill@palantir.com | 828.514.0298

## Acceptance criteria

- [ ] HL7 example messages that can be tested and validated by HHS Protect

## To do

- [ ] Assign Engineer
- [ ] Create HL7 examples
- [ ] Send examples to LaFreda to send to HHS Protect

**Comment by brick-green** [comment]
Think I found the issue here. We'll need to make a new schema specific to Protect.

**Comment by brick-green** [comment]
Here's the test file for Protect. Github doesn't let you attach a .HL7 so I changed the extension to .TXT [protect-covid-19-hl7-bf12ce10-e7ca-4484-b722-b0a5130c0582-20230321193700.txt](https://github.com/CDCgov/prime-reportstream/files/11032878/protect-covid-19-hl7-bf12ce10-e7ca-4484-b722-b0a5130c0582-20230321193700.txt)

**Comment by LaFreda1** [comment]
Closing this ticket until we communicate with HHS protect again
