### ISSUE TITLE
Receive sample data from ETOR through ReportStream

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#8676]
### User Story:

As the simulated hospital defined in ./settings/staging/0149-etor.yml, I should be able to receive FHIR data sent from the ETOR sender, also defined in ./settings/staging/0149-etor.yml, as HL7 V2 in order to enable ETOR engineers to test sending their data to a PHL. This should work in local and staging.

### Description/Use Case
Presently, if you send an ETOR FHIR message it will NOT end up in the simulated PHL's SFTP bucket.

Currently both ETOR sender and PHL receiver are set up in ./settings/staging/0149-etor.yml. We just need to configure:
1. The receiver filter(s) to receive the sender's message.
2. Possibly the contents of the senders message, defined in this [PR](https://github.com/CDCgov/trusted-intermediary/pull/207) so the receiver has something to filter on. 

### Dev Notes:

To set up to locally simulate sending data from the ETOR Service module to ReportStream:
1. Install the etor config:  `./prime multiple-settings set --input ./settings/staging/0149-etor.yml`
3. If you are running locally, and are not testing auth stuff, you can skip uploading a public key.
4. Grab [the fake etor FHIR data in Flexion's PR 207](https://github.com/CDCgov/trusted-intermediary/pull/207/files) and put it in a local file called `etor.fhir`.
5. Get rid of the newlines so its in "ndjson" format:   `tr '\n' ' ' < etor.fhir > etor.ndjson`
6.  Submit the etor.ndjson file to a locally running reportstream:  `curl -X POST -H "client:flexion.etor-service-sender"  -H "content-type:application/fhir+ndjson" --data-binary "@./etor.ndjson" "http://localhost:7071/api/waters"`

### Acceptance Criteria
- [ ] Via the Sender `etor-service-sender`, ReportStream can successfully accept the example FHIR submission [found in Flexion's PR 207](https://github.com/CDCgov/trusted-intermediary/pull/207/files). If there is something wrong with the data, we need to have Flexion change it instead of changing the RS system.
- [ ] Furthermore ,ReportStream can successfully convert, filter, batch and send that data to the `simulated-lab` Receiver.
- [ ] The data is sent from ReportStream to `simulated-lab` in an HL7v2 format (Could be OML or other - we don't care that much about the exact data format for this ticket - just that it sends some sort of HL7v2

Getting this working will likely involve changing the filters and other config info 0149-etor.yml configuration, the FHIR data, and maybe the kotlin code.

Note that `etor-service-sender` and `simulated-lab` are found in: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/settings/staging/0149-etor.yml.

**Comment by bishoyayoub** [comment]
@arnejduranovic please see comment below.

**Comment by arnejduranovic** [comment]
@avnieldravid I don't understand the request for two tickets. A simple "fix" for this ticket is to update the receiver filter to accept data coming from a fake state, let's say "FX" (short for flexion), and then just add the state data to Flexion's sample file (which is not a RS side change). I don't think any code changes will be made, just configuration.

The real fix for this, I'm guessing, is using topics. But that's a set of different stories on the backlog that will take some work.

The point of this ticket is to just get something set up so Flexion can test the whole flow. @jimduff-usds any additional thoughts or corrections?

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8676?planning-poker) with Zenhub @arnejduranovic @carlosfelix2 @PatriciaPerozoUSDS @victor-chaparro @mkalish @jimmyfagan @thetaurean @JessicaWNava
