### ISSUE TITLE
5 MD - Secondary Feed Production Error - Please Resubmit

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#8679]
## **Problem Statement**
Received via PagerDuty over the weekend on 3 production errors in MD secondary feed.

## **What you need to know**
FAILED Sftp upload of inputReportId `3646f165-103e-4c40-bb34-179c39b4bbb0` to SFTPTransportType(host=essence.health.maryland.gov, port=22, filePath=./OTC Results, credentialName=null) (orgService = md-phd.elr-secondary), Exception: Connection reset, All retries failed.  Manual Intervention Required.  Send Error report for: 3646f165-103e-4c40-bb34-179c39b4bbb0 to md-phd.elr-secondary\u001b

FATAL-ALERT gov.cdc.prime.router.azure.SendFunction - FAILED Sftp upload of inputReportId` aeec3996-d648-46fc-a3a5-aa90d5e48d3e` to SFTPTransportType(host=essence.health.maryland.gov, port=22, filePath=./OTC Results, credentialName=null) (orgService = md-phd.elr-secondary), Exception: Exhausted available authentication methods, All retries failed.  Manual Intervention Required.  Send Error report for: aeec3996-d648-46fc-a3a5-aa90d5e48d3e to md-phd.elr-secondar

FATAL-ALERT gov.cdc.prime.router.azure.SendFunction - FAILED Sftp upload of inputReportId `27a0b883-f7bd-4d58-89ac-cc031b4c7591` to SFTPTransportType(host=essence.health.maryland.gov, port=22, filePath=./OTC Results, credentialName=null) (orgService = md-phd.elr-secondary), Exception: Timeout expired, All retries failed.  Manual Intervention Required.  Send Error report for: 27a0b883-f7bd-4d58-89ac-cc031b4c7591 to md-phd.elr-secondar

FATAL-ALERT gov.cdc.prime.router.azure.SendFunction - FAILED Sftp upload of inputReportId `d9b5288b-4c19-4712-920e-cc732761b964` to SFTPTransportType(host=essence.health.maryland.gov, port=22, filePath=./OTC Results, credentialName=null) (orgService = md-phd.elr-secondary), Exception: Exhausted available authentication methods, All retries failed.  Manual Intervention Required.  Send Error report for: d9b5288b-4c19-4712-920e-cc732761b964 to md-phd.elr-secondary

FATAL-ALERT gov.cdc.prime.router.azure.SendFunction - FAILED Sftp upload of inputReportId `923c64a9-2f63-4ee5-a56e-00042859efc9` to SFTPTransportType(host=essence.health.maryland.gov, port=22, filePath=./OTC Results, credentialName=null) (orgService = md-phd.elr-secondary), Exception: Connection reset, All retries failed.  Manual Intervention Required.  Send Error report for: 923c64a9-2f63-4ee5-a56e-00042859efc9 to md-phd.elr-secondary

## **Acceptance Criteria**
-Please resubmit and make sure its successfully sent

## **To Do**
none

## **Additional Comments**
none

**Comment by Jcavallo7** [comment]
Resubmitted this morning, closing ticket.
