### ISSUE TITLE
Ignore third-party browser extension/injected scripts errors

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8688]
## Problem statement

We have no control over third-party browser extensions/injected scripts so we shouldn't be alerting our poor on-call members to exceptions thrown by them.

## What you need to know

- The [withInsights decorator](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/TelemetryService.ts#L96) reports console.warn and console.error calls to Azure, which triggers PagerDuty alerts

## Acceptance criteria

- [ ] Exceptions from third-party extensions/scripts are not reported to Azure/PagerDuty

**Comment by jpandersen87** [comment]
This was accomplished with the custom console object work.
