### ISSUE TITLE
Identify which observation has been filtered out by the condition filter

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#8689]
### User Story:
As a sender, I want to be able to query the submission history and have it tell me which observations have been filtered out by the condition filter.

### Description/Use Case
When I query the submission history and get an error that observations were filtered out, that error should return which observations(s) were filtered out and, ideally, the observation id will be included in the error message. Alternatively, the code could be included

### Acceptance Criteria
- [ ] Some identifying information, preferably the id, is returned when an observation does not pass the condition filter.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8689?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @mkalish @thetaurean @victor-chaparro
