### ISSUE TITLE
FAQ Website Content Creation/Update

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8691]
## Problem statement
The website serves as the first line of defense in answering a visitor's questions. Both senders and receivers currently email the support team with common questions that could be answered with improved content on the ReportStream website. Allowing users and visitors to answer their own questions on the website would reduce the time the Support team spends answering common questions via email. So ReportStream should answer the most common questions on the website.

Since the FAQ has not been updated in a while, this epic is to update the FAQ with answers to the most common questions.

## What to Know
- While the FAQ page is not ideal for content like this, the scope of this epic is to only add content to the existing FAQ page so that the support team can direct people to it as the first line of defense in answering common questions. Improvements to the FAQ page and how it works can come in the future.

## Acceptance criteria

- [x] Edits made and approved based on Sharon's list/docs
- [x] Follow up ticket for eng to update

## To do (Steps to fulfill ACs)

- [x] Review updated answer docs
- [x] Draft any edits
- [x] Get feedback/approval on any edits
- [x] Shared with eng to make changes

[Final updated content](https://docs.google.com/document/d/1B7UdmekWd68nBet8_Ls7QLBRJL6YtjPJ/edit#heading=h.u60md9rmxkia)

**Comment by audreykwr** [comment]
@chris-kuryak I just need to confirm I have the most updated question list.. feel free to link if you know you have it

**Comment by chris-kuryak** [comment]
This is the latest I have. @sliu1000 We are ONLY looking at updating the FAQ content in this ticket, and just confirming that the ones in highlighted Blue are still the most common questions?
https://app.box.com/file/1060732123953?s=mj0wg2haui7v6zq964efigbg934slkld

@audreykwr This may require some back and forth with @sliu1000. Let me know if I can help facilitate.

**Comment by audreykwr** [comment]
@chris-kuryak @sliu1000 I've also been messaging with Jessica about her docs to double check this, so we'll see if she can get me what we need

**Comment by audreykwr** [comment]
@chris-kuryak @lizzieamanning after chatting with Jessica, she has some new docs they would prefer I reference for this but I wasn't able to get those in time for this sprint so we'll get to this next sprint. This will go smoother when we nail down our content request processes and templates and such.

**Comment by Andrey-Glazkv** [comment]
Need more clarity on it - Jessica Cox - Andrey to remind Audrey about it

**Comment by sliu1000** [comment]
@Andrey-Glazkv @audreykwr 

Please find attached a list of the FAQ questions. Some of them are from the current website but I included them so it would be in an organized fashion.

Also, please reference the box for the orginal document Jessica create if needed:  https://app.box.com/integrations/officeonline/openOfficeOnline?fileId=1173208754563&sharedAccessCode= 

FAQ website: https://reportstream.cdc.gov/support/faq

[https://app.zenhub.com/files/304423150/6684eda4-463c-4d5c-9480-3053a96a3dc3/download]

**Comment by lizzieamanning** [comment]
@sliu1000 can you clarify who the user @rnz6 is?

**Comment by chris-kuryak** [comment]
Next step: Create the engineering work ticket to update the content on the FAQ page. No handoff meeting required.
@audreykwr to add content doc to this ticket.

cc: @Andrey-Glazkv

**Comment by audreykwr** [comment]
Content doc in the description section. @chris-kuryak @Andrey-Glazkv who creates the eng ticket?

**Comment by chris-kuryak** [comment]
Engr ticket created
