### ISSUE TITLE
Design how to configure date formats as part of receiver transforms

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#8694]
### **User Story:**
As a receiver, I want to be able to receive dates in the format I'm expecting.

### **Description/Use Case**
Currently the COVID pipeline has the ability to configure the date time format for receivers using this setting `useHighPrecisionHeaderDateTimeFormat:` If set to true the date will include milliseconds. We need to find a way to configure date formats for receivers.

### **Risks/Impacts/Considerations**
The FHIR to HL7 v2 library was including milliseconds to Datetimes. That had to be turned off because CA was returning validation errors on that.

### **Dev Notes:**

- The `convertDateTimeToHL7` function in `FhirPathUtils.kt` was adding milliseconds to datetime. That had to be removed for CA.

- We might need to create a custom FHIR function that allows you to pass a format and format the date time accordingly.

### **Acceptance Criteria**

- [ ] Design how dates can be formatted for receivers and document the design.
- [ ] Present the design  and get buy-in from the Platform team.

**Comment by bishoyayoub** [comment]
@victor-chaparro Need to meet with team for consensus on design

**Comment by oslynn** [comment]
See: FhirPathUtilTests.kt: `test converDateTimeToHL7`()
