### ISSUE TITLE
Require the fields required by RADx MARS

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#8695]
### User Story:
As ReportStream, I want to follow the RADX MARS spec and enforce that their required fields are filled out.

### Description/Use Case
We want to add validation that will cause a message to fail if it does not have the fields required by the RADx MARS spec.

### Dev Notes:
Require the fields that are marked as required in column F of https://docs.google.com/spreadsheets/d/15dKu5zSY23-VVL0oJphILQyHjyDoj_WmTmXUxGXinzQ/edit#gid=0 and are not already coming through (marked in column K)

### Acceptance Criteria
- [] All required fields have validation enforcing their requirement and return an error when not filled out rather than sending the message.

**Comment by arnejduranovic** [comment]
@JessicaWNava Please update to use User Story template and flesh out.

**Comment by arnejduranovic** [comment]
@JessicaWNava Is this story blocked by any validation stories?

**Comment by JessicaWNava** [comment]
> @JessicaWNava Is this story blocked by any validation stories?

Yes, I think so, though didn't realize that at the time. Added the epic as a blocker.
