### ISSUE TITLE
Implement the conditionals to match RADx MARS specification

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#8696]
### User Story:
As a receiver, I want to receive HL7 v2 data in the RADx MARS format, so I can process the data in a format I can support.

### Description/Use Case
The comments in column H of https://docs.google.com/spreadsheets/d/15dKu5zSY23-VVL0oJphILQyHjyDoj_WmTmXUxGXinzQ/edit#gid=0 sometimes supply a conditional that we do not follow. See column L for the conditionals that need to be implemented.

### Risks/Impacts/Considerations
There were a few that we said we needed to push back on, we sent an email and have followed up on those. They can be ignored for this ticket and found in the spreadsheet above (column J).

### Dev Notes:
We should create a separate RadxMars transform that can be extended by others. Special consideration should be taken to determine most appropriate place for such a transform (rx).

### Acceptance Criteria
- [ ] The fields specified in the spreadsheet are updated.
- [ ] Base RadxMars transform created

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8696?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimmyfagan @mkalish @PatriciaPerozoUSDS @thetaurean @TurkeyFried @victor-chaparro
