### ISSUE TITLE
Base10 Genetics Onboarding – Create Org and Sender Settings  

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#8710]
### Acceptance Criteria 
- [x] Added to organization.yml and create yamlitos  
    - [x] Customer status = testing  
    - [x] For HL7 senders, schemaName: hl7/hl7-ingest-covid-19-training  

- [ ] Added to prod settings table  
- [ ] Added to staging settings table  
- [x] Key exchange  
    - [x] 1. Shared secret  
         - [x] Created API keys in Azure staging   
         - [x] Created API keys in Azure prod  
         - [x]  Sent API keys to Sender via Keybase  
     - [ ] 2. Token auth  
         - [ ] Received public key from sender in staging  
              - [ ] Saved public key in keybase  
         - [ ] Received public key from sender in prod  
              - [ ] Saved public key in keybase  
         - [ ] Associated public key with sender settings in staging  
         - [ ] Associated public key with sender settings in prod 

FYI: this ticket can be completely concurrently with “Validate Test Files” ticket for this API sender 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with sender 
- [ ] RS team member who originates this ticket: add any dependencies, as needed 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Sender" 
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by oslynn** [comment]
Good morning, Steve,

I putted the curl commands include API Keys for staging and prod.  

Please DO NOT send any file yet until we are done with validation.  
Your setting are not yet approve to install in both environments.

Very respectfully,
-Ott Sathngam
CDC RS ENG.

**Comment by Jcavallo7** [comment]
*update from user*

Good evening Ott,

 

That is great news!  Thank you so much to you and your team for your help and support so far.  We look forward to sending live results in production next week! 

 

Have a great weekend!

**Comment by oslynn** [comment]
Done
