### ISSUE TITLE
CovX Onboarding – 2. Testing in Staging and Prod

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#8718]
### Acceptance Criteria 
- [ ] Sender has tested in staging and production 
- [ ] RS engineer has determined the data is good enough and graduates Sender to send Prod data to receiver  

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with sender 
- [ ] RS team member who originates this ticket: add dependencies:  
     - [ ] [name of company] Onboarding – Create Org and Sender Settings
     - [ ] [name of company] Onboarding - Validate Test Files 
- [ ] RS team member who originates this ticket: make sure the following are included when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops," "Sender"
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by sliu1000** [comment]
Update from Sender:

Hey James,

 

We gave the staging environment another try this morning around 8 am EST but still received a 401 unauthorized access error. Is the key loaded in on your side?
Nathan Farmer

**Comment by Jcavallo7** [comment]
*update from user*

Hey James,

 

We’ve given this another shot and still get a 401 unauthorized error…have you been able to make an API call on your end to the endpoint with the parameters noted? Is there some way that we could try this in production without causing issues? And are other users having similar issues in staging?

 

Best,

**Comment by GilmoreA6** [comment]
ey James,

 

We are working to submit data to the staging environment and notice a few different endpoint URLs in the documentation, though I am not sure if these are all examples.

 

Is there a staging endpoint that you need to provide us to submit data to?

 

We’ve tried endpoint https://staging.prime.cdc.gov/api/waters but we receive a 503 - service unavailable error message.

**Comment by sliu1000** [comment]
Message from Sender on Friday:
Hi James,

We’ve added the column for equipment model ID and created a test file with the QS 5 model ID attached to this email.

We have also generated a new private key for production, and I have attached a PEM format public key for you to load in on your end. What date could we target for go-live for this process? We are ready on our end
 

Thank you,


Nathan Farmer
Application Engineer | LabLynx, Inc.
2400 Lake Park Drive, Suite 435 | Smyrna, GA 30080
O: 866-522-5969x1040 | F: 877-832-4129
https://www.Lablynx.com

**Comment by sliu1000** [comment]
Message from Sender on 4/20/23:

Hey James,

We needed to take a bit of time to move things to production on our end, but you should have received a file last night in production. Could you please check and confirm?

Thank you!

Nathan Farmer
Application Engineer | LabLynx, Inc.
2400 Lake Park Drive, Suite 435 | Smyrna, GA 30080
O: 866-522-5969x1040 | F: 877-832-4129
https://www.Lablynx.com

**Comment by GilmoreA6** [comment]
Hi James,

 

Sorry for the delay in reviewing these.  I was off at the start of the week and didn’t get to this before I left. 

 

We’d like to get the COVX lab results coming through ReportStream using their CLIA of 05D2210965 (which we already have built in our CalREDIE system since they used have a direct interface) instead of using the SimpleReport lab ID of CDPH000085.  Please make that change for MSH-4.2. 

 

I don’t see any other significant issues, but we’d like you to send in 5-10 more results using their CLIA to do one more complete review. 

 

And a few questions –

When will the rebranding take effect and will the CLIA change or stay the same? 
Once the test messages are approved, how soon can results be sent in production? 
Is their a backlog of results that need to be reported?  If so, how many, how many positives and over what date range?
 

Thank you,

Ellaison

**Comment by GilmoreA6** [comment]
Hi All,

I am still waiting to hear back about when their rebranding will take place. For the backlog question, they switched over reporting on 4/19 to ReportStream and I can send all those results to production once they are approved. There are about 200 results and only 1 positive. I can move them to production within minutes after approval (it is a small configuration change on our side).

Additional results have been sent with the COVX CLIA.

Filename:
covid-19-c146dc94-40ed-4730-ad0f-b6103b33a7e0-20230507070033.hl7

**Comment by GilmoreA6** [comment]
Hi All,

COVX let me know the rebranding is on hold. Did you get a chance to review the below message? Please let me know if there is anything needed here.

Thanks,

James

**Comment by GilmoreA6** [comment]
Moved to production 6/2
