### ISSUE TITLE
Style guide development

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#8722]
## Problem statement

The current style guide for ReportStream could use some updates and refreshing, especially in the glossary/terminology sections. 

## What you need to know

- [Current/past style guide](https://docs.google.com/document/d/1bb36M2doEdKkIsB9RW-mtrCIwjLrPa1t/edit#heading=h.2et92p0)
- [Previous ticket](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/8559)

## Acceptance criteria

- [x] V1 of a new style guide drafted and shared with design/relevant stakeholders for feedback and iteration
- [x] Follow up ticket created for refinement and broader sharing

## To do

- [x] Compare with SimpleReport
- [x] Clean up glossary list
- [ ] ID and refine key terms
- [ ] Writing for the web/accessibility best practices to call out (lower priority - when there are more contributors?)
- [x] ID and refine UX components to call out
- [x] Create separate voice and tone definition work?

**Comment by lizzieamanning** [comment]
@audreykwr flagging for our next 1:1 as I'm curious what level of priority would you give to this work?

**Comment by audreykwr** [comment]
As a quick comment - this is lower priority, currently just occasional background work

**Comment by audreykwr** [comment]
[Draft of style guide](https://docs.google.com/document/d/1N8l6F68pzeyILevuQk8KOlBGFuI-vFJE/edit#)
Follow up tickets to be created as part of new brand and style epic.
