### ISSUE TITLE
Content governance kickoff

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#8724]
## Problem statement

Content governance is a key piece of a cohesive and scalable content strategy. It answers questions like how we decide what to work on, how content gets made and by who, and how we will evaluate our content.

## What you need to know

[Slide deck from meeting](https://docs.google.com/presentation/d/1JnuBGFqcfBwWnQJGr0s9V13IrirXXormdLbhuM2LVZI/edit?usp=sharing)

## Acceptance criteria

- [x] Plan kickoff meeting agenda
- [x] Meet with stakeholders to kick-off process
- [x] Create follow up ticket

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@chris-kuryak this larger pointing is largely because of involvement needed from others, for context. so that is the biggest time factor on this - how available/involved people are or need to be as this progresses

**Comment by chris-kuryak** [comment]
Sounds good!

**Comment by lizzieamanning** [comment]
@audreykwr let's break out the follow up tasks of this ticket as discussed in our 1:1

**Comment by audreykwr** [comment]
@chris-kuryak Closing here. You might noticed it is edited a bit. Notes on those changes are in [the follow up ticket ](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/8807) I just created 

That follow up ticket still needs a little refinement.. but we at least wanted to get it split out as we realize the second part of this was a little less defined that it should be to be included in one ticket
