### ISSUE TITLE
Enable receivers to receive data with the dates in a specified timezone.

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#8737]
### User Story:
As a receiver, I want to receive data with the dates in my local time, as I could in the Covid Pipeline by calling convertDateTimesToReceiverLocalTime.

### Description/Use Case
This will be used to convert the times sent to a receiver into their local date time, or the timezone they request. 

### Risks/Impacts/Considerations
This is needed for CA.

### Dev Notes:
Suggesting that we create a FHIR function that will handle converting date times to receiver local times.

Acceptance Criteria
Dates can have their timezone changed and the time itself changes accordingly.

**Comment by bishoyayoub** [comment]
Adding Jimmy as supplemental resource while Jessica is away.
