### ISSUE TITLE
Allow receivers in the UP to receive HL7 v2 batch data without batch headers

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#8738]
### User Story:
As a receiver, I want to receive HL7 v2 batch data without batch headers, so I can ingest the data the way that I want.

### Description/Use Case
Some receivers may not want to get HL7 v2 batch headers. 
### Dev Notes:
* Need to update the code in HL7MessageHelpers:140 to skip the headers if the settings says so.
Currently, the COVID pipeline setting is `useBatchHeaders`.

### Acceptance Criteria
The UP can send an HL7 v2 batch file to a receiver without batch headers.

**Comment by bishoyayoub** [comment]
@victor-chaparro Can you help confirm if Engagement is working on this so we can remove our labels?

**Comment by adegolier** [comment]
@bishoyayoub I'm working on it! Labels removed.

**Comment by LaFreda1** [comment]
@adegolier any updates on this?
