### ISSUE TITLE
AnavasiDx Onboarding – Validate Receiver  

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#8740]
### Acceptance Criteria 
- [x] Contacted receiver to ask them to validate sample production data (real data) from sender  
- [x] Contacted sender to inform which state we’ll be working with (need sample production data for that state)  
- [x] Data received from sender for the selected state  
     - [x] RS engineer accessed Azure “receive” folder in production to pull out reports from sender  
     - [x] Ensured local receiver configuration for the state matches production  
          - [x] Except the SFTP settings need to point to local  
     - [x] RS engineer submitted reports to the local pipeline  
     - [x] Engineer deliver processed reports to the state by whatever means they specify (email, SFTP, etc.)  
     - [x] Contacted the state to inform them file is ready for validation  
     - [ ] Received confirmation from state that file is validated (clear to go Live after this step) 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with sender and receiver 
- [x] RS team member who originates this ticket: add dependencies:  
     - [x] [name of company] Onboarding – Create Org and Sender Settings 
     - [x] [name of company] Onboarding - Validate Test Files 
     - [x] [name of company] Onboarding – Testing in Staging and Prod 
- [x] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [x] Pipelines: Onboarding & Operations (New) 
     - [x] Labels: "Onboarding-ops" and "Sender" 
     - [x] Epics: [select the epic for this API onboarding sender]

**Comment by GilmoreA6** [comment]
Hi Gene, 

If you are sending test data (no real PHI), that should be sent to our staging environment (no real data/ PHI should be sent to the staging environment). If you are sending to our production endpoint we are expecting that to be real patient data. You are currently in testing mode in production so any submissions sent to the production environment will not be automatically forwarded to any production environment for any jurisdiction. Our last step of onboarding is validating a few real reports from you with the relevant jurisdiction (i.e. if the reports has a patient state of CA, we would validate with CA). 

When you are ready, could you send a few real reports (~5) to our production endpoint that we can use to validate with the public health jurisdictions? You can send as much fake/test data as you want or need to our staging environment.

Thanks,

James

**Comment by LaFreda1** [comment]
Received on March 16, 2023:
To whom it may concern,

 

It seems that James is out of office today and tomorrow.  We are trying to do final production verification of our system and hoping to be complete by the end of the week.  Is there someone that can aid us in getting the final verification across the finish line?

 

Here is my last response to James, before receiving his OOF reply:

 

James,

 

 

Are you saying, with us in test mode, that you want us to use real PHI in our final production tests, with this phrase from below: “If you are sending to our production endpoint we are expecting that to be real patient data.”

 

So, the tests and the patient information need be completely real to test the production endpoint in test mode?

 

Best,

 

Gene

**Comment by LaFreda1** [comment]
Responded on 3/17/23:
Hi Gene,
Since James is OOO, I want to make sure that we get you an answer to your question. Yes, you can now send real PHI to our production endpoint since you are in test production mode. Let me know if you have any more questions.



Best,
LaFreda
