### ISSUE TITLE
Truncate HL7 v2 fields for CA

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#8752]
### **User Story:**
As a CA receiver, I want data that exceeds the HL7 v2 max length to be truncated.

### **Description/Use Case**
Currently the COVID pipeline has the ability to truncate HL7 fields as part of the receiver settings using the `truncateHl7Fields` and `truncateHDNamespaceIds` settings. To avoid sending data to CA that exceeds the max length. We need to truncate the fields listed in the existing CA receiver setting in the covid pipeline. 

### **Risks/Impacts/Considerations**

Messages being sent to CA might fail if fields like the Patient name are too long.

### **Dev Notes:**

- `truncateHl7Fields` accepts a list of HL7 fields that need to be truncated. CA has these listed as part of the receiver settings:
 ` truncateHl7Fields: "OBX-23-1, ORC-21-1, OBR-16-1, OBR-16-3, ORC-12-1, ORC-12-3,\
        \ PID-5-1, PID-5-2, PID-5-3"`

-  `truncateHDNamespaceIds` truncated all HD fields in the HL7 messages. These fields are hard coded inside `HL7Serializer.kt`: 
  `val HD_FIELDS_LOCAL = listOf(
            "MSH-3-1", "MSH-4-1", "OBR-3-2", "OBR-2-2", "ORC-3-2", "ORC-2-2", "ORC-4-2",
            "PID-3-4-1", "PID-3-6-1", "SPM-2-1-2", "SPM-2-2-2"
        )`
- FHIR path provides a substring function, this can be used to truncate the fields to their max length as part of the CA receiver transforms.
- There will be a separate ticket to come up with a better design to handle truncating fields for receivers.
- The max length for these fields can be found in Caristix https://hl7-definition.caristix.com/v2/HL7v2.5.1/Segments

### **Acceptance Criteria**

- [ ] UP will truncate fields if they they exceed the HL7 v2 max length.
- [ ] CA can process a message after fields have been truncated.

**Comment by bishoyayoub** [comment]
Make ticket exclusive to CA - and it will be ready for grooming.
