### ISSUE TITLE
API Documentation Improvements

### ISSUE THREAD

**Issue by Andrey-Glazkv** [CDCgov/prime-reportstream#8761]
## Problem Statement

- Who is the user
- What are they trying to achieve
- What needs to change and why
- What to Know

## Documents and links
Has research been done?

## Assumptions and risks
Optional: People/Roles involved in completing this epic

## Ready?
- [ ] Epic Reviewed with team
- [ ] To the best of our knowledge, all issues added and epic is ready

Start collecting a list of ideas to improve consistency of API yaml docs to get less issues when trying to import the yamls into an automated testing tool. We'll want to approach this in a more holistic way that includes more pieces than just the OpenAPI documentation. It also touches on some sitemap/site IA discussions we've been having.

To do that we want:
- Document a list of possible solutions for a YAML to HTML library for use on documentation pages
- Make a recommendation with reasons why
- Share with API Working Group

One of such paths forward would be full automation for:
- Generating the OpenAPI YAML file (which we do with some issues as noted above in #6243)
- Adding public pages + keeping them up-to-date with the YAML
- Generating test request/response data to show in the Programmer's Guide

**Comment by chris-kuryak** [comment]
Closing as redundant.
