### ISSUE TITLE
Create technical question for ELR sender partner

### ISSUE THREAD

**Issue by jsutantio** [CDCgov/prime-reportstream#8780]
-As an engineer on the Sender side, I'd like to know what to technical information will be requested from me, so that I can efficiently provide the necessary information to start the full ELR pilot process.

### **Background & Context**
Create a sendable document that requests technical information regarding the settings and formats that are needed to enable full ELR submission (instead of just COVID) by the Sender.

### **Working Links**
- [ELR Partner Outreach Plan](https://docs.google.com/document/d/1QycMnAiOk5YlbrTdmtILqLvELwYaHU_dXkD8U0DVpqA/edit?usp=sharing) (WIP)
- [ELR weekly meeting notes](https://docs.google.com/document/d/1k-xAiO91nwFdOpTkDA4D4CNt9RmXIOO-m_Km_O6Qtbo/edit?usp=sharing)
- [Service blueprint](https://app.mural.co/t/nava4113/m/nava4113/1672148125717/f376adefc22f136c60e40cb9f60b1b74ef4ee43d?invited=true&sender=u8e85df6f9eec764c4bfd6788)

### **Acceptance Criteria**
- [ ] Questions are formatted so that the sender engineer easily understands what is asked of them and can quickly document their responses
- [ ] Exported as a pdf or excel doc; saved in CDC PRIME RS SharePoint
- [ ] Linked within the [ELR Partner Outreach Plan](https://docs.google.com/document/d/1QycMnAiOk5YlbrTdmtILqLvELwYaHU_dXkD8U0DVpqA/edit?usp=sharing) for documentation purposes
- [ ] Emailed by ReportStream email to the Sender (cc'ing the appropriate RS members) alongside technical questions

**Comment by bishoyayoub** [comment]
The list is currently with @victor-chaparro. He will review, amend, and provide feedback.
