### ISSUE TITLE
Invalid UP receiver config should cause an error

### ISSUE THREAD

**Issue by jack-h-wang** [CDCgov/prime-reportstream#8810]
## Describe the bug
There is currently no error visible on the Azure portal if a UP receiver is misconfigured and the process to send data fails.

## Steps to reproduce
1. Change the translation schemaName on the `ignore.full_elr` receiver to a schema that does not exist.
2. Run the `end2end_up` smoke test.
3. Observe that the test fails, but there is no descriptive error.

## Expected behavior
An error message describing the failure should be logged and viewable on the Azure portal so that the issue can be more quickly and easily tracked.

**Comment by arnejduranovic** [comment]
I am looking at a similar issue right now. Will update here when I confirm if my fix will fix this or not.
