### ISSUE TITLE
Internal Engineering Retro for Flu Pilot

### ISSUE THREAD

**Issue by jsutantio** [CDCgov/prime-reportstream#8822]
As an engineer working on the UP,  I want to reflect upon the technical work that was completed (or not) during the flu pilot, so that I and other Platform engineers can leverage our learnings from this process for future pilots (e.g., full ELR pilot).

### **Background & Context**
Post-flu pilot, the RS team members will host a series of retrospective meetings with the stakeholders involved to evaluate the pilot process through launch. The culmination of these retros will end with a final internal retro for the RS engineers involved to share their learnings with the rest of the platform team so that the team is better informed and prepared for enabling universal pipeline capabilities.

### **Working Links**
- TBA

### **Acceptance Criteria**
- [ ] Facilitation of retro in a collaborative and judgement-free space (e.g., Mural, GoogleDoc, Retro)
- [ ] Documentation of what went well, didn't, suggestions for improvement, and key learnings

**Comment by lizzieamanning** [comment]
@jsutantio I repurposed #7961 for this- oops! We can repurpose this to something else if needed

**Comment by lizzieamanning** [comment]
@jsutantio I repurposed #7961 for this- oops! We can repurpose this to something else if needed
