### ISSUE TITLE
Modify UP condition filter to OR filter statements instead ANDing

### ISSUE THREAD

**Issue by thetaurean** [CDCgov/prime-reportstream#8837]
### User Story:
As a receiver, I want to receive data matching any of the condition filters I have configured (rather than all of them as currently implemented) so that I can receive data I am interested in.

### Description/Use Case
The Universal Pipeline utilizes a filter on health condition (i.e. LOINC code). This filter ensures the UP only sends data to receivers that are interested. This filter, configured per receiver in `organizations.yml`, supports multiple condition filter "statements" in the configuration file.

Currently these statements are ANDed together such that all must evaluate to TRUE. It would make more sense for them to be OR'd together, so that if any evaluates to true, the data is sent.

Modify the condition filter evaluation logic such that data passes if it matches any of the configured condition filter statements.

### Risks/Impacts/Considerations
- Further documentation is needed for this and similar filters in the pipeline.

### Dev Notes:
- Original issue prompting need for condition filter: #8095
- Issue tracking the work to implement condition filter: #8315
- Example of condition filters in action: #8820 (WIP reflecting current implementation of condition filter)

Key persons: @PatriciaPerozoUSDS and @JessicaWNava 

### Acceptance Criteria
- [ ] Condition filter statements are evaluated on OR basis
- [ ] Documentation in code updated to reflect change
- [ ] Updated Docs (universal-pipeline-filter-reporting.md)

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8837?planning-poker) with Zenhub @arnejduranovic @thetaurean @JessicaWNava @jimmyfagan @jack-h-wang @victor-chaparro
