### ISSUE TITLE
The engagement team needs a standard HL7 sample file to send to senders and receivers

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#8854]
## Problem statement
When the engagement team receives requests for sample HL7 sample files, we currently write a ticket and wait for the engineer who is doing the onboarding to pick it up. We can improve the response time by creating a standard sample file that we can share broadly. 

## What you need to know
We have received quite a bit of requests lately and are currently tailoring the sample file to the requestor. I am proposing to send the standard file as the initial response (or to share during KO). We can then provide a specific file, if requested. 

## Open questions 

- How tailored is tailored? Meaning, which parts of the sample file are we customizing? Why?

## Acceptance criteria

- [ ] Standard sample HL7 file to use during onboarding

## To do

- [ ] Get with Engineers to determine best format and how to make the file standard
- [ ] Get with LaFreda to discuss the next steps on presenting the file to RS users

**Comment by GilmoreA6** [comment]
[https://app.zenhub.com/files/304423150/3f8e5140-563e-44db-b31c-ad992a36a4d1/download](https://app.zenhub.com/files/304423150/3f8e5140-563e-44db-b31c-ad992a36a4d1/download)

**Comment by jakefishbein-navapbc** [comment]
[Link to discovery notes](https://docs.google.com/document/d/1kC2b3Msen3H9t6MhUJzhXuoXhrJc_iQ4mJB3icYoSOc/edit?usp=sharing)

**Comment by lizzieamanning** [comment]
@LaFreda1 @brandonnava how is this sample file different than what we provide today in the API Programmer's Guide? ([Sample HL7 2.5.1 payload and output on page 31](https://reportstream.cdc.gov/assets/pdf/ReportStream-Programmers-Guide-v3.0.pdf))

**Comment by lizzieamanning** [comment]
From what @GilmoreA6 linked, it looks the same to me. If it is the same, what else are we trying to accomplish with this ticket? Better/easier formatting? Is there a format we know to be more helpful? Keeping in mind this update will be live on the website in ~2weeks with the launch of the API programmer's guide

**Comment by lizzieamanning** [comment]
@LaFreda1 could you add some context as to why this was closed?
