### ISSUE TITLE
Donald Shin - Engagement Engineer access ticket

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#8857]
Access Needed for New Engineer

- [x] CDC email - (in Progress - Frank Dilley contact)
- [x] CDC SU account access
- [x] Okta Account Staging
- [x] Okta Account Production
- [x] Open VPN credentials for Staging and Prod dbs
- [x] Metabase Staging Access
- [x] Metabase Production Access
- [x] Zenhub Access
- [x] Easyretro Access
- [x] Mural Access
- [x] Forward meeting invites
- Slack Channels
   - [x] prime-reportstream
   - [x] prime-reportstream-engagement
   - [x] prime-reportstream-engineering
   - [x] cdc-reportstream-engagement-shared

**Comment by brick-green** [comment]
Added Don as a contributer to the github repo. Once he accepts, we should be able to access zenhub

**Comment by LaFreda1** [comment]
@brick-green What is his email?

**Comment by brick-green** [comment]
donald.shin@agile6.com

**Comment by brick-green** [comment]
@cloudmagic80 Do you have an SU account? If so, I think we can close this ticket
