### ISSUE TITLE
Publish "Release Notes" - April 2023

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8866]
## Problem statement
As a user, I would like to know what features, bugs, other user facing updates have been made to ReportStream product.

## Procedure
https://docs.google.com/document/d/1vAiOJlfRMvJPRER3cr9Kr4lQ2-_ybNucJt28kI3fl1I/edit

## Acceptance criteria

- [x] New Web Experience Items added as a comment
- [x] New STLT's finished onboarding this month added as a comment
- [x] New Engagement Items added as a comment
- [x] New Platform Items added as a comment
- [x] Release Notes text (in ticket description) updated with all release notes
- [x] Follow [Procedure](https://docs.google.com/document/d/1vAiOJlfRMvJPRER3cr9Kr4lQ2-_ybNucJt28kI3fl1I/edit
) to publish to RS Website

## Release Notes Text
TBD

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
Kansas added as a STLT receiving data

**Comment by audreykwr** [comment]
Requested changes in PR. @chris-kuryak flagging that the procedure doc has a slightly different process than the ACs when it comes to where the content is drafted and reviewed.

**Comment by chris-kuryak** [comment]
Good callout! I updated the AC's to reflect just following the procedure in the linked doc (for review and approval)

**Comment by Andrey-Glazkv** [comment]
Now just waiting for @etanb to deal with his part of the PR

**Comment by etanb** [comment]
I don't have context on this ticket -- is this going in on this sprint @Andrey-Glazkv @chris-kuryak ?

**Comment by Andrey-Glazkv** [comment]
@etanb its basically here: [link](https://github.com/CDCgov/prime-reportstream/pull/9357)

**Comment by Andrey-Glazkv** [comment]
@etanb yes, this is to be done this sprint
