### ISSUE TITLE
Please re-enable and turn on ReportStream Staging Metabase, now that Staging is back in its regular spot.

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#8871]
**Description**

Please re-enable and turn on ReportStream Staging Metabase, now that Staging is back in its regular spot.

**Specific Requested resources**

https://staging.prime.cdc.gov/metabase/

**Comment by jeremy-page** [comment]
This should be working now, moving to QA pending confirmation from Jim. Please note smtp is not working, however that was added after staging was busted - we will retroactively add smtp support to staging sometime in the next 2 days
