### ISSUE TITLE
Track notes for OOO teammate

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#8872]
## User story

As a designer on PTO, I want my team to help me track what I have missed, so that I can catch up accurately when I return.

## Background & context

Jillian will be OOO for most of Sprint 65, so we want to add any relevant notes for her in her OOO plan.
While all team members should feel empowered to add to this, having a point person will hopefully help! 

## Working links

[OOO doc](https://docs.google.com/document/d/1gNiAqcTnu5_EH_4N1Vrt2BqyZhbB8Gus4jrmysmVaiU/edit)

## Acceptance criteria

- [x] Update OOO plan with anything we need to keep Jillian up to date on

**Comment by audreykwr** [comment]
Closing since Jillian is coming back on Monday!
