### ISSUE TITLE
Content work priority refinement

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#8874]
## Problem statement

We need to know how our current site and plans are meeting our users' needs and RS goals. An audit will examine that based on previously IDed needs and priorities.

The audit IDed main areas of opportunity and potential solutions. The next step is to prioritize those possible action steps for the next quarter alongside goals and priorities.

## What you need to know

- [General planning doc](https://docs.google.com/document/d/1WjaSCEqaZkJ0Xmkll-rllc219S9nT7B1vfyRtN9R0Vc/edit?usp=sharing)
- [Workshop synthesis deck with planning notes](https://docs.google.com/presentation/d/1ljFEf3dUm3z2cOrgikiXoCemIoqDRWWRnMz4vyue--Y/edit#slide=id.g11de60fb153_0_1358)
- [Mural of general work roadmap/misc notes](https://app.mural.co/invitation/mural/nava4113/1673278109303?sender=uc55a7af3b66977fba12f5528&key=27b02b81-58ce-4f9b-a734-4aab2802ad5b)

## Acceptance criteria

- [x] Potential priority work from audit analysis examined alongside KRs
- [x] Feedback and input from key stakeholders gathered

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@lizzieamanning let me know what you think of this first pass at the audit follow up ticket for this sprint

**Comment by lizzieamanning** [comment]
@audreykwr wondering about pulling out the "ticket creation" AC if that would make this more manageable (i.e., less than an 8 pointer). Thoughts?

One more note- next time you open a new ticket, can you try using the design-issue template that is now available? We can always update that template if we are feeling like it isn't meeting our needs!

**Comment by audreykwr** [comment]
Ah! Totally forgot we had that template available now. Sorry about that. Default mode. 

Yeah I think that makes sense. I'll go ahead and do that. And use the new template.

**Comment by audreykwr** [comment]
@lizzieamanning [see follow up here](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/8880)

**Comment by lizzieamanning** [comment]
@audreykwr adding our Slack notes here if helpful:

- AR to finish the analysis and prepare the deck by early next week (4/3-4/4)
- LM to review by Wed next week (4/5)
- AR to share in design crit Thurs (4/6)
- Review in stakeholder meeting (4/7)

**Comment by lizzieamanning** [comment]
@audreykwr adding our Slack notes here if helpful:

- AR to finish the analysis and prepare the deck by early next week (4/3-4/4)
- LM to review by Wed next week (4/5)
- AR to share in design crit Thurs (4/6)
- Review in stakeholder meeting (4/7)

**Comment by lizzieamanning** [comment]
@audreykwr adding our Slack notes here if helpful:

- AR to finish the analysis and prepare the deck by early next week (4/3-4/4)
- LM to review by Wed next week (4/5)
- AR to share in design crit Thurs (4/6)
- Review in stakeholder meeting (4/7)

**Comment by audreykwr** [comment]
Closing. [Final deck from the presentation](https://docs.google.com/presentation/d/1Qa0Ek93niJZQWdHgQCl3LITHTh6_1wEXXAekNGHkh8U/edit#slide=id.g1f9b1d1a6a4_0_104)
