### ISSUE TITLE
Design how to truncate HL7 v2 fields for messages being sent to receivers

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#8876]
### User Story:
As ReportStream, I want HL7 v2 messages being sent to be truncated to a configurable length. 

### Description/Use Case
Currently the COVID pipeline has the ability to truncate HL7 fields as part of the receiver settings using the `truncateHl7Fields` and `truncateHDNamespaceIds` settings. We need the ability to support this as part of the Universal Pipeline. 

### Risks/Impacts/Considerations
* Do we want to follow what the Covid pipeline is doing now, or provide the ability to configure the max length for different fields.

### Dev Notes:
* We need to find out whether we want every receiver to follow the HL7 v2 spec or allow receivers to configure the max length for fields
* Find out if this needs to be in code or part of receiver transforms.
* Look into how HL7 v2 spec expects truncated fields to be represented.
* Should we have a default configuration and allow that to be overridden?
* See #8752 for the work around we did to support CA pilot

### Acceptance Criteria

- [ ] Design the HL7 v2 truncate component and document the design.
- [ ] Present the design to the Pipeline and Engagement team to get buy-in.

**Comment by arnejduranovic** [comment]
My proposal for the user story: 

`As ReportStream, I must support the ability to truncate HL7v2 Field values to a configurable length. `

To me, the user story, as written, gives the impression you want to truncate the HL7 message as a whole, and not the individual fields? Is my understanding correct?
