### ISSUE TITLE
Standardize Receiver config documentation in Keybase

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#8877]
## Problem statement

Receiver configuration documentation, most importantly transport information, is stored in keybase. Each receiving organization has a folder containing the documentation. That documentation is maintained by various engineers but has never been standardized so retrieving that needed information is confusing and time consuming.

## What you need to know

Keybase folder locations:

- ![image.png](https://images.zenhubusercontent.com/60d23d7dcaf07751be9205b6/4bf0c818-2aad-46da-a8a4-16d90e1acab5)[Document 1](https://...)

## Acceptance criteria

- [ ] All documentation is uniform
- [ ] Unneeded documentation is removed
- [ ] Process for updating documentation is created and added to new engineer onboarding packet

**Comment by adegolier** [comment]
Does this stuff need to be in Keybase _and_ the database _and_ Azure?

**Comment by chris-kuryak** [comment]
TBD based on future Engagement Engr Sync

**Comment by chris-kuryak** [comment]
Mikaelah to check in on status with Jeremy to see what they recommend using as a replacement for Keybase?

**Comment by chris-kuryak** [comment]
Response from Jeremy:
Don't use Keybase anymore for storing credentials.

Credentials should be stored in Sharepoint and documents containing credentials should be labeled as "Restricted Use". If needed, use Recipients only and ensure that all onboarding engineers are recipients.
