### ISSUE TITLE
Draft a formal standard operating procedure for onboarding new organizations

### ISSUE THREAD

**Issue by jakefishbein-navapbc** [CDCgov/prime-reportstream#8882]
**User Story**
As a member of the report stream team, I need a single source of truth to ensure reliability in the in how organizations are onboarded to ReportStream.

**Background & Context**
Currently, the onboarding process is largely  based on the expertise of individuals on the team. As the user base scales and new members join the team, it becomes increasingly important to codify the onboarding process. Additionally, as ReportStream begins to process new conditions, this SOP will be updated to include new information as it is available.

**Acceptance Criteria**

- [ ] SOP utilizes PRIME ReportStream branding and formatting.
- [ ] SOP is in PDF format.
- [ ] SOP documents the entire onboarding process from outreach to "go live".
- [ ] SOP documents reviewed with Engagement team

**SOP Example**
[https://app.zenhub.com/files/304423150/ca500934-a5e5-415d-97c1-769f3aee7530/download](https://app.zenhub.com/files/304423150/ca500934-a5e5-415d-97c1-769f3aee7530/download)

Working Links:
[WIP SOP](https://docs.google.com/document/d/10HjEtXyRSyl2dkx_1hXFqkaxq5xMxKpNwI8ePV2rems/edit#)

**Comment by jakefishbein-navapbc** [comment]
[https://app.zenhub.com/files/304423150/ca500934-a5e5-415d-97c1-769f3aee7530/download](https://app.zenhub.com/files/304423150/ca500934-a5e5-415d-97c1-769f3aee7530/download)

**Comment by jakefishbein-navapbc** [comment]
4/24/2023: Met with Glen Grieves to review and formal hand-off ownership of the SOP document.
SOP[https://docs.google.com/document/d/10HjEtXyRSyl2dkx_1hXFqkaxq5xMxKpNwI8ePV2rems/edit#](url)

**Comment by lizzieamanning** [comment]
Note from 4/25: Glen will fill in remaining pieces of SOP (glossary, etc) as well as revisions like ELR impact
