### ISSUE TITLE
Tier 1 Ticket Resolution Time Quantitative Analysis

### ISSUE THREAD

**Issue by jakefishbein-navapbc** [CDCgov/prime-reportstream#8883]
**User Story:**
As a researcher, I need to understand the factors that may contribute to ticket resolution time in order to craft accurate solution concepts.

**Context/Background:** 
The support team has collected a range of data in regards to ticket resolution. The data set includes received and closed dates, assigned team member, hours and minutes to resolve, priority level, and category. This data has already been analyzed to determine the time it takes to close a ticket. This quantitative research will build on that by examining how various factors may influence the time it takes to resolve a ticket.

**Acceptance Criteria:**
The quantitative analysis will produce a report that includes the following findings:

- What is the time between date received and first response
 -Median
 -Max
 -Min
 -Range

- What is the time between date received and closed
 -Median
 -Max
 -Min
 -Range

- What is the time between first response and closed
 -Median
 -Max
 -Min
 -Range

- What is the number of hours spent on a ticket
 -Median
 -Max
 -Min
 -Range

- What is the average difference between date received and first response
 -By category
 -By staff
 -Severity
 -User type

- What is the average difference between date received and resolved
 -By category
 -By staff
 -Severity
 -User type

- What is the difference in average completion time
 -By category
 -By staff
 -Severity
 -User type

- How has completion time changed from January to present

Working Links
[Existing Support Team Research](https://app.box.com/folder/193655681697?s=5t5692yn9740p5m1citsgjt1d6fyni2g)
[WIP Analysis Sheet](https://docs.google.com/spreadsheets/d/16VK_98UIHVlL6aZAqEozrxxL9LYSpf2nne1LQoUqIeA/edit#gid=0)

**Comment by lizzieamanning** [comment]
@jakefishbein-navapbc the support team research link links to the Box folder structure. Can you add the specific links you're using for clarity and visibility? For example, I'm curious where the existing data on the time it takes to close a ticket lives.

**Comment by lizzieamanning** [comment]
@jakefishbein-navapbc when you get a moment, can you link the output of this ticket in a comment for tracking purposes/visibility?

**Comment by jakefishbein-navapbc** [comment]
[Quantitative Analysis Data Table](https://docs.google.com/spreadsheets/d/16VK_98UIHVlL6aZAqEozrxxL9LYSpf2nne1LQoUqIeA/edit?usp=sharing)
