### ISSUE TITLE
Solution Concepts for Priority Categories

### ISSUE THREAD

**Issue by jakefishbein-navapbc** [CDCgov/prime-reportstream#8886]
**User story**
As an Engagement team member, I need to reduce the amount of time it takes to close tickets. I also need to make sure more tickets are handled at the tier 1 level rather than tier 2.

**Background & context**
The engagement team has two Q2 OKRs related to support tickets. These include:
1. 75% of support tickets handled by tier 1
2. Establish "time to resolution average" per ticket category and identify any potential bottlenecks
 
In order to support these OKRs, this ticket will collect information regarding current ticket resolution and provide solution concepts that reduce the time and effort it takes to handle support tickets.

**Working Links**
[Recommendation Report](https://docs.google.com/document/d/1u82Xu2oTb7L95GtGfDt1q-T2oGkdLtW_cxa6EAZoQS0/edit#heading=h.mtc4swvlio8d)

**Acceptance Criteria**
- [x] A report that includes:
- [x] A summary of research
- [x] PRiority categories
- [x] Potential solutions for reducing time and effort
- [x] Deliver report to Brandon and Sharon

**Comment by jakefishbein-navapbc** [comment]
6/16/2023 
Brandon and I aligned around training support staff on configurations. I'm going to bring it up in stand-up to see if there is an engineer who would be excited to do it, then collaborate to develop documentation that can be used and updated in the future.

**Comment by brandonnava** [comment]
Report delivered. Plan to train support set. New ticket for training made so closing this one
