### ISSUE TITLE
ELR File Upload Notification PACSPROD - PW Expiration

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#8905]
## Problem statement

We received an email in the ReportStream inbox that a PA password expired.

## What you need to know

The User Name is: bchdUSDSewsprod

Email Text:
`Error with Login
User Name :  bchdUSDSewsprod
Program Area :  ELR

Error: PS1C:The password has expired. Change password and retry.`

## Acceptance criteria

- [ ] The password has expired. Change password and retry.

## To do

N/A

**Comment by brick-green** [comment]
Closing. Already reset this password with James

**Comment by kant777** [comment]
Thanks @brick-green
