### ISSUE TITLE
Add integration tests for removing Observations from a bundle

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#8910]
### User Story:
As a developer, I want to have integration tests that test the conversion from FHIR to HL7 after removing Observations from a bundle, so I know any future code/configuration changes do not break existing features.

### Description/Use Case
We have a translation test in the integration test suite that takes in an input, generates an output, then compares that output to an expected data file. We need something to test the FHIR to HL7 conversion after an observation has been removed.

### Risks/Impacts/Considerations

A lot of configuration changes have been going in that impact this code and we don't have tests for it.

### Dev Notes:

- FHIR to HL7 integration tests are inside `TranslationTests.kt` and are configured via this file `translation-test-config.csv`. 
- We would need to have a sample FHIR bundle that we can remove an observation from, convert that bundle to HL7 and make sure it matches an expected HL7 file.

### Acceptance Criteria
- [ ] The ReportStream Translation integration test can compare the output of one full-ELR FHIR bundle to an expected full-ELR HL7 message after removing an Observation from the bundle.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8910?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @mkalish @thetaurean
