### ISSUE TITLE
NJ - MFA - Authentification Setup by May 1, 2023

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#8916]
## **Problem Statement**
We received an email in the ReportStream box. The MOVEit Cloud will be ENFORCING Multi Factor Authentication (MFA) on or about May 1st, 2023. Please be sure to enable (MFA) at this point in time to prepare all accounts utilizing and automated logins for testing.

## **What you need to know**
Original Email:
From: Alva, Mark [DOH] <Mark.Alva@doh.nj.gov>
Date: Thursday, March 9, 2023 at 09:47
To:
Subject: MOVEit Cloud SFTP (MFA)

Morning,
The MOVEit Cloud will be ENFORCING Multi Factor Authentication (MFA) on or about May 1st, 2023. Please be sure to enable (MFA) at this point in time to prepare all accounts utilizing and automated logins for testing. After extensive testing, the OIT SFT team has noticed that MOST automated processes are not affected by enabling (MFA). This testing is a MUST to keep all processes and transfers running smoothly for when (MFA) is enforced.

Various users might be utilizing automated processes (scripts, APIs, and other various automated methods) to upload files to the MOVEit Cloud. So, in preparing USERS for the enforcement of (MFA) ahead of time incase that any configurations that send files from the source to the MOVEit Cloud will need to be updated or reconfigured. We would like for you to Test and if  you have any questions or concerns that may arise from your end with the added security feature of (MFA) and how this will potentially affect its users, please don't hesitate to reach out.

We have provided a Word Document with simple steps to switch the account under (MFA). This will help with logging in with Multi-Factor Authentication. DOH has taken the steps to switch over to (MFA), and as of currently we have not had any issues with having this extra security that is needed when dealing with private information. 

In addition:
If you are not involved with uploading files to the account, please reply to all with correct email address of the person who is responsible for uploading files to QA.

The (MFA) is tied to one email, not multiple, that's why we suggest you provide group email account(s), so that there are no confusions on whom might not be receiving these important emails.
If you have any additional questions or concerns, please let us know.
 
(All vendors should start by enabling (MFA) within their MOVEit Cloud account(s) for an initial test before reconfiguring any script.)

Regards, 
Mark Alva
Software Developer 

[Configuring Multifactor Authentication (1) (1).docx](https://github.com/CDCgov/prime-reportstream/files/11124645/Configuring.Multifactor.Authentication.1.1.docx)

## **Acceptance Criteria**

Please enable (MFA) for all accounts utilizing and automated logins for testing.

## **To Do**
A quick note to the assignee of the ticket.

## **Additional Comments**
If applicable, add screenshots, links, etc. to further explain the ticket

**Comment by oslynn** [comment]
Emailed to Mark, NJ-DOH.

Good morning Mark, 

My name is OTT SATHNGAM.  I am one of the CDC ReportStream Engineer.  I got a forwarded email from ProPhase integration engineer as shown below.
I remember that we renewed our CDC ReportStream account with MOVEIT around January of this year.  Will the email apply to CDC ReportStream Account?
If it is apply to us as well, what is next step should we take?

Very respectfully,
-Ott Sathngam
CDC ReportStream Eng.

**Comment by oslynn** [comment]
Morning,

Sorry for the late response to your question...

Various users might be utilizing automated processes (scripts, APIs, and other various automated methods) to upload files to the MOVEit Cloud. So, in preparing USERS for the enforcement of (MFA) ahead of time incase that any configurations that send files from the source to the MOVEit Cloud will need to be updated or reconfigured. We would like for you to "TEST" and if  you have any questions or concerns that may arise from your end while TESTing with the added security feature of (MFA) and how this will potentially affect its users, please don't hesitate to reach out.


Regards,
Mark Alva
Software Developer 
NJ Department of Health, Information Technology  (HIT)

55 N. Willow St.

Trenton NJ 08625

Mark.Alva@doh.nj.gov

**Comment by oslynn** [comment]
I tested their SFTP site in MOVEit Cloud and it functions well.  Therefore, I am closing this ticket.
