### ISSUE TITLE
Update Server-Server Authentication Documentation

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#8918]
### User Story:
As a sender or someone trying to establish server-server connection with ReportStream,  I require the existing documentation be accurate and up to date.

### Description/Use Case
Currently we have auth code documentation split up in various places:
- programmer's guide ([ReportStream-Programmers-Guide-v2.4.docx](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/ReportStream-Programmers-Guide-v2.4.docx))
- generate-jwt.py. (https://github.com/CDCgov/prime-reportstream/tree/master/prime-router/examples/generate-jwt-python)
- et. al.?  (yes - see Jim's comment below)

We need a single place a user can start, probably programmer's guide, and set up server-server auth without having to contact RS engineers for support. I propose the following:

Someone inexperienced with auth on RS follow the documentation and try to set up a server-server connection between staging and their local machine and update documentation as you run into hiccups or outdated information. Add additional documentation/clarification as needed.

### Acceptance Criteria
- [x] Existing auth documentation updated
- [x] New documentation created as needed

**Comment by jimduff-usds** [comment]
But wait there's more!

There's a "how to" playbook:    https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/playbooks/how-to-use-token-auth.md

There's background info in the original proposal doc:   https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/proposals/0001-authentication.md

And in addition to the example code in python, there's example code in kotlin:   https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/tokens/SenderUtils.kt

And there are CLI tools that use that kotlin code.   Those tools are documented in the "playbook" I mention above.

Note that consolidating this is necessary but not sufficient to make this usable by our customers.  I suggest you get some HCD and Documentation expertise to help with this.
