### ISSUE TITLE
Research Receiver Settings for Full ELR Pilot

### ISSUE THREAD

**Issue by avnieldravid** [CDCgov/prime-reportstream#8924]
### User Story:
As a ReportStream engineer, we want to understand the production settings for receivers who are potentially involved in the Full ELR pilot, so that we can write tickets to build features that are missing, in order to support these receivers in the UP.

The states/jurisdictions we are targeting:
- NY
- CO
- MD
- MT
- WA
- Protect (CDC)

### Description/Use Case

- pull the production settings for the receiver
- compare the settings their using to the [spreadsheet Jessica Willis created](https://docs.google.com/spreadsheets/d/1na02y8lwK05_HdL36pKEzBuBw7kkSr-G/edit#gid=1085110351)
-  made to see if that functionality exists in the UP
- based on the above, determine how much work we would have to do before being able to onboard the STLT

### Dev Notes
Pre-recs to be able to do the above:

- a prod account for https://reportstream.cdc.gov/ to be able to access receiver settings OR access and an understanding of how to query for a receiver's settings using the prime CLI
- Access to Jessica's spreadsheet identifying the gaps between the two pipelines

### Acceptance Criteria
- document (ticket in Zenhub) the work needed to accomplish these features

**Comment by JessicaWNava** [comment]
Here is the original parity work: https://docs.google.com/spreadsheets/d/1na02y8lwK05_HdL36pKEzBuBw7kkSr-G/edit#gid=1060769432
