### ISSUE TITLE
Integrate Chromatic

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8928]
## Problem statement

Now that we have our Storybook configuration set up, we can add a GitHub Action to automate the Chromatic deployment.

## What you need to know

- [Chromatic Storybook](https://6419b81d4a47163c3050f14a-xtlligolml.chromatic.com/?path=/story/components-staticalert--default)

## Acceptance criteria

- [ ] We have a GHA to deploy Storybooks to Chromatic

**Comment by chris-kuryak** [comment]
Awaiting approvals from WebX and DevOps
