### ISSUE TITLE
Create design team intro to ReportStream onboarding deck

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#8929]
## User story

As a ReportStream design team member, I want to create a design team intro to ReportStream onboarding deck so that our new team members have a go-to resource when they join the team

## Background & context
There are lots of documents to support onboarding to ReportStream. This is a consolidation effort to audit and select the best materials to add to and link to in a design team deck.

## Open questions
What information about ReportStream should go into this deck?

## Working links
[Deck shell](https://docs.google.com/presentation/d/1b8-t0uMoQwVBPhv1v1XEjGUVCFHO7ZnlcD_SapsSVOI/edit#slide=id.g13ae3e4ca76_0_19)

**Reference materials**
[ReportStream Github ](https://github.com/CDCgov/prime-reportstream/wiki/About-PRIME-ReportStream)
[Brandon's Links](https://docs.google.com/document/d/1kwakXhDSeweCfrzpQ2HzM3YqW7rhQm1P0mm16B5GFrI/edit?pli=1)
[DIBBs wiki](https://docs.google.com/document/d/1h-GhNk3yR9xGqq7Oh1U9ZWzhdw0broNr6lKe8lQmm2g/edit#heading=h.xgy7fnpzeqob)

## Acceptance criteria

- [x]  Flesh out the current deck using existing materials
- [x]  Review with current design team

**Comment by jillian-hammer** [comment]
Lizzie completed this work, links below:
- [CDC ReportStream Design Onboarding: Introduction to ReportStream](https://docs.google.com/presentation/d/1b8-t0uMoQwVBPhv1v1XEjGUVCFHO7ZnlcD_SapsSVOI/edit#slide=id.g13ae3e4ca76_0_19)
- [CDC ReportStream Design Onboarding: Team Ops](https://docs.google.com/presentation/d/1hdq2LtoQ6jgvV98B0QOkKd0GLVaDYP54NV3W8QJE_dI/edit#slide=id.g1198a488f81_0_36)
- [Onboarding guide for CDC ReportStream designers](https://docs.google.com/spreadsheets/d/1jaGxulV4pFyXv1ec0qTOKZkT7jRFntZnP6tb74l-ItM/edit#gid=1506864892)
