### ISSUE TITLE
Add new code snippet component

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8941]
## Problem statement

The API Programmer's Guide includes some CLI commands for interacting with the ReportStream API, and we should add a new component to contain the code snippet and its behaviors.

## What you need to know

- [Figma design](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=3592-36584&starting-point-node-id=3592%3A36212) (on 'Getting started' page)

## Acceptance criteria

- [x] There's a new code snippet component that:
    - [x] Renders the code snippet in a monospaced
    - [x] Renders a copy icon that:
        - [x] When hovered, shows a 'Copy to clipboard' tooltip
        - [x] When clicked, copies the contents of the code snippet to the clipboard
    - [x] Sample code snippets (specified highlighted text) "healthy labs" styled blue
- [x] New code snippet component added to Storybook 
- [ ] Component QA'd by Design team

**Comment by stephenkao** [comment]
@jpandersen87 Since the Storybook configuration was merged in, I think you can write this component entirely in isolation in a story if that'd be helpful.  (Just FYI, though: It does look like writing stories directly in MDX was deprecated in Storybook v7!)

**Comment by Andrey-Glazkv** [comment]
Looks like the review stage is going to continue to the next sprint
