### ISSUE TITLE
Design/content review of API Programmer's Guide implementation

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8947]
Just a reminder :-)

**Comment by audreykwr** [comment]
@stephenkao will you link here what to review or is that in another ticket?

**Comment by stephenkao** [comment]
@audreykwr This is just a placeholder ticket so that we can loop you (and maybe Jillian if she's back by then!) in at the tail end of the implementation so you can look over everything before we'd release it to production.  We can list out what specifically to look for, but this is really intended to be a "review everything before release" ticket :)

**Comment by audreykwr** [comment]
@jillian-hammer moved to in progress, unless this is regarding something else than the review we are doing now

**Comment by chris-kuryak** [comment]
Final review underway.
