### ISSUE TITLE
Add sticky header functionality

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8949]
## Problem statement

One hotly requested feature for our tables is to have the header row to be "sticky," i.e., scrolls with the user down the page for tables with a lot of rows.  We should implement this functionality for our consolidated Table component because ReportStream will always be dealing with a lot of data. Having the ability for the header row to stay "sticky" will enable a better user experience.

## What you need to know

- [CodeSandbox example](https://codesandbox.io/s/determined-buck-396hm) of `position: sticky`

## Acceptance criteria

- [ ] The Table component can take a prop to enable/disable sticky headers

**Comment by chris-kuryak** [comment]
Awaiting responses from USWDS

**Comment by etanb** [comment]
Associated PR: https://github.com/CDCgov/prime-reportstream/pull/9418
