### ISSUE TITLE
Define sender user archetypes

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#8951]
## User story 
As a ReportStream teammate, I want to understand the different classifications of our customers, specifically senders, so that team can have more tailored interactions with our customers. 

## Background and context 
Based on the user task analysis some initial interviews with our customers, variations in customer facets, like technical capacity and/or organization structure have come up to be further explored 

## Open questions

- What different ways can we classify our customers? What are the critical differentiators? (i.e., knowledge level about public health and technical things) What spectrums are emerging from our research?

- What types of organizations do we know about? How are they similar or different?

- What is the best format to present this information in?

## Working Links
[Sender mural ](https://app.mural.co/t/nava4113/m/nava4113/1672245855117/9c84f3ad3a2b9d0bb28654949ce7622eede8378d?sender=u791b7d4d34761ac59b672214)
[Persona mural ](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1669841103381/69622fba64da645be24b3e0944c99aaf1eb2fdf2?sender=u791b7d4d34761ac59b672214)
[Sender persona mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1629747393430/171567851789fad5a733c9fcb6a7bdc9564a4c5f?sender=u791b7d4d34761ac59b672214) (Older but helpful)
[Additional research](https://docs.google.com/document/d/1KxYK6wOH0XbLcdP4pnEVw91-18TI0cknhpNj2sW8Us4/edit#)
[More research](https://docs.google.com/document/d/1EcU31zrL_4UFwL4u1_BgzpywoI1SF42UVhiYfB4ZFDo/edit#)

## ACs

- [x] Using the existing materials and data about our current senders to outline the critical differentiators 

- [x] Share an MVP of archetypes with the design and engagement teams

**Comment by lizzieamanning** [comment]
Sender research folder: https://drive.google.com/drive/u/0/folders/1MrjnjScIJXbQWt-b6MhCtPdVrRvRwJhS

**Comment by lizzieamanning** [comment]
@dylansmith-Nava can you link to the output of your ticket in a comment?

**Comment by dylansmith-Nava** [comment]
Yes indeed! Clean version can be found in [this Mural](https://app.mural.co/t/nava4113/m/nava4113/1685124391511/860e994db2ab19485af21285bac51124b5fb5424?sender=ufb3824a0e63fafb0304f5774).
