### ISSUE TITLE
Convert 'Support' pages to MDX

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8953]
## Problem statement

[Write a short description of what you want to achieve with this task]

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by jpandersen87** [comment]
All pages are now MDX.
