### ISSUE TITLE
Replace Organizations index table

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8959]
## Problem statement

Once we have a new consolidated Table component, we can replace the Organizations index table with it.

## What you need to know

- The table is rendered in OrgsTable: https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/components/Admin/OrgsTable.tsx#L126

![Screenshot 2023-04-03 at 16.29.13.png](https://images.zenhubusercontent.com/5999b3b38f62dc7798c36942/bf36c358-6bda-4657-bf33-48b9f26a90a8)

## Acceptance criteria

- [ ] The Organizations index table is replaced with the new consolidated Table component

**Comment by Andrey-Glazkv** [comment]
Sticky header is still in progress

**Comment by etanb** [comment]
Associated PR: https://github.com/CDCgov/prime-reportstream/pull/9418
