### ISSUE TITLE
Replace MessageTracker details table

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8963]
## Problem Statement

After completing the Custom Table component, the existing website tables need to be replaced with the new custom table component. Therefore, this ticket is to replace the table on the MessageTracker details page.

## Need to Know
- Link?
- 
## Acceptance Criteria
- [ ] Table on MessageTracker details page uses the new custom table component
- [ ] Table on MessageTracker details page has at least the same functionality as it did before replacing with the custom table component

**Comment by etanb** [comment]
PR: https://github.com/CDCgov/prime-reportstream/pull/9624

**Comment by chris-kuryak** [comment]
Joseph helping to unblock

**Comment by chris-kuryak** [comment]
unblocked by Joseph and Etan

**Comment by chris-kuryak** [comment]
PR #9624
