### ISSUE TITLE
WA - DOB Resubmission

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#8969]
## **Problem Statement**

*Jenni Risler from Washington DOH - jenni.risler@doh.wa.gov*
"Patient submitted with future DOB.  Please correct and resubmit."

## **What you need to know**
MSH-10 3A0Q9E9F+63+20230331 is the file she is referring to.

## **Acceptance Criteria**
Correct and resubmit

**Comment by kant777** [comment]
what is the correct DOB?

**Comment by rnz6** [comment]
Upon further review, we have reached out to the submitter to resubmit the corrected patient information via CSV

**Comment by LaFreda1** [comment]
@rnz6 Washington is requesting message ID and info so that they can confirm if this has been resolved on their end.

**Comment by LaFreda1** [comment]
@rnz6 any updates on this request?

**Comment by rnz6** [comment]
@LaFreda1 No response, I've followed up with the submitter from Onpoint Testing.

**Comment by rnz6** [comment]
4/25: OnPoint Testing confirmed they will resubmit the CSV file with patient correction.

**Comment by LaFreda1** [comment]
Fantastic! @rnz6  Will update Washington tomorrow

**Comment by rnz6** [comment]
Email to Washington:

Hi Jenni,

OnPoint Testing has resubmitted the test result for the patient missing a DOB. Please see Report ID: 9127e99e-3c8f-4496-936a-8fddef603240 for this result.

Please feel free to reach out with any further questions or concerns.

Thank you,
