### ISSUE TITLE
[DRAFT] Create a setting to represent a FHIR validation profile

### ISSUE THREAD

**Issue by thetaurean** [CDCgov/prime-reportstream#8975]
## User Story:
TBC

## Description/Use Case

Organizations now have the ability to add `{org}.*.report` scope keys and will need to have the ability to remove them as well

## Dev Notes:
- Coming soon

## Acceptance Criteria
- [ ] Profile should include type (parser, instance, XML)
- [ ] Profile should include type-specific config

**Comment by JessicaWNava** [comment]
Closing as it is a duplicate of #8977
