### ISSUE TITLE
[DRAFT] Implement pre-transform validation in the convert function

### ISSUE THREAD

**Issue by thetaurean** [CDCgov/prime-reportstream#8978]
## User Story:
As a sender, I want the message I send to be validated before the sender transform and enrichment step.

## Description/Use Case
After de-batch and before sender transform and enrichment, we want to validate the data using the `validationProfile` configured for this sender.

## Dev Notes:
 - Use the abstract components from #9597
- Should be datatype agnostic

## Acceptance Criteria
- [ ] Validation is performed with the sender transform.

**Comment by JessicaWNava** [comment]
We are no longer doing pre transform validation and instead are opting for basic initial validation followed by post transform validation
