### ISSUE TITLE
CA not receiving facility results - 4/4/23

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#8984]
## Problem statement

We received an email in the ReportStream inbox, asking us to review the submissions from `Pacific Clinic Laboratory` to see why the State is not receiving results from this location.

## What you need to know

- The state of CA reports that they have not received results from this facility since 3/22/23. Email text follows:

> Our team at LADPH noticed Pacific Clinical Laboratory CLIA# 05D2062640 has had an interruption in their Covid-19 test reporting to LA County beginning 03.22.23 via Prime Report Stream ELR transmission. We have been unable to reach the lab for further updates. I was hoping you could help us with any additional context you may have regarding Pacific Clinical Laboratory connection status?
> 
> Reporting Volume for AG & MOL COVID-19 Tests, by Lab (Received date)
> 
> 07MAR2023 through 03APR2023
> 
> Most recent 4 weeks
> 
> Lab name
> 
> Total count
> 
> 03-28 to 04-03
> 
> 03-21 to 03-27
> 
> 03-14 to 03-20
> 
> 03-07 to 03-13
> 
> Prime Report Stream 0085 (ELR)
> 
> "Pacific Clinical Laboratory"
> 
> 05D2062640
> 
> 417
> 
> 4
> 
> 37
> 
> 173
> 
> 203
> 
> Thank you for your attention to this matter.

## Acceptance criteria

- [ ] Identify and resolve the issue causing the state not to see the results from this facility

## To do

- [ ] Identify why these results are not being received
- [ ] Resolve the underlying cause of the missed results
- [ ] Resubmit any results that were not received during the initial upload

## Additional Notes/Comments

- My preliminary research shows that the first major upload message ID listed under the organization/facility following this date is `134fdb07-527a-49cb-9334-794ee0f3da0c` - this report has 172 results. There was one uploaded the prior day, though there were only two entries in that upload.
- The only matching entry in ReportStream I can find for this particular batch that matches this upload's total result count is listed as coming from **IMMEDIATE CARE CENTER OF WESTMONT-14D2098020**
- I have not found any entries in ReportStream or Metabase with the CLIA number listed in the request email following 3/22/23
- My initial hypothesis is that the CSV is being uploaded with different organization/facility info, and needs to be changed/corrected.

**Comment by oslynn** [comment]
‘Pasific Clinical Laboratory’ switch to from uploading messages to RS to uploading message to SR.  For the CLIA number 05D2062640, it has sender_id = 'simple_report' instead of 'pcl-ca'.  After tracing one message with message id = '040423_2+2+20230405', I see it delivered to ca-dph.elr-saphire successfully.
