### ISSUE TITLE
Design/content QA

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#8998]
*Design*
- Loading indicator isn't horizontally centered

*Content*
- MSH-10 instead of HL7 Row for HL7, CSV Row for CSV

## Acceptance Criteria
- [ ] Update Content per Audrey
- [ ] Final QA with Content

**Comment by audreykwr** [comment]
Thanks!

**Comment by chris-kuryak** [comment]
Awaiting final QA with Content.
