### ISSUE TITLE
Figure out how to handle the cliaForSender setting and implement the solution

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#9002]
## User Story:
As a ReportStream receiver, I want to receive the correct CLIA code in the message header. 

## Description/Use Case
The cliaForSenderSetting basically just sets the CLIA code associated with the sender. There is currently a list of CLIA codes per sender for CA, but we are using the sending-facility-universal-id to default it to the Simple Report CLIA number. Ideally, we would have something dynamic that could determine the CLIA number and put it in the message header.

## Risks/Impacts/Considerations
We want this to work for all sender/receiver combos. However, CA is currently the only one that we are onboarding/considering onboarding that uses this feature. 

## Acceptance Criteria
- [ ] The receiver will receive the correct CLIA code in the message header.

**Comment by JessicaWNava** [comment]
This work came out of investigation into https://github.com/CDCgov/prime-reportstream/issues/8861

**Comment by arnejduranovic** [comment]
You mention `cliaForSender setting` in the title but provide no description of it in the ticket or explain its purpose? Adding this information would be helpful.

**Comment by GilmoreA6** [comment]
This is a CA specific ask that requires that different MSH-4 values be populated based on multiple factors.
1.) For any "out-of-state" results - defined as either ordering provider != "CA" or ordering facility != "CA" they would like  CDPH000075
2.) For any results from SimpleReport they would like CDPH000085.

We can handle these in Receiver specific transforms as these requests will always be specific to a STLT and as of now only pertain to CA

**Comment by LaFreda1** [comment]
This will be handled with FHIR path. Is the case for the flu pilot
