### ISSUE TITLE
Product Health Metrics

### ISSUE THREAD

**Issue by avnieldravid** [CDCgov/prime-reportstream#9014]
As a ReportStream stakeholder, I want Metabase queries to surface product health metrics, so that I can gauge how well the product is performing its jobs.

**Comment by chris-kuryak** [comment]
@jsutantio I just finished a draft of Product Metrics that I'll be sharing at CL/TL sync this week. Can you bring the list generated here to provide feedback on my new list?
And then we can decide if we need a new ticket to track regularly in Metabase/Azure.

But I kinda think we should actually keep this epic for now -- and discuss in our Quarterly planning? Could be good for Q4.

OR we close it and re-open when necessary. Whichever Platform would prefer.
