### ISSUE TITLE
Product Health Metrics v1

### ISSUE THREAD

**Issue by avnieldravid** [CDCgov/prime-reportstream#9017]
### User Story
As a stakeholder, I want Metabase queries to surface product health metrics, so that I can gauge how well the product is performing its jobs.

Note:  Below, using the word "Item", instead of "Message", which is HL7 specific.  For covid-19 data, as an example, an Item is a single Covid-19 Lab Result.

### 1. Volume of Items received from Sender channels, per week.

DONE.  See https://prime.cdc.gov/metabase/question/19-test-reports-received-weekly
Caveats:  Click on the "i" in the upper right corner for important caveats about this metric.

### 2.  Number of items filtered out so they weren’t delivered anywhere. 

See #9676 

### 3. Number of exceptions in the pipeline that aren’t last mile problems (so excluding auth issues, or a STLT endpoint being down)

See #9677 

### 4. Average time of delivery for message in the UP

See #9679

### 5. For reports that failed to send, the average time delay between when the report was supposed to send vs when it was actually sent

See #9680 

### 6. Items that were supposed to be delivered, but did not deliver

That is, Items that bumped into a last-mile problem, exceeded the retry count, and humans were not able to fix the issue, so never got delivered

DONE.  See:  https://prime.cdc.gov/metabase/question/181-percent-delivered-core-okr-for-a-week-click-to-enter-weeknum?weeknum=10&year=2023
Caveats:  Click on the "i" in the upper right corner for important caveats about this metric.

### 7. Number of reportable diseases/conditions sent

See #9681 

### Acceptance Criteria

- [ ] Metabase (or other) queries exist to to get this data
- [ ] The queries have been integrated into the Product KPIs Dashboard

**Comment by avnieldravid** [comment]
@avnieldravid please split this up

**Comment by avnieldravid** [comment]
@jack-h-wang can we groom this a bit more, and break into separate tickets.  thanks!

**Comment by jack-h-wang** [comment]
Subitems that were marked as incomplete have been split into separate issues. The issue description has been updated to link to the new issues.

**Comment by bishoyayoub** [comment]
These metrics needs to be done for both Covid and the Universal Pipeline
