### ISSUE TITLE
Nova Labnetics - New LIS System Delivery

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#9018]
## Problem statement

*user states*

Hello,

We are a laboratory located in Lombard, IL. We are currently setup with ReportStream but have moved to a new LIS provider. Do we need to restart the process, or is there a way for us to send test files from the new LIS system to verify our HL7 formatted API calls to your system are being accepted?

 

The previous API Onboarding was completed with Anshul Kumar (CDC/OD/OCS) < [rdz8@cdc.gov](mailto:rdz8@cdc.gov) >.

Our IT team is already familiar with this setup, so if we need to go through the process again, no problem.

 

Thank you and all the best,

## What you need to know

already onboarded, just new delivery system for test files needs to be made sure it's accepted by RS

**Comment by brick-green** [comment]
@Jcavallo7 What's the name of the sender here?

**Comment by Jcavallo7** [comment]
senders name is nova labnetics

**Comment by brick-green** [comment]
@Jcavallo7 This lab will need to send some test messages from their new system to our staging environment. Can you ask if they are still able to connect to our staging? The connection specs are the same from their original onboarding.

**Comment by brick-green** [comment]
@Jcavallo7 Did we ever hear back from Nova Labnetics on the above question?

**Comment by Jcavallo7** [comment]
Unfortunately, they never got back to me. Should I send another email?

**Comment by brick-green** [comment]
I guess tomorrow will be a week so if they haven't replied by then can you prod them again?

**Comment by Jcavallo7** [comment]
Will do
