### ISSUE TITLE
Cache node modules between GHA jobs

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#9021]
## Problem statement

As the number of front-end GitHub Actions increases, we'll benefit more from caching installed node modules between jobs.  This only takes a few minutes, but a clean installation happens on each job so it adds up.

## What you need to know

- [Docs](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)

## Acceptance criteria

- [ ] Node modules are cached between jobs, and there are no adverse side effects

**Comment by jpandersen87** [comment]
Upcoming new FE PR workflow does this.
