### ISSUE TITLE
Add GHA workflow to deploy to trial frontend on label add

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#9022]
## Problem statement

We now have a GitHub Action to deploy trial frontends, and we can tweak it so it's more seamless to use in our implementation/design process.

## What you need to know

- [trial_frontend workflow](https://github.com/CDCgov/prime-reportstream/blob/master/.github/workflows/release_trial_frontend.yml)

## Acceptance criteria

- [ ] We can append a label for `trialfrontend(01|02|03)` on pull requests and trigger a trial frontend deployment

**Comment by jeremy-page** [comment]
Hello @stephenkao , we'd like to talk about this at engsync before merging. I am super excited you are working on the pipelines - I just want to make sure the devops team has the chance to understand the changes before they come in since we're responsible to maintain it.

**Comment by stephenkao** [comment]
> Hello @stephenkao , we'd like to talk about this at engsync before merging. I am super excited you are working on the pipelines - I just want to make sure the devops team has the chance to understand the changes before they come in since we're responsible to maintain it.

Hey, @jeremy-page.  Goooood point -- definitely makes sense to me for us to talk through this change so I'll add an item to the agenda to the all-teams sync next week!

**Comment by stephenkao** [comment]
Closing because we're not going to be moving forward with it for now.
