### ISSUE TITLE
Analyze sample message by Sonic to identify ELR Pilot gaps

### ISSUE THREAD

**Issue by jsutantio** [CDCgov/prime-reportstream#9025]
### **User Story**
As a developer contributing to the Full ELR Pilot, I need to understand the current state of our potential sender partner's message - so that I and the team can familiarize myself with our sender's messaging and predict what changes and additions are needed for full ELR interoperability.

### **Background/ Description**
One of our target Sender partners for the Full ELR Pilot is Sonic Healthcare, who is currently using ReportStream to report Monkeypox data to the CDC (via Protect). So that we can hit the ground running, the platform team should gain a baseline understanding of how Sonic is currently reporting, specifically the structure and level of detail that is transmitting in their current HL7 messages.

### **Dev Notes**
Pull message from prod, to ensure it's the most up to date data format.
Potential to run it through the translation step to see what's missing.

### **Risks/Impacts/Considerations**
- Make sure to not pull PII data

### **Relevant Links**
[Full ELR Pilot Plan](https://docs.google.com/document/d/1QycMnAiOk5YlbrTdmtILqLvELwYaHU_dXkD8U0DVpqA/edit#)

### **Open Questions**
- At what level of detail is Sonic providing for various fields (e.g., Test order, test performed, LOINCs, provider vs testing facility details, patient info details, AOEs, dates and times (layers of precision) and do we need to match that fidelity for other conditions beyond mpox?

### **Acceptance Criteria**
- [x] Documented in a location that is accessible to future ELR Pilot team members and linked to this ticket & #prime-reportstream-pipeline slack channel (please tag @jsutantio )
- [x] Denotes preliminary modifications and additions to enable full ELR, potentially prioritizing these items to get an MVP

**Comment by avnieldravid** [comment]
Relevant ticket:  https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/6758

**Comment by JessicaWNava** [comment]
Here is a spreadsheet that compares the spec to what data Sonic is sending over: https://docs.google.com/spreadsheets/d/1DVkdz5MMYKAmdVc6GvN49WwgsB81NZyz4poktOEOsoU/edit?usp=sharing

Until we have a receiver, we will not be able to know if what they are sending is enough data or not because it is really dependent on what the receiver wants. We don't have validation that will prevent this message going through.

**Comment by JessicaWNava** [comment]
I did send a message that I will attach to this ticket through with the PII stripped and the data all unique so I could make sure each piece moved over. Some did not which means we will need to make changes. I will create a ticket for this and link it to this ticket. Here is the spreadsheet: https://docs.google.com/spreadsheets/d/1DVkdz5MMYKAmdVc6GvN49WwgsB81NZyz4poktOEOsoU/edit?usp=sharing

**Comment by JessicaWNava** [comment]
Ticket created here: https://github.com/CDCgov/prime-reportstream/issues/9523
