### ISSUE TITLE
FL - Changes to data transmissions to DOH

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#9063]
## Problem statement

We received an email in the ReportStream inbox requesting changes to the data transmitted to the DOH of FL.

## What you need to know

Email text follows:

> DOH ‘just now’ noticed that we have never reported the patient’s gender on any of our reports.
> 
> I need to add that column to both reports please.
> 
> They also said we no longer have to report the AOE questions but I could just leave the columns there and the answers that the engine transforms. But if we are going to do an update, I have asked them if we can get rid of those columns all together.
> 
> Do you have room in your schedule to help us with this?

The request was forwarded to us by Carlos Felix <carlos.felix@agile6.com>, and originated from Lab-Christine Bittner-Lab Services Manager <cbittner@tallahasseeprimarycare.com>.

## Acceptance criteria

- [ ] Confirm that future transmissions have the requested information removed/added and are processed appropriately.

## To do

- [ ] Evaluate current data transmissions and where the changes can be implemented
- [ ] Apply changes and test
- [ ] Get feedback from the user (and the DOH) that all necessary information is still being reported as needed.

**Comment by carlosfelix2** [comment]
Any updates on this ticket @LaFreda1 @jalbinson? Christine is asking for status. Thx

**Comment by carlosfelix2** [comment]
Here is the request from the FL DOH to TPCA:

> DOH ‘just now’ noticed that we have never reported the patient’s gender on any of our reports. I need to add that column to both reports please.
C. Felix - This is potentially a passthrough form the original report to the output. Some of this is done in JS code and another as NextGen Connect configuration.

> They also said we no longer have to report the AOE questions but I could just leave the columns there and the answers that the engine transforms.
> From FL DOH: Yes! you can complete delete the AOE question columns once you add the patient gender column.
C. Felix - this removal of the AOE questions can result in the removal of all the complicated code to support it, making the code a lot simpler.

> However you need to test with us when you do final fix.
> Please still report the production files by using the format you sent to us today.
> Once you are ready to send the new format, please let us know and send one file to test outbox folder for us to review. Once we approve the new format you can use the new format to report in production.
C. Felix - You cannot update the running NextGen Connect instance until the sample data is accepted. You will have to send it manually to FL DOH. This can be done by having Christine send the file to FL DOH.

**Comment by sliu1000** [comment]
@jalbinson Any updates we can provide to the user?

**Comment by LaFreda1** [comment]
@jalbinson any updates to this?

**Comment by jalbinson** [comment]
@GilmoreA6 has been in correspondence with the Florida DPH to work out the technical details on how to get gender field in their reports.

**Comment by LaFreda1** [comment]
@GilmoreA6 to update repo

**Comment by GilmoreA6** [comment]
Changes to MIRTH code changed and tested. Repository located here: https://github.com/CDCgov/prime-field-teams

**Comment by GilmoreA6** [comment]
Good Afternoon All,

Please see attached for the updated Mirth XML files. Instructions for how to update your Mirth Connect instance are below:

Steps:
Login to Mirth Connect as an administrator. 
Under the Mirth Connect menu, click on Channels.
Click on Import Channel under the Channel Tasks menu and select the attached file.  Click yes when asked to overwrite the channel. 
Under the Channel Tasks menu, click Redeploy All then click Yes.
As a reference, these changes will be stored in this code repository in the next few days.  Let me know if you have any questions,

Thanks,

James

**Comment by GilmoreA6** [comment]
Good morning – can you resend the email with the update attached? I can’t seem to find it.

 

Thank you,

 

Christine

**Comment by GilmoreA6** [comment]
Of course,

Here you go!

Please see attached for the updated Mirth XML files. Instructions for how to update your Mirth Connect instance are below:

Steps:
Login to Mirth Connect as an administrator. 
Under the Mirth Connect menu, click on Channels.
Click on Import Channel under the Channel Tasks menu and select the attached file.  Click yes when asked to overwrite the channel. 
Under the Channel Tasks menu, click Redeploy All then click Yes.
As a reference, these changes will be stored in this code repository in the next few days.  Let me know if you have any questions,


James Gilmore (Agile Six)
Senior HL7 Data Analyst
Pandemic-Ready Interoperability Modernization Effort (PRIME)
