### ISSUE TITLE
Brand workshop planning

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#9065]
## User story
As a user, I want to clearly understand ReportStream and how it meets my needs. 

## Background & context
We want to gather alignment on the brand strategy based on the content audit work for ReportStream so that we can refine it. 

## Open questions

- What should the focus of the workshop be? What is the explicit goal?

- What activities help us accomplish this goal?

- Who should be invited? Who is in the "brand working group"?

- What's the best way to communicate with this group?

## Working links
[Content strategy deck ](https://docs.google.com/presentation/d/1Qa0Ek93niJZQWdHgQCl3LITHTh6_1wEXXAekNGHkh8U/edit#slide=id.g2289fb3b2f8_0_2027)
[Planning doc](https://docs.google.com/document/d/19HtugvMXQwObVNP0gd-uaPnT3Hz2LMuobeAcdRB8ojc/edit?usp=sharing)
[Agenda doc](https://docs.google.com/document/d/1s5Whg-UgoBnJv_NmiwqmMqbjf-n2G9pKkW6hoEEpdQE/edit#)

## Acceptance criteria

- [x] Materials and facilitation guide created 
- [x]  Invite sent

**Comment by audreykwr** [comment]
(accidentally closed haha... those buttons are close together!)

**Comment by audreykwr** [comment]
Basics of the agenda and materials created and linked above The next ticket includes sharing for feedback before finalizing so there will be a few more details put into a deck by then that flesh out that agenda more.
