### ISSUE TITLE
Synthesize and share branding workshop findings 

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#9066]
## User story
As a user, I want to clearly understand ReportStream and how it meets my needs.

## Background & context
The brand workshop brought together SMEs and stakeholders to start work defining what we need to form messaging and tone for ReportSteam and begin to create alignment across the product. After gathering their input, we need to make detailed application plans.

## Open questions
- If there will need to be further meetings before creating a draft of messaging and tone 
- 
## Working links
[Workshop 1 deck](https://docs.google.com/presentation/d/1xuiIhUqvvtknLfAiVPFGMYzZxOwjAPpQ0SeebiqhhDE/edit#slide=id.g21240411e1c_0_50)
[Workshop 2 deck](https://docs.google.com/presentation/d/1AVgp1z_lYwGsnqtYzc_gf_R9IpC-nP6Kvh_QQ7r1cGI/edit#slide=id.g21240411e1c_0_50)

##Acceptance criteria

- [x] - Summary of workshop and next steps shared with design team and meeting attendees
- [ ] - Brief summary shared in all teams sync
- [x] - Detailed tickets created for each artifact

**Comment by lizzieamanning** [comment]
@audreykwr fill out

**Comment by audreykwr** [comment]
Follow up tickets:
https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/9481
https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/9482
https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/9483


These are all good candidates to break down sub steps into a couple tickets but I wanted to get these created for now. As I get started on things this sprint it will be easier to tell what steps to break out without having to make a ton of tickets right now.

@lizzieamanning

**Comment by audreykwr** [comment]
Going to share at the next all teams sync but closing now because that is planned now.
