### ISSUE TITLE
Redesign the ReportStream website information architecture (IA)

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#9071]
## Background and Context 
Our goal is to our users meet their needs faster through content that connects to their journey with us and supports the new features to increase self-service. To meet this need, we want to rethink the website IA.

Primary Purpose: Determine WHERE on the site all of the new content should go and how it should be organized.

## Value Proposition 
Create a journey through connected content experiences.

## Impacted Objectives and Key Metrics (OKRs) 
O: Determine website purpose and how we'll achieve our users goals
KR: Define "user task completion", how it's measured, establish baseline
 - This will be mostly impacting how we measure and establish a baseline

## In Scope 

- Card sort user test
- User journey refinement
- Analysis of card sort and other research results
- Applying results to design
- Both the public and authenticated experiences 

## Out of Scope 

- Additional research activities

**Comment by audreykwr** [comment]
Documenting research needs here, but willing to add it elsewhere as needed. 

@jakefishbein-navapbc As discussed, your research plans for this quarter already cover the following questions that will assist in our new IA: 
1. A validated, clear flow of user process and tasks throughout their RS experience
2. Topics/information needed to help with specific steps along that journey
3. Possibly begin to ID where their journey diverges for different user types

[Follow up ticket](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/9270) created to circle back on this with Jake.

**Comment by chris-kuryak** [comment]
All issues closed
