### ISSUE TITLE
Plan card sort

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#9072]
## User story
As a user, I want the ReportStream website to match my mental model.

## Background & context
We don't know if the site is structured in a way that allows users to find what they need and complete the task at hand.  We don't have a scalable framework for launching and housing new features.

## Open questions

- What tool are we using?
- How will we conduct the test?
- With who? Which users will we prioritize? How many?
- Open or closed sort?

## Working links
[Planning doc](https://docs.google.com/document/d/1ueDqQRYPJvyoKEaMapEo1fzf4LPYT-zNVvShVuuQs4I/edit)
[Research plan](https://docs.google.com/document/d/1SDTgNbcq_WfDxeTgwlm8gEqiewAjGBe5hVLOnpSM-OE/edit#)

##Acceptance criteria
- [x] Finalize list for sort and share with design team for review (async or crit) 
- [x] Finalize how we will conduct the test and test the test to ensure users can access the tool 
- [x] Work with Jake, Sharon, and Lizzie to ID participants
- [x] Send final list to Sharon to send

**Comment by lizzieamanning** [comment]
@audreykwr to add existing list to working links

**Comment by lizzieamanning** [comment]
Linking a research plan template for us to use to make sure we are capturing the assumptions and hypotheses: https://docs.google.com/document/d/1SDTgNbcq_WfDxeTgwlm8gEqiewAjGBe5hVLOnpSM-OE/edit# 

@audreykwr

**Comment by Andrey-Glazkv** [comment]
Working on norms on how and when we contact our users

**Comment by Andrey-Glazkv** [comment]
Check how the work on norms is being tracked

**Comment by audreykwr** [comment]
Got the go ahead to move forward with invites

**Comment by lizzieamanning** [comment]
@audreykwr from who? can you be more specific with this status?
