### ISSUE TITLE
Website content governance definition 

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#9074]
## Background and Context 
Content governance is a key piece of a cohesive and scalable content strategy. It answers questions like how we decide what to work on, how content gets made and by who, and how we will evaluate our content.

Primary purpose: Determine HOW we implement and maintain content on the RS website.

## Value Proposition 
Internal users: for our team to understand who is responsible for what and how we plan to update content on the website 
End user value: excellent user content that is consistently maintained 

## Impacted Objectives and Key Metrics (OKRs) 
O: Determine website purpose and how we'll achieve our users goals
KR: Define "user task completion", how it's measured, establish baseline

O: Self-serve sender onboarding
KR: Sender can onboard through 1/2 of process without an engineer

## Working Links[
Kickoff deck](https://docs.google.com/presentation/d/1JnuBGFqcfBwWnQJGr0s9V13IrirXXormdLbhuM2LVZI/edit#slide=id.g21240411e1c_0_50)

## In Scope 
- Workflow and roles for different types of website content
- ID content owners and approvers for different parts of content
- Define review schedule and requirement
- Content request and evaluation process 

## Out of Scope 
Email, Github, other non website governance (But willing to consider expanding to this or creating another epic to address any of these specifically)

**Comment by lizzieamanning** [comment]
@audreykwr to define the scope a bit more

**Comment by chris-kuryak** [comment]
Closing, all items complete
