### ISSUE TITLE
Add stub pages: main index, facilities/providers index, facilities/providers show, report details

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#9076]
## Problem statement

We need to add route scaffolding to support the STLT Dashboard pages.

## What you need to know

There are four types of pages:
- Main index page
- "All facilities & providers" page
- Facility/provider/submitter details page
- Report details page

## Acceptance criteria

- [x] Routes are added for each page type
- [x] Empty pages are added for each route

**Comment by audreykwr** [comment]
@stephenkao looks good to me! Is there anything we should be aware of with the way facility and provider names may translate into that (funky punctuation or anything)?

When you're talking about accounting for receiver name - would that be their client id? Maybe we add that after `dashboard/`?
