### ISSUE TITLE
Implement main index page design

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#9077]
## Problem statement

As part of the STLT Dashboard, we need to implement the design of the main index page.  This implementation is strictly visual, and we'll have a separate ticket for hooking it up to the API afterward.

## What you need to know

![Screenshot 2023-04-12 at 12.19.15.png](https://images.zenhubusercontent.com/5999b3b38f62dc7798c36942/fa35ad15-388d-44bc-9c56-24ee830135aa)

## Acceptance criteria

- [x] The design of the main index page is implemented
    - Note that this page will not be interactive; it's strictly the visual design.

**Comment by penny-lischer** [comment]
https://www.figma.com/file/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=2369-26965&t=crOeR0RfLyczPtzy-0
