### ISSUE TITLE
Implement report details page design

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#9080]
## Problem statement

As part of the STLT Dashboard, we need to implement the design of the report details page.  This implementation is strictly visual, and we'll have a separate ticket for hooking it up to the API afterward.

## What you need to know

![Screenshot 2023-04-12 at 12.22.18.png](https://images.zenhubusercontent.com/5999b3b38f62dc7798c36942/6ce35d34-c8ae-4c5a-97d5-a9ffc2930f42)

## Acceptance criteria

- [ ] The design of the report details page is implemented
    - Note that this page will not be interactive; it's strictly the visual design.

**Comment by penny-lischer** [comment]
https://www.figma.com/file/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=2369-26965&t=crOeR0RfLyczPtzy-0

**Comment by penny-lischer** [comment]
@jillian-hammer do we need the Hippa notice displayed at the bottom of the page?

**Comment by penny-lischer** [comment]
@jillian-hammer I will add some logic to hide the `Download as HLT` section if the file has expired
