### ISSUE TITLE
Arkansas Onboarding - Build Receiver Settings

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#9083]
### Acceptance Criteria 
- [ ] Added to organization.yml and created yamlitos  
    - [ ] Customer status = testing  
- [ ] Added to prod settings table  
    - [ ] Added quality filter = allowNone() 
- [ ] Added to staging settings table  
    - [ ] Added quality filter = allowNone() 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with receiver 
- [ ] RS team member who originates this ticket: add any dependencies, as needed 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Receiver" and state label 
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by sliu1000** [comment]
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/00a5b6b3-2245-4cbc-8553-a87978067d76)

**Comment by sliu1000** [comment]
Update from Receiver:

Cole Menasco <cole.menasco@arkansas.gov>
Gilmore, James (CDC/DDPHSS/OD/HITSSU) (CTR) <uaf6@cdc.gov>;Glenn Grieves <glenngrieves@navapbc.com>;Donald McCormick <Donald.McCormick@arkansas.gov>
Report Stream (CDC);jamie.albinson@focusconsulting.io;LaFreda Howard <lafredahoward@navapbc.com>
Thanks for the sample message, and everything looks great so far! I saw the VPN listed on this page under the ‘Data transport and sending’ section System and settings | Resources (cdc.gov) but I will talk to our Infrastructure team and figure out which of the options you listed down below would work best for us!

Cole Menasco
Arkansas Department of Health
Promoting Interoperability for Public Health

Sr Software Support Specialist
(o) 501-682-4671
(c) 501-400-4899
cole.menasco@arkansas.gov  | www.ar.gov/mu

**Comment by GilmoreA6** [comment]
Hi Cole,

I hope this email finds you well. The Report Stream team is working diligently to improve our onboarding process. As a part of the onboarding process, we would like to schedule a weekly 15-30 minute meeting between you and James, our engineer leading your onboarding efforts. We will meet until your organization has successfully onboarded to the Report Stream platform.

The purpose of this meeting is to troubleshoot any technical issues you might be experiencing with the onboarding process and to make the process as easy as possible for you. Please send me your available days and times. I will coordinate with James to schedule a time that works best for everyone. Once we have a confirmed day and time, I will send you a meeting invitation.

Starting in Budget Period 5 of the Epidemiology and Laboratory Capacity (ELC) Cooperative Agreement, Project C: Health Information Systems, public health departments are required to connect to ReportStream. In addition, we look forward to ReportStream's upcoming expansion to handle ELR for any condition as well as other laboratory data flows (e.g., ETOR).

I look forward to hearing back from you!



Best,
LaFreda

**Comment by GilmoreA6** [comment]
Good Afternoon Cole,

Just wanted to check in and see if you had a chance to discuss transport methods with your integration folks yet. Let me know if I can help in any way or if we should schedule a call with someone on your side to talk about connectivity details.

Thanks!

James

**Comment by GilmoreA6** [comment]
Good morning all.

 

Please provide additional information highlighted below so we can register the facility into our MURCS system.

 

Facility name:  ReportStream CDC PRIME
Facility address:
Facility EHR or LIS system name:
Facility NPI:
CLIA:  11D2030855
OID (If available):  2.16.840.1.114222.4.1.237821
Administrative Contact person:
Administrative Contact phone number:
Administrative Contact email:
IT Contact:
IT Contact phone number:
IT Contact email:
 

 

Thank you!

 

Amy L. Velazquez

Arkansas Department Of Health

Health Program Specialist III

**Comment by GilmoreA6** [comment]
Settings built locally. Testing with mocked SOAP endpoint. Blocked by #11138

**Comment by chris-kuryak** [comment]
@GilmoreA6 can complete this soon(ish)
