### ISSUE TITLE
Style guide refinement plans

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#9104]
## User story

As a user, I want to have a consistent and clear content to help me use ReportStream.

## Background & context

The audit revealed a need for consistency across our content to aid in user confidence and clarity. The style guide will create alignment for content both on the site and other communications with users. We have started work on a v2 and identified areas to begin defining. There has also been ongoing collaboration with SimpleReport on areas of overlap in style needs for increased consistency across PRIME.

## Open questions

- Which new additions to prioritize
- If we need specific tickets for different additions/updates
- How/when to integrate with design components/style guide

## Working links

- [v2 working doc](https://docs.google.com/document/d/1N8l6F68pzeyILevuQk8KOlBGFuI-vFJE/edit#)

## Acceptance criteria

-   [ ] Update service blueprint with relevant learnings
-   [ ] Update the [questions pool](https://docs.google.com/spreadsheets/d/1THH9Ekj5renvIwSpl-6SzzyUJ5tuNcH76l4GTiboQXE/edit#gid=0) with any questions that came up
-   [x] Priority areas reviewed and Q2 updates scoped and ticketed as needed

**Comment by audreykwr** [comment]
Follow up tickets for priorities

Tentatively planned for sprint 70:
[9565](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/9565)
[9566](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/9566)
[9567](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/9567)

Tentatively planned for Sprint 71:
[9568](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/9568)

**Comment by audreykwr** [comment]
@lizzieamanning closing. See comment above for the scoped updates

**Comment by lizzieamanning** [comment]
@audreykwr looks good. Reminder to add final docs or deliverables as comments to the respective tickets when you get there
