### ISSUE TITLE
Consolidate production, Storybook Webpack configuration

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#9109]
## Problem statement

With Storybook now included in the codebase, we should consolidate the Webpack configurations we use for Storybook and production code to save us from having to maintain two separate sets of rules/loaders/plugins.

## What you need to know

- [Storybook docs](https://storybook.js.org/docs/react/builders/webpack)

## Acceptance criteria

- [ ] Storybook uses our production code Webpack

**Comment by jpandersen87** [comment]
Storybook shares the (now vite from webpack) config as desired.
