### ISSUE TITLE
Send FATAL-ERRORs directly to slack

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#9118]
When we get a FATAL-ERROR we should have it sent to slack, not pagerduty.

Right now [this alert rule](https://portal.azure.com/#@cdc.onmicrosoft.com/resource/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourceGroups/prime-data-hub-staging/providers/microsoft.insights/scheduledqueryrules/pdhstaging-alertrule-functionapp-fatal/overview) calls the `pdhstaging-actiongroup-businesshourspdhstaging` Action. 

This ticket is to create a new action pointing at the Slack webhook and changing the alert rule to use that, instead of the one calling PagerDuty.

So
1. Create a new Action "pdhstaging-actiongroup-slack" that calls the Slack webhook
2. Change the pdh{ENV}-alertrule-functionapp-fatal
 Alert to point to the new Action

**Comment by lucasdze** [comment]
[pdhstaging-actiongroup-slack](https://portal.azure.com/#view/Microsoft_Azure_Monitoring_Alerts/EditActionGroupBlade/actionGroupId/%2Fsubscriptions%2F7D1E3999-6577-4CD5-B296-F518E5C8E677%2FresourceGroups%2Fprime-data-hub-staging%2Fproviders%2Fmicrosoft.insights%2FactionGroups%2Fpdhstaging-actiongroup-slack) action group is now created and used to send slack notification in O&O channel for both Prod & staging envs
