### ISSUE TITLE
Inject Provenance resource when missing

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#9125]
### User Story:
As a Connectathon attender, I want to ensure that people can send me messages that do not contain a provenance without erroring out. In the future, as a Reportstream sender, I want to be able to successfully send messages without a provenance. 

### Description/Use Case
We currently produce an error when a message is sent without a provenance. Instead of throwing an error, we want to inject the provenance message so that the error is not produced. 

### Acceptance Criteria
- [x] A message can be sent without the provenance and it will not fail.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9125?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimmyfagan @mkalish @PatriciaPerozoUSDS @thetaurean @TurkeyFried @victor-chaparro
