### ISSUE TITLE
Conduct 3 card sort tests 

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#9129]
## User story
As a user, I want the ReportStream website to match my mental model.

## Background & context
We don't know if the site is structured in a way that allows users to find what they need and complete the task at hand.  We don't have a scalable framework for launching and housing new features.

## Working links
[Planning doc](https://docs.google.com/document/d/1ueDqQRYPJvyoKEaMapEo1fzf4LPYT-zNVvShVuuQs4I/edit)

##Acceptance criteria
- [x] Create notes docs for session
- [x] Host sessions 
- [x] Send thank you to participants
- [x] Add key takeaways to synthesis after each session

**Comment by audreykwr** [comment]
@chris-kuryak @Andrey-Glazkv some sessions are going to go into next sprint because of user schedules. Is there a way you would prefer to split this ticket somehow or just let it go over?

**Comment by Andrey-Glazkv** [comment]
@audreykwr 
Chris and I had a quick chat on it and realized that probably it would work well if we'd go with splitting and renaming the original one based on number of sessions done and to be done.
The number of sessions done this sprint could go to the name of this ticket and the number of postponed ones could be added to a new one. Like "Conduct card sort (# of sessions)".
What do you think about it?

**Comment by lizzieamanning** [comment]
@audreykwr where is the synthesis living?

**Comment by audreykwr** [comment]
@lizzieamanning The mural is linked in the synthesis section of [the research plan](https://docs.google.com/document/d/1SDTgNbcq_WfDxeTgwlm8gEqiewAjGBe5hVLOnpSM-OE/edit#)
