### ISSUE TITLE
Synthesize IA research findings

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#9130]
## User story
As a user, I want the ReportStream website to match my mental model.

## Background & context
We don't know if the site is structured in a way that allows users to find what they need and complete the task at hand. We don't have a scalable framework for launching and housing new features. 

## Open questions
- What implementation will be needed after the sort findings
- How many open questions we may still have after the test and other research
- If a workshop/design team review would be a helpful way to pull this together

## Working links
[IA synthesis plan](https://docs.google.com/document/d/1glPj88v-AIxYI-rYvPAFVt79J47X1Q4fQGtYDK1P86E/edit#)

## Acceptance criteria
- [x] Card sort, journey research, and core model work synthesized together to answer: What mental models to consider when sorting information? What are the key tasks our users are accomplishing through the site and in what order? What content do we have, have planned or should plan for around these tasks that might influence IA?
- [x] Summary doc/deck created and shared

**Comment by lizzieamanning** [comment]
@audreykwr this deck feels like the culmination of a lot of work! Seems to me like this should be a 5? I want to talk more in our 1:1 on Tues about how the other Webex designers can support you here as well

**Comment by audreykwr** [comment]
on track

**Comment by audreykwr** [comment]
[Synthesis deck here](https://docs.google.com/presentation/d/1d8GA7puc3IGCuHOiFgBUSCgGsCNYAhS3cVSr1OdNUkI/edit#slide=id.g21240411e1c_0_50)
