### ISSUE TITLE
New IA Design implementation

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#9131]
## User story
As a user, I want the ReportStream website to match my mental model.

## Background & context
We don't know if the site is structured in a way that allows users to find what they need and complete the task at hand.  We don't have a scalable framework for launching and housing new features.

Primary purpose: Determine WHERE on the site all of this new information goes on the site and how it is organized.

## Open questions
- Specific implementation needs (until card sort and research is done)

## Working links
[Planning doc](https://docs.google.com/document/d/1ueDqQRYPJvyoKEaMapEo1fzf4LPYT-zNVvShVuuQs4I/edit)

##Acceptance criteria
- [ ] Findings from previous IA work applied - specifics TBD

**Comment by chris-kuryak** [comment]
Close per Jillian
