### ISSUE TITLE
Outline questions on user journey for IA

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#9132]
## User story
As a user, I want the ReportStream website to match my mental model and help me find what I need quickly.

## Background & context
We want our site to connect with our users' journeys in how we organize content on our site. There is work being done to refine our understanding of our users' journey that we can leverage for our IA work.

## Open questions
- What do we specifically need to know more about for effective IA
- If any additional research is needed other than what is planned already

## Working links
[will insert working doc when in progress]

## Acceptance criteria
- [ ] Questions documented
- [ ] Doc discussed with other designers/engagement team
- [ ] Plan created for finding answers

**Comment by audreykwr** [comment]
@lizzieamanning after hearing more from Jake about his plans, I don't think we need any additional research on the journey. I think his findings will naturally feed into the plans for this epic. Okay with closing this?

**Comment by lizzieamanning** [comment]
@audreykwr are your general questions documented anywhere? That will help ensure Jake's research covers what we need

**Comment by audreykwr** [comment]
Plan for this with Jake: going to add a comment to the epic for the record and make a placeholder ticket to follow up with later in the quarter to go through his work with him to put it in the format that is most helpful

**Comment by audreykwr** [comment]
Added a comment to our IA epic, tagged Jake, and made the [follow up ticket here](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/9270). 

Let me know if that works for you @lizzieamanning and if we can close this

**Comment by audreykwr** [comment]
@lizzieamanning closing but willing to reopen if you want further action!
