### ISSUE TITLE
Host governance refinement workshop(s)

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#9133]
## User story

As a user, I want to have up to date, accurate and excellent content.

## Background & context

Governance will be key in bringing together the team to create connected and excellent content that stays updated and relevant. We started this work in Q1 and are building from that to further definition.

## Open questions

- If this needs to be multiple, smaller meetings about specific topics or one larger workshop

## Working links

- [Kickoff deck](https://docs.google.com/presentation/d/1JnuBGFqcfBwWnQJGr0s9V13IrirXXormdLbhuM2LVZI/edit#slide=id.g21240411e1c_0_50)

## Acceptance criteria

-   [ ] Update service blueprint with relevant learnings
-   [ ] Update the [questions pool](https://docs.google.com/spreadsheets/d/1THH9Ekj5renvIwSpl-6SzzyUJ5tuNcH76l4GTiboQXE/edit#gid=0) with any questions that came up
- [ ] Meeting hosted

**Comment by chris-kuryak** [comment]
@audreykwr Do you still plan on doing this? Or is this an old ticket?
If it is old, we are going to close this epic because it looks done otherwise.

**Comment by audreykwr** [comment]
This is an oldie. Something like this happened but way long ago. I am sure it is captured in another ticket but also sure that is not worth digging up at this point haha.

**Comment by chris-kuryak** [comment]
Closing as this happened a while ago.
