### ISSUE TITLE
Scope discovery needs for maintenance phase tasks

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#9135]
## User story

As a user, I need to know the status of my data so that I can do my job.

## Background & context

The audit identified that a large way we meet users' needs after they onboard is through tables and dashboards. It also IDed that an area of opportunity to meet user needs quickly through dynamic and customizable content. 

The goal of digging into maintenance phase needs and dashboard is to meet their needs more efficiently and to prepare for an increase in types of information and data that our users may need to find.

## Open questions

- What specific research activities will help us learn what we need 

## Acceptance criteria

-   [x] Specific qualitative and quantitative research needs IDed
- [ ] Create follow up ticket to develop plans for that research

**Comment by audreykwr** [comment]
[Working research plan](https://docs.google.com/document/d/1B4EERdaTPERjDN8HrscBkGlAI5Sl2c7ZwuX5EkjW6vE/edit#heading=h.8avktwn4ql31)

**Comment by Andrey-Glazkv** [comment]
Waiting for some feedback and to be closed EoD 5/9
