### ISSUE TITLE
Host core model workshop

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#9140]
## User story

As a user, I want to find what I need quickly and understand it easily so I can do my job.

## Background & context

The core model provides a way to anchor content plans around our goals, user needs, and the user journey, creating guidance for consolidating redundant content and IA development. The workshop is the main part of creating those plans.

## Working links

none yet

## Acceptance criteria

-   [ ] Meeting hosted

**Comment by lizzieamanning** [comment]
@audreykwr can you comment with what materials you used in the meeting?
