### ISSUE TITLE
Launch core model synthesis

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#9141]
## User story

As a user, I want to find what I need quickly and understand it easily so I can do my job.

## Background & context

The core model provides a way to anchor content plans around our goals, user needs, and the user journey, creating guidance for consolidating redundant content and IA development. Now that the workshop has been completed, the info needs to be gathered from that work into specific plans to implement. We will start this by syncing on expectations for synthesis as a WebX design team

## Working links

[Core model workshop deck](https://docs.google.com/presentation/d/1v00nuhJSXxrMv1kBXZgqcz2cmWyk5_Nz4Ed86Pp-MO4/edit#slide=id.g21240411e1c_0_50)

## Acceptance criteria

-   [ ] Update service blueprint with relevant learnings
-   [ ] Update the [questions pool](https://docs.google.com/spreadsheets/d/1THH9Ekj5renvIwSpl-6SzzyUJ5tuNcH76l4GTiboQXE/edit#gid=0) with any questions that came up
-   [x] Agenda and materials created and shared for meeting
- [x] Meeting hosted

**Comment by audreykwr** [comment]
Great point to clarify - so the core model synth mentioned in that is *just* IA related. So it just pulled out user flow related work. This is looking more holistically and digging into details on what to include on core pages.[ Plan created related to this ticket](https://docs.google.com/document/d/1iEQJtMlpR-smxUqZt8BD1KpobJDfrzV92sdjds2ZYT8/edit#) should help. Just did this today, so that's why it's not linked yet

**Comment by lizzieamanning** [comment]
@audreykwr great that does help, thank you!

**Comment by audreykwr** [comment]
Meeting happening today to check the last AC here
