### ISSUE TITLE
UP Should support sending FHIR to receivers

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#9144]
### User Story
As a receiver of the Universal Pipeline, I want to be able to receive FHIR.

### Description/Use Case
The UP translate step only supports translating to HL7. We want the ability to skip transforming the internal FHIR message to HL7 if the receiver indicates, via their settings, they want to receive FHIR. 

### Dev Notes:
UP currently only supports HL7 (See `FHIRTranslator.doWork`). Inside that function, instead of converting bundle to HL7, we want to do something like this, probably: `FhirContext.forR4().newJsonParser().encodeResourceToString(updatedBundle)`

Whatever solution we come up with, we need to make sure it is [open-closed](https://stackify.com/solid-design-open-closed-principle/), meaning we can add future formats without directly modifying the doWork function. That probably means some refactoring will need to occur.

We also need to implement support for FHIR->FHIR transforms

### Acceptance Criteria
- [ ] UP can send FHIR to receivers
- [ ] Receiver FHIR->FHIR transforms supported
- [ ] Verified to check if Provenance resource shows that the bundle is coming from ReportStream (and other programs if they modified the provenance as well). If this is not the case, created a ticket for this work. Linked here: TODO

**Comment by arnejduranovic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9144?planning-poker) with Zenhub @TurkeyFried @victor-chaparro @JessicaWNava

**Comment by jimmyfagan** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9144?planning-poker) with Zenhub @jimmyfagan

**Comment by jack-h-wang** [comment]
At the routing step, all intended receivers are added to Provenance as Endpoint resources. We may need to consider removing the Endpoint resources before the bundle is sent to a receiver.
