### ISSUE TITLE
Puerto Rico Onboarding - Go Live Coordination

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#9153]
### Acceptance Criteria 
- [ ] Confirmed with STLT when they want to start receiving (date) 
- [x] Removed quality filter in prod settings = allowNone() 
- [x] Removed quality filter in staging settings = allowNone() 
- [x] Set Customer status = active 

### To Do 
- [x] RS engineer: update this ticket with comments with every interaction with receiver 
- [x] RS team member who originates this ticket: add any dependencies, as needed

**Comment by cloudmagic80** [comment]
Update. Puerto Rico sent the public key file but ReportStream couldn't make a connection to PR's system. We will follow another approach where CDC sends them the public key.
Next steps are:

Send Elvis (Puerto Rico) public key
Elvis to create credentials for Donald
Assign the public key to those credentials so Donald can log into
Elvis to share credentials with Donald
Donald to create the yaml file in the format below and save in keybase.
Here is the basic format of the yaml file.

state: PR
sftp:
host: # the host name provided by the receiver
port: # the port to connect to
path: # provided by the receiver (the file path we write to)
userName: # provided by the receiver
password: # not used
ppkPassword: # the password generated above
ppkFileName: # the file name generated above
ppkFileContents: # the pub key file contents (or the putty file contents)

**Comment by cloudmagic80** [comment]
Connected successfully via Report stream.![Screenshot 2023-08-09 at 6.00.24 PM.png](https://images.zenhubusercontent.com/6421effcbcee2c5ba63f6eaa/b3f5d28a-7724-46f9-bad9-f30d1af653ce)

**Comment by cloudmagic80** [comment]
![Screenshot 2023-08-10 at 7.11.49 AM.png](https://images.zenhubusercontent.com/6421effcbcee2c5ba63f6eaa/617395d2-eb0a-4ded-b68a-958f7b9718ae)
