### ISSUE TITLE
Puerto Rico Onboarding - Set Up Connection

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#9154]
### Acceptance Criteria 

CONNECTION TYPE:
If SFTP:
- [x] 1. Submitted host name for CDC whitelisting
- [x] 2. Retrieve username and PW from STLT 
- [x] 3. Determine if they have public key authentication 
- [x] 4. Add private info to Keybase 
- [x] 5. Create Azure secret staging 
- [x] 6. Create Azure secret production 
- [x] 7. Test connection 

### To Do 
- [x] RS engineer: update this ticket with comments with every interaction with receiver 
- [ ] RS team member who originates this ticket: add any dependencies, as needed

**Comment by brick-green** [comment]
Puerto Rico requested use of Azure Storage transfer which is not something we've set up with other STLTs. But it is an interesting opportunity. Many STLTs use Amazon S3 which is analogous to Azure storage transfer so there many be more requests in the future.

Questions to Puerto Rico:

1.  Can PR pull from a storage container managed by ReportStream?
    -  If so, would that be preferable to SFTP?

cc @cloudmagic80

**Comment by brick-green** [comment]
Request sent to CDC to whitelist PR SFTP site

**Comment by brick-green** [comment]
Emailed Elvis in PR asking to refresh the keys and use public key auth. I added @oslynn to the email so he can cover while I'm out

**Comment by cloudmagic80** [comment]
@oslynn  Let's sync up this week about this. The last email we sent to Elvis (Puerto Rico) was on June 14th.

**Comment by brick-green** [comment]
@cloudmagic80 I just included you on the email to Elvis. Sorry I missed you in the first place!

**Comment by cloudmagic80** [comment]
Send another reminder email to Puerto Rico today about using our public key instead of their private key.

**Comment by cloudmagic80** [comment]
We reviewed a private key from Puerto Rico but we need a public key instead. I am waiting on Puerto Rico. If they need assistance, I can get on a call with them to get the right key.

**Comment by cloudmagic80** [comment]
Update. Puerto Rico sent the public key file but ReportStream couldn't make a connection to PR's system. We will follow another approach where CDC sends them the public key.
Next steps are:
1. Send Elvis (Puerto Rico) public key
2. Elvis to create credentials for Donald
3. Assign the public key to those credentials so Donald can log into
4. Elvis to share credentials with Donald
5. Donald to create the yaml file in the format below and save in keybase.

Here is the basic format of the yaml file.

---
- state: PR
  sftp:
    - host: # the host name provided by the receiver
      port: # the port to connect to
      path: # provided by the receiver (the file path we write to)
      userName: # provided by the receiver
      password: # not used
      ppkPassword: # the password generated above
      ppkFileName: # the file name generated above
      ppkFileContents: # the pub key file contents (or the putty file contents)

**Comment by cloudmagic80** [comment]
Connected successfully via Reportstream.
