### ISSUE TITLE
Create plan and prepare for azure functions 4.x upgrade

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#9175]
### User Story:
As ReportStream, I should be on the latest azure functions release, or at the bare minimum, not on a deprecated one.

### Description/Use Case
Presently RS is using azure function 3.x runtime, which [has reached EOL](https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=v4&pivots=programming-language-java). We need to update to the recommended version, 4.x.

There are two semi-contradictory and abandoned PRs that do this work (We can't use Java 19 with azure 4):
1. https://github.com/CDCgov/prime-reportstream/pull/7539
2. https://github.com/CDCgov/prime-reportstream/pull/8996

We should reconcile the above PRs into one, test it, then come up with a migration/go-live plan and share it with dev ops.

Important update: Turns out azure 4 is already used in production functionapp, we just need to update the runtime used in the RS backend.

### Risks/Impacts/Considerations
We need to make sure our system is working before going live. Does this mean we need to first release to a Demo env and manually test there? Whatever our process is, we need to document it for the future.

### Acceptance Criteria
- [ ] #7539 and #8996 combined into one PR
- [ ] Created a document detailing how to update and test an azure function/Java upgrade
- [ ] reviewed with DevOps

**Comment by jack-h-wang** [comment]
Feedback from eng sync (June 12):
Java 11 is still under support and updating to newer Java might be better left to a separate effort later down the line.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9175?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @mkalish @thetaurean

**Comment by jack-h-wang** [comment]
#10534 appears to build in CI without issue. Speaking with DevOps, merging the PR should be the last step needed to complete the migration; all other steps in the [migration guide](https://learn.microsoft.com/en-us/azure/azure-functions/migrate-version-3-version-4?tabs=net6-in-proc%2Cazure-cli%2Cwindows&pivots=programming-language-java) were completed prior to this effort. They believe allowing the PR to follow the standard process of merging to `master` and testing in staging is low risk; I've asked about the possibility of testing in a demo environment first.

**Comment by jack-h-wang** [comment]
Ran several cycles with DevOps testing the changes made in #10534 on the `demo3` environment. Issues that were encountered seemed exclusive to that environment; sending a test report via Postman performed as expected. This confirmed that merging the PR alone is all that was needed to complete the Azure functions 4.x update. The PR was merged to `master` on 7/27 and smoke tests were run against staging to verify no issues were present.
