### ISSUE TITLE
Create ReportStream deck template draft

### ISSUE THREAD

**Issue by jsutantio** [CDCgov/prime-reportstream#9188]
As a RS team member, I'd would like to use a standardized presentation template so that both my internal and external communications visually reflect RS's branding and mission.

### Description/Use Case
Develop a presentation template draft that utilizes ReportStream's visual brand language (VBL). 

### Considerations
- Consider use with other partnering organizations (e.g., SimpleReport, NBS, CDC OPHDST), and how the RS template may complement existing visual branding while still having a differentiated stance.
- What are the typical uses for a presentation document? Who is the audience? Who is the creator? What are the topics?
- Ensure that the template works with MS Office or can be exported to maintain VBL
- Future: Linked to broader style guide documentation (see epic, link TBA)
- Future: Nice to have: Guidelines for proper and improper use
- Future: Prioritize Google Slides template first, then if possible, convert to PowerPoint

### Links
- [USDS Research PP Template](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1682450693288/890d1f3346f7c9a50eef3aceaa562094b5d16b8f?sender=u8e85df6f9eec764c4bfd6788) (requires CDC access)
- [WIP | ReportStream Presentation Template](https://docs.google.com/presentation/d/1Q3vMZSnjHMOGJfrMc9f2P_bT4EhY27U5IZsgmYrISOk/edit?usp=sharing): blank slides with lorem ipsum
- [WIP | ReportStream Sample Slides](https://docs.google.com/presentation/d/12Gkk5un4syxdyKGJ5dwlwTwfHc43o1r1n6bmy99sD3w/edit#slide=id.p): where I'm stress testing the templates with sample content across use cases from our project

### Acceptance Criteria
- [x] Aligns with CDC brand
- [x] Contains templates that are flexible for all teams and disciplines to use (e.g., design research reports, product timeline planning, engineering requirements) on Google Slides
- [x] Review with USDS stakeholders
- [x] Review with Design team

**Comment by chris-kuryak** [comment]
Hey @jsutantio @lizzieamanning , are we going to be tracking this as work on both Platform and Experience board as well?

**Comment by chris-kuryak** [comment]
@jsutantio Thanks for the heads up! 
I would prefer that if the work on this specific ticket is not being done by WebX folks to remove the experience label (which I have done). That will help keep our board less cluttered. Since the epic has the Experience label, we can use that to see all of the tickets/work related to this epic being done by other teams/boards.

cc: @Andrey-Glazkv for awareness and opinion if he has one

**Comment by lizzieamanning** [comment]
@jsutantio it sounds like @jillian-hammer has bandwidth to take this on this sprint. Let me know if you have any questions/concerns or thoughts to add

**Comment by Andrey-Glazkv** [comment]
Basically as I see it - the question is as follows: does WebX need to track a ticket that is a part of another team's epic/board even if one of WebX team members work on it. I don't think it is necessary for WebX to do simply because Platform has way more understanding of this one than WebX so it would be better to keep it off WebX board and keep it on Platform one.

**Comment by jillian-hammer** [comment]
Re-assigning this ticket to the Web Experience board – thanks @jsutantio!

**Comment by jillian-hammer** [comment]
For your review @lizzieamanning!

**Comment by jillian-hammer** [comment]
Sharing the WIP working links for review with design and @lizzieamanning :

- [WIP | ReportStream Presentation Template](https://docs.google.com/presentation/d/1Q3vMZSnjHMOGJfrMc9f2P_bT4EhY27U5IZsgmYrISOk/edit?usp=sharing): blank slides with lorem ipsum
- [WIP | ReportStream Sample Slides](https://docs.google.com/presentation/d/12Gkk5un4syxdyKGJ5dwlwTwfHc43o1r1n6bmy99sD3w/edit#slide=id.p): where I'm stress testing the templates with sample content across use cases from our project

**Comment by jillian-hammer** [comment]
Status: Reviewing with stakeholders (USDS-ers) today 5/26

**Comment by jillian-hammer** [comment]
Reviewed with USDS stakeholders. Approved to move forward with finalizing the design in #9562!
