### ISSUE TITLE
2 Exceptions - PHDProd-Funtionapp - Scheduled Remote-Connection-Check

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#9190]
## **Problem Statement**
Received a Pagerduty notification on one or more exceptions for PHDPROD-Functionapp

## **What you need to know**
DETAILS 
condition: {"allOf"=>[{"dimensions"=>[], "metricName"=>"exceptions/count", "metricNamespace"=>"microsoft.insights/components", "metricValue"=>2, "operator"=>"GreaterThan", "threshold"=>"0", "timeAggregation"=>"Count", "webTestName"=>nil}], "windowEndTime"=>"2023-04-17T20:45:52.615Z", "windowSize"=>"PT1H", "windowStartTime"=>"2023-04-17T19:45:52.615Z"} conditionType: SingleResourceMultipleMetricCriteria essentials: {"alertContextVersion"=>"1.0", "alertId"=>"/subscriptions/7d1e399...

## **Acceptance Criteria**
Please investigate the exception.
Determine if any further action is needed.

## **To Do**
Assign ticket to an Engineer

**Comment by kant777** [comment]
After speaking to Ott I understand that this happens occasionally, so nothing actionable at this point
