### ISSUE TITLE
Define visual branding needs

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#9193]
## User story 

As a ReportStream user, I want to be able to understand and experience the ReportStream brand in a consistent way 

## Background and context 
Now that we have planned out the content strategy brand activities, we want to plan out the visual activities needed to better define our brand. 

## Open questions

- What activities should we consider?

- Who should be involved?

- What artifacts or elements do we envision as deliverables?

## Acceptance criteria 

- [x] Branding needs identified and paired with loose timeline

**Comment by jillian-hammer** [comment]
Created [Branding (Visual) Workspace](https://app.mural.co/invitation/mural/primedatainput6410/1681847288631?sender=u0c3cdba5126734aceb613229&key=3bde4ece-550a-4394-832b-14e1f27c1894) Mural and populated with a few ideas for us to start with, @lizzieamanning!

**Comment by chris-kuryak** [comment]
Currently blocked awaiting Mo alignment.

**Comment by jillian-hammer** [comment]
@lizzieamanning took a stab at refining the needs and mapping them to a loose timeline on the [Mural](https://app.mural.co/invitation/mural/primedatainput6410/1681847288631?sender=u0c3cdba5126734aceb613229&key=3bde4ece-550a-4394-832b-14e1f27c1894). feel free to take a look & we can discuss synchronously.
