### ISSUE TITLE
Sidenav route integration

### ISSUE THREAD

**Issue by jpandersen87** [CDCgov/prime-reportstream#9198]
In the API Programmer's Guide work, there is want of a sidenav that can be dictated by a data structure. Since we already now represent our routes as data structures as well, it feels like these two areas overlap and there is a possibility of simply updating how our routes are laid out and exposed so that we can use routes as our source of truth when creating UI navigation structures.

**Comment by jpandersen87** [comment]
punting this due questions regarding our app's router's future

**Comment by chris-kuryak** [comment]
No longer needed for API Programmer's Guide Web Content MVP

**Comment by chris-kuryak** [comment]
The functionality of the static side nav covers the needs for our API Prog GUide Web Content MVP and meets Design/Content requirements. This enhanced functionality was for assistance in the future for engineering, but may be no longer needed based on moving to a CMS in the future.
