### ISSUE TITLE
IL - 401/Authorization Token

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#9209]
## Problem statement

*user states* 

Hello, 

On 4/18 around 5 PM eastern time, we started seeing failures to upload records to ReportStream in production. We're unable to fetch the authorization token and it's failing with 401 Client Error: Unauthorized for url: https://prime.cdc.gov/api/token?scope=color-labs.%2A.report&grant_type=client_credentials&client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&client_assertion={{assertion here}}. 

We have not modified anything about our ReportStream code in some time, and we're able to successfully fetch a token in staging just fine. So far, this has only affected the upload of one record for us, but we will likely have more records to submit tomorrow. 

Please let me know if I can provide any additional information to help resolve the issue. I'm also happy to join a troubleshooting call if necessary. 

Best, 

Nick Wheeler

**Comment by GilmoreA6** [comment]
Changes that went in on 4/18 deployment made updates to our code around token authorization. These changes should have been backwards compatible and indeed were for a number of senders, however for color they apparently were not. Moving the public key from the sender to the org solve the issue and Color is receiving bearer tokens again.

**Comment by sliu1000** [comment]
Update from Sender:

Hey James, 

Thanks for the quick response. I was able to get production tokens as you mentioned and resent the messages that had failed yesterday. 

Here's what a request I just would have looked like. The JWT is expired now, so I'm comfortable sharing it over email. 

https://prime.cdc.gov/api/token?scope=color-labs.%2A.report&grant_type=client_credentials&client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&client_assertion=eyJhbGciOiJSUzI1NiIsImtpZCI6ImNvbG9yLWxhYnMuZGVmYXVsdCIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJwcmltZS5jZGMuZ292IiwiaXNzIjoiY29sb3ItbGFicyIsInN1YiI6ImNvbG9yLWxhYnMiLCJleHAiOjE2ODE5MjI0MTgsImp0aSI6IjU5NTIzMzEyLTljNTEtNDIwMi05YjhkLTdjNGZhOGJkZGE5ZiJ9.HV0A_7IpiOgChcmG7kV-51r2baQBuX534g_Q106R4El4m_3aHXwgDI2_uhajkq3yd--EEnpxVw4BihU_0-zFyty8b_YSMfFS7OwadcdEC9p8H42bvTdD4NGHfYuVbz17KZebOHw7t8q2LODhQYxV1uzJTVeZHC0PKFIZC4oqqt1mREAsyFgdvDqL7xR8ipW7NiKAr7GKO_s1hvnFgepP6NZngJNvVS01_PdNloXmeZOZIZjC5VFr0DruAgIoGNdZ2k0ZTazfygT3KjcvXQsWQF-zg8URDUg728bbAcsVp6EmCMaAR5cdiNMs-Fx-9KH4Cb_mwxdDQ0og0Um--fHqRw

Let me know if you need anything else. 

Best, 
Nick
