### ISSUE TITLE
[BUG] [File Validator] 404 error when selecting Receiver

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-reportstream#9212]
## Describe the bug
When selecting an Organization that is a Receiver and navigating to the File Validator the user will see a blank page.

## Impact on ReportStream
Dead page. 

## Steps to reproduce
1. Go to RS
2. Go to Organization Settings
3. Select any Organization that has a 'State' Jurisdiction
4. Click on 'Admin' dropdown then 'Validator'
5. See blank page
6. See 404 in dev tools console

## Expected behavior
As a logged in Receiver, I should be able to see the File Validator Tool and the standard 3 schemas. In other words, it should have the same functionality as the public has (non authenticated user).

## Resources

![Screenshot 2023-04-19 at 8.40.15 AM.png](https://images.zenhubusercontent.com/62697ac1be6e84867ab47e74/13b774a5-3833-4bbc-a550-6acc8519fc66)

**Comment by chris-kuryak** [comment]
This looks closed per PR #9660

@etanb don't forget to reference the relevant PR in the future and close if it is ready to be closed.
