### ISSUE TITLE
[Manage Public Key] Updates when public key already configured

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-reportstream#9217]
## Problem statement

When a public key has already been saved for a kid(orgName.sender) they are not able to re upload a new key and currently receive an error message.

## What you need to know

![Screenshot 2023-04-19 at 1.53.24 PM.png](https://images.zenhubusercontent.com/62697ac1be6e84867ab47e74/d207e0f5-4cc5-4dda-b3a1-2f6e8fd5addf)
## Acceptance criteria

- [x] Remove the button to allow to resubmit
- [x] Add text informing user of what to do.

## To do

- [x] Remove the button to allow to resubmit
- [x] Add text informing user of what to do.

**Comment by penny-lischer** [comment]
Part of https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/7862

**Comment by Andrey-Glazkv** [comment]
A conversation on this is needed among Chris, Jillian, Penny
