### ISSUE TITLE
Bug: Incorrect data is written to the database when UP routing has no receivers

### ISSUE THREAD

**Issue by jack-h-wang** [CDCgov/prime-reportstream#9224]
### User Story

As a ReportStream developer, I want the action table to indicate there are no items and not upload to Azure if there are no receivers to route to, so that I can properly track routing in the UP.

### Description/Use Case

If there is no data that passes the filters within the UP routing function, then by design the data proceeds no further. The information written to the database in this circumstance needs to reflect this more clearly.

### Risks/Impacts/Considerations

The work done here may inform the work to be done for #8451

### Dev Notes

Currently, the Universal Pipeline routing function has alternate logic that skips sending a report to the translate function if it determines there are no receivers for the data it is routing. This logic needs to be updated further to set the `item_count` in the action table to 0, and to not upload an Azure blob.

For previous work and instructions to reproduce the scenario, see the previous issue: #7545

### Acceptance Criteria
- [ ] If UP routing has no receivers, `item_count` must be set to 0.
- [ ] If UP routing has no receivers, an Azure blob should not be uploaded.

**Comment by bishoyayoub** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9224?planning-poker) with Zenhub @TurkeyFried

**Comment by bishoyayoub** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9224?planning-poker) with Zenhub @PatriciaPerozoUSDS
