### ISSUE TITLE
Correct the "TestType" and "Clear Complexity" in LIVD-Table.

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#9231]
Correct the "TestType" and "Clear Complexity" in LIVD-Table to sync up with LIVD-Table download from CDC Website.

**Comment by LaFreda1** [comment]
@kant777  any updates?

**Comment by LaFreda1** [comment]
@kant777 please see Ott if you have any questions

**Comment by LaFreda1** [comment]
Kant to discuss with Ott today

**Comment by oslynn** [comment]
@kant777 , I can find any PR for this work.  Did you create one?

**Comment by kant777** [comment]
The "TestType" and "Clear Complexity" are been corrected to "Test Type" and "ClearComplexity". However the goal seems to be removing the "ClearComplexity" column. Will create another ticket for this.
