### ISSUE TITLE
Fix Storybook run command

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#9235]
In https://github.com/CDCgov/prime-reportstream/pull/9019, we removed the `storybook:start` command.  However, this is still used for the base `storybook` command so we need to fix that.

See [this discussion](https://github.com/CDCgov/prime-reportstream/pull/9019#discussion_r1173098304) for more context.

**Comment by jpandersen87** [comment]
Storybook scripts are currently stable.
