### ISSUE TITLE
DEX Integration

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#9241]
### User Story:
As a CDC project that is sending data to the CDC, I need to be able to send data through the CDC's front door, DEX (Data Exchange). 

### Description/Use Case
Presently, we are sending **OTC COVID** data directly to the Palantir system sitting inside the CDC via azure blob store, HHSProtect. This data is in CSV format and comes from BD Veritor. Instead, we need to interface with DEX and DEX can route to HHSProtect. To do this, we will use the Universal Pipeline and thus will send HL7v2 that closely aligns with the **RadxMars OTC ELR IG**.

The original plan was to onboard BDVeritor to UP and have them send us FHIR and we translate it to HL7v2 for DEX/HHSProtect. Since then, BDVeritor has pulled out of onboarding as just a covid sender to the covid pipeline and we need to either confirm they want to onboard as a FHIR sender or find another sender to send us FHIR/HL7 OTC Covid data. 

We haven't worked through the policy approvals to send the CDC something other than OTC covid data, so if we find another sender, we can only accept OTC data from them OR we need to hash out the policy approvals.

We are also sending MPox data to another system in the CDC, but we will focus on COVID first.

### Acceptance Criteria

- [ ]  RS is able to send HL7v2 or FHIR data to the CDC through DEX

**Comment by brandonnava** [comment]
Closing due to DEX shutting down
