### ISSUE TITLE
Onboard DEX to Universal Pipeline STAGING

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#9243]
### User Story:
As a sender to DEX, I, ReportStream, need to help onboard DEX as a receiver to staging so I can test that everything is getting routed correctly.

### Description/Use Case
DEX should be set up to receive data from RS on staging.

### Dev Notes:
Since RS is going to be doing the routing, I recommend the following setup:
1. DEX should be an organization in RS
2. DEX should have one receiver for ALL HL7 data that goes to DEX. DEX will handle the routing of this data. We are doing a blob to blob store transfer so just need to create a storage account and container for DEX for each receiver (only one for right now for covid OTC data HL7v2) and have them connect, just like we do for HHSProtect.

### Acceptance Criteria

- [ ]  Worked with DEX team (Valluripalli, Sai / ucn2@cdc.gov) from DEX to confirm RS can send data to DEX in the way DEX wants it

**Comment by bishoyayoub** [comment]
Need input from Engagement @brick-green

**Comment by brick-green** [comment]
@arnejduranovic @bishoyayoub the blob storage is set up in staging. DEX confirmed they were able to retrieve a test text file from the storage container. Is there anything else needed for this ticket?

**Comment by arnejduranovic** [comment]
@brick-green We should also set up a DEX org with a receiver in staging and connect that to the storage container, has this been done yet? This should also be entered in the organizations.yml file so we can have it locally and easily reproduce the env.

**Comment by brick-green** [comment]
@arnejduranovic gotcha, still need to add to staging settings

Angela just built in a handy little tool to pull settings more easily from staging or prod and load to org file. I think it's better than committing things to the repo. She's going to demo on monday and eng sync.

**Comment by brick-green** [comment]
Set up the receiver in staging for the covid pipeline. Still not super confident in setting up the filters for UP

**Comment by arnejduranovic** [comment]
@brick-green we will need to do it on the UP, we can get together at some point and pair if needed.

**Comment by brick-green** [comment]
DEX asked for this information: 
<img width="972" alt="image" src="https://github.com/CDCgov/prime-reportstream/assets/86254221/d7a749a0-63f6-41a5-9a1e-107204def685">
Going to work ask devops for some assistance

**Comment by LaFreda1** [comment]
Latest email:

Thank you James for uploading files.

 

Request to provide access to(Ali Shianne)  urw2-su@cdc.gov  or urw2@cdc.gov to the storage account to execute some test cases like  number of files uploaded and number filles received.

 

Here is Ip address of (Ali Shianne CDC system )172.16.7.220

 

Regards,

Naresh

**Comment by chris-kuryak** [comment]
DEX no longer requires integration. Project is being decommissioned.
