### ISSUE TITLE
Create proposal for determining condition given test code or other message data

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#9248]
### User Story

As an engineer on ReportStream, I need to design how to map codes (LOINC, et.al.) to condition names so I can implement a solution where a STLT can give RS a list of conditions they want to receive without worrying about sending specific LOINC codes.

### Description/Use Case

We should design a solution that is:
1. maintainable - we can easily update conditions with new codes (LOINC and otherwise)
2. extensible - we should be able to support more than just LOINC codes and be able to easily expand to others, like LDT or PLA

TODO: Prior stories have populated this research document, it should be referenced in the creation of this design

Additionally, we should review Patricia's research doc and investigate each item listed there (for example, RELMA DB). We should aim to reuse as many existing technologies and solutions as possible.

### Risks/Impacts/Considerations

We need to make sure we understand how our solution fits in with everything else going on at the CDC, like for example, SHIELD.

### Acceptance Criteria

- Created design and reviewed with team and SHIELD project.

**Comment by PatriciaPerozoUSDS** [comment]
One place to start is to read about the [SHIELD LIVD initiative](https://aphlinformatics.atlassian.net/wiki/spaces/SC/overview?homepageId=986579060) - https://aphlinformatics.atlassian.net/wiki/spaces/SLC/pages/915407143/LIVD+File+Repository+Requirements

They are no where near having something usable and in prod but we can learn from them

**Comment by GilmoreA6** [comment]
PR created here https://github.com/CDCgov/prime-reportstream/pull/11122

**Comment by GilmoreA6** [comment]
Ask from Platform to include AOE logic and monitoring in initial Proposal.

**Comment by GilmoreA6** [comment]
Monitoring will involve utilizing action log to record when condition can not be mapped from code.

**Comment by GilmoreA6** [comment]
Strategy will involve modifying LookupTableValueSet.kt to log a warning whenever no value is found. We will also need to add a new warning type "Unmapped" to ActionLog.kt

**Comment by GilmoreA6** [comment]
New strategy proposed by Arnej/platform. Modifying design schematic to accommodate. Will have custom fhir bundlehelper to map condition for LOINC/SNOMED.
