### ISSUE TITLE
Revamp Layout of COVID Pipeline Service Blueprint

### ISSUE THREAD

**Issue by jsutantio** [CDCgov/prime-reportstream#9268]
## User story
As an RS teammate, I want to be able to visualize all the people, tools, and processes that are a part of the ReportStream system, so that I have a comprehensive view of how it works.

## Background & context
We created a first draft of the service blueprint a few months ago, but want to add additional detail related to the differences between the COVID pipeline and UP. As an incremental step to this epic, we want to change the layout of the service blueprint to make it easier to visually scan, read, and follow. Below are suggested methods:

1. Linearly (either horizontally or vertically) document the flow of data as it goes (and iterates) through the RS system from user onboarding to the beginning of system maintenance (like a journey map)
2. Label high level steps/ phases with headers and colored backgrounds that enable us to easily identify on phase to another
3. Overlay additional information users (senders, receivers, engagement team/ admins), testing environment, & tools as layers, icons, comment boxes, etc.

## Working links
- [COVID Service blueprint](https://app.mural.co/t/nava4113/m/nava4113/1672148125717/f376adefc22f136c60e40cb9f60b1b74ef4ee43d?sender=u791b7d4d34761ac59b672214) This is the service blueprint mural that has been widely distributed and linked to.
- [Service blueprint Workspace](https://app.mural.co/t/nava4113/m/nava4113/1681488534126/acccd696c031a19d3335e62204ece296ef483b9e?sender=u8e85df6f9eec764c4bfd6788) This is the temporary space that contains drafts and in progress work.
- [Onboarding task analysis dashboard](https://lookerstudio.google.com/u/0/reporting/921e245e-7d5c-4bec-b997-4e1d1f39cdd7/page/p_que8p0on4c) (focuses on senders and receivers, excludes admin/ internal engineers)

## Acceptance criteria
- [x] Journey of RS data from user onboarding to beginning of data maintenance is documented in a linear manner
- [x] Contains the following additional data that was documented in previous version of the blueprint: phases, users (senders, receivers, engagement team/ admins), testing environment, & tools
- [x] Nice to have: timing metrics for major steps
- [x] Copy and paste below current Service Blueprint Mural (with dated note that describes the changes)
- [x] Share during RS team-wide sync

Not within scope:
- [ ] Include universal pipeline (UP) implications or pilot exceptions
- [ ] Precise timing/ durations for each step
- [ ] Documenting "before onboarding" steps (e.g., patient testing/ test submission)
- [ ] Documenting "post onboarding" steps (e.g., RS maintenance, ELR migration, bugs and errors)

**Comment by dylansmith-Nava** [comment]
Sure! Let's start together. Lizzie mentioned you had an idea about how you wanted to improve the service blueprint. Should we find some time to meet up and discuss?

**Comment by dylansmith-Nava** [comment]
Awesome thank you! I will take a look.

**Comment by dylansmith-Nava** [comment]
@jsutantio and I finished out latest version on 5/24 and plan to share out during this week's Design Crit for any last-minute feedback or notes.

**Comment by dylansmith-Nava** [comment]
Added this ticket to the new sprint (Sprint: May 24 - Jun 6, 2023) since Jess observed that we'll still need feedback from Engagement + Platform engineers to make sure the content/structure is feeling good.

**Comment by dylansmith-Nava** [comment]
@lizzieamanning Jess and I feel good about the final version and posted it to the [official Mural](https://app.mural.co/t/nava4113/m/nava4113/1672148125717/f376adefc22f136c60e40cb9f60b1b74ef4ee43d?sender=ufb3824a0e63fafb0304f5774)!

We also put ourselves on the books to showcase the blueprint a bit at the RS All Teams Sync next Wed (5/31), if we have time. Thanks!

**Comment by dylansmith-Nava** [comment]
@lizzieamanning just a note that @jsutantio and I shared out the [Blueprint Mural](https://app.mural.co/t/nava4113/m/nava4113/1672148125717/f376adefc22f136c60e40cb9f60b1b74ef4ee43d?sender=ufb3824a0e63fafb0304f5774) in all-team sync today. Owing to that, I think we can close this ticket out!
