### ISSUE TITLE
PA - MUser PW Expiration 4/23

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#9271]
## Problem statement

Several accounts on MUSER will have passwords to expire in 6 days. Please change password prior to deadline for the following accounts:

achdUSDSewsprod
pphlUSDSewsprod
cchdUSDSewsprod
mcophUSDSewsprod

## What you need to know

 PW at time of writing will expire in 7 day

## To do

Reset PW's

**Comment by brick-green** [comment]
These receivers have been depricated. We don't need to reset the PWs
