### ISSUE TITLE
Make Metadata DB Calls more reusable

### ISSUE THREAD

**Issue by luis-pabon-tf** [CDCgov/prime-reportstream#9272]
### User Story
As a ReportStream developer, I want to minimize duplicate code to make the program more maintainable.

### Description/Use Case
The code in the database classes related to fetching from the `Metadata` tables is very specialized at the moment. For example, Delivery Facilities directly fetches formatted facility data.

### Risks/Impacts/Considerations
Reusable code is not always the fastest code, there may be queries that need to keep their code unique.

### Dev Notes
Identify and update queries where possible so that use-case-specific formatting is not done in the Database classes.

### Acceptance Criteria
- [x] Reduction of copy/pasted code on Metadata-related DB code

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9272?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @mkalish @thetaurean @victor-chaparro
