### ISSUE TITLE
Publish Release Notes - June 2023

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9274]
### Problem statement
As a user, I would like to know what features, bugs, other user facing updates have been made to ReportStream product.

### Procedure
https://docs.google.com/document/d/1vAiOJlfRMvJPRER3cr9Kr4lQ2-_ybNucJt28kI3fl1I/edit 

### Acceptance criteria
- [x] Delivery Manager: Final Release Notes text (in ticket description) updated with all release notes and formatted with markdown
- [x] Content Specialist: Approve release notes content and formatting
- [ ] Engineer: Add **Final Release Notes Text** to [Release Notes page](https://reportstream.cdc.gov/product/release-notes) (reference Procedure above if needed)

## Release Notes Text
**New Features**:
[The API Programmer's Guide,](https://reportstream.cdc.gov/resources/api) previously only available as a PDF download, is now part of the ReportStream website. The web pages provide a user-friendly format that ensures users always have the most updated information.

**Bug Fixes**:

- Users that receive data through ReportStream can now access the [File Validator](https://reportstream.cdc.gov/file-handler/validate) while logged in.
- Contact and service request links on the [support](https://reportstream.cdc.gov/support) page have been fixed.

**New State Connection**:

We’re excited to announce that ReportStream can now send public health data to South Dakota.

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
South Dakota has been added as a receiver!
(per Ott in Slack)

**Comment by Andrey-Glazkv** [comment]
New Features

tbd

Improvements

tbd

New State Connection: We’re excited to announce that ReportStream can now send public health data to South Dakota.

**Comment by chris-kuryak** [comment]
New Features:
- A web version of the ReportStream API Guide has been added to the ReportStream website at
https://reportstream.cdc.gov/resources/api. Previously, this was only available via PDF. This new web version provides an enhanced user-experience and up-to-date guidance for those connecting to the ReportStream API.

Bug Fixes:
- Users that receive data through ReportStream can now access the File Validator Tool while logged in.
- "Contact" and "Service Request" links on the Support Page (https://reportstream.cdc.gov/support) have been fixed.

**Comment by Andrey-Glazkv** [comment]
**New Features:**

A web version of the ReportStream API Guide has been added to the ReportStream website at
https://reportstream.cdc.gov/resources/api. Previously, this was only available via PDF. This new web version provides an enhanced user-experience and up-to-date guidance for those connecting to the ReportStream API.

**Bug Fixes:**

Users that receive data through ReportStream can now access the File Validator Tool while logged in.
"Contact" and "Service Request" links on the Support Page (https://reportstream.cdc.gov/support) have been fixed.

**New State Connection:**

We’re excited to announce that ReportStream can now send public health data to South Dakota.

@audreykwr  - please review this version of release notes

**Comment by audreykwr** [comment]
Edited version below:

**New Features**:
[The API Programmer's Guide,](https://reportstream.cdc.gov/resources/api) previously only available as a PDF download, is now part of the ReportStream website. The web pages provide a user-friendly format that ensures users always have the most updated information.

**Bug Fixes**:

- Users that receive data through ReportStream can now access the [File Validator](https://reportstream.cdc.gov/file-handler/validate) while logged in.
- Contact and service request links on the [support](https://reportstream.cdc.gov/support) page have been fixed.

**New State Connection**:

We’re excited to announce that ReportStream can now send public health data to South Dakota.

**Comment by Andrey-Glazkv** [comment]
@etanb if you have time - could you please incorporate Audrey's version to the website? Thank you!

**Comment by Andrey-Glazkv** [comment]
@audreykwr thank you!

**Comment by audreykwr** [comment]
@etanb should we have a separate ticket for creating the content then? That's the part that was in progress.

**Comment by etanb** [comment]
Yes, I think so. The ticket for publishing the Release Notes should just have the finalized text with the goal of an Engineer deploying said text.

**Comment by Andrey-Glazkv** [comment]
No problem - we can have two tickets instead of one next time.
1. For getting content approved
2. For actually publishing it
@chris-kuryak @etanb @audreykwr
