### ISSUE TITLE
IN - STI/STD Reporting Interest

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#9275]
## **Problem Statement**

We received an email in the ReportStream inbox regarding Indiana's desire to participate in STI/STD reporting.

## **What you need to know**

Message received from pkambhampati@health.in.gov:

> Thanks for your time and effort in getting feedback and trying to make ReportStream system accessible to multiple reportables for Public Health Agencies (PHA).
> 
> Please see my responses below.
> 
> - Are you interested in receiving full ELR data for reportable conditions other than COVID?
>      Yes, certainly. Priority ones are STD (which is on the top of the list) followed by Hepatitis. STD’s and Hep are top 2 conditions which we consume the most by volume in Indiana. Beyond STD and Hep, it’s a SME call if they want to receive ELRs from RS for other reportable diseases.
> 
> - Are you interested in receiving manual entries for STI/STD from our sister product, simple report?
>      Our STD program prefers to have automated process from RS feed, so they can be ingested into our surveillance system - like we are currently doing with COVID. As long as its not adding manual work of data entry our side – we don’t want to miss out on data being entered in Simple reports for Indiana patients. Not sure, if my response makes sense though. I can reach out to STD program team, if you want more comprehensive reply from Indiana. Please let me know.
> 
> Thanks !
> 
> Padma Kambhampati  |  Applications Systems Analyst/Programmer Sr.

## **Acceptance Criteria**

Establish documentation regarding future STI/STD reporting via ReportStream that can be provided to users/organizations/STLTs interested in participating.

## **To Do**

- [ ] Determine next steps in this process
- [ ] Provide specific direction to the RS Support team regarding the handling of these messages

## **Additional Comments**

This email was forwarded to Michael Judd (vuj4@cdc.gov) on 4/21/23. LaFreda and Glenn Graves were CC'd on the initial email.

**Comment by LaFreda1** [comment]
Closing this ticket as we are not offering STI/STD at the moment. I will refer Indiana to the platform team for Full ELR
