### ISSUE TITLE
Kansas onboarding reflections and analysis 

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#9281]
## User story
As an Engagement team member, I want to have a chance to review the particular steps of Kansas's onboarding process so that we can replicate what contributed to the shorter-than-usual timeline

## Background & context
We onboarded Kansas in ~two weeks (April 5th to April 18th). We want to examine what exactly supported this fast pace so we can replicate it in other onboarding efforts.

Some notes:

- STLT understood needs
- STLT was excited, eager, this helped move things forward
- Ott was in constant contact after the initial follow up meeting
- Not that different than usual, but timelines aligned on both sides

## Open questions

- How to replicate momentum?
- How to classify the STLT?
- How much data do they get?
- What roles were on the call?
- How big is the state? Do we know anything about their resources?
- What is the history? I.e., last contact, are there new employees

## Working links
[Drive with Kansas threads](https://drive.google.com/drive/folders/1xDE6uxa7ZDuB-kWxwzsbDXTKguZihlx1)
[Notes from Ott Interview](https://docs.google.com/document/d/1d4m4s6nkrWdP2Jq-nAQHRjomy9rdGklBJ4XB17xRj3c/edit#heading=h.5d3xmmoa5n8j)
[Research Plan](https://docs.google.com/document/d/1xHmk7nkTt00ReaNCzW60MhtZEUz8em-1Y5WYIqv-bas/edit#heading=h.ywptbibq7pqj)
[Interview Guide and Notes](https://docs.google.com/document/d/1IWrWZERsnQ6CkcndMW1U7zBfoc6mP8cFXdCIWFj6u8E/edit#)
[Final Analysis](https://docs.google.com/presentation/d/1P4OjfZpVqTmm5YLtzHypmYAXUKlIv0hluLd4OYsjdN4/edit#slide=id.g1f9b1d1a6a4_0_104)

## Acceptance criteria

- [x]  Review emails and notes to come up with some observations about this particular onboarding process
- [x]  Facilitate call with Kansas 
- [x] Facilitate debrief with Engagement engineer (Ott) 
- [x]  Synthesize and summarize learnings
- [x]  Share with the design and Engagement team owner @GlennRGrieves @LaFreda1 
- [ ]  Add any recommended changes to the existing onboarding SOP

**Comment by lizzieamanning** [comment]
## User story

As an Engagement team member, I want to have a chance to review the particular steps of Kansas's onboarding process so that we can replicate what contributed to the shorter-than-usual timeline

## Background & context

We onboarded Kansas in ~two weeks (April 5th to April 18th). We want to examine what exactly supported this fast pace so we can replicate it in other onboarding efforts.

Some notes: 

- STLT understood needs 
- STLT was excited, eager, this helped move things forward 
- Ott was in constant contact after the initial follow up meeting 
- Not that different than usual, but timelines aligned on both sides 

## Open questions

- How to replicate momentum?
- How to classify the STLT?
- How much data do they get?
- What roles were on the call?
- How big is the state? Do we know anything about their resources?
- What is the history? I.e., last contact, are there new employees 


## Working links

##Acceptance criteria

- [ ] Review emails and notes to come up with some observations about this particular onboarding process

- [ ] Plan a retro to engage the rest of the team in analyzing this effort in particular 

- [ ] Synthesize and summarize learnings in a deck 

- [ ] Share with the design and Engagement teams

- [ ] Add any recommended changes to the existing onboarding SOP

**Comment by jakefishbein-navapbc** [comment]
Call with Kansas scheduled for 4/28/2023 at 3:30pm EST

**Comment by lizzieamanning** [comment]
@jakefishbein-navapbc do you mind linking the deck as a comment?

**Comment by jakefishbein-navapbc** [comment]
@lizzieamanning I was under the impression that we could go with the research report rather than reformatting into a slide deck. Is that still ok or do you need me to create the deck?

**Comment by lizzieamanning** [comment]
Agreed! Just calling out that it would be helpful to link that report in a comment for clarity as to what the deliverable of the ticket is

**Comment by jakefishbein-navapbc** [comment]
[Final Analysis](https://docs.google.com/presentation/d/1P4OjfZpVqTmm5YLtzHypmYAXUKlIv0hluLd4OYsjdN4/edit?usp=sharing)
