### ISSUE TITLE
Convert TokenFunction use annotations for API documentation

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#9300]
# User Story:
As a consumer of the report stream API, I want the token endpoints to be automatically kept in sync with the code

# Description/Use Case
The endpoints in TokenFunction are automatically documented when the code is built

# Risks/Impacts/Considerations

# Dev Notes:
Should be able to refer to ApiKeysFunctions for example of how to add these annotations

# Acceptance Criteria
- [ ] all the functions in `TokenFunction` is documented via annotations

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9300?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @luis-pabon-tf @mkalish @thetaurean

**Comment by arnejduranovic** [comment]
This function will no longer exist with new microservice pattern. Closing.
