### ISSUE TITLE
Add a gradle task for running a swagger-ui to see the API documentation

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#9302]
# User Story:
As a consumer of the report stream API, I want to be able to easily view the API documentation

# Description/Use Case
Swagger UI can be used to visualize the the API documenation

# Risks/Impacts/Considerations

# Dev Notes:
The added swagger gradle plugin should support this with some configuration

# Acceptance Criteria
- [ ] a gradle task can be run that opens the API documentation in a browser via swagger ui

**Comment by arnejduranovic** [comment]
It shows this story is blocked but doesn't #9240 fix this issue?

**Comment by mkalish** [comment]
I'll update the dev notes, but the gradle plugin can actually be used to create a nice ui for testing and looking at the apis https://petstore.swagger.io/ for example.  This PR would set up task to generate that same UI but for the report stream api.

@arnejduranovic

**Comment by arnejduranovic** [comment]
@mkalish Does this story include deleting the manual .yml files we created and adding decorators to the code so the plugin can generate the docs automatically? If so I would make that work more clear in the ticket.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9302?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimmyfagan @luis-pabon-tf @mkalish

**Comment by JFU-NAVA-PBC** [comment]
PR in review, and created a DevOpSec ticket for deployment and configurations on Azure ENVs: 
#10621
