### ISSUE TITLE
Bug: Show error message when the provenance IllegalStateException is thrown.

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#9304]
### User Story:
As a Reportstream user, I want clear responses returned to me.

### Description/Use Case
When I submit a message without a provenance, it will throw an IleegalStateException which can be seen in the logs, but when you hit the submission by report id endpoint, it continues to say received rather than provide an error, so it appears that the message may at some point be sent.

### Dev Notes:
To reproduce this, remove the provenance from a message. Set the quality filter to something that will pass (you cannot just remove it because this will put in place a complicated default quality filter). Send the message

### Acceptance Criteria
- [ ] An error shows in the submission history for a message without a provenance.

**Comment by arnejduranovic** [comment]
@JessicaWNava is this needed now with https://github.com/CDCgov/prime-reportstream/pull/9306 getting merged to master?

**Comment by JessicaWNava** [comment]
Nope, closing.
