### ISSUE TITLE
Terraform checkov detection: CKV_AZURE_109: "Ensure that key vault allows firewall rules settings"

### ISSUE THREAD

**Issue by lucasdze** [CDCgov/prime-reportstream#9312]
Check: CKV_AZURE_109: "Ensure that key vault allows firewall rules settings"
    FAILED for resource: module.init.azurerm_key_vault.init
https://www.checkov.io/5.Policy%20Index/terraform.html

**Comment by snesm** [comment]
Previously added to `.github/workflows/validate_terraform.yml` `skip_check`.
