### ISSUE TITLE
Terraform checkov detection: CKV2_AZURE_32: "Ensure private endpoint is configured to key vault"

### ISSUE THREAD

**Issue by lucasdze** [CDCgov/prime-reportstream#9317]
Check: CKV2_AZURE_32: "Ensure private endpoint is configured to key vault"
	FAILED for resource: module.init.azurerm_key_vault.init

https://www.checkov.io/5.Policy%20Index/terraform.html

**Comment by snesm** [comment]
CKV2_AZURE_32 is obsolete.
