### ISSUE TITLE
Terraform checkov detection: Check: CKV2_AZURE_33: "Ensure storage account is configured with private endpoint"

### ISSUE THREAD

**Issue by lucasdze** [CDCgov/prime-reportstream#9318]
Check: CKV2_AZURE_33: "Ensure storage account is configured with private endpoint"
	FAILED for resource: module.storage.azurerm_storage_account.storage_partner and all other storage accounts

https://www.checkov.io/5.Policy%20Index/terraform.html

**Comment by snesm** [comment]
CKV2_AZURE_33 is obsolete.
