### ISSUE TITLE
Add Web Analytics tracking to PDF download button and other relevant interactions

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9331]
## Problem Statement

Currently, there is no mechanism to track how many times the API Programmer's Guide PDF version is downloaded from the RS website. This information is useful to determine how often people will be using the PDF version vs the web version of the API Programmer's Guide, in an effort to potentially phase out the PDF version. This would make it simpler to keep our documentation aligned and up to date with our users.

The "button" we want to track is the one just under the cards on this page:
https://reportstream.cdc.gov/resources/reportstream-api

## Acceptance Criteria
- [x] Tracking is added to the download link of the API Programmer's Guide that sends information to Azure App Insights
- [x] Alert Chris to the query that can be created to track this event

**Comment by penny-lischer** [comment]
let usg_events = dynamic(["*"]);
let mainTable = union requests, customEvents
    | where timestamp > ago(7d)
    | where isempty(operation_SyntheticSource)
    | extend name =replace("\n", "", name)
    | extend name =replace("\r", "", name)
    | where '*' in (usg_events) or name in (usg_events)
    | where name == "API Programmer\'s guide";
    let resultTable = mainTable;
resultTable
| summarize ["Download Count"] = sum(itemCount) by name, bin(timestamp, 24h)
| render columnchart

**Comment by penny-lischer** [comment]
In review

**Comment by chris-kuryak** [comment]
Regarding the Dashboard Query code and chart, I approve.
