### ISSUE TITLE
Add Design and Content for downloading the PDF version of the programmer's guide

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9340]
## Problem statement

The PDF Version of the Programmer's Guide has the ability to search the entire document and may be preferred by some users. Until more definitive information is known about it's usage by users, we should include it as a downloadable option to the Web Version of the Programmer's Guide.

## What you need to know
- The PDF Version already exists as a downloadable document [here](https://reportstream.cdc.gov/resources/programmers-guide)

## Acceptance criteria

- [x] Add necessary Design/Content to the API Programmer's Guide design for the ability to download the PDF version 
- [x] Inform @jpandersen87 and @chris-kuryak when it is ready to be reviewed

## To do

- [x] Add design to the SOT Figma file once approved by prod/eng

**Comment by jillian-hammer** [comment]
hi @audreykwr – thoughts on something like this? (text is just FPO, of course)!

![ProgGuide_DownloadPDF_050523.png](https://images.zenhubusercontent.com/639236212968fbce989b5d65/eaaa5b83-9a02-43c0-bc63-a3927a54c9d7)

**Comment by audreykwr** [comment]
Hmm. I'm not the placement feels quite right... Maybe after release notes? It's not quite "about our API" like the other two things are. Is last on the page too low though? If so, then my other vote would be under the cards

**Comment by jillian-hammer** [comment]
@audreykwr thanks for reviewing! that's fair – here are some other options i tried with the link higher on the page, but i felt like it competed with the cards and was a little confusing, especially for users who aren't aware of our internal PDF or no PDF debate haha. 

![ProgGuide_DownloadPDF_050523_v3](https://github.com/CDCgov/prime-reportstream/assets/119958649/c1b50f2f-25a0-4490-ba2e-4940548495e5)
![ProgGuide_DownloadPDF_050523_v2](https://github.com/CDCgov/prime-reportstream/assets/119958649/bc8f832f-5d48-4afb-bc84-de61336351e5)

i think it makes sense towards the bottom of the page as a footnote/extra resource, something like below? 

![ProgGuide_DownloadPDF_050523_v4](https://github.com/CDCgov/prime-reportstream/assets/119958649/a6f9be62-5c5b-43c5-b797-4234afdf8ee8)

**Comment by audreykwr** [comment]
I see that.... I think I'm leaning toward the no button one. Feels the least intrusive? 

Maybe with the copy being: 

"Our API guide and documentation is also available as a downloadable PDF."

**Comment by jillian-hammer** [comment]
stand up status: on track, waiting for approval from @jpandersen87

**Comment by jpandersen87** [comment]
👍
