### ISSUE TITLE
Refactor duplicate code in ActionHistory

### ISSUE THREAD

**Issue by jack-h-wang** [CDCgov/prime-reportstream#9345]
### User Story
As a ReportStream engineer, I want to reduce duplicated code, so that the codebase is more concise and maintainable.

### Description/Use Case
The `trackCreatedReport` function in `ActionHistory.kt` has two overloads which are extremely similar in function and have a lot of code copy and pasted from the other. We should refactor this so that we do not have duplicate code in the codebase.

### Risks/Impacts/Considerations
This function serves a central purpose to track work done in all pipelines. Care should be taken to exercise all pipelines when testing.

### Dev Notes
- The overload is to handle a case where `receiver` is not provided by the caller. Additionally, as of #9224 the UP may pass `null` in place of `blobInfo`.

### Acceptance Criteria
- The code executed when calling `trackCreatedReport` can be covered with a single unit test.

**Comment by AncutaIoan** [comment]
hi, could I maybe work on this?

**Comment by arnejduranovic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9345?planning-poker) with Zenhub @JessicaWNava @mkalish @JFU-NAVA-PBC @jack-h-wang @luis-pabon-tf
