### ISSUE TITLE
Build a reusable API Response object

### ISSUE THREAD

**Issue by TurkeyFried** [CDCgov/prime-reportstream#9346]
### User Story
As a ReportStream API user, I want responses to be consistent so that integrations are easy to implement.

### Description/Use Case
The [Website API Payload Proposal](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/proposals/0019-website-api-payload-structure.md) provides a structure that is not currently used on any endpoints. API users, when provided with documentation, will expect responses to match it.

### Risks/Impacts/Considerations
Changing existing endpoints would break existing integrations.

### Acceptance Criteria
- [ ] An object that can be used on any endpoints matching the structure on the proposal

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9346?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @mkalish @thetaurean

**Comment by victor-chaparro** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9346?planning-poker) with Zenhub @victor-chaparro
