### ISSUE TITLE
Research SHIELD project for condition mapping

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#9352]
### User Story

As an engineer on ReportStream, I need to understand how the **SHIELD** project is handling or planning to handle mapping codes (LOINC, et. al) to conditions so that I can come up with a solution for ReportStream and maximize reuse.

### Description/Use Case

Information on the SHIELD project can be found here: https://aphlinformatics.atlassian.net/wiki/spaces/SC/overview?homepageId=986579060

It sounds like SHIELD will eventually have some mechanism for mapping codes to conditions. We should look to understand what their current and future capabilities are and see if we can reuse any of their work or help them along their path.

SHIELD may also have rhapsody configs/tables we should look at to see if they are doing any mapping there.

DM @arnejduranovic for SHIELD contact info.

### Acceptance Criteria

- [ ] Contacted SHIELD for a representative that may provide us Rhapsody config
- [x]  Develop questions to ask SHIELD contact
- [x] Held meeting with SHIELD regarding code to condition mapping
- [ ] Created (if does not exist already) or updated existing condition to code mapping proposal document in repo with findings.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9352?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimmyfagan @mkalish @thetaurean @TurkeyFried @victor-chaparro

**Comment by GilmoreA6** [comment]
https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x0120004368ADED9C3BEA4B94E57C5781F119FF&id=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FDesign%20and%20Research%2FUniversal%20Pipeline&viewid=17db3ff6%2D95c5%2D4562%2Da1f3%2D12b5097b5947
