### ISSUE TITLE
CO - Prod Failure 5/1/23

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#9358]
## **Problem Statement**

An alert was received in Slack regarding a production error for CO.

## **What you need to know**

Message details:

> [1;31m18:45:19.581 [pool-2-thread-2445][87854] FATAL-ALERT gov.cdc.prime.router.azure.SendFunction - FAILED Sftp upload of inputReportId `43354ca2-c12b-4402-81e9-610a451900bf` to SFTPTransportType(host=prod.moveit.state.co.us, port=22, filePath=./, credentialName=null) (orgService = co-phd.elr-hl7), Exception: Connection timed out (Connection timed out), All retries failed. Manual Intervention Required. Send Error report for: `43354ca2-c12b-4402-81e9-610a451900bf` to co-phd.elr-hl7[m

## **Acceptance Criteria**

- Connection is restored and data is resubmitted successfully.

## **To Do**

- [ ] Investigate cause of connection error and resolve.
- [ ] Resubmit data

## **Additional Comments**

Report ID: `43354ca2-c12b-4402-81e9-610a451900bf`

**Comment by oslynn** [comment]
This ticket is duplicated with ticket #9361 which I am working on.
