### ISSUE TITLE
CO - Fatal Errors 5/2/23

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#9375]
## Problem statement

[Write a short description of what you want to achieve with this task]

Last Mile Failures show CO having trouble sending results. While checking receiver dashboard, it is showing CO is down.

 [Links to documents, workflows, or list of key people and contact info]

![image.png](https://images.zenhubusercontent.com/62828ac9597e3bae41382df7/828d0c85-1a31-4cd8-8be1-2311f704fcff)

## Acceptance criteria

- [ ] ...

- [ ] ...

**Comment by oslynn** [comment]
The CO-PHD.ELR-HL& just got back online today at 7:21 AM today.  And, CO-PDH.ELR-SECONDARY was back online yesterday at 3:16 AM.  I am closing this ticket.   Notice, CDC was cleaning up their security connections.  Some of STLT may get dropped from the whitelist.  It is good to go, now.  I am closing the ticket.
