### ISSUE TITLE
bug: In the UP, a report that has been routed but not translated has a status of "NOT DELIVERED" when it should be "RECEIVED"

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#9378]
### User Story
As as user, I would like the submission API to always return the correct status.

### Description/Use Case
There is an edge case in the submission API where if a report has had the route step run but not the translate step, the API will return "NOT DELIVERING" even if ultimately items do make it to a receiver. 

### Risks/Impacts/Considerations
- This is a relatively small edge case that would likely only ever be seen if the system was under a lot of load and would fix itself as soon as the translate step is run.

### Dev Notes
- Adding a timeout can help to reliably recreate this issue
  -  Add `runBlocking { delay(10000) }` to `doWork` in FHIRTranslator.kt
- The code will likely need to be changed to refactor [this](https://github.com/CDCgov/prime-reportstream/blob/64d4044e7afd82e713e51b61cd49f7465609bd4d/prime-router/src/main/kotlin/history/SubmissionHistory.kt#L361) or to adjust how the filter logs get written to the db
  - Of note, a filter log is not written for a jurisdictional filter

[This](https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/8451) is some previous work that was done that helped discover this bug.

### Acceptance Criteria
- [ ] The status for a report that will be routed to receivers after the route step has run but before translate is "RECEIVED"

**Comment by luis-pabon-tf** [comment]
When demoing this ticket, submitting [this body](https://app.zenhub.com/files/304423150/84a00019-2191-4dbc-be90-f3d868fe773b/download) and then immediately checking the Submission History showed the `Not Received` value still appearing. Checking why this happened.
