### ISSUE TITLE
CA - Update Filters to block negative antigen results

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#9380]
California - theodora.fries@cdph.ca.gov

## Problem statement

The state of California is interested in a back-end change to how we receive covid results from SimpleReport.

## What you need to know

Specifically, we would no longer like to receive any negative antigen test results. We still want to receive positive antigen results, and both positive and negative PCR results.

**Comment by LaFreda1** [comment]
Hey @cloudmagic80. We just met with California on this ticket...I am hoping to have this completed by the end of this sprint. Thoughts? @brick-green has insight on what's needed. Let me know

**Comment by cloudmagic80** [comment]
@LaFreda1  I will take a look.

**Comment by oslynn** [comment]
@cloudmagic80 I have quality filter (filterOutNegativeTestType) implemented just for this use case.  The code implementation is in: prime-router/src/main/kotlin/ReportStreamFilterDefinition.kt line 148-181.  Please look at co-phd.elr setting.  And, you should use the existing filter for this ticket.  I am posting it here to let other member see it also.  Add the following quality filter to ca-phd.elr:

qualityFilter: [ "filterOutNegativeAntigenTestType(test_result, 260385009, 260415000, 895231008)" ]

**Comment by cloudmagic80** [comment]
https://github.com/CDCgov/prime-reportstream/pull/9527/files

Pull request created
cc @LaFreda1
