### ISSUE TITLE
WA Notify integration with SimpleReport to end on 5/11

### ISSUE THREAD

**Issue by OHoward2023** [CDCgov/prime-reportstream#9382]
## Problem statement

We are planning for May 10 to be the final day for verification code issuance after which the SimpleReport API verification code issuance key will be disabled.

## What you need to know

We sincerely appreciate your collaboration on this project to integrate WA Notify code issuance with SimpleReport. Since implementing in March 2022, nearly 20,000 verification codes have been issued for positive COVID-19 results reported through SimpleReport. This allowed WA Notify users who tested positive to more quickly notify others they may have exposed.

Original Email Communication:
Hawes, Richard (CDC/DDPHSS/OD)

Thanks for the heads up. I'm forwarding this request to the ReportStream support email address to schedule the configuration change needed. 

BTW: I've taken another job at CDC, so please use the support email address in the future for RS requests. 

-- Rick

United States Digital Service at CDC
rhawes@cdc.gov

From: Higgins, Amanda L (DOH) <Amanda.Higgins@doh.wa.gov>
Sent: Tuesday, May 2, 2023 3:02 PM
To: Hawes, Richard (CDC/DDPHSS/OD) <qom6@cdc.gov>

Subject: WA Notify integration with SimpleReport to end on 5/11
 
Hi Rick,

I hope you are doing well. I am reaching out to let you know that COVID-19 exposure notifications through WA Notify will sunset on May 11 in tandem with the end of the public health emergency order. We are planning for May 10 to be the final day for verification code issuance, after which the SimpleReport API verification code issuance key will be disabled.

To avoid unnecessary requests and errors, please remove the code issuance process from the SimpleReport reporting system at the start of business on May 11. Once it is removed, please let us know and we will disable the SimpleReport API key in the ENCV platform.

We sincerely appreciate your collaboration on this project to integrate WA Notify code issuance with SimpleReport. Since implementing in March 2022, nearly 20,000 verification codes have been issued for positive COVID-19 results reported through SimpleReport. This allowed WA Notify users who tested positive to more quickly notify others they may have exposed.

Please let me know if you have any questions, and thank you for your partnership.

Best regards,

Amanda Higgins, MSHI
Pronouns: She/Her
WA Notify Epidemiologist
Office of Innovation and Technology
Washington State Department of Health

## Acceptance criteria

Once it is removed, please let us know and we will disable the SimpleReport API key in the ENCV platform.

## To do

- Please remove the code issuance process from the SimpleReport reporting system at the start of business on May 11.

**Comment by RickHawesUSDS** [comment]
FYI... The generic name for WANotify is Google/Apple Exposure Notification (GAEN). The setting that governs this data flow is: wa-phd.gaen. Suggest that a change in the setting is used to disable this flow.

**Comment by adegolier** [comment]
Remove transport and set filter to allowNone()

**Comment by sliu1000** [comment]
@adegolier Hi Angela, any update on the status for this? Amanda from WA state is asking for an update.

Best regards,

Sharon

**Comment by sliu1000** [comment]
@RickHawesUSDS Can you please advise @adegolier where exactly this exposure notification should be disabled at is that somewhere in azure?

**Comment by adegolier** [comment]
wa-phd.gaen has been updated to remove the transport and change the filter to allowNone(), effectively shutting it off.

**Comment by sliu1000** [comment]
WA confirmed that no verification codes have been issued.  Please see below communication:
Hi Angela,

I can confirm that no verification codes have been issued through the SimpleReport API today. We will disable the API key in the ENCV platform by EOD. 

Thank you for your assistance with this configuration change. 

Best,

Amanda Higgins, MSHI
