### ISSUE TITLE
API Endpoint: Fetch all providers, facilities and senders for an organizations delivered reports

### ISSUE THREAD

**Issue by luis-pabon-tf** [CDCgov/prime-reportstream#9397]
### User Story

As an organization receiving reports via ReportStream, I want to be able to see a top-level view of all providers, facilities and senders related to my received reports.

### Description/Use Case
The new endpoint will be used to power the mockup [here](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=2369-27610&scaling=min-zoom&page-id=2369%3A26962&starting-point-node-id=2369%3A26965)

### Risks/Impacts/Considerations
Open question: What is facility type in the metadata?
 - This might map to `ordering_provider_name` and `ordering_facility_name`

### Dev Notes
- The number of test results won't be be consumed on the mockup above, but will be needed for a very similar view that will include that data

### Acceptance Criteria
- [x] An endpoint exists at `/api/v1/organizations/{organization}/deliveries/submitters` and should include
  - [x] id
  - [x] Name
  - [ ] Location
  - [x] Facility type
  - [x] Most recent report date
  - [x] Number of test results
- [x] The new endpoint supports Date filters, sorting, pagination

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9397?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimmyfagan @mkalish @thetaurean @TurkeyFried @victor-chaparro
