### ISSUE TITLE
Create utilities for handling common search requests

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#9404]
### User Story
As a client of the report stream API,  I would like a consistent format for applying common parameters

### Description/Use Case
As more endpoints get exposed with similar functionality, such as pagination, sorting and filtering the API should provide a consistent format that these parameters can get applied to all endpoints

### Dev Notes
- Some common functionality that could be consolidated
  - Handling requesting different pages
  - Consistent handling of sort direction
- These class should be parseable from query parameters in a URL or a request body
- Implementer could look to see if there are any kotlin/java libraries that could be used to make this work easier
 
Some potential pseudo code
```kotlin
enum SortDirection {
  ASC,
  DESC
}

class SortParameter<T>(sortProperty: T, sortDirection: SortDirection)
class Pagination(page: int, pageSize: int)
class Filter<T, F extends FilterProperty>(value: T, property: F)

class SearchRequest(sorts: List<SearchParameter>, pagination: Pagination, filters: List<Filter>)
``` 

### Acceptance Criteria
- [x] A re-usable abstract class exists that can be extended that handles common functionality around pagination, sorting and filtering

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9404?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @mkalish @thetaurean @victor-chaparro
