### ISSUE TITLE
Update the content in the PDF Version of the API Programmer's Guide

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9423]
## Problem statement

Some content has been updated in the Web Version of the API Programmer's Guide to include guidance to the File Validator tool and the Public Key tool. To ensure both the PDF and the Web Version are in alignment at launch, we need to update the PDF version to match the content updates in the Web version.

## What you need to know
- [Existing Guide](https://reportstream.cdc.gov/resources/programmers-guide)
- ...

## Acceptance criteria

- [x] Content/Guidance found in the latest version of the Web Version of the API Programmer's Guide matches that of the PDF version
- [x] The PDF version is up-leveled and saved as a new PDF document
- [x] The updated PDF file is linked in the engineering ticket #9424

## To do

- [ ] ...

**Comment by audreykwr** [comment]
[New doc](https://docs.google.com/document/d/1VG15KdjjpCJFuGU9Tdk0q7ESp-cVqV7v/edit?usp=sharing&ouid=105539281535064771922&rtpof=true&sd=true)

**Comment by audreykwr** [comment]
Approved. [new PDF here](https://drive.google.com/file/d/1flwlixIO_ogr29Nk5BcXsRYKzF-JhR3v/view?usp=sharing)

**Comment by audreykwr** [comment]
Linked the pdf in 9424. Closing. @chris-kuryak
