### ISSUE TITLE
Plan minor page updates

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#9430]
## User story

As a user, I want / need content that is easy to understand, so that I can do my job.

## Background & context

The initial audit in Q1 IDed minor updates for readability and consistency throughout the site. This ticket is to review those audit notes and plan which updates can be made for minor improvements this quarter.

## Open questions

- How many pages will be in scope to update this quarter based on level of edit needed

## Acceptance criteria
-   [ ] Review audit notes and list pages for updates
-   [ ] Create follow up tickets as needed

**Comment by chris-kuryak** [comment]
No longer needed based on new site update plans
