### ISSUE TITLE
New Zenhub ticket template

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#9434]
## Problem statement

Zenhub ticket templates will be the start of our new governance process

## What you need to know

[Governance doc](https://docs.google.com/document/d/1__FE0OGlVAby0m7QyKfo_Qr0Gh_PvALaA1_DeCJSjzQ/edit#heading=h.qyvn837dl01t)

**template name**: Content request

### Ticket template content:

_[Governance document](https://docs.google.com/document/d/1__FE0OGlVAby0m7QyKfo_Qr0Gh_PvALaA1_DeCJSjzQ/edit#heading=h.qyvn837dl01t) for content process reference_

**Is this new content or an edit to current content?**

- [ ] **Edit**: It is not a change that affects the design or functionality of the page/feature.
- [ ] **New**: It is something new that is mostly content (not a tool).

**Questions for edit requests:**

1. Current page link:

2. Change requested:

3. Why is this change needed?

4. How urgent is this change and why?

**Questions for new content requests:**

1. Explanation:
2. Status of content: 
- [ ] Idea
- [ ] Initial draft (rough ideas started)
- [ ] Final draft (fairly confident in the content you have for this)
3. What identified audience need does this content help meet? (See the [user task dashboard ](https://lookerstudio.google.com/u/0/reporting/921e245e-7d5c-4bec-b997-4e1d1f39cdd7/page/JYdKD)for verified needs)
4. What OKR (quarterly or annual) does this help meet? How? 
5. Have you considered if existing content already meets these needs, or could with some modification? 

**Complete your request by:**

- [ ] Making sure you’ve answered all questions for the appropriate request type (edit or new)
- [ ] Labeling this ticket as `content request`, `design` and `experience`
- [ ] Assigning this ticket to @audreykwr

_Thank you for contributing to content excellence for ReportStream!_

## Acceptance criteria

- [x] Review template with Audrey to check content and format

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@chris-kuryak per our conversation about new templates

**Comment by chris-kuryak** [comment]
@audreykwr Should this be part of the Content Governance epic?

**Comment by audreykwr** [comment]
Yes! Done

**Comment by audreykwr** [comment]
thanks @chris-kuryak! I realized that we don't have a content request label and that it's not worth making one right now, so let's just make the instructions say "content" label instead of "content request"

**Comment by chris-kuryak** [comment]
@audreykwr I made a `content request` label. Those are easy and don't require PRs.

So I think we are good now?

**Comment by chris-kuryak** [comment]
Closing per @audreykwr approval from Slack.
