### ISSUE TITLE
Write a custom FHIR path function that validates NPI

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#9437]
### User Story

As ReportStream, I need to validate NPI data is valid.

### Description/Use Case
Currently the covid pipeline validates NPIs and if it's valid, additional context is added to the HL7 v2 message. The UP is only checking if the NPI is not empty to add the additional context.

### Risks/Impacts/Considerations
- Invalid NPI can be sent to receivers if it isn't validated.

### Dev Notes
A custom FHIR path function can be written and used as part sender transforms to include the additional context.
`NPIUtilities.kt` contains the logic needed to implement this function.

### Acceptance Criteria

- [ ] ReportStream validates NPIs

**Comment by bishoyayoub** [comment]
@victor-chaparro Should we still pursue this effort?

**Comment by victor-chaparro** [comment]
I think we should if we need to support the Covid pipeline features in the UP. Do you think we need to research what it would take to validate NPI against a FHIR server?

**Comment by arnejduranovic** [comment]
@victor-chaparro This ticket seems to be part of the greater validation effort, no? My vote is to icebox this ticket (since it includes a solution) and consider this problem later when we implement validation. Thoughts?

**Comment by LaFreda1** [comment]
@arnejduranovic Is this work still required?

**Comment by arnejduranovic** [comment]
This remains to be seen, we don't have any hard requirements for this as of yet.
