### ISSUE TITLE
Create ReportStream one-pager draft design

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#9440]
## User story

As a ReportStream representative, I need a one-pager so that I can distribute information to external stakeholders with clear ReportStream branding. This one-pager should be a “sell-sheet” that explains what we do, why senders and receivers should onboard, and how they can do so.

## Background & context

The ReportStream team would benefit from a concise and branded one-pager to distribute at external events. 

## Open questions

-   What are the design and customization limitations of MS Word/Google Slides?
-   What is the content? Where is it coming from?
-   Suggested collaborators: Glenn, Audrey

## Working links
-   [Outline](https://docs.google.com/document/d/1xPdLj5Kb1CFXLz-6vNCKU0h_TFG33LSkoLC8fapahj8/edit#)
-   [Original thread with need](https://nava.slack.com/archives/C051JAPND96/p1683571615880449)

## Acceptance criteria

-   [x] One-pager design uses CDC/ReportStream branded visual language
-   [x] Draft one-pager design created in a shared workspace
-   [x] Reviewed by USDS stakeholders
-   [x] Reviewed by design team (content and Engagement specifically) 
-   [ ] Reviewed by client-facing stakeholders

**Comment by jillian-hammer** [comment]
For your review @lizzieamanning! Thought it made sense to break these into separate tickets and identify both as being drafts.

**Comment by lizzieamanning** [comment]
@jillian-hammer made some updates and added my outline link. Suggested some collaborators too!

**Comment by jillian-hammer** [comment]
Status: on track, finalization blocked by #9470

**Comment by jillian-hammer** [comment]
Status: Reviewing with stakeholders (USDS-ers) today 5/26

**Comment by jillian-hammer** [comment]
Reviewed with USDS stakeholders. Approved to move forward with finalizing #9561!
