### ISSUE TITLE
Develop Plan for Setting up New Okta Instance

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9441]
## Problem statement
Having recently finished a round of research and exploration as to how the existing Okta instance is used, we need to develop a plan for what needs to be changed/updated in our new Okta instance to prepare for a migration of users.

## What you need to know
- [Okta Research Notes](https://docs.google.com/document/d/1lPCVpzU9tqdESWxOyU9KqxOr-Tlax0SVe7u79bTYz2g/edit#heading=h.5d3xmmoa5n8j)
- [Okta Process Mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1681921545021/4b0bdcdfb84b03a3a7b0a90741c9dab5c1e3abd6?sender=u788ba8e0ebf56a2ad7d18905)
- ...

## Acceptance criteria
- [ ] Create staging environment to test a migration of an account from old Okta to new Okta
- [ ] Migrate Chris from Old Okta to new Okta synchronously and determine anything that may need to be fixed/changed (invite Andrey)
- [ ] Determine any size, format, etc requirements for branding on the new Okta instance
- [ ] (together with Product) Develop a plan (within or linked within [Okta Research Notes](https://docs.google.com/document/d/1lPCVpzU9tqdESWxOyU9KqxOr-Tlax0SVe7u79bTYz2g/edit#heading=h.5d3xmmoa5n8j)) that outlines all of the tasks needed to set up the new Okta instance so we are ready for migration of users from old instance to new instance. It should include the following at minimum:
  - [ ] Design needs (noted in the document)
  - [ ] Content needs (noted in the document)
  - [ ] Engineering needs (noted in the document)
  - [ ] Ability for a user to reset their own password

## To do
- [ ] Sync with Chris Kuryak on the needs/scope of this document

**Comment by jpandersen87** [comment]
- [ ] One of trial environments pointed towards new okta
- [ ] Okta Customization options documented
- [ ] Successful user migration test

**Comment by Andrey-Glazkv** [comment]
@jpandersen87 hey, Joseph, just wanted to double check if the number of points (2) was accurate
