### ISSUE TITLE
Lab Information Updates through ReportStream

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#9444]
## **Problem Statement**

We received an email from Kenny McNeil <qmm0@cdc.gov>, Consultant to CDC DCIPHER Program, regarding what occurs when labs submit new or changed information.

## **What you need to know**

Initial inquiry email:

> I have a quick question for the lab team. Is the lab information ever updated or changed that we should ever expected updated or corrected information come through our connection?

Follow-up for clarification:

> Thank you for contacting the ReportStream Support team.
> 
> We appreciate your inquiry and would like to assist with any information you need. Could you please provide me with some examples of what kinds of lab information you are referring to? (e.g. CLIA number, facility name, Ordering Provider/NPI, etc.)

Confirmation of inquiry:

> Sure! I was inquiring about any of the data provided. If we should ever expect any values to go from null to populated or change, such as facility name, ordering provider or even any results.

## **Acceptance Criteria**

Establish a document/statement detailing what happens when new or changed lab information is submitted and when this can occur.

## **To Do**

- [ ] Determine what, if any, notifications or indicators are present when new or changed lab information is submitted
- [ ] Create a standardized response to provide to ReportStream users who may ask about this
- [ ] Provide details to the ReportStream Support team to address the current inquiry from Kenny

## **Additional Comments**

The requester, Kenny McNeil, is part of the National Center for Emerging and Zoonotic Infectious Diseases (NCEZID) via Booz Allen Hamilton.

**Comment by adegolier** [comment]
I'm... not sure I really understand this question? We pass on the info we're given...

**Comment by LaFreda1** [comment]
@wcollin89 please confirm what the need is for this ticket or if we can close it. Thanks!

**Comment by sliu1000** [comment]
@adegolier @GilmoreA6 I believe the user just wants confirmation when a lab name is changed or corrected it won't affect their system.  But I don't believe our Reportstream settings have a static Lab Name, city, etc. field where DCipher would need to be notified of that change.

**Comment by LaFreda1** [comment]
Sharon to respond to email. Closing
