### ISSUE TITLE
Investigate how tests could be written against a real database

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#9455]
### User Story
As a report stream platform developer, I would like to write tests that interact with the database

### Description/Use Case
The work captures investigating how tests could get written that interact with a database without needing to write a smoke test.   An example use case is testing a set of functionality that relies on sorting being performed in the database.

### Dev Notes
- This ticket is to just come up with some possible solutions for this rather than actually implementing
- One potential option would be creating a postgres schema for each test run
- There might be some kotlin libraries that solve this too

### Acceptance Criteria
- [x] a proposal exists that documents how to write tests using the database would work

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9455?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @luis-pabon-tf @mkalish @thetaurean

**Comment by bishoyayoub** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9455?planning-poker) with Zenhub @thetaurean
