### ISSUE TITLE
[CDPHE ELR Prod] Error: Cannot Write Message to DB

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#9456]
## Problem statement

This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the message into the database due to the following reason:
**************************************************
The conversion of a varchar data type to a smalldatetime data type resulted in an out-of-range value.

## What you need to know

Common causes for the failure to write a message to the database include the following:
 - The message contained an end-of-line character in the middle of the record.
 - The message contained a value that was incompatible with the field's datatype (e.g., an invalid date or a string where there should be a date).

Message ID: 1682640000_1312+2+20230429
Received by: CDPHE ELR Prod
Received on: 2023-04-29 13:30:26
File source: CDC PRIME
File name: covid-19-a4b33018-fd48-41af-bb0f-55ab35d196b7-20230429193027.hl7
Performing Org Name: CMHH Pueblo

## To do

Please review, correct, and resubmit the message.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by jalbinson** [comment]
@oslynn has already taken care of this issue.
