### ISSUE TITLE
Engagement team needs the PHE form results to be produce on a RS template

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#9458]
## Problem statement

We recently polled STLTs and COVID data senders on their responses to the public health emergency ending on May 11, 2023. We need to input the results into a RS template.

## What you need to know

Sharon and customer support team has the link to the output of the data. 

## Acceptance criteria

- [ ] Polished version of the data 

## To do

- [x] Input the data into a RS template
- [x] Share with LaFreda

**Comment by sliu1000** [comment]
@jakefishbein-navapbc @LaFreda1 Hello, here's the link to the data: https://app.smartsheetgov.com/sheets/xG9g6X3vg34GwchvFH2jrhjW65ff64rRjfqfMCv1?view=grid&filterId=1543982024025988

Also, here's the dashboard: https://app.smartsheetgov.com/dashboards/5prQ2pfv22Jr387xp5pXQFPFJ97G4xrVHHhCMCw1

**Comment by jakefishbein-navapbc** [comment]
@sliu1000 I don't have permission to access the dashboard. Can you add me?

**Comment by sliu1000** [comment]
@jakefishbein-navapbc Are you using your cdc email? You should be able to access it.

**Comment by jakefishbein-navapbc** [comment]
@LaFreda1 @sliu1000 [Here is the survey deck](https://docs.google.com/presentation/d/1uGnSRo1qjDuuwqrYkuZBU_4h5ANcA56hfsAXEjsFIlI/edit?usp=sharing). please review for accuracy.
