### ISSUE TITLE
Fix position of active link underline in RS website navigation

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#9459]
## Describe the bug
Upon clicking a link in the main nav, the underline style position transforms from being above the line rule to below the line rule. The underline should remain above the line rule in its active link state.

## Impact on ReportStream
Creates visual inconsistency on our public-facing website.

## Steps to reproduce
1. Go to 'reportstream.cdc.gov'
2. Click on any of the top-level pages ('Product' 'Resources' 'Support')
3. See the inconsistent position of the active link underline

## Expected behavior
The link underline should remain above the nav's horizontal line rule.

## Resources
Current behavior ('Support' is the active link, 'Daily Data' is in hover state: 
![image.png](https://images.zenhubusercontent.com/639236212968fbce989b5d65/1a563fe3-fa16-46ba-bbe2-dbc787ed158c)

## Logs
N/A
#### Desktop
 - OS: iOS 12.5 (Monterey) 
 - Browser: Google Chrome
 - Version: Version 112.0.5615.137

## Additional context
N/A

**Comment by jillian-hammer** [comment]
@chris-kuryak can you take a look at this as a candidate for this sprint?

**Comment by jpandersen87** [comment]
Should this be closed due to replacement? @chris-kuryak

**Comment by chris-kuryak** [comment]
@etanb @jillian-hammer is this captured in the Nav Bar update/redesign?

**Comment by jillian-hammer** [comment]
nice catch @jpandersen87, yes @chris-kuryak this can be deprecated! will be fixed with @etanb's new nav bar 😄

**Comment by chris-kuryak** [comment]
Hooray!
Closing as it is being fixed in the Nav bar update/redesign #10709 closing soon.
