### ISSUE TITLE
Design: Standardize styling for a table variant

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#9460]
## User story

As a ReportStream designer/engineer, I need our tables to be standardized, so that we can reduce the amount of technical & design debt and present our tables with visual consistency across the website. 

## Background & context

This work is part of the custom table component MVP. The custom component will also allow for customized future features that will not only meet our users needs, but also standardize tables across our website and make implementing new tables more efficient.

As part of this work, there are three variants of tables, this work covers the first one. 

## Open questions

-   Will the standardized style(s) still provide enough flexibility in meeting the needs of tabular data across our site?
-   How should we handle text fields with long strings?

## Working links
-   [Table Design Discovery Mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1677789052306/05f1e11a2448c3349735fe808833da01c6c0283b?sender=u0c3cdba5126734aceb613229)

## Acceptance criteria

-   [ ] Design spec document created for the Bordered table style

**Comment by yudonoodles** [comment]
Just want to make sure that I understand what the AC correctly, not sure what a "complex" table is, there is only three types I see on the linked [mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1677789052306/05f1e11a2448c3349735fe808833da01c6c0283b?sender=u0c3cdba5126734aceb613229) - borderless, bordered and striped. I spoke with @jillian-hammer about this and she asked me to sync with @etanb, which I did and he wasn't sure what that's referring to either. 

Can I go ahead and update the ticket to "striped" instead of complex @jillian-hammer?

**Comment by jillian-hammer** [comment]
@yudonoodles my bad, typo – you're right, I meant striped!

**Comment by yudonoodles** [comment]
**Need alignment on what specs we want defined for the three tables @jillian-hammer** 
- Color values 
- Font and font-weight definition 
- Sticky header across three types
- Sorting across across three types

**Unsure about:**
Based on what's in the mural "Table Component Layers Priority"Screenshot 2023-06-02 at 3.14.01 PM.png](https://images.zenhubusercontent.com/6435ca831530a05687c6a34a/a47348db-360b-4f86-a443-bcfc9f6d0816), are we also looking to add a feature to the table where it can:
- Expand/Collapse on click to reveal secondary data? This currently is not being offered by USWDS table component. What's the specific use case for this? Where would we need this? 
- As we are standardizing tables, we should standardize the font and weight used in them. I noticed that we are using Roboto for the STLT table and Last Mile Failure and a few more but Public sans on others. I don't see Roboto being used anywhere else. 

**Approach to creating the spec:** Overall, my thought is we need to use the existing framework that USWDS-Trussworks is providing for tables, and we make few tweaks to fit our needs, so I will start with their designs and add definition over it.

**Comment by jillian-hammer** [comment]
thank you for these notes @yudonoodles !!

**Spec alignment**
Yes, we are aligned! I think the only things that are missing from that list are:
- Style of line rules (color, thickness)
- Padding specs 
- Type alignment specs 

do you need any other add'l detail or examples of what that looks like?

**Unsure about**

- Expand/collapse: We have previously discussed it as a method to deal with super duper long text fields (ex. the [Data models](https://pdhstagingpublictrial03.z13.web.core.windows.net/resources/api/documentation/data-model#patient-data-elements) in the Programmer's Guide, or [file names in the message tracker](https://images.zenhubusercontent.com/304423150/9310266b-0466-482c-b91a-b458958a6031/table_scroll_052423.mp4).) However, since it would require additional custom code, we decided to hold on pursuing it until after we've validated if it's a real need or not.
- Typeface standardization: We use Roboto's monospaced form because it makes improves the legibility of data across table rows for quicker comparison & scanning, particularly for things like dates, times, categories, and Report IDs (UUID strings). It appears throughout the Admin Tools section. I think improving the reading ux is a strong reason to keep both typefaces. However, I think we can and should make rules to around when it's used. (Ex, "Roboto Mono is always used for dates. Public Sans is always used for facility names.") how does that level of standardization sound?

**Approach**
- Yes, that sounds good to me. the current table designs are already based on the USWDS/trussworks tables, so I think starting from what we have make sense! it's not starting the design from scratch, moreso just cleaning up and standardizing all the details. 

feel free to keep replying in the thread if anything is unclear or if you have add'l thoughts.

**Comment by jillian-hammer** [comment]
added the link to the [Figma workspace](https://www.figma.com/file/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?type=design&node-id=4875%3A37085&t=rFId8M1WlgIp3NiJ-1) with the current 3 styles to the ticket! @yudonoodles

**Comment by yudonoodles** [comment]
On track to completing. 
06/06 Reviewed the progress of work with @jillian-hammer on Bordered table component and associated specifications. 
For reference, on Figma, I created a flexible table cell component and that will support future design work where we design modularly, plugging in content and adjusting the styling as needed without having to manage different table frames. That way we design, _as a verb_, and create designs, _as a noun,_ in a consistent and reliable way.
