### ISSUE TITLE
Set up default filters for the ETOR topic

### ISSUE THREAD

**Issue by jimmyfagan** [CDCgov/prime-reportstream#9464]
### User Story
As an ETOR organization, I want to have reasonable default filters defined in the code so that I will be able to filter out obviously undesirable data without needing to define my own filters.

### Description/Use Case
In the UP, for full-elr, we have default filters that can be used when an organization doesn't define their own.

Those defaults are as follows:
<details>
  <summary>Quality Filter</summary>
  
  ```kotlin
    /**
     * Default Rules:
     *   Must have message ID, patient last name, patient first name, DOB, specimen type
     *   At least one of patient street, patient zip code, patient phone number, patient email
     *   At least one of order test date, specimen collection date/time, test result date
     */
    val qualityFilterDefault: ReportStreamFilter = listOf(
        "%messageId.exists()",
        "%patient.name.family.exists()",
        "%patient.name.given.count() > 0",
        "%patient.birthDate.exists()",
        "%specimen.type.exists()",
        "(%patient.address.line.exists() or " +
            "%patient.address.postalCode.exists() or " +
            "%patient.telecom.exists())",
        "(" +
            "(%specimen.collection.collectedPeriod.exists() or " +
            "%specimen.collection.collected.exists()" +
            ") or " +
            "%serviceRequest.occurrence.exists() or " +
            "%observation.effective.exists())"
    )
  ```
</details>

<details>
  <summary>Processing Mode Filter</summary>
  
  ```kotlin
    /**
     * Default Rule:
     *  Must have a processing mode id of 'P'
     */
    val processingModeFilterDefault: ReportStreamFilter = listOf(
        "%processingId.exists() and %processingId = 'P'"
    )
  ```
</details>

With the introduction of the `etor` topic in #8592, we have an opportunity to introduce default filter behavior for a topic other than `full-elr`, and since `etor` is a very different use case than `full-elr`, the default filters may look different.

This story will involve determining a reasonable default quality filter for the `etor` topic (perhaps just verifying the message type as a starting point, but maybe doing some research or collaboration with Flexion to decide with more detail). The processing mode filter can use the existing default for `full-elr` most likely. This story should also cover the code that determines default behavior based on topic values.

### Risks/Impacts/Considerations

Any existing documentation about filters and especially default filters should be updated.

### Acceptance Criteria

- [x] A new default quality filter for `etor` is added
- [x] The `etor` default filter doesn't affect `full-elr` receivers
- [x] The Default quality filter to use is determined by the receiver/sender topic. This should work for other filters as well.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9464?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimmyfagan @luis-pabon-tf @mkalish @victor-chaparro
