### ISSUE TITLE
NJ - Files sent/recieved

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#9469]
## Problem statement

[Write a short description of what you want to achieve with this task]

NJ has sent some files over

![image.png](https://images.zenhubusercontent.com/62828ac9597e3bae41382df7/e2c90258-f658-492f-81cc-dd9c2714a22c)

![image.png](https://images.zenhubusercontent.com/62828ac9597e3bae41382df7/b3f03251-6847-48eb-9e9b-adc6651bf474)
## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by oslynn** [comment]
Confirmed with NJ this is only notification email to let ReportStream Know those files had been received by MOVEIT cloud server.

Hi Ott,

 

Thank you for your question.  Yes, the email from MOVEit is a confirmation of what was submitted.

 

Respectfully,

Joyce

Joyce Boyd-Lee, MPH

CDRSS Health Data Specialist | Epidemiology, Environmental & Occupational Health

Email: Joyce.Boyd-Lee@doh.nj.gov

I am closing this ticket.
