### ISSUE TITLE
Design: One-pager content development 

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#9470]
## User story

As a prospective ReportStream partner, I need to understand ReportStream's offerings in a concise sell sheet format, so I can make an informed decision to partner with ReportStream and/or share back with my organization.

## Background & context

This is the sister content ticket of Create ReportStream one-pager draft design #9440. This ticket captures the work of content development for the sell sheet: creating a content outline, draft content, and circulating for review throughout the development process. 

## Open questions

-   What metrics would we like to capture in this sell sheet and how can we get the answers?
-   Is it possible for design to begin to evaluate and quantify what it takes to get onboarded to RS (it’s free, but what time/money investment is needed for onboarding + maintenance?)

## Working links
-  Resource: [Secondary branch research](https://docs.google.com/document/d/1NQIvplbhgmZWUhOzuoe2TFtumKLjV0ePQ5nznlBlTuQ/edit)
-  [Outline word document](https://docs.google.com/document/d/1xPdLj5Kb1CFXLz-6vNCKU0h_TFG33LSkoLC8fapahj8/edit?usp=sharing)
-  [One pager design sandbox doc](https://docs.google.com/document/d/18d5hHvzezKO1cdrSo0iOnt1Yiz4KqFKlGmJelUloUog/edit?usp=sharing)

##  Next steps

-   [x] Design meet with content strategist to brief
-   [x] Design take first pass at outlining sell sheet content
-   [ ] Review with cross team members (particularly Content and Engagement team) and revise per feedback

## Acceptance criteria

-   [x] Draft one-pager content created for review
-   [ ] Reviewed in public channel and/or All Teams Sync, with direct feedback ask from Engagement team
-   [ ] Reviewed by client-facing stakeholders

**Comment by jillian-hammer** [comment]
hi @lizzieamanning and @audreykwr, tagging you here for awareness! audrey, we decided to split the content work into a separate ticket from the design work. see the next steps outlined above and lmk if you have thoughts.

**Comment by jillian-hammer** [comment]
hi @chris-kuryak, letting you know I broke the one-pager development into separate tickets (design #9440 and content #9470, this ticket is the latter).

I gave it 5pts due to the review dependencies. this work will begin this sprint and can go into Sprint Backlog, if ok by you. thank you!

**Comment by chris-kuryak** [comment]
Thanks @jillian-hammer as this is a content task, will this be taken up by Audrey?

**Comment by jillian-hammer** [comment]
since Audrey's plate is pretty full, Lizzie and I will work on the draft outline & content and involve Audrey as a reviewer. I imagine she will be more heavily involved during the content finalization period, but that will be a separate ticket. @chris-kuryak

**Comment by Andrey-Glazkv** [comment]
Hey @jillian-hammer nice work on splitting the ticket! Do we need to move design #9440 into Backlog or In Progress?

**Comment by jillian-hammer** [comment]
@Andrey-Glazkv thanks! I believe #9440 is already in the Sprint Backlog. it's not ready to be moved into In Progress yet.

**Comment by jillian-hammer** [comment]
Status: on track, collecting feedback from engagement team

**Comment by audreykwr** [comment]
On track alongside overlapping messaging work

**Comment by jillian-hammer** [comment]
status: in review with design team + lead

**Comment by Andrey-Glazkv** [comment]
Need to be approved by Mo

**Comment by jillian-hammer** [comment]
Closing, @audreykwr incorporated Mo's comments into the [WIP one pager document](https://docs.google.com/document/d/1QmT738BUwR-WuPcsoGtXLoqxngtN4wIPFSRHeHEhKEY/edit?usp=sharing). thanks audrey!
