### ISSUE TITLE
Update table on the STLT Report Details page

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-reportstream#9474]
## Problem statement

As part of the STLT experience, we need to implement the design of the table on the report details page. This implementation is strictly visual, and we'll have a separate ticket for hooking it up to the API afterward.

## What you need to know
![Screenshot 2023-04-12 at 12.22.18.png](https://images.zenhubusercontent.com/5999b3b38f62dc7798c36942/6ce35d34-c8ae-4c5a-97d5-a9ffc2930f42)

## Acceptance criteria

- [ ] Table should use the new and improved Table component
- [ ] Table should sort on all columns
- [ ] Table should paginate
- [ ] Table should refresh data when filter button is clicked

## To do

- [ ] Update Table to use the new and improved Table component
- [ ] Table should sort on all columns
- [ ] Table should paginate
- [ ] Table should refresh data when filter button is clicked

**Comment by chris-kuryak** [comment]
Awaiting information from Platform team (new API) to update this table with the custom table component.
ETA: 2 sprints away.

**Comment by chris-kuryak** [comment]
No longer needed. Table component already in. Styling will be updated by #10626.
