### ISSUE TITLE
Update the SOP for Updating Release Notes

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9477]
## Problem statement
The [release notes SOP](https://docs.google.com/document/d/1vAiOJlfRMvJPRER3cr9Kr4lQ2-_ybNucJt28kI3fl1I/edit) need to be updated to reflect the current process requirements. This will avoid issues with engineering deployments in the future.

## What you need to know
- [release notes SOP](https://docs.google.com/document/d/1vAiOJlfRMvJPRER3cr9Kr4lQ2-_ybNucJt28kI3fl1I/edit)

## Acceptance criteria
- [ ] Chris, Andrey, and Etan meet and update the Release Notes SOP

**Comment by Andrey-Glazkv** [comment]
Meeting is scheduled - Tuesday 5/30

**Comment by chris-kuryak** [comment]
Met and updated the procedure updated 5/30
