### ISSUE TITLE
Automated daily email

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-reportstream#948]
## Propose

There are currently no notifications about daily data.

Send a daily email to each receiver when there has been new data reported in the last 24 hours

## To do

- [ ] Every 24 hours, check to see if data has been reported for each receiver
- [ ] If new data exists, trigger email to send each receiver every 24 hours
- [ ] Write email content. Will include:
  - Link to download
  - Total tests
  - Total facilities (Maybe stretch goal? Dependent on being able to read HL7)

**Comment by jlusds** [comment]
Current:
There are no notifications about the data

Propose:
Sending a daily email when there was new data in the last 24 hours 
Send a weekly email that calls out data that hasn't been downloaded over the last 7 days

Requirements
-Setting up sendgrid
-Email content + logic
-Ability to opt out (do we want this)

**Comment by jlusds** [comment]
@drew-usds @mry-usds thoughts on the scope of this?

**Comment by drew-usds** [comment]
Just added updates to this in PR #1434

Template screengrab for reference:
<img src="https://user-images.githubusercontent.com/57154955/123744357-a6263c00-d87c-11eb-9077-cfb2f8de7d44.png" width="50%" />

**Comment by jlusds** [comment]
@BerniXiongA6  provided updates on this thread: https://app.zenhub.com/files/304423150/bb083dd8-cf19-448f-9bb5-d71af5064c08/download


Looking at this again, I realize that some public health departments may not get this email everyday - for example, if there are a smaller public health department and testing is not done

1) We send an email when there is no data to let them know there is no data
2) We rename this from 'Daily email' to something else

My recommendation is #1, and if so we need content for a zero state. We should also update the subject line for the zero state, so people can archive without opening if they want
