### ISSUE TITLE
Universal Pipeline Deidentification HL7v2 RadxMars ELR Spec

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#9480]
### User Story
As ReportStream, I need to be able to deidentify messages of PHI/PII before sending to certain jurisdictions, like the CDC.

### Description/Use Case

The DEX project has a [table of values](https://cdc.sharepoint.com/:w:/r/teams/CDC-Data-Exchange/_layouts/15/Doc.aspx?sourcedoc=%7B32A7AB40-62EA-4339-ADFE-0F2D6DB9C1A5%7D&file=Lab%20and%20Case%20Redacted%20Fields.docx&action=default&mobileredirect=true&cid=3f83b8c0-8f15-4004-aede-3912f7eb3bf2) that need to be redacted, which is based off the HL7v2 ELR spec. We need to look up the HL7v2 RadxMars ELR spec and see if that list matches, and then implement that for the DEX receiver.

### Risks/Impacts/Considerations

We can create a placeholder DEX receiver if one is not already created by the time this ticket is picked up and create a follow on ticket to configure the DEX receiver.

### Dev Notes

We need to design a good way to deidentify messages. My first thought is to use receiver transforms on the FHIR before translation. We may need to expand our transform functionality/strategy to support this. Receivers like the CDC could have these transforms set if they need to receive deidentified data.

### Acceptance Criteria

- [x] Deidentification strategy exists
- [x] Deidentification "configuration" (could be transform) created for DEX that follows the RadxMars ELR spec

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9480?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimmyfagan @mkalish @thetaurean @TurkeyFried @victor-chaparro
