### ISSUE TITLE
Onboarding: Review API programmer's guide 

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#9485]
## Background & context

As part of onboarding, especially as a Webex team member who joined after design and content reworked the API programmer's guide, it is important to review the new material, as it can help orient team members to the process.

## Working links

[Final web content](https://docs.google.com/document/d/1xsxkr7EnnpbXo8CcfdDcUnIYNKuFzY1u/edit#heading=h.b9hyc7d95oq4)
[Figma ](https://www.figma.com/file/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?type=design&node-id=3592%3A36210&t=lYoIzs7EJpVAdoQQ-1)

## Acceptance criteria

- [x]  Skim/review above resources for understanding
- [x] Ask other designers @jillian-hammer @audreykwr any questions that come up

**Comment by lizzieamanning** [comment]
@chris-kuryak in our 1:1 today, @yudonoodles and I discussed tracking this onboarding task as helpful so we make sure it is a priority. Sharing for visibility- lmk if you want to discuss any further or would rather not see this on the board

**Comment by chris-kuryak** [comment]
@lizzieamanning No issue from me in tracking this on the board! 
When pointing these issues, just want to ensure they are pointed similar to other Design team issues with similar time requirements (so we can estimate sprint capacity in the future).
