### ISSUE TITLE
Implement a custom FHIR path function to determine if a test result is for Covid

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#9487]
### User Story
As ReportStream, I want the ability to determine if a test result is for Covid, so that I can find covid results in a FHIR bundle.

### Description/Use Case
We need a way to determine if a test contains Covid results, so that we can correctly map OBX segments for the RADx MARS HL7 v2 format. The RADx MARS HL7 v2 format expects covid results to appear in the first OBX segment.

### Risks/Impacts/Considerations
If there's no functionality available to determine if a result is for Covid. We'd have to check against a hardcoded list containing all the covid loinc codes.

### Dev Notes
To determine if a test result is for Covid we can do a lookup in the livd table using the Observation's loinc code and device information.

### Acceptance Criteria

- [ ] ReportStream can identify which test results in a FHIR bundle are for Covid

**Comment by victor-chaparro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9487?planning-poker) with Zenhub @jack-h-wang @JessicaWNava @TurkeyFried @mkalish

**Comment by victor-chaparro** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9487?planning-poker) with Zenhub @victor-chaparro

**Comment by luis-pabon-tf** [comment]
Existing LIVD lookup work by @victor-chaparro already solved this issue, so we don't need additional work here.
