### ISSUE TITLE
Partition etor vs full-elr during routing on Universal Pipeline

### ISSUE THREAD

**Issue by jimmyfagan** [CDCgov/prime-reportstream#9495]
### User Story:

As a ReportStream user, I want etor senders/receivers to be partitioned from full-elr senders/receivers in the Universal Pipeline.

### Description/Use Case

Ticket #8592 involved adding a topic for `etor`. The topics `full-elr` and `etor` both signify usage of the UP, however senders for one topic should only be able to send data to receivers of the same topic. 

### Acceptance Criteria

- [x] `etor-ti` senders can only send to `etor-ti` receivers
- [x] `full-elr` senders can only send to `full-elr` receivers

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9495?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimmyfagan @mkalish @thetaurean @TurkeyFried @victor-chaparro
