### ISSUE TITLE
Centralize participant matrix and link initiatives

### ISSUE THREAD

**Issue by dylansmith-Nava** [CDCgov/prime-reportstream#9498]
## User Story
As a ReportStream teammate, I want quickly and easily understand which research method(s) are currently being run and/or are upcoming, and which research initiative(s) these methods tie back to, so that I can understand why a current research method or session is being conducted and supporting which team goal(s).

## Background and context
Product teammates wanted more visibility and easy access into understanding the status of current research and what research might be upcoming.

## Open questions
- Where should the list of research initiatives live?
- How should they be linked to?
- How do we connect not just upcoming interviews, but other research methods and sessions to research initiatives?

## Working links
- (Participant tracker) [https://docs.google.com/spreadsheets/d/1oZ3jMVo0n-IUDWPlwLqNzllcf9egpu9MUF4jU1rJxfI/edit#gid=0]

## Acceptance criteria
- [ ] Forming a decision around the structure and organization on where these epics/initiatives should live
- [ ] Creating an easily understood and highly visible pathway to tie back to each epic/initiative

## Not in scope
- [ ] Writing content for any prior, current, or upcoming initiatives
- [ ] Deciding which research methods fall under which initiatives

**Comment by lizzieamanning** [comment]
- So that we don't burn out research participants by talking to the same people for different reasons at different times
- So that we can share context across the design team (or really the Engagement team)
- So that we can access notes and insights from one place

**Comment by dylansmith-Nava** [comment]
Discussed slight modification to this ticket with @lizzieamanning's feedback on 5/23.

**Comment by dylansmith-Nava** [comment]
Ported over @audreykwr's participants from [card-sorting document](https://docs.google.com/spreadsheets/d/1g9CT-rlo1M_wMnw34djKsfBOq-IaVHkt83ENyj10tr4/edit#gid=0) into the 1-team participant tracker on 5/23. Structure is feeling good and updates are slowing down.

**Comment by lizzieamanning** [comment]
@dylansmith-Nava can you link to the 1-team participant tracker in a comment when you get a chance?

**Comment by dylansmith-Nava** [comment]
Yep! Here is [the link](https://docs.google.com/spreadsheets/d/1oZ3jMVo0n-IUDWPlwLqNzllcf9egpu9MUF4jU1rJxfI/edit#gid=0) to the participant tracker. Thanks!
