### ISSUE TITLE
VT - Data Filter Changes

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#9506]
## **Problem Statement**

We received an email in the ReportStream inbox from Andrew Gross (andrew.gross@vermont.gov) regarding a request from the VT Department of Health to filter out specific CLIA results.

## **What you need to know**

Message received from Andrew:

> The team at Vermont Department of Health no longer wishes to receive self-reported covid results. To that end, we are inquiring about the possibility of discontinuing results with the below CLIA numbers from ReportStream. Please let me know if this is something that can be put in to effect.
> 
> CLIA numbers VDH no longer wishes to receive:
> 
> 00Z0000015 – OTC by Prescription
> 00Z0000016 – Proctored OTC
> 00Z0000042 – Self Reported OTC
> 00Z0000043 – OTC instrument-read

## **Acceptance Criteria**

Apply changes to data filter and confirm these results are no longer transmitted to VT DOH.

## **To Do**

- [ ] Restrict messages containing specified CLIA numbers from being transmitted to VT

## **Additional Comments**

The CLIA numbers appear to be associated with specific OTC self-tests that they no longer wish to receive.

**Comment by kant777** [comment]
https://github.com/CDCgov/prime-reportstream/pull/9723

**Comment by kant777** [comment]
@LaFreda1 Does Vermont want otc data from Image mover? currently this data has been sent by its own feed elr-otc. Imagie mover is not sending otc clia numbers they are sending the value "SA".

**Comment by sliu1000** [comment]
@wcollin89 Hi Wendy, can you please ask VT if they also no longer want to recieve OTC data from ImageMover?

**Comment by kant777** [comment]
@LaFreda1@sliu1000 @wcollin89 Please ignore my above message. we haven't received any data from ImageMover since August 2022 

applied the new settings to prod with help of @Gilmorea6
