### ISSUE TITLE
Update table on the STLT Facilities & Providers page to use the new and improved Table component

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-reportstream#9507]
## Problem statement

As part of the STLT Dashboard MVP, we need to implement the design of the table on the Facilities & Providers page. This implementation is strictly visual, and we'll have a separate ticket for hooking it up to the API afterward.

## What you need to know

- Latest [Figma File](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?type=design&node-id=6072-40941&t=q6sE1fXW050Nlyo7-1&scaling=min-zoom&page-id=2369%3A26962&starting-point-node-id=6072%3A40941&mode=design)

## Acceptance criteria
- [ ] Table should use the new and improved Table component
- [ ] Table should sort on all columns
- [ ] Table should paginate -- handled by API now
- [ ] Table should refresh data when filter button is clicked
- [ ] Clicking on ReportId will take you to the existing Report Details page /report-details/
* Do not link to Name within rows for now.

## To do

- [ ] Update Table to use the new and improved Table component
- [ ] Table should sort on all columns
- [ ] Table should paginate -- handled by API now
- [ ] Table should refresh data when filter button is clicked
- [ ] Facility Type column needs to apply styling (facilityTypeDisplay)

**Comment by chris-kuryak** [comment]
Penny seems to have implemented this already. So this ticket may not be needed.
Will need to check once the API is integrated into page.

**Comment by chris-kuryak** [comment]
May be completed in the existing work. Will check after it gets completed.

**Comment by chris-kuryak** [comment]
Adding a needs-info label until we get an update from @penny-lischer as to whether this is necessary.

**Comment by chris-kuryak** [comment]
No longer needed. Table component already in. Styling will be updated by #10626.
