### ISSUE TITLE
Create EmailSchedule Settings API

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#952]
Updated path for email API proposal: 

https://github.com/CDCgov/prime-reportstream/tree/master/prime-router/docs/proposals/0007-email-notification

~~Create the EmailSchedule API as found in https://github.com/CDCgov/prime-data-hub/blob/email-notification-proposal/prime-router/docs/proposals/0006-email-notification/0006-email-notification.md~~

**Comment by Bisonburger** [comment]
EmailSettings and EmailEngine have been created and deployed to staging.  

Setup to fire off message (to Mo, myself, & James) tomorrow (20JUL) at 8PDT/11EDT.

**Comment by loripusey** [comment]
@Adrian-Brewster @drew-usds The link to the proposal no longer works, can someone provide a new link?

**Comment by loripusey** [comment]
@drew-usds ?

**Comment by drew-usds** [comment]
@loripusey Matt was working on this, just updated the issue description with what is probably the updated proposal path.

**Comment by loripusey** [comment]
Thanks @drew-usds

**Comment by loripusey** [comment]
Lori/Rachel evaluated and want it to remain in the Icebox for now; we would need a valid use case before moving forward any technological implementation like this
