### ISSUE TITLE
Add a utility function that calculates  age based on DOB

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#9532]
### User Story
A ReportStream, I want the ability to calculate a person's age based on their DOB, so that I can send this to receivers.

### Description/Use Case

The RADx MARS HL7 v2 format expects an OBX segment with the patient's age. We currently only get a patient's DOB and not their age.

### Risks/Impacts/Considerations

RADx MARs messages will not contain the age OBX segment.
https://www.nibib.nih.gov/covid-19/radx-tech-program/mars/HL7v2-implementation-guide specifies the age must be in years, how do we handle persons less than 1 year old?

### Dev Notes

This could be implemented as a custom FHIR path function, so that I can be used during our transforms.

### Acceptance Criteria

- [x] ReportStream can calculate a person's age based on their DOB.
- [x] unit to return (days, months, years) should be configurable

**Comment by bishoyayoub** [comment]
Follow up with Andrew W on RADx MARS spec specifying age must be in years. How do we specify this for persons under one years old?

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9532?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimmyfagan @mkalish @thetaurean @TurkeyFried @victor-chaparro
