### ISSUE TITLE
SPIKE: Investigate requirements to enable Microsoft Defender on all artifacts

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#9544]
Determine what is required and create tickets to enable Microsoft Defender on all supported artifacts

**Comment by lucasdze** [comment]
[Microsoft Defender Documentation](https://learn.microsoft.com/en-us/azure/defender-for-cloud/)

Microsoft Defender for Cloud is a cloud-native application protection platform (CNAPP) with a set of security measures and practices designed to protect cloud-based applications from various cyber threats and vulnerabilities. Defender for Cloud combines the capabilities of:

A development security operations (DevSecOps) solution that unifies security management at the code level across multicloud and multiple-pipeline environments
A cloud security posture management (CSPM) solution that surfaces actions that you can take to prevent breaches
A cloud workload protection platform (CWPP) with specific protections for servers, containers, storage, databases, and other workloads
[Pricing](https://azure.microsoft.com/en-us/pricing/details/defender-for-cloud/)
