### ISSUE TITLE
Finalize content for ReportStream website that is linked from new Error Codes (#8642)

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9546]
_[Governance document](https://docs.google.com/document/d/1__FE0OGlVAby0m7QyKfo_Qr0Gh_PvALaA1_DeCJSjzQ/edit#heading=h.qyvn837dl01t) for content process reference_

## Is this new content or an edit to current content?

- [ ] **Edit**: It is not a change that affects the design or functionality of the page/feature.
- [x] **New**: It is something new that is mostly content (not a tool).

## Questions for edit requests:

1. Current page link:

2. Change requested:

3. Why is this change needed?

4. How urgent is this change and why?

## Questions for new content requests:

1. Explanation:
- The Platform team recently created some new error codes that can help a user self-service their own issues regarding authenticating their connection when sending data to ReportStream. This is found in #8642
- So the purpose of this content is to provide instructions/assistance that will help a user self-service their own issues.
- These new error codes are specific to the API Programmer's Guide [Setting Up your Authentication](https://reportstream.cdc.gov/resources/api/getting-started#set-up-authentication-and-test-your-api-connection) -> Method 1 -> Step 2 (Generate a signed JWT)
- This content should be on the ReportStream website so that it can be linked from the new error codes output from the API.

2. Status of content: 
- [ ] Idea
- [x] Initial draft (rough ideas started)
- [ ] Final draft (fairly confident in the content you have for this)

3. What identified audience need does this content help meet? 
- Sender: Set Up a Public/Private key

4. What OKR (quarterly or annual) does this help meet? How?
- None

5. Have you considered if existing content already meets these needs, or could with some modification? 
- The API Programmer's Guide already has some content around how to accomplish the task of authenticating their connections, but it does not have these error codes. And this content needs to be available via web-link (not only in the static version of the API Programmer's Guide).

## Complete your request by:

- [x] Making sure you’ve answered all questions for the appropriate request type (edit or new)
- [x] Labeling this ticket as `content request`, `design` and `experience`
- [x] Assigning this ticket to @audreykwr

_Thank you for contributing to content excellence for ReportStream!_

------------------------------------

## Content for consideration

The user facing errors can be seen [here](https://github.com/CDCgov/prime-reportstream/blob/0a9c56bac7585122de7135bf3bea4ffb8b4fb753/prime-router/src/main/kotlin/tokens/Server2ServerAuthenticationException.kt#L20); there are comments that explain what the error is from a engineer standpoint, but I've pulled the out below for iteration.  All of the following errors are potentially generated when an organization generates a signed Json Web token (JWT) and attempt to use it to retrieve an access token that can be used to invoke the various APIs.

There is an initial attempt to map these errors to specific content (captured via `errorUri`) but that can be edited.

- expired token: a token has an expiration time associated and a user receives an error if that expiration time has passed
- unsigned JWT: it is possible to generate a JWT without including the signature, possible content would point back to how to generate signed JWT
- malformed JWT: it is possible that what was sent to our API cannot be decoded into a JWT,  possible content would point back to how to generate signed JWT
- invalid scope: as part of requesting an access token, the scope (which resources they can access) must be included in the request and must match the expected format which would look something like `{orgName}.*.report`
- no valid keys: this error can occur if there are no public keys associated with the org or none of them can be used to verify the signature of the JWT
- no matching organization: part of the content of the JWT is a field called `iss` (issuer) which should match to an organization; this error is returned if no organization matches the `iss` field
- missing JWT: this error occurs if the user attempts to request an access token but does not include a JWT at all
- missing scope: this error occurs if the user attempts to request an access token, but does not include a scope

## Finalized Content (and formatting)
TBD

## Acceptance Criteria
- [ ] New error code content created and formatted properly for implementation in #9945
- [ ] Content change (and formatting) to API Programmer's Guide (that will link to new Github page in #9945) created and documented somewhere in this ticket

**Comment by chris-kuryak** [comment]
@audreykwr This is a content request from @mkalish and the Platform team to have a linkable location for some new error codes in the authentication process of setting up new senders.

We should discuss where this can fit into an upcoming sprint.

**Comment by audreykwr** [comment]
@chris-kuryak So this sounds like it's building on this [backlog item](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/8383)? To clarify - is this making it so more specific error codes are generated, like for the validator tool?

**Comment by chris-kuryak** [comment]
@audreykwr 

- This is not related to the Public Key Tool (backlog item you referenced above). These new error codes are for the API Token generation which happens on Page 9, Step 3 of the API Programmer's Guide entitled "**Send the signed JWT to ReportStream to get a temporary bearer token**"
- Yes! This is to add more specific error codes so that users can try to solve their own issues, just like you did for the validator tool.
- In this case, the the API Error codes can now include a URL link with the error code, and the Platform team is looking for a link to include in that error code that will send the user to more useful information.

**Comment by audreykwr** [comment]
@GilmoreA6 Since this will be an update to the API guide section, can you approve this as an update to work on? Flagging you per [the content governance process](https://docs.google.com/document/d/1__FE0OGlVAby0m7QyKfo_Qr0Gh_PvALaA1_DeCJSjzQ/edit#heading=h.sn9794nk3hhd)

**Comment by chris-kuryak** [comment]
@mkalish Do you know how often folks (roughly) would get an error? In other words, what percentage of users get a valid response (no error) on the first try?

This is to help us determine where we want the information to be.

**Comment by chris-kuryak** [comment]
Quick Update @audreykwr, which we can discuss more next week.

1. These new error codes are specific to the API Programmer's Guide [Setting Up your Authentication](https://reportstream.cdc.gov/resources/api/getting-started#set-up-authentication-and-test-your-api-connection) -> Method 1 -> Step 2 (Generate a signed JWT)
2. Currently, the API error code response that Michael has created returns ONLY a link that is specific to that error (seen as individual bullets under "Content for Consideration" in the ticket description above).
  - For example, the original idea from Platform would be that the error link includes a hashtag that can anchor to a specific point on a webpage. Here is an example of a [Github Error code page](https://docs.github.com/en/apps/oauth-apps/maintaining-oauth-apps/troubleshooting-authorization-request-errors#application-suspended) with anchors that link to specific error codes. So if you received the "application suspended error" you would receive a link that takes you to [domain/error_page#application-suspended](https://docs.github.com/en/apps/oauth-apps/maintaining-oauth-apps/troubleshooting-authorization-request-errors#application-suspended).
3. However, if we wanted to link to a generic table/list of error codes, instead of specific anchors, Platform could include an error code in the response, in addition to a link. So that would be like "Error Code 2, [LINK TO TABLE]".

**Comment by chris-kuryak** [comment]
After chat with @audreykwr, plan of attack:
- Finalize content and #anchors for all errors
- Create error content on a ReportStream Repo wiki page
- Add link from API Prog Guide to new Error page on RS Repo
- Add link from Error page on RS Repo to API Prog Guide instructions on how to generate the token
- Inform Platform team (Michael) of new page and anchor links

**Comment by audreykwr** [comment]
Adding for decision tracking: We decided to add it to GitHub and link to that from the codes and from the API guide site page due to rather than adding this content directly on a site page for the following reasons:

1. The current page structure for authentication instructions is not conducive to including this much more into that section and therefore would require restructuring or creating a new page.
2. Not proven to be an error that majority of users encounter.
3. There is precedent for linking to GitHub from the guide for further documentation.

This was still a great use of content requesting as it does create an update to the guide content.

Additional note: Further discussion is planned unrelated to this ticket as we get firmer guidelines for what we put on GitHub vs site content

**Comment by audreykwr** [comment]
[Approved content](https://docs.google.com/document/d/1AqazB32yopIHRjkMOtLa8cBP-qusmu3LQiHFI43cLeo/edit#heading=h.u8u2sxjpgz13) by @mkalish (for the codes) and @GilmoreA6 (for update to the guide content)
