### ISSUE TITLE
UP Receiver Configuration Discovery

### ISSUE THREAD

**Issue by jakefishbein-navapbc** [CDCgov/prime-reportstream#9548]
## Background & context

Based on our experience with Receivers during Covid19 and in our current flu pilot, we have learned that STLTs often have unique needs in terms of the data they want to receive. As of now, our white glove service sets up custom configurations based on the needs of each customer. As ReportStream expands to new conditions, however, STLTs configuration needs will likely grow. This presents an issue of scale as we will not be able to efficiently create custom configuration for each STLT we migrate or onboard to UP. Additionally, configurations have the potential to change, which would create more strain on our engineering team.

This discovery process seeks to determine the range of variations in how STLTs might seek to configure their ReportStream connection. This will allow us to determine the best approach to efficiently supporting STLTs in establishing custom configurations for each of their unique contexts. Discovery will include an analysis of a range of STLTs reporting policies, interviews with STLT representatives, and information gathering from internal subject matter experts. This information will be triangulated to inform engineering and product decisions on how best to meet our STLTs' needs.

The final outcome of this discovery will be the creation of potential self-service configuration concepts. These concepts will be presented in writing along with supporting artifacts such as user flows and wire frames. These will be presented to engineers and product managers to determine accuracy, feasibility, and size.

Sample user story: As a Receiver, I need to configure my setting so that I can ensure that I am receiving the data I want from Senders.

## Value Proposition 
This epic will provide the ReportStream team with guidance on how to approach self-service settings for receivers. This should reduce the overall workload placed on engagement engineers and provide our users with a greater level of control. 

## Impacted Objectives and Key Metrics (OKRs) 
(Need to align with OKR) 
- Metrics Impacted: Time to complete onboarding. Reduced engineering time spent on configurations. Reduction in support tickets related to configurations.

## Open questions
-   In what ways to STLTs differ in the information they collect from senders?
-   How significant is the variation in terms of STLT collection requirements?
-   What does this variation suggest in terms of designing a process or feature to configure UP?
-   What are the most common configurations?
-   What is the level of granularity?
-   If STLTs want certain condition data, how do we determine what to prioritize or what that means for the senders sending that data question?
-   What are the most important questions to answer 

## In Scope  
STLTs

Likely deliverables 
- A summary of the range of STLT configuration requirements.
- A summary of evidence from policy analysis, interviews, and other sources.
- Recommendations to engineering and product about how we might address configuration needs.

## Out of Scope 
Sender configurations

## Users
STLTs

**Comment by dylansmith-Nava** [comment]
Looks great @jakefishbein-navapbc, I am leaving a comment before it falls out of my head.

- I think it's implied in your questions but I'd love to know if there's a set of configs out there that >80% of STLTs share. I.e., we know basically all STLTs request these [20? 50?] configs. Therefore, we can proactively provide them.

**Comment by lizzieamanning** [comment]
For epics, we have this template:
EPIC TEMPLATE

Background and Context 
Value Proposition 
Impacted Objectives and Key Metrics (OKRs) 
In Scope 
Out of Scope 
Users

I think reformatting and filling out those added categories can help us with clarity here @jakefishbein-navapbc

**Comment by lizzieamanning** [comment]
linking resources: 
https://docs.google.com/document/d/1siokYtBQB4mwSQRF93akPp1Nn5Ww3v-UYst7nV-ozUM/edit#

**Comment by lizzieamanning** [comment]
Holding until discovery sprint is finished: https://docs.google.com/document/d/1PJOSW4agb3Pgnp984Qq6f-UlGCJCZ9jpFIZizqSpQfg/edit

**Comment by lizzieamanning** [comment]
Notes for potential tickets:

1. Internal discovery process: reviewing docs to determine what could be translated into a "form"? Talking to eng, etc
2. Flows/wires to validate

**Comment by lizzieamanning** [comment]
https://docs.google.com/spreadsheets/d/1iKYB6OmqXMFkwGp960EUU8Y78pWvwQRs1YYYhObsEKI/edit#gid=206627954
