### ISSUE TITLE
Finalize ReportStream one-pager design

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#9561]
## User story

As a ReportStream representative, I need a one-pager so that I can distribute information to external stakeholders with clear ReportStream branding. This one-pager should be a “sell-sheet” that explains what we do, why senders and receivers should onboard, and how they can do so.

## Background & context

The ReportStream team would benefit from a concise and branded one-pager to distribute at external events. 
This ticket captures the finalization of the draft design (#9440).

## Open questions

-   What are the design and customization limitations of MS Word/Google Slides?
-   What is the content? Where is it coming from?
-   Suggested collaborators: Glenn, Audrey

## Working links
- [Visual branding workspace](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1681847288631/0e18f2c3ba740da2a8d4bc02bdd9f55a28dfadc3?sender=u0c3cdba5126734aceb613229)
-   [Outline](https://docs.google.com/document/d/1xPdLj5Kb1CFXLz-6vNCKU0h_TFG33LSkoLC8fapahj8/edit#)
-   [Original thread with need](https://nava.slack.com/archives/C051JAPND96/p1683571615880449)
- [WIP | ReportStream Doc Template](https://docs.google.com/document/d/168JCeey9lFVgIIwC3QpqI_0KNjJaNskvlp1_BgRQqU4/edit#): blank template with lorem ipsum
- [WIP | ReportStream | One pager design sandbox](https://docs.google.com/document/d/18d5hHvzezKO1cdrSo0iOnt1Yiz4KqFKlGmJelUloUog/edit#heading=h.t1ygjjn9q2u): testing the template with the one pager content outline

## Final links

Google Drive
- PDF: [ReportStream_Onepager_20230621](https://drive.google.com/file/d/1PCvkkkt2hSDfpQwS1v5Ps7UJbWqo9n3D/view?usp=drive_link)
- Docs: [ReportStream_Onepager_20230621](https://docs.google.com/document/d/1YT20rO5gAyJUqph9RdLz4heceJ72MNFi0ySSwRCPPmA/edit?usp=drive_link)

Sharepoint

- PDF: [ReportStream_Onepager_20230621](https://cdc.sharepoint.com/:b:/r/teams/ReportStream/Shared%20Documents/General/ReportStream%20Doc%20and%20Presentation%20Deck%20Templates/ReportStream_Onepager_20230621.pdf?csf=1&web=1&e=nR4P4D)

## Acceptance criteria

-   [x] One-pager design uses CDC/ReportStream branded visual language
-   [x] Reviewed by USDS stakeholders
-   [x] Reviewed by design team (content and Engagement specifically) 
-   [x] Reviewed by client-facing stakeholders
-   [x] Template is Microsoft Word compatible and accessible on Sharepoint
-   [x] Template is Google Docs compatible and accessible on Drive

**Comment by lizzieamanning** [comment]
@jillian-hammer should we add the design in Microsoft tools/Sharepoint as part of this ticket or do you want to track that separately?

**Comment by jillian-hammer** [comment]
@lizzieamanning thanks for flagging, I will add MS compatibility as an AC for this ticket!

**Comment by chris-kuryak** [comment]
@audreykwr @jillian-hammer to sync before taking on this ticket.

**Comment by jillian-hammer** [comment]
@lizzieamanning we haven't finalized the one pager content yet so it's carrying over. however, you're making me realize that we could have separated the doc template itself (no content) as a separate ticket.

**Comment by jillian-hammer** [comment]
Closing! @audreykwr shared [via Slack](https://nava.slack.com/archives/C024MGSJZ38/p1687358089815919).
