### ISSUE TITLE
Finalize ReportStream deck template

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#9562]
As a RS team member, I'd would like to use a standardized presentation template so that both my internal and external communications visually reflect RS's branding and mission.

### Description/Use Case
Develop a presentation template draft that utilizes ReportStream's visual brand language (VBL). 
This is a follow-up ticket to finalize the design work outlined in #9188.

### Considerations
- Consider use with other partnering organizations (e.g., SimpleReport, NBS, CDC OPHDST), and how the RS template may complement existing visual branding while still having a differentiated stance.
- What are the typical uses for a presentation document? Who is the audience? Who is the creator? What are the topics?
- Ensure that the template works with MS Office or can be exported to maintain VBL
- Future: Linked to broader style guide documentation (see epic, link TBA)
- Future: Nice to have: Guidelines for proper and improper use
- Future: Prioritize Google Slides template first, then if possible, convert to PowerPoint

### Links
- [WIP | ReportStream Presentation Template](https://docs.google.com/presentation/d/1Q3vMZSnjHMOGJfrMc9f2P_bT4EhY27U5IZsgmYrISOk/edit?usp=sharing): blank slides with lorem ipsum
- [WIP | ReportStream Sample Slides](https://docs.google.com/presentation/d/12Gkk5un4syxdyKGJ5dwlwTwfHc43o1r1n6bmy99sD3w/edit#slide=id.p): where I'm stress testing the templates with sample content across use cases from our project
- [Microsoft Powerpoint version](https://cdc.sharepoint.com/:p:/r/teams/ReportStream/Shared%20Documents/General/20230605_ReportStream_Deck_Template.pptx?d=w71210b575c684cb8abfc2e033dc8ab52&csf=1&web=1&e=EfNgVY)

### Acceptance Criteria
- [x] Aligns with CDC brand
- [x] Contains templates that are flexible for all teams and disciplines to use (e.g., design research reports, product timeline planning, engineering requirements) on Google Slides
- [x] Review with USDS stakeholders
- [x] Review with Design team
-  [ ] Template is Microsoft Powerpoint compatible and accessible on Sharepoint
-  [x] Template is Google Slides compatible and accessible on Drive

**Comment by jillian-hammer** [comment]
Ready for review @lizzieamanning: 

I did a bit of research and found out that the online version of Powerpoint [doesn't support custom templates](https://support.microsoft.com/en-gb/office/using-templates-in-powerpoint-for-the-web-7d402d46-1eed-48d0-80fe-a26dfee3abac), so unfortunately I can't create a master template :( so instead we might have to take the same approach as we do with Google slides and let people just copy paste the slides they need. 

Can you take a look at the [Sharepoint version](https://cdc.sharepoint.com/:p:/r/teams/ReportStream/Shared%20Documents/General/20230605_ReportStream_Deck_Template.pptx?d=w71210b575c684cb8abfc2e033dc8ab52&csf=1&web=1&e=BvBTOZ) and see if it works for you? Does the text/font/formatting get fussy when you try to edit it? 

thanks!

**Comment by lizzieamanning** [comment]
I made a test deck and the only thing I noticed was that when I click into edit the slides, the font changes to Arial (as you've acknowledged) I think that's great for an MVP as you provided a way for folks to download public sans. 

My only other comment is that it took me a moment to figure out how to copy the template (and ensure I wasn't writing over it), so adding those instructions as a reminder may be nice @jillian-hammer

**Comment by jillian-hammer** [comment]
thanks for this feedback @lizzieamanning! I'll add some how-to instructions as the first slide in both instances and close the ticket.

**Comment by jillian-hammer** [comment]
status: incorporating feedback before closing by eow 6/9.
