### ISSUE TITLE
Publish "Release Notes" - May 2023

### ISSUE THREAD

**Issue by Andrey-Glazkv** [CDCgov/prime-reportstream#9563]
### Problem statement
As a user, I would like to know what features, bugs, other user facing updates have been made to ReportStream product.

### Procedure
https://docs.google.com/document/d/1vAiOJlfRMvJPRER3cr9Kr4lQ2-_ybNucJt28kI3fl1I/edit 

### Acceptance criteria
- [ ] Delivery Manager: Final Release Notes text (in ticket description) updated with all release notes and formatted with markdown
- [ ] Content Specialist: Approve release notes content and formatting
- [ ] Engineer: Add **Final Release Notes Text** to [Release Notes page](https://reportstream.cdc.gov/product/release-notes) (reference Procedure above if needed)

### Final Release Notes Text (formatted properly with Markdown)
**New Features**

- The [ReportStream File Validator tool](https://reportstream.cdc.gov/file-handler/validate) enables users to validate data formatting for COVID test results against three standard schemas (HL7, CSV, CSV-OTC). If a testing facility has a custom data model, they can validate against that schema if logged in. Users can also troubleshoot issues with their datasets by seeing specific errors and warnings for their files.

- The [Public Key tool](https://reportstream.cdc.gov/resources/manage-public-key) allows new testing facilities to upload their shared public key directly through the ReportStream site as they are setting up authentication. Improvements are planned for the future to allow a user to manage their public keys through this tool as well.

**Improvements**

- Usability: The [FAQ Page](https://reportstream.cdc.gov/support/faq) has been updated with additional questions and clearer answers.

**New State Connection**
We’re excited to announce that ReportStream can now send public health data to Pennsylvania.

**Comment by Andrey-Glazkv** [comment]
We’re excited to announce that ReportStream can now send public health data to Kansas.
Improvements:
Users can now use File Validator Tool, Public Key Tool
Users can now see API Programmer's Guide as a webpage (tbd)
FAQ Content Update has been made

**Comment by chris-kuryak** [comment]
@Andrey-Glazkv Here is my attempt:

**New Features**
- The [ReportStream File Validator tool](https://reportstream.cdc.gov/file-handler/validate) enables users to validate COVID test result data against three standard schemas (HL7, CSV, CSV-OTC), as well as any custom schemas associated with a sender. This tool also helps users troubleshoot issues with their datasets.
- The [Public Key tool](https://reportstream.cdc.gov/resources/manage-public-key) allows new senders to upload their shared public key to ReportStream without needing to interface with the ReportStream support team. Improvements are planned for the future to allow a user to manage their public keys as well.

**Improvements**
- Usability: The [API Programmer's Guide](https://reportstream.cdc.gov/resources/programmers-guide) has been added to the ReportStream website in an interactive web format. Future enhancements are planned to further expand the usability of this content.
- Usability: Updated content has been added to the [FAQ Page](https://reportstream.cdc.gov/support/faq) to assist in answering common questions.

**New State Connection**
We’re excited to announce that ReportStream can now send public health data to Pennsylvania.

**Comment by audreykwr** [comment]
Edited version below:

> **New Features**
> 
> - The ReportStream File Validator enables users to validate data formatting for COVID test results against three standard schemas (HL7, CSV, CSV-OTC). If a testing facility has a custom data model, they can validate against that schema if logged in. Users can also troubleshoot issues with their datasets by seeing specific errors and warnings for their files.
> 
> - The Public Key Tool allows new testing facilities to upload their shared public key directly through the ReportStream site as they are setting up authentication. Improvements are planned for the future to allow a user to manage their public keys through this tool as well.
> 
> **Improvements**
> 
> - Usability: The API Programmer's Guide, previously only available as a PDF download, is now part of the ReportStream website. The web pages provide a user-friendly format that ensures users always have the most updated information.

> - Usability: The FAQ page has been updated with additional questions and clearer answers.
> 
> **New State Connection**
> We’re excited to announce that ReportStream can now send public health data to Pennsylvania.

**Comment by chris-kuryak** [comment]
@Andrey-Glazkv Audrey's version is missing the hyperlinks. I will add them back in and post in the body of the ticket.

**Comment by chris-kuryak** [comment]
@Andrey-Glazkv Don't publish these release notes until after the API Programmer's Guide launches. So perhaps just wait until the end of this sprint to be safe.

**Comment by Andrey-Glazkv** [comment]
@chris-kuryak sure, as we agreed last Thursday

**Comment by Andrey-Glazkv** [comment]
@etanb please go ahead and update the Release Notes page with the approved text
cc @chris-kuryak
