### ISSUE TITLE
CO - Divison of Youth Services File Submission Error

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#9572]
## Problem statement

File Submission Error for CO - Sender 

## What you need to know

Message ID: 1684713600_3012+9+20230522
Received by: CDPHE ELR Prod
Received on: 2023-05-22 19:30:48
File source: CDC PRIME
File name: covid-19-18674d32-1fe3-4ee0-8fa6-07186491ea12-20230523013052.hl7
Performing Org Name: CO Divison of Youth Services

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by jalbinson** [comment]
@oslynn and I investigated and determined that this was already completed. The messages were correctly resubmitted by CO - Division of Youth around when the issue was created.
