### ISSUE TITLE
Write visual brand design brief

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#9582]
## User story

As a designer, I need to understand both the strategic approach and scope of ReportStream's visual brand development in the form of a design brief, so that I can ensure that the brand development work stays on track and within bounds during the design phase of the project.

## Background & context

After gathering feedback on approach and scope from USDS stakeholders, our the next step is to finalize the goals and scope of the branding work to inform the subsequent design phase. This visual brand design brief is a necessary alignment tool.

## Open questions

- What is the final scope of the visual design work?
- What is our recommendation re: ReportStream's institutional brand positioning?
- What format should this be in? Add to existing doc or pulled out as deck?

## Working links

- Existing running design brief doc: [Visual Design Brief](https://docs.google.com/document/d/1Bm6RJx4DYuX3zD_-zXkpsnm8VSMw5c8gEEubuRo_Ny4/edit?usp=sharing) to be refined 
- Input: [ReportStream Messaging Summary](https://docs.google.com/presentation/d/16AnBMcWQFT4a8ZFMClOkA_VQttkwOhJfL3H0wpJhXYY/edit?usp=sharing)
- Mural: [Visual branding workspace](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1681847288631/0e18f2c3ba740da2a8d4bc02bdd9f55a28dfadc3?sender=u0c3cdba5126734aceb613229)

## Acceptance criteria

-   [x] Design brief identifies visual brand goals by building upon existing messaging & tone deliverable
-   [x] Design brief outlines recommendation(s) re: institutional brand positioning, in scope visual assets
-   [x] Design brief outlines clear scope of the visual brand design phase
-   [x] Reviewed by design and/or design lead
-   [x] Reviewed by internal stakeholders (All Teams or via Slack)

**Comment by chris-kuryak** [comment]
Will carry over

**Comment by jillian-hammer** [comment]
In review with @lizzieamanning; visual brief link [here](https://docs.google.com/document/d/1Bm6RJx4DYuX3zD_-zXkpsnm8VSMw5c8gEEubuRo_Ny4/edit#bookmark=id.p8wcnn61p63a).

**Comment by jillian-hammer** [comment]
Reviewed by Lizzie, Audrey, and Senongo. Review request out to Drew.
