### ISSUE TITLE
Researching the UP gap analysis

### ISSUE THREAD

**Issue by dylansmith-Nava** [CDCgov/prime-reportstream#9592]
## User Story
As a ReportStream teammate, I want to understand via gap analysis which documents, Murals, etc. need to be updated to reflect UP processes, so I know where I can 'fill in the gap' and help complete the migration to UP.

## Background and context
Engagement team is going to be supporting WebEx and Platform as an "all hands on deck" pivot so that ReportStream is prepared to onboard new users or migrate current users to UP.

## Open questions
- How should we use [Brandon's UP Playbook doc ](https://docs.google.com/document/d/1noB3lK2Nc_vbD4s5ZHgdTjgIjhCii63x_2bjBz7GM1I/edit#heading=h.e9c4snuuhcc8)as our centralized source of truth for where these gaps exist?
- What would be considered "done" for this ticket? @brandonnava 
- Which materials are a priority, and need to be updated first?
- How should we best flag materials that design is capable of updating, versus materials that need to be handled by engineers?

## Working links
[Engagement design/prod sync](https://docs.google.com/document/d/1ilOrCRjlF4PzFiCq368MwA2rriWzxDelx-912tEToKg/edit)

## Acceptance criteria; Proposed
- [ ] >95% of all materials have been properly updated for UP
- [ ] Journey is mapped out for onboarding new users and existing users to UP
- [ ] New and existing users can be successfully onboarded with minor bugs

## Not in scope
- Self-service STLT configuration features
- Self-service new sender authorization features
- Setting design as the primary 'updaters' of materials

**Comment by dylansmith-Nava** [comment]
@lizzieamanning ticket made! I'd love your help / input on any labels that would be appropriate here and/or epics I should tie this to?

Also, I updated the Open Questions, based on your feedback in Slack. Let me know if they make sense! :)

**Comment by lizzieamanning** [comment]
@dylansmith-Nava great! After reviewing again, I wonder if it makes the most sense to scope this ticket for what design _can_ support with. That way, we can have a clear owner and clear bounds. For example, the current ACs are broad and have a lot of dependencies that wouldn't allow us to move this ticket forward sprint by sprint (in my opinion). I think this could be part of a larger epic. @brandonnava does a larger epic exist yet? Other thoughts?

**Comment by dylansmith-Nava** [comment]
Very true - just thinking aloud @lizzieamanning, but perhaps this ticket _could_ be an epic? And then each document or document folder that needs to be updated could be a ticket.

**Comment by lizzieamanning** [comment]
I will leave that to you if you think that works best. To help decide, do you have a sense of how many artifacts that is? @dylansmith-Nava

**Comment by dylansmith-Nava** [comment]
@lizzieamanning tbh I think that's part of this ticket - figuring out which artifact(s) and what content can/needs to be updated by Design. I think next steps for me would be to meet up/ping @brandonnava re: Playbook to start somewhere.

**Comment by dylansmith-Nava** [comment]
@brandonnava I chatted with Lizzie and this ticket seems to be well-summarized by the [UP Playbook](https://docs.google.com/document/d/1noB3lK2Nc_vbD4s5ZHgdTjgIjhCii63x_2bjBz7GM1I/edit#) document you have going!

We were discussing that this ticket feels too broad and may need to be archived from a design perspective. Before I do that, is there any language / content here that you'd like to use? I want to make sure it's useful for you before I close it out!
