### ISSUE TITLE
Replace regex use with html-to-text npm module

### ISSUE THREAD

**Issue by snesm** [CDCgov/prime-reportstream#9601]
## Problem statement

The regex used to remove HMTL markup may have performance issues.

SonarCloud thinks <(.|\n)*?> might allow a DoS condition due to [catastrophic backtracking](https://www.regular-expressions.info/catastrophic.html).
It looks like you’ve used that at https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx#L77 and https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/utils/misc.ts#L180

This problem should be fixed to avoid potentially rendering RS inaccessible.

## What you need to know

- [Regex use one](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx#L77)
- [Regex use two](https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/utils/misc.ts#L180)

## Acceptance criteria

- [ ] Eliminate both regex uses

## To do

- [ ] ...

**Comment by Andrey-Glazkv** [comment]
@etanb hi, could you (or someone who asked you to work on it) please add an example of those issues. Thanks! I assume we want to do it to ensure that we get plain text out of html, right? Just wondering why regex is not applicable.
cc @chris-kuryak

**Comment by etanb** [comment]
> SonarCloud thinks <(.|\n)*?> might allow a DoS condition due to [catastrophic backtracking](https://www.regular-expressions.info/catastrophic.html).
It looks like you’ve used that at https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx#L77 and https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/src/utils/misc.ts#L180

From the reporter @snesm
