### ISSUE TITLE
Update the content (Instructions/Links) to new API Programmer's Guide Webpage(s)

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9602]
## Problem statement
As a user, I need accurate instructions of what to do next during the sender onboarding process. Since launching the web version of the API Programmer's Guide, the instructions as shown on the Public Key Tool flow need to be updated to reference it.

## What you need to know

- [Public Key Tool](https://reportstream.cdc.gov/resources/manage-public-key)

## Acceptance criteria

- [x] Content / instructions ready to hand off to engineering to update the website
- [x] - [ ] Create tickets for engineering with Chris

## To do

- [ ] ...

**Comment by audreykwr** [comment]
Updated content: https://docs.google.com/document/d/1A2inCJxVQVLULYx_CAyzcDP2LpVvNMhvmhw0QTdXnIg/edit

@chris-kuryak let me know what I need to do for the follow on tickets

**Comment by audreykwr** [comment]
@chris-kuryak can we create those eng tickets so we can close this?

**Comment by chris-kuryak** [comment]
Created follow-on engr ticket #10261
Can close this ticket.
