### ISSUE TITLE
Route Resource Page Link to the new API Programmer's Guide

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9613]
## Problem statement
As a user, I want to be able to access the API Programmer's Guide (web version) from within the ReportStream website. As such, the link on the Resources Page to the Programmer's Guide should now go to the new Web Version of the API Programmer's instead of the static page with just a download link of the PDF version.

## What you need to know

- [Resources page](https://reportstream.cdc.gov/resources)
- [Existing API Programmer's Guide Page](https://reportstream.cdc.gov/resources/programmers-guide)
- ...

## Acceptance criteria

- [ ] Align with Design team on the structure of the URLs for the new Programmer's Guide webpages across our site structure
- [ ] Update the routing accordingly

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@jillian-hammer do you think it needs to be reportstream-api? Could it just be /api? 

The card on resources reminds me: @chris-kuryak - can we have a ticket to update that? Since it does not match the content it will go to? I can get that text to you in the ticket for whoever is assigned to update it

**Comment by jillian-hammer** [comment]
good point @audreykwr, simplifying to `/api` makes sense to me. does that work for you @jpandersen87?

**Comment by chris-kuryak** [comment]
@audreykwr Sure thing! Created ticket #9642. Please add your changes to the text in the space I provide under "What you need to know"

**Comment by chris-kuryak** [comment]
Latest confirmed changes:

Landing Page: `/resources/api`
Getting Started: `/resources/api/getting-started`
Documentation: `/resources/api/documentation`
Documentation, with anchor link: `/resources/api/documentation/data-model#patient-data-elements`
