### ISSUE TITLE
Design: Define parameters for handling table edge cases

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#9614]
## User story

As a ReportStream designer/engineer, I need clear technical specs to inform table behavior, so that the tables handle edge cases gracefully and consistently across the website. 

## Background & context

This is part of the custom table component work. We need to consider a swath of edge cases for our tables and define how we’d like to handle them from a design POV in response to technical limitations.

Screen recording of Etan's WIP component (5/24/23):
https://images.zenhubusercontent.com/304423150/9310266b-0466-482c-b91a-b458958a6031/table_scroll_052423.mp4

## Open questions

- In the case of triggering horizontal and vertical scrolling, what is the maximum height for `scrollable` and `stickyHeader` tables? 
  - Do we want to all tables have a max height?
- In the case of long strings, how should we handle word breaks? 
- In the case of long strings, how would we like to truncate / expand that content? 
- In the case of sticky headers, what color/styling should they have?

## Working links

- [WIP spec sheet on Figma](https://www.figma.com/file/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?type=design&node-id=5414-39373)

## Acceptance criteria

- [x] Define specs in an accessible document for engineers to implement

**Comment by jillian-hammer** [comment]
Answers (and some questions!) for discussion with @etanb (once we finalize, we can move to a more perm format):

**In the case of triggering horizontal and vertical scrolling, what is the maximum height for `scrollable` and `stickyHeader` tables?**
OK to proceed with 80v, is this something we can build the ability to tweak per instance or does it need to be standardized globally?

**Do we want to all tables have a max height?**
No, I think our table component should default to not scrolling and not having a max height. I think scrolll+sticky is a behavior you can toggle on/off. Does that work? 

**In the case of long strings, how should we handle word breaks?**
Break-word looks good as currently implemented in the message tracker table. Does design need to add more specificity on min/max size for determining when the word breaks? 

**In the case of long strings, how would we like to truncate / expand that content?**

- Truncate: Click to expand the cell to reveal full field, click again to collapse?
- Future: I still love this [expand/collapse detail reference](https://murally.blob.core.windows.net/uploads/primedatainput6410/0-1679062572612.gif?se=2023-05-26T19%3A01%3A00Z&sp=r&sv=2018-03-28&sr=b&rscc=public%2C%20max-age%3D600&sig=wcXcywzQXEGDcq3cPOAFADbv4n%2BwYmrg%2BRruFMZSvXI%3D). Do you have any immediate reactions to building something like this?

**In the case of sticky headers, what color/styling should they have?**
I will capture answering this definitively in **Design: Standardize styling for the 3x table component variants #9460**, which will outline a final style, but for now, the light gray as implemented in the message tracker looks good!

**Comment by jillian-hammer** [comment]
Status: on track, ongoing coordination with @etanb

**Comment by etanb** [comment]
> In the case of triggering horizontal and vertical scrolling, what is the maximum height for scrollable and stickyHeader tables?
OK to proceed with 80v, is this something we can build the ability to tweak per instance or does it need to be standardized globally?

We can set a default height (there has to be one), but then allow the implementer to input a different height if they so wish.

> Do we want to all tables have a max height?
No, I think our table component should default to not scrolling and not having a max height. I think scrolll+sticky is a behavior you can toggle on/off. Does that work?

Yeah, absolutely! Just wanted to float the idea. The time a `max-height` is required is for scrolling + sticky header.

> In the case of long strings, how should we handle word breaks?
Break-word looks good as currently implemented in the message tracker table. Does design need to add more specificity on min/max size for determining when the word breaks?

Nope! All good, happy to keep the current iteration and make adjustments as needed.

> In the case of long strings, how would we like to truncate / expand that content?
Truncate: Click to expand the cell to reveal full field, click again to collapse?
Future: I still love this [expand/collapse detail reference](https://murally.blob.core.windows.net/uploads/primedatainput6410/0-1679062572612.gif?se=2023-05-26T19%3A01%3A00Z&sp=r&sv=2018-03-28&sr=b&rscc=public%2C%20max-age%3D600&sig=wcXcywzQXEGDcq3cPOAFADbv4n%2BwYmrg%2BRruFMZSvXI%3D). Do you have any immediate reactions to building something like this?

Unfortunately, that link you shared is broken for me. In regards to expanding/collapsing content, we'd then have to decide on a max height OR max character count (some limiter is required) for when expand/collapse should trigger. Definitely something we can do! Should be a separate feature request.

> In the case of sticky headers, what color/styling should they have?
I will capture answering this definitively in Design: Standardize styling for the 3x table component variants https://github.com/CDCgov/prime-reportstream/issues/9460, which will outline a final style, but for now, the light gray as implemented in the message tracker looks good!

Sounds good!

@jillian-hammer

**Comment by jillian-hammer** [comment]
I'm thinking about documenting these decisions in Tshering's existing Figma spec sheet so it's all in one place – thoughts @yudonoodles?

**Comment by jillian-hammer** [comment]
status: adding to figma and closing by eow 6/9

**Comment by yudonoodles** [comment]
@jillian-hammer Yes, makes sense to add it to the same spec doc.

**Comment by jillian-hammer** [comment]
status: complete

- Added agreed upon max height and word break specs to the [WIP spec sheet](https://www.figma.com/file/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?type=design&node-id=5414-39373)
- Added the truncation functionality as a separate feature request per Etan's recommendation, see: Truncate table content with expand/collapse behavior #9790

closing!
