### ISSUE TITLE
Create initial draft of UP Data Flow Blueprint

### ISSUE THREAD

**Issue by dylansmith-Nava** [CDCgov/prime-reportstream#9630]
## User story
As an RS teammate, I want to be able to clearly and easily visualize all the people, tools, and processes that are a part of the ReportStream Universal Pipeline system, so that I have a comprehensive view of how it works, and I know where new opportunities lie.

## Background & context
@jsutantio and @dylansmith-Nava conducted a major overhaul of the initial COVID service blueprint which can be found [in this Mural](https://app.mural.co/t/nava4113/m/nava4113/1672148125717/f376adefc22f136c60e40cb9f60b1b74ef4ee43d?sender=ufb3824a0e63fafb0304f5774). As the ReportStream team migrates ReportStream to the Universal Pipeline (UP), the blueprint now needs to be updated to show UP processes and reflect the "delta" from COVID processes.

We will need to show 1 initial scenario (as other major scenario [Migrating from COVID to UP] has too many unknowns):
- Scenario 1: Onboarding straight to the UP

## Working links
- [COVID Service blueprint](https://app.mural.co/t/nava4113/m/nava4113/1672148125717/f376adefc22f136c60e40cb9f60b1b74ef4ee43d?sender=u791b7d4d34761ac59b672214) This is the service blueprint mural that has been widely distributed and linked to.
- [Service blueprint Workspace](https://app.mural.co/t/nava4113/m/nava4113/1681488534126/acccd696c031a19d3335e62204ece296ef483b9e?sender=u8e85df6f9eec764c4bfd6788) This is the temporary space that contains drafts and in progress work.
- [Interest & Intake Self-Service Opportunities Mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1684158407022/77a87b428e131bcac8a4f63240373ce25a6ba7cf?sender=ufb3824a0e63fafb0304f5774) This is WebEx Mural that focuses on the "Intake" section and opportunities there

## Acceptance criteria
- [x] Documented, linear journey of UP RS data from user onboarding to maintenance following COVID blueprint paradigm
- [x] Display "delta" processes and steps that will be undertaken as the team migrates to UP
- [x] Allows for space for the following additions (to be detailed in later tickets): pain points and drop-out nodes complemented by opportunity areas, and. a more comprehensive lists of tools and features 

Not within scope:
- [ ] Share-out to team for feedback (will be written out in next ticket)
- [ ] Copy and paste below current Service Blueprint Mural -- will come after pressure-testing
- [ ] Precise timing/ durations for each step
- [ ] Documenting "before onboarding" steps (e.g., patient testing/ test submission)
- [ ] Documenting "post onboarding" step specificities (e.g., specific bugs and errors during maintenance, etc.)
- [ ] Conceptual features based on opportunity areas

**Comment by dylansmith-Nava** [comment]
@lizzieamanning @jsutantio here's the new ticket for the UP data flow blueprint! Please let me know what you think and if there are any updates that need to be made here.

**Comment by lizzieamanning** [comment]
@dylansmith-Nava @jsutantio what is the lift for completing all 3 scenarios outlined in this ticket? Does it need to be broken up further? Who will be owning this?

**Comment by dylansmith-Nava** [comment]
@lizzieamanning good point - I think @jsutantio and I can scope our effort for all 3 scenarios. I think it'll be beneficial to show all three, though, and my intuition tells me that it's possible to do them all in this ticket because of our work on the COVID blueprint. I am owning this ticket and Jess is supporting / co-owning the blueprint like last time.

**Comment by dylansmith-Nava** [comment]
Jess updated that the Platform team does not have a comprehensive grasp on what the migration plan would be and wouldn't know until there is some established level of robustness in UP. So ticket was updated just for Scenario 1 and Scenario 2 will come later

**Comment by dylansmith-Nava** [comment]
Initial draft is completed and ready for a team feedback cycle (to be written in another ticket). Link: [this Mural](https://app.mural.co/t/primedatainput6410/m/nava4113/1681488534126/acccd696c031a19d3335e62204ece296ef483b9e?sender=ufb3824a0e63fafb0304f5774) -- it is "ver 2.7 (UP)" in outline
