### ISSUE TITLE
Update Content and Link on API Programmer's Guide Card on Resources Page

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9642]
## Problem statement

As a user, I would like the content on the website to best describe what it contains. Since the API Programmer's Guide has been updated, the text on the **API Programmer's Guide card** on the [Resources page](https://reportstream.cdc.gov/resources) is outdated and needs to be updated.

## What you need to know

- [Resources page](https://reportstream.cdc.gov/resources)
- Existing card:
  - ![Screenshot 2023-05-30 at 8.21.07 AM.png](https://images.zenhubusercontent.com/637d310dba428f3e3d55c9db/5899ffc3-a845-4caa-b7c1-ef3a7803e724)
- The text currently reads: 
  - > **API Programmer's Guide**
   Set up an ELR connection to automatically report all disease data to public health departments.
- The text should now read:
  - > **ReportStream API**
  Learn about our API and how to set up your connection for reporting data to public health departments.

## Acceptance criteria

- [x] Text and title on API Programmer's Guide card now matches the new text written above.
- [x] Resources Page block of "API Programmer's Guide" links to the main page of the new Web Version of the API Programmer's Guide
- [x] Ensure that users with old bookmarks to the old API Programmer's Guide page will be redirected to the new API Programmer's Guide page

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@chris-kuryak new content added - note that I updated the card title as well, so it matches the page it goes to

**Comment by chris-kuryak** [comment]
Awesome @audreykwr ! Will slot it into an upcoming sprint.
