### ISSUE TITLE
Add csirt@cdc.gov to our security scanning results

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#9651]
When github notices a security issue it should send csirt@cdc.gov a notification along as one to our team

**Comment by boris-ning-usds** [comment]
Jeremy, can you make sure Denis has the proper permissions (possibly admin) to see into the security scanning settings? I don't usually step into this repo enough to know enough about this requirement.

**Comment by dkrylovsb** [comment]
@jeremy-page It appears GitHub does not have a way to send alerts to an arbitrary email address, unless that address is a member of GitHub.
