### ISSUE TITLE
[BUG] Fix the File Validator Statistics chart in App Insights Prod Dashboard

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9652]
## Describe the bug
The File Validator Statistics chart in the [App Insights Dashboard](https://portal.azure.com/#@cdc.onmicrosoft.com/dashboard/arm/subscriptions/7d1e3999-6[…]d/providers/microsoft.portal/dashboards/pdhprod-rs-dashboard) is not working.

## Impact on ReportStream
RS team members have no visibility into File Validator usage.

## Steps to reproduce
1. Go to [App Insights Prod Dashboard](https://portal.azure.com/#@cdc.onmicrosoft.com/dashboard/arm/subscriptions/7d1e3999-6[…]d/providers/microsoft.portal/dashboards/pdhprod-rs-dashboard)
2. Go to File Validator Statistics chart
3. It displays an error

## Expected behavior
It should not display an error and should display the File Validator Statistics

## Resources
![Screenshot 2023-05-31 at 9.48.35 AM.png](https://images.zenhubusercontent.com/637d310dba428f3e3d55c9db/929f6070-fbb4-41e9-902d-96360da921e9)

#### Desktop (please complete the following information)
 - OS: Mac
 - Browser Chrome
 - Version

**Comment by lucasdze** [comment]
Issue fixed
![image](https://github.com/CDCgov/prime-reportstream/assets/50645318/98629e15-886a-4ea2-8c87-4b619100d94c)

**Comment by chris-kuryak** [comment]
Thank you!
