### ISSUE TITLE
SD Onboarding - Set Up Connection

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#9657]
### Acceptance Criteria 

CONNECTION TYPE:
If SFTP:
- [ ] 1. Submitted host name for CDC whitelisting
- [x] 2. Retrieve username and PW from STLT 
- [ ] 3. Determine if they have public key authentication 
- [ ] 4. Add private info to Keybase 
- [ ] 5. Create Azure secret staging 
- [x] 6. Create Azure secret production 
- [ ] 7. Test connection

**Comment by oslynn** [comment]
SD needs only positive results to route to them.  We need qualityFilter to filter all negative results out.

**Comment by oslynn** [comment]
Done.
