### ISSUE TITLE
Replace alerts with Tip Callout Component

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9689]
## Problem statement

A new Tip Callout component was created and needs to be added into the existing pages that use it.
This ticket is to standardize that component and add it to the API Documentation Pages, File Validator, and Public Key tool.

## What you need to know

Tip callout components to update to the new standard component (alert-tip):

-  API Documentation Pages
-  File Validator
-  Public Key Tool

## Acceptance criteria

- [ ] Create a Tip Callout component that can be re-used around the site
- [ ] API Page: Replace alerts with Tip Callout component
- [ ] File Validator Tool: Replace alerts with Tip Callout component
- [ ] Public Key Tool: Replace alerts with Tip Callout component

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
Needs to determine with Etan if a completely new component was created for his version, or if he dressed up an existing USWDS component. Will add as an agenda item to upcoming WebX engr sync.

**Comment by Andrey-Glazkv** [comment]
Need to bring it up in Eng sync 06/13 to discuss it with the team

**Comment by chris-kuryak** [comment]
Carry over to next sprint. Will not finish this sprint.

**Comment by chris-kuryak** [comment]
Consensus was reached around how to solve/approach this solution from an engineering perspective.
Will be wrapping around an existing Trussworks component.

**Comment by chris-kuryak** [comment]
@jpandersen87 After creating this Tip Callout Component, we will need to go back in and replace the other areas it is used (File Validator Tool and Public Key Tool) on the site, correct? Meaning, create a separate ticket for that work in the future?

**Comment by chris-kuryak** [comment]
From @jpandersen87 : 

> PR under review also covers updating the two pages to use the new alert

I have updated the AC's accordingly to reflect that.
