### ISSUE TITLE
Add analytics tracking functionality to USLink / Button components

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-reportstream#9692]
## Problem statement

Currently have added Web Analytics tracking to API Programmer's Guide download link and would like to add analytics tracking functionality to the USLink / Button components.

## Acceptance criteria

- [ ] Add function to add analytics tracking functionality to the USLink / Button component when applicable.
- [ ] Replace function being called in the API Programmer's Guide download link to use the new function.

## To do

- [ ] ...

**Comment by jpandersen87** [comment]
Handled via #11964
