### ISSUE TITLE
VT - Discontinuing Intrivo

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#9695]
## Problem statement

User wants to discontinue Intrivo for Vermont.

*user correspondence*

Hello Report stream team,

We got an email from the Vermont Department of Health, and they are requesting us a discontinuation in self-reported covid results from Intrivo. Would you be able to help us with this request?

The content down below is the original email copy.

Thanks,
Chang

## What you need to know

*Vermont to Intrivo correspondence* 

Hello,

I am forwarding the below email requesting a discontinuation in self-reported covid results from Intrivo. I had sent the below email to addresses that I have been informed are no longer contacts for Intrivo.

Thank you for your help with the below request.

Andrew Gross, MPH | Health Data Administrator
Division of Health Statistics & Informatics
Vermont Department of Health
108 Cherry St, Burlington, VT 05402

## Acceptance criteria

- [ ] ...

## To do

Discontinue Reporting

**Comment by Jcavallo7** [comment]
Apologies! I just updated it.

**Comment by LaFreda1** [comment]
Stop sending al data from Intrivo

**Comment by LaFreda1** [comment]
@Jcavallo7 Please confirm with Vermont that they are no longer receiving ANY self-reported covid results, per ticket #9506. If so, we can close this ticket.

**Comment by kant777** [comment]
@LaFreda1 Looks like we can close this
