### ISSUE TITLE
CO - FIltered Reports

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#9697]
## Problem statement

CO Filtered Results for the past week

## What you need to know

![image.png](https://images.zenhubusercontent.com/62828ac9597e3bae41382df7/4e8210dc-5871-4e8b-9439-32fbb605bea1) [Links to documents, workflows, or list of key people and contact info]

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by jalbinson** [comment]
@LaFreda1 Can you clarify what I'm supposed to be working on for this ticket?

**Comment by Jcavallo7** [comment]
Hi, yes apologies, this was received in the RS email box, it was brought to my attention to create the ticket in zenhub for it, not exactly sure as Brick used to handle these before, but I'm guessing It's for updating senders.

**Comment by LaFreda1** [comment]
@Jcavallo7 thank you! @jalbinson Brick is a good resource for this ticket!

**Comment by jalbinson** [comment]
Hi @brick-green, could you help point me in the right direction with this ticket?

**Comment by brick-green** [comment]
@jalbinson uhhhhh, not sure what this is about. @Jcavallo7 who sent that to the RS email box?

**Comment by brick-green** [comment]
It came from metabase to the RS inbox?

**Comment by Jcavallo7** [comment]
yes

**Comment by brick-green** [comment]
hmmm, I don't know who set that up or why. So I'm not sure what work should be taken as a result...

**Comment by jalbinson** [comment]
@LaFreda1 Can this be closed? It doesn't seem like we have any clear direction on what needs to be done.

**Comment by LaFreda1** [comment]
@jalbinson I'll un-assign you and see what we need for this ticket.

**Comment by chris-kuryak** [comment]
Per Sharon - can be closed
