### ISSUE TITLE
Create a new table to hold the metadata for the UP metadata

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#9702]
### User Story
As a report stream developer, I would like the ability to store metadata for reports flowing through the universal pipeline

### Description/Use Case
Similar to the covid pipeline, having access to the metadata for reports going through the UP will be necessary to unlock reporting features.

### Dev Notes
- Link to design [doc](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/proposals/0020-universal-metadata-search/0020-universal-metadata-search.md#a-metadata-table-with-a-jsonb-column)

### Acceptance Criteria
- [ ] A new table called `metadata` exists with the following schema:
  - [ ] `metadata_id` (UUID, primary key)
  - [ ] `sender_id` (UUID, foreign key to setting)
  - [ ] `report_id` (UUID, foreign key to report_file)
  - [ ] `report_index` (Int)
  - [ ] `message_id` (UUID, indexed, foreign key to `message`)
  - [ ] `metadata` (JSONB)
  - [ ] `created_at` (Datetime, indexed)
  - Indices
    - [ ] (`report_id`, `report_index`)

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9702?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimmyfagan @luis-pabon-tf @mkalish @victor-chaparro
