### ISSUE TITLE
Add functionality to create a FHIR bundle with PHI removed from an existing FHIR bundle

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#9704]
### User Story
As a report stream developer, I would like to easily remove PHI from a FHIR bundle

### Description/Use Case
The metadata that gets written to the DB needs to not have any PHI in it since it is persisted, so there needs to be a convenient way to transform a FHIR bundle into one without any PHI

### Risks/Impacts/Considerations
- Should favor removing data from the bundle in order to be safe

### Dev Notes
- This can likely be done with a FHIR transform
- The existing [`getDeidentifiedResultMetaData`](https://github.com/CDCgov/prime-reportstream/blob/9eb5a9cdcd4f638153a551fc41e930b23e53c49d/prime-router/src/main/kotlin/Report.kt#L804) can be referenced for getting started
- Any field that appears on any list we have for PII unless it is currently stored in the covid metadata

### Acceptance Criteria
- [ ] A mechanism exists to create a FHIR bundle from existing one with the PHI removed
- [ ] Reviewed list of data we decided are PII/PHI with engagement team

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9704?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimmyfagan @luis-pabon-tf @mkalish @victor-chaparro
