### ISSUE TITLE
NC Onboarding Operations

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#971]
The following items, generally in order, must be completed to successfully onboard a receiver to ReportStream:

* [ ] Added to organization.yml
* [ ] Added to organizations-local.yml
* [ ] Added to staging settings table
* [ ] Added to prod settings table
* [ ] Added at least one receiver
* [ ] Added OKTA group to download site
* [ ] Added customers to OKTA group for download site
* [ ] Is customer contact made?
* What doc format are we supporting for the receiver (HLV, CSV, other)? **(Add comment below)**
* What transport(s) are we supporting for the receiver (SFTP, other)? **(Add comment below)**
* [ ]  Got credentials?
* [ ] Tested ELR connection locally?
* [ ] Tested ELR connection from Azure?
* [ ] Has the receiver accessed the download site?
* [ ] Has the receiver been sent at least one test file?
* [ ] Has the receiver signed off on file formatting?
* [ ] Are there labs sending data?
* [ ] Has the receiver confirmed receipt of the data?
* [ ] Have the files processed successfully?
* [ ] Are we in production?

**Comment by jlusds** [comment]
NC's ELR documentation from the intake form:

https://cdc.sharepoint.com/:w:/r/sites/DY-PRIME/_layouts/15/Doc.aspx?sourcedoc=%7B7E0046A3-8ECB-40EF-8371-7A9EB60FFCE1%7D&file=Subset%20of%20ELR%20intro%20email%20from%20NC.docx&action=view&mobileredirect=true

**Comment by jlusds** [comment]
Asked for SFTP

**Comment by jlusds** [comment]
Sprint 22 goal - figure out plan

**Comment by MauriceReeves-usds** [comment]
Zero batch file for days with no records and batching by CLIA

**Comment by anshulkumar-usds** [comment]
3/3: NC submitted another intake form. They seem to be interested in RS and SR. Anshul checking with NC to setup a meeting.

**Comment by anshulkumar-usds** [comment]
3/8: Checked with NC again, no update from State.

**Comment by anshulkumar-usds** [comment]
No response from state. Iceboxing

**Comment by anshulkumar-usds** [comment]
3/31: Checked in with NC on HL7 questions and for next steps with connecting via their SFTP and HIE.

**Comment by anshulkumar-usds** [comment]
4/6: Megan still following up with NC. NC-HIE mentioned they only onboard labs and vendors over SFTP; RS is neither. NC continues to recommend PHINMS.

**Comment by sarahnw** [comment]
closing will create a new one when NC onboards
