### ISSUE TITLE
IA recommendation refinement

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#9712]
## User story
As a user, I want the ReportStream website to match my mental model.

## Background & context
We don't know if the site is structured in a way that allows users to find what they need and complete the task at hand. We don't have a scalable framework for launching and housing new features. After coming up with a main research synthesis, we need to refine category names and category items based on those research results to help with navigation development.

## Working links
[Mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1683043148179/c9163e9d9fe8e5dfe1ce2f613d226ae99d4f3f29?sender=uc55a7af3b66977fba12f5528)

## Acceptance criteria
- [x] Category names and items drafted and shared with WebX design

**Comment by lizzieamanning** [comment]
@audreykwr How is this work different from the IA summary deck you shared in the design channel?

**Comment by audreykwr** [comment]
That was focused on research synthesis, this is getting into application. As nav design work begins, this is to hone actual category/section names and refine what it is them since the synthesis only included the cards from the sort as the sources. Let me know if I can explain more. This is referenced in the slide slide of the summary deck as well.

**Comment by lizzieamanning** [comment]
@audreykwr ok that helps. Can you include a more defined AC? I think that's what threw me off. It doesn't sound like the AC here is a summary, but rather the actual category/section names.

**Comment by audreykwr** [comment]
updated to be more specific! Let me know what else I can do to make this clearer

**Comment by audreykwr** [comment]
Application notes added to [this deck](https://docs.google.com/presentation/d/1d8GA7puc3IGCuHOiFgBUSCgGsCNYAhS3cVSr1OdNUkI/edit#slide=id.g253db5ed7ee_0_31)

[Site map rec in this sheet](https://docs.google.com/spreadsheets/d/1xhnqSoRBfkVFrLR6sgM6QgW1kav7g_FyUkPykPIjOMk/edit#gid=1424556959)
