### ISSUE TITLE
Update RS's Figma's Styling in preparation for website redesign work

### ISSUE THREAD

**Issue by yudonoodles** [CDCgov/prime-reportstream#9733]
## User story

As a designer, I want to have up-to-date styles so that I can apply those styles consistently across design and thereby maintain good design practice. In doing so, collaboration with engineer would go smoothly as final deliverables match ReportStream's USWDS styling. 

## Background & context

As we approach the website redesign work in the third quarter, it will be pertinent to make sure that we can design wireframes in an effective and consistent manner, leveraging USWDS's style library and linking them appropriately so that we create consistent and scalable deliverables.

This not only saves time for designers but improves collaboration with engineers in the long run by speaking the same design system language and building a shared understanding together. 

## Working Links
[Figma USWDS Library](https://www.figma.com/file/dCcut3bd9OZ06Co4Wkfc6c/Reference-%7C-Trussworks-3.0-USWDS-Library?type=design&node-id=0%3A6250&t=BTpEA42WIx9IDASB-1)

## Acceptance criteria

-   [ ] Update Text Styles
-   [ ] Update Color Styles

**Comment by jillian-hammer** [comment]
thanks for putting this together @yudonoodles! excited for you to own this work. 

for visibility, can you add more specificity by adding the figma working links & listing which text & color styles you have in mind (when you have a chance)?

**Comment by jillian-hammer** [comment]
just added the label `needs refinement` so we can remember to assign points before the work is picked up.

**Comment by yudonoodles** [comment]
Archiving since it's no longer needed.
