### ISSUE TITLE
Create/update existing components for website redesign  

### ISSUE THREAD

**Issue by yudonoodles** [CDCgov/prime-reportstream#9734]
## User story

As a designer, I want to have flexible and usable ui components to help build out wireframes in a consistent and effective manner. This not only improves collaboration between designers as they work off of the same template/shared assets, but also improve collaboration with engineers as there will be fewer missteps or misalignment as far as what a given component looks like and how it behaves. 

## Background & context

As we approach the website redesign work in the third quarter, it will be pertinent to make sure that we can design wireframes in an effective and consistent manner. This work to update/create ReportStream's component library would ensure that we can build designs in a consistent and scalable way.

## Acceptance criteria

-   [x] Card component
-   [x] Accordion 
-   [x] Button w/icon

**Comment by jillian-hammer** [comment]
thanks @yudonoodles! just added the `needs refinement` label  to provide wiggle room in case you find more components in addition to the card component + as a reminder to assign points before finalizing the scope and picking up the work.
