### ISSUE TITLE
Test Forcing TLSv1.2 for REST Transport

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#9735]
Stephen Nesman is asking for our review on PR#9515 to force TLSv1.3 with fallback to 1.2 (only) for REST transport. We currently have three REST receivers OK, NY & WA. We need to validate that each can use TLS1.3 or 1.2 and test sending a message to their environment

https://github.com/CDCgov/prime-reportstream/pull/9515

**Comment by jalbinson** [comment]
I ran the following command to test whether TLS1.2 was supported by NY
```
openssl s_client -connect api2.health.ny.gov:443 -tls1_2
```

Although the session was not opened because NY requires a client certificate, it does appear that TLS 1.2 version is supported by NY.
