### ISSUE TITLE
Arkansas Onboarding - Go Live Coordination

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#9764]
### Acceptance Criteria 
- [ ] Confirmed with STLT when they want to start receiving (date) 
- [ ] Removed quality filter in prod settings = allowNone() 
- [ ] Removed quality filter in staging settings = allowNone() 
- [ ] Set Customer status = active 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with receiver 
- [ ] RS team member who originates this ticket: add any dependencies, as needed 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Receiver" and state label 
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by sliu1000** [comment]
Update from AK user:

I saw some messages last week.  There are a few things erroring out:

MSH-19: Nobody else is sending this.  Can you leave this field blank?

OBR-16/ORC-12: Copy NPI&NPI&ISO into the 9th component.  Blank out the 10th component.

OBX-18:    Move the first component to the 19th component and the second component to the 20th component.

Regards,

Eddie
