### ISSUE TITLE
Arkansas Onboarding - Validate Test Data

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#9767]
### Acceptance Criteria 
- [ ] Created and sent data using fake data generator 
- [ ] Created and sent data using synthesized data generator 
- [ ] Confirmed with STLT that data passes validation 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with receiver 
- [ ] RS team member who originates this ticket: add any dependencies, as needed 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Receiver" and state label 
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by GilmoreA6** [comment]
Reply from Eddie Butler (AR DOH) on test data.

"Hi all.

 

The message looks very sound, containing all the required fields as far as I can tell.  Would love to get some actual production data flowing into Staging so we can further evaluate.

 

Thanks,

Eddie"
