### ISSUE TITLE
Add tracking of Referring URL to Website Sessions

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9780]
## Problem statement
As a ReportStream product manager, I would like the ability to know where our website traffic is coming from to help determine how users are finding our website. Additionally, knowing how much website traffic comes from organic searches could be a good proxy for determining how many external (non-RS team members) are visiting the website. This will help us learn more about our users and potentially help make product decisions in the future.

The website analytics (in Azure Application Insights) for the ReportStream website currently do not capture the referring URL. In other words, we don't know where our website traffic is coming from.

Therefore, we should start tracking where are traffic originates so we can visualize it on the Azure Application Insights Dashboard.

## What you need to know
- It appears we may need to create a custom event triggered by the beginning of a session
- [Potentially helpful website](https://www.meziantou.net/application-insights-track-http-referer.htm)
- ...

## Acceptance criteria

- [ ] When a visitor comes to the ReportStream website from another URL, it is captured and can be queried in Azure Application Insights
- [ ] An Azure Application Insights Dashboard visualization (perhaps a stacked bar graph) to show the number of sessions split by referring URL over the past 90 days, grouped by 7 day buckets 

## To do

- [ ] ...

**Comment by chris-kuryak** [comment]
Postponed until we decide if needed in the future.

**Comment by KeithNava** [comment]
related to https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/9692 and https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/10543

**Comment by chris-kuryak** [comment]
No longer needed through Azure. Google analytics should be tracking.
