### ISSUE TITLE
Migrate frontend to vite as bundler

### ISSUE THREAD

**Issue by jpandersen87** [CDCgov/prime-reportstream#9785]
Since ejecting from CRA our bundling capabilities have been hampered (as dealing with the ejection scripts and webpack is complex). We need to move the frontend to a new and active bundler that functions similar to CRA (thus requiring minimum project changes). Vite appears to fit the requirements.

Acceptance criteria:
- [ ] localdev mode functional
- [ ] typescript and eslint rules enforced in localdev
- [ ] storybook mode functional
- [ ] jest testing functional
- [ ] tests pass
- [ ] MD/MDX-based pages functional
- [ ] chromatic build functional
- [ ] deployment build functional (use trial as deployment test)
- [ ] typescript rules enforced in build

**Comment by chris-kuryak** [comment]
Awaiting final PR review from Keith
