### ISSUE TITLE
Process sample HL7v2 message from CDC ELIMS Rhapsody System

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#9910]
### User Story

As ReportStream, I need to verify I can process a sample HL7v2.5.1 message from CDC ELIMS Rhapsody and that it gets routed to the correct partner.

### Description/Use Case

We need to run a sample message from Rhapsody and document any differences. The output message that gets sent to a receiver should be identical to the message that was received. It should also get routed to the receiver that the filename of the received message indicates it should get routed to.

### Risks/Impacts/Considerations

We do not necessarily know who the MvP receiver will be, so we can't be 100% sure of the routing at this stage. But, at the very least, we should look at the filename of the sample message and then the message contents and assess our confidence level regarding the accuracy of the routing.

### Acceptance Criteria

- [x] Documented differences between received message and output message
- [ ] Documented differences between actual vs expected routing - Arnej approved skipping for now
- [x] Other documents sent by Julie Crowder evaluated and appropriate actions are taken/planned
- [x] Created follow-up stories to complete MvP goal and reviewed with product

**Comment by arnejduranovic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9910?planning-poker) with Zenhub @jack-h-wang @mkalish @thetaurean @JessicaWNava @jimmyfagan @victor-chaparro @luis-pabon-tf

**Comment by jimmyfagan** [comment]
In case it's useful, linking to a ticket ([#8497](https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/8497)) that _may_ be relevant to the routing piece of this.

**Comment by JessicaWNava** [comment]
Ticket created for follow up work here: https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/10027
