### ISSUE TITLE
More CA receiver transforms

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#9923]
### User Story

As CA, I want to receive dates in my local timezone and receive dates that are consistent with Covid results sent through the Covid Pipeline, so that dates sent through both pipelines match.

### Description/Use Case
CA dates are not being converted to CA's local timezone. Simple Report subtracts 15 minutes from dates being sent to us through the Covid pipeline. CA wants Simple Report to stop doing that for them, but Simple Report can't just turn it off for every message we receive. They will stop doing this for reports sent through the UP, but we will have to continue doing this in the UP to keep dates consistent across the pipelines. We will turn this off once we start routing the Covid results through the UP.

### Risks/Impacts/Considerations
- Dates sent through both pipelines will not match

### Dev Notes
- Add a Simple Report sender transform to subtract 15 minutes from DiagnosticReport.issued | effective and Specimen.collected dates

### Acceptance Criteria

- [x] Dates are converted to CA's local timezone
- [x] 15 minutes are subtracted from the dates listed above

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9923?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimmyfagan @luis-pabon-tf @mkalish

**Comment by bishoyayoub** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9923?planning-poker) with Zenhub @victor-chaparro
