### ISSUE TITLE
Signetic requesting Data Validation for CA

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#9926]
## **Problem Statement**

We received a request in the ReportStream inbox from Signetic regarding data validation for CA.

## **What you need to know**

Email received from Poonam Pahari (poonam@signetic.com):

>  We are seeking verification for the state of California and would like to confirm if we can send test data for review. Please let us know if there have been any changes to the process. 

## **Acceptance Criteria**

- [ ] Perform data validation with Signetic and confirm they can successfully send to CA.

## **To Do**

Please notify the user if there have been any changes to the data validation process since they last worked with us in Jan/Feb 2023.

## **Additional Comments**

None at this time.

**Comment by oslynn** [comment]
Good afternoon, Ellaison, Vanessa,

Hope you all are doing well.  One of our sender, Signetic Lab, would like to start sending test result to CA.
It past ReportStream Validation and want to validate with CA Department Of Health.  Would you please
validate the attached Sample Test Result (negative and positive) messages.  If everything is good, I will enable
ReportStream to route their test result to CA.

My you have a wonderful weekend.

**Comment by oslynn** [comment]
CA doesn't accept their message since their CLIA number is under Certificate Type: Waiver.  Therefore, I will close this ticket.
