### ISSUE TITLE
Password Expiration Warning

### ISSUE THREAD

**Issue by OHoward2023** [CDCgov/prime-reportstream#9934]
## Problem statement

The password has expired and needs to be changed for "dhhs.elr.cdc_prime.prd" account.

## What you need to know

- Your Password Has Expired and Must Be Changed Now

We require that passwords be changed every 356 days and your password has now expired. Your "dhhs.elr.cdc_prime.prd" account will not enjoy full access to our system until you sign on with your old credentials and change your password.

Please use the following URL to connect to our system and enter your existing username ("dhhs.elr.cdc_prime.prd") and old password when prompted.

( https://nhftp.nh.gov/human.aspx?InstID=8570&username=dhhs.elr.cdc_prime.prd )

You will be required to change your password immediately after signing on.

If you need assistance, please contact DoIT Ops SysAdmin Windows at 603-271-7555 / helpdesk@doit.nh.gov.

Regards,
State of New Hampshire  - Secure File Exchange Notification Service - (https://nhftp.nh.gov)

## Acceptance criteria

- Update Site
- Update Azure Vault

## To do

- Change the password.

**Comment by oslynn** [comment]
NH PW does not expire.
