### ISSUE TITLE
Add Github Page with JWT Error Codes/Guidance

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9945]
## Problem statement

The Platform team recently created some new error codes that can help a user self-service their own issues regarding authenticating their connection when sending data to ReportStream.

## What you need to know

- The new error codes and how they will function on the command line are found in #8642.
  - The command line error will function as follows: (a) User receives error and (b) command line response returns a link (with anchor link) to a specific location on a Github page (to be created in this ticket) explaining the error in more detail.
  - There are several error code possibilities, the content of which can be found in #9546.
- So the purpose of this ticket is to add instructions/assistance that will help a user self-service their own issues.
- These new error codes are specific to the API Programmer's Guide Setting Up your Authentication -> Method 1 -> Step 2 (Generate a signed JWT)

## Acceptance criteria

- [ ] Create publicly viewable Github page on the CDC Reportstream Github Wiki that includes the content and formatting found in #9546
- [x] Ensure there is a link from Error page on Github page to API Prog Guide instructions on how to generate the token
- [x] Content is reviewed by Audrey Ross
- [x] Inform Chris Kuryak and Platform team (Michael Kalish and Bishoy Ayoub) of new page and anchor links

## To do

- [ ] ...

**Comment by audreykwr** [comment]
PR https://github.com/CDCgov/prime-reportstream/pull/10073#pullrequestreview-1495263048

**Comment by audreykwr** [comment]
Merged (thanks, @mkalish!) 

Error code links:

- [Expired token](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/examples/generate-jwt-python/jwt-errors.md#expired-token)
- [Unsigned JWT](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/examples/generate-jwt-python/jwt-errors.md#unsigned-jwt)
- [Malformed JWT](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/examples/generate-jwt-python/jwt-errors.md#malformed-jwt)
- [Invalid scope](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/examples/generate-jwt-python/jwt-errors.md#invalid-scope)
- [No valid keys](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/examples/generate-jwt-python/jwt-errors.md#no-valid-keys)
- [No matching organization](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/examples/generate-jwt-python/jwt-errors.md#no-matching-organization)
- [Missing JWT](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/examples/generate-jwt-python/jwt-errors.md#missing-jwt)
- [Missing scope](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/examples/generate-jwt-python/jwt-errors.md#missing-scope)

CC @chris-kuryak @bishoyayoub
