### ISSUE TITLE
Blockframes: Sub-landing page (Onboarding sender)

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#9955]
## User story

As a WebX team member, I want to see the ReportStream website designed iteratively, starting from blockframes, so that the team can continuously align on the scope and anticipate design/content/engineering needs early in the website redesign process. 

## Background & context

The WebX design team creating blockframes for the new ReportStream website redesign. We will work in a templated approach in an effort to streamline designing pages that have a similar format. The **sub-landing page** page template will use the Onboarding sender core model outline as a basis for blockframing. These explorations in a lo-fi blockframe format allow us to explore different solutions and align on an approach across disciplines prior to moving farther into the design process.

## Open questions

-  At what touchpoint(s) should content review? 

## Working links

-   Core model outline: [Onboarding sender](https://docs.google.com/document/d/1NYs6i5C6IYTlsrdcsOS_2E2yUGLczXaZF7sVZdfziMI/edit?usp=sharing)
-   [Site update plan](https://docs.google.com/spreadsheets/d/1xhnqSoRBfkVFrLR6sgM6QgW1kav7g_FyUkPykPIjOMk/edit#gid=0)
-   Figma: [Blockframe working space](https://www.figma.com/file/86JATe4hOwPfihwwloM5b8/Blockframes?type=design&node-id=0%3A1&mode=design&t=DbHTHvihgkt9JfRE-1)
## Acceptance criteria

- [x] Blockframes capture general layout of content & components
- [x] Blockframes build upon content sequence and structure identified in the core model synthesis 
- [x] Review with design and/or design lead

**Comment by yudonoodles** [comment]
Completed the block frame and shared it with design team for review (Jillian, Audrey and Lizzie). Pinged them via slack.

**Comment by yudonoodles** [comment]
- Reviewed and updated design based on Jillian's feedback. 
- Was able to show the design to Lizzie M. during 1-1 today. Lizzie will create a document/mural to log questions or ideas that crop up as we work on pages. 

Next up, @audreykwr will review the design and leave feedback before showing it to product and eng.

**Comment by yudonoodles** [comment]
Created [10197](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/10197) as a follow-up to this one: Review completed block frames including this one referred to as a "sub-landing page," but specifically done using outline for onboarding senders.
