### ISSUE TITLE
Add link in API Programmer's Guide to new JWT Error Codes

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9956]
## Problem statement

The Platform team recently created some new error codes that can help a user self-service their own issues regarding authenticating their connection when sending data to ReportStream. This is found in #8642

## What you need to know

- The new error codes and how they will function on the command line are found in #8642.
  - The command line error will function as follows: (a) User receives error and (b) command line response returns a link (with anchor link) to a specific location on a Github page (to be created in this ticket) explaining the error in more detail.
  - There are several error code possibilities, the content of which can be found in #9546.
- So the purpose of this ticket is to add a link from the [API Programmer's Guide](https://reportstream.cdc.gov/resources/api) to the JWT Token Generation Error codes that are on the new Github page #9945
- These new error codes are specific to the API Programmer's Guide Setting Up your Authentication -> Method 1 -> Step 2 (Generate a signed JWT)
- The content for this change should be found in [API guide change tracker.docx](https://docs.google.com/document/d/1JJoj_c_MfZEj-TGdR1wx0aXkxKDEO7Zh/edit) which was from #9546
  - Go to : Getting started > Setting up authentication > Method 1 > Step 2
  - New Content per [API guide change tracker.docx](https://docs.google.com/document/d/1JJoj_c_MfZEj-TGdR1wx0aXkxKDEO7Zh/edit) ![Screenshot 2023-07-26 at 12.45.55 PM.png](https://images.zenhubusercontent.com/637d310dba428f3e3d55c9db/d9c39081-ee2c-4c4f-8454-f64ea8ee200d)

## Acceptance criteria

- [x] Update content on website [API Documentation](https://reportstream.cdc.gov/resources/api/getting-started) found in Getting Started > Setting up authentication > Method 1 > Step 2 of the [API guide change tracker.docx](https://docs.google.com/document/d/1JJoj_c_MfZEj-TGdR1wx0aXkxKDEO7Zh/edit) to link to [this page](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/examples/generate-jwt-python/jwt-errors.md)
- [x] Ensure link out to Github is treated as a external link with the appropriate "external link" icon
- [ ] QA from Audrey (Content Specialist)

## To do

- [ ] ...

**Comment by audreykwr** [comment]
I think because I'm not added as a reviewer in the PR I can't approve/comment there, but looks good to me! Thanks!
