### ISSUE TITLE
Rotate staging SA access key

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#9961]
Find and replace the leaked SA access key in all locations. The key was[ leaked here](https://github.com/CDCgov/prime-reportstream/actions/runs/5260484606/jobs/9507440227#step:5:32)

https://learn.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal

**Steps:** 

**1- Manually otate the key in Azure: this will create a new primary key**
	https://portal.azure.com/#@cdc.onmicrosoft.com/resource/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourceGroups/prime-data-hub-staging/providers/Microsoft.Storage/storageAccounts/pdhstagingstorageaccount/keys

  **2- Replace the the functionapp storage account connection string   AzureWebJobsStorage**
https://portal.azure.com/#@cdc.onmicrosoft.com/resource/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourceGroups/prime-data-hub-staging/providers/Microsoft.Web/sites/pdhstaging-functionapp/configuration

**Comment by lucasdze** [comment]
Successfully rotated the SA access key in staging along with the FA connection string
