### ISSUE TITLE
Reduce tech debt and code smells in UP "FHIR engine"

### ISSUE THREAD

**Issue by jimmyfagan** [CDCgov/prime-reportstream#9981]
### User Story
As a steward of the ReportStream code base, I want to reduce warnings and code smells in the "FHIR Engine" modules, so that SonarCloud will more easily identify potential issues in the future, and the code will be safer and more readable.

### Description/Use Case
Currently, there are many warnings and ["code smells"](https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&sinceLeakPeriod=true&id=CDCgov_prime-data-hub) in our code base. This story shouldn't be meant to address _all_ of those, but instead will focus on the directories `prime-router/src/main/kotlin/fhirengine/engine/` and `prime-router/src/test/kotlin/fhirengine/engine/`. All IDE warnings and code smells in those directories should either be addressed, or reasons for them not being addressed should be noted in this ticket or elsewhere.

### Risks/Impacts/Considerations
None

### Dev Notes
Some of the code smells are undoubtedly due to unnecessarily strict checks. We should work with DevOps to tune some of those settings.

### Acceptance Criteria
- [ ] [This](https://sonarcloud.io/project/issues?directories=prime-router%2Fsrc%2Fmain%2Fkotlin%2Ffhirengine%2Fengine&resolved=false&types=CODE_SMELL&id=CDCgov_prime-data-hub) and [this](https://sonarcloud.io/project/issues?directories=prime-router%2Fsrc%2Ftest%2Fkotlin%2Ffhirengine%2Fengine%2FfhirRouterTests&resolved=false&types=CODE_SMELL&id=CDCgov_prime-data-hub) directory show 0 major and higher code smells. All minor code smells remaining have some explanation in this ticket or in the resulting PR.
- [ ] IntelliJ warnings have all been addressed in those directories as well.
- [ ] Any SonarCloud settings changes that are needed have been addressed by the DevOps team or have tickets open for them. (ticket created here: https://github.com/CDCgov/prime-reportstream/issues/10049)

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9981?planning-poker) with Zenhub @arnejduranovic @jimmyfagan @mkalish @jack-h-wang @JessicaWNava @luis-pabon-tf @thetaurean
