### ISSUE TITLE
Update Chromatic with the latest RS Storybook components

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9987]
## Problem statement

As Design team gets ready to build wireframes of the new website pages, it would be useful to have the RS Storybook instance updated and be a source of truth for their wireframes/designs. This will also assist Engineering in knowing exactly what components to use and how to style them as we move forward into creating those new pages. 

## What you need to know

- [RS Public Storybook instance](https://6419b81d4a47163c3050f14a-lmvhzszsio.chromatic.com/?path=/story/components-table--borderless)
- [List of Components and Typography](https://docs.google.com/document/d/1VfziI-oNyQ2B9hTWgmoCKT7plHrTVSggESYWXoiQiqY/edit)
- ...
## Acceptance criteria

- [ ] All components and typography on local Storybook instance appear in the public RS Storybook instance (above)
- [ ] Document process for syncing/updating Chromatic for keeping the public RS Storybook instance accurately up to date

## To do

- [ ] ...

**Comment by etanb** [comment]
Just fyi, bumping the point estimate on this since I'll be adding some context/instructions to our README + discovered a better Github workflow on how to update our Chromatic but will take longer to implement cc @Andrey-Glazkv @KeithNava

**Comment by KeithNava** [comment]
> Just fyi, bumping the point estimate on this since I'll be adding some context/instructions to our README + discovered a better Github workflow on how to update our Chromatic but will take longer to implement cc @Andrey-Glazkv @KeithNava

Thanks for the heads up @etanb! What's the TLDR for the Github workflow? Let me know if there's anything I can do to help
